Doxygen: InheritanceListContext Class Reference
InheritanceListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
Returns the number of elements in the list.
virtual TemplateVariant at (size_t index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
Creates a new iterator for this list.
InheritanceListContext (const BaseClassList &list, bool baseClasses)
virtual ~InheritanceListContext ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()=default
Destroys the list.
Static Public Member Functions
static TemplateListIntfPtr alloc (const BaseClassList &list, bool baseClasses)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Public Types inherited from TemplateListIntf
using ConstIteratorPtr = std::unique_ptr< ConstIterator >
Detailed Description
Definition at line 980 of file context.h.
Constructor & Destructor Documentation
InheritanceListContext()
InheritanceListContext::InheritanceListContext (const BaseClassList & list, bool baseClasses)
Definition at line 7557 of file context.cpp.
                                                                                          : p(std::make_unique<Private>())
{
  for (const auto &bcd : list)
  {
    const ClassDef *cd=bcd.classDef;
    QCString name;
    if (baseClasses)
    {
      name = insertTemplateSpecifierInScope(
          cd->displayName(),bcd.templSpecifiers);
    }
    else
    {
      name = cd->displayName();
    }
    //printf("InheritanceListContext: adding %s baseClass=%d\n",qPrint(name),baseClasses);
    p->addClass(cd,name);
  }
}
References ClassDef::displayName(), insertTemplateSpecifierInScope(), and p.
~InheritanceListContext()
InheritanceListContext::~InheritanceListContext () virtual
Definition at line 7577 of file context.cpp.
{
}
Member Function Documentation
alloc()
static TemplateListIntfPtr InheritanceListContext::alloc (const BaseClassList & list, bool baseClasses) inline static
Definition at line 983 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<InheritanceListContext>(list,baseClasses)); }
Referenced by ClassContext::Private::createInheritedByList(), and ClassContext::Private::createInheritsList().
at()
TemplateVariant InheritanceListContext::at (size_t index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 7587 of file context.cpp.
{
  return p->at(index);
}
References p.
count()
size_t InheritanceListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 7582 of file context.cpp.
{
  return p->count();
}
References p.
createIterator()
TemplateListIntf::ConstIteratorPtr InheritanceListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 7592 of file context.cpp.
{
  return p->createIterator();
}
References p.
Member Data Documentation
p
std::unique_ptr<Private> InheritanceListContext::p private
Definition at line 996 of file context.h.
Referenced by at(), count(), createIterator(), and InheritanceListContext().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/context.h
/home/runner/work/doxygen/doxygen/src/context.cpp