Doxygen: ConceptDefMutable Class Reference
ConceptDefMutable Class Reference abstract
#include <src/conceptdef.h>
Public Member Functions
virtual void setIncludeFile (FileDef *fd, const QCString &incName, bool local, bool force)=0
virtual void setTemplateArguments (const ArgumentList &al)=0
virtual void setNamespace (NamespaceDef *nd)=0
virtual void setFileDef (FileDef *fd)=0
virtual void writeTagFile (TextStream &)=0
virtual void writeDocumentation (OutputList &ol)=0
virtual void setInitializer (const QCString &init)=0
virtual void findSectionsInDocumentation ()=0
virtual void setGroupId (int id)=0
virtual void setModuleDef (ModuleDef *mod)=0
Public Member Functions inherited from DefinitionMutable
virtual void setName (const QCString &name)=0
virtual void setId (const QCString &name)=0
virtual void setDefFile (const QCString &df, int defLine, int defColumn)=0
virtual void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)=0
virtual void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)=0
virtual void setInbodyDocumentation (const QCString &d, const QCString &docFile, int docLine)=0
virtual void setReference (const QCString &r)=0
virtual void setBodySegment (int defLine, int bls, int ble)=0
virtual void setBodyDef (const FileDef *fd)=0
virtual void setRefItems (const RefItemVector &sli)=0
virtual void setOuterScope (Definition *d)=0
virtual void setHidden (bool b)=0
virtual void setArtificial (bool b)=0
virtual void setExported (bool b)=0
virtual void setLanguage (SrcLangExt lang)=0
virtual void setLocalName (const QCString &name)=0
virtual void makePartOfGroup (GroupDef *gd)=0
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)=0
virtual void addSourceReferencedBy (MemberDef *d, const QCString &sourceRefName)=0
virtual void addSourceReferences (MemberDef *d, const QCString &sourceRefName)=0
virtual void mergeRefItems (Definition *d)=0
virtual void addInnerCompound (Definition *d)=0
virtual void mergeReferences (const Definition *other)=0
virtual void mergeReferencedBy (const Definition *other)=0
virtual void computeTooltip ()=0
virtual void writeSourceDef (OutputList &ol) const =0
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const =0
virtual bool hasSourceRefs () const =0
virtual bool hasSourceReffedBy () const =0
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const =0
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const =0
virtual void writeNavigationPath (OutputList &ol) const =0
virtual void writeQuickMemberLinks (OutputList &, const MemberDef *) const =0
virtual void writeSummaryLinks (OutputList &) const =0
virtual void writeDocAnchorsToTagFile (TextStream &) const =0
virtual void writeToc (OutputList &ol, const LocalToc &lt) const =0
Public Member Functions inherited from ConceptDef
virtual bool hasDetailedDescription () const =0
virtual const IncludeInfo * includeInfo () const =0
virtual ArgumentList getTemplateParameterList () const =0
virtual QCString initializer () const =0
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const =0
virtual const NamespaceDef * getNamespaceDef () const =0
virtual const FileDef * getFileDef () const =0
virtual const ModuleDef * getModuleDef () const =0
virtual QCString title () const =0
virtual int groupId () const =0
Public Member Functions inherited from Definition
virtual DefType definitionType () const =0
virtual CodeSymbolType codeSymbolType () const =0
virtual bool isAlias () const =0
virtual const QCString & name () const =0
virtual bool isAnonymous () const =0
virtual QCString displayName (bool includeScope=TRUE) const =0
virtual const QCString & localName () const =0
virtual QCString qualifiedName () const =0
virtual QCString symbolName () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString getSourceFileBase () const =0
virtual QCString getSourceAnchor () const =0
virtual QCString documentation () const =0
virtual int docLine () const =0
virtual QCString docFile () const =0
virtual QCString briefDescription (bool abbreviate=FALSE) const =0
virtual QCString briefDescriptionAsTooltip () const =0
virtual int briefLine () const =0
virtual QCString inbodyDocumentation () const =0
virtual QCString inbodyFile () const =0
virtual int inbodyLine () const =0
virtual QCString briefFile () const =0
virtual QCString getDefFileName () const =0
virtual QCString getDefFileExtension () const =0
virtual int getDefLine () const =0
virtual int getDefColumn () const =0
virtual bool hasDocumentation () const =0
virtual bool hasUserDocumentation () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isVisibleInProject () const =0
virtual bool isVisible () const =0
virtual bool isHidden () const =0
virtual bool isArtificial () const =0
virtual bool isExported () const =0
virtual QCString getReference () const =0
virtual bool isReference () const =0
virtual QCString externalReference (const QCString &relPath) const =0
virtual int getStartDefLine () const =0
virtual int getStartBodyLine () const =0
virtual int getEndBodyLine () const =0
virtual const FileDef * getBodyDef () const =0
virtual SrcLangExt getLanguage () const =0
Returns the programming language this definition was written in.
virtual const GroupList & partOfGroups () const =0
virtual bool isLinkableViaGroup () const =0
virtual const RefItemVector & xrefListItems () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual Definition * getOuterScope () const =0
virtual const MemberVector & getReferencesMembers () const =0
virtual const MemberVector & getReferencedByMembers () const =0
virtual bool hasSections () const =0
virtual bool hasSources () const =0
virtual bool hasBriefDescription () const =0
returns TRUE if this class has a brief description
virtual QCString id () const =0
virtual const SectionRefs & getSectionRefs () const =0
returns the section dictionary, only of importance for pagedef
virtual QCString navigationPathAsString () const =0
virtual QCString pathFragment () const =0
virtual void _setSymbolName (const QCString &name)=0
virtual QCString _symbolName () const =0
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Detailed Description
Definition at line 44 of file conceptdef.h.
Member Function Documentation
findSectionsInDocumentation()
virtual void ConceptDefMutable::findSectionsInDocumentation () pure virtual
Implemented in ConceptDefImpl.
Referenced by findSectionsInDocumentation().
setFileDef()
virtual void ConceptDefMutable::setFileDef (FileDef * fd) pure virtual
Implemented in ConceptDefImpl.
Referenced by addConceptToContext().
setGroupId()
virtual void ConceptDefMutable::setGroupId (int id) pure virtual
Implemented in ConceptDefImpl.
Referenced by addConceptToContext().
setIncludeFile()
virtual void ConceptDefMutable::setIncludeFile (FileDef * fd, const QCString & incName, bool local, bool force) pure virtual
Implemented in ConceptDefImpl.
setInitializer()
virtual void ConceptDefMutable::setInitializer (const QCString & init) pure virtual
Implemented in ConceptDefImpl.
Referenced by addConceptToContext().
setModuleDef()
virtual void ConceptDefMutable::setModuleDef (ModuleDef * mod) pure virtual
Implemented in ConceptDefImpl.
References Definition::name().
setNamespace()
virtual void ConceptDefMutable::setNamespace (NamespaceDef * nd) pure virtual
Implemented in ConceptDefImpl.
setTemplateArguments()
virtual void ConceptDefMutable::setTemplateArguments (const ArgumentList & al) pure virtual
Implemented in ConceptDefImpl.
Referenced by addConceptToContext().
writeDocumentation()
virtual void ConceptDefMutable::writeDocumentation (OutputList & ol) pure virtual
Implemented in ConceptDefImpl.
Referenced by generateConceptDocs(), and generateNamespaceConceptDocs().
writeTagFile()
virtual void ConceptDefMutable::writeTagFile (TextStream &) pure virtual
Implemented in ConceptDefImpl.
Referenced by writeTagFile().
The documentation for this class was generated from the following file:
src/conceptdef.h