Doxygen: Debug Class Reference
Debug Class Reference
Class containing a print function for diagnostics.
#include <src/debug.h>
Public Types
enum DebugMask : uint64_t {
Quiet = 0x00'0000ULL , Preprocessor = 0x00'0001ULL , CommentCnv = 0x00'0002ULL , CommentScan = 0x00'0004ULL ,
Formula = 0x00'0008ULL , PrintTree = 0x00'0010ULL , Time = 0x00'0020ULL , ExtCmd = 0x00'0040ULL ,
Markdown = 0x00'0080ULL , FilterOutput = 0x00'0100ULL , Plantuml = 0x00'0200ULL , FortranFixed2Free = 0x00'0400ULL ,
Cite = 0x00'0800ULL , NoLineNo = 0x00'1000ULL , Rtf = 0x00'2000ULL , Qhp = 0x00'4000ULL ,
Tag = 0x00'8000ULL , Alias = 0x01'0000ULL , Entries = 0x02'0000ULL , Sections = 0x04'0000ULL ,
Stderr = 0x08'0000ULL , Layout = 0x10'0000ULL , Lex = 0x0000'FFFF'FF00'0000ULL , Lex_code = 0x0000'0000'0100'0000ULL ,
Lex_commentcnv = 0x0000'0000'0200'0000ULL , Lex_commentscan = 0x0000'0000'0400'0000ULL , Lex_configimpl = 0x0000'0000'0800'0000ULL , Lex_constexp = 0x0000'0000'1000'0000ULL ,
Lex_declinfo = 0x0000'0000'2000'0000ULL , Lex_defargs = 0x0000'0000'4000'0000ULL , Lex_doctokenizer = 0x0000'0000'8000'0000ULL , Lex_fortrancode = 0x0000'0001'0000'0000ULL ,
Lex_fortranscanner = 0x0000'0002'0000'0000ULL , Lex_lexcode = 0x0000'0004'0000'0000ULL , Lex_lexscanner = 0x0000'0008'0000'0000ULL , Lex_pre = 0x0000'0010'0000'0000ULL ,
Lex_pycode = 0x0000'0020'0000'0000ULL , Lex_pyscanner = 0x0000'0040'0000'0000ULL , Lex_scanner = 0x0000'0080'0000'0000ULL , Lex_sqlcode = 0x0000'0100'0000'0000ULL ,
Lex_vhdlcode = 0x0000'0200'0000'0000ULL , Lex_xml = 0x0000'0400'0000'0000ULL , Lex_xmlcode = 0x0000'0800'0000'0000ULL
}
Static Public Member Functions
static void print (DebugMask mask, int prio, const char *fmt,...)
static bool setFlagStr (const QCString &label)
static void setFlag (const DebugMask mask)
static void clearFlag (const DebugMask mask)
static bool isFlagSet (const DebugMask mask)
static void printFlags ()
static void setPriority (int p)
static void startTimer ()
static double elapsedTime ()
Static Private Attributes
static DebugMask curMask = Debug::Quiet
static int curPrio = 0
Detailed Description
Class containing a print function for diagnostics.
Definition at line 24 of file debug.h.
Member Enumeration Documentation
DebugMask
enum Debug::DebugMask : uint64_t
Enumerator
Quiet
Preprocessor
CommentCnv
CommentScan
Formula
PrintTree
Time
ExtCmd
Markdown
FilterOutput
Plantuml
FortranFixed2Free
Cite
NoLineNo
Rtf
Qhp
Tag
Alias
Entries
Sections
Stderr
Layout
Lex
Lex_code
Lex_commentcnv
Lex_commentscan
Lex_configimpl
Lex_constexp
Lex_declinfo
Lex_defargs
Lex_doctokenizer
Lex_fortrancode
Lex_fortranscanner
Lex_lexcode
Lex_lexscanner
Lex_pre
Lex_pycode
Lex_pyscanner
Lex_scanner
Lex_sqlcode
Lex_vhdlcode
Lex_xml
Lex_xmlcode
Definition at line 27 of file debug.h.
                   : uint64_t {
                     Quiet             =             0x00'0000ULL,
                     Preprocessor      =             0x00'0001ULL,
                     CommentCnv        =             0x00'0002ULL,
                     CommentScan       =             0x00'0004ULL,
                     Formula           =             0x00'0008ULL,
                     PrintTree         =             0x00'0010ULL,
                     Time              =             0x00'0020ULL,
                     ExtCmd            =             0x00'0040ULL,
                     Markdown          =             0x00'0080ULL,
                     FilterOutput      =             0x00'0100ULL,
                     Plantuml          =             0x00'0200ULL,
                     FortranFixed2Free =             0x00'0400ULL,
                     Cite              =             0x00'0800ULL,
                     NoLineNo          =             0x00'1000ULL,
                     Rtf               =             0x00'2000ULL,
                     Qhp               =             0x00'4000ULL,
                     Tag               =             0x00'8000ULL,
                     Alias             =             0x01'0000ULL,
                     Entries           =             0x02'0000ULL,
                     Sections          =             0x04'0000ULL,
                     Stderr            =             0x08'0000ULL,
                     Layout            =             0x10'0000ULL,
                     Lex               = 0x0000'FFFF'FF00'0000ULL, // all scanners combined
                     Lex_code          = 0x0000'0000'0100'0000ULL,
                     Lex_commentcnv    = 0x0000'0000'0200'0000ULL,
                     Lex_commentscan   = 0x0000'0000'0400'0000ULL,
                     Lex_configimpl    = 0x0000'0000'0800'0000ULL,
                     Lex_constexp      = 0x0000'0000'1000'0000ULL,
                     Lex_declinfo      = 0x0000'0000'2000'0000ULL,
                     Lex_defargs       = 0x0000'0000'4000'0000ULL,
                     Lex_doctokenizer  = 0x0000'0000'8000'0000ULL,
                     Lex_fortrancode   = 0x0000'0001'0000'0000ULL,
                     Lex_fortranscanner= 0x0000'0002'0000'0000ULL,
                     Lex_lexcode       = 0x0000'0004'0000'0000ULL,
                     Lex_lexscanner    = 0x0000'0008'0000'0000ULL,
                     Lex_pre           = 0x0000'0010'0000'0000ULL,
                     Lex_pycode        = 0x0000'0020'0000'0000ULL,
                     Lex_pyscanner     = 0x0000'0040'0000'0000ULL,
                     Lex_scanner       = 0x0000'0080'0000'0000ULL,
                     Lex_sqlcode       = 0x0000'0100'0000'0000ULL,
                     Lex_vhdlcode      = 0x0000'0200'0000'0000ULL,
                     Lex_xml           = 0x0000'0400'0000'0000ULL,
                     Lex_xmlcode       = 0x0000'0800'0000'0000ULL
                   };
Member Function Documentation
clearFlag()
void Debug::clearFlag (const DebugMask mask) static
Definition at line 125 of file debug.cpp.
{
  curMask = static_cast<DebugMask>(curMask & ~mask);
}
References curMask.
Referenced by devUsage(), generateOutput(), Statistics::print(), usage(), and version().
elapsedTime()
double Debug::elapsedTime () static
Definition at line 204 of file debug.cpp.
{
  return g_runningTime.elapsedTimeS();
}
References Timer::elapsedTimeS(), and g_runningTime.
Referenced by generateOutput(), and msg().
isFlagSet()
bool Debug::isFlagSet (const DebugMask mask) static
Definition at line 135 of file debug.cpp.
{
  return (curMask & mask)!=0;
}
References curMask.
Referenced by CCodeParser::CCodeParser(), CommentScanner::CommentScanner(), convertCppComments(), COutlineParser::COutlineParser(), determineInkscapeVersion(), DocTokenizer::DocTokenizer(), FortranCodeParser::FortranCodeParser(), FormulaManager::generateImages(), generateOutput(), CitationManager::generatePage(), LayoutDocManager::init(), LexCodeParser::LexCodeParser(), LexOutlineParser::LexOutlineParser(), msg(), ConstExpressionParser::parse(), LayoutDocManager::parse(), parseFuncDecl(), ConfigImpl::parseString(), parseTagFile(), preProcessFile(), RTFGenerator::preProcessFileInplace(), DebugLex::print(), print(), print(), Statistics::print(), printNavLayout(), printNavTree(), printSectionsTree(), FortranOutlineParser::Private::Private(), Preprocessor::processFile(), PythonCodeParser::PythonCodeParser(), PythonOutlineParser::PythonOutlineParser(), readIncludeFile(), runHtmlHelpCompiler(), runQHelpGenerator(), SQLCodeParser::SQLCodeParser(), stringToArgumentList(), validatingParseDoc(), validatingParseText(), VHDLCodeParser::VHDLCodeParser(), writeIndent(), and XMLCodeParser::XMLCodeParser().
print()
void Debug::print (DebugMask mask, int prio, const char * fmt, ...) static
Definition at line 81 of file debug.cpp.
{
  if ((curMask&mask) && prio<=curPrio)
  {
    va_list args;
    va_start(args,fmt);
    vfprintf(g_debugFile, fmt, args);
    va_end(args);
  }
}
References curMask, curPrio, and g_debugFile.
Referenced by FileDefImpl::acquireFileVersion(), addValidAliasToMap(), convertCppComments(), anonymous_namespace{tagreader.cpp}::TagFileParser::dump(), expandAlias(), FilterCache::getFileContentsPipe(), PlantumlManager::insert(), CommentScanner::parseCommentBlock(), MarkdownOutlineParser::parseInput(), parseMain(), print(), print(), printLayout(), printNavLayout(), printNavTree(), printSectionsTree(), Markdown::process(), Preprocessor::processFile(), readCodeFragment(), readIncludeFile(), readInputFile(), resolveAliasCmd(), rtfFormatBmkStr(), PlantumlManager::run(), runPlantumlContent(), runQHelpGenerator(), Portable::system(), and PlantumlManager::writePlantUMLSource().
printFlags()
void Debug::printFlags () static
Definition at line 140 of file debug.cpp.
{
  for (const auto &v : s_labels)
  {
     msg("\t%s\n",v.first.c_str());
  }
}
References msg(), and s_labels.
Referenced by devUsage().
setFlag()
void Debug::setFlag (const DebugMask mask) static
Definition at line 120 of file debug.cpp.
{
  curMask = static_cast<DebugMask>(curMask | mask);
}
References curMask.
Referenced by generateOutput(), and Statistics::print().
setFlagStr()
bool Debug::setFlagStr (const QCString & label) static
Definition at line 106 of file debug.cpp.
{
  uint64_t retVal = labelToEnumValue(lab);
  if (retVal == Debug::Stderr)
  {
    g_debugFile = stderr;
  }
  else
  {
    curMask = static_cast<DebugMask>(curMask | retVal);
  }
  return retVal!=0;
}
References curMask, g_debugFile, labelToEnumValue(), and Stderr.
Referenced by readConfiguration().
setPriority()
void Debug::setPriority (int p) static
Definition at line 130 of file debug.cpp.
{
  curPrio = p;
}
References curPrio.
startTimer()
void Debug::startTimer () static
Definition at line 199 of file debug.cpp.
{
  g_runningTime.start();
}
References g_runningTime, and Timer::start().
Referenced by initDoxygen().
Member Data Documentation
curMask
Debug::DebugMask Debug::curMask = Debug::Quiet static private
Definition at line 85 of file debug.h.
Referenced by clearFlag(), isFlagSet(), print(), setFlag(), and setFlagStr().
curPrio
int Debug::curPrio = 0 static private
Definition at line 86 of file debug.h.
Referenced by print(), and setPriority().
The documentation for this class was generated from the following files:
src/debug.h
src/debug.cpp