Doxygen: src/message.cpp File Reference
message.cpp File Reference
#include <cstdio>
#include <cstdlib>
#include <mutex>
#include <atomic>
#include "config.h"
#include "debug.h"
#include "portable.h"
#include "message.h"
#include "doxygen.h"
#include "fileinfo.h"
#include "dir.h"
Functions
void initWarningFormat ()
void msg (const char *fmt,...)
static void format_warn (const QCString &file, int line, const QCString &text)
static void handle_warn_as_error ()
static void do_warn (bool enabled, const QCString &file, int line, const char *prefix, const char *fmt, va_list args)
QCString warn_line (const QCString &file, int line)
void warn_ (const QCString &file, int line, const char *fmt,...)
void va_warn (const QCString &file, int line, const char *fmt, va_list args)
void warn_undoc_ (const QCString &file, int line, const char *fmt,...)
void warn_incomplete_doc_ (const QCString &file, int line, const char *fmt,...)
void warn_doc_error_ (const QCString &file, int line, const char *fmt,...)
void warn_uncond_ (const char *fmt,...)
void err_ (const char *fmt,...)
void err_full_ (const QCString &file, int line, const char *fmt,...)
void term_ (const char *fmt,...)
void warn_flush ()
void finishWarnExit ()
Variables
static QCString g_warnFormat
static QCString g_warnLineFormat
static const char * g_warningStr = "warning: "
static const char * g_errorStr = "error: "
static FILE * g_warnFile = stderr
static WARN_AS_ERROR_t g_warnBehavior = WARN_AS_ERROR_t::NO
static QCString g_warnlogFile
static bool g_warnlogTemp = false
static std::atomic_bool g_warnStat = false
static std::mutex g_mutex
Function Documentation
do_warn()
static void do_warn (bool enabled, const QCString & file, int line, const char * prefix, const char * fmt, va_list args) static
Definition at line 176 of file message.cpp.
{
  if (!enabled) return; // warning type disabled
  va_list argsCopy;
  va_copy(argsCopy, args);
  size_t l=0;
  if (prefix)
  {
    l=strlen(prefix);
  }
  // determine needed buffersize based on:
  // format + arguments
  // prefix
  // 1 position for `\0`
  size_t bufSize = vsnprintf(nullptr, 0, fmt, args) + l;
  QCString text(bufSize, QCString::ExplicitSize);
  if (prefix)
  {
    qstrncpy(text.rawData(),prefix,bufSize);
  }
  vsnprintf(text.rawData()+l, bufSize-l+1, fmt, argsCopy);
  text[bufSize]='\0';
  format_warn(file,line,text);
  va_end(argsCopy);
}
References QCString::ExplicitSize, format_warn(), prefix, qstrncpy(), and QCString::rawData().
Referenced by err_full_(), va_warn(), warn_(), warn_doc_error_(), warn_incomplete_doc_(), and warn_undoc_().
err_()
void err_ (const char * fmt, ...)
Definition at line 263 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  vfprintf(g_warnFile, (QCString(g_errorStr) + fmt).data(), args);
  va_end(args);
  handle_warn_as_error();
}
References g_errorStr, g_warnFile, and handle_warn_as_error().
Referenced by err_().
err_full_()
void err_full_ (const QCString & file, int line, const char * fmt, ...) extern
Definition at line 272 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(TRUE, file, line, g_errorStr, fmt, args);
  va_end(args);
}
References do_warn(), g_errorStr, and TRUE.
Referenced by err_full_().
finishWarnExit()
void finishWarnExit () extern
Definition at line 310 of file message.cpp.
{
  fflush(stdout);
  if (g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT && g_warnlogFile != "-")
  {
    Portable::fclose(g_warnFile);
    g_warnFile = nullptr;
  }
  if (g_warnStat && g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT && g_warnlogFile != "-")
  {
    std::ifstream warnFile = Portable::openInputStream(g_warnlogFile);
    if (!warnFile.is_open())
    {
      g_warnFile = stderr;
      err("Cannot open warnings file '%s' for reading\n",g_warnlogFile.data());
    }
    else
    {
      std::string line;
      while (getline(warnFile,line))
      {
        fprintf(stderr,"%s\n",line.c_str());
      }
      warnFile.close();
    }
  }
  if (g_warnlogTemp) Portable::unlink(g_warnlogFile);
  if (g_warnStat && (g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS ||
                     g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT))
  {
    exit(1);
  }
}
References err, Portable::fclose(), g_warnBehavior, g_warnFile, g_warnlogFile, g_warnlogTemp, g_warnStat, Portable::openInputStream(), and Portable::unlink().
Referenced by generateOutput(), and term_().
format_warn()
static void format_warn (const QCString & file, int line, const QCString & text) static
Definition at line 114 of file message.cpp.
{
  QCString fileSubst = file.isEmpty() ? "<unknown>" : file;
  QCString lineSubst; lineSubst.setNum(line);
  QCString textSubst = text;
  QCString versionSubst;
  // substitute markers by actual values
  QCString msgText =
      substitute(
        substitute(
          substitute(
            substitute(
              g_warnFormat,
              "$file",fileSubst
            ),
            "$line",lineSubst
          ),
          "$version",versionSubst
        ),
        "$text",textSubst
      );
  if (g_warnBehavior == WARN_AS_ERROR_t::YES)
  {
    msgText += " (warning treated as error, aborting now)";
  }
  msgText += '\n';
  {
    std::unique_lock<std::mutex> lock(g_mutex);
    // print resulting message
    fwrite(msgText.data(),1,msgText.length(),g_warnFile);
  }
  if (g_warnBehavior == WARN_AS_ERROR_t::YES)
  {
    if (g_warnFile != stderr && !Config_getBool(QUIET))
    {
      msg("See '%s' for the reason of termination.\n",qPrint(g_warnlogFile));
    }
    exit(1);
  }
  g_warnStat = true;
}
References Config_getBool, QCString::data(), g_mutex, g_warnBehavior, g_warnFile, g_warnFormat, g_warnlogFile, g_warnStat, QCString::isEmpty(), QCString::length(), msg(), qPrint(), QCString::setNum(), and substitute().
Referenced by do_warn().
handle_warn_as_error()
static void handle_warn_as_error () static
Definition at line 157 of file message.cpp.
{
  if (g_warnBehavior == WARN_AS_ERROR_t::YES)
  {
    {
      std::unique_lock<std::mutex> lock(g_mutex);
      QCString msgText = " (warning treated as error, aborting now)\n";
      fwrite(msgText.data(),1,msgText.length(),g_warnFile);
      if (g_warnFile != stderr && !Config_getBool(QUIET))
      {
        // cannot use `msg` due to the mutex
        fprintf(stdout,"See '%s' for the reason of termination.\n",qPrint(g_warnlogFile));
      }
    }
    exit(1);
  }
  g_warnStat = true;
}
References Config_getBool, QCString::data(), g_mutex, g_warnBehavior, g_warnFile, g_warnlogFile, g_warnStat, QCString::length(), and qPrint().
Referenced by err_(), and warn_uncond_().
initWarningFormat()
void initWarningFormat ()
Definition at line 41 of file message.cpp.
{
  g_warnFormat = Config_getString(WARN_FORMAT);
  g_warnLineFormat = Config_getString(WARN_LINE_FORMAT);
  g_warnBehavior = Config_getEnum(WARN_AS_ERROR);
  g_warnlogFile = Config_getString(WARN_LOGFILE);
  if (g_warnlogFile.isEmpty() && g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT)
  {
    uint32_t pid = Portable::pid();
    g_warnlogFile.sprintf("doxygen_warnings_temp_%d.tmp",pid);
    g_warnlogTemp = true;
  }
  if (!g_warnlogFile.isEmpty())
  {
    if (g_warnlogFile == "-")
    {
      g_warnFile = stdout;
    }
    else
    {
      FileInfo fi(g_warnlogFile.str());
      Dir d(fi.dirPath().c_str());
      if (!d.exists() && !d.mkdir(fi.dirPath().c_str()))
      {
        // point it to something valid, because warn() relies on it
        g_warnFile = stderr;
        err("Cannot create directory for '%s', redirecting 'WARN_LOGFILE' output to 'stderr'\n",g_warnlogFile.data());
      }
      else if (!(g_warnFile = Portable::fopen(g_warnlogFile,"w")))
      {
        // point it to something valid, because warn() relies on it
        g_warnFile = stderr;
        err("Cannot open '%s' for writing, redirecting 'WARN_LOGFILE' output to 'stderr'\n",g_warnlogFile.data());
      }
    }
  }
  else
  {
    g_warnFile = stderr;
  }
  if (g_warnBehavior != WARN_AS_ERROR_t::NO)
  {
    g_warningStr = g_errorStr;
  }
  // make sure the g_warnFile is closed in case we call exit and it is still open
  std::atexit([](){
      if (g_warnFile && g_warnFile!=stderr && g_warnFile!=stdout)
      {
        Portable::fclose(g_warnFile);
        g_warnFile = nullptr;
      }
  });
}
References Config_getEnum, Config_getString, FileInfo::dirPath(), err, Dir::exists(), Portable::fclose(), Portable::fopen(), g_errorStr, g_warnBehavior, g_warnFile, g_warnFormat, g_warningStr, g_warnLineFormat, g_warnlogFile, g_warnlogTemp, Dir::mkdir(), and Portable::pid().
Referenced by checkConfiguration(), and term_().
msg()
void msg (const char * fmt, ...)
Definition at line 98 of file message.cpp.
{
  if (!Config_getBool(QUIET))
  {
    std::unique_lock<std::mutex> lock(g_mutex);
    if (Debug::isFlagSet(Debug::Time))
    {
      printf("%.3f sec: ",(static_cast<double>(Debug::elapsedTime())));
    }
    va_list args;
    va_start(args, fmt);
    vfprintf(stdout, fmt, args);
    va_end(args);
  }
}
References Config_getBool, Debug::elapsedTime(), g_mutex, Debug::isFlagSet(), and Debug::Time.
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), FileDefImpl::acquireFileVersion(), adjustConfiguration(), Statistics::begin(), checkAndUpdatePath(), devUsage(), anonymous_namespace{tagreader.cpp}::TagFileParser::error(), LayoutParser::error(), exitDoxygen(), format_warn(), generateConceptDocs(), generateConfigFile(), generateDocsForClassList(), generateExampleDocs(), generateFileDocs(), generateFileSources(), generateFormula(), generateNamespaceClassDocs(), generateNamespaceConceptDocs(), generateNamespaceDocs(), generateOutput(), generatePageDocs(), generateSqlite3(), generateXML(), generateXMLForClass(), LayoutDocManager::init(), FormulaManager::initFromRepository(), initializeTables(), initializeViews(), loadExtensions(), loadStylesheet(), LayoutDocManager::parse(), XMLParser::parse(), parseFile(), parseFilesMultiThreading(), parseInput(), VHDLOutlineParser::parseInput(), parseMain(), parseMain(), parseMain(), parseMain(), parseTagFile(), Statistics::print(), Debug::printFlags(), processData(), readDir(), readIncludeFile(), readTagFile(), reportError(), DotManager::run(), runPlantumlContent(), AutoTrace::setExit(), setTranslator(), stopDoxygen(), LayoutNavEntry::url(), usage(), version(), DirDefImpl::writeDirectoryGraph(), ClassDefImpl::writeDocumentationForInnerClasses(), GroupDefImpl::writeGroupGraph(), writeIndex(), and writeIndexHierarchyEntries().
term_()
void term_ (const char * fmt, ...)
Definition at line 280 of file message.cpp.
{
  {
    std::unique_lock<std::mutex> lock(g_mutex);
    va_list args;
    va_start(args, fmt);
    vfprintf(g_warnFile, (QCString(g_errorStr) + fmt).data(), args);
    va_end(args);
    if (g_warnFile != stderr)
    {
      size_t l = strlen(g_errorStr);
      for (size_t i=0; i<l; i++) fprintf(g_warnFile, " ");
      fprintf(g_warnFile, "%s\n", "Exiting...");
      if (!Config_getBool(QUIET))
      {
        // cannot use `msg` due to the mutex
        fprintf(stdout,"See '%s' for the reason of termination.\n",qPrint(g_warnlogFile));
      }
    }
  }
  exit(1);
}
References Config_getBool, g_errorStr, g_mutex, g_warnFile, g_warnlogFile, and qPrint().
Referenced by term_().
va_warn()
void va_warn (const QCString & file, int line, const char * fmt, va_list args)
Definition at line 225 of file message.cpp.
{
  do_warn(Config_getBool(WARNINGS), file, line, g_warningStr, fmt, args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by warn_().
warn_()
void warn_ (const QCString & file, int line, const char * fmt, ...)
Definition at line 217 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARNINGS), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by anonymous_namespace{tagreader.cpp}::TagFileParser::error(), anonymous_namespace{tagreader.cpp}::TagFileParser::p_warn(), anonymous_namespace{tagreader.cpp}::TagFileParser::p_warn(), and warn_().
warn_doc_error_()
void warn_doc_error_ (const QCString & file, int line, const char * fmt, ...)
Definition at line 246 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARN_IF_DOC_ERROR), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by warn_doc_error_().
warn_flush()
void warn_flush ()
Definition at line 303 of file message.cpp.
{
  fflush(g_warnFile);
}
References g_warnFile.
Referenced by Statistics::end(), and term_().
warn_incomplete_doc_()
void warn_incomplete_doc_ (const QCString & file, int line, const char * fmt, ...)
Definition at line 238 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARN_IF_INCOMPLETE_DOC), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by warn_incomplete_doc_().
warn_line()
QCString warn_line (const QCString & file, int line)
Definition at line 205 of file message.cpp.
{
  QCString fileSubst = file.isEmpty() ? "<unknown>" : file;
  QCString lineSubst; lineSubst.setNum(line);
  return  substitute(
            substitute(
              g_warnLineFormat,
              "$file",fileSubst
            ),
            "$line",lineSubst
          );
}
References g_warnLineFormat, QCString::isEmpty(), QCString::setNum(), and substitute().
Referenced by addMemberFunction(), checkPageRelations(), computePageRelations(), findGlobalMember(), and term_().
warn_uncond_()
void warn_uncond_ (const char * fmt, ...)
Definition at line 254 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  vfprintf(g_warnFile, (QCString(g_warningStr) + fmt).data(), args);
  va_end(args);
  handle_warn_as_error();
}
References g_warnFile, g_warningStr, and handle_warn_as_error().
Referenced by warn_uncond_().
warn_undoc_()
void warn_undoc_ (const QCString & file, int line, const char * fmt, ...)
Definition at line 230 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARN_IF_UNDOCUMENTED), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by warn_undoc_().
Variable Documentation
g_errorStr
const char* g_errorStr = "error: " static
Definition at line 33 of file message.cpp.
Referenced by err_(), err_full_(), initWarningFormat(), and term_().
g_mutex
std::mutex g_mutex static
Definition at line 39 of file message.cpp.
Referenced by format_warn(), handle_warn_as_error(), msg(), and term_().
g_warnBehavior
WARN_AS_ERROR_t g_warnBehavior = WARN_AS_ERROR_t::NO static
Definition at line 35 of file message.cpp.
Referenced by finishWarnExit(), format_warn(), handle_warn_as_error(), and initWarningFormat().
g_warnFile
FILE* g_warnFile = stderr static
Definition at line 34 of file message.cpp.
Referenced by err_(), finishWarnExit(), format_warn(), handle_warn_as_error(), initWarningFormat(), term_(), warn_flush(), and warn_uncond_().
g_warnFormat
QCString g_warnFormat static
Definition at line 30 of file message.cpp.
Referenced by format_warn(), and initWarningFormat().
g_warningStr
const char* g_warningStr = "warning: " static
Definition at line 32 of file message.cpp.
Referenced by initWarningFormat(), va_warn(), warn_(), warn_doc_error_(), warn_incomplete_doc_(), warn_uncond_(), and warn_undoc_().
g_warnLineFormat
QCString g_warnLineFormat static
Definition at line 31 of file message.cpp.
Referenced by initWarningFormat(), and warn_line().
g_warnlogFile
QCString g_warnlogFile static
Definition at line 36 of file message.cpp.
Referenced by finishWarnExit(), format_warn(), handle_warn_as_error(), initWarningFormat(), and term_().
g_warnlogTemp
bool g_warnlogTemp = false static
Definition at line 37 of file message.cpp.
Referenced by finishWarnExit(), and initWarningFormat().
g_warnStat
std::atomic_bool g_warnStat = false static
Definition at line 38 of file message.cpp.
Referenced by finishWarnExit(), format_warn(), and handle_warn_as_error().