Doxygen: src/layout.h File Reference
layout.h File Reference
#include <memory>
#include <vector>
#include "types.h"
#include "construct.h"
Classes
struct LayoutDocEntry
Base class representing a piece of a documentation page.
struct LayoutDocEntrySimple
Represents of a piece of a documentation page without configurable parts.
struct LayoutDocEntrySection
struct LayoutDocEntryMemberDecl
Represents of a member declaration list with configurable title and subtitle.
struct LayoutDocEntryMemberDef
Represents of a member definition list with configurable title.
struct LayoutNavEntry
Base class for the layout of a navigation item at the top of the HTML pages.
class LayoutDocManager
Singleton providing access to the (user configurable) layout of the documentation.
Macros
#define ENTRY_SPECIFICATIONS
#define ESPEC(x)
#define ESPEC(x)
#define NAV_SPECIFICATIONS
#define NSPEC(x, y)
#define NSPEC(x, y)
#define PART_SPECIFICATIONS
#define PSPEC(x, y)
#define PSPEC(x, y)
Typedefs
using LayoutNavEntryList = std::vector< std::unique_ptr<LayoutNavEntry> >
using LayoutDocEntryPtr = std::unique_ptr<LayoutDocEntry>
using LayoutDocEntryList = std::vector<LayoutDocEntryPtr>
Functions
void writeDefaultLayoutFile (const QCString &fileName)
Macro Definition Documentation
ENTRY_SPECIFICATIONS
#define ENTRY_SPECIFICATIONS
Value:
              /* Generic items for all pages */ \
              ESPEC(MemberGroups) \
              ESPEC(MemberDeclStart) ESPEC(MemberDeclEnd) ESPEC(MemberDecl) \
              ESPEC(MemberDefStart) ESPEC(MemberDefEnd) ESPEC(MemberDef) \
              ESPEC(BriefDesc) ESPEC(DetailedDesc) \
              ESPEC(AuthorSection) \
              /* Class specific items */ \
              ESPEC(ClassIncludes) ESPEC(ClassInlineClasses) \
              ESPEC(ClassInheritanceGraph) ESPEC(ClassNestedClasses) \
              ESPEC(ClassCollaborationGraph) ESPEC(ClassAllMembersLink) \
              ESPEC(ClassUsedFiles) \
              /* Concept specific items */ \
              ESPEC(ConceptDefinition) \
              /* Namespace specific items */ \
              ESPEC(NamespaceNestedNamespaces) ESPEC(NamespaceNestedConstantGroups) \
              ESPEC(NamespaceClasses) ESPEC(NamespaceConcepts) ESPEC(NamespaceInterfaces) ESPEC(NamespaceStructs) ESPEC(NamespaceExceptions) \
              ESPEC(NamespaceInlineClasses) \
              /* File specific items */ \
              ESPEC(FileClasses) ESPEC(FileConcepts) ESPEC(FileInterfaces) ESPEC(FileStructs) ESPEC(FileExceptions) ESPEC(FileConstantGroups) ESPEC(FileNamespaces) \
              ESPEC(FileIncludes) ESPEC(FileIncludeGraph) \
              ESPEC(FileIncludedByGraph) ESPEC(FileSourceLink) \
              ESPEC(FileInlineClasses) \
              /* C++20 Modules */ \
              ESPEC(ModuleExports) ESPEC(ModuleClasses) ESPEC(ModuleConcepts) ESPEC(ModuleUsedFiles) \
              /* Group specific items */ \
              ESPEC(GroupClasses) ESPEC(GroupConcepts) ESPEC(GroupModules) ESPEC(GroupInlineClasses) ESPEC(GroupNamespaces) \
              ESPEC(GroupDirs) ESPEC(GroupNestedGroups) ESPEC(GroupFiles) \
              ESPEC(GroupGraph) ESPEC(GroupPageDocs) \
              /* Directory specific items */ \
              ESPEC(DirSubDirs) ESPEC(DirFiles) ESPEC(DirGraph)
Definition at line 36 of file layout.h.
#define ENTRY_SPECIFICATIONS \
              /* Generic items for all pages */ \
              ESPEC(MemberGroups) \
              ESPEC(MemberDeclStart) ESPEC(MemberDeclEnd) ESPEC(MemberDecl) \
              ESPEC(MemberDefStart) ESPEC(MemberDefEnd) ESPEC(MemberDef) \
              ESPEC(BriefDesc) ESPEC(DetailedDesc) \
              ESPEC(AuthorSection) \
              /* Class specific items */ \
              ESPEC(ClassIncludes) ESPEC(ClassInlineClasses) \
              ESPEC(ClassInheritanceGraph) ESPEC(ClassNestedClasses) \
              ESPEC(ClassCollaborationGraph) ESPEC(ClassAllMembersLink) \
              ESPEC(ClassUsedFiles) \
              /* Concept specific items */ \
              ESPEC(ConceptDefinition) \
              /* Namespace specific items */ \
              ESPEC(NamespaceNestedNamespaces) ESPEC(NamespaceNestedConstantGroups) \
              ESPEC(NamespaceClasses) ESPEC(NamespaceConcepts) ESPEC(NamespaceInterfaces) ESPEC(NamespaceStructs) ESPEC(NamespaceExceptions) \
              ESPEC(NamespaceInlineClasses) \
              /* File specific items */ \
              ESPEC(FileClasses) ESPEC(FileConcepts) ESPEC(FileInterfaces) ESPEC(FileStructs) ESPEC(FileExceptions) ESPEC(FileConstantGroups) ESPEC(FileNamespaces) \
              ESPEC(FileIncludes) ESPEC(FileIncludeGraph) \
              ESPEC(FileIncludedByGraph) ESPEC(FileSourceLink) \
              ESPEC(FileInlineClasses) \
              /* C++20 Modules */ \
              ESPEC(ModuleExports) ESPEC(ModuleClasses) ESPEC(ModuleConcepts) ESPEC(ModuleUsedFiles) \
              /* Group specific items */ \
              ESPEC(GroupClasses) ESPEC(GroupConcepts) ESPEC(GroupModules) ESPEC(GroupInlineClasses) ESPEC(GroupNamespaces) \
              ESPEC(GroupDirs) ESPEC(GroupNestedGroups) ESPEC(GroupFiles) \
              ESPEC(GroupGraph) ESPEC(GroupPageDocs) \
              /* Directory specific items */ \
              ESPEC(DirSubDirs) ESPEC(DirFiles) ESPEC(DirGraph)
ESPEC [1/2]
#define ESPEC (x)
Value:
x,
Definition at line 69 of file layout.h.
ESPEC [2/2]
#define ESPEC (x)
Value:
case x: return #x; break;
Definition at line 69 of file layout.h.
NAV_SPECIFICATIONS
#define NAV_SPECIFICATIONS
Definition at line 141 of file layout.h.
#define NAV_SPECIFICATIONS \
      NSPEC(None, = -1) \
      NSPEC(MainPage,) \
      NSPEC(Pages,) \
      NSPEC(Modules,) \
      NSPEC(ModuleList,) \
      NSPEC(ModuleMembers,) \
      NSPEC(Topics,) \
      NSPEC(Namespaces,) \
      NSPEC(NamespaceList,) \
      NSPEC(NamespaceMembers,) \
      NSPEC(Concepts,) \
      NSPEC(Classes,) \
      NSPEC(ClassList,) \
      NSPEC(ClassIndex,) \
      NSPEC(ClassHierarchy,) \
      NSPEC(ClassMembers,) \
      NSPEC(Interfaces,) \
      NSPEC(InterfaceList,) \
      NSPEC(InterfaceIndex,) \
      NSPEC(InterfaceHierarchy,) \
      NSPEC(Structs,) \
      NSPEC(StructList,) \
      NSPEC(StructIndex,) \
      NSPEC(Exceptions,) \
      NSPEC(ExceptionList,) \
      NSPEC(ExceptionIndex,) \
      NSPEC(ExceptionHierarchy,) \
      NSPEC(Files,) \
      NSPEC(FileList,) \
      NSPEC(FileGlobals,) \
      NSPEC(Examples,) \
      NSPEC(User,) \
      NSPEC(UserGroup,)
NSPEC [1/2]
#define NSPEC (x, y)
Value:
x y,
Definition at line 178 of file layout.h.
NSPEC [2/2]
#define NSPEC (x, y)
Value:
case x: return #x; break;
Definition at line 178 of file layout.h.
PART_SPECIFICATIONS
#define PART_SPECIFICATIONS
Value:
  PSPEC(Undefined, = -1)     \
  PSPEC(Class,) PSPEC(Concept,) PSPEC(Namespace,) PSPEC(File,) PSPEC(Group,) PSPEC(Directory,) PSPEC(Module,)       \
  PSPEC(NrParts,)
Definition at line 227 of file layout.h.
#define PART_SPECIFICATIONS \
  PSPEC(Undefined, = -1)     \
  PSPEC(Class,) PSPEC(Concept,) PSPEC(Namespace,) PSPEC(File,) PSPEC(Group,) PSPEC(Directory,) PSPEC(Module,)       \
  PSPEC(NrParts,)
PSPEC [1/2]
#define PSPEC (x, y)
Value:
x y,
Definition at line 238 of file layout.h.
PSPEC [2/2]
#define PSPEC (x, y)
Value:
case x: return #x; break;
Definition at line 238 of file layout.h.
Typedef Documentation
LayoutDocEntryList
using LayoutDocEntryList = std::vector<LayoutDocEntryPtr>
Definition at line 225 of file layout.h.
LayoutDocEntryPtr
using LayoutDocEntryPtr = std::unique_ptr<LayoutDocEntry>
Definition at line 224 of file layout.h.
LayoutNavEntryList
using LayoutNavEntryList = std::vector< std::unique_ptr<LayoutNavEntry> >
Definition at line 136 of file layout.h.
Function Documentation
writeDefaultLayoutFile()
void writeDefaultLayoutFile (const QCString & fileName)
Definition at line 1479 of file layout.cpp.
{
  std::ofstream f;
  if (openOutputFile(fileName,f))
  {
    TextStream t(&f);
    QCString layout_default = ResourceMgr::instance().getAsString("layout_default.xml");
    t << substitute(layout_default,"$doxygenversion",getDoxygenVersion());
  }
  else
  {
    err("Failed to open file %s for writing!\n",qPrint(fileName));
    return;
  }
  f.close();
}
References err, ResourceMgr::getAsString(), ResourceMgr::instance(), openOutputFile(), qPrint(), and substitute().
Referenced by readConfiguration().