Doxygen: Statistics Class Reference
Statistics Class Reference
Classes
struct stat
Public Member Functions
Statistics ()
void begin (const char *name)
void end ()
void print ()
Private Attributes
std::vector< stat > stats
std::chrono::steady_clock::time_point startTime
Detailed Description
Definition at line 216 of file doxygen.cpp.
Constructor & Destructor Documentation
Statistics()
Statistics::Statistics () inline
Definition at line 219 of file doxygen.cpp.
{}
Member Function Documentation
begin()
void Statistics::begin (const char * name) inline
Definition at line 220 of file doxygen.cpp.
    {
      msg("%s", name);
      stats.emplace_back(name,0);
      startTime = std::chrono::steady_clock::now();
    }
References msg(), startTime, and stats.
end()
void Statistics::end () inline
Definition at line 226 of file doxygen.cpp.
    {
      std::chrono::steady_clock::time_point endTime = std::chrono::steady_clock::now();
      stats.back().elapsed = static_cast<double>(std::chrono::duration_cast<
                                std::chrono::microseconds>(endTime - startTime).count())/1000000.0;
      warn_flush();
    }
References startTime, stats, and warn_flush().
print()
void Statistics::print () inline
Definition at line 233 of file doxygen.cpp.
    {
      bool restore=FALSE;
      if (Debug::isFlagSet(Debug::Time))
      {
        Debug::clearFlag(Debug::Time);
        restore=TRUE;
      }
      msg("----------------------\n");
      for (const auto &s : stats)
      {
        msg("Spent %.6f seconds in %s",s.elapsed,s.name);
      }
      if (restore) Debug::setFlag(Debug::Time);
    }
References Debug::clearFlag(), FALSE, Debug::isFlagSet(), msg(), Debug::setFlag(), stats, Debug::Time, and TRUE.
Member Data Documentation
startTime
std::chrono::steady_clock::time_point Statistics::startTime private
Definition at line 257 of file doxygen.cpp.
Referenced by begin(), and end().
stats
std::vector<stat> Statistics::stats private
Definition at line 256 of file doxygen.cpp.
Referenced by begin(), end(), and print().
The documentation for this class was generated from the following file:
src/doxygen.cpp