Doxygen: src/searchindex.h File Reference
searchindex.h File Reference
Web server based search engine.
#include <memory>
#include <vector>
#include <map>
#include <unordered_map>
#include <string>
#include <array>
#include <variant>
#include "qcstring.h"
#include "growbuf.h"
Classes
struct SIData_CurrentDoc
struct SIData_Word
class SearchIndex
Writes search index for doxygen provided server based search engine that uses PHP.
struct SearchIndex::URL
struct SearchIndex::URLInfo
class SearchIndex::IndexWord
class SearchIndexExternal
Writes search index that should be used with an externally provided search engine, e.g.
struct SearchIndexExternal::SearchDocEntry
class SearchIndexIntf
Abstract proxy interface for non-javascript based search indices.
Functions
void initSearchIndexer ()
void finalizeSearchIndexer ()
Detailed Description
Web server based search engine.
Comes in two flavors: internal (via generated index) or external (via doxyindexer + doxysearch)
Definition in file searchindex.h.
Function Documentation
finalizeSearchIndexer()
void finalizeSearchIndexer ()
Cleanup the search indexer
Definition at line 551 of file searchindex.cpp.
{
  Doxygen::searchIndex.setKind(SearchIndexIntf::Disabled);
}
References SearchIndexIntf::Disabled, Doxygen::searchIndex, and SearchIndexIntf::setKind().
Referenced by generateOutput().
initSearchIndexer()
void initSearchIndexer ()
Initialize the search indexer
Definition at line 540 of file searchindex.cpp.
{
  bool searchEngine      = Config_getBool(SEARCHENGINE);
  bool serverBasedSearch = Config_getBool(SERVER_BASED_SEARCH);
  bool externalSearch    = Config_getBool(EXTERNAL_SEARCH);
  if (searchEngine && serverBasedSearch)
  {
    Doxygen::searchIndex.setKind(externalSearch ? SearchIndexIntf::External : SearchIndexIntf::Internal);
  }
}
References Config_getBool, SearchIndexIntf::External, SearchIndexIntf::Internal, Doxygen::searchIndex, and SearchIndexIntf::setKind().
Referenced by parseInput().