Doxygen: /home/runner/work/doxygen/doxygen/src/rtfdocvisitor.cpp File Reference
rtfdocvisitor.cpp File Reference
#include <algorithm>
#include "rtfdocvisitor.h"
#include "docparser.h"
#include "language.h"
#include "doxygen.h"
#include "outputgen.h"
#include "dot.h"
#include "msc.h"
#include "util.h"
#include "rtfstyle.h"
#include "rtfgen.h"
#include "message.h"
#include "parserintf.h"
#include "dia.h"
#include "filedef.h"
#include "config.h"
#include "htmlentity.h"
#include "emoji.h"
#include "plantuml.h"
#include "fileinfo.h"
#include "portable.h"
Macros
#define DBG_RTF(x) do {} while(0)
Functions
static QCString align (const DocHtmlCell &cell)
Macro Definition Documentation
DBG_RTF
#define DBG_RTF (x) do {} while(0)
Definition at line 41 of file rtfdocvisitor.cpp.
Function Documentation
align()
static QCString align (const DocHtmlCell & cell) static
Definition at line 43 of file rtfdocvisitor.cpp.
{
  for (const auto &attr : cell.attribs())
  {
    if (attr.name.lower()=="align")
    {
      if (attr.value.lower()=="center")     return "\\qc ";
      else if (attr.value.lower()=="right") return "\\qr ";
      else return "";
    }
  }
  return "";
}
References DocHtmlCell::attribs().
Referenced by RTFDocVisitor::operator()(), and OutputList::startMemberDocName().