Doxygen: ModuleDefImpl Class Reference
ModuleDefImpl Class Reference
Public Member Functions
ModuleDefImpl (const QCString &fileName, int startLine, int startColom, const QCString &name, Type type, const QCString &partitionName)
DefType definitionType () const override
CodeSymbolType codeSymbolType () const override
QCString displayName (bool=TRUE) const override
QCString getOutputFileBase () const override
QCString anchor () const override
bool isLinkableInProject () const override
bool isLinkable () const override
QCString qualifiedName () const override
void writeSummaryLinks (OutputList &ol) const override
Type moduleType () const override
QCString partitionName () const override
void writeDocumentation (OutputList &ol) override
bool isPrimaryInterface () const override
MemberList * getMemberList (MemberListType lt) const override
const MemberLists & getMemberLists () const override
const MemberGroupList & getMemberGroups () const override
const ClassLinkedRefMap & getClasses () const override
const ConceptLinkedRefMap & getConcepts () const override
int countVisibleMembers () const override
FileDef * getFileDef () const override
const ImportInfoMap & getImports () const override
const ImportInfoMap & getExports () const override
const ModuleMap & partitions () const override
void writeTagFile (TextStream &t) const override
FileList getUsedFiles () const override
void writeExports (OutputList &ol, const QCString &title)
void writeClassDeclarations (OutputList &ol, const QCString &title)
void writeConcepts (OutputList &ol, const QCString &title)
void writeFiles (OutputList &ol, const QCString &title)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void writeAuthorSection (OutputList &ol)
void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const
void addHeader (int line, const QCString &headerName, bool isSystem)
void addImport (int line, const QCString &moduleName, const QCString &partitionName, bool isExported)
void addClassToModule (const Entry *root, ClassDef *cd)
void addConceptToModule (const Entry *root, ConceptDef *cd)
void addMemberToModule (const Entry *root, MemberDef *md)
void addPartition (ModuleDefImpl *mod)
void addContributingModule (ModuleDefImpl *mod)
void setPrimaryInterface (const ModuleDef *mod)
void setFileDef (FileDef *fd)
void addMemberToList (MemberListType lt, MemberDef *md)
void addExportedModule (const QCString &moduleName, const ImportInfo &info)
void addListReferences ()
void addMembersToMemberGroup ()
void distributeMemberGroupDocumentation ()
void findSectionsInDocumentation ()
void sortMemberLists ()
void mergeSymbolsFrom (ModuleDefImpl *other)
bool hasDetailedDescription () const
void countMembers ()
Public Member Functions inherited from DefinitionMixin< ModuleDef >
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=nullptr, const char *d=nullptr, bool isSymbol=TRUE)
DefinitionMixin (const DefinitionMixin &other)
DefinitionMixin (DefinitionMixin &&)=delete
DefinitionMixin & operator= (const DefinitionMixin &other)
DefinitionMixin & operator= (DefinitionMixin &&)=delete
~DefinitionMixin () override=default
bool isAlias () const override
const QCString & name () const override
bool isAnonymous () const override
const QCString & localName () const override
QCString symbolName () const override
QCString getSourceFileBase () const override
QCString getSourceAnchor () const override
QCString documentation () const override
int docLine () const override
QCString docFile () const override
QCString briefDescription (bool abbreviate=FALSE) const override
QCString briefDescriptionAsTooltip () const override
int briefLine () const override
QCString inbodyDocumentation () const override
QCString inbodyFile () const override
int inbodyLine () const override
QCString briefFile () const override
QCString getDefFileName () const override
QCString getDefFileExtension () const override
int getDefLine () const override
int getDefColumn () const override
bool hasDocumentation () const override
bool hasUserDocumentation () const override
bool isVisibleInProject () const override
bool isVisible () const override
bool isHidden () const override
bool isArtificial () const override
bool isExported () const override
QCString getReference () const override
bool isReference () const override
QCString externalReference (const QCString &relPath) const override
int getStartDefLine () const override
int getStartBodyLine () const override
int getEndBodyLine () const override
const FileDef * getBodyDef () const override
SrcLangExt getLanguage () const override
const GroupList & partOfGroups () const override
bool isLinkableViaGroup () const override
const RefItemVector & xrefListItems () const override
const Definition * findInnerCompound (const QCString &name) const override
Definition * getOuterScope () const override
const MemberVector & getReferencesMembers () const override
const MemberVector & getReferencedByMembers () const override
bool hasSections () const override
bool hasSources () const override
bool hasBriefDescription () const override
QCString id () const override
const SectionRefs & getSectionRefs () const override
void setName (const QCString &name) override
void setId (const QCString &name) override
void setDefFile (const QCString &df, int defLine, int defColumn) override
void setDocumentation (const QCString &doc, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE) override
void setBriefDescription (const QCString &brief, const QCString &briefFile, int briefLine) override
void setInbodyDocumentation (const QCString &doc, const QCString &docFile, int docLine) override
void setReference (const QCString &r) override
void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList) override
void setBodySegment (int defLine, int bls, int ble) override
void setBodyDef (const FileDef *fd) override
void addSourceReferencedBy (MemberDef *md, const QCString &sourceRefName) override
void addSourceReferences (MemberDef *md, const QCString &sourceRefName) override
void setRefItems (const RefItemVector &sli) override
void mergeRefItems (Definition *def) override
void mergeReferences (const Definition *other) override
void mergeReferencedBy (const Definition *other) override
void addInnerCompound (Definition *def) override
void setOuterScope (Definition *def) override
void setHidden (bool b) override
void setArtificial (bool b) override
void setExported (bool b) override
void setLanguage (SrcLangExt lang) override
void writeSourceDef (OutputList &ol) const override
void writeInlineCode (OutputList &ol, const QCString &scopeName) const override
bool hasSourceRefs () const override
bool hasSourceReffedBy () const override
void writeSourceRefs (OutputList &ol, const QCString &scopeName) const override
void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const override
void makePartOfGroup (GroupDef *gd) override
void writeNavigationPath (OutputList &ol) const override
QCString navigationPathAsString () const override
void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const override
QCString pathFragment () const override
void writeDocAnchorsToTagFile (TextStream &fs) const override
void setLocalName (const QCString &name) override
void writeToc (OutputList &ol, const LocalToc &lt) const override
void computeTooltip () override
void _setSymbolName (const QCString &name) override
QCString _symbolName () const override
Public Member Functions inherited from ModuleDef
Public Member Functions inherited from DefinitionMutable
Public Member Functions inherited from Definition
Private Attributes
Type m_type
QCString m_partitionName
ImportInfoMap m_imports
ImportInfoMap m_exportedModules
ClassLinkedRefMap m_classes
ConceptLinkedRefMap m_concepts
MemberLists m_memberLists
ModuleMap m_partitions
ModuleList m_contributing
MemberGroupList m_memberGroups
const ModuleDef * m_primaryInterface = nullptr
FileDef * m_fileDef = nullptr
Additional Inherited Members
Public Types inherited from ModuleDef
enum class Type { Interface , Implementation }
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Detailed Description
Definition at line 48 of file moduledef.cpp.
Constructor & Destructor Documentation
ModuleDefImpl()
ModuleDefImpl::ModuleDefImpl (const QCString & fileName, int startLine, int startColom, const QCString & name, Type type, const QCString & partitionName) inline
Definition at line 51 of file moduledef.cpp.
      : DefinitionMixin<ModuleDef>(fileName,startLine,startColom,name,nullptr,nullptr,true),
        m_type(type), m_partitionName(partitionName) {}
References DefinitionMixin< ModuleDef >::DefinitionMixin(), m_partitionName, m_type, Definition::name(), and partitionName().
Referenced by addContributingModule(), addPartition(), and mergeSymbolsFrom().
Member Function Documentation
addClassToModule()
void ModuleDefImpl::addClassToModule (const Entry * root, ClassDef * cd)
Definition at line 197 of file moduledef.cpp.
{
  QCString className = cd->qualifiedName();
  AUTO_TRACE("{}:{} class {} of module {} exported={}",
      root->fileName,root->startLine, className, name(), root->exported);
  bool isExported = m_classes.find(className)!=nullptr;
  if (root->exported && !isExported)
  {
    m_classes.add(className,cd);
  }
  auto cdm = toClassDefMutable(cd);
  if (cdm && root->exported && !cd->isExported())
  {
    cdm->setExported(true);
  }
}
References AUTO_TRACE, Entry::exported, Entry::fileName, Definition::isExported(), m_classes, Definition::name(), Definition::qualifiedName(), Entry::startLine, and toClassDefMutable().
Referenced by ModuleManager::addClassToModule().
addConceptToModule()
void ModuleDefImpl::addConceptToModule (const Entry * root, ConceptDef * cd)
Definition at line 214 of file moduledef.cpp.
{
  QCString conceptName = cd->qualifiedName();
  AUTO_TRACE("{}:{} concept {} of module {} exported={}",
     root->fileName,root->startLine,
     cd->qualifiedName(),name(),
     root->exported);
  bool isExported = m_classes.find(conceptName)!=nullptr;
  if (root->exported && !isExported)
  {
    m_concepts.add(conceptName,cd);
  }
  auto cdm = toConceptDefMutable(cd);
  if (cdm && root->exported && !cd->isExported())
  {
    cdm->setExported(true);
  }
}
References AUTO_TRACE, Entry::exported, Entry::fileName, Definition::isExported(), m_classes, m_concepts, Definition::name(), Definition::qualifiedName(), Entry::startLine, and toConceptDefMutable().
Referenced by ModuleManager::addConceptToModule().
addContributingModule()
void ModuleDefImpl::addContributingModule (ModuleDefImpl * mod)
Definition at line 162 of file moduledef.cpp.
{
  if (std::find(m_contributing.begin(),m_contributing.end(),mod)==m_contributing.end())
  {
    m_contributing.push_back(mod);
  }
}
References m_contributing, and ModuleDefImpl().
Referenced by ModuleManager::collectExportedSymbols().
addExportedModule()
void ModuleDefImpl::addExportedModule (const QCString & moduleName, const ImportInfo & info)
Definition at line 191 of file moduledef.cpp.
{
  AUTO_TRACE("name={}:moduleName={},import={}",name(),moduleName,info.importName);
  m_exportedModules.emplace(moduleName.str(),info);
}
References AUTO_TRACE, ImportInfo::importName, m_exportedModules, DefinitionMixin< ModuleDef >::name(), and QCString::str().
Referenced by ModuleManager::resolvePartitions(), and ModuleManager::resolvePartitionsRecursively().
addHeader()
void ModuleDefImpl::addHeader (int line, const QCString & headerName, bool isSystem)
Definition at line 180 of file moduledef.cpp.
{
  AUTO_TRACE("name={}:line={},header={},isSystem={}",name(),line,headerName,isSystem);
}
References AUTO_TRACE, and DefinitionMixin< ModuleDef >::name().
Referenced by ModuleManager::addHeader().
addImport()
void ModuleDefImpl::addImport (int line, const QCString & moduleName, const QCString & partitionName, bool isExported)
Definition at line 185 of file moduledef.cpp.
{
  AUTO_TRACE("name={}:line={},module={},partition={}",name(),line,moduleName,partitionName);
  m_imports.emplace(getDefFileName().str()+":"+std::to_string(line),ImportInfo(this,moduleName,line,partitionName,isExported));
}
References AUTO_TRACE, DefinitionMixin< ModuleDef >::getDefFileName(), Definition::isExported(), DefinitionMixin< ModuleDef >::isExported(), m_imports, DefinitionMixin< ModuleDef >::name(), and partitionName().
Referenced by ModuleManager::addImport().
addListReferences()
void ModuleDefImpl::addListReferences ()
Definition at line 647 of file moduledef.cpp.
{
  const RefItemVector &xrefItems = xrefListItems();
  addRefItem(xrefItems,
      qualifiedName(),
      getLanguage()==SrcLangExt::Fortran ?
      theTranslator->trModule(TRUE,TRUE) :
      theTranslator->trNamespace(TRUE,TRUE),
      getOutputFileBase(),displayName(),
      QCString(),
      this
      );
  for (const auto &mg : m_memberGroups)
  {
    mg->addListReferences(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType().isDocumentation())
    {
      ml->addListReferences(this);
    }
  }
}
References addRefItem(), displayName(), Fortran, DefinitionMixin< ModuleDef >::getLanguage(), getOutputFileBase(), m_memberGroups, m_memberLists, qualifiedName(), theTranslator, Translator::trModule(), Translator::trNamespace(), TRUE, and DefinitionMixin< ModuleDef >::xrefListItems().
Referenced by ModuleManager::addListReferences().
addMembersToMemberGroup()
void ModuleDefImpl::addMembersToMemberGroup ()
Definition at line 672 of file moduledef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType().isDeclaration())
    {
      ::addMembersToMemberGroup(ml.get(),&m_memberGroups,this);
    }
  }
  // add members inside sections to their groups
  for (const auto &mg : m_memberGroups)
  {
    if (mg->allMembersInSameSection() && Config_getBool(SUBGROUPING))
    {
      //printf("----> addToDeclarationSection(%s)\n",qPrint(mg->header()));
      mg->addToDeclarationSection();
    }
  }
}
References addMembersToMemberGroup(), Config_getBool, m_memberGroups, and m_memberLists.
Referenced by addMembersToMemberGroup(), and ModuleManager::addMembersToMemberGroup().
addMemberToList()
void ModuleDefImpl::addMemberToList (MemberListType lt, MemberDef * md)
Definition at line 245 of file moduledef.cpp.
{
  bool sortBriefDocs = Config_getBool(SORT_BRIEF_DOCS);
  bool sortMemberDocs = Config_getBool(SORT_MEMBER_DOCS);
  auto &ml = m_memberLists.get(lt,MemberListContainer::Module);
  ml->setNeedsSorting(
       (ml->listType().isDeclaration() && sortBriefDocs) ||
       (ml->listType().isDocumentation() && sortMemberDocs));
  ml->push_back(md);
  if (ml->listType().isDeclaration())
  {
    MemberDefMutable *mdm = toMemberDefMutable(md);
    if (mdm)
    {
      mdm->setSectionList(this,ml.get());
    }
  }
}
References Config_getBool, m_memberLists, Module, MemberDefMutable::setSectionList(), and toMemberDefMutable().
Referenced by addMemberToModule().
addMemberToModule()
void ModuleDefImpl::addMemberToModule (const Entry * root, MemberDef * md)
Definition at line 264 of file moduledef.cpp.
{
  AUTO_TRACE("{}:{} member {} of module {} exported={}",
      qPrint(root->fileName),root->startLine,
      qPrint(md->qualifiedName()),qPrint(name()),
      root->exported);
  MemberList *allMemberList = getMemberList(MemberListType::AllMembersList());
  if (allMemberList==nullptr)
  {
    m_memberLists.emplace_back(std::make_unique<MemberList>(MemberListType::AllMembersList(),MemberListContainer::Module));
    allMemberList = m_memberLists.back().get();
  }
  if (allMemberList->contains(md))
  {
    return;
  }
  allMemberList->push_back(md);
  switch (md->memberType())
  {
    case MemberType::Variable:
      addMemberToList(MemberListType::DecVarMembers(),md);
      break;
    case MemberType::Function:
      addMemberToList(MemberListType::DecFuncMembers(),md);
      break;
    case MemberType::Typedef:
      addMemberToList(MemberListType::DecTypedefMembers(),md);
      break;
    case MemberType::Enumeration:
      addMemberToList(MemberListType::DecEnumMembers(),md);
      break;
    default:
      break;
  }
  auto mdm = toMemberDefMutable(md);
  if (mdm && root->exported && !md->isExported())
  {
    mdm->setExported(true);
  }
}
References addMemberToList(), AUTO_TRACE, MemberVector::contains(), Enumeration, Entry::exported, Entry::fileName, Function, getMemberList(), Definition::isExported(), m_memberLists, MemberDef::memberType(), Module, DefinitionMixin< ModuleDef >::name(), MemberVector::push_back(), qPrint(), Definition::qualifiedName(), Entry::startLine, toMemberDefMutable(), Typedef, and Variable.
Referenced by ModuleManager::addMemberToModule().
addPartition()
void ModuleDefImpl::addPartition (ModuleDefImpl * mod)
Definition at line 153 of file moduledef.cpp.
{
  std::string qName = mod->qualifiedName().str();
  if (m_partitions.find(qName)==m_partitions.end())
  {
    m_partitions.emplace(qName,mod);
  }
}
References m_partitions, ModuleDefImpl(), qualifiedName(), and QCString::str().
Referenced by ModuleManager::resolvePartitionsRecursively().
anchor()
QCString ModuleDefImpl::anchor () const inline override virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 61 of file moduledef.cpp.
{ return ""; }
Referenced by writeDeclarationLink().
codeSymbolType()
CodeSymbolType ModuleDefImpl::codeSymbolType () const inline override virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 58 of file moduledef.cpp.
{ return CodeSymbolType::Module; }
References Module.
countMembers()
void ModuleDefImpl::countMembers ()
Definition at line 633 of file moduledef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    ml->countDecMembers();
    ml->countDocMembers();
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->countDecMembers();
    mg->countDocMembers();
  }
}
References m_memberGroups, and m_memberLists.
Referenced by ModuleManager::countMembers().
countVisibleMembers()
int ModuleDefImpl::countVisibleMembers () const override virtual
Implements ModuleDef.
Definition at line 979 of file moduledef.cpp.
{
  int count=0;
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Module))
  {
    if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        MemberList *ml = getMemberList(lmd->type);
        if (ml)
        {
          for (const auto &md : *ml)
          {
            if (md->visibleInIndex())
            {
              count++;
            }
          }
        }
      }
    }
    else if (lde->kind()==LayoutDocEntry::ModuleClasses)
    {
      for (const auto &cd : getClasses())
      {
        if (cd->isLinkableInProject())
        {
          count++;
        }
      }
    }
    else if (lde->kind()==LayoutDocEntry::ModuleConcepts)
    {
      for (const auto &cd : getConcepts())
      {
        if (cd->isLinkableInProject())
        {
          count++;
        }
      }
    }
  }
  return count;
}
References getClasses(), getConcepts(), getMemberList(), LayoutDocManager::instance(), and LayoutDocEntryMemberDecl::type.
definitionType()
DefType ModuleDefImpl::definitionType () const inline override virtual
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Definition at line 57 of file moduledef.cpp.
{ return TypeModule; }
References Definition::TypeModule.
displayName()
QCString ModuleDefImpl::displayName (bool includeScope = TRUE) const inline override virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 59 of file moduledef.cpp.
{ return name(); }
References DefinitionMixin< ModuleDef >::name().
Referenced by addListReferences(), writeDeclarationLink(), and writeDocumentation().
distributeMemberGroupDocumentation()
void ModuleDefImpl::distributeMemberGroupDocumentation ()
Definition at line 693 of file moduledef.cpp.
{
  for (const auto &mg : m_memberGroups)
  {
    mg->distributeMemberGroupDocumentation();
  }
}
References m_memberGroups.
Referenced by ModuleManager::distributeMemberGroupDocumentation().
endMemberDeclarations()
void ModuleDefImpl::endMemberDeclarations (OutputList & ol)
Definition at line 493 of file moduledef.cpp.
{
  ol.endMemberSections();
}
References OutputList::endMemberSections().
Referenced by writeDocumentation().
endMemberDocumentation()
void ModuleDefImpl::endMemberDocumentation (OutputList & ol)
Definition at line 507 of file moduledef.cpp.
{
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.enable(OutputType::Html);
    Doxygen::suppressDocWarnings = FALSE;
  }
}
References Config_getBool, OutputList::enable(), FALSE, Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
findSectionsInDocumentation()
void ModuleDefImpl::findSectionsInDocumentation ()
Definition at line 701 of file moduledef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
  docFindSections(inbodyDocumentation(),this,docFile());
  for (const auto &mg : m_memberGroups)
  {
    mg->findSectionsInDocumentation(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType().isDeclaration())
    {
      ml->findSectionsInDocumentation(this);
    }
  }
}
References DefinitionMixin< ModuleDef >::briefDescription(), DefinitionMixin< ModuleDef >::docFile(), docFindSections(), DefinitionMixin< ModuleDef >::documentation(), DefinitionMixin< ModuleDef >::inbodyDocumentation(), m_memberGroups, and m_memberLists.
Referenced by ModuleManager::findSectionsInDocumentation().
getClasses()
const ClassLinkedRefMap & ModuleDefImpl::getClasses () const inline override virtual
Implements ModuleDef.
Definition at line 75 of file moduledef.cpp.
{ return m_classes;  }
References m_classes.
Referenced by countVisibleMembers(), and mergeSymbolsFrom().
getConcepts()
const ConceptLinkedRefMap & ModuleDefImpl::getConcepts () const inline override virtual
Implements ModuleDef.
Definition at line 76 of file moduledef.cpp.
{ return m_concepts; }
References m_concepts.
Referenced by countVisibleMembers(), and mergeSymbolsFrom().
getExports()
const ImportInfoMap & ModuleDefImpl::getExports () const inline override virtual
Implements ModuleDef.
Definition at line 80 of file moduledef.cpp.
{ return m_exportedModules; }
References m_exportedModules.
getFileDef()
FileDef * ModuleDefImpl::getFileDef () const inline override virtual
Implements ModuleDef.
Definition at line 78 of file moduledef.cpp.
{ return m_fileDef; }
References m_fileDef.
Referenced by writeTagFile().
getImports()
const ImportInfoMap & ModuleDefImpl::getImports () const inline override virtual
Implements ModuleDef.
Definition at line 79 of file moduledef.cpp.
{ return m_imports; }
References m_imports.
getMemberGroups()
const MemberGroupList & ModuleDefImpl::getMemberGroups () const inline override virtual
Implements ModuleDef.
Definition at line 74 of file moduledef.cpp.
{ return m_memberGroups; }
References m_memberGroups.
getMemberList()
MemberList * ModuleDefImpl::getMemberList (MemberListType lt) const override virtual
Implements ModuleDef.
Definition at line 233 of file moduledef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()==lt)
    {
      return ml.get();
    }
  }
  return nullptr;
}
References m_memberLists.
Referenced by addMemberToModule(), countVisibleMembers(), mergeSymbolsFrom(), writeMemberDeclarations(), writeMemberDocumentation(), writeSummaryLinks(), and writeTagFile().
getMemberLists()
const MemberLists & ModuleDefImpl::getMemberLists () const inline override virtual
Implements ModuleDef.
Definition at line 73 of file moduledef.cpp.
{ return m_memberLists; }
References m_memberLists.
getOutputFileBase()
QCString ModuleDefImpl::getOutputFileBase () const override virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 138 of file moduledef.cpp.
{
  return convertNameToFile("module_" + name());
}
References convertNameToFile(), and DefinitionMixin< ModuleDef >::name().
Referenced by addListReferences(), writeDeclarationLink(), writeDocumentation(), and writeTagFile().
getUsedFiles()
FileList ModuleDefImpl::getUsedFiles () const override virtual
Implements ModuleDef.
Definition at line 968 of file moduledef.cpp.
{
  FileList result;
  for (const auto &mod : m_contributing)
  {
    FileDef *fd = mod->getFileDef();
    if (fd) result.push_back(fd);
  }
  return result;
}
References m_contributing.
Referenced by writeTagFile().
hasDetailedDescription()
bool ModuleDefImpl::hasDetailedDescription () const
Definition at line 627 of file moduledef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  return (!briefDescription().isEmpty() && repeatBrief) || !documentation().isEmpty();
}
References DefinitionMixin< ModuleDef >::briefDescription(), Config_getBool, DefinitionMixin< ModuleDef >::documentation(), and QCString::isEmpty().
Referenced by writeBriefDescription(), and writeDetailedDescription().
isLinkable()
bool ModuleDefImpl::isLinkable () const inline override virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 63 of file moduledef.cpp.
{ return hasDocumentation(); }
References DefinitionMixin< ModuleDef >::hasDocumentation().
Referenced by isLinkableInProject(), and writeDeclarationLink().
isLinkableInProject()
bool ModuleDefImpl::isLinkableInProject () const inline override virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 62 of file moduledef.cpp.
{ return isLinkable() && !isHidden() && !isReference(); }
References DefinitionMixin< ModuleDef >::isHidden(), isLinkable(), and DefinitionMixin< ModuleDef >::isReference().
Referenced by writeTagFile().
isPrimaryInterface()
bool ModuleDefImpl::isPrimaryInterface () const inline override virtual
Implements ModuleDef.
Definition at line 71 of file moduledef.cpp.
{ return m_type==Type::Interface && m_partitionName.isEmpty(); }
References ModuleDef::Interface, m_partitionName, and m_type.
Referenced by writeTagFile().
mergeSymbolsFrom()
void ModuleDefImpl::mergeSymbolsFrom (ModuleDefImpl * other)
Definition at line 305 of file moduledef.cpp.
{
  AUTO_TRACE("{} merging symbols of {} ({}:{})",
      name(),other->qualifiedName(),other->getDefFileName(),other->getDefLine());
  for (const auto &cd : other->getClasses())
  {
    m_classes.add(cd->qualifiedName(),cd);
  }
  for (const auto &cd : other->getConcepts())
  {
    m_concepts.add(cd->qualifiedName(),cd);
  }
  auto mergeMemberList = [this,other](MemberListType lt)
  {
    const auto srcMl = other->getMemberList(lt);
    if (srcMl)
    {
      auto &dstMl = m_memberLists.get(lt,srcMl->container());
      for (const auto &md : *srcMl)
      {
        dstMl->push_back(md);
      }
    }
  };
  mergeMemberList(MemberListType::DecVarMembers());
  mergeMemberList(MemberListType::DecFuncMembers());
  mergeMemberList(MemberListType::DecTypedefMembers());
  mergeMemberList(MemberListType::DecEnumMembers());
}
References AUTO_TRACE, getClasses(), getConcepts(), DefinitionMixin< Base >::getDefFileName(), DefinitionMixin< Base >::getDefLine(), getMemberList(), m_classes, m_concepts, m_memberLists, ModuleDefImpl(), DefinitionMixin< ModuleDef >::name(), and qualifiedName().
moduleType()
Type ModuleDefImpl::moduleType () const inline override virtual
Implements ModuleDef.
Definition at line 68 of file moduledef.cpp.
{ return m_type; }
References m_type.
partitionName()
QCString ModuleDefImpl::partitionName () const inline override virtual
Implements ModuleDef.
Definition at line 69 of file moduledef.cpp.
{ return m_partitionName; }
References m_partitionName.
Referenced by addImport(), and ModuleDefImpl().
partitions()
const ModuleMap & ModuleDefImpl::partitions () const inline override virtual
Implements ModuleDef.
Definition at line 81 of file moduledef.cpp.
{ return m_partitions; }
References m_partitions.
qualifiedName()
QCString ModuleDefImpl::qualifiedName () const override virtual
Returns the fully qualified name of this definition
Reimplemented from DefinitionMixin< ModuleDef >.
Definition at line 143 of file moduledef.cpp.
{
  QCString result=name();
  if (!m_partitionName.isEmpty())
  {
    result+=":"+m_partitionName;
  }
  return result;
}
References m_partitionName, and DefinitionMixin< ModuleDef >::name().
Referenced by addListReferences(), addPartition(), and mergeSymbolsFrom().
setFileDef()
void ModuleDefImpl::setFileDef (FileDef * fd)
Definition at line 175 of file moduledef.cpp.
{
  m_fileDef = fd;
}
References m_fileDef.
Referenced by ModuleManager::resolvePartitions().
setPrimaryInterface()
void ModuleDefImpl::setPrimaryInterface (const ModuleDef * mod)
Definition at line 170 of file moduledef.cpp.
{
  m_primaryInterface = mod;
}
References m_primaryInterface.
Referenced by ModuleManager::resolvePartitionsRecursively().
sortMemberLists()
void ModuleDefImpl::sortMemberLists ()
Definition at line 719 of file moduledef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->needsSorting()) { ml->sort(); ml->setNeedsSorting(FALSE); }
  }
  if (Config_getBool(SORT_BRIEF_DOCS))
  {
    auto classComp = [](const ClassLinkedRefMap::Ptr &c1,const ClassLinkedRefMap::Ptr &c2)
    {
      return Config_getBool(SORT_BY_SCOPE_NAME)          ?
        qstricmp_sort(c1->name(), c2->name())<0          :
        qstricmp_sort(c1->className(), c2->className())<0;
    };
    std::stable_sort(m_classes.begin(), m_classes.end(), classComp);
    auto conceptComp = [](const ConceptLinkedRefMap::Ptr &c1,const ConceptLinkedRefMap::Ptr &c2)
    {
      return Config_getBool(SORT_BY_SCOPE_NAME)                   ?
        qstricmp_sort(c1->qualifiedName(), c2->qualifiedName())<0 :
        qstricmp_sort(c1->name(), c2->name())<0;
    };
    std::stable_sort(m_concepts.begin(), m_concepts.end(), conceptComp);
  }
  static auto contrComp = [](const ModuleDef *m1, const ModuleDef *m2)
  {
    FileDef *f1 = m1->getFileDef();
    FileDef *f2 = m2->getFileDef();
    QCString fn1 = f1 ? f1->name() : m1->name();
    QCString fn2 = f2 ? f2->name() : m2->name();
    static auto typeRank = [](const ModuleDef *m) -> int
    {
      if (m->moduleType()==ModuleDef::Type::Interface)
      {
        if (m->partitionName().isEmpty()) return 0;  // primary interface unit
        return 1;                                    // partition interface unit
      }
      else
      {
        if (!m->partitionName().isEmpty()) return 2;  // partition implementation unit
        return 3;                                    // implementation unit
      }
    };
    auto tr1 = typeRank(m1);
    auto tr2 = typeRank(m2);
    int diff = qstricmp_sort(fn1,fn2);
    return tr1<tr2 || (tr1==tr2 && diff<0);
  };
  std::stable_sort(m_contributing.begin(), m_contributing.end(), contrComp);
}
References ClassDef::className(), Config_getBool, FALSE, ModuleDef::getFileDef(), ModuleDef::Interface, m_classes, m_concepts, m_contributing, m_memberLists, Definition::name(), qstricmp_sort(), and Definition::qualifiedName().
Referenced by ModuleManager::sortMemberLists().
startMemberDeclarations()
void ModuleDefImpl::startMemberDeclarations (OutputList & ol)
Definition at line 488 of file moduledef.cpp.
{
  ol.startMemberSections();
}
References OutputList::startMemberSections().
Referenced by writeDocumentation().
startMemberDocumentation()
void ModuleDefImpl::startMemberDocumentation (OutputList & ol)
Definition at line 498 of file moduledef.cpp.
{
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.disable(OutputType::Html);
    Doxygen::suppressDocWarnings = TRUE;
  }
}
References Config_getBool, OutputList::disable(), Html, Doxygen::suppressDocWarnings, and TRUE.
Referenced by writeDocumentation().
writeAuthorSection()
void ModuleDefImpl::writeAuthorSection (OutputList & ol)
Definition at line 615 of file moduledef.cpp.
{
  // write Author section (Man only)
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Man);
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), and TRUE.
Referenced by writeDocumentation().
writeBriefDescription()
void ModuleDefImpl::writeBriefDescription (OutputList & ol)
Definition at line 559 of file moduledef.cpp.
{
  if (hasBriefDescription())
  {
    auto parser { createDocParser() };
    auto ast    { validatingParseDoc(*parser.get(),
                                     briefFile(),briefLine(),this,nullptr,
                                     briefDescription(),TRUE,FALSE,
                                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startParagraph();
      ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Man);
      ol.writeString(" - ");
      ol.popGeneratorState();
      ol.writeDoc(ast.get(),this,nullptr);
      ol.pushGeneratorState();
      ol.disable(OutputType::RTF);
      ol.writeString(" \n");
      ol.enable(OutputType::RTF);
      if (hasDetailedDescription())
      {
        ol.disableAllBut(OutputType::Html);
        ol.startTextLink(QCString(),"details");
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
      }
      ol.popGeneratorState();
      ol.endParagraph();
    }
  }
  ol.writeSynopsis();
}
References DefinitionMixin< ModuleDef >::briefDescription(), Definition::briefFile(), DefinitionMixin< ModuleDef >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), FALSE, DefinitionMixin< ModuleDef >::hasBriefDescription(), hasDetailedDescription(), Html, Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), RTF, OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeClassDeclarations()
void ModuleDefImpl::writeClassDeclarations (OutputList & ol, const QCString & title)
Definition at line 478 of file moduledef.cpp.
{
  m_classes.writeDeclaration(ol,nullptr,title,FALSE);
}
References FALSE, and m_classes.
Referenced by writeDocumentation().
writeConcepts()
void ModuleDefImpl::writeConcepts (OutputList & ol, const QCString & title)
Definition at line 483 of file moduledef.cpp.
{
  m_concepts.writeDeclaration(ol,title,FALSE);
}
References FALSE, and m_concepts.
Referenced by writeDocumentation().
writeDeclarationLink()
void ModuleDefImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const
Definition at line 821 of file moduledef.cpp.
{
  if (isLinkable())
  {
    if (!found) // first module
    {
      ol.startMemberHeader("modules");
      if (!header.isEmpty())
      {
        ol.parseText(header);
      }
      else
      {
        theTranslator->trModule(true,false);
      }
      ol.endMemberHeader();
      ol.startMemberList();
      found=TRUE;
    }
    ol.startMemberDeclaration();
    ol.startMemberItem(anchor(),OutputGenerator::MemberItemType::Normal);
    ol.writeString("module ");
    QCString cname = displayName(!localNames);
    ol.insertMemberAlign();
    if (isLinkable())
    {
      ol.writeObjectLink(getReference(),
          getOutputFileBase(),
          anchor(),
          cname
          );
    }
    else
    {
      ol.startBold();
      ol.docify(cname);
      ol.endBold();
    }
    ol.endMemberItem(OutputGenerator::MemberItemType::Normal);
    // add the brief description if available
    if (!briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
    {
      auto parser { createDocParser() };
      auto ast    { validatingParseDoc(
                                *parser.get(),briefFile(),briefLine(),this,nullptr,
                                briefDescription(),FALSE,FALSE,
                                QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
      if (!ast->isEmpty())
      {
        ol.startMemberDescription(anchor());
        ol.writeDoc(ast.get(),this,nullptr);
        ol.endMemberDescription();
      }
    }
    ol.endMemberDeclaration(anchor(),QCString());
  }
}
References anchor(), DefinitionMixin< ModuleDef >::briefDescription(), Definition::briefFile(), DefinitionMixin< ModuleDef >::briefLine(), Config_getBool, createDocParser(), displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), FALSE, found, getOutputFileBase(), DefinitionMixin< ModuleDef >::getReference(), OutputList::insertMemberAlign(), QCString::isEmpty(), isLinkable(), OutputGenerator::Normal, OutputList::parseText(), OutputList::startBold(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trModule(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by ModuleLinkedRefMap::writeDeclaration().
writeDetailedDescription()
void ModuleDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title)
Definition at line 516 of file moduledef.cpp.
{
  if (hasDetailedDescription())
  {
    ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Html);
      ol.writeAnchor(QCString(),"details");
    ol.popGeneratorState();
    ol.startGroupHeader();
    ol.parseText(title);
    ol.endGroupHeader();
    ol.startTextBlock();
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF))
    {
      ol.generateDoc(briefFile(),briefLine(),this,nullptr,briefDescription(),FALSE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF) &&
        !documentation().isEmpty())
    {
      ol.pushGeneratorState();
        ol.disable(OutputType::Man);
        ol.disable(OutputType::RTF);
        ol.enableAll();
        ol.disableAllBut(OutputType::Man);
        ol.enable(OutputType::Latex);
        ol.writeString("\n\n");
      ol.popGeneratorState();
    }
    if (!documentation().isEmpty())
    {
      ol.generateDoc(docFile(),docLine(),this,nullptr,documentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    ol.endTextBlock();
  }
}
References DefinitionMixin< ModuleDef >::briefDescription(), DefinitionMixin< ModuleDef >::briefFile(), DefinitionMixin< ModuleDef >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< ModuleDef >::docFile(), DefinitionMixin< ModuleDef >::docLine(), DefinitionMixin< ModuleDef >::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), OutputList::endTextBlock(), FALSE, OutputList::generateDoc(), hasDetailedDescription(), Html, Latex, Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), RTF, OutputList::startGroupHeader(), OutputList::startTextBlock(), TRUE, OutputList::writeAnchor(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDocumentation()
void ModuleDefImpl::writeDocumentation (OutputList & ol) override virtual
Implements ModuleDef.
Definition at line 335 of file moduledef.cpp.
{
  if (isReference()) return;
  ol.pushGeneratorState();
  AUTO_TRACE("%s file=%s",name(),getDefFileName());
  SrcLangExt lang = getLanguage();
  QCString pageTitle = theTranslator->trModuleReference(displayName());
  startFile(ol,getOutputFileBase(),name(),pageTitle,HighlightedItem::ModuleVisible,false,QCString(),0);
  // ---- title part
  ol.startHeaderSection();
  writeSummaryLinks(ol);
  ol.startTitleHead(getOutputFileBase());
  ol.pushGeneratorState();
  ol.disable(OutputType::Man);
  ol.parseText(pageTitle);
  ol.popGeneratorState();
  addGroupListToTitle(ol,this);
  ol.pushGeneratorState();
  ol.disable(OutputType::Man);
  ol.endTitleHead(getOutputFileBase(),pageTitle);
  ol.popGeneratorState();
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Man);
  ol.endTitleHead(getOutputFileBase(),name());
  ol.writeString(" - ");
  ol.parseText(pageTitle);
  ol.popGeneratorState();
  ol.endHeaderSection();
  ol.startContents();
  //---------------------------------------- start flexible part -------------------------------
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Module))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
        startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::ModuleClasses:
        if (ls) writeClassDeclarations(ol,ls->title(lang));
        break;
      case LayoutDocEntry::ModuleConcepts:
        if (ls) writeConcepts(ol,ls->title(lang));
        break;
      case LayoutDocEntry::ModuleExports:
        if (ls) writeExports(ol,ls->title(lang));
        break;
      case LayoutDocEntry::ModuleUsedFiles:
        if (ls) writeFiles(ol,ls->title(lang));
        break;
      case LayoutDocEntry::MemberGroups:
        writeMemberGroups(ol);
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd) writeMemberDeclarations(ol,lmd->type,lmd->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDeclEnd:
        endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::DetailedDesc:
        if (ls) writeDetailedDescription(ol,ls->title(lang));
        break;
      case LayoutDocEntry::MemberDefStart:
        startMemberDocumentation(ol);
        break;
      case LayoutDocEntry::MemberDef:
        {
          const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
          if (lmd) writeMemberDocumentation(ol,lmd->type,lmd->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDefEnd:
        endMemberDocumentation(ol);
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::ClassIncludes:
      case LayoutDocEntry::ClassInheritanceGraph:
      case LayoutDocEntry::ClassNestedClasses:
      case LayoutDocEntry::ClassCollaborationGraph:
      case LayoutDocEntry::ClassAllMembersLink:
      case LayoutDocEntry::ClassUsedFiles:
      case LayoutDocEntry::ClassInlineClasses:
      case LayoutDocEntry::FileClasses:
      case LayoutDocEntry::FileConcepts:
      case LayoutDocEntry::FileInterfaces:
      case LayoutDocEntry::FileStructs:
      case LayoutDocEntry::FileExceptions:
      case LayoutDocEntry::FileNamespaces:
      case LayoutDocEntry::FileConstantGroups:
      case LayoutDocEntry::FileIncludes:
      case LayoutDocEntry::FileIncludeGraph:
      case LayoutDocEntry::FileIncludedByGraph:
      case LayoutDocEntry::FileInlineClasses:
      case LayoutDocEntry::FileSourceLink:
      case LayoutDocEntry::NamespaceNestedNamespaces:
      case LayoutDocEntry::NamespaceNestedConstantGroups:
      case LayoutDocEntry::NamespaceClasses:
      case LayoutDocEntry::NamespaceConcepts:
      case LayoutDocEntry::NamespaceInterfaces:
      case LayoutDocEntry::NamespaceStructs:
      case LayoutDocEntry::NamespaceExceptions:
      case LayoutDocEntry::NamespaceInlineClasses:
      case LayoutDocEntry::ConceptDefinition:
      case LayoutDocEntry::GroupClasses:
      case LayoutDocEntry::GroupConcepts:
      case LayoutDocEntry::GroupModules:
      case LayoutDocEntry::GroupInlineClasses:
      case LayoutDocEntry::GroupNamespaces:
      case LayoutDocEntry::GroupDirs:
      case LayoutDocEntry::GroupNestedGroups:
      case LayoutDocEntry::GroupFiles:
      case LayoutDocEntry::GroupGraph:
      case LayoutDocEntry::GroupPageDocs:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::Module entry list\n",lde->kind());
        break;
    }
  }
  //---------------------------------------- end flexible part -------------------------------
  endFile(ol);
  ol.popGeneratorState();
}
References addGroupListToTitle(), AUTO_TRACE, OutputList::disable(), OutputList::disableAllBut(), displayName(), endFile(), OutputList::endHeaderSection(), endMemberDeclarations(), endMemberDocumentation(), OutputList::endTitleHead(), err, DefinitionMixin< ModuleDef >::getDefFileName(), DefinitionMixin< ModuleDef >::getLanguage(), getOutputFileBase(), LayoutDocManager::instance(), DefinitionMixin< ModuleDef >::isReference(), Man, ModuleVisible, DefinitionMixin< ModuleDef >::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startContents(), startFile(), OutputList::startHeaderSection(), startMemberDeclarations(), startMemberDocumentation(), OutputList::startTitleHead(), theTranslator, LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), LayoutDocEntrySection::title(), Translator::trModuleReference(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeClassDeclarations(), writeConcepts(), writeDetailedDescription(), writeExports(), writeFiles(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), OutputList::writeString(), and writeSummaryLinks().
writeExports()
void ModuleDefImpl::writeExports (OutputList & ol, const QCString & title)
Definition at line 880 of file moduledef.cpp.
{
  AUTO_TRACE("name={} count={}",name(),m_exportedModules.size());
  if (!m_exportedModules.empty())
  {
    ol.startMemberHeader("exports");
    ol.parseText(title);
    ol.endMemberHeader();
    ol.startMemberList();
    for (auto &[moduleName,importInfo] : m_exportedModules)
    {
      ModuleDef *mod = ModuleManager::instance().getPrimaryInterface(importInfo.importName);
      ol.startMemberDeclaration();
      ol.startMemberItem(importInfo.importName,OutputGenerator::MemberItemType::Normal);
      ol.docify(theTranslator->trModule(FALSE,TRUE)+" ");
      ol.insertMemberAlign();
      if (mod && mod->isLinkable())
      {
        ol.writeObjectLink(mod->getReference(),mod->getOutputFileBase(),QCString(),mod->displayName());
      }
      else
      {
        ol.startBold();
        ol.docify(importInfo.importName);
        ol.endBold();
      }
      ol.endMemberItem(OutputGenerator::MemberItemType::Normal);
      if (mod && !mod->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
      {
        ol.startMemberDescription(mod->getOutputFileBase());
        ol.generateDoc(briefFile(),briefLine(),mod,nullptr,mod->briefDescription(),FALSE,FALSE,
            QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
        ol.endMemberDescription();
      }
      ol.endMemberDeclaration(QCString(),QCString());
    }
    ol.endMemberList();
  }
}
References AUTO_TRACE, Definition::briefDescription(), DefinitionMixin< ModuleDef >::briefFile(), DefinitionMixin< ModuleDef >::briefLine(), Config_getBool, Definition::displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), FALSE, OutputList::generateDoc(), Definition::getOutputFileBase(), ModuleManager::getPrimaryInterface(), Definition::getReference(), OutputList::insertMemberAlign(), ModuleManager::instance(), QCString::isEmpty(), Definition::isLinkable(), m_exportedModules, DefinitionMixin< ModuleDef >::name(), OutputGenerator::Normal, OutputList::parseText(), OutputList::startBold(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trModule(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeFiles()
void ModuleDefImpl::writeFiles (OutputList & ol, const QCString & title)
Definition at line 920 of file moduledef.cpp.
{
  AUTO_TRACE("{} count={}",name(),m_contributing.size());
  if (!m_contributing.empty())
  {
    ol.startMemberHeader("files");
    ol.parseText(title);
    ol.endMemberHeader();
    ol.startMemberList();
    for (const auto &mod : m_contributing)
    {
      FileDef *fd = mod->getFileDef();
      if (fd)
      {
        ol.startMemberDeclaration();
        ol.startMemberItem(fd->anchor(),OutputGenerator::MemberItemType::Normal);
        ol.docify(theTranslator->trFile(FALSE,TRUE)+" ");
        ol.insertMemberAlign();
        QCString path=fd->getPath();
        if (Config_getBool(FULL_PATH_NAMES))
        {
          ol.docify(stripFromPath(path));
        }
        if (fd->isLinkable())
        {
          ol.writeObjectLink(fd->getReference(),fd->getOutputFileBase(),QCString(),fd->displayName());
        }
        else
        {
          ol.startBold();
          ol.docify(fd->displayName());
          ol.endBold();
        }
        ol.endMemberItem(OutputGenerator::MemberItemType::Normal);
        if (!fd->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
        {
          ol.startMemberDescription(fd->getOutputFileBase());
          ol.generateDoc(briefFile(),briefLine(),fd,nullptr,fd->briefDescription(),FALSE,FALSE,
              QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
          ol.endMemberDescription();
        }
        ol.endMemberDeclaration(QCString(),QCString());
      }
    }
    ol.endMemberList();
  }
}
References Definition::anchor(), AUTO_TRACE, Definition::briefDescription(), DefinitionMixin< ModuleDef >::briefFile(), DefinitionMixin< ModuleDef >::briefLine(), Config_getBool, Definition::displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), FALSE, OutputList::generateDoc(), Definition::getOutputFileBase(), FileDef::getPath(), Definition::getReference(), OutputList::insertMemberAlign(), QCString::isEmpty(), Definition::isLinkable(), m_contributing, DefinitionMixin< ModuleDef >::name(), OutputGenerator::Normal, OutputList::parseText(), OutputList::startBold(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), stripFromPath(), theTranslator, Translator::trFile(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeMemberDeclarations()
void ModuleDefImpl::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title)
Definition at line 603 of file moduledef.cpp.
{
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDeclarations(ol,nullptr,nullptr,nullptr,nullptr,this,title,QCString());
}
References getMemberList(), and MemberList::writeDeclarations().
Referenced by writeDocumentation().
writeMemberDocumentation()
void ModuleDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title)
Definition at line 609 of file moduledef.cpp.
{
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDocumentation(ol,name(),this,title);
}
References getMemberList(), DefinitionMixin< ModuleDef >::name(), and MemberList::writeDocumentation().
Referenced by writeDocumentation().
writeMemberGroups()
void ModuleDefImpl::writeMemberGroups (OutputList & ol)
Definition at line 595 of file moduledef.cpp.
{
  for (const auto &mg : m_memberGroups)
  {
    mg->writeDeclarations(ol,nullptr,nullptr,nullptr,nullptr,this);
  }
}
References m_memberGroups.
Referenced by writeDocumentation().
writeSummaryLinks()
void ModuleDefImpl::writeSummaryLinks (OutputList & ol) const override virtual
Reimplemented from DefinitionMixin< ModuleDef >.
Definition at line 773 of file moduledef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  bool first=TRUE;
  SrcLangExt lang=getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Module))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    if (lde->kind()==LayoutDocEntry::ModuleClasses && m_classes.declVisible() && ls)
    {
      QCString label = "classes";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::ModuleConcepts && m_concepts.declVisible() && ls)
    {
      QCString label = "concepts";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::ModuleUsedFiles && ls)
    {
      QCString label = "files";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        MemberList * ml = getMemberList(lmd->type);
        if (ml && ml->declVisible())
        {
          ol.writeSummaryLink(QCString(),ml->listType().toLabel(),lmd->title(lang),first);
          first=FALSE;
        }
      }
    }
  }
  if (!first)
  {
    ol.writeString("  </div>\n");
  }
  ol.popGeneratorState();
}
References MemberList::declVisible(), OutputList::disableAllBut(), FALSE, DefinitionMixin< ModuleDef >::getLanguage(), getMemberList(), Html, LayoutDocManager::instance(), MemberList::listType(), m_classes, m_concepts, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocEntryMemberDecl::title(), LayoutDocEntrySection::title(), MemberListType::toLabel(), TRUE, LayoutDocEntryMemberDecl::type, OutputList::writeString(), and OutputList::writeSummaryLink().
Referenced by writeDocumentation().
writeTagFile()
void ModuleDefImpl::writeTagFile (TextStream & t) const override virtual
Implements ModuleDef.
Definition at line 1026 of file moduledef.cpp.
{
  if (!isPrimaryInterface() || !isLinkableInProject()) return;
  tagFile << "  <compound kind=\"module\">\n";
  tagFile << "    <name>" << convertToXML(name()) << "</name>\n";
  const FileDef *fd = getFileDef();
  QCString fn = fd ? fd->getOutputFileBase() : getOutputFileBase();
  addHtmlExtensionIfMissing(fn);
  tagFile << "    <filename>" << convertToXML(fn) << "</filename>\n";
#if 0 // at the moment we do not export the members of a module to a tag file.
      // We let the project using a tag file directly link to the implementation of the
      // symbols (which have the same scope).
      //
      // When we support linking to a module's interface instead we need to
      // export the module's members as well. Then we probably need a way to
      // disambiguate/prioritize a link to a module over a link to the implementation,
      // for instance by hiding non-exported symbols from the tag file.
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Group))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::ModuleExports:
        {
          for (const auto &[modName,importInfo] : m_exportedModules)
          {
            tagFile << "    <export>" << convertToXML(importInfo.importName) << "</export>\n";
          }
        }
        break;
      case LayoutDocEntry::ModuleClasses:
        {
          for (const auto &cd : m_classes)
          {
            if (cd->isLinkableInProject())
            {
              tagFile << "    <class kind=\"" << cd->compoundTypeString()
                      << "\">" << convertToXML(cd->name()) << "</class>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::ModuleConcepts:
        {
          for (const auto &cd : m_concepts)
          {
            if (cd->isLinkableInProject())
            {
              tagFile << "    <concept>" << convertToXML(cd->name())
                      << "</concept>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::ModuleUsedFiles:
        {
          for (const auto &usedFd : getUsedFiles())
          {
            if (usedFd->isLinkableInProject())
            {
              tagFile << "    <file>" << convertToXML(usedFd->name()) << "</file>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            MemberList * ml = getMemberList(lmd->type);
            if (ml)
            {
              ml->writeTagFile(tagFile,true);
            }
          }
        }
        break;
      default:
        break;
    }
  }
#endif
  QCString idStr = id();
  if (!idStr.isEmpty())
  {
    tagFile << "    <clangid>" << convertToXML(idStr) << "</clangid>\n";
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << "  </compound>\n";
}
References addHtmlExtensionIfMissing(), convertToXML(), getFileDef(), getMemberList(), Definition::getOutputFileBase(), getOutputFileBase(), getUsedFiles(), DefinitionMixin< ModuleDef >::id(), LayoutDocManager::instance(), QCString::isEmpty(), isLinkableInProject(), isPrimaryInterface(), m_classes, m_concepts, m_exportedModules, DefinitionMixin< ModuleDef >::name(), LayoutDocEntryMemberDecl::type, DefinitionMixin< ModuleDef >::writeDocAnchorsToTagFile(), and MemberList::writeTagFile().
Member Data Documentation
m_classes
ClassLinkedRefMap ModuleDefImpl::m_classes private
Definition at line 128 of file moduledef.cpp.
Referenced by addClassToModule(), addConceptToModule(), getClasses(), mergeSymbolsFrom(), sortMemberLists(), writeClassDeclarations(), writeSummaryLinks(), and writeTagFile().
m_concepts
ConceptLinkedRefMap ModuleDefImpl::m_concepts private
Definition at line 129 of file moduledef.cpp.
Referenced by addConceptToModule(), getConcepts(), mergeSymbolsFrom(), sortMemberLists(), writeConcepts(), writeSummaryLinks(), and writeTagFile().
m_contributing
ModuleList ModuleDefImpl::m_contributing private
Definition at line 132 of file moduledef.cpp.
Referenced by addContributingModule(), getUsedFiles(), sortMemberLists(), and writeFiles().
m_exportedModules
ImportInfoMap ModuleDefImpl::m_exportedModules private
Definition at line 127 of file moduledef.cpp.
Referenced by addExportedModule(), getExports(), writeExports(), and writeTagFile().
m_fileDef
FileDef* ModuleDefImpl::m_fileDef = nullptr private
Definition at line 135 of file moduledef.cpp.
Referenced by getFileDef(), and setFileDef().
m_imports
ImportInfoMap ModuleDefImpl::m_imports private
Definition at line 126 of file moduledef.cpp.
Referenced by addImport(), and getImports().
m_memberGroups
MemberGroupList ModuleDefImpl::m_memberGroups private
Definition at line 133 of file moduledef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), countMembers(), distributeMemberGroupDocumentation(), findSectionsInDocumentation(), getMemberGroups(), and writeMemberGroups().
m_memberLists
MemberLists ModuleDefImpl::m_memberLists private
Definition at line 130 of file moduledef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), addMemberToList(), addMemberToModule(), countMembers(), findSectionsInDocumentation(), getMemberList(), getMemberLists(), mergeSymbolsFrom(), and sortMemberLists().
m_partitionName
QCString ModuleDefImpl::m_partitionName private
Definition at line 125 of file moduledef.cpp.
Referenced by isPrimaryInterface(), ModuleDefImpl(), partitionName(), and qualifiedName().
m_partitions
ModuleMap ModuleDefImpl::m_partitions private
Definition at line 131 of file moduledef.cpp.
Referenced by addPartition(), and partitions().
m_primaryInterface
const ModuleDef* ModuleDefImpl::m_primaryInterface = nullptr private
Definition at line 134 of file moduledef.cpp.
Referenced by setPrimaryInterface().
m_type
Type ModuleDefImpl::m_type private
Definition at line 124 of file moduledef.cpp.
Referenced by isPrimaryInterface(), ModuleDefImpl(), and moduleType().
The documentation for this class was generated from the following file:
src/moduledef.cpp