Doxygen: src/dia.h File Reference
dia.h File Reference
Enumerations
enum class DiaOutputFormat { BITMAP , EPS }
Functions
void writeDiaGraphFromFile (const QCString &inFile, const QCString &outDir, const QCString &outFile, DiaOutputFormat format, const QCString &srcFile, int srcLine)
Enumeration Type Documentation
DiaOutputFormat
enum class DiaOutputFormat strong
Enumerator
BITMAP
EPS
Definition at line 23 of file dia.h.
{ BITMAP , EPS };
Function Documentation
writeDiaGraphFromFile()
void writeDiaGraphFromFile (const QCString & inFile, const QCString & outDir, const QCString & outFile, DiaOutputFormat format, const QCString & srcFile, int srcLine)
Definition at line 26 of file dia.cpp.
{
  QCString absOutFile = outDir;
  absOutFile+=Portable::pathSeparator();
  absOutFile+=outFile;
  // chdir to the output dir, so dot can find the font file.
  std::string oldDir = Dir::currentDirPath();
  // go to the html output directory (i.e. path)
  Dir::setCurrent(outDir.str());
  //printf("Going to dir %s\n",Dir::currentDirPath().c_str());
  QCString diaExe = Config_getString(DIA_PATH)+"dia"+Portable::commandExtension();
  QCString diaArgs;
  QCString extension;
  diaArgs+="-n ";
  if (format==DiaOutputFormat::BITMAP)
  {
    diaArgs+="-t png-libart";
    extension=".png";
  }
  else if (format==DiaOutputFormat::EPS)
  {
    diaArgs+="-t eps";
    extension=".eps";
  }
  diaArgs+=" -e \"";
  diaArgs+=outFile;
  diaArgs+=extension+"\"";
  diaArgs+=" \"";
  diaArgs+=inFile;
  diaArgs+="\"";
  //printf("*** running: %s %s outDir:%s %s\n",qPrint(diaExe),qPrint(diaArgs),outDir,outFile);
  if (Portable::system(diaExe,diaArgs,FALSE)!=0)
  {
    err_full(srcFile,srcLine,"Problems running %s. Check your installation or look typos in you dia file %s",
        qPrint(diaExe),qPrint(inFile));
    goto error;
  }
  if ( (format==DiaOutputFormat::EPS) && (Config_getBool(USE_PDFLATEX)) )
  {
    QCString epstopdfArgs(maxCmdLine, QCString::ExplicitSize);
    epstopdfArgs.sprintf("\"%s.eps\" --outfile=\"%s.pdf\"",
                         qPrint(outFile),qPrint(outFile));
    if (Portable::system("epstopdf",epstopdfArgs)!=0)
    {
      err("Problems running epstopdf. Check your TeX installation!\n");
    }
    else
    {
      Dir().remove(outFile.str()+".eps");
    }
  }
error:
  Dir::setCurrent(oldDir);
}
References BITMAP, Portable::commandExtension(), Config_getBool, Config_getString, Dir::currentDirPath(), EPS, err, err_full, QCString::ExplicitSize, FALSE, maxCmdLine, Portable::pathSeparator(), qPrint(), Dir::remove(), Dir::setCurrent(), QCString::sprintf(), QCString::str(), and Portable::system().
Referenced by DocbookDocVisitor::startDiaFile(), LatexDocVisitor::startDiaFile(), DocbookDocVisitor::writeDiaFile(), HtmlDocVisitor::writeDiaFile(), LatexDocVisitor::writeDiaFile(), and RTFDocVisitor::writeDiaFile().