Doxygen: OutputList::OutputGenElem Struct Reference
OutputList::OutputGenElem Struct Reference
Public Member Functions
OutputGenElem (OutputGenIntfPtr &&v)
OutputGenElem (const OutputGenElem &other)
OutputGenElem & operator= (const OutputGenElem &other)
void setEnabled (bool e)
Public Attributes
OutputGenIntfPtr intf
bool enabled = true
std::stack< bool > enabledStack
Detailed Description
Definition at line 319 of file outputlist.h.
Constructor & Destructor Documentation
OutputGenElem() [1/2]
OutputList::OutputGenElem::OutputGenElem (OutputGenIntfPtr && v) inline explicit
Definition at line 321 of file outputlist.h.
: intf(std::move(v)) {}
References intf.
Referenced by operator=(), and OutputGenElem().
OutputGenElem() [2/2]
OutputList::OutputGenElem::OutputGenElem (const OutputGenElem & other) inline
Definition at line 322 of file outputlist.h.
      {
        intf = other.intf->clone();
        enabled = other.enabled;
      }
References enabled, intf, and OutputGenElem().
Member Function Documentation
operator=()
OutputGenElem & OutputList::OutputGenElem::operator= (const OutputGenElem & other) inline
Definition at line 327 of file outputlist.h.
      {
        if (&other!=this)
        {
          intf = other.intf->clone();
          enabled = other.enabled;
        }
        return *this;
      }
References enabled, intf, and OutputGenElem().
setEnabled()
void OutputList::OutputGenElem::setEnabled (bool e) inline
Definition at line 337 of file outputlist.h.
{ enabled = e && !enabledStack.empty() ? enabledStack.top() : e; }
References enabled, and enabledStack.
Member Data Documentation
enabled
bool OutputList::OutputGenElem::enabled = true
Definition at line 338 of file outputlist.h.
Referenced by operator=(), OutputGenElem(), and setEnabled().
enabledStack
std::stack<bool> OutputList::OutputGenElem::enabledStack
Definition at line 339 of file outputlist.h.
Referenced by setEnabled().
intf
OutputGenIntfPtr OutputList::OutputGenElem::intf
Definition at line 336 of file outputlist.h.
Referenced by operator=(), OutputGenElem(), and OutputGenElem().
The documentation for this struct was generated from the following file:
src/outputlist.h