Doxygen: TemplateNodeSet Class Reference
TemplateNodeSet Class Reference
Class representing an 'set' tag in a template.
Classes
struct Mapping
Public Member Functions
TemplateNodeSet (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeSet ()
void render (TextStream &, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeSet >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()=default
TemplateNode * parent ()
Private Attributes
std::unique_ptr< Mapping > m_mapping
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeSet >
static TemplateNodePtr createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeSet >
void mkpath (const TemplateContextImpl *ci, const std::string &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeSet >
QCString m_templateName
int m_line
Detailed Description
Class representing an 'set' tag in a template.
Definition at line 4290 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeSet()
TemplateNodeSet::TemplateNodeSet (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 4299 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeSet>(parser,parent,line)
    {
      AUTO_TRACE("data={}",Trace::trunc(data));
      ExpressionParser expParser(parser,line);
      // data format: name=expression
      int j=data.find('=');
      ExprAstPtr expr = 0;
      if (j>0 && (expr = expParser.parse(data.mid(j+1))))
      {
        m_mapping = std::make_unique<Mapping>(data.left(j),std::move(expr));
      }
    }
References AUTO_TRACE, QCString::find(), QCString::left(), m_mapping, QCString::mid(), ExpressionParser::parse(), and Trace::trunc().
~TemplateNodeSet()
TemplateNodeSet::~TemplateNodeSet () inline
Definition at line 4312 of file template.cpp.
    {
    }
Member Function Documentation
render()
void TemplateNodeSet::render (TextStream & , TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 4315 of file template.cpp.
    {
      AUTO_TRACE();
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_mapping)
      {
        TemplateVariant value = m_mapping->value->resolve(c);
        ci->set(m_mapping->name,value);
      }
    }
References AUTO_TRACE, TemplateNodeCreator< TemplateNodeSet >::m_line, m_mapping, TemplateNodeCreator< TemplateNodeSet >::m_templateName, TemplateContextImpl::set(), and TemplateContextImpl::setLocation().
Member Data Documentation
m_mapping
std::unique_ptr<Mapping> TemplateNodeSet::m_mapping private
Definition at line 4328 of file template.cpp.
Referenced by render(), and TemplateNodeSet().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/template.cpp