Doxygen: src/dotnode.cpp File Reference
dotnode.cpp File Reference
#include "dotnode.h"
#include "classdef.h"
#include "config.h"
#include "memberlist.h"
#include "membergroup.h"
#include "language.h"
#include "doxygen.h"
#include "util.h"
#include "textstream.h"
Classes
struct EdgeProperties
Helper struct holding the properties of a edge in a dot graph.
Macros
#define DEBUG_RENUMBERING 0
Functions
QCString escapeTooltip (const QCString &tooltip)
static void writeBoxMemberList (TextStream &t, char prot, const MemberList *ml, const ClassDef *scope, bool &lineWritten, bool isStatic=FALSE, const StringUnorderedSet *skipNames=nullptr)
static QCString stripProtectionPrefix (const QCString &s)
Variables
static const char * normalEdgeColorMap []
static const char * normalArrowStyleMap []
static const char * normalEdgeStyleMap []
static const char * umlEdgeColorMap []
static const char * umlArrowStyleMap []
static const char * umlEdgeStyleMap []
static EdgeProperties normalEdgeProps
static EdgeProperties umlEdgeProps
Macro Definition Documentation
DEBUG_RENUMBERING
#define DEBUG_RENUMBERING 0
Definition at line 895 of file dotnode.cpp.
Function Documentation
escapeTooltip()
QCString escapeTooltip (const QCString & tooltip)
Definition at line 99 of file dotnode.cpp.
{
  if (tooltip.isEmpty()) return tooltip;
  QCString result;
  const char *p=tooltip.data();
  char c = 0;
  while ((c=*p++))
  {
    switch(c)
    {
    case '"': result+="\\\""; break;
    case '\\': result+="\\\\"; break;
    default: result+=c; break;
    }
  }
  return result;
}
References QCString::data(), and QCString::isEmpty().
Referenced by common_attributes(), and DotNode::writeBox().
stripProtectionPrefix()
static QCString stripProtectionPrefix (const QCString & s) static
Definition at line 290 of file dotnode.cpp.
{
  if (!s.isEmpty() && (s[0]=='-' || s[0]=='+' || s[0]=='~' || s[0]=='#'))
  {
    return s.mid(1);
  }
  else
  {
    return s;
  }
}
References QCString::isEmpty(), and QCString::mid().
Referenced by DotNode::writeLabel().
writeBoxMemberList()
static void writeBoxMemberList (TextStream & t, char prot, const MemberList * ml, const ClassDef * scope, bool & lineWritten, bool isStatic = FALSE, const StringUnorderedSet * skipNames = nullptr) static
Definition at line 117 of file dotnode.cpp.
{
  constexpr auto tr_start = "<TR><TD VALIGN=\"top\" CELLPADDING=\"1\" CELLSPACING=\"0\">";
  constexpr auto tr_mid   = "</TD><TD VALIGN=\"top\" ALIGN=\"LEFT\" CELLPADDING=\"1\" CELLSPACING=\"0\">";
  constexpr auto tr_end   = "</TD></TR>\n";
  constexpr auto br       = "<BR ALIGN=\"LEFT\"/>";
  if (ml)
  {
    auto hideUndocMembers = Config_getEnum(HIDE_UNDOC_MEMBERS);
    int totalCount=0;
    for (const auto &mma : *ml)
    {
      if (mma->getClassDef()==scope &&
        (skipNames==nullptr || skipNames->find(mma->name().str())==std::end(*skipNames)) &&
          !(hideUndocMembers && !mma->hasDocumentation())
         )
      {
        totalCount++;
      }
    }
    int count=0;
    auto dotUmlDetails = Config_getEnum(DOT_UML_DETAILS);
    for (const auto &mma : *ml)
    {
      if (mma->getClassDef() == scope &&
        (skipNames==nullptr || skipNames->find(mma->name().str())==std::end(*skipNames)) &&
          !(hideUndocMembers && !mma->hasDocumentation())
         )
      {
        int numFields = Config_getInt(UML_LIMIT_NUM_FIELDS);
        if (numFields>0 && (totalCount>numFields*3/2 && count>=numFields))
        {
          t << tr_start << tr_mid << theTranslator->trAndMore(QCString().sprintf("%d",totalCount-count)) << tr_end;
          lineWritten = true;
          break;
        }
        else
        {
          t << tr_start << prot << tr_mid;
          QCString label;
          if (dotUmlDetails==DOT_UML_DETAILS_t::YES)
          {
            label+=mma->typeString();
            label+=" ";
          }
          label+=mma->name();
          if (!mma->isObjCMethod() && (mma->isFunction() || mma->isSlot() || mma->isSignal()))
          {
            if (dotUmlDetails==DOT_UML_DETAILS_t::YES)
            {
              label+=mma->argsString();
            }
            else
            {
              label+="()";
            }
          }
          t << DotNode::convertLabel(label,true);
          t << br << tr_end;
          lineWritten = true;
          count++;
        }
      }
    }
    // write member groups within the memberlist
    for (const auto &mg : ml->getMemberGroupList())
    {
      if (!mg->members().empty())
      {
        writeBoxMemberList(t,prot,&mg->members(),scope,lineWritten,isStatic,skipNames);
      }
    }
  }
}
References Config_getEnum, Config_getInt, DotNode::convertLabel(), FALSE, theTranslator, and writeBoxMemberList().
Referenced by writeBoxMemberList(), and DotNode::writeLabel().
Variable Documentation
normalArrowStyleMap
const char* normalArrowStyleMap[] static
Initial value:
=
{
  "empty",
  "empty",
  "empty",
  "open",
  nullptr,
  nullptr
}
Definition at line 46 of file dotnode.cpp.
{
  "empty",         // Public
  "empty",         // Protected
  "empty",         // Private
  "open",          // "use" relation
  nullptr,         // Undocumented
  nullptr          // template relation
};
normalEdgeColorMap
const char* normalEdgeColorMap[] static
Initial value:
=
{
  "steelblue1",
  "darkgreen",
  "firebrick4",
  "darkorchid3",
  "grey75",
  "orange",
  "orange"
}
mapping from protection levels to color names
Definition at line 35 of file dotnode.cpp.
{
  "steelblue1",    // Public
  "darkgreen",     // Protected
  "firebrick4",    // Private
  "darkorchid3",   // "use" relation
  "grey75",        // Undocumented
  "orange",        // template relation
  "orange"         // type constraint
};
normalEdgeProps
EdgeProperties normalEdgeProps static
Initial value:
=
{
  normalEdgeColorMap, normalArrowStyleMap, normalEdgeStyleMap
}
Definition at line 89 of file dotnode.cpp.
{
  normalEdgeColorMap, normalArrowStyleMap, normalEdgeStyleMap
};
Referenced by DotNode::writeArrow().
normalEdgeStyleMap
const char* normalEdgeStyleMap[] static
Initial value:
=
{
  "solid",
  "dashed"
}
Definition at line 56 of file dotnode.cpp.
{
  "solid",         // inheritance
  "dashed"         // usage
};
umlArrowStyleMap
const char* umlArrowStyleMap[] static
Initial value:
=
{
  "onormal",
  "onormal",
  "onormal",
  "odiamond",
  nullptr,
  nullptr
}
Definition at line 73 of file dotnode.cpp.
{
  "onormal",         // Public
  "onormal",         // Protected
  "onormal",         // Private
  "odiamond",        // "use" relation
  nullptr,           // Undocumented
  nullptr           // template relation
};
umlEdgeColorMap
const char* umlEdgeColorMap[] static
Initial value:
=
{
  "steelblue1",
  "darkgreen",
  "firebrick4",
  "steelblue1",
  "grey75",
  "orange",
  "orange"
}
Definition at line 62 of file dotnode.cpp.
{
  "steelblue1",    // Public
  "darkgreen",     // Protected
  "firebrick4",    // Private
  "steelblue1",    // "use" relation
  "grey75",        // Undocumented
  "orange",        // template relation
  "orange"         // type constraint
};
umlEdgeProps
EdgeProperties umlEdgeProps static
Initial value:
=
{
  umlEdgeColorMap, umlArrowStyleMap, umlEdgeStyleMap
}
Definition at line 94 of file dotnode.cpp.
{
  umlEdgeColorMap, umlArrowStyleMap, umlEdgeStyleMap
};
Referenced by DotNode::writeArrow().
umlEdgeStyleMap
const char* umlEdgeStyleMap[] static
Initial value:
=
{
  "solid",
  "solid"
}
Definition at line 83 of file dotnode.cpp.
{
  "solid",         // inheritance
  "solid"          // usage
};