Doxygen: LexOutlineParser Class Reference
LexOutlineParser Class Reference
Lex language parser using state-based lexical scanning.
#include <src/lexscanner.h>
Classes
struct Private
Public Member Functions
LexOutlineParser ()
~LexOutlineParser () override
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser) override
Parses a single input file with the goal to build an Entry tree.
bool needsPreprocessing (const QCString &) const override
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
void parsePrototype (const QCString &) override
Callback function called by the comment block scanner.
Public Member Functions inherited from OutlineParserInterface
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Lex language parser using state-based lexical scanning.
This is the Lex language parser for doxygen.
Definition at line 27 of file lexscanner.h.
Constructor & Destructor Documentation
LexOutlineParser()
LexOutlineParser::LexOutlineParser ()
Definition at line 1003 of file lexscanner.l.
                                   : p(std::make_unique<LexOutlineParser::Private>())
{
  lexscannerYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  lexscannerYYset_debug(Debug::isFlagSet(Debug::Lex_lexscanner)?1:0,p->yyscanner);
#endif
}
References Debug::isFlagSet(), Debug::Lex_lexscanner, LexOutlineParser(), and p.
Referenced by LexOutlineParser().
~LexOutlineParser()
LexOutlineParser::~LexOutlineParser () override
Definition at line 1011 of file lexscanner.l.
{
  lexscannerYYlex_destroy(p->yyscanner);
}
References p.
Member Function Documentation
needsPreprocessing()
bool LexOutlineParser::needsPreprocessing (const QCString & extension) const inline override virtual
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 37 of file lexscanner.h.
{ return TRUE; };
References TRUE.
parseInput()
void LexOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) override virtual
Parses a single input file with the goal to build an Entry tree.
Parameters
[in] fileName The full name of the file.
[in] fileBuf The contents of the file (zero terminated).
[in,out] root The root of the tree of Entry *nodes representing the information extracted from the file.
[in] clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
Definition at line 1016 of file lexscanner.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->fileName      = fileName;
  DebugLex debugLex(Debug::Lex_lexscanner, __FILE__, qPrint(fileName));
  ::parseMain(p->yyscanner,fileName,fileBuf,root,clangParser);
}
References Debug::Lex_lexscanner, p, parseMain(), and qPrint().
parsePrototype()
void LexOutlineParser::parsePrototype (const QCString & text) inline override virtual
Callback function called by the comment block scanner.
It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Definition at line 38 of file lexscanner.h.
{}
Member Data Documentation
p
std::unique_ptr<Private> LexOutlineParser::p private
Definition at line 42 of file lexscanner.h.
Referenced by LexOutlineParser(), parseInput(), and ~LexOutlineParser().
The documentation for this class was generated from the following files:
src/lexscanner.h
src/lexscanner.l