Doxygen: EntryType Class Reference
EntryType Class Reference
Wrapper class for the Entry type.
#include <src/types.h>
Public Member Functions
ENTRY_TYPES bool isCompound () const
bool isScope () const
bool isFile () const
bool isCompoundDoc () const
bool isDoc () const
std::string to_string () const
Private Types
enum TypeName { ENTRY_TYPES }
enum CategoryBits {
None = 0 , Compound = (1<<16) , Scope = (1<<17) , File = (1<<18) ,
CompoundDoc = (1<<19) , Doc = (1<<20) , TypeMask = 0x0000FFFF , CategoryMask = 0xFFFF0000
}
Private Member Functions
EntryType (int t)
std::string bits_to_string () const
TypeName type () const
Private Attributes
unsigned int m_type = Empty
Friends
bool operator== (const EntryType &t1, const EntryType &t2)
bool operator!= (const EntryType &t1, const EntryType &t2)
Detailed Description
Wrapper class for the Entry type.
Can be set only during construction. Packs the type together with category flags.
Definition at line 630 of file types.h.
Member Enumeration Documentation
CategoryBits
enum EntryType::CategoryBits private
Enumerator
None
Compound
Scope
File
CompoundDoc
Doc
TypeMask
CategoryMask
Definition at line 666 of file types.h.
    {
      None        = 0,
      Compound    = (1<<16),
      Scope       = (1<<17),
      File        = (1<<18),
      CompoundDoc = (1<<19),
      Doc         = (1<<20),
      TypeMask      = 0x0000FFFF,
      CategoryMask  = 0xFFFF0000
    };
TypeName
enum EntryType::TypeName private
Enumerator
ENTRY_TYPES
Definition at line 658 of file types.h.
    {
#define ETYPE(x,bits)                                                   \
      x,
      ENTRY_TYPES
#undef ETYPE
    };
Constructor & Destructor Documentation
EntryType()
EntryType::EntryType (int t) inline explicit private
Definition at line 677 of file types.h.
: m_type(t) {}
References m_type.
Referenced by operator!=, and operator==.
Member Function Documentation
bits_to_string()
std::string EntryType::bits_to_string () const inline private
Definition at line 678 of file types.h.
    {
      std::string result;
      if (m_type&Compound) result+=",Compound";
      if (m_type&Scope) result+=",Scope";
      if (m_type&File) result+=",File";
      if (m_type&CompoundDoc) result+=",CompoundDoc";
      return result;
    }
References Compound, CompoundDoc, File, m_type, and Scope.
isCompound()
ENTRY_TYPES bool EntryType::isCompound () const inline
Definition at line 638 of file types.h.
{ return (m_type & Compound)!=0;    }
References Compound, and m_type.
Referenced by addClassToContext(), buildClassList(), buildListOfUsingDecls(), findUsingDeclarations(), findUsingDeclImports(), isClassSection(), and isVarWithConstructor().
isCompoundDoc()
bool EntryType::isCompoundDoc () const inline
Definition at line 641 of file types.h.
{ return (m_type & CompoundDoc)!=0; }
References CompoundDoc, and m_type.
Referenced by buildClassDocList(), and isClassSection().
isDoc()
bool EntryType::isDoc () const inline
Definition at line 642 of file types.h.
{ return (m_type & Doc)!=0;         }
References Doc, and m_type.
Referenced by addMemberDocs().
isFile()
bool EntryType::isFile () const inline
Definition at line 640 of file types.h.
{ return (m_type & File)!=0;        }
References File, and m_type.
Referenced by buildFileList().
isScope()
bool EntryType::isScope () const inline
Definition at line 639 of file types.h.
{ return (m_type & Scope)!=0;       }
References m_type, and Scope.
Referenced by addClassToContext(), addConceptToContext(), addEnumValuesToEnums(), findEnumDocumentation(), findEnums(), and findMember().
to_string()
std::string EntryType::to_string () const inline
Definition at line 643 of file types.h.
    {
      switch (type())
      {
#define ETYPE(x,bits)                                                   \
        case x : return "["+std::string(#x)+bits_to_string()+"]";
        ENTRY_TYPES
#undef ETYPE
      }
      return "[unknown]";
    }
References ENTRY_TYPES, and type().
Referenced by fmt::formatter< EntryType >::format(), and printNavTree().
type()
TypeName EntryType::type () const inline private
Definition at line 687 of file types.h.
{ return static_cast<TypeName>(m_type & TypeMask); }
References m_type, and TypeMask.
Referenced by to_string().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const EntryType & t1, const EntryType & t2) friend
Definition at line 655 of file types.h.
{ return !(operator==(t1,t2)); }
References EntryType(), and operator==.
operator==
bool operator== (const EntryType & t1, const EntryType & t2) friend
Definition at line 654 of file types.h.
{ return t1.m_type==t2.m_type; }
References EntryType(), and m_type.
Referenced by operator!=.
Member Data Documentation
m_type
unsigned int EntryType::m_type = Empty private
Definition at line 688 of file types.h.
Referenced by bits_to_string(), EntryType(), isCompound(), isCompoundDoc(), isDoc(), isFile(), isScope(), operator==, and type().
The documentation for this class was generated from the following file:
src/types.h