Doxygen: MemberInfoContext::Private Class Reference
MemberInfoContext::Private Class Reference
Public Member Functions
Private (const MemberInfo *mi)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant protection () const
TemplateVariant virtualness () const
TemplateVariant ambiguityScope () const
TemplateVariant member () const
TemplateVariant createMember () const
Private Attributes
const MemberInfo * m_memberInfo
CachedItem< TemplateVariant, Private, &Private::createMember > m_member
Static Private Attributes
static const PropertyMap< MemberInfoContext::Private > s_inst
Detailed Description
Definition at line 7660 of file context.cpp.
Constructor & Destructor Documentation
Private()
MemberInfoContext::Private::Private (const MemberInfo * mi) inline
Definition at line 7663 of file context.cpp.
: m_memberInfo(mi) {}
Member Function Documentation
ambiguityScope()
TemplateVariant MemberInfoContext::Private::ambiguityScope () const inline private
Definition at line 7692 of file context.cpp.
    {
      return m_memberInfo->ambiguityResolutionScope();
    }
References MemberInfo::ambiguityResolutionScope(), and m_memberInfo.
createMember()
TemplateVariant MemberInfoContext::Private::createMember () const inline private
Definition at line 7702 of file context.cpp.
    {
      return m_memberInfo->memberDef() ?
        TemplateVariant(MemberContext::alloc(m_memberInfo->memberDef())) :
        TemplateVariant(false);
    }
References MemberContext::alloc(), m_memberInfo, and MemberInfo::memberDef().
fields()
StringVector MemberInfoContext::Private::fields () const inline
Definition at line 7667 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
get()
TemplateVariant MemberInfoContext::Private::get (const QCString & n) const inline
Definition at line 7666 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), and s_inst.
member()
TemplateVariant MemberInfoContext::Private::member () const inline private
Definition at line 7696 of file context.cpp.
    {
      return m_member.get(this);
    }
References m_member.
protection()
TemplateVariant MemberInfoContext::Private::protection () const inline private
Definition at line 7671 of file context.cpp.
    {
      switch (m_memberInfo->prot())
      {
        case Protection::Public:    return "public";
        case Protection::Protected: return "protected";
        case Protection::Private:   return "private";
        case Protection::Package:   return "package";
      }
      return "";
    }
References m_memberInfo, Package, Private, MemberInfo::prot(), Protected, and Public.
virtualness()
TemplateVariant MemberInfoContext::Private::virtualness () const inline private
Definition at line 7682 of file context.cpp.
    {
      switch (m_memberInfo->virt())
      {
        case Specifier::Normal:   return "normal";
        case Specifier::Virtual:  return "virtual";
        case Specifier::Pure:     return "pure";
      }
      return "";
    }
References m_memberInfo, Normal, Pure, MemberInfo::virt(), and Virtual.
Member Data Documentation
m_member
CachedItem<TemplateVariant, Private, &Private::createMember> MemberInfoContext::Private::m_member private
Definition at line 7709 of file context.cpp.
Referenced by member().
m_memberInfo
const MemberInfo* MemberInfoContext::Private::m_memberInfo private
Definition at line 7708 of file context.cpp.
Referenced by ambiguityScope(), createMember(), protection(), and virtualness().
s_inst
const PropertyMap< MemberInfoContext::Private > MemberInfoContext::Private::s_inst static private
Initial value:
{
  {  "protection",    &Private::protection },
  {  "virtualness",   &Private::virtualness },
  {  "ambiguityScope",&Private::ambiguityScope },
  {  "member",        &Private::member }
}
Definition at line 7710 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/context.cpp