Doxygen: VHDLCodeParser Class Reference
VHDLCodeParser Class Reference
#include <src/vhdlcode.h>
Classes
struct Private
Public Member Functions
VHDLCodeParser ()
~VHDLCodeParser () override
void parseCode (OutputCodeList &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool stripCodeComments, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=nullptr, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=nullptr, bool showLineNumbers=TRUE, const Definition *searchCtx=nullptr, bool collectXRefs=TRUE) override
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
void resetCodeParserState () override
Resets the state of the code parser.
Public Member Functions inherited from CodeParserInterface
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 25 of file vhdlcode.h.
Constructor & Destructor Documentation
VHDLCodeParser()
VHDLCodeParser::VHDLCodeParser ()
Definition at line 1632 of file vhdlcode.l.
                               : p(std::make_unique<Private>())
{
  vhdlcodeYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  vhdlcodeYYset_debug(Debug::isFlagSet(Debug::Lex_vhdlcode)?1:0,p->yyscanner);
#endif
  resetCodeParserState();
}
References Debug::isFlagSet(), Debug::Lex_vhdlcode, p, and resetCodeParserState().
~VHDLCodeParser()
VHDLCodeParser::~VHDLCodeParser () override
Definition at line 1641 of file vhdlcode.l.
{
  vhdlcodeYYlex_destroy(p->yyscanner);
}
References p.
Member Function Documentation
parseCode()
void VHDLCodeParser::parseCode (OutputCodeList & codeOutList, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool stripCodeComments, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = nullptr, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = nullptr, bool showLineNumbers = TRUE, const Definition * searchCtx = nullptr, bool collectXRefs = TRUE) override virtual
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
[in] codeOutList interface for writing the result.
[in] scopeName Name of scope to which the code belongs.
[in] input Actual code in the form of a string
[in] lang The programming language of the code fragment.
[in] stripCodeComments signals whether or not for the code block the doxygen comments should be stripped.
[in] isExampleBlock TRUE iff the code is part of an example.
[in] exampleName Name of the example.
[in] fileDef File definition to which the code is associated.
[in] startLine Starting line in case of a code fragment.
[in] endLine Ending line of the code fragment.
[in] inlineFragment Code fragment that is to be shown inline as part of the documentation.
[in] memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
[in] showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
[in] searchCtx context under which search data has to be stored.
[in] collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
Definition at line 1651 of file vhdlcode.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  //printf("***parseCode() exBlock=%d exName=%s fd=%p\n",exBlock,exName,fd);
  if (s.isEmpty()) return;
  DebugLex debugLex(Debug::Lex_vhdlcode, __FILE__, fd ? qPrint(fd->fileName()): nullptr);
  yyextra->fileName      = fd ? fd->fileName():"";
  if (memberDef)
  {
    const ClassDef *dd=memberDef->getClassDef();
    if (dd) yyextra->currClass=dd->name();
  }
  od.stripCodeComments(stripCodeComments);
  resetCodeParserState();
  yyextra->code = &od;
  yyextra->inputString   = s.data();
  yyextra->inputPosition = 0;
  yyextra->currentFontClass = nullptr;
  yyextra->insideCodeLine = false;
  yyextra->searchCtx = searchCtx;
  yyextra->foldStack.clear();
  yyextra->insideSpecialComment = false;
  if (startLine!=-1)
    yyextra->yyLineNr    = startLine;
  else
    yyextra->yyLineNr    = 1;
  if (endLine!=-1)
    yyextra->inputLines  = endLine+1;
  else
    yyextra->inputLines  = yyextra->yyLineNr + countLines(yyscanner) - 1;
  // yyextra->theCallContext.clear();
  yyextra->exampleBlock  = exBlock;
  yyextra->exampleName   = exName;
  yyextra->sourceFileDef = fd;
  if (exBlock && fd==nullptr)
  {
    // create a dummy filedef for the example
    yyextra->exampleFileDef = createFileDef("",exName);
    yyextra->sourceFileDef = yyextra->exampleFileDef.get();
  }
  if (yyextra->sourceFileDef)
  {
    setCurrentDoc(yyscanner,"l00001");
  }
  yyextra->currentDefinition = nullptr;
  yyextra->currentMemberDef  = nullptr;
  yyextra->vhdlMember        = nullptr;
  if (!yyextra->exampleName.isEmpty())
  {
    yyextra->exampleFile = convertNameToFile(yyextra->exampleName+"-example");
  }
  yyextra->includeCodeFragment = inlineFragment;
  startCodeLine(yyscanner);
  if (!yyextra->lexInit)
  {
    VhdlDocGen::init();
    yyextra->lexInit=true;
  }
  vhdlcodeYYrestart( nullptr, yyscanner );
  BEGIN( Bases );
  vhdlcodeYYlex(yyscanner);
  if (yyextra->insideCodeLine)
  {
    endCodeLine(yyscanner);
  }
  if (Config_getBool(HTML_CODE_FOLDING))
  {
    while (!yyextra->foldStack.empty())
    {
      yyextra->code->endFold();
      yyextra->foldStack.pop_back();
    }
  }
  if (yyextra->exampleFileDef)
  {
    // delete the temporary file definition used for this example
    yyextra->exampleFileDef.reset();
    yyextra->sourceFileDef = nullptr;
  }
  // write the tooltips
  yyextra->tooltipManager.writeTooltips(od);
}
References Config_getBool, convertNameToFile(), countLines(), createFileDef(), QCString::data(), endCodeLine(), FileDef::fileName(), MemberDef::getClassDef(), VhdlDocGen::init(), QCString::isEmpty(), Debug::Lex_vhdlcode, Definition::name(), p, qPrint(), resetCodeParserState(), setCurrentDoc(), startCodeLine(), and OutputCodeList::stripCodeComments().
resetCodeParserState()
void VHDLCodeParser::resetCodeParserState () override virtual
Resets the state of the code parser.
Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Definition at line 1646 of file vhdlcode.l.
{
  p->state.vhdlKeyDict.clear();
}
References p.
Referenced by parseCode(), and VHDLCodeParser().
Member Data Documentation
p
std::unique_ptr<Private> VHDLCodeParser::p private
Definition at line 51 of file vhdlcode.h.
Referenced by parseCode(), resetCodeParserState(), VHDLCodeParser(), and ~VHDLCodeParser().
The documentation for this class was generated from the following files:
src/vhdlcode.h
src/vhdlcode.l