Doxygen: src/filedef.h File Reference
filedef.h File Reference
#include <memory>
#include <unordered_set>
#include "definition.h"
#include "memberlist.h"
#include "containers.h"
Classes
struct IncludeInfo
Class representing the data associated with a #include statement.
class IncludeInfoList
class FileDef
A model of a file symbol.
class FileList
struct FilesInDir
Typedefs
using FileDefSet = std::unordered_set<const FileDef*>
Enumerations
enum class IncludeKind : uint32_t {
IncludeSystem = 0x0001 , IncludeLocal = 0x0002 , ImportSystemObjC = 0x0004 , ImportLocalObjC = 0x0008 ,
ImportSystem = 0x0010 , ImportLocal = 0x0020 , ImportModule = 0x0040
}
Functions
constexpr uint32_t operator| (IncludeKind a, IncludeKind b)
constexpr uint32_t operator| (uint32_t a, IncludeKind b)
constexpr uint32_t operator& (IncludeKind a, uint32_t mask)
QCString includeStatement (SrcLangExt lang, IncludeKind kind)
QCString includeOpen (SrcLangExt lang, IncludeKind kind)
QCString includeClose (SrcLangExt lang, IncludeKind kind)
bool compareFileDefs (const FileDef *fd1, const FileDef *fd2)
std::unique_ptr< FileDef > createFileDef (const QCString &p, const QCString &n, const QCString &ref=QCString(), const QCString &dn=QCString())
FileDef * toFileDef (Definition *d)
const FileDef * toFileDef (const Definition *d)
Variables
constexpr uint32_t IncludeKind_LocalMask = IncludeKind::IncludeLocal | IncludeKind::ImportLocalObjC | IncludeKind::ImportLocal
constexpr uint32_t IncludeKind_SystemMask = IncludeKind::IncludeSystem | IncludeKind::ImportSystemObjC | IncludeKind::ImportSystem
constexpr uint32_t IncludeKind_ImportMask
constexpr uint32_t IncludeKind_ObjCMask = IncludeKind::ImportSystemObjC | IncludeKind::ImportLocalObjC
Typedef Documentation
FileDefSet
using FileDefSet = std::unordered_set<const FileDef*>
Definition at line 44 of file filedef.h.
Enumeration Type Documentation
IncludeKind
enum class IncludeKind : uint32_t strong
Enumerator
IncludeSystem
IncludeLocal
ImportSystemObjC
ImportLocalObjC
ImportSystem
ImportLocal
ImportModule
Definition at line 46 of file filedef.h.
{
  // bits
  IncludeSystem     = 0x0001,
  IncludeLocal      = 0x0002,
  ImportSystemObjC  = 0x0004,
  ImportLocalObjC   = 0x0008,
  ImportSystem      = 0x0010, // C++20 header import
  ImportLocal       = 0x0020, // C++20 header import
  ImportModule      = 0x0040  // C++20 module import
};
Function Documentation
compareFileDefs()
bool compareFileDefs (const FileDef * fd1, const FileDef * fd2)
Definition at line 1885 of file filedef.cpp.
{
  return qstricmp_sort(fd1->name(),fd2->name()) < 0;
}
References Definition::name(), and qstricmp_sort().
Referenced by DirDefImpl::sort(), and writeFileIndex().
createFileDef()
std::unique_ptr< FileDef > createFileDef (const QCString & p, const QCString & n, const QCString & ref = QCString(), const QCString & dn = QCString())
Definition at line 265 of file filedef.cpp.
{
  return std::make_unique<FileDefImpl>(p,n,ref,dn);
}
Referenced by anonymous_namespace{tagreader.cpp}::TagFileParser::buildLists(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), CCodeParser::parseCode(), FortranCodeParser::parseCode(), LexCodeParser::parseCode(), PythonCodeParser::parseCode(), SQLCodeParser::parseCode(), VHDLCodeParser::parseCode(), XMLCodeParser::parseCode(), CodeFragmentManager::parseCodeFragment(), readDir(), readFileOrDirectory(), and writeGraphInfo().
includeClose()
QCString includeClose (SrcLangExt lang, IncludeKind kind)
Definition at line 86 of file filedef.cpp.
{
  if (lang==SrcLangExt::Java || lang==SrcLangExt::IDL) return ";";
  switch (kind)
  {
    case IncludeKind::ImportLocal:       return "\";";
    case IncludeKind::ImportLocalObjC:   return "\"";
    case IncludeKind::IncludeLocal:      return "\"";
    case IncludeKind::ImportSystem:      return ">;";
    case IncludeKind::ImportSystemObjC:  return ">";
    case IncludeKind::IncludeSystem:     return ">";
    case IncludeKind::ImportModule:      return ";";
  }
  return "";
}
References IDL, ImportLocal, ImportLocalObjC, ImportModule, ImportSystem, ImportSystemObjC, IncludeLocal, IncludeSystem, and Java.
Referenced by ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), and FileDefImpl::writeIncludeFiles().
includeOpen()
QCString includeOpen (SrcLangExt lang, IncludeKind kind)
Definition at line 73 of file filedef.cpp.
{
  if (lang==SrcLangExt::Java || kind==IncludeKind::ImportModule) return "";
  if (kind & IncludeKind_LocalMask)
  {
    return "\"";
  }
  else
  {
    return "<";
  }
}
References ImportModule, IncludeKind_LocalMask, and Java.
Referenced by ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), and FileDefImpl::writeIncludeFiles().
includeStatement()
QCString includeStatement (SrcLangExt lang, IncludeKind kind)
Definition at line 56 of file filedef.cpp.
{
  bool isIDLorJava = lang==SrcLangExt::IDL || lang==SrcLangExt::Java;
  if (isIDLorJava || (kind & IncludeKind_ImportMask))
  {
    return "import ";
  }
  else if (kind & IncludeKind_ObjCMask)
  {
    return "#import ";
  }
  else
  {
    return "#include ";
  }
}
References IDL, IncludeKind_ImportMask, IncludeKind_ObjCMask, and Java.
Referenced by ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), and FileDefImpl::writeIncludeFiles().
operator&()
uint32_t operator& (IncludeKind a, uint32_t mask) inline constexpr
Definition at line 60 of file filedef.h.
{ return static_cast<uint32_t>(a) & mask; }
operator|() [1/2]
uint32_t operator| (IncludeKind a, IncludeKind b) inline constexpr
Definition at line 58 of file filedef.h.
{ return static_cast<uint32_t>(a) | static_cast<uint32_t>(b); }
operator|() [2/2]
uint32_t operator| (uint32_t a, IncludeKind b) inline constexpr
Definition at line 59 of file filedef.h.
{ return a | static_cast<uint32_t>(b); }
toFileDef() [1/2]
const FileDef * toFileDef (const Definition * d)
Definition at line 1905 of file filedef.cpp.
{
  if (d==nullptr) return nullptr;
  if (d && typeid(*d)==typeid(FileDefImpl))
  {
    return static_cast<const FileDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
toFileDef() [2/2]
FileDef * toFileDef (Definition * d)
Definition at line 1892 of file filedef.cpp.
{
  if (d==nullptr) return nullptr;
  if (d && typeid(*d)==typeid(FileDefImpl))
  {
    return static_cast<FileDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
Referenced by DocSets::addIndexItem(), DocLink::DocLink(), DocRef::DocRef(), findModuleDef(), SymbolResolver::Private::followPath(), generateJSTree(), FTVHelp::Private::generateTree(), DocParser::handleLinkedWord(), NamespaceDefImpl::insertMember(), insertMemberAlias(), SymbolResolver::Private::isAccessibleFrom(), ClassDefImpl::moveTo(), MemberDefImpl::moveTo(), DefinitionImpl::navigationPathAsString(), node2URL(), SearchIndex::setCurrentDoc(), and SearchIndexExternal::setCurrentDoc().
Variable Documentation
IncludeKind_ImportMask
uint32_t IncludeKind_ImportMask constexpr
Initial value:
= IncludeKind::ImportSystemObjC | IncludeKind::ImportLocalObjC  | IncludeKind::ImportSystem |
                                            IncludeKind::ImportLocal      | IncludeKind::ImportModule
Definition at line 65 of file filedef.h.
Referenced by generateSqlite3ForFile(), includeStatement(), and includeTagFileAttributes().
IncludeKind_LocalMask
uint32_t IncludeKind_LocalMask = IncludeKind::IncludeLocal | IncludeKind::ImportLocalObjC | IncludeKind::ImportLocal constexpr
Definition at line 63 of file filedef.h.
Referenced by generateSqlite3ForFile(), generateXMLForFile(), includeOpen(), includeTagFileAttributes(), and writeIncludeInfo().
IncludeKind_ObjCMask
uint32_t IncludeKind_ObjCMask = IncludeKind::ImportSystemObjC | IncludeKind::ImportLocalObjC constexpr
Definition at line 67 of file filedef.h.
Referenced by includeStatement(), and includeTagFileAttributes().
IncludeKind_SystemMask
uint32_t IncludeKind_SystemMask = IncludeKind::IncludeSystem | IncludeKind::ImportSystemObjC | IncludeKind::ImportSystem constexpr
Definition at line 64 of file filedef.h.