Doxygen: Mapper Class Reference
Mapper Class Reference
Class representing a mapping from command names to command IDs.
#include <src/cmdmapper.h>
Public Member Functions
int map (const QCString &n) const
QCString find (const int n) const
Mapper (const CommandMap &cm, bool caseSensitive)
Private Attributes
const CommandMap & m_map
bool m_cs
Detailed Description
Class representing a mapping from command names to command IDs.
Definition at line 238 of file cmdmapper.h.
Constructor & Destructor Documentation
Mapper()
Mapper::Mapper (const CommandMap & cm, bool caseSensitive)
Definition at line 260 of file cmdmapper.cpp.
                                                      : m_map(cm), m_cs(caseSensitive)
{
}
Member Function Documentation
find()
QCString Mapper::find (const int n) const
Definition at line 250 of file cmdmapper.cpp.
{
  for (const auto &[name,id] : m_map)
  {
    int curVal = id;
    if (curVal == n || (curVal == (n | SIMPLESECT_BIT))) return name.c_str();
  }
  return QCString();
}
References m_map, and SIMPLESECT_BIT.
map()
int Mapper::map (const QCString & n) const
Definition at line 241 of file cmdmapper.cpp.
{
  if (n.isEmpty()) return 0;
  QCString name = n;
  if (!m_cs) name=name.lower();
  auto it = m_map.find(name.str());
  return it!=m_map.end() ? it->second : 0;
}
References QCString::find(), QCString::isEmpty(), QCString::lower(), m_cs, m_map, and QCString::str().
Referenced by DocPara::handleCommand(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlStartTag(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlCell::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocHtmlList::parseXml(), DocHtmlCell::parseXml(), DocHtmlTable::parseXml(), DocHtmlRow::parseXml(), and DocParamList::parseXml().
Member Data Documentation
m_cs
bool Mapper::m_cs private
Definition at line 246 of file cmdmapper.h.
Referenced by map().
m_map
const CommandMap& Mapper::m_map private
Definition at line 245 of file cmdmapper.h.
Referenced by find(), and map().
The documentation for this class was generated from the following files:
src/cmdmapper.h
src/cmdmapper.cpp