Doxygen: OutputCodeList Class Reference
OutputCodeList Class Reference
Class representing a list of different code generators.
#include <src/outputlist.h>
Classes
struct OutputCodeElem
Public Types
using OutputCodeIntfPtr = std::unique_ptr<OutputCodeIntf>
Public Member Functions
int id () const
void setId (int id)
void add (OutputCodeIntfPtr &&p)
template<class T , class... As>
T * add (As &&... args)
Add a code generator to the list, using a syntax similar to std::make_unique<T>()
template<class T >
T * get (OutputType o)
Returns a pointer to a specific generator in the list.
void setEnabledFiltered (OutputType o, bool enabled)
Enable or disable a specific generator.
void clear ()
void codify (const QCString &s)
void stripCodeComments (bool b)
void startSpecialComment ()
void endSpecialComment ()
void setStripIndentAmount (size_t amount)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startCodeLine (int lineNr)
void endCodeLine ()
void startFontClass (const QCString &c)
void endFontClass ()
void writeCodeAnchor (const QCString &name)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
void startFold (int lineNr, const QCString &startMarker, const QCString &endMarker)
void endFold ()
Private Member Functions
template<class... Ts, class... As>
void foreach (void(OutputCodeIntf::*methodPtr)(Ts...), As &&... args)
Private Attributes
std::vector< OutputCodeElem > m_outputCodeList
int m_id = -1
Detailed Description
Class representing a list of different code generators.
It offers the same interface as the specific code generators, and will forward each method to all generators that are enabled.
Definition at line 163 of file outputlist.h.
Member Typedef Documentation
OutputCodeIntfPtr
using OutputCodeList::OutputCodeIntfPtr = std::unique_ptr<OutputCodeIntf>
Definition at line 166 of file outputlist.h.
Member Function Documentation
add() [1/2]
template<class T , class... As> T * OutputCodeList::add (As &&... args) inline
Add a code generator to the list, using a syntax similar to std::make_unique<T>()
Definition at line 201 of file outputlist.h.
    {
      add(std::make_unique<T>(std::forward<As>(args)...));
      return static_cast<T*>(m_outputCodeList.back().intf.get());
    }
References add(), and m_outputCodeList.
add() [2/2]
void OutputCodeList::add (OutputCodeIntfPtr && p) inline
Definition at line 194 of file outputlist.h.
    {
      m_outputCodeList.emplace_back(std::move(p));
    }
References m_outputCodeList.
Referenced by add(), DocbookGenerator::addCodeGen(), HtmlGenerator::addCodeGen(), LatexGenerator::addCodeGen(), ManGenerator::addCodeGen(), RTFGenerator::addCodeGen(), generateBriefDoc(), getSQLDocBlock(), CodeFragmentManager::parseCodeFragment(), FileDefImpl::parseSource(), FileDefImpl::writeSourceBody(), writeXMLCodeBlock(), and writeXMLDocBlock().
clear()
void OutputCodeList::clear () inline
Definition at line 227 of file outputlist.h.
    {
      m_outputCodeList.clear();
    }
References m_outputCodeList.
codify()
void OutputCodeList::codify (const QCString & s) inline
Definition at line 234 of file outputlist.h.
    { foreach(&OutputCodeIntf::codify,s); }
References OutputCodeIntf::codify().
Referenced by FileCodeParser::parseCode().
endCodeFragment()
void OutputCodeList::endCodeFragment (const QCString & style) inline
Definition at line 281 of file outputlist.h.
    { foreach(&OutputCodeIntf::endCodeFragment,style); }
References OutputCodeIntf::endCodeFragment().
Referenced by writeXMLCodeBlock().
endCodeLine()
void OutputCodeList::endCodeLine () inline
Definition at line 266 of file outputlist.h.
    { foreach(&OutputCodeIntf::endCodeLine); }
References OutputCodeIntf::endCodeLine().
Referenced by FileCodeParser::parseCode(), and OutputCodeRecorder::replay().
endFold()
void OutputCodeList::endFold () inline
Definition at line 287 of file outputlist.h.
    { foreach(&OutputCodeIntf::endFold); }
References OutputCodeIntf::endFold().
endFontClass()
void OutputCodeList::endFontClass () inline
Definition at line 272 of file outputlist.h.
    { foreach(&OutputCodeIntf::endFontClass); }
References OutputCodeIntf::endFontClass().
endSpecialComment()
void OutputCodeList::endSpecialComment () inline
Definition at line 243 of file outputlist.h.
    { foreach(&OutputCodeIntf::endSpecialComment); }
References OutputCodeIntf::endSpecialComment().
Referenced by OutputCodeRecorder::replay().
foreach()
template<class... Ts, class... As> void OutputCodeList::foreach (void(OutputCodeIntf::* methodPtr)(Ts...), As &&... args) inline private
Definition at line 292 of file outputlist.h.
    {
      for (auto &e : m_outputCodeList)
      {
        if (e.enabled)
        {
          (e.intf.get()->*methodPtr)(std::forward<As>(args)...);
        }
      }
    }
References m_outputCodeList.
get()
template<class T > T * OutputCodeList::get (OutputType o) inline
Returns a pointer to a specific generator in the list.
Definition at line 209 of file outputlist.h.
    {
      for (auto &e : m_outputCodeList)
      {
        if (e.intf->type()==o) { return static_cast<T*>(e.intf.get()); }
      }
      return nullptr;
    }
References m_outputCodeList.
id()
int OutputCodeList::id () const inline
Definition at line 191 of file outputlist.h.
{ return m_id; }
References m_id.
Referenced by setId(), and TooltipManager::writeTooltips().
setEnabledFiltered()
void OutputCodeList::setEnabledFiltered (OutputType o, bool enabled) inline
Enable or disable a specific generator.
Definition at line 219 of file outputlist.h.
    {
      for (auto &e : m_outputCodeList)
      {
        if (e.intf->type()==o) e.enabled = enabled;
      }
    }
References m_outputCodeList.
setId()
void OutputCodeList::setId (int id) inline
Definition at line 192 of file outputlist.h.
{ m_id = id;   }
References id(), and m_id.
setStripIndentAmount()
void OutputCodeList::setStripIndentAmount (size_t amount) inline
Definition at line 246 of file outputlist.h.
    { foreach(&OutputCodeIntf::setStripIndentAmount,amount); }
References OutputCodeIntf::setStripIndentAmount().
Referenced by OutputCodeRecorder::replay().
startCodeFragment()
void OutputCodeList::startCodeFragment (const QCString & style) inline
Definition at line 278 of file outputlist.h.
    { foreach(&OutputCodeIntf::startCodeFragment,style); }
References OutputCodeIntf::startCodeFragment().
Referenced by MemberDefImpl::_writeMultiLineInitializer(), ConceptDefImpl::writeDefinition(), DefinitionImpl::writeInlineCode(), VhdlDocGen::writeSource(), FileDefImpl::writeSourceBody(), and writeXMLCodeBlock().
startCodeLine()
void OutputCodeList::startCodeLine (int lineNr) inline
Definition at line 263 of file outputlist.h.
    { foreach(&OutputCodeIntf::startCodeLine,lineNr); }
References OutputCodeIntf::startCodeLine().
Referenced by FileCodeParser::parseCode().
startFold()
void OutputCodeList::startFold (int lineNr, const QCString & startMarker, const QCString & endMarker) inline
Definition at line 284 of file outputlist.h.
    { foreach(&OutputCodeIntf::startFold,lineNr,startMarker,endMarker); }
References OutputCodeIntf::startFold().
startFontClass()
void OutputCodeList::startFontClass (const QCString & c) inline
Definition at line 269 of file outputlist.h.
    { foreach(&OutputCodeIntf::startFontClass,c); }
References OutputCodeIntf::startFontClass().
Referenced by startFonts().
startSpecialComment()
void OutputCodeList::startSpecialComment () inline
Definition at line 240 of file outputlist.h.
    { foreach(&OutputCodeIntf::startSpecialComment); }
References OutputCodeIntf::startSpecialComment().
Referenced by OutputCodeRecorder::replay().
stripCodeComments()
void OutputCodeList::stripCodeComments (bool b) inline
Definition at line 237 of file outputlist.h.
    { foreach(&OutputCodeIntf::stripCodeComments,b); }
References OutputCodeIntf::stripCodeComments().
Referenced by CCodeParser::parseCode(), FortranCodeParser::parseCode(), PythonCodeParser::parseCode(), VHDLCodeParser::parseCode(), and OutputCodeRecorder::replay().
writeCodeAnchor()
void OutputCodeList::writeCodeAnchor (const QCString & name) inline
Definition at line 275 of file outputlist.h.
    { foreach(&OutputCodeIntf::writeCodeAnchor,name); }
References OutputCodeIntf::writeCodeAnchor().
Referenced by generateClassMemberLink(), generateClassOrGlobalLink(), and getLinkInScope().
writeCodeLink()
void OutputCodeList::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) inline
Definition at line 249 of file outputlist.h.
    { foreach(&OutputCodeIntf::writeCodeLink,type,ref,file,anchor,name,tooltip); }
References OutputCodeIntf::writeCodeLink().
Referenced by writeMultiLineCodeLink(), writeMultiLineCodeLink(), writeMultiLineCodeLink(), and writeMultiLineCodeLink().
writeLineNumber()
void OutputCodeList::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) inline
Definition at line 255 of file outputlist.h.
    { foreach(&OutputCodeIntf::writeLineNumber,ref,file,anchor,lineNumber,writeLineAnchor); }
References OutputCodeIntf::writeLineNumber().
Referenced by FileCodeParser::parseCode().
writeTooltip()
void OutputCodeList::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) inline
Definition at line 259 of file outputlist.h.
    { foreach(&OutputCodeIntf::writeTooltip,id,docInfo,decl,desc,defInfo,declInfo); }
References OutputCodeIntf::writeTooltip().
Referenced by TooltipManager::writeTooltips().
Member Data Documentation
m_id
int OutputCodeList::m_id = -1 private
Definition at line 304 of file outputlist.h.
Referenced by id(), and setId().
m_outputCodeList
std::vector<OutputCodeElem> OutputCodeList::m_outputCodeList private
Definition at line 303 of file outputlist.h.
Referenced by add(), add(), clear(), foreach(), get(), and setEnabledFiltered().
The documentation for this class was generated from the following file:
src/outputlist.h