Doxygen: DocAutoListItem Class Reference
DocAutoListItem Class Reference
Node representing an item of a auto list.
#include <src/docnode.h>
Public Member Functions
DocAutoListItem (DocParser *parser, DocNodeVariant *parent, int indent, int num)
int itemNumber () const
Token parse ()
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
int m_indent = 0
int m_itemNum = 0
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing an item of a auto list.
Definition at line 574 of file docnode.h.
Constructor & Destructor Documentation
DocAutoListItem()
DocAutoListItem::DocAutoListItem (DocParser * parser, DocNodeVariant * parent, int indent, int num)
Definition at line 2761 of file docnode.cpp.
      : DocCompoundNode(parser,parent), m_indent(indent), m_itemNum(num)
{
}
References DocCompoundNode::DocCompoundNode(), m_indent, m_itemNum, DocNode::parent(), and DocNode::parser().
Member Function Documentation
itemNumber()
int DocAutoListItem::itemNumber () const inline
Definition at line 578 of file docnode.h.
{ return m_itemNum; }
References m_itemNum.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
parse()
Token DocAutoListItem::parse ()
Definition at line 2766 of file docnode.cpp.
{
  AUTO_TRACE();
  Token retval = Token::make_RetVal_OK();
  auto ns = AutoNodeStack(parser(),thisVariant());
  // first parse any number of paragraphs
  bool isFirst=TRUE;
  DocPara *lastPar=nullptr;
  do
  {
    children().append<DocPara>(parser(),thisVariant());
    DocPara *par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse();
    if (!par->isEmpty())
    {
      if (lastPar) lastPar->markLast(FALSE);
      lastPar=par;
    }
    else
    {
      children().pop_back();
    }
    // next paragraph should be more indented than the - marker to belong
    // to this item
  } while (retval.is(TokenRetval::TK_NEWPARA) && parser()->context.token->indent>m_indent);
  if (lastPar) lastPar->markLast();
  AUTO_TRACE_EXIT("retval={}",retval.to_string());
  return retval;
}
References DocNodeList::append(), AUTO_TRACE, AUTO_TRACE_EXIT, DocCompoundNode::children(), FALSE, DocNodeList::get_last(), Token::is(), m_indent, DocPara::markLast(), DocNode::parser(), GrowVector< T >::pop_back(), DocNode::thisVariant(), Token::to_string(), and TRUE.
Member Data Documentation
m_indent
int DocAutoListItem::m_indent = 0 private
Definition at line 582 of file docnode.h.
Referenced by DocAutoListItem(), and parse().
m_itemNum
int DocAutoListItem::m_itemNum = 0 private
Definition at line 583 of file docnode.h.
Referenced by DocAutoListItem(), and itemNumber().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp