Doxygen: XMLParser Class Reference
XMLParser Class Reference
#include <libxml/xml.h>
Classes
struct Private
Public Types
using Transcode = bool(std::string &,const char *)
Public Member Functions
XMLParser (const XMLHandlers &handlers)
~XMLParser () override
XMLParser (const XMLParser &)=delete
XMLParser & operator= (const XMLParser &)=delete
XMLParser (XMLParser &&)=delete
XMLParser & operator= (XMLParser &&)=delete
void parse (const char *fileName, const char *inputString, bool debugEnabled, std::function< void()> debugStart, std::function< void()> debugEnd, std::function< Transcode > transcoder=[](std::string &s, const char *){ return true;})
Public Member Functions inherited from XMLLocator
XMLLocator ()=default
XMLLocator (const XMLLocator &)=delete
XMLLocator & operator= (const XMLLocator &)=delete
XMLLocator (XMLLocator &&)=delete
XMLLocator & operator= (XMLLocator &&)=delete
virtual ~XMLLocator ()=default
Private Member Functions
int lineNr () const override
std::string fileName () const override
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Very basic SAX style parser to parse XML documents.
Definition at line 70 of file xml.h.
Member Typedef Documentation
Transcode
using XMLParser::Transcode = bool(std::string &,const char *)
Definition at line 86 of file xml.h.
Constructor & Destructor Documentation
XMLParser() [1/3]
XMLParser::XMLParser (const XMLHandlers & handlers)
Creates an instance of the parser object. Different instances can run on different threads without interference.
Parameters
handlers The event handlers passed by the client.
Definition at line 436 of file xml.l.
                                                : p(new Private)
{
  xmlYYlex_init_extra(&p->xmlYY_extra,&p->yyscanner);
  p->xmlYY_extra.handlers = handlers;
}
References p.
Referenced by operator=(), operator=(), XMLParser(), and XMLParser().
~XMLParser()
XMLParser::~XMLParser () override
Destructor
Definition at line 442 of file xml.l.
{
  xmlYYlex_destroy(p->yyscanner);
}
References p.
XMLParser() [2/3]
XMLParser::XMLParser (const XMLParser &) delete
References XMLParser().
XMLParser() [3/3]
XMLParser::XMLParser (XMLParser &&) delete
References XMLParser().
Member Function Documentation
fileName()
std::string XMLParser::fileName () const override private virtual
Implements XMLLocator.
Definition at line 507 of file xml.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  return yyextra->fileName;
}
References p.
Referenced by parse().
lineNr()
int XMLParser::lineNr () const override private virtual
Implements XMLLocator.
Definition at line 501 of file xml.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  return yyextra->lineNr;
}
References p.
operator=() [1/2]
XMLParser & XMLParser::operator= (const XMLParser &) delete
References XMLParser().
operator=() [2/2]
XMLParser & XMLParser::operator= (XMLParser &&) delete
References XMLParser().
parse()
void XMLParser::parse (const char * fileName, const char * inputString, bool debugEnabled, std::function< void()> debugStart, std::function< void()> debugEnd, std::function< Transcode > transcoder = [](std::string&s,const char *){ return true; })
Parses a file gives the contents of the file as a string.
Parameters
fileName the name of the file, used for error reporting.
inputString the contents of the file as a zero terminated UTF-8 string.
debugEnabled indicates if debugging via -d lex is enabled or not.
debugStart hook that is to be called before starting with parsing
debugEnd hook that is to be called after finishing with parsing
transcoder hook that is to be called when transcoding text to UTF-8
Definition at line 447 of file xml.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
#ifdef FLEX_DEBUG
  xmlYYset_debug(debugEnabled?1:0,p->yyscanner);
#endif
  if (inputStr==nullptr || inputStr[0]=='\0') return; // empty input
  debugStart();
  BEGIN(Initial);
  yyextra->fileName      = fileName;
  yyextra->lineNr        = 1;
  yyextra->inputString   = inputStr;
  yyextra->inputPosition = 0;
  yyextra->transcodeFunc = transcodeFunc;
  if (static_cast<unsigned char>(inputStr[0])==0xEF &&
      static_cast<unsigned char>(inputStr[1])==0xBB &&
      static_cast<unsigned char>(inputStr[2])==0xBF)
  {
    yyextra->inputPosition = 3; // remove UTF-8 BOM
  }
  xmlYYrestart( 0, yyscanner );
  if (yyextra->handlers.startDocument)
  {
    yyextra->handlers.startDocument();
  }
  xmlYYlex(yyscanner);
  if (yyextra->handlers.endDocument)
  {
    yyextra->handlers.endDocument();
  }
  if (!yyextra->xpath.empty())
  {
    std::string tagName = yyextra->xpath.back();
    std::string msg = "End of file reached while expecting closing tag '"+tagName+"'";
    reportError(yyscanner,msg);
  }
  debugEnd();
}
References fileName(), msg(), p, and reportError().
Referenced by LayoutDocManager::init(), LayoutDocManager::parse(), and parseTagFile().
Member Data Documentation
p
std::unique_ptr<Private> XMLParser::p private
Definition at line 109 of file xml.h.
Referenced by fileName(), lineNr(), parse(), XMLParser(), and ~XMLParser().
The documentation for this class was generated from the following files:
libxml/xml.h
libxml/xml.l