Doxygen: TranslatorCatalan Class Reference
TranslatorCatalan Class Reference
#include <src/translator_ca.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
Public Member Functions inherited from TranslatorAdapter_1_8_0
QCString updateNeededMessage () override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) override methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include "translator.h" or "translator_adapter.h" here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 43 of file translator_ca.h.
Member Function Documentation
getLanguageString()
QCString TranslatorCatalan::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 82 of file translator_ca.h.
    {
      return "0x403 Catalan";
    }
idLanguage()
QCString TranslatorCatalan::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 55 of file translator_ca.h.
    { return "catalan"; }
latexLanguageSupportCommand()
QCString TranslatorCatalan::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 72 of file translator_ca.h.
    {
      //return "\\usepackage[catalan]{babel}\n\\usepackage[latin1]{inputenc}";
      return "\\usepackage[catalan]{babel}\n";
    }
trAll()
QCString TranslatorCatalan::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1380 of file translator_ca.h.
    {
      return "Tot";
    }
trAttention()
QCString TranslatorCatalan::trAttention () inline override virtual
Implements Translator.
Definition at line 966 of file translator_ca.h.
    {
      return "Atenci";
    }
trAuthor()
QCString TranslatorCatalan::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1253 of file translator_ca.h.
    {
      return createNoun(first_capital, singular, "autor", "s");
    }
References Translator::createNoun().
trBug()
QCString TranslatorCatalan::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1125 of file translator_ca.h.
    {
      return "Error";
    }
trBugList()
QCString TranslatorCatalan::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1130 of file translator_ca.h.
    {
      return "Llista d'Errors";
    }
trCallerGraph()
QCString TranslatorCatalan::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1499 of file translator_ca.h.
    {
      return "Grfic de crides a aquesta funci:";
    }
trCallGraph()
QCString TranslatorCatalan::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1385 of file translator_ca.h.
    {
      return "Grfic de crides d'aquesta funci:";
    }
trCiteReferences()
QCString TranslatorCatalan::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1825 of file translator_ca.h.
    { return "Referncies Bibliogrfiques"; }
trClass()
QCString TranslatorCatalan::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1188 of file translator_ca.h.
    {
      return createNoun(first_capital, singular, "classe", "s");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorCatalan::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 516 of file translator_ca.h.
    {
      return "Diagrama d'Herncia per a "+clName+":";
    }
trClassDocumentation()
QCString TranslatorCatalan::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 397 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaci de les Estructures de Dades";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentaci de les Classes";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorCatalan::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1088 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructures de Dades";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorCatalan::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 181 of file translator_ca.h.
    { return "Jerarquia de Classes"; }
trClassHierarchyDescription()
QCString TranslatorCatalan::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 240 of file translator_ca.h.
    { return "Aquesta llista d'herncia est ordenada toscament, "
             "per no completa, de forma alfabtica:";
    }
trCode()
QCString TranslatorCatalan::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 866 of file translator_ca.h.
    {
      return "codi";
    }
trCollaborationDiagram()
QCString TranslatorCatalan::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 821 of file translator_ca.h.
    {
      return "Diagrama de collaboraci per a "+clName+":";
    }
trCompoundIndex()
QCString TranslatorCatalan::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 370 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndex d'Estructures de Dades";
      }
      else
      {
        return "ndex de Classes";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorCatalan::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1553 of file translator_ca.h.
    { return "ndex de Tipus de Dades"; }
trCompoundList()
QCString TranslatorCatalan::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 185 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructures de Dades";
      }
      else
      {
        return "Llista de Classes";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorCatalan::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 255 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Aquestes sn les estructures de dades acompanyades amb breus descripcions:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Aquestes sn les classes acompanyades amb breus descripcions:";
      }
      else
      {
        return "Aquestes sn les classes, estructures, "
               "unions i interfcies acompanyades amb breus descripcions:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorCatalan::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1527 of file translator_ca.h.
    { return "Aquests sn els tipus de dades acompanyats amb breus descripcions:"; }
trCompoundListFortran()
QCString TranslatorCatalan::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1519 of file translator_ca.h.
    { return "Llista de Tipus de Dades"; }
trCompoundMembers()
QCString TranslatorCatalan::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 202 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Camps de Dades";
      }
      else
      {
        return "Membres de Classes";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorCatalan::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 274 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="camps d'estructures i unions";
      }
      else
      {
        result+="membres de classe";
      }
      if (!extractAll)
      {
        result+=" documentats";
      }
      result+=" amb enllaos a ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la documentaci de l'estructura/uni per a cada camp:";
        }
        else
        {
          result+="la documentaci de la classe per a cada membre:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="les estructures/unions a que pertanyen:";
        }
        else
        {
          result+="les classes a que pertanyen:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorCatalan::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1531 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els membres de tipus de dades";
      if (!extractAll)
      {
        result+=" documentats";
      }
      result+=" amb enllaos a ";
      if (!extractAll)
      {
        result+="la documentaci del tipus de dades per a cada membre:";
      }
      else
      {
        result+="els tipus de dades a que pertanyen:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorCatalan::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1523 of file translator_ca.h.
    { return "Camps de Dades"; }
trCompoundReference()
QCString TranslatorCatalan::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 591 of file translator_ca.h.
    {
      QCString result="Referncia de";
      switch(compType)
      {
        case ClassDef::Class:      result+=" la Classe "; break;
        case ClassDef::Struct:     result+=" l'Estructura "; break;
        case ClassDef::Union:      result+=" la Uni "; break;
        case ClassDef::Interface:  result+=" la Interfcie "; break;
        case ClassDef::Protocol:   result+="l Protocol "; break;
        case ClassDef::Category:   result+=" la Categoria "; break;
        case ClassDef::Exception:  result+=" l'Excepci "; break;
        default: break;
      }
      if (isTemplate) result+="Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorCatalan::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1594 of file translator_ca.h.
    {
      QCString result="Referncia de";
      switch(compType)
      {
        case ClassDef::Class:      result+=" el Mdul "; break;
        case ClassDef::Struct:     result+=" el Tipus "; break;
        case ClassDef::Union:      result+=" la Uni "; break;
        case ClassDef::Interface:  result+=" la Interfcie "; break;
        case ClassDef::Protocol:   result+="l Protocol "; break;
        case ClassDef::Category:   result+=" la Categoria "; break;
        case ClassDef::Exception:  result+=" l'Excepci "; break;
        default: break;
      }
      if (isTemplate) result+="Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorCatalan::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 492 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructures de Dades";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorCatalan::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 831 of file translator_ca.h.
    {
      return "Documentaci del Constructor i el Destructor";
    }
trCopyright()
QCString TranslatorCatalan::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1829 of file translator_ca.h.
    { return "Copyright"; }
trDataTypes()
QCString TranslatorCatalan::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1577 of file translator_ca.h.
    { return "Tipus de Dades"; }
trDate()
QCString TranslatorCatalan::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 530 of file translator_ca.h.
    { return "Data"; }
trDateTime()
QCString TranslatorCatalan::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1778 of file translator_ca.h.
    {
      static const char *days[]   = { "Dl","Dt","Dc","Dj","Dv","Ds","Dg" };
      static const char *months[] = { "Gen","Feb","Mar","Abr","Mai","Jun","Jul","Ago","Sep","Oct","Nov","Dec" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorCatalan::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1798 of file translator_ca.h.
    {
      static const char *days_short[]   = { "dl.", "dt.", "dc.", "dj.", "dv.", "ds.", "dg." };
      static const char *days_full[]    = { "dilluns", "dimarts", "dimecres", "dijous", "divendres", "dissabte", "diumenge" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorCatalan::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1814 of file translator_ca.h.
    {
      static const char *dayPeriod[] = { "a.m.", "p.m." };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorCatalan::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 798 of file translator_ca.h.
    {
      return "Definici a la lnia @0 del fitxer @1.";
    }
trDefinedIn()
QCString TranslatorCatalan::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 169 of file translator_ca.h.
    { return "definit a"; }
trDefinedInSourceFile()
QCString TranslatorCatalan::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 802 of file translator_ca.h.
    {
      return "Definici al fitxer @0.";
    }
trDefineDocumentation()
QCString TranslatorCatalan::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 462 of file translator_ca.h.
    { return "Documentaci de les Definicions"; }
trDefines()
QCString TranslatorCatalan::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 426 of file translator_ca.h.
    { return "Definicions"; }
trDefineValue()
QCString TranslatorCatalan::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1115 of file translator_ca.h.
    {
      return "Valor:";
    }
trDeprecated()
QCString TranslatorCatalan::trDeprecated () inline override virtual
Implements Translator.
Definition at line 811 of file translator_ca.h.
    {
      return "Antiquat";
    }
trDeprecatedList()
QCString TranslatorCatalan::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1308 of file translator_ca.h.
    {
      return "Llista d'Antiquats";
    }
trDetailedDescription()
QCString TranslatorCatalan::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 98 of file translator_ca.h.
    { return "Descripci Detallada"; }
trDetails()
QCString TranslatorCatalan::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 102 of file translator_ca.h.
    { return "Detalls"; }
trDir()
QCString TranslatorCatalan::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1475 of file translator_ca.h.
    {
      return createNoun(first_capital, singular, "directori", "s");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorCatalan::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1833 of file translator_ca.h.
    { return QCString("Graf de dependncia de directoris per a ")+name+":"; }
trDirDocumentation()
QCString TranslatorCatalan::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1457 of file translator_ca.h.
    { return "Documentaci dels Directoris"; }
trDirectories()
QCString TranslatorCatalan::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1463 of file translator_ca.h.
    { return "Directoris"; }
trDirIndex()
QCString TranslatorCatalan::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1451 of file translator_ca.h.
    { return "Jerarquia de Directoris"; }
trDirReference()
QCString TranslatorCatalan::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1469 of file translator_ca.h.
    { QCString result="Referncia del Directori "; result+=dirName; return result; }
trDirRelation()
QCString TranslatorCatalan::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1717 of file translator_ca.h.
    {
      return QCString(name)+" Relaci";
    }
trDocumentation()
QCString TranslatorCatalan::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 352 of file translator_ca.h.
    { return (!projName.isEmpty()?projName + " " : "") + ": Documentaci"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorCatalan::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 438 of file translator_ca.h.
    { return "Enumeracions"; }
trEnumerationTypeDocumentation()
QCString TranslatorCatalan::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 474 of file translator_ca.h.
    { return "Documentaci dels Tipus de les Enumeracions"; }
trEnumerationValueDocumentation()
QCString TranslatorCatalan::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1507 of file translator_ca.h.
    { return "Documentaci de les Enumeracions"; }
trEnumerationValues()
QCString TranslatorCatalan::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 456 of file translator_ca.h.
    { return "Valors de les Enumeracions"; }
trEnumName()
QCString TranslatorCatalan::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 161 of file translator_ca.h.
    { return "nom de la enum"; }
trEnumValue()
QCString TranslatorCatalan::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 165 of file translator_ca.h.
    { return "valors de la enum"; }
trEventDocumentation()
QCString TranslatorCatalan::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1325 of file translator_ca.h.
    {
      return "Documentaci dels Esdeveniments";
    }
trEvents()
QCString TranslatorCatalan::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1320 of file translator_ca.h.
    {
      return "Esdeveniments";
    }
trExamples()
QCString TranslatorCatalan::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 232 of file translator_ca.h.
    { return "Exemples"; }
trExamplesDescription()
QCString TranslatorCatalan::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 337 of file translator_ca.h.
    { return "Aquesta s la llista de tots els exemples:"; }
trExceptions()
QCString TranslatorCatalan::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 546 of file translator_ca.h.
    { return "Excepcions"; }
trFile()
QCString TranslatorCatalan::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1197 of file translator_ca.h.
    {
      return createNoun(first_capital, singular, "fitxer", "s");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorCatalan::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 416 of file translator_ca.h.
    { return "Documentaci dels Fitxers"; }
trFileIn()
QCString TranslatorCatalan::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1754 of file translator_ca.h.
    {
      return "Fitxer a "+name;
    }
trFileIndex()
QCString TranslatorCatalan::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 385 of file translator_ca.h.
    { return "ndex de Fitxers"; }
trFileList()
QCString TranslatorCatalan::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 198 of file translator_ca.h.
    { return "Llista dels Fitxers"; }
trFileListDescription()
QCString TranslatorCatalan::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 246 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els fitxers ";
      if (!extractAll) result+="documentats ";
      result+="acompanyats amb breus descripcions:";
      return result;
    }
trFileMembers()
QCString TranslatorCatalan::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 215 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals";
      }
      else
      {
        return "Membres de Fitxers";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorCatalan::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 315 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="totes les funcions, variables, definicions, enumeracions, i definicions de tipus";
        if (!extractAll) result+=" documentades";
      }
      else
      {
        result+="tots els membres de fitxers";
        if (!extractAll) result+=" documentats";
      }
      result+=" amb enllaos ";
      if (extractAll)
        result+="als fitxers als quals corresponen:";
      else
        result+="a la documentaci:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorCatalan::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 613 of file translator_ca.h.
    {
      QCString result="Referncia del Fitxer ";
      result+=fileName;
      return result;
    }
trFriends()
QCString TranslatorCatalan::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 573 of file translator_ca.h.
    { return "Classes Amigues"; }
trFunctionDocumentation()
QCString TranslatorCatalan::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 480 of file translator_ca.h.
    { return "Documentaci de les Funcions"; }
trFunctions()
QCString TranslatorCatalan::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 444 of file translator_ca.h.
    { return "Funcions"; }
trGeneratedAt()
QCString TranslatorCatalan::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 507 of file translator_ca.h.
    {
      QCString result="Generat a "+date;
      if (!projName.isEmpty()) result+=" per a "+projName;
      result+=" per";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorCatalan::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 153 of file translator_ca.h.
    { QCString result="Generat automticament per Doxygen";
      if (!s.isEmpty()) result+=" per a "+s;
      result+=" a partir del codi font.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorCatalan::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 550 of file translator_ca.h.
    { return "Generat per"; }
trGeneratedFromFiles()
QCString TranslatorCatalan::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 750 of file translator_ca.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentaci d'aquest";
      switch(compType)
      {
        case ClassDef::Class:      result+="a classe"; break;
        case ClassDef::Struct:     result+="a estructura"; break;
        case ClassDef::Union:      result+="a uni"; break;
        case ClassDef::Interface:  result+="a interfcie"; break;
        case ClassDef::Protocol:   result+=" protocol"; break;
        case ClassDef::Category:   result+="a categoria"; break;
        case ClassDef::Exception:  result+="a excepci"; break;
        default: break;
      }
      result+=" es va generar a partir del";
      if (!single) result+="s";
      result+=" segent";
      if (!single) result+="s";
      result+=" fitxer";
      if (!single) result+="s:"; else result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorCatalan::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1664 of file translator_ca.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentaci d'aquest";
      switch(compType)
      {
        case ClassDef::Class:      result+=" mdul"; break;
        case ClassDef::Struct:     result+=" tipus"; break;
        case ClassDef::Union:      result+="a uni"; break;
        case ClassDef::Interface:  result+="a interfcie"; break;
        case ClassDef::Protocol:   result+=" protocol"; break;
        case ClassDef::Category:   result+="a categoria"; break;
        case ClassDef::Exception:  result+="a excepci"; break;
        default: break;
      }
      result+=" es va generar a partir del";
      if (!single) result+="s";
      result+=" segent";
      if (!single) result+="s";
      result+=" fitxer";
      if (!single) result+="s:"; else result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorCatalan::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1242 of file translator_ca.h.
    {
      return createNoun(first_capital, singular, "global", "s");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorCatalan::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1729 of file translator_ca.h.
    {
      return "Espai de Noms Global";
    }
trGotoDocumentation()
QCString TranslatorCatalan::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 841 of file translator_ca.h.
    {
      return "Veure la documentaci d'aquest fitxer.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorCatalan::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 874 of file translator_ca.h.
    {
      return "Veure la jerarquia grfica de la classe";
    }
trGotoSourceCode()
QCString TranslatorCatalan::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 836 of file translator_ca.h.
    {
      return "Veure el codi d'aquest fitxer.";
    }
trGotoTextualHierarchy()
QCString TranslatorCatalan::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 878 of file translator_ca.h.
    {
      return "Veure la jerarquia textual de la classe";
    }
trGraphicalHierarchy()
QCString TranslatorCatalan::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 870 of file translator_ca.h.
    {
      return "Jerarquia Grfica de la Classe";
    }
trGroup()
QCString TranslatorCatalan::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1215 of file translator_ca.h.
    {
      return createNoun(first_capital, singular, "grup", "s");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorCatalan::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 364 of file translator_ca.h.
    { return "ndex Jerrquic"; }
trImplementedFromList()
QCString TranslatorCatalan::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1276 of file translator_ca.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorCatalan::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1284 of file translator_ca.h.
    {
      return "Implementat a "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorCatalan::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 970 of file translator_ca.h.
    {
      return "Aquest grfic mostra quins fitxers inclouen, "
             "de forma directa o indirecta, aquest fitxer:";
    }
trInclDepGraph()
QCString TranslatorCatalan::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 826 of file translator_ca.h.
    {
      return "Inclou el graf de dependncies per a "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorCatalan::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1763 of file translator_ca.h.
    {
      return "Inclou fitxer a "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorCatalan::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 147 of file translator_ca.h.
    { return ", incloent tots els membres heretats."; }
trInheritedByList()
QCString TranslatorCatalan::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 684 of file translator_ca.h.
    {
      return "Heretat per "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList()
QCString TranslatorCatalan::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 676 of file translator_ca.h.
    {
      return "Hereta de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorCatalan::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 861 of file translator_ca.h.
    {
      return "Valor inicial:";
    }
trInvariant()
QCString TranslatorCatalan::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 856 of file translator_ca.h.
    {
      return "Invariant";
    }
trISOLang()
QCString TranslatorCatalan::trISOLang () inline override virtual
Implements Translator.
Definition at line 78 of file translator_ca.h.
    {
      return "ca";
    }
trLegend()
QCString TranslatorCatalan::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1048 of file translator_ca.h.
    {
      return "llegenda";
    }
trLegendDocs()
QCString TranslatorCatalan::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 992 of file translator_ca.h.
    {
      return
        "Aquesta pgina explica com s'interpreten els grfics generats per doxygen.<p>\n"
        "Considera aquest exemple:\n"
        "\\code\n"
        "/*! Classe invisible per culpa del retall */\n"
        "class Invisible { };\n\n"
        "/*! Classe truncada, l'herncia est amagada */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe no documentada amb comentaris doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe heredada amb herncia pblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Una classe Template */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe heredada utilitzant herncia protegida */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe heredada utiltzant herncia privada */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe usada per la classe heretada */\n"
        "class Used { };\n\n"
        "/*! Super classe que hereda una quantitat de classes */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Resultar el grfic segent:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Les caixes del grfic superior tenen aquesta interpretaci:\n"
        "<ul>\n"
        "<li>Una caixa negra plena represent l'estructura o classe per la qual el grfic s'ha generat.\n"
        "<li>Una caixa de vora negra representa una estructura o classe documentada.\n"
        "<li>Una caixa de vora verda representa una estructura o classe indocumentada.\n"
        "<li>Una caixa de vora vermalla representa una estructura o classe documentada de la qual "
        "no es mostren totes les relacions d'herncia/inclusi. Un grfic s truncat si no s'ajusta als lmits.\n"
        "</ul>\n"
        "Les sagetes tenen aquest significat:\n"
        "<ul>\n"
        "<li>Una sageta blau fosc remarca una relaci d'herncia de tipus pblica entre dues classes.\n"
        "<li>Una sageta verd fosc remarca una relaci d'herncia de tipus protegida entre dues classes.\n"
        "<li>Una sageta roig fosc remarca una relaci d'herncia de tipus privada entre dues classes.\n"
        "<li>Una sageta puntejada de color porpra indica que una classe s continguda o usada per una altra classe."
        " La sageta s'etiqueta amb la variable o variables a travs de les quals la classe o estructura apuntada s accessible.\n"
        "<li>Una sageta puntejada de color groc indica la relaci entre una instncia template i la classe template de qu ha set instanciada."
        " La sageta s'etiqueta amb els parmetres template de la instncia.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorCatalan::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 985 of file translator_ca.h.
    {
      return "Llegenda del Grfic";
    }
trListOfAllMembers()
QCString TranslatorCatalan::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 135 of file translator_ca.h.
    { return "Llista de tots els membres"; }
trLoading()
QCString TranslatorCatalan::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1723 of file translator_ca.h.
    {
      return "Carregant...";
    }
trMainPage()
QCString TranslatorCatalan::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 785 of file translator_ca.h.
    { return "Pgina principal"; }
trMember()
QCString TranslatorCatalan::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1233 of file translator_ca.h.
    {
      return createNoun(first_capital, singular, "membre", "s");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorCatalan::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 118 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaci dels Camps";
      }
      else
      {
        return "Documentaci de les Dades Membre";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorCatalan::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 110 of file translator_ca.h.
    { return "Documentaci de les Enumeracions Membre"; }
trMemberFunctionDocumentation()
QCString TranslatorCatalan::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 114 of file translator_ca.h.
    { return "Documentaci de les Funcions Membre"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorCatalan::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1515 of file translator_ca.h.
    { return "Documentaci de les Funcions/Subrutines Membre"; }
trMemberList()
QCString TranslatorCatalan::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 139 of file translator_ca.h.
    { return "Llista dels Membres"; }
trMemberTypedefDocumentation()
QCString TranslatorCatalan::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 106 of file translator_ca.h.
    { return "Documentaci de les Definicions de Tipus Membre"; }
trModule()
QCString TranslatorCatalan::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1657 of file translator_ca.h.
    {
      return createNoun(first_capital, singular, "mdul", "s");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorCatalan::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 391 of file translator_ca.h.
    { return "Documentaci dels Mduls"; }
trModuleIndex()
QCString TranslatorCatalan::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 358 of file translator_ca.h.
    { return "ndex de Mduls"; }
trModuleReference()
QCString TranslatorCatalan::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1616 of file translator_ca.h.
    {
      QCString result="Referncia del Mdul ";
      result+=namespaceName;
      return result;
    }
trModules()
QCString TranslatorCatalan::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 177 of file translator_ca.h.
    { return "Mduls"; }
trModulesDescription()
QCString TranslatorCatalan::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 345 of file translator_ca.h.
    { return "Aquesta s la llista de mduls:"; }
trModulesIndex()
QCString TranslatorCatalan::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1650 of file translator_ca.h.
    { return "ndex de Mduls"; }
trModulesList()
QCString TranslatorCatalan::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1581 of file translator_ca.h.
    { return "Llista de Mduls"; }
trModulesListDescription()
QCString TranslatorCatalan::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1585 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els mduls ";
      if (!extractAll) result+="documentats ";
      result+="amb breus descripcions:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorCatalan::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1628 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els membres del mdul";
      if (!extractAll)
      {
        result+=" documentats";
      }
      result+=" amb enllaos a ";
      if (!extractAll)
      {
        result+="la documentaci del mdul per a cada membre:";
      }
      else
      {
        result+="els mduls a que pertanyen:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorCatalan::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1624 of file translator_ca.h.
    { return "Membres del Mdul"; }
trMonth()
QCString TranslatorCatalan::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1806 of file translator_ca.h.
    {
      static const char *months_short[] = { "gen.", "febr.", "mar", "abr.", "maig", "juny", "jul.", "ag.", "set.", "oct.", "nov.", "des." };
      static const char *months_full[]  = { "gener", "febrer", "mar", "abril", "maig", "juny", "juliol", "agost", "setembre", "octubre", "novembre", "desembre" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorCatalan::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 131 of file translator_ca.h.
    { return "Ms..."; }
trNamespace()
QCString TranslatorCatalan::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1206 of file translator_ca.h.
    {
      return createNoun(first_capital, singular, "namespace", "s");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorCatalan::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 730 of file translator_ca.h.
    { return "Documentaci de l'Espai de Noms"; }
trNamespaceIndex()
QCString TranslatorCatalan::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 724 of file translator_ca.h.
    { return "ndex d'Espais de Noms"; }
trNamespaceList()
QCString TranslatorCatalan::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 558 of file translator_ca.h.
    { return "Llista dels Espais de Noms"; }
trNamespaceListDescription()
QCString TranslatorCatalan::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 562 of file translator_ca.h.
    {
      QCString result="Aquests sn tots els espais de noms ";
      if (!extractAll) result+="documentats ";
      result+="amb breus descripcions:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorCatalan::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 710 of file translator_ca.h.
    {
      QCString result="Aquesta s la llista de tots els membres de l'espai de noms ";
      if (!extractAll) result+="documentats ";
      result+="amb enllaos a ";
      if (extractAll)
        result+="la documentaci de l'espai de noms de cada membre:";
      else
        result+="l'espai de noms al qual corresponen:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorCatalan::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 706 of file translator_ca.h.
    { return "Membres de l'Espai de Noms"; }
trNamespaceReference()
QCString TranslatorCatalan::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 621 of file translator_ca.h.
    {
      QCString result="Referncia de l'Espai de Noms ";
      result+=namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorCatalan::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 740 of file translator_ca.h.
    { return "Espais de Noms"; }
trNoMatches()
QCString TranslatorCatalan::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1741 of file translator_ca.h.
    {
      return "Cap coincidncia";
    }
trNote()
QCString TranslatorCatalan::trNote () inline override virtual
Implements Translator.
Definition at line 891 of file translator_ca.h.
    {
      return "Nota";
    }
trOverloadText()
QCString TranslatorCatalan::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1487 of file translator_ca.h.
    {
       return "Aquesta s una funci membre sobrecarregada, "
              "proveda per convenincia. Es diferencia de la funci "
              "anterior noms en els arguments que accepta.";
    }
trPackage()
QCString TranslatorCatalan::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1100 of file translator_ca.h.
    {
      return "Paquet "+name;
    }
trPackageAttribs()
QCString TranslatorCatalan::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1361 of file translator_ca.h.
    {
      return "Atributs de Paquet";
    }
trPackageFunctions()
QCString TranslatorCatalan::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1343 of file translator_ca.h.
    {
      return "Funcions de Paquet";
    }
trPackageListDescription()
QCString TranslatorCatalan::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1105 of file translator_ca.h.
    {
      return "Aquesta s la llista de paquets, amb una breu descripci (si se'n disposa):";
    }
trPackageMembers()
QCString TranslatorCatalan::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1347 of file translator_ca.h.
    {
      return "Membres de Paquet";
    }
trPackages()
QCString TranslatorCatalan::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1110 of file translator_ca.h.
    {
      return "Paquets";
    }
trPackageTypes()
QCString TranslatorCatalan::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1336 of file translator_ca.h.
    {
      return "Tipus de paquets";
    }
trPage()
QCString TranslatorCatalan::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1224 of file translator_ca.h.
    {
      return createNoun(first_capital, singular, "pgin", "es", "a");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorCatalan::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 791 of file translator_ca.h.
    { return "p."; }
trPageIndex()
QCString TranslatorCatalan::trPageIndex () inline override virtual
Implements Translator.
Definition at line 882 of file translator_ca.h.
    {
      return "ndex de Pgines";
    }
trParameters()
QCString TranslatorCatalan::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 542 of file translator_ca.h.
    { return "Parmetres"; }
trPostcondition()
QCString TranslatorCatalan::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 851 of file translator_ca.h.
    {
      return "Postcondici";
    }
trPrecondition()
QCString TranslatorCatalan::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 846 of file translator_ca.h.
    {
      return "Precondici";
    }
trPrivateAttribs()
QCString TranslatorCatalan::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 930 of file translator_ca.h.
    {
      return "Atributs Privats";
    }
trPrivateMembers()
QCString TranslatorCatalan::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 642 of file translator_ca.h.
    { return "Mtodes Privats"; }
trPrivateSlots()
QCString TranslatorCatalan::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 644 of file translator_ca.h.
    { return "Slots Privats"; }
trPrivateTypes()
QCString TranslatorCatalan::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 926 of file translator_ca.h.
    {
      return "Tipus Privats";
    }
trProperties()
QCString TranslatorCatalan::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1073 of file translator_ca.h.
    {
      return "Propietats";
    }
trPropertyDocumentation()
QCString TranslatorCatalan::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1078 of file translator_ca.h.
    {
      return "Documentaci de les Propietats";
    }
trProtectedAttribs()
QCString TranslatorCatalan::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 918 of file translator_ca.h.
    {
      return "Atributs Protegits";
    }
trProtectedMembers()
QCString TranslatorCatalan::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 636 of file translator_ca.h.
    { return "Mtodes Protegits"; }
trProtectedSlots()
QCString TranslatorCatalan::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 638 of file translator_ca.h.
    { return "Slots Protegits"; }
trProtectedTypes()
QCString TranslatorCatalan::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 914 of file translator_ca.h.
    {
      return "Tipus Protegits";
    }
trPublicAttribs()
QCString TranslatorCatalan::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 899 of file translator_ca.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Camps de Dades";
      }
      else
      {
        return "Atributs Pblics";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorCatalan::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 628 of file translator_ca.h.
    { return "Mtodes pblics"; }
trPublicSlots()
QCString TranslatorCatalan::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 630 of file translator_ca.h.
    { return "Slots pblics"; }
trPublicTypes()
QCString TranslatorCatalan::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 895 of file translator_ca.h.
    {
      return "Tipus Pblics";
    }
trReferencedBy()
QCString TranslatorCatalan::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 958 of file translator_ca.h.
    {
      return "Referenciat a";
    }
trReferenceManual()
QCString TranslatorCatalan::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 420 of file translator_ca.h.
    { return "Manual de Referncia"; }
trReferences()
QCString TranslatorCatalan::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1264 of file translator_ca.h.
    {
      return "Referncies";
    }
trReimplementedFromList()
QCString TranslatorCatalan::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 692 of file translator_ca.h.
    {
      return "Reimplementat de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorCatalan::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 700 of file translator_ca.h.
    {
      return "Reimplementat a "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorCatalan::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 583 of file translator_ca.h.
    { return "Documentaci de funcions amigues i relacionades"; }
trRelatedFunctions()
QCString TranslatorCatalan::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 90 of file translator_ca.h.
    { return "Funcions Associades"; }
trRelatedPages()
QCString TranslatorCatalan::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 228 of file translator_ca.h.
    { return "Pgines Relacionades"; }
trRelatedPagesDescription()
QCString TranslatorCatalan::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 341 of file translator_ca.h.
    { return "Aquesta s la llista de totes les pgines de documentaci associades:"; }
trRelatedSubscript()
QCString TranslatorCatalan::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 94 of file translator_ca.h.
    { return "(Remarcar que aquestes funcions no sn funcions membre.)"; }
trRemarks()
QCString TranslatorCatalan::trRemarks () inline override virtual
Implements Translator.
Definition at line 962 of file translator_ca.h.
    {
      return "Remarca";
    }
trReturns()
QCString TranslatorCatalan::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 534 of file translator_ca.h.
    { return "Retorna"; }
trReturnValues()
QCString TranslatorCatalan::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 780 of file translator_ca.h.
    { return "Valors de retorn"; }
trRTFansicp()
QCString TranslatorCatalan::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1164 of file translator_ca.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorCatalan::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1173 of file translator_ca.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorCatalan::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1179 of file translator_ca.h.
    {
      return "ndex";
    }
trRTFTableOfContents()
QCString TranslatorCatalan::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1296 of file translator_ca.h.
    {
      return "Taula de Continguts";
    }
trSearch()
QCString TranslatorCatalan::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 236 of file translator_ca.h.
    { return "Cerca"; }
trSearching()
QCString TranslatorCatalan::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1735 of file translator_ca.h.
    {
      return "Cercant...";
    }
trSearchMatches()
QCString TranslatorCatalan::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1428 of file translator_ca.h.
    {
      return "Resultats:";
    }
trSearchResults()
QCString TranslatorCatalan::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1409 of file translator_ca.h.
    {
      if (numDocuments==0)
      {
        return "No s'ha trobat cap document.";
      }
      else if (numDocuments==1)
      {
        return "Trobat <b>1</b> document.";
      }
      else
      {
        return "Trobats <b>$num</b> documents. "
               "Mostrant els millors resultats primer.";
      }
    }
trSearchResultsTitle()
QCString TranslatorCatalan::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1397 of file translator_ca.h.
    {
      return "Resultats de la Bsqueda";
    }
trSeeAlso()
QCString TranslatorCatalan::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 538 of file translator_ca.h.
    { return "Mireu tamb"; }
trSignals()
QCString TranslatorCatalan::trSignals () inline override virtual
Implements Translator.
Definition at line 632 of file translator_ca.h.
    { return "Senyals"; }
trSince()
QCString TranslatorCatalan::trSince () inline override virtual
Implements Translator.
Definition at line 975 of file translator_ca.h.
    {
      return "Des de";
    }
trSourceFile()
QCString TranslatorCatalan::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1439 of file translator_ca.h.
    {
      return "Fitxer de Codi " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorCatalan::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1368 of file translator_ca.h.
    {
      return "Atributs Esttics de Paquet";
    }
trStaticPackageFunctions()
QCString TranslatorCatalan::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1354 of file translator_ca.h.
    {
      return "Funcions Esttiques de Paquet";
    }
trStaticPrivateAttribs()
QCString TranslatorCatalan::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 934 of file translator_ca.h.
    {
      return "Atributs Privats Esttics";
    }
trStaticPrivateMembers()
QCString TranslatorCatalan::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 646 of file translator_ca.h.
    { return "Mtodes Privats Esttics"; }
trStaticProtectedAttribs()
QCString TranslatorCatalan::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 922 of file translator_ca.h.
    {
      return "Atributs Protegits Esttics";
    }
trStaticProtectedMembers()
QCString TranslatorCatalan::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 640 of file translator_ca.h.
    { return "Mtodes Protegits Esttics"; }
trStaticPublicAttribs()
QCString TranslatorCatalan::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 910 of file translator_ca.h.
    {
      return "Atributs Pblics Esttics";
    }
trStaticPublicMembers()
QCString TranslatorCatalan::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 634 of file translator_ca.h.
    { return "Mtodes Pblics Esttics"; }
trSubprogram()
QCString TranslatorCatalan::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1701 of file translator_ca.h.
    {
      return createNoun(first_capital, singular, "subprogram", "es", "a");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorCatalan::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1571 of file translator_ca.h.
    { return "Documentaci de les Funcions/Subrutines"; }
trSubprograms()
QCString TranslatorCatalan::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1565 of file translator_ca.h.
    { return "Funcions/Subrutines"; }
trTest()
QCString TranslatorCatalan::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1058 of file translator_ca.h.
    {
      return "Prova";
    }
trTestList()
QCString TranslatorCatalan::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1063 of file translator_ca.h.
    {
      return "Llista de proves";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorCatalan::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 143 of file translator_ca.h.
    { return "Aquesta s la llista complerta dels membres de"; }
trTodo()
QCString TranslatorCatalan::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 944 of file translator_ca.h.
    {
      return "Per fer";
    }
trTodoList()
QCString TranslatorCatalan::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 949 of file translator_ca.h.
    {
      return "Llista de coses per fer";
    }
trType()
QCString TranslatorCatalan::trType (bool first_capital, bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1693 of file translator_ca.h.
    {
      return createNoun(first_capital, false, "tipus", "");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorCatalan::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1707 of file translator_ca.h.
    {
      return "Restriccions de Tipus";
    }
trTypedefDocumentation()
QCString TranslatorCatalan::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 468 of file translator_ca.h.
    { return "Documentaci de les Definicions de Tipus"; }
trTypedefs()
QCString TranslatorCatalan::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 432 of file translator_ca.h.
    { return "Definicions de Tipus"; }
trTypeDocumentation()
QCString TranslatorCatalan::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1559 of file translator_ca.h.
    { return "Documentaci dels Tipus de Dades"; }
trVariableDocumentation()
QCString TranslatorCatalan::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 486 of file translator_ca.h.
    { return "Documentaci de les Variables"; }
trVariables()
QCString TranslatorCatalan::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 450 of file translator_ca.h.
    { return "Variables"; }
trVersion()
QCString TranslatorCatalan::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 526 of file translator_ca.h.
    { return "Versi"; }
trWarning()
QCString TranslatorCatalan::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 522 of file translator_ca.h.
    { return "Atenci"; }
trWriteList()
QCString TranslatorCatalan::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 652 of file translator_ca.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_ca.h