Doxygen: FileDefImpl Class Reference
FileDefImpl Class Reference
Public Member Functions
FileDefImpl (const QCString &p, const QCString &n, const QCString &ref=QCString(), const QCString &dn=QCString())
~FileDefImpl () override
DefType definitionType () const override
CodeSymbolType codeSymbolType () const override
const QCString & name () const override
QCString displayName (bool=TRUE) const override
QCString fileName () const override
QCString getOutputFileBase () const override
QCString anchor () const override
QCString getSourceFileBase () const override
QCString includeName () const override
QCString includeDependencyGraphFileName () const override
QCString includedByDependencyGraphFileName () const override
QCString absFilePath () const override
const QCString & docName () const override
bool isSource () const override
bool isDocumentationFile () const override
const Definition * getSourceDefinition (int lineNr) const override
const MemberDef * getSourceMember (int lineNr) const override
QCString getPath () const override
QCString getVersion () const override
bool isLinkableInProject () const override
bool isLinkable () const override
bool isIncluded (const QCString &name) const override
DirDef * getDirDef () const override
ModuleDef * getModuleDef () const override
const LinkedRefMap< NamespaceDef > & getUsedNamespaces () const override
const LinkedRefMap< ClassDef > & getUsedClasses () const override
const IncludeInfoList & includeFileList () const override
const IncludeInfoList & includedByFileList () const override
void getAllIncludeFilesRecursively (StringVector &incFiles) const override
MemberList * getMemberList (MemberListType lt) const override
const MemberLists & getMemberLists () const override
const MemberGroupList & getMemberGroups () const override
const NamespaceLinkedRefMap & getNamespaces () const override
const ConceptLinkedRefMap & getConcepts () const override
const ClassLinkedRefMap & getClasses () const override
QCString title () const override
bool hasDetailedDescription () const override
QCString fileVersion () const override
bool subGrouping () const override
void countMembers () override
int numDocMembers () const override
int numDecMembers () const override
void addSourceRef (int line, const Definition *d, const MemberDef *md) override
void writeDocumentation (OutputList &ol) override
void writeMemberPages (OutputList &ol) override
void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const override
void writeSummaryLinks (OutputList &ol) const override
void writeTagFile (TextStream &t) override
void writeSourceHeader (OutputList &ol) override
void writeSourceBody (OutputList &ol, ClangTUParser *clangParser) override
void writeSourceFooter (OutputList &ol) override
void parseSource (ClangTUParser *clangParser) override
void setDiskName (const QCString &name) override
void insertMember (MemberDef *md) override
void insertClass (ClassDef *cd) override
void insertConcept (ConceptDef *cd) override
void insertNamespace (NamespaceDef *nd) override
void computeAnchors () override
void setDirDef (DirDef *dd) override
void setModuleDef (ModuleDef *mod) override
void addUsingDirective (NamespaceDef *nd) override
void addUsingDeclaration (ClassDef *cd) override
void combineUsingRelations () override
bool generateSourceFile () const override
void sortMemberLists () override
void addIncludeDependency (const FileDef *fd, const QCString &incName, IncludeKind kind) override
void addIncludedByDependency (const FileDef *fd, const QCString &incName, IncludeKind kind) override
void addMembersToMemberGroup () override
void distributeMemberGroupDocumentation () override
void findSectionsInDocumentation () override
void addIncludedUsingDirectives (FileDefSet &visitedFiles) override
void addListReferences () override
bool hasIncludeGraph () const override
bool hasIncludedByGraph () const override
void overrideIncludeGraph (bool e) override
void overrideIncludedByGraph (bool e) override
Public Member Functions inherited from DefinitionMixin< FileDef >
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=nullptr, const char *d=nullptr, bool isSymbol=TRUE)
~DefinitionMixin ()=default
bool isAlias () const override
bool isAnonymous () const override
const QCString & localName () const override
QCString qualifiedName () const override
QCString symbolName () const override
QCString getSourceAnchor () const override
QCString documentation () const override
int docLine () const override
QCString docFile () const override
QCString briefDescription (bool abbreviate=FALSE) const override
QCString briefDescriptionAsTooltip () const override
int briefLine () const override
QCString inbodyDocumentation () const override
QCString inbodyFile () const override
int inbodyLine () const override
QCString briefFile () const override
QCString getDefFileName () const override
QCString getDefFileExtension () const override
int getDefLine () const override
int getDefColumn () const override
bool hasDocumentation () const override
bool hasUserDocumentation () const override
bool isVisibleInProject () const override
bool isVisible () const override
bool isHidden () const override
bool isArtificial () const override
bool isExported () const override
QCString getReference () const override
bool isReference () const override
QCString externalReference (const QCString &relPath) const override
int getStartDefLine () const override
int getStartBodyLine () const override
int getEndBodyLine () const override
const FileDef * getBodyDef () const override
SrcLangExt getLanguage () const override
const GroupList & partOfGroups () const override
bool isLinkableViaGroup () const override
const RefItemVector & xrefListItems () const override
const Definition * findInnerCompound (const QCString &name) const override
Definition * getOuterScope () const override
const MemberVector & getReferencesMembers () const override
const MemberVector & getReferencedByMembers () const override
bool hasSections () const override
bool hasSources () const override
bool hasBriefDescription () const override
QCString id () const override
const SectionRefs & getSectionRefs () const override
void setName (const QCString &name) override
void setId (const QCString &name) override
void setDefFile (const QCString &df, int defLine, int defColumn) override
void setDocumentation (const QCString &doc, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE) override
void setBriefDescription (const QCString &brief, const QCString &briefFile, int briefLine) override
void setInbodyDocumentation (const QCString &doc, const QCString &docFile, int docLine) override
void setReference (const QCString &r) override
void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList) override
void setBodySegment (int defLine, int bls, int ble) override
void setBodyDef (const FileDef *fd) override
void addSourceReferencedBy (MemberDef *md) override
void addSourceReferences (MemberDef *md) override
void setRefItems (const RefItemVector &sli) override
void mergeRefItems (Definition *def) override
void mergeReferences (const Definition *other) override
void mergeReferencedBy (const Definition *other) override
void addInnerCompound (Definition *def) override
void setOuterScope (Definition *def) override
void setHidden (bool b) override
void setArtificial (bool b) override
void setExported (bool b) override
void setLanguage (SrcLangExt lang) override
void writeSourceDef (OutputList &ol, const QCString &scopeName) const override
void writeInlineCode (OutputList &ol, const QCString &scopeName) const override
bool hasSourceRefs () const override
bool hasSourceReffedBy () const override
void writeSourceRefs (OutputList &ol, const QCString &scopeName) const override
void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const override
void makePartOfGroup (GroupDef *gd) override
void writeNavigationPath (OutputList &ol) const override
QCString navigationPathAsString () const override
QCString pathFragment () const override
void writeDocAnchorsToTagFile (TextStream &fs) const override
void setLocalName (const QCString &name) override
void addSectionsToIndex () override
void writeToc (OutputList &ol, const LocalToc &lt) const override
void computeTooltip () override
void _setSymbolName (const QCString &name) override
QCString _symbolName () const override
Public Member Functions inherited from DefinitionMutable
virtual ~DefinitionMutable ()=default
Public Member Functions inherited from Definition
virtual ~Definition ()=default
Private Member Functions
void setDiskNameLocal (const QCString &name)
void acquireFileVersion ()
void addMemberToList (MemberListType lt, MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void writeIncludeFiles (OutputList &ol)
void writeIncludeGraph (OutputList &ol)
void writeIncludedByGraph (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void writeSourceLink (OutputList &ol)
void writeNamespaceDeclarations (OutputList &ol, const QCString &title, bool isConstantGroup)
void writeClassDeclarations (OutputList &ol, const QCString &title, const ClassLinkedRefMap &list)
void writeConcepts (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void writeClassesToTagFile (TextStream &t, const ClassLinkedRefMap &list)
Private Attributes
IncludeInfoMap m_includeMap
IncludeInfoList m_includeList
IncludeInfoMap m_includedByMap
IncludeInfoList m_includedByList
LinkedRefMap< NamespaceDef > m_usingDirList
LinkedRefMap< ClassDef > m_usingDeclList
QCString m_path
QCString m_filePath
QCString m_inclDepFileName
QCString m_inclByDepFileName
QCString m_outputDiskName
QCString m_fileName
QCString m_docname
DefinitionLineMap m_srcDefMap
MemberDefLineMap m_srcMemberMap
bool m_isSource
QCString m_fileVersion
DirDef * m_dir = nullptr
ModuleDef * m_moduleDef = nullptr
MemberLists m_memberLists
MemberGroupList m_memberGroups
NamespaceLinkedRefMap m_namespaces
ClassLinkedRefMap m_classes
ClassLinkedRefMap m_interfaces
ClassLinkedRefMap m_structs
ClassLinkedRefMap m_exceptions
ConceptLinkedRefMap m_concepts
bool m_subGrouping
bool m_hasIncludeGraph = Config_getBool(INCLUDE_GRAPH)
bool m_hasIncludedByGraph = Config_getBool(INCLUDED_BY_GRAPH)
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Protected Member Functions inherited from DefinitionMixin< FileDef >
DefinitionMixin (const DefinitionMixin &def)=default
Detailed Description
Definition at line 120 of file filedef.cpp.
Constructor & Destructor Documentation
FileDefImpl()
FileDefImpl::FileDefImpl (const QCString & p, const QCString & nm, const QCString & lref = QCString(), const QCString & dn = QCString())
create a new file definition, where p is the file path, nm the file name, and lref is an HTML anchor name if the file was read from a tag file or nullptr otherwise
Definition at line 274 of file filedef.cpp.
   : DefinitionMixin(QCString(p)+nm,1,1,nm,nullptr,nullptr,!p.isEmpty())
{
  m_path=removeLongPathMarker(p);
  m_filePath=p+nm;
  m_fileName=nm;
  setReference(lref);
  setDiskNameLocal(!dn.isEmpty() ? dn : nm);
  m_isSource          = guessSection(nm).isSource();
  m_docname           = nm;
  m_dir               = nullptr;
  if (Config_getBool(FULL_PATH_NAMES))
  {
    m_docname.prepend(stripFromPath(m_path));
  }
  setLanguage(getLanguageFromFileName(
     Config_getBool(FULL_PATH_NAMES) ? m_fileName : DefinitionMixin::name()));
  acquireFileVersion();
  m_subGrouping=Config_getBool(SUBGROUPING);
}
References acquireFileVersion(), Config_getBool, getLanguageFromFileName(), guessSection(), QCString::isEmpty(), m_dir, m_docname, m_fileName, m_filePath, m_isSource, m_path, m_subGrouping, DefinitionMixin< Base >::name(), QCString::prepend(), removeLongPathMarker(), setDiskNameLocal(), DefinitionMixin< FileDef >::setLanguage(), DefinitionMixin< FileDef >::setReference(), and stripFromPath().
~FileDefImpl()
FileDefImpl::~FileDefImpl () override
destroy the file definition
Definition at line 298 of file filedef.cpp.
{
}
Member Function Documentation
absFilePath()
QCString FileDefImpl::absFilePath () const inline override virtual
Returns the absolute path including the file name.
Implements FileDef.
Definition at line 138 of file filedef.cpp.
{ return m_filePath; }
References m_filePath.
Referenced by parseSource(), and writeSourceBody().
acquireFileVersion()
void FileDefImpl::acquireFileVersion () private
Definition at line 1577 of file filedef.cpp.
{
  QCString vercmd = Config_getString(FILE_VERSION_FILTER);
  if (!vercmd.isEmpty() && !m_filePath.isEmpty() && !isReference() &&
      m_filePath!="generated" && m_filePath!="graph_legend.dox")
  {
    msg("Version of %s : ",qPrint(m_filePath));
    QCString cmd = vercmd+" \""+m_filePath+"\"";
    Debug::print(Debug::ExtCmd,0,"Executing popen(`%s`)\n",qPrint(cmd));
    FILE *f=Portable::popen(cmd,"r");
    if (!f)
    {
      err("could not execute %s\n",qPrint(vercmd));
      return;
    }
    const int bufSize=1024;
    char buf[bufSize];
    int numRead = static_cast<int>(fread(buf,1,bufSize-1,f));
    Portable::pclose(f);
    if (numRead>0 && numRead<bufSize)
    {
      buf[numRead]='\0';
      m_fileVersion=QCString(buf,numRead).stripWhiteSpace();
      if (!m_fileVersion.isEmpty())
      {
        msg("%s\n",qPrint(m_fileVersion));
        return;
      }
    }
    msg("no version available\n");
  }
}
References Config_getString, err, Debug::ExtCmd, QCString::isEmpty(), DefinitionMixin< FileDef >::isReference(), m_filePath, m_fileVersion, msg(), Portable::pclose(), Portable::popen(), Debug::print(), qPrint(), and QCString::stripWhiteSpace().
Referenced by FileDefImpl().
addIncludedByDependency()
void FileDefImpl::addIncludedByDependency (const FileDef * fd, const QCString & incName, IncludeKind kind) override virtual
Implements FileDef.
Definition at line 1483 of file filedef.cpp.
{
  //printf("FileDefImpl::addIncludedByDependency(%p,%s,%d)\n",fd,incName,local);
  QCString iName = fd ? fd->absFilePath() : incName;
  if (!iName.isEmpty() && m_includedByMap.find(iName.str())==m_includedByMap.end())
  {
    m_includedByList.emplace_back(fd,incName,kind);
    m_includedByMap.insert(std::make_pair(iName.str(),&m_includedByList.back()));
  }
}
References FileDef::absFilePath(), QCString::isEmpty(), m_includedByList, m_includedByMap, and QCString::str().
addIncludeDependency()
void FileDefImpl::addIncludeDependency (const FileDef * fd, const QCString & incName, IncludeKind kind) override virtual
Implements FileDef.
Definition at line 1424 of file filedef.cpp.
{
  //printf("FileDefImpl::addIncludeDependency(%p,%s,%d)\n",fd,incName,local);
  QCString iName = fd ? fd->absFilePath() : incName;
  if (!iName.isEmpty() && m_includeMap.find(iName.str())==m_includeMap.end())
  {
    m_includeList.emplace_back(fd,incName,kind);
    m_includeMap.insert(std::make_pair(iName.str(),&m_includeList.back()));
  }
}
References FileDef::absFilePath(), QCString::isEmpty(), m_includeList, m_includeMap, and QCString::str().
addIncludedUsingDirectives()
void FileDefImpl::addIncludedUsingDirectives (FileDefSet & visitedFiles) override virtual
Implements FileDef.
Definition at line 1435 of file filedef.cpp.
{
  if (visitedFiles.find(this)!=visitedFiles.end()) return; // file already processed
  visitedFiles.insert(this);
  //printf("( FileDefImpl::addIncludedUsingDirectives for file %s\n",qPrint(name()));
  if (!m_includeList.empty()) // file contains #includes
  {
    {
      for (const auto &ii : m_includeList) // foreach #include...
      {
        if (ii.fileDef) // ...that is a known file
        {
          // recurse into this file
          const_cast<FileDef*>(ii.fileDef)->addIncludedUsingDirectives(visitedFiles);
        }
      }
    }
    {
      // iterate through list from last to first
      for (auto ii_it = m_includeList.rbegin(); ii_it!=m_includeList.rend(); ++ii_it)
      {
        auto &ii = *ii_it;
        if (ii.fileDef && ii.fileDef!=this)
        {
          // add using directives
          auto unl = ii.fileDef->getUsedNamespaces();
          for (auto it = unl.rbegin(); it!=unl.rend(); ++it)
          {
            auto *nd = *it;
            //printf("  adding using directive for %s\n",qPrint(nd->qualifiedName()));
            m_usingDirList.prepend(nd->qualifiedName(),nd);
          }
          // add using declarations
          auto  udl = ii.fileDef->getUsedClasses();
          for (auto it = udl.rbegin(); it!=udl.rend(); ++it)
          {
            auto *cd = *it;
            m_usingDeclList.prepend(cd->qualifiedName(),cd);
          }
        }
      }
    }
  }
  //printf(") end FileDefImpl::addIncludedUsingDirectives for file %s\n",qPrint(name()));
}
References addIncludedUsingDirectives(), FileDef::getUsedNamespaces(), m_includeList, m_usingDeclList, m_usingDirList, and LinkedRefMap< T, Hash, KeyEqual, Map >::prepend().
Referenced by addIncludedUsingDirectives().
addListReferences()
void FileDefImpl::addListReferences () override virtual
Implements FileDef.
Definition at line 1512 of file filedef.cpp.
{
  {
    const RefItemVector &xrefItems = xrefListItems();
    addRefItem(xrefItems,
               getOutputFileBase(),
               theTranslator->trFile(TRUE,TRUE),
               getOutputFileBase(),name(),
               QCString(),
               nullptr
              );
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->addListReferences(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
      ml->addListReferences(this);
    }
  }
}
References addRefItem(), getOutputFileBase(), m_memberGroups, m_memberLists, MemberListType_documentationLists, name(), theTranslator, Translator::trFile(), TRUE, and DefinitionMixin< FileDef >::xrefListItems().
addMembersToMemberGroup()
void FileDefImpl::addMembersToMemberGroup () override virtual
Implements FileDef.
Definition at line 1244 of file filedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ::addMembersToMemberGroup(ml.get(),&m_memberGroups,this);
    }
  }
  // add members inside sections to their groups
  for (const auto &mg : m_memberGroups)
  {
    if (mg->allMembersInSameSection() && m_subGrouping)
    {
      //printf("----> addToDeclarationSection(%s)\n",qPrint(mg->header()));
      mg->addToDeclarationSection();
    }
  }
}
References addMembersToMemberGroup(), m_memberGroups, m_memberLists, m_subGrouping, and MemberListType_declarationLists.
Referenced by addMembersToMemberGroup().
addMemberToList()
void FileDefImpl::addMemberToList (MemberListType lt, MemberDef * md) private
Definition at line 1634 of file filedef.cpp.
{
  bool sortBriefDocs = Config_getBool(SORT_BRIEF_DOCS);
  bool sortMemberDocs = Config_getBool(SORT_MEMBER_DOCS);
  const auto &ml = m_memberLists.get(lt,MemberListContainer::File);
  ml->setNeedsSorting(
       ((ml->listType()&MemberListType_declarationLists) && sortBriefDocs) ||
       ((ml->listType()&MemberListType_documentationLists) && sortMemberDocs));
  ml->push_back(md);
  if (ml->listType()&MemberListType_declarationLists)
  {
    MemberDefMutable *mdm = toMemberDefMutable(md);
    if (mdm)
    {
      mdm->setSectionList(this,ml.get());
    }
  }
}
References Config_getBool, File, MemberLists::get(), m_memberLists, MemberListType_declarationLists, MemberListType_documentationLists, MemberDefMutable::setSectionList(), and toMemberDefMutable().
Referenced by insertMember().
addSourceRef()
void FileDefImpl::addSourceRef (int line, const Definition * d, const MemberDef * md) override virtual
Implements FileDef.
Definition at line 1380 of file filedef.cpp.
{
  //printf("FileDefImpl::addSourceDef(%d,%p,%p)\n",line,d,md);
  if (d)
  {
    m_srcDefMap.insert(std::make_pair(line,d));
    if (md) m_srcMemberMap.insert(std::make_pair(line,md));
    //printf("Adding member %s with anchor %s at line %d to file %s\n",
    //    md?qPrint(md->name()):"<none>",md?qPrint(md->anchor()):"<none>",line,qPrint(name()));
  }
}
References m_srcDefMap, and m_srcMemberMap.
addUsingDeclaration()
void FileDefImpl::addUsingDeclaration (ClassDef * cd) override virtual
Implements FileDef.
Definition at line 1419 of file filedef.cpp.
{
  m_usingDeclList.add(cd->qualifiedName(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), m_usingDeclList, and Definition::qualifiedName().
Referenced by combineUsingRelations().
addUsingDirective()
void FileDefImpl::addUsingDirective (NamespaceDef * nd) override virtual
Implements FileDef.
Definition at line 1407 of file filedef.cpp.
{
  m_usingDirList.add(nd->qualifiedName(),nd);
  //printf("%p: FileDefImpl::addUsingDirective: %s:%d\n",this,qPrint(name()),usingDirList->count());
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), m_usingDirList, and Definition::qualifiedName().
Referenced by combineUsingRelations().
anchor()
QCString FileDefImpl::anchor () const inline override virtual
Returns the anchor within a page where this item can be found
Implements FileDef.
Definition at line 133 of file filedef.cpp.
{ return QCString(); }
codeSymbolType()
CodeSymbolType FileDefImpl::codeSymbolType () const inline override virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 127 of file filedef.cpp.
{ return CodeSymbolType::Default; }
References Default.
combineUsingRelations()
void FileDefImpl::combineUsingRelations () override virtual
Implements FileDef.
Definition at line 1539 of file filedef.cpp.
{
  LinkedRefMap<NamespaceDef> usingDirList = m_usingDirList;
  NamespaceDefSet visitedNamespaces;
  for (auto &nd : usingDirList)
  {
    NamespaceDefMutable *ndm = toNamespaceDefMutable(nd);
    if (ndm)
    {
      ndm->combineUsingRelations(visitedNamespaces);
    }
  }
  for (auto &nd : usingDirList)
  {
    // add used namespaces of namespace nd to this namespace
    for (const auto &und : nd->getUsedNamespaces())
    {
      addUsingDirective(und);
    }
    // add used classes of namespace nd to this namespace
    for (const auto &ucd : nd->getUsedClasses())
    {
      addUsingDeclaration(ucd);
    }
  }
}
References addUsingDeclaration(), addUsingDirective(), NamespaceDefMutable::combineUsingRelations(), m_usingDirList, and toNamespaceDefMutable().
computeAnchors()
void FileDefImpl::computeAnchors () override virtual
Compute the HTML anchor names for all members in the class
Implements FileDef.
Definition at line 324 of file filedef.cpp.
{
  MemberList *ml = getMemberList(MemberListType_allMembersList);
  if (ml) ml->setAnchors();
}
References getMemberList(), MemberListType_allMembersList, and MemberList::setAnchors().
countMembers()
void FileDefImpl::countMembers () override virtual
Implements FileDef.
Definition at line 1776 of file filedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    ml->countDecMembers();
    ml->countDocMembers();
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->countDecMembers();
    mg->countDocMembers();
  }
}
References m_memberGroups, and m_memberLists.
definitionType()
DefType FileDefImpl::definitionType () const inline override virtual
Use this for dynamic inspection of the type of the derived class
Implements FileDef.
Definition at line 126 of file filedef.cpp.
{ return TypeFile; }
References Definition::TypeFile.
displayName()
QCString FileDefImpl::displayName (bool includeScope = TRUE) const inline override virtual
Returns the name of the definition as it appears in the output
Implements FileDef.
Definition at line 130 of file filedef.cpp.
{ return localName(); }
References DefinitionMixin< FileDef >::localName().
Referenced by writeDocumentation().
distributeMemberGroupDocumentation()
void FileDefImpl::distributeMemberGroupDocumentation () override virtual
Implements FileDef.
Definition at line 330 of file filedef.cpp.
{
  //printf("FileDefImpl::distributeMemberGroupDocumentation()\n");
  for (const auto &mg : m_memberGroups)
  {
    mg->distributeMemberGroupDocumentation();
  }
}
References m_memberGroups.
docName()
const QCString & FileDefImpl::docName () const inline override virtual
Returns the name as it is used in the documentation
Implements FileDef.
Definition at line 139 of file filedef.cpp.
{ return m_docname; }
References m_docname.
endMemberDeclarations()
void FileDefImpl::endMemberDeclarations (OutputList & ol) private
Definition at line 729 of file filedef.cpp.
{
  ol.endMemberSections();
}
References OutputList::endMemberSections().
Referenced by writeDocumentation().
endMemberDocumentation()
void FileDefImpl::endMemberDocumentation (OutputList & ol) private
Definition at line 743 of file filedef.cpp.
{
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.enable(OutputType::Html);
    Doxygen::suppressDocWarnings = FALSE;
  }
}
References Config_getBool, OutputList::enable(), FALSE, Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
fileName()
QCString FileDefImpl::fileName () const inline override virtual
Implements FileDef.
Definition at line 131 of file filedef.cpp.
{ return m_fileName; }
References m_fileName.
fileVersion()
QCString FileDefImpl::fileVersion () const override virtual
Implements FileDef.
Definition at line 1761 of file filedef.cpp.
{
  return m_fileVersion;
}
References m_fileVersion.
findSectionsInDocumentation()
void FileDefImpl::findSectionsInDocumentation () override virtual
Implements FileDef.
Definition at line 339 of file filedef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
  for (const auto &mg : m_memberGroups)
  {
    mg->findSectionsInDocumentation(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ml->findSectionsInDocumentation(this);
    }
  }
}
References DefinitionMixin< FileDef >::briefDescription(), DefinitionMixin< FileDef >::docFile(), docFindSections(), DefinitionMixin< FileDef >::documentation(), m_memberGroups, m_memberLists, and MemberListType_declarationLists.
generateSourceFile()
bool FileDefImpl::generateSourceFile () const override virtual
Implements FileDef.
Definition at line 1500 of file filedef.cpp.
{
  bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
  bool verbatimHeaders = Config_getBool(VERBATIM_HEADERS);
  return !isReference() &&
         (sourceBrowser ||
           (verbatimHeaders && (guessSection(name()).isHeader() || !m_includedByMap.empty()))
         ) &&
         !isDocumentationFile();
}
References Config_getBool, guessSection(), isDocumentationFile(), DefinitionMixin< FileDef >::isReference(), m_includedByMap, and name().
Referenced by writeSourceHeader(), and writeSourceLink().
getAllIncludeFilesRecursively()
void FileDefImpl::getAllIncludeFilesRecursively (StringVector & incFiles) const override virtual
Implements FileDef.
Definition at line 1750 of file filedef.cpp.
{
  StringUnorderedSet includes;
  ::getAllIncludeFilesRecursively(includes,this,incFiles);
}
References getAllIncludeFilesRecursively().
Referenced by getAllIncludeFilesRecursively().
getClasses()
const ClassLinkedRefMap & FileDefImpl::getClasses () const inline override virtual
Implements FileDef.
Definition at line 161 of file filedef.cpp.
{ return m_classes; }
References m_classes.
getConcepts()
const ConceptLinkedRefMap & FileDefImpl::getConcepts () const inline override virtual
Implements FileDef.
Definition at line 160 of file filedef.cpp.
{ return m_concepts; }
References m_concepts.
getDirDef()
DirDef * FileDefImpl::getDirDef () const inline override virtual
Implements FileDef.
Definition at line 149 of file filedef.cpp.
{ return m_dir; }
References m_dir.
Referenced by writeDocumentation(), and writeSourceHeader().
getMemberGroups()
const MemberGroupList & FileDefImpl::getMemberGroups () const inline override virtual
Implements FileDef.
Definition at line 158 of file filedef.cpp.
{ return m_memberGroups; }
References m_memberGroups.
getMemberList()
MemberList * FileDefImpl::getMemberList (MemberListType lt) const override virtual
Implements FileDef.
Definition at line 1692 of file filedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()==lt)
    {
      return ml.get();
    }
  }
  return nullptr;
}
References m_memberLists.
Referenced by computeAnchors(), insertMember(), numDecMembers(), numDocMembers(), writeDocumentation(), writeMemberDeclarations(), writeMemberDocumentation(), writeQuickMemberLinks(), writeSummaryLinks(), and writeTagFile().
getMemberLists()
const MemberLists & FileDefImpl::getMemberLists () const inline override virtual
Implements FileDef.
Definition at line 157 of file filedef.cpp.
{ return m_memberLists; }
References m_memberLists.
getModuleDef()
ModuleDef * FileDefImpl::getModuleDef () const inline override virtual
Implements FileDef.
Definition at line 150 of file filedef.cpp.
{ return m_moduleDef; }
References m_moduleDef.
getNamespaces()
const NamespaceLinkedRefMap & FileDefImpl::getNamespaces () const inline override virtual
Implements FileDef.
Definition at line 159 of file filedef.cpp.
{ return m_namespaces; }
References m_namespaces.
getOutputFileBase()
QCString FileDefImpl::getOutputFileBase () const override virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements FileDef.
Definition at line 1623 of file filedef.cpp.
{
  return m_outputDiskName;
}
References m_outputDiskName.
Referenced by addListReferences(), writeDocumentation(), writeSourceHeader(), and writeTagFile().
getPath()
QCString FileDefImpl::getPath () const inline override virtual
Returns the absolute path of this file.
Implements FileDef.
Definition at line 144 of file filedef.cpp.
{ return m_path; }
References m_path.
Referenced by writeTagFile().
getSourceDefinition()
const Definition * FileDefImpl::getSourceDefinition (int lineNr) const override virtual
Implements FileDef.
Definition at line 1392 of file filedef.cpp.
{
  auto it = m_srcDefMap.find(lineNr);
  //printf("%s::getSourceDefinition(%d)=%s\n",qPrint(name()),lineNr,it!=m_srcDefMap.end()?qPrint(it->second->name()):"none");
  return it!=m_srcDefMap.end() ? it->second : nullptr;
}
References m_srcDefMap.
getSourceFileBase()
QCString FileDefImpl::getSourceFileBase () const override virtual
Returns the name of the source listing of this definition.
Reimplemented from DefinitionMixin< FileDef >.
Definition at line 1611 of file filedef.cpp.
{
  if (Htags::useHtags)
  {
    return Htags::path2URL(m_filePath);
  }
  else
  {
    return m_outputDiskName+"_source";
  }
}
References m_filePath, m_outputDiskName, Htags::path2URL(), and Htags::useHtags.
Referenced by includeName(), writeDetailedDescription(), and writeSourceHeader().
getSourceMember()
const MemberDef * FileDefImpl::getSourceMember (int lineNr) const override virtual
Implements FileDef.
Definition at line 1399 of file filedef.cpp.
{
  auto it = m_srcMemberMap.find(lineNr);
  //printf("%s::getSourceMember(%d)=%s\n",qPrint(name()),lineNr,it!=m_srcMemberMap.end()?qPrint(it->second->name()):"none");
  return it!=m_srcMemberMap.end() ? it->second : nullptr;
}
References m_srcMemberMap.
getUsedClasses()
const LinkedRefMap< ClassDef > & FileDefImpl::getUsedClasses () const inline override virtual
Implements FileDef.
Definition at line 152 of file filedef.cpp.
{ return m_usingDeclList; }
References m_usingDeclList.
getUsedNamespaces()
const LinkedRefMap< NamespaceDef > & FileDefImpl::getUsedNamespaces () const override virtual
Implements FileDef.
Definition at line 1413 of file filedef.cpp.
{
  //printf("%p: FileDefImpl::getUsedNamespace: %s:%d\n",this,qPrint(name()),usingDirList?usingDirList->count():0);
  return m_usingDirList;
}
References m_usingDirList.
getVersion()
QCString FileDefImpl::getVersion () const inline override virtual
Returns version of this file.
Implements FileDef.
Definition at line 145 of file filedef.cpp.
{ return m_fileVersion; }
References m_fileVersion.
hasDetailedDescription()
bool FileDefImpl::hasDetailedDescription () const override virtual
Implements FileDef.
Definition at line 357 of file filedef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
  return ((!briefDescription().isEmpty() && repeatBrief) ||
          !documentation().stripWhiteSpace().isEmpty() || // avail empty section
          (sourceBrowser && getStartBodyLine()!=-1 && getBodyDef())
         );
}
References DefinitionMixin< FileDef >::briefDescription(), Config_getBool, DefinitionMixin< FileDef >::documentation(), DefinitionMixin< FileDef >::getBodyDef(), DefinitionMixin< FileDef >::getStartBodyLine(), and stripWhiteSpace().
Referenced by writeDetailedDescription().
hasIncludedByGraph()
bool FileDefImpl::hasIncludedByGraph () const override virtual
Implements FileDef.
Definition at line 1817 of file filedef.cpp.
{
  return m_hasIncludedByGraph;
}
References m_hasIncludedByGraph.
hasIncludeGraph()
bool FileDefImpl::hasIncludeGraph () const override virtual
Implements FileDef.
Definition at line 1812 of file filedef.cpp.
{
  return m_hasIncludeGraph;
}
References m_hasIncludeGraph.
includedByDependencyGraphFileName()
QCString FileDefImpl::includedByDependencyGraphFileName () const override virtual
Implements FileDef.
Definition at line 1771 of file filedef.cpp.
{
  return m_inclByDepFileName;
}
References m_inclByDepFileName.
includedByFileList()
const IncludeInfoList & FileDefImpl::includedByFileList () const inline override virtual
Implements FileDef.
Definition at line 154 of file filedef.cpp.
{ return m_includedByList; }
References m_includedByList.
includeDependencyGraphFileName()
QCString FileDefImpl::includeDependencyGraphFileName () const override virtual
Implements FileDef.
Definition at line 1766 of file filedef.cpp.
{
  return m_inclDepFileName;
}
References m_inclDepFileName.
includeFileList()
const IncludeInfoList & FileDefImpl::includeFileList () const inline override virtual
Implements FileDef.
Definition at line 153 of file filedef.cpp.
{ return m_includeList; }
References m_includeList.
includeName()
QCString FileDefImpl::includeName () const override virtual
Returns the name of the verbatim copy of this file (if any).
Implements FileDef.
Definition at line 1629 of file filedef.cpp.
{
  return getSourceFileBase();
}
References getSourceFileBase().
Referenced by writeSourceLink().
insertClass()
void FileDefImpl::insertClass (ClassDef * cd) override virtual
Adds compound definition cd to the list of all compounds of this file
Implements FileDef.
Definition at line 1334 of file filedef.cpp.
{
  if (cd->isHidden()) return;
  ClassLinkedRefMap *list = &m_classes;
  if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
  {
    if (cd->compoundType()==ClassDef::Interface)
    {
      list = &m_interfaces;
    }
    else if (cd->compoundType()==ClassDef::Struct)
    {
      list = &m_structs;
    }
    else if (cd->compoundType()==ClassDef::Exception)
    {
      list = &m_exceptions;
    }
  }
  list->add(cd->name(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), ClassDef::compoundType(), Config_getBool, ClassDef::Exception, ClassDef::Interface, Definition::isHidden(), m_classes, m_exceptions, m_interfaces, m_structs, Definition::name(), and ClassDef::Struct.
insertConcept()
void FileDefImpl::insertConcept (ConceptDef * cd) override virtual
Implements FileDef.
Definition at line 1359 of file filedef.cpp.
{
  if (cd->isHidden()) return;
  m_concepts.add(cd->name(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::isHidden(), m_concepts, and Definition::name().
insertMember()
void FileDefImpl::insertMember (MemberDef * md) override virtual
Adds member definition md to the list of all members of this file
Implements FileDef.
Definition at line 1266 of file filedef.cpp.
{
  if (md->isHidden()) return;
  //printf("%s:FileDefImpl::insertMember(%s (=%p) list has %d elements)\n",
  //    qPrint(name()),qPrint(md->name()),md,allMemberList.count());
  MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
  if (allMemberList && allMemberList->contains(md))
  {
    return;
  }
  if (allMemberList==nullptr)
  {
    m_memberLists.emplace_back(std::make_unique<MemberList>(MemberListType_allMembersList,MemberListContainer::File));
    allMemberList = m_memberLists.back().get();
  }
  allMemberList->push_back(md);
  switch (md->memberType())
  {
    case MemberType_Property:
      if (md->getLanguage() == SrcLangExt::Python)
      {
        addMemberToList(MemberListType_propertyMembers,md);
        addMemberToList(MemberListType_properties,md);
        break;
      }
      //  fallthrough, explicitly no break here
    case MemberType_Variable:
      addMemberToList(MemberListType_decVarMembers,md);
      addMemberToList(MemberListType_docVarMembers,md);
      break;
    case MemberType_Function:
      addMemberToList(MemberListType_decFuncMembers,md);
      addMemberToList(MemberListType_docFuncMembers,md);
      break;
    case MemberType_Typedef:
      addMemberToList(MemberListType_decTypedefMembers,md);
      addMemberToList(MemberListType_docTypedefMembers,md);
      break;
    case MemberType_Sequence:
      addMemberToList(MemberListType_decSequenceMembers,md);
      addMemberToList(MemberListType_docSequenceMembers,md);
      break;
    case MemberType_Dictionary:
      addMemberToList(MemberListType_decDictionaryMembers,md);
      addMemberToList(MemberListType_docDictionaryMembers,md);
      break;
    case MemberType_Enumeration:
      addMemberToList(MemberListType_decEnumMembers,md);
      addMemberToList(MemberListType_docEnumMembers,md);
      break;
    case MemberType_EnumValue:    // enum values are shown inside their enums
      break;
    case MemberType_Define:
      addMemberToList(MemberListType_decDefineMembers,md);
      addMemberToList(MemberListType_docDefineMembers,md);
      break;
    default:
       err("FileDefImpl::insertMembers(): "
           "member '%s' with class scope '%s' inserted in file scope '%s'!\n",
           qPrint(md->name()),
           md->getClassDef() ? qPrint(md->getClassDef()->name()) : "<global>",
           qPrint(name()));
  }
  //addMemberToGroup(md,groupId);
}
References addMemberToList(), MemberVector::contains(), err, File, MemberLists::get(), MemberDef::getClassDef(), Definition::getLanguage(), getMemberList(), Definition::isHidden(), m_memberLists, MemberListType_allMembersList, MemberListType_decDefineMembers, MemberListType_decDictionaryMembers, MemberListType_decEnumMembers, MemberListType_decFuncMembers, MemberListType_decSequenceMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docDictionaryMembers, MemberListType_docEnumMembers, MemberListType_docFuncMembers, MemberListType_docSequenceMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberListType_properties, MemberListType_propertyMembers, MemberDef::memberType(), MemberType_Define, MemberType_Dictionary, MemberType_Enumeration, MemberType_EnumValue, MemberType_Function, MemberType_Property, MemberType_Sequence, MemberType_Typedef, MemberType_Variable, Definition::name(), name(), MemberVector::push_back(), Python, and qPrint().
insertNamespace()
void FileDefImpl::insertNamespace (NamespaceDef * nd) override virtual
Adds namespace definition nd to the list of all compounds of this file
Implements FileDef.
Definition at line 1366 of file filedef.cpp.
{
  if (nd->isHidden()) return;
  m_namespaces.add(nd->name(),nd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::isHidden(), m_namespaces, and Definition::name().
isDocumentationFile()
bool FileDefImpl::isDocumentationFile () const override virtual
Implements FileDef.
Definition at line 1567 of file filedef.cpp.
{
  static const std::unordered_set<std::string> docExtensions =
  { "doc", "txt", "dox", "md", "markdown" };
  int lastDot = name().findRev('.');
  return (lastDot!=-1 && docExtensions.find(name().mid(lastDot+1).str())!=docExtensions.end()) ||
         getLanguageFromFileName(getFileNameExtension(name())) == SrcLangExt::Markdown;
}
References QCString::findRev(), getFileNameExtension(), getLanguageFromFileName(), Markdown, and name().
Referenced by generateSourceFile(), and writeSourceHeader().
isIncluded()
bool FileDefImpl::isIncluded (const QCString & name) const override virtual
Implements FileDef.
Definition at line 1494 of file filedef.cpp.
{
  if (name.isEmpty()) return FALSE;
  return m_includeMap.find(name.str())!=m_includeMap.end();
}
References FALSE, QCString::isEmpty(), m_includeMap, name(), and QCString::str().
isLinkable()
bool FileDefImpl::isLinkable () const inline override virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements FileDef.
Definition at line 147 of file filedef.cpp.
{ return isLinkableInProject() || isReference(); }
References isLinkableInProject(), and DefinitionMixin< FileDef >::isReference().
Referenced by writeSourceHeader().
isLinkableInProject()
bool FileDefImpl::isLinkableInProject () const override virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements FileDef.
Definition at line 1728 of file filedef.cpp.
{
  bool showFiles = Config_getBool(SHOW_FILES);
  return hasDocumentation() && !isReference() && (showFiles || isLinkableViaGroup());
}
References Config_getBool, DefinitionMixin< FileDef >::hasDocumentation(), DefinitionMixin< FileDef >::isLinkableViaGroup(), and DefinitionMixin< FileDef >::isReference().
Referenced by isLinkable().
isSource()
bool FileDefImpl::isSource () const inline override virtual
Returns TRUE if this file is a source file.
Implements FileDef.
Definition at line 140 of file filedef.cpp.
{ return m_isSource; }
References m_isSource.
name()
const QCString & FileDefImpl::name () const override virtual
Returns the unique file name (this may include part of the path).
Reimplemented from DefinitionMixin< FileDef >.
Definition at line 1372 of file filedef.cpp.
{
  if (Config_getBool(FULL_PATH_NAMES))
    return m_fileName;
  else
    return DefinitionMixin::name();
}
References Config_getBool, m_fileName, and DefinitionMixin< Base >::name().
Referenced by addListReferences(), generateSourceFile(), insertMember(), isDocumentationFile(), isIncluded(), setDiskName(), setDiskNameLocal(), title(), writeDetailedDescription(), writeDocumentation(), writeIncludedByGraph(), writeIncludeGraph(), writeMemberDocumentation(), writeMemberPages(), writeSourceHeader(), and writeTagFile().
numDecMembers()
int FileDefImpl::numDecMembers () const override virtual
Implements FileDef.
Definition at line 1796 of file filedef.cpp.
{
  MemberList *ml = getMemberList(MemberListType_allMembersList);
  return ml ? ml->numDecMembers() : 0;
}
References getMemberList(), MemberListType_allMembersList, and MemberList::numDecMembers().
numDocMembers()
int FileDefImpl::numDocMembers () const override virtual
Implements FileDef.
Definition at line 1790 of file filedef.cpp.
{
  MemberList *ml = getMemberList(MemberListType_allMembersList);
  return ml ? ml->numDocMembers() : 0;
}
References getMemberList(), MemberListType_allMembersList, and MemberList::numDocMembers().
overrideIncludedByGraph()
void FileDefImpl::overrideIncludedByGraph (bool e) override virtual
Implements FileDef.
Definition at line 1807 of file filedef.cpp.
{
  m_hasIncludedByGraph=e;
}
References m_hasIncludedByGraph.
overrideIncludeGraph()
void FileDefImpl::overrideIncludeGraph (bool e) override virtual
Implements FileDef.
Definition at line 1802 of file filedef.cpp.
{
  m_hasIncludeGraph=e;
}
References m_hasIncludeGraph.
parseSource()
void FileDefImpl::parseSource (ClangTUParser * clangParser) override virtual
Implements FileDef.
Definition at line 1218 of file filedef.cpp.
{
  bool filterSourceFiles = Config_getBool(FILTER_SOURCE_FILES);
  OutputCodeList devNullList;
  devNullList.add<DevNullCodeGenerator>();
#if USE_LIBCLANG
  if (Doxygen::clangAssistedParsing && clangParser &&
      (getLanguage()==SrcLangExt::Cpp || getLanguage()==SrcLangExt::ObjC))
  {
    clangParser->switchToFile(this);
    clangParser->writeSources(devNullList,this);
  }
  else
#endif
  {
    auto intf = Doxygen::parserManager->getCodeParser(getDefFileExtension());
    intf->resetCodeParserState();
    intf->parseCode(
            devNullList,QCString(),
            fileToString(absFilePath(),filterSourceFiles,TRUE),
            getLanguage(),
            FALSE,QCString(),this
           );
  }
}
References absFilePath(), OutputCodeList::add(), Doxygen::clangAssistedParsing, Config_getBool, Cpp, FALSE, fileToString(), ParserManager::getCodeParser(), DefinitionMixin< FileDef >::getDefFileExtension(), DefinitionMixin< FileDef >::getLanguage(), ObjC, Doxygen::parserManager, and TRUE.
setDirDef()
void FileDefImpl::setDirDef (DirDef * dd) inline override virtual
Implements FileDef.
Definition at line 185 of file filedef.cpp.
{ m_dir=dd; }
References m_dir.
setDiskName()
void FileDefImpl::setDiskName (const QCString & name) override virtual
Implements FileDef.
Definition at line 318 of file filedef.cpp.
{
  setDiskNameLocal(name);
}
References name(), and setDiskNameLocal().
setDiskNameLocal()
void FileDefImpl::setDiskNameLocal (const QCString & name) private
Definition at line 302 of file filedef.cpp.
{
  if (isReference())
  {
    m_outputDiskName = name;
    m_inclDepFileName = name+"_incl";
    m_inclByDepFileName = name+"_dep_incl";
  }
  else
  {
    m_outputDiskName = convertNameToFile(name);
    m_inclDepFileName = convertNameToFile(name+"_incl");
    m_inclByDepFileName = convertNameToFile(name+"_dep_incl");
  }
}
References convertNameToFile(), DefinitionMixin< FileDef >::isReference(), m_inclByDepFileName, m_inclDepFileName, m_outputDiskName, and name().
Referenced by FileDefImpl(), and setDiskName().
setModuleDef()
void FileDefImpl::setModuleDef (ModuleDef * mod) inline override virtual
Implements FileDef.
Definition at line 186 of file filedef.cpp.
{ m_moduleDef=mod; }
References m_moduleDef.
sortMemberLists()
void FileDefImpl::sortMemberLists () override virtual
Implements FileDef.
Definition at line 1653 of file filedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->needsSorting()) { ml->sort(); ml->setNeedsSorting(FALSE); }
  }
  for (const auto &mg : m_memberGroups)
  {
    MemberList &mlg = const_cast<MemberList&>(mg->members());
    if (mlg.needsSorting()) { mlg.sort(); mlg.setNeedsSorting(FALSE); }
  }
  std::sort(m_includedByList.begin(),m_includedByList.end(),
      [](const auto &fi1,const auto &fi2) { return fi1.includeName < fi2.includeName; });
  if (Config_getBool(SORT_BRIEF_DOCS))
  {
    auto classComp = [](const ClassLinkedRefMap::Ptr &c1,const ClassLinkedRefMap::Ptr &c2)
    {
      return Config_getBool(SORT_BY_SCOPE_NAME)     ?
        qstricmp(c1->name(),      c2->name())<0     :
        qstricmp(c1->className(), c2->className())<0;
    };
    std::sort(m_classes.begin(),   m_classes.end(),   classComp);
    std::sort(m_interfaces.begin(),m_interfaces.end(),classComp);
    std::sort(m_structs.begin(),   m_structs.end(),   classComp);
    std::sort(m_exceptions.begin(),m_exceptions.end(),classComp);
    auto namespaceComp = [](const NamespaceLinkedRefMap::Ptr &n1,const NamespaceLinkedRefMap::Ptr &n2)
    {
      return qstricmp(n1->name(),n2->name())<0;
    };
    std::sort(m_namespaces.begin(),m_namespaces.end(),namespaceComp);
  }
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::begin(), ClassDef::className(), Config_getBool, LinkedRefMap< T, Hash, KeyEqual, Map >::end(), FALSE, m_classes, m_exceptions, m_includedByList, m_interfaces, m_memberGroups, m_memberLists, m_namespaces, m_structs, Definition::name(), MemberList::needsSorting(), qstricmp(), MemberList::setNeedsSorting(), and MemberVector::sort().
startMemberDeclarations()
void FileDefImpl::startMemberDeclarations (OutputList & ol) private
Definition at line 724 of file filedef.cpp.
{
  ol.startMemberSections();
}
References OutputList::startMemberSections().
Referenced by writeDocumentation().
startMemberDocumentation()
void FileDefImpl::startMemberDocumentation (OutputList & ol) private
Definition at line 734 of file filedef.cpp.
{
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.disable(OutputType::Html);
    Doxygen::suppressDocWarnings = TRUE;
  }
}
References Config_getBool, OutputList::disable(), Html, Doxygen::suppressDocWarnings, and TRUE.
Referenced by writeDocumentation().
subGrouping()
bool FileDefImpl::subGrouping () const inline override virtual
Implements FileDef.
Definition at line 165 of file filedef.cpp.
{ return m_subGrouping; }
References m_subGrouping.
title()
QCString FileDefImpl::title () const override virtual
Implements FileDef.
Definition at line 1756 of file filedef.cpp.
{
  return theTranslator->trFileReference(name());
}
References name(), theTranslator, and Translator::trFileReference().
Referenced by writeClassDeclarations(), writeConcepts(), writeDetailedDescription(), writeDocumentation(), writeMemberDeclarations(), writeMemberDocumentation(), writeNamespaceDeclarations(), and writeSourceHeader().
writeAuthorSection()
void FileDefImpl::writeAuthorSection (OutputList & ol) private
Definition at line 764 of file filedef.cpp.
{
  // write Author section (Man only)
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Man);
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), and TRUE.
Referenced by writeDocumentation().
writeBriefDescription()
void FileDefImpl::writeBriefDescription (OutputList & ol) private
Definition at line 527 of file filedef.cpp.
{
  if (hasBriefDescription())
  {
    auto parser { createDocParser() };
    auto ast    { validatingParseDoc(*parser.get(),
                                     briefFile(),briefLine(),this,nullptr,
                                     briefDescription(),TRUE,FALSE,
                                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startParagraph();
      ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Man);
      ol.writeString(" - ");
      ol.popGeneratorState();
      ol.writeDoc(ast.get(),this,nullptr);
      ol.pushGeneratorState();
      ol.disable(OutputType::RTF);
      ol.writeString(" \n");
      ol.enable(OutputType::RTF);
      if (Config_getBool(REPEAT_BRIEF) ||
          !documentation().stripWhiteSpace().isEmpty()
         )
      {
        ol.disableAllBut(OutputType::Html);
        ol.startTextLink(QCString(),"details");
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
      }
      ol.popGeneratorState();
      ol.endParagraph();
    }
  }
  ol.writeSynopsis();
}
References DefinitionMixin< FileDef >::briefDescription(), DefinitionMixin< FileDef >::briefFile(), DefinitionMixin< FileDef >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< FileDef >::documentation(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), FALSE, DefinitionMixin< FileDef >::hasBriefDescription(), Html, Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), RTF, OutputList::startParagraph(), OutputList::startTextLink(), stripWhiteSpace(), theTranslator, Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeClassDeclarations()
void FileDefImpl::writeClassDeclarations (OutputList & ol, const QCString & title, const ClassLinkedRefMap & list) private
Definition at line 699 of file filedef.cpp.
{
  // write list of classes
  list.writeDeclaration(ol,nullptr,title,FALSE);
}
References FALSE, title(), and ClassLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeClassesToTagFile()
void FileDefImpl::writeClassesToTagFile (TextStream & t, const ClassLinkedRefMap & list) private
Definition at line 565 of file filedef.cpp.
{
  for (const auto &cd : list)
  {
    if (cd->isLinkableInProject())
    {
      tagFile << "    <class kind=\"" << cd->compoundTypeString() <<
        "\">" << convertToXML(cd->name()) << "</class>\n";
    }
  }
}
References convertToXML().
Referenced by writeTagFile().
writeConcepts()
void FileDefImpl::writeConcepts (OutputList & ol, const QCString & title) private
Definition at line 705 of file filedef.cpp.
{
  // write list of classes
  m_concepts.writeDeclaration(ol,title,FALSE);
}
References FALSE, m_concepts, title(), and ConceptLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeDetailedDescription()
void FileDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) private
Definition at line 465 of file filedef.cpp.
{
  if (hasDetailedDescription())
  {
    ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Html);
      ol.writeAnchor(QCString(),"details");
    ol.popGeneratorState();
    ol.startGroupHeader();
    ol.parseText(title);
    ol.endGroupHeader();
    ol.startTextBlock();
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF))
    {
      ol.generateDoc(briefFile(),briefLine(),this,nullptr,briefDescription(),FALSE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF) &&
        !documentation().isEmpty())
    {
      ol.pushGeneratorState();
        ol.disable(OutputType::Man);
        ol.disable(OutputType::RTF);
        ol.enableAll();
        ol.disableAllBut(OutputType::Man);
        ol.enable(OutputType::Latex);
        ol.writeString("\n\n");
      ol.popGeneratorState();
    }
    if (!documentation().isEmpty())
    {
      ol.generateDoc(docFile(),docLine(),this,nullptr,documentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    //printf("Writing source ref for file %s\n",qPrint(name()));
    if (Config_getBool(SOURCE_BROWSER))
    {
      ol.startParagraph("definition");
      QCString refText = theTranslator->trDefinedInSourceFile();
      int fileMarkerPos = refText.find("@0");
      if (fileMarkerPos!=-1) // should always pass this.
      {
        ol.parseText(refText.left(fileMarkerPos)); //text left from marker 1
        ol.writeObjectLink(QCString(),getSourceFileBase(),QCString(),name());
        ol.parseText(refText.right(
              refText.length()-fileMarkerPos-2)); // text right from marker 2
      }
      else
      {
        err("translation error: invalid marker in trDefinedInSourceFile()\n");
      }
      ol.endParagraph();
    }
    ol.endTextBlock();
  }
}
References DefinitionMixin< FileDef >::briefDescription(), DefinitionMixin< FileDef >::briefFile(), DefinitionMixin< FileDef >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< FileDef >::docFile(), DefinitionMixin< FileDef >::docLine(), DefinitionMixin< FileDef >::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), OutputList::endParagraph(), OutputList::endTextBlock(), err, FALSE, QCString::find(), OutputList::generateDoc(), getSourceFileBase(), hasDetailedDescription(), Html, Latex, QCString::left(), QCString::length(), Man, name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), QCString::right(), RTF, OutputList::startGroupHeader(), OutputList::startParagraph(), OutputList::startTextBlock(), theTranslator, title(), Translator::trDefinedInSourceFile(), TRUE, OutputList::writeAnchor(), OutputList::writeObjectLink(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDocumentation()
void FileDefImpl::writeDocumentation (OutputList & ol) override virtual
Write the documentation page for this file to the file of output generators ol.
Implements FileDef.
Definition at line 845 of file filedef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  //funcList->countDecMembers();
  //QCString fn = name();
  //if (Config_getBool(FULL_PATH_NAMES))
  //{
  //  fn.prepend(stripFromPath(getPath()));
  //}
  //printf("WriteDocumentation diskname=%s\n",qPrint(diskname));
  QCString versionTitle;
  if (!m_fileVersion.isEmpty())
  {
    versionTitle=("("+m_fileVersion+")");
  }
  QCString title = m_docname+versionTitle;
  QCString pageTitle=theTranslator->trFileReference(m_docname);
  if (getDirDef())
  {
    startFile(ol,getOutputFileBase(),name(),pageTitle,HighlightedItem::FileVisible,!generateTreeView);
    if (!generateTreeView)
    {
      getDirDef()->writeNavigationPath(ol);
      ol.endQuickIndices();
    }
    startTitle(ol,getOutputFileBase(),this);
    ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Html);
      ol.parseText(theTranslator->trFileReference(displayName())); // Html only
      ol.enableAll();
      ol.disable(OutputType::Html);
      ol.parseText(Config_getBool(FULL_PATH_NAMES) ?  // other output formats
                   pageTitle :
                   theTranslator->trFileReference(name()));
    ol.popGeneratorState();
    addGroupListToTitle(ol,this);
    endTitle(ol,getOutputFileBase(),title);
  }
  else
  {
    startFile(ol,getOutputFileBase(),name(),pageTitle,HighlightedItem::FileVisible,!generateTreeView);
    if (!generateTreeView)
    {
      ol.endQuickIndices();
    }
    startTitle(ol,getOutputFileBase(),this);
    ol.parseText(pageTitle);
    addGroupListToTitle(ol,this);
    endTitle(ol,getOutputFileBase(),title);
  }
  ol.startContents();
  if (!m_fileVersion.isEmpty())
  {
    ol.disableAllBut(OutputType::Html);
    ol.startProjectNumber();
    ol.docify(versionTitle);
    ol.endProjectNumber();
    ol.enableAll();
  }
  //---------------------------------------- start flexible part -------------------------------
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::File))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
        startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::FileIncludes:
        writeIncludeFiles(ol);
        break;
      case LayoutDocEntry::FileIncludeGraph:
        writeIncludeGraph(ol);
        break;
      case LayoutDocEntry::FileIncludedByGraph:
        writeIncludedByGraph(ol);
        break;
      case LayoutDocEntry::FileSourceLink:
        writeSourceLink(ol);
        break;
      case LayoutDocEntry::FileClasses:
        if (ls) writeClassDeclarations(ol,ls->title(lang),m_classes);
        break;
      case LayoutDocEntry::FileInterfaces:
        if (ls) writeClassDeclarations(ol,ls->title(lang),m_interfaces);
        break;
      case LayoutDocEntry::FileStructs:
        if (ls) writeClassDeclarations(ol,ls->title(lang),m_structs);
        break;
      case LayoutDocEntry::FileExceptions:
        if (ls) writeClassDeclarations(ol,ls->title(lang),m_exceptions);
        break;
      case LayoutDocEntry::FileConcepts:
        if (ls) writeConcepts(ol,ls->title(lang));
        break;
      case LayoutDocEntry::FileNamespaces:
        if (ls) writeNamespaceDeclarations(ol,ls->title(lang),false);
        break;
      case LayoutDocEntry::FileConstantGroups:
        if (ls) writeNamespaceDeclarations(ol,ls->title(lang),true);
        break;
      case LayoutDocEntry::MemberGroups:
        writeMemberGroups(ol);
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd) writeMemberDeclarations(ol,lmd->type,lmd->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDeclEnd:
        endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::DetailedDesc:
        if (ls) writeDetailedDescription(ol,ls->title(lang));
        break;
      case LayoutDocEntry::MemberDefStart:
        startMemberDocumentation(ol);
        break;
      case LayoutDocEntry::FileInlineClasses:
        writeInlineClasses(ol);
        break;
      case LayoutDocEntry::MemberDef:
        {
          const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
          if (lmd) writeMemberDocumentation(ol,lmd->type,lmd->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDefEnd:
        endMemberDocumentation(ol);
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::ClassIncludes:
      case LayoutDocEntry::ClassInheritanceGraph:
      case LayoutDocEntry::ClassNestedClasses:
      case LayoutDocEntry::ClassCollaborationGraph:
      case LayoutDocEntry::ClassAllMembersLink:
      case LayoutDocEntry::ClassUsedFiles:
      case LayoutDocEntry::ClassInlineClasses:
      case LayoutDocEntry::NamespaceNestedNamespaces:
      case LayoutDocEntry::NamespaceNestedConstantGroups:
      case LayoutDocEntry::NamespaceClasses:
      case LayoutDocEntry::NamespaceConcepts:
      case LayoutDocEntry::NamespaceInterfaces:
      case LayoutDocEntry::NamespaceStructs:
      case LayoutDocEntry::NamespaceExceptions:
      case LayoutDocEntry::NamespaceInlineClasses:
      case LayoutDocEntry::ConceptDefinition:
      case LayoutDocEntry::GroupClasses:
      case LayoutDocEntry::GroupConcepts:
      case LayoutDocEntry::GroupModules:
      case LayoutDocEntry::GroupInlineClasses:
      case LayoutDocEntry::GroupNamespaces:
      case LayoutDocEntry::GroupDirs:
      case LayoutDocEntry::GroupNestedGroups:
      case LayoutDocEntry::GroupFiles:
      case LayoutDocEntry::GroupGraph:
      case LayoutDocEntry::GroupPageDocs:
      case LayoutDocEntry::ModuleExports:
      case LayoutDocEntry::ModuleClasses:
      case LayoutDocEntry::ModuleConcepts:
      case LayoutDocEntry::ModuleUsedFiles:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::File entry list\n",lde->kind());
        break;
    }
  }
  //---------------------------------------- end flexible part -------------------------------
  ol.endContents();
  endFileWithNavPath(ol,this);
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    MemberList *ml = getMemberList(MemberListType_allMembersList);
    if (ml) ml->sort();
    writeMemberPages(ol);
  }
}
References addGroupListToTitle(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, LayoutDocEntry::ConceptDefinition, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, OutputList::disable(), OutputList::disableAllBut(), displayName(), LayoutDocManager::docEntries(), OutputList::docify(), OutputList::enableAll(), OutputList::endContents(), endFileWithNavPath(), endMemberDeclarations(), endMemberDocumentation(), OutputList::endProjectNumber(), OutputList::endQuickIndices(), endTitle(), err, LayoutDocManager::File, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::FileStructs, FileVisible, getDirDef(), DefinitionMixin< FileDef >::getLanguage(), getMemberList(), getOutputFileBase(), LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupModules, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, Html, LayoutDocManager::instance(), QCString::isEmpty(), m_classes, m_docname, m_exceptions, m_fileVersion, m_interfaces, m_structs, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, MemberListType_allMembersList, LayoutDocEntry::ModuleClasses, LayoutDocEntry::ModuleConcepts, LayoutDocEntry::ModuleExports, LayoutDocEntry::ModuleUsedFiles, name(), LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, LayoutDocEntry::NamespaceStructs, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), MemberVector::sort(), OutputList::startContents(), startFile(), startMemberDeclarations(), startMemberDocumentation(), OutputList::startProjectNumber(), startTitle(), theTranslator, title(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), Translator::trFileReference(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeClassDeclarations(), writeConcepts(), writeDetailedDescription(), writeIncludedByGraph(), writeIncludeFiles(), writeIncludeGraph(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeMemberPages(), writeNamespaceDeclarations(), DefinitionMutable::writeNavigationPath(), and writeSourceLink().
writeIncludedByGraph()
void FileDefImpl::writeIncludedByGraph (OutputList & ol) private
Definition at line 651 of file filedef.cpp.
{
  if (Config_getBool(HAVE_DOT) && m_hasIncludedByGraph /*&& Config_getBool(INCLUDED_BY_GRAPH)*/)
  {
    //printf("Graph for file %s\n",qPrint(name()));
    DotInclDepGraph incDepGraph(this,TRUE);
    if (incDepGraph.isTooBig())
    {
       warn_uncond("Included by graph for '%s' not generated, too many nodes (%d), threshold is %d. Consider increasing DOT_GRAPH_MAX_NODES.\n",
           qPrint(name()), incDepGraph.numNodes(), Config_getInt(DOT_GRAPH_MAX_NODES));
    }
    else if (!incDepGraph.isTrivial())
    {
      ol.startTextBlock();
      ol.disable(OutputType::Man);
      ol.startInclDepGraph();
      ol.parseText(theTranslator->trInclByDepGraph());
      ol.endInclDepGraph(incDepGraph);
      ol.enableAll();
      ol.endTextBlock(TRUE);
    }
    //incDepGraph.writeGraph(Config_getString(HTML_OUTPUT),fd->getOutputFileBase());
  }
}
References Config_getBool, Config_getInt, OutputList::disable(), OutputList::enableAll(), OutputList::endInclDepGraph(), OutputList::endTextBlock(), DotInclDepGraph::isTooBig(), DotInclDepGraph::isTrivial(), m_hasIncludedByGraph, Man, name(), DotInclDepGraph::numNodes(), OutputList::parseText(), qPrint(), OutputList::startInclDepGraph(), OutputList::startTextBlock(), theTranslator, Translator::trInclByDepGraph(), TRUE, and warn_uncond.
Referenced by writeDocumentation().
writeIncludeFiles()
void FileDefImpl::writeIncludeFiles (OutputList & ol) private
Definition at line 577 of file filedef.cpp.
{
  if (!m_includeList.empty())
  {
    ol.startTextBlock(TRUE);
    for (const auto &ii : m_includeList)
    {
      const FileDef *fd=ii.fileDef;
      ol.startTypewriter();
      SrcLangExt lang = fd ? fd->getLanguage() : SrcLangExt::Cpp;
      ol.docify(::includeStatement(lang,ii.kind));
      ol.docify(::includeOpen(lang,ii.kind));
      ol.disable(OutputType::Html);
      ol.docify(ii.includeName);
      ol.enableAll();
      ol.disableAllBut(OutputType::Html);
      // Here we use the include file name as it appears in the file.
      // we could also we the name as it is used within doxygen,
      // then we should have used fd->docName() instead of ii->includeName
      if (fd && fd->isLinkable())
      {
        ol.writeObjectLink(fd->getReference(),
            fd->generateSourceFile() ? fd->includeName() : fd->getOutputFileBase(),
            QCString(),ii.includeName);
      }
      else
      {
        ModuleDef *mod = ModuleManager::instance().getPrimaryInterface(ii.includeName);
        if (ii.kind==IncludeKind::ImportModule && mod && mod->isLinkable())
        {
          ol.writeObjectLink(mod->getReference(),mod->getOutputFileBase(),
                             QCString(),ii.includeName);
        }
        else
        {
          ol.docify(ii.includeName);
        }
      }
      ol.enableAll();
      ol.docify(::includeClose(lang,ii.kind));
      ol.endTypewriter();
      ol.lineBreak();
    }
    ol.endTextBlock();
  }
}
References Cpp, OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enableAll(), OutputList::endTextBlock(), OutputList::endTypewriter(), FileDef::generateSourceFile(), Definition::getLanguage(), Definition::getOutputFileBase(), FileDef::getOutputFileBase(), ModuleManager::getPrimaryInterface(), Definition::getReference(), Html, ImportModule, includeClose(), FileDef::includeName(), includeOpen(), includeStatement(), ModuleManager::instance(), Definition::isLinkable(), FileDef::isLinkable(), OutputList::lineBreak(), m_includeList, OutputList::startTextBlock(), OutputList::startTypewriter(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeIncludeGraph()
void FileDefImpl::writeIncludeGraph (OutputList & ol) private
Definition at line 626 of file filedef.cpp.
{
  if (Config_getBool(HAVE_DOT) && m_hasIncludeGraph /*&& Config_getBool(INCLUDE_GRAPH)*/)
  {
    //printf("Graph for file %s\n",qPrint(name()));
    DotInclDepGraph incDepGraph(this,FALSE);
    if (incDepGraph.isTooBig())
    {
       warn_uncond("Include graph for '%s' not generated, too many nodes (%d), threshold is %d. Consider increasing DOT_GRAPH_MAX_NODES.\n",
           qPrint(name()), incDepGraph.numNodes(), Config_getInt(DOT_GRAPH_MAX_NODES));
    }
    else if (!incDepGraph.isTrivial())
    {
      ol.startTextBlock();
      ol.disable(OutputType::Man);
      ol.startInclDepGraph();
      ol.parseText(theTranslator->trInclDepGraph(name()));
      ol.endInclDepGraph(incDepGraph);
      ol.enableAll();
      ol.endTextBlock(TRUE);
    }
    //incDepGraph.writeGraph(Config_getString(HTML_OUTPUT),fd->getOutputFileBase());
  }
}
References Config_getBool, Config_getInt, OutputList::disable(), OutputList::enableAll(), OutputList::endInclDepGraph(), OutputList::endTextBlock(), FALSE, DotInclDepGraph::isTooBig(), DotInclDepGraph::isTrivial(), m_hasIncludeGraph, Man, name(), DotInclDepGraph::numNodes(), OutputList::parseText(), qPrint(), OutputList::startInclDepGraph(), OutputList::startTextBlock(), theTranslator, Translator::trInclDepGraph(), TRUE, and warn_uncond.
Referenced by writeDocumentation().
writeInlineClasses()
void FileDefImpl::writeInlineClasses (OutputList & ol) private
Definition at line 711 of file filedef.cpp.
{
  // temporarily undo the disabling could be done by startMemberDocumentation()
  // as a result of setting SEPARATE_MEMBER_PAGES to YES; see bug730512
  bool isEnabled = ol.isEnabled(OutputType::Html);
  ol.enable(OutputType::Html);
  m_classes.writeDocumentation(ol,this);
  // restore the initial state if needed
  if (!isEnabled) ol.disable(OutputType::Html);
}
References OutputList::disable(), OutputList::enable(), Html, OutputList::isEnabled(), m_classes, and ClassLinkedRefMap::writeDocumentation().
Referenced by writeDocumentation().
writeMemberDeclarations()
void FileDefImpl::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1704 of file filedef.cpp.
{
  bool optVhdl = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  MemberList * ml = getMemberList(lt);
  if (ml)
  {
    if (optVhdl) // use specific declarations function
    {
      VhdlDocGen::writeVhdlDeclarations(ml,ol,nullptr,nullptr,this,nullptr,nullptr);
    }
    else
    {
      ml->writeDeclarations(ol,nullptr,nullptr,this,nullptr,nullptr,title,QCString());
    }
  }
}
References Config_getBool, getMemberList(), title(), MemberList::writeDeclarations(), and VhdlDocGen::writeVhdlDeclarations().
Referenced by writeDocumentation().
writeMemberDocumentation()
void FileDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1722 of file filedef.cpp.
{
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDocumentation(ol,name(),this,title);
}
References getMemberList(), name(), title(), and MemberList::writeDocumentation().
Referenced by writeDocumentation().
writeMemberGroups()
void FileDefImpl::writeMemberGroups (OutputList & ol) private
Definition at line 752 of file filedef.cpp.
{
  /* write user defined member groups */
  for (const auto &mg : m_memberGroups)
  {
    if (!mg->allMembersInSameSection() || !m_subGrouping)
    {
      mg->writeDeclarations(ol,nullptr,nullptr,this,nullptr,nullptr);
    }
  }
}
References m_memberGroups, and m_subGrouping.
Referenced by writeDocumentation().
writeMemberPages()
void FileDefImpl::writeMemberPages (OutputList & ol) override virtual
Implements FileDef.
Definition at line 1044 of file filedef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  for (const auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
      ml->writeDocumentationPage(ol,name(),this);
    }
  }
  ol.popGeneratorState();
}
References OutputList::disableAllBut(), Html, m_memberLists, MemberListType_documentationLists, name(), OutputList::popGeneratorState(), and OutputList::pushGeneratorState().
Referenced by writeDocumentation().
writeNamespaceDeclarations()
void FileDefImpl::writeNamespaceDeclarations (OutputList & ol, const QCString & title, bool isConstantGroup) private
Definition at line 692 of file filedef.cpp.
{
  // write list of namespaces
  m_namespaces.writeDeclaration(ol,title,isConstantGroup);
}
References m_namespaces, title(), and NamespaceLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeQuickMemberLinks()
void FileDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const override virtual
Reimplemented from DefinitionMixin< FileDef >.
Definition at line 1060 of file filedef.cpp.
{
  bool createSubDirs=Config_getBool(CREATE_SUBDIRS);
  ol.writeString("      <div class=\"navtab\">\n");
  ol.writeString("        <table>\n");
  MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
  if (allMemberList)
  {
    for (const auto &md : *allMemberList)
    {
      if (md->getFileDef()==this && md->getNamespaceDef()==nullptr && md->isLinkable() && !md->isEnumValue())
      {
        if (md->isLinkableInProject())
        {
          QCString fn=md->getOutputFileBase();
          addHtmlExtensionIfMissing(fn);
          if (md==currentMd) // selected item => highlight
          {
            ol.writeString("          <tr><td class=\"navtabHL\">");
          }
          else
          {
            ol.writeString("          <tr><td class=\"navtab\">");
          }
          ol.writeString("<a class=\"navtab\" ");
          ol.writeString("href=\"");
          if (createSubDirs) ol.writeString("../../");
          ol.writeString(fn+"#"+md->anchor());
          ol.writeString("\">");
          ol.writeString(convertToHtml(md->localName()));
          ol.writeString("</a>");
          ol.writeString("</td></tr>\n");
        }
      }
    }
  }
  ol.writeString("        </table>\n");
  ol.writeString("      </div>\n");
}
References addHtmlExtensionIfMissing(), Config_getBool, convertToHtml(), createSubDirs(), getMemberList(), MemberListType_allMembersList, and OutputList::writeString().
writeSourceBody()
void FileDefImpl::writeSourceBody (OutputList & ol, ClangTUParser * clangParser) override virtual
Implements FileDef.
Definition at line 1157 of file filedef.cpp.
{
  bool filterSourceFiles = Config_getBool(FILTER_SOURCE_FILES);
  OutputCodeList devNullList;
  devNullList.add<DevNullCodeGenerator>();
#if USE_LIBCLANG
  if (Doxygen::clangAssistedParsing && clangParser &&
      (getLanguage()==SrcLangExt::Cpp || getLanguage()==SrcLangExt::ObjC))
  {
    auto &codeOL = ol.codeGenerators();
    codeOL.startCodeFragment("DoxyCode");
    clangParser->switchToFile(this);
    clangParser->writeSources(codeOL,this);
    codeOL.endCodeFragment("DoxyCode");
  }
  else
#endif
  {
    auto intf = Doxygen::parserManager->getCodeParser(getDefFileExtension());
    intf->resetCodeParserState();
    auto &codeOL = ol.codeGenerators();
    codeOL.startCodeFragment("DoxyCode");
    bool needs2PassParsing =
        Doxygen::parseSourcesNeeded &&                // we need to parse (filtered) sources for cross-references
        !filterSourceFiles &&                         // but user wants to show sources as-is
        !getFileFilter(absFilePath(),TRUE).isEmpty(); // and there is a filter used while parsing
    if (needs2PassParsing)
    {
      // parse code for cross-references only (see bug707641)
      intf->parseCode(devNullList,QCString(),
                       fileToString(absFilePath(),TRUE,TRUE),
                       getLanguage(),
                       FALSE,QCString(),this
                      );
    }
    intf->parseCode(codeOL,QCString(),
        fileToString(absFilePath(),filterSourceFiles,TRUE),
        getLanguage(),      // lang
        FALSE,              // isExampleBlock
        QCString(),         // exampleName
        this,               // fileDef
        -1,                 // startLine
        -1,                 // endLine
        FALSE,              // inlineFragment
        nullptr,                  // memberDef
        TRUE,               // showLineNumbers
        nullptr,                  // searchCtx
        !needs2PassParsing  // collectXRefs
        );
    codeOL.endCodeFragment("DoxyCode");
  }
}
References absFilePath(), OutputCodeList::add(), Doxygen::clangAssistedParsing, OutputList::codeGenerators(), Config_getBool, Cpp, FALSE, fileToString(), ParserManager::getCodeParser(), DefinitionMixin< FileDef >::getDefFileExtension(), getFileFilter(), DefinitionMixin< FileDef >::getLanguage(), QCString::isEmpty(), ObjC, Doxygen::parserManager, Doxygen::parseSourcesNeeded, OutputCodeList::startCodeFragment(), and TRUE.
writeSourceFooter()
void FileDefImpl::writeSourceFooter (OutputList & ol) override virtual
Implements FileDef.
Definition at line 1211 of file filedef.cpp.
{
  ol.endContents();
  endFileWithNavPath(ol,this);
  ol.enableAll();
}
References OutputList::enableAll(), OutputList::endContents(), and endFileWithNavPath().
writeSourceHeader()
void FileDefImpl::writeSourceHeader (OutputList & ol) override virtual
Write a source listing of this file to the output
Implements FileDef.
Definition at line 1104 of file filedef.cpp.
{
  bool generateTreeView  = Config_getBool(GENERATE_TREEVIEW);
  QCString title = m_docname;
  if (!m_fileVersion.isEmpty())
  {
    title+=(" ("+m_fileVersion+")");
  }
  QCString pageTitle = theTranslator->trSourceFile(title);
  ol.disable(OutputType::Man);
  bool isDocFile = isDocumentationFile();
  bool genSourceFile = !isDocFile && generateSourceFile();
  if (getDirDef())
  {
    startFile(ol,getSourceFileBase(),QCString(),pageTitle,HighlightedItem::FileVisible,
        !generateTreeView,
        !isDocFile && genSourceFile ? QCString() : getOutputFileBase(),
        0);
    if (!generateTreeView)
    {
      getDirDef()->writeNavigationPath(ol);
      ol.endQuickIndices();
    }
    startTitle(ol,getSourceFileBase());
    ol.parseText(name());
    endTitle(ol,getSourceFileBase(),title);
  }
  else
  {
    startFile(ol,getSourceFileBase(),QCString(),pageTitle,HighlightedItem::FileVisible,false,
        !isDocFile && genSourceFile ? QCString() : getOutputFileBase(),
        0);
    startTitle(ol,getSourceFileBase());
    ol.parseText(title);
    endTitle(ol,getSourceFileBase(),QCString());
  }
  ol.startContents();
  if (isLinkable())
  {
    ol.startTextLink(getOutputFileBase(),QCString());
    ol.parseText(theTranslator->trGotoDocumentation());
    ol.endTextLink();
    ol.pushGeneratorState();
    ol.disableAllBut(OutputType::RTF);
    ol.writeString("\\par\n");
    ol.popGeneratorState();
  }
}
References Config_getBool, OutputList::disable(), OutputList::disableAllBut(), OutputList::endQuickIndices(), OutputList::endTextLink(), endTitle(), FileVisible, generateSourceFile(), getDirDef(), getOutputFileBase(), getSourceFileBase(), isDocumentationFile(), QCString::isEmpty(), isLinkable(), m_docname, m_fileVersion, Man, name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), RTF, OutputList::startContents(), startFile(), OutputList::startTextLink(), startTitle(), theTranslator, title(), Translator::trGotoDocumentation(), Translator::trSourceFile(), DefinitionMutable::writeNavigationPath(), and OutputList::writeString().
writeSourceLink()
void FileDefImpl::writeSourceLink (OutputList & ol) private
Definition at line 677 of file filedef.cpp.
{
  //printf("%s: generateSourceFile()=%d\n",qPrint(name()),generateSourceFile());
  if (generateSourceFile())
  {
    ol.disableAllBut(OutputType::Html);
    ol.startParagraph();
    ol.startTextLink(includeName(),QCString());
    ol.parseText(theTranslator->trGotoSourceCode());
    ol.endTextLink();
    ol.endParagraph();
    ol.enableAll();
  }
}
References OutputList::disableAllBut(), OutputList::enableAll(), OutputList::endParagraph(), OutputList::endTextLink(), generateSourceFile(), Html, includeName(), OutputList::parseText(), OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, and Translator::trGotoSourceCode().
Referenced by writeDocumentation().
writeSummaryLinks()
void FileDefImpl::writeSummaryLinks (OutputList & ol) const override virtual
Reimplemented from DefinitionMixin< FileDef >.
Definition at line 776 of file filedef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  bool first=TRUE;
  SrcLangExt lang=getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::File))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    if (lde->kind()==LayoutDocEntry::FileClasses && m_classes.declVisible() && ls)
    {
      QCString label = "nested-classes";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::FileInterfaces && m_interfaces.declVisible() && ls)
    {
      QCString label = "interfaces";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::FileStructs && m_structs.declVisible() && ls)
    {
      QCString label = "structs";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::FileExceptions && m_exceptions.declVisible() && ls)
    {
      QCString label = "exceptions";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::FileNamespaces && m_namespaces.declVisible(false) && ls)
    {
      QCString label = "namespaces";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::FileConcepts && m_concepts.declVisible() && ls)
    {
      QCString label = "concepts";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        MemberList * ml = getMemberList(lmd->type);
        if (ml && ml->declVisible())
        {
          ol.writeSummaryLink(QCString(),MemberList::listTypeAsString(ml->listType()),lmd->title(lang),first);
          first=FALSE;
        }
      }
    }
  }
  if (!first)
  {
    ol.writeString("  </div>\n");
  }
  ol.popGeneratorState();
}
References ConceptLinkedRefMap::declVisible(), MemberList::declVisible(), NamespaceLinkedRefMap::declVisible(), ClassLinkedRefMap::declVisible(), OutputList::disableAllBut(), LayoutDocManager::docEntries(), FALSE, LayoutDocManager::File, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileStructs, DefinitionMixin< FileDef >::getLanguage(), getMemberList(), Html, LayoutDocManager::instance(), MemberList::listType(), MemberList::listTypeAsString(), m_classes, m_concepts, m_exceptions, m_interfaces, m_namespaces, m_structs, LayoutDocEntry::MemberDecl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), TRUE, LayoutDocEntryMemberDecl::type, OutputList::writeString(), and OutputList::writeSummaryLink().
writeTagFile()
void FileDefImpl::writeTagFile (TextStream & t) override virtual
Implements FileDef.
Definition at line 367 of file filedef.cpp.
{
  QCString fn=getOutputFileBase();
  addHtmlExtensionIfMissing(fn);
  tagFile << "  <compound kind=\"file\">\n";
  tagFile << "    <name>" << convertToXML(name()) << "</name>\n";
  tagFile << "    <path>" << convertToXML(stripFromPath(getPath())) << "</path>\n";
  tagFile << "    <filename>" << fn << "</filename>\n";
  for (const auto &ii : m_includeList)
  {
    const FileDef *fd=ii.fileDef;
    if (fd && fd->isLinkable() && !fd->isReference())
    {
      QCString attr = includeTagFileAttributes(fd->getLanguage(),ii.kind);
      tagFile << "    <includes id=\""
        << convertToXML(fd->getOutputFileBase()) << "\" "
        << "name=\"" << convertToXML(fd->name()) << "\" "
        << attr << ">"
        << convertToXML(ii.includeName)
        << "</includes>\n";
    }
  }
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::File))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::FileClasses:
        {
          writeClassesToTagFile(tagFile, m_classes);
        }
        break;
      case LayoutDocEntry::FileInterfaces:
        {
          writeClassesToTagFile(tagFile, m_interfaces);
        }
        break;
      case LayoutDocEntry::FileStructs:
        {
          writeClassesToTagFile(tagFile, m_structs);
        }
        break;
      case LayoutDocEntry::FileExceptions:
        {
          writeClassesToTagFile(tagFile, m_exceptions);
        }
        break;
      case LayoutDocEntry::FileConcepts:
        {
          for (const auto *nd : m_concepts)
          {
            if (nd->isLinkableInProject())
            {
              tagFile << "    <concept>" << convertToXML(nd->name()) << "</concept>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::FileNamespaces:
        {
          for (const auto *nd : m_namespaces)
          {
            if (nd->isLinkableInProject())
            {
              tagFile << "    <namespace>" << convertToXML(nd->name()) << "</namespace>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            MemberList * ml = getMemberList(lmd->type);
            if (ml)
            {
              ml->writeTagFile(tagFile,false,false);
            }
          }
        }
        break;
      case LayoutDocEntry::MemberGroups:
        {
          for (const auto &mg : m_memberGroups)
          {
            mg->writeTagFile(tagFile);
          }
        }
        break;
      default:
        break;
    }
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << "  </compound>\n";
}
References addHtmlExtensionIfMissing(), convertToXML(), LayoutDocManager::docEntries(), LayoutDocManager::File, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileStructs, Definition::getLanguage(), getMemberList(), FileDef::getOutputFileBase(), getOutputFileBase(), getPath(), includeTagFileAttributes(), LayoutDocManager::instance(), FileDef::isLinkable(), Definition::isReference(), m_classes, m_concepts, m_exceptions, m_includeList, m_interfaces, m_memberGroups, m_namespaces, m_structs, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberGroups, FileDef::name(), name(), stripFromPath(), LayoutDocEntryMemberDecl::type, writeClassesToTagFile(), DefinitionMixin< FileDef >::writeDocAnchorsToTagFile(), and MemberList::writeTagFile().
Member Data Documentation
m_classes
ClassLinkedRefMap FileDefImpl::m_classes private
Definition at line 252 of file filedef.cpp.
Referenced by getClasses(), insertClass(), sortMemberLists(), writeDocumentation(), writeInlineClasses(), writeSummaryLinks(), and writeTagFile().
m_concepts
ConceptLinkedRefMap FileDefImpl::m_concepts private
Definition at line 256 of file filedef.cpp.
Referenced by getConcepts(), insertConcept(), writeConcepts(), writeSummaryLinks(), and writeTagFile().
m_dir
DirDef* FileDefImpl::m_dir = nullptr private
Definition at line 247 of file filedef.cpp.
Referenced by FileDefImpl(), getDirDef(), and setDirDef().
m_docname
QCString FileDefImpl::m_docname private
Definition at line 242 of file filedef.cpp.
Referenced by docName(), FileDefImpl(), writeDocumentation(), and writeSourceHeader().
m_exceptions
ClassLinkedRefMap FileDefImpl::m_exceptions private
Definition at line 255 of file filedef.cpp.
Referenced by insertClass(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
m_fileName
QCString FileDefImpl::m_fileName private
Definition at line 241 of file filedef.cpp.
Referenced by FileDefImpl(), fileName(), and name().
m_filePath
QCString FileDefImpl::m_filePath private
Definition at line 237 of file filedef.cpp.
Referenced by absFilePath(), acquireFileVersion(), FileDefImpl(), and getSourceFileBase().
m_fileVersion
QCString FileDefImpl::m_fileVersion private
Definition at line 246 of file filedef.cpp.
Referenced by acquireFileVersion(), fileVersion(), getVersion(), writeDocumentation(), and writeSourceHeader().
m_hasIncludedByGraph
bool FileDefImpl::m_hasIncludedByGraph = Config_getBool(INCLUDED_BY_GRAPH) private
Definition at line 259 of file filedef.cpp.
Referenced by hasIncludedByGraph(), overrideIncludedByGraph(), and writeIncludedByGraph().
m_hasIncludeGraph
bool FileDefImpl::m_hasIncludeGraph = Config_getBool(INCLUDE_GRAPH) private
Definition at line 258 of file filedef.cpp.
Referenced by hasIncludeGraph(), overrideIncludeGraph(), and writeIncludeGraph().
m_inclByDepFileName
QCString FileDefImpl::m_inclByDepFileName private
Definition at line 239 of file filedef.cpp.
Referenced by includedByDependencyGraphFileName(), and setDiskNameLocal().
m_inclDepFileName
QCString FileDefImpl::m_inclDepFileName private
Definition at line 238 of file filedef.cpp.
Referenced by includeDependencyGraphFileName(), and setDiskNameLocal().
m_includedByList
IncludeInfoList FileDefImpl::m_includedByList private
Definition at line 233 of file filedef.cpp.
Referenced by addIncludedByDependency(), includedByFileList(), and sortMemberLists().
m_includedByMap
IncludeInfoMap FileDefImpl::m_includedByMap private
Definition at line 232 of file filedef.cpp.
Referenced by addIncludedByDependency(), and generateSourceFile().
m_includeList
IncludeInfoList FileDefImpl::m_includeList private
Definition at line 231 of file filedef.cpp.
Referenced by addIncludeDependency(), addIncludedUsingDirectives(), includeFileList(), writeIncludeFiles(), and writeTagFile().
m_includeMap
IncludeInfoMap FileDefImpl::m_includeMap private
Definition at line 230 of file filedef.cpp.
Referenced by addIncludeDependency(), and isIncluded().
m_interfaces
ClassLinkedRefMap FileDefImpl::m_interfaces private
Definition at line 253 of file filedef.cpp.
Referenced by insertClass(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
m_isSource
bool FileDefImpl::m_isSource private
Definition at line 245 of file filedef.cpp.
Referenced by FileDefImpl(), and isSource().
m_memberGroups
MemberGroupList FileDefImpl::m_memberGroups private
Definition at line 250 of file filedef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), countMembers(), distributeMemberGroupDocumentation(), findSectionsInDocumentation(), getMemberGroups(), sortMemberLists(), writeMemberGroups(), and writeTagFile().
m_memberLists
MemberLists FileDefImpl::m_memberLists private
Definition at line 249 of file filedef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), addMemberToList(), countMembers(), findSectionsInDocumentation(), getMemberList(), getMemberLists(), insertMember(), sortMemberLists(), and writeMemberPages().
m_moduleDef
ModuleDef* FileDefImpl::m_moduleDef = nullptr private
Definition at line 248 of file filedef.cpp.
Referenced by getModuleDef(), and setModuleDef().
m_namespaces
NamespaceLinkedRefMap FileDefImpl::m_namespaces private
Definition at line 251 of file filedef.cpp.
Referenced by getNamespaces(), insertNamespace(), sortMemberLists(), writeNamespaceDeclarations(), writeSummaryLinks(), and writeTagFile().
m_outputDiskName
QCString FileDefImpl::m_outputDiskName private
Definition at line 240 of file filedef.cpp.
Referenced by getOutputFileBase(), getSourceFileBase(), and setDiskNameLocal().
m_path
QCString FileDefImpl::m_path private
Definition at line 236 of file filedef.cpp.
Referenced by FileDefImpl(), and getPath().
m_srcDefMap
DefinitionLineMap FileDefImpl::m_srcDefMap private
Definition at line 243 of file filedef.cpp.
Referenced by addSourceRef(), and getSourceDefinition().
m_srcMemberMap
MemberDefLineMap FileDefImpl::m_srcMemberMap private
Definition at line 244 of file filedef.cpp.
Referenced by addSourceRef(), and getSourceMember().
m_structs
ClassLinkedRefMap FileDefImpl::m_structs private
Definition at line 254 of file filedef.cpp.
Referenced by insertClass(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
m_subGrouping
bool FileDefImpl::m_subGrouping private
Definition at line 257 of file filedef.cpp.
Referenced by addMembersToMemberGroup(), FileDefImpl(), subGrouping(), and writeMemberGroups().
m_usingDeclList
LinkedRefMap<ClassDef> FileDefImpl::m_usingDeclList private
Definition at line 235 of file filedef.cpp.
Referenced by addIncludedUsingDirectives(), addUsingDeclaration(), and getUsedClasses().
m_usingDirList
LinkedRefMap<NamespaceDef> FileDefImpl::m_usingDirList private
Definition at line 234 of file filedef.cpp.
Referenced by addIncludedUsingDirectives(), addUsingDirective(), combineUsingRelations(), and getUsedNamespaces().
The documentation for this class was generated from the following file:
src/filedef.cpp