Doxygen: TranslatorRussian Class Reference
TranslatorRussian Class Reference
#include <src/translator_ru.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool, bool full) override
QCString trMonth (int month, bool, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description.
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool single) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
QCString trDesignUnitDocumentation () override
VHDL design unit documentation.
QCString trConcept (bool first_capital, bool singular) override
C++20 concept.
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
QCString trPackageList () override
QCString trFlowchart () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
QCString trCopyToClipboard () override
QCString trImportant () override
Public Member Functions inherited from Translator
virtual QCString updateNeededMessage ()
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Detailed Description
Definition at line 29 of file translator_ru.h.
Member Function Documentation
getLanguageString()
QCString TranslatorRussian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 42 of file translator_ru.h.
    {
      return "0x419 Russian";
    }
idLanguage()
QCString TranslatorRussian::idLanguage () inline override virtual
Used for identification of the language.
Implements Translator.
Definition at line 33 of file translator_ru.h.
    { return "russian"; }
latexLanguageSupportCommand()
QCString TranslatorRussian::latexLanguageSupportCommand () inline override virtual
Implements Translator.
Definition at line 37 of file translator_ru.h.
    { return "\\usepackage[T2A]{fontenc}\n\\usepackage[russian]{babel}\n"; }
trAdditionalInheritedMembers()
QCString TranslatorRussian::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1840 of file translator_ru.h.
    { return "  "; }
trAll()
QCString TranslatorRussian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1344 of file translator_ru.h.
    {
      return "";
    }
trAndMore()
QCString TranslatorRussian::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1818 of file translator_ru.h.
    { return " "+number+" ..."; }
trAttention()
QCString TranslatorRussian::trAttention () inline override virtual
Implements Translator.
Definition at line 948 of file translator_ru.h.
    {
      return "";
    }
trAuthor()
QCString TranslatorRussian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1217 of file translator_ru.h.
    {
      return createNoun(first_capital, singular, "", "");
    }
References Translator::createNoun().
trBug()
QCString TranslatorRussian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1111 of file translator_ru.h.
    {
      return "";
    }
trBugList()
QCString TranslatorRussian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1116 of file translator_ru.h.
    {
      return "";
    }
trCallerGraph()
QCString TranslatorRussian::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1463 of file translator_ru.h.
    {
      return "  :";
    }
trCallGraph()
QCString TranslatorRussian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1349 of file translator_ru.h.
    {
      return " :";
    }
trCiteReferences()
QCString TranslatorRussian::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1794 of file translator_ru.h.
    { return " "; }
trClass()
QCString TranslatorRussian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1144 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        QCString result((first_capital ? " " : " "));
        return result;
      }
      else
      {
      return createNoun(first_capital, singular, "", "");
      }
    }
References Config_getBool, and Translator::createNoun().
Referenced by trCompoundType().
trClassDiagram()
QCString TranslatorRussian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 468 of file translator_ru.h.
    {
      return QCString(" :")+clName+":";
    }
trClassDocumentation()
QCString TranslatorRussian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 344 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorRussian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1074 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorRussian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 149 of file translator_ru.h.
    { return " "; }
trClassHierarchyDescription()
QCString TranslatorRussian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 204 of file translator_ru.h.
    { return " ."; }
trClassMethods()
QCString TranslatorRussian::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1878 of file translator_ru.h.
    {
      return " ";
    }
trCode()
QCString TranslatorRussian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 845 of file translator_ru.h.
    {
      return " ";
    }
trCollaborationDiagram()
QCString TranslatorRussian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 800 of file translator_ru.h.
    {
      return "   "+clName+":";
    }
trCompoundIndex()
QCString TranslatorRussian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 317 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "   ";
      }
      else
      {
        return "  ";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorRussian::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1520 of file translator_ru.h.
    { return " "; }
trCompoundList()
QCString TranslatorRussian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 153 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorRussian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 217 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "     .";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "    .";
      }
      else
      {
        return "    .";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorRussian::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1494 of file translator_ru.h.
    { return "   :"; }
trCompoundListFortran()
QCString TranslatorRussian::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1486 of file translator_ru.h.
    { return " "; }
trCompoundMembers()
QCString TranslatorRussian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 170 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorRussian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 234 of file translator_ru.h.
    {
        QCString result="  ";
        if(!extractAll) result+=" ";
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result+="      ";
        else
          result+="     ";
        if(!extractAll)
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result+="     .";
          else
            result+="     .";
        }
        else
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result += "";
          else
            result += "";
          result+=",    .";
        }
        return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorRussian::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1498 of file translator_ru.h.
    {
      QCString result="  ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+="    ";
      if (!extractAll)
      {
        result+="    :";
      }
      else
      {
         result+="  :";
      }
      return result;
    }
trCompoundMembersDescriptionTotal()
QCString TranslatorRussian::trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2400 of file translator_ru.h.
{
    bool extractAll = Config_getBool(EXTRACT_ALL);
    QCString result = "   ";
    if (!extractAll) {
      result += " ";
    }
    switch (hl) {
    case ClassMemberHighlight::All:
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result += "   ";
      } else {
        result += " ";
      }
      break;
    case ClassMemberHighlight::Functions:
      result += "";
      break;
    case ClassMemberHighlight::Variables:
      result += "";
      break;
    case ClassMemberHighlight::Typedefs:
      result += " ";
      break;
    case ClassMemberHighlight::Enums:
      result += "";
      break;
    case ClassMemberHighlight::EnumValues:
      result += " ";
      break;
    case ClassMemberHighlight::Properties:
      result += "";
      break;
    case ClassMemberHighlight::Events:
      result += "";
      break;
    case ClassMemberHighlight::Related:
      result += " ";
      break;
    case ClassMemberHighlight::Total: // for completeness
      break;
    }
    result += "    ";
    if (!extractAll) {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result += "   /:";
      } else {
        result += "   :";
      }
    } else {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result += "/,    :";
      } else {
        result += ",    :";
      }
    }
    return result;
  }
References ClassMemberHighlight::All, Config_getBool, ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, ClassMemberHighlight::Properties, ClassMemberHighlight::Related, ClassMemberHighlight::Total, ClassMemberHighlight::Typedefs, and ClassMemberHighlight::Variables.
trCompoundMembersFortran()
QCString TranslatorRussian::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1490 of file translator_ru.h.
    { return " "; }
trCompoundReference()
QCString TranslatorRussian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 544 of file translator_ru.h.
    {
      QCString result;
      if (isTemplate)
      {
        result=" ";
        switch(compType)
        {
          case ClassDef::Class:  result+=""; break;
          case ClassDef::Struct: result+=""; break;
          case ClassDef::Union:  result+=""; break;
          case ClassDef::Interface:  result+=""; break;
          case ClassDef::Protocol:   result+=""; break;
          case ClassDef::Category:   result+=""; break;
          case ClassDef::Exception:  result+=""; break;
          default: break;
        }
      }
      else
      {
        switch(compType)
        {
          case ClassDef::Class:  result+=""; break;
          case ClassDef::Struct: result+=""; break;
          case ClassDef::Union:  result+=""; break;
          case ClassDef::Interface:  result+=""; break;
          case ClassDef::Protocol:   result+=""; break;
          case ClassDef::Category:   result+=""; break;
          case ClassDef::Exception:  result+=""; break;
          default: break;
        }
      }
      result+=" ";
      return result+clName;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorRussian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1561 of file translator_ru.h.
    {
      QCString result=clName;
      if (isTemplate)
      {
        switch(compType)
        {
          case ClassDef::Class:      result+=" "; break;
          case ClassDef::Struct:     result+=" "; break;
          case ClassDef::Union:      result+=" "; break;
          case ClassDef::Interface:  result+=" "; break;
          case ClassDef::Protocol:   result+=" "; break;
          case ClassDef::Category:   result+=" "; break;
          case ClassDef::Exception:  result+=" "; break;
          default: break;
        }
      }
      else
      {
        result+="  ";
        switch(compType)
        {
          case ClassDef::Class:      result+=""; break;
          case ClassDef::Struct:     result+=""; break;
          case ClassDef::Union:      result+=""; break;
          case ClassDef::Interface:  result+=""; break;
          case ClassDef::Protocol:   result+=""; break;
          case ClassDef::Category:   result+=""; break;
          case ClassDef::Exception:  result+=""; break;
          default: break;
        }
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice()
QCString TranslatorRussian::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) inline override virtual
Implements Translator.
Definition at line 2167 of file translator_ru.h.
{
    QCString result = " ";
    switch (compType) {
    case ClassDef::Class:
      if (isLocal)
        result += " ";
      result += "  ";
      break;
    case ClassDef::Struct:
      if (isLocal)
        result += " ";
      result += "  ";
      break;
    case ClassDef::Union:
      if (isLocal)
        result += " ";
      result += "  ";
      break;
    case ClassDef::Interface:
      if (isLocal)
        result += " ";
      result += "  ";
      break;
    case ClassDef::Protocol:
      if (isLocal)
        result += " ";
      result += "  ";
      break;
    case ClassDef::Category:
      if (isLocal)
        result += " ";
      result += "  ";
      break;
    case ClassDef::Exception:
      if (isLocal)
        result += " ";
      result += "  ";
      break;
    default:
      break;
    }
    return result + clName;
  }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorRussian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 439 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundType()
QCString TranslatorRussian::trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) inline override virtual
the compound type as used for the xrefitems
Implements Translator.
Definition at line 2309 of file translator_ru.h.
{
    QCString result;
    switch (compType) {
    case ClassDef::Class:
      if (lang == SrcLangExt::Fortran)
        trType(true, true);
      else
        result = trClass(true, true);
      break;
    case ClassDef::Struct:
      result = "";
      break;
    case ClassDef::Union:
      result = "";
      break;
    case ClassDef::Interface:
      result = "";
      break;
    case ClassDef::Protocol:
      result = "";
      break;
    case ClassDef::Category:
      result = "";
      break;
    case ClassDef::Exception:
      result = "";
      break;
    case ClassDef::Service:
      result = "";
      break;
    case ClassDef::Singleton:
      result = "";
      break;
    default:
      break;
    }
    return result;
  }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, Fortran, ClassDef::Interface, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, ClassDef::Struct, trClass(), trType(), and ClassDef::Union.
trConcept()
QCString TranslatorRussian::trConcept (bool first_capital, bool singular) inline override virtual
C++20 concept.
Implements Translator.
Definition at line 2233 of file translator_ru.h.
{
    return createNoun(first_capital, singular, "", "");
  }
References Translator::createNoun().
trConceptDefinition()
QCString TranslatorRussian::trConceptDefinition () inline override virtual
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2262 of file translator_ru.h.
{ return " "; }
trConceptDocumentation()
QCString TranslatorRussian::trConceptDocumentation () inline override virtual
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2248 of file translator_ru.h.
{
    return " ";
  }
trConceptIndex()
QCString TranslatorRussian::trConceptIndex () inline override virtual
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2245 of file translator_ru.h.
{ return " "; }
trConceptList()
QCString TranslatorRussian::trConceptList () inline override virtual
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2242 of file translator_ru.h.
{ return " "; }
trConceptListDescription()
QCString TranslatorRussian::trConceptListDescription (bool extractAll) inline override virtual
used as an introduction to the concept list
Implements Translator.
Definition at line 2253 of file translator_ru.h.
{
    QCString result = "   ";
    if (!extractAll)
      result += " ";
    result += "    :";
    return result;
  }
trConceptReference()
QCString TranslatorRussian::trConceptReference (const QCString & conceptName) inline override virtual
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2237 of file translator_ru.h.
{
    return "   " + conceptName;
  }
trConstantDocumentation()
QCString TranslatorRussian::trConstantDocumentation () inline override virtual
Implements Translator.
Definition at line 2122 of file translator_ru.h.
{
    return " ";
  }
trConstantGroupReference()
QCString TranslatorRussian::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1915 of file translator_ru.h.
    {
      QCString result=namespaceName;
      result+="    ";
      return result;
    }
trConstantGroups()
QCString TranslatorRussian::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1911 of file translator_ru.h.
    { return " "; }
trConstants()
QCString TranslatorRussian::trConstants () inline override virtual
Implements Translator.
Definition at line 2121 of file translator_ru.h.
{ return ""; }
trConstructorDocumentation()
QCString TranslatorRussian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 810 of file translator_ru.h.
    {
      return "()";
    }
trCopyright()
QCString TranslatorRussian::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1798 of file translator_ru.h.
    { return ""; }
trCopyToClipboard()
QCString TranslatorRussian::trCopyToClipboard () inline override virtual
Implements Translator.
Definition at line 2573 of file translator_ru.h.
{ return "   "; }
trCustomReference()
QCString TranslatorRussian::trCustomReference (const QCString & name) inline override virtual
Implements Translator.
Definition at line 2116 of file translator_ru.h.
{
    return " " + name;
  }
trDataMemberDocumentation()
QCString TranslatorRussian::trDataMemberDocumentation () inline override virtual
Implements Translator.
Definition at line 2217 of file translator_ru.h.
{
    return "   ";
  }
trDataMembers()
QCString TranslatorRussian::trDataMembers () inline override virtual
Implements Translator.
Definition at line 2216 of file translator_ru.h.
{ return " "; }
trDataTypes()
QCString TranslatorRussian::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1544 of file translator_ru.h.
    { return " "; }
trDate()
QCString TranslatorRussian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 482 of file translator_ru.h.
    { return ""; }
trDateTime()
QCString TranslatorRussian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1749 of file translator_ru.h.
    {
      static const char *days[]   = { "","","","","","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorRussian::trDayOfWeek (int dayOfWeek, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1769 of file translator_ru.h.
    {
      static const char *days_short[]   = { "", "", "", "", "", "", "" };
      static const char *days_full[]    = { "", "", "", "", "", "", "" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod()
QCString TranslatorRussian::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1783 of file translator_ru.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period?1:0];
    }
trDeclaration()
QCString TranslatorRussian::trDeclaration () inline override virtual
Implements Translator.
Definition at line 2511 of file translator_ru.h.
{ return ""; }
trDefinedAtLineInSourceFile()
QCString TranslatorRussian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 777 of file translator_ru.h.
    {
      return ".    @1  @0";
    }
trDefinedIn()
QCString TranslatorRussian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 137 of file translator_ru.h.
    { return " "; }
trDefinedInSourceFile()
QCString TranslatorRussian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 781 of file translator_ru.h.
    {
      return ".    @0";
    }
trDefineDocumentation()
QCString TranslatorRussian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 409 of file translator_ru.h.
    { return ""; }
trDefines()
QCString TranslatorRussian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 373 of file translator_ru.h.
    { return ""; }
trDefineValue()
QCString TranslatorRussian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1101 of file translator_ru.h.
    {
      return ":";
    }
trDefinition()
QCString TranslatorRussian::trDefinition () inline override virtual
Implements Translator.
Definition at line 2510 of file translator_ru.h.
{ return ""; }
trDeprecated()
QCString TranslatorRussian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 790 of file translator_ru.h.
    {
      return ".";
    }
trDeprecatedList()
QCString TranslatorRussian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1272 of file translator_ru.h.
    {
      return "    ";
    }
trDesignUnitDocumentation()
QCString TranslatorRussian::trDesignUnitDocumentation () inline override virtual
VHDL design unit documentation.
Implements Translator.
Definition at line 2226 of file translator_ru.h.
{ return " "; }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorRussian::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Implements Translator.
Definition at line 1966 of file translator_ru.h.
{
    return "  ";
  }
trDesignUnitIndex()
QCString TranslatorRussian::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Implements Translator.
Definition at line 1981 of file translator_ru.h.
{ return "  "; }
trDesignUnitList()
QCString TranslatorRussian::trDesignUnitList () inline override virtual
VHDL design unit list.
Implements Translator.
Definition at line 1970 of file translator_ru.h.
{ return "  "; }
trDesignUnitListDescription()
QCString TranslatorRussian::trDesignUnitListDescription () inline override virtual
VHDL design unit list description.
Implements Translator.
Definition at line 1976 of file translator_ru.h.
{
    return "        "
           " ,   :";
  }
trDesignUnitMembers()
QCString TranslatorRussian::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Implements Translator.
Definition at line 1972 of file translator_ru.h.
{
    return "  ";
  }
trDesignUnits()
QCString TranslatorRussian::trDesignUnits () inline override virtual
VHDL design units.
Implements Translator.
Definition at line 1983 of file translator_ru.h.
{ return " "; }
trDetailedDescription()
QCString TranslatorRussian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 58 of file translator_ru.h.
    { return " "; }
trDetailLevel()
QCString TranslatorRussian::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1810 of file translator_ru.h.
    { return " "; }
trDetails()
QCString TranslatorRussian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 62 of file translator_ru.h.
    { return ""; }
trDictionaries()
QCString TranslatorRussian::trDictionaries () inline override virtual
Implements Translator.
Definition at line 2129 of file translator_ru.h.
{ return ""; }
trDictionaryDocumentation()
QCString TranslatorRussian::trDictionaryDocumentation () inline override virtual
Implements Translator.
Definition at line 2130 of file translator_ru.h.
{
    return " ";
  }
trDir()
QCString TranslatorRussian::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1439 of file translator_ru.h.
    {
      return createNoun(first_capital, singular, "", "", "");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorRussian::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1802 of file translator_ru.h.
    { return QCString("   ")+name+":"; }
trDirDocumentation()
QCString TranslatorRussian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1421 of file translator_ru.h.
    { return ""; }
trDirectories()
QCString TranslatorRussian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1427 of file translator_ru.h.
    { return "  "; }
trDirIndex()
QCString TranslatorRussian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1415 of file translator_ru.h.
    { return " "; }
trDirReference()
QCString TranslatorRussian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1433 of file translator_ru.h.
    { QCString result=QCString("  ")+ dirName; return result; }
trDirRelation()
QCString TranslatorRussian::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1688 of file translator_ru.h.
    {
      return QCString(name)+" ";
    }
trDocumentation()
QCString TranslatorRussian::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 299 of file translator_ru.h.
    { return (!projName.isEmpty()?projName + " " : "") + ""; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorRussian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 385 of file translator_ru.h.
    { return ""; }
trEnumerationTypeDocumentation()
QCString TranslatorRussian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 421 of file translator_ru.h.
    { return ""; }
trEnumerationValueDocumentation()
QCString TranslatorRussian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1471 of file translator_ru.h.
    { return " "; }
trEnumerationValues()
QCString TranslatorRussian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 403 of file translator_ru.h.
    { return " "; }
trEnumGeneratedFromFiles()
QCString TranslatorRussian::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1822 of file translator_ru.h.
    { QCString result = "      ";
      if (!single) result += "";
      result+=":";
      return result;
    }
trEnumName()
QCString TranslatorRussian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 129 of file translator_ru.h.
    { return ""; }
trEnumReference()
QCString TranslatorRussian::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1830 of file translator_ru.h.
    { return QCString(name)+"   "; }
trEnumValue()
QCString TranslatorRussian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 133 of file translator_ru.h.
    { return " "; }
trEventDocumentation()
QCString TranslatorRussian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1289 of file translator_ru.h.
    {
      return "C";
    }
trEvents()
QCString TranslatorRussian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1284 of file translator_ru.h.
    {
      return "";
    }
trExamples()
QCString TranslatorRussian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 196 of file translator_ru.h.
    { return ""; }
trExamplesDescription()
QCString TranslatorRussian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 284 of file translator_ru.h.
    { return "  ."; }
trExceptionDocumentation()
QCString TranslatorRussian::trExceptionDocumentation () inline override virtual
Implements Translator.
Definition at line 2164 of file translator_ru.h.
{
    return " ";
  }
trExceptionHierarchy()
QCString TranslatorRussian::trExceptionHierarchy () inline override virtual
Implements Translator.
Definition at line 2159 of file translator_ru.h.
{ return " "; }
trExceptionHierarchyDescription()
QCString TranslatorRussian::trExceptionHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2160 of file translator_ru.h.
{
    return "   ,   ,  "
           "  :";
  }
trExceptionIndex()
QCString TranslatorRussian::trExceptionIndex () inline override virtual
Implements Translator.
Definition at line 2154 of file translator_ru.h.
{ return " "; }
trExceptionList()
QCString TranslatorRussian::trExceptionList () inline override virtual
Implements Translator.
Definition at line 2155 of file translator_ru.h.
{ return " "; }
trExceptionListDescription()
QCString TranslatorRussian::trExceptionListDescription () inline override virtual
Implements Translator.
Definition at line 2156 of file translator_ru.h.
{
    return "       :";
  }
trExceptions()
QCString TranslatorRussian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 498 of file translator_ru.h.
    { return ""; }
trExportedModules()
QCString TranslatorRussian::trExportedModules () inline override virtual
Implements Translator.
Definition at line 2567 of file translator_ru.h.
{ return " "; }
trExtendsClass()
QCString TranslatorRussian::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1870 of file translator_ru.h.
    {
      return "  @0.";
    }
trFile()
QCString TranslatorRussian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1161 of file translator_ru.h.
    {
      return createNoun(first_capital, singular, "", "");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorRussian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 363 of file translator_ru.h.
    { return ""; }
trFileIn()
QCString TranslatorRussian::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1725 of file translator_ru.h.
    {
      return "  "+name;
    }
trFileIndex()
QCString TranslatorRussian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 332 of file translator_ru.h.
    { return " "; }
trFileList()
QCString TranslatorRussian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 166 of file translator_ru.h.
    { return ""; }
trFileListDescription()
QCString TranslatorRussian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 208 of file translator_ru.h.
    {
      QCString result="  ";
      if (!extractAll) result+=" ";
      result+=".";
      return result;
    }
trFileMembers()
QCString TranslatorRussian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 184 of file translator_ru.h.
    {
      return "   ";
    }
trFileMembersDescription()
QCString TranslatorRussian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 261 of file translator_ru.h.
    {
      QCString result="  ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , , "
                "   ";
      }
      else
      {
        result+="  ";
      }
      result+="    ";
      if (extractAll)
        result+=",    .";
      else
        result+=".";
      return result;
    }
References Config_getBool.
trFileMembersDescriptionTotal()
QCString TranslatorRussian::trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2350 of file translator_ru.h.
{
    bool extractAll = Config_getBool(EXTRACT_ALL);
    QCString result = "   ";
    if (!extractAll)
      result += " ";
    switch (hl) {
    case FileMemberHighlight::All:
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result += ", , ,   "
                  " ";
      } else {
        result += " ";
      }
      break;
    case FileMemberHighlight::Functions:
      result += "";
      break;
    case FileMemberHighlight::Variables:
      result += "";
      break;
    case FileMemberHighlight::Typedefs:
      result += " ";
      break;
    case FileMemberHighlight::Sequences:
      result += "";
      break;
    case FileMemberHighlight::Dictionaries:
      result += "";
      break;
    case FileMemberHighlight::Enums:
      result += "";
      break;
    case FileMemberHighlight::EnumValues:
      result += " ";
      break;
    case FileMemberHighlight::Defines:
      result += "";
      break;
    case FileMemberHighlight::Total: // for completeness
      break;
    }
    result += "   ";
    if (extractAll)
      result += ",    :";
    else
      result += ":";
    return result;
  }
References FileMemberHighlight::All, Config_getBool, FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, FileMemberHighlight::Sequences, FileMemberHighlight::Total, FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
trFileReference()
QCString TranslatorRussian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 583 of file translator_ru.h.
    {
      return QCString(" ")+fileName;
    }
trFlowchart()
QCString TranslatorRussian::trFlowchart () inline override virtual
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2277 of file translator_ru.h.
{ return "-:"; }
trFriends()
QCString TranslatorRussian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 525 of file translator_ru.h.
    { return ""; }
trFunctionAndProc()
QCString TranslatorRussian::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Implements Translator.
Definition at line 1985 of file translator_ru.h.
{ return "//"; }
trFunctionDocumentation()
QCString TranslatorRussian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 427 of file translator_ru.h.
    { return ""; }
trFunctions()
QCString TranslatorRussian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 391 of file translator_ru.h.
    { return ""; }
trGeneratedAt()
QCString TranslatorRussian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the documentation of a group before the list of links to documented files
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 458 of file translator_ru.h.
    {
      QCString result=" ";
      if (!projName.isEmpty()) result+=QCString(" ")+projName;
      result+=QCString(".  : ")+date;
      result+=".  ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorRussian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 121 of file translator_ru.h.
    { QCString result="  Doxygen";
      if (!s.isEmpty()) result+=QCString("  ")+s;
      result+="   .";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorRussian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 502 of file translator_ru.h.
    { return " "; }
trGeneratedFromFiles()
QCString TranslatorRussian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 718 of file translator_ru.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=QCString("    ");
      switch(compType)
      {
        case ClassDef::Class:      result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Struct:     result+="";
          if (single) result+="";
          break;
        case ClassDef::Union:      result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Interface:  result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Protocol:  result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Category:  result+="";
          if (single) result+=""; else result+="";
          break;
        case ClassDef::Exception:  result+="";
          if (single) result+=""; else result+="";
          break;
        default:
          break;
      }
      result+="   ";
      if (single) result+=":"; else result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorRussian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1641 of file translator_ru.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="  ";
      switch(compType)
      {
        case ClassDef::Class:      result+=""; break;
        case ClassDef::Struct:     result+=""; break;
        case ClassDef::Union:      result+=""; break;
        case ClassDef::Interface:  result+=""; break;
        case ClassDef::Protocol:   result+=""; break;
        case ClassDef::Category:   result+=""; break;
        case ClassDef::Exception:  result+=""; break;
        default: break;
      }
      result+="    ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorRussian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1206 of file translator_ru.h.
    {
      return createNoun(first_capital, singular, "", "", "");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorRussian::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1700 of file translator_ru.h.
    {
      return "  ";
    }
trGotoDocumentation()
QCString TranslatorRussian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 820 of file translator_ru.h.
    {
      return ". .";
    }
trGotoGraphicalHierarchy()
QCString TranslatorRussian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 853 of file translator_ru.h.
    {
      return ".  .";
    }
trGotoSourceCode()
QCString TranslatorRussian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 815 of file translator_ru.h.
    {
      return ".  .";
    }
trGotoTextualHierarchy()
QCString TranslatorRussian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 857 of file translator_ru.h.
    {
      return ".  .";
    }
trGraphicalHierarchy()
QCString TranslatorRussian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 849 of file translator_ru.h.
    {
      return " .  .";
    }
trGroup()
QCString TranslatorRussian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1179 of file translator_ru.h.
    {
      return createNoun(first_capital, singular, "", "", "");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorRussian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 311 of file translator_ru.h.
    { return "  "; }
trImplementedFromList()
QCString TranslatorRussian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1240 of file translator_ru.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorRussian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1248 of file translator_ru.h.
    {
      return "  "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImportant()
QCString TranslatorRussian::trImportant () inline override virtual
Implements Translator.
Definition at line 2577 of file translator_ru.h.
{ return "!"; }
trInclByDepGraph()
QCString TranslatorRussian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 952 of file translator_ru.h.
    {
      return " ,     :";
    }
trInclDepGraph()
QCString TranslatorRussian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 805 of file translator_ru.h.
    {
      return "     "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorRussian::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1734 of file translator_ru.h.
    {
      return "   "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorRussian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 115 of file translator_ru.h.
    { return ",     "; }
trInheritedByList()
QCString TranslatorRussian::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 650 of file translator_ru.h.
    {
      return " :"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorRussian::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1834 of file translator_ru.h.
    { return QCString(members)+"   "+what; }
trInheritsList()
QCString TranslatorRussian::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 642 of file translator_ru.h.
    {
      return " :"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorRussian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 840 of file translator_ru.h.
    {
      return "";
    }
trInstanceMethods()
QCString TranslatorRussian::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1886 of file translator_ru.h.
    {
      return " ";
    }
trInterfaceDocumentation()
QCString TranslatorRussian::trInterfaceDocumentation () inline override virtual
Implements Translator.
Definition at line 2144 of file translator_ru.h.
{
    return " ";
  }
trInterfaceHierarchy()
QCString TranslatorRussian::trInterfaceHierarchy () inline override virtual
Implements Translator.
Definition at line 2139 of file translator_ru.h.
{ return " "; }
trInterfaceHierarchyDescription()
QCString TranslatorRussian::trInterfaceHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2140 of file translator_ru.h.
{
    return "     ,   "
           ",    :";
  }
trInterfaceIndex()
QCString TranslatorRussian::trInterfaceIndex () inline override virtual
Implements Translator.
Definition at line 2134 of file translator_ru.h.
{ return " "; }
trInterfaceList()
QCString TranslatorRussian::trInterfaceList () inline override virtual
Implements Translator.
Definition at line 2135 of file translator_ru.h.
{ return " "; }
trInterfaceListDescription()
QCString TranslatorRussian::trInterfaceListDescription () inline override virtual
Implements Translator.
Definition at line 2136 of file translator_ru.h.
{
    return "       :";
  }
trInterfaces()
QCString TranslatorRussian::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1903 of file translator_ru.h.
    { return " "; }
trInvariant()
QCString TranslatorRussian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 835 of file translator_ru.h.
    {
      return "";
    }
trISOLang()
QCString TranslatorRussian::trISOLang () inline override virtual
Implements Translator.
Definition at line 40 of file translator_ru.h.
    { return "ru"; }
trLegend()
QCString TranslatorRussian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1034 of file translator_ru.h.
    {
      return ". ";
    }
trLegendDocs()
QCString TranslatorRussian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 972 of file translator_ru.h.
    {
      return
        ",   .<p>\n"
        "  :\n"
        "\\code\n"
        "/*!   -  */\n"
        "class Invisible { };\n\n"
        "/*!  ,    */\n"
        "class Truncated : public Invisible { };\n\n"
        "/*   */\n"
        "class Undocumented { };\n\n"
        "/*!   */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*!   */\n"
        "template<class T> class Templ {};\n\n"
        "/*!   */\n"
        "class ProtectedBase { };\n\n"
        "/*!   */\n"
        "class PrivateBase { };\n\n"
        "/*! ,   Inherited */\n"
        "class Used { };\n\n"
        "/*! ,     */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "  :"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "      :\n"
        "<ul>\n"
        "<li>      , "
        "   .\n"
        "<li>        .\n"
        "<li>        .\n"
        "<li>        ,  \n"
        "    / .  , "
        "      .\n"
        "</ul>\n"
        "   :\n"
        "<ul>\n"
        "<li>-        "
        "  .\n"
        "<li>-     .\n"
        "<li>-     .\n"
        "<li>  ,    "
        "     ."
        "   , "
        "      . \n"
        "<li>        "
        ",      .  "
        "  .\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorRussian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 967 of file translator_ru.h.
    {
      return "";
    }
trListOfAllMembers()
QCString TranslatorRussian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 96 of file translator_ru.h.
    {
      return "   ";
    }
trLoading()
QCString TranslatorRussian::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1694 of file translator_ru.h.
    {
      return "...";
    }
trMainPage()
QCString TranslatorRussian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 764 of file translator_ru.h.
    { return " "; }
trMember()
QCString TranslatorRussian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1197 of file translator_ru.h.
    {
      return createNoun(first_capital, singular, "", "");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorRussian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 78 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorRussian::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 70 of file translator_ru.h.
    { return ""; }
trMemberFunctionDocumentation()
QCString TranslatorRussian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 74 of file translator_ru.h.
    { return ""; }
trMemberFunctionDocumentationFortran()
QCString TranslatorRussian::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1482 of file translator_ru.h.
    { return "/"; }
trMemberList()
QCString TranslatorRussian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 103 of file translator_ru.h.
    {
      return "C  ";
    }
trMemberTypedefDocumentation()
QCString TranslatorRussian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 66 of file translator_ru.h.
    { return " "; }
trMethodDocumentation()
QCString TranslatorRussian::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1893 of file translator_ru.h.
    {
      return " ";
    }
trModule()
QCString TranslatorRussian::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1634 of file translator_ru.h.
    {
      return createNoun(first_capital, singular, "", "", "");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorRussian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 338 of file translator_ru.h.
    { return ""; }
trModuleIndex()
QCString TranslatorRussian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 305 of file translator_ru.h.
    { return "  "; }
trModuleMembersDescriptionTotal()
QCString TranslatorRussian::trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2525 of file translator_ru.h.
{
    bool extractAll = Config_getBool(EXTRACT_ALL);
    QCString result = "  ";
    if (!extractAll)
      result += " ";
    QCString singularResult = "";
    QCString pluralResult = "";
    switch (hl) {
    case ModuleMemberHighlight::All:
      singularResult = "";
      pluralResult = "";
      break;
    case ModuleMemberHighlight::Functions:
      singularResult = "";
      pluralResult = "";
      break;
    case ModuleMemberHighlight::Variables:
      singularResult = "";
      pluralResult = "";
      break;
    case ModuleMemberHighlight::Typedefs:
      singularResult = "";
      pluralResult = " ";
      break;
    case ModuleMemberHighlight::Enums:
      singularResult = "";
      pluralResult = "";
      break;
    case ModuleMemberHighlight::EnumValues:
      singularResult = "";
      pluralResult = " ";
      break;
    case ModuleMemberHighlight::Total: // for completeness
      break;
    };
    result += pluralResult + "    ";
    if (extractAll)
      result += "     " + singularResult + ":";
    else
      result += "     :";
    return result;
  }
References ModuleMemberHighlight::All, Config_getBool, ModuleMemberHighlight::Enums, ModuleMemberHighlight::EnumValues, ModuleMemberHighlight::Functions, ModuleMemberHighlight::Total, ModuleMemberHighlight::Typedefs, and ModuleMemberHighlight::Variables.
trModuleReference()
QCString TranslatorRussian::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1598 of file translator_ru.h.
    {
      return QCString(" ") + namespaceName;
    }
trModules()
QCString TranslatorRussian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 145 of file translator_ru.h.
    { return ""; }
trModulesDescription()
QCString TranslatorRussian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 292 of file translator_ru.h.
    { return "  ."; }
trModulesIndex()
QCString TranslatorRussian::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1627 of file translator_ru.h.
    { return " "; }
trModulesList()
QCString TranslatorRussian::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1548 of file translator_ru.h.
    { return " "; }
trModulesListDescription()
QCString TranslatorRussian::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1552 of file translator_ru.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=":";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorRussian::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1608 of file translator_ru.h.
    {
      QCString result="  ";
      if (!extractAll) result+=" ";
      result+="   ";
      if (extractAll)
      {
        result+="    :";
      }
      else
      {
        result+=" ,  :";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorRussian::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1604 of file translator_ru.h.
    { return " "; }
trMonth()
QCString TranslatorRussian::trMonth (int month, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1776 of file translator_ru.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[]  = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore()
QCString TranslatorRussian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 91 of file translator_ru.h.
    { return "..."; }
trNamespace()
QCString TranslatorRussian::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1170 of file translator_ru.h.
    {
      return createNoun(first_capital, singular, "", " ", " ");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorRussian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 698 of file translator_ru.h.
    { return " "; }
trNamespaceIndex()
QCString TranslatorRussian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 692 of file translator_ru.h.
    { return "   "; }
trNamespaceList()
QCString TranslatorRussian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 510 of file translator_ru.h.
    { return " "; }
trNamespaceListDescription()
QCString TranslatorRussian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 514 of file translator_ru.h.
    {
      QCString result="  ";
      if (!extractAll) result+=" ";
      result+=" .";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorRussian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 681 of file translator_ru.h.
    {
      QCString result="  ";
      if (!extractAll) result+=" ";
      result+="  .";
      return result;
    }
trNamespaceMembers()
QCString TranslatorRussian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 677 of file translator_ru.h.
    { return "  "; }
trNamespaceMembersDescriptionTotal()
QCString TranslatorRussian::trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2458 of file translator_ru.h.
{
    bool extractAll = Config_getBool(EXTRACT_ALL);
    QCString result = "  ";
    if (!extractAll)
      result += " ";
    QCString singularResult = "";
    QCString pluralResult = "";
    switch (hl) {
    case NamespaceMemberHighlight::All:
      singularResult = "";
      pluralResult = "";
      break;
    case NamespaceMemberHighlight::Functions:
      singularResult = "";
      pluralResult = "";
      break;
    case NamespaceMemberHighlight::Variables:
      singularResult = "";
      pluralResult = "";
      break;
    case NamespaceMemberHighlight::Typedefs:
      singularResult = "";
      pluralResult = " ";
      break;
    case NamespaceMemberHighlight::Sequences:
      singularResult = "";
      pluralResult = "";
      break;
    case NamespaceMemberHighlight::Dictionaries:
      singularResult = "";
      pluralResult = "";
      break;
    case NamespaceMemberHighlight::Enums:
      singularResult = "";
      pluralResult = "";
      break;
    case NamespaceMemberHighlight::EnumValues:
      singularResult = "";
      pluralResult = " ";
      break;
    case NamespaceMemberHighlight::Total: // for completeness
      break;
    }
    result += pluralResult + "    ";
    if (extractAll)
      result +=
          "     " + singularResult + ":";
    else
      result += " ,    :";
    return result;
  }
References NamespaceMemberHighlight::All, Config_getBool, NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, NamespaceMemberHighlight::Sequences, NamespaceMemberHighlight::Total, NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
trNamespaceReference()
QCString TranslatorRussian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 589 of file translator_ru.h.
    {
      return QCString("  ")+namespaceName;
    }
trNamespaces()
QCString TranslatorRussian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 708 of file translator_ru.h.
    { return " "; }
trNoMatches()
QCString TranslatorRussian::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1712 of file translator_ru.h.
    {
      return " ";
    }
trNote()
QCString TranslatorRussian::trNote () inline override virtual
Implements Translator.
Definition at line 870 of file translator_ru.h.
    {
      return "";
    }
trOperationDocumentation()
QCString TranslatorRussian::trOperationDocumentation () inline override virtual
Implements Translator.
Definition at line 2213 of file translator_ru.h.
{
    return " ";
  }
trOperations()
QCString TranslatorRussian::trOperations () inline override virtual
Implements Translator.
Definition at line 2212 of file translator_ru.h.
{ return ""; }
trOverloadText()
QCString TranslatorRussian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1451 of file translator_ru.h.
    {
       return "      "
              "  .     "
              "  .";
    }
trPackage()
QCString TranslatorRussian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1086 of file translator_ru.h.
    {
      return QCString(" ")+name;
    }
trPackageAttribs()
QCString TranslatorRussian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1325 of file translator_ru.h.
    {
      return "    ";
    }
trPackageFunctions()
QCString TranslatorRussian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1307 of file translator_ru.h.
    {
      return "    ";
    }
trPackageList()
QCString TranslatorRussian::trPackageList () inline override virtual
Implements Translator.
Definition at line 2268 of file translator_ru.h.
{ return " "; }
trPackageListDescription()
QCString TranslatorRussian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1091 of file translator_ru.h.
    {
      return "   .";
    }
trPackageMembers()
QCString TranslatorRussian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1311 of file translator_ru.h.
    {
      return "    ";
    }
trPackages()
QCString TranslatorRussian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1096 of file translator_ru.h.
    {
      return "";
    }
trPackageTypes()
QCString TranslatorRussian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1300 of file translator_ru.h.
    {
      return "    ";
    }
trPage()
QCString TranslatorRussian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1188 of file translator_ru.h.
    {
      return createNoun(first_capital, singular, "", "", "");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorRussian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 770 of file translator_ru.h.
    { return "."; }
trPageIndex()
QCString TranslatorRussian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 861 of file translator_ru.h.
    {
      return "   ";
    }
trPanelSynchronisationTooltip()
QCString TranslatorRussian::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1851 of file translator_ru.h.
    {
      QCString opt = enable ? "" : "";
      return "  "+opt+"   ";
    }
trParameters()
QCString TranslatorRussian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 494 of file translator_ru.h.
    { return ""; }
trPostcondition()
QCString TranslatorRussian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 830 of file translator_ru.h.
    {
      return "";
    }
trPrecondition()
QCString TranslatorRussian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 825 of file translator_ru.h.
    {
      return "";
    }
trPrivateAttribs()
QCString TranslatorRussian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 909 of file translator_ru.h.
    {
      return " ";
    }
trPrivateMembers()
QCString TranslatorRussian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 608 of file translator_ru.h.
    { return " "; }
trPrivateSlots()
QCString TranslatorRussian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 610 of file translator_ru.h.
    { return " "; }
trPrivateTypes()
QCString TranslatorRussian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 905 of file translator_ru.h.
    {
      return " ";
    }
trProperties()
QCString TranslatorRussian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1059 of file translator_ru.h.
    {
      return "";
    }
trPropertyDocumentation()
QCString TranslatorRussian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1064 of file translator_ru.h.
    {
      return "  ";
    }
trProtectedAttribs()
QCString TranslatorRussian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 897 of file translator_ru.h.
    {
      return " ";
    }
trProtectedMembers()
QCString TranslatorRussian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 602 of file translator_ru.h.
    { return " "; }
trProtectedSlots()
QCString TranslatorRussian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 604 of file translator_ru.h.
    { return " "; }
trProtectedTypes()
QCString TranslatorRussian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 893 of file translator_ru.h.
    {
      return " ";
    }
trProvidedByCategory()
QCString TranslatorRussian::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1861 of file translator_ru.h.
    {
      return "  @0.";
    }
trPublicAttribs()
QCString TranslatorRussian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 878 of file translator_ru.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorRussian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 594 of file translator_ru.h.
    { return " "; }
trPublicSlots()
QCString TranslatorRussian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 596 of file translator_ru.h.
    { return " "; }
trPublicTypes()
QCString TranslatorRussian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 874 of file translator_ru.h.
    {
      return " ";
    }
trReferencedBy()
QCString TranslatorRussian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 940 of file translator_ru.h.
    {
      return " ";
    }
trReferenceManual()
QCString TranslatorRussian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 367 of file translator_ru.h.
    { return ""; }
trReferences()
QCString TranslatorRussian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1228 of file translator_ru.h.
    {
      return " ";
    }
trReimplementedFromList()
QCString TranslatorRussian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 658 of file translator_ru.h.
    {
      QCString result=" ";
      if(numEntries>1)
        result+=" ";
      else
        result+=" ";
      return result+" "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorRussian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 671 of file translator_ru.h.
    {
      return "  "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorRussian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 535 of file translator_ru.h.
    { return "     , "
        "  "; }
trRelatedFunctions()
QCString TranslatorRussian::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 50 of file translator_ru.h.
    { return "   "; }
trRelatedPages()
QCString TranslatorRussian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 190 of file translator_ru.h.
    { return ""; }
trRelatedPagesDescription()
QCString TranslatorRussian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 288 of file translator_ru.h.
    { return "   ."; }
trRelatedSubscript()
QCString TranslatorRussian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 54 of file translator_ru.h.
    { return "(  )"; }
trRelatedSymbolDocumentation()
QCString TranslatorRussian::trRelatedSymbolDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes.
Supersedes trRelatedFunctionDocumentation
Implements Translator.
Definition at line 2304 of file translator_ru.h.
{
    return "      ";
  }
trRelatedSymbols()
QCString TranslatorRussian::trRelatedSymbols () inline override virtual
Please translate also updated body of the method trMemberFunctionDocumentation(), now better adapted for VHDL sources documentation.
used in the compound documentation before a list of related symbols.
Supersedes trRelatedFunctions
Implements Translator.
Definition at line 2291 of file translator_ru.h.
{ return "  :"; }
trRelatedSymbolsSubscript()
QCString TranslatorRussian::trRelatedSymbolsSubscript () inline override virtual
subscript for the related symbols
Supersedes trRelatedSubscript
Implements Translator.
Definition at line 2297 of file translator_ru.h.
{ return "()"; }
trRemarks()
QCString TranslatorRussian::trRemarks () inline override virtual
Implements Translator.
Definition at line 944 of file translator_ru.h.
    {
      return ".";
    }
trReturns()
QCString TranslatorRussian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 486 of file translator_ru.h.
    { return ""; }
trReturnValues()
QCString TranslatorRussian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 759 of file translator_ru.h.
    { return " "; }
trRTFansicp()
QCString TranslatorRussian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1125 of file translator_ru.h.
    {
      return "1251";
    }
trRTFCharSet()
QCString TranslatorRussian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1130 of file translator_ru.h.
    {
      return "204";
    }
trRTFGeneralIndex()
QCString TranslatorRussian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1135 of file translator_ru.h.
    {
      return " ";
    }
trRTFTableOfContents()
QCString TranslatorRussian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1260 of file translator_ru.h.
    {
      return "";
    }
trSearch()
QCString TranslatorRussian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 200 of file translator_ru.h.
    { return ""; }
trSearching()
QCString TranslatorRussian::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1706 of file translator_ru.h.
    {
      return "...";
    }
trSearchMatches()
QCString TranslatorRussian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1392 of file translator_ru.h.
    {
      return ":";
    }
trSearchResults()
QCString TranslatorRussian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1373 of file translator_ru.h.
    {
      if (numDocuments==0)
      {
        return " ,      .";
      }
      else if( numDocuments == 1 )
      {
        return " 1 .";
      }
      else
      {
        return "() <b>$num</b> (). "
          "   .";
      }
    }
trSearchResultsTitle()
QCString TranslatorRussian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1361 of file translator_ru.h.
    {
      return " ";
    }
trSeeAlso()
QCString TranslatorRussian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 490 of file translator_ru.h.
    { return ". "; }
trSequenceDocumentation()
QCString TranslatorRussian::trSequenceDocumentation () inline override virtual
Implements Translator.
Definition at line 2126 of file translator_ru.h.
{
    return " ";
  }
trSequences()
QCString TranslatorRussian::trSequences () inline override virtual
Implements Translator.
Definition at line 2125 of file translator_ru.h.
{ return ""; }
trServiceGeneratedFromFiles()
QCString TranslatorRussian::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 1936 of file translator_ru.h.
    {
      // single is true implies a single file
      QCString result="    "
                                "   ";
      if (single) result+=":"; else result+=":";
      return result;
    }
trServiceReference()
QCString TranslatorRussian::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 1922 of file translator_ru.h.
    {
      QCString result=sName;
      result+="   ";
      return result;
    }
trServices()
QCString TranslatorRussian::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1907 of file translator_ru.h.
    { return " "; }
trSignals()
QCString TranslatorRussian::trSignals () inline override virtual
Implements Translator.
Definition at line 598 of file translator_ru.h.
    { return ""; }
trSince()
QCString TranslatorRussian::trSince () inline override virtual
Implements Translator.
Definition at line 956 of file translator_ru.h.
    {
      return " ";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorRussian::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 1945 of file translator_ru.h.
    {
      // single is true implies a single file
      QCString result="    "
                                "   ";
      if (single) result+=":"; else result+=":";
      return result;
    }
trSingletonReference()
QCString TranslatorRussian::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 1929 of file translator_ru.h.
    {
      QCString result=sName;
      result+="   ";
      return result;
    }
trSliceInterfaces()
QCString TranslatorRussian::trSliceInterfaces () inline override virtual
Implements Translator.
Definition at line 2133 of file translator_ru.h.
{ return ""; }
trSourceFile()
QCString TranslatorRussian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1403 of file translator_ru.h.
    {
      return "  " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorRussian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1332 of file translator_ru.h.
    {
      return "     ";
    }
trStaticPackageFunctions()
QCString TranslatorRussian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1318 of file translator_ru.h.
    {
      return "     ";
    }
trStaticPrivateAttribs()
QCString TranslatorRussian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 913 of file translator_ru.h.
    {
      return "  ";
    }
trStaticPrivateMembers()
QCString TranslatorRussian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 612 of file translator_ru.h.
    { return "  "; }
trStaticProtectedAttribs()
QCString TranslatorRussian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 901 of file translator_ru.h.
    {
      return "  ";
    }
trStaticProtectedMembers()
QCString TranslatorRussian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 606 of file translator_ru.h.
    { return "  "; }
trStaticPublicAttribs()
QCString TranslatorRussian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 889 of file translator_ru.h.
    {
      return "  ";
    }
trStaticPublicMembers()
QCString TranslatorRussian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 600 of file translator_ru.h.
    { return "  "; }
trStructDocumentation()
QCString TranslatorRussian::trStructDocumentation () inline override virtual
Implements Translator.
Definition at line 2153 of file translator_ru.h.
{ return " "; }
trStructIndex()
QCString TranslatorRussian::trStructIndex () inline override virtual
Implements Translator.
Definition at line 2148 of file translator_ru.h.
{ return " "; }
trStructList()
QCString TranslatorRussian::trStructList () inline override virtual
Implements Translator.
Definition at line 2149 of file translator_ru.h.
{ return " "; }
trStructListDescription()
QCString TranslatorRussian::trStructListDescription () inline override virtual
Implements Translator.
Definition at line 2150 of file translator_ru.h.
{
    return "       :";
  }
trStructs()
QCString TranslatorRussian::trStructs () inline override virtual
Implements Translator.
Definition at line 2147 of file translator_ru.h.
{ return ""; }
trSubprogram()
QCString TranslatorRussian::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1673 of file translator_ru.h.
    {
      return createNoun(first_capital, singular, "", "", "");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorRussian::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1538 of file translator_ru.h.
    { return "/"; }
trSubprograms()
QCString TranslatorRussian::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1532 of file translator_ru.h.
    { return "/"; }
trTemplateParameters()
QCString TranslatorRussian::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1814 of file translator_ru.h.
    { return " "; }
trTest()
QCString TranslatorRussian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1044 of file translator_ru.h.
    {
      return "";
    }
trTestList()
QCString TranslatorRussian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1049 of file translator_ru.h.
    {
      return " ";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorRussian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 110 of file translator_ru.h.
    { return "   "; }
trTodo()
QCString TranslatorRussian::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 924 of file translator_ru.h.
    {
      return " ";
    }
trTodoList()
QCString TranslatorRussian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 930 of file translator_ru.h.
    {
      return " ";
    }
trTopicDocumentation()
QCString TranslatorRussian::trTopicDocumentation () inline override virtual
Implements Translator.
Definition at line 2518 of file translator_ru.h.
{ return " "; }
trTopicIndex()
QCString TranslatorRussian::trTopicIndex () inline override virtual
Implements Translator.
Definition at line 2520 of file translator_ru.h.
{ return " "; }
trTopicList()
QCString TranslatorRussian::trTopicList () inline override virtual
Implements Translator.
Definition at line 2519 of file translator_ru.h.
{ return " "; }
trTopicListDescription()
QCString TranslatorRussian::trTopicListDescription () inline override virtual
Implements Translator.
Definition at line 2521 of file translator_ru.h.
{
    return "   c  :";
  }
trTopics()
QCString TranslatorRussian::trTopics () inline override virtual
Implements Translator.
Definition at line 2517 of file translator_ru.h.
{ return ""; }
trType()
QCString TranslatorRussian::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1665 of file translator_ru.h.
    {
      return createNoun(first_capital, singular, "", "");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trTypeConstraints()
QCString TranslatorRussian::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1679 of file translator_ru.h.
    {
      return " ";
    }
trTypedefDocumentation()
QCString TranslatorRussian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 415 of file translator_ru.h.
    { return ""; }
trTypedefs()
QCString TranslatorRussian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 379 of file translator_ru.h.
    { return " "; }
trTypeDocumentation()
QCString TranslatorRussian::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1526 of file translator_ru.h.
    { return "  "; }
trVariableDocumentation()
QCString TranslatorRussian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 433 of file translator_ru.h.
    { return ""; }
trVariables()
QCString TranslatorRussian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 397 of file translator_ru.h.
    { return ""; }
trVersion()
QCString TranslatorRussian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 478 of file translator_ru.h.
    { return ""; }
trVhdlType()
QCString TranslatorRussian::trVhdlType (VhdlSpecifier type, bool single) inline override virtual
VHDL type.
Implements Translator.
Definition at line 1987 of file translator_ru.h.
{
    switch (type) {
    case VhdlSpecifier::LIBRARY:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::PACKAGE:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::SIGNAL:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::COMPONENT:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::CONSTANT:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::ENTITY:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::TYPE:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::SUBTYPE:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::FUNCTION:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::RECORD:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::PROCEDURE:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::ARCHITECTURE:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::ATTRIBUTE:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::PROCESS:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::PORT:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::USE:
      if (single)
        return " ";
      else
        return " ";
    case VhdlSpecifier::GENERIC:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::PACKAGE_BODY:
      return " ";
    case VhdlSpecifier::UNITS:
      return "";
    case VhdlSpecifier::SHAREDVARIABLE:
      if (single)
        return " ";
      else
        return " ";
    case VhdlSpecifier::VFILE:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::GROUP:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::INSTANTIATION:
      if (single)
        return " ";
      else
        return " ";
    case VhdlSpecifier::ALIAS:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::CONFIG:
      if (single)
        return "";
      else
        return "";
    case VhdlSpecifier::MISCELLANEOUS:
      return "";
    case VhdlSpecifier::UCF_CONST:
      return "";
    default:
      return "";
    }
  }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorRussian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 474 of file translator_ru.h.
    { return ""; }
trWriteList()
QCString TranslatorRussian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 618 of file translator_ru.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+="  ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_ru.h