Doxygen: src/vhdljjparser.h File Reference
vhdljjparser.h File Reference
#include <vector>
#include <memory>
#include <string>
#include "parserintf.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <ctype.h>
#include "types.h"
#include "entry.h"
#include "vhdldocgen.h"
#include "config.h"
#include "util.h"
Classes
class VHDLOutlineParser
VHDL parser using state-based lexical scanning.
Enumerations
enum class VhdlSection {
UNKNOWN = 0 , GEN_SEC =0x1 , PARAM_SEC , CONTEXT_SEC ,
PROTECTED_SEC
}
Functions
const EntryList & getVhdlInstList ()
QCString filter2008VhdlComment (const QCString &s)
Enumeration Type Documentation
VhdlSection
enum class VhdlSection strong
Enumerator
UNKNOWN
GEN_SEC
PARAM_SEC
CONTEXT_SEC
PROTECTED_SEC
Definition at line 20 of file vhdljjparser.h.
{ UNKNOWN = 0, GEN_SEC=0x1, PARAM_SEC,CONTEXT_SEC,PROTECTED_SEC } ;
Function Documentation
filter2008VhdlComment()
QCString filter2008VhdlComment (const QCString & s)
Definition at line 868 of file vhdljjparser.cpp.
{
  if (s.length()<4) return s;
  GrowBuf growBuf;
  const char *p=s.data()+3; // skip /*!
  char c='\0';
  while (*p == ' ' || *p == '\t') p++;
  while ((c=*p++))
  {
    growBuf.addChar(c);
    if (c == '\n')
    {
      // special handling of space followed by * at beginning of line
      while (*p == ' ' || *p == '\t') p++;
      while (*p == '*') p++;
      // special attention in case character at end is /
      if (*p == '/') p++;
    }
  }
  // special attention in case */ at end of last line
  size_t len = growBuf.getPos();
  if (len>=2 && growBuf.at(len-1) == '/' && growBuf.at(len-2) == '*')
  {
    len -= 2;
    while (len>0 && growBuf.at(len-1) == '*') len--;
    while (len>0 && ((c = growBuf.at(len-1)) == ' ' || c == '\t')) len--;
    growBuf.setPos(len);
  }
  growBuf.addChar(0);
  return growBuf.get();
}
References GrowBuf::addChar(), GrowBuf::at(), QCString::data(), GrowBuf::get(), GrowBuf::getPos(), QCString::length(), and GrowBuf::setPos().
getVhdlInstList()
const EntryList & getVhdlInstList ()
Definition at line 845 of file vhdljjparser.cpp.
{
  return g_instFiles;
}
References g_instFiles.
Referenced by VhdlDocGen::computeVhdlComponentRelations().