Doxygen: XMLLocator Class Reference
XMLLocator Class Reference abstract
#include <libxml/xml.h>
Public Member Functions
XMLLocator ()=default
XMLLocator (const XMLLocator &)=delete
XMLLocator & operator= (const XMLLocator &)=delete
XMLLocator (XMLLocator &&)=delete
XMLLocator & operator= (XMLLocator &&)=delete
virtual ~XMLLocator ()=default
virtual int lineNr () const =0
virtual std::string fileName () const =0
Detailed Description
Definition at line 55 of file xml.h.
Constructor & Destructor Documentation
XMLLocator() [1/3]
XMLLocator::XMLLocator () default
Referenced by operator=(), operator=(), XMLLocator(), and XMLLocator().
XMLLocator() [2/3]
XMLLocator::XMLLocator (const XMLLocator &) delete
References XMLLocator().
XMLLocator() [3/3]
XMLLocator::XMLLocator (XMLLocator &&) delete
References XMLLocator().
~XMLLocator()
virtual XMLLocator::~XMLLocator () virtual default
Member Function Documentation
fileName()
virtual std::string XMLLocator::fileName () const pure virtual
Implemented in XMLParser.
lineNr()
virtual int XMLLocator::lineNr () const pure virtual
Implemented in XMLParser.
operator=() [1/2]
XMLLocator & XMLLocator::operator= (const XMLLocator &) delete
References XMLLocator().
operator=() [2/2]
XMLLocator & XMLLocator::operator= (XMLLocator &&) delete
References XMLLocator().
The documentation for this class was generated from the following file:
libxml/xml.h