Doxygen: ConfigContext::Private Class Reference
ConfigContext::Private Class Reference
Public Member Functions
StringVector fields () const
TemplateVariant get (const QCString &name) const
Private Types
using ConfigData = std::map< std::string, TemplateVariant >
Private Member Functions
ConfigData createConfigData () const
StringVector createFields () const
Private Attributes
CachedItem< StringVector, Private, &Private::createFields > m_fields
CachedItem< ConfigData, Private, &Private::createConfigData > m_configData
Detailed Description
Definition at line 237 of file context.cpp.
Member Typedef Documentation
ConfigData
using ConfigContext::Private::ConfigData = std::map<std::string,TemplateVariant> private
Definition at line 252 of file context.cpp.
Member Function Documentation
createConfigData()
ConfigData ConfigContext::Private::createConfigData () const inline private
Definition at line 254 of file context.cpp.
    {
      std::map<std::string,TemplateVariant> map;
      for (auto name : ConfigValues::instance().fields())
      {
        const ConfigValues::Info *option = ConfigValues::instance().get(QCString(name));
        if (option)
        {
          switch (option->type)
          {
            case ConfigValues::Info::Bool:
              {
                bool b = ConfigValues::instance().*(option->value.b);
                map.insert(std::make_pair(name,TemplateVariant(b)));
              }
              break;
            case ConfigValues::Info::Int:
              {
                int i = ConfigValues::instance().*(option->value.i);
                map.insert(std::make_pair(name,TemplateVariant(i)));
              }
              break;
            case ConfigValues::Info::String:
              {
                QCString s = ConfigValues::instance().*(option->value.s);
                map.insert(std::make_pair(name,TemplateVariant(s)));
              }
              break;
            case ConfigValues::Info::List:
              {
                auto fetchList = [](const StringVector &list) -> TemplateVariant
                {
                  TemplateVariantList elements;
                  elements.reserve(list.size());
                  for (const auto &s : list)
                  {
                    elements.push_back(TemplateVariant(s));
                  }
                  return TemplateImmutableList::alloc(elements);
                };
                const StringVector &l = ConfigValues::instance().*(option->value.l);
                map.insert(std::make_pair(name,fetchList(l)));
              }
              break;
            default:
              break;
          }
        }
      }
      return map;
    }
References TemplateImmutableList::alloc(), and QCString::insert().
createFields()
StringVector ConfigContext::Private::createFields () const inline private
Definition at line 306 of file context.cpp.
    {
      return ConfigValues::instance().fields();
    }
fields()
StringVector ConfigContext::Private::fields () const inline
Definition at line 241 of file context.cpp.
    {
      return m_fields.get(this);
    }
References m_fields.
get()
TemplateVariant ConfigContext::Private::get (const QCString & name) const inline
Definition at line 245 of file context.cpp.
    {
      auto &data = m_configData.get(this);
      auto it = data.find(name.str());
      return (it!=data.end()) ? it->second : TemplateVariant();
    }
References m_configData, and QCString::str().
Member Data Documentation
m_configData
CachedItem<ConfigData, Private, &Private::createConfigData> ConfigContext::Private::m_configData private
Definition at line 312 of file context.cpp.
Referenced by get().
m_fields
CachedItem<StringVector, Private, &Private::createFields > ConfigContext::Private::m_fields private
Definition at line 311 of file context.cpp.
Referenced by fields().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/context.cpp