Doxygen: DocSimpleListItem Class Reference
DocSimpleListItem Class Reference
Node representing a simple list item.
#include <docnode.h>
Public Member Functions
DocSimpleListItem (DocParser *parser, DocNodeVariant *parent)
int parse ()
const DocNodeVariant * paragraph () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
DocNode (const DocNode &)=delete
DocNode & operator= (const DocNode &)=delete
DocNode (DocNode &&)=default
DocNode & operator= (DocNode &&)=default
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
std::unique_ptr< DocNodeVariant > m_paragraph
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a simple list item.
Definition at line 1113 of file docnode.h.
Constructor & Destructor Documentation
DocSimpleListItem()
DocSimpleListItem::DocSimpleListItem (DocParser * parser, DocNodeVariant * parent)
Definition at line 2618 of file docnode.cpp.
      : DocNode(parser,parent)
{
}
Member Function Documentation
paragraph()
const DocNodeVariant * DocSimpleListItem::paragraph () const inline
Definition at line 1118 of file docnode.h.
{ return m_paragraph.get(); }
References m_paragraph.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
parse()
int DocSimpleListItem::parse ()
Definition at line 2624 of file docnode.cpp.
{
  auto ns = AutoNodeStack(parser(),thisVariant());
  m_paragraph = createDocNode<DocPara>(parser(),thisVariant());
  DocPara *par = &std::get<DocPara>(*m_paragraph);
  int rv=par->parse();
  par->markFirst();
  par->markLast();
  return rv;
}
References m_paragraph, DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), DocNode::parser(), and DocNode::thisVariant().
Referenced by DocSimpleList::parse().
Member Data Documentation
m_paragraph
std::unique_ptr<DocNodeVariant> DocSimpleListItem::m_paragraph private
Definition at line 1121 of file docnode.h.
Referenced by paragraph(), and parse().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/docnode.h
/home/runner/work/doxygen/doxygen/src/docnode.cpp