Doxygen: PlantumlManager Class Reference
PlantumlManager Class Reference
Singleton that manages plantuml relation actions.
#include <src/plantuml.h>
Public Types
enum OutputFormat { PUML_BITMAP , PUML_EPS , PUML_SVG }
Plant UML output image formats.
using FilesMap = std::map< std::string, StringVector >
using ContentMap = std::map< std::string, PlantumlContent >
Public Member Functions
void run ()
Run plant UML tool for all images.
QCString writePlantUMLSource (const QCString &outDirArg, const QCString &fileName, const QCString &content, OutputFormat format, const QCString &engine, const QCString &srcFile, int srcLine, bool inlineCode)
Write a PlantUML compatible file.
void generatePlantUMLOutput (const QCString &baseName, const QCString &outDir, OutputFormat format)
Convert a PlantUML file to an image.
Static Public Member Functions
static PlantumlManager & instance ()
Private Member Functions
PlantumlManager ()
void insert (const std::string &key, const std::string &value, const QCString &outDir, OutputFormat format, const QCString &puContent, const QCString &srcFile, int srcLine)
Private Attributes
FilesMap m_pngPlantumlFiles
FilesMap m_svgPlantumlFiles
FilesMap m_epsPlantumlFiles
ContentMap m_pngPlantumlContent
ContentMap m_svgPlantumlContent
ContentMap m_epsPlantumlContent
Detailed Description
Singleton that manages plantuml relation actions.
Definition at line 40 of file plantuml.h.
Member Typedef Documentation
ContentMap
using PlantumlManager::ContentMap = std::map< std::string, PlantumlContent >
Definition at line 76 of file plantuml.h.
FilesMap
using PlantumlManager::FilesMap = std::map< std::string, StringVector >
Definition at line 75 of file plantuml.h.
Member Enumeration Documentation
OutputFormat
enum PlantumlManager::OutputFormat
Plant UML output image formats.
Enumerator
PUML_BITMAP
PUML_EPS
PUML_SVG
Definition at line 44 of file plantuml.h.
{ PUML_BITMAP, PUML_EPS, PUML_SVG };
Constructor & Destructor Documentation
PlantumlManager()
PlantumlManager::PlantumlManager () private
Definition at line 162 of file plantuml.cpp.
{
}
Referenced by instance().
Member Function Documentation
generatePlantUMLOutput()
void PlantumlManager::generatePlantUMLOutput (const QCString & baseName, const QCString & outDir, OutputFormat format)
Convert a PlantUML file to an image.
Parameters
[in] baseName the name of the generated file (as returned by writePlantUMLSource())
[in] outDir the directory to write the resulting image into.
[in] format the image format to generate.
Definition at line 127 of file plantuml.cpp.
{
  QCString imgName = baseName;
  // The basename contains path, we need to strip the path from the filename in order
  // to create the image file name which should be included in the index.qhp (Qt help index file).
  int i = imgName.findRev('/');
  if (i!=-1) // strip path
  {
    imgName=imgName.mid(i+1);
  }
  switch (format)
  {
    case PUML_BITMAP:
      imgName+=".png";
      break;
    case PUML_EPS:
      imgName+=".eps";
      break;
    case PUML_SVG:
      imgName+=".svg";
      break;
  }
  Doxygen::indexList->addImageFile(imgName);
}
References IndexList::addImageFile(), QCString::findRev(), Doxygen::indexList, QCString::mid(), PUML_BITMAP, PUML_EPS, and PUML_SVG.
Referenced by FlowChart::printUmlTree(), DocbookDocVisitor::startPlantUmlFile(), LatexDocVisitor::startPlantUmlFile(), DocbookDocVisitor::writePlantUMLFile(), HtmlDocVisitor::writePlantUMLFile(), LatexDocVisitor::writePlantUMLFile(), and RTFDocVisitor::writePlantUMLFile().
insert()
void PlantumlManager::insert (const std::string & key, const std::string & value, const QCString & outDir, OutputFormat format, const QCString & puContent, const QCString & srcFile, int srcLine) private
Definition at line 372 of file plantuml.cpp.
{
  Debug::print(Debug::Plantuml,0,"*** PlantumlManager::insert key:%s ,value:%s\n",qPrint(key),qPrint(value));
  switch (format)
  {
    case PUML_BITMAP:
      addPlantumlFiles(m_pngPlantumlFiles,key,value);
      print(m_pngPlantumlFiles);
      addPlantumlContent(m_pngPlantumlContent,key,outDir,puContent,srcFile,srcLine);
      print(m_pngPlantumlContent);
      break;
    case PUML_EPS:
      addPlantumlFiles(m_epsPlantumlFiles,key,value);
      print(m_epsPlantumlFiles);
      addPlantumlContent(m_epsPlantumlContent,key,outDir,puContent,srcFile,srcLine);
      print(m_epsPlantumlContent);
      break;
    case PUML_SVG:
      addPlantumlFiles(m_svgPlantumlFiles,key,value);
      print(m_svgPlantumlFiles);
      addPlantumlContent(m_svgPlantumlContent,key,outDir,puContent,srcFile,srcLine);
      print(m_svgPlantumlContent);
      break;
  }
}
References addPlantumlContent(), addPlantumlFiles(), m_epsPlantumlContent, m_epsPlantumlFiles, m_pngPlantumlContent, m_pngPlantumlFiles, m_svgPlantumlContent, m_svgPlantumlFiles, Debug::Plantuml, Debug::print(), print(), PUML_BITMAP, PUML_EPS, PUML_SVG, and qPrint().
Referenced by writePlantUMLSource().
instance()
PlantumlManager & PlantumlManager::instance () static
Definition at line 156 of file plantuml.cpp.
{
  static PlantumlManager theInstance;
  return theInstance;
}
References PlantumlManager().
Referenced by generateOutput(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), FlowChart::printUmlTree(), DocbookDocVisitor::startPlantUmlFile(), LatexDocVisitor::startPlantUmlFile(), DocbookDocVisitor::writePlantUMLFile(), HtmlDocVisitor::writePlantUMLFile(), LatexDocVisitor::writePlantUMLFile(), RTFDocVisitor::writePlantUMLFile(), and writePlantUMLSource().
run()
void PlantumlManager::run ()
Run plant UML tool for all images.
Definition at line 314 of file plantuml.cpp.
{
  Debug::print(Debug::Plantuml,0,"*** %s\n","PlantumlManager::run");
  runPlantumlContent(m_pngPlantumlFiles, m_pngPlantumlContent, PUML_BITMAP);
  runPlantumlContent(m_svgPlantumlFiles, m_svgPlantumlContent, PUML_SVG);
  runPlantumlContent(m_epsPlantumlFiles, m_epsPlantumlContent, PUML_EPS);
}
References m_epsPlantumlContent, m_epsPlantumlFiles, m_pngPlantumlContent, m_pngPlantumlFiles, m_svgPlantumlContent, m_svgPlantumlFiles, Debug::Plantuml, Debug::print(), PUML_BITMAP, PUML_EPS, PUML_SVG, and runPlantumlContent().
Referenced by generateOutput().
writePlantUMLSource()
QCString PlantumlManager::writePlantUMLSource (const QCString & outDirArg, const QCString & fileName, const QCString & content, OutputFormat format, const QCString & engine, const QCString & srcFile, int srcLine, bool inlineCode)
Write a PlantUML compatible file.
Parameters
[in] outDirArg the output directory to write the file to.
[in] fileName the name of the file. If empty a name will be chosen automatically.
[in] content the contents of the PlantUML file.
[in] format the image format to generate.
[in] engine the plantuml engine to use.
[in] srcFile the source file resulting in the write command.
[in] srcLine the line number resulting in the write command.
[in] inlineCode the code is coming from the \statuml ... \enduml (true) command or from the \planumlfile command (false)
Returns
The name of the generated file.
Definition at line 27 of file plantuml.cpp.
{
  QCString baseName;
  QCString puName;
  QCString imgName;
  QCString outDir(outDirArg);
  static int umlindex=1;
  Debug::print(Debug::Plantuml,0,"*** %s fileName: %s\n","writePlantUMLSource",qPrint(fileName));
  Debug::print(Debug::Plantuml,0,"*** %s outDir: %s\n","writePlantUMLSource",qPrint(outDir));
  // strip any trailing slashes and backslashes
  size_t l = 0;
  while ((l=outDir.length())>0 && (outDir.at(l-1)=='/' || outDir.at(l-1)=='\\'))
  {
    outDir = outDir.left(l-1);
  }
  if (fileName.isEmpty()) // generate name
  {
    puName = "inline_umlgraph_"+QCString().setNum(umlindex);
    baseName = outDir+"/inline_umlgraph_"+QCString().setNum(umlindex++);
  }
  else // user specified name
  {
    baseName = fileName;
    int i=baseName.findRev('.');
    if (i!=-1) baseName = baseName.left(i);
    puName = baseName;
    baseName.prepend(outDir+"/");
  }
  switch (format)
  {
    case PUML_BITMAP:
      imgName =puName+".png";
      break;
    case PUML_EPS:
      imgName =puName+".eps";
      break;
    case PUML_SVG:
      imgName =puName+".svg";
      break;
  }
  Debug::print(Debug::Plantuml,0,"*** %s baseName: %s\n","writePlantUMLSource",qPrint(baseName));
  Debug::print(Debug::Plantuml,0,"*** %s puName: %s\n","writePlantUMLSource",qPrint(puName));
  Debug::print(Debug::Plantuml,0,"*** %s imgName: %s\n","writePlantUMLSource",qPrint(imgName));
  QCString text;
  if (inlineCode) text = "@start"+engine+" "+imgName+"\n";
  text.reserve(text.length()+content.length()+100); // add room for image name and end marker
  const char *p = content.data();
  if (p)
  {
    char c = 0;
    bool insideComment = false;
    bool initial       = true;
    while ((c=*p++))
    {
      text+=c;
      switch (c)
      {
        case '\'': insideComment=true; break;
        case '\n': insideComment=false; break;
        case '\t': break;
        case ' ':  break;
        case '@':
          if (initial && qstrncmp(p,"start",5)==0) // @start...
          {
            while ((c=*p++) && isId(c)) text+=c;
            // insert the image name
            text+=' ';
            text+=imgName;
            if (c) text+=c;
          }
          break;
        default:
          if (!insideComment) initial=false;
          break;
      }
    }
    text+='\n';
  }
  if (inlineCode) text +="@end"+engine+"\n";
  //printf("content\n====\n%s\n=====\n->\n-----\n%s\n------\n",qPrint(content),qPrint(text));
  QCString qcOutDir(substitute(outDir,"\\","/"));
  uint32_t pos = qcOutDir.findRev("/");
  QCString generateType(qcOutDir.right(qcOutDir.length() - (pos + 1)) );
  Debug::print(Debug::Plantuml,0,"*** %s generateType: %s\n","writePlantUMLSource",qPrint(generateType));
  PlantumlManager::instance().insert(generateType.str(),puName.str(),outDir,format,text,srcFile,srcLine);
  Debug::print(Debug::Plantuml,0,"*** %s generateType: %s\n","writePlantUMLSource",qPrint(generateType));
  return baseName;
}
References QCString::at(), QCString::data(), QCString::findRev(), insert(), instance(), QCString::isEmpty(), isId(), QCString::left(), QCString::length(), Debug::Plantuml, QCString::prepend(), Debug::print(), PUML_BITMAP, PUML_EPS, PUML_SVG, qPrint(), qstrncmp(), QCString::reserve(), QCString::right(), QCString::setNum(), QCString::str(), and substitute().
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), FlowChart::printUmlTree(), DocbookDocVisitor::startPlantUmlFile(), and LatexDocVisitor::startPlantUmlFile().
Member Data Documentation
m_epsPlantumlContent
ContentMap PlantumlManager::m_epsPlantumlContent private
Definition at line 92 of file plantuml.h.
Referenced by insert(), and run().
m_epsPlantumlFiles
FilesMap PlantumlManager::m_epsPlantumlFiles private
Definition at line 89 of file plantuml.h.
Referenced by insert(), and run().
m_pngPlantumlContent
ContentMap PlantumlManager::m_pngPlantumlContent private
Definition at line 90 of file plantuml.h.
Referenced by insert(), and run().
m_pngPlantumlFiles
FilesMap PlantumlManager::m_pngPlantumlFiles private
Definition at line 87 of file plantuml.h.
Referenced by insert(), and run().
m_svgPlantumlContent
ContentMap PlantumlManager::m_svgPlantumlContent private
Definition at line 91 of file plantuml.h.
Referenced by insert(), and run().
m_svgPlantumlFiles
FilesMap PlantumlManager::m_svgPlantumlFiles private
Definition at line 88 of file plantuml.h.
Referenced by insert(), and run().
The documentation for this class was generated from the following files:
src/plantuml.h
src/plantuml.cpp