Doxygen: DocAutoList Class Reference
DocAutoList Class Reference
Node representing an auto List.
#include <src/docnode.h>
Public Types
enum ListType { Unnumbered =1 , Unchecked =-2 , Checked_x =-3 , Checked_X =-4 }
Public Member Functions
DocAutoList (DocParser *parser, DocNodeVariant *parent, int indent, bool isEnumList, int depth, bool isCheckedList)
bool isEnumList () const
int indent () const
bool isCheckedList () const
int depth () const
Token parse ()
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
int m_indent = 0
bool m_isEnumList = false
bool m_isCheckedList = false
int m_depth = 0
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing an auto List.
Definition at line 550 of file docnode.h.
Member Enumeration Documentation
ListType
enum DocAutoList::ListType
Enumerator
Unnumbered
Unchecked
Checked_x
Checked_X
Definition at line 553 of file docnode.h.
    {
       Unnumbered=1, Unchecked=-2, Checked_x=-3, Checked_X=-4 // positive numbers give the label
    };
Constructor & Destructor Documentation
DocAutoList()
DocAutoList::DocAutoList (DocParser * parser, DocNodeVariant * parent, int indent, bool isEnumList, int depth, bool isCheckedList)
Definition at line 2801 of file docnode.cpp.
                                                       :
      DocCompoundNode(parser,parent), m_indent(indent), m_isEnumList(isEnumList),
      m_isCheckedList(isCheckedList), m_depth(depth)
{
}
References depth(), DocCompoundNode::DocCompoundNode(), indent(), isCheckedList(), isEnumList(), m_depth, m_indent, m_isCheckedList, m_isEnumList, DocNode::parent(), and DocNode::parser().
Member Function Documentation
depth()
int DocAutoList::depth () const inline
Definition at line 563 of file docnode.h.
{ return m_depth; }
References m_depth.
Referenced by DocAutoList(), and HtmlDocVisitor::operator()().
indent()
int DocAutoList::indent () const inline
Definition at line 561 of file docnode.h.
{ return m_indent; }
References m_indent.
Referenced by DocAutoList(), and DocPara::parse().
isCheckedList()
bool DocAutoList::isCheckedList () const inline
Definition at line 562 of file docnode.h.
{ return m_isCheckedList; }
References m_isCheckedList.
Referenced by DocAutoList(), HtmlDocVisitor::operator()(), PerlModDocVisitor::operator()(), and RTFDocVisitor::operator()().
isEnumList()
bool DocAutoList::isEnumList () const inline
Definition at line 560 of file docnode.h.
{ return m_isEnumList; }
References m_isEnumList.
Referenced by DocAutoList(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and DocPara::parse().
parse()
Token DocAutoList::parse ()
Definition at line 2808 of file docnode.cpp.
{
  AUTO_TRACE();
  Token retval = Token::make_RetVal_OK();
  int num=1;
  auto ns = AutoNodeStack(parser(),thisVariant());
  parser()->tokenizer.startAutoList();
          // first item or sub list => create new list
  do
  {
    switch (parser()->context.token->id)
    {
      case -1:
        break;
      case DocAutoList::Unchecked: // unchecked
      case DocAutoList::Checked_x: // checked with x
      case DocAutoList::Checked_X: // checked with X
        num = parser()->context.token->id;
        break;
      default: // explicitly numbered list
        num=parser()->context.token->id;  // override num with real number given
        break;
    }
    children().append<DocAutoListItem>(parser(),thisVariant(),m_indent,num++);
    retval = children().get_last<DocAutoListItem>()->parse();
    //printf("DocAutoList::parse(): retval=0x%x parser()->context.token->indent=%d m_indent=%d "
    //       "m_isEnumList=%d parser()->context.token->isEnumList=%d parser()->context.token->name=%s\n",
    //       retval,parser()->context.token->indent,m_indent,m_isEnumList,parser()->context.token->isEnumList,
    //       qPrint(parser()->context.token->name));
    //printf("num=%d parser()->context.token->id=%d\n",num,parser()->context.token->id);
  }
  while (retval.is(TokenRetval::TK_LISTITEM) &&                // new list item
         m_indent==parser()->context.token->indent &&          // at same indent level
         m_isEnumList==parser()->context.token->isEnumList &&  // of the same kind
         m_isCheckedList==parser()->context.token->isCheckedList &&  // of the same kind
         (parser()->context.token->id==-1 || parser()->context.token->id>=num)  // increasing number (or no number or checked list)
        );
  parser()->tokenizer.endAutoList();
  AUTO_TRACE_EXIT("retval={}",retval.to_string());
  return retval;
}
References DocNodeList::append(), AUTO_TRACE, AUTO_TRACE_EXIT, Checked_X, Checked_x, DocCompoundNode::children(), DocParser::context, DocTokenizer::endAutoList(), DocNodeList::get_last(), TokenInfo::id, Token::is(), m_indent, m_isCheckedList, m_isEnumList, parse(), DocNode::parser(), DocTokenizer::startAutoList(), DocNode::thisVariant(), Token::to_string(), DocParserContext::token, DocParser::tokenizer, and Unchecked.
Referenced by parse().
Member Data Documentation
m_depth
int DocAutoList::m_depth = 0 private
Definition at line 570 of file docnode.h.
Referenced by depth(), and DocAutoList().
m_indent
int DocAutoList::m_indent = 0 private
Definition at line 567 of file docnode.h.
Referenced by DocAutoList(), indent(), and parse().
m_isCheckedList
bool DocAutoList::m_isCheckedList = false private
Definition at line 569 of file docnode.h.
Referenced by DocAutoList(), isCheckedList(), and parse().
m_isEnumList
bool DocAutoList::m_isEnumList = false private
Definition at line 568 of file docnode.h.
Referenced by DocAutoList(), isEnumList(), and parse().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp