Doxygen: src/defargs.l File Reference
defargs.l File Reference
#include <stdint.h>
#include <stdio.h>
#include <assert.h>
#include <ctype.h>
#include "defargs.h"
#include "entry.h"
#include "util.h"
#include "arguments.h"
#include "message.h"
#include "debug.h"
#include "doxygen_lex.h"
#include "defargs.l.h"
Classes
struct defargsYY_state
class KeywordHash
Macros
#define YY_TYPEDEF_YY_SCANNER_T
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1
#define YY_INPUT(buf, result, max_size)
#define LEX_NO_INPUT_FILENAME
#define TOTAL_KEYWORDS 28
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 9
#define MIN_HASH_VALUE 3
#define MAX_HASH_VALUE 48
Typedefs
typedef yyguts_t * yyscan_t
Functions
static const char * stateToString (int state)
static int yyread (yyscan_t yyscanner, char *buf, int max_size)
static bool nameIsActuallyPartOfType (QCString &name)
static const char * getLexerFILE ()
int yylex (yyscan_t yyscanner)
std::unique_ptr< ArgumentList > stringToArgumentList (SrcLangExt lang, const QCString &argsString, QCString *extraTypeChars)
Detailed Description
This scanner is used to convert a string into a list of function or template arguments. Each parsed argument results in a Argument struct, that is put into an ArgumentList in declaration order. Comment blocks for arguments can also be included in the string. The argument string does not contain new-lines (except inside any comment blocks). An Argument consists of the string fields: type,name,default value, and documentation The Argument list as a whole can be pure, constant or volatile.
Examples of input strings are:
*    "(int a,int b) const"
*    "(const char *s="hello world",int=5) = 0"
*    "<class T,class N>"
*    "(char c,const char)"
*
Note: It is not always possible to distinguish between the name and type of an argument. In case of doubt the name is added to the type, and the matchArgumentList in util.cpp is be used to further determine the correct separation.
Definition in file defargs.l.
Macro Definition Documentation
LEX_NO_INPUT_FILENAME
#define LEX_NO_INPUT_FILENAME
Definition at line 117 of file defargs.l.
MAX_HASH_VALUE
#define MAX_HASH_VALUE 48
Definition at line 684 of file defargs.l.
Referenced by KeywordHash::find().
MAX_WORD_LENGTH
#define MAX_WORD_LENGTH 9
Definition at line 682 of file defargs.l.
MIN_HASH_VALUE
#define MIN_HASH_VALUE 3
Definition at line 683 of file defargs.l.
MIN_WORD_LENGTH
#define MIN_WORD_LENGTH 3
Definition at line 681 of file defargs.l.
Referenced by KeywordHash::find().
TOTAL_KEYWORDS
#define TOTAL_KEYWORDS 28
Definition at line 680 of file defargs.l.
YY_INPUT
#define YY_INPUT (buf, result, max_size)
Value:
result=yyread(yyscanner,buf,max_size);
Definition at line 113 of file defargs.l.
YY_NO_INPUT
#define YY_NO_INPUT 1
Definition at line 71 of file defargs.l.
YY_NO_UNISTD_H
#define YY_NO_UNISTD_H 1
Definition at line 72 of file defargs.l.
YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
Definition at line 49 of file defargs.l.
Typedef Documentation
yyscan_t
typedef yyguts_t* yyscan_t
Definition at line 51 of file defargs.l.
Function Documentation
getLexerFILE()
static const char * getLexerFILE () inline static
Definition at line 116 of file defargs.l.
{return __FILE__;}
nameIsActuallyPartOfType()
static bool nameIsActuallyPartOfType (QCString & name) static
Definition at line 802 of file defargs.l.
{
  return KeywordHash::find(name.data(),name.length())!=nullptr;
}
References QCString::data(), KeywordHash::find(), and QCString::length().
stateToString()
static const char * stateToString (int state) static
stringToArgumentList()
std::unique_ptr< ArgumentList > stringToArgumentList (SrcLangExt lang, const QCString & argsString, QCString * extraTypeChars)
Converts an argument string into an ArgumentList.
Parameters
[in] lang language of the current argument list
[in] argsString the list of Arguments.
[out] extraTypeChars point to string to which trailing characters for complex types are written to
Definition at line 814 of file defargs.l.
{
  std::unique_ptr<ArgumentList> al = std::make_unique<ArgumentList>();
  if (argsString.isEmpty()) return al;
  yyscan_t yyscanner;
  defargsYY_state extra(argsString.data(),al,lang);
  defargsYYlex_init_extra(&extra,&yyscanner);
#ifdef FLEX_DEBUG
  defargsYYset_debug(Debug::isFlagSet(Debug::Lex_defargs)?1:0,yyscanner);
#endif
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  DebugLex debugLex(Debug::Lex_defargs, __FILE__, nullptr);
  defargsYYrestart( nullptr, yyscanner );
  BEGIN( Start );
  defargsYYlex(yyscanner);
  if (yyextra->argList->empty())
  {
    yyextra->argList->setNoParameters(TRUE);
  }
  if (extraTypeChars) *extraTypeChars=yyextra->extraTypeChars;
  //printf("stringToArgumentList(%s) result=%s\n",argsString,qPrint(argListToString(*al)));
  defargsYYlex_destroy(yyscanner);
  return al;
}
References QCString::data(), QCString::isEmpty(), Debug::isFlagSet(), Debug::Lex_defargs, and TRUE.
Referenced by addClassToContext(), ClassDefImpl::addMembersToTemplateInstance(), buildDefineList(), anonymous_namespace{tagreader.cpp}::TagFileParser::buildMemberList(), combineDeclarationAndDefinition(), computeTemplateClassRelations(), findMembersWithSpecificName(), findTemplateInstanceRelation(), generateDEFForMember(), getDefsOld(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedSymbolRec(), SymbolResolver::Private::getResolvedTypeRec(), MemberDefImpl::init(), and matchCanonicalTypes().
yylex()
int yylex (yyscan_t yyscanner)
Definition at line 155 of file defargs.l.
                                        { BEGIN(ReadFuncArgType); }
<ReadFuncArgType>{B}*                   {
                                          yyextra->curArgTypeName+=" ";
                                        }
<ReadFuncArgType>"["[^\]]*"]"           {
                                          if (yyextra->curArgTypeName.stripWhiteSpace().isEmpty())
{
                                            yyextra->curArgAttrib=yytext; // for M$-IDL
                                          }
                                          else // array type
{
                                            yyextra->curArgArray+=yytext;
                                          }
                                        }
<ReadFuncArgDef>"'"\\[0-7]{1,3}"'"      { yyextra->curArgDefValue+=yytext; }
<ReadFuncArgDef>"'"\\."'"               { yyextra->curArgDefValue+=yytext; }
<ReadFuncArgDef>"'"."'"                 { yyextra->curArgDefValue+=yytext; }
<ReadFuncArgDef>{RAWBEGIN}              { yyextra->curArgDefValue+=yytext;
                                          QCString text(yytext);
                                          int i=text.find('"');
                                          yyextra->delimiter = yytext+i+1;
                                          yyextra->delimiter=yyextra->delimiter.left(yyextra->delimiter.length()-1);
                                          BEGIN( CopyRawString );
                                        }
<ReadFuncArgDef>\"                      {
                                          yyextra->curArgDefValue+=*yytext;
                                          BEGIN( CopyArgString );
                                        }
<ReadFuncArgType>"("([^:)]+{B}*"::")*{B}*[&*\^]+{Bopt}/{ID} {
                                          // function pointer as argument
                                          yyextra->curArgTypeName+=yytext;
                                          //yyextra->curArgTypeName=yyextra->curArgTypeName.simplifyWhiteSpace();
                                          BEGIN( ReadFuncArgPtr );
                                        }
<ReadFuncArgPtr>{ID}                    {
                                          yyextra->curArgName=yytext;
                                        }
<ReadFuncArgPtr>")"{B}*"("              { // function pointer
                                          yyextra->curArgTypeName+=yytext;
                                          //yyextra->curArgTypeName=yyextra->curArgTypeName.simplifyWhiteSpace();
                                          yyextra->readArgContext = ReadFuncArgType;
                                          yyextra->copyArgValue=&yyextra->curArgTypeName;
                                          yyextra->argRoundCount=0;
                                          BEGIN( CopyArgRound2 );
                                        }
<ReadFuncArgPtr>")"/{B}*"["             { // pointer to fixed size array
                                          yyextra->curArgTypeName+=yytext;
                                          yyextra->curArgTypeName+=yyextra->curArgName;
                                          //yyextra->curArgTypeName=yyextra->curArgTypeName.simplifyWhiteSpace();
                                          BEGIN( ReadFuncArgType );
                                        }
<ReadFuncArgPtr>")"                     { // redundant braces detected / remove them
                                          int i=yyextra->curArgTypeName.findRev('(');
                                          int l=static_cast<int>(yyextra->curArgTypeName.length());
                                          if (i!=-1)
{
                                            yyextra->curArgTypeName=yyextra->curArgTypeName.left(i)+
                                                           yyextra->curArgTypeName.right(l-i-1);
                                          }
                                          yyextra->curArgTypeName+=yyextra->curArgName;
                                          BEGIN( ReadFuncArgType );
                                        }
<ReadFuncArgType>"<="|">="|"->"|">>"|"<<" { // handle operators in defargs
                                          yyextra->curArgTypeName+=yytext;
                                        }
<ReadFuncArgType,ReadFuncArgDef>[({<\[] {
                                          if (YY_START==ReadFuncArgType)
{
                                            yyextra->curArgTypeName+=*yytext;
                                            yyextra->copyArgValue=&yyextra->curArgTypeName;
                                          }
                                          else // YY_START==ReadFuncArgDef
{
                                            yyextra->curArgDefValue+=*yytext;
                                            yyextra->copyArgValue=&yyextra->curArgDefValue;
                                          }
                                          yyextra->readArgContext = YY_START;
                                          if (*yytext=='(')
{
                                            yyextra->argRoundCount=0;
                                            BEGIN( CopyArgRound );
                                          }
                                          else if (*yytext=='[')
{
                                            yyextra->argSquareCount=0;
                                            BEGIN( CopyArgSquare );
                                          }
                                          else if (*yytext=='{')
{
                                            yyextra->argCurlyCount=0;
                                            BEGIN( CopyArgCurly );
                                          }
                                          else // yytext=='<'
{
                                            yyextra->argSharpCount=0;
                                            yyextra->argRoundCount=0;
                                            BEGIN( CopyArgSharp );
                                          }
                                        }
<CopyArgRound,CopyArgRound2>"("         {
                                          yyextra->argRoundCount++;
                                          *yyextra->copyArgValue += *yytext;
                                        }
<CopyArgRound,CopyArgRound2>")"({B}*{ID})* {
                                          *yyextra->copyArgValue += yytext;
                                          if (yyextra->argRoundCount>0)
{
                                            yyextra->argRoundCount--;
                                          }
                                          else
{
                                            if (YY_START==CopyArgRound2)
{
                                              *yyextra->copyArgValue+=" "+yyextra->curArgName;
                                            }
                                            BEGIN( yyextra->readArgContext );
                                          }
                                        }
<CopyArgRound>")"/{B}*                  {
                                          *yyextra->copyArgValue += *yytext;
                                          if (yyextra->argRoundCount>0) yyextra->argRoundCount--;
                                          else BEGIN( yyextra->readArgContext );
                                        }
<CopyArgSquare>"["                      {
                                           yyextra->argSquareCount++;
                                           *yyextra->copyArgValue += *yytext;
                                        }
<CopyArgSquare>"]"({B}*{ID})* {
                                          *yyextra->copyArgValue += yytext;
                                          if (yyextra->argSquareCount>0)
{
                                            yyextra->argRoundCount--;
                                          }
                                          else
{
                                            BEGIN( yyextra->readArgContext );
                                          }
                                        }
<CopyArgSquare>"]"/{B}*                  {
                                          *yyextra->copyArgValue += *yytext;
                                          if (yyextra->argSquareCount>0) yyextra->argSquareCount--;
                                          else BEGIN( yyextra->readArgContext );
                                        }
<CopyArgSharp>"<<"                      {
                                          if (yyextra->argRoundCount>0)
{
                                            // for e.g. < typename A = (i<<3) >
                                            *yyextra->copyArgValue += yytext;
                                          }
                                          else
{
                                            REJECT;
                                          }
                                        }
<CopyArgSharp>">>"                      {
                                          if (yyextra->argRoundCount>0)
{
                                            // for e.g. < typename A = (i>>3) >
                                            *yyextra->copyArgValue += yytext;
                                          }
                                          else
{
                                            REJECT;
                                          }
                                        }
<CopyArgSharp>"<"                       {
                                          // don't count < inside (, e.g. for things like: < typename A=(i<6) >
                                          if (yyextra->argRoundCount==0) yyextra->argSharpCount++;
                                          *yyextra->copyArgValue += *yytext;
                                        }
<CopyArgSharp>">"                       {
                                          *yyextra->copyArgValue += *yytext;
                                          if (yyextra->argRoundCount>0 && yyextra->argSharpCount==0)
{
                                            // don't count > inside )
                                          }
                                          else
{
                                            if (yyextra->argSharpCount>0)
{
                                              yyextra->argSharpCount--;
                                            }
                                            else
{
                                              BEGIN( yyextra->readArgContext );
                                            }
                                          }
                                        }
<CopyArgSharp>"("                       {
                                          yyextra->argRoundCount++;
                                          *yyextra->copyArgValue += *yytext;
                                        }
<CopyArgSharp>")"                       {
                                          yyextra->argRoundCount--;
                                          *yyextra->copyArgValue += *yytext;
                                        }
<CopyArgCurly>"{"                       {
                                          yyextra->argCurlyCount++;
                                          *yyextra->copyArgValue += *yytext;
                                        }
<CopyArgCurly>"}"                       {
                                          *yyextra->copyArgValue += *yytext;
                                          if (yyextra->argCurlyCount>0) yyextra->argCurlyCount--;
                                          else BEGIN( yyextra->readArgContext );
                                        }
<CopyArgString>\\.                      {
                                          yyextra->curArgDefValue+=yytext;
                                        }
<CopyRawString>{RAWEND}                 {
                                          yyextra->curArgDefValue+=yytext;
                                          QCString delimiter(yytext+1);
                                          delimiter=delimiter.left(delimiter.length()-1);
                                          if (delimiter==yyextra->delimiter)
{
                                            BEGIN( ReadFuncArgDef );
                                          }
                                        }
<CopyArgString>\"                       {
                                          yyextra->curArgDefValue+=*yytext;
                                          BEGIN( ReadFuncArgDef );
                                        }
<ReadFuncArgType>"="                    {
                                          BEGIN( ReadFuncArgDef );
                                        }
<ReadFuncArgType,ReadFuncArgDef>[,)>]{B}*({CCS}[*!]|{CPPC}[/!])"<" {
                                          yyextra->lastDocContext=YY_START;
                                          yyextra->lastDocChar=*yytext;
                                          QCString text(yytext);
                                          if (text.find("//")!=-1)
                                            BEGIN( ReadDocLine );
                                          else
                                            BEGIN( ReadDocBlock );
                                        }
<ReadFuncArgType,ReadFuncArgDef>[,)>]   {
                                          if (*yytext==')' && yyextra->curArgTypeName.stripWhiteSpace().isEmpty())
{
                                            yyextra->curArgTypeName+=*yytext;
                                            BEGIN(FuncQual);
                                          }
                                          else
{
                                            yyextra->curArgTypeName=removeRedundantWhiteSpace(yyextra->curArgTypeName);
                                            yyextra->curArgDefValue=yyextra->curArgDefValue.stripWhiteSpace();
                                            //printf("curArgType='%s' curArgDefVal='%s'\n",qPrint(yyextra->curArgTypeName),qPrint(yyextra->curArgDefValue));
                                            int l = static_cast<int>(yyextra->curArgTypeName.length());
                                            if (l>0)
{
                                              int i=l-1;
                                              while (i>=0 && (isspace((uint8_t)yyextra->curArgTypeName.at(i)) || yyextra->curArgTypeName.at(i)=='.')) i--;
                                              while (i>=0 && (isId(yyextra->curArgTypeName.at(i)) || yyextra->curArgTypeName.at(i)=='$')) i--;
                                              Argument a;
                                              a.attrib  = yyextra->curArgAttrib;
                                              a.typeConstraint = yyextra->curTypeConstraint.stripWhiteSpace();
                                              //printf("a->type=%s a->name=%s i=%d l=%d\n",
                                              //        qPrint(a->type),qPrint(a->name),i,l);
                                              a.array.clear();
                                              if (i==l-1 && yyextra->curArgTypeName.at(i)==')') // function argument
{
                                                int bi=yyextra->curArgTypeName.find('(');
                                                int fi=bi-1;
                                                //printf("func arg fi=%d\n",fi);
                                                while (fi>=0 && (isId(yyextra->curArgTypeName.at(fi)) || yyextra->curArgTypeName.at(fi)==':')) fi--;
                                                if (fi>=0)
{
                                                  a.type  = yyextra->curArgTypeName.left(fi+1);
                                                  a.name  = yyextra->curArgTypeName.mid(fi+1,bi-fi-1).stripWhiteSpace();
                                                  a.array = yyextra->curArgTypeName.right(l-bi);
                                                }
                                                else
{
                                                  a.type = yyextra->curArgTypeName;
                                                }
                                              }
                                              else if (i>=0 && yyextra->curArgTypeName.at(i)!=':')
                                              { // type contains a name
                                                a.type = removeRedundantWhiteSpace(yyextra->curArgTypeName.left(i+1)).stripWhiteSpace();
                                                a.name = yyextra->curArgTypeName.right(l-i-1).stripWhiteSpace();
                                                // if the type becomes a type specifier only then we make a mistake
                                                // and need to correct it to avoid seeing a nameless parameter
                                                // "struct A" as a parameter with type "struct" and name "A".
                                                int sv=0;
                                                if      (a.type.startsWith("const "))    sv=6;
                                                else if (a.type.startsWith("volatile ")) sv=9;
                                                if (a.type.mid(sv)=="struct"    ||
                                                    a.type.mid(sv)=="union"     ||
                                                    a.type.mid(sv)=="class"     ||
                                                    a.type.mid(sv)=="typename"  ||
                                                    a.type=="const"             ||
                                                    a.type=="volatile"          ||
                                                    nameIsActuallyPartOfType(a.name)
                                                   )
{
                                                  a.type = a.type + " " + a.name;
                                                  a.name.clear();
                                                }
                                                //printf(" --> a->type='%s' a->name='%s'\n",qPrint(a->type),qPrint(a->name));
                                              }
                                              else // assume only the type was specified, try to determine name later
{
                                                a.type = removeRedundantWhiteSpace(yyextra->curArgTypeName);
                                              }
                                              if (!a.type.isEmpty() && a.type.at(0)=='$') // typeless PHP name?
{
                                                a.name = a.type;
                                                a.type = "";
                                              }
                                              a.array  += removeRedundantWhiteSpace(yyextra->curArgArray);
                                              //printf("array=%s\n",qPrint(a->array));
                                              size_t alen = a.array.length();
                                              if (alen>2 && a.array.at(0)=='(' &&
                                                            a.array.at(alen-1)==')') // fix-up for int *(a[10])
{
                                                i=a.array.find('[')-1;
                                                a.array = a.array.mid(1,alen-2);
                                                if (i>0 && a.name.isEmpty())
{
                                                  a.name  = a.array.left(i).stripWhiteSpace();
                                                  a.array = a.array.mid(i);
                                                }
                                              }
                                              a.defval = yyextra->curArgDefValue;
                                              //printf("a->type=%s a->name=%s a->defval=\"%s\"\n",qPrint(a->type),qPrint(a->name),qPrint(a->defval));
                                              a.docs   = yyextra->curArgDocs.stripWhiteSpace();
                                              //printf("Argument '%s' '%s' adding docs='%s'\n",qPrint(a->type),qPrint(a->name),qPrint(a->docs));
                                              yyextra->argList->push_back(a);
                                            }
                                            yyextra->curArgAttrib.clear();
                                            yyextra->curArgTypeName.clear();
                                            yyextra->curArgDefValue.clear();
                                            yyextra->curArgArray.clear();
                                            yyextra->curArgDocs.clear();
                                            yyextra->curTypeConstraint.clear();
                                            if (*yytext==')')
{
                                              BEGIN(FuncQual);
                                              //printf(">>> end of argument list\n");
                                            }
                                            else
{
                                              BEGIN( ReadFuncArgType );
                                            }
                                          }
                                        }
<ReadFuncArgType,ReadFuncArgPtr>"extends" {
                                           if (yyextra->lang!=SrcLangExt::Java)
{
                                             REJECT;
                                           }
                                           else
{
                                             yyextra->curTypeConstraint.clear();
                                             yyextra->lastExtendsContext=YY_START;
                                             BEGIN(ReadTypeConstraint);
                                           }
                                        }
<ReadFuncArgType,ReadFuncArgPtr>"$"?{ID} {
                                          QCString name(yytext);
                                          if (YY_START==ReadFuncArgType && yyextra->curArgArray=="[]") // Java style array
{
                                            yyextra->curArgTypeName+=" []";
                                            yyextra->curArgArray.clear();
                                          }
                                          //printf("resolveName '%s'->'%s'\n",yytext,qPrint(name));
                                          yyextra->curArgTypeName+=name;
                                        }
<ReadFuncArgType,ReadFuncArgPtr>.       {
                                          yyextra->curArgTypeName+=*yytext;
                                        }
<ReadFuncArgDef,CopyArgString>"<="|"->"|">="|">>"|"<<"  {
                                          yyextra->curArgDefValue+=yytext;
                                        }
<ReadFuncArgDef,CopyArgString,CopyRawString>.           {
                                          yyextra->curArgDefValue+=*yytext;
                                        }
<CopyArgRound,CopyArgRound2,CopyArgSquare,CopyArgSharp,CopyArgCurly>{ID}  {
                                          *yyextra->copyArgValue+=yytext;
                                        }
<CopyArgRound,CopyArgRound2,CopyArgSquare,CopyArgSharp,CopyArgCurly>.  {
                                          *yyextra->copyArgValue += *yytext;
                                        }
<ReadTypeConstraint>[,)>]               {
                                          unput(*yytext);
                                          BEGIN(yyextra->lastExtendsContext);
                                        }
<ReadTypeConstraint>.                   {
                                          yyextra->curTypeConstraint+=yytext;
                                        }
<ReadTypeConstraint>\n                  {
                                          yyextra->curTypeConstraint+=' ';
                                        }
<FuncQual>"const"                       {
                                          yyextra->argList->setConstSpecifier(TRUE);
                                        }
<FuncQual>"volatile"                    {
                                          yyextra->argList->setVolatileSpecifier(TRUE);
                                        }
<FuncQual>"override"                    {
                                        }
<FuncQual>"&"                           {
                                          yyextra->argList->setRefQualifier(RefQualifierType::LValue);
                                        }
<FuncQual>"&&"                          {
                                          yyextra->argList->setRefQualifier(RefQualifierType::RValue);
                                        }
<FuncQual,TrailingReturn>"="{B}*"0"     {
                                          yyextra->argList->setPureSpecifier(TRUE);
                                          BEGIN(FuncQual);
                                        }
<FuncQual>"->"                          { // C++11 trailing return type
                                          yyextra->argList->setTrailingReturnType(QCString(" -> "));
                                          BEGIN(TrailingReturn);
                                        }
<TrailingReturn>{B}/("final"|"override"){B}*  {
                                          unput(*yytext);
                                          BEGIN(FuncQual);
                                        }
<TrailingReturn>.                       {
                                          yyextra->argList->setTrailingReturnType(yyextra->argList->trailingReturnType()+yytext);
                                        }
<TrailingReturn>\n                      {
                                          yyextra->argList->setTrailingReturnType(yyextra->argList->trailingReturnType()+yytext);
                                        }
<FuncQual>")"{B}*"["[^]]*"]"            { // for functions returning a pointer to an array,
                                          // i.e. ")[]" in "int (*f(int))[4]" with argsString="(int))[4]"
                                          yyextra->extraTypeChars=yytext;
                                        }
<ReadDocBlock>[^\*\n]+                  {
                                          yyextra->curArgDocs+=yytext;
                                        }
<ReadDocLine>[^\n]+                     {
                                          yyextra->curArgDocs+=yytext;
                                        }
<ReadDocBlock>{CCE}                     {
                                          if (yyextra->lastDocChar!=0)
                                            unput(yyextra->lastDocChar);
                                          BEGIN(yyextra->lastDocContext);
                                        }
<ReadDocLine>\n                         {
                                          if (yyextra->lastDocChar!=0)
                                            unput(yyextra->lastDocChar);
                                          BEGIN(yyextra->lastDocContext);
                                        }
<ReadDocBlock>\n                        {
                                          yyextra->curArgDocs+=*yytext;
                                        }
<ReadDocBlock>.                         {
                                          yyextra->curArgDocs+=*yytext;
                                        }
<*>({CCS}[*!]|{CPPC}[/!])("<"?)         {
                                          yyextra->lastDocContext=YY_START;
                                          yyextra->lastDocChar=0;
                                          if (yytext[1]=='/')
                                            BEGIN( ReadDocLine );
                                          else
                                            BEGIN( ReadDocBlock );
                                        }
<*>\n
<*>.
%%
yyread()
static int yyread (yyscan_t yyscanner, char * buf, int max_size) static
Definition at line 625 of file defargs.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  int c=0;
  while( c < max_size && yyextra->inputString[yyextra->inputPosition] )
  {
      *buf = yyextra->inputString[yyextra->inputPosition++] ;
      c++; buf++;
  }
  return c;
}