Doxygen: src/debug.cpp File Reference
debug.cpp File Reference
#include <stdarg.h>
#include <algorithm>
#include <stdio.h>
#include <map>
#include <string>
#include <chrono>
#include "debug.h"
#include "message.h"
#include "qcstring.h"
Classes
class Timer
Functions
static char asciiToLower (char in)
static uint64_t labelToEnumValue (const QCString &l)
Variables
static std::map< std::string, Debug::DebugMask > s_labels
static FILE * g_debugFile = stdout
static Timer g_runningTime
Function Documentation
asciiToLower()
static char asciiToLower (char in) static
Definition at line 92 of file debug.cpp.
{
    if (in <= 'Z' && in >= 'A')
        return in - ('Z' - 'z');
    return in;
}
Referenced by convertUTF8ToLower(), and labelToEnumValue().
labelToEnumValue()
static uint64_t labelToEnumValue (const QCString & l) static
Definition at line 98 of file debug.cpp.
{
  std::string s = l.str();
  std::transform(s.begin(),s.end(),s.begin(),asciiToLower);
  auto it = s_labels.find(s);
  return (it!=s_labels.end()) ? it->second : Debug::DebugMask::Quiet;
}
References asciiToLower(), Debug::Quiet, s_labels, and QCString::str().
Referenced by Debug::setFlagStr().
Variable Documentation
g_debugFile
FILE* g_debugFile = stdout static
Definition at line 76 of file debug.cpp.
Referenced by Debug::print(), and Debug::setFlagStr().
g_runningTime
Timer g_runningTime static
Definition at line 197 of file debug.cpp.
Referenced by Debug::elapsedTime(), and Debug::startTimer().
s_labels
std::map< std::string, Debug::DebugMask > s_labels static
Definition at line 29 of file debug.cpp.
{
  { "preprocessor",       Debug::Preprocessor       },
  { "nolineno",           Debug::NoLineNo           },
  { "commentcnv",         Debug::CommentCnv         },
  { "commentscan",        Debug::CommentScan        },
  { "formula",            Debug::Formula            },
  { "printtree",          Debug::PrintTree          },
  { "time",               Debug::Time               },
  { "extcmd",             Debug::ExtCmd             },
  { "markdown",           Debug::Markdown           },
  { "filteroutput",       Debug::FilterOutput       },
  { "plantuml",           Debug::Plantuml           },
  { "fortranfixed2free",  Debug::FortranFixed2Free  },
  { "cite",               Debug::Cite               },
  { "rtf",                Debug::Rtf                },
  { "qhp",                Debug::Qhp                },
  { "tag",                Debug::Tag                },
  { "alias",              Debug::Alias              },
  { "entries",            Debug::Entries            },
  { "sections",           Debug::Sections           },
  { "stderr",             Debug::Stderr             },
  { "layout",             Debug::Layout             },
  { "lex",                Debug::Lex                },
  { "lex:code",           Debug::Lex_code           },
  { "lex:commentcnv",     Debug::Lex_commentcnv     },
  { "lex:commentscan",    Debug::Lex_commentscan    },
  { "lex:configimpl",     Debug::Lex_configimpl     },
  { "lex:constexp",       Debug::Lex_constexp       },
  { "lex:declinfo",       Debug::Lex_declinfo       },
  { "lex:defargs",        Debug::Lex_defargs        },
  { "lex:doctokenizer",   Debug::Lex_doctokenizer   },
  { "lex:fortrancode",    Debug::Lex_fortrancode    },
  { "lex:fortranscanner", Debug::Lex_fortranscanner },
  { "lex:lexcode",        Debug::Lex_lexcode        },
  { "lex:lexscanner",     Debug::Lex_lexscanner     },
  { "lex:pre",            Debug::Lex_pre            },
  { "lex:pycode",         Debug::Lex_pycode         },
  { "lex:pyscanner",      Debug::Lex_pyscanner      },
  { "lex:scanner",        Debug::Lex_scanner        },
  { "lex:sqlcode",        Debug::Lex_sqlcode        },
  { "lex:vhdlcode",       Debug::Lex_vhdlcode       },
  { "lex:xml",            Debug::Lex_xml            },
  { "lex:xmlcode",        Debug::Lex_xmlcode        },
};
Referenced by labelToEnumValue(), and Debug::printFlags().