Doxygen: TranslatorEsperanto Class Reference
TranslatorEsperanto Class Reference
#include <src/translator_eo.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) override methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include "translator.h" or "translator_adapter.h" here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 45 of file translator_eo.h.
Member Function Documentation
getLanguageString()
QCString TranslatorEsperanto::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 85 of file translator_eo.h.
    {
      return "0x409 English (United States)";
    }
idLanguage()
QCString TranslatorEsperanto::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 57 of file translator_eo.h.
    { return "esperanto"; }
latexLanguageSupportCommand()
QCString TranslatorEsperanto::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 74 of file translator_eo.h.
    {
      return "\\usepackage[esperanto]{babel}\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorEsperanto::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1875 of file translator_eo.h.
    { return "Kromaj Hereditaj Membroj"; }
trAll()
QCString TranslatorEsperanto::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1384 of file translator_eo.h.
    {
      return "iuj";
    }
trAndMore()
QCString TranslatorEsperanto::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1853 of file translator_eo.h.
    { return "kaj "+number+" pli..."; }
trAttention()
QCString TranslatorEsperanto::trAttention () inline override virtual
Implements Translator.
Definition at line 964 of file translator_eo.h.
    {
      return "Atentu";
    }
trAuthor()
QCString TranslatorEsperanto::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1257 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "atoro", "j");
    }
References Translator::createNoun().
trBug()
QCString TranslatorEsperanto::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1129 of file translator_eo.h.
    {
      return "Cimo";
    }
trBugList()
QCString TranslatorEsperanto::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1134 of file translator_eo.h.
    {
      return "Cima Listo";
    }
trCallerGraph()
QCString TranslatorEsperanto::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1503 of file translator_eo.h.
    {
      return "Jen la vokdiagramo por tiu i funkcio:";
    }
trCallGraph()
QCString TranslatorEsperanto::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1389 of file translator_eo.h.
    {
      return "Jen la vokdiagramo por tiu i funkcio:";
    }
trCiteReferences()
QCString TranslatorEsperanto::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1829 of file translator_eo.h.
    { return "Bibliografiaj Referencoj"; }
trClass()
QCString TranslatorEsperanto::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1192 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "klaso", "j");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorEsperanto::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 518 of file translator_eo.h.
    {
      return "Heredada diagramo por "+clName+":";
    }
trClassDocumentation()
QCString TranslatorEsperanto::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 399 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstruktura Dokumentado";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klasa Dokumentado";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorEsperanto::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1092 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstrukturoj";
      }
      else
      {
        return "Klasoj";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorEsperanto::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 183 of file translator_eo.h.
    { return "Klasa Hierarkio"; }
trClassHierarchyDescription()
QCString TranslatorEsperanto::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 242 of file translator_eo.h.
    { return "Tiu i heredada listo estas plimalpli, "
             "sed ne tute, ordigita alfabete:";
    }
trClassMethods()
QCString TranslatorEsperanto::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1913 of file translator_eo.h.
    {
      return "Klasaj Metodoj";
    }
trCode()
QCString TranslatorEsperanto::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 864 of file translator_eo.h.
    {
      return "kodo";
    }
trCollaborationDiagram()
QCString TranslatorEsperanto::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 819 of file translator_eo.h.
    {
      return "Kunlaborada diagramo por "+clName+":";
    }
trCompoundIndex()
QCString TranslatorEsperanto::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 372 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstruktura Indekso";
      }
      else
      {
        return "Klasa Indekso";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorEsperanto::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1558 of file translator_eo.h.
    { return "Datumtipa Indekso"; }
trCompoundList()
QCString TranslatorEsperanto::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 187 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstruktoroj";
      }
      else
      {
        return "Klasaro";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorEsperanto::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 257 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Jen datumstrukturoj kun mallongaj priskriboj:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Jen la klasoj kun mallongaj priskriboj:";
      }
      else
      {
        return "Jen la klasoj, strukturoj, kunigoj kaj interfacoj "
               "kun mallongaj priskriboj:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorEsperanto::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1531 of file translator_eo.h.
    { return "Jen la datumtipoj kun mallongaj priskriboj:"; }
trCompoundListFortran()
QCString TranslatorEsperanto::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1523 of file translator_eo.h.
    { return "Datumtipa Listo"; }
trCompoundMembers()
QCString TranslatorEsperanto::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 204 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumkampoj";
      }
      else
      {
        return "Klasaj membroj";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorEsperanto::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 276 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll)
      {
        result+="dokumentitaj ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="strukturaj kaj kunigaj kampoj";
      }
      else
      {
        result+="klasaj membroj";
      }
      result+=" kun ligiloj al ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la struktura/kuniga dokumentado por iu kampo:";
        }
        else
        {
          result+="la klasa dokumentado por iu membro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la strukturoj/kunigoj al kiuj ili apartenas:";
        }
        else
        {
          result+="la klasoj al kiuj ili apartenas:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorEsperanto::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1535 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll)
      {
        result+="dokumentitaj ";
      }
      result+="datumtipaj membroj";
      result+=" kun ligiloj al ";
      if (!extractAll)
      {
         result+="la datumstruktura dokumentado de iu membro";
      }
      else
      {
         result+="la datumtipoj al kiuj ili apartenas:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorEsperanto::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1527 of file translator_eo.h.
    { return "Datumkampoj"; }
trCompoundReference()
QCString TranslatorEsperanto::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 593 of file translator_eo.h.
    {
      QCString result="Referenco de la ";
      if (isTemplate) result+=" ablono de la ";
      switch(compType)
      {
        case ClassDef::Class:      result+="klaso "; break;
        case ClassDef::Struct:     result+="strukturo "; break;
        case ClassDef::Union:      result+="kunigo "; break;
        case ClassDef::Interface:  result+="interfaco "; break;
        case ClassDef::Protocol:   result+="protokolo "; break;
        case ClassDef::Category:   result+="kategorio "; break;
        case ClassDef::Exception:  result+="escepto "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorEsperanto::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1599 of file translator_eo.h.
    {
      QCString result="Referenco de la ";
      if (isTemplate) result+=" ablono de la ";
      switch(compType)
      {
        case ClassDef::Class:      result+="modulo "; break;
        case ClassDef::Struct:     result+="tipo "; break;
        case ClassDef::Union:      result+="kunigo "; break;
        case ClassDef::Interface:  result+="interfaco "; break;
        case ClassDef::Protocol:   result+="protokolo "; break;
        case ClassDef::Category:   result+="kategorio "; break;
        case ClassDef::Exception:  result+="escepto "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorEsperanto::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 494 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstrukturoj";
      }
      else
      {
        return "Klasoj";
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorEsperanto::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 829 of file translator_eo.h.
    {
      return "Konstruila kaj Detruila Dokumentado";
    }
trCopyright()
QCString TranslatorEsperanto::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1833 of file translator_eo.h.
    { return "Kopirajto"; }
trDataTypes()
QCString TranslatorEsperanto::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1582 of file translator_eo.h.
    { return "Datumtipoj"; }
trDate()
QCString TranslatorEsperanto::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 532 of file translator_eo.h.
    { return "Dato"; }
trDateTime()
QCString TranslatorEsperanto::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1774 of file translator_eo.h.
    {
      static const char *days[]   = { "lundo","mardo","merkredo",
                                        "ado","vendredo","sabato",
                                        "dimano" };
      static const char *months[] = { "Januaro", "Februaro", "Marto",
                                        "Aprilo", "Majo", "Junio",
                                        "Julio", "Agusto", "Septembro",
                                        "Oktobro", "Novembro",
                                        "Decembro"
                                    };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s, %d-a de %s %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorEsperanto::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1802 of file translator_eo.h.
    {
      static const char *days_short[]   = { "lu", "ma", "me", "a", "ve", "sa", "di" };
      static const char *days_full[]    = { "lundo", "mardo", "merkredo", "ado", "vendredo", "sabato", "dimano" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorEsperanto::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1818 of file translator_eo.h.
    {
      static const char *dayPeriod[] = { "atm", "ptm" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorEsperanto::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 796 of file translator_eo.h.
    {
      return "Difinita sur la lineo @0 de la dosiero @1.";
    }
trDefinedIn()
QCString TranslatorEsperanto::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 171 of file translator_eo.h.
    { return "difinita en"; }
trDefinedInSourceFile()
QCString TranslatorEsperanto::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 800 of file translator_eo.h.
    {
      return "Difinita en la dosiero @0.";
    }
trDefineDocumentation()
QCString TranslatorEsperanto::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 464 of file translator_eo.h.
    { return "Difina Dokumentado"; }
trDefines()
QCString TranslatorEsperanto::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 428 of file translator_eo.h.
    { return "Difinoj"; }
trDefineValue()
QCString TranslatorEsperanto::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1119 of file translator_eo.h.
    {
      return "Valoro:";
    }
trDeprecated()
QCString TranslatorEsperanto::trDeprecated () inline override virtual
Implements Translator.
Definition at line 809 of file translator_eo.h.
    {
      return "Evitinda";
    }
trDeprecatedList()
QCString TranslatorEsperanto::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1312 of file translator_eo.h.
    {
      return "Evitindaa Listo";
    }
trDetailedDescription()
QCString TranslatorEsperanto::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 100 of file translator_eo.h.
    { return "Detala Priskribo"; }
trDetailLevel()
QCString TranslatorEsperanto::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1845 of file translator_eo.h.
    { return "detala nivelo"; }
trDetails()
QCString TranslatorEsperanto::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 104 of file translator_eo.h.
    { return "Detaloj"; }
trDir()
QCString TranslatorEsperanto::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1479 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "dosierujo", "j");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorEsperanto::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1837 of file translator_eo.h.
    { return QCString("Dosieruja dependa diagramo por ")+name+":"; }
trDirDocumentation()
QCString TranslatorEsperanto::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1461 of file translator_eo.h.
    { return "Dosieruja Dokumentado"; }
trDirectories()
QCString TranslatorEsperanto::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1467 of file translator_eo.h.
    { return "Dosierujoj"; }
trDirIndex()
QCString TranslatorEsperanto::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1455 of file translator_eo.h.
    { return "Dosieruja Hierarkio"; }
trDirReference()
QCString TranslatorEsperanto::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1473 of file translator_eo.h.
    { QCString result=dirName; result+=" Dosieruja Referenco"; return result; }
trDirRelation()
QCString TranslatorEsperanto::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1713 of file translator_eo.h.
    {
      return QCString(name)+" Rilato";
    }
trDocumentation()
QCString TranslatorEsperanto::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 354 of file translator_eo.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentado"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorEsperanto::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 440 of file translator_eo.h.
    { return "Enumeracioj"; }
trEnumerationTypeDocumentation()
QCString TranslatorEsperanto::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 476 of file translator_eo.h.
    { return "Enumeracitipa Dokumentado"; }
trEnumerationValueDocumentation()
QCString TranslatorEsperanto::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1511 of file translator_eo.h.
    { return "Enumeraciila Dokumentado"; }
trEnumerationValues()
QCString TranslatorEsperanto::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 458 of file translator_eo.h.
    { return "Enumeraciilo"; }
trEnumGeneratedFromFiles()
QCString TranslatorEsperanto::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1857 of file translator_eo.h.
    { QCString result = "La dokumentaro por tiu i enum estis generita el la sekva dosiero";
      if (!single) result += "s";
      result+=":";
      return result;
    }
trEnumName()
QCString TranslatorEsperanto::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 163 of file translator_eo.h.
    { return "enum nomo"; }
trEnumReference()
QCString TranslatorEsperanto::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1865 of file translator_eo.h.
    { return QCString(name)+" Enum Referenco"; }
trEnumValue()
QCString TranslatorEsperanto::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 167 of file translator_eo.h.
    { return "enum valoro"; }
trEventDocumentation()
QCString TranslatorEsperanto::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1329 of file translator_eo.h.
    {
      return "Eventa Dokumentado";
    }
trEvents()
QCString TranslatorEsperanto::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1324 of file translator_eo.h.
    {
      return "Eventoj";
    }
trExamples()
QCString TranslatorEsperanto::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 234 of file translator_eo.h.
    { return "Ekzemploj"; }
trExamplesDescription()
QCString TranslatorEsperanto::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 340 of file translator_eo.h.
    { return "Jen listo de iuj la ekzemploj:"; }
trExceptions()
QCString TranslatorEsperanto::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 548 of file translator_eo.h.
    { return "Esceptoj"; }
trExtendsClass()
QCString TranslatorEsperanto::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1905 of file translator_eo.h.
    {
      return "Etendi klason @0.";
    }
trFile()
QCString TranslatorEsperanto::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1201 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "dosiero", "j");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorEsperanto::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 418 of file translator_eo.h.
    { return "Dosiera Dokumentado"; }
trFileIn()
QCString TranslatorEsperanto::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1750 of file translator_eo.h.
    {
      return "Dosiero en "+name;
    }
trFileIndex()
QCString TranslatorEsperanto::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 387 of file translator_eo.h.
    { return "Dosiera Indekso"; }
trFileList()
QCString TranslatorEsperanto::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 200 of file translator_eo.h.
    { return "Dosieraro"; }
trFileListDescription()
QCString TranslatorEsperanto::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 248 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="dosieroj kun mallongaj priskriboj:";
      return result;
    }
trFileMembers()
QCString TranslatorEsperanto::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 217 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Mallokalaoj";
      }
      else
      {
        return "Dosieraj Membroj";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorEsperanto::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 318 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcioj, variabloj, difinoj, enumeracioj kaj tipodifinoj";
      }
      else
      {
        result+="dosieraj membroj";
      }
      result+=" kun ligiloj al ";
      if (extractAll)
        result+="la dosieroj al kiuj ili apartenas:";
      else
        result+="la dokumentado:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorEsperanto::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 615 of file translator_eo.h.
    {
      QCString result=fileName;
      result+=" Dosiera referenco";
      return result;
    }
trFriends()
QCString TranslatorEsperanto::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 575 of file translator_eo.h.
    { return "Amikoj"; }
trFunctionDocumentation()
QCString TranslatorEsperanto::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 482 of file translator_eo.h.
    { return "Funkcia Dokumentado"; }
trFunctions()
QCString TranslatorEsperanto::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 446 of file translator_eo.h.
    { return "Funkcioj"; }
trGeneratedAt()
QCString TranslatorEsperanto::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 509 of file translator_eo.h.
    {
      QCString result="Generita la "+date;
      if (!projName.isEmpty()) result+=" por "+projName;
      result+=" de";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorEsperanto::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 155 of file translator_eo.h.
    { QCString result="Generita atomate de Doxygen";
      if (!s.isEmpty()) result+=" por "+s;
      result+=" el la fontkodo.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorEsperanto::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 552 of file translator_eo.h.
    { return "Generita de"; }
trGeneratedFromFiles()
QCString TranslatorEsperanto::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 752 of file translator_eo.h.
    { // single is true implies a single file
      QCString result="La dokumentado por tiu i ";
      switch(compType)
      {
        case ClassDef::Class:      result+="klaso"; break;
        case ClassDef::Struct:     result+="strukturo"; break;
        case ClassDef::Union:      result+="kunigo"; break;
        case ClassDef::Interface:  result+="interfaco"; break;
        case ClassDef::Protocol:   result+="protokolo"; break;
        case ClassDef::Category:   result+="kategorio"; break;
        case ClassDef::Exception:  result+="escepto"; break;
        default: break;
      }
      result+=" generitas el la ";
      if (single) result+="sekva dosiero:";
      else result+="sekvaj dosieroj:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorEsperanto::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1665 of file translator_eo.h.
    {
      // single is true implies a single file
      QCString result="La dokumentado por tiu i ";
      switch(compType)
      {
        case ClassDef::Class:      result+="modulo"; break;
        case ClassDef::Struct:     result+="tipo"; break;
        case ClassDef::Union:      result+="kunigo"; break;
        case ClassDef::Interface:  result+="interfaco"; break;
        case ClassDef::Protocol:   result+="protokolo"; break;
        case ClassDef::Category:   result+="kategorio"; break;
        case ClassDef::Exception:  result+="escepto"; break;
        default: break;
      }
      result+=" kreiis el la ";
      if (single) result+="sekva dosiero:"; else result+="sekvaj dosieroj:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorEsperanto::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1246 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "mallokalao", "j");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorEsperanto::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1725 of file translator_eo.h.
    {
      return "Malloka Nomspaco";
    }
trGotoDocumentation()
QCString TranslatorEsperanto::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 839 of file translator_eo.h.
    {
      return "Iri al la dokumentado de tiu i dosiero.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorEsperanto::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 872 of file translator_eo.h.
    {
      return "Iri al la grafika klasa hierarkio";
    }
trGotoSourceCode()
QCString TranslatorEsperanto::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 834 of file translator_eo.h.
    {
      return "Iri al la fontkodo de tiu i dosiero.";
    }
trGotoTextualHierarchy()
QCString TranslatorEsperanto::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 876 of file translator_eo.h.
    {
      return "Iri al la teksta klasa hierarkio";
    }
trGraphicalHierarchy()
QCString TranslatorEsperanto::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 868 of file translator_eo.h.
    {
      return "Grafika Klasa Hierarkio";
    }
trGroup()
QCString TranslatorEsperanto::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1219 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "grupo", "j");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorEsperanto::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 366 of file translator_eo.h.
    { return "Hierarkia Indekso"; }
trImplementedFromList()
QCString TranslatorEsperanto::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1280 of file translator_eo.h.
    {
      return "Realigas "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorEsperanto::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1288 of file translator_eo.h.
    {
      return "Realigita en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorEsperanto::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 968 of file translator_eo.h.
    {
      return "Tiu i diagramo montras kiuj dosieroj rekte a malrekte "
             "inkluzivas tiun i dosieron:";
    }
trInclDepGraph()
QCString TranslatorEsperanto::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 824 of file translator_eo.h.
    {
      return "Inkluzivaa dependeca diagramo por "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorEsperanto::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1759 of file translator_eo.h.
    {
      return "Inkluzivas dosieron en "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorEsperanto::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 149 of file translator_eo.h.
    { return ", inkluzive iujn hereditajn membrojn."; }
trInheritedByList()
QCString TranslatorEsperanto::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 686 of file translator_eo.h.
    {
      return "Heredita de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorEsperanto::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1869 of file translator_eo.h.
    { return QCString(members)+" heredita el "+what; }
trInheritsList()
QCString TranslatorEsperanto::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 678 of file translator_eo.h.
    {
      return "Heredas de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorEsperanto::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 859 of file translator_eo.h.
    {
      return "Komenca valoro:";
    }
trInstanceMethods()
QCString TranslatorEsperanto::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1921 of file translator_eo.h.
    {
      return "Aperaj Metodoj";
    }
trInvariant()
QCString TranslatorEsperanto::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 854 of file translator_eo.h.
    {
      return "Malvariao";
    }
trISOLang()
QCString TranslatorEsperanto::trISOLang () inline override virtual
Implements Translator.
Definition at line 79 of file translator_eo.h.
    {
      return "eo";
    }
trLegend()
QCString TranslatorEsperanto::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1052 of file translator_eo.h.
    {
      return "klarigeto";
    }
trLegendDocs()
QCString TranslatorEsperanto::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 990 of file translator_eo.h.
    {
      return
        "Tiu i pao klarigas kiel interpreti la diagramojn generitajn "
        "de doxygen.<p>\n"
        "Konsideru la sekvan ekzemplon:\n"
        "\\code\n"
        "/*! Nevidebla klaso pro trunkado */\n"
        "class Invisible { };\n\n"
        "/*! Trunkita klaso, hereda rilato kaias */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klaso ne dokumentita per komentoj de doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Klaso de kiu heredias per publika heredado */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! ablona klaso */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klaso de kiu heredias per protektita heredado */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klaso de kiu heredias per privata heredado */\n"
        "class PrivateBase { };\n\n"
        "/*! Klaso uzata de la klaso Inherited */\n"
        "class Used { };\n\n"
        "/*! Supra klaso kiu heredas de kelkaj aliaj klasoj */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Tio i liveros la sekvan diagramon:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "La skatoloj de la supra diagramo havas la sekvajn signifojn:\n"
        "<ul>\n"
        "<li>%Plene griza skatolo reprezentas la strukturon a klason "
        "kies diagramo generiis.\n"
        "<li>%Skatolo kun nigra bordero montras dokumentitan strukturon a klason.\n"
        "<li>%Skatolo kun griza bordero montras nedokumentitan strukturon a klason.\n"
        "<li>%Skatolo kun rua bordero montras dokumentitan strukturon a klason por "
        "kiu ne iuj heredadoj/enhavoj montrias. %Diagramo estas trunkota "
        "se i ne adaptias en la donitajn limojn.\n"
        "</ul>\n"
        "La sagoj havas la sekvajn signifojn:\n"
        "<ul>\n"
        "<li>%Malhelblua sago uzatas por montri publika heredado "
        "inter du klasoj.\n"
        "<li>%Malhelverda sago uzatas por protektita heredado.\n"
        "<li>%Malhelrua sago uzatas por privata heredado.\n"
        "<li>%Purpura streka sago uzatas se klaso enhavatas a uzatas "
        "de alia klaso. La sago estas etikedatas kun la variablo(j) "
        "tra kiu la montrita klaso a strukturo estas alirebla.\n"
        "<li>%Flava streka sago montras rilato inter ablona apero kaj "
        "la ablona klaso el kiu i realigitas. La sago etikeditas kun "
        "la parametroj de la ablona apero.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorEsperanto::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 983 of file translator_eo.h.
    {
      return "Diagrama Klarigeto";
    }
trListOfAllMembers()
QCString TranslatorEsperanto::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 137 of file translator_eo.h.
    { return "Listo de iuj membroj"; }
trLoading()
QCString TranslatorEsperanto::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1719 of file translator_eo.h.
    {
      return "arante...";
    }
trMainPage()
QCString TranslatorEsperanto::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 783 of file translator_eo.h.
    { return "efa Pao"; }
trMember()
QCString TranslatorEsperanto::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1237 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "membro", "j");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorEsperanto::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 120 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Kampa Dokumentado";
      }
      else
      {
        return "Dokumentado de la Membraj Datumoj";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorEsperanto::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 112 of file translator_eo.h.
    { return "Dokumentado de la Membraj Enumeracioj"; }
trMemberFunctionDocumentation()
QCString TranslatorEsperanto::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 116 of file translator_eo.h.
    { return "Dokumentado de la Membraj Funkcioj"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorEsperanto::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1519 of file translator_eo.h.
    { return "Dokumentado de Membraj Funkcioj/Subrutinoj"; }
trMemberList()
QCString TranslatorEsperanto::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 141 of file translator_eo.h.
    { return "Membra Listo"; }
trMemberTypedefDocumentation()
QCString TranslatorEsperanto::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 108 of file translator_eo.h.
    { return "Dokumentado de la Membraj Tipodifinoj"; }
trMethodDocumentation()
QCString TranslatorEsperanto::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1928 of file translator_eo.h.
    {
      return "Dokumentaro de la Metodo";
    }
trModule()
QCString TranslatorEsperanto::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1658 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "modulo", "j");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorEsperanto::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 393 of file translator_eo.h.
    { return "Modula Dokumentado"; }
trModuleIndex()
QCString TranslatorEsperanto::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 360 of file translator_eo.h.
    { return "Modula Indekso"; }
trModuleReference()
QCString TranslatorEsperanto::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1620 of file translator_eo.h.
    {
      QCString result=namespaceName;
      result+=" Modula Referenco";
      return result;
    }
trModules()
QCString TranslatorEsperanto::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 179 of file translator_eo.h.
    { return "Moduloj"; }
trModulesDescription()
QCString TranslatorEsperanto::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 348 of file translator_eo.h.
    { return "Jen listo de iuj la moduloj:"; }
trModulesIndex()
QCString TranslatorEsperanto::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1651 of file translator_eo.h.
    { return "Indekso de Moduloj"; }
trModulesList()
QCString TranslatorEsperanto::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1586 of file translator_eo.h.
    { return "Modula Listo"; }
trModulesListDescription()
QCString TranslatorEsperanto::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1590 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="moduloj kun mallongaj priskriboj:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorEsperanto::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1632 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="modulaj membroj kun ligiloj al la ";
      if (extractAll)
      {
        result+="modula dokumentado de iu membro:";
      }
      else
      {
        result+="moduloj al kiuj ili apartenas:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorEsperanto::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1628 of file translator_eo.h.
    { return "Modulaj Membroj"; }
trMonth()
QCString TranslatorEsperanto::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1810 of file translator_eo.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "ag", "sep", "okt", "nov", "dec" };
      static const char *months_full[]  = { "januaro", "februaro", "marto", "aprilo", "majo", "junio", "julio", "agusto", "septembro", "oktobro", "novembro", "decembro" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorEsperanto::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 133 of file translator_eo.h.
    { return "Pli..."; }
trNamespace()
QCString TranslatorEsperanto::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "nomspaco", "j");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorEsperanto::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 732 of file translator_eo.h.
    { return "Nomspaca Dokumentado"; }
trNamespaceIndex()
QCString TranslatorEsperanto::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 726 of file translator_eo.h.
    { return "Nomspaca Indekso"; }
trNamespaceList()
QCString TranslatorEsperanto::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 560 of file translator_eo.h.
    { return "Nomspacaro"; }
trNamespaceListDescription()
QCString TranslatorEsperanto::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 564 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="nomspacoj kun mallongaj priskriboj:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorEsperanto::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 712 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="nomspacaj membroj kun ligiloj al ";
      if (extractAll)
        result+="la nomspaca dokumentado de iu membro:";
      else
        result+="la nomspacoj al kiuj ili apartenas:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorEsperanto::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 708 of file translator_eo.h.
    { return "Nomspacaj Membroj"; }
trNamespaceReference()
QCString TranslatorEsperanto::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 623 of file translator_eo.h.
    {
      QCString result=namespaceName;
      result+=" Nomspaca referenco";
      return result;
    }
trNamespaces()
QCString TranslatorEsperanto::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 742 of file translator_eo.h.
    { return "Nomspacoj"; }
trNoMatches()
QCString TranslatorEsperanto::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1737 of file translator_eo.h.
    {
      return "Nenia kongruo";
    }
trNote()
QCString TranslatorEsperanto::trNote () inline override virtual
Implements Translator.
Definition at line 889 of file translator_eo.h.
    {
      return "Noto";
    }
trOverloadText()
QCString TranslatorEsperanto::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1491 of file translator_eo.h.
    {
       return "Tiu i estas superarita membra funkcio, "
              "donita por faciligo. i nur malsamas de la supra "
              "funkcio nur pro la argumento(j) kiujn ili akceptas.";
    }
trPackage()
QCString TranslatorEsperanto::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1104 of file translator_eo.h.
    {
      return "Pakao "+name;
    }
trPackageAttribs()
QCString TranslatorEsperanto::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1365 of file translator_eo.h.
    {
      return "Pakaaj Atributoj";
    }
trPackageFunctions()
QCString TranslatorEsperanto::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1347 of file translator_eo.h.
    {
      return "Pakaaj Funkcioj";
    }
trPackageListDescription()
QCString TranslatorEsperanto::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1109 of file translator_eo.h.
    {
      return "Jen listo de pakaoj kun mallongaj priskriboj (se ekzistas):";
    }
trPackageMembers()
QCString TranslatorEsperanto::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1351 of file translator_eo.h.
    {
      return "Pakaaj Membroj";
    }
trPackages()
QCString TranslatorEsperanto::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1114 of file translator_eo.h.
    {
      return "Pakaoj";
    }
trPackageTypes()
QCString TranslatorEsperanto::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1340 of file translator_eo.h.
    {
      return "Pakaaj Tipoj";
    }
trPage()
QCString TranslatorEsperanto::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1228 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "pao", "j");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorEsperanto::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 789 of file translator_eo.h.
    { return "p."; }
trPageIndex()
QCString TranslatorEsperanto::trPageIndex () inline override virtual
Implements Translator.
Definition at line 880 of file translator_eo.h.
    {
      return "Paa Indekso";
    }
trPanelSynchronisationTooltip()
QCString TranslatorEsperanto::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1886 of file translator_eo.h.
    {
      QCString opt = enable ? "aktivigi" : "malaktivigi";
      return "klaku por "+opt+" panelan sinkronigon";
    }
trParameters()
QCString TranslatorEsperanto::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 544 of file translator_eo.h.
    { return "Parametroj"; }
trPostcondition()
QCString TranslatorEsperanto::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 849 of file translator_eo.h.
    {
      return "Postkondio";
    }
trPrecondition()
QCString TranslatorEsperanto::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 844 of file translator_eo.h.
    {
      return "Antakondio";
    }
trPrivateAttribs()
QCString TranslatorEsperanto::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 928 of file translator_eo.h.
    {
      return "Privataj Atributoj";
    }
trPrivateMembers()
QCString TranslatorEsperanto::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 644 of file translator_eo.h.
    { return "Privataj Membraj Funkcioj"; }
trPrivateSlots()
QCString TranslatorEsperanto::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 646 of file translator_eo.h.
    { return "Privataj Ingoj"; }
trPrivateTypes()
QCString TranslatorEsperanto::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 924 of file translator_eo.h.
    {
      return "Privataj Tipoj";
    }
trProperties()
QCString TranslatorEsperanto::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1077 of file translator_eo.h.
    {
      return "Atributoj";
    }
trPropertyDocumentation()
QCString TranslatorEsperanto::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1082 of file translator_eo.h.
    {
      return "Atributa Dokumentado";
    }
trProtectedAttribs()
QCString TranslatorEsperanto::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 916 of file translator_eo.h.
    {
      return "Protektitaj Atributoj";
    }
trProtectedMembers()
QCString TranslatorEsperanto::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 638 of file translator_eo.h.
    { return "Protektitaj Membraj Funkcioj"; }
trProtectedSlots()
QCString TranslatorEsperanto::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 640 of file translator_eo.h.
    { return "Protektitaj Ingoj"; }
trProtectedTypes()
QCString TranslatorEsperanto::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 912 of file translator_eo.h.
    {
      return "Protektitaj Tipoj";
    }
trProvidedByCategory()
QCString TranslatorEsperanto::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1896 of file translator_eo.h.
    {
      return "Provizita de kategorio @0.";
    }
trPublicAttribs()
QCString TranslatorEsperanto::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 897 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumkampoj";
      }
      else
      {
        return "Publikaj Atributoj";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorEsperanto::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 630 of file translator_eo.h.
    { return "Publikaj Membraj Funkcioj"; }
trPublicSlots()
QCString TranslatorEsperanto::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 632 of file translator_eo.h.
    { return "Pubikaj Ingoj"; }
trPublicTypes()
QCString TranslatorEsperanto::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 893 of file translator_eo.h.
    {
      return "Publikaj Tipoj";
    }
trReferencedBy()
QCString TranslatorEsperanto::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 956 of file translator_eo.h.
    {
      return "Referencita de";
    }
trReferenceManual()
QCString TranslatorEsperanto::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 422 of file translator_eo.h.
    { return "Referenca Manlibro"; }
trReferences()
QCString TranslatorEsperanto::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1268 of file translator_eo.h.
    {
      return "Referencoj";
    }
trReimplementedFromList()
QCString TranslatorEsperanto::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 694 of file translator_eo.h.
    {
      return "Rerealigita el "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorEsperanto::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 702 of file translator_eo.h.
    {
      return "Rerealigita en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorEsperanto::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 585 of file translator_eo.h.
    { return "Dokumentado pri amikoj kaj rilatitaj funkcioj"; }
trRelatedFunctions()
QCString TranslatorEsperanto::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 92 of file translator_eo.h.
    { return "Rilataj Funkcioj"; }
trRelatedPages()
QCString TranslatorEsperanto::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 230 of file translator_eo.h.
    { return "Rilataj Paoj"; }
trRelatedPagesDescription()
QCString TranslatorEsperanto::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 344 of file translator_eo.h.
    { return "Jen listo de iuj rilataj dokumentadaj paoj:"; }
trRelatedSubscript()
QCString TranslatorEsperanto::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 96 of file translator_eo.h.
    { return "(Atentu ke tiuj i ne estas membraj funkcioj.)"; }
trRemarks()
QCString TranslatorEsperanto::trRemarks () inline override virtual
Implements Translator.
Definition at line 960 of file translator_eo.h.
    {
      return "Rimarkoj";
    }
trReturns()
QCString TranslatorEsperanto::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 536 of file translator_eo.h.
    { return "Liveras"; }
trReturnValues()
QCString TranslatorEsperanto::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 778 of file translator_eo.h.
    { return "Liveraoj"; }
trRTFansicp()
QCString TranslatorEsperanto::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1168 of file translator_eo.h.
    {
      return "";
    }
trRTFCharSet()
QCString TranslatorEsperanto::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1177 of file translator_eo.h.
    {
      return "1";
    }
trRTFGeneralIndex()
QCString TranslatorEsperanto::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1183 of file translator_eo.h.
    {
      return "Indekso";
    }
trRTFTableOfContents()
QCString TranslatorEsperanto::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1300 of file translator_eo.h.
    {
      return "Enhava Tabelo";
    }
trSearch()
QCString TranslatorEsperanto::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 238 of file translator_eo.h.
    { return "Seri"; }
trSearching()
QCString TranslatorEsperanto::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1731 of file translator_eo.h.
    {
      return "Serante...";
    }
trSearchMatches()
QCString TranslatorEsperanto::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1432 of file translator_eo.h.
    {
      return "Kongruoj:";
    }
trSearchResults()
QCString TranslatorEsperanto::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1413 of file translator_eo.h.
    {
      if (numDocuments==0)
      {
        return "Pardonu, nenio dokumento kongruas vian peton.";
      }
      else if (numDocuments==1)
      {
        return "Trafita <b>unu</b> dokumenton kongruantan vian peton.";
      }
      else
      {
        return "Trafitaj <b>$num</b> dokumentojn kongruantajn vian peton. "
               "Montrios plej bonaj kongruoj unue.";
      }
    }
trSearchResultsTitle()
QCString TranslatorEsperanto::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1401 of file translator_eo.h.
    {
      return "Seraj Rezultoj";
    }
trSeeAlso()
QCString TranslatorEsperanto::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 540 of file translator_eo.h.
    { return "Vido anka"; }
trSignals()
QCString TranslatorEsperanto::trSignals () inline override virtual
Implements Translator.
Definition at line 634 of file translator_eo.h.
    { return "Signaloj"; }
trSince()
QCString TranslatorEsperanto::trSince () inline override virtual
Implements Translator.
Definition at line 973 of file translator_eo.h.
    {
      return "De";
    }
trSourceFile()
QCString TranslatorEsperanto::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1443 of file translator_eo.h.
    {
      return filename + " Fonta Dosiero";
    }
trStaticPackageAttribs()
QCString TranslatorEsperanto::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1372 of file translator_eo.h.
    {
      return "Statikaj Pakaaj Atributoj";
    }
trStaticPackageFunctions()
QCString TranslatorEsperanto::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1358 of file translator_eo.h.
    {
      return "Statikaj Pakaaj Funkcioj";
    }
trStaticPrivateAttribs()
QCString TranslatorEsperanto::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 932 of file translator_eo.h.
    {
      return "Statikaj Privataj Atributoj";
    }
trStaticPrivateMembers()
QCString TranslatorEsperanto::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 648 of file translator_eo.h.
    { return "Statikaj Privataj Membraj Funkcioj"; }
trStaticProtectedAttribs()
QCString TranslatorEsperanto::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 920 of file translator_eo.h.
    {
      return "Statikaj Protektitaj Atributoj";
    }
trStaticProtectedMembers()
QCString TranslatorEsperanto::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 642 of file translator_eo.h.
    { return "Statikaj Protektitaj Membraj Funkcioj"; }
trStaticPublicAttribs()
QCString TranslatorEsperanto::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 908 of file translator_eo.h.
    {
      return "Statikaj Publikaj Atributoj";
    }
trStaticPublicMembers()
QCString TranslatorEsperanto::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 636 of file translator_eo.h.
    { return "Statikaj Publikaj Membraj Funkcioj"; }
trSubprogram()
QCString TranslatorEsperanto::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1697 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "subprogramo", "j");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorEsperanto::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1576 of file translator_eo.h.
    { return "Funkcia/Subrutina Dokumentado"; }
trSubprograms()
QCString TranslatorEsperanto::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1570 of file translator_eo.h.
    { return "Funkcioj/Subrutinoj"; }
trTemplateParameters()
QCString TranslatorEsperanto::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1849 of file translator_eo.h.
    { return "Parametroj de ablonoj"; }
trTest()
QCString TranslatorEsperanto::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1062 of file translator_eo.h.
    {
      return "Testo";
    }
trTestList()
QCString TranslatorEsperanto::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1067 of file translator_eo.h.
    {
      return "Testa Listo";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorEsperanto::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 145 of file translator_eo.h.
    { return "Tiu i estas la kompleta membraro de"; }
trTodo()
QCString TranslatorEsperanto::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 942 of file translator_eo.h.
    {
      return "Farendao";
    }
trTodoList()
QCString TranslatorEsperanto::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 947 of file translator_eo.h.
    {
      return "Farendaaro";
    }
trType()
QCString TranslatorEsperanto::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1689 of file translator_eo.h.
    {
      return createNoun(first_capital, singular, "tipo", "j");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorEsperanto::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1703 of file translator_eo.h.
    {
      return "Tipaj Limigoj";
    }
trTypedefDocumentation()
QCString TranslatorEsperanto::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 470 of file translator_eo.h.
    { return "Tipdifina Dokumentado"; }
trTypedefs()
QCString TranslatorEsperanto::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 434 of file translator_eo.h.
    { return "Tipdifinoj"; }
trTypeDocumentation()
QCString TranslatorEsperanto::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1564 of file translator_eo.h.
    { return "Datumtipa Dokumentado"; }
trVariableDocumentation()
QCString TranslatorEsperanto::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 488 of file translator_eo.h.
    { return "Variabla Dokumentado"; }
trVariables()
QCString TranslatorEsperanto::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 452 of file translator_eo.h.
    { return "Variabloj"; }
trVersion()
QCString TranslatorEsperanto::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 528 of file translator_eo.h.
    { return "Versio"; }
trWarning()
QCString TranslatorEsperanto::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 524 of file translator_eo.h.
    { return "Averto"; }
trWriteList()
QCString TranslatorEsperanto::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 654 of file translator_eo.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=", kaj ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_eo.h