Doxygen: src/dotnode.h File Reference
dotnode.h File Reference
#include <vector>
#include <map>
#include <deque>
#include <iostream>
#include "types.h"
#include "dotgraph.h"
Classes
class EdgeInfo
Attributes of an edge of a dot graph.
class DotNode
A node in a dot graph.
class DotNodeMap
class DotNodeDeque
Typedefs
using DotNodeRefVector = std::vector<DotNode*>
using EdgeInfoVector = std::vector<EdgeInfo>
Functions
QCString escapeTooltip (const QCString &tooltip)
Typedef Documentation
DotNodeRefVector
using DotNodeRefVector = std::vector<DotNode*>
Definition at line 63 of file dotnode.h.
EdgeInfoVector
using EdgeInfoVector = std::vector<EdgeInfo>
Definition at line 64 of file dotnode.h.
Function Documentation
escapeTooltip()
QCString escapeTooltip (const QCString & tooltip)
Definition at line 99 of file dotnode.cpp.
{
  if (tooltip.isEmpty()) return tooltip;
  QCString result;
  const char *p=tooltip.data();
  char c = 0;
  while ((c=*p++))
  {
    switch(c)
    {
    case '"': result+="\\\""; break;
    case '\\': result+="\\\\"; break;
    default: result+=c; break;
    }
  }
  return result;
}
References QCString::data(), and QCString::isEmpty().
Referenced by common_attributes(), and DotNode::writeBox().