Doxygen: anonymous_namespace{tagreader.cpp}::TagCompoundVariant Class Reference
anonymous_namespace{tagreader.cpp}::TagCompoundVariant Class Reference
Variant class that holds a unique pointer to one of the specific container types.
Public Types
enum class Type : uint8_t {
Uninitialized = 0 , Class = 1 , Concept = 2 , Namespace = 3 ,
Package = 4 , File = 5 , Group = 6 , Page = 7 ,
Dir = 8 , Module = 9
}
using VariantT
Public Member Functions
TagCompoundVariant ()
TagCompoundVariant (VariantT &&v)
TagCompoundVariant (const TagCompoundVariant &)=delete
TagCompoundVariant & operator= (const TagCompoundVariant &)=delete
TagCompoundVariant (TagCompoundVariant &&)=default
TagCompoundVariant & operator= (TagCompoundVariant &&)=default
~TagCompoundVariant ()=default
template<class R >
R * get ()
Generic non-const getter.
template<class R >
const R * get () const
Generic const getter.
TagCompoundInfo * getCompoundInfo ()
Convenience method to get the shared compound info.
Type type () const
convenience const and non-const getters for each variant component
TagClassInfo * getClassInfo ()
const TagClassInfo * getClassInfo () const
TagConceptInfo * getConceptInfo ()
const TagConceptInfo * getConceptInfo () const
TagNamespaceInfo * getNamespaceInfo ()
const TagNamespaceInfo * getNamespaceInfo () const
TagPackageInfo * getPackageInfo ()
const TagPackageInfo * getPackageInfo () const
TagFileInfo * getFileInfo ()
const TagFileInfo * getFileInfo () const
TagGroupInfo * getGroupInfo ()
const TagGroupInfo * getGroupInfo () const
TagPageInfo * getPageInfo ()
const TagPageInfo * getPageInfo () const
TagDirInfo * getDirInfo ()
const TagDirInfo * getDirInfo () const
TagModuleInfo * getModuleInfo ()
const TagModuleInfo * getModuleInfo () const
Static Public Member Functions
template<class R , typename... Args>
static TagCompoundVariant make (Args &&... args)
Generic factory method to create a variant holding a unique pointer to a given compound type.
Private Attributes
VariantT m_variant
Detailed Description
Variant class that holds a unique pointer to one of the specific container types.
Definition at line 213 of file tagreader.cpp.
Member Typedef Documentation
VariantT
using anonymous_namespace{tagreader.cpp}::TagCompoundVariant::VariantT
Initial value:
 std::variant< std::monostate,
                                   TagClassInfoPtr,
                                   TagConceptInfoPtr,
                                   TagNamespaceInfoPtr,
                                   TagPackageInfoPtr,
                                   TagFileInfoPtr,
                                   TagGroupInfoPtr,
                                   TagPageInfoPtr,
                                   TagDirInfoPtr,
                                   TagModuleInfoPtr>
Definition at line 216 of file tagreader.cpp.
Member Enumeration Documentation
Type
enum class anonymous_namespace{tagreader.cpp}::TagCompoundVariant::Type : uint8_t strong
Enumerator
Uninitialized
Class
Concept
Namespace
Package
File
Group
Page
Dir
Module
Definition at line 227 of file tagreader.cpp.
    {
      Uninitialized = 0,
      Class         = 1,
      Concept       = 2,
      Namespace     = 3,
      Package       = 4,
      File          = 5,
      Group         = 6,
      Page          = 7,
      Dir           = 8,
      Module        = 9
    };
Constructor & Destructor Documentation
TagCompoundVariant() [1/4]
anonymous_namespace{tagreader.cpp}::TagCompoundVariant::TagCompoundVariant () inline
Definition at line 241 of file tagreader.cpp.
{}
Referenced by make(), operator=(), operator=(), TagCompoundVariant(), and TagCompoundVariant().
TagCompoundVariant() [2/4]
anonymous_namespace{tagreader.cpp}::TagCompoundVariant::TagCompoundVariant (VariantT && v) inline explicit
Definition at line 242 of file tagreader.cpp.
: m_variant(std::move(v)) {}
References m_variant.
TagCompoundVariant() [3/4]
anonymous_namespace{tagreader.cpp}::TagCompoundVariant::TagCompoundVariant (const TagCompoundVariant &) delete
References TagCompoundVariant().
TagCompoundVariant() [4/4]
anonymous_namespace{tagreader.cpp}::TagCompoundVariant::TagCompoundVariant (TagCompoundVariant &&) default
References TagCompoundVariant().
~TagCompoundVariant()
anonymous_namespace{tagreader.cpp}::TagCompoundVariant::~TagCompoundVariant () default
Member Function Documentation
get() [1/2]
template<class R > R * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::get () inline
Generic non-const getter.
Definition at line 251 of file tagreader.cpp.
    {
      std::unique_ptr<R> *p = std::get_if<std::unique_ptr<R>>(&m_variant);
      return p ? p->get() : nullptr;
    }
References m_variant.
Referenced by getClassInfo(), getClassInfo(), getConceptInfo(), getConceptInfo(), getDirInfo(), getDirInfo(), getFileInfo(), getFileInfo(), getGroupInfo(), getGroupInfo(), getModuleInfo(), getModuleInfo(), getNamespaceInfo(), getNamespaceInfo(), getPackageInfo(), getPackageInfo(), getPageInfo(), and getPageInfo().
get() [2/2]
template<class R > const R * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::get () const inline
Generic const getter.
Definition at line 258 of file tagreader.cpp.
    {
      const std::unique_ptr<R> *p = std::get_if<std::unique_ptr<R>>(&m_variant);
      return p ? p->get() : nullptr;
    }
References m_variant.
getClassInfo() [1/2]
TagClassInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getClassInfo () inline
Definition at line 274 of file tagreader.cpp.
{ return get<TagClassInfo    >(); }
References get().
Referenced by getCompoundInfo().
getClassInfo() [2/2]
const TagClassInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getClassInfo () const inline
Definition at line 275 of file tagreader.cpp.
{ return get<TagClassInfo    >(); }
References get().
getCompoundInfo()
TagCompoundInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getCompoundInfo () inline
Convenience method to get the shared compound info.
Definition at line 295 of file tagreader.cpp.
    {
      switch(type())
      {
        case Type::Uninitialized: return nullptr;
        case Type::Class:         return getClassInfo();
        case Type::Concept:       return getConceptInfo();
        case Type::Namespace:     return getNamespaceInfo();
        case Type::Package:       return getPackageInfo();
        case Type::File:          return getFileInfo();
        case Type::Group:         return getGroupInfo();
        case Type::Page:          return getPageInfo();
        case Type::Dir:           return getDirInfo();
        case Type::Module:        return getModuleInfo();
      }
      return nullptr;
    }
References Class, Concept, Dir, File, getClassInfo(), getConceptInfo(), getDirInfo(), getFileInfo(), getGroupInfo(), getModuleInfo(), getNamespaceInfo(), getPackageInfo(), getPageInfo(), Group, Module, Namespace, Package, Page, type(), and Uninitialized.
getConceptInfo() [1/2]
TagConceptInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getConceptInfo () inline
Definition at line 276 of file tagreader.cpp.
{ return get<TagConceptInfo  >(); }
References get().
Referenced by getCompoundInfo().
getConceptInfo() [2/2]
const TagConceptInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getConceptInfo () const inline
Definition at line 277 of file tagreader.cpp.
{ return get<TagConceptInfo  >(); }
References get().
getDirInfo() [1/2]
TagDirInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getDirInfo () inline
Definition at line 288 of file tagreader.cpp.
{ return get<TagDirInfo      >(); }
References get().
Referenced by getCompoundInfo().
getDirInfo() [2/2]
const TagDirInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getDirInfo () const inline
Definition at line 289 of file tagreader.cpp.
{ return get<TagDirInfo      >(); }
References get().
getFileInfo() [1/2]
TagFileInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getFileInfo () inline
Definition at line 282 of file tagreader.cpp.
{ return get<TagFileInfo     >(); }
References get().
Referenced by getCompoundInfo().
getFileInfo() [2/2]
const TagFileInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getFileInfo () const inline
Definition at line 283 of file tagreader.cpp.
{ return get<TagFileInfo     >(); }
References get().
getGroupInfo() [1/2]
TagGroupInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getGroupInfo () inline
Definition at line 284 of file tagreader.cpp.
{ return get<TagGroupInfo    >(); }
References get().
Referenced by getCompoundInfo().
getGroupInfo() [2/2]
const TagGroupInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getGroupInfo () const inline
Definition at line 285 of file tagreader.cpp.
{ return get<TagGroupInfo    >(); }
References get().
getModuleInfo() [1/2]
TagModuleInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getModuleInfo () inline
Definition at line 290 of file tagreader.cpp.
{ return get<TagModuleInfo   >(); }
References get().
Referenced by getCompoundInfo().
getModuleInfo() [2/2]
const TagModuleInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getModuleInfo () const inline
Definition at line 291 of file tagreader.cpp.
{ return get<TagModuleInfo   >(); }
References get().
getNamespaceInfo() [1/2]
TagNamespaceInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getNamespaceInfo () inline
Definition at line 278 of file tagreader.cpp.
{ return get<TagNamespaceInfo>(); }
References get().
Referenced by getCompoundInfo().
getNamespaceInfo() [2/2]
const TagNamespaceInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getNamespaceInfo () const inline
Definition at line 279 of file tagreader.cpp.
{ return get<TagNamespaceInfo>(); }
References get().
getPackageInfo() [1/2]
TagPackageInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getPackageInfo () inline
Definition at line 280 of file tagreader.cpp.
{ return get<TagPackageInfo  >(); }
References get().
Referenced by getCompoundInfo().
getPackageInfo() [2/2]
const TagPackageInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getPackageInfo () const inline
Definition at line 281 of file tagreader.cpp.
{ return get<TagPackageInfo  >(); }
References get().
getPageInfo() [1/2]
TagPageInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getPageInfo () inline
Definition at line 286 of file tagreader.cpp.
{ return get<TagPageInfo     >(); }
References get().
Referenced by getCompoundInfo().
getPageInfo() [2/2]
const TagPageInfo * anonymous_namespace{tagreader.cpp}::TagCompoundVariant::getPageInfo () const inline
Definition at line 287 of file tagreader.cpp.
{ return get<TagPageInfo     >(); }
References get().
make()
template<class R , typename... Args> static TagCompoundVariant anonymous_namespace{tagreader.cpp}::TagCompoundVariant::make (Args &&... args) inline static
Generic factory method to create a variant holding a unique pointer to a given compound type.
Definition at line 266 of file tagreader.cpp.
    {
      return TagCompoundVariant(VariantT(std::make_unique<R>(std::forward<Args>(args)...)));
    }
References TagCompoundVariant().
operator=() [1/2]
TagCompoundVariant & anonymous_namespace{tagreader.cpp}::TagCompoundVariant::operator= (const TagCompoundVariant &) delete
References TagCompoundVariant().
operator=() [2/2]
TagCompoundVariant & anonymous_namespace{tagreader.cpp}::TagCompoundVariant::operator= (TagCompoundVariant &&) default
References TagCompoundVariant().
type()
Type anonymous_namespace{tagreader.cpp}::TagCompoundVariant::type () const inline
Definition at line 312 of file tagreader.cpp.
    {
      return static_cast<Type>(m_variant.index());
    }
References m_variant.
Referenced by getCompoundInfo().
Member Data Documentation
m_variant
VariantT anonymous_namespace{tagreader.cpp}::TagCompoundVariant::m_variant private
Definition at line 318 of file tagreader.cpp.
Referenced by get(), get(), TagCompoundVariant(), and type().
The documentation for this class was generated from the following file:
src/tagreader.cpp