Doxygen: src/defargs.h File Reference
defargs.h File Reference
#include "types.h"
#include <memory>
Functions
std::unique_ptr< ArgumentList > stringToArgumentList (SrcLangExt lang, const QCString &argsString, QCString *extraTypeChars=nullptr)
Function Documentation
stringToArgumentList()
std::unique_ptr< ArgumentList > stringToArgumentList (SrcLangExt lang, const QCString & argsString, QCString * extraTypeChars)
Converts an argument string into an ArgumentList.
Parameters
[in] lang language of the current argument list
[in] argsString the list of Arguments.
[out] extraTypeChars point to string to which trailing characters for complex types are written to
Definition at line 814 of file defargs.l.
{
  std::unique_ptr<ArgumentList> al = std::make_unique<ArgumentList>();
  if (argsString.isEmpty()) return al;
  yyscan_t yyscanner;
  defargsYY_state extra(argsString.data(),al,lang);
  defargsYYlex_init_extra(&extra,&yyscanner);
#ifdef FLEX_DEBUG
  defargsYYset_debug(Debug::isFlagSet(Debug::Lex_defargs)?1:0,yyscanner);
#endif
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  DebugLex debugLex(Debug::Lex_defargs, __FILE__, nullptr);
  defargsYYrestart( nullptr, yyscanner );
  BEGIN( Start );
  defargsYYlex(yyscanner);
  if (yyextra->argList->empty())
  {
    yyextra->argList->setNoParameters(TRUE);
  }
  if (extraTypeChars) *extraTypeChars=yyextra->extraTypeChars;
  //printf("stringToArgumentList(%s) result=%s\n",argsString,qPrint(argListToString(*al)));
  defargsYYlex_destroy(yyscanner);
  return al;
}
References QCString::data(), QCString::isEmpty(), Debug::isFlagSet(), Debug::Lex_defargs, and TRUE.
Referenced by addClassToContext(), ClassDefImpl::addMembersToTemplateInstance(), buildDefineList(), anonymous_namespace{tagreader.cpp}::TagFileParser::buildMemberList(), combineDeclarationAndDefinition(), computeTemplateClassRelations(), findMembersWithSpecificName(), findTemplateInstanceRelation(), generateDEFForMember(), getDefsOld(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedSymbolRec(), SymbolResolver::Private::getResolvedTypeRec(), MemberDefImpl::init(), and matchCanonicalTypes().