Doxygen: /home/runner/work/doxygen/doxygen/src/dirdef.h File Reference
dirdef.h File Reference
#include <vector>
#include <map>
#include "qcstring.h"
#include "linkedmap.h"
#include "definition.h"
Classes
class FilePair
Class representing a pair of FileDef objects.
class FilePairLinkedMap
A linked map of file pairs.
class UsedDir
Usage information of a directory.
class DirDef
A model of a directory symbol.
class DirDef::UsedDirLinkedMap
class DirRelation
A usage relation between two directories.
class DirLinkedMap
A linked map of directories.
class DirList
A list of directories.
class DirRelationLinkedMap
Functions
bool compareDirDefs (const DirDef *item1, const DirDef *item2)
DirDef * toDirDef (Definition *d)
const DirDef * toDirDef (const Definition *d)
void buildDirectories ()
void generateDirDocs (OutputList &ol)
void computeDirDependencies ()
Function Documentation
buildDirectories()
void buildDirectories ()
Definition at line 1038 of file dirdef.cpp.
{
  AUTO_TRACE();
  // for each input file
  for (const auto &fn : *Doxygen::inputNameLinkedMap)
  {
    for (const auto &fd : *fn)
    {
      if (fd->getReference().isEmpty())
      {
        DirDef *dir;
        if ((dir=Doxygen::dirLinkedMap->find(fd->getPath()))==0) // new directory
        {
          dir = DirDefImpl::mergeDirectoryInTree(fd->getPath());
        }
        if (dir && !fd->isDocumentationFile()) dir->addFile(fd.get());
      }
      else
      {
        // do something for file imported via tag files.
      }
    }
  }
  // compute relations between directories => introduce container dirs.
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    QCString name = dir->name();
    int i=name.findRev('/',name.length()-2);
    if (i>0)
    {
      DirDef *parent = Doxygen::dirLinkedMap->find(name.left(i+1));
      //if (parent==0) parent=root;
      if (parent)
      {
        parent->addSubDir(dir.get());
        AUTO_TRACE_ADD("DirDefImpl::addSubdir(): Adding subdir {} to {}",
                        dir->displayName(), parent->displayName());
      }
    }
  }
  // sort the directory contents
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    dir->sort();
  }
  // short the directories themselves
  std::sort(Doxygen::dirLinkedMap->begin(),
            Doxygen::dirLinkedMap->end(),
            [](const auto &d1,const auto &d2)
            {
              QCString s1 = d1->shortName(), s2 = d2->shortName();
              int i = qstricmp(s1,s2);
              if (i==0) // if sort name are equal, sort on full path
              {
                QCString n1 = d1->name(), n2 = d2->name();
                int n = qstricmp(n1,n2);
                return n < 0;
              }
              return i < 0;
            });
  // set the directory count identifier
  int dirCount=0;
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    dir->setDirCount(dirCount++);
  }
  computeCommonDirPrefix();
}
References DirDef::addFile(), DirDef::addSubDir(), AUTO_TRACE, AUTO_TRACE_ADD, begin(), computeCommonDirPrefix(), Doxygen::dirLinkedMap, end(), LinkedMap< T, Hash, KeyEqual, Map >::find(), QCString::findRev(), Doxygen::inputNameLinkedMap, QCString::left(), QCString::length(), DirDefImpl::mergeDirectoryInTree(), parent(), and qstricmp().
Referenced by parseInput().
compareDirDefs()
bool compareDirDefs (const DirDef * item1, const DirDef * item2)
Definition at line 1151 of file dirdef.cpp.
{
  return qstricmp(item1->shortName(),item2->shortName()) < 0;
}
References qstricmp(), and DirDef::shortName().
Referenced by DirDefImpl::sort(), and GroupDefImpl::sortMemberLists().
computeDirDependencies()
void computeDirDependencies ()
Definition at line 1112 of file dirdef.cpp.
{
  AUTO_TRACE();
  // compute nesting level for each directory
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    dir->setLevel();
  }
  // compute uses dependencies between directories
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    AUTO_TRACE_ADD("computeDependencies for {}: #dirs={}",dir->name(),Doxygen::dirLinkedMap->size());
    dir->computeDependencies();
  }
}
References AUTO_TRACE, AUTO_TRACE_ADD, Doxygen::dirLinkedMap, and LinkedMap< T, Hash, KeyEqual, Map >::size().
Referenced by parseInput().
generateDirDocs()
void generateDirDocs (OutputList & ol)
Definition at line 1129 of file dirdef.cpp.
{
  AUTO_TRACE();
  for (const auto &dir : *Doxygen::dirLinkedMap)
  {
    ol.pushGeneratorState();
    if (!dir->hasDocumentation())
    {
      ol.disableAllBut(OutputType::Html);
    }
    dir->writeDocumentation(ol);
    ol.popGeneratorState();
  }
  if (Config_getBool(DIRECTORY_GRAPH))
  {
    for (const auto &dr : Doxygen::dirRelations)
    {
      dr->writeDocumentation(ol);
    }
  }
}
References AUTO_TRACE, Config_getBool, Doxygen::dirLinkedMap, Doxygen::dirRelations, OutputList::disableAllBut(), Html, OutputList::popGeneratorState(), and OutputList::pushGeneratorState().
Referenced by generateOutput().
toDirDef() [1/2]
const DirDef * toDirDef (const Definition * d)
Definition at line 1171 of file dirdef.cpp.
{
  if (d==0) return 0;
  if (d && typeid(*d)==typeid(DirDefImpl))
  {
    return static_cast<const DirDef*>(d);
  }
  else
  {
    return 0;
  }
}
toDirDef() [2/2]
DirDef * toDirDef (Definition * d)
Definition at line 1158 of file dirdef.cpp.
{
  if (d==0) return 0;
  if (d && typeid(*d)==typeid(DirDefImpl))
  {
    return static_cast<DirDef*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by NestingNodeContext::Private::addDirFiles(), and NestingNodeContext::Private::createDir().