Doxygen: LayoutDocManager Class Reference
LayoutDocManager Class Reference
Singleton providing access to the (user configurable) layout of the documentation.
#include <layout.h>
Classes
class Private
Public Types
enum LayoutPart {
Undefined = -1 , Class , Concept , Namespace ,
File , Group , Directory , NrParts
}
Public Member Functions
const LayoutDocEntryList & docEntries (LayoutPart part) const
Returns the list of LayoutDocEntry's in representation order for a given page identified by part.
LayoutNavEntry * rootNavEntry () const
returns the (invisible) root of the navigation tree.
LayoutNavEntry * createChildNavEntry (LayoutNavEntry *root, LayoutNavEntry::Kind k, bool vs, const QCString &bf, const QCString &tl, const QCString &intro)
void parse (const QCString &fileName, const char *data=nullptr)
Parses a user provided layout.
void init ()
Static Public Member Functions
static LayoutDocManager & instance ()
Returns a reference to this singleton.
Private Member Functions
void addEntry (LayoutPart p, LayoutDocEntryPtr &&e)
void clear (LayoutPart p)
LayoutDocManager ()
~LayoutDocManager ()
Private Attributes
std::unique_ptr< Private > d
Friends
class LayoutParser
Detailed Description
Singleton providing access to the (user configurable) layout of the documentation.
Definition at line 197 of file layout.h.
Member Enumeration Documentation
LayoutPart
enum LayoutDocManager::LayoutPart
Enumerator
Undefined
Class
Concept
Namespace
File
Group
Directory
NrParts
Definition at line 201 of file layout.h.
    {
      Undefined = -1,
      Class, Concept, Namespace, File, Group, Directory,
      NrParts
    };
Constructor & Destructor Documentation
LayoutDocManager()
LayoutDocManager::LayoutDocManager () private
Definition at line 1318 of file layout.cpp.
                                   : d(std::make_unique<Private>())
{
}
~LayoutDocManager()
LayoutDocManager::~LayoutDocManager () private
Definition at line 1322 of file layout.cpp.
{
}
Member Function Documentation
addEntry()
void LayoutDocManager::addEntry (LayoutDocManager::LayoutPart p, LayoutDocEntryPtr && e) private
Definition at line 1369 of file layout.cpp.
{
  d->docEntries[static_cast<int>(p)].push_back(std::move(e));
}
References d.
Referenced by LayoutParser::endMemberDecl(), LayoutParser::endMemberDef(), LayoutParser::startMemberDecl(), LayoutParser::startMemberDeclEntry(), LayoutParser::startMemberDef(), LayoutParser::startMemberDefEntry(), LayoutParser::startSectionEntry(), and LayoutParser::startSimpleEntry().
clear()
void LayoutDocManager::clear (LayoutDocManager::LayoutPart p) private
Definition at line 1374 of file layout.cpp.
{
  d->docEntries[static_cast<int>(p)].clear();
}
References clear(), and d.
Referenced by clear(), and LayoutParser::startTop().
createChildNavEntry()
LayoutNavEntry * LayoutDocManager::createChildNavEntry (LayoutNavEntry * root, LayoutNavEntry::Kind k, bool vs, const QCString & bf, const QCString & tl, const QCString & intro)
Definition at line 1359 of file layout.cpp.
{
  if (parent==0) parent = &d->rootNav;
  auto ptr = std::make_unique<LayoutNavEntry>(parent,k,vs,bf,tl,intro);
  auto child = ptr.get();
  parent->addChild(std::move(ptr));
  return child;
}
References d, and parent().
Referenced by LayoutParser::startNavEntry().
docEntries()
const LayoutDocEntryList & LayoutDocManager::docEntries (LayoutDocManager::LayoutPart part) const
Returns the list of LayoutDocEntry's in representation order for a given page identified by part.
Definition at line 1349 of file layout.cpp.
{
  return d->docEntries[static_cast<int>(part)];
}
References d, and docEntries().
Referenced by NestingNodeContext::Private::addMembers(), addMembersToIndex(), ClassDefImpl::countAdditionalInheritedMembers(), NamespaceDefImpl::countVisibleMembers(), docEntries(), LayoutParser::endMemberDecl(), LayoutParser::endMemberDef(), ClassDefImpl::getTitleForMemberListType(), ClassDefImpl::setAnonymousEnumType(), ClassDefImpl::writeAdditionalInheritedMembers(), ClassDefImpl::writeDeclaration(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentationContents(), writeGroupTreeNode(), ClassDefImpl::writeInlineDocumentation(), writeNamespaceMembers(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), NamespaceDefImpl::writeSummaryLinks(), GroupDefImpl::writeTagFile(), NamespaceDefImpl::writeTagFile(), ClassDefImpl::writeTagFile(), DirDefImpl::writeTagFile(), and FileDefImpl::writeTagFile().
init()
void LayoutDocManager::init ()
Definition at line 1326 of file layout.cpp.
{
  LayoutParser &layoutParser = LayoutParser::instance();
  XMLHandlers handlers;
  handlers.startElement = [&layoutParser](const std::string &name,const XMLHandlers::Attributes &attrs) { layoutParser.startElement(name,attrs); };
  handlers.endElement   = [&layoutParser](const std::string &name) { layoutParser.endElement(name); };
  handlers.error        = [&layoutParser](const std::string &fileName,int lineNr,const std::string &msg) { layoutParser.error(fileName,lineNr,msg); };
  XMLParser parser(handlers);
  layoutParser.setDocumentLocator(&parser);
  constexpr auto layoutFile = "layout_default.xml";
  QCString layout_default = ResourceMgr::instance().getAsString(layoutFile);
  parser.parse(layoutFile,layout_default.data(),Debug::isFlagSet(Debug::Lex_xml),
               [&]() { DebugLex::print(Debug::Lex_xml,"Entering","libxml/xml.l",layoutFile); },
               [&]() { DebugLex::print(Debug::Lex_xml,"Finished", "libxml/xml.l",layoutFile); }
              );
}
References QCString::data(), XMLHandlers::endElement, LayoutParser::endElement(), XMLHandlers::error, LayoutParser::error(), ResourceMgr::getAsString(), LayoutParser::instance(), ResourceMgr::instance(), Debug::isFlagSet(), Debug::Lex_xml, msg(), XMLParser::parse(), LayoutParser::setDocumentLocator(), XMLHandlers::startElement, and LayoutParser::startElement().
Referenced by parseInput().
instance()
LayoutDocManager & LayoutDocManager::instance () static
Returns a reference to this singleton.
Definition at line 1343 of file layout.cpp.
{
  static LayoutDocManager theInstance;
  return theInstance;
}
Referenced by NestingNodeContext::Private::addMembers(), addMembersToIndex(), ClassDefImpl::countAdditionalInheritedMembers(), NamespaceDefImpl::countVisibleMembers(), LayoutParser::endMemberDecl(), LayoutParser::endMemberDef(), generateJSNavTree(), ClassDefImpl::getTitleForMemberListType(), parseInput(), renderQuickLinksAsTabs(), ClassDefImpl::setAnonymousEnumType(), LayoutParser::startMemberDecl(), LayoutParser::startMemberDeclEntry(), LayoutParser::startMemberDef(), LayoutParser::startMemberDefEntry(), LayoutParser::startNavEntry(), LayoutParser::startNavIndex(), LayoutParser::startSectionEntry(), LayoutParser::startSimpleEntry(), LayoutParser::startTop(), ClassDefImpl::writeAdditionalInheritedMembers(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeConceptIndex(), ClassDefImpl::writeDeclaration(), writeDefaultQuickLinks(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentationContents(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGroupIndex(), writeGroupTreeNode(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), writeIndexHierarchy(), writeIndexHierarchyEntries(), ClassDefImpl::writeInlineDocumentation(), writeMenuData(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writeNamespaceMembers(), writePageIndex(), writePages(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), NamespaceDefImpl::writeSummaryLinks(), GroupDefImpl::writeTagFile(), NamespaceDefImpl::writeTagFile(), ClassDefImpl::writeTagFile(), DirDefImpl::writeTagFile(), and FileDefImpl::writeTagFile().
parse()
void LayoutDocManager::parse (const QCString & fileName, const char * data = nullptr)
Parses a user provided layout.
Definition at line 1379 of file layout.cpp.
{
  LayoutParser &layoutParser = LayoutParser::instance();
  XMLHandlers handlers;
  handlers.startElement = [&layoutParser](const std::string &name,const XMLHandlers::Attributes &attrs) { layoutParser.startElement(name,attrs); };
  handlers.endElement   = [&layoutParser](const std::string &name) { layoutParser.endElement(name); };
  handlers.error        = [&layoutParser](const std::string &fn,int lineNr,const std::string &msg) { layoutParser.error(fn,lineNr,msg); };
  XMLParser parser(handlers);
  layoutParser.setDocumentLocator(&parser);
  parser.parse(fileName.data(),
               data ? data : fileToString(fileName).data(),
               Debug::isFlagSet(Debug::Lex_xml),
               [&]() { DebugLex::print(Debug::Lex_xml,"Entering","libxml/xml.l",qPrint(fileName)); },
               [&]() { DebugLex::print(Debug::Lex_xml,"Finished", "libxml/xml.l",qPrint(fileName)); },
               transcodeCharacterStringToUTF8
              );
}
References QCString::data(), XMLHandlers::endElement, LayoutParser::endElement(), XMLHandlers::error, LayoutParser::error(), fileToString(), LayoutParser::instance(), Debug::isFlagSet(), Debug::Lex_xml, msg(), XMLParser::parse(), DebugLex::print(), qPrint(), LayoutParser::setDocumentLocator(), XMLHandlers::startElement, LayoutParser::startElement(), and transcodeCharacterStringToUTF8().
Referenced by parseInput().
rootNavEntry()
LayoutNavEntry * LayoutDocManager::rootNavEntry () const
returns the (invisible) root of the navigation tree.
Definition at line 1354 of file layout.cpp.
{
  return &d->rootNav;
}
References d.
Referenced by generateJSNavTree(), renderQuickLinksAsTabs(), LayoutParser::startNavIndex(), LayoutParser::startTop(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeConceptIndex(), writeDefaultQuickLinks(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), writeIndexHierarchy(), writeMenuData(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), and writePages().
Friends And Related Symbol Documentation
LayoutParser
friend class LayoutParser friend
Definition at line 227 of file layout.h.
Member Data Documentation
d
std::unique_ptr<Private> LayoutDocManager::d private
Definition at line 226 of file layout.h.
Referenced by addEntry(), clear(), createChildNavEntry(), docEntries(), and rootNavEntry().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/layout.h
/home/runner/work/doxygen/doxygen/src/layout.cpp