Doxygen: DocCite Class Reference
DocCite Class Reference
Node representing a citation of some bibliographic reference.
#include <src/docnode.h>
Public Member Functions
DocCite (DocParser *parser, DocNodeVariant *parent, const QCString &target, const QCString &context)
QCString file () const
QCString relPath () const
QCString ref () const
QCString anchor () const
QCString text () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
QCString m_file
QCString m_relPath
QCString m_ref
QCString m_anchor
QCString m_text
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a citation of some bibliographic reference.
Definition at line 243 of file docnode.h.
Constructor & Destructor Documentation
DocCite()
DocCite::DocCite (DocParser * parser, DocNodeVariant * parent, const QCString & target, const QCString & context)
Definition at line 886 of file docnode.cpp.
                                                                                                 : DocNode(parser,parent)
{
  size_t numBibFiles = Config_getList(CITE_BIB_FILES).size();
  //printf("DocCite::DocCite(target=%s)\n",qPrint(target));
  ASSERT(!target.isEmpty());
  m_relPath = parser->context.relPath;
  const CitationManager &ct = CitationManager::instance();
  const CiteInfo *cite = ct.find(target);
  //printf("cite=%p text='%s' numBibFiles=%d\n",cite,cite?qPrint(cite->text):"<null>",numBibFiles);
  if (numBibFiles>0 && cite && !cite->text().isEmpty()) // ref to citation
  {
    m_text         = cite->text();
    m_ref          = "";
    m_anchor       = ct.anchorPrefix()+cite->label();
    m_file         = convertNameToFile(ct.fileName(),FALSE,TRUE);
    //printf("CITE ==> m_text=%s,m_ref=%s,m_file=%s,m_anchor=%s\n",
    //    qPrint(m_text),qPrint(m_ref),qPrint(m_file),qPrint(m_anchor));
    return;
  }
  m_text = target;
  if (numBibFiles==0)
  {
    warn_doc_error(parser->context.fileName,parser->tokenizer.getLineNr(),"\\cite command found but no bib files specified via CITE_BIB_FILES!");
  }
  else if (cite==nullptr)
  {
    warn_doc_error(parser->context.fileName,parser->tokenizer.getLineNr(),"unable to resolve reference to '%s' for \\cite command",
             qPrint(target));
  }
  else
  {
    warn_doc_error(parser->context.fileName,parser->tokenizer.getLineNr(),"\\cite command to '%s' does not have an associated number",
             qPrint(target));
  }
}
References CitationManager::anchorPrefix(), ASSERT, Config_getList, convertNameToFile(), DocNode::DocNode(), FALSE, CitationManager::fileName(), CitationManager::find(), CitationManager::instance(), QCString::isEmpty(), CiteInfo::label(), m_anchor, m_file, m_ref, m_relPath, m_text, DocNode::parent(), DocNode::parser(), qPrint(), CiteInfo::text(), TRUE, and warn_doc_error.
Member Function Documentation
anchor()
QCString DocCite::anchor () const inline
Definition at line 250 of file docnode.h.
{ return m_anchor; }
References m_anchor.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), TextDocVisitor::operator()(), and XmlDocVisitor::operator()().
file()
QCString DocCite::file () const inline
Definition at line 247 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), TextDocVisitor::operator()(), and XmlDocVisitor::operator()().
ref()
QCString DocCite::ref () const inline
Definition at line 249 of file docnode.h.
{ return m_ref; }
References m_ref.
Referenced by HtmlDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
relPath()
QCString DocCite::relPath () const inline
Definition at line 248 of file docnode.h.
{ return m_relPath; }
References m_relPath.
Referenced by HtmlDocVisitor::operator()().
text()
QCString DocCite::text () const inline
Definition at line 251 of file docnode.h.
{ return m_text; }
References m_text.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), TextDocVisitor::operator()(), and XmlDocVisitor::operator()().
Member Data Documentation
m_anchor
QCString DocCite::m_anchor private
Definition at line 257 of file docnode.h.
Referenced by anchor(), and DocCite().
m_file
QCString DocCite::m_file private
Definition at line 254 of file docnode.h.
Referenced by DocCite(), and file().
m_ref
QCString DocCite::m_ref private
Definition at line 256 of file docnode.h.
Referenced by DocCite(), and ref().
m_relPath
QCString DocCite::m_relPath private
Definition at line 255 of file docnode.h.
Referenced by DocCite(), and relPath().
m_text
QCString DocCite::m_text private
Definition at line 258 of file docnode.h.
Referenced by DocCite(), and text().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp