Doxygen: SymbolListContext::Private Class Reference
SymbolListContext::Private Class Reference
Public Member Functions
Private (const SearchIndexList::const_iterator &start, const SearchIndexList::const_iterator &end)
Public Member Functions inherited from GenericNodeListContext
GenericNodeListContext ()
size_t count () const
Returns the number of elements in the list.
TemplateVariant at (size_t index) const
Returns the element at index position index.
TemplateListIntf::ConstIteratorPtr createIterator () const
Creates a new iterator for this list.
void append (const TemplateVariant &ctn)
bool isEmpty () const
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()=default
Destroys the list.
Additional Inherited Members
Public Types inherited from TemplateListIntf
using ConstIteratorPtr = std::unique_ptr< ConstIterator >
Static Public Member Functions inherited from GenericNodeListContext
static TemplateListIntfPtr alloc ()
Detailed Description
Definition at line 8529 of file context.cpp.
Constructor & Destructor Documentation
Private()
SymbolListContext::Private::Private (const SearchIndexList::const_iterator & start, const SearchIndexList::const_iterator & end) inline
Definition at line 8532 of file context.cpp.
    {
      const Definition *prev = 0;
      for (auto it = start; it!=end;)
      {
        const Definition *def = *it;
        ++it;
        const Definition *next = it!=end ? *it : 0;
        append(SymbolContext::alloc(def,prev,next));
        prev = def;
      }
    }
References SymbolContext::alloc(), GenericNodeListContext::append(), and end().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/context.cpp