Doxygen: ClassLinkedRefMap Class Reference
ClassLinkedRefMap Class Reference
#include <src/classlist.h>
Public Member Functions
bool declVisible (const ClassDef::CompoundType *filter=nullptr) const
void writeDeclaration (OutputList &ol, const ClassDef::CompoundType *filter, const QCString &header, bool localNames) const
void writeDocumentation (OutputList &ol, const Definition *container=nullptr) const
Public Member Functions inherited from LinkedRefMap< ClassDef >
const ClassDef * find (const std::string &key) const
find an object given the key.
const ClassDef * find (const QCString &key) const
find an object given the key.
const ClassDef * find (const char *key) const
find an object given the key.
ClassDef * find (const char *key)
non-const wrapper for find() const
ClassDef * find (const QCString &key)
ClassDef * find (const std::string &key)
non-const wrapper for find() const
bool add (const char *k, ClassDef *obj)
Adds an object reference to the ordered vector if it was not added already.
bool add (const QCString &k, ClassDef *obj)
bool prepend (const char *k, ClassDef *obj)
Prepends an object reference to the ordered vector if it was not added already.
bool prepend (const QCString &key, ClassDef *obj)
bool del (const QCString &key)
Removes an object from the container and deletes it.
Ptr & operator[] (size_t pos)
const Ptr & operator[] (size_t pos) const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
bool empty () const
size_t size () const
void clear ()
Additional Inherited Members
Public Types inherited from LinkedRefMap< ClassDef >
using Ptr
using Vec
using iterator
using const_iterator
using reverse_iterator
using const_reverse_iterator
Detailed Description
Definition at line 30 of file classlist.h.
Member Function Documentation
declVisible()
bool ClassLinkedRefMap::declVisible (const ClassDef::CompoundType * filter = nullptr) const
Definition at line 29 of file classlist.cpp.
{
  bool hideUndocClasses = Config_getBool(HIDE_UNDOC_CLASSES);
  bool extractLocalClasses = Config_getBool(EXTRACT_LOCAL_CLASSES);
  for (const auto &cd : *this)
  {
    if (!cd->isAnonymous() &&
        (filter==nullptr || *filter==cd->compoundType())
       )
    {
      bool isLink = cd->isLinkable();
      if (isLink ||
          (!hideUndocClasses &&
           (!cd->isLocal() || extractLocalClasses)
          )
         )
      {
        return true;
      }
    }
  }
  return false;
}
References Config_getBool.
writeDeclaration()
void ClassLinkedRefMap::writeDeclaration (OutputList & ol, const ClassDef::CompoundType * filter, const QCString & header, bool localNames) const
Definition at line 53 of file classlist.cpp.
{
  bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  bool found=FALSE;
  for (const auto &cd : *this)
  {
    //printf("  ClassLinkedRefMap::writeDeclaration for %s\n",cd->name().data());
    if (!cd->isAnonymous() &&
        !cd->isExtension() &&
        (cd->protection()!=Protection::Private || extractPrivate) &&
        (filter==nullptr || *filter==cd->compoundType())
       )
    {
      //printf("writeDeclarationLink()\n");
      cd->writeDeclarationLink(ol,found,header,localNames);
    }
  }
  if (found) ol.endMemberList();
}
References Config_getBool, OutputList::endMemberList(), FALSE, found, and Private.
Referenced by FileDefImpl::writeClassDeclarations(), and NamespaceDefImpl::writeClassDeclarations().
writeDocumentation()
void ClassLinkedRefMap::writeDocumentation (OutputList & ol, const Definition * container = nullptr) const
Definition at line 74 of file classlist.cpp.
{
  bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  bool inlineGroupedClasses = Config_getBool(INLINE_GROUPED_CLASSES);
  bool inlineSimpleClasses = Config_getBool(INLINE_SIMPLE_STRUCTS);
  if (!inlineGroupedClasses && !inlineSimpleClasses) return;
  bool found=FALSE;
  for (const auto &cd : *this)
  {
    //printf("%s:writeDocumentation() %p linkable=%d embedded=%d container=%p partOfGroups=%zu\n",
    //  cd->name().data(),cd->getOuterScope(),cd->isLinkableInProject(),cd->isEmbeddedInOuterScope(),
    //  container,cd->partOfGroups()->size());
    if (!cd->isAnonymous() &&
        cd->isLinkableInProject() &&
        cd->isEmbeddedInOuterScope() &&
        !cd->isAlias() &&
        (container==nullptr || cd->partOfGroups().empty()) // if container==nullptr -> show as part of the group docs, otherwise only show if not part of a group
       )
    {
      //printf("  showing class %s\n",cd->name().data());
      if (!found)
      {
        ol.writeRuler();
        ol.startGroupHeader();
        ol.parseText(fortranOpt?theTranslator->trTypeDocumentation():
            theTranslator->trClassDocumentation());
        ol.endGroupHeader();
        found=TRUE;
      }
      cd->writeInlineDocumentation(ol);
    }
  }
}
References Config_getBool, OutputList::endGroupHeader(), FALSE, found, OutputList::parseText(), Definition::partOfGroups(), OutputList::startGroupHeader(), theTranslator, Translator::trClassDocumentation(), Translator::trTypeDocumentation(), TRUE, and OutputList::writeRuler().
The documentation for this class was generated from the following files:
src/classlist.h
src/classlist.cpp