Doxygen: DirIterator Class Reference
DirIterator Class Reference
#include <src/dir.h>
Classes
struct Private
Public Types
using value_type = DirEntry
using difference_type = std::ptrdiff_t
using pointer = value_type*
using reference = value_type&
using iterator_category = std::input_iterator_tag
Public Member Functions
DirIterator (const DirIterator &it)
DirIterator & operator= (const DirIterator &it)
DirIterator (DirIterator &&it)
DirIterator & operator= (DirIterator &&it)
DirIterator operator++ ()
const value_type & operator* () const
const value_type * operator-> () const
~DirIterator ()
Private Member Functions
DirIterator ()
DirIterator (const std::string &path)
Private Attributes
std::unique_ptr< Private > p
Friends
class Dir
bool operator== (const DirIterator &it1, const DirIterator &it2)
bool operator!= (const DirIterator &it1, const DirIterator &it2)
DirIterator begin (DirIterator it)
DirIterator end (const DirIterator &)
Detailed Description
Definition at line 43 of file dir.h.
Member Typedef Documentation
difference_type
using DirIterator::difference_type = std::ptrdiff_t
Definition at line 47 of file dir.h.
iterator_category
using DirIterator::iterator_category = std::input_iterator_tag
Definition at line 50 of file dir.h.
pointer
using DirIterator::pointer = value_type*
Definition at line 48 of file dir.h.
reference
using DirIterator::reference = value_type&
Definition at line 49 of file dir.h.
value_type
using DirIterator::value_type = DirEntry
Definition at line 46 of file dir.h.
Constructor & Destructor Documentation
DirIterator() [1/4]
DirIterator::DirIterator (const DirIterator & it)
Definition at line 104 of file dir.cpp.
                                              : p(std::make_unique<Private>())
{
  p->it = it.p->it;
  p->ec = it.p->ec;
  p->current = it.p->current;
}
References DirIterator(), and p.
Referenced by begin, DirIterator(), DirIterator(), end, operator!=, operator++(), operator=(), operator=(), and operator==.
DirIterator() [2/4]
DirIterator::DirIterator (DirIterator && it)
Definition at line 122 of file dir.cpp.
                                         : p(std::make_unique<Private>())
{
  std::exchange(p->it,it.p->it);
  std::exchange(p->ec,it.p->ec);
  std::exchange(p->current,it.p->current);
}
References DirIterator(), and p.
~DirIterator()
DirIterator::~DirIterator ()
Definition at line 137 of file dir.cpp.
{
}
DirIterator() [3/4]
DirIterator::DirIterator () private
Definition at line 96 of file dir.cpp.
                         : p(std::make_unique<Private>())
{
}
References p.
DirIterator() [4/4]
DirIterator::DirIterator (const std::string & path) private
Definition at line 100 of file dir.cpp.
                                              : p(std::make_unique<Private>(path))
{
}
References p.
Member Function Documentation
operator*()
const DirIterator::value_type & DirIterator::operator* () const
Definition at line 148 of file dir.cpp.
{
  p->current.p->entry = *p->it;
  return p->current;
}
References p.
operator++()
DirIterator DirIterator::operator++ ()
Definition at line 141 of file dir.cpp.
{
  DirIterator result;
  result.p->it = ++p->it;
  return result;
}
References DirIterator(), and p.
operator->()
const DirIterator::value_type * DirIterator::operator-> () const
Definition at line 154 of file dir.cpp.
{
  p->current.p->entry = *p->it;
  return &p->current;
}
References p.
operator=() [1/2]
DirIterator & DirIterator::operator= (const DirIterator & it)
Definition at line 111 of file dir.cpp.
{
  if (&it!=this)
  {
    p->it = it.p->it;
    p->ec = it.p->ec;
    p->current = it.p->current;
  }
  return *this;
}
References DirIterator(), and p.
operator=() [2/2]
DirIterator & DirIterator::operator= (DirIterator && it)
Definition at line 129 of file dir.cpp.
{
  std::exchange(p->it,it.p->it);
  std::exchange(p->ec,it.p->ec);
  std::exchange(p->current,it.p->current);
  return *this;
}
References DirIterator(), and p.
Friends And Related Symbol Documentation
begin
DirIterator begin (DirIterator it) friend
Definition at line 170 of file dir.cpp.
{
  return it;
}
References DirIterator().
Dir
friend class Dir friend
Definition at line 66 of file dir.h.
References Dir.
Referenced by Dir.
end
DirIterator end (const DirIterator &) friend
Definition at line 175 of file dir.cpp.
{
  return DirIterator();
}
References DirIterator().
operator!=
bool operator!= (const DirIterator & it1, const DirIterator & it2) friend
Definition at line 165 of file dir.cpp.
{
  return it1.p->it!=it2.p->it;
}
References DirIterator(), and p.
operator==
bool operator== (const DirIterator & it1, const DirIterator & it2) friend
Definition at line 160 of file dir.cpp.
{
  return it1.p->it == it2.p->it;
}
References DirIterator(), and p.
Member Data Documentation
p
std::unique_ptr<Private> DirIterator::p private
Definition at line 70 of file dir.h.
Referenced by DirIterator(), DirIterator(), DirIterator(), DirIterator(), operator!=, operator*(), operator++(), operator->(), operator=(), operator=(), and operator==.
The documentation for this class was generated from the following files:
src/dir.h
src/dir.cpp