Doxygen: ManCodeGenerator Class Reference
ManCodeGenerator Class Reference
Generator for Man page code fragments.
#include <src/mangen.h>
Public Member Functions
ManCodeGenerator (TextStream *t)
void setTextStream (TextStream *t)
OutputType type () const
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &)
void writeLineNumber (const QCString &, const QCString &, const QCString &, int l, bool)
void startCodeLine (int)
void endCodeLine ()
void startFontClass (const QCString &)
void endFontClass ()
void writeCodeAnchor (const QCString &)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &)
void startFold (int, const QCString &, const QCString &)
void endFold ()
Private Attributes
int m_col = 0
TextStream * m_t
Detailed Description
Generator for Man page code fragments.
Definition at line 24 of file mangen.h.
Constructor & Destructor Documentation
ManCodeGenerator()
ManCodeGenerator::ManCodeGenerator (TextStream * t)
Definition at line 111 of file mangen.cpp.
                                                : m_t(t)
{
}
Member Function Documentation
codify()
void ManCodeGenerator::codify (const QCString & text)
Definition at line 160 of file mangen.cpp.
{
  //static char spaces[]="        ";
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    int spacesToNextTabStop;
    while (*p)
    {
      c=*p++;
      switch(c)
      {
        case '-':  *m_t << "\\-"; break; // see  bug747780
        case '.':   *m_t << "\\&."; break; // see  bug652277
        case '\t':  spacesToNextTabStop =
                          Config_getInt(TAB_SIZE) - (m_col%Config_getInt(TAB_SIZE));
                    *m_t << Doxygen::spaces.left(spacesToNextTabStop);
                    m_col+=spacesToNextTabStop;
                    break;
        case '\n':  *m_t << "\n"; m_col=0; break;
        case '\\':  *m_t << "\\\\"; m_col++; break;
        case '\"':  // no break!
        default:    p=writeUTF8Char(*m_t,p-1); m_col++; break;
      }
    }
    //printf("%s",str);fflush(stdout);
  }
}
References Config_getInt, QCString::data(), QCString::isEmpty(), QCString::left(), m_col, m_t, Doxygen::spaces, and writeUTF8Char().
Referenced by endCodeLine().
endCodeFragment()
void ManCodeGenerator::endCodeFragment (const QCString &)
Definition at line 121 of file mangen.cpp.
{
  if (m_col>0) *m_t << "\n";
  *m_t << ".PP\n";
  *m_t << ".fi\n";
  m_col=0;
}
References m_col, and m_t.
endCodeLine()
void ManCodeGenerator::endCodeLine () inline
Definition at line 46 of file mangen.h.
{ codify("\n"); m_col=0; }
References codify(), and m_col.
endFold()
void ManCodeGenerator::endFold () inline
Definition at line 53 of file mangen.h.
{}
endFontClass()
void ManCodeGenerator::endFontClass () inline
Definition at line 48 of file mangen.h.
{}
setTextStream()
void ManCodeGenerator::setTextStream (TextStream * t) inline
Definition at line 28 of file mangen.h.
{ m_t = t; }
References m_t.
Referenced by ManGenerator::ManGenerator(), ManGenerator::ManGenerator(), and ManGenerator::operator=().
startCodeFragment()
void ManCodeGenerator::startCodeFragment (const QCString & style)
Definition at line 115 of file mangen.cpp.
{
  *m_t << "\n";
  *m_t << ".nf\n";
}
References m_t.
startCodeLine()
void ManCodeGenerator::startCodeLine (int) inline
Definition at line 45 of file mangen.h.
{}
startFold()
void ManCodeGenerator::startFold (int , const QCString & , const QCString &) inline
Definition at line 52 of file mangen.h.
{}
startFontClass()
void ManCodeGenerator::startFontClass (const QCString &) inline
Definition at line 47 of file mangen.h.
{}
type()
OutputType ManCodeGenerator::type () const inline
Definition at line 30 of file mangen.h.
{ return OutputType::Man; }
References Man.
writeCodeAnchor()
void ManCodeGenerator::writeCodeAnchor (const QCString &) inline
Definition at line 49 of file mangen.h.
{}
writeCodeLink()
void ManCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip)
Definition at line 135 of file mangen.cpp.
{
  if (!name.isEmpty())
  {
    const char *p=name.data();
    char c=0;
    while ((c=*p++))
    {
      switch(c)
      {
        case '-':  *m_t << "\\-"; break; // see  bug747780
        case '.':  *m_t << "\\&."; break; // see  bug652277
        case '\\': *m_t << "\\\\"; m_col++; break;
        case '\n': *m_t << "\n"; m_col=0; break;
        case '\"':  c = '\''; // no break!
        default: *m_t << c; m_col++; break;
      }
    }
    //printf("%s",str);fflush(stdout);
  }
}
References QCString::data(), QCString::isEmpty(), m_col, and m_t.
writeLineNumber()
void ManCodeGenerator::writeLineNumber (const QCString & , const QCString & , const QCString & , int l, bool)
Definition at line 129 of file mangen.cpp.
{
  *m_t << l << " ";
  m_col=0;
}
References m_col, and m_t.
writeTooltip()
void ManCodeGenerator::writeTooltip (const QCString & , const DocLinkInfo & , const QCString & , const QCString & , const SourceLinkInfo & , const SourceLinkInfo &) inline
Definition at line 37 of file mangen.h.
                       {}
Member Data Documentation
m_col
int ManCodeGenerator::m_col = 0 private
Definition at line 56 of file mangen.h.
Referenced by codify(), endCodeFragment(), endCodeLine(), writeCodeLink(), and writeLineNumber().
m_t
TextStream* ManCodeGenerator::m_t private
Definition at line 57 of file mangen.h.
Referenced by codify(), endCodeFragment(), setTextStream(), startCodeFragment(), writeCodeLink(), and writeLineNumber().
The documentation for this class was generated from the following files:
src/mangen.h
src/mangen.cpp