Doxygen: ClassDefImpl Class Reference
ClassDefImpl Class Reference
Implementation of the ClassDef interface.
Classes
class IMPL
Private data associated with a ClassDef object.
Public Member Functions
ClassDefImpl (const QCString &fileName, int startLine, int startColumn, const QCString &name, CompoundType ct, const QCString &ref=QCString(), const QCString &fName=QCString(), bool isSymbol=TRUE, bool isJavaEnum=FALSE)
DefType definitionType () const override
std::unique_ptr< ClassDef > deepCopy (const QCString &name) const override
void moveTo (Definition *) override
CodeSymbolType codeSymbolType () const override
QCString getOutputFileBase () const override
QCString getInstanceOutputFileBase () const override
QCString getSourceFileBase () const override
QCString getReference () const override
bool isReference () const override
bool isLocal () const override
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES.
ClassLinkedRefMap getClasses () const override
returns the classes nested into this class
bool hasDocumentation () const override
bool hasDetailedDescription () const override
returns TRUE if this class has a non-empty detailed description
QCString collaborationGraphFileName () const override
returns the file name to use for the collaboration graph
QCString inheritanceGraphFileName () const override
returns the file name to use for the inheritance graph
QCString displayName (bool includeScope=TRUE) const override
CompoundType compoundType () const override
Returns the type of compound this is, i.e.
QCString compoundTypeString () const override
Returns the type of compound as a string.
const BaseClassList & baseClasses () const override
Returns the list of base classes from which this class directly inherits.
void updateBaseClasses (const BaseClassList &bcd) override
Update the list of base classes to the one passed.
const BaseClassList & subClasses () const override
Returns the list of sub classes that directly derive from this class.
void updateSubClasses (const BaseClassList &bcd) override
Update the list of sub classes to the one passed.
const MemberNameInfoLinkedMap & memberNameInfoLinkedMap () const override
Returns a dictionary of all members.
Protection protection () const override
Return the protection level (Public,Protected,Private) in which this compound was found.
bool isLinkableInProject () const override
bool isLinkable () const override
bool isVisibleInHierarchy () const override
bool visibleInParentsDeclList () const override
show this class in the declaration section of its parent?
const ArgumentList & templateArguments () const override
Returns the template arguments of this class.
FileDef * getFileDef () const override
Returns the namespace this compound is in, or 0 if it has a global scope.
ModuleDef * getModuleDef () const override
Returns the C++20 module in which this compound's definition can be found.
const MemberDef * getMemberByName (const QCString &) const override
Returns the member with the given name.
int isBaseClass (const ClassDef *bcd, bool followInstances, const QCString &templSpec) const override
Returns TRUE iff bcd is a direct or indirect base class of this class.
bool isSubClass (ClassDef *bcd, int level=0) const override
Returns TRUE iff bcd is a direct or indirect sub class of this class.
bool isAccessibleMember (const MemberDef *md) const override
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
const TemplateInstanceList & getTemplateInstances () const override
Returns a sorted dictionary with all template instances found for this template class.
const ClassDef * templateMaster () const override
Returns the template master of which this class is an instance.
bool isTemplate () const override
Returns TRUE if this class is a template.
const IncludeInfo * includeInfo () const override
const UsesClassList & usedImplementationClasses () const override
const UsesClassList & usedByImplementationClasses () const override
const ConstraintClassList & templateTypeConstraints () const override
bool isTemplateArgument () const override
const Definition * findInnerCompound (const QCString &name) const override
ArgumentLists getTemplateParameterLists () const override
Returns the template parameter lists that form the template declaration of this class.
QCString qualifiedNameWithTemplateParameters (const ArgumentLists *actualParams=nullptr, uint32_t *actualParamIndex=nullptr) const override
bool isAbstract () const override
Returns TRUE if there is at least one pure virtual member in this class.
bool isObjectiveC () const override
Returns TRUE if this class is implemented in Objective-C.
bool isFortran () const override
Returns TRUE if this class is implemented in Fortran.
bool isCSharp () const override
Returns TRUE if this class is implemented in C#.
bool isFinal () const override
Returns TRUE if this class is marked as final.
bool isSealed () const override
Returns TRUE if this class is marked as sealed.
bool isPublished () const override
Returns TRUE if this class is marked as published.
bool isExtension () const override
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
bool isForwardDeclared () const override
Returns TRUE if this class represents a forward declaration of a template class.
bool isInterface () const override
Returns TRUE if this class represents an interface.
ClassDef * categoryOf () const override
Returns the class of which this is a category (Objective-C only)
QCString className () const override
Returns the name of the class including outer classes, but not including namespaces.
MemberList * getMemberList (MemberListType lt) const override
Returns the members in the list identified by lt.
const MemberLists & getMemberLists () const override
Returns the list containing the list of members sorted per type.
const MemberGroupList & getMemberGroups () const override
Returns the member groups defined for this class.
const TemplateNameMap & getTemplateBaseClassNames () const override
bool isUsedOnly () const override
QCString anchor () const override
bool isEmbeddedInOuterScope () const override
bool isSimple () const override
const ClassDef * tagLessReference () const override
const MemberDef * isSmartPointer () const override
bool isJavaEnum () const override
QCString title () const override
QCString generatedFromFiles () const override
const FileList & usedFiles () const override
const ArgumentList & typeConstraints () const override
const ExampleList & getExamples () const override
bool hasExamples () const override
QCString getMemberListFileName () const override
bool subGrouping () const override
bool isSliceLocal () const override
bool hasNonReferenceSuperClass () const override
QCString requiresClause () const override
StringVector getQualifiers () const override
bool containsOverload (const MemberDef *md) const override
ClassDef * insertTemplateInstance (const QCString &fileName, int startLine, int startColumn, const QCString &templSpec, bool &freshInstance) const override
bool isImplicitTemplateInstance () const override
void insertBaseClass (ClassDef *, const QCString &name, Protection p, Specifier s, const QCString &t=QCString()) override
void insertSubClass (ClassDef *, Protection p, Specifier s, const QCString &t=QCString()) override
void insertExplicitTemplateInstance (ClassDef *instance, const QCString &spec) override
void setIncludeFile (FileDef *fd, const QCString &incName, bool local, bool force) override
void insertMember (MemberDef *) override
void insertUsedFile (const FileDef *) override
bool addExample (const QCString &anchor, const QCString &name, const QCString &file) override
void mergeCategory (ClassDef *category) override
void setFileDef (FileDef *fd) override
void setModuleDef (ModuleDef *mod) override
void setSubGrouping (bool enabled) override
void setProtection (Protection p) override
void setGroupDefForAllMembers (GroupDef *g, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs) override
void addInnerCompound (Definition *d) override
void addUsedClass (ClassDef *cd, const QCString &accessName, Protection prot) override
void addUsedByClass (ClassDef *cd, const QCString &accessName, Protection prot) override
void setIsStatic (bool b) override
void setCompoundType (CompoundType t) override
void setClassName (const QCString &name) override
void setClassSpecifier (TypeSpecifier spec) override
void addQualifiers (const StringVector &qualifiers) override
void setTemplateArguments (const ArgumentList &al) override
void setTemplateBaseClassNames (const TemplateNameMap &templateNames) override
void setTemplateMaster (const ClassDef *tm) override
void setImplicitTemplateInstance (bool b) override
void setTypeConstraints (const ArgumentList &al) override
void addMembersToTemplateInstance (const ClassDef *cd, const ArgumentList &templateArguments, const QCString &templSpec) override
void makeTemplateArgument (bool b=TRUE) override
void setCategoryOf (ClassDef *cd) override
void setUsedOnly (bool b) override
void setTagLessReference (const ClassDef *cd) override
void setMetaData (const QCString &md) override
void findSectionsInDocumentation () override
void addMembersToMemberGroup () override
void addListReferences () override
void addTypeConstraints () override
void computeAnchors () override
void mergeMembers () override
void sortMemberLists () override
void distributeMemberGroupDocumentation () override
void writeDocumentation (OutputList &ol) const override
void writeDocumentationForInnerClasses (OutputList &ol) const override
void writeMemberPages (OutputList &ol) const override
void writeMemberList (OutputList &ol) const override
void writeDeclaration (OutputList &ol, const MemberDef *md, bool inGroup, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const override
void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const override
void writeSummaryLinks (OutputList &ol) const override
void reclassifyMember (MemberDefMutable *md, MemberType t) override
void writeInlineDocumentation (OutputList &ol) const override
Write class documentation inside another container (i.e.
void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const override
void removeMemberFromLists (MemberDef *md) override
void setAnonymousEnumType () override
void countMembers () override
void sortAllMembersList () override
void addGroupedInheritedMembers (OutputList &ol, MemberListType lt, const ClassDef *inheritedFrom, const QCString &inheritId) const override
void writeTagFile (TextStream &) const override
int countMembersIncludingGrouped (MemberListType lt, const ClassDef *inheritedFrom, bool additional) const override
int countMemberDeclarations (MemberListType lt, const ClassDef *inheritedFrom, MemberListType lt2, bool invert, bool showAlways, ClassDefSet &visitedClasses) const override
void writeMemberDeclarations (OutputList &ol, ClassDefSet &visitedClasses, MemberListType lt, const QCString &title, const QCString &subTitle=QCString(), bool showInline=FALSE, const ClassDef *inheritedFrom=nullptr, MemberListType lt2=MemberListType::Invalid(), bool invert=FALSE, bool showAlways=FALSE) const override
void setRequiresClause (const QCString &req) override
CLASS_GRAPH_t hasInheritanceGraph () const override
void overrideInheritanceGraph (CLASS_GRAPH_t e) override
bool hasCollaborationGraph () const override
void overrideCollaborationGraph (bool e) override
Public Member Functions inherited from DefinitionMixin< ClassDefMutable >
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=nullptr, const char *d=nullptr, bool isSymbol=TRUE)
DefinitionMixin (const DefinitionMixin &other)
DefinitionMixin (DefinitionMixin &&)=delete
DefinitionMixin & operator= (const DefinitionMixin &other)
DefinitionMixin & operator= (DefinitionMixin &&)=delete
~DefinitionMixin () override=default
bool isAlias () const override
const QCString & name () const override
bool isAnonymous () const override
const QCString & localName () const override
QCString qualifiedName () const override
QCString symbolName () const override
QCString getSourceFileBase () const override
QCString getSourceAnchor () const override
QCString documentation () const override
int docLine () const override
QCString docFile () const override
QCString briefDescription (bool abbreviate=FALSE) const override
QCString briefDescriptionAsTooltip () const override
int briefLine () const override
QCString inbodyDocumentation () const override
QCString inbodyFile () const override
int inbodyLine () const override
QCString briefFile () const override
QCString getDefFileName () const override
QCString getDefFileExtension () const override
int getDefLine () const override
int getDefColumn () const override
bool hasDocumentation () const override
bool hasUserDocumentation () const override
bool isVisibleInProject () const override
bool isVisible () const override
bool isHidden () const override
bool isArtificial () const override
bool isExported () const override
QCString getReference () const override
bool isReference () const override
QCString externalReference (const QCString &relPath) const override
int getStartDefLine () const override
int getStartBodyLine () const override
int getEndBodyLine () const override
const FileDef * getBodyDef () const override
SrcLangExt getLanguage () const override
const GroupList & partOfGroups () const override
bool isLinkableViaGroup () const override
const RefItemVector & xrefListItems () const override
const Definition * findInnerCompound (const QCString &name) const override
Definition * getOuterScope () const override
const MemberVector & getReferencesMembers () const override
const MemberVector & getReferencedByMembers () const override
bool hasSections () const override
bool hasSources () const override
bool hasBriefDescription () const override
QCString id () const override
const SectionRefs & getSectionRefs () const override
void setName (const QCString &name) override
void setId (const QCString &name) override
void setDefFile (const QCString &df, int defLine, int defColumn) override
void setDocumentation (const QCString &doc, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE) override
void setBriefDescription (const QCString &brief, const QCString &briefFile, int briefLine) override
void setInbodyDocumentation (const QCString &doc, const QCString &docFile, int docLine) override
void setReference (const QCString &r) override
void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList) override
void setBodySegment (int defLine, int bls, int ble) override
void setBodyDef (const FileDef *fd) override
void addSourceReferencedBy (MemberDef *md, const QCString &sourceRefName) override
void addSourceReferences (MemberDef *md, const QCString &sourceRefName) override
void setRefItems (const RefItemVector &sli) override
void mergeRefItems (Definition *def) override
void mergeReferences (const Definition *other) override
void mergeReferencedBy (const Definition *other) override
void addInnerCompound (Definition *def) override
void setOuterScope (Definition *def) override
void setHidden (bool b) override
void setArtificial (bool b) override
void setExported (bool b) override
void setLanguage (SrcLangExt lang) override
void writeSourceDef (OutputList &ol) const override
void writeInlineCode (OutputList &ol, const QCString &scopeName) const override
bool hasSourceRefs () const override
bool hasSourceReffedBy () const override
void writeSourceRefs (OutputList &ol, const QCString &scopeName) const override
void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const override
void makePartOfGroup (GroupDef *gd) override
void writeNavigationPath (OutputList &ol) const override
QCString navigationPathAsString () const override
void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const override
void writeSummaryLinks (OutputList &ol) const override
QCString pathFragment () const override
void writeDocAnchorsToTagFile (TextStream &fs) const override
void setLocalName (const QCString &name) override
void writeToc (OutputList &ol, const LocalToc &lt) const override
void computeTooltip () override
void _setSymbolName (const QCString &name) override
QCString _symbolName () const override
Public Member Functions inherited from ClassDefMutable
Public Member Functions inherited from DefinitionMutable
Public Member Functions inherited from ClassDef
Public Member Functions inherited from Definition
Private Member Functions
int countInheritedByNodes () const
int countInheritsNodes () const
int countInheritanceNodes () const
void addUsedInterfaceClasses (MemberDef *md, const QCString &typeStr)
void showUsedFiles (OutputList &ol) const
void writeDocumentationContents (OutputList &ol, const QCString &pageTitle) const
void internalInsertMember (MemberDef *md, Protection prot, bool addToAllList)
void addMemberToList (MemberListType lt, MemberDef *md, bool isBrief)
void writeInheritedMemberDeclarations (OutputList &ol, ClassDefSet &visitedClasses, MemberListType lt, MemberListType lt2, const QCString &title, const ClassDef *inheritedFrom, bool invert, bool showAlways) const
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title, bool showInline=FALSE) const
void writeSimpleMemberDocumentation (OutputList &ol, MemberListType lt) const
void writePlainMemberDeclaration (OutputList &ol, MemberListType lt, bool inGroup, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const
void writeBriefDescription (OutputList &ol, bool exampleFlag) const
void writeDetailedDescription (OutputList &ol, const QCString &pageType, bool exampleFlag, const QCString &title, const QCString &anchor=QCString()) const
void writeIncludeFiles (OutputList &ol) const
void writeIncludeFilesForSlice (OutputList &ol) const
void writeInheritanceGraph (OutputList &ol) const
void writeCollaborationGraph (OutputList &ol) const
void writeMemberGroups (OutputList &ol, bool showInline=FALSE) const
void writeNestedClasses (OutputList &ol, const QCString &title) const
void writeInlineClasses (OutputList &ol) const
void startMemberDeclarations (OutputList &ol) const
void endMemberDeclarations (OutputList &ol) const
void startMemberDocumentation (OutputList &ol) const
void endMemberDocumentation (OutputList &ol) const
void writeAuthorSection (OutputList &ol) const
void writeMoreLink (OutputList &ol, const QCString &anchor) const
void writeDetailedDocumentationBody (OutputList &ol) const
int countAdditionalInheritedMembers () const
void writeAdditionalInheritedMembers (OutputList &ol) const
void addClassAttributes (OutputList &ol) const
int countInheritedDecMembers (MemberListType lt, const ClassDef *inheritedFrom, bool invert, bool showAlways, ClassDefSet &visitedClasses) const
void getTitleForMemberListType (MemberListType type, QCString &title, QCString &subtitle) const
void addTypeConstraint (const QCString &typeConstraint, const QCString &type)
void writeTemplateSpec (OutputList &ol, const Definition *d, const QCString &type, SrcLangExt lang) const
void mergeMembersFromBaseClasses (bool mergeVirtualBaseClass)
Private Attributes
std::unique_ptr< IMPL > m_impl
Additional Inherited Members
Public Types inherited from ClassDef
enum CompoundType {
Class , Struct , Union , Interface ,
Protocol , Category , Exception , Service ,
Singleton
}
The various compound types.
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Detailed Description
Implementation of the ClassDef interface.
Definition at line 185 of file classdef.cpp.
Constructor & Destructor Documentation
ClassDefImpl()
ClassDefImpl::ClassDefImpl (const QCString & fileName, int startLine, int startColumn, const QCString & name, CompoundType ct, const QCString & ref = QCString(), const QCString & fName = QCString(), bool isSymbol = TRUE, bool isJavaEnum = FALSE)
Definition at line 859 of file classdef.cpp.
 : DefinitionMixin(defFileName,defLine,defColumn,removeRedundantWhiteSpace(nm),nullptr,nullptr,isSymbol),
  m_impl(std::make_unique<IMPL>())
{
  setReference(lref);
  m_impl->compType = ct;
  m_impl->isJavaEnum = isJavaEnum;
  QCString compTypeString = getCompoundTypeString(getLanguage(),ct,isJavaEnum);
  m_impl->init(defFileName,name(),compTypeString,fName);
  m_impl->memberListFileName = convertNameToFile(compTypeString+name()+"-members");
  m_impl->collabFileName = convertNameToFile(m_impl->fileName+"_coll_graph");
  m_impl->inheritFileName = convertNameToFile(m_impl->fileName+"_inherit_graph");
  if (lref.isEmpty())
  {
    m_impl->fileName = convertNameToFile(m_impl->fileName);
  }
}
References convertNameToFile(), DefinitionMixin< ClassDefMutable >::DefinitionMixin(), getCompoundTypeString(), DefinitionMixin< ClassDefMutable >::getLanguage(), QCString::isEmpty(), isJavaEnum(), m_impl, DefinitionMixin< ClassDefMutable >::name(), and DefinitionMixin< ClassDefMutable >::setReference().
Referenced by addTypeConstraint(), insertTemplateInstance(), toClassDef(), toClassDef(), toClassDef(), and toClassDefMutable().
Member Function Documentation
addClassAttributes()
void ClassDefImpl::addClassAttributes (OutputList & ol) const private
Definition at line 2703 of file classdef.cpp.
{
  StringVector sl;
  if (isFinal())    sl.emplace_back("final");
  if (isSealed())   sl.emplace_back("sealed");
  if (isAbstract()) sl.emplace_back("abstract");
  if (isExported()) sl.emplace_back("export");
  if (getLanguage()==SrcLangExt::IDL && isPublished()) sl.emplace_back("published");
  for (const auto &sx : m_impl->qualifiers)
  {
    bool alreadyAdded = std::find(sl.begin(), sl.end(), sx) != sl.end();
    if (!alreadyAdded)
    {
      sl.push_back(sx);
    }
  }
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  if (!sl.empty())
  {
    ol.startLabels();
    size_t i=0;
    for (const auto &s : sl)
    {
      i++;
      ol.writeLabel(s.c_str(),i==sl.size());
    }
    ol.endLabels();
  }
  ol.popGeneratorState();
}
References OutputList::disableAllBut(), OutputList::endLabels(), DefinitionMixin< ClassDefMutable >::getLanguage(), Html, IDL, isAbstract(), DefinitionMixin< ClassDefMutable >::isExported(), isFinal(), isPublished(), isSealed(), m_impl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startLabels(), and OutputList::writeLabel().
Referenced by writeDocumentation().
addExample()
bool ClassDefImpl::addExample (const QCString & anchor, const QCString & name, const QCString & file) override virtual
Implements ClassDefMutable.
Definition at line 3364 of file classdef.cpp.
{
  return m_impl->examples.inSort(Example(anchor,nameStr,file));
}
References anchor(), and m_impl.
addGroupedInheritedMembers()
void ClassDefImpl::addGroupedInheritedMembers (OutputList & ol, MemberListType lt, const ClassDef * inheritedFrom, const QCString & inheritId) const override virtual
Implements ClassDef.
Definition at line 4804 of file classdef.cpp.
{
  //printf("** %s::addGroupedInheritedMembers() inheritId=%s\n",qPrint(name()),qPrint(inheritId));
  for (const auto &mg : m_impl->memberGroups)
  {
    if (!mg->allMembersInSameSection() || !m_impl->subGrouping) // group is in its own section
    {
      mg->addGroupedInheritedMembers(ol,this,lt,inheritedFrom,inheritId);
    }
  }
}
References m_impl.
addInnerCompound()
void ClassDefImpl::addInnerCompound (Definition * d) override virtual
Implements DefinitionMutable.
Definition at line 4217 of file classdef.cpp.
{
  //printf("**** %s::addInnerCompound(%s)\n",qPrint(name()),qPrint(d->name()));
  if (d->definitionType()==Definition::TypeClass) // only classes can be
                                                  // nested in classes.
  {
    m_impl->innerClasses.add(d->localName(),toClassDef(d));
  }
}
References Definition::definitionType(), Definition::localName(), m_impl, toClassDef(), and Definition::TypeClass.
addListReferences()
void ClassDefImpl::addListReferences () override virtual
Implements ClassDefMutable.
Definition at line 4412 of file classdef.cpp.
{
  SrcLangExt lang = getLanguage();
  if (!isLinkableInProject()) return;
  //printf("ClassDef(%s)::addListReferences()\n",qPrint(name()));
  {
    const RefItemVector &xrefItems = xrefListItems();
    addRefItem(xrefItems,
             qualifiedName(),
             theTranslator->trCompoundType(compoundType(), lang),
             getOutputFileBase(),
             displayName(),
             QCString(),
             this
            );
  }
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->addListReferences(this);
  }
  for (auto &ml : m_impl->memberLists)
  {
    if (ml->listType().isDetailed())
    {
      ml->addListReferences(this);
    }
  }
}
References addRefItem(), compoundType(), displayName(), DefinitionMixin< ClassDefMutable >::getLanguage(), getOutputFileBase(), isLinkableInProject(), m_impl, DefinitionMixin< ClassDefMutable >::qualifiedName(), theTranslator, Translator::trCompoundType(), and DefinitionMixin< ClassDefMutable >::xrefListItems().
addMembersToMemberGroup()
void ClassDefImpl::addMembersToMemberGroup () override virtual
Implements ClassDefMutable.
Definition at line 1035 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    if (!ml->listType().isDetailed())
    {
      ::addMembersToMemberGroup(ml.get(),&m_impl->memberGroups,this);
    }
  }
  // add members inside sections to their groups
  for (const auto &mg : m_impl->memberGroups)
  {
    if (mg->allMembersInSameSection() && m_impl->subGrouping)
    {
      //printf("addToDeclarationSection(%s)\n",qPrint(mg->header()));
      mg->addToDeclarationSection();
    }
  }
}
References addMembersToMemberGroup(), and m_impl.
Referenced by addMembersToMemberGroup().
addMembersToTemplateInstance()
void ClassDefImpl::addMembersToTemplateInstance (const ClassDef * cd, const ArgumentList & templateArguments, const QCString & templSpec) override virtual
Implements ClassDefMutable.
Definition at line 4308 of file classdef.cpp.
{
  //printf("%s::addMembersToTemplateInstance(%s,%s)\n",qPrint(name()),qPrint(cd->name()),templSpec);
  for (const auto &mni : cd->memberNameInfoLinkedMap())
  {
    for (const auto &mi : *mni)
    {
      auto actualArguments_p = stringToArgumentList(getLanguage(),templSpec);
      MemberDef *md = mi->memberDef();
      auto imd = md->createTemplateInstanceMember(templateArguments,actualArguments_p);
      //printf("%s->setMemberClass(%p)\n",qPrint(imd->name()),this);
      auto mmd = toMemberDefMutable(imd.get());
      mmd->setMemberClass(this);
      mmd->setTemplateMaster(md);
      mmd->setDocumentation(md->documentation(),md->docFile(),md->docLine());
      mmd->setBriefDescription(md->briefDescription(),md->briefFile(),md->briefLine());
      mmd->setInbodyDocumentation(md->inbodyDocumentation(),md->inbodyFile(),md->inbodyLine());
      mmd->setMemberSpecifiers(md->getMemberSpecifiers());
      mmd->setMemberGroupId(md->getMemberGroupId());
      mmd->setArtificial(true);
      insertMember(imd.get());
      //printf("Adding member=%s %s%s to class %s templSpec %s\n",
      //    imd->typeString(),qPrint(imd->name()),imd->argsString(),
      //    qPrint(imd->getClassDef()->name()),templSpec);
      // insert imd in the list of all members
      //printf("Adding member=%s class=%s\n",qPrint(imd->name()),qPrint(name()));
      MemberName *mn = Doxygen::memberNameLinkedMap->add(imd->name());
      mn->push_back(std::move(imd));
    }
  }
  // also instantatie members for nested classes
  for (const auto &innerCd : cd->getClasses())
  {
    ClassDefMutable *ncd = toClassDefMutable(m_impl->innerClasses.find(innerCd->localName()));
    if (ncd)
    {
      ncd->addMembersToTemplateInstance(innerCd,cd->templateArguments(),templSpec);
    }
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), ClassDefMutable::addMembersToTemplateInstance(), Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), MemberDef::createTemplateInstanceMember(), Definition::docFile(), Definition::docLine(), Definition::documentation(), ClassDef::getClasses(), DefinitionMixin< ClassDefMutable >::getLanguage(), MemberDef::getMemberGroupId(), MemberDef::getMemberSpecifiers(), Definition::inbodyDocumentation(), Definition::inbodyFile(), Definition::inbodyLine(), insertMember(), m_impl, ClassDef::memberNameInfoLinkedMap(), Doxygen::memberNameLinkedMap, MemberName::push_back(), stringToArgumentList(), ClassDef::templateArguments(), templateArguments(), toClassDefMutable(), and toMemberDefMutable().
addMemberToList()
void ClassDefImpl::addMemberToList (MemberListType lt, MemberDef * md, bool isBrief) private
Definition at line 4483 of file classdef.cpp.
{
  AUTO_TRACE("{} md={} lt={} isBrief={}",name(),md->name(),lt,isBrief);
  bool sortBriefDocs = Config_getBool(SORT_BRIEF_DOCS);
  bool sortMemberDocs = Config_getBool(SORT_MEMBER_DOCS);
  const auto &ml = m_impl->memberLists.get(lt,MemberListContainer::Class);
  ml->setNeedsSorting((isBrief && sortBriefDocs) || (!isBrief && sortMemberDocs));
  ml->push_back(md);
  // for members in the declaration lists we set the section, needed for member grouping
  if (!ml->listType().isDetailed())
  {
    MemberDefMutable *mdm = toMemberDefMutable(md);
    if (mdm)
    {
      mdm->setSectionList(this,ml.get());
    }
  }
}
References AUTO_TRACE, Class, Config_getBool, m_impl, Definition::name(), DefinitionMixin< ClassDefMutable >::name(), MemberDefMutable::setSectionList(), and toMemberDefMutable().
Referenced by internalInsertMember().
addQualifiers()
void ClassDefImpl::addQualifiers (const StringVector & qualifiers) override virtual
Implements ClassDefMutable.
Definition at line 5179 of file classdef.cpp.
{
  for (const auto &sx : qualifiers)
  {
    bool alreadyAdded = std::find(m_impl->qualifiers.begin(), m_impl->qualifiers.end(), sx) != m_impl->qualifiers.end();
    if (!alreadyAdded)
    {
      m_impl->qualifiers.push_back(sx);
    }
  }
}
References m_impl.
addTypeConstraint()
void ClassDefImpl::addTypeConstraint (const QCString & typeConstraint, const QCString & type) private
Definition at line 3375 of file classdef.cpp.
{
  //printf("addTypeConstraint(%s,%s)\n",qPrint(type),qPrint(typeConstraint));
  bool hideUndocRelation = Config_getBool(HIDE_UNDOC_RELATIONS);
  if (typeConstraint.isEmpty() || type.isEmpty()) return;
  SymbolResolver resolver(getFileDef());
  ClassDefMutable *cd = resolver.resolveClassMutable(this,typeConstraint);
  if (cd==nullptr && !hideUndocRelation)
  {
    cd = toClassDefMutable(
           Doxygen::hiddenClassLinkedMap->add(typeConstraint,
             std::unique_ptr<ClassDef>(
               new ClassDefImpl(
                 getDefFileName(),getDefLine(),
                 getDefColumn(),
                 typeConstraint,
                 ClassDef::Class))));
    if (cd)
    {
      cd->setUsedOnly(TRUE);
      cd->setLanguage(getLanguage());
      //printf("Adding undocumented constraint '%s' to class %s on type %s\n",
      //       qPrint(typeConstraint),qPrint(name()),qPrint(type));
    }
  }
  if (cd)
  {
    auto it = std::find_if(m_impl->constraintClassList.begin(),
                           m_impl->constraintClassList.end(),
                           [&cd](const auto &ccd) { return ccd.classDef==cd; });
    if (it==m_impl->constraintClassList.end())
    {
      m_impl->constraintClassList.emplace_back(cd);
      it = m_impl->constraintClassList.end()-1;
    }
    (*it).addAccessor(type);
    //printf("Adding constraint '%s' to class %s on type %s\n",
    //       qPrint(typeConstraint),qPrint(name()),qPrint(type));
  }
}
References ClassDef::Class, ClassDefImpl(), Config_getBool, DefinitionMixin< ClassDefMutable >::getDefColumn(), DefinitionMixin< ClassDefMutable >::getDefFileName(), DefinitionMixin< ClassDefMutable >::getDefLine(), getFileDef(), DefinitionMixin< ClassDefMutable >::getLanguage(), Doxygen::hiddenClassLinkedMap, QCString::isEmpty(), m_impl, SymbolResolver::resolveClassMutable(), DefinitionMutable::setLanguage(), ClassDefMutable::setUsedOnly(), toClassDefMutable(), and TRUE.
Referenced by addTypeConstraints().
addTypeConstraints()
void ClassDefImpl::addTypeConstraints () override virtual
Implements ClassDefMutable.
Definition at line 3418 of file classdef.cpp.
{
  for (const Argument &a : m_impl->tempArgs)
  {
    if (!a.typeConstraint.isEmpty())
    {
      QCString typeConstraint;
      int i=0,p=0;
      while ((i=a.typeConstraint.find('&',p))!=-1) // typeConstraint="A &I" for C<T extends A & I>
      {
        typeConstraint = a.typeConstraint.mid(p,i-p).stripWhiteSpace();
        addTypeConstraint(typeConstraint,a.type);
        p=i+1;
      }
      typeConstraint = a.typeConstraint.right(a.typeConstraint.length()-p).stripWhiteSpace();
      addTypeConstraint(typeConstraint,a.type);
    }
  }
}
References addTypeConstraint(), QCString::find(), QCString::isEmpty(), QCString::length(), m_impl, QCString::mid(), QCString::right(), QCString::stripWhiteSpace(), Argument::type, and Argument::typeConstraint.
addUsedByClass()
void ClassDefImpl::addUsedByClass (ClassDef * cd, const QCString & accessName, Protection prot) override virtual
Implements ClassDefMutable.
Definition at line 4105 of file classdef.cpp.
{
  bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  bool umlLook = Config_getBool(UML_LOOK);
  if (prot==Protection::Private && !extractPrivate) return;
  //printf("%s::addUsedByClass(%s,%s)\n",qPrint(name()),qPrint(cd->name()),accessName);
  //
  auto it = std::find_if(m_impl->usedByImplClassList.begin(),
                         m_impl->usedByImplClassList.end(),
                         [&cd](const auto &ucd) { return ucd.classDef==cd; });
  if (it==m_impl->usedByImplClassList.end())
  {
     m_impl->usedByImplClassList.emplace_back(cd);
     //printf("Adding used by class %s to class %s\n",
     //    qPrint(cd->name()),qPrint(name()));
     it = m_impl->usedByImplClassList.end()-1;
  }
  QCString acc = accessName;
  if (umlLook)
  {
    switch(prot)
    {
      case Protection::Public:    acc.prepend("+"); break;
      case Protection::Private:   acc.prepend("-"); break;
      case Protection::Protected: acc.prepend("#"); break;
      case Protection::Package:   acc.prepend("~"); break;
    }
  }
  (*it).addAccessor(acc);
}
References Config_getBool, m_impl, Package, QCString::prepend(), Private, Protected, and Public.
addUsedClass()
void ClassDefImpl::addUsedClass (ClassDef * cd, const QCString & accessName, Protection prot) override virtual
Implements ClassDefMutable.
Definition at line 4073 of file classdef.cpp.
{
  bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  bool umlLook = Config_getBool(UML_LOOK);
  if (prot==Protection::Private && !extractPrivate) return;
  //printf("%s::addUsedClass(%s,%s)\n",qPrint(name()),qPrint(cd->name()),accessName);
  auto it = std::find_if(m_impl->usesImplClassList.begin(),
                         m_impl->usesImplClassList.end(),
                         [&cd](const auto &ucd) { return ucd.classDef==cd; });
  if (it==m_impl->usesImplClassList.end())
  {
    m_impl->usesImplClassList.emplace_back(cd);
    //printf("Adding used class %s to class %s via accessor %s\n",
    //    qPrint(cd->name()),qPrint(name()),accessName);
    it = m_impl->usesImplClassList.end()-1;
  }
  QCString acc = accessName;
  if (umlLook)
  {
    switch(prot)
    {
      case Protection::Public:    acc.prepend("+"); break;
      case Protection::Private:   acc.prepend("-"); break;
      case Protection::Protected: acc.prepend("#"); break;
      case Protection::Package:   acc.prepend("~"); break;
    }
  }
  (*it).addAccessor(acc);
}
References Config_getBool, m_impl, Package, QCString::prepend(), Private, Protected, and Public.
addUsedInterfaceClasses()
void ClassDefImpl::addUsedInterfaceClasses (MemberDef * md, const QCString & typeStr) private
References anchor(), and title().
anchor()
QCString ClassDefImpl::anchor () const override virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 5103 of file classdef.cpp.
{
  QCString anc;
  if (isEmbeddedInOuterScope() && !Doxygen::generatingXmlOutput)
  {
    if (m_impl->templateMaster)
    {
      // point to the template of which this class is an instance
      anc = m_impl->templateMaster->getOutputFileBase();
    }
    else
    {
      anc = m_impl->fileName;
    }
  }
  return anc;
}
References Doxygen::generatingXmlOutput, isEmbeddedInOuterScope(), and m_impl.
Referenced by addExample(), addUsedInterfaceClasses(), writeBriefDescription(), writeDeclarationLink(), writeDetailedDescription(), writeInlineDocumentation(), writeMemberList(), writeMoreLink(), and writeTagFile().
baseClasses()
const BaseClassList & ClassDefImpl::baseClasses () const override virtual
Returns the list of base classes from which this class directly inherits.
Implements ClassDef.
Definition at line 4858 of file classdef.cpp.
{
  return m_impl->inherits;
}
References m_impl.
Referenced by isBaseClass(), mergeMembers(), and mergeMembersFromBaseClasses().
categoryOf()
ClassDef * ClassDefImpl::categoryOf () const override virtual
Returns the class of which this is a category (Objective-C only)
Implements ClassDef.
Definition at line 5008 of file classdef.cpp.
{
  return m_impl->categoryOf;
}
References m_impl.
className()
QCString ClassDefImpl::className () const override virtual
Returns the name of the class including outer classes, but not including namespaces.
Implements ClassDef.
Definition at line 4395 of file classdef.cpp.
{
  if (m_impl->className.isEmpty())
  {
    return localName();
  }
  else
  {
    return m_impl->className;
  }
}
References DefinitionMixin< ClassDefMutable >::localName(), and m_impl.
codeSymbolType()
CodeSymbolType ClassDefImpl::codeSymbolType () const override virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 5282 of file classdef.cpp.
{
  switch (compoundType())
  {
    case Class:     return CodeSymbolType::Class;     break;
    case Struct:    return CodeSymbolType::Struct;    break;
    case Union:     return CodeSymbolType::Union;     break;
    case Interface: return CodeSymbolType::Interface; break;
    case Protocol:  return CodeSymbolType::Protocol;  break;
    case Category:  return CodeSymbolType::Category;  break;
    case Exception: return CodeSymbolType::Exception; break;
    case Service:   return CodeSymbolType::Service;   break;
    case Singleton: return CodeSymbolType::Singleton; break;
  }
  return CodeSymbolType::Class;
}
References ClassDef::Category, Category, ClassDef::Class, Class, compoundType(), ClassDef::Exception, Exception, ClassDef::Interface, Interface, ClassDef::Protocol, Protocol, ClassDef::Service, Service, ClassDef::Singleton, Singleton, ClassDef::Struct, Struct, ClassDef::Union, and Union.
collaborationGraphFileName()
QCString ClassDefImpl::collaborationGraphFileName () const override virtual
returns the file name to use for the collaboration graph
Implements ClassDef.
Definition at line 5262 of file classdef.cpp.
{
  return m_impl->collabFileName;
}
References m_impl.
compoundType()
ClassDefImpl::CompoundType ClassDefImpl::compoundType () const override virtual
Returns the type of compound this is, i.e.
class/struct/union/..
Implements ClassDef.
Definition at line 4853 of file classdef.cpp.
{
  return m_impl->compType;
}
References m_impl.
Referenced by addListReferences(), codeSymbolType(), deepCopy(), writeDeclarationLink(), writeDocumentation(), and writeMemberList().
compoundTypeString()
QCString ClassDefImpl::compoundTypeString () const override virtual
Returns the type of compound as a string.
Implements ClassDef.
Definition at line 4138 of file classdef.cpp.
{
  return getCompoundTypeString(getLanguage(),m_impl->compType,isJavaEnum());
}
References getCompoundTypeString(), DefinitionMixin< ClassDefMutable >::getLanguage(), isJavaEnum(), and m_impl.
Referenced by writeDeclaration(), writeDeclarationLink(), writeDetailedDocumentationBody(), writeDocumentationContents(), writeInlineDocumentation(), and writeTagFile().
computeAnchors()
void ClassDefImpl::computeAnchors () override virtual
Implements ClassDefMutable.
Definition at line 1352 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    if (!ml->listType().isDetailed())
    {
      ml->setAnchors();
    }
  }
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->setAnchors();
  }
}
References m_impl.
containsOverload()
bool ClassDefImpl::containsOverload (const MemberDef * md) const override virtual
Implements ClassDef.
Definition at line 5196 of file classdef.cpp.
{
  AUTO_TRACE("name={}",md->name());
  const auto &mni = m_impl->allMemberNameInfoLinkedMap.find(md->name());
  if (mni)
  {
    for (const auto &mi : *mni)
    {
      const MemberDef *classMd = mi->memberDef();
      const ArgumentList &classAl = classMd->argumentList();
      const ArgumentList &al      = md->argumentList();
      bool found = matchArguments2(
          classMd->getOuterScope(),classMd->getFileDef(),&classAl,
          md->getOuterScope(),md->getFileDef(),&al,
          true,getLanguage()
          );
      if (found)
      {
        AUTO_TRACE_EXIT("true");
        return true;
      }
    }
  }
  AUTO_TRACE_EXIT("false");
  return false;
}
References MemberDef::argumentList(), AUTO_TRACE, AUTO_TRACE_EXIT, found, MemberDef::getFileDef(), Definition::getLanguage(), Definition::getOuterScope(), m_impl, matchArguments2(), and Definition::name().
countAdditionalInheritedMembers()
int ClassDefImpl::countAdditionalInheritedMembers () const private
Definition at line 4653 of file classdef.cpp.
{
  int totalCount=0;
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd && lmd->type!=MemberListType::Friends()) // friendship is not inherited
      {
        ClassDefSet visited;
        totalCount+=countInheritedDecMembers(lmd->type,this,TRUE,FALSE,visited);
      }
    }
  }
  //printf("countAdditionalInheritedMembers()=%d\n",totalCount);
  return totalCount;
}
References countInheritedDecMembers(), FALSE, LayoutDocManager::instance(), TRUE, and LayoutDocEntryMemberDecl::type.
Referenced by endMemberDeclarations().
countInheritanceNodes()
int ClassDefImpl::countInheritanceNodes () const private
Definition at line 1819 of file classdef.cpp.
{
  return countInheritedByNodes()+countInheritsNodes();
}
References countInheritedByNodes(), and countInheritsNodes().
Referenced by writeInheritanceGraph().
countInheritedByNodes()
int ClassDefImpl::countInheritedByNodes () const private
Definition at line 1797 of file classdef.cpp.
{
  int count=0;
  for (const auto &ibcd : m_impl->inheritedBy)
  {
    const ClassDef *icd=ibcd.classDef;
    if ( icd->isVisibleInHierarchy()) count++;
  }
  return count;
}
References ClassDef::isVisibleInHierarchy(), and m_impl.
Referenced by countInheritanceNodes(), and writeInheritanceGraph().
countInheritedDecMembers()
int ClassDefImpl::countInheritedDecMembers (MemberListType lt, const ClassDef * inheritedFrom, bool invert, bool showAlways, ClassDefSet & visitedClasses) const private
Definition at line 4597 of file classdef.cpp.
{
  int inhCount = 0;
  int count = countMembersIncludingGrouped(lt,inheritedFrom,FALSE);
  bool process = count>0;
  //printf("%s: countInheritedDecMembers: lt=%d process=%d count=%d invert=%d\n",
  //    qPrint(name()),lt.to_int(),process,count,invert);
  if ((process^invert) || showAlways)
  {
    for (const auto &ibcd : m_impl->inherits)
    {
      ClassDefMutable *icd = toClassDefMutable(ibcd.classDef);
      MemberListType lt1 = MemberListType::Invalid();
      MemberListType lt2 = MemberListType::Invalid();
      if (icd && icd->isLinkable())
      {
        convertProtectionLevel(lt,ibcd.prot,&lt1,&lt2);
        //printf("%s: convert %d->(%d,%d) prot=%d\n",
        //    qPrint(icd->name()),lt.to_int(),lt1.to_int(),lt2.to_int(),ibcd.prot);
        if (visitedClasses.find(icd)==visitedClasses.end())
        {
          visitedClasses.insert(icd); // guard for multiple virtual inheritance
          if (!lt1.isInvalid())
          {
            inhCount+=icd->countMemberDeclarations(lt1,inheritedFrom,lt2,FALSE,TRUE,visitedClasses);
          }
        }
      }
    }
  }
  return inhCount;
}
References convertProtectionLevel(), ClassDef::countMemberDeclarations(), countMembersIncludingGrouped(), FALSE, MemberListType::Invalid(), MemberListType::isInvalid(), Definition::isLinkable(), m_impl, toClassDefMutable(), and TRUE.
Referenced by countAdditionalInheritedMembers(), and countMemberDeclarations().
countInheritsNodes()
int ClassDefImpl::countInheritsNodes () const private
Definition at line 1808 of file classdef.cpp.
{
  int count=0;
  for (const auto &ibcd : m_impl->inherits)
  {
    const ClassDef *icd=ibcd.classDef;
    if ( icd->isVisibleInHierarchy()) count++;
  }
  return count;
}
References ClassDef::isVisibleInHierarchy(), and m_impl.
Referenced by countInheritanceNodes(), and writeInheritanceGraph().
countMemberDeclarations()
int ClassDefImpl::countMemberDeclarations (MemberListType lt, const ClassDef * inheritedFrom, MemberListType lt2, bool invert, bool showAlways, ClassDefSet & visitedClasses) const override virtual
Implements ClassDef.
Definition at line 4519 of file classdef.cpp.
{
  //printf("%s: countMemberDeclarations for %d and %d\n",qPrint(name()),lt.to_int(),lt2.to_int());
  int count=0;
  MemberList * ml  = getMemberList(lt);
  MemberList * ml2 = getMemberList(lt2);
  if (getLanguage()!=SrcLangExt::VHDL) // use specific declarations function
  {
    if (ml)
    {
      count+=ml->numDecMembers();
      //printf("-> ml=%d\n",ml->numDecMembers());
    }
    if (ml2)
    {
      count+=ml2->numDecMembers();
      //printf("-> ml2=%d\n",ml2->numDecMembers());
    }
    // also include grouped members that have their own section in the class (see bug 722759)
    if (inheritedFrom)
    {
      for (const auto &mg : m_impl->memberGroups)
      {
        count+=mg->countGroupedInheritedMembers(lt);
        if (!lt2.isInvalid()) count+=mg->countGroupedInheritedMembers(lt2);
      }
    }
    bool inlineInheritedMembers = Config_getBool(INLINE_INHERITED_MEMB);
    if (!inlineInheritedMembers) // show inherited members as separate lists
    {
      count+=countInheritedDecMembers(lt,inheritedFrom,invert,showAlways,visitedClasses);
    }
  }
  //printf("-> %d\n",count);
  return count;
}
References Config_getBool, countInheritedDecMembers(), DefinitionMixin< ClassDefMutable >::getLanguage(), getMemberList(), MemberListType::isInvalid(), m_impl, MemberList::numDecMembers(), and VHDL.
countMembers()
void ClassDefImpl::countMembers () override virtual
Implements ClassDefMutable.
Definition at line 4583 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    ml->countDecMembers();
    ml->countDocMembers();
  }
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->countDecMembers();
    mg->countDocMembers();
  }
}
References m_impl.
countMembersIncludingGrouped()
int ClassDefImpl::countMembersIncludingGrouped (MemberListType lt, const ClassDef * inheritedFrom, bool additional) const override virtual
Implements ClassDef.
Definition at line 4689 of file classdef.cpp.
{
  int count=0;
  MemberList *ml = getMemberList(lt);
  if (ml)
  {
    count=ml->countInheritableMembers(inheritedFrom);
  }
  //printf("%s:countMembersIncludingGrouped: count=%d\n",qPrint(name()),count);
  for (const auto &mg : m_impl->memberGroups)
  {
    bool hasOwnSection = !mg->allMembersInSameSection() ||
                         !m_impl->subGrouping; // group is in its own section
    if ((additional && hasOwnSection) || (!additional && !hasOwnSection))
    {
      count+=mg->countGroupedInheritedMembers(lt);
    }
  }
  //printf("%s:countMembersIncludingGrouped(lt=%s,%s)=%d\n",
  //    qPrint(name()),qPrint(lt.to_string()),ml?qPrint(ml->listType().toLabel()):"<none>",count);
  return count;
}
References MemberList::countInheritableMembers(), getMemberList(), and m_impl.
Referenced by countInheritedDecMembers(), and writeInheritedMemberDeclarations().
deepCopy()
std::unique_ptr< ClassDef > ClassDefImpl::deepCopy (const QCString & name) const override virtual
Implements ClassDef.
Definition at line 933 of file classdef.cpp.
{
  AUTO_TRACE("name='{}'",name);
  auto result = std::make_unique<ClassDefImpl>(
        getDefFileName(),getDefLine(),getDefColumn(),name,compoundType(),
        std::string(),std::string(),true,m_impl->isJavaEnum);
  // copy other members
  result->m_impl = m_impl->deepCopy();
  // set new file name
  QCString compTypeString = getCompoundTypeString(getLanguage(),m_impl->compType,m_impl->isJavaEnum);
  result->m_impl->fileName = compTypeString+name;
  result->m_impl->memberListFileName = convertNameToFile(compTypeString+name+"-members");
  result->m_impl->collabFileName = convertNameToFile(result->m_impl->fileName+"_coll_graph");
  result->m_impl->inheritFileName = convertNameToFile(result->m_impl->fileName+"_inherit_graph");
  result->m_impl->fileName = convertNameToFile(result->m_impl->fileName);
  // deep copy nested classes
  for (const auto &innerCd : m_impl->innerClasses)
  {
    QCString innerName = name+"::"+innerCd->localName();
    if (Doxygen::classLinkedMap->find(innerName)==nullptr)
    {
      auto cd = Doxygen::classLinkedMap->add(innerName,innerCd->deepCopy(innerName));
      result->addInnerCompound(cd);
      ClassDefMutable *cdm = toClassDefMutable(cd);
      if (cdm)
      {
        cdm->setOuterScope(result.get());
      }
    }
  }
  // copy all member list (and make deep copies of members)
  for (auto &mni : m_impl->allMemberNameInfoLinkedMap)
  {
    for (auto &mi : *mni)
    {
      const MemberDef *md=mi->memberDef();
      auto newMd = md->deepCopy();
      if (newMd)
      {
        auto mmd = toMemberDefMutable(newMd.get());
        AUTO_TRACE_ADD("Copying member {}",mmd->name());
        mmd->moveTo(result.get());
        result->internalInsertMember(newMd.get(),newMd->protection(),true);
        // also add to the global list (which will own newMd)
        MemberName *mn = Doxygen::memberNameLinkedMap->add(newMd->name());
        mn->push_back(std::move(newMd));
      }
    }
  }
  return result;
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), AUTO_TRACE, AUTO_TRACE_ADD, Doxygen::classLinkedMap, compoundType(), convertNameToFile(), MemberDef::deepCopy(), getCompoundTypeString(), DefinitionMixin< ClassDefMutable >::getDefColumn(), DefinitionMixin< ClassDefMutable >::getDefFileName(), DefinitionMixin< ClassDefMutable >::getDefLine(), DefinitionMixin< ClassDefMutable >::getLanguage(), m_impl, Doxygen::memberNameLinkedMap, Definition::name(), MemberName::push_back(), DefinitionMutable::setOuterScope(), toClassDefMutable(), and toMemberDefMutable().
definitionType()
DefType ClassDefImpl::definitionType () const inline override virtual
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Definition at line 193 of file classdef.cpp.
{ return TypeClass; }
References Definition::TypeClass.
displayName()
QCString ClassDefImpl::displayName (bool includeScope = TRUE) const override virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 1010 of file classdef.cpp.
{
  return makeDisplayName(this,includeScope);
}
References makeDisplayName().
Referenced by addListReferences(), title(), writeCollaborationGraph(), writeDeclaration(), writeDeclarationLink(), writeDocumentation(), writeInheritanceGraph(), writeMemberDocumentation(), writeMemberList(), writeMemberPages(), and writeTagFile().
distributeMemberGroupDocumentation()
void ClassDefImpl::distributeMemberGroupDocumentation () override virtual
Implements ClassDefMutable.
Definition at line 1368 of file classdef.cpp.
{
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->distributeMemberGroupDocumentation();
  }
}
References m_impl.
endMemberDeclarations()
void ClassDefImpl::endMemberDeclarations (OutputList & ol) const private
Definition at line 2214 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::endMemberDeclarations()\n",qPrint(name()));
  bool inlineInheritedMembers = Config_getBool(INLINE_INHERITED_MEMB);
  if (!inlineInheritedMembers && countAdditionalInheritedMembers()>0)
  {
    ol.startMemberHeader("inherited");
    ol.parseText(theTranslator->trAdditionalInheritedMembers());
    ol.endMemberHeader();
    writeAdditionalInheritedMembers(ol);
  }
  ol.endMemberSections();
}
References Config_getBool, countAdditionalInheritedMembers(), OutputList::endMemberHeader(), OutputList::endMemberSections(), OutputList::parseText(), OutputList::startMemberHeader(), theTranslator, Translator::trAdditionalInheritedMembers(), and writeAdditionalInheritedMembers().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
endMemberDocumentation()
void ClassDefImpl::endMemberDocumentation (OutputList & ol) const private
Definition at line 2198 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::endMemberDocumentation()\n",qPrint(name()));
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.enable(OutputType::Html);
    Doxygen::suppressDocWarnings = FALSE;
  }
}
References Config_getBool, OutputList::enable(), FALSE, Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
findInnerCompound()
const Definition * ClassDefImpl::findInnerCompound (const QCString & name) const override virtual
Implements Definition.
Definition at line 4227 of file classdef.cpp.
{
  return m_impl->innerClasses.find(name);
}
References m_impl, and Definition::name().
findSectionsInDocumentation()
void ClassDefImpl::findSectionsInDocumentation () override virtual
Implements ClassDefMutable.
Definition at line 1376 of file classdef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
  docFindSections(inbodyDocumentation(),this,docFile());
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->findSectionsInDocumentation(this);
  }
  for (auto &ml : m_impl->memberLists)
  {
    if (!ml->listType().isDetailed())
    {
      ml->findSectionsInDocumentation(this);
    }
  }
}
References DefinitionMixin< ClassDefMutable >::briefDescription(), DefinitionMixin< ClassDefMutable >::docFile(), docFindSections(), DefinitionMixin< ClassDefMutable >::documentation(), DefinitionMixin< ClassDefMutable >::inbodyDocumentation(), and m_impl.
generatedFromFiles()
QCString ClassDefImpl::generatedFromFiles () const override virtual
Implements ClassDef.
Definition at line 1687 of file classdef.cpp.
{
  QCString result;
  SrcLangExt lang = getLanguage();
  size_t numFiles = m_impl->files.size();
  if (lang==SrcLangExt::Fortran)
  {
    result = theTranslator->trGeneratedFromFilesFortran(
          getLanguage()==SrcLangExt::ObjC && m_impl->compType==Interface ? Class : m_impl->compType,
          numFiles==1);
  }
  else if (isJavaEnum())
  {
    result = theTranslator->trEnumGeneratedFromFiles(numFiles==1);
  }
  else if (m_impl->compType==Service)
  {
    result = theTranslator->trServiceGeneratedFromFiles(numFiles==1);
  }
  else if (m_impl->compType==Singleton)
  {
    result = theTranslator->trSingletonGeneratedFromFiles(numFiles==1);
  }
  else
  {
    result = theTranslator->trGeneratedFromFiles(
          getLanguage()==SrcLangExt::ObjC && m_impl->compType==Interface ? Class : m_impl->compType,
          numFiles==1);
  }
  return result;
}
References ClassDef::Class, Fortran, DefinitionMixin< ClassDefMutable >::getLanguage(), ClassDef::Interface, isJavaEnum(), m_impl, ObjC, ClassDef::Service, ClassDef::Singleton, theTranslator, Translator::trEnumGeneratedFromFiles(), Translator::trGeneratedFromFiles(), Translator::trGeneratedFromFilesFortran(), Translator::trServiceGeneratedFromFiles(), and Translator::trSingletonGeneratedFromFiles().
Referenced by showUsedFiles().
getClasses()
ClassLinkedRefMap ClassDefImpl::getClasses () const override virtual
returns the classes nested into this class
Implements ClassDef.
Definition at line 4848 of file classdef.cpp.
{
  return m_impl->innerClasses;
}
References m_impl.
getExamples()
const ExampleList & ClassDefImpl::getExamples () const override virtual
Implements ClassDef.
Definition at line 5242 of file classdef.cpp.
{
  return m_impl->examples;
}
References m_impl.
getFileDef()
FileDef * ClassDefImpl::getFileDef () const override virtual
Returns the namespace this compound is in, or 0 if it has a global scope.
Returns the file in which this compound's definition can be found. Should not return 0 (but it might be a good idea to check anyway).
Implements ClassDef.
Definition at line 4903 of file classdef.cpp.
{
  return m_impl->fileDef;
}
References m_impl.
Referenced by addTypeConstraint(), getOutputFileBase(), isEmbeddedInOuterScope(), and writeTemplateSpec().
getInstanceOutputFileBase()
QCString ClassDefImpl::getInstanceOutputFileBase () const override virtual
Implements ClassDef.
Definition at line 4180 of file classdef.cpp.
{
  return m_impl->fileName;
}
References m_impl.
getMemberByName()
const MemberDef * ClassDefImpl::getMemberByName (const QCString &) const override virtual
Returns the member with the given name.
Implements ClassDef.
Definition at line 4441 of file classdef.cpp.
{
  const MemberDef *xmd = nullptr;
  MemberNameInfo *mni = m_impl->allMemberNameInfoLinkedMap.find(name);
  if (mni)
  {
    const int maxInheritanceDepth = 100000;
    int mdist=maxInheritanceDepth;
    for (auto &mi : *mni)
    {
      const ClassDef *mcd=mi->memberDef()->getClassDef();
      int m=minClassDistance(this,mcd);
      //printf("found member in %s linkable=%d m=%d\n",
      //    qPrint(mcd->name()),mcd->isLinkable(),m);
      if (m<mdist)
      {
        mdist=m;
        xmd=mi->memberDef();
      }
    }
  }
  //printf("getMemberByName(%s)=%p\n",qPrint(name),xmd);
  return xmd;
}
References m_impl, maxInheritanceDepth, minClassDistance(), and Definition::name().
getMemberGroups()
const MemberGroupList & ClassDefImpl::getMemberGroups () const override virtual
Returns the member groups defined for this class.
Implements ClassDef.
Definition at line 5018 of file classdef.cpp.
{
  return m_impl->memberGroups;
}
References m_impl.
getMemberList()
MemberList * ClassDefImpl::getMemberList (MemberListType lt) const override virtual
Returns the members in the list identified by lt.
Implements ClassDef.
Definition at line 4471 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    if (ml->listType()==lt)
    {
      return ml.get();
    }
  }
  return nullptr;
}
References m_impl.
Referenced by countMemberDeclarations(), countMembersIncludingGrouped(), setAnonymousEnumType(), writeMemberDeclarations(), writeMemberDocumentation(), writePlainMemberDeclaration(), writeSimpleMemberDocumentation(), writeSummaryLinks(), and writeTagFile().
getMemberListFileName()
QCString ClassDefImpl::getMemberListFileName () const override virtual
Implements ClassDef.
Definition at line 1005 of file classdef.cpp.
{
  return m_impl->memberListFileName;
}
References m_impl.
Referenced by writeMemberList(), and writeSummaryLinks().
getMemberLists()
const MemberLists & ClassDefImpl::getMemberLists () const override virtual
Returns the list containing the list of members sorted per type.
Implements ClassDef.
Definition at line 5013 of file classdef.cpp.
{
  return m_impl->memberLists;
}
References m_impl.
getModuleDef()
ModuleDef * ClassDefImpl::getModuleDef () const override virtual
Returns the C++20 module in which this compound's definition can be found.
Implements ClassDef.
Definition at line 4908 of file classdef.cpp.
{
  return m_impl->moduleDef;
}
References m_impl.
getOutputFileBase()
QCString ClassDefImpl::getOutputFileBase () const override virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 4143 of file classdef.cpp.
{
  bool inlineGroupedClasses = Config_getBool(INLINE_GROUPED_CLASSES);
  bool inlineSimpleClasses = Config_getBool(INLINE_SIMPLE_STRUCTS);
  if (!Doxygen::generatingXmlOutput)
  {
    Definition *scope=nullptr;
    if (inlineGroupedClasses && !partOfGroups().empty())
    {
      // point to the group that embeds this class
      return partOfGroups().front()->getOutputFileBase();
    }
    else if (inlineSimpleClasses && m_impl->isSimple && !partOfGroups().empty())
    {
      // point to simple struct inside a group
      return partOfGroups().front()->getOutputFileBase();
    }
    else if (inlineSimpleClasses && m_impl->isSimple && (scope=getOuterScope()))
    {
      if (scope==Doxygen::globalScope && getFileDef() && getFileDef()->isLinkableInProject()) // simple struct embedded in file
      {
        return getFileDef()->getOutputFileBase();
      }
      else if (scope->isLinkableInProject()) // simple struct embedded in other container (namespace/group/class)
      {
        return getOuterScope()->getOutputFileBase();
      }
    }
  }
  if (m_impl->templateMaster)
  {
    // point to the template of which this class is an instance
    return m_impl->templateMaster->getOutputFileBase();
  }
  return m_impl->fileName;
}
References Config_getBool, Doxygen::generatingXmlOutput, getFileDef(), Definition::getOuterScope(), DefinitionMixin< ClassDefMutable >::getOuterScope(), Definition::getOutputFileBase(), Doxygen::globalScope, isLinkableInProject(), Definition::isLinkableInProject(), m_impl, Definition::partOfGroups(), and DefinitionMixin< ClassDefMutable >::partOfGroups().
Referenced by addListReferences(), writeDeclarationLink(), writeDetailedDescription(), writeDocumentation(), writeInheritanceGraph(), writeInlineDocumentation(), writeMemberList(), writeMoreLink(), and writeTagFile().
getQualifiers()
StringVector ClassDefImpl::getQualifiers () const override virtual
Implements ClassDef.
Definition at line 5191 of file classdef.cpp.
{
  return m_impl->qualifiers;
}
References m_impl.
getReference()
QCString ClassDefImpl::getReference () const override virtual
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Implements Definition.
Definition at line 4349 of file classdef.cpp.
{
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->getReference();
  }
  else
  {
    return DefinitionMixin::getReference();
  }
}
References DefinitionMixin< Base >::getReference(), and m_impl.
Referenced by writeDeclarationLink(), and writeMemberList().
getSourceFileBase()
QCString ClassDefImpl::getSourceFileBase () const override virtual
Returns the name of the source listing of this definition.
Implements Definition.
Definition at line 4185 of file classdef.cpp.
{
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->getSourceFileBase();
  }
  else
  {
    return DefinitionMixin::getSourceFileBase();
  }
}
References DefinitionMixin< Base >::getSourceFileBase(), and m_impl.
getTemplateBaseClassNames()
const TemplateNameMap & ClassDefImpl::getTemplateBaseClassNames () const override virtual
Implements ClassDef.
Definition at line 4303 of file classdef.cpp.
{
  return m_impl->templBaseClassNames;
}
References m_impl.
getTemplateInstances()
const TemplateInstanceList & ClassDefImpl::getTemplateInstances () const override virtual
Returns a sorted dictionary with all template instances found for this template class.
Returns 0 if not a template or no instances.
Implements ClassDef.
Definition at line 4913 of file classdef.cpp.
{
  return m_impl->templateInstances;
}
References m_impl.
getTemplateParameterLists()
ArgumentLists ClassDefImpl::getTemplateParameterLists () const override virtual
Returns the template parameter lists that form the template declaration of this class.
Example: template<class T> class TC {} = 0; will return a list with one ArgumentList containing one argument with type="class" and name="T".
Implements ClassDef.
Definition at line 4373 of file classdef.cpp.
{
  ArgumentLists result;
  Definition *d=getOuterScope();
  while (d && d->definitionType()==Definition::TypeClass)
  {
    result.insert(result.begin(),toClassDef(d)->templateArguments());
    d = d->getOuterScope();
  }
  if (!templateArguments().empty())
  {
    result.push_back(templateArguments());
  }
  return result;
}
References Definition::definitionType(), Definition::getOuterScope(), DefinitionMixin< ClassDefMutable >::getOuterScope(), templateArguments(), toClassDef(), and Definition::TypeClass.
getTitleForMemberListType()
void ClassDefImpl::getTitleForMemberListType (MemberListType type, QCString & title, QCString & subtitle) const private
Definition at line 4632 of file classdef.cpp.
{
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd && lmd->type==type)
      {
        title = lmd->title(lang);
        subtitle = lmd->subtitle(lang);
        return;
      }
    }
  }
  title="";
  subtitle="";
}
References DefinitionMixin< ClassDefMutable >::getLanguage(), LayoutDocManager::instance(), LayoutDocEntryMemberDecl::subtitle(), title(), LayoutDocEntryMemberDecl::title(), and LayoutDocEntryMemberDecl::type.
hasCollaborationGraph()
bool ClassDefImpl::hasCollaborationGraph () const override virtual
Implements ClassDefMutable.
Definition at line 5304 of file classdef.cpp.
{
  return m_impl->hasCollaborationGraph;
}
References m_impl.
hasDetailedDescription()
bool ClassDefImpl::hasDetailedDescription () const override virtual
returns TRUE if this class has a non-empty detailed description
Implements ClassDef.
Definition at line 1641 of file classdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
  return ((!briefDescription().isEmpty() && repeatBrief) ||
          !documentation().isEmpty() ||
          (sourceBrowser && getStartBodyLine()!=-1 && getBodyDef()));
}
References DefinitionMixin< ClassDefMutable >::briefDescription(), Config_getBool, DefinitionMixin< ClassDefMutable >::documentation(), DefinitionMixin< ClassDefMutable >::getBodyDef(), and DefinitionMixin< ClassDefMutable >::getStartBodyLine().
Referenced by writeBriefDescription(), and writeDetailedDescription().
hasDocumentation()
bool ClassDefImpl::hasDocumentation () const override virtual
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Implements Definition.
Definition at line 3618 of file classdef.cpp.
{
  return DefinitionMixin::hasDocumentation();
}
References DefinitionMixin< Base >::hasDocumentation().
Referenced by isLinkableInProject(), and isVisibleInHierarchy().
hasExamples()
bool ClassDefImpl::hasExamples () const override virtual
Implements ClassDef.
Definition at line 3370 of file classdef.cpp.
{
  return !m_impl->examples.empty();
}
References m_impl.
Referenced by writeDetailedDocumentationBody(), and writeDocumentationContents().
hasInheritanceGraph()
CLASS_GRAPH_t ClassDefImpl::hasInheritanceGraph () const override virtual
Implements ClassDefMutable.
Definition at line 5277 of file classdef.cpp.
{
  return m_impl->typeInheritanceGraph;
}
References m_impl.
hasNonReferenceSuperClass()
bool ClassDefImpl::hasNonReferenceSuperClass () const override virtual
Returns TRUE iff this class or a class inheriting from this class is not defined in an external tag file.
Implements ClassDef.
Definition at line 3487 of file classdef.cpp.
{
  return hasNonReferenceSuperClassRec(this,0);
}
References hasNonReferenceSuperClassRec().
Referenced by isVisibleInHierarchy().
includeInfo()
const IncludeInfo * ClassDefImpl::includeInfo () const override virtual
Implements ClassDef.
Definition at line 4938 of file classdef.cpp.
{
  return m_impl->incInfo.get();
}
References m_impl.
inheritanceGraphFileName()
QCString ClassDefImpl::inheritanceGraphFileName () const override virtual
returns the file name to use for the inheritance graph
Implements ClassDef.
Definition at line 5267 of file classdef.cpp.
{
  return m_impl->inheritFileName;
}
References m_impl.
insertBaseClass()
void ClassDefImpl::insertBaseClass (ClassDef * cd, const QCString & name, Protection p, Specifier s, const QCString & t = QCString()) override virtual
Implements ClassDefMutable.
Definition at line 1016 of file classdef.cpp.
{
  //printf("*** insert base class %s into %s\n",qPrint(cd->name()),qPrint(name()));
  m_impl->inherits.emplace_back(cd,n,p,s,t);
  m_impl->isSimple = FALSE;
}
References FALSE, and m_impl.
Referenced by mergeCategory().
insertExplicitTemplateInstance()
void ClassDefImpl::insertExplicitTemplateInstance (ClassDef * instance, const QCString & spec) override virtual
Implements ClassDefMutable.
Definition at line 4293 of file classdef.cpp.
{
  m_impl->templateInstances.emplace_back(templSpec,templateClass);
}
References m_impl.
insertMember()
void ClassDefImpl::insertMember (MemberDef * md) override virtual
Implements ClassDefMutable.
Definition at line 1346 of file classdef.cpp.
{
  internalInsertMember(md,md->protection(),TRUE);
}
References internalInsertMember(), MemberDef::protection(), and TRUE.
Referenced by addMembersToTemplateInstance(), and reclassifyMember().
insertSubClass()
void ClassDefImpl::insertSubClass (ClassDef * cd, Protection p, Specifier s, const QCString & t = QCString()) override virtual
Implements ClassDefMutable.
Definition at line 1025 of file classdef.cpp.
{
  //printf("*** insert sub class %s into %s\n",qPrint(cd->name()),qPrint(name()));
  bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  if (!extractPrivate && cd->protection()==Protection::Private) return;
  m_impl->inheritedBy.emplace_back(cd,QCString(),p,s,t);
  m_impl->isSimple = FALSE;
}
References Config_getBool, FALSE, m_impl, Private, and ClassDef::protection().
insertTemplateInstance()
ClassDef * ClassDefImpl::insertTemplateInstance (const QCString & fileName, int startLine, int startColumn, const QCString & templSpec, bool & freshInstance) const override virtual
Implements ClassDef.
Definition at line 4232 of file classdef.cpp.
{
  freshInstance = FALSE;
  auto it = std::find_if(m_impl->templateInstances.begin(),
                         m_impl->templateInstances.end(),
                         [&templSpec](const auto &ti) { return templSpec==ti.templSpec; });
  ClassDefMutable *templateClass=nullptr;
  if (it!=m_impl->templateInstances.end())
  {
    templateClass = toClassDefMutable((*it).classDef);
  }
  if (templateClass==nullptr)
  {
    QCString tcname = removeRedundantWhiteSpace(name()+templSpec);
    AUTO_TRACE("New template instance class name='{}' templSpec='{}' inside '{}' hidden={}",
        name(),templSpec,name(),isHidden());
    ClassDef *foundCd = Doxygen::classLinkedMap->find(tcname);
    if (foundCd)
    {
      return foundCd;
    }
    templateClass =
      toClassDefMutable(
          Doxygen::classLinkedMap->add(tcname,
            std::unique_ptr<ClassDef>(
              new ClassDefImpl(fileName,startLine,startColumn,tcname,ClassDef::Class))));
    if (templateClass)
    {
      templateClass->setTemplateMaster(this);
      templateClass->setOuterScope(getOuterScope());
      templateClass->setHidden(isHidden());
      templateClass->setArtificial(isArtificial());
      templateClass->setImplicitTemplateInstance(true);
      m_impl->templateInstances.emplace_back(templSpec,templateClass);
      // also add nested classes
      for (const auto &innerCd : m_impl->innerClasses)
      {
        QCString innerName = tcname+"::"+innerCd->localName();
        ClassDefMutable *innerClass =
          toClassDefMutable(
              Doxygen::classLinkedMap->add(innerName,
                std::unique_ptr<ClassDef>(
                  new ClassDefImpl(fileName,startLine,startColumn,innerName,ClassDef::Class))));
        if (innerClass)
        {
          templateClass->addInnerCompound(innerClass);
          innerClass->setOuterScope(templateClass);
          innerClass->setHidden(isHidden());
          innerClass->setArtificial(TRUE);
          innerClass->setImplicitTemplateInstance(true);
        }
      }
      freshInstance=TRUE;
    }
  }
  return templateClass;
}
References DefinitionMutable::addInnerCompound(), AUTO_TRACE, ClassDef::Class, ClassDefImpl(), Doxygen::classLinkedMap, FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), DefinitionMixin< ClassDefMutable >::getOuterScope(), DefinitionMixin< ClassDefMutable >::isArtificial(), DefinitionMixin< ClassDefMutable >::isHidden(), m_impl, DefinitionMixin< ClassDefMutable >::name(), removeRedundantWhiteSpace(), DefinitionMutable::setArtificial(), DefinitionMutable::setHidden(), ClassDefMutable::setImplicitTemplateInstance(), DefinitionMutable::setOuterScope(), ClassDefMutable::setTemplateMaster(), toClassDefMutable(), and TRUE.
insertUsedFile()
void ClassDefImpl::insertUsedFile (const FileDef * fd) override virtual
Implements ClassDefMutable.
Definition at line 1396 of file classdef.cpp.
{
  if (fd==nullptr) return;
  auto it = std::find(m_impl->files.begin(),m_impl->files.end(),fd);
  if (it==m_impl->files.end())
  {
    m_impl->files.push_back(fd);
  }
  for (const auto &ti : m_impl->templateInstances)
  {
    ClassDefMutable *cdm = toClassDefMutable(ti.classDef);
    if (cdm)
    {
      cdm->insertUsedFile(fd);
    }
  }
}
References ClassDefMutable::insertUsedFile(), m_impl, and toClassDefMutable().
internalInsertMember()
void ClassDefImpl::internalInsertMember (MemberDef * md, Protection prot, bool addToAllList) private
isReference()
Definition at line 1057 of file classdef.cpp.
{
  AUTO_TRACE("{} name={} isHidden={}",name(),md->name(),md->isHidden());
  if (md->isHidden()) return;
  if (getLanguage()==SrcLangExt::VHDL)
  {
    QCString title=theTranslator->trVhdlType(md->getVhdlSpecifiers(),FALSE);
    m_impl->vhdlSummaryTitles.insert(title.str());
  }
  if (1 /*!isReference()*/) // changed to 1 for showing members of external
                            // classes when HAVE_DOT and UML_LOOK are enabled.
  {
    bool isSimple=FALSE;
    /********************************************/
    /* insert member in the declaration section */
    /********************************************/
    if (md->isRelated() && protectionLevelVisible(prot))
    {
      addMemberToList(MemberListType::Related(),md,TRUE);
    }
    else if (md->isFriend())
    {
      addMemberToList(MemberListType::Friends(),md,TRUE);
    }
    else
    {
      switch (md->memberType())
      {
        case MemberType::Service: // UNO IDL
          addMemberToList(MemberListType::Services(),md,TRUE);
          break;
        case MemberType::Interface: // UNO IDL
          addMemberToList(MemberListType::Interfaces(),md,TRUE);
          break;
        case MemberType::Signal: // Qt specific
          addMemberToList(MemberListType::Signals(),md,TRUE);
          break;
        case MemberType::DCOP:   // KDE2 specific
          addMemberToList(MemberListType::DcopMethods(),md,TRUE);
          break;
        case MemberType::Property:
          addMemberToList(MemberListType::Properties(),md,TRUE);
          break;
        case MemberType::Event:
          addMemberToList(MemberListType::Events(),md,TRUE);
          break;
        case MemberType::Slot:   // Qt specific
          switch (prot)
          {
            case Protection::Protected:
            case Protection::Package: // slots in packages are not possible!
              addMemberToList(MemberListType::ProSlots(),md,TRUE);
              break;
            case Protection::Public:
              addMemberToList(MemberListType::PubSlots(),md,TRUE);
              break;
            case Protection::Private:
              addMemberToList(MemberListType::PriSlots(),md,TRUE);
              break;
          }
          break;
        default: // any of the other members
          if (md->isStatic())
          {
            if (md->isVariable())
            {
              switch (prot)
              {
                case Protection::Protected:
                  addMemberToList(MemberListType::ProStaticAttribs(),md,TRUE);
                  break;
                case Protection::Package:
                  addMemberToList(MemberListType::PacStaticAttribs(),md,TRUE);
                  break;
                case Protection::Public:
                  addMemberToList(MemberListType::PubStaticAttribs(),md,TRUE);
                  break;
                case Protection::Private:
                  addMemberToList(MemberListType::PriStaticAttribs(),md,TRUE);
                  break;
              }
            }
            else // function
            {
              switch (prot)
              {
                case Protection::Protected:
                  addMemberToList(MemberListType::ProStaticMethods(),md,TRUE);
                  break;
                case Protection::Package:
                  addMemberToList(MemberListType::PacStaticMethods(),md,TRUE);
                  break;
                case Protection::Public:
                  addMemberToList(MemberListType::PubStaticMethods(),md,TRUE);
                  break;
                case Protection::Private:
                  addMemberToList(MemberListType::PriStaticMethods(),md,TRUE);
                  break;
              }
            }
          }
          else // not static
          {
            if (md->isVariable())
            {
              switch (prot)
              {
                case Protection::Protected:
                  addMemberToList(MemberListType::ProAttribs(),md,TRUE);
                  break;
                case Protection::Package:
                  addMemberToList(MemberListType::PacAttribs(),md,TRUE);
                  break;
                case Protection::Public:
                  addMemberToList(MemberListType::PubAttribs(),md,TRUE);
                  isSimple=TRUE;
                  break;
                case Protection::Private:
                  addMemberToList(MemberListType::PriAttribs(),md,TRUE);
                  break;
              }
            }
            else if (md->isTypedef() || md->isEnumerate() || md->isEnumValue())
            {
              switch (prot)
              {
                case Protection::Protected:
                  addMemberToList(MemberListType::ProTypes(),md,TRUE);
                  break;
                case Protection::Package:
                  addMemberToList(MemberListType::PacTypes(),md,TRUE);
                  break;
                case Protection::Public:
                  addMemberToList(MemberListType::PubTypes(),md,TRUE);
                  isSimple=!md->isEnumerate() &&
                           !md->isEnumValue() &&
                           QCString(md->typeString()).find(")(")==-1; // func ptr typedef
                  break;
                case Protection::Private:
                  addMemberToList(MemberListType::PriTypes(),md,TRUE);
                  break;
              }
            }
            else // member function
            {
              switch (prot)
              {
                case Protection::Protected:
                  addMemberToList(MemberListType::ProMethods(),md,TRUE);
                  break;
                case Protection::Package:
                  addMemberToList(MemberListType::PacMethods(),md,TRUE);
                  break;
                case Protection::Public:
                  addMemberToList(MemberListType::PubMethods(),md,TRUE);
                  break;
                case Protection::Private:
                  addMemberToList(MemberListType::PriMethods(),md,TRUE);
                  break;
              }
            }
          }
          break;
      }
    }
    if (!isSimple) // not a simple field -> not a simple struct
    {
      m_impl->isSimple = FALSE;
    }
    //printf("adding %s simple=%d total_simple=%d\n",qPrint(name()),isSimple,m_impl->isSimple);
    /*******************************************************/
    /* insert member in the detailed documentation section */
    /*******************************************************/
    if ((md->isRelated() && protectionLevelVisible(prot)) || md->isFriend())
    {
      addMemberToList(MemberListType::RelatedMembers(),md,FALSE);
    }
    else if (md->isFunction() &&
             md->protection()==Protection::Private &&
             (md->virtualness()!=Specifier::Normal || md->isOverride() || md->isFinal()) &&
             Config_getBool(EXTRACT_PRIV_VIRTUAL))
    {
      addMemberToList(MemberListType::FunctionMembers(),md,FALSE);
    }
    else
    {
      switch (md->memberType())
      {
        case MemberType::Service: // UNO IDL
          addMemberToList(MemberListType::ServiceMembers(),md,FALSE);
          break;
        case MemberType::Interface: // UNO IDL
          addMemberToList(MemberListType::InterfaceMembers(),md,FALSE);
          break;
        case MemberType::Property:
          addMemberToList(MemberListType::PropertyMembers(),md,FALSE);
          break;
        case MemberType::Event:
          addMemberToList(MemberListType::EventMembers(),md,FALSE);
          break;
        case MemberType::Signal: // fall through
        case MemberType::DCOP:
          addMemberToList(MemberListType::FunctionMembers(),md,FALSE);
          break;
        case MemberType::Slot:
          if (protectionLevelVisible(prot))
          {
            addMemberToList(MemberListType::FunctionMembers(),md,FALSE);
          }
          break;
        default: // any of the other members
          if (protectionLevelVisible(prot))
          {
            switch (md->memberType())
            {
              case MemberType::Typedef:
                addMemberToList(MemberListType::TypedefMembers(),md,FALSE);
                break;
              case MemberType::Enumeration:
                addMemberToList(MemberListType::EnumMembers(),md,FALSE);
                break;
              case MemberType::EnumValue:
                addMemberToList(MemberListType::EnumValMembers(),md,FALSE);
                break;
              case MemberType::Function:
                if (md->isConstructor() || md->isDestructor())
                {
                  m_impl->memberLists.get(MemberListType::Constructors(),MemberListContainer::Class)->push_back(md);
                }
                else
                {
                  addMemberToList(MemberListType::FunctionMembers(),md,FALSE);
                }
                break;
              case MemberType::Variable:
                addMemberToList(MemberListType::VariableMembers(),md,FALSE);
                break;
              case MemberType::Define:
                warn(md->getDefFileName(),md->getDefLine()-1,"A define (%s) cannot be made a member of %s",
                     qPrint(md->name()), qPrint(this->name()));
                break;
              default:
                err("Unexpected member type '%s' found!\n",qPrint(md->memberTypeName()));
            }
          }
          break;
      }
    }
    /*************************************************/
    /* insert member in the appropriate member group */
    /*************************************************/
    // Note: this must be done AFTER inserting the member in the
    // regular groups
    //addMemberToGroup(md,groupId);
  }
  if (md->virtualness()==Specifier::Pure)
  {
    m_impl->isAbstract=true;
  }
  if (md->name()=="operator->")
  {
    m_impl->arrowOperator=md;
  }
  if (addToAllList &&
      !(Config_getBool(HIDE_FRIEND_COMPOUNDS) &&
        md->isFriend() &&
        (QCString(md->typeString())=="friend class" ||
         QCString(md->typeString())=="friend struct" ||
         QCString(md->typeString())=="friend union")))
  {
    //printf("=======> adding member %s to class %s\n",qPrint(md->name()),qPrint(name()));
    MemberNameInfo *mni = m_impl->allMemberNameInfoLinkedMap.add(md->name());
    mni->push_back(std::make_unique<MemberInfo>(md,prot,md->virtualness(),false,false));
  }
}
References addMemberToList(), AUTO_TRACE, Class, Config_getBool, DCOP, Define, Enumeration, EnumValue, err, Event, FALSE, Function, Definition::getDefFileName(), Definition::getDefLine(), DefinitionMixin< ClassDefMutable >::getLanguage(), MemberDef::getVhdlSpecifiers(), Interface, MemberDef::isConstructor(), MemberDef::isDestructor(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFinal(), MemberDef::isFriend(), MemberDef::isFunction(), Definition::isHidden(), MemberDef::isOverride(), MemberDef::isRelated(), isSimple(), MemberDef::isStatic(), MemberDef::isTypedef(), MemberDef::isVariable(), m_impl, MemberDef::memberType(), MemberDef::memberTypeName(), Definition::name(), DefinitionMixin< ClassDefMutable >::name(), Normal, Package, Private, Property, Protected, MemberDef::protection(), protectionLevelVisible(), Public, Pure, MemberNameInfo::push_back(), qPrint(), Service, Signal, Slot, theTranslator, title(), TRUE, Translator::trVhdlType(), Typedef, MemberDef::typeString(), Variable, VHDL, MemberDef::virtualness(), and warn.
Referenced by insertMember(), mergeCategory(), and mergeMembersFromBaseClasses().
isAbstract()
bool ClassDefImpl::isAbstract () const override virtual
Returns TRUE if there is at least one pure virtual member in this class.
Implements ClassDef.
Definition at line 4963 of file classdef.cpp.
{
  return m_impl->isAbstract || m_impl->spec.isAbstract();
}
References m_impl.
Referenced by addClassAttributes().
isAccessibleMember()
bool ClassDefImpl::isAccessibleMember (const MemberDef * md) const override virtual
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
Implements ClassDef.
Definition at line 4466 of file classdef.cpp.
{
  return md->getClassDef() && isBaseClass(md->getClassDef(),TRUE,QCString());
}
References MemberDef::getClassDef(), isBaseClass(), and TRUE.
isBaseClass()
int ClassDefImpl::isBaseClass (const ClassDef * bcd, bool followInstances, const QCString & templSpec) const override virtual
Returns TRUE iff bcd is a direct or indirect base class of this class.
This function will recursively traverse all branches of the inheritance tree.
Implements ClassDef.
Definition at line 3628 of file classdef.cpp.
{
  int distance=0;
  //printf("isBaseClass(cd=%s) looking for %s templSpec=%s\n",qPrint(name()),qPrint(bcd->name()),qPrint(templSpec));
  for (const auto &bclass : baseClasses())
  {
    const ClassDef *ccd = bclass.classDef;
    if (!followInstances && ccd->templateMaster())
    {
      ccd=ccd->templateMaster();
    }
    if (ccd==bcd && (templSpec.isEmpty() || templSpec==bclass.templSpecifiers))
    {
      distance=1;
      break; // no shorter path possible
    }
    else
    {
      int d = ccd->isBaseClass(bcd,followInstances,templSpec);
      if (d>256)
      {
        err("Possible recursive class relation while inside %s and looking for base class %s\n",qPrint(name()),qPrint(bcd->name()));
        return 0;
      }
      else if (d>0) // path found
      {
        if (distance==0 || d+1<distance) // update if no path found yet or shorter path found
        {
          distance=d+1;
        }
      }
    }
  }
  return distance;
}
References baseClasses(), err, ClassDef::isBaseClass(), QCString::isEmpty(), Definition::name(), DefinitionMixin< ClassDefMutable >::name(), qPrint(), and ClassDef::templateMaster().
Referenced by isAccessibleMember().
isCSharp()
bool ClassDefImpl::isCSharp () const override virtual
Returns TRUE if this class is implemented in C#.
Implements ClassDef.
Definition at line 5003 of file classdef.cpp.
{
  return getLanguage()==SrcLangExt::CSharp;
}
References CSharp, and DefinitionMixin< ClassDefMutable >::getLanguage().
isEmbeddedInOuterScope()
bool ClassDefImpl::isEmbeddedInOuterScope () const override virtual
Implements ClassDef.
Definition at line 5121 of file classdef.cpp.
{
  bool inlineGroupedClasses = Config_getBool(INLINE_GROUPED_CLASSES);
  bool inlineSimpleClasses = Config_getBool(INLINE_SIMPLE_STRUCTS);
  Definition *container = getOuterScope();
  bool containerLinkable =
    container &&
       (
        (container==Doxygen::globalScope && getFileDef() && getFileDef()->isLinkableInProject()) || // global class in documented file
        container->isLinkableInProject() // class in documented scope
       );
  // inline because of INLINE_GROUPED_CLASSES=YES ?
  bool b1 = (inlineGroupedClasses && !partOfGroups().empty()); // a grouped class
  // inline because of INLINE_SIMPLE_STRUCTS=YES ?
  bool b2 = (inlineSimpleClasses && m_impl->isSimple && // a simple class
             (containerLinkable || // in a documented container
              !partOfGroups().empty()    // or part of a group
             )
           );
  //printf("%s::isEmbeddedInOuterScope(): inlineGroupedClasses=%d "
  //       "inlineSimpleClasses=%d partOfGroups()=%p m_impl->isSimple=%d "
  //       "getOuterScope()=%s b1=%d b2=%d\n",
  //    qPrint(name()),inlineGroupedClasses,inlineSimpleClasses,
  //    partOfGroups().pointer(),m_impl->isSimple,getOuterScope()?qPrint(getOuterScope()->name()):"<none>",b1,b2);
  return b1 || b2;  // either reason will do
}
References Config_getBool, getFileDef(), DefinitionMixin< ClassDefMutable >::getOuterScope(), Doxygen::globalScope, Definition::isLinkableInProject(), m_impl, and DefinitionMixin< ClassDefMutable >::partOfGroups().
Referenced by anchor().
isExtension()
bool ClassDefImpl::isExtension () const override virtual
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
Implements ClassDef.
Definition at line 5223 of file classdef.cpp.
{
  QCString n = name();
  int si = n.find('(');
  int ei = n.find(')');
  bool b = ei>si && n.mid(si+1,ei-si-1).stripWhiteSpace().isEmpty();
  return b;
}
References QCString::find(), QCString::isEmpty(), QCString::mid(), DefinitionMixin< ClassDefMutable >::name(), and QCString::stripWhiteSpace().
Referenced by mergeCategory(), and visibleInParentsDeclList().
isFinal()
bool ClassDefImpl::isFinal () const override virtual
Returns TRUE if this class is marked as final.
Implements ClassDef.
Definition at line 4968 of file classdef.cpp.
{
  return m_impl->spec.isFinal();
}
References m_impl.
Referenced by addClassAttributes().
isFortran()
bool ClassDefImpl::isFortran () const override virtual
Returns TRUE if this class is implemented in Fortran.
Implements ClassDef.
Definition at line 4998 of file classdef.cpp.
{
  return getLanguage()==SrcLangExt::Fortran;
}
References Fortran, and DefinitionMixin< ClassDefMutable >::getLanguage().
Referenced by writeTagFile().
isForwardDeclared()
bool ClassDefImpl::isForwardDeclared () const override virtual
Returns TRUE if this class represents a forward declaration of a template class.
Implements ClassDef.
Definition at line 4983 of file classdef.cpp.
{
  return m_impl->spec.isForwardDecl();
}
References m_impl.
isImplicitTemplateInstance()
bool ClassDefImpl::isImplicitTemplateInstance () const override virtual
Implements ClassDef.
Definition at line 4923 of file classdef.cpp.
{
  return m_impl->implicitTemplateInstance;
}
References m_impl.
isInterface()
bool ClassDefImpl::isInterface () const override virtual
Returns TRUE if this class represents an interface.
Implements ClassDef.
Definition at line 4988 of file classdef.cpp.
{
  return m_impl->spec.isInterface();
}
References m_impl.
isJavaEnum()
bool ClassDefImpl::isJavaEnum () const override virtual
Implements ClassDef.
Definition at line 5169 of file classdef.cpp.
{
  return m_impl->isJavaEnum;
}
References m_impl.
Referenced by ClassDefImpl(), compoundTypeString(), generatedFromFiles(), and title().
isLinkable()
bool ClassDefImpl::isLinkable () const override virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 3582 of file classdef.cpp.
{
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->isLinkable();
  }
  else
  {
    return isReference() || isLinkableInProject();
  }
}
References isLinkableInProject(), isReference(), and m_impl.
Referenced by visibleInParentsDeclList(), writeDeclaration(), and writeDeclarationLink().
isLinkableInProject()
bool ClassDefImpl::isLinkableInProject () const override virtual
a link to this class is possible within this project
Implements Definition.
Definition at line 3550 of file classdef.cpp.
{
  bool extractLocal   = Config_getBool(EXTRACT_LOCAL_CLASSES);
  bool extractStatic  = Config_getBool(EXTRACT_STATIC);
  bool hideUndoc      = Config_getBool(HIDE_UNDOC_CLASSES);
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->isLinkableInProject();
  }
  else
  {
    //printf("%s::isLinkableInProject() conditions: artificial=%d hidden=%d anonymous=%d protection=%d local=%d docs=%d static=%d ref=%d\n",
    //      qPrint(name()),
    //      !isArtificial(),
    //      !isHidden(),
    //      !isAnonymous(),
    //      m_impl->prot,
    //      !m_impl->isLocal   || extractLocal,
    //      hasDocumentation() || !hideUndoc,
    //      !m_impl->isStatic  || extractStatic,
    //      !isReference());
    return
      !isArtificial() && !isHidden() &&            /* not hidden */
      !isAnonymous() &&                            /* not anonymous */
      protectionLevelVisible(m_impl->prot)      && /* private/internal */
      (!m_impl->isLocal      || extractLocal)   && /* local */
      (hasDocumentation()    || !hideUndoc)     && /* documented */
      (!m_impl->isStatic     || extractStatic)  && /* static */
      !isReference();                              /* not an external reference */
  }
}
References Config_getBool, hasDocumentation(), DefinitionMixin< ClassDefMutable >::isAnonymous(), DefinitionMixin< ClassDefMutable >::isArtificial(), DefinitionMixin< ClassDefMutable >::isHidden(), isReference(), m_impl, and protectionLevelVisible().
Referenced by addListReferences(), getOutputFileBase(), isLinkable(), writeDeclarationLink(), and writeTagFile().
isLocal()
bool ClassDefImpl::isLocal () const override virtual
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES.
Implements ClassDef.
Definition at line 4843 of file classdef.cpp.
{
  return m_impl->isLocal;
}
References m_impl.
Referenced by visibleInParentsDeclList().
isObjectiveC()
bool ClassDefImpl::isObjectiveC () const override virtual
Returns TRUE if this class is implemented in Objective-C.
Implements ClassDef.
Definition at line 4993 of file classdef.cpp.
{
  return getLanguage()==SrcLangExt::ObjC;
}
References DefinitionMixin< ClassDefMutable >::getLanguage(), and ObjC.
Referenced by writeTagFile().
isPublished()
bool ClassDefImpl::isPublished () const override virtual
Returns TRUE if this class is marked as published.
Implements ClassDef.
Definition at line 4978 of file classdef.cpp.
{
  return m_impl->spec.isPublished();
}
References m_impl.
Referenced by addClassAttributes().
isReference()
bool ClassDefImpl::isReference () const override virtual
Returns TRUE if this definition is imported via a tag file.
Implements Definition.
Definition at line 4361 of file classdef.cpp.
{
  if (m_impl->templateMaster)
  {
    return m_impl->templateMaster->isReference();
  }
  else
  {
    return DefinitionMixin::isReference();
  }
}
References DefinitionMixin< Base >::isReference(), and m_impl.
Referenced by isLinkable(), isLinkableInProject(), and isVisibleInHierarchy().
isSealed()
bool ClassDefImpl::isSealed () const override virtual
Returns TRUE if this class is marked as sealed.
Implements ClassDef.
Definition at line 4973 of file classdef.cpp.
{
  return m_impl->spec.isSealed();
}
References m_impl.
Referenced by addClassAttributes().
isSimple()
bool ClassDefImpl::isSimple () const override virtual
Implements ClassDef.
Definition at line 5083 of file classdef.cpp.
{
  return m_impl->isSimple;
}
References m_impl.
Referenced by internalInsertMember(), and writeInlineDocumentation().
isSliceLocal()
bool ClassDefImpl::isSliceLocal () const override virtual
Implements ClassDef.
Definition at line 5252 of file classdef.cpp.
{
  return m_impl->spec.isLocal();
}
References m_impl.
Referenced by title(), and writeDeclarationLink().
isSmartPointer()
const MemberDef * ClassDefImpl::isSmartPointer () const override virtual
Implements ClassDef.
Definition at line 5088 of file classdef.cpp.
{
  return m_impl->arrowOperator;
}
References m_impl.
isSubClass()
bool ClassDefImpl::isSubClass (ClassDef * bcd, int level = 0) const override virtual
Returns TRUE iff bcd is a direct or indirect sub class of this class.
Implements ClassDef.
Definition at line 3666 of file classdef.cpp.
{
  bool found=FALSE;
  if (level>256)
  {
    err("Possible recursive class relation while inside %s and looking for derived class %s\n",qPrint(name()),qPrint(cd->name()));
    return FALSE;
  }
  for (const auto &iscd : subClasses())
  {
    ClassDef *ccd=iscd.classDef;
    found = (ccd==cd) || ccd->isSubClass(cd,level+1);
    if (found) break;
  }
  return found;
}
References err, FALSE, found, ClassDef::isSubClass(), Definition::name(), DefinitionMixin< ClassDefMutable >::name(), qPrint(), and subClasses().
isTemplate()
bool ClassDefImpl::isTemplate () const override virtual
Returns TRUE if this class is a template.
Implements ClassDef.
Definition at line 4933 of file classdef.cpp.
{
  return !m_impl->tempArgs.empty();
}
References m_impl.
isTemplateArgument()
bool ClassDefImpl::isTemplateArgument () const override virtual
Implements ClassDef.
Definition at line 4958 of file classdef.cpp.
{
  return m_impl->isTemplArg;
}
References m_impl.
isUsedOnly()
bool ClassDefImpl::isUsedOnly () const override virtual
Implements ClassDef.
Definition at line 5078 of file classdef.cpp.
{
  return m_impl->usedOnly;
}
References m_impl.
isVisibleInHierarchy()
bool ClassDefImpl::isVisibleInHierarchy () const override virtual
the class is visible in a class diagram, or class hierarchy
Implements ClassDef.
Definition at line 3596 of file classdef.cpp.
{
  bool allExternals     = Config_getBool(ALLEXTERNALS);
  bool hideUndocClasses = Config_getBool(HIDE_UNDOC_CLASSES);
  bool extractStatic    = Config_getBool(EXTRACT_STATIC);
  return // show all classes or a subclass is visible
      ((allExternals && !isArtificial()) || hasNonReferenceSuperClass()) &&
      // and not an anonymous compound
      !isAnonymous() &&
      // and not privately inherited
      protectionLevelVisible(m_impl->prot) &&
      // documented or shown anyway or documentation is external
      (hasDocumentation() ||
       !hideUndocClasses ||
       (m_impl->templateMaster && m_impl->templateMaster->hasDocumentation()) ||
       isReference()
      ) &&
      // is not part of an unnamed namespace or shown anyway
      (!m_impl->isStatic || extractStatic);
}
References Config_getBool, hasDocumentation(), hasNonReferenceSuperClass(), DefinitionMixin< ClassDefMutable >::isAnonymous(), DefinitionMixin< ClassDefMutable >::isArtificial(), isReference(), m_impl, and protectionLevelVisible().
makeTemplateArgument()
void ClassDefImpl::makeTemplateArgument (bool b = TRUE) override virtual
Implements ClassDefMutable.
Definition at line 5063 of file classdef.cpp.
{
  m_impl->isTemplArg = b;
}
References m_impl.
memberNameInfoLinkedMap()
const MemberNameInfoLinkedMap & ClassDefImpl::memberNameInfoLinkedMap () const override virtual
Returns a dictionary of all members.
This includes any inherited members. Members are sorted alphabetically.
Implements ClassDef.
Definition at line 4878 of file classdef.cpp.
{
  return m_impl->allMemberNameInfoLinkedMap;
}
References m_impl.
mergeCategory()
void ClassDefImpl::mergeCategory (ClassDef * cat) override virtual
Merges the members of a Objective-C category into this class.
Implements ClassDefMutable.
Definition at line 3961 of file classdef.cpp.
{
  AUTO_TRACE();
  ClassDefMutable *category = toClassDefMutable(cat);
  if (category)
  {
    bool extractLocalMethods = Config_getBool(EXTRACT_LOCAL_METHODS);
    bool makePrivate = category->isLocal();
    // in case extract local methods is not enabled we don't add the methods
    // of the category in case it is defined in the .m file.
    if (makePrivate && !extractLocalMethods) return;
    bool isExtension = category->isExtension();
    category->setCategoryOf(this);
    if (isExtension)
    {
      category->setArtificial(TRUE);
      // copy base classes/protocols from extension
      for (const auto &bcd : category->baseClasses())
      {
        insertBaseClass(bcd.classDef,bcd.usedName,bcd.prot,bcd.virt,bcd.templSpecifiers);
        // correct bcd.classDef so that they do no longer derive from
        // category, but from this class!
        BaseClassList scl = bcd.classDef->subClasses();
        for (auto &scd : scl)
        {
          if (scd.classDef==category)
          {
            scd.classDef=this;
          }
        }
        bcd.classDef->updateSubClasses(scl);
      }
    }
    // make methods private for categories defined in the .m file
    //printf("%s::mergeCategory makePrivate=%d\n",qPrint(name()),makePrivate);
    const MemberNameInfoLinkedMap &srcMnd  = category->memberNameInfoLinkedMap();
    MemberNameInfoLinkedMap &dstMnd        = m_impl->allMemberNameInfoLinkedMap;
    for (auto &srcMni : srcMnd)
    {
      MemberNameInfo *dstMni=dstMnd.find(srcMni->memberName());
      if (dstMni) // method is already defined in the class
      {
        AUTO_TRACE_ADD("Existing member {}",srcMni->memberName());
        const auto &dstMi = dstMni->front();
        const auto &srcMi = srcMni->front();
        if (srcMi && dstMi)
        {
          MemberDefMutable *smdm = toMemberDefMutable(srcMi->memberDef());
          MemberDefMutable *dmdm = toMemberDefMutable(dstMi->memberDef());
          if (smdm && dmdm)
          {
            combineDeclarationAndDefinition(smdm,dmdm);
            dmdm->setCategory(category);
            dmdm->setCategoryRelation(smdm);
            smdm->setCategoryRelation(dmdm);
          }
        }
      }
      else // new method name
      {
        AUTO_TRACE_ADD("New member {}",srcMni->memberName());
        // create a deep copy of the list
        MemberNameInfo *newMni = dstMnd.add(srcMni->memberName());
        // copy the member(s) from the category to this class
        for (auto &mi : *srcMni)
        {
          //printf("Adding '%s'\n",qPrint(mi->memberDef->name()));
          Protection prot = mi->prot();
          //if (makePrivate) prot = Private;
          auto newMd = mi->memberDef()->deepCopy();
          if (newMd)
          {
            auto mmd = toMemberDefMutable(newMd.get());
            AUTO_TRACE_ADD("Copying member {}",mmd->name());
            mmd->moveTo(this);
            auto newMi=std::make_unique<MemberInfo>(newMd.get(),prot,mi->virt(),mi->inherited(),mi->virtualBaseClass());
            newMi->setScopePath(mi->scopePath());
            newMi->setAmbigClass(mi->ambigClass());
            newMi->setAmbiguityResolutionScope(mi->ambiguityResolutionScope());
            newMni->push_back(std::move(newMi));
            // also add the newly created member to the global members list
            QCString name = newMd->name();
            MemberName *mn = Doxygen::memberNameLinkedMap->add(name);
            mmd->setCategory(category);
            mmd->setCategoryRelation(mi->memberDef());
            auto miMmd = toMemberDefMutable(mi->memberDef());
            if (miMmd) miMmd->setCategoryRelation(newMd.get());
            if (makePrivate || isExtension)
            {
              mmd->makeImplementationDetail();
            }
            internalInsertMember(newMd.get(),prot,FALSE);
            mn->push_back(std::move(newMd));
          }
        }
      }
    }
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), AUTO_TRACE, AUTO_TRACE_ADD, ClassDef::baseClasses(), combineDeclarationAndDefinition(), Config_getBool, FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), MemberNameInfo::front(), insertBaseClass(), internalInsertMember(), ClassDef::isExtension(), isExtension(), ClassDef::isLocal(), m_impl, ClassDef::memberNameInfoLinkedMap(), Doxygen::memberNameLinkedMap, Definition::name(), MemberName::push_back(), MemberNameInfo::push_back(), DefinitionMutable::setArtificial(), MemberDefMutable::setCategory(), ClassDefMutable::setCategoryOf(), MemberDefMutable::setCategoryRelation(), toClassDefMutable(), toMemberDefMutable(), and TRUE.
mergeMembers()
void ClassDefImpl::mergeMembers () override virtual
recursively merges the 'all members' lists of a class base with that of this class. Must only be called for classes without subclasses!
Implements ClassDefMutable.
Definition at line 3927 of file classdef.cpp.
{
  if (m_impl->membersMerged) return;
  if (getLanguage()==SrcLangExt::Python) return; // python does not have member overloading, see issue 8480
  //printf("> %s::mergeMembers()\n",qPrint(name()));
  m_impl->membersMerged=TRUE;
  // first merge the members of the base class recursively
  for (const auto &bcd : baseClasses())
  {
    ClassDefMutable *bClass=toClassDefMutable(bcd.classDef);
    if (bClass)
    {
      // merge the members in the base class of this inheritance branch first
      bClass->mergeMembers();
    }
  }
  // first merge the member that are not inherited via a virtual base class
  // (as this can end up reimplemented via multiple paths, see #10717 for examples)
  mergeMembersFromBaseClasses(false);
  // then process the member that are inherited via a virtual base class to add the
  // ones that are not reimplemented via any path
  mergeMembersFromBaseClasses(true);
  //printf("< %s::mergeMembers()\n",qPrint(name()));
}
References baseClasses(), DefinitionMixin< ClassDefMutable >::getLanguage(), m_impl, ClassDefMutable::mergeMembers(), mergeMembersFromBaseClasses(), Python, toClassDefMutable(), and TRUE.
mergeMembersFromBaseClasses()
void ClassDefImpl::mergeMembersFromBaseClasses (bool mergeVirtualBaseClass) private
Definition at line 3692 of file classdef.cpp.
{
  SrcLangExt lang = getLanguage();
  QCString sep=getLanguageSpecificSeparator(lang,TRUE);
  size_t sepLen = sep.length();
  bool inlineInheritedMembers = Config_getBool(INLINE_INHERITED_MEMB);
  bool extractPrivate         = Config_getBool(EXTRACT_PRIVATE);
  //printf("  mergeMembers for %s mergeVirtualBaseClass=%d\n",qPrint(name()),mergeVirtualBaseClass);
  // the merge the base members with this class' members
  for (const auto &bcd : baseClasses())
  {
    ClassDefMutable *bClass=toClassDefMutable(bcd.classDef);
    if (bClass)
    {
      const MemberNameInfoLinkedMap &srcMnd  = bClass->memberNameInfoLinkedMap();
      MemberNameInfoLinkedMap &dstMnd        = m_impl->allMemberNameInfoLinkedMap;
      for (auto &srcMni : srcMnd)
      {
        MemberNameInfo *dstMni=dstMnd.find(srcMni->memberName());
        if (dstMni)
          // a member with that name is already in the class.
          // the member may hide or reimplement the one in the sub class
          // or there may be another path to the base class that is already
          // visited via another branch in the class hierarchy.
        {
          //printf("    %s hides member name %s\n",qPrint(bClass->name()),qPrint(srcMni->memberName()));
          for (auto &srcMi : *srcMni)
          {
            MemberDef *srcMd = srcMi->memberDef();
            bool found=FALSE;
            bool ambiguous=FALSE;
            bool hidden=FALSE;
            const ClassDef *srcCd = srcMd->getClassDef();
            for (auto &dstMi : *dstMni)
            {
              const MemberDef *dstMd = dstMi->memberDef();
              if (srcMd!=dstMd) // different members
              {
                const ClassDef *dstCd = dstMd->getClassDef();
                //printf("  Is %s a base class of %s?\n",qPrint(srcCd->name()),qPrint(dstCd->name()));
                if (srcCd==dstCd || dstCd->isBaseClass(srcCd,TRUE))
                  // member is in the same or a base class
                {
                  const ArgumentList &srcAl = srcMd->argumentList();
                  const ArgumentList &dstAl = dstMd->argumentList();
                  found=matchArguments2(
                      srcMd->getOuterScope(),srcMd->getFileDef(),&srcAl,
                      dstMd->getOuterScope(),dstMd->getFileDef(),&dstAl,
                      TRUE,getLanguage()
                      );
                  //printf("      Yes, matching (%s<->%s): %d\n",
                  //    qPrint(argListToString(srcMd->argumentList())),
                  //    qPrint(argListToString(dstMd->argumentList())),
                  //    found);
                  hidden = hidden  || !found;
                }
                else // member is in a non base class => multiple inheritance
                     // using the same base class.
                {
                  //printf("       $$ Existing member %s %s add scope %s\n",
                  //    qPrint(dstMi->ambiguityResolutionScope()),
                  //    qPrint(dstMd->name()),
                  //    qPrint(dstMi->scopePath().left(dstMi->scopePath().find("::")+2)));
                  QCString scope=dstMi->scopePath().left(dstMi->scopePath().find(sep)+sepLen);
                  if (scope!=dstMi->ambiguityResolutionScope().left(scope.length()))
                  {
                    dstMi->setAmbiguityResolutionScope(scope+dstMi->ambiguityResolutionScope());
                  }
                  ambiguous=TRUE;
                }
              }
              else // same members
              {
                // do not add if base class is virtual or
                // if scope paths are equal or
                // if base class is an interface (and thus implicitly virtual).
                //printf("      same member found srcMi->virt=%d dstMi->virt=%d\n",srcMi->virt(),dstMi->virt());
                if ((srcMi->virt()!=Specifier::Normal && dstMi->virt()!=Specifier::Normal) ||
                    bClass->name()+sep+srcMi->scopePath() == dstMi->scopePath() ||
                    dstMd->getClassDef()->compoundType()==Interface
                   )
                {
                  found=TRUE;
                }
                else // member can be reached via multiple paths in the
                     // inheritance tree
                {
                  //printf("      $$ Existing member %s %s add scope %s\n",
                  //    qPrint(dstMi->ambiguityResolutionScope()),
                  //    qPrint(dstMd->name()),
                  //    qPrint(dstMi->scopePath().left(dstMi->scopePath().find("::")+2)));
                  QCString scope=dstMi->scopePath().left(dstMi->scopePath().find(sep)+sepLen);
                  if (scope!=dstMi->ambiguityResolutionScope().left(scope.length()))
                  {
                    dstMi->setAmbiguityResolutionScope(dstMi->ambiguityResolutionScope()+scope);
                  }
                  ambiguous=TRUE;
                }
              }
              if (found) break;
            }
            //printf("      member %s::%s hidden %d ambiguous %d srcMi->ambigClass=%p found=%d\n",
            //    qPrint(srcCd->name()),qPrint(srcMd->name()),hidden,ambiguous,
            //    (void*)srcMi->ambigClass(),found);
            // TODO: fix the case where a member is hidden by inheritance
            //       of a member with the same name but with another prototype,
            //       while there is more than one path to the member in the
            //       base class due to multiple inheritance. In this case
            //       it seems that the member is not reachable by prefixing a
            //       scope name either (according to my compiler). Currently,
            //       this case is shown anyway.
            if (!found && srcMd->protection()!=Protection::Private && !srcMd->isFriend() && srcMi->virtualBaseClass()==mergeVirtualBaseClass)
            {
              Protection prot = srcMd->protection();
              if (bcd.prot==Protection::Protected && prot==Protection::Public)
              {
                prot = bcd.prot;
              }
              else if (bcd.prot==Protection::Private)
              {
                prot = bcd.prot;
              }
              if (inlineInheritedMembers)
              {
                if (!isStandardFunc(srcMd))
                {
                  //printf("      %s::insertMember(%s)\n",qPrint(name()),qPrint(srcMd->name()));
                  internalInsertMember(srcMd,prot,FALSE);
                }
              }
              Specifier virt=srcMi->virt();
              if (virt==Specifier::Normal && bcd.virt!=Specifier::Normal) virt=bcd.virt;
              bool virtualBaseClass = bcd.virt!=Specifier::Normal;
              std::unique_ptr<MemberInfo> newMi = std::make_unique<MemberInfo>(srcMd,prot,virt,TRUE,virtualBaseClass);
              newMi->setScopePath(bClass->name()+sep+srcMi->scopePath());
              if (ambiguous)
              {
                //printf("$$ New member %s %s add scope %s::\n",
                //     qPrint(srcMi->ambiguityResolutionScope),
                //     qPrint(srcMd->name()),
                //     qPrint(bClass->name()));
                QCString scope=bClass->name()+sep;
                if (scope!=srcMi->ambiguityResolutionScope().left(scope.length()))
                {
                  newMi->setAmbiguityResolutionScope(scope+srcMi->ambiguityResolutionScope());
                }
              }
              if (hidden)
              {
                if (srcMi->ambigClass()==nullptr)
                {
                  newMi->setAmbigClass(bClass);
                  newMi->setAmbiguityResolutionScope(bClass->name()+sep);
                }
                else
                {
                  newMi->setAmbigClass(srcMi->ambigClass());
                  newMi->setAmbiguityResolutionScope(srcMi->ambigClass()->name()+sep);
                }
              }
              dstMni->push_back(std::move(newMi));
            }
          }
        }
        else // base class has a member that is not in the sub class => copy
        {
          //printf("    %s adds member name %s\n",qPrint(bClass->name()),qPrint(srcMni->memberName()));
          // create a deep copy of the list (only the MemberInfo's will be
          // copied, not the actual MemberDef's)
          MemberNameInfo *newMni = dstMnd.add(srcMni->memberName());
          // copy the member(s) from the base to the sub class
          for (auto &mi : *srcMni)
          {
            if (mi->virtualBaseClass()==mergeVirtualBaseClass && !mi->memberDef()->isFriend()) // don't inherit friends
            {
              Protection prot = mi->prot();
              if (bcd.prot==Protection::Protected)
              {
                if (prot==Protection::Public) prot=Protection::Protected;
              }
              else if (bcd.prot==Protection::Private)
              {
                prot=Protection::Private;
              }
              Specifier virt=mi->virt();
              bool virtualBaseClass = bcd.virt!=Specifier::Normal || mi->virtualBaseClass();
              if (virt==Specifier::Normal && bcd.virt!=Specifier::Normal) virt=bcd.virt;
              //printf("      %s::%s: [mi.prot=%d, bcd.prot=%d => prot=%d], [mi.virt=%d, bcd.virt=%d => virt=%d] virtualBase=%d\n",
              //    qPrint(name()),qPrint(mi->memberDef()->name()),
              //    mi->prot(),bcd.prot,prot,
              //    mi->virt(),bcd.virt,virt,
              //    virtualBaseClass
              //    );
              if (prot!=Protection::Private || extractPrivate)
              {
                if (inlineInheritedMembers)
                {
                  if (!isStandardFunc(mi->memberDef()))
                  {
                    //printf("      %s::insertMember '%s'\n",qPrint(name()),qPrint(mi->memberDef()->name()));
                    internalInsertMember(mi->memberDef(),prot,FALSE);
                  }
                }
                //printf("Adding!\n");
                std::unique_ptr<MemberInfo> newMi = std::make_unique<MemberInfo>(mi->memberDef(),prot,virt,TRUE,virtualBaseClass);
                newMi->setScopePath(bClass->name()+sep+mi->scopePath());
                newMi->setAmbigClass(mi->ambigClass());
                newMi->setAmbiguityResolutionScope(mi->ambiguityResolutionScope());
                newMni->push_back(std::move(newMi));
              }
            }
          }
        }
      }
    }
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), MemberDef::argumentList(), baseClasses(), ClassDef::compoundType(), Config_getBool, FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), found, MemberDef::getClassDef(), MemberDef::getFileDef(), Definition::getLanguage(), DefinitionMixin< ClassDefMutable >::getLanguage(), getLanguageSpecificSeparator(), Definition::getOuterScope(), ClassDef::Interface, internalInsertMember(), ClassDef::isBaseClass(), MemberDef::isFriend(), isStandardFunc(), QCString::left(), QCString::length(), m_impl, matchArguments2(), ClassDef::memberNameInfoLinkedMap(), Definition::name(), Normal, Private, Protected, MemberDef::protection(), Public, MemberNameInfo::push_back(), toClassDefMutable(), and TRUE.
Referenced by mergeMembers().
moveTo()
void ClassDefImpl::moveTo (Definition * scope) override virtual
Implements ClassDef.
Definition at line 991 of file classdef.cpp.
{
  //printf("%s::moveTo(%s)\n",qPrint(name()),qPrint(scope->name()));
  setOuterScope(scope);
  if (scope->definitionType()==Definition::TypeFile)
  {
    m_impl->fileDef = toFileDef(scope);
  }
  else if (scope->definitionType()==Definition::TypeModule)
  {
    m_impl->moduleDef = toModuleDef(scope);
  }
}
References Definition::definitionType(), m_impl, DefinitionMixin< ClassDefMutable >::setOuterScope(), toFileDef(), toModuleDef(), Definition::TypeFile, and Definition::TypeModule.
overrideCollaborationGraph()
void ClassDefImpl::overrideCollaborationGraph (bool e) override virtual
Implements ClassDefMutable.
Definition at line 5299 of file classdef.cpp.
{
  m_impl->hasCollaborationGraph=e;
}
References m_impl.
overrideInheritanceGraph()
void ClassDefImpl::overrideInheritanceGraph (CLASS_GRAPH_t e) override virtual
Implements ClassDefMutable.
Definition at line 5272 of file classdef.cpp.
{
  m_impl->typeInheritanceGraph=e;
}
References m_impl.
protection()
Protection ClassDefImpl::protection () const override virtual
Return the protection level (Public,Protected,Private) in which this compound was found.
Implements ClassDef.
Definition at line 4893 of file classdef.cpp.
{
  return m_impl->prot;
}
References m_impl.
Referenced by visibleInParentsDeclList(), and writeDeclarationLink().
qualifiedNameWithTemplateParameters()
QCString ClassDefImpl::qualifiedNameWithTemplateParameters (const ArgumentLists * actualParams = nullptr, uint32_t * actualParamIndex = nullptr) const override virtual
Implements ClassDef.
Definition at line 4389 of file classdef.cpp.
{
  return makeQualifiedNameWithTemplateParameters(this,actualParams,actualParamIndex);
}
References makeQualifiedNameWithTemplateParameters().
reclassifyMember()
void ClassDefImpl::reclassifyMember (MemberDefMutable * md, MemberType t) override virtual
Implements ClassDefMutable.
Definition at line 5093 of file classdef.cpp.
{
  md->setMemberType(t);
  for (auto &ml : m_impl->memberLists)
  {
    ml->remove(md);
  }
  insertMember(md);
}
References insertMember(), m_impl, and MemberDefMutable::setMemberType().
removeMemberFromLists()
void ClassDefImpl::removeMemberFromLists (MemberDef * md) override virtual
Implements ClassDefMutable.
Definition at line 5161 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    ml->remove(md);
  }
}
References m_impl.
requiresClause()
QCString ClassDefImpl::requiresClause () const override virtual
Implements ClassDef.
Definition at line 3492 of file classdef.cpp.
{
  return m_impl->requiresClause;
}
References m_impl.
setAnonymousEnumType()
void ClassDefImpl::setAnonymousEnumType () override virtual
Implements ClassDefMutable.
Definition at line 4557 of file classdef.cpp.
{
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        MemberList * ml = getMemberList(lmd->type);
        if (ml)
        {
          ml->setAnonymousEnumType();
        }
      }
    }
    else if (lde->kind()==LayoutDocEntry::MemberGroups)
    {
      for (const auto &mg : m_impl->memberGroups)
      {
        mg->setAnonymousEnumType();
      }
    }
  }
}
References getMemberList(), LayoutDocManager::instance(), m_impl, MemberList::setAnonymousEnumType(), and LayoutDocEntryMemberDecl::type.
setCategoryOf()
void ClassDefImpl::setCategoryOf (ClassDef * cd) override virtual
Implements ClassDefMutable.
Definition at line 5068 of file classdef.cpp.
{
  m_impl->categoryOf = cd;
}
References m_impl.
setClassName()
void ClassDefImpl::setClassName (const QCString & name) override virtual
Implements ClassDefMutable.
Definition at line 4407 of file classdef.cpp.
{
  m_impl->className = name;
}
References m_impl, and Definition::name().
setClassSpecifier()
void ClassDefImpl::setClassSpecifier (TypeSpecifier spec) override virtual
Implements ClassDefMutable.
Definition at line 5174 of file classdef.cpp.
{
  m_impl->spec = spec;
}
References m_impl.
setCompoundType()
void ClassDefImpl::setCompoundType (CompoundType t) override virtual
Implements ClassDefMutable.
Definition at line 5052 of file classdef.cpp.
{
  m_impl->compType = t;
}
References m_impl.
setFileDef()
void ClassDefImpl::setFileDef (FileDef * fd) override virtual
Implements ClassDefMutable.
Definition at line 5023 of file classdef.cpp.
{
  m_impl->fileDef = fd;
}
References m_impl.
setGroupDefForAllMembers()
void ClassDefImpl::setGroupDefForAllMembers (GroupDef * g, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs) override virtual
Implements ClassDefMutable.
Definition at line 4197 of file classdef.cpp.
{
  gd->addClass(this);
  //printf("ClassDefImpl::setGroupDefForAllMembers(%s)\n",qPrint(gd->name()));
  for (auto &mni : m_impl->allMemberNameInfoLinkedMap)
  {
    for (auto &mi : *mni)
    {
      MemberDefMutable *md = toMemberDefMutable(mi->memberDef());
      if (md)
      {
        md->setGroupDef(gd,pri,fileName,startLine,hasDocs);
        gd->insertMember(md,TRUE);
        ClassDefMutable *innerClass = toClassDefMutable(md->getClassDefOfAnonymousType());
        if (innerClass) innerClass->setGroupDefForAllMembers(gd,pri,fileName,startLine,hasDocs);
      }
    }
  }
}
References GroupDef::addClass(), MemberDef::getClassDefOfAnonymousType(), GroupDef::insertMember(), m_impl, MemberDefMutable::setGroupDef(), ClassDefMutable::setGroupDefForAllMembers(), toClassDefMutable(), toMemberDefMutable(), and TRUE.
setImplicitTemplateInstance()
void ClassDefImpl::setImplicitTemplateInstance (bool b) override virtual
Implements ClassDefMutable.
Definition at line 4928 of file classdef.cpp.
{
  m_impl->implicitTemplateInstance = b;
}
References m_impl.
setIncludeFile()
void ClassDefImpl::setIncludeFile (FileDef * fd, const QCString & incName, bool local, bool force) override virtual
Implements ClassDefMutable.
Definition at line 1436 of file classdef.cpp.
{
  //printf("ClassDefImpl::setIncludeFile(%p,%s,%d,%d)\n",fd,includeName,local,force);
  if (!m_impl->incInfo) m_impl->incInfo = std::make_unique<IncludeInfo>();
  if ((!includeName.isEmpty() && m_impl->incInfo->includeName.isEmpty()) ||
      (fd!=nullptr && m_impl->incInfo->fileDef==nullptr)
     )
  {
    //printf("Setting file info\n");
    m_impl->incInfo->fileDef     = fd;
    m_impl->incInfo->includeName = includeName;
    m_impl->incInfo->kind        = local ? IncludeKind::IncludeLocal : IncludeKind::IncludeSystem;
  }
  if (force && !includeName.isEmpty())
  {
    m_impl->incInfo->includeName = includeName;
    m_impl->incInfo->kind        = local ? IncludeKind::IncludeLocal : IncludeKind::IncludeSystem;
  }
}
References IncludeLocal, IncludeSystem, QCString::isEmpty(), and m_impl.
setIsStatic()
void ClassDefImpl::setIsStatic (bool b) override virtual
Implements ClassDefMutable.
Definition at line 5047 of file classdef.cpp.
{
  m_impl->isStatic=b;
}
References m_impl.
setMetaData()
void ClassDefImpl::setMetaData (const QCString & md) override virtual
Implements ClassDefMutable.
Definition at line 5257 of file classdef.cpp.
{
  m_impl->metaData = md;
}
References m_impl.
setModuleDef()
void ClassDefImpl::setModuleDef (ModuleDef * mod) override virtual
Implements ClassDefMutable.
Definition at line 5028 of file classdef.cpp.
{
  m_impl->moduleDef = mod;
}
References m_impl.
setProtection()
void ClassDefImpl::setProtection (Protection p) override virtual
Implements ClassDefMutable.
Definition at line 5038 of file classdef.cpp.
{
  m_impl->prot=p;
  if (getLanguage()==SrcLangExt::VHDL && VhdlDocGen::convert(p)==VhdlDocGen::ARCHITECTURECLASS)
  {
    m_impl->className = name();
  }
}
References VhdlDocGen::ARCHITECTURECLASS, VhdlDocGen::convert(), DefinitionMixin< ClassDefMutable >::getLanguage(), m_impl, DefinitionMixin< ClassDefMutable >::name(), and VHDL.
setRequiresClause()
void ClassDefImpl::setRequiresClause (const QCString & req) override virtual
Implements ClassDefMutable.
Definition at line 3497 of file classdef.cpp.
{
  m_impl->requiresClause = req;
}
References m_impl.
setSubGrouping()
void ClassDefImpl::setSubGrouping (bool enabled) override virtual
Implements ClassDefMutable.
Definition at line 5033 of file classdef.cpp.
{
  m_impl->subGrouping = enabled;
}
References m_impl.
setTagLessReference()
void ClassDefImpl::setTagLessReference (const ClassDef * cd) override virtual
Implements ClassDefMutable.
Definition at line 5156 of file classdef.cpp.
{
  m_impl->tagLessRef = cd;
}
References m_impl.
setTemplateArguments()
void ClassDefImpl::setTemplateArguments (const ArgumentList & al) override virtual
Implements ClassDefMutable.
Definition at line 3444 of file classdef.cpp.
{
  m_impl->tempArgs = al;
}
References m_impl.
setTemplateBaseClassNames()
void ClassDefImpl::setTemplateBaseClassNames (const TemplateNameMap & templateNames) override virtual
Implements ClassDefMutable.
Definition at line 4298 of file classdef.cpp.
{
  m_impl->templBaseClassNames = templateNames;
}
References m_impl.
setTemplateMaster()
void ClassDefImpl::setTemplateMaster (const ClassDef * tm) override virtual
Implements ClassDefMutable.
Definition at line 5057 of file classdef.cpp.
{
  assert(tm!=this);
  m_impl->templateMaster=tm;
}
References m_impl.
setTypeConstraints()
void ClassDefImpl::setTypeConstraints (const ArgumentList & al) override virtual
Implements ClassDefMutable.
Definition at line 3439 of file classdef.cpp.
{
  m_impl->typeConstraints = al;
}
References m_impl.
setUsedOnly()
void ClassDefImpl::setUsedOnly (bool b) override virtual
Implements ClassDefMutable.
Definition at line 5073 of file classdef.cpp.
{
  m_impl->usedOnly = b;
}
References m_impl.
showUsedFiles()
void ClassDefImpl::showUsedFiles (OutputList & ol) const private
Definition at line 1719 of file classdef.cpp.
{
  ol.pushGeneratorState();
  ol.disable(OutputType::Man);
  ol.writeRuler();
  ol.pushGeneratorState();
    ol.disableAllBut(OutputType::Docbook);
    ol.startParagraph();
    ol.parseText(generatedFromFiles());
    ol.endParagraph();
  ol.popGeneratorState();
  ol.disable(OutputType::Docbook);
    ol.parseText(generatedFromFiles());
  ol.enable(OutputType::Docbook);
  bool first=TRUE;
  for (const auto &fd : m_impl->files)
  {
    if (first)
    {
      first=FALSE;
      ol.startItemList();
    }
    ol.startItemListItem();
    QCString path=fd->getPath();
    if (Config_getBool(FULL_PATH_NAMES))
    {
      ol.docify(stripFromPath(path));
    }
    QCString fname = fd->name();
    if (!fd->getVersion().isEmpty()) // append version if available
    {
      fname += " (" + fd->getVersion() + ")";
    }
    // for HTML
    ol.pushGeneratorState();
    ol.disableAllBut(OutputType::Html);
    if (fd->generateSourceFile())
    {
      ol.writeObjectLink(QCString(),fd->getSourceFileBase(),QCString(),fname);
    }
    else if (fd->isLinkable())
    {
      ol.writeObjectLink(fd->getReference(),fd->getOutputFileBase(),QCString(),fname);
    }
    else
    {
      ol.startBold();
      ol.docify(fname);
      ol.endBold();
    }
    ol.popGeneratorState();
    // for other output formats
    ol.pushGeneratorState();
    ol.disable(OutputType::Html);
    if (fd->isLinkable())
    {
      ol.writeObjectLink(fd->getReference(),fd->getOutputFileBase(),QCString(),fname);
    }
    else
    {
      ol.docify(fname);
    }
    ol.popGeneratorState();
    ol.endItemListItem();
  }
  if (!first) ol.endItemList();
  ol.popGeneratorState();
}
References Config_getBool, OutputList::disable(), OutputList::disableAllBut(), Docbook, OutputList::docify(), OutputList::enable(), OutputList::endBold(), OutputList::endItemList(), OutputList::endItemListItem(), OutputList::endParagraph(), FALSE, generatedFromFiles(), Html, m_impl, Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startBold(), OutputList::startItemList(), OutputList::startItemListItem(), OutputList::startParagraph(), stripFromPath(), TRUE, OutputList::writeObjectLink(), and OutputList::writeRuler().
Referenced by writeDocumentationContents().
sortAllMembersList()
void ClassDefImpl::sortAllMembersList () override virtual
Implements ClassDefMutable.
Definition at line 4883 of file classdef.cpp.
{
  std::stable_sort(m_impl->allMemberNameInfoLinkedMap.begin(),
            m_impl->allMemberNameInfoLinkedMap.end(),
            [](const auto &m1,const auto &m2)
            {
              return qstricmp_sort(m1->memberName(),m2->memberName())<0;
            });
}
References m_impl.
sortMemberLists()
void ClassDefImpl::sortMemberLists () override virtual
Implements ClassDefMutable.
Definition at line 4503 of file classdef.cpp.
{
  for (auto &ml : m_impl->memberLists)
  {
    if (ml->needsSorting()) { ml->sort(); ml->setNeedsSorting(FALSE); }
  }
  std::stable_sort(m_impl->innerClasses.begin(),
            m_impl->innerClasses.end(),
            [](const auto &c1,const auto &c2)
            {
               return Config_getBool(SORT_BY_SCOPE_NAME)                ?
                      qstricmp_sort(c1->name(),      c2->name()     )<0 :
                      qstricmp_sort(c1->className(), c2->className())<0 ;
            });
}
References FALSE, and m_impl.
startMemberDeclarations()
void ClassDefImpl::startMemberDeclarations (OutputList & ol) const private
Definition at line 2208 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::startMemberDeclarations()\n",qPrint(name()));
  ol.startMemberSections();
}
References OutputList::startMemberSections().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
startMemberDocumentation()
void ClassDefImpl::startMemberDocumentation (OutputList & ol) const private
Definition at line 2188 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::startMemberDocumentation()\n",qPrint(name()));
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.disable(OutputType::Html);
    Doxygen::suppressDocWarnings = TRUE;
  }
}
References Config_getBool, OutputList::disable(), Html, Doxygen::suppressDocWarnings, and TRUE.
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
subClasses()
const BaseClassList & ClassDefImpl::subClasses () const override virtual
Returns the list of sub classes that directly derive from this class.
Implements ClassDef.
Definition at line 4868 of file classdef.cpp.
{
  return m_impl->inheritedBy;
}
References m_impl.
Referenced by isSubClass().
subGrouping()
bool ClassDefImpl::subGrouping () const override virtual
Implements ClassDef.
Definition at line 5247 of file classdef.cpp.
{
  return m_impl->subGrouping;
}
References m_impl.
tagLessReference()
const ClassDef * ClassDefImpl::tagLessReference () const override virtual
Implements ClassDef.
Definition at line 5151 of file classdef.cpp.
{
  return m_impl->tagLessRef;
}
References m_impl.
templateArguments()
const ArgumentList & ClassDefImpl::templateArguments () const override virtual
Returns the template arguments of this class.
Implements ClassDef.
Definition at line 4898 of file classdef.cpp.
{
  return m_impl->tempArgs;
}
References m_impl.
Referenced by addMembersToTemplateInstance(), and getTemplateParameterLists().
templateMaster()
const ClassDef * ClassDefImpl::templateMaster () const override virtual
Returns the template master of which this class is an instance.
Returns 0 if not applicable.
Implements ClassDef.
Definition at line 4918 of file classdef.cpp.
{
  return m_impl->templateMaster;
}
References m_impl.
templateTypeConstraints()
const ConstraintClassList & ClassDefImpl::templateTypeConstraints () const override virtual
Implements ClassDef.
Definition at line 4953 of file classdef.cpp.
{
  return m_impl->constraintClassList;
}
References m_impl.
title()
QCString ClassDefImpl::title () const override virtual
Implements ClassDef.
Definition at line 2884 of file classdef.cpp.
{
  QCString pageTitle;
  SrcLangExt lang = getLanguage();
  if (lang==SrcLangExt::Fortran)
  {
    pageTitle = theTranslator->trCompoundReferenceFortran(displayName(),
              m_impl->compType,
              !m_impl->tempArgs.empty());
  }
  else if (lang==SrcLangExt::Slice)
  {
    pageTitle = theTranslator->trCompoundReferenceSlice(displayName(),
              m_impl->compType,
              isSliceLocal());
  }
  else if (lang==SrcLangExt::VHDL)
  {
    pageTitle = theTranslator->trCustomReference(VhdlDocGen::getClassTitle(this));
  }
  else if (isJavaEnum())
  {
    pageTitle = theTranslator->trEnumReference(displayName());
  }
  else if (m_impl->compType==Service)
  {
    pageTitle = theTranslator->trServiceReference(displayName());
  }
  else if (m_impl->compType==Singleton)
  {
    pageTitle = theTranslator->trSingletonReference(displayName());
  }
  else
  {
    if (Config_getBool(HIDE_COMPOUND_REFERENCE))
    {
      pageTitle = displayName();
    }
    else
    {
      pageTitle = theTranslator->trCompoundReference(displayName(),
                m_impl->compType == Interface && getLanguage()==SrcLangExt::ObjC ? Class : m_impl->compType,
                !m_impl->tempArgs.empty());
    }
  }
  return pageTitle;
}
References ClassDef::Class, Config_getBool, displayName(), Fortran, VhdlDocGen::getClassTitle(), Definition::getLanguage(), DefinitionMixin< ClassDefMutable >::getLanguage(), ClassDef::Interface, isJavaEnum(), isSliceLocal(), m_impl, ObjC, ClassDef::Service, ClassDef::Singleton, Slice, theTranslator, Translator::trCompoundReference(), Translator::trCompoundReferenceFortran(), Translator::trCompoundReferenceSlice(), Translator::trCustomReference(), Translator::trEnumReference(), Translator::trServiceReference(), Translator::trSingletonReference(), and VHDL.
Referenced by addUsedInterfaceClasses(), getTitleForMemberListType(), internalInsertMember(), writeDetailedDescription(), writeDocumentation(), writeInheritedMemberDeclarations(), writeMemberDeclarations(), writeMemberDocumentation(), and writeNestedClasses().
typeConstraints()
const ArgumentList & ClassDefImpl::typeConstraints () const override virtual
Implements ClassDef.
Definition at line 5237 of file classdef.cpp.
{
  return m_impl->typeConstraints;
}
References m_impl.
updateBaseClasses()
void ClassDefImpl::updateBaseClasses (const BaseClassList & bcd) override virtual
Update the list of base classes to the one passed.
Implements ClassDef.
Definition at line 4863 of file classdef.cpp.
{
  m_impl->inherits = bcd;
}
References m_impl.
updateSubClasses()
void ClassDefImpl::updateSubClasses (const BaseClassList & bcd) override virtual
Update the list of sub classes to the one passed.
Implements ClassDef.
Definition at line 4873 of file classdef.cpp.
{
  m_impl->inheritedBy = bcd;
}
References m_impl.
usedByImplementationClasses()
const UsesClassList & ClassDefImpl::usedByImplementationClasses () const override virtual
Implements ClassDef.
Definition at line 4948 of file classdef.cpp.
{
  return m_impl->usedByImplClassList;
}
References m_impl.
usedFiles()
const FileList & ClassDefImpl::usedFiles () const override virtual
Implements ClassDef.
Definition at line 5232 of file classdef.cpp.
{
  return m_impl->files;
}
References m_impl.
usedImplementationClasses()
const UsesClassList & ClassDefImpl::usedImplementationClasses () const override virtual
Implements ClassDef.
Definition at line 4943 of file classdef.cpp.
{
  return m_impl->usesImplClassList;
}
References m_impl.
visibleInParentsDeclList()
bool ClassDefImpl::visibleInParentsDeclList () const override virtual
show this class in the declaration section of its parent?
Implements ClassDef.
Definition at line 2580 of file classdef.cpp.
{
  bool extractPrivate      = Config_getBool(EXTRACT_PRIVATE);
  bool hideUndocClasses = Config_getBool(HIDE_UNDOC_CLASSES);
  bool extractLocalClasses = Config_getBool(EXTRACT_LOCAL_CLASSES);
  bool linkable = isLinkable();
  return (!isAnonymous() && !isExtension() &&
          (protection()!=Protection::Private || extractPrivate) &&
          (linkable || (!hideUndocClasses && (!isLocal() || extractLocalClasses)))
         );
}
References Config_getBool, DefinitionMixin< ClassDefMutable >::isAnonymous(), isExtension(), isLinkable(), isLocal(), Private, and protection().
Referenced by writeDeclarationLink().
writeAdditionalInheritedMembers()
void ClassDefImpl::writeAdditionalInheritedMembers (OutputList & ol) const private
Definition at line 4672 of file classdef.cpp.
{
  //printf("**** writeAdditionalInheritedMembers()\n");
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd && lmd->type!=MemberListType::Friends())
      {
        ClassDefSet visited;
        writeInheritedMemberDeclarations(ol,visited,lmd->type,MemberListType::Invalid(),lmd->title(getLanguage()),this,TRUE,FALSE);
      }
    }
  }
}
References FALSE, Definition::getLanguage(), LayoutDocManager::instance(), MemberListType::Invalid(), LayoutDocEntryMemberDecl::title(), TRUE, LayoutDocEntryMemberDecl::type, and writeInheritedMemberDeclarations().
Referenced by endMemberDeclarations().
writeAuthorSection()
void ClassDefImpl::writeAuthorSection (OutputList & ol) const private
Definition at line 2228 of file classdef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Man);
  ol.writeString("\n");
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), TRUE, and OutputList::writeString().
Referenced by writeDocumentationContents().
writeBriefDescription()
void ClassDefImpl::writeBriefDescription (OutputList & ol, bool exampleFlag) const private
Definition at line 1566 of file classdef.cpp.
{
  if (hasBriefDescription())
  {
    ol.startParagraph();
    ol.pushGeneratorState();
    ol.disableAllBut(OutputType::Man);
    ol.writeString(" - ");
    ol.popGeneratorState();
    ol.generateDoc(briefFile(),briefLine(),this,nullptr,
                   briefDescription(),TRUE,FALSE,QCString(),
                   TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    ol.pushGeneratorState();
    ol.disable(OutputType::RTF);
    ol.writeString(" \n");
    ol.enable(OutputType::RTF);
    ol.popGeneratorState();
    if (hasDetailedDescription() || exampleFlag)
    {
      writeMoreLink(ol,anchor());
    }
    ol.endParagraph();
  }
  ol.writeSynopsis();
}
References anchor(), DefinitionMixin< ClassDefMutable >::briefDescription(), DefinitionMixin< ClassDefMutable >::briefFile(), DefinitionMixin< ClassDefMutable >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), OutputList::enable(), OutputList::endParagraph(), FALSE, OutputList::generateDoc(), DefinitionMixin< ClassDefMutable >::hasBriefDescription(), hasDetailedDescription(), Man, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), RTF, OutputList::startParagraph(), TRUE, writeMoreLink(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentationContents().
writeCollaborationGraph()
void ClassDefImpl::writeCollaborationGraph (OutputList & ol) const private
Definition at line 1959 of file classdef.cpp.
{
  if (Config_getBool(HAVE_DOT) && m_impl->hasCollaborationGraph /*&& Config_getBool(COLLABORATION_GRAPH)*/)
  {
    DotClassGraph usageImplGraph(this,GraphType::Collaboration);
    if (usageImplGraph.isTooBig())
    {
       warn_uncond("Collaboration graph for '%s' not generated, too many nodes (%d), threshold is %d. Consider increasing DOT_GRAPH_MAX_NODES.\n",
           qPrint(name()), usageImplGraph.numNodes(), Config_getInt(DOT_GRAPH_MAX_NODES));
    }
    else if (!usageImplGraph.isTrivial())
    {
      ol.pushGeneratorState();
      ol.disable(OutputType::Man);
      ol.startDotGraph();
      ol.parseText(theTranslator->trCollaborationDiagram(displayName()));
      ol.endDotGraph(usageImplGraph);
      ol.popGeneratorState();
    }
  }
}
References Collaboration, Config_getBool, Config_getInt, OutputList::disable(), displayName(), OutputList::endDotGraph(), DotClassGraph::isTooBig(), DotClassGraph::isTrivial(), m_impl, Man, DefinitionMixin< ClassDefMutable >::name(), DotClassGraph::numNodes(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), qPrint(), OutputList::startDotGraph(), theTranslator, Translator::trCollaborationDiagram(), and warn_uncond.
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeDeclaration()
void ClassDefImpl::writeDeclaration (OutputList & ol, const MemberDef * md, bool inGroup, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const override virtual
called from MemberDef::writeDeclaration() to (recursively) write the definition of an anonymous struct, union or class.
Implements ClassDef.
Definition at line 3505 of file classdef.cpp.
{
  //printf("ClassName='%s' inGroup=%d\n",qPrint(name()),inGroup);
  ol.docify(compoundTypeString());
  QCString cn = displayName(FALSE);
  if (!cn.isEmpty())
  {
    ol.docify(" ");
    if (md && isLinkable())
    {
      ol.writeObjectLink(QCString(),QCString(),md->anchor(),cn);
    }
    else
    {
      ol.startBold();
      ol.docify(cn);
      ol.endBold();
    }
  }
  ol.docify(" {");
  ol.endMemberItem(OutputGenerator::MemberItemType::AnonymousStart);
  ol.endMemberDeclaration(md ? md->anchor() : QCString(),inheritId);
  // write user defined member groups
  for (const auto &mg : m_impl->memberGroups)
  {
    mg->writePlainDeclarations(ol,inGroup,this,nullptr,nullptr,nullptr,nullptr,indentLevel,inheritedFrom,inheritId);
  }
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        writePlainMemberDeclaration(ol,lmd->type,inGroup,indentLevel,inheritedFrom,inheritId);
      }
    }
  }
}
References Definition::anchor(), OutputGenerator::AnonymousStart, compoundTypeString(), displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberItem(), FALSE, LayoutDocManager::instance(), QCString::isEmpty(), isLinkable(), m_impl, OutputList::startBold(), LayoutDocEntryMemberDecl::type, OutputList::writeObjectLink(), and writePlainMemberDeclaration().
writeDeclarationLink()
void ClassDefImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const override virtual
Implements ClassDef.
Definition at line 2592 of file classdef.cpp.
{
  //bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  //bool vhdlOpt    = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  bool sliceOpt   = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
  SrcLangExt lang = getLanguage();
  if (visibleInParentsDeclList())
  {
    if (!found) // first class
    {
      if (sliceOpt)
      {
        if (compoundType()==Interface)
        {
          ol.startMemberHeader("interfaces");
        }
        else if (compoundType()==Struct)
        {
          ol.startMemberHeader("structs");
        }
        else if (compoundType()==Exception)
        {
          ol.startMemberHeader("exceptions");
        }
        else // compoundType==Class
        {
          ol.startMemberHeader("nested-classes");
        }
      }
      else // non-Slice optimization: single header for class/struct/..
      {
        ol.startMemberHeader("nested-classes");
      }
      if (!header.isEmpty())
      {
        ol.parseText(header);
      }
      else if (lang==SrcLangExt::VHDL)
      {
        ol.parseText(theTranslator->trVhdlType(VhdlSpecifier::ARCHITECTURE,FALSE));
      }
      else
      {
        ol.parseText(lang==SrcLangExt::Fortran ?
            theTranslator->trDataTypes() :
            theTranslator->trCompounds());
      }
      ol.endMemberHeader();
      ol.startMemberList();
      found=TRUE;
    }
    ol.startMemberDeclaration();
    ol.startMemberItem(anchor(),OutputGenerator::MemberItemType::Normal);
    QCString ctype = compoundTypeString();
    QCString cname = displayName(!localNames);
    if (lang!=SrcLangExt::VHDL) // for VHDL we swap the name and the type
    {
      if (isSliceLocal())
      {
        ol.writeString("local ");
      }
      ol.writeString(ctype);
      ol.writeString(" ");
      ol.insertMemberAlign();
    }
    if (isLinkable())
    {
      ol.writeObjectLink(getReference(),
          getOutputFileBase(),
          anchor(),
          cname
          );
    }
    else
    {
      ol.startBold();
      ol.docify(cname);
      ol.endBold();
    }
    if (lang==SrcLangExt::VHDL) // now write the type
    {
      ol.writeString(" ");
      ol.insertMemberAlign();
      ol.writeString(VhdlDocGen::getProtectionName(VhdlDocGen::convert(protection())));
    }
    ol.endMemberItem(OutputGenerator::MemberItemType::Normal);
    // add the brief description if available
    if (!briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
    {
      auto parser { createDocParser() };
      auto ast    { validatingParseDoc(*parser.get(),
                                briefFile(),briefLine(),this,nullptr,
                                briefDescription(),FALSE,FALSE,
                                QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
      if (!ast->isEmpty())
      {
        ol.startMemberDescription(anchor());
        ol.writeDoc(ast.get(),this,nullptr);
        if (isLinkableInProject())
        {
          writeMoreLink(ol,anchor());
        }
        ol.endMemberDescription();
      }
    }
    ol.endMemberDeclaration(anchor(),QCString());
  }
}
References anchor(), ARCHITECTURE, DefinitionMixin< ClassDefMutable >::briefDescription(), Definition::briefFile(), DefinitionMixin< ClassDefMutable >::briefLine(), compoundType(), compoundTypeString(), Config_getBool, VhdlDocGen::convert(), createDocParser(), displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), ClassDef::Exception, FALSE, Fortran, found, DefinitionMixin< ClassDefMutable >::getLanguage(), getOutputFileBase(), VhdlDocGen::getProtectionName(), getReference(), OutputList::insertMemberAlign(), ClassDef::Interface, QCString::isEmpty(), isLinkable(), isLinkableInProject(), isSliceLocal(), OutputGenerator::Normal, OutputList::parseText(), protection(), OutputList::startBold(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), ClassDef::Struct, theTranslator, Translator::trCompounds(), Translator::trDataTypes(), TRUE, Translator::trVhdlType(), validatingParseDoc(), VHDL, visibleInParentsDeclList(), OutputList::writeDoc(), writeMoreLink(), OutputList::writeObjectLink(), and OutputList::writeString().
writeDetailedDescription()
void ClassDefImpl::writeDetailedDescription (OutputList & ol, const QCString & pageType, bool exampleFlag, const QCString & title, const QCString & anchor = QCString()) const private
Definition at line 1651 of file classdef.cpp.
{
  if (hasDetailedDescription() || exampleFlag)
  {
    ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Html);
      ol.writeAnchor(QCString(),anchor.isEmpty() ? QCString("details") : anchor);
    ol.popGeneratorState();
    if (!anchor.isEmpty())
    {
      ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.disable(OutputType::Man);
      ol.writeAnchor(getOutputFileBase(),anchor);
      ol.popGeneratorState();
    }
    ol.startGroupHeader();
    ol.parseText(title);
    ol.endGroupHeader();
    writeDetailedDocumentationBody(ol);
  }
  else
  {
    //writeTemplateSpec(ol,this,pageType);
  }
}
References anchor(), OutputList::disable(), OutputList::disableAllBut(), OutputList::endGroupHeader(), getOutputFileBase(), hasDetailedDescription(), Html, Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), title(), OutputList::writeAnchor(), writeDetailedDocumentationBody(), and OutputList::writeRuler().
Referenced by writeDocumentationContents().
writeDetailedDocumentationBody()
void ClassDefImpl::writeDetailedDocumentationBody (OutputList & ol) const private
Definition at line 1594 of file classdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  ol.startTextBlock();
  if (getLanguage()==SrcLangExt::Cpp)
  {
    writeTemplateSpec(ol,this,compoundTypeString(),getLanguage());
  }
  // repeat brief description
  if (!briefDescription().isEmpty() && repeatBrief)
  {
    ol.generateDoc(briefFile(),briefLine(),this,nullptr,briefDescription(),FALSE,FALSE,
                   QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
  }
  if (!briefDescription().isEmpty() && repeatBrief &&
      !documentation().isEmpty())
  {
    ol.pushGeneratorState();
    ol.disable(OutputType::Html);
    ol.writeString("\n\n");
    ol.popGeneratorState();
  }
  // write documentation
  if (!documentation().isEmpty())
  {
    ol.generateDoc(docFile(),docLine(),this,nullptr,documentation(),TRUE,FALSE,
                   QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
  }
  // write type constraints
  writeTypeConstraints(ol,this,m_impl->typeConstraints);
  // write examples
  if (hasExamples())
  {
    ol.startExamples();
    ol.startDescForItem();
    writeExamples(ol,m_impl->examples);
    ol.endDescForItem();
    ol.endExamples();
  }
  writeSourceDef(ol);
  ol.endTextBlock();
}
References DefinitionMixin< ClassDefMutable >::briefDescription(), DefinitionMixin< ClassDefMutable >::briefFile(), DefinitionMixin< ClassDefMutable >::briefLine(), compoundTypeString(), Config_getBool, Cpp, OutputList::disable(), DefinitionMixin< ClassDefMutable >::docFile(), DefinitionMixin< ClassDefMutable >::docLine(), DefinitionMixin< ClassDefMutable >::documentation(), OutputList::endDescForItem(), OutputList::endExamples(), OutputList::endTextBlock(), FALSE, OutputList::generateDoc(), DefinitionMixin< ClassDefMutable >::getLanguage(), hasExamples(), Html, m_impl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startDescForItem(), OutputList::startExamples(), OutputList::startTextBlock(), TRUE, writeExamples(), DefinitionMixin< ClassDefMutable >::writeSourceDef(), OutputList::writeString(), writeTemplateSpec(), and writeTypeConstraints().
Referenced by writeDetailedDescription(), and writeInlineDocumentation().
writeDocumentation()
void ClassDefImpl::writeDocumentation (OutputList & ol) const override virtual
Implements ClassDef.
Definition at line 2934 of file classdef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  //bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  //bool vhdlOpt    = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  bool sliceOpt   = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
  QCString pageTitle = title();
  HighlightedItem hli = HighlightedItem::None;
  if (sliceOpt)
  {
    if (compoundType()==Interface)
    {
      hli = HighlightedItem::InterfaceVisible;
    }
    else if (compoundType()==Struct)
    {
      hli = HighlightedItem::StructVisible;
    }
    else if (compoundType()==Exception)
    {
      hli = HighlightedItem::ExceptionVisible;
    }
    else
    {
      hli = HighlightedItem::ClassVisible;
    }
  }
  else
  {
    hli = HighlightedItem::ClassVisible;
  }
  startFile(ol,getOutputFileBase(),name(),pageTitle,hli,!generateTreeView);
  if (!generateTreeView)
  {
    if (getOuterScope()!=Doxygen::globalScope)
    {
      writeNavigationPath(ol);
    }
    ol.endQuickIndices();
  }
  startTitle(ol,getOutputFileBase(),this);
  ol.parseText(pageTitle);
  addClassAttributes(ol);
  addGroupListToTitle(ol,this);
  endTitle(ol,getOutputFileBase(),displayName());
  writeDocumentationContents(ol,pageTitle);
  endFileWithNavPath(ol,this);
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    writeMemberPages(ol);
  }
}
References addClassAttributes(), addGroupListToTitle(), ClassVisible, compoundType(), Config_getBool, displayName(), endFileWithNavPath(), OutputList::endQuickIndices(), endTitle(), ClassDef::Exception, ExceptionVisible, DefinitionMixin< ClassDefMutable >::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, ClassDef::Interface, InterfaceVisible, DefinitionMixin< ClassDefMutable >::name(), None, OutputList::parseText(), startFile(), startTitle(), ClassDef::Struct, StructVisible, title(), writeDocumentationContents(), writeMemberPages(), and DefinitionMixin< ClassDefMutable >::writeNavigationPath().
writeDocumentationContents()
void ClassDefImpl::writeDocumentationContents (OutputList & ol, const QCString & pageTitle) const private
Definition at line 2737 of file classdef.cpp.
{
  ol.startContents();
  QCString pageType = " ";
  pageType += compoundTypeString();
  bool exampleFlag=hasExamples();
  //---------------------------------------- start flexible part -------------------------------
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol,exampleFlag);
        break;
      case LayoutDocEntry::ClassIncludes:
        if (lang==SrcLangExt::Slice)
        {
          writeIncludeFilesForSlice(ol);
        }
        else
        {
          writeIncludeFiles(ol);
        }
        break;
      case LayoutDocEntry::ClassInheritanceGraph:
        writeInheritanceGraph(ol);
        break;
      case LayoutDocEntry::ClassCollaborationGraph:
        writeCollaborationGraph(ol);
        break;
      case LayoutDocEntry::ClassAllMembersLink:
        //writeAllMembersLink(ol); // this is now part of the summary links
        break;
      case LayoutDocEntry::MemberDeclStart:
        startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::MemberGroups:
        writeMemberGroups(ol);
        break;
      case LayoutDocEntry::MemberDecl:
        {
          ClassDefSet visitedClasses;
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            writeMemberDeclarations(ol,visitedClasses,lmd->type,lmd->title(lang),lmd->subtitle(lang));
          }
        }
        break;
      case LayoutDocEntry::ClassNestedClasses:
        {
          const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
          if (ls)
          {
            writeNestedClasses(ol,ls->title(lang));
          }
        }
        break;
      case LayoutDocEntry::MemberDeclEnd:
        endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::DetailedDesc:
        {
          const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
          if (ls)
          {
            writeDetailedDescription(ol,pageType,exampleFlag,ls->title(lang));
          }
        }
        break;
      case LayoutDocEntry::MemberDefStart:
        startMemberDocumentation(ol);
        break;
      case LayoutDocEntry::ClassInlineClasses:
        writeInlineClasses(ol);
        break;
      case LayoutDocEntry::MemberDef:
        {
          const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
          if (lmd)
          {
            writeMemberDocumentation(ol,lmd->type,lmd->title(lang));
          }
        }
        break;
      case LayoutDocEntry::MemberDefEnd:
        endMemberDocumentation(ol);
        break;
      case LayoutDocEntry::ClassUsedFiles:
        showUsedFiles(ol);
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::NamespaceNestedNamespaces:
      case LayoutDocEntry::NamespaceNestedConstantGroups:
      case LayoutDocEntry::NamespaceClasses:
      case LayoutDocEntry::NamespaceConcepts:
      case LayoutDocEntry::NamespaceInterfaces:
      case LayoutDocEntry::NamespaceStructs:
      case LayoutDocEntry::NamespaceExceptions:
      case LayoutDocEntry::NamespaceInlineClasses:
      case LayoutDocEntry::ConceptDefinition:
      case LayoutDocEntry::FileClasses:
      case LayoutDocEntry::FileConcepts:
      case LayoutDocEntry::FileInterfaces:
      case LayoutDocEntry::FileStructs:
      case LayoutDocEntry::FileExceptions:
      case LayoutDocEntry::FileNamespaces:
      case LayoutDocEntry::FileConstantGroups:
      case LayoutDocEntry::FileIncludes:
      case LayoutDocEntry::FileIncludeGraph:
      case LayoutDocEntry::FileIncludedByGraph:
      case LayoutDocEntry::FileSourceLink:
      case LayoutDocEntry::FileInlineClasses:
      case LayoutDocEntry::GroupClasses:
      case LayoutDocEntry::GroupConcepts:
      case LayoutDocEntry::GroupModules:
      case LayoutDocEntry::GroupInlineClasses:
      case LayoutDocEntry::GroupNamespaces:
      case LayoutDocEntry::GroupDirs:
      case LayoutDocEntry::GroupNestedGroups:
      case LayoutDocEntry::GroupFiles:
      case LayoutDocEntry::GroupGraph:
      case LayoutDocEntry::GroupPageDocs:
      case LayoutDocEntry::ModuleExports:
      case LayoutDocEntry::ModuleClasses:
      case LayoutDocEntry::ModuleConcepts:
      case LayoutDocEntry::ModuleUsedFiles:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::Class entry list\n",lde->kind());
        break;
    }
  }
  ol.endContents();
}
References compoundTypeString(), OutputList::endContents(), endMemberDeclarations(), endMemberDocumentation(), err, DefinitionMixin< ClassDefMutable >::getLanguage(), hasExamples(), LayoutDocManager::instance(), showUsedFiles(), Slice, OutputList::startContents(), startMemberDeclarations(), startMemberDocumentation(), LayoutDocEntryMemberDecl::subtitle(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeCollaborationGraph(), writeDetailedDescription(), writeIncludeFiles(), writeIncludeFilesForSlice(), writeInheritanceGraph(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), and writeNestedClasses().
Referenced by writeDocumentation().
writeDocumentationForInnerClasses()
void ClassDefImpl::writeDocumentationForInnerClasses (OutputList & ol) const override virtual
Implements ClassDef.
Definition at line 3057 of file classdef.cpp.
{
  // write inner classes after the parent, so the tag files contain
  // the definition in proper order!
  for (const auto &innerCd : m_impl->innerClasses)
  {
    if (
        innerCd->isLinkableInProject() && innerCd->templateMaster()==nullptr &&
        protectionLevelVisible(innerCd->protection()) &&
        !innerCd->isEmbeddedInOuterScope()
       )
    {
      msg("Generating docs for nested compound %s...\n",qPrint(innerCd->name()));
      innerCd->writeDocumentation(ol);
      innerCd->writeMemberList(ol);
    }
    innerCd->writeDocumentationForInnerClasses(ol);
  }
}
References m_impl, msg(), protectionLevelVisible(), and qPrint().
writeIncludeFiles()
void ClassDefImpl::writeIncludeFiles (OutputList & ol) const private
Definition at line 2123 of file classdef.cpp.
{
  if (m_impl->incInfo /*&& Config_getBool(SHOW_HEADERFILE)*/)
  {
    SrcLangExt lang = getLanguage();
    QCString nm=m_impl->incInfo->includeName.isEmpty() ?
      (m_impl->incInfo->fileDef ?
       m_impl->incInfo->fileDef->docName() : QCString()
      ) :
      m_impl->incInfo->includeName;
    if (!nm.isEmpty())
    {
      ol.startParagraph();
      ol.startTypewriter();
      ol.docify(::includeStatement(lang,m_impl->incInfo->kind));
      ol.docify(::includeOpen(lang,m_impl->incInfo->kind));
      ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.docify(nm);
      ol.disableAllBut(OutputType::Html);
      ol.enable(OutputType::Html);
      if (m_impl->incInfo->fileDef)
      {
        ol.writeObjectLink(QCString(),m_impl->incInfo->fileDef->includeName(),QCString(),nm);
      }
      else
      {
        ol.docify(nm);
      }
      ol.popGeneratorState();
      ol.docify(::includeClose(lang,m_impl->incInfo->kind));
      ol.endTypewriter();
      ol.endParagraph();
    }
  }
}
References OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTypewriter(), DefinitionMixin< ClassDefMutable >::getLanguage(), Html, includeClose(), includeOpen(), includeStatement(), QCString::isEmpty(), m_impl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startParagraph(), OutputList::startTypewriter(), and OutputList::writeObjectLink().
Referenced by writeDocumentationContents().
writeIncludeFilesForSlice()
void ClassDefImpl::writeIncludeFilesForSlice (OutputList & ol) const private
Definition at line 1982 of file classdef.cpp.
{
  if (m_impl->incInfo)
  {
    QCString nm;
    const StringVector &paths = Config_getList(STRIP_FROM_PATH);
    if (!paths.empty() && m_impl->incInfo->fileDef)
    {
      QCString abs = m_impl->incInfo->fileDef->absFilePath();
      QCString potential;
      size_t length = 0;
      for (const auto &s : paths)
      {
        FileInfo info(s);
        if (info.exists())
        {
          QCString prefix = info.absFilePath();
          if (prefix.at(prefix.length() - 1) != '/')
          {
            prefix += '/';
          }
          if (prefix.length() > length &&
              qstricmp(abs.left(prefix.length()).data(), prefix.data()) == 0) // case insensitive compare
          {
            length = prefix.length();
            potential = abs.right(abs.length() - prefix.length());
          }
        }
      }
      if (length > 0)
      {
        nm = potential;
      }
    }
    if (nm.isEmpty())
    {
      nm = m_impl->incInfo->includeName;
    }
    ol.startParagraph();
    ol.docify(theTranslator->trDefinedIn()+" ");
    ol.startTypewriter();
    ol.docify("<");
    if (m_impl->incInfo->fileDef)
    {
      ol.writeObjectLink(QCString(),m_impl->incInfo->fileDef->includeName(),QCString(),nm);
    }
    else
    {
      ol.docify(nm);
    }
    ol.docify(">");
    ol.endTypewriter();
    ol.endParagraph();
  }
  // Write a summary of the Slice definition including metadata.
  ol.startParagraph();
  ol.startTypewriter();
  if (!m_impl->metaData.isEmpty())
  {
    ol.docify(m_impl->metaData);
    ol.lineBreak();
  }
  if (m_impl->spec.isLocal())
  {
    ol.docify("local ");
  }
  if (m_impl->spec.isInterface())
  {
    ol.docify("interface ");
  }
  else if (m_impl->spec.isStruct())
  {
    ol.docify("struct ");
  }
  else if (m_impl->spec.isException())
  {
    ol.docify("exception ");
  }
  else
  {
    ol.docify("class ");
  }
  ol.docify(stripScope(name()));
  if (!m_impl->inherits.empty())
  {
    if (m_impl->spec.isInterface() || m_impl->spec.isException())
    {
      ol.docify(" extends ");
      bool first=true;
      for (const auto &ibcd : m_impl->inherits)
      {
        if (!first) ol.docify(", ");
        ClassDef *icd = ibcd.classDef;
        ol.docify(icd->name());
        first=false;
      }
    }
    else
    {
      // Must be a class.
      bool implements = false;
      for (const auto &ibcd : m_impl->inherits)
      {
        ClassDef *icd = ibcd.classDef;
        if (icd->isInterface())
        {
          implements = true;
        }
        else
        {
          ol.docify(" extends ");
          ol.docify(icd->name());
        }
      }
      if (implements)
      {
        ol.docify(" implements ");
        bool first = true;
        for (const auto &ibcd : m_impl->inherits)
        {
          ClassDef *icd = ibcd.classDef;
          if (icd->isInterface())
          {
            if (!first) ol.docify(", ");
            first = false;
            ol.docify(icd->name());
          }
        }
      }
    }
  }
  ol.docify(" { ... }");
  ol.endTypewriter();
  ol.endParagraph();
}
References FileInfo::absFilePath(), Config_getList, QCString::data(), OutputList::docify(), OutputList::endParagraph(), OutputList::endTypewriter(), FileInfo::exists(), QCString::isEmpty(), ClassDef::isInterface(), QCString::left(), QCString::length(), OutputList::lineBreak(), m_impl, Definition::name(), DefinitionMixin< ClassDefMutable >::name(), prefix, qstricmp(), QCString::right(), OutputList::startParagraph(), OutputList::startTypewriter(), stripScope(), theTranslator, Translator::trDefinedIn(), and OutputList::writeObjectLink().
Referenced by writeDocumentationContents().
writeInheritanceGraph()
void ClassDefImpl::writeInheritanceGraph (OutputList & ol) const private
Definition at line 1824 of file classdef.cpp.
{
  bool haveDot    = Config_getBool(HAVE_DOT);
  auto classGraph = m_impl->typeInheritanceGraph;
  if (classGraph == CLASS_GRAPH_t::NO) return;
  // count direct inheritance relations
  int count=countInheritanceNodes();
  bool renderDiagram = FALSE;
  if (haveDot && (classGraph==CLASS_GRAPH_t::YES || classGraph==CLASS_GRAPH_t::GRAPH))
    // write class diagram using dot
  {
    DotClassGraph inheritanceGraph(this,GraphType::Inheritance);
    if (inheritanceGraph.isTooBig())
    {
       warn_uncond("Inheritance graph for '%s' not generated, too many nodes (%d), threshold is %d. Consider increasing DOT_GRAPH_MAX_NODES.\n",
           qPrint(name()), inheritanceGraph.numNodes(), Config_getInt(DOT_GRAPH_MAX_NODES));
    }
    else if (!inheritanceGraph.isTrivial())
    {
      ol.pushGeneratorState();
      ol.disable(OutputType::Man);
      ol.startDotGraph();
      ol.parseText(theTranslator->trClassDiagram(displayName()));
      ol.endDotGraph(inheritanceGraph);
      ol.popGeneratorState();
      renderDiagram = TRUE;
    }
  }
  else if ((classGraph==CLASS_GRAPH_t::YES || classGraph==CLASS_GRAPH_t::GRAPH || classGraph==CLASS_GRAPH_t::BUILTIN) && count>0)
    // write class diagram using built-in generator
  {
    ClassDiagram diagram(this); // create a diagram of this class.
    ol.startClassDiagram();
    ol.disable(OutputType::Man);
    ol.parseText(theTranslator->trClassDiagram(displayName()));
    ol.enable(OutputType::Man);
    ol.endClassDiagram(diagram,getOutputFileBase(),displayName());
    renderDiagram = TRUE;
  }
  if (renderDiagram) // if we already show the inheritance relations graphically,
                     // then hide the text version
  {
    ol.disableAllBut(OutputType::Man);
  }
  count = countInheritsNodes();
  if (count>0)
  {
    auto replaceFunc = [this,&ol](size_t entryIndex)
    {
      for (size_t index=0; index<m_impl->inherits.size() ; index++)
      {
        const BaseClassDef &bcd=m_impl->inherits[index];
        const ClassDef *cd=bcd.classDef;
        if (cd->isVisibleInHierarchy()) // filter on the class we want to show
        {
          if (index==entryIndex) // found the requested index
          {
            // use the class name but with the template arguments as given
            // in the inheritance relation
            QCString displayName = insertTemplateSpecifierInScope(
                cd->displayName(),bcd.templSpecifiers);
            if (cd->isLinkable())
            {
              ol.writeObjectLink(cd->getReference(),
                  cd->getOutputFileBase(),
                  cd->anchor(),
                  displayName);
            }
            else
            {
              ol.docify(displayName);
            }
            return;
          }
        }
      }
    };
    ol.startParagraph();
    writeMarkerList(ol,
                    theTranslator->trInheritsList(count).str(),
                    static_cast<size_t>(count),
                    replaceFunc);
    ol.endParagraph();
  }
  // write subclasses
  count = countInheritedByNodes();
  if (count>0)
  {
    auto replaceFunc = [this,&ol](size_t entryIndex)
    {
      for (size_t index=0; index<m_impl->inheritedBy.size() ; index++)
      {
        const BaseClassDef &bcd=m_impl->inheritedBy[index];
        const ClassDef *cd=bcd.classDef;
        if (cd->isVisibleInHierarchy()) // filter on the class we want to show
        {
          if (index==entryIndex) // found the requested index
          {
            if (cd->isLinkable())
            {
              ol.writeObjectLink(cd->getReference(),cd->getOutputFileBase(),cd->anchor(),cd->displayName());
              writeInheritanceSpecifier(ol,bcd);
            }
            else
            {
              ol.docify(cd->displayName());
            }
            return;
          }
        }
      }
    };
    ol.startParagraph();
    writeMarkerList(ol,
                    theTranslator->trInheritedByList(count).str(),
                    static_cast<size_t>(count),
                    replaceFunc);
    ol.endParagraph();
  }
  if (renderDiagram)
  {
    ol.enableAll();
  }
}
References Definition::anchor(), BaseClassDef::classDef, Config_getBool, Config_getInt, countInheritanceNodes(), countInheritedByNodes(), countInheritsNodes(), OutputList::disable(), OutputList::disableAllBut(), displayName(), Definition::displayName(), OutputList::docify(), OutputList::enable(), OutputList::enableAll(), OutputList::endClassDiagram(), OutputList::endDotGraph(), OutputList::endParagraph(), FALSE, getOutputFileBase(), Definition::getOutputFileBase(), Definition::getReference(), Inheritance, insertTemplateSpecifierInScope(), Definition::isLinkable(), DotClassGraph::isTooBig(), DotClassGraph::isTrivial(), ClassDef::isVisibleInHierarchy(), m_impl, Man, DefinitionMixin< ClassDefMutable >::name(), DotClassGraph::numNodes(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), qPrint(), OutputList::startClassDiagram(), OutputList::startDotGraph(), OutputList::startParagraph(), QCString::str(), BaseClassDef::templSpecifiers, theTranslator, Translator::trClassDiagram(), Translator::trInheritedByList(), Translator::trInheritsList(), TRUE, warn_uncond, writeInheritanceSpecifier(), writeMarkerList(), and OutputList::writeObjectLink().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeInheritedMemberDeclarations()
void ClassDefImpl::writeInheritedMemberDeclarations (OutputList & ol, ClassDefSet & visitedClasses, MemberListType lt, MemberListType lt2, const QCString & title, const ClassDef * inheritedFrom, bool invert, bool showAlways) const private
Definition at line 4714 of file classdef.cpp.
{
  int count = countMembersIncludingGrouped(lt,inheritedFrom,FALSE);
  bool process = count>0;
  //printf("%s: writeInheritedMemberDec: lt=%s process=%d invert=%d always=%d\n",
  //    qPrint(name()),qPrint(lt.to_string()),process,invert,showAlways);
  if ((process^invert) || showAlways)
  {
    for (const auto &ibcd : m_impl->inherits)
    {
      ClassDefMutable *icd=toClassDefMutable(ibcd.classDef);
      if (icd && icd->isLinkable())
      {
        MemberListType lt1 = MemberListType::Invalid();
        MemberListType lt3 = MemberListType::Invalid();
        convertProtectionLevel(lt,ibcd.prot,&lt1,&lt3);
        if (lt2.isInvalid() && !lt3.isInvalid())
        {
          lt2=lt3;
        }
        //printf("%s:convert %s->(%s,%s) prot=%d\n",qPrint(icd->name()),qPrint(lt.to_string()),
        //                                          qPrint(lt1.to_string()),qPrint(lt2.to_string()),ibcd.prot);
        if (visitedClasses.find(icd)==visitedClasses.end())
        {
          visitedClasses.insert(icd); // guard for multiple virtual inheritance
          if (!lt1.isInvalid())
          {
            //printf("--> writeMemberDeclarations for type %s\n",qPrint(lt1.to_string()));
            icd->writeMemberDeclarations(ol,visitedClasses,lt1,
                title,QCString(),FALSE,inheritedFrom,lt2,FALSE,TRUE);
          }
        }
        else
        {
          //printf("%s: class already visited!\n",qPrint(icd->name()));
        }
      }
    }
  }
}
References convertProtectionLevel(), countMembersIncludingGrouped(), FALSE, MemberListType::Invalid(), MemberListType::isInvalid(), Definition::isLinkable(), m_impl, title(), toClassDefMutable(), TRUE, and ClassDef::writeMemberDeclarations().
Referenced by writeAdditionalInheritedMembers(), and writeMemberDeclarations().
writeInlineClasses()
void ClassDefImpl::writeInlineClasses (OutputList & ol) const private
Definition at line 2183 of file classdef.cpp.
{
  m_impl->innerClasses.writeDocumentation(ol,this);
}
References m_impl.
Referenced by writeDocumentationContents().
writeInlineDocumentation()
void ClassDefImpl::writeInlineDocumentation (OutputList & ol) const override virtual
Write class documentation inside another container (i.e.
a group)
Implements ClassDef.
Definition at line 2415 of file classdef.cpp.
{
  bool isSimple = m_impl->isSimple;
  ol.addIndexItem(name(),QCString());
  //printf("ClassDefImpl::writeInlineDocumentation(%s)\n",qPrint(name()));
  // part 1: anchor and title
  QCString s = compoundTypeString()+" "+name();
  // part 1a
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  { // only HTML only
    ol.writeAnchor(QCString(),anchor());
    ol.startMemberDoc(QCString(),QCString(),anchor(),name(),1,1,FALSE);
    ol.startMemberDocName(FALSE);
    ol.parseText(s);
    ol.endMemberDocName();
    ol.endMemberDoc(FALSE);
    ol.writeString("</div>");
    ol.startIndent();
  }
  ol.popGeneratorState();
  // part 1b
  ol.pushGeneratorState();
  ol.disable(OutputType::Html);
  ol.disable(OutputType::Man);
  { // for LaTeX/RTF only
    ol.writeAnchor(getOutputFileBase(),anchor());
  }
  ol.popGeneratorState();
  // part 1c
  ol.pushGeneratorState();
  ol.disable(OutputType::Html);
  {
    // for LaTeX/RTF/Man
    ol.startGroupHeader(1);
    ol.parseText(s);
    ol.endGroupHeader(1);
  }
  ol.popGeneratorState();
  SrcLangExt lang=getLanguage();
  // part 2: the header and detailed description
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        {
          // since we already shown the brief description in the
          // declaration part of the container, so we use this to
          // show the details on top.
          writeDetailedDocumentationBody(ol);
        }
        break;
      case LayoutDocEntry::ClassInheritanceGraph:
        writeInheritanceGraph(ol);
        break;
      case LayoutDocEntry::ClassCollaborationGraph:
        writeCollaborationGraph(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
        if (!isSimple) startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            ClassDefSet visitedClasses;
            if (!isSimple) writeMemberDeclarations(ol,visitedClasses,lmd->type,lmd->title(lang),lmd->subtitle(lang),TRUE);
          }
        }
        break;
      case LayoutDocEntry::MemberGroups:
        if (!isSimple) writeMemberGroups(ol,TRUE);
        break;
      case LayoutDocEntry::MemberDeclEnd:
        if (!isSimple) endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::MemberDefStart:
        if (!isSimple) startMemberDocumentation(ol);
        break;
      case LayoutDocEntry::MemberDef:
        {
          const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
          if (lmd)
          {
            if (isSimple)
            {
              writeSimpleMemberDocumentation(ol,lmd->type);
            }
            else
            {
              writeMemberDocumentation(ol,lmd->type,lmd->title(lang),TRUE);
            }
          }
        }
        break;
      case LayoutDocEntry::MemberDefEnd:
        if (!isSimple) endMemberDocumentation(ol);
        break;
      default:
        break;
    }
  }
  // part 3: close the block
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  { // HTML only
    ol.endIndent();
  }
  ol.popGeneratorState();
}
References OutputList::addIndexItem(), anchor(), compoundTypeString(), OutputList::disable(), OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputList::endIndent(), endMemberDeclarations(), OutputList::endMemberDoc(), OutputList::endMemberDocName(), endMemberDocumentation(), FALSE, DefinitionMixin< ClassDefMutable >::getLanguage(), getOutputFileBase(), Html, LayoutDocManager::instance(), isSimple(), m_impl, Man, DefinitionMixin< ClassDefMutable >::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), OutputList::startIndent(), startMemberDeclarations(), OutputList::startMemberDoc(), OutputList::startMemberDocName(), startMemberDocumentation(), LayoutDocEntryMemberDecl::subtitle(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), TRUE, LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, OutputList::writeAnchor(), writeCollaborationGraph(), writeDetailedDocumentationBody(), writeInheritanceGraph(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeSimpleMemberDocumentation(), and OutputList::writeString().
writeMemberDeclarations()
void ClassDefImpl::writeMemberDeclarations (OutputList & ol, ClassDefSet & visitedClasses, MemberListType lt, const QCString & title, const QCString & subTitle = QCString(), bool showInline = FALSE, const ClassDef * inheritedFrom = nullptr, MemberListType lt2 = MemberListType::Invalid(), bool invert = FALSE, bool showAlways = FALSE) const override virtual
Implements ClassDef.
Definition at line 4757 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::writeMemberDeclarations lt=%s lt2=%s\n",qPrint(name()),qPrint(lt.to_string()),qPrint(lt2.to_string()));
  MemberList * ml = getMemberList(lt);
  MemberList * ml2 = getMemberList(lt2);
  if (getLanguage()==SrcLangExt::VHDL) // use specific declarations function
  {
    static const ClassDef *cdef;
    if (cdef!=this)
    { // only one inline link
      VhdlDocGen::writeInlineClassLink(this,ol);
      cdef=this;
    }
    if (ml)
    {
      VhdlDocGen::writeVhdlDeclarations(ml,ol,nullptr,this,nullptr,nullptr,nullptr);
    }
  }
  else
  {
    //printf("%s::writeMemberDeclarations(%s) ml=%p ml2=%p\n",qPrint(name()),qPrint(title),ml,ml2);
    QCString tt = title, st = subTitle;
    if (ml)
    {
      //printf("  writeDeclarations type=%s count=%d\n",qPrint(lt.to_string()),ml->numDecMembers());
      ml->writeDeclarations(ol,this,nullptr,nullptr,nullptr,nullptr,tt,st,FALSE,showInline,inheritedFrom,lt,true);
      tt.clear();
      st.clear();
    }
    if (ml2)
    {
      //printf("  writeDeclarations type=%s count=%d\n",qPrint(lt2.to_string()),ml2->numDecMembers());
      ml2->writeDeclarations(ol,this,nullptr,nullptr,nullptr,nullptr,tt,st,FALSE,showInline,inheritedFrom,lt,ml==nullptr);
    }
    bool inlineInheritedMembers = Config_getBool(INLINE_INHERITED_MEMB);
    if (!inlineInheritedMembers) // show inherited members as separate lists
    {
      writeInheritedMemberDeclarations(ol,visitedClasses,lt,lt2,title,
          inheritedFrom ? inheritedFrom : this,
          invert,showAlways);
    }
  }
}
References QCString::clear(), Config_getBool, FALSE, DefinitionMixin< ClassDefMutable >::getLanguage(), getMemberList(), title(), VHDL, MemberList::writeDeclarations(), writeInheritedMemberDeclarations(), VhdlDocGen::writeInlineClassLink(), and VhdlDocGen::writeVhdlDeclarations().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeMemberDocumentation()
void ClassDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title, bool showInline = FALSE) const private
Definition at line 4817 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::writeMemberDocumentation()\n",qPrint(name()));
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDocumentation(ol,displayName(),this,title,FALSE,showInline);
}
References displayName(), FALSE, getMemberList(), title(), and MemberList::writeDocumentation().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeMemberGroups()
void ClassDefImpl::writeMemberGroups (OutputList & ol, bool showInline = FALSE) const private
Definition at line 2160 of file classdef.cpp.
{
  // write user defined member groups
  for (const auto &mg : m_impl->memberGroups)
  {
    if (!mg->allMembersInSameSection() || !m_impl->subGrouping) // group is in its own section
    {
      mg->writeDeclarations(ol,this,nullptr,nullptr,nullptr,nullptr,showInline);
    }
    else // add this group to the corresponding member section
    {
      //printf("addToDeclarationSection(%s)\n",qPrint(mg->header()));
      //mg->addToDeclarationSection();
    }
  }
}
References m_impl.
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeMemberList()
void ClassDefImpl::writeMemberList (OutputList & ol) const override virtual
Implements ClassDef.
Definition at line 3078 of file classdef.cpp.
{
  bool cOpt    = Config_getBool(OPTIMIZE_OUTPUT_FOR_C);
  //bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  if (m_impl->allMemberNameInfoLinkedMap.empty() || cOpt) return;
  // only for HTML
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  HighlightedItem hli = HighlightedItem::None;
  if (sliceOpt)
  {
    if (compoundType()==Interface)
    {
      hli = HighlightedItem::InterfaceVisible;
    }
    else if (compoundType()==Struct)
    {
      hli = HighlightedItem::StructVisible;
    }
    else if (compoundType()==Exception)
    {
      hli = HighlightedItem::ExceptionVisible;
    }
    else
    {
      hli = HighlightedItem::ClassVisible;
    }
  }
  else
  {
    hli = HighlightedItem::ClassVisible;
  }
  QCString memListFile = getMemberListFileName();
  startFile(ol,memListFile,memListFile,theTranslator->trMemberList(),hli,!generateTreeView,getOutputFileBase());
  if (!generateTreeView)
  {
    if (getOuterScope()!=Doxygen::globalScope)
    {
      writeNavigationPath(ol);
    }
    ol.endQuickIndices();
  }
  startTitle(ol,QCString());
  ol.parseText(displayName()+" "+theTranslator->trMemberList());
  endTitle(ol,QCString(),QCString());
  ol.startContents();
  ol.startParagraph();
  ol.parseText(theTranslator->trThisIsTheListOfAllMembers());
  ol.docify(" ");
  ol.writeObjectLink(getReference(),getOutputFileBase(),anchor(),displayName());
  ol.parseText(theTranslator->trIncludingInheritedMembers());
  ol.endParagraph();
  //ol.startItemList();
  bool first = true; // to prevent empty table
  int idx=0;
  for (auto &mni : m_impl->allMemberNameInfoLinkedMap)
  {
    for (auto &mi : *mni)
    {
      const MemberDef *md=mi->memberDef();
      const ClassDef  *cd=md->getClassDef();
      Protection prot = mi->prot();
      Specifier virt=md->virtualness();
      //printf("%s: Member %s of class %s md->protection()=%d mi->prot=%d prot=%d inherited=%d\n",
      //    qPrint(name()),qPrint(md->name()),qPrint(cd->name()),md->protection(),mi->prot,prot,mi->inherited);
      if (cd && !md->name().isEmpty() && !md->isAnonymous())
      {
        bool memberWritten=FALSE;
        if (cd->isLinkable() && md->isLinkable())
          // create a link to the documentation
        {
          QCString name=mi->ambiguityResolutionScope()+md->name();
          //ol.writeListItem();
          if (first)
          {
            ol.writeString("<table class=\"directory\">\n");
            first = false;
          }
          ol.writeString("  <tr");
          if ((idx&1)==0) ol.writeString(" class=\"even\""); else ol.writeString(" class=\"odd\"");
          idx++;
          ol.writeString("><td class=\"entry\">");
          if (cd->isObjectiveC())
          {
            if (md->isObjCMethod())
            {
              if (md->isStatic())
                ol.writeString("+&#160;</td><td>");
              else
                ol.writeString("-&#160;</td><td>");
            }
            else
              ol.writeString("</td><td class=\"entry\">");
          }
          if (md->isObjCMethod())
          {
            ol.writeObjectLink(md->getReference(),
                md->getOutputFileBase(),
                md->anchor(),md->name());
          }
          else
          {
            //Definition *bd = md->getGroupDef();
            //if (bd==nullptr) bd=cd;
            ol.writeObjectLink(md->getReference(),
                md->getOutputFileBase(),
                md->anchor(),name);
            if ( md->isFunction() || md->isSignal() || md->isSlot() ||
                (md->isFriend() && !md->argsString().isEmpty()))
              ol.docify(md->argsString());
            else if (md->isEnumerate())
              ol.parseText(" "+theTranslator->trEnumName());
            else if (md->isEnumValue())
              ol.parseText(" "+theTranslator->trEnumValue());
            else if (md->isTypedef())
              ol.docify(" typedef");
            else if (md->isFriend() && md->typeString()=="friend class")
              ol.docify(" class");
            //ol.writeString("\n");
          }
          ol.writeString("</td>");
          memberWritten=TRUE;
        }
        else if (!cd->isArtificial() &&
                 !Config_getBool(HIDE_UNDOC_MEMBERS) &&
                  (protectionLevelVisible(md->protection()) || md->isFriend())
                ) // no documentation,
                  // generate link to the class instead.
        {
          //ol.writeListItem();
          if (first)
          {
            ol.writeString("<table class=\"directory\">\n");
            first = false;
          }
          ol.writeString("  <tr bgcolor=\"#f0f0f0\"");
          if ((idx&1)==0) ol.writeString(" class=\"even\""); else ol.writeString(" class=\"odd\"");
          idx++;
          ol.writeString("><td class=\"entry\">");
          if (cd->isObjectiveC())
          {
            if (md->isObjCMethod())
            {
              if (md->isStatic())
                ol.writeString("+&#160;</td><td class=\"entry\">");
              else
                ol.writeString("-&#160;</td><td class=\"entry\">");
            }
            else
              ol.writeString("</td><td class=\"entry\">");
          }
          ol.startBold();
          ol.docify(md->name());
          ol.endBold();
          if (!md->isObjCMethod())
          {
            if ( md->isFunction() || md->isSignal() || md->isSlot() )
              ol.docify(md->argsString());
            else if (md->isEnumerate())
              ol.parseText(" "+theTranslator->trEnumName());
            else if (md->isEnumValue())
              ol.parseText(" "+theTranslator->trEnumValue());
            else if (md->isTypedef())
              ol.docify(" typedef");
          }
          ol.writeString(" (");
          ol.parseText(theTranslator->trDefinedIn()+" ");
          if (cd->isLinkable())
          {
            ol.writeObjectLink(
                cd->getReference(),
                cd->getOutputFileBase(),
                cd->anchor(),
                cd->displayName());
          }
          else
          {
            ol.startBold();
            ol.docify(cd->displayName());
            ol.endBold();
          }
          ol.writeString(")");
          ol.writeString("</td>");
          memberWritten=TRUE;
        }
        if (memberWritten)
        {
          ol.writeString("<td class=\"entry\">");
          ol.writeObjectLink(cd->getReference(),
                             cd->getOutputFileBase(),
                             cd->anchor(),
                             md->category() ?
                                md->category()->displayName() :
                                cd->displayName());
          ol.writeString("</td>");
          ol.writeString("<td class=\"entry\">");
        }
        SrcLangExt lang = md->getLanguage();
        if (
            (prot!=Protection::Public || (virt!=Specifier::Normal && getLanguage()!=SrcLangExt::ObjC) ||
             md->isFriend() || md->isRelated() || md->isExplicit() ||
             md->isMutable() || (md->isInline() && Config_getBool(INLINE_INFO)) ||
             md->isSignal() || md->isSlot() ||
             (getLanguage()==SrcLangExt::IDL &&
              (md->isOptional() || md->isAttribute() || md->isUNOProperty())) ||
             md->isStatic() || lang==SrcLangExt::VHDL
            )
            && memberWritten)
        {
          StringVector sl;
          if (lang==SrcLangExt::VHDL)
          {
            sl.push_back(theTranslator->trVhdlType(md->getVhdlSpecifiers(),TRUE).str()); //append vhdl type
          }
          else if (md->isFriend()) sl.emplace_back("friend");
          else if (md->isRelated()) sl.emplace_back("related");
          else
          {
            if (Config_getBool(INLINE_INFO) && md->isInline())
                                                   sl.emplace_back("inline");
            if (md->isExplicit())                  sl.emplace_back("explicit");
            if (md->isMutable())                   sl.emplace_back("mutable");
            if (prot==Protection::Protected)       sl.emplace_back("protected");
            else if (prot==Protection::Private)    sl.emplace_back("private");
            else if (prot==Protection::Package)    sl.emplace_back("package");
            if (virt==Specifier::Virtual && getLanguage()!=SrcLangExt::ObjC)
                                                   sl.emplace_back("virtual");
            else if (virt==Specifier::Pure)        sl.emplace_back("pure virtual");
            if (md->isStatic())                    sl.emplace_back("static");
            if (md->isSignal())                    sl.emplace_back("signal");
            if (md->isSlot())                      sl.emplace_back("slot");
// this is the extra member page
            if (md->isOptional())                  sl.emplace_back("optional");
            if (md->isAttribute())                 sl.emplace_back("attribute");
            if (md->isUNOProperty())               sl.emplace_back("property");
            if (md->isReadonly())                  sl.emplace_back("readonly");
            if (md->isBound())                     sl.emplace_back("bound");
            if (md->isRemovable())                 sl.emplace_back("removable");
            if (md->isConstrained())               sl.emplace_back("constrained");
            if (md->isTransient())                 sl.emplace_back("transient");
            if (md->isMaybeVoid())                 sl.emplace_back("maybevoid");
            if (md->isMaybeDefault())              sl.emplace_back("maybedefault");
            if (md->isMaybeAmbiguous())            sl.emplace_back("maybeambiguous");
          }
          bool firstSpan=true;
          for (const auto &s : sl)
          {
            if (!firstSpan)
            {
              ol.writeString("</span><span class=\"mlabel\">");
            }
            else
            {
              ol.writeString("<span class=\"mlabel\">");
              firstSpan=false;
            }
            ol.docify(s.c_str());
          }
          if (!firstSpan) ol.writeString("</span>");
        }
        if (memberWritten)
        {
          ol.writeString("</td>");
          ol.writeString("</tr>\n");
        }
      }
    }
  }
  //ol.endItemList();
  if (!first) ol.writeString("</table>");
  endFile(ol);
  ol.popGeneratorState();
}
References anchor(), Definition::anchor(), MemberDef::argsString(), MemberDef::category(), ClassVisible, compoundType(), Config_getBool, OutputList::disableAllBut(), displayName(), Definition::displayName(), OutputList::docify(), OutputList::endBold(), endFile(), OutputList::endParagraph(), OutputList::endQuickIndices(), endTitle(), ClassDef::Exception, ExceptionVisible, FALSE, MemberDef::getClassDef(), Definition::getLanguage(), DefinitionMixin< ClassDefMutable >::getLanguage(), getMemberListFileName(), DefinitionMixin< ClassDefMutable >::getOuterScope(), getOutputFileBase(), Definition::getOutputFileBase(), getReference(), Definition::getReference(), MemberDef::getVhdlSpecifiers(), Doxygen::globalScope, Html, IDL, ClassDef::Interface, InterfaceVisible, Definition::isAnonymous(), Definition::isArtificial(), MemberDef::isAttribute(), MemberDef::isBound(), MemberDef::isConstrained(), QCString::isEmpty(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isExplicit(), MemberDef::isFriend(), MemberDef::isFunction(), MemberDef::isInline(), Definition::isLinkable(), MemberDef::isMaybeAmbiguous(), MemberDef::isMaybeDefault(), MemberDef::isMaybeVoid(), MemberDef::isMutable(), MemberDef::isObjCMethod(), ClassDef::isObjectiveC(), MemberDef::isOptional(), MemberDef::isReadonly(), MemberDef::isRelated(), MemberDef::isRemovable(), MemberDef::isSignal(), MemberDef::isSlot(), MemberDef::isStatic(), MemberDef::isTransient(), MemberDef::isTypedef(), MemberDef::isUNOProperty(), m_impl, Definition::name(), None, Normal, ObjC, Package, OutputList::parseText(), OutputList::popGeneratorState(), Private, Protected, MemberDef::protection(), protectionLevelVisible(), Public, Pure, OutputList::pushGeneratorState(), OutputList::startBold(), OutputList::startContents(), startFile(), OutputList::startParagraph(), startTitle(), QCString::str(), ClassDef::Struct, StructVisible, theTranslator, Translator::trDefinedIn(), Translator::trEnumName(), Translator::trEnumValue(), Translator::trIncludingInheritedMembers(), Translator::trMemberList(), Translator::trThisIsTheListOfAllMembers(), TRUE, Translator::trVhdlType(), MemberDef::typeString(), VHDL, Virtual, MemberDef::virtualness(), DefinitionMixin< ClassDefMutable >::writeNavigationPath(), OutputList::writeObjectLink(), and OutputList::writeString().
writeMemberPages()
void ClassDefImpl::writeMemberPages (OutputList & ol) const override virtual
Implements ClassDef.
Definition at line 2992 of file classdef.cpp.
{
  ///////////////////////////////////////////////////////////////////////////
  //// Member definitions on separate pages
  ///////////////////////////////////////////////////////////////////////////
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  for (const auto &ml : m_impl->memberLists)
  {
    if (ml->numDocMembers()>ml->numDocEnumValues() && ml->listType().isDetailed())
    {
      ml->writeDocumentationPage(ol,displayName(),this);
    }
  }
  ol.popGeneratorState();
}
References OutputList::disableAllBut(), displayName(), Html, m_impl, OutputList::popGeneratorState(), and OutputList::pushGeneratorState().
Referenced by writeDocumentation().
writeMoreLink()
void ClassDefImpl::writeMoreLink (OutputList & ol, const QCString & anchor) const private
Definition at line 2536 of file classdef.cpp.
{
  // TODO: clean up this mess by moving it to
  // the output generators...
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  bool rtfHyperlinks = Config_getBool(RTF_HYPERLINKS);
  bool usePDFLatex   = Config_getBool(USE_PDFLATEX);
  // HTML only
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  ol.docify(" ");
  ol.startTextLink(getOutputFileBase(),
      anchor.isEmpty() ? QCString("details") : anchor);
  ol.parseText(theTranslator->trMore());
  ol.endTextLink();
  ol.popGeneratorState();
  if (!anchor.isEmpty())
  {
    ol.pushGeneratorState();
    // LaTeX + RTF
    ol.disable(OutputType::Html);
    ol.disable(OutputType::Man);
    ol.disable(OutputType::Docbook);
    if (!(usePDFLatex && pdfHyperlinks))
    {
      ol.disable(OutputType::Latex);
    }
    if (!rtfHyperlinks)
    {
      ol.disable(OutputType::RTF);
    }
    ol.docify(" ");
    ol.startTextLink(getOutputFileBase(), anchor);
    ol.parseText(theTranslator->trMore());
    ol.endTextLink();
    // RTF only
    ol.disable(OutputType::Latex);
    ol.writeString("\\par");
    ol.popGeneratorState();
  }
}
References anchor(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), Docbook, OutputList::docify(), OutputList::endTextLink(), getOutputFileBase(), Html, Latex, Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), RTF, OutputList::startTextLink(), theTranslator, Translator::trMore(), and OutputList::writeString().
Referenced by writeBriefDescription(), and writeDeclarationLink().
writeNestedClasses()
void ClassDefImpl::writeNestedClasses (OutputList & ol, const QCString & title) const private
Definition at line 2177 of file classdef.cpp.
{
  // nested classes
  m_impl->innerClasses.writeDeclaration(ol,nullptr,title,TRUE);
}
References m_impl, title(), and TRUE.
Referenced by writeDocumentationContents().
writePlainMemberDeclaration()
void ClassDefImpl::writePlainMemberDeclaration (OutputList & ol, MemberListType lt, bool inGroup, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const private
Definition at line 4831 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::writePlainMemberDeclaration()\n",qPrint(name()));
  MemberList * ml = getMemberList(lt);
  if (ml)
  {
    ml->writePlainDeclarations(ol,inGroup,this,nullptr,nullptr,nullptr,nullptr,indentLevel,inheritedFrom,inheritId);
  }
}
References getMemberList(), and MemberList::writePlainDeclarations().
Referenced by writeDeclaration().
writeQuickMemberLinks()
void ClassDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * md) const override virtual
Implements DefinitionMutable.
Definition at line 3012 of file classdef.cpp.
{
  bool createSubDirs=Config_getBool(CREATE_SUBDIRS);
  ol.writeString("      <div class=\"navtab\">\n");
  ol.writeString("        <table>\n");
  for (auto &mni : m_impl->allMemberNameInfoLinkedMap)
  {
    for (auto &mi : *mni)
    {
      const MemberDef *md=mi->memberDef();
      if (md->getClassDef()==this && md->isLinkable() && !md->isEnumValue())
      {
        if (md->isLinkableInProject())
        {
          if (md==currentMd) // selected item => highlight
          {
            ol.writeString("          <tr><td class=\"navtabHL\">");
          }
          else
          {
            ol.writeString("          <tr><td class=\"navtab\">");
          }
          ol.writeString("<a class=\"navtab\" ");
          ol.writeString("href=\"");
          if (createSubDirs) ol.writeString("../../");
          QCString url = md->getOutputFileBase();
          addHtmlExtensionIfMissing(url);
          ol.writeString(url+"#"+md->anchor());
          ol.writeString("\">");
          ol.writeString(convertToHtml(md->name()));
          ol.writeString("</a>");
          ol.writeString("</td></tr>\n");
        }
      }
    }
  }
  ol.writeString("        </table>\n");
  ol.writeString("      </div>\n");
}
References addHtmlExtensionIfMissing(), Definition::anchor(), Config_getBool, convertToHtml(), createSubDirs(), MemberDef::getClassDef(), Definition::getOutputFileBase(), MemberDef::isEnumValue(), Definition::isLinkable(), Definition::isLinkableInProject(), m_impl, Definition::name(), and OutputList::writeString().
writeSimpleMemberDocumentation()
void ClassDefImpl::writeSimpleMemberDocumentation (OutputList & ol, MemberListType lt) const private
Definition at line 4824 of file classdef.cpp.
{
  //printf("%s: ClassDefImpl::writeSimpleMemberDocumentation()\n",qPrint(name()));
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeSimpleDocumentation(ol,this);
}
References getMemberList(), and MemberList::writeSimpleDocumentation().
Referenced by writeInlineDocumentation().
writeSummaryLinks()
void ClassDefImpl::writeSummaryLinks (OutputList & ol) const override virtual
Implements DefinitionMutable.
Definition at line 2241 of file classdef.cpp.
{
  static bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  bool first=TRUE;
  SrcLangExt lang = getLanguage();
  if (lang!=SrcLangExt::VHDL)
  {
    for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
    {
      if (lde->kind()==LayoutDocEntry::ClassNestedClasses &&
          m_impl->innerClasses.declVisible()
         )
      {
        for (const auto &innerCd : m_impl->innerClasses)
        {
          if (!innerCd->isAnonymous() &&
              !innerCd->isExtension() &&
              (innerCd->protection()!=Protection::Private || extractPrivate) &&
              innerCd->visibleInParentsDeclList()
             )
          {
            const LayoutDocEntrySection *ls = (const LayoutDocEntrySection*)lde.get();
            ol.writeSummaryLink(QCString(),"nested-classes",ls->title(lang),first);
            first=FALSE;
            break;
          }
        }
      }
      else if (lde->kind()==LayoutDocEntry::ClassAllMembersLink &&
               !m_impl->allMemberNameInfoLinkedMap.empty() &&
               !Config_getBool(OPTIMIZE_OUTPUT_FOR_C)
              )
      {
        ol.writeSummaryLink(getMemberListFileName(),"all-members-list",theTranslator->trListOfAllMembers(),first);
        first=FALSE;
      }
      else if (lde->kind()==LayoutDocEntry::MemberDecl)
      {
        const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
        if (lmd)
        {
          MemberList * ml = getMemberList(lmd->type);
          if (ml && ml->declVisible())
          {
            ol.writeSummaryLink(QCString(),ml->listType().toLabel(),lmd->title(lang),first);
            first=FALSE;
          }
        }
      }
    }
  }
  else // VDHL only
  {
    for (const auto &s : m_impl->vhdlSummaryTitles)
    {
      ol.writeSummaryLink(QCString(),convertToId(QCString(s)),QCString(s),first);
      first=FALSE;
    }
  }
  if (!first)
  {
    ol.writeString("  </div>\n");
  }
  ol.popGeneratorState();
}
References Config_getBool, convertToId(), MemberList::declVisible(), OutputList::disableAllBut(), FALSE, DefinitionMixin< ClassDefMutable >::getLanguage(), getMemberList(), getMemberListFileName(), Html, LayoutDocManager::instance(), MemberList::listType(), m_impl, OutputList::popGeneratorState(), Private, OutputList::pushGeneratorState(), theTranslator, LayoutDocEntryMemberDecl::title(), LayoutDocEntrySection::title(), MemberListType::toLabel(), Translator::trListOfAllMembers(), TRUE, LayoutDocEntryMemberDecl::type, VHDL, OutputList::writeString(), and OutputList::writeSummaryLink().
writeTagFile()
void ClassDefImpl::writeTagFile (TextStream & tagFile) const override virtual
Implements ClassDef.
Definition at line 2310 of file classdef.cpp.
{
  if (!isLinkableInProject() || isArtificial()) return;
  tagFile << "  <compound kind=\"";
  if (isFortran() && (compoundTypeString() == "type"))
    tagFile << "struct";
  else
    tagFile << compoundTypeString();
  tagFile << "\"";
  if (isObjectiveC()) { tagFile << " objc=\"yes\""; }
  tagFile << ">\n";
  tagFile << "    <name>" << convertToXML(name()) << "</name>\n";
  QCString fn = getOutputFileBase();
  addHtmlExtensionIfMissing(fn);
  tagFile << "    <filename>" << convertToXML(fn) << "</filename>\n";
  if (!anchor().isEmpty())
  {
    tagFile << "    <anchor>" << convertToXML(anchor()) << "</anchor>\n";
  }
  QCString idStr = id();
  if (!idStr.isEmpty())
  {
    tagFile << "    <clangid>" << convertToXML(idStr) << "</clangid>\n";
  }
  for (const Argument &a : m_impl->tempArgs)
  {
    tagFile << "    <templarg>" << convertToXML(a.type);
    if (!a.name.isEmpty())
    {
      tagFile << " " << convertToXML(a.name);
    }
    tagFile << "</templarg>\n";
  }
  for (const auto &ibcd : m_impl->inherits)
  {
    ClassDef *cd=ibcd.classDef;
    if (cd && cd->isLinkable())
    {
      tagFile << "    <base";
      if (ibcd.prot==Protection::Protected)
      {
        tagFile << " protection=\"protected\"";
      }
      else if (ibcd.prot==Protection::Private)
      {
        tagFile << " protection=\"private\"";
      }
      if (ibcd.virt==Specifier::Virtual)
      {
        tagFile << " virtualness=\"virtual\"";
      }
      QCString displayName = insertTemplateSpecifierInScope(
          cd->displayName(),ibcd.templSpecifiers);
      tagFile << ">" << convertToXML(displayName) << "</base>\n";
    }
  }
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Class))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::ClassNestedClasses:
        {
          for (const auto &innerCd : m_impl->innerClasses)
          {
            if (innerCd->isLinkableInProject() && innerCd->templateMaster()==nullptr &&
                protectionLevelVisible(innerCd->protection()) &&
                !innerCd->isEmbeddedInOuterScope()
               )
            {
              tagFile << "    <class kind=\"" << innerCd->compoundTypeString() <<
                "\">" << convertToXML(innerCd->name()) << "</class>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            MemberList * ml = getMemberList(lmd->type);
            if (ml)
            {
              ml->writeTagFile(tagFile);
            }
          }
        }
        break;
      case LayoutDocEntry::MemberGroups:
        {
          for (const auto &mg : m_impl->memberGroups)
          {
            mg->writeTagFile(tagFile);
          }
        }
        break;
     default:
        break;
    }
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << "  </compound>\n";
}
References addHtmlExtensionIfMissing(), anchor(), compoundTypeString(), convertToXML(), displayName(), Definition::displayName(), getMemberList(), getOutputFileBase(), DefinitionMixin< ClassDefMutable >::id(), insertTemplateSpecifierInScope(), LayoutDocManager::instance(), DefinitionMixin< ClassDefMutable >::isArtificial(), QCString::isEmpty(), isFortran(), Definition::isLinkable(), isLinkableInProject(), isObjectiveC(), m_impl, Argument::name, DefinitionMixin< ClassDefMutable >::name(), Private, Protected, protectionLevelVisible(), Argument::type, LayoutDocEntryMemberDecl::type, Virtual, DefinitionMixin< ClassDefMutable >::writeDocAnchorsToTagFile(), and MemberList::writeTagFile().
writeTemplateSpec()
void ClassDefImpl::writeTemplateSpec (OutputList & ol, const Definition * d, const QCString & type, SrcLangExt lang) const private
Definition at line 1510 of file classdef.cpp.
{
  ArgumentLists specs;
  QCString name;
  searchTemplateSpecs(d,specs,name,lang);
  if (!specs.empty()) // class has template scope specifiers
  {
    ol.startCompoundTemplateParams();
    for (const ArgumentList &al : specs)
    {
      ol.docify("template<");
      auto it = al.begin();
      while (it!=al.end())
      {
        Argument a = *it;
        linkifyText(TextGeneratorOLImpl(ol), // out
          d,                       // scope
          getFileDef(),            // fileScope
          this,                    // self
          a.type,                  // text
          FALSE                    // autoBreak
          );
        if (!a.name.isEmpty())
        {
          ol.docify(" ");
          ol.docify(a.name);
        }
        if (a.defval.length()!=0)
        {
          ol.docify(" = ");
          ol.docify(a.defval);
        }
        ++it;
        if (it!=al.end()) ol.docify(", ");
      }
      ol.docify(">");
      ol.lineBreak();
    }
    if (!m_impl->requiresClause.isEmpty())
    {
      ol.docify("requires ");
      linkifyText(TextGeneratorOLImpl(ol), // out
          d,                       // scope
          getFileDef(),            // fileScope
          this,                    // self
          m_impl->requiresClause,  // text
          FALSE                    // autoBreak
          );
      ol.lineBreak();
    }
    ol.docify(type.lower()+" "+name);
    ol.endCompoundTemplateParams();
  }
}
References Argument::defval, OutputList::docify(), OutputList::endCompoundTemplateParams(), FALSE, getFileDef(), QCString::isEmpty(), QCString::length(), OutputList::lineBreak(), linkifyText(), QCString::lower(), m_impl, Argument::name, Definition::name(), searchTemplateSpecs(), OutputList::startCompoundTemplateParams(), and Argument::type.
Referenced by writeDetailedDocumentationBody().
Member Data Documentation
m_impl
std::unique_ptr<IMPL> ClassDefImpl::m_impl private
Definition at line 409 of file classdef.cpp.
Referenced by addClassAttributes(), addExample(), addGroupedInheritedMembers(), addInnerCompound(), addListReferences(), addMembersToMemberGroup(), addMembersToTemplateInstance(), addMemberToList(), addQualifiers(), addTypeConstraint(), addTypeConstraints(), addUsedByClass(), addUsedClass(), anchor(), baseClasses(), categoryOf(), ClassDefImpl(), className(), collaborationGraphFileName(), compoundType(), compoundTypeString(), computeAnchors(), containsOverload(), countInheritedByNodes(), countInheritedDecMembers(), countInheritsNodes(), countMemberDeclarations(), countMembers(), countMembersIncludingGrouped(), deepCopy(), distributeMemberGroupDocumentation(), findInnerCompound(), findSectionsInDocumentation(), generatedFromFiles(), getClasses(), getExamples(), getFileDef(), getInstanceOutputFileBase(), getMemberByName(), getMemberGroups(), getMemberList(), getMemberListFileName(), getMemberLists(), getModuleDef(), getOutputFileBase(), getQualifiers(), getReference(), getSourceFileBase(), getTemplateBaseClassNames(), getTemplateInstances(), hasCollaborationGraph(), hasExamples(), hasInheritanceGraph(), includeInfo(), inheritanceGraphFileName(), insertBaseClass(), insertExplicitTemplateInstance(), insertSubClass(), insertTemplateInstance(), insertUsedFile(), internalInsertMember(), isAbstract(), isEmbeddedInOuterScope(), isFinal(), isForwardDeclared(), isImplicitTemplateInstance(), isInterface(), isJavaEnum(), isLinkable(), isLinkableInProject(), isLocal(), isPublished(), isReference(), isSealed(), isSimple(), isSliceLocal(), isSmartPointer(), isTemplate(), isTemplateArgument(), isUsedOnly(), isVisibleInHierarchy(), makeTemplateArgument(), memberNameInfoLinkedMap(), mergeCategory(), mergeMembers(), mergeMembersFromBaseClasses(), moveTo(), overrideCollaborationGraph(), overrideInheritanceGraph(), protection(), reclassifyMember(), removeMemberFromLists(), requiresClause(), setAnonymousEnumType(), setCategoryOf(), setClassName(), setClassSpecifier(), setCompoundType(), setFileDef(), setGroupDefForAllMembers(), setImplicitTemplateInstance(), setIncludeFile(), setIsStatic(), setMetaData(), setModuleDef(), setProtection(), setRequiresClause(), setSubGrouping(), setTagLessReference(), setTemplateArguments(), setTemplateBaseClassNames(), setTemplateMaster(), setTypeConstraints(), setUsedOnly(), showUsedFiles(), sortAllMembersList(), sortMemberLists(), subClasses(), subGrouping(), tagLessReference(), templateArguments(), templateMaster(), templateTypeConstraints(), title(), typeConstraints(), updateBaseClasses(), updateSubClasses(), usedByImplementationClasses(), usedFiles(), usedImplementationClasses(), writeCollaborationGraph(), writeDeclaration(), writeDetailedDocumentationBody(), writeDocumentationForInnerClasses(), writeIncludeFiles(), writeIncludeFilesForSlice(), writeInheritanceGraph(), writeInheritedMemberDeclarations(), writeInlineClasses(), writeInlineDocumentation(), writeMemberGroups(), writeMemberList(), writeMemberPages(), writeNestedClasses(), writeQuickMemberLinks(), writeSummaryLinks(), writeTagFile(), and writeTemplateSpec().
The documentation for this class was generated from the following file:
src/classdef.cpp