Doxygen: CPPValue Class Reference
CPPValue Class Reference
A class representing a C-preprocessor value.
#include <src/cppvalue.h>
Public Types
enum Type { Int , Float }
Public Member Functions
CPPValue (char c)
CPPValue (long val=0)
CPPValue (double val)
operator double () const
operator long () const
bool isInt () const
void print () const
Static Public Member Functions
static CPPValue parseOctal (const std::string &token)
static CPPValue parseDecimal (const std::string &token)
static CPPValue parseHexadecimal (const std::string &token)
static CPPValue parseBinary (const std::string &token)
static CPPValue parseCharacter (const std::string &token)
static CPPValue parseFloat (const std::string &token)
Private Attributes
Type type
union {
double d
long l
} v
Detailed Description
A class representing a C-preprocessor value.
Definition at line 23 of file cppvalue.h.
Member Enumeration Documentation
Type
enum CPPValue::Type
Enumerator
Int
Float
Definition at line 26 of file cppvalue.h.
{ Int, Float };
Constructor & Destructor Documentation
CPPValue() [1/3]
CPPValue::CPPValue (char c) inline explicit
Definition at line 28 of file cppvalue.h.
: type(Int) { v.l = c; }
References Int, type, and v.
Referenced by parseBinary(), parseCharacter(), parseDecimal(), parseFloat(), parseHexadecimal(), and parseOctal().
CPPValue() [2/3]
CPPValue::CPPValue (long val = 0) inline explicit
Definition at line 29 of file cppvalue.h.
: type(Int) { v.l = val; }
References Int, type, and v.
CPPValue() [3/3]
CPPValue::CPPValue (double val) inline explicit
Definition at line 30 of file cppvalue.h.
: type(Float) { v.d = val; }
References Float, type, and v.
Member Function Documentation
isInt()
bool CPPValue::isInt () const inline
Definition at line 35 of file cppvalue.h.
{ return type == Int; }
References Int, and type.
operator double()
CPPValue::operator double () const inline
Definition at line 32 of file cppvalue.h.
{ return type==Int ? static_cast<double>(v.l) : v.d; }
References Int, type, and v.
operator long()
CPPValue::operator long () const inline
Definition at line 33 of file cppvalue.h.
{ return type==Int ? v.l : static_cast<long>(v.d);   }
References Int, type, and v.
parseBinary()
CPPValue CPPValue::parseBinary (const std::string & token) static
Definition at line 54 of file cppvalue.cpp.
{
  long val = 0;
  for (const char *p = token.c_str(); *p != 0; p++)
  {
    if (*p >= '0' && *p <= '1') val = val * 2 + *p - '0';
  }
  return CPPValue(val);
}
References CPPValue().
parseCharacter()
CPPValue CPPValue::parseCharacter (const std::string & token) static
Definition at line 64 of file cppvalue.cpp.
{
  if (token[1]=='\\')
  {
    switch(token[2])
    {
      case 'n':  return CPPValue('\n');
      case 't':  return CPPValue('\t');
      case 'v':  return CPPValue('\v');
      case 'b':  return CPPValue('\b');
      case 'r':  return CPPValue('\r');
      case 'f':  return CPPValue('\f');
      case 'a':  return CPPValue('\a');
      case '\\': return CPPValue('\\');
      case '?':  return CPPValue('\?');
      case '\'': return CPPValue('\'');
      case '"':  return CPPValue('"');
      case '0':  // fall through
      case '1':  // fall through
      case '2':  // fall through
      case '3':  // fall through
      case '4':  // fall through
      case '5':  // fall through
      case '6':  // fall through
      case '7':  // fall through
                 return parseOctal(token);
      case 'x':
      case 'X':  return parseHexadecimal(token);
      default:   printf("Invalid escape sequence %s found!\n",token.c_str());
                 return CPPValue(0L);
    }
  }
  return CPPValue(token[1]);
}
References CPPValue(), parseHexadecimal(), and parseOctal().
parseDecimal()
CPPValue CPPValue::parseDecimal (const std::string & token) static
Definition at line 31 of file cppvalue.cpp.
{
  long val = 0;
  for (const char *p = token.c_str(); *p != 0; p++)
  {
    if (*p >= '0' && *p <= '9') val = val * 10 + *p - '0';
  }
  return CPPValue(val);
}
References CPPValue().
parseFloat()
CPPValue CPPValue::parseFloat (const std::string & token) static
Definition at line 99 of file cppvalue.cpp.
{
  return CPPValue(std::stod(token));
}
References CPPValue().
parseHexadecimal()
CPPValue CPPValue::parseHexadecimal (const std::string & token) static
Definition at line 41 of file cppvalue.cpp.
{
  long val = 0;
  for (const char *p = token.c_str(); *p != 0; p++)
  {
    if      (*p >= '0' && *p <= '9') val = val * 16 + *p - '0';
    else if (*p >= 'a' && *p <= 'f') val = val * 16 + *p - 'a' + 10;
    else if (*p >= 'A' && *p <= 'F') val = val * 16 + *p - 'A' + 10;
  }
  //printf("parseHexadecimal %s->%x\n",qPrint(token),val);
  return CPPValue(val);
}
References CPPValue().
Referenced by parseCharacter().
parseOctal()
CPPValue CPPValue::parseOctal (const std::string & token) static
Definition at line 21 of file cppvalue.cpp.
{
  long val = 0;
  for (const char *p = token.c_str(); *p != 0; p++)
  {
    if (*p >= '0' && *p <= '7') val = val * 8 + *p - '0';
  }
  return CPPValue(val);
}
References CPPValue().
Referenced by parseCharacter().
print()
void CPPValue::print () const inline
Definition at line 37 of file cppvalue.h.
    {
      if (type==Int)
        printf("(%ld)\n",v.l);
      else
        printf("(%f)\n",v.d);
    }
References Int, type, and v.
Member Data Documentation
d
double CPPValue::d
Definition at line 54 of file cppvalue.h.
l
long CPPValue::l
Definition at line 55 of file cppvalue.h.
type
Type CPPValue::type private
Definition at line 52 of file cppvalue.h.
Referenced by CPPValue(), CPPValue(), CPPValue(), isInt(), operator double(), operator long(), and print().
[union]
union { ... } CPPValue::v
Referenced by CPPValue(), CPPValue(), CPPValue(), operator double(), operator long(), and print().
The documentation for this class was generated from the following files:
src/cppvalue.h
src/cppvalue.cpp