Doxygen: DocRoot Class Reference
DocRoot Class Reference
Root node of documentation tree.
#include <docnode.h>
Public Member Functions
DocRoot (DocParser *parser, bool indent, bool sl)
void parse ()
bool indent () const
bool singleLine () const
bool isEmpty () const
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
DocNode (const DocNode &)=delete
DocNode & operator= (const DocNode &)=delete
DocNode (DocNode &&)=default
DocNode & operator= (DocNode &&)=default
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
bool m_indent = false
bool m_singleLine = false
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Root node of documentation tree.
Definition at line 1273 of file docnode.h.
Constructor & Destructor Documentation
DocRoot()
DocRoot::DocRoot (DocParser * parser, bool indent, bool sl) inline
Definition at line 1276 of file docnode.h.
      : DocCompoundNode(parser,0), m_indent(indent), m_singleLine(sl) {}
Member Function Documentation
indent()
bool DocRoot::indent () const inline
Definition at line 1279 of file docnode.h.
{ return m_indent; }
References m_indent.
Referenced by RTFDocVisitor::operator()().
isEmpty()
bool DocRoot::isEmpty () const inline
Definition at line 1281 of file docnode.h.
{ return children().empty(); }
References DocCompoundNode::children(), and GrowVector< T >::empty().
parse()
void DocRoot::parse ()
Definition at line 5728 of file docnode.cpp.
{
  AUTO_TRACE();
  auto ns = AutoNodeStack(parser(),thisVariant());
  parser()->tokenizer.setStatePara();
  int retval=0;
  // first parse any number of paragraphs
  bool isFirst=TRUE;
  DocPara *lastPar = nullptr;
  do
  {
    {
      children().append<DocPara>(parser(),thisVariant());
      DocPara *par  = children().get_last<DocPara>();
      if (isFirst) { par->markFirst(); isFirst=FALSE; }
      retval=par->parse();
      if (par->isEmpty() && par->attribs().empty())
      {
        children().pop_back();
      }
      else
      {
        lastPar = par;
      }
    }
    if (retval == RetVal_Paragraph)
    {
      if (!AnchorGenerator::instance().isGenerated(parser()->context.token->sectionId.str()))
      {
        warn_doc_error(parser()->context.fileName,
                       parser()->tokenizer.getLineNr(),
                       "found paragraph command (id: '%s') outside of subsubsection context!",
                       qPrint(parser()->context.token->sectionId));
      }
      while (retval==RetVal_Paragraph)
      {
        if (!parser()->context.token->sectionId.isEmpty())
        {
          const SectionInfo *sec=SectionManager::instance().find(parser()->context.token->sectionId);
          if (sec)
          {
            children().append<DocSection>(parser(),thisVariant(),
                                    4,
                                    parser()->context.token->sectionId);
            retval = children().get_last<DocSection>()->parse();
          }
          else
          {
            warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Invalid paragraph id '%s'; ignoring paragraph",qPrint(parser()->context.token->sectionId));
            retval = 0;
          }
        }
        else
        {
          warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Missing id for paragraph; ignoring paragraph");
          retval = 0;
        }
      }
    }
    if (retval==RetVal_Subsubsection)
    {
      if (!AnchorGenerator::instance().isGenerated(parser()->context.token->sectionId.str()))
      {
        warn_doc_error(parser()->context.fileName,
                       parser()->tokenizer.getLineNr(),
                       "found subsubsection command (id: '%s') outside of subsection context!",
                       qPrint(parser()->context.token->sectionId));
      }
      while (retval==RetVal_Subsubsection)
      {
        if (!parser()->context.token->sectionId.isEmpty())
        {
          const SectionInfo *sec=SectionManager::instance().find(parser()->context.token->sectionId);
          if (sec)
          {
            children().append<DocSection>(parser(),thisVariant(),
                                    3,
                                    parser()->context.token->sectionId);
            retval = children().get_last<DocSection>()->parse();
          }
          else
          {
            warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Invalid subsubsection id '%s'; ignoring subsubsection",qPrint(parser()->context.token->sectionId));
            retval = 0;
          }
        }
        else
        {
          warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Missing id for subsubsection; ignoring subsubsection");
          retval = 0;
        }
      }
    }
    if (retval==RetVal_Subsection)
    {
      if (!AnchorGenerator::instance().isGenerated(parser()->context.token->sectionId.str()))
      {
        warn_doc_error(parser()->context.fileName,
                       parser()->tokenizer.getLineNr(),
                       "found subsection command (id: '%s') outside of section context!",
                       qPrint(parser()->context.token->sectionId));
      }
      while (retval==RetVal_Subsection)
      {
        if (!parser()->context.token->sectionId.isEmpty())
        {
          const SectionInfo *sec=SectionManager::instance().find(parser()->context.token->sectionId);
          if (sec)
          {
            children().append<DocSection>(parser(),thisVariant(),
                                    2,
                                    parser()->context.token->sectionId);
            retval = children().get_last<DocSection>()->parse();
          }
          else
          {
            warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Invalid subsection id '%s'; ignoring subsection",qPrint(parser()->context.token->sectionId));
            retval = 0;
          }
        }
        else
        {
          warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Missing id for subsection; ignoring subsection");
          retval = 0;
        }
      }
    }
    if (retval==TK_LISTITEM)
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Invalid list item found");
    }
    if (retval==RetVal_Internal)
    {
      children().append<DocInternal>(parser(),thisVariant());
      retval = children().get_last<DocInternal>()->parse(1);
    }
  } while (retval!=0 && retval!=RetVal_Section);
  if (lastPar) lastPar->markLast();
  //printf("DocRoot::parse() retval=%d %d\n",retval,RetVal_Section);
  // then parse any number of level1 sections
  while (retval==RetVal_Section)
  {
    if (!parser()->context.token->sectionId.isEmpty())
    {
      const SectionInfo *sec=SectionManager::instance().find(parser()->context.token->sectionId);
      if (sec)
      {
        children().append<DocSection>(parser(),thisVariant(),
                                1,
                                parser()->context.token->sectionId);
        retval = children().get_last<DocSection>()->parse();
      }
      else
      {
        warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Invalid section id '%s'; ignoring section",qPrint(parser()->context.token->sectionId));
        retval = 0;
      }
    }
    else
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Missing id for section; ignoring section");
      retval = 0;
    }
  }
  parser()->handleUnclosedStyleCommands();
}
References DocNodeList::append(), AUTO_TRACE, DocCompoundNode::children(), DocParser::context, FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), DocNodeList::get_last(), DocParser::handleUnclosedStyleCommands(), AnchorGenerator::instance(), SectionManager::instance(), DocPara::markFirst(), DocPara::markLast(), parse(), DocNode::parser(), GrowVector< T >::pop_back(), qPrint(), RetVal_Internal, RetVal_Paragraph, RetVal_Section, RetVal_Subsection, RetVal_Subsubsection, TokenInfo::sectionId, DocTokenizer::setStatePara(), DocNode::thisVariant(), TK_LISTITEM, DocParserContext::token, DocParser::tokenizer, TRUE, and warn_doc_error.
Referenced by parse().
singleLine()
bool DocRoot::singleLine () const inline
Definition at line 1280 of file docnode.h.
{ return m_singleLine; }
References m_singleLine.
Referenced by RTFDocVisitor::operator()().
Member Data Documentation
m_indent
bool DocRoot::m_indent = false private
Definition at line 1284 of file docnode.h.
Referenced by indent().
m_singleLine
bool DocRoot::m_singleLine = false private
Definition at line 1285 of file docnode.h.
Referenced by singleLine().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/docnode.h
/home/runner/work/doxygen/doxygen/src/docnode.cpp