Doxygen: PageDefImpl Class Reference
PageDefImpl Class Reference
Public Member Functions
PageDefImpl (const QCString &f, int l, const QCString &n, const QCString &d, const QCString &t)
~PageDefImpl () override
void setFileName (const QCString &name) override
void setLocalToc (const LocalToc &tl) override
void setShowLineNo (bool) override
DefType definitionType () const override
CodeSymbolType codeSymbolType () const override
bool isLinkableInProject () const override
bool isLinkable () const override
QCString getOutputFileBase () const override
QCString anchor () const override
void findSectionsInDocumentation () override
QCString title () const override
const GroupDef * getGroupDef () const override
const PageLinkedRefMap & getSubPages () const override
void addInnerCompound (Definition *d) override
bool visibleInIndex () const override
bool documentedPage () const override
bool hasSubPages () const override
bool hasParentPage () const override
bool hasTitle () const override
LocalToc localToc () const override
void setPageScope (Definition *d) override
Definition * getPageScope () const override
QCString displayName (bool=TRUE) const override
bool showLineNo () const override
void setTitle (const QCString &title) override
void writeDocumentation (OutputList &ol) override
void writeTagFile (TextStream &) override
void setNestingLevel (int l) override
void writePageDocumentation (OutputList &ol) const override
void addSectionsToIndex () override
Public Member Functions inherited from DefinitionMixin< PageDef >
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=nullptr, const char *d=nullptr, bool isSymbol=TRUE)
DefinitionMixin (const DefinitionMixin &other)
DefinitionMixin (DefinitionMixin &&)=delete
DefinitionMixin & operator= (const DefinitionMixin &other)
DefinitionMixin & operator= (DefinitionMixin &&)=delete
~DefinitionMixin () override=default
bool isAlias () const override
const QCString & name () const override
bool isAnonymous () const override
const QCString & localName () const override
QCString qualifiedName () const override
QCString symbolName () const override
QCString getSourceFileBase () const override
QCString getSourceAnchor () const override
QCString documentation () const override
int docLine () const override
QCString docFile () const override
QCString briefDescription (bool abbreviate=FALSE) const override
QCString briefDescriptionAsTooltip () const override
int briefLine () const override
QCString inbodyDocumentation () const override
QCString inbodyFile () const override
int inbodyLine () const override
QCString briefFile () const override
QCString getDefFileName () const override
QCString getDefFileExtension () const override
int getDefLine () const override
int getDefColumn () const override
bool hasDocumentation () const override
bool hasUserDocumentation () const override
bool isVisibleInProject () const override
bool isVisible () const override
bool isHidden () const override
bool isArtificial () const override
bool isExported () const override
QCString getReference () const override
bool isReference () const override
QCString externalReference (const QCString &relPath) const override
int getStartDefLine () const override
int getStartBodyLine () const override
int getEndBodyLine () const override
const FileDef * getBodyDef () const override
SrcLangExt getLanguage () const override
const GroupList & partOfGroups () const override
bool isLinkableViaGroup () const override
const RefItemVector & xrefListItems () const override
const Definition * findInnerCompound (const QCString &name) const override
Definition * getOuterScope () const override
const MemberVector & getReferencesMembers () const override
const MemberVector & getReferencedByMembers () const override
bool hasSections () const override
bool hasSources () const override
bool hasBriefDescription () const override
QCString id () const override
const SectionRefs & getSectionRefs () const override
void setName (const QCString &name) override
void setId (const QCString &name) override
void setDefFile (const QCString &df, int defLine, int defColumn) override
void setDocumentation (const QCString &doc, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE) override
void setBriefDescription (const QCString &brief, const QCString &briefFile, int briefLine) override
void setInbodyDocumentation (const QCString &doc, const QCString &docFile, int docLine) override
void setReference (const QCString &r) override
void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList) override
void setBodySegment (int defLine, int bls, int ble) override
void setBodyDef (const FileDef *fd) override
void addSourceReferencedBy (MemberDef *md, const QCString &sourceRefName) override
void addSourceReferences (MemberDef *md, const QCString &sourceRefName) override
void setRefItems (const RefItemVector &sli) override
void mergeRefItems (Definition *def) override
void mergeReferences (const Definition *other) override
void mergeReferencedBy (const Definition *other) override
void setOuterScope (Definition *def) override
void setHidden (bool b) override
void setArtificial (bool b) override
void setExported (bool b) override
void setLanguage (SrcLangExt lang) override
void writeSourceDef (OutputList &ol) const override
void writeInlineCode (OutputList &ol, const QCString &scopeName) const override
bool hasSourceRefs () const override
bool hasSourceReffedBy () const override
void writeSourceRefs (OutputList &ol, const QCString &scopeName) const override
void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const override
void makePartOfGroup (GroupDef *gd) override
void writeNavigationPath (OutputList &ol) const override
QCString navigationPathAsString () const override
void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const override
void writeSummaryLinks (OutputList &ol) const override
QCString pathFragment () const override
void writeDocAnchorsToTagFile (TextStream &fs) const override
void setLocalName (const QCString &name) override
void writeToc (OutputList &ol, const LocalToc &lt) const override
void computeTooltip () override
void _setSymbolName (const QCString &name) override
QCString _symbolName () const override
Public Member Functions inherited from PageDef
Public Member Functions inherited from DefinitionMutable
Public Member Functions inherited from Definition
Private Attributes
QCString m_fileName
QCString m_title
PageLinkedRefMap m_subPages
Definition * m_pageScope
int m_nestingLevel
LocalToc m_localToc
bool m_showLineNo
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Detailed Description
Definition at line 31 of file pagedef.cpp.
Constructor & Destructor Documentation
PageDefImpl()
PageDefImpl::PageDefImpl (const QCString & f, int l, const QCString & n, const QCString & d, const QCString & t)
Definition at line 86 of file pagedef.cpp.
 : DefinitionMixin(f,l,1,n), m_title(!t.isEmpty() ? t : n)
{
  setDocumentation(d,f,l);
  m_pageScope = nullptr;
  m_nestingLevel = 0;
  m_fileName = ::convertNameToFile(n,FALSE,TRUE);
  m_showLineNo = FALSE;
}
References convertNameToFile(), DefinitionMixin< PageDef >::DefinitionMixin(), FALSE, m_fileName, m_nestingLevel, m_pageScope, m_showLineNo, m_title, DefinitionMixin< PageDef >::setDocumentation(), and TRUE.
~PageDefImpl()
PageDefImpl::~PageDefImpl () override
Definition at line 97 of file pagedef.cpp.
{
}
Member Function Documentation
addInnerCompound()
void PageDefImpl::addInnerCompound (Definition * d) override virtual
Reimplemented from DefinitionMixin< PageDef >.
Definition at line 126 of file pagedef.cpp.
{
  if (def->definitionType()==Definition::TypePage)
  {
    PageDef *pd = toPageDef(def);
    if (pd)
    {
      m_subPages.add(pd->name(),pd);
      pd->setOuterScope(this);
      if (this==Doxygen::mainPage.get())
      {
        pd->setNestingLevel(m_nestingLevel);
      }
      else
      {
        pd->setNestingLevel(m_nestingLevel+1);
      }
    }
  }
}
References Definition::definitionType(), m_nestingLevel, m_subPages, Doxygen::mainPage, Definition::name(), PageDef::setNestingLevel(), DefinitionMutable::setOuterScope(), toPageDef(), and Definition::TypePage.
addSectionsToIndex()
void PageDefImpl::addSectionsToIndex () override virtual
Implements PageDef.
Definition at line 147 of file pagedef.cpp.
{
  const SectionRefs &sectionRefs = getSectionRefs();
  if (sectionRefs.empty()) return;
  //printf("PageDefImpl::addSectionsToIndex()\n");
  int level=1;
  for (auto it = sectionRefs.begin(); it!=sectionRefs.end(); ++it)
  {
    const SectionInfo *si = *it;
    SectionType type = si->type();
    if (type.isSection())
    {
      //printf("  level=%d title=%s\n",level,qPrint(si->title));
      int nextLevel = type.level();
      if (nextLevel>level)
      {
        for (int i=level;i<nextLevel;i++)
        {
          Doxygen::indexList->incContentsDepth();
        }
      }
      else if (nextLevel<level)
      {
        for (int i=nextLevel;i<level;i++)
        {
          Doxygen::indexList->decContentsDepth();
        }
      }
      QCString title = si->title();
      if (title.isEmpty()) title = si->label();
      title = parseCommentAsText(this,nullptr,title,si->fileName(),si->lineNr());
      // determine if there is a next level inside this item, but be aware of the anchor and table section references.
      auto it_next = std::next(it);
      bool isDir = (it_next!=sectionRefs.end()) ?  ((*it_next)->type().isSection() && (*it_next)->type().level() > nextLevel) : false;
      Doxygen::indexList->addContentsItem(isDir,title,
                                         getReference(),
                                         getOutputFileBase(),
                                         si->label(),
                                         false,
                                         true);
      level = nextLevel;
    }
  }
  while (level>1)
  {
    Doxygen::indexList->decContentsDepth();
    level--;
  }
}
References IndexList::addContentsItem(), SectionRefs::begin(), IndexList::decContentsDepth(), SectionRefs::empty(), SectionRefs::end(), SectionInfo::fileName(), getOutputFileBase(), DefinitionMixin< PageDef >::getReference(), DefinitionMixin< PageDef >::getSectionRefs(), IndexList::incContentsDepth(), Doxygen::indexList, SectionType::isSection(), SectionInfo::label(), SectionType::level(), SectionInfo::lineNr(), parseCommentAsText(), title(), SectionInfo::title(), and SectionInfo::type().
anchor()
QCString PageDefImpl::anchor () const inline override virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 46 of file pagedef.cpp.
{ return QCString(); }
codeSymbolType()
CodeSymbolType PageDefImpl::codeSymbolType () const inline override virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 42 of file pagedef.cpp.
{ return CodeSymbolType::Default; }
References Default.
definitionType()
DefType PageDefImpl::definitionType () const inline override virtual
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Definition at line 41 of file pagedef.cpp.
{ return TypePage; }
References Definition::TypePage.
displayName()
QCString PageDefImpl::displayName (bool includeScope = TRUE) const inline override virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 60 of file pagedef.cpp.
{ return hasTitle() ? m_title : DefinitionMixin::name(); }
References hasTitle(), m_title, and DefinitionMixin< Base >::name().
documentedPage()
bool PageDefImpl::documentedPage () const override virtual
Implements PageDef.
Definition at line 422 of file pagedef.cpp.
{
   return // not part of a group
          !getGroupDef() &&
          // not an externally defined page
          !isReference();
}
References getGroupDef(), and DefinitionMixin< PageDef >::isReference().
findSectionsInDocumentation()
void PageDefImpl::findSectionsInDocumentation () override virtual
Implements PageDef.
Definition at line 101 of file pagedef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
  docFindSections(inbodyDocumentation(),this,docFile());
}
References DefinitionMixin< PageDef >::briefDescription(), DefinitionMixin< PageDef >::docFile(), docFindSections(), DefinitionMixin< PageDef >::documentation(), and DefinitionMixin< PageDef >::inbodyDocumentation().
getGroupDef()
const GroupDef * PageDefImpl::getGroupDef () const override virtual
Implements PageDef.
Definition at line 108 of file pagedef.cpp.
{
  return !partOfGroups().empty() ? partOfGroups().front() : nullptr;
}
References DefinitionMixin< PageDef >::partOfGroups().
Referenced by documentedPage(), getOutputFileBase(), and visibleInIndex().
getOutputFileBase()
QCString PageDefImpl::getOutputFileBase () const override virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 113 of file pagedef.cpp.
{
  if (getGroupDef())
    return getGroupDef()->getOutputFileBase();
  else
    return m_fileName;
}
References getGroupDef(), Definition::getOutputFileBase(), and m_fileName.
Referenced by addSectionsToIndex(), writeDocumentation(), and writeTagFile().
getPageScope()
Definition * PageDefImpl::getPageScope () const inline override virtual
Implements PageDef.
Definition at line 59 of file pagedef.cpp.
{ return m_pageScope; }
References m_pageScope.
getSubPages()
const PageLinkedRefMap & PageDefImpl::getSubPages () const inline override virtual
Implements PageDef.
Definition at line 50 of file pagedef.cpp.
{ return m_subPages; }
References m_subPages.
hasParentPage()
bool PageDefImpl::hasParentPage () const override virtual
Implements PageDef.
Definition at line 197 of file pagedef.cpp.
{
  return getOuterScope() &&
         getOuterScope()->definitionType()==Definition::TypePage;
}
References Definition::definitionType(), DefinitionMixin< PageDef >::getOuterScope(), and Definition::TypePage.
hasSubPages()
bool PageDefImpl::hasSubPages () const override virtual
Implements PageDef.
Definition at line 430 of file pagedef.cpp.
{
  return !m_subPages.empty();
}
References m_subPages.
Referenced by writePageDocumentation().
hasTitle()
bool PageDefImpl::hasTitle () const override virtual
Implements PageDef.
Definition at line 455 of file pagedef.cpp.
{
  return !m_title.isEmpty() && m_title.lower()!="notitle";
}
References m_title.
Referenced by displayName(), and writeDocumentation().
isLinkable()
bool PageDefImpl::isLinkable () const inline override virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 44 of file pagedef.cpp.
{ return isLinkableInProject() || isReference(); }
References isLinkableInProject(), and DefinitionMixin< PageDef >::isReference().
isLinkableInProject()
bool PageDefImpl::isLinkableInProject () const inline override virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 43 of file pagedef.cpp.
{ return /*hasDocumentation() &&*/ !isReference(); }
References DefinitionMixin< PageDef >::isReference().
Referenced by isLinkable().
localToc()
LocalToc PageDefImpl::localToc () const inline override virtual
Implements PageDef.
Definition at line 57 of file pagedef.cpp.
{ return m_localToc; }
References m_localToc.
setFileName()
void PageDefImpl::setFileName (const QCString & name) override virtual
Implements PageDef.
Definition at line 121 of file pagedef.cpp.
{
  m_fileName = name;
}
References m_fileName, Definition::name(), and DefinitionMixin< PageDef >::name().
setLocalToc()
void PageDefImpl::setLocalToc (const LocalToc & tl) override virtual
Implements PageDef.
Definition at line 440 of file pagedef.cpp.
{
  m_localToc = lt;
}
References m_localToc.
setNestingLevel()
void PageDefImpl::setNestingLevel (int l) override virtual
Implements PageDef.
Definition at line 435 of file pagedef.cpp.
{
  m_nestingLevel = l;
}
References m_nestingLevel.
setPageScope()
void PageDefImpl::setPageScope (Definition * d) inline override virtual
Implements PageDef.
Definition at line 58 of file pagedef.cpp.
{ m_pageScope = d; }
References m_pageScope.
setShowLineNo()
void PageDefImpl::setShowLineNo (bool b) override virtual
Implements PageDef.
Definition at line 445 of file pagedef.cpp.
{
  m_showLineNo = b;
}
References m_showLineNo.
setTitle()
void PageDefImpl::setTitle (const QCString & title) override virtual
Implements PageDef.
Definition at line 460 of file pagedef.cpp.
{
  m_title = title;
}
References m_title, and title().
showLineNo()
bool PageDefImpl::showLineNo () const override virtual
Implements PageDef.
Definition at line 450 of file pagedef.cpp.
{
  return m_showLineNo;
}
References m_showLineNo.
title()
QCString PageDefImpl::title () const inline override virtual
Implements PageDef.
Definition at line 48 of file pagedef.cpp.
{ return m_title; }
References m_title.
Referenced by addSectionsToIndex(), setTitle(), writeDocumentation(), and writeTagFile().
visibleInIndex()
bool PageDefImpl::visibleInIndex () const override virtual
Implements PageDef.
Definition at line 413 of file pagedef.cpp.
{
  bool externalPages = Config_getBool(EXTERNAL_PAGES);
  return // not part of a group
         !getGroupDef() &&
         // not an externally defined page
         (!isReference() || externalPages);
}
References Config_getBool, getGroupDef(), and DefinitionMixin< PageDef >::isReference().
writeDocumentation()
void PageDefImpl::writeDocumentation (OutputList & ol) override virtual
Implements PageDef.
Definition at line 233 of file pagedef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  int hierarchyLevel = -1; // Pages start at the root
  PageDef *pd = this;
  while (pd->hasParentPage())
  {
    pd = (PageDef *)pd->getOuterScope();
    ++hierarchyLevel;
  }
  //outputList->disable(OutputType::Man);
  QCString pageName,manPageName;
  pageName    = escapeCharsInString(name(),FALSE,TRUE);
  manPageName = escapeCharsInString(name(),TRUE,TRUE);
  //printf("PageDefImpl::writeDocumentation: %s\n",getOutputFileBase().data());
  ol.pushGeneratorState();
  //1.{
  ol.pushGeneratorState();
  //2.{
  ol.disableAllBut(OutputType::Man);
  startFile(ol,getOutputFileBase(),manPageName,title(),HighlightedItem::Pages,!generateTreeView,
            QCString() /* altSidebarName */, hierarchyLevel);
  ol.enableAll();
  ol.disable(OutputType::Man);
  startFile(ol,getOutputFileBase(),pageName,title(),HighlightedItem::Pages,!generateTreeView,
            QCString() /* altSidebarName */, hierarchyLevel);
  ol.popGeneratorState();
  //2.}
  if (!generateTreeView)
  {
    if (getOuterScope()!=Doxygen::globalScope && !Config_getBool(DISABLE_INDEX))
    {
      DefinitionMutable *outerScope = toDefinitionMutable(getOuterScope());
      if (outerScope)
      {
        outerScope->writeNavigationPath(ol);
      }
    }
    ol.endQuickIndices();
  }
  const SectionInfo *si=SectionManager::instance().find(name());
  // save old generator state and write title only to Man generator
  ol.pushGeneratorState();
  //2.{
  ol.disableAllBut(OutputType::Man);
  ol.startTitleHead(manPageName);
  ol.endTitleHead(manPageName, manPageName);
  if (si)
  {
    ol.writeString(" - ");
    if (si->title() != manPageName)
    {
      ol.generateDoc(docFile(),getStartBodyLine(),this,nullptr,si->title(),TRUE,FALSE,
                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
      ol.endSection(si->label(),si->type());
    }
  }
  ol.popGeneratorState();
  //2.}
  ol.pushGeneratorState();
  //2.{
  ol.disable(OutputType::Man);
  QCString title;
  if (this == Doxygen::mainPage.get() && !hasTitle())
    title = theTranslator->trMainPage();
  else
    title = m_title;
  if (!title.isEmpty() && !name().isEmpty() && si!=nullptr)
  {
    ol.startPageDoc(si->title());
    //ol.startSection(si->label,si->title,si->type);
    ol.startHeaderSection();
    ol.startTitleHead(getOutputFileBase());
    ol.parseText(title);
    ol.endTitleHead(getOutputFileBase(),title);
    ol.endHeaderSection();
    /*ol.generateDoc(docFile(),getStartBodyLine(),this,nullptr,si->title(),TRUE,FALSE,
                   QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));*/
  }
  else
    ol.startPageDoc("");
  ol.popGeneratorState();
  //2.}
  ol.startContents();
  if ((m_localToc.isHtmlEnabled() || m_localToc.isLatexEnabled() || m_localToc.isDocbookEnabled())
    && hasSections())
  {
    writeToc(ol, m_localToc);
  }
  writePageDocumentation(ol);
  ol.endContents();
  ol.endPageDoc();
  if (generateTreeView && getOuterScope()!=Doxygen::globalScope && !Config_getBool(DISABLE_INDEX))
  {
    endFileWithNavPath(ol,getOuterScope());
  }
  else
  {
    endFile(ol,FALSE,TRUE);
  }
  ol.popGeneratorState();
  //1.}
}
References Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< PageDef >::docFile(), OutputList::enableAll(), OutputList::endContents(), endFile(), endFileWithNavPath(), OutputList::endHeaderSection(), OutputList::endPageDoc(), OutputList::endQuickIndices(), OutputList::endSection(), OutputList::endTitleHead(), escapeCharsInString(), FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), OutputList::generateDoc(), Definition::getOuterScope(), DefinitionMixin< PageDef >::getOuterScope(), getOutputFileBase(), DefinitionMixin< PageDef >::getStartBodyLine(), Doxygen::globalScope, PageDef::hasParentPage(), Definition::hasSections(), hasTitle(), SectionManager::instance(), SectionInfo::label(), m_localToc, m_title, Doxygen::mainPage, Man, Definition::name(), DefinitionMixin< PageDef >::name(), Pages, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startContents(), startFile(), OutputList::startHeaderSection(), OutputList::startPageDoc(), OutputList::startTitleHead(), theTranslator, title(), SectionInfo::title(), Definition::toDefinitionMutable, Translator::trMainPage(), TRUE, SectionInfo::type(), DefinitionMutable::writeNavigationPath(), writePageDocumentation(), OutputList::writeString(), and DefinitionMixin< PageDef >::writeToc().
writePageDocumentation()
void PageDefImpl::writePageDocumentation (OutputList & ol) const override virtual
Implements PageDef.
Definition at line 351 of file pagedef.cpp.
{
  ol.startTextBlock();
  QCString docStr = (briefDescription().isEmpty()?"":briefDescription()+"\n\n")+documentation()+inbodyDocumentation();
  if (hasBriefDescription() && !SectionManager::instance().find(name()))
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputType::Man);
    ol.writeString(" - ");
    ol.popGeneratorState();
  }
  ol.disableAllBut(OutputType::Html);
    ol.generateDoc(
      docFile(),           // fileName
      docLine(),           // startLine
      this,                // context
      nullptr,             // memberdef
      docStr,              // docStr
      true,                // index words
      false,               // not an example
      QCString(),          // exampleName
      false,               // singleLine
      false,               // linkFromIndex
      TRUE                 // markdown support
      );
  ol.enableAll();
  ol.disable(OutputType::Html);
    ol.generateDoc(
      docFile(),           // fileName
      docLine(),           // startLine
      this,                // context
      nullptr,             // memberdef
      docStr,              // docStr
      false,               // index words
      false,               // not an example
      QCString(),          // exampleName
      false,               // singleLine
      false,               // linkFromIndex
      TRUE                 // markdown support
      );
  ol.enable(OutputType::Html);
  ol.endTextBlock();
  if (hasSubPages())
  {
    // for printed documentation we write subpages as section's of the
    // parent page.
    ol.pushGeneratorState();
    ol.disableAll();
    ol.enable(OutputType::Latex);
    ol.enable(OutputType::Docbook);
    ol.enable(OutputType::RTF);
    for (const auto &subPage : m_subPages)
    {
      ol.writePageLink(subPage->getOutputFileBase(), FALSE);
    }
    ol.popGeneratorState();
  }
}
References DefinitionMixin< PageDef >::briefDescription(), OutputList::disable(), OutputList::disableAll(), OutputList::disableAllBut(), Docbook, DefinitionMixin< PageDef >::docFile(), DefinitionMixin< PageDef >::docLine(), DefinitionMixin< PageDef >::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endTextBlock(), FALSE, OutputList::generateDoc(), DefinitionMixin< PageDef >::hasBriefDescription(), hasSubPages(), Html, DefinitionMixin< PageDef >::inbodyDocumentation(), SectionManager::instance(), QCString::isEmpty(), Latex, m_subPages, Man, DefinitionMixin< PageDef >::name(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), RTF, OutputList::startTextBlock(), TRUE, OutputList::writePageLink(), and OutputList::writeString().
Referenced by writeDocumentation().
writeTagFile()
void PageDefImpl::writeTagFile (TextStream & tagFile) override virtual
Implements PageDef.
Definition at line 203 of file pagedef.cpp.
{
  bool found = name()=="citelist";
  for (RefListManager::Ptr &rl : RefListManager::instance())
  {
    if (rl->listName()==name())
    {
      found=TRUE;
      break;
    }
  }
  if (!found) // not one of the generated related pages
  {
    QCString fn = getOutputFileBase();
    addHtmlExtensionIfMissing(fn);
    tagFile << "  <compound kind=\"page\">\n";
    tagFile << "    <name>" << name() << "</name>\n";
    tagFile << "    <title>" << convertToXML(title()) << "</title>\n";
    tagFile << "    <filename>" << fn << "</filename>\n";
    for (const auto &subPage : m_subPages)
    {
      QCString sfn = subPage->getOutputFileBase();
      addHtmlExtensionIfMissing(sfn);
      tagFile << "    <subpage>" << sfn << "</subpage>\n";
    }
    writeDocAnchorsToTagFile(tagFile);
    tagFile << "  </compound>\n";
  }
}
References addHtmlExtensionIfMissing(), convertToXML(), found, getOutputFileBase(), RefListManager::instance(), m_subPages, Definition::name(), DefinitionMixin< PageDef >::name(), title(), TRUE, and DefinitionMixin< PageDef >::writeDocAnchorsToTagFile().
Member Data Documentation
m_fileName
QCString PageDefImpl::m_fileName private
Definition at line 70 of file pagedef.cpp.
Referenced by getOutputFileBase(), PageDefImpl(), and setFileName().
m_localToc
LocalToc PageDefImpl::m_localToc private
Definition at line 75 of file pagedef.cpp.
Referenced by localToc(), setLocalToc(), and writeDocumentation().
m_nestingLevel
int PageDefImpl::m_nestingLevel private
Definition at line 74 of file pagedef.cpp.
Referenced by addInnerCompound(), PageDefImpl(), and setNestingLevel().
m_pageScope
Definition* PageDefImpl::m_pageScope private
Definition at line 73 of file pagedef.cpp.
Referenced by getPageScope(), PageDefImpl(), and setPageScope().
m_showLineNo
bool PageDefImpl::m_showLineNo private
Definition at line 76 of file pagedef.cpp.
Referenced by PageDefImpl(), setShowLineNo(), and showLineNo().
m_subPages
PageLinkedRefMap PageDefImpl::m_subPages private
Definition at line 72 of file pagedef.cpp.
Referenced by addInnerCompound(), getSubPages(), hasSubPages(), writePageDocumentation(), and writeTagFile().
m_title
QCString PageDefImpl::m_title private
Definition at line 71 of file pagedef.cpp.
Referenced by displayName(), hasTitle(), PageDefImpl(), setTitle(), title(), and writeDocumentation().
The documentation for this class was generated from the following file:
src/pagedef.cpp