Doxygen: PythonOutlineParser Class Reference
PythonOutlineParser Class Reference
Python Language parser using state-based lexical scanning.
#include <src/pyscanner.h>
Classes
struct Private
Public Member Functions
PythonOutlineParser ()
~PythonOutlineParser () override
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser) override
Parses a single input file with the goal to build an Entry tree.
bool needsPreprocessing (const QCString &extension) const override
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
void parsePrototype (const QCString &text) override
Callback function called by the comment block scanner.
Public Member Functions inherited from OutlineParserInterface
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Python Language parser using state-based lexical scanning.
This is the Python language parser for doxygen.
Definition at line 34 of file pyscanner.h.
Constructor & Destructor Documentation
PythonOutlineParser()
PythonOutlineParser::PythonOutlineParser ()
Definition at line 2328 of file pyscanner.l.
                                         : p(std::make_unique<PythonOutlineParser::Private>())
{
  pyscannerYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  pyscannerYYset_debug(Debug::isFlagSet(Debug::Lex_pyscanner)?1:0,p->yyscanner);
#endif
}
References Debug::isFlagSet(), Debug::Lex_pyscanner, p, and PythonOutlineParser().
Referenced by PythonOutlineParser().
~PythonOutlineParser()
PythonOutlineParser::~PythonOutlineParser () override
Definition at line 2336 of file pyscanner.l.
{
  pyscannerYYlex_destroy(p->yyscanner);
}
References p.
Member Function Documentation
needsPreprocessing()
bool PythonOutlineParser::needsPreprocessing (const QCString & extension) const override virtual
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 2356 of file pyscanner.l.
{
  return FALSE;
}
References FALSE.
parseInput()
void PythonOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) override virtual
Parses a single input file with the goal to build an Entry tree.
Parameters
[in] fileName The full name of the file.
[in] fileBuf The contents of the file (zero terminated).
[in,out] root The root of the tree of Entry *nodes representing the information extracted from the file.
[in] clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
Definition at line 2342 of file pyscanner.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->thisParser = this;
  DebugLex debugLex(Debug::Lex_pyscanner, __FILE__, qPrint(fileName));
  ::parseMain(p->yyscanner, fileName,fileBuf,root);
  // May print the AST for debugging purposes
  // printAST(global_root);
}
References Debug::Lex_pyscanner, p, parseMain(), and qPrint().
parsePrototype()
void PythonOutlineParser::parsePrototype (const QCString & text) override virtual
Callback function called by the comment block scanner.
It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Definition at line 2361 of file pyscanner.l.
{
  ::parsePrototype(p->yyscanner,text);
}
References p, and parsePrototype().
Referenced by parsePrototype().
Member Data Documentation
p
std::unique_ptr<Private> PythonOutlineParser::p private
Definition at line 48 of file pyscanner.h.
Referenced by parseInput(), parsePrototype(), PythonOutlineParser(), and ~PythonOutlineParser().
The documentation for this class was generated from the following files:
src/pyscanner.h
src/pyscanner.l