Doxygen: OutputCodeIntf Class Reference
OutputCodeIntf Class Reference abstract
Base class for code generators.
#include <src/outputgen.h>
Public Member Functions
OutputCodeIntf ()=default
virtual OutputType type () const =0
virtual std::unique_ptr< OutputCodeIntf > clone ()=0
virtual void codify (const QCString &s)=0
virtual void stripCodeComments (bool b)=0
virtual void startSpecialComment ()=0
virtual void endSpecialComment ()=0
virtual void setStripIndentAmount (size_t)=0
virtual void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)=0
virtual void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)=0
virtual void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)=0
virtual void startCodeLine (int lineNr)=0
virtual void endCodeLine ()=0
virtual void startFontClass (const QCString &c)=0
virtual void endFontClass ()=0
virtual void writeCodeAnchor (const QCString &name)=0
virtual void startCodeFragment (const QCString &style)=0
virtual void endCodeFragment (const QCString &style)=0
virtual void startFold (int lineNr, const QCString &startMarker, const QCString &endMarker)=0
virtual void endFold ()=0
Detailed Description
Base class for code generators.
Definition at line 64 of file outputgen.h.
Constructor & Destructor Documentation
OutputCodeIntf()
OutputCodeIntf::OutputCodeIntf () default
References OutputCodeIntf().
Referenced by clone(), and OutputCodeIntf().
Member Function Documentation
clone()
virtual std::unique_ptr< OutputCodeIntf > OutputCodeIntf::clone () pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References clone(), and OutputCodeIntf().
Referenced by clone().
codify()
virtual void OutputCodeIntf::codify (const QCString & s) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References codify().
Referenced by codify(), and OutputCodeList::codify().
endCodeFragment()
virtual void OutputCodeIntf::endCodeFragment (const QCString & style) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References endCodeFragment().
Referenced by endCodeFragment(), and OutputCodeList::endCodeFragment().
endCodeLine()
virtual void OutputCodeIntf::endCodeLine () pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References endCodeLine().
Referenced by endCodeLine(), and OutputCodeList::endCodeLine().
endFold()
virtual void OutputCodeIntf::endFold () pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References endFold().
Referenced by endFold(), and OutputCodeList::endFold().
endFontClass()
virtual void OutputCodeIntf::endFontClass () pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References endFontClass().
Referenced by endFontClass(), and OutputCodeList::endFontClass().
endSpecialComment()
virtual void OutputCodeIntf::endSpecialComment () pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References endSpecialComment().
Referenced by endSpecialComment(), and OutputCodeList::endSpecialComment().
setStripIndentAmount()
virtual void OutputCodeIntf::setStripIndentAmount (size_t) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References setStripIndentAmount().
Referenced by setStripIndentAmount(), and OutputCodeList::setStripIndentAmount().
startCodeFragment()
virtual void OutputCodeIntf::startCodeFragment (const QCString & style) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References startCodeFragment().
Referenced by startCodeFragment(), and OutputCodeList::startCodeFragment().
startCodeLine()
virtual void OutputCodeIntf::startCodeLine (int lineNr) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References startCodeLine().
Referenced by startCodeLine(), and OutputCodeList::startCodeLine().
startFold()
virtual void OutputCodeIntf::startFold (int lineNr, const QCString & startMarker, const QCString & endMarker) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References startFold().
Referenced by startFold(), and OutputCodeList::startFold().
startFontClass()
virtual void OutputCodeIntf::startFontClass (const QCString & c) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References startFontClass().
Referenced by startFontClass(), and OutputCodeList::startFontClass().
startSpecialComment()
virtual void OutputCodeIntf::startSpecialComment () pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References startSpecialComment().
Referenced by startSpecialComment(), and OutputCodeList::startSpecialComment().
stripCodeComments()
virtual void OutputCodeIntf::stripCodeComments (bool b) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References stripCodeComments().
Referenced by stripCodeComments(), and OutputCodeList::stripCodeComments().
type()
virtual OutputType OutputCodeIntf::type () const pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References type().
Referenced by type(), and writeCodeLink().
writeCodeAnchor()
virtual void OutputCodeIntf::writeCodeAnchor (const QCString & name) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References writeCodeAnchor().
Referenced by writeCodeAnchor(), and OutputCodeList::writeCodeAnchor().
writeCodeLink()
virtual void OutputCodeIntf::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References type(), and writeCodeLink().
Referenced by writeCodeLink(), and OutputCodeList::writeCodeLink().
writeLineNumber()
virtual void OutputCodeIntf::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References writeLineNumber().
Referenced by writeLineNumber(), and OutputCodeList::writeLineNumber().
writeTooltip()
virtual void OutputCodeIntf::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) pure virtual
Implemented in DevNullCodeGenerator, DocbookCodeGenerator, HtmlCodeGenerator, LatexCodeGenerator, ManCodeGenerator, OutputCodeDefer< OutputCodeGen >, OutputCodeRecorder, RTFCodeGenerator, and XMLCodeGenerator.
References writeTooltip().
Referenced by writeTooltip(), and OutputCodeList::writeTooltip().
The documentation for this class was generated from the following file:
src/outputgen.h