Doxygen: src/aliases.h File Reference
aliases.h File Reference
#include <string>
#include <string_view>
Functions
std::string resolveAliasCmd (std::string_view aliasCmd)
bool isAliasCmd (std::string_view aliasCmd)
void readAliases ()
Function Documentation
isAliasCmd()
bool isAliasCmd (std::string_view aliasCmd)
Definition at line 528 of file aliases.cpp.
{
  return g_aliasInfoMap.find(std::string{aliasCmd}) != g_aliasInfoMap.end();
}
References g_aliasInfoMap.
Referenced by DocPara::handleCommand().
readAliases()
void readAliases ()
Definition at line 170 of file aliases.cpp.
{
  // add aliases to a dictionary
  const StringVector &aliasList = Config_getList(ALIASES);
  for (const auto &al : aliasList)
  {
    addValidAliasToMap(al);
  }
  for (auto &[name,overloads] : g_aliasInfoMap)
  {
    for (auto &[numParams,aliasInfo] : overloads)
    {
      aliasInfo.value = expandAlias(name+":"+std::to_string(numParams),aliasInfo.value);
    }
  }
  for (auto &[name,overloads] : g_aliasInfoMap)
  {
    for (auto &[numParams,aliasInfo] : overloads)
    {
      aliasInfo.value = escapeAlias(aliasInfo.value);
    }
  }
}
References addValidAliasToMap(), Config_getList, escapeAlias(), expandAlias(), and g_aliasInfoMap.
Referenced by adjustConfiguration().
resolveAliasCmd()
std::string resolveAliasCmd (std::string_view aliasCmd)
Definition at line 504 of file aliases.cpp.
{
  StringUnorderedSet aliasesProcessed;
  //printf("Expanding: '%s'\n",qPrint(aliasCmd));
  std::string result = expandAliasRec(aliasesProcessed,aliasCmd);
  //printf("Expanding result: '%s'->'%s'\n",qPrint(aliasCmd),qPrint(result));
  Debug::print(Debug::Alias,0,"Resolving alias: cmd='%s' result='%s'\n",qPrint(std::string{aliasCmd}),qPrint(result));
  return result;
}
References Debug::Alias, expandAliasRec(), Debug::print(), and qPrint().
Referenced by replaceAliases().