Doxygen: NamespaceDefAliasImpl Class Reference
NamespaceDefAliasImpl Class Reference
Public Member Functions
NamespaceDefAliasImpl (const Definition *newScope, const NamespaceDef *nd)
~NamespaceDefAliasImpl () override
DefType definitionType () const override
const NamespaceDef * getNSAlias () const
CodeSymbolType codeSymbolType () const override
QCString getOutputFileBase () const override
QCString anchor () const override
int numDocMembers () const override
const LinkedRefMap< NamespaceDef > & getUsedNamespaces () const override
const LinkedRefMap< const Definition > & getUsedDefinitions () const override
QCString displayName (bool b=TRUE) const override
const QCString & localName () const override
bool isConstantGroup () const override
bool isModule () const override
bool isLibrary () const override
bool isInline () const override
bool isLinkableInProject () const override
bool isLinkable () const override
bool isVisibleInHierarchy () const override
bool hasDetailedDescription () const override
const Definition * findInnerCompound (const QCString &name) const override
bool subGrouping () const override
MemberList * getMemberList (MemberListType lt) const override
const MemberLists & getMemberLists () const override
const MemberDef * getMemberByName (const QCString &name) const override
const MemberGroupList & getMemberGroups () const override
ClassLinkedRefMap getClasses () const override
ClassLinkedRefMap getInterfaces () const override
ClassLinkedRefMap getStructs () const override
ClassLinkedRefMap getExceptions () const override
NamespaceLinkedRefMap getNamespaces () const override
ConceptLinkedRefMap getConcepts () const override
QCString title () const override
QCString compoundTypeString () const override
int countVisibleMembers () const override
Public Member Functions inherited from DefinitionAliasMixin< NamespaceDef >
DefinitionAliasMixin (const Definition *scope, const Definition *alias)
~DefinitionAliasMixin () override=default
void init ()
void deinit ()
bool isAlias () const override
const QCString & name () const override
bool isAnonymous () const override
QCString qualifiedName () const override
QCString symbolName () const override
QCString getSourceFileBase () const override
QCString getSourceAnchor () const override
QCString documentation () const override
int docLine () const override
QCString docFile () const override
QCString briefDescription (bool abbreviate=FALSE) const override
QCString briefDescriptionAsTooltip () const override
int briefLine () const override
QCString inbodyDocumentation () const override
QCString inbodyFile () const override
int inbodyLine () const override
QCString briefFile () const override
QCString getDefFileName () const override
QCString getDefFileExtension () const override
int getDefLine () const override
int getDefColumn () const override
bool hasDocumentation () const override
bool hasUserDocumentation () const override
bool isVisibleInProject () const override
bool isVisible () const override
bool isHidden () const override
bool isArtificial () const override
bool isExported () const override
QCString getReference () const override
bool isReference () const override
QCString externalReference (const QCString &relPath) const override
int getStartDefLine () const override
int getStartBodyLine () const override
int getEndBodyLine () const override
const FileDef * getBodyDef () const override
SrcLangExt getLanguage () const override
const GroupList & partOfGroups () const override
bool isLinkableViaGroup () const override
const RefItemVector & xrefListItems () const override
Definition * getOuterScope () const override
const MemberVector & getReferencesMembers () const override
const MemberVector & getReferencedByMembers () const override
bool hasSections () const override
bool hasSources () const override
bool hasBriefDescription () const override
QCString id () const override
const SectionRefs & getSectionRefs () const override
QCString navigationPathAsString () const override
QCString pathFragment () const override
Public Member Functions inherited from NamespaceDef
Public Member Functions inherited from Definition
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Protected Member Functions inherited from DefinitionAliasMixin< NamespaceDef >
const Definition * getAlias () const
const Definition * getScope () const
Detailed Description
Definition at line 184 of file namespacedef.cpp.
Constructor & Destructor Documentation
NamespaceDefAliasImpl()
NamespaceDefAliasImpl::NamespaceDefAliasImpl (const Definition * newScope, const NamespaceDef * nd) inline
Definition at line 187 of file namespacedef.cpp.
      : DefinitionAliasMixin(newScope,nd) { init(); }
References DefinitionAliasMixin< NamespaceDef >::DefinitionAliasMixin(), and DefinitionAliasMixin< NamespaceDef >::init().
~NamespaceDefAliasImpl()
NamespaceDefAliasImpl::~NamespaceDefAliasImpl () inline override
Definition at line 189 of file namespacedef.cpp.
{ deinit(); }
References DefinitionAliasMixin< NamespaceDef >::deinit().
Member Function Documentation
anchor()
QCString NamespaceDefAliasImpl::anchor () const inline override virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 201 of file namespacedef.cpp.
    { return getNSAlias()->anchor(); }
References Definition::anchor(), and getNSAlias().
codeSymbolType()
CodeSymbolType NamespaceDefAliasImpl::codeSymbolType () const inline override virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 197 of file namespacedef.cpp.
    { return getNSAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getNSAlias().
compoundTypeString()
QCString NamespaceDefAliasImpl::compoundTypeString () const inline override virtual
Implements NamespaceDef.
Definition at line 255 of file namespacedef.cpp.
    { return getNSAlias()->compoundTypeString(); }
References NamespaceDef::compoundTypeString(), and getNSAlias().
countVisibleMembers()
int NamespaceDefAliasImpl::countVisibleMembers () const inline override virtual
Implements NamespaceDef.
Definition at line 257 of file namespacedef.cpp.
    { return getNSAlias()->countVisibleMembers(); }
References NamespaceDef::countVisibleMembers(), and getNSAlias().
definitionType()
DefType NamespaceDefAliasImpl::definitionType () const inline override virtual
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Definition at line 192 of file namespacedef.cpp.
{ return TypeNamespace; }
References definitionType(), and Definition::TypeNamespace.
Referenced by definitionType().
displayName()
QCString NamespaceDefAliasImpl::displayName (bool includeScope = TRUE) const inline override virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 209 of file namespacedef.cpp.
    { return makeDisplayName(this,b); }
References makeDisplayName().
findInnerCompound()
const Definition * NamespaceDefAliasImpl::findInnerCompound (const QCString & name) const inline override virtual
Reimplemented from DefinitionAliasMixin< NamespaceDef >.
Definition at line 229 of file namespacedef.cpp.
    { return getNSAlias()->findInnerCompound(name); }
References Definition::findInnerCompound(), getNSAlias(), and Definition::name().
getClasses()
ClassLinkedRefMap NamespaceDefAliasImpl::getClasses () const inline override virtual
Returns the classes contained in this namespace
Implements NamespaceDef.
Definition at line 241 of file namespacedef.cpp.
    { return getNSAlias()->getClasses(); }
References NamespaceDef::getClasses(), and getNSAlias().
getConcepts()
ConceptLinkedRefMap NamespaceDefAliasImpl::getConcepts () const inline override virtual
Returns the concepts contained in this namespace
Implements NamespaceDef.
Definition at line 251 of file namespacedef.cpp.
    { return getNSAlias()->getConcepts(); }
References NamespaceDef::getConcepts(), and getNSAlias().
getExceptions()
ClassLinkedRefMap NamespaceDefAliasImpl::getExceptions () const inline override virtual
Returns the Slice exceptions contained in this namespace
Implements NamespaceDef.
Definition at line 247 of file namespacedef.cpp.
    { return getNSAlias()->getExceptions(); }
References NamespaceDef::getExceptions(), and getNSAlias().
getInterfaces()
ClassLinkedRefMap NamespaceDefAliasImpl::getInterfaces () const inline override virtual
Returns the Slice interfaces contained in this namespace
Implements NamespaceDef.
Definition at line 243 of file namespacedef.cpp.
    { return getNSAlias()->getInterfaces(); }
References NamespaceDef::getInterfaces(), and getNSAlias().
getMemberByName()
const MemberDef * NamespaceDefAliasImpl::getMemberByName (const QCString & name) const inline override virtual
Implements NamespaceDef.
Definition at line 237 of file namespacedef.cpp.
    { return getNSAlias()->getMemberByName(name); }
References NamespaceDef::getMemberByName(), getNSAlias(), and Definition::name().
getMemberGroups()
const MemberGroupList & NamespaceDefAliasImpl::getMemberGroups () const inline override virtual
Returns the user defined member groups
Implements NamespaceDef.
Definition at line 239 of file namespacedef.cpp.
    { return getNSAlias()->getMemberGroups(); }
References NamespaceDef::getMemberGroups(), and getNSAlias().
getMemberList()
MemberList * NamespaceDefAliasImpl::getMemberList (MemberListType lt) const inline override virtual
Implements NamespaceDef.
Definition at line 233 of file namespacedef.cpp.
    { return getNSAlias()->getMemberList(lt); }
References NamespaceDef::getMemberList(), and getNSAlias().
getMemberLists()
const MemberLists & NamespaceDefAliasImpl::getMemberLists () const inline override virtual
Implements NamespaceDef.
Definition at line 235 of file namespacedef.cpp.
    { return getNSAlias()->getMemberLists(); }
References NamespaceDef::getMemberLists(), and getNSAlias().
getNamespaces()
NamespaceLinkedRefMap NamespaceDefAliasImpl::getNamespaces () const inline override virtual
Returns the namespaces contained in this namespace
Implements NamespaceDef.
Definition at line 249 of file namespacedef.cpp.
    { return getNSAlias()->getNamespaces(); }
References NamespaceDef::getNamespaces(), and getNSAlias().
getNSAlias()
const NamespaceDef * NamespaceDefAliasImpl::getNSAlias () const inline
Definition at line 194 of file namespacedef.cpp.
{ return toNamespaceDef(getAlias()); }
References DefinitionAliasMixin< NamespaceDef >::getAlias(), and toNamespaceDef().
Referenced by anchor(), codeSymbolType(), compoundTypeString(), countVisibleMembers(), findInnerCompound(), getClasses(), getConcepts(), getExceptions(), getInterfaces(), getMemberByName(), getMemberGroups(), getMemberList(), getMemberLists(), getNamespaces(), getOutputFileBase(), getStructs(), getUsedDefinitions(), getUsedNamespaces(), hasDetailedDescription(), isConstantGroup(), isInline(), isLibrary(), isLinkable(), isLinkableInProject(), isModule(), isVisibleInHierarchy(), localName(), numDocMembers(), subGrouping(), and title().
getOutputFileBase()
QCString NamespaceDefAliasImpl::getOutputFileBase () const inline override virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 199 of file namespacedef.cpp.
    { return getNSAlias()->getOutputFileBase(); }
References getNSAlias(), and Definition::getOutputFileBase().
getStructs()
ClassLinkedRefMap NamespaceDefAliasImpl::getStructs () const inline override virtual
Returns the Slice structs contained in this namespace
Implements NamespaceDef.
Definition at line 245 of file namespacedef.cpp.
    { return getNSAlias()->getStructs(); }
References getNSAlias(), and NamespaceDef::getStructs().
getUsedDefinitions()
const LinkedRefMap< const Definition > & NamespaceDefAliasImpl::getUsedDefinitions () const inline override virtual
Implements NamespaceDef.
Definition at line 207 of file namespacedef.cpp.
    { return getNSAlias()->getUsedDefinitions(); }
References getNSAlias(), and NamespaceDef::getUsedDefinitions().
getUsedNamespaces()
const LinkedRefMap< NamespaceDef > & NamespaceDefAliasImpl::getUsedNamespaces () const inline override virtual
Implements NamespaceDef.
Definition at line 205 of file namespacedef.cpp.
    { return getNSAlias()->getUsedNamespaces(); }
References getNSAlias(), and NamespaceDef::getUsedNamespaces().
hasDetailedDescription()
bool NamespaceDefAliasImpl::hasDetailedDescription () const inline override virtual
Implements NamespaceDef.
Definition at line 227 of file namespacedef.cpp.
    { return getNSAlias()->hasDetailedDescription(); }
References getNSAlias(), and NamespaceDef::hasDetailedDescription().
isConstantGroup()
bool NamespaceDefAliasImpl::isConstantGroup () const inline override virtual
Implements NamespaceDef.
Definition at line 213 of file namespacedef.cpp.
    { return getNSAlias()->isConstantGroup(); }
References getNSAlias(), and NamespaceDef::isConstantGroup().
isInline()
bool NamespaceDefAliasImpl::isInline () const inline override virtual
Implements NamespaceDef.
Definition at line 219 of file namespacedef.cpp.
    { return getNSAlias()->isInline(); }
References getNSAlias(), and NamespaceDef::isInline().
isLibrary()
bool NamespaceDefAliasImpl::isLibrary () const inline override virtual
Implements NamespaceDef.
Definition at line 217 of file namespacedef.cpp.
    { return getNSAlias()->isLibrary(); }
References getNSAlias(), and NamespaceDef::isLibrary().
isLinkable()
bool NamespaceDefAliasImpl::isLinkable () const inline override virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 223 of file namespacedef.cpp.
    { return getNSAlias()->isLinkable(); }
References getNSAlias(), and Definition::isLinkable().
isLinkableInProject()
bool NamespaceDefAliasImpl::isLinkableInProject () const inline override virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 221 of file namespacedef.cpp.
    { return getNSAlias()->isLinkableInProject(); }
References getNSAlias(), and Definition::isLinkableInProject().
isModule()
bool NamespaceDefAliasImpl::isModule () const inline override virtual
Implements NamespaceDef.
Definition at line 215 of file namespacedef.cpp.
    { return getNSAlias()->isModule(); }
References getNSAlias(), and NamespaceDef::isModule().
isVisibleInHierarchy()
bool NamespaceDefAliasImpl::isVisibleInHierarchy () const inline override virtual
Implements NamespaceDef.
Definition at line 225 of file namespacedef.cpp.
    { return getNSAlias()->isVisibleInHierarchy(); }
References getNSAlias(), and NamespaceDef::isVisibleInHierarchy().
localName()
const QCString & NamespaceDefAliasImpl::localName () const inline override virtual
Returns the local name without any scope qualifiers.
Reimplemented from DefinitionAliasMixin< NamespaceDef >.
Definition at line 211 of file namespacedef.cpp.
    { return getNSAlias()->localName(); }
References getNSAlias(), and Definition::localName().
numDocMembers()
int NamespaceDefAliasImpl::numDocMembers () const inline override virtual
Implements NamespaceDef.
Definition at line 203 of file namespacedef.cpp.
    { return getNSAlias()->numDocMembers(); }
References getNSAlias(), and NamespaceDef::numDocMembers().
subGrouping()
bool NamespaceDefAliasImpl::subGrouping () const inline override virtual
Implements NamespaceDef.
Definition at line 231 of file namespacedef.cpp.
    { return getNSAlias()->subGrouping(); }
References getNSAlias(), and NamespaceDef::subGrouping().
title()
QCString NamespaceDefAliasImpl::title () const inline override virtual
Implements NamespaceDef.
Definition at line 253 of file namespacedef.cpp.
    { return getNSAlias()->title(); }
References getNSAlias(), and NamespaceDef::title().
The documentation for this class was generated from the following file:
src/namespacedef.cpp