Doxygen: /home/runner/work/doxygen/doxygen/src/context.cpp File Reference
context.cpp File Reference
#include <assert.h>
#include <sstream>
#include "context.h"
#include "config.h"
#include "index.h"
#include "classlist.h"
#include "doxygen.h"
#include "namespacedef.h"
#include "filedef.h"
#include "pagedef.h"
#include "groupdef.h"
#include "util.h"
#include "version.h"
#include "language.h"
#include "message.h"
#include "vhdldocgen.h"
#include "filename.h"
#include "dirdef.h"
#include "docparser.h"
#include "htmlgen.h"
#include "htmldocvisitor.h"
#include "htmlhelp.h"
#include "latexgen.h"
#include "latexdocvisitor.h"
#include "dot.h"
#include "dotcallgraph.h"
#include "dotclassgraph.h"
#include "dotdirdeps.h"
#include "dotgfxhierarchytable.h"
#include "dotgroupcollaboration.h"
#include "dotincldepgraph.h"
#include "diagram.h"
#include "example.h"
#include "membername.h"
#include "parserintf.h"
#include "portable.h"
#include "arguments.h"
#include "searchindex.h"
#include "resourcemgr.h"
#include "dir.h"
#include "datetime.h"
#include "outputlist.h"
Classes
struct ContextGlobals
class CachedItem< T, TOwner, creator >
Wrapper for data that needs to be cached.
class PropertyMap< T >
Class representing a mapping of properties and the corresponding getter function.
class GenericConstIterator
Template List iterator support.
class GenericNodeListContext
standard template list implementation
class ConfigContext::Private
class DoxygenContext::Private
class TranslateContext::Private
class DefinitionContext< T >
struct DefinitionContext< T >::Cachable
class IncludeInfoContext::Private
class IncludeInfoListContext::Private
class ClassContext::Private
struct ClassContext::Private::Cachable
class NamespaceContext::Private
struct NamespaceContext::Private::Cachable
class FileContext::Private
struct FileContext::Private::Cachable
class DirContext::Private
struct DirContext::Private::Cachable
class PageContext::Private
struct PageContext::Private::Cachable
class TextGeneratorHtml
class TextGeneratorLatex
class TextGeneratorFactory
class MemberContext::Private
struct MemberContext::Private::Cachable
class ConceptContext::Private
struct ConceptContext::Private::Cachable
class ModuleContext::Private
struct ModuleContext::Private::Cachable
class ClassListContext::Private
class ClassIndexContext::Private
class ClassHierarchyContext::Private
class NestingNodeContext::Private
class NestingContext::Private
class ClassTreeContext::Private
class ConceptListContext::Private
class NamespaceListContext::Private
class NamespaceTreeContext::Private
class FileListContext::Private
class DirListContext::Private
class UsedFilesContext::Private
class FileTreeContext::Private
class PageTreeContext::Private
class PageListContext::Private
class ExampleListContext::Private
class ModuleListContext::Private
class ConceptTreeContext::Private
class ModuleTreeContext::Private
class ExampleTreeContext::Private
class NavPathElemContext::Private
class GlobalsIndexContext::Private
class ClassMembersIndexContext::Private
class NamespaceMembersIndexContext::Private
class InheritanceGraphContext::Private
class InheritanceNodeContext::Private
class InheritanceListContext::Private
class MemberListContext::Private
class MemberInfoContext::Private
class AllMembersListContext::Private
class MemberGroupInfoContext::Private
class MemberGroupListContext::Private
class MemberListInfoContext::Private
class InheritedMemberInfoContext::Private
class InheritedMemberInfoListContext::Private
class ArgumentContext::Private
class ArgumentListContext::Private
class SymbolContext::Private
class SymbolListContext::Private
class SymbolGroupContext::Private
class SymbolGroupListContext::Private
class SymbolIndexContext::Private
class SymbolIndicesContext::Private
class SearchIndexContext::Private
class SearchIndicesContext::Private
class HtmlEscaper
class LatexSpaceless
class HtmlSpaceless
class LatexEscaper
Macros
#define BASE_PROPERTIES
Enumerations
enum ContextOutputFormat {
ContextOutputFormat_Unspecified =0 , ContextOutputFormat_Html , ContextOutputFormat_Latex , ContextOutputFormat_Rtf ,
ContextOutputFormat_ManPage , ContextOutputFormat_DocBook , ContextOutputFormat_Xml , ContextOutputFormat_TagFile
}
Functions
static TemplateVariant parseDoc (const Definition *def, const QCString &file, int line, const QCString &relPath, const QCString &docStr, bool isBrief)
static TemplateVariant parseCode (const Definition *d, const QCString &scopeName, const QCString &relPath, const QCString &code, int startLine=-1, int endLine=-1, bool showLineNumbers=FALSE)
static TemplateVariant parseCode (const FileDef *fd, const QCString &relPath)
TemplateVariant createLinkedText (const Definition *def, const QCString &relPath, const QCString &text)
static int computeMaxDepth (const TemplateListIntfPtr list)
static int computeNumNodesAtLevel (const TemplateStructIntfPtr s, int level, int maxLevel)
static int computePreferredDepth (const TemplateListIntfPtr list, int maxDepth)
void generateOutputViaTemplate ()
void generateTemplateFiles (const QCString &templateDir)
Variables
struct ContextGlobals g_globals
Macro Definition Documentation
BASE_PROPERTIES
#define BASE_PROPERTIES
Value:
  {  "name",               &Private::name                }, \
  {  "bareName",           &Private::bareName            }, \
  {  "relPath",            &Private::relPath             }, \
  {  "fileName",           &Private::fileName            }, \
  {  "anchor",             &Private::anchor              }, \
  {  "details",            &Private::details             }, \
  {  "brief",              &Private::brief               }, \
  {  "inbodyDocs",         &Private::inbodyDocs          }, \
  {  "sourceFileName",     &Private::sourceFileName      }, \
  {  "isLinkable",         &Private::isLinkable          }, \
  {  "isLinkableInProject",&Private::isLinkableInProject }, \
  {  "dynSectionId",       &Private::dynSectionId        }, \
  {  "language",           &Private::language            }, \
  {  "sourceDef",          &Private::sourceDef           }, \
  {  "navigationPath",     &Private::navigationPath      }, \
  {  "partOfGroups",       &Private::partOfGroups        }, \
  {  "compoundKind",       &Private::compoundKind        }, \
  {  "isReference",        &Private::isReference         }, \
  {  "externalReference",  &Private::externalReference   }
Definition at line 1580 of file context.cpp.
Enumeration Type Documentation
ContextOutputFormat
enum ContextOutputFormat
Enumerator
ContextOutputFormat_Unspecified
ContextOutputFormat_Html
ContextOutputFormat_Latex
ContextOutputFormat_Rtf
ContextOutputFormat_ManPage
ContextOutputFormat_DocBook
ContextOutputFormat_Xml
ContextOutputFormat_TagFile
Definition at line 64 of file context.cpp.
{
  ContextOutputFormat_Unspecified=0,
  ContextOutputFormat_Html,
  ContextOutputFormat_Latex,
  ContextOutputFormat_Rtf,
  ContextOutputFormat_ManPage,
  ContextOutputFormat_DocBook,
  ContextOutputFormat_Xml,
  ContextOutputFormat_TagFile
};
Function Documentation
computeMaxDepth()
static int computeMaxDepth (const TemplateListIntfPtr list) static
Definition at line 5155 of file context.cpp.
{
  int maxDepth=0;
  if (list)
  {
    TemplateListIntf::ConstIteratorPtr it = list->createIterator();
    TemplateVariant v;
    for (it->toFirst();it->current(v);it->toNext())
    {
      const TemplateStructIntfPtr s = v.toStruct();
      TemplateVariant child = s->get("children");
      int d = computeMaxDepth(child.toList())+1;
      if (d>maxDepth) maxDepth=d;
    }
  }
  return maxDepth;
}
References computeMaxDepth(), TemplateVariant::toList(), and TemplateVariant::toStruct().
Referenced by computeMaxDepth(), ClassHierarchyContext::Private::createMaxDepth(), ClassTreeContext::Private::createMaxDepth(), NamespaceTreeContext::Private::createMaxDepth(), FileTreeContext::Private::createMaxDepth(), PageTreeContext::Private::createMaxDepth(), ConceptTreeContext::Private::createMaxDepth(), ModuleTreeContext::Private::createMaxDepth(), and ExampleTreeContext::Private::createMaxDepth().
computeNumNodesAtLevel()
static int computeNumNodesAtLevel (const TemplateStructIntfPtr s, int level, int maxLevel) static
Definition at line 5173 of file context.cpp.
{
  int num=0;
  if (level<maxLevel)
  {
    num++;
    TemplateVariant child = s->get("children");
    if (child.toList())
    {
      TemplateListIntf::ConstIteratorPtr it = child.toList()->createIterator();
      TemplateVariant v;
      for (it->toFirst();it->current(v);it->toNext())
      {
        num+=computeNumNodesAtLevel(v.toStruct(),level+1,maxLevel);
      }
    }
  }
  return num;
}
References computeNumNodesAtLevel(), TemplateVariant::toList(), and TemplateVariant::toStruct().
Referenced by computeNumNodesAtLevel(), and computePreferredDepth().
computePreferredDepth()
static int computePreferredDepth (const TemplateListIntfPtr list, int maxDepth) static
Definition at line 5193 of file context.cpp.
{
  int preferredNumEntries = Config_getInt(HTML_INDEX_NUM_ENTRIES);
  int preferredDepth=1;
  if (preferredNumEntries>0)
  {
    int depth = maxDepth;
    for (int i=1;i<=depth;i++)
    {
      int num=0;
      TemplateListIntf::ConstIteratorPtr it = list->createIterator();
      TemplateVariant v;
      for (it->toFirst();it->current(v);it->toNext())
      {
        num+=computeNumNodesAtLevel(v.toStruct(),0,i);
      }
      if (num<=preferredNumEntries)
      {
        preferredDepth=i;
      }
      else
      {
        break;
      }
    }
  }
  return preferredDepth;
}
References computeNumNodesAtLevel(), Config_getInt, and TemplateVariant::toStruct().
Referenced by ClassHierarchyContext::Private::createPreferredDepth(), ClassTreeContext::Private::createPreferredDepth(), NamespaceTreeContext::Private::createPreferredDepth(), FileTreeContext::Private::createPreferredDepth(), PageTreeContext::Private::createPreferredDepth(), ConceptTreeContext::Private::createPreferredDepth(), ModuleTreeContext::Private::createPreferredDepth(), and ExampleTreeContext::Private::createPreferredDepth().
createLinkedText()
TemplateVariant createLinkedText (const Definition * def, const QCString & relPath, const QCString & text)
Definition at line 3581 of file context.cpp.
{
  TextStream ts;
  TextGeneratorIntf *tg = TextGeneratorFactory::instance()->create(ts,relPath);
  if (tg)
  {
    linkifyText(*tg,def->getOuterScope(),def->getBodyDef(),def,text);
    delete tg;
    return TemplateVariant(ts.str().c_str(),true);
  }
  else
  {
    return text;
  }
}
References TextGeneratorFactory::create(), Definition::getBodyDef(), Definition::getOuterScope(), TextGeneratorFactory::instance(), linkifyText(), and TextStream::str().
Referenced by MemberContext::Private::createBitfields(), MemberContext::Private::createDeclArgs(), MemberContext::Private::createDeclType(), MemberContext::Private::createDefinition(), ArgumentContext::Private::createDefval(), MemberContext::Private::createException(), MemberContext::Private::createFieldType(), MemberContext::Private::createInitializer(), ConceptContext::Private::createInitializer(), MemberContext::Private::createTemplateAlias(), MemberContext::Private::createTrailingReturnType(), and ArgumentContext::Private::createType().
generateOutputViaTemplate()
void generateOutputViaTemplate ()
Definition at line 9030 of file context.cpp.
{
  {
    auto e = std::make_unique<TemplateEngine>();
    auto ctx = e->createContext();
    if (ctx)
    {
      TemplateStructIntfPtr doxygen              (DoxygenContext::alloc());
      TemplateStructIntfPtr config               (ConfigContext::alloc());
      TemplateStructIntfPtr tr                   (TranslateContext::alloc());
      TemplateListIntfPtr   classList            (ClassListContext::alloc());
      TemplateStructIntfPtr classIndex           (ClassIndexContext::alloc());
      TemplateStructIntfPtr classTree            (ClassTreeContext::alloc());
      TemplateStructIntfPtr classHierarchy       (ClassHierarchyContext::alloc());
      TemplateListIntfPtr   conceptList          (ConceptListContext::alloc());
      TemplateStructIntfPtr conceptTree          (ConceptTreeContext::alloc());
      TemplateListIntfPtr   namespaceList        (NamespaceListContext::alloc());
      TemplateStructIntfPtr namespaceTree        (NamespaceTreeContext::alloc());
      TemplateListIntfPtr   dirList              (DirListContext::alloc());
      TemplateListIntfPtr   fileList             (FileListContext::alloc());
      TemplateStructIntfPtr fileTree             (FileTreeContext::alloc());
      TemplateStructIntfPtr pageTree             (PageTreeContext::alloc(*Doxygen::pageLinkedMap));
      TemplateListIntfPtr   pageList             (PageListContext::alloc(*Doxygen::pageLinkedMap));
      TemplateStructIntfPtr exampleTree          (ExampleTreeContext::alloc());
      TemplateListIntfPtr   exampleList          (ExampleListContext::alloc());
      TemplateStructIntfPtr moduleTree           (ModuleTreeContext::alloc());
      TemplateListIntfPtr   moduleList           (ModuleListContext::alloc());
      TemplateStructIntfPtr globalsIndex         (GlobalsIndexContext::alloc());
      TemplateStructIntfPtr classMembersIndex    (ClassMembersIndexContext::alloc());
      TemplateStructIntfPtr namespaceMembersIndex(NamespaceMembersIndexContext::alloc());
      TemplateListIntfPtr   searchIndices        (SearchIndicesContext::alloc());
      //%% Doxygen doxygen:
      ctx->set("doxygen",doxygen);
      //%% Translator tr:
      ctx->set("tr",tr);
      //%% Config config:
      ctx->set("config",config);
      //%% ClassList classList:
      ctx->set("classList",classList); // not used for standard HTML
      //%% ClassTree classTree:
      ctx->set("classTree",classTree);
      //%% ClassIndex classIndex:
      ctx->set("classIndex",classIndex);
      //%% ClassHierarchy classHierarchy:
      ctx->set("classHierarchy",classHierarchy);
      //%% ConceptList conceptList:
      ctx->set("conceptList",conceptList);
      //%% ConceptTree conceptTree:
      ctx->set("conceptTree",conceptTree);
      //%% NamespaceList namespaceList:
      ctx->set("namespaceList",namespaceList);
      //%% NamespaceTree namespaceTree:
      ctx->set("namespaceTree",namespaceTree);
      //%% FileList fileList:
      ctx->set("fileList",fileList);
      //%% FileTree fileTree:
      ctx->set("fileTree",fileTree);
      //%% PageList pageList
      ctx->set("pageList",pageList);
      //%% PageTree pageTree
      ctx->set("pageTree",pageTree);
      //%% ExampleTree exampleTree
      ctx->set("exampleTree",exampleTree);
      //%% ExampleList exampleList
      ctx->set("exampleList",exampleList);
      //%% ModuleTree moduleTree
      ctx->set("moduleTree",moduleTree);
      //%% ModuleList moduleList
      ctx->set("moduleList",moduleList);
      //%% DirList dirList
      ctx->set("dirList",dirList);
      //%% Page mainPage
      if (Doxygen::mainPage)
      {
        TemplateStructIntfPtr mainPage = PageContext::alloc(Doxygen::mainPage.get(),TRUE,FALSE);
        ctx->set("mainPage",mainPage);
      }
      else
      {
        // TODO: for LaTeX output index should be main... => solve in template
        Doxygen::mainPage = createPageDef("[generated]",1,"index","",Config_getString(PROJECT_NAME));
        Doxygen::mainPage->setFileName("index");
        TemplateStructIntfPtr mainPage = PageContext::alloc(Doxygen::mainPage.get(),TRUE,FALSE);
        ctx->set("mainPage",mainPage);
      }
      //%% GlobalsIndex globalsIndex:
      ctx->set("globalsIndex",globalsIndex);
      //%% ClassMembersIndex classMembersIndex:
      ctx->set("classMembersIndex",classMembersIndex);
      //%% NamespaceMembersIndex namespaceMembersIndex:
      ctx->set("namespaceMembersIndex",namespaceMembersIndex);
      //%% SearchIndices searchIndices
      ctx->set("searchIndices",searchIndices);
      //%% string space
      ctx->set("space"," ");
      //if (Config_getBool(GENERATE_HTML))
      { // render HTML output
        e->setTemplateDir("templates/html"); // TODO: make template part user configurable
        Template *tpl = e->loadByName("htmllayout.tpl",1);
        if (tpl)
        {
          g_globals.outputFormat = ContextOutputFormat_Html;
          g_globals.dynSectionId = 0;
          g_globals.outputDir    = Config_getString(HTML_OUTPUT);
          Dir dir(g_globals.outputDir.str());
          createSubDirs(dir);
          ctx->setEscapeIntf(Config_getString(HTML_FILE_EXTENSION),std::make_unique<HtmlEscaper>());
          ctx->setSpacelessIntf(std::make_unique<HtmlSpaceless>());
          ctx->setOutputDirectory(g_globals.outputDir);
          TextStream ts;
          tpl->render(ts,ctx.get());
        }
        e->unload(tpl);
      }
      // TODO: clean index before each run...
      //if (Config_getBool(GENERATE_LATEX))
      if (0)
      { // render LaTeX output
        e->setTemplateDir("templates/latex"); // TODO: make template part user configurable
        Template *tpl = e->loadByName("latexlayout.tpl",1);
        if (tpl)
        {
          g_globals.outputFormat = ContextOutputFormat_Latex;
          g_globals.dynSectionId = 0;
          g_globals.outputDir    = Config_getString(LATEX_OUTPUT);
          Dir dir(g_globals.outputDir.str());
          createSubDirs(dir);
          ctx->setEscapeIntf(".tex",std::make_unique<LatexEscaper>());
          ctx->setSpacelessIntf(std::make_unique<LatexSpaceless>());
          ctx->setOutputDirectory(g_globals.outputDir);
          TextStream ts;
          tpl->render(ts,ctx.get());
        }
        e->unload(tpl);
      }
    }
  }
}
References ConfigContext::alloc(), DoxygenContext::alloc(), TranslateContext::alloc(), ClassListContext::alloc(), ClassIndexContext::alloc(), ClassHierarchyContext::alloc(), ClassTreeContext::alloc(), ConceptListContext::alloc(), NamespaceListContext::alloc(), NamespaceTreeContext::alloc(), DirListContext::alloc(), FileListContext::alloc(), FileTreeContext::alloc(), ModuleListContext::alloc(), ConceptTreeContext::alloc(), ModuleTreeContext::alloc(), ExampleListContext::alloc(), ExampleTreeContext::alloc(), GlobalsIndexContext::alloc(), ClassMembersIndexContext::alloc(), NamespaceMembersIndexContext::alloc(), SearchIndicesContext::alloc(), PageContext::alloc(), PageListContext::alloc(), PageTreeContext::alloc(), Config_getString, ContextOutputFormat_Html, ContextOutputFormat_Latex, createPageDef(), createSubDirs(), ContextGlobals::dynSectionId, FALSE, g_globals, Doxygen::mainPage, ContextGlobals::outputDir, ContextGlobals::outputFormat, Doxygen::pageLinkedMap, Template::render(), QCString::str(), and TRUE.
Referenced by generateOutput().
generateTemplateFiles()
void generateTemplateFiles (const QCString & templateDir)
Definition at line 9173 of file context.cpp.
{
  if (templateDir.isEmpty()) return;
  Dir thisDir;
  if (!thisDir.exists(templateDir.str()) && !thisDir.mkdir(templateDir.str()))
  {
    err("Failed to create output directory '%s'\n",qPrint(templateDir));
    return;
  }
  std::string outDir = templateDir.str()+"/html";
  if (!thisDir.exists(outDir) && !thisDir.mkdir(outDir))
  {
    err("Failed to create output directory '%s'\n",outDir.c_str());
    return;
  }
  ResourceMgr::instance().writeCategory("html",outDir.c_str());
}
References err, Dir::exists(), ResourceMgr::instance(), QCString::isEmpty(), Dir::mkdir(), qPrint(), QCString::str(), and ResourceMgr::writeCategory().
Referenced by readConfiguration().
parseCode() [1/2]
static TemplateVariant parseCode (const Definition * d, const QCString & scopeName, const QCString & relPath, const QCString & code, int startLine = -1, int endLine = -1, bool showLineNumbers = FALSE) static
Definition at line 1286 of file context.cpp.
{
  auto intf = Doxygen::parserManager->getCodeParser(d->getDefFileExtension());
  intf->resetCodeParserState();
  TextStream t;
  switch (g_globals.outputFormat)
  {
    case ContextOutputFormat_Html:
      {
        OutputCodeList codeList;
        codeList.add<HtmlCodeGenerator>(&t,relPath);
        intf->parseCode(codeList,scopeName,code,d->getLanguage(),FALSE,QCString(),d->getBodyDef(),
            startLine,endLine,TRUE,toMemberDef(d),showLineNumbers,d);
      }
      break;
    case ContextOutputFormat_Latex:
      {
        OutputCodeList codeList;
        codeList.add<LatexCodeGenerator>(&t,relPath,d->docFile());
        intf->parseCode(codeList,scopeName,code,d->getLanguage(),FALSE,QCString(),d->getBodyDef(),
            startLine,endLine,TRUE,toMemberDef(d),showLineNumbers,d);
      }
      break;
    // TODO: support other generators
    default:
      err("context.cpp: output format not yet supported\n");
      break;
  }
  return TemplateVariant(t.str(),TRUE);
}
References OutputCodeList::add(), ContextOutputFormat_Html, ContextOutputFormat_Latex, Definition::docFile(), err, FALSE, g_globals, Definition::getBodyDef(), ParserManager::getCodeParser(), Definition::getDefFileExtension(), Definition::getLanguage(), ContextGlobals::outputFormat, Doxygen::parserManager, TextStream::str(), toMemberDef(), and TRUE.
Referenced by MemberContext::Private::createInitializerAsCode(), ConceptContext::Private::createInitializerAsCode(), MemberContext::Private::createSourceCode(), FileContext::Private::createSources(), PerlModDocVisitor::operator()(), and PerlModDocVisitor::operator()().
parseCode() [2/2]
static TemplateVariant parseCode (const FileDef * fd, const QCString & relPath) static
Definition at line 1318 of file context.cpp.
{
  bool filterSourceFiles = Config_getBool(FILTER_SOURCE_FILES);
  auto intf = Doxygen::parserManager->getCodeParser(fd->getDefFileExtension());
  intf->resetCodeParserState();
  TextStream t;
  switch (g_globals.outputFormat)
  {
    case ContextOutputFormat_Html:
      {
        OutputCodeList codeList;
        codeList.add<HtmlCodeGenerator>(&t,relPath);
        intf->parseCode(codeList,QCString(),
              fileToString(fd->absFilePath(),filterSourceFiles,TRUE), // the sources
              fd->getLanguage(),  // lang
              FALSE,              // isExampleBlock
              QCString(),         // exampleName
              const_cast<FileDef*>(fd),  // fileDef, TODO: should be const
              -1,                 // startLine
              -1,                 // endLine
              FALSE,              // inlineFragment
              0,                  // memberDef
              TRUE,               // showLineNumbers
              0,                  // searchCtx
              TRUE                // collectXRefs, TODO: should become FALSE
              );
      }
      break;
    case ContextOutputFormat_Latex:
      {
        OutputCodeList codeList;
        codeList.add<LatexCodeGenerator>(&t,relPath,fd->docFile());
        intf->parseCode(codeList,QCString(),
              fileToString(fd->absFilePath(),filterSourceFiles,TRUE), // the sources
              fd->getLanguage(),  // lang
              FALSE,              // isExampleBlock
              QCString(),         // exampleName
              const_cast<FileDef*>(fd),  // fileDef, TODO: should be const
              -1,                 // startLine
              -1,                 // endLine
              FALSE,              // inlineFragment
              0,                  // memberDef
              TRUE,               // showLineNumbers
              0,                  // searchCtx
              TRUE                // collectXRefs, TODO: should become FALSE
              );
      }
      break;
    // TODO: support other generators
    default:
      err("context.cpp: output format not yet supported\n");
      break;
  }
  return TemplateVariant(t.str().c_str(),TRUE);
}
References FileDef::absFilePath(), OutputCodeList::add(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, Definition::docFile(), err, FALSE, fileToString(), g_globals, ParserManager::getCodeParser(), Definition::getDefFileExtension(), Definition::getLanguage(), ContextGlobals::outputFormat, Doxygen::parserManager, TextStream::str(), and TRUE.
parseDoc()
static TemplateVariant parseDoc (const Definition * def, const QCString & file, int line, const QCString & relPath, const QCString & docStr, bool isBrief) static
Definition at line 1242 of file context.cpp.
{
  TemplateVariant result;
  auto parser { createDocParser() };
  auto ast    { validatingParseDoc(*parser.get(),file,line,def,0,docStr,TRUE,FALSE,
                                   QCString(),isBrief,FALSE,Config_getBool(MARKDOWN_SUPPORT))
              };
  const DocNodeAST *astImpl = dynamic_cast<DocNodeAST*>(ast.get());
  if (astImpl)
  {
    TextStream ts;
    switch (g_globals.outputFormat)
    {
      case ContextOutputFormat_Html:
        {
          OutputCodeList codeList;
          codeList.add<HtmlCodeGenerator>(&ts,relPath);
          HtmlDocVisitor visitor(ts,codeList,def);
          std::visit(visitor,astImpl->root);
        }
        break;
      case ContextOutputFormat_Latex:
        {
          OutputCodeList codeList;
          codeList.add<LatexCodeGenerator>(&ts,relPath,file);
          LatexDocVisitor visitor(ts,codeList,*codeList.get<LatexCodeGenerator>(),def->getDefFileExtension());
          std::visit(visitor,astImpl->root);
        }
        break;
        // TODO: support other generators
      default:
        err("context.cpp: output format not yet supported\n");
        break;
    }
    bool isEmpty = astImpl->isEmpty();
    if (isEmpty)
      result = "";
    else
      result = TemplateVariant(ts.str().c_str(),TRUE);
  }
  return result;
}
References OutputCodeList::add(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, createDocParser(), err, FALSE, g_globals, OutputCodeList::get(), Definition::getDefFileExtension(), DocNodeAST::isEmpty(), ContextGlobals::outputFormat, DocNodeAST::root, TextStream::str(), TRUE, and validatingParseDoc().
Referenced by DefinitionContext< T >::createBrief(), NestingNodeContext::Private::createBrief(), DefinitionContext< T >::createDetails(), MemberGroupInfoContext::Private::createDocs(), ArgumentContext::Private::createDocs(), PageContext::Private::createExample(), DefinitionContext< T >::createInbodyDocs(), and MemberContext::Private::createParamDocs().
Variable Documentation
g_globals
struct ContextGlobals g_globals
Referenced by MemberContext::Private::callerGraph(), MemberContext::Private::callGraph(), ClassContext::Private::collaborationDiagram(), TextGeneratorFactory::create(), InheritanceGraphContext::Private::createGraph(), DirContext::Private::dirGraph(), DefinitionContext< T >::dynSectionId(), generateOutputViaTemplate(), ModuleContext::Private::groupGraph(), FileContext::Private::includedByGraph(), FileContext::Private::includeGraph(), ClassContext::Private::inheritanceDiagram(), parseCode(), parseCode(), and parseDoc().