Doxygen: TranslatorCzech Class Reference
TranslatorCzech Class Reference
#include <src/translator_cz.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description.
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool single) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
QCString trDesignUnitDocumentation () override
VHDL design unit documentation.
QCString trConcept (bool first_capital, bool singular) override
C++20 concept.
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
QCString trPackageList () override
QCString trFlowchart () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) override methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include "translator.h" or "translator_adapter.h" here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 132 of file translator_cz.h.
Member Function Documentation
getLanguageString()
QCString TranslatorCzech::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 178 of file translator_cz.h.
    {
      return "0x405 Czech";
    }
idLanguage()
QCString TranslatorCzech::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 144 of file translator_cz.h.
    { return "czech"; }
latexLanguageSupportCommand()
QCString TranslatorCzech::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 161 of file translator_cz.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[czech]{babel}\n"
             "\\usepackage{regexpatch}\n"
             "\\makeatletter\n"
             "% Change the `-` delimiter to an active character\n"
             "\\xpatchparametertext\\@@@cmidrule{-}{\\cA-}{}{}\n"
             "\\xpatchparametertext\\@cline{-}{\\cA-}{}{}\n"
             "\\makeatother\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorCzech::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 2024 of file translator_cz.h.
    { return "Dal zddn leny"; }
trAll()
QCString TranslatorCzech::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1534 of file translator_cz.h.
    {
      return "Ve";
    }
trAndMore()
QCString TranslatorCzech::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 2000 of file translator_cz.h.
    { return "a "+number+" dal(ch)..."; }
trAttention()
QCString TranslatorCzech::trAttention () inline override virtual
Implements Translator.
Definition at line 1097 of file translator_cz.h.
    {
      return "Upozornn";    // ??? not checked in a context
    }
trAuthor()
QCString TranslatorCzech::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1407 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "auto", "i", "r");
    }
References Translator::createNoun().
trBug()
QCString TranslatorCzech::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1277 of file translator_cz.h.
    {
      return "Chyba";
    }
trBugList()
QCString TranslatorCzech::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1282 of file translator_cz.h.
    {
      return "Seznam chyb";
    }
trCallerGraph()
QCString TranslatorCzech::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1654 of file translator_cz.h.
    {
      return "Tuto funkci volaj...";
    }
trCallGraph()
QCString TranslatorCzech::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1539 of file translator_cz.h.
    {
      return "Tato funkce vol...";
    }
trCiteReferences()
QCString TranslatorCzech::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1976 of file translator_cz.h.
    { return "Odkazy na literaturu"; }
trClass()
QCString TranslatorCzech::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1340 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "td", "y", "a");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trClassDiagram()
QCString TranslatorCzech::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 636 of file translator_cz.h.
    {
      return "Diagram ddinosti pro tdu "+clName+":";
    }
trClassDocumentation()
QCString TranslatorCzech::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 517 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentace datovch struktur";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentace td";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorCzech::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1240 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov struktury";
      }
      else
      {
        return "Tdy";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorCzech::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 286 of file translator_cz.h.
    { return "Hierarchie td"; }
trClassHierarchyDescription()
QCString TranslatorCzech::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 345 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Zde je hierarchick seznam vech entit:";
      }
      else
      {
        return "Zde naleznete seznam, vyjadujc vztah ddinosti td. "
               "Je seazen piblin (ale ne pln) podle abecedy:";
      }
    }
References Config_getBool.
trClassMethods()
QCString TranslatorCzech::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2062 of file translator_cz.h.
    {
      return "Metody tdy";
    }
trCode()
QCString TranslatorCzech::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 997 of file translator_cz.h.
    {
      return "zdrojov text";
    }
trCollaborationDiagram()
QCString TranslatorCzech::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 950 of file translator_cz.h.
    {
      return "Diagram pro "+clName+":";
    }
trCompoundIndex()
QCString TranslatorCzech::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 490 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Rejstk datovch struktur";
      }
      else
      {
        return "Rejstk td";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorCzech::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1709 of file translator_cz.h.
    { return "Rejstk datovch typ"; }
trCompoundList()
QCString TranslatorCzech::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 290 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov struktury";
      }
      else
      {
        return "Seznam td";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorCzech::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 368 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Nsledujc seznam obsahuje identifikace datovch "
               "struktur a jejich strun popisy:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Nsledujc seznam obsahuje identifikace td. "
               "V seznamu jsou uvedeny jejich strun popisy:";
      }
      else
      {
        return "Nsledujc seznam obsahuje pedevm identifikace "
               "td, ale nachzej se zde i dal netriviln prvky, "
               "jako jsou struktury (struct), unie (union) a rozhran "
               "(interface). V seznamu jsou uvedeny jejich strun "
               "popisy:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorCzech::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1682 of file translator_cz.h.
    { return "Datov typy se strunmi popisy:"; }
trCompoundListFortran()
QCString TranslatorCzech::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1674 of file translator_cz.h.
    { return "Seznam datovch typ"; }
trCompoundMembers()
QCString TranslatorCzech::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 307 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov poloky";
      }
      else
      {
        return "Seznam len td";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorCzech::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 392 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll)
      {
        result+="dokumentovanch ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="poloek struktur (struct) a uni (union)";
      }
      else
      {
        result+="len td";
      }
      result+=" s odkazy na ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktury/unie, ke kterm psluej:";
        }
        else
        {
          result+="tdy, ke kterm psluej:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentaci struktur/uni, ke kterm psluej:";
        }
        else
        {
          result+="dokumentaci td, ke kterm psluej:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorCzech::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1686 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll)
      {
        result+="dokumentovanch ";
      }
      result+="sloek datovch typ";
      result+=" s odkazy na ";
      if (!extractAll)
      {
         result+="dokumentaci datov struktury pro kadou sloku:";
      }
      else
      {
         result+="pslun datov typy:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorCzech::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1678 of file translator_cz.h.
    { return "Datov poloky"; }
trCompoundReference()
QCString TranslatorCzech::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 711 of file translator_cz.h.
    {
      QCString result="Dokumentace ";
      if (isTemplate) result += "ablony ";
      switch(compType)
      {
        case ClassDef::Class:      result+="tdy "; break;
        case ClassDef::Struct:     result+="struktury "; break;
        case ClassDef::Union:      result+="unie "; break;
        case ClassDef::Interface:  result+="rozhran "; break;
        case ClassDef::Protocol:   result+="protokolu "; break;
        case ClassDef::Category:   result+="kategorie "; break;
        case ClassDef::Exception:  result+="vjimky "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorCzech::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1750 of file translator_cz.h.
    {
      QCString result="Dokumentace ";
      if (isTemplate) result += "ablony ";
      switch(compType)
      {
        case ClassDef::Class:      result+="modulu "; break;
        case ClassDef::Struct:     result+="typu "; break;
        case ClassDef::Union:      result+="unie "; break;
        case ClassDef::Interface:  result+="rozhran "; break;
        case ClassDef::Protocol:   result+="protokolu "; break;
        case ClassDef::Category:   result+="kategorie "; break;
        case ClassDef::Exception:  result+="vjimky "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice()
QCString TranslatorCzech::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) inline override virtual
Implements Translator.
Definition at line 2352 of file translator_cz.h.
    {
      QCString result="Dokumentace";
      if (isLocal) result+=" lokln";
      switch(compType)
      {
        case ClassDef::Class:      result+=" tdy "; break;
        case ClassDef::Struct:     result+=" struktury "; break;
        case ClassDef::Union:      result+=" unie "; break;
        case ClassDef::Interface:
                                   if (isLocal) result+="ho";
                                   result+=" rozhran "; break;
        case ClassDef::Protocol:
                                   if (isLocal) result+="ho";
                                   result+=" protokolu "; break;
        case ClassDef::Category:   result+=" kategorie "; break;
        case ClassDef::Exception:  result+=" vyjmky "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorCzech::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 612 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov struktury";
      }
      else
      {
        return "Tdy";
      }
    }
References Config_getBool.
trCompoundType()
QCString TranslatorCzech::trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) inline override virtual
Please translate also updated body of the method trMemberFunctionDocumentation(), now better adapted for VHDL sources documentation. Done.
the compound type as used for the xrefitems
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2471 of file translator_cz.h.
    {
      QCString result;
      switch(compType)
      {
        case ClassDef::Class:
          if (lang == SrcLangExt::Fortran) trType(true,true);
          else result=trClass(true,true);
          break;
        case ClassDef::Struct:     result = "Struktury"; break;
        case ClassDef::Union:      result = "Unie"; break;
        case ClassDef::Interface:  result = "Rozhran"; break;
        case ClassDef::Protocol:   result = "Protokolu"; break;
        case ClassDef::Category:   result = "Kategorie"; break;
        case ClassDef::Exception:  result = "Vjimky"; break;
        case ClassDef::Service:    result = "Sluby"; break;
        case ClassDef::Singleton:  result = "Singletonu"; break;
        default: break;
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, Fortran, ClassDef::Interface, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, ClassDef::Struct, trClass(), trType(), and ClassDef::Union.
trConcept()
QCString TranslatorCzech::trConcept (bool first_capital, bool singular) inline override virtual
C++20 concept.
Implements Translator.
Definition at line 2404 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "koncept", "y");
    }
References Translator::createNoun().
trConceptDefinition()
QCString TranslatorCzech::trConceptDefinition () inline override virtual
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2438 of file translator_cz.h.
    {
      return "Definice koncept";
    }
trConceptDocumentation()
QCString TranslatorCzech::trConceptDocumentation () inline override virtual
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2425 of file translator_cz.h.
    { return "Dokumentace koncept"; }
trConceptIndex()
QCString TranslatorCzech::trConceptIndex () inline override virtual
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2421 of file translator_cz.h.
    { return "Rejstk koncept"; }
trConceptList()
QCString TranslatorCzech::trConceptList () inline override virtual
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2417 of file translator_cz.h.
    { return "Seznam koncept"; }
trConceptListDescription()
QCString TranslatorCzech::trConceptListDescription (bool extractAll) inline override virtual
used as an introduction to the concept list
Implements Translator.
Definition at line 2429 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="koncept se strunmi popisy:";
      return result;
    }
trConceptReference()
QCString TranslatorCzech::trConceptReference (const QCString & conceptName) inline override virtual
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2409 of file translator_cz.h.
    {
      QCString result="Dokumentace konceptu ";
      result+=conceptName;
      return result;
    }
trConstantDocumentation()
QCString TranslatorCzech::trConstantDocumentation () inline override virtual
Implements Translator.
Definition at line 2260 of file translator_cz.h.
    {
        return "Dokumentace konstant";
    }
trConstantGroupReference()
QCString TranslatorCzech::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2099 of file translator_cz.h.
    {
      QCString result="Konstantn skupiny z ";
      result+=namespaceName;
      return result;
    }
trConstantGroups()
QCString TranslatorCzech::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2095 of file translator_cz.h.
    { return "Konstantn skupiny"; }
trConstants()
QCString TranslatorCzech::trConstants () inline override virtual
Implements Translator.
Definition at line 2256 of file translator_cz.h.
    {
        return "Konstanty";
    }
trConstructorDocumentation()
QCString TranslatorCzech::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 960 of file translator_cz.h.
    {
      return "Dokumentace konstruktoru a destruktoru";
    }
trCopyright()
QCString TranslatorCzech::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1980 of file translator_cz.h.
    { return "Copyright"; }
trCustomReference()
QCString TranslatorCzech::trCustomReference (const QCString & name) inline override virtual
Implements Translator.
Definition at line 2252 of file translator_cz.h.
    { return "Dokumentace pro "+name; }
trDataMemberDocumentation()
QCString TranslatorCzech::trDataMemberDocumentation () inline override virtual
Implements Translator.
Definition at line 2386 of file translator_cz.h.
    {
        return "Dokumentace datovch len";
    }
trDataMembers()
QCString TranslatorCzech::trDataMembers () inline override virtual
Implements Translator.
Definition at line 2382 of file translator_cz.h.
    {
        return "Datov leny";
    }
trDataTypes()
QCString TranslatorCzech::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1733 of file translator_cz.h.
    { return "Datov typy"; }
trDate()
QCString TranslatorCzech::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 650 of file translator_cz.h.
    { return "Datum"; }
trDateTime()
QCString TranslatorCzech::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1929 of file translator_cz.h.
    {
      static const char *days[]   = { "po","t","st","t","p","so","ne" };
      static const char *months[] = { "led","no","be","dub","kv","er","ec","srp","z","j","lis","pro" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %d. %s %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d.%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorCzech::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1949 of file translator_cz.h.
    {
      static const char *days_short[]   = { "po", "t", "st", "t", "p", "so", "ne" };
      static const char *days_full[]    = { "pondl", "ter", "steda", "tvrtek", "ptek", "sobota", "nedle" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorCzech::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1965 of file translator_cz.h.
    {
      static const char *dayPeriod[] = { "dop.", "odp." };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorCzech::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 927 of file translator_cz.h.
    {
      return "Definice je uvedena na dku @0 v souboru @1.";
    }
trDefinedIn()
QCString TranslatorCzech::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 274 of file translator_cz.h.
    { return "definovn v"; }
trDefinedInSourceFile()
QCString TranslatorCzech::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 931 of file translator_cz.h.
    {
      return "Definice v souboru @0.";
    }
trDefineDocumentation()
QCString TranslatorCzech::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 582 of file translator_cz.h.
    { return "Dokumentace definic maker"; }
trDefines()
QCString TranslatorCzech::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 546 of file translator_cz.h.
    { return "Definice maker"; }
trDefineValue()
QCString TranslatorCzech::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1267 of file translator_cz.h.
    {
      return "Hodnota:";
    }
trDeprecated()
QCString TranslatorCzech::trDeprecated () inline override virtual
Implements Translator.
Definition at line 940 of file translator_cz.h.
    {
      return "Zastaral";
    }
trDeprecatedList()
QCString TranslatorCzech::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1462 of file translator_cz.h.
    {
      return "Seznam zastaralch prvk";
    }
trDesignUnitDocumentation()
QCString TranslatorCzech::trDesignUnitDocumentation () inline override virtual
VHDL design unit documentation.
Implements Translator.
Definition at line 2396 of file translator_cz.h.
    { return "Dokumentace nvrhov jednotky"; }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorCzech::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Implements Translator.
Definition at line 2143 of file translator_cz.h.
    { return "Hierarchie nvrhovch jednotek"; }
trDesignUnitIndex()
QCString TranslatorCzech::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Implements Translator.
Definition at line 2158 of file translator_cz.h.
    { return "Rejstk nvrhovch jednotek"; }
trDesignUnitList()
QCString TranslatorCzech::trDesignUnitList () inline override virtual
VHDL design unit list.
Implements Translator.
Definition at line 2146 of file translator_cz.h.
    { return "Seznam nvrhovch jednotek"; }
trDesignUnitListDescription()
QCString TranslatorCzech::trDesignUnitListDescription () inline override virtual
VHDL design unit list description.
Implements Translator.
Definition at line 2152 of file translator_cz.h.
    {
        return "Zde naleznete seznam vech len nvrhov jednotky s odkazy na "
            "entity, ke kterm psluej:";
    }
trDesignUnitMembers()
QCString TranslatorCzech::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Implements Translator.
Definition at line 2149 of file translator_cz.h.
    { return "Seznam len nvrhovch jednotek"; }
trDesignUnits()
QCString TranslatorCzech::trDesignUnits () inline override virtual
VHDL design units.
Implements Translator.
Definition at line 2161 of file translator_cz.h.
    { return "Nvrhov jednotky"; }
trDetailedDescription()
QCString TranslatorCzech::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 193 of file translator_cz.h.
    { return "Detailn popis"; }
trDetailLevel()
QCString TranslatorCzech::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1992 of file translator_cz.h.
    { return "rove detail"; }
trDetails()
QCString TranslatorCzech::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 197 of file translator_cz.h.
    { return "Podrobnosti"; }
trDictionaries()
QCString TranslatorCzech::trDictionaries () inline override virtual
Implements Translator.
Definition at line 2272 of file translator_cz.h.
    {
        return "Slovnky";
    }
trDictionaryDocumentation()
QCString TranslatorCzech::trDictionaryDocumentation () inline override virtual
Implements Translator.
Definition at line 2276 of file translator_cz.h.
    {
        return "Dokumentace slovnku";
    }
trDir()
QCString TranslatorCzech::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1630 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "adres", "e");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorCzech::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1984 of file translator_cz.h.
    { return "Graf zvislosti na adresch pro "+name+":"; }    // ??? not checked in a context
trDirDocumentation()
QCString TranslatorCzech::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1612 of file translator_cz.h.
    { return "Dokumentace adres"; }
trDirectories()
QCString TranslatorCzech::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1618 of file translator_cz.h.
    { return "Adrese"; }
trDirIndex()
QCString TranslatorCzech::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1606 of file translator_cz.h.
    { return "Hierarchie adres"; }
trDirReference()
QCString TranslatorCzech::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1624 of file translator_cz.h.
    { QCString result="Reference k adresi "; result+=dirName; return result; }
trDirRelation()
QCString TranslatorCzech::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1868 of file translator_cz.h.
    {
      return "Relace "+name;    // ??? not checked in a context
    }
trDocumentation()
QCString TranslatorCzech::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 472 of file translator_cz.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentace"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorCzech::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 558 of file translator_cz.h.
    { return "Vty"; }
trEnumerationTypeDocumentation()
QCString TranslatorCzech::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 594 of file translator_cz.h.
    { return "Dokumentace vtovch typ"; }
trEnumerationValueDocumentation()
QCString TranslatorCzech::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1662 of file translator_cz.h.
    { return "Dokumentace vtovch hodnot"; }
trEnumerationValues()
QCString TranslatorCzech::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 576 of file translator_cz.h.
    { return "Hodnoty vtu"; }
trEnumGeneratedFromFiles()
QCString TranslatorCzech::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 2004 of file translator_cz.h.
    { QCString result = "Dokumentace pro tento vet byla vygenerovna z nsledujc";
      if (single)
          result += "ho souboru:";
      else
          result += "ch soubor:";
      return result;
    }
trEnumName()
QCString TranslatorCzech::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 266 of file translator_cz.h.
    { return "jmno vtu"; }
trEnumReference()
QCString TranslatorCzech::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 2014 of file translator_cz.h.
    { return "Reference k vtu "+name; }
trEnumValue()
QCString TranslatorCzech::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 270 of file translator_cz.h.
    { return "hodnota vtu"; }
trEventDocumentation()
QCString TranslatorCzech::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1479 of file translator_cz.h.
    {
      return "Dokumentace udlost";
    }
trEvents()
QCString TranslatorCzech::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1474 of file translator_cz.h.
    {
      return "Udlosti";
    }
trExamples()
QCString TranslatorCzech::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 337 of file translator_cz.h.
    { return "Pklady"; }
trExamplesDescription()
QCString TranslatorCzech::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 458 of file translator_cz.h.
    { return "Zde naleznete seznam vech pklad:"; }
trExceptionDocumentation()
QCString TranslatorCzech::trExceptionDocumentation () inline override virtual
Implements Translator.
Definition at line 2348 of file translator_cz.h.
    {
        return "Dokumentace vyjmek";
    }
trExceptionHierarchy()
QCString TranslatorCzech::trExceptionHierarchy () inline override virtual
Implements Translator.
Definition at line 2340 of file translator_cz.h.
    {
        return "Hierarchie vyjmek";
    }
trExceptionHierarchyDescription()
QCString TranslatorCzech::trExceptionHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2344 of file translator_cz.h.
    {
        return "Zde naleznete seznam, vyjadujc vztah ddinosti vyjmek. Je seazen piblin (ale ne pln) podle abecedy:";
    }
trExceptionIndex()
QCString TranslatorCzech::trExceptionIndex () inline override virtual
Implements Translator.
Definition at line 2328 of file translator_cz.h.
    {
        return "Rejstk vyjmek";
    }
trExceptionList()
QCString TranslatorCzech::trExceptionList () inline override virtual
Implements Translator.
Definition at line 2332 of file translator_cz.h.
    {
        return "Seznam vyjmek";
    }
trExceptionListDescription()
QCString TranslatorCzech::trExceptionListDescription () inline override virtual
Implements Translator.
Definition at line 2336 of file translator_cz.h.
    {
        return "Nsledujc seznam obsahuje jmna vjmek a jejich strun popisy:";
    }
trExceptions()
QCString TranslatorCzech::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 666 of file translator_cz.h.
    { return "Vjimky"; }
trExtendsClass()
QCString TranslatorCzech::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2054 of file translator_cz.h.
    {
      return "Roziuje tdu @0.";
    }
trFile()
QCString TranslatorCzech::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1349 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "soubor", "y");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorCzech::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 536 of file translator_cz.h.
    { return "Dokumentace soubor"; }
trFileIn()
QCString TranslatorCzech::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1905 of file translator_cz.h.
    {
      return "Soubor v "+name;
    }
trFileIndex()
QCString TranslatorCzech::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 505 of file translator_cz.h.
    { return "Rejstk soubor"; }
trFileList()
QCString TranslatorCzech::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 303 of file translator_cz.h.
    { return "Seznam soubor"; }
trFileListDescription()
QCString TranslatorCzech::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 359 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="soubor se strunmi popisy:";
      return result;
    }
trFileMembers()
QCString TranslatorCzech::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 320 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globln symboly";
      }
      else
      {
        return "Symboly v souborech";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorCzech::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 434 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkc, promnnch, maker, vt a definic typ (typedef) "
                "s odkazy";
      }
      else
      {
        result+="symbol, kter jsou definovny na rovni svch soubor. "
                "Pro kad symbol je uveden odkaz";
      }
      result+=" na ";
      if (extractAll)
        result+="soubory, ke kterm psluej:";
      else
        result+="dokumentaci:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorCzech::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 733 of file translator_cz.h.
    {
      QCString result="Dokumentace souboru ";
      result+=fileName;
      return result;
    }
trFlowchart()
QCString TranslatorCzech::trFlowchart () inline override virtual
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2457 of file translator_cz.h.
    { return "Vvojov diagram:"; }
trFriends()
QCString TranslatorCzech::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 693 of file translator_cz.h.
    { return "Ptel tdy"; }
trFunctionAndProc()
QCString TranslatorCzech::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Implements Translator.
Definition at line 2164 of file translator_cz.h.
    { return "Funkce/Procedury/Procesy"; }
trFunctionDocumentation()
QCString TranslatorCzech::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 600 of file translator_cz.h.
    { return "Dokumentace funkc"; }
trFunctions()
QCString TranslatorCzech::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 564 of file translator_cz.h.
    { return "Funkce"; }
trGeneratedAt()
QCString TranslatorCzech::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 627 of file translator_cz.h.
    {
      QCString result="Vygenerovno dne: "+date;
      if (!projName.isEmpty()) result +=", pro projekt: "+projName;
      result+=", programem";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorCzech::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 257 of file translator_cz.h.
    { QCString result="Vygenerovno automaticky programem Doxygen "
                      "ze zdrojovch text";
      if (!s.isEmpty()) result+=" projektu "+s;
      result+=".";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorCzech::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 670 of file translator_cz.h.
    { return "Vygenerovno programem"; }
trGeneratedFromFiles()
QCString TranslatorCzech::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 882 of file translator_cz.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="Dokumentace pro ";
      switch(compType)
      {
        case ClassDef::Class:      result+=vhdlOpt?"tuto nvrhovou jednotku":"tuto tdu"; break;
        case ClassDef::Struct:     result+="tuto strukturu"; break;
        case ClassDef::Union:      result+="tuto unii"; break;
        case ClassDef::Interface:  result+="toto rozhran"; break;
        case ClassDef::Protocol:   result+="tento protokol"; break;
        case ClassDef::Category:   result+="tuto kategorii"; break;
        case ClassDef::Exception:  result+="tuto vjimku"; break;
        default: break;
      }
      result+=" byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else        result+="ch soubor:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorCzech::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1817 of file translator_cz.h.
    {
      // single is true implies a single file
      QCString result="Dokumentace pro ";
      switch(compType)
      {
        case ClassDef::Class:      result+="tento modul"; break;
        case ClassDef::Struct:     result+="tento typ"; break;
        case ClassDef::Union:      result+="tuto unii"; break;
        case ClassDef::Interface:  result+="toto rozhran"; break;
        case ClassDef::Protocol:   result+="tento protokol"; break;
        case ClassDef::Category:   result+="tuto kategorii"; break;
        case ClassDef::Exception:  result+="tuto vjimku"; break;
        default: break;
      }
      result+=" byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else result+="ch soubor:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorCzech::trGlobal (bool first_capital, bool singular) inline override virtual
??? Jak to prelozit? Bylo by dobre, kdyby se ozval nekdo, kdo to pouziva.
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1396 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "global", "s");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorCzech::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1880 of file translator_cz.h.
    {
      return "Globln jmenn prostor";
    }
trGotoDocumentation()
QCString TranslatorCzech::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 970 of file translator_cz.h.
    {
      return "Zobrazit dokumentaci tohoto souboru.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorCzech::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 1005 of file translator_cz.h.
    {
      return "Zobrazit grafickou podobu hierarchie";
    }
trGotoSourceCode()
QCString TranslatorCzech::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 965 of file translator_cz.h.
    {
      return "Zobrazit zdrojov text tohoto souboru.";
    }
trGotoTextualHierarchy()
QCString TranslatorCzech::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 1009 of file translator_cz.h.
    {
      return "Zobrazit textovou podobu hierarchie";
    }
trGraphicalHierarchy()
QCString TranslatorCzech::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 1001 of file translator_cz.h.
    {
      return "Grafick zobrazen hierarchie td";
    }
trGroup()
QCString TranslatorCzech::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1368 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "skupin", "y", "a");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorCzech::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 484 of file translator_cz.h.
    { return "Rejstk hierarchie"; }
trImplementedFromList()
QCString TranslatorCzech::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1430 of file translator_cz.h.
    {
      return "Implementuje "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorCzech::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1438 of file translator_cz.h.
    {
      return "Implementovno v "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorCzech::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 1101 of file translator_cz.h.
    {
      return "Nsledujc graf ukazuje, kter soubory pmo nebo "
             "nepmo vkldaj tento soubor:";
    }
trInclDepGraph()
QCString TranslatorCzech::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 955 of file translator_cz.h.
    {
      return "Graf zvislost na vkldanch souborech pro "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorCzech::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1914 of file translator_cz.h.
    {
      return "Vkld (include) soubor z "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorCzech::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 251 of file translator_cz.h.
    { return ", vetn vech zddnch len."; }
trInheritedByList()
QCString TranslatorCzech::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 810 of file translator_cz.h.
    {
      QCString result="Zddna ";
      result += (numEntries == 1) ? "tdou " : "tdami ";
      result += trWriteList(numEntries) + ".";
      return result;
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorCzech::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 2018 of file translator_cz.h.
    { return members+" dd se z "+what; }
trInheritsList()
QCString TranslatorCzech::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 799 of file translator_cz.h.
    {
      QCString result="Dd z ";
      result += (numEntries == 1) ? "bzov tdy " : "bzovch td ";
      result += trWriteList(numEntries) + ".";
      return result;
    }
References trWriteList().
trInitialValue()
QCString TranslatorCzech::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 992 of file translator_cz.h.
    {
      return "Inicializan hodnota:";
    }
trInstanceMethods()
QCString TranslatorCzech::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2070 of file translator_cz.h.
    {
      return "Metody instance";
    }
trInterfaceDocumentation()
QCString TranslatorCzech::trInterfaceDocumentation () inline override virtual
Implements Translator.
Definition at line 2304 of file translator_cz.h.
    {
        return "Dokumentace rozhran";
    }
trInterfaceHierarchy()
QCString TranslatorCzech::trInterfaceHierarchy () inline override virtual
Implements Translator.
Definition at line 2296 of file translator_cz.h.
    {
        return "Hierarchie rozhran";
    }
trInterfaceHierarchyDescription()
QCString TranslatorCzech::trInterfaceHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2300 of file translator_cz.h.
    {
        return "Zde naleznete seznam, vyjadujc vztah ddinosti rozhran. Je seazen piblin (ale ne pln) podle abecedy:";
    }
trInterfaceIndex()
QCString TranslatorCzech::trInterfaceIndex () inline override virtual
Implements Translator.
Definition at line 2284 of file translator_cz.h.
    {
        return "Rejstk rozhran";
    }
trInterfaceList()
QCString TranslatorCzech::trInterfaceList () inline override virtual
Implements Translator.
Definition at line 2288 of file translator_cz.h.
    {
        return "Seznam rozhran";
    }
trInterfaceListDescription()
QCString TranslatorCzech::trInterfaceListDescription () inline override virtual
Implements Translator.
Definition at line 2292 of file translator_cz.h.
    {
        return "Nsledujc seznam obsahuje jmna rozhran a jejich strun popisy:";
    }
trInterfaces()
QCString TranslatorCzech::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2087 of file translator_cz.h.
    { return "Exportovan rozhran"; }
trInvariant()
QCString TranslatorCzech::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 987 of file translator_cz.h.
    {
      return "Invariant";    // ???
    }
trISOLang()
QCString TranslatorCzech::trISOLang () inline override virtual
Implements Translator.
Definition at line 173 of file translator_cz.h.
    {
      return "cs";
    }
trLegend()
QCString TranslatorCzech::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1201 of file translator_cz.h.
    {
      return "vysvtlivky";
    }
trLegendDocs()
QCString TranslatorCzech::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1123 of file translator_cz.h.
    {
      return
        "Zde naleznete vysvtlen, jak maj bt interpretovny grafy, "
        "kter byly vygenerovny programem doxygen.<p>\n"
        "Uvaujte nsledujc pklad:\n"
        "\\code\n"
        "/*! Neviditeln tda, kter se v grafu nezobrazuje, protoe "
        "dolo k oezn grafu. */\n"
        "class Invisible { };\n\n"
        "/*! Tda, u kter dolo k oezn grafu. Vztah ddinosti "
        "je skryt. */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Tda, kter nen dokumentovna komenti programu doxygen. */\n"
        "class Undocumented { };\n\n"
        "/*! Bzov tda ddn veejn (public inheritance). */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! ablona tdy. */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Bzov tda, pouit pro chrnn ddn "
        "(protected inheritance). */\n"
        "class ProtectedBase { };\n\n"
        "/*! Bzov tda, vyuit pro privtn ddn "
        "(private inheritance). */\n"
        "class PrivateBase { };\n\n"
        "/*! Tda, kter je vyuvna tdou Inherited. */\n"
        "class Used { };\n\n"
        "/*! Odvozen tda, kter dd z vce td. */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "K ve uvedenmu bude vygenerovn nsledujc graf:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Bloky (tj. uzly) v uvedenm grafu maj nsledujc vznam:\n"
        "</p>\n"
        "<ul>\n"
        "<li>ed vyplnn obdlnk reprezentuje strukturu nebo tdu, "
            "pro kterou byl graf vygenerovn.</li>\n"
        "<li>Obdlnk s ernm obrysem oznauje dokumentovanou "
            "strukturu nebo tdu.</li>\n"
        "<li>Obdlnk s edm obrysem oznauje nedokumentovanou "
            "strukturu nebo tdu.</li>\n"
        "<li>Obdlnk s ervenm obrysem oznauje dokumentovanou "
            "strukturu nebo tdu, pro kterou\n"
            "nejsou zobrazeny vechny vztahy ddinosti nebo obsaen. "
            "Graf je oezn v ppad, kdy jej\n"
            "nen mon umstit do vymezenho prostoru.</li>\n"
        "</ul>\n"
        "<p>\n"
        "ipky (tj. hrany grafu) maj nsledujc vznam:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Modr ipka se pouv pro oznaen vztahu veejn "
            "ddinosti (public) mezi dvma tdami.</li>\n"
        "<li>Tmav zelen ipka oznauje vztah chrnn ddinosti "
            "(protected).</li>\n"
        "<li>Tmav erven ipka oznauje vztah privtn ddinosti "
            "(private).</li>\n"
        "<li>Purpurov ipka kreslen rkovan se pouv v ppad, "
            "kdy je tda obsaena v jin td,\n"
            "nebo kdy je pouvna jinou tdou. ipka je oznaena "
            "identifiktorem jedn nebo vce promnnch, pes kter\n"
            "je tda nebo struktura zpstupnna.</li>\n"
        "<li>lut ipka kreslen rkovan vyjaduje vztah mezi instanc ablony "
            "a ablonou tdy, na zklad kter byla\n"
            "instance ablony vytvoena. V popisu ipky jsou uvedeny pslun "
            "parametry ablony.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorCzech::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 1116 of file translator_cz.h.
    {
      return "Vysvtlivky ke grafu";
    }
trListOfAllMembers()
QCString TranslatorCzech::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 239 of file translator_cz.h.
    { return "Seznam vech len"; }
trLoading()
QCString TranslatorCzech::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1874 of file translator_cz.h.
    {
      return "Natm...";
    }
trMainPage()
QCString TranslatorCzech::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 914 of file translator_cz.h.
    { return "Hlavn strnka"; }
trMember()
QCString TranslatorCzech::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1386 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "len", "y");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorCzech::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 222 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentace poloek";
      }
      else
      {
        return "Dokumentace datovch len";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorCzech::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 205 of file translator_cz.h.
    { return "Dokumentace lenskch vt"; }
trMemberFunctionDocumentation()
QCString TranslatorCzech::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 209 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Dokumentace lenskch funkc/procedur/proces";
      }
      else
      {
        return "Dokumentace lenskch funkc";
      }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran()
QCString TranslatorCzech::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1670 of file translator_cz.h.
    { return "Dokumentace lenskch funkc/podprogram"; }
trMemberList()
QCString TranslatorCzech::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 243 of file translator_cz.h.
    { return "Seznam len tdy"; }
trMemberTypedefDocumentation()
QCString TranslatorCzech::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 201 of file translator_cz.h.
    { return "Dokumentace lenskch typ"; }
trMethodDocumentation()
QCString TranslatorCzech::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2077 of file translator_cz.h.
    {
      return "Dokumentace metody";
    }
trModule()
QCString TranslatorCzech::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1809 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "modul", "y");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorCzech::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 511 of file translator_cz.h.
    { return "Dokumentace modul"; }
trModuleIndex()
QCString TranslatorCzech::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 478 of file translator_cz.h.
    { return "Rejstk modul"; }
trModuleReference()
QCString TranslatorCzech::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1771 of file translator_cz.h.
    {
      QCString result="Dokumentace modulu ";
      result += namespaceName;
      return result;
    }
trModules()
QCString TranslatorCzech::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 282 of file translator_cz.h.
    { return "Moduly"; }
trModulesDescription()
QCString TranslatorCzech::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 466 of file translator_cz.h.
    { return "Zde naleznete seznam vech modul:"; }
trModulesIndex()
QCString TranslatorCzech::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1802 of file translator_cz.h.
    { return "Rejstk modul"; }
trModulesList()
QCString TranslatorCzech::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1737 of file translator_cz.h.
    { return "Seznam modul"; }
trModulesListDescription()
QCString TranslatorCzech::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1741 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="modul se strunmi popisy:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorCzech::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1783 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="st modul s odkazy ";
      if (extractAll)
      {
        result+="na dokumentaci modulu pro danou st:";
      }
      else
      {
        result+="na moduly, ke kterm st pat:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorCzech::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1779 of file translator_cz.h.
    { return "sti modulu"; }
trMonth()
QCString TranslatorCzech::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1957 of file translator_cz.h.
    {
      static const char *months_short[] = { "led", "no", "be", "dub", "kv", "vn", "vc", "srp", "z", "j", "lis", "pro" };
      static const char *months_full[]  = { "leden", "nor", "bezen", "duben", "kvten", "erven", "ervenec", "srpen", "z", "jen", "listopad", "prosinec" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorCzech::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 235 of file translator_cz.h.
    { return "..."; }
trNamespace()
QCString TranslatorCzech::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1358 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "jmenn", "", "") +
             createNoun(false, singular, " prostor", "y");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorCzech::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 862 of file translator_cz.h.
    { return "Dokumentace jmennch prostor"; }
trNamespaceIndex()
QCString TranslatorCzech::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 856 of file translator_cz.h.
    { return "Rejstk jmennch prostor"; }
trNamespaceList()
QCString TranslatorCzech::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 678 of file translator_cz.h.
    { return "Seznam jmennch prostor"; }
trNamespaceListDescription()
QCString TranslatorCzech::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 682 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="jmennch prostor se strunm popisem:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorCzech::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 841 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="symbol, kter jsou definovny ve svch jmennch prostorech. "
              "U kadho je uveden odkaz na ";
      if (extractAll)
        result+="dokumentaci pslunho jmennho prostoru:";
      else
        result+="pslun jmenn prostor:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorCzech::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 837 of file translator_cz.h.
    { return "Symboly ve jmennm prostoru"; }
trNamespaceReference()
QCString TranslatorCzech::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 741 of file translator_cz.h.
    {
      QCString result="Dokumentace jmennho prostoru ";
      result+=namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorCzech::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 872 of file translator_cz.h.
    { return "Jmenn prostory"; }
trNoMatches()
QCString TranslatorCzech::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1892 of file translator_cz.h.
    {
      return "Nebylo nic nalezeno";
    }
trNote()
QCString TranslatorCzech::trNote () inline override virtual
Implements Translator.
Definition at line 1022 of file translator_cz.h.
    {
      return "Poznmka";
    }
trOperationDocumentation()
QCString TranslatorCzech::trOperationDocumentation () inline override virtual
Implements Translator.
Definition at line 2378 of file translator_cz.h.
    {
        return "Dokumentace operace";
    }
trOperations()
QCString TranslatorCzech::trOperations () inline override virtual
Implements Translator.
Definition at line 2374 of file translator_cz.h.
    {
        return "Operace";
    }
trOverloadText()
QCString TranslatorCzech::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1642 of file translator_cz.h.
    {
       return "Jde o petenou (overloaded) metodu, "
              "kter m usnadnit pouvn. Od ve uveden metody se li "
              "pouze jinak zadvanmi argumenty.";
    }
trPackage()
QCString TranslatorCzech::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1252 of file translator_cz.h.
    {
      return "Balk "+name;
    }
trPackageAttribs()
QCString TranslatorCzech::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1515 of file translator_cz.h.
    {
      return "Atributy v balku";    // ??? not checked in a context
    }
trPackageFunctions()
QCString TranslatorCzech::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1497 of file translator_cz.h.
    {
      return "Funkce v balku";
    }
trPackageList()
QCString TranslatorCzech::trPackageList () inline override virtual
Implements Translator.
Definition at line 2447 of file translator_cz.h.
    { return "Seznam balk"; }
trPackageListDescription()
QCString TranslatorCzech::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1257 of file translator_cz.h.
    {
      return "Zde naleznete seznam balk se strunm popisem (pokud byl uveden):";
    }
trPackageMembers()
QCString TranslatorCzech::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1501 of file translator_cz.h.
    {
      return "leny v balku";    // ??? not checked in a context
    }
trPackages()
QCString TranslatorCzech::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1262 of file translator_cz.h.
    {
      return "Balky";
    }
trPackageTypes()
QCString TranslatorCzech::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1490 of file translator_cz.h.
    {
      return "Typy v balku";
    }
trPage()
QCString TranslatorCzech::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1377 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "strnk", "y", "a");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorCzech::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 920 of file translator_cz.h.
    { return "s."; }
trPageIndex()
QCString TranslatorCzech::trPageIndex () inline override virtual
Implements Translator.
Definition at line 1013 of file translator_cz.h.
    {
      return "Rejstk strnek";
    }
trPanelSynchronisationTooltip()
QCString TranslatorCzech::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 2035 of file translator_cz.h.
    {
      QCString opt = enable ? "povolit" : "zakzat";
      return opt + " synchronizaci panel";
    }
trParameters()
QCString TranslatorCzech::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 662 of file translator_cz.h.
    { return "Parametry"; }
trPostcondition()
QCString TranslatorCzech::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 982 of file translator_cz.h.
    {
      return "Postcondition";    // ???
    }
trPrecondition()
QCString TranslatorCzech::trPrecondition () inline override virtual
??? Jak to prelozit? Bylo by dobre, kdyby se ozval nekdo, kdo to pouziva.
Text for the \pre command
Implements Translator.
Definition at line 977 of file translator_cz.h.
    {
      return "Precondition";    // ???
    }
trPrivateAttribs()
QCString TranslatorCzech::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 1061 of file translator_cz.h.
    {
      return "Privtn atributy";
    }
trPrivateMembers()
QCString TranslatorCzech::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 765 of file translator_cz.h.
    { return "Privtn metody"; }
trPrivateSlots()
QCString TranslatorCzech::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 767 of file translator_cz.h.
    { return "Privtn sloty"; }
trPrivateTypes()
QCString TranslatorCzech::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 1057 of file translator_cz.h.
    {
      return "Privtn typy";
    }
trProperties()
QCString TranslatorCzech::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1226 of file translator_cz.h.
    {
      return "Vlastnosti";
    }
trPropertyDocumentation()
QCString TranslatorCzech::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1231 of file translator_cz.h.
    {
      return "Dokumentace vlastnost";
    }
trProtectedAttribs()
QCString TranslatorCzech::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 1049 of file translator_cz.h.
    {
      return "Chrnn atributy";
    }
trProtectedMembers()
QCString TranslatorCzech::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 759 of file translator_cz.h.
    { return "Chrnn metody"; }
trProtectedSlots()
QCString TranslatorCzech::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 761 of file translator_cz.h.
    { return "Chrnn sloty"; }
trProtectedTypes()
QCString TranslatorCzech::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 1045 of file translator_cz.h.
    {
      return "Chrnn typy";
    }
trProvidedByCategory()
QCString TranslatorCzech::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2045 of file translator_cz.h.
    {
      return "Deklarovno v kategorii @0.";
    }
trPublicAttribs()
QCString TranslatorCzech::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 1030 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov poloky";
      }
      else
      {
        return "Veejn atributy";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorCzech::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 751 of file translator_cz.h.
    { return "Veejn metody"; }
trPublicSlots()
QCString TranslatorCzech::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 753 of file translator_cz.h.
    { return "Veejn sloty"; }
trPublicTypes()
QCString TranslatorCzech::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 1026 of file translator_cz.h.
    {
      return "Veejn typy";
    }
trReferencedBy()
QCString TranslatorCzech::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 1089 of file translator_cz.h.
    {
      return "Pouv se v";
    }
trReferenceManual()
QCString TranslatorCzech::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 540 of file translator_cz.h.
    { return "Referenn pruka"; }
trReferences()
QCString TranslatorCzech::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1418 of file translator_cz.h.
    {
      return "Odkazuje se na";
    }
trReimplementedFromList()
QCString TranslatorCzech::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 821 of file translator_cz.h.
    {
      QCString result="Reimplementuje stejnojmenn prvek z ";
      result += trWriteList(numEntries) + ".";
      return result;
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorCzech::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 831 of file translator_cz.h.
    {
      return "Reimplementovno v "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorCzech::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 703 of file translator_cz.h.
    { return "Dokumentace ptel a souvisejcch funkc tdy"; }
trRelatedFunctions()
QCString TranslatorCzech::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 185 of file translator_cz.h.
    { return "Souvisejc funkce"; }
trRelatedPages()
QCString TranslatorCzech::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 333 of file translator_cz.h.
    { return "Ostatn strnky"; }
trRelatedPagesDescription()
QCString TranslatorCzech::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 462 of file translator_cz.h.
    { return "Nsledujc seznam odkazuje na dal strnky projektu:"; }
trRelatedSubscript()
QCString TranslatorCzech::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 189 of file translator_cz.h.
    { return "(Uveden funkce nejsou lenskmi funkcemi.)"; }
trRemarks()
QCString TranslatorCzech::trRemarks () inline override virtual
Implements Translator.
Definition at line 1093 of file translator_cz.h.
    {
      return "Poznmky";    // ??? not checked in a context
    }
trReturns()
QCString TranslatorCzech::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 654 of file translator_cz.h.
    { return "Nvratov hodnota"; }
trReturnValues()
QCString TranslatorCzech::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 909 of file translator_cz.h.
    { return "Vracen hodnoty"; }
trRTFansicp()
QCString TranslatorCzech::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1316 of file translator_cz.h.
    {
      return "1250";
    }
trRTFCharSet()
QCString TranslatorCzech::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1325 of file translator_cz.h.
    {
      return "238";
    }
trRTFGeneralIndex()
QCString TranslatorCzech::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1331 of file translator_cz.h.
    {
      return "Rejstk";
    }
trRTFTableOfContents()
QCString TranslatorCzech::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1450 of file translator_cz.h.
    {
      return "Obsah";
    }
trSearch()
QCString TranslatorCzech::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 341 of file translator_cz.h.
    { return "Hledat"; }
trSearching()
QCString TranslatorCzech::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1886 of file translator_cz.h.
    {
      return "Vyhledvm...";
    }
trSearchMatches()
QCString TranslatorCzech::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1583 of file translator_cz.h.
    {
      return "Nalezen slova:";
    }
trSearchResults()
QCString TranslatorCzech::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1563 of file translator_cz.h.
    {
      if (numDocuments==0)
      {
        return "Lituji. Vaemu dotazu neodpovd dn dokument.";
      }
      else if (numDocuments==1)
      {
        return "Nalezen jeden dokument, kter vyhovuje vaemu dotazu.";
      }
      else
      {
        return "Nalezeno <b>$num</b> dokument, kter vyhovuj vaemu "
                      "dotazu. Nejlpe odpovdajc dokumenty jsou zobrazeny "
                      "jako prvn.";
      }
    }
trSearchResultsTitle()
QCString TranslatorCzech::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1551 of file translator_cz.h.
    {
      return "Vsledky vyhledvn";
    }
trSeeAlso()
QCString TranslatorCzech::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 658 of file translator_cz.h.
    { return "Viz tak"; }
trSequenceDocumentation()
QCString TranslatorCzech::trSequenceDocumentation () inline override virtual
Implements Translator.
Definition at line 2268 of file translator_cz.h.
    {
        return "Dokumentace sekvence";
    }
trSequences()
QCString TranslatorCzech::trSequences () inline override virtual
Implements Translator.
Definition at line 2264 of file translator_cz.h.
    {
        return "Sekvence";
    }
trServiceGeneratedFromFiles()
QCString TranslatorCzech::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 2120 of file translator_cz.h.
    {
      // single is true implies a single file
      QCString result="Dokumentace k tto slub byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else        result+="ch soubor:";
      return result;
    }
trServiceReference()
QCString TranslatorCzech::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 2106 of file translator_cz.h.
    {
      QCString result="Popis sluby ";
      result+=sName;
      return result;
    }
trServices()
QCString TranslatorCzech::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2091 of file translator_cz.h.
    { return "Zalenn sluby"; }
trSignals()
QCString TranslatorCzech::trSignals () inline override virtual
Implements Translator.
Definition at line 755 of file translator_cz.h.
    { return "Signly"; }
trSince()
QCString TranslatorCzech::trSince () inline override virtual
Implements Translator.
Definition at line 1106 of file translator_cz.h.
    {
      return "Od";    // ??? not checked in a context
    }
trSingletonGeneratedFromFiles()
QCString TranslatorCzech::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 2129 of file translator_cz.h.
    {
      // single is true implies a single file
      QCString result="Dokumentace k tomuto singletonu byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else        result+="ch soubor:";
      return result;
    }
trSingletonReference()
QCString TranslatorCzech::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 2113 of file translator_cz.h.
    {
      QCString result="Popis singletonu ";
      result+=sName;
      return result;
    }
trSliceInterfaces()
QCString TranslatorCzech::trSliceInterfaces () inline override virtual
Implements Translator.
Definition at line 2280 of file translator_cz.h.
    {
        return "Rozhran";
    }
trSourceFile()
QCString TranslatorCzech::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1594 of file translator_cz.h.
    {
      return "Zdrojov soubor " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorCzech::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1522 of file translator_cz.h.
    {
      return "Statick atributy v balku";    // ??? not checked in a context
    }
trStaticPackageFunctions()
QCString TranslatorCzech::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1508 of file translator_cz.h.
    {
      return "Statick funkce v balku";
    }
trStaticPrivateAttribs()
QCString TranslatorCzech::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 1065 of file translator_cz.h.
    {
      return "Statick privtn atributy";
    }
trStaticPrivateMembers()
QCString TranslatorCzech::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 769 of file translator_cz.h.
    { return "Statick privtn metody"; }
trStaticProtectedAttribs()
QCString TranslatorCzech::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 1053 of file translator_cz.h.
    {
      return "Statick chrnn atributy";
    }
trStaticProtectedMembers()
QCString TranslatorCzech::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 763 of file translator_cz.h.
    { return "Statick chrnn metody"; }
trStaticPublicAttribs()
QCString TranslatorCzech::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 1041 of file translator_cz.h.
    {
      return "Statick veejn atributy";
    }
trStaticPublicMembers()
QCString TranslatorCzech::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 757 of file translator_cz.h.
    { return "Statick veejn metody"; }
trStructDocumentation()
QCString TranslatorCzech::trStructDocumentation () inline override virtual
Implements Translator.
Definition at line 2324 of file translator_cz.h.
    {
        return "Dokumentace struktur";
    }
trStructIndex()
QCString TranslatorCzech::trStructIndex () inline override virtual
Implements Translator.
Definition at line 2312 of file translator_cz.h.
    {
        return "Rejstk struktur";
    }
trStructList()
QCString TranslatorCzech::trStructList () inline override virtual
Implements Translator.
Definition at line 2316 of file translator_cz.h.
    {
        return "Seznam struktur";
    }
trStructListDescription()
QCString TranslatorCzech::trStructListDescription () inline override virtual
Implements Translator.
Definition at line 2320 of file translator_cz.h.
    {
        return "Nsledujc seznam obsahuje jmna struktur a jejich strun popisy:";
    }
trStructs()
QCString TranslatorCzech::trStructs () inline override virtual
Implements Translator.
Definition at line 2308 of file translator_cz.h.
    {
        return "Struktury";
    }
trSubprogram()
QCString TranslatorCzech::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1852 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "podprogram", "y");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorCzech::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1727 of file translator_cz.h.
    { return "Dokumentace funkce/podprogramu"; }
trSubprograms()
QCString TranslatorCzech::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1721 of file translator_cz.h.
    { return "Funkce/podprogramy"; }
trTemplateParameters()
QCString TranslatorCzech::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1996 of file translator_cz.h.
    { return "Parametry ablony"; }
trTest()
QCString TranslatorCzech::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1211 of file translator_cz.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorCzech::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1216 of file translator_cz.h.
    {
      return "Seznam test";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorCzech::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 247 of file translator_cz.h.
    { return "Zde naleznete pln seznam len tdy"; }
trTodo()
QCString TranslatorCzech::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1075 of file translator_cz.h.
    {
      return "Plnovan pravy";
    }
trTodoList()
QCString TranslatorCzech::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 1080 of file translator_cz.h.
    {
      return "Seznam plnovanch prav";
    }
trType()
QCString TranslatorCzech::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1843 of file translator_cz.h.
    {
      return createNoun(first_capital, singular, "typ", "y");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trTypeConstraints()
QCString TranslatorCzech::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1858 of file translator_cz.h.
    {
      return "Omezen typ (Type Constraints)";
    }
trTypedefDocumentation()
QCString TranslatorCzech::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 588 of file translator_cz.h.
    { return "Dokumentace definic typ"; }
trTypedefs()
QCString TranslatorCzech::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 552 of file translator_cz.h.
    { return "Definice typ"; }
trTypeDocumentation()
QCString TranslatorCzech::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1715 of file translator_cz.h.
    { return "Dokumentace datovch typ"; }
trVariableDocumentation()
QCString TranslatorCzech::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 606 of file translator_cz.h.
    { return "Dokumentace promnnch"; }
trVariables()
QCString TranslatorCzech::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 570 of file translator_cz.h.
    { return "Promnn"; }
trVersion()
QCString TranslatorCzech::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 646 of file translator_cz.h.
    { return "Verze"; }
trVhdlType()
QCString TranslatorCzech::trVhdlType (VhdlSpecifier type, bool single) inline override virtual
VHDL type.
Implements Translator.
Definition at line 2167 of file translator_cz.h.
    {
      switch(type)
      {
        case VhdlSpecifier::LIBRARY:
          if (single) return "Knihovna";
          else        return "Knihovny";
        case VhdlSpecifier::PACKAGE:
          if (single) return "Balk";
          else        return "Balky";
        case VhdlSpecifier::SIGNAL:
          if (single) return "Signl";
          else        return "Signly";
        case VhdlSpecifier::COMPONENT:
          if (single) return "Komponenta";
          else        return "Komponenty";
        case VhdlSpecifier::CONSTANT:
          if (single) return "Konstanta";
          else        return "Konstanty";
        case VhdlSpecifier::ENTITY:
          if (single) return "Entita";
          else        return "Entity";
        case VhdlSpecifier::TYPE:
          if (single) return "Typ";
          else        return "Typy";
        case VhdlSpecifier::SUBTYPE:
          if (single) return "Subtyp";
          else        return "Subtypy";
        case VhdlSpecifier::FUNCTION:
          if (single) return "Funkce";
          else        return "Funkce";
        case VhdlSpecifier::RECORD:
          if (single) return "Zznam";
          else        return "Zznamy";
        case VhdlSpecifier::PROCEDURE:
          if (single) return "Procedura";
          else        return "Procedury";
        case VhdlSpecifier::ARCHITECTURE:
          if (single) return "Architektura";
          else        return "Architektury";
        case VhdlSpecifier::ATTRIBUTE:
          if (single) return "Atribut";
          else        return "Atributy";
        case VhdlSpecifier::PROCESS:
          if (single) return "Proces";
          else        return "Procesy";
        case VhdlSpecifier::PORT:
          if (single) return "Brna";
          else        return "Brny";
        case VhdlSpecifier::USE:
          if (single) return "Klauzule use";
          else        return "Klauzule use";
        case VhdlSpecifier::GENERIC:
          if (single) return "Generick parametr";
          else        return "Generick parametry";
        case VhdlSpecifier::PACKAGE_BODY:
          return "Tlo balku";
        case VhdlSpecifier::UNITS:
          return "Fyzikln jednotky";
        case VhdlSpecifier::SHAREDVARIABLE:
          if (single) return "Sdlen promnn";
          else        return "Sdlen promnn";
        case VhdlSpecifier::VFILE:
          if (single) return "Soubor";
          else        return "Soubory";
        case VhdlSpecifier::GROUP:
          if (single) return "Skupina";
          else        return "Skupiny";
        case VhdlSpecifier::INSTANTIATION:
          if (single) return "Vloen instance";
          else        return "Vloen instance";
        case VhdlSpecifier::ALIAS:
          if (single) return "Alias";
          else        return "Aliasy";
        case VhdlSpecifier::CONFIG:
          if (single) return "Konfigurace";
          else        return "Konfigurace";
        case VhdlSpecifier::MISCELLANEOUS:
          return "Ostatn";
        case VhdlSpecifier::UCF_CONST:
          return "Omezen (constraints)";
        default:
          return "Tda";
      }
    }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorCzech::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 642 of file translator_cz.h.
    { return "Pozor"; }
trWriteList()
QCString TranslatorCzech::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 775 of file translator_cz.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" a ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_cz.h