Doxygen: ConfigEnum Class Reference
ConfigEnum Class Reference
Class representing an enum type option.
#include <src/configimpl.h>
Public Member Functions
ConfigEnum (const char *name, const char *doc, const char *defVal)
void addValue (const char *v)
const std::vector< QCString > & values () const
QCString * valueRef ()
void substEnvVars () override
void writeTemplate (TextStream &t, bool sl, bool) override
void convertStrToVal (Config::CompareMode compareMode) override
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode) override
void writeXMLDoxyfile (TextStream &t) override
void writeXSDDoxyfile (TextStream &t) override
void init () override
bool isDefault () override
Public Member Functions inherited from ConfigOption
ConfigOption (OptionType t)
OptionType kind () const
QCString name () const
QCString docs () const
QCString dependsOn () const
void addDependency (const char *dep)
void setEncoding (const QCString &e)
void setUserComment (const QCString &u)
Private Attributes
std::vector< QCString > m_valueRange
QCString m_value
QCString m_defValue
Additional Inherited Members
Public Types inherited from ConfigOption
enum OptionType {
O_Info , O_List , O_Enum , O_String ,
O_Int , O_Bool , O_Obsolete , O_Disabled
}
enum { MAX_OPTION_LENGTH = 23 }
Protected Member Functions inherited from ConfigOption
virtual void emptyValueToDefault ()
void writeBoolValue (TextStream &t, bool v, bool initSpace=true)
void writeIntValue (TextStream &t, int i, bool initSpace=true)
void writeStringValue (TextStream &t, const QCString &s, bool initSpace=true, bool wasQuoted=false)
void writeStringList (TextStream &t, const StringVector &l)
Protected Attributes inherited from ConfigOption
QCString m_spaces
QCString m_name
QCString m_doc
QCString m_dependency
QCString m_encoding
QCString m_userComment
OptionType m_kind
Detailed Description
Class representing an enum type option.
Definition at line 155 of file configimpl.h.
Constructor & Destructor Documentation
ConfigEnum()
ConfigEnum::ConfigEnum (const char * name, const char * doc, const char * defVal) inline
Definition at line 158 of file configimpl.h.
      : ConfigOption(O_Enum)
    {
      m_name = name;
      m_doc = doc;
      m_value = defVal;
      m_defValue = defVal;
    }
References ConfigOption::ConfigOption(), m_defValue, ConfigOption::m_doc, ConfigOption::m_name, m_value, ConfigOption::name(), and ConfigOption::O_Enum.
Member Function Documentation
addValue()
void ConfigEnum::addValue (const char * v) inline
Definition at line 166 of file configimpl.h.
{ m_valueRange.emplace_back(v); }
References m_valueRange.
compareDoxyfile()
void ConfigEnum::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) override virtual
Implements ConfigOption.
Definition at line 473 of file configimpl.l.
{
  if (!isDefault()) writeTemplate(t,TRUE,TRUE);
}
References isDefault(), TRUE, and writeTemplate().
convertStrToVal()
void ConfigEnum::convertStrToVal (Config::CompareMode compareMode) override virtual
Reimplemented from ConfigOption.
Definition at line 269 of file configimpl.l.
{
  if (m_value.isEmpty())
  {
    m_value = m_defValue;
    return;
  }
  if (compareMode == Config::CompareMode::CompressedNoEnv)
  {
     if (containsEnvVar(m_value)) return;
  }
  QCString val = m_value.stripWhiteSpace().lower();
  for (const auto &s : m_valueRange)
  {
    if (s.lower() == val)
    {
       m_value = s;
       return;
    }
  }
  ConfigImpl::config_warn("argument '%s' for option %s is not a valid enum value\n"
              "Using the default: %s!\n",qPrint(m_value),qPrint(m_name),qPrint(m_defValue));
  m_value = m_defValue;
}
References Config::CompressedNoEnv, ConfigImpl::config_warn(), containsEnvVar(), m_defValue, ConfigOption::m_name, m_value, m_valueRange, and qPrint().
init()
void ConfigEnum::init () inline override virtual
Reimplemented from ConfigOption.
Definition at line 175 of file configimpl.h.
{ m_value = m_defValue; }
References m_defValue, and m_value.
isDefault()
bool ConfigEnum::isDefault () inline override virtual
Reimplemented from ConfigOption.
Definition at line 176 of file configimpl.h.
{ return m_value == m_defValue; }
References m_defValue, and m_value.
Referenced by compareDoxyfile(), and writeXMLDoxyfile().
substEnvVars()
void ConfigEnum::substEnvVars () override virtual
Implements ConfigOption.
Definition at line 1534 of file configimpl.l.
{
  substEnvVarsInString(m_value);
}
References m_value, and substEnvVarsInString().
valueRef()
QCString * ConfigEnum::valueRef () inline
Definition at line 168 of file configimpl.h.
{ return &m_value; }
References m_value.
Referenced by Config::updateObsolete().
values()
const std::vector< QCString > & ConfigEnum::values () const inline
Definition at line 167 of file configimpl.h.
{ return m_valueRange; }
References m_valueRange.
writeTemplate()
void ConfigEnum::writeTemplate (TextStream & t, bool sl, bool) override virtual
Implements ConfigOption.
Definition at line 456 of file configimpl.l.
{
  if (!sl)
  {
    t << "\n";
    t << convertToComment(m_doc, m_userComment);
    t << "\n";
  }
  else if (!m_userComment.isEmpty())
  {
    t << convertToComment("", m_userComment);
  }
  t << m_name << m_spaces.left(MAX_OPTION_LENGTH-m_name.length()) << "=";
  writeStringValue(t,m_value);
  t << "\n";
}
References convertToComment(), ConfigOption::m_doc, ConfigOption::m_name, ConfigOption::m_spaces, ConfigOption::m_userComment, m_value, ConfigOption::MAX_OPTION_LENGTH, and ConfigOption::writeStringValue().
Referenced by compareDoxyfile().
writeXMLDoxyfile()
void ConfigEnum::writeXMLDoxyfile (TextStream & t) override virtual
Implements ConfigOption.
Definition at line 478 of file configimpl.l.
{
  t << "  <option  id='" << m_name << "'";
  t << " default='" << (isDefault() ? "yes" : "no") << "'";
  t << " type='string'";
  t << ">";
  t << "<value>";
  writeStringValue(t,m_value,false);
  t << "</value>";
  t << "</option>\n";
}
References isDefault(), ConfigOption::m_name, m_value, and ConfigOption::writeStringValue().
writeXSDDoxyfile()
void ConfigEnum::writeXSDDoxyfile (TextStream & t) override virtual
Implements ConfigOption.
Definition at line 490 of file configimpl.l.
{
  t << "      <xsd:enumeration value=\"" << m_name << "\"/>\n";
}
References ConfigOption::m_name.
Member Data Documentation
m_defValue
QCString ConfigEnum::m_defValue private
Definition at line 181 of file configimpl.h.
Referenced by ConfigEnum(), convertStrToVal(), init(), and isDefault().
m_value
QCString ConfigEnum::m_value private
Definition at line 180 of file configimpl.h.
Referenced by ConfigEnum(), convertStrToVal(), init(), isDefault(), substEnvVars(), valueRef(), writeTemplate(), and writeXMLDoxyfile().
m_valueRange
std::vector<QCString> ConfigEnum::m_valueRange private
Definition at line 179 of file configimpl.h.
Referenced by addValue(), convertStrToVal(), and values().
The documentation for this class was generated from the following files:
src/configimpl.h
src/configimpl.l