Doxygen: DocHtmlBlockQuote Class Reference
DocHtmlBlockQuote Class Reference
Node representing an HTML blockquote.
#include <src/docnode.h>
Public Member Functions
DocHtmlBlockQuote (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
Token parse ()
const HtmlAttribList & attribs () const
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
HtmlAttribList m_attribs
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing an HTML blockquote.
Definition at line 1269 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlBlockQuote()
DocHtmlBlockQuote::DocHtmlBlockQuote (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) inline
Definition at line 1272 of file docnode.h.
      : DocCompoundNode(parser,parent), m_attribs(attribs) {}
References attribs(), DocCompoundNode::DocCompoundNode(), m_attribs, DocNode::parent(), and DocNode::parser().
Member Function Documentation
attribs()
const HtmlAttribList & DocHtmlBlockQuote::attribs () const inline
Definition at line 1275 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by DocHtmlBlockQuote(), and HtmlDocVisitor::operator()().
parse()
Token DocHtmlBlockQuote::parse ()
Definition at line 2672 of file docnode.cpp.
{
  AUTO_TRACE();
  Token retval = Token::make_TK_NONE();
  auto ns = AutoNodeStack(parser(),thisVariant());
  // parse one or more paragraphs
  bool isFirst=TRUE;
  DocPara *par=nullptr;
  do
  {
    children().append<DocPara>(parser(),thisVariant());
    par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse();
  }
  while (retval.is(TokenRetval::TK_NEWPARA));
  if (par) par->markLast();
  if (retval.is_any_of(TokenRetval::TK_NONE,TokenRetval::TK_EOF))
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment while inside <blockquote> block");
  }
  AUTO_TRACE_EXIT("retval={}",retval.to_string());
  return retval.is(TokenRetval::RetVal_EndBlockQuote) ? Token::make_RetVal_OK() : retval;
}
References DocNodeList::append(), AUTO_TRACE, AUTO_TRACE_EXIT, DocCompoundNode::children(), FALSE, DocNodeList::get_last(), Token::is(), Token::is_any_of(), DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), DocNode::parser(), DocNode::thisVariant(), Token::to_string(), TRUE, and warn_doc_error.
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlBlockQuote::m_attribs private
Definition at line 1278 of file docnode.h.
Referenced by attribs(), and DocHtmlBlockQuote().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp