Doxygen: DocNodeList Struct Reference
DocNodeList Struct Reference
#include <docnode.h>
Public Member Functions
template<class T , class... Args>
void append (Args &&... args)
Append a new DocNodeVariant to the list by constructing it with type T and parameters Args.
void move_append (DocNodeList &l)
moves the element of list l at the end of this list.
template<class T >
T * get_last ()
Returns a pointer to the last element in the list if that element exists and holds a T, otherwise nullptr is returned.
Public Member Functions inherited from GrowVector< DocNodeVariant >
iterator begin ()
returns an iterator to the beginning
const_iterator begin () const
returns an iterator to the beginning
iterator end ()
returns an iterator to the end
const_iterator end () const
returns an iterator to the end
size_t size () const
returns the number of elements
void push_back (DocNodeVariant &&t)
adds an element to the end
void emplace_back (Args &&...args)
constructs an element in-place at the end
void pop_back ()
removes the last element
DocNodeVariant & at (size_t i)
access specified element
const DocNodeVariant & at (size_t i) const
access specified element
DocNodeVariant & front ()
access the first element
const DocNodeVariant & front () const
access the first element
DocNodeVariant & back ()
access the last element
const DocNodeVariant & back () const
access the last element
bool empty () const
checks whether the container is empty
void clear ()
clears the contents
Additional Inherited Members
Public Types inherited from GrowVector< DocNodeVariant >
using iterator = Iterator< GrowVector, DocNodeVariant >
using const_iterator = Iterator< const GrowVector, const DocNodeVariant >
Detailed Description
Definition at line 119 of file docnode.h.
Member Function Documentation
append()
template<class T , class... Args> void DocNodeList::append (Args &&... args) inline
Append a new DocNodeVariant to the list by constructing it with type T and parameters Args.
Definition at line 1335 of file docnode.h.
{
  // add a DocNodeVariant to the list containing an node T as its active member.
  emplace_back(T(std::forward<Args>(args)...));
  // store a pointer to the variant holding node T inside the node itself.
  // Since DocNodeList is a GrowVector this reference will remain valid even if new
  // elements are added (which would not be the case if a std::vector was used)
  std::get_if<T>(&back())->setThisVariant(&back());
}
References GrowVector< DocNodeVariant >::back(), and GrowVector< DocNodeVariant >::emplace_back().
Referenced by DocSimpleSect::appendLinkWord(), DocParser::defaultHandleToken(), DocParser::errorHandleDefaultToken(), DocParser::handleAHref(), DocParser::handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleDoxyConfig(), DocPara::handleEmoji(), DocPara::handleFile(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlHeader(), DocPara::handleHtmlStartTag(), DocParser::handleImage(), DocParser::handleImg(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocParser::handleInternalRef(), DocPara::handleLink(), DocParser::handleLinkedWord(), DocParser::handleParameterType(), DocPara::handleParamSection(), DocParser::handlePendingStyleCommands(), DocPara::handleRef(), DocPara::handleShowDate(), DocPara::handleSimpleSection(), DocPara::handleStartCode(), DocParser::handleStyleEnter(), DocParser::handleStyleLeave(), DocPara::handleVhdlFlow(), DocPara::handleXRefItem(), DocParser::internalValidatingParseDoc(), DocAutoList::parse(), DocAutoListItem::parse(), DocHRef::parse(), DocHtmlDetails::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefList::parse(), DocParBlock::parse(), DocSimpleList::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlListItem::parse(), DocHtmlDescData::parse(), DocHtmlCell::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocHtmlBlockQuote::parse(), DocText::parse(), DocRoot::parse(), DocSimpleSect::parse(), DocLink::parse(), DocParamList::parse(), DocParamSect::parse(), DocInternal::parse(), DocTitle::parseFromString(), DocHtmlList::parseXml(), DocSimpleSect::parseXml(), DocHtmlListItem::parseXml(), DocHtmlCell::parseXml(), DocHtmlTable::parseXml(), DocHtmlRow::parseXml(), and DocParamList::parseXml().
get_last()
template<class T > T * DocNodeList::get_last inline
Returns a pointer to the last element in the list if that element exists and holds a T, otherwise nullptr is returned.
Definition at line 1355 of file docnode.h.
{
  return std::get_if<T>(&back());
}
References GrowVector< DocNodeVariant >::back().
Referenced by DocSimpleSect::appendLinkWord(), DocParser::handleAHref(), DocPara::handleCommand(), DocPara::handleFile(), DocPara::handleHtmlHeader(), DocPara::handleHtmlStartTag(), DocParser::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocParser::handleInternalRef(), DocPara::handleLink(), DocPara::handleParamSection(), DocPara::handleRef(), DocPara::handleSimpleSection(), DocPara::handleVhdlFlow(), DocPara::handleXRefItem(), DocParser::internalValidatingParseDoc(), DocAutoList::parse(), DocAutoListItem::parse(), DocHtmlDetails::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefList::parse(), DocParBlock::parse(), DocSimpleList::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlListItem::parse(), DocHtmlDescData::parse(), DocHtmlCell::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocHtmlBlockQuote::parse(), DocRoot::parse(), DocSimpleSect::parse(), DocParamList::parse(), DocParamSect::parse(), DocInternal::parse(), DocHtmlList::parseXml(), DocSimpleSect::parseXml(), DocHtmlListItem::parseXml(), DocHtmlCell::parseXml(), DocHtmlTable::parseXml(), DocHtmlRow::parseXml(), and DocParamList::parseXml().
move_append()
void DocNodeList::move_append (DocNodeList & l) inline
moves the element of list l at the end of this list.
List l will become empty.
Definition at line 1345 of file docnode.h.
{
  for (auto &&elem : elements)
  {
    emplace_back(std::move(elem));
  }
  elements.clear();
}
References GrowVector< T >::clear(), and GrowVector< DocNodeVariant >::emplace_back().
Referenced by flattenParagraphs().
The documentation for this struct was generated from the following file:
/home/runner/work/doxygen/doxygen/src/docnode.h