Doxygen: src/latexdocvisitor.cpp File Reference
latexdocvisitor.cpp File Reference
#include <algorithm>
#include <array>
#include "htmlattrib.h"
#include "latexdocvisitor.h"
#include "latexgen.h"
#include "docparser.h"
#include "language.h"
#include "doxygen.h"
#include "outputgen.h"
#include "outputlist.h"
#include "dot.h"
#include "util.h"
#include "message.h"
#include "parserintf.h"
#include "msc.h"
#include "dia.h"
#include "cite.h"
#include "filedef.h"
#include "config.h"
#include "htmlentity.h"
#include "emoji.h"
#include "plantuml.h"
#include "fileinfo.h"
#include "regex.h"
#include "portable.h"
#include "codefragment.h"
Functions
static void insertDimension (TextStream &t, QCString dimension, const char *orientationString)
static void visitPreStart (TextStream &t, bool hasCaption, QCString name, QCString width, QCString height, bool inlineImage=FALSE)
static void visitPostEnd (TextStream &t, bool hasCaption, bool inlineImage=FALSE)
static QCString makeShortName (const QCString &name)
static QCString makeBaseName (const QCString &name)
static bool classEqualsReflist (const DocHtmlDescList &dl)
static bool listIsNested (const DocHtmlDescList &dl)
static bool tableIsNested (const DocNodeVariant *n)
static void writeStartTableCommand (TextStream &t, const DocNodeVariant *n, size_t cols)
static void writeEndTableCommand (TextStream &t, const DocNodeVariant *n)
Variables
static const int g_maxLevels = 7
static const std::array< const char *, g_maxLevels > g_secLabels
static const char * g_paragraphLabel = "doxyparagraph"
static const char * g_subparagraphLabel = "doxysubparagraph"
Function Documentation
classEqualsReflist()
static bool classEqualsReflist (const DocHtmlDescList & dl) static
Definition at line 1121 of file latexdocvisitor.cpp.
{
  HtmlAttribList attrs = dl.attribs();
  auto it = std::find_if(attrs.begin(),attrs.end(),
                      [](const auto &att) { return att.name=="class"; });
  if (it!=attrs.end() && it->value == "reflist") return true;
  return false;
}
References DocHtmlDescList::attribs().
Referenced by listIsNested(), and LatexDocVisitor::operator()().
insertDimension()
static void insertDimension (TextStream & t, QCString dimension, const char * orientationString) static
Definition at line 89 of file latexdocvisitor.cpp.
{
  // dimensions for latex images can be a percentage, in this case they need some extra
  // handling as the % symbol is used for comments
  static const reg::Ex re(R"((\d+)%)");
  std::string s = dimension.str();
  reg::Match match;
  if (reg::search(s,match,re))
  {
    bool ok = false;
    double percent = QCString(match[1].str()).toInt(&ok);
    if (ok)
    {
      t << percent/100.0 << "\\text" << orientationString;
      return;
    }
  }
  t << dimension;
}
References reg::search(), QCString::str(), and QCString::toInt().
Referenced by visitPreStart().
listIsNested()
static bool listIsNested (const DocHtmlDescList & dl) static
Definition at line 1130 of file latexdocvisitor.cpp.
{
  bool isNested=false;
  const DocNodeVariant *n = dl.parent();
  while (n && !isNested)
  {
    if (std::get_if<DocHtmlDescList>(n))
    {
      isNested = !classEqualsReflist(std::get<DocHtmlDescList>(*n));
    }
    n = ::parent(n);
  }
  return isNested;
}
References classEqualsReflist(), DocNode::parent(), and parent().
Referenced by LatexDocVisitor::operator()().
makeBaseName()
static QCString makeBaseName (const QCString & name) static
Definition at line 219 of file latexdocvisitor.cpp.
{
  QCString baseName = makeShortName(name);
  int i=baseName.find('.');
  if (i!=-1)
  {
    baseName=baseName.left(i);
  }
  return baseName;
}
References QCString::find(), QCString::left(), and makeShortName().
makeShortName()
static QCString makeShortName (const QCString & name) static
Definition at line 208 of file latexdocvisitor.cpp.
{
  QCString shortName = name;
  int i = shortName.findRev('/');
  if (i!=-1)
  {
    shortName=shortName.mid(i+1);
  }
  return shortName;
}
References QCString::findRev(), and QCString::mid().
Referenced by makeBaseName().
tableIsNested()
static bool tableIsNested (const DocNodeVariant * n) static
Definition at line 1188 of file latexdocvisitor.cpp.
{
  bool isNested=FALSE;
  while (n && !isNested)
  {
    isNested = holds_one_of_alternatives<DocHtmlTable,DocParamSect>(*n);
    n = ::parent(n);
  }
  return isNested;
}
References FALSE, holds_one_of_alternatives(), and parent().
Referenced by LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), writeEndTableCommand(), and writeStartTableCommand().
visitPostEnd()
static void visitPostEnd (TextStream & t, bool hasCaption, bool inlineImage = FALSE) static
Definition at line 188 of file latexdocvisitor.cpp.
{
    if (inlineImage)
    {
      t << "\n\\end{DoxyInlineImage}\n";
    }
    else
    {
      t << "}\n"; // end mbox or caption
      if (hasCaption)
      {
        t << "\\end{DoxyImage}\n";
      }
      else
      {
        t << "\\end{DoxyImageNoCaption}\n";
      }
    }
}
References FALSE.
Referenced by LatexDocVisitor::endDiaFile(), LatexDocVisitor::endDotFile(), LatexDocVisitor::endMscFile(), LatexDocVisitor::endPlantUmlFile(), LatexDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::writeDiaFile(), LatexDocVisitor::writeMscFile(), and LatexDocVisitor::writePlantUMLFile().
visitPreStart()
static void visitPreStart (TextStream & t, bool hasCaption, QCString name, QCString width, QCString height, bool inlineImage = FALSE) static
Definition at line 109 of file latexdocvisitor.cpp.
{
    if (inlineImage)
    {
      t << "\n\\begin{DoxyInlineImage}\n";
    }
    else
    {
      if (hasCaption)
      {
        t << "\n\\begin{DoxyImage}\n";
      }
      else
      {
        t << "\n\\begin{DoxyImageNoCaption}\n"
               "  \\mbox{";
      }
    }
    t << "\\includegraphics";
    if (!width.isEmpty() || !height.isEmpty())
    {
      t << "[";
    }
    if (!width.isEmpty())
    {
      t << "width=";
      insertDimension(t, width, "width");
    }
    if (!width.isEmpty() && !height.isEmpty())
    {
      t << ",";
    }
    if (!height.isEmpty())
    {
      t << "height=";
      insertDimension(t, height, "height");
    }
    if (width.isEmpty() && height.isEmpty())
    {
      /* default setting */
      if (inlineImage)
      {
        t << "[height=\\baselineskip,keepaspectratio=true]";
      }
      else
      {
        t << "[width=\\textwidth,height=\\textheight/2,keepaspectratio=true]";
      }
    }
    else
    {
      t << "]";
    }
    t << "{" << name << "}";
    if (hasCaption)
    {
      if (!inlineImage)
      {
        if (Config_getBool(PDF_HYPERLINKS))
        {
          t << "\n\\doxyfigcaption{";
        }
        else
        {
          t << "\n\\doxyfigcaptionnolink{";
        }
      }
      else
      {
        t << "%"; // to catch the caption
      }
    }
}
References Config_getBool, FALSE, insertDimension(), and QCString::isEmpty().
Referenced by LatexDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::startDiaFile(), LatexDocVisitor::startDotFile(), LatexDocVisitor::startMscFile(), LatexDocVisitor::startPlantUmlFile(), LatexDocVisitor::writeDiaFile(), LatexDocVisitor::writeMscFile(), and LatexDocVisitor::writePlantUMLFile().
writeEndTableCommand()
static void writeEndTableCommand (TextStream & t, const DocNodeVariant * n) static
Definition at line 1212 of file latexdocvisitor.cpp.
{
  if (tableIsNested(n))
  {
    t << "\\end{tabularx}}\n";
  }
  else
  {
    t << "\\end{longtabu}\n";
  }
  //return isNested ? "TabularNC" : "TabularC";
}
References tableIsNested().
Referenced by LatexDocVisitor::operator()().
writeStartTableCommand()
static void writeStartTableCommand (TextStream & t, const DocNodeVariant * n, size_t cols) static
Definition at line 1199 of file latexdocvisitor.cpp.
{
  if (tableIsNested(n))
  {
    t << "{\\begin{tabularx}{\\linewidth}{|*{" << cols << "}{>{\\raggedright\\arraybackslash}X|}}";
  }
  else
  {
    t << "\\tabulinesep=1mm\n\\begin{longtabu}spread 0pt [c]{*{" << cols << "}{|X[-1]}|}\n";
  }
  //return isNested ? "TabularNC" : "TabularC";
}
References tableIsNested().
Referenced by LatexDocVisitor::operator()().
Variable Documentation
g_maxLevels
const int g_maxLevels = 7 static
Definition at line 44 of file latexdocvisitor.cpp.
Referenced by LatexDocVisitor::getSectionName().
g_paragraphLabel
const char* g_paragraphLabel = "doxyparagraph" static
Definition at line 55 of file latexdocvisitor.cpp.
Referenced by LatexDocVisitor::getSectionName().
g_secLabels
const std::array<const char *,g_maxLevels> g_secLabels static
Initial value:
=
{ "doxysection",
  "doxysubsection",
  "doxysubsubsection",
  "doxysubsubsubsection",
  "doxysubsubsubsubsection",
  "doxysubsubsubsubsubsection",
  "doxysubsubsubsubsubsubsection"
}
Definition at line 45 of file latexdocvisitor.cpp.
{ "doxysection",
  "doxysubsection",
  "doxysubsubsection",
  "doxysubsubsubsection",
  "doxysubsubsubsubsection",
  "doxysubsubsubsubsubsection",
  "doxysubsubsubsubsubsubsection"
};
Referenced by LatexDocVisitor::getSectionName().
g_subparagraphLabel
const char* g_subparagraphLabel = "doxysubparagraph" static
Definition at line 56 of file latexdocvisitor.cpp.
Referenced by LatexDocVisitor::getSectionName().