Doxygen: EdgeInfo Class Reference
EdgeInfo Class Reference
Attributes of an edge of a dot graph.
#include <src/dotnode.h>
Public Types
enum Colors {
Blue =0 , Green =1 , Red =2 , Purple =3 ,
Grey =4 , Orange =5 , Orange2 =6
}
enum Styles { Solid =0 , Dashed =1 }
Public Member Functions
EdgeInfo (Colors color, Styles style, const QCString &lab, const QCString &url, int labColor)
int color () const
int style () const
QCString label () const
QCString url () const
int labelColor () const
Static Public Member Functions
static constexpr Colors protectionToColor (Protection prot)
Private Attributes
int m_color
int m_style
QCString m_label
QCString m_url
int m_labColor
Detailed Description
Attributes of an edge of a dot graph.
Definition at line 32 of file dotnode.h.
Member Enumeration Documentation
Colors
enum EdgeInfo::Colors
Enumerator
Blue
Green
Red
Purple
Grey
Orange
Orange2
Definition at line 35 of file dotnode.h.
{ Blue=0, Green=1, Red=2, Purple=3, Grey=4, Orange=5, Orange2=6 };
Styles
enum EdgeInfo::Styles
Enumerator
Solid
Dashed
Definition at line 36 of file dotnode.h.
{ Solid=0, Dashed=1 };
Constructor & Destructor Documentation
EdgeInfo()
EdgeInfo::EdgeInfo (Colors color, Styles style, const QCString & lab, const QCString & url, int labColor) inline
Definition at line 37 of file dotnode.h.
        : m_color(color), m_style(style), m_label(lab), m_url(url), m_labColor(labColor) {}
References color(), m_color, m_labColor, m_label, m_style, m_url, style(), and url().
Member Function Documentation
color()
int EdgeInfo::color () const inline
Definition at line 39 of file dotnode.h.
{ return m_color; }
References m_color.
Referenced by EdgeInfo(), and DotNode::writeArrow().
label()
QCString EdgeInfo::label () const inline
Definition at line 41 of file dotnode.h.
{ return m_label; }
References m_label.
Referenced by DotNode::writeArrow().
labelColor()
int EdgeInfo::labelColor () const inline
Definition at line 43 of file dotnode.h.
{ return m_labColor; }
References m_labColor.
protectionToColor()
static constexpr Colors EdgeInfo::protectionToColor (Protection prot) inline static constexpr
Definition at line 44 of file dotnode.h.
    {
      switch (prot)
      {
        case Protection::Public:    return Blue;
        case Protection::Protected: return Green;
        case Protection::Private:   return Red;
        case Protection::Package:   return Purple;
      }
      return Blue;
    }
References Blue, Green, Package, Private, Protected, Public, Purple, and Red.
Referenced by DotGfxHierarchyTable::addHierarchy(), and DotClassGraph::buildGraph().
style()
int EdgeInfo::style () const inline
Definition at line 40 of file dotnode.h.
{ return m_style; }
References m_style.
Referenced by EdgeInfo(), and DotNode::writeArrow().
url()
QCString EdgeInfo::url () const inline
Definition at line 42 of file dotnode.h.
{ return m_url; }
References m_url.
Referenced by EdgeInfo().
Member Data Documentation
m_color
int EdgeInfo::m_color private
Definition at line 56 of file dotnode.h.
Referenced by color(), and EdgeInfo().
m_labColor
int EdgeInfo::m_labColor private
Definition at line 60 of file dotnode.h.
Referenced by EdgeInfo(), and labelColor().
m_label
QCString EdgeInfo::m_label private
Definition at line 58 of file dotnode.h.
Referenced by EdgeInfo(), and label().
m_style
int EdgeInfo::m_style private
Definition at line 57 of file dotnode.h.
Referenced by EdgeInfo(), and style().
m_url
QCString EdgeInfo::m_url private
Definition at line 59 of file dotnode.h.
Referenced by EdgeInfo(), and url().
The documentation for this class was generated from the following file:
src/dotnode.h