Doxygen: src/moduledef.cpp File Reference
moduledef.cpp File Reference
#include "moduledef.h"
#include "definitionimpl.h"
#include "entry.h"
#include "memberdef.h"
#include "classlist.h"
#include "namespacedef.h"
#include "conceptdef.h"
#include "config.h"
#include "outputlist.h"
#include "language.h"
#include "util.h"
#include "groupdef.h"
#include "message.h"
#include "membergroup.h"
#include "classdef.h"
#include "textstream.h"
#include "trace.h"
Classes
struct HeaderInfo
class ModuleDefImpl
struct ModuleManager::Private
Typedefs
using HeaderInfoVector = std::vector<HeaderInfo>
Functions
ModuleDef * toModuleDef (Definition *d)
const ModuleDef * toModuleDef (const Definition *d)
static ModuleDefImpl * toModuleDefImpl (ModuleDef *m)
static ModuleDefImpl * toModuleDefImpl (const std::unique_ptr< ModuleDef > &m)
Typedef Documentation
HeaderInfoVector
using HeaderInfoVector = std::vector<HeaderInfo>
Definition at line 45 of file moduledef.cpp.
Function Documentation
toModuleDef() [1/2]
const ModuleDef * toModuleDef (const Definition * d)
Definition at line 1125 of file moduledef.cpp.
{
  if (d==nullptr) return nullptr;
  return (typeid(*d)==typeid(ModuleDefImpl)) ? static_cast<const ModuleDef*>(d) : nullptr;
}
toModuleDef() [2/2]
ModuleDef * toModuleDef (Definition * d)
Definition at line 1119 of file moduledef.cpp.
{
  if (d==nullptr) return nullptr;
  return (typeid(*d)==typeid(ModuleDefImpl)) ? static_cast<ModuleDef*>(d) : nullptr;
}
Referenced by ClassDefImpl::moveTo(), and MemberDefImpl::moveTo().
toModuleDefImpl() [1/2]
static ModuleDefImpl * toModuleDefImpl (const std::unique_ptr< ModuleDef > & m) inline static
Definition at line 1137 of file moduledef.cpp.
{ return static_cast<ModuleDefImpl*>(m.get()); }
toModuleDefImpl() [2/2]
static ModuleDefImpl * toModuleDefImpl (ModuleDef * m) inline static
Definition at line 1131 of file moduledef.cpp.
{ return static_cast<ModuleDefImpl*>(m); }
Referenced by ModuleManager::addClassToModule(), ModuleManager::addConceptToModule(), ModuleManager::addHeader(), ModuleManager::addImport(), ModuleManager::addListReferences(), ModuleManager::addMembersToMemberGroup(), ModuleManager::addMemberToModule(), ModuleManager::addTagInfo(), ModuleManager::collectExportedSymbols(), ModuleManager::collectExportedSymbolsRecursively(), ModuleManager::countMembers(), ModuleManager::distributeMemberGroupDocumentation(), ModuleManager::findSectionsInDocumentation(), ModuleManager::resolvePartitions(), ModuleManager::resolvePartitionsRecursively(), ModuleManager::sortMemberLists(), and ModuleLinkedRefMap::writeDeclaration().