Doxygen: SysTimeKeeper Class Reference
SysTimeKeeper Class Reference
Classes
struct TimeData
Public Member Functions
void start ()
start a timer for this thread
void stop ()
ends a timer for this thread, accumulate time difference since start
double elapsedTime () const
Static Public Member Functions
static SysTimeKeeper & instance ()
Private Attributes
std::map< std::thread::id, std::chrono::steady_clock::time_point > m_startTimes
double m_elapsedTime = 0
std::mutex m_mutex
Detailed Description
Helper class to keep time interval per thread
Definition at line 46 of file portable.cpp.
Member Function Documentation
elapsedTime()
double SysTimeKeeper::elapsedTime () const inline
Definition at line 73 of file portable.cpp.
{ return m_elapsedTime; }
References m_elapsedTime.
Referenced by Portable::getSysElapsedTime().
instance()
SysTimeKeeper & SysTimeKeeper::instance () static
Definition at line 85 of file portable.cpp.
{
  static SysTimeKeeper theInstance;
  return theInstance;
}
Referenced by AutoTimeKeeper::AutoTimeKeeper(), Portable::getSysElapsedTime(), and AutoTimeKeeper::~AutoTimeKeeper().
start()
void SysTimeKeeper::start () inline
start a timer for this thread
Definition at line 51 of file portable.cpp.
    {
      std::lock_guard<std::mutex> lock(m_mutex);
      m_startTimes[std::this_thread::get_id()] = std::chrono::steady_clock::now();
    }
References m_mutex, and m_startTimes.
Referenced by AutoTimeKeeper::AutoTimeKeeper().
stop()
void SysTimeKeeper::stop () inline
ends a timer for this thread, accumulate time difference since start
Definition at line 57 of file portable.cpp.
    {
      std::lock_guard<std::mutex> lock(m_mutex);
      std::chrono::steady_clock::time_point endTime = std::chrono::steady_clock::now();
      auto it = m_startTimes.find(std::this_thread::get_id());
      if (it == m_startTimes.end())
      {
        err("SysTimeKeeper stop() called without matching start()\n");
        return;
      }
      double timeSpent = static_cast<double>(std::chrono::duration_cast<
                         std::chrono::microseconds>(endTime - it->second).count())/1000000.0;
      //printf("timeSpent on thread %zu: %.4f seconds\n",std::hash<std::thread::id>{}(std::this_thread::get_id()),timeSpent);
      m_elapsedTime += timeSpent;
    }
References err, m_elapsedTime, m_mutex, and m_startTimes.
Referenced by AutoTimeKeeper::~AutoTimeKeeper().
Member Data Documentation
m_elapsedTime
double SysTimeKeeper::m_elapsedTime = 0 private
Definition at line 81 of file portable.cpp.
Referenced by elapsedTime(), and stop().
m_mutex
std::mutex SysTimeKeeper::m_mutex private
Definition at line 82 of file portable.cpp.
Referenced by start(), and stop().
m_startTimes
std::map<std::thread::id,std::chrono::steady_clock::time_point> SysTimeKeeper::m_startTimes private
Definition at line 80 of file portable.cpp.
Referenced by start(), and stop().
The documentation for this class was generated from the following file:
src/portable.cpp