Doxygen: src/mangen.cpp File Reference
mangen.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include "message.h"
#include "mangen.h"
#include "config.h"
#include "util.h"
#include "doxygen.h"
#include "docparser.h"
#include "mandocvisitor.h"
#include "language.h"
#include "dir.h"
#include "utf8.h"
#include "datetime.h"
#include "portable.h"
#include "outputlist.h"
Functions
static QCString getExtension ()
static QCString getSubdir ()
static QCString docifyToString (const QCString &str)
static QCString objectLinkToString (const QCString &text)
static QCString buildFileName (const QCString &name)
Function Documentation
buildFileName()
static QCString buildFileName (const QCString & name) static
Definition at line 296 of file mangen.cpp.
{
  QCString fileName;
  if (name.isEmpty()) return "noname";
  const char *p=name.data();
  char c = 0;
  while ((c=*p++))
  {
    switch (c)
    {
      case ':':
        fileName+="_";
        if (*p==':') p++;
        break;
      case '<':
      case '>':
      case '&':
      case '*':
      case '!':
      case '^':
      case '~':
      case '%':
      case '+':
      case '/':
        fileName+="_";
        break;
      default:
        fileName+=c;
    }
  }
  QCString manExtension = "." + getExtension();
  if (fileName.right(manExtension.length())!=manExtension)
  {
    fileName+=manExtension;
  }
  return fileName;
}
References QCString::data(), getExtension(), QCString::isEmpty(), QCString::length(), and QCString::right().
Referenced by ManGenerator::startDoxyAnchor(), and ManGenerator::startFile().
docifyToString()
static QCString docifyToString (const QCString & str) static
Definition at line 79 of file mangen.cpp.
{
  QCString result;
  result.reserve(str.length());
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c=0;
    while ((c=*p++))
    {
      switch(c)
      {
        case '-':  result += "\\-";  break; // see  bug747780
        case '.':  result += "\\&."; break; // see  bug652277
        case '\\': result += "\\\\"; break;
        case '\n': result += "\n";   break;
        case '\"': c = '\'';   // no break!
        default:   result += c;      break;
      }
    }
    //printf("%s",str);fflush(stdout);
  }
  return result;
}
References QCString::data(), QCString::isEmpty(), QCString::length(), and QCString::reserve().
Referenced by RTFGenerator::docify(), objectLinkToString(), ManGenerator::writeInheritedSectionTitle(), and RTFGenerator::writeInheritedSectionTitle().
getExtension()
static QCString getExtension () static
Definition at line 36 of file mangen.cpp.
{
  /*
   * [.][number][rest]
   * in case of . missing, just ignore it
   * in case number missing, just place a 3 in front of it
   */
  QCString ext = Config_getString(MAN_EXTENSION);
  if (ext.isEmpty())
  {
    ext = "3";
  }
  else
  {
    if (ext.at(0)=='.')
    {
      if (ext.length()==1)
      {
        ext = "3";
      }
      else // strip .
      {
        ext = ext.mid(1);
      }
    }
    if (ext.at(0)<'0' || ext.at(0)>'9')
    {
      ext.prepend("3");
    }
  }
  return ext;
}
References QCString::at(), Config_getString, QCString::isEmpty(), QCString::length(), QCString::mid(), and QCString::prepend().
Referenced by buildFileName(), ManGenerator::endTitleHead(), and getSubdir().
getSubdir()
static QCString getSubdir () static
Definition at line 69 of file mangen.cpp.
{
  QCString dir = Config_getString(MAN_SUBDIR);
  if (dir.isEmpty())
  {
    dir = "man" + getExtension();
  }
  return dir;
}
References Config_getString, getExtension(), and QCString::isEmpty().
Referenced by ManGenerator::init(), ManGenerator::ManGenerator(), and ManGenerator::startDoxyAnchor().
objectLinkToString()
static QCString objectLinkToString (const QCString & text) static
Definition at line 104 of file mangen.cpp.
{
  return "\\fB" + docifyToString(text) + "\\fP";
}
References docifyToString().