Doxygen: src/sitemap.cpp File Reference
sitemap.cpp File Reference
#include <algorithm>
#include <memory>
#include <string.h>
#include <vector>
#include <cassert>
#include "config.h"
#include "debug.h"
#include "doxygen.h"
#include "groupdef.h"
#include "memberdef.h"
#include "message.h"
#include "sitemap.h"
#include "textstream.h"
#include "util.h"
#include "portable.h"
#include "language.h"
#include "version.h"
#include "containers.h"
Classes
class Sitemap::Private
class Crawlmap::Private
Functions
static QCString makeFileName (const QCString &withoutExtension)
static QCString makeRef (const QCString &withoutExtension, const QCString &anchor)
Function Documentation
makeFileName()
static QCString makeFileName (const QCString & withoutExtension) static
Definition at line 170 of file sitemap.cpp.
{
  QCString result=withoutExtension;
  if (!result.isEmpty())
  {
    if (result.at(0)=='!') // relative URL -> strip marker
    {
      result=result.mid(1);
    }
    else // add specified HTML extension
    {
      addHtmlExtensionIfMissing(result);
    }
  }
  return result;
}
References addHtmlExtensionIfMissing(), QCString::at(), QCString::isEmpty(), and QCString::mid().
Referenced by makeRef().
makeRef()
static QCString makeRef (const QCString & withoutExtension, const QCString & anchor) static
Definition at line 187 of file sitemap.cpp.
{
  if (withoutExtension.isEmpty()) return QCString();
  QCString result = makeFileName(withoutExtension);
  if (anchor.isEmpty()) return result;
  return result+"#"+anchor;
}
References QCString::isEmpty(), and makeFileName().