Doxygen: MemberDefAliasImpl Class Reference
MemberDefAliasImpl Class Reference
Public Member Functions
MemberDefAliasImpl (const Definition *newScope, const MemberDef *md)
~MemberDefAliasImpl () override
DefType definitionType () const override
const MemberDef * getMdAlias () const
MemberDef * getMdAlias ()
MemberDef * resolveAlias () override
const MemberDef * resolveAlias () const override
std::unique_ptr< MemberDef > deepCopy () const override
void moveTo (Definition *) override
const QCString & name () const override
CodeSymbolType codeSymbolType () const override
QCString getOutputFileBase () const override
QCString getReference () const override
QCString anchor () const override
QCString declaration () const override
QCString definition () const override
QCString typeString () const override
QCString argsString () const override
QCString excpString () const override
QCString bitfieldString () const override
QCString extraTypeChars () const override
const QCString & initializer () const override
int initializerLines () const override
TypeSpecifier getMemberSpecifiers () const override
VhdlSpecifier getVhdlSpecifiers () const override
const MemberList * getSectionList (const Definition *container) const override
QCString displayDefinition () const override
const ClassDef * getClassDef () const override
ClassDef * getClassDef () override
const FileDef * getFileDef () const override
FileDef * getFileDef () override
const ModuleDef * getModuleDef () const override
const NamespaceDef * getNamespaceDef () const override
NamespaceDef * getNamespaceDef () override
const ClassDef * accessorClass () const override
QCString getReadAccessor () const override
QCString getWriteAccessor () const override
const GroupDef * getGroupDef () const override
GroupDef * getGroupDef () override
Grouping::GroupPri_t getGroupPri () const override
QCString getGroupFileName () const override
int getGroupStartLine () const override
bool getGroupHasDocs () const override
QCString qualifiedName () const override
QCString objCMethodName (bool localLink, bool showStatic) const override
Protection protection () const override
Specifier virtualness (int) const override
MemberType memberType () const override
QCString memberTypeName () const override
bool isSignal () const override
bool isSlot () const override
bool isVariable () const override
bool isEnumerate () const override
bool isEnumValue () const override
bool isTypedef () const override
bool isSequence () const override
bool isDictionary () const override
bool isFunction () const override
bool isFunctionPtr () const override
bool isDefine () const override
bool isFriend () const override
bool isDCOP () const override
bool isProperty () const override
bool isEvent () const override
bool isRelated () const override
bool isForeign () const override
bool isStatic () const override
bool isInline () const override
bool isExplicit () const override
bool isMutable () const override
bool isGettable () const override
bool isPrivateGettable () const override
bool isProtectedGettable () const override
bool isSettable () const override
bool isPrivateSettable () const override
bool isProtectedSettable () const override
bool isReadable () const override
bool isWritable () const override
bool isAddable () const override
bool isRemovable () const override
bool isRaisable () const override
bool isFinal () const override
bool isAbstract () const override
bool isOverride () const override
bool isInitonly () const override
bool isOptional () const override
bool isRequired () const override
bool isNonAtomic () const override
bool isCopy () const override
bool isAssign () const override
bool isRetain () const override
bool isWeak () const override
bool isStrong () const override
bool isEnumStruct () const override
bool isUnretained () const override
bool isNew () const override
bool isSealed () const override
bool isImplementation () const override
bool isExternal () const override
bool isTypeAlias () const override
bool isDefault () const override
bool isDelete () const override
bool isNoExcept () const override
bool isAttribute () const override
bool isUNOProperty () const override
bool isReadonly () const override
bool isBound () const override
bool isConstrained () const override
bool isTransient () const override
bool isMaybeVoid () const override
bool isMaybeDefault () const override
bool isMaybeAmbiguous () const override
bool isPublished () const override
bool isTemplateSpecialization () const override
bool isObjCMethod () const override
bool isObjCProperty () const override
bool isCSharpProperty () const override
bool isConstructor () const override
bool isDestructor () const override
bool hasOneLineInitializer () const override
bool hasMultiLineInitializer () const override
bool isCallable () const override
bool isStrongEnumValue () const override
bool livesInsideEnum () const override
bool isSliceLocal () const override
bool isNoDiscard () const override
bool isConstExpr () const override
bool isConstEval () const override
bool isConstInit () const override
int numberOfFlowKeyWords () const override
bool isFriendToHide () const override
bool isNotFriend () const override
bool isFunctionOrSignalSlot () const override
bool isRelatedOrFriend () const override
bool isLinkableInProject () const override
bool isLinkable () const override
bool hasDocumentation () const override
bool hasUserDocumentation () const override
bool isDeleted () const override
bool isBriefSectionVisible () const override
bool isDetailedSectionVisible (MemberListContainer container) const override
bool hasDetailedDescription () const override
bool isFriendClass () const override
bool isDocumentedFriendClass () const override
const MemberDef * reimplements () const override
const MemberVector & reimplementedBy () const override
bool isReimplementedBy (const ClassDef *cd) const override
ClassDef * relatedAlso () const override
bool hasDocumentedEnumValues () const override
const MemberDef * getAnonymousEnumType () const override
bool isDocsForDefinition () const override
const MemberDef * getEnumScope () const override
const MemberVector & enumFieldList () const override
QCString enumBaseType () const override
bool hasExamples () const override
const ExampleList & getExamples () const override
bool isPrototype () const override
const ArgumentList & argumentList () const override
const ArgumentList & declArgumentList () const override
const ArgumentList & templateArguments () const override
const ArgumentLists & definitionTemplateParameterLists () const override
std::optional< ArgumentList > formalTemplateArguments () const override
int getMemberGroupId () const override
MemberGroup * getMemberGroup () const override
bool fromAnonymousScope () const override
MemberDef * fromAnonymousMember () const override
bool hasCallGraph () const override
bool hasCallerGraph () const override
bool hasReferencesRelation () const override
bool hasReferencedByRelation () const override
bool hasInlineSource () const override
QCString sourceRefName () const override
bool hasEnumValues () const override
StringVector getQualifiers () const override
const MemberDef * templateMaster () const override
QCString getScopeString () const override
ClassDef * getClassDefOfAnonymousType () const override
bool isTypedefValCached () const override
const ClassDef * getCachedTypedefVal () const override
QCString getCachedTypedefTemplSpec () const override
QCString getCachedResolvedTypedef () const override
MemberDef * memberDefinition () const override
MemberDef * memberDeclaration () const override
const MemberDef * inheritsDocsFrom () const override
const MemberDef * getGroupAlias () const override
ClassDef * category () const override
const MemberDef * categoryRelation () const override
QCString displayName (bool b=TRUE) const override
QCString getDeclType () const override
StringVector getLabels (const Definition *container) const override
const ArgumentList & typeConstraints () const override
QCString documentation () const override
QCString briefDescription (bool) const override
QCString fieldType () const override
bool isReference () const override
QCString getDeclFileName () const override
int getDeclLine () const override
int getDeclColumn () const override
QCString requiresClause () const override
bool visibleInIndex () const override
void warnIfUndocumented () const override
void warnIfUndocumentedParams () const override
void detectUndocumentedParams (bool, bool) const override
void setMemberGroup (MemberGroup *grp) override
std::unique_ptr< MemberDef > createTemplateInstanceMember (const ArgumentList &formalArgs, const std::unique_ptr< ArgumentList > &actualArgs) const override
void writeDeclaration (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, const ModuleDef *mod, bool inGroup, int indentLevel, const ClassDef *inheritFrom=nullptr, const QCString &inheritId=QCString()) const override
void writeEnumDeclaration (OutputList &typeDecl, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, const ModuleDef *mod) const override
void writeLink (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, const ModuleDef *mod, bool onlyText=FALSE) const override
Public Member Functions inherited from DefinitionAliasMixin< MemberDef >
DefinitionAliasMixin (const Definition *scope, const Definition *alias)
~DefinitionAliasMixin () override=default
void init ()
void deinit ()
bool isAlias () const override
bool isAnonymous () const override
const QCString & localName () const override
QCString symbolName () const override
QCString getSourceFileBase () const override
QCString getSourceAnchor () const override
int docLine () const override
QCString docFile () const override
QCString briefDescriptionAsTooltip () const override
int briefLine () const override
QCString inbodyDocumentation () const override
QCString inbodyFile () const override
int inbodyLine () const override
QCString briefFile () const override
QCString getDefFileName () const override
QCString getDefFileExtension () const override
int getDefLine () const override
int getDefColumn () const override
bool isVisibleInProject () const override
bool isVisible () const override
bool isHidden () const override
bool isArtificial () const override
bool isExported () const override
QCString externalReference (const QCString &relPath) const override
int getStartDefLine () const override
int getStartBodyLine () const override
int getEndBodyLine () const override
const FileDef * getBodyDef () const override
SrcLangExt getLanguage () const override
const GroupList & partOfGroups () const override
bool isLinkableViaGroup () const override
const RefItemVector & xrefListItems () const override
const Definition * findInnerCompound (const QCString &name) const override
Definition * getOuterScope () const override
const MemberVector & getReferencesMembers () const override
const MemberVector & getReferencedByMembers () const override
bool hasSections () const override
bool hasSources () const override
bool hasBriefDescription () const override
QCString id () const override
const SectionRefs & getSectionRefs () const override
QCString navigationPathAsString () const override
QCString pathFragment () const override
Public Member Functions inherited from MemberDef
Public Member Functions inherited from Definition
Private Attributes
MemberGroup * m_memberGroup
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Protected Member Functions inherited from DefinitionAliasMixin< MemberDef >
const Definition * getAlias () const
const Definition * getScope () const
Detailed Description
Definition at line 528 of file memberdef.cpp.
Constructor & Destructor Documentation
MemberDefAliasImpl()
MemberDefAliasImpl::MemberDefAliasImpl (const Definition * newScope, const MemberDef * md) inline
Definition at line 531 of file memberdef.cpp.
    : DefinitionAliasMixin(newScope,md), m_memberGroup(nullptr) { init(); }
References DefinitionAliasMixin< MemberDef >::DefinitionAliasMixin(), DefinitionAliasMixin< MemberDef >::init(), and m_memberGroup.
~MemberDefAliasImpl()
MemberDefAliasImpl::~MemberDefAliasImpl () inline override
Definition at line 533 of file memberdef.cpp.
{ deinit(); }
References DefinitionAliasMixin< MemberDef >::deinit().
Member Function Documentation
accessorClass()
const ClassDef * MemberDefAliasImpl::accessorClass () const inline override virtual
Implements MemberDef.
Definition at line 603 of file memberdef.cpp.
    { return getMdAlias()->accessorClass(); }
References MemberDef::accessorClass(), and getMdAlias().
anchor()
QCString MemberDefAliasImpl::anchor () const inline override virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 556 of file memberdef.cpp.
    { return getMdAlias()->anchor(); }
References Definition::anchor(), and getMdAlias().
argsString()
QCString MemberDefAliasImpl::argsString () const inline override virtual
Implements MemberDef.
Definition at line 564 of file memberdef.cpp.
    { return getMdAlias()->argsString(); }
References MemberDef::argsString(), and getMdAlias().
argumentList()
const ArgumentList & MemberDefAliasImpl::argumentList () const inline override virtual
Implements MemberDef.
Definition at line 849 of file memberdef.cpp.
    { return getMdAlias()->argumentList(); }
References MemberDef::argumentList(), and getMdAlias().
bitfieldString()
QCString MemberDefAliasImpl::bitfieldString () const inline override virtual
Implements MemberDef.
Definition at line 568 of file memberdef.cpp.
    { return getMdAlias()->bitfieldString(); }
References MemberDef::bitfieldString(), and getMdAlias().
briefDescription()
QCString MemberDefAliasImpl::briefDescription (bool abbreviate) const inline override virtual
Returns the brief description of this definition. This can include commands.
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 919 of file memberdef.cpp.
    { return getMdAlias()->briefDescription(); }
References Definition::briefDescription(), and getMdAlias().
category()
ClassDef * MemberDefAliasImpl::category () const inline override virtual
Implements MemberDef.
Definition at line 905 of file memberdef.cpp.
    { return getMdAlias()->category(); }
References MemberDef::category(), and getMdAlias().
categoryRelation()
const MemberDef * MemberDefAliasImpl::categoryRelation () const inline override virtual
Implements MemberDef.
Definition at line 907 of file memberdef.cpp.
    { return getMdAlias()->categoryRelation(); }
References MemberDef::categoryRelation(), and getMdAlias().
codeSymbolType()
CodeSymbolType MemberDefAliasImpl::codeSymbolType () const inline override virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 550 of file memberdef.cpp.
    { return getMdAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getMdAlias().
createTemplateInstanceMember()
std::unique_ptr< MemberDef > MemberDefAliasImpl::createTemplateInstanceMember (const ArgumentList & formalArgs, const std::unique_ptr< ArgumentList > & actualArgs) const inline override virtual
Implements MemberDef.
Definition at line 940 of file memberdef.cpp.
    { return getMdAlias()->createTemplateInstanceMember(formalArgs,actualArgs); }
References MemberDef::createTemplateInstanceMember(), and getMdAlias().
declaration()
QCString MemberDefAliasImpl::declaration () const inline override virtual
Implements MemberDef.
Definition at line 558 of file memberdef.cpp.
    { return getMdAlias()->declaration(); }
References MemberDef::declaration(), and getMdAlias().
declArgumentList()
const ArgumentList & MemberDefAliasImpl::declArgumentList () const inline override virtual
Implements MemberDef.
Definition at line 851 of file memberdef.cpp.
    { return getMdAlias()->declArgumentList(); }
References MemberDef::declArgumentList(), and getMdAlias().
deepCopy()
std::unique_ptr< MemberDef > MemberDefAliasImpl::deepCopy () const inline override virtual
Implements MemberDef.
Definition at line 543 of file memberdef.cpp.
{
      return createMemberDefAlias(getScope(),getMdAlias());
    }
References createMemberDefAlias(), getMdAlias(), and DefinitionAliasMixin< MemberDef >::getScope().
definition()
QCString MemberDefAliasImpl::definition () const inline override virtual
Implements MemberDef.
Definition at line 560 of file memberdef.cpp.
    { return getMdAlias()->definition(); }
References MemberDef::definition(), and getMdAlias().
definitionTemplateParameterLists()
const ArgumentLists & MemberDefAliasImpl::definitionTemplateParameterLists () const inline override virtual
Implements MemberDef.
Definition at line 855 of file memberdef.cpp.
    { return getMdAlias()->definitionTemplateParameterLists(); }
References MemberDef::definitionTemplateParameterLists(), and getMdAlias().
definitionType()
DefType MemberDefAliasImpl::definitionType () const inline override virtual
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Definition at line 536 of file memberdef.cpp.
{ return TypeMember; }
References definitionType(), and Definition::TypeMember.
Referenced by definitionType().
detectUndocumentedParams()
void MemberDefAliasImpl::detectUndocumentedParams (bool , bool) const inline override virtual
Implements MemberDef.
Definition at line 938 of file memberdef.cpp.
{}
displayDefinition()
QCString MemberDefAliasImpl::displayDefinition () const inline override virtual
Implements MemberDef.
Definition at line 582 of file memberdef.cpp.
    { return getMdAlias()->displayDefinition(); }
References MemberDef::displayDefinition(), and getMdAlias().
displayName()
QCString MemberDefAliasImpl::displayName (bool includeScope = TRUE) const inline override virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 909 of file memberdef.cpp.
    { return getMdAlias()->displayName(b); }
References Definition::displayName(), and getMdAlias().
documentation()
QCString MemberDefAliasImpl::documentation () const inline override virtual
Returns the detailed description of this definition
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 917 of file memberdef.cpp.
    { return getMdAlias()->documentation(); }
References Definition::documentation(), and getMdAlias().
enumBaseType()
QCString MemberDefAliasImpl::enumBaseType () const inline override virtual
Implements MemberDef.
Definition at line 841 of file memberdef.cpp.
    { return getMdAlias()->enumBaseType(); }
References MemberDef::enumBaseType(), and getMdAlias().
enumFieldList()
const MemberVector & MemberDefAliasImpl::enumFieldList () const inline override virtual
Implements MemberDef.
Definition at line 839 of file memberdef.cpp.
    { return getMdAlias()->enumFieldList(); }
References MemberDef::enumFieldList(), and getMdAlias().
excpString()
QCString MemberDefAliasImpl::excpString () const inline override virtual
Implements MemberDef.
Definition at line 566 of file memberdef.cpp.
    { return getMdAlias()->excpString(); }
References MemberDef::excpString(), and getMdAlias().
extraTypeChars()
QCString MemberDefAliasImpl::extraTypeChars () const inline override virtual
Implements MemberDef.
Definition at line 570 of file memberdef.cpp.
    { return getMdAlias()->extraTypeChars(); }
References MemberDef::extraTypeChars(), and getMdAlias().
fieldType()
QCString MemberDefAliasImpl::fieldType () const inline override virtual
Implements MemberDef.
Definition at line 921 of file memberdef.cpp.
    { return getMdAlias()->fieldType(); }
References MemberDef::fieldType(), and getMdAlias().
formalTemplateArguments()
std::optional< ArgumentList > MemberDefAliasImpl::formalTemplateArguments () const inline override virtual
Implements MemberDef.
Definition at line 857 of file memberdef.cpp.
    { return getMdAlias()->formalTemplateArguments(); }
References MemberDef::formalTemplateArguments(), and getMdAlias().
fromAnonymousMember()
MemberDef * MemberDefAliasImpl::fromAnonymousMember () const inline override virtual
Implements MemberDef.
Definition at line 865 of file memberdef.cpp.
    { return getMdAlias()->fromAnonymousMember(); }
References MemberDef::fromAnonymousMember(), and getMdAlias().
fromAnonymousScope()
bool MemberDefAliasImpl::fromAnonymousScope () const inline override virtual
Implements MemberDef.
Definition at line 863 of file memberdef.cpp.
    { return getMdAlias()->fromAnonymousScope(); }
References MemberDef::fromAnonymousScope(), and getMdAlias().
getAnonymousEnumType()
const MemberDef * MemberDefAliasImpl::getAnonymousEnumType () const inline override virtual
Implements MemberDef.
Definition at line 833 of file memberdef.cpp.
    { return getMdAlias()->getAnonymousEnumType(); }
References MemberDef::getAnonymousEnumType(), and getMdAlias().
getCachedResolvedTypedef()
QCString MemberDefAliasImpl::getCachedResolvedTypedef () const inline override virtual
Implements MemberDef.
Definition at line 895 of file memberdef.cpp.
    { return getMdAlias()->getCachedResolvedTypedef(); }
References MemberDef::getCachedResolvedTypedef(), and getMdAlias().
getCachedTypedefTemplSpec()
QCString MemberDefAliasImpl::getCachedTypedefTemplSpec () const inline override virtual
Implements MemberDef.
Definition at line 893 of file memberdef.cpp.
    { return getMdAlias()->getCachedTypedefTemplSpec(); }
References MemberDef::getCachedTypedefTemplSpec(), and getMdAlias().
getCachedTypedefVal()
const ClassDef * MemberDefAliasImpl::getCachedTypedefVal () const inline override virtual
Implements MemberDef.
Definition at line 891 of file memberdef.cpp.
    { return getMdAlias()->getCachedTypedefVal(); }
References MemberDef::getCachedTypedefVal(), and getMdAlias().
getClassDef() [1/2]
const ClassDef * MemberDefAliasImpl::getClassDef () const inline override virtual
Implements MemberDef.
Definition at line 585 of file memberdef.cpp.
    { return getMdAlias()->getClassDef(); }
References MemberDef::getClassDef(), and getMdAlias().
getClassDef() [2/2]
ClassDef * MemberDefAliasImpl::getClassDef () inline override virtual
Implements MemberDef.
Definition at line 587 of file memberdef.cpp.
    { return getMdAlias()->getClassDef(); }
References MemberDef::getClassDef(), and getMdAlias().
getClassDefOfAnonymousType()
ClassDef * MemberDefAliasImpl::getClassDefOfAnonymousType () const inline override virtual
Implements MemberDef.
Definition at line 887 of file memberdef.cpp.
    { return getMdAlias()->getClassDefOfAnonymousType(); }
References MemberDef::getClassDefOfAnonymousType(), and getMdAlias().
getDeclColumn()
int MemberDefAliasImpl::getDeclColumn () const inline override virtual
Implements MemberDef.
Definition at line 929 of file memberdef.cpp.
    { return getMdAlias()->getDeclColumn(); }
References MemberDef::getDeclColumn(), and getMdAlias().
getDeclFileName()
QCString MemberDefAliasImpl::getDeclFileName () const inline override virtual
Implements MemberDef.
Definition at line 925 of file memberdef.cpp.
    { return getMdAlias()->getDeclFileName(); }
References MemberDef::getDeclFileName(), and getMdAlias().
getDeclLine()
int MemberDefAliasImpl::getDeclLine () const inline override virtual
Implements MemberDef.
Definition at line 927 of file memberdef.cpp.
    { return getMdAlias()->getDeclLine(); }
References MemberDef::getDeclLine(), and getMdAlias().
getDeclType()
QCString MemberDefAliasImpl::getDeclType () const inline override virtual
Implements MemberDef.
Definition at line 911 of file memberdef.cpp.
    { return getMdAlias()->getDeclType(); }
References MemberDef::getDeclType(), and getMdAlias().
getEnumScope()
const MemberDef * MemberDefAliasImpl::getEnumScope () const inline override virtual
Implements MemberDef.
Definition at line 837 of file memberdef.cpp.
    { return getMdAlias()->getEnumScope(); }
References MemberDef::getEnumScope(), and getMdAlias().
getExamples()
const ExampleList & MemberDefAliasImpl::getExamples () const inline override virtual
Implements MemberDef.
Definition at line 845 of file memberdef.cpp.
    { return getMdAlias()->getExamples(); }
References MemberDef::getExamples(), and getMdAlias().
getFileDef() [1/2]
const FileDef * MemberDefAliasImpl::getFileDef () const inline override virtual
Implements MemberDef.
Definition at line 590 of file memberdef.cpp.
    { return getMdAlias()->getFileDef(); }
References MemberDef::getFileDef(), and getMdAlias().
getFileDef() [2/2]
FileDef * MemberDefAliasImpl::getFileDef () inline override virtual
Implements MemberDef.
Definition at line 592 of file memberdef.cpp.
    { return getMdAlias()->getFileDef(); }
References MemberDef::getFileDef(), and getMdAlias().
getGroupAlias()
const MemberDef * MemberDefAliasImpl::getGroupAlias () const inline override virtual
Implements MemberDef.
Definition at line 903 of file memberdef.cpp.
    { return getMdAlias()->getGroupAlias(); }
References MemberDef::getGroupAlias(), and getMdAlias().
getGroupDef() [1/2]
const GroupDef * MemberDefAliasImpl::getGroupDef () const inline override virtual
Implements MemberDef.
Definition at line 609 of file memberdef.cpp.
    { return getMdAlias()->getGroupDef(); }
References MemberDef::getGroupDef(), and getMdAlias().
getGroupDef() [2/2]
GroupDef * MemberDefAliasImpl::getGroupDef () inline override virtual
Implements MemberDef.
Definition at line 611 of file memberdef.cpp.
    { return getMdAlias()->getGroupDef(); }
References MemberDef::getGroupDef(), and getMdAlias().
getGroupFileName()
QCString MemberDefAliasImpl::getGroupFileName () const inline override virtual
Implements MemberDef.
Definition at line 615 of file memberdef.cpp.
    { return getMdAlias()->getGroupFileName(); }
References MemberDef::getGroupFileName(), and getMdAlias().
getGroupHasDocs()
bool MemberDefAliasImpl::getGroupHasDocs () const inline override virtual
Implements MemberDef.
Definition at line 619 of file memberdef.cpp.
    { return getMdAlias()->getGroupHasDocs(); }
References MemberDef::getGroupHasDocs(), and getMdAlias().
getGroupPri()
Grouping::GroupPri_t MemberDefAliasImpl::getGroupPri () const inline override virtual
Implements MemberDef.
Definition at line 613 of file memberdef.cpp.
    { return getMdAlias()->getGroupPri(); }
References MemberDef::getGroupPri(), and getMdAlias().
getGroupStartLine()
int MemberDefAliasImpl::getGroupStartLine () const inline override virtual
Implements MemberDef.
Definition at line 617 of file memberdef.cpp.
    { return getMdAlias()->getGroupStartLine(); }
References MemberDef::getGroupStartLine(), and getMdAlias().
getLabels()
StringVector MemberDefAliasImpl::getLabels (const Definition * container) const inline override virtual
Implements MemberDef.
Definition at line 913 of file memberdef.cpp.
    { return getMdAlias()->getLabels(container); }
References MemberDef::getLabels(), and getMdAlias().
getMdAlias() [1/2]
MemberDef * MemberDefAliasImpl::getMdAlias () inline
Definition at line 539 of file memberdef.cpp.
{ return toMemberDef(const_cast<Definition*>(getAlias())); }
References DefinitionAliasMixin< MemberDef >::getAlias(), and toMemberDef().
getMdAlias() [2/2]
const MemberDef * MemberDefAliasImpl::getMdAlias () const inline
Definition at line 538 of file memberdef.cpp.
{ return toMemberDef(getAlias()); }
References DefinitionAliasMixin< MemberDef >::getAlias(), and toMemberDef().
Referenced by accessorClass(), anchor(), argsString(), argumentList(), bitfieldString(), briefDescription(), category(), categoryRelation(), codeSymbolType(), createTemplateInstanceMember(), declaration(), declArgumentList(), deepCopy(), definition(), definitionTemplateParameterLists(), displayDefinition(), displayName(), documentation(), enumBaseType(), enumFieldList(), excpString(), extraTypeChars(), fieldType(), formalTemplateArguments(), fromAnonymousMember(), fromAnonymousScope(), getAnonymousEnumType(), getCachedResolvedTypedef(), getCachedTypedefTemplSpec(), getCachedTypedefVal(), getClassDef(), getClassDef(), getClassDefOfAnonymousType(), getDeclColumn(), getDeclFileName(), getDeclLine(), getDeclType(), getEnumScope(), getExamples(), getFileDef(), getFileDef(), getGroupAlias(), getGroupDef(), getGroupDef(), getGroupFileName(), getGroupHasDocs(), getGroupPri(), getGroupStartLine(), getLabels(), getMemberGroupId(), getMemberSpecifiers(), getModuleDef(), getNamespaceDef(), getNamespaceDef(), getOutputFileBase(), getQualifiers(), getReadAccessor(), getReference(), getScopeString(), getSectionList(), getVhdlSpecifiers(), getWriteAccessor(), hasCallerGraph(), hasCallGraph(), hasDetailedDescription(), hasDocumentation(), hasDocumentedEnumValues(), hasEnumValues(), hasExamples(), hasInlineSource(), hasMultiLineInitializer(), hasOneLineInitializer(), hasReferencedByRelation(), hasReferencesRelation(), hasUserDocumentation(), inheritsDocsFrom(), initializer(), initializerLines(), isAbstract(), isAddable(), isAssign(), isAttribute(), isBound(), isBriefSectionVisible(), isCallable(), isConstEval(), isConstExpr(), isConstInit(), isConstrained(), isConstructor(), isCopy(), isCSharpProperty(), isDCOP(), isDefault(), isDefine(), isDelete(), isDeleted(), isDestructor(), isDetailedSectionVisible(), isDictionary(), isDocsForDefinition(), isDocumentedFriendClass(), isEnumerate(), isEnumStruct(), isEnumValue(), isEvent(), isExplicit(), isExternal(), isFinal(), isForeign(), isFriend(), isFriendClass(), isFriendToHide(), isFunction(), isFunctionOrSignalSlot(), isFunctionPtr(), isGettable(), isImplementation(), isInitonly(), isInline(), isLinkable(), isLinkableInProject(), isMaybeAmbiguous(), isMaybeDefault(), isMaybeVoid(), isMutable(), isNew(), isNoDiscard(), isNoExcept(), isNonAtomic(), isNotFriend(), isObjCMethod(), isObjCProperty(), isOptional(), isOverride(), isPrivateGettable(), isPrivateSettable(), isProperty(), isProtectedGettable(), isProtectedSettable(), isPrototype(), isPublished(), isRaisable(), isReadable(), isReadonly(), isReference(), isReimplementedBy(), isRelated(), isRelatedOrFriend(), isRemovable(), isRequired(), isRetain(), isSealed(), isSequence(), isSettable(), isSignal(), isSliceLocal(), isSlot(), isStatic(), isStrong(), isStrongEnumValue(), isTemplateSpecialization(), isTransient(), isTypeAlias(), isTypedef(), isTypedefValCached(), isUNOProperty(), isUnretained(), isVariable(), isWeak(), isWritable(), livesInsideEnum(), memberDeclaration(), memberDefinition(), memberType(), memberTypeName(), name(), numberOfFlowKeyWords(), objCMethodName(), protection(), qualifiedName(), reimplementedBy(), reimplements(), relatedAlso(), requiresClause(), resolveAlias(), resolveAlias(), sourceRefName(), templateArguments(), templateMaster(), typeConstraints(), typeString(), virtualness(), visibleInIndex(), writeDeclaration(), writeEnumDeclaration(), and writeLink().
getMemberGroup()
MemberGroup * MemberDefAliasImpl::getMemberGroup () const inline override virtual
Implements MemberDef.
Definition at line 861 of file memberdef.cpp.
    { return m_memberGroup; }
References m_memberGroup.
getMemberGroupId()
int MemberDefAliasImpl::getMemberGroupId () const inline override virtual
Implements MemberDef.
Definition at line 859 of file memberdef.cpp.
    { return getMdAlias()->getMemberGroupId(); }
References getMdAlias(), and MemberDef::getMemberGroupId().
getMemberSpecifiers()
TypeSpecifier MemberDefAliasImpl::getMemberSpecifiers () const inline override virtual
Implements MemberDef.
Definition at line 576 of file memberdef.cpp.
    { return getMdAlias()->getMemberSpecifiers(); }
References getMdAlias(), and MemberDef::getMemberSpecifiers().
getModuleDef()
const ModuleDef * MemberDefAliasImpl::getModuleDef () const inline override virtual
Implements MemberDef.
Definition at line 595 of file memberdef.cpp.
    { return getMdAlias()->getModuleDef(); }
References getMdAlias(), and MemberDef::getModuleDef().
getNamespaceDef() [1/2]
const NamespaceDef * MemberDefAliasImpl::getNamespaceDef () const inline override virtual
Implements MemberDef.
Definition at line 598 of file memberdef.cpp.
    { return getMdAlias()->getNamespaceDef(); }
References getMdAlias(), and MemberDef::getNamespaceDef().
getNamespaceDef() [2/2]
NamespaceDef * MemberDefAliasImpl::getNamespaceDef () inline override virtual
Implements MemberDef.
Definition at line 600 of file memberdef.cpp.
    { return getMdAlias()->getNamespaceDef(); }
References getMdAlias(), and MemberDef::getNamespaceDef().
getOutputFileBase()
QCString MemberDefAliasImpl::getOutputFileBase () const inline override virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 552 of file memberdef.cpp.
    { return getMdAlias()->getOutputFileBase(); }
References getMdAlias(), and Definition::getOutputFileBase().
getQualifiers()
StringVector MemberDefAliasImpl::getQualifiers () const inline override virtual
Implements MemberDef.
Definition at line 881 of file memberdef.cpp.
    { return getMdAlias()->getQualifiers(); }
References getMdAlias(), and MemberDef::getQualifiers().
getReadAccessor()
QCString MemberDefAliasImpl::getReadAccessor () const inline override virtual
Implements MemberDef.
Definition at line 605 of file memberdef.cpp.
    { return getMdAlias()->getReadAccessor(); }
References getMdAlias(), and MemberDef::getReadAccessor().
getReference()
QCString MemberDefAliasImpl::getReference () const inline override virtual
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 554 of file memberdef.cpp.
    { return getMdAlias()->getReference(); }
References getMdAlias(), and Definition::getReference().
getScopeString()
QCString MemberDefAliasImpl::getScopeString () const inline override virtual
Implements MemberDef.
Definition at line 885 of file memberdef.cpp.
    { return getMdAlias()->getScopeString(); }
References getMdAlias(), and MemberDef::getScopeString().
getSectionList()
const MemberList * MemberDefAliasImpl::getSectionList (const Definition * container) const inline override virtual
Implements MemberDef.
Definition at line 580 of file memberdef.cpp.
    { return getMdAlias()->getSectionList(container); }
References getMdAlias(), and MemberDef::getSectionList().
getVhdlSpecifiers()
VhdlSpecifier MemberDefAliasImpl::getVhdlSpecifiers () const inline override virtual
Implements MemberDef.
Definition at line 578 of file memberdef.cpp.
    { return getMdAlias()->getVhdlSpecifiers(); }
References getMdAlias(), and MemberDef::getVhdlSpecifiers().
getWriteAccessor()
QCString MemberDefAliasImpl::getWriteAccessor () const inline override virtual
Implements MemberDef.
Definition at line 607 of file memberdef.cpp.
    { return getMdAlias()->getWriteAccessor(); }
References getMdAlias(), and MemberDef::getWriteAccessor().
hasCallerGraph()
bool MemberDefAliasImpl::hasCallerGraph () const inline override virtual
Implements MemberDef.
Definition at line 869 of file memberdef.cpp.
    { return getMdAlias()->hasCallerGraph(); }
References getMdAlias(), and MemberDef::hasCallerGraph().
hasCallGraph()
bool MemberDefAliasImpl::hasCallGraph () const inline override virtual
Implements MemberDef.
Definition at line 867 of file memberdef.cpp.
    { return getMdAlias()->hasCallGraph(); }
References getMdAlias(), and MemberDef::hasCallGraph().
hasDetailedDescription()
bool MemberDefAliasImpl::hasDetailedDescription () const inline override virtual
Implements MemberDef.
Definition at line 817 of file memberdef.cpp.
    { return getMdAlias()->hasDetailedDescription(); }
References getMdAlias(), and MemberDef::hasDetailedDescription().
hasDocumentation()
bool MemberDefAliasImpl::hasDocumentation () const inline override virtual
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 807 of file memberdef.cpp.
    { return getMdAlias()->hasDocumentation(); }
References getMdAlias(), and Definition::hasDocumentation().
hasDocumentedEnumValues()
bool MemberDefAliasImpl::hasDocumentedEnumValues () const inline override virtual
Implements MemberDef.
Definition at line 831 of file memberdef.cpp.
    { return getMdAlias()->hasDocumentedEnumValues(); }
References getMdAlias(), and MemberDef::hasDocumentedEnumValues().
hasEnumValues()
bool MemberDefAliasImpl::hasEnumValues () const inline override virtual
Implements MemberDef.
Definition at line 879 of file memberdef.cpp.
    { return getMdAlias()->hasEnumValues(); }
References getMdAlias(), and MemberDef::hasEnumValues().
hasExamples()
bool MemberDefAliasImpl::hasExamples () const inline override virtual
Implements MemberDef.
Definition at line 843 of file memberdef.cpp.
    { return getMdAlias()->hasExamples(); }
References getMdAlias(), and MemberDef::hasExamples().
hasInlineSource()
bool MemberDefAliasImpl::hasInlineSource () const inline override virtual
Implements MemberDef.
Definition at line 875 of file memberdef.cpp.
    { return getMdAlias()->hasInlineSource(); }
References getMdAlias(), and MemberDef::hasInlineSource().
hasMultiLineInitializer()
bool MemberDefAliasImpl::hasMultiLineInitializer () const inline override virtual
Implements MemberDef.
Definition at line 775 of file memberdef.cpp.
    { return getMdAlias()->hasMultiLineInitializer(); }
References getMdAlias(), and MemberDef::hasMultiLineInitializer().
hasOneLineInitializer()
bool MemberDefAliasImpl::hasOneLineInitializer () const inline override virtual
Implements MemberDef.
Definition at line 773 of file memberdef.cpp.
    { return getMdAlias()->hasOneLineInitializer(); }
References getMdAlias(), and MemberDef::hasOneLineInitializer().
hasReferencedByRelation()
bool MemberDefAliasImpl::hasReferencedByRelation () const inline override virtual
Implements MemberDef.
Definition at line 873 of file memberdef.cpp.
    { return getMdAlias()->hasReferencedByRelation(); }
References getMdAlias(), and MemberDef::hasReferencedByRelation().
hasReferencesRelation()
bool MemberDefAliasImpl::hasReferencesRelation () const inline override virtual
Implements MemberDef.
Definition at line 871 of file memberdef.cpp.
    { return getMdAlias()->hasReferencesRelation(); }
References getMdAlias(), and MemberDef::hasReferencesRelation().
hasUserDocumentation()
bool MemberDefAliasImpl::hasUserDocumentation () const inline override virtual
Returns TRUE iff the definition is documented by the user.
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 809 of file memberdef.cpp.
    { return getMdAlias()->hasUserDocumentation(); }
References getMdAlias(), and Definition::hasUserDocumentation().
inheritsDocsFrom()
const MemberDef * MemberDefAliasImpl::inheritsDocsFrom () const inline override virtual
Implements MemberDef.
Definition at line 901 of file memberdef.cpp.
    { return getMdAlias()->inheritsDocsFrom(); }
References getMdAlias(), and MemberDef::inheritsDocsFrom().
initializer()
const QCString & MemberDefAliasImpl::initializer () const inline override virtual
Implements MemberDef.
Definition at line 572 of file memberdef.cpp.
    { return getMdAlias()->initializer(); }
References getMdAlias(), and MemberDef::initializer().
initializerLines()
int MemberDefAliasImpl::initializerLines () const inline override virtual
Implements MemberDef.
Definition at line 574 of file memberdef.cpp.
    { return getMdAlias()->initializerLines(); }
References getMdAlias(), and MemberDef::initializerLines().
isAbstract()
bool MemberDefAliasImpl::isAbstract () const inline override virtual
Implements MemberDef.
Definition at line 699 of file memberdef.cpp.
    { return getMdAlias()->isAbstract(); }
References getMdAlias(), and MemberDef::isAbstract().
isAddable()
bool MemberDefAliasImpl::isAddable () const inline override virtual
Implements MemberDef.
Definition at line 691 of file memberdef.cpp.
    { return getMdAlias()->isAddable(); }
References getMdAlias(), and MemberDef::isAddable().
isAssign()
bool MemberDefAliasImpl::isAssign () const inline override virtual
Implements MemberDef.
Definition at line 713 of file memberdef.cpp.
    { return getMdAlias()->isAssign(); }
References getMdAlias(), and MemberDef::isAssign().
isAttribute()
bool MemberDefAliasImpl::isAttribute () const inline override virtual
Implements MemberDef.
Definition at line 741 of file memberdef.cpp.
    { return getMdAlias()->isAttribute(); }
References getMdAlias(), and MemberDef::isAttribute().
isBound()
bool MemberDefAliasImpl::isBound () const inline override virtual
Implements MemberDef.
Definition at line 747 of file memberdef.cpp.
    { return getMdAlias()->isBound(); }
References getMdAlias(), and MemberDef::isBound().
isBriefSectionVisible()
bool MemberDefAliasImpl::isBriefSectionVisible () const inline override virtual
Implements MemberDef.
Definition at line 813 of file memberdef.cpp.
    { return getMdAlias()->isBriefSectionVisible(); }
References getMdAlias(), and MemberDef::isBriefSectionVisible().
isCallable()
bool MemberDefAliasImpl::isCallable () const inline override virtual
Implements MemberDef.
Definition at line 777 of file memberdef.cpp.
    { return getMdAlias()->isCallable(); }
References getMdAlias(), and MemberDef::isCallable().
isConstEval()
bool MemberDefAliasImpl::isConstEval () const inline override virtual
Implements MemberDef.
Definition at line 789 of file memberdef.cpp.
    { return getMdAlias()->isConstEval(); }
References getMdAlias(), and MemberDef::isConstEval().
isConstExpr()
bool MemberDefAliasImpl::isConstExpr () const inline override virtual
Implements MemberDef.
Definition at line 787 of file memberdef.cpp.
    { return getMdAlias()->isConstExpr(); }
References getMdAlias(), and MemberDef::isConstExpr().
isConstInit()
bool MemberDefAliasImpl::isConstInit () const inline override virtual
Implements MemberDef.
Definition at line 791 of file memberdef.cpp.
    { return getMdAlias()->isConstInit(); }
References getMdAlias(), and MemberDef::isConstInit().
isConstrained()
bool MemberDefAliasImpl::isConstrained () const inline override virtual
Implements MemberDef.
Definition at line 749 of file memberdef.cpp.
    { return getMdAlias()->isConstrained(); }
References getMdAlias(), and MemberDef::isConstrained().
isConstructor()
bool MemberDefAliasImpl::isConstructor () const inline override virtual
Implements MemberDef.
Definition at line 769 of file memberdef.cpp.
    { return getMdAlias()->isConstructor(); }
References getMdAlias(), and MemberDef::isConstructor().
isCopy()
bool MemberDefAliasImpl::isCopy () const inline override virtual
Implements MemberDef.
Definition at line 711 of file memberdef.cpp.
    { return getMdAlias()->isCopy(); }
References getMdAlias(), and MemberDef::isCopy().
isCSharpProperty()
bool MemberDefAliasImpl::isCSharpProperty () const inline override virtual
Implements MemberDef.
Definition at line 767 of file memberdef.cpp.
    { return getMdAlias()->isCSharpProperty(); }
References getMdAlias(), and MemberDef::isCSharpProperty().
isDCOP()
bool MemberDefAliasImpl::isDCOP () const inline override virtual
Implements MemberDef.
Definition at line 657 of file memberdef.cpp.
    { return getMdAlias()->isDCOP(); }
References getMdAlias(), and MemberDef::isDCOP().
isDefault()
bool MemberDefAliasImpl::isDefault () const inline override virtual
Implements MemberDef.
Definition at line 735 of file memberdef.cpp.
    { return getMdAlias()->isDefault(); }
References getMdAlias(), and MemberDef::isDefault().
isDefine()
bool MemberDefAliasImpl::isDefine () const inline override virtual
Implements MemberDef.
Definition at line 653 of file memberdef.cpp.
    { return getMdAlias()->isDefine(); }
References getMdAlias(), and MemberDef::isDefine().
isDelete()
bool MemberDefAliasImpl::isDelete () const inline override virtual
Implements MemberDef.
Definition at line 737 of file memberdef.cpp.
    { return getMdAlias()->isDelete(); }
References getMdAlias(), and MemberDef::isDelete().
isDeleted()
bool MemberDefAliasImpl::isDeleted () const inline override virtual
Implements MemberDef.
Definition at line 811 of file memberdef.cpp.
    { return getMdAlias()->isDeleted(); }
References getMdAlias(), and MemberDef::isDeleted().
isDestructor()
bool MemberDefAliasImpl::isDestructor () const inline override virtual
Implements MemberDef.
Definition at line 771 of file memberdef.cpp.
    { return getMdAlias()->isDestructor(); }
References getMdAlias(), and MemberDef::isDestructor().
isDetailedSectionVisible()
bool MemberDefAliasImpl::isDetailedSectionVisible (MemberListContainer container) const inline override virtual
Implements MemberDef.
Definition at line 815 of file memberdef.cpp.
    { return getMdAlias()->isDetailedSectionVisible(container); }
References getMdAlias(), and MemberDef::isDetailedSectionVisible().
isDictionary()
bool MemberDefAliasImpl::isDictionary () const inline override virtual
Implements MemberDef.
Definition at line 647 of file memberdef.cpp.
    { return getMdAlias()->isDictionary(); }
References getMdAlias(), and MemberDef::isDictionary().
isDocsForDefinition()
bool MemberDefAliasImpl::isDocsForDefinition () const inline override virtual
Implements MemberDef.
Definition at line 835 of file memberdef.cpp.
    { return getMdAlias()->isDocsForDefinition(); }
References getMdAlias(), and MemberDef::isDocsForDefinition().
isDocumentedFriendClass()
bool MemberDefAliasImpl::isDocumentedFriendClass () const inline override virtual
Implements MemberDef.
Definition at line 821 of file memberdef.cpp.
    { return getMdAlias()->isDocumentedFriendClass(); }
References getMdAlias(), and MemberDef::isDocumentedFriendClass().
isEnumerate()
bool MemberDefAliasImpl::isEnumerate () const inline override virtual
Implements MemberDef.
Definition at line 639 of file memberdef.cpp.
    { return getMdAlias()->isEnumerate(); }
References getMdAlias(), and MemberDef::isEnumerate().
isEnumStruct()
bool MemberDefAliasImpl::isEnumStruct () const inline override virtual
Implements MemberDef.
Definition at line 721 of file memberdef.cpp.
    { return getMdAlias()->isEnumStruct(); }
References getMdAlias(), and MemberDef::isEnumStruct().
isEnumValue()
bool MemberDefAliasImpl::isEnumValue () const inline override virtual
Implements MemberDef.
Definition at line 641 of file memberdef.cpp.
    { return getMdAlias()->isEnumValue(); }
References getMdAlias(), and MemberDef::isEnumValue().
isEvent()
bool MemberDefAliasImpl::isEvent () const inline override virtual
Implements MemberDef.
Definition at line 661 of file memberdef.cpp.
    { return getMdAlias()->isEvent(); }
References getMdAlias(), and MemberDef::isEvent().
isExplicit()
bool MemberDefAliasImpl::isExplicit () const inline override virtual
Implements MemberDef.
Definition at line 671 of file memberdef.cpp.
    { return getMdAlias()->isExplicit(); }
References getMdAlias(), and MemberDef::isExplicit().
isExternal()
bool MemberDefAliasImpl::isExternal () const inline override virtual
Implements MemberDef.
Definition at line 731 of file memberdef.cpp.
    { return getMdAlias()->isExternal(); }
References getMdAlias(), and MemberDef::isExternal().
isFinal()
bool MemberDefAliasImpl::isFinal () const inline override virtual
Implements MemberDef.
Definition at line 697 of file memberdef.cpp.
    { return getMdAlias()->isFinal(); }
References getMdAlias(), and MemberDef::isFinal().
isForeign()
bool MemberDefAliasImpl::isForeign () const inline override virtual
Implements MemberDef.
Definition at line 665 of file memberdef.cpp.
    { return getMdAlias()->isForeign(); }
References getMdAlias(), and MemberDef::isForeign().
isFriend()
bool MemberDefAliasImpl::isFriend () const inline override virtual
Implements MemberDef.
Definition at line 655 of file memberdef.cpp.
    { return getMdAlias()->isFriend(); }
References getMdAlias(), and MemberDef::isFriend().
isFriendClass()
bool MemberDefAliasImpl::isFriendClass () const inline override virtual
Implements MemberDef.
Definition at line 819 of file memberdef.cpp.
    { return getMdAlias()->isFriendClass(); }
References getMdAlias(), and MemberDef::isFriendClass().
isFriendToHide()
bool MemberDefAliasImpl::isFriendToHide () const inline override virtual
Implements MemberDef.
Definition at line 795 of file memberdef.cpp.
    { return getMdAlias()->isFriendToHide(); }
References getMdAlias(), and MemberDef::isFriendToHide().
isFunction()
bool MemberDefAliasImpl::isFunction () const inline override virtual
Implements MemberDef.
Definition at line 649 of file memberdef.cpp.
    { return getMdAlias()->isFunction(); }
References getMdAlias(), and MemberDef::isFunction().
isFunctionOrSignalSlot()
bool MemberDefAliasImpl::isFunctionOrSignalSlot () const inline override virtual
Implements MemberDef.
Definition at line 799 of file memberdef.cpp.
    { return getMdAlias()->isFunctionOrSignalSlot(); }
References getMdAlias(), and MemberDef::isFunctionOrSignalSlot().
isFunctionPtr()
bool MemberDefAliasImpl::isFunctionPtr () const inline override virtual
Implements MemberDef.
Definition at line 651 of file memberdef.cpp.
    { return getMdAlias()->isFunctionPtr(); }
References getMdAlias(), and MemberDef::isFunctionPtr().
isGettable()
bool MemberDefAliasImpl::isGettable () const inline override virtual
Implements MemberDef.
Definition at line 675 of file memberdef.cpp.
    { return getMdAlias()->isGettable(); }
References getMdAlias(), and MemberDef::isGettable().
isImplementation()
bool MemberDefAliasImpl::isImplementation () const inline override virtual
Implements MemberDef.
Definition at line 729 of file memberdef.cpp.
    { return getMdAlias()->isImplementation(); }
References getMdAlias(), and MemberDef::isImplementation().
isInitonly()
bool MemberDefAliasImpl::isInitonly () const inline override virtual
Implements MemberDef.
Definition at line 703 of file memberdef.cpp.
    { return getMdAlias()->isInitonly(); }
References getMdAlias(), and MemberDef::isInitonly().
isInline()
bool MemberDefAliasImpl::isInline () const inline override virtual
Implements MemberDef.
Definition at line 669 of file memberdef.cpp.
    { return getMdAlias()->isInline(); }
References getMdAlias(), and MemberDef::isInline().
isLinkable()
bool MemberDefAliasImpl::isLinkable () const inline override virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 805 of file memberdef.cpp.
    { return getMdAlias()->isLinkable(); }
References getMdAlias(), and Definition::isLinkable().
isLinkableInProject()
bool MemberDefAliasImpl::isLinkableInProject () const inline override virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 803 of file memberdef.cpp.
    { return getMdAlias()->isLinkableInProject(); }
References getMdAlias(), and Definition::isLinkableInProject().
isMaybeAmbiguous()
bool MemberDefAliasImpl::isMaybeAmbiguous () const inline override virtual
Implements MemberDef.
Definition at line 757 of file memberdef.cpp.
    { return getMdAlias()->isMaybeAmbiguous(); }
References getMdAlias(), and MemberDef::isMaybeAmbiguous().
isMaybeDefault()
bool MemberDefAliasImpl::isMaybeDefault () const inline override virtual
Implements MemberDef.
Definition at line 755 of file memberdef.cpp.
    { return getMdAlias()->isMaybeDefault(); }
References getMdAlias(), and MemberDef::isMaybeDefault().
isMaybeVoid()
bool MemberDefAliasImpl::isMaybeVoid () const inline override virtual
Implements MemberDef.
Definition at line 753 of file memberdef.cpp.
    { return getMdAlias()->isMaybeVoid(); }
References getMdAlias(), and MemberDef::isMaybeVoid().
isMutable()
bool MemberDefAliasImpl::isMutable () const inline override virtual
Implements MemberDef.
Definition at line 673 of file memberdef.cpp.
    { return getMdAlias()->isMutable(); }
References getMdAlias(), and MemberDef::isMutable().
isNew()
bool MemberDefAliasImpl::isNew () const inline override virtual
Implements MemberDef.
Definition at line 725 of file memberdef.cpp.
    { return getMdAlias()->isNew(); }
References getMdAlias(), and MemberDef::isNew().
isNoDiscard()
bool MemberDefAliasImpl::isNoDiscard () const inline override virtual
Implements MemberDef.
Definition at line 785 of file memberdef.cpp.
    { return getMdAlias()->isNoDiscard(); }
References getMdAlias(), and MemberDef::isNoDiscard().
isNoExcept()
bool MemberDefAliasImpl::isNoExcept () const inline override virtual
Implements MemberDef.
Definition at line 739 of file memberdef.cpp.
    { return getMdAlias()->isNoExcept(); }
References getMdAlias(), and MemberDef::isNoExcept().
isNonAtomic()
bool MemberDefAliasImpl::isNonAtomic () const inline override virtual
Implements MemberDef.
Definition at line 709 of file memberdef.cpp.
    { return getMdAlias()->isNonAtomic(); }
References getMdAlias(), and MemberDef::isNonAtomic().
isNotFriend()
bool MemberDefAliasImpl::isNotFriend () const inline override virtual
Implements MemberDef.
Definition at line 797 of file memberdef.cpp.
    { return getMdAlias()->isNotFriend(); }
References getMdAlias(), and MemberDef::isNotFriend().
isObjCMethod()
bool MemberDefAliasImpl::isObjCMethod () const inline override virtual
Implements MemberDef.
Definition at line 763 of file memberdef.cpp.
    { return getMdAlias()->isObjCMethod(); }
References getMdAlias(), and MemberDef::isObjCMethod().
isObjCProperty()
bool MemberDefAliasImpl::isObjCProperty () const inline override virtual
Implements MemberDef.
Definition at line 765 of file memberdef.cpp.
    { return getMdAlias()->isObjCProperty(); }
References getMdAlias(), and MemberDef::isObjCProperty().
isOptional()
bool MemberDefAliasImpl::isOptional () const inline override virtual
Implements MemberDef.
Definition at line 705 of file memberdef.cpp.
    { return getMdAlias()->isOptional(); }
References getMdAlias(), and MemberDef::isOptional().
isOverride()
bool MemberDefAliasImpl::isOverride () const inline override virtual
Implements MemberDef.
Definition at line 701 of file memberdef.cpp.
    { return getMdAlias()->isOverride(); }
References getMdAlias(), and MemberDef::isOverride().
isPrivateGettable()
bool MemberDefAliasImpl::isPrivateGettable () const inline override virtual
Implements MemberDef.
Definition at line 677 of file memberdef.cpp.
    { return getMdAlias()->isPrivateGettable(); }
References getMdAlias(), and MemberDef::isPrivateGettable().
isPrivateSettable()
bool MemberDefAliasImpl::isPrivateSettable () const inline override virtual
Implements MemberDef.
Definition at line 683 of file memberdef.cpp.
    { return getMdAlias()->isPrivateSettable(); }
References getMdAlias(), and MemberDef::isPrivateSettable().
isProperty()
bool MemberDefAliasImpl::isProperty () const inline override virtual
Implements MemberDef.
Definition at line 659 of file memberdef.cpp.
    { return getMdAlias()->isProperty(); }
References getMdAlias(), and MemberDef::isProperty().
isProtectedGettable()
bool MemberDefAliasImpl::isProtectedGettable () const inline override virtual
Implements MemberDef.
Definition at line 679 of file memberdef.cpp.
    { return getMdAlias()->isProtectedGettable(); }
References getMdAlias(), and MemberDef::isProtectedGettable().
isProtectedSettable()
bool MemberDefAliasImpl::isProtectedSettable () const inline override virtual
Implements MemberDef.
Definition at line 685 of file memberdef.cpp.
    { return getMdAlias()->isProtectedSettable(); }
References getMdAlias(), and MemberDef::isProtectedSettable().
isPrototype()
bool MemberDefAliasImpl::isPrototype () const inline override virtual
Implements MemberDef.
Definition at line 847 of file memberdef.cpp.
    { return getMdAlias()->isPrototype(); }
References getMdAlias(), and MemberDef::isPrototype().
isPublished()
bool MemberDefAliasImpl::isPublished () const inline override virtual
Implements MemberDef.
Definition at line 759 of file memberdef.cpp.
    { return getMdAlias()->isPublished(); }
References getMdAlias(), and MemberDef::isPublished().
isRaisable()
bool MemberDefAliasImpl::isRaisable () const inline override virtual
Implements MemberDef.
Definition at line 695 of file memberdef.cpp.
    { return getMdAlias()->isRaisable(); }
References getMdAlias(), and MemberDef::isRaisable().
isReadable()
bool MemberDefAliasImpl::isReadable () const inline override virtual
Implements MemberDef.
Definition at line 687 of file memberdef.cpp.
    { return getMdAlias()->isReadable(); }
References getMdAlias(), and MemberDef::isReadable().
isReadonly()
bool MemberDefAliasImpl::isReadonly () const inline override virtual
Implements MemberDef.
Definition at line 745 of file memberdef.cpp.
    { return getMdAlias()->isReadable(); }
References getMdAlias(), and MemberDef::isReadable().
isReference()
bool MemberDefAliasImpl::isReference () const inline override virtual
Returns TRUE if this definition is imported via a tag file.
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 923 of file memberdef.cpp.
    { return getMdAlias()->isReference(); }
References getMdAlias(), and Definition::isReference().
isReimplementedBy()
bool MemberDefAliasImpl::isReimplementedBy (const ClassDef * cd) const inline override virtual
Implements MemberDef.
Definition at line 827 of file memberdef.cpp.
    { return getMdAlias()->isReimplementedBy(cd); }
References getMdAlias(), and MemberDef::isReimplementedBy().
isRelated()
bool MemberDefAliasImpl::isRelated () const inline override virtual
Implements MemberDef.
Definition at line 663 of file memberdef.cpp.
    { return getMdAlias()->isRelated(); }
References getMdAlias(), and MemberDef::isRelated().
isRelatedOrFriend()
bool MemberDefAliasImpl::isRelatedOrFriend () const inline override virtual
Implements MemberDef.
Definition at line 801 of file memberdef.cpp.
    { return getMdAlias()->isRelatedOrFriend(); }
References getMdAlias(), and MemberDef::isRelatedOrFriend().
isRemovable()
bool MemberDefAliasImpl::isRemovable () const inline override virtual
Implements MemberDef.
Definition at line 693 of file memberdef.cpp.
    { return getMdAlias()->isRemovable(); }
References getMdAlias(), and MemberDef::isRemovable().
isRequired()
bool MemberDefAliasImpl::isRequired () const inline override virtual
Implements MemberDef.
Definition at line 707 of file memberdef.cpp.
    { return getMdAlias()->isRequired(); }
References getMdAlias(), and MemberDef::isRequired().
isRetain()
bool MemberDefAliasImpl::isRetain () const inline override virtual
Implements MemberDef.
Definition at line 715 of file memberdef.cpp.
    { return getMdAlias()->isRetain(); }
References getMdAlias(), and MemberDef::isRetain().
isSealed()
bool MemberDefAliasImpl::isSealed () const inline override virtual
Implements MemberDef.
Definition at line 727 of file memberdef.cpp.
    { return getMdAlias()->isSealed(); }
References getMdAlias(), and MemberDef::isSealed().
isSequence()
bool MemberDefAliasImpl::isSequence () const inline override virtual
Implements MemberDef.
Definition at line 645 of file memberdef.cpp.
    { return getMdAlias()->isSequence(); }
References getMdAlias(), and MemberDef::isSequence().
isSettable()
bool MemberDefAliasImpl::isSettable () const inline override virtual
Implements MemberDef.
Definition at line 681 of file memberdef.cpp.
    { return getMdAlias()->isSettable(); }
References getMdAlias(), and MemberDef::isSettable().
isSignal()
bool MemberDefAliasImpl::isSignal () const inline override virtual
Implements MemberDef.
Definition at line 633 of file memberdef.cpp.
    { return getMdAlias()->isSignal(); }
References getMdAlias(), and MemberDef::isSignal().
isSliceLocal()
bool MemberDefAliasImpl::isSliceLocal () const inline override virtual
Implements MemberDef.
Definition at line 783 of file memberdef.cpp.
    { return getMdAlias()->isSliceLocal(); }
References getMdAlias(), and MemberDef::isSliceLocal().
isSlot()
bool MemberDefAliasImpl::isSlot () const inline override virtual
Implements MemberDef.
Definition at line 635 of file memberdef.cpp.
    { return getMdAlias()->isSlot(); }
References getMdAlias(), and MemberDef::isSlot().
isStatic()
bool MemberDefAliasImpl::isStatic () const inline override virtual
Implements MemberDef.
Definition at line 667 of file memberdef.cpp.
    { return getMdAlias()->isStatic(); }
References getMdAlias(), and MemberDef::isStatic().
isStrong()
bool MemberDefAliasImpl::isStrong () const inline override virtual
Implements MemberDef.
Definition at line 719 of file memberdef.cpp.
    { return getMdAlias()->isStrong(); }
References getMdAlias(), and MemberDef::isStrong().
isStrongEnumValue()
bool MemberDefAliasImpl::isStrongEnumValue () const inline override virtual
Implements MemberDef.
Definition at line 779 of file memberdef.cpp.
    { return getMdAlias()->isStrongEnumValue(); }
References getMdAlias(), and MemberDef::isStrongEnumValue().
isTemplateSpecialization()
bool MemberDefAliasImpl::isTemplateSpecialization () const inline override virtual
Implements MemberDef.
Definition at line 761 of file memberdef.cpp.
    { return getMdAlias()->isTemplateSpecialization(); }
References getMdAlias(), and MemberDef::isTemplateSpecialization().
isTransient()
bool MemberDefAliasImpl::isTransient () const inline override virtual
Implements MemberDef.
Definition at line 751 of file memberdef.cpp.
    { return getMdAlias()->isTransient(); }
References getMdAlias(), and MemberDef::isTransient().
isTypeAlias()
bool MemberDefAliasImpl::isTypeAlias () const inline override virtual
Implements MemberDef.
Definition at line 733 of file memberdef.cpp.
    { return getMdAlias()->isTypeAlias(); }
References getMdAlias(), and MemberDef::isTypeAlias().
isTypedef()
bool MemberDefAliasImpl::isTypedef () const inline override virtual
Implements MemberDef.
Definition at line 643 of file memberdef.cpp.
    { return getMdAlias()->isTypedef(); }
References getMdAlias(), and MemberDef::isTypedef().
isTypedefValCached()
bool MemberDefAliasImpl::isTypedefValCached () const inline override virtual
Implements MemberDef.
Definition at line 889 of file memberdef.cpp.
    { return getMdAlias()->isTypedefValCached(); }
References getMdAlias(), and MemberDef::isTypedefValCached().
isUNOProperty()
bool MemberDefAliasImpl::isUNOProperty () const inline override virtual
Implements MemberDef.
Definition at line 743 of file memberdef.cpp.
    { return getMdAlias()->isUNOProperty(); }
References getMdAlias(), and MemberDef::isUNOProperty().
isUnretained()
bool MemberDefAliasImpl::isUnretained () const inline override virtual
Implements MemberDef.
Definition at line 723 of file memberdef.cpp.
    { return getMdAlias()->isUnretained(); }
References getMdAlias(), and MemberDef::isUnretained().
isVariable()
bool MemberDefAliasImpl::isVariable () const inline override virtual
Implements MemberDef.
Definition at line 637 of file memberdef.cpp.
    { return getMdAlias()->isVariable(); }
References getMdAlias(), and MemberDef::isVariable().
isWeak()
bool MemberDefAliasImpl::isWeak () const inline override virtual
Implements MemberDef.
Definition at line 717 of file memberdef.cpp.
    { return getMdAlias()->isWeak(); }
References getMdAlias(), and MemberDef::isWeak().
isWritable()
bool MemberDefAliasImpl::isWritable () const inline override virtual
Implements MemberDef.
Definition at line 689 of file memberdef.cpp.
    { return getMdAlias()->isWritable(); }
References getMdAlias(), and MemberDef::isWritable().
livesInsideEnum()
bool MemberDefAliasImpl::livesInsideEnum () const inline override virtual
Implements MemberDef.
Definition at line 781 of file memberdef.cpp.
    { return getMdAlias()->livesInsideEnum(); }
References getMdAlias(), and MemberDef::livesInsideEnum().
memberDeclaration()
MemberDef * MemberDefAliasImpl::memberDeclaration () const inline override virtual
Implements MemberDef.
Definition at line 899 of file memberdef.cpp.
    { return getMdAlias()->memberDeclaration(); }
References getMdAlias(), and MemberDef::memberDeclaration().
memberDefinition()
MemberDef * MemberDefAliasImpl::memberDefinition () const inline override virtual
Implements MemberDef.
Definition at line 897 of file memberdef.cpp.
    { return getMdAlias()->memberDefinition(); }
References getMdAlias(), and MemberDef::memberDefinition().
memberType()
MemberType MemberDefAliasImpl::memberType () const inline override virtual
Implements MemberDef.
Definition at line 629 of file memberdef.cpp.
    { return getMdAlias()->memberType(); }
References getMdAlias(), and MemberDef::memberType().
memberTypeName()
QCString MemberDefAliasImpl::memberTypeName () const inline override virtual
Implements MemberDef.
Definition at line 631 of file memberdef.cpp.
    { return getMdAlias()->memberTypeName(); }
References getMdAlias(), and MemberDef::memberTypeName().
moveTo()
void MemberDefAliasImpl::moveTo (Definition *) inline override virtual
Implements MemberDef.
Definition at line 546 of file memberdef.cpp.
{}
name()
const QCString & MemberDefAliasImpl::name () const inline override virtual
Returns the name of the definition
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 548 of file memberdef.cpp.
    { return getMdAlias()->name(); }
References getMdAlias(), and Definition::name().
numberOfFlowKeyWords()
int MemberDefAliasImpl::numberOfFlowKeyWords () const inline override virtual
Implements MemberDef.
Definition at line 793 of file memberdef.cpp.
    { return getMdAlias()->numberOfFlowKeyWords(); }
References getMdAlias(), and MemberDef::numberOfFlowKeyWords().
objCMethodName()
QCString MemberDefAliasImpl::objCMethodName (bool localLink, bool showStatic) const inline override virtual
Implements MemberDef.
Definition at line 623 of file memberdef.cpp.
    { return getMdAlias()->objCMethodName(localLink,showStatic); }
References getMdAlias(), and MemberDef::objCMethodName().
protection()
Protection MemberDefAliasImpl::protection () const inline override virtual
Implements MemberDef.
Definition at line 625 of file memberdef.cpp.
    { return getMdAlias()->protection(); }
References getMdAlias(), and MemberDef::protection().
qualifiedName()
QCString MemberDefAliasImpl::qualifiedName () const inline override virtual
Returns the fully qualified name of this definition
Reimplemented from DefinitionAliasMixin< MemberDef >.
Definition at line 621 of file memberdef.cpp.
    { return getMdAlias()->qualifiedName(); }
References getMdAlias(), and Definition::qualifiedName().
reimplementedBy()
const MemberVector & MemberDefAliasImpl::reimplementedBy () const inline override virtual
Implements MemberDef.
Definition at line 825 of file memberdef.cpp.
    { return getMdAlias()->reimplementedBy(); }
References getMdAlias(), and MemberDef::reimplementedBy().
reimplements()
const MemberDef * MemberDefAliasImpl::reimplements () const inline override virtual
Implements MemberDef.
Definition at line 823 of file memberdef.cpp.
    { return getMdAlias()->reimplements(); }
References getMdAlias(), and MemberDef::reimplements().
relatedAlso()
ClassDef * MemberDefAliasImpl::relatedAlso () const inline override virtual
Implements MemberDef.
Definition at line 829 of file memberdef.cpp.
    { return getMdAlias()->relatedAlso(); }
References getMdAlias(), and MemberDef::relatedAlso().
requiresClause()
QCString MemberDefAliasImpl::requiresClause () const inline override virtual
Implements MemberDef.
Definition at line 931 of file memberdef.cpp.
    { return getMdAlias()->requiresClause(); }
References getMdAlias(), and MemberDef::requiresClause().
resolveAlias() [1/2]
const MemberDef * MemberDefAliasImpl::resolveAlias () const inline override virtual
Implements MemberDef.
Definition at line 541 of file memberdef.cpp.
{ return getMdAlias(); }
References getMdAlias().
resolveAlias() [2/2]
MemberDef * MemberDefAliasImpl::resolveAlias () inline override virtual
Implements MemberDef.
Definition at line 540 of file memberdef.cpp.
{ return const_cast<MemberDef*>(getMdAlias()); }
References getMdAlias().
setMemberGroup()
void MemberDefAliasImpl::setMemberGroup (MemberGroup * grp) inline override virtual
Implements MemberDef.
Definition at line 939 of file memberdef.cpp.
{ m_memberGroup = grp; }
References m_memberGroup.
sourceRefName()
QCString MemberDefAliasImpl::sourceRefName () const inline override virtual
Implements MemberDef.
Definition at line 877 of file memberdef.cpp.
    { return getMdAlias()->sourceRefName(); }
References getMdAlias(), and MemberDef::sourceRefName().
templateArguments()
const ArgumentList & MemberDefAliasImpl::templateArguments () const inline override virtual
Implements MemberDef.
Definition at line 853 of file memberdef.cpp.
    { return getMdAlias()->templateArguments(); }
References getMdAlias(), and MemberDef::templateArguments().
templateMaster()
const MemberDef * MemberDefAliasImpl::templateMaster () const inline override virtual
Implements MemberDef.
Definition at line 883 of file memberdef.cpp.
    { return getMdAlias()->templateMaster(); }
References getMdAlias(), and MemberDef::templateMaster().
typeConstraints()
const ArgumentList & MemberDefAliasImpl::typeConstraints () const inline override virtual
Implements MemberDef.
Definition at line 915 of file memberdef.cpp.
    { return getMdAlias()->typeConstraints(); }
References getMdAlias(), and MemberDef::typeConstraints().
typeString()
QCString MemberDefAliasImpl::typeString () const inline override virtual
Implements MemberDef.
Definition at line 562 of file memberdef.cpp.
    { return getMdAlias()->typeString(); }
References getMdAlias(), and MemberDef::typeString().
virtualness()
Specifier MemberDefAliasImpl::virtualness (int) const inline override virtual
Implements MemberDef.
Definition at line 627 of file memberdef.cpp.
    { return getMdAlias()->virtualness(); }
References getMdAlias(), and MemberDef::virtualness().
visibleInIndex()
bool MemberDefAliasImpl::visibleInIndex () const inline override virtual
Implements MemberDef.
Definition at line 933 of file memberdef.cpp.
    { return getMdAlias()->visibleInIndex(); }
References getMdAlias(), and MemberDef::visibleInIndex().
warnIfUndocumented()
void MemberDefAliasImpl::warnIfUndocumented () const inline override virtual
Implements MemberDef.
Definition at line 936 of file memberdef.cpp.
{}
warnIfUndocumentedParams()
void MemberDefAliasImpl::warnIfUndocumentedParams () const inline override virtual
Implements MemberDef.
Definition at line 937 of file memberdef.cpp.
{}
writeDeclaration()
void MemberDefAliasImpl::writeDeclaration (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, const ModuleDef * mod, bool inGroup, int indentLevel, const ClassDef * inheritFrom = nullptr, const QCString & inheritId = QCString()) const inline override virtual
Implements MemberDef.
Definition at line 944 of file memberdef.cpp.
    {
      getMdAlias()->writeDeclaration(ol,cd,nd,fd,gd,mod,inGroup,indentLevel,inheritFrom,inheritId);
    }
References getMdAlias(), and MemberDef::writeDeclaration().
writeEnumDeclaration()
void MemberDefAliasImpl::writeEnumDeclaration (OutputList & typeDecl, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, const ModuleDef * mod) const inline override virtual
Implements MemberDef.
Definition at line 950 of file memberdef.cpp.
    {
      getMdAlias()->writeEnumDeclaration(typeDecl,cd,nd,fd,gd,mod);
    }
References getMdAlias(), and MemberDef::writeEnumDeclaration().
writeLink()
void MemberDefAliasImpl::writeLink (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, const ModuleDef * mod, bool onlyText = FALSE) const inline override virtual
Implements MemberDef.
Definition at line 955 of file memberdef.cpp.
    {
      getMdAlias()->writeLink(ol,cd,nd,fd,gd,mod,onlyText);
    }
References getMdAlias(), and MemberDef::writeLink().
Member Data Documentation
m_memberGroup
MemberGroup* MemberDefAliasImpl::m_memberGroup private
Definition at line 962 of file memberdef.cpp.
Referenced by getMemberGroup(), MemberDefAliasImpl(), and setMemberGroup().
The documentation for this class was generated from the following file:
src/memberdef.cpp