Doxygen: TextGeneratorOLImpl Class Reference
TextGeneratorOLImpl Class Reference
Implements TextGeneratorIntf for an OutputDocInterface stream.
#include <util.h>
Public Member Functions
TextGeneratorOLImpl (OutputList &ol)
void writeString (const QCString &s, bool keepSpaces) const
void writeBreak (int indent) const
void writeLink (const QCString &extRef, const QCString &file, const QCString &anchor, const QCString &text) const
Public Member Functions inherited from TextGeneratorIntf
virtual ~TextGeneratorIntf ()=default
Private Attributes
OutputList & m_ol
Detailed Description
Implements TextGeneratorIntf for an OutputDocInterface stream.
Definition at line 73 of file util.h.
Constructor & Destructor Documentation
TextGeneratorOLImpl()
TextGeneratorOLImpl::TextGeneratorOLImpl (OutputList & ol)
Definition at line 101 of file util.cpp.
                                                       : m_ol(ol)
{
}
Member Function Documentation
writeBreak()
void TextGeneratorOLImpl::writeBreak (int indent) const virtual
Implements TextGeneratorIntf.
Definition at line 130 of file util.cpp.
{
  m_ol.lineBreak("typebreak");
  int i;
  for (i=0;i<indent;i++)
  {
    m_ol.writeNonBreakableSpace(3);
  }
}
References OutputList::lineBreak(), m_ol, and OutputList::writeNonBreakableSpace().
writeLink()
void TextGeneratorOLImpl::writeLink (const QCString & extRef, const QCString & file, const QCString & anchor, const QCString & text) const virtual
Implements TextGeneratorIntf.
Definition at line 140 of file util.cpp.
{
  //printf("TextGeneratorOlImpl::writeLink('%s')\n",text);
  m_ol.writeObjectLink(extRef,file,anchor,text);
}
References m_ol, and OutputList::writeObjectLink().
writeString()
void TextGeneratorOLImpl::writeString (const QCString & s, bool keepSpaces) const virtual
Implements TextGeneratorIntf.
Definition at line 105 of file util.cpp.
{
  if (s.isEmpty()) return;
  //printf("TextGeneratorOlImpl::writeString('%s',%d)\n",s,keepSpaces);
  if (keepSpaces)
  {
    const char *p=s.data();
    if (p)
    {
      char cs[2];
      char c;
      cs[1]='\0';
      while ((c=*p++))
      {
        if (c==' ') m_ol.writeNonBreakableSpace(1);
        else cs[0]=c,m_ol.docify(cs);
      }
    }
  }
  else
  {
    m_ol.docify(s);
  }
}
References QCString::data(), OutputList::docify(), QCString::isEmpty(), m_ol, and OutputList::writeNonBreakableSpace().
Member Data Documentation
m_ol
OutputList& TextGeneratorOLImpl::m_ol private
Definition at line 83 of file util.h.
Referenced by writeBreak(), writeLink(), and writeString().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/util.h
/home/runner/work/doxygen/doxygen/src/util.cpp