Doxygen: ExampleTreeContext::Private Class Reference
ExampleTreeContext::Private Class Reference
Public Member Functions
Private ()
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
TemplateVariant title () const
int createMaxDepth () const
int createPreferredDepth () const
Private Attributes
TemplateListIntfPtr m_exampleTree
CachedItem< int, Private, &Private::createMaxDepth > m_maxDepth
CachedItem< int, Private, &Private::createPreferredDepth > m_preferredDepth
Static Private Attributes
static const PropertyMap< ExampleTreeContext::Private > s_inst
Detailed Description
Definition at line 6946 of file context.cpp.
Constructor & Destructor Documentation
Private()
ExampleTreeContext::Private::Private () inline
Definition at line 6949 of file context.cpp.
    {
      m_exampleTree = NestingContext::alloc(0,ContextTreeType::Example,0);
      auto ctx = std::dynamic_pointer_cast<NestingContext>(m_exampleTree);
      ClassDefSet visitedClasses;
      // Add pages
      ctx->addPages(*Doxygen::exampleLinkedMap,TRUE,visitedClasses);
    }
References NestingContext::alloc(), Example, Doxygen::exampleLinkedMap, m_exampleTree, and TRUE.
Member Function Documentation
createMaxDepth()
int ExampleTreeContext::Private::createMaxDepth () const inline private
Definition at line 6974 of file context.cpp.
    {
      return computeMaxDepth(m_exampleTree);
    }
References computeMaxDepth(), and m_exampleTree.
createPreferredDepth()
int ExampleTreeContext::Private::createPreferredDepth () const inline private
Definition at line 6978 of file context.cpp.
    {
      return computePreferredDepth(m_exampleTree,m_maxDepth.get(this));
    }
References computePreferredDepth(), m_exampleTree, and m_maxDepth.
fields()
StringVector ExampleTreeContext::Private::fields () const inline
Definition at line 6960 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fileName()
TemplateVariant ExampleTreeContext::Private::fileName () const inline private
Definition at line 6965 of file context.cpp.
{ return "examples"; }
get()
TemplateVariant ExampleTreeContext::Private::get (const QCString & n) const inline
Definition at line 6959 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), and s_inst.
highlight()
TemplateVariant ExampleTreeContext::Private::highlight () const inline private
Definition at line 6967 of file context.cpp.
{ return "examples"; }
maxDepth()
TemplateVariant ExampleTreeContext::Private::maxDepth () const inline private
Definition at line 6969 of file context.cpp.
{ return m_maxDepth.get(this); }
References m_maxDepth.
preferredDepth()
TemplateVariant ExampleTreeContext::Private::preferredDepth () const inline private
Definition at line 6970 of file context.cpp.
{ return m_preferredDepth.get(this); }
References m_preferredDepth.
relPath()
TemplateVariant ExampleTreeContext::Private::relPath () const inline private
Definition at line 6966 of file context.cpp.
{ return ""; }
subhighlight()
TemplateVariant ExampleTreeContext::Private::subhighlight () const inline private
Definition at line 6968 of file context.cpp.
{ return ""; }
title()
TemplateVariant ExampleTreeContext::Private::title () const inline private
Definition at line 6971 of file context.cpp.
{ return theTranslator->trExamples(); }
References theTranslator, and Translator::trExamples().
tree()
TemplateVariant ExampleTreeContext::Private::tree () const inline private
Definition at line 6964 of file context.cpp.
{ return TemplateVariant(m_exampleTree); }
References m_exampleTree.
Member Data Documentation
m_exampleTree
TemplateListIntfPtr ExampleTreeContext::Private::m_exampleTree private
Definition at line 6982 of file context.cpp.
Referenced by createMaxDepth(), createPreferredDepth(), Private(), and tree().
m_maxDepth
CachedItem<int, Private, &Private::createMaxDepth> ExampleTreeContext::Private::m_maxDepth private
Definition at line 6983 of file context.cpp.
Referenced by createPreferredDepth(), and maxDepth().
m_preferredDepth
CachedItem<int, Private, &Private::createPreferredDepth> ExampleTreeContext::Private::m_preferredDepth private
Definition at line 6984 of file context.cpp.
Referenced by preferredDepth().
s_inst
const PropertyMap< ExampleTreeContext::Private > ExampleTreeContext::Private::s_inst static private
Initial value:
{
  {  "tree",          &Private::tree },
  {  "fileName",      &Private::fileName },
  {  "relPath",       &Private::relPath },
  {  "highlight",     &Private::highlight },
  {  "subhighlight",  &Private::subhighlight },
  {  "title",         &Private::title },
  {  "preferredDepth",&Private::preferredDepth },
  {  "maxDepth",      &Private::maxDepth }
}
Definition at line 6985 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/context.cpp