Doxygen: src/classdef.h File Reference
classdef.h File Reference
#include <memory>
#include <vector>
#include <unordered_set>
#include "containers.h"
#include "definition.h"
#include "arguments.h"
#include "membergroup.h"
#include "configvalues.h"
Classes
struct BaseClassDef
Class that contains information about an inheritance relation.
struct TemplateInstanceDef
Class that contains information about a template instance relation.
class ClassDef
A abstract class representing of a compound symbol.
class ClassDefMutable
struct UsesClassDef
Class that contains information about a usage relation.
class UsesClassList
struct ConstraintClassDef
Class that contains information about a type constraint relations.
class ConstraintClassList
Typedefs
using BaseClassList = std::vector<BaseClassDef>
using TemplateInstanceList = std::vector<TemplateInstanceDef>
using TemplateNameMap = std::map<std::string,int>
using ClassDefSet = std::unordered_set<const ClassDef*>
Functions
std::unique_ptr< ClassDef > createClassDef (const QCString &fileName, int startLine, int startColumn, const QCString &name, ClassDef::CompoundType ct, const QCString &ref=QCString(), const QCString &fName=QCString(), bool isSymbol=TRUE, bool isJavaEnum=FALSE)
Factory method to create a new ClassDef object.
std::unique_ptr< ClassDef > createClassDefAlias (const Definition *newScope, const ClassDef *cd)
ClassDef * toClassDef (Definition *d)
ClassDef * toClassDef (DefinitionMutable *d)
const ClassDef * toClassDef (const Definition *d)
ClassDefMutable * toClassDefMutable (Definition *d)
ClassDef * getClass (const QCString &key)
ClassDefMutable * getClassMutable (const QCString &key)
bool classHasVisibleRoot (const BaseClassList &bcl)
bool classHasVisibleChildren (const ClassDef *cd)
bool classVisibleInIndex (const ClassDef *cd)
int minClassDistance (const ClassDef *cd, const ClassDef *bcd, int level=0)
Protection classInheritedProtectionLevel (const ClassDef *cd, const ClassDef *bcd, Protection prot=Protection::Public, int level=0)
Typedef Documentation
BaseClassList
using BaseClassList = std::vector<BaseClassDef>
Definition at line 81 of file classdef.h.
ClassDefSet
using ClassDefSet = std::unordered_set<const ClassDef*>
Definition at line 95 of file classdef.h.
TemplateInstanceList
using TemplateInstanceList = std::vector<TemplateInstanceDef>
Definition at line 91 of file classdef.h.
TemplateNameMap
using TemplateNameMap = std::map<std::string,int>
Definition at line 93 of file classdef.h.
Function Documentation
classHasVisibleChildren()
bool classHasVisibleChildren (const ClassDef * cd)
Definition at line 5383 of file classdef.cpp.
{
  BaseClassList bcl;
  if (cd->getLanguage()==SrcLangExt::VHDL) // reverse baseClass/subClass relation
  {
    if (cd->baseClasses().empty()) return FALSE;
    bcl=cd->baseClasses();
  }
  else
  {
    if (cd->subClasses().empty()) return FALSE;
    bcl=cd->subClasses();
  }
  for (const auto &bcd : bcl)
  {
    if (bcd.classDef->isVisibleInHierarchy())
    {
      return TRUE;
    }
  }
  return FALSE;
}
References ClassDef::baseClasses(), FALSE, Definition::getLanguage(), ClassDef::subClasses(), TRUE, and VHDL.
Referenced by writeClassTreeForList(), and writeClassTreeToOutput().
classHasVisibleRoot()
bool classHasVisibleRoot (const BaseClassList & bcl)
Definition at line 5372 of file classdef.cpp.
{
  for (const auto &bcd : bcl)
  {
    const ClassDef *cd=bcd.classDef;
    if (cd->isVisibleInHierarchy()) return true;
    if (classHasVisibleRoot(cd->baseClasses())) return true;
  }
  return false;
}
References ClassDef::baseClasses(), classHasVisibleRoot(), and ClassDef::isVisibleInHierarchy().
Referenced by DotGfxHierarchyTable::addClassList(), DotGfxHierarchyTable::addHierarchy(), classHasVisibleRoot(), countClassesInTreeList(), writeClassTreeForList(), and writeClassTreeToOutput().
classInheritedProtectionLevel()
Protection classInheritedProtectionLevel (const ClassDef * cd, const ClassDef * bcd, Protection prot = Protection::Public, int level = 0)
Definition at line 5443 of file classdef.cpp.
{
  if (bcd->categoryOf()) // use class that is being extended in case of
    // an Objective-C category
  {
    bcd=bcd->categoryOf();
  }
  if (cd==bcd)
  {
    goto exit;
  }
  if (level==256)
  {
    err("Internal inconsistency: found class %s seem to have a recursive "
        "inheritance relation! Please send a bug report to doxygen@gmail.com\n",qPrint(cd->name()));
  }
  else if (prot!=Protection::Private)
  {
    for (const auto &bcdi : cd->baseClasses())
    {
      Protection baseProt = classInheritedProtectionLevel(bcdi.classDef,bcd,bcdi.prot,level+1);
      if (baseProt==Protection::Private)        prot=Protection::Private;
      else if (baseProt==Protection::Protected) prot=Protection::Protected;
    }
  }
exit:
  //printf("classInheritedProtectionLevel(%s,%s)=%d\n",qPrint(cd->name()),qPrint(bcd->name()),prot);
  return prot;
}
References ClassDef::baseClasses(), ClassDef::categoryOf(), classInheritedProtectionLevel(), err, Definition::name(), Private, Protected, and qPrint().
Referenced by classInheritedProtectionLevel().
classVisibleInIndex()
bool classVisibleInIndex (const ClassDef * cd)
Definition at line 5408 of file classdef.cpp.
{
  bool allExternals = Config_getBool(ALLEXTERNALS);
  return (allExternals && cd->isLinkable()) || cd->isLinkableInProject();
}
References Config_getBool, Definition::isLinkable(), and Definition::isLinkableInProject().
Referenced by writeClassTree().
createClassDef()
std::unique_ptr< ClassDef > createClassDef (const QCString & fileName, int startLine, int startColumn, const QCString & name, ClassDef::CompoundType ct, const QCString & ref = QCString(), const QCString & fName = QCString(), bool isSymbol = TRUE, bool isJavaEnum = FALSE)
Factory method to create a new ClassDef object.
Definition at line 412 of file classdef.cpp.
{
  return std::make_unique<ClassDefImpl>(fileName,startLine,startColumn,name,ct,ref,fName,isSymbol,isJavaEnum);
}
Referenced by addClassToContext(), createTagLessInstance(), findClassRelation(), findUsedClassesForClass(), and findUsingDeclarations().
createClassDefAlias()
std::unique_ptr< ClassDef > createClassDefAlias (const Definition * newScope, const ClassDef * cd)
Definition at line 642 of file classdef.cpp.
{
  auto acd = std::make_unique<ClassDefAliasImpl>(newScope,cd);
  //printf("cd name=%s localName=%s qualifiedName=%s qualifiedNameWith=%s displayName()=%s\n",
  //    qPrint(acd->name()),qPrint(acd->localName()),qPrint(acd->qualifiedName()),
  //    qPrint(acd->qualifiedNameWithTemplateParameters()),qPrint(acd->displayName()));
  return acd;
}
Referenced by ClassDefAliasImpl::deepCopy(), findUsingDeclImports(), and resolveClassNestingRelations().
getClass()
ClassDef * getClass (const QCString & n)
Get a class definition given its name. Returns nullptr if the class is not found.
Definition at line 5366 of file classdef.cpp.
{
  if (n.isEmpty()) return nullptr;
  return Doxygen::classLinkedMap->find(n);
}
References Doxygen::classLinkedMap, LinkedMap< T, Hash, KeyEqual, Map >::find(), and QCString::isEmpty().
Referenced by buildScopeFromQualifiedName(), extractNamespaceName(), findClassWithinClassContext(), findEnumDocumentation(), findEnums(), findMember(), findUsingDeclarations(), generateClassOrGlobalLink(), generateClassOrGlobalLink(), generateMemberLink(), MemberDefImpl::getClassDefOfAnonymousType(), getClassMutable(), getScopeDefs(), getTemplateArgumentsFromName(), DocParser::handleLinkedWord(), if(), insertTemplateSpecifierInScope(), MemberDefImpl::isDocumentedFriendClass(), SymbolResolver::resolveClass(), resolveLink(), resolveRef(), setCallContextForVar(), stripTemplateSpecifiersFromScope(), and MemberDefImpl::writeDeclaration().
getClassMutable()
ClassDefMutable * getClassMutable (const QCString & key) inline
Definition at line 467 of file classdef.h.
{
  return toClassDefMutable(getClass(key));
}
References getClass(), and toClassDefMutable().
Referenced by addClassToContext(), addEnumValuesToEnums(), addLocalObjCMethod(), addVariableToFile(), computeClassRelations(), computeTemplateClassRelations(), findClassRelation(), findEnums(), findInheritedTemplateInstances(), findMember(), findUsedTemplateInstances(), findUsingDeclImports(), and makeTemplateInstanceRelation().
minClassDistance()
int minClassDistance (const ClassDef * cd, const ClassDef * bcd, int level = 0)
Definition at line 5418 of file classdef.cpp.
{
  const int maxInheritanceDepth = 100000;
  if (bcd->categoryOf()) // use class that is being extended in case of
    // an Objective-C category
  {
    bcd=bcd->categoryOf();
  }
  if (cd==bcd) return level;
  if (level==256)
  {
    warn_uncond("class %s seem to have a recursive "
        "inheritance relation!\n",qPrint(cd->name()));
    return -1;
  }
  int m=maxInheritanceDepth;
  for (const auto &bcdi : cd->baseClasses())
  {
    int mc=minClassDistance(bcdi.classDef,bcd,level+1);
    if (mc<m) m=mc;
    if (m<0) break;
  }
  return m;
}
References ClassDef::baseClasses(), ClassDef::categoryOf(), maxInheritanceDepth, minClassDistance(), Definition::name(), qPrint(), and warn_uncond.
Referenced by getDefsOld(), ClassDefImpl::getMemberByName(), and minClassDistance().
toClassDef() [1/3]
const ClassDef * toClassDef (const Definition * d)
Definition at line 5337 of file classdef.cpp.
{
  if (d && (typeid(*d)==typeid(ClassDefImpl) || typeid(*d)==typeid(ClassDefAliasImpl)))
  {
    return static_cast<const ClassDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
References ClassDefImpl::ClassDefImpl().
toClassDef() [2/3]
ClassDef * toClassDef (Definition * d)
Definition at line 5312 of file classdef.cpp.
{
  if (d && (typeid(*d)==typeid(ClassDefImpl) || typeid(*d)==typeid(ClassDefAliasImpl)))
  {
    return static_cast<ClassDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
References ClassDefImpl::ClassDefImpl().
Referenced by DocSets::addIndexItem(), ClassDefImpl::addInnerCompound(), NamespaceDefImpl::addInnerCompound(), MemberDefImpl::addListReference(), definitionToName(), findMemberLink(), findModuleDef(), findUsingDeclImports(), SymbolResolver::Private::followPath(), generateClassMemberLink(), generateClassOrGlobalLink(), generateClassOrGlobalLink(), FTVHelp::Private::generateTree(), ClassDefAliasImpl::getCdAlias(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedType(), SymbolResolver::Private::getResolvedTypeRec(), ClassDefImpl::getTemplateParameterLists(), SymbolResolver::Private::isAccessibleFrom(), SymbolResolver::Private::isAccessibleFromWithExpScope(), makeQualifiedNameWithTemplateParameters(), MemberDefImpl::moveTo(), scopeIsTemplate(), searchTemplateSpecs(), SearchIndex::setCurrentDoc(), updateCallContextForSmartPointer(), writeDefArgumentList(), writeJavasScriptSearchDataPage(), MemberDefImpl::writeMemberDocSimple(), writeObjCMethodCall(), MemberList::writeSimpleDocumentation(), and VhdlDocGen::writeVHDLTypeDocumentation().
toClassDef() [3/3]
ClassDef * toClassDef (DefinitionMutable * d)
Definition at line 5324 of file classdef.cpp.
{
  Definition *d = toDefinition(md);
  if (d && typeid(*d)==typeid(ClassDefImpl))
  {
    return static_cast<ClassDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
References ClassDefImpl::ClassDefImpl(), and DefinitionMutable::toDefinition.
toClassDefMutable()
ClassDefMutable * toClassDefMutable (Definition * d)
Definition at line 5349 of file classdef.cpp.
{
  if (d && typeid(*d)==typeid(ClassDefImpl))
  {
    return static_cast<ClassDefMutable*>(d);
  }
  else
  {
    return nullptr;
  }
}
References ClassDefImpl::ClassDefImpl().
Referenced by addClassAndNestedClasses(), addClassToContext(), addClassToGroups(), ModuleDefImpl::addClassToModule(), ModuleManager::addClassToModule(), addListReferences(), addMembersToMemberGroup(), ClassDefImpl::addMembersToTemplateInstance(), addMemberToGroups(), ClassDefImpl::addTypeConstraint(), buildCompleteMemberLists(), computeMemberReferences(), computeTemplateClassRelations(), VhdlDocGen::computeVhdlComponentRelations(), ClassDefImpl::countInheritedDecMembers(), countMembers(), createTagLessInstance(), createTemplateInstanceMembers(), ClassDefImpl::deepCopy(), distributeClassGroupRelations(), distributeMemberGroupDocumentation(), findClassRelation(), findSectionsInDocumentation(), findTagLessClasses(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsingDeclarations(), findUsingDeclImports(), generateClassDocs(), generateClassOrGlobalLink(), generateNamespaceClassDocs(), MemberDefImpl::getClassDefMutable(), getClassMutable(), insertMemberAlias(), ClassDefImpl::insertTemplateInstance(), ClassDefImpl::insertUsedFile(), mergeCategories(), ClassDefImpl::mergeCategory(), ClassDefImpl::mergeMembers(), ClassDefImpl::mergeMembersFromBaseClasses(), SymbolResolver::resolveClassMutable(), resolveClassNestingRelations(), setAnonymousEnumType(), ClassDefImpl::setGroupDefForAllMembers(), sortMemberLists(), ClassDefImpl::writeInheritedMemberDeclarations(), and writeTagFile().