Doxygen: DocIncOperator Class Reference
DocIncOperator Class Reference
Node representing a include/dontinclude operator block.
#include <src/docnode.h>
Public Types
enum Type { Line , SkipLine , Skip , Until }
Public Member Functions
DocIncOperator (DocParser *parser, DocNodeVariant *parent, Type t, const QCString &pat, const QCString &context, bool stripCodeComments, bool isExample, const QCString &exampleFile)
Type type () const
const char * typeAsString () const
int line () const
bool showLineNo () const
QCString text () const
QCString pattern () const
QCString context () const
bool isFirst () const
bool isLast () const
void markFirst (bool v=TRUE)
void markLast (bool v=TRUE)
bool stripCodeComments () const
bool isExample () const
QCString exampleFile () const
QCString includeFileName () const
void parse ()
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
Type m_type = Line
int m_line = 0
bool m_showLineNo = false
QCString m_text
QCString m_pattern
QCString m_context
bool m_isFirst = false
bool m_isLast = false
bool m_stripCodeComments = true
bool m_isExample = false
QCString m_exampleFile
QCString m_includeFileName
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a include/dontinclude operator block.
Definition at line 456 of file docnode.h.
Member Enumeration Documentation
Type
enum DocIncOperator::Type
Enumerator
Line
SkipLine
Skip
Until
Definition at line 459 of file docnode.h.
{ Line, SkipLine, Skip, Until };
Constructor & Destructor Documentation
DocIncOperator()
DocIncOperator::DocIncOperator (DocParser * parser, DocNodeVariant * parent, Type t, const QCString & pat, const QCString & context, bool stripCodeComments, bool isExample, const QCString & exampleFile) inline
Definition at line 460 of file docnode.h.
    : DocNode(parser,parent), m_type(t), m_pattern(pat), m_context(context),
      m_isFirst(FALSE), m_isLast(FALSE), m_stripCodeComments(stripCodeComments),
      m_isExample(isExample), m_exampleFile(exampleFile) {}
References context(), DocNode::DocNode(), exampleFile(), isExample(), m_context, m_exampleFile, m_isExample, m_isFirst, m_isLast, m_pattern, m_stripCodeComments, m_type, DocNode::parent(), DocNode::parser(), and stripCodeComments().
Member Function Documentation
context()
QCString DocIncOperator::context () const inline
Definition at line 481 of file docnode.h.
{ return m_context; }
References m_context.
Referenced by DocIncOperator(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and parse().
exampleFile()
QCString DocIncOperator::exampleFile () const inline
Definition at line 488 of file docnode.h.
{ return m_exampleFile; }
References m_exampleFile.
Referenced by DocIncOperator(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
includeFileName()
QCString DocIncOperator::includeFileName () const inline
Definition at line 489 of file docnode.h.
{ return m_includeFileName; }
References m_includeFileName.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
isExample()
bool DocIncOperator::isExample () const inline
Definition at line 487 of file docnode.h.
{ return m_isExample; }
References m_isExample.
Referenced by DocIncOperator(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
isFirst()
bool DocIncOperator::isFirst () const inline
Definition at line 482 of file docnode.h.
{ return m_isFirst; }
References m_isFirst.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
isLast()
bool DocIncOperator::isLast () const inline
Definition at line 483 of file docnode.h.
{ return m_isLast; }
References m_isLast.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
line()
int DocIncOperator::line () const inline
Definition at line 477 of file docnode.h.
{ return m_line; }
References m_line.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
markFirst()
void DocIncOperator::markFirst (bool v = TRUE) inline
Definition at line 484 of file docnode.h.
{ m_isFirst = v; }
References m_isFirst.
markLast()
void DocIncOperator::markLast (bool v = TRUE) inline
Definition at line 485 of file docnode.h.
{ m_isLast = v; }
References m_isLast.
Referenced by DocPara::handleIncludeOperator().
parse()
void DocIncOperator::parse ()
Definition at line 317 of file docnode.cpp.
{
  if (parser()->context.includeFileName.isEmpty())
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),
                   "No previous '\\include' or '\\dontinclude' command for '\\%s' present",
                   typeAsString());
  }
  bool found = false;
  m_includeFileName = parser()->context.includeFileName;
  const char *p = parser()->context.includeFileText.data();
  size_t l = parser()->context.includeFileLength;
  size_t o = parser()->context.includeFileOffset;
  int il = parser()->context.includeFileLine;
  AUTO_TRACE("text={} off={} len={}",Trace::trunc(p),o,l);
  size_t so = o, bo = 0;
  bool nonEmpty = FALSE;
  switch(type())
  {
    case Line:
      while (o<l)
      {
        char c = p[o];
        if (c=='\n')
        {
          parser()->context.includeFileLine++;
          if (nonEmpty) break; // we have a pattern to match
          so=o+1; // no pattern, skip empty line
        }
        else if (!isspace(static_cast<uint8_t>(c))) // no white space char
        {
          nonEmpty=TRUE;
        }
        o++;
      }
      if (parser()->context.includeFileText.mid(so,o-so).find(m_pattern)!=-1)
      {
        m_line  = il;
        m_text = parser()->context.includeFileText.mid(so,o-so);
        found = true;
        AUTO_TRACE_ADD("\\line {}",Trace::trunc(m_text));
      }
      parser()->context.includeFileOffset = std::min(l,o+1); // set pointer to start of new line
      m_showLineNo = parser()->context.includeFileShowLineNo;
      m_stripCodeComments = parser()->context.stripCodeComments;
      break;
    case SkipLine:
      while (o<l)
      {
        so=o;
        while (o<l)
        {
          char c = p[o];
          if (c=='\n')
          {
            parser()->context.includeFileLine++;
            if (nonEmpty) break; // we have a pattern to match
            so=o+1; // no pattern, skip empty line
          }
          else if (!isspace(static_cast<uint8_t>(c))) // no white space char
          {
            nonEmpty=TRUE;
          }
          o++;
        }
        if (parser()->context.includeFileText.mid(so,o-so).find(m_pattern)!=-1)
        {
          m_line  = il;
          m_text = parser()->context.includeFileText.mid(so,o-so);
          found = true;
          AUTO_TRACE_ADD("\\skipline {}",Trace::trunc(m_text));
          break;
        }
        o++; // skip new line
      }
      parser()->context.includeFileOffset = std::min(l,o+1); // set pointer to start of new line
      m_showLineNo = parser()->context.includeFileShowLineNo;
      m_stripCodeComments = parser()->context.stripCodeComments;
      break;
    case Skip:
      while (o<l)
      {
        so=o;
        while (o<l)
        {
          char c = p[o];
          if (c=='\n')
          {
            parser()->context.includeFileLine++;
            if (nonEmpty) break; // we have a pattern to match
            so=o+1; // no pattern, skip empty line
          }
          else if (!isspace(static_cast<uint8_t>(c))) // no white space char
          {
            nonEmpty=TRUE;
          }
          o++;
        }
        if (parser()->context.includeFileText.mid(so,o-so).find(m_pattern)!=-1)
        {
        found = true;
          break;
        }
        o++; // skip new line
      }
      parser()->context.includeFileOffset = so; // set pointer to start of new line
      m_showLineNo = parser()->context.includeFileShowLineNo;
      m_stripCodeComments = parser()->context.stripCodeComments;
      break;
    case Until:
      bo=o;
      while (o<l)
      {
        so=o;
        while (o<l)
        {
          char c = p[o];
          if (c=='\n')
          {
            parser()->context.includeFileLine++;
            if (nonEmpty) break; // we have a pattern to match
            so=o+1; // no pattern, skip empty line
          }
          else if (!isspace(static_cast<uint8_t>(c))) // no white space char
          {
            nonEmpty=TRUE;
          }
          o++;
        }
        if (parser()->context.includeFileText.mid(so,o-so).find(m_pattern)!=-1)
        {
          m_line  = il;
          m_text = parser()->context.includeFileText.mid(bo,o-bo);
          found = true;
          AUTO_TRACE_ADD("\\until {}",Trace::trunc(m_text));
          break;
        }
        o++; // skip new line
      }
      parser()->context.includeFileOffset = std::min(l,o+1); // set pointer to start of new line
      m_showLineNo = parser()->context.includeFileShowLineNo;
      m_stripCodeComments = parser()->context.stripCodeComments;
      break;
  }
  if (!found)
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),
      "referenced pattern '%s' for command '\\%s' not found",qPrint(m_pattern),typeAsString());
  }
}
References AUTO_TRACE, AUTO_TRACE_ADD, context(), DocParser::context, QCString::data(), FALSE, found, DocParserContext::includeFileLength, DocParserContext::includeFileLine, DocParserContext::includeFileName, DocParserContext::includeFileOffset, DocParserContext::includeFileShowLineNo, DocParserContext::includeFileText, Line, m_includeFileName, m_line, m_pattern, m_showLineNo, m_stripCodeComments, m_text, QCString::mid(), DocNode::parser(), qPrint(), Skip, SkipLine, DocParserContext::stripCodeComments, TRUE, Trace::trunc(), type(), typeAsString(), Until, and warn_doc_error.
pattern()
QCString DocIncOperator::pattern () const inline
Definition at line 480 of file docnode.h.
{ return m_pattern; }
References m_pattern.
Referenced by PrintDocVisitor::operator()().
showLineNo()
bool DocIncOperator::showLineNo () const inline
Definition at line 478 of file docnode.h.
{ return m_showLineNo; }
References m_showLineNo.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
stripCodeComments()
bool DocIncOperator::stripCodeComments () const inline
Definition at line 486 of file docnode.h.
{ return m_stripCodeComments; }
References m_stripCodeComments.
Referenced by DocIncOperator(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
text()
QCString DocIncOperator::text () const inline
Definition at line 479 of file docnode.h.
{ return m_text; }
References m_text.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
type()
Type DocIncOperator::type () const inline
Definition at line 465 of file docnode.h.
{ return m_type; }
References m_type.
Referenced by isDocIncOperatorVisible(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and parse().
typeAsString()
const char * DocIncOperator::typeAsString () const inline
Definition at line 466 of file docnode.h.
    {
      switch(m_type)
      {
        case Line:     return "line";
        case SkipLine: return "skipline";
        case Skip:     return "skip";
        case Until:    return "until";
      }
      return "";
    }
References Line, m_type, Skip, SkipLine, and Until.
Referenced by parse().
Member Data Documentation
m_context
QCString DocIncOperator::m_context private
Definition at line 498 of file docnode.h.
Referenced by context(), and DocIncOperator().
m_exampleFile
QCString DocIncOperator::m_exampleFile private
Definition at line 503 of file docnode.h.
Referenced by DocIncOperator(), and exampleFile().
m_includeFileName
QCString DocIncOperator::m_includeFileName private
Definition at line 504 of file docnode.h.
Referenced by includeFileName(), and parse().
m_isExample
bool DocIncOperator::m_isExample = false private
Definition at line 502 of file docnode.h.
Referenced by DocIncOperator(), and isExample().
m_isFirst
bool DocIncOperator::m_isFirst = false private
Definition at line 499 of file docnode.h.
Referenced by DocIncOperator(), isFirst(), and markFirst().
m_isLast
bool DocIncOperator::m_isLast = false private
Definition at line 500 of file docnode.h.
Referenced by DocIncOperator(), isLast(), and markLast().
m_line
int DocIncOperator::m_line = 0 private
Definition at line 494 of file docnode.h.
Referenced by line(), and parse().
m_pattern
QCString DocIncOperator::m_pattern private
Definition at line 497 of file docnode.h.
Referenced by DocIncOperator(), parse(), and pattern().
m_showLineNo
bool DocIncOperator::m_showLineNo = false private
Definition at line 495 of file docnode.h.
Referenced by parse(), and showLineNo().
m_stripCodeComments
bool DocIncOperator::m_stripCodeComments = true private
Definition at line 501 of file docnode.h.
Referenced by DocIncOperator(), parse(), and stripCodeComments().
m_text
QCString DocIncOperator::m_text private
Definition at line 496 of file docnode.h.
Referenced by parse(), and text().
m_type
Type DocIncOperator::m_type = Line private
Definition at line 493 of file docnode.h.
Referenced by DocIncOperator(), type(), and typeAsString().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp