Doxygen: DocSecRefList Class Reference
DocSecRefList Class Reference
Node representing a list of section references.
#include <docnode.h>
Public Member Functions
DocSecRefList (DocParser *parser, DocNodeVariant *parent)
void parse ()
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
DocNode (const DocNode &)=delete
DocNode & operator= (const DocNode &)=delete
DocNode (DocNode &&)=default
DocNode & operator= (DocNode &&)=default
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a list of section references.
Definition at line 920 of file docnode.h.
Constructor & Destructor Documentation
DocSecRefList()
DocSecRefList::DocSecRefList (DocParser * parser, DocNodeVariant * parent) inline
Definition at line 923 of file docnode.h.
: DocCompoundNode(parser,parent) {}
Member Function Documentation
parse()
void DocSecRefList::parse ()
Definition at line 598 of file docnode.cpp.
{
  AUTO_TRACE();
  auto ns = AutoNodeStack(parser(),thisVariant());
  int tok=parser()->tokenizer.lex();
  // skip white space
  while (tok==TK_WHITESPACE || tok==TK_NEWPARA) tok=parser()->tokenizer.lex();
  // handle items
  while (tok)
  {
    if (tok==TK_COMMAND_AT || tok == TK_COMMAND_BS)
    {
      const char *cmd_start = (tok==TK_COMMAND_AT ? "@" : "\\");
      switch (Mappers::cmdMapper->map(parser()->context.token->name))
      {
        case CMD_SECREFITEM:
          {
            tok=parser()->tokenizer.lex();
            if (tok!=TK_WHITESPACE)
            {
              warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected whitespace after \\refitem command");
              break;
            }
            tok=parser()->tokenizer.lex();
            if (tok!=TK_WORD && tok!=TK_LNKWORD)
            {
              warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected token %s as the argument of \\refitem",
                  DocTokenizer::tokToString(tok));
              break;
            }
            children().append<DocSecRefItem>(parser(),thisVariant(),parser()->context.token->name);
            children().get_last<DocSecRefItem>()->parse();
          }
          break;
        case CMD_ENDSECREFLIST:
          return;
        default:
          warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Illegal command %s as part of a \\secreflist",
              qPrint(cmd_start + parser()->context.token->name));
          return;
      }
    }
    else if (tok==TK_WHITESPACE)
    {
      // ignore whitespace
    }
    else
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected token %s inside section reference list",
          DocTokenizer::tokToString(tok));
      return;
    }
    tok=parser()->tokenizer.lex();
  }
}
References DocNodeList::append(), AUTO_TRACE, DocCompoundNode::children(), CMD_ENDSECREFLIST, CMD_SECREFITEM, Mappers::cmdMapper, DocParser::context, DocNodeList::get_last(), DocTokenizer::lex(), TokenInfo::name, parse(), DocNode::parser(), qPrint(), DocNode::thisVariant(), TK_COMMAND_AT, TK_COMMAND_BS, TK_LNKWORD, TK_NEWPARA, TK_WHITESPACE, TK_WORD, DocParserContext::token, DocParser::tokenizer, DocTokenizer::tokToString(), and warn_doc_error.
Referenced by parse().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/docnode.h
/home/runner/work/doxygen/doxygen/src/docnode.cpp