Doxygen: DocHtmlRow Class Reference
DocHtmlRow Class Reference
Node representing a HTML table row.
#include <src/docnode.h>
Public Member Functions
DocHtmlRow (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
size_t numCells () const
const HtmlAttribList & attribs () const
Token parse ()
Token parseXml (bool header)
bool isHeading () const
void setVisibleCells (uint32_t n)
uint32_t visibleCells () const
uint32_t rowIndex () const
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Member Functions
void setRowIndex (uint32_t idx)
Private Attributes
HtmlAttribList m_attribs
uint32_t m_visibleCells = 0
uint32_t m_rowIdx = static_cast<uint32_t>(-1)
Friends
class DocHtmlTable
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a HTML table row.
Definition at line 1224 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlRow()
DocHtmlRow::DocHtmlRow (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) inline
Definition at line 1228 of file docnode.h.
      : DocCompoundNode(parser,parent), m_attribs(attribs) {}
References attribs(), DocCompoundNode::DocCompoundNode(), m_attribs, DocNode::parent(), and DocNode::parser().
Member Function Documentation
attribs()
const HtmlAttribList & DocHtmlRow::attribs () const inline
Definition at line 1231 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by DocHtmlRow(), DocbookDocVisitor::operator()(), and HtmlDocVisitor::operator()().
isHeading()
bool DocHtmlRow::isHeading () const
Definition at line 1880 of file docnode.cpp.
{ // a row is a table heading if all cells are marked as such
  bool heading=TRUE;
  for (const auto &n : children())
  {
    const DocHtmlCell *cell = std::get_if<DocHtmlCell>(&n);
    if (cell && !cell->isHeading())
    {
      heading = FALSE;
      break;
    }
  }
  return !children().empty() && heading;
}
References DocCompoundNode::children(), GrowVector< T >::empty(), FALSE, DocHtmlCell::isHeading(), and TRUE.
Referenced by DocbookDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), parse(), and parseXml().
numCells()
size_t DocHtmlRow::numCells () const inline
Definition at line 1230 of file docnode.h.
{ return children().size(); }
References DocCompoundNode::children(), and GrowVector< T >::size().
Referenced by RTFDocVisitor::operator()().
parse()
Token DocHtmlRow::parse ()
Definition at line 1895 of file docnode.cpp.
{
  AUTO_TRACE();
  Token retval = Token::make_RetVal_OK();
  auto ns = AutoNodeStack(parser(),thisVariant());
  bool isHeading=FALSE;
  bool isFirst=TRUE;
  DocHtmlCell *cell=nullptr;
  // get next token
  Token tok=parser()->tokenizer.lex();
  // skip whitespace
  while (tok.is_any_of(TokenRetval::TK_WHITESPACE,TokenRetval::TK_NEWPARA)) tok=parser()->tokenizer.lex();
  // should find a html tag now
  if (tok.is(TokenRetval::TK_HTMLTAG))
  {
    HtmlTagType tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
    if (tagId==HtmlTagType::HTML_TD && !parser()->context.token->endTag) // found <td> tag
    {
    }
    else if (tagId==HtmlTagType::HTML_TH && !parser()->context.token->endTag) // found <th> tag
    {
      isHeading=TRUE;
    }
    else // found some other tag
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <td> or <th> tag but "
          "found <%s> instead!",qPrint(parser()->context.token->name));
      parser()->tokenizer.pushBackHtmlTag(parser()->context.token->name);
      goto endrow;
    }
  }
  else if (tok.is_any_of(TokenRetval::TK_NONE,TokenRetval::TK_EOF)) // premature end of comment
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment while looking"
        " for a html description title");
    goto endrow;
  }
  else // token other than html token
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <td> or <th> tag but found %s token instead!",
        tok.to_string());
    goto endrow;
  }
  // parse one or more cells
  do
  {
    children().append<DocHtmlCell>(parser(),thisVariant(),
                                            parser()->context.token->attribs,
                                            isHeading);
    cell = children().get_last<DocHtmlCell>();
    cell->markFirst(isFirst);
    isFirst=FALSE;
    retval=cell->parse();
    isHeading = retval.is(TokenRetval::RetVal_TableHCell);
  }
  while (retval.is_any_of(TokenRetval::RetVal_TableCell,TokenRetval::RetVal_TableHCell));
  cell->markLast(TRUE);
endrow:
  return retval;
}
References DocNodeList::append(), TokenInfo::attribs, AUTO_TRACE, DocCompoundNode::children(), DocParser::context, FALSE, DocNodeList::get_last(), HTML_TD, HTML_TH, Mappers::htmlTagMapper, Token::is(), Token::is_any_of(), isHeading(), DocTokenizer::lex(), DocHtmlCell::markFirst(), DocHtmlCell::markLast(), DocHtmlCell::parse(), DocNode::parser(), DocTokenizer::pushBackHtmlTag(), qPrint(), DocNode::thisVariant(), Token::to_string(), DocParserContext::token, DocParser::tokenizer, TRUE, and warn_doc_error.
parseXml()
Token DocHtmlRow::parseXml (bool header)
Definition at line 1960 of file docnode.cpp.
{
  AUTO_TRACE();
  Token retval = Token::make_RetVal_OK();
  auto ns = AutoNodeStack(parser(),thisVariant());
  bool isFirst=TRUE;
  DocHtmlCell *cell=nullptr;
  // get next token
  Token tok=parser()->tokenizer.lex();
  // skip whitespace
  while (tok.is_any_of(TokenRetval::TK_WHITESPACE,TokenRetval::TK_NEWPARA)) tok=parser()->tokenizer.lex();
  // should find a html tag now
  if (tok.is(TokenRetval::TK_HTMLTAG))
  {
    HtmlTagType tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
    if (tagId==HtmlTagType::XML_TERM && !parser()->context.token->endTag) // found <term> tag
    {
    }
    else if (tagId==HtmlTagType::XML_DESCRIPTION && !parser()->context.token->endTag) // found <description> tag
    {
    }
    else // found some other tag
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <term> or <description> tag but "
          "found <%s> instead!",qPrint(parser()->context.token->name));
      parser()->tokenizer.pushBackHtmlTag(parser()->context.token->name);
      goto endrow;
    }
  }
  else if (tok.is_any_of(TokenRetval::TK_NONE,TokenRetval::TK_EOF)) // premature end of comment
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment while looking"
        " for a html description title");
    goto endrow;
  }
  else // token other than html token
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <td> or <th> tag but found %s token instead!",
        tok.to_string());
    goto endrow;
  }
  do
  {
    children().append<DocHtmlCell>(parser(),thisVariant(),parser()->context.token->attribs,isHeading);
    cell = children().get_last<DocHtmlCell>();
    cell->markFirst(isFirst);
    isFirst=FALSE;
    retval=cell->parseXml();
  }
  while (retval.is_any_of(TokenRetval::RetVal_TableCell,TokenRetval::RetVal_TableHCell));
  cell->markLast(TRUE);
endrow:
  return retval;
}
References DocNodeList::append(), TokenInfo::attribs, AUTO_TRACE, DocCompoundNode::children(), DocParser::context, FALSE, DocNodeList::get_last(), Mappers::htmlTagMapper, Token::is(), Token::is_any_of(), isHeading(), DocTokenizer::lex(), DocHtmlCell::markFirst(), DocHtmlCell::markLast(), DocNode::parser(), DocHtmlCell::parseXml(), DocTokenizer::pushBackHtmlTag(), qPrint(), DocNode::thisVariant(), Token::to_string(), DocParserContext::token, DocParser::tokenizer, TRUE, warn_doc_error, XML_DESCRIPTION, and XML_TERM.
rowIndex()
uint32_t DocHtmlRow::rowIndex () const inline
Definition at line 1237 of file docnode.h.
{ return m_rowIdx; }
References m_rowIdx.
Referenced by LatexDocVisitor::operator()().
setRowIndex()
void DocHtmlRow::setRowIndex (uint32_t idx) inline private
Definition at line 1240 of file docnode.h.
{ m_rowIdx = idx; }
References m_rowIdx.
Referenced by DocHtmlTable::computeTableGrid().
setVisibleCells()
void DocHtmlRow::setVisibleCells (uint32_t n) inline
Definition at line 1235 of file docnode.h.
{ m_visibleCells = n; }
References m_visibleCells.
Referenced by DocHtmlTable::computeTableGrid().
visibleCells()
uint32_t DocHtmlRow::visibleCells () const inline
Definition at line 1236 of file docnode.h.
{ return m_visibleCells; }
References m_visibleCells.
Friends And Related Symbol Documentation
DocHtmlTable
friend class DocHtmlTable friend
Definition at line 1226 of file docnode.h.
References DocHtmlTable.
Referenced by DocHtmlTable.
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlRow::m_attribs private
Definition at line 1241 of file docnode.h.
Referenced by attribs(), and DocHtmlRow().
m_rowIdx
uint32_t DocHtmlRow::m_rowIdx = static_cast<uint32_t>(-1) private
Definition at line 1243 of file docnode.h.
Referenced by rowIndex(), and setRowIndex().
m_visibleCells
uint32_t DocHtmlRow::m_visibleCells = 0 private
Definition at line 1242 of file docnode.h.
Referenced by setVisibleCells(), and visibleCells().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp