Doxygen: LayoutParser Class Reference
LayoutParser Class Reference
Public Member Functions
void setDocumentLocator (const XMLLocator *locator)
void error (const std::string &fileName, int lineNr, const std::string &msg)
void startElement (const std::string &name, const XMLHandlers::Attributes &attrib)
void endElement (const std::string &name)
void startSimpleEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes &attrib)
void startSectionEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes &attrib, const QCString &title)
void startMemberDeclEntry (const XMLHandlers::Attributes &attrib, MemberListType type, const QCString &title, const QCString &subscript)
void startMemberDefEntry (const XMLHandlers::Attributes &attrib, MemberListType type, const QCString &title, const QCString &)
void startLayout (const XMLHandlers::Attributes &)
void startNavIndex (const XMLHandlers::Attributes &)
void endNavIndex ()
void startNavEntry (const XMLHandlers::Attributes &attrib)
void endNavEntry ()
void recurseNavEntryChildren (LayoutNavEntry &lne)
void startTop (const XMLHandlers::Attributes &attrib, LayoutDocManager::LayoutPart part, const QCString &scope, LayoutNavEntry::Kind nav)
void endTop ()
void startMemberDef (const XMLHandlers::Attributes &attrib)
void endMemberDef ()
void startMemberDecl (const XMLHandlers::Attributes &attrib)
void endMemberDecl ()
Static Public Member Functions
static LayoutParser & instance ()
Private Attributes
QCString m_scope
LayoutDocManager::LayoutPart m_part = LayoutDocManager::Undefined
LayoutNavEntry * m_rootNav = nullptr
bool m_invalidEntry = false
bool m_visible = true
const XMLLocator * m_locator = nullptr
Static Private Attributes
static int m_userGroupCount =0
Detailed Description
Definition at line 183 of file layout.cpp.
Member Function Documentation
endElement()
void LayoutParser::endElement (const std::string & name)
Definition at line 1366 of file layout.cpp.
{
  //printf("endElement [%s]::[%s]\n",qPrint(m_scope),qPrint(name));
  auto it=g_elementHandlers.end();
  if (!m_scope.isEmpty() && m_scope.right(name.length()+1)==name+"/")
  { // element ends current scope
    it = g_elementHandlers.find(m_scope.left(m_scope.length()-1).str());
  }
  else // continue with current scope
  {
    it = g_elementHandlers.find(m_scope.str()+name);
  }
  if (it!=g_elementHandlers.end())
  {
    it->second.endCb(*this);
  }
}
References anonymous_namespace{layout.cpp}::g_elementHandlers, and m_scope.
Referenced by LayoutDocManager::init(), and LayoutDocManager::parse().
endMemberDecl()
void LayoutParser::endMemberDecl () inline
Definition at line 682 of file layout.cpp.
    {
      int i=m_scope.findRev("memberdecl/");
      if (i!=-1)
      {
        m_scope=m_scope.left(i);
        if (m_part!=LayoutDocManager::Undefined)
        {
          bool isVisible = true;
          for (const auto &lde : LayoutDocManager::instance().docEntries(m_part))
          {
            if (lde->kind() == LayoutDocEntry::MemberDeclStart)
            {
               isVisible = static_cast<const LayoutDocEntrySimple*>(lde.get())->visible();
            }
          }
          LayoutDocManager::instance().addEntry(m_part,std::make_unique<LayoutDocEntrySimple>(LayoutDocEntry::MemberDeclEnd,isVisible));
        }
      }
    }
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), m_part, and m_scope.
endMemberDef()
void LayoutParser::endMemberDef () inline
Definition at line 650 of file layout.cpp.
    {
      QCString scopeOrg = m_scope;
      int i=m_scope.findRev("memberdef/");
      if (i!=-1)
      {
        m_scope=m_scope.left(i);
        if (m_part!=LayoutDocManager::Undefined)
        {
          bool isVisible = true;
          for (const auto &lde : LayoutDocManager::instance().docEntries(m_part))
          {
            if (lde->kind() == LayoutDocEntry::MemberDefStart)
            {
               isVisible = static_cast<const LayoutDocEntrySimple*>(lde.get())->visible();
            }
          }
          LayoutDocManager::instance().addEntry(m_part,std::make_unique<LayoutDocEntrySimple>(LayoutDocEntry::MemberDefEnd,isVisible));
        }
      }
    }
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), m_part, and m_scope.
endNavEntry()
void LayoutParser::endNavEntry () inline
Definition at line 601 of file layout.cpp.
    {
      // set the root back to the parent
      if (m_rootNav && !m_invalidEntry) m_rootNav = m_rootNav->parent();
      m_invalidEntry=FALSE;
    }
References FALSE, m_invalidEntry, and m_rootNav.
endNavIndex()
void LayoutParser::endNavIndex () inline
Definition at line 271 of file layout.cpp.
    {
      m_scope="";
      if (m_rootNav && !m_rootNav->find(LayoutNavEntry::MainPage))
      {
        // no MainPage node... add one as the first item of the root node...
        m_rootNav->prependChild(std::make_unique<LayoutNavEntry>(m_rootNav,LayoutNavEntry::MainPage, TRUE,
                                                   "index",theTranslator->trMainPage(),""));
      }
    }
References m_rootNav, m_scope, theTranslator, Translator::trMainPage(), and TRUE.
endTop()
void LayoutParser::endTop () inline
Definition at line 634 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, and m_scope.
error()
void LayoutParser::error (const std::string & fileName, int lineNr, const std::string & msg) inline
Definition at line 197 of file layout.cpp.
    {
      warn(fileName.c_str(),lineNr,"%s",msg.c_str());
    }
References msg(), and warn.
Referenced by LayoutDocManager::init(), and LayoutDocManager::parse().
instance()
static LayoutParser & LayoutParser::instance () inline static
Definition at line 186 of file layout.cpp.
    {
      static LayoutParser theInstance;
      return theInstance;
    }
Referenced by LayoutDocManager::init(), and LayoutDocManager::parse().
recurseNavEntryChildren()
void LayoutParser::recurseNavEntryChildren (LayoutNavEntry & lne) inline
Definition at line 608 of file layout.cpp.
    {
      bool vis = lne.visible();
      for (const auto &lne1 : lne.children())
      {
        lne1->setVisible(vis && lne1->visible());
        recurseNavEntryChildren(*lne1);
      }
    }
References LayoutNavEntry::children(), recurseNavEntryChildren(), and LayoutNavEntry::visible().
Referenced by recurseNavEntryChildren(), and startTop().
setDocumentLocator()
void LayoutParser::setDocumentLocator (const XMLLocator * locator) inline
Definition at line 193 of file layout.cpp.
    {
      m_locator = locator;
    }
References m_locator.
Referenced by LayoutDocManager::init(), and LayoutDocManager::parse().
startElement()
void LayoutParser::startElement (const std::string & name, const XMLHandlers::Attributes & attrib)
Definition at line 1350 of file layout.cpp.
{
  //printf("startElement [%s]::[%s]\n",qPrint(m_scope),qPrint(name));
  auto it = g_elementHandlers.find(m_scope.str()+name);
  if (it!=g_elementHandlers.end())
  {
    it->second.startCb(*this,attrib);
  }
  else
  {
    std::string fileName = m_locator->fileName();
    warn(fileName.c_str(),m_locator->lineNr(),"Unexpected start tag '%s' found in scope='%s'!",
        qPrint(name),qPrint(m_scope));
  }
}
References anonymous_namespace{layout.cpp}::g_elementHandlers, m_locator, m_scope, qPrint(), and warn.
Referenced by LayoutDocManager::init(), and LayoutDocManager::parse().
startLayout()
void LayoutParser::startLayout (const XMLHandlers::Attributes &) inline
Definition at line 257 of file layout.cpp.
    {
    }
startMemberDecl()
void LayoutParser::startMemberDecl (const XMLHandlers::Attributes & attrib) inline
Definition at line 672 of file layout.cpp.
    {
      m_scope+="memberdecl/";
      if (m_part!=LayoutDocManager::Undefined)
      {
        bool isVisible = m_visible && elemIsVisible(attrib) && parentIsVisible(m_rootNav);
        LayoutDocManager::instance().addEntry(m_part,std::make_unique<LayoutDocEntrySimple>(LayoutDocEntry::MemberDeclStart,isVisible));
      }
    }
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), m_part, m_rootNav, m_scope, m_visible, and parentIsVisible().
startMemberDeclEntry()
void LayoutParser::startMemberDeclEntry (const XMLHandlers::Attributes & attrib, MemberListType type, const QCString & title, const QCString & subscript) inline
Definition at line 230 of file layout.cpp.
    {
      QCString userTitle     = XMLHandlers::value(attrib,"title");
      QCString userSubscript = XMLHandlers::value(attrib,"subtitle");
      if (userTitle.isEmpty())     userTitle     = title;
      if (userSubscript.isEmpty()) userSubscript = subscript;
      bool isVisible = m_visible && elemIsVisible(attrib) && parentIsVisible(m_rootNav);
      if (m_part!=LayoutDocManager::Undefined && isVisible)
      {
        LayoutDocManager::instance().addEntry(m_part,std::make_unique<LayoutDocEntryMemberDecl>(type,userTitle,userSubscript));
      }
    }
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), QCString::isEmpty(), m_part, m_rootNav, m_visible, parentIsVisible(), and XMLHandlers::value().
startMemberDef()
void LayoutParser::startMemberDef (const XMLHandlers::Attributes & attrib) inline
Definition at line 640 of file layout.cpp.
    {
      m_scope+="memberdef/";
      if (m_part!=LayoutDocManager::Undefined)
      {
        bool isVisible = m_visible && elemIsVisible(attrib) && parentIsVisible(m_rootNav);
        LayoutDocManager::instance().addEntry(m_part,std::make_unique<LayoutDocEntrySimple>(LayoutDocEntry::MemberDefStart,isVisible));
      }
    }
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), m_part, m_rootNav, m_scope, m_visible, and parentIsVisible().
startMemberDefEntry()
void LayoutParser::startMemberDefEntry (const XMLHandlers::Attributes & attrib, MemberListType type, const QCString & title, const QCString &) inline
Definition at line 244 of file layout.cpp.
    {
      QCString userTitle = XMLHandlers::value(attrib,"title");
      if (userTitle.isEmpty()) userTitle = title;
      //printf("memberdef: %s\n",qPrint(userTitle));
      bool isVisible = m_visible && elemIsVisible(attrib) && parentIsVisible(m_rootNav);
      if (m_part!=LayoutDocManager::Undefined && isVisible)
      {
        LayoutDocManager::instance().addEntry(m_part,std::make_unique<LayoutDocEntryMemberDef>(type,userTitle));
      }
    }
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), QCString::isEmpty(), m_part, m_rootNav, m_visible, parentIsVisible(), and XMLHandlers::value().
startNavEntry()
void LayoutParser::startNavEntry (const XMLHandlers::Attributes & attrib) inline
Definition at line 282 of file layout.cpp.
    {
      bool javaOpt    = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
      bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
      bool vhdlOpt    = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      bool sliceOpt   = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      bool hasGraphicalHierarchy = Config_getBool(HAVE_DOT) &&
                                          Config_getBool(GRAPHICAL_HIERARCHY);
      bool extractAll = Config_getBool(EXTRACT_ALL);
      static struct NavEntryMap
      {
        const char *typeStr;       // type attribute name in the XML file
        LayoutNavEntry::Kind kind; // corresponding enum name
        QCString mainName;         // default title for an item if it has children
        QCString subName;          // optional name for an item if it is rendered as a child
        QCString intro;            // introduction text to be put on the index page
        QCString baseFile;         // base name of the file containing the index page
      } mapping[] =
      {
        { "mainpage",
          LayoutNavEntry::MainPage,
          theTranslator->trMainPage(),
          QCString(),
          QCString(),
          "index"
        },
        { "pages",
          LayoutNavEntry::Pages,
          theTranslator->trRelatedPages(),
          QCString(),
          theTranslator->trRelatedPagesDescription(),
          "pages"
        },
        { "topics",
          LayoutNavEntry::Topics,
          theTranslator->trTopics(),
          QCString(),
          theTranslator->trTopicListDescription(),
          "topics"
        },
        { "modules",
          LayoutNavEntry::Modules,
          theTranslator->trModules(),
          theTranslator->trModulesList(),
          theTranslator->trModulesDescription(),
          "modules"
        },
        { "modulelist",
          LayoutNavEntry::ModuleList,
          theTranslator->trModulesList(),
          QCString(),
          theTranslator->trModulesListDescription(extractAll),
          "modules"
        },
        { "modulemembers",
          LayoutNavEntry::ModuleMembers,
          theTranslator->trModulesMembers(),
          QCString(),
          theTranslator->trModulesMemberDescription(extractAll),
          "modulemembers"
        },
        { "namespaces",
          LayoutNavEntry::Namespaces,
          javaOpt || vhdlOpt   ? theTranslator->trPackages() : fortranOpt || sliceOpt ? theTranslator->trModules() : theTranslator->trNamespaces(),
          javaOpt || vhdlOpt   ? theTranslator->trPackageList() : fortranOpt || sliceOpt ? theTranslator->trModulesList() : theTranslator->trNamespaceList(),
          javaOpt || vhdlOpt   ? theTranslator->trPackageListDescription() : fortranOpt || sliceOpt ? theTranslator->trModulesListDescription(extractAll) : theTranslator->trNamespaceListDescription(extractAll),
          "namespaces"
        },
        { "namespacelist",
          LayoutNavEntry::NamespaceList,
          javaOpt || vhdlOpt   ? theTranslator->trPackageList() : fortranOpt || sliceOpt ? theTranslator->trModulesList() : theTranslator->trNamespaceList(),
          QCString(),
          javaOpt || vhdlOpt   ? theTranslator->trPackageListDescription() : fortranOpt || sliceOpt ? theTranslator->trModulesListDescription(extractAll) : theTranslator->trNamespaceListDescription(extractAll),
          "namespaces"
        },
        { "namespacemembers",
          LayoutNavEntry::NamespaceMembers,
          javaOpt || vhdlOpt   ? theTranslator->trPackageMembers() : fortranOpt || sliceOpt ? theTranslator->trModulesMembers() : theTranslator->trNamespaceMembers(),
          QCString(),
          fortranOpt || sliceOpt ? theTranslator->trModulesMemberDescription(extractAll) : theTranslator->trNamespaceMemberDescription(extractAll),
          "namespacemembers"
        },
        { "concepts",
          LayoutNavEntry::Concepts,
          theTranslator->trConcept(true,false),
          theTranslator->trConceptList(),
          theTranslator->trConceptListDescription(extractAll),
          "concepts"
        },
        { "classindex",
          LayoutNavEntry::ClassIndex,
          fortranOpt ? theTranslator->trCompoundIndexFortran() : vhdlOpt ? theTranslator->trDesignUnitIndex() : theTranslator->trCompoundIndex(),
          QCString(),
          QCString(),
          "classes"
        },
        { "classes",
          LayoutNavEntry::Classes,
          fortranOpt ? theTranslator->trDataTypes() : vhdlOpt ? theTranslator->trDesignUnits() : theTranslator->trClasses(),
          theTranslator->trCompoundList(),
          fortranOpt ? theTranslator->trCompoundListDescriptionFortran() : vhdlOpt ? theTranslator->trDesignUnitListDescription() : theTranslator->trCompoundListDescription(),
          "annotated"
        },
        { "classlist",
          LayoutNavEntry::ClassList,
          fortranOpt ? theTranslator->trCompoundListFortran() : vhdlOpt ? theTranslator->trDesignUnitList() : theTranslator->trCompoundList(),
          QCString(),
          fortranOpt ? theTranslator->trCompoundListDescriptionFortran() : vhdlOpt ? theTranslator->trDesignUnitListDescription() : theTranslator->trCompoundListDescription(),
          "annotated"
        },
        { "hierarchy",
          LayoutNavEntry::ClassHierarchy,
          vhdlOpt    ? theTranslator->trDesignUnitHierarchy() : theTranslator->trClassHierarchy(),
          QCString(),
          theTranslator->trClassHierarchyDescription(),
          hasGraphicalHierarchy ? "inherits" : "hierarchy"
        },
        { "classmembers",
          LayoutNavEntry::ClassMembers,
          fortranOpt ? theTranslator->trCompoundMembersFortran() : vhdlOpt ? theTranslator->trDesignUnitMembers() : theTranslator->trCompoundMembers(),
          QCString(),
          fortranOpt ? theTranslator->trCompoundMembersDescriptionFortran(extractAll) : theTranslator->trCompoundMembersDescription(extractAll),
          "functions"
        },
        { "interfaceindex",
          LayoutNavEntry::InterfaceIndex,
          theTranslator->trInterfaceIndex(),
          QCString(),
          QCString(),
          "interfaces"
        },
        { "interfaces",
          LayoutNavEntry::Interfaces,
          theTranslator->trSliceInterfaces(),
          theTranslator->trInterfaceList(),
          theTranslator->trInterfaceListDescription(),
          "annotatedinterfaces"
        },
        { "interfacelist",
          LayoutNavEntry::InterfaceList,
          theTranslator->trInterfaceList(),
          QCString(),
          theTranslator->trInterfaceListDescription(),
          "annotatedinterfaces"
        },
        { "interfacehierarchy",
          LayoutNavEntry::InterfaceHierarchy,
          theTranslator->trInterfaceHierarchy(),
          QCString(),
          theTranslator->trInterfaceHierarchyDescription(),
          hasGraphicalHierarchy ? "interfaceinherits" : "interfacehierarchy"
        },
        { "structindex",
          LayoutNavEntry::StructIndex,
          theTranslator->trStructIndex(),
          QCString(),
          QCString(),
          "structs"
        },
        { "structs",
          LayoutNavEntry::Structs,
          theTranslator->trStructs(),
          theTranslator->trStructList(),
          theTranslator->trStructListDescription(),
          "annotatedstructs"
        },
        { "structlist",
          LayoutNavEntry::StructList,
          theTranslator->trStructList(),
          QCString(),
          theTranslator->trStructListDescription(),
          "annotatedstructs"
        },
        { "exceptionindex",
          LayoutNavEntry::ExceptionIndex,
          theTranslator->trExceptionIndex(),
          QCString(),
          QCString(),
          "exceptions"
        },
        { "exceptions",
          LayoutNavEntry::Exceptions,
          theTranslator->trExceptions(),
          theTranslator->trExceptionList(),
          theTranslator->trExceptionListDescription(),
          "annotatedexceptions"
        },
        { "exceptionlist",
          LayoutNavEntry::ExceptionList,
          theTranslator->trExceptionList(),
          QCString(),
          theTranslator->trExceptionListDescription(),
          "annotatedexceptions"
        },
        { "exceptionhierarchy",
          LayoutNavEntry::ExceptionHierarchy,
          theTranslator->trExceptionHierarchy(),
          QCString(),
          theTranslator->trExceptionHierarchyDescription(),
          hasGraphicalHierarchy ? "exceptioninherits" : "exceptionhierarchy"
        },
        { "files",
          LayoutNavEntry::Files,
          theTranslator->trFile(TRUE,FALSE),
          theTranslator->trFileList(),
          theTranslator->trFileListDescription(extractAll),
          "files"
        },
        { "filelist",
          LayoutNavEntry::FileList,
          theTranslator->trFileList(),
          QCString(),
          theTranslator->trFileListDescription(extractAll),
          "files"
        },
        { "globals",
          LayoutNavEntry::FileGlobals,
          theTranslator->trFileMembers(),
          QCString(),
          theTranslator->trFileMembersDescription(extractAll),
          "globals"
        },
        { "examples",
          LayoutNavEntry::Examples,
          theTranslator->trExamples(),
          QCString(),
          theTranslator->trExamplesDescription(),
          "examples"
        },
        { "user",
          LayoutNavEntry::User,
          QCString(),
          QCString(),
          QCString(),
          "user"
        },
        { "usergroup",
          LayoutNavEntry::UserGroup,
          QCString(),
          QCString(),
          QCString(),
          "usergroup"
        },
        { nullptr, // end of list
          static_cast<LayoutNavEntry::Kind>(0),
          QCString(),
          QCString(),
          QCString(),
          QCString()
        }
      };
      // find type in the table
      int i=0;
      QCString type = XMLHandlers::value(attrib,"type");
      while (mapping[i].typeStr)
      {
        if (mapping[i].typeStr==type)
          break;
        i++;
      }
      if (mapping[i].typeStr==nullptr)
      {
        std::string fileName = m_locator->fileName();
        if (type.isEmpty())
        {
          warn(fileName.c_str(),m_locator->lineNr(),"an entry tag within a navindex has no type attribute! Check your layout file!");
        }
        else
        {
          warn(fileName.c_str(),m_locator->lineNr(),"the type '%s' is not supported for the entry tag within a navindex! Check your layout file!",qPrint(type));
        }
        m_invalidEntry=TRUE;
        return;
      }
      LayoutNavEntry::Kind kind = mapping[i].kind;
      QCString baseFile = mapping[i].baseFile;
      QCString title = XMLHandlers::value(attrib,"title");
      bool isVisible = m_visible && elemIsVisible(attrib) && parentIsVisible(m_rootNav);
      if (title.isEmpty()) // use default title
      {
        title = mapping[i].mainName; // use title for main row
        if (m_rootNav!=LayoutDocManager::instance().rootNavEntry() && !mapping[i].subName.isEmpty())
        {
          title = mapping[i].subName; // if this is a child of another row, use the subName if available
                                      // this is mainly done to get compatible naming with older versions.
        }
      }
      QCString intro = XMLHandlers::value(attrib,"intro");
      if (intro.isEmpty()) // use default intro text
      {
        intro = mapping[i].intro;
      }
      QCString url = XMLHandlers::value(attrib,"url");
      if (mapping[i].kind==LayoutNavEntry::User && !url.isEmpty())
      {
        baseFile=url;
      }
      else if (kind==LayoutNavEntry::UserGroup)
      {
        if (!url.isEmpty())
        {
          if (url == "[none]")
          {
            baseFile = QCString();
          }
          else
          {
            baseFile=url;
          }
        }
        else
        {
          baseFile+=QCString().sprintf("%d",m_userGroupCount++);
        }
      }
      // create new item and make it the new root
      m_rootNav = LayoutDocManager::instance().createChildNavEntry(m_rootNav,kind,isVisible,baseFile,title,intro);
    }
References Config_getBool, LayoutDocManager::createChildNavEntry(), elemIsVisible(), FALSE, LayoutDocManager::instance(), QCString::isEmpty(), m_invalidEntry, m_locator, m_rootNav, m_userGroupCount, m_visible, parentIsVisible(), qPrint(), QCString::sprintf(), theTranslator, Translator::trClasses(), Translator::trClassHierarchy(), Translator::trClassHierarchyDescription(), Translator::trCompoundIndex(), Translator::trCompoundIndexFortran(), Translator::trCompoundList(), Translator::trCompoundListDescription(), Translator::trCompoundListDescriptionFortran(), Translator::trCompoundListFortran(), Translator::trCompoundMembers(), Translator::trCompoundMembersDescription(), Translator::trCompoundMembersDescriptionFortran(), Translator::trCompoundMembersFortran(), Translator::trConcept(), Translator::trConceptList(), Translator::trConceptListDescription(), Translator::trDataTypes(), Translator::trDesignUnitHierarchy(), Translator::trDesignUnitIndex(), Translator::trDesignUnitList(), Translator::trDesignUnitListDescription(), Translator::trDesignUnitMembers(), Translator::trDesignUnits(), Translator::trExamples(), Translator::trExamplesDescription(), Translator::trExceptionHierarchy(), Translator::trExceptionHierarchyDescription(), Translator::trExceptionIndex(), Translator::trExceptionList(), Translator::trExceptionListDescription(), Translator::trExceptions(), Translator::trFile(), Translator::trFileList(), Translator::trFileListDescription(), Translator::trFileMembers(), Translator::trFileMembersDescription(), Translator::trInterfaceHierarchy(), Translator::trInterfaceHierarchyDescription(), Translator::trInterfaceIndex(), Translator::trInterfaceList(), Translator::trInterfaceListDescription(), Translator::trMainPage(), Translator::trModules(), Translator::trModulesDescription(), Translator::trModulesList(), Translator::trModulesListDescription(), Translator::trModulesMemberDescription(), Translator::trModulesMembers(), Translator::trNamespaceList(), Translator::trNamespaceListDescription(), Translator::trNamespaceMemberDescription(), Translator::trNamespaceMembers(), Translator::trNamespaces(), Translator::trPackageList(), Translator::trPackageListDescription(), Translator::trPackageMembers(), Translator::trPackages(), Translator::trRelatedPages(), Translator::trRelatedPagesDescription(), Translator::trSliceInterfaces(), Translator::trStructIndex(), Translator::trStructList(), Translator::trStructListDescription(), Translator::trStructs(), Translator::trTopicListDescription(), Translator::trTopics(), TRUE, XMLHandlers::value(), and warn.
startNavIndex()
void LayoutParser::startNavIndex (const XMLHandlers::Attributes &) inline
Definition at line 261 of file layout.cpp.
    {
      m_scope="navindex/";
      m_rootNav = LayoutDocManager::instance().rootNavEntry();
      if (m_rootNav)
      {
        m_rootNav->clear();
      }
    }
References LayoutDocManager::instance(), m_rootNav, m_scope, and LayoutDocManager::rootNavEntry().
startSectionEntry()
void LayoutParser::startSectionEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes & attrib, const QCString & title) inline
Definition at line 215 of file layout.cpp.
    {
      bool isVisible = m_visible && elemIsVisible(attrib) && parentIsVisible(m_rootNav);
      QCString userTitle = XMLHandlers::value(attrib,"title");
      //printf("startSectionEntry: title='%s' userTitle='%s'\n",
      //    qPrint(title),qPrint(userTitle));
      if (userTitle.isEmpty())  userTitle = title;
      if (m_part!=LayoutDocManager::Undefined && isVisible)
      {
        LayoutDocManager::instance().addEntry(m_part,std::make_unique<LayoutDocEntrySection>(k,userTitle,isVisible));
      }
    }
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), QCString::isEmpty(), m_part, m_rootNav, m_visible, parentIsVisible(), and XMLHandlers::value().
startSimpleEntry()
void LayoutParser::startSimpleEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes & attrib) inline
Definition at line 204 of file layout.cpp.
    {
      bool isVisible = m_visible && elemIsVisible(attrib) && parentIsVisible(m_rootNav);
      if (m_part!=LayoutDocManager::Undefined && isVisible)
      {
        LayoutDocManager::instance().addEntry(m_part,std::make_unique<LayoutDocEntrySimple>(k,isVisible));
      }
    }
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), m_part, m_rootNav, m_visible, and parentIsVisible().
startTop()
void LayoutParser::startTop (const XMLHandlers::Attributes & attrib, LayoutDocManager::LayoutPart part, const QCString & scope, LayoutNavEntry::Kind nav) inline
Definition at line 618 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(part);
      m_scope = scope;
      m_part = part;
      m_visible = elemIsVisible(attrib);
      auto *lne = LayoutDocManager::instance().rootNavEntry()->find(nav);
      if (lne)
      {
        m_visible = m_visible && lne->visible();
        lne->setVisible(m_visible);
        recurseNavEntryChildren(*lne);
      }
    }
References LayoutDocManager::clear(), elemIsVisible(), LayoutNavEntry::find(), LayoutDocManager::instance(), m_part, m_scope, m_visible, recurseNavEntryChildren(), and LayoutDocManager::rootNavEntry().
Member Data Documentation
m_invalidEntry
bool LayoutParser::m_invalidEntry = false private
Definition at line 707 of file layout.cpp.
Referenced by endNavEntry(), and startNavEntry().
m_locator
const XMLLocator* LayoutParser::m_locator = nullptr private
Definition at line 710 of file layout.cpp.
Referenced by setDocumentLocator(), startElement(), and startNavEntry().
m_part
LayoutDocManager::LayoutPart LayoutParser::m_part = LayoutDocManager::Undefined private
Definition at line 705 of file layout.cpp.
Referenced by endMemberDecl(), endMemberDef(), endTop(), startMemberDecl(), startMemberDeclEntry(), startMemberDef(), startMemberDefEntry(), startSectionEntry(), startSimpleEntry(), and startTop().
m_rootNav
LayoutNavEntry* LayoutParser::m_rootNav = nullptr private
Definition at line 706 of file layout.cpp.
Referenced by endNavEntry(), endNavIndex(), startMemberDecl(), startMemberDeclEntry(), startMemberDef(), startMemberDefEntry(), startNavEntry(), startNavIndex(), startSectionEntry(), and startSimpleEntry().
m_scope
QCString LayoutParser::m_scope private
Definition at line 704 of file layout.cpp.
Referenced by endElement(), endMemberDecl(), endMemberDef(), endNavIndex(), endTop(), startElement(), startMemberDecl(), startMemberDef(), startNavIndex(), and startTop().
m_userGroupCount
int LayoutParser::m_userGroupCount =0 static private
Definition at line 709 of file layout.cpp.
Referenced by startNavEntry().
m_visible
bool LayoutParser::m_visible = true private
Definition at line 708 of file layout.cpp.
Referenced by startMemberDecl(), startMemberDeclEntry(), startMemberDef(), startMemberDefEntry(), startNavEntry(), startSectionEntry(), startSimpleEntry(), and startTop().
The documentation for this class was generated from the following file:
src/layout.cpp