Doxygen: TranslatorNorwegian Class Reference
TranslatorNorwegian Class Reference
#include <src/translator_no.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trEnumerationValueDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trInterfaces () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
Public Member Functions inherited from TranslatorAdapter_1_4_6
QCString updateNeededMessage () override
QCString trCallerGraph () override
Public Member Functions inherited from TranslatorAdapter_1_6_0
QCString updateNeededMessage () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
Public Member Functions inherited from TranslatorAdapter_1_7_5
QCString updateNeededMessage () override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Public Member Functions inherited from TranslatorAdapter_1_8_0
QCString updateNeededMessage () override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 46 of file translator_no.h.
Member Function Documentation
getLanguageString()
QCString TranslatorNorwegian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 82 of file translator_no.h.
    {
      return "0x814 Norwegian";
    }
idLanguage()
QCString TranslatorNorwegian::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 58 of file translator_no.h.
    { return "norwegian"; }
latexLanguageSupportCommand()
QCString TranslatorNorwegian::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 72 of file translator_no.h.
    {
      return
        "\\usepackage[norsk]{babel}\n";
    }
trAll()
QCString TranslatorNorwegian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1388 of file translator_no.h.
    {
      return "Alle";
    }
trAttention()
QCString TranslatorNorwegian::trAttention () inline override virtual
Implements Translator.
Definition at line 969 of file translator_no.h.
    {
      return "Viktig";
    }
trAuthor()
QCString TranslatorNorwegian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1261 of file translator_no.h.
    {
      return createNoun(first_capital, singular, "forfatter", "e");
    }
References Translator::createNoun().
trBug()
QCString TranslatorNorwegian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1133 of file translator_no.h.
    {
      return "Feil";
    }
trBugList()
QCString TranslatorNorwegian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1138 of file translator_no.h.
    {
      return "Feil-liste";
    }
trCallGraph()
QCString TranslatorNorwegian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1393 of file translator_no.h.
    {
      return "Her er kall-grafen for denne funksjonen:";
    }
trClass()
QCString TranslatorNorwegian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1196 of file translator_no.h.
    {
      return createNoun(first_capital, singular, "klasse", "r");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorNorwegian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 522 of file translator_no.h.
    {
      return "Arvediagram for "+clName+":";
    }
trClassDocumentation()
QCString TranslatorNorwegian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 397 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturdokumentasjon";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassedokumentasjon";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorNorwegian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1096 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorNorwegian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 181 of file translator_no.h.
    { return "Klassehierarki"; }
trClassHierarchyDescription()
QCString TranslatorNorwegian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 240 of file translator_no.h.
    { return "Denne arvelisten er grovsortert alfabetisk "
             "(ikke ndvendigvis korrekt):";
    }
trCode()
QCString TranslatorNorwegian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 869 of file translator_no.h.
    {
      return "kode";
    }
trCollaborationDiagram()
QCString TranslatorNorwegian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 823 of file translator_no.h.
    {
      return "Samarbeidsdiagram for "+clName+":";
    }
trCompoundIndex()
QCString TranslatorNorwegian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 370 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturindeks";
      }
      else
      {
        return "Klasseindeks";
      }
    }
References Config_getBool.
trCompoundList()
QCString TranslatorNorwegian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 185 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasseliste";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorNorwegian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 255 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Her er datastrukturene med korte beskrivelser:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Her er klasser med korte beskrivelser:";
      }
      else
      {
        return "Her er klasser, struct'er, "
               "unioner og interface'er med korte beskrivelser:";
      }
    }
References Config_getBool.
trCompoundMembers()
QCString TranslatorNorwegian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 202 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datafelt";
      }
      else
      {
        return "Klassemedlemmer";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorNorwegian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 274 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll)
      {
        result+="dokumenterte ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct- og unionfelter";
      }
      else
      {
        result+="klassemedlemmer";
      }
      result+=" med koblinger til ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struct/union dokumentasjon for hvert felt:";
        }
        else
        {
          result+="klassedokumentasjonen for hvert medlem:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struct'ene/unionene de hrer til:";
        }
        else
        {
          result+="klassene de hrer til:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundReference()
QCString TranslatorNorwegian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 597 of file translator_no.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Klasse"; break;
        case ClassDef::Struct:     result+=" Struct"; break;
        case ClassDef::Union:      result+=" Union"; break;
        case ClassDef::Interface:  result+=" Grensesnitt"; break;
        case ClassDef::Exception:  result+=" Unntak"; break;
        case ClassDef::Protocol:   result+=" Protocol"; break;
        case ClassDef::Category:   result+=" Category"; break;
        default: break;
      }
      if (isTemplate) result+=" Mal";
      result+=" Referanse";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorNorwegian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 498 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorNorwegian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 834 of file translator_no.h.
    {
      return "Konstruktr- & destruktr-dokumentasjon";
    }
trDate()
QCString TranslatorNorwegian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 536 of file translator_no.h.
    { return "Dato"; }
trDayOfWeek()
QCString TranslatorNorwegian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1502 of file translator_no.h.
    {
      static const char *days_short[]   = { "m.", "ty.", "on.", "to.", "fr.", "la.", "s." };
      static const char *days_full[]    = { "mndag", "tysdag", "onsdag", "torsdag", "fredag", "laurdag", "sndag" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorNorwegian::trDayPeriod (bool period) inline override virtual
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1518 of file translator_no.h.
    {
      static const char *dayPeriod[] = { "f.m.", "e.m." };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorNorwegian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 800 of file translator_no.h.
    {
      return "Definisjon p linje @0 i filen @1.";
    }
trDefinedIn()
QCString TranslatorNorwegian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 169 of file translator_no.h.
    { return "definert i"; }
trDefinedInSourceFile()
QCString TranslatorNorwegian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 804 of file translator_no.h.
    {
      return "Definisjon i filen @0.";
    }
trDefineDocumentation()
QCString TranslatorNorwegian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 462 of file translator_no.h.
    { return "Define-dokumentasjon"; }
trDefines()
QCString TranslatorNorwegian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 426 of file translator_no.h.
    { return "Definisjoner"; }
trDefineValue()
QCString TranslatorNorwegian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1123 of file translator_no.h.
    {
      return "Verdi:";
    }
trDeprecated()
QCString TranslatorNorwegian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 813 of file translator_no.h.
    {
      return "Foreldet";
    }
trDeprecatedList()
QCString TranslatorNorwegian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1316 of file translator_no.h.
    {
      return "Liste over foreldede enheter";
    }
trDetailedDescription()
QCString TranslatorNorwegian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 98 of file translator_no.h.
    { return "Detaljert beskrivelse"; }
trDetails()
QCString TranslatorNorwegian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 102 of file translator_no.h.
    { return "Detaljar"; }
trDir()
QCString TranslatorNorwegian::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1483 of file translator_no.h.
    {
      return createNoun(first_capital, singular, "katalog", "er");
    }
References Translator::createNoun().
trDirDocumentation()
QCString TranslatorNorwegian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1465 of file translator_no.h.
    { return "Katalogdokumentasjon"; }
trDirectories()
QCString TranslatorNorwegian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1471 of file translator_no.h.
    { return "Kataloger"; }
trDirIndex()
QCString TranslatorNorwegian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1459 of file translator_no.h.
    { return "Katalog hierarki"; }
trDirReference()
QCString TranslatorNorwegian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1477 of file translator_no.h.
    { QCString result=dirName; result+=" Katalog referanse"; return result; }
trDocumentation()
QCString TranslatorNorwegian::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 352 of file translator_no.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentasjon"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorNorwegian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 438 of file translator_no.h.
    { return "Enumerasjoner"; }
trEnumerationTypeDocumentation()
QCString TranslatorNorwegian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 474 of file translator_no.h.
    { return "Enumerasjontype dokumentasjon"; }
trEnumerationValueDocumentation()
QCString TranslatorNorwegian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Reimplemented from TranslatorAdapter_1_4_6.
Definition at line 480 of file translator_no.h.
    { return "Enumerasjonsverdi dokumentasjon"; }
trEnumerationValues()
QCString TranslatorNorwegian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 456 of file translator_no.h.
    { return "Enumerasjonsverdier"; }
trEnumName()
QCString TranslatorNorwegian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 161 of file translator_no.h.
    { return "enum-navn"; }
trEnumValue()
QCString TranslatorNorwegian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 165 of file translator_no.h.
    { return "enum-verdi"; }
trEventDocumentation()
QCString TranslatorNorwegian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1333 of file translator_no.h.
    {
      return "Hendelsesdokumentasjon";
    }
trEvents()
QCString TranslatorNorwegian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1328 of file translator_no.h.
    {
      return "Hendelser";
    }
trExamples()
QCString TranslatorNorwegian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 232 of file translator_no.h.
    { return "Eksempler"; }
trExamplesDescription()
QCString TranslatorNorwegian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 337 of file translator_no.h.
    { return "Her er en liste over alle eksemplene:"; }
trExceptions()
QCString TranslatorNorwegian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 552 of file translator_no.h.
    { return "Unntak"; }
trFile()
QCString TranslatorNorwegian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1205 of file translator_no.h.
    {
      return createNoun(first_capital, singular, "fil", "er");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorNorwegian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 416 of file translator_no.h.
    { return "Fildokumentasjon"; }
trFileIndex()
QCString TranslatorNorwegian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 385 of file translator_no.h.
    { return "Filindeks"; }
trFileList()
QCString TranslatorNorwegian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 198 of file translator_no.h.
    { return "Fil-liste"; }
trFileListDescription()
QCString TranslatorNorwegian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 246 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      result+="filer med korte beskrivelser:";
      return result;
    }
trFileMembers()
QCString TranslatorNorwegian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 215 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globale";
      }
      else
      {
        return "Filmedlemmer";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorNorwegian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 315 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funksjoner, variabler, definisjoner, enum'er, og typedef'er";
      }
      else
      {
        result+="filmedlemmer";
      }
      result+=" med koblinger til ";
      if (extractAll)
        result+="filene de hrer til:";
      else
        result+="dokumentasjonen:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorNorwegian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 619 of file translator_no.h.
    {
      QCString result=fileName;
      result+=" filreferanse";
      return result;
    }
trFriends()
QCString TranslatorNorwegian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 579 of file translator_no.h.
    { return "Venner"; }
trFunctionDocumentation()
QCString TranslatorNorwegian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 486 of file translator_no.h.
    { return "Funksjonsdokumentasjon"; }
trFunctions()
QCString TranslatorNorwegian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 444 of file translator_no.h.
    { return "Funksjoner"; }
trGeneratedAt()
QCString TranslatorNorwegian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 513 of file translator_no.h.
    {
      QCString result="Generert "+date;
      if (!projName.isEmpty()) result+=" for "+projName;
      result+=" av";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorNorwegian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 153 of file translator_no.h.
    { QCString result="Generert automatisk av Doxygen";
      if (!s.isEmpty()) result+=" for "+s;
      result+=" fra kildekoden.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorNorwegian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 556 of file translator_no.h.
    { return "Generert av"; }
trGeneratedFromFiles()
QCString TranslatorNorwegian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 756 of file translator_no.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentasjonen for ";
      switch(compType)
      {
        case ClassDef::Class:      result+="denne klasse"; break;
        case ClassDef::Struct:     result+="denne struct"; break;
        case ClassDef::Union:      result+="denne union"; break;
        case ClassDef::Interface:  result+="dette interface"; break;
        case ClassDef::Exception:  result+="dette unntak"; break;
        case ClassDef::Protocol:   result+="denne protocol"; break;
        case ClassDef::Category:   result+="denne category"; break;
        default: break;
      }
      result+=" ble generert fra flgende fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorNorwegian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1250 of file translator_no.h.
    {
      return createNoun(first_capital, singular, "global", "e");
    }
References Translator::createNoun().
trGotoDocumentation()
QCString TranslatorNorwegian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 844 of file translator_no.h.
    {
      return "G til dokumentasjonen til denne filen.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorNorwegian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 877 of file translator_no.h.
    {
      return "G til det grafiske klasse hierarkiet";
    }
trGotoSourceCode()
QCString TranslatorNorwegian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 839 of file translator_no.h.
    {
      return "G til kildekoden til denne filen.";
    }
trGotoTextualHierarchy()
QCString TranslatorNorwegian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 881 of file translator_no.h.
    {
      return "G til tekst-klassehierarki";
    }
trGraphicalHierarchy()
QCString TranslatorNorwegian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 873 of file translator_no.h.
    {
      return "Grafisk klassehierarki";
    }
trGroup()
QCString TranslatorNorwegian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1223 of file translator_no.h.
    {
      return createNoun(first_capital, singular, "gruppe", "r");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorNorwegian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 364 of file translator_no.h.
    { return "Hierarkisk indeks"; }
trImplementedFromList()
QCString TranslatorNorwegian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1284 of file translator_no.h.
    {
      return "Implementerer "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorNorwegian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1292 of file translator_no.h.
    {
      return "Implementert i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorNorwegian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 973 of file translator_no.h.
    {
      return "Denne grafen viser hvilke filer som direkte eller "
             "indirekte inkluderer denne filen:";
    }
trInclDepGraph()
QCString TranslatorNorwegian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 828 of file translator_no.h.
    {
      return "Avhengighetsgraf for "+fName+":";
    }
trIncludingInheritedMembers()
QCString TranslatorNorwegian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 147 of file translator_no.h.
    { return ", alle arvede medlemmer inkludert."; }
trInheritedByList()
QCString TranslatorNorwegian::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 690 of file translator_no.h.
    {
      return "Arvet av "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList()
QCString TranslatorNorwegian::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 682 of file translator_no.h.
    {
      return "Arver "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorNorwegian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 864 of file translator_no.h.
    {
      return "Startverdi:";
    }
trInterfaces()
QCString TranslatorNorwegian::trInterfaces () inline override virtual
Used for Java interfaces in the summary section of Java packages
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 1091 of file translator_no.h.
    {
      return "Grensesnitt";
    }
trInvariant()
QCString TranslatorNorwegian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 859 of file translator_no.h.
    {
      return "Invariant";
    }
trISOLang()
QCString TranslatorNorwegian::trISOLang () inline override virtual
Implements Translator.
Definition at line 78 of file translator_no.h.
    {
      return "nn";
    }
trLegend()
QCString TranslatorNorwegian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1051 of file translator_no.h.
    {
      return "symbolforklaring";
    }
trLegendDocs()
QCString TranslatorNorwegian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 993 of file translator_no.h.
    {
      return
        "Denne siden forklarer hvordan man tolker grafene doxygen genererer.<p>\n"
        "Vi baserer oss p flgende eksempel:\n"
        "\\code\n"
        "/*! Usynlig klasse pga. trunkasjon */\n"
        "class Invisible { };\n\n"
        "/*! Trunkert klasse, arve-relasjon er skjult */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasse som ikke er dokumentert med doxygen-kommentarer */"
        "class Undocumented { };\n\n"
        "/*! Klasse med public-arv */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasse med protected-arv */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasse med private-arv */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasse som blir brukt av klassen Inherited */\n"
        "class Used { };\n\n"
        "/*! Super-klasse som arver flere andre klasser */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Hvis \\c MAX_DOT_GRAPH_HEIGHT er satt til 200 i "
        "konfigurasjonsfila vil dette resultere i flgende graf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Boksene i grafen over betyr flgende:\n"
        "<ul>\n"
        "<li>En fylt svart boks representerer klassen grafen "
        "er generert for.\n"
        "<li>En boks med svart ramme angir en dokumentert struct eller klasse.\n"
        "<li>En boks med gr ramme angir en udokumentert struct eller klasse.\n"
        "<li>En boks med rd ramme angir en dokumentert struct eller klasse "
        "der ikke alle relasjoner er vist. En graf blir trunkert om den ikke "
        "passer innenfor de spesifiserte rammene.\n"
        "</ul>\n"
        "Pilene i grafen har flgende betydning:\n"
        "</ul>\n"
        "<li>En mrk bl pil brukes til  visualisere public-arv mellom to klasser.\n"
        "<li>En mrk grnn pil brukes for protected-arv.\n"
        "<li>En mrk rd pil angir private-arv.\n"
        "<li>En stiplet lilla pil angir at en klasse er inkludert eller brukt "
        "i en annen klasse. Pilen er merket med variablen(e) klassen "
        "er tilgjengelig gjennom.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorNorwegian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 988 of file translator_no.h.
    {
      return "Symbolforklaring";
    }
trListOfAllMembers()
QCString TranslatorNorwegian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 135 of file translator_no.h.
    { return "Liste over alle medlemmer"; }
trMainPage()
QCString TranslatorNorwegian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 787 of file translator_no.h.
    { return "Hovedside"; }
trMember()
QCString TranslatorNorwegian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1241 of file translator_no.h.
    {
      return createNoun(first_capital, singular, "medlem", "mer");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorNorwegian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 118 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Feltdokumentasjon";
      }
      else
      {
        return "Medlemsdata-dokumentasjon";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorNorwegian::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 110 of file translator_no.h.
    { return "Medlemsenumerasjon-dokumentasjon"; }
trMemberFunctionDocumentation()
QCString TranslatorNorwegian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 114 of file translator_no.h.
    { return "Medlemsfunksjon-dokumentasjon"; }
trMemberList()
QCString TranslatorNorwegian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 139 of file translator_no.h.
    { return "Medlemsliste"; }
trMemberTypedefDocumentation()
QCString TranslatorNorwegian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 106 of file translator_no.h.
    { return "Medlemstypedef-dokumentasjon"; }
trModuleDocumentation()
QCString TranslatorNorwegian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 391 of file translator_no.h.
    { return "Moduldokumentasjon"; }
trModuleIndex()
QCString TranslatorNorwegian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 358 of file translator_no.h.
    { return "Modulindeks"; }
trModules()
QCString TranslatorNorwegian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 177 of file translator_no.h.
    { return "Moduler"; }
trModulesDescription()
QCString TranslatorNorwegian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 345 of file translator_no.h.
    { return "Her er en liste over alle moduler:"; }
trMonth()
QCString TranslatorNorwegian::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1510 of file translator_no.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "mai", "jun", "jul", "aug", "sep", "okt", "nov", "des" };
      static const char *months_full[]  = { "januar", "februar", "mars", "april", "mai", "juni", "juli", "august", "september", "oktober", "november", "desember" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorNorwegian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 131 of file translator_no.h.
    { return "Mer..."; }
trNamespace()
QCString TranslatorNorwegian::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1214 of file translator_no.h.
    {
      return createNoun(first_capital, false, "navnerom", "");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorNorwegian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 736 of file translator_no.h.
    { return "Navneromsdokumentasjon"; }
trNamespaceIndex()
QCString TranslatorNorwegian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 730 of file translator_no.h.
    { return "Navneromsindeks"; }
trNamespaceList()
QCString TranslatorNorwegian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 564 of file translator_no.h.
    { return "Navneromsliste"; }
trNamespaceListDescription()
QCString TranslatorNorwegian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 568 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      result+="navnerom med korte beskrivelser:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorNorwegian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 716 of file translator_no.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterte ";
      result+="navneromsmedlemmer med koblinger til ";
      if (extractAll)
        result+="navneromsdokumentasjonen for hvert medlem:";
      else
        result+="navnerommet de hrer til:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorNorwegian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 712 of file translator_no.h.
    { return "Navneromsmedlemmer"; }
trNamespaceReference()
QCString TranslatorNorwegian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 627 of file translator_no.h.
    {
      QCString result=namespaceName;
      result+=" navneromsreferanse";
      return result;
    }
trNamespaces()
QCString TranslatorNorwegian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 746 of file translator_no.h.
    { return "Navnerom"; }
trNote()
QCString TranslatorNorwegian::trNote () inline override virtual
Implements Translator.
Definition at line 894 of file translator_no.h.
    {
      return "Notat";
    }
trOverloadText()
QCString TranslatorNorwegian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1495 of file translator_no.h.
    {
       return "Dette er en overloaded medlemsfunksjon, "
              "generert for deg. Den skiller seg ut fra "
              "funksjonen ovenfor i argument(ene) den aksepterer.";
    }
trPackage()
QCString TranslatorNorwegian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1108 of file translator_no.h.
    {
      return "Package "+name;
    }
trPackageAttribs()
QCString TranslatorNorwegian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1369 of file translator_no.h.
    {
      return "Pakkeattributter";
    }
trPackageFunctions()
QCString TranslatorNorwegian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1351 of file translator_no.h.
    {
      return "Pakkefunksjoner";
    }
trPackageListDescription()
QCString TranslatorNorwegian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1113 of file translator_no.h.
    {
      return "Her er pakkene med korte beskrivelser (om tilgjengelig):";
    }
trPackageMembers()
QCString TranslatorNorwegian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1355 of file translator_no.h.
    {
      return "Pakkemedlemmer";
    }
trPackages()
QCString TranslatorNorwegian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1118 of file translator_no.h.
    {
      return "Pakker";
    }
trPackageTypes()
QCString TranslatorNorwegian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1344 of file translator_no.h.
    {
      return "Pakketyper";
    }
trPage()
QCString TranslatorNorwegian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_no.h.
    {
      return createNoun(first_capital, singular, "side", "r");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorNorwegian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 793 of file translator_no.h.
    { return "s."; }
trPageIndex()
QCString TranslatorNorwegian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 885 of file translator_no.h.
    {
      return "Innhold";
    }
trParameters()
QCString TranslatorNorwegian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 548 of file translator_no.h.
    { return "Parametre"; }
trPostcondition()
QCString TranslatorNorwegian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 854 of file translator_no.h.
    {
      return "Etterbetingelse";
    }
trPrecondition()
QCString TranslatorNorwegian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 849 of file translator_no.h.
    {
      return "Forhndsbetingelse";
    }
trPrivateAttribs()
QCString TranslatorNorwegian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 933 of file translator_no.h.
    {
      return "Private attributter";
    }
trPrivateMembers()
QCString TranslatorNorwegian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 648 of file translator_no.h.
    { return "Private medlemsfunksjoner"; }
trPrivateSlots()
QCString TranslatorNorwegian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 650 of file translator_no.h.
    { return "Private slots"; }
trPrivateTypes()
QCString TranslatorNorwegian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 929 of file translator_no.h.
    {
      return "Private typer";
    }
trProperties()
QCString TranslatorNorwegian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1076 of file translator_no.h.
    {
      return "Egenskaper";
    }
trPropertyDocumentation()
QCString TranslatorNorwegian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1081 of file translator_no.h.
    {
      return "Egenskaps-dokumentasjon";
    }
trProtectedAttribs()
QCString TranslatorNorwegian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 921 of file translator_no.h.
    {
      return "Protected attributter";
    }
trProtectedMembers()
QCString TranslatorNorwegian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 642 of file translator_no.h.
    { return "Protected memdlemsfunksjoner"; }
trProtectedSlots()
QCString TranslatorNorwegian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 644 of file translator_no.h.
    { return "Protected slots"; }
trProtectedTypes()
QCString TranslatorNorwegian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 917 of file translator_no.h.
    {
      return "Protected typer";
    }
trPublicAttribs()
QCString TranslatorNorwegian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 902 of file translator_no.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datafelt";
      }
      else
      {
        return "Public attributter";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorNorwegian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 634 of file translator_no.h.
    { return "Public medlemsfunksjoner"; }
trPublicSlots()
QCString TranslatorNorwegian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 636 of file translator_no.h.
    { return "Public slots"; }
trPublicTypes()
QCString TranslatorNorwegian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 898 of file translator_no.h.
    {
      return "Public typer";
    }
trReferencedBy()
QCString TranslatorNorwegian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 961 of file translator_no.h.
    {
      return "Referert av";
    }
trReferenceManual()
QCString TranslatorNorwegian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 420 of file translator_no.h.
    { return "Referansemanual"; }
trReferences()
QCString TranslatorNorwegian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1272 of file translator_no.h.
    {
      return "Referanser";
    }
trReimplementedFromList()
QCString TranslatorNorwegian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 698 of file translator_no.h.
    {
      return "Reimplementert fra "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorNorwegian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 706 of file translator_no.h.
    {
      return "Reimplementert i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorNorwegian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 589 of file translator_no.h.
    { return "Venner og relatert funksjonsdokumentasjon"; }
trRelatedFunctions()
QCString TranslatorNorwegian::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 90 of file translator_no.h.
    { return "Relaterte funksjoner"; }
trRelatedPages()
QCString TranslatorNorwegian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 228 of file translator_no.h.
    { return "Relaterte sider"; }
trRelatedPagesDescription()
QCString TranslatorNorwegian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 341 of file translator_no.h.
    { return "Her er en liste over alle relaterte dokumentasjonssider:"; }
trRelatedSubscript()
QCString TranslatorNorwegian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 94 of file translator_no.h.
    { return "(Merk at disse ikke er medlemsfunksjoner.)"; }
trRemarks()
QCString TranslatorNorwegian::trRemarks () inline override virtual
Implements Translator.
Definition at line 965 of file translator_no.h.
    {
      return "Merknader";
    }
trReturns()
QCString TranslatorNorwegian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 540 of file translator_no.h.
    { return "Returnerer"; }
trReturnValues()
QCString TranslatorNorwegian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 782 of file translator_no.h.
    { return "Returverdier"; }
trRTFansicp()
QCString TranslatorNorwegian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1172 of file translator_no.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorNorwegian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1181 of file translator_no.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorNorwegian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1187 of file translator_no.h.
    {
      return "Indeks";
    }
trRTFTableOfContents()
QCString TranslatorNorwegian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1304 of file translator_no.h.
    {
      return "Innholdsfortegnelse";
    }
trSearch()
QCString TranslatorNorwegian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 236 of file translator_no.h.
    { return "Sk"; }
trSearchMatches()
QCString TranslatorNorwegian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1436 of file translator_no.h.
    {
      return "Treff:";
    }
trSearchResults()
QCString TranslatorNorwegian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1417 of file translator_no.h.
    {
      if (numDocuments==0)
      {
        return "Beklager, men ingen dokumenter ble funnet.";
      }
      else if (numDocuments==1)
      {
        return "Fant <b>ett</b> dokument som passet ditt sk.";
      }
      else
      {
        return "Fant <b>$num</b> dokumenter som passet ditt sk. "
               "Viser beste treff frst.";
      }
    }
trSearchResultsTitle()
QCString TranslatorNorwegian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1405 of file translator_no.h.
    {
      return "Skeresultater";
    }
trSeeAlso()
QCString TranslatorNorwegian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 544 of file translator_no.h.
    { return "Se ogs"; }
trSignals()
QCString TranslatorNorwegian::trSignals () inline override virtual
Implements Translator.
Definition at line 638 of file translator_no.h.
    { return "Signaler"; }
trSince()
QCString TranslatorNorwegian::trSince () inline override virtual
Implements Translator.
Definition at line 978 of file translator_no.h.
    {
      return "Siden";
    }
trSourceFile()
QCString TranslatorNorwegian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1447 of file translator_no.h.
    {
        return "Kildefil " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorNorwegian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1376 of file translator_no.h.
    {
      return "Statiske Pakkeattributter";
    }
trStaticPackageFunctions()
QCString TranslatorNorwegian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1362 of file translator_no.h.
    {
      return "Statiske Pakkefunksjoner";
    }
trStaticPrivateAttribs()
QCString TranslatorNorwegian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 937 of file translator_no.h.
    {
      return "Statiske private attributter";
    }
trStaticPrivateMembers()
QCString TranslatorNorwegian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 652 of file translator_no.h.
    { return "Statiske private medlemsfunksjoner"; }
trStaticProtectedAttribs()
QCString TranslatorNorwegian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 925 of file translator_no.h.
    {
      return "Statiske protected attributter";
    }
trStaticProtectedMembers()
QCString TranslatorNorwegian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 646 of file translator_no.h.
    { return "Statiske protected medlemsfunksjoner"; }
trStaticPublicAttribs()
QCString TranslatorNorwegian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 913 of file translator_no.h.
    {
      return "Statiske public attributter";
    }
trStaticPublicMembers()
QCString TranslatorNorwegian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 640 of file translator_no.h.
    { return "Statiske public medlemsfunksjoner"; }
trTest()
QCString TranslatorNorwegian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1061 of file translator_no.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorNorwegian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1066 of file translator_no.h.
    {
      return "Test-liste";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorNorwegian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 143 of file translator_no.h.
    { return "Dette er den fullstendige listen over medlemmer for"; }
trTodo()
QCString TranslatorNorwegian::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 947 of file translator_no.h.
    {
      return "Todo";
    }
trTodoList()
QCString TranslatorNorwegian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 952 of file translator_no.h.
    {
      return "Todo-liste";
    }
trTypedefDocumentation()
QCString TranslatorNorwegian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 468 of file translator_no.h.
    { return "Typedef-dokumentasjon"; }
trTypedefs()
QCString TranslatorNorwegian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 432 of file translator_no.h.
    { return "Typedef'er"; }
trVariableDocumentation()
QCString TranslatorNorwegian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 492 of file translator_no.h.
    { return "Variabeldokumentasjon"; }
trVariables()
QCString TranslatorNorwegian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 450 of file translator_no.h.
    { return "Variabler"; }
trVersion()
QCString TranslatorNorwegian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 532 of file translator_no.h.
    { return "Versjon"; }
trWarning()
QCString TranslatorNorwegian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 528 of file translator_no.h.
    { return "Advarsel"; }
trWriteList()
QCString TranslatorNorwegian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 658 of file translator_no.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=", og ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_no.h