Doxygen: DocCompoundNode Class Reference
DocCompoundNode Class Reference
Base class for nodes with children.
#include <src/docnode.h>
Public Member Functions
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
DocNodeList m_children
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Base class for nodes with children.
Definition at line 137 of file docnode.h.
Constructor & Destructor Documentation
DocCompoundNode()
DocCompoundNode::DocCompoundNode (DocParser * parser, DocNodeVariant * parent) inline
Definition at line 140 of file docnode.h.
      : DocNode(parser,parent) {}
References DocNode::DocNode(), DocNode::parent(), and DocNode::parser().
Referenced by DocAutoList::DocAutoList(), DocAutoListItem::DocAutoListItem(), DocDiagramFileBase::DocDiagramFileBase(), DocHRef::DocHRef(), DocHtmlBlockQuote::DocHtmlBlockQuote(), DocHtmlCaption::DocHtmlCaption(), DocHtmlCell::DocHtmlCell(), DocHtmlDescData::DocHtmlDescData(), DocHtmlDescList::DocHtmlDescList(), DocHtmlDescTitle::DocHtmlDescTitle(), DocHtmlDetails::DocHtmlDetails(), DocHtmlHeader::DocHtmlHeader(), DocHtmlList::DocHtmlList(), DocHtmlListItem::DocHtmlListItem(), DocHtmlRow::DocHtmlRow(), DocHtmlSummary::DocHtmlSummary(), DocHtmlTable::DocHtmlTable(), DocImage::DocImage(), DocInternal::DocInternal(), DocInternalRef::DocInternalRef(), DocLink::DocLink(), DocPara::DocPara(), DocParamSect::DocParamSect(), DocParBlock::DocParBlock(), DocRef::DocRef(), DocRoot::DocRoot(), DocSecRefItem::DocSecRefItem(), DocSecRefList::DocSecRefList(), DocSection::DocSection(), DocSimpleList::DocSimpleList(), DocSimpleSect::DocSimpleSect(), DocText::DocText(), DocTitle::DocTitle(), DocVhdlFlow::DocVhdlFlow(), and DocXRefItem::DocXRefItem().
Member Function Documentation
children() [1/2]
DocNodeList & DocCompoundNode::children () inline
Definition at line 142 of file docnode.h.
{ return m_children; }
References m_children.
Referenced by DocSimpleSect::appendLinkWord(), DocHtmlTable::computeTableGrid(), DocHtmlTable::firstRow(), flattenParagraphs(), HtmlDocVisitor::forceEndParagraph(), HtmlDocVisitor::forceStartParagraph(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleDoxyConfig(), DocPara::handleEmoji(), DocPara::handleFile(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlHeader(), DocPara::handleHtmlStartTag(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocPara::handleInheritDoc(), DocPara::handleLink(), DocPara::handleParamSection(), DocPara::handleRef(), DocPara::handleShowDate(), DocPara::handleSimpleSection(), DocPara::handleStartCode(), DocPara::handleVhdlFlow(), DocPara::handleXRefItem(), DocDiagramFileBase::hasCaption(), DocImage::hasCaption(), DocVhdlFlow::hasCaption(), DocRef::hasLinkText(), DocTitle::hasTitle(), DocPara::injectToken(), insideStyleChangeThatIsOutsideParagraph(), DocPara::isEmpty(), DocRoot::isEmpty(), DocText::isEmpty(), DocHtmlRow::isHeading(), DocHtmlRow::numCells(), DocHtmlTable::numRows(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), DocAutoList::parse(), DocAutoListItem::parse(), DocDiaFile::parse(), DocDotFile::parse(), DocHRef::parse(), DocHtmlBlockQuote::parse(), DocHtmlCaption::parse(), DocHtmlCell::parse(), DocHtmlDescData::parse(), DocHtmlDescList::parse(), DocHtmlDescTitle::parse(), DocHtmlDetails::parse(), DocHtmlHeader::parse(), DocHtmlList::parse(), DocHtmlListItem::parse(), DocHtmlRow::parse(), DocHtmlSummary::parse(), DocHtmlTable::parse(), DocImage::parse(), DocInternal::parse(), DocInternalRef::parse(), DocLink::parse(), DocMscFile::parse(), DocPara::parse(), DocParamSect::parse(), DocParBlock::parse(), DocPlantUmlFile::parse(), DocRef::parse(), DocRoot::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocSection::parse(), DocSimpleList::parse(), DocSimpleSect::parse(), DocText::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocXRefItem::parse(), DocTitle::parseFromString(), DocSimpleSect::parseRcs(), DocHtmlCell::parseXml(), DocHtmlList::parseXml(), DocHtmlListItem::parseXml(), DocHtmlRow::parseXml(), DocHtmlTable::parseXml(), and DocSimpleSect::parseXml().
children() [2/2]
const DocNodeList & DocCompoundNode::children () const inline
Definition at line 143 of file docnode.h.
{ return m_children; }
References m_children.
Member Data Documentation
m_children
DocNodeList DocCompoundNode::m_children private
Definition at line 146 of file docnode.h.
Referenced by children(), and children().
The documentation for this class was generated from the following file:
src/docnode.h