Doxygen: GlobalsIndexContext::Private Class Reference
GlobalsIndexContext::Private Class Reference
Public Member Functions
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Types
using MemberFilter = bool(MemberDef::*)() const
Private Member Functions
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant macros () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
TemplateVariant createMembersFiltered (MemberFilter filter) const
TemplateVariant createAll () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createTypedefs () const
TemplateVariant createEnums () const
TemplateVariant createEnumValues () const
TemplateVariant createMacros () const
Private Attributes
CachedItem< TemplateVariant, Private, &Private::createAll > m_all
CachedItem< TemplateVariant, Private, &Private::createFunctions > m_functions
CachedItem< TemplateVariant, Private, &Private::createVariables > m_variables
CachedItem< TemplateVariant, Private, &Private::createTypedefs > m_typedefs
CachedItem< TemplateVariant, Private, &Private::createEnums > m_enums
CachedItem< TemplateVariant, Private, &Private::createEnumValues > m_enumValues
CachedItem< TemplateVariant, Private, &Private::createMacros > m_macros
Static Private Attributes
static const PropertyMap< GlobalsIndexContext::Private > s_inst
Detailed Description
Definition at line 7104 of file context.cpp.
Member Typedef Documentation
MemberFilter
using GlobalsIndexContext::Private::MemberFilter = bool (MemberDef::*)() const private
Definition at line 7130 of file context.cpp.
Member Function Documentation
all()
TemplateVariant GlobalsIndexContext::Private::all () const inline private
Definition at line 7113 of file context.cpp.
{ return m_all.get(this); }
References m_all.
createAll()
TemplateVariant GlobalsIndexContext::Private::createAll () const inline private
Definition at line 7151 of file context.cpp.
{ return createMembersFiltered(0); }
References createMembersFiltered().
createEnums()
TemplateVariant GlobalsIndexContext::Private::createEnums () const inline private
Definition at line 7155 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumerate); }
References createMembersFiltered(), and MemberDef::isEnumerate().
createEnumValues()
TemplateVariant GlobalsIndexContext::Private::createEnumValues () const inline private
Definition at line 7156 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumValue); }
References createMembersFiltered(), and MemberDef::isEnumValue().
createFunctions()
TemplateVariant GlobalsIndexContext::Private::createFunctions () const inline private
Definition at line 7152 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isFunction); }
References createMembersFiltered(), and MemberDef::isFunction().
createMacros()
TemplateVariant GlobalsIndexContext::Private::createMacros () const inline private
Definition at line 7157 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isDefine); }
References createMembersFiltered(), and MemberDef::isDefine().
createMembersFiltered()
TemplateVariant GlobalsIndexContext::Private::createMembersFiltered (MemberFilter filter) const inline private
Definition at line 7131 of file context.cpp.
    {
      TemplateVariantList list;
      for (const auto &mn : *Doxygen::functionNameLinkedMap)
      {
        for (const auto &md : *mn)
        {
          const FileDef *fd=md->getFileDef();
          if (fd && fd->isLinkableInProject() &&
              !md->name().isEmpty() && !md->getNamespaceDef() && md->isLinkableInProject())
          {
            if (filter==0 || (md.get()->*filter)())
            {
              list.push_back(MemberContext::alloc(md.get()));
            }
          }
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), Doxygen::functionNameLinkedMap, and FileDef::isLinkableInProject().
Referenced by createAll(), createEnums(), createEnumValues(), createFunctions(), createMacros(), createTypedefs(), and createVariables().
createTypedefs()
TemplateVariant GlobalsIndexContext::Private::createTypedefs () const inline private
Definition at line 7154 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isTypedef); }
References createMembersFiltered(), and MemberDef::isTypedef().
createVariables()
TemplateVariant GlobalsIndexContext::Private::createVariables () const inline private
Definition at line 7153 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isVariable); }
References createMembersFiltered(), and MemberDef::isVariable().
enums()
TemplateVariant GlobalsIndexContext::Private::enums () const inline private
Definition at line 7117 of file context.cpp.
{ return m_enums.get(this); }
References m_enums.
enumValues()
TemplateVariant GlobalsIndexContext::Private::enumValues () const inline private
Definition at line 7118 of file context.cpp.
{ return m_enumValues.get(this); }
References m_enumValues.
events()
TemplateVariant GlobalsIndexContext::Private::events () const inline private
Definition at line 7121 of file context.cpp.
{ return FALSE; }
References FALSE.
fields()
StringVector GlobalsIndexContext::Private::fields () const inline
Definition at line 7109 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fileName()
TemplateVariant GlobalsIndexContext::Private::fileName () const inline private
Definition at line 7123 of file context.cpp.
{ return "globals"; }
functions()
TemplateVariant GlobalsIndexContext::Private::functions () const inline private
Definition at line 7114 of file context.cpp.
{ return m_functions.get(this); }
References m_functions.
get()
TemplateVariant GlobalsIndexContext::Private::get (const QCString & n) const inline
Definition at line 7108 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), and s_inst.
highlight()
TemplateVariant GlobalsIndexContext::Private::highlight () const inline private
Definition at line 7125 of file context.cpp.
{ return "files"; }
macros()
TemplateVariant GlobalsIndexContext::Private::macros () const inline private
Definition at line 7119 of file context.cpp.
{ return m_macros.get(this); }
References m_macros.
properties()
TemplateVariant GlobalsIndexContext::Private::properties () const inline private
Definition at line 7120 of file context.cpp.
{ return FALSE; }
References FALSE.
related()
TemplateVariant GlobalsIndexContext::Private::related () const inline private
Definition at line 7122 of file context.cpp.
{ return FALSE; }
References FALSE.
relPath()
TemplateVariant GlobalsIndexContext::Private::relPath () const inline private
Definition at line 7124 of file context.cpp.
{ return ""; }
subhighlight()
TemplateVariant GlobalsIndexContext::Private::subhighlight () const inline private
Definition at line 7126 of file context.cpp.
{ return "filemembers"; }
title()
TemplateVariant GlobalsIndexContext::Private::title () const inline private
Definition at line 7127 of file context.cpp.
{ return theTranslator->trFileMembers(); }
References theTranslator, and Translator::trFileMembers().
typedefs()
TemplateVariant GlobalsIndexContext::Private::typedefs () const inline private
Definition at line 7116 of file context.cpp.
{ return m_typedefs.get(this); }
References m_typedefs.
variables()
TemplateVariant GlobalsIndexContext::Private::variables () const inline private
Definition at line 7115 of file context.cpp.
{ return m_variables.get(this); }
References m_variables.
Member Data Documentation
m_all
CachedItem<TemplateVariant, Private, &Private::createAll> GlobalsIndexContext::Private::m_all private
Definition at line 7159 of file context.cpp.
Referenced by all().
m_enums
CachedItem<TemplateVariant, Private, &Private::createEnums> GlobalsIndexContext::Private::m_enums private
Definition at line 7163 of file context.cpp.
Referenced by enums().
m_enumValues
CachedItem<TemplateVariant, Private, &Private::createEnumValues> GlobalsIndexContext::Private::m_enumValues private
Definition at line 7164 of file context.cpp.
Referenced by enumValues().
m_functions
CachedItem<TemplateVariant, Private, &Private::createFunctions> GlobalsIndexContext::Private::m_functions private
Definition at line 7160 of file context.cpp.
Referenced by functions().
m_macros
CachedItem<TemplateVariant, Private, &Private::createMacros> GlobalsIndexContext::Private::m_macros private
Definition at line 7165 of file context.cpp.
Referenced by macros().
m_typedefs
CachedItem<TemplateVariant, Private, &Private::createTypedefs> GlobalsIndexContext::Private::m_typedefs private
Definition at line 7162 of file context.cpp.
Referenced by typedefs().
m_variables
CachedItem<TemplateVariant, Private, &Private::createVariables> GlobalsIndexContext::Private::m_variables private
Definition at line 7161 of file context.cpp.
Referenced by variables().
s_inst
const PropertyMap< GlobalsIndexContext::Private > GlobalsIndexContext::Private::s_inst static private
Initial value:
{
  {  "all",         &Private::all },
  {  "functions",   &Private::functions },
  {  "variables",   &Private::variables },
  {  "typedefs",    &Private::typedefs },
  {  "enums",       &Private::enums },
  {  "enumValues",  &Private::enumValues },
  {  "macros",      &Private::macros },
  {  "properties",  &Private::properties },
  {  "events",      &Private::events },
  {  "related",     &Private::related },
  {  "fileName",    &Private::fileName },
  {  "relPath",     &Private::relPath },
  {  "highlight",   &Private::highlight },
  {  "subhighlight",&Private::subhighlight },
  {  "title",       &Private::title }
}
Definition at line 7166 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/context.cpp