Doxygen: DefinitionMixin< Base > Class Template Reference
DefinitionMixin< Base > Class Template Reference
#include <src/definitionimpl.h>
Public Member Functions
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=nullptr, const char *d=nullptr, bool isSymbol=TRUE)
~DefinitionMixin ()=default
bool isAlias () const override
const QCString & name () const override
bool isAnonymous () const override
const QCString & localName () const override
QCString qualifiedName () const override
QCString symbolName () const override
QCString getSourceFileBase () const override
QCString getSourceAnchor () const override
QCString documentation () const override
int docLine () const override
QCString docFile () const override
QCString briefDescription (bool abbreviate=FALSE) const override
QCString briefDescriptionAsTooltip () const override
int briefLine () const override
QCString inbodyDocumentation () const override
QCString inbodyFile () const override
int inbodyLine () const override
QCString briefFile () const override
QCString getDefFileName () const override
QCString getDefFileExtension () const override
int getDefLine () const override
int getDefColumn () const override
bool hasDocumentation () const override
bool hasUserDocumentation () const override
bool isVisibleInProject () const override
bool isVisible () const override
bool isHidden () const override
bool isArtificial () const override
bool isExported () const override
QCString getReference () const override
bool isReference () const override
QCString externalReference (const QCString &relPath) const override
int getStartDefLine () const override
int getStartBodyLine () const override
int getEndBodyLine () const override
const FileDef * getBodyDef () const override
SrcLangExt getLanguage () const override
const GroupList & partOfGroups () const override
bool isLinkableViaGroup () const override
const RefItemVector & xrefListItems () const override
const Definition * findInnerCompound (const QCString &name) const override
Definition * getOuterScope () const override
const MemberVector & getReferencesMembers () const override
const MemberVector & getReferencedByMembers () const override
bool hasSections () const override
bool hasSources () const override
bool hasBriefDescription () const override
QCString id () const override
const SectionRefs & getSectionRefs () const override
void setName (const QCString &name) override
void setId (const QCString &name) override
void setDefFile (const QCString &df, int defLine, int defColumn) override
void setDocumentation (const QCString &doc, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE) override
void setBriefDescription (const QCString &brief, const QCString &briefFile, int briefLine) override
void setInbodyDocumentation (const QCString &doc, const QCString &docFile, int docLine) override
void setReference (const QCString &r) override
void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList) override
void setBodySegment (int defLine, int bls, int ble) override
void setBodyDef (const FileDef *fd) override
void addSourceReferencedBy (MemberDef *md) override
void addSourceReferences (MemberDef *md) override
void setRefItems (const RefItemVector &sli) override
void mergeRefItems (Definition *def) override
void mergeReferences (const Definition *other) override
void mergeReferencedBy (const Definition *other) override
void addInnerCompound (Definition *def) override
void setOuterScope (Definition *def) override
void setHidden (bool b) override
void setArtificial (bool b) override
void setExported (bool b) override
void setLanguage (SrcLangExt lang) override
void writeSourceDef (OutputList &ol, const QCString &scopeName) const override
void writeInlineCode (OutputList &ol, const QCString &scopeName) const override
bool hasSourceRefs () const override
bool hasSourceReffedBy () const override
void writeSourceRefs (OutputList &ol, const QCString &scopeName) const override
void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const override
void makePartOfGroup (GroupDef *gd) override
void writeNavigationPath (OutputList &ol) const override
QCString navigationPathAsString () const override
void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const override
void writeSummaryLinks (OutputList &ol) const override
QCString pathFragment () const override
void writeDocAnchorsToTagFile (TextStream &fs) const override
void setLocalName (const QCString &name) override
void addSectionsToIndex () override
void writeToc (OutputList &ol, const LocalToc &lt) const override
void computeTooltip () override
void _setSymbolName (const QCString &name) override
QCString _symbolName () const override
Protected Member Functions
DefinitionMixin (const DefinitionMixin &def)=default
Private Member Functions
Definition * toDefinition_ () override
DefinitionMutable * toDefinitionMutable_ () override
const DefinitionImpl * toDefinitionImpl_ () const override
Private Attributes
DefinitionImpl m_impl
Detailed Description
template<class Base>
class DefinitionMixin< Base >
Definition at line 145 of file definitionimpl.h.
Constructor & Destructor Documentation
DefinitionMixin() [1/2]
template<class Base > DefinitionMixin< Base >::DefinitionMixin (const QCString & defFileName, int defLine, int defColumn, const QCString & name, const char * b = nullptr, const char * d = nullptr, bool isSymbol = TRUE) inline
Create a new definition
Definition at line 149 of file definitionimpl.h.
                            : m_impl(this,defFileName,defLine,defColumn,name,b,d,isSymbol) {}
~DefinitionMixin()
template<class Base > DefinitionMixin< Base >::~DefinitionMixin () default
DefinitionMixin() [2/2]
template<class Base > DefinitionMixin< Base >::DefinitionMixin (const DefinitionMixin< Base > & def) protected default
Member Function Documentation
_setSymbolName()
template<class Base > void DefinitionMixin< Base >::_setSymbolName (const QCString & name) inline override
Definition at line 284 of file definitionimpl.h.
    { m_impl._setSymbolName(name); }
References DefinitionImpl::_setSymbolName(), DefinitionMixin< Base >::m_impl, and DefinitionMixin< Base >::name().
_symbolName()
template<class Base > QCString DefinitionMixin< Base >::_symbolName () const inline override
Definition at line 286 of file definitionimpl.h.
    { return m_impl._symbolName(); }
References DefinitionImpl::_symbolName(), and DefinitionMixin< Base >::m_impl.
addInnerCompound()
template<class Base > void DefinitionMixin< Base >::addInnerCompound (Definition * def) inline override
Reimplemented in NamespaceDefImpl, and PageDefImpl.
Definition at line 238 of file definitionimpl.h.
    { m_impl.addInnerCompound(def); }
References DefinitionImpl::addInnerCompound(), and DefinitionMixin< Base >::m_impl.
addSectionsToDefinition()
template<class Base > void DefinitionMixin< Base >::addSectionsToDefinition (const std::vector< const SectionInfo * > & anchorList) inline override
Definition at line 220 of file definitionimpl.h.
    { m_impl.addSectionsToDefinition(anchorList); }
References DefinitionImpl::addSectionsToDefinition(), and DefinitionMixin< Base >::m_impl.
addSectionsToIndex()
template<class Base > void DefinitionMixin< Base >::addSectionsToIndex () inline override
Definition at line 278 of file definitionimpl.h.
    { m_impl.addSectionsToIndex(); }
References DefinitionImpl::addSectionsToIndex(), and DefinitionMixin< Base >::m_impl.
addSourceReferencedBy()
template<class Base > void DefinitionMixin< Base >::addSourceReferencedBy (MemberDef * md) inline override
Definition at line 226 of file definitionimpl.h.
    { m_impl.addSourceReferencedBy(md); }
References DefinitionImpl::addSourceReferencedBy(), and DefinitionMixin< Base >::m_impl.
addSourceReferences()
template<class Base > void DefinitionMixin< Base >::addSourceReferences (MemberDef * md) inline override
Definition at line 228 of file definitionimpl.h.
    { m_impl.addSourceReferences(md); }
References DefinitionImpl::addSourceReferences(), and DefinitionMixin< Base >::m_impl.
briefDescription()
template<class Base > QCString DefinitionMixin< Base >::briefDescription (bool abbreviate = FALSE) const inline override
Reimplemented in MemberDefImpl.
Definition at line 168 of file definitionimpl.h.
{ return m_impl.briefDescription(abbreviate); }
References abbreviate(), DefinitionImpl::briefDescription(), and DefinitionMixin< Base >::m_impl.
Referenced by MemberDefImpl::briefDescription().
briefDescriptionAsTooltip()
template<class Base > QCString DefinitionMixin< Base >::briefDescriptionAsTooltip () const inline override
Definition at line 169 of file definitionimpl.h.
{ return m_impl.briefDescriptionAsTooltip(); }
References DefinitionImpl::briefDescriptionAsTooltip(), and DefinitionMixin< Base >::m_impl.
briefFile()
template<class Base > QCString DefinitionMixin< Base >::briefFile () const inline override
Definition at line 174 of file definitionimpl.h.
{ return m_impl.briefFile(); }
References DefinitionImpl::briefFile(), and DefinitionMixin< Base >::m_impl.
Referenced by DefinitionMixin< Base >::setBriefDescription().
briefLine()
template<class Base > int DefinitionMixin< Base >::briefLine () const inline override
Definition at line 170 of file definitionimpl.h.
{ return m_impl.briefLine(); }
References DefinitionImpl::briefLine(), and DefinitionMixin< Base >::m_impl.
Referenced by DefinitionMixin< Base >::setBriefDescription().
computeTooltip()
template<class Base > void DefinitionMixin< Base >::computeTooltip () inline override
Definition at line 282 of file definitionimpl.h.
    { m_impl.computeTooltip(); }
References DefinitionImpl::computeTooltip(), and DefinitionMixin< Base >::m_impl.
docFile()
template<class Base > QCString DefinitionMixin< Base >::docFile () const inline override
Definition at line 167 of file definitionimpl.h.
{ return m_impl.docFile(); }
References DefinitionImpl::docFile(), and DefinitionMixin< Base >::m_impl.
Referenced by DefinitionMixin< Base >::setDocumentation(), and DefinitionMixin< Base >::setInbodyDocumentation().
docLine()
template<class Base > int DefinitionMixin< Base >::docLine () const inline override
Definition at line 166 of file definitionimpl.h.
{ return m_impl.docLine(); }
References DefinitionImpl::docLine(), and DefinitionMixin< Base >::m_impl.
Referenced by DefinitionMixin< Base >::setDocumentation(), and DefinitionMixin< Base >::setInbodyDocumentation().
documentation()
template<class Base > QCString DefinitionMixin< Base >::documentation () const inline override
Reimplemented in MemberDefImpl.
Definition at line 165 of file definitionimpl.h.
{ return m_impl.documentation(); }
References DefinitionImpl::documentation(), and DefinitionMixin< Base >::m_impl.
Referenced by MemberDefImpl::documentation().
externalReference()
template<class Base > QCString DefinitionMixin< Base >::externalReference (const QCString & relPath) const inline override
Definition at line 188 of file definitionimpl.h.
{ return m_impl.externalReference(relPath); }
References DefinitionImpl::externalReference(), and DefinitionMixin< Base >::m_impl.
findInnerCompound()
template<class Base > const Definition * DefinitionMixin< Base >::findInnerCompound (const QCString & name) const inline override
Reimplemented in NamespaceDefImpl.
Definition at line 197 of file definitionimpl.h.
{ return m_impl.findInnerCompound(name); }
References DefinitionImpl::findInnerCompound(), DefinitionMixin< Base >::m_impl, and DefinitionMixin< Base >::name().
getBodyDef()
template<class Base > const FileDef * DefinitionMixin< Base >::getBodyDef () const inline override
Definition at line 192 of file definitionimpl.h.
{ return m_impl.getBodyDef(); }
References DefinitionImpl::getBodyDef(), and DefinitionMixin< Base >::m_impl.
getDefColumn()
template<class Base > int DefinitionMixin< Base >::getDefColumn () const inline override
Definition at line 178 of file definitionimpl.h.
{ return m_impl.getDefColumn(); }
References DefinitionImpl::getDefColumn(), and DefinitionMixin< Base >::m_impl.
getDefFileExtension()
template<class Base > QCString DefinitionMixin< Base >::getDefFileExtension () const inline override
Definition at line 176 of file definitionimpl.h.
{ return m_impl.getDefFileExtension(); }
References DefinitionImpl::getDefFileExtension(), and DefinitionMixin< Base >::m_impl.
getDefFileName()
template<class Base > QCString DefinitionMixin< Base >::getDefFileName () const inline override
Definition at line 175 of file definitionimpl.h.
{ return m_impl.getDefFileName(); }
References DefinitionImpl::getDefFileName(), and DefinitionMixin< Base >::m_impl.
Referenced by ModuleDefImpl::mergeSymbolsFrom().
getDefLine()
template<class Base > int DefinitionMixin< Base >::getDefLine () const inline override
Definition at line 177 of file definitionimpl.h.
{ return m_impl.getDefLine(); }
References DefinitionImpl::getDefLine(), and DefinitionMixin< Base >::m_impl.
Referenced by ModuleDefImpl::mergeSymbolsFrom().
getEndBodyLine()
template<class Base > int DefinitionMixin< Base >::getEndBodyLine () const inline override
Definition at line 191 of file definitionimpl.h.
{ return m_impl.getEndBodyLine(); }
References DefinitionImpl::getEndBodyLine(), and DefinitionMixin< Base >::m_impl.
getLanguage()
template<class Base > SrcLangExt DefinitionMixin< Base >::getLanguage () const inline override
Definition at line 193 of file definitionimpl.h.
{ return m_impl.getLanguage(); }
References DefinitionImpl::getLanguage(), and DefinitionMixin< Base >::m_impl.
getOuterScope()
template<class Base > Definition * DefinitionMixin< Base >::getOuterScope () const inline override
Definition at line 198 of file definitionimpl.h.
{ return m_impl.getOuterScope(); }
References DefinitionImpl::getOuterScope(), and DefinitionMixin< Base >::m_impl.
getReference()
template<class Base > QCString DefinitionMixin< Base >::getReference () const inline override
Reimplemented in MemberDefImpl.
Definition at line 186 of file definitionimpl.h.
{ return m_impl.getReference(); }
References DefinitionImpl::getReference(), and DefinitionMixin< Base >::m_impl.
Referenced by ClassDefImpl::getReference(), and MemberDefImpl::getReference().
getReferencedByMembers()
template<class Base > const MemberVector & DefinitionMixin< Base >::getReferencedByMembers () const inline override
Definition at line 200 of file definitionimpl.h.
{ return m_impl.getReferencedByMembers(); }
References DefinitionImpl::getReferencedByMembers(), and DefinitionMixin< Base >::m_impl.
getReferencesMembers()
template<class Base > const MemberVector & DefinitionMixin< Base >::getReferencesMembers () const inline override
Definition at line 199 of file definitionimpl.h.
{ return m_impl.getReferencesMembers(); }
References DefinitionImpl::getReferencesMembers(), and DefinitionMixin< Base >::m_impl.
getSectionRefs()
template<class Base > const SectionRefs & DefinitionMixin< Base >::getSectionRefs () const inline override
Definition at line 205 of file definitionimpl.h.
{ return m_impl.getSectionRefs(); }
References DefinitionImpl::getSectionRefs(), and DefinitionMixin< Base >::m_impl.
getSourceAnchor()
template<class Base > QCString DefinitionMixin< Base >::getSourceAnchor () const inline override
Definition at line 164 of file definitionimpl.h.
{ return m_impl.getSourceAnchor(); }
References DefinitionImpl::getSourceAnchor(), and DefinitionMixin< Base >::m_impl.
getSourceFileBase()
template<class Base > QCString DefinitionMixin< Base >::getSourceFileBase () const inline override
Reimplemented in FileDefImpl.
Definition at line 163 of file definitionimpl.h.
{ return m_impl.getSourceFileBase(); }
References DefinitionImpl::getSourceFileBase(), and DefinitionMixin< Base >::m_impl.
Referenced by ClassDefImpl::getSourceFileBase().
getStartBodyLine()
template<class Base > int DefinitionMixin< Base >::getStartBodyLine () const inline override
Definition at line 190 of file definitionimpl.h.
{ return m_impl.getStartBodyLine(); }
References DefinitionImpl::getStartBodyLine(), and DefinitionMixin< Base >::m_impl.
getStartDefLine()
template<class Base > int DefinitionMixin< Base >::getStartDefLine () const inline override
Definition at line 189 of file definitionimpl.h.
{ return m_impl.getStartDefLine(); }
References DefinitionImpl::getStartDefLine(), and DefinitionMixin< Base >::m_impl.
hasBriefDescription()
template<class Base > bool DefinitionMixin< Base >::hasBriefDescription () const inline override
Definition at line 203 of file definitionimpl.h.
{ return m_impl.hasBriefDescription(); }
References DefinitionImpl::hasBriefDescription(), and DefinitionMixin< Base >::m_impl.
hasDocumentation()
template<class Base > bool DefinitionMixin< Base >::hasDocumentation () const inline override
Reimplemented in MemberDefImpl.
Definition at line 179 of file definitionimpl.h.
{ return m_impl.hasDocumentation(); }
References DefinitionImpl::hasDocumentation(), and DefinitionMixin< Base >::m_impl.
Referenced by ClassDefImpl::hasDocumentation(), and MemberDefImpl::hasDocumentation().
hasSections()
template<class Base > bool DefinitionMixin< Base >::hasSections () const inline override
Definition at line 201 of file definitionimpl.h.
{ return m_impl.hasSections(); }
References DefinitionImpl::hasSections(), and DefinitionMixin< Base >::m_impl.
hasSourceReffedBy()
template<class Base > bool DefinitionMixin< Base >::hasSourceReffedBy () const inline override
Definition at line 256 of file definitionimpl.h.
    { return m_impl.hasSourceReffedBy(); }
References DefinitionImpl::hasSourceReffedBy(), and DefinitionMixin< Base >::m_impl.
hasSourceRefs()
template<class Base > bool DefinitionMixin< Base >::hasSourceRefs () const inline override
Definition at line 254 of file definitionimpl.h.
    { return m_impl.hasSourceRefs(); }
References DefinitionImpl::hasSourceRefs(), and DefinitionMixin< Base >::m_impl.
hasSources()
template<class Base > bool DefinitionMixin< Base >::hasSources () const inline override
Definition at line 202 of file definitionimpl.h.
{ return m_impl.hasSources(); }
References DefinitionImpl::hasSources(), and DefinitionMixin< Base >::m_impl.
hasUserDocumentation()
template<class Base > bool DefinitionMixin< Base >::hasUserDocumentation () const inline override
Definition at line 180 of file definitionimpl.h.
{ return m_impl.hasUserDocumentation(); }
References DefinitionImpl::hasUserDocumentation(), and DefinitionMixin< Base >::m_impl.
id()
template<class Base > QCString DefinitionMixin< Base >::id () const inline override
Definition at line 204 of file definitionimpl.h.
{ return m_impl.id(); }
References DefinitionImpl::id(), and DefinitionMixin< Base >::m_impl.
inbodyDocumentation()
template<class Base > QCString DefinitionMixin< Base >::inbodyDocumentation () const inline override
Definition at line 171 of file definitionimpl.h.
{ return m_impl.inbodyDocumentation(); }
References DefinitionImpl::inbodyDocumentation(), and DefinitionMixin< Base >::m_impl.
inbodyFile()
template<class Base > QCString DefinitionMixin< Base >::inbodyFile () const inline override
Definition at line 172 of file definitionimpl.h.
{ return m_impl.inbodyFile(); }
References DefinitionImpl::inbodyFile(), and DefinitionMixin< Base >::m_impl.
inbodyLine()
template<class Base > int DefinitionMixin< Base >::inbodyLine () const inline override
Definition at line 173 of file definitionimpl.h.
{ return m_impl.inbodyLine(); }
References DefinitionImpl::inbodyLine(), and DefinitionMixin< Base >::m_impl.
isAlias()
template<class Base > bool DefinitionMixin< Base >::isAlias () const inline override
Definition at line 155 of file definitionimpl.h.
{ return FALSE; }
References FALSE.
isAnonymous()
template<class Base > bool DefinitionMixin< Base >::isAnonymous () const inline override
Definition at line 159 of file definitionimpl.h.
{ return m_impl.isAnonymous(); }
References DefinitionImpl::isAnonymous(), and DefinitionMixin< Base >::m_impl.
isArtificial()
template<class Base > bool DefinitionMixin< Base >::isArtificial () const inline override
Definition at line 184 of file definitionimpl.h.
{ return m_impl.isArtificial(); }
References DefinitionImpl::isArtificial(), and DefinitionMixin< Base >::m_impl.
isExported()
template<class Base > bool DefinitionMixin< Base >::isExported () const inline override
Definition at line 185 of file definitionimpl.h.
{ return m_impl.isExported(); }
References DefinitionImpl::isExported(), and DefinitionMixin< Base >::m_impl.
isHidden()
template<class Base > bool DefinitionMixin< Base >::isHidden () const inline override
Definition at line 183 of file definitionimpl.h.
{ return m_impl.isHidden(); }
References DefinitionImpl::isHidden(), and DefinitionMixin< Base >::m_impl.
isLinkableViaGroup()
template<class Base > bool DefinitionMixin< Base >::isLinkableViaGroup () const inline override
Definition at line 195 of file definitionimpl.h.
{ return m_impl.isLinkableViaGroup(); }
References DefinitionImpl::isLinkableViaGroup(), and DefinitionMixin< Base >::m_impl.
isReference()
template<class Base > bool DefinitionMixin< Base >::isReference () const inline override
Reimplemented in MemberDefImpl.
Definition at line 187 of file definitionimpl.h.
{ return m_impl.isReference(); }
References DefinitionImpl::isReference(), and DefinitionMixin< Base >::m_impl.
Referenced by ClassDefImpl::isReference(), and MemberDefImpl::isReference().
isVisible()
template<class Base > bool DefinitionMixin< Base >::isVisible () const inline override
Definition at line 182 of file definitionimpl.h.
{ return m_impl.isVisible(); }
References DefinitionImpl::isVisible(), and DefinitionMixin< Base >::m_impl.
isVisibleInProject()
template<class Base > bool DefinitionMixin< Base >::isVisibleInProject () const inline override
Definition at line 181 of file definitionimpl.h.
{ return m_impl.isVisibleInProject(); }
References DefinitionImpl::isVisibleInProject(), and DefinitionMixin< Base >::m_impl.
localName()
template<class Base > const QCString & DefinitionMixin< Base >::localName () const inline override
Definition at line 160 of file definitionimpl.h.
{ return m_impl.localName(); }
References DefinitionImpl::localName(), and DefinitionMixin< Base >::m_impl.
makePartOfGroup()
template<class Base > void DefinitionMixin< Base >::makePartOfGroup (GroupDef * gd) inline override
Definition at line 262 of file definitionimpl.h.
    { m_impl.makePartOfGroup(gd); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::makePartOfGroup().
mergeReferencedBy()
template<class Base > void DefinitionMixin< Base >::mergeReferencedBy (const Definition * other) inline override
Definition at line 236 of file definitionimpl.h.
    { m_impl.mergeReferencedBy(other); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::mergeReferencedBy().
mergeReferences()
template<class Base > void DefinitionMixin< Base >::mergeReferences (const Definition * other) inline override
Definition at line 234 of file definitionimpl.h.
    { m_impl.mergeReferences(other); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::mergeReferences().
mergeRefItems()
template<class Base > void DefinitionMixin< Base >::mergeRefItems (Definition * def) inline override
Definition at line 232 of file definitionimpl.h.
    { m_impl.mergeRefItems(def); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::mergeRefItems().
name()
template<class Base > const QCString & DefinitionMixin< Base >::name () const inline override
Reimplemented in FileDefImpl.
Definition at line 158 of file definitionimpl.h.
{ return m_impl.name(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::name().
Referenced by DefinitionMixin< Base >::_setSymbolName(), GroupDefImpl::displayName(), MemberDefImpl::displayName(), PageDefImpl::displayName(), FileDefImpl::FileDefImpl(), DefinitionMixin< Base >::findInnerCompound(), FileDefImpl::name(), DefinitionMixin< Base >::setId(), DefinitionMixin< Base >::setLocalName(), and DefinitionMixin< Base >::setName().
navigationPathAsString()
template<class Base > QCString DefinitionMixin< Base >::navigationPathAsString () const inline override
Definition at line 266 of file definitionimpl.h.
    { return m_impl.navigationPathAsString(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::navigationPathAsString().
partOfGroups()
template<class Base > const GroupList & DefinitionMixin< Base >::partOfGroups () const inline override
Definition at line 194 of file definitionimpl.h.
{ return m_impl.partOfGroups(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::partOfGroups().
pathFragment()
template<class Base > QCString DefinitionMixin< Base >::pathFragment () const inline override
Definition at line 272 of file definitionimpl.h.
    { return m_impl.pathFragment(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::pathFragment().
qualifiedName()
template<class Base > QCString DefinitionMixin< Base >::qualifiedName () const inline override
Reimplemented in MemberDefImpl, and ModuleDefImpl.
Definition at line 161 of file definitionimpl.h.
{ return m_impl.qualifiedName(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::qualifiedName().
Referenced by MemberDefImpl::qualifiedName().
setArtificial()
template<class Base > void DefinitionMixin< Base >::setArtificial (bool b) inline override
Definition at line 244 of file definitionimpl.h.
    { m_impl.setArtificial(b); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setArtificial().
setBodyDef()
template<class Base > void DefinitionMixin< Base >::setBodyDef (const FileDef * fd) inline override
Definition at line 224 of file definitionimpl.h.
    { m_impl.setBodyDef(fd); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setBodyDef().
setBodySegment()
template<class Base > void DefinitionMixin< Base >::setBodySegment (int defLine, int bls, int ble) inline override
Definition at line 222 of file definitionimpl.h.
    { m_impl.setBodySegment(defLine,bls,ble); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setBodySegment().
setBriefDescription()
template<class Base > void DefinitionMixin< Base >::setBriefDescription (const QCString & brief, const QCString & briefFile, int briefLine) inline override
Reimplemented in MemberDefImpl.
Definition at line 214 of file definitionimpl.h.
    { m_impl.setBriefDescription(brief,briefFile,briefLine); }
References DefinitionMixin< Base >::briefFile(), DefinitionMixin< Base >::briefLine(), DefinitionMixin< Base >::m_impl, and DefinitionImpl::setBriefDescription().
Referenced by MemberDefImpl::setBriefDescription().
setDefFile()
template<class Base > void DefinitionMixin< Base >::setDefFile (const QCString & df, int defLine, int defColumn) inline override
Definition at line 210 of file definitionimpl.h.
    { m_impl.setDefFile(df,defLine,defColumn); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setDefFile().
setDocumentation()
template<class Base > void DefinitionMixin< Base >::setDocumentation (const QCString & doc, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE) inline override
Reimplemented in MemberDefImpl.
Definition at line 212 of file definitionimpl.h.
    { m_impl.setDocumentation(doc,docFile,docLine,stripWhiteSpace); }
References DefinitionMixin< Base >::docFile(), DefinitionMixin< Base >::docLine(), DefinitionMixin< Base >::m_impl, DefinitionImpl::setDocumentation(), and stripWhiteSpace().
Referenced by MemberDefImpl::setDocumentation().
setExported()
template<class Base > void DefinitionMixin< Base >::setExported (bool b) inline override
Definition at line 246 of file definitionimpl.h.
    { m_impl.setExported(b); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setExported().
setHidden()
template<class Base > void DefinitionMixin< Base >::setHidden (bool b) inline override
Reimplemented in MemberDefImpl.
Definition at line 242 of file definitionimpl.h.
    { m_impl.setHidden(b); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setHidden().
Referenced by MemberDefImpl::setHidden().
setId()
template<class Base > void DefinitionMixin< Base >::setId (const QCString & name) inline override
Definition at line 209 of file definitionimpl.h.
{ m_impl.setId(name); }
References DefinitionMixin< Base >::m_impl, DefinitionMixin< Base >::name(), and DefinitionImpl::setId().
Referenced by ModuleManager::addTagInfo().
setInbodyDocumentation()
template<class Base > void DefinitionMixin< Base >::setInbodyDocumentation (const QCString & doc, const QCString & docFile, int docLine) inline override
Reimplemented in MemberDefImpl.
Definition at line 216 of file definitionimpl.h.
    { m_impl.setInbodyDocumentation(doc,docFile,docLine); }
References DefinitionMixin< Base >::docFile(), DefinitionMixin< Base >::docLine(), DefinitionMixin< Base >::m_impl, and DefinitionImpl::setInbodyDocumentation().
Referenced by MemberDefImpl::setInbodyDocumentation().
setLanguage()
template<class Base > void DefinitionMixin< Base >::setLanguage (SrcLangExt lang) inline override
Definition at line 248 of file definitionimpl.h.
    { m_impl.setLanguage(lang); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setLanguage().
setLocalName()
template<class Base > void DefinitionMixin< Base >::setLocalName (const QCString & name) inline override
Definition at line 276 of file definitionimpl.h.
    { m_impl.setLocalName(name); }
References DefinitionMixin< Base >::m_impl, DefinitionMixin< Base >::name(), and DefinitionImpl::setLocalName().
setName()
template<class Base > void DefinitionMixin< Base >::setName (const QCString & name) inline override
Reimplemented in NamespaceDefImpl.
Definition at line 208 of file definitionimpl.h.
{ m_impl.setName(name); }
References DefinitionMixin< Base >::m_impl, DefinitionMixin< Base >::name(), and DefinitionImpl::setName().
Referenced by NamespaceDefImpl::setName().
setOuterScope()
template<class Base > void DefinitionMixin< Base >::setOuterScope (Definition * def) inline override
Definition at line 240 of file definitionimpl.h.
    { m_impl.setOuterScope(def); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setOuterScope().
setReference()
template<class Base > void DefinitionMixin< Base >::setReference (const QCString & r) inline override
Definition at line 218 of file definitionimpl.h.
    { m_impl.setReference(r); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setReference().
Referenced by ModuleManager::addTagInfo().
setRefItems()
template<class Base > void DefinitionMixin< Base >::setRefItems (const RefItemVector & sli) inline override
Definition at line 230 of file definitionimpl.h.
    { m_impl.setRefItems(sli); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setRefItems().
symbolName()
template<class Base > QCString DefinitionMixin< Base >::symbolName () const inline override
Definition at line 162 of file definitionimpl.h.
{ return m_impl.symbolName(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::symbolName().
toDefinition_()
template<class Base > Definition * DefinitionMixin< Base >::toDefinition_ () inline override private
Definition at line 294 of file definitionimpl.h.
{ return this; }
toDefinitionImpl_()
template<class Base > const DefinitionImpl * DefinitionMixin< Base >::toDefinitionImpl_ () const inline override private
Definition at line 296 of file definitionimpl.h.
{ return &m_impl; }
References DefinitionMixin< Base >::m_impl.
toDefinitionMutable_()
template<class Base > DefinitionMutable * DefinitionMixin< Base >::toDefinitionMutable_ () inline override private
Definition at line 295 of file definitionimpl.h.
{ return this; }
writeDocAnchorsToTagFile()
template<class Base > void DefinitionMixin< Base >::writeDocAnchorsToTagFile (TextStream & fs) const inline override
Definition at line 274 of file definitionimpl.h.
    { m_impl.writeDocAnchorsToTagFile(fs); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeDocAnchorsToTagFile().
writeInlineCode()
template<class Base > void DefinitionMixin< Base >::writeInlineCode (OutputList & ol, const QCString & scopeName) const inline override
Definition at line 252 of file definitionimpl.h.
    { m_impl.writeInlineCode(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeInlineCode().
writeNavigationPath()
template<class Base > void DefinitionMixin< Base >::writeNavigationPath (OutputList & ol) const inline override
Definition at line 264 of file definitionimpl.h.
    { m_impl.writeNavigationPath(ol); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeNavigationPath().
writeQuickMemberLinks()
template<class Base > void DefinitionMixin< Base >::writeQuickMemberLinks (OutputList & ol, const MemberDef * md) const inline override
Reimplemented in FileDefImpl, GroupDefImpl, and NamespaceDefImpl.
Definition at line 268 of file definitionimpl.h.
    { m_impl.writeQuickMemberLinks(ol,md); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeQuickMemberLinks().
writeSourceDef()
template<class Base > void DefinitionMixin< Base >::writeSourceDef (OutputList & ol, const QCString & scopeName) const inline override
Definition at line 250 of file definitionimpl.h.
    { m_impl.writeSourceDef(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSourceDef().
writeSourceReffedBy()
template<class Base > void DefinitionMixin< Base >::writeSourceReffedBy (OutputList & ol, const QCString & scopeName) const inline override
Definition at line 260 of file definitionimpl.h.
    { m_impl.writeSourceReffedBy(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSourceReffedBy().
writeSourceRefs()
template<class Base > void DefinitionMixin< Base >::writeSourceRefs (OutputList & ol, const QCString & scopeName) const inline override
Definition at line 258 of file definitionimpl.h.
    { m_impl.writeSourceRefs(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSourceRefs().
writeSummaryLinks()
template<class Base > void DefinitionMixin< Base >::writeSummaryLinks (OutputList & ol) const inline override
Reimplemented in FileDefImpl, GroupDefImpl, ModuleDefImpl, and NamespaceDefImpl.
Definition at line 270 of file definitionimpl.h.
    { m_impl.writeSummaryLinks(ol); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSummaryLinks().
writeToc()
template<class Base > void DefinitionMixin< Base >::writeToc (OutputList & ol, const LocalToc & lt) const inline override
Definition at line 280 of file definitionimpl.h.
    { m_impl.writeToc(ol,lt); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeToc().
xrefListItems()
template<class Base > const RefItemVector & DefinitionMixin< Base >::xrefListItems () const inline override
Definition at line 196 of file definitionimpl.h.
{ return m_impl.xrefListItems(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::xrefListItems().
Member Data Documentation
m_impl
template<class Base > DefinitionImpl DefinitionMixin< Base >::m_impl private
Definition at line 298 of file definitionimpl.h.
Referenced by DefinitionMixin< Base >::_setSymbolName(), DefinitionMixin< Base >::_symbolName(), DefinitionMixin< Base >::addInnerCompound(), DefinitionMixin< Base >::addSectionsToDefinition(), DefinitionMixin< Base >::addSectionsToIndex(), DefinitionMixin< Base >::addSourceReferencedBy(), DefinitionMixin< Base >::addSourceReferences(), DefinitionMixin< Base >::briefDescription(), DefinitionMixin< Base >::briefDescriptionAsTooltip(), DefinitionMixin< Base >::briefFile(), DefinitionMixin< Base >::briefLine(), DefinitionMixin< Base >::computeTooltip(), DefinitionMixin< Base >::docFile(), DefinitionMixin< Base >::docLine(), DefinitionMixin< Base >::documentation(), DefinitionMixin< Base >::externalReference(), DefinitionMixin< Base >::findInnerCompound(), DefinitionMixin< Base >::getBodyDef(), DefinitionMixin< Base >::getDefColumn(), DefinitionMixin< Base >::getDefFileExtension(), DefinitionMixin< Base >::getDefFileName(), DefinitionMixin< Base >::getDefLine(), DefinitionMixin< Base >::getEndBodyLine(), DefinitionMixin< Base >::getLanguage(), DefinitionMixin< Base >::getOuterScope(), DefinitionMixin< Base >::getReference(), DefinitionMixin< Base >::getReferencedByMembers(), DefinitionMixin< Base >::getReferencesMembers(), DefinitionMixin< Base >::getSectionRefs(), DefinitionMixin< Base >::getSourceAnchor(), DefinitionMixin< Base >::getSourceFileBase(), DefinitionMixin< Base >::getStartBodyLine(), DefinitionMixin< Base >::getStartDefLine(), DefinitionMixin< Base >::hasBriefDescription(), DefinitionMixin< Base >::hasDocumentation(), DefinitionMixin< Base >::hasSections(), DefinitionMixin< Base >::hasSourceReffedBy(), DefinitionMixin< Base >::hasSourceRefs(), DefinitionMixin< Base >::hasSources(), DefinitionMixin< Base >::hasUserDocumentation(), DefinitionMixin< Base >::id(), DefinitionMixin< Base >::inbodyDocumentation(), DefinitionMixin< Base >::inbodyFile(), DefinitionMixin< Base >::inbodyLine(), DefinitionMixin< Base >::isAnonymous(), DefinitionMixin< Base >::isArtificial(), DefinitionMixin< Base >::isExported(), DefinitionMixin< Base >::isHidden(), DefinitionMixin< Base >::isLinkableViaGroup(), DefinitionMixin< Base >::isReference(), DefinitionMixin< Base >::isVisible(), DefinitionMixin< Base >::isVisibleInProject(), DefinitionMixin< Base >::localName(), DefinitionMixin< Base >::makePartOfGroup(), DefinitionMixin< Base >::mergeReferencedBy(), DefinitionMixin< Base >::mergeReferences(), DefinitionMixin< Base >::mergeRefItems(), DefinitionMixin< Base >::name(), DefinitionMixin< Base >::navigationPathAsString(), DefinitionMixin< Base >::partOfGroups(), DefinitionMixin< Base >::pathFragment(), DefinitionMixin< Base >::qualifiedName(), DefinitionMixin< Base >::setArtificial(), DefinitionMixin< Base >::setBodyDef(), DefinitionMixin< Base >::setBodySegment(), DefinitionMixin< Base >::setBriefDescription(), DefinitionMixin< Base >::setDefFile(), DefinitionMixin< Base >::setDocumentation(), DefinitionMixin< Base >::setExported(), DefinitionMixin< Base >::setHidden(), DefinitionMixin< Base >::setId(), DefinitionMixin< Base >::setInbodyDocumentation(), DefinitionMixin< Base >::setLanguage(), DefinitionMixin< Base >::setLocalName(), DefinitionMixin< Base >::setName(), DefinitionMixin< Base >::setOuterScope(), DefinitionMixin< Base >::setReference(), DefinitionMixin< Base >::setRefItems(), DefinitionMixin< Base >::symbolName(), DefinitionMixin< Base >::toDefinitionImpl_(), DefinitionMixin< Base >::writeDocAnchorsToTagFile(), DefinitionMixin< Base >::writeInlineCode(), DefinitionMixin< Base >::writeNavigationPath(), DefinitionMixin< Base >::writeQuickMemberLinks(), DefinitionMixin< Base >::writeSourceDef(), DefinitionMixin< Base >::writeSourceReffedBy(), DefinitionMixin< Base >::writeSourceRefs(), DefinitionMixin< Base >::writeSummaryLinks(), DefinitionMixin< Base >::writeToc(), and DefinitionMixin< Base >::xrefListItems().
The documentation for this class was generated from the following file:
src/definitionimpl.h