Doxygen: DirEntry Class Reference
DirEntry Class Reference
#include <src/dir.h>
Classes
struct Private
Public Member Functions
~DirEntry ()
DirEntry (const DirEntry &)
DirEntry & operator= (const DirEntry &)
DirEntry (DirEntry &&)
DirEntry & operator= (DirEntry &&)
bool is_directory () const
bool is_regular_file () const
bool is_symlink () const
std::string path () const
Private Member Functions
DirEntry ()
Private Attributes
std::unique_ptr< Private > p
Friends
class DirIterator
Detailed Description
Definition at line 24 of file dir.h.
Constructor & Destructor Documentation
~DirEntry()
DirEntry::~DirEntry () default
References DirEntry().
DirEntry() [1/3]
DirEntry::DirEntry (const DirEntry & de)
Definition at line 37 of file dir.cpp.
                                     : p(std::make_unique<Private>())
{
  p->entry = de.p->entry;
}
References DirEntry(), and p.
Referenced by DirEntry(), DirEntry(), operator=(), operator=(), and ~DirEntry().
DirEntry() [2/3]
DirEntry::DirEntry (DirEntry && de)
Definition at line 52 of file dir.cpp.
                                : p(std::make_unique<Private>())
{
  p = std::move(de.p);
}
References DirEntry(), and p.
DirEntry() [3/3]
DirEntry::DirEntry () private
Definition at line 33 of file dir.cpp.
                   : p(std::make_unique<Private>())
{
}
References p.
Member Function Documentation
is_directory()
bool DirEntry::is_directory () const
Definition at line 65 of file dir.cpp.
{
  return p->entry.is_directory();
}
References p.
is_regular_file()
bool DirEntry::is_regular_file () const
Definition at line 70 of file dir.cpp.
{
  return p->entry.is_regular_file();
}
References p.
is_symlink()
bool DirEntry::is_symlink () const
Definition at line 75 of file dir.cpp.
{
  return p->entry.is_symlink();
}
References p.
operator=() [1/2]
DirEntry & DirEntry::operator= (const DirEntry & de)
Definition at line 42 of file dir.cpp.
{
  if (this!=&de)
  {
    p = std::make_unique<Private>();
    p->entry = de.p->entry;
  }
  return *this;
}
References DirEntry(), and p.
operator=() [2/2]
DirEntry & DirEntry::operator= (DirEntry && de)
Definition at line 57 of file dir.cpp.
{
  p = std::move(de.p);
  return *this;
}
References DirEntry(), and p.
path()
std::string DirEntry::path () const
Definition at line 80 of file dir.cpp.
{
  return p->entry.path().string();
}
References p.
Friends And Related Symbol Documentation
DirIterator
friend class DirIterator friend
Definition at line 37 of file dir.h.
References DirIterator.
Referenced by DirIterator.
Member Data Documentation
p
std::unique_ptr<Private> DirEntry::p private
Definition at line 40 of file dir.h.
Referenced by DirEntry(), DirEntry(), DirEntry(), is_directory(), is_regular_file(), is_symlink(), operator=(), operator=(), and path().
The documentation for this class was generated from the following files:
src/dir.h
src/dir.cpp