Doxygen: IndexIntf Class Reference
IndexIntf Class Reference abstract
Abstract interface for index generators.
#include <src/indexlist.h>
Public Member Functions
virtual void initialize ()=0
virtual void finalize ()=0
virtual void incContentsDepth ()=0
virtual void decContentsDepth ()=0
virtual void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex, bool addToNavIndex, const Definition *def)=0
virtual void addIndexItem (const Definition *context, const MemberDef *md, const QCString &sectionAnchor, const QCString &title)=0
virtual void addIndexFile (const QCString &name)=0
virtual void addImageFile (const QCString &)=0
virtual void addStyleSheetFile (const QCString &)=0
Detailed Description
Abstract interface for index generators.
Definition at line 32 of file indexlist.h.
Member Function Documentation
addContentsItem()
virtual void IndexIntf::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex, bool addToNavIndex, const Definition * def) pure virtual
Implemented in Crawlmap, DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp, and Sitemap.
References addContentsItem().
Referenced by addContentsItem(), and IndexList::addContentsItem().
addImageFile()
virtual void IndexIntf::addImageFile (const QCString &) pure virtual
Implemented in Crawlmap, DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp, and Sitemap.
References addImageFile().
Referenced by addImageFile(), and IndexList::addImageFile().
addIndexFile()
virtual void IndexIntf::addIndexFile (const QCString & name) pure virtual
Implemented in Crawlmap, DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp, and Sitemap.
References addIndexFile().
Referenced by addIndexFile(), and IndexList::addIndexFile().
addIndexItem()
virtual void IndexIntf::addIndexItem (const Definition * context, const MemberDef * md, const QCString & sectionAnchor, const QCString & title) pure virtual
Implemented in Crawlmap, DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp, and Sitemap.
References addIndexItem().
Referenced by addIndexItem(), and IndexList::addIndexItem().
addStyleSheetFile()
virtual void IndexIntf::addStyleSheetFile (const QCString &) pure virtual
Implemented in Crawlmap, DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp, and Sitemap.
References addStyleSheetFile().
Referenced by addStyleSheetFile(), and IndexList::addStyleSheetFile().
decContentsDepth()
virtual void IndexIntf::decContentsDepth () pure virtual
Implemented in Crawlmap, DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp, and Sitemap.
References decContentsDepth().
Referenced by decContentsDepth(), and IndexList::decContentsDepth().
finalize()
virtual void IndexIntf::finalize () pure virtual
Implemented in Crawlmap, DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp, and Sitemap.
References finalize().
Referenced by finalize(), and IndexList::finalize().
incContentsDepth()
virtual void IndexIntf::incContentsDepth () pure virtual
Implemented in Crawlmap, DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp, and Sitemap.
References incContentsDepth().
Referenced by incContentsDepth(), and IndexList::incContentsDepth().
initialize()
virtual void IndexIntf::initialize () pure virtual
Implemented in Crawlmap, DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp, and Sitemap.
References initialize().
Referenced by initialize(), and IndexList::initialize().
The documentation for this class was generated from the following file:
src/indexlist.h