Doxygen: TranslatorSwedish Class Reference
TranslatorSwedish Class Reference
#include <src/translator_sv.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description Orginal: Here is a list of all design unit members with links to the Entities they belong to:
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool single) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
Orginal: Here are the interfaces with brief descriptions:
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
Orginal: This inheritance list is sorted roughly, but not completely, alphabetically:
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
Orginal: Here are the structs with brief descriptions:
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
Orginal: Here are the exceptions with brief descriptions:
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
Orginal: This inheritance list is sorted roughly, but not completely, alphabetically:
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
QCString trDesignUnitDocumentation () override
VHDL design unit documentation.
QCString trConcept (bool first_capital, bool) override
C++20 concept.
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
QCString trPackageList () override
QCString trFlowchart () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 164 of file translator_sv.h.
Member Function Documentation
getLanguageString()
QCString TranslatorSwedish::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 194 of file translator_sv.h.
    {
      return "0x41D Swedish";
    }
idLanguage()
QCString TranslatorSwedish::idLanguage () inline override virtual
Implements Translator.
Definition at line 168 of file translator_sv.h.
    { return "swedish"; }
latexLanguageSupportCommand()
QCString TranslatorSwedish::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 185 of file translator_sv.h.
    {
      return "\\usepackage[swedish]{babel}\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorSwedish::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1988 of file translator_sv.h.
    { return "Ytterliga rvda medlemmar"; }
trAll()
QCString TranslatorSwedish::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1501 of file translator_sv.h.
    {
      return "Alla";
    }
trAndMore()
QCString TranslatorSwedish::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1966 of file translator_sv.h.
    { return "och "+number+" flera..."; }
trAttention()
QCString TranslatorSwedish::trAttention () inline override virtual
Implements Translator.
Definition at line 1092 of file translator_sv.h.
    {
      return "Observera";
    }
trAuthor()
QCString TranslatorSwedish::trAuthor (bool first_capital, bool) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1374 of file translator_sv.h.
    {
      return createNoun(first_capital, false, "frfattare", "");
    }
References Translator::createNoun().
trBug()
QCString TranslatorSwedish::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1261 of file translator_sv.h.
    {
      return "Bugg";
    }
trBugList()
QCString TranslatorSwedish::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1266 of file translator_sv.h.
    {
      return "Bugglista";
    }
trCallerGraph()
QCString TranslatorSwedish::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1621 of file translator_sv.h.
    {
      return "Hr r anropsgrafen fr denna funktion:";
    }
trCallGraph()
QCString TranslatorSwedish::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1506 of file translator_sv.h.
    {
      return "Hr r anropsdiagrammet fr den hr funktionen:";
    }
trCiteReferences()
QCString TranslatorSwedish::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1942 of file translator_sv.h.
    { return "Bibliografiska Referenser"; }
trClass()
QCString TranslatorSwedish::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1309 of file translator_sv.h.
    {
      return createNoun(first_capital, singular, "klass", "er");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trClassDiagram()
QCString TranslatorSwedish::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 638 of file translator_sv.h.
    {
      return "Klassdiagram fr "+clName;
    }
trClassDocumentation()
QCString TranslatorSwedish::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 519 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentation ver datastrukturer";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassdokumentation";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorSwedish::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1223 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorSwedish::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 302 of file translator_sv.h.
    { return "Klasshierarki"; }
trClassHierarchyDescription()
QCString TranslatorSwedish::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 361 of file translator_sv.h.
    { return "Denna lista ver arv r grovt, men inte helt, "
             "sorterad i alfabetisk ordning:";
    }
trClassMethods()
QCString TranslatorSwedish::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2026 of file translator_sv.h.
    {
      return "Klassmetoder";
    }
trCode()
QCString TranslatorSwedish::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 992 of file translator_sv.h.
    {
      return "kllkod";
    }
trCollaborationDiagram()
QCString TranslatorSwedish::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 947 of file translator_sv.h.
    {
      return "Samarbetsdiagram fr "+clName+":";
    }
trCompoundIndex()
QCString TranslatorSwedish::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 492 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Index ver datastrukturer";
      }
      else
      {
        return "Klassindex";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorSwedish::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1676 of file translator_sv.h.
    { return "Datatypsindex"; }
trCompoundList()
QCString TranslatorSwedish::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 306 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasslista";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorSwedish::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 376 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Hr fljer datastrukturerna med korta beskrivningar:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Hr fljer klasserna med korta beskrivningar:";
      }
      else
      {
        return "Hr fljer klasserna, strukterna, unionerna och "
               "grnssnitten med korta beskrivningar:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorSwedish::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1649 of file translator_sv.h.
    { return "Hr r datatyperna med en kort beskrivning:"; }
trCompoundListFortran()
QCString TranslatorSwedish::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1641 of file translator_sv.h.
    { return "Datatyplista"; }
trCompoundMembers()
QCString TranslatorSwedish::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 323 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dataflt";
      }
      else
      {
        return "Klassmedlemmar";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorSwedish::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 395 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll)
      {
        result+="dokumenterade ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktur- och unions-flt";
      }
      else
      {
        result+="klassmedlemmar";
      }
      result+=" med lnkar till ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktur/union-dokumentationen fr varje flt:";
        }
        else
        {
          result+="klassdokumentationen fr varje medlem:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" strukturerna/unionerna de tillhr:";
        }
        else
        {
          result+="klasserna de tillhr:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorSwedish::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1653 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll)
      {
        result+="dokumenterade ";
      }
      result+="datatypsmedlemmar";
      result+=" med lnkar till ";
      if (!extractAll)
      {
         result+="dokumentation fr varje medlem";
      }
      else
      {
         result+="klasserna de hr till:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorSwedish::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1645 of file translator_sv.h.
    { return "Dataflt"; }
trCompoundReference()
QCString TranslatorSwedish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 710 of file translator_sv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:  result+=" klass"; break;
        case ClassDef::Struct: result+=" strukt"; break;
        case ClassDef::Union:  result+=" union"; break;
        case ClassDef::Interface:  result+=" grnssnitt"; break;
        case ClassDef::Protocol:   result+=" protokoll"; break;
        case ClassDef::Category:   result+=" kategori"; break;
        case ClassDef::Exception:  result+=" undantag"; break;
        default: break;
      }
      if (isTemplate) result+="-mall";
      result+=" referens";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorSwedish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1717 of file translator_sv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Modul"; break;
        case ClassDef::Struct:     result+=" Typ"; break;
        case ClassDef::Union:      result+=" Union"; break;
        case ClassDef::Interface:  result+=" Grnssnitt"; break;
        case ClassDef::Protocol:   result+=" Protokoll"; break;
        case ClassDef::Category:   result+=" Kategori"; break;
        case ClassDef::Exception:  result+=" Undantag"; break;
        default: break;
      }
      if (isTemplate) result+="-mall";
      result+=" referens";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice()
QCString TranslatorSwedish::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) inline override virtual
Implements Translator.
Definition at line 2320 of file translator_sv.h.
    {
      QCString result=clName;
      if (isLocal) result+=" Lokal";
      switch(compType)
      {
        case ClassDef::Class:      result+=" Klass"; break;
        case ClassDef::Struct:     result+=" Struktur"; break;
        case ClassDef::Union:      result+=" Unions"; break;
        case ClassDef::Interface:  result+=" Grnssnitts"; break;
        case ClassDef::Protocol:   result+=" Protokoll"; break;
        case ClassDef::Category:   result+=" Kategori"; break;
        case ClassDef::Exception:  result+=" Undantags"; break;
        default: break;
      }
      result+="referens";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorSwedish::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 614 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trCompoundType()
QCString TranslatorSwedish::trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) inline override virtual
the compound type as used for the xrefitems
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2426 of file translator_sv.h.
    {
      QCString result;
      switch(compType)
      {
        case ClassDef::Class:
          if (lang == SrcLangExt::Fortran) trType(true,true);
          else result=trClass(true,true);
          break;
        case ClassDef::Struct:     result="Strukt"; break;
        case ClassDef::Union:      result="Union"; break;
        case ClassDef::Interface:  result="Grnssnitt"; break;
        case ClassDef::Protocol:   result="Protokoll"; break;
        case ClassDef::Category:   result="Kategori"; break;
        case ClassDef::Exception:  result="Undantag"; break;
        case ClassDef::Service:    result="Tjnstere"; break;
        case ClassDef::Singleton:  result="Singleton"; break;
        default: break;
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, Fortran, ClassDef::Interface, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, ClassDef::Struct, trClass(), trType(), and ClassDef::Union.
trConcept()
QCString TranslatorSwedish::trConcept (bool first_capital, bool) inline override virtual
C++20 concept.
Implements Translator.
Definition at line 2368 of file translator_sv.h.
    {
      return createNoun(first_capital, false, "koncept", "");
    }
References Translator::createNoun().
trConceptDefinition()
QCString TranslatorSwedish::trConceptDefinition () inline override virtual
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2402 of file translator_sv.h.
    {
      return "Konceptdefinition";
    }
trConceptDocumentation()
QCString TranslatorSwedish::trConceptDocumentation () inline override virtual
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2389 of file translator_sv.h.
    { return "Konceptdokumentation"; }
trConceptIndex()
QCString TranslatorSwedish::trConceptIndex () inline override virtual
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2385 of file translator_sv.h.
    { return "Konceptindex"; }
trConceptList()
QCString TranslatorSwedish::trConceptList () inline override virtual
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2381 of file translator_sv.h.
    { return "Konceptlista"; }
trConceptListDescription()
QCString TranslatorSwedish::trConceptListDescription (bool extractAll) inline override virtual
used as an introduction to the concept list
Implements Translator.
Definition at line 2393 of file translator_sv.h.
    {
      QCString result="Hr r listan ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="koncept med en kort beskrivning:";
      return result;
    }
trConceptReference()
QCString TranslatorSwedish::trConceptReference (const QCString & conceptName) inline override virtual
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2373 of file translator_sv.h.
    {
      QCString result=conceptName;
      result+=" Konceptreferens";
      return result;
    }
trConstantDocumentation()
QCString TranslatorSwedish::trConstantDocumentation () inline override virtual
Implements Translator.
Definition at line 2223 of file translator_sv.h.
    {
        return "Konstantdokumentation";
    }
trConstantGroupReference()
QCString TranslatorSwedish::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2063 of file translator_sv.h.
    {
      QCString result=namespaceName;
      result+=" Referens till konstantgrupp";
      return result;
    }
trConstantGroups()
QCString TranslatorSwedish::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2059 of file translator_sv.h.
    { return "Konstantgrupper"; }
trConstants()
QCString TranslatorSwedish::trConstants () inline override virtual
Implements Translator.
Definition at line 2219 of file translator_sv.h.
    {
        return "Konstanter";
    }
trConstructorDocumentation()
QCString TranslatorSwedish::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 957 of file translator_sv.h.
    {
      return "Dokumentation av konstruktorer och destruktorer";
    }
trCopyright()
QCString TranslatorSwedish::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1946 of file translator_sv.h.
    { return "Copyright"; }
trCustomReference()
QCString TranslatorSwedish::trCustomReference (const QCString & name) inline override virtual
Implements Translator.
Definition at line 2215 of file translator_sv.h.
    { return QCString(name)+"referens"; }
trDataMemberDocumentation()
QCString TranslatorSwedish::trDataMemberDocumentation () inline override virtual
Implements Translator.
Definition at line 2350 of file translator_sv.h.
    {
        return "Datamedlemsdokumentation";
    }
trDataMembers()
QCString TranslatorSwedish::trDataMembers () inline override virtual
Implements Translator.
Definition at line 2346 of file translator_sv.h.
    {
        return "Datamedlemmar";
    }
trDataTypes()
QCString TranslatorSwedish::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1700 of file translator_sv.h.
    { return "Datatyper"; }
trDate()
QCString TranslatorSwedish::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 652 of file translator_sv.h.
    { return "Datum"; }
trDateTime()
QCString TranslatorSwedish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1895 of file translator_sv.h.
    {
      static const char *days[]   = { "Mn","Tis","Ons","Tor","Fre","Lr","Sn" };
      static const char *months[] = { "Jan","Feb","Mar","Apr","Maj","Jun","Jul","Aug","Sep","Okt","Nov","Dec" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorSwedish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1915 of file translator_sv.h.
    {
      static const char *days_short[]   = { "mn", "tis", "ons", "tor", "fre", "lr", "sn" };
      static const char *days_full[]    = { "mndag", "tisdag", "onsdag", "torsdag", "fredag", "lrdag", "sndag" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorSwedish::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1931 of file translator_sv.h.
    {
      static const char *dayPeriod[] = { "fm", "em" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorSwedish::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 924 of file translator_sv.h.
    {
      return "Definition p rad @0 i filen @1.";
    }
trDefinedIn()
QCString TranslatorSwedish::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 290 of file translator_sv.h.
    { return "definierad i"; }
trDefinedInSourceFile()
QCString TranslatorSwedish::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 928 of file translator_sv.h.
    {
      return "Definition i filen @0.";
    }
trDefineDocumentation()
QCString TranslatorSwedish::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 584 of file translator_sv.h.
    { return "Dokumentation ver makrodefinitioner"; }
trDefines()
QCString TranslatorSwedish::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 548 of file translator_sv.h.
    { return "Makron"; }
trDefineValue()
QCString TranslatorSwedish::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1251 of file translator_sv.h.
    {
      return "Vrde:";
    }
trDeprecated()
QCString TranslatorSwedish::trDeprecated () inline override virtual
Implements Translator.
Definition at line 937 of file translator_sv.h.
    {
      return "Obsolet";
    }
trDeprecatedList()
QCString TranslatorSwedish::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1429 of file translator_sv.h.
    {
      return "Lista ver frldrade";
    }
trDesignUnitDocumentation()
QCString TranslatorSwedish::trDesignUnitDocumentation () inline override virtual
VHDL design unit documentation.
Implements Translator.
Definition at line 2360 of file translator_sv.h.
    { return "Designenhetsdokumentation"; }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorSwedish::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Implements Translator.
Definition at line 2107 of file translator_sv.h.
    { return "Designenhetshirarki"; }
trDesignUnitIndex()
QCString TranslatorSwedish::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Implements Translator.
Definition at line 2125 of file translator_sv.h.
    { return "Designenhetsindex"; }
trDesignUnitList()
QCString TranslatorSwedish::trDesignUnitList () inline override virtual
VHDL design unit list.
Implements Translator.
Definition at line 2110 of file translator_sv.h.
    { return "Designenhetslista"; }
trDesignUnitListDescription()
QCString TranslatorSwedish::trDesignUnitListDescription () inline override virtual
VHDL design unit list description Orginal: Here is a list of all design unit members with links to the Entities they belong to:
Implements Translator.
Definition at line 2119 of file translator_sv.h.
    {
        return "Hr r en lista av alla designenhetsmedlemmar med lnkar till "
               "entiteterna som de hr till:";
    }
trDesignUnitMembers()
QCString TranslatorSwedish::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Implements Translator.
Definition at line 2113 of file translator_sv.h.
    { return "Designenhetsmedlemmar"; }
trDesignUnits()
QCString TranslatorSwedish::trDesignUnits () inline override virtual
VHDL design units.
Implements Translator.
Definition at line 2128 of file translator_sv.h.
    { return "Designenheter"; }
trDetailedDescription()
QCString TranslatorSwedish::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 210 of file translator_sv.h.
    { return "Detaljerad beskrivning"; }
trDetailLevel()
QCString TranslatorSwedish::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1958 of file translator_sv.h.
    { return "detaljniv"; }
trDetails()
QCString TranslatorSwedish::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 214 of file translator_sv.h.
    { return "Detaljer"; }
trDictionaries()
QCString TranslatorSwedish::trDictionaries () inline override virtual
Implements Translator.
Definition at line 2235 of file translator_sv.h.
    {
        return "Uppslagsverk";
    }
trDictionaryDocumentation()
QCString TranslatorSwedish::trDictionaryDocumentation () inline override virtual
Implements Translator.
Definition at line 2239 of file translator_sv.h.
    {
        return "Uppslagsverksdokumentation";
    }
trDir()
QCString TranslatorSwedish::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1596 of file translator_sv.h.
    {
      return createNoun(first_capital, singular, "katalog", "er");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorSwedish::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1950 of file translator_sv.h.
    { return QCString("Katalogberoendegraf fr ")+name+":"; }
trDirDocumentation()
QCString TranslatorSwedish::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1578 of file translator_sv.h.
    { return "Katalogdokumentation"; }
trDirectories()
QCString TranslatorSwedish::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1584 of file translator_sv.h.
    { return "Kataloger"; }
trDirIndex()
QCString TranslatorSwedish::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1572 of file translator_sv.h.
    { return "Katalogstruktur"; }
trDirReference()
QCString TranslatorSwedish::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1590 of file translator_sv.h.
    { QCString result=dirName; result+=" Katalogreferens"; return result; }
trDirRelation()
QCString TranslatorSwedish::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1834 of file translator_sv.h.
    {
      return QCString(name)+" Relation";
    }
trDocumentation()
QCString TranslatorSwedish::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 474 of file translator_sv.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentation"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorSwedish::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 560 of file translator_sv.h.
    { return "Egenupprknande typer"; }
trEnumerationTypeDocumentation()
QCString TranslatorSwedish::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 596 of file translator_sv.h.
    { return "Dokumentation ver egenupprknande typer"; }
trEnumerationValueDocumentation()
QCString TranslatorSwedish::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1629 of file translator_sv.h.
    { return "Upprknings-dokumentation"; }
trEnumerationValues()
QCString TranslatorSwedish::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 578 of file translator_sv.h.
    { return "Egenupprknade typers vrden"; }
trEnumGeneratedFromFiles()
QCString TranslatorSwedish::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1970 of file translator_sv.h.
    { QCString result = "Dokumentationen fr denna enum var genererad frn fjlande fil";
      if (!single) result += "er";
      result+=":";
      return result;
    }
trEnumName()
QCString TranslatorSwedish::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 282 of file translator_sv.h.
    { return "enum-namn"; }
trEnumReference()
QCString TranslatorSwedish::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1978 of file translator_sv.h.
    { return QCString(name)+" Enum-referens"; }
trEnumValue()
QCString TranslatorSwedish::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 286 of file translator_sv.h.
    { return "enum-vrde"; }
trEventDocumentation()
QCString TranslatorSwedish::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1446 of file translator_sv.h.
    {
      return "Hndelsedokumentation";
    }
trEvents()
QCString TranslatorSwedish::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1441 of file translator_sv.h.
    {
      return "Hndelser";
    }
trExamples()
QCString TranslatorSwedish::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 353 of file translator_sv.h.
    { return "Exempel"; }
trExamplesDescription()
QCString TranslatorSwedish::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 460 of file translator_sv.h.
    { return "Hr fljer en lista med alla exempel:"; }
trExceptionDocumentation()
QCString TranslatorSwedish::trExceptionDocumentation () inline override virtual
Implements Translator.
Definition at line 2316 of file translator_sv.h.
    {
        return "Undantagsdokumentation";
    }
trExceptionHierarchy()
QCString TranslatorSwedish::trExceptionHierarchy () inline override virtual
Implements Translator.
Definition at line 2307 of file translator_sv.h.
    {
        return "Undantagshirarki";
    }
trExceptionHierarchyDescription()
QCString TranslatorSwedish::trExceptionHierarchyDescription () inline override virtual
Orginal: This inheritance list is sorted roughly, but not completely, alphabetically:
Implements Translator.
Definition at line 2312 of file translator_sv.h.
    {
        return "Denna arvslista r grovt sorterad, men inte helt, i alfabetisk ordning:";
    }
trExceptionIndex()
QCString TranslatorSwedish::trExceptionIndex () inline override virtual
Implements Translator.
Definition at line 2294 of file translator_sv.h.
    {
        return "Undantagsindex";
    }
trExceptionList()
QCString TranslatorSwedish::trExceptionList () inline override virtual
Implements Translator.
Definition at line 2298 of file translator_sv.h.
    {
        return "Undantagslista";
    }
trExceptionListDescription()
QCString TranslatorSwedish::trExceptionListDescription () inline override virtual
Orginal: Here are the exceptions with brief descriptions:
Implements Translator.
Definition at line 2303 of file translator_sv.h.
    {
        return "Hr r undantagen med en kort beskrivning:";
    }
trExceptions()
QCString TranslatorSwedish::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 668 of file translator_sv.h.
    { return "Undantag"; }
trExtendsClass()
QCString TranslatorSwedish::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2018 of file translator_sv.h.
    {
      return "Utkar klass @0.";
    }
trFile()
QCString TranslatorSwedish::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1318 of file translator_sv.h.
    {
      return createNoun(first_capital, singular, "fil", "er");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorSwedish::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 538 of file translator_sv.h.
    { return "Fildokumentation"; }
trFileIn()
QCString TranslatorSwedish::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1871 of file translator_sv.h.
    {
      return "Fil i "+name;
    }
trFileIndex()
QCString TranslatorSwedish::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 507 of file translator_sv.h.
    { return "Filindex"; }
trFileList()
QCString TranslatorSwedish::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 319 of file translator_sv.h.
    { return "Fillista"; }
trFileListDescription()
QCString TranslatorSwedish::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 367 of file translator_sv.h.
    {
      QCString result="Hr fljer en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="filer, med en kort beskrivning:";
      return result;
    }
trFileMembers()
QCString TranslatorSwedish::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 336 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globala symboler";
      }
      else
      {
        return "Filmedlemmar";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorSwedish::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 437 of file translator_sv.h.
    {
      QCString result="Hr fljer en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funktioner, variabler, definitioner, enumerationer "
                "och typdefinitioner";
      }
      else
      {
        result+= "filmedlemmar";
      }
      result+= " med lnkar till ";
      if (extractAll)
        result+= "filerna de tillhr:";
      else
        result+= "dokumentationen:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorSwedish::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 732 of file translator_sv.h.
    {
      QCString result=fileName;
      result+=" filreferens";
      return result;
    }
trFlowchart()
QCString TranslatorSwedish::trFlowchart () inline override virtual
Implements Translator.
Definition at line 2418 of file translator_sv.h.
    { return "Fldesdiagram:"; }
trFriends()
QCString TranslatorSwedish::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 695 of file translator_sv.h.
    { return "Vnner"; }
trFunctionAndProc()
QCString TranslatorSwedish::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Implements Translator.
Definition at line 2131 of file translator_sv.h.
    { return "Funktioner/Procedurer/Processer"; }
trFunctionDocumentation()
QCString TranslatorSwedish::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 602 of file translator_sv.h.
    { return "Dokumentation ver funktioner"; }
trFunctions()
QCString TranslatorSwedish::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 566 of file translator_sv.h.
    { return "Funktioner"; }
trGeneratedAt()
QCString TranslatorSwedish::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 629 of file translator_sv.h.
    {
      QCString result="Skapad "+date;
      if (!projName.isEmpty()) result+=" fr "+projName;
      result+=" av";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorSwedish::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 274 of file translator_sv.h.
    { QCString result="Automatiskt skapad av Doxygen";
      if (!s.isEmpty()) result+=" fr "+s;
      result+=" frn kllkoden.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorSwedish::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 672 of file translator_sv.h.
    { return "Skapad av"; }
trGeneratedFromFiles()
QCString TranslatorSwedish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 879 of file translator_sv.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="Dokumentationen fr ";
      switch(compType)
      {
        case ClassDef::Class:      result+=vhdlOpt? "denna designenhets":"denna klass"; break;
        case ClassDef::Struct:     result+="denna strukt"; break;
        case ClassDef::Union:      result+="denna union"; break;
        case ClassDef::Interface:  result+="detta grnssnitt"; break;
        case ClassDef::Protocol:   result+="detta protokoll"; break;
        case ClassDef::Category:   result+="denna kategori"; break;
        case ClassDef::Exception:  result+="detta undantag"; break;
        default: break;
      }
      result+=" var genererad frn fljande fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorSwedish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1784 of file translator_sv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentationen fr ";
      switch(compType)
      {
        case ClassDef::Class:      result+="denna modul"; break;
        case ClassDef::Struct:     result+="denna typ"; break;
        case ClassDef::Union:      result+="denna union"; break;
        case ClassDef::Interface:  result+="detta grnssnitt"; break;
        case ClassDef::Protocol:   result+="detta protokoll"; break;
        case ClassDef::Category:   result+="denna kategori"; break;
        case ClassDef::Exception:  result+="detta undantag"; break;
        default: break;
      }
      result+=" genererades frn fljade fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorSwedish::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1363 of file translator_sv.h.
    {
      return createNoun(first_capital, singular, "global", "er");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorSwedish::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1846 of file translator_sv.h.
    {
      return "Global namnrymd";
    }
trGotoDocumentation()
QCString TranslatorSwedish::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 967 of file translator_sv.h.
    {
      return "G till denna fils dokumentation.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorSwedish::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 1000 of file translator_sv.h.
    {
      return "G till den grafiska klasshierarkin";
    }
trGotoSourceCode()
QCString TranslatorSwedish::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 962 of file translator_sv.h.
    {
      return "G till denna fils kllkod.";
    }
trGotoTextualHierarchy()
QCString TranslatorSwedish::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 1004 of file translator_sv.h.
    {
      return "G till den textbaserade klasshierarkin";
    }
trGraphicalHierarchy()
QCString TranslatorSwedish::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 996 of file translator_sv.h.
    {
      return "Grafisk klasshierarki";
    }
trGroup()
QCString TranslatorSwedish::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1336 of file translator_sv.h.
    {
      return createNoun(first_capital, singular, "grupp", "er");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorSwedish::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 486 of file translator_sv.h.
    { return "Hierarkiskt index"; }
trImplementedFromList()
QCString TranslatorSwedish::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1397 of file translator_sv.h.
    {
      return "Implementerar "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorSwedish::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1405 of file translator_sv.h.
    {
      return "Implementerad i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorSwedish::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 1096 of file translator_sv.h.
    {
      return "Den hr grafen visar vilka filer som direkt eller "
             "indirekt inkluderar denna filen:";
    }
trInclDepGraph()
QCString TranslatorSwedish::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 952 of file translator_sv.h.
    {
      return "Include-beroendediagram fr "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorSwedish::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1880 of file translator_sv.h.
    {
      return "Inkluderar fil i "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorSwedish::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 268 of file translator_sv.h.
    { return " med alla rvda medlemmar."; }
trInheritedByList()
QCString TranslatorSwedish::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 807 of file translator_sv.h.
    {
      return "rvd av "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorSwedish::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1982 of file translator_sv.h.
    { return QCString(members)+" rvd ifrn "+what; }
trInheritsList()
QCString TranslatorSwedish::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 797 of file translator_sv.h.
    {
      return "rver "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorSwedish::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 987 of file translator_sv.h.
    {
      return "Begynnelsevrde:";
    }
trInstanceMethods()
QCString TranslatorSwedish::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2034 of file translator_sv.h.
    {
      return "Instansmetoder";
    }
trInterfaceDocumentation()
QCString TranslatorSwedish::trInterfaceDocumentation () inline override virtual
Implements Translator.
Definition at line 2269 of file translator_sv.h.
    {
        return "Grnssnittsdokumentation";
    }
trInterfaceHierarchy()
QCString TranslatorSwedish::trInterfaceHierarchy () inline override virtual
Implements Translator.
Definition at line 2260 of file translator_sv.h.
    {
        return "Grnssnittshirarkin";
    }
trInterfaceHierarchyDescription()
QCString TranslatorSwedish::trInterfaceHierarchyDescription () inline override virtual
Orginal: This inheritance list is sorted roughly, but not completely, alphabetically:
Implements Translator.
Definition at line 2265 of file translator_sv.h.
    {
        return "Denna arvslista r grovt sorterad, men inte helt, i alfabetisk ordning:";
    }
trInterfaceIndex()
QCString TranslatorSwedish::trInterfaceIndex () inline override virtual
Implements Translator.
Definition at line 2247 of file translator_sv.h.
    {
        return "Grnssnittsindex";
    }
trInterfaceList()
QCString TranslatorSwedish::trInterfaceList () inline override virtual
Implements Translator.
Definition at line 2251 of file translator_sv.h.
    {
        return "Grnssnittslist";
    }
trInterfaceListDescription()
QCString TranslatorSwedish::trInterfaceListDescription () inline override virtual
Orginal: Here are the interfaces with brief descriptions:
Implements Translator.
Definition at line 2256 of file translator_sv.h.
    {
        return "Hr r grnssnitten med en kort beskrivning";
    }
trInterfaces()
QCString TranslatorSwedish::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2051 of file translator_sv.h.
    { return "Exporterade interface"; }
trInvariant()
QCString TranslatorSwedish::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 982 of file translator_sv.h.
    {
      return "Invariant";
    }
trISOLang()
QCString TranslatorSwedish::trISOLang () inline override virtual
Implements Translator.
Definition at line 190 of file translator_sv.h.
    {
      return "sv";
    }
trLegend()
QCString TranslatorSwedish::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1183 of file translator_sv.h.
    {
      return "frklaring";
    }
trLegendDocs()
QCString TranslatorSwedish::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1118 of file translator_sv.h.
    {
      return
        "Den hr sidan frklarar hur man ska tolka de grafer som doxygen "
        "genererar.<p>\n"
        "vervg fljande exempel:\n"
        "\\code\n"
        "/*! Osynlig klass p grund av trunkering */\n"
        "class Invisible { };\n\n"
        "/*! Trunkerad klass, rvningsrelationen r dold */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klass utan doxygen-kommentarer */\n"
        "class Undocumented { };\n\n"
        "/*! Klass som rvs med publikt arv */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! En template-klass */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klass som rvs med skyddat arv */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klass som rvs med privat arv */\n"
        "class PrivateBase { };\n\n"
        "/*! Klass som anvnds av den rvda klassen */\n"
        "class Used { };\n\n"
        "/*! Super-klass som rver ett antal andra klasser */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Detta resulterar i att fljande graf genereras:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Rektanglarna i den ovanstende grafen har fljande betydelser:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%En fylld gr rektangel representerar den strukt eller klass "
        "som har genererat grafen.</li>\n"
        "<li>%En rektangel med svart kant symboliserar en dokumenterad strukt eller klass.</li>\n"
        "<li>%En rektangel med gr kant symboliserar en odokumenterad strukt eller klass.</li>\n"
        "<li>%En klass med rd kant symboliserar en strukt eller klass dr "
        "alla dess relationer inte visas. %En graf trunkeras om den inte fr "
        "plats inom de givna grnserna.</li>\n"
        "</ul>\n"
        "<p>\n"
        "Pilarna har fljande betydelser:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%En mrkbl pil anvnds fr att visualisera en publik arvrelation "
        "mellan tv klasser.</li>\n"
        "<li>%En mrkgrn pil anvnds fr en skyddad arvsrelation.</li>\n"
        "<li>%En mrkrd pil anvnds fr en privat arvsrelation.\n</li>"
        "<li>%En strckad lila pil anvnds om en klass r innesluten eller "
        "anvnd av en annan klass. Vid pilen str namnet p den eller de "
        "variabler som klassen pilen pekar p kommer t.</li>\n"
        "<li>%En strckad gul pil symboliserar frhllandet mellan en "
        "template-instans och template-klassen, som den instantierades frn.\n"
        "Vid pilen str instansens template-parametrar.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorSwedish::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 1111 of file translator_sv.h.
    {
      return "Graffrklaring";
    }
trListOfAllMembers()
QCString TranslatorSwedish::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 256 of file translator_sv.h.
    { return "Lista ver alla medlemmar"; }
trLoading()
QCString TranslatorSwedish::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1840 of file translator_sv.h.
    {
      return "Laddar...";
    }
trMainPage()
QCString TranslatorSwedish::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 911 of file translator_sv.h.
    { return "Huvudsida"; }
trMember()
QCString TranslatorSwedish::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1354 of file translator_sv.h.
    {
      return createNoun(first_capital, singular, "medlem", "mar");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorSwedish::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 239 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentation av flt";
      }
      else
      {
        return "Dokumentation av datamedlemmar";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorSwedish::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 222 of file translator_sv.h.
    { return "Dokumentation av egenupprknande medlemmar"; }
trMemberFunctionDocumentation()
QCString TranslatorSwedish::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 226 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Dokumentation av medlemsfunktioner/-procedurer/-processer";
      }
      else
      {
        return "Dokumentation av medlemsfunktioner";
      }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran()
QCString TranslatorSwedish::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1637 of file translator_sv.h.
    { return "Dokumentation fr memlemsfunktion/subrutin"; }
trMemberList()
QCString TranslatorSwedish::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 260 of file translator_sv.h.
    { return "Medlemslista"; }
trMemberTypedefDocumentation()
QCString TranslatorSwedish::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 218 of file translator_sv.h.
    { return "Dokumentation av typdefinierade medlemmar"; }
trMethodDocumentation()
QCString TranslatorSwedish::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2041 of file translator_sv.h.
    {
      return "Metoddokumentation";
    }
trModule()
QCString TranslatorSwedish::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1776 of file translator_sv.h.
    {
      return createNoun(first_capital, singular, "modul", "er");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorSwedish::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 513 of file translator_sv.h.
    { return "Moduldokumentation"; }
trModuleIndex()
QCString TranslatorSwedish::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 480 of file translator_sv.h.
    { return "Modulindex"; }
trModuleReference()
QCString TranslatorSwedish::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1738 of file translator_sv.h.
    {
      QCString result=namespaceName;
      result+=" Modulreferens";
      return result;
    }
trModules()
QCString TranslatorSwedish::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 298 of file translator_sv.h.
    { return "Moduler"; }
trModulesDescription()
QCString TranslatorSwedish::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 468 of file translator_sv.h.
    { return "Hr fljer en lista ver alla moduler:"; }
trModulesIndex()
QCString TranslatorSwedish::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1769 of file translator_sv.h.
    { return "Modulindex"; }
trModulesList()
QCString TranslatorSwedish::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1704 of file translator_sv.h.
    { return "Modullista"; }
trModulesListDescription()
QCString TranslatorSwedish::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1708 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="moduler med en kort beskrivning:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorSwedish::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1750 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="documented ";
      result+="modulmedlemmar med lnkar till ";
      if (extractAll)
      {
        result+="moduldokumentationen fr varje medlem:";
      }
      else
      {
        result+="modulerna de hr till:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorSwedish::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1746 of file translator_sv.h.
    { return "Modulmedlemmar"; }
trMonth()
QCString TranslatorSwedish::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1923 of file translator_sv.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[]  = { "januari", "februari", "mars", "april", "maj", "juni", "juli", "augusti", "september", "oktober", "november", "december" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorSwedish::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 252 of file translator_sv.h.
    { return "Mer..."; }
trNamespace()
QCString TranslatorSwedish::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1327 of file translator_sv.h.
    {
      return createNoun(first_capital, singular, "namnrymd", "er");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorSwedish::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 859 of file translator_sv.h.
      { return "Namnrymd-dokumentation"; }
trNamespaceIndex()
QCString TranslatorSwedish::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 853 of file translator_sv.h.
    { return "Namnrymdsindex"; }
trNamespaceList()
QCString TranslatorSwedish::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 680 of file translator_sv.h.
    { return "Namnrymdslista"; }
trNamespaceListDescription()
QCString TranslatorSwedish::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 684 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="namnrymder med en kort beskrivning:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorSwedish::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 839 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="namnrymdsmedlemmar med lnkar till ";
      if (extractAll)
        result+=" namnrymd-dokumentationen fr varje medlem:";
      else
        result+="de namnrymder de tillhr:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorSwedish::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 835 of file translator_sv.h.
    { return "Namnrymdsmedlemmar"; }
trNamespaceReference()
QCString TranslatorSwedish::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 740 of file translator_sv.h.
    {
      QCString result=namespaceName;
      result+=" namnrymdreferens";
      return result;
    }
trNamespaces()
QCString TranslatorSwedish::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 869 of file translator_sv.h.
    { return "Namnrymder"; }
trNoMatches()
QCString TranslatorSwedish::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1858 of file translator_sv.h.
    {
      return "Inga trffar";
    }
trNote()
QCString TranslatorSwedish::trNote () inline override virtual
Implements Translator.
Definition at line 1017 of file translator_sv.h.
    {
      return "Notera";
    }
trOperationDocumentation()
QCString TranslatorSwedish::trOperationDocumentation () inline override virtual
Implements Translator.
Definition at line 2342 of file translator_sv.h.
    {
        return "Operationsdokumentation";
    }
trOperations()
QCString TranslatorSwedish::trOperations () inline override virtual
Implements Translator.
Definition at line 2338 of file translator_sv.h.
    {
        return "Operationer";
    }
trOverloadText()
QCString TranslatorSwedish::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1608 of file translator_sv.h.
    {
      return "Det hr r en verlagrad medlemsfunktion "
             "tillhandahllen fr bekvmlighet. Den enda som "
             "skiljer sig frn ovanstende funktion r vilka "
             "argument den tar emot.";
    }
trPackage()
QCString TranslatorSwedish::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1235 of file translator_sv.h.
    {
      return "Paket "+name;
    }
trPackageAttribs()
QCString TranslatorSwedish::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1482 of file translator_sv.h.
    {
      return "Paketattribut";
    }
trPackageFunctions()
QCString TranslatorSwedish::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1464 of file translator_sv.h.
    {
      return "Paketfunktioner";
    }
trPackageList()
QCString TranslatorSwedish::trPackageList () inline override virtual
Implements Translator.
Definition at line 2411 of file translator_sv.h.
    { return "Paketlista"; }
trPackageListDescription()
QCString TranslatorSwedish::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1240 of file translator_sv.h.
    {
      return "Hr r en lista ver paketen med en kort beskrivning "
             "(om sdan finns):";
    }
trPackageMembers()
QCString TranslatorSwedish::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1468 of file translator_sv.h.
    {
      return "Paketmedlemmar";
    }
trPackages()
QCString TranslatorSwedish::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1246 of file translator_sv.h.
    {
      return "Paket";
    }
trPackageTypes()
QCString TranslatorSwedish::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1457 of file translator_sv.h.
    {
      return "Pakettyper";
    }
trPage()
QCString TranslatorSwedish::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1345 of file translator_sv.h.
    {
      return createNoun(first_capital, singular, "sid", "or", "a");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorSwedish::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 917 of file translator_sv.h.
    { return "s."; }
trPageIndex()
QCString TranslatorSwedish::trPageIndex () inline override virtual
Implements Translator.
Definition at line 1008 of file translator_sv.h.
    {
      return "Sidindex";
    }
trPanelSynchronisationTooltip()
QCString TranslatorSwedish::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1999 of file translator_sv.h.
    {
      QCString opt = enable ? "aktivera" : "inaktivera";
      return "klicka fr att "+opt+" panelsynkronisering";
    }
trParameters()
QCString TranslatorSwedish::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 664 of file translator_sv.h.
    { return "Parametrar"; }
trPostcondition()
QCString TranslatorSwedish::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 977 of file translator_sv.h.
    {
      return "Postcondition";
    }
trPrecondition()
QCString TranslatorSwedish::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 972 of file translator_sv.h.
    {
      return "Precondition";
    }
trPrivateAttribs()
QCString TranslatorSwedish::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 1056 of file translator_sv.h.
    {
      return "Privata attribut";
    }
trPrivateMembers()
QCString TranslatorSwedish::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 761 of file translator_sv.h.
    { return "Privata medlemmsfunktioner"; }
trPrivateSlots()
QCString TranslatorSwedish::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 763 of file translator_sv.h.
    { return "Privata slots"; }
trPrivateTypes()
QCString TranslatorSwedish::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 1052 of file translator_sv.h.
    {
      return "Privata typer";
    }
trProperties()
QCString TranslatorSwedish::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1208 of file translator_sv.h.
    {
      return "Egenskaper";
    }
trPropertyDocumentation()
QCString TranslatorSwedish::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1213 of file translator_sv.h.
    {
      return "Egenskapsdokumentation";
    }
trProtectedAttribs()
QCString TranslatorSwedish::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 1044 of file translator_sv.h.
    {
      return "Skyddade attribut";
    }
trProtectedMembers()
QCString TranslatorSwedish::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 755 of file translator_sv.h.
    { return "Skyddade medlemmsfunktioner"; }
trProtectedSlots()
QCString TranslatorSwedish::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 757 of file translator_sv.h.
    { return "Skyddade slots"; }
trProtectedTypes()
QCString TranslatorSwedish::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 1040 of file translator_sv.h.
    {
      return "Skyddade typer";
    }
trProvidedByCategory()
QCString TranslatorSwedish::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2009 of file translator_sv.h.
    {
      return "Tillhandahlls av kategori @0.";
    }
trPublicAttribs()
QCString TranslatorSwedish::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 1025 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dataflt";
      }
      else
      {
        return "Publika attribut";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorSwedish::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 747 of file translator_sv.h.
    { return "Publika medlemsfunktioner"; }
trPublicSlots()
QCString TranslatorSwedish::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 749 of file translator_sv.h.
    { return "Publika slots"; }
trPublicTypes()
QCString TranslatorSwedish::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 1021 of file translator_sv.h.
    {
      return "Publika typer";
    }
trReferencedBy()
QCString TranslatorSwedish::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 1084 of file translator_sv.h.
    {
      return "Refererad av";
    }
trReferenceManual()
QCString TranslatorSwedish::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 542 of file translator_sv.h.
    { return "Referensmanual"; }
trReferences()
QCString TranslatorSwedish::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1385 of file translator_sv.h.
    {
      return "Referenser";
    }
trReimplementedFromList()
QCString TranslatorSwedish::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 817 of file translator_sv.h.
    {
      return "terskapad frn "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorSwedish::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 827 of file translator_sv.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "terskapad i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorSwedish::trRelatedFunctionDocumentation () inline override virtual
Implements Translator.
Definition at line 702 of file translator_sv.h.
    { return "Dokumenation av vnners och relaterade funktioner"; }
trRelatedFunctions()
QCString TranslatorSwedish::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 202 of file translator_sv.h.
    { return "Beslktade funktioner"; }
trRelatedPages()
QCString TranslatorSwedish::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 349 of file translator_sv.h.
    { return "Relaterade sidor"; }
trRelatedPagesDescription()
QCString TranslatorSwedish::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 464 of file translator_sv.h.
    { return "Hr fljer en lista ver alla relaterade dokumentationssidor:";}
trRelatedSubscript()
QCString TranslatorSwedish::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 206 of file translator_sv.h.
    { return "(Observera att dessa inte r medlemsfunktioner)"; }
trRemarks()
QCString TranslatorSwedish::trRemarks () inline override virtual
Implements Translator.
Definition at line 1088 of file translator_sv.h.
    {
      return "Lgg mrke till";
    }
trReturns()
QCString TranslatorSwedish::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 656 of file translator_sv.h.
    { return "Returnerar"; }
trReturnValues()
QCString TranslatorSwedish::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 906 of file translator_sv.h.
    { return "Returvrden"; }
trRTFansicp()
QCString TranslatorSwedish::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
ANSI_CHARSET              0 (x00)            1252
Implements Translator.
Definition at line 1285 of file translator_sv.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorSwedish::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1294 of file translator_sv.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorSwedish::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1300 of file translator_sv.h.
    {
      return "Index";
    }
trRTFTableOfContents()
QCString TranslatorSwedish::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1417 of file translator_sv.h.
    {
      return "Innehllsfrteckning";
    }
trSearch()
QCString TranslatorSwedish::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 357 of file translator_sv.h.
    { return "Sk"; }
trSearching()
QCString TranslatorSwedish::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1852 of file translator_sv.h.
    {
      return "Sker...";
    }
trSearchMatches()
QCString TranslatorSwedish::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1549 of file translator_sv.h.
    {
      return "Trffar:";
    }
trSearchResults()
QCString TranslatorSwedish::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1530 of file translator_sv.h.
    {
      if (numDocuments==0)
      {
        return "Tyvrr finns det inga dokument som matchar din skning.";
      }
      else if (numDocuments==1)
      {
        return "Hittade <b>1</b> dokument som matchar din skning.";
      }
      else
      {
        return "Hittade <b>$num</b> dokument som matchar din skning. "
               "Visar de bsta trffarna frst.";
      }
    }
trSearchResultsTitle()
QCString TranslatorSwedish::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1518 of file translator_sv.h.
    {
      return "Skresultat";
    }
trSeeAlso()
QCString TranslatorSwedish::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 660 of file translator_sv.h.
    { return "Se ven"; }
trSequenceDocumentation()
QCString TranslatorSwedish::trSequenceDocumentation () inline override virtual
Implements Translator.
Definition at line 2231 of file translator_sv.h.
    {
        return "Sekvensdokumentation";
    }
trSequences()
QCString TranslatorSwedish::trSequences () inline override virtual
Implements Translator.
Definition at line 2227 of file translator_sv.h.
    {
        return "Sekvenser";
    }
trServiceGeneratedFromFiles()
QCString TranslatorSwedish::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 2084 of file translator_sv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentationen fr denna tjnst "
                                "genererades frn fljande fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
trServiceReference()
QCString TranslatorSwedish::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 2070 of file translator_sv.h.
    {
      QCString result=sName;
      result+=" Tjnstereferens";
      return result;
    }
trServices()
QCString TranslatorSwedish::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2055 of file translator_sv.h.
    { return "Inkuderade tjnster"; }
trSignals()
QCString TranslatorSwedish::trSignals () inline override virtual
Implements Translator.
Definition at line 751 of file translator_sv.h.
    { return "Signaler"; }
trSince()
QCString TranslatorSwedish::trSince () inline override virtual
Implements Translator.
Definition at line 1101 of file translator_sv.h.
    {
      return "Sedan";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorSwedish::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 2093 of file translator_sv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentationen fr denna singleton "
                                "genererades frn fljande fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
trSingletonReference()
QCString TranslatorSwedish::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 2077 of file translator_sv.h.
    {
      QCString result=sName;
      result+=" Singleton-referens";
      return result;
    }
trSliceInterfaces()
QCString TranslatorSwedish::trSliceInterfaces () inline override virtual
Implements Translator.
Definition at line 2243 of file translator_sv.h.
    {
        return "Grnssnitt";
    }
trSourceFile()
QCString TranslatorSwedish::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1560 of file translator_sv.h.
    {
      return "Kllkodsfilen " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorSwedish::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1489 of file translator_sv.h.
    {
      return "Statiska paketattribut";
    }
trStaticPackageFunctions()
QCString TranslatorSwedish::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1475 of file translator_sv.h.
    {
      return "Statiska paketfunktioner";
    }
trStaticPrivateAttribs()
QCString TranslatorSwedish::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 1060 of file translator_sv.h.
    {
      return "Statiska privata attribut";
    }
trStaticPrivateMembers()
QCString TranslatorSwedish::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 765 of file translator_sv.h.
    { return "Statiska privata medlemmsfunktioner"; }
trStaticProtectedAttribs()
QCString TranslatorSwedish::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 1048 of file translator_sv.h.
    {
      return "Statiska skyddade attribut";
    }
trStaticProtectedMembers()
QCString TranslatorSwedish::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 759 of file translator_sv.h.
    { return "Statiska skyddade medlemmsfunktioner"; }
trStaticPublicAttribs()
QCString TranslatorSwedish::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 1036 of file translator_sv.h.
    {
      return "Statiska publika attribut";
    }
trStaticPublicMembers()
QCString TranslatorSwedish::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 753 of file translator_sv.h.
    { return "Statiska publika medlemmsfunktioner"; }
trStructDocumentation()
QCString TranslatorSwedish::trStructDocumentation () inline override virtual
Implements Translator.
Definition at line 2290 of file translator_sv.h.
    {
        return "Strukturdokumentation";
    }
trStructIndex()
QCString TranslatorSwedish::trStructIndex () inline override virtual
Implements Translator.
Definition at line 2277 of file translator_sv.h.
    {
        return "Strukturindex";
    }
trStructList()
QCString TranslatorSwedish::trStructList () inline override virtual
Implements Translator.
Definition at line 2281 of file translator_sv.h.
    {
        return "Strukturlist";
    }
trStructListDescription()
QCString TranslatorSwedish::trStructListDescription () inline override virtual
Orginal: Here are the structs with brief descriptions:
Implements Translator.
Definition at line 2286 of file translator_sv.h.
    {
        return "Hr r strukturerna med en kort beskrivning:";
    }
trStructs()
QCString TranslatorSwedish::trStructs () inline override virtual
Implements Translator.
Definition at line 2273 of file translator_sv.h.
    {
        return "Strukturer";
    }
trSubprogram()
QCString TranslatorSwedish::trSubprogram (bool first_capital, bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1818 of file translator_sv.h.
    {
      return createNoun(first_capital, false, "underprogram", "");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorSwedish::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1694 of file translator_sv.h.
    { return "Dokumentation fr funktion/subrutin"; }
trSubprograms()
QCString TranslatorSwedish::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1688 of file translator_sv.h.
    { return "Funktioner/subrutiner"; }
trTemplateParameters()
QCString TranslatorSwedish::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1962 of file translator_sv.h.
    { return "Mall-parametrar"; }
trTest()
QCString TranslatorSwedish::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1193 of file translator_sv.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorSwedish::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1198 of file translator_sv.h.
    {
      return "Testlista";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorSwedish::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 264 of file translator_sv.h.
    { return "Det hr r en fullstndig lista ver medlemmar fr"; }
trTodo()
QCString TranslatorSwedish::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1070 of file translator_sv.h.
    {
      return "Att-gra";
    }
trTodoList()
QCString TranslatorSwedish::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 1075 of file translator_sv.h.
    {
      return "Att gra-lista";
    }
trType()
QCString TranslatorSwedish::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1809 of file translator_sv.h.
    {
      return createNoun(first_capital, singular, "typ", "er");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trTypeConstraints()
QCString TranslatorSwedish::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1824 of file translator_sv.h.
    {
      return "Typbegrnsningar";
    }
trTypedefDocumentation()
QCString TranslatorSwedish::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 590 of file translator_sv.h.
    { return "Dokumentation ver typdefinitioner"; }
trTypedefs()
QCString TranslatorSwedish::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 554 of file translator_sv.h.
    { return "Typdefinitioner"; }
trTypeDocumentation()
QCString TranslatorSwedish::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1682 of file translator_sv.h.
    { return "Datatypsdokumentation"; }
trVariableDocumentation()
QCString TranslatorSwedish::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 608 of file translator_sv.h.
    { return "Dokumentation ver variabler"; }
trVariables()
QCString TranslatorSwedish::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 572 of file translator_sv.h.
    { return "Variabler"; }
trVersion()
QCString TranslatorSwedish::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 648 of file translator_sv.h.
    { return "Version"; }
trVhdlType()
QCString TranslatorSwedish::trVhdlType (VhdlSpecifier type, bool single) inline override virtual
VHDL type.
Implements Translator.
Definition at line 2134 of file translator_sv.h.
    {
      switch(type)
      {
        case VhdlSpecifier::LIBRARY:
          return "Biblotek";
        case VhdlSpecifier::PACKAGE:
          return "Paket";
        case VhdlSpecifier::SIGNAL:
          if (single) return "Signal";
          else        return "Signaler";
        case VhdlSpecifier::COMPONENT:
          if (single) return "Komponent";
          else        return "Komponenter";
        case VhdlSpecifier::CONSTANT:
          if (single) return "Konstant";
          else        return "Konstanter";
        case VhdlSpecifier::ENTITY:
          if (single) return "Entitet";
          else        return "Entiteter";
        case VhdlSpecifier::TYPE:
          if (single) return "Typ";
          else        return "Typer";
        case VhdlSpecifier::SUBTYPE:
          if (single) return "Undertyp";
          else        return "Undertyper";
        case VhdlSpecifier::FUNCTION:
          if (single) return "Funktion";
          else        return "Funktioner";
        case VhdlSpecifier::RECORD:
          if (single) return "Post";
          else        return "Poster";
        case VhdlSpecifier::PROCEDURE:
          if (single) return "Procedur";
          else        return "Procedurer";
        case VhdlSpecifier::ARCHITECTURE:
          if (single) return "Arkitektur";
          else        return "Arkitekturer";
        case VhdlSpecifier::ATTRIBUTE:
          return "Attribut";
        case VhdlSpecifier::PROCESS:
          if (single) return "Process";
          else        return "Processer";
        case VhdlSpecifier::PORT:
          if (single) return "Port";
          else        return "Portar";
        case VhdlSpecifier::USE:
          if (single) return "use clause";
          else        return "Use Clauses";
        case VhdlSpecifier::GENERIC:
          if (single) return "Generisk";
          else        return "Generiska";
        case VhdlSpecifier::PACKAGE_BODY:
          return "Paketinehll";
        case VhdlSpecifier::UNITS:
          return "Enheter";
        case VhdlSpecifier::SHAREDVARIABLE:
          if (single) return "Delad Variabel";
          else        return "Delade Variabler";
        case VhdlSpecifier::VFILE:
          if (single) return "Fil";
          else        return "Filer";
        case VhdlSpecifier::GROUP:
          if (single) return "Grupp";
          else        return "Grupper";
        case VhdlSpecifier::INSTANTIATION:
          if (single) return "Instantiation";
          else        return "Instantiations";
        case VhdlSpecifier::ALIAS:
          return "Alias";
        case VhdlSpecifier::CONFIG:
          if (single) return "Konfiguration";
          else        return "Konfigurationer";
        case VhdlSpecifier::MISCELLANEOUS:
          return "Diverse";
        case VhdlSpecifier::UCF_CONST:
          return "Begrnsningar";
        default:
          return "Klass";
      }
    }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorSwedish::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 644 of file translator_sv.h.
    { return "Varning"; }
trWriteList()
QCString TranslatorSwedish::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 771 of file translator_sv.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=", och ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_sv.h