Doxygen: TranslatorLithuanian Class Reference
TranslatorLithuanian Class Reference
#include <src/translator_lt.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
Public Member Functions inherited from TranslatorAdapter_1_4_6
QCString updateNeededMessage () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_6_0
QCString updateNeededMessage () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
Public Member Functions inherited from TranslatorAdapter_1_7_5
QCString updateNeededMessage () override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Public Member Functions inherited from TranslatorAdapter_1_8_0
QCString updateNeededMessage () override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 33 of file translator_lt.h.
Member Function Documentation
getLanguageString()
QCString TranslatorLithuanian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 72 of file translator_lt.h.
    {
      return "0x427 Lithuanian";
    }
idLanguage()
QCString TranslatorLithuanian::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 45 of file translator_lt.h.
    { return "lithuanian"; }
latexLanguageSupportCommand()
QCString TranslatorLithuanian::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 62 of file translator_lt.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[lithuanian]{babel}\n";
    }
trAll()
QCString TranslatorLithuanian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1372 of file translator_lt.h.
    {
      return "Visi";
    }
trAttention()
QCString TranslatorLithuanian::trAttention () inline override virtual
Implements Translator.
Definition at line 951 of file translator_lt.h.
    {
      return "Attention";
    }
trAuthor()
QCString TranslatorLithuanian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1245 of file translator_lt.h.
    {
      return createNoun(first_capital, singular, "autori", "ai", "us");
    }
References Translator::createNoun().
trBug()
QCString TranslatorLithuanian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1117 of file translator_lt.h.
    {
      return "Klaida";
    }
trBugList()
QCString TranslatorLithuanian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1122 of file translator_lt.h.
    {
      return "Klaid Sraas";
    }
trCallGraph()
QCString TranslatorLithuanian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1377 of file translator_lt.h.
    {
      return "Funkcijos kvietimo grafas:";
    }
trClass()
QCString TranslatorLithuanian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1180 of file translator_lt.h.
    {
      return createNoun(first_capital, singular, "klas", "s");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorLithuanian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 506 of file translator_lt.h.
    {
      return "Paveldimumo diagrama "+clName+":"; /*FIXME*/
    }
trClassDocumentation()
QCString TranslatorLithuanian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 387 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros Dokumentacija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klass Dokumentacija";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorLithuanian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1080 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros";
      }
      else
      {
        return "Klass";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorLithuanian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 171 of file translator_lt.h.
    { return "Klasi hierarchija"; }
trClassHierarchyDescription()
QCString TranslatorLithuanian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 230 of file translator_lt.h.
    { return "is paveldjimo sraas yra beveik surikiuotas "
             "abcls tvarka:";
    }
trCode()
QCString TranslatorLithuanian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 851 of file translator_lt.h.
    {
      return "tekstas";/*FIXME*/
    }
trCollaborationDiagram()
QCString TranslatorLithuanian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 806 of file translator_lt.h.
    {
      return "Bendradarbiavimo diagrama "+clName+":";/*FIXME*/
    }
trCompoundIndex()
QCString TranslatorLithuanian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 360 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros Indeksas";
      }
      else
      {
        return "Klass Indeksas";
      }
    }
References Config_getBool.
trCompoundList()
QCString TranslatorLithuanian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 175 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros";
      }
      else
      {
        return "Klass";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorLithuanian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 245 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen struktros su trumpais apraymais:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Klass su trumpais apraymais:";
      }
      else
      {
        return "Klass, struktros, "
               "sjungos ir ssajos su trumpais apraymais:";
      }
    }
References Config_getBool.
trCompoundMembers()
QCString TranslatorLithuanian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 192 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Laukai";
      }
      else
      {
        return "Klasi Nariai";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorLithuanian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 264 of file translator_lt.h.
    {
      QCString result="Vis ";
      if (!extractAll)
      {
        result+="dokumentuot ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktr ir sjung lauk sraas";
      }
      else
      {
        result+="klasi nariai";
      }
      result+=" su ryiais  ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktr/sjung kiekvieno lauko dokumentacij:";
        }
        else
        {
          result+="klass dokumentacija kiekvienam nariui:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktros/sjungos, kurios priklauso:";
        }
        else
        {
          result+="klass, kurios priklauso:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundReference()
QCString TranslatorLithuanian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 581 of file translator_lt.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Klas"; break;
        case ClassDef::Struct:     result+=" Struktra"; break;
        case ClassDef::Union:      result+=" Sjunga"; break;
        case ClassDef::Interface:  result+=" Ssaja"; break;
        case ClassDef::Protocol:   result+=" Protokolas"; break;
        case ClassDef::Category:   result+=" Kategorija"; break;
        case ClassDef::Exception:  result+=" Iimtis"; break;
        default: break;
      }
      if (isTemplate) result+=" ablonas";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorLithuanian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 482 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen struktros";
      }
      else
      {
        return "Klass";
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorLithuanian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 816 of file translator_lt.h.
    {
      return "Konstruktoriaus ir Destruktoriaus Dokumentacija";
    }
trDate()
QCString TranslatorLithuanian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 520 of file translator_lt.h.
    { return "Data"; }
trDayOfWeek()
QCString TranslatorLithuanian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1485 of file translator_lt.h.
    {
      static const char *days_short[]   = { "pr", "an", "tr", "kt", "pn", "t", "sk" };
      static const char *days_full[]    = { "pirmadienis", "antradienis", "treiadienis", "ketvirtadienis", "penktadienis", "etadienis", "sekmadienis" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorLithuanian::trDayPeriod (bool period) inline override virtual
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1501 of file translator_lt.h.
    {
      static const char *dayPeriod[] = { "priepiet", "popiet" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorLithuanian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 783 of file translator_lt.h.
    {
      return "Apibrimas failo @1 eilutje @0.";
    }
trDefinedIn()
QCString TranslatorLithuanian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 159 of file translator_lt.h.
    { return "apibrta"; }
trDefinedInSourceFile()
QCString TranslatorLithuanian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 787 of file translator_lt.h.
    {
      return "Apibrimas faile @0.";
    }
trDefineDocumentation()
QCString TranslatorLithuanian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 452 of file translator_lt.h.
    { return "Apibrim Dokumentacija"; }
trDefines()
QCString TranslatorLithuanian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 416 of file translator_lt.h.
    { return "Apibrimai"; }
trDefineValue()
QCString TranslatorLithuanian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1107 of file translator_lt.h.
    {
      return "Reikm:";
    }
trDeprecated()
QCString TranslatorLithuanian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 796 of file translator_lt.h.
    {
      return "Smerktina";
    }
trDeprecatedList()
QCString TranslatorLithuanian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1300 of file translator_lt.h.
    {
      return "Smerktinum Sraas";
    }
trDetailedDescription()
QCString TranslatorLithuanian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 88 of file translator_lt.h.
    { return "Smulkus apraymas"; }
trDetails()
QCString TranslatorLithuanian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 92 of file translator_lt.h.
    { return "Isamiau"; }
trDir()
QCString TranslatorLithuanian::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1466 of file translator_lt.h.
    {
      return createNoun(first_capital, singular, "direktorij", "os", "a");
    }
References Translator::createNoun().
trDirDocumentation()
QCString TranslatorLithuanian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1448 of file translator_lt.h.
    { return "Direktorij dokumentacija"; }
trDirectories()
QCString TranslatorLithuanian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1454 of file translator_lt.h.
    { return "Direktorijos"; }
trDirIndex()
QCString TranslatorLithuanian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1442 of file translator_lt.h.
    { return "Direktorij hierarchija"; }
trDirReference()
QCString TranslatorLithuanian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1460 of file translator_lt.h.
    { QCString result=dirName; result+=" Directorijos apraas"; return result; }
trDocumentation()
QCString TranslatorLithuanian::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 342 of file translator_lt.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentacija"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorLithuanian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 428 of file translator_lt.h.
    { return "Ivardinimai"; }
trEnumerationTypeDocumentation()
QCString TranslatorLithuanian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 464 of file translator_lt.h.
    { return "Ivardinimo Tipo Dokumentacija"; }
trEnumerationValues()
QCString TranslatorLithuanian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 446 of file translator_lt.h.
    { return "Ivardinim reikms"; }
trEnumName()
QCString TranslatorLithuanian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 151 of file translator_lt.h.
    { return "ivardinimo vardas"; }
trEnumValue()
QCString TranslatorLithuanian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 155 of file translator_lt.h.
    { return "ivardinimo reikm"; }
trEventDocumentation()
QCString TranslatorLithuanian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1317 of file translator_lt.h.
    {
      return "vykio Dokumentacija";
    }
trEvents()
QCString TranslatorLithuanian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1312 of file translator_lt.h.
    {
      return "vykiai";
    }
trExamples()
QCString TranslatorLithuanian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 222 of file translator_lt.h.
    { return "Pavyzdiai"; }
trExamplesDescription()
QCString TranslatorLithuanian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 328 of file translator_lt.h.
    { return "Vis pavyzdi sraas:"; }
trExceptions()
QCString TranslatorLithuanian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 536 of file translator_lt.h.
    { return "Iimtys"; }
trFile()
QCString TranslatorLithuanian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1189 of file translator_lt.h.
    {
      return createNoun(first_capital, singular, "faila", "i", "s");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorLithuanian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 406 of file translator_lt.h.
    { return "Failo Dokumentacija"; }
trFileIndex()
QCString TranslatorLithuanian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 375 of file translator_lt.h.
    { return "Failo Indeksas"; }
trFileList()
QCString TranslatorLithuanian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 188 of file translator_lt.h.
    { return "Failai"; }
trFileListDescription()
QCString TranslatorLithuanian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 236 of file translator_lt.h.
    {
      QCString result="Vis ";
      if (!extractAll) result+="dokumentuot ";
      result+="fail sraas su trumpais apraymais:";
      return result;
    }
trFileMembers()
QCString TranslatorLithuanian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 205 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals Nariai";
      }
      else
      {
        return "Fail Nariai";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorLithuanian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 306 of file translator_lt.h.
    {
      QCString result="Sraas vis ";
      if (!extractAll) result+="dokumentuot ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcij, kintamj, apibrim, ivardinim, ir tip apibrim";
      }
      else
      {
        result+="globali nari";
      }
      result+=" su ryiais  ";
      if (extractAll)
        result+="failus, kuriems jie priklauso:";
      else
        result+="dokumentacija:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorLithuanian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 602 of file translator_lt.h.
    {
      QCString result=fileName;
      result+=" Failo Nuoroda";
      return result;
    }
trFriends()
QCString TranslatorLithuanian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 563 of file translator_lt.h.
    { return "Draugai"; }
trFunctionDocumentation()
QCString TranslatorLithuanian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 470 of file translator_lt.h.
    { return "Funkcijos Dokumentacija"; }
trFunctions()
QCString TranslatorLithuanian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 434 of file translator_lt.h.
    { return "Funkcijos"; }
trGeneratedAt()
QCString TranslatorLithuanian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 497 of file translator_lt.h.
    {
      QCString result="Sugeneruota "+date;/*FIXME*/
      if (!projName.isEmpty()) result+=" "+projName;/*FIXME*/
      result+=" ";/*FIXME*/
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorLithuanian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 143 of file translator_lt.h.
    { QCString result="Automatikai sugeneruota Doxygen rankiu";
      if (!s.isEmpty()) result+=" "+s;
      result+=" i programos kodo.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorLithuanian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 540 of file translator_lt.h.
    { return "Sugeneruota"; }
trGeneratedFromFiles()
QCString TranslatorLithuanian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 739 of file translator_lt.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ";
      switch(compType)
      {
        case ClassDef::Class:      result+="iai klasei"; break;
        case ClassDef::Struct:     result+="iai struktrai"; break;
        case ClassDef::Union:      result+="iai sjungai"; break;
        case ClassDef::Interface:  result+="iai ssajai"; break;
        case ClassDef::Protocol:   result+="iam protocolui"; break;
        case ClassDef::Category:   result+="iai kategorijai"; break;
        case ClassDef::Exception:  result+="iai iimiai"; break;
        default: break;
      }
      result+=" sugeneruota i ";
      if (single) result+="io failo:"; else result+="i fail:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorLithuanian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1234 of file translator_lt.h.
    {
      return createNoun(first_capital, singular, "global", "s", "us");
    }
References Translator::createNoun().
trGotoDocumentation()
QCString TranslatorLithuanian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 826 of file translator_lt.h.
    {
      return "Eiti  io failo dokumentacij.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorLithuanian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 859 of file translator_lt.h.
    {
      return "Eiti  grafin klass hierarchij";
    }
trGotoSourceCode()
QCString TranslatorLithuanian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 821 of file translator_lt.h.
    {
      return "Eiti  io failo programos kod.";
    }
trGotoTextualHierarchy()
QCString TranslatorLithuanian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 863 of file translator_lt.h.
    {
      return "Eiti  tekstin klass hierarchij";
    }
trGraphicalHierarchy()
QCString TranslatorLithuanian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 855 of file translator_lt.h.
    {
      return "Grafin Klass Hierarchija";
    }
trGroup()
QCString TranslatorLithuanian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1207 of file translator_lt.h.
    {
      return createNoun(first_capital, singular, "grup", "s");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorLithuanian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 354 of file translator_lt.h.
    { return "Hierarchijos Indeksas"; }
trImplementedFromList()
QCString TranslatorLithuanian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1268 of file translator_lt.h.
    {
      return "Realizuoja "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorLithuanian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1276 of file translator_lt.h.
    {
      return "Realizuota "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorLithuanian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 955 of file translator_lt.h.
    {
      return "is grafas rodo, kuris failas tiesiogiai ar "
             "netiesiogiai traukia  fail:";
    }
trInclDepGraph()
QCString TranslatorLithuanian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 811 of file translator_lt.h.
    {
      return "traukimo priklausomybi diagrama "+fName+":";/*FIXME*/
    }
trIncludingInheritedMembers()
QCString TranslatorLithuanian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 137 of file translator_lt.h.
    { return ", traukiant visus paveldtus narius."; }
trInheritedByList()
QCString TranslatorLithuanian::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 673 of file translator_lt.h.
    {
      return "Paveldta "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList()
QCString TranslatorLithuanian::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 665 of file translator_lt.h.
    {
      return "Paveldi "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorLithuanian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 846 of file translator_lt.h.
    {
      return "Pradin reikm:";
    }
trInvariant()
QCString TranslatorLithuanian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 841 of file translator_lt.h.
    {
      return "Pastovus";
    }
trISOLang()
QCString TranslatorLithuanian::trISOLang () inline override virtual
Implements Translator.
Definition at line 68 of file translator_lt.h.
    {
      return "lt";
    }
trLegend()
QCString TranslatorLithuanian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1040 of file translator_lt.h.
    {
      return "legenda";
    }
trLegendDocs()
QCString TranslatorLithuanian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 977 of file translator_lt.h.
    {
      return
        "is puslapis paaikina, kaip interpretuoti sugeneruotus grafus "
        "su Doxygen rankiu.<p>\n"
        "Panagrinkite pavyzd:\n"
        "\\kodo pradia\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "If the \\c MAX_DOT_GRAPH_HEIGHT tag in the configuration file "
        "is set to 240 this will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>%A filled black box represents the struct or class for which the "
        "graph is generated.\n"
        "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.\n"
        "</ul>\n"
        "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.\n"
        "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible.\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labeled with "
        "the template parameters of the instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorLithuanian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 970 of file translator_lt.h.
    {
      return "Grafo Legenda";
    }
trListOfAllMembers()
QCString TranslatorLithuanian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 125 of file translator_lt.h.
    { return "Vis nari sraas"; }
trMainPage()
QCString TranslatorLithuanian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 770 of file translator_lt.h.
    { return "Pagrindinis Puslapis"; }
trMember()
QCString TranslatorLithuanian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1225 of file translator_lt.h.
    {
      return createNoun(first_capital, singular, "nar", "iai", "ys");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorLithuanian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 108 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lauko apraymas";
      }
      else
      {
        return "Atribut Dokumentacija";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorLithuanian::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 100 of file translator_lt.h.
    { return "Ivardinimo Dokumentacija"; }
trMemberFunctionDocumentation()
QCString TranslatorLithuanian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 104 of file translator_lt.h.
    { return "Metod Dokumentacija"; }
trMemberList()
QCString TranslatorLithuanian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 129 of file translator_lt.h.
    { return "Nari sraas"; }
trMemberTypedefDocumentation()
QCString TranslatorLithuanian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 96 of file translator_lt.h.
    { return "Tipo Apraymo Dokumentacija"; }
trModuleDocumentation()
QCString TranslatorLithuanian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 381 of file translator_lt.h.
    { return "Modulio Dokumentacija"; }
trModuleIndex()
QCString TranslatorLithuanian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 348 of file translator_lt.h.
    { return "Modulio Indeksas"; }
trModules()
QCString TranslatorLithuanian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 167 of file translator_lt.h.
    { return "Moduliai"; }
trModulesDescription()
QCString TranslatorLithuanian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 336 of file translator_lt.h.
    { return "Vis moduli sraas:"; }
trMonth()
QCString TranslatorLithuanian::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1493 of file translator_lt.h.
    {
      static const char *months_short[] = { "saus.", "vas.", "kov.", "bal.", "geg.", "bir.", "liep.", "rugp.", "rugs.", "spal.", "lapkr.", "gruod." };
      static const char *months_full[]  = { "sausis", "vasaris", "kovas", "balandis", "gegu", "birelis", "liepa", "rugpjtis", "rugsjis", "spalis", "lapkritis", "gruodis" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorLithuanian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 121 of file translator_lt.h.
    { return "Daugiau..."; }
trNamespace()
QCString TranslatorLithuanian::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1198 of file translator_lt.h.
    {
      return createNoun(first_capital, singular, "vard srit", "ys", "is");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorLithuanian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 719 of file translator_lt.h.
    { return "Vard Srities Dokumentacija"; }
trNamespaceIndex()
QCString TranslatorLithuanian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 713 of file translator_lt.h.
    { return "Vard Srities Indeksas"; }
trNamespaceList()
QCString TranslatorLithuanian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 548 of file translator_lt.h.
    { return "Var Srities Sraas"; }
trNamespaceListDescription()
QCString TranslatorLithuanian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 552 of file translator_lt.h.
    {
      QCString result="Sraas vis ";
      if (!extractAll) result+="dokumentuot ";
      result+="vard srii su trumpais apraymais:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorLithuanian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 699 of file translator_lt.h.
    {
      QCString result="Sraas vis ";
      if (!extractAll) result+="dokumentuot ";
      result+="vard srities nari su nuorodomis  ";
      if (extractAll)
        result+="vard srities dokumentacij kiekvienam nariui:";
      else
        result+="vard sritis, kurioms jos priklauso:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorLithuanian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 695 of file translator_lt.h.
    { return "Vard Srities Nariai"; }
trNamespaceReference()
QCString TranslatorLithuanian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 610 of file translator_lt.h.
    {
      QCString result=namespaceName;
      result+=" Vard Srities Nuoroda";
      return result;
    }
trNamespaces()
QCString TranslatorLithuanian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 729 of file translator_lt.h.
    { return "Vard Sritys"; }
trNote()
QCString TranslatorLithuanian::trNote () inline override virtual
Implements Translator.
Definition at line 876 of file translator_lt.h.
    {
      return "Pastaba";
    }
trOverloadText()
QCString TranslatorLithuanian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1478 of file translator_lt.h.
    {
       return "Perkraunamas metodas sukurtas patogumui. "
              "Jis skiriasi nuo aukiau minto tik argumetais.";
    }
trPackage()
QCString TranslatorLithuanian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1092 of file translator_lt.h.
    {
      return "Paketas "+name;
    }
trPackageAttribs()
QCString TranslatorLithuanian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1353 of file translator_lt.h.
    {
      return "Paketo Atributai";
    }
trPackageFunctions()
QCString TranslatorLithuanian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1335 of file translator_lt.h.
    {
      return "Paketo Funkcijos";
    }
trPackageListDescription()
QCString TranslatorLithuanian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1097 of file translator_lt.h.
    {
      return "Paketai su trumpu apraymu:";
    }
trPackageMembers()
QCString TranslatorLithuanian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1339 of file translator_lt.h.
    {
      return "Paketo Nariai";
    }
trPackages()
QCString TranslatorLithuanian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1102 of file translator_lt.h.
    {
      return "Paketai";
    }
trPackageTypes()
QCString TranslatorLithuanian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1328 of file translator_lt.h.
    {
      return "Paketo Tipai";
    }
trPage()
QCString TranslatorLithuanian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1216 of file translator_lt.h.
    {
      return createNoun(first_capital, singular, "puslapi", "ai", "s");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorLithuanian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 776 of file translator_lt.h.
    { return "psl."; }
trPageIndex()
QCString TranslatorLithuanian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 867 of file translator_lt.h.
    {
      return "Puslapio Indeksas";
    }
trParameters()
QCString TranslatorLithuanian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 532 of file translator_lt.h.
    { return "Parametrai"; }
trPostcondition()
QCString TranslatorLithuanian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 836 of file translator_lt.h.
    {
      return "Postcondition";/*FIXME*/
    }
trPrecondition()
QCString TranslatorLithuanian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 831 of file translator_lt.h.
    {
      return "Iakstin slyga";
    }
trPrivateAttribs()
QCString TranslatorLithuanian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 915 of file translator_lt.h.
    {
      return "Privats Atributai";
    }
trPrivateMembers()
QCString TranslatorLithuanian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 631 of file translator_lt.h.
    { return "Privatats Metodai"; }
trPrivateSlots()
QCString TranslatorLithuanian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 633 of file translator_lt.h.
    { return "Privats Slotai"; }/*FIXME*/
trPrivateTypes()
QCString TranslatorLithuanian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 911 of file translator_lt.h.
    {
      return "Privats Tipai";
    }
trProperties()
QCString TranslatorLithuanian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1065 of file translator_lt.h.
    {
      return "Savybs";
    }
trPropertyDocumentation()
QCString TranslatorLithuanian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1070 of file translator_lt.h.
    {
      return "Savybs Dokumentacija";
    }
trProtectedAttribs()
QCString TranslatorLithuanian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 903 of file translator_lt.h.
    {
      return "Apsaugoti Atributai";
    }
trProtectedMembers()
QCString TranslatorLithuanian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 625 of file translator_lt.h.
    { return "Apsaugoti Metodai"; }
trProtectedSlots()
QCString TranslatorLithuanian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 627 of file translator_lt.h.
    { return "Apsaugoti Slotai"; }/*FIXME*/
trProtectedTypes()
QCString TranslatorLithuanian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 899 of file translator_lt.h.
    {
      return "Apsaugoti Tipai";
    }
trPublicAttribs()
QCString TranslatorLithuanian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 884 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Laukai";
      }
      else
      {
        return "Viei Atributai";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorLithuanian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 617 of file translator_lt.h.
    { return "Viei Metodai"; }
trPublicSlots()
QCString TranslatorLithuanian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 619 of file translator_lt.h.
    { return "Viei Slotai"; } /*FIXME*/
trPublicTypes()
QCString TranslatorLithuanian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 880 of file translator_lt.h.
    {
      return "Viei Tipai";
    }
trReferencedBy()
QCString TranslatorLithuanian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 943 of file translator_lt.h.
    {
      return "Naudojamas";
    }
trReferenceManual()
QCString TranslatorLithuanian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 410 of file translator_lt.h.
    { return "Informacinis Vadovas"; }
trReferences()
QCString TranslatorLithuanian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1256 of file translator_lt.h.
    {
      return "Ryiai";
    }
trReimplementedFromList()
QCString TranslatorLithuanian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 681 of file translator_lt.h.
    {
      return "Perkrauna metod i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorLithuanian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 689 of file translator_lt.h.
    {
      return "Metodas perkraunamas "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorLithuanian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 573 of file translator_lt.h.
    { return "Draugik Ir Susijusi Funkcij Dokumentacija"; }
trRelatedFunctions()
QCString TranslatorLithuanian::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 80 of file translator_lt.h.
    { return "Susij Funkcijos"; }
trRelatedPages()
QCString TranslatorLithuanian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 218 of file translator_lt.h.
    { return "Susij Puslapiai"; }
trRelatedPagesDescription()
QCString TranslatorLithuanian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 332 of file translator_lt.h.
    { return "Vis susijusi dokumentacijos puslapi sraas:"; }
trRelatedSubscript()
QCString TranslatorLithuanian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 84 of file translator_lt.h.
    { return "Atkreipkite dmes, i ne metodai"; }
trRemarks()
QCString TranslatorLithuanian::trRemarks () inline override virtual
Implements Translator.
Definition at line 947 of file translator_lt.h.
    {
      return "Pastabos";
    }
trReturns()
QCString TranslatorLithuanian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 524 of file translator_lt.h.
    { return "Graina"; }
trReturnValues()
QCString TranslatorLithuanian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 765 of file translator_lt.h.
    { return "Grainamos reikms"; }
trRTFansicp()
QCString TranslatorLithuanian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1156 of file translator_lt.h.
    {
      return "1257";
    }
trRTFCharSet()
QCString TranslatorLithuanian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1165 of file translator_lt.h.
    {
      return "186";
    }
trRTFGeneralIndex()
QCString TranslatorLithuanian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1171 of file translator_lt.h.
    {
      return "Indeksas";
    }
trRTFTableOfContents()
QCString TranslatorLithuanian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1288 of file translator_lt.h.
    {
      return "Turinys";
    }
trSearch()
QCString TranslatorLithuanian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 226 of file translator_lt.h.
    { return "Paieka"; }
trSearchMatches()
QCString TranslatorLithuanian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1420 of file translator_lt.h.
    {
      return "Atitikmenys:";
    }
trSearchResults()
QCString TranslatorLithuanian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1401 of file translator_lt.h.
    {
      if (numDocuments==0)
      {
        return "Atsipraome, joki dokument nerasta pagal Js uklaus.";
      }
      else if (numDocuments==1)
      {
        return "Surasta <b>1</b> dokumentas, atitinkantis Js uklaus.";
      }
      else
      {
        return "Surasta <b>$num</b> dokument, atitinkani Js uklaus. "
               "Pirmiausiai rodomi labiausiai tenkinantys uklaus.";
      }
    }
trSearchResultsTitle()
QCString TranslatorLithuanian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1389 of file translator_lt.h.
    {
      return "Paiekos Rezultatai";
    }
trSeeAlso()
QCString TranslatorLithuanian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 528 of file translator_lt.h.
    { return "Taip pat irti"; }
trSignals()
QCString TranslatorLithuanian::trSignals () inline override virtual
Implements Translator.
Definition at line 621 of file translator_lt.h.
    { return "Signalai"; }
trSince()
QCString TranslatorLithuanian::trSince () inline override virtual
Implements Translator.
Definition at line 960 of file translator_lt.h.
    {
      return "Nuo";
    }
trSourceFile()
QCString TranslatorLithuanian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1430 of file translator_lt.h.
    {
      return filename + " ieities tekstas";
    }
trStaticPackageAttribs()
QCString TranslatorLithuanian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1360 of file translator_lt.h.
    {
      return "Statiniai Paketo Atributai";
    }
trStaticPackageFunctions()
QCString TranslatorLithuanian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1346 of file translator_lt.h.
    {
      return "Statins Paketo Funkcijos";
    }
trStaticPrivateAttribs()
QCString TranslatorLithuanian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 919 of file translator_lt.h.
    {
      return "Statiniai Privats Atributai";
    }
trStaticPrivateMembers()
QCString TranslatorLithuanian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 635 of file translator_lt.h.
    { return "Statiniai Privats Metodai"; }
trStaticProtectedAttribs()
QCString TranslatorLithuanian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 907 of file translator_lt.h.
    {
      return "Statiniai Apsaugoti Atributai";
    }
trStaticProtectedMembers()
QCString TranslatorLithuanian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 629 of file translator_lt.h.
    { return "Statiniai Apsaugoti Metodai"; }
trStaticPublicAttribs()
QCString TranslatorLithuanian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 895 of file translator_lt.h.
    {
      return "Statiniai Viei Atributai";
    }
trStaticPublicMembers()
QCString TranslatorLithuanian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 623 of file translator_lt.h.
    { return "Statiniai Viei Metodai"; }
trTest()
QCString TranslatorLithuanian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1050 of file translator_lt.h.
    {
      return "Testas";
    }
trTestList()
QCString TranslatorLithuanian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1055 of file translator_lt.h.
    {
      return "Testo Sraas";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorLithuanian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 133 of file translator_lt.h.
    { return "Tai galutinis nari sraas"; }
trTodo()
QCString TranslatorLithuanian::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 929 of file translator_lt.h.
    {
      return "Daryti";
    }
trTodoList()
QCString TranslatorLithuanian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 934 of file translator_lt.h.
    {
      return "Tolimesni Darbai";
    }
trTypedefDocumentation()
QCString TranslatorLithuanian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 458 of file translator_lt.h.
    { return "Tip apibrim Dokumentacija"; }
trTypedefs()
QCString TranslatorLithuanian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 422 of file translator_lt.h.
    { return "Tip apibrimai"; }
trVariableDocumentation()
QCString TranslatorLithuanian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 476 of file translator_lt.h.
    { return "Kintamojo Dokumentacija"; }
trVariables()
QCString TranslatorLithuanian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 440 of file translator_lt.h.
    { return "Kintamieji"; }
trVersion()
QCString TranslatorLithuanian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 516 of file translator_lt.h.
    { return "Versija"; }
trWarning()
QCString TranslatorLithuanian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 512 of file translator_lt.h.
    { return "spjimas"; }
trWriteList()
QCString TranslatorLithuanian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 641 of file translator_lt.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=", ir ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_lt.h