Doxygen: src/dotcallgraph.cpp File Reference
dotcallgraph.cpp File Reference
#include "dotcallgraph.h"
#include "dotnode.h"
#include "memberlist.h"
#include "config.h"
#include "util.h"
Functions
static QCString getUniqueId (const MemberDef *md)
Function Documentation
getUniqueId()
static QCString getUniqueId (const MemberDef * md) static
Definition at line 23 of file dotcallgraph.cpp.
{
  const MemberDef *def = md->memberDefinition();
  if (def==nullptr) def = md;
  QCString result = def->getReference()+"$"+
         def->getOutputFileBase()+"#"+
         def->anchor();
  return result;
}
References Definition::anchor(), Definition::getOutputFileBase(), Definition::getReference(), and MemberDef::memberDefinition().
Referenced by DotCallGraph::buildGraph(), and DotCallGraph::DotCallGraph().