Doxygen: LatexGenerator Class Reference
LatexGenerator Class Reference
Generator for LaTeX output.
#include <src/latexgen.h>
Public Member Functions
LatexGenerator ()
LatexGenerator (const LatexGenerator &)
LatexGenerator & operator= (const LatexGenerator &)
LatexGenerator (LatexGenerator &&)=delete
LatexGenerator & operator= (LatexGenerator &&)=delete
~LatexGenerator ()
void clearBuffer ()
void setCurrentDoc (const Definition *, const QCString &, bool)
void addWord (const QCString &, bool)
OutputType type () const override
std::unique_ptr< OutputGenIntf > clone () override
void addCodeGen (OutputCodeList &list) override
void cleanup () override
void writeDoc (const IDocNodeAST *node, const Definition *ctx, const MemberDef *, int id) override
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id, int hierarchyLevel) override
void endFile () override
void writeSearchInfo () override
void writeFooter (const QCString &) override
void startPageDoc (const QCString &) override
void endPageDoc () override
void startIndexSection (IndexSection) override
void endIndexSection (IndexSection) override
void writePageLink (const QCString &, bool) override
void startProjectNumber () override
void endProjectNumber () override
void writeStyleInfo (int part) override
void startTitleHead (const QCString &) override
void endTitleHead (const QCString &, const QCString &name) override
void startParagraph (const QCString &classDef) override
void endParagraph () override
void writeString (const QCString &text) override
void startIndexListItem () override
void endIndexListItem () override
void startIndexList () override
void endIndexList () override
void startIndexKey () override
void endIndexKey () override
void startIndexValue (bool) override
void endIndexValue (const QCString &, bool) override
void startItemList () override
void endItemList () override
void startIndexItem (const QCString &ref, const QCString &file) override
void endIndexItem (const QCString &ref, const QCString &file) override
void docify (const QCString &text) override
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name) override
void startTextLink (const QCString &, const QCString &) override
void endTextLink () override
void startTypewriter () override
void endTypewriter () override
void startGroupHeader (int) override
void endGroupHeader (int) override
void startItemListItem () override
void endItemListItem () override
void startMemberSections () override
void endMemberSections () override
void startHeaderSection () override
void endHeaderSection () override
void startMemberHeader (const QCString &, int) override
void endMemberHeader () override
void startMemberSubtitle () override
void endMemberSubtitle () override
void startMemberDocList () override
void endMemberDocList () override
void startMemberList () override
void endMemberList () override
void startInlineHeader () override
void endInlineHeader () override
void startAnonTypeScope (int) override
void endAnonTypeScope (int) override
void startMemberItem (const QCString &, MemberItemType, const QCString &) override
void endMemberItem (MemberItemType) override
void startMemberTemplateParams () override
void endMemberTemplateParams (const QCString &, const QCString &) override
void startCompoundTemplateParams () override
void endCompoundTemplateParams () override
void startMemberGroupHeader (bool) override
void endMemberGroupHeader () override
void startMemberGroupDocs () override
void endMemberGroupDocs () override
void startMemberGroup () override
void endMemberGroup (bool) override
void insertMemberAlign (bool) override
void insertMemberAlignLeft (MemberItemType, bool) override
void writeRuler () override
void writeAnchor (const QCString &fileName, const QCString &name) override
void startEmphasis () override
void endEmphasis () override
void startBold () override
void endBold () override
void lineBreak (const QCString &style=QCString()) override
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool) override
void endMemberDoc (bool) override
void startDoxyAnchor (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &) override
void endDoxyAnchor (const QCString &, const QCString &) override
void addLabel (const QCString &, const QCString &) override
void writeChar (char c) override
void writeLatexSpacing () override
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name) override
void startCenter () override
void endCenter () override
void startSmall () override
void endSmall () override
void startMemberDescription (const QCString &, const QCString &, bool) override
void endMemberDescription () override
void startMemberDeclaration () override
void endMemberDeclaration (const QCString &, const QCString &) override
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &) override
void startExamples () override
void endExamples () override
void startDescForItem () override
void endDescForItem () override
void startSection (const QCString &, const QCString &, SectionType) override
void endSection (const QCString &, SectionType) override
void addIndexItem (const QCString &, const QCString &) override
void startIndent () override
void endIndent () override
void writeSynopsis () override
void startClassDiagram () override
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &) override
void startPageRef () override
void endPageRef (const QCString &, const QCString &) override
void startQuickIndices () override
void endQuickIndices () override
void writeSplitBar (const QCString &) override
void writeNavigationPath (const QCString &) override
void writeLogo () override
void writeQuickLinks (HighlightedItem, const QCString &) override
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool) override
void startContents () override
void endContents () override
void writeNonBreakableSpace (int) override
void startDescTable (const QCString &title, const bool hasInits) override
void endDescTable () override
void startDescTableRow () override
void endDescTableRow () override
void startDescTableTitle () override
void endDescTableTitle () override
void startDescTableInit () override
void endDescTableInit () override
void startDescTableData () override
void endDescTableData () override
void lastIndexPage () override
void startDotGraph () override
void endDotGraph (DotClassGraph &) override
void startInclDepGraph () override
void endInclDepGraph (DotInclDepGraph &) override
void startCallGraph () override
void startGroupCollaboration () override
void endGroupCollaboration (DotGroupCollaboration &g) override
void endCallGraph (DotCallGraph &) override
void startDirDepGraph () override
void endDirDepGraph (DotDirDeps &g) override
void writeGraphicalHierarchy (DotGfxHierarchyTable &) override
void startTextBlock (bool) override
void endTextBlock (bool) override
void startMemberDocPrefixItem () override
void endMemberDocPrefixItem () override
void startMemberDocName (bool) override
void endMemberDocName () override
void startParameterType (bool, const QCString &) override
void endParameterType () override
void startParameterName (bool) override
void endParameterName () override
void startParameterExtra () override
void endParameterExtra (bool last, bool one, bool bracket) override
void startParameterDefVal (const char *s) override
void endParameterDefVal () override
void startParameterList (bool) override
void endParameterList () override
void exceptionEntry (const QCString &, bool) override
void startConstraintList (const QCString &) override
void startConstraintParam () override
void endConstraintParam () override
void startConstraintType () override
void endConstraintType () override
void startConstraintDocs () override
void endConstraintDocs () override
void endConstraintList () override
void startMemberDocSimple (bool) override
void endMemberDocSimple (bool) override
void startInlineMemberType () override
void endInlineMemberType () override
void startInlineMemberName () override
void endInlineMemberName () override
void startInlineMemberDoc () override
void endInlineMemberDoc () override
void startLabels () override
void writeLabel (const QCString &l, bool isLast) override
void endLabels () override
void writeLocalToc (const SectionRefs &sr, const LocalToc &lt) override
void startPlainFile (const QCString &name) override
void endPlainFile () override
Public Member Functions inherited from OutputGenerator
OutputGenerator ()
OutputGenerator (const QCString &dir)
virtual ~OutputGenerator ()=default
QCString dir () const
QCString fileName () const
void startPlainFile (const QCString &name)
void endPlainFile ()
Public Member Functions inherited from OutputGenIntf
Static Public Member Functions
static void init ()
static void writeStyleSheetFile (TextStream &t)
static void writeHeaderFile (TextStream &t)
static void writeFooterFile (TextStream &t)
Private Member Functions
void startTitle ()
void endTitle ()
Private Attributes
bool m_firstDescItem = true
bool m_disableLinks = false
QCString m_relPath
int m_indent = 0
bool m_templateMemberItem = false
std::unique_ptr< OutputCodeList > m_codeList
LatexCodeGenerator * m_codeGen
bool m_insideTableEnv = false
int m_hierarchyLevel = 0
Additional Inherited Members
Public Types inherited from OutputGenerator
enum class ParamListTypes { Param , RetVal , Exception }
enum class MemberItemType { Normal , AnonymousStart , AnonymousEnd , Templated }
Protected Attributes inherited from OutputGenerator
TextStream m_t
QCString m_dir
Detailed Description
Generator for LaTeX output.
Definition at line 93 of file latexgen.h.
Constructor & Destructor Documentation
LatexGenerator() [1/3]
LatexGenerator::LatexGenerator ()
Definition at line 317 of file latexgen.cpp.
  : OutputGenerator(Config_getString(LATEX_OUTPUT))
  , m_codeList(std::make_unique<OutputCodeList>())
{
  m_codeGen = m_codeList->add<LatexCodeGenerator>(&m_t);
}
References Config_getString, m_codeGen, m_codeList, OutputGenerator::m_t, and OutputGenerator::OutputGenerator().
Referenced by LatexGenerator(), LatexGenerator(), operator=(), and operator=().
LatexGenerator() [2/3]
LatexGenerator::LatexGenerator (const LatexGenerator & og)
Definition at line 324 of file latexgen.cpp.
                                                       : OutputGenerator(og.m_dir), OutputGenIntf()
{
  m_codeList           = std::make_unique<OutputCodeList>(*og.m_codeList);
  m_codeGen            = m_codeList->get<LatexCodeGenerator>(OutputType::Latex);
  m_codeGen->setTextStream(&m_t);
  m_firstDescItem      = og.m_firstDescItem;
  m_disableLinks       = og.m_disableLinks;
  m_relPath            = og.m_relPath;
  m_indent             = og.m_indent;
  m_templateMemberItem = og.m_templateMemberItem;
  m_hierarchyLevel     = og.m_hierarchyLevel;
}
References Latex, LatexGenerator(), m_codeGen, m_codeList, OutputGenerator::m_dir, m_disableLinks, m_firstDescItem, m_hierarchyLevel, m_indent, m_relPath, OutputGenerator::m_t, m_templateMemberItem, and OutputGenerator::OutputGenerator().
LatexGenerator() [3/3]
LatexGenerator::LatexGenerator (LatexGenerator &&) delete
References LatexGenerator().
~LatexGenerator()
LatexGenerator::~LatexGenerator () default
Member Function Documentation
addCodeGen()
void LatexGenerator::addCodeGen (OutputCodeList & list) override virtual
Implements OutputGenIntf.
Definition at line 357 of file latexgen.cpp.
{
  list.add<LatexCodeGeneratorDefer>(m_codeGen);
}
References OutputCodeList::add(), and m_codeGen.
addIndexItem()
void LatexGenerator::addIndexItem (const QCString & s1, const QCString & s2) override virtual
Implements OutputGenIntf.
Definition at line 1688 of file latexgen.cpp.
{
  if (!s1.isEmpty())
  {
    m_t << "\\index{";
    m_t << latexEscapeLabelName(s1);
    m_t << "@{";
    m_t << latexEscapeIndexChars(s1);
    m_t << "}";
    if (!s2.isEmpty())
    {
      m_t << "!";
      m_t << latexEscapeLabelName(s2);
      m_t << "@{";
      m_t << latexEscapeIndexChars(s2);
      m_t << "}";
    }
    m_t << "}";
  }
}
References QCString::isEmpty(), latexEscapeIndexChars(), latexEscapeLabelName(), and OutputGenerator::m_t.
addLabel()
void LatexGenerator::addLabel (const QCString & fName, const QCString & anchor) override virtual
Implements OutputGenIntf.
Definition at line 1654 of file latexgen.cpp.
{
  m_t << "\\label{";
  if (!fName.isEmpty()) m_t << stripPath(fName);
  if (!anchor.isEmpty()) m_t << "_" << anchor;
  if (m_insideTableEnv) m_t << "}";
  m_t << "} \n";
}
References QCString::isEmpty(), m_insideTableEnv, OutputGenerator::m_t, and stripPath().
addWord()
void LatexGenerator::addWord (const QCString & , bool) inline
Definition at line 110 of file latexgen.h.
{}
cleanup()
void LatexGenerator::cleanup () override virtual
Implements OutputGenIntf.
Definition at line 670 of file latexgen.cpp.
{
  QCString dname = Config_getString(LATEX_OUTPUT);
  Dir d(dname.str());
  clearSubDirs(d);
}
References clearSubDirs(), Config_getString, and QCString::str().
clearBuffer()
void LatexGenerator::clearBuffer ()
clone()
std::unique_ptr< OutputGenIntf > LatexGenerator::clone () inline override virtual
Implements OutputGenIntf.
Definition at line 115 of file latexgen.h.
{ return std::make_unique<LatexGenerator>(*this); }
docify()
void LatexGenerator::docify (const QCString & text) override virtual
Implements OutputGenIntf.
Definition at line 1757 of file latexgen.cpp.
{
  filterLatexString(m_t,str,
                    m_codeGen->insideTabbing(), // insideTabbing
                    false,           // insidePre
                    false,           // insideItem
                    m_codeGen->usedTableLevel()>0,  // insideTable
                    false            // keepSpaces
                   );
}
References filterLatexString(), m_codeGen, and OutputGenerator::m_t.
Referenced by startConstraintList(), startExamples(), startMemberDocSimple(), startParameterDefVal(), startParameterType(), writeChar(), and writeStartAnnoItem().
endAnonTypeScope()
void LatexGenerator::endAnonTypeScope (int indent) override virtual
Implements OutputGenIntf.
Definition at line 1800 of file latexgen.cpp.
{
  if (indent==0)
  {
    m_t << "\n" << "\\end{tabbing}";
    m_codeGen->setInsideTabbing(false);
  }
  m_indent=indent;
}
References m_codeGen, m_indent, and OutputGenerator::m_t.
endBold()
void LatexGenerator::endBold () inline override virtual
Implements OutputGenIntf.
Definition at line 202 of file latexgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endCallGraph()
void LatexGenerator::endCallGraph (DotCallGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 2048 of file latexgen.cpp.
{
  g.writeGraph(m_t,GraphOutputFormat::EPS,EmbeddedOutputFormat::LaTeX,dir(),fileName(),m_relPath);
}
References OutputGenerator::dir(), EPS, OutputGenerator::fileName(), LaTeX, m_relPath, OutputGenerator::m_t, and DotCallGraph::writeGraph().
endCenter()
void LatexGenerator::endCenter () inline override virtual
Implements OutputGenIntf.
Definition at line 214 of file latexgen.h.
{ m_t << "\\end{center}\n"; }
References OutputGenerator::m_t.
endClassDiagram()
void LatexGenerator::endClassDiagram (const ClassDiagram & d, const QCString & fileName, const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 1782 of file latexgen.cpp.
{
  d.writeFigure(m_t,dir(),fileName);
}
References OutputGenerator::dir(), OutputGenerator::fileName(), OutputGenerator::m_t, and ClassDiagram::writeFigure().
endCompoundTemplateParams()
void LatexGenerator::endCompoundTemplateParams () inline override virtual
Implements OutputGenIntf.
Definition at line 185 of file latexgen.h.
{ m_t << "}\n"; }
References OutputGenerator::m_t.
endConstraintDocs()
void LatexGenerator::endConstraintDocs () override virtual
Implements OutputGenIntf.
Definition at line 2177 of file latexgen.cpp.
{
}
endConstraintList()
void LatexGenerator::endConstraintList () override virtual
Implements OutputGenIntf.
Definition at line 2181 of file latexgen.cpp.
{
  m_t << "\\end{description}\n";
  m_t << "\\end{Desc}\n";
}
References OutputGenerator::m_t.
endConstraintParam()
void LatexGenerator::endConstraintParam () override virtual
Implements OutputGenIntf.
Definition at line 2159 of file latexgen.cpp.
{
}
endConstraintType()
void LatexGenerator::endConstraintType () override virtual
Implements OutputGenIntf.
Definition at line 2168 of file latexgen.cpp.
{
  m_t << "}]";
}
References OutputGenerator::m_t.
endContents()
void LatexGenerator::endContents () inline override virtual
Implements OutputGenIntf.
Definition at line 245 of file latexgen.h.
{}
endDescForItem()
void LatexGenerator::endDescForItem () inline override virtual
Implements OutputGenIntf.
Definition at line 226 of file latexgen.h.
{}
endDescTable()
void LatexGenerator::endDescTable () override virtual
Implements OutputGenIntf.
Definition at line 1906 of file latexgen.cpp.
{
  m_codeGen->decUsedTableLevel();
  m_t << "\\end{DoxyEnumFields}\n";
}
References m_codeGen, and OutputGenerator::m_t.
endDescTableData()
void LatexGenerator::endDescTableData () override virtual
Implements OutputGenIntf.
Definition at line 1946 of file latexgen.cpp.
{
  m_t << "\\\\\n\\hline\n\n";
}
References OutputGenerator::m_t.
endDescTableInit()
void LatexGenerator::endDescTableInit () override virtual
Implements OutputGenIntf.
Definition at line 1937 of file latexgen.cpp.
{
}
endDescTableRow()
void LatexGenerator::endDescTableRow () override virtual
Implements OutputGenIntf.
Definition at line 1919 of file latexgen.cpp.
{
}
endDescTableTitle()
void LatexGenerator::endDescTableTitle () override virtual
Implements OutputGenIntf.
Definition at line 1928 of file latexgen.cpp.
{
}
endDirDepGraph()
void LatexGenerator::endDirDepGraph (DotDirDeps & g) override virtual
Implements OutputGenIntf.
Definition at line 2057 of file latexgen.cpp.
{
  g.writeGraph(m_t,GraphOutputFormat::EPS,EmbeddedOutputFormat::LaTeX,dir(),fileName(),m_relPath);
}
References OutputGenerator::dir(), EPS, OutputGenerator::fileName(), LaTeX, m_relPath, OutputGenerator::m_t, and DotDirDeps::writeGraph().
endDotGraph()
void LatexGenerator::endDotGraph (DotClassGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 2021 of file latexgen.cpp.
{
  g.writeGraph(m_t,GraphOutputFormat::EPS,EmbeddedOutputFormat::LaTeX,dir(),fileName(),m_relPath);
}
References OutputGenerator::dir(), EPS, OutputGenerator::fileName(), LaTeX, m_relPath, OutputGenerator::m_t, and DotClassGraph::writeGraph().
endDoxyAnchor()
void LatexGenerator::endDoxyAnchor (const QCString & , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 1650 of file latexgen.cpp.
{
}
endEmphasis()
void LatexGenerator::endEmphasis () inline override virtual
Implements OutputGenIntf.
Definition at line 200 of file latexgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endExamples()
void LatexGenerator::endExamples () override virtual
Implements OutputGenIntf.
Definition at line 2069 of file latexgen.cpp.
{
  m_t << "\\end{Desc}\n";
}
References OutputGenerator::m_t.
endFile()
void LatexGenerator::endFile () override virtual
Implements OutputGenIntf.
Definition at line 714 of file latexgen.cpp.
{
  endPlainFile();
  m_codeGen->setSourceFileName("");
}
References endPlainFile(), and m_codeGen.
endGroupCollaboration()
void LatexGenerator::endGroupCollaboration (DotGroupCollaboration & g) override virtual
Implements OutputGenIntf.
Definition at line 2039 of file latexgen.cpp.
{
  g.writeGraph(m_t,GraphOutputFormat::EPS,EmbeddedOutputFormat::LaTeX,dir(),fileName(),m_relPath);
}
References OutputGenerator::dir(), EPS, OutputGenerator::fileName(), LaTeX, m_relPath, OutputGenerator::m_t, and DotGroupCollaboration::writeGraph().
endGroupHeader()
void LatexGenerator::endGroupHeader (int) override virtual
Implements OutputGenIntf.
Definition at line 1531 of file latexgen.cpp.
{
  m_disableLinks=FALSE;
  m_t << "}\n";
}
References FALSE, m_disableLinks, and OutputGenerator::m_t.
endHeaderSection()
void LatexGenerator::endHeaderSection () inline override virtual
Implements OutputGenIntf.
Definition at line 167 of file latexgen.h.
{}
endInclDepGraph()
void LatexGenerator::endInclDepGraph (DotInclDepGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 2030 of file latexgen.cpp.
{
  g.writeGraph(m_t,GraphOutputFormat::EPS,EmbeddedOutputFormat::LaTeX,dir(),fileName(),m_relPath);
}
References OutputGenerator::dir(), EPS, OutputGenerator::fileName(), LaTeX, m_relPath, OutputGenerator::m_t, and DotInclDepGraph::writeGraph().
endIndent()
void LatexGenerator::endIndent () inline override virtual
Implements OutputGenIntf.
Definition at line 231 of file latexgen.h.
{}
endIndexItem()
void LatexGenerator::endIndexItem (const QCString & ref, const QCString & file) override virtual
Implements OutputGenIntf.
Definition at line 1326 of file latexgen.cpp.
{
  if (ref.isEmpty() && !fn.isEmpty())
  {
    m_t << "}{\\pageref{" << stripPath(fn) << "}}{}\n";
  }
}
References QCString::isEmpty(), OutputGenerator::m_t, and stripPath().
endIndexKey()
void LatexGenerator::endIndexKey () override virtual
Implements OutputGenIntf.
Definition at line 1348 of file latexgen.cpp.
{
}
endIndexList()
void LatexGenerator::endIndexList () inline override virtual
Implements OutputGenIntf.
Definition at line 142 of file latexgen.h.
{ m_t << "\\end{DoxyCompactList}\n"; }
References OutputGenerator::m_t.
endIndexListItem()
void LatexGenerator::endIndexListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 140 of file latexgen.h.
{}
endIndexSection()
void LatexGenerator::endIndexSection (IndexSection is) override virtual
Implements OutputGenIntf.
Definition at line 1071 of file latexgen.cpp.
{
  switch (is)
  {
    case IndexSection::isTitlePageStart:
      break;
    case IndexSection::isTitlePageAuthor:
      break;
    case IndexSection::isMainPage:
      {
        if (Doxygen::mainPage)
        {
          writePageLink(Doxygen::mainPage->getOutputFileBase(), FALSE);
        }
      }
      break;
    case IndexSection::isModuleIndex:
      m_t << "}\n\\input{modules}\n";
      break;
    case IndexSection::isTopicIndex:
      m_t << "}\n\\input{topics}\n";
      break;
    case IndexSection::isDirIndex:
      m_t << "}\n\\input{dirs}\n";
      break;
    case IndexSection::isNamespaceIndex:
      m_t << "}\n\\input{namespaces}\n";
      break;
    case IndexSection::isConceptIndex:
      m_t << "}\n\\input{concepts}\n";
      break;
    case IndexSection::isClassHierarchyIndex:
      m_t << "}\n\\input{hierarchy}\n";
      break;
    case IndexSection::isCompoundIndex:
      m_t << "}\n\\input{annotated}\n";
      break;
    case IndexSection::isFileIndex:
      m_t << "}\n\\input{files}\n";
      break;
    case IndexSection::isPageIndex:
      m_t << "}\n\\input{pages}\n";
      break;
    case IndexSection::isTopicDocumentation:
      {
        m_t << "}\n";
        for (const auto &gd : *Doxygen::groupLinkedMap)
        {
          if (!gd->isReference() && !gd->isASubGroup())
          {
            writePageLink(gd->getOutputFileBase(), FALSE);
          }
        }
      }
      break;
    case IndexSection::isModuleDocumentation:
      {
        m_t << "}\n";
        for (const auto &mod : ModuleManager::instance().modules())
        {
          if (!mod->isReference() && mod->isPrimaryInterface())
          {
            writePageLink(mod->getOutputFileBase(), FALSE);
          }
        }
      }
      break;
    case IndexSection::isDirDocumentation:
      {
        bool found=FALSE;
        for (const auto &dd : *Doxygen::dirLinkedMap)
        {
          if (dd->isLinkableInProject())
          {
            if (!found)
            {
              m_t << "}\n";
              found = TRUE;
            }
            m_t << "\\input{" << dd->getOutputFileBase() << "}\n";
          }
        }
      }
      break;
    case IndexSection::isNamespaceDocumentation:
      {
        bool found=FALSE;
        for (const auto &nd : *Doxygen::namespaceLinkedMap)
        {
          if (nd->isLinkableInProject() && !nd->isAlias())
          {
            if (!found)
            {
              m_t << "}\n";
              found=true;
            }
            m_t << "\\input{" << nd->getOutputFileBase() << "}\n";
          }
        }
      }
      break;
    case IndexSection::isConceptDocumentation:
      {
        bool found=FALSE;
        for (const auto &cd : *Doxygen::conceptLinkedMap)
        {
          if (cd->isLinkableInProject() && !cd->isAlias())
          {
            if (!found)
            {
              m_t << "}\n";
              found=true;
            }
            m_t << "\\input{" << cd->getOutputFileBase() << "}\n";
          }
        }
      }
      break;
    case IndexSection::isClassDocumentation:
      {
        bool found=FALSE;
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->isLinkableInProject() &&
              cd->templateMaster()==nullptr &&
             !cd->isEmbeddedInOuterScope() &&
             !cd->isAlias()
             )
          {
            if (!found)
            {
              m_t << "}\n"; // end doxysection or chapter title
              found=TRUE;
            }
            m_t << "\\input{" << cd->getOutputFileBase() << "}\n";
          }
        }
      }
      break;
    case IndexSection::isFileDocumentation:
      {
        bool isFirst=TRUE;
        for (const auto &fn : *Doxygen::inputNameLinkedMap)
        {
          for (const auto &fd : *fn)
          {
            if (fd->isLinkableInProject())
            {
              if (isFirst)
              {
                m_t << "}\n"; // end doxysection or chapter title
              }
              isFirst=FALSE;
              m_t << "\\input{" << fd->getOutputFileBase() << "}\n";
            }
            if (fd->generateSourceFile())
            {
              if (isFirst)
              {
                m_t << "}\n"; // end doxysection or chapter title
              }
              isFirst=FALSE;
              m_t << "\\input{" << fd->getSourceFileBase() << "}\n";
            }
          }
        }
      }
      break;
    case IndexSection::isExampleDocumentation:
      {
        m_t << "}\n";
        for (const auto &pd : *Doxygen::exampleLinkedMap)
        {
          m_t << "\\input{" << pd->getOutputFileBase() << "}\n";
        }
      }
      break;
    case IndexSection::isPageDocumentation:
      {
        for (const auto &pd : *Doxygen::pageLinkedMap)
        {
          if (!pd->getGroupDef() && !pd->isReference() && !pd->hasParentPage()
            && pd->name() != "citelist" && Doxygen::mainPage.get() != pd.get())
          {
            writePageLink(pd->getOutputFileBase(), FALSE);
          }
        }
      }
      break;
    case IndexSection::isPageDocumentation2:
      break;
    case IndexSection::isEndIndex:
      m_t << substituteLatexKeywords(g_footer,convertToLaTeX(Config_getString(PROJECT_NAME),m_codeGen->insideTabbing()));
      break;
  }
}
References Doxygen::classLinkedMap, Doxygen::conceptLinkedMap, Config_getString, convertToLaTeX(), Doxygen::dirLinkedMap, Doxygen::exampleLinkedMap, FALSE, found, g_footer, Doxygen::groupLinkedMap, Doxygen::inputNameLinkedMap, ModuleManager::instance(), isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, isTopicDocumentation, isTopicIndex, m_codeGen, OutputGenerator::m_t, Doxygen::mainPage, Doxygen::namespaceLinkedMap, Doxygen::pageLinkedMap, substituteLatexKeywords(), TRUE, and writePageLink().
endIndexValue()
void LatexGenerator::endIndexValue (const QCString & name, bool) override virtual
Implements OutputGenIntf.
Definition at line 1358 of file latexgen.cpp.
{
  //if (hasBrief) m_t << ")";
  m_t << "}{\\pageref{" << stripPath(name) << "}}{}\n";
}
References OutputGenerator::m_t, and stripPath().
endInlineHeader()
void LatexGenerator::endInlineHeader () override virtual
Implements OutputGenIntf.
Definition at line 2199 of file latexgen.cpp.
{
  m_t << "}\n";
}
References OutputGenerator::m_t.
endInlineMemberDoc()
void LatexGenerator::endInlineMemberDoc () override virtual
Implements OutputGenIntf.
Definition at line 2273 of file latexgen.cpp.
{
  m_t << "\\\\\n\\hline\n\n";
}
References OutputGenerator::m_t.
endInlineMemberName()
void LatexGenerator::endInlineMemberName () override virtual
Implements OutputGenIntf.
Definition at line 2263 of file latexgen.cpp.
{
  m_t << "&\n";
  m_codeGen->setInsideTabbing(false);
}
References m_codeGen, and OutputGenerator::m_t.
endInlineMemberType()
void LatexGenerator::endInlineMemberType () override virtual
Implements OutputGenIntf.
Definition at line 2252 of file latexgen.cpp.
{
  m_t << "&\n";
  m_codeGen->setInsideTabbing(false);
}
References m_codeGen, and OutputGenerator::m_t.
endItemList()
void LatexGenerator::endItemList () inline override virtual
Implements OutputGenIntf.
Definition at line 148 of file latexgen.h.
{ m_t << "\\end{DoxyCompactItemize}\n"; }
References OutputGenerator::m_t.
endItemListItem()
void LatexGenerator::endItemListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 162 of file latexgen.h.
{}
endLabels()
void LatexGenerator::endLabels () override virtual
Implements OutputGenIntf.
Definition at line 2289 of file latexgen.cpp.
{
}
endMemberDeclaration()
void LatexGenerator::endMemberDeclaration (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 220 of file latexgen.h.
{}
endMemberDescription()
void LatexGenerator::endMemberDescription () override virtual
Implements OutputGenIntf.
Definition at line 1859 of file latexgen.cpp.
{
  if (!m_codeGen->insideTabbing())
  {
    //m_t << "\\item\\end{DoxyCompactList}";
    m_t << "\\end{DoxyCompactList}";
  }
  else
  {
    m_t << "}\\\\\n";
  }
}
References m_codeGen, and OutputGenerator::m_t.
endMemberDoc()
void LatexGenerator::endMemberDoc (bool) override virtual
Implements OutputGenIntf.
Definition at line 1627 of file latexgen.cpp.
{
  m_disableLinks=FALSE;
  m_t << "}\n\n";
  //if (Config_getBool(COMPACT_LATEX)) m_t << "\\hfill";
}
References FALSE, m_disableLinks, and OutputGenerator::m_t.
endMemberDocList()
void LatexGenerator::endMemberDocList () inline override virtual
Implements OutputGenIntf.
Definition at line 173 of file latexgen.h.
{}
endMemberDocName()
void LatexGenerator::endMemberDocName () inline override virtual
Implements OutputGenIntf.
Definition at line 278 of file latexgen.h.
{}
endMemberDocPrefixItem()
void LatexGenerator::endMemberDocPrefixItem () inline override virtual
Implements OutputGenIntf.
Definition at line 276 of file latexgen.h.
{ m_t << "\\\\\n"; }
References OutputGenerator::m_t.
endMemberDocSimple()
void LatexGenerator::endMemberDocSimple (bool isEnum) override virtual
Implements OutputGenIntf.
Definition at line 2233 of file latexgen.cpp.
{
  m_insideTableEnv=false;
  m_codeGen->decUsedTableLevel();
  if (isEnum)
  {
    m_t << "\\end{DoxyEnumFields}\n";
  }
  else
  {
    m_t << "\\end{DoxyFields}\n";
  }
}
References m_codeGen, m_insideTableEnv, and OutputGenerator::m_t.
endMemberGroup()
void LatexGenerator::endMemberGroup (bool hasHeader) override virtual
Implements OutputGenIntf.
Definition at line 2010 of file latexgen.cpp.
{
  if (hasHeader)m_t << "\\end{Indent}";
  m_t << "\n";
}
References OutputGenerator::m_t.
endMemberGroupDocs()
void LatexGenerator::endMemberGroupDocs () override virtual
Implements OutputGenIntf.
Definition at line 2001 of file latexgen.cpp.
{
  m_t << "}";
}
References OutputGenerator::m_t.
endMemberGroupHeader()
void LatexGenerator::endMemberGroupHeader () override virtual
Implements OutputGenIntf.
Definition at line 1989 of file latexgen.cpp.
{
  // changed back to rev 756 due to bug 660501
  m_t << "}\\par\n";
  //m_t << "}\n";
}
References OutputGenerator::m_t.
endMemberHeader()
void LatexGenerator::endMemberHeader () override virtual
Implements OutputGenIntf.
Definition at line 1549 of file latexgen.cpp.
{
  m_disableLinks=FALSE;
  m_t << "}\n";
}
References FALSE, m_disableLinks, and OutputGenerator::m_t.
endMemberItem()
void LatexGenerator::endMemberItem (MemberItemType) override virtual
Implements OutputGenIntf.
Definition at line 1836 of file latexgen.cpp.
{
  if (m_codeGen->insideTabbing())
  {
    m_t << "\\\\";
  }
  m_templateMemberItem = FALSE;
  m_t << "\n";
}
References FALSE, m_codeGen, OutputGenerator::m_t, and m_templateMemberItem.
endMemberList()
void LatexGenerator::endMemberList () override virtual
Implements OutputGenIntf.
Definition at line 1964 of file latexgen.cpp.
{
  //printf("LatexGenerator::endMemberList(%d)\n",m_codeGen->InsideTabbing());
  if (!m_codeGen->insideTabbing())
  {
    m_t << "\\end{DoxyCompactItemize}\n";
  }
}
References m_codeGen, and OutputGenerator::m_t.
endMemberSections()
void LatexGenerator::endMemberSections () inline override virtual
Implements OutputGenIntf.
Definition at line 165 of file latexgen.h.
{}
endMemberSubtitle()
void LatexGenerator::endMemberSubtitle () inline override virtual
Implements OutputGenIntf.
Definition at line 171 of file latexgen.h.
{}
endMemberTemplateParams()
void LatexGenerator::endMemberTemplateParams (const QCString & , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 1818 of file latexgen.cpp.
{
  if (m_templateMemberItem)
  {
    m_t << "}\\\\";
  }
}
References OutputGenerator::m_t, and m_templateMemberItem.
endPageDoc()
void LatexGenerator::endPageDoc () inline override virtual
Implements OutputGenIntf.
Definition at line 126 of file latexgen.h.
{}
endPageRef()
void LatexGenerator::endPageRef (const QCString & clname, const QCString & anchor) override virtual
Implements OutputGenIntf.
Definition at line 1447 of file latexgen.cpp.
{
  m_t << "}{";
  if (!clname.isEmpty()) m_t << clname;
  if (!anchor.isEmpty()) m_t << "_" << anchor;
  m_t << "}";
}
References QCString::isEmpty(), and OutputGenerator::m_t.
endParagraph()
void LatexGenerator::endParagraph () override virtual
Implements OutputGenIntf.
Definition at line 1307 of file latexgen.cpp.
{
  m_t << "\n" << "\n";
}
References OutputGenerator::m_t.
endParameterDefVal()
void LatexGenerator::endParameterDefVal () inline override virtual
Implements OutputGenIntf.
Definition at line 286 of file latexgen.h.
{ endTypewriter(); }
References endTypewriter().
endParameterExtra()
void LatexGenerator::endParameterExtra (bool last, bool one, bool bracket) override virtual
Implements OutputGenIntf.
Definition at line 2111 of file latexgen.cpp.
{
  m_t << "}";
  if (last)
  {
    m_t << "\\end{DoxyParamCaption}";
    if (closeBracket) m_t << ")";
  }
}
References OutputGenerator::m_t.
endParameterList()
void LatexGenerator::endParameterList () override virtual
Implements OutputGenIntf.
Definition at line 2081 of file latexgen.cpp.
{
}
endParameterName()
void LatexGenerator::endParameterName () override virtual
Implements OutputGenIntf.
Definition at line 2101 of file latexgen.cpp.
{
  m_t << "}";
}
References OutputGenerator::m_t.
endParameterType()
void LatexGenerator::endParameterType () override virtual
Implements OutputGenIntf.
Definition at line 2091 of file latexgen.cpp.
{
  m_t << "}]";
}
References OutputGenerator::m_t.
endPlainFile()
void LatexGenerator::endPlainFile () inline override virtual
Implements OutputGenIntf.
Definition at line 315 of file latexgen.h.
{ OutputGenerator::endPlainFile(); }
References OutputGenerator::endPlainFile().
Referenced by endFile(), and writeStyleInfo().
endProjectNumber()
void LatexGenerator::endProjectNumber () inline override virtual
Implements OutputGenIntf.
Definition at line 131 of file latexgen.h.
{}
endQuickIndices()
void LatexGenerator::endQuickIndices () inline override virtual
Implements OutputGenIntf.
Definition at line 238 of file latexgen.h.
{}
endSection()
void LatexGenerator::endSection (const QCString & lab, SectionType) override virtual
Implements OutputGenIntf.
Definition at line 1751 of file latexgen.cpp.
{
  m_t << "}\\label{" << lab << "}\n";
}
References OutputGenerator::m_t.
endSmall()
void LatexGenerator::endSmall () inline override virtual
Implements OutputGenIntf.
Definition at line 216 of file latexgen.h.
{ m_t << "\\normalsize "; }
References OutputGenerator::m_t.
endTextBlock()
void LatexGenerator::endTextBlock (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 273 of file latexgen.h.
{}
endTextLink()
void LatexGenerator::endTextLink () override virtual
Implements OutputGenIntf.
Definition at line 1388 of file latexgen.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  if (!m_disableLinks && pdfHyperlinks)
  {
    m_t << "}";
  }
  m_t << "}";
}
References Config_getBool, m_disableLinks, and OutputGenerator::m_t.
endTitle()
void LatexGenerator::endTitle () inline private
Definition at line 320 of file latexgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endTitleHead()
void LatexGenerator::endTitleHead (const QCString & fileName, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1470 of file latexgen.cpp.
{
  m_t << "}\n";
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  bool usePDFLatex   = Config_getBool(USE_PDFLATEX);
  if (usePDFLatex && pdfHyperlinks && !fileName.isEmpty())
  {
    m_t << "\\hypertarget{" << stripPath(fileName) << "}{}";
  }
  QCString fn = stripPath(fileName);
  if (!fn.isEmpty())
  {
    m_t << "\\label{" << fn << "}";
  }
  if (!name.isEmpty())
  {
    m_t << "\\index{";
    m_t << latexEscapeLabelName(name);
    m_t << "@{";
    m_t << latexEscapeIndexChars(name);
    m_t << "}}\n";
  }
}
References Config_getBool, OutputGenerator::fileName(), QCString::isEmpty(), latexEscapeIndexChars(), latexEscapeLabelName(), OutputGenerator::m_t, and stripPath().
endTypewriter()
void LatexGenerator::endTypewriter () inline override virtual
Implements OutputGenIntf.
Definition at line 158 of file latexgen.h.
{ m_t << "}";      }
References OutputGenerator::m_t.
Referenced by endParameterDefVal().
exceptionEntry()
void LatexGenerator::exceptionEntry (const QCString & prefix, bool closeBracket) override virtual
Implements OutputGenIntf.
Definition at line 2121 of file latexgen.cpp.
{
  if (!prefix.isEmpty())
  {
    m_t << " " << prefix << "(";
  }
  else if (closeBracket)
  {
    m_t << ")";
  }
  m_t << " ";
}
References OutputGenerator::m_t, and prefix.
init()
void LatexGenerator::init () static
Definition at line 628 of file latexgen.cpp.
{
  QCString dname = Config_getString(LATEX_OUTPUT);
  Dir d(dname.str());
  if (!d.exists() && !d.mkdir(dname.str()))
  {
    term("Could not create output directory %s\n",qPrint(dname));
  }
  if (!Config_getString(LATEX_HEADER).isEmpty())
  {
    g_header=fileToString(Config_getString(LATEX_HEADER));
    //printf("g_header='%s'\n",qPrint(g_header));
    QCString result = substituteLatexKeywords(g_header,QCString());
    checkBlocks(result,Config_getString(LATEX_HEADER),latexMarkerInfo);
  }
  else
  {
    g_header = ResourceMgr::instance().getAsString("header.tex");
    QCString result = substituteLatexKeywords(g_header,QCString());
    checkBlocks(result,"<default header.tex>",latexMarkerInfo);
  }
  if (!Config_getString(LATEX_FOOTER).isEmpty())
  {
    g_footer=fileToString(Config_getString(LATEX_FOOTER));
    //printf("g_footer='%s'\n",qPrint(g_footer));
    QCString result = substituteLatexKeywords(g_footer,QCString());
    checkBlocks(result,Config_getString(LATEX_FOOTER),latexMarkerInfo);
  }
  else
  {
    g_footer = ResourceMgr::instance().getAsString("footer.tex");
    QCString result = substituteLatexKeywords(g_footer,QCString());
    checkBlocks(result,"<default footer.tex>",latexMarkerInfo);
  }
  writeLatexMakefile();
  writeMakeBat();
  createSubDirs(d);
}
References checkBlocks(), Config_getString, createSubDirs(), Dir::exists(), fileToString(), g_footer, g_header, ResourceMgr::getAsString(), ResourceMgr::instance(), latexMarkerInfo, Dir::mkdir(), qPrint(), QCString::str(), substituteLatexKeywords(), term, writeLatexMakefile(), and writeMakeBat().
Referenced by generateOutput().
insertMemberAlign()
void LatexGenerator::insertMemberAlign (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 194 of file latexgen.h.
{}
insertMemberAlignLeft()
void LatexGenerator::insertMemberAlignLeft (MemberItemType , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 195 of file latexgen.h.
{}
lastIndexPage()
void LatexGenerator::lastIndexPage () override virtual
Implements OutputGenIntf.
Definition at line 1951 of file latexgen.cpp.
{
}
lineBreak()
void LatexGenerator::lineBreak (const QCString & style = QCString()) override virtual
Implements OutputGenIntf.
Definition at line 2204 of file latexgen.cpp.
{
  if (m_codeGen->insideTabbing())
  {
    m_t << "\\\\\n";
  }
  else
  {
    m_t << "\\newline\n";
  }
}
References m_codeGen, and OutputGenerator::m_t.
operator=() [1/2]
LatexGenerator & LatexGenerator::operator= (const LatexGenerator & og)
Definition at line 337 of file latexgen.cpp.
{
  if (this!=&og)
  {
    m_dir                = og.m_dir;
    m_codeList           = std::make_unique<OutputCodeList>(*og.m_codeList);
    m_codeGen            = m_codeList->get<LatexCodeGenerator>(OutputType::Latex);
    m_codeGen->setTextStream(&m_t);
    m_firstDescItem      = og.m_firstDescItem;
    m_disableLinks       = og.m_disableLinks;
    m_relPath            = og.m_relPath;
    m_indent             = og.m_indent;
    m_templateMemberItem = og.m_templateMemberItem;
    m_hierarchyLevel     = og.m_hierarchyLevel;
  }
  return *this;
}
References Latex, LatexGenerator(), m_codeGen, m_codeList, OutputGenerator::m_dir, m_disableLinks, m_firstDescItem, m_hierarchyLevel, m_indent, m_relPath, OutputGenerator::m_t, and m_templateMemberItem.
operator=() [2/2]
LatexGenerator & LatexGenerator::operator= (LatexGenerator &&) delete
References LatexGenerator().
setCurrentDoc()
void LatexGenerator::setCurrentDoc (const Definition * , const QCString & , bool) inline
Definition at line 109 of file latexgen.h.
{}
startAnonTypeScope()
void LatexGenerator::startAnonTypeScope (int indent) override virtual
Implements OutputGenIntf.
Definition at line 1789 of file latexgen.cpp.
{
  if (indent==0)
  {
    m_t << "\\begin{tabbing}\n";
    m_t << "xx\\=xx\\=xx\\=xx\\=xx\\=xx\\=xx\\=xx\\=xx\\=\\kill\n";
    m_codeGen->setInsideTabbing(true);
  }
  m_indent=indent;
}
References m_codeGen, m_indent, and OutputGenerator::m_t.
startBold()
void LatexGenerator::startBold () inline override virtual
Implements OutputGenIntf.
Definition at line 201 of file latexgen.h.
{ m_t << "{\\bfseries "; }
References OutputGenerator::m_t.
startCallGraph()
void LatexGenerator::startCallGraph () override virtual
Implements OutputGenIntf.
Definition at line 2044 of file latexgen.cpp.
{
}
startCenter()
void LatexGenerator::startCenter () inline override virtual
Implements OutputGenIntf.
Definition at line 213 of file latexgen.h.
{ m_t << "\\begin{center}\n"; }
References OutputGenerator::m_t.
startClassDiagram()
void LatexGenerator::startClassDiagram () override virtual
Implements OutputGenIntf.
Definition at line 1776 of file latexgen.cpp.
{
  //if (Config_getBool(COMPACT_LATEX)) m_t << "\\doxysubsubsection"; else m_t << "\\doxysubsection";
  //m_t << "{";
}
startCompoundTemplateParams()
void LatexGenerator::startCompoundTemplateParams () inline override virtual
Implements OutputGenIntf.
Definition at line 184 of file latexgen.h.
{ m_t << "\\subsubsection*{";}
References OutputGenerator::m_t.
startConstraintDocs()
void LatexGenerator::startConstraintDocs () override virtual
Implements OutputGenIntf.
Definition at line 2173 of file latexgen.cpp.
{
}
startConstraintList()
void LatexGenerator::startConstraintList (const QCString & header) override virtual
Implements OutputGenIntf.
Definition at line 2146 of file latexgen.cpp.
{
  m_t << "\\begin{Desc}\n\\item[";
  docify(header);
  m_t << "]";
  m_t << "\\begin{description}\n";
}
References docify(), and OutputGenerator::m_t.
startConstraintParam()
void LatexGenerator::startConstraintParam () override virtual
Implements OutputGenIntf.
Definition at line 2154 of file latexgen.cpp.
{
  m_t << "\\item[{\\em ";
}
References OutputGenerator::m_t.
startConstraintType()
void LatexGenerator::startConstraintType () override virtual
Implements OutputGenIntf.
Definition at line 2163 of file latexgen.cpp.
{
  m_t << "} : {\\em ";
}
References OutputGenerator::m_t.
startContents()
void LatexGenerator::startContents () inline override virtual
Implements OutputGenIntf.
Definition at line 244 of file latexgen.h.
{}
startDescForItem()
void LatexGenerator::startDescForItem () inline override virtual
Implements OutputGenIntf.
Definition at line 225 of file latexgen.h.
{ m_t << "\\par\n"; }
References OutputGenerator::m_t.
startDescTable()
void LatexGenerator::startDescTable (const QCString & title, const bool hasInits) override virtual
Implements OutputGenIntf.
Definition at line 1900 of file latexgen.cpp.
{
  m_codeGen->incUsedTableLevel();
  m_t << "\\begin{DoxyEnumFields}[" << (hasInits?3:2) << "]{" << title << "}\n";
}
References m_codeGen, and OutputGenerator::m_t.
startDescTableData()
void LatexGenerator::startDescTableData () override virtual
Implements OutputGenIntf.
Definition at line 1941 of file latexgen.cpp.
{
  m_t << "&";
}
References OutputGenerator::m_t.
startDescTableInit()
void LatexGenerator::startDescTableInit () override virtual
Implements OutputGenIntf.
Definition at line 1932 of file latexgen.cpp.
{
  m_t << "&";
}
References OutputGenerator::m_t.
startDescTableRow()
void LatexGenerator::startDescTableRow () override virtual
Implements OutputGenIntf.
Definition at line 1912 of file latexgen.cpp.
{
  // this is needed to prevent the \hypertarget, \label, and \index commands from messing up
  // the row height (based on http://tex.stackexchange.com/a/186102)
  m_t << "\\raisebox{\\heightof{T}}[0pt][0pt]{";
}
References OutputGenerator::m_t.
startDescTableTitle()
void LatexGenerator::startDescTableTitle () override virtual
Implements OutputGenIntf.
Definition at line 1923 of file latexgen.cpp.
{
  m_t << "}";
}
References OutputGenerator::m_t.
startDirDepGraph()
void LatexGenerator::startDirDepGraph () override virtual
Implements OutputGenIntf.
Definition at line 2053 of file latexgen.cpp.
{
}
startDotGraph()
void LatexGenerator::startDotGraph () override virtual
Implements OutputGenIntf.
Definition at line 2016 of file latexgen.cpp.
{
  m_t << "\n" << "\n";
}
References OutputGenerator::m_t.
startDoxyAnchor()
void LatexGenerator::startDoxyAnchor (const QCString & fName, const QCString & , const QCString & anchor, const QCString & , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 1634 of file latexgen.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  bool usePDFLatex   = Config_getBool(USE_PDFLATEX);
  if (m_insideTableEnv) m_t << "\\mbox{"; // see issue #6093
  if (usePDFLatex && pdfHyperlinks)
  {
    m_t << "\\Hypertarget{";
    if (!fName.isEmpty()) m_t << stripPath(fName);
    if (!anchor.isEmpty()) m_t << "_" << anchor;
    m_t << "}";
  }
}
References Config_getBool, QCString::isEmpty(), m_insideTableEnv, OutputGenerator::m_t, and stripPath().
startEmphasis()
void LatexGenerator::startEmphasis () inline override virtual
Implements OutputGenIntf.
Definition at line 199 of file latexgen.h.
{ m_t << "{\\em ";  }
References OutputGenerator::m_t.
startExamples()
void LatexGenerator::startExamples () override virtual
Implements OutputGenIntf.
Definition at line 2062 of file latexgen.cpp.
{
  m_t << "\\begin{Desc}\n\\item[";
  docify(theTranslator->trExamples());
  m_t << "]";
}
References docify(), OutputGenerator::m_t, theTranslator, and Translator::trExamples().
startFile()
void LatexGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id, int hierarchyLevel) override virtual
Implements OutputGenIntf.
Definition at line 700 of file latexgen.cpp.
{
#if 0
  setEncoding(Config_getString(LATEX_OUTPUT_ENCODING));
#endif
  QCString fileName=name;
  m_hierarchyLevel = hierarchyLevel;
  m_relPath = relativePathToRoot(fileName);
  if (!fileName.endsWith(".tex") && !fileName.endsWith(".sty")) fileName+=".tex";
  startPlainFile(fileName);
  m_codeGen->setRelativePath(m_relPath);
  m_codeGen->setSourceFileName(stripPath(fileName));
}
References Config_getString, OutputGenerator::fileName(), m_codeGen, m_hierarchyLevel, m_relPath, relativePathToRoot(), startPlainFile(), and stripPath().
startGroupCollaboration()
void LatexGenerator::startGroupCollaboration () override virtual
Implements OutputGenIntf.
Definition at line 2035 of file latexgen.cpp.
{
}
startGroupHeader()
void LatexGenerator::startGroupHeader (int extraIndentLevel) override virtual
Implements OutputGenIntf.
Definition at line 1508 of file latexgen.cpp.
{
  if (Config_getBool(COMPACT_LATEX))
  {
    extraIndentLevel++;
  }
  if (extraIndentLevel>=3)
  {
    m_t << "\\doxysubparagraph*{";
  }
  else if (extraIndentLevel==2)
  {
    m_t << "\\doxyparagraph{";
  }
  else
  {
    extraIndentLevel += m_hierarchyLevel + 1;
    m_t << "\\doxy" << QCString("sub").repeat(extraIndentLevel) << "section{";
  }
  m_disableLinks=TRUE;
}
References Config_getBool, m_disableLinks, m_hierarchyLevel, OutputGenerator::m_t, and TRUE.
startHeaderSection()
void LatexGenerator::startHeaderSection () inline override virtual
Implements OutputGenIntf.
Definition at line 166 of file latexgen.h.
{}
startInclDepGraph()
void LatexGenerator::startInclDepGraph () override virtual
Implements OutputGenIntf.
Definition at line 2026 of file latexgen.cpp.
{
}
startIndent()
void LatexGenerator::startIndent () inline override virtual
Implements OutputGenIntf.
Definition at line 230 of file latexgen.h.
{}
startIndexItem()
void LatexGenerator::startIndexItem (const QCString & ref, const QCString & file) override virtual
Implements OutputGenIntf.
Definition at line 1317 of file latexgen.cpp.
{
  m_t << "\\item ";
  if (ref.isEmpty() && !fn.isEmpty())
  {
    m_t << "\\contentsline{section}{";
  }
}
References QCString::isEmpty(), and OutputGenerator::m_t.
startIndexKey()
void LatexGenerator::startIndexKey () override virtual
Implements OutputGenIntf.
Definition at line 1343 of file latexgen.cpp.
{
  m_t << "\\item\\contentsline{section}{";
}
References OutputGenerator::m_t.
startIndexList()
void LatexGenerator::startIndexList () inline override virtual
Implements OutputGenIntf.
Definition at line 141 of file latexgen.h.
{ m_t << "\\begin{DoxyCompactList}\n"; }
References OutputGenerator::m_t.
startIndexListItem()
void LatexGenerator::startIndexListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 139 of file latexgen.h.
{}
startIndexSection()
void LatexGenerator::startIndexSection (IndexSection is) override virtual
Implements OutputGenIntf.
Definition at line 905 of file latexgen.cpp.
{
  bool compactLatex = Config_getBool(COMPACT_LATEX);
  switch (is)
  {
    case IndexSection::isTitlePageStart:
      m_t << substituteLatexKeywords(g_header,convertToLaTeX(Config_getString(PROJECT_NAME),m_codeGen->insideTabbing()));
      break;
    case IndexSection::isTitlePageAuthor:
      break;
    case IndexSection::isMainPage:
      break;
    case IndexSection::isModuleIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Module Index}\n"
      break;
    case IndexSection::isTopicIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Topic Index}\n"
      break;
    case IndexSection::isDirIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Directory Index}\n"
      break;
    case IndexSection::isNamespaceIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Namespace Index}\n"
      break;
    case IndexSection::isConceptIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Concept Index}\n"
      break;
    case IndexSection::isClassHierarchyIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Hierarchical Index}\n"
      break;
    case IndexSection::isCompoundIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Annotated Compound Index}\n"
      break;
    case IndexSection::isFileIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Annotated File Index}\n"
      break;
    case IndexSection::isPageIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Annotated Page Index}\n"
      break;
    case IndexSection::isTopicDocumentation:
      {
        for (const auto &gd : *Doxygen::groupLinkedMap)
        {
          if (!gd->isReference())
          {
            if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
            m_t << "{"; //Topic Documentation}\n";
            break;
          }
        }
      }
      break;
    case IndexSection::isModuleDocumentation:
      {
        for (const auto &mod : ModuleManager::instance().modules())
        {
          if (!mod->isReference() && mod->isPrimaryInterface())
          {
            if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
            m_t << "{"; //Topic Documentation}\n";
            break;
          }
        }
      }
      break;
    case IndexSection::isDirDocumentation:
      {
        for (const auto &dd : *Doxygen::dirLinkedMap)
        {
          if (dd->isLinkableInProject())
          {
            if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
            m_t << "{"; //Dir Documentation}\n";
            break;
          }
        }
      }
      break;
    case IndexSection::isNamespaceDocumentation:
      {
        for (const auto &nd : *Doxygen::namespaceLinkedMap)
        {
          if (nd->isLinkableInProject() && !nd->isAlias())
          {
            if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
            m_t << "{"; // Namespace Documentation}\n":
            break;
          }
        }
      }
      break;
    case IndexSection::isConceptDocumentation:
      {
        for (const auto &cd : *Doxygen::conceptLinkedMap)
        {
          if (cd->isLinkableInProject() && !cd->isAlias())
          {
            if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
            m_t << "{"; // Concept Documentation}\n":
            break;
          }
        }
      }
      break;
    case IndexSection::isClassDocumentation:
      {
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->isLinkableInProject() &&
              cd->templateMaster()==nullptr &&
              !cd->isEmbeddedInOuterScope() &&
              !cd->isAlias()
             )
          {
            if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
            m_t << "{"; //Compound Documentation}\n";
            break;
          }
        }
      }
      break;
    case IndexSection::isFileDocumentation:
      {
        bool isFirst=TRUE;
        for (const auto &fn : *Doxygen::inputNameLinkedMap)
        {
          for (const auto &fd : *fn)
          {
            if (fd->isLinkableInProject() || fd->generateSourceFile())
            {
              if (isFirst)
              {
                if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
                m_t << "{"; //File Documentation}\n";
                isFirst=FALSE;
                break;
              }
            }
          }
        }
      }
      break;
    case IndexSection::isExampleDocumentation:
      {
        if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
        m_t << "{"; //Example Documentation}\n";
      }
      break;
    case IndexSection::isPageDocumentation:
      break;
    case IndexSection::isPageDocumentation2:
      break;
    case IndexSection::isEndIndex:
      break;
  }
}
References Doxygen::classLinkedMap, Doxygen::conceptLinkedMap, Config_getBool, Config_getString, convertToLaTeX(), Doxygen::dirLinkedMap, FALSE, g_header, Doxygen::groupLinkedMap, Doxygen::inputNameLinkedMap, ModuleManager::instance(), isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, isTopicDocumentation, isTopicIndex, m_codeGen, OutputGenerator::m_t, Doxygen::namespaceLinkedMap, substituteLatexKeywords(), and TRUE.
startIndexValue()
void LatexGenerator::startIndexValue (bool hasBrief) override virtual
Implements OutputGenIntf.
Definition at line 1352 of file latexgen.cpp.
{
  m_t << " ";
  if (hasBrief) m_t << "\\\\*";
}
References OutputGenerator::m_t.
startInlineHeader()
void LatexGenerator::startInlineHeader () override virtual
Implements OutputGenIntf.
Definition at line 2187 of file latexgen.cpp.
{
  if (Config_getBool(COMPACT_LATEX))
  {
    m_t << "\\doxyparagraph*{";
  }
  else
  {
    m_t << "\\doxy" << QCString("sub").repeat(m_hierarchyLevel + 1) << "section*{";
  }
}
References Config_getBool, m_hierarchyLevel, and OutputGenerator::m_t.
startInlineMemberDoc()
void LatexGenerator::startInlineMemberDoc () override virtual
Implements OutputGenIntf.
Definition at line 2269 of file latexgen.cpp.
{
}
startInlineMemberName()
void LatexGenerator::startInlineMemberName () override virtual
Implements OutputGenIntf.
Definition at line 2258 of file latexgen.cpp.
{
  m_codeGen->setInsideTabbing(true); // to prevent \+ from causing unwanted breaks
}
References m_codeGen.
startInlineMemberType()
void LatexGenerator::startInlineMemberType () override virtual
Implements OutputGenIntf.
Definition at line 2247 of file latexgen.cpp.
{
  m_codeGen->setInsideTabbing(true); // to prevent \+ from causing unwanted breaks
}
References m_codeGen.
startItemList()
void LatexGenerator::startItemList () inline override virtual
Implements OutputGenIntf.
Definition at line 147 of file latexgen.h.
{ m_t << "\\begin{DoxyCompactItemize}\n"; }
References OutputGenerator::m_t.
startItemListItem()
void LatexGenerator::startItemListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 161 of file latexgen.h.
{ m_t << "\\item \n"; }
References OutputGenerator::m_t.
startLabels()
void LatexGenerator::startLabels () override virtual
Implements OutputGenIntf.
Definition at line 2278 of file latexgen.cpp.
{
  m_t << "\\hspace{0.3cm}";
}
References OutputGenerator::m_t.
startMemberDeclaration()
void LatexGenerator::startMemberDeclaration () inline override virtual
Implements OutputGenIntf.
Definition at line 219 of file latexgen.h.
{}
startMemberDescription()
void LatexGenerator::startMemberDescription (const QCString & , const QCString & , bool) override virtual
Implements OutputGenIntf.
Definition at line 1846 of file latexgen.cpp.
{
  if (!m_codeGen->insideTabbing())
  {
    m_t << "\\begin{DoxyCompactList}\\small\\item\\em ";
  }
  else
  {
    for (int i=0;i<m_indent+2;i++) m_t << "\\>";
    m_t << "{\\em ";
  }
}
References m_codeGen, m_indent, and OutputGenerator::m_t.
startMemberDoc()
void LatexGenerator::startMemberDoc (const QCString & clname, const QCString & memname, const QCString & , const QCString & title, int memCount, int memTotal, bool showInline) override virtual
Implements OutputGenIntf.
Definition at line 1555 of file latexgen.cpp.
{
  if (!memname.isEmpty() && memname[0]!='@')
  {
    m_t << "\\index{";
    if (!clname.isEmpty())
    {
      m_t << latexEscapeLabelName(clname);
      m_t << "@{";
      m_t << latexEscapeIndexChars(clname);
      m_t << "}!";
    }
    m_t << latexEscapeLabelName(memname);
    m_t << "@{";
    m_t << latexEscapeIndexChars(memname);
    m_t << "}}\n";
    m_t << "\\index{";
    m_t << latexEscapeLabelName(memname);
    m_t << "@{";
    m_t << latexEscapeIndexChars(memname);
    m_t << "}";
    if (!clname.isEmpty())
    {
      m_t << "!";
      m_t << latexEscapeLabelName(clname);
      m_t << "@{";
      m_t << latexEscapeIndexChars(clname);
      m_t << "}";
    }
    m_t << "}\n";
  }
  bool compactLatex = Config_getBool(COMPACT_LATEX);
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  if (showInline)
  {
    m_t << "\\doxysubparagraph";
  }
  else if (compactLatex)
  {
    m_t << "\\doxyparagraph";
  }
  else
  {
    m_t << "\\doxy" << QCString("sub").repeat(m_hierarchyLevel + 2) << "section";
  }
  m_t << "{";
  if (pdfHyperlinks)
  {
    m_t << "\\texorpdfstring{";
  }
  m_t << latexEscapeIndexChars(title);
  if (pdfHyperlinks)
  {
    m_t << "}{" << latexEscapePDFString(title) << "}";
  }
  if (memTotal>1)
  {
    m_t << "\\hspace{0.1cm}{\\footnotesize\\ttfamily [" << memCount << "/" << memTotal << "]}";
  }
  m_t << "}";
  m_t << "\n{\\footnotesize\\ttfamily ";
  //m_disableLinks=TRUE;
}
References Config_getBool, QCString::isEmpty(), latexEscapeIndexChars(), latexEscapeLabelName(), latexEscapePDFString(), m_hierarchyLevel, and OutputGenerator::m_t.
startMemberDocList()
void LatexGenerator::startMemberDocList () inline override virtual
Implements OutputGenIntf.
Definition at line 172 of file latexgen.h.
{}
startMemberDocName()
void LatexGenerator::startMemberDocName (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 277 of file latexgen.h.
{}
startMemberDocPrefixItem()
void LatexGenerator::startMemberDocPrefixItem () inline override virtual
Implements OutputGenIntf.
Definition at line 275 of file latexgen.h.
{}
startMemberDocSimple()
void LatexGenerator::startMemberDocSimple (bool isEnum) override virtual
Implements OutputGenIntf.
Definition at line 2216 of file latexgen.cpp.
{
  m_codeGen->incUsedTableLevel();
  if (isEnum)
  {
    m_t << "\\begin{DoxyEnumFields}{";
    docify(theTranslator->trEnumerationValues());
  }
  else
  {
    m_t << "\\begin{DoxyFields}{";
    docify(theTranslator->trCompoundMembers());
  }
  m_t << "}\n";
  m_insideTableEnv=true;
}
References docify(), m_codeGen, m_insideTableEnv, OutputGenerator::m_t, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberGroup()
void LatexGenerator::startMemberGroup () override virtual
Implements OutputGenIntf.
Definition at line 2006 of file latexgen.cpp.
{
}
startMemberGroupDocs()
void LatexGenerator::startMemberGroupDocs () override virtual
Implements OutputGenIntf.
Definition at line 1996 of file latexgen.cpp.
{
  m_t << "{\\em ";
}
References OutputGenerator::m_t.
startMemberGroupHeader()
void LatexGenerator::startMemberGroupHeader (bool hasHeader) override virtual
Implements OutputGenIntf.
Definition at line 1974 of file latexgen.cpp.
{
  if (hasHeader) m_t << "\\begin{Indent}";
  m_t << "\\textbf{ ";
  // changed back to rev 756 due to bug 660501
  //if (Config_getBool(COMPACT_LATEX))
  //{
  //  m_t << "\\doxysubparagraph*{";
  //}
  //else
  //{
  //  m_t << "\\doxyparagraph*{";
  //}
}
References OutputGenerator::m_t.
startMemberHeader()
void LatexGenerator::startMemberHeader (const QCString & , int) override virtual
Implements OutputGenIntf.
Definition at line 1537 of file latexgen.cpp.
{
  int l = m_hierarchyLevel + 1;
  if (Config_getBool(COMPACT_LATEX))
  {
    ++l;
  }
  m_t << "\\doxysub" << QCString("sub").repeat(l) << "section*{";
  m_disableLinks=TRUE;
}
References Config_getBool, m_disableLinks, m_hierarchyLevel, OutputGenerator::m_t, and TRUE.
startMemberItem()
void LatexGenerator::startMemberItem (const QCString & , MemberItemType type, const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 1826 of file latexgen.cpp.
{
  //printf("LatexGenerator::startMemberItem(%d)\n",annType);
  if (!m_codeGen->insideTabbing())
  {
    m_t << "\\item \n";
    m_templateMemberItem = (type == MemberItemType::Templated);
  }
}
References m_codeGen, OutputGenerator::m_t, m_templateMemberItem, OutputGenerator::Templated, and type().
startMemberList()
void LatexGenerator::startMemberList () override virtual
Implements OutputGenIntf.
Definition at line 1956 of file latexgen.cpp.
{
  if (!m_codeGen->insideTabbing())
  {
    m_t << "\\begin{DoxyCompactItemize}\n";
  }
}
References m_codeGen, and OutputGenerator::m_t.
startMemberSections()
void LatexGenerator::startMemberSections () inline override virtual
Implements OutputGenIntf.
Definition at line 164 of file latexgen.h.
{}
startMemberSubtitle()
void LatexGenerator::startMemberSubtitle () inline override virtual
Implements OutputGenIntf.
Definition at line 170 of file latexgen.h.
{}
startMemberTemplateParams()
void LatexGenerator::startMemberTemplateParams () override virtual
Implements OutputGenIntf.
Definition at line 1810 of file latexgen.cpp.
{
  if (m_templateMemberItem)
  {
    m_t << "{\\footnotesize ";
  }
}
References OutputGenerator::m_t, and m_templateMemberItem.
startPageDoc()
void LatexGenerator::startPageDoc (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 125 of file latexgen.h.
{}
startPageRef()
void LatexGenerator::startPageRef () override virtual
Implements OutputGenIntf.
Definition at line 1442 of file latexgen.cpp.
{
  m_t << " \\doxyref{}{";
}
References OutputGenerator::m_t.
startParagraph()
void LatexGenerator::startParagraph (const QCString & classDef) override virtual
Implements OutputGenIntf.
Definition at line 1302 of file latexgen.cpp.
{
  m_t << "\n" << "\n";
}
References OutputGenerator::m_t.
startParameterDefVal()
void LatexGenerator::startParameterDefVal (const char * s) inline override virtual
Implements OutputGenIntf.
Definition at line 285 of file latexgen.h.
{ docify(s); startTypewriter(); }
References docify(), and startTypewriter().
startParameterExtra()
void LatexGenerator::startParameterExtra () override virtual
Implements OutputGenIntf.
Definition at line 2106 of file latexgen.cpp.
{
  m_t << "{";
}
References OutputGenerator::m_t.
startParameterList()
void LatexGenerator::startParameterList (bool openBracket) override virtual
Implements OutputGenIntf.
Definition at line 2074 of file latexgen.cpp.
{
  /* start of ParameterType ParameterName list */
  if (openBracket) m_t << "(";
  m_t << "\\begin{DoxyParamCaption}";
}
References OutputGenerator::m_t.
startParameterName()
void LatexGenerator::startParameterName (bool) override virtual
Implements OutputGenIntf.
Definition at line 2096 of file latexgen.cpp.
{
  m_t << "{";
}
References OutputGenerator::m_t.
startParameterType()
void LatexGenerator::startParameterType (bool first, const QCString & key) override virtual
Implements OutputGenIntf.
Definition at line 2085 of file latexgen.cpp.
{
  m_t << "\\item[{";
  if (!first && !key.isEmpty()) docify(key);
}
References docify(), QCString::isEmpty(), and OutputGenerator::m_t.
startPlainFile()
void LatexGenerator::startPlainFile (const QCString & name) inline override virtual
Implements OutputGenIntf.
Definition at line 314 of file latexgen.h.
{ OutputGenerator::startPlainFile(name); }
References OutputGenerator::startPlainFile().
Referenced by startFile(), and writeStyleInfo().
startProjectNumber()
void LatexGenerator::startProjectNumber () override virtual
Implements OutputGenIntf.
Definition at line 725 of file latexgen.cpp.
{
  m_t << "\\\\[1ex]\\large ";
}
References OutputGenerator::m_t.
startQuickIndices()
void LatexGenerator::startQuickIndices () inline override virtual
Implements OutputGenIntf.
Definition at line 237 of file latexgen.h.
{}
startSection()
void LatexGenerator::startSection (const QCString & lab, const QCString & , SectionType type) override virtual
Implements OutputGenIntf.
Definition at line 1710 of file latexgen.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  bool usePDFLatex   = Config_getBool(USE_PDFLATEX);
  if (usePDFLatex && pdfHyperlinks)
  {
    m_t << "\\hypertarget{" << stripPath(lab) << "}{}";
  }
  m_t << "\\";
  if (Config_getBool(COMPACT_LATEX))
  {
    switch(type.level())
    {
      case SectionType::Page:             m_t << "doxysubsection"; break;
      case SectionType::Section:          m_t << "doxysubsubsection"; break;
      case SectionType::Subsection:       m_t << "doxysubsubsubsection"; break;
      case SectionType::Subsubsection:    m_t << "doxysubsubsubsubsection"; break;
      case SectionType::Paragraph:        m_t << "doxysubsubsubsubsubsection"; break;
      case SectionType::Subparagraph:     m_t << "doxysubsubsubsubsubsubsection"; break;
      case SectionType::Subsubparagraph:  m_t << "doxysubsubsubsubsubsubsection"; break;
      default: ASSERT(0); break;
    }
    m_t << "{";
  }
  else
  {
    switch(type.level())
    {
      case SectionType::Page:             m_t << "doxysection"; break;
      case SectionType::Section:          m_t << "doxysubsection"; break;
      case SectionType::Subsection:       m_t << "doxysubsubsection"; break;
      case SectionType::Subsubsection:    m_t << "doxysubsubsubsection"; break;
      case SectionType::Paragraph:        m_t << "doxysubsubsubsubsection"; break;
      case SectionType::Subparagraph:     m_t << "doxysubsubsubsubsubsection"; break;
      case SectionType::Subsubparagraph:  m_t << "doxysubsubsubsubsubsubsection"; break;
      default: ASSERT(0); break;
    }
    m_t << "{";
  }
}
References ASSERT, Config_getBool, OutputGenerator::m_t, SectionType::Page, SectionType::Paragraph, SectionType::Section, stripPath(), SectionType::Subparagraph, SectionType::Subsection, SectionType::Subsubparagraph, SectionType::Subsubsection, and type().
startSmall()
void LatexGenerator::startSmall () inline override virtual
Implements OutputGenIntf.
Definition at line 215 of file latexgen.h.
{ m_t << "\\footnotesize "; }
References OutputGenerator::m_t.
startTextBlock()
void LatexGenerator::startTextBlock (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 272 of file latexgen.h.
{}
startTextLink()
void LatexGenerator::startTextLink (const QCString & f, const QCString & anchor) override virtual
Implements OutputGenIntf.
Definition at line 1372 of file latexgen.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  if (!m_disableLinks && pdfHyperlinks)
  {
    m_t << "\\mbox{\\hyperlink{";
    if (!f.isEmpty()) m_t << stripPath(f);
    if (!anchor.isEmpty()) m_t << "_" << anchor;
    m_t << "}{";
  }
  else
  {
    m_t << "\\textbf{ ";
  }
}
References Config_getBool, QCString::isEmpty(), m_disableLinks, OutputGenerator::m_t, and stripPath().
startTitle()
void LatexGenerator::startTitle () private
Definition at line 1496 of file latexgen.cpp.
{
  if (Config_getBool(COMPACT_LATEX))
  {
    m_t << "\\doxysubsection{";
  }
  else
  {
    m_t << "\\doxysection{";
  }
}
References Config_getBool, and OutputGenerator::m_t.
startTitleHead()
void LatexGenerator::startTitleHead (const QCString & fileName) override virtual
Implements OutputGenIntf.
Definition at line 1456 of file latexgen.cpp.
{
  int hierarchyLevel = m_hierarchyLevel;
  if (Config_getBool(COMPACT_LATEX))
  {
    ++hierarchyLevel;
  }
  if (hierarchyLevel < 0)
    m_t << "\\chapter{";
  else
    m_t << "\\doxy" << QCString("sub").repeat(hierarchyLevel) << "section{";
}
References Config_getBool, OutputGenerator::fileName(), m_hierarchyLevel, and OutputGenerator::m_t.
startTypewriter()
void LatexGenerator::startTypewriter () inline override virtual
Implements OutputGenIntf.
Definition at line 157 of file latexgen.h.
{ m_t << "{\\ttfamily "; }
References OutputGenerator::m_t.
Referenced by startParameterDefVal().
type()
OutputType LatexGenerator::type () const inline override virtual
Implements OutputGenIntf.
Definition at line 114 of file latexgen.h.
{ return OutputType::Latex; }
References Latex.
Referenced by startMemberItem(), and startSection().
writeAnchor()
void LatexGenerator::writeAnchor (const QCString & fileName, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1663 of file latexgen.cpp.
{
  //printf("LatexGenerator::writeAnchor(%s,%s)\n",fName,name);
  m_t << "\\label{" << stripPath(name) << "}\n";
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  bool usePDFLatex   = Config_getBool(USE_PDFLATEX);
  if (usePDFLatex && pdfHyperlinks)
  {
    if (!fName.isEmpty())
    {
      m_t << "\\Hypertarget{" << stripPath(fName) << "_" << stripPath(name) << "}\n";
    }
    else
    {
      m_t << "\\Hypertarget{" << stripPath(name) << "}\n";
    }
  }
}
References Config_getBool, QCString::isEmpty(), OutputGenerator::m_t, and stripPath().
writeChar()
void LatexGenerator::writeChar (char c) override virtual
Implements OutputGenIntf.
Definition at line 1768 of file latexgen.cpp.
{
  char cs[2];
  cs[0]=c;
  cs[1]=0;
  docify(cs);
}
References docify().
writeDoc()
void LatexGenerator::writeDoc (const IDocNodeAST * node, const Definition * ctx, const MemberDef * , int id) override virtual
Implements OutputGenIntf.
Definition at line 2134 of file latexgen.cpp.
{
  const DocNodeAST *astImpl = dynamic_cast<const DocNodeAST*>(ast);
  if (astImpl)
  {
    LatexDocVisitor visitor(m_t,*m_codeList,*m_codeGen,
                            ctx?ctx->getDefFileExtension():QCString(""),
                            m_hierarchyLevel);
    std::visit(visitor,astImpl->root);
  }
}
References Definition::getDefFileExtension(), m_codeGen, m_codeList, m_hierarchyLevel, OutputGenerator::m_t, and DocNodeAST::root.
writeFooter()
void LatexGenerator::writeFooter (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 123 of file latexgen.h.
{}
writeFooterFile()
void LatexGenerator::writeFooterFile (TextStream & t) static
Definition at line 688 of file latexgen.cpp.
{
  t << "% Latex footer for doxygen " << getDoxygenVersion() << "\n";
  t << ResourceMgr::instance().getAsString("footer.tex");
}
References ResourceMgr::getAsString(), and ResourceMgr::instance().
Referenced by readConfiguration().
writeGraphicalHierarchy()
void LatexGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) inline override virtual
Implements OutputGenIntf.
Definition at line 270 of file latexgen.h.
{}
writeHeaderFile()
void LatexGenerator::writeHeaderFile (TextStream & t) static
Definition at line 682 of file latexgen.cpp.
{
  t << "% Latex header for doxygen " << getDoxygenVersion() << "\n";
  t << ResourceMgr::instance().getAsString("header.tex");
}
References ResourceMgr::getAsString(), and ResourceMgr::instance().
Referenced by readConfiguration().
writeInheritedSectionTitle()
void LatexGenerator::writeInheritedSectionTitle (const QCString & , const QCString & ref, const QCString & file, const QCString & anchor, const QCString & title, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 2293 of file latexgen.cpp.
{
  if (Config_getBool(COMPACT_LATEX))
  {
    m_t << "\\doxyparagraph*{";
  }
  else
  {
    m_t << "\\doxy" << QCString("sub").repeat(m_hierarchyLevel + 1) << "section*{";
  }
  m_t << theTranslator->trInheritedFrom(convertToLaTeX(title,m_codeGen->insideTabbing()),
                                        objectLinkToString(ref, file, anchor, name, m_codeGen->insideTabbing(), m_disableLinks));
  m_t << "}\n";
}
References Config_getBool, convertToLaTeX(), m_codeGen, m_disableLinks, m_hierarchyLevel, OutputGenerator::m_t, objectLinkToString(), theTranslator, and Translator::trInheritedFrom().
writeLabel()
void LatexGenerator::writeLabel (const QCString & l, bool isLast) override virtual
Implements OutputGenIntf.
Definition at line 2283 of file latexgen.cpp.
{
  m_t << "{\\ttfamily [" << l << "]}";
  if (!isLast) m_t << ", ";
}
References OutputGenerator::m_t.
writeLatexSpacing()
void LatexGenerator::writeLatexSpacing () inline override virtual
Implements OutputGenIntf.
Definition at line 210 of file latexgen.h.
{ m_t << "\\hspace{0.3cm}"; }
References OutputGenerator::m_t.
writeLocalToc()
void LatexGenerator::writeLocalToc (const SectionRefs & sr, const LocalToc & lt) override virtual
Implements OutputGenIntf.
Definition at line 2311 of file latexgen.cpp.
{
  if (localToc.isLatexEnabled())
  {
    int maxLevel = localToc.latexLevel() + m_hierarchyLevel;
    m_t << "\\etocsetnexttocdepth{" << maxLevel << "}\n";
    m_t << "\\localtableofcontents\n";
  }
}
References LocalToc::isLatexEnabled(), LocalToc::latexLevel(), m_hierarchyLevel, and OutputGenerator::m_t.
writeLogo()
void LatexGenerator::writeLogo () inline override virtual
Implements OutputGenIntf.
Definition at line 241 of file latexgen.h.
{}
writeNavigationPath()
void LatexGenerator::writeNavigationPath (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 240 of file latexgen.h.
{}
writeNonBreakableSpace()
void LatexGenerator::writeNonBreakableSpace (int) override virtual
Implements OutputGenIntf.
Definition at line 1873 of file latexgen.cpp.
{
  //printf("writeNonBreakableSpace()\n");
  if (m_codeGen->insideTabbing())
  {
    m_t << "\\>";
  }
  else
  {
    m_t << "~";
  }
}
References m_codeGen, and OutputGenerator::m_t.
writeObjectLink()
void LatexGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1436 of file latexgen.cpp.
{
  m_t << objectLinkToString(ref,f,anchor,text,m_codeGen->insideTabbing(),m_disableLinks);
}
References m_codeGen, m_disableLinks, OutputGenerator::m_t, and objectLinkToString().
writePageLink()
void LatexGenerator::writePageLink (const QCString & name, bool) override virtual
Implements OutputGenIntf.
Definition at line 1268 of file latexgen.cpp.
{
  //bool &compactLatex = Config_getBool(COMPACT_LATEX);
  // next is remove for bug615957
  //if (compactLatex || first) m_t << "\\input" ; else m_t << "\\include";
  m_t << "\\input" ;
  m_t << "{" << name << "}\n";
}
References OutputGenerator::m_t.
Referenced by endIndexSection().
writeQuickLinks()
void LatexGenerator::writeQuickLinks (HighlightedItem , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 242 of file latexgen.h.
{}
writeRuler()
void LatexGenerator::writeRuler () inline override virtual
Implements OutputGenIntf.
Definition at line 197 of file latexgen.h.
{ m_t << "\n\n"; }
References OutputGenerator::m_t.
writeSearchInfo()
void LatexGenerator::writeSearchInfo () inline override virtual
Implements OutputGenIntf.
Definition at line 122 of file latexgen.h.
{}
writeSplitBar()
void LatexGenerator::writeSplitBar (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 239 of file latexgen.h.
{}
writeStartAnnoItem()
void LatexGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1334 of file latexgen.cpp.
{
  m_t << "\\item\\contentsline{section}\\textbf{ ";
  if (!path.isEmpty()) docify(path);
  docify(name);
  m_t << "} ";
}
References docify(), QCString::isEmpty(), and OutputGenerator::m_t.
writeString()
void LatexGenerator::writeString (const QCString & text) override virtual
Implements OutputGenIntf.
Definition at line 1312 of file latexgen.cpp.
{
  m_t << text;
}
References OutputGenerator::m_t.
writeStyleInfo()
void LatexGenerator::writeStyleInfo (int part) override virtual
an extension of the etoc package is required that is only available in the newer version. Providing the updated version to be used with older versions of LaTeX
Implements OutputGenIntf.
Definition at line 1277 of file latexgen.cpp.
{
  if (part > 0)
    return;
  startPlainFile("doxygen.sty");
  writeDefaultStyleSheet(m_t);
  endPlainFile();
  // workaround for the problem caused by change in LaTeX in version 2019
  // in the unmaintained tabu package
  startPlainFile("tabu_doxygen.sty");
  m_t << ResourceMgr::instance().getAsString("tabu_doxygen.sty");
  endPlainFile();
  startPlainFile("longtable_doxygen.sty");
  m_t << ResourceMgr::instance().getAsString("longtable_doxygen.sty");
  endPlainFile();
  /// an extension of the etoc package is required that is only available in the
  /// newer version. Providing the updated version to be used with older versions
  /// of LaTeX
  startPlainFile("etoc_doxygen.sty");
  m_t << ResourceMgr::instance().getAsString("etoc_doxygen.sty");
  endPlainFile();
}
References endPlainFile(), ResourceMgr::getAsString(), ResourceMgr::instance(), OutputGenerator::m_t, startPlainFile(), and writeDefaultStyleSheet().
writeStyleSheetFile()
void LatexGenerator::writeStyleSheetFile (TextStream & t) static
Definition at line 694 of file latexgen.cpp.
{
  t << "% stylesheet for doxygen " << getDoxygenVersion() << "\n";
  writeDefaultStyleSheet(t);
}
References writeDefaultStyleSheet().
Referenced by readConfiguration().
writeSummaryLink()
void LatexGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 243 of file latexgen.h.
{}
writeSynopsis()
void LatexGenerator::writeSynopsis () inline override virtual
Implements OutputGenIntf.
Definition at line 232 of file latexgen.h.
{}
Member Data Documentation
m_codeGen
LatexCodeGenerator* LatexGenerator::m_codeGen private
Definition at line 328 of file latexgen.h.
Referenced by addCodeGen(), docify(), endAnonTypeScope(), endDescTable(), endFile(), endIndexSection(), endInlineMemberName(), endInlineMemberType(), endMemberDescription(), endMemberDocSimple(), endMemberItem(), endMemberList(), LatexGenerator(), LatexGenerator(), lineBreak(), operator=(), startAnonTypeScope(), startDescTable(), startFile(), startIndexSection(), startInlineMemberName(), startInlineMemberType(), startMemberDescription(), startMemberDocSimple(), startMemberItem(), startMemberList(), writeDoc(), writeInheritedSectionTitle(), writeNonBreakableSpace(), and writeObjectLink().
m_codeList
std::unique_ptr<OutputCodeList> LatexGenerator::m_codeList private
Definition at line 327 of file latexgen.h.
Referenced by LatexGenerator(), LatexGenerator(), operator=(), and writeDoc().
m_disableLinks
bool LatexGenerator::m_disableLinks = false private
Definition at line 323 of file latexgen.h.
Referenced by endGroupHeader(), endMemberDoc(), endMemberHeader(), endTextLink(), LatexGenerator(), operator=(), startGroupHeader(), startMemberHeader(), startTextLink(), writeInheritedSectionTitle(), and writeObjectLink().
m_firstDescItem
bool LatexGenerator::m_firstDescItem = true private
Definition at line 322 of file latexgen.h.
Referenced by LatexGenerator(), and operator=().
m_hierarchyLevel
int LatexGenerator::m_hierarchyLevel = 0 private
Definition at line 330 of file latexgen.h.
Referenced by LatexGenerator(), operator=(), startFile(), startGroupHeader(), startInlineHeader(), startMemberDoc(), startMemberHeader(), startTitleHead(), writeDoc(), writeInheritedSectionTitle(), and writeLocalToc().
m_indent
int LatexGenerator::m_indent = 0 private
Definition at line 325 of file latexgen.h.
Referenced by endAnonTypeScope(), LatexGenerator(), operator=(), startAnonTypeScope(), and startMemberDescription().
m_insideTableEnv
bool LatexGenerator::m_insideTableEnv = false private
Definition at line 329 of file latexgen.h.
Referenced by addLabel(), endMemberDocSimple(), startDoxyAnchor(), and startMemberDocSimple().
m_relPath
QCString LatexGenerator::m_relPath private
Definition at line 324 of file latexgen.h.
Referenced by endCallGraph(), endDirDepGraph(), endDotGraph(), endGroupCollaboration(), endInclDepGraph(), LatexGenerator(), operator=(), and startFile().
m_templateMemberItem
bool LatexGenerator::m_templateMemberItem = false private
Definition at line 326 of file latexgen.h.
Referenced by endMemberItem(), endMemberTemplateParams(), LatexGenerator(), operator=(), startMemberItem(), and startMemberTemplateParams().
The documentation for this class was generated from the following files:
src/latexgen.h
src/latexgen.cpp