Doxygen: Crawlmap Class Reference
Crawlmap Class Reference
#include <src/sitemap.h>
Classes
class Private
Public Member Functions
Crawlmap ()
~Crawlmap ()
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex, bool addToNavIndex, const Definition *def)
void addIndexItem (const Definition *context, const MemberDef *md, const QCString &sectionAnchor, const QCString &title)
void addIndexFile (const QCString &name)
void addImageFile (const QCString &name)
void addStyleSheetFile (const QCString &name)
Public Member Functions inherited from IndexIntf
Static Public Attributes
static const QCString crawlFileName = "doxygen_crawl"
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 54 of file sitemap.h.
Constructor & Destructor Documentation
Crawlmap()
Crawlmap::Crawlmap ()
Definition at line 92 of file sitemap.cpp.
: p(std::make_unique<Private>()) {}
References p.
Referenced by ~Crawlmap().
~Crawlmap()
Crawlmap::~Crawlmap () default
References Crawlmap().
Member Function Documentation
addContentsItem()
void Crawlmap::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex, bool addToNavIndex, const Definition * def) virtual
Implements IndexIntf.
Definition at line 140 of file sitemap.cpp.
{
  if (!file.isEmpty() && ref.isEmpty())      // made file optional param and
                                             // don't place links in crawl file imported
                                             // by tags
  {
    std::string link;
    if (file[0]=='!' || file[0]=='^') // special markers for user defined URLs
    {
      link+=&file[1];
    }
    else
    {
      QCString currFile = file;
      addHtmlExtensionIfMissing(currFile);
      QCString currAnc = anchor;
      link += currFile.data();
      if (!currAnc.isEmpty())
      {
        link += "#";
        link += currAnc.str();
      }
    }
    p->crawlLinks.push_back(link);
  }
}
References addHtmlExtensionIfMissing(), QCString::data(), QCString::isEmpty(), p, and QCString::str().
addImageFile()
void Crawlmap::addImageFile (const QCString & name) inline virtual
Implements IndexIntf.
Definition at line 72 of file sitemap.h.
{}
addIndexFile()
void Crawlmap::addIndexFile (const QCString & name) virtual
Implements IndexIntf.
Definition at line 133 of file sitemap.cpp.
{
  QCString fn = fileName;
  addHtmlExtensionIfMissing(fn);
  p->crawlLinks.push_back(fn.str());
}
References addHtmlExtensionIfMissing(), p, and QCString::str().
addIndexItem()
void Crawlmap::addIndexItem (const Definition * context, const MemberDef * md, const QCString & sectionAnchor, const QCString & title) virtual
Implements IndexIntf.
Definition at line 195 of file sitemap.cpp.
{
  if (context && md) // member
  {
    QCString cfname  = md->getOutputFileBase();
    QCString anchor  = !sectionAnchor.isEmpty() ? sectionAnchor : md->anchor();
    QCString ref     = makeRef(cfname, anchor);
    p->crawlLinks.push_back(ref.str());
  }
  else if (context) // container
  {
    QCString contRef = context->getOutputFileBase();
    QCString ref = makeRef(contRef,sectionAnchor);
    p->crawlLinks.push_back(ref.str());
  }
}
References Definition::anchor(), Definition::getOutputFileBase(), QCString::isEmpty(), makeRef(), p, and QCString::str().
addStyleSheetFile()
void Crawlmap::addStyleSheetFile (const QCString & name) inline virtual
Implements IndexIntf.
Definition at line 73 of file sitemap.h.
{}
decContentsDepth()
void Crawlmap::decContentsDepth () inline virtual
Implements IndexIntf.
Definition at line 64 of file sitemap.h.
{}
finalize()
void Crawlmap::finalize () virtual
Implements IndexIntf.
Definition at line 118 of file sitemap.cpp.
{
  std::sort(p->crawlLinks.begin(),p->crawlLinks.end());
  p->crawlLinks.erase(std::unique(p->crawlLinks.begin(),p->crawlLinks.end()),p->crawlLinks.end());
  for (auto &s : p->crawlLinks)
  {
    p->crawl << "<a href=\"" << s << "\"/>\n";
  }
  p->crawl << "</body>\n";
  p->crawl << "</html>\n";
  p->crawl.flush();
  p->crawlFile.close();
}
References p.
incContentsDepth()
void Crawlmap::incContentsDepth () inline virtual
Implements IndexIntf.
Definition at line 63 of file sitemap.h.
{}
initialize()
void Crawlmap::initialize () virtual
Implements IndexIntf.
Definition at line 95 of file sitemap.cpp.
{
  QCString fileName = Config_getString(HTML_OUTPUT) + "/" + crawlFileName;
  addHtmlExtensionIfMissing(fileName);
  p->crawlFile = Portable::openOutputStream(fileName);
  if (!p->crawlFile.is_open())
  {
    term("Could not open file %s for writing\n", qPrint(fileName));
  }
  p->crawl.setStream(&p->crawlFile);
  p->crawl << "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n";
  p->crawl << "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"" + theTranslator->trISOLang() + "\">\n";
  p->crawl << "<head>\n";
  p->crawl << "<title>Validator / crawler helper</title>\n";
  p->crawl << "<meta http-equiv=\"Content-Type\" content=\"text/xhtml;charset=UTF-8\"/>\n";
  p->crawl << "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=11\"/>\n";
  p->crawl << "<meta name=\"generator\" content=\"Doxygen " + getDoxygenVersion() + "\"/>\n";
  p->crawl << "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n";
  p->crawl << "</head>\n";
  p->crawl << "<body>\n";
}
References addHtmlExtensionIfMissing(), Config_getString, crawlFileName, Portable::openOutputStream(), p, qPrint(), term, theTranslator, and Translator::trISOLang().
Member Data Documentation
crawlFileName
const QCString Crawlmap::crawlFileName = "doxygen_crawl" inline static
Definition at line 75 of file sitemap.h.
Referenced by initialize(), and writeIndex().
p
std::unique_ptr<Private> Crawlmap::p private
Definition at line 79 of file sitemap.h.
Referenced by addContentsItem(), addIndexFile(), addIndexItem(), Crawlmap(), finalize(), and initialize().
The documentation for this class was generated from the following files:
src/sitemap.h
src/sitemap.cpp