Doxygen: DebugLex Class Reference
DebugLex Class Reference
#include <src/debug.h>
Public Member Functions
DebugLex (Debug::DebugMask mask, const char *lexName, const char *fileName)
~DebugLex ()
Static Public Member Functions
static void print (Debug::DebugMask mask, const char *state, const char *lexName, const char *fileName)
Private Attributes
Debug::DebugMask m_mask
QCString m_lexName
QCString m_fileName
Detailed Description
Definition at line 89 of file debug.h.
Constructor & Destructor Documentation
DebugLex()
DebugLex::DebugLex (Debug::DebugMask mask, const char * lexName, const char * fileName)
Definition at line 149 of file debug.cpp.
                                                                               : m_mask(mask), m_lexName(lexName), m_fileName(fileName)
{
  print(m_mask,"Entering",qPrint(m_lexName),qPrint(m_fileName));
}
References m_fileName, m_lexName, m_mask, print(), and qPrint().
~DebugLex()
DebugLex::~DebugLex ()
Definition at line 154 of file debug.cpp.
{
  print(m_mask,"Finished",qPrint(m_lexName),qPrint(m_fileName));
}
References m_fileName, m_lexName, m_mask, print(), and qPrint().
Member Function Documentation
print()
void DebugLex::print (Debug::DebugMask mask, const char * state, const char * lexName, const char * fileName) static
Definition at line 159 of file debug.cpp.
{
  if (fileName && *fileName)
  {
    if (Debug::isFlagSet(mask))
    {
      fprintf(stderr,"%s lexical analyzer: %s (for: %s)\n",state, lexName, fileName);
    }
  }
  else
  {
    if (Debug::isFlagSet(mask))
    {
      fprintf(stderr,"%s lexical analyzer: %s\n",state, lexName);
    }
  }
}
References Debug::isFlagSet().
Referenced by DebugLex(), LayoutDocManager::parse(), and ~DebugLex().
Member Data Documentation
m_fileName
QCString DebugLex::m_fileName private
Definition at line 100 of file debug.h.
Referenced by DebugLex(), and ~DebugLex().
m_lexName
QCString DebugLex::m_lexName private
Definition at line 99 of file debug.h.
Referenced by DebugLex(), and ~DebugLex().
m_mask
Debug::DebugMask DebugLex::m_mask private
Definition at line 98 of file debug.h.
Referenced by DebugLex(), and ~DebugLex().
The documentation for this class was generated from the following files:
src/debug.h
src/debug.cpp