Doxygen: src/msc.h File Reference
msc.h File Reference
Enumerations
enum class MscOutputFormat { BITMAP , EPS , SVG }
Functions
void writeMscGraphFromFile (const QCString &inFile, const QCString &outDir, const QCString &outFile, MscOutputFormat format, const QCString &srcFile, int srcLine)
QCString getMscImageMapFromFile (const QCString &inFile, const QCString &outDir, const QCString &relPath, const QCString &context, const QCString &srcFile, int srcLine)
void writeMscImageMapFromFile (TextStream &t, const QCString &inFile, const QCString &outDir, const QCString &relPath, const QCString &baseName, const QCString &context, MscOutputFormat format, const QCString &srcFile, int srcLine)
Enumeration Type Documentation
MscOutputFormat
enum class MscOutputFormat strong
Enumerator
BITMAP
EPS
SVG
Definition at line 22 of file msc.h.
{ BITMAP, EPS, SVG };
Function Documentation
getMscImageMapFromFile()
QCString getMscImageMapFromFile (const QCString & inFile, const QCString & outDir, const QCString & relPath, const QCString & context, const QCString & srcFile, int srcLine)
writeMscGraphFromFile()
void writeMscGraphFromFile (const QCString & inFile, const QCString & outDir, const QCString & outFile, MscOutputFormat format, const QCString & srcFile, int srcLine)
Definition at line 156 of file msc.cpp.
{
  QCString absOutFile = outDir;
  absOutFile+=Portable::pathSeparator();
  absOutFile+=outFile;
  mscgen_format_t msc_format = mscgen_format_png;
  QCString imgName = absOutFile;
  switch (format)
  {
    case MscOutputFormat::BITMAP:
      msc_format = mscgen_format_png;
      imgName+=".png";
      break;
    case MscOutputFormat::EPS:
      msc_format = mscgen_format_eps;
      imgName+=".eps";
      break;
    case MscOutputFormat::SVG:
      msc_format = mscgen_format_svg;
      imgName+=".svg";
      break;
    default:
      return;
  }
  if (!do_mscgen_generate(inFile,imgName,msc_format,srcFile,srcLine))
  {
    return;
  }
  if ( (format==MscOutputFormat::EPS) && (Config_getBool(USE_PDFLATEX)) )
  {
    QCString epstopdfArgs(maxCmdLine, QCString::ExplicitSize);
    epstopdfArgs.sprintf("\"%s.eps\" --outfile=\"%s.pdf\"",
                         qPrint(absOutFile),qPrint(absOutFile));
    if (Portable::system("epstopdf",epstopdfArgs)!=0)
    {
      err_full(srcFile,srcLine,"Problems running epstopdf when processing '%s.eps'. Check your TeX installation!",
          qPrint(absOutFile));
    }
    else
    {
      Dir().remove((absOutFile + ".eps").data());
    }
  }
  int i=std::max(imgName.findRev('/'),imgName.findRev('\\'));
  if (i!=-1) // strip path
  {
    imgName=imgName.right(imgName.length()-i-1);
  }
  Doxygen::indexList->addImageFile(imgName);
}
References BITMAP, Config_getBool, do_mscgen_generate(), EPS, err_full, QCString::ExplicitSize, QCString::findRev(), Doxygen::indexList, QCString::length(), maxCmdLine, Portable::pathSeparator(), qPrint(), Dir::remove(), QCString::right(), QCString::sprintf(), SVG, and Portable::system().
Referenced by DocbookDocVisitor::startMscFile(), LatexDocVisitor::startMscFile(), DocbookDocVisitor::writeMscFile(), HtmlDocVisitor::writeMscFile(), LatexDocVisitor::writeMscFile(), and RTFDocVisitor::writeMscFile().
writeMscImageMapFromFile()
void writeMscImageMapFromFile (TextStream & t, const QCString & inFile, const QCString & outDir, const QCString & relPath, const QCString & baseName, const QCString & context, MscOutputFormat format, const QCString & srcFile, int srcLine)
Definition at line 233 of file msc.cpp.
{
  QCString mapName = baseName+".map";
  t << "<img src=\"" << relPath << baseName << ".";
  switch (format)
  {
    case MscOutputFormat::BITMAP:
      t << "png";
      break;
    case MscOutputFormat::EPS:
      t << "eps";
      break;
    case MscOutputFormat::SVG:
      t << "svg";
      break;
    default:
      t << "unknown";
  }
  QCString imap = getMscImageMapFromFile(inFile,outDir,relPath,context,format==MscOutputFormat::SVG,srcFile,srcLine);
  if (!imap.isEmpty())
  {
    t << "\" alt=\""
      << baseName << "\" border=\"0\" usemap=\"#" << mapName << "\"/>\n";
    t << "<map name=\"" << mapName << "\" id=\"" << mapName << "\">" << imap << "</map>\n";
  }
  else
  {
    t << "\" alt=\"" << baseName << "\" border=\"0\"/>\n";
  }
}
References BITMAP, EPS, getMscImageMapFromFile(), QCString::isEmpty(), and SVG.
Referenced by HtmlDocVisitor::writeMscFile().