Doxygen: GrowBuf Class Reference
GrowBuf Class Reference
Class representing a string buffer optimized for growing.
#include <src/growbuf.h>
Public Member Functions
GrowBuf ()
GrowBuf (size_t initialSize)
~GrowBuf ()
GrowBuf (const GrowBuf &other)
GrowBuf & operator= (const GrowBuf &other)
GrowBuf (GrowBuf &&other)
GrowBuf & operator= (GrowBuf &&other)
void reserve (size_t size)
void clear ()
void addChar (char c)
void addStr (const QCString &s)
void addStr (const std::string &s)
void addStr (const char *s)
void addStr (const char *s, size_t n)
void addInt (const char *fmt, int value)
char * get ()
const char * get () const
size_t getPos () const
void setPos (size_t newPos)
const char & at (size_t i) const
bool empty () const
Private Attributes
char * m_str
size_t m_pos
size_t m_len
Detailed Description
Class representing a string buffer optimized for growing.
Definition at line 27 of file growbuf.h.
Constructor & Destructor Documentation
GrowBuf() [1/4]
GrowBuf::GrowBuf () inline
Definition at line 30 of file growbuf.h.
: m_str(nullptr), m_pos(0), m_len(0) {}
References m_len, m_pos, and m_str.
Referenced by GrowBuf(), GrowBuf(), operator=(), and operator=().
GrowBuf() [2/4]
GrowBuf::GrowBuf (size_t initialSize) inline
Definition at line 31 of file growbuf.h.
: m_pos(0), m_len(initialSize) { m_str=static_cast<char*>(malloc(m_len)); }
References m_len, m_pos, and m_str.
~GrowBuf()
GrowBuf::~GrowBuf () inline
Definition at line 32 of file growbuf.h.
{ free(m_str); }
References m_str.
GrowBuf() [3/4]
GrowBuf::GrowBuf (const GrowBuf & other) inline
Definition at line 33 of file growbuf.h.
    {
      m_len = other.m_len;
      m_pos = other.m_pos;
      m_str = static_cast<char*>(malloc(m_len));
      memcpy(m_str,other.m_str,m_len);
    }
References GrowBuf(), m_len, m_pos, and m_str.
GrowBuf() [4/4]
GrowBuf::GrowBuf (GrowBuf && other) inline
Definition at line 52 of file growbuf.h.
      : m_str(std::exchange(other.m_str,static_cast<char*>(nullptr)))
      , m_pos(std::exchange(other.m_pos,0))
      , m_len(std::exchange(other.m_len,0))
    {
    }
References GrowBuf(), m_len, m_pos, and m_str.
Member Function Documentation
addChar()
void GrowBuf::addChar (char c) inline
Definition at line 69 of file growbuf.h.
                          { if (m_pos>=m_len) { m_len+=GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                        m_str[m_pos++]=c;
                      }
References GROW_AMOUNT, m_len, m_pos, and m_str.
Referenced by SearchIndexExternal::addWord(), convertCharEntitiesToUTF8(), convertToDocBook(), convertToHtml(), convertToId(), convertToJSString(), convertToPSString(), convertToXML(), detab(), escapeCharsInString(), filter2008VhdlComment(), filterId(), HtmlDocVisitor::filterQuotedCdataAttr(), formatDateTime(), getConvertLatexMacro(), CitationManager::getFormulas(), DocParser::processCopyDoc(), and replaceVariables().
addInt()
void GrowBuf::addInt (const char * fmt, int value) inline
Definition at line 109 of file growbuf.h.
{
                      char tmp[50];
                      snprintf(tmp,50,fmt,value);
                      addStr(tmp);
    }
References addStr().
Referenced by formatDateTime().
addStr() [1/4]
void GrowBuf::addStr (const char * s) inline
Definition at line 90 of file growbuf.h.
{
                        if (s)
{
                          size_t l=strlen(s);
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strcpy(&m_str[m_pos],s);
                          m_pos+=l;
                        }
                      }
References GROW_AMOUNT, m_len, m_pos, and m_str.
addStr() [2/4]
void GrowBuf::addStr (const char * s, size_t n) inline
Definition at line 99 of file growbuf.h.
{
                        if (s)
{
                          size_t l=strlen(s);
                          if (n<l) l=n;
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strncpy(&m_str[m_pos],s,n);
                          m_pos+=l;
                        }
                      }
References GROW_AMOUNT, m_len, m_pos, and m_str.
addStr() [3/4]
void GrowBuf::addStr (const QCString & s) inline
Definition at line 72 of file growbuf.h.
{
                        if (!s.isEmpty())
{
                          size_t l=s.length();
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strcpy(&m_str[m_pos],s.data());
                          m_pos+=l;
                        }
                      }
References QCString::data(), GROW_AMOUNT, QCString::isEmpty(), QCString::length(), m_len, m_pos, and m_str.
Referenced by addInt(), SearchIndexExternal::addWord(), convertCharEntitiesToUTF8(), convertToDocBook(), convertToHtml(), convertToId(), convertToJSString(), convertToPSString(), convertToXML(), detab(), escapeCharsInString(), filterId(), HtmlDocVisitor::filterQuotedCdataAttr(), formatDateTime(), getConvertLatexMacro(), CitationManager::getFormulas(), DocParser::processCopyDoc(), and replaceVariables().
addStr() [4/4]
void GrowBuf::addStr (const std::string & s) inline
Definition at line 81 of file growbuf.h.
{
                        if (!s.empty())
{
                          size_t l=s.length();
                          if (m_pos+l>=m_len) { m_len+=l+GROW_AMOUNT; m_str = static_cast<char*>(realloc(m_str,m_len)); }
                          strcpy(&m_str[m_pos],s.c_str());
                          m_pos+=l;
                        }
                      }
References GROW_AMOUNT, m_len, m_pos, and m_str.
at()
const char & GrowBuf::at (size_t i) const inline
Definition at line 118 of file growbuf.h.
{ return m_str[i]; }
References m_str.
Referenced by filter2008VhdlComment().
clear()
void GrowBuf::clear () inline
Definition at line 68 of file growbuf.h.
{ m_pos=0; }
References m_pos.
Referenced by filterId(), and CitationManager::getFormulas().
empty()
bool GrowBuf::empty () const inline
Definition at line 119 of file growbuf.h.
{ return m_pos==0; }
References m_pos.
get() [1/2]
char * GrowBuf::get () inline
Definition at line 114 of file growbuf.h.
{ return m_str; }
References m_str.
Referenced by convertCharEntitiesToUTF8(), convertToDocBook(), convertToHtml(), convertToId(), convertToJSString(), convertToPSString(), convertToXML(), detab(), escapeCharsInString(), filter2008VhdlComment(), filterId(), HtmlDocVisitor::filterQuotedCdataAttr(), formatDateTime(), getConvertLatexMacro(), CitationManager::getFormulas(), DocParser::processCopyDoc(), and replaceVariables().
get() [2/2]
const char * GrowBuf::get () const inline
Definition at line 115 of file growbuf.h.
{ return m_str; }
References m_str.
getPos()
size_t GrowBuf::getPos () const inline
Definition at line 116 of file growbuf.h.
{ return m_pos; }
References m_pos.
Referenced by SearchIndexExternal::addWord(), filter2008VhdlComment(), and DocParser::processCopyDoc().
operator=() [1/2]
GrowBuf & GrowBuf::operator= (const GrowBuf & other) inline
Definition at line 40 of file growbuf.h.
    {
      if (this!=&other)
      {
        free(m_str);
        m_len = other.m_len;
        m_pos = other.m_pos;
        m_str = static_cast<char*>(malloc(m_len));
        memcpy(m_str,other.m_str,m_len);
      }
      return *this;
    }
References GrowBuf(), m_len, m_pos, and m_str.
operator=() [2/2]
GrowBuf & GrowBuf::operator= (GrowBuf && other) inline
Definition at line 58 of file growbuf.h.
    {
      if (this==&other)
        return *this;
      m_len = std::exchange(other.m_len,0);
      m_pos = std::exchange(other.m_pos,0);
      m_str = std::exchange(other.m_str,static_cast<char*>(nullptr));
      return *this;
    }
References GrowBuf(), m_len, m_pos, and m_str.
reserve()
void GrowBuf::reserve (size_t size) inline
Definition at line 67 of file growbuf.h.
{ if (m_len<size) { m_len = size; m_str = static_cast<char*>(realloc(m_str,m_len)); } }
References m_len, and m_str.
setPos()
void GrowBuf::setPos (size_t newPos) inline
Definition at line 117 of file growbuf.h.
{ m_pos = newPos; }
References m_pos.
Referenced by filter2008VhdlComment().
Member Data Documentation
m_len
size_t GrowBuf::m_len private
Definition at line 123 of file growbuf.h.
Referenced by addChar(), addStr(), addStr(), addStr(), addStr(), GrowBuf(), GrowBuf(), GrowBuf(), GrowBuf(), operator=(), operator=(), and reserve().
m_pos
size_t GrowBuf::m_pos private
Definition at line 122 of file growbuf.h.
Referenced by addChar(), addStr(), addStr(), addStr(), addStr(), clear(), empty(), getPos(), GrowBuf(), GrowBuf(), GrowBuf(), GrowBuf(), operator=(), operator=(), and setPos().
m_str
char* GrowBuf::m_str private
Definition at line 121 of file growbuf.h.
Referenced by addChar(), addStr(), addStr(), addStr(), addStr(), at(), get(), get(), GrowBuf(), GrowBuf(), GrowBuf(), GrowBuf(), operator=(), operator=(), reserve(), and ~GrowBuf().
The documentation for this class was generated from the following file:
src/growbuf.h