Doxygen: DocSymbol Class Reference
DocSymbol Class Reference
Node representing a special symbol.
#include <src/docnode.h>
Public Member Functions
DocSymbol (DocParser *parser, DocNodeVariant *parent, HtmlEntityMapper::SymType s)
HtmlEntityMapper::SymType symbol () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Static Public Member Functions
static HtmlEntityMapper::SymType decodeSymbol (const QCString &symName)
Private Attributes
HtmlEntityMapper::SymType m_symbol = HtmlEntityMapper::Sym_Unknown
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a special symbol.
Definition at line 307 of file docnode.h.
Constructor & Destructor Documentation
DocSymbol()
DocSymbol::DocSymbol (DocParser * parser, DocNodeVariant * parent, HtmlEntityMapper::SymType s) inline
Definition at line 310 of file docnode.h.
      : DocNode(parser,parent), m_symbol(s) {}
References DocNode::DocNode(), m_symbol, DocNode::parent(), and DocNode::parser().
Member Function Documentation
decodeSymbol()
HtmlEntityMapper::SymType DocSymbol::decodeSymbol (const QCString & symName) static
Definition at line 151 of file docnode.cpp.
{
  return HtmlEntityMapper::instance().name2sym(symName);
}
References HtmlEntityMapper::instance(), and HtmlEntityMapper::name2sym().
Referenced by DocParser::defaultHandleToken(), DocIndexEntry::parse(), DocPara::parse(), and DocText::parse().
symbol()
HtmlEntityMapper::SymType DocSymbol::symbol () const inline
Definition at line 312 of file docnode.h.
{ return m_symbol; }
References m_symbol.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), TextDocVisitor::operator()(), and XmlDocVisitor::operator()().
Member Data Documentation
m_symbol
HtmlEntityMapper::SymType DocSymbol::m_symbol = HtmlEntityMapper::Sym_Unknown private
Definition at line 316 of file docnode.h.
Referenced by DocSymbol(), and symbol().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp