Doxygen: src/dotrunner.cpp File Reference
dotrunner.cpp File Reference
#include <cassert>
#include <cmath>
#include <gunzip.hh>
#include "dotrunner.h"
#include "util.h"
#include "portable.h"
#include "dot.h"
#include "message.h"
#include "config.h"
#include "dir.h"
#include "doxygen.h"
Macros
#define MAX_LATEX_GRAPH_INCH 150
#define MAX_LATEX_GRAPH_SIZE (MAX_LATEX_GRAPH_INCH * 72)
#define DBG(x)
Functions
static void checkPngResult (const QCString &imgName)
static bool resetPDFSize (const int width, const int height, const QCString &base)
QCString getBaseNameOfOutput (const QCString &output)
Macro Definition Documentation
DBG
#define DBG (x)
Value:
do {} while(0)
Definition at line 53 of file dotrunner.cpp.
Referenced by reg::Ex::match(), reg::Ex::Private::matchAt(), and DotRunner::readBoundingBox().
MAX_LATEX_GRAPH_INCH
#define MAX_LATEX_GRAPH_INCH 150
Definition at line 49 of file dotrunner.cpp.
Referenced by resetPDFSize().
MAX_LATEX_GRAPH_SIZE
#define MAX_LATEX_GRAPH_SIZE (MAX_LATEX_GRAPH_INCH * 72)
Definition at line 50 of file dotrunner.cpp.
Referenced by DotRunner::run().
Function Documentation
checkPngResult()
static void checkPngResult (const QCString & imgName) static
Definition at line 59 of file dotrunner.cpp.
{
  FILE *f = Portable::fopen(imgName,"rb");
  if (f)
  {
    char data[4];
    if (fread(data,1,4,f)==4)
    {
      if (!(data[1]=='P' && data[2]=='N' && data[3]=='G'))
      {
        err("Image '%s' produced by dot is not a valid PNG!\n"
          "You should either select a different format "
          "(DOT_IMAGE_FORMAT in the config file) or install a more "
          "recent version of graphviz (1.7+)\n",qPrint(imgName)
        );
      }
    }
    else
    {
      err("Could not read image '%s' generated by dot!\n",qPrint(imgName));
    }
    fclose(f);
  }
  else
  {
    err("Could not open image '%s' generated by dot!\n",qPrint(imgName));
  }
}
References err, Portable::fopen(), and qPrint().
Referenced by DotRunner::run().
getBaseNameOfOutput()
QCString getBaseNameOfOutput (const QCString & output)
Definition at line 274 of file dotrunner.cpp.
{
  int index = output.findRev('.');
  if (index < 0) return output;
  return output.left(index);
}
References QCString::findRev(), and QCString::left().
Referenced by DotRunner::run().
resetPDFSize()
static bool resetPDFSize (const int width, const int height, const QCString & base) static
Definition at line 88 of file dotrunner.cpp.
{
  QCString tmpName   = base+".tmp";
  QCString patchFile = base+".dot";
  Dir thisDir;
  if (!thisDir.rename(patchFile.str(),tmpName.str()))
  {
    err("Failed to rename file %s to %s!\n",qPrint(patchFile),qPrint(tmpName));
    return FALSE;
  }
  std::ifstream fi = Portable::openInputStream(tmpName);
  std::ofstream t  = Portable::openOutputStream(patchFile);
  if (!fi.is_open())
  {
    err("problem opening file %s for patching!\n",qPrint(tmpName));
    thisDir.rename(tmpName.str(),patchFile.str());
    return FALSE;
  }
  if (!t.is_open())
  {
    err("problem opening file %s for patching!\n",qPrint(patchFile));
    thisDir.rename(tmpName.str(),patchFile.str());
    return FALSE;
  }
  std::string line;
  while (getline(fi,line)) // foreach line
  {
    if (line.find("LATEX_PDF_SIZE") != std::string::npos)
    {
      double scale = (width > height ? width : height)/double(MAX_LATEX_GRAPH_INCH);
      t << "  size=\""<<width/scale << "," <<height/scale << "\";\n";
    }
    else
      t << line << "\n";
  }
  fi.close();
  t.close();
  // remove temporary file
  thisDir.remove(tmpName.str());
  return TRUE;
}
References err, FALSE, MAX_LATEX_GRAPH_INCH, Portable::openInputStream(), Portable::openOutputStream(), qPrint(), Dir::remove(), Dir::rename(), QCString::str(), and TRUE.
Referenced by DotRunner::run().