Doxygen: TemplateNodeIndexEntry Class Reference
TemplateNodeIndexEntry Class Reference
Class representing an 'indexentry' tag in a template.
Classes
struct Mapping
Public Member Functions
TemplateNodeIndexEntry (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeIndexEntry >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()=default
TemplateNode * parent ()
Private Attributes
QCString m_name
std::vector< Mapping > m_args
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeIndexEntry >
static TemplateNodePtr createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeIndexEntry >
void mkpath (const TemplateContextImpl *ci, const std::string &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeIndexEntry >
QCString m_templateName
int m_line
Detailed Description
Class representing an 'indexentry' tag in a template.
Definition at line 4009 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeIndexEntry()
TemplateNodeIndexEntry::TemplateNodeIndexEntry (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 4018 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeIndexEntry>(parser,parent,line)
    {
      AUTO_TRACE("data={}",Trace::trunc(data));
      ExpressionParser expParser(parser,line);
      std::vector<QCString> args = split(data," ");
      auto it = args.begin();
      if (it==args.end() || (*it).find('=')!=-1)
      {
        parser->warn(parser->templateName(),line,"Missing name for indexentry tag");
      }
      else
      {
        m_name = *it;
        ++it;
        while (it!=args.end())
        {
          QCString arg = *it;
          int j=arg.find('=');
          if (j>0)
          {
            ExprAstPtr expr = expParser.parse(arg.mid(j+1));
            if (expr)
            {
              m_args.emplace_back(arg.left(j),std::move(expr));
            }
          }
          else
          {
            parser->warn(parser->templateName(),line,"invalid argument '%s' for indexentry tag",qPrint(arg));
          }
          ++it;
        }
      }
    }
References AUTO_TRACE, QCString::find(), QCString::left(), m_args, m_name, QCString::mid(), ExpressionParser::parse(), qPrint(), split(), TemplateParser::templateName(), Trace::trunc(), and TemplateParser::warn().
Member Function Documentation
render()
void TemplateNodeIndexEntry::render (TextStream & , TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 4053 of file template.cpp.
    {
      AUTO_TRACE();
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      if (!m_name.isEmpty())
      {
        ci->setLocation(m_templateName,m_line);
        std::vector<TemplateKeyValue> list;
        for (const auto &mapping : m_args)
        {
          list.emplace_back(mapping.name,mapping.value->resolve(c));
        }
        ci->addIndexEntry(m_name,list);
      }
    }
References TemplateContextImpl::addIndexEntry(), AUTO_TRACE, QCString::isEmpty(), m_args, TemplateNodeCreator< TemplateNodeIndexEntry >::m_line, m_name, TemplateNodeCreator< TemplateNodeIndexEntry >::m_templateName, and TemplateContextImpl::setLocation().
Member Data Documentation
m_args
std::vector<Mapping> TemplateNodeIndexEntry::m_args private
Definition at line 4071 of file template.cpp.
Referenced by render(), and TemplateNodeIndexEntry().
m_name
QCString TemplateNodeIndexEntry::m_name private
Definition at line 4070 of file template.cpp.
Referenced by render(), and TemplateNodeIndexEntry().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/template.cpp