Doxygen: FileCodeParser Class Reference
FileCodeParser Class Reference
Generic code parser.
#include <src/fileparser.h>
Public Member Functions
void parseCode (OutputCodeList &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool stripCodeComments, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=nullptr, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=nullptr, bool showLineNumbers=TRUE, const Definition *searchCtx=nullptr, bool collectXRefs=TRUE) override
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
void resetCodeParserState () override
Resets the state of the code parser.
Public Member Functions inherited from CodeParserInterface
Detailed Description
Generic code parser.
Definition at line 22 of file fileparser.h.
Member Function Documentation
parseCode()
void FileCodeParser::parseCode (OutputCodeList & codeOutList, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool stripCodeComments, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = nullptr, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = nullptr, bool showLineNumbers = TRUE, const Definition * searchCtx = nullptr, bool collectXRefs = TRUE) override virtual
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
[in] codeOutList interface for writing the result.
[in] scopeName Name of scope to which the code belongs.
[in] input Actual code in the form of a string
[in] lang The programming language of the code fragment.
[in] stripCodeComments signals whether or not for the code block the doxygen comments should be stripped.
[in] isExampleBlock TRUE iff the code is part of an example.
[in] exampleName Name of the example.
[in] fileDef File definition to which the code is associated.
[in] startLine Starting line in case of a code fragment.
[in] endLine Ending line of the code fragment.
[in] inlineFragment Code fragment that is to be shown inline as part of the documentation.
[in] memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
[in] showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
[in] searchCtx context under which search data has to be stored.
[in] collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
Definition at line 20 of file fileparser.cpp.
{
  int lineNr = startLine!=-1 ? startLine : 1;
  size_t length = input.length();
  size_t i=0;
  while (i<length && (endLine==-1 || lineNr<=endLine))
  {
    size_t j=i;
    while (j<length && input[j]!='\n') j++;
    QCString lineStr = input.mid(i,j-i);
    codeOutIntf.startCodeLine(lineNr);
    if (fileDef != nullptr && showLineNumbers)
    {
      codeOutIntf.writeLineNumber(QCString(),QCString(),QCString(),lineNr,!inlineFragment);
    }
    if (!lineStr.isEmpty()) codeOutIntf.codify(lineStr.data());
    codeOutIntf.endCodeLine();
    lineNr++;
    i=j+1;
  }
}
References OutputCodeList::codify(), QCString::data(), OutputCodeList::endCodeLine(), QCString::isEmpty(), QCString::length(), QCString::mid(), OutputCodeList::startCodeLine(), and OutputCodeList::writeLineNumber().
resetCodeParserState()
void FileCodeParser::resetCodeParserState () inline override virtual
Resets the state of the code parser.
Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Definition at line 41 of file fileparser.h.
{}
The documentation for this class was generated from the following files:
src/fileparser.h
src/fileparser.cpp