Doxygen: NamespaceDefMutable Class Reference
NamespaceDefMutable Class Reference abstract
#include <src/namespacedef.h>
Public Member Functions
virtual void setMetaData (const QCString &m)=0
virtual void insertUsedFile (FileDef *fd)=0
virtual void writeDocumentation (OutputList &ol)=0
virtual void writeMemberPages (OutputList &ol)=0
virtual void writeTagFile (TextStream &)=0
virtual void insertClass (ClassDef *cd)=0
virtual void insertConcept (ConceptDef *cd)=0
virtual void insertNamespace (NamespaceDef *nd)=0
virtual void insertMember (MemberDef *md)=0
virtual void computeAnchors ()=0
virtual void countMembers ()=0
virtual void addMembersToMemberGroup ()=0
virtual void distributeMemberGroupDocumentation ()=0
virtual void findSectionsInDocumentation ()=0
virtual void sortMemberLists ()=0
virtual void addListReferences ()=0
virtual void setFileName (const QCString &fn)=0
virtual void combineUsingRelations (NamespaceDefSet &visitedNamespace)=0
virtual void addUsingDirective (NamespaceDef *nd)=0
virtual void addUsingDeclaration (const Definition *d)=0
virtual void setInline (bool isInline)=0
Public Member Functions inherited from DefinitionMutable
virtual void setName (const QCString &name)=0
virtual void setId (const QCString &name)=0
virtual void setDefFile (const QCString &df, int defLine, int defColumn)=0
virtual void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)=0
virtual void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)=0
virtual void setInbodyDocumentation (const QCString &d, const QCString &docFile, int docLine)=0
virtual void setReference (const QCString &r)=0
virtual void setBodySegment (int defLine, int bls, int ble)=0
virtual void setBodyDef (const FileDef *fd)=0
virtual void setRefItems (const RefItemVector &sli)=0
virtual void setOuterScope (Definition *d)=0
virtual void setHidden (bool b)=0
virtual void setArtificial (bool b)=0
virtual void setExported (bool b)=0
virtual void setLanguage (SrcLangExt lang)=0
virtual void setLocalName (const QCString &name)=0
virtual void makePartOfGroup (GroupDef *gd)=0
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)=0
virtual void addSourceReferencedBy (MemberDef *d, const QCString &sourceRefName)=0
virtual void addSourceReferences (MemberDef *d, const QCString &sourceRefName)=0
virtual void mergeRefItems (Definition *d)=0
virtual void addInnerCompound (Definition *d)=0
virtual void mergeReferences (const Definition *other)=0
virtual void mergeReferencedBy (const Definition *other)=0
virtual void computeTooltip ()=0
virtual void writeSourceDef (OutputList &ol) const =0
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const =0
virtual bool hasSourceRefs () const =0
virtual bool hasSourceReffedBy () const =0
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const =0
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const =0
virtual void writeNavigationPath (OutputList &ol) const =0
virtual void writeQuickMemberLinks (OutputList &, const MemberDef *) const =0
virtual void writeSummaryLinks (OutputList &) const =0
virtual void writeDocAnchorsToTagFile (TextStream &) const =0
virtual void writeToc (OutputList &ol, const LocalToc &lt) const =0
Public Member Functions inherited from NamespaceDef
virtual int numDocMembers () const =0
virtual const LinkedRefMap< NamespaceDef > & getUsedNamespaces () const =0
virtual const LinkedRefMap< const Definition > & getUsedDefinitions () const =0
virtual bool isConstantGroup () const =0
virtual bool isModule () const =0
virtual bool isLibrary () const =0
virtual bool isInline () const =0
virtual bool isVisibleInHierarchy () const =0
virtual bool hasDetailedDescription () const =0
virtual bool subGrouping () const =0
virtual MemberList * getMemberList (MemberListType lt) const =0
virtual const MemberLists & getMemberLists () const =0
virtual const MemberDef * getMemberByName (const QCString &) const =0
virtual int countVisibleMembers () const =0
virtual const MemberGroupList & getMemberGroups () const =0
virtual ClassLinkedRefMap getClasses () const =0
virtual ClassLinkedRefMap getInterfaces () const =0
virtual ClassLinkedRefMap getStructs () const =0
virtual ClassLinkedRefMap getExceptions () const =0
virtual NamespaceLinkedRefMap getNamespaces () const =0
virtual ConceptLinkedRefMap getConcepts () const =0
virtual QCString title () const =0
virtual QCString compoundTypeString () const =0
Public Member Functions inherited from Definition
virtual DefType definitionType () const =0
virtual CodeSymbolType codeSymbolType () const =0
virtual bool isAlias () const =0
virtual const QCString & name () const =0
virtual bool isAnonymous () const =0
virtual QCString displayName (bool includeScope=TRUE) const =0
virtual const QCString & localName () const =0
virtual QCString qualifiedName () const =0
virtual QCString symbolName () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString getSourceFileBase () const =0
virtual QCString getSourceAnchor () const =0
virtual QCString documentation () const =0
virtual int docLine () const =0
virtual QCString docFile () const =0
virtual QCString briefDescription (bool abbreviate=FALSE) const =0
virtual QCString briefDescriptionAsTooltip () const =0
virtual int briefLine () const =0
virtual QCString inbodyDocumentation () const =0
virtual QCString inbodyFile () const =0
virtual int inbodyLine () const =0
virtual QCString briefFile () const =0
virtual QCString getDefFileName () const =0
virtual QCString getDefFileExtension () const =0
virtual int getDefLine () const =0
virtual int getDefColumn () const =0
virtual bool hasDocumentation () const =0
virtual bool hasUserDocumentation () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isVisibleInProject () const =0
virtual bool isVisible () const =0
virtual bool isHidden () const =0
virtual bool isArtificial () const =0
virtual bool isExported () const =0
virtual QCString getReference () const =0
virtual bool isReference () const =0
virtual QCString externalReference (const QCString &relPath) const =0
virtual int getStartDefLine () const =0
virtual int getStartBodyLine () const =0
virtual int getEndBodyLine () const =0
virtual const FileDef * getBodyDef () const =0
virtual SrcLangExt getLanguage () const =0
Returns the programming language this definition was written in.
virtual const GroupList & partOfGroups () const =0
virtual bool isLinkableViaGroup () const =0
virtual const RefItemVector & xrefListItems () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual Definition * getOuterScope () const =0
virtual const MemberVector & getReferencesMembers () const =0
virtual const MemberVector & getReferencedByMembers () const =0
virtual bool hasSections () const =0
virtual bool hasSources () const =0
virtual bool hasBriefDescription () const =0
returns TRUE if this class has a brief description
virtual QCString id () const =0
virtual const SectionRefs & getSectionRefs () const =0
returns the section dictionary, only of importance for pagedef
virtual QCString navigationPathAsString () const =0
virtual QCString pathFragment () const =0
virtual void _setSymbolName (const QCString &name)=0
virtual QCString _symbolName () const =0
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Detailed Description
Definition at line 100 of file namespacedef.h.
Member Function Documentation
addListReferences()
virtual void NamespaceDefMutable::addListReferences () pure virtual
Implemented in NamespaceDefImpl.
Referenced by addListReferences().
addMembersToMemberGroup()
virtual void NamespaceDefMutable::addMembersToMemberGroup () pure virtual
Implemented in NamespaceDefImpl.
Referenced by addMembersToMemberGroup().
addUsingDeclaration()
virtual void NamespaceDefMutable::addUsingDeclaration (const Definition * d) pure virtual
Implemented in NamespaceDefImpl.
Referenced by findUsingDeclarations(), and findUsingDeclImports().
addUsingDirective()
virtual void NamespaceDefMutable::addUsingDirective (NamespaceDef * nd) pure virtual
Implemented in NamespaceDefImpl.
Referenced by findUsingDirectives().
combineUsingRelations()
virtual void NamespaceDefMutable::combineUsingRelations (NamespaceDefSet & visitedNamespace) pure virtual
Implemented in NamespaceDefImpl.
Referenced by combineUsingRelations(), FileDefImpl::combineUsingRelations(), and NamespaceDefImpl::combineUsingRelations().
computeAnchors()
virtual void NamespaceDefMutable::computeAnchors () pure virtual
Implemented in NamespaceDefImpl.
Referenced by computeMemberReferences().
countMembers()
virtual void NamespaceDefMutable::countMembers () pure virtual
Implemented in NamespaceDefImpl.
Referenced by countMembers().
distributeMemberGroupDocumentation()
virtual void NamespaceDefMutable::distributeMemberGroupDocumentation () pure virtual
Implemented in NamespaceDefImpl.
Referenced by distributeMemberGroupDocumentation().
findSectionsInDocumentation()
virtual void NamespaceDefMutable::findSectionsInDocumentation () pure virtual
Implemented in NamespaceDefImpl.
Referenced by findSectionsInDocumentation().
insertClass()
virtual void NamespaceDefMutable::insertClass (ClassDef * cd) pure virtual
Implemented in NamespaceDefImpl.
insertConcept()
virtual void NamespaceDefMutable::insertConcept (ConceptDef * cd) pure virtual
Implemented in NamespaceDefImpl.
insertMember()
virtual void NamespaceDefMutable::insertMember (MemberDef * md) pure virtual
Implemented in NamespaceDefImpl.
Referenced by addVariableToFile(), findEnums(), findUsingDeclImports(), NamespaceDefImpl::insertMember(), and insertMemberAlias().
insertNamespace()
virtual void NamespaceDefMutable::insertNamespace (NamespaceDef * nd) pure virtual
Implemented in NamespaceDefImpl.
insertUsedFile()
virtual void NamespaceDefMutable::insertUsedFile (FileDef * fd) pure virtual
Implemented in NamespaceDefImpl.
Referenced by buildNamespaceList(), and findUsingDirectives().
setFileName()
virtual void NamespaceDefMutable::setFileName (const QCString & fn) pure virtual
Implemented in NamespaceDefImpl.
Referenced by buildNamespaceList().
setInline()
virtual void NamespaceDefMutable::setInline (bool isInline) pure virtual
Implemented in NamespaceDefImpl.
References NamespaceDef::isInline(), and Definition::name().
Referenced by buildNamespaceList(), and findUsingDirectives().
setMetaData()
virtual void NamespaceDefMutable::setMetaData (const QCString & m) pure virtual
Implemented in NamespaceDefImpl.
Referenced by buildNamespaceList(), and findUsingDirectives().
sortMemberLists()
virtual void NamespaceDefMutable::sortMemberLists () pure virtual
Implemented in NamespaceDefImpl.
Referenced by sortMemberLists().
writeDocumentation()
virtual void NamespaceDefMutable::writeDocumentation (OutputList & ol) pure virtual
Implemented in NamespaceDefImpl.
Referenced by generateNamespaceDocs().
writeMemberPages()
virtual void NamespaceDefMutable::writeMemberPages (OutputList & ol) pure virtual
Implemented in NamespaceDefImpl.
writeTagFile()
virtual void NamespaceDefMutable::writeTagFile (TextStream &) pure virtual
Implemented in NamespaceDefImpl.
Referenced by writeTagFile().
The documentation for this class was generated from the following file:
src/namespacedef.h