Doxygen: src/condparser.cpp File Reference
condparser.cpp File Reference
#include <algorithm>
#include "condparser.h"
#include "config.h"
#include "message.h"
Functions
static bool isDelimiter (const char c)
checks if the given char c is a delimiter minus is checked apart, can be unary minus
static bool isAlpha (const char c)
checks if the given char c is a letter or underscore
static bool isAlphaNumSpec (const char c)
Function Documentation
isAlpha()
static bool isAlpha (const char c) static
checks if the given char c is a letter or underscore
Definition at line 77 of file condparser.cpp.
{
  return (c>='A' && c<='Z') || (c>='a' && c<='z') || c=='_';
}
Referenced by CondParser::getToken(), and isAlphaNumSpec().
isAlphaNumSpec()
static bool isAlphaNumSpec (const char c) static
Definition at line 82 of file condparser.cpp.
{
  return isAlpha(c) || (c>='0' && c<='9') || c=='-' || c=='.' || (static_cast<unsigned char>(c)>=0x80);
}
References isAlpha().
Referenced by CondParser::getToken().
isDelimiter()
static bool isDelimiter (const char c) static
checks if the given char c is a delimiter minus is checked apart, can be unary minus
Definition at line 69 of file condparser.cpp.
{
  return c=='&' || c=='|' || c=='!';
}
Referenced by CondParser::getToken().