Doxygen: RTFGenerator Class Reference
RTFGenerator Class Reference
Generator for RTF output.
#include <src/rtfgen.h>
Classes
struct RTFListItemInfo
Public Member Functions
RTFGenerator ()
RTFGenerator (const RTFGenerator &)
RTFGenerator & operator= (const RTFGenerator &)
RTFGenerator (RTFGenerator &&)=delete
RTFGenerator & operator= (RTFGenerator &&)=delete
~RTFGenerator ()
void setRelativePath (const QCString &path)
void setSourceFileName (const QCString &sourceFileName)
void clearBuffer ()
OutputType type () const override
std::unique_ptr< OutputGenIntf > clone () override
void addCodeGen (OutputCodeList &list) override
void cleanup () override
void writeDoc (const IDocNodeAST *ast, const Definition *, const MemberDef *, int) override
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id, int hierarchyLevel) override
void endFile () override
void writeSearchInfo () override
void writeFooter (const QCString &) override
void startPageDoc (const QCString &) override
void endPageDoc () override
void startIndexSection (IndexSection) override
void endIndexSection (IndexSection) override
void writePageLink (const QCString &, bool) override
void startProjectNumber () override
void endProjectNumber () override
void writeStyleInfo (int part) override
void startTitleHead (const QCString &) override
void endTitleHead (const QCString &, const QCString &name) override
void startParagraph (const QCString &classDef) override
void endParagraph () override
void writeString (const QCString &text) override
void startIndexListItem () override
void endIndexListItem () override
void startIndexList () override
void endIndexList () override
void startIndexKey () override
void endIndexKey () override
void startIndexValue (bool) override
void endIndexValue (const QCString &, bool) override
void startItemList () override
void endItemList () override
void startIndexItem (const QCString &ref, const QCString &file) override
void endIndexItem (const QCString &ref, const QCString &file) override
void docify (const QCString &text) override
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name) override
void startTextLink (const QCString &f, const QCString &anchor) override
void endTextLink () override
void startTypewriter () override
void endTypewriter () override
void startGroupHeader (int) override
void endGroupHeader (int) override
void startItemListItem () override
void endItemListItem () override
void startMemberSections () override
void endMemberSections () override
void startHeaderSection () override
void endHeaderSection () override
void startMemberHeader (const QCString &, int) override
void endMemberHeader () override
void startMemberSubtitle () override
void endMemberSubtitle () override
void startMemberDocList () override
void endMemberDocList () override
void startMemberList () override
void endMemberList () override
void startInlineHeader () override
void endInlineHeader () override
void startAnonTypeScope (int) override
void endAnonTypeScope (int) override
void startMemberItem (const QCString &, MemberItemType, const QCString &) override
void endMemberItem (MemberItemType) override
void startMemberTemplateParams () override
void endMemberTemplateParams (const QCString &, const QCString &) override
void startCompoundTemplateParams () override
void endCompoundTemplateParams () override
void insertMemberAlign (bool) override
void insertMemberAlignLeft (MemberItemType, bool) override
void writeRuler () override
void writeAnchor (const QCString &fileName, const QCString &name) override
void startEmphasis () override
void endEmphasis () override
void startBold () override
void endBold () override
void lineBreak (const QCString &style=QCString()) override
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool) override
void endMemberDoc (bool) override
void startDoxyAnchor (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &) override
void endDoxyAnchor (const QCString &, const QCString &) override
void addLabel (const QCString &, const QCString &) override
void writeChar (char c) override
void writeLatexSpacing () override
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name) override
void startCenter () override
void endCenter () override
void startSmall () override
void endSmall () override
void startMemberDescription (const QCString &, const QCString &, bool) override
void endMemberDescription () override
void startMemberDeclaration () override
void endMemberDeclaration (const QCString &, const QCString &) override
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &) override
void startExamples () override
void endExamples () override
void startDescForItem () override
void endDescForItem () override
void startSection (const QCString &, const QCString &, SectionType) override
void endSection (const QCString &, SectionType) override
void addIndexItem (const QCString &, const QCString &) override
void startIndent () override
void endIndent () override
void writeSynopsis () override
void startClassDiagram () override
void endClassDiagram (const ClassDiagram &, const QCString &filename, const QCString &name) override
void startPageRef () override
void endPageRef (const QCString &, const QCString &) override
void startQuickIndices () override
void endQuickIndices () override
void writeSplitBar (const QCString &) override
void writeNavigationPath (const QCString &) override
void writeLogo () override
void writeQuickLinks (HighlightedItem, const QCString &) override
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool) override
void startContents () override
void endContents () override
void writeNonBreakableSpace (int) override
void startDescTable (const QCString &title, const bool hasInits) override
void endDescTable () override
void startDescTableRow () override
void endDescTableRow () override
void startDescTableTitle () override
void endDescTableTitle () override
void startDescTableInit () override
void endDescTableInit () override
void startDescTableData () override
void endDescTableData () override
void startDotGraph () override
void endDotGraph (DotClassGraph &) override
void startInclDepGraph () override
void endInclDepGraph (DotInclDepGraph &) override
void startGroupCollaboration () override
void endGroupCollaboration (DotGroupCollaboration &g) override
void startCallGraph () override
void endCallGraph (DotCallGraph &) override
void startDirDepGraph () override
void endDirDepGraph (DotDirDeps &g) override
void writeGraphicalHierarchy (DotGfxHierarchyTable &) override
void startMemberGroupHeader (bool) override
void endMemberGroupHeader () override
void startMemberGroupDocs () override
void endMemberGroupDocs () override
void startMemberGroup () override
void endMemberGroup (bool) override
void startTextBlock (bool dense) override
void endTextBlock (bool) override
void lastIndexPage () override
void startMemberDocPrefixItem () override
void endMemberDocPrefixItem () override
void startMemberDocName (bool) override
void endMemberDocName () override
void startParameterType (bool, const QCString &) override
void endParameterType () override
void startParameterName (bool) override
void endParameterName () override
void startParameterExtra () override
void endParameterExtra (bool, bool, bool) override
void startParameterDefVal (const char *s) override
void endParameterDefVal () override
void startParameterList (bool) override
void endParameterList () override
void exceptionEntry (const QCString &, bool) override
void startConstraintList (const QCString &) override
void startConstraintParam () override
void endConstraintParam () override
void startConstraintType () override
void endConstraintType () override
void startConstraintDocs () override
void endConstraintDocs () override
void endConstraintList () override
void startMemberDocSimple (bool) override
void endMemberDocSimple (bool) override
void startInlineMemberType () override
void endInlineMemberType () override
void startInlineMemberName () override
void endInlineMemberName () override
void startInlineMemberDoc () override
void endInlineMemberDoc () override
void startLabels () override
void writeLabel (const QCString &l, bool isLast) override
void endLabels () override
void writeLocalToc (const SectionRefs &, const LocalToc &) override
void startPlainFile (const QCString &name) override
void endPlainFile () override
Public Member Functions inherited from OutputGenerator
OutputGenerator ()
OutputGenerator (const QCString &dir)
virtual ~OutputGenerator ()=default
QCString dir () const
QCString fileName () const
void startPlainFile (const QCString &name)
void endPlainFile ()
Public Member Functions inherited from OutputGenIntf
Static Public Member Functions
static void init ()
static void writeStyleSheetFile (TextStream &t)
static void writeExtensionsFile (TextStream &t)
static bool preProcessFileInplace (const QCString &path, const QCString &name)
This is an API to a VERY brittle RTF preprocessor that combines nested RTF files.
Private Member Functions
QCString rtf_BList_DepthStyle ()
QCString rtf_CList_DepthStyle ()
QCString rtf_EList_DepthStyle ()
QCString rtf_LCList_DepthStyle ()
QCString rtf_DList_DepthStyle ()
void beginRTFDocument ()
void beginRTFChapter ()
void beginRTFSection ()
void rtfwriteRuler_doubleline ()
void rtfwriteRuler_emboss ()
void rtfwriteRuler_thick ()
void rtfwriteRuler_thin ()
void writeRTFReference (const QCString &label)
void newParagraph ()
int indentLevel () const
void incIndentLevel ()
void decIndentLevel ()
Private Attributes
bool m_bstartedBody = false
bool m_omitParagraph = false
int m_numCols = 0
QCString m_relPath
int m_hierarchyLevel = 0
int m_indentLevel = 0
std::array< RTFListItemInfo, maxIndentLevels > m_listItemInfo
std::unique_ptr< OutputCodeList > m_codeList
RTFCodeGenerator * m_codeGen
Static Private Attributes
static const int maxIndentLevels = 13
Additional Inherited Members
Public Types inherited from OutputGenerator
enum class ParamListTypes { Param , RetVal , Exception }
enum class MemberItemType { Normal , AnonymousStart , AnonymousEnd , Templated }
Protected Attributes inherited from OutputGenerator
TextStream m_t
QCString m_dir
Detailed Description
Generator for RTF output.
Definition at line 79 of file rtfgen.h.
Constructor & Destructor Documentation
RTFGenerator() [1/3]
RTFGenerator::RTFGenerator ()
Definition at line 336 of file rtfgen.cpp.
  : OutputGenerator(Config_getString(RTF_OUTPUT))
  , m_codeList(std::make_unique<OutputCodeList>())
{
  m_codeGen = m_codeList->add<RTFCodeGenerator>(&m_t);
}
References Config_getString, m_codeGen, m_codeList, OutputGenerator::m_t, and OutputGenerator::OutputGenerator().
Referenced by operator=(), operator=(), RTFGenerator(), and RTFGenerator().
RTFGenerator() [2/3]
RTFGenerator::RTFGenerator (const RTFGenerator & og)
Definition at line 343 of file rtfgen.cpp.
                                                 : OutputGenerator(og.m_dir), OutputGenIntf()
{
  m_codeList       = std::make_unique<OutputCodeList>(*og.m_codeList);
  m_codeGen        = m_codeList->get<RTFCodeGenerator>(OutputType::RTF);
  m_codeGen->setTextStream(&m_t);
  m_bstartedBody   = og.m_bstartedBody;
  m_omitParagraph  = og.m_omitParagraph;
  m_numCols        = og.m_numCols;
  m_relPath        = og.m_relPath;
  m_indentLevel    = og.m_indentLevel;
  m_listItemInfo   = og.m_listItemInfo;
}
References m_bstartedBody, m_codeGen, m_codeList, OutputGenerator::m_dir, m_indentLevel, m_listItemInfo, m_numCols, m_omitParagraph, m_relPath, OutputGenerator::m_t, OutputGenerator::OutputGenerator(), RTF, and RTFGenerator().
RTFGenerator() [3/3]
RTFGenerator::RTFGenerator (RTFGenerator &&) delete
References RTFGenerator().
~RTFGenerator()
RTFGenerator::~RTFGenerator () default
Member Function Documentation
addCodeGen()
void RTFGenerator::addCodeGen (OutputCodeList & list) override virtual
Implements OutputGenIntf.
Definition at line 376 of file rtfgen.cpp.
{
  list.add<RTFCodeGeneratorDefer>(m_codeGen);
}
References OutputCodeList::add(), and m_codeGen.
addIndexItem()
void RTFGenerator::addIndexItem (const QCString & s1, const QCString & s2) override virtual
Implements OutputGenIntf.
Definition at line 1744 of file rtfgen.cpp.
{
  if (!s1.isEmpty())
  {
    m_t << "{\\xe \\v ";
    docify(s1);
    if (!s2.isEmpty())
    {
      m_t << "\\:";
      docify(s2);
    }
    m_t << "}\n";
  }
}
References docify(), QCString::isEmpty(), and OutputGenerator::m_t.
Referenced by endTitleHead(), and startMemberDoc().
addLabel()
void RTFGenerator::addLabel (const QCString & , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 1738 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment addLabel}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
beginRTFChapter()
void RTFGenerator::beginRTFChapter () private
Definition at line 660 of file rtfgen.cpp.
{
  m_t << "\n";
  DBG_RTF(m_t << "{\\comment BeginRTFChapter}\n")
  m_t << rtf_Style_Reset;
  // if we are compact, no extra page breaks...
  if (Config_getBool(COMPACT_RTF))
  {
    //      m_t << "\\sect\\sectd\\sbknone\n";
    m_t << "\\sect\\sbknone\n";
    rtfwriteRuler_thick();
  }
  else
    m_t << "\\sect\\sbkpage\n";
  //m_t << "\\sect\\sectd\\sbkpage\n";
  m_t << rtf_Style["Heading1"].reference() << "\n";
}
References Config_getBool, DBG_RTF, OutputGenerator::m_t, rtf_Style, rtf_Style_Reset, and rtfwriteRuler_thick().
Referenced by endIndexSection(), and startIndexSection().
beginRTFDocument()
void RTFGenerator::beginRTFDocument () private
Definition at line 523 of file rtfgen.cpp.
{
  /* all the included RTF files should begin with the
   * same header
   */
  m_t << "{\\rtf1\\ansi\\ansicpg" << theTranslator->trRTFansicp();
  m_t << "\\uc1 \\deff0\\deflang1033\\deflangfe1033\n";
  DBG_RTF(m_t << "{\\comment Beginning font list}\n")
  m_t << "{\\fonttbl ";
  m_t << "{\\f0\\froman\\fcharset" << theTranslator->trRTFCharSet();
  m_t << "\\fprq2{\\*\\panose 02020603050405020304}Times New Roman;}\n";
  m_t << "{\\f1\\fswiss\\fcharset" << theTranslator->trRTFCharSet();
  m_t << "\\fprq2{\\*\\panose 020b0604020202020204}Arial;}\n";
  m_t << "{\\f2\\fmodern\\fcharset" << theTranslator->trRTFCharSet();
  m_t << "\\fprq1{\\*\\panose 02070309020205020404}Courier New;}\n";
  m_t << "{\\f3\\froman\\fcharset2\\fprq2{\\*\\panose 05050102010706020507}Symbol;}\n";
  m_t << "}\n";
  DBG_RTF(m_t << "{\\comment begin colors}\n")
  m_t << "{\\colortbl;";
  m_t << "\\red0\\green0\\blue0;";
  m_t << "\\red0\\green0\\blue255;";
  m_t << "\\red0\\green255\\blue255;";
  m_t << "\\red0\\green255\\blue0;";
  m_t << "\\red255\\green0\\blue255;";
  m_t << "\\red255\\green0\\blue0;";
  m_t << "\\red255\\green255\\blue0;";
  m_t << "\\red255\\green255\\blue255;";
  m_t << "\\red0\\green0\\blue128;";
  m_t << "\\red0\\green128\\blue128;";
  m_t << "\\red0\\green128\\blue0;";
  m_t << "\\red128\\green0\\blue128;";
  m_t << "\\red128\\green0\\blue0;";
  m_t << "\\red128\\green128\\blue0;";
  m_t << "\\red128\\green128\\blue128;";
  m_t << "\\red192\\green192\\blue192;";
  // code highlighting colors. Note order is important see also RTFGenerator::startFontClass
  m_t << "\\red0\\green128\\blue0;";   // keyword = index 17
  m_t << "\\red96\\green64\\blue32;";  // keywordtype
  m_t << "\\rede0\\green128\\blue0;";  // keywordflow
  m_t << "\\red128\\green0\\blue0;";   // comment
  m_t << "\\red128\\green96\\blue32;"; // preprocessor
  m_t << "\\red0\\green32\\blue128;";  // stringliteral
  m_t << "\\red0\\green128\\blue128;"; // charliteral
  m_t << "\\red255\\green0\\blue255;"; // vhdldigit
  m_t << "\\red0\\green0\\blue0;";     // vhdlchar
  m_t << "\\red112\\green0\\blue112;"; // vhdlkeyword
  m_t << "\\red255\\green0\\blue0;";   // vhdllogic
  m_t << "}\n";
  DBG_RTF(m_t << "{\\comment Beginning style list}\n")
  m_t << "{\\stylesheet\n";
  m_t << "{\\widctlpar\\adjustright \\fs20\\cgrid \\snext0 Normal;}\n";
  // set the paper dimensions according to PAPER_TYPE
  auto paperType = Config_getEnum(PAPER_TYPE);
  m_t << "{";
  switch (paperType)
  {
    // width & height values are inches * 1440
    case PAPER_TYPE_t::a4:        m_t << "\\paperw11900\\paperh16840"; break;
    case PAPER_TYPE_t::letter:    m_t << "\\paperw12240\\paperh15840"; break;
    case PAPER_TYPE_t::legal:     m_t << "\\paperw12240\\paperh20160"; break;
    case PAPER_TYPE_t::executive: m_t << "\\paperw10440\\paperh15120"; break;
  }
  m_t << "\\margl1800\\margr1800\\margt1440\\margb1440\\gutter0\\ltrsect}\n";
  // sort styles ascending by \s-number via an intermediate QArray
  unsigned maxIndex = 0;
  for (const auto &[name,data] : rtf_Style)
  {
    uint32_t index = data.index();
    if (index > maxIndex) maxIndex = index;
  }
  std::vector<const StyleData*> array(maxIndex + 1, nullptr);
  ASSERT(maxIndex < array.size());
  for (const auto &[name,data] : rtf_Style)
  {
    uint32_t index = data.index();
    if (array[index] != nullptr)
    {
      err("Style '%s' redefines \\s%d.\n", name.c_str(), index);
    }
    array[index] = &data;
  }
  // write array elements
  size_t size = array.size();
  for(size_t i = 0; i < size; i++)
  {
    const StyleData *pStyle = array[i];
    if (pStyle)
    {
      m_t << "{" << pStyle->reference() << pStyle->definition() << ";}\n";
    }
  }
  m_t << "}\n";
  // place to write rtf_Table_Default
  int id = -1;
  m_t << "{\\*\\listtable" << "\n";
  for (int i=0 ; rtf_Table_Default[i].definition ; i++ )
  {
    if (id != rtf_Table_Default[i].id)
    {
      if (id != -1)
      {
        m_t << "\\listid" << id << "}" << "\n";
      }
      id = rtf_Table_Default[i].id;
      m_t << "{\\list\\listtemplateid" << rtf_Table_Default[i].id << "\n";
    }
    m_t << "{ " << rtf_Table_Default[i].definition << " }" << "\n";
  }
  m_t << "\\listid" << id << "}" << "\n";
  m_t << "}" <<"\n";
  m_t << "{\\listoverridetable" <<"\n";
  id = -1;
  for (int i=0 ; rtf_Table_Default[i].definition ; i++ )
  {
    if (id != rtf_Table_Default[i].id)
    {
      id = rtf_Table_Default[i].id;
      m_t << "{\\listoverride\\listid" << id << "\\listoverridecount0\\ls" << id << "}" << "\n";
    }
  }
  m_t << "}" << "\n";
  // this comment is needed for postprocessing!
  m_t << "{\\comment begin body}\n";
}
References ASSERT, Config_getEnum, DBG_RTF, Rtf_Table_Default::definition, StyleData::definition(), err, Rtf_Table_Default::id, OutputGenerator::m_t, StyleData::reference(), rtf_Style, rtf_Table_Default, theTranslator, Translator::trRTFansicp(), and Translator::trRTFCharSet().
Referenced by startFile().
beginRTFSection()
void RTFGenerator::beginRTFSection () private
Definition at line 680 of file rtfgen.cpp.
{
  m_t << "\n";
  DBG_RTF(m_t << "{\\comment BeginRTFSection}\n")
  m_t << rtf_Style_Reset;
  // if we are compact, no extra page breaks...
  if (Config_getBool(COMPACT_RTF))
  {
    m_t << "\\sect\\sbknone\n";
    rtfwriteRuler_emboss();
  }
  else
  {
    m_t << "\\sect\\sbkpage\n";
  }
  int level = 2 + m_hierarchyLevel;
  m_t << rtf_Style[QCString().sprintf("Heading%d", level).str()].reference() << "\n";
}
References Config_getBool, DBG_RTF, m_hierarchyLevel, OutputGenerator::m_t, rtf_Style, rtf_Style_Reset, and rtfwriteRuler_emboss().
Referenced by endIndexSection().
cleanup()
void RTFGenerator::cleanup () override virtual
Implements OutputGenIntf.
Definition at line 516 of file rtfgen.cpp.
{
  QCString dname = Config_getString(RTF_OUTPUT);
  Dir d(dname.str());
  clearSubDirs(d);
}
References clearSubDirs(), Config_getString, and QCString::str().
clearBuffer()
void RTFGenerator::clearBuffer ()
clone()
std::unique_ptr< OutputGenIntf > RTFGenerator::clone () inline override virtual
Implements OutputGenIntf.
Definition at line 102 of file rtfgen.h.
{ return std::make_unique<RTFGenerator>(*this); }
decIndentLevel()
void RTFGenerator::decIndentLevel () private
Definition at line 2046 of file rtfgen.cpp.
{
  m_indentLevel--;
  if (m_indentLevel<0)
  {
    err("Negative indent level while generating RTF output!\n");
    m_indentLevel=0;
  }
  m_codeGen->setIndentLevel(m_indentLevel);
}
References err, m_codeGen, and m_indentLevel.
Referenced by endConstraintList(), endExamples(), endIndent(), endIndexList(), endItemList(), endMemberDescription(), and endMemberGroup().
docify()
void RTFGenerator::docify (const QCString & text) override virtual
Implements OutputGenIntf.
Definition at line 1841 of file rtfgen.cpp.
{
  if (str.isEmpty()) return;
  m_t << docifyToString(str);
  m_omitParagraph = FALSE;
}
References docifyToString(), FALSE, QCString::isEmpty(), m_omitParagraph, and OutputGenerator::m_t.
Referenced by addIndexItem(), endTitleHead(), startConstraintList(), startDescTable(), startExamples(), startParameterDefVal(), startSection(), writeChar(), and writeStartAnnoItem().
endAnonTypeScope()
void RTFGenerator::endAnonTypeScope (int) inline override virtual
Implements OutputGenIntf.
Definition at line 165 of file rtfgen.h.
{}
endBold()
void RTFGenerator::endBold () inline override virtual
Implements OutputGenIntf.
Definition at line 181 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
Referenced by endInlineHeader(), endMemberDoc(), startConstraintList(), and startExamples().
endCallGraph()
void RTFGenerator::endCallGraph (DotCallGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 2370 of file rtfgen.cpp.
{
  newParagraph();
  QCString fn = g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::Rtf,dir(),fileName(),m_relPath,FALSE);
  // display the file
  m_t << "{\n";
  m_t << rtf_Style_Reset << "\n";
  m_t << "\\par\\pard \\qc {\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"";
  QCString imgExt = getDotImageExtension();
  m_t << fn << "." << imgExt;
  m_t << "\" \\\\d \\\\*MERGEFORMAT}{\\fldrslt IMAGE}}\\par\n";
  m_t << "}\n";
  DBG_RTF(m_t << "{\\comment (endCallGraph)}\n")
}
References BITMAP, DBG_RTF, OutputGenerator::dir(), FALSE, OutputGenerator::fileName(), getDotImageExtension(), m_relPath, OutputGenerator::m_t, newParagraph(), Rtf, rtf_Style_Reset, and DotCallGraph::writeGraph().
endCenter()
void RTFGenerator::endCenter () inline override virtual
Implements OutputGenIntf.
Definition at line 193 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endClassDiagram()
void RTFGenerator::endClassDiagram (const ClassDiagram & d, const QCString & filename, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1861 of file rtfgen.cpp.
{
  newParagraph();
  // create a png file
  d.writeImage(m_t,dir(),m_relPath,fileName,FALSE);
  // display the file
  m_t << "{\n";
  m_t << rtf_Style_Reset << "\n";
  m_t << "\\par\\pard \\qc {\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"";
  m_t << fileName << ".png\"";
  m_t << " \\\\d \\\\*MERGEFORMAT}{\\fldrslt IMAGE}}\\par\n";
  m_t << "}\n";
}
References OutputGenerator::dir(), FALSE, OutputGenerator::fileName(), m_relPath, OutputGenerator::m_t, newParagraph(), rtf_Style_Reset, and ClassDiagram::writeImage().
endCompoundTemplateParams()
void RTFGenerator::endCompoundTemplateParams () override virtual
Implements OutputGenIntf.
Definition at line 1509 of file rtfgen.cpp.
{
  newParagraph();
  m_t << "}\n";
}
References OutputGenerator::m_t, and newParagraph().
endConstraintDocs()
void RTFGenerator::endConstraintDocs () override virtual
Implements OutputGenIntf.
Definition at line 2698 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endConstraintDocs)}\n")
  newParagraph();
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
endConstraintList()
void RTFGenerator::endConstraintList () override virtual
Implements OutputGenIntf.
Definition at line 2704 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endConstraintList)}\n")
  newParagraph();
  decIndentLevel();
  m_omitParagraph = TRUE;
  m_t << "}";
}
References DBG_RTF, decIndentLevel(), m_omitParagraph, OutputGenerator::m_t, newParagraph(), and TRUE.
endConstraintParam()
void RTFGenerator::endConstraintParam () override virtual
Implements OutputGenIntf.
Definition at line 2673 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endConstraintParam)}\n")
  endEmphasis();
  m_t << " : ";
}
References DBG_RTF, endEmphasis(), and OutputGenerator::m_t.
endConstraintType()
void RTFGenerator::endConstraintType () override virtual
Implements OutputGenIntf.
Definition at line 2686 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endConstraintType)}\n")
  endEmphasis();
  m_t << " ";
}
References DBG_RTF, endEmphasis(), and OutputGenerator::m_t.
endContents()
void RTFGenerator::endContents () inline override virtual
Implements OutputGenIntf.
Definition at line 225 of file rtfgen.h.
{}
endDescForItem()
void RTFGenerator::endDescForItem () override virtual
Implements OutputGenIntf.
Definition at line 1798 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endDescForItem) }\n")
}
References DBG_RTF, and OutputGenerator::m_t.
endDescTable()
void RTFGenerator::endDescTable () override virtual
Implements OutputGenIntf.
Definition at line 1975 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endDescTable)}\n")
  m_t << "}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
endDescTableData()
void RTFGenerator::endDescTableData () override virtual
Implements OutputGenIntf.
Definition at line 2022 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endDescTableData) }\n")
  m_t << "\\cell }{\\row }\n";
}
References DBG_RTF, and OutputGenerator::m_t.
endDescTableInit()
void RTFGenerator::endDescTableInit () override virtual
Implements OutputGenIntf.
Definition at line 2010 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endDescTableInit) }"    << endl)
  m_t << "\\cell }";
}
References DBG_RTF, and OutputGenerator::m_t.
endDescTableRow()
void RTFGenerator::endDescTableRow () override virtual
Implements OutputGenIntf.
Definition at line 1985 of file rtfgen.cpp.
{
}
endDescTableTitle()
void RTFGenerator::endDescTableTitle () override virtual
Implements OutputGenIntf.
Definition at line 1996 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endDescTableTitle) }\n")
  m_t << "\\cell }";
}
References DBG_RTF, and OutputGenerator::m_t.
endDirDepGraph()
void RTFGenerator::endDirDepGraph (DotDirDeps & g) override virtual
Implements OutputGenIntf.
Definition at line 2392 of file rtfgen.cpp.
{
  newParagraph();
  QCString fn = g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::Rtf,dir(),fileName(),m_relPath,FALSE);
  // display the file
  m_t << "{\n";
  m_t << rtf_Style_Reset << "\n";
  m_t << "\\par\\pard \\qc {\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"";
  QCString imgExt = getDotImageExtension();
  m_t << fn << "." << imgExt;
  m_t << "\" \\\\d \\\\*MERGEFORMAT}{\\fldrslt IMAGE}}\\par\n";
  m_t << "}\n";
  DBG_RTF(m_t << "{\\comment (endDirDepGraph)}\n")
}
References BITMAP, DBG_RTF, OutputGenerator::dir(), FALSE, OutputGenerator::fileName(), getDotImageExtension(), m_relPath, OutputGenerator::m_t, newParagraph(), Rtf, rtf_Style_Reset, and DotDirDeps::writeGraph().
endDotGraph()
void RTFGenerator::endDotGraph (DotClassGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 2317 of file rtfgen.cpp.
{
  newParagraph();
  QCString fn = g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::Rtf,dir(),fileName(),m_relPath,TRUE,FALSE);
  // display the file
  m_t << "{\n";
  m_t << rtf_Style_Reset << "\n";
  m_t << "\\par\\pard \\qc {\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"";
  QCString imgExt = getDotImageExtension();
  m_t << fn << "." << imgExt;
  m_t << "\" \\\\d \\\\*MERGEFORMAT}{\\fldrslt IMAGE}}\\par\n";
  m_t << "}\n";
  newParagraph();
  DBG_RTF(m_t << "{\\comment (endDotGraph)}\n")
}
References BITMAP, DBG_RTF, OutputGenerator::dir(), FALSE, OutputGenerator::fileName(), getDotImageExtension(), m_relPath, OutputGenerator::m_t, newParagraph(), Rtf, rtf_Style_Reset, TRUE, and DotClassGraph::writeGraph().
endDoxyAnchor()
void RTFGenerator::endDoxyAnchor (const QCString & fName, const QCString & anchor) override virtual
Implements OutputGenIntf.
Definition at line 1716 of file rtfgen.cpp.
{
  QCString ref;
  if (!fName.isEmpty())
  {
    ref+=stripPath(fName);
  }
  if (!anchor.isEmpty())
  {
    ref+='_';
    ref+=anchor;
  }
  DBG_RTF(m_t << "{\\comment endDoxyAnchor}\n")
  m_t << "{\\bkmkstart ";
  m_t << rtfFormatBmkStr(ref);
  m_t << "}\n";
  m_t << "{\\bkmkend ";
  m_t << rtfFormatBmkStr(ref);
  m_t << "}\n";
}
References DBG_RTF, QCString::isEmpty(), OutputGenerator::m_t, rtfFormatBmkStr(), and stripPath().
endEmphasis()
void RTFGenerator::endEmphasis () inline override virtual
Implements OutputGenIntf.
Definition at line 179 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
Referenced by endConstraintParam(), endConstraintType(), endMemberDescription(), endMemberGroupDocs(), and endPageRef().
endExamples()
void RTFGenerator::endExamples () override virtual
Implements OutputGenIntf.
Definition at line 2578 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endExamples)}\n")
  m_omitParagraph = FALSE;
  newParagraph();
  decIndentLevel();
  m_omitParagraph = TRUE;
  m_t << "}";
}
References DBG_RTF, decIndentLevel(), FALSE, m_omitParagraph, OutputGenerator::m_t, newParagraph(), and TRUE.
endFile()
void RTFGenerator::endFile () override virtual
Implements OutputGenIntf.
Definition at line 715 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endFile}\n")
  m_t << "}";
  endPlainFile();
  setSourceFileName("");
}
References DBG_RTF, endPlainFile(), OutputGenerator::m_t, and setSourceFileName().
endGroupCollaboration()
void RTFGenerator::endGroupCollaboration (DotGroupCollaboration & g) override virtual
Implements OutputGenIntf.
Definition at line 2361 of file rtfgen.cpp.
{
}
endGroupHeader()
void RTFGenerator::endGroupHeader (int) override virtual
Implements OutputGenIntf.
Definition at line 1660 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endGroupHeader}\n")
  m_t << "\\par\n";
  m_t << rtf_Style_Reset << "\n";
}
References DBG_RTF, OutputGenerator::m_t, and rtf_Style_Reset.
Referenced by endMemberHeader().
endHeaderSection()
void RTFGenerator::endHeaderSection () inline override virtual
Implements OutputGenIntf.
Definition at line 153 of file rtfgen.h.
{}
endInclDepGraph()
void RTFGenerator::endInclDepGraph (DotInclDepGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 2340 of file rtfgen.cpp.
{
  newParagraph();
  QCString fn = g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::Rtf,dir(),fileName(),m_relPath,FALSE);
  // display the file
  m_t << "{\n";
  m_t << rtf_Style_Reset << "\n";
  m_t << "\\par\\pard \\qc {\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"";
  QCString imgExt = getDotImageExtension();
  m_t << fn << "." << imgExt;
  m_t << "\" \\\\d \\\\*MERGEFORMAT}{\\fldrslt IMAGE}}\\par\n";
  m_t << "}\n";
  DBG_RTF(m_t << "{\\comment (endInclDepGraph)}\n")
}
References BITMAP, DBG_RTF, OutputGenerator::dir(), FALSE, OutputGenerator::fileName(), getDotImageExtension(), m_relPath, OutputGenerator::m_t, newParagraph(), Rtf, rtf_Style_Reset, and DotInclDepGraph::writeGraph().
endIndent()
void RTFGenerator::endIndent () override virtual
Implements OutputGenIntf.
Definition at line 1767 of file rtfgen.cpp.
{
  m_t << "}\n";
  decIndentLevel();
}
References decIndentLevel(), and OutputGenerator::m_t.
endIndexItem()
void RTFGenerator::endIndexItem (const QCString & ref, const QCString & file) override virtual
Implements OutputGenIntf.
Definition at line 1422 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endIndexItem)}\n")
  if (ref.isEmpty() && !fn.isEmpty())
  {
    m_t << "\\tab ";
    writeRTFReference(fn);
    m_t << "\n";
  }
  else
  {
    m_t << "\n";
  }
  m_omitParagraph = TRUE;
}
References DBG_RTF, QCString::isEmpty(), m_omitParagraph, OutputGenerator::m_t, TRUE, and writeRTFReference().
endIndexKey()
void RTFGenerator::endIndexKey () override virtual
Implements OutputGenIntf.
Definition at line 1468 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endIndexKey)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
endIndexList()
void RTFGenerator::endIndexList () override virtual
Implements OutputGenIntf.
Definition at line 1351 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endIndexList)}\n")
  if (!m_omitParagraph)
  {
    m_t << "\\par";
    m_omitParagraph = TRUE;
  }
  m_t << "}";
  decIndentLevel();
}
References DBG_RTF, decIndentLevel(), m_omitParagraph, OutputGenerator::m_t, and TRUE.
endIndexListItem()
void RTFGenerator::endIndexListItem () override virtual
Implements OutputGenIntf.
Definition at line 2718 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endIndexListItem)}\n")
  m_t << "\\par\n";
}
References DBG_RTF, and OutputGenerator::m_t.
endIndexSection()
void RTFGenerator::endIndexSection (IndexSection is) override virtual
Implements OutputGenIntf.
Definition at line 924 of file rtfgen.cpp.
{
  bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  bool vhdlOpt    = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  QCString projectName = Config_getString(PROJECT_NAME);
  switch (is)
  {
    case IndexSection::isTitlePageStart:
      if (!rtf_title.isEmpty())
        // User has overridden document title in extensions file
        m_t << "}" << rtf_title;
      else
        m_t << "}" << projectName;
      break;
    case IndexSection::isTitlePageAuthor:
      {
        m_t << " doxygen " << getDoxygenVersion() << ".}\n";
        m_t << dateToRTFDateString();
        DBG_RTF(m_t << "{\\comment end of infoblock}\n");
        // setup for this section
        m_t << "}";
        m_t << rtf_Style_Reset <<"\n";
        m_t << "\\sectd\\pgnlcrm\n";
        m_t << "{\\footer "<<rtf_Style["Footer"].reference() << "{\\chpgn}}\n";
        // the title entry
        DBG_RTF(m_t << "{\\comment begin title page}\n")
        m_t << rtf_Style_Reset << rtf_Style["SubTitle"].reference() << "\n"; // set to title style
        m_t << "\\vertalc\\qc\\par\\par\\par\\par\\par\\par\\par\n";
        if (!rtf_logoFilename.isEmpty())
        {
          m_t << "{\\field\\flddirty {\\*\\fldinst INCLUDEPICTURE \"" << rtf_logoFilename;
          m_t << "\" \\\\d \\\\*MERGEFORMAT} {\\fldrslt IMAGE }}\\par\\par\n";
        }
        if (!rtf_company.isEmpty())
        {
          m_t << rtf_company << "\\par\\par\n";
        }
        m_t << rtf_Style_Reset << rtf_Style["Title"].reference() << "\n"; // set to title style
        if (!rtf_title.isEmpty())
        {
          // User has overridden document title in extensions file
          m_t << "{\\field\\fldedit {\\*\\fldinst TITLE \\\\*MERGEFORMAT}{\\fldrslt " << rtf_title << "}}\\par\n";
        }
        else
        {
          auto parser { createDocParser() };
          auto ast    { validatingParseText(*parser.get(), projectName) };
          if (ast)
          {
            m_t << "{\\field\\fldedit {\\*\\fldinst TITLE \\\\*MERGEFORMAT}{\\fldrslt ";
            writeDoc(ast.get(),nullptr,nullptr,0);
            m_t << "}}\\par\n";
          }
        }
        m_t << rtf_Style_Reset << rtf_Style["SubTitle"].reference() << "\n"; // set to title style
        m_t << "\\par\n";
        if (!rtf_documentType.isEmpty())
        {
          m_t << rtf_documentType << "\\par\n";
        }
        if (!rtf_documentId.isEmpty())
        {
          m_t << rtf_documentId << "\\par\n";
        }
        m_t << "\\par\\par\\par\\par\\par\\par\\par\\par\\par\\par\\par\\par\n";
        m_t << rtf_Style_Reset << rtf_Style["SubTitle"].reference() << "\n"; // set to subtitle style
        if (!rtf_author.isEmpty())
        {
          m_t << "{\\field\\fldedit {\\*\\fldinst AUTHOR \\\\*MERGEFORMAT}{\\fldrslt "<< rtf_author << " }}\\par\n";
        }
        else
        {
          m_t << "{\\field\\fldedit {\\*\\fldinst AUTHOR \\\\*MERGEFORMAT}{\\fldrslt AUTHOR}}\\par\n";
        }
        m_t << theTranslator->trVersion() << " " << Config_getString(PROJECT_NUMBER) << "\\par";
        switch (Config_getEnum(TIMESTAMP))
        {
          case TIMESTAMP_t::YES:
          case TIMESTAMP_t::DATETIME:
            m_t << "{\\field\\fldedit {\\*\\fldinst CREATEDATE \\\\*MERGEFORMAT}"
              "{\\fldrslt "<< dateToString(DateTimeType::DateTime) << " }}\\par\n";
            break;
          case TIMESTAMP_t::DATE:
            m_t << "{\\field\\fldedit {\\*\\fldinst CREATEDATE \\\\*MERGEFORMAT}"
              "{\\fldrslt "<< dateToString(DateTimeType::Date) << " }}\\par\n";
            break;
          case TIMESTAMP_t::NO:
            break;
        }
        m_t << "\\page\\page";
        DBG_RTF(m_t << "{\\comment End title page}\n")
        // table of contents section
        DBG_RTF(m_t << "{\\comment Table of contents}\n")
        m_t << "\\vertalt\n";
        m_t << rtf_Style_Reset << "\n";
        m_t << rtf_Style["Heading1"].reference();
        m_t << theTranslator->trRTFTableOfContents() << "\\par\n";
        m_t << rtf_Style_Reset << "\\par\n";
        m_t << "{\\field\\fldedit {\\*\\fldinst TOC \\\\f \\\\*MERGEFORMAT}{\\fldrslt Table of contents}}\\par\n";
        m_t << rtf_Style_Reset << "\n";
      }
      break;
    case IndexSection::isMainPage:
      if (Doxygen::mainPage)
      {
        writePageLink(Doxygen::mainPage->getOutputFileBase(), TRUE);
      }
      break;
    case IndexSection::isTopicIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trTopicIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"topics.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case IndexSection::isModuleIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trModuleIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"modules.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case IndexSection::isDirIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trDirIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"dirs.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case IndexSection::isNamespaceIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      if (fortranOpt)
      {
          m_t << "{\\tc \\v " << theTranslator->trModulesIndex() << "}\n";
      }
      else
      {
          m_t << "{\\tc \\v " << theTranslator->trNamespaceIndex() << "}\n";
      }
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"namespaces.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case IndexSection::isConceptIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trConceptIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"concepts.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case IndexSection::isClassHierarchyIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trHierarchicalIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"hierarchy.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case IndexSection::isCompoundIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      if (fortranOpt)
      {
        m_t << "{\\tc \\v " << theTranslator->trCompoundIndexFortran() << "}\n";
      }
      else if (vhdlOpt)
      {
        m_t << "{\\tc \\v " << theTranslator->trDesignUnitIndex() << "}\n";
      }
      else
      {
        m_t << "{\\tc \\v " << theTranslator->trCompoundIndex() << "}\n";
      }
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"annotated.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case IndexSection::isFileIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trFileIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"files.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case IndexSection::isPageIndex:
      m_t << "\\par " << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trPageIndex() << "}\n";
      m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"pages.rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
      break;
    case IndexSection::isTopicDocumentation:
      {
        m_t << "{\\tc \\v " << theTranslator->trTopicDocumentation() << "}\n";
        for (const auto &gd : *Doxygen::groupLinkedMap)
        {
          if (!gd->isReference() && !gd->isASubGroup())
          {
            writePageLink(gd->getOutputFileBase(), FALSE);
          }
        }
      }
      break;
    case IndexSection::isModuleDocumentation:
      {
        m_t << "{\\tc \\v " << theTranslator->trModuleDocumentation() << "}\n";
        for (const auto &mod : ModuleManager::instance().modules())
        {
          if (!mod->isReference() && mod->isPrimaryInterface())
          {
            writePageLink(mod->getOutputFileBase(), FALSE);
          }
        }
      }
      break;
    case IndexSection::isDirDocumentation:
      {
        bool first=true;
        m_t << "{\\tc \\v " << theTranslator->trDirDocumentation() << "}\n";
        for (const auto &dd : *Doxygen::dirLinkedMap)
        {
          if (dd->isLinkableInProject())
          {
            m_t << "\\par " << rtf_Style_Reset << "\n";
            if (!first)
            {
              beginRTFSection();
            }
            first=false;
            m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
            m_t << dd->getOutputFileBase();
            m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
          }
        }
      }
      break;
    case IndexSection::isNamespaceDocumentation:
      {
        bool first=true;
        for (const auto &nd : *Doxygen::namespaceLinkedMap)
        {
          if (nd->isLinkableInProject() && !nd->isAlias())
          {
            m_t << "\\par " << rtf_Style_Reset << "\n";
            if (!first)
            {
              beginRTFSection();
            }
            first=false;
            m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
            m_t << nd->getOutputFileBase();
            m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
          }
        }
      }
      break;
    case IndexSection::isConceptDocumentation:
      {
        bool first=true;
        for (const auto &cd : *Doxygen::conceptLinkedMap)
        {
          if (cd->isLinkableInProject() && !cd->isAlias())
          {
            m_t << "\\par " << rtf_Style_Reset << "\n";
            if (!first)
            {
              beginRTFSection();
            }
            first=false;
            m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
            m_t << cd->getOutputFileBase();
            m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
          }
        }
      }
      break;
    case IndexSection::isClassDocumentation:
      {
        bool first=true;
        if (fortranOpt)
        {
          m_t << "{\\tc \\v " << theTranslator->trTypeDocumentation() << "}\n";
        }
        else
        {
          m_t << "{\\tc \\v " << theTranslator->trClassDocumentation() << "}\n";
        }
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->isLinkableInProject() &&
              cd->templateMaster()==nullptr &&
             !cd->isEmbeddedInOuterScope() &&
             !cd->isAlias()
             )
          {
            m_t << "\\par " << rtf_Style_Reset << "\n";
            if (!first)
            {
              beginRTFSection();
            }
            first=false;
            m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
            m_t << cd->getOutputFileBase();
            m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
          }
        }
      }
      break;
    case IndexSection::isFileDocumentation:
      {
        bool isFirst=TRUE;
        m_t << "{\\tc \\v " << theTranslator->trFileDocumentation() << "}\n";
        for (const auto &fn : *Doxygen::inputNameLinkedMap)
        {
          for (const auto &fd : *fn)
          {
            if (fd->isLinkableInProject())
            {
              m_t << "\\par " << rtf_Style_Reset << "\n";
              if (!isFirst)
              {
                beginRTFSection();
              }
              isFirst=FALSE;
              m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
              m_t << fd->getOutputFileBase();
              m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
            }
            if (fd->generateSourceFile())
            {
              m_t << "\\par " << rtf_Style_Reset << "\n";
              if (!isFirst)
              {
                beginRTFSection();
              }
              isFirst=FALSE;
              m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
              m_t << fd->getSourceFileBase();
              m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
            }
          }
        }
      }
      break;
    case IndexSection::isExampleDocumentation:
      {
        //m_t << "}\n";
        bool isFirst=true;
        m_t << "{\\tc \\v " << theTranslator->trExamples() << "}\n";
        for (const auto &pd : *Doxygen::exampleLinkedMap)
        {
          m_t << "\\par " << rtf_Style_Reset << "\n";
          if (!isFirst)
          {
            beginRTFSection();
          }
          isFirst=false;
          m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
          m_t << pd->getOutputFileBase();
          m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
        }
      }
      break;
    case IndexSection::isPageDocumentation:
      {
        m_t << "\\par " << rtf_Style_Reset << "\n";
        for (const auto &pd : *Doxygen::pageLinkedMap)
        {
          if (!pd->getGroupDef() && !pd->isReference() && !pd->hasParentPage()
            && Doxygen::mainPage.get() != pd.get())
          {
            writePageLink(pd->getOutputFileBase(), FALSE);
          }
        }
      }
      break;
    case IndexSection::isPageDocumentation2:
      break;
    case IndexSection::isEndIndex:
      beginRTFChapter();
      m_t << rtf_Style["Heading1"].reference();
      m_t << theTranslator->trRTFGeneralIndex() << "\\par \n";
      m_t << rtf_Style_Reset << "\n";
      m_t << "{\\tc \\v " << theTranslator->trRTFGeneralIndex() << "}\n";
      m_t << "{\\field\\fldedit {\\*\\fldinst INDEX \\\\c2 \\\\*MERGEFORMAT}{\\fldrslt INDEX}}\n";
      break;
   }
}
References beginRTFChapter(), beginRTFSection(), Doxygen::classLinkedMap, Doxygen::conceptLinkedMap, Config_getBool, Config_getEnum, Config_getString, createDocParser(), Date, DateTime, dateToRTFDateString(), dateToString(), DBG_RTF, Doxygen::dirLinkedMap, Doxygen::exampleLinkedMap, FALSE, Doxygen::groupLinkedMap, Doxygen::inputNameLinkedMap, ModuleManager::instance(), isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, QCString::isEmpty(), isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, isTopicDocumentation, isTopicIndex, OutputGenerator::m_t, Doxygen::mainPage, Doxygen::namespaceLinkedMap, Doxygen::pageLinkedMap, rtf_author, rtf_company, rtf_documentId, rtf_documentType, rtf_logoFilename, rtf_Style, rtf_Style_Reset, rtf_title, theTranslator, Translator::trClassDocumentation(), Translator::trCompoundIndex(), Translator::trCompoundIndexFortran(), Translator::trConceptIndex(), Translator::trDesignUnitIndex(), Translator::trDirDocumentation(), Translator::trDirIndex(), Translator::trExamples(), Translator::trFileDocumentation(), Translator::trFileIndex(), Translator::trHierarchicalIndex(), Translator::trModuleDocumentation(), Translator::trModuleIndex(), Translator::trModulesIndex(), Translator::trNamespaceIndex(), Translator::trPageIndex(), Translator::trRTFGeneralIndex(), Translator::trRTFTableOfContents(), Translator::trTopicDocumentation(), Translator::trTopicIndex(), Translator::trTypeDocumentation(), TRUE, Translator::trVersion(), validatingParseText(), writeDoc(), and writePageLink().
endIndexValue()
void RTFGenerator::endIndexValue (const QCString & name, bool hasBrief) override virtual
Implements OutputGenIntf.
Definition at line 1480 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endIndexValue)}\n")
  if (hasBrief) m_t << ")";
  m_t << "} ";
  if (!name.isEmpty())
  {
    m_t << "\\tab ";
    writeRTFReference(name);
    m_t << "\n";
  }
  else
  {
    m_t << "\n";
  }
  m_omitParagraph=FALSE;
  newParagraph();
}
References DBG_RTF, FALSE, QCString::isEmpty(), m_omitParagraph, OutputGenerator::m_t, newParagraph(), and writeRTFReference().
endInlineHeader()
void RTFGenerator::endInlineHeader () override virtual
Implements OutputGenIntf.
Definition at line 2732 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endInlineHeader)}\n")
  endBold();
  m_t << "\\par";
  m_t << "}\n";
}
References DBG_RTF, endBold(), and OutputGenerator::m_t.
endInlineMemberDoc()
void RTFGenerator::endInlineMemberDoc () override virtual
Implements OutputGenIntf.
Definition at line 2817 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endInlineMemberDoc)}\n")
  m_t << "\\cell }{\\row }\n";
}
References DBG_RTF, and OutputGenerator::m_t.
endInlineMemberName()
void RTFGenerator::endInlineMemberName () override virtual
Implements OutputGenIntf.
Definition at line 2805 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endInlineMemberName)}\n")
  m_t << "\\cell }";
}
References DBG_RTF, and OutputGenerator::m_t.
endInlineMemberType()
void RTFGenerator::endInlineMemberType () override virtual
Implements OutputGenIntf.
Definition at line 2793 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endInlineMemberType)}\n")
  m_t << "\\cell }";
}
References DBG_RTF, and OutputGenerator::m_t.
endItemList()
void RTFGenerator::endItemList () override virtual
end bullet list
Implements OutputGenIntf.
Definition at line 1377 of file rtfgen.cpp.
{
  newParagraph();
  DBG_RTF(m_t << "{\\comment (endItemList level=" << indentLevel() << ")}\n")
  m_t << "}";
  decIndentLevel();
  m_omitParagraph = TRUE;
}
References DBG_RTF, decIndentLevel(), indentLevel(), m_omitParagraph, OutputGenerator::m_t, newParagraph(), and TRUE.
endItemListItem()
void RTFGenerator::endItemListItem () override virtual
Implements OutputGenIntf.
Definition at line 1406 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endItemListItem)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
endLabels()
void RTFGenerator::endLabels () override virtual
Implements OutputGenIntf.
Definition at line 2833 of file rtfgen.cpp.
{
}
endMemberDeclaration()
void RTFGenerator::endMemberDeclaration (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 200 of file rtfgen.h.
{}
endMemberDescription()
void RTFGenerator::endMemberDescription () override virtual
Implements OutputGenIntf.
Definition at line 1783 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endMemberDescription)}\n")
  endEmphasis();
  decIndentLevel();
  m_t << "\\par";
  m_t << "}\n";
  m_omitParagraph = TRUE;
}
References DBG_RTF, decIndentLevel(), endEmphasis(), m_omitParagraph, OutputGenerator::m_t, and TRUE.
endMemberDoc()
void RTFGenerator::endMemberDoc (bool) override virtual
Implements OutputGenIntf.
Definition at line 1697 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberDoc}\n")
  //const QCString &style = styleStack.pop();
  //printf("RTFGenerator::endMemberDoc() '%s'\n",style);
  //ASSERT(style==rtf_Style["Heading4"].reference());
  endBold();
  m_t << "}\n";
  newParagraph();
}
References DBG_RTF, endBold(), OutputGenerator::m_t, and newParagraph().
endMemberDocList()
void RTFGenerator::endMemberDocList () inline override virtual
Implements OutputGenIntf.
Definition at line 159 of file rtfgen.h.
{}
endMemberDocName()
void RTFGenerator::endMemberDocName () inline override virtual
Implements OutputGenIntf.
Definition at line 265 of file rtfgen.h.
{}
endMemberDocPrefixItem()
void RTFGenerator::endMemberDocPrefixItem () inline override virtual
Implements OutputGenIntf.
Definition at line 263 of file rtfgen.h.
{}
endMemberDocSimple()
void RTFGenerator::endMemberDocSimple (bool) override virtual
Implements OutputGenIntf.
Definition at line 2781 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endMemberDocSimple)}\n")
  m_t << "}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
endMemberGroup()
void RTFGenerator::endMemberGroup (bool hasHeader) override virtual
Implements OutputGenIntf.
Definition at line 2556 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberGroup}\n")
  if (hasHeader) decIndentLevel();
  m_t << "}";
}
References DBG_RTF, decIndentLevel(), and OutputGenerator::m_t.
endMemberGroupDocs()
void RTFGenerator::endMemberGroupDocs () override virtual
Implements OutputGenIntf.
Definition at line 2543 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberGroupDocs}\n")
  endEmphasis();
  newParagraph();
}
References DBG_RTF, endEmphasis(), OutputGenerator::m_t, and newParagraph().
endMemberGroupHeader()
void RTFGenerator::endMemberGroupHeader () override virtual
Implements OutputGenIntf.
Definition at line 2530 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberGroupHeader}\n")
  newParagraph();
  m_t << rtf_Style_Reset << rtf_CList_DepthStyle();
}
References DBG_RTF, OutputGenerator::m_t, newParagraph(), rtf_CList_DepthStyle(), and rtf_Style_Reset.
endMemberHeader()
void RTFGenerator::endMemberHeader () inline override virtual
Implements OutputGenIntf.
Definition at line 155 of file rtfgen.h.
{ endGroupHeader(FALSE); }
References endGroupHeader(), and FALSE.
endMemberItem()
void RTFGenerator::endMemberItem (MemberItemType) override virtual
Implements OutputGenIntf.
Definition at line 1884 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberItem }\n")
  newParagraph();
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
endMemberList()
void RTFGenerator::endMemberList () override virtual
Implements OutputGenIntf.
Definition at line 1936 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endMemberList) }\n")
  m_t << "}\n";
#ifdef DELETEDCODE
  if (!insideTabbing)
    m_t << "\\end{CompactItemize}\n";
#endif
}
References DBG_RTF, and OutputGenerator::m_t.
endMemberSections()
void RTFGenerator::endMemberSections () inline override virtual
Implements OutputGenIntf.
Definition at line 151 of file rtfgen.h.
{}
endMemberSubtitle()
void RTFGenerator::endMemberSubtitle () override virtual
Implements OutputGenIntf.
Definition at line 2146 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endMemberSubtitle}\n")
  newParagraph();
  m_t << "}\n";
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
endMemberTemplateParams()
void RTFGenerator::endMemberTemplateParams (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 169 of file rtfgen.h.
{}
endPageDoc()
void RTFGenerator::endPageDoc () inline override virtual
Implements OutputGenIntf.
Definition at line 113 of file rtfgen.h.
{}
endPageRef()
void RTFGenerator::endPageRef (const QCString & clname, const QCString & anchor) override virtual
Implements OutputGenIntf.
Definition at line 1592 of file rtfgen.cpp.
{
  QCString ref;
  if (!clname.isEmpty())
  {
    ref+=clname;
  }
  if (!anchor.isEmpty())
  {
    ref+='_';
    ref+=anchor;
  }
  writeRTFReference(ref);
  endEmphasis();
  m_t << ")";
}
References endEmphasis(), QCString::isEmpty(), OutputGenerator::m_t, and writeRTFReference().
endParagraph()
void RTFGenerator::endParagraph () override virtual
Implements OutputGenIntf.
Definition at line 2132 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endParagraph}\n")
  m_t << "}\\par\n";
  m_omitParagraph = TRUE;
}
References DBG_RTF, m_omitParagraph, OutputGenerator::m_t, and TRUE.
endParameterDefVal()
void RTFGenerator::endParameterDefVal () inline override virtual
Implements OutputGenIntf.
Definition at line 273 of file rtfgen.h.
{ endTypewriter(); }
References endTypewriter().
endParameterExtra()
void RTFGenerator::endParameterExtra (bool last, bool , bool closeBracket) override virtual
Implements OutputGenIntf.
Definition at line 2855 of file rtfgen.cpp.
{
  if (last && closeBracket)
  {
    m_t << ")";
  }
}
References OutputGenerator::m_t.
endParameterList()
void RTFGenerator::endParameterList () inline override virtual
Implements OutputGenIntf.
Definition at line 275 of file rtfgen.h.
{}
endParameterName()
void RTFGenerator::endParameterName () inline override virtual
Implements OutputGenIntf.
Definition at line 269 of file rtfgen.h.
{}
endParameterType()
void RTFGenerator::endParameterType () override virtual
Implements OutputGenIntf.
Definition at line 2597 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endParameterType)}\n")
  m_t << " ";
}
References DBG_RTF, and OutputGenerator::m_t.
endPlainFile()
void RTFGenerator::endPlainFile () inline override virtual
Implements OutputGenIntf.
Definition at line 303 of file rtfgen.h.
{ OutputGenerator::endPlainFile(); }
References OutputGenerator::endPlainFile().
Referenced by endFile().
endProjectNumber()
void RTFGenerator::endProjectNumber () override virtual
Implements OutputGenIntf.
Definition at line 730 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endProjectNumber }\n")
}
References DBG_RTF, and OutputGenerator::m_t.
endQuickIndices()
void RTFGenerator::endQuickIndices () inline override virtual
Implements OutputGenIntf.
Definition at line 218 of file rtfgen.h.
{}
endSection()
void RTFGenerator::endSection (const QCString & lab, SectionType) override virtual
Implements OutputGenIntf.
Definition at line 1831 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (endSection)}\n")
  // make bookmark
  m_omitParagraph=FALSE;
  newParagraph();
  writeAnchor(QCString(),lab);
  m_t << "}";
}
References DBG_RTF, FALSE, m_omitParagraph, OutputGenerator::m_t, newParagraph(), and writeAnchor().
endSmall()
void RTFGenerator::endSmall () inline override virtual
Implements OutputGenIntf.
Definition at line 195 of file rtfgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endTextBlock()
void RTFGenerator::endTextBlock (bool) override virtual
Implements OutputGenIntf.
Definition at line 2106 of file rtfgen.cpp.
{
  newParagraph();
  DBG_RTF(m_t << "{\\comment endTextBlock}\n")
  m_t << "}\n";
  //m_omitParagraph = TRUE;
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
endTextLink()
void RTFGenerator::endTextLink () override virtual
Implements OutputGenIntf.
Definition at line 1537 of file rtfgen.cpp.
{
  if (Config_getBool(RTF_HYPERLINKS))
  {
    m_t << "}}}\n";
  }
}
References Config_getBool, and OutputGenerator::m_t.
endTitleHead()
void RTFGenerator::endTitleHead (const QCString & fileName, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1619 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment endTitleHead}\n")
  m_t << "\\par " << rtf_Style_Reset << "\n";
  if (!name.isEmpty())
  {
    // make table of contents entry
    int level = 2 + m_hierarchyLevel;
    m_t << "{\\tc\\tcl" << level << " \\v ";
    docify(name);
    m_t << "}\n";
    // make an index entry
    addIndexItem(name,QCString());
  }
  if (!fileName.isEmpty())
  {
    writeAnchor(fileName,QCString());
  }
}
References addIndexItem(), DBG_RTF, docify(), OutputGenerator::fileName(), QCString::isEmpty(), m_hierarchyLevel, OutputGenerator::m_t, rtf_Style_Reset, and writeAnchor().
endTypewriter()
void RTFGenerator::endTypewriter () inline override virtual
Implements OutputGenIntf.
Definition at line 144 of file rtfgen.h.
{ m_t << "}";      }
References OutputGenerator::m_t.
Referenced by endParameterDefVal().
exceptionEntry()
void RTFGenerator::exceptionEntry (const QCString & prefix, bool closeBracket) override virtual
Implements OutputGenIntf.
Definition at line 2603 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (exceptionEntry)}\n")
  if (!prefix.isEmpty())
  {
    m_t << " " << prefix << "(";
  }
  else if (closeBracket)
  {
    m_t << ")";
  }
  m_t << " ";
}
References DBG_RTF, OutputGenerator::m_t, and prefix.
incIndentLevel()
void RTFGenerator::incIndentLevel () private
Definition at line 2035 of file rtfgen.cpp.
{
  m_indentLevel++;
  if (m_indentLevel>=maxIndentLevels)
  {
    m_indentLevel = maxIndentLevels-1;
    err("Maximum indent level (%d) exceeded while generating RTF output!\n",maxIndentLevels);
  }
  m_codeGen->setIndentLevel(m_indentLevel);
}
References err, m_codeGen, m_indentLevel, and maxIndentLevels.
Referenced by startConstraintList(), startExamples(), startIndent(), startIndexList(), startItemList(), startMemberDescription(), and startMemberGroupHeader().
indentLevel()
int RTFGenerator::indentLevel () const private
Definition at line 2030 of file rtfgen.cpp.
{
  return std::min(m_indentLevel,maxIndentLevels-1);
}
References m_indentLevel, and maxIndentLevels.
Referenced by endItemList(), rtf_BList_DepthStyle(), rtf_CList_DepthStyle(), rtf_DList_DepthStyle(), rtf_EList_DepthStyle(), rtf_LCList_DepthStyle(), startItemList(), and startItemListItem().
init()
void RTFGenerator::init () static
Definition at line 458 of file rtfgen.cpp.
{
  QCString dir=Config_getString(RTF_OUTPUT);
  Dir d(dir.str());
  if (!d.exists() && !d.mkdir(dir.str()))
  {
    term("Could not create output directory %s\n",qPrint(dir));
  }
  // first duplicate strings of rtf_Style_Default
  const struct Rtf_Style_Default* def = rtf_Style_Default;
  while (def->reference)
  {
    if (def->definition == nullptr)
    {
      err("Internal: rtf_Style_Default[%s] has no definition.\n", def->name);
    }
    else
    {
      rtf_Style.emplace(def->name, StyleData(def->reference, def->definition));
    }
    def++;
  }
  // overwrite some (or all) definitions from file
  QCString rtfStyleSheetFile = Config_getString(RTF_STYLESHEET_FILE);
  if (!rtfStyleSheetFile.isEmpty())
  {
    loadStylesheet(rtfStyleSheetFile, rtf_Style);
  }
  // If user has defined an extension file, load its contents.
  QCString rtfExtensionsFile = Config_getString(RTF_EXTENSIONS_FILE);
  if (!rtfExtensionsFile.isEmpty())
  {
    loadExtensions(rtfExtensionsFile);
    if (!rtf_logoFilename.isEmpty())
    {
      FileInfo fi(rtf_logoFilename.str());
      if (!fi.exists())
      {
        err("Logo '%s' specified by 'LogoFilename' in the rtf extension file '%s' does not exist!\n",
            qPrint(rtf_logoFilename), qPrint(rtfExtensionsFile));
        rtf_logoFilename = "";
      }
      else
      {
        QCString destFileName = Config_getString(RTF_OUTPUT)+"/"+fi.fileName();
        copyFile(rtf_logoFilename,destFileName);
        rtf_logoFilename = fi.fileName();
      }
    }
  }
  createSubDirs(d);
}
References Config_getString, copyFile(), createSubDirs(), Rtf_Style_Default::definition, OutputGenerator::dir(), err, Dir::exists(), FileInfo::exists(), FileInfo::fileName(), QCString::isEmpty(), loadExtensions(), loadStylesheet(), Dir::mkdir(), Rtf_Style_Default::name, qPrint(), Rtf_Style_Default::reference, rtf_logoFilename, rtf_Style, rtf_Style_Default, QCString::str(), and term.
Referenced by generateOutput().
insertMemberAlign()
void RTFGenerator::insertMemberAlign (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 172 of file rtfgen.h.
{}
insertMemberAlignLeft()
void RTFGenerator::insertMemberAlignLeft (MemberItemType , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 173 of file rtfgen.h.
{}
lastIndexPage()
void RTFGenerator::lastIndexPage () override virtual
Implements OutputGenIntf.
Definition at line 1313 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment Beginning Body of RTF Document}\n")
  // end page and setup for rest of document
  m_t << "\\sect \\sbkpage \\pgndec \\pgnrestart\n";
  m_t << "\\sect \\sectd \\sbknone\n";
  // set new footer with arabic numbers
  m_t << "{\\footer "<< rtf_Style["Footer"].reference() << "{\\chpgn}}\n";
}
References DBG_RTF, OutputGenerator::m_t, and rtf_Style.
lineBreak()
void RTFGenerator::lineBreak (const QCString & style = QCString()) override virtual
Implements OutputGenIntf.
Definition at line 1329 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (lineBreak)}"    << "\n")
  m_t << "\\par\n";
  m_omitParagraph = TRUE;
}
References DBG_RTF, m_omitParagraph, OutputGenerator::m_t, and TRUE.
newParagraph()
void RTFGenerator::newParagraph () private
Definition at line 2114 of file rtfgen.cpp.
{
  if (!m_omitParagraph)
  {
    DBG_RTF(m_t << "{\\comment (newParagraph)}\n")
    m_t << "\\par\n";
  }
  m_omitParagraph = FALSE;
}
References DBG_RTF, FALSE, m_omitParagraph, and OutputGenerator::m_t.
Referenced by endCallGraph(), endClassDiagram(), endCompoundTemplateParams(), endConstraintDocs(), endConstraintList(), endDirDepGraph(), endDotGraph(), endExamples(), endInclDepGraph(), endIndexValue(), endItemList(), endMemberDoc(), endMemberGroupDocs(), endMemberGroupHeader(), endMemberItem(), endMemberSubtitle(), endSection(), endTextBlock(), startConstraintList(), startExamples(), startItemList(), startItemListItem(), and startParagraph().
operator=() [1/2]
RTFGenerator & RTFGenerator::operator= (const RTFGenerator & og)
Definition at line 356 of file rtfgen.cpp.
{
  if (this!=&og)
  {
    m_dir            = og.m_dir;
    m_codeList       = std::make_unique<OutputCodeList>(*og.m_codeList);
    m_codeGen        = m_codeList->get<RTFCodeGenerator>(OutputType::RTF);
    m_codeGen->setTextStream(&m_t);
    m_bstartedBody   = og.m_bstartedBody;
    m_omitParagraph  = og.m_omitParagraph;
    m_numCols        = og.m_numCols;
    m_relPath        = og.m_relPath;
    m_indentLevel    = og.m_indentLevel;
    m_listItemInfo   = og.m_listItemInfo;
  }
  return *this;
}
References m_bstartedBody, m_codeGen, m_codeList, OutputGenerator::m_dir, m_indentLevel, m_listItemInfo, m_numCols, m_omitParagraph, m_relPath, OutputGenerator::m_t, RTF, and RTFGenerator().
operator=() [2/2]
RTFGenerator & RTFGenerator::operator= (RTFGenerator &&) delete
References RTFGenerator().
preProcessFileInplace()
bool RTFGenerator::preProcessFileInplace (const QCString & path, const QCString & name) static
This is an API to a VERY brittle RTF preprocessor that combines nested RTF files.
This version replaces the infile with the new file
Definition at line 2457 of file rtfgen.cpp.
{
  static bool rtfDebug = Debug::isFlagSet(Debug::Rtf);
  Dir d(path.str());
  // store the original directory
  if (!d.exists())
  {
    err("Output dir %s does not exist!\n",qPrint(path));
    return FALSE;
  }
  std::string oldDir = Dir::currentDirPath();
  // go to the html output directory (i.e. path)
  Dir::setCurrent(d.absPath());
  Dir thisDir;
  QCString combinedName = path+"/combined.rtf";
  QCString mainRTFName  = path+"/"+name;
  std::ofstream f = Portable::openOutputStream(combinedName);
  if (!f.is_open())
  {
    err("Failed to open %s for writing!\n",combinedName.data());
    Dir::setCurrent(oldDir);
    return FALSE;
  }
  TextStream outt(&f);
  if (!preProcessFile(thisDir,mainRTFName,outt,true,false))
  {
    // it failed, remove the temp file
    outt.flush();
    f.close();
    if (!rtfDebug) removeSet.insert(FileInfo(thisDir.filePath(combinedName.str())).absFilePath());
    Dir::setCurrent(oldDir);
    return FALSE;
  }
  // everything worked, move the files
  outt.flush();
  f.close();
  if (!rtfDebug)
  {
    thisDir.remove(mainRTFName.str());
  }
  else
  {
    thisDir.rename(mainRTFName.str(),mainRTFName.str() + ".org");
  }
  thisDir.rename(combinedName.str(),mainRTFName.str());
  testRTFOutput(mainRTFName);
  QCString rtfOutputDir = Dir::currentDirPath();
  for (auto &s : removeSet)
  {
    QCString s1(s.c_str());
    if (s1.startsWith(rtfOutputDir)) Portable::unlink(s1);
  }
  Dir::setCurrent(oldDir);
  return TRUE;
}
References Dir::absPath(), Dir::currentDirPath(), QCString::data(), err, Dir::exists(), FALSE, Dir::filePath(), TextStream::flush(), Debug::isFlagSet(), Portable::openOutputStream(), preProcessFile(), qPrint(), Dir::remove(), removeSet, Dir::rename(), Debug::Rtf, Dir::setCurrent(), QCString::startsWith(), QCString::str(), testRTFOutput(), TRUE, and Portable::unlink().
Referenced by generateOutput().
rtf_BList_DepthStyle()
QCString RTFGenerator::rtf_BList_DepthStyle () private
Definition at line 2072 of file rtfgen.cpp.
{
  QCString n=makeIndexName("ListBullet",indentLevel());
  return rtf_Style[n.str()].reference();
}
References indentLevel(), makeIndexName(), rtf_Style, and QCString::str().
Referenced by startItemListItem(), startMemberGroup(), and startMemberItem().
rtf_CList_DepthStyle()
QCString RTFGenerator::rtf_CList_DepthStyle () private
Definition at line 2058 of file rtfgen.cpp.
{
  QCString n=makeIndexName("ListContinue",indentLevel());
  return rtf_Style[n.str()].reference();
}
References indentLevel(), makeIndexName(), rtf_Style, and QCString::str().
Referenced by endMemberGroupHeader(), startIndent(), startMemberDescription(), and startMemberSubtitle().
rtf_DList_DepthStyle()
QCString RTFGenerator::rtf_DList_DepthStyle () private
Definition at line 2085 of file rtfgen.cpp.
{
  QCString n=makeIndexName("DescContinue",indentLevel());
  return rtf_Style[n.str()].reference();
}
References indentLevel(), makeIndexName(), rtf_Style, and QCString::str().
Referenced by startConstraintList(), startDescTable(), startExamples(), and startMemberDocSimple().
rtf_EList_DepthStyle()
QCString RTFGenerator::rtf_EList_DepthStyle () private
Definition at line 2079 of file rtfgen.cpp.
{
  QCString n=makeIndexName("ListEnum",indentLevel());
  return rtf_Style[n.str()].reference();
}
References indentLevel(), makeIndexName(), rtf_Style, and QCString::str().
Referenced by startItemListItem().
rtf_LCList_DepthStyle()
QCString RTFGenerator::rtf_LCList_DepthStyle () private
Definition at line 2065 of file rtfgen.cpp.
{
  QCString n=makeIndexName("LatexTOC",indentLevel());
  return rtf_Style[n.str()].reference();
}
References indentLevel(), makeIndexName(), rtf_Style, and QCString::str().
Referenced by startIndexList().
rtfwriteRuler_doubleline()
void RTFGenerator::rtfwriteRuler_doubleline () private
Definition at line 2628 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (rtfwriteRuler_doubleline)}\n")
  m_t << "{\\pard\\widctlpar\\brdrb\\brdrdb\\brdrw15\\brsp20 \\adjustright \\par}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
rtfwriteRuler_emboss()
void RTFGenerator::rtfwriteRuler_emboss () private
Definition at line 2634 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (rtfwriteRuler_emboss)}\n")
  m_t << "{\\pard\\widctlpar\\brdrb\\brdremboss\\brdrw15\\brsp20 \\adjustright \\par}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
Referenced by beginRTFSection().
rtfwriteRuler_thick()
void RTFGenerator::rtfwriteRuler_thick () private
Definition at line 2640 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (rtfwriteRuler_thick)}\n")
  m_t << "{\\pard\\widctlpar\\brdrb\\brdrs\\brdrw75\\brsp20 \\adjustright \\par}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
Referenced by beginRTFChapter().
rtfwriteRuler_thin()
void RTFGenerator::rtfwriteRuler_thin () private
Definition at line 2646 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (rtfwriteRuler_thin)}\n")
  m_t << "{\\pard\\widctlpar\\brdrb\\brdrs\\brdrw5\\brsp20 \\adjustright \\par}\n";
}
References DBG_RTF, and OutputGenerator::m_t.
Referenced by writeRuler().
setRelativePath()
void RTFGenerator::setRelativePath (const QCString & path)
Definition at line 381 of file rtfgen.cpp.
{
  m_relPath = path;
}
References m_relPath.
Referenced by startFile().
setSourceFileName()
void RTFGenerator::setSourceFileName (const QCString & sourceFileName)
Definition at line 386 of file rtfgen.cpp.
{
  m_codeGen->setSourceFileName(name);
}
References m_codeGen.
Referenced by endFile(), and startFile().
startAnonTypeScope()
void RTFGenerator::startAnonTypeScope (int) inline override virtual
Implements OutputGenIntf.
Definition at line 164 of file rtfgen.h.
{}
startBold()
void RTFGenerator::startBold () inline override virtual
Implements OutputGenIntf.
Definition at line 180 of file rtfgen.h.
{ m_t << "{\\b "; }
References OutputGenerator::m_t.
Referenced by startConstraintList(), startExamples(), startInlineHeader(), and startMemberDoc().
startCallGraph()
void RTFGenerator::startCallGraph () override virtual
Implements OutputGenIntf.
Definition at line 2365 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startCallGraph)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startCenter()
void RTFGenerator::startCenter () inline override virtual
Implements OutputGenIntf.
Definition at line 192 of file rtfgen.h.
{ m_t << "{\\qc\n"; }
References OutputGenerator::m_t.
startClassDiagram()
void RTFGenerator::startClassDiagram () override virtual
Implements OutputGenIntf.
Definition at line 1856 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startClassDiagram }\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startCompoundTemplateParams()
void RTFGenerator::startCompoundTemplateParams () override virtual
Implements OutputGenIntf.
Definition at line 1499 of file rtfgen.cpp.
{
  //beginRTFSubSubSection();
  m_t << "\n";
  DBG_RTF(m_t << "{\\comment Begin SubSubSection}\n")
  m_t << "{\n";
  int level = 4 + m_hierarchyLevel;
  m_t << rtf_Style_Reset << rtf_Style[QCString().sprintf("Heading%d", level).str()].reference() << "\n";
}
References DBG_RTF, m_hierarchyLevel, OutputGenerator::m_t, rtf_Style, and rtf_Style_Reset.
startConstraintDocs()
void RTFGenerator::startConstraintDocs () override virtual
Implements OutputGenIntf.
Definition at line 2693 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startConstraintDocs)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startConstraintList()
void RTFGenerator::startConstraintList (const QCString & header) override virtual
Implements OutputGenIntf.
Definition at line 2652 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startConstraintList)}\n")
  m_t << "{"; // ends at endConstraintList
  m_t << "{";
  startBold();
  newParagraph();
  docify(header);
  endBold();
  m_t << "}";
  newParagraph();
  incIndentLevel();
  m_t << rtf_Style_Reset << rtf_DList_DepthStyle();
}
References DBG_RTF, docify(), endBold(), incIndentLevel(), OutputGenerator::m_t, newParagraph(), rtf_DList_DepthStyle(), rtf_Style_Reset, and startBold().
startConstraintParam()
void RTFGenerator::startConstraintParam () override virtual
Implements OutputGenIntf.
Definition at line 2667 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startConstraintParam)}\n")
  startEmphasis();
}
References DBG_RTF, OutputGenerator::m_t, and startEmphasis().
startConstraintType()
void RTFGenerator::startConstraintType () override virtual
Implements OutputGenIntf.
Definition at line 2680 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startConstraintType)}\n")
  startEmphasis();
}
References DBG_RTF, OutputGenerator::m_t, and startEmphasis().
startContents()
void RTFGenerator::startContents () inline override virtual
Implements OutputGenIntf.
Definition at line 224 of file rtfgen.h.
{}
startDescForItem()
void RTFGenerator::startDescForItem () override virtual
Implements OutputGenIntf.
Definition at line 1793 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDescForItem) }\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startDescTable()
void RTFGenerator::startDescTable (const QCString & title, const bool hasInits) override virtual
Implements OutputGenIntf.
Definition at line 1946 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDescTable) }\n")
  m_t << "{\\par\n";
  m_t << "{" << rtf_Style["Heading5"].reference() << "\n";
  docify(title);
  m_t << ":\\par}\n";
  m_t << rtf_Style_Reset << rtf_DList_DepthStyle();
  m_t << "\\trowd \\trgaph108\\trleft426\\tblind426"
       "\\trbrdrt\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrl\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrb\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrr\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrh\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrv\\brdrs\\brdrw10\\brdrcf15 \n";
  int columnPos2[2] = { 25, 100 };
  int columnPos3[3] = { 25, 45, 100 };
  for (int i=0;i<(hasInits?3:2);i++)
  {
    m_t << "\\clvertalt\\clbrdrt\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrl\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrb\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrr \\brdrs\\brdrw10\\brdrcf15 "
         "\\cltxlrtb "
         "\\cellx" << (rtf_pageWidth*(hasInits?columnPos3[i]:columnPos2[i])/100) << "\n";
  }
  m_t << "\\pard \\widctlpar\\intbl\\adjustright\n";
}
References DBG_RTF, docify(), OutputGenerator::m_t, rtf_DList_DepthStyle(), rtf_pageWidth, rtf_Style, and rtf_Style_Reset.
startDescTableData()
void RTFGenerator::startDescTableData () override virtual
Implements OutputGenIntf.
Definition at line 2016 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDescTableData) }\n")
  m_t << "{";
}
References DBG_RTF, and OutputGenerator::m_t.
startDescTableInit()
void RTFGenerator::startDescTableInit () override virtual
Implements OutputGenIntf.
Definition at line 2002 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDescTableInit) }"    << endl)
  m_t << "{";
  m_t << rtf_Style["BodyText"].reference();
  m_t << "\\qr ";
}
References DBG_RTF, OutputGenerator::m_t, and rtf_Style.
startDescTableRow()
void RTFGenerator::startDescTableRow () override virtual
Implements OutputGenIntf.
Definition at line 1981 of file rtfgen.cpp.
{
}
startDescTableTitle()
void RTFGenerator::startDescTableTitle () override virtual
Implements OutputGenIntf.
Definition at line 1989 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDescTableTitle) }\n")
  m_t << "{";
  m_t << rtf_Style["BodyText"].reference();
}
References DBG_RTF, OutputGenerator::m_t, and rtf_Style.
startDirDepGraph()
void RTFGenerator::startDirDepGraph () override virtual
Implements OutputGenIntf.
Definition at line 2387 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDirDepGraph)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startDotGraph()
void RTFGenerator::startDotGraph () override virtual
Implements OutputGenIntf.
Definition at line 2312 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startDotGraph)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startDoxyAnchor()
void RTFGenerator::startDoxyAnchor (const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 1708 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startDoxyAnchor}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startEmphasis()
void RTFGenerator::startEmphasis () inline override virtual
Implements OutputGenIntf.
Definition at line 178 of file rtfgen.h.
{ m_t << "{\\i ";  }
References OutputGenerator::m_t.
Referenced by startConstraintParam(), startConstraintType(), startMemberDescription(), startMemberGroupDocs(), and startPageRef().
startExamples()
void RTFGenerator::startExamples () override virtual
Implements OutputGenIntf.
Definition at line 2563 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startExamples)}\n")
  m_t << "{"; // ends at endDescList
  m_t << "{"; // ends at endDescTitle
  startBold();
  newParagraph();
  docify(theTranslator->trExamples());
  endBold();
  m_t << "}";
  newParagraph();
  incIndentLevel();
  m_t << rtf_Style_Reset << rtf_DList_DepthStyle();
}
References DBG_RTF, docify(), endBold(), incIndentLevel(), OutputGenerator::m_t, newParagraph(), rtf_DList_DepthStyle(), rtf_Style_Reset, startBold(), theTranslator, and Translator::trExamples().
startFile()
void RTFGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id, int hierarchyLevel) override virtual
Implements OutputGenIntf.
Definition at line 701 of file rtfgen.cpp.
{
  //setEncoding(QCString().sprintf("CP%s",theTranslator->trRTFansicp()));
  QCString fileName=name;
  m_relPath = relativePathToRoot(fileName);
  m_hierarchyLevel = hierarchyLevel;
  if (!fileName.endsWith(".rtf")) fileName+=".rtf";
  startPlainFile(fileName);
  setRelativePath(m_relPath);
  setSourceFileName(stripPath(fileName));
  beginRTFDocument();
}
References beginRTFDocument(), OutputGenerator::fileName(), m_hierarchyLevel, m_relPath, relativePathToRoot(), setRelativePath(), setSourceFileName(), startPlainFile(), and stripPath().
startGroupCollaboration()
void RTFGenerator::startGroupCollaboration () override virtual
Implements OutputGenIntf.
Definition at line 2357 of file rtfgen.cpp.
{
}
startGroupHeader()
void RTFGenerator::startGroupHeader (int extraIndent) override virtual
Implements OutputGenIntf.
Definition at line 1640 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startGroupHeader}\n")
  m_t << rtf_Style_Reset;
  extraIndent += m_hierarchyLevel;
  if (extraIndent>=2)
  {
    m_t << rtf_Style["Heading5"].reference();
  }
  else if (extraIndent==1)
  {
    m_t << rtf_Style["Heading4"].reference();
  }
  else // extraIndent==0
  {
    m_t << rtf_Style["Heading3"].reference();
  }
  m_t << "\n";
}
References DBG_RTF, m_hierarchyLevel, OutputGenerator::m_t, rtf_Style, and rtf_Style_Reset.
Referenced by startMemberHeader().
startHeaderSection()
void RTFGenerator::startHeaderSection () inline override virtual
Implements OutputGenIntf.
Definition at line 152 of file rtfgen.h.
{}
startInclDepGraph()
void RTFGenerator::startInclDepGraph () override virtual
Implements OutputGenIntf.
Definition at line 2335 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startInclDepGraph)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startIndent()
void RTFGenerator::startIndent () override virtual
Implements OutputGenIntf.
Definition at line 1759 of file rtfgen.cpp.
{
  incIndentLevel();
  DBG_RTF(m_t << "{\\comment (startIndent) }\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset << rtf_CList_DepthStyle() << "\n";
}
References DBG_RTF, incIndentLevel(), OutputGenerator::m_t, rtf_CList_DepthStyle(), and rtf_Style_Reset.
startIndexItem()
void RTFGenerator::startIndexItem (const QCString & ref, const QCString & file) override virtual
Implements OutputGenIntf.
Definition at line 1411 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startIndexItem)}\n")
  if (!m_omitParagraph)
  {
    m_t << "\\par\n";
    m_omitParagraph = TRUE;
  }
}
References DBG_RTF, m_omitParagraph, OutputGenerator::m_t, and TRUE.
startIndexKey()
void RTFGenerator::startIndexKey () override virtual
Implements OutputGenIntf.
Definition at line 1462 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startIndexKey)}\n")
  m_t << "{\\b ";
}
References DBG_RTF, and OutputGenerator::m_t.
startIndexList()
void RTFGenerator::startIndexList () override virtual
Implements OutputGenIntf.
Definition at line 1341 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startIndexList)}\n")
  m_t << "{\n";
  m_t << "\\par\n";
  incIndentLevel();
  m_t << rtf_Style_Reset << rtf_LCList_DepthStyle() << "\n";
  m_omitParagraph = TRUE;
}
References DBG_RTF, incIndentLevel(), m_omitParagraph, OutputGenerator::m_t, rtf_LCList_DepthStyle(), rtf_Style_Reset, and TRUE.
startIndexListItem()
void RTFGenerator::startIndexListItem () override virtual
Implements OutputGenIntf.
Definition at line 2713 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startIndexListItem)}\n")
}
References DBG_RTF, and OutputGenerator::m_t.
startIndexSection()
void RTFGenerator::startIndexSection (IndexSection is) override virtual
Implements OutputGenIntf.
Definition at line 735 of file rtfgen.cpp.
{
  //QCString paperName;
  //m_indentLevel = 0;
  switch (is)
  {
    case IndexSection::isTitlePageStart:
      // basic RTFstart
      // get readyfor author etc
      m_t << "{\\info \n";
      m_t << "{\\title {\\comment ";
      break;
    case IndexSection::isTitlePageAuthor:
      m_t << "}\n";
      if (!rtf_subject.isEmpty())      m_t << "{\\subject "  << rtf_subject      << "}\n";
      if (!rtf_comments.isEmpty())     m_t << "{\\comment "  << rtf_comments     << "}\n";
      if (!rtf_company.isEmpty())      m_t << "{\\company "  << rtf_company      << "}\n";
      if (!rtf_author.isEmpty())       m_t << "{\\author "   << rtf_author       << "}\n";
      if (!rtf_manager.isEmpty())      m_t << "{\\manager "  << rtf_manager      << "}\n";
      if (!rtf_documentType.isEmpty()) m_t << "{\\category " << rtf_documentType << "}\n";
      if (!rtf_keywords.isEmpty())     m_t << "{\\keywords " << rtf_keywords     << "}\n";
      m_t << "{\\comment ";
      break;
    case IndexSection::isMainPage:
      //Introduction
      beginRTFChapter();
      break;
    case IndexSection::isTopicIndex:
      //Topic Index
      beginRTFChapter();
      break;
    case IndexSection::isModuleIndex:
      //Module Index
      beginRTFChapter();
      break;
    case IndexSection::isDirIndex:
      //Directory Index
      beginRTFChapter();
      break;
    case IndexSection::isNamespaceIndex:
      //Namespace Index
      beginRTFChapter();
      break;
    case IndexSection::isConceptIndex:
      //Concept Index
      beginRTFChapter();
      break;
    case IndexSection::isClassHierarchyIndex:
      //Hierarchical Index
      DBG_RTF(m_t << "{\\comment start classhierarchy}\n")
      beginRTFChapter();
      break;
    case IndexSection::isCompoundIndex:
      //Annotated Compound Index
      beginRTFChapter();
      break;
    case IndexSection::isFileIndex:
      //Annotated File Index
      beginRTFChapter();
      break;
    case IndexSection::isPageIndex:
      //Related Page Index
      beginRTFChapter();
      break;
    case IndexSection::isTopicDocumentation:
      {
        //Topic Documentation
        for (const auto &gd : *Doxygen::groupLinkedMap)
        {
          if (!gd->isReference())
          {
            beginRTFChapter();
            break;
          }
        }
      }
      break;
    case IndexSection::isModuleDocumentation:
      {
        //Module Documentation
        for (const auto &mod : ModuleManager::instance().modules())
        {
          if (!mod->isReference() && mod->isPrimaryInterface())
          {
            beginRTFChapter();
            break;
          }
        }
      }
      break;
    case IndexSection::isDirDocumentation:
      {
        //Directory Documentation
        for (const auto &dd : *Doxygen::dirLinkedMap)
        {
          if (dd->isLinkableInProject())
          {
            beginRTFChapter();
            break;
          }
        }
      }
      break;
    case IndexSection::isNamespaceDocumentation:
      {
        // Namespace Documentation
        for (const auto &nd : *Doxygen::namespaceLinkedMap)
        {
          if (nd->isLinkableInProject())
          {
            beginRTFChapter();
            break;
          }
        }
      }
      break;
    case IndexSection::isConceptDocumentation:
      {
        // Concept Documentation
        for (const auto &cd : *Doxygen::conceptLinkedMap)
        {
          if (cd->isLinkableInProject())
          {
            beginRTFChapter();
            break;
          }
        }
      }
      break;
    case IndexSection::isClassDocumentation:
      {
        //Compound Documentation
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->isLinkableInProject() &&
              cd->templateMaster()==nullptr &&
             !cd->isEmbeddedInOuterScope() &&
             !cd->isAlias()
             )
          {
            beginRTFChapter();
            break;
          }
        }
      }
      break;
    case IndexSection::isFileDocumentation:
      {
        //File Documentation
        bool isFirst=TRUE;
        for (const auto &fn : *Doxygen::inputNameLinkedMap)
        {
          for (const auto &fd : *fn)
          {
            if (fd->isLinkableInProject() || fd->generateSourceFile())
            {
              if (isFirst)
              {
                beginRTFChapter();
                isFirst=FALSE;
                break;
              }
            }
          }
          if (!isFirst)
          {
            break;
          }
        }
      }
      break;
    case IndexSection::isExampleDocumentation:
      {
        //Example Documentation
        beginRTFChapter();
      }
      break;
    case IndexSection::isPageDocumentation:
      break;
    case IndexSection::isPageDocumentation2:
      break;
    case IndexSection::isEndIndex:
      break;
  }
}
References beginRTFChapter(), Doxygen::classLinkedMap, Doxygen::conceptLinkedMap, DBG_RTF, Doxygen::dirLinkedMap, FALSE, Doxygen::groupLinkedMap, Doxygen::inputNameLinkedMap, ModuleManager::instance(), isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, QCString::isEmpty(), isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, isTopicDocumentation, isTopicIndex, OutputGenerator::m_t, Doxygen::namespaceLinkedMap, rtf_author, rtf_comments, rtf_company, rtf_documentType, rtf_keywords, rtf_manager, rtf_subject, and TRUE.
startIndexValue()
void RTFGenerator::startIndexValue (bool hasBrief) override virtual
Implements OutputGenIntf.
Definition at line 1473 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startIndexValue)}\n")
  m_t << " ";
  if (hasBrief) m_t << "(";
}
References DBG_RTF, and OutputGenerator::m_t.
startInlineHeader()
void RTFGenerator::startInlineHeader () override virtual
Implements OutputGenIntf.
Definition at line 2724 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startInlineHeader)}\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset << rtf_Style["Heading5"].reference();
  startBold();
}
References DBG_RTF, OutputGenerator::m_t, rtf_Style, rtf_Style_Reset, and startBold().
startInlineMemberDoc()
void RTFGenerator::startInlineMemberDoc () override virtual
Implements OutputGenIntf.
Definition at line 2811 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startInlineMemberDoc)}\n")
  m_t << "{";
}
References DBG_RTF, and OutputGenerator::m_t.
startInlineMemberName()
void RTFGenerator::startInlineMemberName () override virtual
Implements OutputGenIntf.
Definition at line 2799 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startInlineMemberName)}\n")
  m_t << "{";
}
References DBG_RTF, and OutputGenerator::m_t.
startInlineMemberType()
void RTFGenerator::startInlineMemberType () override virtual
Implements OutputGenIntf.
Definition at line 2787 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startInlineMemberType)}\n")
  m_t << "{\\qr ";
}
References DBG_RTF, and OutputGenerator::m_t.
startItemList()
void RTFGenerator::startItemList () override virtual
start bullet list
Implements OutputGenIntf.
Definition at line 1364 of file rtfgen.cpp.
{
  newParagraph();
  incIndentLevel();
  int level = indentLevel();
  DBG_RTF(m_t << "{\\comment (startItemList level=" << level << ") }\n")
  m_t << "{";
  m_listItemInfo[level].number = 1;
  m_listItemInfo[level].isEnum = false;
  m_listItemInfo[level].type   = '1';
}
References DBG_RTF, incIndentLevel(), indentLevel(), m_listItemInfo, OutputGenerator::m_t, and newParagraph().
startItemListItem()
void RTFGenerator::startItemListItem () override virtual
write bullet or enum item
Implements OutputGenIntf.
Definition at line 1387 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startItemListItem)}\n")
  newParagraph();
  m_t << rtf_Style_Reset;
  int level = indentLevel();
  if (m_listItemInfo[level].isEnum)
  {
    m_t << rtf_EList_DepthStyle() << "\n";
    m_t << m_listItemInfo[level].number << ".\\tab ";
    m_listItemInfo[level].number++;
  }
  else
  {
    m_t << rtf_BList_DepthStyle() << "\n";
  }
  m_omitParagraph = TRUE;
}
References DBG_RTF, indentLevel(), m_listItemInfo, m_omitParagraph, OutputGenerator::m_t, newParagraph(), rtf_BList_DepthStyle(), rtf_EList_DepthStyle(), rtf_Style_Reset, and TRUE.
startLabels()
void RTFGenerator::startLabels () override virtual
Implements OutputGenIntf.
Definition at line 2823 of file rtfgen.cpp.
{
}
startMemberDeclaration()
void RTFGenerator::startMemberDeclaration () inline override virtual
Implements OutputGenIntf.
Definition at line 199 of file rtfgen.h.
{}
startMemberDescription()
void RTFGenerator::startMemberDescription (const QCString & , const QCString & , bool) override virtual
Implements OutputGenIntf.
Definition at line 1774 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startMemberDescription)}\n")
  m_t << "{\n";
  incIndentLevel();
  m_t << rtf_Style_Reset << rtf_CList_DepthStyle();
  startEmphasis();
}
References DBG_RTF, incIndentLevel(), OutputGenerator::m_t, rtf_CList_DepthStyle(), rtf_Style_Reset, and startEmphasis().
startMemberDoc()
void RTFGenerator::startMemberDoc (const QCString & clname, const QCString & memname, const QCString & , const QCString & , int , int , bool showInline) override virtual
Implements OutputGenIntf.
Definition at line 1667 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberDoc}\n")
  if (!memname.isEmpty() && memname[0]!='@')
  {
    addIndexItem(memname,clname);
    addIndexItem(clname,memname);
  }
  int level = 4 + m_hierarchyLevel;
  if (showInline)
    ++level;
  if (level > 5)
    level = 5;
  if (level < 1)
    level = 1;
  m_t << rtf_Style_Reset << rtf_Style[QCString().sprintf("Heading%d", level).str()].reference();
  //styleStack.push(rtf_Style_Heading4);
  m_t << "{\n";
  //printf("RTFGenerator::startMemberDoc() '%s'\n",rtf_Style["Heading4"].reference());
  startBold();
  m_t << "\n";
}
References addIndexItem(), DBG_RTF, QCString::isEmpty(), m_hierarchyLevel, OutputGenerator::m_t, rtf_Style, rtf_Style_Reset, and startBold().
startMemberDocList()
void RTFGenerator::startMemberDocList () inline override virtual
Implements OutputGenIntf.
Definition at line 158 of file rtfgen.h.
{}
startMemberDocName()
void RTFGenerator::startMemberDocName (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 264 of file rtfgen.h.
{}
startMemberDocPrefixItem()
void RTFGenerator::startMemberDocPrefixItem () inline override virtual
Implements OutputGenIntf.
Definition at line 262 of file rtfgen.h.
{}
startMemberDocSimple()
void RTFGenerator::startMemberDocSimple (bool isEnum) override virtual
Implements OutputGenIntf.
Definition at line 2740 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startMemberDocSimple)}\n")
  m_t << "{\\par\n";
  m_t << "{" << rtf_Style["Heading5"].reference() << "\n";
  if (isEnum)
  {
    m_t << theTranslator->trEnumerationValues();
  }
  else
  {
    m_t << theTranslator->trCompoundMembers();
  }
  m_t << ":\\par}\n";
  m_t << rtf_Style_Reset << rtf_DList_DepthStyle();
  m_t << "\\trowd \\trgaph108\\trleft426\\tblind426"
       "\\trbrdrt\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrl\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrb\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrr\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrh\\brdrs\\brdrw10\\brdrcf15 "
       "\\trbrdrv\\brdrs\\brdrw10\\brdrcf15 \n";
  int n=3,columnPos[3] = { 25, 50, 100 };
  if (isEnum)
  {
    columnPos[0]=30;
    columnPos[1]=100;
    n=2;
  }
  for (int i=0;i<n;i++)
  {
    m_t << "\\clvertalt\\clbrdrt\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrl\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrb\\brdrs\\brdrw10\\brdrcf15 "
         "\\clbrdrr \\brdrs\\brdrw10\\brdrcf15 "
         "\\cltxlrtb "
         "\\cellx" << (rtf_pageWidth*columnPos[i]/100) << "\n";
  }
  m_t << "\\pard \\widctlpar\\intbl\\adjustright\n";
}
References DBG_RTF, OutputGenerator::m_t, rtf_DList_DepthStyle(), rtf_pageWidth, rtf_Style, rtf_Style_Reset, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberGroup()
void RTFGenerator::startMemberGroup () override virtual
Implements OutputGenIntf.
Definition at line 2550 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberGroup}\n")
  m_t << rtf_Style_Reset << rtf_BList_DepthStyle() << "\n";
}
References DBG_RTF, OutputGenerator::m_t, rtf_BList_DepthStyle(), and rtf_Style_Reset.
startMemberGroupDocs()
void RTFGenerator::startMemberGroupDocs () override virtual
Implements OutputGenIntf.
Definition at line 2537 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberGroupDocs}\n")
  startEmphasis();
}
References DBG_RTF, OutputGenerator::m_t, and startEmphasis().
startMemberGroupHeader()
void RTFGenerator::startMemberGroupHeader (bool hasHeader) override virtual
Implements OutputGenIntf.
Definition at line 2522 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberGroupHeader}\n")
  m_t << "{\n";
  if (hasHeader) incIndentLevel();
  m_t << rtf_Style_Reset << rtf_Style["GroupHeader"].reference();
}
References DBG_RTF, incIndentLevel(), OutputGenerator::m_t, rtf_Style, and rtf_Style_Reset.
startMemberHeader()
void RTFGenerator::startMemberHeader (const QCString & , int) inline override virtual
Implements OutputGenIntf.
Definition at line 154 of file rtfgen.h.
{ startGroupHeader(0); }
References startGroupHeader().
startMemberItem()
void RTFGenerator::startMemberItem (const QCString & , MemberItemType , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 1878 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberItem }\n")
  m_t << rtf_Style_Reset << rtf_BList_DepthStyle() << "\n"; // set style to appropriate depth
}
References DBG_RTF, OutputGenerator::m_t, rtf_BList_DepthStyle(), and rtf_Style_Reset.
startMemberList()
void RTFGenerator::startMemberList () override virtual
Implements OutputGenIntf.
Definition at line 1925 of file rtfgen.cpp.
{
  m_t << "\n";
  DBG_RTF(m_t << "{\\comment (startMemberList) }\n")
  m_t << "{\n";
#ifdef DELETEDCODE
  if (!insideTabbing)
    m_t << "\\begin{CompactItemize}\n";
#endif
}
References DBG_RTF, and OutputGenerator::m_t.
startMemberSections()
void RTFGenerator::startMemberSections () inline override virtual
Implements OutputGenIntf.
Definition at line 150 of file rtfgen.h.
{}
startMemberSubtitle()
void RTFGenerator::startMemberSubtitle () override virtual
Implements OutputGenIntf.
Definition at line 2139 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startMemberSubtitle}\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset << rtf_CList_DepthStyle() << "\n";
}
References DBG_RTF, OutputGenerator::m_t, rtf_CList_DepthStyle(), and rtf_Style_Reset.
startMemberTemplateParams()
void RTFGenerator::startMemberTemplateParams () inline override virtual
Implements OutputGenIntf.
Definition at line 168 of file rtfgen.h.
{}
startPageDoc()
void RTFGenerator::startPageDoc (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 112 of file rtfgen.h.
{}
startPageRef()
void RTFGenerator::startPageRef () override virtual
Implements OutputGenIntf.
Definition at line 1586 of file rtfgen.cpp.
{
  m_t << " (";
  startEmphasis();
}
References OutputGenerator::m_t, and startEmphasis().
startParagraph()
void RTFGenerator::startParagraph (const QCString & classDef) override virtual
Implements OutputGenIntf.
Definition at line 2124 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startParagraph}\n")
  newParagraph();
  m_t << "{\n";
  if (QCString(txt) == "reference") m_t << "\\ql\n";
}
References DBG_RTF, OutputGenerator::m_t, and newParagraph().
startParameterDefVal()
void RTFGenerator::startParameterDefVal (const char * s) inline override virtual
Implements OutputGenIntf.
Definition at line 272 of file rtfgen.h.
{ docify(s); startTypewriter(); }
References docify(), and startTypewriter().
startParameterExtra()
void RTFGenerator::startParameterExtra () inline override virtual
Implements OutputGenIntf.
Definition at line 270 of file rtfgen.h.
{}
startParameterList()
void RTFGenerator::startParameterList (bool openBracket) override virtual
Implements OutputGenIntf.
Definition at line 2850 of file rtfgen.cpp.
{
  if (openBracket) m_t << "(";
}
References OutputGenerator::m_t.
startParameterName()
void RTFGenerator::startParameterName (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 268 of file rtfgen.h.
{}
startParameterType()
void RTFGenerator::startParameterType (bool first, const QCString & key) override virtual
Implements OutputGenIntf.
Definition at line 2588 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startParameterType)}\n")
  if (!first && !key.isEmpty())
  {
    m_t << " " << key << " ";
  }
}
References DBG_RTF, QCString::isEmpty(), and OutputGenerator::m_t.
startPlainFile()
void RTFGenerator::startPlainFile (const QCString & name) inline override virtual
Implements OutputGenIntf.
Definition at line 302 of file rtfgen.h.
{ OutputGenerator::startPlainFile(name); }
References OutputGenerator::startPlainFile().
Referenced by startFile().
startProjectNumber()
void RTFGenerator::startProjectNumber () override virtual
Implements OutputGenIntf.
Definition at line 724 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startProjectNumber }\n")
  m_t << " ";
}
References DBG_RTF, and OutputGenerator::m_t.
startQuickIndices()
void RTFGenerator::startQuickIndices () inline override virtual
Implements OutputGenIntf.
Definition at line 217 of file rtfgen.h.
{}
startSection()
void RTFGenerator::startSection (const QCString & , const QCString & title, SectionType type) override virtual
Implements OutputGenIntf.
Definition at line 1803 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startSection)}\n")
  m_t << "{";
  m_t << rtf_Style_Reset;
  int num=SectionType::MaxLevel;
  switch(type.level())
  {
    case SectionType::Page:             num=2+m_hierarchyLevel; break;
    case SectionType::Section:          num=3+m_hierarchyLevel; break;
    case SectionType::Subsection:       // fall through
    case SectionType::Subsubsection:    // fall through
    case SectionType::Paragraph:        // fall through
    case SectionType::Subparagraph:     // fall through
    case SectionType::Subsubparagraph:  num=4+m_hierarchyLevel; break;
    default: ASSERT(0); break;
  }
  num = std::clamp(num, SectionType::MinLevel, SectionType::MaxLevel);
  QCString heading;
  heading.sprintf("Heading%d",num);
  // set style
  m_t << rtf_Style[heading.str()].reference();
  // make table of contents entry
  m_t << "{\\tc\\tcl" << num << " \\v ";
  docify(title);
  m_t << "}\n";
}
References ASSERT, DBG_RTF, docify(), m_hierarchyLevel, OutputGenerator::m_t, SectionType::MaxLevel, SectionType::MinLevel, SectionType::Page, SectionType::Paragraph, rtf_Style, rtf_Style_Reset, SectionType::Section, QCString::sprintf(), QCString::str(), SectionType::Subparagraph, SectionType::Subsection, SectionType::Subsubparagraph, SectionType::Subsubsection, and type().
startSmall()
void RTFGenerator::startSmall () inline override virtual
Implements OutputGenIntf.
Definition at line 194 of file rtfgen.h.
{ m_t << "{\\sub "; }
References OutputGenerator::m_t.
startTextBlock()
void RTFGenerator::startTextBlock (bool dense) override virtual
Implements OutputGenIntf.
Definition at line 2091 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startTextBlock}\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset;
  if (dense) // no spacing between "paragraphs"
  {
    m_t << rtf_Style["DenseText"].reference();
  }
  else // some spacing
  {
    m_t << rtf_Style["BodyText"].reference();
  }
}
References DBG_RTF, OutputGenerator::m_t, rtf_Style, and rtf_Style_Reset.
startTextLink()
void RTFGenerator::startTextLink (const QCString & f, const QCString & anchor) override virtual
Implements OutputGenIntf.
Definition at line 1515 of file rtfgen.cpp.
{
  if (Config_getBool(RTF_HYPERLINKS))
  {
    QCString ref;
    if (!f.isEmpty())
    {
      ref+=stripPath(f);
    }
    if (!anchor.isEmpty())
    {
      ref+='_';
      ref+=anchor;
    }
    m_t << "{\\field {\\*\\fldinst { HYPERLINK  \\\\l \"";
    m_t << rtfFormatBmkStr(ref);
    m_t << "\" }{}";
    m_t << "}{\\fldrslt {\\cs37\\ul\\cf2 ";
  }
}
References Config_getBool, QCString::isEmpty(), OutputGenerator::m_t, rtfFormatBmkStr(), and stripPath().
startTitleHead()
void RTFGenerator::startTitleHead (const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 1609 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment startTitleHead}\n")
  int level = 2 + m_hierarchyLevel;
  QCString heading;
  heading.sprintf("Heading%d", level);
  //    beginRTFSection();
  m_t << rtf_Style_Reset << rtf_Style[heading.str()].reference() << "\n";
}
References DBG_RTF, m_hierarchyLevel, OutputGenerator::m_t, rtf_Style, rtf_Style_Reset, QCString::sprintf(), and QCString::str().
startTypewriter()
void RTFGenerator::startTypewriter () inline override virtual
Implements OutputGenIntf.
Definition at line 143 of file rtfgen.h.
{ m_t << "{\\f2 "; }
References OutputGenerator::m_t.
Referenced by startParameterDefVal().
type()
OutputType RTFGenerator::type () const inline override virtual
Implements OutputGenIntf.
Definition at line 101 of file rtfgen.h.
{ return OutputType::RTF; }
References RTF.
Referenced by startSection().
writeAnchor()
void RTFGenerator::writeAnchor (const QCString & fileName, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1890 of file rtfgen.cpp.
{
  QCString anchor;
  if (!fileName.isEmpty())
  {
    anchor+=stripPath(fileName);
  }
  if (!fileName.isEmpty() && !name.isEmpty())
  {
    anchor+='_';
  }
  if (!name.isEmpty())
  {
    anchor+=name;
  }
  //printf("writeAnchor(%s->%s)\n",qPrint(anchor),qPrint(rtfFormatBmkStr(anchor)));
  DBG_RTF(m_t << "{\\comment writeAnchor (" << anchor << ")}\n")
  m_t << "{\\bkmkstart " << rtfFormatBmkStr(anchor) << "}\n";
  m_t << "{\\bkmkend " << rtfFormatBmkStr(anchor) << "}\n";
}
References DBG_RTF, OutputGenerator::fileName(), QCString::isEmpty(), OutputGenerator::m_t, rtfFormatBmkStr(), and stripPath().
Referenced by endSection(), and endTitleHead().
writeChar()
void RTFGenerator::writeChar (char c) override virtual
Implements OutputGenIntf.
Definition at line 1848 of file rtfgen.cpp.
{
  char cs[2];
  cs[0]=c;
  cs[1]=0;
  docify(cs);
}
References docify().
writeDoc()
void RTFGenerator::writeDoc (const IDocNodeAST * ast, const Definition * ctx, const MemberDef * , int) override virtual
Implements OutputGenIntf.
Definition at line 2617 of file rtfgen.cpp.
{
  auto astImpl = dynamic_cast<const DocNodeAST*>(ast);
  if (astImpl)
  {
    RTFDocVisitor visitor(m_t,*m_codeList,ctx?ctx->getDefFileExtension():QCString(""),m_hierarchyLevel);
    std::visit(visitor,astImpl->root);
  }
  m_omitParagraph = TRUE;
}
References Definition::getDefFileExtension(), m_codeList, m_hierarchyLevel, m_omitParagraph, OutputGenerator::m_t, and TRUE.
Referenced by endIndexSection().
writeExtensionsFile()
void RTFGenerator::writeExtensionsFile (TextStream & t) static
Definition at line 406 of file rtfgen.cpp.
{
  t << "# Generated by doxygen " << getDoxygenVersion() << "\n\n";
  t << "# This file describes extensions used for generating RTF output.\n";
  t << "# All text after a hash (#) is considered a comment and will be ignored.\n";
  t << "# Remove a hash to activate a line.\n\n";
  t << "# Overrides the project title.\n";
  t << "#Title           = \n\n";
  t << "# Name of the company that produced this document.\n";
  t << "#Company         = \n\n";
  t << "# Filename of a company or project logo.\n";
  t << "#LogoFilename    = \n\n";
  t << "# Author of the document.\n";
  t << "#Author          = \n\n";
  t << "# Type of document (e.g. Design Specification, User Manual, etc.).\n";
  t << "#DocumentType    = \n\n";
  t << "# Document tracking number.\n";
  t << "#DocumentId      = \n\n";
  t << "# Name of the author's manager.\n";
  t << "# This field is not displayed in the document itself, but it is \n";
  t << "# available in the information block of the rtf file.  In Microsoft \n";
  t << "# Word, it is available under File:Properties.\n";
  t << "#Manager         = \n\n";
  t << "# Subject of the document.\n";
  t << "# This field is not displayed in the document itself, but it is \n";
  t << "# available in the information block of the rtf file.  In Microsoft \n";
  t << "# Word, it is available under File:Properties.\n";
  t << "#Subject         = \n\n";
  t << "# Comments regarding the document.\n";
  t << "# This field is not displayed in the document itself, but it is \n";
  t << "# available in the information block of the rtf file.  In Microsoft \n";
  t << "# Word, it is available under File:Properties.\n";
  t << "#Comments        = \n\n";
  t << "# Keywords associated with the document.\n";
  t << "# This field is not displayed in the document itself, but it is \n";
  t << "# available in the information block of the rtf file.  In Microsoft \n";
  t << "# Word, it is available under File:Properties.\n";
  t << "#Keywords        = \n\n";
}
Referenced by readConfiguration().
writeFooter()
void RTFGenerator::writeFooter (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 110 of file rtfgen.h.
{}
writeGraphicalHierarchy()
void RTFGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) inline override virtual
Implements OutputGenIntf.
Definition at line 249 of file rtfgen.h.
{}
writeInheritedSectionTitle()
void RTFGenerator::writeInheritedSectionTitle (const QCString & , const QCString & ref, const QCString & file, const QCString & anchor, const QCString & title, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 2837 of file rtfgen.cpp.
{
  m_t << rtf_Style_Reset;
  m_t << rtf_Style["Heading4"].reference();
  m_t << "\n";
  m_t << theTranslator->trInheritedFrom(docifyToString(title), objectLinkToString(ref, file, anchor, name));
  m_t << "\\par\n";
  m_t << rtf_Style_Reset << "\n";
}
References docifyToString(), OutputGenerator::m_t, objectLinkToString(), rtf_Style, rtf_Style_Reset, theTranslator, and Translator::trInheritedFrom().
writeLabel()
void RTFGenerator::writeLabel (const QCString & l, bool isLast) override virtual
Implements OutputGenIntf.
Definition at line 2827 of file rtfgen.cpp.
{
  m_t << "{\\f2 [" << l << "]}";
  if (!isLast) m_t << ", ";
}
References OutputGenerator::m_t.
writeLatexSpacing()
void RTFGenerator::writeLatexSpacing () inline override virtual
Implements OutputGenIntf.
Definition at line 189 of file rtfgen.h.
{};//{ m_t << "\\hspace{0.3cm}"; }
writeLocalToc()
void RTFGenerator::writeLocalToc (const SectionRefs & , const LocalToc &) inline override virtual
Implements OutputGenIntf.
Definition at line 300 of file rtfgen.h.
{}
writeLogo()
void RTFGenerator::writeLogo () inline override virtual
Implements OutputGenIntf.
Definition at line 221 of file rtfgen.h.
{}
writeNavigationPath()
void RTFGenerator::writeNavigationPath (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 220 of file rtfgen.h.
{}
writeNonBreakableSpace()
void RTFGenerator::writeNonBreakableSpace (int) override virtual
Implements OutputGenIntf.
Definition at line 1919 of file rtfgen.cpp.
{
  m_t << "\\~ ";
}
References OutputGenerator::m_t.
writeObjectLink()
void RTFGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1580 of file rtfgen.cpp.
{
  m_t << objectLinkToString(ref,f,anchor,text);
}
References OutputGenerator::m_t, and objectLinkToString().
writePageLink()
void RTFGenerator::writePageLink (const QCString & name, bool) override virtual
Implements OutputGenIntf.
Definition at line 1305 of file rtfgen.cpp.
{
   m_t << "\\par " << rtf_Style_Reset << "\n";
   m_t << "{\\field\\fldedit{\\*\\fldinst INCLUDETEXT \"";
   m_t << name;
   m_t << ".rtf\" \\\\*MERGEFORMAT}{\\fldrslt includedstuff}}\n";
}
References OutputGenerator::m_t, and rtf_Style_Reset.
Referenced by endIndexSection().
writeQuickLinks()
void RTFGenerator::writeQuickLinks (HighlightedItem , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 222 of file rtfgen.h.
{}
writeRTFReference()
void RTFGenerator::writeRTFReference (const QCString & label) private
Definition at line 1912 of file rtfgen.cpp.
{
  m_t << "{\\field\\fldedit {\\*\\fldinst PAGEREF ";
  m_t << rtfFormatBmkStr(stripPath(label));
  m_t << " \\\\*MERGEFORMAT}{\\fldrslt pagenum}}";
}
References OutputGenerator::m_t, rtfFormatBmkStr(), and stripPath().
Referenced by endIndexItem(), endIndexValue(), and endPageRef().
writeRuler()
void RTFGenerator::writeRuler () inline override virtual
Implements OutputGenIntf.
Definition at line 175 of file rtfgen.h.
{ rtfwriteRuler_thin(); }
References rtfwriteRuler_thin().
writeSearchInfo()
void RTFGenerator::writeSearchInfo () inline override virtual
Implements OutputGenIntf.
Definition at line 109 of file rtfgen.h.
{}
writeSplitBar()
void RTFGenerator::writeSplitBar (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 219 of file rtfgen.h.
{}
writeStartAnnoItem()
void RTFGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1438 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (writeStartAnnoItem)}\n")
  m_t << "{\\b ";
  if (!path.isEmpty()) docify(path);
  if (!f.isEmpty() && Config_getBool(RTF_HYPERLINKS))
  {
    m_t << "{\\field {\\*\\fldinst { HYPERLINK  \\\\l \"";
    m_t << rtfFormatBmkStr(stripPath(f));
    m_t << "\" }{}";
    m_t << "}{\\fldrslt {\\cs37\\ul\\cf2 ";
    docify(name);
    m_t << "}}}\n";
  }
  else
  {
    docify(name);
  }
  m_t << "} ";
}
References Config_getBool, DBG_RTF, docify(), QCString::isEmpty(), OutputGenerator::m_t, rtfFormatBmkStr(), and stripPath().
writeString()
void RTFGenerator::writeString (const QCString & text) override virtual
Implements OutputGenIntf.
Definition at line 1336 of file rtfgen.cpp.
{
  m_t << text;
}
References OutputGenerator::m_t.
writeStyleInfo()
void RTFGenerator::writeStyleInfo (int part) override virtual
Implements OutputGenIntf.
Definition at line 1325 of file rtfgen.cpp.
{
}
writeStyleSheetFile()
void RTFGenerator::writeStyleSheetFile (TextStream & t) static
Definition at line 391 of file rtfgen.cpp.
{
  t << "# Generated by doxygen " << getDoxygenVersion() << "\n\n";
  t << "# This file describes styles used for generating RTF output.\n";
  t << "# All text after a hash (#) is considered a comment and will be ignored.\n";
  t << "# Remove a hash to activate a line.\n\n";
  for (int i=0 ; rtf_Style_Default[i].reference!=nullptr ; i++ )
  {
    t << "# " << rtf_Style_Default[i].name << " = "
              << rtf_Style_Default[i].reference
              << rtf_Style_Default[i].definition << "\n";
  }
}
References Rtf_Style_Default::definition, Rtf_Style_Default::name, Rtf_Style_Default::reference, and rtf_Style_Default.
Referenced by readConfiguration().
writeSummaryLink()
void RTFGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 223 of file rtfgen.h.
{}
writeSynopsis()
void RTFGenerator::writeSynopsis () inline override virtual
Implements OutputGenIntf.
Definition at line 212 of file rtfgen.h.
{}
Member Data Documentation
m_bstartedBody
bool RTFGenerator::m_bstartedBody = false private
Definition at line 325 of file rtfgen.h.
Referenced by operator=(), and RTFGenerator().
m_codeGen
RTFCodeGenerator* RTFGenerator::m_codeGen private
Definition at line 342 of file rtfgen.h.
Referenced by addCodeGen(), decIndentLevel(), incIndentLevel(), operator=(), RTFGenerator(), RTFGenerator(), and setSourceFileName().
m_codeList
std::unique_ptr<OutputCodeList> RTFGenerator::m_codeList private
Definition at line 341 of file rtfgen.h.
Referenced by operator=(), RTFGenerator(), RTFGenerator(), and writeDoc().
m_hierarchyLevel
int RTFGenerator::m_hierarchyLevel = 0 private
Definition at line 329 of file rtfgen.h.
Referenced by beginRTFSection(), endTitleHead(), startCompoundTemplateParams(), startFile(), startGroupHeader(), startMemberDoc(), startSection(), startTitleHead(), and writeDoc().
m_indentLevel
int RTFGenerator::m_indentLevel = 0 private
Definition at line 333 of file rtfgen.h.
Referenced by decIndentLevel(), incIndentLevel(), indentLevel(), operator=(), and RTFGenerator().
m_listItemInfo
std::array<RTFListItemInfo,maxIndentLevels> RTFGenerator::m_listItemInfo private
Definition at line 340 of file rtfgen.h.
Referenced by operator=(), RTFGenerator(), startItemList(), and startItemListItem().
m_numCols
int RTFGenerator::m_numCols = 0 private
Definition at line 327 of file rtfgen.h.
Referenced by operator=(), and RTFGenerator().
m_omitParagraph
bool RTFGenerator::m_omitParagraph = false private
Definition at line 326 of file rtfgen.h.
Referenced by docify(), endConstraintList(), endExamples(), endIndexItem(), endIndexList(), endIndexValue(), endItemList(), endMemberDescription(), endParagraph(), endSection(), lineBreak(), newParagraph(), operator=(), RTFGenerator(), startIndexItem(), startIndexList(), startItemListItem(), and writeDoc().
m_relPath
QCString RTFGenerator::m_relPath private
Definition at line 328 of file rtfgen.h.
Referenced by endCallGraph(), endClassDiagram(), endDirDepGraph(), endDotGraph(), endInclDepGraph(), operator=(), RTFGenerator(), setRelativePath(), and startFile().
maxIndentLevels
const int RTFGenerator::maxIndentLevels = 13 static private
Definition at line 332 of file rtfgen.h.
Referenced by incIndentLevel(), and indentLevel().
The documentation for this class was generated from the following files:
src/rtfgen.h
src/rtfgen.cpp