Doxygen: DotRunner Class Reference
DotRunner Class Reference
Helper class to run dot from doxygen from multiple threads.
#include <src/dotrunner.h>
Classes
struct DotJob
Public Member Functions
DotRunner (const QCString &absDotName, const QCString &md5Hash=QCString())
Creates a runner for a dot file.
void addJob (const QCString &format, const QCString &output, const QCString &srcFile, int srcLine)
Adds an additional job to the run.
void preventCleanUp ()
Prevent cleanup of the dot file (for user provided dot files)
bool run ()
Runs dot for all jobs added.
QCString getMd5Hash ()
Static Public Member Functions
static bool readBoundingBox (const QCString &fileName, int *width, int *height, bool isEps)
Private Attributes
QCString m_file
QCString m_md5Hash
QCString m_dotExe
bool m_cleanUp
std::vector< DotJob > m_jobs
Detailed Description
Helper class to run dot from doxygen from multiple threads.
Definition at line 30 of file dotrunner.h.
Constructor & Destructor Documentation
DotRunner()
DotRunner::DotRunner (const QCString & absDotName, const QCString & md5Hash = QCString())
Creates a runner for a dot file.
Definition at line 250 of file dotrunner.cpp.
  : m_file(absDotName)
  , m_md5Hash(md5Hash)
  , m_dotExe(Doxygen::verifiedDotPath)
  , m_cleanUp(Config_getBool(DOT_CLEANUP))
{
}
References Config_getBool, m_cleanUp, m_dotExe, m_file, and m_md5Hash.
Member Function Documentation
addJob()
void DotRunner::addJob (const QCString & format, const QCString & output, const QCString & srcFile, int srcLine)
Adds an additional job to the run.
Performing multiple jobs one file can be faster.
Definition at line 259 of file dotrunner.cpp.
{
  for (auto& s: m_jobs)
  {
    if (s.format != format) continue;
    if (s.output != output) continue;
    // we have this job already
    return;
  }
  auto args = QCString("-T") + format + " -o \"" + output + "\"";
  m_jobs.emplace_back(format, output, args, srcFile, srcLine);
}
References m_jobs.
Referenced by DotGraph::prepareDotFile(), writeDotGraphFromFile(), and writeDotImageMapFromFile().
getMd5Hash()
QCString DotRunner::getMd5Hash () inline
Definition at line 59 of file dotrunner.h.
{ return m_md5Hash; }
References m_md5Hash.
preventCleanUp()
void DotRunner::preventCleanUp () inline
Prevent cleanup of the dot file (for user provided dot files)
Definition at line 54 of file dotrunner.h.
{ m_cleanUp = false; }
References m_cleanUp.
Referenced by writeDotGraphFromFile(), and writeDotImageMapFromFile().
readBoundingBox()
bool DotRunner::readBoundingBox (const QCString & fileName, int * width, int * height, bool isEps) static
Definition at line 130 of file dotrunner.cpp.
{
  std::ifstream f = Portable::openInputStream(fileName);
  if (!f.is_open())
  {
    err("Failed to open file %s for extracting bounding box\n",qPrint(fileName));
    return false;
  }
  // read file contents into string 'contents'
  std::stringstream buffer;
  buffer << f.rdbuf();
  std::string contents = buffer.str();
  // start of bounding box marker we are looking for
  const std::string boundingBox = isEps ? "%%PageBoundingBox:" : "/MediaBox [";
  // helper routine to extract the bounding boxes width and height
  auto extractBoundingBox = [&fileName,&boundingBox,&width,&height](const char *s) -> bool
  {
    int x=0, y=0;
    double w=0, h=0;
    if (sscanf(s+boundingBox.length(),"%d %d %lf %lf",&x,&y,&w,&h)==4)
    {
      *width  = static_cast<int>(std::ceil(w));
      *height = static_cast<int>(std::ceil(h));
      return true;
    }
    err("Failed to extract bounding box from generated diagram file %s\n",qPrint(fileName));
    return false;
  };
  // compressed segment start and end markers
  const std::string streamStart = "stream\n";
  const std::string streamEnd = "\nendstream";
  auto detectDeflateStreamStart = [&streamStart](const char *s)
  {
    size_t len = streamStart.length();
    bool streamOK = strncmp(s,streamStart.c_str(),len)==0;
    if (streamOK) // ASCII marker matches, check stream header bytes as well
    {
      unsigned short header1 = static_cast<unsigned char>(s[len])<<8; // CMF byte
      if (header1) // not end of string
      {
        unsigned short header = (static_cast<unsigned char>(s[len+1])) | header1; // FLG byte
        // check for correct header (see https://www.rfc-editor.org/rfc/rfc1950)
        return ((header&0x8F20)==0x0800) && (header%31)==0;
      }
    }
    return false;
  };
  const size_t l = contents.length();
  size_t i=0;
  while (i<l)
  {
    if (!isEps && contents[i]=='s' && detectDeflateStreamStart(&contents[i]))
    { // compressed stream start
      int col=17;
      i+=streamStart.length();
      const size_t start=i;
      DBG(("---- start stream at offset %08x\n",(int)i));
      while (i<l)
      {
        if (contents[i]=='\n' && strncmp(&contents[i],streamEnd.c_str(),streamEnd.length())==0)
        { // compressed block found in range [start..i]
          DBG(("\n---- end stream at offset %08x\n",(int)i));
          // decompress it into decompressBuf
          std::vector<char> decompressBuf;
          const char *source = &contents[start];
          const size_t sourceLen = i-start;
          size_t sourcePos = 0;
          decompressBuf.reserve(sourceLen*2);
          auto getter = [source,&sourcePos,sourceLen]() -> int {
            return sourcePos<sourceLen ? static_cast<unsigned char>(source[sourcePos++]) : EOF;
          };
          auto putter = [&decompressBuf](const char c) -> int {
            decompressBuf.push_back(c); return c;
          };
          Deflate(getter,putter);
          // convert decompression buffer to string
          std::string s(decompressBuf.begin(), decompressBuf.end());
          DBG(("decompressed_data=[[[\n%s\n]]]\n",s.c_str()));
          // search for bounding box marker
          const size_t idx = s.find(boundingBox);
          if (idx!=std::string::npos) // found bounding box in uncompressed data
          {
            return extractBoundingBox(s.c_str()+idx);
          }
          // continue searching after end stream marker
          i+=streamEnd.length();
          break;
        }
        else // compressed stream character
        {
          if (col>16) { col=0; DBG(("\n%08x: ",static_cast<int>(i))); }
          DBG(("%02x ",static_cast<unsigned char>(contents[i])));
          col++;
          i++;
        }
      }
    }
    else if (((isEps && contents[i]=='%') || (!isEps && contents[i]=='/')) &&
             strncmp(&contents[i],boundingBox.c_str(),boundingBox.length())==0)
    { // uncompressed bounding box
      return extractBoundingBox(&contents[i]);
    }
    else // uncompressed stream character
    {
      i++;
    }
  }
  err("Failed to find bounding box in generated diagram file %s\n",qPrint(fileName));
  // nothing found
  return false;
}
References DBG, err, extractBoundingBox(), Portable::openInputStream(), and qPrint().
Referenced by run(), and DotFilePatcher::writeVecGfxFigure().
run()
bool DotRunner::run ()
Runs dot for all jobs added.
Definition at line 281 of file dotrunner.cpp.
{
  int exitCode=0;
  QCString dotArgs;
  QCString srcFile;
  int srcLine=-1;
  // create output
  if (Config_getBool(DOT_MULTI_TARGETS))
  {
    dotArgs=QCString("\"")+m_file+"\"";
    for (auto& s: m_jobs)
    {
      dotArgs+=' ';
      dotArgs+=s.args;
    }
    if (!m_jobs.empty())
    {
      srcFile = m_jobs.front().srcFile;
      srcLine = m_jobs.front().srcLine;
    }
    if ((exitCode=Portable::system(m_dotExe,dotArgs,FALSE))!=0) goto error;
  }
  else
  {
    for (auto& s : m_jobs)
    {
      srcFile = s.srcFile;
      srcLine = s.srcLine;
      dotArgs=QCString("\"")+m_file+"\" "+s.args;
      if ((exitCode=Portable::system(m_dotExe,dotArgs,FALSE))!=0) goto error;
    }
  }
  // check output
  // As there should be only one pdf file be generated, we don't need code for regenerating multiple pdf files in one call
  for (auto& s : m_jobs)
  {
    if (s.format.startsWith("pdf"))
    {
      int width=0,height=0;
      if (!readBoundingBox(s.output,&width,&height,FALSE)) goto error;
      if ((width > MAX_LATEX_GRAPH_SIZE) || (height > MAX_LATEX_GRAPH_SIZE))
      {
        if (!resetPDFSize(width,height,getBaseNameOfOutput(s.output))) goto error;
        dotArgs=QCString("\"")+m_file+"\" "+s.args;
        if ((exitCode=Portable::system(m_dotExe,dotArgs,FALSE))!=0) goto error;
      }
    }
    if (s.format.startsWith("png"))
    {
      checkPngResult(s.output);
    }
  }
  // remove .dot files
  if (m_cleanUp)
  {
    //printf("removing dot file %s\n",qPrint(m_file));
    Portable::unlink(m_file);
  }
  // create checksum file
  if (!m_md5Hash.isEmpty())
  {
    QCString md5Name = getBaseNameOfOutput(m_file) + ".md5";
    FILE *f = Portable::fopen(md5Name,"w");
    if (f)
    {
      fwrite(m_md5Hash.data(),1,32,f);
      fclose(f);
    }
  }
  return TRUE;
error:
  err_full(srcFile,srcLine,"Problems running dot: exit code=%d, command='%s', arguments='%s'",
    exitCode,qPrint(m_dotExe),qPrint(dotArgs));
  return FALSE;
}
References checkPngResult(), Config_getBool, err_full, FALSE, Portable::fopen(), getBaseNameOfOutput(), m_cleanUp, m_dotExe, m_file, m_jobs, m_md5Hash, MAX_LATEX_GRAPH_SIZE, qPrint(), readBoundingBox(), resetPDFSize(), Portable::system(), TRUE, and Portable::unlink().
Referenced by DotManager::run(), writeDotGraphFromFile(), and writeDotImageMapFromFile().
Member Data Documentation
m_cleanUp
bool DotRunner::m_cleanUp private
Definition at line 67 of file dotrunner.h.
Referenced by DotRunner(), preventCleanUp(), and run().
m_dotExe
QCString DotRunner::m_dotExe private
Definition at line 66 of file dotrunner.h.
Referenced by DotRunner(), and run().
m_file
QCString DotRunner::m_file private
Definition at line 64 of file dotrunner.h.
Referenced by DotRunner(), and run().
m_jobs
std::vector<DotJob> DotRunner::m_jobs private
Definition at line 68 of file dotrunner.h.
Referenced by addJob(), and run().
m_md5Hash
QCString DotRunner::m_md5Hash private
Definition at line 65 of file dotrunner.h.
Referenced by DotRunner(), getMd5Hash(), and run().
The documentation for this class was generated from the following files:
src/dotrunner.h
src/dotrunner.cpp