Doxygen: TranslatorBulgarian Class Reference
TranslatorBulgarian Class Reference
#include <src/translator_bg.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation () override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool, bool full) override
QCString trMonth (int month, bool, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description.
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool single) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
QCString trDesignUnitDocumentation () override
VHDL design unit documentation.
QCString trConcept (bool first_capital, bool singular) override
C++20 concept.
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from Translator
virtual ~Translator ()=default
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) override methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include "translator.h" or "translator_adapter.h" here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 48 of file translator_bg.h.
Member Function Documentation
getLanguageString()
QCString TranslatorBulgarian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 86 of file translator_bg.h.
    {
      return "0x402 bulgarian";
    }
idLanguage()
QCString TranslatorBulgarian::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 60 of file translator_bg.h.
    { return "bulgarian"; }
latexLanguageSupportCommand()
QCString TranslatorBulgarian::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 77 of file translator_bg.h.
    {
    { return "\\usepackage[T2A]{fontenc}\n\\usepackage[bulgarian]{babel}\n"; }
    }
trAdditionalInheritedMembers()
QCString TranslatorBulgarian::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1905 of file translator_bg.h.
    { return "Допълнителни наследени членове"; }
trAll()
QCString TranslatorBulgarian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1415 of file translator_bg.h.
    {
      return "Указател към не филтриран списък на всички членове";
    }
trAndMore()
QCString TranslatorBulgarian::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1883 of file translator_bg.h.
    { return "и "+number+" повече..."; }
trAttention()
QCString TranslatorBulgarian::trAttention () inline override virtual
Implements Translator.
Definition at line 976 of file translator_bg.h.
    {
      return "Внимание";
    }
trAuthor()
QCString TranslatorBulgarian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1286 of file translator_bg.h.
    {
      QCString result((first_capital ? "Автор" : "автор"));
      if (!singular)  result+="и";
      return result;
    }
trBug()
QCString TranslatorBulgarian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1144 of file translator_bg.h.
    {
      return "Бъг";
    }
trBugList()
QCString TranslatorBulgarian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1149 of file translator_bg.h.
    {
      return "Бъгове Списък";
    }
trCallerGraph()
QCString TranslatorBulgarian::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1536 of file translator_bg.h.
    {
      return "Граф на извикванията за тази функция:";
    }
trCallGraph()
QCString TranslatorBulgarian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1420 of file translator_bg.h.
    {
      return "Граф с извикванията за тази функция:";
    }
trCiteReferences()
QCString TranslatorBulgarian::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1859 of file translator_bg.h.
    { return "Библиография"; }
trClass()
QCString TranslatorBulgarian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1207 of file translator_bg.h.
    {
      QCString result((first_capital ? "Клас" : "клас"));
      if (!singular)  result+="ове";
      return result;
    }
trClassDiagram()
QCString TranslatorBulgarian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 528 of file translator_bg.h.
    {
      return (QCString)"Диаграма на наследяване за "+clName+":";
    }
trClassDocumentation()
QCString TranslatorBulgarian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 409 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Структури от данни Документация";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Класове Документация";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorBulgarian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1107 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Структури от данни";
      }
      else
      {
        return "Класове";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorBulgarian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 185 of file translator_bg.h.
    { return "Класове Йерархия"; }
trClassHierarchyDescription()
QCString TranslatorBulgarian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 244 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Йерархичен списък на всички обекти:";
      }
      else
      {
        return "Този списък с наследявания е сортиран, "
               "но не изцяло по азбучен ред:";
      }
    }
References Config_getBool.
trClassMethods()
QCString TranslatorBulgarian::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1943 of file translator_bg.h.
    {
      return "Клас Методи";
    }
trCode()
QCString TranslatorBulgarian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 876 of file translator_bg.h.
    {
      return "изходен код";
    }
trCollaborationDiagram()
QCString TranslatorBulgarian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 831 of file translator_bg.h.
    {
      return (QCString)"Граф на зависимости за класа "+clName+":";
    }
trCompoundIndex()
QCString TranslatorBulgarian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 382 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Структури от данни Указател";
      }
      else
      {
        return "Класове Указател";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorBulgarian::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1591 of file translator_bg.h.
    { return "Типове данни Указател"; }
trCompoundList()
QCString TranslatorBulgarian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 189 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Структури от данни";
      }
      else
      {
        return "Класове Списък";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorBulgarian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 267 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Структури от данни с кратко описание:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Класове с кратко описание:";
      }
      else
      {
        return "Класове, структури, "
               "обединения и интерфейси с кратко описание:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorBulgarian::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1564 of file translator_bg.h.
    { return "Анотиран списък от типовете данни с кратки описания:"; }
trCompoundListFortran()
QCString TranslatorBulgarian::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1556 of file translator_bg.h.
    { return "Типове данни Списък"; }
trCompoundMembers()
QCString TranslatorBulgarian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 206 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Член Полета с данни";
      }
      else
      {
        return "Членове на класа";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorBulgarian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 286 of file translator_bg.h.
    {
      QCString result="Списък на всички ";
      if (!extractAll)
      {
        result+="документирани ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="членове поле, структура и обединение";
      }
      else
      {
        result+="членове на класа";
      }
      result+=" с връзки към ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="документацията за структура/обединение за всяко поле:";
        }
        else
        {
          result+="документацията на класа за всеки член:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="структурите/обединенията, към които принадлежат:";
        }
        else
        {
          result+="класовете, към които принадлежат:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorBulgarian::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1568 of file translator_bg.h.
    {
      QCString result="Списък на всички ";
      if (!extractAll)
      {
        result+="документирани ";
      }
      result+="членове типове данни";
      result+=" с препратки към ";
      if (!extractAll)
      {
         result+="документацията за структура от данни за всеки член";
      }
      else
      {
         result+="типовете данни, към които принадлежат:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorBulgarian::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1560 of file translator_bg.h.
    { return "Полета данни"; }
trCompoundReference()
QCString TranslatorBulgarian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 603 of file translator_bg.h.
    {
      QCString result=(QCString)clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Клас"; break;
        case ClassDef::Struct:     result+=" Структура"; break;
        case ClassDef::Union:      result+=" Обединение"; break;
        case ClassDef::Interface:  result+=" Интерфейс"; break;
        case ClassDef::Protocol:   result+=" Протокол"; break;
        case ClassDef::Category:   result+=" Категория"; break;
        case ClassDef::Exception:  result+=" Изключение"; break;
        default: break;
      }
      if (isTemplate) result+=" Шаблон";
      result+=" Препратка";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorBulgarian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1632 of file translator_bg.h.
    {
      QCString result=(QCString)clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Модул"; break;
        case ClassDef::Struct:     result+=" Тип"; break;
        case ClassDef::Union:      result+=" Обединение"; break;
        case ClassDef::Interface:  result+=" Интерфейс"; break;
        case ClassDef::Protocol:   result+=" Протокол"; break;
        case ClassDef::Category:   result+=" Категория"; break;
        case ClassDef::Exception:  result+=" Изключение"; break;
        default: break;
      }
      if (isTemplate) result+=" Шаблон";
      result+=" Отнася се";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice()
QCString TranslatorBulgarian::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) inline override virtual
Implements Translator.
Definition at line 2233 of file translator_bg.h.
    {
      QCString result=(QCString)clName;
      if (isLocal) result+=" Локален";
      switch(compType)
      {
        case ClassDef::Class:      result+=" Клас"; break;
        case ClassDef::Struct:     result+=" Структура"; break;
        case ClassDef::Union:      result+=" Обединение"; break;
        case ClassDef::Interface:  result+=" Интерфейс"; break;
        case ClassDef::Protocol:   result+=" Протокол"; break;
        case ClassDef::Category:   result+=" Категория"; break;
        case ClassDef::Exception:  result+=" Изключение"; break;
        default: break;
      }
      result+=" Отнася се";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorBulgarian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 504 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Структури от данни";
      }
      else
      {
        return "Класове";
      }
    }
References Config_getBool.
trConcept()
QCString TranslatorBulgarian::trConcept (bool first_capital, bool singular) inline override virtual
C++20 concept.
Implements Translator.
Definition at line 2281 of file translator_bg.h.
    {
      QCString result((first_capital ? "Концепци" : "концепци"));
          if (singular)  result+="я"; else result+="и";
      return result;
    }
trConceptDefinition()
QCString TranslatorBulgarian::trConceptDefinition () inline override virtual
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2317 of file translator_bg.h.
    {
      return "Дефиниция на концепция";
    }
trConceptDocumentation()
QCString TranslatorBulgarian::trConceptDocumentation () inline override virtual
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2304 of file translator_bg.h.
    { return "Концепции Документация"; }
trConceptIndex()
QCString TranslatorBulgarian::trConceptIndex () inline override virtual
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2300 of file translator_bg.h.
    { return "Концепции Указател"; }
trConceptList()
QCString TranslatorBulgarian::trConceptList () inline override virtual
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2296 of file translator_bg.h.
    { return "Концепции Списък"; }
trConceptListDescription()
QCString TranslatorBulgarian::trConceptListDescription (bool extractAll) inline override virtual
used as an introduction to the concept list
Implements Translator.
Definition at line 2308 of file translator_bg.h.
    {
      QCString result="Списък на всички ";
      if (!extractAll) result+="документирани ";
      result+="концепции с кратко описание:";
      return result;
    }
trConceptReference()
QCString TranslatorBulgarian::trConceptReference (const QCString & conceptName) inline override virtual
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2288 of file translator_bg.h.
    {
      QCString result=conceptName;
      result+=" Концепции Справка";
      return result;
    }
trConstantDocumentation()
QCString TranslatorBulgarian::trConstantDocumentation () inline override virtual
Implements Translator.
Definition at line 2141 of file translator_bg.h.
    {
        return "Константи Документация";
    }
trConstantGroupReference()
QCString TranslatorBulgarian::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1980 of file translator_bg.h.
    {
      QCString result=namespaceName;
      result+=" Постоянни групи Справка";
      return result;
    }
trConstantGroups()
QCString TranslatorBulgarian::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1976 of file translator_bg.h.
    { return "Постоянни групи"; }
trConstants()
QCString TranslatorBulgarian::trConstants () inline override virtual
Implements Translator.
Definition at line 2137 of file translator_bg.h.
    {
        return "Константи";
    }
trConstructorDocumentation()
QCString TranslatorBulgarian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 841 of file translator_bg.h.
    {
      return "Конструктор & Деструктор Документация";
    }
trCopyright()
QCString TranslatorBulgarian::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1863 of file translator_bg.h.
    { return "Авторско право"; }
trCustomReference()
QCString TranslatorBulgarian::trCustomReference (const QCString & name) inline override virtual
Implements Translator.
Definition at line 2133 of file translator_bg.h.
    { return QCString(name)+" Отнася се"; }
trDataMemberDocumentation()
QCString TranslatorBulgarian::trDataMemberDocumentation () inline override virtual
Implements Translator.
Definition at line 2263 of file translator_bg.h.
    {
        return "Членове Данни Документация";
    }
trDataMembers()
QCString TranslatorBulgarian::trDataMembers () inline override virtual
Implements Translator.
Definition at line 2259 of file translator_bg.h.
    {
        return "Членове Данни";
    }
trDataTypes()
QCString TranslatorBulgarian::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1615 of file translator_bg.h.
    { return "Типове данни"; }
trDate()
QCString TranslatorBulgarian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 542 of file translator_bg.h.
    { return "Дата"; }
trDateTime()
QCString TranslatorBulgarian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1816 of file translator_bg.h.
    {
      static const char *days[]   = { "Пн","Вт","Ср","Чт","Пт","Сб","Нд" };
      static const char *months[] = { "Яну","Фев","Мар","Апр","Май","Юни","Юли","Авг","Сеп","Окт","Ное","Дек" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorBulgarian::trDayOfWeek (int dayOfWeek, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1836 of file translator_bg.h.
    {
      static const char *days_short[]   = { "пон", "вт", "ср", "четв", "пет", "съб", "нед" };
      static const char *days_full[]    = { "понеделник", "вторник", "сряда", "четвъртък", "петък", "събота", "неделя" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayPeriod()
QCString TranslatorBulgarian::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1848 of file translator_bg.h.
    {
      static const char *dayPeriod[] = { "пр.об.", "сл.об." };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorBulgarian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 808 of file translator_bg.h.
    {
      return "Виж дефиницията във файла @1 ред @0.";
    }
trDefinedIn()
QCString TranslatorBulgarian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 173 of file translator_bg.h.
    { return "дефинирани в"; }
trDefinedInSourceFile()
QCString TranslatorBulgarian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 812 of file translator_bg.h.
    {
      return "Виж дефиницията във файла @0.";
    }
trDefineDocumentation()
QCString TranslatorBulgarian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 474 of file translator_bg.h.
    { return "Макро дефиниции Документация"; }
trDefines()
QCString TranslatorBulgarian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 438 of file translator_bg.h.
    { return "Макроси"; }
trDefineValue()
QCString TranslatorBulgarian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1134 of file translator_bg.h.
    {
      return "Макроопределение:";
    }
trDeprecated()
QCString TranslatorBulgarian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 821 of file translator_bg.h.
    {
      return "Остарело";
    }
trDeprecatedList()
QCString TranslatorBulgarian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1343 of file translator_bg.h.
    {
      return "Остарели дефиниции и декларации Списък";
    }
trDesignUnitDocumentation()
QCString TranslatorBulgarian::trDesignUnitDocumentation () inline override virtual
VHDL design unit documentation.
Implements Translator.
Definition at line 2273 of file translator_bg.h.
    { return "Проектни единици Документация"; }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorBulgarian::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Implements Translator.
Definition at line 2024 of file translator_bg.h.
    { return "Проектни единици Йерархия"; }
trDesignUnitIndex()
QCString TranslatorBulgarian::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Implements Translator.
Definition at line 2039 of file translator_bg.h.
    { return "Проектна единица Указател"; }
trDesignUnitList()
QCString TranslatorBulgarian::trDesignUnitList () inline override virtual
VHDL design unit list.
Implements Translator.
Definition at line 2027 of file translator_bg.h.
    { return "Проектни единици Списък"; }
trDesignUnitListDescription()
QCString TranslatorBulgarian::trDesignUnitListDescription () inline override virtual
VHDL design unit list description.
Implements Translator.
Definition at line 2033 of file translator_bg.h.
    {
        return "Here is a list of all design unit members with links to "
            "the Entities they belong to:";
    }
trDesignUnitMembers()
QCString TranslatorBulgarian::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Implements Translator.
Definition at line 2030 of file translator_bg.h.
    { return "Проектна единица Членове"; }
trDesignUnits()
QCString TranslatorBulgarian::trDesignUnits () inline override virtual
VHDL design units.
Implements Translator.
Definition at line 2042 of file translator_bg.h.
    { return "Проектни единици"; }
trDetailedDescription()
QCString TranslatorBulgarian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 102 of file translator_bg.h.
    { return "Подробно описание"; }
trDetailLevel()
QCString TranslatorBulgarian::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1875 of file translator_bg.h.
    { return "ниво на детайлност"; }
trDetails()
QCString TranslatorBulgarian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 106 of file translator_bg.h.
    { return "Подробности"; }
trDictionaries()
QCString TranslatorBulgarian::trDictionaries () inline override virtual
Implements Translator.
Definition at line 2153 of file translator_bg.h.
    {
        return "Речници";
    }
trDictionaryDocumentation()
QCString TranslatorBulgarian::trDictionaryDocumentation () inline override virtual
Implements Translator.
Definition at line 2157 of file translator_bg.h.
    {
        return "Речници Документация";
    }
trDir()
QCString TranslatorBulgarian::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1510 of file translator_bg.h.
    {
      QCString result((first_capital ? "Директори" : "директори"));
      if (singular) result+="я"; else result+="и";
      return result;
    }
trDirDepGraph()
QCString TranslatorBulgarian::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1867 of file translator_bg.h.
    { return QCString("Граф на зависимостта на директория за ")+name+":"; }
trDirDocumentation()
QCString TranslatorBulgarian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1492 of file translator_bg.h.
    { return "Директории Документация"; }
trDirectories()
QCString TranslatorBulgarian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1498 of file translator_bg.h.
    { return "Директории"; }
trDirIndex()
QCString TranslatorBulgarian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1486 of file translator_bg.h.
    { return "Директории Йерархия"; }
trDirReference()
QCString TranslatorBulgarian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1504 of file translator_bg.h.
    { QCString result=dirName; result+=" Директория Съдържание"; return result; }
trDirRelation()
QCString TranslatorBulgarian::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1755 of file translator_bg.h.
    {
      return QCString(name)+" Връзка";
    }
trDocumentation()
QCString TranslatorBulgarian::trDocumentation () inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 364 of file translator_bg.h.
    { return "Документация"; }
trEnumerations()
QCString TranslatorBulgarian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 450 of file translator_bg.h.
    { return "Изброявания"; }
trEnumerationTypeDocumentation()
QCString TranslatorBulgarian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 486 of file translator_bg.h.
    { return "Изброени типове Документация"; }
trEnumerationValueDocumentation()
QCString TranslatorBulgarian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1544 of file translator_bg.h.
    { return "Изброяване Документация"; }
trEnumerationValues()
QCString TranslatorBulgarian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 468 of file translator_bg.h.
    { return "Елементи на изброяване"; }
trEnumGeneratedFromFiles()
QCString TranslatorBulgarian::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1887 of file translator_bg.h.
    { QCString result = "Документацията за това изброяване е генерирана от ";
          if (single) result+="следният файл:"; else result+="следните файлове:";
      result+=":";
      return result;
    }
trEnumName()
QCString TranslatorBulgarian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 165 of file translator_bg.h.
    { return "изброяване"; }
trEnumReference()
QCString TranslatorBulgarian::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1895 of file translator_bg.h.
    { return QCString(name)+" Изброяване Справка"; }
trEnumValue()
QCString TranslatorBulgarian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 169 of file translator_bg.h.
    { return "елементи на изброяване"; }
trEventDocumentation()
QCString TranslatorBulgarian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1360 of file translator_bg.h.
    {
      return "Събития Документация";
    }
trEvents()
QCString TranslatorBulgarian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1355 of file translator_bg.h.
    {
      return "Събития";
    }
trExamples()
QCString TranslatorBulgarian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 236 of file translator_bg.h.
    { return "Примери"; }
trExamplesDescription()
QCString TranslatorBulgarian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 350 of file translator_bg.h.
    { return "Списък на всички примери:"; }
trExceptionDocumentation()
QCString TranslatorBulgarian::trExceptionDocumentation () inline override virtual
Implements Translator.
Definition at line 2229 of file translator_bg.h.
    {
        return "Изключения Документация";
    }
trExceptionHierarchy()
QCString TranslatorBulgarian::trExceptionHierarchy () inline override virtual
Implements Translator.
Definition at line 2221 of file translator_bg.h.
    {
        return "Изключения Йерархия";
    }
trExceptionHierarchyDescription()
QCString TranslatorBulgarian::trExceptionHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2225 of file translator_bg.h.
    {
        return "Този списък на наследяване е сортиран, но не напълно, по азбучен ред:";
    }
trExceptionIndex()
QCString TranslatorBulgarian::trExceptionIndex () inline override virtual
Implements Translator.
Definition at line 2209 of file translator_bg.h.
    {
        return "Изключения Указател";
    }
trExceptionList()
QCString TranslatorBulgarian::trExceptionList () inline override virtual
Implements Translator.
Definition at line 2213 of file translator_bg.h.
    {
        return "Изключения Списък";
    }
trExceptionListDescription()
QCString TranslatorBulgarian::trExceptionListDescription () inline override virtual
Implements Translator.
Definition at line 2217 of file translator_bg.h.
    {
        return "Изключения с кратки описания:";
    }
trExceptions()
QCString TranslatorBulgarian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 558 of file translator_bg.h.
    { return "Изключения"; }
trExtendsClass()
QCString TranslatorBulgarian::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1935 of file translator_bg.h.
    {
      return "Разширява класа @0.";
    }
trFile()
QCString TranslatorBulgarian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1218 of file translator_bg.h.
    {
      QCString result((first_capital ? "Файл" : "файл"));
      if (!singular)  result+="ове";
      return result;
    }
trFileDocumentation()
QCString TranslatorBulgarian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 428 of file translator_bg.h.
    { return "Файлове Документация"; }
trFileIn()
QCString TranslatorBulgarian::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1792 of file translator_bg.h.
    {
      return (QCString)"Файл в "+name;
    }
trFileIndex()
QCString TranslatorBulgarian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 397 of file translator_bg.h.
    { return "Файлове Списък"; }
trFileList()
QCString TranslatorBulgarian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 202 of file translator_bg.h.
    { return "Файлове Списък"; }
trFileListDescription()
QCString TranslatorBulgarian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 258 of file translator_bg.h.
    {
      QCString result="Пълен списък с ";
      if (!extractAll) result+="документирани ";
      result+="файлове с кратко описание:";
      return result;
    }
trFileMembers()
QCString TranslatorBulgarian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 219 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Глобални";
      }
      else
      {
        return "Файлове Членове";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorBulgarian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 328 of file translator_bg.h.
    {
      QCString result="Списък на всички ";
      if (!extractAll) result+="документирани ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="функции, променливи, макроопределения, изброявания и дефиниции на типове";
      }
      else
      {
        result+="членове на файлове";
      }
      result+=" с връзки към ";
      if (extractAll)
        result+="файловете,към които принадлежат:";
      else
        result+="документацията:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorBulgarian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 625 of file translator_bg.h.
    {
      QCString result=fileName;
      result+=" Файл Справка";
      return result;
    }
trFriends()
QCString TranslatorBulgarian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 585 of file translator_bg.h.
    { return "Приятели"; }
trFunctionAndProc()
QCString TranslatorBulgarian::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Implements Translator.
Definition at line 2045 of file translator_bg.h.
    { return "Функции/Процедури/Процеси"; }
trFunctionDocumentation()
QCString TranslatorBulgarian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 492 of file translator_bg.h.
    { return "Функции Документация"; }
trFunctions()
QCString TranslatorBulgarian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 456 of file translator_bg.h.
    { return "Функции"; }
trGeneratedAt()
QCString TranslatorBulgarian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 519 of file translator_bg.h.
    {
      QCString result=(QCString)"Генерирано на "+date;
      if (!projName.isEmpty()) result+=(QCString)" за "+projName;
      result+=(QCString)" от";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorBulgarian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 157 of file translator_bg.h.
    { QCString result="Генерирано автоматично от Doxygen";
      if (!s.isEmpty()) result+=(QCString)" за "+s;
      result+=" от изходния код.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorBulgarian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 562 of file translator_bg.h.
    { return "Генериран от"; }
trGeneratedFromFiles()
QCString TranslatorBulgarian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 764 of file translator_bg.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result=(QCString)"Документация за ";
      switch(compType)
      {
        case ClassDef::Class:      result+=vhdlOpt?"проектна единица":"клас"; break;
        case ClassDef::Struct:     result+="структура"; break;
        case ClassDef::Union:      result+="обединение"; break;
        case ClassDef::Interface:  result+="интерфейс"; break;
        case ClassDef::Protocol:   result+="протокол"; break;
        case ClassDef::Category:   result+="категория"; break;
        case ClassDef::Exception:  result+="изключение"; break;
        default: break;
      }
      result+=" генериран от ";
      if (single) result+="следният файл:"; else result+="следните файлове:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorBulgarian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1701 of file translator_bg.h.
    {
      // single is true implies a single file
      QCString result=(QCString)"Документацията за ";
      switch(compType)
      {
        case ClassDef::Class:      result+="модул"; break;
        case ClassDef::Struct:     result+="тип"; break;
        case ClassDef::Union:      result+="обединение"; break;
        case ClassDef::Interface:  result+="интерфейс"; break;
        case ClassDef::Protocol:   result+="протокол"; break;
        case ClassDef::Category:   result+="категория"; break;
        case ClassDef::Exception:  result+="изключение"; break;
        default: break;
      }
      result+=" беше генериран ";
      if (single) result+="от следният файл:"; else result+="от следните файлове:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorBulgarian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1273 of file translator_bg.h.
    {
      QCString result((first_capital ? "Глобалн" : "глобалн"));
          result+=(singular ? "а" : "и");
      return result;
    }
trGlobalNamespace()
QCString TranslatorBulgarian::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1767 of file translator_bg.h.
    {
      return "Глобални именни пространства";
    }
trGotoDocumentation()
QCString TranslatorBulgarian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 851 of file translator_bg.h.
    {
      return "Вижте документацията за този файл.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorBulgarian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 884 of file translator_bg.h.
    {
      return "Виж графичен вид на йерархията на класовете";
    }
trGotoSourceCode()
QCString TranslatorBulgarian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 846 of file translator_bg.h.
    {
      return "Вижте изходният код на този файл.";
    }
trGotoTextualHierarchy()
QCString TranslatorBulgarian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 888 of file translator_bg.h.
    {
      return "Виж текстови вид на йерархията на класовете";
    }
trGraphicalHierarchy()
QCString TranslatorBulgarian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 880 of file translator_bg.h.
    {
      return "Йерархия на класовете Графичен вид";
    }
trGroup()
QCString TranslatorBulgarian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1240 of file translator_bg.h.
    {
      QCString result((first_capital ? "Груп" : "груп"));
          result+=(singular ? "а" : "и");
      return result;
    }
trHierarchicalIndex()
QCString TranslatorBulgarian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 376 of file translator_bg.h.
    { return "Класове Йерархичен указател"; }
trImplementedFromList()
QCString TranslatorBulgarian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1311 of file translator_bg.h.
    {
      return "Заменя "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorBulgarian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1319 of file translator_bg.h.
    {
      return "Заменя в "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorBulgarian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 980 of file translator_bg.h.
    {
      return "Граф на файлове показващ, кой файлове включват "
             "явно или косвено този файл:";
    }
trInclDepGraph()
QCString TranslatorBulgarian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 836 of file translator_bg.h.
    {
      return (QCString)"Граф на включените заглавни файлове за "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorBulgarian::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1801 of file translator_bg.h.
    {
      return (QCString)"Включва файла в "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorBulgarian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 151 of file translator_bg.h.
    { return ", включително всички наследени членове."; }
trInheritedByList()
QCString TranslatorBulgarian::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 697 of file translator_bg.h.
    {
      return "Производни класове "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorBulgarian::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1899 of file translator_bg.h.
    { return QCString(members)+" наследен от "+what; }
trInheritsList()
QCString TranslatorBulgarian::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 689 of file translator_bg.h.
    {
      return "Базови класове "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorBulgarian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 871 of file translator_bg.h.
    {
      return "Първоначална стойност:";
    }
trInstanceMethods()
QCString TranslatorBulgarian::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1951 of file translator_bg.h.
    {
      return "Общодостъпни Методи";
    }
trInterfaceDocumentation()
QCString TranslatorBulgarian::trInterfaceDocumentation () inline override virtual
Implements Translator.
Definition at line 2185 of file translator_bg.h.
    {
        return "Интерфейси Документация";
    }
trInterfaceHierarchy()
QCString TranslatorBulgarian::trInterfaceHierarchy () inline override virtual
Implements Translator.
Definition at line 2177 of file translator_bg.h.
    {
        return "Интерфейси Йерархия";
    }
trInterfaceHierarchyDescription()
QCString TranslatorBulgarian::trInterfaceHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2181 of file translator_bg.h.
    {
        return "Този списък на наследяване е сортиран, но не напълно, по азбучен ред:";
    }
trInterfaceIndex()
QCString TranslatorBulgarian::trInterfaceIndex () inline override virtual
Implements Translator.
Definition at line 2165 of file translator_bg.h.
    {
        return "Интерфейси Указател";
    }
trInterfaceList()
QCString TranslatorBulgarian::trInterfaceList () inline override virtual
Implements Translator.
Definition at line 2169 of file translator_bg.h.
    {
        return "Интерфейси списък";
    }
trInterfaceListDescription()
QCString TranslatorBulgarian::trInterfaceListDescription () inline override virtual
Implements Translator.
Definition at line 2173 of file translator_bg.h.
    {
        return "Интерфейсите с кратки описания:";
    }
trInterfaces()
QCString TranslatorBulgarian::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1968 of file translator_bg.h.
    { return "Експортирани интерфейси"; }
trInvariant()
QCString TranslatorBulgarian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 866 of file translator_bg.h.
    {
      return "Инвариант";
    }
trISOLang()
QCString TranslatorBulgarian::trISOLang () inline override virtual
Implements Translator.
Definition at line 82 of file translator_bg.h.
    {
      return "bg";
    }
trLegend()
QCString TranslatorBulgarian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1067 of file translator_bg.h.
    {
      return "легенда";
    }
trLegendDocs()
QCString TranslatorBulgarian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1002 of file translator_bg.h.
    {
      return
        "Тази страница обяснява как да интерпретирате графиките, генерирани "
        "от doxygen.<p>\n"
        "Разгледайте следният пример:\n"
        "\\code\n"
        "/*! Невидим клас поради съкращаване */\n"
        "class Invisible { };\n\n"
        "/*! Съкратен клас, наследствена връзка е скрита */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Класът не е документиран с doxygen коментари */\n"
        "class Undocumented { };\n\n"
        "/*! Клас, който се наследява чрез публично наследяване */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Шаблонен клас */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Клас, който се наследява чрез защитено наследяване */\n"
        "class ProtectedBase { };\n\n"
        "/*! Клас, който се наследява чрез частно наследяване */\n"
        "class PrivateBase { };\n\n"
        "/*! Клас, използващ наследеният клас */\n"
        "class Used { };\n\n"
        "/*! Супер клас, който наследява редица други класове */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Правоъгълниците в този граф имат следното значение:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Правоъгълниците в този граф имат следното значение:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%Запълненият сиво правоъгълник представлява структурата или клас, "
        "за който е създаден графа.</li>\n"
        "<li>%Правоъгълника с черна рамка обозначава документирана структура или клас.</li>\n"
        "<li>%Правоъгълника със сива рамка обозначава недокументирана структура или клас.</li>\n"
        "<li>%Правоъгълника с червена рамка обозначава документирана структура или клас за"
        "който не са показани всички отношения наследяване/съдържание. %A Графa e"
        "съкратен, ако не се вписва в определените граници.</li>\n"
        "</ul>\n"
        "<p>\n"
        "Стрелките имат следното значение:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%Тъмносиня стрелка се използва за визуализиране на публично наследство "
        "между два класа.</li>\n"
        "<li>%Тъмнозелена стрелка се използва за защитено наследяване.</li>\n"
        "<li>%Тъмночервена стрелка се използва за частно наследяване.</li>\n"
        "<li>%Лилава пунктирана стрелка се използва, ако клас се съдържа или използва "
        "от друг клас. Стрелката указва променлива(и) "
        "чрез който е достъпен посоченият клас или структура.</li>\n"
        "<li>%Жълта пунктирана стрелка обозначава връзка между екземпляр на шаблон и "
        "класът шаблон, от който е създаден. Стрелката указва "
        "параметрите на шаблона на екземпляра.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorBulgarian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 995 of file translator_bg.h.
    {
      return "Графична легенда";
    }
trListOfAllMembers()
QCString TranslatorBulgarian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 139 of file translator_bg.h.
    { return "Списък на всички членове"; }
trLoading()
QCString TranslatorBulgarian::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1761 of file translator_bg.h.
    {
      return "Зареждане...";
    }
trMainPage()
QCString TranslatorBulgarian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 795 of file translator_bg.h.
    { return "Главна страница"; }
trMember()
QCString TranslatorBulgarian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1262 of file translator_bg.h.
    {
      QCString result((first_capital ? "Член" : "член"));
      if (!singular)  result+="ове";
      return result;
    }
trMemberDataDocumentation()
QCString TranslatorBulgarian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 122 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Полета Документация";
      }
      else
      {
        return "Член данни Документация";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorBulgarian::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 114 of file translator_bg.h.
    { return "Членове Изброявания Документация"; }
trMemberFunctionDocumentation()
QCString TranslatorBulgarian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 118 of file translator_bg.h.
    { return "Членове Функции(методи) Документация"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorBulgarian::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1552 of file translator_bg.h.
    { return "Функции/подпрограми Документация"; }
trMemberList()
QCString TranslatorBulgarian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 143 of file translator_bg.h.
    { return "Членове Списък"; }
trMemberTypedefDocumentation()
QCString TranslatorBulgarian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 110 of file translator_bg.h.
    { return "Членове Дефинирани типове Документация"; }
trMethodDocumentation()
QCString TranslatorBulgarian::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1958 of file translator_bg.h.
    {
      return "Метод Документация";
    }
trModule()
QCString TranslatorBulgarian::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1691 of file translator_bg.h.
    {
      QCString result((first_capital ? "Модул" : "модул"));
      if (!singular)  result+="и";
      return result;
    }
trModuleDocumentation()
QCString TranslatorBulgarian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 403 of file translator_bg.h.
    { return "Групи Документация"; }
trModuleIndex()
QCString TranslatorBulgarian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 370 of file translator_bg.h.
    { return "Групи Указател"; }
trModuleReference()
QCString TranslatorBulgarian::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1653 of file translator_bg.h.
    {
      QCString result=namespaceName;
      result+=" Модул Справка";
      return result;
    }
trModules()
QCString TranslatorBulgarian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 181 of file translator_bg.h.
    { return "Групи"; }
trModulesDescription()
QCString TranslatorBulgarian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 358 of file translator_bg.h.
    { return "Списък на всички групи:"; }
trModulesIndex()
QCString TranslatorBulgarian::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1684 of file translator_bg.h.
    { return "Модули Указател"; }
trModulesList()
QCString TranslatorBulgarian::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1619 of file translator_bg.h.
    { return "Модули Списък"; }
trModulesListDescription()
QCString TranslatorBulgarian::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1623 of file translator_bg.h.
    {
      QCString result="Списък на всички ";
      if (!extractAll) result+="документирани ";
      result+="модули с кратко описание:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorBulgarian::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1665 of file translator_bg.h.
    {
      QCString result="Списък на всички ";
      if (!extractAll) result+="документирани ";
      result+="членове на модула с връзки към ";
      if (extractAll)
      {
        result+="документацията на модула за всеки член:";
      }
      else
      {
        result+="модулите, към които принадлежат:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorBulgarian::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1661 of file translator_bg.h.
    { return "Модул Членове"; }
trMonth()
QCString TranslatorBulgarian::trMonth (int month, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1842 of file translator_bg.h.
    {
      static const char *months_short[] = { "яну", "фев", "мар", "апр", "май", "юни", "юли", "авг", "сеп", "окт", "ное", "дек" };
      static const char *months_full[]  = { "януари", "февруари", "март", "април", "май", "юни", "юли", "август", "септември", "октомври", "ноември", "декември" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMore()
QCString TranslatorBulgarian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 135 of file translator_bg.h.
    { return "Допълнително..."; }
trNamespace()
QCString TranslatorBulgarian::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1229 of file translator_bg.h.
    {
      QCString result((first_capital ? "Именн" : "именн"));
          result+=(singular ? "о пространство" : "и пространства");
      return result;
    }
trNamespaceDocumentation()
QCString TranslatorBulgarian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 744 of file translator_bg.h.
    { return "Именни пространства Документация"; }
trNamespaceIndex()
QCString TranslatorBulgarian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 738 of file translator_bg.h.
    { return "Именни пространства Указател"; }
trNamespaceList()
QCString TranslatorBulgarian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 570 of file translator_bg.h.
    { return "Именни пространства Списък "; }
trNamespaceListDescription()
QCString TranslatorBulgarian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 574 of file translator_bg.h.
    {
      QCString result="пълен списък с ";
      if (!extractAll) result+="документирани ";
      result+="именни пространства с кратко описание:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorBulgarian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 724 of file translator_bg.h.
    {
      QCString result="Пълен списък с ";
      if (!extractAll) result+="документирани ";
      result+="членове именни пространства с връзки към ";
      if (extractAll)
        result+="документация за именно пространство за всеки член:";
      else
        result+="именните пространства към които принадлежат:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorBulgarian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 719 of file translator_bg.h.
    { return "Членове Именни пространства";
        }
trNamespaceReference()
QCString TranslatorBulgarian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 633 of file translator_bg.h.
    {
      QCString result=namespaceName;
      result+=" Именно пространството Справка";
      return result;
    }
trNamespaces()
QCString TranslatorBulgarian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 754 of file translator_bg.h.
    { return "Именни пространства"; }
trNoMatches()
QCString TranslatorBulgarian::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1779 of file translator_bg.h.
    {
      return "Не намерено";
    }
trNote()
QCString TranslatorBulgarian::trNote () inline override virtual
Implements Translator.
Definition at line 901 of file translator_bg.h.
    {
      return "Пояснение";
    }
trOperationDocumentation()
QCString TranslatorBulgarian::trOperationDocumentation () inline override virtual
Implements Translator.
Definition at line 2255 of file translator_bg.h.
    {
        return "Операции Документация";
    }
trOperations()
QCString TranslatorBulgarian::trOperations () inline override virtual
Implements Translator.
Definition at line 2251 of file translator_bg.h.
    {
        return "Операции";
    }
trOverloadText()
QCString TranslatorBulgarian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1524 of file translator_bg.h.
    {
       return "Това е преопределена член функция, "
              "предоставена за удобство. Различава се от спомената по горе "
              "функция само по броя на фактическите аргументи.";
    }
trPackage()
QCString TranslatorBulgarian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1119 of file translator_bg.h.
    {
      return (QCString)"Пакет "+name;
    }
trPackageAttribs()
QCString TranslatorBulgarian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1396 of file translator_bg.h.
    {
      return "Променливи с област на видимост пакет";
    }
trPackageFunctions()
QCString TranslatorBulgarian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1378 of file translator_bg.h.
    {
      return "Функции с област на видимост пакет";
    }
trPackageListDescription()
QCString TranslatorBulgarian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1124 of file translator_bg.h.
    {
      return "Списък на пакетите с кратки описания(ако има такива):";
    }
trPackageMembers()
QCString TranslatorBulgarian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1382 of file translator_bg.h.
    {
      return "Членове с област на видимост пакет";
    }
trPackages()
QCString TranslatorBulgarian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1129 of file translator_bg.h.
    {
      return "Пакети";
    }
trPackageTypes()
QCString TranslatorBulgarian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1371 of file translator_bg.h.
    {
      return "Типове с област на видимост пакет";
    }
trPage()
QCString TranslatorBulgarian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1251 of file translator_bg.h.
    {
      QCString result((first_capital ? "Страниц" : "странц"));
          result+=(singular ? "а" : "и");
      return result;
    }
trPageAbbreviation()
QCString TranslatorBulgarian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 801 of file translator_bg.h.
    { return "стр."; }
trPageIndex()
QCString TranslatorBulgarian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 892 of file translator_bg.h.
    {
      return "Тематични описания Указател";
    }
trPanelSynchronisationTooltip()
QCString TranslatorBulgarian::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1916 of file translator_bg.h.
    {
      QCString opt = enable ? "включване" : "изключване";
      return "натиснете на "+opt+" за синхронизация на панела";
    }
trParameters()
QCString TranslatorBulgarian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 554 of file translator_bg.h.
    { return "Аргументи"; }
trPostcondition()
QCString TranslatorBulgarian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 861 of file translator_bg.h.
    {
      return "Следусловие";
    }
trPrecondition()
QCString TranslatorBulgarian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 856 of file translator_bg.h.
    {
      return "Предпоставка";
    }
trPrivateAttribs()
QCString TranslatorBulgarian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 940 of file translator_bg.h.
    {
      return "Частни атрибути";
    }
trPrivateMembers()
QCString TranslatorBulgarian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 654 of file translator_bg.h.
    { return "Частни членове функции"; }
trPrivateSlots()
QCString TranslatorBulgarian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 656 of file translator_bg.h.
    { return "Частни слотове"; }
trPrivateTypes()
QCString TranslatorBulgarian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 936 of file translator_bg.h.
    {
      return "Частни типове";
    }
trProperties()
QCString TranslatorBulgarian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1092 of file translator_bg.h.
    {
      return "Свойства";
    }
trPropertyDocumentation()
QCString TranslatorBulgarian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1097 of file translator_bg.h.
    {
      return "Свойство Документация";
    }
trProtectedAttribs()
QCString TranslatorBulgarian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 928 of file translator_bg.h.
    {
      return "Защитени атрибути";
    }
trProtectedMembers()
QCString TranslatorBulgarian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 648 of file translator_bg.h.
    { return "Защитени членове функции"; }
trProtectedSlots()
QCString TranslatorBulgarian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 650 of file translator_bg.h.
    { return "Защитени слотове"; }
trProtectedTypes()
QCString TranslatorBulgarian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 924 of file translator_bg.h.
    {
      return "Защитени типове";
    }
trProvidedByCategory()
QCString TranslatorBulgarian::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1926 of file translator_bg.h.
    {
      return "По групи @0.";
    }
trPublicAttribs()
QCString TranslatorBulgarian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 909 of file translator_bg.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Полета данни";
      }
      else
      {
        return "Общодостъпни атрибути";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorBulgarian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 640 of file translator_bg.h.
    { return "Общодостъпни членове функции"; }
trPublicSlots()
QCString TranslatorBulgarian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 642 of file translator_bg.h.
    { return "Общодостъпни слотове"; }
trPublicTypes()
QCString TranslatorBulgarian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 905 of file translator_bg.h.
    {
      return "Общодостъпни типове";
    }
trReferencedBy()
QCString TranslatorBulgarian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 968 of file translator_bg.h.
    {
      return "Използва се";
    }
trReferenceManual()
QCString TranslatorBulgarian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 432 of file translator_bg.h.
    { return "Помощно ръководство"; }
trReferences()
QCString TranslatorBulgarian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1299 of file translator_bg.h.
    {
      return "Кръстосани препратки";
    }
trReimplementedFromList()
QCString TranslatorBulgarian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 705 of file translator_bg.h.
    {
      return "Заменя наследеният метод "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorBulgarian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 713 of file translator_bg.h.
    {
      return "Заменя в "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorBulgarian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 595 of file translator_bg.h.
    { return "Приятели и Свързани функции Документация"; }
trRelatedFunctions()
QCString TranslatorBulgarian::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 94 of file translator_bg.h.
    { return "Функции, свързани с класа"; }
trRelatedPages()
QCString TranslatorBulgarian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 232 of file translator_bg.h.
    { return "Свързани страници"; }
trRelatedPagesDescription()
QCString TranslatorBulgarian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 354 of file translator_bg.h.
    { return "Списък на всички свързани страници с документация:"; }
trRelatedSubscript()
QCString TranslatorBulgarian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 98 of file translator_bg.h.
    { return "(Имайте предвид, че тези функции не са членове на класа.)"; }
trRemarks()
QCString TranslatorBulgarian::trRemarks () inline override virtual
Implements Translator.
Definition at line 972 of file translator_bg.h.
    {
      return "Забележки";
    }
trReturns()
QCString TranslatorBulgarian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 546 of file translator_bg.h.
    { return "Връща"; }
trReturnValues()
QCString TranslatorBulgarian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 790 of file translator_bg.h.
    { return "Връщана стойност"; }
trRTFansicp()
QCString TranslatorBulgarian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1183 of file translator_bg.h.
    {
      return "1251";
    }
trRTFCharSet()
QCString TranslatorBulgarian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1192 of file translator_bg.h.
    {
      return "204";
    }
trRTFGeneralIndex()
QCString TranslatorBulgarian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1198 of file translator_bg.h.
    {
      return "Азбучен указател";
    }
trRTFTableOfContents()
QCString TranslatorBulgarian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1331 of file translator_bg.h.
    {
      return "Съдържание";
    }
trSearch()
QCString TranslatorBulgarian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 240 of file translator_bg.h.
    { return "Търсене"; }
trSearching()
QCString TranslatorBulgarian::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1773 of file translator_bg.h.
    {
      return "Търсене...";
    }
trSearchMatches()
QCString TranslatorBulgarian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1463 of file translator_bg.h.
    {
      return "Намерено:";
    }
trSearchResults()
QCString TranslatorBulgarian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1444 of file translator_bg.h.
    {
      if (numDocuments==0)
      {
        return "За съжаление няма документи, отговарящи на вашата заявка.";
      }
      else if (numDocuments==1)
      {
        return "Намерен е <b>1</b> документ, съответстващ на вашата заявка.";
      }
      else
      {
        return "Намерени са <b>$num</b> документи, съответстващи на вашата заявка. "
               "Първо се показват най-добрите съвпадения.";
      }
    }
trSearchResultsTitle()
QCString TranslatorBulgarian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1432 of file translator_bg.h.
    {
      return "Резултати от търсенето";
    }
trSeeAlso()
QCString TranslatorBulgarian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 550 of file translator_bg.h.
    { return "Виж също"; }
trSequenceDocumentation()
QCString TranslatorBulgarian::trSequenceDocumentation () inline override virtual
Implements Translator.
Definition at line 2149 of file translator_bg.h.
    {
        return "Последователности Документация";
    }
trSequences()
QCString TranslatorBulgarian::trSequences () inline override virtual
Implements Translator.
Definition at line 2145 of file translator_bg.h.
    {
        return "Последователности";
    }
trServiceGeneratedFromFiles()
QCString TranslatorBulgarian::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 2001 of file translator_bg.h.
    {
      // single is true implies a single file
      QCString result=(QCString)"Документацията за този сървис "
                                "беше генерирано от ";
      if (single) result+="следният файл:"; else result+="следните файлове:";
      return result;
    }
trServiceReference()
QCString TranslatorBulgarian::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 1987 of file translator_bg.h.
    {
      QCString result=(QCString)sName;
      result+=" Сървис Справка";
      return result;
    }
trServices()
QCString TranslatorBulgarian::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1972 of file translator_bg.h.
    { return "Включени услуги"; }
trSignals()
QCString TranslatorBulgarian::trSignals () inline override virtual
Implements Translator.
Definition at line 644 of file translator_bg.h.
    { return "Сигнали"; }
trSince()
QCString TranslatorBulgarian::trSince () inline override virtual
Implements Translator.
Definition at line 985 of file translator_bg.h.
    {
      return "От";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorBulgarian::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 2010 of file translator_bg.h.
    {
      // single is true implies a single file
      QCString result=(QCString)"Документацията за тази конкретика "
                                "беше генерирано от ";
      if (single) result+="следният файл:"; else result+="следните файлове:";
      return result;
    }
trSingletonReference()
QCString TranslatorBulgarian::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 1994 of file translator_bg.h.
    {
      QCString result=(QCString)sName;
      result+=" Конкретика Справка";
      return result;
    }
trSliceInterfaces()
QCString TranslatorBulgarian::trSliceInterfaces () inline override virtual
Implements Translator.
Definition at line 2161 of file translator_bg.h.
    {
        return "Интерфейси";
    }
trSourceFile()
QCString TranslatorBulgarian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1474 of file translator_bg.h.
    {
      return filename + " Изходен файл";
    }
trStaticPackageAttribs()
QCString TranslatorBulgarian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1403 of file translator_bg.h.
    {
      return "Статични променливи с област на видимост пакет";
    }
trStaticPackageFunctions()
QCString TranslatorBulgarian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1389 of file translator_bg.h.
    {
      return "Статични функции с област на видимост пакет";
    }
trStaticPrivateAttribs()
QCString TranslatorBulgarian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 944 of file translator_bg.h.
    {
      return "Статични частни атрибути";
    }
trStaticPrivateMembers()
QCString TranslatorBulgarian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 658 of file translator_bg.h.
    { return "Статични частни членове функции"; }
trStaticProtectedAttribs()
QCString TranslatorBulgarian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 932 of file translator_bg.h.
    {
      return "Статични защитени атрибути";
    }
trStaticProtectedMembers()
QCString TranslatorBulgarian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 652 of file translator_bg.h.
    { return "Статични защитени членове функции"; }
trStaticPublicAttribs()
QCString TranslatorBulgarian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 920 of file translator_bg.h.
    {
      return "Статични общодостъпни атрибути";
    }
trStaticPublicMembers()
QCString TranslatorBulgarian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 646 of file translator_bg.h.
    { return "Статични общодостъпни членове функции"; }
trStructDocumentation()
QCString TranslatorBulgarian::trStructDocumentation () inline override virtual
Implements Translator.
Definition at line 2205 of file translator_bg.h.
    {
        return "Структури Документация";
    }
trStructIndex()
QCString TranslatorBulgarian::trStructIndex () inline override virtual
Implements Translator.
Definition at line 2193 of file translator_bg.h.
    {
        return "Структури Указател";
    }
trStructList()
QCString TranslatorBulgarian::trStructList () inline override virtual
Implements Translator.
Definition at line 2197 of file translator_bg.h.
    {
        return "Структури Списък";
    }
trStructListDescription()
QCString TranslatorBulgarian::trStructListDescription () inline override virtual
Implements Translator.
Definition at line 2201 of file translator_bg.h.
    {
        return "Структури с кратки описания:";
    }
trStructs()
QCString TranslatorBulgarian::trStructs () inline override virtual
Implements Translator.
Definition at line 2189 of file translator_bg.h.
    {
        return "Структури";
    }
trSubprogram()
QCString TranslatorBulgarian::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1737 of file translator_bg.h.
    {
      QCString result((first_capital ? "Подпрограм" : "подпрограм"));
          if (singular) result+="а:"; else result+="и:";
      return result;
    }
trSubprogramDocumentation()
QCString TranslatorBulgarian::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1609 of file translator_bg.h.
    { return "Функции/Подпрограми Документация"; }
trSubprograms()
QCString TranslatorBulgarian::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1603 of file translator_bg.h.
    { return "Функции/Подпрограми"; }
trTemplateParameters()
QCString TranslatorBulgarian::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1879 of file translator_bg.h.
    { return "Шаблона Параметри"; }
trTest()
QCString TranslatorBulgarian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1077 of file translator_bg.h.
    {
      return "Тест";
    }
trTestList()
QCString TranslatorBulgarian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1082 of file translator_bg.h.
    {
      return "Тестове Списък";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorBulgarian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 147 of file translator_bg.h.
    { return "Това е пълен списък с членове за"; }
trTodo()
QCString TranslatorBulgarian::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 954 of file translator_bg.h.
    {
      return "Елементи на списъка със задачи";
    }
trTodoList()
QCString TranslatorBulgarian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 959 of file translator_bg.h.
    {
      return "Списък със задачи за обсъждане свързани с подобренията";
    }
trType()
QCString TranslatorBulgarian::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1726 of file translator_bg.h.
    {
      QCString result((first_capital ? "Тип" : "тип"));
      if (!singular)  result+="ове";
      return result;
    }
trTypeConstraints()
QCString TranslatorBulgarian::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1745 of file translator_bg.h.
    {
      return "Съвместими типове";
    }
trTypedefDocumentation()
QCString TranslatorBulgarian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 480 of file translator_bg.h.
    { return "Дефинирани типове Документация"; }
trTypedefs()
QCString TranslatorBulgarian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 444 of file translator_bg.h.
    { return "Дефиниции на типове"; }
trTypeDocumentation()
QCString TranslatorBulgarian::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1597 of file translator_bg.h.
    { return "Типове данни Документация"; }
trVariableDocumentation()
QCString TranslatorBulgarian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 498 of file translator_bg.h.
    { return "Променливи Документация"; }
trVariables()
QCString TranslatorBulgarian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 462 of file translator_bg.h.
    { return "Променливи"; }
trVersion()
QCString TranslatorBulgarian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 538 of file translator_bg.h.
    { return "Версия"; }
trVhdlType()
QCString TranslatorBulgarian::trVhdlType (VhdlSpecifier type, bool single) inline override virtual
VHDL type.
Implements Translator.
Definition at line 2048 of file translator_bg.h.
    {
      switch(type)
      {
        case VhdlSpecifier::LIBRARY:
          if (single) return "Библиотека";
          else        return "Библиотеки";
        case VhdlSpecifier::PACKAGE:
          if (single) return "Пакет";
          else        return "Пакети";
        case VhdlSpecifier::SIGNAL:
          if (single) return "Сигнал";
          else        return "Сигнали";
        case VhdlSpecifier::COMPONENT:
          if (single) return "Компонент";
          else        return "Компоненти";
        case VhdlSpecifier::CONSTANT:
          if (single) return "Константа";
          else        return "Константи";
        case VhdlSpecifier::ENTITY:
          if (single) return "Същност";
          else        return "Същности";
        case VhdlSpecifier::TYPE:
          if (single) return "Тип";
          else        return "Типове";
        case VhdlSpecifier::SUBTYPE:
          if (single) return "Подтип";
          else        return "Подтипове";
        case VhdlSpecifier::FUNCTION:
          if (single) return "Функция";
          else        return "Функции";
        case VhdlSpecifier::RECORD:
          if (single) return "Запис";
          else        return "Записи";
        case VhdlSpecifier::PROCEDURE:
          if (single) return "Процедура";
          else        return "Процедури";
        case VhdlSpecifier::ARCHITECTURE:
          if (single) return "Архитектура";
          else        return "Архитектури";
        case VhdlSpecifier::ATTRIBUTE:
          if (single) return "Атрибут";
          else        return "Атрибути";
        case VhdlSpecifier::PROCESS:
          if (single) return "Процес";
          else        return "Процеси";
        case VhdlSpecifier::PORT:
          if (single) return "Порт";
          else        return "Портове";
        case VhdlSpecifier::USE:
          if (single) return "use клауза";
          else        return "Use клаузи";
        case VhdlSpecifier::GENERIC:
          if (single) return "Роден";
          else        return "Родни";
        case VhdlSpecifier::PACKAGE_BODY:
          return "Тяло на пакета";
        case VhdlSpecifier::UNITS:
          return "Единици";
        case VhdlSpecifier::SHAREDVARIABLE:
          if (single) return "Споделена променлива";
          else        return "Споделени променливи";
        case VhdlSpecifier::VFILE:
          if (single) return "Файл";
          else        return "Файлове";
        case VhdlSpecifier::GROUP:
          if (single) return "Група";
          else        return "Групи";
        case VhdlSpecifier::INSTANTIATION:
          if (single) return "Инстанция";
          else        return "Инстанции";
        case VhdlSpecifier::ALIAS:
          if (single) return "Псевдоним";
          else        return "Псевдоними";
        case VhdlSpecifier::CONFIG:
          if (single) return "Конфигурация";
          else        return "Конфигурации";
        case VhdlSpecifier::MISCELLANEOUS:
          return "Други";
        case VhdlSpecifier::UCF_CONST:
          return "Ограничения";
        default:
          return "Клас";
      }
    }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorBulgarian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 534 of file translator_bg.h.
    { return "Предупреждение"; }
trWriteList()
QCString TranslatorBulgarian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 664 of file translator_bg.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=", и ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_bg.h