Doxygen: DocHtmlDescData Class Reference
DocHtmlDescData Class Reference
Node representing a HTML description data.
#include <docnode.h>
Public Member Functions
DocHtmlDescData (DocParser *parser, DocNodeVariant *parent)
const HtmlAttribList & attribs () const
int parse ()
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
DocNode (const DocNode &)=delete
DocNode & operator= (const DocNode &)=delete
DocNode (DocNode &&)=default
DocNode & operator= (DocNode &&)=default
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
HtmlAttribList m_attribs
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a HTML description data.
Definition at line 1141 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlDescData()
DocHtmlDescData::DocHtmlDescData (DocParser * parser, DocNodeVariant * parent) inline
Definition at line 1144 of file docnode.h.
: DocCompoundNode(parser,parent) {}
Member Function Documentation
attribs()
const HtmlAttribList & DocHtmlDescData::attribs () const inline
Definition at line 1145 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by HtmlDocVisitor::operator()().
parse()
int DocHtmlDescData::parse ()
Definition at line 2278 of file docnode.cpp.
{
  AUTO_TRACE();
  m_attribs = parser()->context.token->attribs;
  int retval=0;
  auto ns = AutoNodeStack(parser(),thisVariant());
  bool isFirst=TRUE;
  DocPara *par=0;
  do
  {
    children().append<DocPara>(parser(),thisVariant());
    par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse();
  }
  while (retval==TK_NEWPARA);
  if (par) par->markLast();
  return retval;
}
References DocNodeList::append(), TokenInfo::attribs, AUTO_TRACE, DocCompoundNode::children(), DocParser::context, FALSE, DocNodeList::get_last(), m_attribs, DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), DocNode::parser(), DocNode::thisVariant(), TK_NEWPARA, DocParserContext::token, and TRUE.
Referenced by DocHtmlDescList::parse().
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlDescData::m_attribs private
Definition at line 1149 of file docnode.h.
Referenced by attribs(), and parse().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/docnode.h
/home/runner/work/doxygen/doxygen/src/docnode.cpp