Doxygen: OutputCodeList::OutputCodeElem Struct Reference
OutputCodeList::OutputCodeElem Struct Reference
Public Member Functions
OutputCodeElem (OutputCodeIntfPtr &&p)
OutputCodeElem (const OutputCodeElem &other)
OutputCodeElem & operator= (const OutputCodeElem &other)
Public Attributes
OutputCodeIntfPtr intf
bool enabled = true
Detailed Description
Definition at line 169 of file outputlist.h.
Constructor & Destructor Documentation
OutputCodeElem() [1/2]
OutputCodeList::OutputCodeElem::OutputCodeElem (OutputCodeIntfPtr && p) inline explicit
Definition at line 171 of file outputlist.h.
: intf(std::move(p)) {}
References intf.
Referenced by operator=(), and OutputCodeElem().
OutputCodeElem() [2/2]
OutputCodeList::OutputCodeElem::OutputCodeElem (const OutputCodeElem & other) inline
Definition at line 172 of file outputlist.h.
      {
        intf = other.intf->clone();
        enabled = other.enabled;
      }
References enabled, intf, and OutputCodeElem().
Member Function Documentation
operator=()
OutputCodeElem & OutputCodeList::OutputCodeElem::operator= (const OutputCodeElem & other) inline
Definition at line 177 of file outputlist.h.
      {
        if (&other!=this)
        {
          intf = other.intf->clone();
          enabled = other.enabled;
        }
        return *this;
      }
References enabled, intf, and OutputCodeElem().
Member Data Documentation
enabled
bool OutputCodeList::OutputCodeElem::enabled = true
Definition at line 187 of file outputlist.h.
Referenced by operator=(), and OutputCodeElem().
intf
OutputCodeIntfPtr OutputCodeList::OutputCodeElem::intf
Definition at line 186 of file outputlist.h.
Referenced by operator=(), OutputCodeElem(), and OutputCodeElem().
The documentation for this struct was generated from the following file:
src/outputlist.h