Doxygen: HtmlCodeGenerator Class Reference
HtmlCodeGenerator Class Reference
Generator for HTML code fragments.
#include <src/htmlgen.h>
Classes
struct LineInfo
Public Member Functions
HtmlCodeGenerator (TextStream *t, const QCString &relPath)
HtmlCodeGenerator (TextStream *t)
void setTextStream (TextStream *t)
void setFileName (const QCString fileName)
QCString fileName ()
OutputType type () const override
std::unique_ptr< OutputCodeIntf > clone () override
void codify (const QCString &text) override
void stripCodeComments (bool b) override
void startSpecialComment () override
void endSpecialComment () override
void setStripIndentAmount (size_t amount) override
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip) override
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo) override
void writeLineNumber (const QCString &, const QCString &, const QCString &, int, bool) override
void startCodeLine (int) override
void endCodeLine () override
void startFontClass (const QCString &s) override
void endFontClass () override
void writeCodeAnchor (const QCString &anchor) override
void startCodeFragment (const QCString &style) override
void endCodeFragment (const QCString &) override
void startFold (int, const QCString &, const QCString &) override
void endFold () override
void setRelativePath (const QCString &path)
Public Member Functions inherited from OutputCodeIntf
OutputCodeIntf ()=default
Private Member Functions
void _writeCodeLink (const QCString &className, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void _startOpenLine ()
Private Attributes
TextStream * m_t
size_t m_col = 0
QCString m_relPath
QCString m_fileName
bool m_lineOpen = false
bool m_stripCodeComments = false
bool m_hide = false
LineInfo m_lastLineInfo
size_t m_stripIndentAmount = 0
Detailed Description
Generator for HTML code fragments.
Definition at line 24 of file htmlgen.h.
Constructor & Destructor Documentation
HtmlCodeGenerator() [1/2]
HtmlCodeGenerator::HtmlCodeGenerator (TextStream * t, const QCString & relPath)
Definition at line 714 of file htmlgen.cpp.
  : m_t(t), m_relPath(relPath)
{
  //printf("%p:HtmlCodeGenerator()\n",(void*)this);
}
References m_relPath, and m_t.
HtmlCodeGenerator() [2/2]
HtmlCodeGenerator::HtmlCodeGenerator (TextStream * t)
Definition at line 709 of file htmlgen.cpp.
                                                  : m_t(t)
{
  //printf("%p:HtmlCodeGenerator()\n",(void*)this);
}
References m_t.
Member Function Documentation
_startOpenLine()
void HtmlCodeGenerator::_startOpenLine () private
Definition at line 1060 of file htmlgen.cpp.
{
  *m_t << "<div class=\"line\">";
  bool wasHidden=m_hide;
  m_hide = false;
  m_lineOpen = true;
  writeLineNumber(m_lastLineInfo.ref,
      m_lastLineInfo.fileName,
      m_lastLineInfo.anchor,
      m_lastLineInfo.line+1,
      m_lastLineInfo.writeAnchor);
  m_hide = wasHidden;
}
References m_hide, m_lastLineInfo, m_lineOpen, m_t, and writeLineNumber().
Referenced by endFold().
_writeCodeLink()
void HtmlCodeGenerator::_writeCodeLink (const QCString & className, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) private
Definition at line 875 of file htmlgen.cpp.
{
  m_col+=name.length();
  if (m_hide) return;
  if (!ref.isEmpty())
  {
    *m_t << "<a class=\"" << className << "Ref\" ";
    *m_t << externalLinkTarget();
  }
  else
  {
    *m_t << "<a class=\"" << className << "\" ";
  }
  *m_t << "href=\"";
  QCString fn = f;
  addHtmlExtensionIfMissing(fn);
  *m_t << createHtmlUrl(m_relPath,ref,true,
                        fileName()==fn,fn,anchor);
  *m_t << "\"";
  if (!tooltip.isEmpty()) *m_t << " title=\"" << convertToHtml(tooltip) << "\"";
  *m_t << ">";
  codify(name);
  *m_t << "</a>";
}
References addHtmlExtensionIfMissing(), codify(), convertToHtml(), createHtmlUrl(), externalLinkTarget(), fileName(), QCString::isEmpty(), QCString::length(), m_col, m_hide, m_relPath, and m_t.
Referenced by writeCodeLink(), and writeLineNumber().
clone()
std::unique_ptr< OutputCodeIntf > HtmlCodeGenerator::clone () inline override virtual
Implements OutputCodeIntf.
Definition at line 35 of file htmlgen.h.
{ return std::make_unique<HtmlCodeGenerator>(*this); }
codify()
void HtmlCodeGenerator::codify (const QCString & text) override virtual
Implements OutputCodeIntf.
Definition at line 725 of file htmlgen.cpp.
{
  if (!str.isEmpty())
  {
    int tabSize = Config_getInt(TAB_SIZE);
    const char *p=str.data();
    if (m_hide) // only update column count
    {
      m_col = updateColumnCount(p,m_col);
    }
    else // actually output content and keep track of m_col
    {
      while (*p)
      {
        char c=*p++;
        switch(c)
        {
          case '\t': {
                       int spacesToNextTabStop = tabSize - (m_col%tabSize);
                       while (spacesToNextTabStop--)
                       {
                         if (m_col>=m_stripIndentAmount) *m_t << " ";
                         m_col++;
                       }
                     }
                     break;
          case ' ':  if (m_col>=m_stripIndentAmount) *m_t << " ";
                     m_col++;
                     break;
          case '\n': *m_t << "\n"; m_col=0;
                     break;
          case '\r': break;
          case '<':  *m_t << "&lt;"; m_col++;
                     break;
          case '>':  *m_t << "&gt;"; m_col++;
                     break;
          case '&':  *m_t << "&amp;"; m_col++;
                     break;
          case '\'': *m_t << "&#39;"; m_col++; // &apos; is not valid XHTML
                     break;
          case '"':  *m_t << "&quot;"; m_col++;
                     break;
          case '\\':
                     if (*p=='<')
                     { *m_t << "&lt;"; p++; }
                     else if (*p=='>')
                     { *m_t << "&gt;"; p++; }
                     else if (*p=='(')
                     { *m_t << "\\&zwj;("; m_col++;p++; }
                     else if (*p==')')
                     { *m_t << "\\&zwj;)"; m_col++;p++; }
                     else
                       *m_t << "\\";
                     m_col++;
                     break;
          default:
                     {
                       uint8_t uc = static_cast<uint8_t>(c);
                       if (uc<32)
                       {
                         *m_t << "&#x24" << hex[uc>>4] << hex[uc&0xF] << ";";
                         m_col++;
                       }
                       else if (uc<0x80) // printable ASCII char
                       {
                         *m_t << c;
                         m_col++;
                       }
                       else // multibyte UTF-8 char
                       {
                         p=writeUTF8Char(*m_t,p-1);
                         m_col++;
                       }
                     }
                     break;
        }
      }
    }
  }
}
References Config_getInt, QCString::data(), hex, QCString::isEmpty(), m_col, m_hide, m_stripIndentAmount, m_t, updateColumnCount(), and writeUTF8Char().
Referenced by _writeCodeLink(), writeLineNumber(), and writeTooltip().
endCodeFragment()
void HtmlCodeGenerator::endCodeFragment (const QCString &) override virtual
Implements OutputCodeIntf.
Definition at line 1032 of file htmlgen.cpp.
{
  //endCodeLine checks is there is still an open code line, if so closes it.
  endCodeLine();
  *m_t << "</div><!-- fragment -->";
}
References endCodeLine(), and m_t.
endCodeLine()
void HtmlCodeGenerator::endCodeLine () override virtual
Implements OutputCodeIntf.
Definition at line 994 of file htmlgen.cpp.
{
  if (m_hide) return;
  if (m_col == 0)
  {
    *m_t << " ";
    m_col++;
  }
  if (m_lineOpen)
  {
    *m_t << "</div>\n";
    m_lineOpen = FALSE;
  }
}
References FALSE, m_col, m_hide, m_lineOpen, and m_t.
Referenced by endCodeFragment().
endFold()
void HtmlCodeGenerator::endFold () override virtual
Implements OutputCodeIntf.
Definition at line 1074 of file htmlgen.cpp.
{
  if (m_lineOpen) // if we have a hidden comment in a code fold, we need to end the line
  {
    *m_t << "</div>\n";
  }
  *m_t << "</div>\n";
  if (m_lineOpen)
  {
    _startOpenLine();
  }
}
References _startOpenLine(), m_lineOpen, and m_t.
endFontClass()
void HtmlCodeGenerator::endFontClass () override virtual
Implements OutputCodeIntf.
Definition at line 1015 of file htmlgen.cpp.
{
  if (m_hide) return;
  *m_t << "</span>";
}
References m_hide, and m_t.
endSpecialComment()
void HtmlCodeGenerator::endSpecialComment () override virtual
Implements OutputCodeIntf.
Definition at line 817 of file htmlgen.cpp.
{
  //*m_t << "[END]";
  m_hide = false;
}
References m_hide.
fileName()
QCString HtmlCodeGenerator::fileName () inline
Definition at line 32 of file htmlgen.h.
{ return m_fileName; }
References m_fileName.
Referenced by _writeCodeLink(), setFileName(), and writeTooltip().
setFileName()
void HtmlCodeGenerator::setFileName (const QCString fileName) inline
Definition at line 31 of file htmlgen.h.
{ m_fileName = fileName; }
References fileName(), and m_fileName.
setRelativePath()
void HtmlCodeGenerator::setRelativePath (const QCString & path)
Definition at line 720 of file htmlgen.cpp.
{
  m_relPath = path;
}
References m_relPath.
setStripIndentAmount()
void HtmlCodeGenerator::setStripIndentAmount (size_t amount) override virtual
Implements OutputCodeIntf.
Definition at line 823 of file htmlgen.cpp.
{
  m_stripIndentAmount = amount;
}
References m_stripIndentAmount.
setTextStream()
void HtmlCodeGenerator::setTextStream (TextStream * t) inline
Definition at line 30 of file htmlgen.h.
{ m_t = t; }
References m_t.
startCodeFragment()
void HtmlCodeGenerator::startCodeFragment (const QCString & style) override virtual
Implements OutputCodeIntf.
Definition at line 1027 of file htmlgen.cpp.
{
  *m_t << "<div class=\"fragment\">";
}
References m_t.
startCodeLine()
void HtmlCodeGenerator::startCodeLine (int) override virtual
Implements OutputCodeIntf.
Definition at line 983 of file htmlgen.cpp.
{
  m_col=0;
  if (m_hide) return;
  if (!m_lineOpen)
  {
    *m_t << "<div class=\"line\">";
    m_lineOpen = TRUE;
  }
}
References m_col, m_hide, m_lineOpen, m_t, and TRUE.
startFold()
void HtmlCodeGenerator::startFold (int lineNr, const QCString & startMarker, const QCString & endMarker) override virtual
Implements OutputCodeIntf.
Definition at line 1040 of file htmlgen.cpp.
{
  if (m_lineOpen) // if we have a hidden comment in a code fold, we need to end the line
  {
    *m_t << "</div>\n";
  }
  const int maxLineNrStr = 10;
  char lineNumber[maxLineNrStr];
  qsnprintf(lineNumber,maxLineNrStr,"%05d",lineNr);
  *m_t << "<div class=\"foldopen\" id=\"foldopen" << lineNumber <<
          "\" data-start=\"" << startMarker <<
          "\" data-end=\"" << endMarker <<
          "\">\n";
  if (m_lineOpen) // if we have a hidden comment in a code fold, we need to restart the line
  {
    *m_t << "<div class=\"line\">";
  }
  m_hide=false;
}
References m_hide, m_lineOpen, m_t, and qsnprintf.
startFontClass()
void HtmlCodeGenerator::startFontClass (const QCString & s) override virtual
Implements OutputCodeIntf.
Definition at line 1009 of file htmlgen.cpp.
{
  if (m_hide) return;
  *m_t << "<span class=\"" << s << "\">";
}
References m_hide, and m_t.
startSpecialComment()
void HtmlCodeGenerator::startSpecialComment () override virtual
Implements OutputCodeIntf.
Definition at line 811 of file htmlgen.cpp.
{
  m_hide = m_stripCodeComments;
  //*m_t << "[START]";
}
References m_hide, and m_stripCodeComments.
stripCodeComments()
void HtmlCodeGenerator::stripCodeComments (bool b) override virtual
Implements OutputCodeIntf.
Definition at line 806 of file htmlgen.cpp.
{
  m_stripCodeComments = b;
}
References m_stripCodeComments.
type()
OutputType HtmlCodeGenerator::type () const inline override virtual
Implements OutputCodeIntf.
Definition at line 34 of file htmlgen.h.
{ return OutputType::Html; }
References Html.
Referenced by writeCodeLink().
writeCodeAnchor()
void HtmlCodeGenerator::writeCodeAnchor (const QCString & anchor) override virtual
Implements OutputCodeIntf.
Definition at line 1021 of file htmlgen.cpp.
{
  if (m_hide) return;
  *m_t << "<a id=\"" << anchor << "\" name=\"" << anchor << "\"></a>";
}
References m_hide, and m_t.
writeCodeLink()
void HtmlCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) override virtual
Implements OutputCodeIntf.
Definition at line 859 of file htmlgen.cpp.
{
  if (m_hide) return;
  const char *hl = codeSymbolType2Str(type);
  QCString hlClass = "code";
  if (hl)
  {
    hlClass+=" hl_";
    hlClass+=hl;
  }
  _writeCodeLink(hlClass,ref,f,anchor,name,tooltip);
}
References _writeCodeLink(), codeSymbolType2Str(), m_hide, and type().
writeLineNumber()
void HtmlCodeGenerator::writeLineNumber (const QCString & ref, const QCString & filename, const QCString & anchor, int l, bool writeLineAnchor) override virtual
Implements OutputCodeIntf.
Definition at line 828 of file htmlgen.cpp.
{
  m_lastLineInfo = LineInfo(ref,filename,anchor,l,writeLineAnchor);
  if (m_hide) return;
  const int maxLineNrStr = 10;
  char lineNumber[maxLineNrStr];
  char lineAnchor[maxLineNrStr];
  qsnprintf(lineNumber,maxLineNrStr,"%5d",l);
  qsnprintf(lineAnchor,maxLineNrStr,"l%05d",l);
  if (!m_lineOpen)
  {
    *m_t << "<div class=\"line\">";
    m_lineOpen = TRUE;
  }
  if (writeLineAnchor) *m_t << "<a id=\"" << lineAnchor << "\" name=\"" << lineAnchor << "\"></a>";
  *m_t << "<span class=\"lineno\">";
  if (!filename.isEmpty())
  {
    _writeCodeLink("line",ref,filename,anchor,lineNumber,QCString());
  }
  else
  {
    codify(lineNumber);
  }
  *m_t << "</span>";
  m_col=0;
}
References _writeCodeLink(), codify(), QCString::isEmpty(), m_col, m_hide, m_lastLineInfo, m_lineOpen, m_t, qsnprintf, and TRUE.
Referenced by _startOpenLine().
writeTooltip()
void HtmlCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) override virtual
Implements OutputCodeIntf.
Definition at line 903 of file htmlgen.cpp.
{
  if (m_hide) return;
  *m_t << "<div class=\"ttc\" id=\"" << id << "\">";
  *m_t << "<div class=\"ttname\">";
  if (!docInfo.url.isEmpty())
  {
    *m_t << "<a href=\"";
    QCString fn = docInfo.url;
    addHtmlExtensionIfMissing(fn);
    *m_t << createHtmlUrl(m_relPath,docInfo.ref,true,
                          fileName()==fn,fn,docInfo.anchor);
    *m_t << "\">";
  }
  codify(docInfo.name);
  if (!docInfo.url.isEmpty())
  {
    *m_t << "</a>";
  }
  *m_t << "</div>";
  if (!decl.isEmpty())
  {
    *m_t << "<div class=\"ttdeci\">";
    codify(decl);
    *m_t << "</div>";
  }
  if (!desc.isEmpty())
  {
    *m_t << "<div class=\"ttdoc\">";
    codify(desc);
    *m_t << "</div>";
  }
  if (!defInfo.file.isEmpty())
  {
    *m_t << "<div class=\"ttdef\"><b>" << theTranslator->trDefinition() << "</b> ";
    if (!defInfo.url.isEmpty())
    {
      *m_t << "<a href=\"";
      QCString fn = defInfo.url;
      addHtmlExtensionIfMissing(fn);
      *m_t << createHtmlUrl(m_relPath,defInfo.ref,true,
                            fileName()==fn,fn,defInfo.anchor);
      *m_t << "\">";
    }
    *m_t << defInfo.file << ":" << defInfo.line;
    if (!defInfo.url.isEmpty())
    {
      *m_t << "</a>";
    }
    *m_t << "</div>";
  }
  if (!declInfo.file.isEmpty())
  {
    *m_t << "<div class=\"ttdecl\"><b>" << theTranslator->trDeclaration() << "</b> ";
    if (!declInfo.url.isEmpty())
    {
      *m_t << "<a href=\"";
      QCString fn = declInfo.url;
      addHtmlExtensionIfMissing(fn);
      *m_t << createHtmlUrl(m_relPath,declInfo.ref,true,
                            fileName()==fn,fn,declInfo.anchor);
      *m_t << "\">";
    }
    *m_t << declInfo.file << ":" << declInfo.line;
    if (!declInfo.url.isEmpty())
    {
      *m_t << "</a>";
    }
    *m_t << "</div>";
  }
  *m_t << "</div>\n";
}
References addHtmlExtensionIfMissing(), DocLinkInfo::anchor, SourceLinkInfo::anchor, codify(), createHtmlUrl(), SourceLinkInfo::file, fileName(), QCString::isEmpty(), SourceLinkInfo::line, m_hide, m_relPath, m_t, DocLinkInfo::name, DocLinkInfo::ref, SourceLinkInfo::ref, theTranslator, Translator::trDeclaration(), Translator::trDefinition(), DocLinkInfo::url, and SourceLinkInfo::url.
Member Data Documentation
m_col
size_t HtmlCodeGenerator::m_col = 0 private
Definition at line 72 of file htmlgen.h.
Referenced by _writeCodeLink(), codify(), endCodeLine(), startCodeLine(), and writeLineNumber().
m_fileName
QCString HtmlCodeGenerator::m_fileName private
Definition at line 74 of file htmlgen.h.
Referenced by fileName(), and setFileName().
m_hide
bool HtmlCodeGenerator::m_hide = false private
Definition at line 77 of file htmlgen.h.
Referenced by _startOpenLine(), _writeCodeLink(), codify(), endCodeLine(), endFontClass(), endSpecialComment(), startCodeLine(), startFold(), startFontClass(), startSpecialComment(), writeCodeAnchor(), writeCodeLink(), writeLineNumber(), and writeTooltip().
m_lastLineInfo
LineInfo HtmlCodeGenerator::m_lastLineInfo private
Definition at line 89 of file htmlgen.h.
Referenced by _startOpenLine(), and writeLineNumber().
m_lineOpen
bool HtmlCodeGenerator::m_lineOpen = false private
Definition at line 75 of file htmlgen.h.
Referenced by _startOpenLine(), endCodeLine(), endFold(), startCodeLine(), startFold(), and writeLineNumber().
m_relPath
QCString HtmlCodeGenerator::m_relPath private
Definition at line 73 of file htmlgen.h.
Referenced by _writeCodeLink(), HtmlCodeGenerator(), setRelativePath(), and writeTooltip().
m_stripCodeComments
bool HtmlCodeGenerator::m_stripCodeComments = false private
Definition at line 76 of file htmlgen.h.
Referenced by startSpecialComment(), and stripCodeComments().
m_stripIndentAmount
size_t HtmlCodeGenerator::m_stripIndentAmount = 0 private
Definition at line 90 of file htmlgen.h.
Referenced by codify(), and setStripIndentAmount().
m_t
TextStream* HtmlCodeGenerator::m_t private
Definition at line 71 of file htmlgen.h.
Referenced by _startOpenLine(), _writeCodeLink(), codify(), endCodeFragment(), endCodeLine(), endFold(), endFontClass(), HtmlCodeGenerator(), HtmlCodeGenerator(), setTextStream(), startCodeFragment(), startCodeLine(), startFold(), startFontClass(), writeCodeAnchor(), writeLineNumber(), and writeTooltip().
The documentation for this class was generated from the following files:
src/htmlgen.h
src/htmlgen.cpp