Doxygen: LayoutDocEntrySection Struct Reference
LayoutDocEntrySection Struct Reference
#include <layout.h>
Public Member Functions
LayoutDocEntrySection (Kind k, const QCString &tl, bool v)
QCString title (SrcLangExt lang) const
Public Member Functions inherited from LayoutDocEntrySimple
LayoutDocEntrySimple (Kind k, bool v)
Kind kind () const
bool visible () const
Public Member Functions inherited from LayoutDocEntry
virtual ~LayoutDocEntry ()=default
Private Attributes
QCString m_title
Additional Inherited Members
Public Types inherited from LayoutDocEntry
enum Kind {
MemberGroups , MemberDeclStart , MemberDeclEnd , MemberDecl ,
MemberDefStart , MemberDefEnd , MemberDef , BriefDesc ,
DetailedDesc , AuthorSection , ClassIncludes , ClassInlineClasses ,
ClassInheritanceGraph , ClassNestedClasses , ClassCollaborationGraph , ClassAllMembersLink ,
ClassUsedFiles , ConceptDefinition , NamespaceNestedNamespaces , NamespaceNestedConstantGroups ,
NamespaceClasses , NamespaceConcepts , NamespaceInterfaces , NamespaceStructs ,
NamespaceExceptions , NamespaceInlineClasses , FileClasses , FileConcepts ,
FileInterfaces , FileStructs , FileExceptions , FileConstantGroups ,
FileNamespaces , FileIncludes , FileIncludeGraph , FileIncludedByGraph ,
FileSourceLink , FileInlineClasses , GroupClasses , GroupConcepts ,
GroupInlineClasses , GroupNamespaces , GroupDirs , GroupNestedGroups ,
GroupFiles , GroupGraph , GroupPageDocs , DirSubDirs ,
DirFiles , DirGraph
}
Detailed Description
Definition at line 86 of file layout.h.
Constructor & Destructor Documentation
LayoutDocEntrySection()
LayoutDocEntrySection::LayoutDocEntrySection (Kind k, const QCString & tl, bool v) inline
Definition at line 88 of file layout.h.
                                                          :
    LayoutDocEntrySimple(k,v), m_title(tl) {}
Member Function Documentation
title()
QCString LayoutDocEntrySection::title (SrcLangExt lang) const
Definition at line 1446 of file layout.cpp.
{
  return extractLanguageSpecificTitle(m_title,lang);
}
References extractLanguageSpecificTitle(), and m_title.
Referenced by ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentationContents(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), and NamespaceDefImpl::writeSummaryLinks().
Member Data Documentation
m_title
QCString LayoutDocEntrySection::m_title private
Definition at line 92 of file layout.h.
Referenced by title().
The documentation for this struct was generated from the following files:
/home/runner/work/doxygen/doxygen/src/layout.h
/home/runner/work/doxygen/doxygen/src/layout.cpp