Doxygen: ClangParser Class Reference
ClangParser Class Reference
Wrapper for to let libclang assisted parsing.
#include <src/clangparser.h>
Classes
class Private
Public Member Functions
std::unique_ptr< ClangTUParser > createTUParser (const FileDef *fd) const
Static Public Member Functions
static ClangParser * instance ()
Returns the one and only instance of the class.
Private Member Functions
const clang::tooling::CompilationDatabase * database () const
ClangParser ()
virtual ~ClangParser ()
Private Attributes
std::unique_ptr< Private > p
Static Private Attributes
static ClangParser * s_instance = nullptr
Friends
class ClangTUParser
Detailed Description
Wrapper for to let libclang assisted parsing.
Definition at line 79 of file clangparser.h.
Constructor & Destructor Documentation
ClangParser()
ClangParser::ClangParser () private
Definition at line 985 of file clangparser.cpp.
                         : p(std::make_unique<Private>())
{
}
References p.
Referenced by ClangTUParser, and instance().
~ClangParser()
ClangParser::~ClangParser () private virtual
Definition at line 989 of file clangparser.cpp.
{
}
Member Function Documentation
createTUParser()
std::unique_ptr< ClangTUParser > ClangParser::createTUParser (const FileDef * fd) const
Definition at line 993 of file clangparser.cpp.
{
  return nullptr;
}
Referenced by generateFileSources(), parseFilesMultiThreading(), and parseFilesSingleThreading().
database()
const clang::tooling::CompilationDatabase * ClangParser::database () const private
instance()
ClangParser * ClangParser::instance () static
Returns the one and only instance of the class.
Definition at line 33 of file clangparser.cpp.
{
  std::lock_guard<std::mutex> lock(g_clangMutex);
  if (s_instance==nullptr) s_instance = new ClangParser;
  return s_instance;
}
References ClangParser(), g_clangMutex, and s_instance.
Referenced by generateFileSources(), parseFilesMultiThreading(), and parseFilesSingleThreading().
Friends And Related Symbol Documentation
ClangTUParser
friend class ClangTUParser friend
Definition at line 81 of file clangparser.h.
References ClangParser(), and ClangTUParser.
Referenced by ClangTUParser.
Member Data Documentation
p
std::unique_ptr<Private> ClangParser::p private
Definition at line 90 of file clangparser.h.
Referenced by ClangParser().
s_instance
ClangParser * ClangParser::s_instance = nullptr static private
Definition at line 94 of file clangparser.h.
Referenced by instance().
The documentation for this class was generated from the following files:
src/clangparser.h
src/clangparser.cpp