Doxygen: TranslatorPortuguese Class Reference
TranslatorPortuguese Class Reference
#include <src/translator_pt.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description.
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool single) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
QCString trDesignUnitDocumentation () override
VHDL design unit documentation.
QCString trConcept (bool first_capital, bool singular) override
C++20 concept.
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
QCString trPackageList () override
QCString trFlowchart () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
QCString trCopyToClipboard () override
QCString trImportant () override
Public Member Functions inherited from Translator
virtual QCString updateNeededMessage ()
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Detailed Description
Definition at line 84 of file translator_pt.h.
Member Function Documentation
getLanguageString()
QCString TranslatorPortuguese::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 123 of file translator_pt.h.
    {
      return "0x816 Portuguese(Portugal)";
    }
idLanguage()
QCString TranslatorPortuguese::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 96 of file translator_pt.h.
    { return "portuguese"; }
latexLanguageSupportCommand()
QCString TranslatorPortuguese::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 113 of file translator_pt.h.
    {
      return
        "\\usepackage[portuges]{babel}\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorPortuguese::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1929 of file translator_pt.h.
    { return "Outros membros herdados"; }
trAll()
QCString TranslatorPortuguese::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1427 of file translator_pt.h.
    {
      return "Tudo";
    }
trAndMore()
QCString TranslatorPortuguese::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1901 of file translator_pt.h.
    { return "e "+number+" mais..."; }
trAttention()
QCString TranslatorPortuguese::trAttention () inline override virtual
Implements Translator.
Definition at line 1014 of file translator_pt.h.
    {
      return "Ateno";
    }
trAuthor()
QCString TranslatorPortuguese::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1300 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "autor", "es");
    }
References Translator::createNoun().
trBug()
QCString TranslatorPortuguese::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1172 of file translator_pt.h.
    {
      return "Bug";
    }
trBugList()
QCString TranslatorPortuguese::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1177 of file translator_pt.h.
    {
      return "Lista de Bugs";
    }
trCallerGraph()
QCString TranslatorPortuguese::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1549 of file translator_pt.h.
    {
      return "Este  o diagrama das funes que utilizam esta funo:";
    }
trCallGraph()
QCString TranslatorPortuguese::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1432 of file translator_pt.h.
    {
      return "Grafo de chamadas desta funo:";
    }
trCiteReferences()
QCString TranslatorPortuguese::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1873 of file translator_pt.h.
    { return "Referncias Bibliogrficas"; }
trClass()
QCString TranslatorPortuguese::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1235 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "classe", "s");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trClassDiagram()
QCString TranslatorPortuguese::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 563 of file translator_pt.h.
    {
      return "Diagrama de heranas da classe "+clName;
    }
trClassDocumentation()
QCString TranslatorPortuguese::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 444 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentao da estruturas de dados";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentao da classe";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorPortuguese::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1135 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de dados";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorPortuguese::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 231 of file translator_pt.h.
    { return "Hierarquia de classes"; }
trClassHierarchyDescription()
QCString TranslatorPortuguese::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 290 of file translator_pt.h.
    { return "Esta lista de heranas est organizada, dentro do possvel, por ordem alfabtica:"; }
trClassMethods()
QCString TranslatorPortuguese::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1967 of file translator_pt.h.
    {
      return "Mtodos de classe";
    }
trCode()
QCString TranslatorPortuguese::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 914 of file translator_pt.h.
    {
      return "cdigo";
    }
trCollaborationDiagram()
QCString TranslatorPortuguese::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 869 of file translator_pt.h.
    {
      return "Diagrama de colaborao para "+clName+":";
    }
trCompoundIndex()
QCString TranslatorPortuguese::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 417 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndice das estruturas de dados";
      }
      else
      {
        return "ndice dos componentes";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorPortuguese::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1601 of file translator_pt.h.
    { return "ndice de Tipos de Dados"; }
trCompoundList()
QCString TranslatorPortuguese::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 235 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de dados";
      }
      else
      {
        return "Lista de componentes";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorPortuguese::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 303 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lista das estruturas de dados com uma breve descrio:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Lista de classes com uma breve descrio:";
      }
      else
      {
        return "Lista de classes, estruturas, unies e interfaces com uma breve descrio:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorPortuguese::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1578 of file translator_pt.h.
    { return "Aqui esto os tipos de dados com descries resumidas:"; }
trCompoundListFortran()
QCString TranslatorPortuguese::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1570 of file translator_pt.h.
    { return "Lista de Tipos de Dados"; }
trCompoundMembers()
QCString TranslatorPortuguese::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 252 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de dados";
      }
      else
      {
        return "Componentes membro";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorPortuguese::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 320 of file translator_pt.h.
    {
      QCString result="Lista de todas as";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" estruturas e campos de unies";
      }
      else
      {
        result+=" classes membro";
      }
      if (!extractAll)
      {
        result+=" documentadas";
      }
      result+=" com referncia para ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a respectiva documentao:";
        }
        else
        {
          result+="a documentao de cada membro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="as estruturas/unies a que pertencem:";
        }
        else
        {
          result+="as classes a que pertencem:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorPortuguese::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1582 of file translator_pt.h.
    {
      QCString result="Esta  a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos tipos de dados com links para ";
      if (extractAll)
      {
        result+="a documentao dos tipos de dados para cada membro:";
      }
      else
      {
        result+="os tipos de dados a que pertencem:";
      }
      return result;
    }
trCompoundMembersDescriptionTotal()
QCString TranslatorPortuguese::trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2487 of file translator_pt.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool masculine = PortugueseTranslatorUtils::isClassMemberHighlightMasculine(hl);
      QCString result="Esta  a list de ";
      result+= (masculine?"todos os ":"todas as ");
      switch (hl)
      {
        case ClassMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="estruturas e unies";
          }
          else
          {
            result+="membros de classe";
          }
          break;
        case ClassMemberHighlight::Functions:
          result+="funes";
          break;
        case ClassMemberHighlight::Variables:
          result+="variveis";
          break;
        case ClassMemberHighlight::Typedefs:
          result+="definies de tipo";
          break;
        case ClassMemberHighlight::Enums:
          result+="enumeraes";
          break;
        case ClassMemberHighlight::EnumValues:
          result+="valores enumerados";
          break;
        case ClassMemberHighlight::Properties:
          result+="propriedades";
          break;
        case ClassMemberHighlight::Events:
          result+="eventos";
          break;
        case ClassMemberHighlight::Related:
          result+="smbolos relacionados";
          break;
        case ClassMemberHighlight::Total: // for completeness
          break;
      }
      if (!extractAll)
      {
        result+= masculine?" documentados":" documentadas";
      }
      result+=" com links para ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a documentao da estrutura/unio para cada campo:";
        }
        else
        {
          result+="a documentao da classe para cada membro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a estrutura/unio a que petencem:";
        }
        else
        {
          result+="a classe a que pertencem:";
        }
      }
      return result;
    }
References ClassMemberHighlight::All, Config_getBool, ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, PortugueseTranslatorUtils::isClassMemberHighlightMasculine(), ClassMemberHighlight::Properties, ClassMemberHighlight::Related, ClassMemberHighlight::Total, ClassMemberHighlight::Typedefs, and ClassMemberHighlight::Variables.
trCompoundMembersFortran()
QCString TranslatorPortuguese::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1574 of file translator_pt.h.
    { return "Campos de Dados"; }
trCompoundReference()
QCString TranslatorPortuguese::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 638 of file translator_pt.h.
    {
      QCString result="Referncia ";
      switch(compType)
      {
        case ClassDef::Class:      result+=" classe "; break;
        case ClassDef::Struct:     result+=" estrutura "; break;
        case ClassDef::Union:      result+=" unio "; break;
        case ClassDef::Interface:  result+="ao interface "; break;
        case ClassDef::Protocol:   result+="ao protocolo "; break;
        case ClassDef::Category:   result+=" categoria "; break;
        case ClassDef::Exception:  result+=" excepo "; break;
        default: break;
      }
      if (isTemplate) result+="Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorPortuguese::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1642 of file translator_pt.h.
    {
      QCString result = "Referncia ";
      if (isTemplate) result+="da Template ";
      switch(compType)
      {
        case ClassDef::Class:      result+="do Modulo "; break;
        case ClassDef::Struct:     result+="do Tipo "; break;
        case ClassDef::Union:      result+="da Unio "; break;
        case ClassDef::Interface:  result+="da Interface "; break;
        case ClassDef::Protocol:   result+="do Protocolo "; break;
        case ClassDef::Category:   result+="da Categoria "; break;
        case ClassDef::Exception:  result+="da Exceo "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice()
QCString TranslatorPortuguese::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) inline override virtual
Implements Translator.
Definition at line 2270 of file translator_pt.h.
    {
      QCString result="Referncia ";
      switch(compType)
      {
        case ClassDef::Class:      result+="da Classe "; break;
        case ClassDef::Struct:     result+="da Estrutura "; break;
        case ClassDef::Union:      result+="da Unio "; break;
        case ClassDef::Interface:  result+="da Interface "; break;
        case ClassDef::Protocol:   result+="do Protocolo "; break;
        case ClassDef::Category:   result+="da Categoria "; break;
        case ClassDef::Exception:  result+="da Exceo "; break;
        default: break;
      }
      if (isLocal) result+="Local ";
      result+= clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorPortuguese::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 539 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de Dados";
      }
      else
      {
        return "Componentes";
      }
    }
References Config_getBool.
trCompoundType()
QCString TranslatorPortuguese::trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) inline override virtual
the compound type as used for the xrefitems
Implements Translator.
Definition at line 2408 of file translator_pt.h.
    {
      QCString result;
      switch(compType)
      {
        case ClassDef::Class:
          if (lang == SrcLangExt::Fortran) trType(true,true);
          else result=trClass(true,true);
          break;
        case ClassDef::Struct:     result="Estrutura"; break;
        case ClassDef::Union:      result="Unio"; break;
        case ClassDef::Interface:  result="Interface"; break;
        case ClassDef::Protocol:   result="Protocolo"; break;
        case ClassDef::Category:   result="Categoria"; break;
        case ClassDef::Exception:  result="Exceo"; break;
        case ClassDef::Service:    result="Servio"; break;
        case ClassDef::Singleton:  result="Singleton"; break;
        default: break;
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, Fortran, ClassDef::Interface, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, ClassDef::Struct, trClass(), trType(), and ClassDef::Union.
trConcept()
QCString TranslatorPortuguese::trConcept (bool first_capital, bool singular) inline override virtual
C++20 concept.
Implements Translator.
Definition at line 2320 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "conceito", "s");
    }
References Translator::createNoun().
trConceptDefinition()
QCString TranslatorPortuguese::trConceptDefinition () inline override virtual
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2354 of file translator_pt.h.
    {
        return "Definio de conceito";
    }
trConceptDocumentation()
QCString TranslatorPortuguese::trConceptDocumentation () inline override virtual
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2341 of file translator_pt.h.
    { return "Documentao do Conceito"; }
trConceptIndex()
QCString TranslatorPortuguese::trConceptIndex () inline override virtual
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2337 of file translator_pt.h.
    { return "ndice de Conceitos"; }
trConceptList()
QCString TranslatorPortuguese::trConceptList () inline override virtual
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2333 of file translator_pt.h.
    { return "Lista de Conceitos"; }
trConceptListDescription()
QCString TranslatorPortuguese::trConceptListDescription (bool extractAll) inline override virtual
used as an introduction to the concept list
Implements Translator.
Definition at line 2345 of file translator_pt.h.
    {
        QCString result="Esta  a lista de todos os conceitos ";
        if (!extractAll) result+="documentados ";
        result+="com suas respectivas descries:";
        return result;
    }
trConceptReference()
QCString TranslatorPortuguese::trConceptReference (const QCString & conceptName) inline override virtual
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2325 of file translator_pt.h.
    {
        QCString result= "Referncia do Conceito ";
        result+=conceptName;
        return result;
    }
trConstantDocumentation()
QCString TranslatorPortuguese::trConstantDocumentation () inline override virtual
Implements Translator.
Definition at line 2178 of file translator_pt.h.
    {
        return "Constantes";
    }
trConstantGroupReference()
QCString TranslatorPortuguese::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2004 of file translator_pt.h.
    {
      QCString result = "Referncia do grupo de constantes ";
      result += namespaceName;
      return result;
    }
trConstantGroups()
QCString TranslatorPortuguese::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2000 of file translator_pt.h.
    { return "Grupos de Constantes"; }
trConstants()
QCString TranslatorPortuguese::trConstants () inline override virtual
Implements Translator.
Definition at line 2174 of file translator_pt.h.
    {
        return "Constantes";
    }
trConstructorDocumentation()
QCString TranslatorPortuguese::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 879 of file translator_pt.h.
    {
      return "Documentao dos Construtores & Destrutor";
    }
trCopyright()
QCString TranslatorPortuguese::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1877 of file translator_pt.h.
    {
      // Note: I will left it as is because "Direitos de autor" may not fit
      // in the text.
      return "Copyright";
    }
trCopyToClipboard()
QCString TranslatorPortuguese::trCopyToClipboard () inline override virtual
Implements Translator.
Definition at line 2688 of file translator_pt.h.
    {
      return "Copiado para a rea de transferncia";
    }
trCustomReference()
QCString TranslatorPortuguese::trCustomReference (const QCString & name) inline override virtual
Implements Translator.
Definition at line 2170 of file translator_pt.h.
    { return "Referncia de " + QCString(name); }
trDataMemberDocumentation()
QCString TranslatorPortuguese::trDataMemberDocumentation () inline override virtual
Implements Translator.
Definition at line 2300 of file translator_pt.h.
    {
        return "Dados Membros";
    }
trDataMembers()
QCString TranslatorPortuguese::trDataMembers () inline override virtual
Implements Translator.
Definition at line 2296 of file translator_pt.h.
    {
        return "Dados Membros";
    }
trDataTypes()
QCString TranslatorPortuguese::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1625 of file translator_pt.h.
    { return "Tipos de Dados"; }
trDate()
QCString TranslatorPortuguese::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 577 of file translator_pt.h.
    { return "Data"; }
trDateTime()
QCString TranslatorPortuguese::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1826 of file translator_pt.h.
    {
      static const char *days[]   = { "Segunda","Tera","Quarta","Quinta","Sexta","Sbado","Domingo" };
      static const char *months[] = { "Janeiro","Fevereiro","Maro","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s, %d de %s de %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorPortuguese::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1846 of file translator_pt.h.
    {
      static const char *days_short[]   = { "seg", "ter", "qua", "qui", "sex", "sb", "dom" };
      static const char *days_full[]    = { "segunda-feira", "tera-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sbado", "domingo" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorPortuguese::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1862 of file translator_pt.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period?1:0];
    }
trDeclaration()
QCString TranslatorPortuguese::trDeclaration () inline override virtual
Implements Translator.
Definition at line 2617 of file translator_pt.h.
{ return "Declarao";}
trDefinedAtLineInSourceFile()
QCString TranslatorPortuguese::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 846 of file translator_pt.h.
    {
      return "Definido na linha @0 do ficheiro @1.";
    }
trDefinedIn()
QCString TranslatorPortuguese::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 219 of file translator_pt.h.
    { return "definido em"; }
trDefinedInSourceFile()
QCString TranslatorPortuguese::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 850 of file translator_pt.h.
    {
      return "Definido no ficheiro @0.";
    }
trDefineDocumentation()
QCString TranslatorPortuguese::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 509 of file translator_pt.h.
    { return "Documentao das macros"; }
trDefines()
QCString TranslatorPortuguese::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 473 of file translator_pt.h.
    { return "Macros"; }
trDefineValue()
QCString TranslatorPortuguese::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1162 of file translator_pt.h.
    {
      return "Valor:";
    }
trDefinition()
QCString TranslatorPortuguese::trDefinition () inline override virtual
Implements Translator.
Definition at line 2616 of file translator_pt.h.
{ return "Definio";}
trDeprecated()
QCString TranslatorPortuguese::trDeprecated () inline override virtual
Implements Translator.
Definition at line 859 of file translator_pt.h.
    {
      return "Desaprovado";
    }
trDeprecatedList()
QCString TranslatorPortuguese::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1355 of file translator_pt.h.
    {
      return "Lista de Deprecados";
    }
trDesignUnitDocumentation()
QCString TranslatorPortuguese::trDesignUnitDocumentation () inline override virtual
VHDL design unit documentation.
Implements Translator.
Definition at line 2310 of file translator_pt.h.
    {
        return "Documentao da Unidade de Projeto";
    }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorPortuguese::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Implements Translator.
Definition at line 2061 of file translator_pt.h.
    { return "Hierarquia da Unidade de Design"; }
trDesignUnitIndex()
QCString TranslatorPortuguese::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Implements Translator.
Definition at line 2076 of file translator_pt.h.
    { return "ndice de Unidades de Design"; }
trDesignUnitList()
QCString TranslatorPortuguese::trDesignUnitList () inline override virtual
VHDL design unit list.
Implements Translator.
Definition at line 2064 of file translator_pt.h.
    { return "Lista de Unidades de Design"; }
trDesignUnitListDescription()
QCString TranslatorPortuguese::trDesignUnitListDescription () inline override virtual
VHDL design unit list description.
Implements Translator.
Definition at line 2070 of file translator_pt.h.
    {
        return "Esta  uma lista de todos os membros de unidades de design "
                        "com ligaes para as entidades s quais pertencem:";
    }
trDesignUnitMembers()
QCString TranslatorPortuguese::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Implements Translator.
Definition at line 2067 of file translator_pt.h.
    { return "Membros da Unidade de Design"; }
trDesignUnits()
QCString TranslatorPortuguese::trDesignUnits () inline override virtual
VHDL design units.
Implements Translator.
Definition at line 2079 of file translator_pt.h.
    { return "Unidades de Design"; }
trDetailedDescription()
QCString TranslatorPortuguese::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 139 of file translator_pt.h.
    { return "Descrio detalhada"; }
trDetailLevel()
QCString TranslatorPortuguese::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1893 of file translator_pt.h.
    { return "nvel de detalhes"; }
trDetails()
QCString TranslatorPortuguese::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 143 of file translator_pt.h.
    { return "Detalhes"; }
trDictionaries()
QCString TranslatorPortuguese::trDictionaries () inline override virtual
Implements Translator.
Definition at line 2190 of file translator_pt.h.
    {
        return "Dicionrios";
    }
trDictionaryDocumentation()
QCString TranslatorPortuguese::trDictionaryDocumentation () inline override virtual
Implements Translator.
Definition at line 2194 of file translator_pt.h.
    {
        return "Dicionrios";
    }
trDir()
QCString TranslatorPortuguese::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1526 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "diretrio", "s");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorPortuguese::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1885 of file translator_pt.h.
    { return QCString("Grafo de dependncias do diretrio ")+name+":"; }
trDirDocumentation()
QCString TranslatorPortuguese::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1504 of file translator_pt.h.
    { return "Documentao do Diretrio"; }
trDirectories()
QCString TranslatorPortuguese::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1510 of file translator_pt.h.
    { return "Diretrios"; }
trDirIndex()
QCString TranslatorPortuguese::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1498 of file translator_pt.h.
    { return "Hierarquia de Diretrios"; }
trDirReference()
QCString TranslatorPortuguese::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1516 of file translator_pt.h.
    {
        QCString result = "Referncia do diretrio ";
        result += dirName;
        return result;
    }
trDirRelation()
QCString TranslatorPortuguese::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1765 of file translator_pt.h.
    {
      return "Relao " + QCString(name);
    }
trDocumentation()
QCString TranslatorPortuguese::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 399 of file translator_pt.h.
    { return "Documentao" + (!projName.isEmpty()? " de " + projName : ""); }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorPortuguese::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 485 of file translator_pt.h.
    { return "Enumeraes"; }
trEnumerationTypeDocumentation()
QCString TranslatorPortuguese::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 521 of file translator_pt.h.
    { return "Documentao dos valores da enumerao"; }
trEnumerationValueDocumentation()
QCString TranslatorPortuguese::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1557 of file translator_pt.h.
    { return "Documentao da enumerao"; }
trEnumerationValues()
QCString TranslatorPortuguese::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 503 of file translator_pt.h.
    { return "Valores de enumeraes"; }
trEnumGeneratedFromFiles()
QCString TranslatorPortuguese::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1905 of file translator_pt.h.
    { QCString result = "A documentao para esta enumerao foi gerada a partir";
      if (single) {
        result += "do seguinte ficheiro:";
      } else {
        result += "dos seguintes ficheiros:";
      }
      return result;
    }
trEnumName()
QCString TranslatorPortuguese::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 211 of file translator_pt.h.
    { return "enumerao"; }
trEnumReference()
QCString TranslatorPortuguese::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1916 of file translator_pt.h.
    {
      QCString result = "Referncia da enumerao ";
      return result + name;
    }
trEnumValue()
QCString TranslatorPortuguese::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 215 of file translator_pt.h.
    { return "valor enumerado"; }
trEventDocumentation()
QCString TranslatorPortuguese::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1372 of file translator_pt.h.
    {
      return "Documentao dos eventos";
    }
trEvents()
QCString TranslatorPortuguese::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1367 of file translator_pt.h.
    {
      return "Eventos";
    }
trExamples()
QCString TranslatorPortuguese::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 282 of file translator_pt.h.
    { return "Exemplos"; }
trExamplesDescription()
QCString TranslatorPortuguese::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 384 of file translator_pt.h.
    { return "Lista de todos os exemplos:"; }
trExceptionDocumentation()
QCString TranslatorPortuguese::trExceptionDocumentation () inline override virtual
Implements Translator.
Definition at line 2266 of file translator_pt.h.
    {
        return "Excees";
    }
trExceptionHierarchy()
QCString TranslatorPortuguese::trExceptionHierarchy () inline override virtual
Implements Translator.
Definition at line 2258 of file translator_pt.h.
    {
        return "Hierarquia de Excees";
    }
trExceptionHierarchyDescription()
QCString TranslatorPortuguese::trExceptionHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2262 of file translator_pt.h.
    {
        return "Esta  a lista parcialmente ordenadas de heranas:";
    }
trExceptionIndex()
QCString TranslatorPortuguese::trExceptionIndex () inline override virtual
Implements Translator.
Definition at line 2246 of file translator_pt.h.
    {
        return "ndice the Excees";
    }
trExceptionList()
QCString TranslatorPortuguese::trExceptionList () inline override virtual
Implements Translator.
Definition at line 2250 of file translator_pt.h.
    {
        return "Lista de Excees";
    }
trExceptionListDescription()
QCString TranslatorPortuguese::trExceptionListDescription () inline override virtual
Implements Translator.
Definition at line 2254 of file translator_pt.h.
    {
        return "Estas so as excees com suas respectivas descries:";
    }
trExceptions()
QCString TranslatorPortuguese::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 593 of file translator_pt.h.
    { return "Excepes"; }
trExportedModules()
QCString TranslatorPortuguese::trExportedModules () inline override virtual
Implements Translator.
Definition at line 2679 of file translator_pt.h.
    {
      return "Mdulos Exportados";
    }
trExtendsClass()
QCString TranslatorPortuguese::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1959 of file translator_pt.h.
    {
      return "estende a classe @0.";
    }
trFile()
QCString TranslatorPortuguese::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1244 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "ficheiro", "s");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorPortuguese::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 463 of file translator_pt.h.
    { return "Documentao do ficheiro"; }
trFileIn()
QCString TranslatorPortuguese::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1802 of file translator_pt.h.
    {
      return "Ficheiro em "+name;
    }
trFileIndex()
QCString TranslatorPortuguese::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 432 of file translator_pt.h.
    { return "ndice dos ficheiros"; }
trFileList()
QCString TranslatorPortuguese::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 248 of file translator_pt.h.
    { return "Lista de ficheiros"; }
trFileListDescription()
QCString TranslatorPortuguese::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 294 of file translator_pt.h.
    {
      QCString result="Lista de todos os ficheiros ";
      if (!extractAll) result+="documentados ";
      result+="com uma breve descrio:";
      return result;
    }
trFileMembers()
QCString TranslatorPortuguese::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 265 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globais";
      }
      else
      {
        return "Membros dos Ficheiros";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorPortuguese::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 362 of file translator_pt.h.
    {
      QCString result="Lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas as funes, variveis, definies, enumeraes e definies de tipo ";
        if (!extractAll) result+="documentadas ";
      }
      else
      {
        result+="todos os ficheiros membro ";
        if (!extractAll) result+="documentados ";
      }
      result+="com referncia para ";
      if (extractAll)
        result+="o ficheiro a que pertecem:";
      else
        result+="a respectiva documentao:";
      return result;
    }
References Config_getBool.
trFileMembersDescriptionTotal()
QCString TranslatorPortuguese::trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2430 of file translator_pt.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool masculine = PortugueseTranslatorUtils::isFileMemberHighlightMasculine(hl);
      QCString result="Esta  a list de ";
      result+= (masculine?"todos os ":"todas as ");
      switch (hl)
      {
        case FileMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="funes, variveis, definies, enumeraes e definies de tipos";
          }
          else
          {
            result+="membros do ficheiro";
          }
          break;
        case FileMemberHighlight::Functions:
          result+="funes";
          break;
        case FileMemberHighlight::Variables:
          result+="variveis";
          break;
        case FileMemberHighlight::Typedefs:
          result+="definies de tipos";
          break;
        case FileMemberHighlight::Sequences:
          result+="sequencias";
          break;
        case FileMemberHighlight::Dictionaries:
          result+="dicionrios";
          break;
        case FileMemberHighlight::Enums:
          result+="enumeraes";
          break;
        case FileMemberHighlight::EnumValues:
          result+="valores da enumerao";
          break;
        case FileMemberHighlight::Defines:
          result+="definies/macros";
          break;
        case FileMemberHighlight::Total: // for completeness
          break;
      }
      if (!extractAll)
      {
        result+= masculine? " documentados": " documentadas";
      }
      result+=" com links para ";
      if (extractAll)
        result+="os ficheiros aos quais pertencem:";
      else
        result+="a documentao:";
      return result;
    }
References FileMemberHighlight::All, Config_getBool, FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, PortugueseTranslatorUtils::isFileMemberHighlightMasculine(), FileMemberHighlight::Sequences, FileMemberHighlight::Total, FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
trFileReference()
QCString TranslatorPortuguese::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 660 of file translator_pt.h.
    {
      QCString result= "Referncia ao ficheiro ";
      result += fileName;
      return result;
    }
trFlowchart()
QCString TranslatorPortuguese::trFlowchart () inline override virtual
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2372 of file translator_pt.h.
    {
        return "Fluxograma:";
    }
trFriends()
QCString TranslatorPortuguese::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 620 of file translator_pt.h.
    { return "Amigos"; }
trFunctionAndProc()
QCString TranslatorPortuguese::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Implements Translator.
Definition at line 2082 of file translator_pt.h.
    { return "Funes/Procedimentos/Processos"; }
trFunctionDocumentation()
QCString TranslatorPortuguese::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 527 of file translator_pt.h.
    { return "Documentao das funes"; }
trFunctions()
QCString TranslatorPortuguese::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 491 of file translator_pt.h.
    { return "Funes"; }
trGeneratedAt()
QCString TranslatorPortuguese::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 554 of file translator_pt.h.
    {
      QCString result="Gerado em "+date;
      if (!projName.isEmpty()) result+=" para "+projName;
      result+=" por";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorPortuguese::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 203 of file translator_pt.h.
    { QCString result="Gerado automaticamente por Doxygen";
      if (!s.isEmpty()) result+=" para "+s;
      result+=" a partir do cdigo fonte.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorPortuguese::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 597 of file translator_pt.h.
    { return "Gerado por"; }
trGeneratedFromFiles()
QCString TranslatorPortuguese::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 800 of file translator_pt.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="A documentao para ";
      switch(compType)
      {
        case ClassDef::Class:      result+=vhdlOpt?"esta Unidade de Design":"esta classe"; break;
        case ClassDef::Struct:     result+="esta estrutura"; break;
        case ClassDef::Union:      result+="esta unio"; break;
        case ClassDef::Interface:  result+="este interface"; break;
        case ClassDef::Protocol:   result+="este protocolo"; break;
        case ClassDef::Category:   result+="esta categoria"; break;
        case ClassDef::Exception:  result+="esta excepo"; break;
        default: break;
      }
      result+=" foi gerada a partir ";
      if (single) result+=" do seguinte ficheiro:";
      else result+="dos seguintes ficheiros:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorPortuguese::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1711 of file translator_pt.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="A documentao para ";
      switch(compType)
      {
        case ClassDef::Class:      result+="este modulo "; break;
        case ClassDef::Struct:     result+="este tipo "; break;
        case ClassDef::Union:      result+="esta unio "; break;
        case ClassDef::Interface:  result+="esta interface "; break;
        case ClassDef::Protocol:   result+="esto protocolo "; break;
        case ClassDef::Category:   result+="esta categoria "; break;
        case ClassDef::Exception:  result+="esta exceo "; break;
        default: break;
      }
      result+=" foi gerada a partir do";
      if (single)
        result+=" seguinte ficheiro:";
      else
        result+="s seguintes ficheiros:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorPortuguese::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1289 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "globa", "is", "l");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorPortuguese::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1777 of file translator_pt.h.
    {
      return "Namespace global";
    }
trGotoDocumentation()
QCString TranslatorPortuguese::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 889 of file translator_pt.h.
    {
      return "Ir para a documentao deste ficheiro.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorPortuguese::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 922 of file translator_pt.h.
    {
      return "Ir para a representao grfica da hierarquia da classe";
    }
trGotoSourceCode()
QCString TranslatorPortuguese::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 884 of file translator_pt.h.
    {
      return "Ir para o cdigo fonte deste ficheiro.";
    }
trGotoTextualHierarchy()
QCString TranslatorPortuguese::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 926 of file translator_pt.h.
    {
      return "Ir para a representao textual da hierarquia da classe";
    }
trGraphicalHierarchy()
QCString TranslatorPortuguese::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 918 of file translator_pt.h.
    {
      return "Representao grfica da hiearquia da classe";
    }
trGroup()
QCString TranslatorPortuguese::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1262 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "grupo", "s");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorPortuguese::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 411 of file translator_pt.h.
    { return "ndice da hierarquia"; }
trImplementedFromList()
QCString TranslatorPortuguese::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1323 of file translator_pt.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorPortuguese::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1331 of file translator_pt.h.
    {
      return "Implementado em "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImportant()
QCString TranslatorPortuguese::trImportant () inline override virtual
Implements Translator.
Definition at line 2695 of file translator_pt.h.
    {
      return "Importante";
    }
trInclByDepGraph()
QCString TranslatorPortuguese::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 1018 of file translator_pt.h.
    {
      return "Este grafo mostra quais so os ficheiros que incluem directamente ou indirectamente este ficheiro:";
    }
trInclDepGraph()
QCString TranslatorPortuguese::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 874 of file translator_pt.h.
    {
      return "Diagrama de dependncias de incluso para "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorPortuguese::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1811 of file translator_pt.h.
    {
      return "Inclui ficheiro em "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorPortuguese::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 197 of file translator_pt.h.
    { return ", incluindo todos os membros herdados."; }
trInheritedByList()
QCString TranslatorPortuguese::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 732 of file translator_pt.h.
    {
      return "Herdado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorPortuguese::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1923 of file translator_pt.h.
    { return QCString(members)+" herdados de "+what; }
trInheritsList()
QCString TranslatorPortuguese::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 724 of file translator_pt.h.
    {
      return "Derivada de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorPortuguese::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 909 of file translator_pt.h.
    {
      return "Valor inicial:";
    }
trInstanceMethods()
QCString TranslatorPortuguese::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1975 of file translator_pt.h.
    {
      return "Mtodos de instncia";
    }
trInterfaceDocumentation()
QCString TranslatorPortuguese::trInterfaceDocumentation () inline override virtual
Implements Translator.
Definition at line 2222 of file translator_pt.h.
    {
        return "Interfaces";
    }
trInterfaceHierarchy()
QCString TranslatorPortuguese::trInterfaceHierarchy () inline override virtual
Implements Translator.
Definition at line 2214 of file translator_pt.h.
    {
        return "Hierarquia de Interfaces";
    }
trInterfaceHierarchyDescription()
QCString TranslatorPortuguese::trInterfaceHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2218 of file translator_pt.h.
    {
        return "Esta  a lista parcialmente ordenadas de heranas:";
    }
trInterfaceIndex()
QCString TranslatorPortuguese::trInterfaceIndex () inline override virtual
Implements Translator.
Definition at line 2202 of file translator_pt.h.
    {
        return "ndice de Interfaces";
    }
trInterfaceList()
QCString TranslatorPortuguese::trInterfaceList () inline override virtual
Implements Translator.
Definition at line 2206 of file translator_pt.h.
    {
        return "Lista de Interfaces";
    }
trInterfaceListDescription()
QCString TranslatorPortuguese::trInterfaceListDescription () inline override virtual
Implements Translator.
Definition at line 2210 of file translator_pt.h.
    {
        return "Estas so as interfaces com suas respectivas descries:";
    }
trInterfaces()
QCString TranslatorPortuguese::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1992 of file translator_pt.h.
    { return "Interfaces Exportadas"; }
trInvariant()
QCString TranslatorPortuguese::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 904 of file translator_pt.h.
    {
      return "Invariante";
    }
trISOLang()
QCString TranslatorPortuguese::trISOLang () inline override virtual
Implements Translator.
Definition at line 119 of file translator_pt.h.
    {
      return "pt";
    }
trLegend()
QCString TranslatorPortuguese::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1095 of file translator_pt.h.
    {
      return "legenda";
    }
trLegendDocs()
QCString TranslatorPortuguese::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 1037 of file translator_pt.h.
    {
      return
        "Esta pgina explica como interpretar os grafos gerados pelo doxygen.<p>\n"
        "Considere o seguinte exemplo:\n"
        "\\code\n"
        "/*! Esta classe vai estar escondida devido  truncao */\n"
        "class Invisible { };\n\n"
        "/*! Esta classe tem a relao de herana escondida */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe no documentada por comentrios doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe derivada usando derivao pblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe derivada usando derivao protegida */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe derivada usando derivao privada */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe usada pela classe Inherited */\n"
        "class Used { };\n\n"
        "/*! Super classe que deriva de vrias classes */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Isto ir gerar o seguinte grfo:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "As caixas no grafo anterior tm as seguintes interpretaes:\n"
        "<ul>\n"
        "<li>Uma caixa inteiramente preta representa a estrutura ou a classe para "
        "a qual o grafo foi gerado.\n"
        "<li>Uma caixa com borda preta representa uma estrutura ou classe documentada.\n"
        "<li>Uma caixa com borda cinzenta representa uma estrutura ou classe no documentada.\n"
        "<li>Uma caixa com borda vermelha representa uma estrutura ou classe documentada onde "
        "nem todas as relaes de herana/encapsulamento so exibidas. Um grafo  truncado "
        "quando no cabe na sua rea predefinida.\n"
        "</ul>\n"
        "As setas tm a seguinte interpretao:\n"
        "<ul>\n"
        "<li>Uma seta azul escura representa uma relao de herana pblica entre duas classes.\n"
        "<li>Uma seta verde escura representa uma relao de herana protegida.\n"
        "<li>Uma seta vermelha escura representa uma relao de herana privada.\n"
        "<li>Uma seta rocha em tracejado representa uma relao de encapsulamento ou uso por "
        "parte de outra classe. A legenda da seta contm o nome da varivel ou variveis da "
        "relao. A seta aponta da classe que estabelece a relao para a classe ou estrutura que "
        " acessvel.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorPortuguese::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 1032 of file translator_pt.h.
    {
      return "Legenda do grafo";
    }
trListOfAllMembers()
QCString TranslatorPortuguese::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 185 of file translator_pt.h.
    { return "Mostrar lista completa dos membros"; }
trLoading()
QCString TranslatorPortuguese::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1771 of file translator_pt.h.
    {
      return "Carregando...";
    }
trMainPage()
QCString TranslatorPortuguese::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 833 of file translator_pt.h.
    { return "Pgina principal"; }
trMember()
QCString TranslatorPortuguese::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1280 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "membro", "s");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorPortuguese::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 168 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentao dos campos e atributos";
      }
      else
      {
        return "Documentao dos dados membro";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorPortuguese::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 151 of file translator_pt.h.
    { return "Documentao das enumeraes"; }
trMemberFunctionDocumentation()
QCString TranslatorPortuguese::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 155 of file translator_pt.h.
    {
        if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
        {
          return "Documentao das funes, procedimentos e processos";
        }
        else
        {
            return "Documentao das funes";
        }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran()
QCString TranslatorPortuguese::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1566 of file translator_pt.h.
    { return "Documentao de Funo Membro/Subrotina"; }
trMemberList()
QCString TranslatorPortuguese::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 189 of file translator_pt.h.
    { return "Lista dos membros"; }
trMemberTypedefDocumentation()
QCString TranslatorPortuguese::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 147 of file translator_pt.h.
    { return "Documentao das definies de tipo"; }
trMethodDocumentation()
QCString TranslatorPortuguese::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1982 of file translator_pt.h.
    {
      return "Documentao do mtodo";
    }
trModule()
QCString TranslatorPortuguese::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1704 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "modulo", "s");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorPortuguese::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 438 of file translator_pt.h.
    { return "Documentao do mdulo"; }
trModuleIndex()
QCString TranslatorPortuguese::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 405 of file translator_pt.h.
    { return "ndice dos mdulos"; }
trModuleMembersDescriptionTotal()
QCString TranslatorPortuguese::trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2633 of file translator_pt.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool masculine = PortugueseTranslatorUtils::isModuleMemberHighlightMasculine(hl);
      QCString result="Esta  a list de ";
      result+= (masculine?"todos os ":"todas as ");
      QCString singularResult = "";
      QCString pluralResult = "";
      switch (hl)
      {
        case ModuleMemberHighlight::All:
          singularResult="membro";
          break;
        case ModuleMemberHighlight::Functions:
          singularResult="funo";
          pluralResult="funes";
          break;
        case ModuleMemberHighlight::Variables:
          singularResult="varivel";
          pluralResult="variveis";
          break;
        case ModuleMemberHighlight::Typedefs:
          singularResult="definio de tipo";
          pluralResult="definies de tipo";
          break;
        case ModuleMemberHighlight::Enums:
          singularResult="enumerao";
          pluralResult="enumeraes";
          break;
        case ModuleMemberHighlight::EnumValues:
          singularResult="valor enumerado";
          pluralResult="valores enumerados";
          break;
        case ModuleMemberHighlight::Total: // for completeness
          break;
      }
      result+=(pluralResult.isEmpty() ? singularResult+"s" : pluralResult);
      result+="do mdulo ";
      if (!extractAll) result+="documentado ";
      result+=" com links para ";
      if (extractAll)
        result+="a documentao de cada " + singularResult + ":";
      else
        result+="o mdulo a que pertencem:";
      return result;
    }
References ModuleMemberHighlight::All, Config_getBool, ModuleMemberHighlight::Enums, ModuleMemberHighlight::EnumValues, ModuleMemberHighlight::Functions, QCString::isEmpty(), PortugueseTranslatorUtils::isModuleMemberHighlightMasculine(), ModuleMemberHighlight::Total, ModuleMemberHighlight::Typedefs, and ModuleMemberHighlight::Variables.
trModuleReference()
QCString TranslatorPortuguese::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1666 of file translator_pt.h.
    {
      QCString result = "Referncia do Mdulo ";
      result += namespaceName;
      return result;
    }
trModules()
QCString TranslatorPortuguese::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 227 of file translator_pt.h.
    { return "Mdulos"; }
trModulesDescription()
QCString TranslatorPortuguese::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 392 of file translator_pt.h.
    { return "Lista de todos os mdulos:"; }
trModulesIndex()
QCString TranslatorPortuguese::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1697 of file translator_pt.h.
    { return "ndice dos Mdulos"; }
trModulesList()
QCString TranslatorPortuguese::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1629 of file translator_pt.h.
    { return "Lista de Mdulos"; }
trModulesListDescription()
QCString TranslatorPortuguese::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1633 of file translator_pt.h.
    {
      QCString result="Esta  a lista de todos os mdulos ";
      if (!extractAll) result+="documentados ";
      result+="com descries resumidas:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorPortuguese::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1678 of file translator_pt.h.
    {
      QCString result="Esta  a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos mdulos com links para ";
      if (extractAll)
      {
        result+="a documentao dos mdulos para cada membro:";
      }
      else
      {
        result+="os mdulos a que pertencem:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorPortuguese::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1674 of file translator_pt.h.
    { return "Membros do Mdulo"; }
trMonth()
QCString TranslatorPortuguese::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1854 of file translator_pt.h.
    {
      static const char *months_short[] = { "jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez" };
      static const char *months_full[]  = { "janeiro", "fevereiro", "maro", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorPortuguese::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 181 of file translator_pt.h.
    { return "Mais..."; }
trNamespace()
QCString TranslatorPortuguese::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1253 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "namespace", "s");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorPortuguese::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 780 of file translator_pt.h.
    { return "Documentao dos namespaces"; }
trNamespaceIndex()
QCString TranslatorPortuguese::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 774 of file translator_pt.h.
    { return "ndice dos namespaces"; }
trNamespaceList()
QCString TranslatorPortuguese::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 605 of file translator_pt.h.
    { return "Lista de namespaces"; }
trNamespaceListDescription()
QCString TranslatorPortuguese::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 609 of file translator_pt.h.
    {
      QCString result="Lista ";
      if (!extractAll) result+="de toda a documentao ";
      result+="dos namespaces com uma breve descrio:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorPortuguese::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 758 of file translator_pt.h.
    {
      QCString result="Lista ";
      if (extractAll) result+="de todos os ";
      else result+="de toda a documentao dos ";
      result+="membros do namespace com referncia para ";
      if (extractAll)
        result+="a documentao de cada membro:";
      else
        result+="o namespace correspondente:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorPortuguese::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 754 of file translator_pt.h.
    { return "Membros do namespace"; }
trNamespaceMembersDescriptionTotal()
QCString TranslatorPortuguese::trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2562 of file translator_pt.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool masculine = PortugueseTranslatorUtils::isNamespaceMemberHighlightMasculine(hl);
      QCString result="Esta  a list de ";
      result+= (masculine?"todos os ":"todas as ");
      QCString singularResult = "";
      QCString pluralResult = "";
      switch (hl)
      {
        case NamespaceMemberHighlight::All:
          singularResult="membros";
          break;
        case NamespaceMemberHighlight::Functions:
          singularResult="funo";
          pluralResult="funes";
          break;
        case NamespaceMemberHighlight::Variables:
          singularResult="varivel";
          pluralResult="variveis";
          break;
        case NamespaceMemberHighlight::Typedefs:
          singularResult="definio de tipo";
          pluralResult="definies de tipo";
          break;
        case NamespaceMemberHighlight::Sequences:
          singularResult="sequencia";
          pluralResult="sequencias";
          break;
        case NamespaceMemberHighlight::Dictionaries:
          singularResult="dicionrio";
          break;
        case NamespaceMemberHighlight::Enums:
          singularResult="enumerao";
          pluralResult="enumeraes";
          break;
        case NamespaceMemberHighlight::EnumValues:
          singularResult="valor enumerado";
          pluralResult="valores enumerados";
          break;
        case NamespaceMemberHighlight::Total: // for completeness
          break;
      }
      result+=(pluralResult.isEmpty() ? singularResult+"s" : pluralResult);
      result+=" do namespace ";
      if (!extractAll) result+="documentado ";
      result+=" com links para ";
      if (extractAll)
        result+="a documentao de cada " + singularResult + ":";
      else
        result+="o namespace a que pertencem:";
      return result;
    }
References NamespaceMemberHighlight::All, Config_getBool, NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, QCString::isEmpty(), PortugueseTranslatorUtils::isNamespaceMemberHighlightMasculine(), NamespaceMemberHighlight::Sequences, NamespaceMemberHighlight::Total, NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
trNamespaceReference()
QCString TranslatorPortuguese::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 668 of file translator_pt.h.
    {
      QCString result= "Referncia ao namespace ";
      result += namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorPortuguese::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 790 of file translator_pt.h.
    { return "Namespaces"; }
trNoMatches()
QCString TranslatorPortuguese::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1789 of file translator_pt.h.
    {
      return "Nenhuma entrada encontrada";
    }
trNote()
QCString TranslatorPortuguese::trNote () inline override virtual
Implements Translator.
Definition at line 939 of file translator_pt.h.
    {
      return "Nota";
    }
trOperationDocumentation()
QCString TranslatorPortuguese::trOperationDocumentation () inline override virtual
Implements Translator.
Definition at line 2292 of file translator_pt.h.
    {
        return "Operaes";
    }
trOperations()
QCString TranslatorPortuguese::trOperations () inline override virtual
Implements Translator.
Definition at line 2288 of file translator_pt.h.
    {
        return "Operaes";
    }
trOverloadText()
QCString TranslatorPortuguese::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1537 of file translator_pt.h.
    {
       return "Este  um mtodo provido por convenincia. "
                "Ele difere do mtodo acima apenas na lista de "
                "argumentos que devem ser utilizados.";
    }
trPackage()
QCString TranslatorPortuguese::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1147 of file translator_pt.h.
    {
      return "Pacote "+name;
    }
trPackageAttribs()
QCString TranslatorPortuguese::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1408 of file translator_pt.h.
    {
      return "Atributos do Pacote";
    }
trPackageFunctions()
QCString TranslatorPortuguese::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1390 of file translator_pt.h.
    {
      return "Funes do Pacote";
    }
trPackageList()
QCString TranslatorPortuguese::trPackageList () inline override virtual
Implements Translator.
Definition at line 2362 of file translator_pt.h.
    { return "Lista de pacotes"; }
trPackageListDescription()
QCString TranslatorPortuguese::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1152 of file translator_pt.h.
    {
      return "Lista de pacotes com uma breve descrio (se disponvel):";
    }
trPackageMembers()
QCString TranslatorPortuguese::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1394 of file translator_pt.h.
    {
      return "Membros do Pacote";
    }
trPackages()
QCString TranslatorPortuguese::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1157 of file translator_pt.h.
    {
      return "Pacotes";
    }
trPackageTypes()
QCString TranslatorPortuguese::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1383 of file translator_pt.h.
    {
      return "Tipos do Pacote";
    }
trPage()
QCString TranslatorPortuguese::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1271 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "pgina", "s");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorPortuguese::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 839 of file translator_pt.h.
    { return "p. "; }
trPageIndex()
QCString TranslatorPortuguese::trPageIndex () inline override virtual
Implements Translator.
Definition at line 930 of file translator_pt.h.
    {
      return "ndice da pgina";
    }
trPanelSynchronisationTooltip()
QCString TranslatorPortuguese::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1940 of file translator_pt.h.
    {
      QCString opt = enable ? "ativar" : "desativar";
      return "clique para "+opt+" a sincronizao do painel";
    }
trParameters()
QCString TranslatorPortuguese::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 589 of file translator_pt.h.
    { return "Parmetros"; }
trPostcondition()
QCString TranslatorPortuguese::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 899 of file translator_pt.h.
    {
      return "Poscondio";
    }
trPrecondition()
QCString TranslatorPortuguese::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 894 of file translator_pt.h.
    {
      return "Precondio";
    }
trPrivateAttribs()
QCString TranslatorPortuguese::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 978 of file translator_pt.h.
    {
      return "Atributos Privados";
    }
trPrivateMembers()
QCString TranslatorPortuguese::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 690 of file translator_pt.h.
    { return "Membros privados"; }
trPrivateSlots()
QCString TranslatorPortuguese::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 692 of file translator_pt.h.
    { return "Slots privados"; }
trPrivateTypes()
QCString TranslatorPortuguese::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 974 of file translator_pt.h.
    {
      return "Tipos Privados";
    }
trProperties()
QCString TranslatorPortuguese::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1120 of file translator_pt.h.
    {
      return "Propriedades";
    }
trPropertyDocumentation()
QCString TranslatorPortuguese::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1125 of file translator_pt.h.
    {
      return "Documentao das propriedades";
    }
trProtectedAttribs()
QCString TranslatorPortuguese::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 966 of file translator_pt.h.
    {
      return "Atributos Protegidos";
    }
trProtectedMembers()
QCString TranslatorPortuguese::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 684 of file translator_pt.h.
    { return "Membros protegidos"; }
trProtectedSlots()
QCString TranslatorPortuguese::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 686 of file translator_pt.h.
    { return "Slots protegidos"; }
trProtectedTypes()
QCString TranslatorPortuguese::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 962 of file translator_pt.h.
    {
      return "Tipos Protegidos";
    }
trProvidedByCategory()
QCString TranslatorPortuguese::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1950 of file translator_pt.h.
    {
      return "Provido pela categoria @0.";
    }
trPublicAttribs()
QCString TranslatorPortuguese::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 947 of file translator_pt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de Dados";
      }
      else
      {
        return "Atributos Pblicos";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorPortuguese::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 676 of file translator_pt.h.
    { return "Membros pblicos"; }
trPublicSlots()
QCString TranslatorPortuguese::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 678 of file translator_pt.h.
    { return "Slots pblicos"; }
trPublicTypes()
QCString TranslatorPortuguese::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 943 of file translator_pt.h.
    {
      return "Tipos Pblicos";
    }
trReferencedBy()
QCString TranslatorPortuguese::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 1006 of file translator_pt.h.
    {
      return "Referenciado por";
    }
trReferenceManual()
QCString TranslatorPortuguese::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 467 of file translator_pt.h.
    { return "Manual de referncia"; }
trReferences()
QCString TranslatorPortuguese::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1311 of file translator_pt.h.
    {
      return "Referncias";
    }
trReimplementedFromList()
QCString TranslatorPortuguese::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 740 of file translator_pt.h.
    {
      return "Reimplementado de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorPortuguese::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 748 of file translator_pt.h.
    {
      return "Reimplementado em "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorPortuguese::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 630 of file translator_pt.h.
    { return "Documentao das classes amigas e funes relacionadas"; }
trRelatedFunctions()
QCString TranslatorPortuguese::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 131 of file translator_pt.h.
    { return "Funes associadas"; }
trRelatedPages()
QCString TranslatorPortuguese::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 278 of file translator_pt.h.
    { return "Pginas relacionadas"; }
trRelatedPagesDescription()
QCString TranslatorPortuguese::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 388 of file translator_pt.h.
    { return "Lista de documentao relacionada:"; }
trRelatedSubscript()
QCString TranslatorPortuguese::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 135 of file translator_pt.h.
    { return "(Note que no so funes membro)"; }
trRelatedSymbolDocumentation()
QCString TranslatorPortuguese::trRelatedSymbolDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes.
Supersedes trRelatedFunctionDocumentation
Implements Translator.
Definition at line 2404 of file translator_pt.h.
    { return "Documentao dos smbolos amigos e relacionados"; }
trRelatedSymbols()
QCString TranslatorPortuguese::trRelatedSymbols () inline override virtual
Please translate also updated body of the method trMemberFunctionDocumentation(), now better adapted for VHDL sources documentation.
used in the compound documentation before a list of related symbols.
Supersedes trRelatedFunctions
Implements Translator.
Definition at line 2389 of file translator_pt.h.
    { return "Smbolos relacionados"; }
trRelatedSymbolsSubscript()
QCString TranslatorPortuguese::trRelatedSymbolsSubscript () inline override virtual
subscript for the related symbols
Supersedes trRelatedSubscript
Implements Translator.
Definition at line 2396 of file translator_pt.h.
    { return "(Note que estes no so smbolos membros.)"; }
trRemarks()
QCString TranslatorPortuguese::trRemarks () inline override virtual
Implements Translator.
Definition at line 1010 of file translator_pt.h.
    {
      return "Observaes";
    }
trReturns()
QCString TranslatorPortuguese::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 581 of file translator_pt.h.
    { return "Retorna"; }
trReturnValues()
QCString TranslatorPortuguese::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 828 of file translator_pt.h.
    { return "Valores retornados"; }
trRTFansicp()
QCString TranslatorPortuguese::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1211 of file translator_pt.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorPortuguese::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1220 of file translator_pt.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorPortuguese::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1226 of file translator_pt.h.
    {
      return "ndice";
    }
trRTFTableOfContents()
QCString TranslatorPortuguese::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1343 of file translator_pt.h.
    {
      return "ndice";
    }
trSearch()
QCString TranslatorPortuguese::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 286 of file translator_pt.h.
    { return "Localizar"; }
trSearching()
QCString TranslatorPortuguese::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1783 of file translator_pt.h.
    {
      return "Procurando...";
    }
trSearchMatches()
QCString TranslatorPortuguese::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1475 of file translator_pt.h.
    {
      return "Resultados:";
    }
trSearchResults()
QCString TranslatorPortuguese::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1456 of file translator_pt.h.
    {
      if (numDocuments==0)
      {
        return "Nenhum documento foi encontrado.";
      }
      else if (numDocuments==1)
      {
        return "Apenas <b>1</b> documento foi encontrado.";
      }
      else
      {
        return "<b>$num</b> documentos encontrados. "
               "Os melhores resultados vem primeiro.";
      }
    }
trSearchResultsTitle()
QCString TranslatorPortuguese::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1444 of file translator_pt.h.
    {
      return "Resultado da Busca";
    }
trSeeAlso()
QCString TranslatorPortuguese::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 585 of file translator_pt.h.
    { return "Veja tambm"; }
trSequenceDocumentation()
QCString TranslatorPortuguese::trSequenceDocumentation () inline override virtual
Implements Translator.
Definition at line 2186 of file translator_pt.h.
    {
        return "Sequncias";
    }
trSequences()
QCString TranslatorPortuguese::trSequences () inline override virtual
Implements Translator.
Definition at line 2182 of file translator_pt.h.
    {
        return "Sequncias";
    }
trServiceGeneratedFromFiles()
QCString TranslatorPortuguese::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 2028 of file translator_pt.h.
    {
      // single is true implies a single file
      QCString result="A documentao para este servio "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte ficheiro:";
      } else {
        result+="dos: seguintes ficheiros:";
      }
      return result;
    }
trServiceReference()
QCString TranslatorPortuguese::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 2012 of file translator_pt.h.
    {
      QCString result = "Referncia do servio ";
      result += sName;
      return result;
    }
trServices()
QCString TranslatorPortuguese::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1996 of file translator_pt.h.
    { return "Servios Includos"; }
trSignals()
QCString TranslatorPortuguese::trSignals () inline override virtual
Implements Translator.
Definition at line 680 of file translator_pt.h.
    { return "Sinais"; }
trSince()
QCString TranslatorPortuguese::trSince () inline override virtual
Implements Translator.
Definition at line 1022 of file translator_pt.h.
    {
      return "Desde";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorPortuguese::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 2042 of file translator_pt.h.
    {
      // single is true implies a single file
      QCString result="A documentao para este singleton "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte ficheiro:";
      } else {
        result+="dos: seguintes ficheiros:";
      }
      return result;
    }
trSingletonReference()
QCString TranslatorPortuguese::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 2020 of file translator_pt.h.
    {
      QCString result = "Referncia do Singleton ";
      result += sName;
      return result;
    }
trSliceInterfaces()
QCString TranslatorPortuguese::trSliceInterfaces () inline override virtual
Implements Translator.
Definition at line 2198 of file translator_pt.h.
    {
        return "Interfaces";
    }
trSourceFile()
QCString TranslatorPortuguese::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1486 of file translator_pt.h.
    {
      return  "Cdigo-Fonte de " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorPortuguese::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1415 of file translator_pt.h.
    {
      return "Atributos Estticos do Pacote";
    }
trStaticPackageFunctions()
QCString TranslatorPortuguese::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1401 of file translator_pt.h.
    {
      return "Funes Estticas do Pacote";
    }
trStaticPrivateAttribs()
QCString TranslatorPortuguese::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 982 of file translator_pt.h.
    {
      return "Atributos Privados Estticos";
    }
trStaticPrivateMembers()
QCString TranslatorPortuguese::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 694 of file translator_pt.h.
    { return "Membros privados estticos"; }
trStaticProtectedAttribs()
QCString TranslatorPortuguese::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 970 of file translator_pt.h.
    {
      return "Atributos Protegidos Estticos";
    }
trStaticProtectedMembers()
QCString TranslatorPortuguese::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 688 of file translator_pt.h.
    { return "Membros protegidos estticos"; }
trStaticPublicAttribs()
QCString TranslatorPortuguese::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 958 of file translator_pt.h.
    {
      return "Atributos Pblicos Estticos";
    }
trStaticPublicMembers()
QCString TranslatorPortuguese::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 682 of file translator_pt.h.
    { return "Membros pblicos estticos"; }
trStructDocumentation()
QCString TranslatorPortuguese::trStructDocumentation () inline override virtual
Implements Translator.
Definition at line 2242 of file translator_pt.h.
    {
        return "Estruturas";
    }
trStructIndex()
QCString TranslatorPortuguese::trStructIndex () inline override virtual
Implements Translator.
Definition at line 2230 of file translator_pt.h.
    {
        return "ndice de Estruturas";
    }
trStructList()
QCString TranslatorPortuguese::trStructList () inline override virtual
Implements Translator.
Definition at line 2234 of file translator_pt.h.
    {
        return "Lista de Estruturas";
    }
trStructListDescription()
QCString TranslatorPortuguese::trStructListDescription () inline override virtual
Implements Translator.
Definition at line 2238 of file translator_pt.h.
    {
        return "Estas so as estruturas com suas respectivas descries:";
    }
trStructs()
QCString TranslatorPortuguese::trStructs () inline override virtual
Implements Translator.
Definition at line 2226 of file translator_pt.h.
    {
        return "Estruturas";
    }
trSubprogram()
QCString TranslatorPortuguese::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1748 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "subprograma", "s");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorPortuguese::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1619 of file translator_pt.h.
    { return "Documentao da Funo/Subrotina"; }
trSubprograms()
QCString TranslatorPortuguese::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1613 of file translator_pt.h.
    { return "Funes/Subrotinas"; }
trTemplateParameters()
QCString TranslatorPortuguese::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1897 of file translator_pt.h.
    { return "Parmetros de template"; }
trTest()
QCString TranslatorPortuguese::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1105 of file translator_pt.h.
    {
      return "Teste";
    }
trTestList()
QCString TranslatorPortuguese::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1110 of file translator_pt.h.
    {
      return "Lista de teste";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorPortuguese::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 193 of file translator_pt.h.
    { return "Lista completa de todos os membros de"; }
trTodo()
QCString TranslatorPortuguese::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 992 of file translator_pt.h.
    {
      return "Tarefa";
    }
trTodoList()
QCString TranslatorPortuguese::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 997 of file translator_pt.h.
    {
      return "Lista de tarefas";
    }
trTopicDocumentation()
QCString TranslatorPortuguese::trTopicDocumentation () inline override virtual
Implements Translator.
Definition at line 2625 of file translator_pt.h.
    { return "Tpico"; }
trTopicIndex()
QCString TranslatorPortuguese::trTopicIndex () inline override virtual
Implements Translator.
Definition at line 2629 of file translator_pt.h.
    { return "ndice de Tpicos"; }
trTopicList()
QCString TranslatorPortuguese::trTopicList () inline override virtual
Implements Translator.
Definition at line 2627 of file translator_pt.h.
    { return "Lista de Tpicos"; }
trTopicListDescription()
QCString TranslatorPortuguese::trTopicListDescription () inline override virtual
Implements Translator.
Definition at line 2631 of file translator_pt.h.
    { return "Esta  uma lista de todos os tpicos e suas descries:"; }
trTopics()
QCString TranslatorPortuguese::trTopics () inline override virtual
Implements Translator.
Definition at line 2623 of file translator_pt.h.
    { return "Tpicos"; }
trType()
QCString TranslatorPortuguese::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1740 of file translator_pt.h.
    {
      return createNoun(first_capital, singular, "tipo", "s");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trTypeConstraints()
QCString TranslatorPortuguese::trTypeConstraints () inline override virtual
C# Type Contraint list
Implements Translator.
Definition at line 1754 of file translator_pt.h.
    {
      return "Restries do Tipo";
    }
trTypedefDocumentation()
QCString TranslatorPortuguese::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 515 of file translator_pt.h.
    { return "Documentao dos tipos"; }
trTypedefs()
QCString TranslatorPortuguese::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 479 of file translator_pt.h.
    { return "Definies de tipos"; }
trTypeDocumentation()
QCString TranslatorPortuguese::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1607 of file translator_pt.h.
    { return "Documentao dos Tipos de Dados"; }
trVariableDocumentation()
QCString TranslatorPortuguese::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 533 of file translator_pt.h.
    { return "Documentao das variveis"; }
trVariables()
QCString TranslatorPortuguese::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 497 of file translator_pt.h.
    { return "Variveis"; }
trVersion()
QCString TranslatorPortuguese::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 573 of file translator_pt.h.
    { return "Verso"; }
trVhdlType()
QCString TranslatorPortuguese::trVhdlType (VhdlSpecifier type, bool single) inline override virtual
VHDL type.
Implements Translator.
Definition at line 2085 of file translator_pt.h.
    {
      switch(type)
      {
        case VhdlSpecifier::LIBRARY:
          if (single) return "Biblioteca";
          else        return "Bibliotecas";
        case VhdlSpecifier::PACKAGE:
          if (single) return "Pacote";
          else        return "Pacotes";
        case VhdlSpecifier::SIGNAL:
          if (single) return "Sinal";
          else        return "Sinais";
        case VhdlSpecifier::COMPONENT:
          if (single) return "Componente";
          else        return "Componentes";
        case VhdlSpecifier::CONSTANT:
          if (single) return "Constante";
          else        return "Constantes";
        case VhdlSpecifier::ENTITY:
          if (single) return "Entidade";
          else        return "Entidades";
        case VhdlSpecifier::TYPE:
          if (single) return "Tipo";
          else        return "Tipos";
        case VhdlSpecifier::SUBTYPE:
          if (single) return "Subtipo";
          else        return "Subtipos";
        case VhdlSpecifier::FUNCTION:
          if (single) return "Funo";
          else        return "Funes";
        case VhdlSpecifier::RECORD:
          if (single) return "Registro";
          else        return "Registros";
        case VhdlSpecifier::PROCEDURE:
          if (single) return "Procedimento";
          else        return "Procedimentos";
        case VhdlSpecifier::ARCHITECTURE:
          if (single) return "Arquitetura";
          else        return "Arquiteturas";
        case VhdlSpecifier::ATTRIBUTE:
          if (single) return "Atributo";
          else        return "Atributos";
        case VhdlSpecifier::PROCESS:
          if (single) return "Processo";
          else        return "Processos";
        case VhdlSpecifier::PORT:
          if (single) return "Porta";
          else        return "Portas";
        case VhdlSpecifier::USE:
          if (single) return "clusula de uso";
          else        return "clusulas de uso";
        case VhdlSpecifier::GENERIC:
          if (single) return "Generico";
          else        return "Genericos";
        case VhdlSpecifier::PACKAGE_BODY:
          return "Corpo do Pacote";
        case VhdlSpecifier::UNITS:
          return "Unidades";
        case VhdlSpecifier::SHAREDVARIABLE:
          if (single) return "Varivel Compartilhada";
          else        return "Variveis Compartilhadas";
        case VhdlSpecifier::VFILE:
          if (single) return "Ficheiro";
          else        return "Ficheiros";
        case VhdlSpecifier::GROUP:
          if (single) return "Grupo";
          else        return "Grupos";
        case VhdlSpecifier::INSTANTIATION:
          if (single) return "Instncia";
          else        return "Instncias";
        case VhdlSpecifier::ALIAS:
          if (single) return "Apelido";
          else        return "Apelidos";
        case VhdlSpecifier::CONFIG:
          if (single) return "Configurao";
          else        return "Configuraes";
        case VhdlSpecifier::MISCELLANEOUS:
          return "Outros"; // Is this correct for VHDL?
        case VhdlSpecifier::UCF_CONST:
          return "Restries";
        default:
          return "Classe";
      }
    }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorPortuguese::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 569 of file translator_pt.h.
    { return "Aviso"; }
trWriteList()
QCString TranslatorPortuguese::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 700 of file translator_pt.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" e ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_pt.h