Doxygen: ClassContext Class Reference
ClassContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
Gets the value for a field name.
virtual StringVector fields () const
Return the list of fields.
ClassContext (const ClassDef *)
virtual ~ClassContext ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()=default
Destroys the struct.
Static Public Member Functions
static TemplateStructIntfPtr alloc (const ClassDef *cd)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 196 of file context.h.
Constructor & Destructor Documentation
ClassContext()
ClassContext::ClassContext (const ClassDef * cd)
Definition at line 2484 of file context.cpp.
                                             : p(std::make_unique<Private>(cd))
{
}
~ClassContext()
ClassContext::~ClassContext () virtual
Definition at line 2488 of file context.cpp.
{
}
Member Function Documentation
alloc()
static TemplateStructIntfPtr ClassContext::alloc (const ClassDef * cd) inline static
Definition at line 199 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<ClassContext>(cd)); }
Referenced by ClassListContext::Private::addClasses(), MemberContext::Private::createAnonymousType(), MemberContext::Private::createCategory(), ClassContext::Private::createCategoryOf(), NestingNodeContext::Private::createClass(), InheritanceNodeContext::Private::createClass(), InheritedMemberInfoContext::Private::createClass(), MemberContext::Private::createClassDef(), ClassContext::Private::createClasses(), NamespaceContext::Private::createClasses(), FileContext::Private::createClasses(), ModuleContext::Private::createClasses(), ClassIndexContext::Private::createClasses(), NamespaceContext::Private::createInlineClasses(), FileContext::Private::createInlineClasses(), ModuleContext::Private::createInlineClasses(), and ClassContext::Private::createInnerClasses().
fields()
StringVector ClassContext::fields () const virtual
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 2497 of file context.cpp.
{
  return p->fields();
}
References p.
get()
TemplateVariant ClassContext::get (const QCString & name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 2492 of file context.cpp.
{
  return p->get(n);
}
References p.
Member Data Documentation
p
std::unique_ptr<Private> ClassContext::p private
Definition at line 211 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/context.h
/home/runner/work/doxygen/doxygen/src/context.cpp