Doxygen: DotLegendGraph Class Reference
DotLegendGraph Class Reference
Representation of a legend explaining the meaning of boxes, arrows, and colors.
#include <src/dotlegendgraph.h>
Public Member Functions
void writeGraph (const QCString &path)
Public Member Functions inherited from DotGraph
DotGraph ()
virtual ~DotGraph ()=default
Private Member Functions
QCString getBaseName () const override
void computeTheGraph () override
QCString getMapLabel () const override
Additional Inherited Members
Protected Member Functions inherited from DotGraph
int getNextNodeNumber ()
returns the node number.
int getNextEdgeNumber ()
returns the edge number.
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
virtual QCString absMapName () const
virtual QCString getImgAltText () const
QCString absBaseName () const
QCString absDotName () const
QCString imgName () const
QCString absImgName () const
QCString relImgName () const
Static Protected Member Functions inherited from DotGraph
static void writeGraphHeader (TextStream &t, const QCString &title=QCString())
static void writeGraphFooter (TextStream &t)
static void computeGraph (DotNode *root, GraphType gt, GraphOutputFormat format, const QCString &rank, bool renderParents, bool backArrows, const QCString &title, QCString &graphStr)
Protected Attributes inherited from DotGraph
GraphOutputFormat m_graphFormat = GraphOutputFormat::BITMAP
EmbeddedOutputFormat m_textFormat = EmbeddedOutputFormat::Html
Dir m_dir
QCString m_fileName
QCString m_relPath
bool m_generateImageMap = false
int m_graphId = 0
QCString m_absPath
QCString m_baseName
QCString m_theGraph
bool m_regenerate = false
bool m_doNotAddImageToIndex = false
bool m_noDivTag = false
bool m_zoomable = true
bool m_urlOnly = false
Detailed Description
Representation of a legend explaining the meaning of boxes, arrows, and colors.
Definition at line 22 of file dotlegendgraph.h.
Member Function Documentation
computeTheGraph()
void DotLegendGraph::computeTheGraph () override private virtual
Implements DotGraph.
Definition at line 45 of file dotlegendgraph.cpp.
{
  TextStream md5stream;
  writeGraphHeader(md5stream,theTranslator->trLegendTitle());
  DotNode{this,"Inherited", "", "", TRUE}.setNodeId(9).writeBox(md5stream, GraphType::CallGraph, GraphOutputFormat::BITMAP, false);
  md5stream << "  Node10 -> Node9 [dir=\"back\",color=\"steelblue1\",style=\"solid\" tooltip=\" \"];\n";
  DotNode{this,"PublicBase", "", DotNode::placeholderUrl}.setNodeId(10).markHasDocumentation().writeBox(md5stream, GraphType::CallGraph, GraphOutputFormat::BITMAP, false);
  md5stream << "  Node11 -> Node10 [dir=\"back\",color=\"steelblue1\",style=\"solid\" tooltip=\" \"];\n";
  DotNode{this,"Truncated", "", DotNode::placeholderUrl}.setNodeId(11).markAsTruncated().markHasDocumentation().writeBox(md5stream, GraphType::CallGraph, GraphOutputFormat::BITMAP, true);
  md5stream << "  Node13 -> Node9 [dir=\"back\",color=\"darkgreen\",style=\"solid\" tooltip=\" \"];\n";
  md5stream << "  Node13 [label=\"ProtectedBase\",color=\"gray40\",fillcolor=\"white\",style=\"filled\" tooltip=\" \"];\n";
  md5stream << "  Node14 -> Node9 [dir=\"back\",color=\"firebrick4\",style=\"solid\" tooltip=\" \"];\n";
  md5stream << "  Node14 [label=\"PrivateBase\",color=\"gray40\",fillcolor=\"white\",style=\"filled\" tooltip=\" \"];\n";
  md5stream << "  Node15 -> Node9 [dir=\"back\",color=\"steelblue1\",style=\"solid\" tooltip=\" \"];\n";
  DotNode{this,"Undocumented", "", ""}.setNodeId(15).writeBox(md5stream, GraphType::CallGraph, GraphOutputFormat::BITMAP, false);
  md5stream << "  Node16 -> Node9 [dir=\"back\",color=\"steelblue1\",style=\"solid\" tooltip=\" \"];\n";
  md5stream << "  Node16 [label=\"Templ\\< int \\>\",color=\"gray40\",fillcolor=\"white\",style=\"filled\" tooltip=\" \"];\n";
  md5stream << "  Node17 -> Node16 [dir=\"back\",color=\"orange\",style=\"dashed\",label=\"< int >\",fontcolor=\"grey\" tooltip=\" \"];\n";
  md5stream << "  Node17 [label=\"Templ\\< T \\>\",color=\"gray40\",fillcolor=\"white\",style=\"filled\" tooltip=\" \"];\n";
  md5stream << "  Node18 -> Node9 [dir=\"back\",color=\"darkorchid3\",style=\"dashed\",label=\"m_usedClass\",fontcolor=\"grey\" tooltip=\" \"];\n";
  md5stream << "  Node18 [label=\"Used\",color=\"gray40\",fillcolor=\"white\",style=\"filled\" tooltip=\" \"];\n";
  writeGraphFooter(md5stream);
  m_theGraph = md5stream.str();
}
References BITMAP, CallGraph, DotGraph::DotNode, DotGraph::m_theGraph, DotNode::placeholderUrl, TextStream::str(), theTranslator, Translator::trLegendTitle(), TRUE, DotGraph::writeGraphFooter(), and DotGraph::writeGraphHeader().
getBaseName()
QCString DotLegendGraph::getBaseName () const override private virtual
Implements DotGraph.
Definition at line 40 of file dotlegendgraph.cpp.
{
  return "graph_legend";
}
getMapLabel()
QCString DotLegendGraph::getMapLabel () const override private virtual
Implements DotGraph.
Definition at line 71 of file dotlegendgraph.cpp.
{
  return "";
}
writeGraph()
void DotLegendGraph::writeGraph (const QCString & path)
Definition at line 27 of file dotlegendgraph.cpp.
{
  TextStream ts;
  DotGraph::writeGraph(ts, GraphOutputFormat::BITMAP, EmbeddedOutputFormat::Html, path, "", "", FALSE, 0);
  if (getDotImageExtension()=="svg")
  {
    DotManager::instance()->
      createFilePatcher(absBaseName()+Config_getString(HTML_FILE_EXTENSION))->
      addSVGObject("graph_legend", absImgName(),QCString());
  }
}
References DotGraph::absBaseName(), DotGraph::absImgName(), BITMAP, Config_getString, FALSE, getDotImageExtension(), Html, DotManager::instance(), and DotGraph::writeGraph().
Referenced by writeGraphInfo().
The documentation for this class was generated from the following files:
src/dotlegendgraph.h
src/dotlegendgraph.cpp