Doxygen: src/pagedef.cpp File Reference
pagedef.cpp File Reference
#include "pagedef.h"
#include "groupdef.h"
#include "docparser.h"
#include "config.h"
#include "util.h"
#include "outputlist.h"
#include "doxygen.h"
#include "language.h"
#include "namespacedef.h"
#include "reflist.h"
#include "definitionimpl.h"
#include "indexlist.h"
Classes
class PageDefImpl
Functions
std::unique_ptr< PageDef > createPageDef (const QCString &f, int l, const QCString &n, const QCString &d, const QCString &t)
PageDef * toPageDef (Definition *d)
const PageDef * toPageDef (const Definition *d)
Function Documentation
createPageDef()
std::unique_ptr< PageDef > createPageDef (const QCString & f, int l, const QCString & n, const QCString & d, const QCString & t)
Definition at line 79 of file pagedef.cpp.
{
  return std::make_unique<PageDefImpl>(f,l,n,d,t);
}
Referenced by addRelatedPage(), buildExampleList(), and findMainPage().
toPageDef() [1/2]
const PageDef * toPageDef (const Definition * d)
Definition at line 480 of file pagedef.cpp.
{
  if (d==nullptr) return nullptr;
  if (d && typeid(*d)==typeid(PageDefImpl))
  {
    return static_cast<const PageDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
toPageDef() [2/2]
PageDef * toPageDef (Definition * d)
Definition at line 467 of file pagedef.cpp.
{
  if (d==nullptr) return nullptr;
  if (d && typeid(*d)==typeid(PageDefImpl))
  {
    return static_cast<PageDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
Referenced by PageDefImpl::addInnerCompound(), SearchTerm::makeTitle(), DefinitionImpl::navigationPathAsString(), DefinitionImpl::pathFragment(), SearchIndex::setCurrentDoc(), SearchIndexExternal::setCurrentDoc(), validatingParseDoc(), and writeJavasScriptSearchDataPage().