Doxygen: DotGroupCollaboration Class Reference
DotGroupCollaboration Class Reference
Representation of a group collaboration graph.
#include <src/dotgroupcollaboration.h>
Classes
struct Edge
struct Link
Public Member Functions
DotGroupCollaboration (const GroupDef *gd)
~DotGroupCollaboration () override
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
bool isTrivial () const
bool isTooBig () const
int numNodes () const
Public Member Functions inherited from DotGraph
DotGraph ()
virtual ~DotGraph ()=default
Protected Member Functions
QCString getBaseName () const override
QCString getMapLabel () const override
void computeTheGraph () override
Protected Member Functions inherited from DotGraph
int getNextNodeNumber ()
returns the node number.
int getNextEdgeNumber ()
returns the edge number.
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
virtual QCString absMapName () const
virtual QCString getImgAltText () const
QCString absBaseName () const
QCString absDotName () const
QCString imgName () const
QCString absImgName () const
QCString relImgName () const
Private Types
enum EdgeType {
tmember = 0 , tclass , tnamespace , tfile ,
tpages , tdir , thierarchy
}
Private Member Functions
void buildGraph (const GroupDef *gd)
void addCollaborationMember (const Definition *def, QCString &url, EdgeType eType)
void addMemberList (class MemberList *ml)
void writeGraphHeader (TextStream &t, const QCString &title) const
Edge * addEdge (DotNode *_pNStart, DotNode *_pNEnd, EdgeType _eType, const QCString &_label, const QCString &_url)
Private Attributes
DotNode * m_rootNode
DotNodeMap m_usedNodes
QCString m_diskName
std::vector< std::unique_ptr< Edge > > m_edges
Additional Inherited Members
Static Protected Member Functions inherited from DotGraph
static void writeGraphHeader (TextStream &t, const QCString &title=QCString())
static void writeGraphFooter (TextStream &t)
static void computeGraph (DotNode *root, GraphType gt, GraphOutputFormat format, const QCString &rank, bool renderParents, bool backArrows, const QCString &title, QCString &graphStr)
Protected Attributes inherited from DotGraph
GraphOutputFormat m_graphFormat = GraphOutputFormat::BITMAP
EmbeddedOutputFormat m_textFormat = EmbeddedOutputFormat::Html
Dir m_dir
QCString m_fileName
QCString m_relPath
bool m_generateImageMap = false
int m_graphId = 0
QCString m_absPath
QCString m_baseName
QCString m_theGraph
bool m_regenerate = false
bool m_doNotAddImageToIndex = false
bool m_noDivTag = false
bool m_zoomable = true
bool m_urlOnly = false
Detailed Description
Representation of a group collaboration graph.
Definition at line 28 of file dotgroupcollaboration.h.
Member Enumeration Documentation
EdgeType
enum DotGroupCollaboration::EdgeType private
Enumerator
tmember
tclass
tnamespace
tfile
tpages
tdir
thierarchy
Definition at line 48 of file dotgroupcollaboration.h.
    {
      tmember = 0,
      tclass,
      tnamespace,
      tfile,
      tpages,
      tdir,
      thierarchy
    };
Constructor & Destructor Documentation
DotGroupCollaboration()
DotGroupCollaboration::DotGroupCollaboration (const GroupDef * gd)
Definition at line 25 of file dotgroupcollaboration.cpp.
{
  QCString tmp_url = gd->getReference()+"$"+gd->getOutputFileBase();
  QCString tooltip = gd->briefDescriptionAsTooltip();
  m_rootNode = new DotNode(this, gd->groupTitle(), tooltip, tmp_url, TRUE );
  m_rootNode->markAsVisible();
  m_usedNodes.emplace(gd->name().str(), m_rootNode);
  m_diskName = gd->getOutputFileBase();
  buildGraph( gd );
}
References Definition::briefDescriptionAsTooltip(), buildGraph(), DotGraph::DotNode, Definition::getOutputFileBase(), Definition::getReference(), GroupDef::groupTitle(), m_diskName, m_rootNode, m_usedNodes, Definition::name(), QCString::str(), and TRUE.
~DotGroupCollaboration()
DotGroupCollaboration::~DotGroupCollaboration () override
Definition at line 38 of file dotgroupcollaboration.cpp.
{
  // delete all created Nodes saved in m_usedNodes map
  for (const auto &[name,node] : m_usedNodes)
  {
    delete node;
  }
}
References m_usedNodes.
Member Function Documentation
addCollaborationMember()
void DotGroupCollaboration::addCollaborationMember (const Definition * def, QCString & url, EdgeType eType) private
Definition at line 186 of file dotgroupcollaboration.cpp.
{
  // Create group nodes
  QCString tmp_str;
  for (const auto &d : def->partOfGroups())
  {
    auto it = m_usedNodes.find(d->name().str());
    DotNode* nnode = it!=m_usedNodes.end() ? it->second : nullptr;
    if ( nnode != m_rootNode )
    {
      if ( nnode==nullptr )
      { // add node
        tmp_str = d->getReference()+"$"+d->getOutputFileBase();
        QCString tooltip = d->briefDescriptionAsTooltip();
        nnode = new DotNode(this, d->groupTitle(), tooltip, tmp_str );
        nnode->markAsVisible();
        m_usedNodes.emplace(d->name().str(), nnode);
      }
      tmp_str = def->qualifiedName();
      addEdge( m_rootNode, nnode, eType, tmp_str, url );
    }
  }
}
References addEdge(), DotGraph::DotNode, m_rootNode, m_usedNodes, DotNode::markAsVisible(), Definition::partOfGroups(), and Definition::qualifiedName().
Referenced by addMemberList(), and buildGraph().
addEdge()
DotGroupCollaboration::Edge * DotGroupCollaboration::addEdge (DotNode * _pNStart, DotNode * _pNEnd, EdgeType _eType, const QCString & _label, const QCString & _url) private
Definition at line 162 of file dotgroupcollaboration.cpp.
{
  // search a existing link.
  auto it = std::find_if(m_edges.begin(),m_edges.end(),
      [&_pNStart,&_pNEnd,&_eType](const auto &edge)
      { return edge->pNStart==_pNStart && edge->pNEnd==_pNEnd && edge->eType==_eType; });
  if (it==m_edges.end()) // new link
  {
    m_edges.emplace_back(std::make_unique<Edge>(_pNStart,_pNEnd,_eType));
    it = m_edges.end()-1;
  }
  if (!_label.isEmpty()) // add label
  {
    (*it)->links.emplace_back(_label,_url);
  }
  // return found or added edge
  return (*it).get();
}
References DotGraph::DotNode, QCString::isEmpty(), and m_edges.
Referenced by addCollaborationMember(), and buildGraph().
addMemberList()
void DotGroupCollaboration::addMemberList (class MemberList * ml) private
Definition at line 151 of file dotgroupcollaboration.cpp.
{
  QCString url;
  if ( ml==nullptr || ml->empty() ) return;
  for (const auto &def : *ml)
  {
    makeURL(def,url);
    addCollaborationMember( def, url, DotGroupCollaboration::tmember );
  }
}
References addCollaborationMember(), MemberVector::empty(), makeURL(), and tmember.
Referenced by buildGraph().
buildGraph()
void DotGroupCollaboration::buildGraph (const GroupDef * gd) private
Definition at line 58 of file dotgroupcollaboration.cpp.
{
  QCString url;
  //===========================
  // hierarchy.
  // Write parents
  for (const auto &d : gd->partOfGroups())
  {
    DotNode *nnode = nullptr;
    auto it = m_usedNodes.find(d->name().str());
    if ( it==m_usedNodes.end())
    { // add node
      makeURL(d,url);
      QCString tooltip = d->briefDescriptionAsTooltip();
      nnode = new DotNode(this, d->groupTitle(), tooltip, url );
      nnode->markAsVisible();
      m_usedNodes.emplace(d->name().str(), nnode);
    }
    else
    {
      nnode = it->second;
    }
    url = "";
    addEdge( nnode, m_rootNode, DotGroupCollaboration::thierarchy, url, url );
  }
  // Add subgroups
  for (const auto &def : gd->getSubGroups())
  {
    DotNode *nnode = nullptr;
    auto it = m_usedNodes.find(def->name().str());
    if ( it==m_usedNodes.end())
    { // add node
      makeURL(def,url);
      QCString tooltip = def->briefDescriptionAsTooltip();
      nnode = new DotNode(this, def->groupTitle(), tooltip, url );
      nnode->markAsVisible();
      m_usedNodes.emplace(def->name().str(), nnode);
    }
    else
    {
      nnode = it->second;
    }
    url = "";
    addEdge( m_rootNode, nnode, DotGroupCollaboration::thierarchy, url, url );
  }
  //=======================
  // Write collaboration
  // Add members
  addMemberList( gd->getMemberList(MemberListType::AllMembersList()) );
  // Add classes
  for (const auto &def : gd->getClasses())
  {
    makeURL(def,url);
    addCollaborationMember( def, url, DotGroupCollaboration::tclass );
  }
  // Add namespaces
  for (const auto &def : gd->getNamespaces())
  {
    makeURL(def,url);
    addCollaborationMember( def, url, DotGroupCollaboration::tnamespace );
  }
  // Add files
  for (const auto &def : gd->getFiles())
  {
    makeURL(def,url);
    addCollaborationMember( def, url, DotGroupCollaboration::tfile );
  }
  // Add pages
  for (const auto &def : gd->getPages())
  {
    makeURL(def,url);
    addCollaborationMember( def, url, DotGroupCollaboration::tpages );
  }
  // Add directories
  if ( !gd->getDirs().empty() )
  {
    for(const auto def : gd->getDirs())
    {
      makeURL(def,url);
      addCollaborationMember( def, url, DotGroupCollaboration::tdir );
    }
  }
}
References addCollaborationMember(), addEdge(), addMemberList(), DotGraph::DotNode, GroupDef::getClasses(), GroupDef::getDirs(), GroupDef::getFiles(), GroupDef::getMemberList(), GroupDef::getNamespaces(), GroupDef::getPages(), GroupDef::getSubGroups(), m_rootNode, m_usedNodes, makeURL(), DotNode::markAsVisible(), Definition::partOfGroups(), tclass, tdir, tfile, thierarchy, tnamespace, and tpages.
Referenced by DotGroupCollaboration().
computeTheGraph()
void DotGroupCollaboration::computeTheGraph () override protected virtual
Implements DotGraph.
Definition at line 216 of file dotgroupcollaboration.cpp.
{
  TextStream md5stream;
  writeGraphHeader(md5stream,m_rootNode->label());
  // clean write flags
  for (const auto &[name,node] : m_usedNodes)
  {
    node->clearWriteFlag();
  }
  // write other nodes.
  for (const auto &[name,node] : m_usedNodes)
  {
    node->write(md5stream,GraphType::Inheritance,m_graphFormat,TRUE,FALSE,FALSE);
  }
  // write edges
  for (const auto &edge : m_edges)
  {
    edge->write( md5stream );
  }
  writeGraphFooter(md5stream);
  m_theGraph = md5stream.str();
}
References FALSE, Inheritance, m_edges, DotGraph::m_graphFormat, m_rootNode, DotGraph::m_theGraph, m_usedNodes, TextStream::str(), TRUE, DotGraph::writeGraphFooter(), and writeGraphHeader().
getBaseName()
QCString DotGroupCollaboration::getBaseName () const override protected virtual
Implements DotGraph.
Definition at line 211 of file dotgroupcollaboration.cpp.
{
  return m_diskName;
}
References m_diskName.
getMapLabel()
QCString DotGroupCollaboration::getMapLabel () const override protected virtual
Implements DotGraph.
Definition at line 244 of file dotgroupcollaboration.cpp.
{
  return escapeCharsInString(m_baseName, FALSE);
}
References escapeCharsInString(), FALSE, and DotGraph::m_baseName.
isTooBig()
bool DotGroupCollaboration::isTooBig () const
Definition at line 324 of file dotgroupcollaboration.cpp.
{
  return numNodes()>=Config_getInt(DOT_GRAPH_MAX_NODES);
}
References Config_getInt, and numNodes().
Referenced by GroupDefImpl::writeGroupGraph().
isTrivial()
bool DotGroupCollaboration::isTrivial () const
Definition at line 319 of file dotgroupcollaboration.cpp.
{
  return m_usedNodes.size() <= 1;
}
References m_usedNodes.
Referenced by GroupDefImpl::writeGroupGraph().
numNodes()
int DotGroupCollaboration::numNodes () const
Definition at line 329 of file dotgroupcollaboration.cpp.
{
  return static_cast<int>(m_usedNodes.size());
}
References m_usedNodes.
Referenced by isTooBig(), and GroupDefImpl::writeGroupGraph().
writeGraph()
QCString DotGroupCollaboration::writeGraph (TextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1)
Definition at line 249 of file dotgroupcollaboration.cpp.
{
  m_doNotAddImageToIndex = textFormat!=EmbeddedOutputFormat::Html;
  return DotGraph::writeGraph(t, graphFormat, textFormat, path, fileName, relPath, generateImageMap, graphId);
}
References Html, DotGraph::m_doNotAddImageToIndex, and DotGraph::writeGraph().
Referenced by DocbookGenerator::endGroupCollaboration(), HtmlGenerator::endGroupCollaboration(), and LatexGenerator::endGroupCollaboration().
writeGraphHeader()
void DotGroupCollaboration::writeGraphHeader (TextStream & t, const QCString & title) const private
Definition at line 334 of file dotgroupcollaboration.cpp.
{
  DotGraph::writeGraphHeader(t, title);
  t << "  rankdir=LR;\n";
}
References DotGraph::writeGraphHeader().
Referenced by computeTheGraph().
Member Data Documentation
m_diskName
QCString DotGroupCollaboration::m_diskName private
Definition at line 88 of file dotgroupcollaboration.h.
Referenced by DotGroupCollaboration(), and getBaseName().
m_edges
std::vector< std::unique_ptr<Edge> > DotGroupCollaboration::m_edges private
Definition at line 89 of file dotgroupcollaboration.h.
Referenced by addEdge(), and computeTheGraph().
m_rootNode
DotNode* DotGroupCollaboration::m_rootNode private
Definition at line 86 of file dotgroupcollaboration.h.
Referenced by addCollaborationMember(), buildGraph(), computeTheGraph(), and DotGroupCollaboration().
m_usedNodes
DotNodeMap DotGroupCollaboration::m_usedNodes private
Definition at line 87 of file dotgroupcollaboration.h.
Referenced by addCollaborationMember(), buildGraph(), computeTheGraph(), DotGroupCollaboration(), isTrivial(), numNodes(), and ~DotGroupCollaboration().
The documentation for this class was generated from the following files:
src/dotgroupcollaboration.h
src/dotgroupcollaboration.cpp