Doxygen: TemplateStruct Class Reference
TemplateStruct Class Reference
Default implementation of a context value of type struct.
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
Gets the value for a field name.
virtual StringVector fields () const
Return the list of fields.
virtual void set (const QCString &name, const TemplateVariant &v)
Sets the value the field of a struct.
virtual void remove (const QCString &name)
Removes the field from the struct.
TemplateStruct ()=default
Creates a struct.
virtual ~TemplateStruct ()=default
Destroys the struct.
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()=default
Destroys the struct.
Static Public Member Functions
static TemplateStructPtr alloc ()
Creates an instance and returns a shared pointer to it.
Private Attributes
std::unordered_map< std::string, TemplateVariant > m_fields
Detailed Description
Default implementation of a context value of type struct.
Definition at line 134 of file template.cpp.
Constructor & Destructor Documentation
TemplateStruct()
TemplateStruct::TemplateStruct () default
Creates a struct.
~TemplateStruct()
virtual TemplateStruct::~TemplateStruct () virtual default
Destroys the struct.
Member Function Documentation
alloc()
TemplateStructPtr TemplateStruct::alloc () static
Creates an instance and returns a shared pointer to it.
Definition at line 202 of file template.cpp.
{
  return std::make_shared<TemplateStruct>();
}
Referenced by TemplateContextImpl::addIndexEntry(), FilterAlphaIndex::apply(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeBlock::render(), and TemplateNodeMarkers::render().
fields()
StringVector TemplateStruct::fields () const virtual
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 191 of file template.cpp.
{
  StringVector result;
  for (const auto &[name,variant] : m_fields)
  {
    result.push_back(name);
  }
  std::sort(result.begin(),result.end());
  return result;
}
References m_fields.
get()
TemplateVariant TemplateStruct::get (const QCString & name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 185 of file template.cpp.
{
  auto it = m_fields.find(name.str());
  return it!=m_fields.end() ? it->second : TemplateVariant();
}
References m_fields, and QCString::str().
remove()
void TemplateStruct::remove (const QCString & name) virtual
Removes the field from the struct.
Definition at line 176 of file template.cpp.
{
  auto it = m_fields.find(name.str());
  if (it!=m_fields.end())
  {
    m_fields.erase(it);
  }
}
References m_fields, and QCString::str().
set()
void TemplateStruct::set (const QCString & name, const TemplateVariant & v) virtual
Sets the value the field of a struct.
Parameters
[in] name The name of the field.
[in] v The value to set.
Definition at line 163 of file template.cpp.
{
  auto it = m_fields.find(name.str());
  if (it!=m_fields.end()) // change existing field
  {
    it->second = v;
  }
  else // insert new field
  {
    m_fields.insert(std::make_pair(name.str(),v));
  }
}
References m_fields, and QCString::str().
Member Data Documentation
m_fields
std::unordered_map<std::string,TemplateVariant> TemplateStruct::m_fields private
Definition at line 160 of file template.cpp.
Referenced by fields(), get(), remove(), and set().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/template.cpp