Doxygen: src/rtfgen.cpp File Reference
rtfgen.cpp File Reference
#include <mutex>
#include <stdlib.h>
#include <algorithm>
#include <unordered_map>
#include "rtfgen.h"
#include "config.h"
#include "message.h"
#include "doxygen.h"
#include "util.h"
#include "diagram.h"
#include "language.h"
#include "dot.h"
#include "dotcallgraph.h"
#include "dotclassgraph.h"
#include "dotdirdeps.h"
#include "dotincldepgraph.h"
#include "version.h"
#include "pagedef.h"
#include "rtfstyle.h"
#include "rtfdocvisitor.h"
#include "docparser.h"
#include "dirdef.h"
#include "vhdldocgen.h"
#include "portable.h"
#include "groupdef.h"
#include "classlist.h"
#include "filename.h"
#include "namespacedef.h"
#include "dir.h"
#include "utf8.h"
#include "debug.h"
#include "datetime.h"
#include "outputlist.h"
#include "moduledef.h"
Macros
#define DBG_RTF(x)
Functions
static QCString dateToRTFDateString ()
static QCString docifyToString (const QCString &str)
static QCString makeIndexName (const QCString &s, int i)
static QCString objectLinkToString (const QCString &ref, const QCString &f, const QCString &anchor, const QCString &text)
bool isLeadBytes (int c)
static void encodeForOutput (TextStream &t, const QCString &s)
static bool preProcessFile (Dir &d, const QCString &infName, TextStream &t, bool bIncludeHeader=true, bool removeFile=true)
VERY brittle routine inline RTF's included by other RTF's.
void testRTFOutput (const QCString &name)
Tests the integrity of the result by counting brackets.
QCString rtfFormatBmkStr (const QCString &name)
Variables
static StringSet removeSet
static std::mutex g_rtfFormatMutex
static std::unordered_map< std::string, std::string > g_tagMap
static QCString g_nextTag ("AAAAAAAAAA")
Macro Definition Documentation
DBG_RTF
#define DBG_RTF (x)
Definition at line 55 of file rtfgen.cpp.
Referenced by preProcessFile().
Function Documentation
dateToRTFDateString()
static QCString dateToRTFDateString () static
Definition at line 59 of file rtfgen.cpp.
{
  auto tm = getCurrentDateTime();
  QCString result;
  switch (Config_getEnum(TIMESTAMP))
  {
    case TIMESTAMP_t::YES:
    case TIMESTAMP_t::DATETIME:
      result.sprintf("\\yr%d\\mo%d\\dy%d\\hr%d\\min%d\\sec%d",
          tm.tm_year+1900, tm.tm_mon+1, tm.tm_mday,
          tm.tm_hour, tm.tm_min, tm.tm_sec);
      break;
    case TIMESTAMP_t::DATE:
      result.sprintf("\\yr%d\\mo%d\\dy%d",
          tm.tm_year+1900, tm.tm_mon+1, tm.tm_mday);
      break;
    case TIMESTAMP_t::NO:
      return "";
  }
  return "{\\creatim " + result + "}\n";
}
References Config_getEnum, getCurrentDateTime(), and QCString::sprintf().
Referenced by RTFGenerator::endIndexSection().
docifyToString()
static QCString docifyToString (const QCString & str) static
Definition at line 81 of file rtfgen.cpp.
{
  QCString result;
  result.reserve(str.length());
  if (!str.isEmpty())
  {
    const char *p=str.data();
    while (*p)
    {
      char c=*p++;
      switch (c)
      {
        case '{':  result += "\\{";            break;
        case '}':  result += "\\}";            break;
        case '\\': result += "\\\\";           break;
        default:   result += c;                break;
      }
    }
  }
  return result;
}
References QCString::data(), QCString::isEmpty(), QCString::length(), and QCString::reserve().
Referenced by objectLinkToString().
encodeForOutput()
static void encodeForOutput (TextStream & t, const QCString & s) static
Definition at line 2181 of file rtfgen.cpp.
{
  if (s==nullptr) return;
  QCString encoding;
  bool converted=FALSE;
  size_t l = s.length();
  static std::vector<char> enc;
  if (l*4>enc.size()) enc.resize(l*4); // worst case
  encoding.sprintf("CP%s",qPrint(theTranslator->trRTFansicp()));
  if (!encoding.isEmpty())
  {
    // convert from UTF-8 back to the output encoding
    void *cd = portable_iconv_open(encoding.data(),"UTF-8");
    if (cd!=reinterpret_cast<void *>(-1))
    {
      size_t iLeft=l;
      size_t oLeft=enc.size();
      const char *inputPtr = s.data();
      char *outputPtr = &enc[0];
      if (!portable_iconv(cd, &inputPtr, &iLeft, &outputPtr, &oLeft))
      {
        enc.resize(enc.size()-oLeft);
        converted=TRUE;
      }
      portable_iconv_close(cd);
    }
  }
  if (!converted) // if we did not convert anything, copy as is.
  {
    memcpy(enc.data(),s.data(),l);
    enc.resize(l);
  }
  bool multiByte = FALSE;
  for (size_t i=0;i<enc.size();i++)
  {
    uint8_t c = static_cast<uint8_t>(enc.at(i));
    if (c>=0x80 || multiByte)
    {
      char esc[10];
      qsnprintf(esc,10,"\\'%X",c);        // escape sequence for SBCS and DBCS(1st&2nd bytes).
      t << esc;
      if (!multiByte)
      {
        multiByte = isLeadBytes(c);  // It may be DBCS Codepages.
      }
      else
      {
        multiByte = FALSE;           // end of Double Bytes Character.
      }
    }
    else
    {
      t << c;
    }
  }
}
References QCString::data(), FALSE, QCString::isEmpty(), isLeadBytes(), QCString::length(), portable_iconv(), portable_iconv_close(), portable_iconv_open(), qPrint(), qsnprintf, QCString::sprintf(), theTranslator, and TRUE.
Referenced by preProcessFile().
isLeadBytes()
bool isLeadBytes (int c)
Definition at line 2153 of file rtfgen.cpp.
{
  bool result=false;           // for SBCS Codepages (cp1252,1251 etc...);
  QCString codePage = theTranslator->trRTFansicp();
  if (codePage == "932")       // cp932 (Japanese Shift-JIS)
  {
    result = (0x81<=c && c<=0x9f) || (0xe0<=c && c<=0xfc);
  }
  else if (codePage == "936")  // cp936 (Simplified Chinese GBK)
  {
    result = 0x81<=c && c<=0xFE;
  }
  else if (codePage == "949")  // cp949 (Korean)
  {
    result = 0x81<=c && c<=0xFE;
  }
  else if (codePage == "950")  // cp950 (Traditional Chinese Big5)
  {
    result = 0x81<=c && c<=0xFE;
  }
  return result;
}
References theTranslator.
Referenced by encodeForOutput().
makeIndexName()
static QCString makeIndexName (const QCString & s, int i) static
Definition at line 104 of file rtfgen.cpp.
{
  QCString result=s;
  result+=static_cast<char>(i+'0');
  return result;
}
Referenced by RTFGenerator::rtf_BList_DepthStyle(), RTFGenerator::rtf_CList_DepthStyle(), RTFCodeGenerator::rtf_Code_DepthStyle(), RTFGenerator::rtf_DList_DepthStyle(), RTFGenerator::rtf_EList_DepthStyle(), and RTFGenerator::rtf_LCList_DepthStyle().
objectLinkToString()
static QCString objectLinkToString (const QCString & ref, const QCString & f, const QCString & anchor, const QCString & text) static
Definition at line 1545 of file rtfgen.cpp.
{
  QCString result;
  if (ref.isEmpty() && Config_getBool(RTF_HYPERLINKS))
  {
    QCString refName;
    if (!f.isEmpty())
    {
      refName+=stripPath(f);
    }
    if (!anchor.isEmpty())
    {
      refName+='_';
      refName+=anchor;
    }
    result += "{\\field {\\*\\fldinst { HYPERLINK  \\\\l \"";
    result += rtfFormatBmkStr(refName);
    result += "\" }{}";
    result += "}{\\fldrslt {\\cs37\\ul\\cf2 ";
    result += docifyToString(text);
    result += "}}}\n";
  }
  else
  {
    result += "{\\b ";
    result += docifyToString(text);
    result += "}";
  }
  return result;
}
References Config_getBool, docifyToString(), QCString::isEmpty(), rtfFormatBmkStr(), and stripPath().
preProcessFile()
static bool preProcessFile (Dir & d, const QCString & infName, TextStream & t, bool bIncludeHeader = true, bool removeFile = true) static
VERY brittle routine inline RTF's included by other RTF's.
it is recursive and ugly.
Definition at line 2245 of file rtfgen.cpp.
{
  static bool rtfDebug = Debug::isFlagSet(Debug::Rtf);
  std::ifstream f = Portable::openInputStream(infName);
  if (!f.is_open())
  {
    err("problems opening rtf file '%s' for reading\n",infName.data());
    return false;
  }
  const int maxLineLength = 10240;
  static QCString lineBuf(maxLineLength, QCString::ExplicitSize);
  // scan until find end of header
  // this is EXTREEEEEEEMLY brittle.  It works on OUR rtf
  // files because the first line before the body
  // ALWAYS contains "{\comment begin body}"
  std::string line;
  while (getline(f,line))
  {
    line+='\n';
    if (line.find("\\comment begin body")!=std::string::npos) break;
    if (bIncludeHeader) encodeForOutput(t,line.c_str());
  }
  std::string prevLine;
  bool first=true;
  while (getline(f,line))
  {
    line+='\n';
    size_t pos=prevLine.find("INCLUDETEXT \"");
    if (pos!=std::string::npos)
    {
      size_t startNamePos  = prevLine.find('"',pos)+1;
      size_t endNamePos    = prevLine.find('"',startNamePos);
      std::string fileName = prevLine.substr(startNamePos,endNamePos-startNamePos);
      DBG_RTF(t << "{\\comment begin include " << fileName << "}\n")
      if (!preProcessFile(d,fileName.c_str(),t,FALSE)) return FALSE;
      DBG_RTF(t << "{\\comment end include " << fileName << "}\n")
    }
    else if (!first) // no INCLUDETEXT on this line
    {
      encodeForOutput(t,prevLine.c_str());
    }
    prevLine = line;
    first=false;
  }
  if (!bIncludeHeader) // skip final '}' in case we don't include headers
  {
    size_t pos = line.rfind('}');
    if (pos==std::string::npos)
    {
      err("Strange, the last char was not a '}'\n");
      pos = line.length();
    }
    encodeForOutput(t,line.substr(0,pos).c_str());
  }
  else
  {
    encodeForOutput(t,line.c_str());
  }
  f.close();
  // remove temporary file
  if (!rtfDebug && removeFile) removeSet.insert(FileInfo(d.filePath(infName.str())).absFilePath());
  return TRUE;
}
References FileInfo::absFilePath(), QCString::data(), DBG_RTF, encodeForOutput(), err, QCString::ExplicitSize, FALSE, Dir::filePath(), Debug::isFlagSet(), Portable::openInputStream(), preProcessFile(), removeSet, Debug::Rtf, QCString::str(), and TRUE.
Referenced by preProcessFile(), and RTFGenerator::preProcessFileInplace().
rtfFormatBmkStr()
QCString rtfFormatBmkStr (const QCString & name)
Definition at line 2869 of file rtfgen.cpp.
{
  std::lock_guard<std::mutex> lock(g_rtfFormatMutex);
  // To overcome the 40-character tag limitation, we
  // substitute a short arbitrary string for the name
  // supplied, and keep track of the correspondence
  // between names and strings.
  auto it = g_tagMap.find(name.str());
  if (it!=g_tagMap.end()) // already known
  {
    return QCString(it->second);
  }
  QCString tag = g_nextTag;
  auto result = g_tagMap.emplace(name.str(), g_nextTag.str());
  if (result.second) // new item was added
  {
    // increment the next tag.
    char* nxtTag = g_nextTag.rawData() + g_nextTag.length() - 1;
    for ( unsigned int i = 0; i < g_nextTag.length(); ++i, --nxtTag )
    {
      if ( ( ++(*nxtTag) ) > 'Z' )
      {
        *nxtTag = 'A';
      }
      else
      {
        // Since there was no carry, we can stop now
        break;
      }
    }
  }
  Debug::print(Debug::Rtf,0,"Name = %s RTF_tag = %s\n",qPrint(name),qPrint(tag));
  return tag;
}
References g_nextTag, g_rtfFormatMutex, g_tagMap, Rtf_Style_Default::name, Debug::print(), qPrint(), and Debug::Rtf.
Referenced by RTFGenerator::endDoxyAnchor(), objectLinkToString(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::startLink(), RTFGenerator::startTextLink(), RTFGenerator::writeAnchor(), RTFCodeGenerator::writeCodeLink(), RTFCodeGenerator::writeLineNumber(), RTFGenerator::writeRTFReference(), and RTFGenerator::writeStartAnnoItem().
testRTFOutput()
void testRTFOutput (const QCString & name)
Tests the integrity of the result by counting brackets.
Definition at line 2412 of file rtfgen.cpp.
{
  int bcount=0;
  int line=1;
  int c=0;
  std::ifstream f = Portable::openInputStream(name);
  if (f.is_open())
  {
    while ((c=f.get())!=-1)
    {
      if (c=='\\') // escape char
      {
        c=f.get();
        if (c==-1) break;
      }
      else if (c=='{') // open bracket
      {
        bcount++;
      }
      else if (c=='}') // close bracket
      {
        bcount--;
        if (bcount<0)
        {
          goto err;
          break;
        }
      }
      else if (c=='\n') // newline
      {
        line++;
      }
    }
  }
  if (bcount==0) return; // file is OK.
err:
  err("RTF integrity test failed at line %d of %s due to a bracket mismatch.\n"
      "       Please try to create a small code example that produces this error \n"
      "       and send that to doxygen@gmail.com.\n",line,qPrint(name));
}
References err, Rtf_Style_Default::name, Portable::openInputStream(), and qPrint().
Referenced by RTFGenerator::preProcessFileInplace().
Variable Documentation
g_nextTag
QCString g_nextTag("AAAAAAAAAA") ("AAAAAAAAAA") static
Referenced by rtfFormatBmkStr().
g_rtfFormatMutex
std::mutex g_rtfFormatMutex static
Definition at line 2865 of file rtfgen.cpp.
Referenced by rtfFormatBmkStr().
g_tagMap
std::unordered_map<std::string,std::string> g_tagMap static
Definition at line 2866 of file rtfgen.cpp.
Referenced by rtfFormatBmkStr().
removeSet
StringSet removeSet static
Definition at line 57 of file rtfgen.cpp.
Referenced by preProcessFile(), and RTFGenerator::preProcessFileInplace().