Doxygen: HtmlGenerator Class Reference
HtmlGenerator Class Reference
Generator for HTML output.
#include <src/htmlgen.h>
Public Member Functions
HtmlGenerator ()
HtmlGenerator (const HtmlGenerator &)
HtmlGenerator & operator= (const HtmlGenerator &)
HtmlGenerator (HtmlGenerator &&)=delete
HtmlGenerator & operator= (HtmlGenerator &&)=delete
~HtmlGenerator ()
void clearBuffer ()
OutputType type () const override
std::unique_ptr< OutputGenIntf > clone () override
void addCodeGen (OutputCodeList &list) override
void cleanup () override
void writeDoc (const IDocNodeAST *node, const Definition *, const MemberDef *, int id) override
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id, int hierarchyLevel) override
void endFile () override
void writeFooter (const QCString &navPath) override
void writeSearchInfo () override
void startIndexSection (IndexSection) override
void endIndexSection (IndexSection) override
void writePageLink (const QCString &, bool) override
void startProjectNumber () override
void endProjectNumber () override
void writeStyleInfo (int part) override
void startTitleHead (const QCString &) override
void endTitleHead (const QCString &, const QCString &) override
void startParagraph (const QCString &classDef) override
void endParagraph () override
void writeString (const QCString &text) override
void startIndexListItem () override
void endIndexListItem () override
void startIndexList () override
void endIndexList () override
void startIndexKey () override
void endIndexKey () override
void startIndexValue (bool) override
void endIndexValue (const QCString &, bool) override
void startItemList () override
void endItemList () override
void startIndexItem (const QCString &ref, const QCString &file) override
void endIndexItem (const QCString &ref, const QCString &file) override
void docify (const QCString &text) override
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name) override
void startTextLink (const QCString &file, const QCString &anchor) override
void endTextLink () override
void startTypewriter () override
void endTypewriter () override
void startGroupHeader (int) override
void endGroupHeader (int) override
void startItemListItem () override
void endItemListItem () override
void startMemberSections () override
void endMemberSections () override
void startHeaderSection () override
void endHeaderSection () override
void startMemberHeader (const QCString &, int) override
void endMemberHeader () override
void startMemberSubtitle () override
void endMemberSubtitle () override
void startMemberDocList () override
void endMemberDocList () override
void startMemberList () override
void endMemberList () override
void startInlineHeader () override
void endInlineHeader () override
void startAnonTypeScope (int) override
void endAnonTypeScope (int) override
void startMemberItem (const QCString &anchor, MemberItemType, const QCString &inheritId) override
void endMemberItem (MemberItemType) override
void startMemberTemplateParams () override
void endMemberTemplateParams (const QCString &anchor, const QCString &inheritId) override
void startCompoundTemplateParams () override
void endCompoundTemplateParams () override
void startMemberGroupHeader (bool) override
void endMemberGroupHeader () override
void startMemberGroupDocs () override
void endMemberGroupDocs () override
void startMemberGroup () override
void endMemberGroup (bool) override
void insertMemberAlign (bool) override
void insertMemberAlignLeft (MemberItemType, bool) override
void startMemberDescription (const QCString &anchor, const QCString &inheritId, bool typ) override
void endMemberDescription () override
void startMemberDeclaration () override
void endMemberDeclaration (const QCString &anchor, const QCString &inheritId) override
void writeInheritedSectionTitle (const QCString &id, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &title, const QCString &name) override
void writeRuler () override
void writeAnchor (const QCString &, const QCString &name) override
void startEmphasis () override
void endEmphasis () override
void startBold () override
void endBold () override
void startDescForItem () override
void endDescForItem () override
void lineBreak (const QCString &style) override
void writeChar (char c) override
void startMemberDoc (const QCString &clName, const QCString &memName, const QCString &anchor, const QCString &title, int memCount, int memTotal, bool showInline) override
void endMemberDoc (bool) override
void startDoxyAnchor (const QCString &fName, const QCString &manName, const QCString &anchor, const QCString &name, const QCString &args) override
void endDoxyAnchor (const QCString &fName, const QCString &anchor) override
void addLabel (const QCString &, const QCString &) override
void writeLatexSpacing () override
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name) override
void startCenter () override
void endCenter () override
void startSmall () override
void endSmall () override
void startExamples () override
void endExamples () override
void startSection (const QCString &, const QCString &, SectionType) override
void endSection (const QCString &, SectionType) override
void addIndexItem (const QCString &, const QCString &) override
void startIndent () override
void endIndent () override
void writeSynopsis () override
void startClassDiagram () override
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &) override
void startPageRef () override
void endPageRef (const QCString &, const QCString &) override
void startQuickIndices () override
void endQuickIndices () override
void writeSplitBar (const QCString &name) override
void writeNavigationPath (const QCString &s) override
void writeLogo () override
void writeQuickLinks (HighlightedItem hli, const QCString &file) override
void writeSummaryLink (const QCString &file, const QCString &anchor, const QCString &title, bool first) override
void startContents () override
void endContents () override
void startPageDoc (const QCString &pageTitle) override
void endPageDoc () override
void writeNonBreakableSpace (int) override
void startDescTable (const QCString &title, const bool hasInits) override
void endDescTable () override
void startDescTableRow () override
void endDescTableRow () override
void startDescTableTitle () override
void endDescTableTitle () override
void startDescTableInit () override
void endDescTableInit () override
void startDescTableData () override
void endDescTableData () override
void startDotGraph () override
void endDotGraph (DotClassGraph &g) override
void startInclDepGraph () override
void endInclDepGraph (DotInclDepGraph &g) override
void startGroupCollaboration () override
void endGroupCollaboration (DotGroupCollaboration &g) override
void startCallGraph () override
void endCallGraph (DotCallGraph &g) override
void startDirDepGraph () override
void endDirDepGraph (DotDirDeps &g) override
void writeGraphicalHierarchy (DotGfxHierarchyTable &g) override
void startTextBlock (bool) override
void endTextBlock (bool) override
void lastIndexPage () override
void startMemberDocPrefixItem () override
void endMemberDocPrefixItem () override
void startMemberDocName (bool) override
void endMemberDocName () override
void startParameterType (bool first, const QCString &key) override
void endParameterType () override
void startParameterName (bool) override
void endParameterName () override
void startParameterExtra () override
void endParameterExtra (bool last, bool emptyList, bool closeBracket) override
void startParameterDefVal (const char *sep) override
void endParameterDefVal () override
void startParameterList (bool) override
void endParameterList () override
void exceptionEntry (const QCString &, bool) override
void startConstraintList (const QCString &) override
void startConstraintParam () override
void endConstraintParam () override
void startConstraintType () override
void endConstraintType () override
void startConstraintDocs () override
void endConstraintDocs () override
void endConstraintList () override
void startMemberDocSimple (bool) override
void endMemberDocSimple (bool) override
void startInlineMemberType () override
void endInlineMemberType () override
void startInlineMemberName () override
void endInlineMemberName () override
void startInlineMemberDoc () override
void endInlineMemberDoc () override
void startLabels () override
void writeLabel (const QCString &l, bool isLast) override
void endLabels () override
void writeLocalToc (const SectionRefs &sr, const LocalToc &lt) override
void startPlainFile (const QCString &name) override
void endPlainFile () override
Public Member Functions inherited from OutputGenerator
OutputGenerator ()
OutputGenerator (const QCString &dir)
virtual ~OutputGenerator ()=default
QCString dir () const
QCString fileName () const
void startPlainFile (const QCString &name)
void endPlainFile ()
Public Member Functions inherited from OutputGenIntf
Static Public Member Functions
static void init ()
static void writeStyleSheetFile (TextStream &t)
static void writeHeaderFile (TextStream &t, const QCString &cssname)
static void writeFooterFile (TextStream &t)
static void writeTabData ()
Additional initialization after indices have been created.
static void writeSearchInfoStatic (TextStream &t, const QCString &relPath)
static void writeSearchData (const QCString &dir)
static void writeSearchPage ()
static void writeExternalSearchPage ()
static QCString writeLogoAsString (const QCString &path)
static QCString writeSplitBarAsString (const QCString &name, const QCString &relpath)
static QCString getMathJaxMacros ()
static QCString getNavTreeCss ()
Private Member Functions
void startTitle ()
void endTitle ()
void docify_ (const QCString &text, bool inHtmlComment)
Static Private Member Functions
static void writePageFooter (TextStream &t, const QCString &, const QCString &, const QCString &)
Private Attributes
QCString m_lastTitle
QCString m_lastFile
QCString m_relPath
int m_sectionCount = 0
bool m_emptySection = false
std::unique_ptr< OutputCodeList > m_codeList
HtmlCodeGenerator * m_codeGen = nullptr
Additional Inherited Members
Public Types inherited from OutputGenerator
enum class ParamListTypes { Param , RetVal , Exception }
enum class MemberItemType { Normal , AnonymousStart , AnonymousEnd , Templated }
Protected Attributes inherited from OutputGenerator
TextStream m_t
QCString m_dir
Detailed Description
Generator for HTML output.
Definition at line 94 of file htmlgen.h.
Constructor & Destructor Documentation
HtmlGenerator() [1/3]
HtmlGenerator::HtmlGenerator ()
Definition at line 1089 of file htmlgen.cpp.
  : OutputGenerator(Config_getString(HTML_OUTPUT))
  , m_codeList(std::make_unique<OutputCodeList>())
{
  //printf("%p:HtmlGenerator()\n",(void*)this);
  m_codeGen = m_codeList->add<HtmlCodeGenerator>(&m_t);
}
References Config_getString, m_codeGen, m_codeList, OutputGenerator::m_t, and OutputGenerator::OutputGenerator().
Referenced by HtmlGenerator(), HtmlGenerator(), operator=(), and operator=().
HtmlGenerator() [2/3]
HtmlGenerator::HtmlGenerator (const HtmlGenerator & og)
Definition at line 1097 of file htmlgen.cpp.
                                                    : OutputGenerator(og.m_dir), OutputGenIntf()
{
  //printf("%p:HtmlGenerator(copy %p)\n",(void*)this,(void*)&og);
  m_codeList     = std::make_unique<OutputCodeList>(*og.m_codeList);
  m_codeGen      = m_codeList->get<HtmlCodeGenerator>(OutputType::Html);
  m_codeGen->setTextStream(&m_t);
  m_lastTitle    = og.m_lastTitle;
  m_lastFile     = og.m_lastFile;
  m_relPath      = og.m_relPath;
  m_sectionCount = og.m_sectionCount;
  m_emptySection = og.m_emptySection;
}
References Html, HtmlGenerator(), m_codeGen, m_codeList, OutputGenerator::m_dir, m_emptySection, m_lastFile, m_lastTitle, m_relPath, m_sectionCount, OutputGenerator::m_t, and OutputGenerator::OutputGenerator().
HtmlGenerator() [3/3]
HtmlGenerator::HtmlGenerator (HtmlGenerator &&) delete
References HtmlGenerator().
~HtmlGenerator()
HtmlGenerator::~HtmlGenerator () default
References OutputGenerator::dir().
Member Function Documentation
addCodeGen()
void HtmlGenerator::addCodeGen (OutputCodeList & list) override virtual
Implements OutputGenIntf.
Definition at line 1130 of file htmlgen.cpp.
{
  list.add<HtmlCodeGeneratorDefer>(m_codeGen);
}
References OutputCodeList::add(), and m_codeGen.
addIndexItem()
void HtmlGenerator::addIndexItem (const QCString & , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 2566 of file htmlgen.cpp.
{
}
addLabel()
void HtmlGenerator::addLabel (const QCString & , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 1689 of file htmlgen.cpp.
{
}
cleanup()
void HtmlGenerator::cleanup () override virtual
Implements OutputGenIntf.
Definition at line 1283 of file htmlgen.cpp.
{
  QCString dname = Config_getString(HTML_OUTPUT);
  Dir d(dname.str());
  clearSubDirs(d);
}
References clearSubDirs(), Config_getString, and QCString::str().
clearBuffer()
void HtmlGenerator::clearBuffer ()
clone()
std::unique_ptr< OutputGenIntf > HtmlGenerator::clone () inline override virtual
Implements OutputGenIntf.
Definition at line 122 of file htmlgen.h.
{ return std::make_unique<HtmlGenerator>(*this); }
docify()
void HtmlGenerator::docify (const QCString & text) override virtual
Implements OutputGenIntf.
Definition at line 1880 of file htmlgen.cpp.
{
  docify_(str,FALSE);
}
References docify_(), and FALSE.
Referenced by startExamples(), startMemberDoc(), startParameterDefVal(), writeChar(), writeObjectLink(), and writeStartAnnoItem().
docify_()
void HtmlGenerator::docify_ (const QCString & text, bool inHtmlComment) private
Definition at line 1885 of file htmlgen.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    while (*p)
    {
      char c=*p++;
      switch(c)
      {
        case '<':  m_t << "&lt;"; break;
        case '>':  m_t << "&gt;"; break;
        case '&':  m_t << "&amp;"; break;
        case '"':  m_t << "&quot;"; break;
        case '-':  if (inHtmlComment) m_t << "&#45;"; else m_t << "-"; break;
        case '\\':
                   if (*p=='<')
                     { m_t << "&lt;"; p++; }
                   else if (*p=='>')
                     { m_t << "&gt;"; p++; }
                   else if (*p=='(')
                     { m_t << "\\&zwj;("; p++; }
                   else if (*p==')')
                     { m_t << "\\&zwj;)"; p++; }
                   else
                     m_t << "\\";
                   break;
        default:   m_t << c;
      }
    }
  }
}
References QCString::data(), QCString::isEmpty(), and OutputGenerator::m_t.
Referenced by docify().
endAnonTypeScope()
void HtmlGenerator::endAnonTypeScope (int) inline override virtual
Implements OutputGenIntf.
Definition at line 185 of file htmlgen.h.
{}
endBold()
void HtmlGenerator::endBold () inline override virtual
Implements OutputGenIntf.
Definition at line 216 of file htmlgen.h.
{ m_t << "</b>"; }
References OutputGenerator::m_t.
endCallGraph()
void HtmlGenerator::endCallGraph (DotCallGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 2489 of file htmlgen.cpp.
{
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::Html,dir(),fileName(),m_relPath,TRUE,m_sectionCount);
  endSectionContent(m_t);
  m_sectionCount++;
}
References BITMAP, OutputGenerator::dir(), endSectionContent(), endSectionHeader(), endSectionSummary(), OutputGenerator::fileName(), Html, m_relPath, m_sectionCount, OutputGenerator::m_t, startSectionContent(), startSectionSummary(), TRUE, and DotCallGraph::writeGraph().
endCenter()
void HtmlGenerator::endCenter () inline override virtual
Implements OutputGenIntf.
Definition at line 234 of file htmlgen.h.
{ m_t << "</center>\n"; }
References OutputGenerator::m_t.
endClassDiagram()
void HtmlGenerator::endClassDiagram (const ClassDiagram & d, const QCString & fileName, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 2005 of file htmlgen.cpp.
{
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  TextStream tt;
  d.writeImage(tt,dir(),m_relPath,fileName);
  if (!tt.empty())
  {
    m_t << " <div class=\"center\">\n";
    m_t << "  <img src=\"";
    m_t << m_relPath << fileName << ".png\" usemap=\"#" << convertToId(name);
    m_t << "_map\" alt=\"\"/>\n";
    m_t << "  <map id=\"" << convertToId(name);
    m_t << "_map\" name=\"" << convertToId(name);
    m_t << "_map\">\n";
    m_t << tt.str();
    m_t << "  </map>\n";
    m_t << "</div>";
  }
  else
  {
    m_t << " <div class=\"center\">\n";
    m_t << "  <img src=\"";
    m_t << m_relPath << fileName << ".png\" alt=\"\"/>\n";
    m_t << " </div>";
  }
  endSectionContent(m_t);
  m_sectionCount++;
}
References convertToId(), OutputGenerator::dir(), TextStream::empty(), endSectionContent(), endSectionHeader(), endSectionSummary(), OutputGenerator::fileName(), m_relPath, m_sectionCount, OutputGenerator::m_t, startSectionContent(), startSectionSummary(), TextStream::str(), and ClassDiagram::writeImage().
endCompoundTemplateParams()
void HtmlGenerator::endCompoundTemplateParams () override virtual
Implements OutputGenIntf.
Definition at line 2104 of file htmlgen.cpp.
{
  m_t << "</div>";
}
References OutputGenerator::m_t.
endConstraintDocs()
void HtmlGenerator::endConstraintDocs () override virtual
Implements OutputGenIntf.
Definition at line 3304 of file htmlgen.cpp.
{
  m_t << "</td></tr>\n";
}
References OutputGenerator::m_t.
endConstraintList()
void HtmlGenerator::endConstraintList () override virtual
Implements OutputGenIntf.
Definition at line 3309 of file htmlgen.cpp.
{
  m_t << "</table>\n";
  m_t << "</dd>\n";
  m_t << "</dl>\n";
  m_t << "</div>\n";
}
References OutputGenerator::m_t.
endConstraintParam()
void HtmlGenerator::endConstraintParam () override virtual
Implements OutputGenIntf.
Definition at line 3284 of file htmlgen.cpp.
{
  m_t << "</em></td>";
}
References OutputGenerator::m_t.
endConstraintType()
void HtmlGenerator::endConstraintType () override virtual
Implements OutputGenIntf.
Definition at line 3294 of file htmlgen.cpp.
{
  m_t << "</em></td>";
}
References OutputGenerator::m_t.
endContents()
void HtmlGenerator::endContents () override virtual
Implements OutputGenIntf.
Definition at line 3050 of file htmlgen.cpp.
{
  m_t << "</div><!-- contents -->\n";
}
References OutputGenerator::m_t.
endDescForItem()
void HtmlGenerator::endDescForItem () inline override virtual
Implements OutputGenIntf.
Definition at line 218 of file htmlgen.h.
{ m_t << "</dd>\n"; }
References OutputGenerator::m_t.
endDescTable()
void HtmlGenerator::endDescTable () override virtual
Implements OutputGenIntf.
Definition at line 2583 of file htmlgen.cpp.
{
  m_t << "</table>\n";
}
References OutputGenerator::m_t.
endDescTableData()
void HtmlGenerator::endDescTableData () override virtual
Implements OutputGenIntf.
Definition at line 2623 of file htmlgen.cpp.
{
  m_t << "</td>";
}
References OutputGenerator::m_t.
endDescTableInit()
void HtmlGenerator::endDescTableInit () override virtual
Implements OutputGenIntf.
Definition at line 2613 of file htmlgen.cpp.
{
  m_t << "&#160;</td>";
}
References OutputGenerator::m_t.
endDescTableRow()
void HtmlGenerator::endDescTableRow () override virtual
Implements OutputGenIntf.
Definition at line 2593 of file htmlgen.cpp.
{
  m_t << "</tr>\n";
}
References OutputGenerator::m_t.
endDescTableTitle()
void HtmlGenerator::endDescTableTitle () override virtual
Implements OutputGenIntf.
Definition at line 2603 of file htmlgen.cpp.
{
  m_t << "&#160;</td>";
}
References OutputGenerator::m_t.
endDirDepGraph()
void HtmlGenerator::endDirDepGraph (DotDirDeps & g) override virtual
Implements OutputGenIntf.
Definition at line 2507 of file htmlgen.cpp.
{
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::Html,dir(),fileName(),m_relPath,TRUE,m_sectionCount);
  endSectionContent(m_t);
  m_sectionCount++;
}
References BITMAP, OutputGenerator::dir(), endSectionContent(), endSectionHeader(), endSectionSummary(), OutputGenerator::fileName(), Html, m_relPath, m_sectionCount, OutputGenerator::m_t, startSectionContent(), startSectionSummary(), TRUE, and DotDirDeps::writeGraph().
endDotGraph()
void HtmlGenerator::endDotGraph (DotClassGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 2419 of file htmlgen.cpp.
{
  bool generateLegend = Config_getBool(GENERATE_LEGEND);
  bool umlLook = Config_getBool(UML_LOOK);
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::Html,dir(),fileName(),m_relPath,TRUE,TRUE,m_sectionCount);
  if (generateLegend && !umlLook)
  {
    QCString url = m_relPath+"graph_legend"+Doxygen::htmlFileExtension;
    m_t << "<center><span class=\"legend\">[";
    bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
    m_t << "<a ";
    if (generateTreeView) m_t << "target=\"top\" ";
    m_t << "href=\"";
    if (!url.isEmpty()) m_t << url;
    m_t << "\">";
    m_t << theTranslator->trLegend();
    m_t << "</a>";
    m_t << "]</span></center>";
  }
  endSectionContent(m_t);
  m_sectionCount++;
}
References BITMAP, Config_getBool, OutputGenerator::dir(), endSectionContent(), endSectionHeader(), endSectionSummary(), OutputGenerator::fileName(), Html, Doxygen::htmlFileExtension, QCString::isEmpty(), m_relPath, m_sectionCount, OutputGenerator::m_t, startSectionContent(), startSectionSummary(), theTranslator, Translator::trLegend(), TRUE, and DotClassGraph::writeGraph().
endDoxyAnchor()
void HtmlGenerator::endDoxyAnchor (const QCString & fName, const QCString & anchor) override virtual
Implements OutputGenIntf.
Definition at line 1685 of file htmlgen.cpp.
{
}
endEmphasis()
void HtmlGenerator::endEmphasis () inline override virtual
Implements OutputGenIntf.
Definition at line 214 of file htmlgen.h.
{ m_t << "</em>"; }
References OutputGenerator::m_t.
endExamples()
void HtmlGenerator::endExamples () override virtual
Implements OutputGenIntf.
Definition at line 2635 of file htmlgen.cpp.
{
  m_t << "</dl>\n";
}
References OutputGenerator::m_t.
endFile()
void HtmlGenerator::endFile () override virtual
Implements OutputGenIntf.
Definition at line 1591 of file htmlgen.cpp.
{
  endPlainFile();
}
References endPlainFile().
endGroupCollaboration()
void HtmlGenerator::endGroupCollaboration (DotGroupCollaboration & g) override virtual
Implements OutputGenIntf.
Definition at line 2471 of file htmlgen.cpp.
{
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::Html,dir(),fileName(),m_relPath,TRUE,m_sectionCount);
  endSectionContent(m_t);
  m_sectionCount++;
}
References BITMAP, OutputGenerator::dir(), endSectionContent(), endSectionHeader(), endSectionSummary(), OutputGenerator::fileName(), Html, m_relPath, m_sectionCount, OutputGenerator::m_t, startSectionContent(), startSectionSummary(), TRUE, and DotGroupCollaboration::writeGraph().
endGroupHeader()
void HtmlGenerator::endGroupHeader (int extraIndentLevel) override virtual
Implements OutputGenIntf.
Definition at line 1833 of file htmlgen.cpp.
{
  if (extraIndentLevel==2)
  {
    m_t << "</h4>\n";
  }
  else if (extraIndentLevel==1)
  {
    m_t << "</h3>\n";
  }
  else
  {
    m_t << "</h2>\n";
  }
}
References OutputGenerator::m_t.
endHeaderSection()
void HtmlGenerator::endHeaderSection () override virtual
Implements OutputGenIntf.
Definition at line 3346 of file htmlgen.cpp.
{
  m_t << "</div><!--header-->\n";
}
References OutputGenerator::m_t.
endInclDepGraph()
void HtmlGenerator::endInclDepGraph (DotInclDepGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 2453 of file htmlgen.cpp.
{
  endSectionHeader(m_t);
  startSectionSummary(m_t,m_sectionCount);
  endSectionSummary(m_t);
  startSectionContent(m_t,m_sectionCount);
  g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::Html,dir(),fileName(),m_relPath,TRUE,m_sectionCount);
  endSectionContent(m_t);
  m_sectionCount++;
}
References BITMAP, OutputGenerator::dir(), endSectionContent(), endSectionHeader(), endSectionSummary(), OutputGenerator::fileName(), Html, m_relPath, m_sectionCount, OutputGenerator::m_t, startSectionContent(), startSectionSummary(), TRUE, and DotInclDepGraph::writeGraph().
endIndent()
void HtmlGenerator::endIndent () override virtual
Implements OutputGenIntf.
Definition at line 2560 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endIndent -->\n";)
  m_t << "\n</div>\n" << "</div>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endIndexItem()
void HtmlGenerator::endIndexItem (const QCString & ref, const QCString & file) override virtual
Implements OutputGenIntf.
Definition at line 1751 of file htmlgen.cpp.
{
  //printf("HtmlGenerator::endIndexItem(%s,%s,%s)\n",ref,f,name);
  if (!ref.isEmpty() || !f.isEmpty())
  {
    m_t << "</a>";
  }
  else
  {
    m_t << "</b>";
  }
}
References QCString::isEmpty(), and OutputGenerator::m_t.
endIndexKey()
void HtmlGenerator::endIndexKey () override virtual
Implements OutputGenIntf.
Definition at line 2223 of file htmlgen.cpp.
{
  //m_t << "</td>";
}
endIndexList()
void HtmlGenerator::endIndexList () override virtual
Implements OutputGenIntf.
Definition at line 2213 of file htmlgen.cpp.
{
  m_t << "</table>\n";
}
References OutputGenerator::m_t.
endIndexListItem()
void HtmlGenerator::endIndexListItem () override virtual
Implements OutputGenIntf.
Definition at line 1716 of file htmlgen.cpp.
{
  m_t << "</li>\n";
}
References OutputGenerator::m_t.
endIndexSection()
void HtmlGenerator::endIndexSection (IndexSection) inline override virtual
Implements OutputGenIntf.
Definition at line 133 of file htmlgen.h.
{}
endIndexValue()
void HtmlGenerator::endIndexValue (const QCString & , bool) override virtual
Implements OutputGenIntf.
Definition at line 2233 of file htmlgen.cpp.
{
  //m_t << "</td></tr>\n";
}
endInlineHeader()
void HtmlGenerator::endInlineHeader () override virtual
Implements OutputGenIntf.
Definition at line 3361 of file htmlgen.cpp.
{
  m_t << "</h3></td></tr>\n";
}
References OutputGenerator::m_t.
endInlineMemberDoc()
void HtmlGenerator::endInlineMemberDoc () override virtual
Implements OutputGenIntf.
Definition at line 3411 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endInlineMemberDoc -->\n";)
  m_t << "</td></tr>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endInlineMemberName()
void HtmlGenerator::endInlineMemberName () override virtual
Implements OutputGenIntf.
Definition at line 3399 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endInlineMemberName -->\n";)
  m_t << "</td>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endInlineMemberType()
void HtmlGenerator::endInlineMemberType () override virtual
Implements OutputGenIntf.
Definition at line 3387 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endInlineMemberType -->\n";)
  m_t << "</td>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endItemList()
void HtmlGenerator::endItemList () inline override virtual
Implements OutputGenIntf.
Definition at line 153 of file htmlgen.h.
{ m_t << "</ul>\n"; }
References OutputGenerator::m_t.
endItemListItem()
void HtmlGenerator::endItemListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 168 of file htmlgen.h.
{ m_t << "</li>\n"; }
References OutputGenerator::m_t.
endLabels()
void HtmlGenerator::endLabels () override virtual
Implements OutputGenIntf.
Definition at line 3431 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endLabels -->\n";)
  m_t << "</span>";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDeclaration()
void HtmlGenerator::endMemberDeclaration (const QCString & anchor, const QCString & inheritId) override virtual
Implements OutputGenIntf.
Definition at line 3495 of file htmlgen.cpp.
{
  m_t << "<tr class=\"separator:" << anchor;
  if (!inheritId.isEmpty())
  {
    m_t << " inherit " << inheritId;
  }
  m_t << "\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n";
}
References QCString::isEmpty(), and OutputGenerator::m_t.
endMemberDescription()
void HtmlGenerator::endMemberDescription () override virtual
Implements OutputGenIntf.
Definition at line 2147 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDescription -->\n")
  m_t << "<br /></td></tr>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDoc()
void HtmlGenerator::endMemberDoc (bool hasArgs) override virtual
Implements OutputGenIntf.
Definition at line 2403 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDoc -->\n";)
  if (!hasArgs)
  {
    m_t << "        </tr>\n";
  }
  m_t << "      </table>\n";
 // m_t << "</div>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDocList()
void HtmlGenerator::endMemberDocList () override virtual
Implements OutputGenIntf.
Definition at line 2243 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDocList -->\n";)
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDocName()
void HtmlGenerator::endMemberDocName () override virtual
Implements OutputGenIntf.
Definition at line 2287 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDocName -->\n";)
  m_t << "</td>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDocPrefixItem()
void HtmlGenerator::endMemberDocPrefixItem () override virtual
Implements OutputGenIntf.
Definition at line 2271 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDocPrefixItem -->\n";)
  m_t << "</div>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberDocSimple()
void HtmlGenerator::endMemberDocSimple (bool) override virtual
Implements OutputGenIntf.
Definition at line 3375 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberDocSimple -->\n";)
  m_t << "</table>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberGroup()
void HtmlGenerator::endMemberGroup (bool) override virtual
Implements OutputGenIntf.
Definition at line 2549 of file htmlgen.cpp.
{
}
endMemberGroupDocs()
void HtmlGenerator::endMemberGroupDocs () override virtual
Implements OutputGenIntf.
Definition at line 2540 of file htmlgen.cpp.
{
  m_t << "</div></td></tr>\n";
}
References OutputGenerator::m_t.
endMemberGroupHeader()
void HtmlGenerator::endMemberGroupHeader () override virtual
Implements OutputGenIntf.
Definition at line 2530 of file htmlgen.cpp.
{
  m_t << "</div></td></tr>\n";
}
References OutputGenerator::m_t.
endMemberHeader()
void HtmlGenerator::endMemberHeader () override virtual
Implements OutputGenIntf.
Definition at line 2190 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberHeader -->\n")
  m_t << "</h2></td></tr>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberItem()
void HtmlGenerator::endMemberItem (MemberItemType type) override virtual
Implements OutputGenIntf.
Definition at line 2075 of file htmlgen.cpp.
{
  if (type==MemberItemType::AnonymousStart || type==MemberItemType::AnonymousEnd)
  {
    insertMemberAlign(false);
  }
  m_t << "</td></tr>\n";
}
References OutputGenerator::AnonymousEnd, OutputGenerator::AnonymousStart, insertMemberAlign(), OutputGenerator::m_t, and type().
endMemberList()
void HtmlGenerator::endMemberList () override virtual
Implements OutputGenIntf.
Definition at line 2044 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberList -->\n")
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberSections()
void HtmlGenerator::endMemberSections () override virtual
Implements OutputGenIntf.
Definition at line 2161 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberSections -->\n")
  if (!m_emptySection)
  {
    m_t << "</table>\n";
  }
}
References DBG_HTML, m_emptySection, and OutputGenerator::m_t.
endMemberSubtitle()
void HtmlGenerator::endMemberSubtitle () override virtual
Implements OutputGenIntf.
Definition at line 2202 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endMemberSubtitle -->\n")
  m_t << "</td></tr>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endMemberTemplateParams()
void HtmlGenerator::endMemberTemplateParams (const QCString & anchor, const QCString & inheritId) override virtual
Implements OutputGenIntf.
Definition at line 2088 of file htmlgen.cpp.
{
  m_t << "</td></tr>\n";
  m_t << "<tr class=\"memitem:" << anchor;
  if (!inheritId.isEmpty())
  {
    m_t << " inherit " << inheritId;
  }
  m_t << "\"><td class=\"memTemplItemLeft\" align=\"right\" valign=\"top\">";
}
References QCString::isEmpty(), and OutputGenerator::m_t.
endPageDoc()
void HtmlGenerator::endPageDoc () override virtual
Implements OutputGenIntf.
Definition at line 3060 of file htmlgen.cpp.
{
  m_t << "</div><!-- PageDoc -->\n";
}
References OutputGenerator::m_t.
endPageRef()
void HtmlGenerator::endPageRef (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 248 of file htmlgen.h.
{}
endParagraph()
void HtmlGenerator::endParagraph () override virtual
Implements OutputGenIntf.
Definition at line 1701 of file htmlgen.cpp.
{
  m_t << "</p>\n";
}
References OutputGenerator::m_t.
endParameterDefVal()
void HtmlGenerator::endParameterDefVal () override virtual
Implements OutputGenIntf.
Definition at line 2372 of file htmlgen.cpp.
{
  m_t << "</span>";
}
References OutputGenerator::m_t.
endParameterExtra()
void HtmlGenerator::endParameterExtra (bool last, bool emptyList, bool closeBracket) override virtual
Implements OutputGenIntf.
Definition at line 2341 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endParameterExtra -->\n";)
  if (last)
  {
    if (emptyList)
    {
      if (closeBracket) m_t << "</td><td>)";
      m_t << "</td>\n";
      m_t << "          <td>";
    }
    else
    {
      m_t << "&#160;";
      if (closeBracket) m_t << ")";
    }
  }
  else
  {
    m_t << "</td>\n";
    m_t << "        </tr>\n";
  }
}
References DBG_HTML, and OutputGenerator::m_t.
endParameterList()
void HtmlGenerator::endParameterList () override virtual
Implements OutputGenIntf.
Definition at line 2377 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endParameterList -->\n";)
  m_t << "</td>\n";
  m_t << "        </tr>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
endParameterName()
void HtmlGenerator::endParameterName () override virtual
Implements OutputGenIntf.
Definition at line 2330 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endParameterName -->\n";)
  m_t << "</em></span>";
}
References DBG_HTML, and OutputGenerator::m_t.
endParameterType()
void HtmlGenerator::endParameterType () override virtual
Implements OutputGenIntf.
Definition at line 2318 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- endParameterType -->\n";)
  m_t << "</td>";
}
References DBG_HTML, and OutputGenerator::m_t.
endPlainFile()
void HtmlGenerator::endPlainFile () inline override virtual
Implements OutputGenIntf.
Definition at line 330 of file htmlgen.h.
{ OutputGenerator::endPlainFile(); }
References OutputGenerator::endPlainFile().
Referenced by endFile(), and writeStyleInfo().
endProjectNumber()
void HtmlGenerator::endProjectNumber () override virtual
Implements OutputGenIntf.
Definition at line 1601 of file htmlgen.cpp.
{
  m_t << "</h3>";
}
References OutputGenerator::m_t.
endQuickIndices()
void HtmlGenerator::endQuickIndices () override virtual
Implements OutputGenIntf.
Definition at line 2981 of file htmlgen.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  m_t << "</div><!-- top -->\n";
  if (!generateTreeView)
  {
    m_t << "<div id=\"doc-content\">\n";
  }
}
References Config_getBool, and OutputGenerator::m_t.
endSection()
void HtmlGenerator::endSection (const QCString & , SectionType type) override virtual
Implements OutputGenIntf.
Definition at line 1865 of file htmlgen.cpp.
{
  switch(type.level())
  {
    case SectionType::Page:             m_t << "</h1>"; break;
    case SectionType::Section:          m_t << "</h2>"; break;
    case SectionType::Subsection:       m_t << "</h3>"; break;
    case SectionType::Subsubsection:    m_t << "</h4>"; break;
    case SectionType::Paragraph:        m_t << "</h5>"; break;
    case SectionType::Subparagraph:     m_t << "</h6>"; break;
    case SectionType::Subsubparagraph:  m_t << "</h6>"; break;
    default: ASSERT(0); break;
  }
}
References ASSERT, OutputGenerator::m_t, SectionType::Page, SectionType::Paragraph, SectionType::Section, SectionType::Subparagraph, SectionType::Subsection, SectionType::Subsubparagraph, SectionType::Subsubsection, and type().
endSmall()
void HtmlGenerator::endSmall () inline override virtual
Implements OutputGenIntf.
Definition at line 236 of file htmlgen.h.
{ m_t << "</small>\n"; }
References OutputGenerator::m_t.
endTextBlock()
void HtmlGenerator::endTextBlock (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 286 of file htmlgen.h.
{ m_t << "</div>"; }
References OutputGenerator::m_t.
endTextLink()
void HtmlGenerator::endTextLink () override virtual
Implements OutputGenIntf.
Definition at line 1812 of file htmlgen.cpp.
{
  m_t << "</a>";
}
References OutputGenerator::m_t.
endTitle()
void HtmlGenerator::endTitle () inline private
Definition at line 334 of file htmlgen.h.
{ m_t << "</div>"; }
References OutputGenerator::m_t.
Referenced by endTitleHead().
endTitleHead()
void HtmlGenerator::endTitleHead (const QCString & , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 3340 of file htmlgen.cpp.
{
  endTitle();
  m_t << "</div>\n";
}
References endTitle(), and OutputGenerator::m_t.
endTypewriter()
void HtmlGenerator::endTypewriter () inline override virtual
Implements OutputGenIntf.
Definition at line 164 of file htmlgen.h.
{ m_t << "</code>"; }
References OutputGenerator::m_t.
exceptionEntry()
void HtmlGenerator::exceptionEntry (const QCString & prefix, bool closeBracket) override virtual
Implements OutputGenIntf.
Definition at line 2384 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- exceptionEntry -->\n";)
  if (!closeBracket)
  {
  m_t << "</td>\n";
  m_t << "        </tr>\n";
  m_t << "        <tr>\n";
  m_t << "          <td align=\"right\">";
  }
  // colspan 2 so it gets both parameter type and parameter name columns
  if (!prefix.isEmpty())
    m_t << prefix << "</td><td>(</td><td colspan=\"2\">";
  else if (closeBracket)
    m_t << "&#160;)</td><td></td><td></td><td>";
  else
    m_t << "</td><td></td><td colspan=\"2\">";
}
References DBG_HTML, OutputGenerator::m_t, and prefix.
getMathJaxMacros()
QCString HtmlGenerator::getMathJaxMacros () static
Definition at line 3505 of file htmlgen.cpp.
{
  return getConvertLatexMacro();
}
References getConvertLatexMacro().
getNavTreeCss()
QCString HtmlGenerator::getNavTreeCss () static
Definition at line 3510 of file htmlgen.cpp.
{
  ResourceMgr &mgr = ResourceMgr::instance();
  return replaceVariables(mgr.getAsString("navtree.css"));
}
References ResourceMgr::getAsString(), ResourceMgr::instance(), and replaceVariables().
Referenced by init().
init()
void HtmlGenerator::init () static
Definition at line 1135 of file htmlgen.cpp.
{
  QCString dname = Config_getString(HTML_OUTPUT);
  Dir d(dname.str());
  if (!d.exists() && !d.mkdir(dname.str()))
  {
    term("Could not create output directory %s\n",qPrint(dname));
  }
  //writeLogo(dname);
  if (!Config_getString(HTML_HEADER).isEmpty())
  {
    g_header=fileToString(Config_getString(HTML_HEADER));
    //printf("g_header='%s'\n",qPrint(g_header));
    QCString result = substituteHtmlKeywords(g_header,QCString(),QCString());
    checkBlocks(result,Config_getString(HTML_HEADER),htmlMarkerInfo);
  }
  else
  {
    g_header = ResourceMgr::instance().getAsString("header.html");
    QCString result = substituteHtmlKeywords(g_header,QCString(),QCString());
    checkBlocks(result,"<default header.html>",htmlMarkerInfo);
  }
  if (!Config_getString(HTML_FOOTER).isEmpty())
  {
    g_footer=fileToString(Config_getString(HTML_FOOTER));
    //printf("g_footer='%s'\n",qPrint(g_footer));
    QCString result = substituteHtmlKeywords(g_footer,QCString(),QCString());
    checkBlocks(result,Config_getString(HTML_FOOTER),htmlMarkerInfo);
  }
  else
  {
    g_footer = ResourceMgr::instance().getAsString("footer.html");
    QCString result = substituteHtmlKeywords(g_footer,QCString(),QCString());
    checkBlocks(result,"<default footer.html>",htmlMarkerInfo);
  }
  if (Config_getBool(USE_MATHJAX))
  {
    if (!Config_getString(MATHJAX_CODEFILE).isEmpty())
    {
      g_mathjax_code=fileToString(Config_getString(MATHJAX_CODEFILE));
      //printf("g_mathjax_code='%s'\n",qPrint(g_mathjax_code));
    }
    g_latex_macro=getConvertLatexMacro();
    //printf("converted g_latex_macro='%s'\n",qPrint(g_latex_macro));
  }
  createSubDirs(d);
  fillColorStyleMaps();
  ResourceMgr &mgr = ResourceMgr::instance();
  {
    QCString tabsCss;
    if (Config_getBool(HTML_DYNAMIC_MENUS))
    {
      tabsCss = mgr.getAsString("tabs.css");
    }
    else // stylesheet for the 'old' static tabs
    {
      tabsCss = mgr.getAsString("fixed_tabs.css");
    }
    std::ofstream f = Portable::openOutputStream(dname+"/tabs.css");
    if (f.is_open())
    {
      TextStream t(&f);
      t << replaceVariables(tabsCss);
    }
  }
  mgr.copyResource("jquery.js",dname);
  if (Config_getBool(INTERACTIVE_SVG))
  {
    mgr.copyResource("svg.min.js",dname);
  }
  if (!Config_getBool(DISABLE_INDEX) && Config_getBool(HTML_DYNAMIC_MENUS))
  {
    mgr.copyResource("menu.js",dname);
  }
  // copy navtree.css
  {
    std::ofstream f = Portable::openOutputStream(dname+"/navtree.css");
    if (f.is_open())
    {
      TextStream t(&f);
      t << getNavTreeCss();
    }
  }
  // copy resize.js
  {
    std::ofstream f = Portable::openOutputStream(dname+"/resize.js");
    if (f.is_open())
    {
      TextStream t(&f);
      t << substitute(
             substitute(mgr.getAsString("resize.js"),
                "$TREEVIEW_WIDTH", QCString().setNum(Config_getInt(TREEVIEW_WIDTH))),
                "$PROJECTID",      getProjectId());
    }
  }
  if (Config_getBool(HTML_COPY_CLIPBOARD))
  {
    std::ofstream f = Portable::openOutputStream(dname+"/clipboard.js");
    if (f.is_open())
    {
      TextStream t(&f);
      t << substitute(mgr.getAsString("clipboard.js"),"$copy_to_clipboard_text",theTranslator->trCopyToClipboard());
    }
  }
  bool hasCookie = Config_getBool(GENERATE_TREEVIEW) || Config_getBool(SEARCHENGINE) || Config_getEnum(HTML_COLORSTYLE)==HTML_COLORSTYLE_t::TOGGLE;
  if (hasCookie)
  {
    mgr.copyResource("cookie.js",dname);
  }
  if (Config_getBool(HTML_COLORSTYLE)==HTML_COLORSTYLE_t::TOGGLE)
  {
    std::ofstream f = Portable::openOutputStream(dname+"/darkmode_toggle.js");
    if (f.is_open())
    {
      TextStream t(&f);
      t << substitute(replaceColorMarkers(mgr.getAsString("darkmode_toggle.js")),
          "$PROJECTID",getProjectId());
    }
  }
  {
    std::ofstream f = Portable::openOutputStream(dname+"/dynsections.js");
    if (f.is_open())
    {
      TextStream t(&f);
      t << replaceVariables(mgr.getAsString("dynsections.js"));
      if (Config_getBool(SOURCE_BROWSER) && Config_getBool(SOURCE_TOOLTIPS))
      {
        t << replaceVariables(mgr.getAsString("dynsections_tooltips.js"));
      }
    }
  }
}
References checkBlocks(), Config_getBool, Config_getEnum, Config_getInt, Config_getString, ResourceMgr::copyResource(), createSubDirs(), Dir::exists(), fileToString(), fillColorStyleMaps(), g_footer, g_header, g_latex_macro, g_mathjax_code, ResourceMgr::getAsString(), getConvertLatexMacro(), getNavTreeCss(), getProjectId(), htmlMarkerInfo, ResourceMgr::instance(), Dir::mkdir(), Portable::openOutputStream(), qPrint(), replaceColorMarkers(), replaceVariables(), QCString::str(), substitute(), substituteHtmlKeywords(), term, theTranslator, and Translator::trCopyToClipboard().
Referenced by generateOutput().
insertMemberAlign()
void HtmlGenerator::insertMemberAlign (bool templ) override virtual
Implements OutputGenIntf.
Definition at line 2109 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- insertMemberAlign -->\n")
  QCString className = templ ? "memTemplItemRight" : "memItemRight";
  m_t << "&#160;</td><td class=\"" << className << "\" valign=\"bottom\">";
}
References DBG_HTML, and OutputGenerator::m_t.
Referenced by endMemberItem().
insertMemberAlignLeft()
void HtmlGenerator::insertMemberAlignLeft (MemberItemType type, bool initTag) override virtual
Implements OutputGenIntf.
Definition at line 2116 of file htmlgen.cpp.
{
  if (!initTag) m_t << "&#160;</td>";
  switch (type)
  {
    case MemberItemType::Normal:         m_t << "<td class=\"memItemLeft\" align=\"right\" valign=\"top\">"; break;
    case MemberItemType::AnonymousStart: m_t << "<td class=\"memItemLeft\" >"; break;
    case MemberItemType::AnonymousEnd:   m_t << "<td class=\"memItemLeft\" valign=\"top\">"; break;
    case MemberItemType::Templated:      m_t << "<td class=\"memTemplParams\" colspan=\"2\">"; break;
  }
}
References OutputGenerator::AnonymousEnd, OutputGenerator::AnonymousStart, OutputGenerator::m_t, OutputGenerator::Normal, OutputGenerator::Templated, and type().
Referenced by startMemberItem().
lastIndexPage()
void HtmlGenerator::lastIndexPage () inline override virtual
Implements OutputGenIntf.
Definition at line 287 of file htmlgen.h.
{}
lineBreak()
void HtmlGenerator::lineBreak (const QCString & style) override virtual
Implements OutputGenIntf.
Definition at line 3317 of file htmlgen.cpp.
{
  if (!style.isEmpty())
  {
    m_t << "<br class=\"" << style << "\" />\n";
  }
  else
  {
    m_t << "<br />\n";
  }
}
References QCString::isEmpty(), and OutputGenerator::m_t.
operator=() [1/2]
HtmlGenerator & HtmlGenerator::operator= (const HtmlGenerator & og)
Definition at line 1110 of file htmlgen.cpp.
{
  //printf("%p:HtmlGenerator(copy assign %p)\n",(void*)this,(void*)&og);
  if (this!=&og)
  {
    m_dir          = og.m_dir;
    m_codeList     = std::make_unique<OutputCodeList>(*og.m_codeList);
    m_codeGen      = m_codeList->get<HtmlCodeGenerator>(OutputType::Html);
    m_codeGen->setTextStream(&m_t);
    m_lastTitle    = og.m_lastTitle;
    m_lastFile     = og.m_lastFile;
    m_relPath      = og.m_relPath;
    m_sectionCount = og.m_sectionCount;
    m_emptySection = og.m_emptySection;
  }
  return *this;
}
References Html, HtmlGenerator(), m_codeGen, m_codeList, OutputGenerator::m_dir, m_emptySection, m_lastFile, m_lastTitle, m_relPath, m_sectionCount, and OutputGenerator::m_t.
operator=() [2/2]
HtmlGenerator & HtmlGenerator::operator= (HtmlGenerator &&) delete
References HtmlGenerator().
startAnonTypeScope()
void HtmlGenerator::startAnonTypeScope (int) inline override virtual
Implements OutputGenIntf.
Definition at line 184 of file htmlgen.h.
{}
startBold()
void HtmlGenerator::startBold () inline override virtual
Implements OutputGenIntf.
Definition at line 215 of file htmlgen.h.
{ m_t << "<b>"; }
References OutputGenerator::m_t.
startCallGraph()
void HtmlGenerator::startCallGraph () override virtual
Implements OutputGenIntf.
Definition at line 2484 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startCenter()
void HtmlGenerator::startCenter () inline override virtual
Implements OutputGenIntf.
Definition at line 233 of file htmlgen.h.
{ m_t << "<center>\n"; }
References OutputGenerator::m_t.
startClassDiagram()
void HtmlGenerator::startClassDiagram () override virtual
Implements OutputGenIntf.
Definition at line 2000 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startCompoundTemplateParams()
void HtmlGenerator::startCompoundTemplateParams () override virtual
Implements OutputGenIntf.
Definition at line 2099 of file htmlgen.cpp.
{
  m_t << "<div class=\"compoundTemplParams\">";
}
References OutputGenerator::m_t.
startConstraintDocs()
void HtmlGenerator::startConstraintDocs () override virtual
Implements OutputGenIntf.
Definition at line 3299 of file htmlgen.cpp.
{
  m_t << "<td>&#160;";
}
References OutputGenerator::m_t.
startConstraintList()
void HtmlGenerator::startConstraintList (const QCString & header) override virtual
Implements OutputGenIntf.
Definition at line 3272 of file htmlgen.cpp.
{
  m_t << "<div class=\"typeconstraint\">\n";
  m_t << "<dl><dt><b>" << header << "</b></dt><dd>\n";
  m_t << "<table border=\"0\" cellspacing=\"2\" cellpadding=\"0\">\n";
}
References OutputGenerator::m_t.
startConstraintParam()
void HtmlGenerator::startConstraintParam () override virtual
Implements OutputGenIntf.
Definition at line 3279 of file htmlgen.cpp.
{
  m_t << "<tr><td valign=\"top\"><em>";
}
References OutputGenerator::m_t.
startConstraintType()
void HtmlGenerator::startConstraintType () override virtual
Implements OutputGenIntf.
Definition at line 3289 of file htmlgen.cpp.
{
  m_t << "<td>&#160;:</td><td valign=\"top\"><em>";
}
References OutputGenerator::m_t.
startContents()
void HtmlGenerator::startContents () override virtual
Implements OutputGenIntf.
Definition at line 3045 of file htmlgen.cpp.
{
  m_t << "<div class=\"contents\">\n";
}
References OutputGenerator::m_t.
startDescForItem()
void HtmlGenerator::startDescForItem () inline override virtual
Implements OutputGenIntf.
Definition at line 217 of file htmlgen.h.
{ m_t << "<dd>"; }
References OutputGenerator::m_t.
startDescTable()
void HtmlGenerator::startDescTable (const QCString & title, const bool hasInits) override virtual
Implements OutputGenIntf.
Definition at line 2578 of file htmlgen.cpp.
{
  m_t << "<table class=\"fieldtable\">\n"
      << "<tr><th colspan=\"" << (hasInits?3:2) << "\">" << title << "</th></tr>";
}
References OutputGenerator::m_t.
startDescTableData()
void HtmlGenerator::startDescTableData () override virtual
Implements OutputGenIntf.
Definition at line 2618 of file htmlgen.cpp.
{
  m_t << "<td class=\"fielddoc\">";
}
References OutputGenerator::m_t.
startDescTableInit()
void HtmlGenerator::startDescTableInit () override virtual
Implements OutputGenIntf.
Definition at line 2608 of file htmlgen.cpp.
{
  m_t << "<td class=\"fieldinit\">";
}
References OutputGenerator::m_t.
startDescTableRow()
void HtmlGenerator::startDescTableRow () override virtual
Implements OutputGenIntf.
Definition at line 2588 of file htmlgen.cpp.
{
  m_t << "<tr>";
}
References OutputGenerator::m_t.
startDescTableTitle()
void HtmlGenerator::startDescTableTitle () override virtual
Implements OutputGenIntf.
Definition at line 2598 of file htmlgen.cpp.
{
  m_t << "<td class=\"fieldname\">";
}
References OutputGenerator::m_t.
startDirDepGraph()
void HtmlGenerator::startDirDepGraph () override virtual
Implements OutputGenIntf.
Definition at line 2502 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startDotGraph()
void HtmlGenerator::startDotGraph () override virtual
Implements OutputGenIntf.
Definition at line 2414 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startDoxyAnchor()
void HtmlGenerator::startDoxyAnchor (const QCString & fName, const QCString & manName, const QCString & anchor, const QCString & name, const QCString & args) override virtual
Implements OutputGenIntf.
Definition at line 1678 of file htmlgen.cpp.
{
  m_t << "<a id=\"" << anchor << "\" name=\"" << anchor << "\"></a>";
}
References OutputGenerator::m_t.
startEmphasis()
void HtmlGenerator::startEmphasis () inline override virtual
Implements OutputGenIntf.
Definition at line 213 of file htmlgen.h.
{ m_t << "<em>";  }
References OutputGenerator::m_t.
startExamples()
void HtmlGenerator::startExamples () override virtual
Implements OutputGenIntf.
Definition at line 2628 of file htmlgen.cpp.
{
  m_t << "<dl class=\"section examples\"><dt>";
  docify(theTranslator->trExamples());
  m_t << "</dt>";
}
References docify(), OutputGenerator::m_t, theTranslator, and Translator::trExamples().
startFile()
void HtmlGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id, int hierarchyLevel) override virtual
Implements OutputGenIntf.
Definition at line 1465 of file htmlgen.cpp.
{
  //printf("HtmlGenerator::startFile(%s)\n",qPrint(name));
  m_relPath = relativePathToRoot(name);
  QCString fileName = name;
  addHtmlExtensionIfMissing(fileName);
  m_lastTitle=title;
  startPlainFile(fileName);
  m_codeGen->setFileName(fileName);
  m_codeGen->setRelativePath(m_relPath);
  {
    std::lock_guard<std::mutex> lock(g_indexLock);
    Doxygen::indexList->addIndexFile(fileName);
  }
  m_lastFile = fileName;
  m_t << substituteHtmlKeywords(g_header,convertToHtml(filterTitle(title)),m_relPath);
  m_t << "<!-- " << theTranslator->trGeneratedBy() << " Doxygen "
      << getDoxygenVersion() << " -->\n";
  bool searchEngine = Config_getBool(SEARCHENGINE);
  if (searchEngine /*&& !generateTreeView*/)
  {
    m_t << "<script type=\"text/javascript\">\n";
    m_t << "/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */\n";
    m_t << "var searchBox = new SearchBox(\"searchBox\", \""
        << m_relPath<< "search/\",'" << Doxygen::htmlFileExtension << "');\n";
    m_t << "/* @license-end */\n";
    m_t << "</script>\n";
  }
  if (Config_getBool(HTML_CODE_FOLDING))
  {
    m_t << "<script type=\"text/javascript\">\n";
    m_t << "/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */\n";
    m_t << "$(function() { codefold.init(" << (m_relPath.isEmpty() ? "0" : "1") << "); });\n";
    m_t << "/* @license-end */\n";
    m_t << "</script>\n";
  }
  m_sectionCount=0;
}
References addHtmlExtensionIfMissing(), IndexList::addIndexFile(), Config_getBool, convertToHtml(), OutputGenerator::fileName(), filterTitle(), g_header, g_indexLock, Doxygen::htmlFileExtension, Doxygen::indexList, m_codeGen, m_lastFile, m_lastTitle, m_relPath, m_sectionCount, OutputGenerator::m_t, relativePathToRoot(), startPlainFile(), substituteHtmlKeywords(), theTranslator, and Translator::trGeneratedBy().
startGroupCollaboration()
void HtmlGenerator::startGroupCollaboration () override virtual
Implements OutputGenIntf.
Definition at line 2466 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startGroupHeader()
void HtmlGenerator::startGroupHeader (int extraIndentLevel) override virtual
Implements OutputGenIntf.
Definition at line 1817 of file htmlgen.cpp.
{
  if (extraIndentLevel==2)
  {
    m_t << "<h4 class=\"groupheader\">";
  }
  else if (extraIndentLevel==1)
  {
    m_t << "<h3 class=\"groupheader\">";
  }
  else // extraIndentLevel==0
  {
    m_t << "<h2 class=\"groupheader\">";
  }
}
References OutputGenerator::m_t.
startHeaderSection()
void HtmlGenerator::startHeaderSection () override virtual
Implements OutputGenIntf.
Definition at line 3329 of file htmlgen.cpp.
{
  m_t << "<div class=\"header\">\n";
}
References OutputGenerator::m_t.
startInclDepGraph()
void HtmlGenerator::startInclDepGraph () override virtual
Implements OutputGenIntf.
Definition at line 2448 of file htmlgen.cpp.
{
  startSectionHeader(m_t,m_relPath,m_sectionCount);
}
References m_relPath, m_sectionCount, OutputGenerator::m_t, and startSectionHeader().
startIndent()
void HtmlGenerator::startIndent () override virtual
Implements OutputGenIntf.
Definition at line 2553 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startIndent -->\n";)
  m_t << "<div class=\"memdoc\">\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startIndexItem()
void HtmlGenerator::startIndexItem (const QCString & ref, const QCString & file) override virtual
Implements OutputGenIntf.
Definition at line 1721 of file htmlgen.cpp.
{
  //printf("HtmlGenerator::startIndexItem(%s,%s)\n",ref,f);
  if (!ref.isEmpty() || !f.isEmpty())
  {
    if (!ref.isEmpty())
    {
      m_t << "<a class=\"elRef\" ";
      m_t << externalLinkTarget();
    }
    else
    {
      m_t << "<a class=\"el\" ";
    }
    m_t << "href=\"";
    m_t << externalRef(m_relPath,ref,TRUE);
    if (!f.isEmpty())
    {
      QCString fn=f;
      addHtmlExtensionIfMissing(fn);
      m_t << fn;
    }
    m_t << "\">";
  }
  else
  {
    m_t << "<b>";
  }
}
References addHtmlExtensionIfMissing(), externalLinkTarget(), externalRef(), QCString::isEmpty(), m_relPath, OutputGenerator::m_t, and TRUE.
startIndexKey()
void HtmlGenerator::startIndexKey () override virtual
Implements OutputGenIntf.
Definition at line 2218 of file htmlgen.cpp.
{
  //m_t << "  <tr><td class=\"indexkey\">";
}
startIndexList()
void HtmlGenerator::startIndexList () override virtual
Implements OutputGenIntf.
Definition at line 2208 of file htmlgen.cpp.
{
  m_t << "<table>\n";
}
References OutputGenerator::m_t.
startIndexListItem()
void HtmlGenerator::startIndexListItem () override virtual
Implements OutputGenIntf.
Definition at line 1711 of file htmlgen.cpp.
{
  m_t << "<li>";
}
References OutputGenerator::m_t.
startIndexSection()
void HtmlGenerator::startIndexSection (IndexSection) inline override virtual
Implements OutputGenIntf.
Definition at line 132 of file htmlgen.h.
{}
startIndexValue()
void HtmlGenerator::startIndexValue (bool) override virtual
Implements OutputGenIntf.
Definition at line 2228 of file htmlgen.cpp.
{
  //m_t << "<td class=\"indexvalue\">";
}
startInlineHeader()
void HtmlGenerator::startInlineHeader () override virtual
Implements OutputGenIntf.
Definition at line 3351 of file htmlgen.cpp.
{
  if (m_emptySection)
  {
    m_t << "<table class=\"memberdecls\">\n";
    m_emptySection=FALSE;
  }
  m_t << "<tr><td colspan=\"2\"><h3>";
}
References FALSE, m_emptySection, and OutputGenerator::m_t.
startInlineMemberDoc()
void HtmlGenerator::startInlineMemberDoc () override virtual
Implements OutputGenIntf.
Definition at line 3405 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startInlineMemberDoc -->\n";)
  m_t << "<td class=\"fielddoc\">\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startInlineMemberName()
void HtmlGenerator::startInlineMemberName () override virtual
Implements OutputGenIntf.
Definition at line 3393 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startInlineMemberName -->\n";)
  m_t << "<td class=\"fieldname\">\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startInlineMemberType()
void HtmlGenerator::startInlineMemberType () override virtual
Implements OutputGenIntf.
Definition at line 3381 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startInlineMemberType -->\n";)
  m_t << "<tr><td class=\"fieldtype\">\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startItemList()
void HtmlGenerator::startItemList () inline override virtual
Implements OutputGenIntf.
Definition at line 152 of file htmlgen.h.
{ m_t << "<ul>\n"; }
References OutputGenerator::m_t.
startItemListItem()
void HtmlGenerator::startItemListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 167 of file htmlgen.h.
{ m_t << "<li>"; }
References OutputGenerator::m_t.
startLabels()
void HtmlGenerator::startLabels () override virtual
Implements OutputGenIntf.
Definition at line 3417 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startLabels -->\n";)
  m_t << "<span class=\"mlabels\">";
}
References DBG_HTML, and OutputGenerator::m_t.
startMemberDeclaration()
void HtmlGenerator::startMemberDeclaration () inline override virtual
Implements OutputGenIntf.
Definition at line 204 of file htmlgen.h.
{}
startMemberDescription()
void HtmlGenerator::startMemberDescription (const QCString & anchor, const QCString & inheritId, bool typ) override virtual
Implements OutputGenIntf.
Definition at line 2128 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDescription -->\n")
  if (m_emptySection)
  {
    m_t << "<table class=\"memberdecls\">\n";
    m_emptySection=FALSE;
  }
  m_t << "<tr class=\"memdesc:" << anchor;
  if (!inheritId.isEmpty())
  {
    m_t << " inherit " << inheritId;
  }
  m_t << "\">";
  m_t << "<td class=\"mdescLeft\">&#160;</td>";
  if (typ) m_t << "<td class=\"mdescLeft\">&#160;</td>";
  m_t << "<td class=\"mdescRight\">";
}
References DBG_HTML, FALSE, QCString::isEmpty(), m_emptySection, and OutputGenerator::m_t.
startMemberDoc()
void HtmlGenerator::startMemberDoc (const QCString & clName, const QCString & memName, const QCString & anchor, const QCString & title, int memCount, int memTotal, bool showInline) override virtual
Implements OutputGenIntf.
Definition at line 2248 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDoc -->\n";)
  m_t << "\n<h2 class=\"memtitle\">"
      << "<span class=\"permalink\"><a href=\"#" << anchor << "\">&#9670;&#160;</a></span>";
  docify(title);
  if (memTotal>1)
  {
    m_t << " <span class=\"overload\">[" << memCount << "/" << memTotal <<"]</span>";
  }
  m_t << "</h2>\n";
  m_t << "\n<div class=\"memitem\">\n";
  m_t << "<div class=\"memproto\">\n";
}
References DBG_HTML, docify(), and OutputGenerator::m_t.
startMemberDocList()
void HtmlGenerator::startMemberDocList () override virtual
Implements OutputGenIntf.
Definition at line 2238 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDocList -->\n";)
}
References DBG_HTML, and OutputGenerator::m_t.
startMemberDocName()
void HtmlGenerator::startMemberDocName (bool) override virtual
Implements OutputGenIntf.
Definition at line 2277 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDocName -->\n";)
  m_t << "      <table class=\"memname\">\n";
  m_t << "        <tr>\n";
  m_t << "          <td class=\"memname\">";
}
References DBG_HTML, and OutputGenerator::m_t.
startMemberDocPrefixItem()
void HtmlGenerator::startMemberDocPrefixItem () override virtual
Implements OutputGenIntf.
Definition at line 2265 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDocPrefixItem -->\n";)
  m_t << "<div class=\"memtemplate\">\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startMemberDocSimple()
void HtmlGenerator::startMemberDocSimple (bool isEnum) override virtual
Implements OutputGenIntf.
Definition at line 3366 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberDocSimple -->\n";)
  m_t << "<table class=\"fieldtable\">\n";
  m_t << "<tr><th colspan=\"" << (isEnum?"2":"3") << "\">";
  m_t << (isEnum? theTranslator->trEnumerationValues() :
       theTranslator->trCompoundMembers()) << "</th></tr>\n";
}
References DBG_HTML, OutputGenerator::m_t, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberGroup()
void HtmlGenerator::startMemberGroup () override virtual
Implements OutputGenIntf.
Definition at line 2545 of file htmlgen.cpp.
{
}
startMemberGroupDocs()
void HtmlGenerator::startMemberGroupDocs () override virtual
Implements OutputGenIntf.
Definition at line 2535 of file htmlgen.cpp.
{
  m_t << "<tr><td colspan=\"2\"><div class=\"groupText\">";
}
References OutputGenerator::m_t.
startMemberGroupHeader()
void HtmlGenerator::startMemberGroupHeader (bool) override virtual
Implements OutputGenIntf.
Definition at line 2525 of file htmlgen.cpp.
{
  m_t << "<tr><td colspan=\"2\"><div class=\"groupHeader\">";
}
References OutputGenerator::m_t.
startMemberHeader()
void HtmlGenerator::startMemberHeader (const QCString & anchor, int typ) override virtual
Implements OutputGenIntf.
Definition at line 2170 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberHeader -->\n")
  if (!m_emptySection)
  {
    m_t << "</table>";
    m_emptySection=TRUE;
  }
  if (m_emptySection)
  {
    m_t << "<table class=\"memberdecls\">\n";
    m_emptySection=FALSE;
  }
  m_t << "<tr class=\"heading\"><td colspan=\"" << typ << "\"><h2 class=\"groupheader\">";
  if (!anchor.isEmpty())
  {
    m_t << "<a id=\"" << anchor << "\" name=\"" << anchor << "\"></a>\n";
  }
}
References DBG_HTML, FALSE, QCString::isEmpty(), m_emptySection, OutputGenerator::m_t, and TRUE.
startMemberItem()
void HtmlGenerator::startMemberItem (const QCString & anchor, MemberItemType type, const QCString & inheritId) override virtual
Implements OutputGenIntf.
Definition at line 2053 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberItem() -->\n")
  if (m_emptySection)
  {
    m_t << "<table class=\"memberdecls\">\n";
    m_emptySection=FALSE;
  }
  m_t << "<tr class=\"memitem:" << anchor;
  if (!inheritId.isEmpty())
  {
    m_t << " inherit " << inheritId;
  }
  m_t << "\"";
  if (!anchor.isEmpty())
  {
    m_t << " id=\"r_" << anchor << "\"";
  }
  m_t << ">";
  insertMemberAlignLeft(type, true);
}
References DBG_HTML, FALSE, insertMemberAlignLeft(), QCString::isEmpty(), m_emptySection, OutputGenerator::m_t, and type().
startMemberList()
void HtmlGenerator::startMemberList () override virtual
Implements OutputGenIntf.
Definition at line 2039 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberList -->\n")
}
References DBG_HTML, and OutputGenerator::m_t.
startMemberSections()
void HtmlGenerator::startMemberSections () override virtual
Implements OutputGenIntf.
Definition at line 2153 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberSections -->\n")
  m_emptySection=TRUE; // we postpone writing <table> until we actually
                       // write a row to prevent empty tables, which
                       // are not valid XHTML!
}
References DBG_HTML, m_emptySection, OutputGenerator::m_t, and TRUE.
startMemberSubtitle()
void HtmlGenerator::startMemberSubtitle () override virtual
Implements OutputGenIntf.
Definition at line 2196 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startMemberSubtitle -->\n")
  m_t << "<tr><td class=\"ititle\" colspan=\"2\">";
}
References DBG_HTML, and OutputGenerator::m_t.
startMemberTemplateParams()
void HtmlGenerator::startMemberTemplateParams () override virtual
Implements OutputGenIntf.
Definition at line 2084 of file htmlgen.cpp.
{
}
startPageDoc()
void HtmlGenerator::startPageDoc (const QCString & pageTitle) override virtual
Implements OutputGenIntf.
Definition at line 3055 of file htmlgen.cpp.
{
  m_t << "<div>";
}
References OutputGenerator::m_t.
startPageRef()
void HtmlGenerator::startPageRef () inline override virtual
Implements OutputGenIntf.
Definition at line 247 of file htmlgen.h.
{}
startParagraph()
void HtmlGenerator::startParagraph (const QCString & classDef) override virtual
Implements OutputGenIntf.
Definition at line 1693 of file htmlgen.cpp.
{
  if (!classDef.isEmpty())
    m_t << "\n<p class=\"" << classDef << "\">";
  else
    m_t << "\n<p>";
}
References QCString::isEmpty(), and OutputGenerator::m_t.
startParameterDefVal()
void HtmlGenerator::startParameterDefVal (const char * sep) override virtual
Implements OutputGenIntf.
Definition at line 2365 of file htmlgen.cpp.
{
  m_t << "<span class=\"paramdefsep\">";
  docify(s);
  m_t << "</span><span class=\"paramdefval\">";
}
References docify(), and OutputGenerator::m_t.
startParameterExtra()
void HtmlGenerator::startParameterExtra () override virtual
Implements OutputGenIntf.
Definition at line 2336 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startParameterExtra -->\n";)
}
References DBG_HTML, and OutputGenerator::m_t.
startParameterList()
void HtmlGenerator::startParameterList (bool openBracket) override virtual
Implements OutputGenIntf.
Definition at line 2293 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startParameterList -->\n";)
  m_t << "          <td>";
  if (openBracket) m_t << "(";
  m_t << "</td>\n";
}
References DBG_HTML, and OutputGenerator::m_t.
startParameterName()
void HtmlGenerator::startParameterName (bool) override virtual
Implements OutputGenIntf.
Definition at line 2324 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- startParameterName -->\n";)
  m_t << "          <td class=\"paramname\"><span class=\"paramname\"><em>";
}
References DBG_HTML, and OutputGenerator::m_t.
startParameterType()
void HtmlGenerator::startParameterType (bool first, const QCString & key) override virtual
Implements OutputGenIntf.
Definition at line 2301 of file htmlgen.cpp.
{
  if (first)
  {
    DBG_HTML(m_t << "<!-- startFirstParameterType -->\n";)
    m_t << "          <td class=\"paramtype\">";
  }
  else
  {
    DBG_HTML(m_t << "<!-- startParameterType -->\n";)
    m_t << "        <tr>\n";
    m_t << "          <td class=\"paramkey\">" << key << "</td>\n";
    m_t << "          <td></td>\n";
    m_t << "          <td class=\"paramtype\">";
  }
}
References DBG_HTML, and OutputGenerator::m_t.
startPlainFile()
void HtmlGenerator::startPlainFile (const QCString & name) inline override virtual
Implements OutputGenIntf.
Definition at line 329 of file htmlgen.h.
{ OutputGenerator::startPlainFile(name); }
References OutputGenerator::startPlainFile().
Referenced by startFile(), and writeStyleInfo().
startProjectNumber()
void HtmlGenerator::startProjectNumber () override virtual
Implements OutputGenIntf.
Definition at line 1596 of file htmlgen.cpp.
{
  m_t << "<h3 class=\"version\">";
}
References OutputGenerator::m_t.
startQuickIndices()
void HtmlGenerator::startQuickIndices () inline override virtual
Implements OutputGenIntf.
Definition at line 249 of file htmlgen.h.
{}
startSection()
void HtmlGenerator::startSection (const QCString & lab, const QCString & , SectionType type) override virtual
Implements OutputGenIntf.
Definition at line 1849 of file htmlgen.cpp.
{
  switch(type.level())
  {
    case SectionType::Page:             m_t << "\n\n<h1>"; break;
    case SectionType::Section:          m_t << "\n\n<h2>"; break;
    case SectionType::Subsection:       m_t << "\n\n<h3>"; break;
    case SectionType::Subsubsection:    m_t << "\n\n<h4>"; break;
    case SectionType::Paragraph:        m_t << "\n\n<h5>"; break;
    case SectionType::Subparagraph:     m_t << "\n\n<h6>"; break;
    case SectionType::Subsubparagraph:  m_t << "\n\n<h6>"; break;
    default: ASSERT(0); break;
  }
  m_t << "<a id=\"" << lab << "\" name=\"" << lab << "\"></a>";
}
References ASSERT, OutputGenerator::m_t, SectionType::Page, SectionType::Paragraph, SectionType::Section, SectionType::Subparagraph, SectionType::Subsection, SectionType::Subsubparagraph, SectionType::Subsubsection, and type().
startSmall()
void HtmlGenerator::startSmall () inline override virtual
Implements OutputGenIntf.
Definition at line 235 of file htmlgen.h.
{ m_t << "<small>\n"; }
References OutputGenerator::m_t.
startTextBlock()
void HtmlGenerator::startTextBlock (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 285 of file htmlgen.h.
{ m_t << "<div class=\"textblock\">"; }
References OutputGenerator::m_t.
startTextLink()
void HtmlGenerator::startTextLink (const QCString & file, const QCString & anchor) override virtual
Implements OutputGenIntf.
Definition at line 1800 of file htmlgen.cpp.
{
  m_t << "<a href=\"";
  QCString fn = f;
  addHtmlExtensionIfMissing(fn);
  m_t << createHtmlUrl(m_relPath,"",true,
                       fileName() == Config_getString(HTML_OUTPUT)+"/"+fn,
                       fn,
                       anchor);
  m_t << "\">";
}
References addHtmlExtensionIfMissing(), Config_getString, createHtmlUrl(), OutputGenerator::fileName(), m_relPath, and OutputGenerator::m_t.
startTitle()
void HtmlGenerator::startTitle () inline private
Definition at line 333 of file htmlgen.h.
{ m_t << "<div class=\"title\">"; }
References OutputGenerator::m_t.
Referenced by startTitleHead().
startTitleHead()
void HtmlGenerator::startTitleHead (const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 3334 of file htmlgen.cpp.
{
  m_t << "  <div class=\"headertitle\">";
  startTitle();
}
References OutputGenerator::m_t, and startTitle().
startTypewriter()
void HtmlGenerator::startTypewriter () inline override virtual
Implements OutputGenIntf.
Definition at line 163 of file htmlgen.h.
{ m_t << "<code>"; }
References OutputGenerator::m_t.
type()
OutputType HtmlGenerator::type () const inline override virtual
Implements OutputGenIntf.
Definition at line 121 of file htmlgen.h.
{ return OutputType::Html; }
References Html.
Referenced by endMemberItem(), endSection(), insertMemberAlignLeft(), startMemberItem(), startSection(), and writeLocalToc().
writeAnchor()
void HtmlGenerator::writeAnchor (const QCString & , const QCString & name) inline override virtual
Implements OutputGenIntf.
Definition at line 211 of file htmlgen.h.
                                  { m_t << "<a name=\"" << name <<"\" id=\"" << name << "\"></a>"; }
References OutputGenerator::m_t.
writeChar()
void HtmlGenerator::writeChar (char c) override virtual
Implements OutputGenIntf.
Definition at line 1918 of file htmlgen.cpp.
{
  char cs[2];
  cs[0]=c;
  cs[1]=0;
  docify(cs);
}
References docify().
writeDoc()
void HtmlGenerator::writeDoc (const IDocNodeAST * node, const Definition * ctx, const MemberDef * , int id) override virtual
Implements OutputGenIntf.
Definition at line 2640 of file htmlgen.cpp.
{
  const DocNodeAST *astImpl = dynamic_cast<const DocNodeAST*>(ast);
  if (astImpl)
  {
    m_codeList->setId(id);
    HtmlDocVisitor visitor(m_t,*m_codeList,ctx,fileName());
    std::visit(visitor,astImpl->root);
  }
}
References OutputGenerator::fileName(), m_codeList, OutputGenerator::m_t, and DocNodeAST::root.
writeExternalSearchPage()
void HtmlGenerator::writeExternalSearchPage () static
Definition at line 3162 of file htmlgen.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  QCString dname = Config_getString(HTML_OUTPUT);
  QCString fileName = dname+"/search"+Doxygen::htmlFileExtension;
  std::ofstream f = Portable::openOutputStream(fileName);
  if (f.is_open())
  {
    TextStream t(&f);
    t << substituteHtmlKeywords(g_header,"Search","");
    t << "<!-- " << theTranslator->trGeneratedBy() << " Doxygen "
      << getDoxygenVersion() << " -->\n";
    t << "<script type=\"text/javascript\">\n";
                t << "/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */\n";
                t << "var searchBox = new SearchBox(\"searchBox\", \""
      << "search/\",'" << Doxygen::htmlFileExtension << "');\n";
                t << "/* @license-end */\n";
    t << "</script>\n";
    if (!Config_getBool(DISABLE_INDEX))
    {
      writeDefaultQuickLinks(t,HighlightedItem::Search,QCString(),QCString());
      if (!Config_getBool(HTML_DYNAMIC_MENUS)) // for dynamic menus, menu.js creates this part
      {
        t << "            <input type=\"text\" id=\"MSearchField\" name=\"query\" value=\"\" placeholder=\"" << theTranslator->trSearch() <<
             "\" size=\"20\" accesskey=\"S\" onfocus=\"searchBox.OnSearchFieldFocus(true)\" onblur=\"searchBox.OnSearchFieldFocus(false)\"/>\n";
      }
      t << "            </form>\n";
      t << "          </div><div class=\"right\"></div>\n";
      t << "        </div>\n";
      t << "      </li>\n";
      t << "    </ul>\n";
      t << "  </div>\n";
      t << "</div>\n";
    }
    else
    {
      t << "</div>\n";
    }
    t << writeSplitBarAsString("search","");
    t << "<div class=\"header\">\n";
    t << "  <div class=\"headertitle\">\n";
    t << "    <div class=\"title\">" << theTranslator->trSearchResultsTitle() << "</div>\n";
    t << "  </div>\n";
    t << "</div>\n";
    t << "<div class=\"contents\">\n";
    t << "<div id=\"searchresults\"></div>\n";
    t << "</div>\n";
    if (generateTreeView)
    {
      t << "</div><!-- doc-content -->\n";
    }
    writePageFooter(t,"Search","","");
  }
  f.close();
  QCString scriptName = dname+"/search/search.js";
  f = Portable::openOutputStream(scriptName);
  if (f.is_open())
  {
    TextStream t(&f);
    t << "var searchResultsText=["
      << "\"" << theTranslator->trSearchResults(0) << "\","
      << "\"" << theTranslator->trSearchResults(1) << "\","
      << "\"" << theTranslator->trSearchResults(2) << "\"];\n";
    t << "var serverUrl=\"" << Config_getString(SEARCHENGINE_URL) << "\";\n";
    t << "var tagMap = {\n";
    bool first=TRUE;
    // add search mappings
    const StringVector &extraSearchMappings = Config_getList(EXTRA_SEARCH_MAPPINGS);
    for (const auto &ml : extraSearchMappings)
    {
      QCString mapLine = ml.c_str();
      int eqPos = mapLine.find('=');
      if (eqPos!=-1) // tag command contains a destination
      {
        QCString tagName = mapLine.left(eqPos).stripWhiteSpace();
        QCString destName = mapLine.right(mapLine.length()-eqPos-1).stripWhiteSpace();
        if (!tagName.isEmpty())
        {
          if (!first) t << ",\n";
          t << "  \"" << tagName << "\": \"" << destName << "\"";
          first=FALSE;
        }
      }
    }
    if (!first) t << "\n";
    t << "};\n\n";
    t << ResourceMgr::instance().getAsString("extsearch.js");
    t << "\n";
    t << "$(function() {\n";
    t << "  var query = trim(getURLParameter('query'));\n";
    t << "  if (query) {\n";
    t << "    searchFor(query,0,20);\n";
    t << "  } else {\n";
    t << "    var results = $('#results');\n";
    t << "    results.html('<p>" << theTranslator->trSearchResults(0) << "</p>');\n";
    t << "  }\n";
    t << "});\n";
  }
  else
  {
     err("Failed to open file '%s' for writing...\n",qPrint(scriptName));
  }
}
References Config_getBool, Config_getList, Config_getString, err, FALSE, OutputGenerator::fileName(), QCString::find(), g_header, ResourceMgr::getAsString(), Doxygen::htmlFileExtension, ResourceMgr::instance(), QCString::isEmpty(), QCString::left(), QCString::length(), Portable::openOutputStream(), qPrint(), QCString::right(), Search, QCString::stripWhiteSpace(), substituteHtmlKeywords(), theTranslator, Translator::trGeneratedBy(), Translator::trSearch(), Translator::trSearchResults(), Translator::trSearchResultsTitle(), TRUE, writeDefaultQuickLinks(), writePageFooter(), and writeSplitBarAsString().
Referenced by generateOutput().
writeFooter()
void HtmlGenerator::writeFooter (const QCString & navPath) override virtual
Implements OutputGenIntf.
Definition at line 1586 of file htmlgen.cpp.
{
  writePageFooter(m_t,m_lastTitle,m_relPath,navPath);
}
References m_lastTitle, m_relPath, OutputGenerator::m_t, and writePageFooter().
writeFooterFile()
void HtmlGenerator::writeFooterFile (TextStream & t) static
Definition at line 1457 of file htmlgen.cpp.
{
  t << "<!-- HTML footer for doxygen " << getDoxygenVersion() << "-->\n";
  t << ResourceMgr::instance().getAsString("footer.html");
}
References ResourceMgr::getAsString(), and ResourceMgr::instance().
Referenced by readConfiguration().
writeGraphicalHierarchy()
void HtmlGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable & g) override virtual
Implements OutputGenIntf.
Definition at line 2520 of file htmlgen.cpp.
{
  g.writeGraph(m_t,dir(),fileName());
}
References OutputGenerator::dir(), OutputGenerator::fileName(), OutputGenerator::m_t, and DotGfxHierarchyTable::writeGraph().
writeHeaderFile()
void HtmlGenerator::writeHeaderFile (TextStream & t, const QCString & cssname) static
Definition at line 1451 of file htmlgen.cpp.
{
  t << "<!-- HTML header for doxygen " << getDoxygenVersion() << "-->\n";
  t << ResourceMgr::instance().getAsString("header.html");
}
References ResourceMgr::getAsString(), and ResourceMgr::instance().
Referenced by readConfiguration().
writeInheritedSectionTitle()
void HtmlGenerator::writeInheritedSectionTitle (const QCString & id, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & title, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 3437 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- writeInheritedSectionTitle -->\n";)
  QCString a = anchor;
  if (!a.isEmpty()) a.prepend("#");
  QCString classLink = QCString("<a class=\"el\" ");
  if (!ref.isEmpty())
  {
    classLink+= externalLinkTarget();
    classLink += " href=\"";
    classLink+= externalRef(m_relPath,ref,TRUE);
  }
  else
  {
    classLink += "href=\"";
    classLink+=m_relPath;
  }
  QCString fn = file;
  addHtmlExtensionIfMissing(fn);
  classLink=classLink+fn+a;
  classLink+=QCString("\">")+convertToHtml(name,FALSE)+"</a>";
  m_t << "<tr class=\"inherit_header " << id << "\">"
    << "<td colspan=\"2\" onclick=\"javascript:dynsection.toggleInherit('" << id << "')\">"
    << "<img src=\"" << m_relPath << "closed.png\" alt=\"-\"/>&#160;"
    << theTranslator->trInheritedFrom(convertToHtml(title,FALSE),classLink)
    << "</td></tr>\n";
}
References addHtmlExtensionIfMissing(), convertToHtml(), DBG_HTML, externalLinkTarget(), externalRef(), FALSE, QCString::isEmpty(), m_relPath, OutputGenerator::m_t, QCString::prepend(), theTranslator, Translator::trInheritedFrom(), and TRUE.
writeLabel()
void HtmlGenerator::writeLabel (const QCString & l, bool isLast) override virtual
Implements OutputGenIntf.
Definition at line 3423 of file htmlgen.cpp.
{
  DBG_HTML(m_t << "<!-- writeLabel(" << l << ") -->\n";)
  //m_t << "<tt>[" << l << "]</tt>";
  //if (!isLast) m_t << ", ";
  m_t << "<span class=\"mlabel\">" << l << "</span>";
}
References DBG_HTML, and OutputGenerator::m_t.
writeLatexSpacing()
void HtmlGenerator::writeLatexSpacing () inline override virtual
Implements OutputGenIntf.
Definition at line 230 of file htmlgen.h.
{}
writeLocalToc()
void HtmlGenerator::writeLocalToc (const SectionRefs & sr, const LocalToc & lt) override virtual
Implements OutputGenIntf.
Definition at line 3516 of file htmlgen.cpp.
{
  if (localToc.isHtmlEnabled())
  {
    int level=0;
    int indent=0;
    auto writeIndent = [&]()                     { for (int i=0;i<indent*2;i++) m_t << " ";      };
    auto incIndent   = [&](const QCString &text) { writeIndent(); m_t << text << "\n"; indent++; };
    auto decIndent   = [&](const QCString &text) { indent--; writeIndent(); m_t << text << "\n"; };
    m_t << "<div class=\"toc\">";
    m_t << "<h3>" << theTranslator->trRTFTableOfContents() << "</h3>\n";
    int maxLevel = localToc.htmlLevel();
    char cs[2];
    cs[1]='\0';
    BoolVector inLi(maxLevel+1,false);
    for (const SectionInfo *si : sectionRefs)
    {
      //printf("Section: label=%s type=%d isSection()=%d\n",qPrint(si->label()),si->type(),isSection(si->type()));
      SectionType type = si->type();
      if (type.isSection())
      {
        //printf("  level=%d title=%s maxLevel=%d\n",level,qPrint(si->title()),maxLevel);
        int nextLevel = type.level();
        if (nextLevel>level)
        {
          for (int l=level;l<nextLevel;l++)
          {
            if (l < maxLevel)
            {
              incIndent("<ul>");
              cs[0]=static_cast<char>('0'+l+1);
              const char *empty = (l!=nextLevel-1) ? " empty" : "";
              incIndent("<li class=\"level" + QCString(cs) + empty + "\">");
            }
          }
        }
        else if (nextLevel<level)
        {
          for (int l=level;l>nextLevel;l--)
          {
            if (l <= maxLevel) decIndent("</li>");
            inLi[l] = false;
            if (l <= maxLevel) decIndent("</ul>");
          }
        }
        if (nextLevel <= maxLevel)
        {
          if (inLi[nextLevel] || level>nextLevel)
          {
            decIndent("</li>");
            cs[0]=static_cast<char>('0'+nextLevel);
            incIndent("<li class=\"level" + QCString(cs) + "\">");
          }
          QCString titleDoc = si->title();
          QCString label = si->label();
          if (titleDoc.isEmpty()) titleDoc = label;
          writeIndent();
          m_t  << "<a href=\"#"+label+"\">"
               << convertToHtml(filterTitle(titleDoc))
               << "</a>\n";
          inLi[nextLevel]=true;
          level = nextLevel;
        }
      }
    }
    if (level > maxLevel) level = maxLevel;
    while (level>0)
    {
      decIndent("</li>");
      decIndent("</ul>");
      level--;
    }
    m_t << "</div>\n";
  }
}
References convertToHtml(), filterTitle(), LocalToc::htmlLevel(), QCString::isEmpty(), LocalToc::isHtmlEnabled(), OutputGenerator::m_t, theTranslator, Translator::trRTFTableOfContents(), type(), and writeIndent().
writeLogo()
void HtmlGenerator::writeLogo () override virtual
Implements OutputGenIntf.
Definition at line 1575 of file htmlgen.cpp.
{
  m_t << writeLogoAsString(m_relPath);
}
References m_relPath, OutputGenerator::m_t, and writeLogoAsString().
writeLogoAsString()
QCString HtmlGenerator::writeLogoAsString (const QCString & path) static
Definition at line 1544 of file htmlgen.cpp.
{
  QCString result;
  switch (Config_getEnum(TIMESTAMP))
  {
    case TIMESTAMP_t::YES:
    case TIMESTAMP_t::DATETIME:
      result += theTranslator->trGeneratedAt(
                 dateToString(DateTimeType::DateTime),
                 Config_getString(PROJECT_NAME)
                );
      break;
    case TIMESTAMP_t::DATE:
      result += theTranslator->trGeneratedAt(
                 dateToString(DateTimeType::Date),
                 Config_getString(PROJECT_NAME)
                );
      break;
    case TIMESTAMP_t::NO:
      result += theTranslator->trGeneratedBy();
      break;
  }
  result += "&#160;\n<a href=\"https://www.doxygen.org/index.html\">\n"
            "<img class=\"footer\" src=\"";
  result += path;
  result += "doxygen.svg\" width=\"104\" height=\"31\" alt=\"doxygen\"/></a> ";
  result += getDoxygenVersion();
  result += " ";
  return result;
}
References Config_getEnum, Config_getString, Date, DateTime, dateToString(), theTranslator, Translator::trGeneratedAt(), and Translator::trGeneratedBy().
Referenced by writeLogo(), and writeSearchPage().
writeNavigationPath()
void HtmlGenerator::writeNavigationPath (const QCString & s) override virtual
Implements OutputGenIntf.
Definition at line 3040 of file htmlgen.cpp.
{
  m_t << substitute(s,"$relpath^",m_relPath);
}
References m_relPath, OutputGenerator::m_t, and substitute().
writeNonBreakableSpace()
void HtmlGenerator::writeNonBreakableSpace (int n) override virtual
Implements OutputGenIntf.
Definition at line 2570 of file htmlgen.cpp.
{
  for (int i=0; i<n; i++)
  {
    m_t << "&#160;";
  }
}
References OutputGenerator::m_t.
writeObjectLink()
void HtmlGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1776 of file htmlgen.cpp.
{
  if (!ref.isEmpty())
  {
    m_t << "<a class=\"elRef\" ";
    m_t << externalLinkTarget();
  }
  else
  {
    m_t << "<a class=\"el\" ";
  }
  m_t << "href=\"";
  QCString fn = f;
  addHtmlExtensionIfMissing(fn);
  m_t << createHtmlUrl(m_relPath,ref,true,
                       fileName() == Config_getString(HTML_OUTPUT)+"/"+fn,
                       fn,
                       anchor);
  m_t << "\">";
  docify(name);
  m_t << "</a>";
}
References addHtmlExtensionIfMissing(), Config_getString, createHtmlUrl(), docify(), externalLinkTarget(), OutputGenerator::fileName(), QCString::isEmpty(), m_relPath, and OutputGenerator::m_t.
writePageFooter()
void HtmlGenerator::writePageFooter (TextStream & t, const QCString & lastTitle, const QCString & relPath, const QCString & navPath) static private
Definition at line 1580 of file htmlgen.cpp.
{
  t << substituteHtmlKeywords(g_footer,convertToHtml(lastTitle),relPath,navPath);
}
References convertToHtml(), g_footer, and substituteHtmlKeywords().
Referenced by writeExternalSearchPage(), writeFooter(), and writeSearchPage().
writePageLink()
void HtmlGenerator::writePageLink (const QCString & , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 134 of file htmlgen.h.
{}
writeQuickLinks()
void HtmlGenerator::writeQuickLinks (HighlightedItem hli, const QCString & file) override virtual
Implements OutputGenIntf.
Definition at line 3065 of file htmlgen.cpp.
{
  writeDefaultQuickLinks(m_t,hli,file,m_relPath);
}
References m_relPath, OutputGenerator::m_t, and writeDefaultQuickLinks().
writeRuler()
void HtmlGenerator::writeRuler () inline override virtual
Implements OutputGenIntf.
Definition at line 210 of file htmlgen.h.
{ m_t << "<hr/>"; }
References OutputGenerator::m_t.
writeSearchData()
void HtmlGenerator::writeSearchData (const QCString & dir) static
Definition at line 1329 of file htmlgen.cpp.
{
  //bool serverBasedSearch = Config_getBool(SERVER_BASED_SEARCH);
  //writeImgData(dname,serverBasedSearch ? search_server_data : search_client_data);
  ResourceMgr &mgr = ResourceMgr::instance();
  // server side search resources
  mgr.copyResource("mag.svg",dname);
  mgr.copyResource("mag_d.svg",dname);
  Doxygen::indexList->addImageFile("search/mag.svg");
  Doxygen::indexList->addImageFile("search/mag_d.svg");
  // client side search resources
  mgr.copyResource("close.svg",dname);
  Doxygen::indexList->addImageFile("search/close.svg");
  mgr.copyResource("mag_sel.svg",dname);
  mgr.copyResource("mag_seld.svg",dname);
  Doxygen::indexList->addImageFile("search/mag_sel.svg");
  Doxygen::indexList->addImageFile("search/mag_seld.svg");
  QCString searchDirName = dname;
  std::ofstream f = Portable::openOutputStream(searchDirName+"/search.css");
  if (f.is_open())
  {
    TextStream t(&f);
    QCString searchCss;
    // the position of the search box depends on a number of settings.
    // Insert the right piece of CSS code depending on which options are selected
    if (Config_getBool(DISABLE_INDEX))
    {
      if (Config_getBool(GENERATE_TREEVIEW) && Config_getBool(FULL_SIDEBAR))
      {
        searchCss = mgr.getAsString("search_sidebar.css"); // we have a full height side bar
      }
      else if (Config_getBool(HTML_COLORSTYLE)==HTML_COLORSTYLE_t::TOGGLE)
      {
        searchCss = mgr.getAsString("search_nomenu_toggle.css"); // we have no tabs but do have a darkmode button
      }
      else
      {
        searchCss = mgr.getAsString("search_nomenu.css"); // we have no tabs and no darkmode button
      }
    }
    else if (!Config_getBool(HTML_DYNAMIC_MENUS))
    {
      searchCss = mgr.getAsString("search_fixedtabs.css"); // we have tabs, but they are static
    }
    else
    {
      searchCss = mgr.getAsString("search.css"); // default case with a dynamic menu bar
    }
    // and then add the option independent part of the styling
    searchCss += mgr.getAsString("search_common.css");
    searchCss = substitute(searchCss,"$doxygenversion",getDoxygenVersion());
    t << replaceVariables(searchCss);
    Doxygen::indexList->addStyleSheetFile("search/search.css");
  }
}
References IndexList::addImageFile(), IndexList::addStyleSheetFile(), Config_getBool, ResourceMgr::copyResource(), ResourceMgr::getAsString(), Doxygen::indexList, ResourceMgr::instance(), Portable::openOutputStream(), replaceVariables(), and substitute().
Referenced by generateOutput().
writeSearchInfo()
void HtmlGenerator::writeSearchInfo () override virtual
Implements OutputGenIntf.
Definition at line 1538 of file htmlgen.cpp.
{
  writeSearchInfoStatic(m_t,m_relPath);
}
References m_relPath, OutputGenerator::m_t, and writeSearchInfoStatic().
writeSearchInfoStatic()
void HtmlGenerator::writeSearchInfoStatic (TextStream & t, const QCString & relPath) static
Definition at line 1508 of file htmlgen.cpp.
{
  bool searchEngine      = Config_getBool(SEARCHENGINE);
  bool serverBasedSearch = Config_getBool(SERVER_BASED_SEARCH);
  if (searchEngine && !serverBasedSearch)
  {
    t << "<!-- window showing the filter options -->\n";
    t << "<div id=\"MSearchSelectWindow\"\n";
    t << "     onmouseover=\"return searchBox.OnSearchSelectShow()\"\n";
    t << "     onmouseout=\"return searchBox.OnSearchSelectHide()\"\n";
    t << "     onkeydown=\"return searchBox.OnSearchSelectKey(event)\">\n";
    t << "</div>\n";
    t << "\n";
    t << "<!-- iframe showing the search results (closed by default) -->\n";
    t << "<div id=\"MSearchResultsWindow\">\n";
    t << "<div id=\"MSearchResults\">\n";
    t << "<div class=\"SRPage\">\n";
    t << "<div id=\"SRIndex\">\n";
    t << "<div id=\"SRResults\"></div>\n"; // here the results will be inserted
    t << "<div class=\"SRStatus\" id=\"Loading\">"   << theTranslator->trLoading()   << "</div>\n";
    t << "<div class=\"SRStatus\" id=\"Searching\">" << theTranslator->trSearching() << "</div>\n";
    t << "<div class=\"SRStatus\" id=\"NoMatches\">" << theTranslator->trNoMatches() << "</div>\n";
    t << "</div>\n"; // SRIndex
    t << "</div>\n"; // SRPage
    t << "</div>\n"; // MSearchResults
    t << "</div>\n"; // MSearchResultsWindow
    t << "\n";
  }
}
References Config_getBool, theTranslator, Translator::trLoading(), Translator::trNoMatches(), and Translator::trSearching().
Referenced by writeSearchInfo().
writeSearchPage()
void HtmlGenerator::writeSearchPage () static
Definition at line 3071 of file htmlgen.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  bool disableIndex = Config_getBool(DISABLE_INDEX);
  QCString projectName = Config_getString(PROJECT_NAME);
  QCString htmlOutput = Config_getString(HTML_OUTPUT);
  // OPENSEARCH_PROVIDER {
  QCString configFileName = htmlOutput+"/search_config.php";
  std::ofstream f = Portable::openOutputStream(configFileName);
  if (f.is_open())
  {
    TextStream t(&f);
    t << "<?php\n\n";
    t << "$config = array(\n";
    t << "  'PROJECT_NAME' => \"" << convertToHtml(projectName) << "\",\n";
    t << "  'GENERATE_TREEVIEW' => " << (generateTreeView?"true":"false") << ",\n";
    t << "  'DISABLE_INDEX' => " << (disableIndex?"true":"false") << ",\n";
    t << ");\n\n";
    t << "$translator = array(\n";
    t << "  'search_results_title' => \"" << theTranslator->trSearchResultsTitle() << "\",\n";
    t << "  'search_results' => array(\n";
    t << "    0 => \"" << theTranslator->trSearchResults(0) << "\",\n";
    t << "    1 => \"" << theTranslator->trSearchResults(1) << "\",\n";
    t << "    2 => \"" << substitute(theTranslator->trSearchResults(2), "$", "\\$") << "\",\n";
    t << "  ),\n";
    t << "  'search_matches' => \"" << theTranslator->trSearchMatches() << "\",\n";
    t << "  'search' => \"" << theTranslator->trSearch() << "\",\n";
    t << "  'split_bar' => \"" << substitute(substitute(writeSplitBarAsString("search",""), "\"","\\\""), "\n","\\n") << "\",\n";
    t << "  'logo' => \"" << substitute(substitute(writeLogoAsString(""), "\"","\\\""), "\n","\\n") << "\",\n";
    t << ");\n\n";
    t << "?>\n";
  }
  f.close();
  ResourceMgr::instance().copyResource("search_functions.php",htmlOutput);
  ResourceMgr::instance().copyResource("search_opensearch.php",htmlOutput);
  // OPENSEARCH_PROVIDER }
  QCString fileName = htmlOutput+"/search.php";
  f = Portable::openOutputStream(fileName);
  if (f.is_open())
  {
    TextStream t(&f);
    t << substituteHtmlKeywords(g_header,"Search","");
    t << "<!-- " << theTranslator->trGeneratedBy() << " Doxygen "
      << getDoxygenVersion() << " -->\n";
    t << "<script type=\"text/javascript\">\n";
                t << "/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */\n";
                t << "var searchBox = new SearchBox(\"searchBox\", \""
      << "search/\",'" << Doxygen::htmlFileExtension << "');\n";
                t << "/* @license-end */\n";
    t << "</script>\n";
    if (!Config_getBool(DISABLE_INDEX))
    {
      writeDefaultQuickLinks(t,HighlightedItem::Search,QCString(),QCString());
    }
    else
    {
      t << "</div>\n";
    }
    t << "<?php\n";
    t << "require_once \"search_functions.php\";\n";
    t << "main();\n";
    t << "?>\n";
    // Write empty navigation path, to make footer connect properly
    if (generateTreeView)
    {
      t << "</div><!-- doc-content -->\n";
    }
    writePageFooter(t,"Search","","");
  }
  f.close();
  QCString scriptName = htmlOutput+"/search/search.js";
  f = Portable::openOutputStream(scriptName);
  if (f.is_open())
  {
    TextStream t(&f);
    t << ResourceMgr::instance().getAsString("extsearch.js");
  }
  else
  {
     err("Failed to open file '%s' for writing...\n",qPrint(scriptName));
  }
}
References Config_getBool, Config_getString, convertToHtml(), ResourceMgr::copyResource(), err, OutputGenerator::fileName(), g_header, ResourceMgr::getAsString(), Doxygen::htmlFileExtension, ResourceMgr::instance(), Portable::openOutputStream(), qPrint(), Search, substitute(), substituteHtmlKeywords(), theTranslator, Translator::trGeneratedBy(), Translator::trSearch(), Translator::trSearchMatches(), Translator::trSearchResults(), Translator::trSearchResultsTitle(), writeDefaultQuickLinks(), writeLogoAsString(), writePageFooter(), and writeSplitBarAsString().
Referenced by generateOutput().
writeSplitBar()
void HtmlGenerator::writeSplitBar (const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 3035 of file htmlgen.cpp.
{
  m_t << writeSplitBarAsString(name,m_relPath);
}
References m_relPath, OutputGenerator::m_t, and writeSplitBarAsString().
writeSplitBarAsString()
QCString HtmlGenerator::writeSplitBarAsString (const QCString & name, const QCString & relpath) static
Definition at line 2991 of file htmlgen.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  QCString result;
  // write split bar
  if (generateTreeView)
  {
    QCString fn = name;
    addHtmlExtensionIfMissing(fn);
    if (!Config_getBool(DISABLE_INDEX) || !Config_getBool(FULL_SIDEBAR))
    {
      result += QCString(
        "<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n");
    }
    result+= QCString(
     "  <div id=\"nav-tree\">\n"
     "    <div id=\"nav-tree-contents\">\n"
     "      <div id=\"nav-sync\" class=\"sync\"></div>\n"
     "    </div>\n"
     "  </div>\n"
     "  <div id=\"splitbar\" style=\"-moz-user-select:none;\" \n"
     "       class=\"ui-resizable-handle\">\n"
     "  </div>\n"
     "</div>\n"
     "<script type=\"text/javascript\">\n"
     "/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */\n"
     "$(function(){initNavTree('") + fn +
     QCString("','") + relpath +
     QCString("'); initResizable(true); });\n"
     "/* @license-end */\n"
     "</script>\n"
     "<div id=\"doc-content\">\n");
  }
  else
  {
     result += "<script type=\"text/javascript\">\n"
     "/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */\n"
     "$(function(){ initResizable(false); });\n"
     "/* @license-end */\n"
     "</script>\n";
  }
  return result;
}
References addHtmlExtensionIfMissing(), and Config_getBool.
Referenced by writeExternalSearchPage(), writeSearchPage(), and writeSplitBar().
writeStartAnnoItem()
void HtmlGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1764 of file htmlgen.cpp.
{
  m_t << "<li>";
  if (!path.isEmpty()) docify(path);
  QCString fn = f;
  addHtmlExtensionIfMissing(fn);
  m_t << "<a class=\"el\" href=\"" << fn << "\">";
  docify(name);
  m_t << "</a> ";
}
References addHtmlExtensionIfMissing(), docify(), QCString::isEmpty(), and OutputGenerator::m_t.
writeString()
void HtmlGenerator::writeString (const QCString & text) override virtual
Implements OutputGenIntf.
Definition at line 1706 of file htmlgen.cpp.
{
  m_t << text;
}
References OutputGenerator::m_t.
writeStyleInfo()
void HtmlGenerator::writeStyleInfo (int part) override virtual
Implements OutputGenIntf.
Definition at line 1606 of file htmlgen.cpp.
{
  //printf("writeStyleInfo(%d)\n",part);
  if (part==0)
  {
    if (Config_getString(HTML_STYLESHEET).isEmpty()) // write default style sheet
    {
      //printf("write doxygen.css\n");
      startPlainFile("doxygen.css");
      writeDefaultStyleSheet(m_t);
      endPlainFile();
      Doxygen::indexList->addStyleSheetFile("doxygen.css");
    }
    else // write user defined style sheet
    {
      QCString cssName=Config_getString(HTML_STYLESHEET);
      if (!cssName.startsWith("http:") && !cssName.startsWith("https:"))
      {
        FileInfo cssfi(cssName.str());
        if (!cssfi.exists() || !cssfi.isFile() || !cssfi.isReadable())
        {
          err("style sheet %s does not exist or is not readable!\n", qPrint(Config_getString(HTML_STYLESHEET)));
        }
        else
        {
          // convert style sheet to string
          QCString fileStr = fileToString(cssName);
          // write the string into the output dir
          startPlainFile(cssfi.fileName().c_str());
          m_t << fileStr;
          endPlainFile();
        }
        Doxygen::indexList->addStyleSheetFile(cssfi.fileName().c_str());
      }
    }
    const StringVector &extraCssFiles = Config_getList(HTML_EXTRA_STYLESHEET);
    for (const auto &fileName : extraCssFiles)
    {
      if (!fileName.empty())
      {
        FileInfo fi(fileName);
        if (fi.exists())
        {
          Doxygen::indexList->addStyleSheetFile(fi.fileName().c_str());
        }
      }
    }
    Doxygen::indexList->addStyleSheetFile("jquery.js");
    Doxygen::indexList->addStyleSheetFile("resize.js");
    Doxygen::indexList->addStyleSheetFile("navtree.css");
    Doxygen::indexList->addStyleSheetFile("dynsections.js");
    if (Config_getEnum(HTML_COLORSTYLE)==HTML_COLORSTYLE_t::TOGGLE)
    {
      Doxygen::indexList->addStyleSheetFile("darkmode_toggle.js");
    }
    if (Config_getBool(INTERACTIVE_SVG))
    {
      Doxygen::indexList->addStyleSheetFile("svg.min.js");
    }
    if (!Config_getBool(DISABLE_INDEX) && Config_getBool(HTML_DYNAMIC_MENUS))
    {
      Doxygen::indexList->addStyleSheetFile("menu.js");
      Doxygen::indexList->addStyleSheetFile("menudata.js");
    }
  }
}
References IndexList::addStyleSheetFile(), Config_getBool, Config_getEnum, Config_getList, Config_getString, endPlainFile(), err, FileInfo::exists(), FileInfo::fileName(), OutputGenerator::fileName(), fileToString(), Doxygen::indexList, FileInfo::isFile(), FileInfo::isReadable(), OutputGenerator::m_t, qPrint(), startPlainFile(), QCString::startsWith(), QCString::str(), and writeDefaultStyleSheet().
writeStyleSheetFile()
void HtmlGenerator::writeStyleSheetFile (TextStream & t) static
Definition at line 1445 of file htmlgen.cpp.
{
  fillColorStyleMaps();
  writeDefaultStyleSheet(t);
}
References fillColorStyleMaps(), and writeDefaultStyleSheet().
Referenced by readConfiguration().
writeSummaryLink()
void HtmlGenerator::writeSummaryLink (const QCString & file, const QCString & anchor, const QCString & title, bool first) override virtual
Implements OutputGenIntf.
Definition at line 3468 of file htmlgen.cpp.
{
  if (first)
  {
    m_t << "  <div class=\"summary\">\n";
  }
  else
  {
    m_t << " &#124;\n";
  }
  m_t << "<a href=\"";
  if (!file.isEmpty())
  {
    QCString fn = file;
    addHtmlExtensionIfMissing(fn);
    m_t << m_relPath << fn;
  }
  else if (!anchor.isEmpty())
  {
    m_t << "#";
    m_t << anchor;
  }
  m_t << "\">";
  m_t << title;
  m_t << "</a>";
}
References addHtmlExtensionIfMissing(), QCString::isEmpty(), m_relPath, and OutputGenerator::m_t.
writeSynopsis()
void HtmlGenerator::writeSynopsis () inline override virtual
Implements OutputGenIntf.
Definition at line 244 of file htmlgen.h.
{}
writeTabData()
void HtmlGenerator::writeTabData () static
Additional initialization after indices have been created.
Definition at line 1291 of file htmlgen.cpp.
{
  Doxygen::indexList->addStyleSheetFile("tabs.css");
  QCString dname=Config_getString(HTML_OUTPUT);
  ResourceMgr &mgr = ResourceMgr::instance();
  //writeColoredImgData(dname,colored_tab_data);
  mgr.copyResource("tab_a.lum",dname);  // active, light mode
  mgr.copyResource("tab_b.lum",dname);  // normal, light mode
  mgr.copyResource("tab_h.lum",dname);  // highlight, light mode
  mgr.copyResource("tab_s.lum",dname);  // separator, light mode
  mgr.copyResource("tab_ad.lum",dname); // active, dark mode
  mgr.copyResource("tab_bd.lum",dname); // normal, dark mode
  mgr.copyResource("tab_hd.lum",dname); // highlight, dark mode
  mgr.copyResource("tab_sd.lum",dname); // separator, light mode
  mgr.copyResource("nav_h.lum",dname);  // header gradient, light mode
  mgr.copyResource("nav_hd.lum",dname); // header gradient, dark mode
  mgr.copyResource("nav_f.lum",dname); // member definition header, light mode
  mgr.copyResource("nav_fd.lum",dname); // member definition header, dark mode
  mgr.copyResource("bc_s.luma",dname); // breadcrumb separator, light mode
  mgr.copyResource("bc_sd.luma",dname); // breadcrumb separator, dark mode
  mgr.copyResource("doxygen.svg",dname);
  Doxygen::indexList->addImageFile("doxygen.svg");
  mgr.copyResource("closed.luma",dname);
  mgr.copyResource("open.luma",dname);
  mgr.copyResource("sync_on.luma",dname);
  mgr.copyResource("sync_off.luma",dname);
  mgr.copyResource("nav_g.png",dname);
  Doxygen::indexList->addImageFile("nav_g.png");
  mgr.copyResource("plus.svg",dname);
  Doxygen::indexList->addImageFile("plus.svg");
  mgr.copyResource("minus.svg",dname);
  Doxygen::indexList->addImageFile("minus.svg");
  mgr.copyResource("plusd.svg",dname);
  Doxygen::indexList->addImageFile("plusd.svg");
  mgr.copyResource("minusd.svg",dname);
  Doxygen::indexList->addImageFile("minusd.svg");
}
References IndexList::addImageFile(), IndexList::addStyleSheetFile(), Config_getString, ResourceMgr::copyResource(), Doxygen::indexList, and ResourceMgr::instance().
Referenced by generateOutput().
Member Data Documentation
m_codeGen
HtmlCodeGenerator* HtmlGenerator::m_codeGen = nullptr private
Definition at line 344 of file htmlgen.h.
Referenced by addCodeGen(), HtmlGenerator(), HtmlGenerator(), operator=(), and startFile().
m_codeList
std::unique_ptr<OutputCodeList> HtmlGenerator::m_codeList private
Definition at line 343 of file htmlgen.h.
Referenced by HtmlGenerator(), HtmlGenerator(), operator=(), and writeDoc().
m_emptySection
bool HtmlGenerator::m_emptySection = false private
Definition at line 342 of file htmlgen.h.
Referenced by endMemberSections(), HtmlGenerator(), operator=(), startInlineHeader(), startMemberDescription(), startMemberHeader(), startMemberItem(), and startMemberSections().
m_lastFile
QCString HtmlGenerator::m_lastFile private
Definition at line 339 of file htmlgen.h.
Referenced by HtmlGenerator(), operator=(), and startFile().
m_lastTitle
QCString HtmlGenerator::m_lastTitle private
Definition at line 338 of file htmlgen.h.
Referenced by HtmlGenerator(), operator=(), startFile(), and writeFooter().
m_relPath
QCString HtmlGenerator::m_relPath private
Definition at line 340 of file htmlgen.h.
Referenced by endCallGraph(), endClassDiagram(), endDirDepGraph(), endDotGraph(), endGroupCollaboration(), endInclDepGraph(), HtmlGenerator(), operator=(), startCallGraph(), startClassDiagram(), startDirDepGraph(), startDotGraph(), startFile(), startGroupCollaboration(), startInclDepGraph(), startIndexItem(), startTextLink(), writeFooter(), writeInheritedSectionTitle(), writeLogo(), writeNavigationPath(), writeObjectLink(), writeQuickLinks(), writeSearchInfo(), writeSplitBar(), and writeSummaryLink().
m_sectionCount
int HtmlGenerator::m_sectionCount = 0 private
Definition at line 341 of file htmlgen.h.
Referenced by endCallGraph(), endClassDiagram(), endDirDepGraph(), endDotGraph(), endGroupCollaboration(), endInclDepGraph(), HtmlGenerator(), operator=(), startCallGraph(), startClassDiagram(), startDirDepGraph(), startDotGraph(), startFile(), startGroupCollaboration(), and startInclDepGraph().
The documentation for this class was generated from the following files:
src/htmlgen.h
src/htmlgen.cpp