Doxygen: TranslatorPolish Class Reference
TranslatorPolish Class Reference
#include <src/translator_pl.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description.
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool single) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
QCString trDesignUnitDocumentation () override
VHDL design unit documentation.
QCString trConcept (bool first_capital, bool singular) override
C++20 concept.
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
QCString trPackageList () override
QCString trFlowchart () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
QCString trCopyToClipboard () override
QCString trImportant () override
Public Member Functions inherited from Translator
virtual QCString updateNeededMessage ()
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Detailed Description
Definition at line 27 of file translator_pl.h.
Member Function Documentation
getLanguageString()
QCString TranslatorPolish::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 63 of file translator_pl.h.
    {
      return "0x415 Polish";
    }
idLanguage()
QCString TranslatorPolish::idLanguage () inline override virtual
Used for identification of the language. May resemble the string returned by latexBabelPackage(), but it is not used for the same purpose. The identification should not be translated. It should be replaced by the name of the language in English (e.g. Czech, Japanese, Russian, etc.). It should be equal to the identification in language.h.
Implements Translator.
Definition at line 40 of file translator_pl.h.
    { return "polish"; }
latexLanguageSupportCommand()
QCString TranslatorPolish::latexLanguageSupportCommand () inline override virtual
Used to get the command(s) for the language support. This method was designed for languages which do not prefer babel package. If this methods returns empty string, then the latexBabelPackage() method is used to generate the command for using the babel package.
Implements Translator.
Definition at line 47 of file translator_pl.h.
    {
      return "\\usepackage[polish]{babel}\n"
             "\\let\\lll\\undefined\n"; /* to overcome problems with the <<<
                                           symbol as defined in the amssymb
                                           package, and the Polish symbol
                                           "Latin Small Letter L With Stroke"
                                           &lstrok; or &#322; or &#x0142;
                                           We take the amssymb symbol as leading.
                                         */
    }
trAdditionalInheritedMembers()
QCString TranslatorPolish::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1825 of file translator_pl.h.
    { return "Dodatkowe dziedziczone skadowe"; }
trAll()
QCString TranslatorPolish::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1337 of file translator_pl.h.
    {
      return "Wszystko";
    }
trAndMore()
QCString TranslatorPolish::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1804 of file translator_pl.h.
    { return "i "+number+" wicej..."; }
trAttention()
QCString TranslatorPolish::trAttention () inline override virtual
Implements Translator.
Definition at line 951 of file translator_pl.h.
    {
      return "Uwaga";
    }
trAuthor()
QCString TranslatorPolish::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1214 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "autor", "zy");
    }
References Translator::createNoun().
trBug()
QCString TranslatorPolish::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1113 of file translator_pl.h.
    {
      return "Bd";
    }
trBugList()
QCString TranslatorPolish::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1118 of file translator_pl.h.
    {
      return "Lista bdw";
    }
trCallerGraph()
QCString TranslatorPolish::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1462 of file translator_pl.h.
    {
      return "Oto graf wywoywa tej funkcji:";
    }
trCallGraph()
QCString TranslatorPolish::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1342 of file translator_pl.h.
    {
      return "Oto graf wywoa dla tej funkcji:";
    }
trCiteReferences()
QCString TranslatorPolish::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1780 of file translator_pl.h.
    { return "Odwoania do literatury"; }
trClass()
QCString TranslatorPolish::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1149 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "klas", "y", "a");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trClassDiagram()
QCString TranslatorPolish::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 506 of file translator_pl.h.
    {
      return "Diagram dziedziczenia dla "+clName;
    }
trClassDocumentation()
QCString TranslatorPolish::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 387 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacja struktur danych";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentacja klas";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorPolish::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1076 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktury Danych";
      }
      else
      {
        return "Klasy";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorPolish::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 171 of file translator_pl.h.
    { return "Hierarchia klas"; }
trClassHierarchyDescription()
QCString TranslatorPolish::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 230 of file translator_pl.h.
    { return "Ta lista dziedziczenia posortowana jest z grubsza, "
             "cho nie cakowicie, alfabetycznie:";
    }
trClassMethods()
QCString TranslatorPolish::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1863 of file translator_pl.h.
    {
      return "Metody klasy";
    }
trCode()
QCString TranslatorPolish::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 851 of file translator_pl.h.
    {
      return "kod rdowy";
    }
trCollaborationDiagram()
QCString TranslatorPolish::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 806 of file translator_pl.h.
    {
      return "Diagram wsppracy dla "+clName+":";
    }
trCompoundIndex()
QCString TranslatorPolish::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 360 of file translator_pl.h.
    {
     if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indeks struktur danych";
      }
      else
      {
        return "Indeks klas";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorPolish::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1517 of file translator_pl.h.
    { return "Indeks typw danych"; }
trCompoundList()
QCString TranslatorPolish::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 175 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktury danych";
      }
      else
      {
        return "Lista klas";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorPolish::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 245 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tutaj znajduj si struktury danych wraz z ich krtkimi opisami:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Tutaj znajduj si klasy wraz z ich krtkimi opisami:";
      }
      else
      {
        return "Tutaj znajduj si klasy, struktury, "
             "unie i interfejsy wraz z ich krtkimi opisami:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorPolish::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1490 of file translator_pl.h.
    { return "Tutaj znajduj si typy danych wraz z ich krtkimi opisami:"; }
trCompoundListFortran()
QCString TranslatorPolish::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1482 of file translator_pl.h.
    { return "Lista typw danych"; }
trCompoundMembers()
QCString TranslatorPolish::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 192 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Pola danych";
      }
      else
      {
        return "Skadowe klas";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorPolish::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 264 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll)
      {
        result+="udokumentowanych ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="pl struktur i unii";
      }
      else
      {
        result+="skadowych";
      }
      result+=" wraz z odnonikami do ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentacji struktur/unii dla kadego pola:";
        }
        else
        {
          result+="dokumentacji klas dla kadej skadowej:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktur/unii, do ktrych dane pole naley:";
        }
        else
        {
          result+="klas, do ktrych dana skadowa naley:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorPolish::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1494 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll)
      {
        result+="udokumentowanych ";
      }
      result+="skadowych typw danych";
      result+=" wraz z odnonikami do ";
      if (!extractAll)
      {
         result+="dokumentacji struktury danych dla kadej skadowej";
      }
      else
      {
         result+="typw danych, do ktrych dana skadowa naley:";
      }
      return result;
    }
trCompoundMembersDescriptionTotal()
QCString TranslatorPolish::trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2368 of file translator_pl.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="Tutaj jest lista wszystkich ";
      if (!extractAll)
      {
        result+="udokumentowanych ";
      }
      switch (hl)
      {
        case ClassMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="struktur i pl unii";
          }
          else
          {
            result+="skadowych klasy";
          }
          break;
        case ClassMemberHighlight::Functions:
          result+="funkcji";
          break;
        case ClassMemberHighlight::Variables:
          result+="zmiennych";
          break;
        case ClassMemberHighlight::Typedefs:
          result+="definicji typw";
          break;
        case ClassMemberHighlight::Enums:
          result+="wylicze";
          break;
        case ClassMemberHighlight::EnumValues:
          result+="wartoci wylicze";
          break;
        case ClassMemberHighlight::Properties:
          result+="waciwoci";
          break;
        case ClassMemberHighlight::Events:
          result+="zdarze";
          break;
        case ClassMemberHighlight::Related:
          result+="powizanych symboli";
          break;
        case ClassMemberHighlight::Total: // for completeness
          break;
      }
      result+=" zwizanych z";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" dokumentacj kadego pola struktury/unii:";
        }
        else
        {
          result+=" dokumentacj kadej skadowej klasy:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="e struktur/uni do ktrej nale:";
        }
        else
        {
          result+=" klas do ktrej nale:";
        }
      }
      return result;
    }
References ClassMemberHighlight::All, Config_getBool, ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, ClassMemberHighlight::Properties, ClassMemberHighlight::Related, ClassMemberHighlight::Total, ClassMemberHighlight::Typedefs, and ClassMemberHighlight::Variables.
trCompoundMembersFortran()
QCString TranslatorPolish::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1486 of file translator_pl.h.
    { return "Pola danych"; }
trCompoundReference()
QCString TranslatorPolish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 579 of file translator_pl.h.
    {
      QCString result="Dokumentacja";
      if (isTemplate) result+=" szablonu";
      switch(compType)
      {
        case ClassDef::Class:      result+=" klasy "; break;
        case ClassDef::Struct:     result+=" struktury "; break;
        case ClassDef::Union:      result+=" unii "; break;
        case ClassDef::Interface:  result+=" interfejsu "; break;
        case ClassDef::Protocol:   result+=" protokou "; break;
        case ClassDef::Category:   result+=" kategorii "; break;
        case ClassDef::Exception:  result+=" wyjtku "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorPolish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1558 of file translator_pl.h.
    {
      QCString result="Dokumentacja";
      if (isTemplate) result+=" szablonu";
      switch(compType)
      {
        case ClassDef::Class:      result+=" moduu "; break;
        case ClassDef::Struct:     result+=" typu "; break;
        case ClassDef::Union:      result+=" unii "; break;
        case ClassDef::Interface:  result+=" interfejsu "; break;
        case ClassDef::Protocol:   result+=" protokou "; break;
        case ClassDef::Category:   result+=" kategorii "; break;
        case ClassDef::Exception:  result+=" wyjtku "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice()
QCString TranslatorPolish::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) inline override virtual
Implements Translator.
Definition at line 2155 of file translator_pl.h.
    {
      QCString result=clName;
      result+= "Dokumentacja";
      if (isLocal) result+=" Lokal";
      switch(compType)
      {
        case ClassDef::Class:      if (isLocal) result+="nej"; result+=" Klasy"; break;
        case ClassDef::Struct:     if (isLocal) result+="nej"; result+=" Struktury"; break;
        case ClassDef::Union:      if (isLocal) result+="nej"; result+=" Unii"; break;
        case ClassDef::Interface:  if (isLocal) result+="nego"; result+=" Interfejsu"; break;
        case ClassDef::Protocol:   if (isLocal) result+="nego"; result+=" Protokou"; break;
        case ClassDef::Category:   if (isLocal) result+="nej"; result+=" Kategorii"; break;
        case ClassDef::Exception:  if (isLocal) result+="nego"; result+=" Wyjtku"; break;
        default: break;
      }
      result+=" " + clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorPolish::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 482 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktury danych";
      }
      else
      {
        return "Komponenty";
      }
    }
References Config_getBool.
trCompoundType()
QCString TranslatorPolish::trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) inline override virtual
the compound type as used for the xrefitems
Implements Translator.
Definition at line 2294 of file translator_pl.h.
    {
      QCString result;
      switch(compType)
      {
        case ClassDef::Class:
          if (lang == SrcLangExt::Fortran) trType(true,true);
          else result=trClass(true,true);
          break;
        case ClassDef::Struct:     result="Struktura"; break;
        case ClassDef::Union:      result="Unia"; break;
        case ClassDef::Interface:  result="Interfejs"; break;
        case ClassDef::Protocol:   result="Protok"; break;
        case ClassDef::Category:   result="Kategoria"; break;
        case ClassDef::Exception:  result="Wyjtek"; break;
        case ClassDef::Service:    result="Usuga"; break;
        case ClassDef::Singleton:  result="Wzorzec Projektowy"; break;
        default: break;
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, Fortran, ClassDef::Interface, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, ClassDef::Struct, trClass(), trType(), and ClassDef::Union.
trConcept()
QCString TranslatorPolish::trConcept (bool first_capital, bool singular) inline override virtual
C++20 concept.
Implements Translator.
Definition at line 2204 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "koncept", "y");
    }
References Translator::createNoun().
trConceptDefinition()
QCString TranslatorPolish::trConceptDefinition () inline override virtual
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2237 of file translator_pl.h.
    {
      return "Definicja konceptu";
    }
trConceptDocumentation()
QCString TranslatorPolish::trConceptDocumentation () inline override virtual
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2224 of file translator_pl.h.
    { return "Dokumentacja konceptw"; }
trConceptIndex()
QCString TranslatorPolish::trConceptIndex () inline override virtual
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2220 of file translator_pl.h.
    { return "Indeks konceptw"; }
trConceptList()
QCString TranslatorPolish::trConceptList () inline override virtual
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2216 of file translator_pl.h.
    { return "Lista konceptw"; }
trConceptListDescription()
QCString TranslatorPolish::trConceptListDescription (bool extractAll) inline override virtual
used as an introduction to the concept list
Implements Translator.
Definition at line 2228 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="konceptw wraz z ich krtkimi opisami:";
      return result;
    }
trConceptReference()
QCString TranslatorPolish::trConceptReference (const QCString & conceptName) inline override virtual
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2209 of file translator_pl.h.
    {
      QCString result="Dokumentacja konceptu " + conceptName;
      return result;
    }
trConstantDocumentation()
QCString TranslatorPolish::trConstantDocumentation () inline override virtual
Implements Translator.
Definition at line 2061 of file translator_pl.h.
    {
        return "Dokumentacja staych";
    }
trConstantGroupReference()
QCString TranslatorPolish::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1900 of file translator_pl.h.
    {
      QCString result=namespaceName;
      result+=" Dokumentacja grup staych";
      return result;
    }
trConstantGroups()
QCString TranslatorPolish::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1896 of file translator_pl.h.
    { return "Grupy staych"; }
trConstants()
QCString TranslatorPolish::trConstants () inline override virtual
Implements Translator.
Definition at line 2057 of file translator_pl.h.
    {
        return "Stae";
    }
trConstructorDocumentation()
QCString TranslatorPolish::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 816 of file translator_pl.h.
    {
      return "Dokumentacja konstruktora i destruktora";
    }
trCopyright()
QCString TranslatorPolish::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1784 of file translator_pl.h.
    { return "Copyright"; }
trCopyToClipboard()
QCString TranslatorPolish::trCopyToClipboard () inline override virtual
Implements Translator.
Definition at line 2572 of file translator_pl.h.
    {
      return "Kopiuj do schowka";
    }
trCustomReference()
QCString TranslatorPolish::trCustomReference (const QCString & name) inline override virtual
Implements Translator.
Definition at line 2053 of file translator_pl.h.
    { return "Dokumentacja "+name; }
trDataMemberDocumentation()
QCString TranslatorPolish::trDataMemberDocumentation () inline override virtual
Implements Translator.
Definition at line 2186 of file translator_pl.h.
    {
        return "Dokumentacja pl klasy";
    }
trDataMembers()
QCString TranslatorPolish::trDataMembers () inline override virtual
Implements Translator.
Definition at line 2182 of file translator_pl.h.
    {
        return "Pola klasy";
    }
trDataTypes()
QCString TranslatorPolish::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1541 of file translator_pl.h.
    { return "Typy danych"; }
trDate()
QCString TranslatorPolish::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 520 of file translator_pl.h.
    { return "Data"; }
trDateTime()
QCString TranslatorPolish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1733 of file translator_pl.h.
    {
      static const char *days[]   = { "Pn","Wt","r","Cz","Pt","So","N" };
      static const char *months[] = { "sty","lut","mar","kwi","maj","cze","lip","sie","wrz","pa","lis","gru" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s, %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorPolish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1753 of file translator_pl.h.
    {
      static const char *days_short[]   = { "pon.", "wt.", "r.", "czw.", "pt.", "sob.", "niedz." };
      static const char *days_full[]    = { "poniedziaek", "wtorek", "roda", "czwartek", "pitek", "sobota", "niedziela" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorPolish::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1769 of file translator_pl.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period?1:0];
    }
trDeclaration()
QCString TranslatorPolish::trDeclaration () inline override virtual
Implements Translator.
Definition at line 2496 of file translator_pl.h.
{ return "Deklaracja";}
trDefinedAtLineInSourceFile()
QCString TranslatorPolish::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 783 of file translator_pl.h.
    {
      return "Definicja w linii @0 pliku @1.";
    }
trDefinedIn()
QCString TranslatorPolish::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 159 of file translator_pl.h.
    { return "zdefiniowana w"; }
trDefinedInSourceFile()
QCString TranslatorPolish::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 787 of file translator_pl.h.
    {
      return "Definicja w pliku @0.";
    }
trDefineDocumentation()
QCString TranslatorPolish::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 452 of file translator_pl.h.
    { return "Dokumentacja definicji"; }
trDefines()
QCString TranslatorPolish::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 416 of file translator_pl.h.
    { return "Definicje"; }
trDefineValue()
QCString TranslatorPolish::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1103 of file translator_pl.h.
    {
      return "Warto:";
    }
trDefinition()
QCString TranslatorPolish::trDefinition () inline override virtual
Implements Translator.
Definition at line 2495 of file translator_pl.h.
{ return "Definicja";}
trDeprecated()
QCString TranslatorPolish::trDeprecated () inline override virtual
Implements Translator.
Definition at line 796 of file translator_pl.h.
    {
      return "Do wycofania";
    }
trDeprecatedList()
QCString TranslatorPolish::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1265 of file translator_pl.h.
    {
      return "Lista elementw do wycofania";
    }
trDesignUnitDocumentation()
QCString TranslatorPolish::trDesignUnitDocumentation () inline override virtual
VHDL design unit documentation.
Implements Translator.
Definition at line 2196 of file translator_pl.h.
    { return "Dokumentacja jednostek projektowych"; }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorPolish::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Implements Translator.
Definition at line 1944 of file translator_pl.h.
    { return "Hierarchia jednostek projektowych"; }
trDesignUnitIndex()
QCString TranslatorPolish::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Implements Translator.
Definition at line 1959 of file translator_pl.h.
    { return "Indeks jednostek projektowych"; }
trDesignUnitList()
QCString TranslatorPolish::trDesignUnitList () inline override virtual
VHDL design unit list.
Implements Translator.
Definition at line 1947 of file translator_pl.h.
    { return "Lista jednostek projektowych"; }
trDesignUnitListDescription()
QCString TranslatorPolish::trDesignUnitListDescription () inline override virtual
VHDL design unit list description.
Implements Translator.
Definition at line 1953 of file translator_pl.h.
    {
        return "Tu znajduje si lista wszystkich skadowych jednostek projektowych "
        "zwizanych z Jednostkami Nadrzdnymi do ktrych nale:";
    }
trDesignUnitMembers()
QCString TranslatorPolish::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Implements Translator.
Definition at line 1950 of file translator_pl.h.
    { return "Skadowe jednostki projektowej"; }
trDesignUnits()
QCString TranslatorPolish::trDesignUnits () inline override virtual
VHDL design units.
Implements Translator.
Definition at line 1962 of file translator_pl.h.
    { return "Jednostki projektowe"; }
trDetailedDescription()
QCString TranslatorPolish::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 79 of file translator_pl.h.
    { return "Opis szczegowy"; }
trDetailLevel()
QCString TranslatorPolish::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1796 of file translator_pl.h.
    { return "poziom szczegw"; }
trDetails()
QCString TranslatorPolish::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 83 of file translator_pl.h.
    { return "Szczegy"; }
trDictionaries()
QCString TranslatorPolish::trDictionaries () inline override virtual
Implements Translator.
Definition at line 2073 of file translator_pl.h.
    {
        return "Sowniki";
    }
trDictionaryDocumentation()
QCString TranslatorPolish::trDictionaryDocumentation () inline override virtual
Implements Translator.
Definition at line 2077 of file translator_pl.h.
    {
        return "Dokumentacja sownikw";
    }
trDir()
QCString TranslatorPolish::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1439 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "katalog", "i");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorPolish::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1788 of file translator_pl.h.
    { return QCString("Wykres zalenoci katalogu dla ")+name+":"; }
trDirDocumentation()
QCString TranslatorPolish::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1420 of file translator_pl.h.
    { return "Dokumentacja katalogw"; }
trDirectories()
QCString TranslatorPolish::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1426 of file translator_pl.h.
    { return "Katalogi"; }
trDirIndex()
QCString TranslatorPolish::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1414 of file translator_pl.h.
    { return "Struktura katalogw"; }
trDirReference()
QCString TranslatorPolish::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1433 of file translator_pl.h.
    { QCString result="Dokumentacja katalogu "; result+=dirName; return result; }
trDirRelation()
QCString TranslatorPolish::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1672 of file translator_pl.h.
    {
      return "Relacja "+ QCString(name);
    }
trDocumentation()
QCString TranslatorPolish::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 342 of file translator_pl.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentacja"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorPolish::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 428 of file translator_pl.h.
    { return "Wyliczenia"; }
trEnumerationTypeDocumentation()
QCString TranslatorPolish::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 464 of file translator_pl.h.
    { return "Dokumentacja typw wyliczanych"; }
trEnumerationValueDocumentation()
QCString TranslatorPolish::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1470 of file translator_pl.h.
    { return "Dokumentacja wylicze"; }
trEnumerationValues()
QCString TranslatorPolish::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 446 of file translator_pl.h.
    { return "Wartoci wylicze"; }
trEnumGeneratedFromFiles()
QCString TranslatorPolish::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1808 of file translator_pl.h.
    { QCString result = "Dokumentacja dla tego wyliczenia zostaa wygenerowana z plik";
      if (single) result+="u:"; else result+="w:";
      return result;
    }
trEnumName()
QCString TranslatorPolish::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 151 of file translator_pl.h.
    { return "nazwa wyliczenia"; }
trEnumReference()
QCString TranslatorPolish::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1815 of file translator_pl.h.
    { QCString result="Dokumentacja wyliczenia "; result+=name; return result; }
trEnumValue()
QCString TranslatorPolish::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 155 of file translator_pl.h.
    { return "warto wyliczenia"; }
trEventDocumentation()
QCString TranslatorPolish::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1282 of file translator_pl.h.
    {
      return "Dokumentacja zdarze";
    }
trEvents()
QCString TranslatorPolish::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1277 of file translator_pl.h.
    {
      return "Zdarzenia";
    }
trExamples()
QCString TranslatorPolish::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 222 of file translator_pl.h.
    { return "Przykady"; }
trExamplesDescription()
QCString TranslatorPolish::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 327 of file translator_pl.h.
    { return "Tutaj znajduje si lista wszystkich przykadw:"; }
trExceptionDocumentation()
QCString TranslatorPolish::trExceptionDocumentation () inline override virtual
Implements Translator.
Definition at line 2151 of file translator_pl.h.
    {
        return "Dokumentacja wyjtkw";
    }
trExceptionHierarchy()
QCString TranslatorPolish::trExceptionHierarchy () inline override virtual
Implements Translator.
Definition at line 2142 of file translator_pl.h.
    {
        return "Hierarchia wyjtkw";
    }
trExceptionHierarchyDescription()
QCString TranslatorPolish::trExceptionHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2146 of file translator_pl.h.
    {
        return "Ta lista dziedziczenia posortowana jest z grubsza, "
        "cho nie cakowicie, alfabetycznie:";
    }
trExceptionIndex()
QCString TranslatorPolish::trExceptionIndex () inline override virtual
Implements Translator.
Definition at line 2130 of file translator_pl.h.
    {
        return "Indeks wyjtkw";
    }
trExceptionList()
QCString TranslatorPolish::trExceptionList () inline override virtual
Implements Translator.
Definition at line 2134 of file translator_pl.h.
    {
        return "Lista wyjtkw";
    }
trExceptionListDescription()
QCString TranslatorPolish::trExceptionListDescription () inline override virtual
Implements Translator.
Definition at line 2138 of file translator_pl.h.
    {
        return "Tutaj znajduj si wyjtki wraz z ich krtkimi opisami:";
    }
trExceptions()
QCString TranslatorPolish::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 536 of file translator_pl.h.
    { return "Wyjtki"; }
trExportedModules()
QCString TranslatorPolish::trExportedModules () inline override virtual
Implements Translator.
Definition at line 2563 of file translator_pl.h.
    {
      return "Eksportowane moduy";
    }
trExtendsClass()
QCString TranslatorPolish::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1855 of file translator_pl.h.
    {
      return "Rozszerza klas @0.";
    }
trFile()
QCString TranslatorPolish::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1158 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "plik", "i");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorPolish::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 406 of file translator_pl.h.
    { return "Dokumentacja plikw"; }
trFileIn()
QCString TranslatorPolish::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1709 of file translator_pl.h.
    {
      return "Plik w "+name;
    }
trFileIndex()
QCString TranslatorPolish::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 375 of file translator_pl.h.
    { return "Indeks plikw"; }
trFileList()
QCString TranslatorPolish::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 188 of file translator_pl.h.
    { return "Lista plikw"; }
trFileListDescription()
QCString TranslatorPolish::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 236 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="plikw wraz z ich krtkimi opisami:";
      return result;
    }
trFileMembers()
QCString TranslatorPolish::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 205 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globalne";
      }
      else
      {
        return "Skadowe plikw";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorPolish::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 306 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcji, zmiennych, definicji, wylicze i definicji typw";
      }
      else
      {
        result+="skadowych plikw";
      }
      result+=" wraz z odnonikami do ";
      if (extractAll)
        result+="plikw, do ktrych one nale:";
      else
        result+="dokumentacji:";
      return result;
    }
References Config_getBool.
trFileMembersDescriptionTotal()
QCString TranslatorPolish::trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2316 of file translator_pl.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="Tutaj jest lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      switch (hl)
      {
        case FileMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="funkcji, zmiennych, definicji, wylicze, i definicji typw";
          }
          else
          {
            result+="doczonych plikw";
          }
          break;
        case FileMemberHighlight::Functions:
          result+="funkcji";
          break;
        case FileMemberHighlight::Variables:
          result+="zmiennych";
          break;
        case FileMemberHighlight::Typedefs:
          result+="definicji typw";
          break;
        case FileMemberHighlight::Sequences:
          result+="sekwencji";
          break;
        case FileMemberHighlight::Dictionaries:
          result+="sownikw";
          break;
        case FileMemberHighlight::Enums:
          result+="wylicze";
          break;
        case FileMemberHighlight::EnumValues:
          result+="wartoci wylicze";
          break;
        case FileMemberHighlight::Defines:
          result+="definicji";
          break;
        case FileMemberHighlight::Total: // for completeness
          break;
      }
      result+=" zwizanych z ";
      if (extractAll)
        result+="plikami do ktrych nale:";
      else
        result+="dokumentacj:";
      return result;
    }
References FileMemberHighlight::All, Config_getBool, FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, FileMemberHighlight::Sequences, FileMemberHighlight::Total, FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
trFileReference()
QCString TranslatorPolish::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 601 of file translator_pl.h.
    {
      QCString result="Dokumentacja pliku ";
      result+=fileName;
      return result;
    }
trFlowchart()
QCString TranslatorPolish::trFlowchart () inline override virtual
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2256 of file translator_pl.h.
    { return "Schemat blokowy:"; }
trFriends()
QCString TranslatorPolish::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 561 of file translator_pl.h.
    { return "Przyjaciele"; }
trFunctionAndProc()
QCString TranslatorPolish::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Implements Translator.
Definition at line 1965 of file translator_pl.h.
    { return "Funkcje/Procedury/Procesy"; }
trFunctionDocumentation()
QCString TranslatorPolish::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 470 of file translator_pl.h.
    { return "Dokumentacja funkcji"; }
trFunctions()
QCString TranslatorPolish::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 434 of file translator_pl.h.
    { return "Funkcje"; }
trGeneratedAt()
QCString TranslatorPolish::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 497 of file translator_pl.h.
    {
      QCString result="Wygenerowano "+date;
      if (!projName.isEmpty()) result+=" dla "+projName;
      result+=" za pomoc";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorPolish::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 143 of file translator_pl.h.
    { QCString result="Wygenerowano automatycznie z kodu rdowego programem Doxygen";
      if (!s.isEmpty()) result+=" dla "+s;
      result+=".";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorPolish::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 540 of file translator_pl.h.
    { return "Wygenerowano za pomoc"; }
trGeneratedFromFiles()
QCString TranslatorPolish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 739 of file translator_pl.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacja dla te";
      switch(compType)
      {
        case ClassDef::Class:      result+="j klasy"; break;
        case ClassDef::Struct:     result+="j struktury"; break;
        case ClassDef::Union:      result+="j unii"; break;
        case ClassDef::Interface:  result+="go interfejsu"; break;
        case ClassDef::Protocol:   result+="go protokou"; break;
        case ClassDef::Category:   result+="j kategorii"; break;
        case ClassDef::Exception:  result+="go wyjtku"; break;
        default: break;
      }
      result+=" zostaa wygenerowana z plik";
      if (single) result+="u:"; else result+="w:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorPolish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1624 of file translator_pl.h.
    {
      // single is true implies a single file
      QCString result="Dokumentacja dla te";
      switch(compType)
      {
        case ClassDef::Class:      result+="go moduu"; break;
        case ClassDef::Struct:     result+="go typu"; break;
        case ClassDef::Union:      result+="j unii"; break;
        case ClassDef::Interface:  result+="go interfejsu"; break;
        case ClassDef::Protocol:   result+="go protokou"; break;
        case ClassDef::Category:   result+="j kategorii"; break;
        case ClassDef::Exception:  result+="go wyjtku"; break;
        default: break;
      }
      result+=" zostaa wygenerowana z plik";
      if (single) result+="u:"; else result+="w:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorPolish::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1203 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "global", "ne", "ny");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorPolish::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1684 of file translator_pl.h.
    {
      return "Globalna przestrze nazw";
    }
trGotoDocumentation()
QCString TranslatorPolish::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 826 of file translator_pl.h.
    {
      return "Id do dokumentacji tego pliku.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorPolish::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 859 of file translator_pl.h.
    {
      return "Id do graficznej hierarchii klas";
    }
trGotoSourceCode()
QCString TranslatorPolish::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 821 of file translator_pl.h.
    {
      return "Id do kodu rdowego tego pliku.";
    }
trGotoTextualHierarchy()
QCString TranslatorPolish::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 863 of file translator_pl.h.
    {
      return "Id do tekstowej hierarchii klas";
    }
trGraphicalHierarchy()
QCString TranslatorPolish::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 855 of file translator_pl.h.
    {
      return "Graficzna hierarchia klas";
    }
trGroup()
QCString TranslatorPolish::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1176 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "grupa", "y");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorPolish::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 354 of file translator_pl.h.
    { return "Indeks hierarchiczny"; }
trImplementedFromList()
QCString TranslatorPolish::trImplementedFromList (int numEntries) inline override virtual
Implements Translator.
Definition at line 1236 of file translator_pl.h.
    {
      return "Implementuje "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorPolish::trImplementedInList (int numEntries) inline override virtual
Implements Translator.
Definition at line 1241 of file translator_pl.h.
    {
      return "Implementowany w "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImportant()
QCString TranslatorPolish::trImportant () inline override virtual
Implements Translator.
Definition at line 2580 of file translator_pl.h.
    {
      return "Wane";
    }
trInclByDepGraph()
QCString TranslatorPolish::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 955 of file translator_pl.h.
    {
      return "Ten wykres pokazuje, ktre pliki bezporednio lub "
             "porednio zaczaj ten plik:";
    }
trInclDepGraph()
QCString TranslatorPolish::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 811 of file translator_pl.h.
    {
      return "Wykres zalenoci zaczania dla "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorPolish::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1718 of file translator_pl.h.
    {
      return "Zawiera plik w "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorPolish::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 137 of file translator_pl.h.
    { return ", uwzgldniajca wszystkie dziedziczone skadowe."; }
trInheritedByList()
QCString TranslatorPolish::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 673 of file translator_pl.h.
    {
      return "Dziedziczona przez "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorPolish::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1819 of file translator_pl.h.
    { return QCString(members)+" dziedziczone z "+what; }
trInheritsList()
QCString TranslatorPolish::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 665 of file translator_pl.h.
    {
      return "Dziedziczy "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorPolish::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 846 of file translator_pl.h.
    {
      return "Warto pocztkowa:";
    }
trInstanceMethods()
QCString TranslatorPolish::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1871 of file translator_pl.h.
    {
      return "Metody instancji";
    }
trInterfaceDocumentation()
QCString TranslatorPolish::trInterfaceDocumentation () inline override virtual
Implements Translator.
Definition at line 2106 of file translator_pl.h.
    {
        return "Dokumentacja interfejsw";
    }
trInterfaceHierarchy()
QCString TranslatorPolish::trInterfaceHierarchy () inline override virtual
Implements Translator.
Definition at line 2097 of file translator_pl.h.
    {
        return "Hierarchia interfejsw";
    }
trInterfaceHierarchyDescription()
QCString TranslatorPolish::trInterfaceHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2101 of file translator_pl.h.
    {
        return "Ta lista dziedziczenia posortowana jest z grubsza, "
        "cho nie cakowicie, alfabetycznie:";
    }
trInterfaceIndex()
QCString TranslatorPolish::trInterfaceIndex () inline override virtual
Implements Translator.
Definition at line 2085 of file translator_pl.h.
    {
        return "Indeks interfejsw";
    }
trInterfaceList()
QCString TranslatorPolish::trInterfaceList () inline override virtual
Implements Translator.
Definition at line 2089 of file translator_pl.h.
    {
        return "Lista interfejsw";
    }
trInterfaceListDescription()
QCString TranslatorPolish::trInterfaceListDescription () inline override virtual
Implements Translator.
Definition at line 2093 of file translator_pl.h.
    {
        return "Tutaj znajduje si lista interfejsw wraz z ich krtkimi opisami:";
    }
trInterfaces()
QCString TranslatorPolish::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1888 of file translator_pl.h.
    { return "Eksportowane interfejsy"; }
trInvariant()
QCString TranslatorPolish::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 841 of file translator_pl.h.
    {
      return "Niezmiennik";
    }
trISOLang()
QCString TranslatorPolish::trISOLang () inline override virtual
Implements Translator.
Definition at line 59 of file translator_pl.h.
    {
      return "pl";
    }
trLegend()
QCString TranslatorPolish::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1037 of file translator_pl.h.
    {
      return "legenda";
    }
trLegendDocs()
QCString TranslatorPolish::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 975 of file translator_pl.h.
    {
      return
        "Ta strona wyjania jak interpretowa wykresy, ktre s wygenerowane "
        "przez doxygen.<p>\n"
        "Rozwa nastpujcy przykad:\n"
        "\\code\n"
        "/*! Klasa Niewidzialna z powodu okrojenia */\n"
        "class Niewidzialna { };\n\n"
        "/*! Klasa Okrojona, relacja dziedziczenia jest ukryta */\n"
        "class Okrojona : public Niewidzialna { };\n\n"
        "/* Klasa nie udokumentowana komentarzami doxygen */\n"
        "class Nieudokumentowana { };\n\n"
        "/*! Klasa, ktra jest dziedziczona publicznie */\n"
        "class PublicznaBaza : public Okrojona { };\n\n"
        "/*! Szablon klasy */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasa, ktra jest dziedziczona przy uyciu dziedziczenia chronionego */\n"
        "class ChronionaBaza { };\n\n"
        "/*! Klasa, ktra jest dziedziczona prywatnie */\n"
        "class PrywatnaBaza { };\n\n"
        "/*! Klasa, ktra jest uyta przez klas Dziedziczona */\n"
        "class Uzyta { };\n\n"
        "/*! Superklasa, ktra dziedziczy kilka innych klas */\n"
        "class Dziedziczona : public PublicznaBaza,\n"
        "                     protected ChronionaBaza,\n"
        "                     private PrywatnaBaza,\n"
        "                     public Nieudokumentowana,\n"
        "                     public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Uzyta *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Rezultat na nastpujcym wykresie:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Prostokty w powyszym wykresie maj nastpujce znaczenie:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Wypeniony czarny prostokt reprezentuje struktur lub klas dla "
        "ktrej zosta wygenerowany wykres.</li>\n"
        "<li>Prostokt z czarn obwolut oznacza udokumentowan struktur lub klas.</li>\n"
        "<li>Prostokt z szar obwolut oznacza nieudokumentowan struktur lub klas.</li>\n"
        "<li>Prostokt z czerwon obwolut oznacza udokumentowan struktur lub klas dla\n"
        "ktrej nie s pokazane wszystkie relacje dziedziczenia/zawierania. Wykres jest "
        "okrojony, jeli nie mieci si w okrelonych brzegach.</li>\n"
        "</ul>\n"
        "<p>\n"
        "Strzaki maj nastpujce znaczenie:\n"
        "<p>\n"
        "<ul>\n"
        "<li>Ciemno niebieska strzaka jest uywana do wizualizacji relacji "
        "dziedziczenia publicznego pomidzy dwiema klasami.</li>\n"
        "<li>Ciemno zielona strzaka jest uywana dla dziedziczenia chronionego.</li>\n"
        "<li>Ciemno czerwona strzaka jest uywana dla dziedziczenia prywatnego.</li>\n"
        "<li>Fioletowa przerywana strzaka jest uywana jeli klasa jest zawarta "
        "lub uyta przez inn klas. Strzaka jest podpisana zmienn(ymi) "
        "przez ktre wskazywana klasa lub struktura jest dostpna. </li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorPolish::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 970 of file translator_pl.h.
    {
      return "Legenda wykresu";
    }
trListOfAllMembers()
QCString TranslatorPolish::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 125 of file translator_pl.h.
    { return "Lista wszystkich skadowych"; }
trLoading()
QCString TranslatorPolish::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1678 of file translator_pl.h.
    {
      return "Wczytywanie...";
    }
trMainPage()
QCString TranslatorPolish::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 770 of file translator_pl.h.
    { return "Strona gwna"; }
trMember()
QCString TranslatorPolish::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1194 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "skadow", "e", "a");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorPolish::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 108 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacja pl";
      }
      else
      {
        return "Dokumentacja atrybutw skadowych";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorPolish::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 91 of file translator_pl.h.
    { return "Dokumentacja skadowych wyliczanych"; }
trMemberFunctionDocumentation()
QCString TranslatorPolish::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 95 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Dokumentacja funkcji/procedur/procesw skadowych";
      }
      else
      {
        return "Dokumentacja funkcji skadowych";
      }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran()
QCString TranslatorPolish::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1478 of file translator_pl.h.
    { return "Dokumentacja skadowej funkcji/podprogramu"; }
trMemberList()
QCString TranslatorPolish::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 129 of file translator_pl.h.
    { return "Lista skadowych"; }
trMemberTypedefDocumentation()
QCString TranslatorPolish::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 87 of file translator_pl.h.
    { return "Dokumentacja skadowych definicji typu"; }
trMethodDocumentation()
QCString TranslatorPolish::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1878 of file translator_pl.h.
    {
      return "Dokumentacja metod";
    }
trModule()
QCString TranslatorPolish::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1617 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "modu", "y");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorPolish::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 381 of file translator_pl.h.
    { return "Dokumentacja grup"; }
trModuleIndex()
QCString TranslatorPolish::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 348 of file translator_pl.h.
    { return "Indeks grup"; }
trModuleMembersDescriptionTotal()
QCString TranslatorPolish::trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2518 of file translator_pl.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="Tutaj jest lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="moduw ";
      QCString singularResult = "";
      QCString pluralResult = "";
      switch (hl)
      {
        case ModuleMemberHighlight::All:
          singularResult="kadej skadowej";
          pluralResult = "wszystkich skadowych";
          break;
        case ModuleMemberHighlight::Functions:
          singularResult="kadej funkcji";
          pluralResult = "wszystkich funkcji";
          break;
        case ModuleMemberHighlight::Variables:
          singularResult="kadej zmiennej";
          pluralResult = "wszystkich zmiennych";
          break;
        case ModuleMemberHighlight::Typedefs:
          singularResult="kadej definicji typu";
          pluralResult = "wszystkich definicji typw";
          break;
        case ModuleMemberHighlight::Enums:
          singularResult="kadego wyliczenia";
          pluralResult = "wszystkich wylicze";
          break;
        case ModuleMemberHighlight::EnumValues:
          singularResult="kadej wartoci wylicze";
          pluralResult = "wszystkich wartoci wylicze";
          break;
        case ModuleMemberHighlight::Total: // for completeness
          break;
      }
      result+=pluralResult;
      result+=" zwizanych z ";
      if (extractAll)
        result+="dokumentacj moduu dla " + singularResult + ":";
      else
        result+="moduem do ktrego nale:";
      return result;
    }
References ModuleMemberHighlight::All, Config_getBool, ModuleMemberHighlight::Enums, ModuleMemberHighlight::EnumValues, ModuleMemberHighlight::Functions, ModuleMemberHighlight::Total, ModuleMemberHighlight::Typedefs, and ModuleMemberHighlight::Variables.
trModuleReference()
QCString TranslatorPolish::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1579 of file translator_pl.h.
    {
      QCString result="Dokumentacja moduu ";
      result+=namespaceName;
      return result;
    }
trModules()
QCString TranslatorPolish::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 167 of file translator_pl.h.
    { return "Moduy"; }
trModulesDescription()
QCString TranslatorPolish::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 335 of file translator_pl.h.
    { return "Tutaj znajduje si lista wszystkich grup:"; }
trModulesIndex()
QCString TranslatorPolish::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1610 of file translator_pl.h.
    { return "Indeks moduu"; }
trModulesList()
QCString TranslatorPolish::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1545 of file translator_pl.h.
    { return "Lista moduw"; }
trModulesListDescription()
QCString TranslatorPolish::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1549 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="moduw wraz z ich krtkimi opisami:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorPolish::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1591 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="skadowych moduw wraz z odnonikami do ";
      if (extractAll)
      {
        result+="dokumentacji moduu dla kadej skadowej:";
      }
      else
      {
        result+="moduw, do ktrych skadowe te nale:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorPolish::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1587 of file translator_pl.h.
    { return "Skadowe moduu"; }
trMonth()
QCString TranslatorPolish::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1761 of file translator_pl.h.
    {
      static const char *months_short[] = { "sty", "lut", "mar", "kwi", "maj", "cze", "lip", "sie", "wrz", "pa", "lis", "gru" };
      static const char *months_full[]  = { "stycze", "luty", "marzec", "kwiecie", "maj", "czerwiec", "lipiec", "sierpie", "wrzesie", "padziernik", "listopad", "grudzie" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorPolish::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 121 of file translator_pl.h.
    { return "Wicej..."; }
trNamespace()
QCString TranslatorPolish::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1167 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "przestrze", "nie", "") + " nazw";
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorPolish::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 719 of file translator_pl.h.
    { return "Dokumentacja przestrzeni nazw"; }
trNamespaceIndex()
QCString TranslatorPolish::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 713 of file translator_pl.h.
    { return "Indeks przestrzeni nazw"; }
trNamespaceList()
QCString TranslatorPolish::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 546 of file translator_pl.h.
    { return "Lista przestrzeni nazw"; }
trNamespaceListDescription()
QCString TranslatorPolish::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 550 of file translator_pl.h.
    {
      QCString result="Tutaj znajduj si wszystkie ";
      if (!extractAll) result+="udokumentowane ";
      result+="przestrzenie nazw wraz z ich krtkimi opisami:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorPolish::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 699 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="skadowych wraz z odnonikami do ";
      if (extractAll)
        result+="dokumentacji przestrzeni nazw dla kadej skadowej:";
      else
        result+="przestrzeni nazw do ktrych skadowe te nale:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorPolish::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 695 of file translator_pl.h.
    { return "Skadowe przestrzeni nazw"; }
trNamespaceMembersDescriptionTotal()
QCString TranslatorPolish::trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2441 of file translator_pl.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="Tutaj jest lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="przestrzeni nazw ";
      QCString singularResult = "";
      QCString pluralResult = "";
      switch (hl)
      {
        case NamespaceMemberHighlight::All:
          singularResult="kadej skadowej";
          pluralResult="wszystkich skadowych";
          break;
        case NamespaceMemberHighlight::Functions:
          singularResult="kadej funkcji";
          pluralResult="wszystkich funkcji";
          break;
        case NamespaceMemberHighlight::Variables:
          singularResult="kadej zmiennej";
          pluralResult="wszystkich zmiennych";
          break;
        case NamespaceMemberHighlight::Typedefs:
          singularResult="kadej definicji typu";
          pluralResult="wszystkich definicji typw";
          break;
        case NamespaceMemberHighlight::Sequences:
          singularResult="kadej sekwencji";
          pluralResult="wszystkich sekwencji";
          break;
        case NamespaceMemberHighlight::Dictionaries:
          singularResult="kadego sownika";
          pluralResult="wszystkich sownikw";
          break;
        case NamespaceMemberHighlight::Enums:
          singularResult="kadego wyliczenia";
          pluralResult="wszystkich wylicze";
          break;
        case NamespaceMemberHighlight::EnumValues:
          singularResult="kadej wartoci wyliczenia";
          pluralResult="wszystkich wartoci wylicze";
          break;
        case NamespaceMemberHighlight::Total: // for completeness
          break;
      }
      result+=pluralResult;
      result+=" zwizanych z ";
      if (extractAll)
        result+="przestrzeni nazw dla " + singularResult + ":";
      else
        result+="przestrzeni nazw do ktrej nale:";
      return result;
    }
References NamespaceMemberHighlight::All, Config_getBool, NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, NamespaceMemberHighlight::Sequences, NamespaceMemberHighlight::Total, NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
trNamespaceReference()
QCString TranslatorPolish::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 609 of file translator_pl.h.
    {
      QCString result="Dokumentacja przestrzeni nazw ";
      result+=namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorPolish::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 729 of file translator_pl.h.
    { return "Przestrzenie nazw"; }
trNoMatches()
QCString TranslatorPolish::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1696 of file translator_pl.h.
    {
      return "Brak dopasowa";
    }
trNote()
QCString TranslatorPolish::trNote () inline override virtual
Implements Translator.
Definition at line 876 of file translator_pl.h.
    {
      return "Nota";
    }
trOperationDocumentation()
QCString TranslatorPolish::trOperationDocumentation () inline override virtual
Implements Translator.
Definition at line 2178 of file translator_pl.h.
    {
        return "Dokumentacja operacji";
    }
trOperations()
QCString TranslatorPolish::trOperations () inline override virtual
Implements Translator.
Definition at line 2174 of file translator_pl.h.
    {
        return "Operacje";
    }
trOverloadText()
QCString TranslatorPolish::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1451 of file translator_pl.h.
    {
      return "To jest metoda przeciona, udostpniona dla wygody. "
             "Rni si od powyszej metody tylko zestawem akceptowanych argumentw.";
    }
trPackage()
QCString TranslatorPolish::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1088 of file translator_pl.h.
    {
      return "Pakiet "+name;
    }
trPackageAttribs()
QCString TranslatorPolish::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1318 of file translator_pl.h.
    {
      return "Atrybuty pakietu";
    }
trPackageFunctions()
QCString TranslatorPolish::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1300 of file translator_pl.h.
    {
      return "Funkcje pakietu";
    }
trPackageList()
QCString TranslatorPolish::trPackageList () inline override virtual
Implements Translator.
Definition at line 2246 of file translator_pl.h.
    { return "Lista pakietw"; }
trPackageListDescription()
QCString TranslatorPolish::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1093 of file translator_pl.h.
    {
      return "Oto lista pakietw wraz z ich krtkimi opisami (jeli s dostpne):";
    }
trPackageMembers()
QCString TranslatorPolish::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1304 of file translator_pl.h.
    {
      return "Skadowe pakietu";
    }
trPackages()
QCString TranslatorPolish::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1098 of file translator_pl.h.
    {
      return "Pakiety";
    }
trPackageTypes()
QCString TranslatorPolish::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1293 of file translator_pl.h.
    {
      return "Typy pakietu";
    }
trPage()
QCString TranslatorPolish::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1185 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "stron", "y", "a");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorPolish::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 776 of file translator_pl.h.
    { return "str."; }
trPageIndex()
QCString TranslatorPolish::trPageIndex () inline override virtual
Implements Translator.
Definition at line 867 of file translator_pl.h.
    {
      return "Indeks stron";
    }
trPanelSynchronisationTooltip()
QCString TranslatorPolish::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1836 of file translator_pl.h.
    {
      QCString opt = enable ? "wczy" : "wyczy";
      return "kliknij eby "+opt+" pokazywanie otwartego elementu w drzewie zawartoci";
    }
trParameters()
QCString TranslatorPolish::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 532 of file translator_pl.h.
    { return "Parametry"; }
trPostcondition()
QCString TranslatorPolish::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 836 of file translator_pl.h.
    {
      return "Warunek kocowy";
    }
trPrecondition()
QCString TranslatorPolish::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 831 of file translator_pl.h.
    {
      return "Warunek wstpny";
    }
trPrivateAttribs()
QCString TranslatorPolish::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 915 of file translator_pl.h.
    {
      return "Atrybuty prywatne";
    }
trPrivateMembers()
QCString TranslatorPolish::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 631 of file translator_pl.h.
    { return "Metody prywatne"; }
trPrivateSlots()
QCString TranslatorPolish::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 633 of file translator_pl.h.
    { return "Sloty prywatne"; }
trPrivateTypes()
QCString TranslatorPolish::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 911 of file translator_pl.h.
    {
      return "Typy prywatne";
    }
trProperties()
QCString TranslatorPolish::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1062 of file translator_pl.h.
    {
      return "Waciwoci";
    }
trPropertyDocumentation()
QCString TranslatorPolish::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1067 of file translator_pl.h.
    {
      return "Dokumentacja waciwoci";
    }
trProtectedAttribs()
QCString TranslatorPolish::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 903 of file translator_pl.h.
    {
      return "Atrybuty chronione";
    }
trProtectedMembers()
QCString TranslatorPolish::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 625 of file translator_pl.h.
    { return "Metody chronione"; }
trProtectedSlots()
QCString TranslatorPolish::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 627 of file translator_pl.h.
    { return "Sloty chronione"; }
trProtectedTypes()
QCString TranslatorPolish::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 899 of file translator_pl.h.
    {
      return "Typy chronione";
    }
trProvidedByCategory()
QCString TranslatorPolish::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1846 of file translator_pl.h.
    {
      return "Dostarczany przez kategori @0.";
    }
trPublicAttribs()
QCString TranslatorPolish::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 884 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Pola danych";
      }
      else
      {
        return "Atrybuty publiczne";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorPolish::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 617 of file translator_pl.h.
    { return "Metody publiczne"; }
trPublicSlots()
QCString TranslatorPolish::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 619 of file translator_pl.h.
    { return "Sloty publiczne"; }
trPublicTypes()
QCString TranslatorPolish::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 880 of file translator_pl.h.
    {
      return "Typy publiczne";
    }
trReferencedBy()
QCString TranslatorPolish::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 943 of file translator_pl.h.
    {
      return "Odwoania w";
    }
trReferenceManual()
QCString TranslatorPolish::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 410 of file translator_pl.h.
    { return "Podrcznik"; }
trReferences()
QCString TranslatorPolish::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1225 of file translator_pl.h.
    {
      return "Odwouje si do";
    }
trReimplementedFromList()
QCString TranslatorPolish::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 681 of file translator_pl.h.
    {
      return "Reimplementowana z "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorPolish::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 689 of file translator_pl.h.
    {
      return "Reimplementowana w "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorPolish::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 571 of file translator_pl.h.
    { return "Dokumentacja przyjaci i powizanych funkcji"; }
trRelatedFunctions()
QCString TranslatorPolish::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 71 of file translator_pl.h.
    { return "Funkcje powizane"; }
trRelatedPages()
QCString TranslatorPolish::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 218 of file translator_pl.h.
    { return "Powizane strony"; }
trRelatedPagesDescription()
QCString TranslatorPolish::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 331 of file translator_pl.h.
    { return "Tutaj znajduje si lista wszystkich powizanych stron dokumentacji:"; }
trRelatedSubscript()
QCString TranslatorPolish::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 75 of file translator_pl.h.
    { return "(Zauwa, e to nie s metody klas.)"; }
trRelatedSymbolDocumentation()
QCString TranslatorPolish::trRelatedSymbolDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes.
Supersedes trRelatedFunctionDocumentation
Implements Translator.
Definition at line 2286 of file translator_pl.h.
    { return "Dokumentacja przyjaci i powizanych symboli"; }
trRelatedSymbols()
QCString TranslatorPolish::trRelatedSymbols () inline override virtual
Please translate also updated body of the method trMemberFunctionDocumentation(), now better adapted for VHDL sources documentation.
used in the compound documentation before a list of related symbols.
Supersedes trRelatedFunctions
Implements Translator.
Definition at line 2271 of file translator_pl.h.
    { return "Powizane symbole"; }
trRelatedSymbolsSubscript()
QCString TranslatorPolish::trRelatedSymbolsSubscript () inline override virtual
subscript for the related symbols
Supersedes trRelatedSubscript
Implements Translator.
Definition at line 2278 of file translator_pl.h.
    { return "(Zauwa, e te symbole nie s skadowymi.)"; }
trRemarks()
QCString TranslatorPolish::trRemarks () inline override virtual
Implements Translator.
Definition at line 947 of file translator_pl.h.
    {
      return "Spostrzeenia";
    }
trReturns()
QCString TranslatorPolish::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 524 of file translator_pl.h.
    { return "Zwraca"; }
trReturnValues()
QCString TranslatorPolish::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 765 of file translator_pl.h.
    { return "Zwracane wartoci"; }
trRTFansicp()
QCString TranslatorPolish::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1128 of file translator_pl.h.
    {
      return "1250";
    }
trRTFCharSet()
QCString TranslatorPolish::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1134 of file translator_pl.h.
    {
      return "238";
    }
trRTFGeneralIndex()
QCString TranslatorPolish::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1140 of file translator_pl.h.
    {
      return "Indeks";
    }
trRTFTableOfContents()
QCString TranslatorPolish::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1253 of file translator_pl.h.
    {
      return "Spis treci";
    }
trSearch()
QCString TranslatorPolish::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 226 of file translator_pl.h.
    { return "Szukaj"; }
trSearching()
QCString TranslatorPolish::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1690 of file translator_pl.h.
    {
      return "Szukanie...";
    }
trSearchMatches()
QCString TranslatorPolish::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1391 of file translator_pl.h.
    {
      return "Pasujce sowa:";
    }
trSearchResults()
QCString TranslatorPolish::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1366 of file translator_pl.h.
    {
      if (numDocuments==0)
      {
        return "Niestety aden dokument nie pasuje do twojego zapytania.";
      }
      else if (numDocuments==1)
      {
        return "Znaleziono <b>1</b> dokument pasujcy do twojego zapytania.";
      }
      int count = numDocuments % 10;
      if ((count>=2) && (count<=4))
      {
        return "Znaleziono <b>$num</b> dokumenty pasujce do twojego zapytania. "
               "Najlepiej pasujce dokumenty wywietlane s na pocztku listy.";
      }
      else
      {
        return "Znaleziono <b>$num</b> dokumentw pasujcych do twojego zapytania. "
               "Najlepiej pasujce dokumenty wywietlane s na pocztku listy.";
      }
    }
trSearchResultsTitle()
QCString TranslatorPolish::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1354 of file translator_pl.h.
    {
      return "Wyniki szukania";
    }
trSeeAlso()
QCString TranslatorPolish::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 528 of file translator_pl.h.
    { return "Zobacz rwnie"; }
trSequenceDocumentation()
QCString TranslatorPolish::trSequenceDocumentation () inline override virtual
Implements Translator.
Definition at line 2069 of file translator_pl.h.
    {
        return "Dokumentacja sekwencji";
    }
trSequences()
QCString TranslatorPolish::trSequences () inline override virtual
Implements Translator.
Definition at line 2065 of file translator_pl.h.
    {
        return "Sekwencje";
    }
trServiceGeneratedFromFiles()
QCString TranslatorPolish::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 1921 of file translator_pl.h.
    {
      // single is true implies a single file
      QCString result="Dokumentacja dla tej usugi "
                      "zostaa wygenerowana z plik";
      if (single) result+="u:"; else result+="w:";
      return result;
    }
trServiceReference()
QCString TranslatorPolish::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 1907 of file translator_pl.h.
    {
      QCString result=sName;
      result+=" Dokumentacja usug";
      return result;
    }
trServices()
QCString TranslatorPolish::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1892 of file translator_pl.h.
    { return "Zaczone usugi"; }
trSignals()
QCString TranslatorPolish::trSignals () inline override virtual
Implements Translator.
Definition at line 621 of file translator_pl.h.
    { return "Sygnay"; }
trSince()
QCString TranslatorPolish::trSince () inline override virtual
Implements Translator.
Definition at line 960 of file translator_pl.h.
    {
      return "Od";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorPolish::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 1930 of file translator_pl.h.
    {
      // single is true implies a single file
      QCString result="Dokumentacja dla tego wzorca projektowego "
                      "zostaa wygenerowana z plik";
      if (single) result+="u:"; else result+="w:";
      return result;
    }
trSingletonReference()
QCString TranslatorPolish::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 1914 of file translator_pl.h.
    {
      QCString result=sName;
      result+=" Dokumentacja wzorcw projektowych";
      return result;
    }
trSliceInterfaces()
QCString TranslatorPolish::trSliceInterfaces () inline override virtual
Implements Translator.
Definition at line 2081 of file translator_pl.h.
    {
        return "Interfejsy";
    }
trSourceFile()
QCString TranslatorPolish::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1402 of file translator_pl.h.
    {
      return "Plik rdowy " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorPolish::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1325 of file translator_pl.h.
    {
      return "Statyczne atrybuty pakietu";
    }
trStaticPackageFunctions()
QCString TranslatorPolish::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1311 of file translator_pl.h.
    {
      return "Statyczne funkcje pakietu";
    }
trStaticPrivateAttribs()
QCString TranslatorPolish::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 919 of file translator_pl.h.
    {
      return "Statyczne atrybuty prywatne";
    }
trStaticPrivateMembers()
QCString TranslatorPolish::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 635 of file translator_pl.h.
    { return "Statyczne metody prywatne"; }
trStaticProtectedAttribs()
QCString TranslatorPolish::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 907 of file translator_pl.h.
    {
      return "Statyczne atrybuty chronione";
    }
trStaticProtectedMembers()
QCString TranslatorPolish::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 629 of file translator_pl.h.
    { return "Statyczne metody chronione"; }
trStaticPublicAttribs()
QCString TranslatorPolish::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 895 of file translator_pl.h.
    {
      return "Statyczne atrybuty publiczne";
    }
trStaticPublicMembers()
QCString TranslatorPolish::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 623 of file translator_pl.h.
    { return "Statyczne metody publiczne"; }
trStructDocumentation()
QCString TranslatorPolish::trStructDocumentation () inline override virtual
Implements Translator.
Definition at line 2126 of file translator_pl.h.
    {
        return "Dokumentacja struktur";
    }
trStructIndex()
QCString TranslatorPolish::trStructIndex () inline override virtual
Implements Translator.
Definition at line 2114 of file translator_pl.h.
    {
        return "Indeks struktur";
    }
trStructList()
QCString TranslatorPolish::trStructList () inline override virtual
Implements Translator.
Definition at line 2118 of file translator_pl.h.
    {
        return "Lista struktur";
    }
trStructListDescription()
QCString TranslatorPolish::trStructListDescription () inline override virtual
Implements Translator.
Definition at line 2122 of file translator_pl.h.
    {
        return "Tutaj znajduj si struktury wraz z ich krtkimi opisami:";
    }
trStructs()
QCString TranslatorPolish::trStructs () inline override virtual
Implements Translator.
Definition at line 2110 of file translator_pl.h.
    {
        return "Struktury";
    }
trSubprogram()
QCString TranslatorPolish::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1656 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "podprogram", "y");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorPolish::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1535 of file translator_pl.h.
    { return "Dokumentacja funkcji/podprogramu"; }
trSubprograms()
QCString TranslatorPolish::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1529 of file translator_pl.h.
    { return "Funkcje/podprogramy"; }
trTemplateParameters()
QCString TranslatorPolish::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1800 of file translator_pl.h.
    { return "Parametry Szablonu"; }
trTest()
QCString TranslatorPolish::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1047 of file translator_pl.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorPolish::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1052 of file translator_pl.h.
    {
      return "Lista testw";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorPolish::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 133 of file translator_pl.h.
    { return "To jest kompletna lista skadowych dla"; }
trTodo()
QCString TranslatorPolish::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 929 of file translator_pl.h.
    {
      return "Do zrobienia";
    }
trTodoList()
QCString TranslatorPolish::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 934 of file translator_pl.h.
    {
      return "Lista rzeczy do zrobienia";
    }
trTopicDocumentation()
QCString TranslatorPolish::trTopicDocumentation () inline override virtual
Implements Translator.
Definition at line 2510 of file translator_pl.h.
    { return "Dokumentacja sekcji"; }
trTopicIndex()
QCString TranslatorPolish::trTopicIndex () inline override virtual
Implements Translator.
Definition at line 2514 of file translator_pl.h.
    { return "Indeks sekcji"; }
trTopicList()
QCString TranslatorPolish::trTopicList () inline override virtual
Implements Translator.
Definition at line 2512 of file translator_pl.h.
    { return "Lista sekcji"; }
trTopicListDescription()
QCString TranslatorPolish::trTopicListDescription () inline override virtual
Implements Translator.
Definition at line 2516 of file translator_pl.h.
    { return "Tutaj jest lista wszystkich sekcji wraz z ich krtkimi opisami:"; }
trTopics()
QCString TranslatorPolish::trTopics () inline override virtual
Implements Translator.
Definition at line 2508 of file translator_pl.h.
    { return "Sekcje"; }
trType()
QCString TranslatorPolish::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1648 of file translator_pl.h.
    {
      return createNoun(first_capital, singular, "typ", "y");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trTypeConstraints()
QCString TranslatorPolish::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1662 of file translator_pl.h.
    {
      return "Ograniczenia typw";
    }
trTypedefDocumentation()
QCString TranslatorPolish::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 458 of file translator_pl.h.
    { return "Dokumentacja definicji typw"; }
trTypedefs()
QCString TranslatorPolish::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 422 of file translator_pl.h.
    { return "Definicje typw"; }
trTypeDocumentation()
QCString TranslatorPolish::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1523 of file translator_pl.h.
    { return "Dokumentacja typw danych"; }
trVariableDocumentation()
QCString TranslatorPolish::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 476 of file translator_pl.h.
    { return "Dokumentacja zmiennych"; }
trVariables()
QCString TranslatorPolish::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 440 of file translator_pl.h.
    { return "Zmienne"; }
trVersion()
QCString TranslatorPolish::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 516 of file translator_pl.h.
    { return "Wersja"; }
trVhdlType()
QCString TranslatorPolish::trVhdlType (VhdlSpecifier type, bool single) inline override virtual
VHDL type.
Implements Translator.
Definition at line 1968 of file translator_pl.h.
    {
      switch(type)
      {
        case VhdlSpecifier::LIBRARY:
          if (single) return "Biblioteka";
          else        return "Biblioteki";
        case VhdlSpecifier::PACKAGE:
          if (single) return "Pakiet";
          else        return "Pakiety";
        case VhdlSpecifier::SIGNAL:
          if (single) return "Sygna";
          else        return "Sygnay";
        case VhdlSpecifier::COMPONENT:
          if (single) return "Komponent";
          else        return "Komponenty";
        case VhdlSpecifier::CONSTANT:
          if (single) return "Staa";
          else        return "Stae";
        case VhdlSpecifier::ENTITY:
          if (single) return "Jednostka";
          else        return "Jednostki";
        case VhdlSpecifier::TYPE:
          if (single) return "Typ";
          else        return "Typy";
        case VhdlSpecifier::SUBTYPE:
          if (single) return "Podtyp";
          else        return "Podtypy";
        case VhdlSpecifier::FUNCTION:
          if (single) return "Funkcja";
          else        return "Funkcje";
        case VhdlSpecifier::RECORD:
          if (single) return "Rekord";
          else        return "Rekordy";
        case VhdlSpecifier::PROCEDURE:
          if (single) return "Procedura";
          else        return "Procedury";
        case VhdlSpecifier::ARCHITECTURE:
          if (single) return "Architektura";
          else        return "Architektury";
        case VhdlSpecifier::ATTRIBUTE:
          if (single) return "Atrybut";
          else        return "Atrybuty";
        case VhdlSpecifier::PROCESS:
          if (single) return "Proces";
          else        return "Procesy";
        case VhdlSpecifier::PORT:
          if (single) return "Port";
          else        return "Porty";
        case VhdlSpecifier::USE:
          if (single) return "Klauzula uycia";
          else        return "Klauzule uycia";
        case VhdlSpecifier::GENERIC:
          if (single) return "Generyczny";
          else        return "Generyczne";
        case VhdlSpecifier::PACKAGE_BODY:
          return "Ciao pakietu";
        case VhdlSpecifier::UNITS:
          return "Jednostki";
        case VhdlSpecifier::SHAREDVARIABLE:
          if (single) return "Wspdzielona zmienna";
          else        return "Wspdzielone zmienne";
        case VhdlSpecifier::VFILE:
          if (single) return "Plik";
          else        return "Pliki";
        case VhdlSpecifier::GROUP:
          if (single) return "Grupa";
          else        return "Grupy";
        case VhdlSpecifier::INSTANTIATION:
          if (single) return "Utworzona instancja";
          else        return "Utworzone instancje";
        case VhdlSpecifier::ALIAS:
          if (single) return "Alias";
          else        return "Aliasy";
        case VhdlSpecifier::CONFIG:
          if (single) return "Konfiguracja";
          else        return "Konfiguracje";
        case VhdlSpecifier::MISCELLANEOUS:
          return "Rne";
        case VhdlSpecifier::UCF_CONST:
          return "Ograniczenia";
        default:
          return "Klasa";
      }
    }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorPolish::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 512 of file translator_pl.h.
    { return "Ostrzeenie"; }
trWriteList()
QCString TranslatorPolish::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 641 of file translator_pl.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_pl.h