Doxygen: src/index.h File Reference
index.h File Reference
#include <memory>
#include <vector>
#include <map>
#include "qcstring.h"
#include "construct.h"
Classes
class Index
Namespaces
namespace ClassMemberHighlight
namespace FileMemberHighlight
namespace NamespaceMemberHighlight
namespace ModuleMemberHighlight
Enumerations
enum class IndexSection {
isTitlePageStart , isTitlePageAuthor , isMainPage , isModuleIndex ,
isTopicIndex , isDirIndex , isNamespaceIndex , isConceptIndex ,
isClassHierarchyIndex , isCompoundIndex , isFileIndex , isPageIndex ,
isModuleDocumentation , isTopicDocumentation , isDirDocumentation , isNamespaceDocumentation ,
isClassDocumentation , isConceptDocumentation , isFileDocumentation , isExampleDocumentation ,
isPageDocumentation , isPageDocumentation2 , isEndIndex
}
enum class HighlightedItem {
None =0 , Main , Modules , Namespaces ,
Topics , ClassHierarchy , InterfaceHierarchy , ExceptionHierarchy ,
Classes , Concepts , Interfaces , Structs ,
Exceptions , AnnotatedClasses , AnnotatedInterfaces , AnnotatedStructs ,
AnnotatedExceptions , Files , NamespaceMembers , ModuleMembers ,
Functions , Globals , Pages , Examples ,
Search , UserGroup , ClassVisible , ConceptVisible ,
InterfaceVisible , StructVisible , ExceptionVisible , NamespaceVisible ,
FileVisible , ModuleVisible
}
enum ClassMemberHighlight::Enum : int {
ClassMemberHighlight::All = 0 , ClassMemberHighlight::Functions , ClassMemberHighlight::Variables , ClassMemberHighlight::Typedefs ,
ClassMemberHighlight::Enums , ClassMemberHighlight::EnumValues , ClassMemberHighlight::Properties , ClassMemberHighlight::Events ,
ClassMemberHighlight::Related , ClassMemberHighlight::Total
}
enum FileMemberHighlight::Enum : int {
FileMemberHighlight::All = 0 , FileMemberHighlight::Functions , FileMemberHighlight::Variables , FileMemberHighlight::Typedefs ,
FileMemberHighlight::Sequences , FileMemberHighlight::Dictionaries , FileMemberHighlight::Enums , FileMemberHighlight::EnumValues ,
FileMemberHighlight::Defines , FileMemberHighlight::Total
}
enum NamespaceMemberHighlight::Enum : int {
NamespaceMemberHighlight::All = 0 , NamespaceMemberHighlight::Functions , NamespaceMemberHighlight::Variables , NamespaceMemberHighlight::Typedefs ,
NamespaceMemberHighlight::Sequences , NamespaceMemberHighlight::Dictionaries , NamespaceMemberHighlight::Enums , NamespaceMemberHighlight::EnumValues ,
NamespaceMemberHighlight::Total
}
enum ModuleMemberHighlight::Enum : int {
ModuleMemberHighlight::All = 0 , ModuleMemberHighlight::Functions , ModuleMemberHighlight::Variables , ModuleMemberHighlight::Typedefs ,
ModuleMemberHighlight::Enums , ModuleMemberHighlight::EnumValues , ModuleMemberHighlight::Total
}
Functions
void writeGraphInfo (OutputList &ol)
void writeIndexHierarchy (OutputList &ol)
void startTitle (OutputList &ol, const QCString &fileName, const DefinitionMutable *def=nullptr)
void endTitle (OutputList &ol, const QCString &fileName, const QCString &name)
void startFile (OutputList &ol, const QCString &name, const QCString &manName, const QCString &title, HighlightedItem hli=HighlightedItem::None, bool additionalIndices=FALSE, const QCString &altSidebarName=QCString(), int hierarchyLevel=0)
void endFile (OutputList &ol, bool skipNavIndex=FALSE, bool skipEndContents=FALSE, const QCString &navPath=QCString())
void endFileWithNavPath (OutputList &ol, const Definition *d)
Enumeration Type Documentation
HighlightedItem
enum class HighlightedItem strong
Enumerator
None
Main
Modules
Namespaces
Topics
ClassHierarchy
InterfaceHierarchy
ExceptionHierarchy
Classes
Concepts
Interfaces
Structs
Exceptions
AnnotatedClasses
AnnotatedInterfaces
AnnotatedStructs
AnnotatedExceptions
Files
NamespaceMembers
ModuleMembers
Functions
Globals
Pages
Examples
Search
UserGroup
ClassVisible
ConceptVisible
InterfaceVisible
StructVisible
ExceptionVisible
NamespaceVisible
FileVisible
ModuleVisible
Definition at line 58 of file index.h.
{
  None=0,
  Main,
  Modules,
  Namespaces,
  Topics,
  ClassHierarchy,
  InterfaceHierarchy,
  ExceptionHierarchy,
  Classes,
  Concepts,
  Interfaces,
  Structs,
  Exceptions,
  AnnotatedClasses,
  AnnotatedInterfaces,
  AnnotatedStructs,
  AnnotatedExceptions,
  Files,
  NamespaceMembers,
  ModuleMembers,
  Functions,
  Globals,
  Pages,
  Examples,
  Search,
  UserGroup,
  ClassVisible,
  ConceptVisible,
  InterfaceVisible,
  StructVisible,
  ExceptionVisible,
  NamespaceVisible,
  FileVisible,
  ModuleVisible
};
IndexSection
enum class IndexSection strong
Enumerator
isTitlePageStart
isTitlePageAuthor
isMainPage
isModuleIndex
isTopicIndex
isDirIndex
isNamespaceIndex
isConceptIndex
isClassHierarchyIndex
isCompoundIndex
isFileIndex
isPageIndex
isModuleDocumentation
isTopicDocumentation
isDirDocumentation
isNamespaceDocumentation
isClassDocumentation
isConceptDocumentation
isFileDocumentation
isExampleDocumentation
isPageDocumentation
isPageDocumentation2
isEndIndex
Definition at line 31 of file index.h.
{
  isTitlePageStart,
  isTitlePageAuthor,
  isMainPage,
  isModuleIndex,
  isTopicIndex,
  isDirIndex,
  isNamespaceIndex,
  isConceptIndex,
  isClassHierarchyIndex,
  isCompoundIndex,
  isFileIndex,
  isPageIndex,
  isModuleDocumentation,
  isTopicDocumentation,
  isDirDocumentation,
  isNamespaceDocumentation,
  isClassDocumentation,
  isConceptDocumentation,
  isFileDocumentation,
  isExampleDocumentation,
  isPageDocumentation,
  isPageDocumentation2,
  isEndIndex
};
Function Documentation
endFile()
void endFile (OutputList & ol, bool skipNavIndex = FALSE, bool skipEndContents = FALSE, const QCString & navPath = QCString())
Definition at line 421 of file index.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  if (!skipNavIndex)
  {
    if (!skipEndContents) ol.endContents();
    if (generateTreeView)
    {
      ol.writeString("</div><!-- doc-content -->\n");
    }
  }
  ol.writeFooter(navPath); // write the footer
  ol.popGeneratorState();
  ol.endFile();
}
References Config_getBool, OutputList::disableAllBut(), OutputList::endContents(), OutputList::endFile(), Html, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::writeFooter(), and OutputList::writeString().
Referenced by endFileWithNavPath(), generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndexFiltered(), writeConceptIndex(), GroupDefImpl::writeDocumentation(), ModuleDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), ClassDefImpl::writeMemberList(), writeModuleIndex(), writeModuleMemberIndexFiltered(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), writeTopicIndex(), and writeUserGroupStubPage().
endFileWithNavPath()
void endFileWithNavPath (OutputList & ol, const Definition * d)
Definition at line 441 of file index.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  QCString navPath;
  if (generateTreeView)
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputType::Html);
    ol.writeString("</div><!-- doc-content -->\n");
    ol.popGeneratorState();
    navPath = d->navigationPathAsString();
  }
  endFile(ol,generateTreeView,TRUE,navPath);
}
References Config_getBool, OutputList::disableAllBut(), endFile(), Html, Definition::navigationPathAsString(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), TRUE, and OutputList::writeString().
Referenced by ClassDefImpl::writeDocumentation(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), and FileDefImpl::writeSourceFooter().
endTitle()
void endTitle (OutputList & ol, const QCString & fileName, const QCString & name)
Definition at line 395 of file index.cpp.
{
  ol.popGeneratorState();
  ol.endTitleHead(fileName,name);
  ol.endHeaderSection();
}
References OutputList::endHeaderSection(), OutputList::endTitleHead(), and OutputList::popGeneratorState().
Referenced by generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeConceptIndex(), ClassDefImpl::writeDocumentation(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeMemberList(), writeModuleIndex(), writeNamespaceIndex(), writePageIndex(), FileDefImpl::writeSourceHeader(), writeTopicIndex(), and writeUserGroupStubPage().
startFile()
void startFile (OutputList & ol, const QCString & name, const QCString & manName, const QCString & title, HighlightedItem hli = HighlightedItem::None, bool additionalIndices = FALSE, const QCString & altSidebarName = QCString(), int hierarchyLevel = 0)
Definition at line 402 of file index.cpp.
{
  bool disableIndex = Config_getBool(DISABLE_INDEX);
  ol.startFile(name,manName,title,hierarchyLevel);
  ol.startQuickIndices();
  if (!disableIndex)
  {
    ol.writeQuickLinks(hli,name);
  }
  if (!additionalIndices)
  {
    ol.endQuickIndices();
  }
  ol.writeSplitBar(!altSidebarName.isEmpty() ? altSidebarName : name);
  ol.writeSearchInfo();
}
References Config_getBool, OutputList::endQuickIndices(), QCString::isEmpty(), OutputList::startFile(), OutputList::startQuickIndices(), OutputList::writeQuickLinks(), OutputList::writeSearchInfo(), and OutputList::writeSplitBar().
Referenced by generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeConceptIndex(), ClassDefImpl::writeDocumentation(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), ModuleDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeMemberList(), writeModuleIndex(), writeNamespaceIndex(), writePageIndex(), FileDefImpl::writeSourceHeader(), writeTopicIndex(), and writeUserGroupStubPage().
startTitle()
void startTitle (OutputList & ol, const QCString & fileName, const DefinitionMutable * def = nullptr)
Definition at line 386 of file index.cpp.
{
  ol.startHeaderSection();
  if (def) def->writeSummaryLinks(ol);
  ol.startTitleHead(fileName);
  ol.pushGeneratorState();
  ol.disable(OutputType::Man);
}
References OutputList::disable(), Man, OutputList::pushGeneratorState(), OutputList::startHeaderSection(), OutputList::startTitleHead(), and DefinitionMutable::writeSummaryLinks().
Referenced by generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeConceptIndex(), ClassDefImpl::writeDocumentation(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeMemberList(), writeModuleIndex(), writeNamespaceIndex(), writePageIndex(), FileDefImpl::writeSourceHeader(), writeTopicIndex(), and writeUserGroupStubPage().
writeGraphInfo()
void writeGraphInfo (OutputList & ol)
Definition at line 3946 of file index.cpp.
{
  if (!Config_getBool(HAVE_DOT) || !Config_getBool(GENERATE_HTML)) return;
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  DotLegendGraph gd;
  gd.writeGraph(Config_getString(HTML_OUTPUT));
  bool oldStripCommentsState = Config_getBool(STRIP_CODE_COMMENTS);
  bool oldCreateSubdirs = Config_getBool(CREATE_SUBDIRS);
  // temporarily disable the stripping of comments for our own code example!
  Config_updateBool(STRIP_CODE_COMMENTS,FALSE);
  // temporarily disable create subdirs for linking to our example
  Config_updateBool(CREATE_SUBDIRS,FALSE);
  startFile(ol,"graph_legend",QCString(),theTranslator->trLegendTitle());
  startTitle(ol,QCString());
  ol.parseText(theTranslator->trLegendTitle());
  endTitle(ol,QCString(),QCString());
  ol.startContents();
  QCString legendDocs = theTranslator->trLegendDocs();
  int s = legendDocs.find("<center>");
  int e = legendDocs.find("</center>");
  QCString imgExt = getDotImageExtension();
  if (imgExt=="svg" && s!=-1 && e!=-1)
  {
    legendDocs = legendDocs.left(s+8) + "[!-- " + "SVG 0 --]" + legendDocs.mid(e);
    //printf("legendDocs=%s\n",qPrint(legendDocs));
  }
  {
    auto fd = createFileDef("","graph_legend.dox");
    ol.generateDoc("graph_legend",1,fd.get(),nullptr,legendDocs,FALSE,FALSE,
        QCString(),FALSE,FALSE,FALSE);
  }
  // restore config settings
  Config_updateBool(STRIP_CODE_COMMENTS,oldStripCommentsState);
  Config_updateBool(CREATE_SUBDIRS,oldCreateSubdirs);
  endFile(ol);
  ol.popGeneratorState();
}
References Config_getBool, Config_getString, Config_updateBool, createFileDef(), OutputList::disableAllBut(), endFile(), endTitle(), FALSE, QCString::find(), OutputList::generateDoc(), getDotImageExtension(), Html, QCString::left(), QCString::mid(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startContents(), startFile(), startTitle(), theTranslator, and DotLegendGraph::writeGraph().
Referenced by generateOutput().
writeIndexHierarchy()
void writeIndexHierarchy (OutputList & ol)
Definition at line 5587 of file index.cpp.
{
  writeMenuData();
  LayoutNavEntry *lne = LayoutDocManager::instance().rootNavEntry();
  if (lne)
  {
    writeIndexHierarchyEntries(ol,lne->children());
  }
}
References LayoutNavEntry::children(), LayoutDocManager::instance(), LayoutDocManager::rootNavEntry(), writeIndexHierarchyEntries(), and writeMenuData().
Referenced by generateOutput().