Doxygen: MemberListType Class Reference
MemberListType Class Reference
Wrapper class for the MemberListType type.
#include <src/types.h>
Public Member Functions
constexpr bool isInvalid () const
ML_TYPES constexpr bool isPublic () const
constexpr bool isOnlyPublic () const
constexpr bool isProtected () const
constexpr bool isPackage () const
constexpr bool isPrivate () const
constexpr bool isDetailed () const
constexpr bool isDeclaration () const
constexpr bool isDocumentation () const
std::string to_string () const
int to_int () const
constexpr const char * toLabel () const
constexpr const char * toXML () const
MemberListType toPublic () const
MemberListType toProtected () const
Static Public Member Functions
static MemberListType Invalid ()
Private Types
enum CategoryBits {
Public = (1<<16) , Protected = (1<<17) , Package = (1<<18) , Private = (1<<19) ,
OnlyPublic = (1<<20) , Detailed = (1<<21) , Declaration = (1<<22) , Documentation = (1<<23) ,
TypeMask = 0x0000FFFF , CategoryMask = 0xFFFF0000
}
enum TypeName { Invalid_ = -1 , ML_TYPES }
Private Member Functions
MemberListType (int t)
std::string bits_to_string () const
constexpr TypeName type () const
Private Attributes
int m_type = static_cast<int>(Invalid_)
Friends
bool operator== (const MemberListType &t1, const MemberListType &t2)
bool operator!= (const MemberListType &t1, const MemberListType &t2)
Detailed Description
Wrapper class for the MemberListType type.
Can be set only during construction. Packs the type together with category flags.
Definition at line 183 of file types.h.
Member Enumeration Documentation
CategoryBits
enum MemberListType::CategoryBits private
Enumerator
Public
Protected
Package
Private
OnlyPublic
Detailed
Declaration
Documentation
TypeMask
CategoryMask
Definition at line 185 of file types.h.
    {
      Public        = (1<<16),
      Protected     = (1<<17),
      Package       = (1<<18),
      Private       = (1<<19),
      OnlyPublic    = (1<<20),
      Detailed      = (1<<21),
      Declaration   = (1<<22),
      Documentation = (1<<23),
      TypeMask      = 0x0000FFFF,
      CategoryMask  = 0xFFFF0000
    };
TypeName
enum MemberListType::TypeName private
Enumerator
Invalid_
ML_TYPES
Definition at line 199 of file types.h.
    {
      Invalid_ = -1,
#define ML_TYPE(x,bits,to_pub,to_prot,label,xml_str) \
      x##_,
      ML_TYPES
#undef ML_TYPE
    };
Constructor & Destructor Documentation
MemberListType()
MemberListType::MemberListType (int t) inline explicit private
Definition at line 292 of file types.h.
: m_type(t) {}
References m_type.
Referenced by Invalid(), operator!=, operator==, toProtected(), and toPublic().
Member Function Documentation
bits_to_string()
std::string MemberListType::bits_to_string () const inline private
Definition at line 293 of file types.h.
    {
      std::string result;
      if (m_type&Public) result+=",Public";
      if (m_type&Protected) result+=",Protected";
      if (m_type&Package) result+=",Package";
      if (m_type&Private) result+=",Private";
      if (m_type&OnlyPublic) result+=",OnlyPublic";
      if (m_type&Detailed) result+=",Detailed";
      if (m_type&Documentation) result+=",Documentation";
      return result;
    }
References Detailed, Documentation, m_type, OnlyPublic, Package, Private, Protected, and Public.
Invalid()
static MemberListType MemberListType::Invalid () inline static
Definition at line 209 of file types.h.
{ return MemberListType(Invalid_); }
References Invalid_, and MemberListType().
Referenced by convertProtectionLevel(), ClassDefImpl::countInheritedDecMembers(), toProtected(), toPublic(), ClassDefImpl::writeAdditionalInheritedMembers(), and ClassDefImpl::writeInheritedMemberDeclarations().
isDeclaration()
bool MemberListType::isDeclaration () const inline constexpr
Definition at line 222 of file types.h.
{ return (m_type & Declaration)!=0;   }
References Declaration, and m_type.
Referenced by generateSqlite3ForFile(), generateSqlite3ForGroup(), generateSqlite3ForModule(), generateSqlite3ForNamespace(), generateXMLForFile(), generateXMLForGroup(), generateXMLForModule(), and generateXMLForNamespace().
isDetailed()
bool MemberListType::isDetailed () const inline constexpr
Definition at line 221 of file types.h.
{ return (m_type & Detailed)!=0;      }
References Detailed, and m_type.
Referenced by generateSqlite3ForClass(), and generateXMLForClass().
isDocumentation()
bool MemberListType::isDocumentation () const inline constexpr
Definition at line 223 of file types.h.
{ return (m_type & Documentation)!=0; }
References Documentation, and m_type.
isInvalid()
bool MemberListType::isInvalid () const inline constexpr
Definition at line 210 of file types.h.
{ return m_type==Invalid_; }
References Invalid_, and m_type.
Referenced by ClassDefImpl::countInheritedDecMembers(), ClassDefImpl::countMemberDeclarations(), and ClassDefImpl::writeInheritedMemberDeclarations().
isOnlyPublic()
bool MemberListType::isOnlyPublic () const inline constexpr
Definition at line 217 of file types.h.
{ return (m_type & OnlyPublic)!=0;    }
References m_type, and OnlyPublic.
isPackage()
bool MemberListType::isPackage () const inline constexpr
Definition at line 219 of file types.h.
{ return (m_type & Package)!=0;       }
References m_type, and Package.
isPrivate()
bool MemberListType::isPrivate () const inline constexpr
Definition at line 220 of file types.h.
{ return (m_type & Private)!=0;       }
References m_type, and Private.
Referenced by convertProtectionLevel().
isProtected()
bool MemberListType::isProtected () const inline constexpr
Definition at line 218 of file types.h.
{ return (m_type & Protected)!=0;     }
References m_type, and Protected.
Referenced by convertProtectionLevel().
isPublic()
ML_TYPES constexpr bool MemberListType::isPublic () const inline constexpr
Definition at line 216 of file types.h.
{ return (m_type & Public)!=0;        }
References m_type, and Public.
Referenced by convertProtectionLevel().
to_int()
int MemberListType::to_int () const inline
Definition at line 236 of file types.h.
    {
      return m_type!=Invalid_ ? m_type&TypeMask : -1;
    }
References Invalid_, m_type, and TypeMask.
to_string()
std::string MemberListType::to_string () const inline
Definition at line 224 of file types.h.
    {
      switch (type())
      {
        case Invalid_: return "[Invalid]";
#define ML_TYPE(x,bits,to_pub,to_prot,label,xml_str) \
        case x##_ : return "["+std::string(#x)+bits_to_string()+"]";
        ML_TYPES
#undef ML_TYPE
      }
      return "[unknown]";
    }
References Invalid_, ML_TYPES, and type().
Referenced by fmt::formatter< MemberListType >::format().
toLabel()
const char * MemberListType::toLabel () const inline constexpr
Definition at line 240 of file types.h.
    {
      switch (type())
      {
        case Invalid_: return "";
#define ML_TYPE(x,bits,to_pub,to_prot,label,xml_str) \
        case x##_ : return label;
        ML_TYPES
#undef ML_TYPE
      }
      return "";
    }
References Invalid_, ML_TYPES, and type().
Referenced by MemberList::writeDeclarations(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), ModuleDefImpl::writeSummaryLinks(), and NamespaceDefImpl::writeSummaryLinks().
toProtected()
MemberListType MemberListType::toProtected () const inline
Definition at line 276 of file types.h.
    {
      switch (type())
      {
        case Invalid_: return Invalid();
#define ML_TYPE(x,bits,to_pub,to_prot,label,xml_str) \
        case x##_ : return to_prot();
        ML_TYPES
#undef ML_TYPE
      }
      return Invalid();
    }
References Invalid(), Invalid_, MemberListType(), ML_TYPES, and type().
Referenced by convertProtectionLevel().
toPublic()
MemberListType MemberListType::toPublic () const inline
Definition at line 264 of file types.h.
    {
      switch (type())
      {
        case Invalid_: return Invalid();
#define ML_TYPE(x,bits,to_pub,to_prot,label,xml_str) \
        case x##_ : return to_pub();
        ML_TYPES
#undef ML_TYPE
      }
      return Invalid();
    }
References Invalid(), Invalid_, MemberListType(), ML_TYPES, and type().
Referenced by convertProtectionLevel().
toXML()
const char * MemberListType::toXML () const inline constexpr
Definition at line 252 of file types.h.
    {
      switch (type())
      {
        case Invalid_: return "";
#define ML_TYPE(x,bits,to_pub,to_prot,label,xml_str) \
        case x##_ : return xml_str;
        ML_TYPES
#undef ML_TYPE
      }
      return "";
    }
References Invalid_, ML_TYPES, and type().
Referenced by generateXMLForClass(), generateXMLForFile(), generateXMLForGroup(), generateXMLForModule(), and generateXMLForNamespace().
type()
TypeName MemberListType::type () const inline constexpr private
Definition at line 305 of file types.h.
{ return static_cast<TypeName>(m_type & TypeMask); }
References m_type, and TypeMask.
Referenced by to_string(), toLabel(), toProtected(), toPublic(), and toXML().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const MemberListType & t1, const MemberListType & t2) friend
Definition at line 289 of file types.h.
{ return !(operator==(t1,t2)); }
References MemberListType(), and operator==.
operator==
bool operator== (const MemberListType & t1, const MemberListType & t2) friend
Definition at line 288 of file types.h.
{ return t1.m_type==t2.m_type; }
References m_type, and MemberListType().
Referenced by operator!=.
Member Data Documentation
m_type
int MemberListType::m_type = static_cast<int>(Invalid_) private
Definition at line 306 of file types.h.
Referenced by bits_to_string(), isDeclaration(), isDetailed(), isDocumentation(), isInvalid(), isOnlyPublic(), isPackage(), isPrivate(), isProtected(), isPublic(), MemberListType(), operator==, to_int(), and type().
The documentation for this class was generated from the following file:
src/types.h