Doxygen: TemplateImmutableStruct Class Reference
TemplateImmutableStruct Class Reference
Template API
Default implementation of an immutable context value of type struct.
#include <template.h>
Classes
class Private
Private data of a template struct object.
Public Types
using StructField = std::pair< const std::string, TemplateVariant >
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
Gets the value for a field name.
virtual StringVector fields () const
Return the list of fields.
TemplateImmutableStruct (std::initializer_list< StructField > fields)
Creates a struct.
virtual ~TemplateImmutableStruct ()
Destroys the struct.
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()=default
Destroys the struct.
Static Public Member Functions
static TemplateStructIntfPtr alloc (std::initializer_list< StructField > fields)
Creates an instance and returns a shared pointer to it.
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Default implementation of an immutable context value of type struct.
Definition at line 367 of file template.h.
Member Typedef Documentation
StructField
using TemplateImmutableStruct::StructField = std::pair<const std::string,TemplateVariant>
Definition at line 374 of file template.h.
Constructor & Destructor Documentation
TemplateImmutableStruct()
TemplateImmutableStruct::TemplateImmutableStruct (std::initializer_list< StructField > fields)
Creates a struct.
Definition at line 453 of file template.cpp.
  : p(std::make_unique<Private>(fields))
{
}
~TemplateImmutableStruct()
TemplateImmutableStruct::~TemplateImmutableStruct () virtual
Destroys the struct.
Definition at line 459 of file template.cpp.
{
}
Member Function Documentation
alloc()
TemplateStructIntfPtr TemplateImmutableStruct::alloc (std::initializer_list< StructField > fields) static
Creates an instance and returns a shared pointer to it.
Parameters
fields the fields of the struct as key/value pairs.
Definition at line 480 of file template.cpp.
{
  return std::make_shared<TemplateImmutableStruct>(fields);
}
References fields().
Referenced by ClassContext::Private::createExamples(), MemberContext::Private::createExamples(), and DefinitionContext< T >::DefinitionContext().
fields()
StringVector TemplateImmutableStruct::fields () const virtual
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 469 of file template.cpp.
{
  StringVector result;
  for (const auto &[name,variant] : p->fields)
  {
    result.push_back(name);
  }
  std::sort(result.begin(),result.end());
  return result;
}
References p.
Referenced by alloc().
get()
TemplateVariant TemplateImmutableStruct::get (const QCString & name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 463 of file template.cpp.
{
  auto it = p->fields.find(name.str());
  return it!=p->fields.end() ? it->second : TemplateVariant();
}
References p, and QCString::str().
Member Data Documentation
p
std::unique_ptr<Private> TemplateImmutableStruct::p private
Definition at line 389 of file template.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/template.h
/home/runner/work/doxygen/doxygen/src/template.cpp