Doxygen: DocVhdlFlow Class Reference
DocVhdlFlow Class Reference
Node representing a VHDL flow chart.
#include <src/docnode.h>
Public Member Functions
DocVhdlFlow (DocParser *parser, DocNodeVariant *parent)
void parse ()
bool hasCaption () const
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a VHDL flow chart.
Definition at line 727 of file docnode.h.
Constructor & Destructor Documentation
DocVhdlFlow()
DocVhdlFlow::DocVhdlFlow (DocParser * parser, DocNodeVariant * parent)
Definition at line 1211 of file docnode.cpp.
                                                                 : DocCompoundNode(parser,parent)
{
}
References DocCompoundNode::DocCompoundNode(), DocNode::parent(), and DocNode::parser().
Member Function Documentation
hasCaption()
bool DocVhdlFlow::hasCaption () const inline
Definition at line 732 of file docnode.h.
{ return !children().empty(); }
References DocCompoundNode::children(), and GrowVector< T >::empty().
Referenced by HtmlDocVisitor::operator()().
parse()
void DocVhdlFlow::parse ()
Definition at line 1215 of file docnode.cpp.
{
  AUTO_TRACE();
  auto ns = AutoNodeStack(parser(),thisVariant());
  parser()->tokenizer.setStateTitle();
  Token tok = parser()->tokenizer.lex();
  while (!tok.is_any_of(TokenRetval::TK_NONE, TokenRetval::TK_EOF))
  {
    if (!parser()->defaultHandleToken(thisVariant(),tok,children()))
    {
      parser()->errorHandleDefaultToken(thisVariant(),tok,children(),"\\vhdlflow");
    }
    tok = parser()->tokenizer.lex();
  }
  parser()->tokenizer.lex();
  parser()->tokenizer.setStatePara();
  parser()->handlePendingStyleCommands(thisVariant(),children());
  VhdlDocGen::createFlowChart(parser()->context.memberDef);
}
References AUTO_TRACE, DocCompoundNode::children(), VhdlDocGen::createFlowChart(), DocParser::errorHandleDefaultToken(), DocParser::handlePendingStyleCommands(), Token::is_any_of(), DocTokenizer::lex(), DocNode::parser(), DocTokenizer::setStatePara(), DocTokenizer::setStateTitle(), DocNode::thisVariant(), and DocParser::tokenizer.
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp