Doxygen: src/perlmodgen.cpp File Reference
perlmodgen.cpp File Reference
#include <stdlib.h>
#include <stack>
#include "perlmodgen.h"
#include "docparser.h"
#include "docnode.h"
#include "message.h"
#include "doxygen.h"
#include "pagedef.h"
#include "memberlist.h"
#include "arguments.h"
#include "config.h"
#include "groupdef.h"
#include "classdef.h"
#include "classlist.h"
#include "filename.h"
#include "membername.h"
#include "namespacedef.h"
#include "membergroup.h"
#include "section.h"
#include "util.h"
#include "htmlentity.h"
#include "emoji.h"
#include "dir.h"
#include "portable.h"
#include "moduledef.h"
#include "construct.h"
Classes
class PerlModOutputStream
class PerlModOutput
class PerlModDocVisitor
Concrete visitor implementation for PerlMod output.
class PerlModGenerator
Macros
#define PERLOUTPUT_MAX_INDENTATION 40
Functions
static void addTemplateArgumentList (const ArgumentList &al, PerlModOutput &output, const QCString &)
static void addTemplateList (const ClassDef *cd, PerlModOutput &output)
static void addTemplateList (const ConceptDef *cd, PerlModOutput &output)
static void addPerlModDocBlock (PerlModOutput &output, const QCString &name, const QCString &fileName, int lineNr, const Definition *scope, const MemberDef *md, const QCString &text)
static const char * getProtectionName (Protection prot)
static const char * getVirtualnessName (Specifier virt)
void setPerlModDoxyfile (const QCString &qs)
void generatePerlMod ()
Variables
static QCString pathDoxyfile
static QCString pathDoxyExec
Macro Definition Documentation
PERLOUTPUT_MAX_INDENTATION
#define PERLOUTPUT_MAX_INDENTATION 40
Definition at line 45 of file perlmodgen.cpp.
Referenced by PerlModOutput::decIndent(), and PerlModOutput::incIndent().
Function Documentation
addPerlModDocBlock()
static void addPerlModDocBlock (PerlModOutput & output, const QCString & name, const QCString & fileName, int lineNr, const Definition * scope, const MemberDef * md, const QCString & text) static
Definition at line 1355 of file perlmodgen.cpp.
{
  QCString stext = text.stripWhiteSpace();
  if (stext.isEmpty())
  {
    output.addField(name).add("{}");
  }
  else
  {
    auto parser { createDocParser() };
    auto ast    { validatingParseDoc(*parser.get(),
                                     fileName,lineNr,scope,md,stext,FALSE,FALSE,
                                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    output.openHash(name);
    auto astImpl = dynamic_cast<const DocNodeAST*>(ast.get());
    if (astImpl)
    {
      PerlModDocVisitor visitor(output);
      std::visit(visitor,astImpl->root);
      visitor.finish();
    }
    output.closeHash();
  }
}
References PerlModOutput::add(), PerlModOutput::addField(), PerlModOutput::closeHash(), Config_getBool, createDocParser(), FALSE, PerlModDocVisitor::finish(), QCString::isEmpty(), PerlModOutput::openHash(), QCString::stripWhiteSpace(), and validatingParseDoc().
Referenced by PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForConcept(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForModule(), PerlModGenerator::generatePerlModForNamespace(), and PerlModGenerator::generatePerlModForPage().
addTemplateArgumentList()
static void addTemplateArgumentList (const ArgumentList & al, PerlModOutput & output, const QCString &) static
Definition at line 1326 of file perlmodgen.cpp.
{
  if (!al.hasParameters()) return;
  output.openList("template_parameters");
  for (const Argument &a : al)
  {
    output.openHash();
    if (!a.type.isEmpty())
      output.addFieldQuotedString("type", a.type);
    if (!a.name.isEmpty())
      output.addFieldQuotedString("declaration_name", a.name)
        .addFieldQuotedString("definition_name", a.name);
    if (!a.defval.isEmpty())
      output.addFieldQuotedString("default", a.defval);
    output.closeHash();
  }
  output.closeList();
}
References PerlModOutput::addFieldQuotedString(), PerlModOutput::closeHash(), PerlModOutput::closeList(), ArgumentList::hasParameters(), PerlModOutput::openHash(), and PerlModOutput::openList().
Referenced by addTemplateList(), and addTemplateList().
addTemplateList() [1/2]
static void addTemplateList (const ClassDef * cd, PerlModOutput & output) static
Definition at line 1345 of file perlmodgen.cpp.
{
  addTemplateArgumentList(cd->templateArguments(),output,cd->name());
}
References addTemplateArgumentList(), Definition::name(), and ClassDef::templateArguments().
Referenced by PerlModGenerator::generatePerlModForClass(), and PerlModGenerator::generatePerlModForConcept().
addTemplateList() [2/2]
static void addTemplateList (const ConceptDef * cd, PerlModOutput & output) static
Definition at line 1350 of file perlmodgen.cpp.
{
  addTemplateArgumentList(cd->getTemplateParameterList(),output,cd->name());
}
References addTemplateArgumentList(), ConceptDef::getTemplateParameterList(), and Definition::name().
generatePerlMod()
void generatePerlMod ()
Definition at line 2951 of file perlmodgen.cpp.
{
  PerlModGenerator pmg(Config_getBool(PERLMOD_PRETTY));
  pmg.generate();
}
References Config_getBool, and PerlModGenerator::generate().
Referenced by generateOutput().
getProtectionName()
static const char * getProtectionName (Protection prot) static
Definition at line 1386 of file perlmodgen.cpp.
{
  switch (prot)
  {
    case Protection::Public:    return "public";
    case Protection::Protected: return "protected";
    case Protection::Private:   return "private";
    case Protection::Package:   return "package";
  }
  return nullptr;
}
References Package, Private, Protected, and Public.
Referenced by PerlModGenerator::addListOfAllMembers(), PerlModGenerator::generatePerlModForClass(), and PerlModGenerator::generatePerlModForMember().
getVirtualnessName()
static const char * getVirtualnessName (Specifier virt) static
Definition at line 1398 of file perlmodgen.cpp.
{
  switch(virt)
  {
    case Specifier::Normal:  return "non_virtual";
    case Specifier::Virtual: return "virtual";
    case Specifier::Pure:    return "pure_virtual";
  }
  return nullptr;
}
References Normal, Pure, and Virtual.
Referenced by PerlModGenerator::addListOfAllMembers(), PerlModGenerator::generatePerlModForClass(), and PerlModGenerator::generatePerlModForMember().
setPerlModDoxyfile()
void setPerlModDoxyfile (const QCString & qs)
Definition at line 1412 of file perlmodgen.cpp.
{
  pathDoxyfile = qs;
  pathDoxyExec = Dir::currentDirPath();
}
References Dir::currentDirPath(), pathDoxyExec, and pathDoxyfile.
Referenced by readConfiguration().
Variable Documentation
pathDoxyExec
QCString pathDoxyExec static
Definition at line 1410 of file perlmodgen.cpp.
Referenced by PerlModGenerator::generateDoxyRules(), and setPerlModDoxyfile().
pathDoxyfile
QCString pathDoxyfile static
Definition at line 1409 of file perlmodgen.cpp.
Referenced by PerlModGenerator::generateDoxyRules(), and setPerlModDoxyfile().