Doxygen: TranslatorRomanian Class Reference
TranslatorRomanian Class Reference
#include <src/translator_ro.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString updateNeededMessage () override
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString updateNeededMessage () override
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 45 of file translator_ro.h.
Member Function Documentation
getLanguageString()
QCString TranslatorRomanian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 81 of file translator_ro.h.
    {
      return "0x418 Romanian";
    }
idLanguage()
QCString TranslatorRomanian::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 57 of file translator_ro.h.
    { return "romanian"; }
latexLanguageSupportCommand()
QCString TranslatorRomanian::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 73 of file translator_ro.h.
    {
      return "\\usepackage[romanian]{babel}\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorRomanian::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1880 of file translator_ro.h.
    { return "Membri Motenii Adiionali"; }
trAll()
QCString TranslatorRomanian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1393 of file translator_ro.h.
    {
      return "Toate";
    }
trAndMore()
QCString TranslatorRomanian::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1856 of file translator_ro.h.
    { return "i nc " + number; }
trAttention()
QCString TranslatorRomanian::trAttention () inline override virtual
Implements Translator.
Definition at line 977 of file translator_ro.h.
    {
      return "Atenie";
    }
trAuthor()
QCString TranslatorRomanian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1266 of file translator_ro.h.
    {
      return createNoun(first_capital, singular, "autor", "ii", "ul");
    }
References Translator::createNoun().
trBug()
QCString TranslatorRomanian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1138 of file translator_ro.h.
    {
      return "Problema (Bug)";
    }
trBugList()
QCString TranslatorRomanian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1143 of file translator_ro.h.
    {
      return "Lista de Probleme (Bugs)";
    }
trCallerGraph()
QCString TranslatorRomanian::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1515 of file translator_ro.h.
    {
      return "Graful de apeluri pentru aceast funcie:";
    }
trCallGraph()
QCString TranslatorRomanian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1398 of file translator_ro.h.
    {
      return "Graful de apel al acestei funcii:";
    }
trCiteReferences()
QCString TranslatorRomanian::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1832 of file translator_ro.h.
    { return "Referine Bibliografice"; }
trClass()
QCString TranslatorRomanian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1201 of file translator_ro.h.
    {
      return createNoun(first_capital, singular, "clas", "ele", "a");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorRomanian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 528 of file translator_ro.h.
    {
      return "Diagrama de relaii pentru "+clName;
    }
trClassDocumentation()
QCString TranslatorRomanian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 407 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaia Structurilor de Date";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentaia Claselor";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorRomanian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1101 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structuri de Date";
      }
      else
      {
        return "Clase";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorRomanian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 181 of file translator_ro.h.
    { return "Ierarhia Claselor"; }
trClassHierarchyDescription()
QCString TranslatorRomanian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 243 of file translator_ro.h.
    { return "Aceast list de moteniri este sortat n general, "
             "dar nu complet, n ordine alfabetic:";
    }
trClassMethods()
QCString TranslatorRomanian::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1918 of file translator_ro.h.
    {
      return "Metodele Clasei";
    }
trCode()
QCString TranslatorRomanian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 876 of file translator_ro.h.
    {
      return "cod";
    }
trCollaborationDiagram()
QCString TranslatorRomanian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 831 of file translator_ro.h.
    {
      return "Diagrama de relaii pentru "+clName+":";
    }
trCompoundIndex()
QCString TranslatorRomanian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 379 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indexul Structurilor de Date";
      }
      else
      {
        return "Indexul Claselor";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorRomanian::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1569 of file translator_ro.h.
    { return "Indexul Tipurilor de Date"; }
trCompoundList()
QCString TranslatorRomanian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 185 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structuri de Date";
      }
      else
      {
        return "Lista Claselor";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorRomanian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 259 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lista structurilor de date, cu scurte descrieri:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Lista claselor, cu scurte descrieri:";
      }
      else
      {
        return "Lista claselor, structurilor, uniunilor i interfeelor"
                ", cu scurte descrieri:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorRomanian::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1543 of file translator_ro.h.
    { return "Tipurile de date, cu scurte descrieri:"; }
trCompoundListFortran()
QCString TranslatorRomanian::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1535 of file translator_ro.h.
    { return "Lista Tipurilor de Date"; }
trCompoundMembers()
QCString TranslatorRomanian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 203 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cmpurile de Date";
      }
      else
      {
        return "Membrii Componeni"; //cu articol hotarat
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorRomanian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 278 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="cmpurilor ";
        if (!extractAll) result+=" documentate ";
        result+="din structuri si uniuni ";
      }
      else
      {
        result+="membrilor ";
          if (!extractAll) result+="documentai ";
        result+="din toate clasele ";
      }
      result+=", cu legturi ctre ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="documentaia structurii/uniunii pentru fiecare cmp n parte:";
        }
        else
        {
          result+="documentaia clasei pentru fiecare membru n parte:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="structurile/uniunile de care aparin:";
        }
        else
        {
          result+="clasele de care aparin:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorRomanian::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1547 of file translator_ro.h.
    {
      QCString result="Lista tuturor tipurilor de date ";
      if (!extractAll)
      {
        result+="documentate ";
      }
      result+=" cu legturi ctre ";
      if (!extractAll)
      {
         result+="documentaia structurii de date pentru fiecare membru";
      }
      else
      {
         result+="tipurile de date de care aparin:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorRomanian::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1539 of file translator_ro.h.
    { return "Cmpuri de date"; }
trCompoundReference()
QCString TranslatorRomanian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 602 of file translator_ro.h.
    {
          QCString result="Referin la ";
      switch(compType)
      {
        case ClassDef::Class:      result+="clasa "; break;
        case ClassDef::Struct:     result+="structura "; break;
        case ClassDef::Union:      result+="uniunea "; break;
        case ClassDef::Interface:  result+="interfaa "; break;
        case ClassDef::Protocol:   result+="protocolul "; break;
        case ClassDef::Category:   result+="categoria "; break;
        case ClassDef::Exception:  result+="excepia "; break;
        default: break;
      }
      if (isTemplate) result+=" (Template) ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorRomanian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1610 of file translator_ro.h.
    {
      QCString result="Referin la ";
      switch(compType)
      {
        case ClassDef::Class:      result+="Modulul "; break;
        case ClassDef::Struct:     result+="Tipul "; break;
        case ClassDef::Union:      result+="Uniunea "; break;
        case ClassDef::Interface:  result+="Interfaa "; break;
        case ClassDef::Protocol:   result+="Protocolul "; break;
        case ClassDef::Category:   result+="Categoria "; break;
        case ClassDef::Exception:  result+="Excepia "; break;
        default: break;
      }
      if (isTemplate) result+="(Template) ";
          result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorRomanian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 503 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structuri de Date";
      }
      else
      {
        return "Membri";
      }
    }
References Config_getBool.
trConstantGroupReference()
QCString TranslatorRomanian::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1955 of file translator_ro.h.
    {
      QCString result=namespaceName;
      result+=" Referin Grup Constant";
      return result;
    }
trConstantGroups()
QCString TranslatorRomanian::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1951 of file translator_ro.h.
    { return "Grupuri Constante"; }
trConstructorDocumentation()
QCString TranslatorRomanian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 841 of file translator_ro.h.
    {
      return "Documentaia pentru Constructori i Destructori";
    }
trCopyright()
QCString TranslatorRomanian::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1836 of file translator_ro.h.
    { return "Copyright"; }
trDataTypes()
QCString TranslatorRomanian::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1593 of file translator_ro.h.
    { return "Tipuri de Date"; }
trDate()
QCString TranslatorRomanian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 542 of file translator_ro.h.
    { return "Data"; }
trDateTime()
QCString TranslatorRomanian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1785 of file translator_ro.h.
    {
      static const char *days[]   = { "Luni","Mari","Miercuri","Joi","Vineri","Smbt","Duminic" };
      static const char *months[] = { "Ian","Feb","Mar","Apr","Mai","Iun","Iul","Aug","Sep","Oct","Noi","Dec" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorRomanian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1805 of file translator_ro.h.
    {
      static const char *days_short[]   = { "lun.", "mar.", "mie.", "joi", "vin.", "sm.", "dum." };
      static const char *days_full[]    = { "luni", "mar?i", "miercuri", "joi", "vineri", "smbt", "duminic" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorRomanian::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1821 of file translator_ro.h.
    {
      static const char *dayPeriod[] = { "a.m.", "p.m." };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorRomanian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 808 of file translator_ro.h.
    {
      return "Definiia n linia @0 a fiierului @1.";
    }
trDefinedIn()
QCString TranslatorRomanian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 169 of file translator_ro.h.
    { return "definit n"; }
trDefinedInSourceFile()
QCString TranslatorRomanian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 812 of file translator_ro.h.
    {
      return "Definiia n fiierul @0.";
    }
trDefineDocumentation()
QCString TranslatorRomanian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 473 of file translator_ro.h.
    { return "Documentaia definiiilor"; }
trDefines()
QCString TranslatorRomanian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 437 of file translator_ro.h.
    { return "Definiii"; }
trDefineValue()
QCString TranslatorRomanian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1128 of file translator_ro.h.
    {
      return "Valoare:";
    }
trDeprecated()
QCString TranslatorRomanian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 821 of file translator_ro.h.
    {
      return "nvechit(Deprecated)";
    }
trDeprecatedList()
QCString TranslatorRomanian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1321 of file translator_ro.h.
    {
      return "Lista elementelor nvechite (deprecated)";
    }
trDetailedDescription()
QCString TranslatorRomanian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 97 of file translator_ro.h.
    { return "Descriere Detaliat"; }
trDetailLevel()
QCString TranslatorRomanian::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1848 of file translator_ro.h.
    { return "nivel de detaliu"; }
trDetails()
QCString TranslatorRomanian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 101 of file translator_ro.h.
    { return "Detalii"; }
trDir()
QCString TranslatorRomanian::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1491 of file translator_ro.h.
     {
      return createNoun(first_capital, singular, "directo", "are", "r");
     }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorRomanian::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1840 of file translator_ro.h.
    { return QCString("Grafic de dependen a directoarelor pentru ")+name+":"; }
trDirDocumentation()
QCString TranslatorRomanian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1470 of file translator_ro.h.
     { return "Documentaia directoarelor"; }
trDirectories()
QCString TranslatorRomanian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1476 of file translator_ro.h.
     { return "Directoare"; }
trDirIndex()
QCString TranslatorRomanian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1464 of file translator_ro.h.
     { return "Ierarhia directoarelor"; }
trDirReference()
QCString TranslatorRomanian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1482 of file translator_ro.h.
     {
       QCString  result="Director-referin "; result+=dirName;
       return result;
     }
trDirRelation()
QCString TranslatorRomanian::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1724 of file translator_ro.h.
    {
      return QCString(name)+" Relaie";
    }
trDocumentation()
QCString TranslatorRomanian::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 361 of file translator_ro.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Documentaie"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorRomanian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 449 of file translator_ro.h.
    { return "Enumerri"; }
trEnumerationTypeDocumentation()
QCString TranslatorRomanian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 485 of file translator_ro.h.
    { return "Documentaia enumerrilor"; }
trEnumerationValueDocumentation()
QCString TranslatorRomanian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1523 of file translator_ro.h.
    { return "Documentaia Enumeratorilor"; }
trEnumerationValues()
QCString TranslatorRomanian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 467 of file translator_ro.h.
    { return "Valori de enumerri"; }
trEnumGeneratedFromFiles()
QCString TranslatorRomanian::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1860 of file translator_ro.h.
    { QCString result = "Documentaia pentru acest enum a fost generat din ";
      if (single)
        result += "urmtorul fiier:";
      else
        result += "urmtoarele fiiere:";
      return result;
    }
trEnumName()
QCString TranslatorRomanian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 161 of file translator_ro.h.
    { return "nume enumerare"; }
trEnumReference()
QCString TranslatorRomanian::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1870 of file translator_ro.h.
    { return QCString(name)+" Referin Enum"; }
trEnumValue()
QCString TranslatorRomanian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 165 of file translator_ro.h.
    { return "valoare enumerare"; }
trEventDocumentation()
QCString TranslatorRomanian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1338 of file translator_ro.h.
    {
      return "Documentaia aferent evenimentelor";
    }
trEvents()
QCString TranslatorRomanian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1333 of file translator_ro.h.
    {
      return "Evenimente";
    }
trExamples()
QCString TranslatorRomanian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 235 of file translator_ro.h.
    { return "Exemple"; }
trExamplesDescription()
QCString TranslatorRomanian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 346 of file translator_ro.h.
    { return "Lista tuturor exemplelor:"; }
trExceptions()
QCString TranslatorRomanian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 558 of file translator_ro.h.
    { return "Excepii"; }
trExtendsClass()
QCString TranslatorRomanian::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1910 of file translator_ro.h.
    {
      return "Extinde clasa @0.";
    }
trFile()
QCString TranslatorRomanian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_ro.h.
    {
      return createNoun(first_capital, singular, "fiier", "ele", "ul");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorRomanian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 427 of file translator_ro.h.
    { return "Documentaia Fiierelor"; }
trFileIn()
QCString TranslatorRomanian::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1761 of file translator_ro.h.
    {
      return "Fiierul din "+name;
    }
trFileIndex()
QCString TranslatorRomanian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 395 of file translator_ro.h.
    { return "Indexul Fiierelor"; }
trFileList()
QCString TranslatorRomanian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 199 of file translator_ro.h.
    { return "Lista fiierelor"; }
trFileListDescription()
QCString TranslatorRomanian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 249 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      result+="fiierelor";
          if (!extractAll) result+=" documentate";
          result+=", cu scurte descrieri:";
      return result;
    }
trFileMembers()
QCString TranslatorRomanian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 217 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globale";
      }
      else
      {
        return "Membrii din Fiier"; //cu articol hotarat
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorRomanian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 322 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funciilor, variabilelor, definiiilor, enumerrilor i definiiilor de tip";
          if (!extractAll) result+=" documentate";
      }
      else
      {
        result+="membrilor ";
          if (!extractAll) result+="documentai ";
          result+="din toate fiierele";
      }
      result+=", cu legturi ctre ";
      if (extractAll)
        result+="fiierele de care aparin:";
      else
        result+="documentaia aferent:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorRomanian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 625 of file translator_ro.h.
    {
      QCString result="Referin la fiierul ";
      result+=fileName;
      return result;
    }
trFriends()
QCString TranslatorRomanian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 584 of file translator_ro.h.
    { return "Prieteni"; }
trFunctionDocumentation()
QCString TranslatorRomanian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 491 of file translator_ro.h.
    { return "Documentaia funciilor"; }
trFunctions()
QCString TranslatorRomanian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 455 of file translator_ro.h.
    { return "Funcii"; }
trGeneratedAt()
QCString TranslatorRomanian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 519 of file translator_ro.h.
    {
      QCString result="Generat "+date;
      if (!projName.isEmpty()) result+=" pentru "+projName;
      result+=" de ctre";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorRomanian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 153 of file translator_ro.h.
    { QCString result="Generat automat de Doxygen";
      if (!s.isEmpty()) result+=" pentru "+s;
      result+=" din codul surs.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorRomanian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 562 of file translator_ro.h.
    { return "Generat de"; }
trGeneratedFromFiles()
QCString TranslatorRomanian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 764 of file translator_ro.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Documentaia pentru aceast ";
      switch(compType)
      {
        case ClassDef::Class:      result+="clas"; break;
        case ClassDef::Struct:     result+="structur"; break;
        case ClassDef::Union:      result+="uniune"; break;
        case ClassDef::Interface:  result+="interfa"; break;
        case ClassDef::Protocol:   result+="protocol"; break;
        case ClassDef::Category:   result+="categorie"; break;
        case ClassDef::Exception:  result+="excepie"; break;
        default: break;
      }
      result+=" a fost generat din fiier";
      if (single) result+="ul:"; else result+="ele:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorRomanian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1676 of file translator_ro.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Documentaia ";
      switch(compType)
      {
        case ClassDef::Class:      result+="modulului"; break;
        case ClassDef::Struct:     result+="tipului"; break;
        case ClassDef::Union:      result+="uniunii"; break;
        case ClassDef::Interface:  result+="interfeei"; break;
        case ClassDef::Protocol:   result+="protocolului"; break;
        case ClassDef::Category:   result+="categoriei"; break;
        case ClassDef::Exception:  result+="excepiei"; break;
        default: break;
      }
      result+=" a fost generat din urmto";
      if (single) result+="rul fiier:"; else result+="arele fiiere:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorRomanian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1255 of file translator_ro.h.
    {
      return createNoun(first_capital, singular, "global", "e");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorRomanian::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1736 of file translator_ro.h.
    {
      return "Namespace Global";
    }
trGotoDocumentation()
QCString TranslatorRomanian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 851 of file translator_ro.h.
    {
      return "Vezi documentaia.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorRomanian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 884 of file translator_ro.h.
    {
      return "Vezi ierarhia claselor n mod grafic";
    }
trGotoSourceCode()
QCString TranslatorRomanian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 846 of file translator_ro.h.
    {
      return "Vezi sursele.";
    }
trGotoTextualHierarchy()
QCString TranslatorRomanian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 888 of file translator_ro.h.
    {
      return "Vezi ierarhia claselor n mod text";
    }
trGraphicalHierarchy()
QCString TranslatorRomanian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 880 of file translator_ro.h.
    {
      return "Ierarhia Claselor n mod grafic";
    }
trGroup()
QCString TranslatorRomanian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1228 of file translator_ro.h.
    {
      return createNoun(first_capital, singular, "grupu", "rile", "l");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorRomanian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 373 of file translator_ro.h.
    { return "Index Ierarhic"; }
trImplementedFromList()
QCString TranslatorRomanian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1289 of file translator_ro.h.
    {
      return "Implementeaz "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorRomanian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1297 of file translator_ro.h.
    {
      return "Implementat n "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorRomanian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 981 of file translator_ro.h.
    {
      return "Acest graf arat care fiiere includ, "
                  "direct sau indirect, acest fiier:";
    }
trInclDepGraph()
QCString TranslatorRomanian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 836 of file translator_ro.h.
    {
      return "Graful dependenelor prin incluziune pentru "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorRomanian::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1770 of file translator_ro.h.
    {
      return "Include fiierul din "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorRomanian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 147 of file translator_ro.h.
    { return ", inclusiv a tuturor membrilor motenii."; }
trInheritedByList()
QCString TranslatorRomanian::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 697 of file translator_ro.h.
    {
      return "Motenit de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorRomanian::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1874 of file translator_ro.h.
    { return QCString(members)+" motenit(e) din "+what; }
trInheritsList()
QCString TranslatorRomanian::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 689 of file translator_ro.h.
    {
      return "Motenete "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorRomanian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 871 of file translator_ro.h.
    {
      return "Valoarea iniial:";
    }
trInstanceMethods()
QCString TranslatorRomanian::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1926 of file translator_ro.h.
    {
      return "Metodele Instanei";
    }
trInterfaces()
QCString TranslatorRomanian::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1943 of file translator_ro.h.
    { return "Interfee exportate"; }
trInvariant()
QCString TranslatorRomanian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 866 of file translator_ro.h.
    {
      return "Invariant";
    }
trISOLang()
QCString TranslatorRomanian::trISOLang () inline override virtual
Implements Translator.
Definition at line 77 of file translator_ro.h.
    {
      return "ro";
    }
trLegend()
QCString TranslatorRomanian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1061 of file translator_ro.h.
    {
      return "legenda";
    }
trLegendDocs()
QCString TranslatorRomanian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 1001 of file translator_ro.h.
    {
      return
        "Aceast pagin arat modul n care trebuie s interpretai "
                "grafurile generate de doxygen.<p>\n"
        "Considerai urmtorul exemplu:\n"
        "\\code\n"
        "/*! Clas invizibil, tiat din cauza depirii spaiului */\n"
        "class Invisible { };\n\n"
        "/*! Alt clas tiat, relaia de motenire este ascuns */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Clas necomentat n stil doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Clas care este motenit n mod public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Clas template */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Clas care este motenit n mod protejat */\n"
        "class ProtectedBase { };\n\n"
        "/*! Clas care este motenit n mod privat */\n"
        "class PrivateBase { };\n\n"
        "/*! Clas care este folosit de clasa Inherited */\n"
        "class Used { };\n\n"
        "/*! Superclas care motenete un numr de alte clase */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dac tagul \\c MAX_DOT_GRAPH_HEIGHT din fiierul de configurare "
        "este setat la 200, acesta este graful rezultat:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Csuele din partea de sus au urmtoarea semnificaie:\n"
        "<ul>\n"
        "<li>O csu neagr reprezint structura sau clasa pentru care "
        "graful este generat.\n"
        "<li>O csu cu marginea neagr reprezint o structur sau o clas documentate.\n"
        "<li>O csu cu marginea gri reprezint o structur sau o clas nedocumentate.\n"
        "<li>O csu cu marginea roie reprezint o structur sau o clas documentate, pentru\n"
        "care nu toate relaiile de motenire/incluziune sunt artate. Un graf este "
        "tiat dac nu ncape n marginile specificate."
        "</ul>\n"
        "Sgeile au urmtoarea semnificaie:\n"
        "<ul>\n"
        "<li>O sgeat de un albastru nchis este folosit cnd avem o relaie de "
        "motenire public ntre dou clase.\n"
        "<li>O sgeat de un verde nchis este folosit cnd avem o motenire protejat.\n"
        "<li>O sgeat de un rou nchis este folosit cnd avem o motenire privat.\n"
        "<li>O sgeat violet punctat este folosit pentru o clas coninut sau folosit "
        "de o alt clas. Sgeata este marcat cu variabila(e) "
        "prin care este accesibil clasa sau structura spre care este ndreptat. \n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorRomanian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 996 of file translator_ro.h.
    {
      return "Legenda grafului";
    }
trListOfAllMembers()
QCString TranslatorRomanian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 135 of file translator_ro.h.
    { return "Lista tuturor membrilor"; }
trLoading()
QCString TranslatorRomanian::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1730 of file translator_ro.h.
    {
      return "Se ncarc...";
    }
trMainPage()
QCString TranslatorRomanian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 795 of file translator_ro.h.
    { return "Pagina principal"; }
trMember()
QCString TranslatorRomanian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1246 of file translator_ro.h.
    {
      return createNoun(first_capital, singular, "membr", "ii", "ul");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorRomanian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 117 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaia Cmpurilor";
      }
      else
      {
        return "Documentaia Datelor Membre";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorRomanian::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 109 of file translator_ro.h.
    { return "Documentaia Enumerrilor Membre"; }
trMemberFunctionDocumentation()
QCString TranslatorRomanian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 113 of file translator_ro.h.
    { return "Documentaia Funciilor Membre"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorRomanian::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1531 of file translator_ro.h.
    { return "Documentaia Funciei Membre/Subrutinei"; }
trMemberList()
QCString TranslatorRomanian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 139 of file translator_ro.h.
    { return "Lista Membrilor"; }
trMemberTypedefDocumentation()
QCString TranslatorRomanian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 105 of file translator_ro.h.
    { return "Documentaia Definiiilor de Tipuri (typedef) Membre"; }
trMethodDocumentation()
QCString TranslatorRomanian::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1933 of file translator_ro.h.
    {
      return "Documentaia Metodelor";
    }
trModule()
QCString TranslatorRomanian::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1669 of file translator_ro.h.
    {
      return createNoun(first_capital, singular, "modul", "ele", "ul");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorRomanian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 401 of file translator_ro.h.
    { return "Documentaia Modulelor"; }
trModuleIndex()
QCString TranslatorRomanian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 367 of file translator_ro.h.
    { return "Indexul Modulelor"; }
trModuleReference()
QCString TranslatorRomanian::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1631 of file translator_ro.h.
    {
      QCString result="Referin la Modulul ";
          result += namespaceName;
      return result;
    }
trModules()
QCString TranslatorRomanian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 177 of file translator_ro.h.
    { return "Module"; }
trModulesDescription()
QCString TranslatorRomanian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 354 of file translator_ro.h.
    { return "Lista tuturor modulelor:"; }
trModulesIndex()
QCString TranslatorRomanian::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1662 of file translator_ro.h.
    { return "Indexul Modulelor"; }
trModulesList()
QCString TranslatorRomanian::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1597 of file translator_ro.h.
    { return "Lista Modulelor"; }
trModulesListDescription()
QCString TranslatorRomanian::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1601 of file translator_ro.h.
    {
      QCString result="Lista tuturor modulelor ";
      if (!extractAll) result+="documentate ";
      result+="cu scurte descrieri:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorRomanian::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1643 of file translator_ro.h.
    {
      QCString result="Lista tuturor membrilor ";
      if (!extractAll) result+="documentai ai ";
      result+="modulului cu legturi ctre ";
      if (extractAll)
      {
        result+="documentaia modulului pentru fiecare membru:";
      }
      else
      {
        result+="modulele de care aparin:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorRomanian::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1639 of file translator_ro.h.
    { return "Membrii Modulului"; }
trMonth()
QCString TranslatorRomanian::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1813 of file translator_ro.h.
    {
      static const char *months_short[] = { "ian.", "feb.", "mar.", "apr.", "mai", "iun.", "iul.", "aug.", "sept.", "oct.", "nov.", "dec." };
      static const char *months_full[]  = { "ianuarie", "februarie", "martie", "aprilie", "mai", "iunie", "iulie", "august", "septembrie", "octombrie", "noiembrie", "decembrie" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorRomanian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 131 of file translator_ro.h.
    { return "Mai mult..."; }
trNamespace()
QCString TranslatorRomanian::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1219 of file translator_ro.h.
    {
      return createNoun(first_capital, singular, "namespace", "-urile", "-ul");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorRomanian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 744 of file translator_ro.h.
    { return "Documentaia Namespace-ului"; }
trNamespaceIndex()
QCString TranslatorRomanian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 738 of file translator_ro.h.
    { return "Indexul Namespace-ului"; }
trNamespaceList()
QCString TranslatorRomanian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 568 of file translator_ro.h.
    { return "Lista de Namespace-uri"; }
trNamespaceListDescription()
QCString TranslatorRomanian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 572 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      result+="namespace-urilor ";
          if (!extractAll) result+="documentate ";
          result+=", cu scurte descrieri:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorRomanian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 723 of file translator_ro.h.
    {
      QCString result="Lista tuturor membrilor ";
      if (!extractAll) result+="documentai ";
          result+="din toate namespace-urile, cu legturi ctre ";
      if (extractAll)
        result+="documentaia namespace-ului pentru fiecare membru n parte:";
      else
        result+="namespace-urile de care aparin:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorRomanian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 719 of file translator_ro.h.
    { return "Membrii Namespace-ului"; }
trNamespaceReference()
QCString TranslatorRomanian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 633 of file translator_ro.h.
    {
      QCString result="Referin la Namespace-ul ";
      result+=namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorRomanian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 754 of file translator_ro.h.
    { return "Namespace-uri"; }
trNoMatches()
QCString TranslatorRomanian::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1748 of file translator_ro.h.
    {
      return "Niciun rezultat";
    }
trNote()
QCString TranslatorRomanian::trNote () inline override virtual
Implements Translator.
Definition at line 901 of file translator_ro.h.
    {
      return "Not";
    }
trOverloadText()
QCString TranslatorRomanian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1503 of file translator_ro.h.
    {
       return "Aceasta este o funcie membr suprascris. "
              "Difer de funcia de mai sus "
              "doar prin argumentele acceptate.";
    }
trPackage()
QCString TranslatorRomanian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1113 of file translator_ro.h.
    {
      return "Pachet "+name;
    }
trPackageAttribs()
QCString TranslatorRomanian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1374 of file translator_ro.h.
    {
      return "Atribute n pachet";
    }
trPackageFunctions()
QCString TranslatorRomanian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1356 of file translator_ro.h.
    {
      return "Funcii n pachet";
    }
trPackageListDescription()
QCString TranslatorRomanian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1118 of file translator_ro.h.
    {
      return "Lista pachetelor, nsoit de scurte explicaii, acolo unde acestea exist:";
    }
trPackageMembers()
QCString TranslatorRomanian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1360 of file translator_ro.h.
    {
      return "Membrii n pachet";
    }
trPackages()
QCString TranslatorRomanian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1123 of file translator_ro.h.
    {
      return "Pachete";
    }
trPackageTypes()
QCString TranslatorRomanian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1349 of file translator_ro.h.
    {
      return "Tipuri n pachet";
    }
trPage()
QCString TranslatorRomanian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1237 of file translator_ro.h.
    {
      return createNoun(first_capital, singular, "pagin", "ile", "a");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorRomanian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 801 of file translator_ro.h.
    { return "pg."; }
trPageIndex()
QCString TranslatorRomanian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 892 of file translator_ro.h.
    {
      return "Indexul Paginilor";
    }
trPanelSynchronisationTooltip()
QCString TranslatorRomanian::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1891 of file translator_ro.h.
    {
      QCString opt = enable ? "activa" : "dezactiva";
      return "apas click pentru a "+opt+" sincronizarea panourilor";
    }
trParameters()
QCString TranslatorRomanian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 554 of file translator_ro.h.
    { return "Parametri"; }
trPostcondition()
QCString TranslatorRomanian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 861 of file translator_ro.h.
    {
      return "Postcondiie";
    }
trPrecondition()
QCString TranslatorRomanian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 856 of file translator_ro.h.
    {
      return "Precondiie";
    }
trPrivateAttribs()
QCString TranslatorRomanian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 941 of file translator_ro.h.
    {
      return "Atribute Private";
    }
trPrivateMembers()
QCString TranslatorRomanian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 655 of file translator_ro.h.
    { return "Metode Private"; }
trPrivateSlots()
QCString TranslatorRomanian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 657 of file translator_ro.h.
    { return "Conectori (slots) Privai"; }
trPrivateTypes()
QCString TranslatorRomanian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 937 of file translator_ro.h.
    {
      return "Tipuri Private";
    }
trProperties()
QCString TranslatorRomanian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1086 of file translator_ro.h.
    {
      return "Proprieti";
    }
trPropertyDocumentation()
QCString TranslatorRomanian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1091 of file translator_ro.h.
    {
      return "Documentaia Proprietilor";
    }
trProtectedAttribs()
QCString TranslatorRomanian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 929 of file translator_ro.h.
    {
      return "Atribute Protejate";
    }
trProtectedMembers()
QCString TranslatorRomanian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 649 of file translator_ro.h.
    { return "Metode Protejate"; }
trProtectedSlots()
QCString TranslatorRomanian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 651 of file translator_ro.h.
    { return "Conectori (slots) Protejai"; }
trProtectedTypes()
QCString TranslatorRomanian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 925 of file translator_ro.h.
    {
      return "Tipuri Protejate";
    }
trProvidedByCategory()
QCString TranslatorRomanian::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1901 of file translator_ro.h.
    {
      return "Furnizat de categoria @0.";
    }
trPublicAttribs()
QCString TranslatorRomanian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 909 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cmpuri de Date";
      }
      else
      {
        return "Atribute Publice";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorRomanian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 641 of file translator_ro.h.
    { return "Metode Publice"; }
trPublicSlots()
QCString TranslatorRomanian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 643 of file translator_ro.h.
    { return "Conectori (slots) Publici"; }
trPublicTypes()
QCString TranslatorRomanian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 905 of file translator_ro.h.
    {
      return "Tipuri Publice";
    }
trReferencedBy()
QCString TranslatorRomanian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 969 of file translator_ro.h.
    {
      return "Semnalat de";
    }
trReferenceManual()
QCString TranslatorRomanian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 431 of file translator_ro.h.
    { return "Manual de utilizare"; }
trReferences()
QCString TranslatorRomanian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1277 of file translator_ro.h.
    {
      return "Referine";
    }
trReimplementedFromList()
QCString TranslatorRomanian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 705 of file translator_ro.h.
    {
      return "Reimplementat din "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorRomanian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 713 of file translator_ro.h.
    {
      return "Reimplementat n "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorRomanian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 594 of file translator_ro.h.
    { return "Documentaia funciilor prietene sau nrudite"; }
trRelatedFunctions()
QCString TranslatorRomanian::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 89 of file translator_ro.h.
    { return "Funcii nrudite"; }
trRelatedPages()
QCString TranslatorRomanian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 231 of file translator_ro.h.
    { return "Pagini nrudite"; }
trRelatedPagesDescription()
QCString TranslatorRomanian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 350 of file translator_ro.h.
    { return "Lista tuturor documentaiilor nrudite:"; }
trRelatedSubscript()
QCString TranslatorRomanian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 93 of file translator_ro.h.
    { return "(Atenie: acestea nu sunt funcii membre.)"; }
trRemarks()
QCString TranslatorRomanian::trRemarks () inline override virtual
Implements Translator.
Definition at line 973 of file translator_ro.h.
    {
      return "Observaii";
    }
trReturns()
QCString TranslatorRomanian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 546 of file translator_ro.h.
    { return "ntoarce"; }
trReturnValues()
QCString TranslatorRomanian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 790 of file translator_ro.h.
    { return "Valori returnate"; }
trRTFansicp()
QCString TranslatorRomanian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1177 of file translator_ro.h.
    {
      return "1250"; //EASTEUROPE_CHARSET
    }
trRTFCharSet()
QCString TranslatorRomanian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1186 of file translator_ro.h.
    {
      return "238";
    }
trRTFGeneralIndex()
QCString TranslatorRomanian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1192 of file translator_ro.h.
    {
      return "Index";
    }
trRTFTableOfContents()
QCString TranslatorRomanian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1309 of file translator_ro.h.
    {
      return "Cuprins";
    }
trSearch()
QCString TranslatorRomanian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 239 of file translator_ro.h.
    { return "Caut"; }
trSearching()
QCString TranslatorRomanian::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1742 of file translator_ro.h.
    {
      return "Cutare...";
    }
trSearchMatches()
QCString TranslatorRomanian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1441 of file translator_ro.h.
    {
      return "Gsite:";
    }
trSearchResults()
QCString TranslatorRomanian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1422 of file translator_ro.h.
    {
      if (numDocuments==0)
      {
        return "Din pcate nu am gsit nici un document care s corespund cererii.";
      }
      else if (numDocuments==1)
      {
        return "Am gsit <b>1</b> document corespunznd cererii.";
      }
      else
      {
        return "Am gsit <b>$num</b> documente corespunznd cererii. "
               "Lista documentelor gsite, sortate dup relevan.";
      }
    }
trSearchResultsTitle()
QCString TranslatorRomanian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1410 of file translator_ro.h.
    {
      return "Rezultatele cutarii";
    }
trSeeAlso()
QCString TranslatorRomanian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 550 of file translator_ro.h.
    { return "Vezi i"; }
trServiceGeneratedFromFiles()
QCString TranslatorRomanian::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 1976 of file translator_ro.h.
    {
      // single is true implies a single file
      QCString result="Documentaia pentru acest serviciu "
                                "a fost generat din ";
      if (single)
        result += "urmtorul fiier:";
      else
        result += "urmtoarele fiiere:";
      return result;
    }
trServiceReference()
QCString TranslatorRomanian::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 1962 of file translator_ro.h.
    {
      QCString result=sName;
      result+=" Referin Serviciu";
      return result;
    }
trServices()
QCString TranslatorRomanian::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1947 of file translator_ro.h.
    { return "Servicii Incluse"; }
trSignals()
QCString TranslatorRomanian::trSignals () inline override virtual
Implements Translator.
Definition at line 645 of file translator_ro.h.
    { return "Semnale"; }
trSince()
QCString TranslatorRomanian::trSince () inline override virtual
Implements Translator.
Definition at line 986 of file translator_ro.h.
    {
      return "Din";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorRomanian::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 1988 of file translator_ro.h.
    {
      // single is true implies a single file
      QCString result="Documentaia pentru acest singleton "
                                "a fost generat din ";
      if (single)
        result += "urmtorul fiier:";
      else
        result += "urmtoarele fiiere:";
      return result;
    }
trSingletonReference()
QCString TranslatorRomanian::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 1969 of file translator_ro.h.
    {
      QCString result=sName;
      result+=" Referin Singleton";
      return result;
    }
trSourceFile()
QCString TranslatorRomanian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1452 of file translator_ro.h.
     {
       return " Fiierul surs " + filename;
     }
trStaticPackageAttribs()
QCString TranslatorRomanian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1381 of file translator_ro.h.
    {
      return "Atribute statice n pachet";
    }
trStaticPackageFunctions()
QCString TranslatorRomanian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1367 of file translator_ro.h.
    {
      return "Funcii statice n pachet";
    }
trStaticPrivateAttribs()
QCString TranslatorRomanian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 945 of file translator_ro.h.
    {
      return "Atribute Statice Private";
    }
trStaticPrivateMembers()
QCString TranslatorRomanian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 659 of file translator_ro.h.
    { return "Metode Statice Private"; }
trStaticProtectedAttribs()
QCString TranslatorRomanian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 933 of file translator_ro.h.
    {
      return "Atribute Statice Protejate";
    }
trStaticProtectedMembers()
QCString TranslatorRomanian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 653 of file translator_ro.h.
    { return "Metode Statice Protejate"; }
trStaticPublicAttribs()
QCString TranslatorRomanian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 921 of file translator_ro.h.
    {
      return "Atribute Statice Publice";
    }
trStaticPublicMembers()
QCString TranslatorRomanian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 647 of file translator_ro.h.
    { return "Metode Statice Publice"; }
trSubprogram()
QCString TranslatorRomanian::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1708 of file translator_ro.h.
    {
      return createNoun(first_capital, singular, "subprogram", "ele", "ul");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorRomanian::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1587 of file translator_ro.h.
    { return "Documentaia Funciilor/Subrutinelor"; }
trSubprograms()
QCString TranslatorRomanian::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1581 of file translator_ro.h.
    { return "Funcii/Subrutine"; }
trTemplateParameters()
QCString TranslatorRomanian::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1852 of file translator_ro.h.
    { return "Parametri Template"; }
trTest()
QCString TranslatorRomanian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1071 of file translator_ro.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorRomanian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1076 of file translator_ro.h.
    {
      return "List de teste";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorRomanian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 143 of file translator_ro.h.
    { return "Lista complet a membrilor din"; }
trTodo()
QCString TranslatorRomanian::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 955 of file translator_ro.h.
    {
      return "De fcut";
    }
trTodoList()
QCString TranslatorRomanian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 960 of file translator_ro.h.
    {
      return "Lista lucrurilor de fcut";
    }
trType()
QCString TranslatorRomanian::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1700 of file translator_ro.h.
    {
      return createNoun(first_capital, singular, "tip", "urile", "ul");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorRomanian::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1714 of file translator_ro.h.
    {
      return "Constrngerile de Tip";
    }
trTypedefDocumentation()
QCString TranslatorRomanian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 479 of file translator_ro.h.
    { return "Documentaia definiiilor de tipuri"; }
trTypedefs()
QCString TranslatorRomanian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 443 of file translator_ro.h.
    { return "Definiii de tipuri"; }
trTypeDocumentation()
QCString TranslatorRomanian::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1575 of file translator_ro.h.
    { return "Documentaia Tipurilor de Date"; }
trVariableDocumentation()
QCString TranslatorRomanian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 497 of file translator_ro.h.
    { return "Documentaia variabilelor"; }
trVariables()
QCString TranslatorRomanian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 461 of file translator_ro.h.
    { return "Variabile"; }
trVersion()
QCString TranslatorRomanian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 538 of file translator_ro.h.
    { return "Versiunea"; }
trWarning()
QCString TranslatorRomanian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 534 of file translator_ro.h.
    { return "Atenie"; }
trWriteList()
QCString TranslatorRomanian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 665 of file translator_ro.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_ro.h