Doxygen: SpanishTranslatorUtils Namespace Reference
SpanishTranslatorUtils Namespace Reference
Functions
bool isClassMemberHighlightMasculine (ClassMemberHighlight::Enum hl)
bool isFileMemberHighlightMasculine (FileMemberHighlight::Enum hl)
bool isNamespaceMemberHighlightMasculine (NamespaceMemberHighlight::Enum hl)
Detailed Description
translator_es.h modified by Lucas Cruz (7-julio-2000) Updated from 1.3.8 to 1.4.6 by Guillermo Ballester Valor (May-05-2006) Updated to 1.5.1 by Bartomeu Creus Navarro (22-enero-2007) Updated to 1.5.5 by Bartomeu Creus Navarro (5-febrero-2008) Updated to 1.5.8 by Bartomeu Creus Navarro (10-abril-2009) Updated to 1.6.3 by Bartomeu Creus Navarro (3-marzo-2010) Updated to 1.6.4 by Bartomeu Creus Navarro (26-mayo-2010) [(16-jun-2010) grabado en UTF-8] Updated to 1.8.0 by Bartomeu Creus Navarro (11-abril-2012) Updated to 1.8.2 by Bartomeu Creus Navarro (01-julio-2012) Updated to 1.8.4 by Bartomeu Creus Navarro (17-julio-2013) Updated to 1.9.6 by David H. Martín (28-diciembre-2022) Updated to 1.9.7 by David H. Martín (27-marzo-2023)
Function Documentation
isClassMemberHighlightMasculine()
bool SpanishTranslatorUtils::isClassMemberHighlightMasculine (ClassMemberHighlight::Enum hl) inline
Returns true if the gender of the given component is masculine in Spanish.
Definition at line 40 of file translator_es.h.
    {
      switch (hl)
      {
        case ClassMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            // structs and unions
            return false;
          }
          else
          {
            // class members
            return true;
          }
        case ClassMemberHighlight::Functions:
        case ClassMemberHighlight::Variables:
        case ClassMemberHighlight::Enums:
        case ClassMemberHighlight::Properties:
          return false;
        case ClassMemberHighlight::EnumValues:
        case ClassMemberHighlight::Typedefs:
        case ClassMemberHighlight::Events:
        case ClassMemberHighlight::Related:
        default:
          return true;
      }
    }
References ClassMemberHighlight::All, Config_getBool, ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, ClassMemberHighlight::Properties, ClassMemberHighlight::Related, ClassMemberHighlight::Typedefs, and ClassMemberHighlight::Variables.
Referenced by TranslatorSpanish::trCompoundMembersDescriptionTotal().
isFileMemberHighlightMasculine()
bool SpanishTranslatorUtils::isFileMemberHighlightMasculine (FileMemberHighlight::Enum hl) inline
Returns true if the gender of the given component is masculine in Spanish.
Definition at line 71 of file translator_es.h.
    {
      switch (hl)
      {
        case FileMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            // functions, variables...
            return false;
          }
          else
          {
            // file members
            return true;
          }
        case FileMemberHighlight::Functions:
        case FileMemberHighlight::Variables:
        case FileMemberHighlight::Sequences:
        case FileMemberHighlight::Enums:
        case FileMemberHighlight::Defines:
          return false;
        case FileMemberHighlight::Dictionaries:
        case FileMemberHighlight::EnumValues:
        case FileMemberHighlight::Typedefs:
        default:
          return true;
      }
    }
References FileMemberHighlight::All, Config_getBool, FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, FileMemberHighlight::Sequences, FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
Referenced by TranslatorSpanish::trFileMembersDescriptionTotal().
isNamespaceMemberHighlightMasculine()
bool SpanishTranslatorUtils::isNamespaceMemberHighlightMasculine (NamespaceMemberHighlight::Enum hl) inline
Returns true if the gender of the given component is masculine in Spanish.
Definition at line 102 of file translator_es.h.
    {
      switch (hl)
      {
        case NamespaceMemberHighlight::Functions:
        case NamespaceMemberHighlight::Variables:
        case NamespaceMemberHighlight::Sequences:
        case NamespaceMemberHighlight::Enums:
          return false;
        case NamespaceMemberHighlight::All:
        case NamespaceMemberHighlight::Dictionaries:
        case NamespaceMemberHighlight::EnumValues:
        case NamespaceMemberHighlight::Typedefs:
        default:
          return true;
      }
    }
References NamespaceMemberHighlight::All, NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, NamespaceMemberHighlight::Sequences, NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
Referenced by TranslatorSpanish::trNamespaceMembersDescriptionTotal().