Doxygen: CodeFragmentManager Class Reference
CodeFragmentManager Class Reference
#include <src/codefragment.h>
Classes
struct Private
Public Member Functions
void parseCodeFragment (OutputCodeList &codeOutList, const QCString &fileName, const QCString &blockId, const QCString &scopeName, bool showLineNumbers, bool trimLeft)
Static Public Member Functions
static CodeFragmentManager & instance ()
Private Member Functions
CodeFragmentManager ()
~CodeFragmentManager ()
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 28 of file codefragment.h.
Constructor & Destructor Documentation
CodeFragmentManager()
CodeFragmentManager::CodeFragmentManager () private
Definition at line 231 of file codefragment.cpp.
                                         : p(std::make_unique<Private>())
{
}
~CodeFragmentManager()
CodeFragmentManager::~CodeFragmentManager () private default
Member Function Documentation
instance()
CodeFragmentManager & CodeFragmentManager::instance () static
Definition at line 237 of file codefragment.cpp.
{
  static CodeFragmentManager m;
  return m;
}
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
parseCodeFragment()
void CodeFragmentManager::parseCodeFragment (OutputCodeList & codeOutList, const QCString & fileName, const QCString & blockId, const QCString & scopeName, bool showLineNumbers, bool trimLeft)
Definition at line 286 of file codefragment.cpp.
{
  AUTO_TRACE("CodeFragmentManager::parseCodeFragment({},blockId={},scopeName={},showLineNumber={},trimLeft={}",
      fileName, blockId, scopeName, showLineNumbers, trimLeft);
  std::string fragmentKey=fileName.str()+":"+scopeName.str();
  std::unordered_map< std::string,std::unique_ptr<Private::FragmentInfo> >::iterator it;
  bool inserted = false;
  {
    // create new entry if it is not yet in the map
    std::lock_guard lock(p->mutex);
    it = p->fragments.find(fragmentKey);
    if (it == p->fragments.end())
    {
      it = p->fragments.emplace(fragmentKey, std::make_unique<Private::FragmentInfo>()).first;
      inserted = true;
      AUTO_TRACE_ADD("new fragment");
    }
  }
  // only lock the one item we are working with
  auto &codeFragment = it->second;
  std::lock_guard lock(codeFragment->mutex);
  if (inserted) // new entry, need to parse the file and record the output and cache it
  {
    SrcLangExt langExt = getLanguageFromFileName(fileName);
    FileInfo cfi( fileName.str() );
    auto fd = createFileDef( cfi.dirPath(), cfi.fileName() );
    auto intf = Doxygen::parserManager->getCodeParser(getFileNameExtension(fileName));
    intf->resetCodeParserState();
    bool filterSourceFiles = Config_getBool(FILTER_SOURCE_FILES);
    bool needs2PassParsing =
        Doxygen::parseSourcesNeeded &&                // we need to parse (filtered) sources for cross-references
        !filterSourceFiles &&                         // but user wants to show sources as-is
        !getFileFilter(fileName,TRUE).isEmpty();     // and there is a filter used while parsing
    codeFragment->fileContents = readTextFileByName(fileName);
    //printf("fileContents=[%s]\n",qPrint(codeFragment->fileContents));
    if (needs2PassParsing)
    {
      OutputCodeList devNullList;
      devNullList.add<DevNullCodeGenerator>();
      intf->parseCode(devNullList,
                      scopeName,
                      codeFragment->fileContents,
                      langExt,
                      false,
                      QCString()
                      );
    }
    codeFragment->findBlockMarkers();
    if (codeFragment->fileContents.length()>0) // parse the normal version
    {
      intf->parseCode(codeFragment->recorderCodeList,
          scopeName,
          codeFragment->fileContents,
          langExt,            // lang
          false,              // isExampleBlock
          QCString(),         // exampleName
          fd.get(),           // fileDef
          -1,                 // startLine
          -1,                 // endLine
          true,               // inlineFragment
          nullptr,            // memberDef
          true,               // showLineNumbers
          nullptr,            // searchCtx
          false               // collectXRefs
          );
    }
    if (codeFragment->fileContentsTrimLeft.length()>0) // also need to parse a version with trimmed indentation
    {
      intf->parseCode(codeFragment->recorderCodeListTrimLeft,
          scopeName,
          codeFragment->fileContentsTrimLeft,
          langExt,            // lang
          false,              // isExampleBlock
          QCString(),         // exampleName
          fd.get(),           // fileDef
          -1,                 // startLine
          -1,                 // endLine
          true,               // inlineFragment
          nullptr,            // memberDef
          true,               // showLineNumbers
          nullptr,            // searchCtx
          false               // collectXRefs
          );
    }
  }
  // use the recorded OutputCodeList from the cache to output a pre-recorded fragment
  auto blockKv = codeFragment->blocksById.find(blockId.str());
  if (blockKv != codeFragment->blocksById.end())
  {
    const auto &marker = blockKv->second;
    int startLine = marker->lines[0];
    int endLine   = marker->lines[1];
    AUTO_TRACE_ADD("replay(start={},end={}) fileContentsTrimLeft.empty()={}",startLine,endLine,codeFragment->fileContentsTrimLeft.isEmpty());
    if (!trimLeft || codeFragment->fileContentsTrimLeft.isEmpty()) // replay the normal version
    {
      codeFragment->recorderCodeList.get<OutputCodeRecorder>()->replay(codeOutList,startLine+1,endLine,showLineNumbers);
    }
    else // replay the trimmed version
    {
      codeFragment->recorderCodeListTrimLeft.get<OutputCodeRecorder>()->replay(codeOutList,startLine+1,endLine,showLineNumbers);
    }
  }
  else
  {
    AUTO_TRACE_ADD("block not found!");
  }
}
References OutputCodeList::add(), AUTO_TRACE, AUTO_TRACE_ADD, Config_getBool, createFileDef(), FileInfo::dirPath(), FileInfo::fileName(), ParserManager::getCodeParser(), getFileFilter(), getFileNameExtension(), getLanguageFromFileName(), QCString::isEmpty(), p, Doxygen::parserManager, Doxygen::parseSourcesNeeded, readTextFileByName(), QCString::str(), and TRUE.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
Member Data Documentation
p
std::unique_ptr<Private> CodeFragmentManager::p private
Definition at line 44 of file codefragment.h.
Referenced by parseCodeFragment().
The documentation for this class was generated from the following files:
src/codefragment.h
src/codefragment.cpp