Doxygen: src/dotgroupcollaboration.cpp File Reference
dotgroupcollaboration.cpp File Reference
#include "dotgroupcollaboration.h"
#include "classlist.h"
#include "doxygen.h"
#include "namespacedef.h"
#include "pagedef.h"
#include "util.h"
#include "config.h"
#include "textstream.h"
Functions
static void makeURL (const Definition *def, QCString &url)
Function Documentation
makeURL()
static void makeURL (const Definition * def, QCString & url) static
Definition at line 47 of file dotgroupcollaboration.cpp.
{
  QCString fn = def->getOutputFileBase();
  addHtmlExtensionIfMissing(fn);
  url = def->getReference()+"$"+fn;
  if (!def->anchor().isEmpty())
  {
    url+="#"+def->anchor();
  }
}
References addHtmlExtensionIfMissing(), Definition::anchor(), Definition::getOutputFileBase(), Definition::getReference(), and QCString::isEmpty().
Referenced by DotGroupCollaboration::addMemberList(), and DotGroupCollaboration::buildGraph().