Doxygen: src/vhdljjparser.cpp File Reference
vhdljjparser.cpp File Reference
#include <string>
#include "qcstring.h"
#include "containers.h"
#include "vhdljjparser.h"
#include "vhdldocgen.h"
#include "message.h"
#include "config.h"
#include "doxygen.h"
#include "util.h"
#include "language.h"
#include "commentscan.h"
#include "definition.h"
#include "searchindex.h"
#include "outputlist.h"
#include "arguments.h"
#include "types.h"
#include "growbuf.h"
#include "markdown.h"
#include "VhdlParserTokenManager.h"
#include "VhdlParserErrorHandler.hpp"
#include "regex.h"
Classes
struct VHDLDocInfo
struct VHDLOutlineParser::Private
Functions
static bool isConstraintFile (const QCString &fileName, const QCString &ext)
const EntryList & getVhdlInstList ()
QCString filter2008VhdlComment (const QCString &s)
Variables
static EntryList g_instFiles
static int idCounter
Function Documentation
filter2008VhdlComment()
QCString filter2008VhdlComment (const QCString & s)
Definition at line 868 of file vhdljjparser.cpp.
{
  if (s.length()<4) return s;
  GrowBuf growBuf;
  const char *p=s.data()+3; // skip /*!
  char c='\0';
  while (*p == ' ' || *p == '\t') p++;
  while ((c=*p++))
  {
    growBuf.addChar(c);
    if (c == '\n')
    {
      // special handling of space followed by * at beginning of line
      while (*p == ' ' || *p == '\t') p++;
      while (*p == '*') p++;
      // special attention in case character at end is /
      if (*p == '/') p++;
    }
  }
  // special attention in case */ at end of last line
  size_t len = growBuf.getPos();
  if (len>=2 && growBuf.at(len-1) == '/' && growBuf.at(len-2) == '*')
  {
    len -= 2;
    while (len>0 && growBuf.at(len-1) == '*') len--;
    while (len>0 && ((c = growBuf.at(len-1)) == ' ' || c == '\t')) len--;
    growBuf.setPos(len);
  }
  growBuf.addChar(0);
  return growBuf.get();
}
References GrowBuf::addChar(), GrowBuf::at(), QCString::data(), GrowBuf::get(), GrowBuf::getPos(), QCString::length(), and GrowBuf::setPos().
getVhdlInstList()
const EntryList & getVhdlInstList ()
Definition at line 845 of file vhdljjparser.cpp.
{
  return g_instFiles;
}
References g_instFiles.
Referenced by VhdlDocGen::computeVhdlComponentRelations().
isConstraintFile()
static bool isConstraintFile (const QCString & fileName, const QCString & ext) static
Definition at line 47 of file vhdljjparser.cpp.
{
  return fileName.right(ext.length())==ext;
}
References QCString::length(), and QCString::right().
Referenced by VHDLOutlineParser::parseInput().
Variable Documentation
g_instFiles
EntryList g_instFiles static
Definition at line 55 of file vhdljjparser.cpp.
Referenced by VHDLOutlineParser::addCompInst(), and getVhdlInstList().
idCounter
int idCounter static
Definition at line 246 of file vhdljjparser.cpp.
Referenced by VHDLOutlineParser::getNameID().