Doxygen: ManGenerator Class Reference
ManGenerator Class Reference
Generator for Man page output.
#include <src/mangen.h>
Public Member Functions
ManGenerator ()
ManGenerator (const ManGenerator &)
ManGenerator & operator= (const ManGenerator &)
ManGenerator (ManGenerator &&)=delete
ManGenerator & operator= (ManGenerator &&)=delete
~ManGenerator ()
void clearBuffer ()
void newParagraph ()
OutputType type () const override
std::unique_ptr< OutputGenIntf > clone () override
void addCodeGen (OutputCodeList &list) override
void cleanup () override
void writeDoc (const IDocNodeAST *ast, const Definition *, const MemberDef *, int) override
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id, int hierarchyLevel) override
void endFile () override
void writeSearchInfo () override
void writeFooter (const QCString &) override
void startPageDoc (const QCString &) override
void endPageDoc () override
void startIndexSection (IndexSection) override
void endIndexSection (IndexSection) override
void writePageLink (const QCString &, bool) override
void startProjectNumber () override
void endProjectNumber () override
void writeStyleInfo (int) override
void startTitleHead (const QCString &) override
void endTitleHead (const QCString &, const QCString &) override
void startParagraph (const QCString &classDef) override
void endParagraph () override
void writeString (const QCString &text) override
void startIndexListItem () override
void endIndexListItem () override
void startIndexList () override
void endIndexList () override
void startIndexKey () override
void endIndexKey () override
void startIndexValue (bool) override
void endIndexValue (const QCString &, bool) override
void startItemList () override
void endItemList () override
void startIndexItem (const QCString &ref, const QCString &file) override
void endIndexItem (const QCString &ref, const QCString &file) override
void docify (const QCString &text) override
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name) override
void startTextLink (const QCString &, const QCString &) override
void endTextLink () override
void startTypewriter () override
void endTypewriter () override
void startGroupHeader (int) override
void endGroupHeader (int) override
void startMemberSections () override
void endMemberSections () override
void startHeaderSection () override
void endHeaderSection () override
void startMemberHeader (const QCString &, int) override
void endMemberHeader () override
void insertMemberAlign (bool) override
void insertMemberAlignLeft (MemberItemType, bool) override
void startMemberSubtitle () override
void endMemberSubtitle () override
void startItemListItem () override
void endItemListItem () override
void startMemberDocList () override
void endMemberDocList () override
void startMemberList () override
void endMemberList () override
void startInlineHeader () override
void endInlineHeader () override
void startAnonTypeScope (int) override
void endAnonTypeScope (int) override
void startMemberItem (const QCString &, MemberItemType, const QCString &) override
void endMemberItem (MemberItemType) override
void startMemberTemplateParams () override
void endMemberTemplateParams (const QCString &, const QCString &) override
void startCompoundTemplateParams () override
void endCompoundTemplateParams () override
void startMemberGroupHeader (bool) override
void endMemberGroupHeader () override
void startMemberGroupDocs () override
void endMemberGroupDocs () override
void startMemberGroup () override
void endMemberGroup (bool) override
void writeRuler () override
void writeAnchor (const QCString &, const QCString &) override
void startEmphasis () override
void endEmphasis () override
void startBold () override
void endBold () override
void startBoldEmphasis ()
void endBoldEmphasis ()
void lineBreak (const QCString &) override
void writeChar (char c) override
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool) override
void endMemberDoc (bool) override
void startDoxyAnchor (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &) override
void endDoxyAnchor (const QCString &, const QCString &) override
void addLabel (const QCString &, const QCString &) override
void writeLatexSpacing () override
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name) override
void startCenter () override
void endCenter () override
void startSmall () override
void endSmall () override
void startMemberDescription (const QCString &, const QCString &, bool) override
void endMemberDescription () override
void startMemberDeclaration () override
void endMemberDeclaration (const QCString &, const QCString &) override
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &) override
void startExamples () override
void endExamples () override
void startDescForItem () override
void endDescForItem () override
void startSection (const QCString &, const QCString &, SectionType) override
void endSection (const QCString &, SectionType) override
void addIndexItem (const QCString &, const QCString &) override
void startIndent () override
void endIndent () override
void writeSynopsis () override
void startClassDiagram () override
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &) override
void startPageRef () override
void endPageRef (const QCString &, const QCString &) override
void startQuickIndices () override
void endQuickIndices () override
void writeSplitBar (const QCString &) override
void writeNavigationPath (const QCString &) override
void writeLogo () override
void writeQuickLinks (HighlightedItem, const QCString &) override
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool) override
void startContents () override
void endContents () override
void writeNonBreakableSpace (int n) override
void startDescTable (const QCString &title, const bool hasInits) override
void endDescTable () override
void startDescTableTitle () override
void endDescTableTitle () override
void startDescTableRow () override
void endDescTableRow () override
void startDescTableInit () override
void endDescTableInit () override
void startDescTableData () override
void endDescTableData () override
void startDotGraph () override
void endDotGraph (DotClassGraph &) override
void startInclDepGraph () override
void endInclDepGraph (DotInclDepGraph &) override
void startGroupCollaboration () override
void endGroupCollaboration (DotGroupCollaboration &) override
void startCallGraph () override
void endCallGraph (DotCallGraph &) override
void startDirDepGraph () override
void endDirDepGraph (DotDirDeps &) override
void writeGraphicalHierarchy (DotGfxHierarchyTable &) override
void startTextBlock (bool) override
void endTextBlock (bool) override
void lastIndexPage () override
void startMemberDocPrefixItem () override
void endMemberDocPrefixItem () override
void startMemberDocName (bool) override
void endMemberDocName () override
void startParameterType (bool, const QCString &) override
void endParameterType () override
void startParameterName (bool) override
void endParameterName () override
void startParameterExtra () override
void endParameterExtra (bool, bool, bool) override
void startParameterDefVal (const char *s) override
void endParameterDefVal () override
void startParameterList (bool) override
void endParameterList () override
void exceptionEntry (const QCString &, bool) override
void startConstraintList (const QCString &) override
void startConstraintParam () override
void endConstraintParam () override
void startConstraintType () override
void endConstraintType () override
void startConstraintDocs () override
void endConstraintDocs () override
void endConstraintList () override
void startMemberDocSimple (bool) override
void endMemberDocSimple (bool) override
void startInlineMemberType () override
void endInlineMemberType () override
void startInlineMemberName () override
void endInlineMemberName () override
void startInlineMemberDoc () override
void endInlineMemberDoc () override
void startLabels () override
void writeLabel (const QCString &l, bool isLast) override
void endLabels () override
void writeLocalToc (const SectionRefs &, const LocalToc &) override
void startPlainFile (const QCString &name) override
void endPlainFile () override
Public Member Functions inherited from OutputGenerator
OutputGenerator ()
OutputGenerator (const QCString &dir)
virtual ~OutputGenerator ()=default
QCString dir () const
QCString fileName () const
void startPlainFile (const QCString &name)
void endPlainFile ()
Public Member Functions inherited from OutputGenIntf
Static Public Member Functions
static void init ()
Private Member Functions
void startTitle ()
void endTitle ()
Private Attributes
bool m_firstCol = true
int m_col = 0
bool m_paragraph = true
bool m_upperCase = false
bool m_insideTabbing = false
bool m_inHeader = false
std::unique_ptr< OutputCodeList > m_codeList
ManCodeGenerator * m_codeGen
Additional Inherited Members
Public Types inherited from OutputGenerator
enum class ParamListTypes { Param , RetVal , Exception }
enum class MemberItemType { Normal , AnonymousStart , AnonymousEnd , Templated }
Protected Attributes inherited from OutputGenerator
TextStream m_t
QCString m_dir
Detailed Description
Generator for Man page output.
Definition at line 68 of file mangen.h.
Constructor & Destructor Documentation
ManGenerator() [1/3]
ManGenerator::ManGenerator ()
Definition at line 227 of file mangen.cpp.
  : OutputGenerator(Config_getString(MAN_OUTPUT)+"/"+getSubdir())
  , m_codeList(std::make_unique<OutputCodeList>())
{
  m_codeGen = m_codeList->add<ManCodeGenerator>(&m_t);
}
References Config_getString, getSubdir(), m_codeGen, m_codeList, OutputGenerator::m_t, and OutputGenerator::OutputGenerator().
Referenced by ManGenerator(), ManGenerator(), operator=(), and operator=().
ManGenerator() [2/3]
ManGenerator::ManGenerator (const ManGenerator & og)
Definition at line 234 of file mangen.cpp.
                                                 : OutputGenerator(og.m_dir), OutputGenIntf()
{
  m_codeList = std::make_unique<OutputCodeList>(*og.m_codeList);
  m_codeGen      = m_codeList->get<ManCodeGenerator>(OutputType::Man);
  m_codeGen->setTextStream(&m_t);
  m_firstCol      = og.m_firstCol;
  m_col           = og.m_col;
  m_paragraph     = og.m_paragraph;
  m_upperCase     = og.m_upperCase;
  m_insideTabbing = og.m_insideTabbing;
  m_inHeader      = og.m_inHeader;
}
References m_codeGen, m_codeList, m_col, OutputGenerator::m_dir, m_firstCol, m_inHeader, m_insideTabbing, m_paragraph, OutputGenerator::m_t, m_upperCase, Man, ManGenerator(), and OutputGenerator::OutputGenerator().
ManGenerator() [3/3]
ManGenerator::ManGenerator (ManGenerator &&) delete
References ManGenerator().
~ManGenerator()
ManGenerator::~ManGenerator () default
Member Function Documentation
addCodeGen()
void ManGenerator::addCodeGen (OutputCodeList & list) override virtual
Implements OutputGenIntf.
Definition at line 267 of file mangen.cpp.
{
  list.add<ManCodeGeneratorDefer>(m_codeGen);
}
References OutputCodeList::add(), and m_codeGen.
addIndexItem()
void ManGenerator::addIndexItem (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 199 of file mangen.h.
{}
addLabel()
void ManGenerator::addLabel (const QCString & , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 563 of file mangen.cpp.
{
}
cleanup()
void ManGenerator::cleanup () override virtual
Implements OutputGenIntf.
Definition at line 289 of file mangen.cpp.
{
  QCString dname = Config_getString(MAN_OUTPUT);
  Dir d(dname.str());
  clearSubDirs(d);
}
References clearSubDirs(), Config_getString, and QCString::str().
clearBuffer()
void ManGenerator::clearBuffer ()
clone()
std::unique_ptr< OutputGenIntf > ManGenerator::clone () inline override virtual
Implements OutputGenIntf.
Definition at line 85 of file mangen.h.
{ return std::make_unique<ManGenerator>(*this); }
docify()
void ManGenerator::docify (const QCString & text) override virtual
Implements OutputGenIntf.
Definition at line 459 of file mangen.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c=0;
    while ((c=*p++))
    {
      switch(c)
      {
        case '-':  m_t << "\\-";           break; // see  bug747780
        case '.':  m_t << "\\&.";          break; // see  bug652277
        case '\\': m_t << "\\\\"; m_col++; break;
        case '\n': m_t << "\n";   m_col=0; break;
        case '\"': c = '\'';         // no break!
        default:   m_t << c;      m_col++; break;
      }
    }
    m_firstCol=(c=='\n');
    //printf("%s",str);fflush(stdout);
  }
  m_paragraph=FALSE;
}
References QCString::data(), FALSE, QCString::isEmpty(), m_col, m_firstCol, m_paragraph, and OutputGenerator::m_t.
Referenced by startConstraintList(), startDescTable(), startExamples(), startMemberDocSimple(), startParameterDefVal(), writeObjectLink(), and writeString().
endAnonTypeScope()
void ManGenerator::endAnonTypeScope (int indentLevel) override virtual
Implements OutputGenIntf.
Definition at line 614 of file mangen.cpp.
{
  if (indentLevel==0)
  {
    m_insideTabbing=FALSE;
  }
}
References FALSE, and m_insideTabbing.
endBold()
void ManGenerator::endBold () inline override virtual
Implements OutputGenIntf.
Definition at line 169 of file mangen.h.
{ m_t << "\\fP"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by startConstraintList(), startDescTable(), startExamples(), and writeObjectLink().
endBoldEmphasis()
void ManGenerator::endBoldEmphasis () inline
Definition at line 171 of file mangen.h.
{ m_t << "\\fP"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by endDescTableTitle().
endCallGraph()
void ManGenerator::endCallGraph (DotCallGraph &) inline override virtual
Implements OutputGenIntf.
Definition at line 236 of file mangen.h.
{}
endCenter()
void ManGenerator::endCenter () inline override virtual
Implements OutputGenIntf.
Definition at line 184 of file mangen.h.
{}
endClassDiagram()
void ManGenerator::endClassDiagram (const ClassDiagram & , const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 204 of file mangen.h.
{}
endCompoundTemplateParams()
void ManGenerator::endCompoundTemplateParams () override virtual
Implements OutputGenIntf.
Definition at line 580 of file mangen.cpp.
{
  m_t << "\"";
}
References OutputGenerator::m_t.
endConstraintDocs()
void ManGenerator::endConstraintDocs () override virtual
Implements OutputGenIntf.
Definition at line 816 of file mangen.cpp.
{
  m_t << "\n"; m_firstCol=TRUE;
}
References m_firstCol, OutputGenerator::m_t, and TRUE.
endConstraintList()
void ManGenerator::endConstraintList () override virtual
Implements OutputGenIntf.
Definition at line 821 of file mangen.cpp.
{
}
endConstraintParam()
void ManGenerator::endConstraintParam () override virtual
Implements OutputGenIntf.
Definition at line 795 of file mangen.cpp.
{
  endEmphasis();
  endItemListItem();
  m_t << " : ";
}
References endEmphasis(), endItemListItem(), and OutputGenerator::m_t.
endConstraintType()
void ManGenerator::endConstraintType () override virtual
Implements OutputGenIntf.
Definition at line 807 of file mangen.cpp.
{
  endEmphasis();
}
References endEmphasis().
endContents()
void ManGenerator::endContents () inline override virtual
Implements OutputGenIntf.
Definition at line 215 of file mangen.h.
{}
endDescForItem()
void ManGenerator::endDescForItem () override virtual
Implements OutputGenIntf.
Definition at line 602 of file mangen.cpp.
{
}
Referenced by endDescTable().
endDescTable()
void ManGenerator::endDescTable () override virtual
Implements OutputGenIntf.
Definition at line 758 of file mangen.cpp.
{
  endDescForItem();
}
References endDescForItem().
endDescTableData()
void ManGenerator::endDescTableData () inline override virtual
Implements OutputGenIntf.
Definition at line 227 of file mangen.h.
{}
endDescTableInit()
void ManGenerator::endDescTableInit () inline override virtual
Implements OutputGenIntf.
Definition at line 225 of file mangen.h.
{};
endDescTableRow()
void ManGenerator::endDescTableRow () inline override virtual
Implements OutputGenIntf.
Definition at line 223 of file mangen.h.
{}
endDescTableTitle()
void ManGenerator::endDescTableTitle () inline override virtual
Implements OutputGenIntf.
Definition at line 221 of file mangen.h.
{ endBoldEmphasis(); }
References endBoldEmphasis().
endDirDepGraph()
void ManGenerator::endDirDepGraph (DotDirDeps &) inline override virtual
Implements OutputGenIntf.
Definition at line 238 of file mangen.h.
{}
endDotGraph()
void ManGenerator::endDotGraph (DotClassGraph &) inline override virtual
Implements OutputGenIntf.
Definition at line 230 of file mangen.h.
{}
endDoxyAnchor()
void ManGenerator::endDoxyAnchor (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 177 of file mangen.h.
{}
endEmphasis()
void ManGenerator::endEmphasis () inline override virtual
Implements OutputGenIntf.
Definition at line 167 of file mangen.h.
{ m_t << "\\fP"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by endConstraintParam(), and endConstraintType().
endExamples()
void ManGenerator::endExamples () override virtual
Implements OutputGenIntf.
Definition at line 739 of file mangen.cpp.
{
}
endFile()
void ManGenerator::endFile () override virtual
Implements OutputGenIntf.
Definition at line 343 of file mangen.cpp.
{
  m_t << "\n";
  endPlainFile();
}
References endPlainFile(), and OutputGenerator::m_t.
endGroupCollaboration()
void ManGenerator::endGroupCollaboration (DotGroupCollaboration &) inline override virtual
Implements OutputGenIntf.
Definition at line 234 of file mangen.h.
{}
endGroupHeader()
void ManGenerator::endGroupHeader (int) override virtual
Implements OutputGenIntf.
Definition at line 438 of file mangen.cpp.
{
  m_t << "\"\n.PP \n";
  m_firstCol=TRUE;
  m_paragraph=TRUE;
  m_upperCase=FALSE;
}
References FALSE, m_firstCol, m_paragraph, OutputGenerator::m_t, m_upperCase, and TRUE.
Referenced by endSection().
endHeaderSection()
void ManGenerator::endHeaderSection () override virtual
Implements OutputGenIntf.
Definition at line 913 of file mangen.cpp.
{
}
endInclDepGraph()
void ManGenerator::endInclDepGraph (DotInclDepGraph &) inline override virtual
Implements OutputGenIntf.
Definition at line 232 of file mangen.h.
{}
endIndent()
void ManGenerator::endIndent () inline override virtual
Implements OutputGenIntf.
Definition at line 201 of file mangen.h.
{}
endIndexItem()
void ManGenerator::endIndexItem (const QCString & ref, const QCString & file) override virtual
Implements OutputGenIntf.
Definition at line 415 of file mangen.cpp.
{
}
endIndexKey()
void ManGenerator::endIndexKey () inline override virtual
Implements OutputGenIntf.
Definition at line 114 of file mangen.h.
{}
endIndexList()
void ManGenerator::endIndexList () inline override virtual
Implements OutputGenIntf.
Definition at line 112 of file mangen.h.
{ newParagraph(); }
References newParagraph().
endIndexListItem()
void ManGenerator::endIndexListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 110 of file mangen.h.
{}
endIndexSection()
void ManGenerator::endIndexSection (IndexSection) inline override virtual
Implements OutputGenIntf.
Definition at line 98 of file mangen.h.
{}
endIndexValue()
void ManGenerator::endIndexValue (const QCString & , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 116 of file mangen.h.
{}
endInlineHeader()
void ManGenerator::endInlineHeader () override virtual
Implements OutputGenIntf.
Definition at line 835 of file mangen.cpp.
{
  m_t << "\\fP\"\n" << ".in +1c\n";
  m_firstCol = FALSE;
}
References FALSE, m_firstCol, and OutputGenerator::m_t.
endInlineMemberDoc()
void ManGenerator::endInlineMemberDoc () override virtual
Implements OutputGenIntf.
Definition at line 891 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".br\n";
  m_t << ".PP\n";
  m_firstCol=TRUE;
}
References m_firstCol, OutputGenerator::m_t, and TRUE.
endInlineMemberName()
void ManGenerator::endInlineMemberName () override virtual
Implements OutputGenIntf.
Definition at line 882 of file mangen.cpp.
{
  m_t << "\\fP ";
}
References OutputGenerator::m_t.
endInlineMemberType()
void ManGenerator::endInlineMemberType () override virtual
Implements OutputGenIntf.
Definition at line 872 of file mangen.cpp.
{
  m_t << " ";
}
References OutputGenerator::m_t.
endItemList()
void ManGenerator::endItemList () inline override virtual
Implements OutputGenIntf.
Definition at line 118 of file mangen.h.
{ newParagraph(); }
References newParagraph().
endItemListItem()
void ManGenerator::endItemListItem () override virtual
Implements OutputGenIntf.
Definition at line 519 of file mangen.cpp.
{
}
Referenced by endConstraintParam(), and startDescTableTitle().
endLabels()
void ManGenerator::endLabels () override virtual
Implements OutputGenIntf.
Definition at line 909 of file mangen.cpp.
{
}
endMemberDeclaration()
void ManGenerator::endMemberDeclaration (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 190 of file mangen.h.
{}
endMemberDescription()
void ManGenerator::endMemberDescription () inline override virtual
Implements OutputGenIntf.
Definition at line 188 of file mangen.h.
{ m_t << "\""; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
endMemberDoc()
void ManGenerator::endMemberDoc (bool) override virtual
Implements OutputGenIntf.
Definition at line 567 of file mangen.cpp.
{
    m_t << "\"\n";
}
References OutputGenerator::m_t.
endMemberDocList()
void ManGenerator::endMemberDocList () inline override virtual
Implements OutputGenIntf.
Definition at line 143 of file mangen.h.
{}
endMemberDocName()
void ManGenerator::endMemberDocName () inline override virtual
Implements OutputGenIntf.
Definition at line 248 of file mangen.h.
{}
endMemberDocPrefixItem()
void ManGenerator::endMemberDocPrefixItem () inline override virtual
Implements OutputGenIntf.
Definition at line 246 of file mangen.h.
{}
endMemberDocSimple()
void ManGenerator::endMemberDocSimple (bool) override virtual
Implements OutputGenIntf.
Definition at line 860 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".RE\n";
  m_t << ".PP\n";
  m_firstCol=TRUE;
}
References m_firstCol, OutputGenerator::m_t, and TRUE.
endMemberGroup()
void ManGenerator::endMemberGroup (bool) override virtual
Implements OutputGenIntf.
Definition at line 676 of file mangen.cpp.
{
  m_t << "\n.in -1c";
  m_firstCol=FALSE;
}
References FALSE, m_firstCol, and OutputGenerator::m_t.
endMemberGroupDocs()
void ManGenerator::endMemberGroupDocs () override virtual
Implements OutputGenIntf.
Definition at line 666 of file mangen.cpp.
{
  m_t << "\n.PP";
}
References OutputGenerator::m_t.
endMemberGroupHeader()
void ManGenerator::endMemberGroupHeader () override virtual
Implements OutputGenIntf.
Definition at line 656 of file mangen.cpp.
{
  m_t << "\\fP\"\n.br\n";
  m_firstCol=TRUE;
}
References m_firstCol, OutputGenerator::m_t, and TRUE.
endMemberHeader()
void ManGenerator::endMemberHeader () override virtual
Implements OutputGenIntf.
Definition at line 452 of file mangen.cpp.
{
  m_t << "\"\n";
  m_firstCol=TRUE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
Referenced by endSection().
endMemberItem()
void ManGenerator::endMemberItem (MemberItemType) override virtual
Implements OutputGenIntf.
Definition at line 630 of file mangen.cpp.
{
  m_t << "\"\n.br";
}
References OutputGenerator::m_t.
endMemberList()
void ManGenerator::endMemberList () override virtual
Implements OutputGenIntf.
Definition at line 643 of file mangen.cpp.
{
  if (!m_insideTabbing)
  {
    m_t << "\n.in -1c"; m_firstCol=FALSE;
  }
}
References FALSE, m_firstCol, m_insideTabbing, and OutputGenerator::m_t.
endMemberSections()
void ManGenerator::endMemberSections () inline override virtual
Implements OutputGenIntf.
Definition at line 131 of file mangen.h.
{}
endMemberSubtitle()
void ManGenerator::endMemberSubtitle () inline override virtual
Implements OutputGenIntf.
Definition at line 139 of file mangen.h.
{}
endMemberTemplateParams()
void ManGenerator::endMemberTemplateParams (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 153 of file mangen.h.
{}
endPageDoc()
void ManGenerator::endPageDoc () inline override virtual
Implements OutputGenIntf.
Definition at line 96 of file mangen.h.
{}
endPageRef()
void ManGenerator::endPageRef (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 206 of file mangen.h.
{}
endParagraph()
void ManGenerator::endParagraph () override virtual
Implements OutputGenIntf.
Definition at line 402 of file mangen.cpp.
{
}
endParameterDefVal()
void ManGenerator::endParameterDefVal () inline override virtual
Implements OutputGenIntf.
Definition at line 256 of file mangen.h.
{ endTypewriter(); }
References endTypewriter().
endParameterExtra()
void ManGenerator::endParameterExtra (bool last, bool , bool closeBracket) override virtual
Implements OutputGenIntf.
Definition at line 932 of file mangen.cpp.
{
  if (last && closeBracket)
  {
    m_t << ")";
  }
}
References OutputGenerator::m_t.
endParameterList()
void ManGenerator::endParameterList () inline override virtual
Implements OutputGenIntf.
Definition at line 258 of file mangen.h.
{}
endParameterName()
void ManGenerator::endParameterName () inline override virtual
Implements OutputGenIntf.
Definition at line 252 of file mangen.h.
{}
endParameterType()
void ManGenerator::endParameterType () override virtual
Implements OutputGenIntf.
Definition at line 939 of file mangen.cpp.
{
  m_t << " ";
}
References OutputGenerator::m_t.
endPlainFile()
void ManGenerator::endPlainFile () inline override virtual
Implements OutputGenIntf.
Definition at line 286 of file mangen.h.
{ OutputGenerator::endPlainFile(); }
References OutputGenerator::endPlainFile().
Referenced by endFile().
endProjectNumber()
void ManGenerator::endProjectNumber () inline override virtual
Implements OutputGenIntf.
Definition at line 101 of file mangen.h.
{}
endQuickIndices()
void ManGenerator::endQuickIndices () inline override virtual
Implements OutputGenIntf.
Definition at line 208 of file mangen.h.
{}
endSection()
void ManGenerator::endSection (const QCString & , SectionType type) override virtual
Implements OutputGenIntf.
Definition at line 700 of file mangen.cpp.
{
  if( !m_inHeader )
  {
    switch(type.level())
    {
      case SectionType::Page:            // fall through
      case SectionType::Section:         endGroupHeader(0); break;
      case SectionType::Subsection:      // fall through
      case SectionType::Subsubsection:   // fall through
      case SectionType::Paragraph:       // fall through
      case SectionType::Subparagraph:    // fall through
      case SectionType::Subsubparagraph: endMemberHeader(); break;
      default: ASSERT(0); break;
    }
  }
  else
  {
    m_t << "\n.PP\n";
    m_firstCol=TRUE;
    m_paragraph=FALSE;
    m_inHeader=FALSE;
  }
}
References ASSERT, endGroupHeader(), endMemberHeader(), FALSE, m_firstCol, m_inHeader, m_paragraph, OutputGenerator::m_t, SectionType::Page, SectionType::Paragraph, SectionType::Section, SectionType::Subparagraph, SectionType::Subsection, SectionType::Subsubparagraph, SectionType::Subsubsection, TRUE, and type().
endSmall()
void ManGenerator::endSmall () inline override virtual
Implements OutputGenIntf.
Definition at line 186 of file mangen.h.
{}
endTextBlock()
void ManGenerator::endTextBlock (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 242 of file mangen.h.
{}
endTextLink()
void ManGenerator::endTextLink () inline override virtual
Implements OutputGenIntf.
Definition at line 125 of file mangen.h.
{}
endTitle()
void ManGenerator::endTitle () private
Definition at line 505 of file mangen.cpp.
{
    m_t << "\"";
}
References OutputGenerator::m_t.
endTitleHead()
void ManGenerator::endTitleHead (const QCString & , const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 349 of file mangen.cpp.
{
  m_t << ".TH \"" << name << "\" " << getExtension() << " \"";
  switch (Config_getEnum(TIMESTAMP))
  {
    case TIMESTAMP_t::YES:
    case TIMESTAMP_t::DATETIME:
      m_t << dateToString(DateTimeType::DateTime) << "\" \"";
      break;
    case TIMESTAMP_t::DATE:
      m_t << dateToString(DateTimeType::Date) << "\" \"";
      break;
    case TIMESTAMP_t::NO:
      break;
  }
  if (!Config_getString(PROJECT_NUMBER).isEmpty())
    m_t << "Version " << Config_getString(PROJECT_NUMBER) << "\" \"";
  if (Config_getString(PROJECT_NAME).isEmpty())
    m_t << "Doxygen";
  else
    m_t << Config_getString(PROJECT_NAME);
  m_t << "\" \\\" -*- nroff -*-\n";
  m_t << ".ad l\n";
  m_t << ".nh\n";
  m_t << ".SH NAME\n";
  m_t << name;
  m_firstCol=FALSE;
  m_paragraph=TRUE;
  m_inHeader=TRUE;
}
References Config_getEnum, Config_getString, Date, DateTime, dateToString(), FALSE, getExtension(), m_firstCol, m_inHeader, m_paragraph, OutputGenerator::m_t, and TRUE.
endTypewriter()
void ManGenerator::endTypewriter () inline override virtual
Implements OutputGenIntf.
Definition at line 127 of file mangen.h.
{ m_t << "\\fP"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by endParameterDefVal().
exceptionEntry()
void ManGenerator::exceptionEntry (const QCString & , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 259 of file mangen.h.
{}
init()
void ManGenerator::init () static
Definition at line 272 of file mangen.cpp.
{
  QCString manOutput = Config_getString(MAN_OUTPUT);
  Dir d(manOutput.str());
  if (!d.exists() && !d.mkdir(manOutput.str()))
  {
    term("Could not create output directory %s\n",qPrint(manOutput));
  }
  std::string manDir = manOutput.str()+"/"+getSubdir().str();
  if (!d.exists(manDir) && !d.mkdir(manDir))
  {
    term("Could not create output directory %s/%s\n",qPrint(manOutput), qPrint(getSubdir()));
  }
  createSubDirs(d);
}
References Config_getString, createSubDirs(), Dir::exists(), getSubdir(), Dir::mkdir(), qPrint(), QCString::str(), and term.
Referenced by generateOutput().
insertMemberAlign()
void ManGenerator::insertMemberAlign (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 136 of file mangen.h.
{}
insertMemberAlignLeft()
void ManGenerator::insertMemberAlignLeft (MemberItemType , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 137 of file mangen.h.
{}
lastIndexPage()
void ManGenerator::lastIndexPage () inline override virtual
Implements OutputGenIntf.
Definition at line 243 of file mangen.h.
{}
lineBreak()
void ManGenerator::lineBreak (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 172 of file mangen.h.
{ m_t << "\n.br\n"; }
References OutputGenerator::m_t.
newParagraph()
void ManGenerator::newParagraph ()
Definition at line 380 of file mangen.cpp.
{
  if (!m_paragraph)
  {
    if (!m_firstCol) m_t << "\n";
    m_t << ".PP\n";
    m_firstCol=TRUE;
  }
  m_paragraph=TRUE;
}
References m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
Referenced by endIndexList(), and endItemList().
operator=() [1/2]
ManGenerator & ManGenerator::operator= (const ManGenerator & og)
Definition at line 247 of file mangen.cpp.
{
  if (this!=&og)
  {
    m_dir           = og.m_dir;
    m_codeList = std::make_unique<OutputCodeList>(*og.m_codeList);
    m_codeGen       = m_codeList->get<ManCodeGenerator>(OutputType::Man);
    m_codeGen->setTextStream(&m_t);
    m_firstCol      = og.m_firstCol;
    m_col           = og.m_col;
    m_paragraph     = og.m_paragraph;
    m_upperCase     = og.m_upperCase;
    m_insideTabbing = og.m_insideTabbing;
    m_inHeader      = og.m_inHeader;
  }
  return *this;
}
References m_codeGen, m_codeList, m_col, OutputGenerator::m_dir, m_firstCol, m_inHeader, m_insideTabbing, m_paragraph, OutputGenerator::m_t, m_upperCase, Man, and ManGenerator().
operator=() [2/2]
ManGenerator & ManGenerator::operator= (ManGenerator &&) delete
References ManGenerator().
startAnonTypeScope()
void ManGenerator::startAnonTypeScope (int indentLevel) override virtual
Implements OutputGenIntf.
Definition at line 606 of file mangen.cpp.
{
  if (indentLevel==0)
  {
    m_insideTabbing=TRUE;
  }
}
References m_insideTabbing, and TRUE.
startBold()
void ManGenerator::startBold () inline override virtual
Implements OutputGenIntf.
Definition at line 168 of file mangen.h.
{ m_t << "\\fB"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by startConstraintList(), startDescTable(), startExamples(), and writeObjectLink().
startBoldEmphasis()
void ManGenerator::startBoldEmphasis () inline
Definition at line 170 of file mangen.h.
{ m_t << "\\f(BI"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by startDescTableTitle().
startCallGraph()
void ManGenerator::startCallGraph () inline override virtual
Implements OutputGenIntf.
Definition at line 235 of file mangen.h.
{}
startCenter()
void ManGenerator::startCenter () inline override virtual
Implements OutputGenIntf.
Definition at line 183 of file mangen.h.
{}
startClassDiagram()
void ManGenerator::startClassDiagram () inline override virtual
Implements OutputGenIntf.
Definition at line 203 of file mangen.h.
{}
startCompoundTemplateParams()
void ManGenerator::startCompoundTemplateParams () override virtual
Implements OutputGenIntf.
Definition at line 572 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << "\n.SS \"";
  m_firstCol=FALSE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, and OutputGenerator::m_t.
startConstraintDocs()
void ManGenerator::startConstraintDocs () override virtual
Implements OutputGenIntf.
Definition at line 812 of file mangen.cpp.
{
}
startConstraintList()
void ManGenerator::startConstraintList (const QCString & header) override virtual
Implements OutputGenIntf.
Definition at line 775 of file mangen.cpp.
{
  if (!m_firstCol)
  { m_t << "\n.PP\n";
    m_firstCol=TRUE; m_paragraph=TRUE;
    m_col=0;
  }
  m_paragraph=FALSE;
  startBold();
  docify(header);
  endBold();
  m_paragraph=TRUE;
}
References docify(), endBold(), FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, startBold(), and TRUE.
startConstraintParam()
void ManGenerator::startConstraintParam () override virtual
Implements OutputGenIntf.
Definition at line 789 of file mangen.cpp.
{
  startItemListItem();
  startEmphasis();
}
References startEmphasis(), and startItemListItem().
startConstraintType()
void ManGenerator::startConstraintType () override virtual
Implements OutputGenIntf.
Definition at line 802 of file mangen.cpp.
{
  startEmphasis();
}
References startEmphasis().
startContents()
void ManGenerator::startContents () inline override virtual
Implements OutputGenIntf.
Definition at line 214 of file mangen.h.
{}
startDescForItem()
void ManGenerator::startDescForItem () override virtual
Implements OutputGenIntf.
Definition at line 592 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  if (!m_paragraph) m_t << ".in -1c\n";
  m_t << ".in +1c\n";
  m_firstCol=TRUE;
  m_paragraph=FALSE;
  m_col=0;
}
References FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
Referenced by startDescTable().
startDescTable()
void ManGenerator::startDescTable (const QCString & title, const bool hasInits) override virtual
Implements OutputGenIntf.
Definition at line 743 of file mangen.cpp.
{
  if (!m_firstCol)
  { m_t << "\n.PP\n";
    m_firstCol=TRUE; m_paragraph=TRUE;
    m_col=0;
  }
  m_paragraph=FALSE;
  startBold();
  docify(title);
  endBold();
  m_paragraph=TRUE;
  startDescForItem();
}
References docify(), endBold(), FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, startBold(), startDescForItem(), and TRUE.
startDescTableData()
void ManGenerator::startDescTableData () inline override virtual
Implements OutputGenIntf.
Definition at line 226 of file mangen.h.
{ m_t << "\n"; m_firstCol=TRUE; }
References m_firstCol, OutputGenerator::m_t, and TRUE.
startDescTableInit()
void ManGenerator::startDescTableInit () inline override virtual
Implements OutputGenIntf.
Definition at line 224 of file mangen.h.
{};
startDescTableRow()
void ManGenerator::startDescTableRow () inline override virtual
Implements OutputGenIntf.
Definition at line 222 of file mangen.h.
{}
startDescTableTitle()
void ManGenerator::startDescTableTitle () inline override virtual
Implements OutputGenIntf.
Definition at line 220 of file mangen.h.
{ startItemListItem(); startBoldEmphasis(); endItemListItem(); }
References endItemListItem(), startBoldEmphasis(), and startItemListItem().
startDirDepGraph()
void ManGenerator::startDirDepGraph () inline override virtual
Implements OutputGenIntf.
Definition at line 237 of file mangen.h.
{}
startDotGraph()
void ManGenerator::startDotGraph () inline override virtual
Implements OutputGenIntf.
Definition at line 229 of file mangen.h.
{}
startDoxyAnchor()
void ManGenerator::startDoxyAnchor (const QCString & , const QCString & manName, const QCString & , const QCString & name, const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 531 of file mangen.cpp.
{
    // something to be done?
    if( !Config_getBool(MAN_LINKS) )
    {
        return; // no
    }
    // the name of the link file is derived from the name of the anchor:
    // - truncate after an (optional) ::
    QCString baseName = name;
    int i=baseName.findRev("::");
    if (i!=-1) baseName=baseName.right(baseName.length()-i-2);
    //printf("Converting man link '%s'->'%s'->'%s'\n",
    //       name,qPrint(baseName),qPrint(buildFileName(baseName)));
    // - remove dangerous characters and append suffix, then add dir prefix
    QCString fileName=dir()+"/"+buildFileName( baseName );
    FileInfo fi(fileName.str());
    if (!fi.exists())
    {
      std::ofstream linkStream = Portable::openOutputStream(fileName);
      if (linkStream.is_open())
      {
        linkStream << ".so " << getSubdir() << "/" << buildFileName( manName ) << "\n";
      }
    }
}
References buildFileName(), Config_getBool, OutputGenerator::dir(), FileInfo::exists(), OutputGenerator::fileName(), QCString::findRev(), getSubdir(), QCString::length(), Portable::openOutputStream(), and QCString::right().
startEmphasis()
void ManGenerator::startEmphasis () inline override virtual
Implements OutputGenIntf.
Definition at line 166 of file mangen.h.
{ m_t << "\\fI"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by startConstraintParam(), and startConstraintType().
startExamples()
void ManGenerator::startExamples () override virtual
Implements OutputGenIntf.
Definition at line 725 of file mangen.cpp.
{
  if (!m_firstCol)
  { m_t << "\n" << ".PP\n";
    m_firstCol=TRUE; m_paragraph=TRUE;
    m_col=0;
  }
  m_paragraph=FALSE;
  startBold();
  docify(theTranslator->trExamples());
  endBold();
  m_paragraph=TRUE;
}
References docify(), endBold(), FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, startBold(), theTranslator, Translator::trExamples(), and TRUE.
startFile()
void ManGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id, int hierarchyLevel) override virtual
Implements OutputGenIntf.
Definition at line 337 of file mangen.cpp.
{
  startPlainFile( buildFileName( manName ) );
  m_firstCol=TRUE;
}
References buildFileName(), m_firstCol, startPlainFile(), and TRUE.
startGroupCollaboration()
void ManGenerator::startGroupCollaboration () inline override virtual
Implements OutputGenIntf.
Definition at line 233 of file mangen.h.
{}
startGroupHeader()
void ManGenerator::startGroupHeader (int) override virtual
Implements OutputGenIntf.
Definition at line 430 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".SH \"";
  m_upperCase=TRUE;
  m_firstCol=FALSE;
}
References FALSE, m_firstCol, OutputGenerator::m_t, m_upperCase, and TRUE.
Referenced by startSection().
startHeaderSection()
void ManGenerator::startHeaderSection () inline override virtual
Implements OutputGenIntf.
Definition at line 132 of file mangen.h.
{}
startInclDepGraph()
void ManGenerator::startInclDepGraph () inline override virtual
Implements OutputGenIntf.
Definition at line 231 of file mangen.h.
{}
startIndent()
void ManGenerator::startIndent () inline override virtual
Implements OutputGenIntf.
Definition at line 200 of file mangen.h.
{}
startIndexItem()
void ManGenerator::startIndexItem (const QCString & ref, const QCString & file) override virtual
Implements OutputGenIntf.
Definition at line 411 of file mangen.cpp.
{
}
startIndexKey()
void ManGenerator::startIndexKey () inline override virtual
Implements OutputGenIntf.
Definition at line 113 of file mangen.h.
{}
startIndexList()
void ManGenerator::startIndexList () inline override virtual
Implements OutputGenIntf.
Definition at line 111 of file mangen.h.
{}
startIndexListItem()
void ManGenerator::startIndexListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 109 of file mangen.h.
{}
startIndexSection()
void ManGenerator::startIndexSection (IndexSection) inline override virtual
Implements OutputGenIntf.
Definition at line 97 of file mangen.h.
{}
startIndexValue()
void ManGenerator::startIndexValue (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 115 of file mangen.h.
{}
startInlineHeader()
void ManGenerator::startInlineHeader () override virtual
Implements OutputGenIntf.
Definition at line 826 of file mangen.cpp.
{
  if (!m_firstCol)
  {
    m_t << "\n.PP\n" << ".in -1c\n";
  }
  m_t << ".RI \"\\fB";
}
References m_firstCol, and OutputGenerator::m_t.
startInlineMemberDoc()
void ManGenerator::startInlineMemberDoc () override virtual
Implements OutputGenIntf.
Definition at line 887 of file mangen.cpp.
{
}
startInlineMemberName()
void ManGenerator::startInlineMemberName () override virtual
Implements OutputGenIntf.
Definition at line 877 of file mangen.cpp.
{
  m_t << "\\fI";
}
References OutputGenerator::m_t.
startInlineMemberType()
void ManGenerator::startInlineMemberType () override virtual
Implements OutputGenIntf.
Definition at line 868 of file mangen.cpp.
{
}
startItemList()
void ManGenerator::startItemList () inline override virtual
Implements OutputGenIntf.
Definition at line 117 of file mangen.h.
{}
startItemListItem()
void ManGenerator::startItemListItem () override virtual
Implements OutputGenIntf.
Definition at line 510 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".TP\n";
  m_firstCol=TRUE;
  m_paragraph=FALSE;
  m_col=0;
}
References FALSE, m_col, m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
Referenced by startConstraintParam(), and startDescTableTitle().
startLabels()
void ManGenerator::startLabels () override virtual
Implements OutputGenIntf.
Definition at line 899 of file mangen.cpp.
{
}
startMemberDeclaration()
void ManGenerator::startMemberDeclaration () inline override virtual
Implements OutputGenIntf.
Definition at line 189 of file mangen.h.
{}
startMemberDescription()
void ManGenerator::startMemberDescription (const QCString & , const QCString & , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 187 of file mangen.h.
{ m_t << "\n.RI \""; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
startMemberDoc()
void ManGenerator::startMemberDoc (const QCString & , const QCString & , const QCString & , const QCString & , int , int , bool) override virtual
Implements OutputGenIntf.
Definition at line 523 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".SS \"";
  m_firstCol=FALSE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, and OutputGenerator::m_t.
startMemberDocList()
void ManGenerator::startMemberDocList () inline override virtual
Implements OutputGenIntf.
Definition at line 142 of file mangen.h.
{}
startMemberDocName()
void ManGenerator::startMemberDocName (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 247 of file mangen.h.
{}
startMemberDocPrefixItem()
void ManGenerator::startMemberDocPrefixItem () inline override virtual
Implements OutputGenIntf.
Definition at line 245 of file mangen.h.
{}
startMemberDocSimple()
void ManGenerator::startMemberDocSimple (bool isEnum) override virtual
Implements OutputGenIntf.
Definition at line 841 of file mangen.cpp.
{
  if (!m_firstCol)
  {
    m_t << "\n.PP\n";
  }
  m_t << "\\fB";
  if (isEnum)
  {
    docify(theTranslator->trEnumerationValues());
  }
  else
  {
    docify(theTranslator->trCompoundMembers());
  }
  m_t << ":\\fP\n";
  m_t << ".RS 4\n";
}
References docify(), m_firstCol, OutputGenerator::m_t, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberGroup()
void ManGenerator::startMemberGroup () override virtual
Implements OutputGenIntf.
Definition at line 671 of file mangen.cpp.
{
  m_t << "\n.in +1c";
}
References OutputGenerator::m_t.
startMemberGroupDocs()
void ManGenerator::startMemberGroupDocs () override virtual
Implements OutputGenIntf.
Definition at line 662 of file mangen.cpp.
{
}
startMemberGroupHeader()
void ManGenerator::startMemberGroupHeader (bool) override virtual
Implements OutputGenIntf.
Definition at line 651 of file mangen.cpp.
{
  m_t << "\n.PP\n.RI \"\\fB";
}
References OutputGenerator::m_t.
startMemberHeader()
void ManGenerator::startMemberHeader (const QCString & , int) override virtual
Implements OutputGenIntf.
Definition at line 446 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".SS \"";
}
References m_firstCol, and OutputGenerator::m_t.
Referenced by startSection().
startMemberItem()
void ManGenerator::startMemberItem (const QCString & , MemberItemType , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 623 of file mangen.cpp.
{
  if (m_firstCol && !m_insideTabbing) m_t << ".in +1c\n";
  m_t << "\n.ti -1c\n.RI \"";
  m_firstCol=FALSE;
}
References FALSE, m_firstCol, m_insideTabbing, and OutputGenerator::m_t.
startMemberList()
void ManGenerator::startMemberList () override virtual
Implements OutputGenIntf.
Definition at line 635 of file mangen.cpp.
{
  if (!m_insideTabbing)
  {
    m_t << "\n.in +1c"; m_firstCol=FALSE;
  }
}
References FALSE, m_firstCol, m_insideTabbing, and OutputGenerator::m_t.
startMemberSections()
void ManGenerator::startMemberSections () inline override virtual
Implements OutputGenIntf.
Definition at line 130 of file mangen.h.
{}
startMemberSubtitle()
void ManGenerator::startMemberSubtitle () inline override virtual
Implements OutputGenIntf.
Definition at line 138 of file mangen.h.
{}
startMemberTemplateParams()
void ManGenerator::startMemberTemplateParams () inline override virtual
Implements OutputGenIntf.
Definition at line 152 of file mangen.h.
{}
startPageDoc()
void ManGenerator::startPageDoc (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 95 of file mangen.h.
{}
startPageRef()
void ManGenerator::startPageRef () inline override virtual
Implements OutputGenIntf.
Definition at line 205 of file mangen.h.
{}
startParagraph()
void ManGenerator::startParagraph (const QCString & classDef) override virtual
Implements OutputGenIntf.
Definition at line 391 of file mangen.cpp.
{
  if (!m_paragraph)
  {
    if (!m_firstCol) m_t << "\n";
    m_t << ".PP\n";
    m_firstCol=TRUE;
  }
  m_paragraph=TRUE;
}
References m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
startParameterDefVal()
void ManGenerator::startParameterDefVal (const char * s) inline override virtual
Implements OutputGenIntf.
Definition at line 255 of file mangen.h.
{ docify(s); startTypewriter(); }
References docify(), and startTypewriter().
startParameterExtra()
void ManGenerator::startParameterExtra () inline override virtual
Implements OutputGenIntf.
Definition at line 253 of file mangen.h.
{}
startParameterList()
void ManGenerator::startParameterList (bool openBracket) override virtual
Implements OutputGenIntf.
Definition at line 927 of file mangen.cpp.
{
  if (openBracket) m_t << "(";
}
References OutputGenerator::m_t.
startParameterName()
void ManGenerator::startParameterName (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 251 of file mangen.h.
{}
startParameterType()
void ManGenerator::startParameterType (bool , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 249 of file mangen.h.
{}
startPlainFile()
void ManGenerator::startPlainFile (const QCString & name) inline override virtual
Implements OutputGenIntf.
Definition at line 285 of file mangen.h.
{ OutputGenerator::startPlainFile(name); }
References OutputGenerator::startPlainFile().
Referenced by startFile().
startProjectNumber()
void ManGenerator::startProjectNumber () inline override virtual
Implements OutputGenIntf.
Definition at line 100 of file mangen.h.
{}
startQuickIndices()
void ManGenerator::startQuickIndices () inline override virtual
Implements OutputGenIntf.
Definition at line 207 of file mangen.h.
{}
startSection()
void ManGenerator::startSection (const QCString & , const QCString & , SectionType type) override virtual
Implements OutputGenIntf.
Definition at line 682 of file mangen.cpp.
{
  if( !m_inHeader )
  {
    switch(type.level())
    {
      case SectionType::Page:             // fall through
      case SectionType::Section:          startGroupHeader(0); break;
      case SectionType::Subsection:       // fall through
      case SectionType::Subsubsection:    // fall through
      case SectionType::Paragraph:        // fall through
      case SectionType::Subparagraph:     // fall through
      case SectionType::Subsubparagraph:  startMemberHeader(QCString(), -1); break;
      default: ASSERT(0); break;
    }
  }
}
References ASSERT, m_inHeader, SectionType::Page, SectionType::Paragraph, SectionType::Section, startGroupHeader(), startMemberHeader(), SectionType::Subparagraph, SectionType::Subsection, SectionType::Subsubparagraph, SectionType::Subsubsection, and type().
startSmall()
void ManGenerator::startSmall () inline override virtual
Implements OutputGenIntf.
Definition at line 185 of file mangen.h.
{}
startTextBlock()
void ManGenerator::startTextBlock (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 241 of file mangen.h.
{}
startTextLink()
void ManGenerator::startTextLink (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 124 of file mangen.h.
{}
startTitle()
void ManGenerator::startTitle () private
Definition at line 497 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".SH \"";
  m_firstCol=FALSE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, and OutputGenerator::m_t.
startTitleHead()
void ManGenerator::startTitleHead (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 103 of file mangen.h.
{}
startTypewriter()
void ManGenerator::startTypewriter () inline override virtual
Implements OutputGenIntf.
Definition at line 126 of file mangen.h.
{ m_t << "\\fR"; m_firstCol=FALSE; }
References FALSE, m_firstCol, and OutputGenerator::m_t.
Referenced by startParameterDefVal().
type()
OutputType ManGenerator::type () const inline override virtual
Implements OutputGenIntf.
Definition at line 84 of file mangen.h.
{ return OutputType::Man; }
References Man.
Referenced by endSection(), and startSection().
writeAnchor()
void ManGenerator::writeAnchor (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 165 of file mangen.h.
{}
writeChar()
void ManGenerator::writeChar (char c) override virtual
Implements OutputGenIntf.
Definition at line 483 of file mangen.cpp.
{
  m_firstCol=(c=='\n');
  if (m_firstCol) m_col=0; else m_col++;
  switch (c)
  {
    case '\\': m_t << "\\\\"; break;
  case '\"': c = '\''; // no break!
    default:   m_t << c; break;
  }
  //printf("%c",c);fflush(stdout);
  m_paragraph=FALSE;
}
References FALSE, m_col, m_firstCol, m_paragraph, and OutputGenerator::m_t.
writeDoc()
void ManGenerator::writeDoc (const IDocNodeAST * ast, const Definition * ctx, const MemberDef * , int) override virtual
Implements OutputGenIntf.
Definition at line 763 of file mangen.cpp.
{
  const DocNodeAST *astImpl = dynamic_cast<const DocNodeAST *>(ast);
  if (astImpl)
  {
    ManDocVisitor visitor(m_t,*m_codeList,ctx?ctx->getDefFileExtension():QCString(""));
    std::visit(visitor,astImpl->root);
  }
  m_firstCol=FALSE;
  m_paragraph = FALSE;
}
References FALSE, Definition::getDefFileExtension(), m_codeList, m_firstCol, m_paragraph, OutputGenerator::m_t, and DocNodeAST::root.
writeFooter()
void ManGenerator::writeFooter (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 93 of file mangen.h.
{}
writeGraphicalHierarchy()
void ManGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) inline override virtual
Implements OutputGenIntf.
Definition at line 239 of file mangen.h.
{}
writeInheritedSectionTitle()
void ManGenerator::writeInheritedSectionTitle (const QCString & , const QCString & , const QCString & , const QCString & , const QCString & title, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 917 of file mangen.cpp.
{
  m_t << "\n\n";
  m_t << theTranslator->trInheritedFrom(docifyToString(title), objectLinkToString(name));
  m_firstCol = FALSE;
}
References docifyToString(), FALSE, m_firstCol, OutputGenerator::m_t, objectLinkToString(), theTranslator, and Translator::trInheritedFrom().
writeLabel()
void ManGenerator::writeLabel (const QCString & l, bool isLast) override virtual
Implements OutputGenIntf.
Definition at line 903 of file mangen.cpp.
{
  m_t << "\\fR [" << l << "]\\fP";
  if (!isLast) m_t << ", ";
}
References OutputGenerator::m_t.
writeLatexSpacing()
void ManGenerator::writeLatexSpacing () inline override virtual
Implements OutputGenIntf.
Definition at line 179 of file mangen.h.
{}
writeLocalToc()
void ManGenerator::writeLocalToc (const SectionRefs & , const LocalToc &) inline override virtual
Implements OutputGenIntf.
Definition at line 283 of file mangen.h.
{}
writeLogo()
void ManGenerator::writeLogo () inline override virtual
Implements OutputGenIntf.
Definition at line 211 of file mangen.h.
{}
writeNavigationPath()
void ManGenerator::writeNavigationPath (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 210 of file mangen.h.
{}
writeNonBreakableSpace()
void ManGenerator::writeNonBreakableSpace (int n) inline override virtual
Implements OutputGenIntf.
Definition at line 216 of file mangen.h.
{ for (int i=0;i<n;i++) m_t << " "; }
References OutputGenerator::m_t.
writeObjectLink()
void ManGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 424 of file mangen.cpp.
{
  startBold(); docify(name); endBold();
}
References docify(), endBold(), and startBold().
writePageLink()
void ManGenerator::writePageLink (const QCString & , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 99 of file mangen.h.
{}
writeQuickLinks()
void ManGenerator::writeQuickLinks (HighlightedItem , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 212 of file mangen.h.
{}
writeRuler()
void ManGenerator::writeRuler () inline override virtual
Implements OutputGenIntf.
Definition at line 164 of file mangen.h.
{}
writeSearchInfo()
void ManGenerator::writeSearchInfo () inline override virtual
Implements OutputGenIntf.
Definition at line 92 of file mangen.h.
{}
writeSplitBar()
void ManGenerator::writeSplitBar (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 209 of file mangen.h.
{}
writeStartAnnoItem()
void ManGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 419 of file mangen.cpp.
{
}
writeString()
void ManGenerator::writeString (const QCString & text) override virtual
Implements OutputGenIntf.
Definition at line 406 of file mangen.cpp.
{
  docify(text);
}
References docify().
writeStyleInfo()
void ManGenerator::writeStyleInfo (int) inline override virtual
Implements OutputGenIntf.
Definition at line 102 of file mangen.h.
{}
writeSummaryLink()
void ManGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 213 of file mangen.h.
{}
writeSynopsis()
void ManGenerator::writeSynopsis () override virtual
Implements OutputGenIntf.
Definition at line 584 of file mangen.cpp.
{
  if (!m_firstCol) m_t << "\n";
  m_t << ".SH SYNOPSIS\n.br\n.PP\n";
  m_firstCol=TRUE;
  m_paragraph=FALSE;
}
References FALSE, m_firstCol, m_paragraph, OutputGenerator::m_t, and TRUE.
Member Data Documentation
m_codeGen
ManCodeGenerator* ManGenerator::m_codeGen private
Definition at line 299 of file mangen.h.
Referenced by addCodeGen(), ManGenerator(), ManGenerator(), and operator=().
m_codeList
std::unique_ptr<OutputCodeList> ManGenerator::m_codeList private
Definition at line 298 of file mangen.h.
Referenced by ManGenerator(), ManGenerator(), operator=(), and writeDoc().
m_col
int ManGenerator::m_col = 0 private
Definition at line 293 of file mangen.h.
Referenced by docify(), ManGenerator(), operator=(), startConstraintList(), startDescForItem(), startDescTable(), startExamples(), startItemListItem(), and writeChar().
m_firstCol
bool ManGenerator::m_firstCol = true private
Definition at line 292 of file mangen.h.
Referenced by docify(), endBold(), endBoldEmphasis(), endConstraintDocs(), endEmphasis(), endGroupHeader(), endInlineHeader(), endInlineMemberDoc(), endMemberDescription(), endMemberDocSimple(), endMemberGroup(), endMemberGroupHeader(), endMemberHeader(), endMemberList(), endSection(), endTitleHead(), endTypewriter(), ManGenerator(), newParagraph(), operator=(), startBold(), startBoldEmphasis(), startCompoundTemplateParams(), startConstraintList(), startDescForItem(), startDescTable(), startDescTableData(), startEmphasis(), startExamples(), startFile(), startGroupHeader(), startInlineHeader(), startItemListItem(), startMemberDescription(), startMemberDoc(), startMemberDocSimple(), startMemberHeader(), startMemberItem(), startMemberList(), startParagraph(), startTitle(), startTypewriter(), writeChar(), writeDoc(), writeInheritedSectionTitle(), and writeSynopsis().
m_inHeader
bool ManGenerator::m_inHeader = false private
Definition at line 297 of file mangen.h.
Referenced by endSection(), endTitleHead(), ManGenerator(), operator=(), and startSection().
m_insideTabbing
bool ManGenerator::m_insideTabbing = false private
Definition at line 296 of file mangen.h.
Referenced by endAnonTypeScope(), endMemberList(), ManGenerator(), operator=(), startAnonTypeScope(), startMemberItem(), and startMemberList().
m_paragraph
bool ManGenerator::m_paragraph = true private
Definition at line 294 of file mangen.h.
Referenced by docify(), endGroupHeader(), endMemberHeader(), endSection(), endTitleHead(), ManGenerator(), newParagraph(), operator=(), startCompoundTemplateParams(), startConstraintList(), startDescForItem(), startDescTable(), startExamples(), startItemListItem(), startMemberDoc(), startParagraph(), startTitle(), writeChar(), writeDoc(), and writeSynopsis().
m_upperCase
bool ManGenerator::m_upperCase = false private
Definition at line 295 of file mangen.h.
Referenced by endGroupHeader(), ManGenerator(), operator=(), and startGroupHeader().
The documentation for this class was generated from the following files:
src/mangen.h
src/mangen.cpp