Doxygen: src/dot.cpp File Reference
dot.cpp File Reference
#include <cstdlib>
#include <cassert>
#include <sstream>
#include <algorithm>
#include <mutex>
#include "config.h"
#include "dot.h"
#include "dotrunner.h"
#include "dotfilepatcher.h"
#include "util.h"
#include "portable.h"
#include "message.h"
#include "doxygen.h"
#include "language.h"
#include "indexlist.h"
#include "dir.h"
Macros
#define MAP_CMD "cmapx"
Functions
static void setDotFontPath (const QCString &path)
static void unsetDotFontPath ()
void writeDotGraphFromFile (const QCString &inFile, const QCString &outDir, const QCString &outFile, GraphOutputFormat format, const QCString &srcFile, int srcLine)
void writeDotImageMapFromFile (TextStream &t, const QCString &inFile, const QCString &outDir, const QCString &relPath, const QCString &baseName, const QCString &context, int graphId, const QCString &srcFile, int srcLine)
Variables
static QCString g_dotFontPath
static std::mutex g_dotManagerMutex
Macro Definition Documentation
MAP_CMD
#define MAP_CMD "cmapx"
Definition at line 34 of file dot.cpp.
Referenced by DotGraph::prepareDotFile(), and writeDotImageMapFromFile().
Function Documentation
setDotFontPath()
static void setDotFontPath (const QCString & path) static
Definition at line 42 of file dot.cpp.
{
  ASSERT(g_dotFontPath.isEmpty());
  g_dotFontPath = Portable::getenv("DOTFONTPATH");
  QCString newFontPath = Config_getString(DOT_FONTPATH);
  if (!newFontPath.isEmpty() && !path.isEmpty())
  {
    newFontPath.prepend(path+Portable::pathListSeparator());
  }
  else if (newFontPath.isEmpty() && !path.isEmpty())
  {
    newFontPath=path;
  }
  else
  {
    Portable::unsetenv("DOTFONTPATH");
    return;
  }
  Portable::setenv("DOTFONTPATH",newFontPath);
}
References ASSERT, Config_getString, g_dotFontPath, Portable::getenv(), QCString::isEmpty(), Portable::pathListSeparator(), QCString::prepend(), Portable::setenv(), and Portable::unsetenv().
Referenced by DotManager::run().
unsetDotFontPath()
static void unsetDotFontPath () static
Definition at line 63 of file dot.cpp.
{
  if (g_dotFontPath.isEmpty())
  {
    Portable::unsetenv("DOTFONTPATH");
  }
  else
  {
    Portable::setenv("DOTFONTPATH",g_dotFontPath);
  }
  g_dotFontPath="";
}
References g_dotFontPath, Portable::setenv(), and Portable::unsetenv().
Referenced by DotManager::run().
writeDotGraphFromFile()
void writeDotGraphFromFile (const QCString & inFile, const QCString & outDir, const QCString & outFile, GraphOutputFormat format, const QCString & srcFile, int srcLine)
Definition at line 230 of file dot.cpp.
{
  Dir d(outDir.str());
  if (!d.exists())
  {
    term("Output dir %s does not exist!\n",qPrint(outDir));
  }
  QCString imgExt = getDotImageExtension();
  QCString imgName = QCString(outFile)+"."+imgExt;
  QCString absImgName = QCString(d.absPath())+"/"+imgName;
  QCString absOutFile = QCString(d.absPath())+"/"+outFile;
  DotRunner dotRun(inFile);
  if (format==GraphOutputFormat::BITMAP)
  {
    dotRun.addJob(Config_getEnumAsString(DOT_IMAGE_FORMAT),absImgName,srcFile,srcLine);
  }
  else // format==GraphOutputFormat::EPS
  {
    if (Config_getBool(USE_PDFLATEX))
    {
      dotRun.addJob("pdf",absOutFile+".pdf",srcFile,srcLine);
    }
    else
    {
      dotRun.addJob("ps",absOutFile+".eps",srcFile,srcLine);
    }
  }
  dotRun.preventCleanUp();
  if (!dotRun.run())
  {
     return;
  }
  Doxygen::indexList->addImageFile(imgName);
}
References Dir::absPath(), DotRunner::addJob(), BITMAP, Config_getBool, Config_getEnumAsString, Dir::exists(), getDotImageExtension(), Doxygen::indexList, DotRunner::preventCleanUp(), qPrint(), DotRunner::run(), QCString::str(), and term.
Referenced by DocbookDocVisitor::startDotFile(), LatexDocVisitor::startDotFile(), DocbookDocVisitor::writeDotFile(), HtmlDocVisitor::writeDotFile(), and RTFDocVisitor::writeDotFile().
writeDotImageMapFromFile()
void writeDotImageMapFromFile (TextStream & t, const QCString & inFile, const QCString & outDir, const QCString & relPath, const QCString & baseName, const QCString & context, int graphId, const QCString & srcFile, int srcLine)
Writes user defined image map to the output.
Parameters
t text stream to write to
inFile just the basename part of the filename
outDir output directory
relPath relative path the to root of the output dir
baseName the base name of the output files
context the scope in which this graph is found (for resolving links)
graphId a unique id for this graph, use for dynamic sections
srcFile the source file
srcLine the line number in the source file
Definition at line 283 of file dot.cpp.
{
  Dir d(outDir.str());
  if (!d.exists())
  {
    term("Output dir %s does not exist!\n",qPrint(outDir));
  }
  QCString mapName = baseName+".map";
  QCString imgExt = getDotImageExtension();
  QCString imgName = baseName+"."+imgExt;
  QCString absOutFile = QCString(d.absPath())+"/"+mapName;
  DotRunner dotRun(inFile);
  dotRun.addJob(MAP_CMD,absOutFile,srcFile,srcLine);
  dotRun.preventCleanUp();
  if (!dotRun.run())
  {
    return;
  }
  if (imgExt=="svg") // vector graphics
  {
    QCString svgName = outDir+"/"+baseName+".svg";
    DotFilePatcher::writeSVGFigureLink(t,relPath,baseName,svgName);
    DotFilePatcher patcher(svgName);
    patcher.addSVGConversion("",TRUE,context,TRUE,graphId);
    patcher.run();
  }
  else // bitmap graphics
  {
    TextStream tt;
    t << "<img src=\"" << relPath << imgName << "\" alt=\""
      << imgName << "\" border=\"0\" usemap=\"#" << mapName << "\"/>\n";
    DotFilePatcher::convertMapFile(tt, absOutFile, relPath ,TRUE, context);
    if (!tt.empty())
    {
      t << "<map name=\"" << mapName << "\" id=\"" << mapName << "\">";
      t << tt.str();
      t << "</map>\n";
    }
  }
  d.remove(absOutFile.str());
}
References Dir::absPath(), DotRunner::addJob(), DotFilePatcher::addSVGConversion(), DotFilePatcher::convertMapFile(), TextStream::empty(), Dir::exists(), getDotImageExtension(), MAP_CMD, DotRunner::preventCleanUp(), qPrint(), Dir::remove(), DotFilePatcher::run(), DotRunner::run(), QCString::str(), TextStream::str(), term, TRUE, and DotFilePatcher::writeSVGFigureLink().
Referenced by HtmlDocVisitor::writeDotFile().
Variable Documentation
g_dotFontPath
QCString g_dotFontPath static
Definition at line 38 of file dot.cpp.
Referenced by setDotFontPath(), and unsetDotFontPath().
g_dotManagerMutex
std::mutex g_dotManagerMutex static
Definition at line 40 of file dot.cpp.
Referenced by DotManager::createFilePatcher(), and DotManager::createRunner().