Doxygen: /home/runner/work/doxygen/doxygen/src/qcstring.cpp File Reference
qcstring.cpp File Reference
#include "qcstring.h"
#include <limits.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <ctype.h>
Functions
char toLowerChar (char c)
static bool ok_in_base (char c, int base)
void * qmemmove (void *dst, const void *src, size_t len)
char * qstrdup (const char *str)
Returns a copy of a string s.
void qstrfree (const char *str)
Frees the memory allocated using qstrdup().
char * qstrncpy (char *dst, const char *src, size_t len)
int qstricmp (const char *s1, const char *s2)
int qstrnicmp (const char *s1, const char *s2, size_t len)
QCString substitute (const QCString &s, const QCString &src, const QCString &dst)
substitute all occurrences of src in s by dst
QCString substitute (const QCString &s, const QCString &src, const QCString &dst, int skip_seq)
substitute all occurrences of src in s by dst, but skip each consecutive sequence of src where the number consecutive src matches skip_seq; if skip_seq is negative, skip any number of consecutive src
Function Documentation
ok_in_base()
static bool ok_in_base (char c, int base) static
Definition at line 219 of file qcstring.cpp.
{
    if ( base <= 10 )
        return c>='0' && c<='9' && (c-'0') < base;
    else
        return (c>='0' && c<='9') ||
               (c >= 'a' && c < char('a'+base-10)) ||
               (c >= 'A' && c < char('A'+base-10));
}
Referenced by QCString::toLong(), QCString::toUInt64(), and QCString::toULong().
qmemmove()
void * qmemmove (void * dst, const void * src, size_t len)
Definition at line 402 of file qcstring.cpp.
{
  char *d;
  const char *s;
  if ( dst > src ) {
    d = static_cast<char *>(dst) + len - 1;
    s = static_cast<const char *>(src) + len - 1;
    while ( len-- )
      *d-- = *s--;
  }
  else if ( dst < src ) {
    d = static_cast<char *>(dst);
    s = static_cast<const char *>(src);
    while ( len-- )
      *d++ = *s++;
  }
  return dst;
}
Referenced by BufStr::dropFromStart().
qstrdup()
char * qstrdup (const char * s)
Returns a copy of a string s.
Note that memory is passed to the caller, use qstrfree() to release.
Definition at line 421 of file qcstring.cpp.
{
  if ( !str )
    return 0;
  char *dst = new char[qstrlen(str)+1];
  return strcpy( dst, str );
}
References qstrlen().
qstrfree()
void qstrfree (const char * str)
Frees the memory allocated using qstrdup().
Definition at line 429 of file qcstring.cpp.
{
  delete[](str);
}
qstricmp()
int qstricmp (const char * s1, const char * s2)
Definition at line 444 of file qcstring.cpp.
{
  if ( !s1 || !s2 )
  {
    return s1 == s2 ? 0 : static_cast<int>(s2 - s1);
  }
  int res;
  char c;
  for ( ; !(res = ((c=toLowerChar(*s1)) - toLowerChar(*s2))); s1++, s2++ )
  {
    if ( !c ) // strings are equal
      break;
  }
  return res;
}
References toLowerChar().
Referenced by buildDirectories(), compareDirDefs(), compareFileDefs(), compareString(), VhdlDocGen::findAllArchitectures(), DocGroup::findExistingGroup(), FlowChart::findLabel(), VhdlDocGen::findVhdlClass(), genericCompareMembers(), mainPageHasOwnTitle(), DirDefImpl::matchPath(), parseInput(), qstricmp(), qstricmp(), qstricmp(), readConfiguration(), searchInputFiles(), FileDefImpl::sortMemberLists(), GroupDefImpl::sortMemberLists(), NamespaceDefImpl::sortMemberLists(), stripFromPath(), transcodeCharacterBuffer(), transcodeCharacterStringToUTF8(), writeColumn(), FlowChart::writeFlowLinks(), ClassDefImpl::writeIncludeFilesForSlice(), writeIndex(), and VhdlDocGen::writeProcedureProto().
qstrncpy()
char * qstrncpy (char * dst, const char * src, size_t len)
Definition at line 434 of file qcstring.cpp.
{
  if ( !src )
    return nullptr;
  strncpy( dst, src, len );
  if ( len > 0 )
    dst[len-1] = '\0';
  return dst;
}
Referenced by do_warn().
qstrnicmp()
int qstrnicmp (const char * s1, const char * s2, size_t len)
Definition at line 460 of file qcstring.cpp.
{
  if ( !s1 || !s2 )
  {
    return static_cast<int>(s2 - s1);
  }
  for ( ; len--; s1++, s2++ )
  {
    char c = toLowerChar(*s1);
    int res = c-toLowerChar(*s2);
    if ( res!=0 ) // strings are not equal
      return res;
    if ( c==0 ) // strings are equal
      break;
  }
  return 0;
}
References toLowerChar().
Referenced by QCString::contains(), QCString::find(), QCString::findRev(), qstrnicmp(), qstrnicmp(), and qstrnicmp().
substitute() [1/2]
QCString substitute (const QCString & s, const QCString & src, const QCString & dst)
substitute all occurrences of src in s by dst
Definition at line 479 of file qcstring.cpp.
{
  if (s.isEmpty() || src.isEmpty()) return s;
  const char *p, *q;
  int srcLen = src.length();
  int dstLen = dst.length();
  int resLen;
  if (srcLen!=dstLen)
  {
    int count;
    for (count=0, p=s.data(); (q=strstr(p,src.data()))!=0; p=q+srcLen) count++;
    resLen = s.length()+count*(dstLen-srcLen);
  }
  else // result has same size as s
  {
    resLen = s.length();
  }
  QCString result(resLen+1);
  char *r;
  for (r=result.rawData(), p=s.data(); (q=strstr(p,src.data()))!=0; p=q+srcLen)
  {
    int l = static_cast<int>(q-p);
    memcpy(r,p,l);
    r+=l;
    if (dstLen>0) memcpy(r,dst.data(),dstLen);
    r+=dstLen;
  }
  if (r)
  {
    qstrcpy(r,p);
  }
  //printf("substitute(%s,%s,%s)->%s\n",s,src,dst,result.data());
  return result;
}
References QCString::data(), QCString::isEmpty(), QCString::length(), qstrcpy(), and QCString::rawData().
Referenced by abbreviate(), addEnumValuesToEnums(), FlowChart::addFlowChart(), addFrom(), addMemberFunction(), addModule(), addPageToContext(), Markdown::addStrEscapeUtf8Nbsp(), addVariable(), addVariableToClass(), FilterNoWrap::apply(), buildListOfUsingDecls(), buildNamespaceList(), DocParser::checkUnOrMultipleDocumentedParams(), convertFileId2Var(), ResourceMgr::copyResourceAs(), Portable::correct_path(), MemberDefImpl::displayDefinition(), field2URL(), findDirDocumentation(), DocParser::findDocsForMemberOrCompound(), findGlobalMember(), findGroupScope(), findMember(), findUsingDeclarations(), findUsingDirectives(), fixSpaces(), format_warn(), generateClassOrGlobalLink(), generateClassOrGlobalLink(), RefList::generatePage(), FTVHelp::generateTreeViewScripts(), VhdlDocGen::getClassName(), getDefsOld(), DocPara::handleStartCode(), InheritedMemberInfoContext::Private::id(), linkToText(), makeDisplayName(), makeDisplayName(), matchExcludedSymbols(), Markdown::process(), Markdown::processLink(), processTagLessClasses(), replaceAliasArguments(), resolveRef(), DotFilePatcher::run(), SearchIndex::setCurrentDoc(), substitute(), substituteHtmlKeywords(), substituteLatexKeywords(), Portable::system(), ConfigImpl::takeStartComment(), ConfigImpl::takeStoreRepl(), ConfigImpl::takeUserComment(), unescapeCRef(), warn_line(), writeAlphabeticalClassList(), writeColumn(), MemberDefImpl::writeDeclaration(), MemberList::writeDeclarations(), writeDefaultLayoutFile(), MemberDefImpl::writeDocumentation(), HtmlGenerator::writeNavigationPath(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeSearchPage(), and VhdlDocGen::writeVHDLTypeDocumentation().
substitute() [2/2]
QCString substitute (const QCString & s, const QCString & src, const QCString & dst, int skip_seq)
substitute all occurrences of src in s by dst, but skip each consecutive sequence of src where the number consecutive src matches skip_seq; if skip_seq is negative, skip any number of consecutive src
Definition at line 520 of file qcstring.cpp.
{
  if (s.isEmpty() || src.isEmpty()) return s;
  const char *p, *q;
  int srcLen = src.length();
  int dstLen = dst.length();
  int resLen;
  if (srcLen!=dstLen)
  {
    int count;
    for (count=0, p=s.data(); (q=strstr(p,src.data()))!=0; p=q+srcLen) count++;
    resLen = s.length()+count*(dstLen-srcLen);
  }
  else // result has same size as s
  {
    resLen = s.length();
  }
  QCString result(resLen+1);
  char *r;
  for (r=result.rawData(), p=s.data(); (q=strstr(p,src.data()))!=0; p=q+srcLen)
  {
    // search a consecutive sequence of src
    int seq = 0, skip = 0;
    if (skip_seq)
    {
      for (const char *n=q+srcLen; qstrncmp(n,src.data(),srcLen)==0; seq=1+skip, n+=srcLen)
        ++skip; // number of consecutive src after the current one
      // verify the allowed number of consecutive src to skip
      if (skip_seq > 0 && skip_seq != seq)
        seq = skip = 0;
    }
    // skip a consecutive sequence of src when necessary
    int l = static_cast<int>((q + seq * srcLen)-p);
    memcpy(r,p,l);
    r+=l;
    if (skip)
    {
      // skip only the consecutive src found after the current one
      q += skip * srcLen;
      // the next loop will skip the current src, aka (p=q+srcLen)
      continue;
    }
    if (dstLen>0) memcpy(r,dst.data(),dstLen);
    r+=dstLen;
  }
  qstrcpy(r,p);
  result.resize(static_cast<int>(strlen(result.data())+1));
  //printf("substitute(%s,%s,%s)->%s\n",s,src,dst,result.data());
  return result;
}
References QCString::data(), QCString::isEmpty(), QCString::length(), qstrcpy(), qstrncmp(), QCString::rawData(), and QCString::resize().
toLowerChar()
char toLowerChar (char c) inline
Definition at line 24 of file qcstring.cpp.
{
  return c>='A' && c<='Z' ? c|0x20 : c;
}
Referenced by QCString::contains(), QCString::find(), QCString::findRev(), qstricmp(), and qstrnicmp().