Doxygen: SearchIndexExternal Class Reference
SearchIndexExternal Class Reference
Writes search index that should be used with an externally provided search engine, e.g.
#include <src/searchindex.h>
Classes
struct SearchDocEntry
Public Member Functions
SearchIndexExternal ()
void setCurrentDoc (const Definition *ctx, const QCString &anchor, bool isSourceFile)
void addWord (const QCString &word, bool hiPriority)
void write (const QCString &file)
Private Attributes
std::map< std::string, SearchDocEntry > m_docEntries
SearchDocEntry * m_current = nullptr
Detailed Description
Writes search index that should be used with an externally provided search engine, e.g.
doxyindexer and doxysearch.cgi.
Definition at line 113 of file searchindex.h.
Constructor & Destructor Documentation
SearchIndexExternal()
SearchIndexExternal::SearchIndexExternal ()
Definition at line 387 of file searchindex.cpp.
{
}
Member Function Documentation
addWord()
void SearchIndexExternal::addWord (const QCString & word, bool hiPriority)
Definition at line 493 of file searchindex.cpp.
{
  std::lock_guard<std::mutex> lock(g_searchIndexMutex);
  if (word.isEmpty() || !isId(word[0]) || m_current==nullptr) return;
  GrowBuf *pText = hiPriority ? &m_current->importantText : &m_current->normalText;
  if (pText->getPos()>0) pText->addChar(' ');
  pText->addStr(word);
  //printf("addWord %s\n",word);
}
References GrowBuf::addChar(), GrowBuf::addStr(), g_searchIndexMutex, GrowBuf::getPos(), isId(), and word.
setCurrentDoc()
void SearchIndexExternal::setCurrentDoc (const Definition * ctx, const QCString & anchor, bool isSourceFile)
Definition at line 450 of file searchindex.cpp.
{
  std::lock_guard<std::mutex> lock(g_searchIndexMutex);
  QCString extId = stripPath(Config_getString(EXTERNAL_SEARCH_ID));
  QCString url = isSourceFile ? (toFileDef(ctx))->getSourceFileBase() : ctx->getOutputFileBase();
  addHtmlExtensionIfMissing(url);
  if (!anchor.isEmpty()) url+=QCString("#")+anchor;
  QCString key = extId+";"+url;
  auto it = m_docEntries.find(key.str());
  if (it == m_docEntries.end())
  {
    SearchDocEntry e;
    e.type = isSourceFile ? QCString("source") : definitionToName(ctx);
    e.name = ctx->qualifiedName();
    if (ctx->definitionType()==Definition::TypeMember)
    {
      e.args = (toMemberDef(ctx))->argsString();
    }
    else if (ctx->definitionType()==Definition::TypeGroup)
    {
      const GroupDef *gd = toGroupDef(ctx);
      if (!gd->groupTitle().isEmpty())
      {
        e.name = filterTitle(gd->groupTitle());
      }
    }
    else if (ctx->definitionType()==Definition::TypePage)
    {
      const PageDef *pd = toPageDef(ctx);
      if (pd->hasTitle())
      {
        e.name = filterTitle(pd->title());
      }
    }
    e.extId = extId;
    e.url  = url;
    it = m_docEntries.emplace(key.str(),e).first;
    //printf("searchIndexExt %s : %s\n",qPrint(e->name),qPrint(e->url));
  }
  m_current = &it->second;
}
References addHtmlExtensionIfMissing(), SearchIndexExternal::SearchDocEntry::args, Config_getString, definitionToName(), Definition::definitionType(), SearchIndexExternal::SearchDocEntry::extId, filterTitle(), QCString::find(), g_searchIndexMutex, Definition::getOutputFileBase(), GroupDef::groupTitle(), PageDef::hasTitle(), QCString::isEmpty(), SearchIndexExternal::SearchDocEntry::name, Definition::qualifiedName(), QCString::str(), stripPath(), PageDef::title(), toFileDef(), toGroupDef(), toMemberDef(), toPageDef(), SearchIndexExternal::SearchDocEntry::type, Definition::TypeGroup, Definition::TypeMember, Definition::TypePage, and SearchIndexExternal::SearchDocEntry::url.
write()
void SearchIndexExternal::write (const QCString & file)
Definition at line 503 of file searchindex.cpp.
{
  std::ofstream t = Portable::openOutputStream(fileName);
  if (t.is_open())
  {
    t << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
    t << "<add>\n";
    for (auto &[name,doc] : m_docEntries)
    {
      doc.normalText.addChar(0);    // make sure buffer ends with a 0 terminator
      doc.importantText.addChar(0); // make sure buffer ends with a 0 terminator
      t << "  <doc>\n";
      t << "    <field name=\"type\">"     << doc.type << "</field>\n";
      t << "    <field name=\"name\">"     << convertToXML(doc.name) << "</field>\n";
      if (!doc.args.isEmpty())
      {
        t << "    <field name=\"args\">"     << convertToXML(doc.args) << "</field>\n";
      }
      if (!doc.extId.isEmpty())
      {
        t << "    <field name=\"tag\">"      << convertToXML(doc.extId)  << "</field>\n";
      }
      t << "    <field name=\"url\">"      << convertToXML(doc.url)  << "</field>\n";
      t << "    <field name=\"keywords\">" << convertToXML(doc.importantText.get())  << "</field>\n";
      t << "    <field name=\"text\">"     << convertToXML(doc.normalText.get())     << "</field>\n";
      t << "  </doc>\n";
    }
    t << "</add>\n";
  }
  else
  {
    err("Failed to open file %s for writing!\n",qPrint(fileName));
  }
}
References convertToXML(), err, Portable::openOutputStream(), and qPrint().
Member Data Documentation
m_current
SearchDocEntry* SearchIndexExternal::m_current = nullptr private
Definition at line 133 of file searchindex.h.
m_docEntries
std::map<std::string,SearchDocEntry> SearchIndexExternal::m_docEntries private
Definition at line 132 of file searchindex.h.
The documentation for this class was generated from the following files:
src/searchindex.h
src/searchindex.cpp