Doxygen: TranslatorLatvian Class Reference
TranslatorLatvian Class Reference
#include <src/translator_lv.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) override methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include "translator.h" or "translator_adapter.h" here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 51 of file translator_lv.h.
Member Function Documentation
getLanguageString()
QCString TranslatorLatvian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 87 of file translator_lv.h.
    {
      return "0x426 Latvian";
    }
idLanguage()
QCString TranslatorLatvian::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 63 of file translator_lv.h.
    { return "latvian"; }
latexLanguageSupportCommand()
QCString TranslatorLatvian::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 77 of file translator_lv.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[latvian]{babel}\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorLatvian::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1877 of file translator_lv.h.
    { return "Papildus mantotie elementi"; }
trAll()
QCString TranslatorLatvian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1389 of file translator_lv.h.
    {
      return "Visi";
    }
trAndMore()
QCString TranslatorLatvian::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1853 of file translator_lv.h.
    { return "un vl "+number+"..."; }
trAttention()
QCString TranslatorLatvian::trAttention () inline override virtual
Implements Translator.
Definition at line 966 of file translator_lv.h.
    {
      return "Uzmanbu";
    }
trAuthor()
QCString TranslatorLatvian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1262 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "autor", "i", "s");
    }
References Translator::createNoun().
trBug()
QCString TranslatorLatvian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1134 of file translator_lv.h.
    {
      return "Kda";
    }
trBugList()
QCString TranslatorLatvian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1139 of file translator_lv.h.
    {
      return "Kdu saraksts";
    }
trCallerGraph()
QCString TranslatorLatvian::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1508 of file translator_lv.h.
    {
      return "eit ir s funkcijas izsaukuma grafs:";
    }
trCallGraph()
QCString TranslatorLatvian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1394 of file translator_lv.h.
    {
      return "eit ir visu funkciju izsaugumu grafs:";
    }
trCiteReferences()
QCString TranslatorLatvian::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1829 of file translator_lv.h.
    { return "Bibliogrfisks atsauces"; }
trClass()
QCString TranslatorLatvian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1197 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "klase", "s");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorLatvian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 521 of file translator_lv.h.
    {
      return "Mantojambas diagramma klasei "+clName+":";
    }
trClassDocumentation()
QCString TranslatorLatvian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 402 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras dokomentcija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klases dokumentcija";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorLatvian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1097 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras";
      }
      else
      {
        return "Klases";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorLatvian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 186 of file translator_lv.h.
    { return "Klau hierarhija"; }
trClassHierarchyDescription()
QCString TranslatorLatvian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 245 of file translator_lv.h.
    { return "is mantojambas saraksts ir sakrtots aptuveni, "
             "bet ne pilnb, alfabta secb:";
    }
trClassMethods()
QCString TranslatorLatvian::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1915 of file translator_lv.h.
    {
      return "Klases metodes";
    }
trCode()
QCString TranslatorLatvian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 866 of file translator_lv.h.
    {
      return "pirmkods";
    }
trCollaborationDiagram()
QCString TranslatorLatvian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 821 of file translator_lv.h.
    {
      return "Sadarbbas diagramma klasei "+clName+":";
    }
trCompoundIndex()
QCString TranslatorLatvian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 375 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktru indess";
      }
      else
      {
        return "Klau indekss";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorLatvian::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1563 of file translator_lv.h.
    { return "Datu tipu indekss"; }
trCompoundList()
QCString TranslatorLatvian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 190 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras";
      }
      else
      {
        return "Klau saraksts";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorLatvian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 260 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "eit ir visas datu struktras ar su aprakstu:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "eit ir visas klases ar su aprakstu:";
      }
      else
      {
        return "eit ir visas klases, struktras, "
               "apvienojumi un interfeisi ar su aprakstu:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorLatvian::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1536 of file translator_lv.h.
    { return "eit ir visu datu tipu saraksts ar su aprakstu:"; }
trCompoundListFortran()
QCString TranslatorLatvian::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1528 of file translator_lv.h.
    { return "Datu tipu saraksts"; }
trCompoundMembers()
QCString TranslatorLatvian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 207 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu lauki";
      }
      else
      {
        return "Klases elementi";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorLatvian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 279 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll)
      {
        result+="dokumentto ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktru un apvienojumu lauku";
      }
      else
      {
        result+="klases elementu";
      }
      result+=" saraksts ar saitm uz ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktru/apvienojumu dokumentciju katram laukam:";
        }
        else
        {
          result+="klases dokumentciju katram elementam:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktrm/apvienojumiem, kam tie pieder:";
        }
        else
        {
          result+="klasm, kam tie pieder:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorLatvian::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1540 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll)
      {
        result+="dokumentto ";
      }
      result+="datu tipu saraksts";
      result+=" ar saitm uz ";
      if (!extractAll)
      {
         result+="datu struktras dokumentciju katram elementam:";
      }
      else
      {
         result+="datu tipiem, kam tie pieder:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorLatvian::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1532 of file translator_lv.h.
    { return "Datu lauki"; }
trCompoundReference()
QCString TranslatorLatvian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 596 of file translator_lv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" klases"; break;
        case ClassDef::Struct:     result+=" struktras"; break;
        case ClassDef::Union:      result+=" apvienojuma"; break;
        case ClassDef::Interface:  result+=" interfeisa"; break;
        case ClassDef::Protocol:   result+=" protokola"; break;
        case ClassDef::Category:   result+=" kategorijas"; break;
        case ClassDef::Exception:  result+=" izmuma"; break;
        default: break;
      }
      if (isTemplate) result+=" veidnes";
      result+=" apraksts";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorLatvian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1604 of file translator_lv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" modua"; break;
        case ClassDef::Struct:     result+=" tipa"; break;
        case ClassDef::Union:      result+=" apvienojuma"; break;
        case ClassDef::Interface:  result+=" interfeisa"; break;
        case ClassDef::Protocol:   result+=" protokola"; break;
        case ClassDef::Category:   result+=" kategorijas"; break;
        case ClassDef::Exception:  result+=" izmuma"; break;
        default: break;
      }
      if (isTemplate) result+=" sagataves";
      result+=" atsauce";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorLatvian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 497 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu struktras";
      }
      else
      {
        return "Klases";
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorLatvian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 831 of file translator_lv.h.
    {
      return "Konstruktora un destruktora dokumentcija";
    }
trCopyright()
QCString TranslatorLatvian::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1833 of file translator_lv.h.
    { return "Autortiesbas"; }
trDataTypes()
QCString TranslatorLatvian::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1587 of file translator_lv.h.
    { return "Datu tipi"; }
trDate()
QCString TranslatorLatvian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 535 of file translator_lv.h.
    { return "Datums"; }
trDateTime()
QCString TranslatorLatvian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1782 of file translator_lv.h.
    {
      static const char *days[]   = { "Pirm","Otr","Tr","Cet","Piekt","Sest","Sv" };
      static const char *months[] = { "Jan","Feb","Mar","Apr","Mai","Jn","Jl","Aug","Sept","Okt","Nov","Dec" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorLatvian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1802 of file translator_lv.h.
    {
      static const char *days_short[]   = { "pirmd.", "otrd.", "tred.", "ceturtd.", "piektd.", "sestd.", "svtd." };
      static const char *days_full[]    = { "pirmdiena", "otrdiena", "trediena", "ceturtdiena", "piektdiena", "sestdiena", "svtdiena" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorLatvian::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1818 of file translator_lv.h.
    {
      static const char *dayPeriod[] = { "priekp.", "pcp." };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorLatvian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 798 of file translator_lv.h.
    {
      return "Defints lnij @0 fail @1.";
    }
trDefinedIn()
QCString TranslatorLatvian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 174 of file translator_lv.h.
    { return "defints"; }
trDefinedInSourceFile()
QCString TranslatorLatvian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 802 of file translator_lv.h.
    {
      return "Defints fail @0.";
    }
trDefineDocumentation()
QCString TranslatorLatvian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 467 of file translator_lv.h.
    { return "Makro defincijas dokumentcija"; }
trDefines()
QCString TranslatorLatvian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 431 of file translator_lv.h.
    { return "Makro"; }
trDefineValue()
QCString TranslatorLatvian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1124 of file translator_lv.h.
    {
      return "Vrtba:";
    }
trDeprecated()
QCString TranslatorLatvian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 811 of file translator_lv.h.
    {
      return "Novecojusi";
    }
trDeprecatedList()
QCString TranslatorLatvian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1317 of file translator_lv.h.
    {
      return "Novecojuo saraksts";
    }
trDetailedDescription()
QCString TranslatorLatvian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 103 of file translator_lv.h.
    { return "Detalizts apraksts"; }
trDetailLevel()
QCString TranslatorLatvian::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1845 of file translator_lv.h.
    { return "detalizcijas lmenis"; }
trDetails()
QCString TranslatorLatvian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 107 of file translator_lv.h.
    { return "Skka informcija"; }
trDir()
QCString TranslatorLatvian::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1484 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "direktorija", "s");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorLatvian::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1837 of file translator_lv.h.
    { return QCString("Atkarbu grafs direktorijai ")+name+":"; }
trDirDocumentation()
QCString TranslatorLatvian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1466 of file translator_lv.h.
    { return "Direktorijas dokumentcija"; }
trDirectories()
QCString TranslatorLatvian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1472 of file translator_lv.h.
    { return "Direktorijas"; }
trDirIndex()
QCString TranslatorLatvian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1460 of file translator_lv.h.
    { return "Direktoriju struktra"; }
trDirReference()
QCString TranslatorLatvian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1478 of file translator_lv.h.
    { QCString result="Direktorijas "; result+=dirName; result+=" atsauce"; return result; }
trDirRelation()
QCString TranslatorLatvian::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1721 of file translator_lv.h.
    {
      return QCString(name)+" relcija";
    }
trDocumentation()
QCString TranslatorLatvian::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 357 of file translator_lv.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentcija"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorLatvian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 443 of file translator_lv.h.
    { return "Uzskaitjumi"; }
trEnumerationTypeDocumentation()
QCString TranslatorLatvian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 479 of file translator_lv.h.
    { return "Uzskaitjumlitera tipa dokumentcija"; }
trEnumerationValueDocumentation()
QCString TranslatorLatvian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1516 of file translator_lv.h.
    { return "Uzskaitjumlitera dokumentcija"; }
trEnumerationValues()
QCString TranslatorLatvian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 461 of file translator_lv.h.
    { return "Uzskaitjumliteri"; }
trEnumGeneratedFromFiles()
QCString TranslatorLatvian::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1857 of file translator_lv.h.
    { QCString result = "Dokumentcija im uzskaitjumliterlim tika enerta no sekojo";
      if (single) result+="a"; else result += "iem";
      result+=" fail";
      if (single) result+="a"; else result += "iem";
      result+=":";
      return result;
    }
trEnumName()
QCString TranslatorLatvian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 166 of file translator_lv.h.
    { return "uzskaitjuma nosaukums"; }
trEnumReference()
QCString TranslatorLatvian::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1867 of file translator_lv.h.
    { return QCString(name)+" uzskaitjumlitera atsauce"; }
trEnumValue()
QCString TranslatorLatvian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 170 of file translator_lv.h.
    { return "uzskaitjuma vrtba"; }
trEventDocumentation()
QCString TranslatorLatvian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1334 of file translator_lv.h.
    {
      return "Notikumu dokumentcija";
    }
trEvents()
QCString TranslatorLatvian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1329 of file translator_lv.h.
    {
      return "Notikumi";
    }
trExamples()
QCString TranslatorLatvian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 237 of file translator_lv.h.
    { return "Piemri"; }
trExamplesDescription()
QCString TranslatorLatvian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 343 of file translator_lv.h.
    { return "eit ir visu piemru saraksts:"; }
trExceptions()
QCString TranslatorLatvian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 551 of file translator_lv.h.
    { return "Izmumi"; }
trExtendsClass()
QCString TranslatorLatvian::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1907 of file translator_lv.h.
    {
      return "Paplaina klasi @0.";
    }
trFile()
QCString TranslatorLatvian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1206 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "fail", "i", "s");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorLatvian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 421 of file translator_lv.h.
    { return "Faila dokumentcija"; }
trFileIn()
QCString TranslatorLatvian::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1758 of file translator_lv.h.
    {
      return "File in "+name;
    }
trFileIndex()
QCString TranslatorLatvian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 390 of file translator_lv.h.
    { return "Failu indekss"; }
trFileList()
QCString TranslatorLatvian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 203 of file translator_lv.h.
    { return "Failu saraksts"; }
trFileListDescription()
QCString TranslatorLatvian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 251 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      result+="failu saraksts ar su aprakstu:";
      return result;
    }
trFileMembers()
QCString TranslatorLatvian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 220 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globlie";
      }
      else
      {
        return "Faila elementi";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorLatvian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 321 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkciju, maingo, definciju, uzskaitjumliteru un typedefs";
      }
      else
      {
        result+="faila elementu";
      }
      result+=" saraksts ar saitm uz ";
      if (extractAll)
        result+="failiem, kam tie pieder:";
      else
        result+="dokumentciju:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorLatvian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 618 of file translator_lv.h.
    {
      QCString result=fileName;
      result+=" faila apraksts";
      return result;
    }
trFriends()
QCString TranslatorLatvian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 578 of file translator_lv.h.
    { return "Draugi"; }
trFunctionDocumentation()
QCString TranslatorLatvian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 485 of file translator_lv.h.
    { return "Funkcijas dokumentcija"; }
trFunctions()
QCString TranslatorLatvian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 449 of file translator_lv.h.
    { return "Funkcijas"; }
trGeneratedAt()
QCString TranslatorLatvian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 512 of file translator_lv.h.
    {
      QCString result="enerts "+date;
      if (!projName.isEmpty()) result+=" projektam "+projName;
      result+=" ar";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorLatvian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 158 of file translator_lv.h.
    { QCString result="Automtiski enerts izmantojot Doxygen";
      if (!s.isEmpty()) result+=" priek "+s;
      result+=" no pirmkoda.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorLatvian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 555 of file translator_lv.h.
    { return "enerts ar"; }
trGeneratedFromFiles()
QCString TranslatorLatvian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 755 of file translator_lv.h.
    { // single is true implies a single file
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class:      result+="s klases"; break;
        case ClassDef::Struct:     result+="s struktras"; break;
        case ClassDef::Union:      result+=" apvienojuma"; break;
        case ClassDef::Interface:  result+=" interfeisa"; break;
        case ClassDef::Protocol:   result+=" protokola"; break;
        case ClassDef::Category:   result+="s kategorijas"; break;
        case ClassDef::Exception:  result+=" izmuma"; break;
        default: break;
      }
      result+=" dokumentcijas tika enerta no da fail";
      if (single) result+="a:"; else result+="iem:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorLatvian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1671 of file translator_lv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentcija ";
      switch(compType)
      {
        case ClassDef::Class:      result+="im modulim"; break;
        case ClassDef::Struct:     result+="im tipam"; break;
        case ClassDef::Union:      result+="im apvienojumam"; break;
        case ClassDef::Interface:  result+="im interfeisam"; break;
        case ClassDef::Protocol:   result+="im protokolam"; break;
        case ClassDef::Category:   result+="ai kategorijai"; break;
        case ClassDef::Exception:  result+="im izmumam"; break;
        default: break;
      }
      result+=" tika enerta no fail";
      if (single) result+="a:"; else result+="iem:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorLatvian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1251 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "globl", "ie", "ais");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorLatvian::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1733 of file translator_lv.h.
    {
      return "Global Namespace";
    }
trGotoDocumentation()
QCString TranslatorLatvian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 841 of file translator_lv.h.
    {
      return "Ietu uz  faila dokumentciju.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorLatvian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 874 of file translator_lv.h.
    {
      return "Iet uz grafisku klases hierarhiju";
    }
trGotoSourceCode()
QCString TranslatorLatvian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 836 of file translator_lv.h.
    {
      return "Iet uz  faila pirmkodu.";
    }
trGotoTextualHierarchy()
QCString TranslatorLatvian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 878 of file translator_lv.h.
    {
      return "Iet uz tekstulu klases hierarhiju";
    }
trGraphicalHierarchy()
QCString TranslatorLatvian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 870 of file translator_lv.h.
    {
      return "Grafiska klases hierarhija";
    }
trGroup()
QCString TranslatorLatvian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1224 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "grupa", "s");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorLatvian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 369 of file translator_lv.h.
    { return "Hierarhijas indekss"; }
trImplementedFromList()
QCString TranslatorLatvian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1285 of file translator_lv.h.
    {
      return "steno "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorLatvian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1293 of file translator_lv.h.
    {
      return "stenots "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorLatvian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 970 of file translator_lv.h.
    {
      return "is grafs rda kuri faili tiei vai "
             "netiei iekauj o failu:";
    }
trInclDepGraph()
QCString TranslatorLatvian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 826 of file translator_lv.h.
    {
    }
trIncludesFileIn()
QCString TranslatorLatvian::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1767 of file translator_lv.h.
    {
      return "Includes file in "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorLatvian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 152 of file translator_lv.h.
    { return ", ieskaitot mantotos elementus."; }
trInheritedByList()
QCString TranslatorLatvian::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 689 of file translator_lv.h.
    {
      return "Tiek mantots "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorLatvian::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1871 of file translator_lv.h.
    { return QCString(members)+" manto no "+what; }
trInheritsList()
QCString TranslatorLatvian::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 681 of file translator_lv.h.
    {
      return "Manto no "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorLatvian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 861 of file translator_lv.h.
    {
      return "Skotnj vrtba:";
    }
trInstanceMethods()
QCString TranslatorLatvian::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1923 of file translator_lv.h.
    {
      return "Instances metodes";
    }
trInvariant()
QCString TranslatorLatvian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 856 of file translator_lv.h.
    {
      return "Invariants";
    }
trISOLang()
QCString TranslatorLatvian::trISOLang () inline override virtual
Implements Translator.
Definition at line 83 of file translator_lv.h.
    {
      return "lv";
    }
trLegend()
QCString TranslatorLatvian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1057 of file translator_lv.h.
    {
      return "leenda";
    }
trLegendDocs()
QCString TranslatorLatvian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 992 of file translator_lv.h.
    {
      return
        "This page explains how to interpret the graphs that are generated "
        "by doxygen.<p>\n"
        "Consider the following example:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "This will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A filled gray box represents the struct or class for which the "
        "graph is generated.</li>\n"
        "<li>%A box with a black border denotes a documented struct or class.</li>\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.</li>\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.</li>\n"
        "</ul>\n"
        "<p>\n"
        "The arrows have the following meaning:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.</li>\n"
        "<li>%A dark green arrow is used for protected inheritance.</li>\n"
        "<li>%A dark red arrow is used for private inheritance.</li>\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible.</li>\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labeled with "
        "the template parameters of the instance.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorLatvian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 985 of file translator_lv.h.
    {
      return "Grafika leenda";
    }
trListOfAllMembers()
QCString TranslatorLatvian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 140 of file translator_lv.h.
    { return "Visu elementu saraksts"; }
trLoading()
QCString TranslatorLatvian::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1727 of file translator_lv.h.
    {
      return "Tiek veikta ielde...";
    }
trMainPage()
QCString TranslatorLatvian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 785 of file translator_lv.h.
    { return "Skumlapa"; }
trMember()
QCString TranslatorLatvian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1242 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "element", "i", "s");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorLatvian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 123 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lauka dokumentcija";
      }
      else
      {
        return "Elementa datu dokumentcija";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorLatvian::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 115 of file translator_lv.h.
    { return "Elementa uzskaitjumlitera dokumentcija"; }
trMemberFunctionDocumentation()
QCString TranslatorLatvian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 119 of file translator_lv.h.
    { return "Elementa funkcijas dokumentcija"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorLatvian::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1524 of file translator_lv.h.
    { return "Elementa funckijas/apakrutnas dokumentcija"; }
trMemberList()
QCString TranslatorLatvian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 144 of file translator_lv.h.
    { return "Elementu saraksts"; }
trMemberTypedefDocumentation()
QCString TranslatorLatvian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 111 of file translator_lv.h.
    { return "Elementa Typedef dokumentcija"; }
trMethodDocumentation()
QCString TranslatorLatvian::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1930 of file translator_lv.h.
    {
      return "Metou dokumentcija";
    }
trModule()
QCString TranslatorLatvian::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1663 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "modu", "i", "lis");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorLatvian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 396 of file translator_lv.h.
    { return "Modua dokumentcija"; }
trModuleIndex()
QCString TranslatorLatvian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 363 of file translator_lv.h.
    { return "Moduu indekss"; }
trModuleReference()
QCString TranslatorLatvian::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1625 of file translator_lv.h.
    {
      QCString result=namespaceName;
      result+=" moduu atsauce";
      return result;
    }
trModules()
QCString TranslatorLatvian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 182 of file translator_lv.h.
    { return "Modui"; }
trModulesDescription()
QCString TranslatorLatvian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 351 of file translator_lv.h.
    { return "eit ir visu moduu saraksts:"; }
trModulesIndex()
QCString TranslatorLatvian::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1656 of file translator_lv.h.
    { return "Moduu indekss"; }
trModulesList()
QCString TranslatorLatvian::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1591 of file translator_lv.h.
    { return "Moduu saraksts"; }
trModulesListDescription()
QCString TranslatorLatvian::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1595 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      result+="moduu saraksts ar su aprakstu:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorLatvian::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1637 of file translator_lv.h.
    {
      QCString result="eit ir visu ";
      if (!extractAll) result+="dokumentto ";
      result+="modua elementu saraksts ar saitm uz ";
      if (extractAll)
      {
        result+="modua dokumentciju katram elementam:";
      }
      else
      {
        result+="moduiem, kuriem tie pieder:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorLatvian::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1633 of file translator_lv.h.
    { return "Modua elementi"; }
trMonth()
QCString TranslatorLatvian::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1810 of file translator_lv.h.
    {
      static const char *months_short[] = { "janv.", "febr.", "marts", "apr.", "maijs", "jn.", "jl.", "aug.", "sept.", "okt.", "nov.", "dec." };
      static const char *months_full[]  = { "janvris", "februris", "marts", "aprlis", "maijs", "jnijs", "jlijs", "augusts", "septembris", "oktobris", "novembris", "decembris" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorLatvian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 136 of file translator_lv.h.
    { return "vairk..."; }
trNamespace()
QCString TranslatorLatvian::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1215 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "nosaukumvieta", "s");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorLatvian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 735 of file translator_lv.h.
    { return "Nosaukumvietas dokumentcija"; }
trNamespaceIndex()
QCString TranslatorLatvian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 729 of file translator_lv.h.
    { return "Nosaukumvietu indekss"; }
trNamespaceList()
QCString TranslatorLatvian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 563 of file translator_lv.h.
    { return "Nosaukumvietu saraksts"; }
trNamespaceListDescription()
QCString TranslatorLatvian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 567 of file translator_lv.h.
    {
      QCString result="eit ir visas ";
      if (!extractAll) result+="dokumentts ";
      result+="nosaukumvietas ar su aprakstu:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorLatvian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 715 of file translator_lv.h.
    {
      QCString result="eit ir visi ";
      if (!extractAll) result+="dokumenttie ";
      result+="nosaukumvietas elementi ar saitm uz ";
      if (extractAll)
        result+="nosaukumvieta dokumentciju katram elementam:";
      else
        result+="nosaukumvietu, kam tie pieder:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorLatvian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 711 of file translator_lv.h.
    { return "Nosaukumvietas elementi"; }
trNamespaceReference()
QCString TranslatorLatvian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 626 of file translator_lv.h.
    {
      QCString result=namespaceName;
      result+=" nosaukumvietas apraksts";
      return result;
    }
trNamespaces()
QCString TranslatorLatvian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 745 of file translator_lv.h.
    { return "Nosaukumvietas"; }
trNoMatches()
QCString TranslatorLatvian::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1745 of file translator_lv.h.
    {
      return "Nav atbilstbu";
    }
trNote()
QCString TranslatorLatvian::trNote () inline override virtual
Implements Translator.
Definition at line 891 of file translator_lv.h.
    {
      return "Piezme";
    }
trOverloadText()
QCString TranslatorLatvian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1496 of file translator_lv.h.
    {
       return " ir elementa prslogota funkcija, kas "
              "pardta tikai informtvo nolkos. T atiras no iepriekapraksts "
              "funkcijas tikai ar parametriem, ko t saem.";
    }
trPackage()
QCString TranslatorLatvian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1109 of file translator_lv.h.
    {
      return "Pakotne "+name;
    }
trPackageAttribs()
QCString TranslatorLatvian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1370 of file translator_lv.h.
    {
      return "Pakas atribti";
    }
trPackageFunctions()
QCString TranslatorLatvian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1352 of file translator_lv.h.
    {
      return "Pakas funkcijas";
    }
trPackageListDescription()
QCString TranslatorLatvian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1114 of file translator_lv.h.
    {
      return "Here are the packages with brief descriptions (if available):";
    }
trPackageMembers()
QCString TranslatorLatvian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1356 of file translator_lv.h.
    {
      return "Pakas elementi";
    }
trPackages()
QCString TranslatorLatvian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1119 of file translator_lv.h.
    {
      return "Pakotnes";
    }
trPackageTypes()
QCString TranslatorLatvian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1345 of file translator_lv.h.
    {
      return "Pakas tipi";
    }
trPage()
QCString TranslatorLatvian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1233 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "lapa", "s");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorLatvian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 791 of file translator_lv.h.
    { return "lpp."; }
trPageIndex()
QCString TranslatorLatvian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 882 of file translator_lv.h.
    {
      return "Lapas indekss";
    }
trPanelSynchronisationTooltip()
QCString TranslatorLatvian::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1888 of file translator_lv.h.
    {
      QCString opt = enable ? "iespjotu" : "atspjotu";
      return "uzklikint, lai "+opt+" paneu sinhronizciju";
    }
trParameters()
QCString TranslatorLatvian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 547 of file translator_lv.h.
    { return "Parametri"; }
trPostcondition()
QCString TranslatorLatvian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 851 of file translator_lv.h.
    {
      return "Pcnosacjums";
    }
trPrecondition()
QCString TranslatorLatvian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 846 of file translator_lv.h.
    {
      return "Pirmsnosacjums";
    }
trPrivateAttribs()
QCString TranslatorLatvian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 930 of file translator_lv.h.
    {
      return "Privtie atribti";
    }
trPrivateMembers()
QCString TranslatorLatvian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 647 of file translator_lv.h.
    { return "Privts elementa funkcijas"; }
trPrivateSlots()
QCString TranslatorLatvian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 649 of file translator_lv.h.
    { return "Privts spraugas"; }
trPrivateTypes()
QCString TranslatorLatvian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 926 of file translator_lv.h.
    {
      return "Privtie tipi";
    }
trProperties()
QCString TranslatorLatvian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1082 of file translator_lv.h.
    {
      return "Rekvizti";
    }
trPropertyDocumentation()
QCString TranslatorLatvian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1087 of file translator_lv.h.
    {
      return "Rekviztu dokumentcija";
    }
trProtectedAttribs()
QCString TranslatorLatvian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 918 of file translator_lv.h.
    {
      return "Aizsargtie atribti";
    }
trProtectedMembers()
QCString TranslatorLatvian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 641 of file translator_lv.h.
    { return "Aizsargts elementa funkcijas"; }
trProtectedSlots()
QCString TranslatorLatvian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 643 of file translator_lv.h.
    { return "Aizsargts spraugas"; }
trProtectedTypes()
QCString TranslatorLatvian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 914 of file translator_lv.h.
    {
      return "Aizsargtie tipi";
    }
trProvidedByCategory()
QCString TranslatorLatvian::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1898 of file translator_lv.h.
    {
      return "Nodroina kategorija @0.";
    }
trPublicAttribs()
QCString TranslatorLatvian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 899 of file translator_lv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datu lauki";
      }
      else
      {
        return "Publiskie atribti";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorLatvian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 633 of file translator_lv.h.
    { return "Publisks elementa funkcijas"; }
trPublicSlots()
QCString TranslatorLatvian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 635 of file translator_lv.h.
    { return "Publisks spraugas"; }
trPublicTypes()
QCString TranslatorLatvian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 895 of file translator_lv.h.
    {
      return "Publiskie tipi";
    }
trReferencedBy()
QCString TranslatorLatvian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 958 of file translator_lv.h.
    {
      return "Atsauces no";
    }
trReferenceManual()
QCString TranslatorLatvian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 425 of file translator_lv.h.
    { return "Rokasgrmata"; }
trReferences()
QCString TranslatorLatvian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1273 of file translator_lv.h.
    {
      return "Atsauces";
    }
trReimplementedFromList()
QCString TranslatorLatvian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 697 of file translator_lv.h.
    {
      return "Primplementts no "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorLatvian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 705 of file translator_lv.h.
    {
      return "Primplementts "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorLatvian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 588 of file translator_lv.h.
    { return "Draugu un saistto funkciju dokumentcija"; }
trRelatedFunctions()
QCString TranslatorLatvian::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 95 of file translator_lv.h.
    { return "Saistts funkcijas"; }
trRelatedPages()
QCString TranslatorLatvian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 233 of file translator_lv.h.
    { return "Saistts lapas"; }
trRelatedPagesDescription()
QCString TranslatorLatvian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 347 of file translator_lv.h.
    { return "Here is a list of all related documentation pages:"; }
trRelatedSubscript()
QCString TranslatorLatvian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 99 of file translator_lv.h.
    { return "(s nav elementu funkcijas.)"; }
trRemarks()
QCString TranslatorLatvian::trRemarks () inline override virtual
Implements Translator.
Definition at line 962 of file translator_lv.h.
    {
      return "Piebildes";
    }
trReturns()
QCString TranslatorLatvian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 539 of file translator_lv.h.
    { return "Atgrie"; }
trReturnValues()
QCString TranslatorLatvian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 780 of file translator_lv.h.
    { return "Atgrieams vrtbas"; }
trRTFansicp()
QCString TranslatorLatvian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1173 of file translator_lv.h.
    {
      return "1257";
    }
trRTFCharSet()
QCString TranslatorLatvian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1182 of file translator_lv.h.
    {
      return "186";
    }
trRTFGeneralIndex()
QCString TranslatorLatvian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1188 of file translator_lv.h.
    {
      return "Indekss";
    }
trRTFTableOfContents()
QCString TranslatorLatvian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1305 of file translator_lv.h.
    {
      return "Satura rdtjs";
    }
trSearch()
QCString TranslatorLatvian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 241 of file translator_lv.h.
    { return "Meklt"; }
trSearching()
QCString TranslatorLatvian::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1739 of file translator_lv.h.
    {
      return "Mekl...";
    }
trSearchMatches()
QCString TranslatorLatvian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1437 of file translator_lv.h.
    {
      return "Atbilst mekltajam:";
    }
trSearchResults()
QCString TranslatorLatvian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1418 of file translator_lv.h.
    {
      if (numDocuments==0)
      {
        return "Netika atrasts neviens dokuments.";
      }
      else if (numDocuments==1)
      {
        return "Atrasts <b>1</b> dokuments.";
      }
      else
      {
        return "Atrasti <b>$num</b> Dokumenti. "
               "Skum attlo tos, kas atbilst vispreczk.";
      }
    }
trSearchResultsTitle()
QCString TranslatorLatvian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1406 of file translator_lv.h.
    {
      return "Meklanas rezultti";
    }
trSeeAlso()
QCString TranslatorLatvian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 543 of file translator_lv.h.
    { return "Skatties ar"; }
trSignals()
QCString TranslatorLatvian::trSignals () inline override virtual
Implements Translator.
Definition at line 637 of file translator_lv.h.
    { return "Signli"; }
trSince()
QCString TranslatorLatvian::trSince () inline override virtual
Implements Translator.
Definition at line 975 of file translator_lv.h.
    {
      return "Kop";
    }
trSourceFile()
QCString TranslatorLatvian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1448 of file translator_lv.h.
    {
      return filename + " pirmkoda fails";
    }
trStaticPackageAttribs()
QCString TranslatorLatvian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1377 of file translator_lv.h.
    {
      return "Statiskie pakas atribti";
    }
trStaticPackageFunctions()
QCString TranslatorLatvian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1363 of file translator_lv.h.
    {
      return "Statisks pakas funkcijas";
    }
trStaticPrivateAttribs()
QCString TranslatorLatvian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 934 of file translator_lv.h.
    {
      return "Statiskie privtie atribti";
    }
trStaticPrivateMembers()
QCString TranslatorLatvian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 651 of file translator_lv.h.
    { return "Statisks privts elementa funkcijas"; }
trStaticProtectedAttribs()
QCString TranslatorLatvian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 922 of file translator_lv.h.
    {
      return "Statiskie aizsargtie atribti";
    }
trStaticProtectedMembers()
QCString TranslatorLatvian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 645 of file translator_lv.h.
    { return "Statisks aizsargts elementa funkcijas"; }
trStaticPublicAttribs()
QCString TranslatorLatvian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 910 of file translator_lv.h.
    {
      return "Statiskie publiskie atribti";
    }
trStaticPublicMembers()
QCString TranslatorLatvian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 639 of file translator_lv.h.
    { return "Statisks publisks elementa funkcijas"; }
trSubprogram()
QCString TranslatorLatvian::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1705 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "apakprogramma", "s");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorLatvian::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1581 of file translator_lv.h.
    { return "Funkcijas/Apakrutnas dokumentcija"; }
trSubprograms()
QCString TranslatorLatvian::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1575 of file translator_lv.h.
    { return "Funkcijas/Apakrutnas"; }
trTemplateParameters()
QCString TranslatorLatvian::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1849 of file translator_lv.h.
    { return "Sagataves parametri"; }
trTest()
QCString TranslatorLatvian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1067 of file translator_lv.h.
    {
      return "Testi";
    }
trTestList()
QCString TranslatorLatvian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1072 of file translator_lv.h.
    {
      return "Testu saraksts";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorLatvian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 148 of file translator_lv.h.
    { return "is ir pilns elementu saraksts klasei"; }
trTodo()
QCString TranslatorLatvian::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 944 of file translator_lv.h.
    {
      return "Jizdara";
    }
trTodoList()
QCString TranslatorLatvian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 949 of file translator_lv.h.
    {
      return "Darmo darbu saraksts";
    }
trType()
QCString TranslatorLatvian::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1696 of file translator_lv.h.
    {
      return createNoun(first_capital, singular, "tip", "i", "s");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorLatvian::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1711 of file translator_lv.h.
    {
      return "Tipa ierobeojumi";
    }
trTypedefDocumentation()
QCString TranslatorLatvian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 473 of file translator_lv.h.
    { return "Typedef dokumentcija"; }
trTypedefs()
QCString TranslatorLatvian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 437 of file translator_lv.h.
    { return "Typedefs"; }
trTypeDocumentation()
QCString TranslatorLatvian::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1569 of file translator_lv.h.
    { return "Datu tipa dokumentcija"; }
trVariableDocumentation()
QCString TranslatorLatvian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 491 of file translator_lv.h.
    { return "Maingo dokumentcija"; }
trVariables()
QCString TranslatorLatvian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 455 of file translator_lv.h.
    { return "Maingie"; }
trVersion()
QCString TranslatorLatvian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 531 of file translator_lv.h.
    { return "Versija"; }
trWarning()
QCString TranslatorLatvian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 527 of file translator_lv.h.
    { return "Brdinjums"; }
trWriteList()
QCString TranslatorLatvian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 657 of file translator_lv.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=", un ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_lv.h