Doxygen: DocSimpleSectSep Class Reference
DocSimpleSectSep Class Reference
Node representing a separator between two simple sections of the same type.
#include <src/docnode.h>
Public Member Functions
DocSimpleSectSep (DocParser *parser, DocNodeVariant *parent)
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a separator between two simple sections of the same type.
Definition at line 1022 of file docnode.h.
Constructor & Destructor Documentation
DocSimpleSectSep()
DocSimpleSectSep::DocSimpleSectSep (DocParser * parser, DocNodeVariant * parent) inline
Definition at line 1025 of file docnode.h.
: DocNode(parser,parent) {}
References DocNode::DocNode(), DocNode::parent(), and DocNode::parser().
The documentation for this class was generated from the following file:
src/docnode.h