Doxygen: TranslatorTurkish Class Reference
TranslatorTurkish Class Reference
#include <src/translator_tr.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool, bool full) override
QCString trMonth (int month, bool, bool full) override
QCString trDayPeriod (bool period) override
Public Member Functions inherited from TranslatorAdapter_1_7_5
QCString updateNeededMessage () override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
Public Member Functions inherited from TranslatorAdapter_1_8_0
QCString updateNeededMessage () override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) override methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include "translator.h" or "translator_adapter.h" here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 43 of file translator_tr.h.
Member Function Documentation
getLanguageString()
QCString TranslatorTurkish::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 80 of file translator_tr.h.
    {
      return "0x41F Turkey";
    }
idLanguage()
QCString TranslatorTurkish::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 55 of file translator_tr.h.
    { return "turkish"; }
latexLanguageSupportCommand()
QCString TranslatorTurkish::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 72 of file translator_tr.h.
    {
      return "\\usepackage[turkish]{babel}\n";
    }
trAll()
QCString TranslatorTurkish::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1377 of file translator_tr.h.
    {
      return "Tm";
    }
trAttention()
QCString TranslatorTurkish::trAttention () inline override virtual
Implements Translator.
Definition at line 957 of file translator_tr.h.
    {
      return "Dikkat";
    }
trAuthor()
QCString TranslatorTurkish::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1250 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "yazar", "lar");
    }
References Translator::createNoun().
trBug()
QCString TranslatorTurkish::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1122 of file translator_tr.h.
    {
      return "Hata";
    }
trBugList()
QCString TranslatorTurkish::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1127 of file translator_tr.h.
    {
      return "Hata Listesi";
    }
trCallerGraph()
QCString TranslatorTurkish::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1496 of file translator_tr.h.
    {
      return "Bu fonksiyon iin arlma emas:";
    }
trCallGraph()
QCString TranslatorTurkish::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1382 of file translator_tr.h.
    {
      return "Bu fonksiyon iin arlma emas:";
    }
trClass()
QCString TranslatorTurkish::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1185 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "snf", "lar");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorTurkish::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 510 of file translator_tr.h.
    {
      return clName+" iin kaltm emas:";
    }
trClassDocumentation()
QCString TranslatorTurkish::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 391 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar Dokmantasyonu";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Snf Dokmantasyonu";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorTurkish::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1085 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar";
      }
      else
      {
        return "Snflar";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorTurkish::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 179 of file translator_tr.h.
    { return "Snf Hiyerarisi"; }
trClassHierarchyDescription()
QCString TranslatorTurkish::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 238 of file translator_tr.h.
    { return "Bu kaltm listesi tamamen olmasa da yaklak "
             "olarak alfabetik sraya konulmutur:";
    }
trCode()
QCString TranslatorTurkish::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 857 of file translator_tr.h.
    {
      return "kod";
    }
trCollaborationDiagram()
QCString TranslatorTurkish::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 812 of file translator_tr.h.
    {
      return clName+" iin ibirlii (collaboration) emas:";
    }
trCompoundIndex()
QCString TranslatorTurkish::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 364 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar ndeksi";
      }
      else
      {
        return "Snf ndeksi";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorTurkish::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1550 of file translator_tr.h.
    { return "Veri Tipi ndeksi"; }
trCompoundList()
QCString TranslatorTurkish::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 183 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar";
      }
      else
      {
        return "Snf Listesi";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorTurkish::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 253 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Ksa tanmlaryla birlikte veri yaplar:";
      }
      else
      {
        return "Ksa tanmlaryla snflar, yaplar (struct), "
               "birleimler(union) ve arayzler:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorTurkish::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1524 of file translator_tr.h.
    { return "Ksa tanmlaryla veri tipleri:"; }
trCompoundListFortran()
QCString TranslatorTurkish::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1516 of file translator_tr.h.
    { return "Veri Tipleri Listesi"; }
trCompoundMembers()
QCString TranslatorTurkish::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 200 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Alanlar";
      }
      else
      {
        return "Snf yeleri";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorTurkish::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 268 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll)
      {
        result+="dokmante edilmi ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="yap(struct) ve birleim(union) yaplarn ierir";
      }
      else
      {
        result+="snf yelerini ierir";
      }
      result+=" ve ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="her alan yap(struct)/birleim(union) dokmantasyonuna balar:";
        }
        else
        {
          result+="her ye iin snf dokmantasyonuna balar:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="ait olduu yap(struct)/birleime(union) balar:";
        }
        else
        {
          result+="ait olduu snfa balar:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorTurkish::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1528 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll)
      {
        result+="dokmante edilmi ";
      }
      result+="veri tiplerini ierir ve ";
      if (!extractAll)
      {
         result+="her yeyi veri yaps dokmantasyonuna balar:";
      }
      else
      {
         result+="ait olduklar veri tiplerine balar:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorTurkish::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1520 of file translator_tr.h.
    { return "Veri Alanlar"; }
trCompoundReference()
QCString TranslatorTurkish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 585 of file translator_tr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Snf"; break;
        case ClassDef::Struct:     result+=" Yap(Struct)"; break;
        case ClassDef::Union:      result+=" Birleim(Union)"; break;
        case ClassDef::Interface:  result+=" Arayz(Interface)"; break;
        case ClassDef::Protocol:   result+=" Protokol"; break;
        case ClassDef::Category:   result+=" Kategori"; break;
        case ClassDef::Exception:  result+=" stisna"; break;
        default: break;
      }
      if (isTemplate) result+=" ablon";
      result+=" Referans";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorTurkish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1591 of file translator_tr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Modl"; break;
        case ClassDef::Struct:     result+=" Tip"; break;
        case ClassDef::Union:      result+=" Birleim(Union)"; break;
        case ClassDef::Interface:  result+=" Arayz"; break;
        case ClassDef::Protocol:   result+=" Protokol"; break;
        case ClassDef::Category:   result+=" Kategori"; break;
        case ClassDef::Exception:  result+=" stisna"; break;
        default: break;
      }
      if (isTemplate) result+=" ablon";
      result+=" Referans";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorTurkish::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 486 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar";
      }
      else
      {
        return "Snflar";
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorTurkish::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 822 of file translator_tr.h.
    {
      return "Constructor & Destructor Dokmantasyonu";
    }
trDataTypes()
QCString TranslatorTurkish::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1574 of file translator_tr.h.
    { return "Veri Tipleri"; }
trDate()
QCString TranslatorTurkish::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 524 of file translator_tr.h.
    { return "Tarih"; }
trDateTime()
QCString TranslatorTurkish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1768 of file translator_tr.h.
    {
    static const char *days[]   = { "Pzt","Sal","ar","Per","Cma","Cmt","Pzr" };
    static const char *months[] = { "Oca","ub","Mar","Nis","May","Haz","Tem","Au","Eyl","Ekm","Kas","Ara" };
    QCString sdate;
    if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
    {
    sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
    }
    if (includeTime == DateTimeType::DateTime) sdate += " ";
    if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
    {
      QCString stime;
      stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
      sdate+=stime;
    }
    return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorTurkish::trDayOfWeek (int dayOfWeek, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1788 of file translator_tr.h.
    {
      static const char *days_short[]   = { "Pzt", "Sal", "ar", "Per", "Cum", "Cmt", "Paz" };
      static const char *days_full[]    = { "Pazartesi", "Sal", "aramba", "Perembe", "Cuma", "Cumartesi", "Pazar" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod()
QCString TranslatorTurkish::trDayPeriod (bool period) inline override virtual
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1802 of file translator_tr.h.
    {
      static const char *dayPeriod[] = { "", "S" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorTurkish::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 789 of file translator_tr.h.
    {
      return "@1 dosyasnn @0 numaral satrnda tanmlanmtr.";
    }
trDefinedIn()
QCString TranslatorTurkish::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 167 of file translator_tr.h.
    { return "tanmland yer"; }
trDefinedInSourceFile()
QCString TranslatorTurkish::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 793 of file translator_tr.h.
    {
      return "@0 dosyasnda tanmlanmtr.";
    }
trDefineDocumentation()
QCString TranslatorTurkish::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 456 of file translator_tr.h.
    { return "Makro Dokmantasyonu"; }
trDefines()
QCString TranslatorTurkish::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 420 of file translator_tr.h.
    { return "Makrolar"; }
trDefineValue()
QCString TranslatorTurkish::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1112 of file translator_tr.h.
    {
      return "Deer:";
    }
trDeprecated()
QCString TranslatorTurkish::trDeprecated () inline override virtual
Implements Translator.
Definition at line 802 of file translator_tr.h.
    {
      return "Kullanmdan kalkmtr";
    }
trDeprecatedList()
QCString TranslatorTurkish::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1305 of file translator_tr.h.
    {
      return "Kullanmdan Kalkanlar Listesl";
    }
trDetailedDescription()
QCString TranslatorTurkish::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 96 of file translator_tr.h.
    { return "Ayrntl tanmlama"; }
trDetails()
QCString TranslatorTurkish::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 100 of file translator_tr.h.
    { return "Ayrntlar"; }
trDir()
QCString TranslatorTurkish::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1472 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "dizin", "ler");
    }
References Translator::createNoun().
trDirDocumentation()
QCString TranslatorTurkish::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1454 of file translator_tr.h.
    { return "Dizin Dokmantasyonu"; }
trDirectories()
QCString TranslatorTurkish::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1460 of file translator_tr.h.
    { return "Dizinler"; }
trDirIndex()
QCString TranslatorTurkish::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1448 of file translator_tr.h.
    { return "Dizin Hiyerarisi"; }
trDirReference()
QCString TranslatorTurkish::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1466 of file translator_tr.h.
    { QCString result=dirName; result+=" Dizin Referans"; return result; }
trDirRelation()
QCString TranslatorTurkish::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1707 of file translator_tr.h.
    {
    return QCString(name)+" likisi";
    }
trDocumentation()
QCString TranslatorTurkish::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 346 of file translator_tr.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokmantasyonu"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorTurkish::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 432 of file translator_tr.h.
    { return "Enmerasyonlar"; }
trEnumerationTypeDocumentation()
QCString TranslatorTurkish::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 468 of file translator_tr.h.
    { return "Enmerasyon Tipi Dokmantasyonu"; }
trEnumerationValueDocumentation()
QCString TranslatorTurkish::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1504 of file translator_tr.h.
    { return "Enmerasyon Dokmantasyonu"; }
trEnumerationValues()
QCString TranslatorTurkish::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 450 of file translator_tr.h.
    { return "Enmeratr"; }
trEnumName()
QCString TranslatorTurkish::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 159 of file translator_tr.h.
    { return "enum ad"; }
trEnumValue()
QCString TranslatorTurkish::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 163 of file translator_tr.h.
    { return "enum deeri"; }
trEventDocumentation()
QCString TranslatorTurkish::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1322 of file translator_tr.h.
    {
      return "Olay Dokmantasyonu";
    }
trEvents()
QCString TranslatorTurkish::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1317 of file translator_tr.h.
    {
      return "Olaylar";
    }
trExamples()
QCString TranslatorTurkish::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 230 of file translator_tr.h.
    { return "rnekler"; }
trExamplesDescription()
QCString TranslatorTurkish::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 332 of file translator_tr.h.
    { return "Tm rneklerin listesi aadadr:"; }
trExceptions()
QCString TranslatorTurkish::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 540 of file translator_tr.h.
    { return "stisnalar"; }
trFile()
QCString TranslatorTurkish::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1194 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "dosya", "lar");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorTurkish::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 410 of file translator_tr.h.
    { return "Dosya Dokmantasyonu"; }
trFileIn()
QCString TranslatorTurkish::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1744 of file translator_tr.h.
    {
    return name+" dizinindeki dosya";
    }
trFileIndex()
QCString TranslatorTurkish::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 379 of file translator_tr.h.
    { return "Dosya ndeksi"; }
trFileList()
QCString TranslatorTurkish::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 196 of file translator_tr.h.
    { return "Dosya Listesi"; }
trFileListDescription()
QCString TranslatorTurkish::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 244 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="dosyalar ksa aklamalaryla gstermektedir:";
      return result;
    }
trFileMembers()
QCString TranslatorTurkish::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 213 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globaller";
      }
      else
      {
        return "Dosya yeleri";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorTurkish::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 310 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="fonksiyonlar, deikenleri, makrolar, enmerasyonlar ve typedef\'leri ierir";
      }
      else
      {
        result+="dosya yelerini ierir";
      }
      result+=" ve ";
      if (extractAll)
        result+="ait olduu dosyalar balar:";
      else
        result+="dokmantasyona balar:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorTurkish::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 607 of file translator_tr.h.
    {
      QCString result=fileName;
      result+=" Dosya Referans";
      return result;
    }
trFriends()
QCString TranslatorTurkish::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 567 of file translator_tr.h.
    { return "Arkadalar"; }
trFunctionDocumentation()
QCString TranslatorTurkish::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 474 of file translator_tr.h.
    { return "Fonksiyon Dokmantasyonu"; }
trFunctions()
QCString TranslatorTurkish::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 438 of file translator_tr.h.
    { return "Fonksiyonlar"; }
trGeneratedAt()
QCString TranslatorTurkish::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 501 of file translator_tr.h.
    {
      QCString result=projName+" iin "+date;
      if (!projName.isEmpty()) result+=" tarihinde ";
      result+=" reten: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorTurkish::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 151 of file translator_tr.h.
    { QCString result="Doxygen tarafndan";
      if (!s.isEmpty()) result+=s+" iin ";
      result+=" kaynak koddan otomatik retilmitir.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorTurkish::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 544 of file translator_tr.h.
    { return "Oluturan"; }
trGeneratedFromFiles()
QCString TranslatorTurkish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 744 of file translator_tr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Bu ";
      switch(compType)
      {
        case ClassDef::Class:      result+="snf"; break;
        case ClassDef::Struct:     result+="yap(struct)"; break;
        case ClassDef::Union:      result+="birleim(union)"; break;
        case ClassDef::Interface:  result+="arayz(interface)"; break;
        case ClassDef::Protocol:   result+="protokol"; break;
        case ClassDef::Category:   result+="kategori"; break;
        case ClassDef::Exception:  result+="istisna"; break;
        default: break;
      }
      result+=" iin dokmantasyon aadaki dosya";
      if (single) result+=""; else result+="lar";
      result+="dan retilmitir:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorTurkish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1657 of file translator_tr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Bu ";
      switch(compType)
      {
        case ClassDef::Class:      result+="modl"; break;
        case ClassDef::Struct:     result+="tip"; break;
        case ClassDef::Union:      result+="birleim(union)"; break;
        case ClassDef::Interface:  result+="arayz"; break;
        case ClassDef::Protocol:   result+="protokol"; break;
        case ClassDef::Category:   result+="kategori"; break;
        case ClassDef::Exception:  result+="istisna"; break;
        default: break;
      }
      result+=" iin dokmantasyon aadaki dosya";
      if (single) result+=":"; else result+="lar";
      result="dan retilmitir:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorTurkish::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1239 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "global deiken", "ler");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorTurkish::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1719 of file translator_tr.h.
    {
    return "En st Seviye";
    }
trGotoDocumentation()
QCString TranslatorTurkish::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 832 of file translator_tr.h.
    {
      return "Bu dosyann dokmantasyonuna git.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorTurkish::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 865 of file translator_tr.h.
    {
      return "Grafiksel snf hiyerarisine git";
    }
trGotoSourceCode()
QCString TranslatorTurkish::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 827 of file translator_tr.h.
    {
      return "Bu dosyann kaynak koduna git.";
    }
trGotoTextualHierarchy()
QCString TranslatorTurkish::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 869 of file translator_tr.h.
    {
      return "Metinsel snf hiyerarisine git";
    }
trGraphicalHierarchy()
QCString TranslatorTurkish::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 861 of file translator_tr.h.
    {
      return "Grafiksel Snf Hiyerarisi";
    }
trGroup()
QCString TranslatorTurkish::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1212 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "grup", "lar");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorTurkish::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 358 of file translator_tr.h.
    { return "Hiyerarik ndeksi"; }
trImplementedFromList()
QCString TranslatorTurkish::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1273 of file translator_tr.h.
    {
      return "u yeleri gerekler: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorTurkish::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1281 of file translator_tr.h.
    {
      return "u yelerce gereklenir: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorTurkish::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 961 of file translator_tr.h.
    {
      return "Bu ekil hangi dosyalarn dorudan ya da "
             "dolayl olarak bu dosyay ierdiini gsterir:";
    }
trInclDepGraph()
QCString TranslatorTurkish::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 817 of file translator_tr.h.
    {
      return fName+" iin ierme bamllk grafii:";
    }
trIncludesFileIn()
QCString TranslatorTurkish::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1753 of file translator_tr.h.
    {
    return name + " dizinindeki dosyay kapsyor";
    }
trIncludingInheritedMembers()
QCString TranslatorTurkish::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 145 of file translator_tr.h.
    { return "  (kaltmla gelen yeleri de ierir)."; }
trInheritedByList()
QCString TranslatorTurkish::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 678 of file translator_tr.h.
    {
      return "u snflarn atasdr : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList()
QCString TranslatorTurkish::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 670 of file translator_tr.h.
    {
      return "u snflardan tremitir : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorTurkish::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 852 of file translator_tr.h.
    {
      return "lk deer:";
    }
trInvariant()
QCString TranslatorTurkish::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 847 of file translator_tr.h.
    {
      return "Deimez(Invariant)";
    }
trISOLang()
QCString TranslatorTurkish::trISOLang () inline override virtual
Implements Translator.
Definition at line 76 of file translator_tr.h.
    {
      return "tr";
    }
trLegend()
QCString TranslatorTurkish::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1045 of file translator_tr.h.
    {
      return "lejant";
    }
trLegendDocs()
QCString TranslatorTurkish::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 983 of file translator_tr.h.
    {
      return
        "Bu dosya doxygen tarafndan retilen grafiklerin nasl anlalacan "
        "aklar.<p>\n"
        "Aadaki rnee bakalm:\n"
        "\\code\n"
        "/*! Sadeleme yznden grnmeyen snf */\n"
        "class Invisible { };\n\n"
        "/*! Sadelemi snf, kaltm ilikisi gizli */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Doxygen yorumlaryla dokmante edilmemi snf */\n"
        "class Undocumented { };\n\n"
        "/*! Public kaltmla tretilen snf */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Bir ablon snf */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Korumal kaltmla tretilen snf */\n"
        "class ProtectedBase { };\n\n"
        "/*! zel kaltmla tretilen snf */\n"
        "class PrivateBase { };\n\n"
        "/*! Tretilen snf tarafndan kullanlan snf */\n"
        "class Used { };\n\n"
        "/*! Pekok snftan treyen bir snf */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Bu kod aadaki emay oluturur:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Yukardaki emadaki kutular aada aklanmtr:\n"
        "<ul>\n"
        "<li>Dolu gri kutu emann ait olduu yap(struct) ya da snf "
        "gsterir.\n"
        "<li>Siyah ereveli bir kutu dokmante edilmi bir yap(struct) ya da snf gsterir.\n"
        "<li>Gri ereveli bir kutu dokmante edilmemi bir yap(struct) ya da snf gsterir.\n"
        "<li>Krmz ereveli bir kutu tm kaltm/ierme ilikileri gsterilmemi ve dokmante "
        "edilmi bir yap(struct) ya da snf gsterir. %A ema belirlenen snrlara "
        "smyorsa sadeletirilir.\n"
        "</ul>\n"
        "Oklarn anlam aadaki gibidir:\n"
        "<ul>\n"
        "<li>Koyu mavi ok iki snf arasndaki public kaltm ilikisini "
        "gstermekte kullanlr.\n"
        "<li>Koyu yeil ok korumal kaltm gsterir.\n"
        "<li>Koyu krmz ok zel kaltm gsterir.\n"
        "<li>Mor kesikli izgi bir snfn dieri tarafndan ieriliyor ya da kullanlyor "
        "olduunu gsterir. Ok iaret edilen snfn hangi deiken(ler) tarafndan eriildiini "
        "gsteren etiketle iaretlenitir.\n"
        "<li>Sar kesikli izgi ablondan retilen bir snf ve ilgili ablon snf "
        "arasndaki ilikiyi gsterir. Ok treyen snfn ablon parametreleriyle "
        "etiketlenmitir.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorTurkish::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 976 of file translator_tr.h.
    {
      return "ekil Lejant";
    }
trListOfAllMembers()
QCString TranslatorTurkish::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 133 of file translator_tr.h.
    { return "Tm yelerin listesi"; }
trLoading()
QCString TranslatorTurkish::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1713 of file translator_tr.h.
    {
    return "Yklyor...";
    }
trMainPage()
QCString TranslatorTurkish::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 776 of file translator_tr.h.
    { return "Ana Sayfa"; }
trMember()
QCString TranslatorTurkish::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1230 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "ye", "ler");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorTurkish::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 116 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Alan Dokmantasyonu";
      }
      else
      {
        return "ye Veri Dokmantasyonu";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorTurkish::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 108 of file translator_tr.h.
    { return "ye Enmerasyon Dokmantasyonu"; }
trMemberFunctionDocumentation()
QCString TranslatorTurkish::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member fonksiyonlar.
Implements Translator.
Definition at line 112 of file translator_tr.h.
    { return "ye Fonksiyon Dokmantasyonu"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorTurkish::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1512 of file translator_tr.h.
    { return "ye Fonksiyon/Subroutine Dokmantasyonu"; }
trMemberList()
QCString TranslatorTurkish::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 137 of file translator_tr.h.
    { return "ye Listesi"; }
trMemberTypedefDocumentation()
QCString TranslatorTurkish::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 104 of file translator_tr.h.
    { return "ye Typedef Dokmantasyonu"; }
trModule()
QCString TranslatorTurkish::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1650 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "modl", "ler");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorTurkish::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 385 of file translator_tr.h.
    { return "Modl Dokmantasyonu"; }
trModuleIndex()
QCString TranslatorTurkish::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 352 of file translator_tr.h.
    { return "Modl ndeksi"; }
trModuleReference()
QCString TranslatorTurkish::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1612 of file translator_tr.h.
    {
      QCString result=namespaceName;
      result+=" Modl Referans";
      return result;
    }
trModules()
QCString TranslatorTurkish::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 175 of file translator_tr.h.
    { return "Modller"; }
trModulesDescription()
QCString TranslatorTurkish::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 340 of file translator_tr.h.
    { return "Tm modllerin listesi aadadr:"; }
trModulesIndex()
QCString TranslatorTurkish::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1643 of file translator_tr.h.
    { return "Modller Indeksi"; }
trModulesList()
QCString TranslatorTurkish::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1578 of file translator_tr.h.
    { return "Modller Listesi"; }
trModulesListDescription()
QCString TranslatorTurkish::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1582 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="modlleri ksa tanmlarya ierir:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorTurkish::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1624 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="modl yelerini ierir ve ";
      if (extractAll)
      {
        result+="her yeyi modl dokmantasyonuna balar:";
      }
      else
      {
        result+="ait olduklar modllere balar:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorTurkish::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1620 of file translator_tr.h.
    { return "Modl yeleri"; }
trMonth()
QCString TranslatorTurkish::trMonth (int month, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1795 of file translator_tr.h.
    {
      static const char *months_short[] = { "Oca", "ub", "Mar", "Nis", "May", "Haz", "Tem", "Au", "Eyl", "Eki", "Kas", "Ara" };
      static const char *months_full[]  = { "Ocak", "ubat", "Mart", "Nisan", "Mays", "Haziran", "Temmuz", "Austos", "Eyll", "Ekim", "Kasm", "Aralk" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore()
QCString TranslatorTurkish::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 129 of file translator_tr.h.
    { return "Ayrntlar..."; }
trNamespace()
QCString TranslatorTurkish::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1203 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "namespace", "\'ler");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorTurkish::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 724 of file translator_tr.h.
    { return "Namespace Dokmantasyonu"; }
trNamespaceIndex()
QCString TranslatorTurkish::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 718 of file translator_tr.h.
    { return "Namespace ndeksi"; }
trNamespaceList()
QCString TranslatorTurkish::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 552 of file translator_tr.h.
    { return "Namespace Listesi"; }
trNamespaceListDescription()
QCString TranslatorTurkish::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 556 of file translator_tr.h.
    {
      QCString result="Tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="namespace\'lerin ksa tanmlaryla listesi aadadr:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorTurkish::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 704 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="namespace yelerini listeler ve ";
      if (extractAll)
        result+="her ye iin ye dokmantasyonuna balar:";
      else
        result+="ait olduu namespace\'lere balar:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorTurkish::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 700 of file translator_tr.h.
    { return "Namespace yeleri"; }
trNamespaceReference()
QCString TranslatorTurkish::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 615 of file translator_tr.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Referans";
      return result;
    }
trNamespaces()
QCString TranslatorTurkish::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 734 of file translator_tr.h.
    { return "Namespace\'ler"; }
trNoMatches()
QCString TranslatorTurkish::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1731 of file translator_tr.h.
    {
    return "Eleme Yok";
    }
trNote()
QCString TranslatorTurkish::trNote () inline override virtual
Implements Translator.
Definition at line 882 of file translator_tr.h.
    {
      return "Not";
    }
trOverloadText()
QCString TranslatorTurkish::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1484 of file translator_tr.h.
    {
       return "Bu ok anlaml (overloaded) bir ye fonksiyondur, "
              "tamamlk asndan burada verilmektedir. Yukardaki fonksiyondan "
              "sadece ald argman(lar) asndan farkldr.";
    }
trPackage()
QCString TranslatorTurkish::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1097 of file translator_tr.h.
    {
      return "Paket "+name;
    }
trPackageAttribs()
QCString TranslatorTurkish::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1358 of file translator_tr.h.
    {
      return "Packet zellikleri(attribute)";
    }
trPackageFunctions()
QCString TranslatorTurkish::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class fonksiyonlar with package scope.
Implements Translator.
Definition at line 1340 of file translator_tr.h.
    {
      return "Paket Fonksiyonlar";
    }
trPackageListDescription()
QCString TranslatorTurkish::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1102 of file translator_tr.h.
    {
      return "Paketler ve ksa tanmlar (var ise):";
    }
trPackageMembers()
QCString TranslatorTurkish::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1344 of file translator_tr.h.
    {
      return "Paket yeler";
    }
trPackages()
QCString TranslatorTurkish::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1107 of file translator_tr.h.
    {
      return "Paketler";
    }
trPackageTypes()
QCString TranslatorTurkish::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1333 of file translator_tr.h.
    {
      return "Paket Tipleri";
    }
trPage()
QCString TranslatorTurkish::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1221 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "sayfa", "lar");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorTurkish::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 782 of file translator_tr.h.
    { return "sf."; }
trPageIndex()
QCString TranslatorTurkish::trPageIndex () inline override virtual
Implements Translator.
Definition at line 873 of file translator_tr.h.
    {
      return "Sayfa ndeksi";
    }
trParameters()
QCString TranslatorTurkish::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 536 of file translator_tr.h.
    { return "Parametreler"; }
trPostcondition()
QCString TranslatorTurkish::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 842 of file translator_tr.h.
    {
      return "Son art (Postcondition)";
    }
trPrecondition()
QCString TranslatorTurkish::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 837 of file translator_tr.h.
    {
      return "n art";
    }
trPrivateAttribs()
QCString TranslatorTurkish::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 921 of file translator_tr.h.
    {
      return "zel zellikler(attribute)";
    }
trPrivateMembers()
QCString TranslatorTurkish::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 636 of file translator_tr.h.
    { return "zel ye Fonksiyonlar"; }
trPrivateSlots()
QCString TranslatorTurkish::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 638 of file translator_tr.h.
    { return "zel Slotlar"; }
trPrivateTypes()
QCString TranslatorTurkish::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 917 of file translator_tr.h.
    {
      return "zel Tipler";
    }
trProperties()
QCString TranslatorTurkish::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1070 of file translator_tr.h.
    {
      return "zellikler";
    }
trPropertyDocumentation()
QCString TranslatorTurkish::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1075 of file translator_tr.h.
    {
      return "zellik Dokmantasyonu";
    }
trProtectedAttribs()
QCString TranslatorTurkish::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 909 of file translator_tr.h.
    {
      return "Korumal zellikler(attribute)";
    }
trProtectedMembers()
QCString TranslatorTurkish::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 630 of file translator_tr.h.
    { return "Korumal ye Fonksiyonlar"; }
trProtectedSlots()
QCString TranslatorTurkish::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 632 of file translator_tr.h.
    { return "Korumal Slotlar"; }
trProtectedTypes()
QCString TranslatorTurkish::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 905 of file translator_tr.h.
    {
      return "Korumal Tipler";
    }
trPublicAttribs()
QCString TranslatorTurkish::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 890 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Alanlar";
      }
      else
      {
        return "Public zellikler(attribute)";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorTurkish::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 622 of file translator_tr.h.
    { return "Public ye Fonksiyonlar"; }
trPublicSlots()
QCString TranslatorTurkish::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 624 of file translator_tr.h.
    { return "Public Slotlar"; }
trPublicTypes()
QCString TranslatorTurkish::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 886 of file translator_tr.h.
    {
      return "Public Tipler";
    }
trReferencedBy()
QCString TranslatorTurkish::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 949 of file translator_tr.h.
    {
      return "Referans veren";
    }
trReferenceManual()
QCString TranslatorTurkish::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 414 of file translator_tr.h.
    { return "Referans Kitab"; }
trReferences()
QCString TranslatorTurkish::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1261 of file translator_tr.h.
    {
      return "Referanslar";
    }
trReimplementedFromList()
QCString TranslatorTurkish::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 686 of file translator_tr.h.
    {
      return "u yeleri yeniden tanmlar : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorTurkish::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 694 of file translator_tr.h.
    {
      return "u yeler tarafndan yeniden tanmlanmtr : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorTurkish::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 577 of file translator_tr.h.
    { return "Arkada Ve lgili Fonksiyon Dokmantasyonu"; }
trRelatedFunctions()
QCString TranslatorTurkish::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related fonksiyonlar.
Implements Translator.
Definition at line 88 of file translator_tr.h.
    { return "lgili Fonksiyonlar"; }
trRelatedPages()
QCString TranslatorTurkish::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 226 of file translator_tr.h.
    { return "lgili Sayfalar"; }
trRelatedPagesDescription()
QCString TranslatorTurkish::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 336 of file translator_tr.h.
    { return "lgili tm dokmantasyon sayfalarnn listesi aadadr:"; }
trRelatedSubscript()
QCString TranslatorTurkish::trRelatedSubscript () inline override virtual
subscript for the related fonksiyonlar.
Implements Translator.
Definition at line 92 of file translator_tr.h.
    { return "(Not: Bu fonksiyonlar ye fonksiyon deildir.)"; }
trRemarks()
QCString TranslatorTurkish::trRemarks () inline override virtual
Implements Translator.
Definition at line 953 of file translator_tr.h.
    {
      return "Dipnotlar";
    }
trReturns()
QCString TranslatorTurkish::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 528 of file translator_tr.h.
    { return "Dndrd deer"; }
trReturnValues()
QCString TranslatorTurkish::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 771 of file translator_tr.h.
    { return "Dndrd deerler"; }
trRTFansicp()
QCString TranslatorTurkish::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1161 of file translator_tr.h.
    {
      return "1254";
    }
trRTFCharSet()
QCString TranslatorTurkish::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1170 of file translator_tr.h.
    {
      return "162";
    }
trRTFGeneralIndex()
QCString TranslatorTurkish::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1176 of file translator_tr.h.
    {
      return "ndeks";
    }
trRTFTableOfContents()
QCString TranslatorTurkish::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1293 of file translator_tr.h.
    {
      return "indekiler";
    }
trSearch()
QCString TranslatorTurkish::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 234 of file translator_tr.h.
    { return "Ara"; }
trSearching()
QCString TranslatorTurkish::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1725 of file translator_tr.h.
    {
    return "Aryor...";
    }
trSearchMatches()
QCString TranslatorTurkish::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1425 of file translator_tr.h.
    {
      return "Eleme:";
    }
trSearchResults()
QCString TranslatorTurkish::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1406 of file translator_tr.h.
    {
      if (numDocuments==0)
      {
        return "zgnm, sorgunuzla eleen dokman bulunamad.";
      }
      else if (numDocuments==1)
      {
        return "Sorgunuzla eleen <b>1</b> dokman bulundu.";
      }
      else
      {
        return "Sorgunuzla eleen <b>$num</b> dokman bulundu. "
               "nce en iyi elemeler gsteriliyor.";
      }
    }
trSearchResultsTitle()
QCString TranslatorTurkish::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1394 of file translator_tr.h.
    {
      return "Arama sonular";
    }
trSeeAlso()
QCString TranslatorTurkish::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 532 of file translator_tr.h.
    { return "Ayrca Baknz"; }
trSignals()
QCString TranslatorTurkish::trSignals () inline override virtual
Implements Translator.
Definition at line 626 of file translator_tr.h.
    { return "Sinyaller"; }
trSince()
QCString TranslatorTurkish::trSince () inline override virtual
Implements Translator.
Definition at line 966 of file translator_tr.h.
    {
      return "u zamandan beri";
    }
trSourceFile()
QCString TranslatorTurkish::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1436 of file translator_tr.h.
    {
      return filename + " Kaynak Dosyas";
    }
trStaticPackageAttribs()
QCString TranslatorTurkish::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1365 of file translator_tr.h.
    {
      return "Statik Packet zellikleri(attribute)";
    }
trStaticPackageFunctions()
QCString TranslatorTurkish::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class fonksiyonlar with package scope.
Implements Translator.
Definition at line 1351 of file translator_tr.h.
    {
      return "Static Pakat Fonksiyonlar";
    }
trStaticPrivateAttribs()
QCString TranslatorTurkish::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 925 of file translator_tr.h.
    {
      return "Statik zel zellikler(attribute)";
    }
trStaticPrivateMembers()
QCString TranslatorTurkish::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 640 of file translator_tr.h.
    { return "Statik zel ye Fonksiyonlar"; }
trStaticProtectedAttribs()
QCString TranslatorTurkish::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 913 of file translator_tr.h.
    {
      return "Statik Korumal Attributes";
    }
trStaticProtectedMembers()
QCString TranslatorTurkish::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 634 of file translator_tr.h.
    { return "Statik Korumal ye Fonksiyonlar"; }
trStaticPublicAttribs()
QCString TranslatorTurkish::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 901 of file translator_tr.h.
    {
      return "Statik Public zellikler(attribute)";
    }
trStaticPublicMembers()
QCString TranslatorTurkish::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 628 of file translator_tr.h.
    { return "Statik Public ye Fonksiyonlar"; }
trSubprogram()
QCString TranslatorTurkish::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1690 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "alt program", "lar");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorTurkish::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1568 of file translator_tr.h.
    { return "Fonksiyon/Subroutine Dokmantasyonu"; }
trSubprograms()
QCString TranslatorTurkish::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1562 of file translator_tr.h.
    { return "Fonksiyonlar/Subroutine\'ler"; }
trTest()
QCString TranslatorTurkish::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1055 of file translator_tr.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorTurkish::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1060 of file translator_tr.h.
    {
      return "Test Listesi";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorTurkish::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 141 of file translator_tr.h.
    { return "u snfn tm yelerinin listesidir:"; }
trTodo()
QCString TranslatorTurkish::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 935 of file translator_tr.h.
    {
      return "Yaplacak";
    }
trTodoList()
QCString TranslatorTurkish::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 940 of file translator_tr.h.
    {
      return "Yaplacaklar Listesi";
    }
trType()
QCString TranslatorTurkish::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1682 of file translator_tr.h.
    {
      return createNoun(first_capital, singular, "tip", "ler");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorTurkish::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1696 of file translator_tr.h.
    {
      return "Tip Snrlamalar";
    }
trTypedefDocumentation()
QCString TranslatorTurkish::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 462 of file translator_tr.h.
    { return "Typedef Dokmantasyonu"; }
trTypedefs()
QCString TranslatorTurkish::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 426 of file translator_tr.h.
    { return "Typedef\'ler"; }
trTypeDocumentation()
QCString TranslatorTurkish::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1556 of file translator_tr.h.
    { return "Veri Tipi Dokmantasyonu"; }
trVariableDocumentation()
QCString TranslatorTurkish::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 480 of file translator_tr.h.
    { return "Deiken Dokmantasyonu"; }
trVariables()
QCString TranslatorTurkish::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 444 of file translator_tr.h.
    { return "Deikenler"; }
trVersion()
QCString TranslatorTurkish::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 520 of file translator_tr.h.
    { return "Srm"; }
trWarning()
QCString TranslatorTurkish::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 516 of file translator_tr.h.
    { return "Uyar"; }
trWriteList()
QCString TranslatorTurkish::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 646 of file translator_tr.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" ve ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_tr.h