Doxygen: SearchTerm Struct Reference
SearchTerm Struct Reference
Searchable term.
#include <src/searchindex_js.h>
Public Types
using LinkInfo = std::variant<std::monostate,const Definition *,const SectionInfo *>
Public Member Functions
SearchTerm (const QCString &w, const Definition *d)
SearchTerm (const QCString &w, const SectionInfo *s)
QCString termEncoded () const
encoded version of the search term
Public Attributes
QCString word
lower case word that is indexed (e.g. name of a symbol, or word from a title)
QCString title
title to show in the output for this search result
LinkInfo info
definition to link to
Private Member Functions
void makeTitle ()
Detailed Description
Searchable term.
Definition at line 42 of file searchindex_js.h.
Member Typedef Documentation
LinkInfo
using SearchTerm::LinkInfo = std::variant<std::monostate,const Definition *,const SectionInfo *>
Definition at line 44 of file searchindex_js.h.
Constructor & Destructor Documentation
SearchTerm() [1/2]
SearchTerm::SearchTerm (const QCString & w, const Definition * d) inline
Definition at line 45 of file searchindex_js.h.
: word(w.str()), info(d)  { makeTitle(); }
References info, makeTitle(), and word.
SearchTerm() [2/2]
SearchTerm::SearchTerm (const QCString & w, const SectionInfo * s) inline
Definition at line 46 of file searchindex_js.h.
: word(w.str()), info(s)  { makeTitle(); }
References info, makeTitle(), and word.
Member Function Documentation
makeTitle()
void SearchTerm::makeTitle () private
Definition at line 43 of file searchindex_js.cpp.
{
  if (std::holds_alternative<const Definition *>(info))
  {
    const Definition *def = std::get<const Definition *>(info);
    Definition::DefType type = def->definitionType();
    title = type==Definition::TypeGroup ?  filterTitle(toGroupDef(def)->groupTitle()) :
            type==Definition::TypePage  ?  filterTitle(toPageDef(def)->title()) :
                                           def->localName();
  }
  else if (std::holds_alternative<const SectionInfo *>(info))
  {
    title = std::get<const SectionInfo *>(info)->title();
  }
  else
  {
    assert(false);
  }
}
References Definition::definitionType(), filterTitle(), info, Definition::localName(), title, toGroupDef(), toPageDef(), Definition::TypeGroup, and Definition::TypePage.
Referenced by SearchTerm(), and SearchTerm().
termEncoded()
QCString SearchTerm::termEncoded () const
encoded version of the search term
Definition at line 63 of file searchindex_js.cpp.
{
  TextStream t;
  for (size_t i=0;i<word.length();i++)
  {
    if (isIdJS(word.at(i)))
    {
      t << word.at(i);
    }
    else // escape non-identifier characters
    {
      static const char *hex = "0123456789ABCDEF";
      unsigned char uc = static_cast<unsigned char>(word.at(i));
      t << '_';
      t << hex[uc>>4];
      t << hex[uc&0xF];
    }
  }
  return convertUTF8ToLower(t.str());
}
References convertUTF8ToLower(), hex, isIdJS(), TextStream::str(), and word.
Member Data Documentation
info
LinkInfo SearchTerm::info
definition to link to
Definition at line 49 of file searchindex_js.h.
Referenced by makeTitle(), SearchTerm(), and SearchTerm().
title
QCString SearchTerm::title
title to show in the output for this search result
Definition at line 48 of file searchindex_js.h.
Referenced by makeTitle().
word
QCString SearchTerm::word
lower case word that is indexed (e.g. name of a symbol, or word from a title)
Definition at line 47 of file searchindex_js.h.
Referenced by SearchTerm(), SearchTerm(), and termEncoded().
The documentation for this struct was generated from the following files:
src/searchindex_js.h
src/searchindex_js.cpp