Doxygen: LocalDef Class Reference
LocalDef Class Reference
Class representing a local class definition found while generating syntax highlighted code.
#include <src/scopedtypevariant.h>
Public Member Functions
void insertBaseClass (const QCString &name)
std::vector< QCString > baseClasses () const
Private Attributes
std::vector< QCString > m_baseClasses
Detailed Description
Class representing a local class definition found while generating syntax highlighted code.
Definition at line 28 of file scopedtypevariant.h.
Member Function Documentation
baseClasses()
std::vector< QCString > LocalDef::baseClasses () const inline
Definition at line 32 of file scopedtypevariant.h.
{ return m_baseClasses; }
References m_baseClasses.
Referenced by generateFunctionLink(), generateFunctionLink(), generateMemberLink(), and getLinkInScope().
insertBaseClass()
void LocalDef::insertBaseClass (const QCString & name) inline
Definition at line 31 of file scopedtypevariant.h.
{ m_baseClasses.push_back(name); }
References m_baseClasses.
Member Data Documentation
m_baseClasses
std::vector<QCString> LocalDef::m_baseClasses private
Definition at line 34 of file scopedtypevariant.h.
Referenced by baseClasses(), and insertBaseClass().
The documentation for this class was generated from the following file:
src/scopedtypevariant.h