Doxygen: DocParamSect Class Reference
DocParamSect Class Reference
Node representing a parameter section.
#include <src/docnode.h>
Public Types
enum Type {
Unknown , Param , RetVal , Exception ,
TemplateParam
}
enum Direction { In =1 , Out =2 , InOut =3 , Unspecified =0 }
Public Member Functions
DocParamSect (DocParser *parser, DocNodeVariant *parent, Type t)
Token parse (const QCString &cmdName, bool xmlContext, Direction d)
Type type () const
bool hasInOutSpecifier () const
bool hasTypeSpecifier () const
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
Type m_type = Unknown
bool m_hasInOutSpecifier = false
bool m_hasTypeSpecifier = false
Friends
class DocParamList
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a parameter section.
Definition at line 1031 of file docnode.h.
Member Enumeration Documentation
Direction
enum DocParamSect::Direction
Enumerator
In
Out
InOut
Unspecified
Definition at line 1039 of file docnode.h.
    {
       In=1, Out=2, InOut=3, Unspecified=0
    };
Type
enum DocParamSect::Type
Enumerator
Unknown
Param
RetVal
Exception
TemplateParam
Definition at line 1035 of file docnode.h.
    {
       Unknown, Param, RetVal, Exception, TemplateParam
    };
Constructor & Destructor Documentation
DocParamSect()
DocParamSect::DocParamSect (DocParser * parser, DocNodeVariant * parent, Type t) inline
Definition at line 1043 of file docnode.h.
      : DocCompoundNode(parser,parent), m_type(t), m_hasInOutSpecifier(FALSE), m_hasTypeSpecifier(FALSE)
    {}
References DocCompoundNode::DocCompoundNode(), m_hasInOutSpecifier, m_hasTypeSpecifier, m_type, DocNode::parent(), and DocNode::parser().
Member Function Documentation
hasInOutSpecifier()
bool DocParamSect::hasInOutSpecifier () const inline
Definition at line 1048 of file docnode.h.
{ return m_hasInOutSpecifier; }
References m_hasInOutSpecifier.
Referenced by DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), and RTFDocVisitor::operator()().
hasTypeSpecifier()
bool DocParamSect::hasTypeSpecifier () const inline
Definition at line 1049 of file docnode.h.
{ return m_hasTypeSpecifier; }
References m_hasTypeSpecifier.
Referenced by DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), and RTFDocVisitor::operator()().
parse()
Token DocParamSect::parse (const QCString & cmdName, bool xmlContext, Direction d)
Definition at line 3181 of file docnode.cpp.
{
  AUTO_TRACE();
  Token retval = Token::make_RetVal_OK();
  auto ns = AutoNodeStack(parser(),thisVariant());
  if (d!=Unspecified)
  {
    m_hasInOutSpecifier=TRUE;
  }
  if (!children().empty() && std::holds_alternative<DocParamList>(children().back()))
  {
    DocParamList &lastPl = std::get<DocParamList>(children().back());
    lastPl.markLast(false);
  }
  bool markFirst = children().empty();
  children().append<DocParamList>(parser(),thisVariant(),m_type,d);
  DocParamList *pl = children().get_last<DocParamList>();
  if (markFirst)
  {
    pl->markFirst();
  }
  pl->markLast();
  if (xmlContext)
  {
    retval = pl->parseXml(cmdName);
  }
  else
  {
    retval = pl->parse(cmdName);
  }
  if (retval.is(TokenRetval::RetVal_EndParBlock))
  {
    retval = Token::make_RetVal_OK();
  }
  AUTO_TRACE_EXIT("retval={}",retval.to_string());
  return retval;
}
References DocNodeList::append(), AUTO_TRACE, AUTO_TRACE_EXIT, DocCompoundNode::children(), DocParamList, GrowVector< T >::empty(), DocNodeList::get_last(), Token::is(), m_hasInOutSpecifier, m_type, DocParamList::markLast(), DocNode::parser(), DocNode::thisVariant(), Token::to_string(), TRUE, and Unspecified.
Referenced by DocPara::handleParamSection().
type()
Type DocParamSect::type () const inline
Definition at line 1047 of file docnode.h.
{ return m_type; }
References m_type.
Referenced by DocPara::handleParamSection(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
Friends And Related Symbol Documentation
DocParamList
friend class DocParamList friend
Definition at line 1033 of file docnode.h.
References DocParamList.
Referenced by DocParamList, and parse().
Member Data Documentation
m_hasInOutSpecifier
bool DocParamSect::m_hasInOutSpecifier = false private
Definition at line 1053 of file docnode.h.
Referenced by DocParamSect(), hasInOutSpecifier(), and parse().
m_hasTypeSpecifier
bool DocParamSect::m_hasTypeSpecifier = false private
Definition at line 1054 of file docnode.h.
Referenced by DocParamSect(), and hasTypeSpecifier().
m_type
Type DocParamSect::m_type = Unknown private
Definition at line 1052 of file docnode.h.
Referenced by DocParamSect(), parse(), and type().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp