Doxygen: src/cite.cpp File Reference
cite.cpp File Reference
#include "cite.h"
#include "config.h"
#include "language.h"
#include "message.h"
#include "portable.h"
#include "resourcemgr.h"
#include "util.h"
#include "debug.h"
#include "fileinfo.h"
#include "dir.h"
#include "growbuf.h"
#include "entry.h"
#include "commentscan.h"
#include "linkedmap.h"
#include <map>
#include <unordered_map>
#include <string>
#include <fstream>
Classes
class CitePosition
class that provide information about the p[osition of a citation name
class CiteInfoImpl
struct CitationManager::Private
Functions
static QCString getBibFile (const QCString &inFile)
Variables
const char * bibTmpFile = "bibTmpFile_"
const char * bibTmpDir = "bibTmpDir/"
const std::string g_formulaMarker = "CITE_FORMULA_"
Function Documentation
getBibFile()
static QCString getBibFile (const QCString & inFile) static
Definition at line 50 of file cite.cpp.
{
  QCString name = inFile;
  if (!name.isEmpty() && !name.endsWith(".bib")) name+=".bib";
  return name;
}
References QCString::endsWith(), and QCString::isEmpty().
Referenced by CitationManager::generatePage(), and CitationManager::latexBibFiles().
Variable Documentation
bibTmpDir
const char* bibTmpDir = "bibTmpDir/"
Definition at line 38 of file cite.cpp.
Referenced by CitationManager::generatePage().
bibTmpFile
const char* bibTmpFile = "bibTmpFile_"
Definition at line 37 of file cite.cpp.
Referenced by CitationManager::generatePage(), and CitationManager::latexBibFiles().
g_formulaMarker
const std::string g_formulaMarker = "CITE_FORMULA_"
Definition at line 230 of file cite.cpp.
Referenced by CitationManager::getFormulas(), and CitationManager::replaceFormulas().