Doxygen: src/sqlite3gen.h File Reference
sqlite3gen.h File Reference
Functions
void generateSqlite3 ()
Function Documentation
generateSqlite3()
void generateSqlite3 ()
Definition at line 2577 of file sqlite3gen.cpp.
{
  // + classes
  // + namespaces
  // + files
  // + groups
  // + related pages
  // + examples
  // + main page
  sqlite3 *db;
  db = openDbConnection();
  if (db==nullptr)
  {
    return;
  }
# ifdef SQLITE3_DEBUG
  // debug: show all executed statements
  sqlite3_trace(db, &sqlLog, nullptr);
# endif
  beginTransaction(db);
  pragmaTuning(db);
  if (-1==initializeTables(db))
    return;
  if ( -1 == prepareStatements(db) )
  {
    err("sqlite generator: prepareStatements failed!\n");
    return;
  }
  recordMetadata();
  // + classes
  for (const auto &cd : *Doxygen::classLinkedMap)
  {
    msg("Generating Sqlite3 output for class %s\n",qPrint(cd->name()));
    generateSqlite3ForClass(cd.get());
  }
  // + concepts
  for (const auto &cd : *Doxygen::conceptLinkedMap)
  {
    msg("Generating Sqlite3 output for concept %s\n",qPrint(cd->name()));
    generateSqlite3ForConcept(cd.get());
  }
  // + modules
  for (const auto &mod : ModuleManager::instance().modules())
  {
    msg("Generating Sqlite3 output for module %s\n",qPrint(mod->name()));
    generateSqlite3ForModule(mod.get());
  }
  // + namespaces
  for (const auto &nd : *Doxygen::namespaceLinkedMap)
  {
    msg("Generating Sqlite3 output for namespace %s\n",qPrint(nd->name()));
    generateSqlite3ForNamespace(nd.get());
  }
  // + files
  for (const auto &fn : *Doxygen::inputNameLinkedMap)
  {
    for (const auto &fd : *fn)
    {
      msg("Generating Sqlite3 output for file %s\n",qPrint(fd->name()));
      generateSqlite3ForFile(fd.get());
    }
  }
  // + groups
  for (const auto &gd : *Doxygen::groupLinkedMap)
  {
    msg("Generating Sqlite3 output for group %s\n",qPrint(gd->name()));
    generateSqlite3ForGroup(gd.get());
  }
  // + page
  for (const auto &pd : *Doxygen::pageLinkedMap)
  {
    msg("Generating Sqlite3 output for page %s\n",qPrint(pd->name()));
    generateSqlite3ForPage(pd.get(),FALSE);
  }
  // + dirs
  for (const auto &dd : *Doxygen::dirLinkedMap)
  {
    msg("Generating Sqlite3 output for dir %s\n",qPrint(dd->name()));
    generateSqlite3ForDir(dd.get());
  }
  // + examples
  for (const auto &pd : *Doxygen::exampleLinkedMap)
  {
    msg("Generating Sqlite3 output for example %s\n",qPrint(pd->name()));
    generateSqlite3ForPage(pd.get(),TRUE);
  }
  // + main page
  if (Doxygen::mainPage)
  {
    msg("Generating Sqlite3 output for the main page\n");
    generateSqlite3ForPage(Doxygen::mainPage.get(),FALSE);
  }
  // TODO: copied from initializeSchema; not certain if we should say/do more
  // if there's a failure here?
  if (-1==initializeViews(db))
    return;
  endTransaction(db);
}
References beginTransaction(), Doxygen::classLinkedMap, Doxygen::conceptLinkedMap, Doxygen::dirLinkedMap, endTransaction(), err, Doxygen::exampleLinkedMap, FALSE, generateSqlite3ForClass(), generateSqlite3ForConcept(), generateSqlite3ForDir(), generateSqlite3ForFile(), generateSqlite3ForGroup(), generateSqlite3ForModule(), generateSqlite3ForNamespace(), generateSqlite3ForPage(), Doxygen::groupLinkedMap, initializeTables(), initializeViews(), Doxygen::inputNameLinkedMap, ModuleManager::instance(), Doxygen::mainPage, ModuleManager::modules(), msg(), Doxygen::namespaceLinkedMap, openDbConnection(), Doxygen::pageLinkedMap, pragmaTuning(), prepareStatements(), qPrint(), recordMetadata(), and TRUE.
Referenced by generateOutput().