Doxygen: TranslatorSpanish Class Reference
TranslatorSpanish Class Reference
#include <src/translator_es.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description.
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool single) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
QCString trDesignUnitDocumentation () override
VHDL design unit documentation.
QCString trConcept (bool first_capital, bool singular) override
C++20 concept.
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
QCString trPackageList () override
QCString trFlowchart () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 121 of file translator_es.h.
Member Function Documentation
getLanguageString()
QCString TranslatorSpanish::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 160 of file translator_es.h.
    {
      return "0x40A Spanish";
    }
idLanguage()
QCString TranslatorSpanish::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 133 of file translator_es.h.
    { return "spanish"; }
latexLanguageSupportCommand()
QCString TranslatorSpanish::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 150 of file translator_es.h.
    {
      return "\\usepackage[spanish, es-noshorthands, shorthands=off]{babel}";
    }
trAdditionalInheritedMembers()
QCString TranslatorSpanish::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 2028 of file translator_es.h.
    { return "Otros miembros heredados"; }
trAll()
QCString TranslatorSpanish::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1530 of file translator_es.h.
    {
      return "Todos";
    }
trAndMore()
QCString TranslatorSpanish::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 2004 of file translator_es.h.
    { return "y "+number+" ms..."; }
trAttention()
QCString TranslatorSpanish::trAttention () inline override virtual
Implements Translator.
Definition at line 1089 of file translator_es.h.
    {
      return "Atencin";
    }
trAuthor()
QCString TranslatorSpanish::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1398 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "autor", "es");
    }
References Translator::createNoun().
trBug()
QCString TranslatorSpanish::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1267 of file translator_es.h.
    {
      return "Defecto";
    }
trBugList()
QCString TranslatorSpanish::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1273 of file translator_es.h.
    {
      return "Lista de defectos";
    }
trCallerGraph()
QCString TranslatorSpanish::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1656 of file translator_es.h.
    {
      return "Grfico de llamadas a esta funcin:";
    }
trCallGraph()
QCString TranslatorSpanish::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1536 of file translator_es.h.
    {
      return "Grfico de llamadas de esta funcin:";
    }
trCiteReferences()
QCString TranslatorSpanish::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1980 of file translator_es.h.
    { return "Referencias bibliogrficas"; }
trClass()
QCString TranslatorSpanish::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1331 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "clase", "s");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trClassDiagram()
QCString TranslatorSpanish::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 608 of file translator_es.h.
    {
      return "Diagrama de herencia de "+clName;
    }
trClassDocumentation()
QCString TranslatorSpanish::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 489 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentacin de estructuras de datos";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentacin de clases";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorSpanish::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1225 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructuras de datos";
      }
      else
      {
        return "Clases";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorSpanish::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 267 of file translator_es.h.
    { return "Jerarqua de clases"; }
trClassHierarchyDescription()
QCString TranslatorSpanish::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 326 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Esta es la lista jerrquica de todas las entidades:";
      }
      else
      {
        return "Este listado de herencia est ordenado de forma general "
               "pero no est en orden alfabtico estricto:";
      }
    }
References Config_getBool.
trClassMethods()
QCString TranslatorSpanish::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2066 of file translator_es.h.
    {
      return "Mtodos de clase";
    }
trCode()
QCString TranslatorSpanish::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 973 of file translator_es.h.
    {
      return "cdigo fuente";
    }
trCollaborationDiagram()
QCString TranslatorSpanish::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 919 of file translator_es.h.
    {
      return "Diagrama de colaboracin de "+clName+":";
    }
trCompoundIndex()
QCString TranslatorSpanish::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 462 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndice de estructuras de datos";
      }
      else
      {
        return "ndice de clases";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorSpanish::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1711 of file translator_es.h.
    { return "ndice de tipos de datos"; }
trCompoundList()
QCString TranslatorSpanish::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 271 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructuras de datos";
      }
      else
      {
        return "Lista de clases";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorSpanish::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 349 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lista de estructuras con breves descripciones:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Lista de clases con breves descripciones:";
      }
      else
      {
       return "Lista de clases, estructuras, "
             "uniones e interfaces con breves descripciones:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorSpanish::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1684 of file translator_es.h.
    { return "Esta es la lista de los tipos de datos con breves descripciones:"; }
trCompoundListFortran()
QCString TranslatorSpanish::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1676 of file translator_es.h.
    { return "Lista de campos de datos"; }
trCompoundMembers()
QCString TranslatorSpanish::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 288 of file translator_es.h.
    {
    if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de datos";
      }
      else
      {
        return "Miembros de clases";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorSpanish::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 367 of file translator_es.h.
    {
      QCString result="Lista de todos los ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="campos de estructuras y uniones";
      }
      else
      {
        result+="campos de clases";
      }
      if (!extractAll)
      {
        result+=" documentados";
      }
      result+=" con enlaces a ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la documentacin de la estructura/unin para cada campo:";
        }
        else
        {
          result+="la documentacin de la clase para cada miembro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="las estructuras/uniones a las que pertenecen:";
        }
        else
        {
          result+="las clases a las que pertenecen:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorSpanish::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1688 of file translator_es.h.
    {
      QCString result="Esta es la lista de todos ";
      result+="los tipos de datos miembro ";
      if (!extractAll)
      {
        result+="documentados ";
      }
      result+="con enlaces a ";
      if (!extractAll)
      {
         result+="la documentacin de la estructura de datos para cada miembro";
      }
      else
      {
         result+="los tipos de datos a los que pertenecen:";
      }
      return result;
    }
trCompoundMembersDescriptionTotal()
QCString TranslatorSpanish::trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) inline override virtual
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2566 of file translator_es.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool masculine = SpanishTranslatorUtils::isClassMemberHighlightMasculine(hl);
      QCString result="Lista de ";
      result+=(masculine ? "todos los " : "todas las ");
      switch (hl)
      {
        case ClassMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="estructuras y uniones";
          }
          else
          {
            result+="miembros de clases";
          }
          break;
        case ClassMemberHighlight::Functions:
          result+="funciones";
          break;
        case ClassMemberHighlight::Variables:
          result+="variables";
          break;
        case ClassMemberHighlight::Typedefs:
          result+="typedefs";
          break;
        case ClassMemberHighlight::Enums:
          result+="enumeraciones";
          break;
        case ClassMemberHighlight::EnumValues:
          result+="valores enumerados";
          break;
        case ClassMemberHighlight::Properties:
          result+="propiedades";
          break;
        case ClassMemberHighlight::Events:
          result+="eventos";
          break;
        case ClassMemberHighlight::Related:
          result+="smbolos relacionados";
          break;
        case ClassMemberHighlight::Total: // for completeness
          break;
      }
      if (!extractAll) result+=(masculine ? "documentados " : "documentadas ");
      result+=" con enlaces ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a la documentacin de la estructura/unin para cada campo:";
        }
        else
        {
          result+="a la documentacin de la clase para cada miembro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a las estructuras/uniones a las que pertenecen:";
        }
        else
        {
          result+="a las clases a las que pertenecen:";
        }
      }
      return result;
    }
References ClassMemberHighlight::All, Config_getBool, ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, SpanishTranslatorUtils::isClassMemberHighlightMasculine(), ClassMemberHighlight::Properties, ClassMemberHighlight::Related, ClassMemberHighlight::Total, ClassMemberHighlight::Typedefs, and ClassMemberHighlight::Variables.
trCompoundMembersFortran()
QCString TranslatorSpanish::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1680 of file translator_es.h.
    { return "Campos de datos"; }
trCompoundReference()
QCString TranslatorSpanish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 683 of file translator_es.h.
    {
      QCString result="Referencia de";
      if (isTemplate) result+=" la plantilla de";
      switch(compType)
      {
        case ClassDef::Class:      result+=" la clase "; break;
        case ClassDef::Struct:     result+=" la estructura "; break;
        case ClassDef::Union:      result+=" la unin "; break;
        case ClassDef::Interface:  result+=" la interface "; break;
        case ClassDef::Protocol:   result+="l protocolo "; break;
        case ClassDef::Category:   result+=" la categora "; break;
        case ClassDef::Exception:  result+=" la excepcin "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorSpanish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1752 of file translator_es.h.
    {
      QCString result="Referencia de";
      if (isTemplate) result+=" la plantilla de";
      switch(compType)
      {
        case ClassDef::Class:      result+="l mdulo"; break;
        case ClassDef::Struct:     result+="l tipo"; break;
        case ClassDef::Union:      result+=" la unin"; break;
        case ClassDef::Interface:  result+=" la interface"; break;
        case ClassDef::Protocol:   result+="l protocolo"; break;
        case ClassDef::Category:   result+=" la categora"; break;
        case ClassDef::Exception:  result+=" la excepcin"; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice()
QCString TranslatorSpanish::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) inline override virtual
Implements Translator.
Definition at line 2355 of file translator_es.h.
    {
      QCString result="Referencia de";
      switch(compType)
      {
        case ClassDef::Class:      result+=" la clase "; break;
        case ClassDef::Struct:     result+=" la estructura "; break;
        case ClassDef::Union:      result+=" la unin "; break;
        case ClassDef::Interface:  result+=" la interface "; break;
        case ClassDef::Protocol:   result+="l protocolo "; break;
        case ClassDef::Category:   result+=" la categora "; break;
        case ClassDef::Exception:  result+=" la excepcin "; break;
        default: break;
      }
      if (isLocal) result+=" local ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorSpanish::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 584 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructuras de datos";
      }
      else
      {
        return "Clases";
      }
    }
References Config_getBool.
trCompoundType()
QCString TranslatorSpanish::trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) inline override virtual
the compound type as used for the xrefitems
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2490 of file translator_es.h.
    {
      QCString result;
      switch(compType)
      {
        case ClassDef::Class:
          if (lang == SrcLangExt::Fortran) trType(true,true);
          else result=trClass(true,true);
          break;
        case ClassDef::Struct:     result="Estructura"; break;
        case ClassDef::Union:      result="Unin"; break;
        case ClassDef::Interface:  result="Interface"; break;
        case ClassDef::Protocol:   result="Protocolo"; break;
        case ClassDef::Category:   result="Categora"; break;
        case ClassDef::Exception:  result="Excepcin"; break;
        case ClassDef::Service:    result="Servicio"; break;
        case ClassDef::Singleton:  result="Singleton"; break;
        default: break;
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, Fortran, ClassDef::Interface, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, ClassDef::Struct, trClass(), trType(), and ClassDef::Union.
trConcept()
QCString TranslatorSpanish::trConcept (bool first_capital, bool singular) inline override virtual
C++20 concept.
Implements Translator.
Definition at line 2403 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "concepto", "s");
    }
References Translator::createNoun().
trConceptDefinition()
QCString TranslatorSpanish::trConceptDefinition () inline override virtual
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2437 of file translator_es.h.
    {
      return "Definicin de concepto";
    }
trConceptDocumentation()
QCString TranslatorSpanish::trConceptDocumentation () inline override virtual
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2424 of file translator_es.h.
    { return "Documentacin de conceptos"; }
trConceptIndex()
QCString TranslatorSpanish::trConceptIndex () inline override virtual
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2420 of file translator_es.h.
    { return "ndice de conceptos"; }
trConceptList()
QCString TranslatorSpanish::trConceptList () inline override virtual
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2416 of file translator_es.h.
    { return "Lista de conceptos"; }
trConceptListDescription()
QCString TranslatorSpanish::trConceptListDescription (bool extractAll) inline override virtual
used as an introduction to the concept list
Implements Translator.
Definition at line 2428 of file translator_es.h.
    {
      QCString result="Esta es la lista de todos los conceptos ";
      if (!extractAll) result+="documentados ";
      result+="con breves descripciones:";
      return result;
    }
trConceptReference()
QCString TranslatorSpanish::trConceptReference (const QCString & conceptName) inline override virtual
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2408 of file translator_es.h.
    {
      QCString result="Referencia del concepto ";
      result+=conceptName;
      return result;
    }
trConstantDocumentation()
QCString TranslatorSpanish::trConstantDocumentation () inline override virtual
Implements Translator.
Definition at line 2263 of file translator_es.h.
    {
        return "Documentacin de constantes";
    }
trConstantGroupReference()
QCString TranslatorSpanish::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2103 of file translator_es.h.
    {
      QCString result="Referencia a grupos de constantes de ";
      result+=namespaceName;
      return result;
    }
trConstantGroups()
QCString TranslatorSpanish::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2099 of file translator_es.h.
    { return "Grupos de constantes"; }
trConstants()
QCString TranslatorSpanish::trConstants () inline override virtual
Implements Translator.
Definition at line 2259 of file translator_es.h.
    {
        return "Constantes";
    }
trConstructorDocumentation()
QCString TranslatorSpanish::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 931 of file translator_es.h.
    {
      return "Documentacin de constructores y destructores";
    }
trCopyright()
QCString TranslatorSpanish::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1984 of file translator_es.h.
    { return "Copyright"; }
trCustomReference()
QCString TranslatorSpanish::trCustomReference (const QCString & name) inline override virtual
Implements Translator.
Definition at line 2256 of file translator_es.h.
    { return "Referencia de "+name; }
trDataMemberDocumentation()
QCString TranslatorSpanish::trDataMemberDocumentation () inline override virtual
Implements Translator.
Definition at line 2385 of file translator_es.h.
    {
        return "Documentacin de datos miembro";
    }
trDataMembers()
QCString TranslatorSpanish::trDataMembers () inline override virtual
Implements Translator.
Definition at line 2381 of file translator_es.h.
    {
        return "Datos miembro";
    }
trDataTypes()
QCString TranslatorSpanish::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1735 of file translator_es.h.
    { return "Tipos de datos"; }
trDate()
QCString TranslatorSpanish::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 622 of file translator_es.h.
    { return "Fecha"; }
trDateTime()
QCString TranslatorSpanish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1932 of file translator_es.h.
    {
      static const char *days[]   = { "Lunes","Martes","Mircoles","Jueves",
                                      "Viernes","Sbado","Domingo" };
      static const char *months[] = { "enero","febrero","marzo","abril",
                                      "mayo","junio","julio","agosto",
                                      "septiembre","octubre","noviembre","diciembre" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s, %d de %s de %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorSpanish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1955 of file translator_es.h.
    {
      static const char *days_short[]   = { "lun", "mar", "mi", "jue", "vie", "sb", "dom" };
      static const char *days_full[]    = { "lunes", "martes", "mircoles", "jueves", "viernes", "sbado", "domingo" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return first_capital? text.mid(0,1).upper()+text.mid(1) : text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorSpanish::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1969 of file translator_es.h.
    {
      static const char *dayPeriod[] = { "a. m.", "p. m." };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorSpanish::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 896 of file translator_es.h.
    {
      return "Definicin en la lnea @0 del archivo @1.";
    }
trDefinedIn()
QCString TranslatorSpanish::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 255 of file translator_es.h.
    { return "definido en"; }
trDefinedInSourceFile()
QCString TranslatorSpanish::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 900 of file translator_es.h.
    {
      return "Definicin en el archivo @0.";
    }
trDefineDocumentation()
QCString TranslatorSpanish::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 554 of file translator_es.h.
    { return "Documentacin de define"; }
trDefines()
QCString TranslatorSpanish::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 518 of file translator_es.h.
    { return "defines"; }
trDefineValue()
QCString TranslatorSpanish::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1257 of file translator_es.h.
    {
      return "Valor:";
    }
trDeprecated()
QCString TranslatorSpanish::trDeprecated () inline override virtual
Implements Translator.
Definition at line 909 of file translator_es.h.
    {
    return "Obsoleto";
    }
trDeprecatedList()
QCString TranslatorSpanish::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1453 of file translator_es.h.
    {
      return "Lista de obsoletos";
    }
trDesignUnitDocumentation()
QCString TranslatorSpanish::trDesignUnitDocumentation () inline override virtual
VHDL design unit documentation.
Implements Translator.
Definition at line 2395 of file translator_es.h.
    { return "Documentacin de unidades de diseo"; }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorSpanish::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Implements Translator.
Definition at line 2147 of file translator_es.h.
    { return "Jerarqua de unidades de diseo"; }
trDesignUnitIndex()
QCString TranslatorSpanish::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Implements Translator.
Definition at line 2162 of file translator_es.h.
    { return "ndice de unidades de diseo"; }
trDesignUnitList()
QCString TranslatorSpanish::trDesignUnitList () inline override virtual
VHDL design unit list.
Implements Translator.
Definition at line 2150 of file translator_es.h.
    { return "Lista de unidades de diseo"; }
trDesignUnitListDescription()
QCString TranslatorSpanish::trDesignUnitListDescription () inline override virtual
VHDL design unit list description.
Implements Translator.
Definition at line 2156 of file translator_es.h.
    {
        return "Esta es la lista de todos los miembros de unidades de diseo con "
            "enlaces a las entidades a las que pertenecen:";
    }
trDesignUnitMembers()
QCString TranslatorSpanish::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Implements Translator.
Definition at line 2153 of file translator_es.h.
    { return "Miembros de unidades de diseo"; }
trDesignUnits()
QCString TranslatorSpanish::trDesignUnits () inline override virtual
VHDL design units.
Implements Translator.
Definition at line 2165 of file translator_es.h.
    { return "Unidades de diseo"; }
trDetailedDescription()
QCString TranslatorSpanish::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 175 of file translator_es.h.
    { return "Descripcin detallada"; }
trDetailLevel()
QCString TranslatorSpanish::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1996 of file translator_es.h.
    { return "nivel de detalle"; }
trDetails()
QCString TranslatorSpanish::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 179 of file translator_es.h.
    { return "Detalles"; }
trDictionaries()
QCString TranslatorSpanish::trDictionaries () inline override virtual
Implements Translator.
Definition at line 2275 of file translator_es.h.
    {
        return "Diccionarios";
    }
trDictionaryDocumentation()
QCString TranslatorSpanish::trDictionaryDocumentation () inline override virtual
Implements Translator.
Definition at line 2279 of file translator_es.h.
    {
        return "Documentacin de diccionarios";
    }
trDir()
QCString TranslatorSpanish::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1632 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "directorio", "s");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorSpanish::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1988 of file translator_es.h.
    { return "Grfico de dependencias de directorios de "+name+":"; }
trDirDocumentation()
QCString TranslatorSpanish::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1610 of file translator_es.h.
    { return "Documentacin de directorios"; }
trDirectories()
QCString TranslatorSpanish::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1616 of file translator_es.h.
    { return "Directorios"; }
trDirIndex()
QCString TranslatorSpanish::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1604 of file translator_es.h.
    { return "Jerarqua de directorios"; }
trDirReference()
QCString TranslatorSpanish::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1622 of file translator_es.h.
    {
      QCString result="Referencia del directorio ";
      result+=dirName;
      return result;
    }
trDirRelation()
QCString TranslatorSpanish::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1871 of file translator_es.h.
    {
      return "Relacin "+name;
    }
trDocumentation()
QCString TranslatorSpanish::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 444 of file translator_es.h.
    { return "Documentacin" + (!projName.isEmpty()? " de " + projName : ""); }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorSpanish::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 530 of file translator_es.h.
    { return "Enumeraciones"; }
trEnumerationTypeDocumentation()
QCString TranslatorSpanish::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 566 of file translator_es.h.
    { return "Documentacin de enumeraciones"; }
trEnumerationValueDocumentation()
QCString TranslatorSpanish::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1664 of file translator_es.h.
    { return "Documentacin de valores enumerados"; }
trEnumerationValues()
QCString TranslatorSpanish::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 548 of file translator_es.h.
    { return "Valores de enumeraciones"; }
trEnumGeneratedFromFiles()
QCString TranslatorSpanish::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 2008 of file translator_es.h.
    { QCString result = "La documentacin de esta enumeracin est generada de";
      if (single)
          result += "l siguiente archivo:";
      else
          result += " los siguientes archivos:";
      return result;
    }
trEnumName()
QCString TranslatorSpanish::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 247 of file translator_es.h.
    { return "nombre de enumeracin"; }
trEnumReference()
QCString TranslatorSpanish::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 2018 of file translator_es.h.
    { return "Referencia de la enumeracin "+name; }
trEnumValue()
QCString TranslatorSpanish::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 251 of file translator_es.h.
    { return "valor enumerado"; }
trEventDocumentation()
QCString TranslatorSpanish::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1471 of file translator_es.h.
    {
      return "Documentacin de eventos";
    }
trEvents()
QCString TranslatorSpanish::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1465 of file translator_es.h.
    {
      return "Eventos";
    }
trExamples()
QCString TranslatorSpanish::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 318 of file translator_es.h.
    { return "Ejemplos"; }
trExamplesDescription()
QCString TranslatorSpanish::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 430 of file translator_es.h.
    { return "Lista de todos los ejemplos:"; }
trExceptionDocumentation()
QCString TranslatorSpanish::trExceptionDocumentation () inline override virtual
Implements Translator.
Definition at line 2351 of file translator_es.h.
    {
        return "Documentacin de excepciones";
    }
trExceptionHierarchy()
QCString TranslatorSpanish::trExceptionHierarchy () inline override virtual
Implements Translator.
Definition at line 2343 of file translator_es.h.
    {
        return "Jerarqua de excepciones";
    }
trExceptionHierarchyDescription()
QCString TranslatorSpanish::trExceptionHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2347 of file translator_es.h.
    {
        return "Este listado de herencia est ordenado de forma general, pero no est en orden alfabtico estricto:";
    }
trExceptionIndex()
QCString TranslatorSpanish::trExceptionIndex () inline override virtual
Implements Translator.
Definition at line 2331 of file translator_es.h.
    {
        return "ndice de excepciones";
    }
trExceptionList()
QCString TranslatorSpanish::trExceptionList () inline override virtual
Implements Translator.
Definition at line 2335 of file translator_es.h.
    {
        return "Lista de excepciones";
    }
trExceptionListDescription()
QCString TranslatorSpanish::trExceptionListDescription () inline override virtual
Implements Translator.
Definition at line 2339 of file translator_es.h.
    {
        return "Esta es la lista de las excepciones con breves descripciones:";
    }
trExceptions()
QCString TranslatorSpanish::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 638 of file translator_es.h.
    { return "Excepciones"; }
trExtendsClass()
QCString TranslatorSpanish::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2058 of file translator_es.h.
    {
      return "Extiende la clase @0.";
    }
trFile()
QCString TranslatorSpanish::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1340 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "archivo", "s");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorSpanish::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 508 of file translator_es.h.
    { return "Documentacin de archivos"; }
trFileIn()
QCString TranslatorSpanish::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1908 of file translator_es.h.
    {
      return "Archivo en "+name;
    }
trFileIndex()
QCString TranslatorSpanish::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 477 of file translator_es.h.
    { return "ndice de archivos"; }
trFileList()
QCString TranslatorSpanish::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 284 of file translator_es.h.
    { return "Lista de archivos"; }
trFileListDescription()
QCString TranslatorSpanish::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 340 of file translator_es.h.
    {
      QCString result="Lista de todos los archivos ";
      if (!extractAll) result+="documentados y ";
      result+="con breves descripciones:";
      return result;
    }
trFileMembers()
QCString TranslatorSpanish::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 301 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globales";
      }
      else
      {
        return "Miembros de los archivos";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorSpanish::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 409 of file translator_es.h.
    {
      QCString result="Lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas las funciones, variables, defines, enumeraciones y typedefs";
      }
      else
      {
        result+="todos los miembros de los archivos";
      }
      if (!extractAll) result+=" documentados";
      result+=" con enlaces ";
      if (extractAll)
        result+="a los archivos a los que corresponden:";
      else
        result+="a la documentacin:";
      return result;
    }
References Config_getBool.
trFileMembersDescriptionTotal()
QCString TranslatorSpanish::trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) inline override virtual
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2512 of file translator_es.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool masculine = SpanishTranslatorUtils::isFileMemberHighlightMasculine(hl);
      QCString result="Lista de ";
      result+=(masculine ? "todos los " : "todas las ");
      switch (hl)
      {
        case FileMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="funciones, variables, defines, enumeraciones y typedefs";
          }
          else
          {
            result+="miembros de los archivos";
          }
          break;
        case FileMemberHighlight::Functions:
          result+="funciones";
          break;
        case FileMemberHighlight::Variables:
          result+="variables";
          break;
        case FileMemberHighlight::Typedefs:
          result+="typedefs";
          break;
        case FileMemberHighlight::Sequences:
          result+="secuencias";
          break;
        case FileMemberHighlight::Dictionaries:
          result+="diccionarios";
          break;
        case FileMemberHighlight::Enums:
          result+="enumeraciones";
          break;
        case FileMemberHighlight::EnumValues:
          result+="valores enumerados";
          break;
        case FileMemberHighlight::Defines:
          result+="macros";
          break;
        case FileMemberHighlight::Total: // for completeness
          break;
      }
      if (!extractAll) result+=(masculine ? "documentados " : "documentadas ");
      result+=" con enlaces ";
      if (extractAll)
        result+="a los archivos a los que corresponden:";
      else
        result+="a la documentacin:";
      return result;
    }
References FileMemberHighlight::All, Config_getBool, FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, SpanishTranslatorUtils::isFileMemberHighlightMasculine(), FileMemberHighlight::Sequences, FileMemberHighlight::Total, FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
trFileReference()
QCString TranslatorSpanish::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 705 of file translator_es.h.
    {
      QCString result="Referencia del archivo ";
      result+=fileName;
      return result;
    }
trFlowchart()
QCString TranslatorSpanish::trFlowchart () inline override virtual
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2456 of file translator_es.h.
    { return "Diagrama de flujo:"; }
trFriends()
QCString TranslatorSpanish::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 665 of file translator_es.h.
    { return "Amigas"; }
trFunctionAndProc()
QCString TranslatorSpanish::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Implements Translator.
Definition at line 2168 of file translator_es.h.
    { return "Funciones/procedimientos/procesos"; }
trFunctionDocumentation()
QCString TranslatorSpanish::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 572 of file translator_es.h.
    { return "Documentacin de funciones"; }
trFunctions()
QCString TranslatorSpanish::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 536 of file translator_es.h.
    { return "Funciones"; }
trGeneratedAt()
QCString TranslatorSpanish::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 599 of file translator_es.h.
    {
      QCString result="Generado el "+date;
      if (!projName.isEmpty()) result+=" para "+projName;
      result+=" por";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorSpanish::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 239 of file translator_es.h.
    { QCString result="Generado automticamente por Doxygen";
      if (!s.isEmpty()) result+=" para "+s;
      result+=" del cdigo fuente.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorSpanish::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 642 of file translator_es.h.
    { return "Generado por"; }
trGeneratedFromFiles()
QCString TranslatorSpanish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 851 of file translator_es.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="La documentacin de est";
      switch(compType)
      {
        case ClassDef::Class:      result+=vhdlOpt? "a unidad de diseo":"a clase"; break;
        case ClassDef::Struct:     result+="a estructura"; break;
        case ClassDef::Union:      result+="a unin"; break;
        case ClassDef::Interface:  result+="a interface"; break;
        case ClassDef::Protocol:   result+="e protocolo"; break;
        case ClassDef::Category:   result+="a categora"; break;
        case ClassDef::Exception:  result+="a excepcin"; break;
        default: break;
      }
      result+=" est generada de";
      if (single) result+="l siguiente archivo:";
      else result+=" los siguientes archivos:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorSpanish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1820 of file translator_es.h.
    {
      // single is true implies a single file
      QCString result="La documentacin de est";
      switch(compType)
      {
        case ClassDef::Class:      result+="e mdulo"; break;
        case ClassDef::Struct:     result+="e tipo"; break;
        case ClassDef::Union:      result+="a unin"; break;
        case ClassDef::Interface:  result+="a interface"; break;
        case ClassDef::Protocol:   result+="e protocolo"; break;
        case ClassDef::Category:   result+="a categora"; break;
        case ClassDef::Exception:  result+="a excepcin"; break;
        default: break;
      }
      result+=" est generada de";
      if (single) result+="l siguiente archivo:";
      else result+=" los siguientes archivos:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorSpanish::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1387 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "global", "es");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorSpanish::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1883 of file translator_es.h.
    {
      return "Espacio de nombres global";
    }
trGotoDocumentation()
QCString TranslatorSpanish::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 943 of file translator_es.h.
    {
      return "Ir a la documentacin de este archivo.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorSpanish::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 983 of file translator_es.h.
    {
      return "Ir al grfico de jerarqua de clases";
    }
trGotoSourceCode()
QCString TranslatorSpanish::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 937 of file translator_es.h.
    {
      return "Ir al cdigo fuente de este archivo.";
    }
trGotoTextualHierarchy()
QCString TranslatorSpanish::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 988 of file translator_es.h.
    {
      return "Ir al texto de jerarqua de clases";
    }
trGraphicalHierarchy()
QCString TranslatorSpanish::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 978 of file translator_es.h.
    {
      return "Grfico de jerarqua de clases";
    }
trGroup()
QCString TranslatorSpanish::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1360 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "mdulo", "s");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorSpanish::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 456 of file translator_es.h.
    { return "ndice jerrquico"; }
trImplementedFromList()
QCString TranslatorSpanish::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1421 of file translator_es.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorSpanish::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1429 of file translator_es.h.
    {
      return "Implementado en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorSpanish::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 1094 of file translator_es.h.
    {
      return "Grfico de los archivos que directa o "
              "indirectamente incluyen a este archivo:";
    }
trInclDepGraph()
QCString TranslatorSpanish::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 925 of file translator_es.h.
    {
      return "Grfico de dependencias incluidas en "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorSpanish::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1917 of file translator_es.h.
    {
      return "Incluye archivo en "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorSpanish::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 233 of file translator_es.h.
    { return ", incluyendo todos los heredados:"; }
trInheritedByList()
QCString TranslatorSpanish::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 785 of file translator_es.h.
    {
      return "Heredado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorSpanish::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 2022 of file translator_es.h.
    { return members+" heredados de "+what; }
trInheritsList()
QCString TranslatorSpanish::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 777 of file translator_es.h.
    {
      return "Hereda de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorSpanish::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 967 of file translator_es.h.
    {
      return "Valor inicial:";
    }
trInstanceMethods()
QCString TranslatorSpanish::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2074 of file translator_es.h.
    {
      return "Mtodos de instancia";
    }
trInterfaceDocumentation()
QCString TranslatorSpanish::trInterfaceDocumentation () inline override virtual
Implements Translator.
Definition at line 2307 of file translator_es.h.
    {
        return "Documentacin de interfaces";
    }
trInterfaceHierarchy()
QCString TranslatorSpanish::trInterfaceHierarchy () inline override virtual
Implements Translator.
Definition at line 2299 of file translator_es.h.
    {
        return "Jerarqua de interfaces";
    }
trInterfaceHierarchyDescription()
QCString TranslatorSpanish::trInterfaceHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2303 of file translator_es.h.
    {
        return "Este listado de herencia est ordenado de forma general, pero no est en orden alfabtico estricto:";
    }
trInterfaceIndex()
QCString TranslatorSpanish::trInterfaceIndex () inline override virtual
Implements Translator.
Definition at line 2287 of file translator_es.h.
    {
        return "ndice de interfaces";
    }
trInterfaceList()
QCString TranslatorSpanish::trInterfaceList () inline override virtual
Implements Translator.
Definition at line 2291 of file translator_es.h.
    {
        return "Lista de interfaces";
    }
trInterfaceListDescription()
QCString TranslatorSpanish::trInterfaceListDescription () inline override virtual
Implements Translator.
Definition at line 2295 of file translator_es.h.
    {
        return "Esta es la lista de las interfaces con breves descripciones:";
    }
trInterfaces()
QCString TranslatorSpanish::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2091 of file translator_es.h.
    { return "Interfaces exportadas"; }
trInvariant()
QCString TranslatorSpanish::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 961 of file translator_es.h.
    {
      return "Invariante";
    }
trISOLang()
QCString TranslatorSpanish::trISOLang () inline override virtual
Implements Translator.
Definition at line 155 of file translator_es.h.
    {
      return "es";
    }
trLegend()
QCString TranslatorSpanish::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1183 of file translator_es.h.
    {
      return "leyenda";
    }
trLegendDocs()
QCString TranslatorSpanish::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1118 of file translator_es.h.
    {
      return
        "Esta pgina explica cmo interpretar los grficos generados "
        "por doxygen.<p>\n"
        "Considrese el siguiente ejemplo:\n"
        "\\code\n"
        "/*! Clase invisible por truncamiento */\n"
        "class Invisible { };\n\n"
        "/*! Clase truncada, relacin de herencia escondida */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Clase no documentada con comentarios de doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Clase que es heredera usando herencia publica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Plantilla de clases */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Clase que es heredera usando herencia protegida  */\n"
        "class ProtectedBase { };\n\n"
        "/*! Clase que es heredera usando herencia privada  */\n"
        "class PrivateBase { };\n\n"
        "/*! Clase que es usada por la clase heredada */\n"
        "class Used { };\n\n"
        "/*! Superclase que hereda de varias otras clases */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dar como resultado el siguiente grfico:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Las cajas del grfico superior tienen el siguiente significado:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Una caja gris rellena representa la estructura o clase para la cual "
        "se gener el grfico.\n"
        "<li>Una caja con borde negro indica una estructura o clase documentada.\n"
        "<li>Una caja con borde gris indica una estructura o clase no documentada.\n"
        "<li>Una caja con borde rojo indica una estructura o clase documentada"
        " de la que no todas las relaciones de herencia/asociacin se "
        "muestran. Un grfico queda cortado si no encaja dentro de los "
        "lmites especificados."
        "</ul>\n"
        "<p>\n"
        "Las flechas tienen el siguiente significado:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Una flecha azul oscuro se usa para mostrar una relacin de herencia publica entre dos clases.\n"
        "<li>Una flecha verde oscuro se usa para una herencia protegida.\n"
        "<li>Una flecha rojo oscuro se usa para herencia privada.\n"
        "<li>Una flecha prpura discontinua se usa si la clase est contenida o "
        "se usa por otra clase. La flecha est etiquetada por la variable "
        "con que se accede a la clase o estructura apuntada. \n"
        "<li>Una flecha amarilla discontinua indica la relacin entre una instancia de plantilla y la clase de plantilla de la que se ha instanciado."
        " La flecha se etiqueta con los parmetros de plantilla de la instancia.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorSpanish::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 1110 of file translator_es.h.
    {
      return "Leyenda del grfico";
    }
trListOfAllMembers()
QCString TranslatorSpanish::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 221 of file translator_es.h.
    { return "Lista de todos los miembros"; }
trLoading()
QCString TranslatorSpanish::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1877 of file translator_es.h.
    {
      return "Cargando...";
    }
trMainPage()
QCString TranslatorSpanish::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 883 of file translator_es.h.
    { return "Pgina principal"; }
trMember()
QCString TranslatorSpanish::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1378 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "miembro", "s");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorSpanish::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 204 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentacin de campos";
      }
      else
      {
        return "Documentacin de datos miembro";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorSpanish::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 187 of file translator_es.h.
    { return "Documentacin de las enumeraciones miembro de la clase"; }
trMemberFunctionDocumentation()
QCString TranslatorSpanish::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 191 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Documentacin de funciones/procedimientos/procesos miembro";
      }
      else
      {
        return "Documentacin de funciones miembro";
      }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran()
QCString TranslatorSpanish::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1672 of file translator_es.h.
    { return "Documentacin de funciones/subrutinas miembros"; }
trMemberList()
QCString TranslatorSpanish::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 225 of file translator_es.h.
    { return "Lista de los miembros"; }
trMemberTypedefDocumentation()
QCString TranslatorSpanish::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 183 of file translator_es.h.
    { return "Documentacin de los Typedef miembros de la clase"; }
trMethodDocumentation()
QCString TranslatorSpanish::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2081 of file translator_es.h.
    {
      return "Documentacin de mtodos";
    }
trModule()
QCString TranslatorSpanish::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1812 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "mdulo", "s");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorSpanish::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 483 of file translator_es.h.
    { return "Documentacin de mdulos"; }
trModuleIndex()
QCString TranslatorSpanish::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 450 of file translator_es.h.
    { return "ndice de mdulos"; }
trModuleReference()
QCString TranslatorSpanish::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1774 of file translator_es.h.
    {
      QCString result="Referencia del mdulo ";
      result+=namespaceName;
      return result;
    }
trModules()
QCString TranslatorSpanish::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 263 of file translator_es.h.
    { return "Mdulos"; }
trModulesDescription()
QCString TranslatorSpanish::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 438 of file translator_es.h.
    { return "Lista de todos los mdulos:"; }
trModulesIndex()
QCString TranslatorSpanish::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1805 of file translator_es.h.
    { return "ndice de mdulos"; }
trModulesList()
QCString TranslatorSpanish::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1739 of file translator_es.h.
    { return "Lista de mdulos"; }
trModulesListDescription()
QCString TranslatorSpanish::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1743 of file translator_es.h.
    {
      QCString result="Lista de todos los mdulos ";
      if (!extractAll) result+="documentados ";
      result+="con breves descripciones:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorSpanish::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1786 of file translator_es.h.
    {
      QCString result="Lista de todos los miembros del mdulo ";
      if (!extractAll) result+="documentados ";
      result+="con enlaces ";
      if (extractAll)
      {
        result+="a la documentacin del mdulo para cada uno:";
      }
      else
      {
        result+="al mdulo al que pertenecen:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorSpanish::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1782 of file translator_es.h.
    { return "Miembros del mdulo"; }
trMonth()
QCString TranslatorSpanish::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1962 of file translator_es.h.
    {
      static const char *months_short[] = { "ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic" };
      static const char *months_full[]  = { "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      return first_capital? text.mid(0,1).upper()+text.mid(1) : text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorSpanish::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 217 of file translator_es.h.
    { return "Ms..."; }
trNamespace()
QCString TranslatorSpanish::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1349 of file translator_es.h.
    {
      QCString result = createNoun(first_capital, singular, "espacio", "s");
      result+=" de nombres";
      return result;
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorSpanish::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 831 of file translator_es.h.
    { return "Documentacin de espacios de nombres"; }
trNamespaceIndex()
QCString TranslatorSpanish::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 825 of file translator_es.h.
    { return "ndice de espacios de nombres"; }
trNamespaceList()
QCString TranslatorSpanish::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 650 of file translator_es.h.
    { return "Lista de espacios de nombres"; }
trNamespaceListDescription()
QCString TranslatorSpanish::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 654 of file translator_es.h.
    {
      QCString result="Lista de ";
      if (!extractAll) result+="todos ";
      result+="los espacios de nombres documentados, con breves descripciones:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorSpanish::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 811 of file translator_es.h.
    {
      QCString result="Lista de todos los miembros de espacios de nombres ";
      if (!extractAll) result+="documentados ";
      result+="con enlaces a ";
      if (extractAll)
        result+="la documentacin del espacio de nombres de cada miembro:";
      else
        result+="al espacio de nombres al que pertenecen:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorSpanish::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 807 of file translator_es.h.
    { return "Miembros del espacio de nombres "; }
trNamespaceMembersDescriptionTotal()
QCString TranslatorSpanish::trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) inline override virtual
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2638 of file translator_es.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool masculine = SpanishTranslatorUtils::isNamespaceMemberHighlightMasculine(hl);
      QCString result="Lista de ";
      result+=(masculine ? "todos los " : "todas las ");
      QCString singularResult = "";
      QCString pluralResult = "";
      switch (hl)
      {
        case NamespaceMemberHighlight::All:
          singularResult="miembro";
          pluralResult="miembros";
          break;
        case NamespaceMemberHighlight::Functions:
          singularResult="funcin";
          pluralResult="funciones";
          break;
        case NamespaceMemberHighlight::Variables:
          singularResult="variable";
          pluralResult="variables";
          break;
        case NamespaceMemberHighlight::Typedefs:
          singularResult="typedef";
          pluralResult="typedefs";
          break;
        case NamespaceMemberHighlight::Sequences:
          singularResult="secuencia";
          pluralResult="secuencias";
          break;
        case NamespaceMemberHighlight::Dictionaries:
          singularResult="diccionario";
          pluralResult="diccionarios";
          break;
        case NamespaceMemberHighlight::Enums:
          singularResult="enumeracin";
          pluralResult="enumeraciones";
          break;
        case NamespaceMemberHighlight::EnumValues:
          singularResult="valor enumerado";
          pluralResult="valores enumerados";
          break;
        case NamespaceMemberHighlight::Total: // for completeness
          break;
      }
      result+=(pluralResult.isEmpty() ? singularResult+"s" : pluralResult);
      result+="del espacio de nombres ";
      if (!extractAll) result+=(masculine ? "documentados " : "documentadas ");
      result+=" con enlaces ";
      if (extractAll)
        result+="a la documentacin del espacio de nombres de cada " + singularResult + ":";
      else
        result+="a los espacios de nombres a los que pertenecen:";
      return result;
    }
References NamespaceMemberHighlight::All, Config_getBool, NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, QCString::isEmpty(), SpanishTranslatorUtils::isNamespaceMemberHighlightMasculine(), NamespaceMemberHighlight::Sequences, NamespaceMemberHighlight::Total, NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
trNamespaceReference()
QCString TranslatorSpanish::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 713 of file translator_es.h.
    {
      QCString result="Referencia del espacio de nombres ";
      result+=namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorSpanish::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 841 of file translator_es.h.
    { return "Espacios de nombres"; }
trNoMatches()
QCString TranslatorSpanish::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1895 of file translator_es.h.
    {
      return "Nada coincide";
    }
trNote()
QCString TranslatorSpanish::trNote () inline override virtual
Implements Translator.
Definition at line 1002 of file translator_es.h.
    {
      return "Nota";
    }
trOperationDocumentation()
QCString TranslatorSpanish::trOperationDocumentation () inline override virtual
Implements Translator.
Definition at line 2377 of file translator_es.h.
    {
        return "Documentacin de operaciones";
    }
trOperations()
QCString TranslatorSpanish::trOperations () inline override virtual
Implements Translator.
Definition at line 2373 of file translator_es.h.
    {
        return "Operaciones";
    }
trOverloadText()
QCString TranslatorSpanish::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1644 of file translator_es.h.
    {
       return "Esta es una funcin miembro sobrecargada que se "
               "suministra por conveniencia. Difiere de la anterior "
               "funcin solamente en los argumentos que acepta.";
    }
trPackage()
QCString TranslatorSpanish::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1238 of file translator_es.h.
    {
      return "Paquete "+name;
    }
trPackageAttribs()
QCString TranslatorSpanish::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1510 of file translator_es.h.
    {
      return "Atributos de paquete";
    }
trPackageFunctions()
QCString TranslatorSpanish::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1490 of file translator_es.h.
    {
      return "Funciones de paquete";
    }
trPackageList()
QCString TranslatorSpanish::trPackageList () inline override virtual
Implements Translator.
Definition at line 2446 of file translator_es.h.
    { return "Lista de paquetes"; }
trPackageListDescription()
QCString TranslatorSpanish::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1245 of file translator_es.h.
    {
      return "Estos son los paquetes con breves descripciones (si estn disponibles):";
    }
trPackageMembers()
QCString TranslatorSpanish::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1494 of file translator_es.h.
    {
      return "Miembros de paquete";
    }
trPackages()
QCString TranslatorSpanish::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1251 of file translator_es.h.
    {
      return "Paquetes";
    }
trPackageTypes()
QCString TranslatorSpanish::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1482 of file translator_es.h.
    {
      return "Tipos de paquete";
    }
trPage()
QCString TranslatorSpanish::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1369 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "pgina", "s");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorSpanish::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 889 of file translator_es.h.
    { return "pg."; }
trPageIndex()
QCString TranslatorSpanish::trPageIndex () inline override virtual
Implements Translator.
Definition at line 993 of file translator_es.h.
    {
      return "ndice de pginas";
    }
trPanelSynchronisationTooltip()
QCString TranslatorSpanish::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 2039 of file translator_es.h.
    {
      QCString opt = enable ? "habilitar" : "deshabilitar";
      return "pulsar para "+opt+" sincronizacin";
    }
trParameters()
QCString TranslatorSpanish::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 634 of file translator_es.h.
    { return "Parmetros"; }
trPostcondition()
QCString TranslatorSpanish::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 955 of file translator_es.h.
    {
      return "Postcondicin";
    }
trPrecondition()
QCString TranslatorSpanish::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 949 of file translator_es.h.
    {
      return "Precondicin";
    }
trPrivateAttribs()
QCString TranslatorSpanish::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 1049 of file translator_es.h.
    {
      return "Atributos privados";
    }
trPrivateMembers()
QCString TranslatorSpanish::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 741 of file translator_es.h.
    { return "Mtodos privados"; }
trPrivateSlots()
QCString TranslatorSpanish::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 744 of file translator_es.h.
    { return "Slots privados"; }
trPrivateTypes()
QCString TranslatorSpanish::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 1044 of file translator_es.h.
    {
      return "Tipos privados";
    }
trProperties()
QCString TranslatorSpanish::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1209 of file translator_es.h.
    {
      return "Propiedades";
    }
trPropertyDocumentation()
QCString TranslatorSpanish::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1215 of file translator_es.h.
    {
      return "Documentacin de propiedades";
    }
trProtectedAttribs()
QCString TranslatorSpanish::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 1034 of file translator_es.h.
    {
      return "Atributos protegidos";
    }
trProtectedMembers()
QCString TranslatorSpanish::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 732 of file translator_es.h.
    { return "Mtodos protegidos"; }
trProtectedSlots()
QCString TranslatorSpanish::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 735 of file translator_es.h.
    { return "Slots protegidos"; }
trProtectedTypes()
QCString TranslatorSpanish::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 1029 of file translator_es.h.
    {
      return "Tipos protegidos";
    }
trProvidedByCategory()
QCString TranslatorSpanish::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2049 of file translator_es.h.
    {
      return "Proporcionado por la categora @0.";
    }
trPublicAttribs()
QCString TranslatorSpanish::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 1012 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de datos";
      }
      else
      {
        return "Atributos pblicos";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorSpanish::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 720 of file translator_es.h.
    { return "Mtodos pblicos"; }
trPublicSlots()
QCString TranslatorSpanish::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 723 of file translator_es.h.
    { return "Slots pblicos"; }
trPublicTypes()
QCString TranslatorSpanish::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 1007 of file translator_es.h.
    {
      return "Tipos pblicos";
    }
trReferencedBy()
QCString TranslatorSpanish::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 1079 of file translator_es.h.
    {
      return "Referenciado por";
    }
trReferenceManual()
QCString TranslatorSpanish::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 512 of file translator_es.h.
    { return "Manual de referencia"; }
trReferences()
QCString TranslatorSpanish::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1409 of file translator_es.h.
    {
      return "Hace referencia a";
    }
trReimplementedFromList()
QCString TranslatorSpanish::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 793 of file translator_es.h.
    {
      return "Reimplementado de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorSpanish::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 801 of file translator_es.h.
    {
      return "Reimplementado en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorSpanish::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 675 of file translator_es.h.
    { return "Documentacin de clases amigas y funciones relacionadas"; }
trRelatedFunctions()
QCString TranslatorSpanish::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 167 of file translator_es.h.
    { return "Funciones relacionadas"; }
trRelatedPages()
QCString TranslatorSpanish::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 314 of file translator_es.h.
    { return "Pginas relacionadas"; }
trRelatedPagesDescription()
QCString TranslatorSpanish::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 434 of file translator_es.h.
    { return "Lista de toda la documentacin relacionada:"; }
trRelatedSubscript()
QCString TranslatorSpanish::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 171 of file translator_es.h.
    { return "(Observar que estas no son funciones miembro.)"; }
trRelatedSymbolDocumentation()
QCString TranslatorSpanish::trRelatedSymbolDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes.
Supersedes trRelatedFunctionDocumentation
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2486 of file translator_es.h.
    { return "Documentacin de smbolos amigos y relacionados"; }
trRelatedSymbols()
QCString TranslatorSpanish::trRelatedSymbols () inline override virtual
Please translate also updated body of the method trMemberFunctionDocumentation(), now better adapted for VHDL sources documentation.
used in the compound documentation before a list of related symbols.
Supersedes trRelatedFunctions
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2471 of file translator_es.h.
    { return "Smbolos relacionados"; }
trRelatedSymbolsSubscript()
QCString TranslatorSpanish::trRelatedSymbolsSubscript () inline override virtual
subscript for the related symbols
Supersedes trRelatedSubscript
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2478 of file translator_es.h.
    { return "(Observar que estos no son smbolos miembro.)"; }
trRemarks()
QCString TranslatorSpanish::trRemarks () inline override virtual
Implements Translator.
Definition at line 1084 of file translator_es.h.
    {
      return "Comentarios";
    }
trReturns()
QCString TranslatorSpanish::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 626 of file translator_es.h.
    { return "Devuelve"; }
trReturnValues()
QCString TranslatorSpanish::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 878 of file translator_es.h.
    { return "Valores devueltos"; }
trRTFansicp()
QCString TranslatorSpanish::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1307 of file translator_es.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorSpanish::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1316 of file translator_es.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorSpanish::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1322 of file translator_es.h.
    {
      return "ndice";
    }
trRTFTableOfContents()
QCString TranslatorSpanish::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1441 of file translator_es.h.
    {
      return "Tabla de contenidos";
    }
trSearch()
QCString TranslatorSpanish::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 322 of file translator_es.h.
    { return "Buscar"; }
trSearching()
QCString TranslatorSpanish::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1889 of file translator_es.h.
    {
      return "Buscando...";
    }
trSearchMatches()
QCString TranslatorSpanish::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1581 of file translator_es.h.
    {
      return "Coincidencias:";
    }
trSearchResults()
QCString TranslatorSpanish::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1561 of file translator_es.h.
    {
      if (numDocuments==0)
      {
        return "Disculpe, no se encontraron documentos que coincidan con su bsqueda.";
      }
      else if (numDocuments==1)
      {
        return "Se encontr <b>1</b> documento que coincide con su bsqueda.";
      }
      else
      {
        return "Se encontraron <b>$num</b> documentos que coinciden con su bsqueda. "
                "Se muestran los mejores resultados primero.";
      }
    }
trSearchResultsTitle()
QCString TranslatorSpanish::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1548 of file translator_es.h.
    {
      return "Resultados de la bsqueda";
    }
trSeeAlso()
QCString TranslatorSpanish::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 630 of file translator_es.h.
    { return "Ver tambin"; }
trSequenceDocumentation()
QCString TranslatorSpanish::trSequenceDocumentation () inline override virtual
Implements Translator.
Definition at line 2271 of file translator_es.h.
    {
        return "Documentacin de secuencias";
    }
trSequences()
QCString TranslatorSpanish::trSequences () inline override virtual
Implements Translator.
Definition at line 2267 of file translator_es.h.
    {
        return "Secuencias";
    }
trServiceGeneratedFromFiles()
QCString TranslatorSpanish::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 2124 of file translator_es.h.
    {
      // single is true implies a single file
      QCString result="La documentacin de este servicio "
                      "est generada de";
      if (single) result+="l siguiente archivo:"; else result+=" los siguientes archivos:";
      return result;
    }
trServiceReference()
QCString TranslatorSpanish::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 2110 of file translator_es.h.
    {
      QCString result="Referencia a servicios de ";
      result+=sName;
      return result;
    }
trServices()
QCString TranslatorSpanish::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2095 of file translator_es.h.
    { return "Servicios incluidos"; }
trSignals()
QCString TranslatorSpanish::trSignals () inline override virtual
Implements Translator.
Definition at line 726 of file translator_es.h.
    { return "Seales"; }
trSince()
QCString TranslatorSpanish::trSince () inline override virtual
Implements Translator.
Definition at line 1100 of file translator_es.h.
    {
      return "Desde";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorSpanish::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 2133 of file translator_es.h.
    {
      // single is true implies a single file
      QCString result="La documentacin de este singleton "
                      "est generada de";
      if (single) result+="l siguiente archivo:"; else result+=" los siguientes archivos:";
      return result;
    }
trSingletonReference()
QCString TranslatorSpanish::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 2117 of file translator_es.h.
    {
      QCString result="Referencia a singleton de ";
      result+=sName;
      return result;
    }
trSliceInterfaces()
QCString TranslatorSpanish::trSliceInterfaces () inline override virtual
Implements Translator.
Definition at line 2283 of file translator_es.h.
    {
        return "Interfaces";
    }
trSourceFile()
QCString TranslatorSpanish::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1592 of file translator_es.h.
    {
      return "Archivo de cdigo fuente " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorSpanish::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1518 of file translator_es.h.
    {
      return "Atributos estticos de paquete";
    }
trStaticPackageFunctions()
QCString TranslatorSpanish::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1502 of file translator_es.h.
    {
      return "Funciones estticas de paquete";
    }
trStaticPrivateAttribs()
QCString TranslatorSpanish::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 1054 of file translator_es.h.
    {
      return "Atributos estticos privados";
    }
trStaticPrivateMembers()
QCString TranslatorSpanish::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 747 of file translator_es.h.
    { return "Mtodos privados estticos"; }
trStaticProtectedAttribs()
QCString TranslatorSpanish::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 1039 of file translator_es.h.
    {
      return "Atributos estticos protegidos";
    }
trStaticProtectedMembers()
QCString TranslatorSpanish::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 738 of file translator_es.h.
    { return "Mtodos protegidos estticos"; }
trStaticPublicAttribs()
QCString TranslatorSpanish::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 1024 of file translator_es.h.
    {
      return "Atributos pblicos estticos";
    }
trStaticPublicMembers()
QCString TranslatorSpanish::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 729 of file translator_es.h.
    { return "Mtodos pblicos estticos"; }
trStructDocumentation()
QCString TranslatorSpanish::trStructDocumentation () inline override virtual
Implements Translator.
Definition at line 2327 of file translator_es.h.
    {
        return "Documentacin de estructuras de datos";
    }
trStructIndex()
QCString TranslatorSpanish::trStructIndex () inline override virtual
Implements Translator.
Definition at line 2315 of file translator_es.h.
    {
        return "ndice de estructuras de datos";
    }
trStructList()
QCString TranslatorSpanish::trStructList () inline override virtual
Implements Translator.
Definition at line 2319 of file translator_es.h.
    {
        return "Lista de estructuras de datos";
    }
trStructListDescription()
QCString TranslatorSpanish::trStructListDescription () inline override virtual
Implements Translator.
Definition at line 2323 of file translator_es.h.
    {
        return "Esta es la lista de las estructuras de datos con breves descripciones:";
    }
trStructs()
QCString TranslatorSpanish::trStructs () inline override virtual
Implements Translator.
Definition at line 2311 of file translator_es.h.
    {
        return "Estructuras de datos";
    }
trSubprogram()
QCString TranslatorSpanish::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1855 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "subprograma", "s");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorSpanish::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1729 of file translator_es.h.
    { return "Documentacin de funciones/subrutinas"; }
trSubprograms()
QCString TranslatorSpanish::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1723 of file translator_es.h.
    { return "Funciones/subrutinas"; }
trTemplateParameters()
QCString TranslatorSpanish::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 2000 of file translator_es.h.
    { return "Parmetros de plantilla"; }
trTest()
QCString TranslatorSpanish::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1193 of file translator_es.h.
    {
      return "Prueba";
    }
trTestList()
QCString TranslatorSpanish::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1199 of file translator_es.h.
    {
      return "Lista de pruebas";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorSpanish::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 229 of file translator_es.h.
    { return "Lista completa de los miembros de"; }
trTodo()
QCString TranslatorSpanish::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1064 of file translator_es.h.
    {
      return "Tareas pendientes";
    }
trTodoList()
QCString TranslatorSpanish::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 1070 of file translator_es.h.
    {
      return "Lista de tareas pendientes";
    }
trType()
QCString TranslatorSpanish::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1846 of file translator_es.h.
    {
      return createNoun(first_capital, singular, "tipo", "s");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trTypeConstraints()
QCString TranslatorSpanish::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1861 of file translator_es.h.
    {
      return "Restricciones de tipo";
    }
trTypedefDocumentation()
QCString TranslatorSpanish::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 560 of file translator_es.h.
    { return "Documentacin de typedef"; }
trTypedefs()
QCString TranslatorSpanish::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 524 of file translator_es.h.
    { return "typedefs"; }
trTypeDocumentation()
QCString TranslatorSpanish::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1717 of file translator_es.h.
    { return "Documentacin de tipos de datos"; }
trVariableDocumentation()
QCString TranslatorSpanish::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 578 of file translator_es.h.
    { return "Documentacin de variables"; }
trVariables()
QCString TranslatorSpanish::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 542 of file translator_es.h.
    { return "Variables"; }
trVersion()
QCString TranslatorSpanish::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 618 of file translator_es.h.
    { return "Versin"; }
trVhdlType()
QCString TranslatorSpanish::trVhdlType (VhdlSpecifier type, bool single) inline override virtual
VHDL type.
Implements Translator.
Definition at line 2171 of file translator_es.h.
    {
      switch(type)
      {
        case VhdlSpecifier::LIBRARY:
          if (single) return "Biblioteca";
          else        return "Bibliotecas";
        case VhdlSpecifier::PACKAGE:
          if (single) return "Paquete";
          else        return "Paquetes";
        case VhdlSpecifier::SIGNAL:
          if (single) return "Seal";
          else        return "Seales";
        case VhdlSpecifier::COMPONENT:
          if (single) return "Componente";
          else        return "Componentes";
        case VhdlSpecifier::CONSTANT:
          if (single) return "Constante";
          else        return "Constantes";
        case VhdlSpecifier::ENTITY:
          if (single) return "Entidad";
          else        return "Entidades";
        case VhdlSpecifier::TYPE:
          if (single) return "Tipo";
          else        return "Tipos";
        case VhdlSpecifier::SUBTYPE:
          if (single) return "Subtipo";
          else        return "Subtipos";
        case VhdlSpecifier::FUNCTION:
          if (single) return "Funcin";
          else        return "Funciones";
        case VhdlSpecifier::RECORD:
          if (single) return "Registro";
          else        return "Registros";
        case VhdlSpecifier::PROCEDURE:
          if (single) return "Procedimiento";
          else        return "Procedimientos";
        case VhdlSpecifier::ARCHITECTURE:
          if (single) return "Arquitectura";
          else        return "Arquitecturas";
        case VhdlSpecifier::ATTRIBUTE:
          if (single) return "Atributo";
          else        return "Atributos";
        case VhdlSpecifier::PROCESS:
          if (single) return "Proceso";
          else        return "Procesos";
        case VhdlSpecifier::PORT:
          if (single) return "Puerto";
          else        return "Puertos";
        case VhdlSpecifier::USE:
          if (single) return "Clusula de uso";
          else        return "Clusulas de uso";
        case VhdlSpecifier::GENERIC:
          if (single) return "Genrico";
          else        return "Genricos";
        case VhdlSpecifier::PACKAGE_BODY:
          return "Cuerpo del paquete";
        case VhdlSpecifier::UNITS:
          return "Unidades";
        case VhdlSpecifier::SHAREDVARIABLE:
          if (single) return "Variable compartida";
          else        return "Variables compartidas";
        case VhdlSpecifier::VFILE:
          if (single) return "Archivo";
          else        return "Archivos";
        case VhdlSpecifier::GROUP:
          if (single) return "Grupo";
          else        return "Grupos";
        case VhdlSpecifier::INSTANTIATION:
          if (single) return "Instanciacin";
          else        return "Instanciaciones";
        case VhdlSpecifier::ALIAS:
          if (single) return "Alias";
          else        return "Aliases";
        case VhdlSpecifier::CONFIG:
          if (single) return "Configuracin";
          else        return "Configuraciones";
        case VhdlSpecifier::MISCELLANEOUS:
          return "Varios";
        case VhdlSpecifier::UCF_CONST:
          return "Restricciones";
        default:
          return "Clase";
      }
    }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorSpanish::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 614 of file translator_es.h.
    { return "Atencin"; }
trWriteList()
QCString TranslatorSpanish::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 753 of file translator_es.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" y ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_es.h