Doxygen: NamespaceLinkedRefMap Class Reference
NamespaceLinkedRefMap Class Reference
#include <src/namespacedef.h>
Public Member Functions
void writeDeclaration (OutputList &ol, const QCString &title, bool isConstantGroup=false, bool localName=FALSE)
bool declVisible (bool isContantGroup) const
Public Member Functions inherited from LinkedRefMap< const NamespaceDef >
const const NamespaceDef * find (const std::string &key) const
find an object given the key.
const const NamespaceDef * find (const QCString &key) const
find an object given the key.
const const NamespaceDef * find (const char *key) const
find an object given the key.
const NamespaceDef * find (const char *key)
non-const wrapper for find() const
const NamespaceDef * find (const QCString &key)
const NamespaceDef * find (const std::string &key)
non-const wrapper for find() const
bool add (const char *k, const NamespaceDef *obj)
Adds an object reference to the ordered vector if it was not added already.
bool add (const QCString &k, const NamespaceDef *obj)
bool prepend (const char *k, const NamespaceDef *obj)
Prepends an object reference to the ordered vector if it was not added already.
bool prepend (const QCString &key, const NamespaceDef *obj)
bool del (const QCString &key)
Removes an object from the container and deletes it.
Ptr & operator[] (size_t pos)
const Ptr & operator[] (size_t pos) const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
bool empty () const
size_t size () const
void clear ()
Additional Inherited Members
Public Types inherited from LinkedRefMap< const NamespaceDef >
using Ptr
using Vec
using iterator
using const_iterator
using reverse_iterator
using const_reverse_iterator
Detailed Description
Definition at line 45 of file namespacedef.h.
Member Function Documentation
declVisible()
bool NamespaceLinkedRefMap::declVisible (bool isContantGroup) const
Definition at line 1345 of file namespacedef.cpp.
{
  bool found=false;
  for (const auto &nd : *this)
  {
    if (nd->isLinkable() && nd->hasDocumentation())
    {
      SrcLangExt lang = nd->getLanguage();
      if (SrcLangExt::IDL==lang)
      {
        if (isConstantGroup == nd->isConstantGroup())
        {
          found=true;
          break;
        }
      }
      else if (!isConstantGroup) // ensure we only get extra section in IDL
      {
        if (nd->isConstantGroup())
        {
          err("Internal inconsistency: constant group but not IDL?\n");
        }
        found=true;
        break;
      }
    }
  }
  return found;
}
References err, found, and IDL.
Referenced by writeDeclaration().
writeDeclaration()
void NamespaceLinkedRefMap::writeDeclaration (OutputList & ol, const QCString & title, bool isConstantGroup = false, bool localName = FALSE)
Definition at line 1375 of file namespacedef.cpp.
{
  if (empty()) return; // no namespaces in the list
  if (Config_getBool(OPTIMIZE_OUTPUT_VHDL)) return;
  if (!declVisible(isConstantGroup)) return;
  // write list of namespaces
  ol.startMemberHeader(isConstantGroup ? "constantgroups" : "namespaces");
  //bool javaOpt    = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
  //bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  ol.parseText(title);
  ol.endMemberHeader();
  ol.startMemberList();
  for (const auto &nd : *this)
  {
    if (nd->isLinkable() && nd->hasDocumentation())
    {
      SrcLangExt lang = nd->getLanguage();
      if (lang==SrcLangExt::IDL && (isConstantGroup != nd->isConstantGroup()))
          continue; // will be output in another pass, see layout_default.xml
      ol.startMemberDeclaration();
      ol.startMemberItem(nd->anchor(),OutputGenerator::MemberItemType::Normal);
      QCString ct = nd->compoundTypeString();
      ol.docify(ct);
      ol.docify(" ");
      ol.insertMemberAlign();
      QCString name;
      if (localName)
      {
        name = nd->localName();
      }
      else
      {
        name = nd->displayName();
      }
      ol.writeObjectLink(nd->getReference(),nd->getOutputFileBase(),QCString(),name);
      ol.endMemberItem(OutputGenerator::MemberItemType::Normal);
      if (!nd->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
      {
        ol.startMemberDescription(nd->getOutputFileBase());
        ol.generateDoc(nd->briefFile(),nd->briefLine(),nd,nullptr,nd->briefDescription(),FALSE,FALSE,
                       QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
        ol.endMemberDescription();
      }
      ol.endMemberDeclaration(QCString(),QCString());
    }
  }
  ol.endMemberList();
}
References Config_getBool, declVisible(), OutputList::docify(), LinkedRefMap< const NamespaceDef >::empty(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), FALSE, OutputList::generateDoc(), IDL, OutputList::insertMemberAlign(), OutputGenerator::Normal, OutputList::parseText(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), TRUE, and OutputList::writeObjectLink().
The documentation for this class was generated from the following files:
src/namespacedef.h
src/namespacedef.cpp