Doxygen: src/trace.h File Reference
trace.h File Reference
#include "spdlog/spdlog.h"
#include "types.h"
#include "qcstring.h"
#include "construct.h"
Classes
class AutoTrace
Helper class to trace an entry statement at creation and another one at destruction.
struct fmt::formatter< T >
struct fmt::formatter< QCString >
adds support for formatting QCString
struct fmt::formatter< Protection >
adds support for formatting Protected
struct fmt::formatter< Specifier >
adds support for formatting Specifier
struct fmt::formatter< MethodTypes >
adds support for formatting MethodTypes
struct fmt::formatter< RelatesType >
adds support for formatting RelatesType
struct fmt::formatter< Relationship >
adds support for formatting RelationShip
struct fmt::formatter< SrcLangExt >
adds support for formatting SrcLangExt
struct fmt::formatter< MemberType >
adds support for formatting MemberType
struct fmt::formatter< TypeSpecifier >
adds support for formatting TypeSpecifier
struct fmt::formatter< EntryType >
adds support for formatting EntryType
struct fmt::formatter< MemberListType >
adds support for formatting MemberListType
Namespaces
namespace Trace
namespace fmt
Macros
#define ENABLE_TRACING 1
#define ENABLE_SYMBOLRESOLVER_TRACING 0
#define ENABLE_MARKDOWN_TRACING 0
#define ENABLE_DOCPARSER_TRACING 0
#define SPELOG_ACTIVE_LEVEL SPDLOG_LEVEL_INFO
#define TRACE(...)
#define AUTO_TRACE(...)
#define AUTO_TRACE_ADD(...)
#define AUTO_TRACE_EXIT(...)
Functions
void initTracing (const QCString &logFile, bool timing)
void exitTracing ()
QCString Trace::trunc (const QCString &s, size_t numChars=15)
Variables
std::shared_ptr< spdlog::logger > g_tracer
Macro Definition Documentation
AUTO_TRACE
#define AUTO_TRACE (...)
Value:
(void)0
Definition at line 147 of file trace.h.
AUTO_TRACE_ADD
#define AUTO_TRACE_ADD (...)
Value:
(void)0
Definition at line 148 of file trace.h.
AUTO_TRACE_EXIT
#define AUTO_TRACE_EXIT (...)
Value:
(void)0
Definition at line 149 of file trace.h.
ENABLE_DOCPARSER_TRACING
#define ENABLE_DOCPARSER_TRACING 0
Definition at line 31 of file trace.h.
ENABLE_MARKDOWN_TRACING
#define ENABLE_MARKDOWN_TRACING 0
Definition at line 30 of file trace.h.
ENABLE_SYMBOLRESOLVER_TRACING
#define ENABLE_SYMBOLRESOLVER_TRACING 0
Definition at line 29 of file trace.h.
ENABLE_TRACING
#define ENABLE_TRACING 1
Definition at line 21 of file trace.h.
SPELOG_ACTIVE_LEVEL
#define SPELOG_ACTIVE_LEVEL SPDLOG_LEVEL_INFO
Definition at line 37 of file trace.h.
TRACE
#define TRACE (...)
Value:
(void)0
Definition at line 77 of file trace.h.
Referenced by computeVerifiedDotPath(), and readConfiguration().
Function Documentation
exitTracing()
void exitTracing ()
Definition at line 52 of file trace.cpp.
{
  if (g_tracer)
  {
    spdlog::shutdown();
  }
}
References g_tracer.
Referenced by generateOutput(), and stopDoxygen().
initTracing()
void initTracing (const QCString & logFile, bool timing)
Definition at line 22 of file trace.cpp.
{
  if (!logFile.isEmpty())
  {
    std::vector<spdlog::sink_ptr> sinks;
    if (logFile=="stdout")
    {
      sinks.push_back(std::make_shared<spdlog::sinks::stdout_sink_mt>());
    }
    else if (logFile=="stderr")
    {
      sinks.push_back(std::make_shared<spdlog::sinks::stderr_sink_mt>());
    }
    else // normal file
    {
      sinks.push_back(std::make_shared<spdlog::sinks::basic_file_sink_mt>(logFile.str(),true));
    }
    g_tracer = std::make_shared<spdlog::logger>("tracing", sinks.begin(),sinks.end());
    g_tracer->set_level(spdlog::level::trace);
    if (timing)
    {
      g_tracer->set_pattern("[%C-%m-%d %T.%e][%t][%s:%#](%!) %v");
    }
    else
    {
      g_tracer->set_pattern("[%s:%#](%!) %v");
    }
  }
}
References g_tracer, QCString::isEmpty(), and QCString::str().
Referenced by readConfiguration().
Variable Documentation
g_tracer
std::shared_ptr<spdlog::logger> g_tracer extern
Definition at line 20 of file trace.cpp.
Referenced by AutoTrace::add(), AutoTrace::AutoTrace(), AutoTrace::AutoTrace(), exitTracing(), initTracing(), and AutoTrace::~AutoTrace().