Doxygen: MemberDefImpl Class Reference
MemberDefImpl Class Reference
Public Member Functions
MemberDefImpl (const QCString &defFileName, int defLine, int defColumn, const QCString &type, const QCString &name, const QCString &args, const QCString &excp, Protection prot, Specifier virt, bool stat, Relationship related, MemberType t, const ArgumentList &tal, const ArgumentList &al, const QCString &metaData)
~MemberDefImpl () override=default
DefType definitionType () const override
MemberDef * resolveAlias () override
const MemberDef * resolveAlias () const override
CodeSymbolType codeSymbolType () const override
std::unique_ptr< MemberDef > deepCopy () const override
void moveTo (Definition *) override
QCString getOutputFileBase () const override
QCString getReference () const override
QCString anchor () const override
QCString declaration () const override
QCString definition () const override
QCString typeString () const override
QCString argsString () const override
QCString excpString () const override
QCString bitfieldString () const override
QCString extraTypeChars () const override
const QCString & initializer () const override
int initializerLines () const override
TypeSpecifier getMemberSpecifiers () const override
VhdlSpecifier getVhdlSpecifiers () const override
const MemberList * getSectionList (const Definition *) const override
QCString displayDefinition () const override
const ClassDef * getClassDef () const override
ClassDef * getClassDef () override
const FileDef * getFileDef () const override
FileDef * getFileDef () override
const NamespaceDef * getNamespaceDef () const override
NamespaceDef * getNamespaceDef () override
const GroupDef * getGroupDef () const override
GroupDef * getGroupDef () override
const ModuleDef * getModuleDef () const override
ClassDef * accessorClass () const override
QCString getReadAccessor () const override
QCString getWriteAccessor () const override
Grouping::GroupPri_t getGroupPri () const override
QCString getGroupFileName () const override
int getGroupStartLine () const override
bool getGroupHasDocs () const override
QCString qualifiedName () const override
QCString objCMethodName (bool localLink, bool showStatic) const override
Protection protection () const override
Specifier virtualness (int count=0) const override
MemberType memberType () const override
QCString memberTypeName () const override
bool isSignal () const override
bool isSlot () const override
bool isVariable () const override
bool isEnumerate () const override
bool isEnumValue () const override
bool isTypedef () const override
bool isSequence () const override
bool isDictionary () const override
bool isFunction () const override
bool isFunctionPtr () const override
bool isDefine () const override
bool isFriend () const override
bool isDCOP () const override
bool isProperty () const override
bool isEvent () const override
bool isRelated () const override
bool isForeign () const override
bool isStatic () const override
bool isInline () const override
bool isExplicit () const override
bool isMutable () const override
bool isGettable () const override
bool isPrivateGettable () const override
bool isProtectedGettable () const override
bool isSettable () const override
bool isPrivateSettable () const override
bool isProtectedSettable () const override
bool isReadable () const override
bool isWritable () const override
bool isAddable () const override
bool isRemovable () const override
bool isRaisable () const override
bool isFinal () const override
bool isAbstract () const override
bool isOverride () const override
bool isInitonly () const override
bool isOptional () const override
bool isRequired () const override
bool isNonAtomic () const override
bool isCopy () const override
bool isAssign () const override
bool isRetain () const override
bool isWeak () const override
bool isStrong () const override
bool isEnumStruct () const override
bool isUnretained () const override
bool isNew () const override
bool isSealed () const override
bool isImplementation () const override
bool isExternal () const override
bool isTypeAlias () const override
bool isDefault () const override
bool isDelete () const override
bool isNoExcept () const override
bool isAttribute () const override
bool isUNOProperty () const override
bool isReadonly () const override
bool isBound () const override
bool isConstrained () const override
bool isTransient () const override
bool isMaybeVoid () const override
bool isMaybeDefault () const override
bool isMaybeAmbiguous () const override
bool isPublished () const override
bool isTemplateSpecialization () const override
bool isObjCMethod () const override
bool isObjCProperty () const override
bool isCSharpProperty () const override
bool isConstructor () const override
bool isDestructor () const override
bool hasOneLineInitializer () const override
bool hasMultiLineInitializer () const override
bool isCallable () const override
bool isStrongEnumValue () const override
bool livesInsideEnum () const override
bool isSliceLocal () const override
bool isNoDiscard () const override
bool isConstExpr () const override
bool isConstEval () const override
bool isConstInit () const override
int numberOfFlowKeyWords () const override
bool isFriendToHide () const override
bool isNotFriend () const override
bool isFunctionOrSignalSlot () const override
bool isRelatedOrFriend () const override
bool isLinkableInProject () const override
bool isLinkable () const override
bool hasDocumentation () const override
bool hasUserDocumentation () const override
bool isDeleted () const override
bool isBriefSectionVisible () const override
bool isDetailedSectionVisible (MemberListContainer container) const override
bool hasDetailedDescription () const override
bool isFriendClass () const override
bool isDocumentedFriendClass () const override
const MemberDef * reimplements () const override
const MemberVector & reimplementedBy () const override
bool isReimplementedBy (const ClassDef *cd) const override
ClassDef * relatedAlso () const override
bool hasDocumentedEnumValues () const override
const MemberDef * getAnonymousEnumType () const override
bool isDocsForDefinition () const override
const MemberDef * getEnumScope () const override
const MemberVector & enumFieldList () const override
void setEnumBaseType (const QCString &type) override
QCString enumBaseType () const override
bool hasExamples () const override
const ExampleList & getExamples () const override
bool isPrototype () const override
const ArgumentList & argumentList () const override
const ArgumentList & declArgumentList () const override
const ArgumentList & templateArguments () const override
const ArgumentLists & definitionTemplateParameterLists () const override
std::optional< ArgumentList > formalTemplateArguments () const override
int getMemberGroupId () const override
MemberGroup * getMemberGroup () const override
bool fromAnonymousScope () const override
MemberDef * fromAnonymousMember () const override
bool hasCallGraph () const override
bool hasCallerGraph () const override
bool hasReferencesRelation () const override
bool hasReferencedByRelation () const override
bool hasEnumValues () const override
bool hasInlineSource () const override
QCString sourceRefName () const override
const MemberDef * templateMaster () const override
QCString getScopeString () const override
ClassDef * getClassDefOfAnonymousType () const override
bool isTypedefValCached () const override
const ClassDef * getCachedTypedefVal () const override
QCString getCachedTypedefTemplSpec () const override
QCString getCachedResolvedTypedef () const override
MemberDef * memberDefinition () const override
MemberDef * memberDeclaration () const override
const MemberDef * inheritsDocsFrom () const override
const MemberDef * getGroupAlias () const override
ClassDef * category () const override
const MemberDef * categoryRelation () const override
QCString displayName (bool=TRUE) const override
QCString getDeclType () const override
StringVector getLabels (const Definition *container) const override
const ArgumentList & typeConstraints () const override
QCString requiresClause () const override
QCString documentation () const override
QCString briefDescription (bool abbr=FALSE) const override
QCString fieldType () const override
bool isReference () const override
QCString getDeclFileName () const override
int getDeclLine () const override
int getDeclColumn () const override
void setMemberType (MemberType t) override
void setDefinition (const QCString &d) override
void setFileDef (FileDef *fd) override
void setAnchor () override
void setProtection (Protection p) override
void setMemberSpecifiers (TypeSpecifier s) override
void setVhdlSpecifiers (VhdlSpecifier s) override
void mergeMemberSpecifiers (TypeSpecifier s) override
void setInitializer (const QCString &i) override
void setBitfields (const QCString &s) override
void setMaxInitLines (int lines) override
void setMemberClass (ClassDef *cd) override
void setSectionList (const Definition *container, const MemberList *sl) override
void setGroupDef (GroupDef *gd, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs, MemberDef *member=nullptr) override
void setReadAccessor (const QCString &r) override
void setWriteAccessor (const QCString &w) override
void setTemplateSpecialization (bool b) override
void makeRelated () override
void makeForeign () override
void setInheritsDocsFrom (const MemberDef *md) override
void setTagInfo (const TagInfo *i) override
void setArgsString (const QCString &as) override
void setReimplements (MemberDef *md) override
void insertReimplementedBy (MemberDef *md) override
void setRelatedAlso (ClassDef *cd) override
void insertEnumField (MemberDef *md) override
void setEnumScope (MemberDef *md, bool livesInsideEnum=FALSE) override
void setEnumClassScope (ClassDef *cd) override
void setDocumentedEnumValues (bool value) override
void setAnonymousEnumType (const MemberDef *md) override
bool addExample (const QCString &anchor, const QCString &name, const QCString &file) override
void setPrototype (bool p, const QCString &df, int line, int column) override
void setExplicitExternal (bool b, const QCString &df, int line, int column) override
void setDeclFile (const QCString &df, int line, int column) override
void moveArgumentList (std::unique_ptr< ArgumentList > al) override
void moveDeclArgumentList (std::unique_ptr< ArgumentList > al) override
void setDefinitionTemplateParameterLists (const ArgumentLists &lists) override
void setTypeConstraints (const ArgumentList &al) override
void setType (const QCString &t) override
void setAccessorType (ClassDef *cd, const QCString &t) override
void setNamespace (NamespaceDef *nd) override
void setMemberGroup (MemberGroup *grp) override
void setMemberGroupId (int id) override
void makeImplementationDetail () override
void setFromAnonymousScope (bool b) override
void setFromAnonymousMember (MemberDef *m) override
void overrideCallGraph (bool e) override
void overrideCallerGraph (bool e) override
void overrideReferencedByRelation (bool e) override
void overrideReferencesRelation (bool e) override
void overrideEnumValues (bool e) override
void overrideInlineSource (bool e) override
void setTemplateMaster (MemberDef *mt) override
void setFormalTemplateArguments (const ArgumentList &al) override
void addListReference (Definition *d) override
void setDocsForDefinition (bool b) override
void setGroupAlias (const MemberDef *md) override
void cacheTypedefVal (const ClassDef *val, const QCString &templSpec, const QCString &resolvedType) override
void invalidateTypedefValCache () override
void invalidateCachedArgumentTypes () override
void setMemberDefinition (MemberDef *md) override
void setMemberDeclaration (MemberDef *md) override
void copyArgumentNames (const MemberDef *bmd) override
void setCategory (ClassDef *) override
void setCategoryRelation (const MemberDef *) override
void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE) override
void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine) override
void setInbodyDocumentation (const QCString &d, const QCString &inbodyFile, int inbodyLine) override
void setHidden (bool b) override
void setRequiresClause (const QCString &req) override
void incrementFlowKeyWordCount () override
void writeDeclaration (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, const ModuleDef *mod, bool inGroup, int indentLevel, const ClassDef *inheritFrom=nullptr, const QCString &inheritId=QCString()) const override
void writeDocumentation (const MemberList *ml, int memCount, int memTotal, OutputList &ol, const QCString &scopeName, const Definition *container, bool inGroup, bool showEnumValues=FALSE, bool showInline=FALSE) const override
void writeMemberDocSimple (OutputList &ol, const Definition *container) const override
void writeEnumDeclaration (OutputList &typeDecl, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, const ModuleDef *mod) const override
void writeTagFile (TextStream &, bool useQualifiedName, bool showNamespaceMembers) const override
void warnIfUndocumented () const override
void warnIfUndocumentedParams () const override
bool visibleInIndex () const override
void detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const override
std::unique_ptr< MemberDef > createTemplateInstanceMember (const ArgumentList &formalArgs, const std::unique_ptr< ArgumentList > &actualArgs) const override
void findSectionsInDocumentation () override
void writeLink (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, const ModuleDef *mod, bool onlyText=FALSE) const override
void resolveUnnamedParameters (const MemberDef *md) override
void addQualifiers (const StringVector &qualifiers) override
StringVector getQualifiers () const override
ClassDefMutable * getClassDefMutable () override
void setModuleDef (ModuleDef *mod) override
Public Member Functions inherited from DefinitionMixin< MemberDefMutable >
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=nullptr, const char *d=nullptr, bool isSymbol=TRUE)
DefinitionMixin (const DefinitionMixin &other)
DefinitionMixin (DefinitionMixin &&)=delete
DefinitionMixin & operator= (const DefinitionMixin &other)
DefinitionMixin & operator= (DefinitionMixin &&)=delete
~DefinitionMixin () override=default
bool isAlias () const override
const QCString & name () const override
bool isAnonymous () const override
const QCString & localName () const override
QCString symbolName () const override
QCString getSourceFileBase () const override
QCString getSourceAnchor () const override
int docLine () const override
QCString docFile () const override
QCString briefDescriptionAsTooltip () const override
int briefLine () const override
QCString inbodyDocumentation () const override
QCString inbodyFile () const override
int inbodyLine () const override
QCString briefFile () const override
QCString getDefFileName () const override
QCString getDefFileExtension () const override
int getDefLine () const override
int getDefColumn () const override
bool isVisibleInProject () const override
bool isVisible () const override
bool isHidden () const override
bool isArtificial () const override
bool isExported () const override
QCString externalReference (const QCString &relPath) const override
int getStartDefLine () const override
int getStartBodyLine () const override
int getEndBodyLine () const override
const FileDef * getBodyDef () const override
SrcLangExt getLanguage () const override
const GroupList & partOfGroups () const override
bool isLinkableViaGroup () const override
const RefItemVector & xrefListItems () const override
const Definition * findInnerCompound (const QCString &name) const override
Definition * getOuterScope () const override
const MemberVector & getReferencesMembers () const override
const MemberVector & getReferencedByMembers () const override
bool hasSections () const override
bool hasSources () const override
bool hasBriefDescription () const override
QCString id () const override
const SectionRefs & getSectionRefs () const override
void setName (const QCString &name) override
void setId (const QCString &name) override
void setDefFile (const QCString &df, int defLine, int defColumn) override
void setReference (const QCString &r) override
void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList) override
void setBodySegment (int defLine, int bls, int ble) override
void setBodyDef (const FileDef *fd) override
void addSourceReferencedBy (MemberDef *md, const QCString &sourceRefName) override
void addSourceReferences (MemberDef *md, const QCString &sourceRefName) override
void setRefItems (const RefItemVector &sli) override
void mergeRefItems (Definition *def) override
void mergeReferences (const Definition *other) override
void mergeReferencedBy (const Definition *other) override
void addInnerCompound (Definition *def) override
void setOuterScope (Definition *def) override
void setArtificial (bool b) override
void setExported (bool b) override
void setLanguage (SrcLangExt lang) override
void writeSourceDef (OutputList &ol) const override
void writeInlineCode (OutputList &ol, const QCString &scopeName) const override
bool hasSourceRefs () const override
bool hasSourceReffedBy () const override
void writeSourceRefs (OutputList &ol, const QCString &scopeName) const override
void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const override
void makePartOfGroup (GroupDef *gd) override
void writeNavigationPath (OutputList &ol) const override
QCString navigationPathAsString () const override
void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const override
void writeSummaryLinks (OutputList &ol) const override
QCString pathFragment () const override
void writeDocAnchorsToTagFile (TextStream &fs) const override
void setLocalName (const QCString &name) override
void writeToc (OutputList &ol, const LocalToc &lt) const override
void computeTooltip () override
void _setSymbolName (const QCString &name) override
QCString _symbolName () const override
Public Member Functions inherited from MemberDefMutable
Public Member Functions inherited from DefinitionMutable
Public Member Functions inherited from MemberDef
Public Member Functions inherited from Definition
Private Member Functions
void _computeLinkableInProject ()
void _computeIsConstructor ()
void _computeIsDestructor ()
void _writeGroupInclude (OutputList &ol, bool inGroup) const
void _writeMultiLineInitializer (OutputList &ol, const QCString &scopeName) const
void _writeCallGraph (OutputList &ol) const
void _writeCallerGraph (OutputList &ol) const
void _writeReimplements (OutputList &ol) const
bool _isReimplements () const
void _writeReimplementedBy (OutputList &ol) const
size_t _countReimplementedBy () const
void _writeExamples (OutputList &ol) const
void _writeTypeConstraints (OutputList &ol) const
void _writeEnumValues (OutputList &ol, const Definition *container, const QCString &cfname, const QCString &ciname, const QCString &cname) const
void _writeCategoryRelation (OutputList &ol) const
void _writeTagData (const DefType) const
void _writeTemplatePrefix (OutputList &ol, const Definition *def, const ArgumentList &al, bool writeReqClause=true) const
bool _hasVisibleCallGraph () const
bool _hasVisibleCallerGraph () const
bool _isAnonymousBitField () const
void init (Definition *def, const QCString &t, const QCString &a, const QCString &e, Protection p, Specifier v, bool s, Relationship r, MemberType mt, const ArgumentList &tal, const ArgumentList &al, const QCString &meta)
Private Attributes
uint8_t m_isLinkableCached
uint8_t m_isConstructorCached
uint8_t m_isDestructorCached
ClassDef * m_classDef = nullptr
FileDef * m_fileDef = nullptr
NamespaceDef * m_nspace = nullptr
ModuleDef * m_moduleDef = nullptr
const MemberDef * m_enumScope = nullptr
bool m_livesInsideEnum = false
const MemberDef * m_annEnumType = nullptr
MemberVector m_enumFields
MemberDef * m_redefines = nullptr
MemberVector m_redefinedBy
MemberDef * m_memDef = nullptr
MemberDef * m_memDec = nullptr
ClassDef * m_relatedAlso = nullptr
ExampleList m_examples
QCString m_type
QCString m_accessorType
ClassDef * m_accessorClass = nullptr
QCString m_args
QCString m_def
QCString m_anc
Specifier m_virt = Specifier::Normal
Protection m_prot = Protection::Public
QCString m_decl
QCString m_bitfields
QCString m_read
QCString m_write
QCString m_exception
QCString m_initializer
QCString m_extraTypeChars
QCString m_enumBaseType
QCString m_requiresClause
int m_initLines = 0
TypeSpecifier m_memSpec
VhdlSpecifier m_vhdlSpec
MemberType m_mtype = MemberType::Define
int m_maxInitLines = 0
int m_userInitLines = 0
MemberDef * m_annMemb = nullptr
ArgumentList m_defArgList
ArgumentList m_declArgList
ArgumentList m_tArgList
ArgumentList m_typeConstraints
MemberDef * m_templateMaster = nullptr
std::optional< ArgumentList > m_formalTemplateArguments
ArgumentLists m_defTmpArgLists
QCString m_metaData
ClassDef * m_cachedAnonymousType = nullptr
std::map< const Definition *, const MemberList * > m_sectionMap
const MemberDef * m_groupAlias = nullptr
int m_grpId = 0
MemberGroup * m_memberGroup = nullptr
GroupDef * m_group = nullptr
Grouping::GroupPri_t m_grouppri = Grouping::GROUPING_AUTO_DEF
QCString m_groupFileName
int m_groupStartLine = 0
MemberDef * m_groupMember = nullptr
bool m_isTypedefValCached = false
const ClassDef * m_cachedTypedefValue = nullptr
QCString m_cachedTypedefTemplSpec
QCString m_cachedResolvedType
const MemberDef * m_docProvider = nullptr
QCString m_explicitOutputFileBase
StringVector m_qualifiers
bool m_implOnly = false
bool m_hasDocumentedParams = false
bool m_hasDocumentedReturnType = false
bool m_isDMember = false
Relationship m_related = Relationship::Member
bool m_stat = false
bool m_proto = false
bool m_docEnumValues = false
bool m_annScope = false
bool m_hasDetailedDescriptionCached = false
bool m_detailedDescriptionCachedValue = false
bool m_hasCallGraph = false
bool m_hasCallerGraph = false
bool m_hasReferencedByRelation = false
bool m_hasReferencesRelation = false
bool m_hasInlineSource = false
bool m_hasEnumValues = false
bool m_explExt = false
bool m_tspec = false
bool m_groupHasDocs = false
bool m_docsForDefinition = false
ClassDef * m_category = nullptr
const MemberDef * m_categoryRelation = nullptr
QCString m_declFileName
int m_declLine = -1
int m_declColumn = -1
int m_numberOfFlowKW = 0
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Detailed Description
Definition at line 53 of file memberdef.cpp.
Constructor & Destructor Documentation
MemberDefImpl()
MemberDefImpl::MemberDefImpl (const QCString & df, int dl, int dc, const QCString & t, const QCString & na, const QCString & a, const QCString & e, Protection p, Specifier v, bool s, Relationship r, MemberType mt, const ArgumentList & tal, const ArgumentList & al, const QCString & meta)
Creates a new member definition.
Parameters
df File containing the definition of this member.
dl Line at which the member definition was found.
dc Column at which the member definition was found.
t A string representing the type of the member.
na A string representing the name of the member.
a A string representing the arguments of the member.
e A string representing the throw clause of the members.
p The protection context of the member, possible values are: Public, Protected, Private.
v The degree of 'virtualness' of the member, possible values are: Normal, Virtual, Pure.
s A boolean that is true iff the member is static.
r The relationship between the class and the member.
mt The kind of member. See MemberType for a list of all types.
tal The template arguments of this member.
al The arguments of this member. This is a structured form of the string past as argument a.
meta Slice metadata.
Definition at line 1432 of file memberdef.cpp.
                      : DefinitionMixin(df,dl,dc,removeRedundantWhiteSpace(na))
{
  //printf("MemberDefImpl::MemberDef(%s)\n",qPrint(na));
  init(this,t,a,e,p,v,s,r,mt,tal,al,meta);
  m_isLinkableCached    = 0;
  m_isConstructorCached = 0;
  m_isDestructorCached  = 0;
}
References DefinitionMixin< MemberDefMutable >::DefinitionMixin(), init(), m_isConstructorCached, m_isDestructorCached, m_isLinkableCached, and removeRedundantWhiteSpace().
Referenced by deepCopy(), isConstructor(), isDestructor(), isLinkableInProject(), and ~MemberDefImpl().
~MemberDefImpl()
MemberDefImpl::~MemberDefImpl () override default
References MemberDefImpl().
Member Function Documentation
_computeIsConstructor()
void MemberDefImpl::_computeIsConstructor () private
Definition at line 4652 of file memberdef.cpp.
{
  m_isConstructorCached=1; // FALSE
  if (getClassDef())
  {
    if (m_isDMember) // for D
    {
      m_isConstructorCached = name()=="this" ? 2 : 1;
      return;
    }
    else if (getLanguage()==SrcLangExt::PHP) // for PHP
    {
      m_isConstructorCached = name()=="__construct" ? 2 : 1;
      return;
    }
    else if (name()=="__init__" &&
             getLanguage()==SrcLangExt::Python) // for Python
    {
      m_isConstructorCached = 2; // TRUE
      return;
    }
    else // for other languages
    {
      QCString locName = getClassDef()->localName();
      int i=locName.find('<');
      if (i==-1) // not a template class
      {
        m_isConstructorCached = name()==locName ? 2 : 1;
      }
      else
      {
        m_isConstructorCached = name()==locName.left(i) ? 2 : 1;
      }
      return;
    }
  }
}
References QCString::find(), getClassDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), QCString::left(), Definition::localName(), m_isConstructorCached, m_isDMember, DefinitionMixin< MemberDefMutable >::name(), PHP, and Python.
Referenced by isConstructor().
_computeIsDestructor()
void MemberDefImpl::_computeIsDestructor () private
Definition at line 4702 of file memberdef.cpp.
{
  bool isDestructor = false;
  if (m_isDMember) // for D
  {
    isDestructor = name()=="~this";
  }
  else if (getLanguage()==SrcLangExt::PHP) // for PHP
  {
    isDestructor = name()=="__destruct";
  }
  else if (name()=="__del__" &&
           getLanguage()==SrcLangExt::Python) // for Python
  {
    isDestructor = true;
  }
  else if (getLanguage()==SrcLangExt::Fortran) // for Fortran
  {
    isDestructor = typeString()=="final";
  }
  else // other languages
  {
    isDestructor =
           (name().find('~')!=-1 || name().find('!')!=-1)  // The ! is for C++/CLI
           && name().find("operator")==-1;
  }
  m_isDestructorCached = isDestructor ? 2 : 1;
}
References QCString::find(), Fortran, DefinitionMixin< MemberDefMutable >::getLanguage(), isDestructor(), m_isDestructorCached, m_isDMember, DefinitionMixin< MemberDefMutable >::name(), PHP, Python, and typeString().
Referenced by isDestructor().
_computeLinkableInProject()
void MemberDefImpl::_computeLinkableInProject () private
Definition at line 1786 of file memberdef.cpp.
{
  AUTO_TRACE("name={}",qualifiedName());
  bool extractStatic  = Config_getBool(EXTRACT_STATIC);
  bool extractPrivateVirtual = Config_getBool(EXTRACT_PRIV_VIRTUAL);
  m_isLinkableCached = 2; // linkable
  //printf("MemberDefImpl::isLinkableInProject(name=%s)\n",qPrint(name()));
  if (isHidden())
  {
    AUTO_TRACE_ADD("is hidden");
    m_isLinkableCached = 1;
    return;
  }
  if (templateMaster())
  {
    AUTO_TRACE_ADD("has master template");
    m_isLinkableCached = templateMaster()->isLinkableInProject() ? 2 : 1;
    return;
  }
  if (isAnonymous())
  {
    AUTO_TRACE_ADD("name invalid");
    m_isLinkableCached = 1; // not a valid or a dummy name
    return;
  }
  if (!hasDocumentation() || isReference())
  {
    AUTO_TRACE_ADD("no docs or reference");
    m_isLinkableCached = 1; // no documentation
    return;
  }
  const GroupDef *groupDef = getGroupDef();
  const ModuleDef *moduleDef = getModuleDef();
  const ClassDef *classDef = getClassDef();
  if (groupDef && !groupDef->isLinkableInProject())
  {
    AUTO_TRACE_ADD("in not linkable group");
    m_isLinkableCached = 1; // group but group not linkable
    return;
  }
  if (!groupDef && classDef && !classDef->isLinkableInProject())
  {
    AUTO_TRACE_ADD("in not linkable class");
    m_isLinkableCached = 1; // in class but class not linkable
    return;
  }
  if (!groupDef && moduleDef && !moduleDef->isLinkableInProject())
  {
    AUTO_TRACE_ADD("in not linkable module");
    m_isLinkableCached = 1; // in module but module not linkable
    return;
  }
  const NamespaceDef *nspace = getNamespaceDef();
  const FileDef *fileDef = getFileDef();
  if (!groupDef && nspace /*&& m_related==Relationship::Member*/ && !nspace->isLinkableInProject()
      && (fileDef==nullptr || !fileDef->isLinkableInProject()))
  {
    AUTO_TRACE_ADD("in not linkable namespace");
    m_isLinkableCached = 1; // in namespace but namespace not linkable
    return;
  }
  if (!groupDef && !nspace &&
      /*m_related==Relationship::Member &&*/ !classDef &&
      fileDef && !fileDef->isLinkableInProject())
  {
    AUTO_TRACE_ADD("in not linkable file");
    m_isLinkableCached = 1; // in file (and not in namespace) but file not linkable
    return;
  }
  if ((!protectionLevelVisible(m_prot) && m_mtype!=MemberType::Friend) &&
       !(m_prot==Protection::Private && (m_virt!=Specifier::Normal || isOverride() || isFinal()) && extractPrivateVirtual))
  {
    AUTO_TRACE_ADD("private and invisible");
    m_isLinkableCached = 1; // hidden due to protection
    return;
  }
  if (m_stat && classDef==nullptr && !extractStatic)
  {
    AUTO_TRACE_ADD("static and invisible");
    m_isLinkableCached = 1; // hidden due to staticness
    return;
  }
  AUTO_TRACE_ADD("linkable");
  return; // linkable!
}
References AUTO_TRACE, AUTO_TRACE_ADD, Config_getBool, Friend, getClassDef(), getFileDef(), getGroupDef(), getModuleDef(), getNamespaceDef(), hasDocumentation(), DefinitionMixin< MemberDefMutable >::isAnonymous(), isFinal(), DefinitionMixin< MemberDefMutable >::isHidden(), Definition::isLinkableInProject(), isOverride(), isReference(), m_isLinkableCached, m_mtype, m_prot, m_stat, m_virt, Normal, Private, protectionLevelVisible(), qualifiedName(), and templateMaster().
Referenced by isLinkableInProject().
_countReimplementedBy()
size_t MemberDefImpl::_countReimplementedBy () const private
Definition at line 3041 of file memberdef.cpp.
{
  const MemberVector &bml=reimplementedBy();
  size_t count=0;
  for (const auto &bmd : bml)
  {
    const ClassDef *bcd=bmd->getClassDef();
    // count the members that directly inherit from md and for
    // which the member and class are visible in the docs.
    if ( bcd && bmd->isLinkable() && bcd->isLinkable() )
    {
      count++;
    }
  }
  return count;
}
References Definition::isLinkable(), and reimplementedBy().
Referenced by _writeReimplementedBy(), and hasDetailedDescription().
_hasVisibleCallerGraph()
bool MemberDefImpl::_hasVisibleCallerGraph () const private
Definition at line 5674 of file memberdef.cpp.
{
  bool enabled = m_hasCallerGraph &&
         (isFunction() || isSlot() || isSignal()) &&
         Config_getBool(HAVE_DOT);
  if (enabled)
  {
    bool trivial = DotCallGraph::isTrivial(this,TRUE);
    return !trivial;
  }
  return FALSE;
}
References Config_getBool, FALSE, isFunction(), isSignal(), isSlot(), DotCallGraph::isTrivial(), m_hasCallerGraph, and TRUE.
Referenced by _writeCallerGraph(), and hasDetailedDescription().
_hasVisibleCallGraph()
bool MemberDefImpl::_hasVisibleCallGraph () const private
Definition at line 5656 of file memberdef.cpp.
{
  bool enabled = m_hasCallGraph &&
         (isFunction() || isSlot() || isSignal()) &&
         Config_getBool(HAVE_DOT);
  if (enabled)
  {
    bool trivial = DotCallGraph::isTrivial(this,FALSE);
    return !trivial;
  }
  return FALSE;
}
References Config_getBool, FALSE, isFunction(), isSignal(), isSlot(), DotCallGraph::isTrivial(), and m_hasCallGraph.
Referenced by _writeCallGraph(), and hasDetailedDescription().
_isAnonymousBitField()
bool MemberDefImpl::_isAnonymousBitField () const private
Definition at line 2217 of file memberdef.cpp.
{
  return !m_bitfields.isEmpty() && name().startsWith("__pad"); // anonymous bitfield
}
References m_bitfields, DefinitionMixin< MemberDefMutable >::name(), and QCString::startsWith().
Referenced by warnIfUndocumented(), and writeDeclaration().
_isReimplements()
bool MemberDefImpl::_isReimplements () const private
Definition at line 2968 of file memberdef.cpp.
{
  const MemberDef *bmd=reimplements();
  const ClassDef *bcd=nullptr;
  if (bmd && (bcd=bmd->getClassDef()))
  {
    // write class that contains a member that is reimplemented by this one
    if (bcd->isLinkable())
    {
      return true;
    }
  }
  return false;
}
References MemberDef::getClassDef(), Definition::isLinkable(), and reimplements().
Referenced by hasDetailedDescription().
_writeCallerGraph()
void MemberDefImpl::_writeCallerGraph (OutputList & ol) const private
Definition at line 2946 of file memberdef.cpp.
{
  if (_hasVisibleCallerGraph())
  {
    DotCallGraph callerGraph(this, TRUE);
    if (callerGraph.isTooBig())
    {
       warn_uncond("Caller graph for '%s' not generated, too many nodes (%d), threshold is %d. Consider increasing DOT_GRAPH_MAX_NODES.\n",
           qPrint(qualifiedName()), callerGraph.numNodes(), Config_getInt(DOT_GRAPH_MAX_NODES));
    }
    else if (!callerGraph.isTrivial())
    {
      msg("Generating caller graph for function %s\n",qPrint(qualifiedName()));
      ol.disable(OutputType::Man);
      ol.startCallGraph();
      ol.parseText(theTranslator->trCallerGraph());
      ol.endCallGraph(callerGraph);
      ol.enableAll();
    }
  }
}
References _hasVisibleCallerGraph(), Config_getInt, OutputList::disable(), OutputList::enableAll(), OutputList::endCallGraph(), DotCallGraph::isTooBig(), DotCallGraph::isTrivial(), Man, msg(), DotCallGraph::numNodes(), OutputList::parseText(), qPrint(), qualifiedName(), OutputList::startCallGraph(), theTranslator, Translator::trCallerGraph(), TRUE, and warn_uncond.
Referenced by writeDocumentation().
_writeCallGraph()
void MemberDefImpl::_writeCallGraph (OutputList & ol) const private
Definition at line 2923 of file memberdef.cpp.
{
  // write call graph
  if (_hasVisibleCallGraph())
  {
    DotCallGraph callGraph(this,FALSE);
    if (callGraph.isTooBig())
    {
       warn_uncond("Call graph for '%s' not generated, too many nodes (%d), threshold is %d. Consider increasing DOT_GRAPH_MAX_NODES.\n",
           qPrint(qualifiedName()), callGraph.numNodes(), Config_getInt(DOT_GRAPH_MAX_NODES));
    }
    else if (!callGraph.isTrivial())
    {
      msg("Generating call graph for function %s\n",qPrint(qualifiedName()));
      ol.disable(OutputType::Man);
      ol.startCallGraph();
      ol.parseText(theTranslator->trCallGraph());
      ol.endCallGraph(callGraph);
      ol.enableAll();
    }
  }
}
References _hasVisibleCallGraph(), Config_getInt, OutputList::disable(), OutputList::enableAll(), OutputList::endCallGraph(), FALSE, DotCallGraph::isTooBig(), DotCallGraph::isTrivial(), Man, msg(), DotCallGraph::numNodes(), OutputList::parseText(), qPrint(), qualifiedName(), OutputList::startCallGraph(), theTranslator, Translator::trCallGraph(), and warn_uncond.
Referenced by writeDocumentation().
_writeCategoryRelation()
void MemberDefImpl::_writeCategoryRelation (OutputList & ol) const private
Definition at line 3117 of file memberdef.cpp.
{
  if (getClassDef()) // this should be a member of a class/category
  {
    //printf("%s: category %s relation %s class=%s categoryOf=%s\n",
    //    qPrint(name()),
    //    m_category ? qPrint(m_category->name()) : "<none>",
    //    m_categoryRelation ? qPrint(m_categoryRelation->name()) : "<none>",
    //    qPrint(m_classDef->name()),
    //    m_classDef->categoryOf() ? qPrint(m_classDef->categoryOf()->name()) : "<none>"
    //    );
    QCString text;
    QCString ref;
    QCString file;
    QCString anc;
    QCString name;
    int i=-1;
    if (m_categoryRelation && m_categoryRelation->isLinkable())
    {
      if (m_category)
      {
        // this member is in a normal class and implements method categoryRelation from category
        // so link to method 'categoryRelation' with 'provided by category 'category' text.
        text = theTranslator->trProvidedByCategory();
        name = m_category->displayName();
      }
      else if (getClassDef()->categoryOf())
      {
        // this member is part of a category so link to the corresponding class member of the class we extend
        // so link to method 'categoryRelation' with 'extends class 'classDef->categoryOf()'
        text = theTranslator->trExtendsClass();
        name = getClassDef()->categoryOf()->displayName();
      }
      i=text.find("@0");
      if (i!=-1)
      {
        const MemberDef *md = m_categoryRelation;
        ref  = md->getReference();
        file = md->getOutputFileBase();
        anc  = md->anchor();
      }
    }
    if (i!=-1 && !name.isEmpty())
    {
      ol.startParagraph();
      ol.parseText(text.left(i));
      ol.writeObjectLink(ref,file,anc,name);
      ol.parseText(text.mid(i+2));
      ol.endParagraph();
    }
  }
}
References Definition::anchor(), ClassDef::categoryOf(), Definition::displayName(), OutputList::endParagraph(), QCString::find(), getClassDef(), Definition::getOutputFileBase(), Definition::getReference(), QCString::left(), m_category, m_categoryRelation, QCString::mid(), Definition::name(), OutputList::parseText(), OutputList::startParagraph(), theTranslator, Translator::trExtendsClass(), Translator::trProvidedByCategory(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
_writeEnumValues()
void MemberDefImpl::_writeEnumValues (OutputList & ol, const Definition * container, const QCString & cfname, const QCString & ciname, const QCString & cname) const private
Definition at line 3191 of file memberdef.cpp.
{
  // For enum, we also write the documented enum values
  if (isEnumerate())
  {
    bool first=true;
    //printf("** %s: enum values=%zu\n",qPrint(name()),enumFieldList().size());
    bool hasInits = false;
    if (hasEnumValues())
    {
      for (const auto &fmd : enumFieldList())
      {
        if (fmd->isLinkable())
        {
          if (!fmd->initializer().isEmpty())
          {
            hasInits = true;
            break;
          }
        }
      }
    }
    for (const auto &fmd : enumFieldList())
    {
      //printf("Enum %p: isLinkable()=%d\n",fmd,fmd->isLinkable());
      if (fmd->isLinkable())
      {
        if (first)
        {
          ol.startDescTable(theTranslator->trEnumerationValues(),hasInits);
          first=false;
        }
        ol.startDescTableRow();
        ol.addIndexItem(fmd->name(),ciname);
        ol.addIndexItem(ciname,fmd->name());
        ol.startDescTableTitle();
        ol.startDoxyAnchor(cfname,cname,fmd->anchor(),fmd->name(),fmd->argsString());
        ol.addLabel(cfname,fmd->anchor());
        ol.docify(fmd->name());
        ol.disableAllBut(OutputType::Man);
        ol.writeString(" ");
        ol.enableAll();
        ol.endDoxyAnchor(cfname,fmd->anchor());
        ol.endDescTableTitle();
        if (hasInits)
        {
          ol.startDescTableInit();
          if (!fmd->initializer().isEmpty())
          {
            QCString initStr = fmd->initializer().stripWhiteSpace();
            if (initStr.startsWith("=")) initStr = initStr.mid(1).stripWhiteSpace();
            ol.disableAllBut(OutputType::Man);
            ol.writeString("(");
            ol.enableAll();
            ol.docify(initStr);
            ol.disableAllBut(OutputType::Man);
            ol.writeString(")");
            ol.enableAll();
          }
          ol.endDescTableInit();
        }
        ol.startDescTableData();
        bool hasBrief = !fmd->briefDescription().isEmpty();
        bool hasDetails = !fmd->documentation().isEmpty();
        if (hasBrief)
        {
          ol.generateDoc(fmd->briefFile(),fmd->briefLine(),
              getOuterScope()?getOuterScope():container,
              fmd,fmd->briefDescription(),TRUE,FALSE,
              QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
        }
        if (hasDetails)
        {
          ol.generateDoc(fmd->docFile(),fmd->docLine(),
              getOuterScope()?getOuterScope():container,
              fmd,fmd->documentation()+"\n",TRUE,FALSE,
              QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
        }
        ol.endDescTableData();
        ol.endDescTableRow();
      }
    }
    if (!first)
    {
      ol.endDescTable();
    }
  }
}
References OutputList::addIndexItem(), OutputList::addLabel(), Definition::briefDescription(), Config_getBool, OutputList::disableAllBut(), OutputList::docify(), Definition::documentation(), OutputList::enableAll(), OutputList::endDescTable(), OutputList::endDescTableData(), OutputList::endDescTableInit(), OutputList::endDescTableRow(), OutputList::endDescTableTitle(), OutputList::endDoxyAnchor(), enumFieldList(), FALSE, OutputList::generateDoc(), Definition::getOuterScope(), DefinitionMixin< MemberDefMutable >::getOuterScope(), hasEnumValues(), isEnumerate(), Man, QCString::mid(), OutputList::startDescTable(), OutputList::startDescTableData(), OutputList::startDescTableInit(), OutputList::startDescTableRow(), OutputList::startDescTableTitle(), OutputList::startDoxyAnchor(), QCString::startsWith(), QCString::stripWhiteSpace(), theTranslator, Translator::trEnumerationValues(), TRUE, and OutputList::writeString().
Referenced by writeDocumentation().
_writeExamples()
void MemberDefImpl::_writeExamples (OutputList & ol) const private
Definition at line 3170 of file memberdef.cpp.
{
  // write the list of examples that use this member
  if (hasExamples())
  {
    ol.startExamples();
    ol.startDescForItem();
    writeExamples(ol,m_examples);
    ol.endDescForItem();
    ol.endExamples();
  }
}
References OutputList::endDescForItem(), OutputList::endExamples(), hasExamples(), m_examples, OutputList::startDescForItem(), OutputList::startExamples(), and writeExamples().
Referenced by writeDocumentation().
_writeGroupInclude()
void MemberDefImpl::_writeGroupInclude (OutputList & ol, bool inGroup) const private
Definition at line 3364 of file memberdef.cpp.
{
  // only write out the include file if this is not part of a class or file
  // definition
  bool showGroupedMembInc = Config_getBool(SHOW_GROUPED_MEMB_INC);
  const FileDef *fd = getFileDef();
  QCString nm;
  if (fd) nm = getFileDef()->docName();
  if (inGroup && fd && showGroupedMembInc && !nm.isEmpty())
  {
    ol.startParagraph();
    ol.startTypewriter();
    SrcLangExt lang = getLanguage();
    bool isIDLorJava = lang==SrcLangExt::IDL || lang==SrcLangExt::Java;
    if (isIDLorJava)
    {
      ol.docify("import ");
    }
    else
    {
      ol.docify("#include ");
    }
    if (isIDLorJava) ol.docify("\""); else ol.docify("<");
    if (fd->isLinkable())
    {
      ol.writeObjectLink(fd->getReference(),fd->getOutputFileBase(),fd->anchor(),nm);
    }
    else
    {
      ol.docify(nm);
    }
    if (isIDLorJava) ol.docify("\""); else ol.docify(">");
    ol.endTypewriter();
    ol.endParagraph();
  }
}
References Definition::anchor(), Config_getBool, OutputList::docify(), FileDef::docName(), OutputList::endParagraph(), OutputList::endTypewriter(), getFileDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), Definition::getOutputFileBase(), Definition::getReference(), IDL, QCString::isEmpty(), Definition::isLinkable(), Java, OutputList::startParagraph(), OutputList::startTypewriter(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
_writeMultiLineInitializer()
void MemberDefImpl::_writeMultiLineInitializer (OutputList & ol, const QCString & scopeName) const private
Definition at line 3405 of file memberdef.cpp.
{
    //printf("md=%s initLines=%d init='%s'\n",qPrint(name()),initLines,qPrint(init));
    ol.startBold();
    if (m_mtype==MemberType::Define)
      ol.parseText(theTranslator->trDefineValue());
    else
      ol.parseText(theTranslator->trInitialValue());
    ol.endBold();
    QCString langCorrected = getDefFileExtension();
    SrcLangExt srcLangExt = getLanguageFromFileName(getDefFileExtension());
    if (srcLangExt == SrcLangExt::Lex)
    {
      langCorrected = ".doxygen_lex_c";
      srcLangExt = SrcLangExt::Cpp;
    }
    auto intf = Doxygen::parserManager->getCodeParser(langCorrected);
    intf->resetCodeParserState();
    auto &codeOL = ol.codeGenerators();
    codeOL.startCodeFragment("DoxyCode");
    intf->parseCode(codeOL,scopeName,m_initializer,srcLangExt,Config_getBool(STRIP_CODE_COMMENTS),FALSE,QCString(),getFileDef(),
                     -1,-1,TRUE,this,FALSE,this);
    codeOL.endCodeFragment("DoxyCode");
}
References OutputList::codeGenerators(), Config_getBool, Cpp, Define, OutputList::endBold(), FALSE, ParserManager::getCodeParser(), DefinitionMixin< MemberDefMutable >::getDefFileExtension(), getFileDef(), getLanguageFromFileName(), Lex, m_initializer, m_mtype, Doxygen::parserManager, OutputList::parseText(), OutputList::startBold(), OutputCodeList::startCodeFragment(), theTranslator, Translator::trDefineValue(), Translator::trInitialValue(), and TRUE.
Referenced by writeDocumentation().
_writeReimplementedBy()
void MemberDefImpl::_writeReimplementedBy (OutputList & ol) const private
Definition at line 3058 of file memberdef.cpp.
{
  const MemberVector &bml=reimplementedBy();
  size_t count = _countReimplementedBy();
  if (count>0)
  {
    auto replaceFunc = [&bml,&ol](size_t entryIndex)
    {
      size_t cnt=0;
      auto it = bml.begin();
      // find the entryIndex-th documented entry in the inheritance list.
      const MemberDef *bmd = nullptr;
      const ClassDef *bcd = nullptr;
      while (it!=bml.end())
      {
        bmd = *it;
        bcd = bmd->getClassDef();
        if ( bmd->isLinkable() && bcd->isLinkable())
        {
          if (cnt==entryIndex) break;
          cnt++;
        }
        ++it;
      }
      if (bcd && bmd) // write link for marker
      {
        //ol.writeObjectLink(bcd->getReference(),bcd->getOutputFileBase(),
        //    bmd->anchor(),bcd->name());
        ol.writeObjectLink(bmd->getReference(),bmd->getOutputFileBase(),
            bmd->anchor(),bcd->displayName());
        if (bmd->isLinkableInProject() )
        {
          writePageRef(ol,bmd->getOutputFileBase(),bmd->anchor());
        }
      }
    };
    QCString reimplInLine;
    if (m_virt==Specifier::Pure || (getClassDef() && getClassDef()->compoundType()==ClassDef::Interface))
    {
      reimplInLine = theTranslator->trImplementedInList(static_cast<int>(count));
    }
    else
    {
      reimplInLine = theTranslator->trReimplementedInList(static_cast<int>(count));
    }
    // write the list of classes that overwrite this member
    ol.startParagraph();
    writeMarkerList(ol,
                    reimplInLine.str(),
                    count,
                    replaceFunc);
    ol.endParagraph();
  }
}
References _countReimplementedBy(), Definition::anchor(), MemberVector::begin(), Definition::displayName(), MemberVector::end(), OutputList::endParagraph(), MemberDef::getClassDef(), getClassDef(), Definition::getOutputFileBase(), Definition::getReference(), ClassDef::Interface, Definition::isLinkable(), Definition::isLinkableInProject(), m_virt, Pure, reimplementedBy(), OutputList::startParagraph(), QCString::str(), theTranslator, Translator::trImplementedInList(), Translator::trReimplementedInList(), writeMarkerList(), OutputList::writeObjectLink(), and writePageRef().
Referenced by writeDocumentation().
_writeReimplements()
void MemberDefImpl::_writeReimplements (OutputList & ol) const private
Definition at line 2982 of file memberdef.cpp.
{
  const MemberDef *bmd=reimplements();
  const ClassDef *bcd=nullptr;
  if (bmd && (bcd=bmd->getClassDef()))
  {
    // write class that contains a member that is reimplemented by this one
    if (bcd->isLinkable())
    {
      ol.startParagraph();
      QCString reimplFromLine;
      if (bmd->virtualness()!=Specifier::Pure && bcd->compoundType()!=ClassDef::Interface)
      {
        reimplFromLine = theTranslator->trReimplementedFromList(1);
      }
      else
      {
        reimplFromLine = theTranslator->trImplementedFromList(1);
      }
      int markerPos = reimplFromLine.find("@0");
      if (markerPos!=-1) // should always pass this.
      {
        ol.parseText(reimplFromLine.left(markerPos)); //text left from marker
        if (bmd->isLinkable()) // replace marker with link
        {
          //Definition *bd=bmd->group;
          //if (bd==0) bd=bcd;
          ol.writeObjectLink(bmd->getReference(),bmd->getOutputFileBase(),
              bmd->anchor(),bcd->displayName());
          //ol.writeObjectLink(bcd->getReference(),bcd->getOutputFileBase(),
          //    bmd->anchor(),bcd->name());
          if ( bmd->isLinkableInProject() )
          {
            writePageRef(ol,bmd->getOutputFileBase(),bmd->anchor());
          }
        }
        else
        {
          ol.writeObjectLink(bcd->getReference(),bcd->getOutputFileBase(),
              QCString(),bcd->displayName());
          if (bcd->isLinkableInProject()/* && !Config_getBool(PDF_HYPERLINKS)*/ )
          {
            writePageRef(ol,bcd->getOutputFileBase(),bcd->anchor());
          }
        }
        ol.parseText(reimplFromLine.right(
              reimplFromLine.length()-markerPos-2)); // text right from marker
      }
      else
      {
        err("translation error: no marker in trReimplementsFromList()\n");
      }
      ol.endParagraph();
    }
  }
}
References Definition::anchor(), ClassDef::compoundType(), Definition::displayName(), OutputList::endParagraph(), err, QCString::find(), MemberDef::getClassDef(), Definition::getOutputFileBase(), Definition::getReference(), ClassDef::Interface, Definition::isLinkable(), Definition::isLinkableInProject(), QCString::left(), QCString::length(), OutputList::parseText(), Pure, reimplements(), QCString::right(), OutputList::startParagraph(), theTranslator, Translator::trImplementedFromList(), Translator::trReimplementedFromList(), MemberDef::virtualness(), OutputList::writeObjectLink(), and writePageRef().
Referenced by writeDocumentation().
_writeTagData()
void MemberDefImpl::_writeTagData (const DefType) const private
_writeTemplatePrefix()
void MemberDefImpl::_writeTemplatePrefix (OutputList & ol, const Definition * def, const ArgumentList & al, bool writeReqClause = true) const private
Definition at line 2169 of file memberdef.cpp.
{
  ol.docify("template<");
  for (auto it = al.begin(); it!=al.end();)
  {
    Argument a = *it;
    linkifyText(TextGeneratorOLImpl(ol), // out
        def,                     // scope
        getFileDef(),            // fileScope
        this,                    // self
        a.type,                  // text
        FALSE                    // autoBreak
        );
    ol.docify(" ");
    ol.docify(a.name);
    if (a.defval.length()!=0)
    {
      ol.docify(" = ");
      ol.docify(a.defval);
    }
    ++it;
    if (it!=al.end()) ol.docify(", ");
  }
  ol.docify("> ");
  if (writeReqClause && !m_requiresClause.isEmpty())
  {
    ol.lineBreak();
    ol.docify("requires ");
    linkifyText(TextGeneratorOLImpl(ol), // out
        def,                     // scope
        getFileDef(),            // fileScope
        this,                    // self
        m_requiresClause,  // text
        FALSE                    // autoBreak
        );
  }
}
References ArgumentList::begin(), Argument::defval, OutputList::docify(), ArgumentList::end(), FALSE, getFileDef(), QCString::length(), OutputList::lineBreak(), linkifyText(), m_requiresClause, Argument::name, and Argument::type.
Referenced by writeDeclaration(), and writeDocumentation().
_writeTypeConstraints()
void MemberDefImpl::_writeTypeConstraints (OutputList & ol) const private
Definition at line 3183 of file memberdef.cpp.
{
  if (m_typeConstraints.hasParameters())
  {
    writeTypeConstraints(ol,this,m_typeConstraints);
  }
}
References m_typeConstraints, and writeTypeConstraints().
Referenced by writeDocumentation().
accessorClass()
ClassDef * MemberDefImpl::accessorClass () const override virtual
Implements MemberDef.
Definition at line 4893 of file memberdef.cpp.
{
  return m_accessorClass;
}
References m_accessorClass.
addExample()
bool MemberDefImpl::addExample (const QCString & anchor, const QCString & name, const QCString & file) override virtual
Implements MemberDefMutable.
Definition at line 1624 of file memberdef.cpp.
{
  //printf("%s::addExample(%s,%s,%s)\n",qPrint(name()),anchor,nameStr,file);
  return m_examples.inSort(Example(anchor,nameStr,file));
}
References anchor(), and m_examples.
addListReference()
void MemberDefImpl::addListReference (Definition * d) override virtual
Implements MemberDefMutable.
Definition at line 4482 of file memberdef.cpp.
{
  bool optimizeOutputForC = Config_getBool(OPTIMIZE_OUTPUT_FOR_C);
  //bool hideScopeNames     = Config_getBool(HIDE_SCOPE_NAMES);
  //bool optimizeOutputJava = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
  //bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  SrcLangExt lang = getLanguage();
  if (!isLinkableInProject()) return;
  QCString memLabel;
  if (optimizeOutputForC)
  {
    memLabel=theTranslator->trGlobal(TRUE,TRUE);
  }
  else if (lang==SrcLangExt::Fortran)
  {
    memLabel=theTranslator->trSubprogram(TRUE,TRUE);
  }
  else
  {
    memLabel=theTranslator->trMember(TRUE,TRUE);
  }
  QCString memName = name();
  Definition *pd=getOuterScope();
  QCString pdName = pd->definitionType()==Definition::TypeClass ?
                    (toClassDef(pd))->displayName() : pd->name();
  QCString sep = getLanguageSpecificSeparator(lang,TRUE);
  QCString memArgs;
  if (!isRelated()
      /* && commented out as a result of bug 597016
      (
       (!hideScopeNames &&                    // there is a scope
        pd && pd!=Doxygen::globalScope)       // and we can show it
       ||
       (pd=getClassDef())                     // it's a class so we
                                              // show the scope anyway
      )
      */
     )
  {
    if (isObjCMethod())
    {
      memName = "[" + pd->name() + " " + name() + "]";
    }
    else
    {
      if (pd!=Doxygen::globalScope) memName.prepend(pdName+sep);
      memArgs = argsString();
    }
  }
  const RefItemVector &xrefItems = xrefListItems();
  if (sep!="::")
  {
    memName = substitute(memName,"::",sep);
  }
  addRefItem(xrefItems,
        qualifiedName()+argsString(), // argsString is needed for overloaded functions (see bug 609624)
        memLabel,
        getOutputFileBase()+"#"+anchor(),memName,memArgs,pd);
}
References addRefItem(), anchor(), argsString(), Config_getBool, Definition::definitionType(), displayName(), Fortran, DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), DefinitionMixin< MemberDefMutable >::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, isLinkableInProject(), isObjCMethod(), isRelated(), Definition::name(), DefinitionMixin< MemberDefMutable >::name(), QCString::prepend(), qualifiedName(), substitute(), theTranslator, toClassDef(), Translator::trGlobal(), Translator::trMember(), Translator::trSubprogram(), TRUE, Definition::TypeClass, and DefinitionMixin< MemberDefMutable >::xrefListItems().
addQualifiers()
void MemberDefImpl::addQualifiers (const StringVector & qualifiers) override virtual
Implements MemberDefMutable.
Definition at line 5826 of file memberdef.cpp.
{
  for (const auto &sx : qualifiers)
  {
    bool alreadyAdded = std::find(m_qualifiers.begin(), m_qualifiers.end(), sx) != m_qualifiers.end();
    if (!alreadyAdded)
    {
      m_qualifiers.push_back(sx);
    }
  }
}
References m_qualifiers.
anchor()
QCString MemberDefImpl::anchor () const override virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 1763 of file memberdef.cpp.
{
  QCString result=m_anc;
  if (m_groupAlias)     return m_groupAlias->anchor();
  if (m_templateMaster) return m_templateMaster->anchor();
  if (m_enumScope && m_enumScope!=this) // avoid recursion for C#'s public enum E { E, F }
  {
    result.prepend(m_enumScope->anchor());
  }
  if (getGroupDef())
  {
    if (m_groupMember)
    {
      result=m_groupMember->anchor();
    }
    else if (getReference().isEmpty())
    {
      result.prepend("g");
    }
  }
  return result;
}
References getGroupDef(), getReference(), m_anc, m_enumScope, m_groupAlias, m_groupMember, m_templateMaster, and QCString::prepend().
Referenced by addExample(), addListReference(), getOutputFileBase(), writeDeclaration(), writeDocumentation(), writeLink(), writeMemberDocSimple(), and writeTagFile().
argsString()
QCString MemberDefImpl::argsString () const override virtual
Implements MemberDef.
Definition at line 5029 of file memberdef.cpp.
{
  return m_args;
}
References m_args.
Referenced by addListReference(), isFunctionPtr(), sourceRefName(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), writeMemberDocSimple(), and writeTagFile().
argumentList()
const ArgumentList & MemberDefImpl::argumentList () const override virtual
Implements MemberDef.
Definition at line 5568 of file memberdef.cpp.
{
  return m_defArgList;
}
References m_defArgList.
Referenced by detectUndocumentedParams(), and warnIfUndocumentedParams().
bitfieldString()
QCString MemberDefImpl::bitfieldString () const override virtual
Implements MemberDef.
Definition at line 5039 of file memberdef.cpp.
{
  return m_bitfields;
}
References m_bitfields.
briefDescription()
QCString MemberDefImpl::briefDescription (bool abbreviate = FALSE) const override virtual
Returns the brief description of this definition. This can include commands.
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 6277 of file memberdef.cpp.
{
  if (m_templateMaster)
  {
    return m_templateMaster->briefDescription(abbr);
  }
  else
  {
    return DefinitionMixin::briefDescription(abbr);
  }
}
References DefinitionMixin< Base >::briefDescription(), and m_templateMaster.
Referenced by findSectionsInDocumentation(), hasDetailedDescription(), writeDeclaration(), writeDocumentation(), and writeMemberDocSimple().
cacheTypedefVal()
void MemberDefImpl::cacheTypedefVal (const ClassDef * val, const QCString & templSpec, const QCString & resolvedType) override virtual
Implements MemberDefMutable.
Definition at line 6044 of file memberdef.cpp.
{
  m_isTypedefValCached=TRUE;
  m_cachedTypedefValue=val;
  m_cachedTypedefTemplSpec=templSpec;
  m_cachedResolvedType=resolvedType;
  //printf("MemberDefImpl::cacheTypedefVal=%s m_impl=%p\n",qPrint(m_cachedResolvedType),m_impl);
}
References m_cachedResolvedType, m_cachedTypedefTemplSpec, m_cachedTypedefValue, m_isTypedefValCached, and TRUE.
category()
ClassDef * MemberDefImpl::category () const override virtual
Implements MemberDef.
Definition at line 6004 of file memberdef.cpp.
{
  return m_category;
}
References m_category.
categoryRelation()
const MemberDef * MemberDefImpl::categoryRelation () const override virtual
Implements MemberDef.
Definition at line 6014 of file memberdef.cpp.
{
  return m_categoryRelation;
}
References m_categoryRelation.
codeSymbolType()
CodeSymbolType MemberDefImpl::codeSymbolType () const override virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 6357 of file memberdef.cpp.
{
  switch (memberType())
  {
    case MemberType::Define:      return CodeSymbolType::Define;
    case MemberType::Function:    return CodeSymbolType::Function;
    case MemberType::Variable:    return CodeSymbolType::Variable;
    case MemberType::Typedef:     return CodeSymbolType::Typedef;
    case MemberType::Enumeration: return CodeSymbolType::Enumeration;
    case MemberType::EnumValue:   return CodeSymbolType::EnumValue;
    case MemberType::Signal:      return CodeSymbolType::Signal;
    case MemberType::Slot:        return CodeSymbolType::Slot;
    case MemberType::Friend:      return CodeSymbolType::Friend;
    case MemberType::DCOP:        return CodeSymbolType::DCOP;
    case MemberType::Property:    return CodeSymbolType::Property;
    case MemberType::Event:       return CodeSymbolType::Event;
    case MemberType::Interface:   return CodeSymbolType::Interface;
    case MemberType::Service:     return CodeSymbolType::Service;
    case MemberType::Sequence:    return CodeSymbolType::Sequence;
    case MemberType::Dictionary:  return CodeSymbolType::Dictionary;
  }
  return CodeSymbolType::Default;
}
References DCOP, Default, Define, Dictionary, Enumeration, EnumValue, Event, Friend, Function, Interface, memberType(), Property, Sequence, Service, Signal, Slot, Typedef, and Variable.
copyArgumentNames()
void MemberDefImpl::copyArgumentNames (const MemberDef * bmd) override virtual
Implements MemberDefMutable.
Definition at line 6053 of file memberdef.cpp.
{
  {
    const ArgumentList &srcAl = bmd->argumentList();
    ArgumentList &dstAl = m_defArgList;
    auto srcIt = srcAl.begin();
    auto dstIt = dstAl.begin();
    while ( srcIt!=srcAl.end() && dstIt!=dstAl.end())
    {
      Argument &argDst       = *dstIt;
      const Argument &argSrc = *srcIt;
      argDst.name = argSrc.name;
      argDst.docs = argSrc.docs;
      ++srcIt;
      ++dstIt;
    }
  }
  {
    const ArgumentList &srcAl = bmd->declArgumentList();
    ArgumentList &dstAl = m_declArgList;
    auto srcIt = srcAl.begin();
    auto dstIt = dstAl.begin();
    while ( srcIt!=srcAl.end() && dstIt!=dstAl.end())
    {
      Argument &argDst       = *dstIt;
      const Argument &argSrc = *srcIt;
      argDst.name = argSrc.name;
      argDst.docs = argSrc.docs;
      ++srcIt;
      ++dstIt;
    }
  }
}
References MemberDef::argumentList(), ArgumentList::begin(), MemberDef::declArgumentList(), Argument::docs, ArgumentList::end(), m_declArgList, m_defArgList, and Argument::name.
createTemplateInstanceMember()
std::unique_ptr< MemberDef > MemberDefImpl::createTemplateInstanceMember (const ArgumentList & formalArgs, const std::unique_ptr< ArgumentList > & actualArgs) const override virtual
Implements MemberDef.
Definition at line 4406 of file memberdef.cpp.
{
  //printf("  Member %s %s %s\n",qPrint(typeString()),qPrint(name()),qPrint(argsString()));
  std::unique_ptr<ArgumentList> actualArgList = std::make_unique<ArgumentList>(m_defArgList);
  if (!m_defArgList.empty())
  {
    // replace formal arguments with actuals
    for (Argument &arg : *actualArgList)
    {
      arg.type = substituteTemplateArgumentsInString(arg.type,formalArgs,actualArgs.get());
    }
    actualArgList->setTrailingReturnType(
       substituteTemplateArgumentsInString(actualArgList->trailingReturnType(),formalArgs,actualArgs.get()));
  }
  QCString methodName=name();
  if (methodName.startsWith("operator ")) // conversion operator
  {
    methodName=substituteTemplateArgumentsInString(methodName,formalArgs,actualArgs.get());
  }
  auto imd = createMemberDef(
                       getDefFileName(),getDefLine(),getDefColumn(),
                       substituteTemplateArgumentsInString(m_type,formalArgs,actualArgs.get()),
                       methodName,
                       substituteTemplateArgumentsInString(m_args,formalArgs,actualArgs.get()),
                       m_exception, m_prot,
                       m_virt, m_stat, m_related, m_mtype,
                       ArgumentList(), ArgumentList(), ""
                   );
  auto mmd = toMemberDefMutable(imd.get());
  mmd->moveArgumentList(std::move(actualArgList));
  mmd->setDefinition(substituteTemplateArgumentsInString(m_def,formalArgs,actualArgs.get()));
  mmd->setBodyDef(getBodyDef());
  mmd->setBodySegment(getDefLine(),getStartBodyLine(),getEndBodyLine());
  mmd->setFormalTemplateArguments(formalArgs);
  // TODO: init other member variables (if needed).
  // TODO: reimplemented info
  return imd;
}
References createMemberDef(), DefinitionMixin< MemberDefMutable >::getBodyDef(), DefinitionMixin< MemberDefMutable >::getDefColumn(), DefinitionMixin< MemberDefMutable >::getDefFileName(), DefinitionMixin< MemberDefMutable >::getDefLine(), DefinitionMixin< MemberDefMutable >::getEndBodyLine(), DefinitionMixin< MemberDefMutable >::getStartBodyLine(), m_args, m_def, m_defArgList, m_exception, m_mtype, m_prot, m_related, m_stat, m_type, m_virt, DefinitionMixin< MemberDefMutable >::name(), QCString::startsWith(), substituteTemplateArgumentsInString(), and toMemberDefMutable().
declaration()
QCString MemberDefImpl::declaration () const override virtual
Implements MemberDef.
Definition at line 5009 of file memberdef.cpp.
{
  return m_decl;
}
References m_decl.
declArgumentList()
const ArgumentList & MemberDefImpl::declArgumentList () const override virtual
Implements MemberDef.
Definition at line 5573 of file memberdef.cpp.
{
  return m_declArgList;
}
References m_declArgList.
Referenced by detectUndocumentedParams(), and warnIfUndocumentedParams().
deepCopy()
std::unique_ptr< MemberDef > MemberDefImpl::deepCopy () const override virtual
Implements MemberDef.
Definition at line 1445 of file memberdef.cpp.
{
  std::unique_ptr<MemberDefImpl> result(new MemberDefImpl(
        getDefFileName(),getDefLine(),getDefColumn(),m_type,localName(),m_args,m_exception,
        m_prot,m_virt,m_stat,m_related,m_mtype,m_tArgList,m_defArgList,m_metaData));
  // first copy base members
  result->DefinitionMixin<MemberDefMutable>::operator=(*this);
  // then copy other members
  result->m_typeConstraints                = m_typeConstraints                ;
  result->m_declArgList                    = m_declArgList                    ;
  result->m_classDef                       = m_classDef                       ;
  result->m_fileDef                        = m_fileDef                        ;
  result->m_moduleDef                      = m_moduleDef                      ;
  result->m_nspace                         = m_nspace                         ;
  result->m_enumScope                      = m_enumScope                      ;
  result->m_livesInsideEnum                = m_livesInsideEnum                ;
  result->m_annEnumType                    = m_annEnumType                    ;
  result->m_enumFields                     = m_enumFields                     ;
  result->m_redefines                      = m_redefines                      ;
  result->m_redefinedBy                    = m_redefinedBy                    ;
  result->m_memDef                         = m_memDef                         ;
  result->m_memDec                         = m_memDec                         ;
  result->m_relatedAlso                    = m_relatedAlso                    ;
  result->m_examples                       = m_examples                       ;
  result->m_accessorType                   = m_accessorType                   ;
  result->m_accessorClass                  = m_accessorClass                  ;
  result->m_def                            = m_def                            ;
  result->m_anc                            = m_anc                            ;
  result->m_decl                           = m_decl                           ;
  result->m_bitfields                      = m_bitfields                      ;
  result->m_read                           = m_read                           ;
  result->m_write                          = m_write                          ;
  result->m_exception                      = m_exception                      ;
  result->m_initializer                    = m_initializer                    ;
  result->m_extraTypeChars                 = m_extraTypeChars                 ;
  result->m_enumBaseType                   = m_enumBaseType                   ;
  result->m_requiresClause                 = m_requiresClause                 ;
  result->m_initLines                      = m_initLines                      ;
  result->m_memSpec                        = m_memSpec                        ;
  result->m_vhdlSpec                       = m_vhdlSpec                       ;
  result->m_maxInitLines                   = m_maxInitLines                   ;
  result->m_userInitLines                  = m_userInitLines                  ;
  result->m_annMemb                        = m_annMemb                        ;
  result->m_defArgList                     = m_defArgList                     ;
  result->m_declArgList                    = m_declArgList                    ;
  result->m_tArgList                       = m_tArgList                       ;
  result->m_typeConstraints                = m_typeConstraints                ;
  result->m_templateMaster                 = m_templateMaster                 ;
  result->m_formalTemplateArguments        = m_formalTemplateArguments        ;
  result->m_defTmpArgLists                 = m_defTmpArgLists                 ;
  result->m_cachedAnonymousType            = m_cachedAnonymousType            ;
  result->m_sectionMap                     = m_sectionMap                     ;
  result->m_groupAlias                     = m_groupAlias                     ;
  result->m_grpId                          = m_grpId                          ;
  result->m_memberGroup                    = m_memberGroup                    ;
  result->m_group                          = m_group                          ;
  result->m_grouppri                       = m_grouppri                       ;
  result->m_groupFileName                  = m_groupFileName                  ;
  result->m_groupStartLine                 = m_groupStartLine                 ;
  result->m_groupMember                    = m_groupMember                    ;
  result->m_isTypedefValCached             = m_isTypedefValCached             ;
  result->m_cachedTypedefValue             = m_cachedTypedefValue             ;
  result->m_cachedTypedefTemplSpec         = m_cachedTypedefTemplSpec         ;
  result->m_cachedResolvedType             = m_cachedResolvedType             ;
  result->m_docProvider                    = m_docProvider                    ;
  result->m_explicitOutputFileBase         = m_explicitOutputFileBase         ;
  result->m_qualifiers                     = m_qualifiers                     ;
  result->m_implOnly                       = m_implOnly                       ;
  result->m_hasDocumentedParams            = m_hasDocumentedParams            ;
  result->m_hasDocumentedReturnType        = m_hasDocumentedReturnType        ;
  result->m_isDMember                      = m_isDMember                      ;
  result->m_proto                          = m_proto                          ;
  result->m_docEnumValues                  = m_docEnumValues                  ;
  result->m_annScope                       = m_annScope                       ;
  result->m_hasDetailedDescriptionCached   = m_hasDetailedDescriptionCached   ;
  result->m_detailedDescriptionCachedValue = m_detailedDescriptionCachedValue ;
  result->m_hasCallGraph                   = m_hasCallGraph                   ;
  result->m_hasCallerGraph                 = m_hasCallerGraph                 ;
  result->m_hasReferencedByRelation        = m_hasReferencedByRelation        ;
  result->m_hasReferencesRelation          = m_hasReferencesRelation          ;
  result->m_hasEnumValues                  = m_hasEnumValues                  ;
  result->m_hasInlineSource                = m_hasInlineSource                ;
  result->m_explExt                        = m_explExt                        ;
  result->m_tspec                          = m_tspec                          ;
  result->m_groupHasDocs                   = m_groupHasDocs                   ;
  result->m_docsForDefinition              = m_docsForDefinition              ;
  result->m_category                       = m_category                       ;
  result->m_categoryRelation               = m_categoryRelation               ;
  result->m_declFileName                   = m_declFileName                   ;
  result->m_declLine                       = m_declLine                       ;
  result->m_declColumn                     = m_declColumn                     ;
  result->m_numberOfFlowKW                 = m_numberOfFlowKW                 ;
  result->setDefinitionTemplateParameterLists(m_defTmpArgLists);
  result->m_isLinkableCached    = 0;
  result->m_isConstructorCached = 0;
  result->m_isDestructorCached  = 0;
  return result;
}
References DefinitionMixin< MemberDefMutable >::getDefColumn(), DefinitionMixin< MemberDefMutable >::getDefFileName(), DefinitionMixin< MemberDefMutable >::getDefLine(), DefinitionMixin< MemberDefMutable >::localName(), m_accessorClass, m_accessorType, m_anc, m_annEnumType, m_annMemb, m_annScope, m_args, m_bitfields, m_cachedAnonymousType, m_cachedResolvedType, m_cachedTypedefTemplSpec, m_cachedTypedefValue, m_category, m_categoryRelation, m_classDef, m_decl, m_declArgList, m_declColumn, m_declFileName, m_declLine, m_def, m_defArgList, m_defTmpArgLists, m_detailedDescriptionCachedValue, m_docEnumValues, m_docProvider, m_docsForDefinition, m_enumBaseType, m_enumFields, m_enumScope, m_examples, m_exception, m_explExt, m_explicitOutputFileBase, m_extraTypeChars, m_fileDef, m_formalTemplateArguments, m_group, m_groupAlias, m_groupFileName, m_groupHasDocs, m_groupMember, m_grouppri, m_groupStartLine, m_grpId, m_hasCallerGraph, m_hasCallGraph, m_hasDetailedDescriptionCached, m_hasDocumentedParams, m_hasDocumentedReturnType, m_hasEnumValues, m_hasInlineSource, m_hasReferencedByRelation, m_hasReferencesRelation, m_implOnly, m_initializer, m_initLines, m_isDMember, m_isTypedefValCached, m_livesInsideEnum, m_maxInitLines, m_memberGroup, m_memDec, m_memDef, m_memSpec, m_metaData, m_moduleDef, m_mtype, m_nspace, m_numberOfFlowKW, m_prot, m_proto, m_qualifiers, m_read, m_redefinedBy, m_redefines, m_related, m_relatedAlso, m_requiresClause, m_sectionMap, m_stat, m_tArgList, m_templateMaster, m_tspec, m_type, m_typeConstraints, m_userInitLines, m_vhdlSpec, m_virt, m_write, and MemberDefImpl().
definition()
QCString MemberDefImpl::definition () const override virtual
Implements MemberDef.
Definition at line 5014 of file memberdef.cpp.
{
  return m_def;
}
References m_def.
Referenced by displayDefinition(), setAnchor(), and writeDocumentation().
definitionTemplateParameterLists()
const ArgumentLists & MemberDefImpl::definitionTemplateParameterLists () const override virtual
Implements MemberDef.
Definition at line 5631 of file memberdef.cpp.
{
  return m_defTmpArgLists;
}
References m_defTmpArgLists.
definitionType()
DefType MemberDefImpl::definitionType () const inline override virtual
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Definition at line 64 of file memberdef.cpp.
{ return TypeMember; }
References definitionType(), and Definition::TypeMember.
Referenced by definitionType().
detectUndocumentedParams()
void MemberDefImpl::detectUndocumentedParams (bool hasParamCommand, bool hasReturnCommand) const override virtual
Implements MemberDef.
Definition at line 4170 of file memberdef.cpp.
{
  bool isPython = getLanguage()==SrcLangExt::Python;
  // this function is called while parsing the documentation. A member can have multiple
  // documentation blocks, which could be handled by multiple threads, hence this guard.
  std::lock_guard<std::mutex> lock(g_detectUndocumentedParamsMutex);
  if (!m_hasDocumentedParams && hasParamCommand)
  {
    //printf("%s:hasDocumentedParams=TRUE;\n",qPrint(name()));
    m_hasDocumentedParams = true;
  }
  else if (!m_hasDocumentedParams)
  {
    const ArgumentList &al     = argumentList();
    const ArgumentList &declAl = declArgumentList();
    bool allDoc=TRUE; // no parameter => all parameters are documented
    if ( // member has parameters
        al.hasParameters()  // with at least one parameter (that is not void)
       )
    {
      // see if all parameters have documentation
      for (auto it = al.begin(); it!=al.end() && allDoc; ++it)
      {
        Argument a = *it;
        if (!a.name.isEmpty() && a.type!="void" &&
            !(isPython && (a.name=="self" || a.name=="cls"))
           )
        {
          allDoc = !a.docs.isEmpty();
        }
        //printf("a->type=%s a->name=%s doc=%s\n",
        //        qPrint(a->type),qPrint(a->name),qPrint(a->docs));
      }
      if (!allDoc && declAl.empty()) // try declaration arguments as well
      {
        allDoc=true;
        for (auto it = al.begin(); it!=al.end() && allDoc; ++it)
        {
          Argument a = *it;
          if (!a.name.isEmpty() && a.type!="void" &&
              !(isPython && (a.name=="self" || a.name=="cls"))
             )
          {
            allDoc = !a.docs.isEmpty();
          }
          //printf("a->name=%s doc=%s\n",qPrint(a->name),qPrint(a->docs));
        }
      }
    }
    if (allDoc)
    {
      //printf("%s:hasDocumentedParams=TRUE;\n",qPrint(name()));
      m_hasDocumentedParams = true;
    }
  }
  //printf("Member %s hasDocumentedReturnType=%d hasReturnCommand=%d\n",
  //    qPrint(name()),m_hasDocumentedReturnType,hasReturnCommand);
  m_hasDocumentedReturnType = m_hasDocumentedReturnType || hasReturnCommand;
}
References argumentList(), ArgumentList::begin(), declArgumentList(), Argument::docs, ArgumentList::empty(), ArgumentList::end(), g_detectUndocumentedParamsMutex, DefinitionMixin< MemberDefMutable >::getLanguage(), ArgumentList::hasParameters(), QCString::isEmpty(), m_hasDocumentedParams, m_hasDocumentedReturnType, Argument::name, Python, TRUE, and Argument::type.
displayDefinition()
QCString MemberDefImpl::displayDefinition () const override virtual
Implements MemberDef.
Definition at line 3289 of file memberdef.cpp.
{
  QCString ldef = definition();
  QCString title = name();
  if (isEnumerate())
  {
    if (isAnonymous())
    {
      ldef = title = "anonymous enum";
      if (!m_enumBaseType.isEmpty())
      {
        ldef+=" : "+m_enumBaseType;
      }
    }
    else
    {
      ldef.prepend("enum ");
      if (isSliceLocal())
      {
        ldef.prepend("local ");
      }
    }
  }
  else if (isEnumValue())
  {
    if (isAnonymous())
    {
      ldef=ldef.mid(2);
    }
  }
  std::string sdef = ldef.str();
  reg::Match match;
  if (reg::search(sdef,match,reAnonymous))
  {
    ldef = match.prefix().str() + " { ... } " + removeAnonymousScopes(match.suffix().str());
  }
  const ClassDef *cd=getClassDef();
  if (cd && cd->isObjectiveC())
  {
    // strip scope name
    int ep = ldef.find("::");
    if (ep!=-1)
    {
      int sp=ldef.findRev(' ',ep);
      if (sp!=-1)
      {
        ldef=ldef.left(sp+1)+ldef.mid(ep+2);
      }
    }
    // strip keywords
    int dp = ldef.find(':');
    if (dp!=-1)
    {
      ldef=ldef.left(dp+1);
    }
    int l=static_cast<int>(ldef.length());
    //printf("start >%s<\n",qPrint(ldef));
    int i=l-1;
    while (i>=0 && (isId(ldef.at(i)) || ldef.at(i)==':')) i--;
    while (i>=0 && isspace(static_cast<uint8_t>(ldef.at(i)))) i--;
    if (i>0)
    {
      // insert branches around the type
      ldef = "("+ldef.left(i+1)+")"+ldef.mid(i+1);
    }
    //printf("end   >%s< i=%d\n",qPrint(ldef),i);
    if (isStatic()) ldef.prepend("+ "); else ldef.prepend("- ");
  }
  SrcLangExt lang = getLanguage();
  QCString sep = getLanguageSpecificSeparator(lang,TRUE);
  return substitute(ldef,"::",sep);
}
References QCString::at(), definition(), QCString::find(), QCString::findRev(), getClassDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), DefinitionMixin< MemberDefMutable >::isAnonymous(), isEnumerate(), isEnumValue(), isId(), ClassDef::isObjectiveC(), isSliceLocal(), isStatic(), QCString::left(), QCString::length(), m_enumBaseType, QCString::mid(), DefinitionMixin< MemberDefMutable >::name(), QCString::prepend(), reAnonymous, removeAnonymousScopes(), reg::search(), QCString::str(), substitute(), and TRUE.
displayName()
QCString MemberDefImpl::displayName (bool includeScope = TRUE) const override virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 6115 of file memberdef.cpp.
{
  return DefinitionMixin::name();
}
References DefinitionMixin< Base >::name().
Referenced by addListReference().
documentation()
QCString MemberDefImpl::documentation () const override virtual
Returns the detailed description of this definition
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 6289 of file memberdef.cpp.
{
  if (m_templateMaster)
  {
    return m_templateMaster->documentation();
  }
  else
  {
    return DefinitionMixin::documentation();
  }
}
References DefinitionMixin< Base >::documentation(), and m_templateMaster.
Referenced by findSectionsInDocumentation(), hasDetailedDescription(), isBriefSectionVisible(), writeDocumentation(), and writeMemberDocSimple().
enumBaseType()
QCString MemberDefImpl::enumBaseType () const override virtual
Implements MemberDef.
Definition at line 6029 of file memberdef.cpp.
{
  return m_enumBaseType;
}
References m_enumBaseType.
enumFieldList()
const MemberVector & MemberDefImpl::enumFieldList () const override virtual
Implements MemberDef.
Definition at line 5553 of file memberdef.cpp.
{
  return m_enumFields;
}
References m_enumFields.
Referenced by _writeEnumValues(), and warnIfUndocumented().
excpString()
QCString MemberDefImpl::excpString () const override virtual
Implements MemberDef.
Definition at line 5034 of file memberdef.cpp.
{
  return m_exception;
}
References m_exception.
Referenced by writeDeclaration(), and writeDocumentation().
extraTypeChars()
QCString MemberDefImpl::extraTypeChars () const override virtual
Implements MemberDef.
Definition at line 5019 of file memberdef.cpp.
{
  return m_extraTypeChars;
}
References m_extraTypeChars.
fieldType()
QCString MemberDefImpl::fieldType () const override virtual
Implements MemberDef.
Definition at line 3924 of file memberdef.cpp.
{
  QCString type = m_accessorType;
  if (type.isEmpty())
  {
    type = m_type;
  }
  if (isTypedef() && getLanguage() != SrcLangExt::Slice) type.prepend("typedef ");
  return simplifyTypeForTable(type);
}
References DefinitionMixin< MemberDefMutable >::getLanguage(), QCString::isEmpty(), isTypedef(), m_accessorType, m_type, QCString::prepend(), simplifyTypeForTable(), and Slice.
Referenced by writeMemberDocSimple().
findSectionsInDocumentation()
void MemberDefImpl::findSectionsInDocumentation () override virtual
Implements MemberDefMutable.
Definition at line 4898 of file memberdef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
  docFindSections(inbodyDocumentation(),this,docFile());
}
References briefDescription(), DefinitionMixin< MemberDefMutable >::docFile(), docFindSections(), documentation(), and DefinitionMixin< MemberDefMutable >::inbodyDocumentation().
formalTemplateArguments()
std::optional< ArgumentList > MemberDefImpl::formalTemplateArguments () const override virtual
Implements MemberDef.
Definition at line 5712 of file memberdef.cpp.
{
  return m_formalTemplateArguments;
}
References m_formalTemplateArguments.
fromAnonymousMember()
MemberDef * MemberDefImpl::fromAnonymousMember () const override virtual
Implements MemberDef.
Definition at line 5963 of file memberdef.cpp.
{
  return m_annMemb;
}
References m_annMemb.
fromAnonymousScope()
bool MemberDefImpl::fromAnonymousScope () const override virtual
Implements MemberDef.
Definition at line 5646 of file memberdef.cpp.
{
  return m_annScope;
}
References m_annScope.
getAnonymousEnumType()
const MemberDef * MemberDefImpl::getAnonymousEnumType () const override virtual
Implements MemberDef.
Definition at line 5508 of file memberdef.cpp.
{
  return m_annEnumType;
}
References m_annEnumType.
Referenced by writeDeclaration().
getCachedResolvedTypedef()
QCString MemberDefImpl::getCachedResolvedTypedef () const override virtual
Implements MemberDef.
Definition at line 5732 of file memberdef.cpp.
{
  //printf("MemberDefImpl::getCachedResolvedTypedef()=%s m_impl=%p\n",qPrint(m_cachedResolvedType),m_impl);
  return m_cachedResolvedType;
}
References m_cachedResolvedType.
getCachedTypedefTemplSpec()
QCString MemberDefImpl::getCachedTypedefTemplSpec () const override virtual
Implements MemberDef.
Definition at line 5727 of file memberdef.cpp.
{
  return m_cachedTypedefTemplSpec;
}
References m_cachedTypedefTemplSpec.
getCachedTypedefVal()
const ClassDef * MemberDefImpl::getCachedTypedefVal () const override virtual
Implements MemberDef.
Definition at line 5722 of file memberdef.cpp.
{
  return m_cachedTypedefValue;
}
References m_cachedTypedefValue.
getClassDef() [1/2]
const ClassDef * MemberDefImpl::getClassDef () const override virtual
Implements MemberDef.
Definition at line 5064 of file memberdef.cpp.
{
  return m_classDef;
}
References m_classDef.
Referenced by _computeIsConstructor(), _computeLinkableInProject(), _writeCategoryRelation(), _writeReimplementedBy(), displayDefinition(), getClassDefOfAnonymousType(), getLabels(), getOutputFileBase(), getReference(), getScopeString(), hasDetailedDescription(), isBriefSectionVisible(), isCSharpProperty(), isDetailedSectionVisible(), isObjCMethod(), isObjCProperty(), objCMethodName(), qualifiedName(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), and writeLink().
getClassDef() [2/2]
ClassDef * MemberDefImpl::getClassDef () override virtual
Implements MemberDef.
Definition at line 5069 of file memberdef.cpp.
{
  return m_classDef;
}
References m_classDef.
getClassDefMutable()
ClassDefMutable * MemberDefImpl::getClassDefMutable () override virtual
Implements MemberDefMutable.
Definition at line 5074 of file memberdef.cpp.
{
  return toClassDefMutable(m_classDef);
}
References m_classDef, and toClassDefMutable().
getClassDefOfAnonymousType()
ClassDef * MemberDefImpl::getClassDefOfAnonymousType () const override virtual
If this member has an anonymous class/struct/union as its type, then this method will return the ClassDef that describes this return type.
Implements MemberDef.
Definition at line 1984 of file memberdef.cpp.
{
  std::lock_guard<std::mutex> lock(g_cachedAnonymousTypeMutex);
  //printf("%s:getClassDefOfAnonymousType() cache=%s\n",qPrint(name()),
  //                   m_cachedAnonymousType?qPrint(m_cachedAnonymousType->name()):"<empty>");
  if (m_cachedAnonymousType) return m_cachedAnonymousType;
  QCString cname;
  if (getClassDef()!=nullptr)
  {
    cname=getClassDef()->name();
  }
  else if (getNamespaceDef()!=nullptr)
  {
    cname=getNamespaceDef()->name();
  }
  QCString ltype(m_type);
  // strip 'friend' keyword from ltype
  ltype.stripPrefix("friend ");
  // search for the last anonymous scope in the member type
  ClassDef *annoClassDef=nullptr;
  // match expression if it contains at least one @1 marker, e.g.
  // 'struct A::@1::@2::B' matches 'A::@1::@2::B' but 'struct A::B' does not match.
  std::string stype = ltype.str();
  static const reg::Ex r(R"([\w@:]*@\d+[\w@:]*)");
  reg::Match match;
  if (reg::search(stype,match,r)) // found anonymous scope in type
  {
    QCString annName = match.str();
    // if inside a class or namespace try to prepend the scope name
    if (!cname.isEmpty() && annName.left(cname.length()+2)!=cname+"::")
    {
      QCString ts=stripAnonymousNamespaceScope(cname+"::"+annName);
      annoClassDef=getClass(ts);
    }
    // if not found yet, try without scope name
    if (annoClassDef==nullptr)
    {
      QCString ts=stripAnonymousNamespaceScope(annName);
      annoClassDef=getClass(ts);
    }
  }
  m_cachedAnonymousType = annoClassDef;
  return annoClassDef;
}
References g_cachedAnonymousTypeMutex, getClass(), getClassDef(), getNamespaceDef(), QCString::isEmpty(), QCString::left(), QCString::length(), m_cachedAnonymousType, m_type, Definition::name(), reg::search(), QCString::str(), stripAnonymousNamespaceScope(), and QCString::stripPrefix().
Referenced by writeDeclaration(), and writeDocumentation().
getDeclColumn()
int MemberDefImpl::getDeclColumn () const override virtual
Implements MemberDef.
Definition at line 5768 of file memberdef.cpp.
{
  return m_declColumn;
}
References m_declColumn.
getDeclFileName()
QCString MemberDefImpl::getDeclFileName () const override virtual
Implements MemberDef.
Definition at line 5758 of file memberdef.cpp.
{
  return m_declFileName;
}
References m_declFileName.
getDeclLine()
int MemberDefImpl::getDeclLine () const override virtual
Implements MemberDef.
Definition at line 5763 of file memberdef.cpp.
{
  return m_declLine;
}
References m_declLine.
getDeclType()
QCString MemberDefImpl::getDeclType () const override virtual
Implements MemberDef.
Definition at line 2129 of file memberdef.cpp.
{
  SrcLangExt lang = getLanguage();
  QCString ltype(m_type);
  if (lang==SrcLangExt::Cpp && isEnumerate() && isStrong())
  {
    if (isEnumStruct())
    {
      ltype+=" struct";
    }
    else
    {
      ltype+=" class";
    }
  }
  if (isTypedef() && getLanguage() != SrcLangExt::Slice)
  {
    ltype.prepend("typedef ");
  }
  if (isTypeAlias())
  {
    ltype="using";
  }
  // strip 'friend' keyword from ltype
  ltype.stripPrefix("friend ");
  if (ltype=="@") // rename type from enum values
  {
    ltype="";
  }
  else
  {
    if (isObjCMethod())
    {
      ltype.prepend("(");
      ltype.append(")");
    }
  }
  return ltype;
}
References QCString::append(), Cpp, DefinitionMixin< MemberDefMutable >::getLanguage(), isEnumerate(), isEnumStruct(), isObjCMethod(), isStrong(), isTypeAlias(), isTypedef(), m_type, QCString::prepend(), Slice, and QCString::stripPrefix().
getEnumScope()
const MemberDef * MemberDefImpl::getEnumScope () const override virtual
Implements MemberDef.
Definition at line 5518 of file memberdef.cpp.
{
  return m_enumScope;
}
References m_enumScope.
Referenced by getOutputFileBase(), and writeLink().
getExamples()
const ExampleList & MemberDefImpl::getExamples () const override virtual
Implements MemberDef.
Definition at line 5558 of file memberdef.cpp.
{
  return m_examples;
}
References m_examples.
getFileDef() [1/2]
const FileDef * MemberDefImpl::getFileDef () const override virtual
Implements MemberDef.
Definition at line 5079 of file memberdef.cpp.
{
  return m_fileDef;
}
References m_fileDef.
Referenced by _computeLinkableInProject(), _writeGroupInclude(), _writeMultiLineInitializer(), _writeTemplatePrefix(), getOutputFileBase(), getReference(), sourceRefName(), warnIfUndocumented(), writeDeclaration(), and writeDocumentation().
getFileDef() [2/2]
FileDef * MemberDefImpl::getFileDef () override virtual
Implements MemberDef.
Definition at line 5084 of file memberdef.cpp.
{
  return m_fileDef;
}
References m_fileDef.
getGroupAlias()
const MemberDef * MemberDefImpl::getGroupAlias () const override virtual
Implements MemberDef.
Definition at line 5753 of file memberdef.cpp.
{
  return m_groupAlias;
}
References m_groupAlias.
getGroupDef() [1/2]
const GroupDef * MemberDefImpl::getGroupDef () const override virtual
Implements MemberDef.
Definition at line 5109 of file memberdef.cpp.
{
  return m_group;
}
References m_group.
Referenced by _computeLinkableInProject(), anchor(), getOutputFileBase(), getReference(), isDetailedSectionVisible(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), and writeLink().
getGroupDef() [2/2]
GroupDef * MemberDefImpl::getGroupDef () override virtual
Implements MemberDef.
Definition at line 5114 of file memberdef.cpp.
{
  return m_group;
}
References m_group.
getGroupFileName()
QCString MemberDefImpl::getGroupFileName () const override virtual
Implements MemberDef.
Definition at line 5129 of file memberdef.cpp.
{
  return m_groupFileName;
}
References m_groupFileName.
getGroupHasDocs()
bool MemberDefImpl::getGroupHasDocs () const override virtual
Implements MemberDef.
Definition at line 5139 of file memberdef.cpp.
{
  return m_groupHasDocs;
}
References m_groupHasDocs.
getGroupPri()
Grouping::GroupPri_t MemberDefImpl::getGroupPri () const override virtual
Implements MemberDef.
Definition at line 5124 of file memberdef.cpp.
{
  return m_grouppri;
}
References m_grouppri.
getGroupStartLine()
int MemberDefImpl::getGroupStartLine () const override virtual
Implements MemberDef.
Definition at line 5134 of file memberdef.cpp.
{
  return m_groupStartLine;
}
References m_groupStartLine.
getLabels()
StringVector MemberDefImpl::getLabels (const Definition * container) const override virtual
Implements MemberDef.
Definition at line 2787 of file memberdef.cpp.
{
  StringVector sl;
  bool inlineInfo = Config_getBool(INLINE_INFO);
  Specifier lvirt=virtualness();
  if ((!isObjCMethod() || isOptional() || isRequired()) &&
      (protection()!=Protection::Public || lvirt!=Specifier::Normal ||
       isFriend() || isRelated() ||
       (isInline() && inlineInfo) ||
       isSignal() || isSlot() ||
       isStatic() || isExternal() ||
       isExported() ||
       (getClassDef() && getClassDef()!=container && container->definitionType()==TypeClass) ||
       TypeSpecifier(m_memSpec).setInline(false)!=TypeSpecifier()
      )
     )
  {
    // write the member specifier list
    //ol.writeLatexSpacing();
    //ol.startTypewriter();
    //ol.docify(" [");
    SrcLangExt lang = getLanguage();
    bool optVhdl = lang==SrcLangExt::VHDL;
    bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
    if (optVhdl)
    {
      sl.push_back(theTranslator->trVhdlType(getVhdlSpecifiers(),TRUE).str());
    }
    else
    {
      if (isFriend())                                   sl.emplace_back("friend");
      else if (isRelated())                             sl.emplace_back("related");
      else
      {
        if      (isExternal())                          sl.emplace_back("extern");
        if      (inlineInfo && isInline())              sl.emplace_back("inline");
        if      (isExplicit())                          sl.emplace_back("explicit");
        if      (isMutable())                           sl.emplace_back("mutable");
        if      (isStatic())                            sl.emplace_back("static");
        if      (isGettable())                          sl.emplace_back("get");
        if      (isProtectedGettable())                 sl.emplace_back("protected get");
        if      (isSettable())                          sl.emplace_back("set");
        if      (isProtectedSettable())                 sl.emplace_back("protected set");
        if (extractPrivate)
        {
          if    (isPrivateGettable())                   sl.emplace_back("private get");
          if    (isPrivateSettable())                   sl.emplace_back("private set");
        }
        if      (isNoDiscard())                         sl.emplace_back("nodiscard");
        if      (isConstExpr())                         sl.emplace_back("constexpr");
        if      (isConstEval())                         sl.emplace_back("consteval");
        if      (isConstInit())                         sl.emplace_back("constinit");
        if      (isAddable())                           sl.emplace_back("add");
        if      (!isUNOProperty() && isRemovable())     sl.emplace_back("remove");
        if      (isRaisable())                          sl.emplace_back("raise");
        if      (isReadable())                          sl.emplace_back("read");
        if      (isWritable())                          sl.emplace_back("write");
        if      (isFinal())                             sl.emplace_back("final");
        if      (isAbstract())                          sl.emplace_back("abstract");
        if      (isOverride())                          sl.emplace_back("override");
        if      (isInitonly())                          sl.emplace_back("initonly");
        if      (isSealed())                            sl.emplace_back("sealed");
        if      (isNew())                               sl.emplace_back("new");
        if      (isOptional())                          sl.emplace_back("optional");
        if      (isRequired())                          sl.emplace_back("required");
        if      (isExported())                          sl.emplace_back("export");
        if      (isNonAtomic())                         sl.emplace_back("nonatomic");
        else if (isObjCProperty())                      sl.emplace_back("atomic");
        // mutual exclusive Objective 2.0 property attributes
        if      (isAssign())                            sl.emplace_back("assign");
        else if (isCopy())                              sl.emplace_back("copy");
        else if (isRetain())                            sl.emplace_back("retain");
        else if (isWeak())                              sl.emplace_back("weak");
        else if (lang!=SrcLangExt::CSharp && isStrong()) sl.emplace_back("strong");
        else if (isUnretained())                        sl.emplace_back("unsafe_unretained");
        if (!isObjCMethod())
        {
          if      (protection()==Protection::Protected) sl.emplace_back("protected");
          else if (protection()==Protection::Private)   sl.emplace_back("private");
          else if (protection()==Protection::Package)   sl.emplace_back("package");
          if      (lvirt==Specifier::Virtual)           sl.emplace_back("virtual");
          else if (lvirt==Specifier::Pure)              sl.emplace_back("pure virtual");
          if      (isSignal())                          sl.emplace_back("signal");
          if      (isSlot())                            sl.emplace_back("slot");
          if      (isDefault())                         sl.emplace_back("default");
          if      (isDelete())                          sl.emplace_back("delete");
          if      (isNoExcept())                        sl.emplace_back("noexcept");
          if      (isAttribute())                       sl.emplace_back("attribute");
          if      (isUNOProperty())                     sl.emplace_back("property");
          if      (isReadonly())                        sl.emplace_back("readonly");
          if      (isBound())                           sl.emplace_back("bound");
          if      (isUNOProperty() && isRemovable())    sl.emplace_back("removable");
          if      (isConstrained())                     sl.emplace_back("constrained");
          if      (isTransient())                       sl.emplace_back("transient");
          if      (isMaybeVoid())                       sl.emplace_back("maybevoid");
          if      (isMaybeDefault())                    sl.emplace_back("maybedefault");
          if      (isMaybeAmbiguous())                  sl.emplace_back("maybeambiguous");
          if      (isPublished())                       sl.emplace_back("published"); // enum
        }
        if (isObjCProperty() && isImplementation())
        {
          sl.emplace_back("implementation");
        }
      }
      if (getClassDef() &&
          container->definitionType()==TypeClass &&
          getClassDef()!=container &&
          !isRelated()
         )
      {
        sl.emplace_back("inherited");
      }
    }
  }
  else if (isObjCMethod() && isImplementation())
  {
    sl.emplace_back("implementation");
  }
  for (const auto &sx : m_qualifiers)
  {
    bool alreadyAdded = std::find(sl.begin(), sl.end(), sx) != sl.end();
    if (!alreadyAdded)
    {
      sl.push_back(sx);
    }
  }
  return sl;
}
References Config_getBool, CSharp, Definition::definitionType(), getClassDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), getVhdlSpecifiers(), isAbstract(), isAddable(), isAssign(), isAttribute(), isBound(), isConstEval(), isConstExpr(), isConstInit(), isConstrained(), isCopy(), isDefault(), isDelete(), isExplicit(), DefinitionMixin< MemberDefMutable >::isExported(), isExternal(), isFinal(), isFriend(), isGettable(), isImplementation(), isInitonly(), isInline(), isMaybeAmbiguous(), isMaybeDefault(), isMaybeVoid(), isMutable(), isNew(), isNoDiscard(), isNoExcept(), isNonAtomic(), isObjCMethod(), isObjCProperty(), isOptional(), isOverride(), isPrivateGettable(), isPrivateSettable(), isProtectedGettable(), isProtectedSettable(), isPublished(), isRaisable(), isReadable(), isReadonly(), isRelated(), isRemovable(), isRequired(), isRetain(), isSealed(), isSettable(), isSignal(), isSlot(), isStatic(), isStrong(), isTransient(), isUNOProperty(), isUnretained(), isWeak(), isWritable(), m_memSpec, m_qualifiers, Normal, Package, Private, Protected, protection(), Public, Pure, theTranslator, TRUE, Translator::trVhdlType(), Definition::TypeClass, VHDL, Virtual, and virtualness().
Referenced by writeDocumentation().
getMemberGroup()
MemberGroup * MemberDefImpl::getMemberGroup () const override virtual
Implements MemberDef.
Definition at line 5641 of file memberdef.cpp.
{
  return m_memberGroup;
}
References m_memberGroup.
getMemberGroupId()
int MemberDefImpl::getMemberGroupId () const override virtual
Implements MemberDef.
Definition at line 5636 of file memberdef.cpp.
{
  return m_grpId;
}
References m_grpId.
getMemberSpecifiers()
TypeSpecifier MemberDefImpl::getMemberSpecifiers () const override virtual
Implements MemberDef.
Definition at line 5054 of file memberdef.cpp.
{
  return m_memSpec;
}
References m_memSpec.
getModuleDef()
const ModuleDef * MemberDefImpl::getModuleDef () const override virtual
Implements MemberDef.
Definition at line 5119 of file memberdef.cpp.
{
  return m_moduleDef;
}
References m_moduleDef.
Referenced by _computeLinkableInProject(), getOutputFileBase(), getReference(), writeDocumentation(), and writeLink().
getNamespaceDef() [1/2]
const NamespaceDef * MemberDefImpl::getNamespaceDef () const override virtual
Implements MemberDef.
Definition at line 5089 of file memberdef.cpp.
{
  return m_nspace;
}
References m_nspace.
Referenced by _computeLinkableInProject(), getClassDefOfAnonymousType(), getOutputFileBase(), getReference(), getScopeString(), isDetailedSectionVisible(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), writeLink(), and writeTagFile().
getNamespaceDef() [2/2]
NamespaceDef * MemberDefImpl::getNamespaceDef () override virtual
Implements MemberDef.
Definition at line 5094 of file memberdef.cpp.
{
  return m_nspace;
}
References m_nspace.
getOutputFileBase()
QCString MemberDefImpl::getOutputFileBase () const override virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 1655 of file memberdef.cpp.
{
  bool separateMemberPages = Config_getBool(SEPARATE_MEMBER_PAGES);
  bool inlineSimpleClasses = Config_getBool(INLINE_SIMPLE_STRUCTS);
  QCString baseName;
  //printf("Member: %s: templateMaster=%p group=%p classDef=%p nspace=%p fileDef=%p\n",
  //    qPrint(name()),m_templateMaster,m_group,m_classDef,
  //    m_nspace,m_fileDef);
  const NamespaceDef *nspace = getNamespaceDef();
  const FileDef *fileDef = getFileDef();
  const ClassDef *classDef = getClassDef();
  const ModuleDef *moduleDef = getModuleDef();
  const GroupDef *groupDef = getGroupDef();
  if (!m_explicitOutputFileBase.isEmpty())
  {
    return m_explicitOutputFileBase;
  }
  else if (templateMaster())
  {
    return templateMaster()->getOutputFileBase();
  }
  else if (groupDef)
  {
    baseName=groupDef->getOutputFileBase();
  }
  else if (classDef)
  {
    baseName=classDef->getOutputFileBase();
    if (inlineSimpleClasses && classDef->isSimple())
    {
      return baseName;
    }
  }
  else if (nspace && (nspace->isLinkable() || nspace->isAnonymous()))
  {
    baseName=nspace->getOutputFileBase();
  }
  else if (fileDef)
  {
    baseName=fileDef->getOutputFileBase();
  }
  else if (moduleDef)
  {
    baseName=moduleDef->getOutputFileBase();
  }
  if (baseName.isEmpty())
  {
    warn(getDefFileName(),getDefLine(),
       "Internal inconsistency: member %s does not belong to any"
       " container!",qPrint(name())
      );
    return "dummy";
  }
  else if (separateMemberPages && hasDetailedDescription())
  {
    if (getEnumScope()) // enum value, which is part of enum's documentation
    {
      baseName+="_"+getEnumScope()->anchor();
    }
    else
    {
      baseName+="_"+anchor();
    }
  }
  return baseName;
}
References Definition::anchor(), anchor(), Config_getBool, getClassDef(), DefinitionMixin< MemberDefMutable >::getDefFileName(), DefinitionMixin< MemberDefMutable >::getDefLine(), getEnumScope(), getFileDef(), getGroupDef(), getModuleDef(), getNamespaceDef(), Definition::getOutputFileBase(), hasDetailedDescription(), Definition::isAnonymous(), QCString::isEmpty(), Definition::isLinkable(), ClassDef::isSimple(), m_explicitOutputFileBase, DefinitionMixin< MemberDefMutable >::name(), qPrint(), templateMaster(), and warn.
Referenced by addListReference(), writeDeclaration(), writeDocumentation(), writeLink(), writeMemberDocSimple(), and writeTagFile().
getQualifiers()
StringVector MemberDefImpl::getQualifiers () const override virtual
Implements MemberDef.
Definition at line 5821 of file memberdef.cpp.
{
  return m_qualifiers;
}
References m_qualifiers.
getReadAccessor()
QCString MemberDefImpl::getReadAccessor () const override virtual
Implements MemberDef.
Definition at line 5099 of file memberdef.cpp.
{
  return m_read;
}
References m_read.
getReference()
QCString MemberDefImpl::getReference () const override virtual
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 1724 of file memberdef.cpp.
{
  QCString ref = DefinitionMixin::getReference();
  if (!ref.isEmpty())
  {
    return ref;
  }
  const NamespaceDef *nspace = getNamespaceDef();
  const FileDef *fileDef = getFileDef();
  const ClassDef *classDef = getClassDef();
  const ModuleDef *moduleDef = getModuleDef();
  const GroupDef *groupDef = getGroupDef();
  if (templateMaster())
  {
    return templateMaster()->getReference();
  }
  else if (groupDef)
  {
    return groupDef->getReference();
  }
  else if (classDef)
  {
    return classDef->getReference();
  }
  else if (nspace)
  {
    return nspace->getReference();
  }
  else if (moduleDef)
  {
    return moduleDef->getReference();
  }
  else if (fileDef)
  {
    return fileDef->getReference();
  }
  return "";
}
References getClassDef(), getFileDef(), getGroupDef(), getModuleDef(), getNamespaceDef(), Definition::getReference(), DefinitionMixin< Base >::getReference(), QCString::isEmpty(), and templateMaster().
Referenced by anchor(), and writeLink().
getScopeString()
QCString MemberDefImpl::getScopeString () const override virtual
Implements MemberDef.
Definition at line 4318 of file memberdef.cpp.
{
  QCString result;
  if (isStrong()) result=name();
  else if (getClassDef()) result=getClassDef()->displayName();
  else if (getNamespaceDef()) result=getNamespaceDef()->displayName();
  return result;
}
References Definition::displayName(), getClassDef(), getNamespaceDef(), isStrong(), and DefinitionMixin< MemberDefMutable >::name().
Referenced by sourceRefName(), and writeDocumentation().
getSectionList()
const MemberList * MemberDefImpl::getSectionList (const Definition * container) const override virtual
Implements MemberDef.
Definition at line 4542 of file memberdef.cpp.
{
  auto it = m_sectionMap.find(container);
  return it!=m_sectionMap.end() ? it->second : nullptr;
}
References m_sectionMap.
getVhdlSpecifiers()
VhdlSpecifier MemberDefImpl::getVhdlSpecifiers () const override virtual
Implements MemberDef.
Definition at line 5059 of file memberdef.cpp.
{
  return m_vhdlSpec;
}
References m_vhdlSpec.
Referenced by getLabels().
getWriteAccessor()
QCString MemberDefImpl::getWriteAccessor () const override virtual
Implements MemberDef.
Definition at line 5104 of file memberdef.cpp.
{
  return m_write;
}
References m_write.
hasCallerGraph()
bool MemberDefImpl::hasCallerGraph () const override virtual
Implements MemberDef.
Definition at line 5669 of file memberdef.cpp.
{
  return m_hasCallerGraph;
}
References m_hasCallerGraph.
hasCallGraph()
bool MemberDefImpl::hasCallGraph () const override virtual
Implements MemberDef.
Definition at line 5651 of file memberdef.cpp.
{
  return m_hasCallGraph;
}
References m_hasCallGraph.
hasDetailedDescription()
bool MemberDefImpl::hasDetailedDescription () const override virtual
Implements MemberDef.
Definition at line 2664 of file memberdef.cpp.
{
  std::lock_guard<std::mutex> lock(g_hasDetailedDescriptionMutex);
  //printf(">hasDetailedDescription(cached=%d)\n",m_hasDetailedDescriptionCached);
  if (!m_hasDetailedDescriptionCached)
  {
    bool extractAll            = Config_getBool(EXTRACT_ALL);
    bool alwaysDetailedSec     = Config_getBool(ALWAYS_DETAILED_SEC);
    bool repeatBrief           = Config_getBool(REPEAT_BRIEF);
    bool briefMemberDesc       = Config_getBool(BRIEF_MEMBER_DESC);
    bool hideUndocMembers      = Config_getBool(HIDE_UNDOC_MEMBERS);
    bool extractStatic         = Config_getBool(EXTRACT_STATIC);
    bool extractPrivateVirtual = Config_getBool(EXTRACT_PRIV_VIRTUAL);
    bool inlineSources         = hasInlineSource();
    // the member has detailed documentation because the user added some comments
    bool docFilter =
           // extract all is enabled
           extractAll ||
           // has detailed docs
           !documentation().isEmpty() ||
           // has inbody docs
           !inbodyDocumentation().isEmpty() ||
           // is an enum with values that are documented
           (isEnumerate() && hasDocumentedEnumValues()) ||
           // is documented enum value
           (m_mtype==MemberType::EnumValue && !briefDescription().isEmpty()) ||
           // has brief description that is part of the detailed description
           (!briefDescription().isEmpty() &&           // has brief docs
            (alwaysDetailedSec &&                      // they are visible in
             (repeatBrief ||                           // detailed section or
              !briefMemberDesc                         // they are explicitly not
             )                                         // shown in brief section
            )
           ) ||
           // has one or more documented arguments
           (m_templateMaster ?
            m_templateMaster->argumentList().hasDocumentation() :
            m_defArgList.hasDocumentation());
    // generate function                  guard
    // ==================                 =======
    // _writeGroupInclude              -> ignored in calculation
    // multiLineInitializer()          -> hasMultiLineInitializer()
    // _writeReimplements              -> _isReimplements()
    // _writeReimplementedBy           -> _countReimplementedBy()>0
    // _writeExamples                  -> hasExamples()
    // _writeTypeConstraints           -> m_typeConstraints.hasParameters()
    // writeSourceDef                  -> !getSourceFileBase().isEmpty();
    // writeInlineCode                 -> hasInlineSource() && hasSources()
    // writeSourceRefs                 -> hasReferencesRelation() && hasSourceRefs()
    // writeSourceReffedBy             -> hasReferencedByRelation() && hasSourceReffedBy()
    // _writeCallGraph                 -> _hasVisibleCallGraph()
    // _writeCallerGraph               -> _hasVisibleCallerGraph()
    // the member has detailed documentation because there is some generated info
    bool docInfo =
           // has a multi-line initialization block
           (hasMultiLineInitializer()) ||
           // reimplements / reimplemented by
           _isReimplements() || (_countReimplementedBy() > 0) ||
           // examples
           hasExamples() ||
           // type constraints
           m_typeConstraints.hasParameters() ||
           // has source definition
           !getSourceFileBase().isEmpty() ||
           // has inline sources
           (inlineSources && hasSources()) ||
           // has references
           (hasReferencesRelation() && hasSourceRefs()) ||
           (hasReferencedByRelation() && hasSourceReffedBy()) ||
           // call graph
           _hasVisibleCallGraph() ||
           // caller graph
           _hasVisibleCallerGraph();
    if (!hideUndocMembers) // if HIDE_UNDOC_MEMBERS is NO we also show the detailed section
                           // if there is only some generated info
    {
      docFilter = docFilter || docInfo;
    }
    // this is not a global static or global statics should be extracted
    bool staticFilter = getClassDef()!=nullptr || !isStatic() || extractStatic;
    // only include members that are non-private unless EXTRACT_PRIVATE is
    // set to YES or the member is part of a   group
    bool privateFilter = protectionLevelVisible(protection()) || m_mtype==MemberType::Friend ||
                         (m_prot==Protection::Private && (m_virt!=Specifier::Normal || isOverride() || isFinal()) && extractPrivateVirtual);
    // hide friend (class|struct|union) member if HIDE_FRIEND_COMPOUNDS
    // is true
    bool friendCompoundFilter = !(Config_getBool(HIDE_FRIEND_COMPOUNDS) && isFriend());
    m_detailedDescriptionCachedValue =
        (docFilter && staticFilter && privateFilter && friendCompoundFilter && !isHidden());
    //printf("docFilter=%d docInfo=%d staticFilter=%d privateFilter=%d friendCompoundFilter=%d !isHidden()=%d",
    //    docFilter,docInfo,staticFilter,privateFilter,friendCompoundFilter,!isHidden());
    m_hasDetailedDescriptionCached = true;
  }
  //printf("<hasDetailedDescription(cached=%d)\n",m_hasDetailedDescriptionCached);
  return m_detailedDescriptionCachedValue;
}
References _countReimplementedBy(), _hasVisibleCallerGraph(), _hasVisibleCallGraph(), _isReimplements(), briefDescription(), Config_getBool, documentation(), EnumValue, Friend, g_hasDetailedDescriptionMutex, getClassDef(), DefinitionMixin< MemberDefMutable >::getSourceFileBase(), hasDocumentation(), hasDocumentedEnumValues(), hasExamples(), hasInlineSource(), hasMultiLineInitializer(), hasReferencedByRelation(), hasReferencesRelation(), DefinitionMixin< MemberDefMutable >::hasSourceReffedBy(), DefinitionMixin< MemberDefMutable >::hasSourceRefs(), DefinitionMixin< MemberDefMutable >::hasSources(), DefinitionMixin< MemberDefMutable >::inbodyDocumentation(), QCString::isEmpty(), isEnumerate(), isFinal(), isFriend(), DefinitionMixin< MemberDefMutable >::isHidden(), isOverride(), isStatic(), m_defArgList, m_detailedDescriptionCachedValue, m_hasDetailedDescriptionCached, m_mtype, m_prot, m_templateMaster, m_typeConstraints, m_virt, Normal, Private, protection(), and protectionLevelVisible().
Referenced by getOutputFileBase(), isDetailedSectionVisible(), warnIfUndocumented(), writeDeclaration(), and writeLink().
hasDocumentation()
bool MemberDefImpl::hasDocumentation () const override virtual
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 4305 of file memberdef.cpp.
{
  return DefinitionMixin::hasDocumentation() ||
         (m_mtype==MemberType::Enumeration && m_docEnumValues) ||  // has enum values
         (m_defArgList.hasDocumentation());   // has doc arguments
}
References Enumeration, DefinitionMixin< Base >::hasDocumentation(), m_defArgList, m_docEnumValues, and m_mtype.
Referenced by _computeLinkableInProject(), hasDetailedDescription(), isBriefSectionVisible(), visibleInIndex(), warnIfUndocumentedParams(), and writeDeclaration().
hasDocumentedEnumValues()
bool MemberDefImpl::hasDocumentedEnumValues () const override virtual
Implements MemberDef.
Definition at line 5503 of file memberdef.cpp.
{
  return m_docEnumValues;
}
References m_docEnumValues.
Referenced by hasDetailedDescription(), and writeEnumDeclaration().
hasEnumValues()
bool MemberDefImpl::hasEnumValues () const override virtual
Implements MemberDef.
Definition at line 5702 of file memberdef.cpp.
{
  return m_hasEnumValues;
}
References m_hasEnumValues.
Referenced by _writeEnumValues().
hasExamples()
bool MemberDefImpl::hasExamples () const override virtual
Implements MemberDef.
Definition at line 1630 of file memberdef.cpp.
{
  return !m_examples.empty();
}
References m_examples.
Referenced by _writeExamples(), and hasDetailedDescription().
hasInlineSource()
bool MemberDefImpl::hasInlineSource () const override virtual
Implements MemberDef.
Definition at line 5697 of file memberdef.cpp.
{
  return m_hasInlineSource;
}
References m_hasInlineSource.
Referenced by hasDetailedDescription().
hasMultiLineInitializer()
bool MemberDefImpl::hasMultiLineInitializer () const override virtual
Implements MemberDef.
Definition at line 4460 of file memberdef.cpp.
{
  //printf("initLines=%d userInitLines=%d maxInitLines=%d\n",
  //    initLines,userInitLines,maxInitLines);
  bool isFuncLikeMacro = m_mtype==MemberType::Define && m_defArgList.hasParameters();
  return (m_initLines>0 || (!m_initializer.isEmpty() && isFuncLikeMacro)) &&
         ((m_initLines<m_maxInitLines && m_userInitLines==-1) // implicitly enabled
          || m_initLines<m_userInitLines // explicitly enabled
         );
}
References Define, m_defArgList, m_initializer, m_initLines, m_maxInitLines, m_mtype, and m_userInitLines.
Referenced by hasDetailedDescription(), and writeDocumentation().
hasOneLineInitializer()
bool MemberDefImpl::hasOneLineInitializer () const override virtual
Implements MemberDef.
Definition at line 4449 of file memberdef.cpp.
{
  //printf("%s: init=%s, initLines=%d maxInitLines=%d userInitLines=%d\n",
  //    qPrint(name()),qPrint(m_initializer),m_initLines,
  //    m_maxInitLines,m_userInitLines);
  bool isFuncLikeMacro = m_mtype==MemberType::Define && m_defArgList.hasParameters();
  return !m_initializer.isEmpty() && m_initLines==0 && // one line initializer
         !isFuncLikeMacro &&
         ((m_maxInitLines>0 && m_userInitLines==-1) || m_userInitLines>0); // enabled by default or explicitly
}
References Define, m_defArgList, m_initializer, m_initLines, m_maxInitLines, m_mtype, and m_userInitLines.
Referenced by writeDeclaration(), writeDocumentation(), and writeMemberDocSimple().
hasReferencedByRelation()
bool MemberDefImpl::hasReferencedByRelation () const override virtual
Implements MemberDef.
Definition at line 5687 of file memberdef.cpp.
{
  return m_hasReferencedByRelation;
}
References m_hasReferencedByRelation.
Referenced by hasDetailedDescription(), and writeDocumentation().
hasReferencesRelation()
bool MemberDefImpl::hasReferencesRelation () const override virtual
Implements MemberDef.
Definition at line 5692 of file memberdef.cpp.
{
  return m_hasReferencesRelation;
}
References m_hasReferencesRelation.
Referenced by hasDetailedDescription(), and writeDocumentation().
hasUserDocumentation()
bool MemberDefImpl::hasUserDocumentation () const override virtual
Returns TRUE iff the definition is documented by the user.
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 6301 of file memberdef.cpp.
{
  if (m_templateMaster)
  {
    return m_templateMaster->hasUserDocumentation();
  }
  else
  {
    return DefinitionMixin::hasUserDocumentation();
  }
}
References DefinitionMixin< Base >::hasUserDocumentation(), and m_templateMaster.
Referenced by warnIfUndocumented().
incrementFlowKeyWordCount()
void MemberDefImpl::incrementFlowKeyWordCount () override virtual
Implements MemberDefMutable.
Definition at line 6103 of file memberdef.cpp.
{
  m_numberOfFlowKW++;
}
References m_numberOfFlowKW.
inheritsDocsFrom()
const MemberDef * MemberDefImpl::inheritsDocsFrom () const override virtual
Implements MemberDef.
Definition at line 5748 of file memberdef.cpp.
{
  return m_docProvider;
}
References m_docProvider.
init()
void MemberDefImpl::init (Definition * def, const QCString & t, const QCString & a, const QCString & e, Protection p, Specifier v, bool s, Relationship r, MemberType mt, const ArgumentList & tal, const ArgumentList & al, const QCString & meta) private
Definition at line 1322 of file memberdef.cpp.
{
  m_classDef=nullptr;
  m_fileDef=nullptr;
  m_moduleDef=nullptr;
  m_redefines=nullptr;
  m_relatedAlso=nullptr;
  m_accessorClass=nullptr;
  m_nspace=nullptr;
  m_memDef=nullptr;
  m_memDec=nullptr;
  m_group=nullptr;
  m_grpId=-1;
  m_enumScope=nullptr;
  m_livesInsideEnum=FALSE;
  m_hasCallGraph            = Config_getBool(CALL_GRAPH);
  m_hasCallerGraph          = Config_getBool(CALLER_GRAPH);
  m_hasReferencedByRelation = Config_getBool(REFERENCED_BY_RELATION);
  m_hasReferencesRelation   = Config_getBool(REFERENCES_RELATION);
  m_hasEnumValues           = Config_getBool(SHOW_ENUM_VALUES);
  m_hasInlineSource         = Config_getBool(INLINE_SOURCES);
  m_initLines=0;
  m_type=t;
  if (mt==MemberType::Typedef) m_type.stripPrefix("typedef ");
  //  type.stripPrefix("struct ");
  //  type.stripPrefix("class " );
  //  type.stripPrefix("union " );
  m_type=removeRedundantWhiteSpace(m_type);
  m_args=a;
  m_args=removeRedundantWhiteSpace(m_args);
  if (m_type.isEmpty()) m_decl=d->name()+m_args; else m_decl=m_type+" "+d->name()+m_args;
  m_memberGroup=nullptr;
  m_virt=v;
  m_prot=p;
  m_related=r;
  m_stat=s;
  m_mtype=mt;
  m_exception=e;
  m_proto=FALSE;
  m_annScope=FALSE;
  m_memSpec=TypeSpecifier();
  m_vhdlSpec=VhdlSpecifier::UNKNOWN;
  m_annMemb=nullptr;
  m_annEnumType=nullptr;
  m_groupAlias=nullptr;
  m_explExt=FALSE;
  m_tspec=FALSE;
  m_cachedAnonymousType=nullptr;
  m_maxInitLines=Config_getInt(MAX_INITIALIZER_LINES);
  m_userInitLines=-1;
  m_docEnumValues=FALSE;
  // copy function template arguments (if any)
  m_tArgList = tal;
  //printf("new member al=%p\n",al);
  // copy function definition arguments (if any)
  m_defArgList = al;
  // convert function declaration arguments (if any)
  if (!m_args.isEmpty())
  {
    m_declArgList = *stringToArgumentList(d->getLanguage(),m_args,&m_extraTypeChars);
    //printf("setDeclArgList %s to %s const=%d\n",qPrint(args),
    //    qPrint(argListToString(declArgList)),declArgList->constSpecifier);
  }
  m_metaData = meta;
  m_templateMaster = nullptr;
  m_docsForDefinition = TRUE;
  m_isTypedefValCached = FALSE;
  m_cachedTypedefValue = nullptr;
  m_implOnly=FALSE;
  m_groupMember = nullptr;
  m_hasDocumentedParams = FALSE;
  m_hasDocumentedReturnType = FALSE;
  m_docProvider = nullptr;
  m_isDMember = d->getDefFileName().lower().endsWith(".d");
}
References Config_getBool, Config_getInt, QCString::endsWith(), FALSE, Definition::getDefFileName(), Definition::getLanguage(), QCString::lower(), m_accessorClass, m_annEnumType, m_annMemb, m_annScope, m_args, m_cachedAnonymousType, m_cachedTypedefValue, m_classDef, m_decl, m_declArgList, m_defArgList, m_docEnumValues, m_docProvider, m_docsForDefinition, m_enumScope, m_exception, m_explExt, m_extraTypeChars, m_fileDef, m_group, m_groupAlias, m_groupMember, m_grpId, m_hasCallerGraph, m_hasCallGraph, m_hasDocumentedParams, m_hasDocumentedReturnType, m_hasEnumValues, m_hasInlineSource, m_hasReferencedByRelation, m_hasReferencesRelation, m_implOnly, m_initLines, m_isDMember, m_isTypedefValCached, m_livesInsideEnum, m_maxInitLines, m_memberGroup, m_memDec, m_memDef, m_memSpec, m_metaData, m_moduleDef, m_mtype, m_nspace, m_prot, m_proto, m_redefines, m_related, m_relatedAlso, m_stat, m_tArgList, m_templateMaster, m_tspec, m_type, m_userInitLines, m_vhdlSpec, m_virt, Definition::name(), removeRedundantWhiteSpace(), stringToArgumentList(), TRUE, Typedef, and UNKNOWN.
Referenced by MemberDefImpl(), and writeDocumentation().
initializer()
const QCString & MemberDefImpl::initializer () const override virtual
Implements MemberDef.
Definition at line 5044 of file memberdef.cpp.
{
  return m_initializer;
}
References m_initializer.
Referenced by setInitializer().
initializerLines()
int MemberDefImpl::initializerLines () const override virtual
Implements MemberDef.
Definition at line 5049 of file memberdef.cpp.
{
  return m_initLines;
}
References m_initLines.
insertEnumField()
void MemberDefImpl::insertEnumField (MemberDef * md) override virtual
Implements MemberDefMutable.
Definition at line 1619 of file memberdef.cpp.
{
  m_enumFields.push_back(md);
}
References m_enumFields.
insertReimplementedBy()
void MemberDefImpl::insertReimplementedBy (MemberDef * md) override virtual
Implements MemberDefMutable.
Definition at line 1574 of file memberdef.cpp.
{
  if (m_templateMaster)
  {
    MemberDefMutable *mdm = toMemberDefMutable(m_templateMaster);
    if (mdm)
    {
      mdm->insertReimplementedBy(md);
    }
  }
  if (!m_redefinedBy.contains(md))
  {
    m_redefinedBy.inSort(md);
  }
}
References MemberDefMutable::insertReimplementedBy(), m_redefinedBy, m_templateMaster, and toMemberDefMutable().
invalidateCachedArgumentTypes()
void MemberDefImpl::invalidateCachedArgumentTypes () override virtual
Implements MemberDefMutable.
Definition at line 6097 of file memberdef.cpp.
{
  invalidateCachedTypesInArgumentList(m_defArgList);
  invalidateCachedTypesInArgumentList(m_declArgList);
}
References invalidateCachedTypesInArgumentList(), m_declArgList, and m_defArgList.
invalidateTypedefValCache()
void MemberDefImpl::invalidateTypedefValCache () override virtual
Implements MemberDefMutable.
Definition at line 5989 of file memberdef.cpp.
{
  m_isTypedefValCached=FALSE;
}
References FALSE, and m_isTypedefValCached.
isAbstract()
bool MemberDefImpl::isAbstract () const override virtual
Implements MemberDef.
Definition at line 5339 of file memberdef.cpp.
{
  return m_memSpec.isAbstract();
}
References m_memSpec.
Referenced by getLabels().
isAddable()
bool MemberDefImpl::isAddable () const override virtual
Implements MemberDef.
Definition at line 5289 of file memberdef.cpp.
{
  return m_memSpec.isAddable();
}
References m_memSpec.
Referenced by getLabels(), and writeDeclaration().
isAssign()
bool MemberDefImpl::isAssign () const override virtual
Implements MemberDef.
Definition at line 5364 of file memberdef.cpp.
{
  return m_memSpec.isAssign();
}
References m_memSpec.
Referenced by getLabels().
isAttribute()
bool MemberDefImpl::isAttribute () const override virtual
Implements MemberDef.
Definition at line 5421 of file memberdef.cpp.
{
  return m_memSpec.isAttribute();
}
References m_memSpec.
Referenced by getLabels().
isBound()
bool MemberDefImpl::isBound () const override virtual
Implements MemberDef.
Definition at line 5436 of file memberdef.cpp.
{
  return m_memSpec.isBound();
}
References m_memSpec.
Referenced by getLabels().
isBriefSectionVisible()
bool MemberDefImpl::isBriefSectionVisible () const override virtual
This methods returns TRUE iff the brief section (also known as declaration section) is visible in the documentation.
Implements MemberDef.
Definition at line 2036 of file memberdef.cpp.
{
  bool extractStatic       = Config_getBool(EXTRACT_STATIC);
  bool extractPrivateVirtual = Config_getBool(EXTRACT_PRIV_VIRTUAL);
  bool hideUndocMembers    = Config_getBool(HIDE_UNDOC_MEMBERS);
  bool briefMemberDesc     = Config_getBool(BRIEF_MEMBER_DESC);
  bool repeatBrief         = Config_getBool(REPEAT_BRIEF);
  bool hideFriendCompounds = Config_getBool(HIDE_FRIEND_COMPOUNDS);
  //printf("Member %s grpId=%d docs=%s file=%s args=%s\n",
  //    qPrint(name()),
  //    0,"", //grpId,grpId==-1?"<none>":Doxygen::memberDocDict[grpId]->data(),
  //    "", //qPrint(getFileDef()->name()),
  //    argsString());
  bool hasDocs = hasDocumentation();
  // only include static members with file/namespace scope if
  // explicitly enabled in the config file
  bool visibleIfStatic = !(getClassDef()==nullptr &&
                           isStatic() &&
                           !extractStatic
                          );
  // only include members is the are documented or
  // HIDE_UNDOC_MEMBERS is NO in the config file
  bool visibleIfDocumented = (!hideUndocMembers ||
                              hasDocs ||
                              isDocumentedFriendClass()
                             );
  // hide members with no detailed description and brief descriptions
  // explicitly disabled.
  bool visibleIfEnabled = !(hideUndocMembers &&
                            documentation().isEmpty() &&
                            !briefMemberDesc &&
                            !repeatBrief
                           );
  // Hide friend (class|struct|union) declarations if HIDE_FRIEND_COMPOUNDS is true
  bool visibleIfFriendCompound = !(hideFriendCompounds &&
                                   isFriend() /*&&
                                   (m_type=="friend class" ||
                                    m_type=="friend struct" ||
                                    m_type=="friend union"
                                   )*/
                                  );
  // only include members that are non-private unless EXTRACT_PRIVATE is
  // set to YES or the member is part of a group. And as a special case,
  // private *documented* virtual members are shown if EXTRACT_PRIV_VIRTUAL
  // is set to YES
  bool visibleIfPrivate = (protectionLevelVisible(protection()) ||
                           m_mtype==MemberType::Friend ||
                           (m_prot==Protection::Private &&
                               (m_virt!=Specifier::Normal || isOverride() || isFinal()) && extractPrivateVirtual && hasDocs)
                          );
  // hide member if it overrides a member in a superclass and has no
  // documentation of its own
  //bool visibleIfDocVirtual = !reimplements() ||
  //                           !Config_getBool(INHERIT_DOCS) ||
  //                           hasDocs;
  // true if this member is a constructor or destructor
  bool cOrDTor = isConstructor() || isDestructor();
  // hide default constructors or destructors (no args) without
  // documentation
  bool visibleIfNotDefaultCDTor = !(cOrDTor &&
                                   (m_defArgList.empty() ||
                                    m_defArgList.front().type == "void"
                                   ) &&
                                   !hasDocs
                                  );
  //printf("visibleIfStatic=%d visibleIfDocumented=%d visibleIfEnabled=%d "
  //       "visibleIfPrivate=%d visibleIfNotDefaultCDTor=%d "
  //       "visibleIfFriendCompound=%d !annScope=%d\n",
  //       visibleIfStatic,visibleIfDocumented,
  //       visibleIfEnabled,visibleIfPrivate,visibleIfNotDefaultCDTor,
  //       visibleIfFriendCompound,!m_annScope);
  bool visible = visibleIfStatic     && visibleIfDocumented      &&
                 visibleIfEnabled    && visibleIfPrivate         &&
                 /*visibleIfDocVirtual &&*/ visibleIfNotDefaultCDTor &&
                 visibleIfFriendCompound &&
                 !m_annScope && !isHidden();
  //printf("MemberDefImpl::isBriefSectionVisible() %d\n",visible);
  return visible;
}
References Config_getBool, documentation(), Friend, getClassDef(), hasDocumentation(), isConstructor(), isDestructor(), isDocumentedFriendClass(), QCString::isEmpty(), isFinal(), isFriend(), DefinitionMixin< MemberDefMutable >::isHidden(), isOverride(), isStatic(), m_annScope, m_defArgList, m_mtype, m_prot, m_virt, Normal, Private, protection(), and protectionLevelVisible().
Referenced by writeEnumDeclaration().
isCallable()
bool MemberDefImpl::isCallable () const override virtual
Implements MemberDef.
Definition at line 5487 of file memberdef.cpp.
{
  return isFunction() ||
         isSlot() ||
         isSignal() ||
         isConstructor() ||
         isDestructor() ||
         isObjCMethod() ||
         isFriend();
}
References isConstructor(), isDestructor(), isFriend(), isFunction(), isObjCMethod(), isSignal(), and isSlot().
Referenced by sourceRefName().
isConstEval()
bool MemberDefImpl::isConstEval () const override virtual
Implements MemberDef.
Definition at line 5543 of file memberdef.cpp.
{
  return m_memSpec.isConstEval();
}
References m_memSpec.
Referenced by getLabels().
isConstExpr()
bool MemberDefImpl::isConstExpr () const override virtual
Implements MemberDef.
Definition at line 5538 of file memberdef.cpp.
{
  return m_memSpec.isConstExpr();
}
References m_memSpec.
Referenced by getLabels().
isConstInit()
bool MemberDefImpl::isConstInit () const override virtual
Implements MemberDef.
Definition at line 5548 of file memberdef.cpp.
{
  return m_memSpec.isConstInit();
}
References m_memSpec.
Referenced by getLabels().
isConstrained()
bool MemberDefImpl::isConstrained () const override virtual
Implements MemberDef.
Definition at line 5441 of file memberdef.cpp.
{
  return m_memSpec.isConstrained();
}
References m_memSpec.
Referenced by getLabels().
isConstructor()
bool MemberDefImpl::isConstructor () const override virtual
Implements MemberDef.
Definition at line 4690 of file memberdef.cpp.
{
  if (m_isConstructorCached==0)
  {
    MemberDefImpl *that = const_cast<MemberDefImpl*>(this);
    that->_computeIsConstructor();
  }
  ASSERT(m_isConstructorCached>0);
  return m_isConstructorCached==2;
}
References _computeIsConstructor(), ASSERT, m_isConstructorCached, and MemberDefImpl().
Referenced by isBriefSectionVisible(), isCallable(), and warnIfUndocumentedParams().
isCopy()
bool MemberDefImpl::isCopy () const override virtual
Implements MemberDef.
Definition at line 5359 of file memberdef.cpp.
{
  return m_memSpec.isCopy();
}
References m_memSpec.
Referenced by getLabels().
isCSharpProperty()
bool MemberDefImpl::isCSharpProperty () const override virtual
Implements MemberDef.
Definition at line 4951 of file memberdef.cpp.
{
  if (getClassDef() && getClassDef()->isCSharp() && isProperty()) return TRUE;
  return FALSE;
}
References FALSE, getClassDef(), isProperty(), and TRUE.
isDCOP()
bool MemberDefImpl::isDCOP () const override virtual
Implements MemberDef.
Definition at line 5214 of file memberdef.cpp.
{
  return m_mtype==MemberType::DCOP;
}
References DCOP, and m_mtype.
isDefault()
bool MemberDefImpl::isDefault () const override virtual
Implements MemberDef.
Definition at line 5406 of file memberdef.cpp.
{
  return m_memSpec.isDefault();
}
References m_memSpec.
Referenced by getLabels().
isDefine()
bool MemberDefImpl::isDefine () const override virtual
Implements MemberDef.
Definition at line 5204 of file memberdef.cpp.
{
  return m_mtype==MemberType::Define;
}
References Define, and m_mtype.
Referenced by writeDeclaration(), writeDocumentation(), and writeMemberDocSimple().
isDelete()
bool MemberDefImpl::isDelete () const override virtual
Implements MemberDef.
Definition at line 5411 of file memberdef.cpp.
{
  return m_memSpec.isDelete();
}
References m_memSpec.
Referenced by getLabels().
isDeleted()
bool MemberDefImpl::isDeleted () const override virtual
Implements MemberDef.
Definition at line 4300 of file memberdef.cpp.
{
  return m_defArgList.isDeleted();
}
References m_defArgList.
Referenced by warnIfUndocumented(), and warnIfUndocumentedParams().
isDestructor()
bool MemberDefImpl::isDestructor () const override virtual
Implements MemberDef.
Definition at line 4731 of file memberdef.cpp.
{
  if (m_isDestructorCached==0)
  {
    MemberDefImpl *that=const_cast<MemberDefImpl*>(this);
    that->_computeIsDestructor();
  }
  ASSERT(m_isDestructorCached>0);
  return m_isDestructorCached==2;
}
References _computeIsDestructor(), ASSERT, m_isDestructorCached, and MemberDefImpl().
Referenced by _computeIsDestructor(), isBriefSectionVisible(), isCallable(), and warnIfUndocumentedParams().
isDetailedSectionVisible()
bool MemberDefImpl::isDetailedSectionVisible (MemberListContainer container) const override virtual
Implements MemberDef.
Definition at line 2769 of file memberdef.cpp.
{
  bool separateMemPages = Config_getBool(SEPARATE_MEMBER_PAGES);
  bool inlineSimpleStructs = Config_getBool(INLINE_SIMPLE_STRUCTS);
  bool hideUndocMembers = Config_getBool(HIDE_UNDOC_MEMBERS);
  bool groupFilter = getGroupDef()==nullptr || container==MemberListContainer::Group || separateMemPages;
  bool fileFilter  = getNamespaceDef()==nullptr || !getNamespaceDef()->isLinkable() || container!=MemberListContainer::File;
  bool simpleFilter = (hasBriefDescription() || !hideUndocMembers) && inlineSimpleStructs &&
                      getClassDef()!=nullptr && getClassDef()->isSimple();
  bool visible = hasDetailedDescription() && groupFilter && fileFilter &&
                 !isReference();
  bool result = visible || simpleFilter;
  //printf("%s::isDetailedSectionVisible: %d groupFilter=%d fileFilter=%d\n",
  //    qPrint(name()),result,groupFilter,fileFilter);
  return result;
}
References Config_getBool, File, getClassDef(), getGroupDef(), getNamespaceDef(), Group, DefinitionMixin< MemberDefMutable >::hasBriefDescription(), hasDetailedDescription(), Definition::isLinkable(), isReference(), and ClassDef::isSimple().
isDictionary()
bool MemberDefImpl::isDictionary () const override virtual
Implements MemberDef.
Definition at line 5189 of file memberdef.cpp.
{
  return m_mtype==MemberType::Dictionary;
}
References Dictionary, and m_mtype.
isDocsForDefinition()
bool MemberDefImpl::isDocsForDefinition () const override virtual
Implements MemberDef.
Definition at line 5513 of file memberdef.cpp.
{
  return m_docsForDefinition;
}
References m_docsForDefinition.
Referenced by warnIfUndocumentedParams().
isDocumentedFriendClass()
bool MemberDefImpl::isDocumentedFriendClass () const override virtual
Implements MemberDef.
Definition at line 4290 of file memberdef.cpp.
{
  ClassDef *fcd=nullptr;
  QCString baseName=name();
  int i=baseName.find('<');
  if (i!=-1) baseName=baseName.left(i);
  return (isFriendClass() &&
         (fcd=getClass(baseName)) && fcd->isLinkable());
}
References QCString::find(), getClass(), isFriendClass(), Definition::isLinkable(), QCString::left(), and DefinitionMixin< MemberDefMutable >::name().
Referenced by isBriefSectionVisible(), and writeDeclaration().
isEnumerate()
bool MemberDefImpl::isEnumerate () const override virtual
Implements MemberDef.
Definition at line 5169 of file memberdef.cpp.
{
  return m_mtype==MemberType::Enumeration;
}
References Enumeration, and m_mtype.
Referenced by _writeEnumValues(), displayDefinition(), getDeclType(), hasDetailedDescription(), warnIfUndocumented(), and writeDocumentation().
isEnumStruct()
bool MemberDefImpl::isEnumStruct () const override virtual
Implements MemberDef.
Definition at line 5384 of file memberdef.cpp.
{
  return m_memSpec.isEnumStruct();
}
References m_memSpec.
Referenced by getDeclType(), and writeDocumentation().
isEnumValue()
bool MemberDefImpl::isEnumValue () const override virtual
Implements MemberDef.
Definition at line 5174 of file memberdef.cpp.
{
  return m_mtype==MemberType::EnumValue;
}
References EnumValue, and m_mtype.
Referenced by displayDefinition(), and writeDocumentation().
isEvent()
bool MemberDefImpl::isEvent () const override virtual
Implements MemberDef.
Definition at line 5224 of file memberdef.cpp.
{
  return m_mtype==MemberType::Event;
}
References Event, and m_mtype.
Referenced by writeDeclaration().
isExplicit()
bool MemberDefImpl::isExplicit () const override virtual
Implements MemberDef.
Definition at line 5249 of file memberdef.cpp.
{
  return m_memSpec.isExplicit();
}
References m_memSpec.
Referenced by getLabels().
isExternal()
bool MemberDefImpl::isExternal () const override virtual
Implements MemberDef.
Definition at line 5477 of file memberdef.cpp.
{
  return m_explExt;
}
References m_explExt.
Referenced by getLabels().
isFinal()
bool MemberDefImpl::isFinal () const override virtual
Implements MemberDef.
Definition at line 5314 of file memberdef.cpp.
{
  return m_memSpec.isFinal();
}
References m_memSpec.
Referenced by _computeLinkableInProject(), getLabels(), hasDetailedDescription(), isBriefSectionVisible(), and writeDeclaration().
isForeign()
bool MemberDefImpl::isForeign () const override virtual
Implements MemberDef.
Definition at line 5234 of file memberdef.cpp.
{
  return m_related == Relationship::Foreign;
}
References Foreign, and m_related.
Referenced by isRelatedOrFriend().
isFriend()
bool MemberDefImpl::isFriend () const override virtual
Implements MemberDef.
Definition at line 5209 of file memberdef.cpp.
{
  return m_mtype==MemberType::Friend;
}
References Friend, and m_mtype.
Referenced by getLabels(), hasDetailedDescription(), isBriefSectionVisible(), isCallable(), isFriendClass(), isNotFriend(), and isRelatedOrFriend().
isFriendClass()
bool MemberDefImpl::isFriendClass () const override virtual
Implements MemberDef.
Definition at line 6328 of file memberdef.cpp.
{
  return (isFriend() &&
         (m_type=="friend class" || m_type=="friend struct" ||
          m_type=="friend union"));
}
References isFriend(), and m_type.
Referenced by isDocumentedFriendClass(), and warnIfUndocumented().
isFriendToHide()
bool MemberDefImpl::isFriendToHide () const override virtual
Implements MemberDef.
Definition at line 6318 of file memberdef.cpp.
{
  bool hideFriendCompounds = Config_getBool(HIDE_FRIEND_COMPOUNDS);
  bool isFriendToHide = hideFriendCompounds &&
     (m_type=="friend class"  ||
      m_type=="friend struct" ||
      m_type=="friend union");
  return isFriendToHide;
}
References Config_getBool, isFriendToHide(), and m_type.
Referenced by isFriendToHide(), isNotFriend(), and isRelatedOrFriend().
isFunction()
bool MemberDefImpl::isFunction () const override virtual
Implements MemberDef.
Definition at line 5194 of file memberdef.cpp.
{
  return m_mtype==MemberType::Function;
}
References Function, and m_mtype.
Referenced by _hasVisibleCallerGraph(), _hasVisibleCallGraph(), isCallable(), isFunctionOrSignalSlot(), isObjCMethod(), warnIfUndocumentedParams(), and writeDocumentation().
isFunctionOrSignalSlot()
bool MemberDefImpl::isFunctionOrSignalSlot () const override virtual
Implements MemberDef.
Definition at line 6341 of file memberdef.cpp.
{
  return isFunction() || isSlot() || isSignal();
}
References isFunction(), isSignal(), and isSlot().
isFunctionPtr()
bool MemberDefImpl::isFunctionPtr () const override virtual
Implements MemberDef.
Definition at line 5199 of file memberdef.cpp.
{
  return m_mtype==MemberType::Variable && QCString(argsString()).find(")(")!=-1;
}
References argsString(), m_mtype, and Variable.
Referenced by writeMemberDocSimple().
isGettable()
bool MemberDefImpl::isGettable () const override virtual
Implements MemberDef.
Definition at line 5259 of file memberdef.cpp.
{
  return m_memSpec.isGettable();
}
References m_memSpec.
Referenced by getLabels(), and writeDeclaration().
isImplementation()
bool MemberDefImpl::isImplementation () const override virtual
Implements MemberDef.
Definition at line 5472 of file memberdef.cpp.
{
  return m_implOnly;
}
References m_implOnly.
Referenced by getLabels(), and writeDeclaration().
isInitonly()
bool MemberDefImpl::isInitonly () const override virtual
Implements MemberDef.
Definition at line 5334 of file memberdef.cpp.
{
  return m_memSpec.isInitonly();
}
References m_memSpec.
Referenced by getLabels().
isInline()
bool MemberDefImpl::isInline () const override virtual
Implements MemberDef.
Definition at line 5244 of file memberdef.cpp.
{
  return m_memSpec.isInline();
}
References m_memSpec.
Referenced by getLabels().
isLinkable()
bool MemberDefImpl::isLinkable () const override virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 1907 of file memberdef.cpp.
{
  if (m_templateMaster)
  {
    return m_templateMaster->isLinkable();
  }
  else
  {
    return isLinkableInProject() || isReference();
  }
}
References isLinkableInProject(), isReference(), and m_templateMaster.
Referenced by visibleInIndex(), writeDocumentation(), and writeLink().
isLinkableInProject()
bool MemberDefImpl::isLinkableInProject () const override virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 1896 of file memberdef.cpp.
{
  if (m_isLinkableCached==0)
  {
    MemberDefImpl *that = const_cast<MemberDefImpl*>(this);
    that->_computeLinkableInProject();
  }
  ASSERT(m_isLinkableCached>0);
  return m_isLinkableCached==2;
}
References _computeLinkableInProject(), ASSERT, m_isLinkableCached, and MemberDefImpl().
Referenced by addListReference(), isLinkable(), writeEnumDeclaration(), and writeTagFile().
isMaybeAmbiguous()
bool MemberDefImpl::isMaybeAmbiguous () const override virtual
Implements MemberDef.
Definition at line 5461 of file memberdef.cpp.
{
  return m_memSpec.isMaybeAmbiguous();
}
References m_memSpec.
Referenced by getLabels().
isMaybeDefault()
bool MemberDefImpl::isMaybeDefault () const override virtual
Implements MemberDef.
Definition at line 5456 of file memberdef.cpp.
{
  return m_memSpec.isMaybeDefault();
}
References m_memSpec.
Referenced by getLabels().
isMaybeVoid()
bool MemberDefImpl::isMaybeVoid () const override virtual
Implements MemberDef.
Definition at line 5451 of file memberdef.cpp.
{
  return m_memSpec.isMaybeVoid();
}
References m_memSpec.
Referenced by getLabels().
isMutable()
bool MemberDefImpl::isMutable () const override virtual
Implements MemberDef.
Definition at line 5254 of file memberdef.cpp.
{
  return m_memSpec.isMutable();
}
References m_memSpec.
Referenced by getLabels().
isNew()
bool MemberDefImpl::isNew () const override virtual
Implements MemberDef.
Definition at line 5319 of file memberdef.cpp.
{
  return m_memSpec.isNew();
}
References m_memSpec.
Referenced by getLabels().
isNoDiscard()
bool MemberDefImpl::isNoDiscard () const override virtual
Implements MemberDef.
Definition at line 5533 of file memberdef.cpp.
{
  return m_memSpec.isNoDiscard();
}
References m_memSpec.
Referenced by getLabels().
isNoExcept()
bool MemberDefImpl::isNoExcept () const override virtual
Implements MemberDef.
Definition at line 5416 of file memberdef.cpp.
{
  return m_memSpec.isNoExcept();
}
References m_memSpec.
Referenced by getLabels().
isNonAtomic()
bool MemberDefImpl::isNonAtomic () const override virtual
Implements MemberDef.
Definition at line 5354 of file memberdef.cpp.
{
  return m_memSpec.isNonAtomic();
}
References m_memSpec.
Referenced by getLabels().
isNotFriend()
bool MemberDefImpl::isNotFriend () const override virtual
Implements MemberDef.
Definition at line 6336 of file memberdef.cpp.
{
  return !(isFriend() && isFriendToHide());
}
References isFriend(), and isFriendToHide().
isObjCMethod()
bool MemberDefImpl::isObjCMethod () const override virtual
Implements MemberDef.
Definition at line 4939 of file memberdef.cpp.
{
  if (getClassDef() && getClassDef()->isObjectiveC() && isFunction()) return TRUE;
  return FALSE;
}
References FALSE, getClassDef(), isFunction(), and TRUE.
Referenced by addListReference(), getDeclType(), getLabels(), isCallable(), qualifiedName(), writeDeclaration(), writeDocumentation(), writeLink(), and writeMemberDocSimple().
isObjCProperty()
bool MemberDefImpl::isObjCProperty () const override virtual
Implements MemberDef.
Definition at line 4945 of file memberdef.cpp.
{
  if (getClassDef() && getClassDef()->isObjectiveC() && isProperty()) return TRUE;
  return FALSE;
}
References FALSE, getClassDef(), isProperty(), and TRUE.
Referenced by getLabels(), and writeDeclaration().
isOptional()
bool MemberDefImpl::isOptional () const override virtual
Implements MemberDef.
Definition at line 5344 of file memberdef.cpp.
{
  return m_memSpec.isOptional();
}
References m_memSpec.
Referenced by getLabels().
isOverride()
bool MemberDefImpl::isOverride () const override virtual
Implements MemberDef.
Definition at line 5329 of file memberdef.cpp.
{
  return m_memSpec.isOverride();
}
References m_memSpec.
Referenced by _computeLinkableInProject(), getLabels(), hasDetailedDescription(), isBriefSectionVisible(), and writeDeclaration().
isPrivateGettable()
bool MemberDefImpl::isPrivateGettable () const override virtual
Implements MemberDef.
Definition at line 5264 of file memberdef.cpp.
{
  return m_memSpec.isPrivateGettable();
}
References m_memSpec.
Referenced by getLabels(), and writeDeclaration().
isPrivateSettable()
bool MemberDefImpl::isPrivateSettable () const override virtual
Implements MemberDef.
Definition at line 5279 of file memberdef.cpp.
{
  return m_memSpec.isPrivateSettable();
}
References m_memSpec.
Referenced by getLabels(), and writeDeclaration().
isProperty()
bool MemberDefImpl::isProperty () const override virtual
Implements MemberDef.
Definition at line 5219 of file memberdef.cpp.
{
  return m_mtype==MemberType::Property;
}
References m_mtype, and Property.
Referenced by isCSharpProperty(), isObjCProperty(), and writeDeclaration().
isProtectedGettable()
bool MemberDefImpl::isProtectedGettable () const override virtual
Implements MemberDef.
Definition at line 5269 of file memberdef.cpp.
{
  return m_memSpec.isProtectedGettable();
}
References m_memSpec.
Referenced by getLabels(), and writeDeclaration().
isProtectedSettable()
bool MemberDefImpl::isProtectedSettable () const override virtual
Implements MemberDef.
Definition at line 5284 of file memberdef.cpp.
{
  return m_memSpec.isProtectedSettable();
}
References m_memSpec.
Referenced by getLabels(), and writeDeclaration().
isPrototype()
bool MemberDefImpl::isPrototype () const override virtual
Implements MemberDef.
Definition at line 5563 of file memberdef.cpp.
{
  return m_proto;
}
References m_proto.
isPublished()
bool MemberDefImpl::isPublished () const override virtual
Implements MemberDef.
Definition at line 5466 of file memberdef.cpp.
{
  return m_memSpec.isPublished();
}
References m_memSpec.
Referenced by getLabels().
isRaisable()
bool MemberDefImpl::isRaisable () const override virtual
Implements MemberDef.
Definition at line 5299 of file memberdef.cpp.
{
  return m_memSpec.isRaisable();
}
References m_memSpec.
Referenced by getLabels(), and writeDeclaration().
isReadable()
bool MemberDefImpl::isReadable () const override virtual
Implements MemberDef.
Definition at line 5304 of file memberdef.cpp.
{
  return m_memSpec.isReadable();
}
References m_memSpec.
Referenced by getLabels().
isReadonly()
bool MemberDefImpl::isReadonly () const override virtual
Implements MemberDef.
Definition at line 5431 of file memberdef.cpp.
{
  return m_memSpec.isReadonly();
}
References m_memSpec.
Referenced by getLabels().
isReference()
bool MemberDefImpl::isReference () const override virtual
Returns TRUE if this definition is imported via a tag file.
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 6351 of file memberdef.cpp.
{
  return DefinitionMixin::isReference() ||
         (m_templateMaster && m_templateMaster->isReference());
}
References DefinitionMixin< Base >::isReference(), and m_templateMaster.
Referenced by _computeLinkableInProject(), isDetailedSectionVisible(), isLinkable(), warnIfUndocumented(), warnIfUndocumentedParams(), and writeDeclaration().
isReimplementedBy()
bool MemberDefImpl::isReimplementedBy (const ClassDef * cd) const override virtual
Implements MemberDef.
Definition at line 1600 of file memberdef.cpp.
{
  if (cd)
  {
    for (const auto &md : m_redefinedBy)
    {
      const ClassDef *mcd = md->getClassDef();
      if (mcd)
      {
        if (cd==mcd || cd->isBaseClass(mcd,TRUE))
        {
          return TRUE;
        }
      }
    }
  }
  return FALSE;
}
References FALSE, ClassDef::isBaseClass(), m_redefinedBy, and TRUE.
isRelated()
bool MemberDefImpl::isRelated () const override virtual
Implements MemberDef.
Definition at line 5229 of file memberdef.cpp.
{
  return m_related == Relationship::Related;
}
References m_related, and Related.
Referenced by addListReference(), getLabels(), isRelatedOrFriend(), and writeLink().
isRelatedOrFriend()
bool MemberDefImpl::isRelatedOrFriend () const override virtual
Implements MemberDef.
Definition at line 6346 of file memberdef.cpp.
{
  return isRelated() || isForeign() || (isFriend() && !isFriendToHide());
}
References isForeign(), isFriend(), isFriendToHide(), and isRelated().
isRemovable()
bool MemberDefImpl::isRemovable () const override virtual
Implements MemberDef.
Definition at line 5294 of file memberdef.cpp.
{
  return m_memSpec.isRemovable();
}
References m_memSpec.
Referenced by getLabels(), and writeDeclaration().
isRequired()
bool MemberDefImpl::isRequired () const override virtual
Implements MemberDef.
Definition at line 5349 of file memberdef.cpp.
{
  return m_memSpec.isRequired();
}
References m_memSpec.
Referenced by getLabels().
isRetain()
bool MemberDefImpl::isRetain () const override virtual
Implements MemberDef.
Definition at line 5369 of file memberdef.cpp.
{
  return m_memSpec.isRetain();
}
References m_memSpec.
Referenced by getLabels().
isSealed()
bool MemberDefImpl::isSealed () const override virtual
Implements MemberDef.
Definition at line 5324 of file memberdef.cpp.
{
  return m_memSpec.isSealed();
}
References m_memSpec.
Referenced by getLabels().
isSequence()
bool MemberDefImpl::isSequence () const override virtual
Implements MemberDef.
Definition at line 5184 of file memberdef.cpp.
{
  return m_mtype==MemberType::Sequence;
}
References m_mtype, and Sequence.
isSettable()
bool MemberDefImpl::isSettable () const override virtual
Implements MemberDef.
Definition at line 5274 of file memberdef.cpp.
{
  return m_memSpec.isSettable();
}
References m_memSpec.
Referenced by getLabels(), and writeDeclaration().
isSignal()
bool MemberDefImpl::isSignal () const override virtual
Implements MemberDef.
Definition at line 5154 of file memberdef.cpp.
{
  return m_mtype==MemberType::Signal;
}
References m_mtype, and Signal.
Referenced by _hasVisibleCallerGraph(), _hasVisibleCallGraph(), getLabels(), isCallable(), and isFunctionOrSignalSlot().
isSliceLocal()
bool MemberDefImpl::isSliceLocal () const override virtual
Implements MemberDef.
Definition at line 5528 of file memberdef.cpp.
{
  return m_memSpec.isLocal();
}
References m_memSpec.
Referenced by displayDefinition(), and writeDocumentation().
isSlot()
bool MemberDefImpl::isSlot () const override virtual
Implements MemberDef.
Definition at line 5159 of file memberdef.cpp.
{
  return m_mtype==MemberType::Slot;
}
References m_mtype, and Slot.
Referenced by _hasVisibleCallerGraph(), _hasVisibleCallGraph(), getLabels(), isCallable(), and isFunctionOrSignalSlot().
isStatic()
bool MemberDefImpl::isStatic () const override virtual
Implements MemberDef.
Definition at line 5239 of file memberdef.cpp.
{
  return m_stat;
}
References m_stat.
Referenced by displayDefinition(), getLabels(), hasDetailedDescription(), isBriefSectionVisible(), objCMethodName(), qualifiedName(), sourceRefName(), visibleInIndex(), writeDeclaration(), writeDocumentation(), writeLink(), and writeTagFile().
isStrong()
bool MemberDefImpl::isStrong () const override virtual
Implements MemberDef.
Definition at line 5379 of file memberdef.cpp.
{
  return m_memSpec.isStrong();
}
References m_memSpec.
Referenced by getDeclType(), getLabels(), getScopeString(), writeDocumentation(), and writeTagFile().
isStrongEnumValue()
bool MemberDefImpl::isStrongEnumValue () const override virtual
Implements MemberDef.
Definition at line 5389 of file memberdef.cpp.
{
  return m_mtype==MemberType::EnumValue &&
         m_enumScope &&
         m_enumScope->isStrong();
}
References EnumValue, m_enumScope, and m_mtype.
isTemplateSpecialization()
bool MemberDefImpl::isTemplateSpecialization () const override virtual
Implements MemberDef.
Definition at line 5482 of file memberdef.cpp.
{
  return m_tspec;
}
References m_tspec.
Referenced by writeDocumentation().
isTransient()
bool MemberDefImpl::isTransient () const override virtual
Implements MemberDef.
Definition at line 5446 of file memberdef.cpp.
{
  return m_memSpec.isTransient();
}
References m_memSpec.
Referenced by getLabels().
isTypeAlias()
bool MemberDefImpl::isTypeAlias () const override virtual
Implements MemberDef.
Definition at line 5401 of file memberdef.cpp.
{
  return m_memSpec.isAlias();
}
References m_memSpec.
Referenced by getDeclType(), writeDeclaration(), and writeDocumentation().
isTypedef()
bool MemberDefImpl::isTypedef () const override virtual
Implements MemberDef.
Definition at line 5179 of file memberdef.cpp.
{
  return m_mtype==MemberType::Typedef;
}
References m_mtype, and Typedef.
Referenced by fieldType(), getDeclType(), writeDeclaration(), and writeDocumentation().
isTypedefValCached()
bool MemberDefImpl::isTypedefValCached () const override virtual
Implements MemberDef.
Definition at line 5717 of file memberdef.cpp.
{
  return m_isTypedefValCached;
}
References m_isTypedefValCached.
isUNOProperty()
bool MemberDefImpl::isUNOProperty () const override virtual
Implements MemberDef.
Definition at line 5426 of file memberdef.cpp.
{
  return m_memSpec.isProperty();
}
References m_memSpec.
Referenced by getLabels().
isUnretained()
bool MemberDefImpl::isUnretained () const override virtual
Implements MemberDef.
Definition at line 5396 of file memberdef.cpp.
{
  return m_memSpec.isUnretained();
}
References m_memSpec.
Referenced by getLabels().
isVariable()
bool MemberDefImpl::isVariable () const override virtual
Implements MemberDef.
Definition at line 5164 of file memberdef.cpp.
{
  return m_mtype==MemberType::Variable;
}
References m_mtype, and Variable.
Referenced by writeDocumentation(), and writeMemberDocSimple().
isWeak()
bool MemberDefImpl::isWeak () const override virtual
Implements MemberDef.
Definition at line 5374 of file memberdef.cpp.
{
  return m_memSpec.isWeak();
}
References m_memSpec.
Referenced by getLabels().
isWritable()
bool MemberDefImpl::isWritable () const override virtual
Implements MemberDef.
Definition at line 5309 of file memberdef.cpp.
{
  return m_memSpec.isWritable();
}
References m_memSpec.
Referenced by getLabels().
livesInsideEnum()
bool MemberDefImpl::livesInsideEnum () const override virtual
Implements MemberDef.
Definition at line 5523 of file memberdef.cpp.
{
  return m_livesInsideEnum;
}
References m_livesInsideEnum.
Referenced by setEnumScope().
makeForeign()
void MemberDefImpl::makeForeign () override virtual
Implements MemberDefMutable.
Definition at line 5872 of file memberdef.cpp.
{
  m_related = Relationship::Foreign;
  m_isLinkableCached = 0;
}
References Foreign, m_isLinkableCached, and m_related.
makeImplementationDetail()
void MemberDefImpl::makeImplementationDetail () override virtual
Implements MemberDefMutable.
Definition at line 5948 of file memberdef.cpp.
{
  m_implOnly=TRUE;
}
References m_implOnly, and TRUE.
makeRelated()
void MemberDefImpl::makeRelated () override virtual
Implements MemberDefMutable.
Definition at line 5866 of file memberdef.cpp.
{
  m_related = Relationship::Related;
  m_isLinkableCached = 0;
}
References m_isLinkableCached, m_related, and Related.
memberDeclaration()
MemberDef * MemberDefImpl::memberDeclaration () const override virtual
Implements MemberDef.
Definition at line 5743 of file memberdef.cpp.
{
  return m_memDec;
}
References m_memDec.
memberDefinition()
MemberDef * MemberDefImpl::memberDefinition () const override virtual
Implements MemberDef.
Definition at line 5738 of file memberdef.cpp.
{
  return m_memDef;
}
References m_memDef.
memberType()
MemberType MemberDefImpl::memberType () const override virtual
Implements MemberDef.
Definition at line 5149 of file memberdef.cpp.
{
  return m_mtype;
}
References m_mtype.
Referenced by codeSymbolType().
memberTypeName()
QCString MemberDefImpl::memberTypeName () const override virtual
Implements MemberDef.
Definition at line 4048 of file memberdef.cpp.
{
  switch (m_mtype)
  {
    case MemberType::Define:      return "macro definition";
    case MemberType::Function:    return "function";
    case MemberType::Variable:    return "variable";
    case MemberType::Typedef:     return "typedef";
    case MemberType::Enumeration: return "enumeration";
    case MemberType::EnumValue:   return "enumvalue";
    case MemberType::Signal:      return "signal";
    case MemberType::Slot:        return "slot";
    case MemberType::Friend:      return "friend";
    case MemberType::DCOP:        return "dcop";
    case MemberType::Property:    return "property";
    case MemberType::Event:       return "event";
    case MemberType::Interface:   return "interface";
    case MemberType::Service:     return "service";
    case MemberType::Sequence:    return "sequence";
    case MemberType::Dictionary:  return "dictionary";
    default:          return "unknown";
  }
}
References DCOP, Define, Dictionary, Enumeration, EnumValue, Event, Friend, Function, Interface, m_mtype, Property, Sequence, Service, Signal, Slot, Typedef, and Variable.
Referenced by warnIfUndocumented().
mergeMemberSpecifiers()
void MemberDefImpl::mergeMemberSpecifiers (TypeSpecifier s) override virtual
Implements MemberDefMutable.
Definition at line 5816 of file memberdef.cpp.
{
  m_memSpec.merge(s);
}
References m_memSpec.
moveArgumentList()
void MemberDefImpl::moveArgumentList (std::unique_ptr< ArgumentList > al) override virtual
Implements MemberDefMutable.
Definition at line 4867 of file memberdef.cpp.
{
  m_defArgList = *al;
}
References m_defArgList.
moveDeclArgumentList()
void MemberDefImpl::moveDeclArgumentList (std::unique_ptr< ArgumentList > al) override virtual
Implements MemberDefMutable.
Definition at line 4872 of file memberdef.cpp.
{
  m_declArgList = *al;
}
References m_declArgList.
moveTo()
void MemberDefImpl::moveTo (Definition * scope) override virtual
Implements MemberDef.
Definition at line 1545 of file memberdef.cpp.
{
   setOuterScope(scope);
   if (scope->definitionType()==Definition::TypeClass)
   {
     m_classDef = toClassDef(scope);
   }
   else if (scope->definitionType()==Definition::TypeFile)
   {
     m_fileDef = toFileDef(scope);
   }
   else if (scope->definitionType()==Definition::TypeModule)
   {
     m_moduleDef = toModuleDef(scope);
   }
   else if (scope->definitionType()==Definition::TypeNamespace)
   {
     m_nspace = toNamespaceDef(scope);
   }
   m_isLinkableCached = 0;
   m_isConstructorCached = 0;
}
References Definition::definitionType(), m_classDef, m_fileDef, m_isConstructorCached, m_isLinkableCached, m_moduleDef, m_nspace, DefinitionMixin< MemberDefMutable >::setOuterScope(), toClassDef(), toFileDef(), toModuleDef(), toNamespaceDef(), Definition::TypeClass, Definition::TypeFile, Definition::TypeModule, and Definition::TypeNamespace.
numberOfFlowKeyWords()
int MemberDefImpl::numberOfFlowKeyWords () const override virtual
Implements MemberDef.
Definition at line 6108 of file memberdef.cpp.
{
  return m_numberOfFlowKW;
}
References m_numberOfFlowKW.
objCMethodName()
QCString MemberDefImpl::objCMethodName (bool localLink, bool showStatic) const override virtual
Implements MemberDef.
Definition at line 4992 of file memberdef.cpp.
{
  QCString qm;
  if (showStatic)
  {
    if (isStatic()) qm="+ "; else qm="- ";
  }
  qm+=name();
  if (!localLink) // link to method of same class
  {
    qm+=" (";
    qm+=getClassDef()->name();
    qm+=")";
  }
  return qm;
}
References getClassDef(), isStatic(), Definition::name(), and DefinitionMixin< MemberDefMutable >::name().
overrideCallerGraph()
void MemberDefImpl::overrideCallerGraph (bool e) override virtual
Implements MemberDefMutable.
Definition at line 4911 of file memberdef.cpp.
{
  m_hasCallerGraph=e;
  if (e) Doxygen::parseSourcesNeeded = TRUE;
}
References m_hasCallerGraph, Doxygen::parseSourcesNeeded, and TRUE.
overrideCallGraph()
void MemberDefImpl::overrideCallGraph (bool e) override virtual
Implements MemberDefMutable.
Definition at line 4905 of file memberdef.cpp.
{
  m_hasCallGraph=e;
  if (e) Doxygen::parseSourcesNeeded = TRUE;
}
References m_hasCallGraph, Doxygen::parseSourcesNeeded, and TRUE.
overrideEnumValues()
void MemberDefImpl::overrideEnumValues (bool e) override virtual
Implements MemberDefMutable.
Definition at line 4929 of file memberdef.cpp.
{
  m_hasEnumValues=e;
}
References m_hasEnumValues.
overrideInlineSource()
void MemberDefImpl::overrideInlineSource (bool e) override virtual
Implements MemberDefMutable.
Definition at line 4934 of file memberdef.cpp.
{
  m_hasInlineSource=e;
}
References m_hasInlineSource.
overrideReferencedByRelation()
void MemberDefImpl::overrideReferencedByRelation (bool e) override virtual
Implements MemberDefMutable.
Definition at line 4917 of file memberdef.cpp.
{
  m_hasReferencedByRelation=e;
  if (e) Doxygen::parseSourcesNeeded = TRUE;
}
References m_hasReferencedByRelation, Doxygen::parseSourcesNeeded, and TRUE.
overrideReferencesRelation()
void MemberDefImpl::overrideReferencesRelation (bool e) override virtual
Implements MemberDefMutable.
Definition at line 4923 of file memberdef.cpp.
{
  m_hasReferencesRelation=e;
  if (e) Doxygen::parseSourcesNeeded = TRUE;
}
References m_hasReferencesRelation, Doxygen::parseSourcesNeeded, and TRUE.
protection()
Protection MemberDefImpl::protection () const override virtual
Implements MemberDef.
Definition at line 5144 of file memberdef.cpp.
{
  return m_prot;
}
References m_prot.
Referenced by getLabels(), hasDetailedDescription(), isBriefSectionVisible(), and writeDeclaration().
qualifiedName()
QCString MemberDefImpl::qualifiedName () const override virtual
Returns the fully qualified name of this definition
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 4957 of file memberdef.cpp.
{
  if (isObjCMethod())
  {
    QCString qm;
    if (isStatic()) qm="+"; else qm="-";
    qm+="[";
    qm+=getClassDef()->name()+" ";
    qm+=name();
    qm+="]";
    return qm;
  }
  else if (m_enumScope && m_enumScope->isStrong())
  {
    return m_enumScope->qualifiedName()+
           getLanguageSpecificSeparator(getLanguage())+
           localName();
  }
  else
  {
    return DefinitionMixin::qualifiedName();
  }
}
References getClassDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), isObjCMethod(), isStatic(), DefinitionMixin< MemberDefMutable >::localName(), m_enumScope, Definition::name(), DefinitionMixin< MemberDefMutable >::name(), and DefinitionMixin< Base >::qualifiedName().
Referenced by _computeLinkableInProject(), _writeCallerGraph(), _writeCallGraph(), addListReference(), warnIfUndocumented(), warnIfUndocumentedParams(), and writeTagFile().
reimplementedBy()
const MemberVector & MemberDefImpl::reimplementedBy () const override virtual
Implements MemberDef.
Definition at line 1595 of file memberdef.cpp.
{
  return m_redefinedBy;
}
References m_redefinedBy.
Referenced by _countReimplementedBy(), and _writeReimplementedBy().
reimplements()
const MemberDef * MemberDefImpl::reimplements () const override virtual
Implements MemberDef.
Definition at line 1590 of file memberdef.cpp.
{
  return m_redefines;
}
References m_redefines.
Referenced by _isReimplements(), _writeReimplements(), and virtualness().
relatedAlso()
ClassDef * MemberDefImpl::relatedAlso () const override virtual
Implements MemberDef.
Definition at line 5498 of file memberdef.cpp.
{
  return m_relatedAlso;
}
References m_relatedAlso.
requiresClause()
QCString MemberDefImpl::requiresClause () const override virtual
Implements MemberDef.
Definition at line 6039 of file memberdef.cpp.
{
  return m_requiresClause;
}
References m_requiresClause.
resolveAlias() [1/2]
const MemberDef * MemberDefImpl::resolveAlias () const inline override virtual
Implements MemberDef.
Definition at line 66 of file memberdef.cpp.
{ return this; }
resolveAlias() [2/2]
MemberDef * MemberDefImpl::resolveAlias () inline override virtual
Implements MemberDef.
Definition at line 65 of file memberdef.cpp.
{ return this; }
resolveUnnamedParameters()
void MemberDefImpl::resolveUnnamedParameters (const MemberDef * md) override virtual
Implements MemberDefMutable.
Definition at line 5578 of file memberdef.cpp.
{
  ArgumentList &decAl = m_declArgList;
  ArgumentList &defAl = m_defArgList;
  const ArgumentList &decAlSrc = md->declArgumentList();
  const ArgumentList &defAlSrc = md->argumentList();
  auto decSrc = decAlSrc.begin(), defSrc = defAlSrc.begin();
  for (auto decIt = decAl.begin(), defIt = defAl.begin();
       decIt != decAl.end() && defIt != defAl.end() && decSrc != decAlSrc.end() && defSrc != defAlSrc.end();
       ++decIt, ++defIt, ++decSrc, ++defSrc++)
  {
    Argument &decA = *decIt;
    Argument &defA = *defIt;
    const Argument &decAS = *decSrc;
    const Argument &defAS = *defSrc;
    if (decA.name.isEmpty())
    {
      if (!defA.name.isEmpty())
      {
        decA.name = defA.name;
      }
      else if (!decAS.name.isEmpty())
      {
        decA.name = decAS.name;
      }
      else if (!defAS.name.isEmpty())
      {
        decA.name = defAS.name;
      }
    }
    if (defA.name.isEmpty())
    {
      if (!decA.name.isEmpty())
      {
        defA.name = decA.name;
      }
      else if (!decAS.name.isEmpty())
      {
        defA.name = decAS.name;
      }
      else if (!defAS.name.isEmpty())
      {
        defA.name = defAS.name;
      }
    }
  }
}
References MemberDef::argumentList(), ArgumentList::begin(), MemberDef::declArgumentList(), ArgumentList::end(), QCString::isEmpty(), m_declArgList, m_defArgList, and Argument::name.
setAccessorType()
void MemberDefImpl::setAccessorType (ClassDef * cd, const QCString & t) override virtual
Implements MemberDefMutable.
Definition at line 4887 of file memberdef.cpp.
{
  m_accessorClass = cd;
  m_accessorType = t;
}
References m_accessorClass, and m_accessorType.
setAnchor()
void MemberDefImpl::setAnchor () override virtual
Implements MemberDefMutable.
Definition at line 4327 of file memberdef.cpp.
{
  QCString memAnchor = name();
  if (!m_args.isEmpty()) memAnchor+=m_args;
  if (m_memSpec.isAlias()) // this is for backward compatibility
  {
    memAnchor.prepend(" = "+m_initializer);
  }
  memAnchor.prepend(definition()); // actually the method name is now included
            // twice, which is silly, but we keep it this way for backward
            // compatibility.
  // include number of template arguments as well,
  // to distinguish between two template
  // specializations that only differ in the template parameters.
  if (m_tArgList.hasParameters())
  {
    char buf[20];
    qsnprintf(buf,20,"%d:",static_cast<int>(m_tArgList.size()));
    buf[19]='\0';
    memAnchor.prepend(buf);
  }
  if (!m_requiresClause.isEmpty())
  {
    memAnchor+=" "+m_requiresClause;
  }
  // convert to md5 hash
  uint8_t md5_sig[16];
  char sigStr[33];
  MD5Buffer(memAnchor.data(),static_cast<unsigned int>(memAnchor.length()),md5_sig);
  MD5SigToString(md5_sig,sigStr);
  m_anc = QCString("a")+sigStr;
}
References QCString::data(), definition(), QCString::length(), m_anc, m_args, m_initializer, m_memSpec, m_requiresClause, m_tArgList, DefinitionMixin< MemberDefMutable >::name(), QCString::prepend(), and qsnprintf.
setAnonymousEnumType()
void MemberDefImpl::setAnonymousEnumType (const MemberDef * md) override virtual
Implements MemberDefMutable.
Definition at line 5905 of file memberdef.cpp.
{
  m_annEnumType = md;
}
References m_annEnumType.
setArgsString()
void MemberDefImpl::setArgsString (const QCString & as) override virtual
Implements MemberDefMutable.
Definition at line 5883 of file memberdef.cpp.
{
  m_args = as;
}
References m_args.
setBitfields()
void MemberDefImpl::setBitfields (const QCString & s) override virtual
Implements MemberDefMutable.
Definition at line 5838 of file memberdef.cpp.
{
  m_bitfields = QCString(s).simplifyWhiteSpace();
}
References m_bitfields.
setBriefDescription()
void MemberDefImpl::setBriefDescription (const QCString & b, const QCString & briefFile, int briefLine) override virtual
Sets the brief description of this definition to b. A dot is added to the sentence if not available.
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 1878 of file memberdef.cpp.
{
  DefinitionMixin::setBriefDescription(b,briefFile,briefLine);
  m_isLinkableCached = 0;
}
References Definition::briefFile(), DefinitionMixin< MemberDefMutable >::briefFile(), Definition::briefLine(), DefinitionMixin< MemberDefMutable >::briefLine(), m_isLinkableCached, and DefinitionMixin< Base >::setBriefDescription().
setCategory()
void MemberDefImpl::setCategory (ClassDef * def) override virtual
Implements MemberDefMutable.
Definition at line 6009 of file memberdef.cpp.
{
  m_category = def;
}
References m_category.
setCategoryRelation()
void MemberDefImpl::setCategoryRelation (const MemberDef * md) override virtual
Implements MemberDefMutable.
Definition at line 6019 of file memberdef.cpp.
{
  m_categoryRelation = md;
}
References m_categoryRelation.
setDeclFile()
void MemberDefImpl::setDeclFile (const QCString & df, int line, int column) override virtual
Implements MemberDefMutable.
Definition at line 5936 of file memberdef.cpp.
{
  m_declFileName = df;
  m_declLine = line;
  m_declColumn = column;
}
References m_declColumn, m_declFileName, and m_declLine.
Referenced by setExplicitExternal(), and setPrototype().
setDefinition()
void MemberDefImpl::setDefinition (const QCString & d) override virtual
Implements MemberDefMutable.
Definition at line 5782 of file memberdef.cpp.
{
  m_def=d;
}
References m_def.
setDefinitionTemplateParameterLists()
void MemberDefImpl::setDefinitionTemplateParameterLists (const ArgumentLists & lists) override virtual
Implements MemberDefMutable.
Definition at line 1920 of file memberdef.cpp.
{
  m_defTmpArgLists = lists;
}
References m_defTmpArgLists.
setDocsForDefinition()
void MemberDefImpl::setDocsForDefinition (bool b) override virtual
Implements MemberDefMutable.
Definition at line 5979 of file memberdef.cpp.
{
  m_docsForDefinition = b;
}
References m_docsForDefinition.
setDocumentation()
void MemberDefImpl::setDocumentation (const QCString & d, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE) override virtual
Sets the documentation of this definition to d.
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 1872 of file memberdef.cpp.
{
  DefinitionMixin::setDocumentation(d,docFile,docLine,stripWhiteSpace);
  m_isLinkableCached = 0;
}
References Definition::docFile(), DefinitionMixin< MemberDefMutable >::docFile(), Definition::docLine(), DefinitionMixin< MemberDefMutable >::docLine(), m_isLinkableCached, DefinitionMixin< Base >::setDocumentation(), and stripWhiteSpace().
setDocumentedEnumValues()
void MemberDefImpl::setDocumentedEnumValues (bool value) override virtual
Implements MemberDefMutable.
Definition at line 5900 of file memberdef.cpp.
{
  m_docEnumValues=value;
}
References m_docEnumValues.
setEnumBaseType()
void MemberDefImpl::setEnumBaseType (const QCString & type) override virtual
Implements MemberDefMutable.
Definition at line 6024 of file memberdef.cpp.
{
  m_enumBaseType = type;
}
References m_enumBaseType.
setEnumClassScope()
void MemberDefImpl::setEnumClassScope (ClassDef * cd) override virtual
Implements MemberDefMutable.
Definition at line 5893 of file memberdef.cpp.
{
  m_classDef = cd;
  m_isLinkableCached = 0;
  m_isConstructorCached = 0;
}
References m_classDef, m_isConstructorCached, and m_isLinkableCached.
setEnumScope()
void MemberDefImpl::setEnumScope (MemberDef * md, bool livesInsideEnum = FALSE) override virtual
Implements MemberDefMutable.
Definition at line 4377 of file memberdef.cpp.
{
  m_enumScope=md;
  m_livesInsideEnum=livesInsideEnum;
  if (md->getGroupDef())
  {
    m_group           = md->getGroupDef();
    m_grouppri        = md->getGroupPri();
    m_groupFileName   = md->getGroupFileName();
    m_groupStartLine  = md->getGroupStartLine();
    m_groupHasDocs    = md->getGroupHasDocs();
    m_isLinkableCached = 0;
  }
}
References MemberDef::getGroupDef(), MemberDef::getGroupFileName(), MemberDef::getGroupHasDocs(), MemberDef::getGroupPri(), MemberDef::getGroupStartLine(), livesInsideEnum(), m_enumScope, m_group, m_groupFileName, m_groupHasDocs, m_grouppri, m_groupStartLine, m_isLinkableCached, and m_livesInsideEnum.
setExplicitExternal()
void MemberDefImpl::setExplicitExternal (bool b, const QCString & df, int line, int column) override virtual
Implements MemberDefMutable.
Definition at line 5923 of file memberdef.cpp.
{
  m_explExt=b;
  if (b)
  {
    setDeclFile(df,line,column);
  }
  else
  {
    setDefFile(df,line,column);
  }
}
References m_explExt, setDeclFile(), and DefinitionMixin< MemberDefMutable >::setDefFile().
setFileDef()
void MemberDefImpl::setFileDef (FileDef * fd) override virtual
Implements MemberDefMutable.
Definition at line 5787 of file memberdef.cpp.
{
  m_fileDef=fd;
  m_isLinkableCached = 0;
  m_isConstructorCached = 0;
  m_isDestructorCached = 0;
}
References m_fileDef, m_isConstructorCached, m_isDestructorCached, and m_isLinkableCached.
setFormalTemplateArguments()
void MemberDefImpl::setFormalTemplateArguments (const ArgumentList & al) override virtual
Implements MemberDefMutable.
Definition at line 5974 of file memberdef.cpp.
{
  m_formalTemplateArguments = al;
}
References m_formalTemplateArguments.
setFromAnonymousMember()
void MemberDefImpl::setFromAnonymousMember (MemberDef * m) override virtual
Implements MemberDefMutable.
Definition at line 5958 of file memberdef.cpp.
{
  m_annMemb=m;
}
References m_annMemb.
setFromAnonymousScope()
void MemberDefImpl::setFromAnonymousScope (bool b) override virtual
Implements MemberDefMutable.
Definition at line 5953 of file memberdef.cpp.
{
  m_annScope=b;
}
References m_annScope.
setGroupAlias()
void MemberDefImpl::setGroupAlias (const MemberDef * md) override virtual
Implements MemberDefMutable.
Definition at line 5984 of file memberdef.cpp.
{
  m_groupAlias = md;
}
References m_groupAlias.
setGroupDef()
void MemberDefImpl::setGroupDef (GroupDef * gd, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs, MemberDef * member = nullptr) override virtual
Implements MemberDefMutable.
Definition at line 4363 of file memberdef.cpp.
{
  //printf("%s MemberDefImpl::setGroupDef(%s)\n",qPrint(name()),qPrint(gd->name()));
  m_group=gd;
  m_grouppri=pri;
  m_groupFileName=fileName;
  m_groupStartLine=startLine;
  m_groupHasDocs=hasDocs;
  m_groupMember=member;
  m_isLinkableCached = 0;
}
References m_group, m_groupFileName, m_groupHasDocs, m_groupMember, m_grouppri, m_groupStartLine, and m_isLinkableCached.
setHidden()
void MemberDefImpl::setHidden (bool b) override virtual
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 1890 of file memberdef.cpp.
{
  DefinitionMixin::setHidden(b);
  m_isLinkableCached = 0;
}
References m_isLinkableCached, and DefinitionMixin< Base >::setHidden().
setInbodyDocumentation()
void MemberDefImpl::setInbodyDocumentation (const QCString & d, const QCString & docFile, int docLine) override virtual
Set the documentation that was found inside the body of an item. If there was already some documentation set, the new documentation will be appended.
Reimplemented from DefinitionMixin< MemberDefMutable >.
Definition at line 1884 of file memberdef.cpp.
{
  DefinitionMixin::setInbodyDocumentation(d,inbodyFile,inbodyLine);
  m_isLinkableCached = 0;
}
References Definition::inbodyFile(), DefinitionMixin< MemberDefMutable >::inbodyFile(), Definition::inbodyLine(), DefinitionMixin< MemberDefMutable >::inbodyLine(), m_isLinkableCached, and DefinitionMixin< Base >::setInbodyDocumentation().
setInheritsDocsFrom()
void MemberDefImpl::setInheritsDocsFrom (const MemberDef * md) override virtual
Implements MemberDefMutable.
Definition at line 5878 of file memberdef.cpp.
{
  m_docProvider = md;
}
References m_docProvider.
setInitializer()
void MemberDefImpl::setInitializer (const QCString & i) override virtual
Implements MemberDefMutable.
Definition at line 4471 of file memberdef.cpp.
{
  m_initializer=initializer;
  int l=static_cast<int>(m_initializer.length());
  int p=l-1;
  while (p>=0 && isspace(static_cast<uint8_t>(m_initializer.at(p)))) p--;
  m_initializer=m_initializer.left(p+1);
  m_initLines=m_initializer.contains('\n');
  //printf("%s::setInitializer(%s)\n",qPrint(name()),qPrint(m_initializer));
}
References initializer(), m_initializer, and m_initLines.
setMaxInitLines()
void MemberDefImpl::setMaxInitLines (int lines) override virtual
Implements MemberDefMutable.
Definition at line 5843 of file memberdef.cpp.
{
  if (lines!=-1)
  {
    m_userInitLines=lines;
  }
}
References m_userInitLines.
setMemberClass()
void MemberDefImpl::setMemberClass (ClassDef * cd) override virtual
Implements MemberDefMutable.
Definition at line 4392 of file memberdef.cpp.
{
  m_classDef=cd;
  m_isLinkableCached = 0;
  m_isConstructorCached = 0;
  setOuterScope(cd);
}
References m_classDef, m_isConstructorCached, m_isLinkableCached, and DefinitionMixin< MemberDefMutable >::setOuterScope().
setMemberDeclaration()
void MemberDefImpl::setMemberDeclaration (MemberDef * md) override virtual
Implements MemberDefMutable.
Definition at line 5999 of file memberdef.cpp.
{
  m_memDec=md;
}
References m_memDec.
setMemberDefinition()
void MemberDefImpl::setMemberDefinition (MemberDef * md) override virtual
Implements MemberDefMutable.
Definition at line 5994 of file memberdef.cpp.
{
  m_memDef=md;
}
References m_memDef.
setMemberGroup()
void MemberDefImpl::setMemberGroup (MemberGroup * grp) override virtual
Implements MemberDef.
Definition at line 4313 of file memberdef.cpp.
{
  m_memberGroup = grp;
}
References m_memberGroup.
setMemberGroupId()
void MemberDefImpl::setMemberGroupId (int id) override virtual
Implements MemberDefMutable.
Definition at line 5943 of file memberdef.cpp.
{
  m_grpId=id;
}
References Definition::id(), and m_grpId.
setMemberSpecifiers()
void MemberDefImpl::setMemberSpecifiers (TypeSpecifier s) override virtual
Implements MemberDefMutable.
Definition at line 5806 of file memberdef.cpp.
{
  m_memSpec=s;
}
References m_memSpec.
setMemberType()
void MemberDefImpl::setMemberType (MemberType t) override virtual
Implements MemberDefMutable.
Definition at line 5776 of file memberdef.cpp.
{
  m_mtype=t;
  m_isLinkableCached = 0;
}
References m_isLinkableCached, and m_mtype.
setModuleDef()
void MemberDefImpl::setModuleDef (ModuleDef * mod) override virtual
Implements MemberDefMutable.
Definition at line 5795 of file memberdef.cpp.
{
  m_moduleDef=mod;
}
References m_moduleDef.
setNamespace()
void MemberDefImpl::setNamespace (NamespaceDef * nd) override virtual
Implements MemberDefMutable.
Definition at line 4400 of file memberdef.cpp.
{
  m_nspace=nd;
  setOuterScope(nd);
}
References m_nspace, and DefinitionMixin< MemberDefMutable >::setOuterScope().
setProtection()
void MemberDefImpl::setProtection (Protection p) override virtual
Implements MemberDefMutable.
Definition at line 5800 of file memberdef.cpp.
{
  m_prot=p;
  m_isLinkableCached = 0;
}
References m_isLinkableCached, and m_prot.
setPrototype()
void MemberDefImpl::setPrototype (bool p, const QCString & df, int line, int column) override virtual
Implements MemberDefMutable.
Definition at line 5910 of file memberdef.cpp.
{
  m_proto=p;
  if (p)
  {
    setDeclFile(df,line,column);
  }
  else
  {
    setDefFile(df,line,column);
  }
}
References m_proto, setDeclFile(), and DefinitionMixin< MemberDefMutable >::setDefFile().
setReadAccessor()
void MemberDefImpl::setReadAccessor (const QCString & r) override virtual
Implements MemberDefMutable.
Definition at line 5851 of file memberdef.cpp.
{
  m_read=r;
}
References m_read.
setReimplements()
void MemberDefImpl::setReimplements (MemberDef * md) override virtual
Implements MemberDefMutable.
Definition at line 1569 of file memberdef.cpp.
{
  m_redefines = md;
}
References m_redefines.
setRelatedAlso()
void MemberDefImpl::setRelatedAlso (ClassDef * cd) override virtual
Implements MemberDefMutable.
Definition at line 5888 of file memberdef.cpp.
{
  m_relatedAlso=cd;
}
References m_relatedAlso.
setRequiresClause()
void MemberDefImpl::setRequiresClause (const QCString & req) override virtual
Implements MemberDefMutable.
Definition at line 6034 of file memberdef.cpp.
{
  m_requiresClause = req;
}
References m_requiresClause.
setSectionList()
void MemberDefImpl::setSectionList (const Definition * container, const MemberList * sl) override virtual
Implements MemberDefMutable.
Definition at line 4548 of file memberdef.cpp.
{
  //printf("MemberDefImpl::setSectionList(%s,%p) name=%s\n",qPrint(d->name()),sl,qPrint(name()));
  m_sectionMap.emplace(container,sl);
}
References m_sectionMap.
setTagInfo()
void MemberDefImpl::setTagInfo (const TagInfo * i) override virtual
Implements MemberDefMutable.
Definition at line 4981 of file memberdef.cpp.
{
  if (ti)
  {
    //printf("%s: Setting tag name=%s anchor=%s\n",qPrint(name()),qPrint(ti->tagName),qPrint(ti->anchor));
    m_anc=ti->anchor;
    setReference(ti->tagName);
    m_explicitOutputFileBase = stripExtension(ti->fileName);
  }
}
References TagInfo::anchor, TagInfo::fileName, m_anc, m_explicitOutputFileBase, DefinitionMixin< MemberDefMutable >::setReference(), stripExtension(), and TagInfo::tagName.
setTemplateMaster()
void MemberDefImpl::setTemplateMaster (MemberDef * mt) override virtual
Implements MemberDefMutable.
Definition at line 5968 of file memberdef.cpp.
{
  m_templateMaster=mt;
  m_isLinkableCached = 0;
}
References m_isLinkableCached, and m_templateMaster.
setTemplateSpecialization()
void MemberDefImpl::setTemplateSpecialization (bool b) override virtual
Implements MemberDefMutable.
Definition at line 5861 of file memberdef.cpp.
{
  m_tspec=b;
}
References m_tspec.
setType()
void MemberDefImpl::setType (const QCString & t) override virtual
Implements MemberDefMutable.
Definition at line 4882 of file memberdef.cpp.
{
  m_type = t;
}
References m_type.
setTypeConstraints()
void MemberDefImpl::setTypeConstraints (const ArgumentList & al) override virtual
Implements MemberDefMutable.
Definition at line 4877 of file memberdef.cpp.
{
  m_typeConstraints = al;
}
References m_typeConstraints.
setVhdlSpecifiers()
void MemberDefImpl::setVhdlSpecifiers (VhdlSpecifier s) override virtual
Implements MemberDefMutable.
Definition at line 5811 of file memberdef.cpp.
{
  m_vhdlSpec=s;
}
References m_vhdlSpec.
setWriteAccessor()
void MemberDefImpl::setWriteAccessor (const QCString & w) override virtual
Implements MemberDefMutable.
Definition at line 5856 of file memberdef.cpp.
{
  m_write=w;
}
References m_write.
sourceRefName()
QCString MemberDefImpl::sourceRefName () const override virtual
Implements MemberDef.
Definition at line 1635 of file memberdef.cpp.
{
  QCString n  = name();
  QCString s = getScopeString();
  if (!s.isEmpty())
  {
    n.prepend(s+"::");
  }
  else if (isStatic() && getFileDef())
  {
    n.prepend(getFileDef()->name()+":");
  }
  if (isCallable())
  {
    n.append(argsString());
  }
  return n;
}
References QCString::append(), argsString(), getFileDef(), getScopeString(), isCallable(), QCString::isEmpty(), isStatic(), DefinitionMixin< MemberDefMutable >::name(), and QCString::prepend().
templateArguments()
const ArgumentList & MemberDefImpl::templateArguments () const override virtual
Implements MemberDef.
Definition at line 5626 of file memberdef.cpp.
{
  return m_tArgList;
}
References m_tArgList.
templateMaster()
const MemberDef * MemberDefImpl::templateMaster () const override virtual
Implements MemberDef.
Definition at line 5707 of file memberdef.cpp.
{
  return m_templateMaster;
}
References m_templateMaster.
Referenced by _computeLinkableInProject(), getOutputFileBase(), and getReference().
typeConstraints()
const ArgumentList & MemberDefImpl::typeConstraints () const override virtual
Implements MemberDef.
Definition at line 6313 of file memberdef.cpp.
{
  return m_typeConstraints;
}
References m_typeConstraints.
typeString()
QCString MemberDefImpl::typeString () const override virtual
Implements MemberDef.
Definition at line 5024 of file memberdef.cpp.
{
  return m_type;
}
References m_type.
Referenced by _computeIsDestructor(), warnIfUndocumentedParams(), and writeTagFile().
virtualness()
Specifier MemberDefImpl::virtualness (int count = 0) const override virtual
Implements MemberDef.
Definition at line 4554 of file memberdef.cpp.
{
  if (count>25)
  {
     warn(getDefFileName(),getDefLine(),
       "Internal inconsistency: recursion detected in overload relation for member %s!"
       ,qPrint(name())
      );
     return Specifier::Normal;
  }
  Specifier v = m_virt;
  const MemberDef *rmd = reimplements();
  while (rmd && v==Specifier::Normal)
  {
    v = rmd->virtualness(count+1)==Specifier::Normal ? Specifier::Normal : Specifier::Virtual;
    rmd = rmd->reimplements();
  }
  return v;
}
References DefinitionMixin< MemberDefMutable >::getDefFileName(), DefinitionMixin< MemberDefMutable >::getDefLine(), m_virt, DefinitionMixin< MemberDefMutable >::name(), Normal, qPrint(), MemberDef::reimplements(), reimplements(), Virtual, MemberDef::virtualness(), and warn.
Referenced by getLabels().
visibleInIndex()
bool MemberDefImpl::visibleInIndex () const override virtual
Implements MemberDef.
Definition at line 4144 of file memberdef.cpp.
{
  bool hideUndocMembers = Config_getBool(HIDE_UNDOC_MEMBERS);
  bool extractStatic = Config_getBool(EXTRACT_STATIC);
  return (!isAnonymous() &&
      (!hideUndocMembers || hasDocumentation()) &&
      (!isStatic() || extractStatic) &&
      isLinkable()
     );
}
References Config_getBool, hasDocumentation(), DefinitionMixin< MemberDefMutable >::isAnonymous(), isLinkable(), and isStatic().
warnIfUndocumented()
void MemberDefImpl::warnIfUndocumented () const override virtual
Implements MemberDef.
Definition at line 4072 of file memberdef.cpp.
{
  /*
   *  Removed bug_303020:
   *  if (m_memberGroup) return;
   */
  const ClassDef     *cd = getClassDef();
  const NamespaceDef *nd = getNamespaceDef();
  const FileDef      *fd = getFileDef();
  const GroupDef     *gd = getGroupDef();
  const Definition *d=nullptr;
  QCString t;
  if (cd)
  {
    t=cd->compoundTypeString();
    d=cd;
  }
  else if (nd)
  {
    t=nd->compoundTypeString();
    d=nd;
  }
  else if (gd)
  {
    t="group";
    d=gd;
  }
  else
  {
    t="file";
    d=fd;
  }
  bool extractAll = Config_getBool(EXTRACT_ALL);
  //printf("%s:warnIfUndoc: hasUserDocs=%d isFriendClass=%d protection=%d isRef=%d isDel=%d\n",
  //    qPrint(name()),
  //    hasUserDocumentation(),isFriendClass(),protectionLevelVisible(m_prot),isReference(),isDeleted());
  if ((!hasUserDocumentation() && !extractAll) &&
      !isFriendClass() &&
      name().find('@')==-1 && d && d->name().find('@')==-1 &&
      !_isAnonymousBitField() &&
      protectionLevelVisible(m_prot) &&
      !isReference() && !isDeleted()
     )
  {
    SrcLangExt lang = getLanguage();
    QCString sep = getLanguageSpecificSeparator(lang,TRUE);
    warn_undoc(getDefFileName(),getDefLine(),"Member %s%s (%s) of %s %s is not documented.",
         qPrint(name()),qPrint(argsString()),qPrint(memberTypeName()),qPrint(t),
         qPrint(substitute(d->name(),"::",sep)));
  }
  else if (!hasDetailedDescription())
  {
    warnIfUndocumentedParams();
  }
  // if it is an enum, we check that its members are documented
  if (!extractAll && isEnumerate() && Config_getBool(WARN_IF_UNDOC_ENUM_VAL))
  {
    for (const auto &fmd : enumFieldList())
    {
      if (!fmd->isLinkableInProject())
      {
        SrcLangExt lang = getLanguage();
        QCString sep = getLanguageSpecificSeparator(lang,TRUE);
        warn(fmd->getDefFileName(),fmd->getDefLine(), "Documentation for enum member '%s%s%s' is missing.",
             qPrint(qualifiedName()),qPrint(sep),qPrint(fmd->name()));
      }
    }
  }
}
References _isAnonymousBitField(), argsString(), ClassDef::compoundTypeString(), NamespaceDef::compoundTypeString(), Config_getBool, enumFieldList(), QCString::find(), getClassDef(), DefinitionMixin< MemberDefMutable >::getDefFileName(), DefinitionMixin< MemberDefMutable >::getDefLine(), getFileDef(), getGroupDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), getNamespaceDef(), hasDetailedDescription(), hasUserDocumentation(), isDeleted(), isEnumerate(), isFriendClass(), isReference(), m_prot, memberTypeName(), Definition::name(), DefinitionMixin< MemberDefMutable >::name(), protectionLevelVisible(), qPrint(), qualifiedName(), substitute(), TRUE, warn, warn_undoc, and warnIfUndocumentedParams().
Referenced by writeDeclaration().
warnIfUndocumentedParams()
void MemberDefImpl::warnIfUndocumentedParams () const override virtual
Implements MemberDef.
Definition at line 4233 of file memberdef.cpp.
{
  QCString returnType = typeString();
  bool isFortran = getLanguage()==SrcLangExt::Fortran;
  bool isFortranSubroutine = isFortran && returnType.find("subroutine")!=-1;
  bool isVoidReturn =   returnType=="void" || returnType.endsWith(" void");
  if (!isVoidReturn && (returnType=="auto" || returnType.endsWith(" auto")))
  {
    const ArgumentList &defArgList=isDocsForDefinition() ?  argumentList() : declArgumentList();
    if (!defArgList.trailingReturnType().isEmpty())
    {
      QCString strippedTrailingReturn = stripTrailingReturn(defArgList.trailingReturnType());
      isVoidReturn = (strippedTrailingReturn=="void") || (strippedTrailingReturn.endsWith(" void"));
    }
  }
  if (!Config_getBool(EXTRACT_ALL) &&
      Config_getBool(WARN_IF_UNDOCUMENTED) &&
      Config_getBool(WARN_NO_PARAMDOC) &&
      isFunction() &&
      !isDeleted() &&
      !isReference() &&
      !Doxygen::suppressDocWarnings)
  {
    if (!m_hasDocumentedParams)
    {
      warn_doc_error(docFile(),docLine(),
          "parameters of member %s are not documented",
          qPrint(qualifiedName()));
    }
    if (!m_hasDocumentedReturnType &&
        hasDocumentation() && !returnType.isEmpty() &&
        !( // not one of the cases where nothing is returned
          isVoidReturn        || // void return type
          isFortranSubroutine || // fortran subroutine
          isConstructor()     || // a constructor
          isDestructor()         // or destructor
         )
       )
    {
      warn_doc_error(docFile(),docLine(),
          "return type of member %s is not documented",
          qPrint(qualifiedName()));
    }
  }
  if (Config_getBool(WARN_IF_DOC_ERROR) &&
            m_hasDocumentedReturnType &&
            (isVoidReturn        || // void return type
             isFortranSubroutine || // fortran subroutine
             isConstructor()     || // a constructor
             isDestructor()))       // or destructor
  {
    warn_doc_error(docFile(),docLine(),"found documented return type for %s that does not return anything",
                   qPrint(qualifiedName()));
  }
}
References argumentList(), Config_getBool, declArgumentList(), DefinitionMixin< MemberDefMutable >::docFile(), DefinitionMixin< MemberDefMutable >::docLine(), QCString::endsWith(), QCString::find(), Fortran, DefinitionMixin< MemberDefMutable >::getLanguage(), hasDocumentation(), isConstructor(), isDeleted(), isDestructor(), isDocsForDefinition(), QCString::isEmpty(), isFunction(), isReference(), m_hasDocumentedParams, m_hasDocumentedReturnType, qPrint(), qualifiedName(), stripTrailingReturn(), Doxygen::suppressDocWarnings, ArgumentList::trailingReturnType(), typeString(), and warn_doc_error.
Referenced by warnIfUndocumented(), and writeDocumentation().
writeDeclaration()
void MemberDefImpl::writeDeclaration (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, const ModuleDef * mod, bool inGroup, int indentLevel, const ClassDef * inheritFrom = nullptr, const QCString & inheritId = QCString()) const override virtual
init.isEmpty() && initLines==0 && // one line initializer
Implements MemberDef.
Definition at line 2222 of file memberdef.cpp.
{
  //printf("> %s MemberDefImpl::writeDeclaration() inGroup=%d inheritId=%s\n",qPrint(qualifiedName()),inGroup,qPrint(inheritId));
  // hide enum value, since they appear already as part of the enum, unless they
  // are explicitly grouped.
  if (!inGroup && m_mtype==MemberType::EnumValue) return;
  const Definition *d=nullptr;
  ASSERT (cd!=nullptr || nd!=nullptr || fd!=nullptr || gd!=nullptr || mod!=nullptr); // member should belong to something
  if (cd) d=cd;
  else if (nd) d=nd;
  else if (mod) d=mod;
  else if (fd) d=fd;
  else d=gd;
  if (d==gd) // see bug 753608
  {
    if (getClassDef())          d = getClassDef();
    else if (getNamespaceDef()) d = getNamespaceDef();
    else if (getFileDef())      d = getFileDef();
  }
  else if (d==fd) // see issue #9850, namespace member can be shown in file scope as well
  {
    if (getNamespaceDef()) d = getNamespaceDef();
  }
  if (d==nullptr)
  {
    err("No context could be derived for member '%s'\n",qPrint(name()));
    return; // should not happen
  }
  QCString cname  = d->name();
  QCString cdname = d->displayName();
  QCString cfname = getOutputFileBase();
  // search for the last anonymous scope in the member type
  ClassDef *annoClassDef=getClassDefOfAnonymousType();
  ol.startMemberDeclaration();
  // start a new member declaration
  bool isAnonType = annoClassDef || m_annMemb || m_annEnumType;
  OutputGenerator::MemberItemType anonType = isAnonType ? OutputGenerator::MemberItemType::AnonymousStart :
                              !m_tArgList.empty() ? OutputGenerator::MemberItemType::Templated      :
                                                          OutputGenerator::MemberItemType::Normal;
  ol.startMemberItem(anchor(), anonType, inheritId);
  // If there is no detailed description we need to write the anchor here.
  bool detailsVisible = hasDetailedDescription();
  bool writeAnchor = (inGroup || getGroupDef()==nullptr) &&     // only write anchors for member that have no details and are
                     !detailsVisible && !m_annMemb && // rendered inside the group page or are not grouped at all
                     inheritId.isEmpty();
  if (writeAnchor)
  {
    QCString doxyArgs=argsString();
    QCString doxyName=name();
    if (!cname.isEmpty())
    {
      doxyName.prepend(cdname+getLanguageSpecificSeparator(getLanguage()));
    }
    ol.startDoxyAnchor(cfname,cname,anchor(),doxyName,doxyArgs);
    ol.addLabel(cfname,anchor());
  }
  if (!detailsVisible)
  {
    ol.pushGeneratorState();
    ol.disable(OutputType::Man);
    ol.disable(OutputType::Latex);
    ol.disable(OutputType::Docbook);
    ol.docify("\n");
    ol.popGeneratorState();
  }
  if (annoClassDef || m_annMemb)
  {
    for (int j=0;j<indentLevel;j++)
    {
      ol.writeNonBreakableSpace(3);
    }
  }
  // *** write template lists
  if (m_tArgList.hasParameters() && getLanguage()==SrcLangExt::Cpp)
  {
    if (!isAnonType) ol.startMemberTemplateParams();
    _writeTemplatePrefix(ol,d,m_tArgList);
    if (!isAnonType) ol.endMemberTemplateParams(anchor(),inheritId);
  }
  // *** write type
  QCString ltype(m_type);
  if (isTypedef() && getLanguage() != SrcLangExt::Slice)
  {
    ltype.prepend("typedef ");
  }
  if (isTypeAlias())
  {
    ltype="using";
  }
  // strip 'friend' keyword from ltype
  ltype.stripPrefix("friend ");
  static const reg::Ex r(R"(@\d+)");
  reg::Match match;
  std::string stype = ltype.str();
  bool endAnonScopeNeeded=FALSE;
  if (reg::search(stype,match,r)) // member has an anonymous type
  {
    int i = static_cast<int>(match.position());
    int l = static_cast<int>(match.length());
    //printf("annoClassDef=%p annMemb=%p scopeName='%s' anonymous='%s'\n",
    //    annoClassDef,annMemb,qPrint(cname),qPrint(ltype.mid(i,l)));
    if (annoClassDef) // type is an anonymous compound
    {
      int ir=i+l;
      //printf("<<<<<<<<<<<<<<\n");
      ol.startAnonTypeScope(indentLevel);
      annoClassDef->writeDeclaration(ol,m_annMemb,inGroup,indentLevel+1,inheritedFrom,inheritId);
      //printf(">>>>>>>>>>>>>> startMemberItem(2)\n");
      anonType = OutputGenerator::MemberItemType::AnonymousEnd;
      ol.startMemberItem(anchor(),anonType,inheritId);
      for (int j=0;j< indentLevel;j++)
      {
        ol.writeNonBreakableSpace(3);
      }
      QCString varName=ltype.right(ltype.length()-ir).stripWhiteSpace();
      //printf(">>>>>> ltype='%s' varName='%s'\n",qPrint(ltype),qPrint(varName));
      ol.docify("}");
      if (varName.isEmpty() && isAnonymous())
      {
        ol.docify(";");
      }
      else if (!varName.isEmpty() && (varName.at(0)=='*' || varName.at(0)=='&'))
      {
        ol.docify(" ");
        ol.docify(varName);
      }
      endAnonScopeNeeded=TRUE;
    }
    else
    {
      if (getAnonymousEnumType()) // type is an anonymous enum
      {
        linkifyText(TextGeneratorOLImpl(ol), // out
                    d,                       // scope
                    getBodyDef(),            // fileScope
                    this,                    // self
                    ltype.left(i),           // text
                    FALSE                    // autoBreak
                   );
        getAnonymousEnumType()->writeEnumDeclaration(ol,cd,nd,fd,gd,mod);
        //ol+=*getAnonymousEnumType()->enumDecl();
        linkifyText(TextGeneratorOLImpl(ol),d,getFileDef(),this,ltype.right(ltype.length()-i-l),TRUE);
      }
      else
      {
        ltype = ltype.left(i) + " { ... } " + removeAnonymousScopes(ltype.right(ltype.length()-i-l));
        linkifyText(TextGeneratorOLImpl(ol), // out
                    d,                       // scope
                    getBodyDef(),            // fileScope
                    this,                    // self
                    ltype,                   // text
                    FALSE                    // autoBreak
                   );
      }
    }
  }
  else if (ltype=="@") // rename type from enum values
  {
    ltype="";
  }
  else
  {
    if (isObjCMethod())
    {
      ltype.prepend("(");
      ltype.append(")");
    }
    linkifyText(TextGeneratorOLImpl(ol), // out
                d,                       // scope
                getBodyDef(),            // fileScope
                this,                    // self
                ltype,                   // text
                FALSE                    // autoBreak
               );
  }
  bool htmlOn = ol.isEnabled(OutputType::Html);
  if (htmlOn && !ltype.isEmpty())
  {
    ol.disable(OutputType::Html);
  }
  if (!ltype.isEmpty()) ol.docify(" ");
  if (htmlOn)
  {
    ol.enable(OutputType::Html);
  }
  if (m_annMemb)
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputType::Html);
    ol.writeNonBreakableSpace(3);
    ol.popGeneratorState();
  }
  else
  {
    ol.insertMemberAlign(m_tArgList.hasParameters());
  }
  // *** write name
  if (!isAnonymous() && !_isAnonymousBitField()) // hide anonymous stuff
  {
    bool extractPrivateVirtual = Config_getBool(EXTRACT_PRIV_VIRTUAL);
    bool extractStatic  = Config_getBool(EXTRACT_STATIC);
    MemberDefMutable *annMemb = toMemberDefMutable(m_annMemb);
    bool visibleIfPrivate = (protectionLevelVisible(protection()) ||
                             m_mtype==MemberType::Friend ||
                             (m_prot==Protection::Private &&
                                (m_virt!=Specifier::Normal || isOverride() || isFinal()) &&
                                extractPrivateVirtual && hasDocumentation()
                             ));
    //printf("Member name=`%s gd=%p md->groupDef=%p inGroup=%d isLinkable()=%d hasDocumentation=%d\n",qPrint(name()),gd,getGroupDef(),inGroup,isLinkable(),hasDocumentation());
    if (!name().isEmpty() && // name valid
        (hasDetailedDescription() || isReference()) && // has docs
        visibleIfPrivate &&
        !(isStatic() && getClassDef()==nullptr && !extractStatic) // hidden due to static-ness
       )
    {
      if (annMemb)
      {
        //printf("anchor=%s ann_anchor=%s\n",anchor(),annMemb->anchor());
        annMemb->writeLink(ol,
            annMemb->getClassDef(),
            annMemb->getNamespaceDef(),
            annMemb->getFileDef(),
            annMemb->getGroupDef(),
            annMemb->getModuleDef());
      }
      else
      {
        //printf("writeLink %s->%d\n",qPrint(name),hasDocumentation());
        const ClassDef *rcd = cd;
        if (isReference() && getClassDef()) rcd = getClassDef();
        writeLink(ol,rcd,nd,fd,gd,mod);
      }
    }
    else if (isDocumentedFriendClass())
      // if the member is an undocumented friend declaration for some class,
      // then maybe we can link to the class
    {
      writeLink(ol,getClass(name()),nullptr,nullptr,nullptr,nullptr);
    }
    else
      // there is a brief member description and brief member
      // descriptions are enabled or there is no detailed description.
    {
      const ClassDef *rcd = cd;
      if (isReference() && getClassDef()) rcd = getClassDef();
      writeLink(ol,rcd,nd,fd,gd,mod,TRUE);
    }
  }
  // *** write arguments
  if (!argsString().isEmpty() && !isObjCMethod())
  {
    if (!isDefine() && !isTypedef()) ol.writeString(" ");
    linkifyText(TextGeneratorOLImpl(ol), // out
                d,                       // scope
                getBodyDef(),            // fileScope
                this,                    // self
                isDefine() ?
                   substitute(argsString(),",",", ") :
                isTypedef() ?
                   substitute(argsString(),")(",") (") :
                   combineArgsAndException(argsString(),excpString()), // text
                m_annMemb!=nullptr,      // autoBreak
                TRUE,                    // external
                FALSE,                   // keepSpaces
                indentLevel
               );
  }
  // *** write bitfields
  if (!m_bitfields.isEmpty()) // add bitfields
  {
    linkifyText(TextGeneratorOLImpl(ol),d,getBodyDef(),this,m_bitfields);
  }
  else if (hasOneLineInitializer()
      //!init.isEmpty() && initLines==0 && // one line initializer
      //((maxInitLines>0 && userInitLines==-1) || userInitLines>0) // enabled by default or explicitly
          ) // add initializer
  {
    if (isTypeAlias()) // using statement
    {
      ol.writeString(" = ");
      linkifyText(TextGeneratorOLImpl(ol),d,getBodyDef(),this,m_initializer.simplifyWhiteSpace());
    }
    else if (!isDefine())
    {
      //ol.writeString(" = ");
      ol.writeString(" ");
      linkifyText(TextGeneratorOLImpl(ol),d,getBodyDef(),this,m_initializer.simplifyWhiteSpace());
    }
    else
    {
      ol.writeNonBreakableSpace(3);
      linkifyText(TextGeneratorOLImpl(ol),d,getBodyDef(),this,m_initializer);
    }
  }
  if ((isObjCMethod() || isObjCProperty()) && isImplementation())
  {
    ol.startTypewriter();
    ol.docify(" [implementation]");
    ol.endTypewriter();
  }
  bool extractPrivate = Config_getBool(EXTRACT_PRIVATE);
  if (isProperty() && (isSettable() || isGettable() ||
      isPrivateSettable() || isPrivateGettable() ||
      isProtectedSettable() || isProtectedGettable()))
  {
      ol.writeLatexSpacing();
      ol.startTypewriter();
      ol.docify(" [");
      StringVector sl;
      if (isGettable())             sl.emplace_back("get");
      if (isProtectedGettable())    sl.emplace_back("protected get");
      if (isSettable())             sl.emplace_back("set");
      if (isProtectedSettable())    sl.emplace_back("protected set");
      if (extractPrivate)
      {
        if (isPrivateGettable())    sl.emplace_back("private get");
        if (isPrivateSettable())    sl.emplace_back("private set");
      }
      bool first=true;
      for (const auto &s : sl)
      {
         if (!first)
         {
           ol.docify(", ");
         }
         first=false;
         ol.docify(s.c_str());
      }
      ol.docify("]");
      ol.endTypewriter();
  }
  if (isEvent() && (isAddable() || isRemovable() || isRaisable()))
  {
      ol.writeLatexSpacing();
      ol.startTypewriter();
      ol.docify(" [");
      StringVector sl;
      if (isAddable())   sl.emplace_back("add");
      if (isRemovable()) sl.emplace_back("remove");
      if (isRaisable())  sl.emplace_back("raise");
      bool first=true;
      for (const auto &s : sl)
      {
        if (!first)
        {
          ol.docify(", ");
        }
        first=false;
        ol.docify(s.c_str());
      }
      ol.docify("]");
      ol.endTypewriter();
  }
  if (writeAnchor)
  {
    ol.endDoxyAnchor(cfname,anchor());
  }
  //printf("endMember %s annoClassDef=%p annEnumType=%p\n",
  //    qPrint(name()),annoClassDef,annEnumType);
  ol.endMemberItem(anonType);
  if (endAnonScopeNeeded)
  {
    ol.endAnonTypeScope(indentLevel);
  }
  // write brief description
  if (!briefDescription().isEmpty() &&
      Config_getBool(BRIEF_MEMBER_DESC)
     )
  {
    auto parser { createDocParser() };
    auto ast    { validatingParseDoc(*parser.get(),
                                     briefFile(),briefLine(),
                                     getOuterScope()?getOuterScope():d,
                                     this,briefDescription(),TRUE,FALSE,
                                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startMemberDescription(anchor(),inheritId);
      ol.writeDoc(ast.get(),getOuterScope()?getOuterScope():d,this);
      if (detailsVisible) // add More.. link only when both brief and details are visible
      {
        if (!isAnonymous()) // hide anonymous stuff
        {
          ol.pushGeneratorState();
          ol.disableAllBut(OutputType::Html);
          ol.docify(" ");
          MemberDefMutable *annMemb = toMemberDefMutable(m_annMemb);
          if (annMemb)
          {
            ol.startTextLink(annMemb->getOutputFileBase(),annMemb->anchor());
            ol.parseText(theTranslator->trMore());
            ol.endTextLink();
          }
          ol.popGeneratorState();
        }
      }
      // for RTF we need to add an extra empty paragraph
      ol.pushGeneratorState();
      ol.disableAllBut(OutputType::RTF);
      ol.startParagraph();
      ol.endParagraph();
      ol.popGeneratorState();
      ol.endMemberDescription();
    }
  }
  ol.endMemberDeclaration(anchor(),inheritId);
  warnIfUndocumented();
  //printf("< %s MemberDefImpl::writeDeclaration() inGroup=%d\n",qPrint(qualifiedName()),inGroup);
}
References _isAnonymousBitField(), _writeTemplatePrefix(), OutputList::addLabel(), Definition::anchor(), anchor(), OutputGenerator::AnonymousEnd, OutputGenerator::AnonymousStart, QCString::append(), argsString(), ASSERT, QCString::at(), briefDescription(), Definition::briefFile(), DefinitionMixin< MemberDefMutable >::briefLine(), combineArgsAndException(), Config_getBool, Cpp, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), Definition::displayName(), Docbook, OutputList::docify(), OutputList::enable(), OutputList::endAnonTypeScope(), OutputList::endDoxyAnchor(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberItem(), OutputList::endMemberTemplateParams(), OutputList::endParagraph(), OutputList::endTextLink(), OutputList::endTypewriter(), EnumValue, err, excpString(), FALSE, Friend, getAnonymousEnumType(), DefinitionMixin< MemberDefMutable >::getBodyDef(), getClass(), MemberDef::getClassDef(), getClassDef(), getClassDefOfAnonymousType(), MemberDef::getFileDef(), getFileDef(), MemberDef::getGroupDef(), getGroupDef(), Definition::getLanguage(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), MemberDef::getModuleDef(), MemberDef::getNamespaceDef(), getNamespaceDef(), Definition::getOuterScope(), DefinitionMixin< MemberDefMutable >::getOuterScope(), Definition::getOutputFileBase(), getOutputFileBase(), hasDetailedDescription(), hasDocumentation(), hasOneLineInitializer(), Html, OutputList::insertMemberAlign(), isAddable(), Definition::isAnonymous(), DefinitionMixin< MemberDefMutable >::isAnonymous(), isDefine(), isDocumentedFriendClass(), QCString::isEmpty(), OutputList::isEnabled(), isEvent(), isFinal(), isGettable(), isImplementation(), isObjCMethod(), isObjCProperty(), isOverride(), isPrivateGettable(), isPrivateSettable(), isProperty(), isProtectedGettable(), isProtectedSettable(), isRaisable(), isReference(), isRemovable(), isSettable(), isStatic(), isTypeAlias(), isTypedef(), Latex, QCString::left(), QCString::length(), linkifyText(), m_annEnumType, m_annMemb, m_bitfields, m_initializer, m_mtype, m_prot, m_tArgList, m_type, m_virt, Man, Definition::name(), DefinitionMixin< MemberDefMutable >::name(), OutputGenerator::Normal, Normal, OutputList::parseText(), OutputList::popGeneratorState(), QCString::prepend(), Private, protection(), protectionLevelVisible(), OutputList::pushGeneratorState(), qPrint(), removeAnonymousScopes(), QCString::right(), RTF, reg::search(), Slice, OutputList::startAnonTypeScope(), OutputList::startDoxyAnchor(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberItem(), OutputList::startMemberTemplateParams(), OutputList::startParagraph(), OutputList::startTextLink(), OutputList::startTypewriter(), QCString::str(), QCString::stripPrefix(), QCString::stripWhiteSpace(), substitute(), OutputGenerator::Templated, theTranslator, toMemberDefMutable(), Translator::trMore(), TRUE, validatingParseDoc(), warnIfUndocumented(), ClassDef::writeDeclaration(), OutputList::writeDoc(), MemberDef::writeEnumDeclaration(), OutputList::writeLatexSpacing(), MemberDef::writeLink(), writeLink(), OutputList::writeNonBreakableSpace(), and OutputList::writeString().
writeDocumentation()
void MemberDefImpl::writeDocumentation (const MemberList * ml, int memCount, int memTotal, OutputList & ol, const QCString & scName, const Definition * container, bool inGroup, bool showEnumValues = FALSE, bool showInline = FALSE) const override virtual
Writes the "detailed documentation" section of this member to all active output formats.
Implements MemberDefMutable.
Definition at line 3433 of file memberdef.cpp.
{
  // if this member is in a group find the real scope name.
  bool hasParameterList = FALSE;
  //printf("MemberDefImpl::writeDocumentation(): name='%s' hasDocs='%d' containerType=%d inGroup=%d sectionLinkable=%d\n",
  //    qPrint(name()),hasDocs,container->definitionType(),inGroup,hasDetailedDescription());
  //if ( !hasDocs ) return;
  //if (isEnumValue() && !showEnumValues) return;
  SrcLangExt lang = getLanguage();
  //printf("member=%s lang=%d\n",qPrint(name()),lang);
  bool optVhdl = lang==SrcLangExt::VHDL;
  QCString sep = getLanguageSpecificSeparator(lang,TRUE);
  QCString scopeName = scName;
  QCString memAnchor = anchor();
  QCString ciname = container->displayName();
  const Definition *scopedContainer = container; // see bug 753608
  if (container->definitionType()==TypeGroup)
  {
    if (getClassDef())          { scopeName=getClassDef()->displayName();     scopedContainer=getClassDef(); }
    else if (getNamespaceDef()) { scopeName=getNamespaceDef()->displayName(); scopedContainer=getNamespaceDef(); }
    else if (getFileDef())      { scopeName=getFileDef()->displayName();      scopedContainer=getFileDef(); }
    ciname = (toGroupDef(container))->groupTitle();
  }
  else if (container->definitionType()==TypeFile && getNamespaceDef() && getNamespaceDef()->isLinkable())
  { // member is in a namespace, but is written as part of the file documentation
    // as well, so we need to make sure its anchor is unique (it is not really used).
    memAnchor.prepend("file_");
  }
  QCString cname   = container->name();
  QCString cfname  = getOutputFileBase();
  // get member name
  QCString doxyName=name();
  // prepend scope if there is any. TODO: make this optional for C only docs
  if (!scopeName.isEmpty())
  {
    doxyName.prepend(scopeName+sep);
  }
  QCString doxyArgs=argsString();
  QCString ldef = definition();
  QCString title = name();
  //printf("member '%s' def='%s'\n",qPrint(name()),qPrint(ldef));
  if (isEnumerate())
  {
    if (title.at(0)=='@')
    {
      ldef = title = "anonymous enum";
      if (!m_enumBaseType.isEmpty())
      {
        ldef+=" : "+m_enumBaseType;
      }
    }
    else
    {
      if (lang==SrcLangExt::Cpp)
      {
        if (isEnumStruct()) ldef.prepend("struct ");
        else if (isStrong()) ldef.prepend("class ");
      }
      ldef.prepend("enum ");
      if (isSliceLocal())
      {
        ldef.prepend("local ");
      }
    }
  }
  else if (isEnumValue())
  {
    if (ldef.at(0)=='@')
    {
      ldef=ldef.mid(2);
    }
  }
  else if (isFunction() && !isObjCMethod())
  {
    title += "()";
  }
  if (lang == SrcLangExt::Slice)
  {
    // Remove the container scope from the member name.
    QCString prefix = scName + sep;
    int pos = ldef.findRev(prefix.data());
    if(pos != -1)
    {
      ldef.remove(pos, prefix.length());
    }
  }
  ldef.stripPrefix("constexpr ");
  ldef.stripPrefix("consteval ");
  ldef.stripPrefix("constinit ");
  //----------------------------------------
  ol.pushGeneratorState();
  bool htmlEndLabelTable=FALSE;
  StringVector sl = getLabels(scopedContainer);
  static const reg::Ex r(R"(@\d+)");
  reg::Match match;
  std::string sdef = ldef.str();
  if ((isVariable() || isTypedef()) && reg::search(sdef,match,r))
  {
    // find enum type and insert it in the definition
    bool found=false;
    for (const auto &vmd : *ml)
    {
      if (vmd->isEnumerate() && match.str()==vmd->name())
      {
        ol.startDoxyAnchor(cfname, cname, memAnchor, doxyName, doxyArgs);
        ol.startMemberDoc(ciname,name(),memAnchor,name(),memCount,memTotal,showInline);
        ol.addLabel(cfname, memAnchor);
        std::string prefix = match.prefix().str();
        std::string suffix = match.suffix().str();
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,prefix.c_str());
        vmd->writeEnumDeclaration(ol,getClassDef(),getNamespaceDef(),getFileDef(),getGroupDef(),getModuleDef());
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,suffix.c_str());
        found=true;
        break;
      }
    }
    if (!found) // anonymous compound
    {
      ClassDef *annoClassDef=getClassDefOfAnonymousType();
      QCString typeName;
      if (annoClassDef) typeName=annoClassDef->compoundTypeString();
      ol.startDoxyAnchor(cfname, cname, memAnchor, doxyName, doxyArgs);
      ol.startMemberDoc(ciname,name(),memAnchor,"["+typeName+"]",memCount,memTotal,showInline);
      ol.addLabel(cfname, memAnchor);
      // search for the last anonymous compound name in the definition
      ol.startMemberDocName(isObjCMethod());
      if (reg::search(sdef,match,reAnonymous))
      {
        std::string prefix = match.prefix().str();
        std::string suffix = match.suffix().str();
        ol.docify(prefix.c_str());
        ol.docify(" { ... } ");
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,removeAnonymousScopes(suffix.c_str()));
      }
      else
      {
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,ldef);
      }
    }
  }
  else // not an enum value or anonymous compound
  {
    ol.startDoxyAnchor(cfname, cname, memAnchor, doxyName, doxyArgs);
    ol.startMemberDoc(ciname,name(),memAnchor,title,memCount,memTotal,showInline);
    ol.addLabel(cfname, memAnchor);
    if (!m_metaData.isEmpty() && getLanguage()==SrcLangExt::Slice)
    {
      ol.startMemberDocPrefixItem();
      ol.docify(m_metaData);
      ol.endMemberDocPrefixItem();
    }
    const ClassDef *cd=getClassDef();
    const NamespaceDef *nd=getNamespaceDef();
    bool first=TRUE;
    if (!m_defTmpArgLists.empty() && lang==SrcLangExt::Cpp)
      // definition has explicit template parameter declarations
    {
      for (const ArgumentList &tal : m_defTmpArgLists)
      {
        if (!tal.empty())
        {
          if (!first) ol.docify(" ");
          ol.startMemberDocPrefixItem();
          _writeTemplatePrefix(ol,scopedContainer,tal);
          ol.endMemberDocPrefixItem();
        }
      }
    }
    else // definition gets it template parameters from its class
      // (since no definition was found)
    {
      if (cd && lang==SrcLangExt::Cpp && !isTemplateSpecialization())
      {
        for (const ArgumentList &tal : cd->getTemplateParameterLists())
        {
          if (!tal.empty())
          {
            if (!first) ol.docify(" ");
            ol.startMemberDocPrefixItem();
            _writeTemplatePrefix(ol,scopedContainer,tal,false);
            ol.endMemberDocPrefixItem();
          }
        }
      }
      if (m_tArgList.hasParameters() && lang==SrcLangExt::Cpp) // function template prefix
      {
        ol.startMemberDocPrefixItem();
        _writeTemplatePrefix(ol,scopedContainer,m_tArgList);
        ol.endMemberDocPrefixItem();
      }
    }
    if (!sl.empty())
    {
      ol.pushGeneratorState();
      ol.disableAll();
      ol.enable(OutputType::Html);
      ol.writeString("<table class=\"mlabels\">\n");
      ol.writeString("  <tr>\n");
      ol.writeString("  <td class=\"mlabels-left\">\n");
      ol.popGeneratorState();
      htmlEndLabelTable=TRUE;
    }
    ol.startMemberDocName(isObjCMethod());
    if (cd && cd->isObjectiveC())
    {
      // strip scope name
      int ep = ldef.find("::");
      if (ep!=-1)
      {
        int sp=ldef.findRev(' ',ep);
        if (sp!=-1)
        {
          ldef=ldef.left(sp+1)+ldef.mid(ep+2);
        } else {
          ldef=ldef.mid(ep+2);
        }
      }
      // strip keywords
      int dp = ldef.find(':');
      if (dp!=-1)
      {
        ldef=ldef.left(dp+1);
      }
      int dl=static_cast<int>(ldef.length());
      //printf("start >%s<\n",qPrint(ldef));
      int i=dl-1;
      while (i>=0 && (isId(ldef.at(i)) || ldef.at(i)==':')) i--;
      while (i>=0 && isspace(static_cast<uint8_t>(ldef.at(i)))) i--;
      if (i>0)
      {
        // insert branches around the type
        ldef="("+ldef.left(i+1)+")"+ldef.mid(i+1);
      }
      //printf("end   >%s< i=%d\n",qPrint(ldef),i);
      if (isStatic()) ldef.prepend("+ "); else ldef.prepend("- ");
    }
    if (optVhdl)
    {
      hasParameterList=VhdlDocGen::writeVHDLTypeDocumentation(this,scopedContainer,ol);
    }
    else if (lang==SrcLangExt::Slice)
    {
      // Eliminate the self-reference.
      int pos = ldef.findRev(' ');
      if (pos<0) pos=0;
      if (pos>0)
      {
        linkifyText(TextGeneratorOLImpl(ol),
                    scopedContainer,
                    getBodyDef(),
                    this,
                    ldef.left(pos)
                   );
      }
      ol.docify(ldef.mid(pos));
      const Definition *scope = cd;
      if (scope==nullptr) scope = nd;
      hasParameterList=writeDefArgumentList(ol,scope,this);
    }
    else
    {
      linkifyText(TextGeneratorOLImpl(ol),
                  scopedContainer,
                  getBodyDef(),
                  this,
                  substitute(ldef,"::",sep)
                 );
      const Definition *scope = cd;
      if (scope==nullptr) scope = nd;
      hasParameterList=writeDefArgumentList(ol,scope,this);
    }
    if (hasOneLineInitializer()) // add initializer
    {
      if (isTypeAlias())
      {
        ol.docify(" = ");
        QCString init = m_initializer.simplifyWhiteSpace();
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,init);
      }
      else if (!isDefine())
      {
        ol.docify(" ");
        QCString init = m_initializer.simplifyWhiteSpace();
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,init);
      }
      else
      {
        ol.writeNonBreakableSpace(3);
        linkifyText(TextGeneratorOLImpl(ol),scopedContainer,getBodyDef(),this,m_initializer);
      }
    }
    if (!excpString().isEmpty()) // add exception list
    {
      writeExceptionList(ol,cd,this);
      hasParameterList=true; // call endParameterList below
    }
  }
  ol.pushGeneratorState();
  ol.disable(OutputType::Html);
  if (!sl.empty())
  {
    ol.startLabels();
    size_t count=0;
    for (const auto &s : sl)
    {
      count++;
      ol.writeLabel(s.c_str(),count==sl.size());
    }
    ol.endLabels();
  }
  ol.popGeneratorState();
  if (hasParameterList)
  {
    ol.endParameterList();
    ol.endMemberDoc(TRUE);
  }
  else
  {
    ol.endMemberDocName();
    ol.endMemberDoc(FALSE);
  }
  // for HTML write the labels here
  ol.pushGeneratorState();
  ol.disableAll();
  ol.enable(OutputType::Html);
  if (htmlEndLabelTable)
  {
    ol.writeString("  </td>\n");
    ol.writeString("  <td class=\"mlabels-right\">\n");
    ol.startLabels();
    size_t count=0;
    for (const auto &s : sl)
    {
      count++;
      ol.writeLabel(s.c_str(),count==sl.size());
    }
    ol.endLabels();
    ol.writeString("  </td>\n");
    ol.writeString("  </tr>\n");
    ol.writeString("</table>\n");
  }
  ol.writeString("</div>");
  ol.popGeneratorState();
  ol.endDoxyAnchor(cfname,memAnchor);
  ol.startIndent();
  _writeGroupInclude(ol,inGroup);
  /* write multi-line initializer (if any) */
  if (hasMultiLineInitializer()) _writeMultiLineInitializer(ol,scopeName);
  /* write brief description */
  QCString brief = briefDescription();
  if (!brief.isEmpty() &&
      (Config_getBool(REPEAT_BRIEF) ||
       !Config_getBool(BRIEF_MEMBER_DESC)
      )
     )
  {
    ol.startParagraph();
    ol.generateDoc(briefFile(),briefLine(),
                scopedContainer,this,
                brief,FALSE,FALSE,
                QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    ol.endParagraph();
  }
  /* write detailed description */
  QCString detailed = documentation();
  if (!detailed.isEmpty() ||
      !inbodyDocumentation().isEmpty())
  {
    // write vhdl inline code with or without option INLINE_SOURCE
    if (optVhdl && VhdlDocGen::isMisc(this))
    {
      VhdlDocGen::writeSource(this,ol,cname);
      return;
    }
    else
    {
      ol.generateDoc(docFile(),docLine(),scopedContainer,this,detailed+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    if (!inbodyDocumentation().isEmpty())
    {
      ol.generateDoc(inbodyFile(),inbodyLine(),
                     scopedContainer,this,
                     inbodyDocumentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
  }
  else if (!brief.isEmpty() && (Config_getBool(REPEAT_BRIEF) || !Config_getBool(BRIEF_MEMBER_DESC)))
  {
    if (!inbodyDocumentation().isEmpty())
    {
      ol.generateDoc(inbodyFile(),inbodyLine(),scopedContainer,this,inbodyDocumentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
  }
  //printf("***** defArgList=%p name=%s docs=%s hasDocs=%d\n",
  //     defArgList,
  //     defArgList?defArgList->hasDocumentation():-1);
  const ArgumentList &docArgList = m_templateMaster ?
                                   m_templateMaster->argumentList() :
                                   m_defArgList;
  ol.generateDoc(
        docFile(),docLine(),
        scopedContainer,
        this,         // memberDef
        inlineArgListToDoc(docArgList),    // docStr
        TRUE,         // indexWords
        FALSE,        // isExample
        QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT)
        );
  _writeEnumValues(ol,scopedContainer,cfname,ciname,cname);
  _writeReimplements(ol);
  _writeReimplementedBy(ol);
  _writeCategoryRelation(ol);
  _writeExamples(ol);
  _writeTypeConstraints(ol);
  QCString scopeStr = getScopeString();
  writeSourceDef(ol);
  writeInlineCode(ol,scopeStr);
  if (hasReferencesRelation()) writeSourceRefs(ol,scopeStr);
  if (hasReferencedByRelation()) writeSourceReffedBy(ol,scopeStr);
  _writeCallGraph(ol);
  _writeCallerGraph(ol);
  ol.endIndent();
  // enable LaTeX again
  //if (Config_getBool(EXTRACT_ALL) && !hasDocs) ol.enable(OutputType::Latex);
  ol.popGeneratorState();
  warnIfUndocumentedParams();
}
References _writeCallerGraph(), _writeCallGraph(), _writeCategoryRelation(), _writeEnumValues(), _writeExamples(), _writeGroupInclude(), _writeMultiLineInitializer(), _writeReimplementedBy(), _writeReimplements(), _writeTemplatePrefix(), _writeTypeConstraints(), OutputList::addLabel(), anchor(), argsString(), QCString::at(), briefDescription(), DefinitionMixin< MemberDefMutable >::briefFile(), DefinitionMixin< MemberDefMutable >::briefLine(), ClassDef::compoundTypeString(), Config_getBool, Cpp, definition(), Definition::definitionType(), OutputList::disable(), OutputList::disableAll(), Definition::displayName(), DefinitionMixin< MemberDefMutable >::docFile(), OutputList::docify(), DefinitionMixin< MemberDefMutable >::docLine(), documentation(), ArgumentList::empty(), OutputList::enable(), OutputList::endDoxyAnchor(), OutputList::endIndent(), OutputList::endLabels(), OutputList::endMemberDoc(), OutputList::endMemberDocName(), OutputList::endMemberDocPrefixItem(), OutputList::endParagraph(), OutputList::endParameterList(), excpString(), FALSE, QCString::find(), QCString::findRev(), found, OutputList::generateDoc(), DefinitionMixin< MemberDefMutable >::getBodyDef(), getClassDef(), getClassDefOfAnonymousType(), getFileDef(), getGroupDef(), getLabels(), Definition::getLanguage(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), getModuleDef(), getNamespaceDef(), getOutputFileBase(), getScopeString(), ClassDef::getTemplateParameterLists(), hasMultiLineInitializer(), hasOneLineInitializer(), hasReferencedByRelation(), hasReferencesRelation(), Html, Definition::inbodyDocumentation(), DefinitionMixin< MemberDefMutable >::inbodyDocumentation(), DefinitionMixin< MemberDefMutable >::inbodyFile(), DefinitionMixin< MemberDefMutable >::inbodyLine(), init(), inlineArgListToDoc(), isDefine(), QCString::isEmpty(), isEnumerate(), isEnumStruct(), isEnumValue(), isFunction(), isId(), isLinkable(), VhdlDocGen::isMisc(), isObjCMethod(), ClassDef::isObjectiveC(), isSliceLocal(), isStatic(), isStrong(), isTemplateSpecialization(), isTypeAlias(), isTypedef(), isVariable(), QCString::left(), QCString::length(), linkifyText(), m_defArgList, m_defTmpArgLists, m_enumBaseType, m_initializer, m_metaData, m_tArgList, m_templateMaster, QCString::mid(), Definition::name(), DefinitionMixin< MemberDefMutable >::name(), OutputList::popGeneratorState(), prefix, QCString::prepend(), OutputList::pushGeneratorState(), reAnonymous, QCString::remove(), removeAnonymousScopes(), reg::search(), Slice, OutputList::startDoxyAnchor(), OutputList::startIndent(), OutputList::startLabels(), OutputList::startMemberDoc(), OutputList::startMemberDocName(), OutputList::startMemberDocPrefixItem(), OutputList::startParagraph(), QCString::str(), QCString::stripPrefix(), substitute(), toGroupDef(), TRUE, Definition::TypeFile, Definition::TypeGroup, VHDL, warnIfUndocumentedParams(), writeDefArgumentList(), writeExceptionList(), DefinitionMixin< MemberDefMutable >::writeInlineCode(), OutputList::writeLabel(), OutputList::writeNonBreakableSpace(), VhdlDocGen::writeSource(), DefinitionMixin< MemberDefMutable >::writeSourceDef(), DefinitionMixin< MemberDefMutable >::writeSourceReffedBy(), DefinitionMixin< MemberDefMutable >::writeSourceRefs(), OutputList::writeString(), and VhdlDocGen::writeVHDLTypeDocumentation().
writeEnumDeclaration()
void MemberDefImpl::writeEnumDeclaration (OutputList & typeDecl, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, const ModuleDef * mod) const override virtual
Implements MemberDef.
Definition at line 4742 of file memberdef.cpp.
{
  int enumMemCount=0;
  uint32_t numVisibleEnumValues=0;
  for (const auto &fmd : m_enumFields)
  {
    if (fmd->isBriefSectionVisible()) numVisibleEnumValues++;
  }
  if (numVisibleEnumValues==0 && !isBriefSectionVisible())
  {
    return;
  }
  QCString n = name();
  int i=n.findRev("::");
  if (i!=-1) n=n.right(n.length()-i-2); // strip scope (TODO: is this needed?)
  if (n[0]!='@') // not an anonymous enum
  {
    if (isLinkableInProject() || hasDocumentedEnumValues())
    {
      //_writeTagData(compoundType);
      writeLink(typeDecl,cd,nd,fd,gd,mod);
    }
    else
    {
      typeDecl.startBold();
      typeDecl.docify(n);
      typeDecl.endBold();
    }
    typeDecl.writeChar(' ');
  }
  if (!m_enumBaseType.isEmpty())
  {
    typeDecl.writeChar(':');
    typeDecl.writeChar(' ');
    typeDecl.docify(m_enumBaseType);
    typeDecl.writeChar(' ');
  }
  uint32_t enumValuesPerLine = static_cast<uint32_t>(Config_getInt(ENUM_VALUES_PER_LINE));
  if (numVisibleEnumValues>0 && enumValuesPerLine>0)
  {
    typeDecl.docify("{ ");
    auto it = m_enumFields.begin();
    if (it!=m_enumFields.end())
    {
      const MemberDef *fmd=*it;
      bool fmdVisible = fmd->isBriefSectionVisible();
      bool first=true;
      while (fmd)
      {
        if (fmdVisible)
        {
          if (!first)
          {
            typeDecl.writeString(", ");
          }
          /* in html we start a new line after a number of items */
          if (numVisibleEnumValues>enumValuesPerLine
              && (enumMemCount%enumValuesPerLine)==0
             )
          {
            typeDecl.pushGeneratorState();
            typeDecl.disableAllBut(OutputType::Html);
            typeDecl.enable(OutputType::Latex);
            typeDecl.enable(OutputType::Docbook);
            typeDecl.lineBreak();
            typeDecl.disable(OutputType::Latex);
            typeDecl.disable(OutputType::Docbook);
            typeDecl.writeString("&#160;&#160;");
            typeDecl.popGeneratorState();
          }
          if (fmd->hasDocumentation()) // enum value has docs
          {
            fmd->writeLink(typeDecl,cd,nd,fd,gd,mod);
          }
          else // no docs for this enum value
          {
            typeDecl.startBold();
            typeDecl.docify(fmd->name());
            typeDecl.endBold();
          }
          if (fmd->hasOneLineInitializer()) // enum value has initializer
          {
            //typeDecl.writeString(" = ");
            typeDecl.writeString(" ");
            typeDecl.parseText(fmd->initializer());
          }
          first=false;
        }
        bool prevVisible = fmdVisible;
        ++it;
        if (it!=m_enumFields.end())
        {
          fmd=*it;
        }
        else
        {
          fmd=nullptr;
        }
        if (prevVisible)
        {
          typeDecl.disable(OutputType::Man);
          typeDecl.writeString("\n"); // to prevent too long lines in LaTeX
          typeDecl.enable(OutputType::Man);
          enumMemCount++;
        }
      }
      if (numVisibleEnumValues>enumValuesPerLine)
      {
        typeDecl.pushGeneratorState();
        typeDecl.disableAllBut(OutputType::Html);
        typeDecl.lineBreak();
        typeDecl.popGeneratorState();
      }
    }
    typeDecl.docify(" }");
  }
}
References Config_getInt, OutputList::disable(), OutputList::disableAllBut(), Docbook, OutputList::docify(), OutputList::enable(), OutputList::endBold(), QCString::findRev(), Definition::hasDocumentation(), hasDocumentedEnumValues(), MemberDef::hasOneLineInitializer(), Html, MemberDef::initializer(), MemberDef::isBriefSectionVisible(), isBriefSectionVisible(), isLinkableInProject(), Latex, QCString::length(), OutputList::lineBreak(), m_enumBaseType, m_enumFields, Man, Definition::name(), DefinitionMixin< MemberDefMutable >::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), QCString::right(), OutputList::startBold(), OutputList::writeChar(), MemberDef::writeLink(), writeLink(), and OutputList::writeString().
writeLink()
void MemberDefImpl::writeLink (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, const ModuleDef * mod, bool onlyText = FALSE) const override virtual
Implements MemberDef.
Definition at line 1925 of file memberdef.cpp.
{
  SrcLangExt lang = getLanguage();
  bool hideScopeNames     = Config_getBool(HIDE_SCOPE_NAMES);
  QCString sep = getLanguageSpecificSeparator(lang,TRUE);
  QCString n = name();
  const ClassDef *classDef = getClassDef();
  const ModuleDef *moduleDef = getModuleDef();
  const NamespaceDef *nspace = getNamespaceDef();
  if (!hideScopeNames)
  {
    if (m_enumScope && m_livesInsideEnum && getGroupDef()!=nullptr)
    {
      n.prepend(m_enumScope->displayName()+sep);
    }
    if (classDef && gd && !isRelated())
    {
      n.prepend(classDef->displayName()+sep);
    }
    else if (nspace && (gd || fd || moduleDef))
    {
      n.prepend(nspace->displayName()+sep);
    }
  }
  if (isObjCMethod())
  {
    if (isStatic()) ol.docify("+ "); else ol.docify("- ");
  }
  if (!onlyText && (isLinkable() || hasDetailedDescription())) // write link
  {
    if (m_mtype==MemberType::EnumValue && getGroupDef()==nullptr &&          // enum value is not grouped
        getEnumScope() && getEnumScope()->getGroupDef()) // but its container is
    {
      const GroupDef *enumValGroup = getEnumScope()->getGroupDef();
      ol.writeObjectLink(enumValGroup->getReference(),
                         enumValGroup->getOutputFileBase(),
                         anchor(),n);
    }
    else
    {
      ol.writeObjectLink(getReference(),getOutputFileBase(),anchor(),n);
    }
  }
  else // write only text
  {
    ol.startBold();
    ol.docify(n);
    ol.endBold();
  }
}
References anchor(), Config_getBool, Definition::displayName(), OutputList::docify(), OutputList::endBold(), EnumValue, getClassDef(), getEnumScope(), MemberDef::getGroupDef(), getGroupDef(), DefinitionMixin< MemberDefMutable >::getLanguage(), getLanguageSpecificSeparator(), getModuleDef(), getNamespaceDef(), Definition::getOutputFileBase(), getOutputFileBase(), Definition::getReference(), getReference(), hasDetailedDescription(), isLinkable(), isObjCMethod(), isRelated(), isStatic(), m_enumScope, m_livesInsideEnum, m_mtype, DefinitionMixin< MemberDefMutable >::name(), QCString::prepend(), OutputList::startBold(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDeclaration(), and writeEnumDeclaration().
writeMemberDocSimple()
void MemberDefImpl::writeMemberDocSimple (OutputList & ol, const Definition * container) const override virtual
Implements MemberDefMutable.
Definition at line 3936 of file memberdef.cpp.
{
  Definition *scope  = getOuterScope();
  QCString doxyName  = name();
  QCString doxyArgs  = argsString();
  QCString memAnchor = anchor();
  QCString cfname    = getOutputFileBase();
  QCString cname;
  if (scope) cname   = scope->name();
  if (doxyName.at(0)=='@')
  {
    doxyName="__unnamed__";
  }
  ClassDef *cd = m_accessorClass;
  //printf("===> %s::anonymous: %s\n",qPrint(name()),cd?qPrint(cd->name()):"<none>");
  if (container && container->definitionType()==Definition::TypeClass &&
      !(toClassDef(container))->isJavaEnum())
  {
    ol.startInlineMemberType();
    ol.startDoxyAnchor(cfname,cname,memAnchor,doxyName,doxyArgs);
    ol.addLabel(cfname,memAnchor);
    QCString ts = fieldType();
    if (isFunctionPtr())
        ts = m_type + m_args;
    if (cd) // cd points to an anonymous struct pointed to by this member
      // so we add a link to it from the type column.
    {
      int i=0;
      const char *prefixes[] = { "struct ","union ","class ", nullptr };
      const char **p = prefixes;
      while (*p)
      {
        int l=qstrlen(*p);
        if (ts.left(l)==*p)
        {
          ol.writeString(*p);
          i=l;
        }
        p++;
      }
      ol.writeObjectLink(cd->getReference(),
          cd->getOutputFileBase(),
          cd->anchor(),ts.mid(i));
    }
    else // use standard auto linking
    {
      linkifyText(TextGeneratorOLImpl(ol), // out
          scope,                   // scope
          getBodyDef(),            // fileScope
          this,                    // self
          ts                       // text
          );
    }
    ol.endDoxyAnchor(cfname,memAnchor);
    ol.endInlineMemberType();
  }
  ol.startInlineMemberName();
  ol.docify(doxyName);
  if (isVariable() && !argsString().isEmpty() && !isObjCMethod() && !isFunctionPtr())
  {
    linkifyText(TextGeneratorOLImpl(ol),getOuterScope(),getBodyDef(),this,argsString());
  }
  if (!m_bitfields.isEmpty()) // add bitfields
  {
    linkifyText(TextGeneratorOLImpl(ol),getOuterScope(),getBodyDef(),this,m_bitfields);
  }
  if (hasOneLineInitializer() && !isDefine())
  {
    ol.writeString(" ");
    linkifyText(TextGeneratorOLImpl(ol),getOuterScope(),getBodyDef(),this,m_initializer.simplifyWhiteSpace());
  }
  ol.endInlineMemberName();
  ol.startInlineMemberDoc();
  QCString brief           = briefDescription();
  QCString detailed        = documentation();
  /* write brief description */
  if (!brief.isEmpty())
  {
    ol.generateDoc(briefFile(),briefLine(),
                getOuterScope()?getOuterScope():container,this,
                brief,FALSE,FALSE,
                QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
  }
  /* write detailed description */
  if (!detailed.isEmpty())
  {
    if (!brief.isEmpty())
    {
      ol.disable(OutputType::Html);
      ol.lineBreak();
      ol.enable(OutputType::Html);
    }
    ol.generateDoc(docFile(),docLine(),
                getOuterScope()?getOuterScope():container,this,
                detailed+"\n",FALSE,FALSE,
                QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
  }
  ol.endInlineMemberDoc();
}
References OutputList::addLabel(), Definition::anchor(), anchor(), argsString(), QCString::at(), briefDescription(), DefinitionMixin< MemberDefMutable >::briefFile(), DefinitionMixin< MemberDefMutable >::briefLine(), Config_getBool, Definition::definitionType(), OutputList::disable(), DefinitionMixin< MemberDefMutable >::docFile(), OutputList::docify(), DefinitionMixin< MemberDefMutable >::docLine(), documentation(), OutputList::enable(), OutputList::endDoxyAnchor(), OutputList::endInlineMemberDoc(), OutputList::endInlineMemberName(), OutputList::endInlineMemberType(), FALSE, fieldType(), OutputList::generateDoc(), DefinitionMixin< MemberDefMutable >::getBodyDef(), DefinitionMixin< MemberDefMutable >::getOuterScope(), Definition::getOutputFileBase(), getOutputFileBase(), Definition::getReference(), hasOneLineInitializer(), Html, isDefine(), QCString::isEmpty(), isFunctionPtr(), isObjCMethod(), isVariable(), QCString::left(), OutputList::lineBreak(), linkifyText(), m_accessorClass, m_args, m_bitfields, m_initializer, m_type, QCString::mid(), Definition::name(), DefinitionMixin< MemberDefMutable >::name(), qstrlen(), OutputList::startDoxyAnchor(), OutputList::startInlineMemberDoc(), OutputList::startInlineMemberName(), OutputList::startInlineMemberType(), toClassDef(), TRUE, Definition::TypeClass, OutputList::writeObjectLink(), and OutputList::writeString().
writeTagFile()
void MemberDefImpl::writeTagFile (TextStream & tagFile, bool useQualifiedName, bool showNamespaceMembers) const override virtual
Implements MemberDefMutable.
Definition at line 4574 of file memberdef.cpp.
{
  if (!isLinkableInProject()) return;
  if (!showNamespaceMembers && getNamespaceDef()) return;
  tagFile << "    <member kind=\"";
  switch (m_mtype)
  {
    case MemberType::Define:      tagFile << "define";      break;
    case MemberType::EnumValue:   tagFile << "enumvalue";   break;
    case MemberType::Property:    tagFile << "property";    break;
    case MemberType::Event:       tagFile << "event";       break;
    case MemberType::Variable:    tagFile << "variable";    break;
    case MemberType::Typedef:     tagFile << "typedef";     break;
    case MemberType::Enumeration: tagFile << "enumeration"; break;
    case MemberType::Function:    tagFile << "function";    break;
    case MemberType::Signal:      tagFile << "signal";      break;
    case MemberType::Friend:      tagFile << "friend";      break;
    case MemberType::DCOP:        tagFile << "dcop";        break;
    case MemberType::Slot:        tagFile << "slot";        break;
    case MemberType::Interface:   tagFile << "interface";   break;
    case MemberType::Service:     tagFile << "service";     break;
    case MemberType::Sequence:    tagFile << "sequence";    break;
    case MemberType::Dictionary:  tagFile << "dictionary";  break;
  }
  if (m_prot!=Protection::Public)
  {
    tagFile << "\" protection=\"";
    if (m_prot==Protection::Protected)    tagFile << "protected";
    else if (m_prot==Protection::Package) tagFile << "package";
    else /* Private */                          tagFile << "private";
  }
  if (m_virt!=Specifier::Normal)
  {
    tagFile << "\" virtualness=\"";
    if (m_virt==Specifier::Virtual) tagFile << "virtual";
    else /* Pure */                       tagFile << "pure";
  }
  if (isStatic())
  {
    tagFile << "\" static=\"yes";
  }
  tagFile << "\">\n";
  if (typeString()!=QCString("@"))
  {
    tagFile << "      <type>" << convertToXML(typeString()) << "</type>\n";
  }
  QCString fn = getOutputFileBase();
  addHtmlExtensionIfMissing(fn);
  tagFile << "      <name>" << convertToXML(useQualifiedName ? qualifiedName() : name()) << "</name>\n";
  tagFile << "      <anchorfile>" << convertToXML(fn) << "</anchorfile>\n";
  tagFile << "      <anchor>" << convertToXML(anchor()) << "</anchor>\n";
  QCString idStr = id();
  if (!idStr.isEmpty())
  {
    tagFile << "      <clangid>" << convertToXML(idStr) << "</clangid>\n";
  }
  tagFile << "      <arglist>" << convertToXML(argsString()) << "</arglist>\n";
  if (isStrong())
  {
    for (const auto &fmd : m_enumFields)
    {
      if (!fmd->isReference())
      {
        tagFile << "      <enumvalue file=\"" << convertToXML(fn);
        tagFile << "\" anchor=\"" << convertToXML(fmd->anchor());
        idStr = fmd->id();
        if (!idStr.isEmpty())
        {
          tagFile << "\" clangid=\"" << convertToXML(idStr);
        }
        tagFile  << "\">" << convertToXML(fmd->name()) << "</enumvalue>\n";
      }
    }
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << "    </member>\n";
}
References addHtmlExtensionIfMissing(), anchor(), argsString(), convertToXML(), DCOP, Define, Dictionary, Enumeration, EnumValue, Event, Friend, Function, getNamespaceDef(), getOutputFileBase(), DefinitionMixin< MemberDefMutable >::id(), Interface, QCString::isEmpty(), isLinkableInProject(), isStatic(), isStrong(), m_enumFields, m_mtype, m_prot, m_virt, DefinitionMixin< MemberDefMutable >::name(), Normal, Package, Property, Protected, Public, qualifiedName(), Sequence, Service, Signal, Slot, Typedef, typeString(), Variable, Virtual, and DefinitionMixin< MemberDefMutable >::writeDocAnchorsToTagFile().
Member Data Documentation
m_accessorClass
ClassDef* MemberDefImpl::m_accessorClass = nullptr private
Definition at line 415 of file memberdef.cpp.
Referenced by accessorClass(), deepCopy(), init(), setAccessorType(), and writeMemberDocSimple().
m_accessorType
QCString MemberDefImpl::m_accessorType private
Definition at line 414 of file memberdef.cpp.
Referenced by deepCopy(), fieldType(), and setAccessorType().
m_anc
QCString MemberDefImpl::m_anc private
Definition at line 418 of file memberdef.cpp.
Referenced by anchor(), deepCopy(), setAnchor(), and setTagInfo().
m_annEnumType
const MemberDef* MemberDefImpl::m_annEnumType = nullptr private
Definition at line 401 of file memberdef.cpp.
Referenced by deepCopy(), getAnonymousEnumType(), init(), setAnonymousEnumType(), and writeDeclaration().
m_annMemb
MemberDef* MemberDefImpl::m_annMemb = nullptr private
Definition at line 438 of file memberdef.cpp.
Referenced by deepCopy(), fromAnonymousMember(), init(), setFromAnonymousMember(), and writeDeclaration().
m_annScope
bool MemberDefImpl::m_annScope = false private
Definition at line 492 of file memberdef.cpp.
Referenced by deepCopy(), fromAnonymousScope(), init(), isBriefSectionVisible(), and setFromAnonymousScope().
m_args
QCString MemberDefImpl::m_args private
Definition at line 416 of file memberdef.cpp.
Referenced by argsString(), createTemplateInstanceMember(), deepCopy(), init(), setAnchor(), setArgsString(), and writeMemberDocSimple().
m_bitfields
QCString MemberDefImpl::m_bitfields private
Definition at line 423 of file memberdef.cpp.
Referenced by _isAnonymousBitField(), bitfieldString(), deepCopy(), setBitfields(), writeDeclaration(), and writeMemberDocSimple().
m_cachedAnonymousType
ClassDef* MemberDefImpl::m_cachedAnonymousType = nullptr mutable private
Definition at line 452 of file memberdef.cpp.
Referenced by deepCopy(), getClassDefOfAnonymousType(), and init().
m_cachedResolvedType
QCString MemberDefImpl::m_cachedResolvedType private
Definition at line 470 of file memberdef.cpp.
Referenced by cacheTypedefVal(), deepCopy(), and getCachedResolvedTypedef().
m_cachedTypedefTemplSpec
QCString MemberDefImpl::m_cachedTypedefTemplSpec private
Definition at line 469 of file memberdef.cpp.
Referenced by cacheTypedefVal(), deepCopy(), and getCachedTypedefTemplSpec().
m_cachedTypedefValue
const ClassDef* MemberDefImpl::m_cachedTypedefValue = nullptr private
Definition at line 468 of file memberdef.cpp.
Referenced by cacheTypedefVal(), deepCopy(), getCachedTypedefVal(), and init().
m_category
ClassDef* MemberDefImpl::m_category = nullptr private
Definition at line 508 of file memberdef.cpp.
Referenced by _writeCategoryRelation(), category(), deepCopy(), and setCategory().
m_categoryRelation
const MemberDef* MemberDefImpl::m_categoryRelation = nullptr private
Definition at line 509 of file memberdef.cpp.
Referenced by _writeCategoryRelation(), categoryRelation(), deepCopy(), and setCategoryRelation().
m_classDef
ClassDef* MemberDefImpl::m_classDef = nullptr private
Definition at line 394 of file memberdef.cpp.
Referenced by deepCopy(), getClassDef(), getClassDef(), getClassDefMutable(), init(), moveTo(), setEnumClassScope(), and setMemberClass().
m_decl
QCString MemberDefImpl::m_decl private
Definition at line 421 of file memberdef.cpp.
Referenced by declaration(), deepCopy(), and init().
m_declArgList
ArgumentList MemberDefImpl::m_declArgList private
Definition at line 441 of file memberdef.cpp.
Referenced by copyArgumentNames(), declArgumentList(), deepCopy(), init(), invalidateCachedArgumentTypes(), moveDeclArgumentList(), and resolveUnnamedParameters().
m_declColumn
int MemberDefImpl::m_declColumn = -1 private
Definition at line 512 of file memberdef.cpp.
Referenced by deepCopy(), getDeclColumn(), and setDeclFile().
m_declFileName
QCString MemberDefImpl::m_declFileName private
Definition at line 510 of file memberdef.cpp.
Referenced by deepCopy(), getDeclFileName(), and setDeclFile().
m_declLine
int MemberDefImpl::m_declLine = -1 private
Definition at line 511 of file memberdef.cpp.
Referenced by deepCopy(), getDeclLine(), and setDeclFile().
m_def
QCString MemberDefImpl::m_def private
Definition at line 417 of file memberdef.cpp.
Referenced by createTemplateInstanceMember(), deepCopy(), definition(), and setDefinition().
m_defArgList
ArgumentList MemberDefImpl::m_defArgList private
Definition at line 440 of file memberdef.cpp.
Referenced by argumentList(), copyArgumentNames(), createTemplateInstanceMember(), deepCopy(), hasDetailedDescription(), hasDocumentation(), hasMultiLineInitializer(), hasOneLineInitializer(), init(), invalidateCachedArgumentTypes(), isBriefSectionVisible(), isDeleted(), moveArgumentList(), resolveUnnamedParameters(), and writeDocumentation().
m_defTmpArgLists
ArgumentLists MemberDefImpl::m_defTmpArgLists private
Definition at line 447 of file memberdef.cpp.
Referenced by deepCopy(), definitionTemplateParameterLists(), setDefinitionTemplateParameterLists(), and writeDocumentation().
m_detailedDescriptionCachedValue
bool MemberDefImpl::m_detailedDescriptionCachedValue = false mutable private
Definition at line 494 of file memberdef.cpp.
Referenced by deepCopy(), and hasDetailedDescription().
m_docEnumValues
bool MemberDefImpl::m_docEnumValues = false private
Definition at line 490 of file memberdef.cpp.
Referenced by deepCopy(), hasDocumentation(), hasDocumentedEnumValues(), init(), and setDocumentedEnumValues().
m_docProvider
const MemberDef* MemberDefImpl::m_docProvider = nullptr private
Definition at line 473 of file memberdef.cpp.
Referenced by deepCopy(), inheritsDocsFrom(), init(), and setInheritsDocsFrom().
m_docsForDefinition
bool MemberDefImpl::m_docsForDefinition = false private
Definition at line 505 of file memberdef.cpp.
Referenced by deepCopy(), init(), isDocsForDefinition(), and setDocsForDefinition().
m_enumBaseType
QCString MemberDefImpl::m_enumBaseType private
Definition at line 429 of file memberdef.cpp.
Referenced by deepCopy(), displayDefinition(), enumBaseType(), setEnumBaseType(), writeDocumentation(), and writeEnumDeclaration().
m_enumFields
MemberVector MemberDefImpl::m_enumFields private
Definition at line 402 of file memberdef.cpp.
Referenced by deepCopy(), enumFieldList(), insertEnumField(), writeEnumDeclaration(), and writeTagFile().
m_enumScope
const MemberDef* MemberDefImpl::m_enumScope = nullptr private
Definition at line 399 of file memberdef.cpp.
Referenced by anchor(), deepCopy(), getEnumScope(), init(), isStrongEnumValue(), qualifiedName(), setEnumScope(), and writeLink().
m_examples
ExampleList MemberDefImpl::m_examples private
Definition at line 411 of file memberdef.cpp.
Referenced by _writeExamples(), addExample(), deepCopy(), getExamples(), and hasExamples().
m_exception
QCString MemberDefImpl::m_exception private
Definition at line 426 of file memberdef.cpp.
Referenced by createTemplateInstanceMember(), deepCopy(), excpString(), and init().
m_explExt
bool MemberDefImpl::m_explExt = false private
Definition at line 502 of file memberdef.cpp.
Referenced by deepCopy(), init(), isExternal(), and setExplicitExternal().
m_explicitOutputFileBase
QCString MemberDefImpl::m_explicitOutputFileBase private
Definition at line 476 of file memberdef.cpp.
Referenced by deepCopy(), getOutputFileBase(), and setTagInfo().
m_extraTypeChars
QCString MemberDefImpl::m_extraTypeChars private
Definition at line 428 of file memberdef.cpp.
Referenced by deepCopy(), extraTypeChars(), and init().
m_fileDef
FileDef* MemberDefImpl::m_fileDef = nullptr private
Definition at line 395 of file memberdef.cpp.
Referenced by deepCopy(), getFileDef(), getFileDef(), init(), moveTo(), and setFileDef().
m_formalTemplateArguments
std::optional<ArgumentList> MemberDefImpl::m_formalTemplateArguments private
Definition at line 446 of file memberdef.cpp.
Referenced by deepCopy(), formalTemplateArguments(), and setFormalTemplateArguments().
m_group
GroupDef* MemberDefImpl::m_group = nullptr private
Definition at line 461 of file memberdef.cpp.
Referenced by deepCopy(), getGroupDef(), getGroupDef(), init(), setEnumScope(), and setGroupDef().
m_groupAlias
const MemberDef* MemberDefImpl::m_groupAlias = nullptr private
Definition at line 458 of file memberdef.cpp.
Referenced by anchor(), deepCopy(), getGroupAlias(), init(), and setGroupAlias().
m_groupFileName
QCString MemberDefImpl::m_groupFileName private
Definition at line 463 of file memberdef.cpp.
Referenced by deepCopy(), getGroupFileName(), setEnumScope(), and setGroupDef().
m_groupHasDocs
bool MemberDefImpl::m_groupHasDocs = false private
Definition at line 504 of file memberdef.cpp.
Referenced by deepCopy(), getGroupHasDocs(), setEnumScope(), and setGroupDef().
m_groupMember
MemberDef* MemberDefImpl::m_groupMember = nullptr private
Definition at line 465 of file memberdef.cpp.
Referenced by anchor(), deepCopy(), init(), and setGroupDef().
m_grouppri
Grouping::GroupPri_t MemberDefImpl::m_grouppri = Grouping::GROUPING_AUTO_DEF private
Definition at line 462 of file memberdef.cpp.
Referenced by deepCopy(), getGroupPri(), setEnumScope(), and setGroupDef().
m_groupStartLine
int MemberDefImpl::m_groupStartLine = 0 private
Definition at line 464 of file memberdef.cpp.
Referenced by deepCopy(), getGroupStartLine(), setEnumScope(), and setGroupDef().
m_grpId
int MemberDefImpl::m_grpId = 0 private
Definition at line 459 of file memberdef.cpp.
Referenced by deepCopy(), getMemberGroupId(), init(), and setMemberGroupId().
m_hasCallerGraph
bool MemberDefImpl::m_hasCallerGraph = false private
Definition at line 497 of file memberdef.cpp.
Referenced by _hasVisibleCallerGraph(), deepCopy(), hasCallerGraph(), init(), and overrideCallerGraph().
m_hasCallGraph
bool MemberDefImpl::m_hasCallGraph = false private
Definition at line 496 of file memberdef.cpp.
Referenced by _hasVisibleCallGraph(), deepCopy(), hasCallGraph(), init(), and overrideCallGraph().
m_hasDetailedDescriptionCached
bool MemberDefImpl::m_hasDetailedDescriptionCached = false mutable private
Definition at line 493 of file memberdef.cpp.
Referenced by deepCopy(), and hasDetailedDescription().
m_hasDocumentedParams
bool MemberDefImpl::m_hasDocumentedParams = false mutable private
Definition at line 484 of file memberdef.cpp.
Referenced by deepCopy(), detectUndocumentedParams(), init(), and warnIfUndocumentedParams().
m_hasDocumentedReturnType
bool MemberDefImpl::m_hasDocumentedReturnType = false mutable private
Definition at line 485 of file memberdef.cpp.
Referenced by deepCopy(), detectUndocumentedParams(), init(), and warnIfUndocumentedParams().
m_hasEnumValues
bool MemberDefImpl::m_hasEnumValues = false private
Definition at line 501 of file memberdef.cpp.
Referenced by deepCopy(), hasEnumValues(), init(), and overrideEnumValues().
m_hasInlineSource
bool MemberDefImpl::m_hasInlineSource = false private
Definition at line 500 of file memberdef.cpp.
Referenced by deepCopy(), hasInlineSource(), init(), and overrideInlineSource().
m_hasReferencedByRelation
bool MemberDefImpl::m_hasReferencedByRelation = false private
Definition at line 498 of file memberdef.cpp.
Referenced by deepCopy(), hasReferencedByRelation(), init(), and overrideReferencedByRelation().
m_hasReferencesRelation
bool MemberDefImpl::m_hasReferencesRelation = false private
Definition at line 499 of file memberdef.cpp.
Referenced by deepCopy(), hasReferencesRelation(), init(), and overrideReferencesRelation().
m_implOnly
bool MemberDefImpl::m_implOnly = false private
Definition at line 482 of file memberdef.cpp.
Referenced by deepCopy(), init(), isImplementation(), and makeImplementationDetail().
m_initializer
QCString MemberDefImpl::m_initializer private
Definition at line 427 of file memberdef.cpp.
Referenced by _writeMultiLineInitializer(), deepCopy(), hasMultiLineInitializer(), hasOneLineInitializer(), initializer(), setAnchor(), setInitializer(), writeDeclaration(), writeDocumentation(), and writeMemberDocSimple().
m_initLines
int MemberDefImpl::m_initLines = 0 private
Definition at line 431 of file memberdef.cpp.
Referenced by deepCopy(), hasMultiLineInitializer(), hasOneLineInitializer(), init(), initializerLines(), and setInitializer().
m_isConstructorCached
uint8_t MemberDefImpl::m_isConstructorCached private
Definition at line 391 of file memberdef.cpp.
Referenced by _computeIsConstructor(), isConstructor(), MemberDefImpl(), moveTo(), setEnumClassScope(), setFileDef(), and setMemberClass().
m_isDestructorCached
uint8_t MemberDefImpl::m_isDestructorCached private
Definition at line 392 of file memberdef.cpp.
Referenced by _computeIsDestructor(), isDestructor(), MemberDefImpl(), and setFileDef().
m_isDMember
bool MemberDefImpl::m_isDMember = false private
Definition at line 486 of file memberdef.cpp.
Referenced by _computeIsConstructor(), _computeIsDestructor(), deepCopy(), and init().
m_isLinkableCached
uint8_t MemberDefImpl::m_isLinkableCached private
Definition at line 390 of file memberdef.cpp.
Referenced by _computeLinkableInProject(), isLinkableInProject(), makeForeign(), makeRelated(), MemberDefImpl(), moveTo(), setBriefDescription(), setDocumentation(), setEnumClassScope(), setEnumScope(), setFileDef(), setGroupDef(), setHidden(), setInbodyDocumentation(), setMemberClass(), setMemberType(), setProtection(), and setTemplateMaster().
m_isTypedefValCached
bool MemberDefImpl::m_isTypedefValCached = false private
Definition at line 467 of file memberdef.cpp.
Referenced by cacheTypedefVal(), deepCopy(), init(), invalidateTypedefValCache(), and isTypedefValCached().
m_livesInsideEnum
bool MemberDefImpl::m_livesInsideEnum = false private
Definition at line 400 of file memberdef.cpp.
Referenced by deepCopy(), init(), livesInsideEnum(), setEnumScope(), and writeLink().
m_maxInitLines
int MemberDefImpl::m_maxInitLines = 0 private
Definition at line 436 of file memberdef.cpp.
Referenced by deepCopy(), hasMultiLineInitializer(), hasOneLineInitializer(), and init().
m_memberGroup
MemberGroup* MemberDefImpl::m_memberGroup = nullptr private
Definition at line 460 of file memberdef.cpp.
Referenced by deepCopy(), getMemberGroup(), init(), and setMemberGroup().
m_memDec
MemberDef* MemberDefImpl::m_memDec = nullptr private
Definition at line 408 of file memberdef.cpp.
Referenced by deepCopy(), init(), memberDeclaration(), and setMemberDeclaration().
m_memDef
MemberDef* MemberDefImpl::m_memDef = nullptr private
Definition at line 407 of file memberdef.cpp.
Referenced by deepCopy(), init(), memberDefinition(), and setMemberDefinition().
m_memSpec
TypeSpecifier MemberDefImpl::m_memSpec private
Definition at line 433 of file memberdef.cpp.
Referenced by deepCopy(), getLabels(), getMemberSpecifiers(), init(), isAbstract(), isAddable(), isAssign(), isAttribute(), isBound(), isConstEval(), isConstExpr(), isConstInit(), isConstrained(), isCopy(), isDefault(), isDelete(), isEnumStruct(), isExplicit(), isFinal(), isGettable(), isInitonly(), isInline(), isMaybeAmbiguous(), isMaybeDefault(), isMaybeVoid(), isMutable(), isNew(), isNoDiscard(), isNoExcept(), isNonAtomic(), isOptional(), isOverride(), isPrivateGettable(), isPrivateSettable(), isProtectedGettable(), isProtectedSettable(), isPublished(), isRaisable(), isReadable(), isReadonly(), isRemovable(), isRequired(), isRetain(), isSealed(), isSettable(), isSliceLocal(), isStrong(), isTransient(), isTypeAlias(), isUNOProperty(), isUnretained(), isWeak(), isWritable(), mergeMemberSpecifiers(), setAnchor(), and setMemberSpecifiers().
m_metaData
QCString MemberDefImpl::m_metaData private
Definition at line 450 of file memberdef.cpp.
Referenced by deepCopy(), init(), and writeDocumentation().
m_moduleDef
ModuleDef* MemberDefImpl::m_moduleDef = nullptr private
Definition at line 397 of file memberdef.cpp.
Referenced by deepCopy(), getModuleDef(), init(), moveTo(), and setModuleDef().
m_mtype
MemberType MemberDefImpl::m_mtype = MemberType::Define private
Definition at line 435 of file memberdef.cpp.
Referenced by _computeLinkableInProject(), _writeMultiLineInitializer(), createTemplateInstanceMember(), deepCopy(), hasDetailedDescription(), hasDocumentation(), hasMultiLineInitializer(), hasOneLineInitializer(), init(), isBriefSectionVisible(), isDCOP(), isDefine(), isDictionary(), isEnumerate(), isEnumValue(), isEvent(), isFriend(), isFunction(), isFunctionPtr(), isProperty(), isSequence(), isSignal(), isSlot(), isStrongEnumValue(), isTypedef(), isVariable(), memberType(), memberTypeName(), setMemberType(), writeDeclaration(), writeLink(), and writeTagFile().
m_nspace
NamespaceDef* MemberDefImpl::m_nspace = nullptr private
Definition at line 396 of file memberdef.cpp.
Referenced by deepCopy(), getNamespaceDef(), getNamespaceDef(), init(), moveTo(), and setNamespace().
m_numberOfFlowKW
int MemberDefImpl::m_numberOfFlowKW = 0 private
Definition at line 513 of file memberdef.cpp.
Referenced by deepCopy(), incrementFlowKeyWordCount(), and numberOfFlowKeyWords().
m_prot
Protection MemberDefImpl::m_prot = Protection::Public private
Definition at line 420 of file memberdef.cpp.
Referenced by _computeLinkableInProject(), createTemplateInstanceMember(), deepCopy(), hasDetailedDescription(), init(), isBriefSectionVisible(), protection(), setProtection(), warnIfUndocumented(), writeDeclaration(), and writeTagFile().
m_proto
bool MemberDefImpl::m_proto = false private
Definition at line 489 of file memberdef.cpp.
Referenced by deepCopy(), init(), isPrototype(), and setPrototype().
m_qualifiers
StringVector MemberDefImpl::m_qualifiers private
Definition at line 479 of file memberdef.cpp.
Referenced by addQualifiers(), deepCopy(), getLabels(), and getQualifiers().
m_read
QCString MemberDefImpl::m_read private
Definition at line 424 of file memberdef.cpp.
Referenced by deepCopy(), getReadAccessor(), and setReadAccessor().
m_redefinedBy
MemberVector MemberDefImpl::m_redefinedBy private
Definition at line 405 of file memberdef.cpp.
Referenced by deepCopy(), insertReimplementedBy(), isReimplementedBy(), and reimplementedBy().
m_redefines
MemberDef* MemberDefImpl::m_redefines = nullptr private
Definition at line 404 of file memberdef.cpp.
Referenced by deepCopy(), init(), reimplements(), and setReimplements().
m_related
Relationship MemberDefImpl::m_related = Relationship::Member private
Definition at line 487 of file memberdef.cpp.
Referenced by createTemplateInstanceMember(), deepCopy(), init(), isForeign(), isRelated(), makeForeign(), and makeRelated().
m_relatedAlso
ClassDef* MemberDefImpl::m_relatedAlso = nullptr private
Definition at line 409 of file memberdef.cpp.
Referenced by deepCopy(), init(), relatedAlso(), and setRelatedAlso().
m_requiresClause
QCString MemberDefImpl::m_requiresClause private
Definition at line 430 of file memberdef.cpp.
Referenced by _writeTemplatePrefix(), deepCopy(), requiresClause(), setAnchor(), and setRequiresClause().
m_sectionMap
std::map<const Definition *,const MemberList *> MemberDefImpl::m_sectionMap private
Definition at line 456 of file memberdef.cpp.
Referenced by deepCopy(), getSectionList(), and setSectionList().
m_stat
bool MemberDefImpl::m_stat = false private
Definition at line 488 of file memberdef.cpp.
Referenced by _computeLinkableInProject(), createTemplateInstanceMember(), deepCopy(), init(), and isStatic().
m_tArgList
ArgumentList MemberDefImpl::m_tArgList private
Definition at line 443 of file memberdef.cpp.
Referenced by deepCopy(), init(), setAnchor(), templateArguments(), writeDeclaration(), and writeDocumentation().
m_templateMaster
MemberDef* MemberDefImpl::m_templateMaster = nullptr private
Definition at line 445 of file memberdef.cpp.
Referenced by anchor(), briefDescription(), deepCopy(), documentation(), hasDetailedDescription(), hasUserDocumentation(), init(), insertReimplementedBy(), isLinkable(), isReference(), setTemplateMaster(), templateMaster(), and writeDocumentation().
m_tspec
bool MemberDefImpl::m_tspec = false private
Definition at line 503 of file memberdef.cpp.
Referenced by deepCopy(), init(), isTemplateSpecialization(), and setTemplateSpecialization().
m_type
QCString MemberDefImpl::m_type private
Definition at line 413 of file memberdef.cpp.
Referenced by createTemplateInstanceMember(), deepCopy(), fieldType(), getClassDefOfAnonymousType(), getDeclType(), init(), isFriendClass(), isFriendToHide(), setType(), typeString(), writeDeclaration(), and writeMemberDocSimple().
m_typeConstraints
ArgumentList MemberDefImpl::m_typeConstraints private
Definition at line 444 of file memberdef.cpp.
Referenced by _writeTypeConstraints(), deepCopy(), hasDetailedDescription(), setTypeConstraints(), and typeConstraints().
m_userInitLines
int MemberDefImpl::m_userInitLines = 0 private
Definition at line 437 of file memberdef.cpp.
Referenced by deepCopy(), hasMultiLineInitializer(), hasOneLineInitializer(), init(), and setMaxInitLines().
m_vhdlSpec
VhdlSpecifier MemberDefImpl::m_vhdlSpec private
Definition at line 434 of file memberdef.cpp.
Referenced by deepCopy(), getVhdlSpecifiers(), init(), and setVhdlSpecifiers().
m_virt
Specifier MemberDefImpl::m_virt = Specifier::Normal private
Definition at line 419 of file memberdef.cpp.
Referenced by _computeLinkableInProject(), _writeReimplementedBy(), createTemplateInstanceMember(), deepCopy(), hasDetailedDescription(), init(), isBriefSectionVisible(), virtualness(), writeDeclaration(), and writeTagFile().
m_write
QCString MemberDefImpl::m_write private
Definition at line 425 of file memberdef.cpp.
Referenced by deepCopy(), getWriteAccessor(), and setWriteAccessor().
The documentation for this class was generated from the following file:
src/memberdef.cpp