Doxygen: src/dotgraph.cpp File Reference
dotgraph.cpp File Reference
#include <mutex>
#include <regex>
#include "config.h"
#include "doxygen.h"
#include "indexlist.h"
#include "md5.h"
#include "message.h"
#include "util.h"
#include "dot.h"
#include "dotrunner.h"
#include "dotgraph.h"
#include "dotnode.h"
#include "dotfilepatcher.h"
#include "fileinfo.h"
#include "portable.h"
Macros
#define MAP_CMD "cmapx"
Functions
static bool sameMd5Signature (const QCString &baseName, const QCString &md5)
static bool deliverablesPresent (const QCString &file1, const QCString &file2)
static bool insertMapFile (TextStream &out, const QCString &mapFile, const QCString &relPath, const QCString &mapLabel)
Variables
std::mutex g_dotIndexListMutex
Macro Definition Documentation
MAP_CMD
#define MAP_CMD "cmapx"
Definition at line 34 of file dotgraph.cpp.
Function Documentation
deliverablesPresent()
static bool deliverablesPresent (const QCString & file1, const QCString & file2) static
Definition at line 69 of file dotgraph.cpp.
{
  bool file1Ok = true;
  bool file2Ok = true;
  if (!file1.isEmpty())
  {
    FileInfo fi(file1.str());
    file1Ok = (fi.exists() && fi.size()>0);
  }
  if (!file2.isEmpty())
  {
    FileInfo fi(file2.str());
    file2Ok = (fi.exists() && fi.size()>0);
  }
  return file1Ok && file2Ok;
}
References FileInfo::exists(), QCString::isEmpty(), FileInfo::size(), and QCString::str().
Referenced by DotGraph::prepareDotFile().
insertMapFile()
static bool insertMapFile (TextStream & out, const QCString & mapFile, const QCString & relPath, const QCString & mapLabel) static
Definition at line 86 of file dotgraph.cpp.
{
  FileInfo fi(mapFile.str());
  if (fi.exists() && fi.size()>0) // reuse existing map file
  {
    TextStream t;
    DotFilePatcher::convertMapFile(t,mapFile,relPath,false);
    if (!t.empty())
    {
      out << "<map name=\"" << mapLabel << "\" id=\"" << mapLabel << "\">\n";
      out << t.str();
      out << "</map>\n";
    }
    return true;
  }
  return false; // no map file yet, need to generate it
}
References DotFilePatcher::convertMapFile(), TextStream::empty(), FileInfo::exists(), FileInfo::size(), QCString::str(), and TextStream::str().
Referenced by DotGraph::generateCode().
sameMd5Signature()
static bool sameMd5Signature (const QCString & baseName, const QCString & md5) static
Checks if a file "baseName".md5 exists. If so the contents are compared with md5. If equal FALSE is returned. The .md5 is created or updated after successful creation of the output file.
Definition at line 43 of file dotgraph.cpp.
{
  bool same = false;
  char md5stored[33];
  md5stored[0]=0;
  std::ifstream f = Portable::openInputStream(baseName+".md5",true);
  if (f.is_open())
  {
    // read checksum
    f.read(md5stored,32);
    md5stored[32]='\0';
    // compare checksum
    if (!f.fail() && md5==md5stored)
    {
      same = true;
    }
    //printf("sameSignature(%s,%s==%s)=%d\n",qPrint(baseName),md5stored,qPrint(md5),same);
  }
  else
  {
    //printf("sameSignature(%s) not found\n",qPrint(baseName));
  }
  return same;
}
References Portable::openInputStream().
Referenced by DotGraph::prepareDotFile().
Variable Documentation
g_dotIndexListMutex
std::mutex g_dotIndexListMutex
Definition at line 113 of file dotgraph.cpp.
Referenced by DotGraph::writeGraph().