Doxygen: TranslatorFrench Class Reference
TranslatorFrench Class Reference
#include <src/translator_fr.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description.
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool single) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
QCString trDesignUnitDocumentation () override
VHDL design unit documentation.
QCString trConcept (bool first_capital, bool singular) override
C++20 concept.
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 106 of file translator_fr.h.
Member Function Documentation
getLanguageString()
QCString TranslatorFrench::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 142 of file translator_fr.h.
    {
      return "0x40C French";
    }
idLanguage()
QCString TranslatorFrench::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 118 of file translator_fr.h.
    { return "french"; }
latexLanguageSupportCommand()
QCString TranslatorFrench::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 132 of file translator_fr.h.
    {
      return "\\usepackage[french]{babel}\n"
             "\\NoAutoSpaceBeforeFDP\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorFrench::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1942 of file translator_fr.h.
    { return "Membres hrits additionnels"; }
trAll()
QCString TranslatorFrench::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1456 of file translator_fr.h.
    {
      return "Tout";
    }
trAndMore()
QCString TranslatorFrench::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1920 of file translator_fr.h.
    { return "et "+number+" de plus..."; }
trAttention()
QCString TranslatorFrench::trAttention () inline override virtual
Implements Translator.
Definition at line 1031 of file translator_fr.h.
    {
      return "Attention";
    }
trAuthor()
QCString TranslatorFrench::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1329 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "auteur", "s");
    }
References Translator::createNoun().
trBug()
QCString TranslatorFrench::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1199 of file translator_fr.h.
    {
      return "Bogue";
    }
trBugList()
QCString TranslatorFrench::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1204 of file translator_fr.h.
    {
      return "Liste des bogues";
    }
trCallerGraph()
QCString TranslatorFrench::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1575 of file translator_fr.h.
    {
      return "Voici le graphe des appelants de cette fonction :";
    }
trCallGraph()
QCString TranslatorFrench::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1461 of file translator_fr.h.
    {
      return "Voici le graphe d'appel pour cette fonction :";
    }
trCiteReferences()
QCString TranslatorFrench::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1895 of file translator_fr.h.
    { return "Rfrences bibliographiques"; }
trClass()
QCString TranslatorFrench::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1262 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "classe", "s");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorFrench::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 581 of file translator_fr.h.
    {
      return "Graphe d'hritage de "+clName+":";
    }
trClassDocumentation()
QCString TranslatorFrench::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 462 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentation des structures de donnes";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentation des classes";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorFrench::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1162 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structures de donnes";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorFrench::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 241 of file translator_fr.h.
    { return "Hirarchie des classes"; }
trClassHierarchyDescription()
QCString TranslatorFrench::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 300 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Liste hirarchique de toutes les entits :";
      }
      else
      {
        return "Cette liste d'hritage est classe "
               "approximativement par ordre alphabtique :";
      }
    }
References Config_getBool.
trClassMethods()
QCString TranslatorFrench::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1980 of file translator_fr.h.
    {
      return "Mthodes de classe";
    }
trCode()
QCString TranslatorFrench::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 931 of file translator_fr.h.
    {
      return "code";
    }
trCollaborationDiagram()
QCString TranslatorFrench::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 886 of file translator_fr.h.
    {
      return "Graphe de collaboration de "+clName+":";
    }
trCompoundIndex()
QCString TranslatorFrench::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 435 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Index des structures de donnes";
      }
      else
      {
        return "Index des classes";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorFrench::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1629 of file translator_fr.h.
    { return "Index du type de donnes"; }
trCompoundList()
QCString TranslatorFrench::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 245 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structures de donnes";
      }
      else
      {
        return "Liste des classes";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorFrench::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 323 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Liste des structures de donnes avec une brve description :";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Liste des classes avec une brve description :";
      }
      else
      {
        return "Liste des classes, structures, "
               "unions et interfaces avec une brve description :";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorFrench::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1603 of file translator_fr.h.
    { return "Liste des types de donnes avec une brve description :"; }
trCompoundListFortran()
QCString TranslatorFrench::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1595 of file translator_fr.h.
    { return "Liste des types de donnes"; }
trCompoundMembers()
QCString TranslatorFrench::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 262 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Champs de donne";
      }
      else
      {
        return "Membres de classe";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorFrench::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 341 of file translator_fr.h.
    {
      QCString result="Liste de tous les ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="champs de structure et d'union ";
      }
      else
      {
        result+="membres de classe ";
      }
      if (!extractAll)
      {
        result+="documents ";
      }
      result+="avec des liens vers ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la documentation de structure/union de chaque champ :";
        }
        else
        {
          result+="la documentation de classe de chaque membre :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="les structures/unions auxquelles ils appartiennent :";
        }
        else
        {
          result+="les classes auxquelles ils appartiennent :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorFrench::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1607 of file translator_fr.h.
    {
      QCString result="Liste de tous les membres de types de donnes ";
      if (!extractAll)
      {
        result+="documents ";
      }
      result+="avec des liens vers ";
      if (!extractAll)
      {
         result+="la documentation de la structure des donnes de chaque membre :";
      }
      else
      {
         result+="les types des donnes auxquels ils appartiennent :";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorFrench::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1599 of file translator_fr.h.
    { return "Champs de donnes"; }
trCompoundReference()
QCString TranslatorFrench::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 656 of file translator_fr.h.
    {
      QCString result="Rfrence ";
      if (isTemplate) result+="du modle ";
      result+="de ";
      switch(compType)
      {
        case ClassDef::Class:      result+="la classe "; break;
        case ClassDef::Struct:     result+="la structure "; break;
        case ClassDef::Union:      result+="l'union "; break;
        case ClassDef::Interface:  result+="l'interface "; break;
        case ClassDef::Protocol:   result+="le protocol "; break;
        case ClassDef::Category:   result+="la catgorie "; break;
        case ClassDef::Exception:  result+="l'exception "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorFrench::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1670 of file translator_fr.h.
    {
      QCString result="Rference ";
      if (isTemplate) result+="du modle ";
      switch(compType)
      {
        case ClassDef::Class:      result+="du module "; break;
        case ClassDef::Struct:     result+="du type "; break;
        case ClassDef::Union:      result+="de l'union "; break;
        case ClassDef::Interface:  result+="de l'interface "; break;
        case ClassDef::Protocol:   result+="du protocole "; break;
        case ClassDef::Category:   result+="de la catgorie "; break;
        case ClassDef::Exception:  result+="de l'exception "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice()
QCString TranslatorFrench::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) inline override virtual
Implements Translator.
Definition at line 2269 of file translator_fr.h.
    {
      QCString result = "Rfrence ";
      bool feminine = true;
      switch(compType)
      {
        case ClassDef::Class:      result+="de la classe "; break;
        case ClassDef::Struct:     result+="de la structure "; break;
        case ClassDef::Union:      result+="de l'union "; break;
        case ClassDef::Interface:  result+="de l'interface "; break;
        case ClassDef::Protocol:   result+="du protocole "; feminine=false; break;
        case ClassDef::Category:   result+="de la catgorie "; break;
        case ClassDef::Exception:  result+="de l'exception "; break;
        default: break;
      }
      if(isLocal)
      {
        result += (feminine) ? "locale " : "local ";
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorFrench::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 557 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structures de donnes";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trConcept()
QCString TranslatorFrench::trConcept (bool first_capital, bool singular) inline override virtual
C++20 concept.
Implements Translator.
Definition at line 2324 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "concept", "s");
    }
References Translator::createNoun().
trConceptDefinition()
QCString TranslatorFrench::trConceptDefinition () inline override virtual
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2358 of file translator_fr.h.
    {
      return "Dfinition du concept";
    }
trConceptDocumentation()
QCString TranslatorFrench::trConceptDocumentation () inline override virtual
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2345 of file translator_fr.h.
    { return "Documentation des concepts"; }
trConceptIndex()
QCString TranslatorFrench::trConceptIndex () inline override virtual
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2341 of file translator_fr.h.
    { return "Index des concepts"; }
trConceptList()
QCString TranslatorFrench::trConceptList () inline override virtual
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2337 of file translator_fr.h.
    { return "Liste des concepts"; }
trConceptListDescription()
QCString TranslatorFrench::trConceptListDescription (bool extractAll) inline override virtual
used as an introduction to the concept list
Implements Translator.
Definition at line 2349 of file translator_fr.h.
    {
      QCString result="Liste de tous les concepts ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description :";
      return result;
    }
trConceptReference()
QCString TranslatorFrench::trConceptReference (const QCString & conceptName) inline override virtual
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2329 of file translator_fr.h.
    {
      QCString result="Reference du concept ";
      result+=conceptName;
      return result;
    }
trConstantDocumentation()
QCString TranslatorFrench::trConstantDocumentation () inline override virtual
Implements Translator.
Definition at line 2177 of file translator_fr.h.
    {
        return "Documentation des constantes";
    }
trConstantGroupReference()
QCString TranslatorFrench::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2017 of file translator_fr.h.
    {
      QCString result="Rfrence du groupe constant ";
      result+=namespaceName;
      return result;
    }
trConstantGroups()
QCString TranslatorFrench::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2013 of file translator_fr.h.
    { return "Groupes constants"; }
trConstants()
QCString TranslatorFrench::trConstants () inline override virtual
Implements Translator.
Definition at line 2173 of file translator_fr.h.
    {
        return "Constantes";
    }
trConstructorDocumentation()
QCString TranslatorFrench::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 896 of file translator_fr.h.
    {
      return "Documentation des constructeurs et destructeur";
    }
trCopyright()
QCString TranslatorFrench::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1899 of file translator_fr.h.
    { return "Copyright"; }
trCustomReference()
QCString TranslatorFrench::trCustomReference (const QCString & name) inline override virtual
Implements Translator.
Definition at line 2170 of file translator_fr.h.
    { return QCString("Rfrence ") + QCString(name); }
trDataMemberDocumentation()
QCString TranslatorFrench::trDataMemberDocumentation () inline override virtual
Implements Translator.
Definition at line 2306 of file translator_fr.h.
    {
        return "Documentation des champs de donnes";
    }
trDataMembers()
QCString TranslatorFrench::trDataMembers () inline override virtual
Implements Translator.
Definition at line 2302 of file translator_fr.h.
    {
        return "Champs de donnes";
    }
trDataTypes()
QCString TranslatorFrench::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1653 of file translator_fr.h.
    { return "Les types de donnes"; }
trDate()
QCString TranslatorFrench::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 595 of file translator_fr.h.
    { return "Date"; }
trDateTime()
QCString TranslatorFrench::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1848 of file translator_fr.h.
    {
      static const char *days[]   = { "Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche" };
      static const char *months[] = { "Janvier","Fvrier","Mars","Avril","Mai","Juin","Juillet","Aot","Septembre","Octobre","Novembre","Dcembre" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorFrench::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1868 of file translator_fr.h.
    {
      static const char *days_short[]   = { "lun.", "mar.", "mer.", "jeu.", "ven.", "sam.", "dim." };
      static const char *days_full[]    = { "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorFrench::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1884 of file translator_fr.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorFrench::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 863 of file translator_fr.h.
    {
      return "Dfinition  la ligne @0 du fichier @1.";
    }
trDefinedIn()
QCString TranslatorFrench::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 229 of file translator_fr.h.
    { return "dfini dans"; }
trDefinedInSourceFile()
QCString TranslatorFrench::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 867 of file translator_fr.h.
    {
      return "Dfinition dans le fichier @0.";
    }
trDefineDocumentation()
QCString TranslatorFrench::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 527 of file translator_fr.h.
    { return "Documentation des macros"; }
trDefines()
QCString TranslatorFrench::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 491 of file translator_fr.h.
    { return "Macros"; }
trDefineValue()
QCString TranslatorFrench::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1189 of file translator_fr.h.
    {
      return "Valeur :";
    }
trDeprecated()
QCString TranslatorFrench::trDeprecated () inline override virtual
Implements Translator.
Definition at line 876 of file translator_fr.h.
    {
      return "Obsolte";
    }
trDeprecatedList()
QCString TranslatorFrench::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1384 of file translator_fr.h.
    {
      return "Liste des lments obsoltes";
    }
trDesignUnitDocumentation()
QCString TranslatorFrench::trDesignUnitDocumentation () inline override virtual
VHDL design unit documentation.
Implements Translator.
Definition at line 2316 of file translator_fr.h.
    { return "Documentation de l'unit de conception"; }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorFrench::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Implements Translator.
Definition at line 2061 of file translator_fr.h.
    { return "Hirarchie des units de conception"; }
trDesignUnitIndex()
QCString TranslatorFrench::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Implements Translator.
Definition at line 2076 of file translator_fr.h.
    { return "Index des units de conception"; }
trDesignUnitList()
QCString TranslatorFrench::trDesignUnitList () inline override virtual
VHDL design unit list.
Implements Translator.
Definition at line 2064 of file translator_fr.h.
    { return "Liste des units de conception"; }
trDesignUnitListDescription()
QCString TranslatorFrench::trDesignUnitListDescription () inline override virtual
VHDL design unit list description.
Implements Translator.
Definition at line 2070 of file translator_fr.h.
    {
        return "Liste de tous les membres des units de conception avec liens vers "
            "les entits auxquelles ils appartiennent :";
    }
trDesignUnitMembers()
QCString TranslatorFrench::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Implements Translator.
Definition at line 2067 of file translator_fr.h.
    { return "Membres des units de conception"; }
trDesignUnits()
QCString TranslatorFrench::trDesignUnits () inline override virtual
VHDL design units.
Implements Translator.
Definition at line 2079 of file translator_fr.h.
    { return "Units de conception"; }
trDetailedDescription()
QCString TranslatorFrench::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 158 of file translator_fr.h.
    { return "Description dtaille"; }
trDetailLevel()
QCString TranslatorFrench::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1912 of file translator_fr.h.
    { return "Niveau de dtails"; }
trDetails()
QCString TranslatorFrench::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 162 of file translator_fr.h.
    { return "Dtails"; }
trDictionaries()
QCString TranslatorFrench::trDictionaries () inline override virtual
Implements Translator.
Definition at line 2189 of file translator_fr.h.
    {
        return "Dictionnaires";
    }
trDictionaryDocumentation()
QCString TranslatorFrench::trDictionaryDocumentation () inline override virtual
Implements Translator.
Definition at line 2193 of file translator_fr.h.
    {
        return "Documentation des dictionnaires";
    }
trDir()
QCString TranslatorFrench::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1551 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "rpertoire", "s");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorFrench::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1903 of file translator_fr.h.
    { return QCString("Graphe des dpendances de rpertoires pour ")+name+":"; }
trDirDocumentation()
QCString TranslatorFrench::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1533 of file translator_fr.h.
    { return "Documentation des rpertoires"; }
trDirectories()
QCString TranslatorFrench::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1539 of file translator_fr.h.
    { return "Rpertoires"; }
trDirIndex()
QCString TranslatorFrench::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1527 of file translator_fr.h.
    { return "Hirarchie de rpertoires"; }
trDirReference()
QCString TranslatorFrench::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1545 of file translator_fr.h.
    { QCString  result="Rpertoire de rfrence de "; result+=dirName; return result; }
trDirRelation()
QCString TranslatorFrench::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1787 of file translator_fr.h.
    {
      return "Relation " + QCString(name);
    }
trDocumentation()
QCString TranslatorFrench::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 417 of file translator_fr.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Documentation"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorFrench::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 503 of file translator_fr.h.
    { return "numrations"; }
trEnumerationTypeDocumentation()
QCString TranslatorFrench::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 539 of file translator_fr.h.
    { return "Documentation du type de l'numration"; }
trEnumerationValueDocumentation()
QCString TranslatorFrench::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1583 of file translator_fr.h.
    { return "Documentation des numrations"; }
trEnumerationValues()
QCString TranslatorFrench::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 521 of file translator_fr.h.
    { return "Valeurs numres"; }
trEnumGeneratedFromFiles()
QCString TranslatorFrench::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1924 of file translator_fr.h.
    { QCString result = "La documentation pour cette numration a t gnre  partir ";
      if (!single) result += "du fichier suivant"; else result += "des fichiers suivants";
      result+=" :";
      return result;
    }
trEnumName()
QCString TranslatorFrench::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 221 of file translator_fr.h.
    { return "numration"; }
trEnumReference()
QCString TranslatorFrench::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1932 of file translator_fr.h.
    { return QCString(name)+" Rfrence de l'numration"; }
trEnumValue()
QCString TranslatorFrench::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 225 of file translator_fr.h.
    { return "valeur numre"; }
trEventDocumentation()
QCString TranslatorFrench::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1401 of file translator_fr.h.
    {
      return "Documentation des vnements";
    }
trEvents()
QCString TranslatorFrench::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1396 of file translator_fr.h.
    {
      return "vnements";
    }
trExamples()
QCString TranslatorFrench::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 292 of file translator_fr.h.
    { return "Exemples"; }
trExamplesDescription()
QCString TranslatorFrench::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 405 of file translator_fr.h.
    { return "Liste de tous les exemples :"; }
trExceptionDocumentation()
QCString TranslatorFrench::trExceptionDocumentation () inline override virtual
Implements Translator.
Definition at line 2265 of file translator_fr.h.
    {
        return "Documentation des exceptions";
    }
trExceptionHierarchy()
QCString TranslatorFrench::trExceptionHierarchy () inline override virtual
Implements Translator.
Definition at line 2257 of file translator_fr.h.
    {
        return "Hirarchies des exceptions";
    }
trExceptionHierarchyDescription()
QCString TranslatorFrench::trExceptionHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2261 of file translator_fr.h.
    {
        return "Cette liste d'hritage est classe approximativement par ordre alphabtique :";
    }
trExceptionIndex()
QCString TranslatorFrench::trExceptionIndex () inline override virtual
Implements Translator.
Definition at line 2245 of file translator_fr.h.
    {
        return "Index des exceptions";
    }
trExceptionList()
QCString TranslatorFrench::trExceptionList () inline override virtual
Implements Translator.
Definition at line 2249 of file translator_fr.h.
    {
        return "Liste des exceptions";
    }
trExceptionListDescription()
QCString TranslatorFrench::trExceptionListDescription () inline override virtual
Implements Translator.
Definition at line 2253 of file translator_fr.h.
    {
        return "Liste des exceptions avec une brve description :";
    }
trExceptions()
QCString TranslatorFrench::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 611 of file translator_fr.h.
    { return "Exceptions"; }
trExtendsClass()
QCString TranslatorFrench::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1972 of file translator_fr.h.
    {
      return "Drive la classe @0.";
    }
trFile()
QCString TranslatorFrench::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1271 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "fichier", "s");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorFrench::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 481 of file translator_fr.h.
    { return "Documentation des fichiers"; }
trFileIn()
QCString TranslatorFrench::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1824 of file translator_fr.h.
    {
      return "Fichier dans "+name;
    }
trFileIndex()
QCString TranslatorFrench::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 450 of file translator_fr.h.
    { return "Index des fichiers"; }
trFileList()
QCString TranslatorFrench::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 258 of file translator_fr.h.
    { return "Liste des fichiers"; }
trFileListDescription()
QCString TranslatorFrench::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 314 of file translator_fr.h.
    {
      QCString result="Liste de tous les fichiers ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description :";
      return result;
    }
trFileMembers()
QCString TranslatorFrench::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 275 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Variables globale";
      }
      else
      {
        return "Membres de fichier";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorFrench::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 383 of file translator_fr.h.
    {
      QCString result="Liste ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="de toutes les fonctions, variables, macros, enumrations, et dfinitions de type ";
      }
      else
      {
        result+="de tous les membres de fichier ";
      }
      if (!extractAll) result+="documents ";
      result+="avec des liens vers ";
      if (extractAll)
        result+="les fichiers auxquels ils appartiennent :";
      else
        result+="la documentation :";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorFrench::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 679 of file translator_fr.h.
    {
      QCString result= "Rfrence du fichier ";
      result+=fileName;
      return result;
    }
trFriends()
QCString TranslatorFrench::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 638 of file translator_fr.h.
    { return "Amis"; }
trFunctionAndProc()
QCString TranslatorFrench::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Implements Translator.
Definition at line 2082 of file translator_fr.h.
    { return "Fonctions/Procdures/Processes"; }
trFunctionDocumentation()
QCString TranslatorFrench::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 545 of file translator_fr.h.
    { return "Documentation des fonctions"; }
trFunctions()
QCString TranslatorFrench::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 509 of file translator_fr.h.
    { return "Fonctions"; }
trGeneratedAt()
QCString TranslatorFrench::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 572 of file translator_fr.h.
    {
      QCString result="Gnr le "+date;
      if (!projName.isEmpty()) result+=" pour "+projName;
      result+=" par";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorFrench::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 213 of file translator_fr.h.
    { QCString result="Gnr automatiquement par Doxygen";
      if (!s.isEmpty()) result+=" pour "+s;
      result+="  partir du code source.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorFrench::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 615 of file translator_fr.h.
    { return "Gnr par"; }
trGeneratedFromFiles()
QCString TranslatorFrench::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 816 of file translator_fr.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      bool feminine = true;
      QCString result="La documentation de ";
      switch(compType)
      {
        case ClassDef::Class:      result+=vhdlOpt? "cette units de conception":"cette classe"; break;
        case ClassDef::Struct:     result+="cette structure"; break;
        case ClassDef::Union:      result+="cette union"; break;
        case ClassDef::Interface:  result+="cette interface"; break;
        case ClassDef::Protocol:   result+="ce protocol"; feminine = false; break;
        case ClassDef::Category:   result+="cette catgorie"; break;
        case ClassDef::Exception:  result+="cette exception"; break;
        default: break;
      }
      if (feminine) result+= " a t gnre  partir ";
      else result+=" a t gnr  partir ";
      if (single) result+="du fichier suivant :";
      else result+="des fichiers suivants :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorFrench::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1737 of file translator_fr.h.
    {
      // single is true implies a single file
      QCString result="La documentation de ";
      switch(compType)
      {
        case ClassDef::Class:      result+="ce module"; break;
        case ClassDef::Struct:     result+="ce type"; break;
        case ClassDef::Union:      result+="cette union"; break;
        case ClassDef::Interface:  result+="cette interface"; break;
        case ClassDef::Protocol:   result+="ce protocole"; break;
        case ClassDef::Category:   result+="cette catgorie"; break;
        case ClassDef::Exception:  result+="cette exception"; break;
        default: break;
      }
      result+=" a t gnre  partir ";
      if (single) result+="du fichier suivant :"; else result+="des fichiers suivants :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorFrench::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1318 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "globa", "ux(ales)", "l(e)");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorFrench::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1799 of file translator_fr.h.
    {
      return "Espace de nommage global";
    }
trGotoDocumentation()
QCString TranslatorFrench::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 906 of file translator_fr.h.
    {
      return "Aller  la documentation de ce fichier.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorFrench::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 939 of file translator_fr.h.
    {
      return "Aller au graphe hirarchique des classes";
    }
trGotoSourceCode()
QCString TranslatorFrench::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 901 of file translator_fr.h.
    {
      return "Aller au code source de ce fichier.";
    }
trGotoTextualHierarchy()
QCString TranslatorFrench::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 943 of file translator_fr.h.
    {
      return "Aller  la hirarchie des classes en mode texte";
    }
trGraphicalHierarchy()
QCString TranslatorFrench::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 935 of file translator_fr.h.
    {
      return "Graphe hirarchique des classes";
    }
trGroup()
QCString TranslatorFrench::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1291 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "groupe", "s");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorFrench::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 429 of file translator_fr.h.
    { return "Index hirarchique"; }
trImplementedFromList()
QCString TranslatorFrench::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1352 of file translator_fr.h.
    {
      return "Implmente "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorFrench::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1360 of file translator_fr.h.
    {
      return "Implment dans "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorFrench::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 1035 of file translator_fr.h.
    {
      return "Ce graphe montre quels fichiers incluent directement "
             "ou indirectement ce fichier :";
    }
trInclDepGraph()
QCString TranslatorFrench::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 891 of file translator_fr.h.
    {
      return "Graphe des dpendances par inclusion de "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorFrench::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1833 of file translator_fr.h.
    {
      return "Inclut le fichier dans "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorFrench::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 207 of file translator_fr.h.
    { return ", y compris les membres hrits :"; }
trInheritedByList()
QCString TranslatorFrench::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 750 of file translator_fr.h.
    {
      return "Drive par "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorFrench::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1936 of file translator_fr.h.
    { return QCString(members)+" hrits de "+what; }
trInheritsList()
QCString TranslatorFrench::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 742 of file translator_fr.h.
    {
      return "Est drive de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorFrench::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 926 of file translator_fr.h.
    {
      return "Valeur initiale :";
    }
trInstanceMethods()
QCString TranslatorFrench::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1988 of file translator_fr.h.
    {
      return "Mthodes d'instance";
    }
trInterfaceDocumentation()
QCString TranslatorFrench::trInterfaceDocumentation () inline override virtual
Implements Translator.
Definition at line 2221 of file translator_fr.h.
    {
        return "Documentation des interfaces";
    }
trInterfaceHierarchy()
QCString TranslatorFrench::trInterfaceHierarchy () inline override virtual
Implements Translator.
Definition at line 2213 of file translator_fr.h.
    {
        return "Hirarchies des interfaces";
    }
trInterfaceHierarchyDescription()
QCString TranslatorFrench::trInterfaceHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2217 of file translator_fr.h.
    {
        return "Cette liste d'hritage est classe approximativement par ordre alphabtique :";
    }
trInterfaceIndex()
QCString TranslatorFrench::trInterfaceIndex () inline override virtual
Implements Translator.
Definition at line 2201 of file translator_fr.h.
    {
        return "Index des interfaces";
    }
trInterfaceList()
QCString TranslatorFrench::trInterfaceList () inline override virtual
Implements Translator.
Definition at line 2205 of file translator_fr.h.
    {
        return "Liste des interfaces";
    }
trInterfaceListDescription()
QCString TranslatorFrench::trInterfaceListDescription () inline override virtual
Implements Translator.
Definition at line 2209 of file translator_fr.h.
    {
        return "Liste des interfaces avec une brve description :";
    }
trInterfaces()
QCString TranslatorFrench::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2005 of file translator_fr.h.
    { return "Interfaces exportes"; }
trInvariant()
QCString TranslatorFrench::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 921 of file translator_fr.h.
    {
      return "Invariant";
    }
trISOLang()
QCString TranslatorFrench::trISOLang () inline override virtual
Implements Translator.
Definition at line 138 of file translator_fr.h.
    {
      return "fr";
    }
trLegend()
QCString TranslatorFrench::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1122 of file translator_fr.h.
    {
      return "lgende";
    }
trLegendDocs()
QCString TranslatorFrench::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1057 of file translator_fr.h.
    {
      return
        "Cette page explique comment interprter les graphes gnrs "
        "par doxygen.<p>\n"
        "Considrez l'exemple suivant :\n"
        "\\code\n"
        "/*! Classe invisible  cause d'une troncature */\n"
        "class Invisible { };\n\n"
        "/*! Classe tronque, la relation d'hritage est masque */\n"
        "class Truncated : public Invisible { };\n\n"
        "/*! Classe non documente avec des commentaires Doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe drive par hritage public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Un modle de classe */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe drive par hritage protg */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe drive par hritage priv */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe utilise par la classe drive */\n"
        "class Used { };\n\n"
        "/*! Super-classe qui hrite de plusieurs autres classes */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Cela aboutira au graphe suivant :"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Les rectangles du graphe ci-dessus ont la signification suivante :\n"
        "</p>\n"
        "<ul>\n"
        "<li>Un rectangle plein noir reprsente la structure ou la classe pour laquelle "
        "le graphe est gnr.\n"
        "<li>Un rectangle avec un bord noir indique une classe ou une structure documente.\n"
        "<li>Un rectangle avec un bord gris indique une classe ou une structure non documente.\n"
        "<li>Un rectangle avec un bord rouge indique une structure ou une classe documente\n"
        "pour laquelle des relations d'hritage ou de collaboration manquent. Un graphe est "
        "tronqu s'il n'entre pas dans les limites spcifies."
        "</ul>\n"
        "<p>\n"
        "Les flches ont la signification suivante :\n"
        "</p>\n"
        "<ul>\n"
        "<li>Une bleu fonc est utilise pour visualiser une relation d'hritage publique "
        "entre deux classes.\n"
        "<li>Une flche vert fonc est utilise pour une relation d'hritage protge.\n"
        "<li>Une flche rouge fonc est utilise pour une relation d'hritage prive.\n"
        "<li>Une flche violette en pointills est utilise si une classe est contenue ou "
        "utilise par une autre classe. La flche est tiquete avec la ou les variable(s) "
        "qui permettent d'accder  la classe ou structure pointe. \n"
        "<li>Une flche jaune en pointills indique une relation entre un modle d'instance et "
        "le modle de classe duquel il est instanci. La flche est tiquete avec "
        "les paramtres de modle de l'instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorFrench::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 1050 of file translator_fr.h.
    {
      return "Lgende du graphe";
    }
trListOfAllMembers()
QCString TranslatorFrench::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 195 of file translator_fr.h.
    { return "Liste de tous les membres"; }
trLoading()
QCString TranslatorFrench::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1793 of file translator_fr.h.
    {
      return "Chargement...";
    }
trMainPage()
QCString TranslatorFrench::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 850 of file translator_fr.h.
    { return "Page principale"; }
trMember()
QCString TranslatorFrench::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1309 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "membre", "s");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorFrench::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 178 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentation des champs";
      }
      else
      {
        return "Documentation des donnes membres";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorFrench::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 170 of file translator_fr.h.
    { return "Documentation des numrations membres"; }
trMemberFunctionDocumentation()
QCString TranslatorFrench::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 174 of file translator_fr.h.
    { return "Documentation des fonctions membres"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorFrench::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1591 of file translator_fr.h.
    { return "Documentation des fonctions/subroutines membres"; }
trMemberList()
QCString TranslatorFrench::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 199 of file translator_fr.h.
    { return "Liste des membres"; }
trMemberTypedefDocumentation()
QCString TranslatorFrench::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 166 of file translator_fr.h.
    { return "Documentation des dfinitions de type membres"; }
trMethodDocumentation()
QCString TranslatorFrench::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1995 of file translator_fr.h.
    {
      return "Documentation des mthodes";
    }
trModule()
QCString TranslatorFrench::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1729 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "module", "s");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorFrench::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 456 of file translator_fr.h.
    { return "Documentation des modules"; }
trModuleIndex()
QCString TranslatorFrench::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 423 of file translator_fr.h.
    { return "Index des modules"; }
trModuleReference()
QCString TranslatorFrench::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1691 of file translator_fr.h.
    {
      QCString result="Rfrence du module ";
      result+= namespaceName;
      return result;
    }
trModules()
QCString TranslatorFrench::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 237 of file translator_fr.h.
    { return "Modules"; }
trModulesDescription()
QCString TranslatorFrench::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 413 of file translator_fr.h.
    { return "Liste de tous les modules :"; }
trModulesIndex()
QCString TranslatorFrench::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1722 of file translator_fr.h.
    { return "Index des modules"; }
trModulesList()
QCString TranslatorFrench::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1657 of file translator_fr.h.
    { return "Liste des modules"; }
trModulesListDescription()
QCString TranslatorFrench::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1661 of file translator_fr.h.
    {
      QCString result="Liste de tous les modules ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description :";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorFrench::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1703 of file translator_fr.h.
    {
      QCString result="Liste de tous les membres ";
      if (!extractAll) result+="documents ";
      result+="du module avec des liens vers ";
      if (extractAll)
      {
        result+="la documentation du module de chaque membre :";
      }
      else
      {
        result+="les modules auxquels ils appartiennent :";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorFrench::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1699 of file translator_fr.h.
    { return "Membres du module"; }
trMonth()
QCString TranslatorFrench::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1876 of file translator_fr.h.
    {
      static const char *months_short[] = { "janv.", "fvr.", "mars", "avr.", "mai", "juin", "juil.", "aot", "sept.", "oct.", "nov.", "dc." };
      static const char *months_full[]  = { "janvier", "fvrier", "mars", "avril", "mai", "juin", "juillet", "aot", "septembre", "octobre", "novembre", "dcembre" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorFrench::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 191 of file translator_fr.h.
    { return "Plus de dtails..."; }
trNamespace()
QCString TranslatorFrench::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1280 of file translator_fr.h.
    {
      QCString result = createNoun(first_capital, singular, "espace", "s");
      result+=" de nommage";
      return result;
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorFrench::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 796 of file translator_fr.h.
    { return "Documentation des espaces de nommage"; }
trNamespaceIndex()
QCString TranslatorFrench::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 790 of file translator_fr.h.
    { return "Index des espaces de nommage"; }
trNamespaceList()
QCString TranslatorFrench::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 623 of file translator_fr.h.
    { return "Liste des espaces de nommage"; }
trNamespaceListDescription()
QCString TranslatorFrench::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 627 of file translator_fr.h.
    {
      QCString result="Liste de tous les espaces de nommage ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorFrench::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 776 of file translator_fr.h.
    {
      QCString result="Liste de tous les membres des espaces de nommage ";
      if (!extractAll) result+="documents ";
        result+="avec des liens vers ";
      if (extractAll)
        result+="la documentation de namespace de chaque membre :";
      else
        result+="les espaces de nommage auxquels ils appartiennent :";
      return result;
    }
trNamespaceMembers()
QCString TranslatorFrench::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 772 of file translator_fr.h.
    { return "Membres de l'espace de nommage"; }
trNamespaceReference()
QCString TranslatorFrench::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 687 of file translator_fr.h.
    {
      QCString result= "Rfrence de l'espace de nommage ";
      result+=namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorFrench::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 806 of file translator_fr.h.
    { return "Espaces de nommage"; }
trNoMatches()
QCString TranslatorFrench::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1811 of file translator_fr.h.
    {
      return "Aucune correspondance";
    }
trNote()
QCString TranslatorFrench::trNote () inline override virtual
Implements Translator.
Definition at line 956 of file translator_fr.h.
    {
      return "Note";
    }
trOperationDocumentation()
QCString TranslatorFrench::trOperationDocumentation () inline override virtual
Implements Translator.
Definition at line 2298 of file translator_fr.h.
    {
        return "Documentation des oprations";
    }
trOperations()
QCString TranslatorFrench::trOperations () inline override virtual
Implements Translator.
Definition at line 2294 of file translator_fr.h.
    {
        return "Oprations";
    }
trOverloadText()
QCString TranslatorFrench::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1563 of file translator_fr.h.
    {
       return "Ceci est une fonction membre surcharge, "
              "propose par commodit. Elle diffre de la fonction "
              "ci-dessus uniquement par le(s) argument(s) qu'elle accepte.";
    }
trPackage()
QCString TranslatorFrench::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1174 of file translator_fr.h.
    {
      return "Paquetage "+name;
    }
trPackageAttribs()
QCString TranslatorFrench::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1437 of file translator_fr.h.
    {
      return "Attributs de paquetage";
    }
trPackageFunctions()
QCString TranslatorFrench::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1419 of file translator_fr.h.
    {
      return "Fonctions de paquetage";
    }
trPackageList()
QCString TranslatorFrench::trPackageList () inline override virtual
Implements Translator.
Definition at line 2367 of file translator_fr.h.
    { return "Liste des paquetages"; }
trPackageListDescription()
QCString TranslatorFrench::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1179 of file translator_fr.h.
    {
      return "Liste des paquetages avec une brve description (si disponible) :";
    }
trPackageMembers()
QCString TranslatorFrench::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1423 of file translator_fr.h.
    {
      return "Membres de paquetage";
    }
trPackages()
QCString TranslatorFrench::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1184 of file translator_fr.h.
    {
      return "Paquetages";
    }
trPackageTypes()
QCString TranslatorFrench::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1412 of file translator_fr.h.
    {
      return "Types de paquetage";
    }
trPage()
QCString TranslatorFrench::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1300 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "page", "s");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorFrench::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 856 of file translator_fr.h.
    { return "p."; }
trPageIndex()
QCString TranslatorFrench::trPageIndex () inline override virtual
Implements Translator.
Definition at line 947 of file translator_fr.h.
    {
      return "Index des pages";
    }
trPanelSynchronisationTooltip()
QCString TranslatorFrench::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1953 of file translator_fr.h.
    {
      QCString opt = enable ? "activer" : "dsactiver";
      return "cliquez pour "+opt+" la synchronisation du panel";
    }
trParameters()
QCString TranslatorFrench::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 607 of file translator_fr.h.
    { return "Paramtres"; }
trPostcondition()
QCString TranslatorFrench::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 916 of file translator_fr.h.
    {
      return "Postcondition";
    }
trPrecondition()
QCString TranslatorFrench::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 911 of file translator_fr.h.
    {
      return "Prcondition";
    }
trPrivateAttribs()
QCString TranslatorFrench::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 995 of file translator_fr.h.
    {
      return "Attributs privs";
    }
trPrivateMembers()
QCString TranslatorFrench::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 708 of file translator_fr.h.
    { return "Fonctions membres prives"; }
trPrivateSlots()
QCString TranslatorFrench::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 710 of file translator_fr.h.
    { return "Connecteurs privs"; }
trPrivateTypes()
QCString TranslatorFrench::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 991 of file translator_fr.h.
    {
      return "Types privs";
    }
trProperties()
QCString TranslatorFrench::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1147 of file translator_fr.h.
    {
      return "Proprits";
    }
trPropertyDocumentation()
QCString TranslatorFrench::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1152 of file translator_fr.h.
    {
      return "Documentation des proprits";
    }
trProtectedAttribs()
QCString TranslatorFrench::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 983 of file translator_fr.h.
    {
      return "Attributs protgs";
    }
trProtectedMembers()
QCString TranslatorFrench::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 702 of file translator_fr.h.
    { return "Fonctions membres protges"; }
trProtectedSlots()
QCString TranslatorFrench::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 704 of file translator_fr.h.
    { return "Connecteurs protgs"; }
trProtectedTypes()
QCString TranslatorFrench::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 979 of file translator_fr.h.
    {
      return "Types protgs";
    }
trProvidedByCategory()
QCString TranslatorFrench::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1963 of file translator_fr.h.
    {
      return "Dclare dans la catgorie @0.";
    }
trPublicAttribs()
QCString TranslatorFrench::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 964 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Champs de donnes";
      }
      else
      {
        return "Attributs publics";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorFrench::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 694 of file translator_fr.h.
    { return "Fonctions membres publiques"; }
trPublicSlots()
QCString TranslatorFrench::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 696 of file translator_fr.h.
    { return "Connecteurs publics"; }
trPublicTypes()
QCString TranslatorFrench::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 960 of file translator_fr.h.
    {
      return "Types publics";
    }
trReferencedBy()
QCString TranslatorFrench::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 1023 of file translator_fr.h.
    {
      return "Rfrenc par";
    }
trReferenceManual()
QCString TranslatorFrench::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 485 of file translator_fr.h.
    { return "Manuel de rfrence"; }
trReferences()
QCString TranslatorFrench::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1340 of file translator_fr.h.
    {
      return "Rfrences";
    }
trReimplementedFromList()
QCString TranslatorFrench::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 758 of file translator_fr.h.
    {
      return "Rimplmente  partir de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorFrench::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 766 of file translator_fr.h.
    {
      return "Rimplmente dans "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorFrench::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 648 of file translator_fr.h.
    { return "Documentation des fonctions amies et associes"; }
trRelatedFunctions()
QCString TranslatorFrench::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 150 of file translator_fr.h.
    { return "Fonctions associes"; }
trRelatedPages()
QCString TranslatorFrench::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 288 of file translator_fr.h.
    { return "Pages associes"; }
trRelatedPagesDescription()
QCString TranslatorFrench::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 409 of file translator_fr.h.
    { return "Liste de toutes les pages de documentation associes :"; }
trRelatedSubscript()
QCString TranslatorFrench::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 154 of file translator_fr.h.
    { return "(Notez que ce ne sont pas des fonctions membres)"; }
trRemarks()
QCString TranslatorFrench::trRemarks () inline override virtual
Implements Translator.
Definition at line 1027 of file translator_fr.h.
    {
      return "Remarques";
    }
trReturns()
QCString TranslatorFrench::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 599 of file translator_fr.h.
    { return "Renvoie"; }
trReturnValues()
QCString TranslatorFrench::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 845 of file translator_fr.h.
    { return "Valeurs retournes"; }
trRTFansicp()
QCString TranslatorFrench::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1238 of file translator_fr.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorFrench::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1247 of file translator_fr.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorFrench::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1253 of file translator_fr.h.
    {
      return "Index";
    }
trRTFTableOfContents()
QCString TranslatorFrench::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1372 of file translator_fr.h.
    {
      return "Table des matires";
    }
trSearch()
QCString TranslatorFrench::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 296 of file translator_fr.h.
    { return "Recherche"; }
trSearching()
QCString TranslatorFrench::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1805 of file translator_fr.h.
    {
      return "Recherche...";
    }
trSearchMatches()
QCString TranslatorFrench::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1504 of file translator_fr.h.
    {
      return "Correspondances :";
    }
trSearchResults()
QCString TranslatorFrench::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1485 of file translator_fr.h.
    {
      if (numDocuments==0)
      {
        return "Dsol, aucun document ne correspond  votre requte.";
      }
      else if (numDocuments==1)
      {
        return "Trouv <b>1</b> document correspondant  votre requte.";
      }
      else
      {
        return "Trouv  <b>$num</b> documents correspondant  votre requte. "
               "Class par ordre de pertinence dcroissant.";
      }
    }
trSearchResultsTitle()
QCString TranslatorFrench::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1473 of file translator_fr.h.
    {
      return "Rsultats de la recherche";
    }
trSeeAlso()
QCString TranslatorFrench::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 603 of file translator_fr.h.
    { return "Voir galement"; }
trSequenceDocumentation()
QCString TranslatorFrench::trSequenceDocumentation () inline override virtual
Implements Translator.
Definition at line 2185 of file translator_fr.h.
    {
        return "Documentation des squences";
    }
trSequences()
QCString TranslatorFrench::trSequences () inline override virtual
Implements Translator.
Definition at line 2181 of file translator_fr.h.
    {
        return "Squences";
    }
trServiceGeneratedFromFiles()
QCString TranslatorFrench::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 2038 of file translator_fr.h.
    {
      // single is true implies a single file
      QCString result="La documentation pour ce service "
                                "a t gnre par ";
      if (single) result+="le fichier suivant :"; else result+="les fichiers suivants :";
      return result;
    }
trServiceReference()
QCString TranslatorFrench::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 2024 of file translator_fr.h.
    {
      QCString result="Rfrence du service ";
      result+=sName;
      return result;
    }
trServices()
QCString TranslatorFrench::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2009 of file translator_fr.h.
    { return "Services inclus"; }
trSignals()
QCString TranslatorFrench::trSignals () inline override virtual
Implements Translator.
Definition at line 698 of file translator_fr.h.
    { return "Signaux"; }
trSince()
QCString TranslatorFrench::trSince () inline override virtual
Implements Translator.
Definition at line 1040 of file translator_fr.h.
    {
      return "Depuis";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorFrench::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 2047 of file translator_fr.h.
    {
      // single is true implies a single file
      QCString result="La documentation pour ce singleton "
                                "a t gnre par ";
      if (single) result+="le fichier suivant :"; else result+="les fichiers suivants :";
      return result;
    }
trSingletonReference()
QCString TranslatorFrench::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 2031 of file translator_fr.h.
    {
      QCString result="Rfrence du singleton ";
      result+=sName;
      return result;
    }
trSliceInterfaces()
QCString TranslatorFrench::trSliceInterfaces () inline override virtual
Implements Translator.
Definition at line 2197 of file translator_fr.h.
    {
        return "Interfaces";
    }
trSourceFile()
QCString TranslatorFrench::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1515 of file translator_fr.h.
    {
      return " Fichier source de " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorFrench::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1444 of file translator_fr.h.
    {
      return "Attributs statiques de paquetage";
    }
trStaticPackageFunctions()
QCString TranslatorFrench::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1430 of file translator_fr.h.
    {
      return "Fonctions statiques de paquetage";
    }
trStaticPrivateAttribs()
QCString TranslatorFrench::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 999 of file translator_fr.h.
    {
      return "Attributs privs statiques";
    }
trStaticPrivateMembers()
QCString TranslatorFrench::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 712 of file translator_fr.h.
    { return "Fonctions membres prives statiques"; }
trStaticProtectedAttribs()
QCString TranslatorFrench::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 987 of file translator_fr.h.
    {
      return "Attributs protgs statiques";
    }
trStaticProtectedMembers()
QCString TranslatorFrench::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 706 of file translator_fr.h.
    { return "Fonctions membres protges statiques"; }
trStaticPublicAttribs()
QCString TranslatorFrench::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 975 of file translator_fr.h.
    {
      return "Attributs publics statiques";
    }
trStaticPublicMembers()
QCString TranslatorFrench::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 700 of file translator_fr.h.
    { return "Fonctions membres publiques statiques"; }
trStructDocumentation()
QCString TranslatorFrench::trStructDocumentation () inline override virtual
Implements Translator.
Definition at line 2241 of file translator_fr.h.
    {
        return "Documentation des structures";
    }
trStructIndex()
QCString TranslatorFrench::trStructIndex () inline override virtual
Implements Translator.
Definition at line 2229 of file translator_fr.h.
    {
        return "Index des structures";
    }
trStructList()
QCString TranslatorFrench::trStructList () inline override virtual
Implements Translator.
Definition at line 2233 of file translator_fr.h.
    {
        return "Liste des structures";
    }
trStructListDescription()
QCString TranslatorFrench::trStructListDescription () inline override virtual
Implements Translator.
Definition at line 2237 of file translator_fr.h.
    {
        return "Liste des structures avec une brve description :";
    }
trStructs()
QCString TranslatorFrench::trStructs () inline override virtual
Implements Translator.
Definition at line 2225 of file translator_fr.h.
    {
        return "Structures";
    }
trSubprogram()
QCString TranslatorFrench::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1771 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "sous-programme", "s");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorFrench::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1647 of file translator_fr.h.
    { return "Documentation de la fonction/subroutine"; }
trSubprograms()
QCString TranslatorFrench::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1641 of file translator_fr.h.
    { return "Fonctions/Subroutines"; }
trTemplateParameters()
QCString TranslatorFrench::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1916 of file translator_fr.h.
    { return "Paramtres du template"; }
trTest()
QCString TranslatorFrench::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1132 of file translator_fr.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorFrench::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1137 of file translator_fr.h.
    {
      return "Liste des tests";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorFrench::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 203 of file translator_fr.h.
    { return "Liste complte des membres de"; }
trTodo()
QCString TranslatorFrench::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1009 of file translator_fr.h.
    {
      return "A faire";
    }
trTodoList()
QCString TranslatorFrench::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 1014 of file translator_fr.h.
    {
      return "Liste des choses  faire";
    }
trType()
QCString TranslatorFrench::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1762 of file translator_fr.h.
    {
      return createNoun(first_capital, singular, "type", "s");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorFrench::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1777 of file translator_fr.h.
    {
      return "Contraintes de type";
    }
trTypedefDocumentation()
QCString TranslatorFrench::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 533 of file translator_fr.h.
    { return "Documentation des dfinitions de type"; }
trTypedefs()
QCString TranslatorFrench::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 497 of file translator_fr.h.
    { return "Dfinitions de type"; }
trTypeDocumentation()
QCString TranslatorFrench::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1635 of file translator_fr.h.
    { return "Documentation du type de donnes"; }
trVariableDocumentation()
QCString TranslatorFrench::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 551 of file translator_fr.h.
    { return "Documentation des variables"; }
trVariables()
QCString TranslatorFrench::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 515 of file translator_fr.h.
    { return "Variables"; }
trVersion()
QCString TranslatorFrench::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 591 of file translator_fr.h.
    { return "Version"; }
trVhdlType()
QCString TranslatorFrench::trVhdlType (VhdlSpecifier type, bool single) inline override virtual
VHDL type.
Implements Translator.
Definition at line 2085 of file translator_fr.h.
    {
      switch(type)
      {
        case VhdlSpecifier::LIBRARY:
          if (single) return "Librairie";
          else        return "Librairies";
        case VhdlSpecifier::PACKAGE:
          if (single) return "Paquetage";
          else        return "Paquetages";
        case VhdlSpecifier::SIGNAL:
          if (single) return "Signal";
          else        return "Signaux";
        case VhdlSpecifier::COMPONENT:
          if (single) return "Composant";
          else        return "Composants";
        case VhdlSpecifier::CONSTANT:
          if (single) return "Constante";
          else        return "Constantes";
        case VhdlSpecifier::ENTITY:
          if (single) return "Entit";
          else        return "Entits";
        case VhdlSpecifier::TYPE:
          if (single) return "Type";
          else        return "Types";
        case VhdlSpecifier::SUBTYPE:
          if (single) return "Sous-type";
          else        return "Sous-types";
        case VhdlSpecifier::FUNCTION:
          if (single) return "Fonction";
          else        return "Fonctions";
        case VhdlSpecifier::RECORD:
          if (single) return "Enregistrement";
          else        return "Enregistrements";
        case VhdlSpecifier::PROCEDURE:
          if (single) return "Procdure";
          else        return "Procdures";
        case VhdlSpecifier::ARCHITECTURE:
          if (single) return "Architecture";
          else        return "Architectures";
        case VhdlSpecifier::ATTRIBUTE:
          if (single) return "Attribut";
          else        return "Attributs";
        case VhdlSpecifier::PROCESS:
          if (single) return "Process";
          else        return "Processes";
        case VhdlSpecifier::PORT:
          if (single) return "Port";
          else        return "Ports";
        case VhdlSpecifier::USE:
          if (single) return "Clause d'utilisation";
          else        return "Clauses d'utilisation";
        case VhdlSpecifier::GENERIC:
          if (single) return "Generique";
          else        return "Generiques";
        case VhdlSpecifier::PACKAGE_BODY:
          return "Corps du paquetage";
        case VhdlSpecifier::UNITS:
          return "Units";
        case VhdlSpecifier::SHAREDVARIABLE:
          if (single) return "Variable partage";
          else        return "Variables partages";
        case VhdlSpecifier::VFILE:
          if (single) return "Fichier";
          else        return "Fichiers";
        case VhdlSpecifier::GROUP:
          if (single) return "Groupe";
          else        return "Groupes";
        case VhdlSpecifier::INSTANTIATION:
          if (single) return "Instanciation";
          else        return "Instanciations";
        case VhdlSpecifier::ALIAS:
          if (single) return "Alias";
          else        return "Alias";
        case VhdlSpecifier::CONFIG:
          if (single) return "Configuration";
          else        return "Configurations";
        case VhdlSpecifier::MISCELLANEOUS:
          return "Divers";
        case VhdlSpecifier::UCF_CONST:
          return "Contraintes";
        default:
          return "Classe";
      }
    }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorFrench::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 587 of file translator_fr.h.
    { return "Avertissement"; }
trWriteList()
QCString TranslatorFrench::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 718 of file translator_fr.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=", et ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_fr.h