Doxygen: DocSecRefItem Class Reference
DocSecRefItem Class Reference
Node representing a reference to a section.
#include <src/docnode.h>
Public Member Functions
DocSecRefItem (DocParser *parser, DocNodeVariant *parent, const QCString &target)
QCString target () const
QCString file () const
QCString anchor () const
QCString relPath () const
QCString ref () const
bool refToTable () const
bool isSubPage () const
void parse ()
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
QCString m_target
RefType m_refType = Unknown
bool m_isSubPage = false
QCString m_file
QCString m_relPath
QCString m_ref
QCString m_anchor
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a reference to a section.
Definition at line 913 of file docnode.h.
Constructor & Destructor Documentation
DocSecRefItem()
DocSecRefItem::DocSecRefItem (DocParser * parser, DocNodeVariant * parent, const QCString & target)
Definition at line 532 of file docnode.cpp.
                                                                                            :
      DocCompoundNode(parser,parent), m_target(target), m_relPath(parser->context.relPath)
{
}
References DocCompoundNode::DocCompoundNode(), m_relPath, m_target, DocNode::parent(), DocNode::parser(), relPath(), and target().
Member Function Documentation
anchor()
QCString DocSecRefItem::anchor () const inline
Definition at line 919 of file docnode.h.
{ return m_anchor; }
References m_anchor.
Referenced by HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), and XmlDocVisitor::operator()().
file()
QCString DocSecRefItem::file () const inline
Definition at line 918 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), and XmlDocVisitor::operator()().
isSubPage()
bool DocSecRefItem::isSubPage () const inline
Definition at line 923 of file docnode.h.
{ return m_isSubPage; }
References m_isSubPage.
Referenced by HtmlDocVisitor::operator()(), and LatexDocVisitor::operator()().
parse()
void DocSecRefItem::parse ()
Definition at line 537 of file docnode.cpp.
{
  AUTO_TRACE();
  auto ns = AutoNodeStack(parser(),thisVariant());
  parser()->tokenizer.setStateTitle();
  Token tok = parser()->tokenizer.lex();
  while (!tok.is_any_of(TokenRetval::TK_NONE, TokenRetval::TK_EOF))
  {
    if (!parser()->defaultHandleToken(thisVariant(),tok,children()))
    {
      parser()->errorHandleDefaultToken(thisVariant(),tok,children(),"\\refitem");
    }
    tok = parser()->tokenizer.lex();
  }
  parser()->tokenizer.setStatePara();
  parser()->handlePendingStyleCommands(thisVariant(),children());
  if (!m_target.isEmpty())
  {
    const SectionInfo *sec = SectionManager::instance().find(m_target);
    if (sec==nullptr && parser()->context.lang==SrcLangExt::Markdown) // lookup as markdown file
    {
      sec = SectionManager::instance().find(markdownFileNameToId(m_target));
    }
    if (sec) // ref to section or anchor
    {
      // set defaults
      m_ref       = sec->ref();
      m_file      = stripKnownExtensions(sec->fileName());
      m_refType   = Section;
      m_anchor    = sec->label();
      m_isSubPage = false;
      // adjust if needed
      switch (sec->type().level())
      {
        case SectionType::Page:
          {
            PageDef *pd = Doxygen::pageLinkedMap->find(m_target);
            m_isSubPage = pd && pd->hasParentPage();
            if (!m_isSubPage)
            {
              m_anchor="";
            }
          }
          break;
        case SectionType::Anchor:
          m_refType = Anchor;
          break;
        case SectionType::Table:
          m_refType = Table;
          break;
        default:
          break;
      }
      //printf("m_ref=%s,m_file=%s,type=%d\n",
      //    qPrint(m_ref),qPrint(m_file),m_refType);
    }
    else
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"reference to unknown section %s",
          qPrint(m_target));
    }
  }
  else
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"reference to empty target");
  }
}
References DocNode::Anchor, SectionType::Anchor, AUTO_TRACE, DocCompoundNode::children(), DocParser::errorHandleDefaultToken(), SectionInfo::fileName(), LinkedMap< T, Hash, KeyEqual, Map >::find(), DocParser::handlePendingStyleCommands(), PageDef::hasParentPage(), SectionManager::instance(), Token::is_any_of(), SectionInfo::label(), SectionType::level(), DocTokenizer::lex(), m_anchor, m_file, m_isSubPage, m_ref, m_refType, m_target, Markdown, markdownFileNameToId(), SectionType::Page, Doxygen::pageLinkedMap, DocNode::parser(), qPrint(), SectionInfo::ref(), DocNode::Section, DocTokenizer::setStatePara(), DocTokenizer::setStateTitle(), stripKnownExtensions(), DocNode::Table, SectionType::Table, DocNode::thisVariant(), DocParser::tokenizer, SectionInfo::type(), and warn_doc_error.
ref()
QCString DocSecRefItem::ref () const inline
Definition at line 921 of file docnode.h.
{ return m_ref; }
References m_ref.
Referenced by HtmlDocVisitor::operator()(), and LatexDocVisitor::operator()().
refToTable()
bool DocSecRefItem::refToTable () const inline
Definition at line 922 of file docnode.h.
{ return m_refType==Table; }
References m_refType, and DocNode::Table.
Referenced by LatexDocVisitor::operator()().
relPath()
QCString DocSecRefItem::relPath () const inline
Definition at line 920 of file docnode.h.
{ return m_relPath; }
References m_relPath.
Referenced by DocSecRefItem(), and HtmlDocVisitor::operator()().
target()
QCString DocSecRefItem::target () const inline
Definition at line 917 of file docnode.h.
{ return m_target; }
References m_target.
Referenced by DocSecRefItem(), and PrintDocVisitor::operator()().
Member Data Documentation
m_anchor
QCString DocSecRefItem::m_anchor private
Definition at line 933 of file docnode.h.
Referenced by anchor(), and parse().
m_file
QCString DocSecRefItem::m_file private
Definition at line 930 of file docnode.h.
Referenced by file(), and parse().
m_isSubPage
bool DocSecRefItem::m_isSubPage = false private
Definition at line 929 of file docnode.h.
Referenced by isSubPage(), and parse().
m_ref
QCString DocSecRefItem::m_ref private
Definition at line 932 of file docnode.h.
Referenced by parse(), and ref().
m_refType
RefType DocSecRefItem::m_refType = Unknown private
Definition at line 928 of file docnode.h.
Referenced by parse(), and refToTable().
m_relPath
QCString DocSecRefItem::m_relPath private
Definition at line 931 of file docnode.h.
Referenced by DocSecRefItem(), and relPath().
m_target
QCString DocSecRefItem::m_target private
Definition at line 927 of file docnode.h.
Referenced by DocSecRefItem(), parse(), and target().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp