Doxygen: DeepCopyUniquePtr< T > Class Template Reference
DeepCopyUniquePtr< T > Class Template Reference
Helper class add copy/assignment support to std::unique_ptr by making a deep copy Note that T may not be a polymorphic type.
Public Member Functions
DeepCopyUniquePtr (const DeepCopyUniquePtr &other)
DeepCopyUniquePtr & operator= (const DeepCopyUniquePtr &other)
DeepCopyUniquePtr (DeepCopyUniquePtr &&other)
DeepCopyUniquePtr & operator= (DeepCopyUniquePtr &&other)
~DeepCopyUniquePtr ()=default
Detailed Description
template<class T>
class DeepCopyUniquePtr< T >
Helper class add copy/assignment support to std::unique_ptr by making a deep copy Note that T may not be a polymorphic type.
Definition at line 59 of file definition.cpp.
Constructor & Destructor Documentation
DeepCopyUniquePtr() [1/2]
template<class T > DeepCopyUniquePtr< T >::DeepCopyUniquePtr (const DeepCopyUniquePtr< T > & other) inline
Definition at line 63 of file definition.cpp.
       : std::unique_ptr<T>(other ? new T(*other) : nullptr)
    {
    }
References DeepCopyUniquePtr().
Referenced by DeepCopyUniquePtr(), DeepCopyUniquePtr(), operator=(), and operator=().
DeepCopyUniquePtr() [2/2]
template<class T > DeepCopyUniquePtr< T >::DeepCopyUniquePtr (DeepCopyUniquePtr< T > && other) inline
Definition at line 72 of file definition.cpp.
: std::unique_ptr<T>(std::move(other)) {}
References DeepCopyUniquePtr().
~DeepCopyUniquePtr()
template<class T > DeepCopyUniquePtr< T >::~DeepCopyUniquePtr () default
Member Function Documentation
operator=() [1/2]
template<class T > DeepCopyUniquePtr & DeepCopyUniquePtr< T >::operator= (const DeepCopyUniquePtr< T > & other) inline
Definition at line 67 of file definition.cpp.
    {
      if (*this!=other) this->reset(other ? new T(*other) : nullptr);
      return *this;
    }
References DeepCopyUniquePtr().
operator=() [2/2]
template<class T > DeepCopyUniquePtr & DeepCopyUniquePtr< T >::operator= (DeepCopyUniquePtr< T > && other) inline
Definition at line 73 of file definition.cpp.
    {
      std::unique_ptr<T>::operator=(std::move(other));
      return *this;
    }
References DeepCopyUniquePtr().
The documentation for this class was generated from the following file:
src/definition.cpp