Doxygen: AnchorGenerator Class Reference
AnchorGenerator Class Reference
Singleton class used to generate anchors for Markdown headers.
#include <src/anchor.h>
Classes
struct Private
Public Member Functions
std::string generate (const std::string &title)
generates an anchor for a section with title.
bool isGenerated (const std::string &anchor) const
Returns true iff anchor is one of the generated anchors.
int reserve (const std::string &anchor)
Reserves a non-generated anchor.
Static Public Member Functions
static AnchorGenerator & instance ()
Returns the singleton instance.
static bool looksGenerated (const std::string &anchor)
Returns true if anchor is a potentially generated anchor.
static std::string addPrefixIfNeeded (const std::string &anchor)
Private Member Functions
AnchorGenerator ()
~AnchorGenerator ()
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Singleton class used to generate anchors for Markdown headers.
Definition at line 25 of file anchor.h.
Constructor & Destructor Documentation
AnchorGenerator()
AnchorGenerator::AnchorGenerator () private
Definition at line 34 of file anchor.cpp.
: p(std::make_unique<Private>()) {}
References p.
Referenced by instance(), and ~AnchorGenerator().
~AnchorGenerator()
AnchorGenerator::~AnchorGenerator () private default
References AnchorGenerator().
Member Function Documentation
addPrefixIfNeeded()
std::string AnchorGenerator::addPrefixIfNeeded (const std::string & anchor) static
Definition at line 46 of file anchor.cpp.
{
  if (Config_getEnum(MARKDOWN_ID_STYLE)==MARKDOWN_ID_STYLE_t::GITHUB &&
      (anchor.empty() || anchor.front() == '-' || std::isdigit(anchor.front())))
  {
    return prefix+anchor;
  }
  else
  {
    return anchor;
  }
}
References Config_getEnum, and prefix.
Referenced by generate(), and Markdown::Private::processLink().
generate()
std::string AnchorGenerator::generate (const std::string & title)
generates an anchor for a section with title.
Returns the anchor.
Definition at line 59 of file anchor.cpp.
{
  std::lock_guard lock(p->mutex);
  std::string result;
  auto createDoxygenStyleAnchor = [&]()
  {
    // overwrite result with the doxygen style anchor
    result = prefix+std::to_string(p->anchorCount++);
  };
  auto createGitHubStyleAnchor = [&]()
  {
    result.clear();
    size_t pos=0;
    while (pos<label.length())
    {
      uint8_t bytes       = getUTF8CharNumBytes(label[pos]);
      std::string charStr = getUTF8CharAt(label,pos);
      uint32_t cUnicode   = getUnicodeForUTF8CharAt(label,pos);
      char c = charStr[0];
      if (qisspace(c) || c=='-')
      {
        result+='-';
      }
      else if (c!='_' && isUTF8PunctuationCharacter(cUnicode))
      {
        // skip punctuation characters
      }
      else // normal UTF8 character
      {
        result+=convertUTF8ToLower(charStr);
      }
      pos+=bytes;
    }
    //printf("label='%s' result='%s'\n",qPrint(label),qPrint(result));
    if (result.empty()) // fallback use doxygen style anchor
    {
      createDoxygenStyleAnchor();
    }
    else
    {
      result = addPrefixIfNeeded(result);
      int &count = p->idCount[result];
      // Add end digits if an identical header already exists
      if (count>0)
      {
        result+="-"+std::to_string(count);
      }
      count++;
    }
  };
  switch (Config_getEnum(MARKDOWN_ID_STYLE))
  {
    case MARKDOWN_ID_STYLE_t::DOXYGEN:
      createDoxygenStyleAnchor();
      break;
    case MARKDOWN_ID_STYLE_t::GITHUB:
      createGitHubStyleAnchor();
      break;
  }
  p->anchorsUsed.insert(result);
  return result;
}
References addPrefixIfNeeded(), Config_getEnum, convertUTF8ToLower(), getUnicodeForUTF8CharAt(), getUTF8CharAt(), getUTF8CharNumBytes(), isUTF8PunctuationCharacter(), p, prefix, and qisspace().
Referenced by Markdown::Private::extractTitleId(), and MarkdownOutlineParser::parseInput().
instance()
AnchorGenerator & AnchorGenerator::instance () static
Returns the singleton instance.
Definition at line 38 of file anchor.cpp.
{
  static AnchorGenerator am;
  return am;
}
References AnchorGenerator().
Referenced by Markdown::Private::extractTitleId(), DocRoot::parse(), DocSection::parse(), MarkdownOutlineParser::parseInput(), and DefinitionImpl::writeDocAnchorsToTagFile().
isGenerated()
bool AnchorGenerator::isGenerated (const std::string & anchor) const
Returns true iff anchor is one of the generated anchors.
Definition at line 128 of file anchor.cpp.
{
  std::lock_guard lock(p->mutex);
  return p->anchorsUsed.find(anchor)!=p->anchorsUsed.end();
}
References p.
Referenced by DefinitionImpl::writeDocAnchorsToTagFile().
looksGenerated()
bool AnchorGenerator::looksGenerated (const std::string & anchor) static
Returns true if anchor is a potentially generated anchor.
Note this is a much weaker check than isGenerated() and may not always work.
Definition at line 140 of file anchor.cpp.
{
  return Config_getEnum(MARKDOWN_ID_STYLE)==MARKDOWN_ID_STYLE_t::DOXYGEN &&
         QCString(anchor).startsWith("autotoc_md");
}
References Config_getEnum.
Referenced by anonymous_namespace{tagreader.cpp}::TagFileParser::endDocAnchor().
reserve()
int AnchorGenerator::reserve (const std::string & anchor)
Reserves a non-generated anchor.
Definition at line 134 of file anchor.cpp.
{
  std::lock_guard lock(p->mutex);
  return p->idCount[anchor]++;
}
References p.
Member Data Documentation
p
std::unique_ptr<Private> AnchorGenerator::p private
Definition at line 54 of file anchor.h.
Referenced by AnchorGenerator(), generate(), isGenerated(), and reserve().
The documentation for this class was generated from the following files:
src/anchor.h
src/anchor.cpp