Doxygen: /home/runner/work/doxygen/doxygen/src/rtfgen.h File Reference
rtfgen.h File Reference
#include <array>
#include "config.h"
#include "outputgen.h"
Classes
class RTFCodeGenerator
Generator for RTF code fragments.
class RTFGenerator
Generator for RTF output.
struct RTFGenerator::RTFListItemInfo
Functions
QCString rtfFormatBmkStr (const QCString &name)
Function Documentation
rtfFormatBmkStr()
QCString rtfFormatBmkStr (const QCString & name)
Definition at line 2736 of file rtfgen.cpp.
{
  std::lock_guard<std::mutex> lock(g_rtfFormatMutex);
  // To overcome the 40-character tag limitation, we
  // substitute a short arbitrary string for the name
  // supplied, and keep track of the correspondence
  // between names and strings.
  auto it = g_tagMap.find(name.str());
  if (it!=g_tagMap.end()) // already known
  {
    return QCString(it->second);
  }
  QCString tag = g_nextTag;
  auto result = g_tagMap.insert( std::make_pair(name.str(), g_nextTag.str()) );
  if (result.second) // new item was added
  {
    // increment the next tag.
    char* nxtTag = g_nextTag.rawData() + g_nextTag.length() - 1;
    for ( unsigned int i = 0; i < g_nextTag.length(); ++i, --nxtTag )
    {
      if ( ( ++(*nxtTag) ) > 'Z' )
      {
        *nxtTag = 'A';
      }
      else
      {
        // Since there was no carry, we can stop now
        break;
      }
    }
  }
  Debug::print(Debug::Rtf,0,"Name = %s RTF_tag = %s\n",qPrint(name),qPrint(tag));
  return tag;
}
References g_nextTag, g_rtfFormatMutex, g_tagMap, QCString::insert(), QCString::length(), Rtf_Style_Default::name, Debug::print(), qPrint(), QCString::rawData(), Debug::Rtf, and QCString::str().
Referenced by RTFGenerator::endDoxyAnchor(), objectLinkToString(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::startLink(), RTFGenerator::startTextLink(), RTFGenerator::writeAnchor(), RTFCodeGenerator::writeCodeLink(), RTFCodeGenerator::writeLineNumber(), RTFGenerator::writeRTFReference(), and RTFGenerator::writeStartAnnoItem().