Doxygen: /home/runner/work/doxygen/doxygen/src/docbookgen.cpp File Reference
docbookgen.cpp File Reference
#include <stdlib.h>
#include "docbookgen.h"
#include "doxygen.h"
#include "message.h"
#include "config.h"
#include "classlist.h"
#include "classdef.h"
#include "diagram.h"
#include "util.h"
#include "defargs.h"
#include "outputgen.h"
#include "dot.h"
#include "dotcallgraph.h"
#include "dotclassgraph.h"
#include "dotdirdeps.h"
#include "dotgroupcollaboration.h"
#include "dotincldepgraph.h"
#include "pagedef.h"
#include "filename.h"
#include "version.h"
#include "docbookvisitor.h"
#include "docparser.h"
#include "language.h"
#include "parserintf.h"
#include "arguments.h"
#include "memberlist.h"
#include "groupdef.h"
#include "memberdef.h"
#include "namespacedef.h"
#include "membername.h"
#include "membergroup.h"
#include "dirdef.h"
#include "section.h"
#include "dir.h"
#include "growbuf.h"
#include "outputlist.h"
Macros
#define Docbook_DB(x) do {} while(0)
#define DB_GEN_C
#define DB_GEN_C1(x)
#define DB_GEN_C2(y)
#define DB_GEN_C2a(x, y)
Functions
void writeDocbookString (TextStream &t, const QCString &s)
void writeDocbookCodeString (TextStream &t, const QCString &str, int &col)
static void addIndexTerm (TextStream &t, QCString prim, QCString sec="")
void writeDocbookLink (TextStream &t, const QCString &, const QCString &compoundId, const QCString &anchorId, const QCString &text, const QCString &)
static QCString objectLinkToString (const QCString &, const QCString &f, const QCString &anchor, const QCString &text)
QCString convertToDocBook (const QCString &s, const bool retainNewline)
Variables
static constexpr auto hex ="0123456789ABCDEF"
Macro Definition Documentation
DB_GEN_C
#define DB_GEN_C
Definition at line 69 of file docbookgen.cpp.
DB_GEN_C1
#define DB_GEN_C1 (x)
Definition at line 70 of file docbookgen.cpp.
DB_GEN_C2
#define DB_GEN_C2 (y)
Definition at line 71 of file docbookgen.cpp.
DB_GEN_C2a
#define DB_GEN_C2a (x, y)
Definition at line 72 of file docbookgen.cpp.
Docbook_DB
#define Docbook_DB (x) do {} while(0)
Definition at line 57 of file docbookgen.cpp.
Function Documentation
addIndexTerm()
static void addIndexTerm (TextStream & t, QCString prim, QCString sec = "") static
Definition at line 124 of file docbookgen.cpp.
{
  t << "<indexterm><primary>";
  t << convertToDocBook(prim);
  t << "</primary>";
  if (!sec.isEmpty())
  {
    t << "<secondary>";
    t << convertToDocBook(sec);
    t << "</secondary>";
  }
  t << "</indexterm>\n";
}
References convertToDocBook().
Referenced by DocbookGenerator::addIndexItem(), DocbookGenerator::endTitleHead(), and DocbookGenerator::startMemberDoc().
convertToDocBook()
QCString convertToDocBook (const QCString & s, const bool retainNewline)
Converts a string to an DocBook-encoded string
Definition at line 1386 of file docbookgen.cpp.
{
  if (s.isEmpty()) return s;
  GrowBuf growBuf;
  const char *q;
  int cnt;
  const char *p=s.data();
  char c;
  while ((c=*p++))
  {
    switch (c)
    {
      case '\n': if (retainNewline) growBuf.addStr("<literallayout>&#160;&#xa;</literallayout>"); growBuf.addChar(c);   break;
      case '<':  growBuf.addStr("&lt;");   break;
      case '>':  growBuf.addStr("&gt;");   break;
      case '&':  // possibility to have a special symbol
        q = p;
        cnt = 2; // we have to count & and ; as well
        while ((*q >= 'a' && *q <= 'z') || (*q >= 'A' && *q <= 'Z') || (*q >= '0' && *q <= '9'))
        {
          cnt++;
          q++;
        }
        if (*q == ';')
        {
           --p; // we need & as well
           HtmlEntityMapper::SymType res = HtmlEntityMapper::instance().name2sym(QCString(p).left(cnt));
           if (res == HtmlEntityMapper::Sym_Unknown)
           {
             p++;
             growBuf.addStr("&amp;");
           }
           else
           {
             growBuf.addStr(HtmlEntityMapper::instance().docbook(res));
             q++;
             p = q;
           }
        }
        else
        {
          growBuf.addStr("&amp;");
        }
        break;
      case '\'': growBuf.addStr("&apos;"); break;
      case '"':  growBuf.addStr("&quot;"); break;
      case  1: case  2: case  3: case  4: case  5: case  6: case 7:  case  8:
      case 11: case 12: case 14: case 15: case 16: case 17: case 18:
      case 19: case 20: case 21: case 22: case 23: case 24: case 25: case 26:
      case 27: case 28: case 29: case 30: case 31:
        growBuf.addStr("&#x24");
        growBuf.addChar(hex[static_cast<uint8_t>(c)>>4]);
        growBuf.addChar(hex[static_cast<uint8_t>(c)&0xF]);
        growBuf.addChar(';');
        break;
      default:
        growBuf.addChar(c);
        break;
    }
  }
  growBuf.addChar(0);
  return growBuf.get();
}
References GrowBuf::addChar(), GrowBuf::addStr(), QCString::data(), GrowBuf::get(), hex, HtmlEntityMapper::instance(), QCString::isEmpty(), HtmlEntityMapper::name2sym(), and HtmlEntityMapper::Sym_Unknown.
Referenced by addIndexTerm(), DocbookGenerator::docify(), DocbookDocVisitor::filter(), objectLinkToString(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookGenerator::startDescTable(), DocbookGenerator::startIndexSection(), DocbookGenerator::startMemberDoc(), DocbookGenerator::startMemberDocSimple(), DocbookDocVisitor::visitPreStart(), writeDocbookString(), DocbookGenerator::writeInheritedSectionTitle(), and DocbookGenerator::writeLocalToc().
objectLinkToString()
static QCString objectLinkToString (const QCString & , const QCString & f, const QCString & anchor, const QCString & text) static
Definition at line 726 of file docbookgen.cpp.
{
DB_GEN_C
  QCString result;
  if (!anchor.isEmpty())
  {
    if (!f.isEmpty()) result += "<link linkend=\"_" + stripPath(f) + "_1" + anchor + "\">";
    else   result += "<link linkend=\"_" + anchor + "\">";
  }
  else
  {
    result += "<link linkend=\"_" + stripPath(f) + "\">";
  }
  result += convertToDocBook(text);
  result += "</link>";
  return result;
}
References convertToDocBook(), DB_GEN_C, QCString::isEmpty(), and stripPath().
Referenced by DocbookGenerator::writeInheritedSectionTitle(), LatexGenerator::writeInheritedSectionTitle(), ManGenerator::writeInheritedSectionTitle(), RTFGenerator::writeInheritedSectionTitle(), DocbookGenerator::writeObjectLink(), LatexGenerator::writeObjectLink(), and RTFGenerator::writeObjectLink().
writeDocbookCodeString()
void writeDocbookCodeString (TextStream & t, const QCString & str, int & col) inline
Definition at line 82 of file docbookgen.cpp.
{
  if (str.isEmpty()) return;
  const char *s = str.data();
  char c;
  while ((c=*s++))
  {
    switch(c)
    {
      case '\t':
        {
          int tabSize = Config_getInt(TAB_SIZE);
          int spacesToNextTabStop = tabSize - (col%tabSize);
          col+=spacesToNextTabStop;
          while (spacesToNextTabStop--) t << "&#32;";
          break;
        }
      case ' ':  t << "&#32;"; col++;  break;
      case '<':  t << "&lt;"; col++;   break;
      case '>':  t << "&gt;"; col++;   break;
      case '&':  t << "&amp;"; col++;  break;
      case '\'': t << "&apos;"; col++; break;
      case '"':  t << "&quot;"; col++; break;
      default:
        {
          uint8_t uc = static_cast<uint8_t>(c);
          static const char *hex="0123456789ABCDEF";
          if (uc<32)
          {
            t << "&#x24" << hex[uc>>4] << hex[uc&0xF] << ";";
          }
          else
          {
            t << c;
          }
          col++;
        }
        break;
    }
  }
}
References Config_getInt, QCString::data(), hex, and QCString::isEmpty().
Referenced by DocbookCodeGenerator::codify().
writeDocbookLink()
void writeDocbookLink (TextStream & t, const QCString & , const QCString & compoundId, const QCString & anchorId, const QCString & text, const QCString &)
Definition at line 137 of file docbookgen.cpp.
{
  t << "<link linkend=\"_" << stripPath(compoundId);
  if (!anchorId.isEmpty()) t << "_1" << anchorId;
  t << "\"";
  t << ">";
  writeDocbookString(t,text);
  t << "</link>";
}
References QCString::isEmpty(), stripPath(), and writeDocbookString().
Referenced by DocbookCodeGenerator::writeCodeLink().
writeDocbookString()
void writeDocbookString (TextStream & t, const QCString & s) inline
Definition at line 77 of file docbookgen.cpp.
{
  t << convertToDocBook(s);
}
References convertToDocBook().
Referenced by DocbookCodeGenerator::writeCodeLinkLine(), and writeDocbookLink().
Variable Documentation
hex
constexpr auto hex ="0123456789ABCDEF" static constexpr
Definition at line 1383 of file docbookgen.cpp.
Referenced by HtmlCodeGenerator::codify(), convertToDocBook(), HtmlCodeGenerator::docify(), HtmlDocVisitor::filter(), HtmlDocVisitor::filterQuotedCdataAttr(), getDirectoryBackgroundColor(), FilterAlphaIndex::keyToLabel(), latexFilterURL(), letterToLabel(), searchId(), writeDocbookCodeString(), and TextGeneratorHtml::writeString().