Doxygen: DocNode Class Reference
DocNode Class Reference
Abstract node interface with type information.
#include <src/docnode.h>
Public Member Functions
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Protected Types
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions
void setInsidePreformatted (bool p)
Private Attributes
bool m_insidePre = false
DocParser * m_parser
DocNodeVariant * m_parent
DocNodeVariant * m_thisVariant = nullptr
Detailed Description
Abstract node interface with type information.
Definition at line 80 of file docnode.h.
Member Enumeration Documentation
RefType
enum DocNode::RefType protected
Enumerator
Unknown
Anchor
Section
Table
Definition at line 109 of file docnode.h.
{ Unknown, Anchor, Section, Table };
Constructor & Destructor Documentation
DocNode()
DocNode::DocNode (DocParser * parser, DocNodeVariant * parent) inline
Creates a new node
Definition at line 84 of file docnode.h.
: m_parser(parser), m_parent(parent) {}
References m_parent, m_parser, parent(), and parser().
Referenced by DocAnchor::DocAnchor(), DocCite::DocCite(), DocCompoundNode::DocCompoundNode(), DocEmoji::DocEmoji(), DocFormula::DocFormula(), DocHorRuler::DocHorRuler(), DocInclude::DocInclude(), DocIncOperator::DocIncOperator(), DocIndexEntry::DocIndexEntry(), DocLineBreak::DocLineBreak(), DocLineBreak::DocLineBreak(), DocLinkedWord::DocLinkedWord(), DocParamList::DocParamList(), DocSeparator::DocSeparator(), DocSimpleListItem::DocSimpleListItem(), DocSimpleSectSep::DocSimpleSectSep(), DocStyleChange::DocStyleChange(), DocSymbol::DocSymbol(), DocURL::DocURL(), DocVerbatim::DocVerbatim(), DocWhiteSpace::DocWhiteSpace(), DocWord::DocWord(), and ~DocNode().
~DocNode()
DocNode::~DocNode () default
References DocNode().
Member Function Documentation
isPreformatted()
bool DocNode::isPreformatted () const inline
Returns TRUE iff this node is inside a preformatted section
Definition at line 104 of file docnode.h.
{ return m_insidePre; }
References m_insidePre.
Referenced by HtmlDocVisitor::operator()(), HtmlDocVisitor::operator()(), HtmlDocVisitor::operator()(), HtmlDocVisitor::operator()(), HtmlDocVisitor::operator()(), and HtmlDocVisitor::operator()().
parent() [1/2]
DocNodeVariant * DocNode::parent () inline
Returns the parent of this node or nullptr for the root node.
Definition at line 89 of file docnode.h.
{ return m_parent; }
References m_parent, and parent().
Referenced by determineIfNeedsTag(), DocAnchor::DocAnchor(), DocAutoList::DocAutoList(), DocAutoListItem::DocAutoListItem(), DocCite::DocCite(), DocCompoundNode::DocCompoundNode(), DocDiagramFileBase::DocDiagramFileBase(), DocEmoji::DocEmoji(), DocFormula::DocFormula(), DocHorRuler::DocHorRuler(), DocHRef::DocHRef(), DocHtmlBlockQuote::DocHtmlBlockQuote(), DocHtmlCaption::DocHtmlCaption(), DocHtmlCell::DocHtmlCell(), DocHtmlDescData::DocHtmlDescData(), DocHtmlDescList::DocHtmlDescList(), DocHtmlDescTitle::DocHtmlDescTitle(), DocHtmlDetails::DocHtmlDetails(), DocHtmlHeader::DocHtmlHeader(), DocHtmlList::DocHtmlList(), DocHtmlListItem::DocHtmlListItem(), DocHtmlRow::DocHtmlRow(), DocHtmlSummary::DocHtmlSummary(), DocHtmlTable::DocHtmlTable(), DocImage::DocImage(), DocInclude::DocInclude(), DocIncOperator::DocIncOperator(), DocIndexEntry::DocIndexEntry(), DocInternal::DocInternal(), DocInternalRef::DocInternalRef(), DocLineBreak::DocLineBreak(), DocLineBreak::DocLineBreak(), DocLink::DocLink(), DocLinkedWord::DocLinkedWord(), DocNode(), DocPara::DocPara(), DocParamList::DocParamList(), DocParamSect::DocParamSect(), DocParBlock::DocParBlock(), DocRef::DocRef(), DocSecRefItem::DocSecRefItem(), DocSecRefList::DocSecRefList(), DocSection::DocSection(), DocSeparator::DocSeparator(), DocSimpleList::DocSimpleList(), DocSimpleListItem::DocSimpleListItem(), DocSimpleSect::DocSimpleSect(), DocSimpleSectSep::DocSimpleSectSep(), DocStyleChange::DocStyleChange(), DocSymbol::DocSymbol(), DocTitle::DocTitle(), DocURL::DocURL(), DocVerbatim::DocVerbatim(), DocVhdlFlow::DocVhdlFlow(), DocWhiteSpace::DocWhiteSpace(), DocWord::DocWord(), DocXRefItem::DocXRefItem(), getParagraphContext(), DocPara::handleHtmlStartTag(), listIsNested(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), ManDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), parent(), DocPara::parse(), DocParamList::parse(), DocTitle::parseFromString(), DocHtmlDetails::parseSummary(), and setParent().
parent() [2/2]
const DocNodeVariant * DocNode::parent () const inline
Definition at line 90 of file docnode.h.
{ return m_parent; }
References m_parent.
parser() [1/2]
DocParser * DocNode::parser () inline
Definition at line 97 of file docnode.h.
{ return m_parser; }
References m_parser.
Referenced by DocSimpleSect::appendLinkWord(), DocAnchor::DocAnchor(), DocAutoList::DocAutoList(), DocAutoListItem::DocAutoListItem(), DocCite::DocCite(), DocCompoundNode::DocCompoundNode(), DocDiaFile::DocDiaFile(), DocDiagramFileBase::DocDiagramFileBase(), DocDotFile::DocDotFile(), DocEmoji::DocEmoji(), DocFormula::DocFormula(), DocHorRuler::DocHorRuler(), DocHRef::DocHRef(), DocHtmlBlockQuote::DocHtmlBlockQuote(), DocHtmlCaption::DocHtmlCaption(), DocHtmlCell::DocHtmlCell(), DocHtmlDescData::DocHtmlDescData(), DocHtmlDescList::DocHtmlDescList(), DocHtmlDescTitle::DocHtmlDescTitle(), DocHtmlDetails::DocHtmlDetails(), DocHtmlHeader::DocHtmlHeader(), DocHtmlList::DocHtmlList(), DocHtmlListItem::DocHtmlListItem(), DocHtmlRow::DocHtmlRow(), DocHtmlSummary::DocHtmlSummary(), DocHtmlTable::DocHtmlTable(), DocImage::DocImage(), DocInclude::DocInclude(), DocIncOperator::DocIncOperator(), DocIndexEntry::DocIndexEntry(), DocInternal::DocInternal(), DocInternalRef::DocInternalRef(), DocLineBreak::DocLineBreak(), DocLineBreak::DocLineBreak(), DocLink::DocLink(), DocLinkedWord::DocLinkedWord(), DocMscFile::DocMscFile(), DocNode(), DocPara::DocPara(), DocParamList::DocParamList(), DocParamSect::DocParamSect(), DocParBlock::DocParBlock(), DocPlantUmlFile::DocPlantUmlFile(), DocRef::DocRef(), DocRoot::DocRoot(), DocSecRefItem::DocSecRefItem(), DocSecRefList::DocSecRefList(), DocSection::DocSection(), DocSeparator::DocSeparator(), DocSimpleList::DocSimpleList(), DocSimpleListItem::DocSimpleListItem(), DocSimpleSect::DocSimpleSect(), DocSimpleSectSep::DocSimpleSectSep(), DocStyleChange::DocStyleChange(), DocSymbol::DocSymbol(), DocText::DocText(), DocTitle::DocTitle(), DocURL::DocURL(), DocVerbatim::DocVerbatim(), DocVhdlFlow::DocVhdlFlow(), DocWhiteSpace::DocWhiteSpace(), DocWord::DocWord(), DocXRefItem::DocXRefItem(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleDoxyConfig(), DocPara::handleEmoji(), DocPara::handleFile(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlHeader(), DocPara::handleHtmlStartTag(), DocPara::handleIFile(), DocPara::handleILine(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocPara::handleInheritDoc(), DocPara::handleLink(), DocPara::handleParamSection(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleShowDate(), DocPara::handleSimpleSection(), DocPara::handleStartCode(), DocPara::handleVhdlFlow(), DocPara::handleXRefItem(), DocPara::injectToken(), DocAutoList::parse(), DocAutoListItem::parse(), DocDiaFile::parse(), DocDotFile::parse(), DocHRef::parse(), DocHtmlBlockQuote::parse(), DocHtmlCaption::parse(), DocHtmlCell::parse(), DocHtmlDescData::parse(), DocHtmlDescList::parse(), DocHtmlDescTitle::parse(), DocHtmlDetails::parse(), DocHtmlHeader::parse(), DocHtmlList::parse(), DocHtmlListItem::parse(), DocHtmlRow::parse(), DocHtmlSummary::parse(), DocHtmlTable::parse(), DocImage::parse(), DocInclude::parse(), DocIncOperator::parse(), DocIndexEntry::parse(), DocInternal::parse(), DocInternalRef::parse(), DocLink::parse(), DocMscFile::parse(), DocPara::parse(), DocParamList::parse(), DocParamSect::parse(), DocParBlock::parse(), DocPlantUmlFile::parse(), DocRef::parse(), DocRoot::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocSection::parse(), DocSimpleList::parse(), DocSimpleListItem::parse(), DocSimpleSect::parse(), DocText::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocXRefItem::parse(), DocTitle::parseFromString(), DocSimpleSect::parseRcs(), DocHtmlDetails::parseSummary(), DocHtmlCell::parseXml(), DocHtmlList::parseXml(), DocHtmlListItem::parseXml(), DocHtmlRow::parseXml(), DocHtmlTable::parseXml(), DocParamList::parseXml(), and DocSimpleSect::parseXml().
parser() [2/2]
const DocParser * DocNode::parser () const inline
Definition at line 98 of file docnode.h.
{ return m_parser; }
References m_parser.
setInsidePreformatted()
void DocNode::setInsidePreformatted (bool p) inline protected
Sets whether or not this item is inside a preformatted section
Definition at line 108 of file docnode.h.
{ m_insidePre = p; }
References m_insidePre.
Referenced by DocPara::handleHtmlEndTag(), and DocPara::handleHtmlStartTag().
setParent()
void DocNode::setParent (DocNodeVariant * parent) inline
Sets a new parent for this node.
Definition at line 101 of file docnode.h.
{ m_parent = parent; }
References m_parent, and parent().
setThisVariant()
void DocNode::setThisVariant (DocNodeVariant * thisVariant) inline
Definition at line 95 of file docnode.h.
{ m_thisVariant=thisVariant; }
References m_thisVariant, and thisVariant().
thisVariant() [1/2]
DocNodeVariant * DocNode::thisVariant () inline
Definition at line 92 of file docnode.h.
{ return m_thisVariant; }
References m_thisVariant.
Referenced by DocSimpleSect::appendLinkWord(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleDoxyConfig(), DocPara::handleEmoji(), DocPara::handleFile(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlHeader(), DocPara::handleHtmlStartTag(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocPara::handleInheritDoc(), DocPara::handleLink(), DocPara::handleParamSection(), DocPara::handleRef(), DocPara::handleShowDate(), DocPara::handleSimpleSection(), DocPara::handleStartCode(), DocPara::handleVhdlFlow(), DocPara::handleXRefItem(), DocPara::injectToken(), DocAutoList::parse(), DocAutoListItem::parse(), DocDiaFile::parse(), DocDotFile::parse(), DocHRef::parse(), DocHtmlBlockQuote::parse(), DocHtmlCaption::parse(), DocHtmlCell::parse(), DocHtmlDescData::parse(), DocHtmlDescList::parse(), DocHtmlDescTitle::parse(), DocHtmlDetails::parse(), DocHtmlHeader::parse(), DocHtmlList::parse(), DocHtmlListItem::parse(), DocHtmlRow::parse(), DocHtmlSummary::parse(), DocHtmlTable::parse(), DocImage::parse(), DocIndexEntry::parse(), DocInternal::parse(), DocInternalRef::parse(), DocLink::parse(), DocMscFile::parse(), DocPara::parse(), DocParamList::parse(), DocParamSect::parse(), DocParBlock::parse(), DocPlantUmlFile::parse(), DocRef::parse(), DocRoot::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocSection::parse(), DocSimpleList::parse(), DocSimpleListItem::parse(), DocSimpleSect::parse(), DocText::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocXRefItem::parse(), DocTitle::parseFromString(), DocSimpleSect::parseRcs(), DocHtmlCell::parseXml(), DocHtmlList::parseXml(), DocHtmlListItem::parseXml(), DocHtmlRow::parseXml(), DocHtmlTable::parseXml(), DocParamList::parseXml(), DocSimpleSect::parseXml(), and setThisVariant().
thisVariant() [2/2]
const DocNodeVariant * DocNode::thisVariant () const inline
Definition at line 93 of file docnode.h.
{ return m_thisVariant; }
References m_thisVariant.
Member Data Documentation
m_insidePre
bool DocNode::m_insidePre = false private
Definition at line 111 of file docnode.h.
Referenced by isPreformatted(), and setInsidePreformatted().
m_parent
DocNodeVariant* DocNode::m_parent private
Definition at line 113 of file docnode.h.
Referenced by DocNode(), parent(), parent(), and setParent().
m_parser
DocParser* DocNode::m_parser private
Definition at line 112 of file docnode.h.
Referenced by DocNode(), parser(), and parser().
m_thisVariant
DocNodeVariant* DocNode::m_thisVariant = nullptr private
Definition at line 114 of file docnode.h.
Referenced by setThisVariant(), thisVariant(), and thisVariant().
The documentation for this class was generated from the following file:
src/docnode.h