Doxygen: ConceptTreeContext::Private Class Reference
ConceptTreeContext::Private Class Reference
Public Member Functions
Private ()
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
TemplateVariant title () const
int createMaxDepth () const
int createPreferredDepth () const
Private Attributes
TemplateListIntfPtr m_conceptTree
CachedItem< int, Private, &Private::createMaxDepth > m_maxDepth
CachedItem< int, Private, &Private::createPreferredDepth > m_preferredDepth
Static Private Attributes
static const PropertyMap< ConceptTreeContext::Private > s_inst
Detailed Description
Definition at line 6791 of file context.cpp.
Constructor & Destructor Documentation
Private()
ConceptTreeContext::Private::Private () inline
Definition at line 6794 of file context.cpp.
    {
      m_conceptTree = NestingContext::alloc(0,ContextTreeType::Concept,0);
      auto ctx = std::dynamic_pointer_cast<NestingContext>(m_conceptTree);
      ClassDefSet visitedClasses;
      // Add concepts
      ctx->addNamespaces(*Doxygen::namespaceLinkedMap,TRUE,FALSE,TRUE,visitedClasses);
      ctx->addConcepts(*Doxygen::conceptLinkedMap,TRUE,visitedClasses);
    }
References NestingContext::alloc(), Concept, Doxygen::conceptLinkedMap, FALSE, m_conceptTree, Doxygen::namespaceLinkedMap, and TRUE.
Member Function Documentation
createMaxDepth()
int ConceptTreeContext::Private::createMaxDepth () const inline private
Definition at line 6820 of file context.cpp.
    {
      return computeMaxDepth(m_conceptTree);
    }
References computeMaxDepth(), and m_conceptTree.
createPreferredDepth()
int ConceptTreeContext::Private::createPreferredDepth () const inline private
Definition at line 6824 of file context.cpp.
    {
      return computePreferredDepth(m_conceptTree,m_maxDepth.get(this));
    }
References computePreferredDepth(), m_conceptTree, and m_maxDepth.
fields()
StringVector ConceptTreeContext::Private::fields () const inline
Definition at line 6806 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fileName()
TemplateVariant ConceptTreeContext::Private::fileName () const inline private
Definition at line 6811 of file context.cpp.
{ return "concepts"; }
get()
TemplateVariant ConceptTreeContext::Private::get (const QCString & n) const inline
Definition at line 6805 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), and s_inst.
highlight()
TemplateVariant ConceptTreeContext::Private::highlight () const inline private
Definition at line 6813 of file context.cpp.
{ return "concepts"; }
maxDepth()
TemplateVariant ConceptTreeContext::Private::maxDepth () const inline private
Definition at line 6815 of file context.cpp.
{ return m_maxDepth.get(this); }
References m_maxDepth.
preferredDepth()
TemplateVariant ConceptTreeContext::Private::preferredDepth () const inline private
Definition at line 6816 of file context.cpp.
{ return m_preferredDepth.get(this); }
References m_preferredDepth.
relPath()
TemplateVariant ConceptTreeContext::Private::relPath () const inline private
Definition at line 6812 of file context.cpp.
{ return ""; }
subhighlight()
TemplateVariant ConceptTreeContext::Private::subhighlight () const inline private
Definition at line 6814 of file context.cpp.
{ return ""; }
title()
TemplateVariant ConceptTreeContext::Private::title () const inline private
Definition at line 6817 of file context.cpp.
{ return theTranslator->trConcept(true,false); }
References theTranslator, and Translator::trConcept().
tree()
TemplateVariant ConceptTreeContext::Private::tree () const inline private
Definition at line 6810 of file context.cpp.
{ return TemplateVariant(m_conceptTree); }
References m_conceptTree.
Member Data Documentation
m_conceptTree
TemplateListIntfPtr ConceptTreeContext::Private::m_conceptTree private
Definition at line 6828 of file context.cpp.
Referenced by createMaxDepth(), createPreferredDepth(), Private(), and tree().
m_maxDepth
CachedItem<int, Private, &Private::createMaxDepth> ConceptTreeContext::Private::m_maxDepth private
Definition at line 6829 of file context.cpp.
Referenced by createPreferredDepth(), and maxDepth().
m_preferredDepth
CachedItem<int, Private, &Private::createPreferredDepth> ConceptTreeContext::Private::m_preferredDepth private
Definition at line 6830 of file context.cpp.
Referenced by preferredDepth().
s_inst
const PropertyMap< ConceptTreeContext::Private > ConceptTreeContext::Private::s_inst static private
Initial value:
{
  {  "tree",          &Private::tree },
  {  "fileName",      &Private::fileName },
  {  "relPath",       &Private::relPath },
  {  "highlight",     &Private::highlight },
  {  "subhighlight",  &Private::subhighlight },
  {  "title",         &Private::title },
  {  "preferredDepth",&Private::preferredDepth },
  {  "maxDepth",      &Private::maxDepth }
}
Definition at line 6831 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/context.cpp