Doxygen: TemplateNodeIf Class Reference
TemplateNodeIf Class Reference
Class representing an 'if' tag in a template.
Classes
struct GuardedNodes
Public Member Functions
TemplateNodeIf (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeIf ()
void render (TextStream &ts, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeIf >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()=default
TemplateNode * parent ()
Private Attributes
std::vector< std::unique_ptr< GuardedNodes > > m_ifGuardedNodes
TemplateNodeList m_falseNodes
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeIf >
static TemplateNodePtr createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeIf >
void mkpath (const TemplateContextImpl *ci, const std::string &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeIf >
QCString m_templateName
int m_line
Detailed Description
Class representing an 'if' tag in a template.
Definition at line 3072 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeIf()
TemplateNodeIf::TemplateNodeIf (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 3075 of file template.cpp.
                                                                                              :
      TemplateNodeCreator<TemplateNodeIf>(parser,parent,line)
    {
      AUTO_TRACE("data={}",Trace::trunc(data));
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"missing argument for if tag");
      }
      StringVector stopAt = { "endif", "elif", "else" };
      // if 'nodes'
      {
        m_ifGuardedNodes.push_back(std::make_unique<GuardedNodes>());
        auto &guardedNodes = m_ifGuardedNodes.back();
        ExpressionParser ex(parser,line);
        guardedNodes->line = line;
        guardedNodes->guardAst = ex.parse(data);
        parser->parse(this,line,stopAt,guardedNodes->trueNodes);
      }
      auto tok = parser->takeNextToken();
      // elif 'nodes'
      while (tok && tok->data.startsWith("elif "))
      {
        m_ifGuardedNodes.push_back(std::make_unique<GuardedNodes>());
        auto &guardedNodes = m_ifGuardedNodes.back();
        ExpressionParser ex(parser,line);
        guardedNodes->line = tok->line;
        guardedNodes->guardAst = ex.parse(tok->data.mid(5));
        parser->parse(this,tok->line,stopAt,guardedNodes->trueNodes);
        // proceed to the next token
        tok = parser->takeNextToken();
      }
      // else 'nodes'
      if (tok && tok->data=="else")
      {
        stopAt.pop_back(); // remove "else"
        stopAt.pop_back(); // remove "elif"
        parser->parse(this,line,stopAt,m_falseNodes);
        parser->removeNextToken(); // skip over endif
      }
    }
References AUTO_TRACE, QCString::isEmpty(), m_falseNodes, m_ifGuardedNodes, TemplateNodeCreator< TemplateNodeIf >::m_templateName, ExpressionParser::parse(), TemplateParser::parse(), TemplateParser::removeNextToken(), TemplateParser::takeNextToken(), Trace::trunc(), and TemplateParser::warn().
~TemplateNodeIf()
TemplateNodeIf::~TemplateNodeIf () inline
Definition at line 3118 of file template.cpp.
    {
    }
Member Function Documentation
render()
void TemplateNodeIf::render (TextStream & ts, TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 3122 of file template.cpp.
    {
      AUTO_TRACE();
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      //printf("TemplateNodeIf::render #trueNodes=%d #falseNodes=%d\n",m_trueNodes.count(),m_falseNodes.count());
      bool processed=FALSE;
      for (auto &nodes : m_ifGuardedNodes)
      {
        if (nodes->guardAst)
        {
          TemplateVariant guardValue = nodes->guardAst->resolve(c);
          if (guardValue.toBool()) // render nodes for the first guard that evaluated to 'true'
          {
            nodes->trueNodes.render(ts,c);
            processed=TRUE;
            break;
          }
        }
        else
        {
          ci->warn(m_templateName,nodes->line,"invalid expression for if/elif");
        }
      }
      if (!processed)
      {
        // all guards are false, render 'else' nodes
        m_falseNodes.render(ts,c);
      }
    }
References AUTO_TRACE, FALSE, m_falseNodes, m_ifGuardedNodes, TemplateNodeCreator< TemplateNodeIf >::m_line, TemplateNodeCreator< TemplateNodeIf >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::setLocation(), TemplateVariant::toBool(), TRUE, and TemplateContextImpl::warn().
Member Data Documentation
m_falseNodes
TemplateNodeList TemplateNodeIf::m_falseNodes private
Definition at line 3161 of file template.cpp.
Referenced by render(), and TemplateNodeIf().
m_ifGuardedNodes
std::vector< std::unique_ptr<GuardedNodes> > TemplateNodeIf::m_ifGuardedNodes private
Definition at line 3160 of file template.cpp.
Referenced by render(), and TemplateNodeIf().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/template.cpp