Doxygen: src/docparser_p.h File Reference
docparser_p.h File Reference
Private header shared between docparser.cpp and docnode.cpp.
#include <cassert>
#include <stack>
#include <iterator>
#include <vector>
#include <deque>
#include <cstdint>
#include "containers.h"
#include "docparser.h"
#include "docnode.h"
#include "doctokenizer.h"
#include "searchindex.h"
#include "construct.h"
#include "cmdmapper.h"
Classes
class IterableStack< T, Container >
struct DocParserContext
Parser's context to store all global variables.
class DocParser
class AutoNodeStack
Typedefs
using DefinitionStack = std::vector<const Definition *>
using DocNodeStack = std::stack<DocNodeVariant *>
using DocStyleChangeStack = IterableStack<const DocNodeVariant *>
Functions
bool isPreformatted (const DocNodeVariant *n)
bool insidePRE (const DocNodeVariant *n)
bool insideLI (const DocNodeVariant *n)
bool insideBlockQuote (const DocNodeVariant *n)
bool insideUL (const DocNodeVariant *n)
bool insideOL (const DocNodeVariant *n)
bool insideTable (const DocNodeVariant *n)
bool insideDetails (const DocNodeVariant *n)
bool insideDL (const DocNodeVariant *n)
Detailed Description
Private header shared between docparser.cpp and docnode.cpp.
Definition in file docparser_p.h.
Typedef Documentation
DefinitionStack
using DefinitionStack = std::vector<const Definition *>
Definition at line 38 of file docparser_p.h.
DocNodeStack
using DocNodeStack = std::stack<DocNodeVariant *>
Definition at line 39 of file docparser_p.h.
DocStyleChangeStack
using DocStyleChangeStack = IterableStack<const DocNodeVariant *>
Definition at line 55 of file docparser_p.h.
Function Documentation
insideBlockQuote()
bool insideBlockQuote (const DocNodeVariant * n) inline
Returns TRUE iff node n is a child of a html list item node
Definition at line 199 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlBlockQuote>(*n)) return TRUE;
    n=parent(n);
  }
  return FALSE;
}
References FALSE, parent(), and TRUE.
Referenced by DocPara::handleHtmlEndTag().
insideDetails()
bool insideDetails (const DocNodeVariant * n) inline
Definition at line 258 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlDetails>(*n)) return TRUE;
    n=parent(n);
  }
  return FALSE;
}
References FALSE, parent(), and TRUE.
Referenced by DocPara::handleHtmlEndTag(), and DocPara::handleHtmlStartTag().
insideDL()
bool insideDL (const DocNodeVariant * n) inline
Definition at line 270 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlDescList>(*n)) return TRUE;
    n=parent(n);
  }
  return FALSE;
}
References FALSE, parent(), and TRUE.
Referenced by DocPara::handleHtmlStartTag().
insideLI()
bool insideLI (const DocNodeVariant * n) inline
Returns TRUE iff node n is a child of a html list item node
Definition at line 188 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlListItem>(*n)) return TRUE;
    n=parent(n);
  }
  return FALSE;
}
References FALSE, parent(), and TRUE.
Referenced by DocPara::handleHtmlEndTag(), and DocParser::handleStyleArgument().
insideOL()
bool insideOL (const DocNodeVariant * n) inline
Returns TRUE iff node n is a child of a ordered html list node
Definition at line 230 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlList>(*n) &&
        std::get<DocHtmlList>(*n).type()==DocHtmlList::Ordered)
    {
      return TRUE;
    }
    n=parent(n);
  }
  return FALSE;
}
References FALSE, DocHtmlList::Ordered, parent(), and TRUE.
Referenced by DocPara::handleHtmlEndTag(), and DocPara::handleHtmlStartTag().
insidePRE()
bool insidePRE (const DocNodeVariant * n) inline
Returns TRUE iff node n is a child of a preformatted node
Definition at line 177 of file docparser_p.h.
{
  while (n)
  {
    if (isPreformatted(n)) return TRUE;
    n=parent(n);
  }
  return FALSE;
}
References FALSE, isPreformatted(), parent(), and TRUE.
Referenced by DocParser::defaultHandleToken(), and DocPara::parse().
insideTable()
bool insideTable (const DocNodeVariant * n) inline
Definition at line 246 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlTable>(*n)) return TRUE;
    n=parent(n);
  }
  return FALSE;
}
References FALSE, parent(), and TRUE.
Referenced by filterLatexString(), and DocPara::handleHtmlStartTag().
insideUL()
bool insideUL (const DocNodeVariant * n) inline
Returns TRUE iff node n is a child of a unordered html list node
Definition at line 213 of file docparser_p.h.
{
  while (n)
  {
    if (std::holds_alternative<DocHtmlList>(*n) &&
        std::get<DocHtmlList>(*n).type()==DocHtmlList::Unordered)
    {
      return TRUE;
    }
    n=parent(n);
  }
  return FALSE;
}
References FALSE, parent(), TRUE, and DocHtmlList::Unordered.
Referenced by DocPara::handleHtmlEndTag(), and DocPara::handleHtmlStartTag().
isPreformatted()
bool isPreformatted (const DocNodeVariant * n) inline
Definition at line 171 of file docparser_p.h.
{
  return std::visit([](auto &&x)->decltype(auto) { return x.isPreformatted(); }, *n);
}
Referenced by insidePRE().