Doxygen: src/docbookvisitor.cpp File Reference
docbookvisitor.cpp File Reference
#include "docbookvisitor.h"
#include "docparser.h"
#include "language.h"
#include "doxygen.h"
#include "outputgen.h"
#include "docbookgen.h"
#include "dot.h"
#include "message.h"
#include "util.h"
#include "parserintf.h"
#include "filename.h"
#include "config.h"
#include "filedef.h"
#include "msc.h"
#include "dia.h"
#include "htmlentity.h"
#include "emoji.h"
#include "plantuml.h"
#include "growbuf.h"
#include "fileinfo.h"
#include "portable.h"
#include "codefragment.h"
Macros
#define DB_VIS_C
#define DB_VIS_C1(x)
#define DB_VIS_C2(y)
#define DB_VIS_C2a(x, y)
Functions
static QCString filterId (const QCString &s)
static bool supportedHtmlAttribute (const QCString &name)
static QCString makeShortName (const QCString &baseName)
static QCString makeBaseName (const QCString &name)
Macro Definition Documentation
DB_VIS_C
#define DB_VIS_C
Definition at line 45 of file docbookvisitor.cpp.
Referenced by DocbookDocVisitor::DocbookDocVisitor(), DocbookDocVisitor::endDiaFile(), DocbookDocVisitor::endDotFile(), DocbookDocVisitor::endLink(), DocbookDocVisitor::endMscFile(), DocbookDocVisitor::endPlantUmlFile(), DocbookDocVisitor::filter(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::startDiaFile(), DocbookDocVisitor::startDotFile(), DocbookDocVisitor::startLink(), DocbookDocVisitor::startMscFile(), DocbookDocVisitor::startPlantUmlFile(), DocbookDocVisitor::writeDiaFile(), DocbookDocVisitor::writeDotFile(), DocbookDocVisitor::writeMscFile(), and DocbookDocVisitor::writePlantUMLFile().
DB_VIS_C1
#define DB_VIS_C1 (x)
Definition at line 46 of file docbookvisitor.cpp.
DB_VIS_C2
#define DB_VIS_C2 (y)
Definition at line 47 of file docbookvisitor.cpp.
DB_VIS_C2a
#define DB_VIS_C2a (x, y)
Definition at line 48 of file docbookvisitor.cpp.
Function Documentation
filterId()
static QCString filterId (const QCString & s) static
Definition at line 51 of file docbookvisitor.cpp.
{
  if (s.isEmpty()) return s;
  GrowBuf growBuf;
  growBuf.clear();
  const char *p=s.data();
  char c=0;
  while ((c=*p++))
  {
    switch (c)
    {
      case ':':  growBuf.addStr("_1");   break;
      default:   growBuf.addChar(c);       break;
    }
  }
  growBuf.addChar(0);
  return growBuf.get();
}
References GrowBuf::addChar(), GrowBuf::addStr(), GrowBuf::clear(), QCString::data(), GrowBuf::get(), and QCString::isEmpty().
Referenced by DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), and DocbookDocVisitor::operator()().
makeBaseName()
static QCString makeBaseName (const QCString & name) static
Definition at line 97 of file docbookvisitor.cpp.
{
  QCString result = makeShortName(name);
  int i = result.find('.');
  if (i!=-1)
  {
    result=result.left(i);
  }
  return result;
}
References QCString::find(), QCString::left(), and makeShortName().
Referenced by HtmlDocVisitor::operator()(), DocbookDocVisitor::startDiaFile(), LatexDocVisitor::startDiaFile(), DocbookDocVisitor::startDotFile(), LatexDocVisitor::startDotFile(), DocbookDocVisitor::startMscFile(), LatexDocVisitor::startMscFile(), DocbookDocVisitor::startPlantUmlFile(), LatexDocVisitor::startPlantUmlFile(), HtmlDocVisitor::writeDiaFile(), RTFDocVisitor::writeDiaFile(), HtmlDocVisitor::writeDotFile(), RTFDocVisitor::writeDotFile(), HtmlDocVisitor::writeMscFile(), RTFDocVisitor::writeMscFile(), HtmlDocVisitor::writePlantUMLFile(), and RTFDocVisitor::writePlantUMLFile().
makeShortName()
static QCString makeShortName (const QCString & baseName) static
Definition at line 86 of file docbookvisitor.cpp.
{
  QCString result = baseName;
  int i = result.findRev('/');
  if (i!=-1)
  {
    result=result.mid(i+1);
  }
  return result;
}
References QCString::findRev(), and QCString::mid().
Referenced by makeBaseName(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::startPlantUmlFile(), DocbookDocVisitor::writeDiaFile(), LatexDocVisitor::writeDiaFile(), DocbookDocVisitor::writeDotFile(), DocbookDocVisitor::writeMscFile(), LatexDocVisitor::writeMscFile(), DocbookDocVisitor::writePlantUMLFile(), and LatexDocVisitor::writePlantUMLFile().
supportedHtmlAttribute()
static bool supportedHtmlAttribute (const QCString & name) static
Definition at line 70 of file docbookvisitor.cpp.
{
  return (name=="align" ||
          name=="bgcolor" ||
          name=="border" ||
          name=="cellpadding" ||
          name=="cellspacing" ||
          name=="class" ||
          name=="frame" ||
          name=="label" ||
          name=="style" ||
          name=="width" ||
          name=="tabstyle" ||
          name=="title");
}
Referenced by DocbookDocVisitor::operator()(), and DocbookDocVisitor::operator()().