Doxygen: TranslatorSlovak Class Reference
TranslatorSlovak Class Reference
#include <src/translator_sk.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString updateNeededMessage () override
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString updateNeededMessage () override
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 35 of file translator_sk.h.
Member Function Documentation
getLanguageString()
QCString TranslatorSlovak::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 56 of file translator_sk.h.
    {
      return "0x41B Slovak";
    }
idLanguage()
QCString TranslatorSlovak::idLanguage () inline override virtual
Implements Translator.
Definition at line 40 of file translator_sk.h.
    { return "slovak"; }
latexLanguageSupportCommand()
QCString TranslatorSlovak::latexLanguageSupportCommand () inline override virtual
Implements Translator.
Definition at line 43 of file translator_sk.h.
    { return "\\usepackage[slovak]{babel}\n"
             "\\usepackage{regexpatch}\n"
             "\\makeatletter\n"
             "% Change the `-` delimiter to an active character\n"
             "\\xpatchparametertext\\@@@cmidrule{-}{\\cA-}{}{}\n"
             "\\xpatchparametertext\\@cline{-}{\\cA-}{}{}\n"
             "\\makeatother\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorSlovak::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1836 of file translator_sk.h.
    { return "aie zdeden leny"; }
trAll()
QCString TranslatorSlovak::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1338 of file translator_sk.h.
    {
      return "Vetko";
    }
trAndMore()
QCString TranslatorSlovak::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1807 of file translator_sk.h.
    {
        QCString result("a " + number + " a");
        if (number.toInt() >= 5)
            result += "ch";
        return result + "...";
    }
References QCString::toInt().
trAttention()
QCString TranslatorSlovak::trAttention () inline override virtual
Implements Translator.
Definition at line 946 of file translator_sk.h.
    {
      return "Upozornenie";
    }
trAuthor()
QCString TranslatorSlovak::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1211 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "autor", "i");
    }
References Translator::createNoun().
trBug()
QCString TranslatorSlovak::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1110 of file translator_sk.h.
    {
      return "Chyba";
    }
trBugList()
QCString TranslatorSlovak::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1115 of file translator_sk.h.
    {
      return "Zoznam chb";
    }
trCallerGraph()
QCString TranslatorSlovak::trCallerGraph () inline override virtual
Implements Translator.
Definition at line 1462 of file translator_sk.h.
    { return "Tto funkciu volaj..."; }
trCallGraph()
QCString TranslatorSlovak::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1343 of file translator_sk.h.
    {
      return "Tto funkcia vol...";
    }
trCiteReferences()
QCString TranslatorSlovak::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1783 of file translator_sk.h.
    { return "Odkazy na literatru"; }
trClass()
QCString TranslatorSlovak::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1146 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "tried", "y", "a");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorSlovak::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 486 of file translator_sk.h.
    {
      return "Diagram dedinosti pre triedu "+clName;
    }
trClassDocumentation()
QCString TranslatorSlovak::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 380 of file translator_sk.h.
    { return "Dokumentcia tried"; }
trClasses()
QCString TranslatorSlovak::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1079 of file translator_sk.h.
    {
      return "Triedy";
    }
trClassHierarchy()
QCString TranslatorSlovak::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 156 of file translator_sk.h.
    { return "Hierarchia tried"; }
trClassHierarchyDescription()
QCString TranslatorSlovak::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 215 of file translator_sk.h.
    { return "Tu njdete zoznam, vyjadrujci vzah dedinosti tried. "
             "Je zoraden pribline (ale nie plne) poda abecedy:";
    }
trClassMethods()
QCString TranslatorSlovak::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1874 of file translator_sk.h.
    {
      return "Metdy triedy";
    }
trCode()
QCString TranslatorSlovak::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 846 of file translator_sk.h.
    {
      return "zdrojov text";
    }
trCollaborationDiagram()
QCString TranslatorSlovak::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 800 of file translator_sk.h.
    {
      return "Diagram tried pre "+clName+":";
    }
trCompoundIndex()
QCString TranslatorSlovak::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 353 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Register dtovch truktr";
      }
      else
      {
        return "Register tried";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorSlovak::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1518 of file translator_sk.h.
    { return "Register dtovch typov"; }
trCompoundList()
QCString TranslatorSlovak::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 160 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov truktry";
      }
      else
      {
        return "Zoznam tried";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorSlovak::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 230 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Nasledujci zoznam obsahuje identifikciu dtovch "
               "truktr a ich strun popisy:";
      }
      else
      {
        return "Nasledujci zoznam obsahuje predovetkm identifikciu "
               "tried, ale nachdzaj sa tu i alie netrivilne prvky, "
               "ako s truktry (struct), uniony (union) a rozhrania "
               "(interface). V zozname s uveden ich strun "
               "popisy:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorSlovak::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1490 of file translator_sk.h.
    { return "Dtov typy so strunmi popismi:"; }
trCompoundListFortran()
QCString TranslatorSlovak::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1482 of file translator_sk.h.
    { return "Zoznam dtovch typov"; }
trCompoundMembers()
QCString TranslatorSlovak::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 177 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov poloky";
      }
      else
      {
        return "Zoznam lenov tried";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorSlovak::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 248 of file translator_sk.h.
    {
      QCString result= "Tu njdete zoznam vetkch ";
      if (!extractAll)
      {
        result += "dokumentovanch ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result += "poloiek truktr (struct) a unionov (union) ";
      }
      else
      {
        result += "lenov tried ";
      }
      result += "s odkazmi na ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result += "dokumentciu truktr/unionov, ku ktorm prislchaj:";
        }
        else
        {
          result += "dokumentciu tried, ku ktorm prislchaj:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="truktry/uniony, ku ktorm prislchaj:";
        }
        else
        {
          result+="triedy, ku ktorm prislchaj:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorSlovak::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1494 of file translator_sk.h.
    {
      QCString result="Nasleduje zoznam vetkch ";
      if (!extractAll)
      {
        result+="dokumentovanch ";
      }
      result+="zloiek dtovch typov";
      result+=" s odkazmi na ";
      if (!extractAll)
      {
         result+="dokumentciu dtovej truktry pre kad zloku:";
      }
      else
      {
          result+="pslun dtov typy:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorSlovak::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1486 of file translator_sk.h.
    { return "Dtov polia"; }
trCompoundReference()
QCString TranslatorSlovak::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 559 of file translator_sk.h.
    {
      QCString result("Dokumentcia ");
      if (isTemplate) result+="ablny ";
      switch(compType)
      {
        case ClassDef::Class:       result+="triedy "; break;
        case ClassDef::Struct:     result+="truktry "; break;
        case ClassDef::Union:       result+="unionu "; break;
        case ClassDef::Interface:  result+="rozhrania "; break;
        case ClassDef::Protocol:   result+="protokol "; break;
        case ClassDef::Category:   result+="kategria "; break;
        case ClassDef::Exception:  result+="vnimky "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorSlovak::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1559 of file translator_sk.h.
    {
      QCString result("Dokumentcia ");
      if (isTemplate) result += "ablny ";
      switch(compType)
      {
        case ClassDef::Class:      result += "triedy "; break;
        case ClassDef::Struct:     result += "typu "; break;
        case ClassDef::Union:      result += "nie "; break;
        case ClassDef::Interface:  result += "rozhrania "; break;
        case ClassDef::Protocol:   result += "protokolu "; break;
        case ClassDef::Category:   result += "kategrie "; break;
        case ClassDef::Exception:  result += "vnimky "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorSlovak::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 462 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov truktry";
      }
      else
      {
        return "Triedy";
      }
    }
References Config_getBool.
trConstantGroupReference()
QCString TranslatorSlovak::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1911 of file translator_sk.h.
    {
      QCString result="Kontantn skupiny z ";
      result += namespaceName;
      return result;
    }
trConstantGroups()
QCString TranslatorSlovak::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1907 of file translator_sk.h.
    { return "Kontantn skupiny"; }
trConstructorDocumentation()
QCString TranslatorSlovak::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 811 of file translator_sk.h.
    {
      return "Dokumentcia kontruktoru a detruktoru";
    }
trCopyright()
QCString TranslatorSlovak::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1787 of file translator_sk.h.
    { return "Copyright"; }
trDataTypes()
QCString TranslatorSlovak::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1542 of file translator_sk.h.
    { return "Dtov typy"; }
trDate()
QCString TranslatorSlovak::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 500 of file translator_sk.h.
    { return "Dtum"; }
trDateTime()
QCString TranslatorSlovak::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1736 of file translator_sk.h.
    {
      static const char *days[]   = { "po","ut","st","t","pi","so","ne" };
      static const char *months[] = { "jan","feb","mar","apr","mj","jn","jl","aug","sep","okt","nov","dec" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %d. %s %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d.%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorSlovak::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1756 of file translator_sk.h.
    {
      static const char *days_short[]   = { "po", "ut", "st", "t", "pi", "so", "ne" };
      static const char *days_full[]    = { "pondelok", "utorok", "streda", "tvrtok", "piatok", "sobota", "nedea" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorSlovak::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1772 of file translator_sk.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorSlovak::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 777 of file translator_sk.h.
    {
      return "Defincia je uveden na riadku @0 v sbore @1.";
    }
trDefinedIn()
QCString TranslatorSlovak::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 144 of file translator_sk.h.
    { return "definovan v"; }
trDefinedInSourceFile()
QCString TranslatorSlovak::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 781 of file translator_sk.h.
    {
      return "Defincia v sbore @0.";
    }
trDefineDocumentation()
QCString TranslatorSlovak::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 432 of file translator_sk.h.
    { return "Dokumentcia k defincim makier"; }
trDefines()
QCString TranslatorSlovak::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 396 of file translator_sk.h.
    { return "Defincia makier"; }
trDefineValue()
QCString TranslatorSlovak::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1100 of file translator_sk.h.
    {
      return "Hodnota:";
    }
trDeprecated()
QCString TranslatorSlovak::trDeprecated () inline override virtual
Implements Translator.
Definition at line 790 of file translator_sk.h.
    {
      return "Zastaral";
    }
trDeprecatedList()
QCString TranslatorSlovak::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1266 of file translator_sk.h.
    {
      return "Zastaran metdy";
    }
trDetailedDescription()
QCString TranslatorSlovak::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 71 of file translator_sk.h.
    { return "Detailn popis"; }
trDetailLevel()
QCString TranslatorSlovak::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1799 of file translator_sk.h.
    { return "rove detailov"; }
trDetails()
QCString TranslatorSlovak::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 75 of file translator_sk.h.
    { return "Podrobnosti"; }
trDir()
QCString TranslatorSlovak::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1439 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "adresr", "e");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorSlovak::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1791 of file translator_sk.h.
    { return QCString("Graf zvislosti na prieinkoch pre  ")+name+":"; }
trDirDocumentation()
QCString TranslatorSlovak::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1417 of file translator_sk.h.
    { return "Dokumentcia k adresrom"; }
trDirectories()
QCString TranslatorSlovak::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1423 of file translator_sk.h.
    { return "Adresre"; }
trDirIndex()
QCString TranslatorSlovak::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1411 of file translator_sk.h.
    { return "Hierarchia adresrov"; }
trDirReference()
QCString TranslatorSlovak::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1429 of file translator_sk.h.
    {
        QCString result = "Referencia k adresru ";
        result += dirName;
        return result;
    }
trDirRelation()
QCString TranslatorSlovak::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1675 of file translator_sk.h.
    {
      return "Relcia " + QCString(name);
    }
trDocumentation()
QCString TranslatorSlovak::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 335 of file translator_sk.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentcia"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorSlovak::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 408 of file translator_sk.h.
    { return "Enumercie"; }
trEnumerationTypeDocumentation()
QCString TranslatorSlovak::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 444 of file translator_sk.h.
    { return "Dokumentcia enumeranch typov"; }
trEnumerationValueDocumentation()
QCString TranslatorSlovak::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1469 of file translator_sk.h.
    { return "Dokumentcia enumeranch hodnt"; }
trEnumerationValues()
QCString TranslatorSlovak::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 426 of file translator_sk.h.
    { return "Hodnoty enumerci"; }
trEnumGeneratedFromFiles()
QCString TranslatorSlovak::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1816 of file translator_sk.h.
    { QCString result = "Dokumentcia pre tuto enumerciu bola generovan z ";
      if (single)
          result += "nasledujceho sboru:";
      else
          result += "nasledujcich sborov:";
      return result;
    }
trEnumName()
QCString TranslatorSlovak::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 136 of file translator_sk.h.
    { return "meno enumercie"; }
trEnumReference()
QCString TranslatorSlovak::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1826 of file translator_sk.h.
    { return "Referencia k enumercii "+QCString(name); }
trEnumValue()
QCString TranslatorSlovak::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 140 of file translator_sk.h.
    { return "hodnota enumercie"; }
trEventDocumentation()
QCString TranslatorSlovak::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1283 of file translator_sk.h.
    {
      return "Dokumentcia udalost";
    }
trEvents()
QCString TranslatorSlovak::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1278 of file translator_sk.h.
    {
      return "Udalosti";
    }
trExamples()
QCString TranslatorSlovak::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 207 of file translator_sk.h.
    { return "Prklady"; }
trExamplesDescription()
QCString TranslatorSlovak::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 319 of file translator_sk.h.
    { return "Tu njdete zoznam vetkch prkladov:"; }
trExceptions()
QCString TranslatorSlovak::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 516 of file translator_sk.h.
    { return "Vnimky"; }
trExtendsClass()
QCString TranslatorSlovak::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1866 of file translator_sk.h.
    {
      return "Roziruje triedu @0.";
    }
trFile()
QCString TranslatorSlovak::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1155 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "sbor", "y");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorSlovak::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 386 of file translator_sk.h.
    { return "Dokumentcia sborov"; }
trFileIn()
QCString TranslatorSlovak::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1712 of file translator_sk.h.
    {
      return "Sbor v "+name;
    }
trFileIndex()
QCString TranslatorSlovak::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 368 of file translator_sk.h.
    { return "Register sborov"; }
trFileList()
QCString TranslatorSlovak::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 173 of file translator_sk.h.
    { return "Zoznam sborov"; }
trFileListDescription()
QCString TranslatorSlovak::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 221 of file translator_sk.h.
    {
        QCString result("Tu njdete zoznam vetkch ");
        if (!extractAll) result+="dokumentovanch ";
        result+="sborov so strunmi popismi:";
        return result;
    }
trFileMembers()
QCString TranslatorSlovak::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 190 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globlne symboly";
      }
      else
      {
        return "Symboly v sboroch";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorSlovak::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 294 of file translator_sk.h.
    {
      QCString result="Tu njdete zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkci, premennch, makier, enumerci a definci typov (typedef) "
                "s odkazmi na ";
      }
      else
      {
        result+="symbolov, ktor s definovan na rovni svojich sborov. "
                "Pre kad symbol je uveden odkaz na ";
      }
      if (extractAll)
        result+="sbory, ku ktorm prislchaj:";
      else
        result+="dokumentciu:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorSlovak::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 581 of file translator_sk.h.
    {
      QCString result("Dokumentcia sboru ");
      result+=fileName;
      return result;
    }
trFriends()
QCString TranslatorSlovak::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 541 of file translator_sk.h.
    { return "Priatelia (friends)"; }
trFunctionDocumentation()
QCString TranslatorSlovak::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 450 of file translator_sk.h.
    { return "Dokumentcia funkci"; }
trFunctions()
QCString TranslatorSlovak::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 414 of file translator_sk.h.
    { return "Funkcie"; }
trGeneratedAt()
QCString TranslatorSlovak::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 477 of file translator_sk.h.
    {
      QCString result="Generovan "+date;
      if (!projName.isEmpty()) result+=" pre projekt "+projName;
      result+=" programom";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorSlovak::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 126 of file translator_sk.h.
    { QCString result("Generovan automaticky programom Doxygen "
                      "zo zdrojovch textov");
      if (!s.isEmpty())
          result+=" projektu "+s;
      result+=".";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorSlovak::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 520 of file translator_sk.h.
    { return "Generovan programom"; }
trGeneratedFromFiles()
QCString TranslatorSlovak::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 732 of file translator_sk.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentcia pre ";
      switch(compType)
      {
        case ClassDef::Class:       result+="tto triedu"; break;
        case ClassDef::Struct:     result+="tto truktru (struct)"; break;
        case ClassDef::Union:       result+="tento union"; break;
        case ClassDef::Interface:  result+="toto rozhranie"; break;
        case ClassDef::Protocol:   result+="protokol"; break;
        case ClassDef::Category:   result+="kategria"; break;
        case ClassDef::Exception:  result+="tto vnimku"; break;
        default: break;
      }
      result+=" bola generovan z ";
      if (single) result+="nasledujceho sboru:";
      else                result+="nasledujcich sborov:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorSlovak::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1626 of file translator_sk.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentcia ";
      switch(compType)
      {
        case ClassDef::Class:      result+="k tomuto modulu"; break;
        case ClassDef::Struct:     result+="k tomuto typu"; break;
        case ClassDef::Union:      result+="k tejto nii"; break;
        case ClassDef::Interface:  result+="k tomuto rozhraniu"; break;
        case ClassDef::Protocol:   result+="k tomuto protokolu"; break;
        case ClassDef::Category:   result+="k tejto kategrii"; break;
        case ClassDef::Exception:  result+="k tejto vnimke"; break;
        default: break;
      }
      result+=" bola vygenerovan z ";
      if (single) result+="nasledujceho sboru:";
      else result+="nasledujcich sborov:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorSlovak::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1200 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "globln", "e", "y");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorSlovak::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1687 of file translator_sk.h.
    {
      return "Globlny priestor mien";
    }
trGotoDocumentation()
QCString TranslatorSlovak::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 821 of file translator_sk.h.
    {
      return "Zobrazi dokumentciu tohoto sboru.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorSlovak::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 854 of file translator_sk.h.
    {
      return "Zobrazi grafick podobu hierarchie tried";
    }
trGotoSourceCode()
QCString TranslatorSlovak::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 816 of file translator_sk.h.
    {
      return "Zobrazi zdrojov text tohoto sboru.";
    }
trGotoTextualHierarchy()
QCString TranslatorSlovak::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 858 of file translator_sk.h.
    {
      return "Zobrazi textov podobu hierarchie tried";
    }
trGraphicalHierarchy()
QCString TranslatorSlovak::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 850 of file translator_sk.h.
    {
      return "Grafick zobrazenie hierarchie tried";
    }
trGroup()
QCString TranslatorSlovak::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1173 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "skupin", "y", "a");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorSlovak::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 347 of file translator_sk.h.
    { return "Register hierarchie tried"; }
trImplementedFromList()
QCString TranslatorSlovak::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1234 of file translator_sk.h.
    {
      return "Implementuje " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorSlovak::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this member.
Implements Translator.
Definition at line 1242 of file translator_sk.h.
    {
      return "Implementovan v " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorSlovak::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 950 of file translator_sk.h.
    {
      return "Nasledujci graf ukazuje, ktor sbory priamo alebo "
             "nepriamo vkladaj tento sbor:";
    }
trInclDepGraph()
QCString TranslatorSlovak::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 805 of file translator_sk.h.
    {
      return "Graf zvislost na vkladanch sboroch "
                    "pre "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorSlovak::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1721 of file translator_sk.h.
    {
      return "Vklad (include) sbor z "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorSlovak::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 120 of file translator_sk.h.
    { return ", vrtane vetkch zdedench lenov."; }
trInheritedByList()
QCString TranslatorSlovak::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 656 of file translator_sk.h.
    {
      QCString result("Zdeden ");
      result += (numEntries == 1) ? "triedou " : "triedami ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorSlovak::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1830 of file translator_sk.h.
    { return QCString(members)+" ded sa z "+what; }
trInheritsList()
QCString TranslatorSlovak::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 645 of file translator_sk.h.
    {
      QCString result("Ded od ");
      result += (numEntries == 1) ? "bzovej triedy " : "bzovch tried ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trInitialValue()
QCString TranslatorSlovak::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 841 of file translator_sk.h.
    {
      return "Inicializtor:";
    }
trInstanceMethods()
QCString TranslatorSlovak::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1882 of file translator_sk.h.
    {
      return "Metdy intancie";
    }
trInterfaces()
QCString TranslatorSlovak::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1899 of file translator_sk.h.
    { return "Exportovan rozhrania"; }
trInvariant()
QCString TranslatorSlovak::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 836 of file translator_sk.h.
    {
      return "Invariant";
    }
trISOLang()
QCString TranslatorSlovak::trISOLang () inline override virtual
Implements Translator.
Definition at line 52 of file translator_sk.h.
    {
      return "sk";
    }
trLegend()
QCString TranslatorSlovak::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1039 of file translator_sk.h.
    {
      return "vysvetlivky";
    }
trLegendDocs()
QCString TranslatorSlovak::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 970 of file translator_sk.h.
    {
      return
        "Tu njdete vysvetlenie, ako maj by interpretovan grafy, "
        "ktor boli generovan programom doxygen.<p>\n"
        "Uvaujte nasledujci prklad:\n"
        "\\code\n"
        "/*! Neviditeln trieda, ktor sa v grafe nezobrazuje, pretoe "
        "dolo k orezaniu grafu. */\n"
        "class Invisible { };\n\n"
        "/*! Trieda, u ktorej dolo k orezaniu grafu. Vzah dedinosti "
        "je skryt. */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Trieda, ktor nieje dokumentovan komentrmi programu doxygen. */\n"
        "class Undocumented { };\n\n"
        "/*! Odvoden trieda s verejnm (public) dedenm bzovej triedy. */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! ablna triedy. */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Odvoden trieda s chrnenm (protected) dedenm bzovej triedy. */\n"
        "class ProtectedBase { };\n\n"
        "/*! Odvoden trieda s privtnym dedenm bzovej triedy. */\n"
        "class PrivateBase { };\n\n"
        "/*! Trieda, ktor je vyuvan triedou Inherited. */\n"
        "class Used { };\n\n"
        "/*! Odvoden trieda, ktor rznym spsobom ded od viacerch bzovch "
        "tried. */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "        Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "K vyie uvedenmu bude vygenerovan nasledujci graf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Bloky (tj. uzly) v uvedenom grafe maj nasledujci vznam:\n"
        "<ul>\n"
        "<li>ierne vyplnen obdnik reprezentuje truktru alebo triedu, "
            "pre ktor bol graf generovan.\n"
        "<li>Obdnik s iernym obrysom oznauje dokumentovan "
            "truktru alebo triedu.\n"
        "<li>Obdnik so edm obrysom oznauje nedokumentovan "
            "truktru alebo triedu.\n"
        "<li>Obdnik s ervenm obrysom oznauje dokumentovan "
            "truktru alebo triedu, pre ktor\n"
            "nies zobrazen vetky vzahy dedinosti alebo obsiahnutia. "
            "Graf je orezan v prpade, kedy ho\n"
            "nieje mon umiestni do vymedzench hranc.\n"
        "</ul>\n"
        "pky (tj. hrany grafu) maj nasledujc vznam:\n"
        "<ul>\n"
        "<li>Tmavo modr pka sa pouva pre oznaenie vzahu verejnej "
            "dedinosti medzi dvoma triedami.\n"
        "<li>Tmavo zelen pka oznauje vzah chrnenej dedinosti "
            "(protected).\n"
        "<li>Tmavo erven pka oznauje vzah privtnej dedinosti.\n"
        "<li>Purpurov pka kreslen iarkovane sa pouva v prpade, "
            "ak je trieda obsiahnut v inej triede,\n"
            "alebo ak je pouvan inou triedou. Je oznaen identifiktorom "
            "jednej alebo viacerch premennch (objektov), cez ktor\n"
            "je trieda alebo truktra zprstupnena.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorSlovak::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 965 of file translator_sk.h.
    {
      return "Vysvetlivky ku grafu";
    }
trListOfAllMembers()
QCString TranslatorSlovak::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 108 of file translator_sk.h.
    { return "Zoznam vetkch lenov"; }
trLoading()
QCString TranslatorSlovak::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1681 of file translator_sk.h.
    {
      return "Natam...";
    }
trMainPage()
QCString TranslatorSlovak::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 764 of file translator_sk.h.
    { return "Hlavn strnka"; }
trMember()
QCString TranslatorSlovak::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1191 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "len", "y");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorSlovak::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 91 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentcia k polokm";
      }
      else
      {
        return "Dokumentcia k dtovm lenom";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorSlovak::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 83 of file translator_sk.h.
    { return "Dokumentcia k lenskm enumercim"; }
trMemberFunctionDocumentation()
QCString TranslatorSlovak::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 87 of file translator_sk.h.
    { return "Dokumentcia k metdam"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorSlovak::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1478 of file translator_sk.h.
    { return "Dokumentcia lenskch funkci/podprogramov"; }
trMemberList()
QCString TranslatorSlovak::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 112 of file translator_sk.h.
    { return "Zoznam lenov triedy"; }
trMemberTypedefDocumentation()
QCString TranslatorSlovak::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 79 of file translator_sk.h.
    { return "Dokumentcia k lenskm typom"; }
trMethodDocumentation()
QCString TranslatorSlovak::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1889 of file translator_sk.h.
    {
      return "Dokumentcia metdy";
    }
trModule()
QCString TranslatorSlovak::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1619 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "modul", "y");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorSlovak::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 374 of file translator_sk.h.
    { return "Dokumentcia modulov"; }
trModuleIndex()
QCString TranslatorSlovak::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 341 of file translator_sk.h.
    { return "Register modulov"; }
trModuleReference()
QCString TranslatorSlovak::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1581 of file translator_sk.h.
    {
      QCString result="Dokumentcia modulu ";
      result += namespaceName;
      return result;
    }
trModules()
QCString TranslatorSlovak::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 152 of file translator_sk.h.
    { return "Moduly"; }
trModulesDescription()
QCString TranslatorSlovak::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 329 of file translator_sk.h.
    { return "Tu njdete zoznam vetkch modulov:"; }
trModulesIndex()
QCString TranslatorSlovak::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1612 of file translator_sk.h.
    { return "Register modulov"; }
trModulesList()
QCString TranslatorSlovak::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1546 of file translator_sk.h.
    { return "Zoznam modulov"; }
trModulesListDescription()
QCString TranslatorSlovak::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1550 of file translator_sk.h.
    {
      QCString result="Nasleduje zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="modulov so strunmi popismi:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorSlovak::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1593 of file translator_sk.h.
    {
      QCString result="Nasleduje zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="ast modulov s odkazmi ";
      if (extractAll)
      {
        result+="na dokumentciu modulov pre dan as:";
      }
      else
      {
        result+="na moduly, ku ktorm as patr:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorSlovak::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1589 of file translator_sk.h.
    { return "asti modulu"; }
trMonth()
QCString TranslatorSlovak::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1764 of file translator_sk.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "mj", "jn", "jl", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[]  = { "janur", "februr", "marec", "aprl", "mj", "jn", "jl", "august", "september", "oktber", "november", "december" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorSlovak::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 104 of file translator_sk.h.
    { return "..."; }
trNamespace()
QCString TranslatorSlovak::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1164 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "priestor", "y") + " mien";
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorSlovak::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 712 of file translator_sk.h.
    { return "Dokumentcia priestorov mien"; }
trNamespaceIndex()
QCString TranslatorSlovak::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 706 of file translator_sk.h.
    { return "Register priestorov mien"; }
trNamespaceList()
QCString TranslatorSlovak::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 526 of file translator_sk.h.
    { return "Zoznam priestorov mien"; }
trNamespaceListDescription()
QCString TranslatorSlovak::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 530 of file translator_sk.h.
    {
      QCString result="Tu njdete zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="priestorov mien so strunm popisom:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorSlovak::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 691 of file translator_sk.h.
    {
      QCString result="Tu njdete zoznam vetkch ";
      if (!extractAll) result+="dokumentovanch ";
      result+="symbolov, ktor s definovan vo svojich priestoroch mien. "
              "U kadho je uveden odkaz na ";
      if (extractAll)
        result+="dokumentciu prslunho priestoru mien:";
      else
        result+="prslun priestor mien:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorSlovak::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 687 of file translator_sk.h.
    { return "Symboly v priestoroch mien"; }
trNamespaceReference()
QCString TranslatorSlovak::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 589 of file translator_sk.h.
    {
      QCString result("Dokumentcia priestoru mien ");
      result+=namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorSlovak::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 722 of file translator_sk.h.
    { return "Priestory mien"; }
trNoMatches()
QCString TranslatorSlovak::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1699 of file translator_sk.h.
    {
      return "Ni sa nenalo";
    }
trNote()
QCString TranslatorSlovak::trNote () inline override virtual
Implements Translator.
Definition at line 871 of file translator_sk.h.
    {
      return "Poznmka";
    }
trOverloadText()
QCString TranslatorSlovak::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1451 of file translator_sk.h.
    {
       return "Ide o preaen (overloaded) metdu, "
              "ktor m uahi pouvanie. Od vyie uvedenej metdy sa odliuje "
              "iba inak zadvanmi argumentami.";
    }
trPackage()
QCString TranslatorSlovak::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1084 of file translator_sk.h.
    {
      return "Balk "+name;
    }
trPackageAttribs()
QCString TranslatorSlovak::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1319 of file translator_sk.h.
    {
      return "Atribty balku";
    }
trPackageFunctions()
QCString TranslatorSlovak::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1301 of file translator_sk.h.
    {
      return "Funkcie v balku";
    }
trPackageListDescription()
QCString TranslatorSlovak::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1089 of file translator_sk.h.
    {
      return "Tu njdete zoznam balkov so strunm popisom "
             "(pokia bol uveden):";
    }
trPackageMembers()
QCString TranslatorSlovak::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1305 of file translator_sk.h.
    {
      return "leny v balku";
    }
trPackages()
QCString TranslatorSlovak::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1095 of file translator_sk.h.
    {
      return "Balky";
    }
trPackageTypes()
QCString TranslatorSlovak::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1294 of file translator_sk.h.
    {
      return "Typy v balku";
    }
trPage()
QCString TranslatorSlovak::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1182 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "strnk", "y", "a");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorSlovak::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 770 of file translator_sk.h.
    { return "s."; }
trPageIndex()
QCString TranslatorSlovak::trPageIndex () inline override virtual
Implements Translator.
Definition at line 862 of file translator_sk.h.
    {
      return "Register strnok";
    }
trPanelSynchronisationTooltip()
QCString TranslatorSlovak::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1847 of file translator_sk.h.
    {
      QCString opt = enable ? "povoli" : "zakza";
      return opt + " synchronizciu panelov";
    }
trParameters()
QCString TranslatorSlovak::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 512 of file translator_sk.h.
    { return "Parametre"; }
trPostcondition()
QCString TranslatorSlovak::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 831 of file translator_sk.h.
    {
      return "Postpodmienka";
    }
trPrecondition()
QCString TranslatorSlovak::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 826 of file translator_sk.h.
    {
      return "Prepodmienka";
    }
trPrivateAttribs()
QCString TranslatorSlovak::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 910 of file translator_sk.h.
    {
      return "Privtne atribty";
    }
trPrivateMembers()
QCString TranslatorSlovak::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 611 of file translator_sk.h.
    { return "Privtne metdy"; }
trPrivateSlots()
QCString TranslatorSlovak::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 613 of file translator_sk.h.
    { return "Privtne sloty"; }
trPrivateTypes()
QCString TranslatorSlovak::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 906 of file translator_sk.h.
    {
      return "Privtne typy";
    }
trProperties()
QCString TranslatorSlovak::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1065 of file translator_sk.h.
    {
      return "Vlastnosti";
    }
trPropertyDocumentation()
QCString TranslatorSlovak::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1070 of file translator_sk.h.
    {
      return "Dokumentcia k vlastnosti";
    }
trProtectedAttribs()
QCString TranslatorSlovak::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 898 of file translator_sk.h.
    {
      return "Chrnen atribty";
    }
trProtectedMembers()
QCString TranslatorSlovak::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 605 of file translator_sk.h.
    { return "Chrnen metdy"; }
trProtectedSlots()
QCString TranslatorSlovak::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 607 of file translator_sk.h.
    { return "Chrnen sloty"; }
trProtectedTypes()
QCString TranslatorSlovak::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 894 of file translator_sk.h.
    {
      return "Chrnen typy";
    }
trProvidedByCategory()
QCString TranslatorSlovak::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1857 of file translator_sk.h.
    {
      return "Deklarovan v kategrii @0.";
    }
trPublicAttribs()
QCString TranslatorSlovak::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 879 of file translator_sk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dtov poloky";
      }
      else
      {
        return "Verejn atribty";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorSlovak::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 597 of file translator_sk.h.
    { return "Verejn metdy"; }
trPublicSlots()
QCString TranslatorSlovak::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 599 of file translator_sk.h.
    { return "Verejn sloty"; }
trPublicTypes()
QCString TranslatorSlovak::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 875 of file translator_sk.h.
    {
      return "Verejn typy";
    }
trReferencedBy()
QCString TranslatorSlovak::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 938 of file translator_sk.h.
    {
      return "Pouva sa v";
    }
trReferenceManual()
QCString TranslatorSlovak::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 390 of file translator_sk.h.
    { return "Referenn prruka"; }
trReferences()
QCString TranslatorSlovak::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1222 of file translator_sk.h.
    {
      return "Odkazuje sa na";
    }
trReimplementedFromList()
QCString TranslatorSlovak::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 667 of file translator_sk.h.
    {
      QCString result("Reimplementuje ");
      result += (numEntries == 1) ? "metdu triedy " : "metdy tried ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorSlovak::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 678 of file translator_sk.h.
    {
      QCString result("Reimplementovan ");
      result += (numEntries == 1) ? "triedou " : "triedami ";
      result += trWriteList(numEntries)+".";
      return result;
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorSlovak::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 551 of file translator_sk.h.
    { return "Dokumentcia k priateom (friends)"; }
trRelatedFunctions()
QCString TranslatorSlovak::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 63 of file translator_sk.h.
    { return "Svisiace funkcie"; }
trRelatedPages()
QCString TranslatorSlovak::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 203 of file translator_sk.h.
    { return "Ostatn strnky"; }
trRelatedPagesDescription()
QCString TranslatorSlovak::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 323 of file translator_sk.h.
    { return "Nasledujci zoznam odkazuje na alie strnky projektu, "
             "ktor maj charakter usporiadanch zoznamov informci, "
             "pozbieranch z rznych miest v zdrojovch sboroch:"; }
trRelatedSubscript()
QCString TranslatorSlovak::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 67 of file translator_sk.h.
    { return "(Uveden funkcie nies lenskmi funkciami.)"; }
trRemarks()
QCString TranslatorSlovak::trRemarks () inline override virtual
Implements Translator.
Definition at line 942 of file translator_sk.h.
    {
      return "Poznmky";
    }
trReturns()
QCString TranslatorSlovak::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 504 of file translator_sk.h.
    { return "Nvratov hodnota"; }
trReturnValues()
QCString TranslatorSlovak::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 759 of file translator_sk.h.
    { return "Nvratov hodnoty"; }
trRTFansicp()
QCString TranslatorSlovak::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1125 of file translator_sk.h.
    {
      return "1250";
    }
trRTFCharSet()
QCString TranslatorSlovak::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1131 of file translator_sk.h.
    {
      return "238";
    }
trRTFGeneralIndex()
QCString TranslatorSlovak::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1137 of file translator_sk.h.
    {
      return "Index";
    }
trRTFTableOfContents()
QCString TranslatorSlovak::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1254 of file translator_sk.h.
    {
      return "Obsah";
    }
trSearch()
QCString TranslatorSlovak::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 211 of file translator_sk.h.
    { return "Hada"; }
trSearching()
QCString TranslatorSlovak::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1693 of file translator_sk.h.
    {
      return "Vyhadvam...";
    }
trSearchMatches()
QCString TranslatorSlovak::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1386 of file translator_sk.h.
    {
      return "Njden slov:";
    }
trSearchResults()
QCString TranslatorSlovak::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1367 of file translator_sk.h.
    {
      if (numDocuments==0)
      {
        return "utujem. Vmu dotazu neodpoved iadny dokument.";
      }
      else if (numDocuments==1)
      {
        return "Bol njden jedin dokument, ktor vyhovuje vmu dotazu.";
      }
      else
      {
        return "Bolo njdench <b>$num</b> dokumentov, ktor vyhovuj vmu "
                      "dotazu. Najviac odpovedajce dokumenty s ako prv.";
      }
    }
trSearchResultsTitle()
QCString TranslatorSlovak::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1355 of file translator_sk.h.
    {
      return "Vsledky vyhadvania";
    }
trSeeAlso()
QCString TranslatorSlovak::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 508 of file translator_sk.h.
    { return "Viz tie"; }
trServiceGeneratedFromFiles()
QCString TranslatorSlovak::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 1932 of file translator_sk.h.
    {
      // single is true implies a single file
      QCString result="Dokumentcia k tejto slube bola vygenerovan ";
      if (single) result+="z nasledujceho sboru:";
      else        result+="z nasledujcich sborov:";
      return result;
    }
trServiceReference()
QCString TranslatorSlovak::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 1918 of file translator_sk.h.
    {
      QCString result="Popis sluby ";
      result += sName;
      return result;
    }
trServices()
QCString TranslatorSlovak::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1903 of file translator_sk.h.
    { return "Zalenen sluby"; }
trSignals()
QCString TranslatorSlovak::trSignals () inline override virtual
Implements Translator.
Definition at line 601 of file translator_sk.h.
    { return "Signly"; }
trSince()
QCString TranslatorSlovak::trSince () inline override virtual
Implements Translator.
Definition at line 955 of file translator_sk.h.
    {
      return "Od";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorSlovak::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 1941 of file translator_sk.h.
    {
      // single is true implies a single file
      QCString result="Dokumentcia k tomuto singletonu bola vygenerovan ";
      if (single) result+="z nasledujceho sboru:";
      else        result+="z nasledujcich sborov:";
      return result;
    }
trSingletonReference()
QCString TranslatorSlovak::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 1925 of file translator_sk.h.
    {
      QCString result="Popis singletonu ";
      result += sName;
      return result;
    }
trSourceFile()
QCString TranslatorSlovak::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1397 of file translator_sk.h.
    {
      return QCString("Zdrojov sbor ") + filename;
    }
trStaticPackageAttribs()
QCString TranslatorSlovak::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1326 of file translator_sk.h.
    {
      return "Statick atribty balku";
    }
trStaticPackageFunctions()
QCString TranslatorSlovak::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1312 of file translator_sk.h.
    {
      return "Statick funkcie v balku";
    }
trStaticPrivateAttribs()
QCString TranslatorSlovak::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 914 of file translator_sk.h.
    {
      return "Statick privtne atribty";
    }
trStaticPrivateMembers()
QCString TranslatorSlovak::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 615 of file translator_sk.h.
    { return "Statick privtne metdy"; }
trStaticProtectedAttribs()
QCString TranslatorSlovak::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 902 of file translator_sk.h.
    {
      return "Statick chrnen atribty";
    }
trStaticProtectedMembers()
QCString TranslatorSlovak::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 609 of file translator_sk.h.
    { return "Statick chrnen metdy"; }
trStaticPublicAttribs()
QCString TranslatorSlovak::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 890 of file translator_sk.h.
    {
      return "Statick verejn atribty";
    }
trStaticPublicMembers()
QCString TranslatorSlovak::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 603 of file translator_sk.h.
    { return "Statick verejn metdy"; }
trSubprogram()
QCString TranslatorSlovak::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1659 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "podprogram", "y");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorSlovak::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1536 of file translator_sk.h.
    { return "Dokumentcia funkcie/podprogramu"; }
trSubprograms()
QCString TranslatorSlovak::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1530 of file translator_sk.h.
    { return "Funkcie/podprogramy"; }
trTemplateParameters()
QCString TranslatorSlovak::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1803 of file translator_sk.h.
    { return "Parametry abln"; }
trTest()
QCString TranslatorSlovak::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1049 of file translator_sk.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorSlovak::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1055 of file translator_sk.h.
    {
      return "Zoznam testov";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorSlovak::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 116 of file translator_sk.h.
    { return "Tu njdete pln zoznam lenov triedy"; }
trTodo()
QCString TranslatorSlovak::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 924 of file translator_sk.h.
    {
      return "Plnovan pravy";
    }
trTodoList()
QCString TranslatorSlovak::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 929 of file translator_sk.h.
    {
      return "Zoznam plnovanch prav";
    }
trType()
QCString TranslatorSlovak::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1651 of file translator_sk.h.
    {
      return createNoun(first_capital, singular, "typ", "y");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorSlovak::trTypeConstraints () inline override virtual
C# Type Contraint list
Implements Translator.
Definition at line 1665 of file translator_sk.h.
    {
      return "Obmedzenie typov (Type Constraints)";
    }
trTypedefDocumentation()
QCString TranslatorSlovak::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 438 of file translator_sk.h.
    { return "Dokumentcia definci typov"; }
trTypedefs()
QCString TranslatorSlovak::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 402 of file translator_sk.h.
    { return "Defincia typov"; }
trTypeDocumentation()
QCString TranslatorSlovak::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1524 of file translator_sk.h.
    { return "Dokumentcia k dtovm typom"; }
trVariableDocumentation()
QCString TranslatorSlovak::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 456 of file translator_sk.h.
    { return "Dokumentcia premennch"; }
trVariables()
QCString TranslatorSlovak::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 420 of file translator_sk.h.
    { return "Premenn"; }
trVersion()
QCString TranslatorSlovak::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 496 of file translator_sk.h.
    { return "Verzia"; }
trWarning()
QCString TranslatorSlovak::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 492 of file translator_sk.h.
    { return "Pozor"; }
trWriteList()
QCString TranslatorSlovak::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 621 of file translator_sk.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                            // the fore last entry
            result+=" a ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_sk.h