Doxygen: /home/runner/work/doxygen/doxygen/src/conceptdef.cpp File Reference
conceptdef.cpp File Reference
#include "conceptdef.h"
#include "definitionimpl.h"
#include "util.h"
#include "config.h"
#include "doxygen.h"
#include "language.h"
#include "outputlist.h"
#include "searchindex.h"
#include "message.h"
#include "parserintf.h"
#include "layout.h"
#include "namespacedef.h"
Classes
class ConceptDefImpl
class ConceptDefAliasImpl
Functions
std::unique_ptr< ConceptDef > createConceptDef (const QCString &fileName, int startLine, int startColumn, const QCString &name, const QCString &tagRef, const QCString &tagFile)
std::unique_ptr< ConceptDef > createConceptDefAlias (const Definition *newScope, const ConceptDef *cd)
static QCString templateSpec (const ArgumentList &al)
ConceptDef * toConceptDef (Definition *d)
ConceptDef * toConceptDef (DefinitionMutable *md)
const ConceptDef * toConceptDef (const Definition *d)
ConceptDefMutable * toConceptDefMutable (Definition *d)
ConceptDefMutable * toConceptDefMutable (const Definition *d)
ConceptDef * getConcept (const QCString &n)
ConceptDef * getResolvedConcept (const Definition *d, const QCString &name)
Function Documentation
createConceptDef()
std::unique_ptr< ConceptDef > createConceptDef (const QCString & fileName, int startLine, int startColumn, const QCString & name, const QCString & tagRef, const QCString & tagFile)
Definition at line 87 of file conceptdef.cpp.
{
  return std::make_unique<ConceptDefImpl>(fileName,startLine,startColumn,name,tagRef,tagFile);
}
Referenced by addConceptToContext().
createConceptDefAlias()
std::unique_ptr< ConceptDef > createConceptDefAlias (const Definition * newScope, const ConceptDef * cd)
Definition at line 144 of file conceptdef.cpp.
{
  return std::make_unique<ConceptDefAliasImpl>(newScope,cd);
}
getConcept()
ConceptDef * getConcept (const QCString & n)
Definition at line 754 of file conceptdef.cpp.
{
  if (n.isEmpty()) return 0;
  return Doxygen::conceptLinkedMap->find(n);
}
References Doxygen::conceptLinkedMap, LinkedMap< T, Hash, KeyEqual, Map >::find(), and QCString::isEmpty().
Referenced by getConceptMutable(), getResolvedConcept(), if(), and resolveLink().
getResolvedConcept()
ConceptDef * getResolvedConcept (const Definition * d, const QCString & name)
Definition at line 760 of file conceptdef.cpp.
{
  ConceptDef *cd=0;
  while (d && d!=Doxygen::globalScope)
  {
    cd = getConcept(d->name()+"::"+name);
    if (cd) return cd;
    d = d->getOuterScope();
  }
  cd = getConcept(name);
  return cd;
}
References getConcept(), Definition::getOuterScope(), Doxygen::globalScope, and Definition::name().
Referenced by generateClassOrGlobalLink().
templateSpec()
static QCString templateSpec (const ArgumentList & al) static
Definition at line 380 of file conceptdef.cpp.
{
  TextStream t;
  t << "template<";
  bool first=true;
  for (const auto &a : al)
  {
    if (!first) t << ", ";
    t << a.type;
    if (!a.name.isEmpty())
    {
      t << " " << a.name;
    }
    if (a.defval.length()!=0)
    {
      t << " " << a.defval;
    }
    first=false;
  }
  t << ">";
  return t.str();
}
References TextStream::str().
Referenced by ConceptDefImpl::setInitializer().
toConceptDef() [1/3]
const ConceptDef * toConceptDef (const Definition * d)
Definition at line 716 of file conceptdef.cpp.
{
  if (d && (typeid(*d)==typeid(ConceptDefImpl) || typeid(*d)==typeid(ConceptDefAliasImpl)))
  {
    return static_cast<const ConceptDef*>(d);
  }
  else
  {
    return 0;
  }
}
toConceptDef() [2/3]
ConceptDef * toConceptDef (Definition * d)
Definition at line 691 of file conceptdef.cpp.
{
  if (d && (typeid(*d)==typeid(ConceptDefImpl) || typeid(*d)==typeid(ConceptDefAliasImpl)))
  {
    return static_cast<ConceptDef*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by NamespaceDefImpl::addInnerCompound(), and ConceptDefAliasImpl::getCdAlias().
toConceptDef() [3/3]
ConceptDef * toConceptDef (DefinitionMutable * md)
Definition at line 703 of file conceptdef.cpp.
{
  Definition *d = toDefinition(md);
  if (d && typeid(*d)==typeid(ConceptDefImpl))
  {
    return static_cast<ConceptDef*>(d);
  }
  else
  {
    return 0;
  }
}
References toDefinition().
toConceptDefMutable() [1/2]
ConceptDefMutable * toConceptDefMutable (const Definition * d)
Definition at line 740 of file conceptdef.cpp.
{
  if (d && typeid(*d)==typeid(ConceptDefImpl))
  {
    return const_cast<ConceptDefMutable*>(static_cast<const ConceptDefMutable*>(d));
  }
  else
  {
    return 0;
  }
}
toConceptDefMutable() [2/2]
ConceptDefMutable * toConceptDefMutable (Definition * d)
Definition at line 728 of file conceptdef.cpp.
{
  if (d && typeid(*d)==typeid(ConceptDefImpl))
  {
    return static_cast<ConceptDefMutable*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by addConceptToContext(), addConceptToGroups(), distributeConceptGroups(), findSectionsInDocumentation(), generateConceptDocs(), generateNamespaceConceptDocs(), getConceptMutable(), and writeTagFile().