Doxygen: DocHRef Class Reference
DocHRef Class Reference
Node representing a Hypertext reference.
#include <src/docnode.h>
Public Member Functions
DocHRef (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, const QCString &url, const QCString &relPath, const QCString &file)
Token parse ()
QCString url () const
QCString file () const
QCString relPath () const
const HtmlAttribList & attribs () const
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
HtmlAttribList m_attribs
QCString m_url
QCString m_relPath
QCString m_file
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a Hypertext reference.
Definition at line 801 of file docnode.h.
Constructor & Destructor Documentation
DocHRef()
DocHRef::DocHRef (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, const QCString & url, const QCString & relPath, const QCString & file) inline
Definition at line 804 of file docnode.h.
    : DocCompoundNode(parser,parent), m_attribs(attribs), m_url(url),
      m_relPath(relPath), m_file(file) {}
References attribs(), DocCompoundNode::DocCompoundNode(), file(), m_attribs, m_file, m_relPath, m_url, DocNode::parent(), DocNode::parser(), relPath(), and url().
Member Function Documentation
attribs()
const HtmlAttribList & DocHRef::attribs () const inline
Definition at line 812 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by DocHRef(), and HtmlDocVisitor::operator()().
file()
QCString DocHRef::file () const inline
Definition at line 810 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by DocHRef(), DocbookDocVisitor::operator()(), and RTFDocVisitor::operator()().
parse()
Token DocHRef::parse ()
Definition at line 1449 of file docnode.cpp.
{
  AUTO_TRACE();
  Token retval(TokenRetval::RetVal_OK);
  auto ns = AutoNodeStack(parser(),thisVariant());
  Token tok = parser()->tokenizer.lex();
  while (!tok.is_any_of(TokenRetval::TK_NONE, TokenRetval::TK_EOF))
  {
    if (!parser()->defaultHandleToken(thisVariant(),tok,children()))
    {
      switch (tok.value())
      {
        case TokenRetval::TK_HTMLTAG:
          {
            HtmlTagType tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
            if (tagId==HtmlTagType::HTML_A && parser()->context.token->endTag) // found </a> tag
            {
              goto endhref;
            }
            else if (tagId==HtmlTagType::HTML_BR)
            {
              children().append<DocLineBreak>(parser(),thisVariant(),parser()->context.token->attribs);
            }
            else
            {
              warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected html tag <%s%s> found within <a href=...> context",
                  parser()->context.token->endTag?"/":"",qPrint(parser()->context.token->name));
            }
          }
          break;
        default:
          parser()->errorHandleDefaultToken(thisVariant(),tok,children(),"<a>..</a> block");
          break;
      }
    }
    tok = parser()->tokenizer.lex();
  }
  if (tok.is_any_of(TokenRetval::TK_NONE,TokenRetval::TK_EOF))
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected end of comment while inside"
           " <a href=...> tag");
  }
endhref:
  parser()->handlePendingStyleCommands(thisVariant(),children());
  return retval;
}
References DocNodeList::append(), TokenInfo::attribs, AUTO_TRACE, DocCompoundNode::children(), DocParser::context, DocParser::errorHandleDefaultToken(), DocParser::handlePendingStyleCommands(), HTML_A, HTML_BR, Mappers::htmlTagMapper, Token::is_any_of(), DocTokenizer::lex(), DocNode::parser(), qPrint(), DocNode::thisVariant(), DocParserContext::token, DocParser::tokenizer, Token::value(), and warn_doc_error.
relPath()
QCString DocHRef::relPath () const inline
Definition at line 811 of file docnode.h.
{ return m_relPath; }
References m_relPath.
Referenced by DocHRef(), and HtmlDocVisitor::operator()().
url()
QCString DocHRef::url () const inline
Definition at line 809 of file docnode.h.
{ return m_url; }
References m_url.
Referenced by DocHRef(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
Member Data Documentation
m_attribs
HtmlAttribList DocHRef::m_attribs private
Definition at line 815 of file docnode.h.
Referenced by attribs(), and DocHRef().
m_file
QCString DocHRef::m_file private
Definition at line 818 of file docnode.h.
Referenced by DocHRef(), and file().
m_relPath
QCString DocHRef::m_relPath private
Definition at line 817 of file docnode.h.
Referenced by DocHRef(), and relPath().
m_url
QCString DocHRef::m_url private
Definition at line 816 of file docnode.h.
Referenced by DocHRef(), and url().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp