Doxygen: DocVisitor Class Reference
DocVisitor Class Reference
Helper base class for functionality shared by all visitors.
#include <src/docvisitor.h>
Classes
struct Private
Public Member Functions
DocVisitor ()
virtual ~DocVisitor ()
CodeParserInterface & getCodeParser (const QCString &langExt)
void pushHidden (bool hide)
bool popHidden ()
Private Attributes
std::unique_ptr< Private > m_p
Detailed Description
Helper base class for functionality shared by all visitors.
Definition at line 28 of file docvisitor.h.
Constructor & Destructor Documentation
DocVisitor()
DocVisitor::DocVisitor ()
Definition at line 32 of file docvisitor.cpp.
                       : m_p(std::make_unique<Private>())
{
}
References m_p.
~DocVisitor()
DocVisitor::~DocVisitor () virtual
Definition at line 36 of file docvisitor.cpp.
{
}
Member Function Documentation
getCodeParser()
CodeParserInterface & DocVisitor::getCodeParser (const QCString & langExt)
Definition at line 40 of file docvisitor.cpp.
{
  std::string ext = extension.str();
  // for each extension we create a code parser once per visitor, so that
  // the context of the same parser object is reused throughout multiple passes for instance
  // for code fragments shown via dontinclude.
  auto it = m_p->parserFactoryMap.find(ext);
  if (it==m_p->parserFactoryMap.end())
  {
    auto factory = Doxygen::parserManager->getCodeParserFactory(extension);
    auto result = m_p->parserFactoryMap.emplace(ext,factory());
    it = result.first;
  }
  return *it->second.get();
}
References ParserManager::getCodeParserFactory(), m_p, Doxygen::parserManager, and QCString::str().
Referenced by DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), HtmlDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), ManDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), and XmlDocVisitor::operator()().
popHidden()
bool DocVisitor::popHidden ()
Definition at line 61 of file docvisitor.cpp.
{
  if (m_p->hidden.empty()) return false;
  bool v = m_p->hidden.top();
  m_p->hidden.pop();
  return v;
}
References m_p.
Referenced by RTFDocVisitor::includePicturePostRTF(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
pushHidden()
void DocVisitor::pushHidden (bool hide)
Definition at line 56 of file docvisitor.cpp.
{
  m_p->hidden.push(hide);
}
References m_p.
Referenced by RTFDocVisitor::includePicturePreRTF(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
Member Data Documentation
m_p
std::unique_ptr<Private> DocVisitor::m_p private
Definition at line 31 of file docvisitor.h.
Referenced by DocVisitor(), getCodeParser(), popHidden(), and pushHidden().
The documentation for this class was generated from the following files:
src/docvisitor.h
src/docvisitor.cpp