Doxygen: DiagramItem Class Reference
DiagramItem Class Reference
Class representing a single node in the built-in class diagram.
Public Member Functions
DiagramItem (DiagramItem *p, uint32_t number, const ClassDef *cd, Protection prot, Specifier virt, const QCString &ts)
QCString label () const
QCString fileName () const
DiagramItem * parentItem ()
DiagramItemList getChildren ()
void move (int dx, int dy)
uint32_t xPos () const
uint32_t yPos () const
float xfPos () const
float yfPos () const
uint32_t avgChildPos () const
uint32_t numChildren () const
void addChild (DiagramItem *di)
uint32_t number () const
Protection protection () const
Specifier virtualness () const
void putInList ()
bool isInList () const
const ClassDef * getClassDef () const
Private Attributes
DiagramItemList m_children
DiagramItem * m_parent
uint32_t m_x = 0
uint32_t m_y = 0
uint32_t m_num
Protection m_prot
Specifier m_virt
QCString m_templSpec
bool m_inList = false
const ClassDef * m_classDef
Detailed Description
Class representing a single node in the built-in class diagram.
Definition at line 41 of file diagram.cpp.
Constructor & Destructor Documentation
DiagramItem()
DiagramItem::DiagramItem (DiagramItem * p, uint32_t number, const ClassDef * cd, Protection prot, Specifier virt, const QCString & ts)
Definition at line 297 of file diagram.cpp.
  : m_parent(p), m_num(number), m_prot(pr), m_virt(vi), m_templSpec(ts), m_classDef(cd)
{
}
References DiagramItem(), m_classDef, m_num, m_parent, m_prot, m_templSpec, m_virt, and number().
Referenced by addChild(), avgChildPos(), DiagramItem(), and parentItem().
Member Function Documentation
addChild()
void DiagramItem::addChild (DiagramItem * di)
Definition at line 349 of file diagram.cpp.
{
  m_children.push_back(di);
}
References DiagramItem(), and m_children.
avgChildPos()
uint32_t DiagramItem::avgChildPos () const
Definition at line 330 of file diagram.cpp.
{
  DiagramItem *di = nullptr;
  size_t c=m_children.size();
  if (c==0) // no children -> don't move
    return xPos();
  if ((di=m_children.front())->isInList()) // children should be in a list
    return di->xPos();
  if (c&1) // odd number of children -> get pos of middle child
    return m_children.at(c/2)->xPos();
  else // even number of children -> get middle of most middle children
    return (m_children.at(c/2-1)->xPos()+m_children.at(c/2)->xPos())/2;
}
References DiagramItem(), m_children, and xPos().
Referenced by TreeDiagram::layoutTree().
fileName()
QCString DiagramItem::fileName () const
Definition at line 325 of file diagram.cpp.
{
  return m_classDef->getOutputFileBase();
}
References m_classDef.
getChildren()
DiagramItemList DiagramItem::getChildren () inline
Definition at line 49 of file diagram.cpp.
{ return m_children; }
References m_children.
Referenced by TreeDiagram::drawConnectors(), TreeDiagram::layoutTree(), and TreeDiagram::moveChildren().
getClassDef()
const ClassDef * DiagramItem::getClassDef () const inline
Definition at line 63 of file diagram.cpp.
{ return m_classDef; }
References m_classDef.
Referenced by TreeDiagram::drawBoxes().
isInList()
bool DiagramItem::isInList () const inline
Definition at line 62 of file diagram.cpp.
{ return m_inList; }
References m_inList.
Referenced by TreeDiagram::drawBoxes(), and TreeDiagram::drawConnectors().
label()
QCString DiagramItem::label () const
Definition at line 303 of file diagram.cpp.
{
  QCString result;
  if (!m_templSpec.isEmpty())
  {
    // we use classDef->name() here and not displayName() in order
    // to get the name used in the inheritance relation.
    QCString n = m_classDef->name();
    if (n.endsWith("-p"))
    {
      n = n.left(n.length()-2);
    }
    result=insertTemplateSpecifierInScope(n,m_templSpec);
  }
  else
  {
    result=m_classDef->displayName();
  }
  if (Config_getBool(HIDE_SCOPE_NAMES)) result=stripScope(result);
  return result;
}
References Config_getBool, QCString::endsWith(), insertTemplateSpecifierInScope(), QCString::left(), QCString::length(), m_classDef, m_templSpec, and stripScope().
Referenced by writeBitmapBox(), and writeVectorBox().
move()
void DiagramItem::move (int dx, int dy) inline
Definition at line 50 of file diagram.cpp.
{ m_x=static_cast<uint32_t>(m_x+dx); m_y=static_cast<uint32_t>(m_y+dy); }
References m_x, and m_y.
Referenced by ClassDiagram::ClassDiagram(), and TreeDiagram::computeLayout().
number()
uint32_t DiagramItem::number () const inline
Definition at line 58 of file diagram.cpp.
{ return m_num; }
References m_num.
Referenced by DiagramItem(), and TreeDiagram::layoutTree().
numChildren()
uint32_t DiagramItem::numChildren () const
Definition at line 344 of file diagram.cpp.
{
  return static_cast<uint32_t>(m_children.size());
}
References m_children.
Referenced by TreeDiagram::computeLayout(), TreeDiagram::drawBoxes(), and TreeDiagram::layoutTree().
parentItem()
DiagramItem * DiagramItem::parentItem () inline
Definition at line 48 of file diagram.cpp.
{ return m_parent; }
References DiagramItem(), and m_parent.
Referenced by TreeDiagram::computeRows(), TreeDiagram::drawBoxes(), and TreeDiagram::drawConnectors().
protection()
Protection DiagramItem::protection () const inline
Definition at line 59 of file diagram.cpp.
{ return m_prot; }
References m_prot.
Referenced by TreeDiagram::drawConnectors().
putInList()
void DiagramItem::putInList () inline
Definition at line 61 of file diagram.cpp.
{ m_inList=TRUE; }
References m_inList, and TRUE.
virtualness()
Specifier DiagramItem::virtualness () const inline
Definition at line 60 of file diagram.cpp.
{ return m_virt; }
References m_virt.
Referenced by writeBitmapBox(), and writeVectorBox().
xfPos()
float DiagramItem::xfPos () const inline
Definition at line 53 of file diagram.cpp.
{ return static_cast<float>(m_x); }
References m_x.
Referenced by TreeDiagram::drawBoxes(), and TreeDiagram::drawConnectors().
xPos()
uint32_t DiagramItem::xPos () const inline
Definition at line 51 of file diagram.cpp.
{ return m_x; }
References m_x.
Referenced by avgChildPos(), ClassDiagram::ClassDiagram(), TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), and TreeDiagram::layoutTree().
yfPos()
float DiagramItem::yfPos () const inline
Definition at line 54 of file diagram.cpp.
{ return static_cast<float>(m_y); }
References m_y.
Referenced by TreeDiagram::drawBoxes(), and TreeDiagram::drawConnectors().
yPos()
uint32_t DiagramItem::yPos () const inline
Definition at line 52 of file diagram.cpp.
{ return m_y; }
References m_y.
Referenced by TreeDiagram::drawBoxes(), and TreeDiagram::drawConnectors().
Member Data Documentation
m_children
DiagramItemList DiagramItem::m_children private
Definition at line 65 of file diagram.cpp.
Referenced by addChild(), avgChildPos(), getChildren(), and numChildren().
m_classDef
const ClassDef* DiagramItem::m_classDef private
Definition at line 74 of file diagram.cpp.
Referenced by DiagramItem(), fileName(), getClassDef(), and label().
m_inList
bool DiagramItem::m_inList = false private
Definition at line 73 of file diagram.cpp.
Referenced by isInList(), and putInList().
m_num
uint32_t DiagramItem::m_num private
Definition at line 69 of file diagram.cpp.
Referenced by DiagramItem(), and number().
m_parent
DiagramItem* DiagramItem::m_parent private
Definition at line 66 of file diagram.cpp.
Referenced by DiagramItem(), and parentItem().
m_prot
Protection DiagramItem::m_prot private
Definition at line 70 of file diagram.cpp.
Referenced by DiagramItem(), and protection().
m_templSpec
QCString DiagramItem::m_templSpec private
Definition at line 72 of file diagram.cpp.
Referenced by DiagramItem(), and label().
m_virt
Specifier DiagramItem::m_virt private
Definition at line 71 of file diagram.cpp.
Referenced by DiagramItem(), and virtualness().
m_x
uint32_t DiagramItem::m_x = 0 private
Definition at line 67 of file diagram.cpp.
Referenced by move(), xfPos(), and xPos().
m_y
uint32_t DiagramItem::m_y = 0 private
Definition at line 68 of file diagram.cpp.
Referenced by move(), yfPos(), and yPos().
The documentation for this class was generated from the following file:
src/diagram.cpp