Doxygen: CodeParserInterface Class Reference
CodeParserInterface Class Reference abstract
Abstract interface for code parsers.
#include <src/parserintf.h>
Public Member Functions
virtual ~CodeParserInterface ()=default
virtual void parseCode (OutputCodeList &codeOutList, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=nullptr, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=nullptr, bool showLineNumbers=TRUE, const Definition *searchCtx=nullptr, bool collectXRefs=TRUE)=0
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
virtual void resetCodeParserState ()=0
Resets the state of the code parser.
Detailed Description
Abstract interface for code parsers.
By implementing the methods of this interface one can add a new language parser to doxygen. This interface is used for syntax highlighting, but also to extract cross references and call graphs.
Definition at line 81 of file parserintf.h.
Constructor & Destructor Documentation
~CodeParserInterface()
virtual CodeParserInterface::~CodeParserInterface () virtual default
Member Function Documentation
parseCode()
virtual void CodeParserInterface::parseCode (OutputCodeList & codeOutList, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = nullptr, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = nullptr, bool showLineNumbers = TRUE, const Definition * searchCtx = nullptr, bool collectXRefs = TRUE) pure virtual
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
[in] codeOutList interface for writing the result.
[in] scopeName Name of scope to which the code belongs.
[in] input Actual code in the form of a string
[in] lang The programming language of the code fragment.
[in] isExampleBlock TRUE iff the code is part of an example.
[in] exampleName Name of the example.
[in] fileDef File definition to which the code is associated.
[in] startLine Starting line in case of a code fragment.
[in] endLine Ending line of the code fragment.
[in] inlineFragment Code fragment that is to be shown inline as part of the documentation.
[in] memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
[in] showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
[in] searchCtx context under which search data has to be stored.
[in] collectXRefs collect cross-reference relations.
Implemented in CCodeParser, FileCodeParser, FortranCodeParser, PythonCodeParser, VHDLCodeParser, LexCodeParser, SQLCodeParser, and XMLCodeParser.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
resetCodeParserState()
virtual void CodeParserInterface::resetCodeParserState () pure virtual
Resets the state of the code parser.
Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implemented in CCodeParser, FileCodeParser, FortranCodeParser, LexCodeParser, PythonCodeParser, SQLCodeParser, VHDLCodeParser, and XMLCodeParser.
The documentation for this class was generated from the following file:
src/parserintf.h