Doxygen: src/tooltip.cpp File Reference
tooltip.cpp File Reference
#include <map>
#include <memory>
#include <unordered_map>
#include <unordered_set>
#include <string>
#include <mutex>
#include "tooltip.h"
#include "definition.h"
#include "outputlist.h"
#include "util.h"
#include "filedef.h"
#include "doxygen.h"
#include "config.h"
Classes
class TooltipManager::Private
Functions
static QCString escapeId (const QCString &s)
Variables
static std::mutex g_tooltipsFileMutex
static std::mutex g_tooltipsTipMutex
static std::unordered_map< int, std::unordered_set< std::string > > g_tooltipsWrittenPerFile
Function Documentation
escapeId()
static QCString escapeId (const QCString & s) static
Definition at line 49 of file tooltip.cpp.
{
  QCString res=s;
  for (size_t i=0;i<res.length();i++) if (!isId(res[i])) res[i]='_';
  return res;
}
References isId(), and QCString::length().
Referenced by TooltipManager::addTooltip().
Variable Documentation
g_tooltipsFileMutex
std::mutex g_tooltipsFileMutex static
Definition at line 31 of file tooltip.cpp.
Referenced by TooltipManager::writeTooltips().
g_tooltipsTipMutex
std::mutex g_tooltipsTipMutex static
Definition at line 32 of file tooltip.cpp.
Referenced by TooltipManager::writeTooltips().
g_tooltipsWrittenPerFile
std::unordered_map<int, std::unordered_set<std::string> > g_tooltipsWrittenPerFile static
Definition at line 33 of file tooltip.cpp.
Referenced by TooltipManager::writeTooltips().