Doxygen: DotAttributes Class Reference
DotAttributes Class Reference
Class representing an attribute list of a dot graph object.
#include <src/dotattributes.h>
Public Member Functions
DotAttributes (const QCString &input)
Creates an instance of a DotAttribute list given its initial string representation.
QCString str () const
Return the string representation of the attribute list.
void updateValue (const QCString &key, const QCString &inpValue)
update a given attribute with a new value.
Private Attributes
QCString m_input
Detailed Description
Class representing an attribute list of a dot graph object.
Definition at line 26 of file dotattributes.h.
Constructor & Destructor Documentation
DotAttributes()
DotAttributes::DotAttributes (const QCString & input) inline
Creates an instance of a DotAttribute list given its initial string representation.
Definition at line 30 of file dotattributes.h.
: m_input(input) {}
References m_input.
Member Function Documentation
str()
QCString DotAttributes::str () const inline
Return the string representation of the attribute list.
Definition at line 33 of file dotattributes.h.
{ return m_input; }
References m_input.
Referenced by Config::updateObsolete().
updateValue()
void DotAttributes::updateValue (const QCString & key, const QCString & inpValue) inline
update a given attribute with a new value.
If the attribute is not found a new attribute will be appended.
Definition at line 37 of file dotattributes.h.
    {
      // look for key\s*=
      const std::string regStr = key.str()+R"(\s*=)";
      const reg::Ex re { regStr };
      reg::Match match;
      std::string s = m_input.str();
      if (reg::search(s,match,re)) // replace existing attribute
      {
        size_t len      = s.length();
        size_t startPos = match.position()+match.length(); // position after =
        size_t pos      = startPos;
        while (pos<len && qisspace(s[pos])) pos++;
        if (pos<len && s[pos]=='"') // quoted value, search for end quote, ignoring escaped quotes
        {
          char pc=s[pos];
          pos++; // skip over start quote
          while (pos<len && (s[pos]!='"' || (s[pos]=='"' && pc=='\\'))) pc=s[pos++];
          if (pos<len) pos++; // skip over end quote
        }
        else // unquoted value, search for attribute separator (space,comma, or semicolon)
        {
          while (pos<len && s[pos]!=',' && s[pos]!=';' && !qisspace(s[pos])) pos++;
        }
        QCString value;
        if (inpValue.isEmpty())
        {
          value = m_input.mid(startPos,pos-startPos);
        }
        else
        {
          value = inpValue;
        }
        // pos is now the position after the value, so replace the part between [start..pos) with the new value
        m_input=m_input.left(startPos)+value.quoted()+m_input.mid(pos);
      }
      else // append new attribute
      {
        if (!inpValue.isEmpty())
        {
          if (!m_input.isEmpty()) m_input+=",";
          m_input+=key+"="+inpValue.quoted();
        }
      }
    }
References QCString::isEmpty(), m_input, qisspace(), QCString::quoted(), reg::search(), and QCString::str().
Referenced by updateAttribute().
Member Data Documentation
m_input
QCString DotAttributes::m_input private
Definition at line 84 of file dotattributes.h.
Referenced by DotAttributes(), str(), and updateValue().
The documentation for this class was generated from the following file:
src/dotattributes.h