Doxygen: TranslatorDanish Class Reference
TranslatorDanish Class Reference
#include <src/translator_dk.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trEnumerationValueDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
Public Member Functions inherited from TranslatorAdapter_1_8_0
QCString updateNeededMessage () override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 90 of file translator_dk.h.
Member Function Documentation
getLanguageString()
QCString TranslatorDanish::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 126 of file translator_dk.h.
    {
      return "0x406 Danish";
    }
idLanguage()
QCString TranslatorDanish::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 102 of file translator_dk.h.
    { return "danish"; }
latexLanguageSupportCommand()
QCString TranslatorDanish::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 116 of file translator_dk.h.
    {
      return
        "\\usepackage[danish]{babel}\n";
    }
trAll()
QCString TranslatorDanish::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1319 of file translator_dk.h.
    {
      return "Alle";
    }
trAttention()
QCString TranslatorDanish::trAttention () inline override virtual
Implements Translator.
Definition at line 940 of file translator_dk.h.
    {
      return "OBS";
    }
trAuthor()
QCString TranslatorDanish::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1217 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "forfatter", "e");
    }
References Translator::createNoun().
trBug()
QCString TranslatorDanish::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1109 of file translator_dk.h.
    {
      return "Kendte fejl";
    }
trBugList()
QCString TranslatorDanish::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1114 of file translator_dk.h.
    {
      return "Liste over kendte fejl";
    }
trCallerGraph()
QCString TranslatorDanish::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1440 of file translator_dk.h.
    {
      return "Her er kalder-grafen for denne funktion:";
    }
trCallGraph()
QCString TranslatorDanish::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1325 of file translator_dk.h.
    {
      return "Her er kald-grafen for denne funktion:";
    }
trCiteReferences()
QCString TranslatorDanish::trCiteReferences () inline override virtual
Implements Translator.
Definition at line 1767 of file translator_dk.h.
    {
      return "Bibliografiske referencer";
    }
trClass()
QCString TranslatorDanish::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1152 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "klasse", "r");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorDanish::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 529 of file translator_dk.h.
    {
      return "Stamtr for "+clName+":";
    }
trClassDocumentation()
QCString TranslatorDanish::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 407 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastruktur-documentation";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klasse-dokumentation";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorDanish::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1073 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datastrukturer";
      } else {
        return "Klasser";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorDanish::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 224 of file translator_dk.h.
    { return "Klassehierarki"; }
trClassHierarchyDescription()
QCString TranslatorDanish::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 275 of file translator_dk.h.
    { return "Denne nedarvningsliste er sorteret nsten - "
             "men ikke ndvendigvis helt - alfabetisk:";
    }
trCode()
QCString TranslatorDanish::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 869 of file translator_dk.h.
    { return "kildekode"; }
trCollaborationDiagram()
QCString TranslatorDanish::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 831 of file translator_dk.h.
    {
      return "Samarbejdsdiagram for "+clName+":";
    }
trCompoundIndex()
QCString TranslatorDanish::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 383 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Indeks over datastrukturer";
      } else {
        return "Indeks over sammensatte typer";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorDanish::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1501 of file translator_dk.h.
    { return "Datatype indeks"; }   // "Data Type Index"
trCompoundList()
QCString TranslatorDanish::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 228 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datastrukturer";
      } else {
        return "Oversigt over sammensatte typer";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorDanish::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 290 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Her er datastrukturerne med korte beskrivelser:";
      } else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE)) {
        return "Her er klasserne med korte beskrivelser:";
      } else {
        return "Her er klasserne, datastrukturerne, "
               "unionerne og grnsefladerne med korte beskrivelser:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorDanish::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1474 of file translator_dk.h.
    { return "Her er de datatyper med kort beskrivelse:"; }  // "Here are the data types with brief descriptions:"
trCompoundListFortran()
QCString TranslatorDanish::trCompoundListFortran () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1466 of file translator_dk.h.
    { return "Data Type Liste"; }       // "Data Types List"
trCompoundMembers()
QCString TranslatorDanish::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 242 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Data-felter";
      } else {
        return "Felter i sammensatte typer";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorDanish::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 304 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) {
        result+="dokumenterede ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result+="felter i datastrukturer og unioner";
      } else {
        result+="klassemedlemmer";
      }
      result+=" med links til ";
      if (!extractAll) {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+="datastruktur/unions-dokumentationen for hvert felt:";
        } else {
          result+="klassedokumentationen for hvert medlem:";
        }
      } else {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+="de datastrukturer/unioner, de hrer til:";
        } else {
          result+="de klasser, de hrer til:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorDanish::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1478 of file translator_dk.h.
    {
      QCString result="Her er en liste af alle "; // "Here is a list of all "
      if (!extractAll)
      {
        result+="dokumenteret ";  // "documented "
      }
      result+="datatype medlemmer"; //  "data types members"
      result+=" med links til ";    // " with links to "
      if (!extractAll)
      {
         result+="data strukturer dokumenteret for hver medlem";    // "the data structure documentation for each member"
      }
      else
      {
         result+="de datatyper som de tilhrer:";  // "the data types they belong to:"
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorDanish::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1470 of file translator_dk.h.
    { return "Data felter"; }   // "Data Fields"
trCompoundReference()
QCString TranslatorDanish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 604 of file translator_dk.h.
    {
      QCString result=clName+" ";
      switch(compType)
      {
        case ClassDef::Class:      result+=" Klasse-"; break;
        case ClassDef::Struct:     result+=" Datastruktur-"; break;
        case ClassDef::Union:      result+=" Union-"; break;
        case ClassDef::Interface:  result+=" Grnseflade-"; break;
        case ClassDef::Protocol:   result+=" Protokol-"; break;
        case ClassDef::Category:   result+=" Kategori-"; break; // " Category-"
        case ClassDef::Exception:  result+=" Undtagelse-"; break;   //  " Exception"
        default: break;
      }
      if (isTemplate) result+="skabelon-";  // "template-"
      result+="reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorDanish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1542 of file translator_dk.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Modul"; break;     // " Module"
        case ClassDef::Struct:     result+=" Type"; break;      // " Type"
        case ClassDef::Union:      result+=" Union"; break;     // " Union"
        case ClassDef::Interface:  result+=" Grnseflade"; break; // " Interface"
        case ClassDef::Protocol:   result+=" Protocol"; break;      // " Protocol"
        case ClassDef::Category:   result+=" Kategori"; break;      // " Category"
        case ClassDef::Exception:  result+=" Undtagelse"; break; // " Exception"
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Reference";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorDanish::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 508 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datastrukturer";
      } else {
        return "Sammensatte typer";
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorDanish::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 841 of file translator_dk.h.
    {
      return "Dokumentation af konstruktrer og destruktrer";
      // "Constructor & Destructor dokumentation";
    }
trCopyright()
QCString TranslatorDanish::trCopyright () inline override virtual
Implements Translator.
Definition at line 1772 of file translator_dk.h.
    {
      return "Copyright";
    }
trDataTypes()
QCString TranslatorDanish::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1525 of file translator_dk.h.
    { return "Datatyper"; }    // "Data Types"
trDate()
QCString TranslatorDanish::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 543 of file translator_dk.h.
    { return "Dato"; }
trDateTime()
QCString TranslatorDanish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1721 of file translator_dk.h.
    {
      static const char *days[]   = { "Man","Tir","Ons","Tor","Fre","Lr","Sn" }; // { "Mon","Tue","Wed","Thu","Fri","Sat","Sun" };
      static const char *months[] = { "Jan","Feb","Mar","Apr","Maj","Jun","Jul","Aug","Sep","Okt","Nov","Dec" };    //  { "Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorDanish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1741 of file translator_dk.h.
    {
      static const char *days_short[]   = { "ma", "ti", "on", "to", "fr", "l", "s" };
      static const char *days_full[]    = { "mandag", "tirsdag", "onsdag", "torsdag", "fredag", "lrdag", "sndag" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorDanish::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1757 of file translator_dk.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorDanish::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 806 of file translator_dk.h.
    {
      return "Defineret p linje @0 i filen @1.";
    }
trDefinedIn()
QCString TranslatorDanish::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 212 of file translator_dk.h.
    { return "defineret i"; }
trDefinedInSourceFile()
QCString TranslatorDanish::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 811 of file translator_dk.h.
    {
      return "Defineret i filen @0.";
    }
trDefineDocumentation()
QCString TranslatorDanish::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 472 of file translator_dk.h.
    { return "#Define-dokumentation"; }
trDefines()
QCString TranslatorDanish::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 436 of file translator_dk.h.
    { return "#Defines"; }
trDefineValue()
QCString TranslatorDanish::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1099 of file translator_dk.h.
    {
      return "Vrdi:";
    }
trDeprecated()
QCString TranslatorDanish::trDeprecated () inline override virtual
Implements Translator.
Definition at line 820 of file translator_dk.h.
    {
      return "Frardes - fortidslevn"; // ?? - What is the context?
          // "Ugleset" :)
    }
trDeprecatedList()
QCString TranslatorDanish::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1272 of file translator_dk.h.
    {
      return "Liste over fortidslevn, hvis brug frardes";
    }
trDetailedDescription()
QCString TranslatorDanish::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 143 of file translator_dk.h.
    { return "Detaljeret beskrivelse"; }
trDetails()
QCString TranslatorDanish::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 147 of file translator_dk.h.
    { return "Detaljer"; }
trDir()
QCString TranslatorDanish::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1415 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "katalog", "er");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorDanish::trDirDepGraph (const QCString & name) inline override virtual
Implements Translator.
Definition at line 1777 of file translator_dk.h.
    {
      return QCString("Afhngighedsgraf for katalog ")+name+":";
    }
trDirDocumentation()
QCString TranslatorDanish::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1397 of file translator_dk.h.
    { return "Katalog-dokumentation"; }
trDirectories()
QCString TranslatorDanish::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1403 of file translator_dk.h.
    { return "Kataloger"; }
trDirIndex()
QCString TranslatorDanish::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1391 of file translator_dk.h.
    { return "Katalogstruktur"; }
trDirReference()
QCString TranslatorDanish::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1409 of file translator_dk.h.
      { QCString result="Indhold af kataloget "; result+=dirName; return result;}
trDirRelation()
QCString TranslatorDanish::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1660 of file translator_dk.h.
    {
      return QCString(name)+" Relation";        // " Relation"
    }
trDocumentation()
QCString TranslatorDanish::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 365 of file translator_dk.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentation"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorDanish::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 448 of file translator_dk.h.
    { return "Enumerationer"; }
trEnumerationTypeDocumentation()
QCString TranslatorDanish::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 484 of file translator_dk.h.
    { return "Dokumentation af enumerations-typer"; }
trEnumerationValueDocumentation()
QCString TranslatorDanish::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 490 of file translator_dk.h.
    { return "Dokumentation af enumerations-vrdier"; }
trEnumerationValues()
QCString TranslatorDanish::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 466 of file translator_dk.h.
    { return "Enumerationsvrdier"; }
trEnumName()
QCString TranslatorDanish::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 204 of file translator_dk.h.
    { return "enumerationsnavn"; }
trEnumValue()
QCString TranslatorDanish::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 208 of file translator_dk.h.
    { return "enumerationsvrdi"; }
trEventDocumentation()
QCString TranslatorDanish::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1289 of file translator_dk.h.
    {
      return "Begivenhedsdokumentation";
    }
trEvents()
QCString TranslatorDanish::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1284 of file translator_dk.h.
    {
      return "Begivenheder";
    }
trExamples()
QCString TranslatorDanish::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 267 of file translator_dk.h.
    { return "Eksempler"; }
trExamplesDescription()
QCString TranslatorDanish::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 353 of file translator_dk.h.
    { return "Her er en liste over alle eksempler:"; }
trExceptions()
QCString TranslatorDanish::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 559 of file translator_dk.h.
    { return "Undtagelser"; }    // "Exceptions"
trFile()
QCString TranslatorDanish::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1161 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "fil", "er");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorDanish::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 426 of file translator_dk.h.
    { return "Fil-dokumentation"; }
trFileIn()
QCString TranslatorDanish::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1697 of file translator_dk.h.
    {
      return "File i "+name;     // "File in "
    }
trFileIndex()
QCString TranslatorDanish::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 395 of file translator_dk.h.
    { return "Fil-indeks"; }
trFileList()
QCString TranslatorDanish::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 238 of file translator_dk.h.
    { return "Filoversigt"; }
trFileListDescription()
QCString TranslatorDanish::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 281 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      result+="filer med korte beskrivelser:";
      return result;
    }
trFileMembers()
QCString TranslatorDanish::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 252 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Globale symboler";
      } else {
        return "Placering i filer"; // Fil-medlemmer"; //TODO
        //"Globale definitioner" ?
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorDanish::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 333 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result+="funktioner, variable, #defines, enumerationer "
            "og typedefinitioner";
      } else {
        result+="fil-medlemmer";
      }
      result+=", med links til ";
      if (extractAll)
        result+="de filer, de tilhrer:";
      else
        result+="deres dokumentation:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorDanish::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 626 of file translator_dk.h.
    {
      QCString result=fileName;
      result+=" filreference";
      return result;
    }
trFriends()
QCString TranslatorDanish::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 586 of file translator_dk.h.
    { return "Friends"; }
trFunctionDocumentation()
QCString TranslatorDanish::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 496 of file translator_dk.h.
    { return "Funktions-dokumentation"; }
trFunctions()
QCString TranslatorDanish::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 454 of file translator_dk.h.
    { return "Funktioner"; }
trGeneratedAt()
QCString TranslatorDanish::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 520 of file translator_dk.h.
    {
      QCString result="Genereret "+date;
      if (!projName.isEmpty()) result+=" for "+projName;
      result+=" af";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorDanish::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 196 of file translator_dk.h.
    { QCString result="Automatisk genereret af Doxygen";
      if (!s.isEmpty()) result+=" for "+s;
      result+=" ud fra kildekoden.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorDanish::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 563 of file translator_dk.h.
    { return "Genereret af"; }
trGeneratedFromFiles()
QCString TranslatorDanish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 762 of file translator_dk.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentationen for denne ";
      switch(compType)
      {
        case ClassDef::Class:      result+="klasse"; break;
        case ClassDef::Struct:     result+="datastruktur"; break;
        case ClassDef::Union:      result+="union"; break;
        case ClassDef::Interface:  result+="grnseflade"; break;
        case ClassDef::Protocol:   result+="protokol"; break; // "protocol"
        case ClassDef::Category:   result+="kategori"; break; // "category"
        case ClassDef::Exception:  result+="undtagelse"; break;  // "exception"
        default: break;
      }
      result+=" blev genereret ud fra fil";
      if (single) result+="en:"; else result+="erne:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorDanish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1610 of file translator_dk.h.
    {
      // single is true implies a single file
      QCString result="The documentation for this ";
      switch(compType)
      {
        case ClassDef::Class:      result+="modul"; break;        // "module"
        case ClassDef::Struct:     result+="type"; break;         // "type"
        case ClassDef::Union:      result+="union"; break;        // "union"
        case ClassDef::Interface:  result+="grnseflade"; break;  // "interface"
        case ClassDef::Protocol:   result+="protokol"; break;     // "protocol"
        case ClassDef::Category:   result+="kategori"; break;     // "category"
        case ClassDef::Exception:  result+="undtagelse"; break;   // "exception"
        default: break;
      }
      result+=" var lavet udfra flgende file";                   // " was generated from the following file"
      if (single) result+=":"; else result+="r:";                 // ":" / "s:"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorDanish::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1206 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "global", "e");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorDanish::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1672 of file translator_dk.h.
    {
      return "Globalt Namespace";    // "Global Namespace"
    }
trGotoDocumentation()
QCString TranslatorDanish::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 851 of file translator_dk.h.
    { return "Hop til denne fils dokumentation."; }
trGotoGraphicalHierarchy()
QCString TranslatorDanish::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 873 of file translator_dk.h.
    { return "Hop til det grafiske klassehierarki"; }
trGotoSourceCode()
QCString TranslatorDanish::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 848 of file translator_dk.h.
    { return "Hop til denne fils kildekode."; }
trGotoTextualHierarchy()
QCString TranslatorDanish::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 875 of file translator_dk.h.
    { return "Hop til det tekstuelle klassehierarki"; }
trGraphicalHierarchy()
QCString TranslatorDanish::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 871 of file translator_dk.h.
    { return "Grafisk klassehierarki"; }
trGroup()
QCString TranslatorDanish::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1179 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "gruppe", "r");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorDanish::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 377 of file translator_dk.h.
    { return "Hierarkisk indeks"; }
trImplementedFromList()
QCString TranslatorDanish::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1240 of file translator_dk.h.
    {
      return "Implementerer "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorDanish::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1248 of file translator_dk.h.
    {
      return "Implementeret i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorDanish::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 944 of file translator_dk.h.
    {
      return
        "Denne graf viser, hvilke filer der direkte eller "
        "indirekte inkluderer denne fil:";
    }
trInclDepGraph()
QCString TranslatorDanish::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 836 of file translator_dk.h.
    {
      return "Inklusions-afhngighedsgraf for "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorDanish::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1706 of file translator_dk.h.
    {
      return "Inkluderer file i "+name;    // "Includes file in "
    }
trIncludingInheritedMembers()
QCString TranslatorDanish::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 190 of file translator_dk.h.
    { return ", inklusive alle nedarvede medlemmer."; }
trInheritedByList()
QCString TranslatorDanish::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 696 of file translator_dk.h.
    {
      return "Nedarvet af "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList()
QCString TranslatorDanish::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 688 of file translator_dk.h.
    {
      return "Nedarver "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorDanish::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 865 of file translator_dk.h.
    { return "Startvrdi:"; }
trInvariant()
QCString TranslatorDanish::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 861 of file translator_dk.h.
    { return "Invariant"; }
trISOLang()
QCString TranslatorDanish::trISOLang () inline override virtual
Implements Translator.
Definition at line 122 of file translator_dk.h.
    {
      return "da";
    }
trLegend()
QCString TranslatorDanish::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1033 of file translator_dk.h.
    {
      return "forklaring til graf";
    }
trLegendDocs()
QCString TranslatorDanish::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 965 of file translator_dk.h.
    {
      return
                "Denne side forklarer, hvordan man skal fortolke de grafer, "
                "der genereres af doxygen.<p>\n"
        "Tag flgende eksempel:\n"
        "\\code\n"
        "/*! Klasse der er usynlig pg.a. beskring */\n"
        "class Invisible { };\n\n"
        "/*! Beskret klasse: nedarvningsrelation er skjult */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasse der ikke er dokumenteret med doxygen-kommentarer */\n"
        "class Undocumented { };\n\n"
        "/*! Klasse der nedarves fra offentligt */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! En template-klasse */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasse der nedarves fra beskyttet */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasse der nedarves fra privat */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasse der bruges af Inherited-klassen */\n"
        "class Used { };\n\n"
        "/*! Klasse der nedarver en masse andre klasser */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Hvis \\c MAX_DOT_GRAPH_HEIGHT i konfigurationsfilen "
        "er sat til 240, vil dette resultere i flgende graf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "De forskellige slags kasser i ovenstende graf har flgende "
                "betydninger:\n"
        "<ul>\n"
        "<li>%En udfyldt sort kasse reprsenterer den datastruktur eller "
                "klasse, grafen er genereret for.\n"
        "<li>%En kasse med sort kant betegner en dokumenteret datastruktur "
                " eller klasse.\n"
        "<li>%En kasse med gr kant betegner en udokumenteret datastruktur "
                " eller klasse.\n"
        "<li>%En kasse med rd kant betegner en dokumenteret datastruktur "
                " eller klasse, for hvilken ikke alle "
                "nedarvnings- og indeholdelses-relationer er vist. "
        "%Grafer beskres, hvis de fylder mere end de specificerede dimensioner.\n "
        "</ul>\n"
        "Pilene har flgende betydninger:\n"
        "<ul>\n"
        "<li>%En mrkebl pil viser en offentlig nedarvningsrelation "
                "mellem to klasser.\n"
        "<li>%En mrkegrn pil viser en beskyttet nedarvningsrelation.\n"
        "<li>%En mrkerd pil viser en privat nedarvningsrelation.\n"
        "<li>%En lilla, stiplet pil bruges, nr en klasse er indeholdt i "
                "eller benyttes af en anden klasse. "
        "Ved pilen str navnet p den eller de variable, gennem hvilke(n) "
                "den klasse, pilen peger p, er tilgngelig.\n"
        "<li>%En gul, stiplet pil viser forholdet mellem en template-instans "
                "og den template-klasse, den er instantieret fra."
        "Ved pilen str template-parametrene brugt ved instantieringen.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorDanish::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 960 of file translator_dk.h.
    {
      return "Graf-forklaring";
    }
trListOfAllMembers()
QCString TranslatorDanish::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 178 of file translator_dk.h.
    { return "Liste over alle medlemmer"; }
trLoading()
QCString TranslatorDanish::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1666 of file translator_dk.h.
    {
      return "Indlser...";          // "Loading..."
    }
trMainPage()
QCString TranslatorDanish::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 793 of file translator_dk.h.
    { return "Hovedside"; }
trMember()
QCString TranslatorDanish::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1197 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "medlem", "mer");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorDanish::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 164 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Felt-dokumentation";
      } else {
        return "Dokumentation af feltvariable";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorDanish::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 155 of file translator_dk.h.
    { return "Dokumentation af medlems-enumerationer"; }
trMemberFunctionDocumentation()
QCString TranslatorDanish::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 160 of file translator_dk.h.
    { return "Dokumentation af medlemsfunktioner"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorDanish::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1449 of file translator_dk.h.
    { return "Medlem Funktion/Subroutine Dokumentation"; }  // "Member Function/Subroutine Documentation"
trMemberList()
QCString TranslatorDanish::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 182 of file translator_dk.h.
    { return "Liste over medlemmer"; }
trMemberTypedefDocumentation()
QCString TranslatorDanish::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 151 of file translator_dk.h.
    { return "Dokumentation af medlems-typedefinitioner"; }
trModule()
QCString TranslatorDanish::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1602 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "modul", "er");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorDanish::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 401 of file translator_dk.h.
    { return "Modul-dokumentation"; }
trModuleIndex()
QCString TranslatorDanish::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 371 of file translator_dk.h.
    { return "Modul-indeks"; }
trModuleReference()
QCString TranslatorDanish::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1564 of file translator_dk.h.
    {
      QCString result=namespaceName;
      result+=" Modulreference";  // " Module Reference"
      return result;
    }
trModules()
QCString TranslatorDanish::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 220 of file translator_dk.h.
    { return "Moduler"; }
trModulesDescription()
QCString TranslatorDanish::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 361 of file translator_dk.h.
    { return "Her er en liste over alle moduler:"; }
trModulesIndex()
QCString TranslatorDanish::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1595 of file translator_dk.h.
    { return "Modulindekser"; }     // "Modules Index"
trModulesList()
QCString TranslatorDanish::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1529 of file translator_dk.h.
    { return "Modulliste"; }  // "Modules List"
trModulesListDescription()
QCString TranslatorDanish::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1533 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";     // "Here is a list of all "
      if (!extractAll) result+="dokumenteret ";       // "documented "
      result+="moduler med kort beskrivelse:";   // "modules with brief descriptions:"
      return result;
    }
trModulesMemberDescription()
QCString TranslatorDanish::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1576 of file translator_dk.h.
    {
      QCString result="Her er en list over alle ";     // "Here is a list of all "
      if (!extractAll) result+="Dokumentet ";       // "documented "
      result+="modulmemlemmer med link til ";      // "module members with links to "
      if (extractAll)
      {
        result+="dokumentation for hvert model medlem:";    // "the module documentation for each member:"
      }
      else
      {
        result+="moduler de tilhre:";  // "the modules they belong to:"
      }
      return result;
    }
trModulesMembers()
QCString TranslatorDanish::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1572 of file translator_dk.h.
    { return "Modulmedlemmer"; }    // "Module Members"
trMonth()
QCString TranslatorDanish::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1749 of file translator_dk.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[]  = { "januar", "februar", "marts", "april", "maj", "juni", "juli", "august", "september", "oktober", "november", "december" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorDanish::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 174 of file translator_dk.h.
    { return "Mere..."; }
trNamespace()
QCString TranslatorDanish::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1170 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "namespace", "s");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorDanish::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 742 of file translator_dk.h.
    { return "Namespace-dokumentation"; }
trNamespaceIndex()
QCString TranslatorDanish::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 736 of file translator_dk.h.
    { return "Namespace-indeks"; }
trNamespaceList()
QCString TranslatorDanish::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 571 of file translator_dk.h.
    { return "Oversigt over namespaces"; }
trNamespaceListDescription()
QCString TranslatorDanish::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 575 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      result+="namespaces med korte beskrivelser:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorDanish::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 722 of file translator_dk.h.
    {
      QCString result="Her er en liste over alle ";
      if (!extractAll) result+="dokumenterede ";
      result+="namespace-medlemmer med links til ";
      if (extractAll)
        result+="namespace-dokumentationen for hvert medlem:";
      else
        result+="det namespace, de hrer til:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorDanish::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 718 of file translator_dk.h.
    { return "Namespace-medlemmer"; }
trNamespaceReference()
QCString TranslatorDanish::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 634 of file translator_dk.h.
    {
      QCString result=namespaceName;
      result+=" namespace-reference";
      return result;
    }
trNamespaces()
QCString TranslatorDanish::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 752 of file translator_dk.h.
    { return "Namespaces"; }
trNoMatches()
QCString TranslatorDanish::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1684 of file translator_dk.h.
    {
      return "Ingen fund";      // "No Matches"
    }
trNote()
QCString TranslatorDanish::trNote () inline override virtual
Implements Translator.
Definition at line 884 of file translator_dk.h.
    { return "Note"; }
trOverloadText()
QCString TranslatorDanish::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1427 of file translator_dk.h.
    {
       return "Dette er en overdefineret medlemsfunktion, "
              "defineret af bekvemmelighedshensyn. "
              "Den adskiller sig kun fra den ovenstende funktion i, "
              "hvilke argumenter den tager.";
    }
trPackage()
QCString TranslatorDanish::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1082 of file translator_dk.h.
    {
      return "Pakke "+name;
    }
trPackageAttribs()
QCString TranslatorDanish::trPackageAttribs () inline override virtual
Implements Translator.
Definition at line 1307 of file translator_dk.h.
    { return "Attributter med pakke-scope"; }
trPackageFunctions()
QCString TranslatorDanish::trPackageFunctions () inline override virtual
Implements Translator.
Definition at line 1301 of file translator_dk.h.
    { return "Metoder med pakke-scope"; }
trPackageListDescription()
QCString TranslatorDanish::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1087 of file translator_dk.h.
    {
      return
        "Her er en liste over pakkerne, med korte beskrivelser "
        "(hvor en sdan findes):";
    }
trPackageMembers()
QCString TranslatorDanish::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1303 of file translator_dk.h.
    { return "Medlemmer med pakke-scope"; }
trPackages()
QCString TranslatorDanish::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1094 of file translator_dk.h.
    {
      return "Pakker";
    }
trPackageTypes()
QCString TranslatorDanish::trPackageTypes () inline override virtual
Implements Translator.
Definition at line 1299 of file translator_dk.h.
    { return "Typer med pakke-scope"; }
trPage()
QCString TranslatorDanish::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1188 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "side", "r");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorDanish::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 799 of file translator_dk.h.
    { return "s."; }
trPageIndex()
QCString TranslatorDanish::trPageIndex () inline override virtual
Implements Translator.
Definition at line 877 of file translator_dk.h.
    { return "Sideindeks"; }
trParameters()
QCString TranslatorDanish::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 555 of file translator_dk.h.
    { return "Parametre"; }
trPostcondition()
QCString TranslatorDanish::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 858 of file translator_dk.h.
    { return "Resultat (postcondition)"; }
trPrecondition()
QCString TranslatorDanish::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 855 of file translator_dk.h.
    { return "Forudstninger (precondition)"; }
trPrivateAttribs()
QCString TranslatorDanish::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 908 of file translator_dk.h.
    { return "Private attributter"; }
trPrivateMembers()
QCString TranslatorDanish::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 655 of file translator_dk.h.
    { return "Private metoder"; }
trPrivateSlots()
QCString TranslatorDanish::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 657 of file translator_dk.h.
    { return "Private slots"; }
trPrivateTypes()
QCString TranslatorDanish::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 906 of file translator_dk.h.
    { return "Private typer"; }
trProperties()
QCString TranslatorDanish::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1058 of file translator_dk.h.
    {
      return "Egenskaber";
    }
trPropertyDocumentation()
QCString TranslatorDanish::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1063 of file translator_dk.h.
    {
      return "Egenskabsdokumentation";
    }
trProtectedAttribs()
QCString TranslatorDanish::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 902 of file translator_dk.h.
    { return "Beskyttede attributter"; }
trProtectedMembers()
QCString TranslatorDanish::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 649 of file translator_dk.h.
    { return "Beskyttede metoder"; }
trProtectedSlots()
QCString TranslatorDanish::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 651 of file translator_dk.h.
    { return "Beskyttede slots"; }
trProtectedTypes()
QCString TranslatorDanish::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 900 of file translator_dk.h.
    { return "Beskyttede typer"; }
trPublicAttribs()
QCString TranslatorDanish::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 889 of file translator_dk.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "Datafelter";
      } else {
        return "Offentlige attributter";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorDanish::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 641 of file translator_dk.h.
    { return "Offentlige metoder"; }
trPublicSlots()
QCString TranslatorDanish::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 643 of file translator_dk.h.
    { return "Offentlige slots"; }
trPublicTypes()
QCString TranslatorDanish::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 886 of file translator_dk.h.
    { return "Offentlige typer"; }
trReferencedBy()
QCString TranslatorDanish::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 932 of file translator_dk.h.
    {
      return "Refereret til af";
    }
trReferenceManual()
QCString TranslatorDanish::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 430 of file translator_dk.h.
    { return "Referencemanual"; }
trReferences()
QCString TranslatorDanish::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1228 of file translator_dk.h.
    {
      return "Indeholder referencer til";
    }
trReimplementedFromList()
QCString TranslatorDanish::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 704 of file translator_dk.h.
    {
      return "Overskriver metode fra "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorDanish::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 712 of file translator_dk.h.
    {
      return "Reimplementeret i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorDanish::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 596 of file translator_dk.h.
    { return "Dokumentation af friends og af relaterede funktioner"; }
trRelatedFunctions()
QCString TranslatorDanish::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 134 of file translator_dk.h.
    { return "Relaterede funktioner"; }
trRelatedPages()
QCString TranslatorDanish::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 263 of file translator_dk.h.
    { return "Relaterede sider"; }
trRelatedPagesDescription()
QCString TranslatorDanish::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 357 of file translator_dk.h.
    { return "Her er en liste over alle relaterede dokumentationssider:"; }
trRelatedSubscript()
QCString TranslatorDanish::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 138 of file translator_dk.h.
    { return "(Bemrk at disse ikke er medlems-funktioner.)"; }
trRemarks()
QCString TranslatorDanish::trRemarks () inline override virtual
Implements Translator.
Definition at line 936 of file translator_dk.h.
    {
      return "Bemrkninger";
    }
trReturns()
QCString TranslatorDanish::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 547 of file translator_dk.h.
    { return "Returnerer"; }
trReturnValues()
QCString TranslatorDanish::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 788 of file translator_dk.h.
    { return "Returvrdier"; }
trRTFansicp()
QCString TranslatorDanish::trRTFansicp () inline override virtual
Used as ansicpg for RTF file (used table extract:)
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
ANSI_CHARSET              0 (x00)            1252
Implements Translator.
Definition at line 1131 of file translator_dk.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorDanish::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1137 of file translator_dk.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorDanish::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1143 of file translator_dk.h.
    {
      return "Indeks";
    }
trRTFTableOfContents()
QCString TranslatorDanish::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1260 of file translator_dk.h.
    {
      return "Indholdsfortegnelse";
    }
trSearch()
QCString TranslatorDanish::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 271 of file translator_dk.h.
    { return "Sg"; }
trSearching()
QCString TranslatorDanish::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1678 of file translator_dk.h.
    {
      return "Sger...";    // "Searching..."
    }
trSearchMatches()
QCString TranslatorDanish::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1366 of file translator_dk.h.
    {
      return "Fundne ord:"; //translation?
    }
trSearchResults()
QCString TranslatorDanish::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1350 of file translator_dk.h.
    {
      if (numDocuments==0) {
        return "Beklager - ingen dokumenter passede til din foresprgsel.";
      } else if (numDocuments==1) {
        return "Fandt <b>1</b> dokument, der passer til din foresprgsel.";
      } else {
        return
          "Fandt <b>$num</b> dokumenter, der passer til din foresprgsel. "
          "De, der passer bedst, vises frst.";
      }
    }
trSearchResultsTitle()
QCString TranslatorDanish::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1337 of file translator_dk.h.
    {
      return "Sgeresultater";
    }
trSeeAlso()
QCString TranslatorDanish::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 551 of file translator_dk.h.
    { return "Se ogs"; }
trSignals()
QCString TranslatorDanish::trSignals () inline override virtual
Implements Translator.
Definition at line 645 of file translator_dk.h.
    { return "Signaler"; }
trSince()
QCString TranslatorDanish::trSince () inline override virtual
Implements Translator.
Definition at line 950 of file translator_dk.h.
    {
      return "Siden";
    }
trSourceFile()
QCString TranslatorDanish::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1378 of file translator_dk.h.
    {
      return "Kildefilen " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorDanish::trStaticPackageAttribs () inline override virtual
Implements Translator.
Definition at line 1309 of file translator_dk.h.
    { return "Statiske attributter med pakke-scope"; }
trStaticPackageFunctions()
QCString TranslatorDanish::trStaticPackageFunctions () inline override virtual
Implements Translator.
Definition at line 1305 of file translator_dk.h.
    { return "Statiske metoder med pakke-scope"; }
trStaticPrivateAttribs()
QCString TranslatorDanish::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 910 of file translator_dk.h.
    { return "Statiske, private attributter"; }
trStaticPrivateMembers()
QCString TranslatorDanish::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 659 of file translator_dk.h.
    { return "Statiske, private metoder"; }
trStaticProtectedAttribs()
QCString TranslatorDanish::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 904 of file translator_dk.h.
    { return "Statiske, beskyttede attributter"; }
trStaticProtectedMembers()
QCString TranslatorDanish::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 653 of file translator_dk.h.
    { return "Statiske, beskyttede metoder"; }
trStaticPublicAttribs()
QCString TranslatorDanish::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 898 of file translator_dk.h.
    { return "Statiske, offentlige attributter"; }
trStaticPublicMembers()
QCString TranslatorDanish::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 647 of file translator_dk.h.
    { return "Statiske, offentlige metoder"; }
trSubprogram()
QCString TranslatorDanish::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1644 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "subprogram", "er");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorDanish::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1519 of file translator_dk.h.
    { return "Funktion/Subroutine dokumentation"; } // "Function/Subroutine Documentation"
trSubprograms()
QCString TranslatorDanish::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1513 of file translator_dk.h.
    { return "Funktioner/Subroutiner"; } // "Functions/Subroutines"
trTest()
QCString TranslatorDanish::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1043 of file translator_dk.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorDanish::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1048 of file translator_dk.h.
    {
      return "Testliste";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorDanish::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 186 of file translator_dk.h.
    { return "Dette er den komplette liste over medlemmer i"; }
trTodo()
QCString TranslatorDanish::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 918 of file translator_dk.h.
    {
      return "Todo";
    }
trTodoList()
QCString TranslatorDanish::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 923 of file translator_dk.h.
    {
      return "Todo-liste";
    }
trType()
QCString TranslatorDanish::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1635 of file translator_dk.h.
    {
      return createNoun(first_capital, singular, "type", "r");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorDanish::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1650 of file translator_dk.h.
    {
      return "typebegrnsninger";        // "Type Constraints"
    }
trTypedefDocumentation()
QCString TranslatorDanish::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 478 of file translator_dk.h.
    { return "Dokumentation af typedefinitioner"; }
trTypedefs()
QCString TranslatorDanish::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 442 of file translator_dk.h.
    { return "Typedefinitioner"; }
trTypeDocumentation()
QCString TranslatorDanish::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1507 of file translator_dk.h.
    { return "Datatype dokumentation"; }   // "Data Type Documentation"
trVariableDocumentation()
QCString TranslatorDanish::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 502 of file translator_dk.h.
    { return "Variabel-dokumentation"; }
trVariables()
QCString TranslatorDanish::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 460 of file translator_dk.h.
    { return "Variable"; }
trVersion()
QCString TranslatorDanish::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 539 of file translator_dk.h.
    { return "Version"; }
trWarning()
QCString TranslatorDanish::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 535 of file translator_dk.h.
    { return "Advarsel"; }
trWriteList()
QCString TranslatorDanish::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 665 of file translator_dk.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) { // not the last entry, so we need a separator
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" og ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_dk.h