Doxygen: TranslatorSlovene Class Reference
TranslatorSlovene Class Reference
#include <src/translator_si.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
Public Member Functions inherited from TranslatorAdapter_1_4_6
QCString updateNeededMessage () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_6_0
QCString updateNeededMessage () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
Public Member Functions inherited from TranslatorAdapter_1_7_5
QCString updateNeededMessage () override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Public Member Functions inherited from TranslatorAdapter_1_8_0
QCString updateNeededMessage () override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 24 of file translator_si.h.
Member Function Documentation
getLanguageString()
QCString TranslatorSlovene::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 38 of file translator_si.h.
    {
      return "0x424 Slovenian";
    }
idLanguage()
QCString TranslatorSlovene::idLanguage () inline override virtual
Implements Translator.
Definition at line 27 of file translator_si.h.
    { return "slovene"; }
latexLanguageSupportCommand()
QCString TranslatorSlovene::latexLanguageSupportCommand () inline override virtual
Used to get the command(s) for the language support. This method was designed for languages which do not prefer babel package. If this methods returns empty string, then the latexBabelPackage() method is used to generate the command for using the babel package.
Implements Translator.
Definition at line 34 of file translator_si.h.
    { return "\\usepackage[slovene]{babel}\n"; }
trAll()
QCString TranslatorSlovene::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1026 of file translator_si.h.
    {
      return "Vse";
    }
trAttention()
QCString TranslatorSlovene::trAttention () inline override virtual
Implements Translator.
Definition at line 598 of file translator_si.h.
    {
      return "Pozor";
    }
trAuthor()
QCString TranslatorSlovene::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 901 of file translator_si.h.
    {
      return createNoun(first_capital, singular, "avtor", "ji");
    }
References Translator::createNoun().
trBug()
QCString TranslatorSlovene::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 773 of file translator_si.h.
    {
      return "Programska napaka";
    }
trBugList()
QCString TranslatorSlovene::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 778 of file translator_si.h.
    {
      return "Seznam programskih napak";
    }
trCallGraph()
QCString TranslatorSlovene::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1031 of file translator_si.h.
    {
      return "Graf klicev tekoe funkcije:";
    }
trClass()
QCString TranslatorSlovene::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 836 of file translator_si.h.
    {
      return createNoun(first_capital, singular, "razred", "i");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorSlovene::trClassDiagram (const QCString & clName) inline override virtual
Implements Translator.
Definition at line 189 of file translator_si.h.
    {
      return "Diagram razredov za "+clName;
    }
trClassDocumentation()
QCString TranslatorSlovene::trClassDocumentation () inline override virtual
Implements Translator.
Definition at line 151 of file translator_si.h.
    { return "Opis razreda"; }
trClasses()
QCString TranslatorSlovene::trClasses () inline override virtual
Used for Java interfaces in the summary section of Java packages
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 736 of file translator_si.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Podatkovne strukture";
      }
      else
      {
        return "Razredi";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorSlovene::trClassHierarchy () inline override virtual
Implements Translator.
Definition at line 85 of file translator_si.h.
    { return "dedovalna hierarhija"; }
trClassHierarchyDescription()
QCString TranslatorSlovene::trClassHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 101 of file translator_si.h.
      { return "Hierarhino drevo je (okvirno) sortirano po abecedi. ";
    }
trCode()
QCString TranslatorSlovene::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 506 of file translator_si.h.
    {
      return "koda";
    }
trCollaborationDiagram()
QCString TranslatorSlovene::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 455 of file translator_si.h.
    {
      return "Kolaboracijski diagram razreda "+clName+":";
    }
trCompoundIndex()
QCString TranslatorSlovene::trCompoundIndex () inline override virtual
Implements Translator.
Definition at line 145 of file translator_si.h.
    { return "abecedni seznam"; }
trCompoundList()
QCString TranslatorSlovene::trCompoundList () inline override virtual
Implements Translator.
Definition at line 87 of file translator_si.h.
    { return "kratek opis razredov"; }
trCompoundListDescription()
QCString TranslatorSlovene::trCompoundListDescription () inline override virtual
Implements Translator.
Definition at line 111 of file translator_si.h.
    { return "Seznam razredov, mnoic in struktur "
             "s kratkim opisom :";
    }
trCompoundMembers()
QCString TranslatorSlovene::trCompoundMembers () inline override virtual
Implements Translator.
Definition at line 91 of file translator_si.h.
    { return "metode in atributi"; }
trCompoundMembersDescription()
QCString TranslatorSlovene::trCompoundMembersDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 115 of file translator_si.h.
    {
      QCString result="Seznam vseh ";
      if (!extractAll) result+="dokumentiranih ";
      result+="metod in atributov s povezavami na ";
      if (extractAll) result+="opis posamezne metode in/ali atributa:";
      else result+="opis razreda :";
      return result;
    }
trCompoundReference()
QCString TranslatorSlovene::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool) inline override virtual
Implements Translator.
Definition at line 237 of file translator_si.h.
    {
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class:  result+=" Razred "; break;
        case ClassDef::Struct: result+=" Struktura "; break;
        case ClassDef::Union:  result+=" Mnoica "; break;
        case ClassDef::Interface:  result+=" IDL vmesnik "; break;
        case ClassDef::Protocol:   result+=" protocol "; break; // translate me!
        case ClassDef::Category:   result+=" category "; break; // translate me!
        case ClassDef::Exception:  result+=" IDL prekinitev "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorSlovene::trCompounds () inline override virtual
Implements Translator.
Definition at line 180 of file translator_si.h.
    { return "Strukture"; }
trConstructorDocumentation()
QCString TranslatorSlovene::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 471 of file translator_si.h.
    {
      return "Opis konstruktorjev in destruktorjev ";
    }
trDate()
QCString TranslatorSlovene::trDate () inline override virtual
Implements Translator.
Definition at line 197 of file translator_si.h.
    { return "Datum"; }
trDayOfWeek()
QCString TranslatorSlovene::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1147 of file translator_si.h.
    {
      static const char *days_short[]   = { "pon.", "tor.", "sre.", "et.", "pet.", "sob.", "ned." };
      static const char *days_full[]    = { "ponedeljek", "torek", "sreda", "etrtek", "petek", "sobota", "nedelja" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorSlovene::trDayPeriod (bool period) inline override virtual
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1163 of file translator_si.h.
    {
      static const char *dayPeriod[] = { "dop.", "pop." };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorSlovene::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 432 of file translator_si.h.
    {
      return "Definirano v @0 vrstici datoteke @1.";
    }
trDefinedIn()
QCString TranslatorSlovene::trDefinedIn () inline override virtual
Implements Translator.
Definition at line 81 of file translator_si.h.
    { return "definirano v"; }
trDefinedInSourceFile()
QCString TranslatorSlovene::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 436 of file translator_si.h.
    {
      return "Definirano v datoteki @0.";
    }
trDefineDocumentation()
QCString TranslatorSlovene::trDefineDocumentation () inline override virtual
Implements Translator.
Definition at line 170 of file translator_si.h.
    { return "Opis makro definicije"; }
trDefines()
QCString TranslatorSlovene::trDefines () inline override virtual
Implements Translator.
Definition at line 158 of file translator_si.h.
    { return "Makro deklaracije"; }
trDefineValue()
QCString TranslatorSlovene::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 763 of file translator_si.h.
    {
      return "Vrednost:";
    }
trDeprecated()
QCString TranslatorSlovene::trDeprecated () inline override virtual
Implements Translator.
Definition at line 445 of file translator_si.h.
    {
      return "Zastarelo";
    }
trDeprecatedList()
QCString TranslatorSlovene::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 954 of file translator_si.h.
    {
      return "Seznam opuenih";
    }
trDetailedDescription()
QCString TranslatorSlovene::trDetailedDescription () inline override virtual
Implements Translator.
Definition at line 46 of file translator_si.h.
    { return "Podroben opis"; }
trDetails()
QCString TranslatorSlovene::trDetails () inline override virtual
Implements Translator.
Definition at line 48 of file translator_si.h.
    { return "Podrobnosti"; }
trDir()
QCString TranslatorSlovene::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1128 of file translator_si.h.
    {
      return createNoun(first_capital, singular, "imenik", "i");
    }
References Translator::createNoun().
trDirDocumentation()
QCString TranslatorSlovene::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1107 of file translator_si.h.
    { return "Opisi imenikov"; }
trDirectories()
QCString TranslatorSlovene::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1113 of file translator_si.h.
    { return "Imeniki"; }
trDirIndex()
QCString TranslatorSlovene::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1101 of file translator_si.h.
    { return "Hierarhija imenikov"; }
trDirReference()
QCString TranslatorSlovene::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1119 of file translator_si.h.
    { QCString result=dirName;
      result+=" imenike reference"; /* not sure for context */
      return result;
    }
trDocumentation()
QCString TranslatorSlovene::trDocumentation (const QCString & projName) inline override virtual
Implements Translator.
Definition at line 139 of file translator_si.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentacija"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorSlovene::trEnumerations () inline override virtual
Implements Translator.
Definition at line 162 of file translator_si.h.
    { return "Natevni tipi"; }
trEnumerationTypeDocumentation()
QCString TranslatorSlovene::trEnumerationTypeDocumentation () inline override virtual
Implements Translator.
Definition at line 174 of file translator_si.h.
    { return "Opis natevnega (enum) tipa"; }
trEnumerationValues()
QCString TranslatorSlovene::trEnumerationValues () inline override virtual
Implements Translator.
Definition at line 168 of file translator_si.h.
    { return "Vrednosti natevnih tipov"; }
trEnumName()
QCString TranslatorSlovene::trEnumName () inline override virtual
Implements Translator.
Definition at line 77 of file translator_si.h.
    { return "natevno ime"; }
trEnumValue()
QCString TranslatorSlovene::trEnumValue () inline override virtual
Implements Translator.
Definition at line 79 of file translator_si.h.
    { return "natevna vrednost"; }
trEventDocumentation()
QCString TranslatorSlovene::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 971 of file translator_si.h.
    {
      return "Opisi dogodkov";
    }
trEvents()
QCString TranslatorSlovene::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 966 of file translator_si.h.
    {
      return "Dogodki";
    }
trExamples()
QCString TranslatorSlovene::trExamples () inline override virtual
Implements Translator.
Definition at line 97 of file translator_si.h.
    { return "Primeri"; }
trExamplesDescription()
QCString TranslatorSlovene::trExamplesDescription () inline override virtual
Implements Translator.
Definition at line 133 of file translator_si.h.
    { return "Seznam primerov :"; }
trExceptions()
QCString TranslatorSlovene::trExceptions () inline override virtual
Implements Translator.
Definition at line 205 of file translator_si.h.
    { return "Prekinitve"; }
trFile()
QCString TranslatorSlovene::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 845 of file translator_si.h.
    {
      return createNoun(first_capital, singular, "datotek", "e", "a");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorSlovene::trFileDocumentation () inline override virtual
Implements Translator.
Definition at line 153 of file translator_si.h.
    { return "Opis datoteke"; }
trFileIndex()
QCString TranslatorSlovene::trFileIndex () inline override virtual
Implements Translator.
Definition at line 147 of file translator_si.h.
    { return "seznam datotek"; }
trFileList()
QCString TranslatorSlovene::trFileList () inline override virtual
Implements Translator.
Definition at line 89 of file translator_si.h.
    { return "seznam datotek"; }
trFileListDescription()
QCString TranslatorSlovene::trFileListDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 104 of file translator_si.h.
    {
      QCString result="Seznam vseh ";
      if (!extractAll) result+="dokumentiranih ";
      result+="datotek s kratkim opisom:";
      return result;
    }
trFileMembers()
QCString TranslatorSlovene::trFileMembers () inline override virtual
Implements Translator.
Definition at line 93 of file translator_si.h.
    { return "komponente v datotekah"; }
trFileMembersDescription()
QCString TranslatorSlovene::trFileMembersDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 124 of file translator_si.h.
    {
      QCString result="Seznam ";
      if (!extractAll) result+="dokumentiranih ";
      result+="entitet v datotekah ";
      if (extractAll) result+="skupaj z opisom datoteke v kateri se nahajajo:";
      else result+="s povezavami na datoteke v katerih se nahajajo:";
      return result;
    }
trFileReference()
QCString TranslatorSlovene::trFileReference (const QCString & fileName) inline override virtual
Implements Translator.
Definition at line 258 of file translator_si.h.
    {
      QCString result="Datoteka ";
          result+=fileName;
          return result;
    }
trFriends()
QCString TranslatorSlovene::trFriends () inline override virtual
Implements Translator.
Definition at line 223 of file translator_si.h.
    { return "Prijatelji (Friends) "; }
trFunctionDocumentation()
QCString TranslatorSlovene::trFunctionDocumentation () inline override virtual
Implements Translator.
Definition at line 176 of file translator_si.h.
    { return "Opis funkcije"; }
trFunctions()
QCString TranslatorSlovene::trFunctions () inline override virtual
Implements Translator.
Definition at line 164 of file translator_si.h.
    { return "Funkcije"; }
trGeneratedAt()
QCString TranslatorSlovene::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
Implements Translator.
Definition at line 182 of file translator_si.h.
    {
      QCString result="Generirano "+date;
      if (!projName.isEmpty()) result+=" projekt: "+projName;
      result+=" generator: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorSlovene::trGeneratedAutomatically (const QCString & s) inline override virtual
Implements Translator.
Definition at line 71 of file translator_si.h.
    { QCString result="zgenerirano z Doxygen-om";
      if (!s.isEmpty()) result+=" za "+s;
      result+=" iz izvorne kode.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorSlovene::trGeneratedBy () inline override virtual
Implements Translator.
Definition at line 207 of file translator_si.h.
    { return "Izdelano s pomojo"; }
trGeneratedFromFiles()
QCString TranslatorSlovene::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 386 of file translator_si.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Opis ";
      switch(compType)
      {
        case ClassDef::Class:      result+="razreda"; break;
        case ClassDef::Struct:     result+="strukture"; break;
        case ClassDef::Union:      result+="unije"; break;
        case ClassDef::Interface:  result+="vmesnika (interface)"; break;
        case ClassDef::Protocol:   result+="protocol"; break; // translate me!
        case ClassDef::Category:   result+="category"; break; // translate me!
        case ClassDef::Exception:  result+="prekinitve (exception)"; break;
        default: break;
      }
      result+=" je zgrajen na podlagi naslednj";
      if (single) result+="e "; else result+="ih";
      result+=" datotek";
      if (single) result+="e :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorSlovene::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 890 of file translator_si.h.
    {
      return createNoun(first_capital, singular, "global", "s");
    }
References Translator::createNoun().
trGotoDocumentation()
QCString TranslatorSlovene::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 481 of file translator_si.h.
    {
      return "dokumenacija tekoe datoteke.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorSlovene::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 514 of file translator_si.h.
    {
      return "Dedovalna hierarhija v grafini obliki";
    }
trGotoSourceCode()
QCString TranslatorSlovene::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 476 of file translator_si.h.
    {
      return "izvorna koda";
    }
trGotoTextualHierarchy()
QCString TranslatorSlovene::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 518 of file translator_si.h.
    {
      return "Dedovalna hierarhija v tekstovni obliki";
    }
trGraphicalHierarchy()
QCString TranslatorSlovene::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 510 of file translator_si.h.
    {
      return "Hierarhija razredov v grafini obliki";
    }
trGroup()
QCString TranslatorSlovene::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 863 of file translator_si.h.
    {
      return createNoun(first_capital, singular, "skupina", "s");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorSlovene::trHierarchicalIndex () inline override virtual
Implements Translator.
Definition at line 143 of file translator_si.h.
    { return "Hierarhini indeks"; }
trImplementedFromList()
QCString TranslatorSlovene::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 922 of file translator_si.h.
    {
      return "Implementira "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorSlovene::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 930 of file translator_si.h.
    {
      return "Implementirano v "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorSlovene::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 602 of file translator_si.h.
    {
      return "Graf prikazuje datoteke, ki posredno ali neposredno "
             "vkljuujejo tekoo datoteko. Pravokotniki simbolizirajo datoteke, "
             "puice pa relacije med datotekami. Tekoa datoteka je prikazana "
             "kot pravokotnik s rno podlago, ostale pa kot pravokotnik brez podlage. "
             "Smer puice A->B definira relacijo \"A vkljuuje B\". "
             "Vse datoteke, ki torej mejijo na tekoo (t.j. obstaja povezava med rnim in "
             "praznim pravokotnikom), jo direktno vkljuujejo, medtem, ko jo ostale vkljuujejo "
             "le posredno. "
        ;
    }
trInclDepGraph()
QCString TranslatorSlovene::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 460 of file translator_si.h.
    {
      return "Graf prikazuje seznam datotek, "
          "ki jih datoteka \""+fName+"\" "
          "direktno ali indirektno vkljuuje. Pravokotniki ponazarjajo datoteke, puice "
          "predstavljajo relacije med njimi. "
          "rn pravokotnik ponazarja datoteko "+fName+". Puice A->B ponazarjajo "
          "usmerjeno relacijo \"A vkljuuje B\"."
;
    }
trIncludingInheritedMembers()
QCString TranslatorSlovene::trIncludingInheritedMembers () inline override virtual
Implements Translator.
Definition at line 69 of file translator_si.h.
    { return ", vkljuujo dedovane metode in atribute."; }
trInheritedByList()
QCString TranslatorSlovene::trInheritedByList (int numEntries) inline override virtual
Implements Translator.
Definition at line 326 of file translator_si.h.
    {
      return "Naslijeena u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList()
QCString TranslatorSlovene::trInheritsList (int numEntries) inline override virtual
Implements Translator.
Definition at line 320 of file translator_si.h.
    {
      return "Deduje od "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorSlovene::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 501 of file translator_si.h.
    {
      return "Zaetna vrednost / definicija :";
    }
trInvariant()
QCString TranslatorSlovene::trInvariant () inline override virtual
Text for the
Invariant
command
Implements Translator.
Definition at line 496 of file translator_si.h.
    {
      return "Invarianta";
    }
trISOLang()
QCString TranslatorSlovene::trISOLang () inline override virtual
Implements Translator.
Definition at line 36 of file translator_si.h.
    { return "sl"; }
trLegend()
QCString TranslatorSlovene::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 691 of file translator_si.h.
    {
      return "legenda";
    }
trLegendDocs()
QCString TranslatorSlovene::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 631 of file translator_si.h.
    {
      return
        "Tekoa stran pojasnjuje nain interpretacije grafov, ki jih izrie "
        "doxygen.<p>\n"
        "Poglejmo si naslednji primer:\n"
        "\\code\n"
        "/*! Nevide razred zaradi rezanja */\n"
        "class Invisible { };\n\n"
        "/*! Odrezan razred, dedovalna relacija je skrita */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* razred, ki ni opisan z doxygen komentarji */\n"
        "class Undocumented { };\n\n"
        "/*! Razred, ki ga dedujemo s pomojo javnega dedovanja */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Razred, ki ga dedujemo s pomojo zaitenega dedovanja */\n"
        "class ProtectedBase { };\n\n"
        "/*! Razred, ki ga dedujemo s pomojo skritega dedovanja */\n"
        "class PrivateBase { };\n\n"
        "/*! Razred, ki ga uporablja dedovani razred */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "If the \\c MAX_DOT_GRAPH_HEIGHT tag in the configuration file "
        "is set to 200 this will result in the following graph:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>%A filled black box represents the struct or class for which the "
        "graph is generated.\n"
        "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.\n"
        "<li>%A box with a red border denotes a documented struct or class for\n"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries."
        "</ul>\n"
        "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.\n"
        "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible. \n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorSlovene::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 624 of file translator_si.h.
    {
      return "Legenda grafa";
    }
trListOfAllMembers()
QCString TranslatorSlovene::trListOfAllMembers () inline override virtual
Implements Translator.
Definition at line 63 of file translator_si.h.
    { return "Seznam vseh metod / atributov"; }
trMainPage()
QCString TranslatorSlovene::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 419 of file translator_si.h.
    { return "prva stran"; }
trMember()
QCString TranslatorSlovene::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 881 of file translator_si.h.
    {
      return createNoun(first_capital, singular, "element", "i");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorSlovene::trMemberDataDocumentation () inline override virtual
Implements Translator.
Definition at line 59 of file translator_si.h.
    { return "Opis atributov"; }
trMemberEnumerationDocumentation()
QCString TranslatorSlovene::trMemberEnumerationDocumentation () inline override virtual
Implements Translator.
Definition at line 53 of file translator_si.h.
    { return "Opis komponent  natevnih tipov"; }
trMemberFunctionDocumentation()
QCString TranslatorSlovene::trMemberFunctionDocumentation () inline override virtual
Implements Translator.
Definition at line 57 of file translator_si.h.
    { return "Opis metod"; }
trMemberList()
QCString TranslatorSlovene::trMemberList () inline override virtual
Implements Translator.
Definition at line 65 of file translator_si.h.
    { return " - seznam metod in atributov."; }
trMemberTypedefDocumentation()
QCString TranslatorSlovene::trMemberTypedefDocumentation () inline override virtual
Implements Translator.
Definition at line 51 of file translator_si.h.
    { return "Opis uporabniko definiranih tipov"; }
trModuleDocumentation()
QCString TranslatorSlovene::trModuleDocumentation () inline override virtual
Implements Translator.
Definition at line 149 of file translator_si.h.
    { return "Dokumentacija modulov"; }
trModuleIndex()
QCString TranslatorSlovene::trModuleIndex () inline override virtual
Implements Translator.
Definition at line 141 of file translator_si.h.
    { return "seznam modulov"; }
trModules()
QCString TranslatorSlovene::trModules () inline override virtual
Implements Translator.
Definition at line 83 of file translator_si.h.
    { return "moduli"; }
trModulesDescription()
QCString TranslatorSlovene::trModulesDescription () inline override virtual
Implements Translator.
Definition at line 137 of file translator_si.h.
    { return "Seznam modulov:"; }
trMonth()
QCString TranslatorSlovene::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1155 of file translator_si.h.
    {
      static const char *months_short[] = { "jan.", "feb.", "mar.", "apr.", "maj", "jun.", "jul.", "avg.", "sep.", "okt.", "nov.", "dec." };
      static const char *months_full[]  = { "januar", "februar", "marec", "april", "maj", "junij", "julij", "avgust", "september", "oktober", "november", "december" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorSlovene::trMore () inline override virtual
Implements Translator.
Definition at line 61 of file translator_si.h.
    { return "..."; }
trNamespace()
QCString TranslatorSlovene::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 854 of file translator_si.h.
    {
      return createNoun(first_capital, singular, "imenski prostor", "i");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorSlovene::trNamespaceDocumentation () inline override virtual
Implements Translator.
Definition at line 364 of file translator_si.h.
    { return "Podatki o imenskih prostorih"; }
trNamespaceIndex()
QCString TranslatorSlovene::trNamespaceIndex () inline override virtual
Implements Translator.
Definition at line 360 of file translator_si.h.
    { return "Indeks imenskih prostorov"; }
trNamespaceList()
QCString TranslatorSlovene::trNamespaceList () inline override virtual
Implements Translator.
Definition at line 214 of file translator_si.h.
    { return "imenski prostori"; }
trNamespaceListDescription()
QCString TranslatorSlovene::trNamespaceListDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 216 of file translator_si.h.
    {
      QCString result="Seznam ";
      if (!extractAll) result+="dokumentiranih ";
      result+="imenskih prostorov z opisom:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorSlovene::trNamespaceMemberDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 348 of file translator_si.h.
    {
      QCString result="Seznam vseh ";
      if (!extractAll) result+="dokumentiranih ";
      result+="elementov imenskega prostora s povezavami na ";
      if (extractAll)
        result+="opis vsakega elementa:";
      else
        result+="imenski prostor, ki mu pripadajo:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorSlovene::trNamespaceMembers () inline override virtual
Implements Translator.
Definition at line 345 of file translator_si.h.
    { return "elementi imenskega prostora"; }
trNamespaceReference()
QCString TranslatorSlovene::trNamespaceReference (const QCString & namespaceName) inline override virtual
Implements Translator.
Definition at line 265 of file translator_si.h.
    {
      QCString result ="Imenski prostor ";
          result+=namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorSlovene::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 375 of file translator_si.h.
    { return "Imenski prostori"; }
trNote()
QCString TranslatorSlovene::trNote () inline override virtual
Implements Translator.
Definition at line 531 of file translator_si.h.
    {
      return "Opomba";
    }
trOverloadText()
QCString TranslatorSlovene::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1140 of file translator_si.h.
    {
      return "To je ponovno definirana metoda, " /* don't know Slovene expresion for overloaded */
             "podana je zaradi prironosti. Metoda se od predhodnje razlikuje "
             "samo v tevilu in/ali tipu formalnih argumentov.";
    }
trPackage()
QCString TranslatorSlovene::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 748 of file translator_si.h.
    {
      return "JAVA paket "+name;
    }
trPackageAttribs()
QCString TranslatorSlovene::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1007 of file translator_si.h.
    {
      return "Atributi paketa";
    }
trPackageFunctions()
QCString TranslatorSlovene::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 989 of file translator_si.h.
    {
      return "Funkcije paketa";   /* don't know the context */
    }
trPackageListDescription()
QCString TranslatorSlovene::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 753 of file translator_si.h.
    {
      return "Seznam JAVA paketov in njihovih kratkih opisov v primeru, da obstajajo:";
    }
trPackageMembers()
QCString TranslatorSlovene::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 993 of file translator_si.h.
    {
      return "Elemente paketa";   /* don't know the context */
    }
trPackages()
QCString TranslatorSlovene::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 758 of file translator_si.h.
    {
      return "JAVA paketi";
    }
trPackageTypes()
QCString TranslatorSlovene::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 982 of file translator_si.h.
    {
      return "Tipi paketov";
    }
trPage()
QCString TranslatorSlovene::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 872 of file translator_si.h.
    {
      return createNoun(first_capital, singular, "stran", "i");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorSlovene::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 425 of file translator_si.h.
    { return "str."; }
trPageIndex()
QCString TranslatorSlovene::trPageIndex () inline override virtual
Implements Translator.
Definition at line 522 of file translator_si.h.
    {
      return "Indeks strani";
    }
trParameters()
QCString TranslatorSlovene::trParameters () inline override virtual
Implements Translator.
Definition at line 203 of file translator_si.h.
    { return "Parametri"; }
trPostcondition()
QCString TranslatorSlovene::trPostcondition () inline override virtual
Text for the
Postcondition
command
Implements Translator.
Definition at line 491 of file translator_si.h.
    {
      return "Naknadni pogoji (posconditions)";
    }
trPrecondition()
QCString TranslatorSlovene::trPrecondition () inline override virtual
Text for the
Precondition
command
Implements Translator.
Definition at line 486 of file translator_si.h.
    {
      return "Predpogoji (preconditions)";
    }
trPrivateAttribs()
QCString TranslatorSlovene::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 563 of file translator_si.h.
    {
      return "Skriti atributi";
    }
trPrivateMembers()
QCString TranslatorSlovene::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 289 of file translator_si.h.
    { return "Skrite metode in atributi"; }
trPrivateSlots()
QCString TranslatorSlovene::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 291 of file translator_si.h.
    { return "Skriti slotovi"; }
trPrivateTypes()
QCString TranslatorSlovene::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 559 of file translator_si.h.
    {
      return "Skriti tipi";
    }
trProperties()
QCString TranslatorSlovene::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 716 of file translator_si.h.
    {
      return "IDL Lastnosti";
    }
trPropertyDocumentation()
QCString TranslatorSlovene::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 721 of file translator_si.h.
    {
      return "Opis IDL lastnosti";
    }
trProtectedAttribs()
QCString TranslatorSlovene::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 551 of file translator_si.h.
    {
      return "Zaiteni atributi";
    }
trProtectedMembers()
QCString TranslatorSlovene::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 283 of file translator_si.h.
    { return "Zaitene metode in atributi"; }
trProtectedSlots()
QCString TranslatorSlovene::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 285 of file translator_si.h.
    { return "Zaiteni sloti"; }
trProtectedTypes()
QCString TranslatorSlovene::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 547 of file translator_si.h.
    {
      return "Zaiteni tipi";
    }
trPublicAttribs()
QCString TranslatorSlovene::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 539 of file translator_si.h.
    {
      return "Javni atributi";
    }
trPublicMembers()
QCString TranslatorSlovene::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 275 of file translator_si.h.
    { return "Javne metode"; }
trPublicSlots()
QCString TranslatorSlovene::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 277 of file translator_si.h.
    { return "Public slotovi"; }
trPublicTypes()
QCString TranslatorSlovene::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 535 of file translator_si.h.
    {
      return "Javni tipi";
    }
trReferencedBy()
QCString TranslatorSlovene::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 590 of file translator_si.h.
    {
      return "Uporabniki entitete:  ";
    }
trReferenceManual()
QCString TranslatorSlovene::trReferenceManual () inline override virtual
Implements Translator.
Definition at line 155 of file translator_si.h.
    { return "Prironik"; }
trReferences()
QCString TranslatorSlovene::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 911 of file translator_si.h.
    {
      return "Reference";
    }
trReimplementedFromList()
QCString TranslatorSlovene::trReimplementedFromList (int numEntries) inline override virtual
Implements Translator.
Definition at line 332 of file translator_si.h.
    {
      return "Skrije implementacijo iz "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorSlovene::trReimplementedInList (int numEntries) inline override virtual
Implements Translator.
Definition at line 338 of file translator_si.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "Metodo skrijejo implementacije v razredih "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorSlovene::trRelatedFunctionDocumentation () inline override virtual
Implements Translator.
Definition at line 230 of file translator_si.h.
    { return "Podatki o poveznih funkcijah"; }
trRelatedFunctions()
QCString TranslatorSlovene::trRelatedFunctions () inline override virtual
Implements Translator.
Definition at line 42 of file translator_si.h.
    { return "Povezane funkcije"; }
trRelatedPages()
QCString TranslatorSlovene::trRelatedPages () inline override virtual
Implements Translator.
Definition at line 95 of file translator_si.h.
    { return "dodatni opisi"; }
trRelatedPagesDescription()
QCString TranslatorSlovene::trRelatedPagesDescription () inline override virtual
Implements Translator.
Definition at line 135 of file translator_si.h.
    { return "Seznam strani z dodatnimi opisi:"; }
trRelatedSubscript()
QCString TranslatorSlovene::trRelatedSubscript () inline override virtual
Implements Translator.
Definition at line 44 of file translator_si.h.
    { return "(To niso metode.)"; }
trRemarks()
QCString TranslatorSlovene::trRemarks () inline override virtual
Implements Translator.
Definition at line 594 of file translator_si.h.
    {
      return "Opomba";
    }
trReturns()
QCString TranslatorSlovene::trReturns () inline override virtual
Implements Translator.
Definition at line 199 of file translator_si.h.
    { return "Rezultat(i)"; }
trReturnValues()
QCString TranslatorSlovene::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 414 of file translator_si.h.
    { return "Povratna vrednost"; }
trRTFansicp()
QCString TranslatorSlovene::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 812 of file translator_si.h.
    {
      return "1250";
    }
trRTFCharSet()
QCString TranslatorSlovene::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 821 of file translator_si.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorSlovene::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 827 of file translator_si.h.
    {
      return "Indeks";
    }
trRTFTableOfContents()
QCString TranslatorSlovene::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 942 of file translator_si.h.
    {
      return "Vsebina";
    }
trSearch()
QCString TranslatorSlovene::trSearch () inline override virtual
Implements Translator.
Definition at line 99 of file translator_si.h.
    { return "Ii"; }
trSearchMatches()
QCString TranslatorSlovene::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1078 of file translator_si.h.
    {
      return "Zadetki:";
    }
trSearchResults()
QCString TranslatorSlovene::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1055 of file translator_si.h.
    {
      if (numDocuments==0)
      {
        return "Oprostite, noben dokument ne ustreza vaemu povpraevanju.";
      }
      else if (numDocuments==1)
      {
        return "Nael sem <b>1</b> dokument, ki ustreza vaemu povpraevanju.";
      }
      else if (numDocuments==2)
      {
        return "Nael sem <b>2</b> dokumenta, ki ustrezata vaemu povpraevanju.";
      }
      else
      {
        return "Nael sem <b>$num</b> dokumentov, ki ustrezajo vaemu povpraevanju. "
               "Dokumenti z najboljo stopnjo ujemanja se nahajajo na zaetku.";
      }
    }
trSearchResultsTitle()
QCString TranslatorSlovene::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1043 of file translator_si.h.
    {
      return "Rezultat(i) iskanja";
    }
trSeeAlso()
QCString TranslatorSlovene::trSeeAlso () inline override virtual
Implements Translator.
Definition at line 201 of file translator_si.h.
    { return "Glej"; }
trSignals()
QCString TranslatorSlovene::trSignals () inline override virtual
Implements Translator.
Definition at line 279 of file translator_si.h.
    { return "Programske prekinitve"; }
trSince()
QCString TranslatorSlovene::trSince () inline override virtual
Implements Translator.
Definition at line 614 of file translator_si.h.
    {
      return "Od";
    }
trSourceFile()
QCString TranslatorSlovene::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1089 of file translator_si.h.
    {
      return filename + " izvorna koda";
    }
trStaticPackageAttribs()
QCString TranslatorSlovene::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1014 of file translator_si.h.
    {
      return "Statini atributi paketa";
    }
trStaticPackageFunctions()
QCString TranslatorSlovene::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1000 of file translator_si.h.
    {
      return "Statine funkcije paketa";
    }
trStaticPrivateAttribs()
QCString TranslatorSlovene::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 567 of file translator_si.h.
    {
      return "Statini skriti atributi";
    }
trStaticPrivateMembers()
QCString TranslatorSlovene::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 293 of file translator_si.h.
    { return "Statine skrite metode in atributi"; }
trStaticProtectedAttribs()
QCString TranslatorSlovene::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 555 of file translator_si.h.
    {
      return "Statini zaiteni tipi";
    }
trStaticProtectedMembers()
QCString TranslatorSlovene::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 287 of file translator_si.h.
    { return "Statine zaitene metode in atributi"; }
trStaticPublicAttribs()
QCString TranslatorSlovene::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 543 of file translator_si.h.
    {
      return "Statini javni atributi";
    }
trStaticPublicMembers()
QCString TranslatorSlovene::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 281 of file translator_si.h.
    { return "Statine javne metode in atributi"; }
trTest()
QCString TranslatorSlovene::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 701 of file translator_si.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorSlovene::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 706 of file translator_si.h.
    {
      return "Test List";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorSlovene::trThisIsTheListOfAllMembers () inline override virtual
Implements Translator.
Definition at line 67 of file translator_si.h.
    { return "Seznam metod razreda"; }
trTodo()
QCString TranslatorSlovene::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 576 of file translator_si.h.
    {
      return "TODO";
    }
trTodoList()
QCString TranslatorSlovene::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 581 of file translator_si.h.
    {
      return "Seznam nedokonanih opravil";
    }
trTypedefDocumentation()
QCString TranslatorSlovene::trTypedefDocumentation () inline override virtual
Implements Translator.
Definition at line 172 of file translator_si.h.
    { return "Opis uporabniko definiranega tipa"; }
trTypedefs()
QCString TranslatorSlovene::trTypedefs () inline override virtual
Implements Translator.
Definition at line 160 of file translator_si.h.
    { return "Uporabniko definirani tipi"; }
trVariableDocumentation()
QCString TranslatorSlovene::trVariableDocumentation () inline override virtual
Implements Translator.
Definition at line 178 of file translator_si.h.
    { return "Opis spremenljivke"; }
trVariables()
QCString TranslatorSlovene::trVariables () inline override virtual
Implements Translator.
Definition at line 166 of file translator_si.h.
    { return "Spremenljivke"; }
trVersion()
QCString TranslatorSlovene::trVersion () inline override virtual
Implements Translator.
Definition at line 195 of file translator_si.h.
    { return "Verzija"; }
trWarning()
QCString TranslatorSlovene::trWarning () inline override virtual
Implements Translator.
Definition at line 193 of file translator_si.h.
    { return "Opozorilo"; }
trWriteList()
QCString TranslatorSlovene::trWriteList (int numEntries) inline override virtual
Implements Translator.
Definition at line 297 of file translator_si.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" in ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_si.h