Doxygen: TranslatorAfrikaans Class Reference
TranslatorAfrikaans Class Reference
#include <src/translator_za.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
Public Member Functions inherited from TranslatorAdapter_1_6_0
QCString updateNeededMessage () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
Public Member Functions inherited from TranslatorAdapter_1_7_5
QCString updateNeededMessage () override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Public Member Functions inherited from TranslatorAdapter_1_8_0
QCString updateNeededMessage () override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 29 of file translator_za.h.
Member Function Documentation
getLanguageString()
QCString TranslatorAfrikaans::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 66 of file translator_za.h.
    {
      return "0x436 Afrikaans";
    }
idLanguage()
QCString TranslatorAfrikaans::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 41 of file translator_za.h.
    { return "afrikaans"; }
latexLanguageSupportCommand()
QCString TranslatorAfrikaans::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The Afrikaans LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 58 of file translator_za.h.
    {
      return "\\usepackage[afrikaans]{babel}\n";
    }
trAll()
QCString TranslatorAfrikaans::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1365 of file translator_za.h.
    {
      return "Alle Lede";
    }
trAttention()
QCString TranslatorAfrikaans::trAttention () inline override virtual
Implements Translator.
Definition at line 944 of file translator_za.h.
    {
      return "Aandag";
    }
trAuthor()
QCString TranslatorAfrikaans::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1238 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "outeur", "s");
    }
References Translator::createNoun().
trBug()
QCString TranslatorAfrikaans::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1110 of file translator_za.h.
    {
      return "Bug";
    }
trBugList()
QCString TranslatorAfrikaans::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1115 of file translator_za.h.
    {
      return "Bug Lys";
    }
trCallerGraph()
QCString TranslatorAfrikaans::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1484 of file translator_za.h.
    {
      return "Hier is die roep skema vir die funksie:";
    }
trCallGraph()
QCString TranslatorAfrikaans::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1370 of file translator_za.h.
    {
      return "'n gebruiks diagram vir hierdie funksie:";
    }
trClass()
QCString TranslatorAfrikaans::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1173 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "klas", "se");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorAfrikaans::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 498 of file translator_za.h.
    {
      return "Afleidings diagram vir "+clName+":";
    }
trClassDocumentation()
QCString TranslatorAfrikaans::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 379 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture Dokumentasie";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klas Dokumentasie";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorAfrikaans::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1073 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture";
      }
      else
      {
        return "Klasse";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorAfrikaans::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 165 of file translator_za.h.
    { return "Klas Hierargie"; }
trClassHierarchyDescription()
QCString TranslatorAfrikaans::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 224 of file translator_za.h.
    {
      return "Hierdie afgeleide lys word rofweg gesorteer: ";
    }
trCode()
QCString TranslatorAfrikaans::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 844 of file translator_za.h.
    {
      return "kode";
    }
trCollaborationDiagram()
QCString TranslatorAfrikaans::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 799 of file translator_za.h.
    {
      return "Samewerkings diagram vir "+clName+":";
    }
trCompoundIndex()
QCString TranslatorAfrikaans::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 352 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture Indeks";
      }
      else
      {
        return "Klas Indeks";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorAfrikaans::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1539 of file translator_za.h.
    { return "Data Tipe Indeks"; }
trCompoundList()
QCString TranslatorAfrikaans::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 169 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture";
      }
      else
      {
        return "Klas Lys";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorAfrikaans::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 239 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " Data strukture met kort beskrywings:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Klasse met kort beskrywings:";
      }
      else
      {
        return "Klasse, structs, "
               "unions en intervlakke met kort beskrywings:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorAfrikaans::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1512 of file translator_za.h.
    { return "Hier is die data tipes met kort beskrywings:"; }
trCompoundListFortran()
QCString TranslatorAfrikaans::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1504 of file translator_za.h.
    { return "Data Tipes Lys"; }
trCompoundMembers()
QCString TranslatorAfrikaans::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 186 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Velde";
      }
      else
      {
        return "Klas Lede";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorAfrikaans::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 258 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll)
      {
        result+="gedokumenteerde ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct en union velde";
      }
      else
      {
        result+="klas lede";
      }
      result+=" met skakels na ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die struct/union dokumentasie vir elke veld:";
        }
        else
        {
          result+="die klas dokumentasie vir elke lid:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die structures/unions waaraan hulle behoort:";
        }
        else
        {
          result+="die klasse waaraan hulle behoort:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorAfrikaans::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1516 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle ";
      if (!extractAll)
      {
        result+="gedokumenteerde ";
      }
      result+="data tipe lede";
      result+=" met skakels na ";
      if (!extractAll)
      {
         result+="die data strukture dokumentasie vir elke lid";
      }
      else
      {
         result+="die data tipes waaraan hulle behoort:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorAfrikaans::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1508 of file translator_za.h.
    { return "Data Velde"; }
trCompoundReference()
QCString TranslatorAfrikaans::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 573 of file translator_za.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" klas"; break;
        case ClassDef::Struct:     result+=" Struct"; break;
        case ClassDef::Union:      result+=" Union"; break;
        case ClassDef::Interface:  result+=" Intervlak"; break;
        case ClassDef::Protocol:   result+=" Protocol"; break;
        case ClassDef::Category:   result+=" Kategorie"; break;
        case ClassDef::Exception:  result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Verwysing";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorAfrikaans::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1580 of file translator_za.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Module"; break;
        case ClassDef::Struct:     result+=" Tipe"; break;
        case ClassDef::Union:      result+=" Unie"; break;
        case ClassDef::Interface:  result+=" Interflak"; break;
        case ClassDef::Protocol:   result+=" Protokol"; break;
        case ClassDef::Category:   result+=" Kategorie"; break;
        case ClassDef::Exception:  result+=" Eksepsie"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Bron";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorAfrikaans::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 474 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture";
      }
      else
      {
        return "Klasse";
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorAfrikaans::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 809 of file translator_za.h.
    {
      return "Konstruktor & Destruktor Dokumentasie";
    }
trDataTypes()
QCString TranslatorAfrikaans::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1563 of file translator_za.h.
    { return "Data Tipes"; }
trDate()
QCString TranslatorAfrikaans::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 512 of file translator_za.h.
    { return "Datum"; }
trDayOfWeek()
QCString TranslatorAfrikaans::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1689 of file translator_za.h.
    {
      static const char *days_short[]   = { "Ma.", "Di.", "Wo.", "Do.", "Vr.", "Sa.", "So." };
      static const char *days_full[]    = { "Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrydag", "Saterdag", "Sondag" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorAfrikaans::trDayPeriod (bool period) inline override virtual
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1705 of file translator_za.h.
    {
      static const char *dayPeriod[] = { "vm.", "nm." };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorAfrikaans::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 776 of file translator_za.h.
    {
      return "Gedefinier by lyn @0 van ler @1.";
    }
trDefinedIn()
QCString TranslatorAfrikaans::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 153 of file translator_za.h.
    { return "gedefinier in"; }
trDefinedInSourceFile()
QCString TranslatorAfrikaans::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 780 of file translator_za.h.
    {
      return "Definisie in ler @0.";
    }
trDefineDocumentation()
QCString TranslatorAfrikaans::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 444 of file translator_za.h.
    { return "Define Documentation"; }
trDefines()
QCString TranslatorAfrikaans::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 408 of file translator_za.h.
    { return "Definiesies"; }
trDefineValue()
QCString TranslatorAfrikaans::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1100 of file translator_za.h.
    {
      return "Waarde:";
    }
trDeprecated()
QCString TranslatorAfrikaans::trDeprecated () inline override virtual
Implements Translator.
Definition at line 789 of file translator_za.h.
    {
      return "Verouderd";
    }
trDeprecatedList()
QCString TranslatorAfrikaans::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1293 of file translator_za.h.
    {
      return "Verouderde Lys";
    }
trDetailedDescription()
QCString TranslatorAfrikaans::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 82 of file translator_za.h.
    { return "Detail Beskrywing"; }
trDetails()
QCString TranslatorAfrikaans::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 86 of file translator_za.h.
    { return "Besonderhede"; }
trDir()
QCString TranslatorAfrikaans::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1460 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "director", "ies", "y");
    }
References Translator::createNoun().
trDirDocumentation()
QCString TranslatorAfrikaans::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1442 of file translator_za.h.
    { return "Directory Documentasie"; }
trDirectories()
QCString TranslatorAfrikaans::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1448 of file translator_za.h.
    { return "Directories"; }
trDirIndex()
QCString TranslatorAfrikaans::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1436 of file translator_za.h.
    { return "Directory Hirargie"; }
trDirReference()
QCString TranslatorAfrikaans::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1454 of file translator_za.h.
    { QCString result=dirName; result+=" Directory Verwysing"; return result; }
trDocumentation()
QCString TranslatorAfrikaans::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 334 of file translator_za.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentasie"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorAfrikaans::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 420 of file translator_za.h.
    { return "Enumerations"; }
trEnumerationTypeDocumentation()
QCString TranslatorAfrikaans::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 456 of file translator_za.h.
    { return "Enumeration Type Dokumentasie"; }
trEnumerationValueDocumentation()
QCString TranslatorAfrikaans::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1492 of file translator_za.h.
    { return "Enumerator Dokumentasie"; }
trEnumerationValues()
QCString TranslatorAfrikaans::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 438 of file translator_za.h.
    { return "Enumeration waardes"; }
trEnumName()
QCString TranslatorAfrikaans::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 145 of file translator_za.h.
    { return "enum naam"; }
trEnumValue()
QCString TranslatorAfrikaans::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 149 of file translator_za.h.
    { return "enum waarde"; }
trEventDocumentation()
QCString TranslatorAfrikaans::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1310 of file translator_za.h.
    {
      return "Event Dokumentasie";
    }
trEvents()
QCString TranslatorAfrikaans::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1305 of file translator_za.h.
    {
      return "Events";
    }
trExamples()
QCString TranslatorAfrikaans::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 216 of file translator_za.h.
    { return "Voorbeelde"; }
trExamplesDescription()
QCString TranslatorAfrikaans::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 322 of file translator_za.h.
    { return "'n Lys van alle voorbeelde:"; }
trExceptions()
QCString TranslatorAfrikaans::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 528 of file translator_za.h.
    { return "Exceptions"; }
trFile()
QCString TranslatorAfrikaans::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1182 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "ler", "s");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorAfrikaans::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 398 of file translator_za.h.
    { return "Ler Dokumentasie"; }
trFileIndex()
QCString TranslatorAfrikaans::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 367 of file translator_za.h.
    { return "Ler Indeks"; }
trFileList()
QCString TranslatorAfrikaans::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 182 of file translator_za.h.
    { return "Ler Lys"; }
trFileListDescription()
QCString TranslatorAfrikaans::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 230 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle  ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="lers met kort beskrywings:";
      return result;
    }
trFileMembers()
QCString TranslatorAfrikaans::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 199 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals";
      }
      else
      {
        return "Ler Lede";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorAfrikaans::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 300 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funksies, veranderlikes, defines, enums, en typedefs";
      }
      else
      {
        result+="ler lede";
      }
      result+=" met skakels na ";
      if (extractAll)
        result+="die lers waaraan hulle behoort:";
      else
        result+="die dokumentasie:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorAfrikaans::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 595 of file translator_za.h.
    {
      QCString result=fileName;
      result+=" Ler Verwysing";
      return result;
    }
trFriends()
QCString TranslatorAfrikaans::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 555 of file translator_za.h.
    { return "Friends"; }
trFunctionDocumentation()
QCString TranslatorAfrikaans::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 462 of file translator_za.h.
    { return "Funksie Dokumentasie"; }
trFunctions()
QCString TranslatorAfrikaans::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 426 of file translator_za.h.
    { return "Funksies"; }
trGeneratedAt()
QCString TranslatorAfrikaans::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 489 of file translator_za.h.
    {
      QCString result="Gegenereer op "+date;
      if (!projName.isEmpty()) result+=" vir "+projName;
      result+=" deur";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorAfrikaans::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 137 of file translator_za.h.
    { QCString result="Automaties gegenereer deur Doxygen";
      if (!s.isEmpty()) result+=" vir "+s;
      result+=" van die bron kode af.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorAfrikaans::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 532 of file translator_za.h.
    { return "Gegenereer deur"; }
trGeneratedFromFiles()
QCString TranslatorAfrikaans::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 732 of file translator_za.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Die dokumentasie vir hierdie ";
      switch(compType)
      {
        case ClassDef::Class:      result+="klas"; break;
        case ClassDef::Struct:     result+="struct"; break;
        case ClassDef::Union:      result+="union"; break;
        case ClassDef::Interface:  result+="intervlak"; break;
        case ClassDef::Protocol:   result+="protokol"; break;
        case ClassDef::Category:   result+="kategorie"; break;
        case ClassDef::Exception:  result+="eksepsie"; break;
        default: break;
      }
      result+=" is gegenereer vanaf die volgende ler";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorAfrikaans::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1646 of file translator_za.h.
    {
      // single is true implies a single file
      QCString result="Die dokumentasie vir hierdie ";
      switch(compType)
      {
        case ClassDef::Class:      result+="module"; break;
        case ClassDef::Struct:     result+="tipe"; break;
        case ClassDef::Union:      result+="unie"; break;
        case ClassDef::Interface:  result+="Interflak"; break;
        case ClassDef::Protocol:   result+="protokcol"; break;
        case ClassDef::Category:   result+="kategorie"; break;
        case ClassDef::Exception:  result+="eksepsie"; break;
        default: break;
      }
      result+=" is gegenereer vanaf die volgende ler";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorAfrikaans::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1227 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "global", "s");
    }
References Translator::createNoun().
trGotoDocumentation()
QCString TranslatorAfrikaans::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 819 of file translator_za.h.
    {
      return "Skakel na die dokumentasie van hierdie ler.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorAfrikaans::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 852 of file translator_za.h.
    {
      return "Skakel na die grafiese klasse hierargie";
    }
trGotoSourceCode()
QCString TranslatorAfrikaans::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 814 of file translator_za.h.
    {
      return "Skakel na die bron kode van hierdie ler.";
    }
trGotoTextualHierarchy()
QCString TranslatorAfrikaans::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 856 of file translator_za.h.
    {
      return "Skakel na die teks klasse hierargie";
    }
trGraphicalHierarchy()
QCString TranslatorAfrikaans::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 848 of file translator_za.h.
    {
      return "Grafiese Klasse Hierargie";
    }
trGroup()
QCString TranslatorAfrikaans::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1200 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "groep", "e");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorAfrikaans::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 346 of file translator_za.h.
    { return "Hierargiese Indeks"; }
trImplementedFromList()
QCString TranslatorAfrikaans::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1261 of file translator_za.h.
    {
      return "Implimenteer "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorAfrikaans::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1269 of file translator_za.h.
    {
      return "Geimplimenteer in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorAfrikaans::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 948 of file translator_za.h.
    {
      return "Hierdie diagram verduidelik watter lers direk of"
             "indirek hierdie ler insluit:";
    }
trInclDepGraph()
QCString TranslatorAfrikaans::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 804 of file translator_za.h.
    {
      return "Insluitings afhanklikheid diagram vir "+fName+":";
    }
trIncludingInheritedMembers()
QCString TranslatorAfrikaans::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 131 of file translator_za.h.
    { return ", insluitend alle afgeleide lede."; }
trInheritedByList()
QCString TranslatorAfrikaans::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 666 of file translator_za.h.
    {
      return "Afgelei van"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList()
QCString TranslatorAfrikaans::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 658 of file translator_za.h.
    {
      return "Afgelei van"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorAfrikaans::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 839 of file translator_za.h.
    {
      return "Oorspronklike waarde:";
    }
trInvariant()
QCString TranslatorAfrikaans::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 834 of file translator_za.h.
    {
      return "Invariant";
    }
trISOLang()
QCString TranslatorAfrikaans::trISOLang () inline override virtual
Implements Translator.
Definition at line 62 of file translator_za.h.
    {
      return "af";
    }
trLegend()
QCString TranslatorAfrikaans::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1033 of file translator_za.h.
    {
      return "beskrywing";
    }
trLegendDocs()
QCString TranslatorAfrikaans::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 970 of file translator_za.h.
    {
      return
        "Hierdie bladsy beskryf die diagram konvensies wat gebruik word "
        "deur doxygen.<p>\n"
        "in hierdie voorbeeld:\n"
        "\\code\n"
        "/*! Onsigbare klas weens afkorting */\n"
        "class Invisible { };\n\n"
        "/*! Afgekorte klas, afgeleide verwantskap word versteek */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Ongedokumenteerde Klas, geen doxygen kommentaar nie */\n"
        "class Undocumented{ };\n\n"
        "/*! 'n Klas wat afgelei is met 'n publieke verwantskap */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! 'n template klas */\n"
        "template<class T> class Templ { };\n\n"
        "/*! 'n Klas wat afgelei is met 'n beskermde verwantskap */\n"
        "class ProtectedBase { };\n\n"
        "/*! 'n Klas wat afgelei is met 'n private verwantskap */\n"
        "class PrivateBase { };\n\n"
        "/*! 'n Klas wat gebrui word deur die Afgeleide klas */\n"
        "class GebruikMy { };\n\n"
        "/*! 'n Super klas wat afgelei word van 'n aantal basis klasse */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Ongedokumenteer,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "As die \\c MAX_DOT_GRAPH_HEIGHT merker in die konfigurasie ler "
        "aan 240 gelyk gestel is, word die volgende diagram geproduseer:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Die reghoeke in die diagram het die volgende betekenis:\n"
        "<ul>\n"
        "<li>%'n Soliede swart reghoek verteenwoordig die klas waarvoor "
        "die diagram gegenereer is.\n"
        "<li>%'n Reghoek met 'n swart omlyning verteenwoordig 'n gedokumenteerde klas.\n"
        "<li>%'n Reghoek met 'n grys omlyning verteenwoordig 'n ongedokumenteerde klas.\n"
        "<li>%'n Reghoek met 'n rooi omlyning verteenwoordig 'n gedokumenteerde klas waarvoor"
        "alle verwante klasse (afgeleide of gebruik) nie getoon word nie. %'n Diagram word "
        "op hierie manier afgekort as dit nie in die gespesifiseerde raam pas nie.\n"
        "</ul>\n"
        "Die pyltjies het die volgende betekenis:\n"
        "<ul>\n"
        "<li>%'n Donker blou pyltjie verteenwoordig 'n publieke afgeleide "
        "verwantskap tussen twee klasse.\n"
        "<li>%'n Donker groen pyltjie word gebruik vir 'n beskermde verwantskap.\n"
        "<li>%'n Donker rooi pyltjie verteenwoordig private verwantskappe.\n"
        "<li>%'n Pers pyltjie word gebruik as 'n klas gebruik of bevat word "
        "deur 'n ander klas. Die pyltjie word gemerk met die veranderlike(s) waar deur "
        "die verwysde klass verkrygbaar is.\n"
        "<li>%'n Geel stippel pyl verteenwoordig die verwantslap tussen 'n template instansie en "
        "die template waarvan die klas vervaardig is. Die pyltjie word gemerk met die "
        "template parameters van die instansie.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorAfrikaans::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 963 of file translator_za.h.
    {
      return "Diagram beskrywing";
    }
trListOfAllMembers()
QCString TranslatorAfrikaans::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 119 of file translator_za.h.
    { return "Lys van alle lede"; }
trMainPage()
QCString TranslatorAfrikaans::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 763 of file translator_za.h.
    { return "Hoof Bladsy"; }
trMember()
QCString TranslatorAfrikaans::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1218 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "l", "ede", "id");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorAfrikaans::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 102 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veld Dokumentasie";
      }
      else
      {
        return "Lede Data Dokumentasie";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorAfrikaans::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 94 of file translator_za.h.
    { return "Lede Enumerasie Dokumentasie"; }
trMemberFunctionDocumentation()
QCString TranslatorAfrikaans::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 98 of file translator_za.h.
    { return "Lede Funksie Dokumentasie"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorAfrikaans::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1500 of file translator_za.h.
    { return "Lede Funksie/Subroetine Dokumentasie"; }
trMemberList()
QCString TranslatorAfrikaans::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 123 of file translator_za.h.
    { return "Lede Lys"; }
trMemberTypedefDocumentation()
QCString TranslatorAfrikaans::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 90 of file translator_za.h.
    { return "Lede Typedef Dokumentasie"; }
trModule()
QCString TranslatorAfrikaans::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1639 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "module", "s");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorAfrikaans::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 373 of file translator_za.h.
    { return "Module Dokumentasie"; }
trModuleIndex()
QCString TranslatorAfrikaans::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 340 of file translator_za.h.
    { return "Module Indeks"; }
trModuleReference()
QCString TranslatorAfrikaans::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1601 of file translator_za.h.
    {
      QCString result=namespaceName;
      result+=" Module Bron";
      return result;
    }
trModules()
QCString TranslatorAfrikaans::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 161 of file translator_za.h.
    { return "Modules"; }
trModulesDescription()
QCString TranslatorAfrikaans::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 330 of file translator_za.h.
    { return "'n Lys van alle modules:"; }
trModulesIndex()
QCString TranslatorAfrikaans::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1632 of file translator_za.h.
    { return "Modules Indeks"; }
trModulesList()
QCString TranslatorAfrikaans::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1567 of file translator_za.h.
    { return "Modules Lys"; }
trModulesListDescription()
QCString TranslatorAfrikaans::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1571 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="modules met kort beskrywings:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorAfrikaans::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1613 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="module lede met skakels na ";
      if (extractAll)
      {
        result+="die module dokumentasie vir elke lid:";
      }
      else
      {
        result+="die modules waaraan hulle behoort:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorAfrikaans::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1609 of file translator_za.h.
    { return "Module Lede"; }
trMonth()
QCString TranslatorAfrikaans::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1697 of file translator_za.h.
    {
      static const char *months_short[] = { "Jan.", "Feb.", "Mrt.", "Apr.", "Mei", "Jun.", "Jul.", "Aug.", "Sep.", "Okt.", "Nov.", "Des." };
      static const char *months_full[]  = { "Januarie", "Februarie", "Maart", "April", "Mei", "Junie", "Julie", "Augustus", "September", "Oktober", "November", "Desember" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorAfrikaans::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 115 of file translator_za.h.
    { return "Meer detail..."; }
trNamespace()
QCString TranslatorAfrikaans::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1191 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "namespace", "s");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorAfrikaans::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 712 of file translator_za.h.
    { return "Namespace Dokumentasie"; }
trNamespaceIndex()
QCString TranslatorAfrikaans::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 706 of file translator_za.h.
    { return "Namespace Indeks"; }
trNamespaceList()
QCString TranslatorAfrikaans::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 540 of file translator_za.h.
    { return "Namespace Lys"; }
trNamespaceListDescription()
QCString TranslatorAfrikaans::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 544 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="namespaces met kort beskrywings:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorAfrikaans::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 692 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="namespace lede met skakels na ";
      if (extractAll)
        result+="die namespace dokumentasie vir elke lid:";
      else
        result+="die namespaces waaraan hulle behoort:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorAfrikaans::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 688 of file translator_za.h.
    { return "Namespace Lede"; }
trNamespaceReference()
QCString TranslatorAfrikaans::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 603 of file translator_za.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Verwysing";
      return result;
    }
trNamespaces()
QCString TranslatorAfrikaans::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 722 of file translator_za.h.
    { return "Namespaces"; }
trNote()
QCString TranslatorAfrikaans::trNote () inline override virtual
Implements Translator.
Definition at line 869 of file translator_za.h.
    {
      return "Nota";
    }
trOverloadText()
QCString TranslatorAfrikaans::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1472 of file translator_za.h.
    {
       return "Hierdie is 'n oorlaaide lede funksie, "
              "vertoon vir volledigheid. Dit verskil slegs van die bogegewe "
              "funksie in die argument(e) wat dit aanvaar.";
    }
trPackage()
QCString TranslatorAfrikaans::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1085 of file translator_za.h.
    {
      return "Pakket "+name;
    }
trPackageAttribs()
QCString TranslatorAfrikaans::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1346 of file translator_za.h.
    {
      return "Pakket Eienskappe";
    }
trPackageFunctions()
QCString TranslatorAfrikaans::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1328 of file translator_za.h.
    {
      return "Pakket Funksies";
    }
trPackageListDescription()
QCString TranslatorAfrikaans::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1090 of file translator_za.h.
    {
      return "Die pakkette met kort beskrywings (indien beskikbaar):";
    }
trPackageMembers()
QCString TranslatorAfrikaans::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1332 of file translator_za.h.
    {
      return "Pakket Lede";
    }
trPackages()
QCString TranslatorAfrikaans::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1095 of file translator_za.h.
    {
      return "Pakkette";
    }
trPackageTypes()
QCString TranslatorAfrikaans::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1321 of file translator_za.h.
    {
      return "Pakket Tipes";
    }
trPage()
QCString TranslatorAfrikaans::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1209 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "bladsy", "e");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorAfrikaans::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 769 of file translator_za.h.
    { return "p."; }
trPageIndex()
QCString TranslatorAfrikaans::trPageIndex () inline override virtual
Implements Translator.
Definition at line 860 of file translator_za.h.
    {
      return "Bladsy Indeks";
    }
trParameters()
QCString TranslatorAfrikaans::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 524 of file translator_za.h.
    { return "Parameters"; }
trPostcondition()
QCString TranslatorAfrikaans::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 829 of file translator_za.h.
    {
      return "Postkondisie";
    }
trPrecondition()
QCString TranslatorAfrikaans::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 824 of file translator_za.h.
    {
      return "Prekondisie";
    }
trPrivateAttribs()
QCString TranslatorAfrikaans::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 908 of file translator_za.h.
    {
      return "Private Attribute";
    }
trPrivateMembers()
QCString TranslatorAfrikaans::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 624 of file translator_za.h.
    { return "Private Lede Funksies"; }
trPrivateSlots()
QCString TranslatorAfrikaans::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 626 of file translator_za.h.
    { return "Private Slots"; }
trPrivateTypes()
QCString TranslatorAfrikaans::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 904 of file translator_za.h.
    {
      return "Private Tipes";
    }
trProperties()
QCString TranslatorAfrikaans::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1058 of file translator_za.h.
    {
      return "Eienskappe";
    }
trPropertyDocumentation()
QCString TranslatorAfrikaans::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1063 of file translator_za.h.
    {
      return "Eienskap Dokumentasie";
    }
trProtectedAttribs()
QCString TranslatorAfrikaans::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 896 of file translator_za.h.
    {
      return "Beskermde Attribute";
    }
trProtectedMembers()
QCString TranslatorAfrikaans::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 618 of file translator_za.h.
    { return "Beskermde Lede Funksies"; }
trProtectedSlots()
QCString TranslatorAfrikaans::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 620 of file translator_za.h.
    { return "Beskermde Slots"; }
trProtectedTypes()
QCString TranslatorAfrikaans::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 892 of file translator_za.h.
    {
      return "Beskermde Tipes";
    }
trPublicAttribs()
QCString TranslatorAfrikaans::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 877 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Velde";
      }
      else
      {
        return "Publieke Public Attributes";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorAfrikaans::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 610 of file translator_za.h.
    { return "Publieke Lede Funksies"; }
trPublicSlots()
QCString TranslatorAfrikaans::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 612 of file translator_za.h.
    { return "Publieke Slots"; }
trPublicTypes()
QCString TranslatorAfrikaans::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 873 of file translator_za.h.
    {
      return "Publieke Tipes";
    }
trReferencedBy()
QCString TranslatorAfrikaans::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 936 of file translator_za.h.
    {
      return "Verwysing van";
    }
trReferenceManual()
QCString TranslatorAfrikaans::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 402 of file translator_za.h.
    { return "Verwysings Handleiding"; }
trReferences()
QCString TranslatorAfrikaans::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1249 of file translator_za.h.
    {
      return "Verwysings";
    }
trReimplementedFromList()
QCString TranslatorAfrikaans::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 674 of file translator_za.h.
    {
      return "Hergeimplimenteer van "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorAfrikaans::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 682 of file translator_za.h.
    {
      return "Hergeimplimenter in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorAfrikaans::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 565 of file translator_za.h.
    { return "Friends En Verwante Funksie Dokumentasie"; }
trRelatedFunctions()
QCString TranslatorAfrikaans::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 74 of file translator_za.h.
    { return "Verwante Funksies"; }
trRelatedPages()
QCString TranslatorAfrikaans::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 212 of file translator_za.h.
    { return "Verwante Bladsye"; }
trRelatedPagesDescription()
QCString TranslatorAfrikaans::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 326 of file translator_za.h.
    { return "'n Lys van alle verwante dokumentasie:"; }
trRelatedSubscript()
QCString TranslatorAfrikaans::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 78 of file translator_za.h.
    { return "(Let daarop dat hierdie nie lede funksies is nie.)"; }
trRemarks()
QCString TranslatorAfrikaans::trRemarks () inline override virtual
Implements Translator.
Definition at line 940 of file translator_za.h.
    {
      return "Opmerkings";
    }
trReturns()
QCString TranslatorAfrikaans::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 516 of file translator_za.h.
    { return "Returns"; }
trReturnValues()
QCString TranslatorAfrikaans::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 758 of file translator_za.h.
    { return "Return waardes"; }
trRTFansicp()
QCString TranslatorAfrikaans::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1149 of file translator_za.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorAfrikaans::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1158 of file translator_za.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorAfrikaans::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1164 of file translator_za.h.
    {
      return "Indeks";
    }
trRTFTableOfContents()
QCString TranslatorAfrikaans::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1281 of file translator_za.h.
    {
      return "Inhoudsopgawe";
    }
trSearch()
QCString TranslatorAfrikaans::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 220 of file translator_za.h.
    { return "Soek"; }
trSearchMatches()
QCString TranslatorAfrikaans::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1413 of file translator_za.h.
    {
      return "Teikens:";
    }
trSearchResults()
QCString TranslatorAfrikaans::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1394 of file translator_za.h.
    {
      if (numDocuments==0)
      {
        return "Geen dokumente na gelang van jou navraag nie.";
      }
      else if (numDocuments==1)
      {
        return "Die soektog het <b>1</b> dokument gevind na gelang van jou navraag.";
      }
      else
      {
        return "Die soektog het <b>$num</b> dokumente gevind na gelang van jou navraag. "
               "Beste resultate eerste.";
      }
    }
trSearchResultsTitle()
QCString TranslatorAfrikaans::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1382 of file translator_za.h.
    {
      return "Soektog Resultate";
    }
trSeeAlso()
QCString TranslatorAfrikaans::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 520 of file translator_za.h.
    { return "Sien ook"; }
trSignals()
QCString TranslatorAfrikaans::trSignals () inline override virtual
Implements Translator.
Definition at line 614 of file translator_za.h.
    { return "Signals"; }
trSince()
QCString TranslatorAfrikaans::trSince () inline override virtual
Implements Translator.
Definition at line 953 of file translator_za.h.
    {
      return "Sederd";
    }
trSourceFile()
QCString TranslatorAfrikaans::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1424 of file translator_za.h.
    {
      return filename + " Bron kode Ler";
    }
trStaticPackageAttribs()
QCString TranslatorAfrikaans::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1353 of file translator_za.h.
    {
      return "Statiese Pakket Eienskappe";
    }
trStaticPackageFunctions()
QCString TranslatorAfrikaans::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1339 of file translator_za.h.
    {
      return "Statiese Pakket Funksies";
    }
trStaticPrivateAttribs()
QCString TranslatorAfrikaans::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 912 of file translator_za.h.
    {
      return "Statiese Private Attribute";
    }
trStaticPrivateMembers()
QCString TranslatorAfrikaans::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 628 of file translator_za.h.
    { return "Statiese Private Lede Funksies"; }
trStaticProtectedAttribs()
QCString TranslatorAfrikaans::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 900 of file translator_za.h.
    {
      return "Statiese Beskermde Attribute";
    }
trStaticProtectedMembers()
QCString TranslatorAfrikaans::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 622 of file translator_za.h.
    { return "Statiese Beskermde Lede Funksies"; }
trStaticPublicAttribs()
QCString TranslatorAfrikaans::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 888 of file translator_za.h.
    {
      return "Statiese Publieke Attribute";
    }
trStaticPublicMembers()
QCString TranslatorAfrikaans::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 616 of file translator_za.h.
    { return "Statiese Publieke Lede Funksies"; }
trSubprogram()
QCString TranslatorAfrikaans::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1678 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "subprogram", "me");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorAfrikaans::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1557 of file translator_za.h.
    { return "Funksies/Subroetine Dokumentasie"; }
trSubprograms()
QCString TranslatorAfrikaans::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1551 of file translator_za.h.
    { return "Funksies/Subroetines"; }
trTest()
QCString TranslatorAfrikaans::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1043 of file translator_za.h.
    {
      return "Toets";
    }
trTestList()
QCString TranslatorAfrikaans::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1048 of file translator_za.h.
    {
      return "Toets Lys";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorAfrikaans::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 127 of file translator_za.h.
    { return "Hierdie is 'n volledige lys van lede vir"; }
trTodo()
QCString TranslatorAfrikaans::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 922 of file translator_za.h.
    {
      return "Aksies";
    }
trTodoList()
QCString TranslatorAfrikaans::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 927 of file translator_za.h.
    {
      return "Aksie Lys";
    }
trType()
QCString TranslatorAfrikaans::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1670 of file translator_za.h.
    {
      return createNoun(first_capital, singular, "tipe", "s");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorAfrikaans::trTypeConstraints () inline override virtual
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1684 of file translator_za.h.
    {
      return "Tipe Limiete";
    }
trTypedefDocumentation()
QCString TranslatorAfrikaans::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 450 of file translator_za.h.
    { return "Typedef Dokumentasie"; }
trTypedefs()
QCString TranslatorAfrikaans::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 414 of file translator_za.h.
    { return "Typedefs"; }
trTypeDocumentation()
QCString TranslatorAfrikaans::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1545 of file translator_za.h.
    { return "Data Tipe Dokumentasie"; }
trVariableDocumentation()
QCString TranslatorAfrikaans::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 468 of file translator_za.h.
    { return "Veranderlike Dokumentasie"; }
trVariables()
QCString TranslatorAfrikaans::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 432 of file translator_za.h.
    { return "Veranderlikes"; }
trVersion()
QCString TranslatorAfrikaans::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 508 of file translator_za.h.
    { return "Weergawe"; }
trWarning()
QCString TranslatorAfrikaans::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 504 of file translator_za.h.
    { return "Waarskuwing"; }
trWriteList()
QCString TranslatorAfrikaans::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 634 of file translator_za.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=", en ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_za.h