Doxygen: src/classdef.cpp File Reference
classdef.cpp File Reference
#include <cstdio>
#include <algorithm>
#include "types.h"
#include "classdef.h"
#include "classlist.h"
#include "entry.h"
#include "doxygen.h"
#include "membername.h"
#include "message.h"
#include "config.h"
#include "util.h"
#include "diagram.h"
#include "language.h"
#include "htmlhelp.h"
#include "example.h"
#include "outputlist.h"
#include "dot.h"
#include "dotclassgraph.h"
#include "dotrunner.h"
#include "defargs.h"
#include "debug.h"
#include "docparser.h"
#include "searchindex.h"
#include "vhdldocgen.h"
#include "layout.h"
#include "arguments.h"
#include "memberlist.h"
#include "groupdef.h"
#include "filedef.h"
#include "namespacedef.h"
#include "membergroup.h"
#include "definitionimpl.h"
#include "symbolresolver.h"
#include "fileinfo.h"
#include "trace.h"
#include "moduledef.h"
Classes
class ClassDefImpl
Implementation of the ClassDef interface.
class ClassDefAliasImpl
class ClassDefImpl::IMPL
Private data associated with a ClassDef object.
Functions
static QCString makeQualifiedNameWithTemplateParameters (const ClassDef *cd, const ArgumentLists *actualParams, uint32_t *actualParamIndex)
static QCString makeDisplayName (const ClassDef *cd, bool includeScope)
static QCString getCompoundTypeString (SrcLangExt lang, ClassDef::CompoundType compType, bool isJavaEnum)
std::unique_ptr< ClassDef > createClassDef (const QCString &fileName, int startLine, int startColumn, const QCString &name, ClassDef::CompoundType ct, const QCString &ref, const QCString &fName, bool isSymbol, bool isJavaEnum)
Factory method to create a new ClassDef object.
std::unique_ptr< ClassDef > createClassDefAlias (const Definition *newScope, const ClassDef *cd)
static void writeInheritanceSpecifier (OutputList &ol, const BaseClassDef &bcd)
static void searchTemplateSpecs (const Definition *d, ArgumentLists &result, QCString &name, SrcLangExt lang)
static bool hasNonReferenceSuperClassRec (const ClassDef *cd, int level)
static bool isStandardFunc (const MemberDef *md)
ClassDef * toClassDef (Definition *d)
ClassDef * toClassDef (DefinitionMutable *md)
const ClassDef * toClassDef (const Definition *d)
ClassDefMutable * toClassDefMutable (Definition *d)
ClassDef * getClass (const QCString &n)
bool classHasVisibleRoot (const BaseClassList &bcl)
bool classHasVisibleChildren (const ClassDef *cd)
bool classVisibleInIndex (const ClassDef *cd)
int minClassDistance (const ClassDef *cd, const ClassDef *bcd, int level)
Protection classInheritedProtectionLevel (const ClassDef *cd, const ClassDef *bcd, Protection prot, int level)
Function Documentation
classHasVisibleChildren()
bool classHasVisibleChildren (const ClassDef * cd)
Definition at line 5383 of file classdef.cpp.
{
  BaseClassList bcl;
  if (cd->getLanguage()==SrcLangExt::VHDL) // reverse baseClass/subClass relation
  {
    if (cd->baseClasses().empty()) return FALSE;
    bcl=cd->baseClasses();
  }
  else
  {
    if (cd->subClasses().empty()) return FALSE;
    bcl=cd->subClasses();
  }
  for (const auto &bcd : bcl)
  {
    if (bcd.classDef->isVisibleInHierarchy())
    {
      return TRUE;
    }
  }
  return FALSE;
}
References ClassDef::baseClasses(), FALSE, Definition::getLanguage(), ClassDef::subClasses(), TRUE, and VHDL.
Referenced by writeClassTreeForList(), and writeClassTreeToOutput().
classHasVisibleRoot()
bool classHasVisibleRoot (const BaseClassList & bcl)
Definition at line 5372 of file classdef.cpp.
{
  for (const auto &bcd : bcl)
  {
    const ClassDef *cd=bcd.classDef;
    if (cd->isVisibleInHierarchy()) return true;
    if (classHasVisibleRoot(cd->baseClasses())) return true;
  }
  return false;
}
References ClassDef::baseClasses(), classHasVisibleRoot(), and ClassDef::isVisibleInHierarchy().
Referenced by DotGfxHierarchyTable::addClassList(), DotGfxHierarchyTable::addHierarchy(), classHasVisibleRoot(), countClassesInTreeList(), writeClassTreeForList(), and writeClassTreeToOutput().
classInheritedProtectionLevel()
Protection classInheritedProtectionLevel (const ClassDef * cd, const ClassDef * bcd, Protection prot, int level)
Definition at line 5443 of file classdef.cpp.
{
  if (bcd->categoryOf()) // use class that is being extended in case of
    // an Objective-C category
  {
    bcd=bcd->categoryOf();
  }
  if (cd==bcd)
  {
    goto exit;
  }
  if (level==256)
  {
    err("Internal inconsistency: found class %s seem to have a recursive "
        "inheritance relation! Please send a bug report to doxygen@gmail.com\n",qPrint(cd->name()));
  }
  else if (prot!=Protection::Private)
  {
    for (const auto &bcdi : cd->baseClasses())
    {
      Protection baseProt = classInheritedProtectionLevel(bcdi.classDef,bcd,bcdi.prot,level+1);
      if (baseProt==Protection::Private)        prot=Protection::Private;
      else if (baseProt==Protection::Protected) prot=Protection::Protected;
    }
  }
exit:
  //printf("classInheritedProtectionLevel(%s,%s)=%d\n",qPrint(cd->name()),qPrint(bcd->name()),prot);
  return prot;
}
References ClassDef::baseClasses(), ClassDef::categoryOf(), classInheritedProtectionLevel(), err, Definition::name(), Private, Protected, and qPrint().
Referenced by classInheritedProtectionLevel().
classVisibleInIndex()
bool classVisibleInIndex (const ClassDef * cd)
Definition at line 5408 of file classdef.cpp.
{
  bool allExternals = Config_getBool(ALLEXTERNALS);
  return (allExternals && cd->isLinkable()) || cd->isLinkableInProject();
}
References Config_getBool, Definition::isLinkable(), and Definition::isLinkableInProject().
Referenced by writeClassTree().
createClassDef()
std::unique_ptr< ClassDef > createClassDef (const QCString & fileName, int startLine, int startColumn, const QCString & name, ClassDef::CompoundType ct, const QCString & ref, const QCString & fName, bool isSymbol, bool isJavaEnum)
Factory method to create a new ClassDef object.
Definition at line 412 of file classdef.cpp.
{
  return std::make_unique<ClassDefImpl>(fileName,startLine,startColumn,name,ct,ref,fName,isSymbol,isJavaEnum);
}
Referenced by addClassToContext(), createTagLessInstance(), findClassRelation(), findUsedClassesForClass(), and findUsingDeclarations().
createClassDefAlias()
std::unique_ptr< ClassDef > createClassDefAlias (const Definition * newScope, const ClassDef * cd)
Definition at line 642 of file classdef.cpp.
{
  auto acd = std::make_unique<ClassDefAliasImpl>(newScope,cd);
  //printf("cd name=%s localName=%s qualifiedName=%s qualifiedNameWith=%s displayName()=%s\n",
  //    qPrint(acd->name()),qPrint(acd->localName()),qPrint(acd->qualifiedName()),
  //    qPrint(acd->qualifiedNameWithTemplateParameters()),qPrint(acd->displayName()));
  return acd;
}
Referenced by ClassDefAliasImpl::deepCopy(), findUsingDeclImports(), and resolveClassNestingRelations().
getClass()
ClassDef * getClass (const QCString & n)
Get a class definition given its name. Returns nullptr if the class is not found.
Definition at line 5366 of file classdef.cpp.
{
  if (n.isEmpty()) return nullptr;
  return Doxygen::classLinkedMap->find(n);
}
References Doxygen::classLinkedMap, LinkedMap< T, Hash, KeyEqual, Map >::find(), and QCString::isEmpty().
Referenced by buildScopeFromQualifiedName(), extractNamespaceName(), findClassWithinClassContext(), findEnumDocumentation(), findEnums(), findMember(), findUsingDeclarations(), generateClassOrGlobalLink(), generateClassOrGlobalLink(), generateMemberLink(), MemberDefImpl::getClassDefOfAnonymousType(), getClassMutable(), getScopeDefs(), getTemplateArgumentsFromName(), DocParser::handleLinkedWord(), if(), insertTemplateSpecifierInScope(), MemberDefImpl::isDocumentedFriendClass(), SymbolResolver::resolveClass(), resolveLink(), resolveRef(), setCallContextForVar(), stripTemplateSpecifiersFromScope(), and MemberDefImpl::writeDeclaration().
getCompoundTypeString()
static QCString getCompoundTypeString (SrcLangExt lang, ClassDef::CompoundType compType, bool isJavaEnum) static
Definition at line 147 of file classdef.cpp.
{
  if (lang==SrcLangExt::Fortran)
  {
    switch (compType)
    {
      case ClassDef::Class:     return "module";
      case ClassDef::Struct:    return "type";
      case ClassDef::Union:     return "union";
      case ClassDef::Interface: return "interface";
      case ClassDef::Protocol:  return "protocol";
      case ClassDef::Category:  return "category";
      case ClassDef::Exception: return "exception";
      default:                  return "unknown";
    }
  }
  else
  {
    switch (compType)
    {
      case ClassDef::Class:     return isJavaEnum ? "enum" : "class";
      case ClassDef::Struct:    return "struct";
      case ClassDef::Union:     return "union";
      case ClassDef::Interface: return lang==SrcLangExt::ObjC ? "class" : "interface";
      case ClassDef::Protocol:  return "protocol";
      case ClassDef::Category:  return "category";
      case ClassDef::Exception: return "exception";
      case ClassDef::Service:   return "service";
      case ClassDef::Singleton: return "singleton";
      default:                  return "unknown";
    }
  }
}
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, Fortran, ClassDef::Interface, ObjC, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, ClassDef::Struct, and ClassDef::Union.
Referenced by ClassDefImpl::ClassDefImpl(), ClassDefImpl::compoundTypeString(), and ClassDefImpl::deepCopy().
hasNonReferenceSuperClassRec()
static bool hasNonReferenceSuperClassRec (const ClassDef * cd, int level) static
Definition at line 3449 of file classdef.cpp.
{
  bool found=!cd->isReference() && cd->isLinkableInProject() && !cd->isHidden();
  if (found)
  {
    return TRUE; // we're done if this class is not a reference
  }
  for (const auto &ibcd : cd->subClasses())
  {
    const ClassDef *bcd=ibcd.classDef;
    if (level>256)
    {
      err("Possible recursive class relation while inside %s and looking for base class %s\n",qPrint(cd->name()),qPrint(bcd->name()));
      return FALSE;
    }
    // recurse into the super class branch
    found = found || hasNonReferenceSuperClassRec(bcd,level+1);
    if (!found)
    {
      // look for template instances that might have non-reference super classes
      for (const auto &cil : bcd->getTemplateInstances())
      {
        // recurse into the template instance branch
        found = hasNonReferenceSuperClassRec(cil.classDef,level+1);
        if (found) break;
      }
    }
    else
    {
      break;
    }
  }
  return found;
}
References err, FALSE, found, ClassDef::getTemplateInstances(), hasNonReferenceSuperClassRec(), Definition::isHidden(), Definition::isLinkableInProject(), Definition::isReference(), Definition::name(), qPrint(), ClassDef::subClasses(), and TRUE.
Referenced by ClassDefImpl::hasNonReferenceSuperClass(), and hasNonReferenceSuperClassRec().
isStandardFunc()
static bool isStandardFunc (const MemberDef * md) static
Definition at line 3685 of file classdef.cpp.
{
  return md->name()=="operator=" || // assignment operator
         md->isConstructor() ||     // constructor
         md->isDestructor();        // destructor
}
References MemberDef::isConstructor(), MemberDef::isDestructor(), and Definition::name().
Referenced by ClassDefImpl::mergeMembersFromBaseClasses().
makeDisplayName()
static QCString makeDisplayName (const ClassDef * cd, bool includeScope) static
Definition at line 108 of file classdef.cpp.
{
  //bool optimizeOutputForJava = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
  SrcLangExt lang = cd->getLanguage();
  //bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  QCString n;
  if (lang==SrcLangExt::VHDL)
  {
    n = VhdlDocGen::getClassName(cd);
  }
  else
  {
    if (includeScope)
    {
      n=cd->qualifiedNameWithTemplateParameters();
    }
    else
    {
      n=cd->className();
    }
  }
  if (cd->isAnonymous())
  {
    n = removeAnonymousScopes(n);
  }
  QCString sep=getLanguageSpecificSeparator(lang);
  if (sep!="::")
  {
    n=substitute(n,"::",sep);
  }
  if (cd->compoundType()==ClassDef::Protocol && n.endsWith("-p"))
  {
    n="<"+n.left(n.length()-2)+">";
  }
  return n;
}
References ClassDef::className(), ClassDef::compoundType(), QCString::endsWith(), VhdlDocGen::getClassName(), Definition::getLanguage(), getLanguageSpecificSeparator(), Definition::isAnonymous(), QCString::left(), QCString::length(), ClassDef::Protocol, ClassDef::qualifiedNameWithTemplateParameters(), removeAnonymousScopes(), substitute(), and VHDL.
Referenced by ClassDefAliasImpl::displayName(), and ClassDefImpl::displayName().
makeQualifiedNameWithTemplateParameters()
static QCString makeQualifiedNameWithTemplateParameters (const ClassDef * cd, const ArgumentLists * actualParams, uint32_t * actualParamIndex) static
Definition at line 56 of file classdef.cpp.
{
  //bool optimizeOutputJava = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
  bool hideScopeNames = Config_getBool(HIDE_SCOPE_NAMES);
  //printf("qualifiedNameWithTemplateParameters() localName=%s\n",qPrint(cd->localName()));
  QCString scName;
  const Definition *d=cd->getOuterScope();
  if (d)
  {
    if (d->definitionType()==Definition::TypeClass)
    {
      const ClassDef *ocd=toClassDef(d);
      scName = ocd->qualifiedNameWithTemplateParameters(actualParams,actualParamIndex);
    }
    else if (!hideScopeNames)
    {
      scName = d->qualifiedName();
    }
  }
  SrcLangExt lang = cd->getLanguage();
  QCString scopeSeparator = getLanguageSpecificSeparator(lang);
  if (!scName.isEmpty()) scName+=scopeSeparator;
  bool isSpecialization = cd->localName().find('<')!=-1;
  QCString clName = cd->className();
  scName+=clName;
  if (!cd->templateArguments().empty())
  {
    if (actualParams && *actualParamIndex<actualParams->size())
    {
      const ArgumentList &al = actualParams->at(*actualParamIndex);
      if (!isSpecialization)
      {
        scName+=tempArgListToString(al,lang);
      }
      (*actualParamIndex)++;
    }
    else
    {
      if (!isSpecialization)
      {
        scName+=tempArgListToString(cd->templateArguments(),lang);
      }
    }
  }
  //printf("qualifiedNameWithTemplateParameters: scope=%s qualifiedName=%s\n",qPrint(name()),qPrint(scName));
  return scName;
}
References ArgumentList::at(), ClassDef::className(), Config_getBool, Definition::definitionType(), ArgumentList::empty(), QCString::find(), Definition::getLanguage(), getLanguageSpecificSeparator(), Definition::getOuterScope(), QCString::isEmpty(), isSpecialization(), Definition::localName(), Definition::qualifiedName(), ClassDef::qualifiedNameWithTemplateParameters(), tempArgListToString(), ClassDef::templateArguments(), toClassDef(), and Definition::TypeClass.
Referenced by ClassDefAliasImpl::qualifiedNameWithTemplateParameters(), and ClassDefImpl::qualifiedNameWithTemplateParameters().
minClassDistance()
int minClassDistance (const ClassDef * cd, const ClassDef * bcd, int level)
Definition at line 5418 of file classdef.cpp.
{
  const int maxInheritanceDepth = 100000;
  if (bcd->categoryOf()) // use class that is being extended in case of
    // an Objective-C category
  {
    bcd=bcd->categoryOf();
  }
  if (cd==bcd) return level;
  if (level==256)
  {
    warn_uncond("class %s seem to have a recursive "
        "inheritance relation!\n",qPrint(cd->name()));
    return -1;
  }
  int m=maxInheritanceDepth;
  for (const auto &bcdi : cd->baseClasses())
  {
    int mc=minClassDistance(bcdi.classDef,bcd,level+1);
    if (mc<m) m=mc;
    if (m<0) break;
  }
  return m;
}
References ClassDef::baseClasses(), ClassDef::categoryOf(), maxInheritanceDepth, minClassDistance(), Definition::name(), qPrint(), and warn_uncond.
Referenced by getDefsOld(), ClassDefImpl::getMemberByName(), and minClassDistance().
searchTemplateSpecs()
static void searchTemplateSpecs (const Definition * d, ArgumentLists & result, QCString & name, SrcLangExt lang) static
Definition at line 1475 of file classdef.cpp.
{
  if (d->definitionType()==Definition::TypeClass)
  {
    if (d->getOuterScope())
    {
      searchTemplateSpecs(d->getOuterScope(),result,name,lang);
    }
    const ClassDef *cd=toClassDef(d);
    if (!name.isEmpty()) name+="::";
    QCString clName = d->localName();
    if (clName.endsWith("-p"))
    {
      clName = clName.left(clName.length()-2);
    }
    name+=clName;
    bool isSpecialization = d->localName().find('<')!=-1;
    if (!cd->templateArguments().empty())
    {
      result.push_back(cd->templateArguments());
      if (!isSpecialization)
      {
        name+=tempArgListToString(cd->templateArguments(),lang);
      }
    }
  }
  else
  {
    name+=d->qualifiedName();
  }
}
References Definition::definitionType(), ArgumentList::empty(), QCString::endsWith(), QCString::find(), Definition::getOuterScope(), isSpecialization(), QCString::left(), QCString::length(), Definition::localName(), Definition::name(), Definition::qualifiedName(), searchTemplateSpecs(), tempArgListToString(), ClassDef::templateArguments(), toClassDef(), and Definition::TypeClass.
Referenced by searchTemplateSpecs(), and ClassDefImpl::writeTemplateSpec().
toClassDef() [1/3]
const ClassDef * toClassDef (const Definition * d)
Definition at line 5337 of file classdef.cpp.
{
  if (d && (typeid(*d)==typeid(ClassDefImpl) || typeid(*d)==typeid(ClassDefAliasImpl)))
  {
    return static_cast<const ClassDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
References ClassDefImpl::ClassDefImpl().
toClassDef() [2/3]
ClassDef * toClassDef (Definition * d)
Definition at line 5312 of file classdef.cpp.
{
  if (d && (typeid(*d)==typeid(ClassDefImpl) || typeid(*d)==typeid(ClassDefAliasImpl)))
  {
    return static_cast<ClassDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
References ClassDefImpl::ClassDefImpl().
Referenced by DocSets::addIndexItem(), ClassDefImpl::addInnerCompound(), NamespaceDefImpl::addInnerCompound(), MemberDefImpl::addListReference(), definitionToName(), findMemberLink(), findModuleDef(), findUsingDeclImports(), SymbolResolver::Private::followPath(), generateClassMemberLink(), generateClassOrGlobalLink(), generateClassOrGlobalLink(), FTVHelp::Private::generateTree(), ClassDefAliasImpl::getCdAlias(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedType(), SymbolResolver::Private::getResolvedTypeRec(), ClassDefImpl::getTemplateParameterLists(), SymbolResolver::Private::isAccessibleFrom(), SymbolResolver::Private::isAccessibleFromWithExpScope(), makeQualifiedNameWithTemplateParameters(), MemberDefImpl::moveTo(), scopeIsTemplate(), searchTemplateSpecs(), SearchIndex::setCurrentDoc(), updateCallContextForSmartPointer(), writeDefArgumentList(), writeJavasScriptSearchDataPage(), MemberDefImpl::writeMemberDocSimple(), writeObjCMethodCall(), MemberList::writeSimpleDocumentation(), and VhdlDocGen::writeVHDLTypeDocumentation().
toClassDef() [3/3]
ClassDef * toClassDef (DefinitionMutable * md)
Definition at line 5324 of file classdef.cpp.
{
  Definition *d = toDefinition(md);
  if (d && typeid(*d)==typeid(ClassDefImpl))
  {
    return static_cast<ClassDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
References ClassDefImpl::ClassDefImpl(), and DefinitionMutable::toDefinition.
toClassDefMutable()
ClassDefMutable * toClassDefMutable (Definition * d)
Definition at line 5349 of file classdef.cpp.
{
  if (d && typeid(*d)==typeid(ClassDefImpl))
  {
    return static_cast<ClassDefMutable*>(d);
  }
  else
  {
    return nullptr;
  }
}
References ClassDefImpl::ClassDefImpl().
Referenced by addClassAndNestedClasses(), addClassToContext(), addClassToGroups(), ModuleDefImpl::addClassToModule(), ModuleManager::addClassToModule(), addListReferences(), addMembersToMemberGroup(), ClassDefImpl::addMembersToTemplateInstance(), addMemberToGroups(), ClassDefImpl::addTypeConstraint(), buildCompleteMemberLists(), computeMemberReferences(), computeTemplateClassRelations(), VhdlDocGen::computeVhdlComponentRelations(), ClassDefImpl::countInheritedDecMembers(), countMembers(), createTagLessInstance(), createTemplateInstanceMembers(), ClassDefImpl::deepCopy(), distributeClassGroupRelations(), distributeMemberGroupDocumentation(), findClassRelation(), findSectionsInDocumentation(), findTagLessClasses(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsingDeclarations(), findUsingDeclImports(), generateClassDocs(), generateClassOrGlobalLink(), generateNamespaceClassDocs(), MemberDefImpl::getClassDefMutable(), getClassMutable(), insertMemberAlias(), ClassDefImpl::insertTemplateInstance(), ClassDefImpl::insertUsedFile(), mergeCategories(), ClassDefImpl::mergeCategory(), ClassDefImpl::mergeMembers(), ClassDefImpl::mergeMembersFromBaseClasses(), SymbolResolver::resolveClassMutable(), resolveClassNestingRelations(), setAnonymousEnumType(), ClassDefImpl::setGroupDefForAllMembers(), sortMemberLists(), ClassDefImpl::writeInheritedMemberDeclarations(), and writeTagFile().
writeInheritanceSpecifier()
static void writeInheritanceSpecifier (OutputList & ol, const BaseClassDef & bcd) static
Definition at line 1414 of file classdef.cpp.
{
  if (bcd.prot!=Protection::Public || bcd.virt!=Specifier::Normal)
  {
    ol.startTypewriter();
    ol.docify(" [");
    StringVector sl;
    if      (bcd.prot==Protection::Protected) sl.emplace_back("protected");
    else if (bcd.prot==Protection::Private)   sl.emplace_back("private");
    if      (bcd.virt==Specifier::Virtual)    sl.emplace_back("virtual");
    bool first=true;
    for (const auto &s : sl)
    {
      if (!first) ol.docify(", ");
      ol.docify(s.c_str());
      first=false;
    }
    ol.docify("]");
    ol.endTypewriter();
  }
}
References OutputList::docify(), OutputList::endTypewriter(), Normal, Private, BaseClassDef::prot, Protected, Public, OutputList::startTypewriter(), BaseClassDef::virt, and Virtual.
Referenced by ClassDefImpl::writeInheritanceGraph().