Doxygen: OutputGenIntf Class Reference
OutputGenIntf Class Reference abstract
Abstract interface for output generators.
#include <src/outputgen.h>
Public Member Functions
virtual OutputType type () const =0
virtual std::unique_ptr< OutputGenIntf > clone ()=0
virtual void addCodeGen (OutputCodeList &list)=0
virtual void writeDoc (const IDocNodeAST *ast, const Definition *ctx, const MemberDef *md, int id)=0
virtual void startIndexSection (IndexSection is)=0
virtual void endIndexSection (IndexSection is)=0
virtual void writePageLink (const QCString &name, bool first)=0
virtual void startProjectNumber ()=0
virtual void endProjectNumber ()=0
virtual void writeStyleInfo (int part)=0
virtual void writeSearchInfo ()=0
virtual void writeFooter (const QCString &navPath)=0
virtual void startFile (const QCString &name, const QCString &manName, const QCString &title, int id, int hierarchyLevel)=0
virtual void endFile ()=0
virtual void startTitleHead (const QCString &fileName)=0
virtual void endTitleHead (const QCString &fileName, const QCString &name)=0
virtual void startParagraph (const QCString &classDef=QCString())=0
virtual void endParagraph ()=0
virtual void writeString (const QCString &text)=0
virtual void startIndexListItem ()=0
virtual void endIndexListItem ()=0
virtual void startIndexList ()=0
virtual void endIndexList ()=0
virtual void startIndexKey ()=0
virtual void endIndexKey ()=0
virtual void startIndexValue (bool b)=0
virtual void endIndexValue (const QCString &name, bool b)=0
virtual void startItemList ()=0
virtual void endItemList ()=0
virtual void startIndexItem (const QCString &ref, const QCString &file)=0
virtual void endIndexItem (const QCString &ref, const QCString &file)=0
virtual void docify (const QCString &s)=0
virtual void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)=0
virtual void startTextLink (const QCString &file, const QCString &anchor)=0
virtual void endTextLink ()=0
virtual void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name)=0
virtual void startTypewriter ()=0
virtual void endTypewriter ()=0
virtual void startGroupHeader (int extraLevels=0)=0
virtual void endGroupHeader (int extraLevels=0)=0
virtual void startItemListItem ()=0
virtual void endItemListItem ()=0
virtual void startMemberSections ()=0
virtual void endMemberSections ()=0
virtual void startHeaderSection ()=0
virtual void endHeaderSection ()=0
virtual void startMemberHeader (const QCString &anchor, int typ=2)=0
virtual void endMemberHeader ()=0
virtual void startMemberSubtitle ()=0
virtual void endMemberSubtitle ()=0
virtual void startMemberDocList ()=0
virtual void endMemberDocList ()=0
virtual void startMemberList ()=0
virtual void endMemberList ()=0
virtual void startInlineHeader ()=0
virtual void endInlineHeader ()=0
virtual void startAnonTypeScope (int i1)=0
virtual void endAnonTypeScope (int i1)=0
virtual void startMemberItem (const QCString &anchor, OutputGenerator::MemberItemType type, const QCString &id=QCString())=0
virtual void endMemberItem (OutputGenerator::MemberItemType type)=0
virtual void startMemberTemplateParams ()=0
virtual void endMemberTemplateParams (const QCString &anchor, const QCString &inheritId)=0
virtual void startCompoundTemplateParams ()=0
virtual void endCompoundTemplateParams ()=0
virtual void startMemberGroupHeader (bool b)=0
virtual void endMemberGroupHeader ()=0
virtual void startMemberGroupDocs ()=0
virtual void endMemberGroupDocs ()=0
virtual void startMemberGroup ()=0
virtual void endMemberGroup (bool last)=0
virtual void insertMemberAlign (bool templ=FALSE)=0
virtual void insertMemberAlignLeft (OutputGenerator::MemberItemType typ=OutputGenerator::MemberItemType::Normal, bool templ=FALSE)=0
virtual void writeRuler ()=0
virtual void writeAnchor (const QCString &fileName, const QCString &name)=0
virtual void startEmphasis ()=0
virtual void endEmphasis ()=0
virtual void writeChar (char c)=0
virtual void startMemberDoc (const QCString &clName, const QCString &memName, const QCString &anchor, const QCString &title, int memCount, int memTotal, bool showInline)=0
virtual void endMemberDoc (bool hasArgs)=0
virtual void startDoxyAnchor (const QCString &fName, const QCString &manName, const QCString &anchor, const QCString &name, const QCString &args)=0
virtual void endDoxyAnchor (const QCString &fn, const QCString &anchor)=0
virtual void addLabel (const QCString &fName, const QCString &anchor)=0
virtual void writeLatexSpacing ()=0
virtual void startDescForItem ()=0
virtual void endDescForItem ()=0
virtual void startCenter ()=0
virtual void endCenter ()=0
virtual void startSmall ()=0
virtual void endSmall ()=0
virtual void lineBreak (const QCString &style=QCString())=0
virtual void startBold ()=0
virtual void endBold ()=0
virtual void startMemberDescription (const QCString &anchor, const QCString &inheritId=QCString(), bool typ=false)=0
virtual void endMemberDescription ()=0
virtual void startMemberDeclaration ()=0
virtual void endMemberDeclaration (const QCString &anchor, const QCString &inheritId)=0
virtual void writeInheritedSectionTitle (const QCString &id, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &title, const QCString &name)=0
virtual void startExamples ()=0
virtual void endExamples ()=0
virtual void startIndent ()=0
virtual void endIndent ()=0
virtual void startSection (const QCString &lab, const QCString &title, SectionType t)=0
virtual void endSection (const QCString &lab, SectionType t)=0
virtual void addIndexItem (const QCString &s1, const QCString &s2)=0
virtual void writeSynopsis ()=0
virtual void startClassDiagram ()=0
virtual void endClassDiagram (const ClassDiagram &d, const QCString &f, const QCString &n)=0
virtual void startPageRef ()=0
virtual void endPageRef (const QCString &c, const QCString &a)=0
virtual void startQuickIndices ()=0
virtual void endQuickIndices ()=0
virtual void writeSplitBar (const QCString &name)=0
virtual void writeNavigationPath (const QCString &s)=0
virtual void writeLogo ()=0
virtual void writeQuickLinks (HighlightedItem hli, const QCString &file)=0
virtual void writeSummaryLink (const QCString &file, const QCString &anchor, const QCString &title, bool first)=0
virtual void startContents ()=0
virtual void endContents ()=0
virtual void startPageDoc (const QCString &pageTitle)=0
virtual void endPageDoc ()=0
virtual void writeNonBreakableSpace (int num)=0
virtual void startDescTable (const QCString &title, const bool hasInits)=0
virtual void endDescTable ()=0
virtual void startDescTableRow ()=0
virtual void endDescTableRow ()=0
virtual void startDescTableTitle ()=0
virtual void endDescTableTitle ()=0
virtual void startDescTableInit ()=0
virtual void endDescTableInit ()=0
virtual void startDescTableData ()=0
virtual void endDescTableData ()=0
virtual void startDotGraph ()=0
virtual void endDotGraph (DotClassGraph &g)=0
virtual void startInclDepGraph ()=0
virtual void endInclDepGraph (DotInclDepGraph &g)=0
virtual void startCallGraph ()=0
virtual void endCallGraph (DotCallGraph &g)=0
virtual void startDirDepGraph ()=0
virtual void endDirDepGraph (DotDirDeps &g)=0
virtual void startGroupCollaboration ()=0
virtual void endGroupCollaboration (DotGroupCollaboration &g)=0
virtual void writeGraphicalHierarchy (DotGfxHierarchyTable &g)=0
virtual void startTextBlock (bool dense=FALSE)=0
virtual void endTextBlock (bool paraBreak=FALSE)=0
virtual void lastIndexPage ()=0
virtual void startMemberDocPrefixItem ()=0
virtual void endMemberDocPrefixItem ()=0
virtual void startMemberDocName (bool align)=0
virtual void endMemberDocName ()=0
virtual void startParameterType (bool first, const QCString &key)=0
virtual void endParameterType ()=0
virtual void startParameterName (bool one)=0
virtual void endParameterName ()=0
virtual void startParameterExtra ()=0
virtual void endParameterExtra (bool last, bool one, bool bracket)=0
virtual void startParameterDefVal (const char *separator)=0
virtual void endParameterDefVal ()=0
virtual void startParameterList (bool openBracket)=0
virtual void endParameterList ()=0
virtual void exceptionEntry (const QCString &prefix, bool closeBracket)=0
virtual void startConstraintList (const QCString &header)=0
virtual void startConstraintParam ()=0
virtual void endConstraintParam ()=0
virtual void startConstraintType ()=0
virtual void endConstraintType ()=0
virtual void startConstraintDocs ()=0
virtual void endConstraintDocs ()=0
virtual void endConstraintList ()=0
virtual void startMemberDocSimple (bool b)=0
virtual void endMemberDocSimple (bool b)=0
virtual void startInlineMemberType ()=0
virtual void endInlineMemberType ()=0
virtual void startInlineMemberName ()=0
virtual void endInlineMemberName ()=0
virtual void startInlineMemberDoc ()=0
virtual void endInlineMemberDoc ()=0
virtual void startLabels ()=0
virtual void writeLabel (const QCString &l, bool isLast)=0
virtual void endLabels ()=0
virtual void writeLocalToc (const SectionRefs &refs, const LocalToc &lt)=0
virtual void cleanup ()=0
virtual void startPlainFile (const QCString &name)=0
virtual void endPlainFile ()=0
Detailed Description
Abstract interface for output generators.
Definition at line 126 of file outputgen.h.
Member Function Documentation
addCodeGen()
virtual void OutputGenIntf::addCodeGen (OutputCodeList & list) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
addIndexItem()
virtual void OutputGenIntf::addIndexItem (const QCString & s1, const QCString & s2) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::addIndexItem().
addLabel()
virtual void OutputGenIntf::addLabel (const QCString & fName, const QCString & anchor) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::addLabel().
cleanup()
virtual void OutputGenIntf::cleanup () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::cleanup().
clone()
virtual std::unique_ptr< OutputGenIntf > OutputGenIntf::clone () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
docify()
virtual void OutputGenIntf::docify (const QCString & s) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::docify().
endAnonTypeScope()
virtual void OutputGenIntf::endAnonTypeScope (int i1) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endAnonTypeScope().
endBold()
virtual void OutputGenIntf::endBold () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endBold().
endCallGraph()
virtual void OutputGenIntf::endCallGraph (DotCallGraph & g) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endCallGraph().
endCenter()
virtual void OutputGenIntf::endCenter () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endCenter().
endClassDiagram()
virtual void OutputGenIntf::endClassDiagram (const ClassDiagram & d, const QCString & f, const QCString & n) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endClassDiagram().
endCompoundTemplateParams()
virtual void OutputGenIntf::endCompoundTemplateParams () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endCompoundTemplateParams().
endConstraintDocs()
virtual void OutputGenIntf::endConstraintDocs () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endConstraintDocs().
endConstraintList()
virtual void OutputGenIntf::endConstraintList () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endConstraintList().
endConstraintParam()
virtual void OutputGenIntf::endConstraintParam () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endConstraintParam().
endConstraintType()
virtual void OutputGenIntf::endConstraintType () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endConstraintType().
endContents()
virtual void OutputGenIntf::endContents () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endContents().
endDescForItem()
virtual void OutputGenIntf::endDescForItem () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endDescForItem().
endDescTable()
virtual void OutputGenIntf::endDescTable () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endDescTable().
endDescTableData()
virtual void OutputGenIntf::endDescTableData () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endDescTableData().
endDescTableInit()
virtual void OutputGenIntf::endDescTableInit () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endDescTableInit().
endDescTableRow()
virtual void OutputGenIntf::endDescTableRow () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endDescTableRow().
endDescTableTitle()
virtual void OutputGenIntf::endDescTableTitle () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endDescTableTitle().
endDirDepGraph()
virtual void OutputGenIntf::endDirDepGraph (DotDirDeps & g) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endDirDepGraph().
endDotGraph()
virtual void OutputGenIntf::endDotGraph (DotClassGraph & g) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endDotGraph().
endDoxyAnchor()
virtual void OutputGenIntf::endDoxyAnchor (const QCString & fn, const QCString & anchor) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endDoxyAnchor().
endEmphasis()
virtual void OutputGenIntf::endEmphasis () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endEmphasis().
endExamples()
virtual void OutputGenIntf::endExamples () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endExamples().
endFile()
virtual void OutputGenIntf::endFile () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endFile().
endGroupCollaboration()
virtual void OutputGenIntf::endGroupCollaboration (DotGroupCollaboration & g) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endGroupCollaboration().
endGroupHeader()
virtual void OutputGenIntf::endGroupHeader (int extraLevels = 0) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endGroupHeader().
endHeaderSection()
virtual void OutputGenIntf::endHeaderSection () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endHeaderSection().
endInclDepGraph()
virtual void OutputGenIntf::endInclDepGraph (DotInclDepGraph & g) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endInclDepGraph().
endIndent()
virtual void OutputGenIntf::endIndent () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endIndent().
endIndexItem()
virtual void OutputGenIntf::endIndexItem (const QCString & ref, const QCString & file) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endIndexItem().
endIndexKey()
virtual void OutputGenIntf::endIndexKey () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endIndexKey().
endIndexList()
virtual void OutputGenIntf::endIndexList () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endIndexList().
endIndexListItem()
virtual void OutputGenIntf::endIndexListItem () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endIndexListItem().
endIndexSection()
virtual void OutputGenIntf::endIndexSection (IndexSection is) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endIndexSection().
endIndexValue()
virtual void OutputGenIntf::endIndexValue (const QCString & name, bool b) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endIndexValue().
endInlineHeader()
virtual void OutputGenIntf::endInlineHeader () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endInlineHeader().
endInlineMemberDoc()
virtual void OutputGenIntf::endInlineMemberDoc () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endInlineMemberDoc().
endInlineMemberName()
virtual void OutputGenIntf::endInlineMemberName () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endInlineMemberName().
endInlineMemberType()
virtual void OutputGenIntf::endInlineMemberType () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endInlineMemberType().
endItemList()
virtual void OutputGenIntf::endItemList () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endItemList().
endItemListItem()
virtual void OutputGenIntf::endItemListItem () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endItemListItem().
endLabels()
virtual void OutputGenIntf::endLabels () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endLabels().
endMemberDeclaration()
virtual void OutputGenIntf::endMemberDeclaration (const QCString & anchor, const QCString & inheritId) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberDeclaration().
endMemberDescription()
virtual void OutputGenIntf::endMemberDescription () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberDescription().
endMemberDoc()
virtual void OutputGenIntf::endMemberDoc (bool hasArgs) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberDoc().
endMemberDocList()
virtual void OutputGenIntf::endMemberDocList () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberDocList().
endMemberDocName()
virtual void OutputGenIntf::endMemberDocName () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberDocName().
endMemberDocPrefixItem()
virtual void OutputGenIntf::endMemberDocPrefixItem () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberDocPrefixItem().
endMemberDocSimple()
virtual void OutputGenIntf::endMemberDocSimple (bool b) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberDocSimple().
endMemberGroup()
virtual void OutputGenIntf::endMemberGroup (bool last) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberGroup().
endMemberGroupDocs()
virtual void OutputGenIntf::endMemberGroupDocs () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberGroupDocs().
endMemberGroupHeader()
virtual void OutputGenIntf::endMemberGroupHeader () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberGroupHeader().
endMemberHeader()
virtual void OutputGenIntf::endMemberHeader () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberHeader().
endMemberItem()
virtual void OutputGenIntf::endMemberItem (OutputGenerator::MemberItemType type) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberItem().
endMemberList()
virtual void OutputGenIntf::endMemberList () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberList().
endMemberSections()
virtual void OutputGenIntf::endMemberSections () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberSections().
endMemberSubtitle()
virtual void OutputGenIntf::endMemberSubtitle () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberSubtitle().
endMemberTemplateParams()
virtual void OutputGenIntf::endMemberTemplateParams (const QCString & anchor, const QCString & inheritId) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endMemberTemplateParams().
endPageDoc()
virtual void OutputGenIntf::endPageDoc () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endPageDoc().
endPageRef()
virtual void OutputGenIntf::endPageRef (const QCString & c, const QCString & a) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endPageRef().
endParagraph()
virtual void OutputGenIntf::endParagraph () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endParagraph().
endParameterDefVal()
virtual void OutputGenIntf::endParameterDefVal () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endParameterDefVal().
endParameterExtra()
virtual void OutputGenIntf::endParameterExtra (bool last, bool one, bool bracket) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endParameterExtra().
endParameterList()
virtual void OutputGenIntf::endParameterList () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endParameterList().
endParameterName()
virtual void OutputGenIntf::endParameterName () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endParameterName().
endParameterType()
virtual void OutputGenIntf::endParameterType () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endParameterType().
endPlainFile()
virtual void OutputGenIntf::endPlainFile () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endPlainFile().
endProjectNumber()
virtual void OutputGenIntf::endProjectNumber () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endProjectNumber().
endQuickIndices()
virtual void OutputGenIntf::endQuickIndices () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endQuickIndices().
endSection()
virtual void OutputGenIntf::endSection (const QCString & lab, SectionType t) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endSection().
endSmall()
virtual void OutputGenIntf::endSmall () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endSmall().
endTextBlock()
virtual void OutputGenIntf::endTextBlock (bool paraBreak = FALSE) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endTextBlock().
endTextLink()
virtual void OutputGenIntf::endTextLink () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endTextLink().
endTitleHead()
virtual void OutputGenIntf::endTitleHead (const QCString & fileName, const QCString & name) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endTitleHead().
endTypewriter()
virtual void OutputGenIntf::endTypewriter () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::endTypewriter().
exceptionEntry()
virtual void OutputGenIntf::exceptionEntry (const QCString & prefix, bool closeBracket) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::exceptionEntry().
insertMemberAlign()
virtual void OutputGenIntf::insertMemberAlign (bool templ = FALSE) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::insertMemberAlign().
insertMemberAlignLeft()
virtual void OutputGenIntf::insertMemberAlignLeft (OutputGenerator::MemberItemType typ = OutputGenerator::MemberItemType::Normal, bool templ = FALSE) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::insertMemberAlignLeft().
lastIndexPage()
virtual void OutputGenIntf::lastIndexPage () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::lastIndexPage().
lineBreak()
virtual void OutputGenIntf::lineBreak (const QCString & style = QCString()) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::lineBreak().
startAnonTypeScope()
virtual void OutputGenIntf::startAnonTypeScope (int i1) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startAnonTypeScope().
startBold()
virtual void OutputGenIntf::startBold () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startBold().
startCallGraph()
virtual void OutputGenIntf::startCallGraph () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startCallGraph().
startCenter()
virtual void OutputGenIntf::startCenter () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startCenter().
startClassDiagram()
virtual void OutputGenIntf::startClassDiagram () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startClassDiagram().
startCompoundTemplateParams()
virtual void OutputGenIntf::startCompoundTemplateParams () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startCompoundTemplateParams().
startConstraintDocs()
virtual void OutputGenIntf::startConstraintDocs () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startConstraintDocs().
startConstraintList()
virtual void OutputGenIntf::startConstraintList (const QCString & header) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startConstraintList().
startConstraintParam()
virtual void OutputGenIntf::startConstraintParam () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startConstraintParam().
startConstraintType()
virtual void OutputGenIntf::startConstraintType () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startConstraintType().
startContents()
virtual void OutputGenIntf::startContents () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startContents().
startDescForItem()
virtual void OutputGenIntf::startDescForItem () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startDescForItem().
startDescTable()
virtual void OutputGenIntf::startDescTable (const QCString & title, const bool hasInits) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startDescTable().
startDescTableData()
virtual void OutputGenIntf::startDescTableData () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startDescTableData().
startDescTableInit()
virtual void OutputGenIntf::startDescTableInit () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startDescTableInit().
startDescTableRow()
virtual void OutputGenIntf::startDescTableRow () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startDescTableRow().
startDescTableTitle()
virtual void OutputGenIntf::startDescTableTitle () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startDescTableTitle().
startDirDepGraph()
virtual void OutputGenIntf::startDirDepGraph () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startDirDepGraph().
startDotGraph()
virtual void OutputGenIntf::startDotGraph () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startDotGraph().
startDoxyAnchor()
virtual void OutputGenIntf::startDoxyAnchor (const QCString & fName, const QCString & manName, const QCString & anchor, const QCString & name, const QCString & args) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startDoxyAnchor().
startEmphasis()
virtual void OutputGenIntf::startEmphasis () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startEmphasis().
startExamples()
virtual void OutputGenIntf::startExamples () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startExamples().
startFile()
virtual void OutputGenIntf::startFile (const QCString & name, const QCString & manName, const QCString & title, int id, int hierarchyLevel) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startFile().
startGroupCollaboration()
virtual void OutputGenIntf::startGroupCollaboration () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startGroupCollaboration().
startGroupHeader()
virtual void OutputGenIntf::startGroupHeader (int extraLevels = 0) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startGroupHeader().
startHeaderSection()
virtual void OutputGenIntf::startHeaderSection () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startHeaderSection().
startInclDepGraph()
virtual void OutputGenIntf::startInclDepGraph () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startInclDepGraph().
startIndent()
virtual void OutputGenIntf::startIndent () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startIndent().
startIndexItem()
virtual void OutputGenIntf::startIndexItem (const QCString & ref, const QCString & file) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startIndexItem().
startIndexKey()
virtual void OutputGenIntf::startIndexKey () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startIndexKey().
startIndexList()
virtual void OutputGenIntf::startIndexList () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startIndexList().
startIndexListItem()
virtual void OutputGenIntf::startIndexListItem () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startIndexListItem().
startIndexSection()
virtual void OutputGenIntf::startIndexSection (IndexSection is) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startIndexSection().
startIndexValue()
virtual void OutputGenIntf::startIndexValue (bool b) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startIndexValue().
startInlineHeader()
virtual void OutputGenIntf::startInlineHeader () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startInlineHeader().
startInlineMemberDoc()
virtual void OutputGenIntf::startInlineMemberDoc () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startInlineMemberDoc().
startInlineMemberName()
virtual void OutputGenIntf::startInlineMemberName () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startInlineMemberName().
startInlineMemberType()
virtual void OutputGenIntf::startInlineMemberType () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startInlineMemberType().
startItemList()
virtual void OutputGenIntf::startItemList () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startItemList().
startItemListItem()
virtual void OutputGenIntf::startItemListItem () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startItemListItem().
startLabels()
virtual void OutputGenIntf::startLabels () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startLabels().
startMemberDeclaration()
virtual void OutputGenIntf::startMemberDeclaration () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberDeclaration().
startMemberDescription()
virtual void OutputGenIntf::startMemberDescription (const QCString & anchor, const QCString & inheritId = QCString(), bool typ = false) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberDescription().
startMemberDoc()
virtual void OutputGenIntf::startMemberDoc (const QCString & clName, const QCString & memName, const QCString & anchor, const QCString & title, int memCount, int memTotal, bool showInline) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberDoc().
startMemberDocList()
virtual void OutputGenIntf::startMemberDocList () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberDocList().
startMemberDocName()
virtual void OutputGenIntf::startMemberDocName (bool align) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberDocName().
startMemberDocPrefixItem()
virtual void OutputGenIntf::startMemberDocPrefixItem () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberDocPrefixItem().
startMemberDocSimple()
virtual void OutputGenIntf::startMemberDocSimple (bool b) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberDocSimple().
startMemberGroup()
virtual void OutputGenIntf::startMemberGroup () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberGroup().
startMemberGroupDocs()
virtual void OutputGenIntf::startMemberGroupDocs () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberGroupDocs().
startMemberGroupHeader()
virtual void OutputGenIntf::startMemberGroupHeader (bool b) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberGroupHeader().
startMemberHeader()
virtual void OutputGenIntf::startMemberHeader (const QCString & anchor, int typ = 2) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberHeader().
startMemberItem()
virtual void OutputGenIntf::startMemberItem (const QCString & anchor, OutputGenerator::MemberItemType type, const QCString & id = QCString()) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberItem().
startMemberList()
virtual void OutputGenIntf::startMemberList () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberList().
startMemberSections()
virtual void OutputGenIntf::startMemberSections () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberSections().
startMemberSubtitle()
virtual void OutputGenIntf::startMemberSubtitle () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberSubtitle().
startMemberTemplateParams()
virtual void OutputGenIntf::startMemberTemplateParams () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startMemberTemplateParams().
startPageDoc()
virtual void OutputGenIntf::startPageDoc (const QCString & pageTitle) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startPageDoc().
startPageRef()
virtual void OutputGenIntf::startPageRef () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startPageRef().
startParagraph()
virtual void OutputGenIntf::startParagraph (const QCString & classDef = QCString()) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startParagraph().
startParameterDefVal()
virtual void OutputGenIntf::startParameterDefVal (const char * separator) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startParameterDefVal().
startParameterExtra()
virtual void OutputGenIntf::startParameterExtra () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startParameterExtra().
startParameterList()
virtual void OutputGenIntf::startParameterList (bool openBracket) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startParameterList().
startParameterName()
virtual void OutputGenIntf::startParameterName (bool one) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startParameterName().
startParameterType()
virtual void OutputGenIntf::startParameterType (bool first, const QCString & key) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startParameterType().
startPlainFile()
virtual void OutputGenIntf::startPlainFile (const QCString & name) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startPlainFile().
startProjectNumber()
virtual void OutputGenIntf::startProjectNumber () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startProjectNumber().
startQuickIndices()
virtual void OutputGenIntf::startQuickIndices () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startQuickIndices().
startSection()
virtual void OutputGenIntf::startSection (const QCString & lab, const QCString & title, SectionType t) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startSection().
startSmall()
virtual void OutputGenIntf::startSmall () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startSmall().
startTextBlock()
virtual void OutputGenIntf::startTextBlock (bool dense = FALSE) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startTextBlock().
startTextLink()
virtual void OutputGenIntf::startTextLink (const QCString & file, const QCString & anchor) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startTextLink().
startTitleHead()
virtual void OutputGenIntf::startTitleHead (const QCString & fileName) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startTitleHead().
startTypewriter()
virtual void OutputGenIntf::startTypewriter () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::startTypewriter().
type()
virtual OutputType OutputGenIntf::type () const pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
writeAnchor()
virtual void OutputGenIntf::writeAnchor (const QCString & fileName, const QCString & name) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeAnchor().
writeChar()
virtual void OutputGenIntf::writeChar (char c) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeChar().
writeDoc()
virtual void OutputGenIntf::writeDoc (const IDocNodeAST * ast, const Definition * ctx, const MemberDef * md, int id) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeDoc().
writeFooter()
virtual void OutputGenIntf::writeFooter (const QCString & navPath) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeFooter().
writeGraphicalHierarchy()
virtual void OutputGenIntf::writeGraphicalHierarchy (DotGfxHierarchyTable & g) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeGraphicalHierarchy().
writeInheritedSectionTitle()
virtual void OutputGenIntf::writeInheritedSectionTitle (const QCString & id, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & title, const QCString & name) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeInheritedSectionTitle().
writeLabel()
virtual void OutputGenIntf::writeLabel (const QCString & l, bool isLast) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeLabel().
writeLatexSpacing()
virtual void OutputGenIntf::writeLatexSpacing () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeLatexSpacing().
writeLocalToc()
virtual void OutputGenIntf::writeLocalToc (const SectionRefs & refs, const LocalToc & lt) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeLocalToc().
writeLogo()
virtual void OutputGenIntf::writeLogo () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeLogo().
writeNavigationPath()
virtual void OutputGenIntf::writeNavigationPath (const QCString & s) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeNavigationPath().
writeNonBreakableSpace()
virtual void OutputGenIntf::writeNonBreakableSpace (int num) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeNonBreakableSpace().
writeObjectLink()
virtual void OutputGenIntf::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeObjectLink().
writePageLink()
virtual void OutputGenIntf::writePageLink (const QCString & name, bool first) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writePageLink().
writeQuickLinks()
virtual void OutputGenIntf::writeQuickLinks (HighlightedItem hli, const QCString & file) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeQuickLinks().
writeRuler()
virtual void OutputGenIntf::writeRuler () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeRuler().
writeSearchInfo()
virtual void OutputGenIntf::writeSearchInfo () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeSearchInfo().
writeSplitBar()
virtual void OutputGenIntf::writeSplitBar (const QCString & name) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeSplitBar().
writeStartAnnoItem()
virtual void OutputGenIntf::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeStartAnnoItem().
writeString()
virtual void OutputGenIntf::writeString (const QCString & text) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeString().
writeStyleInfo()
virtual void OutputGenIntf::writeStyleInfo (int part) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeStyleInfo().
writeSummaryLink()
virtual void OutputGenIntf::writeSummaryLink (const QCString & file, const QCString & anchor, const QCString & title, bool first) pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeSummaryLink().
writeSynopsis()
virtual void OutputGenIntf::writeSynopsis () pure virtual
Implemented in DocbookGenerator, HtmlGenerator, LatexGenerator, ManGenerator, and RTFGenerator.
Referenced by OutputList::writeSynopsis().
The documentation for this class was generated from the following file:
src/outputgen.h