Doxygen: ConfigOption Class Reference
ConfigOption Class Reference abstract
Abstract base class for any configuration option.
#include <src/configimpl.h>
Public Types
enum OptionType {
O_Info , O_List , O_Enum , O_String ,
O_Int , O_Bool , O_Obsolete , O_Disabled
}
enum { MAX_OPTION_LENGTH = 23 }
Public Member Functions
ConfigOption (OptionType t)
OptionType kind () const
QCString name () const
QCString docs () const
QCString dependsOn () const
void addDependency (const char *dep)
void setEncoding (const QCString &e)
void setUserComment (const QCString &u)
Protected Member Functions
virtual void writeTemplate (TextStream &t, bool sl, bool upd)=0
virtual void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)=0
virtual void writeXMLDoxyfile (TextStream &t)=0
virtual void writeXSDDoxyfile (TextStream &t)=0
virtual void convertStrToVal (Config::CompareMode)
virtual void emptyValueToDefault ()
virtual void substEnvVars ()=0
virtual void init ()
virtual bool isDefault ()
void writeBoolValue (TextStream &t, bool v, bool initSpace=true)
void writeIntValue (TextStream &t, int i, bool initSpace=true)
void writeStringValue (TextStream &t, const QCString &s, bool initSpace=true, bool wasQuoted=false)
void writeStringList (TextStream &t, const StringVector &l)
Protected Attributes
QCString m_spaces
QCString m_name
QCString m_doc
QCString m_dependency
QCString m_encoding
QCString m_userComment
OptionType m_kind
Friends
class ConfigImpl
Detailed Description
Abstract base class for any configuration option.
Definition at line 37 of file configimpl.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MAX_OPTION_LENGTH
Maximum length of an option in the config file. Used for alignment purposes.
Definition at line 56 of file configimpl.h.
    {
     /*! Maximum length of an option in the config file. Used for
      *  alignment purposes.
      */
      MAX_OPTION_LENGTH = 23
    };
OptionType
enum ConfigOption::OptionType
The type of option
Enumerator
O_Info
A section header.
O_List
A list of items.
O_Enum
A fixed set of items.
O_String
A single item.
O_Int
An integer value.
O_Bool
A boolean value.
O_Obsolete
An obsolete option.
O_Disabled
Disabled compile time option.
Definition at line 45 of file configimpl.h.
    {
      O_Info,      //!< A section header
      O_List,      //!< A list of items
      O_Enum,      //!< A fixed set of items
      O_String,    //!< A single item
      O_Int,       //!< An integer value
      O_Bool,      //!< A boolean value
      O_Obsolete,  //!< An obsolete option
      O_Disabled   //!< Disabled compile time option
    };
Constructor & Destructor Documentation
ConfigOption()
ConfigOption::ConfigOption (OptionType t) inline
Definition at line 63 of file configimpl.h.
                               : m_kind(t)
    {
      m_spaces.fill(' ',40);
    }
References m_kind, and m_spaces.
Referenced by ConfigBool::ConfigBool(), ConfigDisabled::ConfigDisabled(), ConfigEnum::ConfigEnum(), ConfigImpl, ConfigInfo::ConfigInfo(), ConfigInt::ConfigInt(), ConfigList::ConfigList(), ConfigObsolete::ConfigObsolete(), and ConfigString::ConfigString().
Member Function Documentation
addDependency()
void ConfigOption::addDependency (const char * dep) inline
Definition at line 74 of file configimpl.h.
{ m_dependency = dep; }
References m_dependency.
compareDoxyfile()
virtual void ConfigOption::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) protected pure virtual
Implemented in ConfigBool, ConfigDisabled, ConfigEnum, ConfigInfo, ConfigInt, ConfigList, ConfigObsolete, and ConfigString.
Referenced by ConfigImpl::compareDoxyfile().
convertStrToVal()
virtual void ConfigOption::convertStrToVal (Config::CompareMode) inline protected virtual
Reimplemented in ConfigBool, ConfigEnum, and ConfigInt.
Definition at line 83 of file configimpl.h.
{}
Referenced by ConfigImpl::convertStrToVal().
dependsOn()
QCString ConfigOption::dependsOn () const inline
Definition at line 73 of file configimpl.h.
{ return m_dependency; }
References m_dependency.
Referenced by Config::checkAndCorrect(), and ConfigImpl::init().
docs()
QCString ConfigOption::docs () const inline
Definition at line 71 of file configimpl.h.
{ return m_doc; }
References m_doc.
emptyValueToDefault()
virtual void ConfigOption::emptyValueToDefault () inline protected virtual
Reimplemented in ConfigList, and ConfigString.
Definition at line 84 of file configimpl.h.
{}
Referenced by ConfigImpl::emptyValueToDefault().
init()
virtual void ConfigOption::init () inline protected virtual
Reimplemented in ConfigBool, ConfigEnum, ConfigInt, ConfigList, and ConfigString.
Definition at line 86 of file configimpl.h.
{}
Referenced by ConfigImpl::init().
isDefault()
virtual bool ConfigOption::isDefault () inline protected virtual
Reimplemented in ConfigBool, ConfigEnum, ConfigInt, ConfigList, and ConfigString.
Definition at line 87 of file configimpl.h.
{ return true; }
kind()
OptionType ConfigOption::kind () const inline
returns the kind of option this is.
Definition at line 69 of file configimpl.h.
{ return m_kind; }
References m_kind.
Referenced by Config::checkAndCorrect(), DocPara::handleDoxyConfig(), and Config::updateObsolete().
name()
QCString ConfigOption::name () const inline
Definition at line 70 of file configimpl.h.
{ return m_name; }
References m_name.
Referenced by Config::checkAndCorrect(), ConfigBool::ConfigBool(), ConfigDisabled::ConfigDisabled(), ConfigEnum::ConfigEnum(), ConfigInfo::ConfigInfo(), ConfigInt::ConfigInt(), ConfigList::ConfigList(), ConfigObsolete::ConfigObsolete(), ConfigString::ConfigString(), and ConfigImpl::init().
setEncoding()
void ConfigOption::setEncoding (const QCString & e) inline
Definition at line 75 of file configimpl.h.
{ m_encoding = e; }
References m_encoding.
setUserComment()
void ConfigOption::setUserComment (const QCString & u) inline
Definition at line 76 of file configimpl.h.
{ m_userComment += u; }
References m_userComment.
substEnvVars()
virtual void ConfigOption::substEnvVars () protected pure virtual
Implemented in ConfigBool, ConfigDisabled, ConfigEnum, ConfigInfo, ConfigInt, ConfigList, ConfigObsolete, and ConfigString.
Referenced by ConfigImpl::substituteEnvironmentVars().
writeBoolValue()
void ConfigOption::writeBoolValue (TextStream & t, bool v, bool initSpace = true) protected
Definition at line 137 of file configimpl.l.
{
  if (initSpace) t << " ";
  if (v) t << "YES"; else t << "NO";
}
Referenced by ConfigBool::writeTemplate(), and ConfigBool::writeXMLDoxyfile().
writeIntValue()
void ConfigOption::writeIntValue (TextStream & t, int i, bool initSpace = true) protected
Definition at line 143 of file configimpl.l.
{
  if (initSpace) t << " ";
  t << i;
}
Referenced by ConfigInt::writeTemplate(), and ConfigInt::writeXMLDoxyfile().
writeStringList()
void ConfigOption::writeStringList (TextStream & t, const StringVector & l) protected
Definition at line 181 of file configimpl.l.
{
  bool first=TRUE;
  for (const auto &p : l)
  {
    if (!first) t << " \\\n";
    QCString s=p.c_str();
    if (!first)
      t << "                        ";
    bool wasQuoted = ((s.at(0)=='"') && (s.at(s.length()-1)=='"'));
    if (wasQuoted)
    {
      s = s.mid(1,s.length()-2);
    }
    writeStringValue(t,s,true,wasQuoted);
    first=FALSE;
  }
}
References QCString::at(), FALSE, QCString::length(), QCString::mid(), TRUE, and writeStringValue().
Referenced by ConfigList::writeTemplate().
writeStringValue()
void ConfigOption::writeStringValue (TextStream & t, const QCString & s, bool initSpace = true, bool wasQuoted = false) protected
Definition at line 149 of file configimpl.l.
{
  char c = 0;
  bool needsEscaping=wasQuoted;
  // convert the string back to it original g_encoding
  QCString se = configStringRecode(s,"UTF-8",m_encoding);
  if (se.isEmpty()) return;
  const char *p=se.data();
  if (p)
  {
    if (initSpace) t << " ";
    while ((c=*p++)!=0 && !needsEscaping)
      needsEscaping = (c==' ' || c== ',' || c=='\n' || c=='\t' || c=='"' || c=='#');
    if (needsEscaping)
    {
      t << "\"";
      p=se.data();
      while (*p)
      {
        if (*p==' ' && *(p+1)=='\0') break; // skip inserted space at the end
        if (*p=='"') t << "\\"; // escape quotes
        t << *p++;
      }
      t << "\"";
    }
    else
    {
      t << se;
    }
  }
}
References configStringRecode(), QCString::data(), QCString::isEmpty(), and m_encoding.
Referenced by writeStringList(), ConfigBool::writeTemplate(), ConfigEnum::writeTemplate(), ConfigInt::writeTemplate(), ConfigString::writeTemplate(), ConfigEnum::writeXMLDoxyfile(), ConfigList::writeXMLDoxyfile(), and ConfigString::writeXMLDoxyfile().
writeTemplate()
virtual void ConfigOption::writeTemplate (TextStream & t, bool sl, bool upd) protected pure virtual
Implemented in ConfigBool, ConfigDisabled, ConfigEnum, ConfigInfo, ConfigInt, ConfigList, ConfigObsolete, and ConfigString.
Referenced by ConfigImpl::writeTemplate().
writeXMLDoxyfile()
virtual void ConfigOption::writeXMLDoxyfile (TextStream & t) protected pure virtual
Implemented in ConfigBool, ConfigDisabled, ConfigEnum, ConfigInfo, ConfigInt, ConfigList, ConfigObsolete, and ConfigString.
Referenced by ConfigImpl::writeXMLDoxyfile().
writeXSDDoxyfile()
virtual void ConfigOption::writeXSDDoxyfile (TextStream & t) protected pure virtual
Implemented in ConfigBool, ConfigDisabled, ConfigEnum, ConfigInfo, ConfigInt, ConfigList, ConfigObsolete, and ConfigString.
Referenced by ConfigImpl::writeXSDDoxyfile().
Friends And Related Symbol Documentation
ConfigImpl
friend class ConfigImpl friend
Definition at line 39 of file configimpl.h.
References ConfigImpl, and ConfigOption().
Referenced by ConfigImpl.
Member Data Documentation
m_dependency
QCString ConfigOption::m_dependency protected
Definition at line 97 of file configimpl.h.
Referenced by addDependency(), and dependsOn().
m_doc
QCString ConfigOption::m_doc protected
Definition at line 96 of file configimpl.h.
Referenced by ConfigBool::ConfigBool(), ConfigEnum::ConfigEnum(), ConfigInfo::ConfigInfo(), ConfigInt::ConfigInt(), ConfigList::ConfigList(), ConfigString::ConfigString(), docs(), ConfigBool::writeTemplate(), ConfigEnum::writeTemplate(), ConfigInfo::writeTemplate(), ConfigInt::writeTemplate(), ConfigList::writeTemplate(), and ConfigString::writeTemplate().
m_encoding
QCString ConfigOption::m_encoding protected
Definition at line 98 of file configimpl.h.
Referenced by setEncoding(), and writeStringValue().
m_kind
OptionType ConfigOption::m_kind protected
Definition at line 100 of file configimpl.h.
Referenced by ConfigOption(), and kind().
m_name
QCString ConfigOption::m_name protected
Definition at line 95 of file configimpl.h.
Referenced by ConfigBool::ConfigBool(), ConfigDisabled::ConfigDisabled(), ConfigEnum::ConfigEnum(), ConfigInfo::ConfigInfo(), ConfigInt::ConfigInt(), ConfigList::ConfigList(), ConfigObsolete::ConfigObsolete(), ConfigString::ConfigString(), ConfigBool::convertStrToVal(), ConfigEnum::convertStrToVal(), ConfigInt::convertStrToVal(), name(), ConfigBool::writeTemplate(), ConfigEnum::writeTemplate(), ConfigInt::writeTemplate(), ConfigList::writeTemplate(), ConfigString::writeTemplate(), ConfigBool::writeXMLDoxyfile(), ConfigEnum::writeXMLDoxyfile(), ConfigInt::writeXMLDoxyfile(), ConfigList::writeXMLDoxyfile(), ConfigString::writeXMLDoxyfile(), ConfigBool::writeXSDDoxyfile(), ConfigDisabled::writeXSDDoxyfile(), ConfigEnum::writeXSDDoxyfile(), ConfigInt::writeXSDDoxyfile(), ConfigList::writeXSDDoxyfile(), and ConfigString::writeXSDDoxyfile().
m_spaces
QCString ConfigOption::m_spaces protected
Definition at line 94 of file configimpl.h.
Referenced by ConfigOption(), ConfigBool::writeTemplate(), ConfigEnum::writeTemplate(), ConfigInt::writeTemplate(), ConfigList::writeTemplate(), and ConfigString::writeTemplate().
m_userComment
QCString ConfigOption::m_userComment protected
Definition at line 99 of file configimpl.h.
Referenced by ConfigImpl::compareDoxyfile(), setUserComment(), ConfigBool::writeTemplate(), ConfigEnum::writeTemplate(), ConfigInt::writeTemplate(), ConfigList::writeTemplate(), and ConfigString::writeTemplate().
The documentation for this class was generated from the following files:
src/configimpl.h
src/configimpl.l