Doxygen: ConceptDefImpl Class Reference
ConceptDefImpl Class Reference
Public Member Functions
ConceptDefImpl (const QCString &fileName, int startLine, int startColumn, const QCString &name, const QCString &tagRef=QCString(), const QCString &tagFile=QCString())
~ConceptDefImpl ()
ConceptDef * resolveAlias ()
DefType definitionType () const override
CodeSymbolType codeSymbolType () const override
QCString getOutputFileBase () const override
bool hasDetailedDescription () const override
QCString displayName (bool includeScope=true) const override
const IncludeInfo * includeInfo () const override
ArgumentList getTemplateParameterList () const override
QCString anchor () const override
bool isLinkableInProject () const override
bool isLinkable () const override
QCString initializer () const override
void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const override
const NamespaceDef * getNamespaceDef () const override
const FileDef * getFileDef () const override
const ModuleDef * getModuleDef () const override
QCString title () const override
int groupId () const override
void setIncludeFile (FileDef *fd, const QCString &incName, bool local, bool force) override
void setTemplateArguments (const ArgumentList &al) override
void setNamespace (NamespaceDef *nd) override
void setFileDef (FileDef *fd) override
void setModuleDef (ModuleDef *mod) override
void writeTagFile (TextStream &) override
void writeDocumentation (OutputList &) override
void setInitializer (const QCString &init) override
void findSectionsInDocumentation () override
void setGroupId (int id) override
void writeBriefDescription (OutputList &) const
void writeAuthorSection (OutputList &ol) const
void writeIncludeFiles (OutputList &ol) const
void writeDetailedDescription (OutputList &ol, const QCString &title) const
void writeDefinition (OutputList &ol, const QCString &title) const
void addConceptAttributes (OutputList &ol) const
Public Member Functions inherited from DefinitionMixin< ConceptDefMutable >
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=nullptr, const char *d=nullptr, bool isSymbol=TRUE)
~DefinitionMixin ()=default
bool isAlias () const override
const QCString & name () const override
bool isAnonymous () const override
const QCString & localName () const override
QCString qualifiedName () const override
QCString symbolName () const override
QCString getSourceFileBase () const override
QCString getSourceAnchor () const override
QCString documentation () const override
int docLine () const override
QCString docFile () const override
QCString briefDescription (bool abbreviate=FALSE) const override
QCString briefDescriptionAsTooltip () const override
int briefLine () const override
QCString inbodyDocumentation () const override
QCString inbodyFile () const override
int inbodyLine () const override
QCString briefFile () const override
QCString getDefFileName () const override
QCString getDefFileExtension () const override
int getDefLine () const override
int getDefColumn () const override
bool hasDocumentation () const override
bool hasUserDocumentation () const override
bool isVisibleInProject () const override
bool isVisible () const override
bool isHidden () const override
bool isArtificial () const override
bool isExported () const override
QCString getReference () const override
bool isReference () const override
QCString externalReference (const QCString &relPath) const override
int getStartDefLine () const override
int getStartBodyLine () const override
int getEndBodyLine () const override
const FileDef * getBodyDef () const override
SrcLangExt getLanguage () const override
const GroupList & partOfGroups () const override
bool isLinkableViaGroup () const override
const RefItemVector & xrefListItems () const override
const Definition * findInnerCompound (const QCString &name) const override
Definition * getOuterScope () const override
const MemberVector & getReferencesMembers () const override
const MemberVector & getReferencedByMembers () const override
bool hasSections () const override
bool hasSources () const override
bool hasBriefDescription () const override
QCString id () const override
const SectionRefs & getSectionRefs () const override
void setName (const QCString &name) override
void setId (const QCString &name) override
void setDefFile (const QCString &df, int defLine, int defColumn) override
void setDocumentation (const QCString &doc, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE) override
void setBriefDescription (const QCString &brief, const QCString &briefFile, int briefLine) override
void setInbodyDocumentation (const QCString &doc, const QCString &docFile, int docLine) override
void setReference (const QCString &r) override
void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList) override
void setBodySegment (int defLine, int bls, int ble) override
void setBodyDef (const FileDef *fd) override
void addSourceReferencedBy (MemberDef *md) override
void addSourceReferences (MemberDef *md) override
void setRefItems (const RefItemVector &sli) override
void mergeRefItems (Definition *def) override
void mergeReferences (const Definition *other) override
void mergeReferencedBy (const Definition *other) override
void addInnerCompound (Definition *def) override
void setOuterScope (Definition *def) override
void setHidden (bool b) override
void setArtificial (bool b) override
void setExported (bool b) override
void setLanguage (SrcLangExt lang) override
void writeSourceDef (OutputList &ol, const QCString &scopeName) const override
void writeInlineCode (OutputList &ol, const QCString &scopeName) const override
bool hasSourceRefs () const override
bool hasSourceReffedBy () const override
void writeSourceRefs (OutputList &ol, const QCString &scopeName) const override
void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const override
void makePartOfGroup (GroupDef *gd) override
void writeNavigationPath (OutputList &ol) const override
QCString navigationPathAsString () const override
void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const override
void writeSummaryLinks (OutputList &ol) const override
QCString pathFragment () const override
void writeDocAnchorsToTagFile (TextStream &fs) const override
void setLocalName (const QCString &name) override
void addSectionsToIndex () override
void writeToc (OutputList &ol, const LocalToc &lt) const override
void computeTooltip () override
void _setSymbolName (const QCString &name) override
QCString _symbolName () const override
Public Member Functions inherited from DefinitionMutable
virtual ~DefinitionMutable ()=default
Public Member Functions inherited from Definition
virtual ~Definition ()=default
Private Attributes
QCString m_fileName
std::unique_ptr< IncludeInfo > m_incInfo
NamespaceDef * m_nspace = nullptr
FileDef * m_fileDef = nullptr
ModuleDef * m_moduleDef = nullptr
ArgumentList m_tArgList
QCString m_initializer
int m_groupId = -1
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Protected Member Functions inherited from DefinitionMixin< ConceptDefMutable >
DefinitionMixin (const DefinitionMixin &def)=default
Detailed Description
Definition at line 31 of file conceptdef.cpp.
Constructor & Destructor Documentation
ConceptDefImpl()
ConceptDefImpl::ConceptDefImpl (const QCString & fileName, int startLine, int startColumn, const QCString & name, const QCString & tagRef = QCString(), const QCString & tagFile = QCString())
Definition at line 157 of file conceptdef.cpp.
                                                                         : DefinitionMixin(fileName,startLine,startColumn,name)
{
  if (!tagFile.isEmpty())
  {
    if (!tagRef.isEmpty())
    {
      m_fileName = stripExtension(tagFile);
    }
    else
    {
      m_fileName = convertNameToFile(stripExtension(tagFile));
    }
  }
  else
  {
    m_fileName = convertNameToFile(QCString("concept")+name);
  }
  setReference(tagRef);
}
References convertNameToFile(), QCString::isEmpty(), m_fileName, DefinitionMixin< ConceptDefMutable >::name(), DefinitionMixin< ConceptDefMutable >::setReference(), and stripExtension().
~ConceptDefImpl()
ConceptDefImpl::~ConceptDefImpl ()
Definition at line 178 of file conceptdef.cpp.
{
}
Member Function Documentation
addConceptAttributes()
void ConceptDefImpl::addConceptAttributes (OutputList & ol) const
Definition at line 501 of file conceptdef.cpp.
{
  if (isExported())
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputType::Html);
    ol.startLabels();
    ol.writeLabel("export",false);
    ol.endLabels();
    ol.popGeneratorState();
  }
}
References OutputList::disableAllBut(), OutputList::endLabels(), Html, DefinitionMixin< ConceptDefMutable >::isExported(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startLabels(), and OutputList::writeLabel().
Referenced by writeDocumentation().
anchor()
QCString ConceptDefImpl::anchor () const override virtual
Returns the anchor within a page where this item can be found
Implements ConceptDef.
Definition at line 201 of file conceptdef.cpp.
{
  return "";
}
Referenced by writeDeclarationLink().
codeSymbolType()
CodeSymbolType ConceptDefImpl::codeSymbolType () const inline override virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 42 of file conceptdef.cpp.
{ return CodeSymbolType::Concept; }
References Concept.
definitionType()
Definition::DefType ConceptDefImpl::definitionType () const override virtual
Use this for dynamic inspection of the type of the derived class
Implements ConceptDef.
Definition at line 182 of file conceptdef.cpp.
{
  return TypeConcept;
}
References Definition::TypeConcept.
displayName()
QCString ConceptDefImpl::displayName (bool includeScope = true) const override virtual
Returns the name of the definition as it appears in the output
Implements ConceptDef.
Definition at line 206 of file conceptdef.cpp.
{
  return includeScope ? name() : localName();
}
References DefinitionMixin< ConceptDefMutable >::localName(), and DefinitionMixin< ConceptDefMutable >::name().
Referenced by title(), writeDeclarationLink(), and writeDocumentation().
findSectionsInDocumentation()
void ConceptDefImpl::findSectionsInDocumentation () override virtual
Implements ConceptDefMutable.
Definition at line 684 of file conceptdef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::docFile(), docFindSections(), and DefinitionMixin< ConceptDefMutable >::documentation().
getFileDef()
const FileDef * ConceptDefImpl::getFileDef () const override virtual
Implements ConceptDef.
Definition at line 277 of file conceptdef.cpp.
{
  return m_fileDef;
}
References m_fileDef.
getModuleDef()
const ModuleDef * ConceptDefImpl::getModuleDef () const override virtual
Implements ConceptDef.
Definition at line 282 of file conceptdef.cpp.
{
  return m_moduleDef;
}
References m_moduleDef.
getNamespaceDef()
const NamespaceDef * ConceptDefImpl::getNamespaceDef () const override virtual
Implements ConceptDef.
Definition at line 262 of file conceptdef.cpp.
{
  return m_nspace;
}
References m_nspace.
getOutputFileBase()
QCString ConceptDefImpl::getOutputFileBase () const override virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements ConceptDef.
Definition at line 187 of file conceptdef.cpp.
{
  return m_fileName;
}
References m_fileName.
Referenced by writeBriefDescription(), writeDeclarationLink(), writeDocumentation(), and writeTagFile().
getTemplateParameterList()
ArgumentList ConceptDefImpl::getTemplateParameterList () const override virtual
Implements ConceptDef.
Definition at line 216 of file conceptdef.cpp.
{
  return m_tArgList;
}
References m_tArgList.
groupId()
int ConceptDefImpl::groupId () const override virtual
Implements ConceptDef.
Definition at line 292 of file conceptdef.cpp.
{
  return m_groupId;
}
References m_groupId.
hasDetailedDescription()
bool ConceptDefImpl::hasDetailedDescription () const override virtual
Implements ConceptDef.
Definition at line 192 of file conceptdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
  return ((!briefDescription().isEmpty() && repeatBrief) ||
          !documentation().isEmpty() ||
          (sourceBrowser && getStartBodyLine()!=-1 && getBodyDef()));
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), Config_getBool, DefinitionMixin< ConceptDefMutable >::documentation(), DefinitionMixin< ConceptDefMutable >::getBodyDef(), and DefinitionMixin< ConceptDefMutable >::getStartBodyLine().
Referenced by writeBriefDescription(), and writeDetailedDescription().
includeInfo()
const IncludeInfo * ConceptDefImpl::includeInfo () const override virtual
Implements ConceptDef.
Definition at line 211 of file conceptdef.cpp.
{
  return m_incInfo.get();
}
References m_incInfo.
initializer()
QCString ConceptDefImpl::initializer () const override virtual
Implements ConceptDef.
Definition at line 418 of file conceptdef.cpp.
{
  return m_initializer;
}
References m_initializer.
isLinkable()
bool ConceptDefImpl::isLinkable () const override virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements ConceptDef.
Definition at line 229 of file conceptdef.cpp.
{
  return isLinkableInProject() || isReference();
}
References isLinkableInProject(), and DefinitionMixin< ConceptDefMutable >::isReference().
Referenced by writeDeclarationLink().
isLinkableInProject()
bool ConceptDefImpl::isLinkableInProject () const override virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements ConceptDef.
Definition at line 221 of file conceptdef.cpp.
{
  bool hideUndoc = Config_getBool(HIDE_UNDOC_CLASSES);
  return (hasDocumentation() || !hideUndoc) && /* documented */
         !isHidden() &&                        /* not hidden */
         !isReference();                       /* not an external reference */
}
References Config_getBool, DefinitionMixin< ConceptDefMutable >::hasDocumentation(), DefinitionMixin< ConceptDefMutable >::isHidden(), and DefinitionMixin< ConceptDefMutable >::isReference().
Referenced by isLinkable().
resolveAlias()
ConceptDef * ConceptDefImpl::resolveAlias () inline
Definition at line 38 of file conceptdef.cpp.
{ return this; }
setFileDef()
void ConceptDefImpl::setFileDef (FileDef * fd) override virtual
Implements ConceptDefMutable.
Definition at line 267 of file conceptdef.cpp.
{
  m_fileDef=fd;
}
References m_fileDef.
setGroupId()
void ConceptDefImpl::setGroupId (int id) override virtual
Implements ConceptDefMutable.
Definition at line 297 of file conceptdef.cpp.
{
  m_groupId = id;
}
References DefinitionMixin< ConceptDefMutable >::id(), and m_groupId.
setIncludeFile()
void ConceptDefImpl::setIncludeFile (FileDef * fd, const QCString & incName, bool local, bool force) override virtual
Implements ConceptDefMutable.
Definition at line 234 of file conceptdef.cpp.
{
  if (!m_incInfo) m_incInfo = std::make_unique<IncludeInfo>();
  if ((!incName.isEmpty() && m_incInfo->includeName.isEmpty()) ||
      (fd!=nullptr && m_incInfo->fileDef==nullptr)
     )
  {
    m_incInfo->fileDef     = fd;
    m_incInfo->includeName = incName;
    m_incInfo->kind        = local ? IncludeKind::IncludeLocal : IncludeKind::IncludeSystem;
  }
  if (force && !incName.isEmpty())
  {
    m_incInfo->includeName = incName;
    m_incInfo->kind        = local ? IncludeKind::IncludeLocal : IncludeKind::IncludeSystem;
  }
}
References IncludeLocal, FileDef::includeName(), IncludeSystem, QCString::isEmpty(), and m_incInfo.
setInitializer()
void ConceptDefImpl::setInitializer (const QCString & init) override virtual
Implements ConceptDefMutable.
Definition at line 413 of file conceptdef.cpp.
{
  m_initializer = templateSpec(m_tArgList)+"\nconcept "+name()+" = "+init;
}
References m_initializer, m_tArgList, DefinitionMixin< ConceptDefMutable >::name(), and templateSpec().
setModuleDef()
void ConceptDefImpl::setModuleDef (ModuleDef * mod) override virtual
Implements ConceptDefMutable.
Definition at line 272 of file conceptdef.cpp.
{
  m_moduleDef=mod;
}
References m_moduleDef.
setNamespace()
void ConceptDefImpl::setNamespace (NamespaceDef * nd) override virtual
Implements ConceptDefMutable.
Definition at line 257 of file conceptdef.cpp.
{
  m_nspace = nd;
}
References m_nspace.
setTemplateArguments()
void ConceptDefImpl::setTemplateArguments (const ArgumentList & al) override virtual
Implements ConceptDefMutable.
Definition at line 252 of file conceptdef.cpp.
{
  m_tArgList = al;
}
References m_tArgList.
title()
QCString ConceptDefImpl::title () const override virtual
Implements ConceptDef.
Definition at line 287 of file conceptdef.cpp.
{
  return theTranslator->trConceptReference(displayName());
}
References displayName(), theTranslator, and Translator::trConceptReference().
Referenced by writeDefinition(), and writeDetailedDescription().
writeAuthorSection()
void ConceptDefImpl::writeAuthorSection (OutputList & ol) const
Definition at line 489 of file conceptdef.cpp.
{
  // write Author section (Man only)
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Man);
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), and TRUE.
Referenced by writeDocumentation().
writeBriefDescription()
void ConceptDefImpl::writeBriefDescription (OutputList & ol) const
Definition at line 318 of file conceptdef.cpp.
{
  if (hasBriefDescription())
  {
    auto parser { createDocParser() };
    auto ast    { validatingParseDoc(
                        *parser.get(),briefFile(),briefLine(),this,nullptr,
                        briefDescription(),TRUE,FALSE,
                        QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startParagraph();
      ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Man);
      ol.writeString(" - ");
      ol.popGeneratorState();
      ol.writeDoc(ast.get(),this,nullptr);
      ol.pushGeneratorState();
      ol.disable(OutputType::RTF);
      ol.writeString(" \n");
      ol.enable(OutputType::RTF);
      if (hasDetailedDescription())
      {
        ol.disableAllBut(OutputType::Html);
        ol.startTextLink(getOutputFileBase(),"details");
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
      }
      ol.popGeneratorState();
      ol.endParagraph();
    }
  }
  ol.writeSynopsis();
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::briefFile(), DefinitionMixin< ConceptDefMutable >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), FALSE, getOutputFileBase(), DefinitionMixin< ConceptDefMutable >::hasBriefDescription(), hasDetailedDescription(), Html, Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), RTF, OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeDeclarationLink()
void ConceptDefImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const override virtual
Implements ConceptDef.
Definition at line 626 of file conceptdef.cpp.
{
  if (isLinkable())
  {
    if (!found) // first concept
    {
      ol.startMemberHeader("concepts");
      if (!header.isEmpty())
      {
        ol.parseText(header);
      }
      else
      {
        theTranslator->trConcept(true,false);
      }
      ol.endMemberHeader();
      ol.startMemberList();
      found=TRUE;
    }
    ol.startMemberDeclaration();
    ol.startMemberItem(anchor(),OutputGenerator::MemberItemType::Normal);
    ol.writeString("concept ");
    QCString cname = displayName(!localNames);
    ol.insertMemberAlign();
    if (isLinkable())
    {
      ol.writeObjectLink(getReference(),
          getOutputFileBase(),
          anchor(),
          cname
          );
    }
    else
    {
      ol.startBold();
      ol.docify(cname);
      ol.endBold();
    }
    ol.endMemberItem(OutputGenerator::MemberItemType::Normal);
    // add the brief description if available
    if (!briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
    {
      auto parser { createDocParser() };
      auto ast    { validatingParseDoc(
                                *parser.get(),briefFile(),briefLine(),this,nullptr,
                                briefDescription(),FALSE,FALSE,
                                QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
      if (!ast->isEmpty())
      {
        ol.startMemberDescription(anchor());
        ol.writeDoc(ast.get(),this,nullptr);
        ol.endMemberDescription();
      }
    }
    ol.endMemberDeclaration(anchor(),QCString());
  }
}
References anchor(), DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::briefFile(), DefinitionMixin< ConceptDefMutable >::briefLine(), Config_getBool, createDocParser(), displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), FALSE, found, getOutputFileBase(), DefinitionMixin< ConceptDefMutable >::getReference(), OutputList::insertMemberAlign(), QCString::isEmpty(), isLinkable(), OutputGenerator::Normal, OutputList::parseText(), OutputList::startBold(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trConcept(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeObjectLink(), and OutputList::writeString().
writeDefinition()
void ConceptDefImpl::writeDefinition (OutputList & ol, const QCString & title) const
Definition at line 423 of file conceptdef.cpp.
{
    ol.startGroupHeader();
      ol.parseText(title);
    ol.endGroupHeader();
    auto intf = Doxygen::parserManager->getCodeParser(".cpp");
    intf->resetCodeParserState();
    auto &codeOL = ol.codeGenerators();
    codeOL.startCodeFragment("DoxyCode");
    QCString scopeName;
    if (getOuterScope()!=Doxygen::globalScope) scopeName=getOuterScope()->name();
    TextStream conceptDef;
    conceptDef << m_initializer;
    intf->parseCode(codeOL,scopeName,conceptDef.str(),SrcLangExt::Cpp,false,QCString(),
                    m_fileDef, -1,-1,true,nullptr,false,this);
    codeOL.endCodeFragment("DoxyCode");
}
References OutputList::codeGenerators(), Cpp, OutputList::endGroupHeader(), ParserManager::getCodeParser(), DefinitionMixin< ConceptDefMutable >::getOuterScope(), Doxygen::globalScope, m_fileDef, m_initializer, Definition::name(), Doxygen::parserManager, OutputList::parseText(), OutputCodeList::startCodeFragment(), OutputList::startGroupHeader(), TextStream::str(), and title().
Referenced by writeDocumentation().
writeDetailedDescription()
void ConceptDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) const
Definition at line 442 of file conceptdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  if (hasDetailedDescription())
  {
    ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Html);
      ol.writeAnchor(QCString(),"details");
    ol.popGeneratorState();
    ol.startGroupHeader();
      ol.parseText(title);
    ol.endGroupHeader();
    ol.startTextBlock();
    // repeat brief description
    if (!briefDescription().isEmpty() && repeatBrief)
    {
      ol.generateDoc(briefFile(),briefLine(),this,nullptr,briefDescription(),FALSE,FALSE,
          QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    if (!briefDescription().isEmpty() && repeatBrief &&
        !documentation().isEmpty())
    {
      ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.writeString("\n\n");
      ol.popGeneratorState();
    }
    // write documentation
    if (!documentation().isEmpty())
    {
      ol.generateDoc(docFile(),docLine(),this,nullptr,documentation(),TRUE,FALSE,
          QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    writeSourceDef(ol,name());
    ol.endTextBlock();
  }
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::briefFile(), DefinitionMixin< ConceptDefMutable >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< ConceptDefMutable >::docFile(), DefinitionMixin< ConceptDefMutable >::docLine(), DefinitionMixin< ConceptDefMutable >::documentation(), OutputList::endGroupHeader(), OutputList::endTextBlock(), FALSE, OutputList::generateDoc(), hasDetailedDescription(), Html, DefinitionMixin< ConceptDefMutable >::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), OutputList::startTextBlock(), title(), TRUE, OutputList::writeAnchor(), OutputList::writeRuler(), DefinitionMixin< ConceptDefMutable >::writeSourceDef(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDocumentation()
void ConceptDefImpl::writeDocumentation (OutputList & ol) override virtual
Implements ConceptDefMutable.
Definition at line 514 of file conceptdef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  QCString pageTitle = theTranslator->trConceptReference(displayName());
  startFile(ol,getOutputFileBase(),name(),pageTitle,HighlightedItem::ConceptVisible,!generateTreeView);
  // ---- navigation part
  if (!generateTreeView)
  {
    if (getOuterScope()!=Doxygen::globalScope)
    {
      writeNavigationPath(ol);
    }
    ol.endQuickIndices();
  }
  // ---- title part
  startTitle(ol,getOutputFileBase(),this);
  ol.parseText(pageTitle);
  addConceptAttributes(ol);
  addGroupListToTitle(ol,this);
  endTitle(ol,getOutputFileBase(),displayName());
  // ---- contents part
  ol.startContents();
  //---------------------------------------- start flexible part -------------------------------
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Concept))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol);
        break;
      case LayoutDocEntry::ConceptDefinition:
        if (ls) writeDefinition(ol,ls->title(getLanguage()));
        break;
      case LayoutDocEntry::DetailedDesc:
        if (ls) writeDetailedDescription(ol,ls->title(getLanguage()));
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::ClassIncludes:
        writeIncludeFiles(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
      case LayoutDocEntry::NamespaceClasses:
      case LayoutDocEntry::NamespaceInterfaces:
      case LayoutDocEntry::NamespaceStructs:
      case LayoutDocEntry::NamespaceExceptions:
      case LayoutDocEntry::NamespaceConcepts:
      case LayoutDocEntry::NamespaceNestedNamespaces:
      case LayoutDocEntry::NamespaceNestedConstantGroups:
      case LayoutDocEntry::MemberGroups:
      case LayoutDocEntry::MemberDecl:
      case LayoutDocEntry::MemberDeclEnd:
      case LayoutDocEntry::MemberDefStart:
      case LayoutDocEntry::NamespaceInlineClasses:
      case LayoutDocEntry::MemberDef:
      case LayoutDocEntry::MemberDefEnd:
      case LayoutDocEntry::ClassInheritanceGraph:
      case LayoutDocEntry::ClassNestedClasses:
      case LayoutDocEntry::ClassCollaborationGraph:
      case LayoutDocEntry::ClassAllMembersLink:
      case LayoutDocEntry::ClassUsedFiles:
      case LayoutDocEntry::ClassInlineClasses:
      case LayoutDocEntry::FileClasses:
      case LayoutDocEntry::FileConcepts:
      case LayoutDocEntry::FileInterfaces:
      case LayoutDocEntry::FileStructs:
      case LayoutDocEntry::FileExceptions:
      case LayoutDocEntry::FileNamespaces:
      case LayoutDocEntry::FileConstantGroups:
      case LayoutDocEntry::FileIncludes:
      case LayoutDocEntry::FileIncludeGraph:
      case LayoutDocEntry::FileIncludedByGraph:
      case LayoutDocEntry::FileInlineClasses:
      case LayoutDocEntry::FileSourceLink:
      case LayoutDocEntry::GroupClasses:
      case LayoutDocEntry::GroupConcepts:
      case LayoutDocEntry::GroupModules:
      case LayoutDocEntry::GroupInlineClasses:
      case LayoutDocEntry::GroupNamespaces:
      case LayoutDocEntry::GroupDirs:
      case LayoutDocEntry::GroupNestedGroups:
      case LayoutDocEntry::GroupFiles:
      case LayoutDocEntry::GroupGraph:
      case LayoutDocEntry::GroupPageDocs:
      case LayoutDocEntry::ModuleExports:
      case LayoutDocEntry::ModuleClasses:
      case LayoutDocEntry::ModuleConcepts:
      case LayoutDocEntry::ModuleUsedFiles:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::Concept entry list\n",lde->kind());
        break;
    }
  }
  //---------------------------------------- end flexible part -------------------------------
  ol.endContents();
  endFileWithNavPath(ol,this);
}
References addConceptAttributes(), addGroupListToTitle(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, LayoutDocManager::Concept, LayoutDocEntry::ConceptDefinition, ConceptVisible, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, displayName(), LayoutDocManager::docEntries(), OutputList::endContents(), endFileWithNavPath(), OutputList::endQuickIndices(), endTitle(), err, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::FileStructs, DefinitionMixin< ConceptDefMutable >::getLanguage(), DefinitionMixin< ConceptDefMutable >::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupModules, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, LayoutDocManager::instance(), LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, LayoutDocEntry::ModuleClasses, LayoutDocEntry::ModuleConcepts, LayoutDocEntry::ModuleExports, LayoutDocEntry::ModuleUsedFiles, DefinitionMixin< ConceptDefMutable >::name(), LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, LayoutDocEntry::NamespaceStructs, OutputList::parseText(), OutputList::startContents(), startFile(), startTitle(), theTranslator, LayoutDocEntrySection::title(), Translator::trConceptReference(), writeAuthorSection(), writeBriefDescription(), writeDefinition(), writeDetailedDescription(), writeIncludeFiles(), and DefinitionMixin< ConceptDefMutable >::writeNavigationPath().
writeIncludeFiles()
void ConceptDefImpl::writeIncludeFiles (OutputList & ol) const
Definition at line 354 of file conceptdef.cpp.
{
  if (m_incInfo)
  {
    QCString nm=m_incInfo->includeName.isEmpty() ?
      (m_incInfo->fileDef ?
       m_incInfo->fileDef->docName() : QCString()
      ) :
      m_incInfo->includeName;
    if (!nm.isEmpty())
    {
      ol.startParagraph();
      ol.startTypewriter();
      ol.docify(::includeStatement(SrcLangExt::Cpp,m_incInfo->kind));
      ol.docify(::includeOpen(SrcLangExt::Cpp,m_incInfo->kind));
      ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.docify(nm);
      ol.disableAllBut(OutputType::Html);
      ol.enable(OutputType::Html);
      if (m_incInfo->fileDef)
      {
        ol.writeObjectLink(QCString(),m_incInfo->fileDef->includeName(),QCString(),nm);
      }
      else
      {
        ol.docify(nm);
      }
      ol.popGeneratorState();
      ol.docify(::includeClose(SrcLangExt::Cpp,m_incInfo->kind));
      ol.endTypewriter();
      ol.endParagraph();
    }
  }
}
References Cpp, OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTypewriter(), Html, includeClose(), includeOpen(), includeStatement(), QCString::isEmpty(), m_incInfo, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startParagraph(), OutputList::startTypewriter(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeTagFile()
void ConceptDefImpl::writeTagFile (TextStream & tagFile) override virtual
Implements ConceptDefMutable.
Definition at line 302 of file conceptdef.cpp.
{
  tagFile << "  <compound kind=\"concept\">\n";
  tagFile << "    <name>" << convertToXML(name()) << "</name>\n";
  QCString fn = getOutputFileBase();
  addHtmlExtensionIfMissing(fn);
  tagFile << "    <filename>" << convertToXML(fn) << "</filename>\n";
  QCString idStr = id();
  if (!idStr.isEmpty())
  {
    tagFile << "    <clangid>" << convertToXML(idStr) << "</clangid>\n";
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << "  </compound>\n";
}
References addHtmlExtensionIfMissing(), convertToXML(), getOutputFileBase(), DefinitionMixin< ConceptDefMutable >::id(), QCString::isEmpty(), DefinitionMixin< ConceptDefMutable >::name(), and DefinitionMixin< ConceptDefMutable >::writeDocAnchorsToTagFile().
Member Data Documentation
m_fileDef
FileDef* ConceptDefImpl::m_fileDef = nullptr private
Definition at line 84 of file conceptdef.cpp.
Referenced by getFileDef(), setFileDef(), and writeDefinition().
m_fileName
QCString ConceptDefImpl::m_fileName private
Definition at line 81 of file conceptdef.cpp.
Referenced by ConceptDefImpl(), and getOutputFileBase().
m_groupId
int ConceptDefImpl::m_groupId = -1 private
Definition at line 88 of file conceptdef.cpp.
Referenced by groupId(), and setGroupId().
m_incInfo
std::unique_ptr<IncludeInfo> ConceptDefImpl::m_incInfo private
Definition at line 82 of file conceptdef.cpp.
Referenced by includeInfo(), setIncludeFile(), and writeIncludeFiles().
m_initializer
QCString ConceptDefImpl::m_initializer private
Definition at line 87 of file conceptdef.cpp.
Referenced by initializer(), setInitializer(), and writeDefinition().
m_moduleDef
ModuleDef* ConceptDefImpl::m_moduleDef = nullptr private
Definition at line 85 of file conceptdef.cpp.
Referenced by getModuleDef(), and setModuleDef().
m_nspace
NamespaceDef* ConceptDefImpl::m_nspace = nullptr private
Definition at line 83 of file conceptdef.cpp.
Referenced by getNamespaceDef(), and setNamespace().
m_tArgList
ArgumentList ConceptDefImpl::m_tArgList private
Definition at line 86 of file conceptdef.cpp.
Referenced by getTemplateParameterList(), setInitializer(), and setTemplateArguments().
The documentation for this class was generated from the following file:
src/conceptdef.cpp