Doxygen: ModuleContext Class Reference
ModuleContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
Gets the value for a field name.
virtual StringVector fields () const
Return the list of fields.
ModuleContext (const GroupDef *)
virtual ~ModuleContext ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()=default
Destroys the struct.
Static Public Member Functions
static TemplateStructIntfPtr alloc (const GroupDef *gd)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 338 of file context.h.
Constructor & Destructor Documentation
ModuleContext()
ModuleContext::ModuleContext (const GroupDef * gd)
Definition at line 5001 of file context.cpp.
                                               : p(std::make_unique<Private>(gd))
{
}
~ModuleContext()
ModuleContext::~ModuleContext () virtual
Definition at line 5005 of file context.cpp.
{
}
Member Function Documentation
alloc()
static TemplateStructIntfPtr ModuleContext::alloc (const GroupDef * gd) inline static
Definition at line 341 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<ModuleContext>(gd)); }
Referenced by ModuleListContext::Private::addModules(), NestingNodeContext::Private::createModule(), ModuleContext::Private::createModules(), and DefinitionContext< T >::createPartOfGroups().
fields()
StringVector ModuleContext::fields () const virtual
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 5014 of file context.cpp.
{
  return p->fields();
}
References p.
get()
TemplateVariant ModuleContext::get (const QCString & name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 5009 of file context.cpp.
{
  return p->get(n);
}
References p.
Member Data Documentation
p
std::unique_ptr<Private> ModuleContext::p private
Definition at line 353 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/context.h
/home/runner/work/doxygen/doxygen/src/context.cpp