Doxygen: /home/runner/work/doxygen/doxygen/src/markdown.h File Reference
markdown.h File Reference
#include <functional>
#include "qcstring.h"
#include "parserintf.h"
#include "growbuf.h"
Classes
class Markdown
Helper class to process markdown formatted text.
struct Markdown::LinkRef
class MarkdownOutlineParser
Functions
QCString markdownFileNameToId (const QCString &fileName)
processes string s and converts markdown into doxygen/html commands.
Function Documentation
markdownFileNameToId()
QCString markdownFileNameToId (const QCString & fileName)
processes string s and converts markdown into doxygen/html commands.
Definition at line 3336 of file markdown.cpp.
{
  AUTO_TRACE("fileName={}",fileName);
  std::string absFileName = FileInfo(fileName.str()).absFilePath();
  QCString baseFn  = stripFromPath(absFileName.c_str());
  int i = baseFn.findRev('.');
  if (i!=-1) baseFn = baseFn.left(i);
  QCString baseName = escapeCharsInString(baseFn,false,false);
  //printf("markdownFileNameToId(%s)=md_%s\n",qPrint(fileName),qPrint(baseName));
  QCString res = "md_"+baseName;
  AUTO_TRACE_EXIT("result={}",res);
  return res;
}
References FileInfo::absFilePath(), AUTO_TRACE, AUTO_TRACE_EXIT, escapeCharsInString(), QCString::findRev(), QCString::left(), QCString::str(), and stripFromPath().
Referenced by DocRef::DocRef(), DocSecRefItem::parse(), and MarkdownOutlineParser::parseInput().