Doxygen: Index Class Reference
Index Class Reference
#include <src/index.h>
Classes
struct Private
Public Types
using MemberIndexList = std::vector<const MemberDef *>
using MemberIndexMap = std::map<std::string,MemberIndexList>
Public Member Functions
void countDataStructures ()
void addClassMemberNameToIndex (const MemberDef *md)
void addFileMemberNameToIndex (const MemberDef *md)
void addNamespaceMemberNameToIndex (const MemberDef *md)
void addModuleMemberNameToIndex (const MemberDef *md)
void sortMemberIndexLists ()
int numAnnotatedClasses () const
int numAnnotatedClassesPrinted () const
int numHierarchyClasses () const
int numAnnotatedInterfaces () const
int numAnnotatedInterfacesPrinted () const
int numHierarchyInterfaces () const
int numAnnotatedStructs () const
int numAnnotatedStructsPrinted () const
int numAnnotatedExceptions () const
int numAnnotatedExceptionsPrinted () const
int numHierarchyExceptions () const
int numDocumentedGroups () const
int numDocumentedNamespaces () const
int numDocumentedConcepts () const
int numDocumentedModules () const
int numIndexedPages () const
int numDocumentedFiles () const
int numDocumentedPages () const
int numDocumentedDirs () const
int numDocumentedClassMembers (ClassMemberHighlight::Enum e) const
int numDocumentedFileMembers (FileMemberHighlight::Enum e) const
int numDocumentedNamespaceMembers (NamespaceMemberHighlight::Enum e) const
int numDocumentedModuleMembers (ModuleMemberHighlight::Enum e) const
MemberIndexMap isClassIndexLetterUsed (ClassMemberHighlight::Enum e) const
MemberIndexMap isFileIndexLetterUsed (FileMemberHighlight::Enum e) const
MemberIndexMap isNamespaceIndexLetterUsed (NamespaceMemberHighlight::Enum e) const
MemberIndexMap isModuleIndexLetterUsed (ModuleMemberHighlight::Enum e) const
Static Public Member Functions
static Index & instance ()
Private Member Functions
void resetDocumentedClassMembers (int i)
void resetDocumentedFileMembers (int i)
void resetDocumentedNamespaceMembers (int i)
void resetDocumentedModuleMembers (int i)
void incrementDocumentedClassMembers (int i, const std::string &letter, const MemberDef *md)
void incrementDocumentedFileMembers (int i, const std::string &letter, const MemberDef *md)
void incrementDocumentedNamespaceMembers (int i, const std::string &letter, const MemberDef *md)
void incrementDocumentedModuleMembers (int i, const std::string &letter, const MemberDef *md)
Index ()
~Index ()
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 164 of file index.h.
Member Typedef Documentation
MemberIndexList
using Index::MemberIndexList = std::vector<const MemberDef *>
Definition at line 167 of file index.h.
MemberIndexMap
using Index::MemberIndexMap = std::map<std::string,MemberIndexList>
Definition at line 168 of file index.h.
Constructor & Destructor Documentation
Index()
Index::Index () private
Definition at line 100 of file index.cpp.
             : p(std::make_unique<Private>())
{
}
References p.
Referenced by instance(), and ~Index().
~Index()
Index::~Index () private default
References Index().
Member Function Documentation
addClassMemberNameToIndex()
void Index::addClassMemberNameToIndex (const MemberDef * md)
Definition at line 2836 of file index.cpp.
{
  bool hideFriendCompounds = Config_getBool(HIDE_FRIEND_COMPOUNDS);
  const ClassDef *cd=nullptr;
  if (md->isLinkableInProject() &&
      (cd=md->getClassDef())    &&
      cd->isLinkableInProject() &&
      !cd->isImplicitTemplateInstance())
  {
    QCString n = md->name();
    std::string letter = getUTF8CharAt(n.str(),getPrefixIndex(n));
    if (!letter.empty())
    {
      letter = convertUTF8ToLower(letter);
      bool isFriendToHide = hideFriendCompounds &&
        (QCString(md->typeString())=="friend class" ||
         QCString(md->typeString())=="friend struct" ||
         QCString(md->typeString())=="friend union");
      if (!(md->isFriend() && isFriendToHide) &&
          (!md->isEnumValue() || (md->getEnumScope() && !md->getEnumScope()->isStrong()))
         )
      {
        incrementDocumentedClassMembers(ClassMemberHighlight::All,letter,md);
      }
      if (md->isFunction()  || md->isSlot() || md->isSignal())
      {
        incrementDocumentedClassMembers(ClassMemberHighlight::Functions,letter,md);
      }
      else if (md->isVariable())
      {
        incrementDocumentedClassMembers(ClassMemberHighlight::Variables,letter,md);
      }
      else if (md->isTypedef())
      {
        incrementDocumentedClassMembers(ClassMemberHighlight::Typedefs,letter,md);
      }
      else if (md->isEnumerate())
      {
        incrementDocumentedClassMembers(ClassMemberHighlight::Enums,letter,md);
      }
      else if (md->isEnumValue() && md->getEnumScope() && !md->getEnumScope()->isStrong())
      {
        incrementDocumentedClassMembers(ClassMemberHighlight::EnumValues,letter,md);
      }
      else if (md->isProperty())
      {
        incrementDocumentedClassMembers(ClassMemberHighlight::Properties,letter,md);
      }
      else if (md->isEvent())
      {
        incrementDocumentedClassMembers(ClassMemberHighlight::Events,letter,md);
      }
      else if (md->isRelated() || md->isForeign() ||
               (md->isFriend() && !isFriendToHide))
      {
        incrementDocumentedClassMembers(ClassMemberHighlight::Related,letter,md);
      }
    }
  }
}
References ClassMemberHighlight::All, Config_getBool, convertUTF8ToLower(), ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, MemberDef::getClassDef(), MemberDef::getEnumScope(), getPrefixIndex(), getUTF8CharAt(), incrementDocumentedClassMembers(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isEvent(), MemberDef::isForeign(), MemberDef::isFriend(), MemberDef::isFunction(), ClassDef::isImplicitTemplateInstance(), Definition::isLinkableInProject(), MemberDef::isProperty(), MemberDef::isRelated(), MemberDef::isSignal(), MemberDef::isSlot(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), Definition::name(), ClassMemberHighlight::Properties, ClassMemberHighlight::Related, QCString::str(), ClassMemberHighlight::Typedefs, MemberDef::typeString(), and ClassMemberHighlight::Variables.
addFileMemberNameToIndex()
void Index::addFileMemberNameToIndex (const MemberDef * md)
Definition at line 2948 of file index.cpp.
{
  const FileDef *fd=md->getFileDef();
  if (fd && fd->isLinkableInProject() && md->isLinkableInProject())
  {
    QCString n = md->name();
    std::string letter = getUTF8CharAt(n.str(),getPrefixIndex(n));
    if (!letter.empty())
    {
      letter = convertUTF8ToLower(letter);
      if (!md->isEnumValue() || (md->getEnumScope() && !md->getEnumScope()->isStrong()))
      {
        incrementDocumentedFileMembers(FileMemberHighlight::All,letter,md);
      }
      if (md->isFunction())
      {
        incrementDocumentedFileMembers(FileMemberHighlight::Functions,letter,md);
      }
      else if (md->isVariable())
      {
        incrementDocumentedFileMembers(FileMemberHighlight::Variables,letter,md);
      }
      else if (md->isTypedef())
      {
        incrementDocumentedFileMembers(FileMemberHighlight::Typedefs,letter,md);
      }
      else if (md->isSequence())
      {
        incrementDocumentedFileMembers(FileMemberHighlight::Sequences,letter,md);
      }
      else if (md->isDictionary())
      {
        incrementDocumentedFileMembers(FileMemberHighlight::Dictionaries,letter,md);
      }
      else if (md->isEnumerate())
      {
        incrementDocumentedFileMembers(FileMemberHighlight::Enums,letter,md);
      }
      else if (md->isEnumValue() && md->getEnumScope() && !md->getEnumScope()->isStrong())
      {
        incrementDocumentedFileMembers(FileMemberHighlight::EnumValues,letter,md);
      }
      else if (md->isDefine())
      {
        incrementDocumentedFileMembers(FileMemberHighlight::Defines,letter,md);
      }
    }
  }
}
References FileMemberHighlight::All, convertUTF8ToLower(), FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, MemberDef::getEnumScope(), MemberDef::getFileDef(), getPrefixIndex(), getUTF8CharAt(), incrementDocumentedFileMembers(), MemberDef::isDefine(), MemberDef::isDictionary(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFunction(), Definition::isLinkableInProject(), MemberDef::isSequence(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), Definition::name(), FileMemberHighlight::Sequences, QCString::str(), FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
addModuleMemberNameToIndex()
void Index::addModuleMemberNameToIndex (const MemberDef * md)
Definition at line 3000 of file index.cpp.
{
  const ModuleDef *mod = md->getModuleDef();
  if (mod && mod->isPrimaryInterface() && mod->isLinkableInProject() && md->isLinkableInProject())
  {
    QCString n = md->name();
    std::string letter = getUTF8CharAt(n.str(),getPrefixIndex(n));
    if (!letter.empty())
    {
      letter = convertUTF8ToLower(letter);
      if (!md->isEnumValue() || (md->getEnumScope() && !md->getEnumScope()->isStrong()))
      {
        incrementDocumentedModuleMembers(ModuleMemberHighlight::All,letter,md);
      }
      if (md->isFunction())
      {
        incrementDocumentedModuleMembers(ModuleMemberHighlight::Functions,letter,md);
      }
      else if (md->isVariable())
      {
        incrementDocumentedModuleMembers(ModuleMemberHighlight::Variables,letter,md);
      }
      else if (md->isTypedef())
      {
        incrementDocumentedModuleMembers(ModuleMemberHighlight::Typedefs,letter,md);
      }
      else if (md->isEnumerate())
      {
        incrementDocumentedModuleMembers(ModuleMemberHighlight::Enums,letter,md);
      }
      else if (md->isEnumValue() && md->getEnumScope() && !md->getEnumScope()->isStrong())
      {
        incrementDocumentedModuleMembers(ModuleMemberHighlight::EnumValues,letter,md);
      }
    }
  }
}
References ModuleMemberHighlight::All, convertUTF8ToLower(), ModuleMemberHighlight::Enums, ModuleMemberHighlight::EnumValues, ModuleMemberHighlight::Functions, MemberDef::getEnumScope(), MemberDef::getModuleDef(), getPrefixIndex(), getUTF8CharAt(), incrementDocumentedModuleMembers(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFunction(), Definition::isLinkableInProject(), ModuleDef::isPrimaryInterface(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), Definition::name(), QCString::str(), ModuleMemberHighlight::Typedefs, and ModuleMemberHighlight::Variables.
addNamespaceMemberNameToIndex()
void Index::addNamespaceMemberNameToIndex (const MemberDef * md)
Definition at line 2900 of file index.cpp.
{
  const NamespaceDef *nd=md->getNamespaceDef();
  if (nd && nd->isLinkableInProject() && md->isLinkableInProject())
  {
    QCString n = md->name();
    std::string letter = getUTF8CharAt(n.str(),getPrefixIndex(n));
    if (!letter.empty())
    {
      letter = convertUTF8ToLower(letter);
      if (!md->isEnumValue() || (md->getEnumScope() && !md->getEnumScope()->isStrong()))
      {
        incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::All,letter,md);
      }
      if (md->isFunction())
      {
        incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Functions,letter,md);
      }
      else if (md->isVariable())
      {
        incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Variables,letter,md);
      }
      else if (md->isTypedef())
      {
        incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Typedefs,letter,md);
      }
      else if (md->isSequence())
      {
        incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Sequences,letter,md);
      }
      else if (md->isDictionary())
      {
        incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Dictionaries,letter,md);
      }
      else if (md->isEnumerate())
      {
        incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::Enums,letter,md);
      }
      else if (md->isEnumValue() && md->getEnumScope() && !md->getEnumScope()->isStrong())
      {
        incrementDocumentedNamespaceMembers(NamespaceMemberHighlight::EnumValues,letter,md);
      }
    }
  }
}
References NamespaceMemberHighlight::All, convertUTF8ToLower(), NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, MemberDef::getEnumScope(), MemberDef::getNamespaceDef(), getPrefixIndex(), getUTF8CharAt(), incrementDocumentedNamespaceMembers(), MemberDef::isDictionary(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFunction(), Definition::isLinkableInProject(), MemberDef::isSequence(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), Definition::name(), NamespaceMemberHighlight::Sequences, QCString::str(), NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
countDataStructures()
void Index::countDataStructures ()
Definition at line 262 of file index.cpp.
{
  for (int j=0;j<ClassMemberHighlight::Total;j++)
  {
    resetDocumentedClassMembers(j);
  }
  for (int j=0;j<NamespaceMemberHighlight::Total;j++)
  {
    resetDocumentedNamespaceMembers(j);
  }
  for (int j=0;j<FileMemberHighlight::Total;j++)
  {
    resetDocumentedFileMembers(j);
  }
  for (int j=0;j<ModuleMemberHighlight::Total;j++)
  {
    resetDocumentedModuleMembers(j);
  }
  bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
  p->annotatedClasses           = countAnnotatedClasses(&p->annotatedClassesPrinted, ClassDef::Class); // "classes" + "annotated"
  p->hierarchyClasses           = countClassHierarchy(ClassDef::Class);     // "hierarchy"
  // "interfaces" + "annotated"
  p->annotatedInterfaces        = sliceOpt ? countAnnotatedClasses(&p->annotatedInterfacesPrinted, ClassDef::Interface) : 0;
  // "interfacehierarchy"
  p->hierarchyInterfaces        = sliceOpt ? countClassHierarchy(ClassDef::Interface) : 0;
  // "structs" + "annotated"
  p->annotatedStructs           = sliceOpt ? countAnnotatedClasses(&p->annotatedStructsPrinted, ClassDef::Struct) : 0;
  // "exceptions" + "annotated"
  p->annotatedExceptions        = sliceOpt ? countAnnotatedClasses(&p->annotatedExceptionsPrinted, ClassDef::Exception) : 0;
  // "exceptionhierarchy"
  p->hierarchyExceptions        = sliceOpt ? countClassHierarchy(ClassDef::Exception) : 0;
  countFiles(p->documentedFiles,p->documentedFiles);         // "files"
  countRelatedPages(p->documentedPages,p->indexedPages);     // "pages"
  p->documentedGroups           = countGroups();             // "topics"
  p->documentedNamespaces       = countNamespaces();         // "namespaces"
  p->documentedConcepts         = countConcepts();           // "concepts"
  p->documentedDirs             = countDirs();               // "dirs"
  p->documentedModules          = ModuleManager::instance().numDocumentedModules();
  // "globals"
  // "namespacemembers"
  // "functions"
}
References ClassDef::Class, Config_getBool, countAnnotatedClasses(), countClassHierarchy(), countConcepts(), countDirs(), countFiles(), countGroups(), countNamespaces(), countRelatedPages(), ClassDef::Exception, ModuleManager::instance(), ClassDef::Interface, ModuleManager::numDocumentedModules(), p, resetDocumentedClassMembers(), resetDocumentedFileMembers(), resetDocumentedModuleMembers(), resetDocumentedNamespaceMembers(), ClassDef::Struct, ClassMemberHighlight::Total, FileMemberHighlight::Total, ModuleMemberHighlight::Total, and NamespaceMemberHighlight::Total.
Referenced by parseInput().
incrementDocumentedClassMembers()
void Index::incrementDocumentedClassMembers (int i, const std::string & letter, const MemberDef * md) private
Definition at line 193 of file index.cpp.
{
  p->documentedClassMembers[i]++;
  MemberIndexMap_add(p->classIndexLetterUsed[i],letter,md);
}
References MemberIndexMap_add(), and p.
Referenced by addClassMemberNameToIndex().
incrementDocumentedFileMembers()
void Index::incrementDocumentedFileMembers (int i, const std::string & letter, const MemberDef * md) private
Definition at line 199 of file index.cpp.
{
  p->documentedFileMembers[i]++;
  MemberIndexMap_add(p->fileIndexLetterUsed[i],letter,md);
}
References MemberIndexMap_add(), and p.
Referenced by addFileMemberNameToIndex().
incrementDocumentedModuleMembers()
void Index::incrementDocumentedModuleMembers (int i, const std::string & letter, const MemberDef * md) private
Definition at line 211 of file index.cpp.
{
  p->documentedModuleMembers[i]++;
  MemberIndexMap_add(p->moduleIndexLetterUsed[i],letter,md);
}
References MemberIndexMap_add(), and p.
Referenced by addModuleMemberNameToIndex().
incrementDocumentedNamespaceMembers()
void Index::incrementDocumentedNamespaceMembers (int i, const std::string & letter, const MemberDef * md) private
Definition at line 205 of file index.cpp.
{
  p->documentedNamespaceMembers[i]++;
  MemberIndexMap_add(p->namespaceIndexLetterUsed[i],letter,md);
}
References MemberIndexMap_add(), and p.
Referenced by addNamespaceMemberNameToIndex().
instance()
Index & Index::instance () static
Definition at line 106 of file index.cpp.
{
  static Index index;
  return index;
}
References Index().
Referenced by addMembersToIndex(), generateFileDocs(), generatePageDocs(), parseInput(), quickLinkVisible(), quickLinkVisible(), renderQuickLinksAsJs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedExceptionIndex(), writeAnnotatedIndex(), writeAnnotatedInterfaceIndex(), writeAnnotatedStructIndex(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeConceptIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), writeIndexHierarchyEntries(), writeModuleMemberIndex(), writeModuleMemberIndexFiltered(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), and writeTopicIndex().
isClassIndexLetterUsed()
Index::MemberIndexMap Index::isClassIndexLetterUsed (ClassMemberHighlight::Enum e) const
Definition at line 136 of file index.cpp.
{
  return p->classIndexLetterUsed[static_cast<int>(e)];
}
References p.
Referenced by renderQuickLinksAsJs().
isFileIndexLetterUsed()
Index::MemberIndexMap Index::isFileIndexLetterUsed (FileMemberHighlight::Enum e) const
Definition at line 141 of file index.cpp.
{
  return p->fileIndexLetterUsed[static_cast<int>(e)];
}
References p.
Referenced by renderQuickLinksAsJs().
isModuleIndexLetterUsed()
Index::MemberIndexMap Index::isModuleIndexLetterUsed (ModuleMemberHighlight::Enum e) const
Definition at line 151 of file index.cpp.
{
  return p->moduleIndexLetterUsed[static_cast<int>(e)];
}
References p.
Referenced by renderQuickLinksAsJs().
isNamespaceIndexLetterUsed()
Index::MemberIndexMap Index::isNamespaceIndexLetterUsed (NamespaceMemberHighlight::Enum e) const
Definition at line 146 of file index.cpp.
{
  return p->namespaceIndexLetterUsed[static_cast<int>(e)];
}
References p.
Referenced by renderQuickLinksAsJs().
numAnnotatedClasses()
int Index::numAnnotatedClasses () const
Definition at line 112 of file index.cpp.
{ return p->annotatedClasses;        }
References p.
numAnnotatedClassesPrinted()
int Index::numAnnotatedClassesPrinted () const
Definition at line 113 of file index.cpp.
{ return p->annotatedClassesPrinted; }
References p.
numAnnotatedExceptions()
int Index::numAnnotatedExceptions () const
Definition at line 120 of file index.cpp.
{ return p->annotatedExceptions; }
References p.
numAnnotatedExceptionsPrinted()
int Index::numAnnotatedExceptionsPrinted () const
Definition at line 121 of file index.cpp.
{ return p->annotatedExceptionsPrinted; }
References p.
numAnnotatedInterfaces()
int Index::numAnnotatedInterfaces () const
Definition at line 115 of file index.cpp.
{ return p->annotatedInterfaces; }
References p.
numAnnotatedInterfacesPrinted()
int Index::numAnnotatedInterfacesPrinted () const
Definition at line 116 of file index.cpp.
{ return p->annotatedInterfacesPrinted; }
References p.
numAnnotatedStructs()
int Index::numAnnotatedStructs () const
Definition at line 118 of file index.cpp.
{ return p->annotatedStructs; }
References p.
numAnnotatedStructsPrinted()
int Index::numAnnotatedStructsPrinted () const
Definition at line 119 of file index.cpp.
{ return p->annotatedStructsPrinted; }
References p.
numDocumentedClassMembers()
int Index::numDocumentedClassMembers (ClassMemberHighlight::Enum e) const
Definition at line 131 of file index.cpp.
{ return p->documentedClassMembers[e]; }
References p.
Referenced by renderQuickLinksAsJs().
numDocumentedConcepts()
int Index::numDocumentedConcepts () const
Definition at line 125 of file index.cpp.
{ return p->documentedConcepts; }
References p.
numDocumentedDirs()
int Index::numDocumentedDirs () const
Definition at line 130 of file index.cpp.
{ return p->documentedDirs; }
References p.
numDocumentedFileMembers()
int Index::numDocumentedFileMembers (FileMemberHighlight::Enum e) const
Definition at line 132 of file index.cpp.
{ return p->documentedFileMembers[e];  }
References p.
Referenced by renderQuickLinksAsJs().
numDocumentedFiles()
int Index::numDocumentedFiles () const
Definition at line 128 of file index.cpp.
{ return p->documentedFiles; }
References p.
numDocumentedGroups()
int Index::numDocumentedGroups () const
Definition at line 123 of file index.cpp.
{ return p->documentedGroups; }
References p.
numDocumentedModuleMembers()
int Index::numDocumentedModuleMembers (ModuleMemberHighlight::Enum e) const
Definition at line 134 of file index.cpp.
{ return p->documentedModuleMembers[e]; }
References p.
Referenced by renderQuickLinksAsJs().
numDocumentedModules()
int Index::numDocumentedModules () const
Definition at line 126 of file index.cpp.
{ return p->documentedModules; }
References p.
numDocumentedNamespaceMembers()
int Index::numDocumentedNamespaceMembers (NamespaceMemberHighlight::Enum e) const
Definition at line 133 of file index.cpp.
{ return p->documentedNamespaceMembers[e]; }
References p.
Referenced by renderQuickLinksAsJs().
numDocumentedNamespaces()
int Index::numDocumentedNamespaces () const
Definition at line 124 of file index.cpp.
{ return p->documentedNamespaces; }
References p.
numDocumentedPages()
int Index::numDocumentedPages () const
Definition at line 129 of file index.cpp.
{ return p->documentedPages; }
References p.
numHierarchyClasses()
int Index::numHierarchyClasses () const
Definition at line 114 of file index.cpp.
{ return p->hierarchyClasses;        }
References p.
numHierarchyExceptions()
int Index::numHierarchyExceptions () const
Definition at line 122 of file index.cpp.
{ return p->hierarchyExceptions; }
References p.
numHierarchyInterfaces()
int Index::numHierarchyInterfaces () const
Definition at line 117 of file index.cpp.
{ return p->hierarchyInterfaces; }
References p.
numIndexedPages()
int Index::numIndexedPages () const
Definition at line 127 of file index.cpp.
{ return p->indexedPages; }
References p.
resetDocumentedClassMembers()
void Index::resetDocumentedClassMembers (int i) private
Definition at line 156 of file index.cpp.
{
  p->documentedClassMembers[i]=0;
  p->classIndexLetterUsed[i].clear();
}
References p.
Referenced by countDataStructures().
resetDocumentedFileMembers()
void Index::resetDocumentedFileMembers (int i) private
Definition at line 162 of file index.cpp.
{
  p->documentedFileMembers[i]=0;
  p->fileIndexLetterUsed[i].clear();
}
References p.
Referenced by countDataStructures().
resetDocumentedModuleMembers()
void Index::resetDocumentedModuleMembers (int i) private
Definition at line 174 of file index.cpp.
{
  p->documentedModuleMembers[i]=0;
  p->moduleIndexLetterUsed[i].clear();
}
References p.
Referenced by countDataStructures().
resetDocumentedNamespaceMembers()
void Index::resetDocumentedNamespaceMembers (int i) private
Definition at line 168 of file index.cpp.
{
  p->documentedNamespaceMembers[i]=0;
  p->namespaceIndexLetterUsed[i].clear();
}
References p.
Referenced by countDataStructures().
sortMemberIndexLists()
void Index::sortMemberIndexLists ()
Definition at line 218 of file index.cpp.
{
  auto sortMemberIndexList = [](MemberIndexMap &map)
  {
    for (auto &[name,list] : map)
    {
      std::stable_sort(list.begin(),list.end(),
          [](const MemberDef *md1,const MemberDef *md2)
          {
            // consider candidates A::a, B::b, B::a, A::b, A::A, B::B,
            // want after sorting: A::A, A::a, B::a, B::B, A::b, B::b
            // so we can later group entries
            // - A: A
            // - a: A, B
            // - B: B
            // - b: A, B
            int result = qstricmp_sort(md1->name(),md2->name());
            if (result==0) // next compare with full scope
            {
              result = qstricmp_sort(md1->qualifiedName(),md2->qualifiedName());
            }
            return result<0;
          });
    }
  };
  for (auto &idx : p->classIndexLetterUsed)
  {
    sortMemberIndexList(idx);
  }
  for (auto &idx : p->fileIndexLetterUsed)
  {
    sortMemberIndexList(idx);
  }
  for (auto &idx : p->namespaceIndexLetterUsed)
  {
    sortMemberIndexList(idx);
  }
  for (auto &idx : p->moduleIndexLetterUsed)
  {
    sortMemberIndexList(idx);
  }
}
Member Data Documentation
p
std::unique_ptr<Private> Index::p private
Definition at line 221 of file index.h.
Referenced by countDataStructures(), incrementDocumentedClassMembers(), incrementDocumentedFileMembers(), incrementDocumentedModuleMembers(), incrementDocumentedNamespaceMembers(), Index(), isClassIndexLetterUsed(), isFileIndexLetterUsed(), isModuleIndexLetterUsed(), isNamespaceIndexLetterUsed(), numAnnotatedClasses(), numAnnotatedClassesPrinted(), numAnnotatedExceptions(), numAnnotatedExceptionsPrinted(), numAnnotatedInterfaces(), numAnnotatedInterfacesPrinted(), numAnnotatedStructs(), numAnnotatedStructsPrinted(), numDocumentedClassMembers(), numDocumentedConcepts(), numDocumentedDirs(), numDocumentedFileMembers(), numDocumentedFiles(), numDocumentedGroups(), numDocumentedModuleMembers(), numDocumentedModules(), numDocumentedNamespaceMembers(), numDocumentedNamespaces(), numDocumentedPages(), numHierarchyClasses(), numHierarchyExceptions(), numHierarchyInterfaces(), numIndexedPages(), resetDocumentedClassMembers(), resetDocumentedFileMembers(), resetDocumentedModuleMembers(), and resetDocumentedNamespaceMembers().
The documentation for this class was generated from the following files:
src/index.h
src/index.cpp