Doxygen: src/layout.cpp File Reference
layout.cpp File Reference
#include <array>
#include <assert.h>
#include "types.h"
#include "layout.h"
#include "message.h"
#include "language.h"
#include "util.h"
#include "doxygen.h"
#include "version.h"
#include "config.h"
#include "xml.h"
#include "resourcemgr.h"
#include "docparser.h"
#include "docnode.h"
#include "debug.h"
Classes
class LayoutParser
struct anonymous_namespace{layout.cpp}::ElementCallbacks
class LayoutDocManager::Private
Namespaces
namespace anonymous_namespace{layout.cpp}
Functions
QCString compileOptions (const QCString &def)
QCString compileOptions (const QCString &def, SrcLangExt langId1, const QCString &value1)
QCString compileOptions (const QCString &def, SrcLangExt langId1, const QCString &value1, SrcLangExt langId2, const QCString &value2)
QCString compileOptions (const QCString &def, SrcLangExt langId1, const QCString &value1, SrcLangExt langId2, const QCString &value2, SrcLangExt langId3, const QCString &value3)
QCString compileOptions (const QCString &def, SrcLangExt langId1, const QCString &value1, SrcLangExt langId2, const QCString &value2, SrcLangExt langId3, const QCString &value3, SrcLangExt langId4, const QCString &value4)
QCString compileOptions (const QCString &def, SrcLangExt langId1, const QCString &value1, SrcLangExt langId2, const QCString &value2, SrcLangExt langId3, const QCString &value3, SrcLangExt langId4, const QCString &value4, SrcLangExt langId5, const QCString &value5)
static bool elemIsVisible (const XMLHandlers::Attributes &attrib, bool defVal=TRUE)
static bool parentIsVisible (LayoutNavEntry *parent)
template<class... Args>
static auto anonymous_namespace{layout.cpp}::startCb (void(LayoutParser::*fn)(Args...))
template<class... Args>
static auto anonymous_namespace{layout.cpp}::startCb (void(LayoutParser::*fn)(Args...), LayoutDocEntry::Kind kind)
template<class... Args>
static auto anonymous_namespace{layout.cpp}::startCb (void(LayoutParser::*fn)(Args...), LayoutDocEntry::Kind kind, const std::function< QCString()> &title)
template<class... Args>
static auto anonymous_namespace{layout.cpp}::startCb (void(LayoutParser::*fn)(Args...), MemberListType type, const std::function< QCString()> &title)
template<class... Args>
static auto anonymous_namespace{layout.cpp}::startCb (void(LayoutParser::*fn)(Args...), MemberListType type, const std::function< QCString()> &title, const std::function< QCString()> &subtitle)
template<class... Args>
static auto anonymous_namespace{layout.cpp}::startCb (void(LayoutParser::*fn)(Args...), LayoutDocManager::LayoutPart part, const QCString &scope, LayoutNavEntry::Kind nav)
static auto anonymous_namespace{layout.cpp}::endCb (void(LayoutParser::*fn)())
void writeDefaultLayoutFile (const QCString &fileName)
QCString extractLanguageSpecificTitle (const QCString &input, SrcLangExt lang)
Variables
static const std::map< std::string, ElementCallbacks > anonymous_namespace{layout.cpp}::g_elementHandlers
Function Documentation
compileOptions() [1/6]
QCString compileOptions (const QCString & def) inline
Definition at line 37 of file layout.cpp.
{
  return def;
}
Referenced by compileOptions(), compileOptions(), compileOptions(), compileOptions(), and compileOptions().
compileOptions() [2/6]
QCString compileOptions (const QCString & def, SrcLangExt langId1, const QCString & value1) inline
Definition at line 42 of file layout.cpp.
{
  return compileOptions(def)+"|"+QCString().setNum(static_cast<long>(langId1))+"="+value1;
}
References compileOptions(), and QCString::setNum().
compileOptions() [3/6]
QCString compileOptions (const QCString & def, SrcLangExt langId1, const QCString & value1, SrcLangExt langId2, const QCString & value2) inline
Definition at line 47 of file layout.cpp.
{
  return compileOptions(def,langId1,value1)+
         "|"+QCString().setNum(static_cast<long>(langId2))+"="+value2;
}
References compileOptions(), and QCString::setNum().
compileOptions() [4/6]
QCString compileOptions (const QCString & def, SrcLangExt langId1, const QCString & value1, SrcLangExt langId2, const QCString & value2, SrcLangExt langId3, const QCString & value3) inline
Definition at line 54 of file layout.cpp.
{
  return compileOptions(def,langId1,value1,langId2,value2)+
         "|"+QCString().setNum(static_cast<long>(langId3))+"="+value3;
}
References compileOptions(), and QCString::setNum().
compileOptions() [5/6]
QCString compileOptions (const QCString & def, SrcLangExt langId1, const QCString & value1, SrcLangExt langId2, const QCString & value2, SrcLangExt langId3, const QCString & value3, SrcLangExt langId4, const QCString & value4) inline
Definition at line 62 of file layout.cpp.
{
  return compileOptions(def,langId1,value1,langId2,value2,langId3,value3)+
         "|"+QCString().setNum(static_cast<long>(langId4))+"="+value4;
}
References compileOptions(), and QCString::setNum().
compileOptions() [6/6]
QCString compileOptions (const QCString & def, SrcLangExt langId1, const QCString & value1, SrcLangExt langId2, const QCString & value2, SrcLangExt langId3, const QCString & value3, SrcLangExt langId4, const QCString & value4, SrcLangExt langId5, const QCString & value5) inline
Definition at line 71 of file layout.cpp.
{
  return compileOptions(def,langId1,value1,langId2,value2,langId3,value3,langId4,value4)+
         "|"+QCString().setNum(static_cast<long>(langId5))+"="+value5;
}
References compileOptions(), and QCString::setNum().
elemIsVisible()
static bool elemIsVisible (const XMLHandlers::Attributes & attrib, bool defVal = TRUE) static
Definition at line 81 of file layout.cpp.
{
  QCString visible = XMLHandlers::value(attrib,"visible");
  if (visible.isEmpty()) return defVal;
  if (visible.at(0)=='$' && visible.length()>1)
  {
    QCString id = visible.mid(1);
    const ConfigValues::Info *opt = ConfigValues::instance().get(id);
    if (opt && opt->type==ConfigValues::Info::Bool)
    {
      return ConfigValues::instance().*(opt->value.b);
    }
    else if (opt && opt->type==ConfigValues::Info::String)
    {
      return opt->getBooleanRepresentation();
    }
    else if (!opt)
    {
      err("found unsupported value '%s' for visible attribute in layout file, reverting to '%s'\n",
          qPrint(visible),(defVal?"yes":"no"));
      return defVal;
    }
  }
  QCString visibleLow = visible.lower();
  if (visibleLow=="no" || visibleLow=="false" || visibleLow=="0") return FALSE;
  else if (visibleLow=="yes" || visibleLow=="true" || visibleLow=="1") return TRUE;
  else
  {
    err("found unsupported value '%s' for visible attribute in layout file, reverting to '%s'\n",
        qPrint(visible),(defVal?"yes":"no"));
    return defVal;
  }
}
References QCString::at(), err, FALSE, QCString::isEmpty(), QCString::length(), QCString::lower(), QCString::mid(), qPrint(), TRUE, and XMLHandlers::value().
Referenced by LayoutParser::startMemberDecl(), LayoutParser::startMemberDeclEntry(), LayoutParser::startMemberDef(), LayoutParser::startMemberDefEntry(), LayoutParser::startNavEntry(), LayoutParser::startSectionEntry(), LayoutParser::startSimpleEntry(), and LayoutParser::startTop().
extractLanguageSpecificTitle()
QCString extractLanguageSpecificTitle (const QCString & input, SrcLangExt lang)
Definition at line 1503 of file layout.cpp.
{
  int s=0,e=input.find('|');
  if (e==-1) return input; // simple title case
  int e1=e;
  while (e!=-1) // look for 'number=title' pattern separated by '|'
  {
    s=e+1;
    e=input.find('|',s);
    int i=input.find('=',s);
    assert(i>s);
    SrcLangExt key= static_cast<SrcLangExt>(input.mid(s,i-s).toUInt());
    if (key==lang) // found matching key
    {
      if (e==-1) e=static_cast<int>(input.length());
      return input.mid(i+1,e-i-1);
    }
  }
  return input.left(e1); // fallback, no explicit language key found
}
References QCString::find(), QCString::left(), QCString::length(), and QCString::mid().
Referenced by LayoutDocEntryMemberDecl::subtitle(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), and LayoutDocEntrySection::title().
parentIsVisible()
static bool parentIsVisible (LayoutNavEntry * parent) static
Definition at line 115 of file layout.cpp.
{
  return parent==nullptr || parent->visible();
}
References parent().
Referenced by LayoutParser::startMemberDecl(), LayoutParser::startMemberDeclEntry(), LayoutParser::startMemberDef(), LayoutParser::startMemberDefEntry(), LayoutParser::startNavEntry(), LayoutParser::startSectionEntry(), and LayoutParser::startSimpleEntry().
writeDefaultLayoutFile()
void writeDefaultLayoutFile (const QCString & fileName)
Definition at line 1479 of file layout.cpp.
{
  std::ofstream f;
  if (openOutputFile(fileName,f))
  {
    TextStream t(&f);
    QCString layout_default = ResourceMgr::instance().getAsString("layout_default.xml");
    t << substitute(layout_default,"$doxygenversion",getDoxygenVersion());
  }
  else
  {
    err("Failed to open file %s for writing!\n",qPrint(fileName));
    return;
  }
  f.close();
}
References err, ResourceMgr::getAsString(), ResourceMgr::instance(), openOutputFile(), qPrint(), and substitute().
Referenced by readConfiguration().