Doxygen: src/qhp.cpp File Reference
qhp.cpp File Reference
#include <algorithm>
#include <memory>
#include <string.h>
#include <vector>
#include <cassert>
#include <mutex>
#include "config.h"
#include "debug.h"
#include "doxygen.h"
#include "groupdef.h"
#include "memberdef.h"
#include "message.h"
#include "qhp.h"
#include "textstream.h"
#include "util.h"
#include "portable.h"
#include "language.h"
#include "version.h"
Classes
class QhpSectionTree
struct QhpSectionTree::Node
class Qhp::Private
Functions
static void writeIndent (TextStream &t, int indent)
static QCString getFullProjectName ()
static QCString makeFileName (const QCString &withoutExtension)
static QCString makeRef (const QCString &withoutExtension, const QCString &anchor)
Variables
static std::once_flag g_blankWritten
Function Documentation
getFullProjectName()
static QCString getFullProjectName () static
Definition at line 161 of file qhp.cpp.
{
  QCString projectName = Config_getString(PROJECT_NAME);
  QCString versionText = Config_getString(PROJECT_NUMBER);
  if (projectName.isEmpty()) projectName="Root";
  if (!versionText.isEmpty()) projectName+=" "+versionText;
  return projectName;
}
References Config_getString, and QCString::isEmpty().
Referenced by Qhp::initialize().
makeFileName()
static QCString makeFileName (const QCString & withoutExtension) static
Definition at line 170 of file qhp.cpp.
{
  QCString result=withoutExtension;
  if (!result.isEmpty())
  {
    if (result.at(0)=='!') // relative URL -> strip marker
    {
      result=result.mid(1);
    }
    else // add specified HTML extension
    {
      addHtmlExtensionIfMissing(result);
    }
  }
  return result;
}
References addHtmlExtensionIfMissing(), QCString::at(), QCString::isEmpty(), and QCString::mid().
Referenced by makeRef().
makeRef()
static QCString makeRef (const QCString & withoutExtension, const QCString & anchor) static
Definition at line 187 of file qhp.cpp.
{
  //printf("QHP::makeRef(%s,%s)\n",withoutExtension,anchor);
  if (withoutExtension.isEmpty()) return QCString();
  QCString result = makeFileName(withoutExtension);
  if (anchor.isEmpty()) return result;
  return result+"#"+anchor;
}
References QCString::isEmpty(), and makeFileName().
Referenced by Qhp::addContentsItem(), Crawlmap::addIndexItem(), and Qhp::addIndexItem().
writeIndent()
static void writeIndent (TextStream & t, int indent) inline static
Definition at line 37 of file qhp.cpp.
{
  if (Debug::isFlagSet(Debug::Qhp))
  {
    for (int i=0;i<indent;i++) t << "  ";
  }
}
References Debug::isFlagSet(), and Debug::Qhp.
Referenced by Qhp::addIndexItem(), Qhp::finalize(), generateXMLForPage(), Qhp::initialize(), QhpSectionTree::traverse(), HtmlGenerator::writeLocalToc(), and QhpSectionTree::writeToc().
Variable Documentation
g_blankWritten
std::once_flag g_blankWritten static
Definition at line 34 of file qhp.cpp.
Referenced by Qhp::addContentsItem().