Doxygen: /home/runner/work/doxygen/doxygen/src/template.cpp File Reference
template.cpp File Reference
#include "template.h"
#include <vector>
#include <algorithm>
#include <unordered_map>
#include <deque>
#include <cstdio>
#include "message.h"
#include "util.h"
#include "resourcemgr.h"
#include "portable.h"
#include "regex.h"
#include "fileinfo.h"
#include "dir.h"
#include "utf8.h"
#include "latexgen.h"
#include "trace.h"
Classes
class TemplateStruct
Default implementation of a context value of type struct.
class TemplateListGenericConstIterator< List >
class TemplateList
Default implementation of a context value of type list.
class TemplateImmutableStruct::Private
Private data of a template struct object.
class TemplateImmutableList::Private
Private data of a template immutable list object.
class Operator
Class representing operators that can appear in template expressions.
class TemplateBlockContext
Class holding stacks of blocks available in the context.
struct TemplateKeyValue
A container to store a key-value pair.
class TemplateContextImpl
Internal class representing the implementation of a template context.
class FilterAdd
The implementation of the "add" filter.
class FilterGet
The implementation of the "get" filter.
class FilterRaw
The implementation of the "raw" filter.
class FilterKeep
The implementation of the "keep" filter.
class FilterList
The implementation of the "list" filter.
class FilterTexLabel
The implementation of the "texlabel" filter.
class FilterTexIndex
The implementation of the "texindex" filter.
class FilterAppend
The implementation of the "append" filter.
class FilterPrepend
The implementation of the "prepend" filter.
class FilterLength
The implementation of the "length" filter.
class FilterDefault
The implementation of the "default" filter.
class FilterFlatten
The implementation of the "flatten" filter.
class FilterListSort
The implementation of the "listsort" filter.
struct FilterListSort::ListElem
class FilterGroupBy
The implementation of the "groupBy" filter.
struct FilterGroupBy::ListElem
class FilterRelative
The implementation of the "relative" filter.
class FilterPaginate
The implementation of the "paginate" filter.
class FilterAlphaIndex
The implementation of the "alphaIndex" filter.
struct FilterAlphaIndex::ListElem
class FilterStripPath
The implementation of the "default" filter.
class FilterNoWrap
The implementation of the "default" filter.
class FilterDivisibleBy
The implementation of the "divisibleby" filter.
class FilterIsRelativeURL
The implementation of the "isRelativeURL" filter.
class FilterIsAbsoluteURL
The implementation of the "isRelativeURL" filter.
class FilterLower
The implementation of the "lower" filter.
class FilterUpper
The implementation of the "upper" filter.
class FilterHex
The implementation of the "upper" filter.
class FilterEscape
The implementation of the "e" filter.
class FilterDecodeURL
The implementation of the "decodeURL" filter The leading character is removed from the value in case it is a ^ or !.
class TemplateFilterFactory
Factory singleton for registering and creating filters.
class TemplateFilterFactory::AutoRegister< T >
Helper class for registering a filter function.
class ExprAst
Base class for all nodes in the abstract syntax tree of an expression.
class ExprAstNumber
Class representing a number in the AST.
class ExprAstVariable
Class representing a variable in the AST.
class ExprAstFunctionVariable
class ExprAstFilter
Class representing a filter in the AST.
class ExprAstFilterAppl
Class representing a filter applied to an expression in the AST.
class ExprAstLiteral
Class representing a string literal in the AST.
class ExprAstNegate
Class representing a negation (not) operator in the AST.
class ExprAstUnary
class ExprAstBinary
Class representing a binary operator in the AST.
class TemplateNode
Base class of all nodes in a template's AST.
class TemplateToken
Class representing a lexical token in a template.
class TemplateNodeList
Class representing a list of AST nodes in a template.
class TemplateParser
Parser for templates.
class ExpressionParser
Recursive decent parser for Django style template expressions.
class ExpressionParser::ExprToken
Class representing a token within an expression.
class TemplateImpl
Internal class representing the implementation of a template.
class TemplateNodeText
Class representing a piece of plain text in a template.
class TemplateNodeVariable
Class representing a variable in a template.
class TemplateNodeCreator< T >
Helper class for creating template AST tag nodes and returning the template for a given node.
class TemplateNodeIf
Class representing an 'if' tag in a template.
struct TemplateNodeIf::GuardedNodes
class TemplateNodeRepeat
Class representing a 'for' tag in a template.
class TemplateNodeRange
Class representing a 'range' tag in a template.
class TemplateNodeFor
Class representing a 'for' tag in a template.
class TemplateNodeMsg
Class representing an 'markers' tag in a template.
class TemplateNodeBlock
Class representing a 'block' tag in a template.
class TemplateNodeExtend
Class representing a 'extend' tag in a template.
class TemplateNodeInclude
Class representing an 'include' tag in a template.
class TemplateNodeCreate
Class representing an 'create' tag in a template.
class TemplateNodeTree
Class representing an 'tree' tag in a template.
struct TemplateNodeTree::TreeContext
class TemplateNodeIndexEntry
Class representing an 'indexentry' tag in a template.
struct TemplateNodeIndexEntry::Mapping
class TemplateNodeOpenSubIndex
Class representing an 'opensubindex' tag in a template.
class TemplateNodeCloseSubIndex
Class representing an 'closesubindex' tag in a template.
class TemplateNodeWith
Class representing an 'with' tag in a template.
struct TemplateNodeWith::Mapping
class TemplateNodeCycle
Class representing an 'cycle' tag in a template.
class TemplateNodeSet
Class representing an 'set' tag in a template.
struct TemplateNodeSet::Mapping
class TemplateNodeSpaceless
Class representing an 'spaceless' tag in a template.
class TemplateNodeMarkers
Class representing an 'markers' tag in a template.
class TemplateNodeTabbing
Class representing an 'tabbing' tag in a template.
class TemplateNodeResource
Class representing an 'markers' tag in a template.
class TemplateNodeEncoding
Class representing the 'encoding' tag in a template.
class TemplateNodeFactory
Factory class for creating tag AST nodes found in a template.
class TemplateNodeFactory::AutoRegister< T >
Helper class for registering a template AST node.
class TemplateLexer
Lexer class for turning a template into a list of tokens.
class TemplateEngine::Private
Private data of the template engine.
class TemplateEngine::Private::IncludeEntry
Macros
#define warn warn_
Typedefs
using TemplateStructPtr = std::shared_ptr< TemplateStruct >
using TemplateListPtr = std::shared_ptr< TemplateList >
using ExprAstPtr = std::unique_ptr< ExprAst >
using ExprAstList = std::vector< ExprAstPtr >
using ExprAstFilterPtr = std::unique_ptr< ExprAstFilter >
using TemplateNodePtr = std::unique_ptr< TemplateNode >
using TemplateTokenPtr = std::unique_ptr< TemplateToken >
using TemplateTokenStream = std::deque< TemplateTokenPtr >
Functions
static std::vector< QCString > split (const QCString &str, const QCString &sep, bool allowEmptyEntries=FALSE, bool cleanup=TRUE)
static void removeSpacesAroundEquals (QCString &s)
Strips spaces surrounding = from string in, so ‘foo = 10 bar=5 baz= 'hello’will becomefoo=10 bar=5 baz='hello'`.
static void getPathListFunc (const TemplateStructIntfPtr entry, TemplateListPtr list)
static TemplateVariant getPathFunc (const TemplateStructIntfWeakPtr entryWeakRef)
static void stripLeadingWhiteSpace (QCString &s)
Variables
static TemplateFilterFactory::AutoRegister< FilterAdd > fAdd ("add")
static TemplateFilterFactory::AutoRegister< FilterGet > fGet ("get")
static TemplateFilterFactory::AutoRegister< FilterHex > fHex ("hex")
static TemplateFilterFactory::AutoRegister< FilterRaw > fRaw ("raw")
static TemplateFilterFactory::AutoRegister< FilterKeep > fKeep ("keep")
static TemplateFilterFactory::AutoRegister< FilterList > fList ("list")
static TemplateFilterFactory::AutoRegister< FilterLower > fLower ("lower")
static TemplateFilterFactory::AutoRegister< FilterUpper > fUpper ("upper")
static TemplateFilterFactory::AutoRegister< FilterAppend > fAppend ("append")
static TemplateFilterFactory::AutoRegister< FilterEscape > fEscape ("escape")
static TemplateFilterFactory::AutoRegister< FilterLength > fLength ("length")
static TemplateFilterFactory::AutoRegister< FilterNoWrap > fNoWrap ("nowrap")
static TemplateFilterFactory::AutoRegister< FilterFlatten > fFlatten ("flatten")
static TemplateFilterFactory::AutoRegister< FilterDefault > fDefault ("default")
static TemplateFilterFactory::AutoRegister< FilterPrepend > fPrepend ("prepend")
static TemplateFilterFactory::AutoRegister< FilterGroupBy > fGroupBy ("groupBy")
static TemplateFilterFactory::AutoRegister< FilterRelative > fRelative ("relative")
static TemplateFilterFactory::AutoRegister< FilterListSort > fListSort ("listsort")
static TemplateFilterFactory::AutoRegister< FilterTexLabel > fTexLabel ("texLabel")
static TemplateFilterFactory::AutoRegister< FilterTexIndex > fTexIndex ("texIndex")
static TemplateFilterFactory::AutoRegister< FilterPaginate > fPaginate ("paginate")
static TemplateFilterFactory::AutoRegister< FilterStripPath > fStripPath ("stripPath")
static TemplateFilterFactory::AutoRegister< FilterDecodeURL > fDecodeURL ("decodeURL")
static TemplateFilterFactory::AutoRegister< FilterAlphaIndex > fAlphaIndex ("alphaIndex")
static TemplateFilterFactory::AutoRegister< FilterDivisibleBy > fDivisibleBy ("divisibleby")
static TemplateFilterFactory::AutoRegister< FilterIsRelativeURL > fIsRelativeURL ("isRelativeURL")
static TemplateFilterFactory::AutoRegister< FilterIsAbsoluteURL > fIsAbsoluteURL ("isAbsoluteURL")
static TemplateNodeFactory::AutoRegister< TemplateNodeIf > autoRefIf ("if")
static TemplateNodeFactory::AutoRegister< TemplateNodeFor > autoRefFor ("for")
static TemplateNodeFactory::AutoRegister< TemplateNodeMsg > autoRefMsg ("msg")
static TemplateNodeFactory::AutoRegister< TemplateNodeSet > autoRefSet ("set")
static TemplateNodeFactory::AutoRegister< TemplateNodeTree > autoRefTree ("recursetree")
static TemplateNodeFactory::AutoRegister< TemplateNodeWith > autoRefWith ("with")
static TemplateNodeFactory::AutoRegister< TemplateNodeBlock > autoRefBlock ("block")
static TemplateNodeFactory::AutoRegister< TemplateNodeCycle > autoRefCycle ("cycle")
static TemplateNodeFactory::AutoRegister< TemplateNodeRange > autoRefRange ("range")
static TemplateNodeFactory::AutoRegister< TemplateNodeExtend > autoRefExtend ("extend")
static TemplateNodeFactory::AutoRegister< TemplateNodeCreate > autoRefCreate ("create")
static TemplateNodeFactory::AutoRegister< TemplateNodeRepeat > autoRefRepeat ("repeat")
static TemplateNodeFactory::AutoRegister< TemplateNodeInclude > autoRefInclude ("include")
static TemplateNodeFactory::AutoRegister< TemplateNodeMarkers > autoRefMarkers ("markers")
static TemplateNodeFactory::AutoRegister< TemplateNodeTabbing > autoRefTabbing ("tabbing")
static TemplateNodeFactory::AutoRegister< TemplateNodeResource > autoRefResource ("resource")
static TemplateNodeFactory::AutoRegister< TemplateNodeEncoding > autoRefEncoding ("encoding")
static TemplateNodeFactory::AutoRegister< TemplateNodeSpaceless > autoRefSpaceless ("spaceless")
static TemplateNodeFactory::AutoRegister< TemplateNodeIndexEntry > autoRefIndexEntry ("indexentry")
static TemplateNodeFactory::AutoRegister< TemplateNodeOpenSubIndex > autoRefOpenSubIndex ("opensubindex")
static TemplateNodeFactory::AutoRegister< TemplateNodeCloseSubIndex > autoRefCloseSubIndex ("closesubindex")
Macro Definition Documentation
warn
#define warn warn_
Definition at line 37 of file template.cpp.
Typedef Documentation
ExprAstFilterPtr
using ExprAstFilterPtr = std::unique_ptr<ExprAstFilter>
Definition at line 1742 of file template.cpp.
ExprAstList
using ExprAstList = std::vector< ExprAstPtr >
Definition at line 1654 of file template.cpp.
ExprAstPtr
using ExprAstPtr = std::unique_ptr<ExprAst>
Definition at line 1653 of file template.cpp.
TemplateListPtr
using TemplateListPtr = std::shared_ptr<TemplateList>
Definition at line 208 of file template.cpp.
TemplateNodePtr
using TemplateNodePtr = std::unique_ptr<TemplateNode>
Definition at line 1929 of file template.cpp.
TemplateStructPtr
using TemplateStructPtr = std::shared_ptr<TemplateStruct>
Definition at line 131 of file template.cpp.
TemplateTokenPtr
using TemplateTokenPtr = std::unique_ptr<TemplateToken>
Definition at line 1944 of file template.cpp.
TemplateTokenStream
using TemplateTokenStream = std::deque< TemplateTokenPtr >
Definition at line 1945 of file template.cpp.
Function Documentation
getPathFunc()
static TemplateVariant getPathFunc (const TemplateStructIntfWeakPtr entryWeakRef) static
Definition at line 2816 of file template.cpp.
{
  TemplateListPtr result = TemplateList::alloc();
  getPathListFunc(entryWeakRef.lock(),result);
  return std::static_pointer_cast<TemplateListIntf>(result);
}
References TemplateList::alloc(), and getPathListFunc().
Referenced by TemplateContextImpl::addIndexEntry().
getPathListFunc()
static void getPathListFunc (const TemplateStructIntfPtr entry, TemplateListPtr list) static
Definition at line 2803 of file template.cpp.
{
  if (entry)
  {
    TemplateVariant parent = entry->get("parent");
    if (parent.isStruct() || parent.isWeakStruct())
    {
      getPathListFunc(parent.toStruct(),list);
    }
    list->append(entry);
  }
}
References getPathListFunc(), and parent().
Referenced by getPathFunc(), and getPathListFunc().
removeSpacesAroundEquals()
static void removeSpacesAroundEquals (QCString & s) static
Strips spaces surrounding = from string in, so ‘foo = 10 bar=5 baz= 'hello’will becomefoo=10 bar=5 baz='hello'`.
Definition at line 97 of file template.cpp.
{
  //printf(">removeSpacesAroundEquals(%s)\n",qPrint(s));
  uint32_t i=0, dstIdx=0, l=s.length();
  while (i<l)
  {
    char c = s[i++];
    if (c==' ')
    {
      bool found=false;
      // look ahead for space or '='
      uint32_t j=i;
      while (j<l && (s[j]==' '|| s[j]=='='))
      {
        if (s[j]=='=') found=true;
        j++;
      }
      if (found) // found a '=', write it without spaces
      {
        c = '=';
        i=j;
      }
    }
    s[dstIdx++]=c;
  }
  s.resize(dstIdx+1);
  //printf("<removeSpacesAroundEquals(%s)\n",qPrint(s));
}
References found, QCString::length(), and QCString::resize().
Referenced by TemplateNodeWith::TemplateNodeWith().
split()
static std::vector< QCString > split (const QCString & str, const QCString & sep, bool allowEmptyEntries = FALSE, bool cleanup = TRUE) static
Definition at line 43 of file template.cpp.
{
  std::vector<QCString> lst;
  int j = 0;
  int i = str.find( sep, j );
  while (i!=-1)
  {
    if ( str.mid(j,i-j).length() > 0 )
    {
      if (cleanup)
      {
        lst.push_back(str.mid(j,i-j).stripWhiteSpace());
      }
      else
      {
        lst.push_back(str.mid(j,i-j));
      }
    }
    else if (allowEmptyEntries)
    {
      lst.push_back("");
    }
    j = i + sep.length();
    i = str.find(sep,j);
  }
  int l = str.length() - 1;
  if (str.mid(j,l-j+1).length()>0)
  {
    if (cleanup)
    {
      lst.push_back(str.mid(j,l-j+1).stripWhiteSpace());
    }
    else
    {
      lst.push_back(str.mid(j,l-j+1));
    }
  }
  else if (allowEmptyEntries)
  {
    lst.push_back("");
  }
  return lst;
}
References QCString::find(), QCString::length(), QCString::mid(), and QCString::stripWhiteSpace().
Referenced by VHDLOutlineParser::addProto(), VHDLOutlineParser::addVhdlType(), FlowChart::alignCommentNode(), VHDLOutlineParser::checkInlineCode(), checkVhdlString(), VHDLOutlineParser::createFunction(), VhdlDocGen::findArchitecture(), formatBriefNote(), getFilteredImageAttributes(), VhdlDocGen::getIndexWord(), DocPara::handleCommand(), DocParser::handleImage(), DocPara::handleInclude(), Qhp::initialize(), VhdlDocGen::parseForBinding(), VhdlDocGen::parseForConfig(), TemplateNodeCycle::TemplateNodeCycle(), TemplateNodeFor::TemplateNodeFor(), TemplateNodeIndexEntry::TemplateNodeIndexEntry(), TemplateNodeWith::TemplateNodeWith(), writeFuncProto(), VhdlDocGen::writeInlineClassLink(), and VhdlDocGen::writeRecUnitDocu().
stripLeadingWhiteSpace()
static void stripLeadingWhiteSpace (QCString & s) static
Definition at line 3775 of file template.cpp.
{
  bool skipSpaces=true;
  const char *src = s.data();
  char *dst = s.rawData();
  char c;
  while ((c=*src++))
  {
    if (c=='\n') { *dst++=c; skipSpaces=true; }
    else if (c==' ' && skipSpaces) {}
    else { *dst++ = c; skipSpaces=false; }
  }
  s.resize(dst-s.data()+1);
}
References QCString::data(), QCString::rawData(), and QCString::resize().
Referenced by TemplateNodeCreate::render().
Variable Documentation
autoRefBlock
TemplateNodeFactory::AutoRegister< TemplateNodeBlock > autoRefBlock("block") ("block") static
autoRefCloseSubIndex
TemplateNodeFactory::AutoRegister< TemplateNodeCloseSubIndex > autoRefCloseSubIndex("closesubindex") ("closesubindex") static
autoRefCreate
TemplateNodeFactory::AutoRegister< TemplateNodeCreate > autoRefCreate("create") ("create") static
autoRefCycle
TemplateNodeFactory::AutoRegister< TemplateNodeCycle > autoRefCycle("cycle") ("cycle") static
autoRefEncoding
TemplateNodeFactory::AutoRegister< TemplateNodeEncoding > autoRefEncoding("encoding") ("encoding") static
autoRefExtend
TemplateNodeFactory::AutoRegister< TemplateNodeExtend > autoRefExtend("extend") ("extend") static
autoRefFor
TemplateNodeFactory::AutoRegister< TemplateNodeFor > autoRefFor("for") ("for") static
autoRefIf
TemplateNodeFactory::AutoRegister< TemplateNodeIf > autoRefIf("if") ("if") static
autoRefInclude
TemplateNodeFactory::AutoRegister< TemplateNodeInclude > autoRefInclude("include") ("include") static
autoRefIndexEntry
TemplateNodeFactory::AutoRegister< TemplateNodeIndexEntry > autoRefIndexEntry("indexentry") ("indexentry") static
autoRefMarkers
TemplateNodeFactory::AutoRegister< TemplateNodeMarkers > autoRefMarkers("markers") ("markers") static
autoRefMsg
TemplateNodeFactory::AutoRegister< TemplateNodeMsg > autoRefMsg("msg") ("msg") static
autoRefOpenSubIndex
TemplateNodeFactory::AutoRegister< TemplateNodeOpenSubIndex > autoRefOpenSubIndex("opensubindex") ("opensubindex") static
autoRefRange
TemplateNodeFactory::AutoRegister< TemplateNodeRange > autoRefRange("range") ("range") static
autoRefRepeat
TemplateNodeFactory::AutoRegister< TemplateNodeRepeat > autoRefRepeat("repeat") ("repeat") static
autoRefResource
TemplateNodeFactory::AutoRegister< TemplateNodeResource > autoRefResource("resource") ("resource") static
autoRefSet
TemplateNodeFactory::AutoRegister< TemplateNodeSet > autoRefSet("set") ("set") static
autoRefSpaceless
TemplateNodeFactory::AutoRegister< TemplateNodeSpaceless > autoRefSpaceless("spaceless") ("spaceless") static
autoRefTabbing
TemplateNodeFactory::AutoRegister< TemplateNodeTabbing > autoRefTabbing("tabbing") ("tabbing") static
autoRefTree
TemplateNodeFactory::AutoRegister< TemplateNodeTree > autoRefTree("recursetree") ("recursetree") static
autoRefWith
TemplateNodeFactory::AutoRegister< TemplateNodeWith > autoRefWith("with") ("with") static
fAdd
TemplateFilterFactory::AutoRegister< FilterAdd > fAdd("add") ("add") static
fAlphaIndex
TemplateFilterFactory::AutoRegister< FilterAlphaIndex > fAlphaIndex("alphaIndex") ("alphaIndex") static
fAppend
TemplateFilterFactory::AutoRegister< FilterAppend > fAppend("append") ("append") static
fDecodeURL
TemplateFilterFactory::AutoRegister< FilterDecodeURL > fDecodeURL("decodeURL") ("decodeURL") static
fDefault
TemplateFilterFactory::AutoRegister< FilterDefault > fDefault("default") ("default") static
fDivisibleBy
TemplateFilterFactory::AutoRegister< FilterDivisibleBy > fDivisibleBy("divisibleby") ("divisibleby") static
fEscape
TemplateFilterFactory::AutoRegister< FilterEscape > fEscape("escape") ("escape") static
fFlatten
TemplateFilterFactory::AutoRegister< FilterFlatten > fFlatten("flatten") ("flatten") static
fGet
TemplateFilterFactory::AutoRegister< FilterGet > fGet("get") ("get") static
fGroupBy
TemplateFilterFactory::AutoRegister< FilterGroupBy > fGroupBy("groupBy") ("groupBy") static
fHex
TemplateFilterFactory::AutoRegister< FilterHex > fHex("hex") ("hex") static
fIsAbsoluteURL
TemplateFilterFactory::AutoRegister< FilterIsAbsoluteURL > fIsAbsoluteURL("isAbsoluteURL") ("isAbsoluteURL") static
fIsRelativeURL
TemplateFilterFactory::AutoRegister< FilterIsRelativeURL > fIsRelativeURL("isRelativeURL") ("isRelativeURL") static
fKeep
TemplateFilterFactory::AutoRegister< FilterKeep > fKeep("keep") ("keep") static
fLength
TemplateFilterFactory::AutoRegister< FilterLength > fLength("length") ("length") static
fList
TemplateFilterFactory::AutoRegister< FilterList > fList("list") ("list") static
Referenced by NestingContext::Private::addFiles().
fListSort
TemplateFilterFactory::AutoRegister< FilterListSort > fListSort("listsort") ("listsort") static
fLower
TemplateFilterFactory::AutoRegister< FilterLower > fLower("lower") ("lower") static
fNoWrap
TemplateFilterFactory::AutoRegister< FilterNoWrap > fNoWrap("nowrap") ("nowrap") static
fPaginate
TemplateFilterFactory::AutoRegister< FilterPaginate > fPaginate("paginate") ("paginate") static
fPrepend
TemplateFilterFactory::AutoRegister< FilterPrepend > fPrepend("prepend") ("prepend") static
fRaw
TemplateFilterFactory::AutoRegister< FilterRaw > fRaw("raw") ("raw") static
fRelative
TemplateFilterFactory::AutoRegister< FilterRelative > fRelative("relative") ("relative") static
fStripPath
TemplateFilterFactory::AutoRegister< FilterStripPath > fStripPath("stripPath") ("stripPath") static
fTexIndex
TemplateFilterFactory::AutoRegister< FilterTexIndex > fTexIndex("texIndex") ("texIndex") static
fTexLabel
TemplateFilterFactory::AutoRegister< FilterTexLabel > fTexLabel("texLabel") ("texLabel") static
fUpper
TemplateFilterFactory::AutoRegister< FilterUpper > fUpper("upper") ("upper") static