Doxygen: DocHtmlListItem Class Reference
DocHtmlListItem Class Reference
Node representing a HTML list item.
#include <src/docnode.h>
Public Member Functions
DocHtmlListItem (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, int num)
int itemNumber () const
const HtmlAttribList & attribs () const
int parse ()
int parseXml ()
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
DocNode (const DocNode &)=delete
DocNode & operator= (const DocNode &)=delete
DocNode (DocNode &&)=default
DocNode & operator= (DocNode &&)=default
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
HtmlAttribList m_attribs
int m_itemNum = 0
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a HTML list item.
Definition at line 1122 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlListItem()
DocHtmlListItem::DocHtmlListItem (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, int num) inline
Definition at line 1125 of file docnode.h.
    : DocCompoundNode(parser,parent), m_attribs(attribs), m_itemNum(num) {}
Member Function Documentation
attribs()
const HtmlAttribList & DocHtmlListItem::attribs () const inline
Definition at line 1128 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
itemNumber()
int DocHtmlListItem::itemNumber () const inline
Definition at line 1127 of file docnode.h.
{ return m_itemNum; }
References m_itemNum.
parse()
int DocHtmlListItem::parse ()
Definition at line 2395 of file docnode.cpp.
{
  AUTO_TRACE();
  int retval=0;
  auto ns = AutoNodeStack(parser(),thisVariant());
  // parse one or more paragraphs
  bool isFirst=TRUE;
  DocPara *par=nullptr;
  do
  {
    children().append<DocPara>(parser(),thisVariant());
    par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse();
  }
  while (retval==TK_NEWPARA);
  if (par) par->markLast();
  AUTO_TRACE_EXIT("retval={}",DocTokenizer::retvalToString(retval));
  return retval;
}
References DocNodeList::append(), AUTO_TRACE, AUTO_TRACE_EXIT, DocCompoundNode::children(), FALSE, DocNodeList::get_last(), DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), DocNode::parser(), DocTokenizer::retvalToString(), DocNode::thisVariant(), TK_NEWPARA, and TRUE.
Referenced by DocHtmlList::parse().
parseXml()
int DocHtmlListItem::parseXml ()
Definition at line 2418 of file docnode.cpp.
{
  AUTO_TRACE();
  int retval=0;
  auto ns = AutoNodeStack(parser(),thisVariant());
  // parse one or more paragraphs
  bool isFirst=TRUE;
  DocPara *par=nullptr;
  do
  {
    children().append<DocPara>(parser(),thisVariant());
    par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse();
    if (retval==0) break;
    //printf("new item: retval=%x parser()->context.token->name=%s parser()->context.token->endTag=%d\n",
    //    retval,qPrint(parser()->context.token->name),parser()->context.token->endTag);
    if (retval==RetVal_ListItem)
    {
      break;
    }
  }
  while (retval!=RetVal_CloseXml);
  if (par) par->markLast();
  AUTO_TRACE_EXIT("retval={}",DocTokenizer::retvalToString(retval));
  return retval;
}
References DocNodeList::append(), AUTO_TRACE, AUTO_TRACE_EXIT, DocCompoundNode::children(), FALSE, DocNodeList::get_last(), DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), DocNode::parser(), RetVal_CloseXml, RetVal_ListItem, DocTokenizer::retvalToString(), DocNode::thisVariant(), and TRUE.
Referenced by DocHtmlList::parseXml().
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlListItem::m_attribs private
Definition at line 1133 of file docnode.h.
Referenced by attribs().
m_itemNum
int DocHtmlListItem::m_itemNum = 0 private
Definition at line 1134 of file docnode.h.
Referenced by itemNumber().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp