Doxygen: DocbookGenerator Class Reference
DocbookGenerator Class Reference
#include <src/docbookgen.h>
Public Member Functions
DocbookGenerator ()
DocbookGenerator (const DocbookGenerator &)
DocbookGenerator & operator= (const DocbookGenerator &)
DocbookGenerator (DocbookGenerator &&)=delete
DocbookGenerator & operator= (DocbookGenerator &&)=delete
~DocbookGenerator ()
OutputType type () const override
std::unique_ptr< OutputGenIntf > clone () override
void addCodeGen (OutputCodeList &list) override
void cleanup () override
void writeDoc (const IDocNodeAST *node, const Definition *ctx, const MemberDef *md, int id) override
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id, int hierarchyLevel) override
void endFile () override
void writeSearchInfo () override
void writeFooter (const QCString &) override
void startIndexSection (IndexSection) override
void endIndexSection (IndexSection) override
void writePageLink (const QCString &, bool) override
void startProjectNumber () override
void endProjectNumber () override
void writeStyleInfo (int) override
void startTitleHead (const QCString &) override
void endTitleHead (const QCString &fileName, const QCString &name) override
void startIndexListItem () override
void endIndexListItem () override
void startIndexList () override
void endIndexList () override
void startIndexKey () override
void endIndexKey () override
void startIndexValue (bool) override
void endIndexValue (const QCString &, bool) override
void startItemList () override
void endItemList () override
void startIndexItem (const QCString &, const QCString &) override
void endIndexItem (const QCString &, const QCString &) override
void startItemListItem () override
void endItemListItem () override
void docify (const QCString &text) override
void writeChar (char) override
void writeString (const QCString &) override
void startParagraph (const QCString &) override
void endParagraph () override
void writeObjectLink (const QCString &, const QCString &, const QCString &, const QCString &) override
void startBold () override
void endBold () override
void startTypewriter () override
void endTypewriter () override
void startEmphasis () override
void endEmphasis () override
void writeRuler () override
void startDescForItem () override
void endDescForItem () override
void startCenter () override
void endCenter () override
void startSmall () override
void endSmall () override
void startExamples () override
void endExamples () override
void writeAnchor (const QCString &, const QCString &) override
void startSection (const QCString &, const QCString &, SectionType) override
void endSection (const QCString &, SectionType) override
void lineBreak (const QCString &) override
void addIndexItem (const QCString &, const QCString &) override
void writeNonBreakableSpace (int) override
void startDescTable (const QCString &title, const bool hasInits) override
void endDescTable () override
void startDescTableRow () override
void endDescTableRow () override
void startDescTableTitle () override
void endDescTableTitle () override
void startDescTableInit () override
void endDescTableInit () override
void startDescTableData () override
void endDescTableData () override
void startTextLink (const QCString &, const QCString &) override
void endTextLink () override
void startPageRef () override
void endPageRef (const QCString &, const QCString &) override
void startGroupHeader (int) override
void endGroupHeader (int) override
void startMemberSections () override
void endMemberSections () override
void startHeaderSection () override
void endHeaderSection () override
void startMemberHeader (const QCString &anchor, int typ) override
void endMemberHeader () override
void startMemberSubtitle () override
void endMemberSubtitle () override
void startMemberDocList () override
void endMemberDocList () override
void startMemberList () override
void endMemberList () override
void startInlineHeader () override
void endInlineHeader () override
void startAnonTypeScope (int) override
void endAnonTypeScope (int) override
void startMemberItem (const QCString &, MemberItemType, const QCString &) override
void endMemberItem (MemberItemType) override
void startMemberTemplateParams () override
void endMemberTemplateParams (const QCString &, const QCString &) override
void startCompoundTemplateParams () override
void endCompoundTemplateParams () override
void startMemberGroupHeader (bool) override
void endMemberGroupHeader () override
void startMemberGroupDocs () override
void endMemberGroupDocs () override
void startMemberGroup () override
void endMemberGroup (bool) override
void insertMemberAlign (bool) override
void insertMemberAlignLeft (MemberItemType, bool) override
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool) override
void endMemberDoc (bool) override
void startDoxyAnchor (const QCString &fName, const QCString &manName, const QCString &anchor, const QCString &name, const QCString &args) override
void endDoxyAnchor (const QCString &fileName, const QCString &anchor) override
void addLabel (const QCString &, const QCString &) override
void writeLatexSpacing () override
void writeStartAnnoItem (const QCString &, const QCString &, const QCString &, const QCString &) override
void startMemberDescription (const QCString &, const QCString &, bool) override
void endMemberDescription () override
void startMemberDeclaration () override
void endMemberDeclaration (const QCString &, const QCString &) override
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &) override
void startIndent () override
void endIndent () override
void writeSynopsis () override
void startClassDiagram () override
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &) override
void startDotGraph () override
void endDotGraph (DotClassGraph &g) override
void startInclDepGraph () override
void endInclDepGraph (DotInclDepGraph &g) override
void startGroupCollaboration () override
void endGroupCollaboration (DotGroupCollaboration &g) override
void startCallGraph () override
void endCallGraph (DotCallGraph &g) override
void startDirDepGraph () override
void endDirDepGraph (DotDirDeps &g) override
void writeGraphicalHierarchy (DotGfxHierarchyTable &) override
void startQuickIndices () override
void endQuickIndices () override
void writeSplitBar (const QCString &) override
void writeNavigationPath (const QCString &) override
void writeLogo () override
void writeQuickLinks (HighlightedItem, const QCString &) override
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool) override
void startContents () override
void endContents () override
void startPageDoc (const QCString &) override
void endPageDoc () override
void startTextBlock (bool) override
void endTextBlock (bool) override
void lastIndexPage () override
void startMemberDocPrefixItem () override
void endMemberDocPrefixItem () override
void startMemberDocName (bool) override
void endMemberDocName () override
void startParameterType (bool, const QCString &) override
void endParameterType () override
void startParameterName (bool) override
void endParameterName () override
void startParameterExtra () override
void endParameterExtra (bool, bool, bool) override
void startParameterDefVal (const char *sep) override
void endParameterDefVal () override
void startParameterList (bool) override
void endParameterList () override
void exceptionEntry (const QCString &, bool) override
void startConstraintList (const QCString &) override
void startConstraintParam () override
void endConstraintParam () override
void startConstraintType () override
void endConstraintType () override
void startConstraintDocs () override
void endConstraintDocs () override
void endConstraintList () override
void startMemberDocSimple (bool) override
void endMemberDocSimple (bool) override
void startInlineMemberType () override
void endInlineMemberType () override
void startInlineMemberName () override
void endInlineMemberName () override
void startInlineMemberDoc () override
void endInlineMemberDoc () override
void startLabels () override
void writeLabel (const QCString &, bool) override
void endLabels () override
void writeLocalToc (const SectionRefs &sr, const LocalToc &lt) override
void startPlainFile (const QCString &name) override
void endPlainFile () override
Public Member Functions inherited from OutputGenerator
OutputGenerator ()
OutputGenerator (const QCString &dir)
virtual ~OutputGenerator ()=default
QCString dir () const
QCString fileName () const
void startPlainFile (const QCString &name)
void endPlainFile ()
Public Member Functions inherited from OutputGenIntf
Static Public Member Functions
static void init ()
Private Member Functions
void openSection (const QCString &attr=QCString())
void closeSection ()
void closeAllSections ()
Private Attributes
QCString relPath
std::unique_ptr< OutputCodeList > m_codeList
DocbookCodeGenerator * m_codeGen = nullptr
bool m_denseText = false
bool m_inGroup = false
int m_levelListItem = 0
std::array< bool, 20 > m_inListItem = { false, }
std::array< bool, 20 > m_inSimpleSect = { false, }
bool m_descTable = false
bool m_simpleTable = false
int m_inLevel = -1
bool m_firstMember = false
int m_openSectionCount = 0
QCString m_pageLinks
Additional Inherited Members
Public Types inherited from OutputGenerator
enum class ParamListTypes { Param , RetVal , Exception }
enum class MemberItemType { Normal , AnonymousStart , AnonymousEnd , Templated }
Protected Attributes inherited from OutputGenerator
TextStream m_t
QCString m_dir
Detailed Description
Definition at line 103 of file docbookgen.h.
Constructor & Destructor Documentation
DocbookGenerator() [1/3]
DocbookGenerator::DocbookGenerator ()
Definition at line 319 of file docbookgen.cpp.
  : OutputGenerator(Config_getString(DOCBOOK_OUTPUT))
  , m_codeList(std::make_unique<OutputCodeList>())
{
DB_GEN_C
  m_codeGen = m_codeList->add<DocbookCodeGenerator>(&m_t);
}
References Config_getString, DB_GEN_C, m_codeGen, m_codeList, OutputGenerator::m_t, and OutputGenerator::OutputGenerator().
Referenced by DocbookGenerator(), DocbookGenerator(), operator=(), and operator=().
DocbookGenerator() [2/3]
DocbookGenerator::DocbookGenerator (const DocbookGenerator & og)
Definition at line 327 of file docbookgen.cpp.
                                                             : OutputGenerator(og.m_dir), OutputGenIntf()
{
  m_codeList         = std::make_unique<OutputCodeList>(*og.m_codeList);
  m_codeGen          = m_codeList->get<DocbookCodeGenerator>(OutputType::Docbook);
  m_codeGen->setTextStream(&m_t);
  m_denseText        = og.m_denseText;
  m_inGroup          = og.m_inGroup;
  m_levelListItem    = og.m_levelListItem;
  m_inListItem       = og.m_inListItem;
  m_inSimpleSect     = og.m_inSimpleSect;
  m_descTable        = og.m_descTable;
  m_simpleTable      = og.m_simpleTable;
  m_inLevel          = og.m_inLevel;
  m_firstMember      = og.m_firstMember;
  m_openSectionCount = og.m_openSectionCount;
}
References Docbook, DocbookGenerator(), m_codeGen, m_codeList, m_denseText, m_descTable, OutputGenerator::m_dir, m_firstMember, m_inGroup, m_inLevel, m_inListItem, m_inSimpleSect, m_levelListItem, m_openSectionCount, m_simpleTable, OutputGenerator::m_t, and OutputGenerator::OutputGenerator().
DocbookGenerator() [3/3]
DocbookGenerator::DocbookGenerator (DocbookGenerator &&) delete
References DocbookGenerator().
~DocbookGenerator()
DocbookGenerator::~DocbookGenerator () default
Member Function Documentation
addCodeGen()
void DocbookGenerator::addCodeGen (OutputCodeList & list) override virtual
Implements OutputGenIntf.
Definition at line 368 of file docbookgen.cpp.
{
  list.add<DocbookCodeGeneratorDefer>(m_codeGen);
}
References OutputCodeList::add(), and m_codeGen.
addIndexItem()
void DocbookGenerator::addIndexItem (const QCString & prim, const QCString & sec) override virtual
Implements OutputGenIntf.
Definition at line 1144 of file docbookgen.cpp.
{
DB_GEN_C
  addIndexTerm(m_t, prim, sec);
}
References addIndexTerm(), DB_GEN_C, and OutputGenerator::m_t.
addLabel()
void DocbookGenerator::addLabel (const QCString & , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 959 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
cleanup()
void DocbookGenerator::cleanup () override virtual
Implements OutputGenIntf.
Definition at line 384 of file docbookgen.cpp.
{
  QCString dname = Config_getString(DOCBOOK_OUTPUT);
  Dir d(dname.str());
  clearSubDirs(d);
}
References clearSubDirs(), Config_getString, and QCString::str().
clone()
std::unique_ptr< OutputGenIntf > DocbookGenerator::clone () inline override virtual
Implements OutputGenIntf.
Definition at line 121 of file docbookgen.h.
{ return std::make_unique<DocbookGenerator>(*this); }
closeAllSections()
void DocbookGenerator::closeAllSections () private
Definition at line 1398 of file docbookgen.cpp.
{
  while (m_openSectionCount>0)
  {
    closeSection();
  }
}
References closeSection(), and m_openSectionCount.
Referenced by endFile().
closeSection()
void DocbookGenerator::closeSection () private
Definition at line 1392 of file docbookgen.cpp.
{
   m_t << "</section>\n";
   m_openSectionCount--;
}
References m_openSectionCount, and OutputGenerator::m_t.
Referenced by closeAllSections(), endSection(), startDoxyAnchor(), startGroupHeader(), and writeRuler().
docify()
void DocbookGenerator::docify (const QCString & text) override virtual
Implements OutputGenIntf.
Definition at line 766 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << convertToDocBook(str);
}
References convertToDocBook(), DB_GEN_C, and OutputGenerator::m_t.
Referenced by startConstraintList(), startExamples(), and writeChar().
endAnonTypeScope()
void DocbookGenerator::endAnonTypeScope (int) inline override virtual
Implements OutputGenIntf.
Definition at line 213 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endBold()
void DocbookGenerator::endBold () override virtual
Implements OutputGenIntf.
Definition at line 828 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</emphasis>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endCallGraph()
void DocbookGenerator::endCallGraph (DotCallGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 1321 of file docbookgen.cpp.
{
DB_GEN_C
  QCString fn = g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::DocBook,dir(),fileName(),relPath,FALSE);
}
References BITMAP, DB_GEN_C, OutputGenerator::dir(), DocBook, FALSE, OutputGenerator::fileName(), OutputGenerator::m_t, relPath, and DotCallGraph::writeGraph().
endCenter()
void DocbookGenerator::endCenter () inline override virtual
Implements OutputGenIntf.
Definition at line 169 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endClassDiagram()
void DocbookGenerator::endClassDiagram (const ClassDiagram & d, const QCString & fileName, const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 997 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "    <informalfigure>\n";
  m_t << "        <mediaobject>\n";
  m_t << "            <imageobject>\n";
  m_t << "                <imagedata width=\"50%\" align=\"center\" valign=\"middle\" scalefit=\"0\" fileref=\""
                         << relPath << fileName << ".png\">" << "</imagedata>\n";
  m_t << "            </imageobject>\n";
  d.writeImage(m_t,dir(),relPath,fileName,FALSE);
  m_t << "        </mediaobject>\n";
  m_t << "    </informalfigure>\n";
  m_t << "</para>\n";
}
References DB_GEN_C, OutputGenerator::dir(), FALSE, OutputGenerator::fileName(), OutputGenerator::m_t, relPath, and ClassDiagram::writeImage().
endCompoundTemplateParams()
void DocbookGenerator::endCompoundTemplateParams () override virtual
Implements OutputGenIntf.
Definition at line 1045 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</title></simplesect>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endConstraintDocs()
void DocbookGenerator::endConstraintDocs () override virtual
Implements OutputGenIntf.
Definition at line 1374 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endConstraintList()
void DocbookGenerator::endConstraintList () override virtual
Implements OutputGenIntf.
Definition at line 1378 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</simplesect>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endConstraintParam()
void DocbookGenerator::endConstraintParam () override virtual
Implements OutputGenIntf.
Definition at line 1356 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endConstraintType()
void DocbookGenerator::endConstraintType () override virtual
Implements OutputGenIntf.
Definition at line 1365 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</emphasis></para>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endContents()
void DocbookGenerator::endContents () inline override virtual
Implements OutputGenIntf.
Definition at line 270 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endDescForItem()
void DocbookGenerator::endDescForItem () inline override virtual
Implements OutputGenIntf.
Definition at line 167 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endDescTable()
void DocbookGenerator::endDescTable () override virtual
Implements OutputGenIntf.
Definition at line 1236 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "    </tbody>\n";
  m_t << "    </tgroup>\n";
  m_t << "</informaltable>\n";
  m_descTable = FALSE;
}
References DB_GEN_C, FALSE, m_descTable, and OutputGenerator::m_t.
endDescTableData()
void DocbookGenerator::endDescTableData () override virtual
Implements OutputGenIntf.
Definition at line 1285 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endDescTableInit()
void DocbookGenerator::endDescTableInit () override virtual
Implements OutputGenIntf.
Definition at line 1274 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endDescTableRow()
void DocbookGenerator::endDescTableRow () override virtual
Implements OutputGenIntf.
Definition at line 1252 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</row>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endDescTableTitle()
void DocbookGenerator::endDescTableTitle () override virtual
Implements OutputGenIntf.
Definition at line 1263 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endDirDepGraph()
void DocbookGenerator::endDirDepGraph (DotDirDeps & g) override virtual
Implements OutputGenIntf.
Definition at line 1330 of file docbookgen.cpp.
{
DB_GEN_C
  QCString fn = g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::DocBook,dir(),fileName(),relPath,FALSE);
}
References BITMAP, DB_GEN_C, OutputGenerator::dir(), DocBook, FALSE, OutputGenerator::fileName(), OutputGenerator::m_t, relPath, and DotDirDeps::writeGraph().
endDotGraph()
void DocbookGenerator::endDotGraph (DotClassGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 1303 of file docbookgen.cpp.
{
DB_GEN_C
  g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::DocBook,dir(),fileName(),relPath,TRUE,FALSE);
}
References BITMAP, DB_GEN_C, OutputGenerator::dir(), DocBook, FALSE, OutputGenerator::fileName(), OutputGenerator::m_t, relPath, TRUE, and DotClassGraph::writeGraph().
endDoxyAnchor()
void DocbookGenerator::endDoxyAnchor (const QCString & fileName, const QCString & anchor) override virtual
Implements OutputGenIntf.
Definition at line 955 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endEmphasis()
void DocbookGenerator::endEmphasis () inline override virtual
Implements OutputGenIntf.
Definition at line 164 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endExamples()
void DocbookGenerator::endExamples () override virtual
Implements OutputGenIntf.
Definition at line 1035 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</simplesect>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endFile()
void DocbookGenerator::endFile () override virtual
Implements OutputGenIntf.
Definition at line 423 of file docbookgen.cpp.
{
DB_GEN_C
  closeAllSections();
  m_inLevel = -1;
  m_inGroup = FALSE;
  // Write page links only after all sections have been closed to avoid bugs
  m_t << m_pageLinks;
  QCString fileType="section";
  QCString fileName= m_codeGen->sourceFileName();
  if (fileName == "index.xml")
  {
    fileType="book";
  }
  else if (fileName == "mainpage.xml")
  {
    fileType="chapter";
  }
  m_t << "</" << fileType << ">\n";
  endPlainFile();
  m_codeGen->setSourceFileName("");
}
References closeAllSections(), DB_GEN_C, endPlainFile(), FALSE, OutputGenerator::fileName(), m_codeGen, m_inGroup, m_inLevel, m_pageLinks, and OutputGenerator::m_t.
endGroupCollaboration()
void DocbookGenerator::endGroupCollaboration (DotGroupCollaboration & g) override virtual
Implements OutputGenIntf.
Definition at line 1294 of file docbookgen.cpp.
{
DB_GEN_C
  g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::DocBook,dir(),fileName(),relPath,FALSE);
}
References BITMAP, DB_GEN_C, OutputGenerator::dir(), DocBook, FALSE, OutputGenerator::fileName(), OutputGenerator::m_t, relPath, and DotGroupCollaboration::writeGraph().
endGroupHeader()
void DocbookGenerator::endGroupHeader (int) override virtual
Implements OutputGenIntf.
Definition at line 854 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</title>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endHeaderSection()
void DocbookGenerator::endHeaderSection () inline override virtual
Implements OutputGenIntf.
Definition at line 201 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endInclDepGraph()
void DocbookGenerator::endInclDepGraph (DotInclDepGraph & g) override virtual
Implements OutputGenIntf.
Definition at line 1312 of file docbookgen.cpp.
{
DB_GEN_C
  QCString fn = g.writeGraph(m_t,GraphOutputFormat::BITMAP,EmbeddedOutputFormat::DocBook,dir(),fileName(),relPath,FALSE);
}
References BITMAP, DB_GEN_C, OutputGenerator::dir(), DocBook, FALSE, OutputGenerator::fileName(), OutputGenerator::m_t, relPath, and DotInclDepGraph::writeGraph().
endIndent()
void DocbookGenerator::endIndent () inline override virtual
Implements OutputGenIntf.
Definition at line 247 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endIndexItem()
void DocbookGenerator::endIndexItem (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 150 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexKey()
void DocbookGenerator::endIndexKey () inline override virtual
Implements OutputGenIntf.
Definition at line 143 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexList()
void DocbookGenerator::endIndexList () inline override virtual
Implements OutputGenIntf.
Definition at line 141 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexListItem()
void DocbookGenerator::endIndexListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 139 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endIndexSection()
void DocbookGenerator::endIndexSection (IndexSection is) override virtual
Implements OutputGenIntf.
Definition at line 533 of file docbookgen.cpp.
{
DB_GEN_C2("IndexSection " << is)
  switch (is)
  {
    case IndexSection::isTitlePageStart:
      break;
    case IndexSection::isTitlePageAuthor:
      break;
    case IndexSection::isMainPage:
      {
        if (Doxygen::mainPage)
        {
          writePageLink(QCString("mainpage"), TRUE);
        }
      }
      break;
    case IndexSection::isModuleIndex:
      //m_t << "</chapter>\n";
      break;
    case IndexSection::isTopicIndex:
      //m_t << "</chapter>\n";
      break;
    case IndexSection::isDirIndex:
      //m_t << "<xi:include href=\"dirs.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case IndexSection::isNamespaceIndex:
      //m_t << "<xi:include href=\"namespaces.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case IndexSection::isConceptIndex:
      //m_t << "<xi:include href=\"concepts.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case IndexSection::isClassHierarchyIndex:
      //m_t << "<xi:include href=\"hierarchy.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case IndexSection::isCompoundIndex:
      //m_t << "</chapter>\n";
      break;
    case IndexSection::isFileIndex:
      //m_t << "<xi:include href=\"files.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case IndexSection::isPageIndex:
      //m_t << "<xi:include href=\"pages.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>";
      //m_t << "</chapter>\n";
      break;
    case IndexSection::isTopicDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &gd : *Doxygen::groupLinkedMap)
        {
          if (!gd->isReference() && !gd->isASubGroup())
          {
            writePageLink(gd->getOutputFileBase(), TRUE);
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case IndexSection::isModuleDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &mod : ModuleManager::instance().modules())
        {
          if (!mod->isReference() && mod->isPrimaryInterface())
          {
            writePageLink(mod->getOutputFileBase(), TRUE);
          }
        }
      }
      m_t << "</chapter>\n";
      break;
      break;
    case IndexSection::isDirDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &dd : *Doxygen::dirLinkedMap)
        {
          if (dd->isLinkableInProject())
          {
            m_t << "<    xi:include href=\"" << dd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case IndexSection::isNamespaceDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &nd : *Doxygen::namespaceLinkedMap)
        {
          if (nd->isLinkableInProject() && !nd->isAlias())
          {
            m_t << "<xi:include href=\"" << nd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case IndexSection::isConceptDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &cd : *Doxygen::conceptLinkedMap)
        {
          if (cd->isLinkableInProject() && !cd->isAlias())
          {
            m_t << "<xi:include href=\"" << cd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case IndexSection::isClassDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->isLinkableInProject() &&
              cd->templateMaster()==nullptr &&
             !cd->isEmbeddedInOuterScope() &&
             !cd->isAlias()
             )
          {
            m_t << "    <xi:include href=\"" << cd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case IndexSection::isFileDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &fn : *Doxygen::inputNameLinkedMap)
        {
          for (const auto &fd : *fn)
          {
            if (fd->isLinkableInProject())
            {
              m_t << "    <xi:include href=\"" << fd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
            }
            if (fd->generateSourceFile())
            {
              m_t << "    <xi:include href=\"" << fd->getSourceFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
            }
          }
        }
      }
      m_t << "</chapter>\n";
      break;
    case IndexSection::isExampleDocumentation:
      {
        m_t << "</title>\n";
        for (const auto &pd : *Doxygen::exampleLinkedMap)
        {
          m_t << "    <xi:include href=\"" << pd->getOutputFileBase() << ".xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n";
        }
      }
      m_t << "</chapter>\n";
      break;
    case IndexSection::isPageDocumentation:
        for (const auto &pd : *Doxygen::pageLinkedMap)
        {
          if (!pd->getGroupDef() && !pd->isReference() && !pd->hasParentPage()
            && Doxygen::mainPage.get() != pd.get())
          {
            writePageLink(pd->getOutputFileBase(), TRUE);
          }
        }
      break;
    case IndexSection::isPageDocumentation2:
      break;
    case IndexSection::isEndIndex:
      m_t << "<index/>\n";
      break;
  }
}
References Doxygen::classLinkedMap, Doxygen::conceptLinkedMap, DB_GEN_C2, Doxygen::dirLinkedMap, Doxygen::exampleLinkedMap, Doxygen::groupLinkedMap, Doxygen::inputNameLinkedMap, ModuleManager::instance(), isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, isTopicDocumentation, isTopicIndex, OutputGenerator::m_t, Doxygen::mainPage, Doxygen::namespaceLinkedMap, Doxygen::pageLinkedMap, TRUE, and writePageLink().
endIndexValue()
void DocbookGenerator::endIndexValue (const QCString & , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 145 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endInlineHeader()
void DocbookGenerator::endInlineHeader () inline override virtual
Implements OutputGenIntf.
Definition at line 211 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endInlineMemberDoc()
void DocbookGenerator::endInlineMemberDoc () override virtual
Implements OutputGenIntf.
Definition at line 1215 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</entry></row>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endInlineMemberName()
void DocbookGenerator::endInlineMemberName () override virtual
Implements OutputGenIntf.
Definition at line 1203 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endInlineMemberType()
void DocbookGenerator::endInlineMemberType () override virtual
Implements OutputGenIntf.
Definition at line 1191 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endItemList()
void DocbookGenerator::endItemList () inline override virtual
Implements OutputGenIntf.
Definition at line 147 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endItemListItem()
void DocbookGenerator::endItemListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 152 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endLabels()
void DocbookGenerator::endLabels () override virtual
Implements OutputGenIntf.
Definition at line 1023 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endMemberDeclaration()
void DocbookGenerator::endMemberDeclaration (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 242 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberDescription()
void DocbookGenerator::endMemberDescription () inline override virtual
Implements OutputGenIntf.
Definition at line 240 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberDoc()
void DocbookGenerator::endMemberDoc (bool) override virtual
Implements OutputGenIntf.
Definition at line 924 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</computeroutput></para>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberDocList()
void DocbookGenerator::endMemberDocList () override virtual
Implements OutputGenIntf.
Definition at line 1339 of file docbookgen.cpp.
{
DB_GEN_C
  m_inGroup = TRUE;
}
References DB_GEN_C, m_inGroup, and TRUE.
endMemberDocName()
void DocbookGenerator::endMemberDocName () override virtual
Implements OutputGenIntf.
Definition at line 968 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endMemberDocPrefixItem()
void DocbookGenerator::endMemberDocPrefixItem () override virtual
Implements OutputGenIntf.
Definition at line 1063 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</computeroutput>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberDocSimple()
void DocbookGenerator::endMemberDocSimple (bool) override virtual
Implements OutputGenIntf.
Definition at line 1176 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "    </tbody>\n";
  m_t << "    </tgroup>\n";
  m_t << "</table>\n";
  m_simpleTable = false;
}
References DB_GEN_C, m_simpleTable, and OutputGenerator::m_t.
endMemberGroup()
void DocbookGenerator::endMemberGroup (bool) override virtual
Implements OutputGenIntf.
Definition at line 986 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</simplesect>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberGroupDocs()
void DocbookGenerator::endMemberGroupDocs () inline override virtual
Implements OutputGenIntf.
Definition at line 223 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberGroupHeader()
void DocbookGenerator::endMemberGroupHeader () override virtual
Implements OutputGenIntf.
Definition at line 977 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</title>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberHeader()
void DocbookGenerator::endMemberHeader () override virtual
Implements OutputGenIntf.
Definition at line 761 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "    </title>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberItem()
void DocbookGenerator::endMemberItem (MemberItemType) override virtual
Implements OutputGenIntf.
Definition at line 818 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</para>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endMemberList()
void DocbookGenerator::endMemberList () override virtual
Implements OutputGenIntf.
Definition at line 801 of file docbookgen.cpp.
{
DB_GEN_C
  if (m_inListItem[m_levelListItem]) m_t << "</listitem>\n";
  m_inListItem[m_levelListItem] = FALSE;
  m_t << "        </itemizedlist>\n";
  m_levelListItem = (m_levelListItem> 0 ?  m_levelListItem - 1 : 0);
  if (m_inSimpleSect[m_levelListItem]) m_t << "</simplesect>\n";
  m_inSimpleSect[m_levelListItem] = FALSE;
}
References DB_GEN_C, FALSE, m_inListItem, m_inSimpleSect, m_levelListItem, and OutputGenerator::m_t.
endMemberSections()
void DocbookGenerator::endMemberSections () inline override virtual
Implements OutputGenIntf.
Definition at line 199 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberSubtitle()
void DocbookGenerator::endMemberSubtitle () inline override virtual
Implements OutputGenIntf.
Definition at line 205 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endMemberTemplateParams()
void DocbookGenerator::endMemberTemplateParams (const QCString & , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 1126 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</para>";
  m_t << "<para>";
}
References DB_GEN_C, and OutputGenerator::m_t.
endPageDoc()
void DocbookGenerator::endPageDoc () inline override virtual
Implements OutputGenIntf.
Definition at line 272 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
endPageRef()
void DocbookGenerator::endPageRef (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 194 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endParagraph()
void DocbookGenerator::endParagraph () override virtual
Implements OutputGenIntf.
Definition at line 743 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</para>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
endParameterDefVal()
void DocbookGenerator::endParameterDefVal () override virtual
Implements OutputGenIntf.
Definition at line 1115 of file docbookgen.cpp.
{
DB_GEN_C
  if (!m_denseText) m_t << "</computeroutput>\n";
}
References DB_GEN_C, m_denseText, and OutputGenerator::m_t.
endParameterExtra()
void DocbookGenerator::endParameterExtra (bool last, bool , bool closeBracket) override virtual
Implements OutputGenIntf.
Definition at line 1098 of file docbookgen.cpp.
{
DB_GEN_C
  if (last && closeBracket)
  {
    m_t << ")";
  }
}
References DB_GEN_C, and OutputGenerator::m_t.
endParameterList()
void DocbookGenerator::endParameterList () override virtual
Implements OutputGenIntf.
Definition at line 865 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endParameterName()
void DocbookGenerator::endParameterName () override virtual
Implements OutputGenIntf.
Definition at line 1088 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
endParameterType()
void DocbookGenerator::endParameterType () inline override virtual
Implements OutputGenIntf.
Definition at line 281 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endPlainFile()
void DocbookGenerator::endPlainFile () inline override virtual
Implements OutputGenIntf.
Definition at line 317 of file docbookgen.h.
{ OutputGenerator::endPlainFile(); }
References OutputGenerator::endPlainFile().
Referenced by endFile().
endProjectNumber()
void DocbookGenerator::endProjectNumber () inline override virtual
Implements OutputGenIntf.
Definition at line 134 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endQuickIndices()
void DocbookGenerator::endQuickIndices () inline override virtual
Implements OutputGenIntf.
Definition at line 263 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
endSection()
void DocbookGenerator::endSection (const QCString & , SectionType) override virtual
Implements OutputGenIntf.
Definition at line 1138 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</title>";
  closeSection();
}
References closeSection(), DB_GEN_C, and OutputGenerator::m_t.
endSmall()
void DocbookGenerator::endSmall () inline override virtual
Implements OutputGenIntf.
Definition at line 171 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endTextBlock()
void DocbookGenerator::endTextBlock (bool) override virtual
Implements OutputGenIntf.
Definition at line 898 of file docbookgen.cpp.
{
DB_GEN_C
  if (m_denseText)
  {
    m_denseText = FALSE;
    m_t << "</programlisting>";
  }
}
References DB_GEN_C, FALSE, m_denseText, and OutputGenerator::m_t.
endTextLink()
void DocbookGenerator::endTextLink () inline override virtual
Implements OutputGenIntf.
Definition at line 192 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
endTitleHead()
void DocbookGenerator::endTitleHead (const QCString & fileName, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 934 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</title>\n";
  if (!name.isEmpty()) addIndexTerm(m_t, name);
}
References addIndexTerm(), DB_GEN_C, QCString::isEmpty(), and OutputGenerator::m_t.
endTypewriter()
void DocbookGenerator::endTypewriter () override virtual
Implements OutputGenIntf.
Definition at line 884 of file docbookgen.cpp.
{
DB_GEN_C
  if (!m_denseText) m_t << "</computeroutput>\n";
}
References DB_GEN_C, m_denseText, and OutputGenerator::m_t.
exceptionEntry()
void DocbookGenerator::exceptionEntry (const QCString & prefix, bool closeBracket) override virtual
Implements OutputGenIntf.
Definition at line 1068 of file docbookgen.cpp.
{
DB_GEN_C
  if (!prefix.isEmpty())
  {
    m_t << " " << prefix << "(";
  }
  else if (closeBracket)
  {
    m_t << ")";
  }
  m_t << " ";
}
References DB_GEN_C, OutputGenerator::m_t, and prefix.
init()
void DocbookGenerator::init () static
Definition at line 373 of file docbookgen.cpp.
{
  QCString dir=Config_getString(DOCBOOK_OUTPUT);
  Dir d(dir.str());
  if (!d.exists() && !d.mkdir(dir.str()))
  {
    term("Could not create output directory %s\n",qPrint(dir));
  }
  createSubDirs(d);
}
References Config_getString, createSubDirs(), OutputGenerator::dir(), Dir::exists(), Dir::mkdir(), qPrint(), and term.
Referenced by generateOutput().
insertMemberAlign()
void DocbookGenerator::insertMemberAlign (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 226 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
insertMemberAlignLeft()
void DocbookGenerator::insertMemberAlignLeft (MemberItemType , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 227 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
lastIndexPage()
void DocbookGenerator::lastIndexPage () inline override virtual
Implements OutputGenIntf.
Definition at line 275 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
lineBreak()
void DocbookGenerator::lineBreak (const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 874 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<?linebreak?>";
}
References DB_GEN_C, and OutputGenerator::m_t.
openSection()
void DocbookGenerator::openSection (const QCString & attr = QCString()) private
Definition at line 1384 of file docbookgen.cpp.
{
   m_t << "<section";
   if (!attr.isEmpty()) m_t << " " << attr;
   m_t << ">\n";
   m_openSectionCount++;
}
References QCString::isEmpty(), m_openSectionCount, and OutputGenerator::m_t.
Referenced by startGroupHeader(), startMemberDoc(), and startSection().
operator=() [1/2]
DocbookGenerator & DocbookGenerator::operator= (const DocbookGenerator & og)
Definition at line 344 of file docbookgen.cpp.
{
  if (this!=&og)
  {
    m_dir              = og.m_dir;
    m_codeList         = std::make_unique<OutputCodeList>(*og.m_codeList);
    m_codeGen          = m_codeList->get<DocbookCodeGenerator>(OutputType::Docbook);
    m_codeGen->setTextStream(&m_t);
    m_denseText        = og.m_denseText;
    m_inGroup          = og.m_inGroup;
    m_levelListItem    = og.m_levelListItem;
    m_inListItem       = og.m_inListItem;
    m_inSimpleSect     = og.m_inSimpleSect;
    m_descTable        = og.m_descTable;
    m_simpleTable      = og.m_simpleTable;
    m_inLevel          = og.m_inLevel;
    m_firstMember      = og.m_firstMember;
    m_openSectionCount = og.m_openSectionCount;
  }
  return *this;
}
References Docbook, DocbookGenerator(), m_codeGen, m_codeList, m_denseText, m_descTable, OutputGenerator::m_dir, m_firstMember, m_inGroup, m_inLevel, m_inListItem, m_inSimpleSect, m_levelListItem, m_openSectionCount, m_simpleTable, and OutputGenerator::m_t.
operator=() [2/2]
DocbookGenerator & DocbookGenerator::operator= (DocbookGenerator &&) delete
References DocbookGenerator().
startAnonTypeScope()
void DocbookGenerator::startAnonTypeScope (int) inline override virtual
Implements OutputGenIntf.
Definition at line 212 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startBold()
void DocbookGenerator::startBold () override virtual
Implements OutputGenIntf.
Definition at line 823 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<emphasis role=\"strong\">";
}
References DB_GEN_C, and OutputGenerator::m_t.
startCallGraph()
void DocbookGenerator::startCallGraph () override virtual
Implements OutputGenIntf.
Definition at line 1317 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startCenter()
void DocbookGenerator::startCenter () inline override virtual
Implements OutputGenIntf.
Definition at line 168 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startClassDiagram()
void DocbookGenerator::startClassDiagram () override virtual
Implements OutputGenIntf.
Definition at line 991 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<para>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startCompoundTemplateParams()
void DocbookGenerator::startCompoundTemplateParams () override virtual
Implements OutputGenIntf.
Definition at line 1040 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<simplesect><title>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startConstraintDocs()
void DocbookGenerator::startConstraintDocs () override virtual
Implements OutputGenIntf.
Definition at line 1370 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startConstraintList()
void DocbookGenerator::startConstraintList (const QCString & header) override virtual
Implements OutputGenIntf.
Definition at line 1344 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<simplesect><title>";
  docify(header);
  m_t << "</title>\n";
}
References DB_GEN_C, docify(), and OutputGenerator::m_t.
startConstraintParam()
void DocbookGenerator::startConstraintParam () override virtual
Implements OutputGenIntf.
Definition at line 1351 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<para><emphasis role=\"strong\">";
}
References DB_GEN_C, and OutputGenerator::m_t.
startConstraintType()
void DocbookGenerator::startConstraintType () override virtual
Implements OutputGenIntf.
Definition at line 1360 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << ":";
}
References DB_GEN_C, and OutputGenerator::m_t.
startContents()
void DocbookGenerator::startContents () inline override virtual
Implements OutputGenIntf.
Definition at line 269 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startDescForItem()
void DocbookGenerator::startDescForItem () inline override virtual
Implements OutputGenIntf.
Definition at line 166 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startDescTable()
void DocbookGenerator::startDescTable (const QCString & title, const bool hasInits) override virtual
Implements OutputGenIntf.
Definition at line 1221 of file docbookgen.cpp.
{
DB_GEN_C
  int ncols = (hasInits?3:2);
  m_t << "<informaltable frame=\"all\">\n";
  if (!title.isEmpty()) m_t << "<title>" << convertToDocBook(title) << "</title>\n";
  m_t << "    <tgroup cols=\"" << ncols << "\" align=\"left\" colsep=\"1\" rowsep=\"1\">\n";
  int i = 1;
  m_t << "      <colspec colname='c" << i++ << "'/>\n";
  if (hasInits) m_t << "      <colspec colname='c" << i++ << "' align='right'/>\n";
  m_t << "      <colspec colname='c" << i++ << "'/>\n";
  m_t << "<tbody>\n";
  m_descTable = TRUE;
}
References convertToDocBook(), DB_GEN_C, QCString::isEmpty(), m_descTable, OutputGenerator::m_t, and TRUE.
startDescTableData()
void DocbookGenerator::startDescTableData () override virtual
Implements OutputGenIntf.
Definition at line 1279 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</entry><entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startDescTableInit()
void DocbookGenerator::startDescTableInit () override virtual
Implements OutputGenIntf.
Definition at line 1268 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "</entry><entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startDescTableRow()
void DocbookGenerator::startDescTableRow () override virtual
Implements OutputGenIntf.
Definition at line 1245 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<row>";
  m_t << "<entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startDescTableTitle()
void DocbookGenerator::startDescTableTitle () override virtual
Implements OutputGenIntf.
Definition at line 1258 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startDirDepGraph()
void DocbookGenerator::startDirDepGraph () override virtual
Implements OutputGenIntf.
Definition at line 1326 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startDotGraph()
void DocbookGenerator::startDotGraph () override virtual
Implements OutputGenIntf.
Definition at line 1299 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startDoxyAnchor()
void DocbookGenerator::startDoxyAnchor (const QCString & fName, const QCString & manName, const QCString & anchor, const QCString & name, const QCString & args) override virtual
Implements OutputGenIntf.
Definition at line 940 of file docbookgen.cpp.
{
DB_GEN_C
  if (!m_inListItem[m_levelListItem] && !m_descTable && !m_simpleTable)
  {
    if (!m_firstMember) closeSection();
    m_firstMember = FALSE;
  }
  if (!anchor.isEmpty())
  {
    m_t << "<anchor xml:id=\"_" << stripPath(fName) << "_1" << anchor << "\"/>";
  }
}
References closeSection(), DB_GEN_C, FALSE, QCString::isEmpty(), m_descTable, m_firstMember, m_inListItem, m_levelListItem, m_simpleTable, OutputGenerator::m_t, and stripPath().
startEmphasis()
void DocbookGenerator::startEmphasis () inline override virtual
Implements OutputGenIntf.
Definition at line 163 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startExamples()
void DocbookGenerator::startExamples () override virtual
Implements OutputGenIntf.
Definition at line 1027 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<simplesect><title>";
  docify(theTranslator->trExamples());
  m_t << "</title>";
}
References DB_GEN_C, docify(), OutputGenerator::m_t, theTranslator, and Translator::trExamples().
startFile()
void DocbookGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id, int hierarchyLevel) override virtual
Implements OutputGenIntf.
Definition at line 392 of file docbookgen.cpp.
{
DB_GEN_C
  QCString fileName=name;
  QCString pageName;
  QCString fileType="section";
  if (fileName == "refman")
  {
    fileName="index";
    fileType="book";
  }
  else if (fileName == "index")
  {
    fileName="mainpage";
    fileType="chapter";
  }
  pageName = fileName;
  relPath = relativePathToRoot(fileName);
  if (!fileName.endsWith(".xml")) fileName+=".xml";
  startPlainFile(fileName);
  m_codeGen->setRelativePath(relPath);
  m_codeGen->setSourceFileName(stripPath(fileName));
  m_pageLinks = QCString();
  m_t << "<?xml version='1.0' encoding='UTF-8' standalone='no'?>\n";
  m_t << "<" << fileType << " xmlns=\"http://docbook.org/ns/docbook\" version=\"5.0\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"";
  if (!pageName.isEmpty()) m_t << " xml:id=\"_" <<  stripPath(pageName) << "\"";
  m_t << " xml:lang=\"" << theTranslator->trISOLang() << "\"";
  m_t << ">\n";
}
References DB_GEN_C, OutputGenerator::fileName(), QCString::isEmpty(), m_codeGen, m_pageLinks, OutputGenerator::m_t, relativePathToRoot(), relPath, startPlainFile(), stripPath(), theTranslator, and Translator::trISOLang().
startGroupCollaboration()
void DocbookGenerator::startGroupCollaboration () override virtual
Implements OutputGenIntf.
Definition at line 1290 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startGroupHeader()
void DocbookGenerator::startGroupHeader (int extraIndentLevel) override virtual
Implements OutputGenIntf.
Definition at line 833 of file docbookgen.cpp.
{
DB_GEN_C2("m_inLevel " << m_inLevel)
DB_GEN_C2("extraIndentLevel " << extraIndentLevel)
  m_firstMember = TRUE;
  if (m_inSimpleSect[m_levelListItem]) m_t << "</simplesect>\n";
  m_inSimpleSect[m_levelListItem] = FALSE;
  if (m_inLevel != -1) m_inGroup = TRUE;
  if (m_inLevel == extraIndentLevel) closeSection();
  m_inLevel = extraIndentLevel;
  openSection();
  m_t << "<title>";
}
References closeSection(), DB_GEN_C2, FALSE, m_firstMember, m_inGroup, m_inLevel, m_inSimpleSect, m_levelListItem, OutputGenerator::m_t, openSection(), and TRUE.
startHeaderSection()
void DocbookGenerator::startHeaderSection () inline override virtual
Implements OutputGenIntf.
Definition at line 200 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startInclDepGraph()
void DocbookGenerator::startInclDepGraph () override virtual
Implements OutputGenIntf.
Definition at line 1308 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startIndent()
void DocbookGenerator::startIndent () inline override virtual
Implements OutputGenIntf.
Definition at line 246 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startIndexItem()
void DocbookGenerator::startIndexItem (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 149 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexKey()
void DocbookGenerator::startIndexKey () inline override virtual
Implements OutputGenIntf.
Definition at line 142 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexList()
void DocbookGenerator::startIndexList () inline override virtual
Implements OutputGenIntf.
Definition at line 140 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexListItem()
void DocbookGenerator::startIndexListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 138 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startIndexSection()
void DocbookGenerator::startIndexSection (IndexSection is) override virtual
Implements OutputGenIntf.
Definition at line 448 of file docbookgen.cpp.
{
DB_GEN_C2("IndexSection " << is)
  switch (is)
  {
    case IndexSection::isTitlePageStart:
      {
        QCString dbk_projectName = Config_getString(PROJECT_NAME);
        m_t << "    <info>\n";
        m_t << "    <title>" << convertToDocBook(dbk_projectName) << "</title>\n";
        m_t << "    </info>\n";
      }
      break;
    case IndexSection::isTitlePageAuthor:
      break;
    case IndexSection::isMainPage:
      break;
    case IndexSection::isModuleIndex:
      //Module Index\n"
      break;
    case IndexSection::isTopicIndex:
      //Module Index\n"
      break;
    case IndexSection::isDirIndex:
      //Directory Index\n"
      break;
    case IndexSection::isNamespaceIndex:
      //Namespace Index\n"
      break;
    case IndexSection::isConceptIndex:
      //Concept Index\n"
      break;
    case IndexSection::isClassHierarchyIndex:
      //Hierarchical Index\n"
      break;
    case IndexSection::isCompoundIndex:
      //m_t << "{"; //Class Index}\n"
      break;
    case IndexSection::isFileIndex:
      //Annotated File Index\n"
      break;
    case IndexSection::isPageIndex:
      //Annotated Page Index\n"
      break;
    case IndexSection::isModuleDocumentation:
      m_t << "<chapter>\n";
      m_t << "    <title>";
      break;
    case IndexSection::isTopicDocumentation:
      m_t << "<chapter>\n";
      m_t << "    <title>";
      break;
    case IndexSection::isDirDocumentation:
      m_t << "<chapter>\n";
      m_t << "    <title>";
      break;
    case IndexSection::isNamespaceDocumentation:
      m_t << "<chapter>\n";
      m_t << "    <title>";
      break;
    case IndexSection::isConceptDocumentation:
      m_t << "<chapter>\n";
      m_t << "    <title>";
      break;
    case IndexSection::isClassDocumentation:
      m_t << "<chapter>\n";
      m_t << "    <title>";
      break;
    case IndexSection::isFileDocumentation:
      m_t << "<chapter>\n";
      m_t << "    <title>";
      break;
    case IndexSection::isExampleDocumentation:
      m_t << "<chapter>\n";
      m_t << "    <title>";
      break;
    case IndexSection::isPageDocumentation:
      break;
    case IndexSection::isPageDocumentation2:
      break;
    case IndexSection::isEndIndex:
      break;
  }
}
References Config_getString, convertToDocBook(), DB_GEN_C2, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, isTopicDocumentation, isTopicIndex, and OutputGenerator::m_t.
startIndexValue()
void DocbookGenerator::startIndexValue (bool) inline override virtual
Implements OutputGenIntf.
Definition at line 144 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startInlineHeader()
void DocbookGenerator::startInlineHeader () inline override virtual
Implements OutputGenIntf.
Definition at line 210 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startInlineMemberDoc()
void DocbookGenerator::startInlineMemberDoc () override virtual
Implements OutputGenIntf.
Definition at line 1209 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startInlineMemberName()
void DocbookGenerator::startInlineMemberName () override virtual
Implements OutputGenIntf.
Definition at line 1197 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startInlineMemberType()
void DocbookGenerator::startInlineMemberType () override virtual
Implements OutputGenIntf.
Definition at line 1185 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<row><entry>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startItemList()
void DocbookGenerator::startItemList () inline override virtual
Implements OutputGenIntf.
Definition at line 146 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startItemListItem()
void DocbookGenerator::startItemListItem () inline override virtual
Implements OutputGenIntf.
Definition at line 151 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startLabels()
void DocbookGenerator::startLabels () override virtual
Implements OutputGenIntf.
Definition at line 1011 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startMemberDeclaration()
void DocbookGenerator::startMemberDeclaration () inline override virtual
Implements OutputGenIntf.
Definition at line 241 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberDescription()
void DocbookGenerator::startMemberDescription (const QCString & , const QCString & , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 239 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberDoc()
void DocbookGenerator::startMemberDoc (const QCString & clname, const QCString & memname, const QCString & , const QCString & title, int memCount, int memTotal, bool) override virtual
Implements OutputGenIntf.
Definition at line 907 of file docbookgen.cpp.
{
DB_GEN_C2("m_inLevel " << m_inLevel)
  openSection();
  m_t << "    <title>" << convertToDocBook(title);
  if (memTotal>1)
  {
    m_t << "<computeroutput>[" << memCount << "/" << memTotal << "]</computeroutput>";
  }
  m_t << "</title>\n";
  if (!memname.isEmpty() && memname[0]!='@')
  {
    addIndexTerm(m_t,memname,clname);
    addIndexTerm(m_t,clname,memname);
  }
}
References addIndexTerm(), convertToDocBook(), DB_GEN_C2, QCString::isEmpty(), m_inLevel, OutputGenerator::m_t, and openSection().
startMemberDocList()
void DocbookGenerator::startMemberDocList () override virtual
Implements OutputGenIntf.
Definition at line 1335 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startMemberDocName()
void DocbookGenerator::startMemberDocName (bool) override virtual
Implements OutputGenIntf.
Definition at line 963 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<para><computeroutput>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startMemberDocPrefixItem()
void DocbookGenerator::startMemberDocPrefixItem () override virtual
Implements OutputGenIntf.
Definition at line 1058 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<computeroutput>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startMemberDocSimple()
void DocbookGenerator::startMemberDocSimple (bool isEnum) override virtual
Implements OutputGenIntf.
Definition at line 1150 of file docbookgen.cpp.
{
DB_GEN_C
  int ncols=0;
  QCString title;
  if (isEnum)
  {
    ncols = 2;
    title = theTranslator->trEnumerationValues();
  }
  else
  {
    ncols = 3;
    title = theTranslator->trCompoundMembers();
  }
  m_t << "<table frame=\"all\">\n";
  if (!title.isEmpty()) m_t << "<title>" << convertToDocBook(title) << "</title>\n";
  m_t << "    <tgroup cols=\"" << ncols << "\" align=\"left\" colsep=\"1\" rowsep=\"1\">\n";
  for (int i = 0; i < ncols; i++)
  {
    m_t << "      <colspec colname='c" << i+1 << "'/>\n";
  }
  m_t << "<tbody>\n";
  m_simpleTable = true;
}
References convertToDocBook(), DB_GEN_C, QCString::isEmpty(), m_simpleTable, OutputGenerator::m_t, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberGroup()
void DocbookGenerator::startMemberGroup () override virtual
Implements OutputGenIntf.
Definition at line 982 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startMemberGroupDocs()
void DocbookGenerator::startMemberGroupDocs () inline override virtual
Implements OutputGenIntf.
Definition at line 222 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberGroupHeader()
void DocbookGenerator::startMemberGroupHeader (bool) override virtual
Implements OutputGenIntf.
Definition at line 972 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<simplesect><title>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startMemberHeader()
void DocbookGenerator::startMemberHeader (const QCString & anchor, int typ) override virtual
Implements OutputGenIntf.
Definition at line 753 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<simplesect>\n";
  m_inSimpleSect[m_levelListItem] = TRUE;
  m_t << "    <title>";
}
References DB_GEN_C, m_inSimpleSect, m_levelListItem, OutputGenerator::m_t, and TRUE.
startMemberItem()
void DocbookGenerator::startMemberItem (const QCString & , MemberItemType , const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 811 of file docbookgen.cpp.
{
DB_GEN_C
  if (m_inListItem[m_levelListItem]) m_t << "</listitem>\n";
  m_t << "            <listitem><para>";
  m_inListItem[m_levelListItem] = TRUE;
}
References DB_GEN_C, m_inListItem, m_levelListItem, OutputGenerator::m_t, and TRUE.
startMemberList()
void DocbookGenerator::startMemberList () override virtual
Implements OutputGenIntf.
Definition at line 795 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "        <itemizedlist>\n";
  m_levelListItem++;
}
References DB_GEN_C, m_levelListItem, and OutputGenerator::m_t.
startMemberSections()
void DocbookGenerator::startMemberSections () inline override virtual
Implements OutputGenIntf.
Definition at line 198 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberSubtitle()
void DocbookGenerator::startMemberSubtitle () inline override virtual
Implements OutputGenIntf.
Definition at line 204 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startMemberTemplateParams()
void DocbookGenerator::startMemberTemplateParams () override virtual
Implements OutputGenIntf.
Definition at line 1121 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startPageDoc()
void DocbookGenerator::startPageDoc (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 271 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
startPageRef()
void DocbookGenerator::startPageRef () inline override virtual
Implements OutputGenIntf.
Definition at line 193 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startParagraph()
void DocbookGenerator::startParagraph (const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 737 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<para>\n";
}
References DB_GEN_C, and OutputGenerator::m_t.
startParameterDefVal()
void DocbookGenerator::startParameterDefVal (const char * sep) override virtual
Implements OutputGenIntf.
Definition at line 1108 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << sep;
  if (!m_denseText) m_t << "<computeroutput>";
}
References DB_GEN_C, m_denseText, and OutputGenerator::m_t.
startParameterExtra()
void DocbookGenerator::startParameterExtra () override virtual
Implements OutputGenIntf.
Definition at line 1093 of file docbookgen.cpp.
{
DB_GEN_C
}
References DB_GEN_C.
startParameterList()
void DocbookGenerator::startParameterList (bool openBracket) override virtual
Implements OutputGenIntf.
Definition at line 860 of file docbookgen.cpp.
{
DB_GEN_C
  if (openBracket) m_t << "(";
}
References DB_GEN_C, and OutputGenerator::m_t.
startParameterName()
void DocbookGenerator::startParameterName (bool) override virtual
Implements OutputGenIntf.
Definition at line 1082 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << " ";
}
References DB_GEN_C, and OutputGenerator::m_t.
startParameterType()
void DocbookGenerator::startParameterType (bool , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 280 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startPlainFile()
void DocbookGenerator::startPlainFile (const QCString & name) inline override virtual
Implements OutputGenIntf.
Definition at line 316 of file docbookgen.h.
{ OutputGenerator::startPlainFile(name); }
References OutputGenerator::startPlainFile().
Referenced by startFile().
startProjectNumber()
void DocbookGenerator::startProjectNumber () inline override virtual
Implements OutputGenIntf.
Definition at line 133 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startQuickIndices()
void DocbookGenerator::startQuickIndices () inline override virtual
Implements OutputGenIntf.
Definition at line 262 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
startSection()
void DocbookGenerator::startSection (const QCString & lab, const QCString & , SectionType) override virtual
Implements OutputGenIntf.
Definition at line 1132 of file docbookgen.cpp.
{
DB_GEN_C
  openSection("xml:id=\"_" + stripPath(lab) + "\"");
  m_t << "<title>";
}
References DB_GEN_C, OutputGenerator::m_t, openSection(), and stripPath().
startSmall()
void DocbookGenerator::startSmall () inline override virtual
Implements OutputGenIntf.
Definition at line 170 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startTextBlock()
void DocbookGenerator::startTextBlock (bool dense) override virtual
Implements OutputGenIntf.
Definition at line 889 of file docbookgen.cpp.
{
DB_GEN_C
  if (dense)
  {
    m_denseText = TRUE;
    m_t << "<programlisting linenumbering=\"unnumbered\">";
  }
}
References DB_GEN_C, m_denseText, OutputGenerator::m_t, and TRUE.
startTextLink()
void DocbookGenerator::startTextLink (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 191 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
startTitleHead()
void DocbookGenerator::startTitleHead (const QCString &) override virtual
Implements OutputGenIntf.
Definition at line 929 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<title>";
}
References DB_GEN_C, and OutputGenerator::m_t.
startTypewriter()
void DocbookGenerator::startTypewriter () override virtual
Implements OutputGenIntf.
Definition at line 879 of file docbookgen.cpp.
{
DB_GEN_C
  if (!m_denseText) m_t << "<computeroutput>";
}
References DB_GEN_C, m_denseText, and OutputGenerator::m_t.
type()
OutputType DocbookGenerator::type () const inline override virtual
Implements OutputGenIntf.
Definition at line 120 of file docbookgen.h.
{ return OutputType::Docbook; }
References Docbook.
Referenced by writeLocalToc().
writeAnchor()
void DocbookGenerator::writeAnchor (const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 174 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeChar()
void DocbookGenerator::writeChar (char c) override virtual
Implements OutputGenIntf.
Definition at line 1050 of file docbookgen.cpp.
{
DB_GEN_C
  char cs[2];
  cs[0]=c;
  cs[1]=0;
  docify(cs);
}
References DB_GEN_C, and docify().
writeDoc()
void DocbookGenerator::writeDoc (const IDocNodeAST * node, const Definition * ctx, const MemberDef * md, int id) override virtual
Implements OutputGenIntf.
Definition at line 726 of file docbookgen.cpp.
{
DB_GEN_C
  auto astImpl = dynamic_cast<const DocNodeAST*>(ast);
  if (astImpl)
  {
    DocbookDocVisitor visitor(m_t,*m_codeList,ctx?ctx->getDefFileExtension():QCString());
    std::visit(visitor,astImpl->root);
  }
}
References DB_GEN_C, Definition::getDefFileExtension(), m_codeList, and OutputGenerator::m_t.
writeFooter()
void DocbookGenerator::writeFooter (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 129 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeGraphicalHierarchy()
void DocbookGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) inline override virtual
Implements OutputGenIntf.
Definition at line 261 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeInheritedSectionTitle()
void DocbookGenerator::writeInheritedSectionTitle (const QCString & , const QCString & ref, const QCString & file, const QCString & anchor, const QCString & title, const QCString & name) override virtual
Implements OutputGenIntf.
Definition at line 1406 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << theTranslator->trInheritedFrom(convertToDocBook(title), objectLinkToString(ref, file, anchor, name));
}
References convertToDocBook(), DB_GEN_C, OutputGenerator::m_t, objectLinkToString(), theTranslator, and Translator::trInheritedFrom().
writeLabel()
void DocbookGenerator::writeLabel (const QCString & l, bool isLast) override virtual
Implements OutputGenIntf.
Definition at line 1016 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << "<computeroutput>[" << l << "]</computeroutput>";
  if (!isLast) m_t << ", ";
}
References DB_GEN_C, and OutputGenerator::m_t.
writeLatexSpacing()
void DocbookGenerator::writeLatexSpacing () inline override virtual
Implements OutputGenIntf.
Definition at line 236 of file docbookgen.h.
{DB_GEN_EMPTY}
References DB_GEN_EMPTY.
writeLocalToc()
void DocbookGenerator::writeLocalToc (const SectionRefs & sr, const LocalToc & lt) override virtual
Implements OutputGenIntf.
Definition at line 1415 of file docbookgen.cpp.
{
  if (localToc.isDocbookEnabled())
  {
    m_t << "    <toc>\n";
    m_t << "    <title>" << theTranslator->trRTFTableOfContents() << "</title>\n";
    int level=1;
    int maxLevel = localToc.docbookLevel();
    BoolVector inLi(maxLevel+1,false);
    for (const SectionInfo *si : sectionRefs)
    {
      SectionType type = si->type();
      if (type.isSection())
      {
        //printf("  level=%d title=%s\n",level,qPrint(si->title));
        int nextLevel = type.level();
        if (nextLevel>level)
        {
          for (int l=level;l<nextLevel;l++)
          {
            if (l < maxLevel) m_t << "    <tocdiv>\n";
          }
        }
        else if (nextLevel<level)
        {
          for (int l=level;l>nextLevel;l--)
          {
            inLi[l]=FALSE;
            if (l <= maxLevel) m_t << "    </tocdiv>\n";
          }
        }
        if (nextLevel <= maxLevel)
        {
          QCString titleDoc = convertToDocBook(si->title());
          QCString label    = convertToDocBook(si->label());
          if (titleDoc.isEmpty()) titleDoc = label;
          m_t << "      <tocentry>" << titleDoc << "</tocentry>\n";
        }
        inLi[nextLevel]=TRUE;
        level = nextLevel;
      }
    }
    if (level > maxLevel) level = maxLevel;
    while (level>1 && level <= maxLevel)
    {
      inLi[level]=FALSE;
      m_t << "</tocdiv>\n";
      level--;
    }
    m_t << "    </toc>\n";
  }
}
References convertToDocBook(), LocalToc::docbookLevel(), FALSE, LocalToc::isDocbookEnabled(), QCString::isEmpty(), OutputGenerator::m_t, theTranslator, Translator::trRTFTableOfContents(), TRUE, and type().
writeLogo()
void DocbookGenerator::writeLogo () inline override virtual
Implements OutputGenIntf.
Definition at line 266 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeNavigationPath()
void DocbookGenerator::writeNavigationPath (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 265 of file docbookgen.h.
{DB_GEN_NEW};
References DB_GEN_NEW.
writeNonBreakableSpace()
void DocbookGenerator::writeNonBreakableSpace (int n) override virtual
Implements OutputGenIntf.
Definition at line 869 of file docbookgen.cpp.
{
DB_GEN_C
  for (int i=0;i<n;i++) m_t << "&#160;";
}
References DB_GEN_C, and OutputGenerator::m_t.
writeObjectLink()
void DocbookGenerator::writeObjectLink (const QCString & ref, const QCString & f, const QCString & anchor, const QCString & text) override virtual
Implements OutputGenIntf.
Definition at line 789 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << objectLinkToString(ref,f,anchor,text);
}
References DB_GEN_C, OutputGenerator::m_t, and objectLinkToString().
writePageLink()
void DocbookGenerator::writePageLink (const QCString & name, bool first) override virtual
Implements OutputGenIntf.
Definition at line 713 of file docbookgen.cpp.
{
DB_GEN_C
  QCString link;
  link.sprintf("    <xi:include href=\"%s.xml\" xmlns:xi=\"http://www.w3.org/2001/XInclude\"/>\n",
               name.data());
  if (first)
    m_t << link;
  else
    // Buffer page links and write them after all sections are closed
    m_pageLinks += link;
}
References QCString::data(), DB_GEN_C, m_pageLinks, and OutputGenerator::m_t.
Referenced by endIndexSection().
writeQuickLinks()
void DocbookGenerator::writeQuickLinks (HighlightedItem , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 267 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeRuler()
void DocbookGenerator::writeRuler () override virtual
Implements OutputGenIntf.
Definition at line 846 of file docbookgen.cpp.
{
DB_GEN_C2("m_inLevel " << m_inLevel)
DB_GEN_C2("m_inGroup " << m_inGroup)
  if (m_inGroup) closeSection();
  m_inGroup = FALSE;
}
References closeSection(), DB_GEN_C2, FALSE, m_inGroup, and m_inLevel.
writeSearchInfo()
void DocbookGenerator::writeSearchInfo () inline override virtual
Implements OutputGenIntf.
Definition at line 128 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeSplitBar()
void DocbookGenerator::writeSplitBar (const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 264 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeStartAnnoItem()
void DocbookGenerator::writeStartAnnoItem (const QCString & , const QCString & , const QCString & , const QCString &) inline override virtual
Implements OutputGenIntf.
Definition at line 237 of file docbookgen.h.
                                                                        {DB_GEN_NEW};
References DB_GEN_NEW.
writeString()
void DocbookGenerator::writeString (const QCString & text) override virtual
Implements OutputGenIntf.
Definition at line 748 of file docbookgen.cpp.
{
DB_GEN_C
  m_t << text;
}
References DB_GEN_C, and OutputGenerator::m_t.
writeStyleInfo()
void DocbookGenerator::writeStyleInfo (int) inline override virtual
Implements OutputGenIntf.
Definition at line 135 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeSummaryLink()
void DocbookGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) inline override virtual
Implements OutputGenIntf.
Definition at line 268 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
writeSynopsis()
void DocbookGenerator::writeSynopsis () inline override virtual
Implements OutputGenIntf.
Definition at line 248 of file docbookgen.h.
{DB_GEN_EMPTY};
References DB_GEN_EMPTY.
Member Data Documentation
m_codeGen
DocbookCodeGenerator* DocbookGenerator::m_codeGen = nullptr private
Definition at line 326 of file docbookgen.h.
Referenced by addCodeGen(), DocbookGenerator(), DocbookGenerator(), endFile(), operator=(), and startFile().
m_codeList
std::unique_ptr<OutputCodeList> DocbookGenerator::m_codeList private
Definition at line 325 of file docbookgen.h.
Referenced by DocbookGenerator(), DocbookGenerator(), operator=(), and writeDoc().
m_denseText
bool DocbookGenerator::m_denseText = false private
Definition at line 327 of file docbookgen.h.
Referenced by DocbookGenerator(), endParameterDefVal(), endTextBlock(), endTypewriter(), operator=(), startParameterDefVal(), startTextBlock(), and startTypewriter().
m_descTable
bool DocbookGenerator::m_descTable = false private
Definition at line 332 of file docbookgen.h.
Referenced by DocbookGenerator(), endDescTable(), operator=(), startDescTable(), and startDoxyAnchor().
m_firstMember
bool DocbookGenerator::m_firstMember = false private
Definition at line 335 of file docbookgen.h.
Referenced by DocbookGenerator(), operator=(), startDoxyAnchor(), and startGroupHeader().
m_inGroup
bool DocbookGenerator::m_inGroup = false private
Definition at line 328 of file docbookgen.h.
Referenced by DocbookGenerator(), endFile(), endMemberDocList(), operator=(), startGroupHeader(), and writeRuler().
m_inLevel
int DocbookGenerator::m_inLevel = -1 private
Definition at line 334 of file docbookgen.h.
Referenced by DocbookGenerator(), endFile(), operator=(), startGroupHeader(), startMemberDoc(), and writeRuler().
m_inListItem
std::array<bool,20> DocbookGenerator::m_inListItem = { false, } private
Definition at line 330 of file docbookgen.h.
{ false, };
Referenced by DocbookGenerator(), endMemberList(), operator=(), startDoxyAnchor(), and startMemberItem().
m_inSimpleSect
std::array<bool,20> DocbookGenerator::m_inSimpleSect = { false, } private
Definition at line 331 of file docbookgen.h.
{ false, };
Referenced by DocbookGenerator(), endMemberList(), operator=(), startGroupHeader(), and startMemberHeader().
m_levelListItem
int DocbookGenerator::m_levelListItem = 0 private
Definition at line 329 of file docbookgen.h.
Referenced by DocbookGenerator(), endMemberList(), operator=(), startDoxyAnchor(), startGroupHeader(), startMemberHeader(), startMemberItem(), and startMemberList().
m_openSectionCount
int DocbookGenerator::m_openSectionCount = 0 private
Definition at line 336 of file docbookgen.h.
Referenced by closeAllSections(), closeSection(), DocbookGenerator(), openSection(), and operator=().
m_pageLinks
QCString DocbookGenerator::m_pageLinks private
Definition at line 337 of file docbookgen.h.
Referenced by endFile(), startFile(), and writePageLink().
m_simpleTable
bool DocbookGenerator::m_simpleTable = false private
Definition at line 333 of file docbookgen.h.
Referenced by DocbookGenerator(), endMemberDocSimple(), operator=(), startDoxyAnchor(), and startMemberDocSimple().
relPath
QCString DocbookGenerator::relPath private
Definition at line 324 of file docbookgen.h.
Referenced by endCallGraph(), endClassDiagram(), endDirDepGraph(), endDotGraph(), endGroupCollaboration(), endInclDepGraph(), and startFile().
The documentation for this class was generated from the following files:
src/docbookgen.h
src/docbookgen.cpp