Doxygen: /home/runner/work/doxygen/doxygen/src/docbookgen.h File Reference
docbookgen.h File Reference
#include <memory>
#include <array>
#include "config.h"
#include "outputgen.h"
Classes
class DocbookCodeGenerator
class DocbookGenerator
Macros
#define DB_GEN_EMPTY
#define DB_GEN_H
#define DB_GEN_H1(x)
#define DB_GEN_H2(y)
#define DB_GEN_H2a(x, y)
#define DB_GEN_NEW
Functions
QCString convertToDocBook (const QCString &s, const bool retainNewline=false)
Macro Definition Documentation
DB_GEN_EMPTY
#define DB_GEN_EMPTY
Definition at line 26 of file docbookgen.h.
DB_GEN_H
#define DB_GEN_H
Definition at line 38 of file docbookgen.h.
DB_GEN_H1
#define DB_GEN_H1 (x)
Definition at line 39 of file docbookgen.h.
DB_GEN_H2
#define DB_GEN_H2 (y)
Definition at line 40 of file docbookgen.h.
DB_GEN_H2a
#define DB_GEN_H2a (x, y)
Definition at line 41 of file docbookgen.h.
DB_GEN_NEW
#define DB_GEN_NEW
Definition at line 42 of file docbookgen.h.
Function Documentation
convertToDocBook()
QCString convertToDocBook (const QCString & s, const bool retainNewline)
Converts a string to an DocBook-encoded string
Definition at line 1386 of file docbookgen.cpp.
{
  if (s.isEmpty()) return s;
  GrowBuf growBuf;
  const char *q;
  int cnt;
  const char *p=s.data();
  char c;
  while ((c=*p++))
  {
    switch (c)
    {
      case '\n': if (retainNewline) growBuf.addStr("<literallayout>&#160;&#xa;</literallayout>"); growBuf.addChar(c);   break;
      case '<':  growBuf.addStr("&lt;");   break;
      case '>':  growBuf.addStr("&gt;");   break;
      case '&':  // possibility to have a special symbol
        q = p;
        cnt = 2; // we have to count & and ; as well
        while ((*q >= 'a' && *q <= 'z') || (*q >= 'A' && *q <= 'Z') || (*q >= '0' && *q <= '9'))
        {
          cnt++;
          q++;
        }
        if (*q == ';')
        {
           --p; // we need & as well
           HtmlEntityMapper::SymType res = HtmlEntityMapper::instance().name2sym(QCString(p).left(cnt));
           if (res == HtmlEntityMapper::Sym_Unknown)
           {
             p++;
             growBuf.addStr("&amp;");
           }
           else
           {
             growBuf.addStr(HtmlEntityMapper::instance().docbook(res));
             q++;
             p = q;
           }
        }
        else
        {
          growBuf.addStr("&amp;");
        }
        break;
      case '\'': growBuf.addStr("&apos;"); break;
      case '"':  growBuf.addStr("&quot;"); break;
      case  1: case  2: case  3: case  4: case  5: case  6: case 7:  case  8:
      case 11: case 12: case 14: case 15: case 16: case 17: case 18:
      case 19: case 20: case 21: case 22: case 23: case 24: case 25: case 26:
      case 27: case 28: case 29: case 30: case 31:
        growBuf.addStr("&#x24");
        growBuf.addChar(hex[static_cast<uint8_t>(c)>>4]);
        growBuf.addChar(hex[static_cast<uint8_t>(c)&0xF]);
        growBuf.addChar(';');
        break;
      default:
        growBuf.addChar(c);
        break;
    }
  }
  growBuf.addChar(0);
  return growBuf.get();
}
References GrowBuf::addChar(), GrowBuf::addStr(), QCString::data(), GrowBuf::get(), hex, HtmlEntityMapper::instance(), QCString::isEmpty(), HtmlEntityMapper::name2sym(), and HtmlEntityMapper::Sym_Unknown.
Referenced by addIndexTerm(), DocbookGenerator::docify(), DocbookDocVisitor::filter(), objectLinkToString(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocbookGenerator::startDescTable(), DocbookGenerator::startIndexSection(), DocbookGenerator::startMemberDoc(), DocbookGenerator::startMemberDocSimple(), DocbookDocVisitor::visitPreStart(), writeDocbookString(), DocbookGenerator::writeInheritedSectionTitle(), and DocbookGenerator::writeLocalToc().