Doxygen: /home/runner/work/doxygen/doxygen/src/vhdldocgen.cpp File Reference
vhdldocgen.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <map>
#include <algorithm>
#include "qcstring.h"
#include "vhdldocgen.h"
#include "message.h"
#include "config.h"
#include "doxygen.h"
#include "util.h"
#include "language.h"
#include "commentscan.h"
#include "definition.h"
#include "searchindex.h"
#include "outputlist.h"
#include "parserintf.h"
#include "layout.h"
#include "arguments.h"
#include "portable.h"
#include "memberlist.h"
#include "memberdef.h"
#include "groupdef.h"
#include "classlist.h"
#include "namespacedef.h"
#include "filename.h"
#include "membergroup.h"
#include "membername.h"
#include "plantuml.h"
#include "vhdljjparser.h"
#include "VhdlParser.h"
#include "regex.h"
#include "textstream.h"
Macros
#define theTranslator_vhdlType theTranslator->trVhdlType
#define STARTL
#define DECLN
#define STARTFIN (FlowChart::START_NO | FlowChart::END_NO)
#define LOOP
#define ENDCL (FlowChart::END_CASE | FlowChart::END_LOOP)
#define EEND (FlowChart::ENDIF_NO | FlowChart::ELSE_NO)
#define IFF (FlowChart::ELSIF_NO | FlowChart::IF_NO)
#define EXITNEXT (FlowChart::EXIT_NO | FlowChart::NEXT_NO)
#define EMPTY (EEND | FlowChart::ELSIF_NO)
#define EE (FlowChart::ELSE_NO | FlowChart::ELSIF_NO)
#define EMPTNODE (ENDCL | EEND | FlowChart::ELSIF_NO)
#define FLOWLEN (flowList.size()-1)
Functions
static void initUCF (Entry *root, const QCString &type, QCString &qcs, int line, const QCString &fileName, QCString &brief)
static void writeUCFLink (const MemberDef *mdef, OutputList &ol)
static void addInstance (ClassDefMutable *entity, ClassDefMutable *arch, ClassDefMutable *inst, const std::shared_ptr< Entry > &cur)
static void createSVG ()
static void startDot (TextStream &t)
static void startTable (TextStream &t, const QCString &className)
static std::vector< const MemberDef * > getPorts (const ClassDef *cd)
static void writeVhdlEntityToolTip (TextStream &t, ClassDef *cd)
static void endDot (TextStream &t)
static void writeTable (const std::vector< const MemberDef * > &portList, TextStream &t)
static void endTable (TextStream &t)
static void writeClassToDot (TextStream &t, ClassDef *cd)
static void writeVhdlDotLink (TextStream &t, const QCString &a, const QCString &b, const QCString &style)
static void codify (TextStream &t, const QCString &str)
static void writeLink (const MemberDef *mdef, OutputList &ol)
static void startFonts (const QCString &q, const char *keyword, OutputList &ol)
static QCString splitString (QCString &str, char c)
static int compareString (const QCString &s1, const QCString &s2)
static QCString formatBriefNote (const QCString &brief, ClassDef *cd)
static void writeColumn (TextStream &t, const MemberDef *md, bool start)
static bool membersHaveSpecificType (const MemberList *ml, uint64_t type)
static const MemberDef * findMemFlow (const MemberDef *mdef)
void alignText (QCString &q)
Variables
static const MemberDef * flowMember =0
static const std::set< std::string > g_vhdlKeyWordSet0
static const std::set< std::string > g_vhdlKeyWordSet1
static const std::set< std::string > g_vhdlKeyWordSet2
static const std::set< std::string > g_vhdlKeyWordSet3
static std::map< std::string, const MemberDef * > g_varMap
static std::vector< ClassDef * > g_classList
static std::map< ClassDef *, std::vector< ClassDef * > > g_packages
static int recordCounter =0
static std::vector< const MemberDef * > mdList
static int ifcounter =0
static int nodeCounter =0
struct {
const char * textNodeLink
const char * yesNodeLink
const char * noNodeLink
const char * comment
const char * decisionNode
const char * varNode
const char * startEndNode
const char * textNode
} flowCol
std::vector< FlowChart > flowList
Macro Definition Documentation
DECLN
#define DECLN
Value:
                  (FlowChart::WHEN_NO      | \
                  FlowChart::ELSIF_NO     | FlowChart::IF_NO    | \
                  FlowChart::FOR_NO       | FlowChart::WHILE_NO | \
                  FlowChart::CASE_NO      | FlowChart::LOOP_NO )
Definition at line 2869 of file vhdldocgen.cpp.
EE
#define EE (FlowChart::ELSE_NO | FlowChart::ELSIF_NO)
Definition at line 2881 of file vhdldocgen.cpp.
EEND
#define EEND (FlowChart::ENDIF_NO | FlowChart::ELSE_NO)
Definition at line 2877 of file vhdldocgen.cpp.
EMPTNODE
#define EMPTNODE (ENDCL | EEND | FlowChart::ELSIF_NO)
Definition at line 2882 of file vhdldocgen.cpp.
EMPTY
#define EMPTY (EEND | FlowChart::ELSIF_NO)
Definition at line 2880 of file vhdldocgen.cpp.
ENDCL
#define ENDCL (FlowChart::END_CASE | FlowChart::END_LOOP)
Definition at line 2876 of file vhdldocgen.cpp.
EXITNEXT
#define EXITNEXT (FlowChart::EXIT_NO | FlowChart::NEXT_NO)
Definition at line 2879 of file vhdldocgen.cpp.
FLOWLEN
#define FLOWLEN (flowList.size()-1)
Definition at line 2883 of file vhdldocgen.cpp.
IFF
#define IFF (FlowChart::ELSIF_NO | FlowChart::IF_NO)
Definition at line 2878 of file vhdldocgen.cpp.
LOOP
#define LOOP
Value:
                  (FlowChart::FOR_NO       | FlowChart::WHILE_NO | \
                  FlowChart::LOOP_NO )
Definition at line 2874 of file vhdldocgen.cpp.
STARTFIN
#define STARTFIN (FlowChart::START_NO | FlowChart::END_NO)
Definition at line 2873 of file vhdldocgen.cpp.
STARTL
#define STARTL
Value:
                  (FlowChart::WHILE_NO     | FlowChart::IF_NO    | \
                  FlowChart::FOR_NO       | FlowChart::CASE_NO  | \
                  FlowChart::LOOP_NO      | WHEN_NO)
Definition at line 2866 of file vhdldocgen.cpp.
theTranslator_vhdlType
#define theTranslator_vhdlType theTranslator->trVhdlType
Definition at line 64 of file vhdldocgen.cpp.
Function Documentation
addInstance()
static void addInstance (ClassDefMutable * entity, ClassDefMutable * arch, ClassDefMutable * inst, const std::shared_ptr< Entry > & cur) static
Definition at line 2559 of file vhdldocgen.cpp.
{
  QCString bName,n1;
  if (ar==0) return;
  if (classEntity==0)
  {
    //add component inst
    n1=cur->type;
    goto ferr;
  }
  if (classEntity==cd) return;
  bName=classEntity->name();
  // fprintf(stderr,"\naddInstance %s to %s %s %s\n",qPrint( classEntity->name()),qPrint(cd->name()),qPrint(ar->name()),cur->name);
  n1=classEntity->name();
  if (!cd->isBaseClass(classEntity, true))
  {
    cd->insertBaseClass(classEntity,n1,Protection::Public,Specifier::Normal,QCString());
  }
  else
  {
    VhdlDocGen::addBaseClass(cd,classEntity);
  }
  if (!VhdlDocGen::isSubClass(classEntity,cd,true,0))
  {
    classEntity->insertSubClass(cd,Protection::Public,Specifier::Normal,QCString());
    classEntity->setLanguage(SrcLangExt_VHDL);
  }
ferr:
  QCString uu=cur->name;
  auto md = createMemberDef(
      ar->getDefFileName(), cur->startLine,cur->startColumn,
      n1,uu,uu, QCString(),
      Protection::Public,
      Specifier::Normal,
      cur->isStatic,
      Relationship::Member,
      MemberType_Variable,
      ArgumentList(),
      ArgumentList(),
      "");
  auto mmd = toMemberDefMutable(md.get());
  if (!ar->getOutputFileBase().isEmpty())
  {
    TagInfo tg;
    tg.anchor = 0;
    tg.fileName = ar->getOutputFileBase();
    tg.tagName = 0;
    mmd->setTagInfo(&tg);
  }
  //fprintf(stderr,"\n%s%s%s\n",qPrint(md->name()),qPrint(cur->brief),qPrint(cur->doc));
  mmd->setLanguage(SrcLangExt_VHDL);
  mmd->setMemberSpecifiers(VhdlDocGen::INSTANTIATION);
  mmd->setBriefDescription(cur->brief,cur->briefFile,cur->briefLine);
  mmd->setBodySegment(cur->startLine,cur->startLine,-1) ;
  mmd->setDocumentation(cur->doc,cur->docFile,cur->docLine);
  FileDef *fd=ar->getFileDef();
  mmd->setBodyDef(fd);
  ar->insertMember(md.get());
  MemberName *mn = Doxygen::functionNameLinkedMap->add(uu);
  mn->push_back(std::move(md));
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), VhdlDocGen::addBaseClass(), TagInfo::anchor, createMemberDef(), TagInfo::fileName, Doxygen::functionNameLinkedMap, Definition::getDefFileName(), ClassDef::getFileDef(), ClassDef::getOutputFileBase(), ClassDefMutable::insertBaseClass(), ClassDefMutable::insertMember(), ClassDefMutable::insertSubClass(), VhdlDocGen::INSTANTIATION, ClassDef::isBaseClass(), QCString::isEmpty(), VhdlDocGen::isSubClass(), Member, MemberType_Variable, Definition::name(), Normal, Public, MemberName::push_back(), DefinitionMutable::setBodyDef(), DefinitionMutable::setLanguage(), SrcLangExt_VHDL, TagInfo::tagName, and toMemberDefMutable().
Referenced by VhdlDocGen::computeVhdlComponentRelations().
alignText()
void alignText (QCString & q)
Definition at line 2918 of file vhdldocgen.cpp.
{
  if (q.length()<=80) return;
  if (q.length()>200)
  {
    q.resize(200);
  }
  q.append(" ...");
  QCString str(q);
  QCString temp;
  while (str.length()>80)
  {
    int j=std::max(str.findRev(' ',80),str.findRev('|',80));
    if (j<=0)
    {
      temp+=str;
      q=temp;
      return;
    }
    else
    {
      QCString qcs=str.left(j);
      temp+=qcs+"\\";
      temp+="n";
      str.remove(0,j);
    }
  }//while
 q=temp+str;
// #endif
}
References QCString::append(), QCString::findRev(), QCString::left(), QCString::length(), QCString::remove(), and QCString::resize().
Referenced by FlowChart::writeShape().
codify()
static void codify (TextStream & t, const QCString & str) static
Definition at line 98 of file vhdldocgen.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    while (*p)
    {
      c=*p++;
      switch(c)
      {
        case '<':  t << "&lt;";
                   break;
        case '>':  t << "&gt;";
                   break;
        case '&':  t << "&amp;";
                   break;
        case '\'': t << "&#39;";
                   break;
        case '"':  t << "&quot;";
                   break;
        default:   t << c;
                   break;
      }
    }
  }
}
References QCString::data(), and QCString::isEmpty().
Referenced by writeColumn().
compareString()
static int compareString (const QCString & s1, const QCString & s2) static
Definition at line 154 of file vhdldocgen.cpp.
{
  return qstricmp(s1.stripWhiteSpace(),s2.stripWhiteSpace());
}
References qstricmp(), and QCString::stripWhiteSpace().
Referenced by VhdlDocGen::findFunction().
createSVG()
static void createSVG () static
Definition at line 159 of file vhdldocgen.cpp.
{
    QCString ov =Config_getString(HTML_OUTPUT);
    QCString dir="-o \""+ov+"/vhdl_design_overview.html\"";
    ov+="/vhdl_design.dot";
    QCString vlargs="-Tsvg \""+ov+"\" "+dir ;
    if (Portable::system(Doxygen::verifiedDotPath,vlargs)!=0)
    {
      err("could not create dot file\n");
    }
}
References Config_getString, err, Portable::system(), and Doxygen::verifiedDotPath.
Referenced by VhdlDocGen::writeOverview().
endDot()
static void endDot (TextStream & t) static
Definition at line 250 of file vhdldocgen.cpp.
{
  t <<" } \n";
}
Referenced by VhdlDocGen::writeOverview().
endTable()
static void endTable (TextStream & t) static
Definition at line 394 of file vhdldocgen.cpp.
{
  t << "</TABLE>>\n";
  t << "] \n";
}
Referenced by VhdlDocGen::writeOverview().
findMemFlow()
static const MemberDef * findMemFlow (const MemberDef * mdef) static
Definition at line 2756 of file vhdldocgen.cpp.
{
  for (const auto &md : mdList)
  {
    if (md->name()==mdef->name() &&  md->getStartBodyLine()==mdef->getStartBodyLine())
    {
      return md;
    }
  }
  return 0;
}
References Definition::getStartBodyLine(), mdList, and Definition::name().
Referenced by VhdlDocGen::createFlowChart().
formatBriefNote()
static QCString formatBriefNote (const QCString & brief, ClassDef * cd) static
Definition at line 273 of file vhdldocgen.cpp.
{
  QCString vForm;
  QCString repl("<BR ALIGN=\"LEFT\"/>");
  QCString file=cd->getDefFileName();
  int k=cd->briefLine();
  auto qsl=split(brief.str(),"\n");
  for(const auto &line : qsl)
  {
    vForm+=parseCommentAsText(cd,NULL,line.c_str(),file,k);
    k++;
    vForm+=repl;
  }
  return vForm;
}
References Definition::briefLine(), Definition::getDefFileName(), parseCommentAsText(), split(), and QCString::str().
Referenced by writeVhdlEntityToolTip().
getPorts()
static std::vector< const MemberDef * > getPorts (const ClassDef * cd) static
Definition at line 416 of file vhdldocgen.cpp.
{
  MemberList *ml = cd->getMemberList(MemberListType_variableMembers);
  std::vector<const MemberDef *> portList;
  if (ml==0)
  {
    return portList;
  }
  for (const auto &md : *ml)
  {
    if (md->getMemberSpecifiers()==VhdlDocGen::PORT)
    {
      portList.push_back(md);
    }
  }
  return portList;
}
References ClassDef::getMemberList(), MemberListType_variableMembers, VhdlDocGen::PORT, and MemberVector::push_back().
Referenced by VhdlDocGen::writeOverview().
initUCF()
static void initUCF (Entry * root, const QCString & type, QCString & qcs, int line, const QCString & fileName, QCString & brief) static
Definition at line 2341 of file vhdldocgen.cpp.
{
  if (qcs.isEmpty())return;
  QCString n;
  VhdlDocGen::deleteAllChars(qcs,';');
  qcs=qcs.stripWhiteSpace();
  static const reg::Ex reg(R"([\s=])");
  int i = findIndex(qcs.str(),reg);
  if (i<0) return;
  if (i==0)
  {
    n=type;
    VhdlDocGen::deleteAllChars(n,'#');
  }
  else
  {
    n=qcs.left(i);
  }
  qcs=qcs.remove(0,i+1);
  //  qcs.prepend("|");
  qcs.stripPrefix("=");
  std::shared_ptr<Entry> current = std::make_shared<Entry>();
  current->spec=VhdlDocGen::UCF_CONST;
  current->section=Entry::VARIABLE_SEC;
  current->bodyLine=line;
  current->fileName=fileName;
  current->type="ucf_const";
  current->args+=qcs;
  current->lang=  SrcLangExt_VHDL ;
  // adding dummy name for constraints like VOLTAGE=5,TEMPERATURE=20 C
  if (n.isEmpty())
  {
    n="dummy";
    n+=VhdlDocGen::getRecordNumber();
  }
  current->name= n+"_";
  current->name.append(VhdlDocGen::getRecordNumber());
  if (!brief.isEmpty())
  {
    current->brief=brief;
    current->briefLine=line;
    current->briefFile=fileName;
    brief.resize(0);
  }
  root->moveToSubEntryAndKeep(current);
}
References QCString::append(), VhdlDocGen::deleteAllChars(), findIndex(), VhdlDocGen::getRecordNumber(), QCString::isEmpty(), QCString::left(), Entry::moveToSubEntryAndKeep(), QCString::remove(), QCString::resize(), SrcLangExt_VHDL, QCString::str(), QCString::stripPrefix(), QCString::stripWhiteSpace(), VhdlDocGen::UCF_CONST, and Entry::VARIABLE_SEC.
Referenced by VhdlDocGen::parseUCF().
membersHaveSpecificType()
static bool membersHaveSpecificType (const MemberList * ml, uint64_t type) static
Definition at line 2095 of file vhdldocgen.cpp.
{
  if (ml==0) return FALSE;
  for (const auto &mdd : *ml)
  {
    if (mdd->getMemberSpecifiers()==type) //is type in class
    {
      return TRUE;
    }
  }
  for (const auto &mg : ml->getMemberGroupList())
  {
    if (!mg->members().empty())
    {
      if (membersHaveSpecificType(&mg->members(),type)) return TRUE;
    }
  }
  return FALSE;
}
References FALSE, MemberList::getMemberGroupList(), membersHaveSpecificType(), and TRUE.
Referenced by membersHaveSpecificType(), and VhdlDocGen::writeVHDLDeclarations().
splitString()
static QCString splitString (QCString & str, char c) static
Definition at line 142 of file vhdldocgen.cpp.
{
  QCString n=str;
  int i=str.find(c);
  if (i>0)
  {
    n=str.left(i);
    str=str.remove(0,i+1);
  }
  return n;
}
References QCString::find(), QCString::left(), and QCString::remove().
Referenced by writeUCFLink().
startDot()
static void startDot (TextStream & t) static
Definition at line 242 of file vhdldocgen.cpp.
{
  t << " digraph G { \n";
  t << "rankdir=LR \n";
  t << "concentrate=TRUE\n";
  t << "stylesheet=\"doxygen.css\"\n";
}
Referenced by VhdlDocGen::writeOverview().
startFonts()
static void startFonts (const QCString & q, const char * keyword, OutputList & ol) static
Definition at line 134 of file vhdldocgen.cpp.
{
  auto &codeOL = ol.codeGenerators();
  codeOL.startFontClass(keyword);
  codeOL.codify(q);
  codeOL.endFontClass();
}
References OutputList::codeGenerators(), and OutputCodeList::startFontClass().
Referenced by VhdlDocGen::writeFormatString(), VhdlDocGen::writeFuncProcDocu(), VhdlDocGen::writeFunctionProto(), VhdlDocGen::writeProcedureProto(), and VhdlDocGen::writeStringLink().
startTable()
static void startTable (TextStream & t, const QCString & className) static
Definition at line 255 of file vhdldocgen.cpp.
{
  t << className <<" [ shape=none , fontname=\"arial\",  fontcolor=\"blue\" , \n";
  t << "label=<<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\">\n";
}
Referenced by VhdlDocGen::writeOverview().
writeClassToDot()
static void writeClassToDot (TextStream & t, ClassDef * cd) static
Definition at line 400 of file vhdldocgen.cpp.
{
  t << "<TR><TD COLSPAN=\"2\" BGCOLOR=\"yellow\" ";
  t << "PORT=\"";
  t << cd->name();
  t << "\" ";
  t << "href=\"";
  QCString fn = cd->getOutputFileBase();
  addHtmlExtensionIfMissing(fn);
  t << fn;
  t << "\" ";
  t << ">";
  t << cd->name();
  t << " </TD></TR>\n";
}
References addHtmlExtensionIfMissing(), ClassDef::getOutputFileBase(), and Definition::name().
Referenced by VhdlDocGen::writeOverview().
writeColumn()
static void writeColumn (TextStream & t, const MemberDef * md, bool start) static
Definition at line 312 of file vhdldocgen.cpp.
{
  QCString toolTip;
  bool bidir=(md!=0 &&( qstricmp(md->typeString(),"inout")==0));
  if (md)
  {
    toolTip=md->briefDescriptionAsTooltip();
    if (!toolTip.isEmpty())
    {
      QCString largs = md->argsString();
      toolTip+=" [";
      toolTip+=substitute(largs,"%"," ");
      toolTip+="]";
    }
  }
  if (start)
  {
    t <<"<TR>\n";
  }
  t << "<TD ALIGN=\"LEFT\" ";
  if (md)
  {
    QCString fn = md->getOutputFileBase();
    addHtmlExtensionIfMissing(fn);
    t << "href=\"" << fn << "#" << md->anchor() <<"\" ";
    t<<" TOOLTIP=\"";
    if (!toolTip.isEmpty())
    {
      codify(t,toolTip);
    }
    else
    {
      QCString largs = md->argsString();
      if (!largs.isEmpty())
      {
        largs=substitute(largs,"%"," ");
        codify(t,largs);
      }
    }
    t << "\" ";
    t << " PORT=\"";
    t << md->name();
    t << "\" ";
  }
  if (!toolTip.isEmpty())
  {
    // if (!toolTip.isEmpty())
    if (bidir)
      t << "BGCOLOR=\"orange\">";
    else
      t << "BGCOLOR=\"azure\">";
  }
  else if (bidir)
  {
    t << "BGCOLOR=\"pink\">";
  }
  else
  {
    t << "BGCOLOR=\"lightgrey\">";
  }
  if (md)
  {
    t << md->name();
  }
  else
  {
    t << " \n";
  }
  t << "</TD>\n";
  if (!start)
  {
    t << "</TR>\n";
  }
}
References addHtmlExtensionIfMissing(), MemberDef::anchor(), MemberDef::argsString(), Definition::briefDescriptionAsTooltip(), codify(), MemberDef::getOutputFileBase(), QCString::isEmpty(), Definition::name(), qstricmp(), substitute(), and MemberDef::typeString().
Referenced by writeTable().
writeLink()
static void writeLink (const MemberDef * mdef, OutputList & ol) static
Definition at line 126 of file vhdldocgen.cpp.
{
  ol.writeObjectLink(mdef->getReference(),
      mdef->getOutputFileBase(),
      mdef->anchor(),
      mdef->name());
}
References MemberDef::anchor(), MemberDef::getOutputFileBase(), MemberDef::getReference(), Definition::name(), and OutputList::writeObjectLink().
Referenced by VhdlDocGen::writeRecordUnit(), VhdlDocGen::writeSource(), VhdlDocGen::writeStringLink(), writeUCFLink(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVHDLTypeDocumentation().
writeTable()
static void writeTable (const std::vector< const MemberDef * > & portList, TextStream & t) static
Definition at line 438 of file vhdldocgen.cpp.
{
  std::vector<const MemberDef *> inPorts;
  std::vector<const MemberDef *> outPorts;
  for (const auto &md : portList)
  {
    QCString qc=md->typeString();
    if (qc=="in")
    {
      inPorts.push_back(md);
    }
    else
    {
      outPorts.push_back(md);
    }
  }
  size_t inp  = inPorts.size();
  size_t outp = outPorts.size();
  size_t maxLen;
  if (inp>=outp)
  {
    maxLen=inp;
  }
  else
  {
    maxLen=outp;
  }
  size_t i;
  for (i=0;i<maxLen;i++)
  {
    //write inports
    if (i<inp)
    {
      auto md = inPorts[i];
      writeColumn(t,md,TRUE);
    }
    else
    {
      writeColumn(t,NULL,TRUE);
    }
    if (i<outp)
    {
      auto md = outPorts[i];
      writeColumn(t,md,FALSE);
    }
    else
    {
      writeColumn(t,NULL,FALSE);
    }
  }
}
References FALSE, QCString::size(), TRUE, and writeColumn().
Referenced by VhdlDocGen::writeOverview().
writeUCFLink()
static void writeUCFLink (const MemberDef * mdef, OutputList & ol) static
Definition at line 2398 of file vhdldocgen.cpp.
{
  QCString largs(mdef->argsString());
  QCString n= splitString(largs, '#');
  // VhdlDocGen::adjustRecordMember(mdef);
  bool equ=(n.length()==largs.length());
  if (!equ)
  {
    ol.writeString(n);
    ol.docify(" ");
    ol.insertMemberAlign();
  }
  if (mdef->name().contains("dummy")==0)
  {
    writeLink(mdef,ol);
  }
  if (equ)
  {
    ol.insertMemberAlign();
  }
  ol.docify(" ");
  VhdlDocGen::formatString(largs,ol,mdef);
}
References MemberDef::argsString(), QCString::contains(), OutputList::docify(), VhdlDocGen::formatString(), OutputList::insertMemberAlign(), QCString::length(), Definition::name(), splitString(), writeLink(), and OutputList::writeString().
Referenced by VhdlDocGen::writeVHDLDeclaration().
writeVhdlDotLink()
static void writeVhdlDotLink (TextStream & t, const QCString & a, const QCString & b, const QCString & style) static
Definition at line 261 of file vhdldocgen.cpp.
{
  t << a << "->" << b;
  if (!style.isEmpty())
  {
    t << "[style=" << style << "];\n";
  }
  t << "\n";
}
References QCString::isEmpty().
Referenced by VhdlDocGen::writeOverview(), and writeVhdlEntityToolTip().
writeVhdlEntityToolTip()
static void writeVhdlEntityToolTip (TextStream & t, ClassDef * cd) static
Definition at line 291 of file vhdldocgen.cpp.
{
  QCString brief=cd->briefDescription();
  if (brief.isEmpty()) return;
  brief=formatBriefNote(brief,cd);
  QCString node="node";
  node+=VhdlDocGen::getRecordNumber();
  t << node <<"[shape=none margin=0.1, label=<\n";
  t << "<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"2\" >\n ";
  t << "<TR><TD BGCOLOR=\"lightcyan\"> ";
  t << brief;
  t << " </TD></TR></TABLE>>];";
  QCString dotn=cd->name()+":";
  dotn+=cd->name();
  writeVhdlDotLink(t,dotn,node,"dotted");
}
References Definition::briefDescription(), formatBriefNote(), VhdlDocGen::getRecordNumber(), QCString::isEmpty(), Definition::name(), and writeVhdlDotLink().
Referenced by VhdlDocGen::writeOverview().
Variable Documentation
comment
const char* comment
Definition at line 2896 of file vhdldocgen.cpp.
Referenced by codifyLines(), CommentScanner::parseCommentBlock(), VhdlDocGen::parseUCF(), and writeObjCMethodCall().
decisionNode
const char* decisionNode
Definition at line 2897 of file vhdldocgen.cpp.
[struct]
struct { ... } flowCol
Initial value:
=
{ "green",
  "red",
  "black",
  "khaki",
  "0.7 0.3 1.0",
  "lightyellow",
  "white",
  "lightcyan"
}
Referenced by FlowChart::buildCommentNodes(), FlowChart::writeEdge(), and FlowChart::writeShape().
flowList
std::vector<FlowChart> flowList
Definition at line 2912 of file vhdldocgen.cpp.
Referenced by FlowChart::addFlowChart(), FlowChart::buildCommentNodes(), FlowChart::colTextNodes(), FlowChart::delFlowList(), FlowChart::findLabel(), FlowChart::findNextLoop(), FlowChart::findNode(), FlowChart::findPrevLoop(), FlowChart::getNextIfLink(), FlowChart::getNextNode(), FlowChart::printFlowTree(), FlowChart::printUmlTree(), FlowChart::writeFlowChart(), and FlowChart::writeFlowLinks().
flowMember
const MemberDef* flowMember =0 static
Definition at line 83 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::getFlowMember(), and VhdlDocGen::setFlowMember().
g_classList
std::vector<ClassDef*> g_classList static
Definition at line 595 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::findMemberDef(), and VhdlDocGen::resetCodeVhdlParserState().
g_packages
std::map<ClassDef*,std::vector<ClassDef*> > g_packages static
Definition at line 596 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::findAllPackages(), VhdlDocGen::findMember(), and VhdlDocGen::resetCodeVhdlParserState().
g_varMap
std::map<std::string,const MemberDef*> g_varMap static
Definition at line 594 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::findMemberDef(), and VhdlDocGen::resetCodeVhdlParserState().
g_vhdlKeyWordSet0
const std::set< std::string > g_vhdlKeyWordSet0 static
Initial value:
=
{
  "abs","access","after","alias","all","and","architecture","array","assert","assume","assume_guarantee","attribute",
  "begin","block","body","buffer","bus",
  "case","component","configuration","constant","context","cover",
  "default","disconnect","downto",
  "else","elsif","end","entity","exit",
  "fairness","file","for","force","function",
  "generate","generic","group","guarded",
  "if","impure","in","inertial","inout","is",
  "label","library","linkage","literal","loop",
  "map","mod",
  "nand","new","next","nor","not","null",
  "of","on","open","or","others","out",
  "package","parameter","port","postponed","procedure","process","property","protected","pure",
  "range","record","register","reject","release","restrict","restrict_guarantee","rem","report","rol","ror","return",
  "select","sequence","severity","signal","shared","sla","sll","sra","srl","strong","subtype",
  "then","to","transport","type",
  "unaffected","units","until","use",
  "variable","vmode","vprop","vunit",
  "wait","when","while","with",
  "xor","xnor"
}
Definition at line 507 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::findKeyWord().
g_vhdlKeyWordSet1
const std::set< std::string> g_vhdlKeyWordSet1 static
Initial value:
=
{
  "natural","unsigned","signed","string","boolean", "bit","bit_vector","character",
  "std_ulogic","std_ulogic_vector","std_logic","std_logic_vector","integer",
  "real","float","ufixed","sfixed","time","positive"
}
Definition at line 533 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::findKeyWord().
g_vhdlKeyWordSet2
const std::set< std::string > g_vhdlKeyWordSet2 static
Initial value:
=
{
  "abs","and","or","not","mod","xor","rem","xnor","ror","rol","sla","sll"
}
Definition at line 541 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::findKeyWord().
g_vhdlKeyWordSet3
const std::set< std::string > g_vhdlKeyWordSet3 static
Initial value:
=
{
  "base","left","right","high","low","ascending",
  "image","value","pos","val","succ","pred","leftof","rightof","left","right","high","low",
  "range","reverse_range","length","ascending","delayed","stable","quiet","transaction","event",
  "active","last_event","last_active","last_value","driving","driving_value","simple_name","instance_name","path_name"
}
Definition at line 547 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::findKeyWord().
ifcounter
int ifcounter =0 static
Definition at line 2885 of file vhdldocgen.cpp.
Referenced by FlowChart::delFlowList(), FlowChart::FlowChart(), and FlowChart::moveToPrevLevel().
mdList
std::vector<const MemberDef*> mdList static
Definition at line 2754 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::createFlowChart(), and findMemFlow().
nodeCounter
int nodeCounter =0 static
Definition at line 2886 of file vhdldocgen.cpp.
Referenced by FlowChart::delFlowList(), and FlowChart::FlowChart().
noNodeLink
const char* noNodeLink
Definition at line 2893 of file vhdldocgen.cpp.
recordCounter
int recordCounter =0 static
Definition at line 1113 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::getRecordNumber().
startEndNode
const char* startEndNode
Definition at line 2899 of file vhdldocgen.cpp.
textNode
const char* textNode
Definition at line 2900 of file vhdldocgen.cpp.
textNodeLink
const char* textNodeLink
Definition at line 2891 of file vhdldocgen.cpp.
varNode
const char* varNode
Definition at line 2898 of file vhdldocgen.cpp.
yesNodeLink
const char* yesNodeLink
Definition at line 2892 of file vhdldocgen.cpp.