Doxygen: PortugueseTranslatorUtils Namespace Reference
PortugueseTranslatorUtils Namespace Reference
Functions
bool isClassMemberHighlightMasculine (ClassMemberHighlight::Enum hl)
bool isFileMemberHighlightMasculine (FileMemberHighlight::Enum hl)
bool isNamespaceMemberHighlightMasculine (NamespaceMemberHighlight::Enum hl)
bool isModuleMemberHighlightMasculine (ModuleMemberHighlight::Enum hl)
Function Documentation
isClassMemberHighlightMasculine()
bool PortugueseTranslatorUtils::isClassMemberHighlightMasculine (ClassMemberHighlight::Enum hl) inline
Returns true if the gender of the given component is masculine in Portuguese.
Definition at line 78 of file translator_br.h.
    {
      switch (hl)
      {
        case ClassMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            // as estruturas e uniões
            return false;
          }
          else
          {
            // os membros da classe
            return true;
          }
          break;
        case ClassMemberHighlight::Functions:
        case ClassMemberHighlight::Variables:
        case ClassMemberHighlight::Enums:
        case ClassMemberHighlight::Properties:
        case ClassMemberHighlight::Typedefs:
          return false;
        case ClassMemberHighlight::EnumValues:
        case ClassMemberHighlight::Events:
        case ClassMemberHighlight::Related:
        default:
          return true;
      }
    }
References ClassMemberHighlight::All, Config_getBool, ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, ClassMemberHighlight::Properties, ClassMemberHighlight::Related, ClassMemberHighlight::Typedefs, and ClassMemberHighlight::Variables.
Referenced by TranslatorBrazilian::trCompoundMembersDescriptionTotal(), and TranslatorPortuguese::trCompoundMembersDescriptionTotal().
isFileMemberHighlightMasculine()
bool PortugueseTranslatorUtils::isFileMemberHighlightMasculine (FileMemberHighlight::Enum hl) inline
Returns true if the gender of the given component is masculine in Portuguese.
Definition at line 110 of file translator_br.h.
    {
      switch (hl)
      {
        case FileMemberHighlight::All:
        case FileMemberHighlight::Dictionaries:
        case FileMemberHighlight::EnumValues:
          return true;
        case FileMemberHighlight::Functions:
        case FileMemberHighlight::Variables:
        case FileMemberHighlight::Typedefs:
        case FileMemberHighlight::Sequences:
        case FileMemberHighlight::Enums:
        case FileMemberHighlight::Defines:
          return false;
        default:
          return true;
      }
    }
References FileMemberHighlight::All, FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, FileMemberHighlight::Sequences, FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
Referenced by TranslatorBrazilian::trFileMembersDescriptionTotal(), and TranslatorPortuguese::trFileMembersDescriptionTotal().
isModuleMemberHighlightMasculine()
bool PortugueseTranslatorUtils::isModuleMemberHighlightMasculine (ModuleMemberHighlight::Enum hl) inline
Returns true if the gender of the given component is masculine in Brazilian Portuguese and European Portuguese.
Definition at line 153 of file translator_br.h.
    {
      switch (hl)
      {
        case ModuleMemberHighlight::All:
        case ModuleMemberHighlight::EnumValues:
          return true;
        case ModuleMemberHighlight::Functions:
        case ModuleMemberHighlight::Variables:
        case ModuleMemberHighlight::Typedefs:
        case ModuleMemberHighlight::Enums:
          return false;
        default:
          return true;
      }
    }
References ModuleMemberHighlight::All, ModuleMemberHighlight::Enums, ModuleMemberHighlight::EnumValues, ModuleMemberHighlight::Functions, ModuleMemberHighlight::Typedefs, and ModuleMemberHighlight::Variables.
Referenced by TranslatorBrazilian::trModuleMembersDescriptionTotal(), and TranslatorPortuguese::trModuleMembersDescriptionTotal().
isNamespaceMemberHighlightMasculine()
bool PortugueseTranslatorUtils::isNamespaceMemberHighlightMasculine (NamespaceMemberHighlight::Enum hl) inline
Returns true if the gender of the given component is masculine in Brazilian Portuguese and European Portuguese.
Definition at line 132 of file translator_br.h.
    {
      switch (hl)
      {
        case NamespaceMemberHighlight::All:
        case NamespaceMemberHighlight::Dictionaries:
        case NamespaceMemberHighlight::EnumValues:
          return true;
        case NamespaceMemberHighlight::Functions:
        case NamespaceMemberHighlight::Variables:
        case NamespaceMemberHighlight::Typedefs:
        case NamespaceMemberHighlight::Sequences:
        case NamespaceMemberHighlight::Enums:
          return false;
        default:
          return true;
      }
    }
References NamespaceMemberHighlight::All, NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, NamespaceMemberHighlight::Sequences, NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
Referenced by TranslatorBrazilian::trNamespaceMembersDescriptionTotal(), and TranslatorPortuguese::trNamespaceMembersDescriptionTotal().