Doxygen: TranslatorChinese Class Reference
TranslatorChinese Class Reference
#include <src/translator_cn.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString latexFontenc () override
QCString latexDocumentPre () override
QCString latexDocumentPost () override
bool needsPunctuation () override
add punctuation at the end of a brief description when needed and supported by the language
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool, bool) override
QCString trFile (bool, bool) override
QCString trNamespace (bool, bool) override
QCString trGroup (bool, bool) override
QCString trPage (bool, bool) override
QCString trMember (bool, bool) override
QCString trGlobal (bool, bool) override
QCString trAuthor (bool, bool) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool, bool) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool, bool) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) override
QCString trType (bool, bool) override
QCString trSubprogram (bool, bool) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool, bool full) override
QCString trMonth (int month, bool, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description.
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
QCString trDesignUnitDocumentation () override
VHDL design unit documentation.
QCString trConcept (bool, bool) override
C++20 concept.
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
QCString trPackageList () override
QCString trFlowchart () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
QCString trCopyToClipboard () override
QCString trImportant () override
Public Member Functions inherited from Translator
virtual QCString updateNeededMessage ()
virtual QCString latexFont ()
virtual QCString latexCommandName ()
Additional Inherited Members
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Detailed Description
Definition at line 27 of file translator_cn.h.
Member Function Documentation
getLanguageString()
QCString TranslatorChinese::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 62 of file translator_cn.h.
    {
      return "0x804 Chinese (PRC)";
    }
idLanguage()
QCString TranslatorChinese::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in the language.cpp.
Implements Translator.
Definition at line 37 of file translator_cn.h.
    { return "chinese"; }
latexDocumentPost()
QCString TranslatorChinese::latexDocumentPost () inline override virtual
Sets the commands to be inserted directly before the \\end{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 74 of file translator_cn.h.
    {
      return "\\end{CJK}\n";
    }
latexDocumentPre()
QCString TranslatorChinese::latexDocumentPre () inline override virtual
Sets the commands to be inserted directly after the \\begin{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 70 of file translator_cn.h.
    {
      return "\\begin{CJK}{UTF8}{gbsn}\n";
    }
latexFontenc()
QCString TranslatorChinese::latexFontenc () inline override virtual
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 66 of file translator_cn.h.
    {
      return "";
    }
latexLanguageSupportCommand()
QCString TranslatorChinese::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 54 of file translator_cn.h.
    {
      return "\\usepackage{CJKutf8}\n";
    }
needsPunctuation()
bool TranslatorChinese::needsPunctuation () inline override virtual
add punctuation at the end of a brief description when needed and supported by the language
Reimplemented from Translator.
Definition at line 78 of file translator_cn.h.
    {
      return false;
    }
trAdditionalInheritedMembers()
QCString TranslatorChinese::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1913 of file translator_cn.h.
    { return ""; }
trAll()
QCString TranslatorChinese::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1427 of file translator_cn.h.
    {
      return "";
    }
trAndMore()
QCString TranslatorChinese::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1895 of file translator_cn.h.
    { return "" CN_SPC+number+CN_SPC "..."; }
References CN_SPC.
trAttention()
QCString TranslatorChinese::trAttention () inline override virtual
Implements Translator.
Definition at line 993 of file translator_cn.h.
    {
      return "";
    }
trAuthor()
QCString TranslatorChinese::trAuthor (bool , bool) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1295 of file translator_cn.h.
    {
      return "";
    }
trBug()
QCString TranslatorChinese::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1162 of file translator_cn.h.
    {
      return "Bug";
    }
trBugList()
QCString TranslatorChinese::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1167 of file translator_cn.h.
    {
      return "Bug" CN_SPC "";
    }
References CN_SPC.
trCallerGraph()
QCString TranslatorChinese::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1554 of file translator_cn.h.
    {
      return ":";
    }
trCallGraph()
QCString TranslatorChinese::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1433 of file translator_cn.h.
    {
      return ":";
    }
trCiteReferences()
QCString TranslatorChinese::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1869 of file translator_cn.h.
    { return ""; }
trClass()
QCString TranslatorChinese::trClass (bool , bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1229 of file translator_cn.h.
    {
      return "";
    }
Referenced by trCompoundType().
trClassDiagram()
QCString TranslatorChinese::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 509 of file translator_cn.h.
    {
      return "" CN_SPC+clName+CN_SPC ":";
    }
References CN_SPC.
trClassDocumentation()
QCString TranslatorChinese::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 392 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else {
        return "";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorChinese::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1121 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorChinese::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 189 of file translator_cn.h.
    { return ""; }
trClassHierarchyDescription()
QCString TranslatorChinese::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 241 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return ":";
      }
      else
      {
        return ":" CN_SPC;
      }
    }
References CN_SPC, and Config_getBool.
trClassMethods()
QCString TranslatorChinese::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1953 of file translator_cn.h.
    {
      return "";
    }
trCode()
QCString TranslatorChinese::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 876 of file translator_cn.h.
    {
      return "";
    }
trCollaborationDiagram()
QCString TranslatorChinese::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 822 of file translator_cn.h.
    {
      return clName+CN_SPC ":";
    }
References CN_SPC.
trCompoundIndex()
QCString TranslatorChinese::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 366 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorChinese::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1610 of file translator_cn.h.
    { return ""; }
trCompoundList()
QCString TranslatorChinese::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated class
Implements Translator.
Definition at line 193 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorChinese::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 263 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return ":";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return ":";
      }
      else
      {
        return ":";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorChinese::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1584 of file translator_cn.h.
    { return ":"; }
trCompoundListFortran()
QCString TranslatorChinese::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1576 of file translator_cn.h.
    { return ""; }
trCompoundMembers()
QCString TranslatorChinese::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 208 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorChinese::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 280 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) {
        result+="";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result+="";
      }
      else {
        result+="";
      }
      result+="";
      if (extractAll) {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+=":";
        }
        else {
          result+=":";
        }
      }
      else {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+=":";
        }
        else {
          result+=":";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorChinese::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1588 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll)
      {
        result+="";
      }
      result+=",";
      if (!extractAll)
      {
        result+=":";
      }
      else
      {
        result+=":";
      }
      return result;
    }
trCompoundMembersDescriptionTotal()
QCString TranslatorChinese::trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2423 of file translator_cn.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="";
      if (!extractAll)
      {
        result+="";
      }
      switch (hl)
      {
        case ClassMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="";
          }
          else
          {
            result+="";
          }
          break;
        case ClassMemberHighlight::Functions:
          result+="";
          break;
        case ClassMemberHighlight::Variables:
          result+="";
          break;
        case ClassMemberHighlight::Typedefs:
          result+="";
          break;
        case ClassMemberHighlight::Enums:
          result+="";
          break;
        case ClassMemberHighlight::EnumValues:
          result+="";
          break;
        case ClassMemberHighlight::Properties:
          result+="";
          break;
        case ClassMemberHighlight::Events:
          result+="";
          break;
        case ClassMemberHighlight::Related:
          result+="";
          break;
        case ClassMemberHighlight::Total: // for completeness
          break;
      }
      result+=", ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" () ";
        }
        else
        {
          result+="";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" ()";
        }
        else
        {
          result+="";
        }
      }
      result+=":" CN_SPC;
      return result;
    }
References ClassMemberHighlight::All, CN_SPC, Config_getBool, ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, ClassMemberHighlight::Properties, ClassMemberHighlight::Related, ClassMemberHighlight::Total, ClassMemberHighlight::Typedefs, and ClassMemberHighlight::Variables.
trCompoundMembersFortran()
QCString TranslatorChinese::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1580 of file translator_cn.h.
    { return ""; }
trCompoundReference()
QCString TranslatorChinese::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 584 of file translator_cn.h.
    {
      QCString result=clName;
      if (isTemplate) result+=CN_SPC "";
      switch(compType)
      {
        case ClassDef::Class:  result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union:  result+=""; break;
        case ClassDef::Interface:  result+=""; break;
        case ClassDef::Protocol:   result+=""; break;
        case ClassDef::Category:   result+=""; break;
        case ClassDef::Exception:  result+=""; break;
        default: break;
      }
      result+=CN_SPC "";
      return result;
    }
References ClassDef::Category, ClassDef::Class, CN_SPC, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorChinese::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1653 of file translator_cn.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=CN_SPC ""; break;
        case ClassDef::Struct:     result+=CN_SPC ""; break;
        case ClassDef::Union:      result+=CN_SPC ""; break;
        case ClassDef::Interface:  result+=CN_SPC ""; break;
        case ClassDef::Protocol:   result+=CN_SPC ""; break;
        case ClassDef::Category:   result+=CN_SPC ""; break;
        case ClassDef::Exception:  result+=CN_SPC ""; break;
        default: break;
      }
      if (isTemplate) result+="" CN_SPC;
      result+="";
      return result;
    }
References ClassDef::Category, ClassDef::Class, CN_SPC, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice()
QCString TranslatorChinese::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) inline override virtual
Implements Translator.
Definition at line 2213 of file translator_cn.h.
    {
      QCString result=clName;
      if (isLocal) result+=CN_SPC "";
      switch(compType)
      {
        case ClassDef::Class:      result+=CN_SPC ""; break;
        case ClassDef::Struct:     result+=CN_SPC ""; break;
        case ClassDef::Union:      result+=CN_SPC ""; break;
        case ClassDef::Interface:  result+=CN_SPC ""; break;
        case ClassDef::Protocol:   result+=CN_SPC ""; break;
        case ClassDef::Category:   result+=CN_SPC ""; break;
        case ClassDef::Exception:  result+=CN_SPC ""; break;
        default: break;
      }
      result+="";
      return result;
    }
References ClassDef::Category, ClassDef::Class, CN_SPC, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorChinese::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 486 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trCompoundType()
QCString TranslatorChinese::trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) inline override virtual
the compound type as used for the xrefitems
Implements Translator.
Definition at line 2348 of file translator_cn.h.
    {
      QCString result;
      switch(compType)
      {
        case ClassDef::Class:
          if (lang == SrcLangExt::Fortran) trType(true,true);
          else result=trClass(true,true);
          break;
        case ClassDef::Struct:     result=""; break;
        case ClassDef::Union:      result=""; break;
        case ClassDef::Interface:  result=""; break;
        case ClassDef::Protocol:   result=""; break;
        case ClassDef::Category:   result=""; break;
        case ClassDef::Exception:  result=""; break;
        case ClassDef::Service:    result=""; break;
        case ClassDef::Singleton:  result=""; break;
        default: break;
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, Fortran, ClassDef::Interface, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, ClassDef::Struct, trClass(), trType(), and ClassDef::Union.
trConcept()
QCString TranslatorChinese::trConcept (bool , bool) inline override virtual
C++20 concept.
Implements Translator.
Definition at line 2261 of file translator_cn.h.
    {
      return "";
    }
trConceptDefinition()
QCString TranslatorChinese::trConceptDefinition () inline override virtual
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2295 of file translator_cn.h.
    {
      return "";
    }
trConceptDocumentation()
QCString TranslatorChinese::trConceptDocumentation () inline override virtual
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2282 of file translator_cn.h.
    { return ""; }
trConceptIndex()
QCString TranslatorChinese::trConceptIndex () inline override virtual
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2278 of file translator_cn.h.
    { return ""; }
trConceptList()
QCString TranslatorChinese::trConceptList () inline override virtual
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2274 of file translator_cn.h.
    { return ""; }
trConceptListDescription()
QCString TranslatorChinese::trConceptListDescription (bool extractAll) inline override virtual
used as an introduction to the concept list
Implements Translator.
Definition at line 2286 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=", :";
      return result;
    }
trConceptReference()
QCString TranslatorChinese::trConceptReference (const QCString & conceptName) inline override virtual
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2266 of file translator_cn.h.
    {
      QCString result=conceptName;
      result+=CN_SPC "";
      return result;
    }
References CN_SPC.
trConstantDocumentation()
QCString TranslatorChinese::trConstantDocumentation () inline override virtual
Implements Translator.
Definition at line 2121 of file translator_cn.h.
    {
        return "";
    }
trConstantGroupReference()
QCString TranslatorChinese::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1990 of file translator_cn.h.
    {
      QCString result=namespaceName;
      result+= CN_SPC "";
      return result;
    }
References CN_SPC.
trConstantGroups()
QCString TranslatorChinese::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1986 of file translator_cn.h.
    { return ""; }
trConstants()
QCString TranslatorChinese::trConstants () inline override virtual
Implements Translator.
Definition at line 2117 of file translator_cn.h.
    {
        return "";
    }
trConstructorDocumentation()
QCString TranslatorChinese::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 834 of file translator_cn.h.
    {
      return "";
    }
trCopyright()
QCString TranslatorChinese::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1873 of file translator_cn.h.
    { return ""; }
trCopyToClipboard()
QCString TranslatorChinese::trCopyToClipboard () inline override virtual
Implements Translator.
Definition at line 2607 of file translator_cn.h.
    {
      return "";
    }
trCustomReference()
QCString TranslatorChinese::trCustomReference (const QCString & name) inline override virtual
Implements Translator.
Definition at line 2113 of file translator_cn.h.
    { return QCString(name)+" "; }
trDataMemberDocumentation()
QCString TranslatorChinese::trDataMemberDocumentation () inline override virtual
Implements Translator.
Definition at line 2243 of file translator_cn.h.
    {
        return "";
    }
trDataMembers()
QCString TranslatorChinese::trDataMembers () inline override virtual
Implements Translator.
Definition at line 2239 of file translator_cn.h.
    {
        return "";
    }
trDataTypes()
QCString TranslatorChinese::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1636 of file translator_cn.h.
    { return ""; }
trDate()
QCString TranslatorChinese::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 523 of file translator_cn.h.
    { return ""; }
trDateTime()
QCString TranslatorChinese::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1824 of file translator_cn.h.
    {
      static const char *days[]   = { "","","","","","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%d" CN_SPC "%s" CN_SPC "%d" CN_SPC "%s",year, months[month-1], day, days[dayOfWeek-1]);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References CN_SPC, Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorChinese::trDayOfWeek (int dayOfWeek, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1846 of file translator_cn.h.
    {
      static const char *days_short[]   = { "", "", "", "", "", "", "" };
      static const char *days_full[]    = { "", "", "", "", "", "", "" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayPeriod()
QCString TranslatorChinese::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1858 of file translator_cn.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period?1:0];
    }
trDeclaration()
QCString TranslatorChinese::trDeclaration () inline override virtual
Implements Translator.
Definition at line 2543 of file translator_cn.h.
{ return "";}
trDefinedAtLineInSourceFile()
QCString TranslatorChinese::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 798 of file translator_cn.h.
    {
      return "" CN_SPC "@1" CN_SPC "" CN_SPC "@0" CN_SPC ".";
    }
References CN_SPC.
trDefinedIn()
QCString TranslatorChinese::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 177 of file translator_cn.h.
    { return "" CN_SPC; }
References CN_SPC.
trDefinedInSourceFile()
QCString TranslatorChinese::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 803 of file translator_cn.h.
    {
      return "" CN_SPC "@0" CN_SPC ".";
    }
References CN_SPC.
trDefineDocumentation()
QCString TranslatorChinese::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 456 of file translator_cn.h.
    { return ""; }
trDefines()
QCString TranslatorChinese::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 420 of file translator_cn.h.
    { return ""; }
trDefineValue()
QCString TranslatorChinese::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1153 of file translator_cn.h.
    {
      return ":";
    }
trDefinition()
QCString TranslatorChinese::trDefinition () inline override virtual
Implements Translator.
Definition at line 2542 of file translator_cn.h.
{ return "";}
trDeprecated()
QCString TranslatorChinese::trDeprecated () inline override virtual
Implements Translator.
Definition at line 812 of file translator_cn.h.
    {
      return "";
    }
trDeprecatedList()
QCString TranslatorChinese::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1350 of file translator_cn.h.
    {
      return "";
    }
trDesignUnitDocumentation()
QCString TranslatorChinese::trDesignUnitDocumentation () inline override virtual
VHDL design unit documentation.
Implements Translator.
Definition at line 2253 of file translator_cn.h.
    { return ""; }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorChinese::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Implements Translator.
Definition at line 2028 of file translator_cn.h.
    { return ""; }
trDesignUnitIndex()
QCString TranslatorChinese::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Implements Translator.
Definition at line 2042 of file translator_cn.h.
    { return ""; }
trDesignUnitList()
QCString TranslatorChinese::trDesignUnitList () inline override virtual
VHDL design unit list.
Implements Translator.
Definition at line 2031 of file translator_cn.h.
    { return ""; }
trDesignUnitListDescription()
QCString TranslatorChinese::trDesignUnitListDescription () inline override virtual
VHDL design unit list description.
Implements Translator.
Definition at line 2037 of file translator_cn.h.
    {
        return ":";
    }
trDesignUnitMembers()
QCString TranslatorChinese::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Implements Translator.
Definition at line 2034 of file translator_cn.h.
    { return ""; }
trDesignUnits()
QCString TranslatorChinese::trDesignUnits () inline override virtual
VHDL design units.
Implements Translator.
Definition at line 2045 of file translator_cn.h.
    { return ""; }
trDetailedDescription()
QCString TranslatorChinese::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 96 of file translator_cn.h.
    { return ""; }
trDetailLevel()
QCString TranslatorChinese::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1887 of file translator_cn.h.
    { return ""; }
trDetails()
QCString TranslatorChinese::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 100 of file translator_cn.h.
    { return ""; }
trDictionaries()
QCString TranslatorChinese::trDictionaries () inline override virtual
Implements Translator.
Definition at line 2133 of file translator_cn.h.
    {
        return "";
    }
trDictionaryDocumentation()
QCString TranslatorChinese::trDictionaryDocumentation () inline override virtual
Implements Translator.
Definition at line 2137 of file translator_cn.h.
    {
        return "";
    }
trDir()
QCString TranslatorChinese::trDir (bool , bool) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1531 of file translator_cn.h.
    {
      return "";
    }
trDirDepGraph()
QCString TranslatorChinese::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1877 of file translator_cn.h.
    {
      return QCString(name)+CN_SPC "";
    }
References CN_SPC.
trDirDocumentation()
QCString TranslatorChinese::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1507 of file translator_cn.h.
    {
      return "";
    }
trDirectories()
QCString TranslatorChinese::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1515 of file translator_cn.h.
    { return ""; }
trDirIndex()
QCString TranslatorChinese::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1499 of file translator_cn.h.
    {
      return "";
    }
trDirReference()
QCString TranslatorChinese::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1521 of file translator_cn.h.
    {
      QCString result=dirName;
      result+=CN_SPC "";
      return result;
    }
References CN_SPC.
trDirRelation()
QCString TranslatorChinese::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1761 of file translator_cn.h.
    {
      // return QCString(name)+" Relation";
      // unsure
      return QCString(name)+CN_SPC "";
    }
References CN_SPC.
trDocumentation()
QCString TranslatorChinese::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 348 of file translator_cn.h.
    { return (!projName.isEmpty()?projName + " " : "") + ""; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorChinese::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 432 of file translator_cn.h.
    { return ""; }
trEnumerationTypeDocumentation()
QCString TranslatorChinese::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 468 of file translator_cn.h.
    { return ""; }
trEnumerationValueDocumentation()
QCString TranslatorChinese::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1562 of file translator_cn.h.
    {
      return "";
    }
trEnumerationValues()
QCString TranslatorChinese::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 450 of file translator_cn.h.
    { return ""; }
trEnumGeneratedFromFiles()
QCString TranslatorChinese::trEnumGeneratedFromFiles (bool) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1899 of file translator_cn.h.
    { return ":"; }
trEnumName()
QCString TranslatorChinese::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 169 of file translator_cn.h.
    { return ""; }
trEnumReference()
QCString TranslatorChinese::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1903 of file translator_cn.h.
    { return QCString(name)+CN_SPC ""; }
References CN_SPC.
trEnumValue()
QCString TranslatorChinese::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 173 of file translator_cn.h.
    { return ""; }
trEventDocumentation()
QCString TranslatorChinese::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1368 of file translator_cn.h.
    {
      return "";
    }
trEvents()
QCString TranslatorChinese::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1362 of file translator_cn.h.
    {
      return "";
    }
trExamples()
QCString TranslatorChinese::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 233 of file translator_cn.h.
    { return ""; }
trExamplesDescription()
QCString TranslatorChinese::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 334 of file translator_cn.h.
    { return ":"; }
trExceptionDocumentation()
QCString TranslatorChinese::trExceptionDocumentation () inline override virtual
Implements Translator.
Definition at line 2209 of file translator_cn.h.
    {
        return "";
    }
trExceptionHierarchy()
QCString TranslatorChinese::trExceptionHierarchy () inline override virtual
Implements Translator.
Definition at line 2201 of file translator_cn.h.
    {
        return "";
    }
trExceptionHierarchyDescription()
QCString TranslatorChinese::trExceptionHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2205 of file translator_cn.h.
    {
        return ":";
    }
trExceptionIndex()
QCString TranslatorChinese::trExceptionIndex () inline override virtual
Implements Translator.
Definition at line 2189 of file translator_cn.h.
    {
        return "";
    }
trExceptionList()
QCString TranslatorChinese::trExceptionList () inline override virtual
Implements Translator.
Definition at line 2193 of file translator_cn.h.
    {
        return "";
    }
trExceptionListDescription()
QCString TranslatorChinese::trExceptionListDescription () inline override virtual
Implements Translator.
Definition at line 2197 of file translator_cn.h.
    {
        return ":";
    }
trExceptions()
QCString TranslatorChinese::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 539 of file translator_cn.h.
    { return ""; }
trExportedModules()
QCString TranslatorChinese::trExportedModules () inline override virtual
Implements Translator.
Definition at line 2598 of file translator_cn.h.
    {
      return "";
    }
trExtendsClass()
QCString TranslatorChinese::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1945 of file translator_cn.h.
    {
      return " @0.";
    }
trFile()
QCString TranslatorChinese::trFile (bool , bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1238 of file translator_cn.h.
    {
      return "";
    }
trFileDocumentation()
QCString TranslatorChinese::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 410 of file translator_cn.h.
    { return ""; }
trFileIn()
QCString TranslatorChinese::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1800 of file translator_cn.h.
    {
      return QCString("")+CN_SPC+name;
    }
References CN_SPC.
trFileIndex()
QCString TranslatorChinese::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 380 of file translator_cn.h.
    { return ""; }
trFileList()
QCString TranslatorChinese::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 204 of file translator_cn.h.
    { return ""; }
trFileListDescription()
QCString TranslatorChinese::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 254 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=":";
      return result;
    }
trFileMembers()
QCString TranslatorChinese::trFileMembers () inline override virtual
This is put above each page as a link to all member of files.
Implements Translator.
Definition at line 219 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "";
      } else {
        return "";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorChinese::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 313 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll)
        result +="";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result +="";
      }
      else {
        result +="";
      }
      result+="";
      if (extractAll)
        result+=":";
      else
        result+=":";
      return result;
    }
References Config_getBool.
trFileMembersDescriptionTotal()
QCString TranslatorChinese::trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2370 of file translator_cn.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="";
      if (!extractAll) result+="";
      switch (hl)
      {
        case FileMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="";
          }
          else
          {
            result+="";
          }
          break;
        case FileMemberHighlight::Functions:
          result+="";
          break;
        case FileMemberHighlight::Variables:
          result+="";
          break;
        case FileMemberHighlight::Typedefs:
          result+="";
          break;
        case FileMemberHighlight::Sequences:
          result+="";
          break;
        case FileMemberHighlight::Dictionaries:
          result+="";
          break;
        case FileMemberHighlight::Enums:
          result+="";
          break;
        case FileMemberHighlight::EnumValues:
          result+="";
          break;
        case FileMemberHighlight::Defines:
          result+="";
          break;
        case FileMemberHighlight::Total: // for completeness
          break;
      }
      result+=", ";
      if (extractAll)
        result+="";
      else
        result+="";
      result+=":" CN_SPC;
      return result;
    }
References FileMemberHighlight::All, CN_SPC, Config_getBool, FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, FileMemberHighlight::Sequences, FileMemberHighlight::Total, FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
trFileReference()
QCString TranslatorChinese::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 606 of file translator_cn.h.
    {
      QCString result=fileName;
      result+=CN_SPC "";
      return result;
    }
References CN_SPC.
trFlowchart()
QCString TranslatorChinese::trFlowchart () inline override virtual
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2314 of file translator_cn.h.
    { return ":"; }
trFriends()
QCString TranslatorChinese::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 566 of file translator_cn.h.
    { return ""; }
trFunctionAndProc()
QCString TranslatorChinese::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Implements Translator.
Definition at line 2048 of file translator_cn.h.
    { return "//"; }
trFunctionDocumentation()
QCString TranslatorChinese::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 474 of file translator_cn.h.
    { return ""; }
trFunctions()
QCString TranslatorChinese::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 438 of file translator_cn.h.
    { return ""; }
trGeneratedAt()
QCString TranslatorChinese::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 500 of file translator_cn.h.
    {
      QCString result="" CN_SPC+date;
      if (!projName.isEmpty()) result+=CN_SPC ", " CN_SPC+projName;
      result+="" CN_SPC;
      return result;
    }
References CN_SPC, and QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorChinese::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 160 of file translator_cn.h.
    { QCString result;
      result = "" CN_SPC "Doyxgen" CN_SPC "" CN_SPC;
      if (!s.isEmpty()) result += (s+CN_SPC "" CN_SPC);
      result+= ".";
      return result;
    }
References CN_SPC, and QCString::isEmpty().
trGeneratedBy()
QCString TranslatorChinese::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 543 of file translator_cn.h.
    { return ""; }
trGeneratedFromFiles()
QCString TranslatorChinese::trGeneratedFromFiles (ClassDef::CompoundType compType, bool) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 755 of file translator_cn.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class:      result+=vhdlOpt?"":""; break;
        case ClassDef::Struct:     result+=""; break;
        case ClassDef::Union:      result+=""; break;
        case ClassDef::Interface:  result+=""; break;
        case ClassDef::Protocol:   result+=""; break;
        case ClassDef::Category:   result+=""; break;
        case ClassDef::Exception:  result+=""; break;
        default: break;
      }
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorChinese::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1713 of file translator_cn.h.
    {
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class:      result+=CN_SPC ""; break;
        case ClassDef::Struct:     result+=CN_SPC ""; break;
        case ClassDef::Union:      result+=CN_SPC ""; break;
        case ClassDef::Interface:  result+=CN_SPC ""; break;
        case ClassDef::Protocol:   result+=CN_SPC ""; break;
        case ClassDef::Category:   result+=CN_SPC ""; break;
        case ClassDef::Exception:  result+=CN_SPC ""; break;
        default: break;
      }
      result+=CN_SPC ":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, CN_SPC, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorChinese::trGlobal (bool , bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1284 of file translator_cn.h.
    {
      return "";
    }
trGlobalNamespace()
QCString TranslatorChinese::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1775 of file translator_cn.h.
    {
      return "";
    }
trGotoDocumentation()
QCString TranslatorChinese::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 846 of file translator_cn.h.
    {
      return ".";
    }
trGotoGraphicalHierarchy()
QCString TranslatorChinese::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 886 of file translator_cn.h.
    {
      return "";
    }
trGotoSourceCode()
QCString TranslatorChinese::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 840 of file translator_cn.h.
    {
      return ".";
    }
trGotoTextualHierarchy()
QCString TranslatorChinese::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 891 of file translator_cn.h.
    {
      return "";
    }
trGraphicalHierarchy()
QCString TranslatorChinese::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 881 of file translator_cn.h.
    {
      return "";
    }
trGroup()
QCString TranslatorChinese::trGroup (bool , bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1257 of file translator_cn.h.
    {
      return "";
    }
trHierarchicalIndex()
QCString TranslatorChinese::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 360 of file translator_cn.h.
    { return ""; }
trImplementedFromList()
QCString TranslatorChinese::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1318 of file translator_cn.h.
    {
      return "" CN_SPC+trWriteList(numEntries)+".";
    }
References CN_SPC, and trWriteList().
trImplementedInList()
QCString TranslatorChinese::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1326 of file translator_cn.h.
    {
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trImportant()
QCString TranslatorChinese::trImportant () inline override virtual
Implements Translator.
Definition at line 2614 of file translator_cn.h.
    {
      return "";
    }
trInclByDepGraph()
QCString TranslatorChinese::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 998 of file translator_cn.h.
    {
      return ":";
    }
trInclDepGraph()
QCString TranslatorChinese::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 828 of file translator_cn.h.
    {
      return fName+CN_SPC "(Include):";
    }
References CN_SPC.
trIncludesFileIn()
QCString TranslatorChinese::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1809 of file translator_cn.h.
    {
      return "" CN_SPC+name+CN_SPC "";
    }
References CN_SPC.
trIncludingInheritedMembers()
QCString TranslatorChinese::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 154 of file translator_cn.h.
    { return ","; }
trInheritedByList()
QCString TranslatorChinese::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 686 of file translator_cn.h.
    {
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trInheritedFrom()
QCString TranslatorChinese::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1907 of file translator_cn.h.
    { return QCString(members)+CN_SPC "" CN_SPC+what; }
References CN_SPC.
trInheritsList()
QCString TranslatorChinese::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 680 of file translator_cn.h.
    { return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";  }
References CN_SPC, and trWriteList().
trInitialValue()
QCString TranslatorChinese::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 870 of file translator_cn.h.
    {
      return ":";
    }
trInstanceMethods()
QCString TranslatorChinese::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1961 of file translator_cn.h.
    {
      return "";
    }
trInterfaceDocumentation()
QCString TranslatorChinese::trInterfaceDocumentation () inline override virtual
Implements Translator.
Definition at line 2165 of file translator_cn.h.
    {
        return "";
    }
trInterfaceHierarchy()
QCString TranslatorChinese::trInterfaceHierarchy () inline override virtual
Implements Translator.
Definition at line 2157 of file translator_cn.h.
    {
        return "";
    }
trInterfaceHierarchyDescription()
QCString TranslatorChinese::trInterfaceHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2161 of file translator_cn.h.
    {
        return ":";
    }
trInterfaceIndex()
QCString TranslatorChinese::trInterfaceIndex () inline override virtual
Implements Translator.
Definition at line 2145 of file translator_cn.h.
    {
        return "";
    }
trInterfaceList()
QCString TranslatorChinese::trInterfaceList () inline override virtual
Implements Translator.
Definition at line 2149 of file translator_cn.h.
    {
        return "";
    }
trInterfaceListDescription()
QCString TranslatorChinese::trInterfaceListDescription () inline override virtual
Implements Translator.
Definition at line 2153 of file translator_cn.h.
    {
        return ":";
    }
trInterfaces()
QCString TranslatorChinese::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1978 of file translator_cn.h.
    { return ""; }
trInvariant()
QCString TranslatorChinese::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 864 of file translator_cn.h.
    {
      return "";
    }
trISOLang()
QCString TranslatorChinese::trISOLang () inline override virtual
Implements Translator.
Definition at line 58 of file translator_cn.h.
    {
      return "zh";
    }
trLegend()
QCString TranslatorChinese::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1079 of file translator_cn.h.
    {
      return "";
    }
trLegendDocs()
QCString TranslatorChinese::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1021 of file translator_cn.h.
    {
      return
        "" CN_SPC "doxygen" CN_SPC ".<p>\n"
        ":\n"
        "\\code\n"
        "/*! " CN_SPC "Invisible" CN_SPC " */\n"
        "class Invisible { };\n\n"
        "/*! Truncated" CN_SPC " */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* " CN_SPC "doxygen" CN_SPC " */\n"
        "class Undocumented { };\n\n"
        "/*! public" CN_SPC " */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*!  */\n"
        "template<class T> class Templ { };\n\n"
        "/*! protected" CN_SPC " */\n"
        "class ProtectedBase { };\n\n"
        "/*! private" CN_SPC " */\n"
        "class PrivateBase { };\n\n"
        "/*! " CN_SPC "Inherited" CN_SPC " */\n"
        "class Used { };\n\n"
        "/*!  */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        ":"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        ":\n"
        "</p>\n"
        "<ul>\n"
        "<li>% .</li>\n"
        "<li>% .</li>\n"
        "<li>% .</li>\n"
        "<li>% ."
        "%.</li>\n"
        "</ul>\n"
        "<p>\n"
        ":\n"
        "</p>\n"
        "<ul>\n"
        "<li>% " CN_SPC "public" CN_SPC ".</li>\n"
        "<li>% " CN_SPC "protected" CN_SPC ".</li>\n"
        "<li>% " CN_SPC "private" CN_SPC ".</li>\n"
        "<li>% . .</li>\n"
        "<li>% . .</li>\n"
        "</ul>\n";
    }
References CN_SPC, and getDotImageExtension().
trLegendTitle()
QCString TranslatorChinese::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 1013 of file translator_cn.h.
    {
      return "";
    }
trListOfAllMembers()
QCString TranslatorChinese::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 142 of file translator_cn.h.
    { return ""; }
trLoading()
QCString TranslatorChinese::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1769 of file translator_cn.h.
    {
      return "...";
    }
trMainPage()
QCString TranslatorChinese::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 785 of file translator_cn.h.
    { return ""; }
trMember()
QCString TranslatorChinese::trMember (bool , bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1275 of file translator_cn.h.
    {
      return "";
    }
trMemberDataDocumentation()
QCString TranslatorChinese::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 125 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorChinese::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 108 of file translator_cn.h.
    { return ""; }
trMemberFunctionDocumentation()
QCString TranslatorChinese::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member function.
Implements Translator.
Definition at line 112 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "//";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran()
QCString TranslatorChinese::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1572 of file translator_cn.h.
    { return "/"; }
trMemberList()
QCString TranslatorChinese::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 146 of file translator_cn.h.
    { return ""; }
trMemberTypedefDocumentation()
QCString TranslatorChinese::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 104 of file translator_cn.h.
    { return ""; }
trMethodDocumentation()
QCString TranslatorChinese::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1968 of file translator_cn.h.
    {
      return "";
    }
trModule()
QCString TranslatorChinese::trModule (bool , bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1706 of file translator_cn.h.
    {
      return "";
    }
trModuleDocumentation()
QCString TranslatorChinese::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 386 of file translator_cn.h.
    { return ""; }
trModuleIndex()
QCString TranslatorChinese::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 354 of file translator_cn.h.
    { return ""; }
trModuleMembersDescriptionTotal()
QCString TranslatorChinese::trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2559 of file translator_cn.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="";
      if (!extractAll) result+="";
      result+="";
      QCString singularResult = "";
      switch (hl)
      {
        case ModuleMemberHighlight::All:
          singularResult="";
          break;
        case ModuleMemberHighlight::Functions:
          singularResult="";
          break;
        case ModuleMemberHighlight::Variables:
          singularResult="";
          break;
        case ModuleMemberHighlight::Typedefs:
          singularResult="";
          break;
        case ModuleMemberHighlight::Enums:
          singularResult="";
          break;
        case ModuleMemberHighlight::EnumValues:
          singularResult="";
          break;
        case ModuleMemberHighlight::Total: // for completeness
          break;
      }
      result+=singularResult;
      result+=", ";
      if (extractAll)
        result+="" + singularResult + "";
      else
        result+="";
      result+=":" CN_SPC;
      return result;
    }
References ModuleMemberHighlight::All, CN_SPC, Config_getBool, ModuleMemberHighlight::Enums, ModuleMemberHighlight::EnumValues, ModuleMemberHighlight::Functions, ModuleMemberHighlight::Total, ModuleMemberHighlight::Typedefs, and ModuleMemberHighlight::Variables.
trModuleReference()
QCString TranslatorChinese::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1675 of file translator_cn.h.
    {
      QCString result=namespaceName;
      result += CN_SPC "";
      return result;
    }
References CN_SPC.
trModules()
QCString TranslatorChinese::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 185 of file translator_cn.h.
    { return ""; }
trModulesDescription()
QCString TranslatorChinese::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 342 of file translator_cn.h.
    { return ":"; }
trModulesIndex()
QCString TranslatorChinese::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1699 of file translator_cn.h.
    { return ""; }
trModulesList()
QCString TranslatorChinese::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1640 of file translator_cn.h.
    { return ""; }
trModulesListDescription()
QCString TranslatorChinese::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1644 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=":";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorChinese::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1687 of file translator_cn.h.
    {
      if(!extractAll) {
        return ":";
      } else {
        return ":";
      }
    }
trModulesMembers()
QCString TranslatorChinese::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1683 of file translator_cn.h.
    { return ""; }
trMonth()
QCString TranslatorChinese::trMonth (int month, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1852 of file translator_cn.h.
    {
      static const char *months_short[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
      static const char *months_full[]  = { "", "", "", "", "", "", "", "", "", "", "", "" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMore()
QCString TranslatorChinese::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 138 of file translator_cn.h.
    { return "..."; }
trNamespace()
QCString TranslatorChinese::trNamespace (bool , bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1248 of file translator_cn.h.
    {
      return "";
    }
trNamespaceDocumentation()
QCString TranslatorChinese::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 733 of file translator_cn.h.
    { return ""; }
trNamespaceIndex()
QCString TranslatorChinese::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 727 of file translator_cn.h.
    { return ""; }
trNamespaceList()
QCString TranslatorChinese::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 551 of file translator_cn.h.
    { return ""; }
trNamespaceListDescription()
QCString TranslatorChinese::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 555 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=":";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorChinese::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 712 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+="";
      if (extractAll)
        result+=":";
      else
        result+=":";
      return result;
    }
trNamespaceMembers()
QCString TranslatorChinese::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 708 of file translator_cn.h.
    { return ""; }
trNamespaceMembersDescriptionTotal()
QCString TranslatorChinese::trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2497 of file translator_cn.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="";
      if (!extractAll) result+="";
      result+="";
      QCString singularResult = "";
      switch (hl)
      {
        case NamespaceMemberHighlight::All:
          singularResult="";
          break;
        case NamespaceMemberHighlight::Functions:
          singularResult="";
          break;
        case NamespaceMemberHighlight::Variables:
          singularResult="";
          break;
        case NamespaceMemberHighlight::Typedefs:
          singularResult="";
          break;
        case NamespaceMemberHighlight::Sequences:
          singularResult="";
          break;
        case NamespaceMemberHighlight::Dictionaries:
          singularResult="";
          break;
        case NamespaceMemberHighlight::Enums:
          singularResult="";
          break;
        case NamespaceMemberHighlight::EnumValues:
          singularResult="";
          break;
        case NamespaceMemberHighlight::Total: // for completeness
          break;
      }
      result+=singularResult;
      result+=", ";
      if (extractAll)
        result+="" + singularResult + "";
      else
        result+="";
      result+=":" CN_SPC;
      return result;
    }
References NamespaceMemberHighlight::All, CN_SPC, Config_getBool, NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, NamespaceMemberHighlight::Sequences, NamespaceMemberHighlight::Total, NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
trNamespaceReference()
QCString TranslatorChinese::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 614 of file translator_cn.h.
    { QCString result=namespaceName;
      result+=CN_SPC "";
      return result;
    }
References CN_SPC.
trNamespaces()
QCString TranslatorChinese::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 743 of file translator_cn.h.
    {
      return "";
    }
trNoMatches()
QCString TranslatorChinese::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1787 of file translator_cn.h.
    {
      return "";
    }
trNote()
QCString TranslatorChinese::trNote () inline override virtual
Implements Translator.
Definition at line 905 of file translator_cn.h.
    {
      return "";
    }
trOperationDocumentation()
QCString TranslatorChinese::trOperationDocumentation () inline override virtual
Implements Translator.
Definition at line 2235 of file translator_cn.h.
    {
        return "";
    }
trOperations()
QCString TranslatorChinese::trOperations () inline override virtual
Implements Translator.
Definition at line 2231 of file translator_cn.h.
    {
        return "";
    }
trOverloadText()
QCString TranslatorChinese::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1543 of file translator_cn.h.
    {
      return "."
             ".";
    }
trPackage()
QCString TranslatorChinese::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1134 of file translator_cn.h.
    {
      return "" CN_SPC+name;
    }
References CN_SPC.
trPackageAttribs()
QCString TranslatorChinese::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1407 of file translator_cn.h.
    {
      return "";
    }
trPackageFunctions()
QCString TranslatorChinese::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1387 of file translator_cn.h.
    {
      return "";
    }
trPackageList()
QCString TranslatorChinese::trPackageList () inline override virtual
Implements Translator.
Definition at line 2304 of file translator_cn.h.
    { return ""; }
trPackageListDescription()
QCString TranslatorChinese::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1141 of file translator_cn.h.
    {
       return "():";
    }
trPackageMembers()
QCString TranslatorChinese::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1391 of file translator_cn.h.
    {
      return "";
    }
trPackages()
QCString TranslatorChinese::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1147 of file translator_cn.h.
    {
      return "";
    }
trPackageTypes()
QCString TranslatorChinese::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1379 of file translator_cn.h.
    {
      return "";
    }
trPage()
QCString TranslatorChinese::trPage (bool , bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1266 of file translator_cn.h.
    {
      return "";
    }
trPageAbbreviation()
QCString TranslatorChinese::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 791 of file translator_cn.h.
    { return "p."; }
trPageIndex()
QCString TranslatorChinese::trPageIndex () inline override virtual
Implements Translator.
Definition at line 896 of file translator_cn.h.
    {
      return "";
    }
trPanelSynchronisationTooltip()
QCString TranslatorChinese::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1926 of file translator_cn.h.
    {
      QCString opt = enable ? "" : "";
      return "" CN_SPC+opt+CN_SPC "";
    }
References CN_SPC.
trParameters()
QCString TranslatorChinese::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 535 of file translator_cn.h.
    { return ""; }
trPostcondition()
QCString TranslatorChinese::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 858 of file translator_cn.h.
    {
      return "";
    }
trPrecondition()
QCString TranslatorChinese::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 852 of file translator_cn.h.
    {
      return "";
    }
trPrivateAttribs()
QCString TranslatorChinese::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 952 of file translator_cn.h.
    {
      return "Private ";
    }
trPrivateMembers()
QCString TranslatorChinese::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 642 of file translator_cn.h.
    { return "Private "; }
trPrivateSlots()
QCString TranslatorChinese::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 645 of file translator_cn.h.
    { return "Private "; }
trPrivateTypes()
QCString TranslatorChinese::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 947 of file translator_cn.h.
    {
      return "Private ";
    }
trProperties()
QCString TranslatorChinese::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1105 of file translator_cn.h.
    {
      return "";
    }
trPropertyDocumentation()
QCString TranslatorChinese::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1111 of file translator_cn.h.
    {
      return "";
    }
trProtectedAttribs()
QCString TranslatorChinese::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 937 of file translator_cn.h.
    {
      return "Protected ";
    }
trProtectedMembers()
QCString TranslatorChinese::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 633 of file translator_cn.h.
    { return "Protected "; }
trProtectedSlots()
QCString TranslatorChinese::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 636 of file translator_cn.h.
    { return "Protected "; }
trProtectedTypes()
QCString TranslatorChinese::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 932 of file translator_cn.h.
    {
      return "Protected ";
    }
trProvidedByCategory()
QCString TranslatorChinese::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1936 of file translator_cn.h.
    {
      return " category @0 .";
    }
trPublicAttribs()
QCString TranslatorChinese::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 915 of file translator_cn.h.
    {
       if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
       {
         return "";
       }
       else
       {
         return "Public ";
       }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorChinese::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 621 of file translator_cn.h.
    { return "Public "; }
trPublicSlots()
QCString TranslatorChinese::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 624 of file translator_cn.h.
    { return "Public "; }
trPublicTypes()
QCString TranslatorChinese::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 910 of file translator_cn.h.
    {
      return "Public ";
    }
trReferencedBy()
QCString TranslatorChinese::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 983 of file translator_cn.h.
    {
      return "";
    }
trReferenceManual()
QCString TranslatorChinese::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 414 of file translator_cn.h.
    { return ""; }
trReferences()
QCString TranslatorChinese::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1306 of file translator_cn.h.
    {
      return "";
    }
trReimplementedFromList()
QCString TranslatorChinese::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 694 of file translator_cn.h.
    {
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trReimplementedInList()
QCString TranslatorChinese::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 702 of file translator_cn.h.
    {
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorChinese::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 576 of file translator_cn.h.
    { return ""; }
trRelatedFunctions()
QCString TranslatorChinese::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 86 of file translator_cn.h.
    { return ""; }
trRelatedPages()
QCString TranslatorChinese::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 229 of file translator_cn.h.
    { return ""; }
trRelatedPagesDescription()
QCString TranslatorChinese::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 338 of file translator_cn.h.
    { return ":"; }
trRelatedSubscript()
QCString TranslatorChinese::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 90 of file translator_cn.h.
    { return "(: .)"; }
trRelatedSymbolDocumentation()
QCString TranslatorChinese::trRelatedSymbolDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes.
Supersedes trRelatedFunctionDocumentation
Implements Translator.
Definition at line 2344 of file translator_cn.h.
    { return ""; }
trRelatedSymbols()
QCString TranslatorChinese::trRelatedSymbols () inline override virtual
Please translate also updated body of the method trMemberFunctionDocumentation(), now better adapted for VHDL sources documentation.
used in the compound documentation before a list of related symbols.
Supersedes trRelatedFunctions
Implements Translator.
Definition at line 2329 of file translator_cn.h.
    { return ""; }
trRelatedSymbolsSubscript()
QCString TranslatorChinese::trRelatedSymbolsSubscript () inline override virtual
subscript for the related symbols
Supersedes trRelatedSubscript
Implements Translator.
Definition at line 2336 of file translator_cn.h.
    { return "(: .)"; }
trRemarks()
QCString TranslatorChinese::trRemarks () inline override virtual
Implements Translator.
Definition at line 988 of file translator_cn.h.
    {
      return "";
    }
trReturns()
QCString TranslatorChinese::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 527 of file translator_cn.h.
    { return ""; }
trReturnValues()
QCString TranslatorChinese::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 780 of file translator_cn.h.
    { return ""; }
trRTFansicp()
QCString TranslatorChinese::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1201 of file translator_cn.h.
    {
      return "936";
    }
trRTFCharSet()
QCString TranslatorChinese::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1209 of file translator_cn.h.
    {
      return "134";
    }
trRTFGeneralIndex()
QCString TranslatorChinese::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1216 of file translator_cn.h.
    {
      return "";
    }
trRTFTableOfContents()
QCString TranslatorChinese::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1338 of file translator_cn.h.
    {
      return "";
    }
trSearch()
QCString TranslatorChinese::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 237 of file translator_cn.h.
    { return ""; }
trSearching()
QCString TranslatorChinese::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1781 of file translator_cn.h.
    {
      return "...";
    }
trSearchMatches()
QCString TranslatorChinese::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1477 of file translator_cn.h.
    {
      return ":";
    }
trSearchResults()
QCString TranslatorChinese::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1458 of file translator_cn.h.
    {
      if (numDocuments==0)
      {
        return ",.";
      }
      else if (numDocuments==1)
      {
        return "<b>1</b>.";
      }
      else
      {
        return "<b>$num</b>."
               ".";
      }
    }
trSearchResultsTitle()
QCString TranslatorChinese::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1445 of file translator_cn.h.
    {
      return "";
    }
trSeeAlso()
QCString TranslatorChinese::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 531 of file translator_cn.h.
    { return ""; }
trSequenceDocumentation()
QCString TranslatorChinese::trSequenceDocumentation () inline override virtual
Implements Translator.
Definition at line 2129 of file translator_cn.h.
    {
        return "";
    }
trSequences()
QCString TranslatorChinese::trSequences () inline override virtual
Implements Translator.
Definition at line 2125 of file translator_cn.h.
    {
        return "";
    }
trServiceGeneratedFromFiles()
QCString TranslatorChinese::trServiceGeneratedFromFiles (bool) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 2011 of file translator_cn.h.
    {
      // single is true implies a single file
      return ":";
    }
trServiceReference()
QCString TranslatorChinese::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 1997 of file translator_cn.h.
    {
      QCString result=sName;
      result+= CN_SPC "";
      return result;
    }
References CN_SPC.
trServices()
QCString TranslatorChinese::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1982 of file translator_cn.h.
    { return ""; }
trSignals()
QCString TranslatorChinese::trSignals () inline override virtual
Implements Translator.
Definition at line 627 of file translator_cn.h.
    { return ""; }
trSince()
QCString TranslatorChinese::trSince () inline override virtual
Implements Translator.
Definition at line 1003 of file translator_cn.h.
    {
      return "";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorChinese::trSingletonGeneratedFromFiles (bool) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 2017 of file translator_cn.h.
    {
      // single is true implies a single file
      return ":";
    }
trSingletonReference()
QCString TranslatorChinese::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 2004 of file translator_cn.h.
    {
      QCString result=sName;
      result+= CN_SPC "";
      return result;
    }
References CN_SPC.
trSliceInterfaces()
QCString TranslatorChinese::trSliceInterfaces () inline override virtual
Implements Translator.
Definition at line 2141 of file translator_cn.h.
    {
        return "";
    }
trSourceFile()
QCString TranslatorChinese::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1488 of file translator_cn.h.
    {
      return filename + CN_SPC "";
    }
References CN_SPC.
trStaticPackageAttribs()
QCString TranslatorChinese::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1415 of file translator_cn.h.
    {
      return "";
    }
trStaticPackageFunctions()
QCString TranslatorChinese::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1399 of file translator_cn.h.
    {
      return "";
    }
trStaticPrivateAttribs()
QCString TranslatorChinese::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 957 of file translator_cn.h.
    {
      return " Private ";
    }
trStaticPrivateMembers()
QCString TranslatorChinese::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 648 of file translator_cn.h.
    { return " Private "; }
trStaticProtectedAttribs()
QCString TranslatorChinese::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 942 of file translator_cn.h.
    {
      return " Protected ";
    }
trStaticProtectedMembers()
QCString TranslatorChinese::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 639 of file translator_cn.h.
    { return " Protected "; }
trStaticPublicAttribs()
QCString TranslatorChinese::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 927 of file translator_cn.h.
    {
      return " Public ";
    }
trStaticPublicMembers()
QCString TranslatorChinese::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 630 of file translator_cn.h.
    { return " Public "; }
trStructDocumentation()
QCString TranslatorChinese::trStructDocumentation () inline override virtual
Implements Translator.
Definition at line 2185 of file translator_cn.h.
    {
        return "";
    }
trStructIndex()
QCString TranslatorChinese::trStructIndex () inline override virtual
Implements Translator.
Definition at line 2173 of file translator_cn.h.
    {
        return "";
    }
trStructList()
QCString TranslatorChinese::trStructList () inline override virtual
Implements Translator.
Definition at line 2177 of file translator_cn.h.
    {
        return "";
    }
trStructListDescription()
QCString TranslatorChinese::trStructListDescription () inline override virtual
Implements Translator.
Definition at line 2181 of file translator_cn.h.
    {
        return ":";
    }
trStructs()
QCString TranslatorChinese::trStructs () inline override virtual
Implements Translator.
Definition at line 2169 of file translator_cn.h.
    {
        return "";
    }
trSubprogram()
QCString TranslatorChinese::trSubprogram (bool , bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1745 of file translator_cn.h.
    {
      return "";
    }
trSubprogramDocumentation()
QCString TranslatorChinese::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1629 of file translator_cn.h.
    { return "/"; }
trSubprograms()
QCString TranslatorChinese::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1623 of file translator_cn.h.
    { return "/"; }
trTemplateParameters()
QCString TranslatorChinese::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1891 of file translator_cn.h.
    { return ""; }
trTest()
QCString TranslatorChinese::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1089 of file translator_cn.h.
    {
      return "";
    }
trTestList()
QCString TranslatorChinese::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1095 of file translator_cn.h.
    {
      return "";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorChinese::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 150 of file translator_cn.h.
    { return ""; }
trTodo()
QCString TranslatorChinese::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 968 of file translator_cn.h.
    {
      return "";
    }
trTodoList()
QCString TranslatorChinese::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 974 of file translator_cn.h.
    {
      return "";
    }
trTopicDocumentation()
QCString TranslatorChinese::trTopicDocumentation () inline override virtual
Implements Translator.
Definition at line 2551 of file translator_cn.h.
    { return ""; }
trTopicIndex()
QCString TranslatorChinese::trTopicIndex () inline override virtual
Implements Translator.
Definition at line 2555 of file translator_cn.h.
    { return ""; }
trTopicList()
QCString TranslatorChinese::trTopicList () inline override virtual
Implements Translator.
Definition at line 2553 of file translator_cn.h.
    { return ""; }
trTopicListDescription()
QCString TranslatorChinese::trTopicListDescription () inline override virtual
Implements Translator.
Definition at line 2557 of file translator_cn.h.
    { return ":"; }
trTopics()
QCString TranslatorChinese::trTopics () inline override virtual
Implements Translator.
Definition at line 2549 of file translator_cn.h.
    { return ""; }
trType()
QCString TranslatorChinese::trType (bool , bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1736 of file translator_cn.h.
    {
      return "";
    }
Referenced by trCompoundType().
trTypeConstraints()
QCString TranslatorChinese::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1751 of file translator_cn.h.
    {
      return "";
    }
trTypedefDocumentation()
QCString TranslatorChinese::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 462 of file translator_cn.h.
    { return ""; }
trTypedefs()
QCString TranslatorChinese::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 426 of file translator_cn.h.
    { return ""; }
trTypeDocumentation()
QCString TranslatorChinese::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1617 of file translator_cn.h.
    { return ""; }
trVariableDocumentation()
QCString TranslatorChinese::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 480 of file translator_cn.h.
    { return ""; }
trVariables()
QCString TranslatorChinese::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 444 of file translator_cn.h.
    { return ""; }
trVersion()
QCString TranslatorChinese::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 519 of file translator_cn.h.
    { return ""; }
trVhdlType()
QCString TranslatorChinese::trVhdlType (VhdlSpecifier type, bool) inline override virtual
VHDL type.
Implements Translator.
Definition at line 2051 of file translator_cn.h.
    {
      switch(type)
      {
        case VhdlSpecifier::LIBRARY:
          return "";
        case VhdlSpecifier::PACKAGE:
          return "";
        case VhdlSpecifier::SIGNAL:
          return "";
        case VhdlSpecifier::COMPONENT:
          return "";
        case VhdlSpecifier::CONSTANT:
          return "";
        case VhdlSpecifier::ENTITY:
          return "";
        case VhdlSpecifier::TYPE:
          return "";
        case VhdlSpecifier::SUBTYPE:
          return "";
        case VhdlSpecifier::FUNCTION:
          return "";
        case VhdlSpecifier::RECORD:
          return "";
        case VhdlSpecifier::PROCEDURE:
          return "";
        case VhdlSpecifier::ARCHITECTURE:
          return "";
        case VhdlSpecifier::ATTRIBUTE:
          return "";
        case VhdlSpecifier::PROCESS:
          return "";
        case VhdlSpecifier::PORT:
          return "";
        case VhdlSpecifier::USE:
          return "";
        case VhdlSpecifier::GENERIC:
          return "";
        case VhdlSpecifier::PACKAGE_BODY:
          return "";
        case VhdlSpecifier::UNITS:
          return "";
        case VhdlSpecifier::SHAREDVARIABLE:
          return "";
        case VhdlSpecifier::VFILE:
          return "";
        case VhdlSpecifier::GROUP:
          return "";
        case VhdlSpecifier::INSTANTIATION:
          return "";
        case VhdlSpecifier::ALIAS:
          return "";
        case VhdlSpecifier::CONFIG:
          return " ";
        case VhdlSpecifier::MISCELLANEOUS:
          return "";
        case VhdlSpecifier::UCF_CONST:
          return "";
        default:
          return "";
      }
    }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorChinese::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 515 of file translator_cn.h.
    { return ""; }
trWriteList()
QCString TranslatorChinese::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 656 of file translator_cn.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+="," CN_SPC;
          else                // the fore last entry
            result+=CN_SPC ", " CN_SPC;
        }
      }
      return result;
    }
References CN_SPC, and generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_cn.h