Doxygen: /home/runner/work/doxygen/doxygen/src/section.h File Reference
section.h File Reference
#include <string>
#include <unordered_map>
#include "qcstring.h"
#include "linkedmap.h"
Classes
class SectionInfo
class that provide information about a section.
class SectionRefs
class that represents a list of constant references to sections.
class SectionManager
singleton class that owns the list of all sections
Enumerations
enum class SectionType {
Page = 0 , Section = 1 , Subsection = 2 , Subsubsection = 3 ,
Paragraph = 4 , Anchor = 5 , Table = 6
}
enum representing the various types of sections and entities that can be referred to.
Functions
constexpr bool isSection (SectionType type)
return true if type is a section, and false if it is a page, anchor or table.
Enumeration Type Documentation
SectionType
enum class SectionType strong
enum representing the various types of sections and entities that can be referred to.
Enumerator
Page
Section
Subsection
Subsubsection
Paragraph
Anchor
Table
Definition at line 28 of file section.h.
{
  Page          = 0,
  Section       = 1,
  Subsection    = 2,
  Subsubsection = 3,
  Paragraph     = 4,
  Anchor        = 5,
  Table         = 6
};
Function Documentation
isSection()
constexpr bool isSection (SectionType type) inline constexpr
return true if type is a section, and false if it is a page, anchor or table.
Definition at line 40 of file section.h.
{
  return (type==SectionType::Section       ||
          type==SectionType::Subsection    ||
          type==SectionType::Subsubsection ||
          type==SectionType::Paragraph);
}
References Paragraph, Section, Subsection, and Subsubsection.
Referenced by DefinitionImpl::addSectionsToIndex(), generateXMLForPage(), DefinitionImpl::hasSections(), DocbookGenerator::writeLocalToc(), and HtmlGenerator::writeLocalToc().