Doxygen: TranslatorFinnish Class Reference
TranslatorFinnish Class Reference
#include <src/translator_fi.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
Public Member Functions inherited from TranslatorAdapter_1_6_0
QCString updateNeededMessage () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
Public Member Functions inherited from TranslatorAdapter_1_7_5
QCString updateNeededMessage () override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Public Member Functions inherited from TranslatorAdapter_1_8_0
QCString updateNeededMessage () override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 89 of file translator_fi.h.
Member Function Documentation
getLanguageString()
QCString TranslatorFinnish::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 126 of file translator_fi.h.
    {
      return "0x40B Finnish";
    }
idLanguage()
QCString TranslatorFinnish::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 100 of file translator_fi.h.
    { return "finnish"; }
latexLanguageSupportCommand()
QCString TranslatorFinnish::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 117 of file translator_fi.h.
    {
      return "\\usepackage[finnish]{babel}\n";
    }
trAll()
QCString TranslatorFinnish::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1488 of file translator_fi.h.
    {
      return "Kaikki"; // "All"
    }
trAttention()
QCString TranslatorFinnish::trAttention () inline override virtual
Implements Translator.
Definition at line 1017 of file translator_fi.h.
    {
      return "Huomio"; // "Attention"
    }
trAuthor()
QCString TranslatorFinnish::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1361 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "tekij", "t");
    }
References Translator::createNoun().
trBug()
QCString TranslatorFinnish::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1233 of file translator_fi.h.
    {
      return "Bugi"; // "Bug"
    }
trBugList()
QCString TranslatorFinnish::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1238 of file translator_fi.h.
    {
      return "Bugilista"; // "Bug List"
    }
trCallerGraph()
QCString TranslatorFinnish::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1611 of file translator_fi.h.
    {
      return "Tss on kutsukaavio tlle funktiolle:"; // "Here is the caller graph for this function:"
    }
trCallGraph()
QCString TranslatorFinnish::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1493 of file translator_fi.h.
    {
      return "Tss on kutsukaavio tlle funktiolle:"; // "Here is the call graph for this function:"
    }
trClass()
QCString TranslatorFinnish::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1296 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "luok", "at", "ka");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorFinnish::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 570 of file translator_fi.h.
    {
      return "Luokan "+clName+" luokkakaavio"; // "Inheritance diagram for "
    }
trClassDocumentation()
QCString TranslatorFinnish::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 447 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueiden dokumentaatio"; // "Data Structure Documentation"
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Luokkien dokumentaatio"; // "Class Documentation"
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorFinnish::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1196 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueet"; // "Data Structures"
      }
      else
      {
        return "Luokat"; // "Classes"
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorFinnish::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 230 of file translator_fi.h.
    { return "Luokkahierarkia"; } // "Class Hierarchy"
trClassHierarchyDescription()
QCString TranslatorFinnish::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 289 of file translator_fi.h.
    { return "Tm periytymislista on ptasoltaan aakkostettu " // "This inheritance list is sorted roughly, "
             "mutta alijsenet on aakkostettu itsenisesti:"; // "but not completely, alphabetically:";
    }
trCode()
QCString TranslatorFinnish::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 916 of file translator_fi.h.
    {
      return "koodi"; // "code"
    }
trCollaborationDiagram()
QCString TranslatorFinnish::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 871 of file translator_fi.h.
    {
      return "Yhteistykaavio luokalle "+clName+":"; // "Collaboration diagram for "+clName+":"
    }
trCompoundIndex()
QCString TranslatorFinnish::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 420 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueluettelo"; // "Data Structure Index"
      }
      else
      {
        return "Luokkaluettelo"; // "Class Index"
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorFinnish::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1666 of file translator_fi.h.
    { return "Tietotyyppien hakemisto"; } // "Data Type Index"
trCompoundList()
QCString TranslatorFinnish::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 234 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueet"; // "Data Structures"
      }
      else
      {
        return "Luokkalista"; // "Class List"
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorFinnish::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 304 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tss ovat tietueet lyhyen selitteen kanssa:"; // "Here are the data structures with brief descriptions:"
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Tss ovat luokat " // "Here are the classes
             "lyhyen selitteen kanssa:"; // "with brief descriptions:"
      }
      else
      {
        return "Tss ovat luokat, tietueet ja " // "Here are the classes, structs and "
             "yhdisteet lyhyen selitteen kanssa:"; // "unions with brief descriptions:"
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorFinnish::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1639 of file translator_fi.h.
    { return "Tss ovat tietotyypit lyhyiden selitysten kanssa:"; } // "Here are the data types with brief descriptions:"
trCompoundListFortran()
QCString TranslatorFinnish::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1631 of file translator_fi.h.
    { return "Tietotyyppien lista"; } // "Data Types List"
trCompoundMembers()
QCString TranslatorFinnish::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 251 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueen kentt"; // "Data Fields"
      }
      else
      {
        return "Luokan jsenet"; // "Class Members"
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorFinnish::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 324 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll)
      {
        result+="dokumentoiduista "; // "documented "
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="tietuiden ja yhdisteiden kentist"; // "struct and union fields"
      }
      else
      {
        result+="luokkien jsenist"; // "class members"
      }
      result+=" linkitettyin "; // " with links to "
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="jokaisen kentn tietueen/yhdisteen dokumentaatioon:"; // "the struct/union documentation for each field:"
        }
        else
        {
          result+="jokaisen jsenen luokkadokumentaatioon:"; // "the class documentation for each member:"
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+= "tietueisiin/yhdisteisiin, joihin ne kuuluvat:"; // "the structures/unions they belong to:"
        }
        else
        {
          result+="luokkiin, joihin ne kuuluvat"; //"the classes they belong to:"
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorFinnish::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1643 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll)
      {
        result+="dokumentoiduista "; // "documented "
      }
      result+="tietotyyppien jsenist"; // "data types members"
      result+=", sek linkit "; // " with links to "
      if (!extractAll)
      {
         result+="tietueen dokumentaatioon jokaiselle jsenelle"; // "the data structure documentation for each member"
      }
      else
      {
         result+="tietotyyppeihin, joihin ne kuuluvat:"; // "the data types they belong to:"
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorFinnish::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1635 of file translator_fi.h.
    { return "Kentt"; } // "Data Fields";
trCompoundReference()
QCString TranslatorFinnish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 645 of file translator_fi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" luokka"; break; // " Class"
        case ClassDef::Struct:     result+=" tietue"; break; // " Struct"
        case ClassDef::Union:      result+=" yhdiste"; break; // " Union"
        case ClassDef::Interface:  result+=" rajapinta"; break; // " Interface"
        case ClassDef::Protocol:   result+=" protokolla"; break; // " Protocol"
        case ClassDef::Category:   result+=" kategoria"; break; // " Category"
        case ClassDef::Exception:  result+=" poikkeus"; break; // " Exception"
        default: break;
      }
      if (isTemplate) result+="malli"; // " Template"
      result+="referenssi"; // " Reference"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorFinnish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1707 of file translator_fi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" moduuli"; break; // " Module"
        case ClassDef::Struct:     result+=" tyyppi"; break; // " Type"
        case ClassDef::Union:      result+=" yhdiste"; break; // " Union"
        case ClassDef::Interface:  result+=" rajapinta"; break; // " Interface"
        case ClassDef::Protocol:   result+=" protokolla"; break; // " Protocol"
        case ClassDef::Category:   result+=" kategoria"; break; // " Category"
        case ClassDef::Exception:  result+=" poikkeus"; break; // " Exception"
        default: break;
      }
      if (isTemplate) result+="malli"; // " Template"
      result+="referenssi"; // " Reference"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorFinnish::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 542 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueet"; // "Data Structures"
      }
      else
      {
        return "Luokat"; // "Classes"
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorFinnish::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 881 of file translator_fi.h.
    {
      return "Rakentajien & purkajien dokumentaatio"; // "Constructor & Destructor Documentation";
    }
trDataTypes()
QCString TranslatorFinnish::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1690 of file translator_fi.h.
    { return "Tietotyypit"; } // "Data Types"
trDate()
QCString TranslatorFinnish::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 584 of file translator_fi.h.
    { return "Pivys"; } // "Date"
trDayOfWeek()
QCString TranslatorFinnish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1816 of file translator_fi.h.
    {
      static const char *days_short[]   = { "ma", "ti", "ke", "to", "pe", "la", "su" };
      static const char *days_full[]    = { "maanantai", "tiistai", "keskiviikko", "torstai", "perjantai", "lauantai", "sunnuntai" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorFinnish::trDayPeriod (bool period) inline override virtual
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1832 of file translator_fi.h.
    {
      static const char *dayPeriod[] = { "ap.", "ip." };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorFinnish::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 848 of file translator_fi.h.
    {
      return "Mrittely tiedoston @1 rivill @0."; //  "Definition at line @0 of file @1."
    }
trDefinedIn()
QCString TranslatorFinnish::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 218 of file translator_fi.h.
    { return "mritelty"; } // "defined in"
trDefinedInSourceFile()
QCString TranslatorFinnish::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 852 of file translator_fi.h.
    {
      return "Mrittely tiedostossa @0."; // "Definition in file @0."
    }
trDefineDocumentation()
QCString TranslatorFinnish::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 512 of file translator_fi.h.
    { return "Mritysten dokumentointi"; } // "Define Documentation"
trDefines()
QCString TranslatorFinnish::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 476 of file translator_fi.h.
    { return "Mrittelyt"; } // "Defines"
trDefineValue()
QCString TranslatorFinnish::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1223 of file translator_fi.h.
    {
      return "Arvo:"; // "Value:"
    }
trDeprecated()
QCString TranslatorFinnish::trDeprecated () inline override virtual
Implements Translator.
Definition at line 861 of file translator_fi.h.
    {
      return "Vanhentunut"; // "Deprecated"
    }
trDeprecatedList()
QCString TranslatorFinnish::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1416 of file translator_fi.h.
    {
      return "Vanhentuneiden lista"; // "Deprecated List"
    }
trDetailedDescription()
QCString TranslatorFinnish::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 141 of file translator_fi.h.
    { return "Yksityiskohtainen selite"; } // "Detailed Description"
trDetails()
QCString TranslatorFinnish::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 145 of file translator_fi.h.
    { return "Yksityiskohdat"; }
trDir()
QCString TranslatorFinnish::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1584 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "hakemisto", "t");
    }
References Translator::createNoun().
trDirDocumentation()
QCString TranslatorFinnish::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1565 of file translator_fi.h.
    { return "Hakemistojen dokumentaatio"; } // "Directory Documentation"
trDirectories()
QCString TranslatorFinnish::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1571 of file translator_fi.h.
    { return "Hakemistot"; } // "Directories"
trDirIndex()
QCString TranslatorFinnish::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1559 of file translator_fi.h.
    { return "Hakemistohierarkia"; } // "Directory Hierarchy"
trDirReference()
QCString TranslatorFinnish::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1577 of file translator_fi.h.
    { QCString result=dirName; result+=" hakemistoreferenssi"; return result; }
trDocumentation()
QCString TranslatorFinnish::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 402 of file translator_fi.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentaatio"; } // "Documentation"
References QCString::isEmpty().
trEnumerations()
QCString TranslatorFinnish::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 488 of file translator_fi.h.
    { return "Luettelotyypit"; } // "Enumerations"
trEnumerationTypeDocumentation()
QCString TranslatorFinnish::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 524 of file translator_fi.h.
    { return "Luettelotyyppien dokumentaatio"; } // "Enumeration Type Documentation"
trEnumerationValueDocumentation()
QCString TranslatorFinnish::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1619 of file translator_fi.h.
    { return "Luettelotyypin dokumentaatio"; } // "Enumerator Documentation"
trEnumerationValues()
QCString TranslatorFinnish::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 506 of file translator_fi.h.
    { return "Luettelotyyppien arvot"; } // "Enumerator"
trEnumName()
QCString TranslatorFinnish::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 210 of file translator_fi.h.
    { return "luettelotyypin nimi"; } // "enum name"
trEnumValue()
QCString TranslatorFinnish::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 214 of file translator_fi.h.
    { return "luettelotyypin arvo"; } // "enum value"
trEventDocumentation()
QCString TranslatorFinnish::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1433 of file translator_fi.h.
    {
      return "Tapahtumien dokumentaatio"; // "Event Documentation"
    }
trEvents()
QCString TranslatorFinnish::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1428 of file translator_fi.h.
    {
      return "Tapahtumat"; // "Events"
    }
trExamples()
QCString TranslatorFinnish::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 281 of file translator_fi.h.
    { return "Esimerkit"; } // "Examples"
trExamplesDescription()
QCString TranslatorFinnish::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 388 of file translator_fi.h.
    { return "Tss on lista kaikista esimerkeist:"; } //  "Here is a list of all examples:"
trExceptions()
QCString TranslatorFinnish::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 600 of file translator_fi.h.
    { return "Poikkeukset"; } // "Exceptions"
trFile()
QCString TranslatorFinnish::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1305 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "tiedosto", "t");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorFinnish::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 466 of file translator_fi.h.
    { return "Tiedostojen dokumentaatio"; } // "File Documentation"
trFileIndex()
QCString TranslatorFinnish::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 435 of file translator_fi.h.
    { return "Tiedostoluettelo"; } // "File Index"
trFileList()
QCString TranslatorFinnish::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 247 of file translator_fi.h.
    { return "Tiedostolista"; } // "File List"
trFileListDescription()
QCString TranslatorFinnish::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 295 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista ";
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="tiedostoista lyhyen selitteen kanssa:"; // "files with brief descriptions:"
      return result;
    }
trFileMembers()
QCString TranslatorFinnish::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 264 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globaalit"; // "Globals"
      }
      else
      {
        return "Tiedoston jsenet"; // "File Members"
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorFinnish::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 366 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funktioista, muuttujista, mrittelyist, luettelotyypeist ja tyyppimrittelyist"; // "functions, variables, defines, enums, and typedefs"
      }
      else
      {
        result+="tiedoston jsenist"; // "file members"
      }
      result+=" linkitettyin "; // " with links to "
      if (extractAll)
        result+="tiedostoihin, joihin ne kuuluvat:"; // "the files they belong to:"
      else
        result+="dokumentaatioon:"; // "the documentation:"
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorFinnish::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 667 of file translator_fi.h.
    {
      QCString result=fileName;
      result+=" tiedostoreferenssi"; // " File Reference"
      return result;
    }
trFriends()
QCString TranslatorFinnish::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 627 of file translator_fi.h.
    { return "Ystvt"; } // "Friends"
trFunctionDocumentation()
QCString TranslatorFinnish::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 530 of file translator_fi.h.
    { return "Funktioiden dokumentaatio"; } // "Function Documentation"
trFunctions()
QCString TranslatorFinnish::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 494 of file translator_fi.h.
    { return "Funktiot"; } // "Functions"
trGeneratedAt()
QCString TranslatorFinnish::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 557 of file translator_fi.h.
    {
        // funktio on hiukan vaikea knt prepositioihin sidotun rakenteen vuoksi.
        // Muutetaan siis lauserakennetta suomalaisemmaksi
        // Generated on $date for $project by:
        // -> Generated for $project on $date by:
      QCString result="Generoinut ";
      if (!projName.isEmpty()) result+="projektille "+projName+" ";
      result+=date+" ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorFinnish::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 197 of file translator_fi.h.
    { QCString result="Automaattisesti luotu Doxygenilla "
                      "lhdekoodista projektille "+s; // "Generated automatically by Doxygen" ... "for" ... "from the sourcecode"
      //if (s) result+=" voor "+s;
      // tss on ongelma, kuinka taivuttaa parametria, esim. "Jcad"+"in"; "IFC2VRML konversio"+"n"
      // mutta ratkaistaan ongelma ktevsti kaksoispisteell -> "Jcad:n" / "IFC2VRML konversio:n"
      // lopputulos on vhemmn kkk ja tysin luettava, mutta ei kuitenkaan tydellinen.
      //
      // kierretn ongelma taivuttamalla sanaa projekti :)
      return result;
    }
trGeneratedBy()
QCString TranslatorFinnish::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 604 of file translator_fi.h.
    { return "Generoinut"; } // "Generated by"
trGeneratedFromFiles()
QCString TranslatorFinnish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 804 of file translator_fi.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentaatio tlle "; // "The documentation for this "
      switch(compType)
      {
        case ClassDef::Class:      result+="luokalle"; break; // "class"
        case ClassDef::Struct:     result+="tietueelle"; break; // "struct"
        case ClassDef::Union:      result+="yhdisteelle"; break; // "union"
        case ClassDef::Interface:  result+="rajapinnalle"; break; // "interface"
        case ClassDef::Protocol:   result+="protokollalle"; break; // "protocol"
        case ClassDef::Category:   result+="kategorialle"; break; // "category"
        case ClassDef::Exception:  result+="poikkeukselle"; break; // "exception"
        default: break;
      }
      if (single) result+=" luotiin seuraavasta tiedostosta:"; // " was generated from the following file"
      else result+=" luotiin seuraavista tiedostoista:"; // ":" or "s:"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorFinnish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1773 of file translator_fi.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentaatio tlle "; // "The documentation for this "
      switch(compType)
      {
        case ClassDef::Class:      result+="moduulille"; break; // "module"
        case ClassDef::Struct:     result+="tyypille"; break; // "type"
        case ClassDef::Union:      result+="yhdisteelle"; break; // "union"
        case ClassDef::Interface:  result+="rajapinnalle"; break; // "interface"
        case ClassDef::Protocol:   result+="protokollalle"; break; // "protocol"
        case ClassDef::Category:   result+="kategorialle"; break; // "category"
        case ClassDef::Exception:  result+="poikkeukselle"; break; // "exception"
        default: break;
      }
      result+=" luotiin "; // " was generated from the following file"
      if (single) result+="seuraavasta tiedostosta:"; else result+="seuraavista tiedostoista:"; // ":" / "s:"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorFinnish::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1350 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "globaali", "t");
    }
References Translator::createNoun().
trGotoDocumentation()
QCString TranslatorFinnish::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 891 of file translator_fi.h.
    {
      return "Siirry tmn tiedoston dokumentaatioon."; // "Go to the documentation of this file."
    }
trGotoGraphicalHierarchy()
QCString TranslatorFinnish::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 924 of file translator_fi.h.
    {
      return "Siirry graafiseen luokkahierarkiaan"; // "Go to the graphical class hierarchy"
    }
trGotoSourceCode()
QCString TranslatorFinnish::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 886 of file translator_fi.h.
    {
      return "Siirry tmn tiedoston lhdekoodiin."; // "Go to the source code of this file."
    }
trGotoTextualHierarchy()
QCString TranslatorFinnish::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 928 of file translator_fi.h.
    {
      return "Siirry tekstimuotoiseen luokkahierarkiaan"; // "Go to the textual class hierarchy"
    }
trGraphicalHierarchy()
QCString TranslatorFinnish::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 920 of file translator_fi.h.
    {
      return "Graafinen luokkahierarkia"; // "Graphical Class Hierarchy"
    }
trGroup()
QCString TranslatorFinnish::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1323 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "ryhm", "t");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorFinnish::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 414 of file translator_fi.h.
    { return "Hierarkinen luettelo"; } // "Hierarchical Index"
trImplementedFromList()
QCString TranslatorFinnish::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1384 of file translator_fi.h.
    {
      return "Toteuttaa luokan "+trWriteList(numEntries)+"."; // "Implements "
    }
References trWriteList().
trImplementedInList()
QCString TranslatorFinnish::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1392 of file translator_fi.h.
    {
      return "Toteutettu luokassa "+trWriteList(numEntries)+"."; // "Implemented in "
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorFinnish::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 1021 of file translator_fi.h.
    {
      return "Tm kaavio nytt, mitk tiedostot suorasti "
             "tai epsuorasti sisllyttvt tmn tiedoston";
             // "This graph shows which files directly or "
             // "indirectly include this file:"
    }
trInclDepGraph()
QCString TranslatorFinnish::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 876 of file translator_fi.h.
    {
    }
trIncludingInheritedMembers()
QCString TranslatorFinnish::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 191 of file translator_fi.h.
    { return ", sislten kaikki perityt jsenet."; } // ", including all inherited members."
trInheritedByList()
QCString TranslatorFinnish::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 738 of file translator_fi.h.
    {
      return QCString("Periytetn ")+(numEntries > 1 ? "luokissa " : "luokassa ")+trWriteList(numEntries)+"."; // "Inherited by "
    }
References trWriteList().
trInheritsList()
QCString TranslatorFinnish::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 730 of file translator_fi.h.
    {
      return QCString("Periytyy ")+(numEntries > 1 ? "luokista " : "luokasta ")+trWriteList(numEntries)+"."; // "Inherits "
    }
References trWriteList().
trInitialValue()
QCString TranslatorFinnish::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 911 of file translator_fi.h.
    {
      return "Alkuarvo:"; // "Initial value:"
    }
trInvariant()
QCString TranslatorFinnish::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 906 of file translator_fi.h.
    {
      return "Invariantti"; // vai "Pysyvisvittm"? "Invariant"
    }
trISOLang()
QCString TranslatorFinnish::trISOLang () inline override virtual
Implements Translator.
Definition at line 122 of file translator_fi.h.
    {
      return "fi";
    }
trLegend()
QCString TranslatorFinnish::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1156 of file translator_fi.h.
    {
      return "selite"; // "legend"
    }
trLegendDocs()
QCString TranslatorFinnish::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1046 of file translator_fi.h.
    {
      return
        "Tm sivu selitt, kuinka doxygenin luomia kaavioita tulkitaan.<p>\n"
        // "This page explains how to interpret the graphs that are generated "
        // "by doxygen.<p>\n"
        "Ajattele seuraavaa esimerkki:\n"
        // "Consider the following example:\n"
        "\\code\n"
        "/*! Nkymtn luokka katkaisun vuoksi */\n"
        // "/*! Invisible class because of truncation */\n"
        "class Nakymaton { };\n\n"
        // "class Invisible { };\n\n"
        "/*! Katkaistu luokka, periytymissuhde on piilotettu */\n"
        // "/*! Truncated class, inheritance relation is hidden */\n"
        "class Katkaistu : public Nakymaton { };\n\n"
        // "class Truncated : public Invisible { };\n\n"
        "/* Luokkaa ei ole dokumentoitu doxygen-kommenteilla */\n"
        // "/* Class not documented with doxygen comments */\n"
        "class Dokumentoimaton {};\n\n"
        // "class Undocumented { };\n\n"
        "/*! Julkista periyttmist kytten periytetty luokka */\n"
        // "/*! Class that is inherited using public inheritance */\n"
        "class JulkinenKanta : public Katkaistu { };\n\n"
        // "class PublicBase : public Truncated { };\n\n"
        "/*! Malliluokka */\n"
        // "/*! A template class */\n"
        "template<class T> class Malli { };\n\n"
        // "template<class T> class Templ { };\n\n"
        "/*! Suojeltua periytymist kytten periytetty luokka */\n"
        // "/*! Class that is inherited using protected inheritance */\n"
        "class SuojeltuKanta { };\n\n"
        // "class ProtectedBase { };\n\n"
        "/*! Yksityist periytymist kytten periytetty luokka */\n"
        // "/*! Class that is inherited using private inheritance */\n"
        "class YksityisKanta { };\n\n"
        // "class PrivateBase { };\n\n"
        "/*! Luokka jota periytetty luokka kytt */\n"
        // "/*! Class that is used by the Inherited class */\n"
        "class Kaytetty { };\n\n"
        // "class Used { };\n\n"
        "/*! Kantaluokka joka periytyy useasta muusta luokasta */\n"
        // "/*! Super class that inherits a number of other classes */\n"
        "class Periytetty : public JulkinenKanta,\n"
        "                 : protected SuojeltuKanta,\n"
        "                 : private YksityisKanta,\n"
        "                 : public Dokumentoimaton,\n"
        "                 : public Malli<int>\n"
        "{\n"
        "  private:\n"
        "    Kaytetty *m_kaytettyLuokka;\n"
        "}\n"
        // "class Inherited : public PublicBase,\n"
        // "                  protected ProtectedBase,\n"
        // "                  private PrivateBase,\n"
        // "                  public Undocumented,\n"
        // "                  public Templ<int>\n"
        // "{\n"
        // "  private:\n"
        // "    Used *m_usedClass;\n"
        // "};\n"
        "\\endcode\n"
        "Tuloksena on seuraavanlainen kaavio:"
        //"This will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Yllolevassa kaaviossa laatikoilla on seuraavat merkitykset\n:"
        // "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>Tytetty harmaa laatikko esitt tietuetta tai luokkaa, jolle "
        // "<li>%A filled gray box represents the struct or class for which the "
        "kaavio on luotu.\n"
        // "graph is generated.\n"
        "<li>Mustareunainen laatikko merkitsee dokumentoitua tietuetta tai luokkaa.\n"
        // "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>Harmaareunainen laatikko merkitsee dokumentoimatonta tietuetta tai luokkaa.\n"
        // "<li>%A box with a grey border denotes an undocumented struct or class.\n"
        "<li>Punareunainen laatikko merkistee dokumentoitua luokkaa tai structia "
        // "<li>%A box with a red border denotes a documented struct or class for"
        "jolle ei nytet kaikkia periytymis-/sisllyssuhteita. Kaavio "
        // "which not all inheritance/containment relations are shown. %A graph is "
        "katkaistaan, jos se ei mahdu mriteltyjen rajojen sisn.\n"
        // "truncated if it does not fit within the specified boundaries.\n"
        "</ul>\n"
        "Nuolilla on seuraavat merkitykset:\n"
        // "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>Tummansinist nuolta kytetn osoittamaan julkista periytymis"
        // "<li>%A dark blue arrow is used to visualize a public inheritance "
        "suhdetta kahden luokan vlill.\n"
        // "relation between two classes.\n"
        "<li>Tummanvihre nuolta kytetn suojellussa periytymisess.\n"
        // "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>Tummanpunaista nuolta kytetn yksityisess periytymisess.\n"
        // "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>Purppuranvrist katkoviivaa kytetn, jos luokka sisltyy tai "
        // "<li>%A purple dashed arrow is used if a class is contained or used "
        "on toisen luokan kyttm. Nuoli nimetn sill muuttujalla/muuttujilla "
        // "by another class. The arrow is labeled with the variable(s) "
        "jonka lpi osoitettua luokkaa tai tietuetta kytetn.\n"
        // "through which the pointed class or struct is accessible.\n"
        "<li>Keltainen katkoviivalla piirretty nuoli merkitsee suhdetta mallin esiintymn ja "
        // "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "malliluokan vlill. Nuoli nimetn "
        // "the template class it was instantiated from. The arrow is labeled with "
        "mallin esiintymn malliparametrilla.\n"
        // "the template parameters of the instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorFinnish::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 1039 of file translator_fi.h.
    {
      return "Kaavion selite"; // "Graph Legend"
    }
trListOfAllMembers()
QCString TranslatorFinnish::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 179 of file translator_fi.h.
    { return "Lista kaikista jsenist"; } // "List of all members."
trMainPage()
QCString TranslatorFinnish::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 835 of file translator_fi.h.
    { return "Psivu"; } // "Main Page"
trMember()
QCString TranslatorFinnish::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1341 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "jsen", "et");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorFinnish::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 162 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Kenttien dokumentaatio"; // "Field Documentation";
      }
      else
      {
        return "Jsendatan dokumentaatio"; // "Member Data Documentation"
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorFinnish::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 154 of file translator_fi.h.
    { return "Jsenluettelotyyppien dokumentaatio"; } // "Member Enumeration Documentation"
trMemberFunctionDocumentation()
QCString TranslatorFinnish::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 158 of file translator_fi.h.
    { return "Jsenfunktioiden dokumentaatio"; } // "Member Function Documentation"
trMemberFunctionDocumentationFortran()
QCString TranslatorFinnish::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1627 of file translator_fi.h.
    { return "Jsenfunktioiden/aliohjelmien dokumentaatio"; } // "Member Function/Subroutine Documentation"
trMemberList()
QCString TranslatorFinnish::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 181 of file translator_fi.h.
    { return "Jsenlista"; } // "Member List"
trMemberTypedefDocumentation()
QCString TranslatorFinnish::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 149 of file translator_fi.h.
    { return "Jsentyyppimrittelyiden dokumentaatio"; } // "Member Typedef Documentation"
trModule()
QCString TranslatorFinnish::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1766 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "moduuli", "t");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorFinnish::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 441 of file translator_fi.h.
    { return "Moduulien dokumentaatio"; } // "Module Documentation"
trModuleIndex()
QCString TranslatorFinnish::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 408 of file translator_fi.h.
    { return "Moduuliluettelo"; } // "Module Index"
trModuleReference()
QCString TranslatorFinnish::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1728 of file translator_fi.h.
    {
      QCString result=namespaceName;
      result+=" moduulin referenssi"; // " Module Reference"
      return result;
    }
trModules()
QCString TranslatorFinnish::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 226 of file translator_fi.h.
    { return "Moduulit"; } // "Modules"
trModulesDescription()
QCString TranslatorFinnish::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 396 of file translator_fi.h.
    { return "Tss on lista kaikista moduleista:"; } // "Here is a list of all modules:"
trModulesIndex()
QCString TranslatorFinnish::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1759 of file translator_fi.h.
    { return "Moduulien hakemisto"; } // "Modules Index"
trModulesList()
QCString TranslatorFinnish::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1694 of file translator_fi.h.
    { return "Moduulilista"; } // "Modules List"
trModulesListDescription()
QCString TranslatorFinnish::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1698 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="moduuleista lyhyiden selitysten kanssa:"; // "modules with brief descriptions:"
      return result;
    }
trModulesMemberDescription()
QCString TranslatorFinnish::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1740 of file translator_fi.h.
    {
      QCString result="Tss on lista moduulin kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista"; // "documented "
      result+="jsenist, sek linkit "; // "module members with links to "
      if (extractAll)
      {
        result+="moduulin dokumentaatioon jokaiselle jsenelle:"; // "the module documentation for each member:"
      }
      else
      {
        result+="moduuleihin, joihin ne kuuluvat:"; // "the modules they belong to:"
      }
      return result;
    }
trModulesMembers()
QCString TranslatorFinnish::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1736 of file translator_fi.h.
    { return "Moduulin jsenet"; } // "Module Members"
trMonth()
QCString TranslatorFinnish::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1824 of file translator_fi.h.
    {
      static const char *months_short[] = { "tammi", "helmi", "maalis", "huhti", "touko", "kes", "hein", "elo", "syys", "loka", "marras", "joulu" };
      static const char *months_full[]  = { "tammikuu", "helmikuu", "maaliskuu", "huhtikuu", "toukokuu", "keskuu", "heinkuu", "elokuu", "syyskuu", "lokakuu", "marraskuu", "joulukuu" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorFinnish::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 175 of file translator_fi.h.
    { return "Lis..."; } // ""
trNamespace()
QCString TranslatorFinnish::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1314 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "nimiavaruu", "det", "s");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorFinnish::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 784 of file translator_fi.h.
    { return "Nimiavaruuden dokumentaatio"; } // "Namespace Documentation"
trNamespaceIndex()
QCString TranslatorFinnish::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 778 of file translator_fi.h.
    { return "Nimiavaruuksien luettelo"; } // "Namespace Index"
trNamespaceList()
QCString TranslatorFinnish::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 612 of file translator_fi.h.
    { return "Nimiavaruus Lista"; } // "Namespace List"
trNamespaceListDescription()
QCString TranslatorFinnish::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 616 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="nimiavaruuksista lyhyen selitteen kanssa:"; // "namespaces with brief descriptions:"
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorFinnish::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 764 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="nimiavaruuden jsenist linkitettyn "; // "namespace members with links to "
      if (extractAll)
        result+="nimiavaruuden dokumentaatioon johon ne kuuluvat:"; // "the namespace documentation for each member:";
      else
        result+="nimiavaruuksiin joihin ne kuuluvat:"; // "the namespaces they belong to:"
      return result;
    }
trNamespaceMembers()
QCString TranslatorFinnish::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 760 of file translator_fi.h.
    { return "Nimiavaruuden jsenet"; } // "Namespace Members"
trNamespaceReference()
QCString TranslatorFinnish::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 675 of file translator_fi.h.
    {
      QCString result=namespaceName;
      result+=" nimiavaruusreferenssi"; // " Namespace Reference"
      return result;
    }
trNamespaces()
QCString TranslatorFinnish::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 794 of file translator_fi.h.
    { return "Nimiavaruudet"; } // "Namespaces"; }
trNote()
QCString TranslatorFinnish::trNote () inline override virtual
Implements Translator.
Definition at line 941 of file translator_fi.h.
    {
        // FIXME: Misshn merkityksess tt kytetn?
      return "Huomautus"; // "Note"
    }
trOverloadText()
QCString TranslatorFinnish::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1596 of file translator_fi.h.
    {
       return "Tm on ylikuormitettu jsenfunktio, ja se tarjotaan "
              "kytn helpottamiseksi. Se eroaa yllolevasta "
              "funktiosta ainoastaan hyvksymiltn parametreilta.";
              // "This is an overloaded member function, "
              // "provided for convenience. It differs from the above "
              // "function only in what argument(s) it accepts."
    }
trPackage()
QCString TranslatorFinnish::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1208 of file translator_fi.h.
    {
      return "Paketti "+name; // "Package "
    }
trPackageAttribs()
QCString TranslatorFinnish::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1469 of file translator_fi.h.
    {
      return "Paketin attribuutit"; // "Package Attributes"
    }
trPackageFunctions()
QCString TranslatorFinnish::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1451 of file translator_fi.h.
    {
      return "Paketin funktiot"; // "Package Functions"
    }
trPackageListDescription()
QCString TranslatorFinnish::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1213 of file translator_fi.h.
    {
      return "Tss ovat paketit lyhyiden selitysten kanssa (jos saatavilla):"; // "Here are the packages with brief descriptions (if available):"
    }
trPackageMembers()
QCString TranslatorFinnish::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1455 of file translator_fi.h.
    {
      return "Paketin jsenet"; // "Package Members"
    }
trPackages()
QCString TranslatorFinnish::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1218 of file translator_fi.h.
    {
      return "Paketit"; // "Packages"
    }
trPackageTypes()
QCString TranslatorFinnish::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1444 of file translator_fi.h.
    {
      return "Paketin tyypit"; // "Package Types"
    }
trPage()
QCString TranslatorFinnish::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1332 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "sivu", "t");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorFinnish::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 841 of file translator_fi.h.
    { return "s."; } // "p."
trPageIndex()
QCString TranslatorFinnish::trPageIndex () inline override virtual
Implements Translator.
Definition at line 932 of file translator_fi.h.
    {
      return "Sivuhakemisto"; // "Page Index"
    }
trParameters()
QCString TranslatorFinnish::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 596 of file translator_fi.h.
    { return "Parametrit"; } // "Parameters"
trPostcondition()
QCString TranslatorFinnish::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 901 of file translator_fi.h.
    {
      return "Jlkiehto"; // "Postcondition"
    }
trPrecondition()
QCString TranslatorFinnish::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 896 of file translator_fi.h.
    {
      return "Esiehto"; //"Precondition"
    }
trPrivateAttribs()
QCString TranslatorFinnish::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 981 of file translator_fi.h.
    {
      return "Yksityiset attribuutit"; // "Private Attributes"
    }
trPrivateMembers()
QCString TranslatorFinnish::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 696 of file translator_fi.h.
    { return "Yksityiset jsenfunktiot"; } // "Private Member Functions"
trPrivateSlots()
QCString TranslatorFinnish::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 698 of file translator_fi.h.
    { return "Yksityiset vastineet"; } // "Private Slots"
trPrivateTypes()
QCString TranslatorFinnish::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 977 of file translator_fi.h.
    {
      return "Yksityiset tyypit"; // "Private Types"
    }
trProperties()
QCString TranslatorFinnish::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1181 of file translator_fi.h.
    {
      return "Ominaisuudet"; // "Properties"
    }
trPropertyDocumentation()
QCString TranslatorFinnish::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1186 of file translator_fi.h.
    {
      return "Ominaisuuksien dokumentaatio"; // "Property Documentation"
    }
trProtectedAttribs()
QCString TranslatorFinnish::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 969 of file translator_fi.h.
    {
      return "Suojellut attribuutit"; // "Protected Attributes"
    }
trProtectedMembers()
QCString TranslatorFinnish::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 690 of file translator_fi.h.
    { return "Suojatut jsenfunktiot"; } // "Protected Member Functions"
trProtectedSlots()
QCString TranslatorFinnish::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 692 of file translator_fi.h.
    { return "Suojatut vastineet"; } // "Protected Slots"
trProtectedTypes()
QCString TranslatorFinnish::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 965 of file translator_fi.h.
    {
      return "Suojellut tyypit"; // "Protected Types"
    }
trPublicAttribs()
QCString TranslatorFinnish::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 950 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueen kentt"; // "Data Fields"
      }
      else
      {
        return "Julkiset attribuutit"; // "Public Attributes"
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorFinnish::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 682 of file translator_fi.h.
    { return "Julkiset jsenfunktiot"; } // "Public Member Functions"
trPublicSlots()
QCString TranslatorFinnish::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 684 of file translator_fi.h.
    { return "Julkiset vastineet"; } // "Public Slots"
trPublicTypes()
QCString TranslatorFinnish::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 946 of file translator_fi.h.
    {
      return "Julkiset tyypit"; // "Public Types"
    }
trReferencedBy()
QCString TranslatorFinnish::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 1009 of file translator_fi.h.
    {
      return "Viitattu"; // "Referenced by"
    }
trReferenceManual()
QCString TranslatorFinnish::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 470 of file translator_fi.h.
    { return "Ksikirja"; } // "Reference Manual"
trReferences()
QCString TranslatorFinnish::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1372 of file translator_fi.h.
    {
      return "Viittaukset"; // "References"
    }
trReimplementedFromList()
QCString TranslatorFinnish::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 746 of file translator_fi.h.
    {
      return QCString("Uudelleentoteuttaa ")+(numEntries > 1 ? "luokat " : "luokan  ")+trWriteList(numEntries)+"."; // "Reimplemented from "
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorFinnish::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 754 of file translator_fi.h.
    {
      return QCString("Uudelleentoteutetaan ")+(numEntries > 1 ? "luokissa " : "luokassa ")+trWriteList(numEntries)+"."; // "Reimplemented in "
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorFinnish::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 637 of file translator_fi.h.
    { return "Ystvt ja niihin liittyvien funktioiden dokumentaatio"; } // "Friends And Related Function Documentation"
trRelatedFunctions()
QCString TranslatorFinnish::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 133 of file translator_fi.h.
    { return "Liittyvt funktiot"; } // "Related Functions";
trRelatedPages()
QCString TranslatorFinnish::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 277 of file translator_fi.h.
    { return "Liittyvt sivut"; } // "Related Pages"
trRelatedPagesDescription()
QCString TranslatorFinnish::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 392 of file translator_fi.h.
    { return "Tss on lista kaikista liittyvist dokumentaatiosivuista:"; } // "Here is a list of all related documentation pages:"
trRelatedSubscript()
QCString TranslatorFinnish::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 137 of file translator_fi.h.
    { return "(Huomaa, ett nm eivt ole jsenfunktioita.)"; } // "(Note that these are not member functions.)"
trRemarks()
QCString TranslatorFinnish::trRemarks () inline override virtual
Implements Translator.
Definition at line 1013 of file translator_fi.h.
    {
      return "Huomioita"; // "Remarks"
    }
trReturns()
QCString TranslatorFinnish::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 588 of file translator_fi.h.
    { return "Palauttaa"; } // "Returns"
trReturnValues()
QCString TranslatorFinnish::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 830 of file translator_fi.h.
    { return "Paluuarvot"; } // "Return values"
trRTFansicp()
QCString TranslatorFinnish::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1272 of file translator_fi.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorFinnish::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1281 of file translator_fi.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorFinnish::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1287 of file translator_fi.h.
    {
      return "Hakemisto"; // "Index"
    }
trRTFTableOfContents()
QCString TranslatorFinnish::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1404 of file translator_fi.h.
    {
      return "Sisllysluettelo"; // "Table of Contents"
    }
trSearch()
QCString TranslatorFinnish::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 285 of file translator_fi.h.
    { return "Etsi"; } // "Search"
trSearchMatches()
QCString TranslatorFinnish::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1536 of file translator_fi.h.
    {
      return "Osumat:"; // "Matches:"
    }
trSearchResults()
QCString TranslatorFinnish::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1517 of file translator_fi.h.
    {
      if (numDocuments==0)
      {
        return "Valitettavasti yksikn dokumentti ei vastannut hakuasi."; // "Sorry, no documents matching your query."
      }
      else if (numDocuments==1)
      {
        return "Lytyi <b>1</b> dokumentti, joka vastasi hakuasi."; // "Found <b>1</b> document matching your query.";
      }
      else
      {
        return "Lytyi <b>$num</b> dokumenttia, jotka vastasivat hakuasi. " // "Found <b>$num</b> documents matching your query. "
                "Parhaat tulokset nytetn ensin."; // "Showing best matches first."
      }
    }
trSearchResultsTitle()
QCString TranslatorFinnish::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1505 of file translator_fi.h.
    {
      return "Hakutulokset"; // "Search Results"
    }
trSeeAlso()
QCString TranslatorFinnish::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 592 of file translator_fi.h.
    { return "Katso mys"; } // "See also"
trSignals()
QCString TranslatorFinnish::trSignals () inline override virtual
Implements Translator.
Definition at line 686 of file translator_fi.h.
    { return "Signaalit"; } // "Signals"
trSince()
QCString TranslatorFinnish::trSince () inline override virtual
Implements Translator.
Definition at line 1028 of file translator_fi.h.
    {
        // FIXME: Miss merkityksess tt kytetn?
      return "Lhtien"; // "Since"
    }
trSourceFile()
QCString TranslatorFinnish::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1547 of file translator_fi.h.
    {
      return filename + " lhdekooditiedosto"; // " Source File"
    }
trStaticPackageAttribs()
QCString TranslatorFinnish::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1476 of file translator_fi.h.
    {
      return "Paketin staattiset attribuutit"; // "Static Package Attributes"
    }
trStaticPackageFunctions()
QCString TranslatorFinnish::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1462 of file translator_fi.h.
    {
      return "Paketin staattiset funktiot"; // "Static Package Functions"
    }
trStaticPrivateAttribs()
QCString TranslatorFinnish::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 985 of file translator_fi.h.
    {
      return "Staattiset yksityiset attribuutit"; // "Static Private Attributes"
    }
trStaticPrivateMembers()
QCString TranslatorFinnish::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 700 of file translator_fi.h.
    { return "Staattiset yksityiset jsenfunktiot"; } // "Static Private Member Functions"
trStaticProtectedAttribs()
QCString TranslatorFinnish::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 973 of file translator_fi.h.
    {
      return "Staattiset suojellut attribuutit"; // "Static Protected Attributes"
    }
trStaticProtectedMembers()
QCString TranslatorFinnish::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 694 of file translator_fi.h.
    { return "Staattiset suojatut jsenfunktiot"; } // "Static Protected Member Functions"
trStaticPublicAttribs()
QCString TranslatorFinnish::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 961 of file translator_fi.h.
    {
      return "Staattiset julkiset attribuutit"; // "Static Public Attributes"
    }
trStaticPublicMembers()
QCString TranslatorFinnish::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 688 of file translator_fi.h.
    { return "Staattiset julkiset jsenfunktiot"; } // "Static Public Member Functions"
trSubprogram()
QCString TranslatorFinnish::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1805 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "aliohjelma", "t");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorFinnish::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1684 of file translator_fi.h.
    { return "Funktioiden/aliohjelmien dokumentaatio"; } // "Function/Subroutine Documentation"
trSubprograms()
QCString TranslatorFinnish::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1678 of file translator_fi.h.
    { return "Funktiot/aliohjelmat"; } // "Functions/Subroutines"
trTest()
QCString TranslatorFinnish::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1166 of file translator_fi.h.
    {
      return "Testi"; // "Test"
    }
trTestList()
QCString TranslatorFinnish::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1171 of file translator_fi.h.
    {
      return "Testilista"; // "Test List"
    }
trThisIsTheListOfAllMembers()
QCString TranslatorFinnish::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 187 of file translator_fi.h.
    { return "Tm on lista kaikista jsenist luokassa"; } // "This is the complete list of members for "
trTodo()
QCString TranslatorFinnish::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 995 of file translator_fi.h.
    {
      return "Viel tehtvn"; // "Todo"
    }
trTodoList()
QCString TranslatorFinnish::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 1000 of file translator_fi.h.
    {
      return "Tehtvlista"; // "Todo List"
    }
trType()
QCString TranslatorFinnish::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1797 of file translator_fi.h.
    {
      return createNoun(first_capital, singular, "tyyp", "it", "pi");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorFinnish::trTypeConstraints () inline override virtual
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1811 of file translator_fi.h.
    {
      return "Tyyppien rajoitteet"; // "Type Constraints"
    }
trTypedefDocumentation()
QCString TranslatorFinnish::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 518 of file translator_fi.h.
    { return "Tyyppimritysten dokumentaatio"; } // "Typedef Documentation"
trTypedefs()
QCString TranslatorFinnish::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 482 of file translator_fi.h.
    { return "Tyyppimrittelyt"; } // "Typedefs"
trTypeDocumentation()
QCString TranslatorFinnish::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1672 of file translator_fi.h.
    { return "Tietotyyppien dokumentaatio"; } // "Data Type Documentation"
trVariableDocumentation()
QCString TranslatorFinnish::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 536 of file translator_fi.h.
    { return "Muuttujien dokumentaatio"; } // "Variable Documentation"
trVariables()
QCString TranslatorFinnish::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 500 of file translator_fi.h.
    { return "Muuttujat"; } // "Variables"
trVersion()
QCString TranslatorFinnish::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 580 of file translator_fi.h.
    { return "Versio"; } // "Version"
trWarning()
QCString TranslatorFinnish::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 576 of file translator_fi.h.
    { return "Varoitus"; } // "Warning"
trWriteList()
QCString TranslatorFinnish::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 706 of file translator_fi.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" ja "; // ", and "
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_fi.h