Doxygen: src/codefragment.cpp File Reference
codefragment.cpp File Reference
#include <mutex>
#include <unordered_map>
#include <map>
#include "codefragment.h"
#include "util.h"
#include "doxygen.h"
#include "parserintf.h"
#include "outputlist.h"
#include "clangparser.h"
#include "trace.h"
#include "fileinfo.h"
#include "filedef.h"
#include "portable.h"
#include "message.h"
Classes
struct CodeFragmentManager::Private
struct CodeFragmentManager::Private::BlockMarker
struct CodeFragmentManager::Private::FragmentInfo
Functions
static QCString readTextFileByName (const QCString &file)
Function Documentation
readTextFileByName()
static QCString readTextFileByName (const QCString & file) static
Definition at line 193 of file codefragment.cpp.
{
  AUTO_TRACE("file={}",file);
  if (Portable::isAbsolutePath(file))
  {
    FileInfo fi(file.str());
    if (fi.exists())
    {
      return fileToString(file,Config_getBool(FILTER_SOURCE_FILES));
    }
  }
  const StringVector &examplePathList = Config_getList(EXAMPLE_PATH);
  for (const auto &s : examplePathList)
  {
    std::string absFileName = s+(Portable::pathSeparator()+file).str();
    FileInfo fi(absFileName);
    if (fi.exists())
    {
      return fileToString(QCString(absFileName),Config_getBool(FILTER_SOURCE_FILES));
    }
  }
  // as a fallback we also look in the exampleNameDict
  bool ambig=false;
  FileDef *fd = findFileDef(Doxygen::exampleNameLinkedMap,file,ambig);
  if (fd)
  {
    if (ambig)
    {
      err("included file name '%s' is ambiguous.\nPossible candidates:\n%s\n",qPrint(file),
           qPrint(showFileDefMatches(Doxygen::exampleNameLinkedMap,file))
          );
    }
    return fileToString(fd->absFilePath(),Config_getBool(FILTER_SOURCE_FILES));
  }
  else
  {
    err("included file %s is not found. Check your EXAMPLE_PATH\n",qPrint(file));
  }
  return QCString();
}
References FileDef::absFilePath(), AUTO_TRACE, Config_getBool, Config_getList, err, Doxygen::exampleNameLinkedMap, FileInfo::exists(), fileToString(), findFileDef(), Portable::isAbsolutePath(), Portable::pathSeparator(), qPrint(), showFileDefMatches(), and QCString::str().
Referenced by CodeFragmentManager::parseCodeFragment().