Doxygen: AccessStack Class Reference
AccessStack Class Reference
Helper class representing the stack of items considered while resolving the scope.
Classes
struct AccessElem
Element in the stack.
Public Member Functions
void push (const Definition *scope, const FileDef *fileScope, const Definition *item)
void push (const Definition *scope, const FileDef *fileScope, const Definition *item, const QCString &expScope)
void pop ()
bool find (const Definition *scope, const FileDef *fileScope, const Definition *item)
bool find (const Definition *scope, const FileDef *fileScope, const Definition *item, const QCString &expScope)
void clear ()
Private Attributes
std::vector< AccessElem > m_elements
Detailed Description
Helper class representing the stack of items considered while resolving the scope.
Definition at line 45 of file symbolresolver.cpp.
Member Function Documentation
clear()
void AccessStack::clear () inline
Definition at line 82 of file symbolresolver.cpp.
    {
      m_elements.clear();
    }
References m_elements.
find() [1/2]
bool AccessStack::find (const Definition * scope, const FileDef * fileScope, const Definition * item) inline
Definition at line 70 of file symbolresolver.cpp.
    {
      auto it = std::find_if(m_elements.begin(),m_elements.end(),
                             [&](const AccessElem &e) { return e.scope==scope && e.fileScope==fileScope && e.item==item; });
      return it!=m_elements.end();
    }
References m_elements.
Referenced by SymbolResolver::Private::isAccessibleFrom(), and SymbolResolver::Private::isAccessibleFromWithExpScope().
find() [2/2]
bool AccessStack::find (const Definition * scope, const FileDef * fileScope, const Definition * item, const QCString & expScope) inline
Definition at line 76 of file symbolresolver.cpp.
    {
      auto it = std::find_if(m_elements.begin(),m_elements.end(),
                             [&](const AccessElem &e) { return e.scope==scope && e.fileScope==fileScope && e.item==item && e.expScope==expScope; });
      return it!=m_elements.end();
    }
References m_elements.
pop()
void AccessStack::pop () inline
Definition at line 66 of file symbolresolver.cpp.
    {
      if (!m_elements.empty()) m_elements.pop_back();
    }
References m_elements.
Referenced by SymbolResolver::Private::isAccessibleFrom(), and SymbolResolver::Private::isAccessibleFromWithExpScope().
push() [1/2]
void AccessStack::push (const Definition * scope, const FileDef * fileScope, const Definition * item) inline
Definition at line 58 of file symbolresolver.cpp.
    {
      m_elements.emplace_back(scope,fileScope,item);
    }
References m_elements.
Referenced by SymbolResolver::Private::isAccessibleFrom(), and SymbolResolver::Private::isAccessibleFromWithExpScope().
push() [2/2]
void AccessStack::push (const Definition * scope, const FileDef * fileScope, const Definition * item, const QCString & expScope) inline
Definition at line 62 of file symbolresolver.cpp.
    {
      m_elements.emplace_back(scope,fileScope,item,expScope);
    }
References m_elements.
Member Data Documentation
m_elements
std::vector<AccessElem> AccessStack::m_elements private
Definition at line 88 of file symbolresolver.cpp.
Referenced by clear(), find(), find(), pop(), push(), and push().
The documentation for this class was generated from the following file:
src/symbolresolver.cpp