Doxygen: DefineManager::DefinesPerFile Class Reference
DefineManager::DefinesPerFile Class Reference
Local class used to hold the defines for a single file.
Public Member Functions
DefinesPerFile (DefineManager *parent)
Creates an empty container for defines.
void addInclude (const std::string &fileName)
void store (const DefineMap &fromMap)
void retrieve (DefineMap &toMap)
void retrieveRec (DefineMap &toMap, StringUnorderedSet &includeStack)
bool stored () const
Private Attributes
DefineManager * m_parent
DefineMap m_defines
StringUnorderedSet m_includedFiles
bool m_stored = false
Detailed Description
Local class used to hold the defines for a single file.
Definition at line 117 of file pre.l.
Constructor & Destructor Documentation
DefinesPerFile()
DefineManager::DefinesPerFile::DefinesPerFile (DefineManager * parent) inline
Creates an empty container for defines.
Definition at line 121 of file pre.l.
          : m_parent(parent)
        {
        }
References m_parent.
Referenced by retrieveRec().
Member Function Documentation
addInclude()
void DefineManager::DefinesPerFile::addInclude (const std::string & fileName) inline
Definition at line 125 of file pre.l.
        {
          m_includedFiles.insert(fileName);
        }
References m_includedFiles.
retrieve()
void DefineManager::DefinesPerFile::retrieve (DefineMap & toMap) inline
Definition at line 138 of file pre.l.
        {
          StringUnorderedSet includeStack;
          retrieveRec(toMap,includeStack);
        }
References retrieveRec().
retrieveRec()
void DefineManager::DefinesPerFile::retrieveRec (DefineMap & toMap, StringUnorderedSet & includeStack) inline
Definition at line 143 of file pre.l.
        {
          //printf("  retrieveRec #includedFiles=%zu\n",m_includedFiles.size());
          for (auto incFile : m_includedFiles)
          {
            DefinesPerFile *dpf = m_parent->find(incFile);
            if (dpf && includeStack.find(incFile)==includeStack.end())
            {
              includeStack.insert(incFile);
              dpf->retrieveRec(toMap,includeStack);
              //printf("  retrieveRec: processing include %s: #toMap=%zu\n",qPrint(incFile),toMap.size());
            }
          }
          for (auto &[name,define] : m_defines)
          {
            toMap.emplace(name,define);
          }
        }
References DefinesPerFile(), m_defines, m_includedFiles, m_parent, and retrieveRec().
Referenced by retrieve(), and retrieveRec().
store()
void DefineManager::DefinesPerFile::store (const DefineMap & fromMap) inline
Definition at line 129 of file pre.l.
        {
          for (auto &[name,define] : fromMap)
          {
            m_defines.emplace(name,define);
          }
          //printf("  m_defines.size()=%zu\n",m_defines.size());
          m_stored=true;
        }
References m_defines, and m_stored.
stored()
bool DefineManager::DefinesPerFile::stored () const inline
Definition at line 161 of file pre.l.
{ return m_stored; }
References m_stored.
Member Data Documentation
m_defines
DefineMap DefineManager::DefinesPerFile::m_defines private
Definition at line 164 of file pre.l.
Referenced by retrieveRec(), and store().
m_includedFiles
StringUnorderedSet DefineManager::DefinesPerFile::m_includedFiles private
Definition at line 165 of file pre.l.
Referenced by addInclude(), and retrieveRec().
m_parent
DefineManager* DefineManager::DefinesPerFile::m_parent private
Definition at line 163 of file pre.l.
Referenced by DefinesPerFile(), and retrieveRec().
m_stored
bool DefineManager::DefinesPerFile::m_stored = false private
Definition at line 166 of file pre.l.
Referenced by store(), and stored().
The documentation for this class was generated from the following file:
src/pre.l