Doxygen: CCodeParser Class Reference
CCodeParser Class Reference
#include <src/code.h>
Classes
struct Private
Public Member Functions
CCodeParser ()
~CCodeParser () override
void parseCode (OutputCodeList &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool stripCodeComments, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=nullptr, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=nullptr, bool showLineNumbers=TRUE, const Definition *searchCtx=nullptr, bool collectXRefs=TRUE) override
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
void resetCodeParserState () override
Resets the state of the code parser.
void setInsideCodeLine (bool inp)
bool insideCodeLine () const
Public Member Functions inherited from CodeParserInterface
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 29 of file code.h.
Constructor & Destructor Documentation
CCodeParser()
CCodeParser::CCodeParser ()
Definition at line 4045 of file code.l.
                         : p(std::make_unique<CCodeParser::Private>())
{
  codeYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  codeYYset_debug(Debug::isFlagSet(Debug::Lex_code)?1:0,p->yyscanner);
#endif
  resetCodeParserState();
}
References CCodeParser(), Debug::isFlagSet(), Debug::Lex_code, p, and resetCodeParserState().
Referenced by CCodeParser().
~CCodeParser()
CCodeParser::~CCodeParser () override
Definition at line 4054 of file code.l.
{
  codeYYlex_destroy(p->yyscanner);
}
References p.
Member Function Documentation
insideCodeLine()
bool CCodeParser::insideCodeLine () const
Definition at line 4077 of file code.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  return yyextra->insideCodeLine;
}
References p.
parseCode()
void CCodeParser::parseCode (OutputCodeList & codeOutList, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool stripCodeComments, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = nullptr, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = nullptr, bool showLineNumbers = TRUE, const Definition * searchCtx = nullptr, bool collectXRefs = TRUE) override virtual
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
[in] codeOutList interface for writing the result.
[in] scopeName Name of scope to which the code belongs.
[in] input Actual code in the form of a string
[in] lang The programming language of the code fragment.
[in] stripCodeComments signals whether or not for the code block the doxygen comments should be stripped.
[in] isExampleBlock TRUE iff the code is part of an example.
[in] exampleName Name of the example.
[in] fileDef File definition to which the code is associated.
[in] startLine Starting line in case of a code fragment.
[in] endLine Ending line of the code fragment.
[in] inlineFragment Code fragment that is to be shown inline as part of the documentation.
[in] memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
[in] showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
[in] searchCtx context under which search data has to be stored.
[in] collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
Definition at line 4083 of file code.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  DBG_CTX((stderr,"***parseCode() exBlock=%d exName=%s fd=%p scopeName=%s searchCtx=%s\n",
           exBlock,qPrint(exName),(void*)fd,qPrint(scopeName),searchCtx?qPrint(searchCtx->name()):"<none>"));
  if (s.isEmpty()) return;
  DebugLex debugLex(Debug::Lex_code, __FILE__, fd ? qPrint(fd->fileName()): !exName.isEmpty() ? qPrint(exName) : nullptr);
  od.stripCodeComments(stripCodeComments);
  yyextra->code = &od;
  yyextra->inputString   = s.data();
  yyextra->fileName      = fd ? fd->fileName():"";
  yyextra->absFileName   = fd ? fd->absFilePath():"";
  yyextra->inputPosition = 0;
  codeYYrestart(nullptr,yyscanner);
  yyextra->currentFontClass = nullptr;
  yyextra->searchCtx = searchCtx;
  yyextra->collectXRefs = collectXRefs;
  yyextra->inFunctionTryBlock = FALSE;
  yyextra->symbolResolver.setFileScope(fd);
  yyextra->foldStack.clear();
  yyextra->insideSpecialComment = false;
  if (startLine!=-1)
    yyextra->yyLineNr    = startLine;
  else
    yyextra->yyLineNr    = 1;
  if (endLine!=-1)
    yyextra->inputLines  = endLine+1;
  else
    yyextra->inputLines  = yyextra->yyLineNr + countLines(yyscanner) - 1;
  yyextra->curlyCount    = 0;
  yyextra->bodyCurlyCount    = 0;
  yyextra->bracketCount  = 0;
  yyextra->sharpCount    = 0;
  yyextra->insideTemplate = FALSE;
  yyextra->theCallContext.clear();
  while (!yyextra->scopeStack.empty()) yyextra->scopeStack.pop();
  yyextra->scopeName     = scopeName;
  DBG_CTX((stderr,"parseCCode %s\n",qPrint(scopeName)));
  yyextra->exampleBlock  = exBlock;
  yyextra->exampleName   = exName;
  yyextra->sourceFileDef = fd;
  yyextra->lineNumbers   = fd && showLineNumbers;
  if (fd==nullptr)
  {
    // create a dummy filedef for the example
    yyextra->exampleFileDef = createFileDef(QCString(),(!exName.isEmpty()?exName:"generated"));
    yyextra->sourceFileDef  = yyextra->exampleFileDef.get();
  }
  yyextra->lang        = lang;
  yyextra->insideObjC  = lang==SrcLangExt::ObjC;
  if (yyextra->sourceFileDef)
  {
    setCurrentDoc(yyscanner,"l00001");
  }
  yyextra->currentDefinition = searchCtx ? searchCtx : getResolvedNamespace(scopeName);
  yyextra->currentMemberDef = nullptr;
  yyextra->searchingForBody = exBlock;
  yyextra->insideBody = FALSE;
  yyextra->bracketCount = 0;
  if (!yyextra->exampleName.isEmpty())
  {
    yyextra->exampleFile = convertNameToFile(yyextra->exampleName+"-example",FALSE,TRUE);
    DBG_CTX((stderr,"yyextra->exampleFile=%s\n",qPrint(yyextra->exampleFile)));
  }
  yyextra->includeCodeFragment = inlineFragment;
  DBG_CTX((stderr,"** exBlock=%d exName=%s include=%d\n",exBlock,qPrint(exName),inlineFragment));
  if (!yyextra->insideCodeLine)
  {
    startCodeLine(yyscanner);
  }
  yyextra->type.clear();
  yyextra->name.clear();
  yyextra->args.clear();
  yyextra->parmName.clear();
  yyextra->parmType.clear();
  if (memberDef) setParameterList(yyscanner,memberDef);
  BEGIN( Body );
  codeYYlex(yyscanner);
  yyextra->lexInit=TRUE;
  if (yyextra->insideCodeLine)
  {
    endCodeLine(yyscanner);
  }
  if (Config_getBool(HTML_CODE_FOLDING))
  {
    while (!yyextra->foldStack.empty())
    {
      yyextra->code->endFold();
      yyextra->foldStack.pop_back();
    }
  }
  if (yyextra->exampleFileDef)
  {
    // delete the temporary file definition used for this example
    yyextra->exampleFileDef.reset();
    yyextra->sourceFileDef=nullptr;
  }
  // write the tooltips
  yyextra->tooltipManager.writeTooltips(od);
}
References FileDef::absFilePath(), Config_getBool, convertNameToFile(), countLines(), createFileDef(), QCString::data(), DBG_CTX, endCodeLine(), FALSE, FileDef::fileName(), getResolvedNamespace(), QCString::isEmpty(), Debug::Lex_code, Definition::name(), ObjC, p, qPrint(), setCurrentDoc(), setParameterList(), startCodeLine(), OutputCodeList::stripCodeComments(), and TRUE.
resetCodeParserState()
void CCodeParser::resetCodeParserState () override virtual
Resets the state of the code parser.
Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Definition at line 4059 of file code.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  DBG_CTX((stderr,"***CodeParser::reset()\n"));
  yyextra->theVarContext.clear();
  while (!yyextra->scopeNameLengthStack.empty()) yyextra->scopeNameLengthStack.pop_back();
  yyextra->codeClassMap.clear();
  yyextra->curClassBases.clear();
  yyextra->anchorCount = 0;
  yyextra->insideCodeLine = false;
}
References DBG_CTX, and p.
Referenced by CCodeParser().
setInsideCodeLine()
void CCodeParser::setInsideCodeLine (bool inp)
Definition at line 4071 of file code.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->insideCodeLine = inp;
}
References p.
Member Data Documentation
p
std::unique_ptr<Private> CCodeParser::p private
Definition at line 56 of file code.h.
Referenced by CCodeParser(), insideCodeLine(), parseCode(), resetCodeParserState(), setInsideCodeLine(), and ~CCodeParser().
The documentation for this class was generated from the following files:
src/code.h
src/code.l