Doxygen: ClassTreeContext::Private Class Reference
ClassTreeContext::Private Class Reference
Public Member Functions
Private ()
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
TemplateVariant title () const
int createMaxDepth () const
int createPreferredDepth () const
Private Attributes
TemplateListIntfPtr m_classTree
CachedItem< int, Private, &Private::createMaxDepth > m_maxDepth
CachedItem< int, Private, &Private::createPreferredDepth > m_preferredDepth
Static Private Attributes
static const PropertyMap< ClassTreeContext::Private > s_inst
Detailed Description
Definition at line 6116 of file context.cpp.
Constructor & Destructor Documentation
Private()
ClassTreeContext::Private::Private () inline
Definition at line 6119 of file context.cpp.
    {
      m_classTree = NestingContext::alloc(0,ContextTreeType::ClassNesting,0);
      auto ctx = std::dynamic_pointer_cast<NestingContext>(m_classTree);
      ClassDefSet visitedClasses;
      ctx->addNamespaces(*Doxygen::namespaceLinkedMap,TRUE,TRUE,FALSE,visitedClasses);
      ctx->addClasses(*Doxygen::classLinkedMap,TRUE,visitedClasses);
    }
References NestingContext::alloc(), Doxygen::classLinkedMap, ClassNesting, FALSE, m_classTree, Doxygen::namespaceLinkedMap, and TRUE.
Member Function Documentation
createMaxDepth()
int ClassTreeContext::Private::createMaxDepth () const inline private
Definition at line 6148 of file context.cpp.
    {
      return computeMaxDepth(m_classTree);
    }
References computeMaxDepth(), and m_classTree.
createPreferredDepth()
int ClassTreeContext::Private::createPreferredDepth () const inline private
Definition at line 6152 of file context.cpp.
    {
      return computePreferredDepth(m_classTree,m_maxDepth.get(this));
    }
References computePreferredDepth(), m_classTree, and m_maxDepth.
fields()
StringVector ClassTreeContext::Private::fields () const inline
Definition at line 6130 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fileName()
TemplateVariant ClassTreeContext::Private::fileName () const inline private
Definition at line 6135 of file context.cpp.
{ return "annotated"; }
get()
TemplateVariant ClassTreeContext::Private::get (const QCString & n) const inline
Definition at line 6129 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), and s_inst.
highlight()
TemplateVariant ClassTreeContext::Private::highlight () const inline private
Definition at line 6137 of file context.cpp.
{ return "classes"; }
maxDepth()
TemplateVariant ClassTreeContext::Private::maxDepth () const inline private
Definition at line 6139 of file context.cpp.
{ return m_maxDepth.get(this); }
References m_maxDepth.
preferredDepth()
TemplateVariant ClassTreeContext::Private::preferredDepth () const inline private
Definition at line 6140 of file context.cpp.
{ return m_preferredDepth.get(this); }
References m_preferredDepth.
relPath()
TemplateVariant ClassTreeContext::Private::relPath () const inline private
Definition at line 6136 of file context.cpp.
{ return ""; }
subhighlight()
TemplateVariant ClassTreeContext::Private::subhighlight () const inline private
Definition at line 6138 of file context.cpp.
{ return "classlist"; }
title()
TemplateVariant ClassTreeContext::Private::title () const inline private
Definition at line 6141 of file context.cpp.
    {
      return Config_getBool(OPTIMIZE_FOR_FORTRAN) ? theTranslator->trCompoundListFortran() :
             Config_getBool(OPTIMIZE_OUTPUT_VHDL) ? theTranslator->trDesignUnitList()      :
                                                    theTranslator->trClasses();
    }
References Config_getBool, theTranslator, Translator::trClasses(), Translator::trCompoundListFortran(), and Translator::trDesignUnitList().
tree()
TemplateVariant ClassTreeContext::Private::tree () const inline private
Definition at line 6134 of file context.cpp.
{ return TemplateVariant(m_classTree); }
References m_classTree.
Member Data Documentation
m_classTree
TemplateListIntfPtr ClassTreeContext::Private::m_classTree private
Definition at line 6156 of file context.cpp.
Referenced by createMaxDepth(), createPreferredDepth(), Private(), and tree().
m_maxDepth
CachedItem<int, Private, &Private::createMaxDepth> ClassTreeContext::Private::m_maxDepth private
Definition at line 6157 of file context.cpp.
Referenced by createPreferredDepth(), and maxDepth().
m_preferredDepth
CachedItem<int, Private, &Private::createPreferredDepth> ClassTreeContext::Private::m_preferredDepth private
Definition at line 6158 of file context.cpp.
Referenced by preferredDepth().
s_inst
const PropertyMap< ClassTreeContext::Private > ClassTreeContext::Private::s_inst static private
Initial value:
{
  {  "tree",          &Private::tree },
  {  "fileName",      &Private::fileName },
  {  "relPath",       &Private::relPath },
  {  "highlight",     &Private::highlight },
  {  "subhighlight",  &Private::subhighlight },
  {  "title",         &Private::title },
  {  "preferredDepth",&Private::preferredDepth },
  {  "maxDepth",      &Private::maxDepth }
}
Definition at line 6159 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/context.cpp