Doxygen: src/msc.cpp File Reference
msc.cpp File Reference
#include "msc.h"
#include "portable.h"
#include "config.h"
#include "message.h"
#include "docparser.h"
#include "docnode.h"
#include "doxygen.h"
#include "indexlist.h"
#include "util.h"
#include "mscgen_api.h"
#include "dir.h"
#include "textstream.h"
Functions
static bool convertMapFile (TextStream &t, const QCString &mapName, const QCString &relPath, const QCString &context, const QCString &srcFile, int srcLine)
static bool do_mscgen_generate (const QCString &inFile, const QCString &outFile, mscgen_format_t msc_format, const QCString &srcFile, int srcLine)
void writeMscGraphFromFile (const QCString &inFile, const QCString &outDir, const QCString &outFile, MscOutputFormat format, const QCString &srcFile, int srcLine)
static QCString getMscImageMapFromFile (const QCString &inFile, const QCString &, const QCString &relPath, const QCString &context, bool writeSVGMap, const QCString &srcFile, int srcLine)
void writeMscImageMapFromFile (TextStream &t, const QCString &inFile, const QCString &outDir, const QCString &relPath, const QCString &baseName, const QCString &context, MscOutputFormat format, const QCString &srcFile, int srcLine)
Variables
static const int maxCmdLine = 40960
Function Documentation
convertMapFile()
static bool convertMapFile (TextStream & t, const QCString & mapName, const QCString & relPath, const QCString & context, const QCString & srcFile, int srcLine) static
Definition at line 31 of file msc.cpp.
{
  std::ifstream f = Portable::openInputStream(mapName);
  if (!f.is_open())
  {
    err("failed to open map file %s for inclusion in the docs!\n"
        "If you installed Graphviz/dot after a previous failing run, \n"
        "try deleting the output directory and rerun doxygen.\n",qPrint(mapName));
    return false;
  }
  const int maxLineLen=1024;
  char url[maxLineLen];
  char ref[maxLineLen];
  int x1=0, y1=0, x2=0, y2=0;
  std::string line;
  while (getline(f,line))
  {
    bool isRef = false;
    //printf("ReadLine '%s'\n",line.c_str());
    if (qstrncmp(line.c_str(),"rect",4)==0)
    {
      // obtain the url and the coordinates in the order used by graphviz-1.5
      sscanf(line.c_str(),"rect %s %d,%d %d,%d",url,&x1,&y1,&x2,&y2);
      if (qstrcmp(url,"\\ref")==0 || qstrcmp(url,"@ref")==0)
      {
        isRef = true;
        sscanf(line.c_str(),"rect %s %s %d,%d %d,%d",ref,url,&x1,&y1,&x2,&y2);
      }
      // sanity checks
      if (y2<y1) { int temp=y2; y2=y1; y1=temp; }
      if (x2<x1) { int temp=x2; x2=x1; x1=temp; }
      bool link = false;
      if ( isRef )
      {
        // handle doxygen \ref tag URL reference
        auto parser { createDocParser() };
        auto dfAst  { createRef( *parser.get(), url, context, srcFile, srcLine) };
        auto dfAstImpl = dynamic_cast<const DocNodeAST*>(dfAst.get());
        const DocRef *df = std::get_if<DocRef>(&dfAstImpl->root);
        if (!df->file().isEmpty() || !df->anchor().isEmpty())
        {
          link = true;
          t << "<area href=\"";
          t << externalRef(relPath,df->ref(),TRUE);
        }
        if (!df->file().isEmpty())
        {
          QCString fn = df->file();
          addHtmlExtensionIfMissing(fn);
          t << fn;
        }
        if (!df->anchor().isEmpty())
        {
          t << "#" << df->anchor();
        }
      }
      else
      {
        link = true;
        t << "<area href=\"";
        t << url;
      }
      if (link)
      {
        t << "\" shape=\"rect\" coords=\""
          << x1 << "," << y1 << "," << x2 << "," << y2 << "\""
          << " alt=\"\"/>\n";
      }
    }
  }
  return true;
}
References addHtmlExtensionIfMissing(), DocRef::anchor(), createDocParser(), createRef(), err, externalRef(), DocRef::file(), QCString::isEmpty(), Portable::openInputStream(), qPrint(), qstrcmp(), qstrncmp(), DocRef::ref(), and TRUE.
Referenced by getMscImageMapFromFile().
do_mscgen_generate()
static bool do_mscgen_generate (const QCString & inFile, const QCString & outFile, mscgen_format_t msc_format, const QCString & srcFile, int srcLine) static
Definition at line 111 of file msc.cpp.
{
  auto mscgen_tool = Config_getString(MSCGEN_TOOL).stripWhiteSpace();
  if (!mscgen_tool.isEmpty()) // use external mscgen tool
  {
    QCString type;
    switch (msc_format)
    {
      case mscgen_format_png:
        type = "png";
        break;
      case mscgen_format_eps:
        type = "eps";
        break;
      case mscgen_format_svg:
        type = "svg";
        break;
      case mscgen_format_pngmap:
      case mscgen_format_svgmap:
        type = "ismap";
        break;
    }
    int exitcode = Portable::system(mscgen_tool,"-T"+type+" -o "+outFile+" "+inFile);
    if (exitcode!=0)
    {
      err_full(srcFile,srcLine,"Problems running external tool %s given via MSCGEN_TOOL (exit status: %d)."
          " Look for typos in your msc file and check error messages above.",
          qPrint(mscgen_tool),exitcode);
      return false;
    }
  }
  else // use built-in mscgen tool
  {
    int code = mscgen_generate(inFile.data(),outFile.data(),msc_format);
    if (code!=0)
    {
      err_full(srcFile,srcLine,"Problems generating msc output (error=%s). Look for typos in you msc file '%s'",
          mscgen_error2str(code),qPrint(inFile));
      return false;
    }
  }
  return true;
}
References Config_getString, QCString::data(), err_full, qPrint(), and Portable::system().
Referenced by getMscImageMapFromFile(), and writeMscGraphFromFile().
getMscImageMapFromFile()
static QCString getMscImageMapFromFile (const QCString & inFile, const QCString & , const QCString & relPath, const QCString & context, bool writeSVGMap, const QCString & srcFile, int srcLine) static
Definition at line 214 of file msc.cpp.
{
  QCString outFile = inFile + ".map";
  if (!do_mscgen_generate(inFile,outFile,
                            writeSVGMap ? mscgen_format_svgmap : mscgen_format_pngmap,
                            srcFile,srcLine))
    return "";
  TextStream t;
  convertMapFile(t, outFile, relPath, context, srcFile, srcLine);
  Dir().remove(outFile.str());
  return t.str();
}
References convertMapFile(), do_mscgen_generate(), Dir::remove(), QCString::str(), and TextStream::str().
Referenced by writeMscImageMapFromFile().
writeMscGraphFromFile()
void writeMscGraphFromFile (const QCString & inFile, const QCString & outDir, const QCString & outFile, MscOutputFormat format, const QCString & srcFile, int srcLine)
Definition at line 156 of file msc.cpp.
{
  QCString absOutFile = outDir;
  absOutFile+=Portable::pathSeparator();
  absOutFile+=outFile;
  mscgen_format_t msc_format = mscgen_format_png;
  QCString imgName = absOutFile;
  switch (format)
  {
    case MscOutputFormat::BITMAP:
      msc_format = mscgen_format_png;
      imgName+=".png";
      break;
    case MscOutputFormat::EPS:
      msc_format = mscgen_format_eps;
      imgName+=".eps";
      break;
    case MscOutputFormat::SVG:
      msc_format = mscgen_format_svg;
      imgName+=".svg";
      break;
    default:
      return;
  }
  if (!do_mscgen_generate(inFile,imgName,msc_format,srcFile,srcLine))
  {
    return;
  }
  if ( (format==MscOutputFormat::EPS) && (Config_getBool(USE_PDFLATEX)) )
  {
    QCString epstopdfArgs(maxCmdLine, QCString::ExplicitSize);
    epstopdfArgs.sprintf("\"%s.eps\" --outfile=\"%s.pdf\"",
                         qPrint(absOutFile),qPrint(absOutFile));
    if (Portable::system("epstopdf",epstopdfArgs)!=0)
    {
      err_full(srcFile,srcLine,"Problems running epstopdf when processing '%s.eps'. Check your TeX installation!",
          qPrint(absOutFile));
    }
    else
    {
      Dir().remove((absOutFile + ".eps").data());
    }
  }
  int i=std::max(imgName.findRev('/'),imgName.findRev('\\'));
  if (i!=-1) // strip path
  {
    imgName=imgName.right(imgName.length()-i-1);
  }
  Doxygen::indexList->addImageFile(imgName);
}
References BITMAP, Config_getBool, do_mscgen_generate(), EPS, err_full, QCString::ExplicitSize, QCString::findRev(), Doxygen::indexList, QCString::length(), maxCmdLine, Portable::pathSeparator(), qPrint(), Dir::remove(), QCString::right(), QCString::sprintf(), SVG, and Portable::system().
Referenced by DocbookDocVisitor::startMscFile(), LatexDocVisitor::startMscFile(), DocbookDocVisitor::writeMscFile(), HtmlDocVisitor::writeMscFile(), LatexDocVisitor::writeMscFile(), and RTFDocVisitor::writeMscFile().
writeMscImageMapFromFile()
void writeMscImageMapFromFile (TextStream & t, const QCString & inFile, const QCString & outDir, const QCString & relPath, const QCString & baseName, const QCString & context, MscOutputFormat format, const QCString & srcFile, int srcLine)
Definition at line 233 of file msc.cpp.
{
  QCString mapName = baseName+".map";
  t << "<img src=\"" << relPath << baseName << ".";
  switch (format)
  {
    case MscOutputFormat::BITMAP:
      t << "png";
      break;
    case MscOutputFormat::EPS:
      t << "eps";
      break;
    case MscOutputFormat::SVG:
      t << "svg";
      break;
    default:
      t << "unknown";
  }
  QCString imap = getMscImageMapFromFile(inFile,outDir,relPath,context,format==MscOutputFormat::SVG,srcFile,srcLine);
  if (!imap.isEmpty())
  {
    t << "\" alt=\""
      << baseName << "\" border=\"0\" usemap=\"#" << mapName << "\"/>\n";
    t << "<map name=\"" << mapName << "\" id=\"" << mapName << "\">" << imap << "</map>\n";
  }
  else
  {
    t << "\" alt=\"" << baseName << "\" border=\"0\"/>\n";
  }
}
References BITMAP, EPS, getMscImageMapFromFile(), QCString::isEmpty(), and SVG.
Referenced by HtmlDocVisitor::writeMscFile().
Variable Documentation
maxCmdLine
const int maxCmdLine = 40960 static
Definition at line 29 of file msc.cpp.