Doxygen: PerlModOutputStream Class Reference
PerlModOutputStream Class Reference
Public Member Functions
PerlModOutputStream (std::ostream &t)
void add (char c)
void add (const QCString &s)
void add (int n)
void add (unsigned int n)
Public Attributes
std::ostream & m_t
Detailed Description
Definition at line 45 of file perlmodgen.cpp.
Constructor & Destructor Documentation
PerlModOutputStream()
PerlModOutputStream::PerlModOutputStream (std::ostream & t) inline
Definition at line 51 of file perlmodgen.cpp.
: m_t(t) { }
Member Function Documentation
add() [1/4]
void PerlModOutputStream::add (char c)
Definition at line 59 of file perlmodgen.cpp.
{
  m_t << c;
  //if (m_t != 0)
  //  (*m_t) << c;
  //else
  //  m_s += c;
}
References m_t.
Referenced by PerlModOutput::add(), PerlModOutput::add(), PerlModOutput::add(), PerlModOutput::add(), PerlModOutput::add(), PerlModOutput::continueBlock(), PerlModOutput::iaddField(), PerlModOutput::iaddFieldQuotedChar(), PerlModOutput::iaddFieldQuotedString(), PerlModOutput::iaddQuoted(), PerlModOutput::iclose(), PerlModOutput::indent(), and PerlModOutput::iopen().
add() [2/4]
void PerlModOutputStream::add (const QCString & s)
Definition at line 68 of file perlmodgen.cpp.
{
  m_t << s;
  //if (m_t != 0)
  //  (*m_t) << s;
  //else
  //  m_s += s;
}
References m_t.
add() [3/4]
void PerlModOutputStream::add (int n)
Definition at line 77 of file perlmodgen.cpp.
{
  m_t << n;
  //if (m_t != 0)
  //  (*m_t) << n;
  //else
  //  m_s += QCString().setNum(n);
}
References m_t.
add() [4/4]
void PerlModOutputStream::add (unsigned int n)
Definition at line 86 of file perlmodgen.cpp.
{
  m_t << n;
  //if (m_t != 0)
  //  (*m_t) << n;
  //else
  //  m_s += QCString().setNum(n);
}
References m_t.
Member Data Documentation
m_t
std::ostream& PerlModOutputStream::m_t
Definition at line 49 of file perlmodgen.cpp.
Referenced by add(), add(), add(), and add().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/perlmodgen.cpp