Doxygen: src/portable.h File Reference
portable.h File Reference
Portable versions of functions that are platform dependent.
#include <stdio.h>
#include <sys/types.h>
#include <stdint.h>
#include <fstream>
#include "containers.h"
#include "qcstring.h"
Namespaces
namespace Portable
Functions
int Portable::system (const QCString &command, const QCString &args, bool commandHasConsole=true)
uint32_t Portable::pid ()
QCString Portable::getenv (const QCString &variable)
void Portable::setenv (const QCString &variable, const QCString &value)
void Portable::unsetenv (const QCString &variable)
FILE * Portable::fopen (const QCString &fileName, const QCString &mode)
int Portable::fclose (FILE *f)
void Portable::unlink (const QCString &fileName)
QCString Portable::pathSeparator ()
QCString Portable::pathListSeparator ()
const char * Portable::ghostScriptCommand ()
const char * Portable::commandExtension ()
bool Portable::fileSystemIsCaseSensitive ()
FILE * Portable::popen (const QCString &name, const QCString &type)
int Portable::pclose (FILE *stream)
double Portable::getSysElapsedTime ()
bool Portable::isAbsolutePath (const QCString &fileName)
void Portable::correctPath (const StringVector &list)
Correct a possible wrong PATH variable.
void Portable::setShortDir ()
const char * Portable::strnstr (const char *haystack, const char *needle, size_t haystack_len)
const char * Portable::devNull ()
bool Portable::checkForExecutable (const QCString &fileName)
size_t Portable::recodeUtf8StringToW (const QCString &inputStr, uint16_t **buf)
std::ofstream Portable::openOutputStream (const QCString &name, bool append=false)
std::ifstream Portable::openInputStream (const QCString &name, bool binary=false, bool openAtEnd=false)
void * portable_iconv_open (const char *tocode, const char *fromcode)
size_t portable_iconv (void *cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft)
int portable_iconv_close (void *cd)
Detailed Description
Portable versions of functions that are platform dependent.
Definition in file portable.h.
Function Documentation
portable_iconv()
size_t portable_iconv (void * cd, const char ** inbuf, size_t * inbytesleft, char ** outbuf, size_t * outbytesleft)
Referenced by configStringRecode(), encodeForOutput(), HtmlHelpRecoder::recode(), Portable::recodeUtf8StringToW(), transcodeCharacterBuffer(), and transcodeCharacterStringToUTF8().
portable_iconv_close()
int portable_iconv_close (void * cd)
Referenced by adjustConfiguration(), configStringRecode(), encodeForOutput(), HtmlHelpRecoder::finalize(), Portable::recodeUtf8StringToW(), transcodeCharacterBuffer(), and transcodeCharacterStringToUTF8().
portable_iconv_open()
void * portable_iconv_open (const char * tocode, const char * fromcode)
Referenced by adjustConfiguration(), configStringRecode(), encodeForOutput(), HtmlHelpRecoder::initialize(), Portable::recodeUtf8StringToW(), transcodeCharacterBuffer(), and transcodeCharacterStringToUTF8().