Doxygen: InheritanceNodeContext::Private Class Reference
InheritanceNodeContext::Private Class Reference
Public Member Functions
Private (const ClassDef *cd, const QCString &name)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant getClass () const
TemplateVariant name () const
TemplateVariant createClass () const
Private Attributes
const ClassDef * m_classDef
CachedItem< TemplateVariant, Private, &Private::createClass > m_classContext
QCString m_name
Static Private Attributes
static const PropertyMap< InheritanceNodeContext::Private > s_inst
Detailed Description
Definition at line 7493 of file context.cpp.
Constructor & Destructor Documentation
Private()
InheritanceNodeContext::Private::Private (const ClassDef * cd, const QCString & name) inline
Definition at line 7496 of file context.cpp.
      : m_classDef(cd), m_name(name) {}
Member Function Documentation
createClass()
TemplateVariant InheritanceNodeContext::Private::createClass () const inline private
Definition at line 7509 of file context.cpp.
    {
      return ClassContext::alloc(m_classDef);
    }
References ClassContext::alloc(), and m_classDef.
fields()
StringVector InheritanceNodeContext::Private::fields () const inline
Definition at line 7501 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
get()
TemplateVariant InheritanceNodeContext::Private::get (const QCString & n) const inline
Definition at line 7500 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), and s_inst.
getClass()
TemplateVariant InheritanceNodeContext::Private::getClass () const inline private
Definition at line 7505 of file context.cpp.
{ return m_classContext.get(this); }
References m_classContext.
name()
TemplateVariant InheritanceNodeContext::Private::name () const inline private
Definition at line 7506 of file context.cpp.
{ return m_name; }
References m_name.
Member Data Documentation
m_classContext
CachedItem<TemplateVariant, Private, &Private::createClass> InheritanceNodeContext::Private::m_classContext private
Definition at line 7514 of file context.cpp.
Referenced by getClass().
m_classDef
const ClassDef* InheritanceNodeContext::Private::m_classDef private
Definition at line 7513 of file context.cpp.
Referenced by createClass().
m_name
QCString InheritanceNodeContext::Private::m_name private
Definition at line 7515 of file context.cpp.
Referenced by name().
s_inst
const PropertyMap< InheritanceNodeContext::Private > InheritanceNodeContext::Private::s_inst static private
Initial value:
{
  {  "class",&Private::getClass },
  {  "name", &Private::name }
}
Definition at line 7516 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/context.cpp