Doxygen: TranslatorItalian Class Reference
TranslatorItalian Class Reference
#include <src/translator_it.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool) override
QCString trNamespace (bool first_capital, bool) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString updateNeededMessage () override
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString updateNeededMessage () override
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 92 of file translator_it.h.
Member Function Documentation
getLanguageString()
QCString TranslatorItalian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 119 of file translator_it.h.
    {
      return "0x410 Italian";
    }
idLanguage()
QCString TranslatorItalian::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 104 of file translator_it.h.
    { return "italian"; }
latexLanguageSupportCommand()
QCString TranslatorItalian::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method was designed for languages which do wish to use a babel package.
Implements Translator.
Definition at line 110 of file translator_it.h.
    {
      return "\\usepackage[italian]{babel}\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorItalian::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1849 of file translator_it.h.
    { return "Altri membri ereditati"; }
trAll()
QCString TranslatorItalian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1365 of file translator_it.h.
    {
      return "Tutto";
    }
trAndMore()
QCString TranslatorItalian::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1826 of file translator_it.h.
    { return "e altri "+number+" ..."; }
trAttention()
QCString TranslatorItalian::trAttention () inline override virtual
Implements Translator.
Definition at line 978 of file translator_it.h.
    {
      return "Attenzione";
    }
trAuthor()
QCString TranslatorItalian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1237 of file translator_it.h.
    {
      return createNoun(first_capital, singular, "autor", "i", "e");
    }
References Translator::createNoun().
trBug()
QCString TranslatorItalian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1136 of file translator_it.h.
    {
      return "Bug";
    }
trBugList()
QCString TranslatorItalian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1141 of file translator_it.h.
    {
      return "Lista dei bug";
    }
trCallerGraph()
QCString TranslatorItalian::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1484 of file translator_it.h.
    {
      return "Questo  il grafo dei chiamanti di questa funzione:";
    }
trCallGraph()
QCString TranslatorItalian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1370 of file translator_it.h.
    {
      return "Questo  il grafo delle chiamate per questa funzione:";
    }
trCiteReferences()
QCString TranslatorItalian::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1802 of file translator_it.h.
    { return "Riferimenti bibliografici"; }
trClass()
QCString TranslatorItalian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1172 of file translator_it.h.
    {
      return createNoun(first_capital, singular, "class", "i", "e");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorItalian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 526 of file translator_it.h.
    {
      return "Diagramma delle classi per "+clName;
    }
trClassDocumentation()
QCString TranslatorItalian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 420 of file translator_it.h.
    { return "Documentazione delle classi"; }
trClasses()
QCString TranslatorItalian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1099 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strutture dati";
      }
      else
      {
          return "Classi";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorItalian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 219 of file translator_it.h.
    { return "Gerarchia delle classi"; }
trClassHierarchyDescription()
QCString TranslatorItalian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 278 of file translator_it.h.
    {
        return "Questo elenco di ereditariet  ordinato "
        "approssimativamente, ma non completamente, in ordine alfabetico:";
    }
trClassMethods()
QCString TranslatorItalian::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1887 of file translator_it.h.
    {
      return "Metodi della classe";
    }
trCode()
QCString TranslatorItalian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 877 of file translator_it.h.
    {
      return "codice";
    }
trCollaborationDiagram()
QCString TranslatorItalian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 832 of file translator_it.h.
    {
      return "Diagramma di collaborazione per "+clName+":";
    }
trCompoundIndex()
QCString TranslatorItalian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 393 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indice delle strutture dati";
      }
      else
      {
        return "Indice dei tipi composti";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorItalian::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1538 of file translator_it.h.
    { return "Indice dei tipi dati"; }
trCompoundList()
QCString TranslatorItalian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 223 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strutture dati";
      }
      else
      {
        return "Elenco dei tipi composti";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorItalian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 295 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Queste sono le strutture dati con una loro breve descrizione:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Queste sono le classi con una loro breve descrizione:";
      }
      else
      {
        return "Queste sono le classi, le struct, le union e le interfacce con una loro breve descrizione:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorItalian::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1512 of file translator_it.h.
    { return "Questi sono i tipi dato con una loro breve descrizione:"; }
trCompoundListFortran()
QCString TranslatorItalian::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1504 of file translator_it.h.
    { return "Elenco dei tipi di dato"; }
trCompoundMembers()
QCString TranslatorItalian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 240 of file translator_it.h.
     {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campi dei dati";
      }
      else
      {
        return "Membri dei composti";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorItalian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 313 of file translator_it.h.
    {
      QCString result="Questo  un elenco ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        if (!extractAll) result+="delle struct e delle union documentate ";
        else result+="di tutte le struct e le union ";
      }
      else
      {
        if (!extractAll) result+="dei membri documentati ";
        else result+="di tutti i membri ";
      }
      result+="con collegamenti alla documentazione ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
          if (extractAll) result+="della struct/union per ciascun campo:";
          else result+="delle struct/union a cui appartengono:";
      }
      else
      {
          if (extractAll) result+="della classe a cui appartengono:";
          else result+="delle classi a cui appartengono:";
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorItalian::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1516 of file translator_it.h.
    {
      QCString result="Questa  una lista di tutti i membri ";
      if (!extractAll)
      {
        result+="documentati ";
      }
      result+="dei tipi di dato con collegamenti ";
      if (!extractAll)
      {
         result+="alla documentazione della struttura dati per ciascun membro:";
      }
      else
      {
         result+="ai tipi dato a cui appartengono:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorItalian::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1508 of file translator_it.h.
    { return "Membri dei tipi di dato"; }
trCompoundReference()
QCString TranslatorItalian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 602 of file translator_it.h.
    {
      QCString result="Riferimenti per ";
      if (isTemplate) result="Template per ";
      switch(compType)
      {
        case ClassDef::Class:  result+="la classe "; break;
        case ClassDef::Struct: result+="la struct "; break;
        case ClassDef::Union:  result+="la union "; break;
        case ClassDef::Interface:  result+="l'interfaccia "; break;
        case ClassDef::Protocol:   result+="il protocollo "; break;
        case ClassDef::Category:   result+="la categoria "; break;
        case ClassDef::Exception:  result+="l'eccezione "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorItalian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1579 of file translator_it.h.
    {
      QCString result="Riferimenti per ";
      if (isTemplate) result="Template per ";
      switch(compType)
      {
        case ClassDef::Class:      result+=" il modulo"; break;
        case ClassDef::Struct:     result+=" il tipo dato"; break;
        case ClassDef::Union:      result+=" l'union"; break;
        case ClassDef::Interface:  result+=" l'nterfaccia"; break;
        case ClassDef::Protocol:   result+=" il protocollo"; break;
        case ClassDef::Category:   result+=" la categoria"; break;
        case ClassDef::Exception:  result+=" l'eccezione"; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorItalian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 502 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strutture dati";
      }
      else
      {
        return "Composti";
      }
    }
References Config_getBool.
trConstantGroupReference()
QCString TranslatorItalian::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1924 of file translator_it.h.
    {
      QCString result="Riferimenti per il gruppo di costanti ";
      result+=namespaceName;
      return result;
    }
trConstantGroups()
QCString TranslatorItalian::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1920 of file translator_it.h.
    { return "Gruppi di costanti"; }
trConstructorDocumentation()
QCString TranslatorItalian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 842 of file translator_it.h.
    {
      return "Documentazione dei costruttori e dei distruttori";
    }
trCopyright()
QCString TranslatorItalian::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1806 of file translator_it.h.
    { return "Copyright"; }
trDataTypes()
QCString TranslatorItalian::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1562 of file translator_it.h.
    { return "Tipi di dato"; }
trDate()
QCString TranslatorItalian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 540 of file translator_it.h.
    { return "Data"; }
trDateTime()
QCString TranslatorItalian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1755 of file translator_it.h.
    {
      static const char *days[]   = { "Lun","Mar","Mer","Gio","Ven","Sab","Dom" };
      static const char *months[] = { "Gen","Feb","Mar","Apr","Mag","Giu","Lug","Ago","Set","Ott","Nov","Dic" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorItalian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1775 of file translator_it.h.
    {
      static const char *days_short[]   = { "lun", "mar", "mer", "gio", "ven", "sab", "dom" };
      static const char *days_full[]    = { "luned", "marted", "mercoled", "gioved", "venerd", "sabato", "domenica" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorItalian::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1791 of file translator_it.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorItalian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 809 of file translator_it.h.
    {
      return "Definizione alla linea @0 del file @1.";
    }
trDefinedIn()
QCString TranslatorItalian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 207 of file translator_it.h.
    { return "definito in"; }
trDefinedInSourceFile()
QCString TranslatorItalian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 813 of file translator_it.h.
    {
      return "Definizione nel file @0.";
    }
trDefineDocumentation()
QCString TranslatorItalian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 472 of file translator_it.h.
    { return "Documentazione delle definizioni"; }
trDefines()
QCString TranslatorItalian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 436 of file translator_it.h.
    { return "Definizioni"; }
trDefineValue()
QCString TranslatorItalian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1126 of file translator_it.h.
    {
      return "Valore:";
    }
trDeprecated()
QCString TranslatorItalian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 822 of file translator_it.h.
    {
      return "Deprecato";
    }
trDeprecatedList()
QCString TranslatorItalian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1292 of file translator_it.h.
    {
      return "Lista degli elementi deprecati";
    }
trDetailedDescription()
QCString TranslatorItalian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 135 of file translator_it.h.
    { return "Descrizione dettagliata"; }
trDetailLevel()
QCString TranslatorItalian::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1818 of file translator_it.h.
    { return "livello di dettaglio"; }
trDetails()
QCString TranslatorItalian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 139 of file translator_it.h.
    { return "Dettagli"; }
trDir()
QCString TranslatorItalian::trDir (bool first_capital, bool) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1460 of file translator_it.h.
    {
      return createNoun(first_capital, false, "directory", "");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorItalian::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1810 of file translator_it.h.
    { return QCString("Grafo di dipendenza delle directory per ")+name+":"; }
trDirDocumentation()
QCString TranslatorItalian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1442 of file translator_it.h.
    { return "Documentazione delle directory"; }
trDirectories()
QCString TranslatorItalian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1448 of file translator_it.h.
    { return "Directory"; }
trDirIndex()
QCString TranslatorItalian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1436 of file translator_it.h.
    { return "Gerarchia delle directory"; }
trDirReference()
QCString TranslatorItalian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1454 of file translator_it.h.
    { QCString result="Riferimenti per la directory "; result+=dirName; return result; }
trDirRelation()
QCString TranslatorItalian::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1694 of file translator_it.h.
    {
      return "Relazione per "+QCString(name);
    }
trDocumentation()
QCString TranslatorItalian::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 375 of file translator_it.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Documentazione"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorItalian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 448 of file translator_it.h.
    { return "Tipi enumerati (enum)"; }
trEnumerationTypeDocumentation()
QCString TranslatorItalian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 484 of file translator_it.h.
    { return "Documentazione dei tipi enumerati"; }
trEnumerationValueDocumentation()
QCString TranslatorItalian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1492 of file translator_it.h.
    { return "Documentazione dei tipi enumerati"; }
trEnumerationValues()
QCString TranslatorItalian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 466 of file translator_it.h.
    { return "Valori del tipo enumerato"; }
trEnumGeneratedFromFiles()
QCString TranslatorItalian::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1830 of file translator_it.h.
    { QCString result = "La documentazione per questo tipo enumerato  stata generata a partire";
      if (!single) result += " dai seguenti";
      else result += " dal seguente";
      result+=" file:";
      return result;
    }
trEnumName()
QCString TranslatorItalian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 199 of file translator_it.h.
    { return "nome di tipo enumerato"; }
trEnumReference()
QCString TranslatorItalian::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1839 of file translator_it.h.
    { return QCString("Riferimenti per il tipo enumerato ") + QCString(name); }
trEnumValue()
QCString TranslatorItalian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 203 of file translator_it.h.
    { return "valore di tipo enumerato"; }
trEventDocumentation()
QCString TranslatorItalian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1309 of file translator_it.h.
    {
      return "Documentazione degli eventi";
    }
trEvents()
QCString TranslatorItalian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1304 of file translator_it.h.
    {
      return "Eventi";
    }
trExamples()
QCString TranslatorItalian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 270 of file translator_it.h.
    { return "Esempi"; }
trExamplesDescription()
QCString TranslatorItalian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 361 of file translator_it.h.
    { return "Questo  l'elenco di tutti gli esempi:"; }
trExceptions()
QCString TranslatorItalian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 556 of file translator_it.h.
    { return "Eccezioni"; }
trExtendsClass()
QCString TranslatorItalian::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1879 of file translator_it.h.
    {
      return "Estende la classe @0.";
    }
trFile()
QCString TranslatorItalian::trFile (bool first_capital, bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1181 of file translator_it.h.
    {
      return createNoun(first_capital, false, "file", "");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorItalian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 426 of file translator_it.h.
    { return "Documentazione dei file"; }
trFileIn()
QCString TranslatorItalian::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1731 of file translator_it.h.
    {
      return "File in "+name;
    }
trFileIndex()
QCString TranslatorItalian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 408 of file translator_it.h.
    { return "Indice dei file"; }
trFileList()
QCString TranslatorItalian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 236 of file translator_it.h.
    { return "Elenco dei file"; }
trFileListDescription()
QCString TranslatorItalian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 285 of file translator_it.h.
    {
      QCString result="Questo  un elenco ";
      if (!extractAll) result+="dei file documentati ";
      else result+="di tutti i file ";
      result+="con una loro breve descrizione:";
      return result;
    }
trFileMembers()
QCString TranslatorItalian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 253 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Elementi globali";
      }
      else
      {
        return "Elementi dei file";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorItalian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 341 of file translator_it.h.
    {
      QCString result="Questo  un elenco ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
          if (!extractAll) result+="delle funzioni, delle variabili, delle define, dei tipi enumerati e delle ridefinizioni dei tipi (typedef) documentate ";
          else result+="di tutte le funzioni, variabili, define, tipi enumerati, e ridefinizioni dei tipi (typedef) ";
      }
      else
      {
          if (!extractAll) result+="degli elementi documentati dei file ";
          else result+="di tutti gli elementi dei file ";
      }
      result+="con collegamenti alla documentazione";
      if (extractAll) result+=" del file a cui appartengono:";
      else result+=":";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorItalian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 625 of file translator_it.h.
    {
      QCString result="Riferimenti per il file ";
      result+=fileName;
      return result;
    }
trFriends()
QCString TranslatorItalian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 584 of file translator_it.h.
    { return "Friend"; }
trFunctionDocumentation()
QCString TranslatorItalian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 490 of file translator_it.h.
    { return "Documentazione delle funzioni"; }
trFunctions()
QCString TranslatorItalian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 454 of file translator_it.h.
    { return "Funzioni"; }
trGeneratedAt()
QCString TranslatorItalian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 517 of file translator_it.h.
    {
      QCString result="Generato "+date;
      if (!projName.isEmpty()) result+=" per "+projName;
      result+=" da";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorItalian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 190 of file translator_it.h.
    {
      QCString result="Generato automaticamente da Doxygen";
      if (!s.isEmpty()) result+=" per "+s;
      result+=" a partire dal codice sorgente.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorItalian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 560 of file translator_it.h.
    { return "Generato da"; }
trGeneratedFromFiles()
QCString TranslatorItalian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 764 of file translator_it.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentazione per quest";
      switch(compType)
      {
        case ClassDef::Class:      result+="a classe"; break;
        case ClassDef::Struct:     result+="a struct"; break;
        case ClassDef::Union:      result+="a union"; break;
        case ClassDef::Interface:  result+="a interfaccia"; break;
        case ClassDef::Protocol:   result+="o protocollo"; break;
        case ClassDef::Category:   result+="a categoria"; break;
        case ClassDef::Exception:  result+="a eccezione"; break;
        default: break;
      }
      result+="  stata generata a partire ";
      if (single) result+="dal seguente file:";
      else result+="dai seguenti file:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorItalian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1646 of file translator_it.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentazione per quest";
      switch(compType)
      {
        case ClassDef::Class:      result+="o modulo"; break;
        case ClassDef::Struct:     result+="o tipo"; break;
        case ClassDef::Union:      result+="a union"; break;
        case ClassDef::Interface:  result+="a interfaccia"; break;
        case ClassDef::Protocol:   result+="o protocollo"; break;
        case ClassDef::Category:   result+="a categoria"; break;
        case ClassDef::Exception:  result+="a eccezione"; break;
        default: break;
      }
      result+="  stata generata a partire ";
      if (single) result+="dal seguente file:"; else result+="dai seguenti file:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorItalian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1226 of file translator_it.h.
    {
      return createNoun(first_capital, singular, "global", "i", "e");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorItalian::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1706 of file translator_it.h.
    {
      return "Namespace globale";
    }
trGotoDocumentation()
QCString TranslatorItalian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 852 of file translator_it.h.
    {
      return "Vai alla documentazione di questo file.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorItalian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 885 of file translator_it.h.
    {
      return "Vai al grafico della gerarchia delle classi";
    }
trGotoSourceCode()
QCString TranslatorItalian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 847 of file translator_it.h.
    {
      return "Vai al codice sorgente di questo file.";
    }
trGotoTextualHierarchy()
QCString TranslatorItalian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 889 of file translator_it.h.
    {
      return "Vai alla gerarchia delle classi (testuale)";
    }
trGraphicalHierarchy()
QCString TranslatorItalian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 881 of file translator_it.h.
    {
      return "Grafico della gerarchia delle classi";
    }
trGroup()
QCString TranslatorItalian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_it.h.
    {
      return createNoun(first_capital, singular, "grupp", "i", "o");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorItalian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 387 of file translator_it.h.
    { return "Indice della gerarchia"; }
trImplementedFromList()
QCString TranslatorItalian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1260 of file translator_it.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorItalian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1268 of file translator_it.h.
    {
      return "Implementato in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorItalian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 982 of file translator_it.h.
    {
      return "Questo grafo mostra quali altri file includono direttamente o indirettamente questo file:";
    }
trInclDepGraph()
QCString TranslatorItalian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 837 of file translator_it.h.
    {
      return "Grafo delle dipendenze di inclusione per "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorItalian::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1740 of file translator_it.h.
    {
      return "Include il file in "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorItalian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 184 of file translator_it.h.
    { return ", inclusi tutti i membri ereditati."; }
trInheritedByList()
QCString TranslatorItalian::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 697 of file translator_it.h.
    {
      return "Base per "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorItalian::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1843 of file translator_it.h.
    { return QCString(members)+" ereditati da "+what; }
trInheritsList()
QCString TranslatorItalian::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 689 of file translator_it.h.
    {
      return "Eredita da "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorItalian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 872 of file translator_it.h.
    {
      return "Valore iniziale:";
    }
trInstanceMethods()
QCString TranslatorItalian::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1895 of file translator_it.h.
    {
      return "Metodi di instanza";
    }
trInterfaces()
QCString TranslatorItalian::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1912 of file translator_it.h.
    { return "Interfacce esportate"; }
trInvariant()
QCString TranslatorItalian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 867 of file translator_it.h.
    {
      return "Invariante";
    }
trISOLang()
QCString TranslatorItalian::trISOLang () inline override virtual
Implements Translator.
Definition at line 115 of file translator_it.h.
    {
      return "it";
    }
trLegend()
QCString TranslatorItalian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1059 of file translator_it.h.
    {
      return "legenda";
    }
trLegendDocs()
QCString TranslatorItalian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 1001 of file translator_it.h.
    {
      return
        "Questa pagina spiega come interpretare i grafi generati da doxygen.<p>\n"
        "Si consideri l'esempio seguente:\n"
        "\\code\n"
        "/*! Classe invisibile per troncamento */\n"
        "class Invisible { };\n\n"
        "/*! Classe tronca, la relazione di ereditariet  nascosta */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe non documentata con i commenti speciali di doxygen*/\n"
        "class Undocumented { };\n\n"
        "/*! Classe estesa mediante ereditariet pubblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Classe templatizzata */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe estesa mediante ereditariet protetta*/\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe estesa mediante ereditariet privata*/\n"
        "class PrivateBase { };\n\n"
        "/*! Classe utilizzata dalla classe Inherited */\n"
        "class Used { };\n\n"
        "/*! Classe che eredita da varie classi*/\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Verr prodotto il grafo seguente:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "I riquadri nel grafo qui sopra hanno il seguente significato:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Il riquadro grigio pieno rappresenta la struct o la classe per la quale il grafo  stato generato.</li>\n"
        "<li>Un riquadro con un bordo nero denota una struct o una classe documentata.</li>\n"
        "<li>Un riquadro con un bordo grigio indica una struct o una classe non documentata.</li>\n"
        "<li>Un riquadro con un bordo rosso indica una struct o una classe per la quale non sono mostrate tutte le relazioni di ereditariet/contenimento (un grafo viene troncato se non rientra nei limiti prestabiliti).</li>\n"
        "</ul>\n"
        "<p>\n"
        "Le frecce hanno il seguente significato:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Una freccia blu scuro indica una relazione di ereditariet pubblica tra due classi.</li>\n"
        "<li>Una freccia verde indica un'ereditariet protetta.</li>\n"
        "<li>Una freccia rossa indica un'ereditariet privata.</li>\n"
        "<li>Una freccia viola tratteggiata indica che una classe  contenuta o usata da un'altra classe."
        " La freccia viene etichettata con la o le variabili attraverso cui la struct o la classe puntata dalla freccia  accessibile.</li>\n"
        "<li>Una freccia gialla tratteggiata indica la relazione tra una istanza di un template e la classe templatizzata da cui  stata istanziata."
        " La freccia viene etichettata con i parametri di template dell'istanza.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorItalian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 996 of file translator_it.h.
    {
      return "Legenda del grafo";
    }
trListOfAllMembers()
QCString TranslatorItalian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 172 of file translator_it.h.
    { return "Elenco di tutti i membri"; }
trLoading()
QCString TranslatorItalian::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1700 of file translator_it.h.
    {
      return "Caricamento in corso...";
    }
trMainPage()
QCString TranslatorItalian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 796 of file translator_it.h.
    { return "Pagina Principale"; }
trMember()
QCString TranslatorItalian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1217 of file translator_it.h.
    {
      return createNoun(first_capital, singular, "membr", "i", "o");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorItalian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 155 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentazione dei campi";
      }
      else
      {
        return "Documentazione dei membri dato";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorItalian::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 147 of file translator_it.h.
    { return "Documentazione dei tipi enumerati (enum)"; }
trMemberFunctionDocumentation()
QCString TranslatorItalian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 151 of file translator_it.h.
    { return "Documentazione delle funzioni membro"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorItalian::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1500 of file translator_it.h.
    { return "Documentazione delle funzioni membro/subroutine"; }
trMemberList()
QCString TranslatorItalian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 176 of file translator_it.h.
    { return "Elenco dei membri"; }
trMemberTypedefDocumentation()
QCString TranslatorItalian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 143 of file translator_it.h.
    { return "Documentazione delle ridefinizioni dei tipi (typedef)"; }
trMethodDocumentation()
QCString TranslatorItalian::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1902 of file translator_it.h.
    {
      return "Documentazione dei metodi";
    }
trModule()
QCString TranslatorItalian::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1639 of file translator_it.h.
    {
      return createNoun(first_capital, singular, "modul", "i", "o");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorItalian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 414 of file translator_it.h.
    { return "Documentazione dei moduli"; }
trModuleIndex()
QCString TranslatorItalian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 381 of file translator_it.h.
    { return "Indice dei moduli"; }
trModuleReference()
QCString TranslatorItalian::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1601 of file translator_it.h.
    {
      QCString result="Riferimenti per il modulo ";
      result+=namespaceName;
      return result;
    }
trModules()
QCString TranslatorItalian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 215 of file translator_it.h.
    { return "Moduli"; }
trModulesDescription()
QCString TranslatorItalian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 369 of file translator_it.h.
    { return "Questo  l'elenco di tutti i moduli:"; }
trModulesIndex()
QCString TranslatorItalian::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1632 of file translator_it.h.
    { return "Indice dei moduli"; }
trModulesList()
QCString TranslatorItalian::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1566 of file translator_it.h.
    { return "Elenco dei moduli"; }
trModulesListDescription()
QCString TranslatorItalian::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1570 of file translator_it.h.
    {
      QCString result="Questa  una lista di tutti i moduli ";
      if (!extractAll) result+="documentati ";
      result+="con una loro breve descrizione:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorItalian::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1613 of file translator_it.h.
    {
      QCString result="Questo  un elenco di tutti i membri dei moduli ";
      if (!extractAll) result+="documentati ";
      result+="con collegamenti ";
      if (extractAll)
      {
        result+="alla documentazione del modulo per ciascun membro:";
      }
      else
      {
        result+="al modulo a cui appartengono:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorItalian::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1609 of file translator_it.h.
    { return "Membri del modulo"; }
trMonth()
QCString TranslatorItalian::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1783 of file translator_it.h.
    {
      static const char *months_short[] = { "gen", "feb", "mar", "apr", "mag", "giu", "lug", "ago", "set", "ott", "nov", "dic" };
      static const char *months_full[]  = { "gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno", "luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorItalian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 168 of file translator_it.h.
    { return "Continua..."; }
trNamespace()
QCString TranslatorItalian::trNamespace (bool first_capital, bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1190 of file translator_it.h.
    {
      return createNoun(first_capital, false, "namespace", "");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorItalian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 744 of file translator_it.h.
    { return "Documentazione dei namespace"; }
trNamespaceIndex()
QCString TranslatorItalian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 738 of file translator_it.h.
    { return "Indice dei namespace"; }
trNamespaceList()
QCString TranslatorItalian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 568 of file translator_it.h.
    { return "Lista dei namespace"; }
trNamespaceListDescription()
QCString TranslatorItalian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 572 of file translator_it.h.
    {
      QCString result="Questa  l'elenco ";
      if (!extractAll) result+="dei namespace documentati, ";
      else result+="di tutti i namespace ";
      result+="con una loro breve descrizione:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorItalian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 723 of file translator_it.h.
    {
      QCString result="Questa  la lista ";
      if (!extractAll) result+="dei membri documentati del namespace, ";
       else result+="di tutti i membri del namespace ";
      result+="con collegamenti ";
      if (extractAll)
        result+="alla documentazione del namespace per ciascun membro:";
      else
        result+="ai namespace a cui appartengono:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorItalian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 719 of file translator_it.h.
    { return "Membri dei namespace"; }
trNamespaceReference()
QCString TranslatorItalian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 633 of file translator_it.h.
    {
      QCString result="Riferimenti per il namespace ";
      result+=namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorItalian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 754 of file translator_it.h.
    { return "Namespace"; }
trNoMatches()
QCString TranslatorItalian::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1718 of file translator_it.h.
    {
      return "Nessun risultato";
    }
trNote()
QCString TranslatorItalian::trNote () inline override virtual
Implements Translator.
Definition at line 902 of file translator_it.h.
    {
      return "Nota";
    }
trOverloadText()
QCString TranslatorItalian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1472 of file translator_it.h.
    {
       return "Questa  una funzione membro sovraccaricata (overloaded), "
              "fornita per comodit. Differisce dalla funzione di cui sopra "
              "unicamente per gli argomenti passati.";
    }
trPackage()
QCString TranslatorItalian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1111 of file translator_it.h.
    {
      return "Package "+name;
    }
trPackageAttribs()
QCString TranslatorItalian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1346 of file translator_it.h.
    {
      return "Attributi con visibilit di package";
    }
trPackageFunctions()
QCString TranslatorItalian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1328 of file translator_it.h.
    {
      return "Funzioni con visibilit di package";
    }
trPackageListDescription()
QCString TranslatorItalian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1116 of file translator_it.h.
    {
      return "Questi sono i package e una loro breve descrizione (se disponibile):";
    }
trPackageMembers()
QCString TranslatorItalian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1332 of file translator_it.h.
    {
      return "Membri con visibilit di package";
    }
trPackages()
QCString TranslatorItalian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1121 of file translator_it.h.
    {
      return "Package";
    }
trPackageTypes()
QCString TranslatorItalian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1321 of file translator_it.h.
    {
      return "Tipi con visibilit di package";
    }
trPage()
QCString TranslatorItalian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1208 of file translator_it.h.
    {
      return createNoun(first_capital, singular, "pagin", "e", "a");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorItalian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 802 of file translator_it.h.
    { return "pag."; }
trPageIndex()
QCString TranslatorItalian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 893 of file translator_it.h.
    {
      return "Indice delle pagine";
    }
trPanelSynchronisationTooltip()
QCString TranslatorItalian::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1860 of file translator_it.h.
    {
      QCString opt = enable ? "abilitare" : "disabilitare";
      return "cliccare per "+opt+" la sincronizzazione del pannello";
    }
trParameters()
QCString TranslatorItalian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 552 of file translator_it.h.
    { return "Parametri"; }
trPostcondition()
QCString TranslatorItalian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 862 of file translator_it.h.
    {
      return "Postcondizione";
    }
trPrecondition()
QCString TranslatorItalian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 857 of file translator_it.h.
    {
      return "Precondizione";
    }
trPrivateAttribs()
QCString TranslatorItalian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 942 of file translator_it.h.
    {
      return "Attributi privati";
    }
trPrivateMembers()
QCString TranslatorItalian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 655 of file translator_it.h.
    { return "Membri privati"; }
trPrivateSlots()
QCString TranslatorItalian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 657 of file translator_it.h.
    { return "Slot privati"; }
trPrivateTypes()
QCString TranslatorItalian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 938 of file translator_it.h.
    {
      return "Tipi privati";
    }
trProperties()
QCString TranslatorItalian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1084 of file translator_it.h.
    {
      return "Propriet";
    }
trPropertyDocumentation()
QCString TranslatorItalian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1089 of file translator_it.h.
    {
      return "Documentazione delle propriet";
    }
trProtectedAttribs()
QCString TranslatorItalian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 930 of file translator_it.h.
    {
      return "Attributi protetti";
    }
trProtectedMembers()
QCString TranslatorItalian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 649 of file translator_it.h.
    { return "Membri protetti"; }
trProtectedSlots()
QCString TranslatorItalian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 651 of file translator_it.h.
    { return "Slot protetti"; }
trProtectedTypes()
QCString TranslatorItalian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 926 of file translator_it.h.
    {
      return "Tipi protetti";
    }
trProvidedByCategory()
QCString TranslatorItalian::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1870 of file translator_it.h.
    {
      return "Fornito dalla categoria @0.";
    }
trPublicAttribs()
QCString TranslatorItalian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 910 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campi";
      }
      else
      {
      return "Attributi pubblici";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorItalian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 641 of file translator_it.h.
    { return "Membri pubblici"; }
trPublicSlots()
QCString TranslatorItalian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 643 of file translator_it.h.
    { return "Slot pubblici"; }
trPublicTypes()
QCString TranslatorItalian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 906 of file translator_it.h.
    {
      return "Tipi pubblici";
    }
trReferencedBy()
QCString TranslatorItalian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 970 of file translator_it.h.
    {
      return "Referenziato da";
    }
trReferenceManual()
QCString TranslatorItalian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 430 of file translator_it.h.
    { return "Manuale di riferimento"; }
trReferences()
QCString TranslatorItalian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1248 of file translator_it.h.
    {
      return "Referenzia";
    }
trReimplementedFromList()
QCString TranslatorItalian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 705 of file translator_it.h.
    {
      return "Reimplementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorItalian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 713 of file translator_it.h.
    {
      return "Reimplementata in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorItalian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 594 of file translator_it.h.
    { return "Documentazione dei friend e delle funzioni collegate"; }
trRelatedFunctions()
QCString TranslatorItalian::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 127 of file translator_it.h.
    { return "Funzioni collegate"; }
trRelatedPages()
QCString TranslatorItalian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 266 of file translator_it.h.
    { return "Pagine collegate"; }
trRelatedPagesDescription()
QCString TranslatorItalian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 365 of file translator_it.h.
    { return "Questo  l'elenco di tutte le pagine di documentazione collegate:"; }
trRelatedSubscript()
QCString TranslatorItalian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 131 of file translator_it.h.
    { return "(Si noti che queste non sono funzioni membro.)"; }
trRemarks()
QCString TranslatorItalian::trRemarks () inline override virtual
Implements Translator.
Definition at line 974 of file translator_it.h.
    {
      return "Osservazioni";
    }
trReturns()
QCString TranslatorItalian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 544 of file translator_it.h.
    { return "Restituisce"; }
trReturnValues()
QCString TranslatorItalian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 791 of file translator_it.h.
    { return "Valori di ritorno"; }
trRTFansicp()
QCString TranslatorItalian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1151 of file translator_it.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorItalian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1157 of file translator_it.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorItalian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1163 of file translator_it.h.
    {
      return "Indice";
    }
trRTFTableOfContents()
QCString TranslatorItalian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1280 of file translator_it.h.
    {
      return "Sommario";
    }
trSearch()
QCString TranslatorItalian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 274 of file translator_it.h.
    { return "Cerca"; }
trSearching()
QCString TranslatorItalian::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1712 of file translator_it.h.
    {
      return "Ricerca in corso...";
    }
trSearchMatches()
QCString TranslatorItalian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1413 of file translator_it.h.
    {
      return "Corrispondenze:";
    }
trSearchResults()
QCString TranslatorItalian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1394 of file translator_it.h.
    {
      if (numDocuments==0)
      {
        return "Nessun documento soddisfa la tua richiesta.";
      }
      else if (numDocuments==1)
      {
        return "Trovato <b>1</b> documento che soddisfa la tua richiesta.";
      }
      else
      {
        return "Trovati <b>$num</b> documenti che soddisfano la tua richiesta. "
               "Le corrispondenze migliori sono in testa.";
      }
    }
trSearchResultsTitle()
QCString TranslatorItalian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1382 of file translator_it.h.
    {
      return "Risultati della ricerca";
    }
trSeeAlso()
QCString TranslatorItalian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 548 of file translator_it.h.
    { return "Si veda anche"; }
trServiceGeneratedFromFiles()
QCString TranslatorItalian::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 1945 of file translator_it.h.
    {
      // single is true implies a single file
      QCString result="La documentazione per questo servizio "
                                " stata generata a partire ";
      if (single) result+="dal seguente file:"; else result+="dai seguenti file:";
      return result;
    }
trServiceReference()
QCString TranslatorItalian::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 1931 of file translator_it.h.
    {
      QCString result="Riferimenti per il servizio ";
      result+=sName;
      return result;
    }
trServices()
QCString TranslatorItalian::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1916 of file translator_it.h.
    { return "Servizi inclusi"; }
trSignals()
QCString TranslatorItalian::trSignals () inline override virtual
Implements Translator.
Definition at line 645 of file translator_it.h.
    { return "Signal"; }
trSince()
QCString TranslatorItalian::trSince () inline override virtual
Implements Translator.
Definition at line 986 of file translator_it.h.
    {
      return "A partire da";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorItalian::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 1954 of file translator_it.h.
    {
      // single is true implies a single file
      QCString result="La documentazione per questo singleton "
                                " stata generata a partire ";
      if (single) result+="dal seguente file:"; else result+="dai seguenti file:";
      return result;
    }
trSingletonReference()
QCString TranslatorItalian::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 1938 of file translator_it.h.
    {
      QCString result="Riferimenti per il singleton ";
      result+=sName;
      return result;
    }
trSourceFile()
QCString TranslatorItalian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1424 of file translator_it.h.
    {
      return " File sorgente " + filename ;
    }
trStaticPackageAttribs()
QCString TranslatorItalian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1353 of file translator_it.h.
    {
      return "Attributi statici con visibilit di package";
    }
trStaticPackageFunctions()
QCString TranslatorItalian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1339 of file translator_it.h.
    {
      return "Funzioni statiche con visibilit di package";
    }
trStaticPrivateAttribs()
QCString TranslatorItalian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 946 of file translator_it.h.
    {
      return "Attributi privati statici";
    }
trStaticPrivateMembers()
QCString TranslatorItalian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 659 of file translator_it.h.
    { return "Membri privati statici"; }
trStaticProtectedAttribs()
QCString TranslatorItalian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 934 of file translator_it.h.
    {
      return "Attributi protetti statici";
    }
trStaticProtectedMembers()
QCString TranslatorItalian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 653 of file translator_it.h.
    { return "Membri protetti statici"; }
trStaticPublicAttribs()
QCString TranslatorItalian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 922 of file translator_it.h.
    {
      return "Attributi pubblici statici";
    }
trStaticPublicMembers()
QCString TranslatorItalian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 647 of file translator_it.h.
    { return "Membri pubblici statici"; }
trSubprogram()
QCString TranslatorItalian::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1678 of file translator_it.h.
    {
      return createNoun(first_capital, singular, "sottoprogramm", "i", "a");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorItalian::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1556 of file translator_it.h.
    { return "Documentazione funzioni/subroutine"; }
trSubprograms()
QCString TranslatorItalian::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1550 of file translator_it.h.
    { return "Funzioni/Subroutine"; }
trTemplateParameters()
QCString TranslatorItalian::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1822 of file translator_it.h.
    { return "Parametri dei template"; }
trTest()
QCString TranslatorItalian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1069 of file translator_it.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorItalian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1074 of file translator_it.h.
    {
      return "Lista dei test";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorItalian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 180 of file translator_it.h.
    { return "Questo  l'elenco completo di tutti i membri di"; }
trTodo()
QCString TranslatorItalian::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 956 of file translator_it.h.
    {
      return "Da fare";
    }
trTodoList()
QCString TranslatorItalian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 961 of file translator_it.h.
    {
      return "Elenco delle cose da fare";
    }
trType()
QCString TranslatorItalian::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1670 of file translator_it.h.
    {
      return createNoun(first_capital, singular, "tip", "i", "o");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorItalian::trTypeConstraints () inline override virtual
C# Type Contraint list
Implements Translator.
Definition at line 1684 of file translator_it.h.
    {
      return "Vincoli dei tipi";
    }
trTypedefDocumentation()
QCString TranslatorItalian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 478 of file translator_it.h.
    { return "Documentazione delle ridefinizioni di tipo (typedef)"; }
trTypedefs()
QCString TranslatorItalian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 442 of file translator_it.h.
    { return "Ridefinizioni di tipo (typedef)"; }
trTypeDocumentation()
QCString TranslatorItalian::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1544 of file translator_it.h.
    { return "Documentazione dei tipi dato"; }
trVariableDocumentation()
QCString TranslatorItalian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 496 of file translator_it.h.
    { return "Documentazione delle variabili"; }
trVariables()
QCString TranslatorItalian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 460 of file translator_it.h.
    { return "Variabili"; }
trVersion()
QCString TranslatorItalian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 536 of file translator_it.h.
    { return "Versione"; }
trWarning()
QCString TranslatorItalian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 532 of file translator_it.h.
    { return "Avvertimento"; }
trWriteList()
QCString TranslatorItalian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 665 of file translator_it.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=", e ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_it.h