Doxygen: /home/runner/work/doxygen/doxygen/src/configimpl.l File Reference
configimpl.l File Reference
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <ctype.h>
#include <stdarg.h>
#include <errno.h>
#include <thread>
#include <algorithm>
#include <iostream>
#include <iomanip>
#include <cstdint>
#include "config.h"
#include "regex.h"
#include "configimpl.h"
#include "version.h"
#include "portable.h"
#include "message.h"
#include "language.h"
#include "configoptions.h"
#include "fileinfo.h"
#include "dir.h"
#include "textstream.h"
#include "dotattributes.h"
#include "debug.h"
#include "doxygen_lex.h"
Classes
struct ConfigFileState
Macros
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1
#define SHOW_INCLUDES 0
#define USE_STATE2STRING 0
#define MAX_INCLUDE_DEPTH 10
#define YY_NEVER_INTERACTIVE 1
#define unput_string(yytext, yyleng) do { for (int i=(int)yyleng-1;i>=0;i--) unput(yytext[i]); } while(0)
#define YY_INPUT(buf, result, max_size) result=yyread(buf,max_size);
#define LEX_NO_REENTRANT
Functions
void config_err (const char *fmt,...)
void config_term (const char *fmt,...)
void config_warn (const char *fmt,...)
static QCString configStringRecode (const QCString &str, const QCString &fromEncoding, const QCString &toEncoding)
static bool containsEnvVar (QCString &str)
static QCString convertToComment (const QCString &s, const QCString &u)
static bool convertStringToBool (const QCString &str, bool &isValid)
static const char * getLexerFILE ()
static int yyread (char *buf, int max_size)
static void checkEncoding ()
static QCString stripComment (const QCString &s)
static void processStoreRepl (QCString &storeReplStr)
static void processString ()
static void processList ()
static FILE * tryPath (const QCString &path, const QCString &fileName)
static void substEnvVarsInStrList (StringVector &sl)
static void substEnvVarsInString (QCString &s)
static FILE * findFile (const QCString &fileName)
static void readIncludeFile (const QCString &incName)
int yylex (void)
static QCString configFileToString (const QCString &name)
static void cleanUpPaths (StringVector &str)
static bool checkFileName (const QCString &s, const char *optionName)
static void checkList (const StringVector &list, const char *name, bool equalRequired, bool valueRequired)
static void adjustBoolSetting (const char *depOption, const char *optionName, bool expectedValue)
static void adjustStringSetting (const char *depOption, const char *optionName, const QCString &expectedValue)
static void adjustColorStyleSetting (const char *depOption)
static void updateAttribute (DotAttributes &attr, QCString name, ConfigObsolete *value)
Variables
static const char * warning_str = "warning: "
static const char * error_str = "error: "
static const char * g_inputString
static int g_inputPosition
static int g_yyLineNr
static QCString g_yyFileName
static QCString g_cmd
static QCString * g_string =0
static StringVector * g_list =0
static QCString g_listStr
static StringVector g_includePathList
static std::vector< std::unique_ptr< ConfigFileState > > g_includeStack
static bool g_configUpdate = FALSE
static QCString g_encoding
static ConfigImpl * g_config
static Config::CompareMode g_compareMode = Config::CompareMode::Full
static QCString g_localStoreRepl
static const reg::Ex reEnvVar (R"(\$\‍((\a[\w.-]*)\‍))")
static const reg::Ex reEnvVarExt (R"(\$\‍((\a[\w.-]*\‍(\a[\w.-]*\‍))\‍))")
static const reg::Ex reEnvVarCMake (R"(@\a\w*@)")
Macro Definition Documentation
LEX_NO_REENTRANT
#define LEX_NO_REENTRANT
Definition at line 648 of file configimpl.l.
MAX_INCLUDE_DEPTH
#define MAX_INCLUDE_DEPTH 10
Definition at line 96 of file configimpl.l.
SHOW_INCLUDES
#define SHOW_INCLUDES 0
Definition at line 53 of file configimpl.l.
unput_string
#define unput_string (yytext, yyleng) do { for (int i=(int)yyleng-1;i>=0;i--) unput(yytext[i]); } while(0)
Definition at line 640 of file configimpl.l.
USE_STATE2STRING
#define USE_STATE2STRING 0
Definition at line 55 of file configimpl.l.
YY_INPUT
#define YY_INPUT (buf, result, max_size) result=yyread(buf,max_size);
Definition at line 644 of file configimpl.l.
YY_NEVER_INTERACTIVE
#define YY_NEVER_INTERACTIVE 1
Definition at line 97 of file configimpl.l.
YY_NO_INPUT
#define YY_NO_INPUT 1
Definition at line 49 of file configimpl.l.
YY_NO_UNISTD_H
#define YY_NO_UNISTD_H 1
Definition at line 50 of file configimpl.l.
Function Documentation
adjustBoolSetting()
static void adjustBoolSetting (const char * depOption, const char * optionName, bool expectedValue) static
Definition at line 1667 of file configimpl.l.
{
  // lookup option by name
  const ConfigValues::Info *option = ConfigValues::instance().get(optionName);
  if (option && option->type==ConfigValues::Info::Bool) // safety check
  {
    if (ConfigValues::instance().*(option->value.b)!=expectedValue) // current value differs from expectation
    {
      err("When enabling %s the %s option should be %s. I'll adjust it for you.\n",depOption,optionName,expectedValue? "enabled" : "disabled");
      ConfigValues::instance().*(option->value.b)=expectedValue; // adjust option
    }
  }
}
References err.
Referenced by Config::checkAndCorrect().
adjustColorStyleSetting()
static void adjustColorStyleSetting (const char * depOption) static
Definition at line 1695 of file configimpl.l.
{
  auto updateColorStyle = [&depOption](HTML_COLORSTYLE_t curStyle,HTML_COLORSTYLE_t newStyle)
  {
    err("When enabling '%s' the 'HTML_COLORSTYLE' option should be either 'LIGHT' or 'DARK' but has value '%s'. I'll adjust it for you to '%s'.\n",
        depOption,
        qPrint(HTML_COLORSTYLE_enum2str(curStyle)),
        qPrint(HTML_COLORSTYLE_enum2str(newStyle)));
    Config_updateEnum(HTML_COLORSTYLE,newStyle);
  };
  auto colorStyle = Config_getEnum(HTML_COLORSTYLE);
  switch (colorStyle)
  {
    case HTML_COLORSTYLE_t::LIGHT:
    case HTML_COLORSTYLE_t::DARK:
      // no adjustment needed
      break;
    case HTML_COLORSTYLE_t::AUTO_LIGHT:
    case HTML_COLORSTYLE_t::TOGGLE:
      updateColorStyle(colorStyle,HTML_COLORSTYLE_t::LIGHT);
      break;
    case HTML_COLORSTYLE_t::AUTO_DARK:
      updateColorStyle(colorStyle,HTML_COLORSTYLE_t::DARK);
      break;
  }
}
References Config_getEnum, Config_updateEnum, err, and qPrint().
Referenced by Config::checkAndCorrect().
adjustStringSetting()
static void adjustStringSetting (const char * depOption, const char * optionName, const QCString & expectedValue) static
Definition at line 1681 of file configimpl.l.
{
  // lookup option by name
  const ConfigValues::Info *option = ConfigValues::instance().get(optionName);
  if (option && option->type==ConfigValues::Info::String) // safety check
  {
    if (ConfigValues::instance().*(option->value.s)!=expectedValue) // current value differs from expectation
    {
      err("When enabling %s the %s option should have value '%s'. I'll adjust it for you.\n",depOption,optionName,qPrint(expectedValue));
      ConfigValues::instance().*(option->value.s)=expectedValue; // adjust option
    }
  }
}
References err, and qPrint().
Referenced by Config::checkAndCorrect().
checkEncoding()
static void checkEncoding () static
Definition at line 709 of file configimpl.l.
{
  ConfigString *option = dynamic_cast<ConfigString*>(g_config->get("DOXYFILE_ENCODING"));
  g_encoding = *option->valueRef();
}
References g_config, g_encoding, ConfigImpl::get(), and ConfigString::valueRef().
Referenced by processString().
checkFileName()
static bool checkFileName (const QCString & s, const char * optionName) static
Definition at line 1619 of file configimpl.l.
{
  QCString val = s.stripWhiteSpace().lower();
  if ((val=="yes" || val=="true"  || val=="1" || val=="all") ||
      (val=="no"  || val=="false" || val=="0" || val=="none"))
  {
    err("file name expected for option %s, got %s instead. Ignoring...\n",optionName,qPrint(s));
    return false;
  }
  return true;
}
References err, QCString::lower(), qPrint(), and QCString::stripWhiteSpace().
Referenced by Config::checkAndCorrect().
checkList()
static void checkList (const StringVector & list, const char * name, bool equalRequired, bool valueRequired) static
Definition at line 1637 of file configimpl.l.
{
  for (const auto &s: list)
  {
    QCString item=s.c_str();
    item=item.stripWhiteSpace();
    int i=item.find('=');
    if (i==-1 && equalRequired)
    {
      err("Illegal format for option %s, no equal sign ('=') specified for item '%s'\n",name,qPrint(item));
    }
    if (i!=-1)
    {
      QCString myName=item.left(i).stripWhiteSpace();
      if (myName.isEmpty())
      {
        err("Illegal format for option %s, no name specified for item '%s'\n",name,qPrint(item));
      }
      else if (valueRequired)
      {
        QCString myValue=item.right(item.length()-i-1).stripWhiteSpace();
        if (myValue.isEmpty())
        {
          err("Illegal format for option %s, no value specified for item '%s'\n",name,qPrint(item));
        }
      }
    }
  }
}
References err, QCString::find(), QCString::isEmpty(), QCString::left(), QCString::length(), qPrint(), QCString::right(), and QCString::stripWhiteSpace().
Referenced by Config::checkAndCorrect().
cleanUpPaths()
static void cleanUpPaths (StringVector & str) static
Definition at line 1600 of file configimpl.l.
{
  for (size_t i=0;i<str.size();i++)
  {
    std::string path = str[i];
    std::replace(path.begin(),path.end(),'\\','/');
    if ((path[0]!='/' && (path.size()<=2 || path[1]!=':')) || path[path.size()-1]!='/')
    {
      FileInfo fi(path);
      if (fi.exists() && fi.isDir())
      {
        path = fi.absFilePath();
        if (path[path.size()-1]!='/') path+='/';
      }
    }
    str[i]=path;
  }
}
References FileInfo::absFilePath(), FileInfo::exists(), and FileInfo::isDir().
Referenced by Config::checkAndCorrect().
config_err()
void config_err (const char * fmt, ...)
Definition at line 64 of file configimpl.l.
{
  va_list args;
  va_start(args, fmt);
  vfprintf(stderr, qPrint(QCString(error_str) + fmt), args);
  va_end(args);
}
References error_str, and qPrint().
Referenced by tryPath().
config_term()
void config_term (const char * fmt, ...)
Definition at line 71 of file configimpl.l.
{
  va_list args;
  va_start(args, fmt);
  vfprintf(stderr, qPrint(QCString(error_str) + fmt), args);
  va_end(args);
  fprintf(stderr, "%s\n", "Exiting...");
  exit(1);
}
References error_str, and qPrint().
Referenced by Config::checkAndCorrect(), configFileToString(), configStringRecode(), ConfigImpl::getBool(), ConfigImpl::getEnum(), ConfigImpl::getInt(), ConfigImpl::getList(), ConfigImpl::getString(), ConfigImpl::init(), and readIncludeFile().
config_warn()
void config_warn (const char * fmt, ...)
Definition at line 81 of file configimpl.l.
{
  va_list args;
  va_start(args, fmt);
  vfprintf(stderr, qPrint(QCString(warning_str) + fmt), args);
  va_end(args);
}
References qPrint(), and warning_str.
Referenced by ConfigEnum::convertStrToVal(), ConfigInt::convertStrToVal(), ConfigBool::convertStrToVal(), processList(), and processString().
configFileToString()
static QCString configFileToString (const QCString & name) static
Definition at line 1538 of file configimpl.l.
{
  if (name.isEmpty()) return QCString();
  auto stream2string = [](std::istream &in) -> std::string
  {
    std::string ret;
    char buffer[4096];
    while (in.read(buffer, sizeof(buffer))) ret.append(buffer, sizeof(buffer));
    ret.append(buffer, static_cast<uint32_t>(in.gcount()));
    if (!ret.empty() && ret[ret.length()-1]!='\n') ret+='\n'; // to help the scanner
    return ret;
  };
  if (name=="-") // read from stdin
  {
    // read contents from stdin into contents string
    return stream2string(std::cin);
  }
  else // read from file
  {
    std::ifstream f = Portable::openInputStream(name);
    if (!f.is_open())
    {
      config_term("file '%s' not found or could not be opened\n",qPrint(name));
      return "";
    }
    return stream2string(f);
  }
}
References config_term(), QCString::isEmpty(), Portable::openInputStream(), and qPrint().
Referenced by ConfigImpl::parse().
configStringRecode()
static QCString configStringRecode (const QCString & str, const QCString & fromEncoding, const QCString & toEncoding) static
Definition at line 673 of file configimpl.l.
{
  if (inputEncoding.isEmpty() || outputEncoding.isEmpty() || inputEncoding==outputEncoding) return str;
  size_t inputSize=str.length();
  size_t outputSize=inputSize*4+1;
  QCString output(outputSize);
  void *cd = portable_iconv_open(outputEncoding.data(),inputEncoding.data());
  if (cd==reinterpret_cast<void *>(-1))
  {
    config_term("Error: unsupported character conversion: '%s'->'%s'\n"
                "Check the 'DOXYFILE_ENCODING' setting in the config file!\n",
        qPrint(inputEncoding),qPrint(outputEncoding));
  }
  size_t iLeft=inputSize;
  size_t oLeft=outputSize;
  const char *inputPtr  = str.data();
  char *outputPtr = output.rawData();
  if (!portable_iconv(cd, &inputPtr, &iLeft, &outputPtr, &oLeft))
  {
    outputSize-=oLeft;
    output.resize(outputSize+1);
    output.at(outputSize)='\0';
    //printf("iconv: input size=%d output size=%d\n[%s]\n",size,newSize,qPrint(srcBuf));
  }
  else
  {
    config_term("Error: failed to translate characters from %s to %s: %s\n",
        qPrint(inputEncoding),qPrint(outputEncoding),strerror(errno));
  }
  portable_iconv_close(cd);
  return output;
}
References QCString::at(), config_term(), QCString::data(), QCString::isEmpty(), QCString::length(), portable_iconv(), portable_iconv_close(), portable_iconv_open(), qPrint(), QCString::rawData(), and QCString::resize().
Referenced by processList(), processStoreRepl(), processString(), and ConfigOption::writeStringValue().
containsEnvVar()
static bool containsEnvVar (QCString & str) static
Definition at line 1362 of file configimpl.l.
{
  reg::Match m;
  std::string s = str.str();
  return reg::search(s,m,reEnvVar) || reg::search(s,m,reEnvVarExt) || reg::search(s,m,reEnvVarCMake);
}
References reEnvVar, reEnvVarCMake, reEnvVarExt, reg::search(), and QCString::str().
Referenced by ConfigInt::compareDoxyfile(), ConfigBool::compareDoxyfile(), ConfigEnum::convertStrToVal(), ConfigInt::convertStrToVal(), and ConfigBool::convertStrToVal().
convertStringToBool()
static bool convertStringToBool (const QCString & str, bool & isValid) static
Definition at line 230 of file configimpl.l.
{
  isValid=false;
  QCString val = str.stripWhiteSpace().lower();
  if (!val.isEmpty())
  {
    if (val=="yes" || val=="true" || val=="1" || val=="all")
    {
      isValid=true;
      return true;
    }
    else if (val=="no" || val=="false" || val=="0" || val=="none")
    {
      isValid=true;
      return false;
    }
  }
  return false;
}
References QCString::isEmpty(), QCString::lower(), and QCString::stripWhiteSpace().
Referenced by ConfigBool::convertStrToVal(), and Config::updateObsolete().
convertToComment()
static QCString convertToComment (const QCString & s, const QCString & u) static
Definition at line 101 of file configimpl.l.
{
  //printf("convertToComment(%s)=%s\n",qPrint(s),qPrint(u));
  QCString result;
  if (!s.isEmpty())
  {
    QCString tmp=s.stripWhiteSpace();
    const char *p=tmp.data();
    char c;
    if (p)
    {
      result+="#";
      if (*p && *p!='\n')
      {
        result+=" ";
      }
      while ((c=*p++))
      {
        if (c=='\n')
        {
          result+="\n#";
          if (*p && *p!='\n')
          {
            result+=" ";
          }
        }
        else result+=c;
      }
      result+='\n';
    }
  }
  if (!u.isEmpty())
  {
    if (!result.isEmpty()) result+='\n';
    result+= u;
  }
  return result;
}
References QCString::data(), QCString::isEmpty(), and QCString::stripWhiteSpace().
Referenced by ConfigImpl::writeTemplate(), ConfigInt::writeTemplate(), ConfigBool::writeTemplate(), ConfigList::writeTemplate(), ConfigEnum::writeTemplate(), and ConfigString::writeTemplate().
findFile()
static FILE * findFile (const QCString & fileName) static
Definition at line 920 of file configimpl.l.
{
  if (fileName.isEmpty())
  {
    return 0;
  }
  if (Portable::isAbsolutePath(fileName))
  {
    return tryPath(QCString(), fileName);
  }
  substEnvVarsInStrList(g_includePathList);
  for (const auto &s : g_includePathList)
  {
    FILE *f = tryPath(s.c_str(),fileName);
    if (f) return f;
  }
  // try cwd if g_includePathList fails
  return tryPath(".",fileName);
}
References g_includePathList, Portable::isAbsolutePath(), QCString::isEmpty(), substEnvVarsInStrList(), and tryPath().
Referenced by readIncludeFile().
getLexerFILE()
static const char * getLexerFILE () inline static
Definition at line 647 of file configimpl.l.
{return __FILE__;}
processList()
static void processList () static
Definition at line 811 of file configimpl.l.
{
  bool allowCommaAsSeparator = g_cmd!="PREDEFINED";
  QCString s = stripComment(g_listStr.stripWhiteSpace());
  int l = s.length();
  QCString elemStr;
  bool wasQuote=false;
  // helper to push elemStr to the list and clear it
  auto addElem = [&elemStr,&wasQuote]()
  {
    if (!elemStr.isEmpty())
    {
      QCString e = configStringRecode(elemStr,g_encoding,"UTF-8");
      //printf("Processed list element '%s'\n",qPrint(e));
      if (wasQuote) e = "\""+e+"\"";
      wasQuote = false;
      g_list->push_back(e.str());
      elemStr="";
    }
  };
  bool needsSeparator=false;
  bool insideQuote=false;
  bool warned=false;
  for (int i=0;i<l;i++)
  {
    char c = s.at(i);
    if (!needsSeparator && c=='\\') // escaped character
    {
      if (i<l-1 && s.at(i+1)=='"') // unescape the quote character
      {
        elemStr+='"';
      }
      else // keep other escaped characters in escaped form
      {
        elemStr+=c;
        if (i<l-1)
        {
          elemStr+=s.at(i+1);
        }
      }
      i++; // skip over the escaped character
    }
    else if (!needsSeparator && c=='"') // quote character
    {
      if (!insideQuote)
      {
        insideQuote=true;
        wasQuote=true;
      }
      else // this quote ends an element
      {
        insideQuote=false;
        needsSeparator=true;
      }
    }
    else if (!insideQuote && ((c==',' && allowCommaAsSeparator) || isspace(c))) // separator
    {
      needsSeparator=false;
      addElem();
    }
    else // normal content character
    {
      if (needsSeparator)
      {
        if (!warned)
        {
          config_warn("Invalid value for '%s' tag at line %d, file %s: Values in list '%s' are not properly space %sseparated\n",
                    qPrint(g_cmd),g_yyLineNr,qPrint(g_yyFileName),qPrint(g_listStr.stripWhiteSpace()),allowCommaAsSeparator?"or comma ":"");
          warned=true;
        }
        needsSeparator=false;
        i--; // try the character again as part of a new element
        addElem();
      }
      else
      {
        elemStr+=c;
      }
    }
  }
  // add last part
  addElem();
  if (insideQuote)
  {
    config_warn("Invalid value for '%s' tag at line %d, file %s: Values in list '%s' are not properly quoted\n",
                qPrint(g_cmd),g_yyLineNr,qPrint(g_yyFileName),qPrint(g_listStr.stripWhiteSpace()));
  }
}
References QCString::at(), config_warn(), configStringRecode(), g_cmd, g_encoding, g_list, g_listStr, g_yyFileName, g_yyLineNr, QCString::isEmpty(), QCString::length(), qPrint(), QCString::str(), stripComment(), and QCString::stripWhiteSpace().
processStoreRepl()
static void processStoreRepl (QCString & storeReplStr) static
Definition at line 743 of file configimpl.l.
{
  // strip leading and trailing whitespace
  QCString s = stripComment(storeReplStr.stripWhiteSpace());
  // recode the string
  storeReplStr=configStringRecode(s,g_encoding,"UTF-8");
}
References configStringRecode(), g_encoding, stripComment(), and QCString::stripWhiteSpace().
processString()
static void processString () static
Definition at line 751 of file configimpl.l.
{
  // strip leading and trailing whitespace
  QCString s = stripComment(g_string->stripWhiteSpace());
  int l = s.length();
  // remove surrounding quotes if present (and not escaped)
  if (l>=2 && s.at(0)=='"' && s.at(l-1)=='"' && // remove quotes
      (s.at(l-2)!='\\' || (s.at(l-2)=='\\' && s.at(l-3)=='\\')))
  {
    s=s.mid(1,s.length()-2);
    l=s.length();
  }
  // check for invalid and/or escaped quotes
  bool warned=false;
  QCString result;
  for (int i=0;i<l;i++)
  {
    char c = s.at(i);
    if (c=='\\') // escaped character
    {
      if (i<l-1 && s.at(i+1)=='"') // unescape the quote character
      {
        result+='"';
      }
      else // keep other escaped characters in escaped form
      {
        result+=c;
        if (i<l-1)
        {
          result+=s.at(i+1);
        }
      }
      i++; // skip over the escaped character
    }
    else if (c=='"') // unescaped quote
    {
      if (!warned)
      {
        config_warn("Invalid value for '%s' tag at line %d, file %s: Value '%s' is not properly quoted\n",
                    qPrint(g_cmd),g_yyLineNr,qPrint(g_yyFileName),qPrint(g_string->stripWhiteSpace()));
      }
      warned=true;
    }
    else // normal character
    {
      result+=c;
    }
  }
  // recode the string
  *g_string=configStringRecode(result,g_encoding,"UTF-8");
  // update encoding
  checkEncoding();
  //printf("Processed string '%s'\n",qPrint(g_string));
}
References QCString::at(), checkEncoding(), config_warn(), configStringRecode(), g_cmd, g_encoding, g_string, g_yyFileName, g_yyLineNr, QCString::length(), QCString::mid(), qPrint(), stripComment(), and QCString::stripWhiteSpace().
readIncludeFile()
static void readIncludeFile (const QCString & incName) static
Definition at line 940 of file configimpl.l.
{
  if (g_includeStack.size()==MAX_INCLUDE_DEPTH) {
    config_term("maximum include depth (%d) reached, %s is not included. Aborting...\n",
        MAX_INCLUDE_DEPTH,qPrint(incName));
  }
  QCString inc = incName;
  substEnvVarsInString(inc);
  inc = inc.stripWhiteSpace();
  uint32_t incLen = inc.length();
  if (incLen>0 && inc.at(0)=='"' && inc.at(incLen-1)=='"') // strip quotes
  {
    inc=inc.mid(1,incLen-2);
  }
  FILE *f;
  if ((f=findFile(inc))) // see if the include file can be found
  {
    // For debugging
#if SHOW_INCLUDES
    for (size_t i=0;i<g_includeStack.size();i++) msg("  ");
    msg("@INCLUDE = %s: parsing...\n",qPrint(inc));
#endif
    // store the state of the old file
    ConfigFileState *fs=new ConfigFileState;
    fs->oldState=YY_CURRENT_BUFFER;
    fs->lineNr=g_yyLineNr;
    fs->fileName=g_yyFileName;
    fs->filePtr=f;
    // push the state on the stack
    g_includeStack.push_back(std::unique_ptr<ConfigFileState>(fs));
    // set the scanner to the include file
    yy_switch_to_buffer(yy_create_buffer(f, YY_BUF_SIZE));
    fs->newState=YY_CURRENT_BUFFER;
    g_yyFileName=inc;
  }
  else
  {
    config_term("@INCLUDE = %s: not found!\n",qPrint(inc));
  }
}
References QCString::at(), config_term(), ConfigFileState::fileName, ConfigFileState::filePtr, findFile(), g_includeStack, g_yyFileName, g_yyLineNr, QCString::length(), ConfigFileState::lineNr, MAX_INCLUDE_DEPTH, QCString::mid(), msg(), ConfigFileState::newState, ConfigFileState::oldState, qPrint(), QCString::stripWhiteSpace(), and substEnvVarsInString().
stripComment()
static QCString stripComment (const QCString & s) static
Definition at line 715 of file configimpl.l.
{
  // check if there is a comment at the end of the string
  bool insideQuote=false;
  int l = s.length();
  for (int i=0;i<l;i++)
  {
    char c = s.at(i);
    if (c=='\\') // skip over escaped characters
    {
      i++;
    }
    else if (c=='"') // toggle inside/outside quotation
    {
      insideQuote=!insideQuote;
    }
    else if (!insideQuote && c=='#') // found start of a comment
    {
      if (i<l-1 && s.at(i+1)=='#') // ## -> user comment
      {
        g_config->appendUserComment(s.mid(i)+"\n");
      }
      return s.left(i).stripWhiteSpace();
    }
  }
  return s;
}
References ConfigImpl::appendUserComment(), QCString::at(), g_config, QCString::left(), QCString::length(), QCString::mid(), and QCString::stripWhiteSpace().
Referenced by processList(), processStoreRepl(), and processString().
substEnvVarsInString()
static void substEnvVarsInString (QCString & s) static
Definition at line 1369 of file configimpl.l.
{
  if (str.isEmpty()) return;
  auto replace = [](const std::string &s, const reg::Ex &re) -> std::string
  {
    reg::Iterator it(s,re);
    reg::Iterator end;
    std::string result;
    size_t p = 0;
    for (; it!=end ; ++it)
    {
      const auto &match = *it;
      size_t i = match.position();
      size_t l = match.length();
      result+=s.substr(p,i-p);
      std::string matchContents = match[1].str();
      QCString env=Portable::getenv(matchContents.c_str()); // get content of $(..) match
      substEnvVarsInString(env); // recursively expand variables if needed.
      result+=env.str();
      p=i+l;
    }
    result+=s.substr(p);
    return result;
  };
  str = QCString(replace(replace(str.str(),reEnvVar),reEnvVarExt)).stripWhiteSpace();
}
References end(), Portable::getenv(), QCString::isEmpty(), reEnvVar, reEnvVarExt, QCString::str(), QCString::stripWhiteSpace(), and substEnvVarsInString().
Referenced by readIncludeFile(), ConfigEnum::substEnvVars(), ConfigString::substEnvVars(), ConfigInt::substEnvVars(), ConfigBool::substEnvVars(), substEnvVarsInString(), and substEnvVarsInStrList().
substEnvVarsInStrList()
static void substEnvVarsInStrList (StringVector & sl) static
Definition at line 1397 of file configimpl.l.
{
  StringVector results;
  for (const auto &s : sl)
  {
    QCString result = s.c_str();
    bool wasQuoted = ((result.at(0)=='"') && (result.at(result.length()-1)=='"'));
    if (wasQuoted)
    {
      result = result.mid(1,result.length()-2);
    }
    else
    {
      wasQuoted = (result.find(' ')!=-1) || (result.find('\t')!=-1) || (result.find('"')!=-1);
    }
    // here we strip the quote again
    substEnvVarsInString(result);
    //printf("Result %s was quoted=%d\n",qPrint(result),wasQuoted);
    if (!wasQuoted) /* as a result of the expansion, a single string
                       may have expanded into a list, which we'll
                       add to sl. If the original string already
                       contained multiple elements no further
                       splitting is done to allow quoted items with spaces! */
    {
      int l=result.length();
      int i,p=0;
      // skip spaces
      // search for a "word"
      for (i=0;i<l;i++)
      {
        char c=0;
        // skip until start of new word
        while (i<l && ((c=result.at(i))==' ' || c=='\t')) i++;
        p=i; // p marks the start index of the word
        // skip until end of a word
        while (i<l && ((c=result.at(i))!=' ' && c!='\t' && c!='"')) i++;
        if (i<l) // not at the end of the string
        {
          if (c=='"') // word within quotes
          {
            p=i+1;
            for (i++;i<l;i++)
            {
              c=result.at(i);
              if (c=='"') // end quote
              {
                results.push_back(result.mid(p,i-p).str());
                p=i+1;
                break;
              }
              else if (c=='\\') // skip escaped stuff
              {
                i++;
              }
            }
          }
          else if (c==' ' || c=='\t') // separator
          {
            if (i>p) results.push_back(result.mid(p,i-p).str());
            p=i+1;
          }
        }
      }
      if (p!=l) // add the leftover as a string
      {
        results.push_back(result.right(l-p).str());
      }
    }
    else // just goto the next element in the list
    {
      if (!result.isEmpty()) results.push_back(result.str());
    }
  }
  sl = results;
}
References QCString::at(), QCString::find(), QCString::isEmpty(), QCString::length(), QCString::mid(), QCString::right(), QCString::str(), and substEnvVarsInString().
Referenced by findFile(), and ConfigList::substEnvVars().
tryPath()
static FILE * tryPath (const QCString & path, const QCString & fileName) static
Definition at line 904 of file configimpl.l.
{
  QCString absName=(!path.isEmpty() ? path+"/"+fileName : fileName);
  FileInfo fi(absName.str());
  if (fi.exists() && fi.isFile())
  {
    FILE *f=Portable::fopen(absName,"r");
    if (!f) config_err("could not open file %s for reading\n",qPrint(absName));
    return f;
  }
  return 0;
}
References config_err(), FileInfo::exists(), Portable::fopen(), QCString::isEmpty(), FileInfo::isFile(), qPrint(), and QCString::str().
Referenced by findFile().
updateAttribute()
static void updateAttribute (DotAttributes & attr, QCString name, ConfigObsolete * value) static
Definition at line 2181 of file configimpl.l.
{
  attr.updateValue(name,*value->valueStringRef());
}
References DotAttributes::updateValue(), and ConfigObsolete::valueStringRef().
Referenced by Config::updateObsolete().
yylex()
int yylex (void)
Definition at line 1000 of file configimpl.l.
{
                                           g_config->appendUserComment(yytext);
                                           g_yyLineNr++;
                                         }
<Start>"#".*"\n"                         { /* normal comment */
                                           g_yyLineNr++;
                                         }
   /*-------------- TAG start ---------------*/
<Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"="   { g_cmd=yytext;
                                           g_cmd=g_cmd.left(g_cmd.length()-1).stripWhiteSpace();
                                           ConfigOption *option = g_config->get(g_cmd);
                                           if (option==0) // oops not known
{
                                             config_warn("ignoring unsupported tag '%s' at line %d, file %s\n",
                                                 qPrint(g_cmd),g_yyLineNr,qPrint(g_yyFileName));
                                             BEGIN(SkipInvalid);
                                           }
                                           else // known tag
{
                                             option->setUserComment(g_config->takeUserComment());
                                             option->setEncoding(g_encoding);
                                             switch(option->kind())
{
                                               case ConfigOption::O_Info:
                                                 // shouldn't get here!
                                                 BEGIN(SkipInvalid);
                                                 break;
                                               case ConfigOption::O_List:
                                                 g_list = dynamic_cast<ConfigList *>(option)->valueRef();
                                                 g_list->clear();
                                                 g_listStr="";
                                                 BEGIN(GetStrList);
                                                 break;
                                               case ConfigOption::O_Enum:
                                                 g_string = dynamic_cast<ConfigEnum *>(option)->valueRef();
                                                 g_string->resize(0);
                                                 BEGIN(GetString);
                                                 break;
                                               case ConfigOption::O_String:
                                                 g_string = dynamic_cast<ConfigString *>(option)->valueRef();
                                                 g_string->resize(0);
                                                 BEGIN(GetString);
                                                 break;
                                               case ConfigOption::O_Int:
                                                 g_string = dynamic_cast<ConfigInt *>(option)->valueStringRef();
                                                 g_string->resize(0);
                                                 BEGIN(GetString);
                                                 break;
                                               case ConfigOption::O_Bool:
                                                 g_string = dynamic_cast<ConfigBool *>(option)->valueStringRef();
                                                 g_string->resize(0);
                                                 BEGIN(GetString);
                                                 break;
                                               case ConfigOption::O_Obsolete:
                                                 if (g_configUpdate)
{
                                                   config_warn("Tag '%s' at line %d of file '%s' has become obsolete.\n"
                                                              "         This tag has been removed.\n", qPrint(g_cmd),g_yyLineNr,qPrint(g_yyFileName));
                                                 }
                                                 else
{
                                                   config_warn("Tag '%s' at line %d of file '%s' has become obsolete.\n"
                                                              "         To avoid this warning please remove this line from your configuration "
                                                              "file or upgrade it using \"doxygen -u\"\n", qPrint(g_cmd),g_yyLineNr,qPrint(g_yyFileName));
                                                 }
                                                 dynamic_cast<ConfigObsolete*>(option)->markAsPresent();
                                                 if (dynamic_cast<ConfigObsolete*>(option)->orgType()==ConfigOption::O_List)
{
                                                   g_list = dynamic_cast<ConfigObsolete*>(option)->valueListRef();
                                                   g_list->clear();
                                                   g_listStr="";
                                                   BEGIN(GetStrList);
                                                 }
                                                 else
{
                                                   g_string = dynamic_cast<ConfigObsolete*>(option)->valueStringRef();
                                                   g_string->resize(0);
                                                   BEGIN(GetString);
                                                 }
                                                 break;
                                               case ConfigOption::O_Disabled:
                                                 if (g_configUpdate)
{
                                                   config_warn("Tag '%s' at line %d of file '%s' belongs to an option that was not enabled at compile time.\n"
                                                              "         This tag has been removed.\n", qPrint(g_cmd),g_yyLineNr,qPrint(g_yyFileName));
                                                 }
                                                 else
{
                                                   config_warn("Tag '%s' at line %d of file '%s' belongs to an option that was not enabled at compile time.\n"
                                                              "         To avoid this warning please remove this line from your configuration "
                                                            "file or upgrade it using \"doxygen -u\", or recompile doxygen with this feature enabled.\n", qPrint(g_cmd),g_yyLineNr,qPrint(g_yyFileName));
                                                 }
                                                 BEGIN(SkipInvalid);
                                                 break;
                                             }
                                           }
                                        }
<Start>[a-z_A-Z][a-z_A-Z0-9]*[ \t]*"+=" { g_cmd=yytext;
                                          g_cmd=g_cmd.left(g_cmd.length()-2).stripWhiteSpace();
                                          ConfigOption *option = g_config->get(g_cmd);
                                          if (option==0) // oops not known
{
                                            config_warn("ignoring unsupported tag '%s' at line %d, file %s\n",
                                                qPrint(g_cmd),g_yyLineNr,qPrint(g_yyFileName));
                                            BEGIN(SkipInvalid);
                                          }
                                          else // known tag
{
                                            option->setUserComment(g_config->takeUserComment());
                                            switch(option->kind())
{
                                              case ConfigOption::O_Info:
                                                // shouldn't get here!
                                                BEGIN(SkipInvalid);
                                                break;
                                              case ConfigOption::O_List:
                                                g_list = dynamic_cast<ConfigList *>(option)->valueRef();
                                                g_listStr="";
                                                BEGIN(GetStrList);
                                                break;
                                              case ConfigOption::O_Enum:
                                              case ConfigOption::O_String:
                                              case ConfigOption::O_Int:
                                              case ConfigOption::O_Bool:
                                                config_warn("operator += not supported for '%s'. Ignoring line at line %d, file %s\n",
                                                    yytext,g_yyLineNr,qPrint(g_yyFileName));
                                                BEGIN(SkipInvalid);
                                                break;
                                               case ConfigOption::O_Obsolete:
                                                 config_warn("Tag '%s' at line %d of file %s has become obsolete.\n"
                                                            "To avoid this warning please update your configuration "
                                                            "file using \"doxygen -u\"\n", qPrint(g_cmd),g_yyLineNr,qPrint(g_yyFileName));
                                                 if (dynamic_cast<ConfigObsolete*>(option)->orgType()==ConfigOption::O_List)
{
                                                   g_list = dynamic_cast<ConfigObsolete*>(option)->valueListRef();
                                                   g_listStr="";
                                                   BEGIN(GetStrList);
                                                 }
                                                 else
{
                                                   BEGIN(SkipInvalid);
                                                 }
                                                 break;
                                               case ConfigOption::O_Disabled:
                                                 config_warn("Tag '%s' at line %d of file %s belongs to an option that was not enabled at compile time.\n"
                                                            "To avoid this warning please remove this line from your configuration "
                                                            "file, upgrade it using \"doxygen -u\", or recompile doxygen with this feature enabled.\n", qPrint(g_cmd),g_yyLineNr,qPrint(g_yyFileName));
                                                 BEGIN(SkipInvalid);
                                                 break;
                                             }
                                           }
                                        }
   /*-------------- INCLUDE* ---------------*/
<Start>"@INCLUDE_PATH"[ \t]*"="         { BEGIN(GetStrList); g_list=&g_includePathList; g_list->clear(); g_listStr=""; }
  /* include a g_config file */
<Start>"@INCLUDE"[ \t]*"="              { BEGIN(Include);}
<Start>"$("{REGEX_a}({REGEX_w}|[.-])*")" | // e.g. $(HOME)
<Start>"$("{REGEX_a}({REGEX_w}|[.-])*"("{REGEX_a}({REGEX_w}|[.-])*"))" { // e.g. $(PROGRAMFILES(X86))
                                          g_localStoreRepl = yytext;
                                          if (g_compareMode == Config::CompareMode::CompressedNoEnv) // the x_noenv
{
                                            BEGIN(StoreRepl);
                                          }
                                          else
{
                                            substEnvVarsInString(g_localStoreRepl);
                                            unput_string(g_localStoreRepl.data(),g_localStoreRepl.length());
                                          }
                                        }
<Start>"@"{REGEX_a}{REGEX_w}*"@"        {
                                          if (g_compareMode == Config::CompareMode::CompressedNoEnv) // the x_noenv
{
                                            g_localStoreRepl = yytext;
                                            BEGIN(StoreRepl);
                                          }
                                          else
{
                                            config_warn("ignoring unknown '%s' at line %d, file %s\n",
                                                        yytext,g_yyLineNr,qPrint(g_yyFileName));
                                          }
                                        }
<Include>([^ \"\t\r\n]+)|("\""[^\n\"]+"\"") {
                                          readIncludeFile(configStringRecode(yytext,g_encoding,"UTF-8"));
                                          BEGIN(Start);
                                        }
<<EOF>>                                 {
                                          //printf("End of include file\n");
                                          //printf("Include stack depth=%d\n",g_includeStack.count());
                                          if (g_includeStack.empty())
{
                                            //printf("Terminating scanner!\n");
                                            yyterminate();
                                          }
                                          else
{
                                            auto &fs=g_includeStack.back();
                                            fclose(fs->filePtr);
                                            YY_BUFFER_STATE oldBuf = YY_CURRENT_BUFFER;
                                            yy_switch_to_buffer( fs->oldState );
                                            yy_delete_buffer( oldBuf );
                                            g_yyLineNr=fs->lineNr;
                                            g_yyFileName=fs->fileName;
                                            g_includeStack.pop_back();
                                          }
                                        }
<Start>[a-z_A-Z0-9]+                    { config_warn("ignoring unknown tag '%s' at line %d, file %s\n",yytext,g_yyLineNr,qPrint(g_yyFileName)); }
   /*-------------- GetString ---------------*/
<StoreRepl>\n                           {
                                          g_localStoreRepl += yytext;
                                          processStoreRepl(g_localStoreRepl);
                                          g_config->appendStoreRepl(g_localStoreRepl + "\n");
                                          g_localStoreRepl.resize(0);
                                          g_yyLineNr++; // end of string
                                          BEGIN(Start);
                                        }
<StoreRepl>\\[ \r\t]*\n                 { g_yyLineNr++; // line continuation
                                          g_localStoreRepl += yytext;
                                        }
<StoreRepl>"\\"                         { // escape character
                                          g_localStoreRepl += yytext;
                                        }
<StoreRepl>[^\n\\]+                     { // string part without escape characters
                                          g_localStoreRepl += yytext;
                                        }
   /*-------------- GetString ---------------*/
<GetString>\n                           { processString();
                                          g_yyLineNr++; // end of string
                                          BEGIN(Start);
                                        }
<GetString>\\[ \r\t]*\n                 { g_yyLineNr++; // line continuation
                                          *g_string+=' ';
                                        }
<GetString>"\\"                         { // escape character
                                          *g_string+=yytext;
                                        }
<GetString>[^\n\\]+                     { // string part without escape characters
                                          *g_string+=yytext;
                                        }
   /*-------------- GetStrList --------------*/
<GetStrList>\n                          { processList();
                                          g_yyLineNr++; // end of list
                                          BEGIN(Start);
                                        }
<GetStrList>\\[ \r\t]*\n                { g_yyLineNr++; // line continuation
                                          g_listStr+=' ';
                                        }
<GetStrList>"\\"                        { // escape character
                                          g_listStr+=yytext;
                                        }
<GetStrList>[^\n\\]+                    { // string part without escape characters
                                          g_listStr+=yytext;
                                        }
   /*-------------- SkipInvalid --------------*/
<SkipInvalid>\n                         { g_yyLineNr++; // end of list
                                          BEGIN(Start);
                                        }
<SkipInvalid>\\[ \r\t]*\n               { g_yyLineNr++; // line continuation
                                        }
<SkipInvalid>"\\"                       { // escape character
                                        }
<SkipInvalid>[^\n\\]+                   { // string part without escape characters
                                        }
   /*-------------- fall through -------------*/
<*>\\[ \r\t]*\n                         { g_yyLineNr++; }
<*>[ \t\r]
<*>\n                                   { g_yyLineNr++ ; }
<*>.                                    { config_warn("ignoring unknown character '%c' at line %d, file %s\n",yytext[0],g_yyLineNr,qPrint(g_yyFileName)); }
%%
Referenced by convertCppComments().
yyread()
static int yyread (char * buf, int max_size) static
Definition at line 651 of file configimpl.l.
{
  // no file included
  if (g_includeStack.empty())
  {
    int c=0;
    if (g_inputString==0) return c;
    while( c < max_size && g_inputString[g_inputPosition] )
    {
      *buf = g_inputString[g_inputPosition++] ;
      c++; buf++;
    }
    return c;
  }
  else
  {
    //assert(g_includeStack.current()->newState==YY_CURRENT_BUFFER);
    return static_cast<int>(fread(buf,1,max_size,g_includeStack.back()->filePtr));
  }
}
References g_includeStack, g_inputPosition, and g_inputString.
Variable Documentation
error_str
const char* error_str = "error: " static
Definition at line 62 of file configimpl.l.
Referenced by config_err(), and config_term().
g_cmd
QCString g_cmd static
Definition at line 628 of file configimpl.l.
Referenced by processList(), and processString().
g_compareMode
Config::CompareMode g_compareMode = Config::CompareMode::Full static
Definition at line 637 of file configimpl.l.
Referenced by Config::parse().
g_config
ConfigImpl* g_config static
Definition at line 636 of file configimpl.l.
Referenced by checkEncoding(), Config::parse(), ConfigImpl::parseString(), and stripComment().
g_configUpdate
bool g_configUpdate = FALSE static
Definition at line 634 of file configimpl.l.
Referenced by ConfigImpl::parseString().
g_encoding
QCString g_encoding static
Definition at line 635 of file configimpl.l.
Referenced by checkEncoding(), ConfigImpl::parse(), processList(), processStoreRepl(), and processString().
g_includePathList
StringVector g_includePathList static
Definition at line 632 of file configimpl.l.
Referenced by findFile().
g_includeStack
std::vector< std::unique_ptr<ConfigFileState> > g_includeStack static
Definition at line 633 of file configimpl.l.
Referenced by ConfigImpl::parseString(), readIncludeFile(), and yyread().
g_inputPosition
int g_inputPosition static
Definition at line 625 of file configimpl.l.
Referenced by ConfigImpl::parseString(), and yyread().
g_inputString
const char* g_inputString static
Definition at line 624 of file configimpl.l.
Referenced by ConfigImpl::parseString(), and yyread().
g_list
StringVector* g_list =0 static
Definition at line 630 of file configimpl.l.
Referenced by processList().
g_listStr
QCString g_listStr static
Definition at line 631 of file configimpl.l.
Referenced by processList().
g_localStoreRepl
QCString g_localStoreRepl static
Definition at line 638 of file configimpl.l.
g_string
QCString* g_string =0 static
Definition at line 629 of file configimpl.l.
Referenced by processString().
g_yyFileName
QCString g_yyFileName static
Definition at line 627 of file configimpl.l.
Referenced by ConfigImpl::parseString(), processList(), processString(), and readIncludeFile().
g_yyLineNr
int g_yyLineNr static
Definition at line 626 of file configimpl.l.
Referenced by ConfigImpl::parseString(), processList(), processString(), and readIncludeFile().
reEnvVar
const reg::Ex reEnvVar(R"(\$\‍((\a[\w.-]*)\‍))") (R"(\$\‍((\a[\w.-]*)\‍))") static
Referenced by containsEnvVar(), and substEnvVarsInString().
reEnvVarCMake
const reg::Ex reEnvVarCMake(R"(@\a\w*@)") (R"(@\a\w*@)") static
Referenced by containsEnvVar().
reEnvVarExt
const reg::Ex reEnvVarExt(R"(\$\‍((\a[\w.-]*\‍(\a[\w.-]*\‍))\‍))") (R"(\$\‍((\a[\w.-]*\‍(\a[\w.-]*\‍))\‍))") static
Referenced by containsEnvVar(), and substEnvVarsInString().
warning_str
const char* warning_str = "warning: " static
Definition at line 61 of file configimpl.l.
Referenced by config_warn().