Doxygen: TypeSpecifier Class Reference
TypeSpecifier Class Reference
Wrapper class for a number of boolean properties.
#include <src/types.h>
Public Member Functions
TypeSpecifier ()
void reset ()
void merge (const TypeSpecifier &other)
std::string to_string () const
Friends
bool operator== (const TypeSpecifier &t1, const TypeSpecifier &t2)
bool operator!= (const TypeSpecifier &t1, const TypeSpecifier &t2)
Detailed Description
Wrapper class for a number of boolean properties.
The properties are packed together, and initialized to false.
Definition at line 491 of file types.h.
Constructor & Destructor Documentation
TypeSpecifier()
TypeSpecifier::TypeSpecifier () inline
Definition at line 494 of file types.h.
{ reset(); }
References reset().
Referenced by merge(), operator!=, and operator==.
Member Function Documentation
merge()
void TypeSpecifier::merge (const TypeSpecifier & other) inline
Definition at line 498 of file types.h.
    {
#define TSPEC(x) m_is##x = m_is##x || other.is##x();
      TYPE_SPECIFIERS
#undef TSPEC
    }
References TYPE_SPECIFIERS, and TypeSpecifier().
reset()
void TypeSpecifier::reset () inline
Definition at line 496 of file types.h.
{ std::memset(this, 0, sizeof(*this)); }
Referenced by TypeSpecifier().
to_string()
std::string TypeSpecifier::to_string () const inline
Definition at line 520 of file types.h.
    {
      std::string result="[";
      bool first=true;
#define TSPEC(x)                                                          \
      if (m_is##x) {                                                      \
        if (!first) result+=",";                                          \
        result+=#x; first=false;                                          \
      }
      TYPE_SPECIFIERS
#undef TSPEC
      result+="]";
      return result;
    }
References TYPE_SPECIFIERS.
Referenced by fmt::formatter< TypeSpecifier >::format(), and printNavTree().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const TypeSpecifier & t1, const TypeSpecifier & t2) friend
Definition at line 514 of file types.h.
    {
      return !(operator==(t1,t2));
    }
References operator==, and TypeSpecifier().
operator==
bool operator== (const TypeSpecifier & t1, const TypeSpecifier & t2) friend
Definition at line 505 of file types.h.
    {
      bool eq = true;
#define TSPEC(x) eq = eq && (t1.m_is##x == t2.m_is##x);
      TYPE_SPECIFIERS
#undef TSPEC
      return eq;
    }
References TYPE_SPECIFIERS, and TypeSpecifier().
Referenced by operator!=.
The documentation for this class was generated from the following file:
src/types.h