Doxygen: TranslatorIndonesian Class Reference
TranslatorIndonesian Class Reference
#include <src/translator_id.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool, bool full) override
QCString trMonth (int month, bool, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
Public Member Functions inherited from TranslatorAdapter_1_8_0
QCString updateNeededMessage () override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 27 of file translator_id.h.
Member Function Documentation
getLanguageString()
QCString TranslatorIndonesian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 65 of file translator_id.h.
    {
      return "0x421 Indonesian";
    }
idLanguage()
QCString TranslatorIndonesian::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 39 of file translator_id.h.
    { return "indonesian"; }
latexLanguageSupportCommand()
QCString TranslatorIndonesian::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 56 of file translator_id.h.
    {
      return "\\usepackage[bahasa]{babel}";
    }
trAll()
QCString TranslatorIndonesian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1365 of file translator_id.h.
    {
      return "Semua";
    }
trAttention()
QCString TranslatorIndonesian::trAttention () inline override virtual
Implements Translator.
Definition at line 945 of file translator_id.h.
    {
      return "Perhatian";
    }
trAuthor()
QCString TranslatorIndonesian::trAuthor (bool first_capital, bool) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1238 of file translator_id.h.
    {
      return createNoun(first_capital, false, "penulis", "");
    }
References Translator::createNoun().
trBug()
QCString TranslatorIndonesian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1109 of file translator_id.h.
    {
      return "Bug";
    }
trBugList()
QCString TranslatorIndonesian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1114 of file translator_id.h.
    {
      return "Daftar Bug";
    }
trCallerGraph()
QCString TranslatorIndonesian::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1484 of file translator_id.h.
    {
      return "Berikut ini bagan fungsi-pemanggil untuk fungsi ini:";
    }
trCallGraph()
QCString TranslatorIndonesian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1370 of file translator_id.h.
    {
      return "Berikut ini bagan fungsi-terpanggil untuk fungsi ini:";
    }
trCiteReferences()
QCString TranslatorIndonesian::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1798 of file translator_id.h.
    { return "Daftar Pustaka"; }
trClass()
QCString TranslatorIndonesian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1172 of file translator_id.h.
    {
      return createNoun(first_capital, singular, "kelas", "-kelas");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorIndonesian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 498 of file translator_id.h.
    {
      return "Diagram hierarki kelas untuk "+clName+":";
    }
trClassDocumentation()
QCString TranslatorIndonesian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 379 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentasi Struktur Data";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentasi Kelas";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorIndonesian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1072 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktur Data";
      }
      else
      {
        return "Daftar Kelas";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorIndonesian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 164 of file translator_id.h.
    { return "Hierarki Kelas"; }
trClassHierarchyDescription()
QCString TranslatorIndonesian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 223 of file translator_id.h.
    { return "Hierarki kelas ini diurutkan kurang-lebih"
        " berdasarkan abjad:";
    }
trCode()
QCString TranslatorIndonesian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 845 of file translator_id.h.
    {
      return "kode";
    }
trCollaborationDiagram()
QCString TranslatorIndonesian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 800 of file translator_id.h.
    {
      return "Diagram kolaborasi untuk "+clName+":";
    }
trCompoundIndex()
QCString TranslatorIndonesian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 352 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indeks Struktur Data";
      }
      else
      {
        return "Indeks Kelas";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorIndonesian::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1538 of file translator_id.h.
    { return "Indeks Tipe Data"; }
trCompoundList()
QCString TranslatorIndonesian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 168 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktur Data";
      }
      else
      {
        return "Daftar Kelas";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorIndonesian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 238 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Berikut ini daftar struktur data, dengan penjelasan singkat:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Berikut ini daftar kelas, dengan penjelasan singkat:";
      }
      else
      {
        return "Berikut ini daftar kelas, struct, union, dan interface, dengan penjelasan singkat:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorIndonesian::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1512 of file translator_id.h.
    { return "Berikut daftar tipe data, dengan penjelasan singkat:"; }
trCompoundListFortran()
QCString TranslatorIndonesian::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1504 of file translator_id.h.
    { return "Daftar Tipe Data"; }
trCompoundMembers()
QCString TranslatorIndonesian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 185 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Variabel Data";
      }
      else
      {
        return "Daftar Anggota Kelas";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorIndonesian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 256 of file translator_id.h.
    {
      QCString result="Berikut ini daftar seluruh ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="variabel anggota struct dan union";
      }
      else
      {
        result+="kelas";
      }
      if (!extractAll)
      {
        result+=" yang didokumentasikan";
      }
      result+=", dengan tautan ke ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentasi struct/union untuk setiap variabel:";
        }
        else
        {
          result+="dokumentasi kelas untuk setiap anggota:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struct/union yang memuatnya:";
        }
        else
        {
          result+="kelas yang memuatnya:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorIndonesian::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1516 of file translator_id.h.
    {
      QCString result="Berikut daftar semua anggota tipe data ";
      if (!extractAll)
      {
        result+="terdokumentasi ";
      }
      result+=" dengan tautan ke ";
      if (!extractAll)
      {
         result+="dokumentasi struktur data untuk setiap anggota:";
      }
      else
      {
         result+="tipe data yang memuatnya:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorIndonesian::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1508 of file translator_id.h.
    { return "Variabel Data"; }
trCompoundReference()
QCString TranslatorIndonesian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 573 of file translator_id.h.
    {
      QCString result="Referensi";
      switch(compType)
      {
        case ClassDef::Class:      result+=" Kelas "; break;
        case ClassDef::Struct:     result+=" Struct "; break;
        case ClassDef::Union:      result+=" Union "; break;
        case ClassDef::Interface:  result+=" Interface "; break;
        case ClassDef::Protocol:   result+=" Protokol "; break;
        case ClassDef::Category:   result+=" Kategori "; break;
        case ClassDef::Exception:  result+=" Eksepsi "; break;
        default: break;
      }
      if (isTemplate) result+=" Template ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorIndonesian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1579 of file translator_id.h.
    {
      QCString result="Referensi ";
      if (isTemplate) result+="Template ";
      switch(compType)
      {
        case ClassDef::Class:      result+="Modul "; break;
        case ClassDef::Struct:     result+="Tipe "; break;
        case ClassDef::Union:      result+="Union "; break;
        case ClassDef::Interface:  result+="Antarmuka "; break;
        case ClassDef::Protocol:   result+="Protokol "; break;
        case ClassDef::Category:   result+="Kategori "; break;
        case ClassDef::Exception:  result+="Eksepsi "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorIndonesian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 474 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktur Data";
      }
      else
      {
        return "Kelas";
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorIndonesian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 810 of file translator_id.h.
    {
      return "Dokumentasi Konstruktor & Destruktor";
    }
trCopyright()
QCString TranslatorIndonesian::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1802 of file translator_id.h.
    { return "Hak Cipta"; }
trDataTypes()
QCString TranslatorIndonesian::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1562 of file translator_id.h.
    { return "Tipe Data"; }
trDate()
QCString TranslatorIndonesian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 512 of file translator_id.h.
    { return "Tanggal"; }
trDateTime()
QCString TranslatorIndonesian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1755 of file translator_id.h.
    {
      static const char *days[]   = { "Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu" };
      static const char *months[] = { "Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorIndonesian::trDayOfWeek (int dayOfWeek, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1775 of file translator_id.h.
    {
      static const char *days_short[]   = { "Sen", "Sel", "Rab", "Kam", "Jum", "Sab", "Min" };
      static const char *days_full[]    = { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" };
      return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
    }
trDayPeriod()
QCString TranslatorIndonesian::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1787 of file translator_id.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorIndonesian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 777 of file translator_id.h.
    {
      return "Definisi pada baris @0 dalam file @1.";
    }
trDefinedIn()
QCString TranslatorIndonesian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 152 of file translator_id.h.
    { return "didefinisikan di"; }
trDefinedInSourceFile()
QCString TranslatorIndonesian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 781 of file translator_id.h.
    {
      return "Definisi dalam file @0.";
    }
trDefineDocumentation()
QCString TranslatorIndonesian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 444 of file translator_id.h.
    { return "Dokumentasi Makro Definisi"; }
trDefines()
QCString TranslatorIndonesian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 408 of file translator_id.h.
    { return "Makro Definisi"; }
trDefineValue()
QCString TranslatorIndonesian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1099 of file translator_id.h.
    {
      return "Nilai:";
    }
trDeprecated()
QCString TranslatorIndonesian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 790 of file translator_id.h.
    {
      return "Kadaluarsa";
    }
trDeprecatedList()
QCString TranslatorIndonesian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1293 of file translator_id.h.
    {
      return "Daftar Kadaluarsa";
    }
trDetailedDescription()
QCString TranslatorIndonesian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 81 of file translator_id.h.
    { return "Keterangan Lengkap"; }
trDetails()
QCString TranslatorIndonesian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 85 of file translator_id.h.
    { return "Detail"; }
trDir()
QCString TranslatorIndonesian::trDir (bool first_capital, bool) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1460 of file translator_id.h.
    {
      return createNoun(first_capital, false, "direktori", "");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorIndonesian::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1806 of file translator_id.h.
    { return QCString("Bagan dependensi directori untuk ")+name+":"; }
trDirDocumentation()
QCString TranslatorIndonesian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1442 of file translator_id.h.
    { return "Dokumentasi Direktori"; }
trDirectories()
QCString TranslatorIndonesian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1448 of file translator_id.h.
    { return "Daftar Direktori"; }
trDirIndex()
QCString TranslatorIndonesian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1436 of file translator_id.h.
    { return "Hierarki Direktori"; }
trDirReference()
QCString TranslatorIndonesian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1454 of file translator_id.h.
    { QCString result="Referensi Direktori "; result+=dirName; return result; }
trDirRelation()
QCString TranslatorIndonesian::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1694 of file translator_id.h.
    {
      return "Relasi "+QCString(name);
    }
trDocumentation()
QCString TranslatorIndonesian::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 334 of file translator_id.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentasi"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorIndonesian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 420 of file translator_id.h.
    { return "Enumerasi"; }
trEnumerationTypeDocumentation()
QCString TranslatorIndonesian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 456 of file translator_id.h.
    { return "Dokumentasi Tipe Enumerasi"; }
trEnumerationValueDocumentation()
QCString TranslatorIndonesian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1492 of file translator_id.h.
    { return "Dokumentasi Nilai Enumerasi"; }
trEnumerationValues()
QCString TranslatorIndonesian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 438 of file translator_id.h.
    { return "Nilai enumerasi"; }
trEnumName()
QCString TranslatorIndonesian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 144 of file translator_id.h.
    { return "nama enumerasi"; }
trEnumValue()
QCString TranslatorIndonesian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 148 of file translator_id.h.
    { return "nilai enumerasi"; }
trEventDocumentation()
QCString TranslatorIndonesian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1310 of file translator_id.h.
    {
      return "Dokumentasi Event";
    }
trEvents()
QCString TranslatorIndonesian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1305 of file translator_id.h.
    {
      return "Event";
    }
trExamples()
QCString TranslatorIndonesian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 215 of file translator_id.h.
    { return "Contoh"; }
trExamplesDescription()
QCString TranslatorIndonesian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 320 of file translator_id.h.
    { return "Berikut ini daftar semua contoh:"; }
trExceptions()
QCString TranslatorIndonesian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 528 of file translator_id.h.
    { return "Eksepsi"; }
trFile()
QCString TranslatorIndonesian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1181 of file translator_id.h.
    {
      return createNoun(first_capital, singular, "file", "-file");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorIndonesian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 398 of file translator_id.h.
    { return "Dokumentasi File"; }
trFileIn()
QCString TranslatorIndonesian::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1731 of file translator_id.h.
    {
      return "File dimuat dalam "+name;
    }
trFileIndex()
QCString TranslatorIndonesian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 367 of file translator_id.h.
    { return "Indeks File"; }
trFileList()
QCString TranslatorIndonesian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 181 of file translator_id.h.
    { return "Daftar File"; }
trFileListDescription()
QCString TranslatorIndonesian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 229 of file translator_id.h.
    {
      QCString result="Berikut ini daftar seluruh file";
      if (!extractAll) result+=" yang didokumentasikan";
      result += ", dengan penjelasan singkat:";
      return result;
    }
trFileMembers()
QCString TranslatorIndonesian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 198 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Daftar Definisi Global";
      }
      else
      {
        return "Daftar Anggota File";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorIndonesian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 298 of file translator_id.h.
    {
      QCString result="Berikut ini daftar ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="fungsi, variabel, makro definisi, enumerasi, dan tipe";
      }
      else
      {
        result+="file";
      }
      if (!extractAll) result+=" yang didokumentasikan";
      result+=", dengan tautan ke ";
      if (extractAll)
        result+="file yang memuatnya:";
      else
        result+="dokumentasinya:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorIndonesian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 595 of file translator_id.h.
    {
      QCString result="Referensi File ";
      result+=fileName;
      return result;
    }
trFriends()
QCString TranslatorIndonesian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 555 of file translator_id.h.
    { return "Friend"; }
trFunctionDocumentation()
QCString TranslatorIndonesian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 462 of file translator_id.h.
    { return "Dokumentasi Fungsi"; }
trFunctions()
QCString TranslatorIndonesian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 426 of file translator_id.h.
    { return "Fungsi"; }
trGeneratedAt()
QCString TranslatorIndonesian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 489 of file translator_id.h.
    {
      QCString result="Dibangkitkan pada tanggal "+date;
      if (!projName.isEmpty()) result+=" untuk "+projName;
      result+=" oleh";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorIndonesian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 136 of file translator_id.h.
    { QCString result="Dibangkitkan secara otomatis oleh Doxygen";
      if (!s.isEmpty()) result+=" untuk "+s;
      result+=" dari kode sumber.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorIndonesian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 532 of file translator_id.h.
    { return "Dibangkitkan oleh"; }
trGeneratedFromFiles()
QCString TranslatorIndonesian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 732 of file translator_id.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentasi untuk ";
      switch(compType)
      {
        case ClassDef::Class:      result+="kelas"; break;
        case ClassDef::Struct:     result+="struct"; break;
        case ClassDef::Union:      result+="union"; break;
        case ClassDef::Interface:  result+="interface"; break;
        case ClassDef::Protocol:   result+="protokol"; break;
        case ClassDef::Category:   result+="kategori"; break;
        case ClassDef::Exception:  result+="eksepsi"; break;
        default: break;
      }
      result+=" ini dibangkitkan dari file";
      result+=single ? "" : "-file";
      result+=" berikut:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorIndonesian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1645 of file translator_id.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentasi untuk ";
      switch(compType)
      {
        case ClassDef::Class:      result+="module"; break;
        case ClassDef::Struct:     result+="type"; break;
        case ClassDef::Union:      result+="union"; break;
        case ClassDef::Interface:  result+="interface"; break;
        case ClassDef::Protocol:   result+="protocol"; break;
        case ClassDef::Category:   result+="category"; break;
        case ClassDef::Exception:  result+="exception"; break;
        default: break;
      }
      result+=" ini dibangkitkan dari file";
      if (!single) result+="-file ";
          result+="berikut:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorIndonesian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1226 of file translator_id.h.
    {
      return createNoun(first_capital, singular, "definisi", "-definisi") +
                " global";
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorIndonesian::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1706 of file translator_id.h.
    {
      return "Namespace Global";
    }
trGotoDocumentation()
QCString TranslatorIndonesian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 820 of file translator_id.h.
    {
      return "Ke dokumentasi file ini.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorIndonesian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 853 of file translator_id.h.
    {
      return "Ke bagan grafis hierarki kelas";
    }
trGotoSourceCode()
QCString TranslatorIndonesian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 815 of file translator_id.h.
    {
      return "Ke kode sumber file ini.";
    }
trGotoTextualHierarchy()
QCString TranslatorIndonesian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 857 of file translator_id.h.
    {
      return "Ke bagan tekstual hierarki kelas";
    }
trGraphicalHierarchy()
QCString TranslatorIndonesian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 849 of file translator_id.h.
    {
      return "Hierarki Kelas Secara Grafis";
    }
trGroup()
QCString TranslatorIndonesian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_id.h.
    {
      return createNoun(first_capital, singular, "kelompok", "-kelompok");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorIndonesian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 346 of file translator_id.h.
    { return "Indeks Hierarki Kelas"; }
trImplementedFromList()
QCString TranslatorIndonesian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1261 of file translator_id.h.
    {
      return "Mengimplementasikan "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorIndonesian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1269 of file translator_id.h.
    {
      return "Diimplementasikan di "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorIndonesian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 949 of file translator_id.h.
    {
      return "Bagan ini menunjukkan file-file yang memuat"
        " atau menggunakan file ini baik secara langsung maupun"
        " tidak langsung:";
    }
trInclDepGraph()
QCString TranslatorIndonesian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 805 of file translator_id.h.
    {
      return "Bagan kebergantungan pemuatan untuk "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorIndonesian::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1740 of file translator_id.h.
    {
      return "Memuat file dalam "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorIndonesian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 130 of file translator_id.h.
    { return ", termasuk semua anggota yang diwariskan."; }
trInheritedByList()
QCString TranslatorIndonesian::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 666 of file translator_id.h.
    {
      return "Diwariskan ke "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList()
QCString TranslatorIndonesian::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 658 of file translator_id.h.
    {
      return "Mewarisi "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorIndonesian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 840 of file translator_id.h.
    {
      return "Nilai awal:";
    }
trInvariant()
QCString TranslatorIndonesian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 835 of file translator_id.h.
    {
      return "Invarian";
    }
trISOLang()
QCString TranslatorIndonesian::trISOLang () inline override virtual
Implements Translator.
Definition at line 61 of file translator_id.h.
    {
      return "id";
    }
trLegend()
QCString TranslatorIndonesian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1032 of file translator_id.h.
    {
      return "keterangan";
    }
trLegendDocs()
QCString TranslatorIndonesian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 972 of file translator_id.h.
    {
      return
        "Halaman ini berisi keterangan cara membaca bagan yang dibangkitkan "
        "oleh doxygen.<p>\n"
        "Contoh:\n"
        "\\code\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Apabila tag \\c MAX_DOT_GRAPH_HEIGHT di file konfigurasi "
        "diset ke 240 kode di atas akan menghasilkan bagan berikut:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Kotak-kotak pada bagan di atas mempunyai arti sebagai berikut:\n"
        "<ul>\n"
        "<li>%Kotak hitam merupakan struct atau kelas yang bersangkutan.\n"
        "<li>%Kotak berbingkai hitam adalah struct atau kelas yang mempunyai dokumentasi.\n"
        "<li>%Kotak dengan bingkai abu-abu adalah struct atau kelas tanpa dokumentasi.\n"
        "<li>%Kotak dengan bingkai merah merupakan struct atau kelas yang didokumentasikan tetapi"
        "tidak semua relasinya ditampilkan. %Sebuah bagan "
        "akan terpotong apabila lebih besar daripada ukuran yang ditentukan.\n"
        "</ul>\n"
        "Arti dari tanda-tanda panah adalah sebagai berikut:\n"
        "<ul>\n"
        "<li>%Panah biru tua menandakan pewarisan publik.\n"
        "<li>%Panah hijau tua untuk pewarisan diproteksi.\n"
        "<li>%Panah merah tua untuk pewarisan privat.\n"
        "<li>%Panah ungu putus-putus menandakan kelas tersebut berhubungan dengan kelas lain. "
        "Panah tersebut diberi judul sesuai dengan kelas atau struct tujuan.\n"
        "<li>%Panah kuning putus-putus menandakan hubungan antara sebuah template kelas dan "
        "instance dari template tersebut. Panah tersebut diberi judul sesuai dengan "
        "parameter template yang digunakan.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorIndonesian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 965 of file translator_id.h.
    {
      return "Keterangan Bagan";
    }
trListOfAllMembers()
QCString TranslatorIndonesian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 118 of file translator_id.h.
    { return "Daftar semua anggota"; }
trLoading()
QCString TranslatorIndonesian::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1700 of file translator_id.h.
    {
      return "Memuat...";
    }
trMainPage()
QCString TranslatorIndonesian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 764 of file translator_id.h.
    { return "Halaman Utama"; }
trMember()
QCString TranslatorIndonesian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1217 of file translator_id.h.
    {
      return createNoun(first_capital, singular, "anggota", "-anggota");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorIndonesian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 101 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentasi Variabel";
      }
      else
      {
        return "Dokumentasi Anggota: Data";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorIndonesian::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 93 of file translator_id.h.
    { return "Dokumentasi Anggota: Enumerasi"; }
trMemberFunctionDocumentation()
QCString TranslatorIndonesian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 97 of file translator_id.h.
    { return "Dokumentasi Anggota: Fungsi"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorIndonesian::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1500 of file translator_id.h.
    { return "Dokumentasi Fungsi/Subrutin Anggota"; }
trMemberList()
QCString TranslatorIndonesian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 122 of file translator_id.h.
    { return "Daftar anggota"; }
trMemberTypedefDocumentation()
QCString TranslatorIndonesian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 89 of file translator_id.h.
    { return "Dokumentasi Anggota: Tipe"; }
trModule()
QCString TranslatorIndonesian::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1638 of file translator_id.h.
    {
      return createNoun(first_capital, singular, "modul", "-modul");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorIndonesian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 373 of file translator_id.h.
    { return "Dokumentasi Modul"; }
trModuleIndex()
QCString TranslatorIndonesian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 340 of file translator_id.h.
    { return "Indeks Modul"; }
trModuleReference()
QCString TranslatorIndonesian::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1600 of file translator_id.h.
    {
      QCString result="Referensi Modul ";
      result+=namespaceName;
      return result;
    }
trModules()
QCString TranslatorIndonesian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 160 of file translator_id.h.
    { return "Modul"; }
trModulesDescription()
QCString TranslatorIndonesian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 328 of file translator_id.h.
    { return "Berikut ini daftar semua modul:"; }
trModulesIndex()
QCString TranslatorIndonesian::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1631 of file translator_id.h.
    { return "Indeks Modul"; }
trModulesList()
QCString TranslatorIndonesian::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1566 of file translator_id.h.
    { return "Modules List"; }
trModulesListDescription()
QCString TranslatorIndonesian::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1570 of file translator_id.h.
    {
      QCString result="Berikut daftar semua modul";
      if (!extractAll) result+=" terdokumentasi";
      result+=", dengan penjelasan singkat:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorIndonesian::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1612 of file translator_id.h.
    {
      QCString result="Berikut daftar semua anggota modul ";
      if (!extractAll) result+="terdokumentasi ";
      result+="dengan tautan ke ";
      if (extractAll)
      {
        result+="dokumentasi modul untuk setiap anggota:";
      }
      else
      {
        result+="modul yang memuatnya:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorIndonesian::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1608 of file translator_id.h.
    { return "Anggota Modul"; }
trMonth()
QCString TranslatorIndonesian::trMonth (int month, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1781 of file translator_id.h.
    {
      static const char *months_short[] = { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des" };
      static const char *months_full[]  = { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" };
      return full? months_full[month-1] : months_short[month-1];
    }
trMore()
QCString TranslatorIndonesian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 114 of file translator_id.h.
    { return "Selengkapnya..."; }
trNamespace()
QCString TranslatorIndonesian::trNamespace (bool first_capital, bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1190 of file translator_id.h.
    {
      return createNoun(first_capital, false, "namespace", "");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorIndonesian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 712 of file translator_id.h.
    { return "Dokumentasi Namespace"; }
trNamespaceIndex()
QCString TranslatorIndonesian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 706 of file translator_id.h.
    { return "Indeks Namespace"; }
trNamespaceList()
QCString TranslatorIndonesian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 540 of file translator_id.h.
    { return "Daftar Namespace"; }
trNamespaceListDescription()
QCString TranslatorIndonesian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 544 of file translator_id.h.
    {
      QCString result="Berikut ini daftar namespace";
      if (!extractAll) result+=" yang didokumentasikan";
      result+=", dengan keterangan singkat:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorIndonesian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 692 of file translator_id.h.
    {
      QCString result="Berikut ini daftar anggota namespace";
      if (!extractAll) result+=" yang didokumentasikan";
      result+=", dengan tautan ke ";
      if (extractAll)
        result+="dokumentasi namespace untuk setiap anggota:";
      else
        result+="namespace yang memuatnya:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorIndonesian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 688 of file translator_id.h.
    { return "Anggota Namespace"; }
trNamespaceReference()
QCString TranslatorIndonesian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 603 of file translator_id.h.
    {
      QCString result="Referensi Namespace ";
      result+=namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorIndonesian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 722 of file translator_id.h.
    { return "Daftar Namespace"; }
trNoMatches()
QCString TranslatorIndonesian::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1718 of file translator_id.h.
    {
      return "Tidak Ditemukan";
    }
trNote()
QCString TranslatorIndonesian::trNote () inline override virtual
Implements Translator.
Definition at line 870 of file translator_id.h.
    {
      return "Catatan";
    }
trOverloadText()
QCString TranslatorIndonesian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1472 of file translator_id.h.
    {
      return "Ini adalah fungsi anggota yang di-overload"
        " untuk kemudahan. Perbedaannya dengan fungsi di atas"
        " hanya pada parameter-parameter yang diterima.";
    }
trPackage()
QCString TranslatorIndonesian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1084 of file translator_id.h.
    {
      return "Paket "+name;
    }
trPackageAttribs()
QCString TranslatorIndonesian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1346 of file translator_id.h.
    {
      return "Daftar Atribut Paket";
    }
trPackageFunctions()
QCString TranslatorIndonesian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1328 of file translator_id.h.
    {
      return "Daftar Fungsi Paket";
    }
trPackageListDescription()
QCString TranslatorIndonesian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1089 of file translator_id.h.
    {
      return "Berikut ini daftar paket, dengan keterangan singkat (apabila tersedia):";
    }
trPackageMembers()
QCString TranslatorIndonesian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1332 of file translator_id.h.
    {
      return "Anggota-anggota Paket";
    }
trPackages()
QCString TranslatorIndonesian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1094 of file translator_id.h.
    {
      return "Daftar Paket";
    }
trPackageTypes()
QCString TranslatorIndonesian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1321 of file translator_id.h.
    {
      return "Jenis Paket";
    }
trPage()
QCString TranslatorIndonesian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1208 of file translator_id.h.
    {
      return createNoun(first_capital, singular, "halaman", "-halaman");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorIndonesian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 770 of file translator_id.h.
    { return "hal."; }
trPageIndex()
QCString TranslatorIndonesian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 861 of file translator_id.h.
    {
      return "Indeks Halaman";
    }
trParameters()
QCString TranslatorIndonesian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 524 of file translator_id.h.
    { return "Parameter"; }
trPostcondition()
QCString TranslatorIndonesian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 830 of file translator_id.h.
    {
      return "Kondisi Akhir";
    }
trPrecondition()
QCString TranslatorIndonesian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 825 of file translator_id.h.
    {
      return "Kondisi Awal";
    }
trPrivateAttribs()
QCString TranslatorIndonesian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 909 of file translator_id.h.
    {
      return "Atribut Privat";
    }
trPrivateMembers()
QCString TranslatorIndonesian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 624 of file translator_id.h.
    { return "Fungsi Anggota Privat"; }
trPrivateSlots()
QCString TranslatorIndonesian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 626 of file translator_id.h.
    { return "Slot Privat"; }
trPrivateTypes()
QCString TranslatorIndonesian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 905 of file translator_id.h.
    {
      return "Tipe Privat";
    }
trProperties()
QCString TranslatorIndonesian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1057 of file translator_id.h.
    {
      return "Daftar Property";
    }
trPropertyDocumentation()
QCString TranslatorIndonesian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1062 of file translator_id.h.
    {
      return "Dokumentasi Property";
    }
trProtectedAttribs()
QCString TranslatorIndonesian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 897 of file translator_id.h.
    {
      return "Atribut Diproteksi";
    }
trProtectedMembers()
QCString TranslatorIndonesian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 618 of file translator_id.h.
    { return "Fungsi Anggota Diproteksi"; }
trProtectedSlots()
QCString TranslatorIndonesian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 620 of file translator_id.h.
    { return "Slot Diproteksi"; }
trProtectedTypes()
QCString TranslatorIndonesian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 893 of file translator_id.h.
    {
      return "Tipe Diproteksi";
    }
trPublicAttribs()
QCString TranslatorIndonesian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 878 of file translator_id.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Variabel Data";
      }
      else
      {
        return "Atribut Publik";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorIndonesian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 610 of file translator_id.h.
    { return "Fungsi Anggota Publik"; }
trPublicSlots()
QCString TranslatorIndonesian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 612 of file translator_id.h.
    { return "Slot Publik"; }
trPublicTypes()
QCString TranslatorIndonesian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 874 of file translator_id.h.
    {
      return "Tipe Publik";
    }
trReferencedBy()
QCString TranslatorIndonesian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 937 of file translator_id.h.
    {
      return "Direferensikan oleh";
    }
trReferenceManual()
QCString TranslatorIndonesian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 402 of file translator_id.h.
    { return "Dokumen Referensi"; }
trReferences()
QCString TranslatorIndonesian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1249 of file translator_id.h.
    {
      return "Referensi";
    }
trReimplementedFromList()
QCString TranslatorIndonesian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 674 of file translator_id.h.
    {
      return "Di-reimplementasikan dari "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorIndonesian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 682 of file translator_id.h.
    {
      return "Diimplementasikan ulang di "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorIndonesian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 565 of file translator_id.h.
    { return "Dokumentasi Friend Dan Fungsi Terkait"; }
trRelatedFunctions()
QCString TranslatorIndonesian::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 73 of file translator_id.h.
    { return "Fungsi-fungsi Terkait"; }
trRelatedPages()
QCString TranslatorIndonesian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 211 of file translator_id.h.
    { return "Halaman Terkait"; }
trRelatedPagesDescription()
QCString TranslatorIndonesian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 324 of file translator_id.h.
    { return "Berikut ini daftar semua halaman dokumentasi yang terkait:"; }
trRelatedSubscript()
QCString TranslatorIndonesian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 77 of file translator_id.h.
    { return "(Perhatikan bahwa fungsi-fungsi tersebut bukan fungsi anggota.)"; }
trRemarks()
QCString TranslatorIndonesian::trRemarks () inline override virtual
Implements Translator.
Definition at line 941 of file translator_id.h.
    {
      return "Keterangan";
    }
trReturns()
QCString TranslatorIndonesian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 516 of file translator_id.h.
    { return "Mengembalikan"; }
trReturnValues()
QCString TranslatorIndonesian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 759 of file translator_id.h.
    { return "Nilai kembali"; }
trRTFansicp()
QCString TranslatorIndonesian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1148 of file translator_id.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorIndonesian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1157 of file translator_id.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorIndonesian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1163 of file translator_id.h.
    {
      return "Indeks";
    }
trRTFTableOfContents()
QCString TranslatorIndonesian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1281 of file translator_id.h.
    {
      return "Daftar Isi";
    }
trSearch()
QCString TranslatorIndonesian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 219 of file translator_id.h.
    { return "Cari"; }
trSearching()
QCString TranslatorIndonesian::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1712 of file translator_id.h.
    {
      return "Mencari...";
    }
trSearchMatches()
QCString TranslatorIndonesian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1413 of file translator_id.h.
    {
      return "Kecocokan:";
    }
trSearchResults()
QCString TranslatorIndonesian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1394 of file translator_id.h.
    {
      if (numDocuments==0)
      {
        return "Maaf, tidak ada dokumen yang cocok.";
      }
      else if (numDocuments==1)
      {
        return "Ditemukan <b>1</b> dokumen yang cocok.";
      }
      else
      {
        return "Ditemukan <b>$num</b> documents yang cocok. "
               "Menampilkan hasil terbaik lebih awal.";
      }
    }
trSearchResultsTitle()
QCString TranslatorIndonesian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1382 of file translator_id.h.
    {
      return "Hasil Pencarian";
    }
trSeeAlso()
QCString TranslatorIndonesian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 520 of file translator_id.h.
    { return "Lihat juga"; }
trSignals()
QCString TranslatorIndonesian::trSignals () inline override virtual
Implements Translator.
Definition at line 614 of file translator_id.h.
    { return "Signal"; }
trSince()
QCString TranslatorIndonesian::trSince () inline override virtual
Implements Translator.
Definition at line 955 of file translator_id.h.
    {
      return "Sejak";
    }
trSourceFile()
QCString TranslatorIndonesian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1424 of file translator_id.h.
    {
      return "Kode Sumber:" + filename;
    }
trStaticPackageAttribs()
QCString TranslatorIndonesian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1353 of file translator_id.h.
    {
      return "Daftar Atribut Statis Paket";
    }
trStaticPackageFunctions()
QCString TranslatorIndonesian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1339 of file translator_id.h.
    {
      return "Daftar Fungsi Statis Paket";
    }
trStaticPrivateAttribs()
QCString TranslatorIndonesian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 913 of file translator_id.h.
    {
      return "Atribut Privat Statis";
    }
trStaticPrivateMembers()
QCString TranslatorIndonesian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 628 of file translator_id.h.
    { return "Fungsi Anggota Privat Statis"; }
trStaticProtectedAttribs()
QCString TranslatorIndonesian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 901 of file translator_id.h.
    {
      return "Atribut Diproteksi Statis";
    }
trStaticProtectedMembers()
QCString TranslatorIndonesian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 622 of file translator_id.h.
    { return "Fungsi Anggota Diproteksi Statis"; }
trStaticPublicAttribs()
QCString TranslatorIndonesian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 889 of file translator_id.h.
    {
      return "Atribut Publik Statis";
    }
trStaticPublicMembers()
QCString TranslatorIndonesian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 616 of file translator_id.h.
    { return "Fungsi Anggota Publik Statis"; }
trSubprogram()
QCString TranslatorIndonesian::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1678 of file translator_id.h.
    {
      return createNoun(first_capital, singular, "subprogram", "-subprogram");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorIndonesian::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1556 of file translator_id.h.
    { return "Dokumentasi Fungsi/Subrutin"; }
trSubprograms()
QCString TranslatorIndonesian::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1550 of file translator_id.h.
    { return "Fungsi/Subrutin"; }
trTest()
QCString TranslatorIndonesian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1042 of file translator_id.h.
    {
      return "Tes";
    }
trTestList()
QCString TranslatorIndonesian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1047 of file translator_id.h.
    {
      return "Daftar Tes";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorIndonesian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 126 of file translator_id.h.
    { return "Berikut ini daftar lengkap anggota untuk"; }
trTodo()
QCString TranslatorIndonesian::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 923 of file translator_id.h.
    {
      return "Tugas";
    }
trTodoList()
QCString TranslatorIndonesian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 928 of file translator_id.h.
    {
      return "Daftar Tugas";
    }
trType()
QCString TranslatorIndonesian::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1670 of file translator_id.h.
    {
      return createNoun(first_capital, singular, "tipe", "-tipe");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorIndonesian::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1684 of file translator_id.h.
    {
      return "Batasan Tipe";
    }
trTypedefDocumentation()
QCString TranslatorIndonesian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 450 of file translator_id.h.
    { return "Dokumentasi Definisi Tipe"; }
trTypedefs()
QCString TranslatorIndonesian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 414 of file translator_id.h.
    { return "Definisi Tipe"; }
trTypeDocumentation()
QCString TranslatorIndonesian::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1544 of file translator_id.h.
    { return "Dokumentasi Tipe Data"; }
trVariableDocumentation()
QCString TranslatorIndonesian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 468 of file translator_id.h.
    { return "Dokumentasi Variabel"; }
trVariables()
QCString TranslatorIndonesian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 432 of file translator_id.h.
    { return "Variabel"; }
trVersion()
QCString TranslatorIndonesian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 508 of file translator_id.h.
    { return "Versi"; }
trWarning()
QCString TranslatorIndonesian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 504 of file translator_id.h.
    { return "Peringatan"; }
trWriteList()
QCString TranslatorIndonesian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 634 of file translator_id.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
        // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=", dan ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_id.h