Doxygen: Sitemap Class Reference
Sitemap Class Reference
#include <src/sitemap.h>
Classes
class Private
Public Member Functions
Sitemap ()
~Sitemap ()
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex, bool addToNavIndex, const Definition *def)
void addIndexItem (const Definition *context, const MemberDef *md, const QCString &sectionAnchor, const QCString &title)
void addIndexFile (const QCString &name)
void addImageFile (const QCString &name)
void addStyleSheetFile (const QCString &name)
Public Member Functions inherited from IndexIntf
Static Public Attributes
static const QCString sitemapFileName = "sitemap.xml"
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 26 of file sitemap.h.
Constructor & Destructor Documentation
Sitemap()
Sitemap::Sitemap ()
Definition at line 43 of file sitemap.cpp.
: p(std::make_unique<Private>()) {}
References p.
Referenced by ~Sitemap().
~Sitemap()
Sitemap::~Sitemap () default
References Sitemap().
Member Function Documentation
addContentsItem()
void Sitemap::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex, bool addToNavIndex, const Definition * def) inline virtual
Implements IndexIntf.
Definition at line 37 of file sitemap.h.
                                               {}
addImageFile()
void Sitemap::addImageFile (const QCString & name) inline virtual
Implements IndexIntf.
Definition at line 44 of file sitemap.h.
{}
addIndexFile()
void Sitemap::addIndexFile (const QCString & name) virtual
Implements IndexIntf.
Definition at line 72 of file sitemap.cpp.
{
  QCString fn = fileName;
  QCString sidemapUrl = Config_getString(SITEMAP_URL);
  addHtmlExtensionIfMissing(fn);
  p->doc << "  <url>\n";
  p->doc << "    <loc>" << convertToXML(sidemapUrl + fn) << "</loc>\n";
  p->doc << "  </url>\n";
}
References addHtmlExtensionIfMissing(), Config_getString, convertToXML(), and p.
addIndexItem()
void Sitemap::addIndexItem (const Definition * context, const MemberDef * md, const QCString & sectionAnchor, const QCString & title) inline virtual
Implements IndexIntf.
Definition at line 41 of file sitemap.h.
                                                                           {}
addStyleSheetFile()
void Sitemap::addStyleSheetFile (const QCString & name) inline virtual
Implements IndexIntf.
Definition at line 45 of file sitemap.h.
{}
decContentsDepth()
void Sitemap::decContentsDepth () inline virtual
Implements IndexIntf.
Definition at line 36 of file sitemap.h.
{}
finalize()
void Sitemap::finalize () virtual
Implements IndexIntf.
Definition at line 65 of file sitemap.cpp.
{
  p->doc << "</urlset>\n";
  p->doc.flush();
  p->docFile.close();
}
References p.
incContentsDepth()
void Sitemap::incContentsDepth () inline virtual
Implements IndexIntf.
Definition at line 35 of file sitemap.h.
{}
initialize()
void Sitemap::initialize () virtual
Implements IndexIntf.
Definition at line 46 of file sitemap.cpp.
{
  QCString fileName = Config_getString(HTML_OUTPUT) + "/" + sitemapFileName;
  p->docFile = Portable::openOutputStream(fileName);
  if (!p->docFile.is_open())
  {
    term("Could not open file %s for writing\n", qPrint(fileName));
  }
  p->doc.setStream(&p->docFile);
  p->doc << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
  p->doc << "<urlset\n";
  p->doc << "  xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"\n";
  p->doc << "  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n";
  p->doc << "  xsi:schemaLocation=\"http://www.sitemaps.org/schemas/sitemap/0.9\n";
  p->doc << "      http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd\">\n";
}
References Config_getString, Portable::openOutputStream(), p, qPrint(), sitemapFileName, and term.
Member Data Documentation
p
std::unique_ptr<Private> Sitemap::p private
Definition at line 51 of file sitemap.h.
Referenced by addIndexFile(), finalize(), initialize(), and Sitemap().
sitemapFileName
const QCString Sitemap::sitemapFileName = "sitemap.xml" inline static
Definition at line 47 of file sitemap.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/sitemap.h
src/sitemap.cpp