Doxygen: TranslatorCroatian Class Reference
TranslatorCroatian Class Reference
#include <src/translator_hr.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool, bool full) override
QCString trMonth (int month, bool, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 85 of file translator_hr.h.
Member Function Documentation
getLanguageString()
QCString TranslatorCroatian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 96 of file translator_hr.h.
    {
      return "0x41A Croatian";
    }
idLanguage()
QCString TranslatorCroatian::idLanguage () inline override virtual
Implements Translator.
Definition at line 90 of file translator_hr.h.
    { return "croatian"; }
latexLanguageSupportCommand()
QCString TranslatorCroatian::latexLanguageSupportCommand () inline override virtual
Implements Translator.
Definition at line 92 of file translator_hr.h.
    { return "\\usepackage[croatian]{babel}\n"; }
trAdditionalInheritedMembers()
QCString TranslatorCroatian::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1559 of file translator_hr.h.
    { return "Dodatni naslijeeni lanovi"; }
trAll()
QCString TranslatorCroatian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1074 of file translator_hr.h.
        {
                return "Sve";
        }
trAndMore()
QCString TranslatorCroatian::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1537 of file translator_hr.h.
    { return "i jo "+number+" ..."; }
trAttention()
QCString TranslatorCroatian::trAttention () inline override virtual
Implements Translator.
Definition at line 701 of file translator_hr.h.
    {
        return "Panja";
    }
trAuthor()
QCString TranslatorCroatian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 953 of file translator_hr.h.
    {
      return createNoun(first_capital, singular, "autor", "i");
    }
References Translator::createNoun().
trBug()
QCString TranslatorCroatian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 854 of file translator_hr.h.
    {
      return "Greka";
    }
trBugList()
QCString TranslatorCroatian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 859 of file translator_hr.h.
    {
      return "Popis greaka";
    }
trCallerGraph()
QCString TranslatorCroatian::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1199 of file translator_hr.h.
    {
      return "Ovo je graf funkcija koje pozivaju ovu funkciju:";
    }
trCallGraph()
QCString TranslatorCroatian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1079 of file translator_hr.h.
        {
                return "Ovo je dijagram poziva za ovu funkciju:";
        }
trCiteReferences()
QCString TranslatorCroatian::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1513 of file translator_hr.h.
    { return "Bibliografija"; }
trClass()
QCString TranslatorCroatian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 887 of file translator_hr.h.
    {
      return createNoun(first_capital, singular, "klas", "e", "a");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorCroatian::trClassDiagram (const QCString & clName) inline override virtual
Implements Translator.
Definition at line 300 of file translator_hr.h.
    {
      return QCString("Dijagram klasa za ")+clName;
    }
trClassDocumentation()
QCString TranslatorCroatian::trClassDocumentation () inline override virtual
Implements Translator.
Definition at line 249 of file translator_hr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacija struktura podataka";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentacija klasa";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorCroatian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 824 of file translator_hr.h.
    {
      return "Klase";
    }
trClassHierarchy()
QCString TranslatorCroatian::trClassHierarchy () inline override virtual
Implements Translator.
Definition at line 140 of file translator_hr.h.
    { return "Stablo klasa"; }
trClassHierarchyDescription()
QCString TranslatorCroatian::trClassHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 170 of file translator_hr.h.
    { return "Stablo naslijeivanja je sloeno "
             "priblino po abecedi:";
    }
trCode()
QCString TranslatorCroatian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 609 of file translator_hr.h.
    {
      return "kod";
    }
trCollaborationDiagram()
QCString TranslatorCroatian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 564 of file translator_hr.h.
    {
      return "Kolaboracijski dijagram za "+clName+ ":";
    }
trCompoundIndex()
QCString TranslatorCroatian::trCompoundIndex () inline override virtual
Implements Translator.
Definition at line 234 of file translator_hr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Kazalo struktura podataka";
      }
      else
      {
        return "Skupno kazalo ";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorCroatian::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1253 of file translator_hr.h.
    { return "Kazalo data tipova"; }
trCompoundList()
QCString TranslatorCroatian::trCompoundList () inline override virtual
Implements Translator.
Definition at line 142 of file translator_hr.h.
        {
                if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
                {
                        return "Sve strukture";
                }
                else
                {
                        return "Sve klase";
                }
        }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorCroatian::trCompoundListDescription () inline override virtual
Implements Translator.
Definition at line 181 of file translator_hr.h.
    { return "Popis svih klasa, unija i struktura "
                  "s kratkim opisom :";
    }
trCompoundListDescriptionFortran()
QCString TranslatorCroatian::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1226 of file translator_hr.h.
    { return "Tipovi podataka s kratkim opisom:"; }
trCompoundListFortran()
QCString TranslatorCroatian::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1218 of file translator_hr.h.
    { return "Lista tipova podataka"; }
trCompoundMembers()
QCString TranslatorCroatian::trCompoundMembers () inline override virtual
Implements Translator.
Definition at line 155 of file translator_hr.h.
        {
                if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
                        return "Svi lanovi struktura";
                else
                        return "Svi lanovi klasa";
        }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorCroatian::trCompoundMembersDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 185 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll)
                  result+="dokumentiranih ";
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
                  result+="lanova klasa s linkovima na ";
          else
                  result+="lanova struktura s linkovima na ";
      if (!extractAll)
          {
                  result+="dokumentaciju svakog lana:";
      }
          else
          {
                  if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
                          result+="dokumentaciju klase :";
                  else
                          result +="dokumentaciju strukture";
          }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorCroatian::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1230 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll)
      {
        result+="dokumentiranih ";
      }
      result+="polja";
      result+=" s linkovima na ";
      if (!extractAll)
      {
        result+="dokumentaciju struktura podataka za svako polje";
      }
      else
      {
        result+="strukture kojima pripadaju:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorCroatian::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1222 of file translator_hr.h.
    { return "Polja"; }
trCompoundReference()
QCString TranslatorCroatian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool) inline override virtual
Implements Translator.
Definition at line 348 of file translator_hr.h.
    {
      QCString result="Opis ";
      switch(compType)
      {
        case ClassDef::Class:  result+=" klase "; break;
        case ClassDef::Struct: result+=" strukture "; break;
        case ClassDef::Union:  result+=" unije "; break;
        case ClassDef::Interface:  result+=" suelja (interface) "; break;
        case ClassDef::Protocol:   result+=" protokola "; break;
        case ClassDef::Category:   result+=" kategorije "; break;
        case ClassDef::Exception:  result+=" iznimke (exception) "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorCroatian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1294 of file translator_hr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Modul"; break;
        case ClassDef::Struct:     result+=" Tip"; break;
        case ClassDef::Union:      result+=" Unija"; break;
        case ClassDef::Interface:  result+=" Suelje"; break;
        case ClassDef::Protocol:   result+=" Protokol"; break;
        case ClassDef::Category:   result+=" Kategorija"; break;
        case ClassDef::Exception:  result+=" Iznimka"; break;
        default: break;
      }
      if (isTemplate) result+=" Predloak";
      result+=" Referenca";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorCroatian::trCompounds () inline override virtual
Implements Translator.
Definition at line 291 of file translator_hr.h.
    { return "Strukture"; }
trConstructorDocumentation()
QCString TranslatorCroatian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 574 of file translator_hr.h.
    {
      return "Dokumentacija konstruktora i destruktora ";
    }
trCopyright()
QCString TranslatorCroatian::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1517 of file translator_hr.h.
    { return "Copyright"; }
trDataTypes()
QCString TranslatorCroatian::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1277 of file translator_hr.h.
    { return "Tipovi podataka"; }
trDate()
QCString TranslatorCroatian::trDate () inline override virtual
Implements Translator.
Definition at line 308 of file translator_hr.h.
    { return "Datum"; }
trDateTime()
QCString TranslatorCroatian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1467 of file translator_hr.h.
    {
      static const char *days[]   = { "Pon","Uto","Sri","et","Pet","Sub","Ned" };
      static const char *months[] = { "Sje","Velj","Ou","Tra","Svi","Lip","Srp","Kol","Ruj","Lis","Stu","Pro" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorCroatian::trDayOfWeek (int dayOfWeek, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1487 of file translator_hr.h.
    {
      static const char *days_short[]   = { "pon", "uto", "sri", "et", "pet", "sub", "ned" };
      static const char *days_full[]    = { "ponedjeljak", "utorak", "srijeda", "etvrtak", "petak", "subota", "nedjelja" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod()
QCString TranslatorCroatian::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1501 of file translator_hr.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorCroatian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 541 of file translator_hr.h.
    {
      return "Definirano u liniji @0 datoteke @1.";
    }
trDefinedIn()
QCString TranslatorCroatian::trDefinedIn () inline override virtual
Implements Translator.
Definition at line 136 of file translator_hr.h.
    { return "definirano u"; }
trDefinedInSourceFile()
QCString TranslatorCroatian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 545 of file translator_hr.h.
    {
      return "Definirano u datoteci @0.";
    }
trDefineDocumentation()
QCString TranslatorCroatian::trDefineDocumentation () inline override virtual
Implements Translator.
Definition at line 281 of file translator_hr.h.
    { return "Dokumentacija definicija"; }
trDefines()
QCString TranslatorCroatian::trDefines () inline override virtual
Implements Translator.
Definition at line 269 of file translator_hr.h.
    { return "Definicije"; }
trDefineValue()
QCString TranslatorCroatian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 844 of file translator_hr.h.
    {
      return "Vrijednost:";
    }
trDeprecated()
QCString TranslatorCroatian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 554 of file translator_hr.h.
    {
      return "Zastarjelo";
    }
trDeprecatedList()
QCString TranslatorCroatian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1005 of file translator_hr.h.
    {
      return "Popis zastarjelih metoda";
    }
trDetailedDescription()
QCString TranslatorCroatian::trDetailedDescription () inline override virtual
Implements Translator.
Definition at line 104 of file translator_hr.h.
    { return "Detaljno objanjenje"; }
trDetailLevel()
QCString TranslatorCroatian::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1529 of file translator_hr.h.
    { return "razina detalja"; }
trDetails()
QCString TranslatorCroatian::trDetails () inline override virtual
Implements Translator.
Definition at line 106 of file translator_hr.h.
    { return "Detalji"; }
trDir()
QCString TranslatorCroatian::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1176 of file translator_hr.h.
    {
      return createNoun(first_capital, singular, "direktorij", "i");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorCroatian::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1521 of file translator_hr.h.
    { return QCString("Direktoriji o kojima ovisi ")+name+":"; }
trDirDocumentation()
QCString TranslatorCroatian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1158 of file translator_hr.h.
    { return "Dokumentacija direktorija"; }
trDirectories()
QCString TranslatorCroatian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1164 of file translator_hr.h.
    { return "Direktoriji"; }
trDirIndex()
QCString TranslatorCroatian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1152 of file translator_hr.h.
    { return "Stablo direktorija"; }
trDirReference()
QCString TranslatorCroatian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1170 of file translator_hr.h.
    { QCString result= "Opis direktorija "; result += dirName; return result; }
trDirRelation()
QCString TranslatorCroatian::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1406 of file translator_hr.h.
    {
        return QCString("Relacije ") + QCString(name);
    }
trDocumentation()
QCString TranslatorCroatian::trDocumentation (const QCString & projName) inline override virtual
Implements Translator.
Definition at line 228 of file translator_hr.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentacija"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorCroatian::trEnumerations () inline override virtual
Implements Translator.
Definition at line 273 of file translator_hr.h.
    { return "Enumeracije"; }
trEnumerationTypeDocumentation()
QCString TranslatorCroatian::trEnumerationTypeDocumentation () inline override virtual
Implements Translator.
Definition at line 285 of file translator_hr.h.
    { return "Dokumentacija enumeracijskog tipa"; }
trEnumerationValueDocumentation()
QCString TranslatorCroatian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1207 of file translator_hr.h.
    { return "Dokumentacija enumeracija"; }
trEnumerationValues()
QCString TranslatorCroatian::trEnumerationValues () inline override virtual
Implements Translator.
Definition at line 279 of file translator_hr.h.
    { return "Vrijednosti enumeracija"; }
trEnumGeneratedFromFiles()
QCString TranslatorCroatian::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1541 of file translator_hr.h.
    { QCString result = "Dokumatacija za ovu enumeraciju je generirana iz ";
      if (!single) result += "datoteka:";
      else result += "datoteke:";
      return result;
    }
trEnumName()
QCString TranslatorCroatian::trEnumName () inline override virtual
Implements Translator.
Definition at line 132 of file translator_hr.h.
    { return "enum ime"; }
trEnumReference()
QCString TranslatorCroatian::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1549 of file translator_hr.h.
    { return "Opis enumeracije " + QCString(name); }
trEnumValue()
QCString TranslatorCroatian::trEnumValue () inline override virtual
Implements Translator.
Definition at line 134 of file translator_hr.h.
    { return "enum vrijednost"; }
trEventDocumentation()
QCString TranslatorCroatian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1021 of file translator_hr.h.
    {
      return "Dokumentacija dogaaja";
    }
trEvents()
QCString TranslatorCroatian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1016 of file translator_hr.h.
    {
      return "Dogaaji";
    }
trExamples()
QCString TranslatorCroatian::trExamples () inline override virtual
Implements Translator.
Definition at line 166 of file translator_hr.h.
    { return "Primjeri"; }
trExamplesDescription()
QCString TranslatorCroatian::trExamplesDescription () inline override virtual
Implements Translator.
Definition at line 221 of file translator_hr.h.
    { return "Popis primjera :"; }
trExceptions()
QCString TranslatorCroatian::trExceptions () inline override virtual
Implements Translator.
Definition at line 316 of file translator_hr.h.
    { return "Iznimke"; }
trFile()
QCString TranslatorCroatian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 896 of file translator_hr.h.
    {
      return createNoun(first_capital, singular, "datotek", "e", "a");
    }
References Translator::createNoun().
Referenced by trGeneratedFromFiles().
trFileDocumentation()
QCString TranslatorCroatian::trFileDocumentation () inline override virtual
Implements Translator.
Definition at line 264 of file translator_hr.h.
    { return "Dokumentacija datoteka"; }
trFileIn()
QCString TranslatorCroatian::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1443 of file translator_hr.h.
    {
      return "Datoteka u "+name;
    }
trFileIndex()
QCString TranslatorCroatian::trFileIndex () inline override virtual
Implements Translator.
Definition at line 245 of file translator_hr.h.
    { return "Kazalo datoteka"; }
trFileList()
QCString TranslatorCroatian::trFileList () inline override virtual
Implements Translator.
Definition at line 153 of file translator_hr.h.
    { return "Popis datoteka"; }
trFileListDescription()
QCString TranslatorCroatian::trFileListDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 174 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="datoteka, s kratkim opisom:";
      return result;
    }
trFileMembers()
QCString TranslatorCroatian::trFileMembers () inline override virtual
Implements Translator.
Definition at line 162 of file translator_hr.h.
    { return "lanovi klasa u datoteci"; }
trFileMembersDescription()
QCString TranslatorCroatian::trFileMembersDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 209 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll)
                  result+="dokumentiranih ";
      result+="lanova s linkovima na ";
      if (extractAll)
                  result+="dokumentaciju datoteke u kojima se nalaze:";
      else
                  result+="datoteke u kojima se nalaze:";
      return result;
    }
trFileReference()
QCString TranslatorCroatian::trFileReference (const QCString & fileName) inline override virtual
Implements Translator.
Definition at line 368 of file translator_hr.h.
    {
      QCString result="Opis datoteke ";
          result+=fileName;
          return result;
    }
trFriends()
QCString TranslatorCroatian::trFriends () inline override virtual
Implements Translator.
Definition at line 334 of file translator_hr.h.
    { return "Friend-ovi "; }
trFunctionDocumentation()
QCString TranslatorCroatian::trFunctionDocumentation () inline override virtual
Implements Translator.
Definition at line 287 of file translator_hr.h.
    { return "Dokumentacije funkcija"; }
trFunctions()
QCString TranslatorCroatian::trFunctions () inline override virtual
Implements Translator.
Definition at line 275 of file translator_hr.h.
    { return "Funkcije"; }
trGeneratedAt()
QCString TranslatorCroatian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
Implements Translator.
Definition at line 293 of file translator_hr.h.
    {
      QCString result="Napravljeno "+date;
      if (!projName.isEmpty()) result+=" projekt: "+projName;
      result+=" generator: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorCroatian::trGeneratedAutomatically (const QCString & s) inline override virtual
Implements Translator.
Definition at line 126 of file translator_hr.h.
    { QCString result="napravljeno automatski Doxygen-om";
      if (!s.isEmpty()) result+=" za "+s;
      result+=" iz programskog koda.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorCroatian::trGeneratedBy () inline override virtual
Implements Translator.
Definition at line 318 of file translator_hr.h.
    { return "Generirao"; }
trGeneratedFromFiles()
QCString TranslatorCroatian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 498 of file translator_hr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ";
      switch(compType)
      {
        case ClassDef::Class:      result+="klase"; break;
        case ClassDef::Struct:     result+="strukture"; break;
        case ClassDef::Union:      result+="unije"; break;
        case ClassDef::Interface:  result+="suelja (interface)"; break;
        case ClassDef::Protocol:   result+="protokola"; break;
        case ClassDef::Category:   result+="kategorije"; break;
        case ClassDef::Exception:  result+="iznimke (exception)"; break;
        default: break;
      }
      result+=" je napravljena iz " + trFile(FALSE, single) + ": ";
          return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, FALSE, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, trFile(), and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorCroatian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1360 of file translator_hr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ovog ";
      switch(compType)
      {
        case ClassDef::Class:      result+="modula"; break;
        case ClassDef::Struct:     result+="tipa"; break;
        case ClassDef::Union:      result+="unije"; break;
        case ClassDef::Interface:  result+="suelja"; break;
        case ClassDef::Protocol:   result+="protokola"; break;
        case ClassDef::Category:   result+="kategorije"; break;
        case ClassDef::Exception:  result+="iznimke"; break;
        default: break;
      }
      result+=" je napravljena iz :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorCroatian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 941 of file translator_hr.h.
    {
      return createNoun(first_capital, singular, "globaln", "e", "a") +
             createNoun(false, singular, " varijabl", "e", "a");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorCroatian::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1418 of file translator_hr.h.
    {
        return "Globalni namespace";
    }
trGotoDocumentation()
QCString TranslatorCroatian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 584 of file translator_hr.h.
    {
      return "Dokumenacija za ovu datoteku.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorCroatian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 617 of file translator_hr.h.
    {
      return "Grafiko stablo klasa";
    }
trGotoSourceCode()
QCString TranslatorCroatian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 579 of file translator_hr.h.
    {
      return "Izvorni kod";
    }
trGotoTextualHierarchy()
QCString TranslatorCroatian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 621 of file translator_hr.h.
    {
      return "Tekstualno stablo klasa";
    }
trGraphicalHierarchy()
QCString TranslatorCroatian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 613 of file translator_hr.h.
    {
      return "Grafiko stablo klasa";
    }
trGroup()
QCString TranslatorCroatian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 914 of file translator_hr.h.
    {
      return createNoun(first_capital, singular, "grup", "e", "a");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorCroatian::trHierarchicalIndex () inline override virtual
Implements Translator.
Definition at line 232 of file translator_hr.h.
    { return "Hijerarhijsko kazalo"; }
trImplementedFromList()
QCString TranslatorCroatian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 975 of file translator_hr.h.
    {
      return "Implementira "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorCroatian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 983 of file translator_hr.h.
    {
      return "Implementirano u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorCroatian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 705 of file translator_hr.h.
    {
      return "Ovaj graf pokazuje koje datoteke izravno "
             "ili neizravno ukljuuju ovu datoteku:";
    }
trInclDepGraph()
QCString TranslatorCroatian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 569 of file translator_hr.h.
    {
      return "Graf include meuovisnosti za "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorCroatian::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1452 of file translator_hr.h.
    {
      return "Ukljuuje datotake u "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorCroatian::trIncludingInheritedMembers () inline override virtual
Implements Translator.
Definition at line 124 of file translator_hr.h.
    { return ", ukljuujui naslijeene lanove."; }
trInheritedByList()
QCString TranslatorCroatian::trInheritedByList (int numEntries) inline override virtual
Implements Translator.
Definition at line 436 of file translator_hr.h.
    {
      return "Naslijeena u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorCroatian::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1553 of file translator_hr.h.
    { return QCString(members)+" naslijeeni od "+what; }
trInheritsList()
QCString TranslatorCroatian::trInheritsList (int numEntries) inline override virtual
Implements Translator.
Definition at line 430 of file translator_hr.h.
    {
      return "Naslijeuje od "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorCroatian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 604 of file translator_hr.h.
    {
      return "Poetna vrijednost:";
    }
trInvariant()
QCString TranslatorCroatian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 599 of file translator_hr.h.
    {
      return "Invarijanta";
    }
trISOLang()
QCString TranslatorCroatian::trISOLang () inline override virtual
Implements Translator.
Definition at line 94 of file translator_hr.h.
    { return "hr"; }
trLegend()
QCString TranslatorCroatian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 785 of file translator_hr.h.
    {
      return "legenda";
    }
trLegendDocs()
QCString TranslatorCroatian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 725 of file translator_hr.h.
    {
      return
        "Ova stranica objanjava kako interpretirati grafikone koje je generirao "
        "doxygen.<p>\n"
        "Na primjer:\n"
        "\\code\n"
        "/*! Nevidljiva klasa (nee stati na graf date visine) */\n"
        "class Invisible { };\n\n"
        "/*! Odrezana klasa, inheritance je skriven (klase se vidi na grafu, ali ne i sve bazne klase) */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Nedokumentirana klasa */\n"
        "class Undocumented { };\n\n"
        "/*! Klasa koja je naslijeena public  */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasa koje je naslijeena protected */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasa koje je naslijeena private */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasa koja se koristi agregacijom  */\n"
        "class Used { };\n\n"
        "/*! Super klasa koja naslijeuje/koristi ostale */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "To e rezultirati grafikonom:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Pravokutnici imaju slijedee znaenje:\n"
        "<ul>\n"
        "<li>Puni crni predstavlja klasu za koji je napravljen graf.\n"
        "<li>Pravokutnik s crnim rubom predstavlja dokumentiranu klasu.\n"
        "<li>Pravokutnik s sivim rubom predstavlja nedokumentiranu klasu.\n"
        "<li>Pravokutnik s crvenim rubom predstavlja dokumentiranu klasu\n"
        "Za koju nije prikazan graf naslijeivanja. Graf je odrezan "
        "ako ne stane unutar odreenih granica."
        "</ul>\n"
        "Strelice imaju slijedee znaenje:\n"
        "<ul>\n"
        "<li>Tamnoplava strelica oznaava public naslijeivanje.\n"
        "<li>Tamnozelena strelica oznaava protected naslijeivanje.\n"
        "<li>Tamnocrvena strelica oznaava private naslijeivanje.\n"
        "<li>Ljubiasta isprekidana strelica se koristi ako je klasa dio "
        "druge klase ili ako se klasa koristi u drugoj klasi. Natpis na "
        "strelici je ime varijable u drugoj klasi\n"
        "Strelica je oznaena imenom varijable.\n"
        "<li>uta isprekidana strelica oznaava relaciju izmeu template instance "
        "i template klase. Oznaena je imenom template parametra\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorCroatian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 720 of file translator_hr.h.
    {
      return "Legenda";
    }
trListOfAllMembers()
QCString TranslatorCroatian::trListOfAllMembers () inline override virtual
Implements Translator.
Definition at line 118 of file translator_hr.h.
    { return "Popis svih lanova"; }
trLoading()
QCString TranslatorCroatian::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1412 of file translator_hr.h.
    {
        return "Uitavam...";
    }
trMainPage()
QCString TranslatorCroatian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 528 of file translator_hr.h.
    { return "Glavna stranica"; }
trMember()
QCString TranslatorCroatian::trMember (bool , bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 932 of file translator_hr.h.
    {
      return createNoun(false, singular, "lan", "ovi");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorCroatian::trMemberDataDocumentation () inline override virtual
Implements Translator.
Definition at line 114 of file translator_hr.h.
    { return "Documentacija varijabli"; }
trMemberEnumerationDocumentation()
QCString TranslatorCroatian::trMemberEnumerationDocumentation () inline override virtual
Implements Translator.
Definition at line 110 of file translator_hr.h.
    { return "Dokumentacija enumeracijskih lanova"; }
trMemberFunctionDocumentation()
QCString TranslatorCroatian::trMemberFunctionDocumentation () inline override virtual
Implements Translator.
Definition at line 112 of file translator_hr.h.
    { return "Dokumentacija funkcija"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorCroatian::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1214 of file translator_hr.h.
    { return "Dokumentacija member funkcija/subrutina"; }
trMemberList()
QCString TranslatorCroatian::trMemberList () inline override virtual
Implements Translator.
Definition at line 120 of file translator_hr.h.
    { return "Popis lanova."; }
trMemberTypedefDocumentation()
QCString TranslatorCroatian::trMemberTypedefDocumentation () inline override virtual
Implements Translator.
Definition at line 108 of file translator_hr.h.
    { return "Dokumentacija typedef lanova"; }
trModule()
QCString TranslatorCroatian::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1353 of file translator_hr.h.
    {
      return createNoun(first_capital, singular, "modul", "i");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorCroatian::trModuleDocumentation () inline override virtual
Implements Translator.
Definition at line 247 of file translator_hr.h.
    { return "Dokumentacija modula"; }
trModuleIndex()
QCString TranslatorCroatian::trModuleIndex () inline override virtual
Implements Translator.
Definition at line 230 of file translator_hr.h.
    { return "Kazalo modula"; }
trModuleReference()
QCString TranslatorCroatian::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1315 of file translator_hr.h.
    {
      QCString result=namespaceName;
      result+=" - Sadraj modula";
      return result;
    }
trModules()
QCString TranslatorCroatian::trModules () inline override virtual
Implements Translator.
Definition at line 138 of file translator_hr.h.
    { return "Moduli"; }
trModulesDescription()
QCString TranslatorCroatian::trModulesDescription () inline override virtual
Implements Translator.
Definition at line 225 of file translator_hr.h.
    { return "Popis svih modula:"; }
trModulesIndex()
QCString TranslatorCroatian::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1346 of file translator_hr.h.
    { return "Kazalo modula"; }
trModulesList()
QCString TranslatorCroatian::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1281 of file translator_hr.h.
    { return "Popis modula"; }
trModulesListDescription()
QCString TranslatorCroatian::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1285 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="modula s kratkim opisom:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorCroatian::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1327 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="lanova modula s linkovima na ";
      if (extractAll)
      {
        result+="dokumentaciju modula za svaki lan:";
      }
      else
      {
        result+="modul kojem pripadaju:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorCroatian::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1323 of file translator_hr.h.
    { return "lanovi modula"; }
trMonth()
QCString TranslatorCroatian::trMonth (int month, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1494 of file translator_hr.h.
    {
      static const char *months_short[] = { "sij", "vlj", "ou", "tra", "svi", "lip", "srp", "kol", "ruj", "lis", "stu", "pro" };
      static const char *months_full[]  = { "sijeanj", "veljaa", "oujak", "travanj", "svibanj", "lipanj", "srpanj", "kolovoz", "rujan", "listopad", "studeni", "prosinac" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore()
QCString TranslatorCroatian::trMore () inline override virtual
Implements Translator.
Definition at line 116 of file translator_hr.h.
    { return "Opirnije..."; }
trNamespace()
QCString TranslatorCroatian::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 905 of file translator_hr.h.
    {
      return createNoun(first_capital, singular, "imeni", "ci", "k");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorCroatian::trNamespaceDocumentation () inline override virtual
Implements Translator.
Definition at line 474 of file translator_hr.h.
    { return "Dokumentacija namespace-a"; }
trNamespaceIndex()
QCString TranslatorCroatian::trNamespaceIndex () inline override virtual
Implements Translator.
Definition at line 470 of file translator_hr.h.
    { return "Kazalo imenika"; }
trNamespaceList()
QCString TranslatorCroatian::trNamespaceList () inline override virtual
Implements Translator.
Definition at line 325 of file translator_hr.h.
    { return "Popis imenika"; }
trNamespaceListDescription()
QCString TranslatorCroatian::trNamespaceListDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 327 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="imenika s kratkim opisom:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorCroatian::trNamespaceMemberDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 458 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="lanova imenika s linkovima na ";
      if (extractAll)
        result+="imeniku dokumentaciju svakog lana:";
      else
        result+="imenike kojima pripadaju:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorCroatian::trNamespaceMembers () inline override virtual
Implements Translator.
Definition at line 455 of file translator_hr.h.
    { return "lanovi imenika"; }
trNamespaceReference()
QCString TranslatorCroatian::trNamespaceReference (const QCString & namespaceName) inline override virtual
Implements Translator.
Definition at line 375 of file translator_hr.h.
    {
      QCString result ="Opis imenika ";
          result+=namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorCroatian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 486 of file translator_hr.h.
    {
      return "Imenici";
    }
trNoMatches()
QCString TranslatorCroatian::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1430 of file translator_hr.h.
    {
        return "Nema traenih podataka";
    }
trNote()
QCString TranslatorCroatian::trNote () inline override virtual
Implements Translator.
Definition at line 634 of file translator_hr.h.
    {
      return "Primjedba";
    }
trOverloadText()
QCString TranslatorCroatian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1187 of file translator_hr.h.
    {
       return "Ovo je preoptereena funkcija (overload). "
              "Razlikuje se od navedene metode "
              "samo po vrsti argumenata koje prihvaa.";
    }
trPackage()
QCString TranslatorCroatian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 829 of file translator_hr.h.
    {
      return "Paket "+name;
    }
trPackageAttribs()
QCString TranslatorCroatian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1056 of file translator_hr.h.
    {
      return "Atributi u paketu";
    }
trPackageFunctions()
QCString TranslatorCroatian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1038 of file translator_hr.h.
    {
      return "Funkcije u paketu";
    }
trPackageListDescription()
QCString TranslatorCroatian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 834 of file translator_hr.h.
    {
      return "Paketi s kratkim opisom (ukoliko postoji):";
    }
trPackageMembers()
QCString TranslatorCroatian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1042 of file translator_hr.h.
    {
      return "lanovi u paketu";
    }
trPackages()
QCString TranslatorCroatian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 839 of file translator_hr.h.
    {
      return "Paketi";
    }
trPackageTypes()
QCString TranslatorCroatian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1031 of file translator_hr.h.
    {
      return "Tipovi u paketu";
    }
trPage()
QCString TranslatorCroatian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 923 of file translator_hr.h.
    {
      return createNoun(first_capital, singular, "stranic", "e", "a");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorCroatian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 534 of file translator_hr.h.
    { return "str."; }
trPageIndex()
QCString TranslatorCroatian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 625 of file translator_hr.h.
    {
      return "Indeks stranice";
    }
trParameters()
QCString TranslatorCroatian::trParameters () inline override virtual
Implements Translator.
Definition at line 314 of file translator_hr.h.
    { return "Parametri"; }
trPostcondition()
QCString TranslatorCroatian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 594 of file translator_hr.h.
    {
      return "Postuvjeti";
    }
trPrecondition()
QCString TranslatorCroatian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 589 of file translator_hr.h.
    {
      return "Preduvjeti";
    }
trPrivateAttribs()
QCString TranslatorCroatian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 666 of file translator_hr.h.
    {
      return "Private atributi";
    }
trPrivateMembers()
QCString TranslatorCroatian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 399 of file translator_hr.h.
    { return "Privatni lanovi"; }
trPrivateSlots()
QCString TranslatorCroatian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 401 of file translator_hr.h.
    { return "Privatni slotovi"; }
trPrivateTypes()
QCString TranslatorCroatian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 662 of file translator_hr.h.
    {
      return "Private tipovi";
    }
trProperties()
QCString TranslatorCroatian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 809 of file translator_hr.h.
    {
      return "Svojstva (property)";
    }
trPropertyDocumentation()
QCString TranslatorCroatian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 814 of file translator_hr.h.
    {
      return "Dokumentacija svojstava";
    }
trProtectedAttribs()
QCString TranslatorCroatian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 654 of file translator_hr.h.
    {
      return "Protected atributi";
    }
trProtectedMembers()
QCString TranslatorCroatian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 393 of file translator_hr.h.
    { return "Protected lanovi"; }
trProtectedSlots()
QCString TranslatorCroatian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 395 of file translator_hr.h.
    { return "Protected slotovi"; }
trProtectedTypes()
QCString TranslatorCroatian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 650 of file translator_hr.h.
    {
      return "Protected tipovi";
    }
trPublicAttribs()
QCString TranslatorCroatian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 642 of file translator_hr.h.
    {
      return "Public atributi";
    }
trPublicMembers()
QCString TranslatorCroatian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 385 of file translator_hr.h.
    { return "Public lanovi"; }
trPublicSlots()
QCString TranslatorCroatian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 387 of file translator_hr.h.
    { return "Public slotovi"; }
trPublicTypes()
QCString TranslatorCroatian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 638 of file translator_hr.h.
    {
      return "Public tipovi";
    }
trReferencedBy()
QCString TranslatorCroatian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 693 of file translator_hr.h.
    {
      return "Referencirano od";
    }
trReferenceManual()
QCString TranslatorCroatian::trReferenceManual () inline override virtual
Implements Translator.
Definition at line 266 of file translator_hr.h.
    { return "Prirunik"; }
trReferences()
QCString TranslatorCroatian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 964 of file translator_hr.h.
    {
      return "Reference";
    }
trReimplementedFromList()
QCString TranslatorCroatian::trReimplementedFromList (int numEntries) inline override virtual
Implements Translator.
Definition at line 442 of file translator_hr.h.
    {
      return "Reimplementirano od  "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorCroatian::trReimplementedInList (int numEntries) inline override virtual
Implements Translator.
Definition at line 448 of file translator_hr.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "Reimplementacija u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorCroatian::trRelatedFunctionDocumentation () inline override virtual
Implements Translator.
Definition at line 341 of file translator_hr.h.
    { return "Dokumentacija povezanih funkcija"; }
trRelatedFunctions()
QCString TranslatorCroatian::trRelatedFunctions () inline override virtual
Implements Translator.
Definition at line 100 of file translator_hr.h.
    { return "Povezane funkcije"; }
trRelatedPages()
QCString TranslatorCroatian::trRelatedPages () inline override virtual
Implements Translator.
Definition at line 164 of file translator_hr.h.
    { return "Stranice povezane s ovom"; }
trRelatedPagesDescription()
QCString TranslatorCroatian::trRelatedPagesDescription () inline override virtual
Implements Translator.
Definition at line 223 of file translator_hr.h.
    { return "Popis povezanih stranica:"; }
trRelatedSubscript()
QCString TranslatorCroatian::trRelatedSubscript () inline override virtual
Implements Translator.
Definition at line 102 of file translator_hr.h.
    { return "(To nisu member funkcije.)"; }
trRemarks()
QCString TranslatorCroatian::trRemarks () inline override virtual
Implements Translator.
Definition at line 697 of file translator_hr.h.
    {
      return "Napomene";
    }
trReturns()
QCString TranslatorCroatian::trReturns () inline override virtual
Implements Translator.
Definition at line 310 of file translator_hr.h.
    { return "Povratne vrijednosti"; }
trReturnValues()
QCString TranslatorCroatian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 523 of file translator_hr.h.
    { return "Povratna vrijednost"; }
trRTFansicp()
QCString TranslatorCroatian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
Implements Translator.
Definition at line 868 of file translator_hr.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorCroatian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 873 of file translator_hr.h.
    {
      return "238";
    }
trRTFGeneralIndex()
QCString TranslatorCroatian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 878 of file translator_hr.h.
    {
      return "Sadraj";
    }
trRTFTableOfContents()
QCString TranslatorCroatian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 994 of file translator_hr.h.
    {
      return "Sadraj";
    }
trSearch()
QCString TranslatorCroatian::trSearch () inline override virtual
Implements Translator.
Definition at line 168 of file translator_hr.h.
    { return "Trai"; }
trSearching()
QCString TranslatorCroatian::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1424 of file translator_hr.h.
    {
        return "Traim...";
    }
trSearchMatches()
QCString TranslatorCroatian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1129 of file translator_hr.h.
        {
                return "Pronaeno:";
        }
trSearchResults()
QCString TranslatorCroatian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1103 of file translator_hr.h.
        {
                if (numDocuments==0)
                {
                        return "Nema dokumenta koji odgovaraju vaem upitu";
                }
                else if (numDocuments==1)
                {
                        return "Naen <b>1</b> dokument koji odgovara vaem upitu.";
                }
                else if (numDocuments<5)
                {
                        // Croatian (AFAIK all Slavic languages except Macedonian and Bulgarian)
            // have different plural form for 2,3,4.
                        return "Naena <b>$num</b> dokumenta koji odgovaraju vaem upitu."
                                "Najbolji su prikazani prvi.";
                }
                else
                {
                        return "Naeno <b>$num</b> dokumenata koji odgovaraju vaem upitu."
                                "Najbolji su prikazani prvi.";
                }
        }
trSearchResultsTitle()
QCString TranslatorCroatian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1091 of file translator_hr.h.
        {
                return "Rezultati pretrage";
        }
trSeeAlso()
QCString TranslatorCroatian::trSeeAlso () inline override virtual
Implements Translator.
Definition at line 312 of file translator_hr.h.
    { return "Vidi takoer"; }
trSignals()
QCString TranslatorCroatian::trSignals () inline override virtual
Implements Translator.
Definition at line 389 of file translator_hr.h.
    { return "Signali"; }
trSince()
QCString TranslatorCroatian::trSince () inline override virtual
Implements Translator.
Definition at line 710 of file translator_hr.h.
    {
      return "Od";
    }
trSourceFile()
QCString TranslatorCroatian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1140 of file translator_hr.h.
    {
      return "Izvorni kod datoteke " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorCroatian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1063 of file translator_hr.h.
    {
      return "Statiki atributi u paketu";
    }
trStaticPackageFunctions()
QCString TranslatorCroatian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1049 of file translator_hr.h.
    {
      return "Statike funkcije u paketu";
    }
trStaticPrivateAttribs()
QCString TranslatorCroatian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 670 of file translator_hr.h.
    {
      return "Static private atributi";
    }
trStaticPrivateMembers()
QCString TranslatorCroatian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 403 of file translator_hr.h.
    { return "Statini privatni lanovi"; }
trStaticProtectedAttribs()
QCString TranslatorCroatian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 658 of file translator_hr.h.
    {
      return "Static protected atributi";
    }
trStaticProtectedMembers()
QCString TranslatorCroatian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 397 of file translator_hr.h.
    { return "Static protected lanovi"; }
trStaticPublicAttribs()
QCString TranslatorCroatian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 646 of file translator_hr.h.
    {
      return "Static public atributi";
    }
trStaticPublicMembers()
QCString TranslatorCroatian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 391 of file translator_hr.h.
    { return "Static public lanovi"; }
trSubprogram()
QCString TranslatorCroatian::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1391 of file translator_hr.h.
    {
      return createNoun(first_capital, singular, "subprogram", "i");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorCroatian::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1271 of file translator_hr.h.
    { return "Documentacija funkcija/subrutina"; }
trSubprograms()
QCString TranslatorCroatian::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1265 of file translator_hr.h.
    { return "Funkcije/Subrutine"; }
trTemplateParameters()
QCString TranslatorCroatian::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1533 of file translator_hr.h.
    { return "Parametri predloka"; }
trTest()
QCString TranslatorCroatian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 794 of file translator_hr.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorCroatian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 799 of file translator_hr.h.
    {
      return "Test lista";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorCroatian::trThisIsTheListOfAllMembers () inline override virtual
Implements Translator.
Definition at line 122 of file translator_hr.h.
    { return "Ovo je popis svih lanova"; }
trTodo()
QCString TranslatorCroatian::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 679 of file translator_hr.h.
    {
      return "Za uraditi";
    }
trTodoList()
QCString TranslatorCroatian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 684 of file translator_hr.h.
    {
      return "Ostalo za uraditi";
    }
trType()
QCString TranslatorCroatian::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1383 of file translator_hr.h.
    {
      return createNoun(first_capital, singular, "tip", "ovi");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorCroatian::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1397 of file translator_hr.h.
    {
      return "Ogranienja tipova (Type Constraints)";
    }
trTypedefDocumentation()
QCString TranslatorCroatian::trTypedefDocumentation () inline override virtual
Implements Translator.
Definition at line 283 of file translator_hr.h.
    { return "Dokumentacija typedef-a"; }
trTypedefs()
QCString TranslatorCroatian::trTypedefs () inline override virtual
Implements Translator.
Definition at line 271 of file translator_hr.h.
    { return "Typedef-ovi"; }
trTypeDocumentation()
QCString TranslatorCroatian::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1259 of file translator_hr.h.
    { return "Dokumentacija tipova podataka"; }
trVariableDocumentation()
QCString TranslatorCroatian::trVariableDocumentation () inline override virtual
Implements Translator.
Definition at line 289 of file translator_hr.h.
    { return "Dokumentacija varijable"; }
trVariables()
QCString TranslatorCroatian::trVariables () inline override virtual
Implements Translator.
Definition at line 277 of file translator_hr.h.
    { return "Varijable"; }
trVersion()
QCString TranslatorCroatian::trVersion () inline override virtual
Implements Translator.
Definition at line 306 of file translator_hr.h.
    { return "Verzija"; }
trWarning()
QCString TranslatorCroatian::trWarning () inline override virtual
Implements Translator.
Definition at line 304 of file translator_hr.h.
    { return "Upozorenje"; }
trWriteList()
QCString TranslatorCroatian::trWriteList (int numEntries) inline override virtual
Implements Translator.
Definition at line 407 of file translator_hr.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+="";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_hr.h