Doxygen: DotDirDeps Class Reference
DotDirDeps Class Reference
Representation of an directory dependency graph.
#include <src/dotdirdeps.h>
Public Member Functions
DotDirDeps (const DirDef *dir)
~DotDirDeps () override
bool isTrivial () const
QCString writeGraph (TextStream &out, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1, bool linkRelations=TRUE)
Public Member Functions inherited from DotGraph
DotGraph ()
virtual ~DotGraph ()=default
Protected Member Functions
QCString getBaseName () const override
QCString getMapLabel () const override
void computeTheGraph () override
QCString getImgAltText () const override
Protected Member Functions inherited from DotGraph
int getNextNodeNumber ()
returns the node number.
int getNextEdgeNumber ()
returns the edge number.
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
virtual QCString absMapName () const
QCString absBaseName () const
QCString absDotName () const
QCString imgName () const
QCString absImgName () const
QCString relImgName () const
Private Attributes
const DirDef * m_dir = nullptr
bool m_linkRelations = false
Additional Inherited Members
Static Protected Member Functions inherited from DotGraph
static void writeGraphHeader (TextStream &t, const QCString &title=QCString())
static void writeGraphFooter (TextStream &t)
static void computeGraph (DotNode *root, GraphType gt, GraphOutputFormat format, const QCString &rank, bool renderParents, bool backArrows, const QCString &title, QCString &graphStr)
Protected Attributes inherited from DotGraph
GraphOutputFormat m_graphFormat = GraphOutputFormat::BITMAP
EmbeddedOutputFormat m_textFormat = EmbeddedOutputFormat::Html
Dir m_dir
QCString m_fileName
QCString m_relPath
bool m_generateImageMap = false
int m_graphId = 0
QCString m_absPath
QCString m_baseName
QCString m_theGraph
bool m_regenerate = false
bool m_doNotAddImageToIndex = false
bool m_noDivTag = false
bool m_zoomable = true
bool m_urlOnly = false
Detailed Description
Representation of an directory dependency graph.
Definition at line 25 of file dotdirdeps.h.
Constructor & Destructor Documentation
DotDirDeps()
DotDirDeps::DotDirDeps (const DirDef * dir)
Definition at line 403 of file dotdirdeps.cpp.
                                        : m_dir(dir)
{
}
References m_dir.
~DotDirDeps()
DotDirDeps::~DotDirDeps () override
Definition at line 407 of file dotdirdeps.cpp.
{
}
Member Function Documentation
computeTheGraph()
void DotDirDeps::computeTheGraph () override protected virtual
Implements DotGraph.
Definition at line 417 of file dotdirdeps.cpp.
{
  // compute md5 checksum of the graph were are about to generate
  TextStream md5stream;
  writeGraphHeader(md5stream, m_dir->displayName());
  md5stream << "  compound=true\n";
  writeDotDirDepGraph(md5stream,m_dir,m_linkRelations);
  writeGraphFooter(md5stream);
  m_theGraph = md5stream.str();
}
References m_dir, m_linkRelations, DotGraph::m_theGraph, TextStream::str(), writeDotDirDepGraph(), DotGraph::writeGraphFooter(), and DotGraph::writeGraphHeader().
getBaseName()
QCString DotDirDeps::getBaseName () const override protected virtual
Implements DotGraph.
Definition at line 411 of file dotdirdeps.cpp.
{
  return m_dir->getOutputFileBase()+"_dep";
}
References m_dir.
getImgAltText()
QCString DotDirDeps::getImgAltText () const override protected virtual
Reimplemented from DotGraph.
Definition at line 433 of file dotdirdeps.cpp.
{
  return convertToXML(m_dir->displayName());
}
References convertToXML(), and m_dir.
getMapLabel()
QCString DotDirDeps::getMapLabel () const override protected virtual
Implements DotGraph.
Definition at line 428 of file dotdirdeps.cpp.
{
  return escapeCharsInString(m_baseName,FALSE);
}
References escapeCharsInString(), FALSE, and DotGraph::m_baseName.
isTrivial()
bool DotDirDeps::isTrivial () const
Definition at line 447 of file dotdirdeps.cpp.
{
  return m_dir->depGraphIsTrivial();
}
References m_dir.
Referenced by DirDefImpl::writeDirectoryGraph().
writeGraph()
QCString DotDirDeps::writeGraph (TextStream & out, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1, bool linkRelations = TRUE)
Definition at line 438 of file dotdirdeps.cpp.
{
  m_linkRelations = linkRelations;
  m_urlOnly = TRUE;
  return DotGraph::writeGraph(out, graphFormat, textFormat, path, fileName, relPath, generateImageMap, graphId);
}
References m_linkRelations, DotGraph::m_urlOnly, TRUE, and DotGraph::writeGraph().
Referenced by DocbookGenerator::endDirDepGraph(), HtmlGenerator::endDirDepGraph(), LatexGenerator::endDirDepGraph(), and RTFGenerator::endDirDepGraph().
Member Data Documentation
m_dir
const DirDef* DotDirDeps::m_dir = nullptr private
Definition at line 50 of file dotdirdeps.h.
Referenced by computeTheGraph(), DotDirDeps(), getBaseName(), getImgAltText(), and isTrivial().
m_linkRelations
bool DotDirDeps::m_linkRelations = false private
Definition at line 52 of file dotdirdeps.h.
Referenced by computeTheGraph(), and writeGraph().
The documentation for this class was generated from the following files:
src/dotdirdeps.h
src/dotdirdeps.cpp