Doxygen: TextGeneratorIntf Class Reference
TextGeneratorIntf Class Reference abstract
Abstract interface for a hyperlinked text fragment.
#include <util.h>
Public Member Functions
virtual ~TextGeneratorIntf ()=default
virtual void writeString (const QCString &, bool) const =0
virtual void writeBreak (int indent) const =0
virtual void writeLink (const QCString &extRef, const QCString &file, const QCString &anchor, const QCString &text) const =0
Detailed Description
Abstract interface for a hyperlinked text fragment.
Definition at line 61 of file util.h.
Constructor & Destructor Documentation
~TextGeneratorIntf()
virtual TextGeneratorIntf::~TextGeneratorIntf () virtual default
Member Function Documentation
writeBreak()
virtual void TextGeneratorIntf::writeBreak (int indent) const pure virtual
Implemented in TextGeneratorHtml, TextGeneratorLatex, TextGeneratorOLImpl, TextGeneratorSqlite3Impl, and TextGeneratorXMLImpl.
Referenced by if().
writeLink()
virtual void TextGeneratorIntf::writeLink (const QCString & extRef, const QCString & file, const QCString & anchor, const QCString & text) const pure virtual
Implemented in TextGeneratorSqlite3Impl, TextGeneratorOLImpl, TextGeneratorXMLImpl, TextGeneratorHtml, and TextGeneratorLatex.
Referenced by if().
writeString()
virtual void TextGeneratorIntf::writeString (const QCString & , bool) const pure virtual
Implemented in TextGeneratorSqlite3Impl, TextGeneratorHtml, TextGeneratorLatex, TextGeneratorOLImpl, and TextGeneratorXMLImpl.
Referenced by if(), and linkifyText().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/util.h