Doxygen: TranslatorUkrainian Class Reference
TranslatorUkrainian Class Reference
#include <src/translator_ua.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation () override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool, bool full) override
QCString trMonth (int month, bool, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from Translator
virtual ~Translator ()=default
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 22 of file translator_ua.h.
Member Function Documentation
getLanguageString()
QCString TranslatorUkrainian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 38 of file translator_ua.h.
    {
      return "0x422 Ukrainian";
    }
idLanguage()
QCString TranslatorUkrainian::idLanguage () inline override virtual
Used for identification of the language.
Implements Translator.
Definition at line 26 of file translator_ua.h.
    { return "ukrainian"; }
latexLanguageSupportCommand()
QCString TranslatorUkrainian::latexLanguageSupportCommand () inline override virtual
Implements Translator.
Definition at line 30 of file translator_ua.h.
    {
      return "\\usepackage[T2A]{fontenc}\n\\usepackage[ukrainian]{babel}\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorUkrainian::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1864 of file translator_ua.h.
    { return "Додаткові успадковані елементи"; }
trAll()
QCString TranslatorUkrainian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1356 of file translator_ua.h.
    {
      return "Всі";
    }
trAndMore()
QCString TranslatorUkrainian::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1842 of file translator_ua.h.
    { return "і ще  "+number+"..."; }
trAttention()
QCString TranslatorUkrainian::trAttention () inline override virtual
Implements Translator.
Definition at line 942 of file translator_ua.h.
    {
      return "Увага";
    }
trAuthor()
QCString TranslatorUkrainian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1222 of file translator_ua.h.
    {
      QCString result((first_capital ? "Автор" : "автор"));
      if (!singular) result+="и";
      return result;
    }
trBug()
QCString TranslatorUkrainian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1102 of file translator_ua.h.
    {
      return "Дефект";
    }
trBugList()
QCString TranslatorUkrainian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1107 of file translator_ua.h.
    {
      return "Список дефектів";
    }
trCallerGraph()
QCString TranslatorUkrainian::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1477 of file translator_ua.h.
    {
      return "Граф викликів для цієї функції:";
    }
trCallGraph()
QCString TranslatorUkrainian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1361 of file translator_ua.h.
    {
      return "Граф всіх викликів цієї функції:";
    }
trCiteReferences()
QCString TranslatorUkrainian::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1818 of file translator_ua.h.
    { return "Бібліографічні посилання"; }
trClass()
QCString TranslatorUkrainian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1135 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        QCString result((first_capital ? "Структури даних" : "структури даних"));
        return result;
      }
      else
      {
        QCString result((first_capital ? "Клас" : "клас"));
        if(!singular) result+="и";
        return result;
      }
    }
References Config_getBool.
trClassDiagram()
QCString TranslatorUkrainian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 463 of file translator_ua.h.
    {
      return QCString("Схема успадкувань для ")+clName;
    }
trClassDocumentation()
QCString TranslatorUkrainian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 339 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return  "Структури даних" ;
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return  "Класи" ;
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorUkrainian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1065 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return  "Структури даних" ;
      }
      else
      {
        return  "Класи" ;
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorUkrainian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 145 of file translator_ua.h.
    { return "Ієрархія класів"; }
trClassHierarchyDescription()
QCString TranslatorUkrainian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 200 of file translator_ua.h.
    { return "Список успадкувань впорядковано наближено до алфавіту"; }
trClassMethods()
QCString TranslatorUkrainian::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1902 of file translator_ua.h.
    {
      return "Методи класу";
    }
trCode()
QCString TranslatorUkrainian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 839 of file translator_ua.h.
    {
      return "Вихідні тексти";
    }
trCollaborationDiagram()
QCString TranslatorUkrainian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 794 of file translator_ua.h.
    {
      return "Діаграма зв'язків класу "+clName+":";
    }
trCompoundIndex()
QCString TranslatorUkrainian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 312 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return  "Алфавітний покажчик структур даних" ;
      }
      else
      {
        return  "Алфавітний покажчик класів" ;
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorUkrainian::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1532 of file translator_ua.h.
    { return "Список типів даних"; }
trCompoundList()
QCString TranslatorUkrainian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 149 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return  "Структури даних" ;
      }
      else
      {
        return  "Класи" ;
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorUkrainian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 213 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return  "Структури даних з коротким описом." ;
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return  "Класи з коротким описом." ;
      }
      else
      {
        return  "Класи, структури, об'єднання та інтерфейси  з коротким описом." ;
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorUkrainian::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1505 of file translator_ua.h.
    { return "Типи даних з коротким описом:"; }
trCompoundListFortran()
QCString TranslatorUkrainian::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1497 of file translator_ua.h.
    { return "Список типів даних"; }
trCompoundMembers()
QCString TranslatorUkrainian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 166 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return  "Поля структур" ;
      }
      else
      {
        return  "Елементи класів" ;
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorUkrainian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 230 of file translator_ua.h.
    {
        QCString result="Список всіх ";
        if(!extractAll) result+="документоаних ";
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result+="елементів структур даних з посиланням на ";
        else
          result+="елементів класів даних з посиланням на ";
        if(extractAll)
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result+="документацію по структурі/об'єднанню кожного елементу.";
          else
            result+="документацію по класу кожного елементу.";
        }
        else
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result += "відповідні структури";
          else
            result += "відповідні класи";
          result+=", до яких вони належать.";
        }
        return  result ;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorUkrainian::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1509 of file translator_ua.h.
    {
      QCString result="Список усіх ";
      if (!extractAll)
      {
        result+="задокументованих ";
      }
      result+="елементів типів даних";
      result+=" з посиланнями на ";
      if (!extractAll)
      {
         result+="документацію структури даних кожного елемента";
      }
      else
      {
         result+="типи даних, до яких вони належать:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorUkrainian::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1501 of file translator_ua.h.
    { return "Поля даних"; }
trCompoundReference()
QCString TranslatorUkrainian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 538 of file translator_ua.h.
    {
      QCString result;
      if (isTemplate)
      {
        result="Шаблон ";
        switch(compType)
        {
          case ClassDef::Class:  result+="класу"; break;
          case ClassDef::Struct: result+="структури"; break;
          case ClassDef::Union:  result+="об'єднання"; break;
          case ClassDef::Interface:  result+="інтерфейсу"; break;
          case ClassDef::Protocol:   result+="протоколу"; break;
          case ClassDef::Category:   result+="категорії"; break;
          case ClassDef::Exception:  result+="Виняток"; break;
          default: break;
        }
      }
      else
      {
        switch(compType)
        {
          case ClassDef::Class:  result+="Клас"; break;
          case ClassDef::Struct: result+="Структура"; break;
          case ClassDef::Union:  result+="Об'єднання"; break;
          case ClassDef::Interface:  result+="Інтерфейс"; break;
          case ClassDef::Protocol:   result+="Протокол"; break;
          case ClassDef::Category:   result+="Категорія"; break;
          case ClassDef::Exception:  result+="Виняток"; break;
          default: break;
        }
      }
      result+=" ";
      return result+clName;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorUkrainian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1573 of file translator_ua.h.
    {
      QCString result=clName;
      if (isTemplate)
      {
        switch(compType)
        {
          case ClassDef::Class:      result+=" Модуль"; break;
          case ClassDef::Struct:     result+=" Тип"; break;
          case ClassDef::Union:      result+=" Об'єднання"; break;
          case ClassDef::Interface:  result+=" Інтерфейс"; break;
          case ClassDef::Protocol:   result+=" Протокол"; break;
          case ClassDef::Category:   result+=" Категорія"; break;
          case ClassDef::Exception:  result+=" Виняток"; break;
          default: break;
        }
      }
      else
      {
        result+=" Шаблон ";
        switch(compType)
        {
          case ClassDef::Class:      result+="модуля"; break;
          case ClassDef::Struct:     result+="типу"; break;
          case ClassDef::Union:      result+="об'єднання"; break;
          case ClassDef::Interface:  result+="інтерфейсу"; break;
          case ClassDef::Protocol:   result+="протоколу"; break;
          case ClassDef::Category:   result+="категорії"; break;
          case ClassDef::Exception:  result+="винятка"; break;
          default: break;
        }
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorUkrainian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 434 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return  "Структури даних" ;
      }
      else
      {
        return  "Класи" ;
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorUkrainian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 804 of file translator_ua.h.
    {
      return "Конструктор(и)";
    }
trCopyright()
QCString TranslatorUkrainian::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1822 of file translator_ua.h.
    { return "Копірайт"; }
trDataTypes()
QCString TranslatorUkrainian::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1556 of file translator_ua.h.
    { return "Типи даних"; }
trDate()
QCString TranslatorUkrainian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 477 of file translator_ua.h.
    { return "Дата"; }
trDateTime()
QCString TranslatorUkrainian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1773 of file translator_ua.h.
    {
      static const char *days[]   = { "Понеділок","Вівторок","Середа","Четвер","П'ятниця","Субота","Неділя" };
      static const char *months[] = { "січня","лютого","березня","квітня","травня","червня","липня","серпня","вересня","жотня","листопада","грудня" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s, %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorUkrainian::trDayOfWeek (int dayOfWeek, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1793 of file translator_ua.h.
    {
      static const char *days_short[]   = { "Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Нд" };
      static const char *days_full[]    = { "понеділок", "вівторок", "середа", "четвер", "п'ятниця", "субота", "неділя" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod()
QCString TranslatorUkrainian::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1807 of file translator_ua.h.
    {
      static const char *dayPeriod[] = { "дп", "пп" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorUkrainian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 771 of file translator_ua.h.
    {
      return "Див. визначення в файлі @1, рядок @0";
    }
trDefinedIn()
QCString TranslatorUkrainian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 133 of file translator_ua.h.
    { return "визначено в "; }
trDefinedInSourceFile()
QCString TranslatorUkrainian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 775 of file translator_ua.h.
    {
      return "Див. визначення в файлі @0";
    }
trDefineDocumentation()
QCString TranslatorUkrainian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 404 of file translator_ua.h.
    { return "Опис макровизначень"; }
trDefines()
QCString TranslatorUkrainian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 368 of file translator_ua.h.
    { return "Макровизначення"; }
trDefineValue()
QCString TranslatorUkrainian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1092 of file translator_ua.h.
    {
      return "Макровизначення:";
    }
trDeprecated()
QCString TranslatorUkrainian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 784 of file translator_ua.h.
    {
      return "Не рекомендовано";
    }
trDeprecatedList()
QCString TranslatorUkrainian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1279 of file translator_ua.h.
    {
      return "Застарілі елементи";
    }
trDetailedDescription()
QCString TranslatorUkrainian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 54 of file translator_ua.h.
    { return "Детальний опис"; }
trDetailLevel()
QCString TranslatorUkrainian::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1834 of file translator_ua.h.
    { return "рівень елемента"; }
trDetails()
QCString TranslatorUkrainian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 58 of file translator_ua.h.
    { return "Подробиці"; }
trDir()
QCString TranslatorUkrainian::trDir (bool , bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1451 of file translator_ua.h.
    {
      QCString result("Каталог");
      if (!singular) result+="и";
      return result;
    }
trDirDepGraph()
QCString TranslatorUkrainian::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1826 of file translator_ua.h.
    { return QCString("Граф залежностей каталогу для ")+name+":"; }
trDirDocumentation()
QCString TranslatorUkrainian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1433 of file translator_ua.h.
    { return "Документація каталогів"; }
trDirectories()
QCString TranslatorUkrainian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1439 of file translator_ua.h.
    { return "Каталоги"; }
trDirIndex()
QCString TranslatorUkrainian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1427 of file translator_ua.h.
    { return "Дерево каталогів"; }
trDirReference()
QCString TranslatorUkrainian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1445 of file translator_ua.h.
    { QCString result="Довідник каталогу "; result+=dirName; return result; }
trDirRelation()
QCString TranslatorUkrainian::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1712 of file translator_ua.h.
    {
      return "Зв'язок з "+QCString(name);
    }
trDocumentation()
QCString TranslatorUkrainian::trDocumentation () inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 294 of file translator_ua.h.
    { return "Документація"; }
trEnumerations()
QCString TranslatorUkrainian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 380 of file translator_ua.h.
    { return "Переліки"; }
trEnumerationTypeDocumentation()
QCString TranslatorUkrainian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 416 of file translator_ua.h.
    { return "Опис переліків"; }
trEnumerationValueDocumentation()
QCString TranslatorUkrainian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1485 of file translator_ua.h.
    { return "Документація переліку"; }
trEnumerationValues()
QCString TranslatorUkrainian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 398 of file translator_ua.h.
    { return "Елементи переліків"; }
trEnumGeneratedFromFiles()
QCString TranslatorUkrainian::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1846 of file translator_ua.h.
    { QCString result = "Документацію для цього переліку булозгенеровано з ";
            result += (single? "наступного файла": "наступних файлів");
      result+=":";
      return result;
    }
trEnumName()
QCString TranslatorUkrainian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 125 of file translator_ua.h.
    { return "Перелік"; }
trEnumReference()
QCString TranslatorUkrainian::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1854 of file translator_ua.h.
    { return QCString(name)+" Перелік"; }
trEnumValue()
QCString TranslatorUkrainian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 129 of file translator_ua.h.
    { return "Елемент переліку"; }
trEventDocumentation()
QCString TranslatorUkrainian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1297 of file translator_ua.h.
    {
      return "Документація подій";
    }
trEvents()
QCString TranslatorUkrainian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1291 of file translator_ua.h.
    {
      return "Події";
    }
trExamples()
QCString TranslatorUkrainian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 192 of file translator_ua.h.
    { return "Приклади"; }
trExamplesDescription()
QCString TranslatorUkrainian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 280 of file translator_ua.h.
    { return "Повний список прикладів."; }
trExceptions()
QCString TranslatorUkrainian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 493 of file translator_ua.h.
    { return "Обробка виняткових ситуацій"; }
trExtendsClass()
QCString TranslatorUkrainian::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1894 of file translator_ua.h.
    {
      return "Розширює клас @0.";
    }
trFile()
QCString TranslatorUkrainian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1154 of file translator_ua.h.
    {
      QCString result((first_capital ? "Файл" : "файл"));
      if (!singular)  result+="и";
      return result;
    }
trFileDocumentation()
QCString TranslatorUkrainian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 358 of file translator_ua.h.
    { return "Файли"; }
trFileIn()
QCString TranslatorUkrainian::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1749 of file translator_ua.h.
    {
      return "Файл у "+name;
    }
trFileIndex()
QCString TranslatorUkrainian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 327 of file translator_ua.h.
    { return  "Покажчик файлв" ; }
trFileList()
QCString TranslatorUkrainian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 162 of file translator_ua.h.
    { return "Файли"; }
trFileListDescription()
QCString TranslatorUkrainian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 204 of file translator_ua.h.
    {
      QCString result="Повний список ";
      if (!extractAll) result+="документованих ";
      result+="файлів.";
      return result;
    }
trFileMembers()
QCString TranslatorUkrainian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 180 of file translator_ua.h.
    {
      return  "Елементи файлу" ;
    }
trFileMembersDescription()
QCString TranslatorUkrainian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 257 of file translator_ua.h.
    {
      QCString result="Список всіх ";
      if (!extractAll) result+="документованих ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="функцій, змінних, макровизначень, "
                "переліків і визначень типів";
      }
      else
      {
        result+="елементів файлів ";
      }
      result+=" з посиланям на ";
      if (extractAll)
        result+="файли, до яких вони належать.";
      else
        result+="документацію.";
      return  result ;
    }
References Config_getBool.
trFileReference()
QCString TranslatorUkrainian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 577 of file translator_ua.h.
    {
      return QCString("Файл ")+fileName;
    }
trFriends()
QCString TranslatorUkrainian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 520 of file translator_ua.h.
    { return "Дружні класи"; }
trFunctionDocumentation()
QCString TranslatorUkrainian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 422 of file translator_ua.h.
    { return "Опис функцій"; }
trFunctions()
QCString TranslatorUkrainian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 386 of file translator_ua.h.
    { return "Функції"; }
trGeneratedAt()
QCString TranslatorUkrainian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the documentation of a group before the list of links to documented files
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 453 of file translator_ua.h.
    {
      QCString result="Документація ";
      if (!projName.isEmpty()) result+=QCString("до ")+projName;
      result+=QCString(" створена ")+date;
      result+=" системою";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorUkrainian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 117 of file translator_ua.h.
    { QCString result="Автоматично створено за допомогою Doxygen";
      if (!s.isEmpty()) result+=QCString(" для ")+s;
      result+=" з тексту програми.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorUkrainian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 497 of file translator_ua.h.
    { return "Створено системою"; }
trGeneratedFromFiles()
QCString TranslatorUkrainian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 712 of file translator_ua.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Документація  ";
      switch(compType)
      {
        case ClassDef::Class:
          if (single) result+="цього класу"; else result+="цих класів";
          break;
        case ClassDef::Struct:
          if (single) result+="цієї структури"; else result+="цих структур";
          break;
        case ClassDef::Union:
          if (single) result+="цього об'єднання"; else result+="цих об'єднань";
          break;
        case ClassDef::Interface:
          if (single) result+="цього інтерфейсу"; else result+="цих інтерфейсів";
          break;
        case ClassDef::Protocol:
          if (single) result+="цього протоколу"; else result+="цих протоколів";
          break;
        case ClassDef::Category:
          if (single) result+="цієї категорії"; else result+="цих категорій";
          break;
        case ClassDef::Exception:
          if (single) result+="цього винятку"; else result+="цих винятків";
          break;
        default:
          break;
      }
      result+=" була створена з файл";
      if (single) result+="у:"; else result+="ів:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorUkrainian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1658 of file translator_ua.h.
    {
      // single is true implies a single file
      QCString result="Документацію для ";
      switch(compType)
      {
        case ClassDef::Class:      result+="цього модуля"; break;
        case ClassDef::Struct:     result+="цього типу"; break;
        case ClassDef::Union:      result+="цього об'єднання"; break;
        case ClassDef::Interface:  result+="цього інтерфейсу"; break;
        case ClassDef::Protocol:   result+="цього протоколу"; break;
        case ClassDef::Category:   result+="цієї категорії"; break;
        case ClassDef::Exception:  result+="цього винятку"; break;
        default: break;
      }
      result+=" було згенеровано з ";
      if (single) result+="наступного файлу:"; else result+="наступних файлів:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorUkrainian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1209 of file translator_ua.h.
    {
      QCString result((first_capital ? "Глобальн" : "глобальн"));
      result+=(singular ? "ий" : "і");
      return result;
    }
trGlobalNamespace()
QCString TranslatorUkrainian::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1724 of file translator_ua.h.
    {
      return "Глобальний простір імен";
    }
trGotoDocumentation()
QCString TranslatorUkrainian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 814 of file translator_ua.h.
    {
      return "Див. документацію.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorUkrainian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 847 of file translator_ua.h.
    {
      return "див. графічну ієрархію";
    }
trGotoSourceCode()
QCString TranslatorUkrainian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 809 of file translator_ua.h.
    {
      return "Див. вихідні тексти.";
    }
trGotoTextualHierarchy()
QCString TranslatorUkrainian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 851 of file translator_ua.h.
    {
      return "див. текстову ієрархію";
    }
trGraphicalHierarchy()
QCString TranslatorUkrainian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 843 of file translator_ua.h.
    {
      return "Графічна ієрархія класів";
    }
trGroup()
QCString TranslatorUkrainian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1176 of file translator_ua.h.
    {
      QCString result((first_capital ? "Груп" : "груп"));
      result+=(singular ? "а" : "и");
      return result;
    }
trHierarchicalIndex()
QCString TranslatorUkrainian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 306 of file translator_ua.h.
    { return "Ієрархічний покажчик класів"; }
trImplementedFromList()
QCString TranslatorUkrainian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1247 of file translator_ua.h.
    {
      return "Реалізує " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorUkrainian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1255 of file translator_ua.h.
    {
      return "Реалізує в " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorUkrainian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 946 of file translator_ua.h.
    {
      return "Граф файлів, які включають цей файл:";
    }
trInclDepGraph()
QCString TranslatorUkrainian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 799 of file translator_ua.h.
    {
      return QCString("Діаграма включених заголовочних файлів для ")+fName+":";
    }
trIncludesFileIn()
QCString TranslatorUkrainian::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1758 of file translator_ua.h.
    {
      return "Включає файли в "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorUkrainian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 111 of file translator_ua.h.
    { return ", включаючи всі успадковані елементи"; }
trInheritedByList()
QCString TranslatorUkrainian::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 645 of file translator_ua.h.
    {
      return "Успадковано класами "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorUkrainian::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1858 of file translator_ua.h.
    { return QCString(members)+" успадковано з "+what; }
trInheritsList()
QCString TranslatorUkrainian::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 637 of file translator_ua.h.
    {
      return "Успадковує клас "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorUkrainian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 834 of file translator_ua.h.
    {
      return "Початкові значення";
    }
trInstanceMethods()
QCString TranslatorUkrainian::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1910 of file translator_ua.h.
    {
      return "Методи об'єкта";
    }
trInvariant()
QCString TranslatorUkrainian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 829 of file translator_ua.h.
    {
      return "Інваріант";
    }
trISOLang()
QCString TranslatorUkrainian::trISOLang () inline override virtual
Implements Translator.
Definition at line 34 of file translator_ua.h.
    {
      return "uk";
    }
trLegend()
QCString TranslatorUkrainian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1025 of file translator_ua.h.
    {
      return "див. легенду";
    }
trLegendDocs()
QCString TranslatorUkrainian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 966 of file translator_ua.h.
    {
      return
        "Позначення, що використовуються у графах.<p>\n"
        "Розглянемо наступний приклад:\n"
        "\\code\n"
        "/*! Невидимий клас через зрізання */\n"
        "class Invisible { };\n\n"
        "/*! Обмежений клас, відношення успадкування приховане */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Недокументований клас */\n"
        "class Undocumented { };\n\n"
        "/*! Загальнодоступне успадкування */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Захищене успадкування */\n"
        "class ProtectedBase { };\n\n"
        "/*! Приватне успадкування */\n"
        "class PrivateBase { };\n\n"
        "/*! Клас, що використовується класом Inherited */\n"
        "class Used { };\n\n"
        "/*! Клас, що успадковує інші класи */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Таким чином, отримуємо наступний граф:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Прямокутники в цьому графі мають наступний зміст:\n"
        "<ul>\n"
        "<li>Заповнений чорний прямокутник відображає структуру або клас, "
        "для якого створено граф.\n"
        "<li>Прямокутник з чорною межею відображає документовану структуру або клас.\n"
        "<li>Прямокутник з сірою межею відображає недокументовану структуру або клас.\n"
        "<li>Прямокутник з червоною межею відображає документовану структуру або клас, для яких\n"
        " не всі співвідношення успадкування/змісту показані. Граф зрізаниЙ, "
        "якщо він не вміщається у вказані межі."
        "</ul>\n"
        "Стрілки мають наступний зміст:\n"
        "<ul>\n"
        "<li>Темносиня стрілка відображає відношення загальнодоступного успадкування "
        "між двома класами.\n"
        "<li>Темнозелена стрілка використовується при захищеному успадкуванні.\n"
        "<li>Темночервона стрілка використовується при приватному успадкуванні.\n"
        "<li>Пурпурна стрілка використовується, якщо клас міститься в"
        "іншому класі або ним використовується."
        "Стрілка етикетується змінною, "
        "через яку відбувається доступ до вказаної структури або класу. \n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorUkrainian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 961 of file translator_ua.h.
    {
      return "Легенда";
    }
trListOfAllMembers()
QCString TranslatorUkrainian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 92 of file translator_ua.h.
    {
      return  "Список всіх елементів" ;
    }
trLoading()
QCString TranslatorUkrainian::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1718 of file translator_ua.h.
    {
      return "Завантаження...";
    }
trMainPage()
QCString TranslatorUkrainian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 758 of file translator_ua.h.
    { return "Титульна сторінка"; }
trMember()
QCString TranslatorUkrainian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1198 of file translator_ua.h.
    {
      QCString result((first_capital ? "Елемент" : "елемент"));
      if (!singular)  result+="и";
      return result;
    }
trMemberDataDocumentation()
QCString TranslatorUkrainian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 74 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return  "Поля" ;
      }
      else
      {
        return  "Компонентні дані" ;
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorUkrainian::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 66 of file translator_ua.h.
    { return "Опис переліків користувача"; }
trMemberFunctionDocumentation()
QCString TranslatorUkrainian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 70 of file translator_ua.h.
    { return "Опис методів компонент"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorUkrainian::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1493 of file translator_ua.h.
    { return "Документація функції/підпрограми"; }
trMemberList()
QCString TranslatorUkrainian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 99 of file translator_ua.h.
    {
      return  "Cписок елементів" ;
    }
trMemberTypedefDocumentation()
QCString TranslatorUkrainian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 62 of file translator_ua.h.
    { return "Опис типів користувача"; }
trMethodDocumentation()
QCString TranslatorUkrainian::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1917 of file translator_ua.h.
    {
      return "Документація метода";
    }
trModule()
QCString TranslatorUkrainian::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1648 of file translator_ua.h.
    {
            QCString result((first_capital ? "Модул" : "модул"));
            result+=(singular? "ь": "і");
      return result;
    }
trModuleDocumentation()
QCString TranslatorUkrainian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 333 of file translator_ua.h.
    { return "Програмні Модулі"; }
trModuleIndex()
QCString TranslatorUkrainian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 300 of file translator_ua.h.
    { return "Алфавітний покажчик модулів"; }
trModuleReference()
QCString TranslatorUkrainian::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1610 of file translator_ua.h.
    {
      QCString result=namespaceName;
      result+=" Модуль";
      return result;
    }
trModules()
QCString TranslatorUkrainian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 141 of file translator_ua.h.
    { return "Програмні модулі"; }
trModulesDescription()
QCString TranslatorUkrainian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 288 of file translator_ua.h.
    { return "Повний список модулів."; }
trModulesIndex()
QCString TranslatorUkrainian::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1641 of file translator_ua.h.
    { return "Алфавітний покажчик модулів"; }
trModulesList()
QCString TranslatorUkrainian::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1560 of file translator_ua.h.
    { return "Список модулів"; }
trModulesListDescription()
QCString TranslatorUkrainian::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1564 of file translator_ua.h.
    {
      QCString result="Список усіх ";
      if (!extractAll) result+="задокументованих ";
      result+="модулів з коротким описом:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorUkrainian::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1622 of file translator_ua.h.
    {
      QCString result="Список усіх ";
      if (!extractAll) result+="задокументованих ";
      result+="елементів модулів з посиланнями на ";
      if (extractAll)
      {
        result+="документацію модуля для кожного елемента:";
      }
      else
      {
        result+="модулі, до яких вони належать:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorUkrainian::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1618 of file translator_ua.h.
    { return "Елементи модуля"; }
trMonth()
QCString TranslatorUkrainian::trMonth (int month, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1800 of file translator_ua.h.
    {
      static const char *months_short[] = { "Січ", "Лют", "Бер", "Кві", "Тра", "Чер", "Лип", "Сер", "Вер", "Жов", "Лис", "Гру" };
      static const char *months_full[]  = { "січень", "лютий", "березень", "квітень", "травень", "червень", "липень", "серпень", "вересень", "жовтень", "листопад", "грудень" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore()
QCString TranslatorUkrainian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 87 of file translator_ua.h.
    { return "Детальніше..."; }
trNamespace()
QCString TranslatorUkrainian::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1165 of file translator_ua.h.
    {
      QCString result((first_capital ? "Прост" : "прост"));
      result+=(singular?"ір імен":"ори імен");
      return result;
    }
trNamespaceDocumentation()
QCString TranslatorUkrainian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 692 of file translator_ua.h.
    { return "Опис простору імен"; }
trNamespaceIndex()
QCString TranslatorUkrainian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 686 of file translator_ua.h.
    { return "Алфавітний покажчик простору імен"; }
trNamespaceList()
QCString TranslatorUkrainian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 505 of file translator_ua.h.
    { return "Простір імен"; }
trNamespaceListDescription()
QCString TranslatorUkrainian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 509 of file translator_ua.h.
    {
      QCString result="Повний список ";
      if (!extractAll) result+="документованих ";
      result+="просторів імен.";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorUkrainian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 671 of file translator_ua.h.
    {
      QCString result="Повний список ";
      if (!extractAll) result+="документованих ";
      result+="елеметів простору імен з посиланням ";
      if (extractAll)
        result+="на документацію для кожного елементу:";
      else
        result+="на простір імен до якого вони належать:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorUkrainian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 667 of file translator_ua.h.
    { return "Елементи простору імен"; }
trNamespaceReference()
QCString TranslatorUkrainian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 583 of file translator_ua.h.
    {
      return QCString("Простір імен ")+namespaceName;
    }
trNamespaces()
QCString TranslatorUkrainian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 702 of file translator_ua.h.
    { return  "Простори імен" ; }
trNoMatches()
QCString TranslatorUkrainian::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1736 of file translator_ua.h.
    {
      return "Нічого не знайдено";
    }
trNote()
QCString TranslatorUkrainian::trNote () inline override virtual
Implements Translator.
Definition at line 864 of file translator_ua.h.
    {
      return "Нотатки";
    }
trOverloadText()
QCString TranslatorUkrainian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1465 of file translator_ua.h.
    {
       return "Це перезавантажуваний метод, "
              "ввкдкний для зручності. Він відрізняється від "
              "описаної вище функції лише списком аргуметнів.";
    }
trPackage()
QCString TranslatorUkrainian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1077 of file translator_ua.h.
    {
      return QCString("Пакет ")+name;
    }
trPackageAttribs()
QCString TranslatorUkrainian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1336 of file translator_ua.h.
    {
      return "Атрибути пакетів";
    }
trPackageFunctions()
QCString TranslatorUkrainian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1316 of file translator_ua.h.
    {
      return "Функції пакетів";
    }
trPackageListDescription()
QCString TranslatorUkrainian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1082 of file translator_ua.h.
    {
      return "Повний список документованих пакетів.";
    }
trPackageMembers()
QCString TranslatorUkrainian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1320 of file translator_ua.h.
    {
      return "Елементи пакетів";
    }
trPackages()
QCString TranslatorUkrainian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1087 of file translator_ua.h.
    {
      return "Пакети";
    }
trPackageTypes()
QCString TranslatorUkrainian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1308 of file translator_ua.h.
    {
      return "Типи пакетів";
    }
trPage()
QCString TranslatorUkrainian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1187 of file translator_ua.h.
    {
      QCString result((first_capital ? "Сторінк" : "сторінк"));
      result+=(singular ? "а" : "и");
      return result;
    }
trPageAbbreviation()
QCString TranslatorUkrainian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 764 of file translator_ua.h.
    { return "стор."; }
trPageIndex()
QCString TranslatorUkrainian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 855 of file translator_ua.h.
    {
      return "Алфавітний покажчик тематичних описів";
    }
trPanelSynchronisationTooltip()
QCString TranslatorUkrainian::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1875 of file translator_ua.h.
    {
      QCString opt = enable ? "дозволити" : "заборонити";
      return "клацніть мишкою, щоб "+opt+" синхронізацію панелі";
    }
trParameters()
QCString TranslatorUkrainian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 489 of file translator_ua.h.
    { return "Аргументи"; }
trPostcondition()
QCString TranslatorUkrainian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 824 of file translator_ua.h.
    {
      return "Післяумови";
    }
trPrecondition()
QCString TranslatorUkrainian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 819 of file translator_ua.h.
    {
      return "Передумови";
    }
trPrivateAttribs()
QCString TranslatorUkrainian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 903 of file translator_ua.h.
    {
      return "Приватні дані";
    }
trPrivateMembers()
QCString TranslatorUkrainian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 602 of file translator_ua.h.
    { return "Приватні елементи"; }
trPrivateSlots()
QCString TranslatorUkrainian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 604 of file translator_ua.h.
    { return "Приватні слоти"; }
trPrivateTypes()
QCString TranslatorUkrainian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 899 of file translator_ua.h.
    {
      return "Приватні типи";
    }
trProperties()
QCString TranslatorUkrainian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1050 of file translator_ua.h.
    {
      return "Властивості";
    }
trPropertyDocumentation()
QCString TranslatorUkrainian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1055 of file translator_ua.h.
    {
      return "Повний список властивостей";
    }
trProtectedAttribs()
QCString TranslatorUkrainian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 891 of file translator_ua.h.
    {
      return "Захищені дані";
    }
trProtectedMembers()
QCString TranslatorUkrainian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 596 of file translator_ua.h.
    { return "Захищені елементи"; }
trProtectedSlots()
QCString TranslatorUkrainian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 598 of file translator_ua.h.
    { return "Захищені слоти"; }
trProtectedTypes()
QCString TranslatorUkrainian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 887 of file translator_ua.h.
    {
      return "Захищені типи";
    }
trProvidedByCategory()
QCString TranslatorUkrainian::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1885 of file translator_ua.h.
    {
      return "Забезпечено категорією @0.";
    }
trPublicAttribs()
QCString TranslatorUkrainian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 872 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return  "Поля даних" ;
      }
      else
      {
        return  "Загальнодоступні атрибути" ;
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorUkrainian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 588 of file translator_ua.h.
    { return "Загальнодоступні елементи"; }
trPublicSlots()
QCString TranslatorUkrainian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 590 of file translator_ua.h.
    { return "Загальнодоступні слоти"; }
trPublicTypes()
QCString TranslatorUkrainian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 868 of file translator_ua.h.
    {
      return "Загальнодоступні типи";
    }
trReferencedBy()
QCString TranslatorUkrainian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 934 of file translator_ua.h.
    {
      return "Вживається в";
    }
trReferenceManual()
QCString TranslatorUkrainian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 362 of file translator_ua.h.
    { return "Довідковий посібник"; }
trReferences()
QCString TranslatorUkrainian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1235 of file translator_ua.h.
    {
      return "Використовує";
    }
trReimplementedFromList()
QCString TranslatorUkrainian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 653 of file translator_ua.h.
    {
      return "Переозначення з "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorUkrainian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 661 of file translator_ua.h.
    {
      return "Переозначається в "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorUkrainian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 530 of file translator_ua.h.
      { return "Документация до дружніх класів та відповідних функцій"; }
trRelatedFunctions()
QCString TranslatorUkrainian::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 46 of file translator_ua.h.
    { return "Споріднені фукції"; }
trRelatedPages()
QCString TranslatorUkrainian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 186 of file translator_ua.h.
    { return "Додаткова інформація"; }
trRelatedPagesDescription()
QCString TranslatorUkrainian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 284 of file translator_ua.h.
    { return "Повний список додаткових описів."; }
trRelatedSubscript()
QCString TranslatorUkrainian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 50 of file translator_ua.h.
    { return "(не методи компонент)"; }
trRemarks()
QCString TranslatorUkrainian::trRemarks () inline override virtual
Implements Translator.
Definition at line 938 of file translator_ua.h.
    {
      return "Прим.";
    }
trReturns()
QCString TranslatorUkrainian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 481 of file translator_ua.h.
    { return "Повертає"; }
trReturnValues()
QCString TranslatorUkrainian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 753 of file translator_ua.h.
    { return "Значення, що повертаються"; }
trRTFansicp()
QCString TranslatorUkrainian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1116 of file translator_ua.h.
    {
      return "1251";
    }
trRTFCharSet()
QCString TranslatorUkrainian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1121 of file translator_ua.h.
    {
      return "204";
    }
trRTFGeneralIndex()
QCString TranslatorUkrainian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1126 of file translator_ua.h.
    {
      return "Предметний покажчик";
    }
trRTFTableOfContents()
QCString TranslatorUkrainian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1267 of file translator_ua.h.
    {
      return "Зміст";
    }
trSearch()
QCString TranslatorUkrainian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 196 of file translator_ua.h.
    { return "Пошук"; }
trSearching()
QCString TranslatorUkrainian::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1730 of file translator_ua.h.
    {
      return "Пошук...";
    }
trSearchMatches()
QCString TranslatorUkrainian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1404 of file translator_ua.h.
    {
      return "Відповідність:";
    }
trSearchResults()
QCString TranslatorUkrainian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1385 of file translator_ua.h.
    {
      if (numDocuments==0)
      {
        return "Не знайдено документів відповідно до вашого запиту.";
      }
      else if (numDocuments==1)
      {
        return "Було знайдено <b>1</b> документ відповідно до вашого запиту.";
      }
      else
      {
        return "Було знайдено <b>$num</b> документів відповідно до вашого запиту. "
               "Найкращі відповідності показано спочатку.";
      }
    }
trSearchResultsTitle()
QCString TranslatorUkrainian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1373 of file translator_ua.h.
    {
      return "Результати пошуку";
    }
trSeeAlso()
QCString TranslatorUkrainian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 485 of file translator_ua.h.
    { return "Див. також"; }
trSignals()
QCString TranslatorUkrainian::trSignals () inline override virtual
Implements Translator.
Definition at line 592 of file translator_ua.h.
    { return "Сигнали"; }
trSince()
QCString TranslatorUkrainian::trSince () inline override virtual
Implements Translator.
Definition at line 950 of file translator_ua.h.
    {
      return "Починаючи з";
    }
trSourceFile()
QCString TranslatorUkrainian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1415 of file translator_ua.h.
    {
      return "Текст програми "+filename;
    }
trStaticPackageAttribs()
QCString TranslatorUkrainian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1344 of file translator_ua.h.
    {
      return "Статичні атрибути пакетів";
    }
trStaticPackageFunctions()
QCString TranslatorUkrainian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1328 of file translator_ua.h.
    {
      return "Статичні функцію пакетів";
    }
trStaticPrivateAttribs()
QCString TranslatorUkrainian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 907 of file translator_ua.h.
    {
      return "Приватні статичні дані";
    }
trStaticPrivateMembers()
QCString TranslatorUkrainian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 606 of file translator_ua.h.
    { return "Приватні статичні елементи"; }
trStaticProtectedAttribs()
QCString TranslatorUkrainian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 895 of file translator_ua.h.
    {
      return "Статичні захищені дані";
    }
trStaticProtectedMembers()
QCString TranslatorUkrainian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 600 of file translator_ua.h.
    { return "Захищені статичні елементи"; }
trStaticPublicAttribs()
QCString TranslatorUkrainian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 883 of file translator_ua.h.
    {
      return "Статичні загальнодоступні данні";
    }
trStaticPublicMembers()
QCString TranslatorUkrainian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 594 of file translator_ua.h.
    { return "Загальнодоступні статичні елементи"; }
trSubprogram()
QCString TranslatorUkrainian::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1694 of file translator_ua.h.
    {
      QCString result((first_capital ? "Підпрограм" : "підпрограм"));
      result+= (singular? "а": "и");
      return result;
    }
trSubprogramDocumentation()
QCString TranslatorUkrainian::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1550 of file translator_ua.h.
    { return "Документація функцій/підпрограм"; }
trSubprograms()
QCString TranslatorUkrainian::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1544 of file translator_ua.h.
    { return "Функції/підпрограми"; }
trTemplateParameters()
QCString TranslatorUkrainian::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1838 of file translator_ua.h.
    { return "Параметри шаблона"; }
trTest()
QCString TranslatorUkrainian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1035 of file translator_ua.h.
    {
      return "Тест";
    }
trTestList()
QCString TranslatorUkrainian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1040 of file translator_ua.h.
    {
      return "Список тестів";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorUkrainian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 106 of file translator_ua.h.
    { return "Повний список елементів"; }
trTodo()
QCString TranslatorUkrainian::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 918 of file translator_ua.h.
    {
      return "Необхідно зробити";
    }
trTodoList()
QCString TranslatorUkrainian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 924 of file translator_ua.h.
    {
      return "Список завдань";
    }
trType()
QCString TranslatorUkrainian::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1683 of file translator_ua.h.
    {
      QCString result((first_capital ? "Тип" : "тип"));
      if (!singular)  result+="и";
      return result;
    }
trTypeConstraints()
QCString TranslatorUkrainian::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1702 of file translator_ua.h.
    {
      return "Обмеження типу";
    }
trTypedefDocumentation()
QCString TranslatorUkrainian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 410 of file translator_ua.h.
    { return "Опис визначень типів"; }
trTypedefs()
QCString TranslatorUkrainian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 374 of file translator_ua.h.
    { return "Визначення типів"; }
trTypeDocumentation()
QCString TranslatorUkrainian::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1538 of file translator_ua.h.
    { return "Документація типів даних"; }
trVariableDocumentation()
QCString TranslatorUkrainian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 428 of file translator_ua.h.
    { return "Опис змінних"; }
trVariables()
QCString TranslatorUkrainian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 392 of file translator_ua.h.
    { return "Змінні"; }
trVersion()
QCString TranslatorUkrainian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 473 of file translator_ua.h.
    { return "Версія"; }
trWarning()
QCString TranslatorUkrainian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 469 of file translator_ua.h.
    { return "Застереження"; }
trWriteList()
QCString TranslatorUkrainian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 612 of file translator_ua.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+= " і " ;
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_ua.h