Doxygen: src/groupdef.cpp File Reference
groupdef.cpp File Reference
#include <algorithm>
#include <vector>
#include <ctype.h>
#include "groupdef.h"
#include "classdef.h"
#include "filedef.h"
#include "classlist.h"
#include "outputlist.h"
#include "namespacedef.h"
#include "language.h"
#include "util.h"
#include "memberlist.h"
#include "message.h"
#include "membergroup.h"
#include "doxygen.h"
#include "pagedef.h"
#include "docparser.h"
#include "searchindex.h"
#include "dot.h"
#include "dotgroupcollaboration.h"
#include "vhdldocgen.h"
#include "layout.h"
#include "arguments.h"
#include "entry.h"
#include "membername.h"
#include "dirdef.h"
#include "config.h"
#include "definitionimpl.h"
#include "regex.h"
#include "moduledef.h"
Classes
class GroupDefImpl
Functions
std::unique_ptr< GroupDef > createGroupDef (const QCString &fileName, int line, const QCString &name, const QCString &title, const QCString &refFileName)
void addClassToGroups (const Entry *root, ClassDef *cd)
void addConceptToGroups (const Entry *root, ConceptDef *cd)
void addModuleToGroups (const Entry *root, ModuleDef *mod)
void addNamespaceToGroups (const Entry *root, NamespaceDef *nd)
void addDirToGroups (const Entry *root, DirDef *dd)
void addGroupToGroups (const Entry *root, GroupDef *subGroup)
void addMemberToGroups (const Entry *root, MemberDef *md)
void addExampleToGroups (const Entry *root, PageDef *eg)
template<class Vec >
static void groupClassesWithSameScope (Vec &vec)
static bool hasNonReferenceNestedGroupRec (const GroupDef *gd, int level)
GroupDef * toGroupDef (Definition *d)
const GroupDef * toGroupDef (const Definition *d)
Function Documentation
addClassToGroups()
void addClassToGroups (const Entry * root, ClassDef * cd)
Definition at line 1410 of file groupdef.cpp.
{
  for (const Grouping &g : root->groups)
  {
    GroupDef *gd=nullptr;
    if (!g.groupname.isEmpty()) gd=Doxygen::groupLinkedMap->find(g.groupname);
    if (gd && gd->addClass(cd))
    {
      ClassDefMutable *cdm = toClassDefMutable(cd);
      if (cdm)
      {
        cdm->makePartOfGroup(gd);
      }
      //printf("Compound %s: in group %s\n",qPrint(cd->name()),gd->groupTitle());
    }
    else if (!gd && g.pri == Grouping::GROUPING_INGROUP)
    {
      warn(root->fileName, root->startLine,
          "Found non-existing group '%s' for the command '%s', ignoring command",
          qPrint(g.groupname), Grouping::getGroupPriName( g.pri )
          );
    }
  }
}
References GroupDef::addClass(), Entry::fileName, Grouping::getGroupPriName(), Grouping::GROUPING_INGROUP, Doxygen::groupLinkedMap, Entry::groups, DefinitionMutable::makePartOfGroup(), qPrint(), Entry::startLine, toClassDefMutable(), and warn.
Referenced by addClassToContext().
addConceptToGroups()
void addConceptToGroups (const Entry * root, ConceptDef * cd)
Definition at line 1435 of file groupdef.cpp.
{
  for (const Grouping &g : root->groups)
  {
    GroupDef *gd = Doxygen::groupLinkedMap->find(g.groupname);
    if (gd && gd->addConcept(cd))
    {
      ConceptDefMutable *cdm = toConceptDefMutable(cd);
      if (cdm)
      {
        cdm->makePartOfGroup(gd);
      }
      //printf("Compound %s: in group %s\n",qPrint(cd->name()),gd->groupTitle());
    }
    else if (!gd && g.pri == Grouping::GROUPING_INGROUP)
    {
      warn(root->fileName, root->startLine,
          "Found non-existing group '%s' for the command '%s', ignoring command",
          qPrint(g.groupname), Grouping::getGroupPriName( g.pri )
          );
    }
  }
}
References GroupDef::addConcept(), Entry::fileName, LinkedMap< T, Hash, KeyEqual, Map >::find(), Grouping::getGroupPriName(), Grouping::GROUPING_INGROUP, Doxygen::groupLinkedMap, Entry::groups, DefinitionMutable::makePartOfGroup(), qPrint(), Entry::startLine, toConceptDefMutable(), and warn.
Referenced by addConceptToContext().
addDirToGroups()
void addDirToGroups (const Entry * root, DirDef * dd)
Definition at line 1507 of file groupdef.cpp.
{
  //printf("*** root->groups.size()=%d\n",root->groups.size());
  for (const Grouping &g : root->groups)
  {
    GroupDef *gd = Doxygen::groupLinkedMap->find(g.groupname);
    //printf("group '%s'\n",qPrint(g->groupname));
    if (gd)
    {
      gd->addDir(dd);
      dd->makePartOfGroup(gd);
      //printf("Dir %s: in group %s\n",qPrint(dd->name()),qPrint(g->groupname));
    }
    else if (!gd && g.pri == Grouping::GROUPING_INGROUP)
    {
      warn(root->fileName, root->startLine,
          "Found non-existing group '%s' for the command '%s', ignoring command",
          qPrint(g.groupname), Grouping::getGroupPriName( g.pri )
          );
    }
  }
}
References GroupDef::addDir(), Entry::fileName, LinkedMap< T, Hash, KeyEqual, Map >::find(), Grouping::getGroupPriName(), Grouping::GROUPING_INGROUP, Doxygen::groupLinkedMap, Entry::groups, DefinitionMutable::makePartOfGroup(), qPrint(), Entry::startLine, and warn.
Referenced by findDirDocumentation().
addExampleToGroups()
void addExampleToGroups (const Entry * root, PageDef * eg)
Definition at line 1691 of file groupdef.cpp.
{
  for (const Grouping &g : root->groups)
  {
    GroupDef *gd = Doxygen::groupLinkedMap->find(g.groupname);
    if (gd)
    {
      gd->addExample(eg);
      eg->makePartOfGroup(gd);
      //printf("Example %s: in group %s\n",qPrint(eg->name()),s->data());
    }
    else if (!gd && g.pri == Grouping::GROUPING_INGROUP)
    {
      warn(root->fileName, root->startLine,
          "Found non-existing group '%s' for the command '%s', ignoring command",
          qPrint(g.groupname), Grouping::getGroupPriName( g.pri )
          );
    }
  }
}
References GroupDef::addExample(), Entry::fileName, LinkedMap< T, Hash, KeyEqual, Map >::find(), Grouping::getGroupPriName(), Grouping::GROUPING_INGROUP, Doxygen::groupLinkedMap, Entry::groups, DefinitionMutable::makePartOfGroup(), qPrint(), Entry::startLine, and warn.
addGroupToGroups()
void addGroupToGroups (const Entry * root, GroupDef * subGroup)
Definition at line 1530 of file groupdef.cpp.
{
  //printf("addGroupToGroups for %s groups=%d\n",qPrint(root->name),root->groups.size());
  for (const Grouping &g : root->groups)
  {
    GroupDef *gd = Doxygen::groupLinkedMap->find(g.groupname);
    if (gd)
    {
      if (gd==subGroup)
      {
        warn(root->fileName,root->startLine,"Refusing to add group %s to itself",
            qPrint(gd->name()));
      }
      else if (subGroup->findGroup(gd))
      {
        warn(root->fileName,root->startLine,"Refusing to add group %s to group %s, since the latter is already a "
                                            "subgroup of the former", qPrint(subGroup->name()),qPrint(gd->name()));
      }
      else if (!gd->findGroup(subGroup))
      {
        gd->addGroup(subGroup);
        subGroup->makePartOfGroup(gd);
      }
    }
    else if (!gd && g.pri == Grouping::GROUPING_INGROUP)
    {
      warn(root->fileName, root->startLine,
          "Found non-existing group '%s' for the command '%s', ignoring command",
          qPrint(g.groupname), Grouping::getGroupPriName( g.pri )
          );
    }
  }
}
References GroupDef::addGroup(), Entry::fileName, LinkedMap< T, Hash, KeyEqual, Map >::find(), GroupDef::findGroup(), Grouping::getGroupPriName(), Grouping::GROUPING_INGROUP, Doxygen::groupLinkedMap, Entry::groups, DefinitionMutable::makePartOfGroup(), Definition::name(), qPrint(), Entry::startLine, and warn.
Referenced by organizeSubGroupsFiltered().
addMemberToGroups()
void addMemberToGroups (const Entry * root, MemberDef * md)
Add a member to the group with the highest priority
Definition at line 1565 of file groupdef.cpp.
{
  //printf("addMemberToGroups:  Root %p = %s, md %p=%s groups=%zu\n",
  //    root, qPrint(root->name), md, qPrint(md->name()), root->groups.size() );
  // Search entry's group list for group with highest pri.
  Grouping::GroupPri_t pri = Grouping::GROUPING_LOWEST;
  GroupDef *fgd=nullptr;
  for (const Grouping &g : root->groups)
  {
    GroupDef *gd=nullptr;
    if (!g.groupname.isEmpty()) gd=Doxygen::groupLinkedMap->find(g.groupname);
    if (gd && g.pri >= pri)
    {
      if (fgd && gd!=fgd && g.pri==pri)
      {
        warn(root->fileName, root->startLine,
            "Member %s found in multiple %s groups! "
            "The member will be put in group %s, and not in group %s",
            qPrint(md->name()), Grouping::getGroupPriName( pri ),
            qPrint(gd->name()), qPrint(fgd->name())
            );
      }
      fgd = gd;
      pri = g.pri;
    }
    else if (!gd && g.pri == Grouping::GROUPING_INGROUP)
    {
      warn(root->fileName, root->startLine,
          "Found non-existing group '%s' for the command '%s', ignoring command",
          qPrint(g.groupname), Grouping::getGroupPriName( g.pri )
          );
    }
  }
  //printf("fgd=%p\n",fgd);
  // put member into group defined by this entry?
  if (fgd)
  {
    GroupDef *mgd = const_cast<GroupDef*>(md->getGroupDef());
    //printf("mgd=%p\n",mgd);
    bool insertit = FALSE;
    if (mgd==nullptr)
    {
      insertit = TRUE;
    }
    else if (mgd!=fgd)
    {
      bool moveit = FALSE;
      // move member from one group to another if
      // - the new one has a higher priority
      // - the new entry has the same priority, but with docs where the old one had no docs
      if (md->getGroupPri()<pri)
      {
        moveit = TRUE;
      }
      else
      {
        if (md->getGroupPri()==pri)
        {
          if (!root->doc.isEmpty() && !md->getGroupHasDocs())
          {
            moveit = TRUE;
          }
          else if (!root->doc.isEmpty() && md->getGroupHasDocs())
          {
            warn(md->getGroupFileName(),md->getGroupStartLine(),
                "Member documentation for %s found several times in %s groups!\n"
                "%s:%d: The member will remain in group %s, and won't be put into group %s",
                qPrint(md->name()), Grouping::getGroupPriName( pri ),
                qPrint(root->fileName), root->startLine,
                qPrint(mgd->name()),
                qPrint(fgd->name())
                );
          }
        }
      }
      if (moveit)
      {
        //printf("removeMember\n");
        mgd->removeMember(md);
        insertit = TRUE;
      }
    }
    if (insertit)
    {
      //printf("insertMember found at %s line %d: %s: related %s\n",
      //    qPrint(md->getDefFileName()),md->getDefLine(),
      //    qPrint(md->name()),qPrint(root->relates));
      bool success = fgd->insertMember(md);
      if (success)
      {
        MemberDefMutable *mdm = toMemberDefMutable(md);
        if (mdm)
        {
          //printf("insertMember successful\n");
          mdm->setGroupDef(fgd,pri,root->fileName,root->startLine,!root->doc.isEmpty());
          ClassDefMutable *cdm = toClassDefMutable(mdm->getClassDefOfAnonymousType());
          if (cdm)
          {
            cdm->setGroupDefForAllMembers(fgd,pri,root->fileName,root->startLine,root->doc.length() != 0);
          }
          if (mdm->isEnumerate() && mdm->getGroupDef() && md->isStrong())
          {
            for (const auto &emd : mdm->enumFieldList())
            {
              MemberDefMutable *emdm = toMemberDefMutable(emd);
              if (emdm && emdm->getGroupDef()==nullptr)
              {
                emdm->setGroupDef(mdm->getGroupDef(),mdm->getGroupPri(),
                                 mdm->getGroupFileName(),mdm->getGroupStartLine(),
                                 mdm->getGroupHasDocs());
              }
            }
          }
        }
      }
    }
  }
}
References Entry::doc, MemberDef::enumFieldList(), FALSE, Entry::fileName, MemberDef::getClassDefOfAnonymousType(), MemberDef::getGroupDef(), MemberDef::getGroupFileName(), MemberDef::getGroupHasDocs(), MemberDef::getGroupPri(), Grouping::getGroupPriName(), MemberDef::getGroupStartLine(), Grouping::GROUPING_INGROUP, Grouping::GROUPING_LOWEST, Doxygen::groupLinkedMap, Entry::groups, GroupDef::insertMember(), QCString::isEmpty(), MemberDef::isEnumerate(), MemberDef::isStrong(), QCString::length(), Definition::name(), qPrint(), GroupDef::removeMember(), MemberDefMutable::setGroupDef(), ClassDefMutable::setGroupDefForAllMembers(), Entry::startLine, toClassDefMutable(), toMemberDefMutable(), TRUE, and warn.
Referenced by addDefineDoc(), addEnumDocs(), addMemberDocs(), addVariableToClass(), addVariableToFile(), findEnums(), and findMember().
addModuleToGroups()
void addModuleToGroups (const Entry * root, ModuleDef * mod)
Definition at line 1459 of file groupdef.cpp.
{
  for (const Grouping &g : root->groups)
  {
    GroupDef *gd = Doxygen::groupLinkedMap->find(g.groupname);
    if (gd && gd->addModule(mod))
    {
      mod->makePartOfGroup(gd);
      //printf("Module %s: in group %s\n",qPrint(mod->name()),gd->groupTitle());
    }
    else if (!gd && g.pri == Grouping::GROUPING_INGROUP)
    {
      warn(root->fileName, root->startLine,
          "Found non-existing group '%s' for the command '%s', ignoring command",
          qPrint(g.groupname), Grouping::getGroupPriName( g.pri )
          );
    }
  }
}
References GroupDef::addModule(), Entry::fileName, LinkedMap< T, Hash, KeyEqual, Map >::find(), Grouping::getGroupPriName(), Grouping::GROUPING_INGROUP, Doxygen::groupLinkedMap, Entry::groups, DefinitionMutable::makePartOfGroup(), qPrint(), Entry::startLine, and warn.
Referenced by ModuleManager::addDocs().
addNamespaceToGroups()
void addNamespaceToGroups (const Entry * root, NamespaceDef * nd)
Definition at line 1480 of file groupdef.cpp.
{
  //printf("root->groups.size()=%zu\n",root->groups.size());
  for (const Grouping &g : root->groups)
  {
    GroupDef *gd=nullptr;
    if (!g.groupname.isEmpty()) gd=Doxygen::groupLinkedMap->find(g.groupname);
    //printf("group '%s' gd=%p\n",qPrint(g.groupname),(void*)gd);
    if (gd && gd->addNamespace(nd))
    {
      NamespaceDefMutable *ndm = toNamespaceDefMutable(nd);
      if (ndm)
      {
        ndm->makePartOfGroup(gd);
      }
      //printf("Namespace %s: in group %s\n",qPrint(nd->name()),qPrint(gd->name()));
    }
    else if (!gd && g.pri == Grouping::GROUPING_INGROUP)
    {
      warn(root->fileName, root->startLine,
          "Found non-existing group '%s' for the command '%s', ignoring command",
          qPrint(g.groupname), Grouping::getGroupPriName( g.pri )
          );
    }
  }
}
References GroupDef::addNamespace(), Entry::fileName, Grouping::getGroupPriName(), Grouping::GROUPING_INGROUP, Doxygen::groupLinkedMap, Entry::groups, DefinitionMutable::makePartOfGroup(), qPrint(), Entry::startLine, toNamespaceDefMutable(), and warn.
Referenced by buildNamespaceList().
createGroupDef()
std::unique_ptr< GroupDef > createGroupDef (const QCString & fileName, int line, const QCString & name, const QCString & title, const QCString & refFileName)
Definition at line 173 of file groupdef.cpp.
{
  return std::make_unique<GroupDefImpl>(fileName,line,name,title,refFileName);
}
Referenced by buildGroupListFiltered().
groupClassesWithSameScope()
template<class Vec > static void groupClassesWithSameScope (Vec & vec) static
Definition at line 1755 of file groupdef.cpp.
{
  bool done=false;
  while (!done) // for each iteration
  {
    done=true;
    for (size_t i=0; i<vec.size(); i++) // go through all items
    {
      std::string qni = vec[i]->name().str();
      size_t posi = qni.rfind("::");
      if (posi!=std::string::npos)
      {
        std::string scope = qni.substr(0,posi);
        auto it = std::find_if( vec.begin(), vec.end(),
            [&](typename Vec::Ptr &cd)
            { return cd->name().str()==scope; });
        if (it!=vec.end())
        {
          size_t idx = std::distance(vec.begin(),it);
          if (i<idx) // parent scope located after child scope
          {
            // to avoid reordering elements with the same parent
            // we skip to the last one with the same scope
            size_t k = idx;
            while (k<vec.size() && vec[k]->name().str().substr(0,posi)==scope)
            {
              idx = k;
              k++;
            }
            // swap the items such that i is inserted after idx
            for (size_t j=i; j<idx; j++)
            {
              std::swap(vec[j],vec[j+1]);
            }
            done=false;
          }
          else if (idx<i && vec[i-1]->name().str().substr(0,posi)!=scope)
          {
            // parent scope is found before the item, and the item
            // has some other item with a different scope in front of it
            // move idx to the end of range with the same scope
            while (idx<i && vec[idx]->name().str().substr(0,posi)==scope)
            {
              idx++;
            }
            // swap the items such that i is just after idx
            for (size_t j=idx; j<i; j++)
            {
              std::swap(vec[j],vec[j+1]);
            }
            done=false;
          }
        }
      }
    }
  }
}
Referenced by GroupDefImpl::sortMemberLists().
hasNonReferenceNestedGroupRec()
static bool hasNonReferenceNestedGroupRec (const GroupDef * gd, int level) static
Definition at line 1893 of file groupdef.cpp.
{
  if (level>30)
  {
    err("Possible recursive group relation while inside %s\n",qPrint(gd->name()));
    return false;
  }
  bool found=gd->isLinkableInProject();
  if (found)
  {
    return true;
  }
  else
  {
    for (const auto &igd : gd->getSubGroups())
    {
      found = found || hasNonReferenceNestedGroupRec(igd,level+1);
      if (found) break;
    }
  }
  return found;
}
References err, found, GroupDef::getSubGroups(), hasNonReferenceNestedGroupRec(), GroupDef::isLinkableInProject(), Definition::name(), and qPrint().
Referenced by hasNonReferenceNestedGroupRec(), and GroupDefImpl::isVisibleInHierarchy().
toGroupDef() [1/2]
const GroupDef * toGroupDef (const Definition * d)
Definition at line 1976 of file groupdef.cpp.
{
  if (d==nullptr) return nullptr;
  if (d && typeid(*d)==typeid(GroupDefImpl))
  {
    return static_cast<const GroupDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
toGroupDef() [2/2]
GroupDef * toGroupDef (Definition * d)
Definition at line 1963 of file groupdef.cpp.
{
  if (d==nullptr) return nullptr;
  if (d && typeid(*d)==typeid(GroupDefImpl))
  {
    return static_cast<GroupDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
Referenced by DocRef::DocRef(), generateLink(), DocParser::handleLinkedWord(), SearchTerm::makeTitle(), DefinitionImpl::navigationPathAsString(), DefinitionImpl::pathFragment(), SearchIndex::setCurrentDoc(), SearchIndexExternal::setCurrentDoc(), validatingParseDoc(), MemberDefImpl::writeDocumentation(), and writeJavasScriptSearchDataPage().