Doxygen: src/htmlhelp.cpp File Reference
htmlhelp.cpp File Reference
#include <algorithm>
#include <stdio.h>
#include <stdlib.h>
#include "htmlhelp.h"
#include "config.h"
#include "message.h"
#include "doxygen.h"
#include "language.h"
#include "portable.h"
#include "groupdef.h"
#include "memberdef.h"
#include "filedef.h"
#include "util.h"
#include "linkedmap.h"
#include "regex.h"
#include "fileinfo.h"
Classes
class HtmlHelpRecoder
Helper class to deal with recoding the UTF8 encoded text back to the native encoding specified by CHM_INDEX_ENCODING.
struct IndexField
Class representing a field in the HTML help index.
class HtmlHelpIndex
A helper class for HtmlHelp that manages a two level index in alphabetical order.
class HtmlHelp::Private
Functions
static QCString field2URL (const IndexField *f, bool checkReversed)
static QCString convertToHtmlAndTruncate (const QCString &s)
Function Documentation
convertToHtmlAndTruncate()
static QCString convertToHtmlAndTruncate (const QCString & s) static
Definition at line 185 of file htmlhelp.cpp.
{
  /* to prevent
   *  Warning: Keyword string:
   *    ...
   *  is too long.  The maximum size is 488 characters.
   */
  int maxLen = 400;
  size_t maxExpandedLen = maxLen+50;
  QCString result = convertToHtml(s,true);
  if (result.length()>maxExpandedLen) // we need to truncate the string
  {
    // in the unlikely case that the string after conversion grows from maxLen to maxExpandedLen, we try smaller parts
    // until we end up below the limit
    while (maxLen>0 && result.length()>maxExpandedLen)
    {
      result = convertToHtml(s.left(maxLen));
      maxLen-=20;
    }
    return result+"...";
  }
  else
  {
    return result;
  }
}
References convertToHtml(), QCString::left(), and QCString::length().
Referenced by HtmlHelpIndex::writeFields().
field2URL()
static QCString field2URL (const IndexField * f, bool checkReversed) static
Definition at line 174 of file htmlhelp.cpp.
{
  QCString result = f->url;
  addHtmlExtensionIfMissing(result);
  if (!f->anchor.isEmpty() && (!checkReversed || f->reversed))
  {
    result+="#"+f->anchor;
  }
  return result;
}
References addHtmlExtensionIfMissing(), IndexField::anchor, QCString::isEmpty(), IndexField::reversed, and IndexField::url.
Referenced by HtmlHelpIndex::writeFields().