Doxygen: COutlineParser Class Reference
COutlineParser Class Reference
C-like language parser using state-based lexical scanning.
#include <src/scanner.h>
Classes
struct Private
Public Member Functions
COutlineParser ()
COutlineParser (const COutlineParser &)=delete
COutlineParser & operator= (COutlineParser &)=delete
COutlineParser (COutlineParser &&)=delete
COutlineParser & operator= (COutlineParser &&)=delete
~COutlineParser () override
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser) override
Parses a single input file with the goal to build an Entry tree.
bool needsPreprocessing (const QCString &extension) const override
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
void parsePrototype (const QCString &text) override
Callback function called by the comment block scanner.
Public Member Functions inherited from OutlineParserInterface
Private Attributes
std::unique_ptr< Private > p
Detailed Description
C-like language parser using state-based lexical scanning.
This is the language parser for doxygen. It is somewhat fuzzy and supports C++ and various languages that are closely related to C++, such as C, C#, Objective-C, Java, PHP, and IDL.
Definition at line 29 of file scanner.h.
Constructor & Destructor Documentation
COutlineParser() [1/3]
COutlineParser::COutlineParser ()
Definition at line 8334 of file scanner.l.
                               : p(std::make_unique<COutlineParser::Private>())
{
  scannerYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  scannerYYset_debug(Debug::isFlagSet(Debug::Lex_scanner)?1:0,p->yyscanner);
#endif
}
References COutlineParser(), Debug::isFlagSet(), Debug::Lex_scanner, and p.
Referenced by COutlineParser(), COutlineParser(), COutlineParser(), operator=(), and operator=().
COutlineParser() [2/3]
COutlineParser::COutlineParser (const COutlineParser &) delete
References COutlineParser().
COutlineParser() [3/3]
COutlineParser::COutlineParser (COutlineParser &&) delete
References COutlineParser().
~COutlineParser()
COutlineParser::~COutlineParser () override
Definition at line 8342 of file scanner.l.
{
  scannerYYlex_destroy(p->yyscanner);
}
References p.
Member Function Documentation
needsPreprocessing()
bool COutlineParser::needsPreprocessing (const QCString & extension) const override virtual
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 8362 of file scanner.l.
{
  QCString fe=extension.lower();
  SrcLangExt lang = getLanguageFromFileName(extension);
  return (SrcLangExt::Cpp == lang) || (SrcLangExt::Lex == lang) ||
   !( fe==".java" || fe==".as"  || fe==".d"    || fe==".php" ||
      fe==".php4" || fe==".inc" || fe==".phtml"|| fe==".php5"
    );
}
References Cpp, getLanguageFromFileName(), Lex, and QCString::lower().
operator=() [1/2]
COutlineParser & COutlineParser::operator= (COutlineParser &&) delete
References COutlineParser().
operator=() [2/2]
COutlineParser & COutlineParser::operator= (COutlineParser &) delete
References COutlineParser().
parseInput()
void COutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) override virtual
Parses a single input file with the goal to build an Entry tree.
Parameters
[in] fileName The full name of the file.
[in] fileBuf The contents of the file (zero terminated).
[in,out] root The root of the tree of Entry *nodes representing the information extracted from the file.
[in] clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
Definition at line 8347 of file scanner.l.
{
  AUTO_TRACE();
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->thisParser = this;
  DebugLex debugLex(Debug::Lex_scanner, __FILE__, qPrint(fileName));
  ::parseMain(p->yyscanner,fileName,fileBuf,root,clangParser);
}
References AUTO_TRACE, Debug::Lex_scanner, p, parseMain(), and qPrint().
parsePrototype()
void COutlineParser::parsePrototype (const QCString & text) override virtual
Callback function called by the comment block scanner.
It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Definition at line 8372 of file scanner.l.
{
  ::parsePrototype(p->yyscanner,text);
}
References p, and parsePrototype().
Referenced by parsePrototype().
Member Data Documentation
p
std::unique_ptr<Private> COutlineParser::p private
Definition at line 46 of file scanner.h.
Referenced by COutlineParser(), parseInput(), parsePrototype(), and ~COutlineParser().
The documentation for this class was generated from the following files:
src/scanner.h
src/scanner.l