Doxygen: RTFCodeGenerator Class Reference
RTFCodeGenerator Class Reference
Generator for RTF code fragments.
#include <src/rtfgen.h>
Public Member Functions
RTFCodeGenerator (TextStream *t)
void setTextStream (TextStream *t)
OutputType type () const override
void codify (const QCString &text) override
void stripCodeComments (bool b) override
void startSpecialComment () override
void endSpecialComment () override
void setStripIndentAmount (size_t amount) override
std::unique_ptr< OutputCodeIntf > clone () override
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip) override
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &) override
void writeLineNumber (const QCString &, const QCString &, const QCString &, int l, bool) override
void startCodeLine (int) override
void endCodeLine () override
void startFontClass (const QCString &) override
void endFontClass () override
void writeCodeAnchor (const QCString &) override
void startCodeFragment (const QCString &style) override
void endCodeFragment (const QCString &) override
void startFold (int, const QCString &, const QCString &) override
void endFold () override
Public Member Functions inherited from OutputCodeIntf
OutputCodeIntf ()=default
Private Member Functions
void setSourceFileName (const QCString &name)
void setIndentLevel (int level)
QCString rtf_Code_DepthStyle ()
Private Attributes
size_t m_col = 0
TextStream * m_t
bool m_doxyCodeLineOpen = false
QCString m_sourceFileName
int m_indentLevel = 0
bool m_stripCodeComments = false
bool m_hide = false
size_t m_stripIndentAmount = 0
Friends
class RTFGenerator
Detailed Description
Generator for RTF code fragments.
Definition at line 27 of file rtfgen.h.
Constructor & Destructor Documentation
RTFCodeGenerator()
RTFCodeGenerator::RTFCodeGenerator (TextStream * t)
Definition at line 114 of file rtfgen.cpp.
                                                : m_t(t)
{
}
References m_t.
Member Function Documentation
clone()
std::unique_ptr< OutputCodeIntf > RTFCodeGenerator::clone () inline override virtual
Implements OutputCodeIntf.
Definition at line 39 of file rtfgen.h.
{ return std::make_unique<RTFCodeGenerator>(*this); }
codify()
void RTFCodeGenerator::codify (const QCString & text) override virtual
Implements OutputCodeIntf.
Definition at line 153 of file rtfgen.cpp.
{
  // note that RTF does not have a "verbatim", so "\n" means
  // nothing... add a "newParagraph()";
  const int tabSize = Config_getInt(TAB_SIZE);
  if (!str.isEmpty())
  {
    char c;
    const char *p=str.data();
    if (m_hide)
    {
      m_col = updateColumnCount(p,m_col);
    }
    else
    {
      while ((c=*p++))
      {
        switch(c)
        {
          case '\t':  {
                        int spacesToNextTabStop = tabSize - (m_col%tabSize);
                        while (spacesToNextTabStop--)
{
                          if (m_col>=m_stripIndentAmount) *m_t << " ";
                          m_col++;
                        }
                      }
                      break;
          case ' ':   if (m_col>=m_stripIndentAmount) *m_t << " ";
                      m_col++;
                      break;
          case '\n':  *m_t << "\\par\n";
                      m_col=0;
                      break;
          case '{':   *m_t << "\\{"; m_col++;          break;
          case '}':   *m_t << "\\}"; m_col++;          break;
          case '\\':  *m_t << "\\\\"; m_col++;         break;
          default:    p=writeUTF8Char(*m_t,p-1); m_col++; break;
        }
      }
    }
  }
}
References Config_getInt, QCString::data(), QCString::isEmpty(), m_col, m_hide, m_stripIndentAmount, m_t, updateColumnCount(), and writeUTF8Char().
Referenced by writeCodeLink().
endCodeFragment()
void RTFCodeGenerator::endCodeFragment (const QCString &) override virtual
Implements OutputCodeIntf.
Definition at line 225 of file rtfgen.cpp.
{
  endCodeLine();
  DBG_RTF(*m_t << "{\\comment (endCodeFragment) }\n")
  *m_t << "}\n";
  //m_omitParagraph = TRUE;
}
References DBG_RTF, endCodeLine(), and m_t.
endCodeLine()
void RTFCodeGenerator::endCodeLine () override virtual
Implements OutputCodeIntf.
Definition at line 285 of file rtfgen.cpp.
{
  if (m_hide) return;
  if (m_doxyCodeLineOpen) *m_t << "\\par\n";
  m_doxyCodeLineOpen = false;
}
References m_doxyCodeLineOpen, m_hide, and m_t.
Referenced by endCodeFragment().
endFold()
void RTFCodeGenerator::endFold () inline override virtual
Implements OutputCodeIntf.
Definition at line 60 of file rtfgen.h.
{}
endFontClass()
void RTFCodeGenerator::endFontClass () override virtual
Implements OutputCodeIntf.
Definition at line 317 of file rtfgen.cpp.
{
  if (m_hide) return;
  *m_t << "}";
}
References m_hide, and m_t.
endSpecialComment()
void RTFCodeGenerator::endSpecialComment () override virtual
Implements OutputCodeIntf.
Definition at line 207 of file rtfgen.cpp.
{
  m_hide = false;
}
References m_hide.
rtf_Code_DepthStyle()
QCString RTFCodeGenerator::rtf_Code_DepthStyle () private
Definition at line 323 of file rtfgen.cpp.
{
  QCString n=makeIndexName("CodeExample",m_indentLevel);
  return rtf_Style[n.str()].reference();
}
References m_indentLevel, makeIndexName(), rtf_Style, and QCString::str().
Referenced by startCodeFragment().
setIndentLevel()
void RTFCodeGenerator::setIndentLevel (int level) inline private
Definition at line 65 of file rtfgen.h.
{ m_indentLevel=level; }
References m_indentLevel.
setSourceFileName()
void RTFCodeGenerator::setSourceFileName (const QCString & name) private
Definition at line 329 of file rtfgen.cpp.
{
  m_sourceFileName = name;
}
References m_sourceFileName.
setStripIndentAmount()
void RTFCodeGenerator::setStripIndentAmount (size_t amount) override virtual
Implements OutputCodeIntf.
Definition at line 212 of file rtfgen.cpp.
{
  m_stripIndentAmount = amount;
}
References m_stripIndentAmount.
setTextStream()
void RTFCodeGenerator::setTextStream (TextStream * t) inline
Definition at line 31 of file rtfgen.h.
{ m_t = t; }
References m_t.
startCodeFragment()
void RTFCodeGenerator::startCodeFragment (const QCString & style) override virtual
Implements OutputCodeIntf.
Definition at line 217 of file rtfgen.cpp.
{
  DBG_RTF(*m_t << "{\\comment (startCodeFragment) }\n")
  *m_t << "{\n";
  *m_t << "\\par\n";
  *m_t << rtf_Style_Reset << rtf_Code_DepthStyle();
}
References DBG_RTF, m_t, rtf_Code_DepthStyle(), and rtf_Style_Reset.
startCodeLine()
void RTFCodeGenerator::startCodeLine (int) override virtual
Implements OutputCodeIntf.
Definition at line 278 of file rtfgen.cpp.
{
  if (m_hide) return;
  m_doxyCodeLineOpen = true;
  m_col=0;
}
References m_col, m_doxyCodeLineOpen, and m_hide.
startFold()
void RTFCodeGenerator::startFold (int , const QCString & , const QCString &) inline override virtual
Implements OutputCodeIntf.
Definition at line 59 of file rtfgen.h.
{}
startFontClass()
void RTFCodeGenerator::startFontClass (const QCString & name) override virtual
Implements OutputCodeIntf.
Definition at line 292 of file rtfgen.cpp.
{
  if (m_hide) return;
  int cod = 2;
  static const std::unordered_map<std::string,int> map {
   { "keyword",       17 },
   { "keywordtype",   18 },
   { "keywordflow",   19 },
   { "comment",       20 },
   { "preprocessor",  21 },
   { "stringliteral", 22 },
   { "charliteral",   23 },
   { "vhdldigit",     24 },
   { "vhdlchar",      25 },
   { "vhdlkeyword",   26 },
   { "vhdllogic",     27 }
  };
  auto it = map.find(name.str());
  if (it != map.end())
  {
    cod = it->second;
  }
  *m_t << "{\\cf" << cod << " ";
}
References m_hide, m_t, and QCString::str().
startSpecialComment()
void RTFCodeGenerator::startSpecialComment () override virtual
Implements OutputCodeIntf.
Definition at line 202 of file rtfgen.cpp.
{
  m_hide = m_stripCodeComments;
}
References m_hide, and m_stripCodeComments.
stripCodeComments()
void RTFCodeGenerator::stripCodeComments (bool b) override virtual
Implements OutputCodeIntf.
Definition at line 197 of file rtfgen.cpp.
{
  m_stripCodeComments = b;
}
References m_stripCodeComments.
type()
OutputType RTFCodeGenerator::type () const inline override virtual
Implements OutputCodeIntf.
Definition at line 33 of file rtfgen.h.
{ return OutputType::RTF; }
References RTF.
writeCodeAnchor()
void RTFCodeGenerator::writeCodeAnchor (const QCString &) inline override virtual
Implements OutputCodeIntf.
Definition at line 56 of file rtfgen.h.
{}
writeCodeLink()
void RTFCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) override virtual
Implements OutputCodeIntf.
Definition at line 118 of file rtfgen.cpp.
{
  m_col+=name.length();
  if (m_hide) return;
  if (ref.isEmpty() && Config_getBool(RTF_HYPERLINKS))
  {
    QCString refName;
    if (!f.isEmpty())
    {
      refName+=stripPath(f);
    }
    if (!anchor.isEmpty())
    {
      refName+='_';
      refName+=anchor;
    }
    *m_t << "{\\field {\\*\\fldinst { HYPERLINK  \\\\l \"";
    *m_t << rtfFormatBmkStr(refName);
    *m_t << "\" }{}";
    *m_t << "}{\\fldrslt {\\cs37\\ul\\cf2 ";
    codify(name);
    *m_t << "}}}\n";
  }
  else
  {
    codify(name);
  }
}
References codify(), Config_getBool, QCString::isEmpty(), QCString::length(), m_col, m_hide, m_t, rtfFormatBmkStr(), and stripPath().
Referenced by writeLineNumber().
writeLineNumber()
void RTFCodeGenerator::writeLineNumber (const QCString & ref, const QCString & fileName, const QCString & anchor, int l, bool writeLineAnchor) override virtual
Implements OutputCodeIntf.
Definition at line 234 of file rtfgen.cpp.
{
  if (m_hide) return;
  bool rtfHyperlinks = Config_getBool(RTF_HYPERLINKS);
  m_doxyCodeLineOpen = true;
  if (Config_getBool(SOURCE_BROWSER))
  {
    QCString lineNumber;
    lineNumber.sprintf("%05d",l);
    QCString lineAnchor;
    if (!m_sourceFileName.isEmpty())
    {
      lineAnchor.sprintf("_l%05d",l);
      lineAnchor.prepend(stripExtensionGeneral(stripPath(m_sourceFileName), ".rtf"));
    }
    bool showTarget = rtfHyperlinks && !lineAnchor.isEmpty() && writeLineAnchor;
    if (showTarget)
    {
        *m_t << "{\\bkmkstart ";
        *m_t << rtfFormatBmkStr(lineAnchor);
        *m_t << "}";
        *m_t << "{\\bkmkend ";
        *m_t << rtfFormatBmkStr(lineAnchor);
        *m_t << "}\n";
    }
    if (!fileName.isEmpty())
    {
      writeCodeLink(CodeSymbolType::Default,ref,fileName,anchor,lineNumber,QCString());
    }
    else
    {
      *m_t << lineNumber;
    }
    *m_t << " ";
  }
  else
  {
    *m_t << l << " ";
  }
  m_col=0;
}
References Config_getBool, Default, QCString::isEmpty(), m_col, m_doxyCodeLineOpen, m_hide, m_sourceFileName, m_t, QCString::prepend(), rtfFormatBmkStr(), QCString::sprintf(), stripExtensionGeneral(), stripPath(), and writeCodeLink().
writeTooltip()
void RTFCodeGenerator::writeTooltip (const QCString & , const DocLinkInfo & , const QCString & , const QCString & , const SourceLinkInfo & , const SourceLinkInfo &) inline override virtual
Implements OutputCodeIntf.
Definition at line 44 of file rtfgen.h.
                                {}
Friends And Related Symbol Documentation
RTFGenerator
friend class RTFGenerator friend
Definition at line 63 of file rtfgen.h.
References RTFGenerator.
Referenced by RTFGenerator.
Member Data Documentation
m_col
size_t RTFCodeGenerator::m_col = 0 private
Definition at line 67 of file rtfgen.h.
Referenced by codify(), startCodeLine(), writeCodeLink(), and writeLineNumber().
m_doxyCodeLineOpen
bool RTFCodeGenerator::m_doxyCodeLineOpen = false private
Definition at line 69 of file rtfgen.h.
Referenced by endCodeLine(), startCodeLine(), and writeLineNumber().
m_hide
bool RTFCodeGenerator::m_hide = false private
Definition at line 73 of file rtfgen.h.
Referenced by codify(), endCodeLine(), endFontClass(), endSpecialComment(), startCodeLine(), startFontClass(), startSpecialComment(), writeCodeLink(), and writeLineNumber().
m_indentLevel
int RTFCodeGenerator::m_indentLevel = 0 private
Definition at line 71 of file rtfgen.h.
Referenced by rtf_Code_DepthStyle(), and setIndentLevel().
m_sourceFileName
QCString RTFCodeGenerator::m_sourceFileName private
Definition at line 70 of file rtfgen.h.
Referenced by setSourceFileName(), and writeLineNumber().
m_stripCodeComments
bool RTFCodeGenerator::m_stripCodeComments = false private
Definition at line 72 of file rtfgen.h.
Referenced by startSpecialComment(), and stripCodeComments().
m_stripIndentAmount
size_t RTFCodeGenerator::m_stripIndentAmount = 0 private
Definition at line 74 of file rtfgen.h.
Referenced by codify(), and setStripIndentAmount().
m_t
TextStream* RTFCodeGenerator::m_t private
Definition at line 68 of file rtfgen.h.
Referenced by codify(), endCodeFragment(), endCodeLine(), endFontClass(), RTFCodeGenerator(), setTextStream(), startCodeFragment(), startFontClass(), writeCodeLink(), and writeLineNumber().
The documentation for this class was generated from the following files:
src/rtfgen.h
src/rtfgen.cpp