Doxygen: ArgumentContext::Private Class Reference
ArgumentContext::Private Class Reference
Public Member Functions
Private (const Argument &arg, const Definition *def, const QCString &relPath)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant type () const
TemplateVariant attrib () const
TemplateVariant name () const
TemplateVariant defVal () const
TemplateVariant array () const
TemplateVariant docs () const
TemplateVariant namePart () const
TemplateVariant createType () const
TemplateVariant createDefval () const
TemplateVariant createDocs () const
Private Attributes
Argument m_argument
const Definition * m_def
QCString m_relPath
CachedItem< TemplateVariant, Private, &Private::createType > m_type
CachedItem< TemplateVariant, Private, &Private::createDefval > m_defval
CachedItem< TemplateVariant, Private, &Private::createDocs > m_docs
Static Private Attributes
static const PropertyMap< ArgumentContext::Private > s_inst
Detailed Description
Definition at line 8236 of file context.cpp.
Constructor & Destructor Documentation
Private()
ArgumentContext::Private::Private (const Argument & arg, const Definition * def, const QCString & relPath) inline
Definition at line 8239 of file context.cpp.
      : m_argument(arg), m_def(def), m_relPath(relPath) {}
Member Function Documentation
array()
TemplateVariant ArgumentContext::Private::array () const inline private
Definition at line 8252 of file context.cpp.
{ return m_argument.array; }
References Argument::array, and m_argument.
attrib()
TemplateVariant ArgumentContext::Private::attrib () const inline private
Definition at line 8249 of file context.cpp.
{ return m_argument.attrib; }
References Argument::attrib, and m_argument.
createDefval()
TemplateVariant ArgumentContext::Private::createDefval () const inline private
Definition at line 8271 of file context.cpp.
    {
      return createLinkedText(m_def,m_relPath,m_argument.defval);
    }
References createLinkedText(), Argument::defval, m_argument, m_def, and m_relPath.
createDocs()
TemplateVariant ArgumentContext::Private::createDocs () const inline private
Definition at line 8275 of file context.cpp.
    {
      return !m_argument.docs.isEmpty() ?
          TemplateVariant(parseDoc(m_def,m_def->docFile(),m_def->docLine(),m_relPath,m_argument.docs,TRUE)) :
          TemplateVariant("");
    }
References Definition::docFile(), Definition::docLine(), Argument::docs, QCString::isEmpty(), m_argument, m_def, m_relPath, parseDoc(), and TRUE.
createType()
TemplateVariant ArgumentContext::Private::createType () const inline private
Definition at line 8267 of file context.cpp.
    {
      return createLinkedText(m_def,m_relPath,m_argument.type);
    }
References createLinkedText(), m_argument, m_def, m_relPath, and Argument::type.
defVal()
TemplateVariant ArgumentContext::Private::defVal () const inline private
Definition at line 8251 of file context.cpp.
{ return m_defval.get(this); }
References m_defval.
docs()
TemplateVariant ArgumentContext::Private::docs () const inline private
Definition at line 8253 of file context.cpp.
{ return m_docs.get(this); }
References m_docs.
fields()
StringVector ArgumentContext::Private::fields () const inline
Definition at line 8244 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
get()
TemplateVariant ArgumentContext::Private::get (const QCString & n) const inline
Definition at line 8243 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), and s_inst.
name()
TemplateVariant ArgumentContext::Private::name () const inline private
Definition at line 8250 of file context.cpp.
{ return m_argument.name; }
References m_argument, and Argument::name.
namePart()
TemplateVariant ArgumentContext::Private::namePart () const inline private
Definition at line 8254 of file context.cpp.
    {
      QCString result = m_argument.attrib;
      size_t l = result.length();
      if (l>2 && result.at(0)=='[' && result.at(l-1)==']')
      {
        result = result.mid(1,l-2);
        if (result!=",") result+=":"; // for normal keywords add colon
      }
      return result;
    }
References QCString::at(), Argument::attrib, QCString::length(), m_argument, and QCString::mid().
type()
TemplateVariant ArgumentContext::Private::type () const inline private
Definition at line 8248 of file context.cpp.
{ return m_type.get(this); }
References m_type.
Member Data Documentation
m_argument
Argument ArgumentContext::Private::m_argument private
Definition at line 8281 of file context.cpp.
Referenced by array(), attrib(), createDefval(), createDocs(), createType(), name(), and namePart().
m_def
const Definition* ArgumentContext::Private::m_def private
Definition at line 8282 of file context.cpp.
Referenced by createDefval(), createDocs(), and createType().
m_defval
CachedItem<TemplateVariant, Private, &Private::createDefval> ArgumentContext::Private::m_defval private
Definition at line 8285 of file context.cpp.
Referenced by defVal().
m_docs
CachedItem<TemplateVariant, Private, &Private::createDocs> ArgumentContext::Private::m_docs private
Definition at line 8286 of file context.cpp.
Referenced by docs().
m_relPath
QCString ArgumentContext::Private::m_relPath private
Definition at line 8283 of file context.cpp.
Referenced by createDefval(), createDocs(), and createType().
m_type
CachedItem<TemplateVariant, Private, &Private::createType> ArgumentContext::Private::m_type private
Definition at line 8284 of file context.cpp.
Referenced by type().
s_inst
const PropertyMap< ArgumentContext::Private > ArgumentContext::Private::s_inst static private
Initial value:
{
  {  "type",     &Private::type },
  {  "name",     &Private::name },
  {  "defVal",   &Private::defVal },
  {  "docs",     &Private::docs },
  {  "attrib",   &Private::attrib },
  {  "array",    &Private::array },
  {  "namePart", &Private::namePart }
}
Definition at line 8287 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/context.cpp