Doxygen: TranslatorDutch Class Reference
TranslatorDutch Class Reference
#include <src/translator_nl.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trEnumerationValueDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description.
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool single) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
QCString trDesignUnitDocumentation () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
QCString trPackageList () override
QCString trFlowchart () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicIndex () override
QCString trTopicList () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
QCString trCopyToClipboard () override
QCString trImportant () override
Public Member Functions inherited from Translator
virtual QCString updateNeededMessage ()
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Detailed Description
Definition at line 21 of file translator_nl.h.
Member Function Documentation
getLanguageString()
QCString TranslatorDutch::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 41 of file translator_nl.h.
    {
      return "0x413 Dutch";
    }
idLanguage()
QCString TranslatorDutch::idLanguage () inline override virtual
Implements Translator.
Definition at line 24 of file translator_nl.h.
    { return "dutch"; }
latexLanguageSupportCommand()
QCString TranslatorDutch::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 37 of file translator_nl.h.
    { return "\\usepackage[dutch]{babel}\n"; }
trAdditionalInheritedMembers()
QCString TranslatorDutch::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1609 of file translator_nl.h.
    { return "Additionele Overgerfde Members"; }
trAll()
QCString TranslatorDutch::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1154 of file translator_nl.h.
    {
      return "Alle";
    }
trAndMore()
QCString TranslatorDutch::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1586 of file translator_nl.h.
    { return "en "+number+ " anderen..."; }
trAttention()
QCString TranslatorDutch::trAttention () inline override virtual
Implements Translator.
Definition at line 742 of file translator_nl.h.
    {
      return "Attentie";
    }
trAuthor()
QCString TranslatorDutch::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1033 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "auteur", "s");
    }
References Translator::createNoun().
trBug()
QCString TranslatorDutch::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 905 of file translator_nl.h.
    {
      return "Bug";
    }
trBugList()
QCString TranslatorDutch::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 910 of file translator_nl.h.
    {
      return "Bug Lijst";
    }
trCallerGraph()
QCString TranslatorDutch::trCallerGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1273 of file translator_nl.h.
    {
      return "Hier is de caller graaf voor deze functie:";
    }
trCallGraph()
QCString TranslatorDutch::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1159 of file translator_nl.h.
    {
      return "Hier is de call graaf voor deze functie:";
    }
trCiteReferences()
QCString TranslatorDutch::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1562 of file translator_nl.h.
    { return "Bibliografie"; }
trClass()
QCString TranslatorDutch::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 968 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "klasse", "n");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trClassDiagram()
QCString TranslatorDutch::trClassDiagram (const QCString & clName) inline override virtual
Implements Translator.
Definition at line 328 of file translator_nl.h.
    {
      return "Klasse diagram voor "+clName;
    }
trClassDocumentation()
QCString TranslatorDutch::trClassDocumentation () inline override virtual
Implements Translator.
Definition at line 266 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Klassen Documentatie";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassen Documentatie";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorDutch::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 868 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structuren";
      }
      else
      {
        return "Klassen";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorDutch::trClassHierarchy () inline override virtual
Implements Translator.
Definition at line 104 of file translator_nl.h.
    { return "Klasse Hirarchie"; }
trClassHierarchyDescription()
QCString TranslatorDutch::trClassHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 147 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Hieronder is een hirarchische lijst met alle entiteiten:";
      }
      else
      {
        return "Deze inheritance lijst is min of meer alfabetisch gesorteerd:";
      }
    }
References Config_getBool.
trClassMethods()
QCString TranslatorDutch::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1647 of file translator_nl.h.
    {
      return "Klasse Methoden";
    }
trCode()
QCString TranslatorDutch::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 641 of file translator_nl.h.
    {
      return "code";
    }
trCollaborationDiagram()
QCString TranslatorDutch::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 596 of file translator_nl.h.
    {
      return "Collaboratie diagram voor "+clName+":";
    }
trCompoundIndex()
QCString TranslatorDutch::trCompoundIndex () inline override virtual
Implements Translator.
Definition at line 251 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structuren Index";
      }
      else
      {
        return "Klasse Index";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorDutch::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1312 of file translator_nl.h.
    { return "Data Type Index"; }
trCompoundList()
QCString TranslatorDutch::trCompoundList () inline override virtual
Implements Translator.
Definition at line 106 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structuren Lijst";
      }
      else
      {
        return "Klasse Lijst";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorDutch::trCompoundListDescription () inline override virtual
Implements Translator.
Definition at line 165 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Hieronder volgen de structs "
               "met voor elk een korte beschrijving:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Hieronder volgen de klassen "
               "met voor elk een korte beschrijving:";
      }
      else
      {
        return "Hieronder volgen de klassen, structs en "
               "unions met voor elk een korte beschrijving:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorDutch::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1295 of file translator_nl.h.
    { return "Hieronder volgen de data types elk een korte beschrijving:"; }
trCompoundListFortran()
QCString TranslatorDutch::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1287 of file translator_nl.h.
    { return "Lijst met data types"; }
trCompoundMembers()
QCString TranslatorDutch::trCompoundMembers () inline override virtual
Implements Translator.
Definition at line 119 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Velden";
      }
      else
      {
        return "Klasse Members";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorDutch::trCompoundMembersDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 183 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct en union velden";
      }
      else
      {
        result+="klasse members";
      }
      result+=" met links naar ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="de struct/union documentatie voor elke veld:";
        }
        else
        {
           result+="de klasse documentatie voor elke member:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="de structures/unions waartoe ze behoren:";
        }
        else
        {
          result+="de klassen waartoe ze behoren:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorDutch::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1299 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="data types met links naar ";
      if (!extractAll) result+="de klasse documentatie voor elke member:";
      else result+="de klassen waartoe ze behoren:";
      return result;
    }
trCompoundMembersDescriptionTotal()
QCString TranslatorDutch::trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2079 of file translator_nl.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct en union velden";
      }
      else
      {
        result+="klasse members";
      }
      switch (hl)
      {
        case ClassMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="struct en union velden";
          }
          else
          {
            result+="klasse members";
          }
          break;
        case ClassMemberHighlight::Functions:
          result+="functies";
          break;
        case ClassMemberHighlight::Variables:
          result+="variabelen";
          break;
        case ClassMemberHighlight::Typedefs:
          result+="typedefs";
          break;
        case ClassMemberHighlight::Enums:
          result+="enumeraties";
          break;
        case ClassMemberHighlight::EnumValues:
          result+="enumeratie waarden";
          break;
        case ClassMemberHighlight::Properties:
          result+="properties";
          break;
        case ClassMemberHighlight::Events:
          result+="events";
          break;
        case ClassMemberHighlight::Related:
          result+="gerelateerde symbolen";
          break;
        case ClassMemberHighlight::Total: // for completeness
          break;
      }
      result+=" met links naar ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="de struct/union documentatie voor elke veld:";
        }
        else
        {
           result+="de klasse documentatie voor elke symbool:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="de structures/unions waartoe ze behoren:";
        }
        else
        {
          result+="de klassen waartoe ze behoren:";
        }
      }
      return result;
    }
References ClassMemberHighlight::All, Config_getBool, ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, ClassMemberHighlight::Properties, ClassMemberHighlight::Related, ClassMemberHighlight::Total, ClassMemberHighlight::Typedefs, and ClassMemberHighlight::Variables.
trCompoundMembersFortran()
QCString TranslatorDutch::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1291 of file translator_nl.h.
    { return "Data velden"; }
trCompoundReference()
QCString TranslatorDutch::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
Implements Translator.
Definition at line 376 of file translator_nl.h.
    {
      QCString result=clName;
      if (isTemplate) result+=" Template";
      switch(compType)
      {
        case ClassDef::Class:  result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union:  result+=" Union"; break;
        case ClassDef::Interface:  result+=" Interface"; break;
        case ClassDef::Protocol:  result+=" Protocol"; break;
        case ClassDef::Category:  result+=" Category"; break;
        case ClassDef::Exception:  result+=" Exception"; break;
        default: break;
      }
      result+=" Referentie";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorDutch::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1353 of file translator_nl.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Module"; break;
        case ClassDef::Struct:     result+=" Type"; break;
        case ClassDef::Union:      result+=" Union"; break;
        case ClassDef::Interface:  result+=" Interface"; break;
        case ClassDef::Protocol:   result+=" Protocol"; break;
        case ClassDef::Category:   result+=" Category"; break;
        case ClassDef::Exception:  result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Referentie";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice()
QCString TranslatorDutch::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) inline override virtual
Implements Translator.
Definition at line 1887 of file translator_nl.h.
    {
      QCString result=clName;
      if (isLocal) result+=" Lokale";
      switch(compType)
      {
        case ClassDef::Class:  result+=" Class"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union:  result+=" Union"; break;
        case ClassDef::Interface:  result+=" Interface"; break;
        case ClassDef::Protocol:  result+=" Protocol"; break;
        case ClassDef::Category:  result+=" Category"; break;
        case ClassDef::Exception:  result+=" Exception"; break;
        default: break;
      }
      result+=" Referentie";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorDutch::trCompounds () inline override virtual
Implements Translator.
Definition at line 310 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Structuren";
      }
      else
      {
        return "Klassen";
      }
    }
References Config_getBool.
trCompoundType()
QCString TranslatorDutch::trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) inline override virtual
Implements Translator.
Definition at line 2005 of file translator_nl.h.
    {
      QCString result;
      switch(compType)
      {
        case ClassDef::Class:
          if (lang == SrcLangExt::Fortran) trType(true,true);
          else result=trClass(true,true);
          break;
        case ClassDef::Struct:     result="Struct"; break;
        case ClassDef::Union:      result="Union"; break;
        case ClassDef::Interface:  result="Interface"; break;
        case ClassDef::Protocol:   result="Protocol"; break;
        case ClassDef::Category:   result="Category"; break;
        case ClassDef::Exception:  result="Exception"; break;
        case ClassDef::Service:    result="Service"; break;
        case ClassDef::Singleton:  result="Singleton"; break;
        default: break;
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, Fortran, ClassDef::Interface, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, ClassDef::Struct, trClass(), trType(), and ClassDef::Union.
trConcept()
QCString TranslatorDutch::trConcept (bool first_capital, bool singular) inline override virtual
Implements Translator.
Definition at line 1923 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "concept", "en");
    }
References Translator::createNoun().
trConceptDefinition()
QCString TranslatorDutch::trConceptDefinition () inline override virtual
Implements Translator.
Definition at line 1952 of file translator_nl.h.
    {
      return "Concept definitie";
    }
trConceptDocumentation()
QCString TranslatorDutch::trConceptDocumentation () inline override virtual
Implements Translator.
Definition at line 1941 of file translator_nl.h.
    { return "Concept Documentatie"; }
trConceptIndex()
QCString TranslatorDutch::trConceptIndex () inline override virtual
Implements Translator.
Definition at line 1938 of file translator_nl.h.
    { return "Concept Index"; }
trConceptList()
QCString TranslatorDutch::trConceptList () inline override virtual
Implements Translator.
Definition at line 1935 of file translator_nl.h.
    { return "Concept Lijst"; }
trConceptListDescription()
QCString TranslatorDutch::trConceptListDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 1944 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="concepten, elk met een korte beschrijving:";
      return result;
    }
trConceptReference()
QCString TranslatorDutch::trConceptReference (const QCString & conceptName) inline override virtual
Implements Translator.
Definition at line 1928 of file translator_nl.h.
    {
      QCString result=conceptName;
      result+=" Concept Referentie";
      return result;
    }
trConstantDocumentation()
QCString TranslatorDutch::trConstantDocumentation () inline override virtual
Implements Translator.
Definition at line 1841 of file translator_nl.h.
    { return "Documentatie van konstanten"; }
trConstantGroupReference()
QCString TranslatorDutch::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1684 of file translator_nl.h.
    {
      QCString result=namespaceName;
      result+=" Konstanten Groepen Referentie";
      return result;
    }
trConstantGroups()
QCString TranslatorDutch::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1680 of file translator_nl.h.
    { return "Konstanten Groepen"; }
trConstants()
QCString TranslatorDutch::trConstants () inline override virtual
Implements Translator.
Definition at line 1839 of file translator_nl.h.
    { return "Konstanten"; }
trConstructorDocumentation()
QCString TranslatorDutch::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 606 of file translator_nl.h.
    {
      return "Constructor & Destructor Documentatie";
    }
trCopyright()
QCString TranslatorDutch::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1566 of file translator_nl.h.
    { return "Copyright"; }
trCopyToClipboard()
QCString TranslatorDutch::trCopyToClipboard () inline override virtual
Implements Translator.
Definition at line 2284 of file translator_nl.h.
    {
      return "Kopiren naar het klembord";
    }
trCustomReference()
QCString TranslatorDutch::trCustomReference (const QCString & name) inline override virtual
Implements Translator.
Definition at line 1835 of file translator_nl.h.
    { return name+" Referentie"; }
trDataMemberDocumentation()
QCString TranslatorDutch::trDataMemberDocumentation () inline override virtual
Implements Translator.
Definition at line 1911 of file translator_nl.h.
    { return "Documentatie van data members"; }
trDataMembers()
QCString TranslatorDutch::trDataMembers () inline override virtual
Implements Translator.
Definition at line 1909 of file translator_nl.h.
    { return "Data members"; }
trDataTypes()
QCString TranslatorDutch::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1336 of file translator_nl.h.
    { return "Data Types"; }
trDate()
QCString TranslatorDutch::trDate () inline override virtual
Implements Translator.
Definition at line 336 of file translator_nl.h.
    { return "Datum"; }
trDateTime()
QCString TranslatorDutch::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Implements Translator.
Definition at line 1515 of file translator_nl.h.
    {
      static const char *days[]   = { "Ma","Di","Wo","Do","Vr","Za","Zo" };
      static const char *months[] = { "Jan","Feb","Maa","Apr","Mei","Jun","Jul","Aug","Sep","Okt","Nov","Dec" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorDutch::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1535 of file translator_nl.h.
    {
      static const char *days_short[]   = { "ma", "di", "wo", "do", "vr", "za", "zo" };
      static const char *days_full[]    = { "maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorDutch::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1551 of file translator_nl.h.
    {
      static const char *dayPeriod[] = { "a.m.", "p.m." };
      return dayPeriod[period?1:0];
    }
trDeclaration()
QCString TranslatorDutch::trDeclaration () inline override virtual
Implements Translator.
Definition at line 2214 of file translator_nl.h.
{ return "Declaratie";}
trDefinedAtLineInSourceFile()
QCString TranslatorDutch::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 573 of file translator_nl.h.
    {
      return "De definitie bevindt zich op regel @0 in het bestand @1.";
    }
trDefinedIn()
QCString TranslatorDutch::trDefinedIn () inline override virtual
Implements Translator.
Definition at line 100 of file translator_nl.h.
    { return "gedefinieerd in"; }
trDefinedInSourceFile()
QCString TranslatorDutch::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 577 of file translator_nl.h.
    {
      return "De definitie bevindt zich in het bestand @0.";
    }
trDefineDocumentation()
QCString TranslatorDutch::trDefineDocumentation () inline override virtual
Implements Translator.
Definition at line 298 of file translator_nl.h.
    { return "Documentatie van macro's"; }
trDefines()
QCString TranslatorDutch::trDefines () inline override virtual
Implements Translator.
Definition at line 286 of file translator_nl.h.
    { return "Macros"; }
trDefineValue()
QCString TranslatorDutch::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 895 of file translator_nl.h.
    {
      return "Waarde:";
    }
trDefinition()
QCString TranslatorDutch::trDefinition () inline override virtual
Implements Translator.
Definition at line 2213 of file translator_nl.h.
{ return "Definitie";}
trDeprecated()
QCString TranslatorDutch::trDeprecated () inline override virtual
Implements Translator.
Definition at line 586 of file translator_nl.h.
    {
      return "Verouderd";
    }
trDeprecatedList()
QCString TranslatorDutch::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1083 of file translator_nl.h.
    {
      return "Deprecated Lijst";
    }
trDesignUnitDocumentation()
QCString TranslatorDutch::trDesignUnitDocumentation () inline override virtual
Implements Translator.
Definition at line 1917 of file translator_nl.h.
    { return "Ontwerp Eenheid Documentatie"; }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorDutch::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Implements Translator.
Definition at line 1726 of file translator_nl.h.
    { return "Ontwerp Eenheid Hirarchie"; }
trDesignUnitIndex()
QCString TranslatorDutch::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Implements Translator.
Definition at line 1741 of file translator_nl.h.
    { return "Ontwerp Eenheid Index"; }
trDesignUnitList()
QCString TranslatorDutch::trDesignUnitList () inline override virtual
VHDL design unit list.
Implements Translator.
Definition at line 1729 of file translator_nl.h.
    { return "Ontwerp Eenheid Lijst"; }
trDesignUnitListDescription()
QCString TranslatorDutch::trDesignUnitListDescription () inline override virtual
VHDL design unit list description.
Implements Translator.
Definition at line 1735 of file translator_nl.h.
    {
      return "hieronder volgt de lijst met all ontwerp eenheden met links "
             "naar de entiteiten waar ze bij behoren:";
    }
trDesignUnitMembers()
QCString TranslatorDutch::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Implements Translator.
Definition at line 1732 of file translator_nl.h.
    { return "Ontwerp Eenheid Members"; }
trDesignUnits()
QCString TranslatorDutch::trDesignUnits () inline override virtual
VHDL design units.
Implements Translator.
Definition at line 1744 of file translator_nl.h.
    { return "Ontwerp Eenheden"; }
trDetailedDescription()
QCString TranslatorDutch::trDetailedDescription () inline override virtual
Implements Translator.
Definition at line 49 of file translator_nl.h.
    { return "Gedetailleerde Beschrijving"; }
trDetailLevel()
QCString TranslatorDutch::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1578 of file translator_nl.h.
    { return "detail niveau"; }
trDetails()
QCString TranslatorDutch::trDetails () inline override virtual
Implements Translator.
Definition at line 51 of file translator_nl.h.
    { return "Details"; }
trDictionaries()
QCString TranslatorDutch::trDictionaries () inline override virtual
Implements Translator.
Definition at line 1847 of file translator_nl.h.
    { return "Vertalingslijsten"; }
trDictionaryDocumentation()
QCString TranslatorDutch::trDictionaryDocumentation () inline override virtual
Implements Translator.
Definition at line 1849 of file translator_nl.h.
    { return "Documentatie van vertalingslijsten"; }
trDir()
QCString TranslatorDutch::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1249 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "folder", "s");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorDutch::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1570 of file translator_nl.h.
    { return "Folder afhankelijkheidsgraaf voor "+name+":"; }
trDirDocumentation()
QCString TranslatorDutch::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1231 of file translator_nl.h.
    { return "Folder Documentatie"; }
trDirectories()
QCString TranslatorDutch::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1237 of file translator_nl.h.
    { return "Folders"; }
trDirIndex()
QCString TranslatorDutch::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1225 of file translator_nl.h.
    { return "Folder Hirarchie"; }
trDirReference()
QCString TranslatorDutch::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1243 of file translator_nl.h.
    { QCString result=dirName; result+=" Folder Referentie"; return result; }
trDirRelation()
QCString TranslatorDutch::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1465 of file translator_nl.h.
    {
      return name+" Relatie";
    }
trDocumentation()
QCString TranslatorDutch::trDocumentation (const QCString & projName) inline override virtual
Implements Translator.
Definition at line 245 of file translator_nl.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Documentatie"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorDutch::trEnumerations () inline override virtual
Implements Translator.
Definition at line 290 of file translator_nl.h.
    { return "Enumeraties"; }
trEnumerationTypeDocumentation()
QCString TranslatorDutch::trEnumerationTypeDocumentation () inline override virtual
Implements Translator.
Definition at line 302 of file translator_nl.h.
    { return "Documentatie van enumeratie types"; }
trEnumerationValueDocumentation()
QCString TranslatorDutch::trEnumerationValueDocumentation () inline override virtual
Implements Translator.
Definition at line 304 of file translator_nl.h.
    { return "Documentatie van enumeratie waarden"; }
trEnumerationValues()
QCString TranslatorDutch::trEnumerationValues () inline override virtual
Implements Translator.
Definition at line 296 of file translator_nl.h.
    { return "Enumeratie waarden"; }
trEnumGeneratedFromFiles()
QCString TranslatorDutch::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1590 of file translator_nl.h.
    { QCString result = "De documentatie voor deze enum is gegenereerd op basis van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
trEnumName()
QCString TranslatorDutch::trEnumName () inline override virtual
Implements Translator.
Definition at line 96 of file translator_nl.h.
    { return "enum naam"; }
trEnumReference()
QCString TranslatorDutch::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1599 of file translator_nl.h.
    { return name+" Enum Referentie"; }
trEnumValue()
QCString TranslatorDutch::trEnumValue () inline override virtual
Implements Translator.
Definition at line 98 of file translator_nl.h.
    { return "enum waarde"; }
trEventDocumentation()
QCString TranslatorDutch::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1099 of file translator_nl.h.
    {
      return "Event Documentatie";
    }
trEvents()
QCString TranslatorDutch::trEvents () inline override virtual
Used as a header for a section of events found in a C# program
Implements Translator.
Definition at line 1094 of file translator_nl.h.
    {
      return "Events";
    }
trExamples()
QCString TranslatorDutch::trExamples () inline override virtual
Implements Translator.
Definition at line 143 of file translator_nl.h.
    { return "Voorbeelden"; }
trExamplesDescription()
QCString TranslatorDutch::trExamplesDescription () inline override virtual
Implements Translator.
Definition at line 238 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle voorbeelden:"; }
trExceptionDocumentation()
QCString TranslatorDutch::trExceptionDocumentation () inline override virtual
Implements Translator.
Definition at line 1885 of file translator_nl.h.
    { return "Documentatie van exceptions"; }
trExceptionHierarchy()
QCString TranslatorDutch::trExceptionHierarchy () inline override virtual
Implements Translator.
Definition at line 1881 of file translator_nl.h.
    { return "Exception Hirarchie"; }
trExceptionHierarchyDescription()
QCString TranslatorDutch::trExceptionHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 1883 of file translator_nl.h.
    { return "Deze inheritance lijst is min of meer alfabetisch gesorteerd:"; }
trExceptionIndex()
QCString TranslatorDutch::trExceptionIndex () inline override virtual
Implements Translator.
Definition at line 1875 of file translator_nl.h.
    { return "Index van exceptions"; }
trExceptionList()
QCString TranslatorDutch::trExceptionList () inline override virtual
Implements Translator.
Definition at line 1877 of file translator_nl.h.
    { return "Lijst van exceptions"; }
trExceptionListDescription()
QCString TranslatorDutch::trExceptionListDescription () inline override virtual
Implements Translator.
Definition at line 1879 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle exeptions, elk met een korte beschrijving:"; }
trExceptions()
QCString TranslatorDutch::trExceptions () inline override virtual
Implements Translator.
Definition at line 344 of file translator_nl.h.
    { return "Excepties"; }
trExportedModules()
QCString TranslatorDutch::trExportedModules () inline override virtual
Implements Translator.
Definition at line 2275 of file translator_nl.h.
    {
      return "Gexporteerde Modules";
    }
trExtendsClass()
QCString TranslatorDutch::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1639 of file translator_nl.h.
    {
      return "Uitbereiding van klasse @0.";
    }
trFile()
QCString TranslatorDutch::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 977 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "bestand", "en");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorDutch::trFileDocumentation () inline override virtual
Implements Translator.
Definition at line 281 of file translator_nl.h.
    { return "Bestand Documentatie"; }
trFileIn()
QCString TranslatorDutch::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1502 of file translator_nl.h.
    {
      return "Bestand in "+name;
    }
trFileIndex()
QCString TranslatorDutch::trFileIndex () inline override virtual
Implements Translator.
Definition at line 262 of file translator_nl.h.
    { return "Bestand Index"; }
trFileList()
QCString TranslatorDutch::trFileList () inline override virtual
Implements Translator.
Definition at line 117 of file translator_nl.h.
    { return "Bestandslijst"; }
trFileListDescription()
QCString TranslatorDutch::trFileListDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 158 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="bestanden, elk met een korte beschrijving:";
      return result;
    }
trFileMembers()
QCString TranslatorDutch::trFileMembers () inline override virtual
Implements Translator.
Definition at line 130 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Glabale members";
      }
      else
      {
        return "Bestand members";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorDutch::trFileMembersDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 221 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="functies, variabelen, macros, enumeraties, en typedefs";
      }
      else
      {
        result+="bestand members";
      }
      result+=" met links naar ";
      if (extractAll) result+="de bestand's documentatie voor elke member:";
      else result+="de bestanden waartoe ze behoren:";
      return result;
    }
References Config_getBool.
trFileMembersDescriptionTotal()
QCString TranslatorDutch::trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2027 of file translator_nl.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      switch (hl)
      {
        case FileMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="functies, variabelen, macros, enumeraties, en typedefs";
          }
          else
          {
            result+="bestand members";
          }
          break;
        case FileMemberHighlight::Functions:
          result+="functies";
          break;
        case FileMemberHighlight::Variables:
          result+="variabelen";
          break;
        case FileMemberHighlight::Typedefs:
          result+="typedefs";
          break;
        case FileMemberHighlight::Sequences:
          result+="reeksen";
          break;
        case FileMemberHighlight::Dictionaries:
          result+="vertalingslijsten";
          break;
        case FileMemberHighlight::Enums:
          result+="enumeratie";
          break;
        case FileMemberHighlight::EnumValues:
          result+="enumeratie waarden";
          break;
        case FileMemberHighlight::Defines:
          result+="macros";
          break;
        case FileMemberHighlight::Total: // for completeness
          break;
      }
      result+=" met links naar ";
      if (extractAll) result+="de bestand's documentatie voor elke member:";
      else result+="de bestanden waartoe ze behoren:";
      return result;
    }
References FileMemberHighlight::All, Config_getBool, FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, FileMemberHighlight::Sequences, FileMemberHighlight::Total, FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
trFileReference()
QCString TranslatorDutch::trFileReference (const QCString & fileName) inline override virtual
Implements Translator.
Definition at line 397 of file translator_nl.h.
    {
      QCString result=fileName;
      result+=" Bestand Referentie";
      return result;
    }
trFlowchart()
QCString TranslatorDutch::trFlowchart () inline override virtual
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 1971 of file translator_nl.h.
    { return "Stroomschema:"; }
trFriends()
QCString TranslatorDutch::trFriends () inline override virtual
Implements Translator.
Definition at line 362 of file translator_nl.h.
    { return "Friends"; }
trFunctionAndProc()
QCString TranslatorDutch::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Implements Translator.
Definition at line 1747 of file translator_nl.h.
    { return "Functies/Procedures/Processen"; }
trFunctionDocumentation()
QCString TranslatorDutch::trFunctionDocumentation () inline override virtual
Implements Translator.
Definition at line 306 of file translator_nl.h.
    { return "Documentatie van functies"; }
trFunctions()
QCString TranslatorDutch::trFunctions () inline override virtual
Implements Translator.
Definition at line 292 of file translator_nl.h.
    { return "Functies"; }
trGeneratedAt()
QCString TranslatorDutch::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
Implements Translator.
Definition at line 321 of file translator_nl.h.
    {
      QCString result="Gegenereerd op "+date;
      if (!projName.isEmpty()) result+=" voor "+projName;
      result+=" door";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorDutch::trGeneratedAutomatically (const QCString & s) inline override virtual
Implements Translator.
Definition at line 90 of file translator_nl.h.
    { QCString result="Automatisch gegenereerd door Doxygen";
      if (!s.isEmpty()) result+=" voor "+s;
      result+=" uit de programmatekst.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorDutch::trGeneratedBy () inline override virtual
Implements Translator.
Definition at line 346 of file translator_nl.h.
    { return "Gegenereerd door"; }
trGeneratedFromFiles()
QCString TranslatorDutch::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 526 of file translator_nl.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="De documentatie voor ";
      switch(compType)
      {
        case ClassDef::Class:      result+=vhdlOpt?"deze ontwerp eenheid":"deze klasse"; break;
        case ClassDef::Struct:     result+="deze struct"; break;
        case ClassDef::Union:      result+="deze union"; break;
        case ClassDef::Interface:  result+="dit interface"; break;
        case ClassDef::Protocol:   result+="dit protocol"; break;
        case ClassDef::Category:   result+="deze categorie"; break;
        case ClassDef::Exception:  result+="deze exceptie"; break;
        default: break;
      }
      result+=" is gegenereerd op basis van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorDutch::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1415 of file translator_nl.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="De documentatie voor ";
      switch(compType)
      {
        case ClassDef::Class:      result+="deze module"; break;
        case ClassDef::Struct:     result+="dit type"; break;
        case ClassDef::Union:      result+="deze union"; break;
        case ClassDef::Interface:  result+="dit interface"; break;
        case ClassDef::Protocol:   result+="dit protocol"; break;
        case ClassDef::Category:   result+="deze category"; break;
        case ClassDef::Exception:  result+="deze exception"; break;
        default: break;
      }
      result+=" is gegenereerd op basis van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorDutch::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1022 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "globale member", "s");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorDutch::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1477 of file translator_nl.h.
    {
      return "Globale Namespace";
    }
trGotoDocumentation()
QCString TranslatorDutch::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 616 of file translator_nl.h.
    {
      return "Ga naar de documentatie van dit bestand.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorDutch::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 649 of file translator_nl.h.
    {
      return "Ga naar de grafische klasse hirarchie";
    }
trGotoSourceCode()
QCString TranslatorDutch::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 611 of file translator_nl.h.
    {
      return "Ga naar de broncode van dit bestand.";
    }
trGotoTextualHierarchy()
QCString TranslatorDutch::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 653 of file translator_nl.h.
    {
      return "Ga naar de tekstuele klasse hirarchie";
    }
trGraphicalHierarchy()
QCString TranslatorDutch::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 645 of file translator_nl.h.
    {
      return "Grafische Klasse Hirarchie";
    }
trGroup()
QCString TranslatorDutch::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 995 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "groep", "en");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorDutch::trHierarchicalIndex () inline override virtual
Implements Translator.
Definition at line 249 of file translator_nl.h.
    { return "Hirarchische Index"; }
trImplementedFromList()
QCString TranslatorDutch::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1056 of file translator_nl.h.
    {
      return "Implementeert "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorDutch::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1064 of file translator_nl.h.
    {
      return "Wordt gemplementeerd door "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImportant()
QCString TranslatorDutch::trImportant () inline override virtual
Implements Translator.
Definition at line 2293 of file translator_nl.h.
    {
      return "Belangrijk";
    }
trInclByDepGraph()
QCString TranslatorDutch::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 746 of file translator_nl.h.
    {
      return "Deze graaf geeft aan welke bestanden direct of "
             "indirect afhankelijk zijn van dit bestand:";
    }
trInclDepGraph()
QCString TranslatorDutch::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 601 of file translator_nl.h.
    {
      return "Include afhankelijkheidsgraaf voor "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorDutch::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1511 of file translator_nl.h.
    {
      return "Includeert bestand in "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorDutch::trIncludingInheritedMembers () inline override virtual
Implements Translator.
Definition at line 88 of file translator_nl.h.
    { return ", inclusief alle overgerfde members."; }
trInheritedByList()
QCString TranslatorDutch::trInheritedByList (int numEntries) inline override virtual
Implements Translator.
Definition at line 464 of file translator_nl.h.
    {
      return "Wordt overgerfd door "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorDutch::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1603 of file translator_nl.h.
    { return members+" overgerfd van "+what; }
trInheritsList()
QCString TranslatorDutch::trInheritsList (int numEntries) inline override virtual
Implements Translator.
Definition at line 458 of file translator_nl.h.
    {
      return "Erft over van "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorDutch::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 636 of file translator_nl.h.
    {
      return "Initile waarde:";
    }
trInstanceMethods()
QCString TranslatorDutch::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1655 of file translator_nl.h.
    {
      return "Instantie Methoden";
    }
trInterfaceDocumentation()
QCString TranslatorDutch::trInterfaceDocumentation () inline override virtual
Implements Translator.
Definition at line 1863 of file translator_nl.h.
    { return "Documentatie van interfaces"; }
trInterfaceHierarchy()
QCString TranslatorDutch::trInterfaceHierarchy () inline override virtual
Implements Translator.
Definition at line 1859 of file translator_nl.h.
    { return "Interface Hirarchie"; }
trInterfaceHierarchyDescription()
QCString TranslatorDutch::trInterfaceHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 1861 of file translator_nl.h.
    { return "Deze inheritance lijst is min of meer alfabetisch gesorteerd:"; }
trInterfaceIndex()
QCString TranslatorDutch::trInterfaceIndex () inline override virtual
Implements Translator.
Definition at line 1853 of file translator_nl.h.
    { return "Index van interfaces"; }
trInterfaceList()
QCString TranslatorDutch::trInterfaceList () inline override virtual
Implements Translator.
Definition at line 1855 of file translator_nl.h.
    { return "Lijst van interfaces"; }
trInterfaceListDescription()
QCString TranslatorDutch::trInterfaceListDescription () inline override virtual
Implements Translator.
Definition at line 1857 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle interfaces, elk met een korte beschrijving:"; }
trInterfaces()
QCString TranslatorDutch::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1672 of file translator_nl.h.
    { return "Geporteerde Interfaces"; }
trInvariant()
QCString TranslatorDutch::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 631 of file translator_nl.h.
    {
      return "Invariant";
    }
trISOLang()
QCString TranslatorDutch::trISOLang () inline override virtual
Implements Translator.
Definition at line 39 of file translator_nl.h.
    { return "nl"; }
trLegend()
QCString TranslatorDutch::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 828 of file translator_nl.h.
    {
      return "legenda";
    }
trLegendDocs()
QCString TranslatorDutch::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 766 of file translator_nl.h.
    {
      return
        "Deze pagina legt uit hoe de grafen die gegenereerd worden door doxygen "
        "genterpreteerd dienen te worden.<p>\n"
        "Beschouw het volgende voorbeeld:\n"
        "\\code\n"
        "/*! Onzichtbare klasse vanwege afkappen van de graaf */\n"
        "class Invisible { };\n\n"
        "/*! Afgekapte klasse, overervingsrelatie is verborgen */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasse is niet gedocumenteerd met doxygen commentaar */\n"
        "class Undocumented { };\n\n"
        "/*! Klasse met public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasse met protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasse met private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasse die wordt gebruikt door de klasse Inherited */\n"
        "class Used { };\n\n"
        "/*! Super klasse die overerft van een aantal andere klassen */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dit voorbeeld zal resulteren in de volgende graaf:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "De rechthoeken in the bovenstaande graaf hebben de volgende betekenis:\n"
        "<ul>\n"
        "<li>Een gevulde grijze rechthoek representeert de structure of klasse waarvoor "
        "de graaf is gegenereerd.\n"
        "<li>Een rechthoek met een zwarte rand representeert een gedocumenteerde structure of klasse.\n"
        "<li>Een rechthoek met een grijze rand representeert een ongedocumenteerde structure of klasse.\n"
        "<li>Een rechthoek met een rode rand representeert een gedocumenteerde structure or klasse waarvoor\n"
        "niet alle overervings- of gebruiksrelaties konden worden getoond. Een graaf wordt "
        "afgekapt als hij niet past binnen de gespecificeerde grenzen."
        "</ul>\n"
        "De pijlen hebben de volgende betekenis:\n"
        "<ul>\n"
        "<li>Een blauwe pijl visualizeert een public inheritance "
        "relatie tussen twee klassen.\n"
        "<li>Een donkergroene pijl wordt gebruikt voor protected inheritance.\n"
        "<li>Een donkerrode pijl wordt gebruikt voor private inheritance.\n"
        "<li>Een paars gestippelde pijl wordt gebruikt indien een klasse bevat is of gebruikt wordt "
        "door een andere klasse. De pijl is gelabeled met de variable(n) "
        "die toegang geven tot de aangewezen klasse of structure. \n"
        "<li>Een geel gestippelde pijl wordt gebruikt om een relatie tussen een \n"
        "template instantie en een template klasse aan te geven. De pijl is gelabeld met \n"
        "template parameters van de instantie.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorDutch::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 761 of file translator_nl.h.
    {
      return "Graaf Legenda";
    }
trListOfAllMembers()
QCString TranslatorDutch::trListOfAllMembers () inline override virtual
Implements Translator.
Definition at line 82 of file translator_nl.h.
    { return "Lijst van alle members"; }
trLoading()
QCString TranslatorDutch::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1471 of file translator_nl.h.
    {
      return "Laden...";
    }
trMainPage()
QCString TranslatorDutch::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 560 of file translator_nl.h.
    { return "Hoofd Pagina"; }
trMember()
QCString TranslatorDutch::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1013 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "member", "s");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorDutch::trMemberDataDocumentation () inline override virtual
Implements Translator.
Definition at line 69 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentatie van data velden";
      }
      else
      {
        return "Documentatie van data members";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorDutch::trMemberEnumerationDocumentation () inline override virtual
Implements Translator.
Definition at line 56 of file translator_nl.h.
    { return "Documentatie van enumeratie members"; }
trMemberFunctionDocumentation()
QCString TranslatorDutch::trMemberFunctionDocumentation () inline override virtual
Implements Translator.
Definition at line 58 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Documentatie van functie/procedure/process members";
      }
      else
      {
        return "Documentatie van functie members";
      }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran()
QCString TranslatorDutch::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1279 of file translator_nl.h.
    { return "Member Functie/Subroutine Documentatie"; }
trMemberList()
QCString TranslatorDutch::trMemberList () inline override virtual
Implements Translator.
Definition at line 84 of file translator_nl.h.
    { return "Member Lijst"; }
trMemberTypedefDocumentation()
QCString TranslatorDutch::trMemberTypedefDocumentation () inline override virtual
Implements Translator.
Definition at line 54 of file translator_nl.h.
    { return "Documentatie van type definitie members"; }
trMethodDocumentation()
QCString TranslatorDutch::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1662 of file translator_nl.h.
    {
      return "Methode Documentatie";
    }
trModule()
QCString TranslatorDutch::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1408 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "module", "n");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorDutch::trModuleDocumentation () inline override virtual
Implements Translator.
Definition at line 264 of file translator_nl.h.
    { return "Module Documentatie"; }
trModuleIndex()
QCString TranslatorDutch::trModuleIndex () inline override virtual
Implements Translator.
Definition at line 247 of file translator_nl.h.
    { return "Module Index"; }
trModuleMembersDescriptionTotal()
QCString TranslatorDutch::trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2230 of file translator_nl.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="Hier is een lijst van alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="module ";
      QCString singularResult = "";
      QCString pluralResult = "";
      switch (hl)
      {
        case ModuleMemberHighlight::All:
          singularResult="symbool";
          pluralResult="symbolen";
          break;
        case ModuleMemberHighlight::Functions:
          singularResult="e functie";
          pluralResult="functies";
          break;
        case ModuleMemberHighlight::Variables:
          singularResult="e variabele";
          pluralResult="variabelen";
          break;
        case ModuleMemberHighlight::Typedefs:
          singularResult="e typedef";
          pluralResult="typedefs";
          break;
        case ModuleMemberHighlight::Enums:
          singularResult="e enumeratie";
          pluralResult="enumeraties";
          break;
        case ModuleMemberHighlight::EnumValues:
          singularResult="e enumeratie waarde";
          pluralResult="enumeratie waarden";
          break;
        case ModuleMemberHighlight::Total: // for completeness
          break;
      }
      result+=pluralResult;
      result+=" met links naar ";
      if (extractAll)
        result+="de module documentatie voor ieder" + singularResult + ":";
      else
        result+="de modules waartoe ze behoren:";
      return result;
    }
References ModuleMemberHighlight::All, Config_getBool, ModuleMemberHighlight::Enums, ModuleMemberHighlight::EnumValues, ModuleMemberHighlight::Functions, ModuleMemberHighlight::Total, ModuleMemberHighlight::Typedefs, and ModuleMemberHighlight::Variables.
trModuleReference()
QCString TranslatorDutch::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1374 of file translator_nl.h.
    {
      QCString result=namespaceName;
      result+=" Module Referentie";
      return result;
    }
trModules()
QCString TranslatorDutch::trModules () inline override virtual
Implements Translator.
Definition at line 102 of file translator_nl.h.
    { return "Modules"; }
trModulesDescription()
QCString TranslatorDutch::trModulesDescription () inline override virtual
Implements Translator.
Definition at line 242 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle modules:"; }
trModulesIndex()
QCString TranslatorDutch::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1401 of file translator_nl.h.
    { return "Module Index"; }
trModulesList()
QCString TranslatorDutch::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1340 of file translator_nl.h.
    { return "Module Lijst"; }
trModulesListDescription()
QCString TranslatorDutch::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1344 of file translator_nl.h.
    {
      QCString result="Hieronder volgt de lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="modulen, elk met een korte beschrijving:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorDutch::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1386 of file translator_nl.h.
    {
      QCString result="Hier is een lijst van alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="module members met links naar ";
      if (extractAll)
        result+="de module documentatie voor iedere member:";
      else
        result+="de module waartoe ze behoren:";
      return result;
    }
trModulesMembers()
QCString TranslatorDutch::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1382 of file translator_nl.h.
    { return "Module Members"; }
trMonth()
QCString TranslatorDutch::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1543 of file translator_nl.h.
    {
      static const char *months_short[] = { "jan", "feb", "mrt", "apr", "mei", "jun", "jul", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[]  = { "januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorDutch::trMore () inline override virtual
Implements Translator.
Definition at line 80 of file translator_nl.h.
    { return "Meer..."; }
trNamespace()
QCString TranslatorDutch::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 986 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "namespace", "s");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorDutch::trNamespaceDocumentation () inline override virtual
Implements Translator.
Definition at line 502 of file translator_nl.h.
    { return "Namespace Documentatie"; }
trNamespaceIndex()
QCString TranslatorDutch::trNamespaceIndex () inline override virtual
Implements Translator.
Definition at line 498 of file translator_nl.h.
    { return "Namespace Index"; }
trNamespaceList()
QCString TranslatorDutch::trNamespaceList () inline override virtual
Implements Translator.
Definition at line 353 of file translator_nl.h.
    { return "Namespace Lijst"; }
trNamespaceListDescription()
QCString TranslatorDutch::trNamespaceListDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 355 of file translator_nl.h.
    {
      QCString result="Hier is een lijst met alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="namespaces met voor elk een korte beschrijving:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorDutch::trNamespaceMemberDescription (bool extractAll) inline override virtual
Implements Translator.
Definition at line 486 of file translator_nl.h.
    {
      QCString result="Hier is een lijst van alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="namespace members met links naar ";
      if (extractAll)
        result+="de namespace documentatie voor iedere member:";
      else
        result+="de namespaces waartoe ze behoren:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorDutch::trNamespaceMembers () inline override virtual
Implements Translator.
Definition at line 483 of file translator_nl.h.
    { return "Namespace Members"; }
trNamespaceMembersDescriptionTotal()
QCString TranslatorDutch::trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2159 of file translator_nl.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="Hier is een lijst van alle ";
      if (!extractAll) result+="gedocumenteerde ";
      result+="namespace ";
      QCString singularResult = "";
      QCString pluralResult = "";
      switch (hl)
      {
        case NamespaceMemberHighlight::All:
          singularResult="symbool";
          pluralResult="symbolen";
          break;
        case NamespaceMemberHighlight::Functions:
          singularResult="e functie";
          pluralResult="functies";
          break;
        case NamespaceMemberHighlight::Variables:
          singularResult="e variabele";
          pluralResult="variabelen";
          break;
        case NamespaceMemberHighlight::Typedefs:
          singularResult="e typedef";
          pluralResult="typedefs";
          break;
        case NamespaceMemberHighlight::Sequences:
          singularResult="e reeks";
          pluralResult="reeksen";
          break;
        case NamespaceMemberHighlight::Dictionaries:
          singularResult="e vertalingslijst";
          pluralResult="vertalingslijsten";
          break;
        case NamespaceMemberHighlight::Enums:
          singularResult="e enumeratie";
          pluralResult="enumeraties";
          break;
        case NamespaceMemberHighlight::EnumValues:
          singularResult="e enumeratie waarde";
          pluralResult="enumeratie waarden";
          break;
        case NamespaceMemberHighlight::Total: // for completeness
          break;
      }
      result+=pluralResult;
      result+=" met links naar ";
      if (extractAll)
        result+="de namespace documentatie voor ieder" + singularResult + ":";
      else
        result+="de namespaces waartoe ze behoren:";
      return result;
    }
References NamespaceMemberHighlight::All, Config_getBool, NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, NamespaceMemberHighlight::Sequences, NamespaceMemberHighlight::Total, NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
trNamespaceReference()
QCString TranslatorDutch::trNamespaceReference (const QCString & namespaceName) inline override virtual
Implements Translator.
Definition at line 404 of file translator_nl.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Referentie";
      return result;
    }
trNamespaces()
QCString TranslatorDutch::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 514 of file translator_nl.h.
    {
      return "Namespaces";
    }
trNoMatches()
QCString TranslatorDutch::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1489 of file translator_nl.h.
    {
      return "Niets gevonden";
    }
trNote()
QCString TranslatorDutch::trNote () inline override virtual
Implements Translator.
Definition at line 666 of file translator_nl.h.
    {
      return "Noot";
    }
trOperationDocumentation()
QCString TranslatorDutch::trOperationDocumentation () inline override virtual
Implements Translator.
Definition at line 1907 of file translator_nl.h.
    { return "Documentatie van bewerkingen"; }
trOperations()
QCString TranslatorDutch::trOperations () inline override virtual
Implements Translator.
Definition at line 1905 of file translator_nl.h.
    { return "Bewerkingen"; }
trOverloadText()
QCString TranslatorDutch::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a function.
Implements Translator.
Definition at line 1261 of file translator_nl.h.
    {
      return "Deze functie is overloaded en is beschikbaar gemaakt om het "
             "gebruik te vergemakkelijken. Ze verschilt alleen van de "
             "bovenstaande functie wat betreft de parameterlijst.";
    }
trPackage()
QCString TranslatorDutch::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 880 of file translator_nl.h.
    {
      return "Package "+name;
    }
trPackageAttribs()
QCString TranslatorDutch::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1135 of file translator_nl.h.
    {
      return "Package Attributen";
    }
trPackageFunctions()
QCString TranslatorDutch::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1117 of file translator_nl.h.
    {
      return "Package Functies";
    }
trPackageList()
QCString TranslatorDutch::trPackageList () inline override virtual
Implements Translator.
Definition at line 1961 of file translator_nl.h.
    { return "Package Lijst"; }
trPackageListDescription()
QCString TranslatorDutch::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 885 of file translator_nl.h.
    {
      return "Hier volgen de packages, elk met een korte beschrijving (indien aanwezig):";
    }
trPackageMembers()
QCString TranslatorDutch::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1121 of file translator_nl.h.
    {
      return "Package Members";
    }
trPackages()
QCString TranslatorDutch::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 890 of file translator_nl.h.
    {
      return "Packages";
    }
trPackageTypes()
QCString TranslatorDutch::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1110 of file translator_nl.h.
    {
      return "Package Types";
    }
trPage()
QCString TranslatorDutch::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1004 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "pagina", "s");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorDutch::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 566 of file translator_nl.h.
    { return "p."; }
trPageIndex()
QCString TranslatorDutch::trPageIndex () inline override virtual
Implements Translator.
Definition at line 657 of file translator_nl.h.
    {
      return "Pagina Index";
    }
trPanelSynchronisationTooltip()
QCString TranslatorDutch::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1620 of file translator_nl.h.
    {
      QCString opt = enable ? "in" : "uit";
      return "klik hier om de paneel synchronisatie "+opt+" te schakelen";
    }
trParameters()
QCString TranslatorDutch::trParameters () inline override virtual
Implements Translator.
Definition at line 342 of file translator_nl.h.
    { return "Parameters"; }
trPostcondition()
QCString TranslatorDutch::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 626 of file translator_nl.h.
    {
      return "Postconditie";
    }
trPrecondition()
QCString TranslatorDutch::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 621 of file translator_nl.h.
    {
      return "Preconditie";
    }
trPrivateAttribs()
QCString TranslatorDutch::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 705 of file translator_nl.h.
    {
      return "Private Attributen";
    }
trPrivateMembers()
QCString TranslatorDutch::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 427 of file translator_nl.h.
    { return "Private Members"; }
trPrivateSlots()
QCString TranslatorDutch::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 429 of file translator_nl.h.
    { return "Private Slots"; }
trPrivateTypes()
QCString TranslatorDutch::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 701 of file translator_nl.h.
    {
      return "Private Typen";
    }
trProperties()
QCString TranslatorDutch::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 853 of file translator_nl.h.
    {
      return "Properties";
    }
trPropertyDocumentation()
QCString TranslatorDutch::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 858 of file translator_nl.h.
    {
      return "Property Documentatie";
    }
trProtectedAttribs()
QCString TranslatorDutch::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 693 of file translator_nl.h.
    {
      return "Protected Attributen";
    }
trProtectedMembers()
QCString TranslatorDutch::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 421 of file translator_nl.h.
    { return "Protected Members"; }
trProtectedSlots()
QCString TranslatorDutch::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 423 of file translator_nl.h.
    { return "Protected Slots"; }
trProtectedTypes()
QCString TranslatorDutch::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 689 of file translator_nl.h.
    {
      return "Protected Typen";
    }
trProvidedByCategory()
QCString TranslatorDutch::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1630 of file translator_nl.h.
    {
      return "Wordt aangeboden door category @0.";
    }
trPublicAttribs()
QCString TranslatorDutch::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 674 of file translator_nl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Velden";
      }
      else
      {
        return "Public Attributen";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorDutch::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 413 of file translator_nl.h.
    { return "Public Members"; }
trPublicSlots()
QCString TranslatorDutch::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 415 of file translator_nl.h.
    { return "Public Slots"; }
trPublicTypes()
QCString TranslatorDutch::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 670 of file translator_nl.h.
    {
      return "Public Typen";
    }
trReferencedBy()
QCString TranslatorDutch::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 734 of file translator_nl.h.
    {
      return "Wordt aangeroepen door";
    }
trReferenceManual()
QCString TranslatorDutch::trReferenceManual () inline override virtual
Implements Translator.
Definition at line 283 of file translator_nl.h.
    { return "Naslagwerk"; }
trReferences()
QCString TranslatorDutch::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1044 of file translator_nl.h.
    {
      return "Gebruikt";
    }
trReimplementedFromList()
QCString TranslatorDutch::trReimplementedFromList (int numEntries) inline override virtual
Implements Translator.
Definition at line 470 of file translator_nl.h.
    {
      return "Nieuwe implementatie van "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorDutch::trReimplementedInList (int numEntries) inline override virtual
Implements Translator.
Definition at line 476 of file translator_nl.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "Opnieuw gemplementeerd in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorDutch::trRelatedFunctionDocumentation () inline override virtual
Implements Translator.
Definition at line 369 of file translator_nl.h.
    { return "Documentatie van friends en gerelateerde functies"; }
trRelatedFunctions()
QCString TranslatorDutch::trRelatedFunctions () inline override virtual
Implements Translator.
Definition at line 45 of file translator_nl.h.
    { return "Gerelateerde functies"; }
trRelatedPages()
QCString TranslatorDutch::trRelatedPages () inline override virtual
Implements Translator.
Definition at line 141 of file translator_nl.h.
    { return "Gerelateerde pagina's"; }
trRelatedPagesDescription()
QCString TranslatorDutch::trRelatedPagesDescription () inline override virtual
Implements Translator.
Definition at line 240 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle pagina's die gerelateerde documentatie bevatten:"; }
trRelatedSubscript()
QCString TranslatorDutch::trRelatedSubscript () inline override virtual
Implements Translator.
Definition at line 47 of file translator_nl.h.
    { return "(Merk op dat dit geen member functies zijn.)"; }
trRelatedSymbolDocumentation()
QCString TranslatorDutch::trRelatedSymbolDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes.
Supersedes trRelatedFunctionDocumentation
Implements Translator.
Definition at line 2002 of file translator_nl.h.
    { return "Documentatie van friends en gerelateerde symbolen"; }
trRelatedSymbols()
QCString TranslatorDutch::trRelatedSymbols () inline override virtual
Please translate also updated body of the method trMemberFunctionDocumentation(), now better adapted for VHDL sources documentation. Done.
used in the compound documentation before a list of related symbols.
Supersedes trRelatedFunctions
Implements Translator.
Definition at line 1987 of file translator_nl.h.
    { return "Gerelateerde symbolen"; }
trRelatedSymbolsSubscript()
QCString TranslatorDutch::trRelatedSymbolsSubscript () inline override virtual
subscript for the related symbols
Supersedes trRelatedSubscript
Implements Translator.
Definition at line 1994 of file translator_nl.h.
    { return "(Merk op dat dit geen member symbolen zijn.)"; }
trRemarks()
QCString TranslatorDutch::trRemarks () inline override virtual
Implements Translator.
Definition at line 738 of file translator_nl.h.
    {
      return "Opmerkingen";
    }
trReturns()
QCString TranslatorDutch::trReturns () inline override virtual
Implements Translator.
Definition at line 338 of file translator_nl.h.
    { return "Retourneert"; }
trReturnValues()
QCString TranslatorDutch::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 555 of file translator_nl.h.
    { return "Retour waarden"; }
trRTFansicp()
QCString TranslatorDutch::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 944 of file translator_nl.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorDutch::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 953 of file translator_nl.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorDutch::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 959 of file translator_nl.h.
    {
      return "Index";
    }
trRTFTableOfContents()
QCString TranslatorDutch::trRTFTableOfContents () inline override virtual
Implements Translator.
Definition at line 1073 of file translator_nl.h.
    { return "Inhoudsopgave"; }
trSearch()
QCString TranslatorDutch::trSearch () inline override virtual
Implements Translator.
Definition at line 145 of file translator_nl.h.
    { return "Zoeken"; }
trSearching()
QCString TranslatorDutch::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1483 of file translator_nl.h.
    {
      return "Zoeken...";
    }
trSearchMatches()
QCString TranslatorDutch::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1202 of file translator_nl.h.
    {
      return "Gevonden:";
    }
trSearchResults()
QCString TranslatorDutch::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1183 of file translator_nl.h.
    {
      if (numDocuments==0)
      {
        return "Helaas, er zijn geen documenten gevonden die aan de zoekopdracht voldoen.";
      }
      else if (numDocuments==1)
      {
        return "Er is <b>1</b> document gevonden dat aan de zoekopdracht voldoet.";
      }
      else
      {
        return "Er zijn <b>$num</b> documenten gevonden die aan de zoekopdracht voldoen. "
               "De beste resultaten worden eerst getoond.";
      }
    }
trSearchResultsTitle()
QCString TranslatorDutch::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1171 of file translator_nl.h.
    {
      return "Zoek Resultaten";
    }
trSeeAlso()
QCString TranslatorDutch::trSeeAlso () inline override virtual
Implements Translator.
Definition at line 340 of file translator_nl.h.
    { return "Zie ook"; }
trSequenceDocumentation()
QCString TranslatorDutch::trSequenceDocumentation () inline override virtual
Implements Translator.
Definition at line 1845 of file translator_nl.h.
    { return "Documentatie van reeksen"; }
trSequences()
QCString TranslatorDutch::trSequences () inline override virtual
Implements Translator.
Definition at line 1843 of file translator_nl.h.
    { return "Reeksen"; }
trServiceGeneratedFromFiles()
QCString TranslatorDutch::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 1705 of file translator_nl.h.
    { QCString result = "De documentatie voor deze service is gegenereerd op basis van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
trServiceReference()
QCString TranslatorDutch::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 1691 of file translator_nl.h.
    {
      QCString result=sName;
      result+=" Service Referentie";
      return result;
    }
trServices()
QCString TranslatorDutch::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1676 of file translator_nl.h.
    { return "Gencludeerde Services"; }
trSignals()
QCString TranslatorDutch::trSignals () inline override virtual
Implements Translator.
Definition at line 417 of file translator_nl.h.
    { return "Signals"; }
trSince()
QCString TranslatorDutch::trSince () inline override virtual
Implements Translator.
Definition at line 751 of file translator_nl.h.
    {
      return "Sinds";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorDutch::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 1713 of file translator_nl.h.
    { QCString result = "De documentatie voor deze singleton is gegenereerd op basis van ";
      if (single) result+="het"; else result+="de";
      result+=" volgende bestand";
      if (single) result+=":"; else result+="en:";
      return result;
    }
trSingletonReference()
QCString TranslatorDutch::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 1698 of file translator_nl.h.
    {
      QCString result=sName;
      result+=" Singleton Referentie";
      return result;
    }
trSliceInterfaces()
QCString TranslatorDutch::trSliceInterfaces () inline override virtual
Implements Translator.
Definition at line 1851 of file translator_nl.h.
    { return "Interfaces"; }
trSourceFile()
QCString TranslatorDutch::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1213 of file translator_nl.h.
    {
      return filename + " Bron Bestand";
    }
trStaticPackageAttribs()
QCString TranslatorDutch::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1142 of file translator_nl.h.
    {
      return "Statische Package Attributen";
    }
trStaticPackageFunctions()
QCString TranslatorDutch::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1128 of file translator_nl.h.
    {
      return "Statische Package Functies";
    }
trStaticPrivateAttribs()
QCString TranslatorDutch::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 709 of file translator_nl.h.
    {
      return "Static Private Attributen";
    }
trStaticPrivateMembers()
QCString TranslatorDutch::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 431 of file translator_nl.h.
    { return "Static Private Members"; }
trStaticProtectedAttribs()
QCString TranslatorDutch::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 697 of file translator_nl.h.
    {
      return "Static Protected Attributen";
    }
trStaticProtectedMembers()
QCString TranslatorDutch::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 425 of file translator_nl.h.
    { return "Static Protected Members"; }
trStaticPublicAttribs()
QCString TranslatorDutch::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 685 of file translator_nl.h.
    {
      return "Static Public Attributen";
    }
trStaticPublicMembers()
QCString TranslatorDutch::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 419 of file translator_nl.h.
    { return "Static Public Members"; }
trStructDocumentation()
QCString TranslatorDutch::trStructDocumentation () inline override virtual
Implements Translator.
Definition at line 1873 of file translator_nl.h.
    { return "Documentatie van structs"; }
trStructIndex()
QCString TranslatorDutch::trStructIndex () inline override virtual
Implements Translator.
Definition at line 1867 of file translator_nl.h.
    { return "Index van struct"; }
trStructList()
QCString TranslatorDutch::trStructList () inline override virtual
Implements Translator.
Definition at line 1869 of file translator_nl.h.
    { return "Lijst van struct"; }
trStructListDescription()
QCString TranslatorDutch::trStructListDescription () inline override virtual
Implements Translator.
Definition at line 1871 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle structs, elk met een korte beschrijving:"; }
trStructs()
QCString TranslatorDutch::trStructs () inline override virtual
Implements Translator.
Definition at line 1865 of file translator_nl.h.
    { return "Structs"; }
trSubprogram()
QCString TranslatorDutch::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1449 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "subprogramma", "s");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorDutch::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1330 of file translator_nl.h.
    { return "Functie/Subroutine Documentatie"; }
trSubprograms()
QCString TranslatorDutch::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1324 of file translator_nl.h.
    { return "Functies/Subroutines"; }
trTemplateParameters()
QCString TranslatorDutch::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1582 of file translator_nl.h.
    { return "Template Parameters"; }
trTest()
QCString TranslatorDutch::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 838 of file translator_nl.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorDutch::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 843 of file translator_nl.h.
    {
      return "Test Lijst";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorDutch::trThisIsTheListOfAllMembers () inline override virtual
Implements Translator.
Definition at line 86 of file translator_nl.h.
    { return "Dit is de complete lijst van alle members voor"; }
trTodo()
QCString TranslatorDutch::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 720 of file translator_nl.h.
    {
      return "Todo";
    }
trTodoList()
QCString TranslatorDutch::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 725 of file translator_nl.h.
    {
      return "Todo Lijst";
    }
trTopicDocumentation()
QCString TranslatorDutch::trTopicDocumentation () inline override virtual
Implements Translator.
Definition at line 2222 of file translator_nl.h.
    { return "Documentatie voor dit onderwerp"; }
trTopicIndex()
QCString TranslatorDutch::trTopicIndex () inline override virtual
Implements Translator.
Definition at line 2224 of file translator_nl.h.
    { return "Overwerpen"; }
trTopicList()
QCString TranslatorDutch::trTopicList () inline override virtual
Implements Translator.
Definition at line 2226 of file translator_nl.h.
    { return "Lijst met onderwerpen"; }
trTopicListDescription()
QCString TranslatorDutch::trTopicListDescription () inline override virtual
Implements Translator.
Definition at line 2228 of file translator_nl.h.
    { return "Hieronder volgt de lijst met alle onderwerpen, elk met een korte beschrijving:"; }
trTopics()
QCString TranslatorDutch::trTopics () inline override virtual
Implements Translator.
Definition at line 2220 of file translator_nl.h.
    { return "Onderwerpen"; }
trType()
QCString TranslatorDutch::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1441 of file translator_nl.h.
    {
      return createNoun(first_capital, singular, "type", "s");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trTypeConstraints()
QCString TranslatorDutch::trTypeConstraints () inline override virtual
C# Type Contraint list
Implements Translator.
Definition at line 1455 of file translator_nl.h.
    {
      return "Type Beperkingen";
    }
trTypedefDocumentation()
QCString TranslatorDutch::trTypedefDocumentation () inline override virtual
Implements Translator.
Definition at line 300 of file translator_nl.h.
    { return "Documentatie van typedefs"; }
trTypedefs()
QCString TranslatorDutch::trTypedefs () inline override virtual
Implements Translator.
Definition at line 288 of file translator_nl.h.
    { return "Typedefs"; }
trTypeDocumentation()
QCString TranslatorDutch::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1318 of file translator_nl.h.
    { return "Data Type Documentatie"; }
trVariableDocumentation()
QCString TranslatorDutch::trVariableDocumentation () inline override virtual
Implements Translator.
Definition at line 308 of file translator_nl.h.
    { return "Documentatie van variabelen"; }
trVariables()
QCString TranslatorDutch::trVariables () inline override virtual
Implements Translator.
Definition at line 294 of file translator_nl.h.
    { return "Variabelen"; }
trVersion()
QCString TranslatorDutch::trVersion () inline override virtual
Implements Translator.
Definition at line 334 of file translator_nl.h.
    { return "Versie"; }
trVhdlType()
QCString TranslatorDutch::trVhdlType (VhdlSpecifier type, bool single) inline override virtual
VHDL type.
Implements Translator.
Definition at line 1750 of file translator_nl.h.
    {
      switch(type)
      {
        case VhdlSpecifier::LIBRARY:
          if (single) return "Bibliotheek";
          else        return "Bibliotheken";
        case VhdlSpecifier::PACKAGE:
          if (single) return "Package";
          else        return "Packages";
        case VhdlSpecifier::SIGNAL:
          if (single) return "Signal";
          else        return "Signals";
        case VhdlSpecifier::COMPONENT:
          if (single) return "Bestanddeel";
          else        return "Bestanddelen";
        case VhdlSpecifier::CONSTANT:
          if (single) return "Konstante";
          else        return "Konstanten";
        case VhdlSpecifier::ENTITY:
          if (single) return "Entiteit";
          else        return "Entiteiten";
        case VhdlSpecifier::TYPE:
          if (single) return "Type";
          else        return "Types";
        case VhdlSpecifier::SUBTYPE:
          if (single) return "Ondertype";
          else        return "Ondertypes";
        case VhdlSpecifier::FUNCTION:
          if (single) return "Funktie";
          else        return "Funkties";
        case VhdlSpecifier::RECORD:
          if (single) return "Record";
          else        return "Records";
        case VhdlSpecifier::PROCEDURE:
          if (single) return "Procedure";
          else        return "Procedures";
        case VhdlSpecifier::ARCHITECTURE:
          if (single) return "Architectuur";
          else        return "Architecturen";
        case VhdlSpecifier::ATTRIBUTE:
          if (single) return "Attribuut";
          else        return "Attributen";
        case VhdlSpecifier::PROCESS:
          if (single) return "Proces";
          else        return "Processen";
        case VhdlSpecifier::PORT:
          if (single) return "Poort";
          else        return "Porten";
        case VhdlSpecifier::USE:
          if (single) return "gebruiks clausule";
          else        return "Gebruiks Clausules";
        case VhdlSpecifier::GENERIC:
          if (single) return "Algemeen";
          else        return "Algemene";
        case VhdlSpecifier::PACKAGE_BODY:
          return "Package Body";
        case VhdlSpecifier::UNITS:
          return "Eenheden";
        case VhdlSpecifier::SHAREDVARIABLE:
          if (single) return "Gedeelde Variable";
          else        return "Gedeelde Variablen";
        case VhdlSpecifier::VFILE:
          if (single) return "Bestand";
          else        return "Bestanden";
        case VhdlSpecifier::GROUP:
          if (single) return "Groep";
          else        return "Groepen";
        case VhdlSpecifier::INSTANTIATION:
          if (single) return "Instantiring";
          else        return "Instantiringen";
        case VhdlSpecifier::ALIAS:
          if (single) return "Alias";
          else        return "Aliases";
        case VhdlSpecifier::CONFIG:
          if (single) return "Configuratie";
          else        return "Configuraties";
        case VhdlSpecifier::MISCELLANEOUS:
          return "Diverse";
        case VhdlSpecifier::UCF_CONST:
          return "Limiteringen";
        default:
          return "Klasse";
      }
    }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorDutch::trWarning () inline override virtual
Implements Translator.
Definition at line 332 of file translator_nl.h.
    { return "Waarschuwing"; }
trWriteList()
QCString TranslatorDutch::trWriteList (int numEntries) inline override virtual
Implements Translator.
Definition at line 435 of file translator_nl.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" en ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_nl.h