Doxygen: src/stringutil.h File Reference
stringutil.h File Reference
Some helper functions for std::string.
#include <string>
#include <string_view>
Functions
void substituteInplace (std::string &s, std::string_view toReplace, std::string_view replaceWith)
Replaces occurrences of substring toReplace in string s with string replaceWith.
std::string substituteStringView (std::string_view s, std::string_view toReplace, std::string_view replaceWith)
Returns a new string where occurrences of substring toReplace in string s are replaced by string replaceWith.
std::string_view stripWhiteSpace (std::string_view s)
Given a string view s, returns a new, narrower view on that string, skipping over any leading or trailing whitespace characters.
void addTerminalCharIfMissing (std::string &s, char c)
Detailed Description
Some helper functions for std::string.
Definition in file stringutil.h.
Function Documentation
addTerminalCharIfMissing()
void addTerminalCharIfMissing (std::string & s, char c) inline
Definition at line 84 of file stringutil.h.
{
  if (s.empty())
  {
    s+=c;
  }
  else
  {
    if (s[s.length()-1]!=c) s+=c;
  }
}
Referenced by fileToString(), and parseFile().
stripWhiteSpace()
std::string_view stripWhiteSpace (std::string_view s) inline
Given a string view s, returns a new, narrower view on that string, skipping over any leading or trailing whitespace characters.
Definition at line 72 of file stringutil.h.
{
  static auto isspace = [](char c){ return c==' ' || c=='\t' || c=='\n' || c=='\r'; };
  size_t sl = s.length();
  if (sl==0 || (!isspace(s[0]) && !isspace(s[sl-1]))) return s;
  size_t start=0, end=sl-1;
  while (start<sl && isspace(s[start])) start++;
  if (start==sl) return s.substr(0,0); // only whitespace
  while (end>start && isspace(s[end])) end--;
  return s.substr(start,end+1-start);
}
References end().
Referenced by DefinitionImpl::_setDocumentation(), addValidAliasToMap(), endBrief(), VhdlDocGen::getClass(), handleInheritanceGraph(), handleToc(), FileDefImpl::hasDetailedDescription(), parseIncludeOptions(), DefinitionImpl::setDocumentation(), DefinitionMixin< Base >::setDocumentation(), MemberDefImpl::setDocumentation(), Markdown::Private::writeBlockQuote(), and FileDefImpl::writeBriefDescription().
substituteInplace()
void substituteInplace (std::string & s, std::string_view toReplace, std::string_view replaceWith) inline
Replaces occurrences of substring toReplace in string s with string replaceWith.
Modifies s in place.
Definition at line 29 of file stringutil.h.
{
  std::string buf;
  size_t pos = 0;
  size_t prevPos = 0;
  buf.reserve(s.length());
  while ((pos=s.find(toReplace, prevPos))!=std::string::npos)
  {
    buf.append(s, prevPos, pos - prevPos);
    buf += replaceWith;
    prevPos = pos + toReplace.length();
  }
  buf.append(s, prevPos, s.size() - prevPos);
  s.swap(buf);
}
Referenced by replaceAliasArguments().
substituteStringView()
std::string substituteStringView (std::string_view s, std::string_view toReplace, std::string_view replaceWith) inline
Returns a new string where occurrences of substring toReplace in string s are replaced by string replaceWith.
Definition at line 50 of file stringutil.h.
{
  std::string buf;
  size_t pos = 0;
  size_t prevPos = 0;
  buf.reserve(s.length());
  while ((pos=s.find(toReplace, prevPos))!=std::string::npos)
  {
    buf.append(s, prevPos, pos - prevPos);
    buf += replaceWith;
    prevPos = pos + toReplace.length();
  }
  buf.append(s, prevPos, s.size() - prevPos);
  return buf;
}
Referenced by escapeAlias(), and replaceAliases().