Doxygen: DefinitionImpl::IMPL Class Reference
DefinitionImpl::IMPL Class Reference
Private data associated with a Symbol DefinitionImpl object.
Public Member Functions
void init (const QCString &df, const QCString &n)
void setDefFileName (const QCString &df)
Public Attributes
Definition * def = nullptr
SectionRefs sectionRefs
std::unordered_map< std::string, MemberDef * > sourceRefByDict
std::unordered_map< std::string, MemberDef * > sourceRefsDict
RefItemVector xrefListItems
GroupList partOfGroups
DeepCopyUniquePtr< DocInfo > details
DeepCopyUniquePtr< DocInfo > inbodyDocs
DeepCopyUniquePtr< BriefInfo > brief
DeepCopyUniquePtr< BodyInfo > body
QCString briefSignatures
QCString docSignatures
QCString localName
QCString qualifiedName
QCString ref
bool hidden = FALSE
bool isArtificial = FALSE
bool isAnonymous = FALSE
bool isExported = FALSE
Definition * outerScope = nullptr
QCString defFileName
QCString defFileExt
SrcLangExt lang = SrcLangExt::Unknown
QCString id
QCString name
bool isSymbol
QCString symbolName
int defLine
int defColumn
MemberVector referencesMembers
MemberVector referencedByMembers
Detailed Description
Private data associated with a Symbol DefinitionImpl object.
Definition at line 89 of file definition.cpp.
Member Function Documentation
init()
void DefinitionImpl::IMPL::init (const QCString & df, const QCString & n)
Definition at line 152 of file definition.cpp.
{
  setDefFileName(df);
  QCString lname = n;
  if (lname!="<globalScope>")
  {
    //extractNamespaceName(m_name,m_localName,ns);
    localName=stripScope(n);
  }
  else
  {
    localName=n;
  }
  //printf("localName=%s\n",qPrint(localName));
  brief.reset();
  details.reset();
  body.reset();
  inbodyDocs.reset();
  sourceRefByDict.clear();
  sourceRefsDict.clear();
  outerScope      = Doxygen::globalScope;
  hidden          = FALSE;
  isArtificial    = FALSE;
  isExported      = FALSE;
  lang            = SrcLangExt::Unknown;
}
References QCString::clear(), FALSE, Doxygen::globalScope, DefinitionImpl::isArtificial(), DefinitionImpl::isExported(), DefinitionImpl::localName(), stripScope(), and Unknown.
setDefFileName()
void DefinitionImpl::IMPL::setDefFileName (const QCString & df)
Definition at line 142 of file definition.cpp.
{
  defFileName = df;
  int lastDot = defFileName.findRev('.');
  if (lastDot!=-1)
  {
    defFileExt = defFileName.mid(lastDot);
  }
}
References defFileExt, and defFileName.
Member Data Documentation
body
DeepCopyUniquePtr<BodyInfo> DefinitionImpl::IMPL::body
Definition at line 107 of file definition.cpp.
brief
DeepCopyUniquePtr<BriefInfo> DefinitionImpl::IMPL::brief
Definition at line 106 of file definition.cpp.
briefSignatures
QCString DefinitionImpl::IMPL::briefSignatures
Definition at line 108 of file definition.cpp.
def
Definition* DefinitionImpl::IMPL::def = nullptr
Definition at line 95 of file definition.cpp.
defColumn
int DefinitionImpl::IMPL::defColumn
Definition at line 135 of file definition.cpp.
defFileExt
QCString DefinitionImpl::IMPL::defFileExt
Definition at line 125 of file definition.cpp.
Referenced by setDefFileName().
defFileName
QCString DefinitionImpl::IMPL::defFileName
Definition at line 124 of file definition.cpp.
Referenced by setDefFileName().
defLine
int DefinitionImpl::IMPL::defLine
Definition at line 134 of file definition.cpp.
details
DeepCopyUniquePtr<DocInfo> DefinitionImpl::IMPL::details
Definition at line 104 of file definition.cpp.
docSignatures
QCString DefinitionImpl::IMPL::docSignatures
Definition at line 109 of file definition.cpp.
hidden
bool DefinitionImpl::IMPL::hidden = FALSE
Definition at line 116 of file definition.cpp.
id
QCString DefinitionImpl::IMPL::id
Definition at line 129 of file definition.cpp.
inbodyDocs
DeepCopyUniquePtr<DocInfo> DefinitionImpl::IMPL::inbodyDocs
Definition at line 105 of file definition.cpp.
isAnonymous
bool DefinitionImpl::IMPL::isAnonymous = FALSE
Definition at line 118 of file definition.cpp.
isArtificial
bool DefinitionImpl::IMPL::isArtificial = FALSE
Definition at line 117 of file definition.cpp.
isExported
bool DefinitionImpl::IMPL::isExported = FALSE
Definition at line 119 of file definition.cpp.
isSymbol
bool DefinitionImpl::IMPL::isSymbol
Definition at line 132 of file definition.cpp.
lang
SrcLangExt DefinitionImpl::IMPL::lang = SrcLangExt::Unknown
Definition at line 127 of file definition.cpp.
localName
QCString DefinitionImpl::IMPL::localName
Definition at line 111 of file definition.cpp.
name
QCString DefinitionImpl::IMPL::name
Definition at line 131 of file definition.cpp.
outerScope
Definition* DefinitionImpl::IMPL::outerScope = nullptr
Definition at line 121 of file definition.cpp.
partOfGroups
GroupList DefinitionImpl::IMPL::partOfGroups
Definition at line 102 of file definition.cpp.
qualifiedName
QCString DefinitionImpl::IMPL::qualifiedName
Definition at line 113 of file definition.cpp.
ref
QCString DefinitionImpl::IMPL::ref
Definition at line 114 of file definition.cpp.
referencedByMembers
MemberVector DefinitionImpl::IMPL::referencedByMembers
Definition at line 138 of file definition.cpp.
referencesMembers
MemberVector DefinitionImpl::IMPL::referencesMembers
Definition at line 137 of file definition.cpp.
sectionRefs
SectionRefs DefinitionImpl::IMPL::sectionRefs
Definition at line 97 of file definition.cpp.
sourceRefByDict
std::unordered_map<std::string,MemberDef *> DefinitionImpl::IMPL::sourceRefByDict
Definition at line 99 of file definition.cpp.
sourceRefsDict
std::unordered_map<std::string,MemberDef *> DefinitionImpl::IMPL::sourceRefsDict
Definition at line 100 of file definition.cpp.
symbolName
QCString DefinitionImpl::IMPL::symbolName
Definition at line 133 of file definition.cpp.
xrefListItems
RefItemVector DefinitionImpl::IMPL::xrefListItems
Definition at line 101 of file definition.cpp.
The documentation for this class was generated from the following file:
src/definition.cpp