Doxygen: FilterCache Class Reference
FilterCache Class Reference
Classes
struct FilterCacheItem
Public Member Functions
bool getFileContents (const QCString &fileName, size_t startLine, size_t endLine, BufStr &str)
collects the part of file fileName starting at startLine and ending at endLine into buffer str.
Static Public Member Functions
static FilterCache & instance ()
Private Types
using LineOffsets = std::vector< size_t >
Private Member Functions
bool getFileContentsPipe (const QCString &fileName, const QCString &filter, size_t startLine, size_t endLine, BufStr &str)
bool getFileContentsDisk (const QCString &fileName, size_t startLine, size_t endLine, BufStr &str)
reads the fragment start at startLine and ending at endLine from file fileName into buffer str
void compileLineOffsets (const QCString &fileName, const BufStr &str)
computes the starting offset for each line for file fileName, whose contents should already be stored in buffer str.
auto getFragmentLocation (const LineOffsets &lineOffsets, size_t startLine, size_t endLine) -> std::tuple< size_t, size_t >
Returns the byte offset and size within a file of a fragment given the array of line offsets and the start and end line of the fragment.
void shrinkBuffer (BufStr &str, const QCString &fileName, size_t startLine, size_t endLine)
Shrinks buffer str which should hold the contents of fileName to the fragment starting a line startLine and ending at line endLine.
void readFragmentFromFile (BufStr &str, const QCString &fileName, size_t startOffset, size_t size=0)
Reads the fragment start at byte offset startOffset of file fileName into buffer str.
FilterCache ()
Private Attributes
std::unordered_map< std::string, FilterCacheItem > m_cache
std::unordered_map< std::string, LineOffsets > m_lineOffsets
std::mutex m_mutex
size_t m_endPos
Detailed Description
Cache for storing the result of filtering a file
Definition at line 590 of file definition.cpp.
Member Typedef Documentation
LineOffsets
using FilterCache::LineOffsets = std::vector<size_t> private
Definition at line 598 of file definition.cpp.
Constructor & Destructor Documentation
FilterCache()
FilterCache::FilterCache () inline private
Definition at line 786 of file definition.cpp.
: m_endPos(0) { }
Member Function Documentation
compileLineOffsets()
void FilterCache::compileLineOffsets (const QCString & fileName, const BufStr & str) inline private
computes the starting offset for each line for file fileName, whose contents should already be stored in buffer str.
Definition at line 727 of file definition.cpp.
    {
      const char *p=str.data();
      // line 1 (index 0) is at offset 0
      auto it = m_lineOffsets.insert(std::make_pair(fileName.data(),LineOffsets{0})).first;
      while (*p)
      {
        char c;
        while ((c=*p)!='\n' && c!=0) p++; // search until end of the line
        p++;
        it->second.push_back(p-str.data());
      }
    }
References BufStr::data(), QCString::data(), and m_lineOffsets.
Referenced by shrinkBuffer().
getFileContents()
bool FilterCache::getFileContents (const QCString & fileName, size_t startLine, size_t endLine, BufStr & str) inline
collects the part of file fileName starting at startLine and ending at endLine into buffer str.
Applies filtering if FILTER_SOURCE_FILES is enabled and the file extension matches a filter. Caches file information so that subsequent extraction of blocks from the same file can be performed efficiently
Definition at line 607 of file definition.cpp.
    {
      std::lock_guard<std::mutex> lock(m_mutex);
      bool filterSourceFiles = Config_getBool(FILTER_SOURCE_FILES);
      QCString filter = getFileFilter(fileName,TRUE);
      bool usePipe = !filter.isEmpty() && filterSourceFiles;
      return usePipe ? getFileContentsPipe(fileName,filter,startLine,endLine,str)
                     : getFileContentsDisk(fileName,startLine,endLine,str);
    }
References Config_getBool, getFileContentsDisk(), getFileContentsPipe(), getFileFilter(), QCString::isEmpty(), m_mutex, and TRUE.
Referenced by readCodeFragment().
getFileContentsDisk()
bool FilterCache::getFileContentsDisk (const QCString & fileName, size_t startLine, size_t endLine, BufStr & str) inline private
reads the fragment start at startLine and ending at endLine from file fileName into buffer str
Definition at line 703 of file definition.cpp.
    {
      // normal file
      //printf("getFileContents(%s): no filter\n",qPrint(fileName));
      auto it = m_lineOffsets.find(fileName.str());
      if (it == m_lineOffsets.end()) // new file
      {
        // read file completely into str buffer
        readFragmentFromFile(str,fileName,0);
        // shrink buffer to [startLine..endLine] part
        shrinkBuffer(str,fileName,startLine,endLine);
      }
      else // file already processed before
      {
        auto [ startLineOffset, fragmentSize] = getFragmentLocation(it->second,startLine,endLine);
        //printf("%s: existing file [%zu-%zu] -> start=%zu size=%zu\n",
        //    qPrint(fileName),startLine,endLine,startLineOffset,fragmentSize);
        readFragmentFromFile(str,fileName,startLineOffset,fragmentSize);
      }
      return true;
    }
References getFragmentLocation(), m_lineOffsets, readFragmentFromFile(), shrinkBuffer(), and QCString::str().
Referenced by getFileContents().
getFileContentsPipe()
bool FilterCache::getFileContentsPipe (const QCString & fileName, const QCString & filter, size_t startLine, size_t endLine, BufStr & str) inline private
Definition at line 617 of file definition.cpp.
    {
      auto it = m_cache.find(fileName.str());
      if (it!=m_cache.end()) // cache hit: reuse stored result
      {
        auto item = it->second;
        //printf("getFileContents(%s): cache hit\n",qPrint(fileName));
        // file already processed, get the results after filtering from the tmp file
        Debug::print(Debug::FilterOutput,0,"Reusing filter result for %s from %s at offset=%lld size=%zu\n",
               qPrint(fileName),qPrint(Doxygen::filterDBFileName),item.filePos,item.fileSize);
        auto it_off = m_lineOffsets.find(fileName.str());
        assert(it_off!=m_lineOffsets.end());
        auto [ startLineOffset, fragmentSize] = getFragmentLocation(it_off->second,startLine,endLine);
        //printf("%s: existing file [%zu-%zu]->[%zu-%zu] size=%zu\n",
        //    qPrint(fileName),startLine,endLine,startLineOffset,endLineOffset,fragmentSize);
        readFragmentFromFile(str, Doxygen::filterDBFileName.data(),
                             item.filePos+startLineOffset, fragmentSize);
        return true;
      }
      else // cache miss: filter active but file not previously processed
      {
        //printf("getFileContents(%s): cache miss\n",qPrint(fileName));
        // filter file
        QCString cmd=filter+" \""+fileName+"\"";
        Debug::print(Debug::ExtCmd,0,"Executing popen(`%s`)\n",qPrint(cmd));
        FILE *f = Portable::popen(cmd,"r");
        if (f==0)
        {
          // handle error
          err("Error opening filter pipe command '%s'\n",qPrint(cmd));
          str.addChar('\0');
          return false;
        }
        FILE *bf = Portable::fopen(Doxygen::filterDBFileName,"a+b");
        FilterCacheItem item;
        item.filePos = m_endPos;
        if (bf==0)
        {
          // handle error
          err("Error opening filter database file %s\n",qPrint(Doxygen::filterDBFileName));
          str.addChar('\0');
          Portable::pclose(f);
          return false;
        }
        // append the filtered output to the database file
        size_t size=0;
        while (!feof(f))
        {
          const int blockSize = 4096;
          char buf[blockSize];
          size_t bytesRead = fread(buf,1,blockSize,f);
          size_t bytesWritten = fwrite(buf,1,bytesRead,bf);
          if (bytesRead!=bytesWritten)
          {
            // handle error
            err("Failed to write to filter database %s. Wrote %zu out of %zu bytes\n",
                qPrint(Doxygen::filterDBFileName),bytesWritten,bytesRead);
            str.addChar('\0');
            Portable::pclose(f);
            fclose(bf);
            return false;
          }
          size+=bytesWritten;
          str.addArray(buf,static_cast<uint32_t>(bytesWritten));
        }
        str.addChar('\0');
        item.fileSize = size;
        // add location entry to the dictionary
        m_cache.insert(std::make_pair(fileName.str(),item));
        Debug::print(Debug::FilterOutput,0,"Storing new filter result for %s in %s at offset=%lld size=%zu\n",
               qPrint(fileName),qPrint(Doxygen::filterDBFileName),item.filePos,item.fileSize);
        // update end of file position
        m_endPos += size;
        Portable::pclose(f);
        fclose(bf);
        // shrink buffer to [startLine..endLine] part
        shrinkBuffer(str,fileName,startLine,endLine);
      }
      return true;
    }
References BufStr::addArray(), BufStr::addChar(), err, Debug::ExtCmd, FilterCache::FilterCacheItem::filePos, FilterCache::FilterCacheItem::fileSize, Doxygen::filterDBFileName, Debug::FilterOutput, Portable::fopen(), getFragmentLocation(), m_cache, m_endPos, m_lineOffsets, Portable::pclose(), Portable::popen(), Debug::print(), qPrint(), readFragmentFromFile(), shrinkBuffer(), and QCString::str().
Referenced by getFileContents().
getFragmentLocation()
auto FilterCache::getFragmentLocation (const LineOffsets & lineOffsets, size_t startLine, size_t endLine) -> std::tuple<size_t,size_t> inline private
Returns the byte offset and size within a file of a fragment given the array of line offsets and the start and end line of the fragment.
Definition at line 743 of file definition.cpp.
    {
      assert(startLine > 0);
      assert(startLine <= endLine);
      const size_t startLineOffset = lineOffsets[std::min(startLine-1,lineOffsets.size()-1)];
      const size_t endLineOffset   = lineOffsets[std::min(endLine,    lineOffsets.size()-1)];
      assert(startLineOffset <= endLineOffset);
      const size_t fragmentSize = endLineOffset-startLineOffset;
      return std::tie(startLineOffset,fragmentSize);
    };
Referenced by getFileContentsDisk(), getFileContentsPipe(), and shrinkBuffer().
instance()
FilterCache & FilterCache::instance () static
Definition at line 793 of file definition.cpp.
{
  static FilterCache theInstance;
  return theInstance;
}
Referenced by readCodeFragment().
readFragmentFromFile()
void FilterCache::readFragmentFromFile (BufStr & str, const QCString & fileName, size_t startOffset, size_t size = 0) inline private
Reads the fragment start at byte offset startOffset of file fileName into buffer str.
Result will be a null terminated. If size==0 the whole file will be read and startOffset is ignored. If size>0, size bytes will be read.
Definition at line 775 of file definition.cpp.
    {
      std::ifstream ifs = Portable::openInputStream(fileName,true,true);
      if (size==0) { startOffset=0; size = static_cast<size_t>(ifs.tellg()); }
      ifs.seekg(startOffset, std::ios::beg);
      str.resize(size+1);
      ifs.read(str.data(), size);
      str.skip(size);
      str.addChar('\0');
    }
References BufStr::addChar(), BufStr::data(), Portable::openInputStream(), BufStr::resize(), and BufStr::skip().
Referenced by getFileContentsDisk(), and getFileContentsPipe().
shrinkBuffer()
void FilterCache::shrinkBuffer (BufStr & str, const QCString & fileName, size_t startLine, size_t endLine) inline private
Shrinks buffer str which should hold the contents of fileName to the fragment starting a line startLine and ending at line endLine.
Definition at line 757 of file definition.cpp.
    {
      // compute offsets from start for each line
      compileLineOffsets(fileName,str);
      auto it = m_lineOffsets.find(fileName.str());
      assert(it!=m_lineOffsets.end());
      const LineOffsets &lineOffsets = it->second;
      auto [ startLineOffset, fragmentSize] = getFragmentLocation(lineOffsets,startLine,endLine);
      //printf("%s: new file [%zu-%zu]->[%zu-%zu] size=%zu\n",
      //    qPrint(fileName),startLine,endLine,startLineOffset,endLineOffset,fragmentSize);
      str.dropFromStart(startLineOffset);
      str.resize(fragmentSize+1);
      str.at(fragmentSize)='\0';
    }
References BufStr::at(), compileLineOffsets(), BufStr::dropFromStart(), getFragmentLocation(), m_lineOffsets, BufStr::resize(), and QCString::str().
Referenced by getFileContentsDisk(), and getFileContentsPipe().
Member Data Documentation
m_cache
std::unordered_map<std::string,FilterCacheItem> FilterCache::m_cache private
Definition at line 787 of file definition.cpp.
Referenced by getFileContentsPipe().
m_endPos
size_t FilterCache::m_endPos private
Definition at line 790 of file definition.cpp.
Referenced by getFileContentsPipe().
m_lineOffsets
std::unordered_map<std::string,LineOffsets> FilterCache::m_lineOffsets private
Definition at line 788 of file definition.cpp.
Referenced by compileLineOffsets(), getFileContentsDisk(), getFileContentsPipe(), and shrinkBuffer().
m_mutex
std::mutex FilterCache::m_mutex private
Definition at line 789 of file definition.cpp.
Referenced by getFileContents().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/definition.cpp