Doxygen: GroupDefImpl Class Reference
GroupDefImpl Class Reference
Public Member Functions
GroupDefImpl (const QCString &fileName, int line, const QCString &name, const QCString &title, const QCString &refFileName=QCString())
virtual ~GroupDefImpl ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual QCString displayName (bool=TRUE) const
virtual QCString groupTitle () const
virtual void setGroupTitle (const QCString &newtitle)
virtual bool hasGroupTitle () const
virtual void addFile (FileDef *def)
virtual bool containsFile (const FileDef *def) const
virtual bool addClass (ClassDef *def)
virtual bool addConcept (ConceptDef *def)
virtual bool addNamespace (NamespaceDef *def)
virtual void addGroup (GroupDef *def)
virtual void addPage (PageDef *def)
virtual void addExample (PageDef *def)
virtual void addDir (DirDef *dd)
virtual bool insertMember (MemberDef *def, bool docOnly=FALSE)
virtual void removeMember (MemberDef *md)
virtual bool findGroup (const GroupDef *def) const
virtual void writeDocumentation (OutputList &ol)
virtual void writeMemberPages (OutputList &ol, int hierarchyLevel)
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const
virtual void writeTagFile (TextStream &)
virtual size_t numDocMembers () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool isASubGroup () const
virtual void computeAnchors ()
virtual void countMembers ()
virtual void addMembersToMemberGroup ()
virtual void distributeMemberGroupDocumentation ()
virtual void findSectionsInDocumentation ()
virtual void addListReferences ()
virtual void sortMemberLists ()
virtual bool subGrouping () const
virtual void setGroupScope (Definition *d)
virtual Definition * getGroupScope () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberGroupList & getMemberGroups () const
virtual const FileList & getFiles () const
virtual const ClassLinkedRefMap & getClasses () const
virtual const ConceptLinkedRefMap & getConcepts () const
virtual const NamespaceLinkedRefMap & getNamespaces () const
virtual const GroupList & getSubGroups () const
virtual const PageLinkedRefMap & getPages () const
virtual const DirList & getDirs () const
virtual const PageLinkedRefMap & getExamples () const
virtual bool hasDetailedDescription () const
virtual void sortSubGroups ()
Public Member Functions inherited from DefinitionMixin< GroupDef >
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~DefinitionMixin ()=default
virtual bool isAlias () const
virtual const QCString & name () const
virtual bool isAnonymous () const
virtual const QCString & localName () const
virtual QCString qualifiedName () const
virtual QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
virtual int docLine () const
virtual QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
virtual QCString briefDescriptionAsTooltip () const
virtual int briefLine () const
virtual QCString inbodyDocumentation () const
virtual QCString inbodyFile () const
virtual int inbodyLine () const
virtual QCString briefFile () const
virtual QCString getDefFileName () const
virtual QCString getDefFileExtension () const
virtual int getDefLine () const
virtual int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
virtual bool isHidden () const
virtual bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
virtual QCString externalReference (const QCString &relPath) const
virtual int getStartDefLine () const
virtual int getStartBodyLine () const
virtual int getEndBodyLine () const
virtual const FileDef * getBodyDef () const
virtual SrcLangExt getLanguage () const
virtual const GroupList & partOfGroups () const
virtual bool isLinkableViaGroup () const
virtual const RefItemVector & xrefListItems () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual Definition * getOuterScope () const
virtual const MemberVector & getReferencesMembers () const
virtual const MemberVector & getReferencedByMembers () const
virtual bool hasSections () const
virtual bool hasSources () const
virtual bool hasBriefDescription () const
virtual QCString id () const
virtual const SectionRefs & getSectionRefs () const
virtual void setName (const QCString &name)
virtual void setId (const QCString &name)
virtual void setDefFile (const QCString &df, int defLine, int defColumn)
virtual void setDocumentation (const QCString &doc, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const QCString &brief, const QCString &briefFile, int briefLine)
virtual void setInbodyDocumentation (const QCString &doc, const QCString &docFile, int docLine)
virtual void setReference (const QCString &r)
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)
virtual void setBodySegment (int defLine, int bls, int ble)
virtual void setBodyDef (const FileDef *fd)
virtual void addSourceReferencedBy (MemberDef *md)
virtual void addSourceReferences (MemberDef *md)
virtual void setRefItems (const RefItemVector &sli)
virtual void mergeRefItems (Definition *def)
virtual void mergeReferences (const Definition *other)
virtual void mergeReferencedBy (const Definition *other)
virtual void addInnerCompound (Definition *def)
virtual void setOuterScope (Definition *def)
virtual void setHidden (bool b)
virtual void setArtificial (bool b)
virtual void setLanguage (SrcLangExt lang)
virtual void writeSourceDef (OutputList &ol, const QCString &scopeName) const
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const
virtual bool hasSourceRefs () const
virtual bool hasSourceReffedBy () const
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const
virtual void makePartOfGroup (GroupDef *gd)
virtual void writeNavigationPath (OutputList &ol) const
virtual QCString navigationPathAsString () const
virtual QCString pathFragment () const
virtual void writeDocAnchorsToTagFile (TextStream &fs) const
virtual void setLocalName (const QCString &name)
virtual void addSectionsToIndex ()
virtual void writeToc (OutputList &ol, const LocalToc &lt) const
virtual void computeTooltip ()
virtual void _setSymbolName (const QCString &name)
virtual QCString _symbolName () const
Public Member Functions inherited from DefinitionMutable
virtual ~DefinitionMutable ()=default
Public Member Functions inherited from Definition
virtual ~Definition ()=default
Private Member Functions
void addMemberListToGroup (MemberList *, bool(MemberDef::*)() const)
void addMemberToList (MemberListType lt, MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void removeMemberFromList (MemberListType lt, MemberDef *md)
void writeGroupGraph (OutputList &ol)
void writeFiles (OutputList &ol, const QCString &title)
void writeNamespaces (OutputList &ol, const QCString &title)
void writeNestedGroups (OutputList &ol, const QCString &title)
void writeDirs (OutputList &ol, const QCString &title)
void writeClasses (OutputList &ol, const QCString &title)
void writeConcepts (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void writePageDocumentation (OutputList &ol)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void writeSummaryLinks (OutputList &ol) const
void updateLanguage (const Definition *)
Private Attributes
QCString m_title
bool m_titleSet
QCString m_fileName
FileList m_fileList
ClassLinkedRefMap m_classes
ConceptLinkedRefMap m_concepts
NamespaceLinkedRefMap m_namespaces
GroupList m_groups
PageLinkedRefMap m_pages
PageLinkedRefMap m_examples
DirList m_dirList
MemberList m_allMemberList
MemberNameInfoLinkedMap m_allMemberNameInfoLinkedMap
Definition * m_groupScope
MemberLists m_memberLists
MemberGroupList m_memberGroups
bool m_subGrouping
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeMember = 3 ,
TypeGroup = 4 , TypePackage = 5 , TypePage = 6 , TypeDir = 7 ,
TypeConcept = 8
}
Protected Member Functions inherited from DefinitionMixin< GroupDef >
DefinitionMixin (const DefinitionMixin &def)=default
Detailed Description
Definition at line 52 of file groupdef.cpp.
Constructor & Destructor Documentation
GroupDefImpl()
GroupDefImpl::GroupDefImpl (const QCString & fileName, int line, const QCString & name, const QCString & title, const QCString & refFileName = QCString())
Definition at line 172 of file groupdef.cpp.
                                                : DefinitionMixin(df,dl,1,na),
                    m_allMemberList(MemberListType_allMembersList,MemberListContainer::Group)
{
  if (!refFileName.isEmpty())
  {
    m_fileName=stripExtension(refFileName);
  }
  else
  {
    m_fileName = convertNameToFile(QCString("group_")+na);
  }
  setGroupTitle( t );
  //visited = 0;
  m_groupScope = 0;
  m_subGrouping=Config_getBool(SUBGROUPING);
}
References Config_getBool, convertNameToFile(), QCString::isEmpty(), m_fileName, m_groupScope, m_subGrouping, setGroupTitle(), and stripExtension().
~GroupDefImpl()
GroupDefImpl::~GroupDefImpl () virtual
Definition at line 191 of file groupdef.cpp.
{
}
Member Function Documentation
addClass()
bool GroupDefImpl::addClass (ClassDef * def) virtual
Implements GroupDef.
Definition at line 257 of file groupdef.cpp.
{
  if (cd->isHidden()) return FALSE;
  updateLanguage(cd);
  QCString qn = cd->name();
  if (m_classes.find(qn)==0)
  {
    m_classes.add(qn,cd);
    return TRUE;
  }
  return FALSE;
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), FALSE, LinkedRefMap< T, Hash, KeyEqual, Map >::find(), Definition::isHidden(), m_classes, Definition::name(), TRUE, and updateLanguage().
addConcept()
bool GroupDefImpl::addConcept (ConceptDef * def) virtual
Implements GroupDef.
Definition at line 270 of file groupdef.cpp.
{
  if (cd->isHidden()) return FALSE;
  QCString qn = cd->name();
  if (m_concepts.find(qn)==0)
  {
    m_concepts.add(qn,cd);
    return TRUE;
  }
  return FALSE;
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), FALSE, LinkedRefMap< T, Hash, KeyEqual, Map >::find(), Definition::isHidden(), m_concepts, Definition::name(), and TRUE.
addDir()
void GroupDefImpl::addDir (DirDef * dd) virtual
Implements GroupDef.
Definition at line 295 of file groupdef.cpp.
{
  if (def->isHidden()) return;
  m_dirList.push_back(def);
}
References Definition::isHidden(), and m_dirList.
addExample()
void GroupDefImpl::addExample (PageDef * def) virtual
Implements GroupDef.
Definition at line 309 of file groupdef.cpp.
{
  if (def->isHidden()) return;
  m_examples.add(def->name(),def);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::isHidden(), m_examples, and Definition::name().
addFile()
void GroupDefImpl::addFile (FileDef * def) virtual
Implements GroupDef.
Definition at line 238 of file groupdef.cpp.
{
  bool sortBriefDocs = Config_getBool(SORT_BRIEF_DOCS);
  if (def->isHidden()) return;
  updateLanguage(def);
  if (sortBriefDocs)
    m_fileList.insert( std::upper_bound( m_fileList.begin(), m_fileList.end(), def,
                                         [](const auto &fd1, const auto &fd2)
                                         { return qstricmp(fd1->name(),fd2->name())<0; }),
                       def);
  else
    m_fileList.push_back(def);
}
References Config_getBool, Definition::isHidden(), m_fileList, and updateLanguage().
addGroup()
void GroupDefImpl::addGroup (GroupDef * def) virtual
Implements GroupDef.
Definition at line 571 of file groupdef.cpp.
{
  //printf("adding group '%s' to group '%s'\n",qPrint(def->name()),qPrint(name()));
  //if (Config_getBool(SORT_MEMBER_DOCS))
  //  groupList->inSort(def);
  //else
  m_groups.push_back(def);
}
References m_groups.
addListReferences()
void GroupDefImpl::addListReferences () virtual
Implements GroupDef.
Definition at line 1586 of file groupdef.cpp.
{
  {
    const RefItemVector &xrefItems = xrefListItems();
    addRefItem(xrefItems,
             getOutputFileBase(),
             theTranslator->trGroup(TRUE,TRUE),
             getOutputFileBase(),name(),
             QCString(),
             0
            );
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->addListReferences(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
      ml->addListReferences(this);
    }
  }
}
References addRefItem(), getOutputFileBase(), m_memberGroups, m_memberLists, MemberListType_documentationLists, DefinitionMixin< GroupDef >::name(), theTranslator, Translator::trGroup(), TRUE, and DefinitionMixin< GroupDef >::xrefListItems().
addMemberListToGroup()
void GroupDefImpl::addMemberListToGroup (MemberList * , bool(MemberDef::*)() const) private
addMembersToMemberGroup()
void GroupDefImpl::addMembersToMemberGroup () virtual
Implements GroupDef.
Definition at line 316 of file groupdef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ::addMembersToMemberGroup(ml.get(),&m_memberGroups,this);
    }
  }
}
References addMembersToMemberGroup(), m_memberGroups, m_memberLists, and MemberListType_declarationLists.
Referenced by addMembersToMemberGroup().
addMemberToList()
void GroupDefImpl::addMemberToList (MemberListType lt, MemberDef * md) private
Definition at line 1611 of file groupdef.cpp.
{
  bool sortBriefDocs = Config_getBool(SORT_BRIEF_DOCS);
  bool sortMemberDocs = Config_getBool(SORT_MEMBER_DOCS);
  const auto &ml = m_memberLists.get(lt,MemberListContainer::Group);
  ml->setNeedsSorting(
      ((ml->listType()&MemberListType_declarationLists) && sortBriefDocs) ||
      ((ml->listType()&MemberListType_documentationLists) && sortMemberDocs));
  ml->push_back(md);
}
References Config_getBool, MemberLists::get(), Group, m_memberLists, MemberListType_declarationLists, and MemberListType_documentationLists.
Referenced by insertMember().
addNamespace()
bool GroupDefImpl::addNamespace (NamespaceDef * def) virtual
Implements GroupDef.
Definition at line 282 of file groupdef.cpp.
{
  //printf("adding namespace hidden=%d\n",def->isHidden());
  if (def->isHidden()) return false;
  if (m_namespaces.find(def->name())==0)
  {
    updateLanguage(def);
    m_namespaces.add(def->name(),def);
    return true;
  }
  return false;
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), LinkedRefMap< T, Hash, KeyEqual, Map >::find(), Definition::isHidden(), m_namespaces, Definition::name(), and updateLanguage().
addPage()
void GroupDefImpl::addPage (PageDef * def) virtual
Implements GroupDef.
Definition at line 301 of file groupdef.cpp.
{
  if (def->isHidden()) return;
  //printf("Making page %s part of a group\n",qPrint(def->name));
  m_pages.add(def->name(),def);
  def->makePartOfGroup(this);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::isHidden(), m_pages, DefinitionMutable::makePartOfGroup(), and Definition::name().
anchor()
virtual QCString GroupDefImpl::anchor () const inline virtual
Returns the anchor within a page where this item can be found
Implements GroupDef.
Definition at line 61 of file groupdef.cpp.
{ return QCString(); }
codeSymbolType()
virtual CodeSymbolType GroupDefImpl::codeSymbolType () const inline virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 59 of file groupdef.cpp.
{ return CodeSymbolType::Default; }
References Default.
computeAnchors()
void GroupDefImpl::computeAnchors () virtual
Compute the HTML anchor names for all members in the group
Implements GroupDef.
Definition at line 611 of file groupdef.cpp.
{
  //printf("GroupDefImpl::computeAnchors()\n");
  m_allMemberList.setAnchors();
}
References m_allMemberList, and MemberList::setAnchors().
containsFile()
bool GroupDefImpl::containsFile (const FileDef * def) const virtual
Implements GroupDef.
Definition at line 252 of file groupdef.cpp.
{
  return std::find(m_fileList.cbegin(),m_fileList.cend(), def) != m_fileList.cend();
}
References m_fileList.
countMembers()
void GroupDefImpl::countMembers () virtual
Implements GroupDef.
Definition at line 585 of file groupdef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    ml->countDecMembers();
    ml->countDocMembers();
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->countDecMembers();
    mg->countDocMembers();
  }
}
References m_memberGroups, and m_memberLists.
definitionType()
virtual DefType GroupDefImpl::definitionType () const inline virtual
Use this for dynamic inspection of the type of the derived class
Implements GroupDef.
Definition at line 58 of file groupdef.cpp.
{ return TypeGroup; }
References Definition::TypeGroup.
displayName()
virtual QCString GroupDefImpl::displayName (bool includeScope = TRUE) const inline virtual
Returns the name of the definition as it appears in the output
Implements GroupDef.
Definition at line 62 of file groupdef.cpp.
{ return hasGroupTitle() ? m_title : DefinitionMixin::name(); }
References hasGroupTitle(), m_title, and DefinitionMixin< Base >::name().
distributeMemberGroupDocumentation()
void GroupDefImpl::distributeMemberGroupDocumentation () virtual
Implements GroupDef.
Definition at line 211 of file groupdef.cpp.
{
  for (const auto &mg : m_memberGroups)
  {
    mg->distributeMemberGroupDocumentation();
  }
}
References m_memberGroups.
endMemberDeclarations()
void GroupDefImpl::endMemberDeclarations (OutputList & ol) private
Definition at line 1020 of file groupdef.cpp.
{
  ol.endMemberSections();
}
References OutputList::endMemberSections().
Referenced by writeDocumentation().
endMemberDocumentation()
void GroupDefImpl::endMemberDocumentation (OutputList & ol) private
Definition at line 1036 of file groupdef.cpp.
{
  //printf("** GroupDefImpl::endMemberDocumentation()\n");
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.popGeneratorState();
    Doxygen::suppressDocWarnings = FALSE;
  }
}
References Config_getBool, FALSE, OutputList::popGeneratorState(), and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
findGroup()
bool GroupDefImpl::findGroup (const GroupDef * def) const virtual
Implements GroupDef.
Definition at line 555 of file groupdef.cpp.
{
  if (this==def)
  {
    return TRUE;
  }
  for (const auto &gd : m_groups)
  {
    if (gd->findGroup(def))
    {
      return TRUE;
    }
  }
  return FALSE;
}
References FALSE, m_groups, and TRUE.
findSectionsInDocumentation()
void GroupDefImpl::findSectionsInDocumentation () virtual
Implements GroupDef.
Definition at line 219 of file groupdef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
  for (const auto &mg : m_memberGroups)
  {
    mg->findSectionsInDocumentation(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ml->findSectionsInDocumentation(this);
    }
  }
}
References DefinitionMixin< GroupDef >::briefDescription(), DefinitionMixin< GroupDef >::docFile(), docFindSections(), DefinitionMixin< GroupDef >::documentation(), m_memberGroups, m_memberLists, and MemberListType_declarationLists.
getClasses()
virtual const ClassLinkedRefMap & GroupDefImpl::getClasses () const inline virtual
Implements GroupDef.
Definition at line 107 of file groupdef.cpp.
{ return m_classes; }
References m_classes.
getConcepts()
virtual const ConceptLinkedRefMap & GroupDefImpl::getConcepts () const inline virtual
Implements GroupDef.
Definition at line 108 of file groupdef.cpp.
{ return m_concepts; }
References m_concepts.
getDirs()
virtual const DirList & GroupDefImpl::getDirs () const inline virtual
Implements GroupDef.
Definition at line 112 of file groupdef.cpp.
{ return m_dirList; }
References m_dirList.
getExamples()
virtual const PageLinkedRefMap & GroupDefImpl::getExamples () const inline virtual
Implements GroupDef.
Definition at line 113 of file groupdef.cpp.
{ return m_examples; }
References m_examples.
getFiles()
virtual const FileList & GroupDefImpl::getFiles () const inline virtual
Implements GroupDef.
Definition at line 106 of file groupdef.cpp.
{ return m_fileList; }
References m_fileList.
getGroupScope()
virtual Definition * GroupDefImpl::getGroupScope () const inline virtual
Implements GroupDef.
Definition at line 98 of file groupdef.cpp.
{ return m_groupScope; }
References m_groupScope.
getMemberGroups()
virtual const MemberGroupList & GroupDefImpl::getMemberGroups () const inline virtual
Implements GroupDef.
Definition at line 104 of file groupdef.cpp.
{ return m_memberGroups; }
References m_memberGroups.
getMemberList()
MemberList * GroupDefImpl::getMemberList (MemberListType lt) const virtual
Implements GroupDef.
Definition at line 1714 of file groupdef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()==lt)
    {
      return ml.get();
    }
  }
  return 0;
}
References m_memberLists.
Referenced by removeMemberFromList(), writeMemberDeclarations(), writeMemberDocumentation(), writeSummaryLinks(), and writeTagFile().
getMemberLists()
virtual const MemberLists & GroupDefImpl::getMemberLists () const inline virtual
Implements GroupDef.
Definition at line 101 of file groupdef.cpp.
{ return m_memberLists; }
References m_memberLists.
getNamespaces()
virtual const NamespaceLinkedRefMap & GroupDefImpl::getNamespaces () const inline virtual
Implements GroupDef.
Definition at line 109 of file groupdef.cpp.
{ return m_namespaces; }
References m_namespaces.
getOutputFileBase()
QCString GroupDefImpl::getOutputFileBase () const virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements GroupDef.
Definition at line 1581 of file groupdef.cpp.
{
  return m_fileName;
}
References m_fileName.
Referenced by addListReferences(), writeDocumentation(), and writeTagFile().
getPages()
virtual const PageLinkedRefMap & GroupDefImpl::getPages () const inline virtual
Implements GroupDef.
Definition at line 111 of file groupdef.cpp.
{ return m_pages; }
References m_pages.
getSubGroups()
virtual const GroupList & GroupDefImpl::getSubGroups () const inline virtual
Implements GroupDef.
Definition at line 110 of file groupdef.cpp.
{ return m_groups; }
References m_groups.
Referenced by writeDocumentation().
groupTitle()
virtual QCString GroupDefImpl::groupTitle () const inline virtual
Implements GroupDef.
Definition at line 63 of file groupdef.cpp.
{ return m_title; }
References m_title.
hasDetailedDescription()
bool GroupDefImpl::hasDetailedDescription () const virtual
Implements GroupDef.
Definition at line 1782 of file groupdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  return ((!briefDescription().isEmpty() && repeatBrief) ||
         !documentation().isEmpty() ||
         !inbodyDocumentation().isEmpty()) &&
         (m_pages.size()!=numDocMembers());
}
References DefinitionMixin< GroupDef >::briefDescription(), Config_getBool, DefinitionMixin< GroupDef >::documentation(), DefinitionMixin< GroupDef >::inbodyDocumentation(), m_pages, numDocMembers(), and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
Referenced by writeBriefDescription().
hasGroupTitle()
virtual bool GroupDefImpl::hasGroupTitle () const inline virtual
Implements GroupDef.
Definition at line 65 of file groupdef.cpp.
{ return m_titleSet; }
References m_titleSet.
Referenced by displayName().
insertMember()
bool GroupDefImpl::insertMember (MemberDef * def, bool docOnly = FALSE) virtual
Implements GroupDef.
Definition at line 328 of file groupdef.cpp.
{
  if (md->isHidden()) return FALSE;
  updateLanguage(md);
  //printf("GroupDef(%s)::insertMember(%s)\n", qPrint(title), qPrint(md->name()));
  MemberNameInfo *mni = m_allMemberNameInfoLinkedMap.add(md->name());
  for (auto &srcMi : *mni)
  {
    const MemberDef *srcMd = srcMi->memberDef();
    if (srcMd==md) return FALSE; // already added before!
    bool sameScope = srcMd->getOuterScope()==md->getOuterScope() || // same class or namespace
        // both inside a file => definition and declaration do not have to be in the same file
         (srcMd->getOuterScope()->definitionType()==Definition::TypeFile &&
             md->getOuterScope()->definitionType()==Definition::TypeFile);
    const ArgumentList &srcMdAl  = srcMd->argumentList();
    const ArgumentList &mdAl     = md->argumentList();
    const ArgumentList &tSrcMdAl = srcMd->templateArguments();
    const ArgumentList &tMdAl    = md->templateArguments();
    if (srcMd->isFunction() && md->isFunction() && // both are a function
        (tSrcMdAl.size()==tMdAl.size()) &&       // same number of template arguments
        matchArguments2(srcMd->getOuterScope(),srcMd->getFileDef(),&srcMdAl,
                        md->getOuterScope(),md->getFileDef(),&mdAl,
                        TRUE,srcMd->getLanguage()
                       ) && // matching parameters
        sameScope // both are found in the same scope
       )
    {
      MemberDefMutable *mdm = toMemberDefMutable(md);
      if (mdm && srcMd->getGroupAlias()==0)
      {
        mdm->setGroupAlias(srcMd);
      }
      else if (mdm && md!=srcMd->getGroupAlias())
      {
        mdm->setGroupAlias(srcMd->getGroupAlias());
      }
      return FALSE; // member is the same as one that is already added
    }
  }
  mni->push_back(std::make_unique<MemberInfo>(md,md->protection(),md->virtualness(),FALSE));
  //printf("Added member!\n");
  m_allMemberList.push_back(md);
  switch(md->memberType())
  {
    case MemberType_Variable:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decVarMembers,md);
      }
      addMemberToList(MemberListType_docVarMembers,md);
      break;
    case MemberType_Function:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decFuncMembers,md);
      }
      addMemberToList(MemberListType_docFuncMembers,md);
      break;
    case MemberType_Typedef:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decTypedefMembers,md);
      }
      addMemberToList(MemberListType_docTypedefMembers,md);
      break;
    case MemberType_Enumeration:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decEnumMembers,md);
      }
      addMemberToList(MemberListType_docEnumMembers,md);
      break;
    case MemberType_EnumValue:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decEnumValMembers,md);
      }
      addMemberToList(MemberListType_docEnumValMembers,md);
      break;
    case MemberType_Define:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decDefineMembers,md);
      }
      addMemberToList(MemberListType_docDefineMembers,md);
      break;
    case MemberType_Signal:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decSignalMembers,md);
      }
      addMemberToList(MemberListType_docSignalMembers,md);
      break;
    case MemberType_Slot:
      if (md->protection()==Protection::Public)
      {
        if (!docOnly)
        {
          addMemberToList(MemberListType_decPubSlotMembers,md);
        }
        addMemberToList(MemberListType_docPubSlotMembers,md);
      }
      else if (md->protection()==Protection::Protected)
      {
        if (!docOnly)
        {
          addMemberToList(MemberListType_decProSlotMembers,md);
        }
        addMemberToList(MemberListType_docProSlotMembers,md);
      }
      else
      {
        if (!docOnly)
        {
          addMemberToList(MemberListType_decPriSlotMembers,md);
        }
        addMemberToList(MemberListType_docPriSlotMembers,md);
      }
      break;
    case MemberType_Event:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decEventMembers,md);
      }
      addMemberToList(MemberListType_docEventMembers,md);
      break;
    case MemberType_Property:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decPropMembers,md);
      }
      addMemberToList(MemberListType_docPropMembers,md);
      break;
    case MemberType_Friend:
      if (!docOnly)
      {
        addMemberToList(MemberListType_decFriendMembers,md);
      }
      addMemberToList(MemberListType_docFriendMembers,md);
      break;
    default:
      err("GroupDefImpl::insertMembers(): "
           "member '%s' (typeid=%d) with scope '%s' inserted in group scope '%s'!\n",
           qPrint(md->name()),md->memberType(),
           md->getClassDef() ? qPrint(md->getClassDef()->name()) : "",
           qPrint(name()));
  }
  return TRUE;
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), addMemberToList(), MemberDef::argumentList(), Definition::definitionType(), err, FALSE, MemberDef::getClassDef(), MemberDef::getFileDef(), MemberDef::getGroupAlias(), Definition::getLanguage(), Definition::getOuterScope(), MemberDef::isFunction(), Definition::isHidden(), m_allMemberList, m_allMemberNameInfoLinkedMap, matchArguments2(), MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decEnumValMembers, MemberListType_decEventMembers, MemberListType_decFriendMembers, MemberListType_decFuncMembers, MemberListType_decPriSlotMembers, MemberListType_decPropMembers, MemberListType_decProSlotMembers, MemberListType_decPubSlotMembers, MemberListType_decSignalMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docEnumMembers, MemberListType_docEnumValMembers, MemberListType_docEventMembers, MemberListType_docFriendMembers, MemberListType_docFuncMembers, MemberListType_docPriSlotMembers, MemberListType_docPropMembers, MemberListType_docProSlotMembers, MemberListType_docPubSlotMembers, MemberListType_docSignalMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberDef::memberType(), MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Property, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, DefinitionMixin< GroupDef >::name(), Definition::name(), Protected, MemberDef::protection(), Public, MemberVector::push_back(), MemberNameInfo::push_back(), qPrint(), MemberDefMutable::setGroupAlias(), ArgumentList::size(), MemberDef::templateArguments(), toMemberDefMutable(), TRUE, Definition::TypeFile, updateLanguage(), and MemberDef::virtualness().
isASubGroup()
bool GroupDefImpl::isASubGroup () const virtual
Implements GroupDef.
Definition at line 580 of file groupdef.cpp.
{
  return !partOfGroups().empty();
}
References DefinitionMixin< GroupDef >::partOfGroups().
isLinkable()
bool GroupDefImpl::isLinkable () const virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements GroupDef.
Definition at line 1767 of file groupdef.cpp.
{
  return hasUserDocumentation();
}
References DefinitionMixin< GroupDef >::hasUserDocumentation().
Referenced by isLinkableInProject().
isLinkableInProject()
bool GroupDefImpl::isLinkableInProject () const virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements GroupDef.
Definition at line 1762 of file groupdef.cpp.
{
  return !isReference() && isLinkable();
}
References isLinkable(), and DefinitionMixin< GroupDef >::isReference().
numDocMembers()
size_t GroupDefImpl::numDocMembers () const virtual
Implements GroupDef.
Definition at line 599 of file groupdef.cpp.
{
  return m_fileList.size()+
         m_classes.size()+
         m_namespaces.size()+
         m_groups.size()+
         m_allMemberList.size()+
         m_pages.size()+
         m_examples.size();
}
References m_allMemberList, m_classes, m_examples, m_fileList, m_groups, m_namespaces, m_pages, LinkedRefMap< T, Hash, KeyEqual, Map >::size(), and MemberVector::size().
Referenced by hasDetailedDescription(), and writeDetailedDescription().
removeMember()
void GroupDefImpl::removeMember (MemberDef * md) virtual
Implements GroupDef.
Definition at line 481 of file groupdef.cpp.
{
  // fprintf(stderr, "GroupDef(%s)::removeMember( %s )\n", qPrint(title), qPrint(md->name()));
  MemberNameInfo *mni = m_allMemberNameInfoLinkedMap.find(md->name());
  if (mni)
  {
    m_allMemberNameInfoLinkedMap.del(md->name());
    removeMemberFromList(MemberListType_allMembersList,md);
    switch(md->memberType())
    {
      case MemberType_Variable:
        removeMemberFromList(MemberListType_decVarMembers,md);
        removeMemberFromList(MemberListType_docVarMembers,md);
        break;
      case MemberType_Function:
        removeMemberFromList(MemberListType_decFuncMembers,md);
        removeMemberFromList(MemberListType_docFuncMembers,md);
        break;
      case MemberType_Typedef:
        removeMemberFromList(MemberListType_decTypedefMembers,md);
        removeMemberFromList(MemberListType_docTypedefMembers,md);
        break;
      case MemberType_Enumeration:
        removeMemberFromList(MemberListType_decEnumMembers,md);
        removeMemberFromList(MemberListType_docEnumMembers,md);
        break;
      case MemberType_EnumValue:
        removeMemberFromList(MemberListType_decEnumValMembers,md);
        removeMemberFromList(MemberListType_docEnumValMembers,md);
        break;
      case MemberType_Define:
        removeMemberFromList(MemberListType_decDefineMembers,md);
        removeMemberFromList(MemberListType_docDefineMembers,md);
        break;
      case MemberType_Signal:
        removeMemberFromList(MemberListType_decSignalMembers,md);
        removeMemberFromList(MemberListType_docSignalMembers,md);
        break;
      case MemberType_Slot:
        if (md->protection()==Protection::Public)
        {
          removeMemberFromList(MemberListType_decPubSlotMembers,md);
          removeMemberFromList(MemberListType_docPubSlotMembers,md);
        }
        else if (md->protection()==Protection::Protected)
        {
          removeMemberFromList(MemberListType_decProSlotMembers,md);
          removeMemberFromList(MemberListType_docProSlotMembers,md);
        }
        else
        {
          removeMemberFromList(MemberListType_decPriSlotMembers,md);
          removeMemberFromList(MemberListType_docPriSlotMembers,md);
        }
        break;
      case MemberType_Event:
        removeMemberFromList(MemberListType_decEventMembers,md);
        removeMemberFromList(MemberListType_docEventMembers,md);
        break;
      case MemberType_Property:
        removeMemberFromList(MemberListType_decPropMembers,md);
        removeMemberFromList(MemberListType_docPropMembers,md);
        break;
      case MemberType_Friend:
        removeMemberFromList(MemberListType_decFriendMembers,md);
        removeMemberFromList(MemberListType_docFriendMembers,md);
        break;
      default:
        err("GroupDefImpl::removeMember(): unexpected member remove in file!\n");
    }
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::del(), err, LinkedMap< T, Hash, KeyEqual, Map >::find(), m_allMemberNameInfoLinkedMap, MemberListType_allMembersList, MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decEnumValMembers, MemberListType_decEventMembers, MemberListType_decFriendMembers, MemberListType_decFuncMembers, MemberListType_decPriSlotMembers, MemberListType_decPropMembers, MemberListType_decProSlotMembers, MemberListType_decPubSlotMembers, MemberListType_decSignalMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docEnumMembers, MemberListType_docEnumValMembers, MemberListType_docEventMembers, MemberListType_docFriendMembers, MemberListType_docFuncMembers, MemberListType_docPriSlotMembers, MemberListType_docPropMembers, MemberListType_docProSlotMembers, MemberListType_docPubSlotMembers, MemberListType_docSignalMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberDef::memberType(), MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Property, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, Definition::name(), Protected, MemberDef::protection(), Public, and removeMemberFromList().
removeMemberFromList()
void GroupDefImpl::removeMemberFromList (MemberListType lt, MemberDef * md) private
Definition at line 1748 of file groupdef.cpp.
{
  MemberList *ml = getMemberList(lt);
  if (ml) ml->remove(md);
}
References getMemberList(), and MemberVector::remove().
Referenced by removeMember().
setGroupScope()
virtual void GroupDefImpl::setGroupScope (Definition * d) inline virtual
Implements GroupDef.
Definition at line 97 of file groupdef.cpp.
{ m_groupScope = d; }
References m_groupScope.
setGroupTitle()
void GroupDefImpl::setGroupTitle (const QCString & newtitle) virtual
Implements GroupDef.
Definition at line 195 of file groupdef.cpp.
{
  if ( !t.isEmpty())
  {
    m_title = t;
    m_titleSet = TRUE;
  }
  else
  {
    m_title = name();
    m_title[0]=static_cast<char>(toupper(m_title[0]));
    m_titleSet = FALSE;
  }
}
References FALSE, QCString::isEmpty(), m_title, m_titleSet, DefinitionMixin< GroupDef >::name(), and TRUE.
Referenced by GroupDefImpl().
sortMemberLists()
void GroupDefImpl::sortMemberLists () virtual
Implements GroupDef.
Definition at line 1682 of file groupdef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->needsSorting()) { ml->sort(); ml->setNeedsSorting(FALSE); }
  }
  if (Config_getBool(SORT_BRIEF_DOCS))
  {
    std::sort(m_dirList.begin(), m_dirList.end(), compareDirDefs);
    auto classComp = [](const ClassLinkedRefMap::Ptr &c1,const ClassLinkedRefMap::Ptr &c2)
    {
      return Config_getBool(SORT_BY_SCOPE_NAME)     ?
        qstricmp(c1->name(), c2->name())<0          :
        qstricmp(c1->className(), c2->className())<0;
    };
    std::sort(m_classes.begin(), m_classes.end(), classComp);
    auto namespaceComp = [](const NamespaceLinkedRefMap::Ptr &n1,const NamespaceLinkedRefMap::Ptr &n2)
    {
      return qstricmp(n1->name(),n2->name())<0;
    };
    std::sort(m_namespaces.begin(),m_namespaces.end(),namespaceComp);
  }
  else
  {
    groupClassesWithSameScope(m_classes);
    groupClassesWithSameScope(m_namespaces);
  }
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::begin(), ClassDef::className(), compareDirDefs(), Config_getBool, LinkedRefMap< T, Hash, KeyEqual, Map >::end(), FALSE, groupClassesWithSameScope(), m_classes, m_dirList, m_memberLists, m_namespaces, Definition::name(), and qstricmp().
sortSubGroups()
void GroupDefImpl::sortSubGroups () virtual
Implements GroupDef.
Definition at line 1754 of file groupdef.cpp.
{
  std::sort(m_groups.begin(),
            m_groups.end(),
            [](const auto &g1,const auto &g2)
            { return g1->groupTitle() < g2->groupTitle(); });
}
References m_groups.
startMemberDeclarations()
void GroupDefImpl::startMemberDeclarations (OutputList & ol) private
Definition at line 1015 of file groupdef.cpp.
{
  ol.startMemberSections();
}
References OutputList::startMemberSections().
Referenced by writeDocumentation().
startMemberDocumentation()
void GroupDefImpl::startMemberDocumentation (OutputList & ol) private
Definition at line 1025 of file groupdef.cpp.
{
  //printf("** GroupDefImpl::startMemberDocumentation()\n");
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.pushGeneratorState();
    ol.disable(OutputType::Html);
    Doxygen::suppressDocWarnings = TRUE;
  }
}
References Config_getBool, OutputList::disable(), Html, OutputList::pushGeneratorState(), Doxygen::suppressDocWarnings, and TRUE.
Referenced by writeDocumentation().
subGrouping()
virtual bool GroupDefImpl::subGrouping () const inline virtual
Implements GroupDef.
Definition at line 95 of file groupdef.cpp.
{ return m_subGrouping; }
References m_subGrouping.
updateLanguage()
void GroupDefImpl::updateLanguage (const Definition * d) private
Definition at line 1774 of file groupdef.cpp.
{
  if (getLanguage()==SrcLangExt_Unknown && d->getLanguage()!=SrcLangExt_Unknown)
  {
    setLanguage(d->getLanguage());
  }
}
References DefinitionMixin< GroupDef >::getLanguage(), Definition::getLanguage(), DefinitionMixin< GroupDef >::setLanguage(), and SrcLangExt_Unknown.
Referenced by addClass(), addFile(), addNamespace(), and insertMember().
writeAuthorSection()
void GroupDefImpl::writeAuthorSection (OutputList & ol) private
Definition at line 1046 of file groupdef.cpp.
{
  // write Author section (Man only)
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Man);
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), and TRUE.
Referenced by writeDocumentation().
writeBriefDescription()
void GroupDefImpl::writeBriefDescription (OutputList & ol) private
Definition at line 802 of file groupdef.cpp.
{
  if (hasBriefDescription())
  {
    auto parser { createDocParser() };
    auto ast    { validatingParseDoc(*parser.get(),
                                     briefFile(),briefLine(),this,0,
                                     briefDescription(),TRUE,FALSE,
                                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startParagraph();
      ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Man);
      ol.writeString(" - ");
      ol.popGeneratorState();
      ol.writeDoc(ast.get(),this,0);
      ol.pushGeneratorState();
      ol.disable(OutputType::RTF);
      ol.writeString(" \n");
      ol.enable(OutputType::RTF);
      if (hasDetailedDescription())
      {
        ol.disableAllBut(OutputType::Html);
        ol.startTextLink(QCString(),"details");
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
      }
      ol.popGeneratorState();
      ol.endParagraph();
    }
  }
  ol.writeSynopsis();
}
References DefinitionMixin< GroupDef >::briefDescription(), DefinitionMixin< GroupDef >::briefFile(), DefinitionMixin< GroupDef >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), FALSE, DefinitionMixin< GroupDef >::hasBriefDescription(), hasDetailedDescription(), Html, Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), RTF, OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeClasses()
void GroupDefImpl::writeClasses (OutputList & ol, const QCString & title) private
Definition at line 967 of file groupdef.cpp.
{
  // write list of classes
  m_classes.writeDeclaration(ol,0,title,FALSE);
}
References FALSE, m_classes, and ClassLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeConcepts()
void GroupDefImpl::writeConcepts (OutputList & ol, const QCString & title) private
Definition at line 973 of file groupdef.cpp.
{
  // write list of concepts
  m_concepts.writeDeclaration(ol,title,FALSE);
}
References FALSE, m_concepts, and ConceptLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeDetailedDescription()
void GroupDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) private
Definition at line 739 of file groupdef.cpp.
{
  if ((!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF))
      || !documentation().isEmpty() || !inbodyDocumentation().isEmpty()
     )
  {
    ol.pushGeneratorState();
    if (m_pages.size()!=numDocMembers()) // not only pages -> classical layout
    {
      ol.pushGeneratorState();
        ol.disable(OutputType::Html);
        ol.writeRuler();
      ol.popGeneratorState();
      ol.pushGeneratorState();
        ol.disableAllBut(OutputType::Html);
        ol.writeAnchor(QCString(),"details");
      ol.popGeneratorState();
    }
    else
    {
      ol.disableAllBut(OutputType::Man); // always print title for man page
    }
    ol.startGroupHeader();
    ol.parseText(title);
    ol.endGroupHeader();
    ol.popGeneratorState();
    // repeat brief description
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF))
    {
      ol.generateDoc(briefFile(),briefLine(),this,0,briefDescription(),FALSE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    // write separator between brief and details
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF) &&
        !documentation().isEmpty())
    {
      ol.pushGeneratorState();
      ol.disable(OutputType::Man);
      ol.disable(OutputType::RTF);
      ol.enableAll();
      ol.disableAllBut(OutputType::Man);
      ol.enable(OutputType::Latex);
      ol.writeString("\n\n");
      ol.popGeneratorState();
    }
    // write detailed documentation
    if (!documentation().isEmpty())
    {
      ol.generateDoc(docFile(),docLine(),this,0,documentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    // write inbody documentation
    if (!inbodyDocumentation().isEmpty())
    {
      ol.generateDoc(inbodyFile(),inbodyLine(),this,0,inbodyDocumentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
  }
}
References DefinitionMixin< GroupDef >::briefDescription(), DefinitionMixin< GroupDef >::briefFile(), DefinitionMixin< GroupDef >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< GroupDef >::docFile(), DefinitionMixin< GroupDef >::docLine(), DefinitionMixin< GroupDef >::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), FALSE, OutputList::generateDoc(), Html, DefinitionMixin< GroupDef >::inbodyDocumentation(), DefinitionMixin< GroupDef >::inbodyFile(), DefinitionMixin< GroupDef >::inbodyLine(), Latex, m_pages, Man, numDocMembers(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), RTF, LinkedRefMap< T, Hash, KeyEqual, Map >::size(), OutputList::startGroupHeader(), TRUE, OutputList::writeAnchor(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDirs()
void GroupDefImpl::writeDirs (OutputList & ol, const QCString & title) private
Definition at line 935 of file groupdef.cpp.
{
  // write list of directories
  if (!m_dirList.empty())
  {
    ol.startMemberHeader("dirs");
    ol.parseText(title);
    ol.endMemberHeader();
    ol.startMemberList();
    for(const auto dd : m_dirList)
    {
      if (!dd->hasDocumentation()) continue;
      ol.startMemberDeclaration();
      ol.startMemberItem(dd->getOutputFileBase(),OutputGenerator::MemberItemType::Normal);
      ol.parseText(theTranslator->trDir(FALSE,TRUE));
      ol.insertMemberAlign();
      ol.writeObjectLink(dd->getReference(),dd->getOutputFileBase(),QCString(),dd->shortName());
      ol.endMemberItem(OutputGenerator::MemberItemType::Normal);
      if (!dd->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
      {
        ol.startMemberDescription(dd->getOutputFileBase());
        ol.generateDoc(briefFile(),briefLine(),dd,0,dd->briefDescription(),FALSE,FALSE,
                       QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
        ol.endMemberDescription();
      }
      ol.endMemberDeclaration(QCString(),QCString());
    }
    ol.endMemberList();
  }
}
References DefinitionMixin< GroupDef >::briefFile(), DefinitionMixin< GroupDef >::briefLine(), Config_getBool, OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), FALSE, OutputList::generateDoc(), OutputList::insertMemberAlign(), m_dirList, OutputGenerator::Normal, OutputList::parseText(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trDir(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeDocumentation()
void GroupDefImpl::writeDocumentation (OutputList & ol) virtual
Implements GroupDef.
Definition at line 1108 of file groupdef.cpp.
{
  //bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  ol.pushGeneratorState();
  // Find out how deep this group is nested. In case of multiple parents, use the first one.
  int hierarchyLevel = 0;
  const GroupDef *gd = this;
  while (!gd->partOfGroups().empty())
  {
    gd = gd->partOfGroups().front();
    ++hierarchyLevel;
  }
  startFile(ol,getOutputFileBase(),name(),m_title,HighlightedItem::Modules,
            FALSE /* additionalIndices*/, QCString() /*altSidebarName*/, hierarchyLevel);
  ol.startHeaderSection();
  writeSummaryLinks(ol);
  ol.startTitleHead(getOutputFileBase());
  ol.pushGeneratorState();
  ol.disable(OutputType::Man);
  ol.parseText(m_title);
  ol.popGeneratorState();
  addGroupListToTitle(ol,this);
  ol.pushGeneratorState();
  ol.disable(OutputType::Man);
  ol.endTitleHead(getOutputFileBase(),m_title);
  ol.popGeneratorState();
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Man);
  ol.endTitleHead(getOutputFileBase(),name());
  if (!m_title.isEmpty())
  {
    ol.writeString(" - ");
    ol.parseText(m_title);
  }
  ol.popGeneratorState();
  ol.endHeaderSection();
  ol.startContents();
  //---------------------------------------- start flexible part -------------------------------
  SrcLangExt lang=getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Group))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
        startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::GroupClasses:
        if (ls) writeClasses(ol,ls->title(lang));
        break;
      case LayoutDocEntry::GroupConcepts:
        if (ls) writeConcepts(ol,ls->title(lang));
        break;
      case LayoutDocEntry::GroupInlineClasses:
        writeInlineClasses(ol);
        break;
      case LayoutDocEntry::GroupNamespaces:
        if (ls) writeNamespaces(ol,ls->title(lang));
        break;
      case LayoutDocEntry::MemberGroups:
        writeMemberGroups(ol);
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            writeMemberDeclarations(ol,lmd->type,lmd->title(lang));
          }
        }
        break;
      case LayoutDocEntry::MemberDeclEnd:
        endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::DetailedDesc:
        if (ls) writeDetailedDescription(ol,ls->title(lang));
        break;
      case LayoutDocEntry::MemberDefStart:
        startMemberDocumentation(ol);
        break;
      case LayoutDocEntry::MemberDef:
        {
          const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
          if (lmd)
          {
            writeMemberDocumentation(ol,lmd->type,lmd->title(lang));
          }
        }
        break;
      case LayoutDocEntry::MemberDefEnd:
        endMemberDocumentation(ol);
        break;
      case LayoutDocEntry::GroupNestedGroups:
        if (ls) writeNestedGroups(ol,ls->title(lang));
        break;
      case LayoutDocEntry::GroupPageDocs:
        writePageDocumentation(ol);
        break;
      case LayoutDocEntry::GroupDirs:
        if (ls) writeDirs(ol,ls->title(lang));
        break;
      case LayoutDocEntry::GroupFiles:
        if (ls) writeFiles(ol,ls->title(lang));
        break;
      case LayoutDocEntry::GroupGraph:
        writeGroupGraph(ol);
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::ClassIncludes:
      case LayoutDocEntry::ClassInheritanceGraph:
      case LayoutDocEntry::ClassNestedClasses:
      case LayoutDocEntry::ClassCollaborationGraph:
      case LayoutDocEntry::ClassAllMembersLink:
      case LayoutDocEntry::ClassUsedFiles:
      case LayoutDocEntry::ClassInlineClasses:
      case LayoutDocEntry::NamespaceNestedNamespaces:
      case LayoutDocEntry::NamespaceNestedConstantGroups:
      case LayoutDocEntry::NamespaceClasses:
      case LayoutDocEntry::NamespaceConcepts:
      case LayoutDocEntry::NamespaceInterfaces:
      case LayoutDocEntry::NamespaceStructs:
      case LayoutDocEntry::NamespaceExceptions:
      case LayoutDocEntry::NamespaceInlineClasses:
      case LayoutDocEntry::ConceptDefinition:
      case LayoutDocEntry::FileClasses:
      case LayoutDocEntry::FileConcepts:
      case LayoutDocEntry::FileInterfaces:
      case LayoutDocEntry::FileStructs:
      case LayoutDocEntry::FileExceptions:
      case LayoutDocEntry::FileNamespaces:
      case LayoutDocEntry::FileConstantGroups:
      case LayoutDocEntry::FileIncludes:
      case LayoutDocEntry::FileIncludeGraph:
      case LayoutDocEntry::FileIncludedByGraph:
      case LayoutDocEntry::FileSourceLink:
      case LayoutDocEntry::FileInlineClasses:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::Group entry list\n",lde->kind());
        break;
    }
  }
  //---------------------------------------- end flexible part -------------------------------
  for (auto &subgd : getSubGroups())
  {
    if (!subgd->isReference())
    {
      if (subgd->partOfGroups().front() == this)
      {
        ol.writePageLink(subgd->getOutputFileBase(), FALSE);
      }
      else
      {
        // Could write a note explaining that the subgroup belongs to another
        // group and add a link here.
      }
    }
  }
  endFile(ol);
  ol.popGeneratorState();
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    m_allMemberList.sort();
    writeMemberPages(ol, hierarchyLevel + 1);
  }
}
References addGroupListToTitle(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, LayoutDocEntry::ConceptDefinition, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, OutputList::disable(), OutputList::disableAllBut(), LayoutDocManager::docEntries(), endFile(), OutputList::endHeaderSection(), endMemberDeclarations(), endMemberDocumentation(), OutputList::endTitleHead(), err, FALSE, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::FileStructs, DefinitionMixin< GroupDef >::getLanguage(), getOutputFileBase(), getSubGroups(), LayoutDocManager::Group, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, LayoutDocManager::instance(), QCString::isEmpty(), m_allMemberList, m_title, Man, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, Modules, DefinitionMixin< GroupDef >::name(), LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, LayoutDocEntry::NamespaceStructs, OutputList::parseText(), Definition::partOfGroups(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), MemberVector::sort(), OutputList::startContents(), startFile(), OutputList::startHeaderSection(), startMemberDeclarations(), startMemberDocumentation(), OutputList::startTitleHead(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeClasses(), writeConcepts(), writeDetailedDescription(), writeDirs(), writeFiles(), writeGroupGraph(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeMemberPages(), writeNamespaces(), writeNestedGroups(), writePageDocumentation(), OutputList::writePageLink(), OutputList::writeString(), and writeSummaryLinks().
writeFiles()
void GroupDefImpl::writeFiles (OutputList & ol, const QCString & title) private
Definition at line 858 of file groupdef.cpp.
{
  // write list of files
  if (!m_fileList.empty())
  {
    ol.startMemberHeader("files");
    ol.parseText(title);
    ol.endMemberHeader();
    ol.startMemberList();
    for (const auto &fd : m_fileList)
    {
      if (!fd->hasDocumentation()) continue;
      ol.startMemberDeclaration();
      ol.startMemberItem(fd->getOutputFileBase(),OutputGenerator::MemberItemType::Normal);
      ol.docify(theTranslator->trFile(FALSE,TRUE)+" ");
      ol.insertMemberAlign();
      ol.writeObjectLink(fd->getReference(),fd->getOutputFileBase(),QCString(),fd->displayName());
      ol.endMemberItem(OutputGenerator::MemberItemType::Normal);
      if (!fd->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
      {
        ol.startMemberDescription(fd->getOutputFileBase());
        ol.generateDoc(briefFile(),briefLine(),fd,0,fd->briefDescription(),FALSE,FALSE,
                       QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
        ol.endMemberDescription();
      }
      ol.endMemberDeclaration(QCString(),QCString());
    }
    ol.endMemberList();
  }
}
References DefinitionMixin< GroupDef >::briefFile(), DefinitionMixin< GroupDef >::briefLine(), Config_getBool, OutputList::docify(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), FALSE, OutputList::generateDoc(), OutputList::insertMemberAlign(), m_fileList, OutputGenerator::Normal, OutputList::parseText(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trFile(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeGroupGraph()
void GroupDefImpl::writeGroupGraph (OutputList & ol) private
Definition at line 838 of file groupdef.cpp.
{
  if (Config_getBool(HAVE_DOT) /*&& Config_getBool(GROUP_GRAPHS)*/ )
  {
    DotGroupCollaboration graph(this);
    if (!graph.isTrivial())
    {
      msg("Generating dependency graph for group %s\n",qPrint(qualifiedName()));
      ol.pushGeneratorState();
      ol.disable(OutputType::Man);
      //ol.startParagraph();
      ol.startGroupCollaboration();
      ol.parseText(theTranslator->trCollaborationDiagram(m_title));
      ol.endGroupCollaboration(graph);
      //ol.endParagraph();
      ol.popGeneratorState();
    }
  }
}
References Config_getBool, OutputList::disable(), OutputList::endGroupCollaboration(), DotGroupCollaboration::isTrivial(), m_title, Man, msg(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), qPrint(), DefinitionMixin< GroupDef >::qualifiedName(), OutputList::startGroupCollaboration(), theTranslator, and Translator::trCollaborationDiagram().
Referenced by writeDocumentation().
writeInlineClasses()
void GroupDefImpl::writeInlineClasses (OutputList & ol) private
Definition at line 979 of file groupdef.cpp.
{
  m_classes.writeDocumentation(ol);
}
References m_classes, and ClassLinkedRefMap::writeDocumentation().
Referenced by writeDocumentation().
writeMemberDeclarations()
void GroupDefImpl::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1726 of file groupdef.cpp.
{
  bool optimizeVhdl = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  MemberList * ml = getMemberList(lt);
  if (optimizeVhdl && ml)
  {
    VhdlDocGen::writeVhdlDeclarations(ml,ol,this,0,0,0);
    return;
  }
  if (ml)
  {
    ml->writeDeclarations(ol,0,0,0,this,title,QCString());
  }
}
References Config_getBool, getMemberList(), MemberList::writeDeclarations(), and VhdlDocGen::writeVhdlDeclarations().
Referenced by writeDocumentation().
writeMemberDocumentation()
void GroupDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1742 of file groupdef.cpp.
{
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDocumentation(ol,name(),this,title);
}
References getMemberList(), DefinitionMixin< GroupDef >::name(), and MemberList::writeDocumentation().
Referenced by writeDocumentation().
writeMemberGroups()
void GroupDefImpl::writeMemberGroups (OutputList & ol) private
Definition at line 1006 of file groupdef.cpp.
{
  /* write user defined member groups */
  for (const auto &mg : m_memberGroups)
  {
    mg->writeDeclarations(ol,0,0,0,this);
  }
}
References m_memberGroups.
Referenced by writeDocumentation().
writeMemberPages()
void GroupDefImpl::writeMemberPages (OutputList & ol, int hierarchyLevel) virtual
Implements GroupDef.
Definition at line 1291 of file groupdef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  for (const auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
       ml->writeDocumentationPage(ol,name(),this,hierarchyLevel);
    }
  }
  ol.popGeneratorState();
}
References OutputList::disableAllBut(), Html, m_memberLists, MemberListType_documentationLists, DefinitionMixin< GroupDef >::name(), OutputList::popGeneratorState(), and OutputList::pushGeneratorState().
Referenced by writeDocumentation().
writeNamespaces()
void GroupDefImpl::writeNamespaces (OutputList & ol, const QCString & title) private
Definition at line 889 of file groupdef.cpp.
{
  // write list of namespaces
  m_namespaces.writeDeclaration(ol,title);
}
References m_namespaces, and NamespaceLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeNestedGroups()
void GroupDefImpl::writeNestedGroups (OutputList & ol, const QCString & title) private
Definition at line 895 of file groupdef.cpp.
{
  // write list of groups
  int count=0;
  for (const auto &gd : m_groups)
  {
    if (gd->isVisible()) count++;
  }
  if (count>0)
  {
    ol.startMemberHeader("groups");
    ol.parseText(title);
    ol.endMemberHeader();
    ol.startMemberList();
    for (const auto &gd : m_groups)
    {
      if (gd->isVisible())
      {
        if (!gd->hasDocumentation()) continue;
        ol.startMemberDeclaration();
        ol.startMemberItem(gd->getOutputFileBase(),OutputGenerator::MemberItemType::Normal);
        //ol.docify(theTranslator->trGroup(FALSE,TRUE));
        //ol.docify(" ");
        ol.insertMemberAlign();
        ol.writeObjectLink(gd->getReference(),gd->getOutputFileBase(),QCString(),gd->groupTitle());
        ol.endMemberItem(OutputGenerator::MemberItemType::Normal);
        if (!gd->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
        {
          ol.startMemberDescription(gd->getOutputFileBase());
          ol.generateDoc(briefFile(),briefLine(),gd,0,gd->briefDescription(),FALSE,FALSE,
                         QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
          ol.endMemberDescription();
        }
        ol.endMemberDeclaration(QCString(),QCString());
      }
    }
    ol.endMemberList();
  }
}
References DefinitionMixin< GroupDef >::briefFile(), DefinitionMixin< GroupDef >::briefLine(), Config_getBool, OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), FALSE, OutputList::generateDoc(), OutputList::insertMemberAlign(), m_groups, OutputGenerator::Normal, OutputList::parseText(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), TRUE, and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writePageDocumentation()
void GroupDefImpl::writePageDocumentation (OutputList & ol) private
Definition at line 984 of file groupdef.cpp.
{
  for (const auto *pd : m_pages)
  {
    if (!pd->isReference())
    {
      const SectionInfo *si=0;
      if (pd->hasTitle() && !pd->name().isEmpty() &&
          (si=SectionManager::instance().find(pd->name()))!=0)
      {
        ol.startSection(si->label(),si->title(),SectionType::Subsection);
        ol.docify(si->title());
        ol.endSection(si->label(),SectionType::Subsection);
      }
      ol.startTextBlock();
      ol.generateDoc(pd->docFile(),pd->docLine(),pd,0,(pd->documentation()+pd->inbodyDocumentation()),TRUE,FALSE,
                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
      ol.endTextBlock();
    }
  }
}
References Config_getBool, OutputList::docify(), OutputList::endSection(), OutputList::endTextBlock(), FALSE, LinkedMap< T, Hash, KeyEqual, Map >::find(), OutputList::generateDoc(), SectionManager::instance(), SectionInfo::label(), m_pages, OutputList::startSection(), OutputList::startTextBlock(), Subsection, SectionInfo::title(), and TRUE.
Referenced by writeDocumentation().
writeQuickMemberLinks()
void GroupDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const virtual
Reimplemented from DefinitionMixin< GroupDef >.
Definition at line 1307 of file groupdef.cpp.
{
  bool createSubDirs=Config_getBool(CREATE_SUBDIRS);
  ol.writeString("      <div class=\"navtab\">\n");
  ol.writeString("        <table>\n");
  for (const auto *md : m_allMemberList)
  {
    if (md->getGroupDef()==this && md->isLinkable() && !md->isEnumValue())
    {
      if (md->isLinkableInProject())
      {
        QCString fn = md->getOutputFileBase();
        addHtmlExtensionIfMissing(fn);
        if (md==currentMd) // selected item => highlight
        {
          ol.writeString("          <tr><td class=\"navtabHL\">");
        }
        else
        {
          ol.writeString("          <tr><td class=\"navtab\">");
        }
        ol.writeString("<a class=\"navtab\" ");
        ol.writeString("href=\"");
        if (createSubDirs) ol.writeString("../../");
        ol.writeString(fn+"#"+md->anchor());
        ol.writeString("\">");
        ol.writeString(convertToHtml(md->localName()));
        ol.writeString("</a>");
        ol.writeString("</td></tr>\n");
      }
    }
  }
  ol.writeString("        </table>\n");
  ol.writeString("      </div>\n");
}
References addHtmlExtensionIfMissing(), Config_getBool, convertToHtml(), createSubDirs(), m_allMemberList, and OutputList::writeString().
writeSummaryLinks()
void GroupDefImpl::writeSummaryLinks (OutputList & ol) const private virtual
Reimplemented from DefinitionMixin< GroupDef >.
Definition at line 1058 of file groupdef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  bool first=TRUE;
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Group))
  {
    if ((lde->kind()==LayoutDocEntry::GroupClasses      &&  m_classes.declVisible()) ||
        (lde->kind()==LayoutDocEntry::GroupConcepts     &&  m_concepts.declVisible()) ||
        (lde->kind()==LayoutDocEntry::GroupNamespaces   &&  m_namespaces.declVisible(false)) ||
        (lde->kind()==LayoutDocEntry::GroupFiles        && !m_fileList.empty()) ||
        (lde->kind()==LayoutDocEntry::GroupNestedGroups && !m_groups.empty()) ||
        (lde->kind()==LayoutDocEntry::GroupDirs         && !m_dirList.empty())
       )
    {
      const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
      if (ls)
      {
        QCString label = lde->kind()==LayoutDocEntry::GroupClasses      ? "nested-classes" :
                         lde->kind()==LayoutDocEntry::GroupConcepts     ? "concepts"       :
                         lde->kind()==LayoutDocEntry::GroupNamespaces   ? "namespaces"     :
                         lde->kind()==LayoutDocEntry::GroupFiles        ? "files"          :
                         lde->kind()==LayoutDocEntry::GroupNestedGroups ? "groups"         :
                         "dirs";
        ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
        first=FALSE;
      }
    }
    else if (lde->kind()==LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        MemberList * ml = getMemberList(lmd->type);
        if (ml && ml->declVisible())
        {
          ol.writeSummaryLink(QCString(),MemberList::listTypeAsString(ml->listType()),lmd->title(lang),first);
          first=FALSE;
        }
      }
    }
  }
  if (!first)
  {
    ol.writeString("  </div>\n");
  }
  ol.popGeneratorState();
}
References ConceptLinkedRefMap::declVisible(), MemberList::declVisible(), NamespaceLinkedRefMap::declVisible(), ClassLinkedRefMap::declVisible(), OutputList::disableAllBut(), LayoutDocManager::docEntries(), FALSE, DefinitionMixin< GroupDef >::getLanguage(), getMemberList(), LayoutDocManager::Group, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, Html, LayoutDocManager::instance(), MemberList::listType(), MemberList::listTypeAsString(), m_classes, m_concepts, m_dirList, m_fileList, m_groups, m_namespaces, LayoutDocEntry::MemberDecl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), TRUE, LayoutDocEntryMemberDecl::type, OutputList::writeString(), and OutputList::writeSummaryLink().
Referenced by writeDocumentation().
writeTagFile()
void GroupDefImpl::writeTagFile (TextStream & tagFile) virtual
Implements GroupDef.
Definition at line 617 of file groupdef.cpp.
{
  QCString fn = getOutputFileBase();
  addHtmlExtensionIfMissing(fn);
  tagFile << "  <compound kind=\"group\">\n";
  tagFile << "    <name>" << convertToXML(name()) << "</name>\n";
  tagFile << "    <title>" << convertToXML(m_title) << "</title>\n";
  tagFile << "    <filename>" << fn << "</filename>\n";
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Group))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::GroupClasses:
        {
          for (const auto &cd : m_classes)
          {
            if (cd->isLinkableInProject())
            {
              tagFile << "    <class kind=\"" << cd->compoundTypeString()
                      << "\">" << convertToXML(cd->name()) << "</class>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupConcepts:
        {
          for (const auto &cd : m_concepts)
          {
            if (cd->isLinkableInProject())
            {
              tagFile << "    <concept>" << convertToXML(cd->name())
                      << "</concept>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupNamespaces:
        {
          for (const auto &nd : m_namespaces)
          {
            if (nd->isLinkableInProject())
            {
              tagFile << "    <namespace>" << convertToXML(nd->name())
                      << "</namespace>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupFiles:
        {
          for (const auto &fd : m_fileList)
          {
            if (fd->isLinkableInProject())
            {
              tagFile << "    <file>" << convertToXML(fd->name()) << "</file>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupPageDocs:
        {
          for (const auto &pd : m_pages)
          {
            QCString pageName = pd->getOutputFileBase();
            if (pd->isLinkableInProject())
            {
              tagFile << "    <page>" << convertToXML(pageName) << "</page>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupDirs:
        {
          for (const auto &dd : m_dirList)
          {
            if (dd->isLinkableInProject())
            {
              tagFile << "    <dir>" << convertToXML(dd->displayName()) << "</dir>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::GroupNestedGroups:
        {
          for (const auto &gd : m_groups)
          {
            if (gd->isVisible())
            {
              tagFile << "    <subgroup>" << convertToXML(gd->name()) << "</subgroup>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            MemberList * ml = getMemberList(lmd->type);
            if (ml)
            {
              ml->writeTagFile(tagFile,true);
            }
          }
        }
        break;
      case LayoutDocEntry::MemberGroups:
        {
          for (const auto &mg : m_memberGroups)
          {
            mg->writeTagFile(tagFile,true);
          }
        }
        break;
      default:
        break;
    }
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << "  </compound>\n";
}
References addHtmlExtensionIfMissing(), convertToXML(), LayoutDocManager::docEntries(), getMemberList(), getOutputFileBase(), LayoutDocManager::Group, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, LayoutDocManager::instance(), m_classes, m_concepts, m_dirList, m_fileList, m_groups, m_memberGroups, m_namespaces, m_pages, m_title, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberGroups, DefinitionMixin< GroupDef >::name(), LayoutDocEntryMemberDecl::type, DefinitionMixin< GroupDef >::writeDocAnchorsToTagFile(), and MemberList::writeTagFile().
Member Data Documentation
m_allMemberList
MemberList GroupDefImpl::m_allMemberList private
Definition at line 154 of file groupdef.cpp.
Referenced by computeAnchors(), insertMember(), numDocMembers(), writeDocumentation(), and writeQuickMemberLinks().
m_allMemberNameInfoLinkedMap
MemberNameInfoLinkedMap GroupDefImpl::m_allMemberNameInfoLinkedMap private
Definition at line 155 of file groupdef.cpp.
Referenced by insertMember(), and removeMember().
m_classes
ClassLinkedRefMap GroupDefImpl::m_classes private
Definition at line 147 of file groupdef.cpp.
Referenced by addClass(), getClasses(), numDocMembers(), sortMemberLists(), writeClasses(), writeInlineClasses(), writeSummaryLinks(), and writeTagFile().
m_concepts
ConceptLinkedRefMap GroupDefImpl::m_concepts private
Definition at line 148 of file groupdef.cpp.
Referenced by addConcept(), getConcepts(), writeConcepts(), writeSummaryLinks(), and writeTagFile().
m_dirList
DirList GroupDefImpl::m_dirList private
Definition at line 153 of file groupdef.cpp.
Referenced by addDir(), getDirs(), sortMemberLists(), writeDirs(), writeSummaryLinks(), and writeTagFile().
m_examples
PageLinkedRefMap GroupDefImpl::m_examples private
Definition at line 152 of file groupdef.cpp.
Referenced by addExample(), getExamples(), and numDocMembers().
m_fileList
FileList GroupDefImpl::m_fileList private
Definition at line 146 of file groupdef.cpp.
Referenced by addFile(), containsFile(), getFiles(), numDocMembers(), writeFiles(), writeSummaryLinks(), and writeTagFile().
m_fileName
QCString GroupDefImpl::m_fileName private
Definition at line 145 of file groupdef.cpp.
Referenced by getOutputFileBase(), and GroupDefImpl().
m_groups
GroupList GroupDefImpl::m_groups private
Definition at line 150 of file groupdef.cpp.
Referenced by addGroup(), findGroup(), getSubGroups(), numDocMembers(), sortSubGroups(), writeNestedGroups(), writeSummaryLinks(), and writeTagFile().
m_groupScope
Definition* GroupDefImpl::m_groupScope private
Definition at line 156 of file groupdef.cpp.
Referenced by getGroupScope(), GroupDefImpl(), and setGroupScope().
m_memberGroups
MemberGroupList GroupDefImpl::m_memberGroups private
Definition at line 158 of file groupdef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), countMembers(), distributeMemberGroupDocumentation(), findSectionsInDocumentation(), getMemberGroups(), writeMemberGroups(), and writeTagFile().
m_memberLists
MemberLists GroupDefImpl::m_memberLists private
Definition at line 157 of file groupdef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), addMemberToList(), countMembers(), findSectionsInDocumentation(), getMemberList(), getMemberLists(), sortMemberLists(), and writeMemberPages().
m_namespaces
NamespaceLinkedRefMap GroupDefImpl::m_namespaces private
Definition at line 149 of file groupdef.cpp.
Referenced by addNamespace(), getNamespaces(), numDocMembers(), sortMemberLists(), writeNamespaces(), writeSummaryLinks(), and writeTagFile().
m_pages
PageLinkedRefMap GroupDefImpl::m_pages private
Definition at line 151 of file groupdef.cpp.
Referenced by addPage(), getPages(), hasDetailedDescription(), numDocMembers(), writeDetailedDescription(), writePageDocumentation(), and writeTagFile().
m_subGrouping
bool GroupDefImpl::m_subGrouping private
Definition at line 159 of file groupdef.cpp.
Referenced by GroupDefImpl(), and subGrouping().
m_title
QCString GroupDefImpl::m_title private
Definition at line 143 of file groupdef.cpp.
Referenced by displayName(), groupTitle(), setGroupTitle(), writeDocumentation(), writeGroupGraph(), and writeTagFile().
m_titleSet
bool GroupDefImpl::m_titleSet private
Definition at line 144 of file groupdef.cpp.
Referenced by hasGroupTitle(), and setGroupTitle().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/groupdef.cpp