Doxygen: ConfigObsolete Class Reference
ConfigObsolete Class Reference
Section marker for obsolete options.
#include <src/configimpl.h>
Public Member Functions
ConfigObsolete (const char *name, OptionType orgType)
void writeTemplate (TextStream &, bool, bool) override
void compareDoxyfile (TextStream &, Config::CompareMode) override
void writeXMLDoxyfile (TextStream &) override
void writeXSDDoxyfile (TextStream &) override
void substEnvVars () override
OptionType orgType () const
StringVector * valueListRef ()
QCString * valueStringRef ()
void markAsPresent ()
bool isPresent () const
Public Member Functions inherited from ConfigOption
ConfigOption (OptionType t)
OptionType kind () const
QCString name () const
QCString docs () const
QCString dependsOn () const
void addDependency (const char *dep)
void setEncoding (const QCString &e)
void setUserComment (const QCString &u)
Private Attributes
OptionType m_orgType
StringVector m_listvalue
QCString m_valueString
bool m_present = false
Additional Inherited Members
Public Types inherited from ConfigOption
enum OptionType {
O_Info , O_List , O_Enum , O_String ,
O_Int , O_Bool , O_Obsolete , O_Disabled
}
enum { MAX_OPTION_LENGTH = 23 }
Protected Member Functions inherited from ConfigOption
virtual void convertStrToVal (Config::CompareMode)
virtual void emptyValueToDefault ()
virtual void init ()
virtual bool isDefault ()
void writeBoolValue (TextStream &t, bool v, bool initSpace=true)
void writeIntValue (TextStream &t, int i, bool initSpace=true)
void writeStringValue (TextStream &t, const QCString &s, bool initSpace=true, bool wasQuoted=false)
void writeStringList (TextStream &t, const StringVector &l)
Protected Attributes inherited from ConfigOption
QCString m_spaces
QCString m_name
QCString m_doc
QCString m_dependency
QCString m_encoding
QCString m_userComment
OptionType m_kind
Detailed Description
Section marker for obsolete options.
Definition at line 283 of file configimpl.h.
Constructor & Destructor Documentation
ConfigObsolete()
ConfigObsolete::ConfigObsolete (const char * name, OptionType orgType) inline
Definition at line 286 of file configimpl.h.
                                                        : ConfigOption(O_Obsolete), m_orgType(orgType)
    { m_name = name; }
References ConfigOption::ConfigOption(), ConfigOption::m_name, m_orgType, ConfigOption::name(), ConfigOption::O_Obsolete, and orgType().
Member Function Documentation
compareDoxyfile()
void ConfigObsolete::compareDoxyfile (TextStream & , Config::CompareMode) inline override virtual
Implements ConfigOption.
Definition at line 289 of file configimpl.h.
{}
isPresent()
bool ConfigObsolete::isPresent () const inline
Definition at line 297 of file configimpl.h.
{ return m_present; }
References m_present.
Referenced by Config::updateObsolete().
markAsPresent()
void ConfigObsolete::markAsPresent () inline
Definition at line 296 of file configimpl.h.
{ m_present = true; }
References m_present.
orgType()
OptionType ConfigObsolete::orgType () const inline
Definition at line 293 of file configimpl.h.
{ return m_orgType; }
References m_orgType.
Referenced by ConfigObsolete(), and Config::updateObsolete().
substEnvVars()
void ConfigObsolete::substEnvVars () inline override virtual
Implements ConfigOption.
Definition at line 292 of file configimpl.h.
{}
valueListRef()
StringVector * ConfigObsolete::valueListRef () inline
Definition at line 294 of file configimpl.h.
{ return &m_listvalue; }
References m_listvalue.
valueStringRef()
QCString * ConfigObsolete::valueStringRef () inline
Definition at line 295 of file configimpl.h.
{ return &m_valueString; }
References m_valueString.
Referenced by updateAttribute(), and Config::updateObsolete().
writeTemplate()
void ConfigObsolete::writeTemplate (TextStream & , bool , bool) override virtual
Implements ConfigOption.
Definition at line 629 of file configimpl.l.
{}
writeXMLDoxyfile()
void ConfigObsolete::writeXMLDoxyfile (TextStream &) inline override virtual
Implements ConfigOption.
Definition at line 290 of file configimpl.h.
{}
writeXSDDoxyfile()
void ConfigObsolete::writeXSDDoxyfile (TextStream &) inline override virtual
Implements ConfigOption.
Definition at line 291 of file configimpl.h.
{}
Member Data Documentation
m_listvalue
StringVector ConfigObsolete::m_listvalue private
Definition at line 300 of file configimpl.h.
Referenced by valueListRef().
m_orgType
OptionType ConfigObsolete::m_orgType private
Definition at line 299 of file configimpl.h.
Referenced by ConfigObsolete(), and orgType().
m_present
bool ConfigObsolete::m_present = false private
Definition at line 302 of file configimpl.h.
Referenced by isPresent(), and markAsPresent().
m_valueString
QCString ConfigObsolete::m_valueString private
Definition at line 301 of file configimpl.h.
Referenced by valueStringRef().
The documentation for this class was generated from the following files:
src/configimpl.h
src/configimpl.l