Doxygen: src/formula.cpp File Reference
formula.cpp File Reference
#include <map>
#include <vector>
#include <string>
#include <utility>
#include "formula.h"
#include "message.h"
#include "config.h"
#include "util.h"
#include "portable.h"
#include "image.h"
#include "fileinfo.h"
#include "dir.h"
#include "regex.h"
#include "linkedmap.h"
#include "threadpool.h"
#include "latexgen.h"
#include "debug.h"
#include "doxygen.h"
#include "indexlist.h"
Classes
struct FormulaManager::Private
Functions
static int determineInkscapeVersion (const Dir &thisDir)
static bool createDVIFile (const QCString &fileName)
static bool createPostscriptFile (const QCString &fileName, const QCString &formBase, int pageIndex)
static bool createEPSbboxFile (const QCString &formBase)
static bool extractBoundingBox (const QCString &formBase, int *x1, int *y1, int *x2, int *y2, double *x1hi, double *y1hi, double *x2hi, double *y2hi)
static double updateFormulaSize (Formula *formula, int x1, int y1, int x2, int y2)
static bool createCroppedPDF (const QCString &formBase, int x1, int y1, int x2, int y2)
static bool createCroppedEPS (const QCString &formBase)
static bool createSVGFromPDF (const QCString &formBase, const QCString &outFile)
static bool createSVGFromPDFviaInkscape (const Dir &thisDir, const QCString &formBase, const QCString &outFile)
static bool updateEPSBoundingBox (const QCString &formBase, int x1, int y1, int x2, int y2, double x1hi, double y1hi, double x2hi, double y2hi)
static bool createPNG (const QCString &formBase, const QCString &outFile, double scaleFactor)
static StringVector generateFormula (const Dir &thisDir, const QCString &formulaFileName, Formula *formula, int pageNum, int pageIndex, FormulaManager::Format format, FormulaManager::HighDPI hd, FormulaManager::Mode mode)
Variables
static std::mutex g_formulaUpdateMutex
static std::mutex g_inkscapeDetectionMutex
Function Documentation
createCroppedEPS()
static bool createCroppedEPS (const QCString & formBase) static
Definition at line 366 of file formula.cpp.
{
  const size_t argsLen = 4096;
  char args[argsLen];
  // crop the image to its bounding box
  qsnprintf(args,argsLen,"-q -dBATCH -dNOPAUSE -P- -dNOSAFER -sDEVICE=eps2write"
              " -o %s_tmp.eps -f %s_tmp.ps",qPrint(formBase),qPrint(formBase));
  if (Portable::system(Portable::ghostScriptCommand(),args)!=0)
  {
    err("Problems running %s. Check your installation!\n",Portable::ghostScriptCommand());
    return false;
  }
  return true;
}
References err, Portable::ghostScriptCommand(), qPrint(), qsnprintf, and Portable::system().
Referenced by generateFormula().
createCroppedPDF()
static bool createCroppedPDF (const QCString & formBase, int x1, int y1, int x2, int y2) static
Definition at line 350 of file formula.cpp.
{
  const size_t argsLen = 4096;
  char args[argsLen];
  // crop the image to its bounding box
  qsnprintf(args,argsLen,"-q -dBATCH -dNOPAUSE -P- -dNOSAFER -sDEVICE=pdfwrite"
              " -o %s_tmp.pdf -c \"[/CropBox [%d %d %d %d] /PAGES pdfmark\" -f %s_tmp.ps",
      qPrint(formBase),x1,y1,x2,y2,qPrint(formBase));
  if (Portable::system(Portable::ghostScriptCommand(),args)!=0)
  {
    err("Problems running %s. Check your installation!\n",Portable::ghostScriptCommand());
    return false;
  }
  return true;
}
References err, Portable::ghostScriptCommand(), qPrint(), qsnprintf, and Portable::system().
Referenced by generateFormula().
createDVIFile()
static bool createDVIFile (const QCString & fileName) static
Definition at line 241 of file formula.cpp.
{
  QCString latexCmd = "latex";
  const size_t argsLen = 4096;
  char args[argsLen];
  int rerunCount=1;
  while (rerunCount<8)
  {
    //printf("Running latex...\n");
    qsnprintf(args,argsLen,"-interaction=batchmode %s >%s",qPrint(fileName),Portable::devNull());
    if ((Portable::system(latexCmd,args)!=0) || (Portable::system(latexCmd,args)!=0))
    {
      err("Problems running latex. Check your installation or look "
          "for typos in %s.tex and check %s.log!\n",qPrint(fileName),qPrint(fileName));
      return false;
    }
    // check the log file if we need to run latex again to resolve references
    QCString logFile = fileToString(fileName+".log");
    if (logFile.isEmpty() ||
        (logFile.find("Rerun to get cross-references right")==-1 && logFile.find("Rerun LaTeX")==-1))
    {
      break;
    }
    rerunCount++;
  }
  return true;
}
References Portable::devNull(), err, fileToString(), QCString::find(), QCString::isEmpty(), qPrint(), qsnprintf, and Portable::system().
Referenced by FormulaManager::createFormulasTexFile().
createEPSbboxFile()
static bool createEPSbboxFile (const QCString & formBase) static
Definition at line 284 of file formula.cpp.
{
  const size_t argsLen = 4096;
  char args[argsLen];
  // extract the bounding box for the postscript file
  qsnprintf(args,argsLen,"-q -dBATCH -dNOPAUSE -P- -dNOSAFER -sDEVICE=bbox %s_tmp.ps 2>%s_tmp.epsi",
      qPrint(formBase),qPrint(formBase));
  if (Portable::system(Portable::ghostScriptCommand(),args)!=0)
  {
    err("Problems running %s. Check your installation!\n",Portable::ghostScriptCommand());
    return false;
  }
  return true;
}
References err, Portable::ghostScriptCommand(), qPrint(), qsnprintf, and Portable::system().
Referenced by generateFormula().
createPNG()
static bool createPNG (const QCString & formBase, const QCString & outFile, double scaleFactor) static
Definition at line 459 of file formula.cpp.
{
  const size_t argsLen = 4096;
  char args[argsLen];
  qsnprintf(args,argsLen,"-q -dNOSAFER -dBATCH -dNOPAUSE -dEPSCrop -sDEVICE=pngalpha -dGraphicsAlphaBits=4 -dTextAlphaBits=4 "
               "-r%d -sOutputFile=%s %s_tmp_corr.eps",static_cast<int>(scaleFactor*72),qPrint(outFile),qPrint(formBase));
  if (Portable::system(Portable::ghostScriptCommand(),args)!=0)
  {
    err("Problems running %s. Check your installation!\n",Portable::ghostScriptCommand());
    return false;
  }
  return true;
}
References err, Portable::ghostScriptCommand(), qPrint(), qsnprintf, and Portable::system().
Referenced by generateFormula().
createPostscriptFile()
static bool createPostscriptFile (const QCString & fileName, const QCString & formBase, int pageIndex) static
Definition at line 269 of file formula.cpp.
{
  const size_t argsLen = 4096;
  char args[argsLen];
  // run dvips to convert the page with number pageIndex to an
  // postscript file.
  qsnprintf(args,argsLen,"-q -D 600 -n 1 -p %d -o %s_tmp.ps %s.dvi",pageIndex,qPrint(formBase),qPrint(fileName));
  if (Portable::system("dvips",args)!=0)
  {
    err("Problems running dvips. Check your installation!\n");
    return false;
  }
  return true;
}
References err, qPrint(), qsnprintf, and Portable::system().
Referenced by generateFormula().
createSVGFromPDF()
static bool createSVGFromPDF (const QCString & formBase, const QCString & outFile) static
Definition at line 381 of file formula.cpp.
{
  const size_t argsLen = 4096;
  char args[argsLen];
  qsnprintf(args,argsLen,"%s_tmp.pdf %s",qPrint(formBase),qPrint(outFile));
  if (Portable::system("pdf2svg",args)!=0)
  {
    err("Problems running pdf2svg. Check your installation!\n");
    return false;
  }
  return true;
}
References err, qPrint(), qsnprintf, and Portable::system().
Referenced by generateFormula().
createSVGFromPDFviaInkscape()
static bool createSVGFromPDFviaInkscape (const Dir & thisDir, const QCString & formBase, const QCString & outFile) static
Definition at line 394 of file formula.cpp.
{
  const size_t argsLen = 4096;
  char args[argsLen];
  int inkscapeVersion = determineInkscapeVersion(thisDir);
  if (inkscapeVersion == -1)
  {
    err("Problems determining the version of inkscape. Check your installation!\n");
    return false;
  }
  else if (inkscapeVersion == 0)
  {
    qsnprintf(args,argsLen,"-l %s -z %s_tmp.pdf 2>%s",qPrint(outFile),qPrint(formBase),Portable::devNull());
  }
  else // inkscapeVersion >= 1
  {
    qsnprintf(args,argsLen,"--export-type=svg --export-filename=%s %s_tmp.pdf 2>%s",qPrint(outFile),qPrint(formBase),Portable::devNull());
  }
  if (Portable::system("inkscape",args)!=0)
  {
    err("Problems running inkscape. Check your installation!\n");
    return false;
  }
  return true;
}
References determineInkscapeVersion(), Portable::devNull(), err, qPrint(), qsnprintf, and Portable::system().
Referenced by generateFormula().
determineInkscapeVersion()
static int determineInkscapeVersion (const Dir & thisDir) static
Definition at line 729 of file formula.cpp.
{
  std::lock_guard<std::mutex> lock(g_inkscapeDetectionMutex);
  // The command line interface (CLI) of Inkscape 1.0 has changed in comparison to
  // previous versions. In order to invokine Inkscape, the used version is detected
  // and based on the version the right syntax of the CLI is chosen.
  static int inkscapeVersion = -2;
  if (inkscapeVersion == -2) // initial one time version check
  {
    QCString inkscapeVersionFile = "inkscape_version" ;
    inkscapeVersion = -1;
    QCString args = "-z --version >"+inkscapeVersionFile+" 2>"+Portable::devNull();
    if (Portable::system("inkscape",args)!=0)
    {
      // looks like the old syntax gave problems, lets try the new syntax
      args = " --version >"+inkscapeVersionFile+" 2>"+Portable::devNull();
      if (Portable::system("inkscape",args)!=0)
      {
        return -1;
      }
    }
    // read version file and determine major version
    std::ifstream inkscapeVersionIn = Portable::openInputStream(inkscapeVersionFile);
    if (inkscapeVersionIn.is_open())
    {
      std::string line;
      while (getline(inkscapeVersionIn,line))
      {
        size_t dotPos = line.find('.');
        if (line.rfind("Inkscape ",0)==0 && dotPos>0)
        {
          // get major version
          inkscapeVersion = std::stoi(line.substr(9,dotPos-9));
          break;
        }
      }
      inkscapeVersionIn.close();
    }
    else // failed to open version file
    {
      return -1;
    }
    if (!Debug::isFlagSet(Debug::Formula))
    {
      thisDir.remove(inkscapeVersionFile.str());
    }
  }
  return inkscapeVersion;
}
References Portable::devNull(), Debug::Formula, g_inkscapeDetectionMutex, Debug::isFlagSet(), Portable::openInputStream(), Dir::remove(), QCString::str(), and Portable::system().
Referenced by createSVGFromPDFviaInkscape().
extractBoundingBox()
static bool extractBoundingBox (const QCString & formBase, int * x1, int * y1, int * x2, int * y2, double * x1hi, double * y1hi, double * x2hi, double * y2hi) static
Definition at line 299 of file formula.cpp.
{
  FileInfo fi((formBase+"_tmp.epsi").str());
  if (fi.exists())
  {
    QCString eps = fileToString(formBase+"_tmp.epsi");
    int i = eps.find("%%BoundingBox:");
    if (i!=-1)
    {
      sscanf(eps.data()+i,"%%%%BoundingBox:%d %d %d %d",x1,y1,x2,y2);
    }
    else
    {
      err("Couldn't extract bounding box from %s_tmp.epsi\n",qPrint(formBase));
      return false;
    }
    i = eps.find("%%HiResBoundingBox:");
    if (i!=-1)
    {
      sscanf(eps.data()+i,"%%%%HiResBoundingBox:%lf %lf %lf %lf",x1hi,y1hi,x2hi,y2hi);
    }
    else
    {
      err("Couldn't extract high resolution bounding box from %s_tmp.epsi\n",qPrint(formBase));
      return false;
    }
  }
  //printf("Bounding box [%d %d %d %d]\n",x1,y1,x2,y2);
  return true;
}
References QCString::data(), err, FileInfo::exists(), fileToString(), QCString::find(), and qPrint().
Referenced by generateFormula(), and DotRunner::readBoundingBox().
generateFormula()
static StringVector generateFormula (const Dir & thisDir, const QCString & formulaFileName, Formula * formula, int pageNum, int pageIndex, FormulaManager::Format format, FormulaManager::HighDPI hd, FormulaManager::Mode mode) static
Definition at line 473 of file formula.cpp.
{
  StringVector tempFiles;
  QCString outputFile;
  outputFile.sprintf("form_%d%s.%s",pageNum, mode==FormulaManager::Mode::Light?"":"_dark", format==FormulaManager::Format::Vector?"svg":"png");
  msg("Generating image %s for formula\n",qPrint(outputFile));
  QCString formBase;
  formBase.sprintf("_form%d%s",pageNum,mode==FormulaManager::Mode::Light?"":"_dark");
  if (!createPostscriptFile(formulaFileName,formBase,pageIndex)) return tempFiles;
  int x1=0,y1=0,x2=0,y2=0;
  double x1hi=0.0,y1hi=0.0,x2hi=0.0,y2hi=0.0;
  if (mode==FormulaManager::Mode::Light)
  {
    if (!createEPSbboxFile(formBase)) return tempFiles;
    // extract the bounding box info from the generated .epsi file
    if (!extractBoundingBox(formBase,&x1,&y1,&x2,&y2,&x1hi,&y1hi,&x2hi,&y2hi)) return tempFiles;
  }
  else // for dark images the bounding box is wrong (includes the black) so
       // use the bounding box of the light image instead.
  {
    QCString formBaseLight;
    formBaseLight.sprintf("_form%d",pageNum);
    if (!extractBoundingBox(formBaseLight,&x1,&y1,&x2,&y2,&x1hi,&y1hi,&x2hi,&y2hi)) return tempFiles;
  }
  // convert the corrected EPS to a bitmap
  double scaleFactor = updateFormulaSize(formula,x1,y1,x2,y2);
  if (format==FormulaManager::Format::Vector)
  {
    if (!createCroppedPDF(formBase,x1,y1,x2,y2)) return tempFiles;
    // if we have pdf2svg available use it to create a SVG image
    if (Portable::checkForExecutable("pdf2svg"))
    {
      createSVGFromPDF(formBase,outputFile);
    }
    else if (Portable::checkForExecutable("inkscape")) // alternative is to use inkscape
    {
      createSVGFromPDFviaInkscape(thisDir,formBase,outputFile);
    }
    else
    {
      err("Neither 'pdf2svg' nor 'inkscape' present for conversion of formula to 'svg'\n");
      return tempFiles;
    }
    tempFiles.push_back(formBase.str()+"_tmp.pdf");
  }
  else // format==FormulaManager::Format::Bitmap
  {
    if (!createCroppedEPS(formBase)) return tempFiles;
    if (!updateEPSBoundingBox(formBase,x1,y1,x2,y2,x1hi,y1hi,x2hi,y2hi)) return tempFiles;
    if (hd==FormulaManager::HighDPI::On) // for high DPI display it looks much better if the
                                         // image resolution is higher than the display resolution
    {
      scaleFactor*=2;
    }
    if (!createPNG(formBase,outputFile,scaleFactor)) return tempFiles;
    tempFiles.push_back(formBase.str()+"_tmp.eps");
    tempFiles.push_back(formBase.str()+"_tmp_corr.eps");
  }
  // remove intermediate image files
  tempFiles.push_back(formBase.str()+"_tmp.ps");
  if (mode==FormulaManager::Mode::Light)
  {
    tempFiles.push_back(formBase.str()+"_tmp.epsi");
  }
  return tempFiles;
}
References Portable::checkForExecutable(), createCroppedEPS(), createCroppedPDF(), createEPSbboxFile(), createPNG(), createPostscriptFile(), createSVGFromPDF(), createSVGFromPDFviaInkscape(), err, extractBoundingBox(), FormulaManager::Light, msg(), FormulaManager::On, qPrint(), QCString::sprintf(), QCString::str(), updateEPSBoundingBox(), updateFormulaSize(), and FormulaManager::Vector.
Referenced by FormulaManager::createFormulasTexFile().
updateEPSBoundingBox()
static bool updateEPSBoundingBox (const QCString & formBase, int x1, int y1, int x2, int y2, double x1hi, double y1hi, double x2hi, double y2hi) static
Definition at line 421 of file formula.cpp.
{
  // read back %s_tmp.eps and replace
  // bounding box values with x1,y1,x2,y2 and remove the HiResBoundingBox
  std::ifstream epsIn  = Portable::openInputStream(formBase+"_tmp.eps");
  std::ofstream epsOut = Portable::openOutputStream(formBase+"_tmp_corr.eps");
  if (epsIn.is_open() && epsOut.is_open())
  {
    std::string line;
    while (getline(epsIn,line))
    {
      if (line.rfind("%%BoundingBox",0)==0)
      {
        epsOut << "%%BoundingBox: " << std::max(0,x1-1) << " " << std::max(0,y1-1) << " " << (x2+1) << " " << (y2+1) << "\n";
      }
      else if (line.rfind("%%HiResBoundingBox",0)==0)
      {
        epsOut << "%%HiResBoundingBox: " << std::max(0.0,x1hi-1.0) << " " << std::max(0.0,y1hi-1.0) << " " << (x2hi+1.0) << " " << (y2hi+1.0) << "\n";
      }
      else
      {
        epsOut << line << "\n";
      }
    }
    epsIn.close();
    epsOut.close();
  }
  else
  {
    err("Problems correcting the eps files from %s_tmp.eps to %s_tmp_corr.eps\n",
        qPrint(formBase),qPrint(formBase));
    return false;
  }
  return true;
}
References err, Portable::openInputStream(), Portable::openOutputStream(), and qPrint().
Referenced by generateFormula().
updateFormulaSize()
static double updateFormulaSize (Formula * formula, int x1, int y1, int x2, int y2) static
Definition at line 334 of file formula.cpp.
{
  double scaleFactor = 1.25;
  int zoomFactor = Config_getInt(FORMULA_FONTSIZE);
  if (zoomFactor<8 || zoomFactor>50) zoomFactor=10;
  scaleFactor *= zoomFactor/10.0;
  if (formula)
  {
    std::lock_guard<std::mutex> lock(g_formulaUpdateMutex);
    formula->setWidth(static_cast<int>((x2-x1)*scaleFactor+0.5));
    formula->setHeight(static_cast<int>((y2-y1)*scaleFactor+0.5));
  }
  return scaleFactor;
}
References Config_getInt, g_formulaUpdateMutex, Formula::setHeight(), and Formula::setWidth().
Referenced by generateFormula().
Variable Documentation
g_formulaUpdateMutex
std::mutex g_formulaUpdateMutex static
Definition at line 332 of file formula.cpp.
Referenced by updateFormulaSize().
g_inkscapeDetectionMutex
std::mutex g_inkscapeDetectionMutex static
Definition at line 725 of file formula.cpp.
Referenced by determineInkscapeVersion().