Doxygen: DocHtmlSummary Class Reference
DocHtmlSummary Class Reference
Node Html summary.
#include <src/docnode.h>
Public Member Functions
DocHtmlSummary (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
const HtmlAttribList & attribs () const
void parse ()
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
HtmlAttribList m_attribs
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node Html summary.
Definition at line 822 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlSummary()
DocHtmlSummary::DocHtmlSummary (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) inline
Definition at line 825 of file docnode.h.
                                                                                           :
       DocCompoundNode(parser,parent), m_attribs(attribs) {}
References attribs(), DocCompoundNode::DocCompoundNode(), m_attribs, DocNode::parent(), and DocNode::parser().
Member Function Documentation
attribs()
const HtmlAttribList & DocHtmlSummary::attribs () const inline
Definition at line 827 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by DocHtmlSummary(), HtmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
parse()
void DocHtmlSummary::parse ()
Definition at line 1371 of file docnode.cpp.
{
  AUTO_TRACE();
  auto ns = AutoNodeStack(parser(),thisVariant());
  parser()->tokenizer.setStateTitle();
  Token tok = parser()->tokenizer.lex();
  while (!tok.is_any_of(TokenRetval::TK_NONE, TokenRetval::TK_EOF))
  {
    HtmlTagType tagId = HtmlTagType::UNKNOWN;
    // check of </summary>
    if (tok.value()==TokenRetval::TK_HTMLTAG &&
        (tagId=Mappers::htmlTagMapper->map(parser()->context.token->name))==HtmlTagType::XML_SUMMARY &&
        parser()->context.token->endTag
       )
    {
      break;
    }
    else if (!parser()->defaultHandleToken(thisVariant(),tok,children()))
    {
      parser()->errorHandleDefaultToken(thisVariant(),tok,children(),"summary section");
    }
    tok = parser()->tokenizer.lex();
  }
  parser()->tokenizer.setStatePara();
  if (tok.is_any_of(TokenRetval::TK_NONE,TokenRetval::TK_EOF))
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected end of comment while inside"
           " <summary> tag");
  }
}
References AUTO_TRACE, DocCompoundNode::children(), DocParser::errorHandleDefaultToken(), Mappers::htmlTagMapper, Token::is_any_of(), DocTokenizer::lex(), DocNode::parser(), DocTokenizer::setStatePara(), DocTokenizer::setStateTitle(), DocNode::thisVariant(), DocParser::tokenizer, UNKNOWN, Token::value(), warn_doc_error, and XML_SUMMARY.
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlSummary::m_attribs private
Definition at line 831 of file docnode.h.
Referenced by attribs(), and DocHtmlSummary().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp