Doxygen: TranslatorVietnamese Class Reference
TranslatorVietnamese Class Reference
#include <src/translator_vi.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString latexFontenc () override
QCString latexCommandName () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDayOfWeek (int dayOfWeek, bool, bool full) override
QCString trMonth (int month, bool, bool full) override
QCString trDayPeriod (bool period) override
Public Member Functions inherited from TranslatorAdapter_1_6_0
QCString updateNeededMessage () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
Public Member Functions inherited from TranslatorAdapter_1_7_5
QCString updateNeededMessage () override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Public Member Functions inherited from TranslatorAdapter_1_8_0
QCString updateNeededMessage () override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trInterfaces () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) override methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include "translator.h" or "translator_adapter.h" here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 50 of file translator_vi.h.
Member Function Documentation
getLanguageString()
QCString TranslatorVietnamese::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 96 of file translator_vi.h.
    {
      return "0x42A Vietnamese";
    }
idLanguage()
QCString TranslatorVietnamese::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 62 of file translator_vi.h.
    { return "vietnamese"; }
latexCommandName()
QCString TranslatorVietnamese::latexCommandName () inline override virtual
Set the name to be used as latex command.
Reimplemented from Translator.
Definition at line 88 of file translator_vi.h.
    {
      return p_latexCommandName("xelatex");
    }
References Translator::p_latexCommandName().
latexFontenc()
QCString TranslatorVietnamese::latexFontenc () inline override virtual
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 84 of file translator_vi.h.
    {
      return "";
    }
latexLanguageSupportCommand()
QCString TranslatorVietnamese::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 79 of file translator_vi.h.
    {
      return
        "\\usepackage[vietnamese]{babel}\n";
    }
trAll()
QCString TranslatorVietnamese::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1394 of file translator_vi.h.
    {
      return "Tt c";
    }
trAttention()
QCString TranslatorVietnamese::trAttention () inline override virtual
Implements Translator.
Definition at line 974 of file translator_vi.h.
    {
      return "Ch ";
    }
trAuthor()
QCString TranslatorVietnamese::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1267 of file translator_vi.h.
    {
      return createNoun(first_capital, singular, "tc gi", "");
    }
References Translator::createNoun().
trBug()
QCString TranslatorVietnamese::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1139 of file translator_vi.h.
    {
      return "Li";
    }
trBugList()
QCString TranslatorVietnamese::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1144 of file translator_vi.h.
    {
      return "Danh sch li";
    }
trCallerGraph()
QCString TranslatorVietnamese::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1513 of file translator_vi.h.
    {
      return "Biu  cc li gi cho hm ny:";
    }
trCallGraph()
QCString TranslatorVietnamese::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1399 of file translator_vi.h.
    {
      return "Biu  cc li gi cho hm ny:";
    }
trClass()
QCString TranslatorVietnamese::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1202 of file translator_vi.h.
    {
      return createNoun(first_capital, singular, "class", "es");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorVietnamese::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 529 of file translator_vi.h.
    {
      return "S  k tha cho "+clName+":";
    }
trClassDocumentation()
QCString TranslatorVietnamese::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 410 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Thng tin v cu trc c s d liu";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Thng tin v Class";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorVietnamese::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1102 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cu trc d liu";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorVietnamese::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 194 of file translator_vi.h.
    { return "Kin trc Class"; }
trClassHierarchyDescription()
QCString TranslatorVietnamese::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 253 of file translator_vi.h.
    { return "Danh sch k tha  c sp xp theo ABC, "
             "nhng cha y :";
    }
trCode()
QCString TranslatorVietnamese::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 874 of file translator_vi.h.
    {
      return "m ngun";
    }
trCollaborationDiagram()
QCString TranslatorVietnamese::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 829 of file translator_vi.h.
    {
      return "S  lin kt cho "+clName+":";
    }
trCompoundIndex()
QCString TranslatorVietnamese::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 383 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Index cu trc c s d liu";
      }
      else
      {
        return "Class Index";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorVietnamese::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1568 of file translator_vi.h.
    { return "Ch mc kiu d liu"; }
trCompoundList()
QCString TranslatorVietnamese::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 198 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cu trc c s d liu (Data Structures)";
      }
      else
      {
        return "Danh mc cc Class";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorVietnamese::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 268 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "y l cu trc c s d liu vi m t tm tt:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "y l cc classes vi cc m t tm tt:";
      }
      else
      {
        return "y l cc classes, structs, "
               "unions v interfaces vi cc m t tm tt:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorVietnamese::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1541 of file translator_vi.h.
    { return "Kiu d liu vi cc m t tm tt:"; }
trCompoundListFortran()
QCString TranslatorVietnamese::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1533 of file translator_vi.h.
    { return "Danh sch kiu d liu"; }
trCompoundMembers()
QCString TranslatorVietnamese::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 215 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cc trng d liu";
      }
      else
      {
        return "Cc thnh vin ca Class";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorVietnamese::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 287 of file translator_vi.h.
    {
      QCString result="Danh mc tt c cc ";
      if (!extractAll)
      {
        result+="( c m t) ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct v union fields";
      }
      else
      {
        result+="class members";
      }
      result+=" cng vi cc cc lin kt n ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="Thng tin v struct/union cho tng trng:";
        }
        else
        {
          result+="Thng tin v class cho tng thnh vin:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="cc structures/unions thuc:";
        }
        else
        {
          result+="cc lp thuc:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorVietnamese::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1545 of file translator_vi.h.
    {
      QCString result="Danh sch tt c ";
      if (!extractAll)
      {
        result+="( c m t) ";
      }
      result+="cc kiu d liu thnh vin";
      result+=" cng vi lin kt vi ";
      if (!extractAll)
      {
         result+="Thng tin cu trc d liu cho tng thnh vin";
      }
      else
      {
         result+=" cc kiu d liu thuc:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorVietnamese::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1537 of file translator_vi.h.
    { return "Trng d liu"; }
trCompoundReference()
QCString TranslatorVietnamese::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 604 of file translator_vi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Class"; break;
        case ClassDef::Struct:     result+=" Struct"; break;
        case ClassDef::Union:      result+=" Union"; break;
        case ClassDef::Interface:  result+=" Interface"; break;
        case ClassDef::Protocol:   result+=" Protocol"; break;
        case ClassDef::Category:   result+=" Category"; break;
        case ClassDef::Exception:  result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Tham chiu";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorVietnamese::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1609 of file translator_vi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Module"; break;
        case ClassDef::Struct:     result+=" Type"; break;
        case ClassDef::Union:      result+=" Union"; break;
        case ClassDef::Interface:  result+=" Interface"; break;
        case ClassDef::Protocol:   result+=" Protocol"; break;
        case ClassDef::Category:   result+=" Category"; break;
        case ClassDef::Exception:  result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Tham chiu";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorVietnamese::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 505 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cu trc c s d liu";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorVietnamese::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 839 of file translator_vi.h.
    {
      return "Thng tin v Constructor v Destructor";
    }
trDataTypes()
QCString TranslatorVietnamese::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1592 of file translator_vi.h.
    { return "Kiu d liu"; }
trDate()
QCString TranslatorVietnamese::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 543 of file translator_vi.h.
    { return "Ngy"; }
trDayOfWeek()
QCString TranslatorVietnamese::trDayOfWeek (int dayOfWeek, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1718 of file translator_vi.h.
    {
      static const char *days_short[]   = { "T2", "T3", "T4", "T5", "T6", "T7", "CN" };
      static const char *days_full[]    = { "Th Hai", "Th Ba", "Th T", "Th Nm", "Th Sau", "Th Bay", "Chu Nht" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod()
QCString TranslatorVietnamese::trDayPeriod (bool period) inline override virtual
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1732 of file translator_vi.h.
    {
      static const char *dayPeriod[] = { "SA", "CH" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorVietnamese::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 806 of file translator_vi.h.
    {
      return "nh ngha ti dng @0 trong file @1.";
    }
trDefinedIn()
QCString TranslatorVietnamese::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 182 of file translator_vi.h.
    { return "c nh ngha trong"; }
trDefinedInSourceFile()
QCString TranslatorVietnamese::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 810 of file translator_vi.h.
    {
      return "nh ngha trong file @0.";
    }
trDefineDocumentation()
QCString TranslatorVietnamese::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 475 of file translator_vi.h.
    { return "Thng tin v nh ngha"; }
trDefines()
QCString TranslatorVietnamese::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 439 of file translator_vi.h.
    { return "nh ngha"; }
trDefineValue()
QCString TranslatorVietnamese::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1129 of file translator_vi.h.
    {
      return "Gi tr:";
    }
trDeprecated()
QCString TranslatorVietnamese::trDeprecated () inline override virtual
Implements Translator.
Definition at line 819 of file translator_vi.h.
    {
      return "Khng tn thnh";
    }
trDeprecatedList()
QCString TranslatorVietnamese::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1322 of file translator_vi.h.
    {
      return "Danh sch Deprecated";
    }
trDetailedDescription()
QCString TranslatorVietnamese::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 111 of file translator_vi.h.
    { return "M t chi tit"; }
trDetails()
QCString TranslatorVietnamese::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 115 of file translator_vi.h.
    { return "Chi tit"; }
trDir()
QCString TranslatorVietnamese::trDir (bool first_capital, bool) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1489 of file translator_vi.h.
    {
      return createNoun(first_capital, false, "th mc", "");
    }
References Translator::createNoun().
trDirDocumentation()
QCString TranslatorVietnamese::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1471 of file translator_vi.h.
    { return "Thng tin v th mc"; }
trDirectories()
QCString TranslatorVietnamese::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1477 of file translator_vi.h.
    { return "Cc th mc"; }
trDirIndex()
QCString TranslatorVietnamese::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1465 of file translator_vi.h.
    { return "Cu trc th mc"; }
trDirReference()
QCString TranslatorVietnamese::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1483 of file translator_vi.h.
    { QCString result=dirName; result+=" Tham chiu th mc"; return result; }
trDocumentation()
QCString TranslatorVietnamese::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 365 of file translator_vi.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Thng tin"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorVietnamese::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 451 of file translator_vi.h.
    { return "Enumerations"; }
trEnumerationTypeDocumentation()
QCString TranslatorVietnamese::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 487 of file translator_vi.h.
    { return "Thng tin v Enumeration Type"; }
trEnumerationValueDocumentation()
QCString TranslatorVietnamese::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1521 of file translator_vi.h.
    { return "Thng tin Enumerator"; }
trEnumerationValues()
QCString TranslatorVietnamese::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 469 of file translator_vi.h.
    { return "Enumerator"; }
trEnumName()
QCString TranslatorVietnamese::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 174 of file translator_vi.h.
    { return "tn enum"; }
trEnumValue()
QCString TranslatorVietnamese::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 178 of file translator_vi.h.
    { return "gi tr enum"; }
trEventDocumentation()
QCString TranslatorVietnamese::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1339 of file translator_vi.h.
    {
      return "Thng tin v s kin";
    }
trEvents()
QCString TranslatorVietnamese::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1334 of file translator_vi.h.
    {
      return "S kin";
    }
trExamples()
QCString TranslatorVietnamese::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 245 of file translator_vi.h.
    { return "Cc v d"; }
trExamplesDescription()
QCString TranslatorVietnamese::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 351 of file translator_vi.h.
    { return "Danh sch tt c cc v d:"; }
trExceptions()
QCString TranslatorVietnamese::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 559 of file translator_vi.h.
    { return "Exceptions"; }
trFile()
QCString TranslatorVietnamese::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1211 of file translator_vi.h.
    {
      return createNoun(first_capital, singular, "file", "s");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorVietnamese::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 429 of file translator_vi.h.
    { return "Thng tin v File"; }
trFileIndex()
QCString TranslatorVietnamese::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 398 of file translator_vi.h.
    { return "File Index"; }
trFileList()
QCString TranslatorVietnamese::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 211 of file translator_vi.h.
    { return "Danh mc File"; }
trFileListDescription()
QCString TranslatorVietnamese::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 259 of file translator_vi.h.
    {
      QCString result="Danh mc y  tt c cc ";
      if (!extractAll) result+="( c bin son) ";
      result+="files cng vi cc m t tm tt:";
      return result;
    }
trFileMembers()
QCString TranslatorVietnamese::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 228 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Ton cc";
      }
      else
      {
        return "File thnh vin";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorVietnamese::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 329 of file translator_vi.h.
    {
      QCString result="Danh sch tt c cc ";
      if (!extractAll) result+="( c m tat) ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="functions, variables, defines, enums, v typedefs";
      }
      else
      {
        result+="cc file thnh vin";
      }
      result+=" cng vi links ti ";
      if (extractAll)
        result+="cc files thuc:";
      else
        result+="ti liu:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorVietnamese::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 626 of file translator_vi.h.
    {
      QCString result=fileName;
      result+=" File Tham chiu";
      return result;
    }
trFriends()
QCString TranslatorVietnamese::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 586 of file translator_vi.h.
    { return "Friends"; }
trFunctionDocumentation()
QCString TranslatorVietnamese::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 493 of file translator_vi.h.
    { return "Thng tin v hm"; }
trFunctions()
QCString TranslatorVietnamese::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 457 of file translator_vi.h.
    { return "Cc hm"; }
trGeneratedAt()
QCString TranslatorVietnamese::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 520 of file translator_vi.h.
    {
      QCString result="c bin son vo "+date;
      if (!projName.isEmpty()) result+=" cho m ngun d n "+projName;
      result+=" bi";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorVietnamese::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 166 of file translator_vi.h.
    { QCString result="c to ra bi Doxygen";
      if (!s.isEmpty()) result+=" cho "+s;
      result+=" t m ngun.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorVietnamese::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 563 of file translator_vi.h.
    { return "c bin son bi"; }
trGeneratedFromFiles()
QCString TranslatorVietnamese::trGeneratedFromFiles (ClassDef::CompoundType compType, bool) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 763 of file translator_vi.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Thng tin cho ";
      switch(compType)
      {
        case ClassDef::Class:      result+="class"; break;
        case ClassDef::Struct:     result+="struct"; break;
        case ClassDef::Union:      result+="union"; break;
        case ClassDef::Interface:  result+="interface"; break;
        case ClassDef::Protocol:   result+="protocol"; break;
        case ClassDef::Category:   result+="category"; break;
        case ClassDef::Exception:  result+="exception"; break;
        default: break;
      }
      result+=" c bin son t cc file sau y";
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorVietnamese::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1675 of file translator_vi.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Thng tin cho ";
      switch(compType)
      {
        case ClassDef::Class:      result+="module"; break;
        case ClassDef::Struct:     result+="type"; break;
        case ClassDef::Union:      result+="union"; break;
        case ClassDef::Interface:  result+="interface"; break;
        case ClassDef::Protocol:   result+="protocol"; break;
        case ClassDef::Category:   result+="category"; break;
        case ClassDef::Exception:  result+="exception"; break;
        default: break;
      }
      result+=" c bin son t cc file sau y";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorVietnamese::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1256 of file translator_vi.h.
    {
      return createNoun(first_capital, singular, "global", "s");
    }
References Translator::createNoun().
trGotoDocumentation()
QCString TranslatorVietnamese::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 849 of file translator_vi.h.
    {
      return "Ti Thng tin ca file ny.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorVietnamese::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 882 of file translator_vi.h.
    {
      return "Ti kin trc  ha ca Class";
    }
trGotoSourceCode()
QCString TranslatorVietnamese::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 844 of file translator_vi.h.
    {
      return "Ti m ngun ca file ny.";
    }
trGotoTextualHierarchy()
QCString TranslatorVietnamese::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 886 of file translator_vi.h.
    {
      return "Ti kin trc text ca Class";
    }
trGraphicalHierarchy()
QCString TranslatorVietnamese::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 878 of file translator_vi.h.
    {
      return "Kin trc  ha ca Class";
    }
trGroup()
QCString TranslatorVietnamese::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1229 of file translator_vi.h.
    {
      return createNoun(first_capital, singular, "group", "s");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorVietnamese::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 377 of file translator_vi.h.
    { return "Hierarchical Index"; }
trImplementedFromList()
QCString TranslatorVietnamese::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1290 of file translator_vi.h.
    {
      return "Thc hin "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorVietnamese::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1298 of file translator_vi.h.
    {
      return "c thc hin trong "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorVietnamese::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 978 of file translator_vi.h.
    {
      return " th ny biu th nhng file no trc tip hoc"
             "khng trc tip bao gm file ny:";
    }
trInclDepGraph()
QCString TranslatorVietnamese::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 834 of file translator_vi.h.
    {
      return "Km theo graph ph thuc cho "+fName+":";
    }
trIncludingInheritedMembers()
QCString TranslatorVietnamese::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 160 of file translator_vi.h.
    { return ", cng vi tt c cc thnh vin k tha."; }
trInheritedByList()
QCString TranslatorVietnamese::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 697 of file translator_vi.h.
    {
      return "c k tha bi "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList()
QCString TranslatorVietnamese::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 689 of file translator_vi.h.
    {
      return "K tha "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorVietnamese::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 869 of file translator_vi.h.
    {
      return "Gi tr khi to:";
    }
trInvariant()
QCString TranslatorVietnamese::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 864 of file translator_vi.h.
    {
      return "Bt bin";
    }
trISOLang()
QCString TranslatorVietnamese::trISOLang () inline override virtual
Implements Translator.
Definition at line 92 of file translator_vi.h.
    {
      return "vi";
    }
trLegend()
QCString TranslatorVietnamese::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1062 of file translator_vi.h.
    {
      return "Ch gii";
    }
trLegendDocs()
QCString TranslatorVietnamese::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1000 of file translator_vi.h.
    {
      return
        "Trang ny gii ngha cc biu  c bin son bi "
        " doxygen.<p>\n"
        "Hy xem xt cc v d sau:\n"
        "\\code\n"
        "/*! Cc lp khng thy c bi s ct ngn */\n"
        "Lp khng nhn thy class { };\n\n"
        "/*! class b ct, quan h k tha b n */\n"
        "class b ct : b n ton cc { };\n\n"
        "/* Class khng c m t vi cc ch gii doxygen */\n"
        "class khng c m t { };\n\n"
        "/*! Class c k tha s dng cc k tha public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*!  template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class c k tha s dng k tha protected */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class c k tha s dng k tha protected private */\n"
        "class PrivateBase { };\n\n"
        "/*! Class c s dng bi cc class k tha */\n"
        "class c s dng { };\n\n"
        "/*! Super class k tha mt s cc class khc */\n"
        "class c k tha : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Kt qu trong biu  sau y:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Cc hp trong biu  trn c  ngha nh sau:\n"
        "<ul>\n"
        "<li>%Hp mu xm biu th cu trc clas cho "
        "biu  c th hin.\n"
        "<li>%Hp c khung mu en biu th struct hoc class c m t.\n"
        "<li>%Hp c khung mu xm biu th struct hoc class cha c m t.\n"
        "<li>%Hp c khung mu  biu th struct hoc class c m t "
        "khi m khng phi tt c cc quan h k tha/containment c bin din.. %Biu  b "
        "ct nu n khng nm trn trong cc bin c cho trc..\n"
        "</ul>\n"
        "Cc mi tn c  ngha nh sau::\n"
        "<ul>\n"
        "<li>%Mi tn mu xanh m biu th cc quan h k tha cng khai "
        "gia 2 class.\n"
        "<li>%Mi tn mu xanh l cy m biu th k tha c bo v (protected).\n"
        "<li>%Mi tn  m biu th k tha dng private.\n"
        "<li>%Mi tn mu hng t qung biu th class c s dng "
        "bi class khc. Mi tn c gn nhn vi cc gi tr "
        "m cc calsss hoc struct c truy cp ti.\n"
        "<li>%Mi tn vng t qung c th quan h gia template instance v "
        "template class c dn xut t . Mi tn c gn nhn vi "
        "tham s ca template.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorVietnamese::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 993 of file translator_vi.h.
    {
      return "Ch gii Graph";
    }
trListOfAllMembers()
QCString TranslatorVietnamese::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 148 of file translator_vi.h.
    { return "Lit k tt c cc thnh vin"; }
trMainPage()
QCString TranslatorVietnamese::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 793 of file translator_vi.h.
    { return "Tranh chnh"; }
trMember()
QCString TranslatorVietnamese::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1247 of file translator_vi.h.
    {
      return createNoun(first_capital, singular, "member", "s");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorVietnamese::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 131 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Thng tin v trng";
      }
      else
      {
        return "Thng tin v Member Data";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorVietnamese::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 123 of file translator_vi.h.
    { return "Thng tin v Member Enumeration"; }
trMemberFunctionDocumentation()
QCString TranslatorVietnamese::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 127 of file translator_vi.h.
    { return "Thng tin v hm thnh vin"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorVietnamese::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1529 of file translator_vi.h.
    { return "Thng tin v cc hm v cc th tc thnh vin"; }
trMemberList()
QCString TranslatorVietnamese::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 152 of file translator_vi.h.
    { return "Danh sch thnh vin"; }
trMemberTypedefDocumentation()
QCString TranslatorVietnamese::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 119 of file translator_vi.h.
    { return "Thng tin v Member Typedef"; }
trModule()
QCString TranslatorVietnamese::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1668 of file translator_vi.h.
    {
      return createNoun(first_capital, singular, "module", "");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorVietnamese::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 404 of file translator_vi.h.
    { return "Thng tin v cc Module"; }
trModuleIndex()
QCString TranslatorVietnamese::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 371 of file translator_vi.h.
    { return "Ch mc (Index) Module"; }
trModuleReference()
QCString TranslatorVietnamese::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1630 of file translator_vi.h.
    {
      QCString result=namespaceName;
      result+=" Tham chiu Module";
      return result;
    }
trModules()
QCString TranslatorVietnamese::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 190 of file translator_vi.h.
    { return "Cc Modules"; }
trModulesDescription()
QCString TranslatorVietnamese::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 359 of file translator_vi.h.
    { return "Danh sch tt c cc thnh vin:"; }
trModulesIndex()
QCString TranslatorVietnamese::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1661 of file translator_vi.h.
    { return "Ch mc cc Module"; }
trModulesList()
QCString TranslatorVietnamese::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1596 of file translator_vi.h.
    { return "Danh sch Modules"; }
trModulesListDescription()
QCString TranslatorVietnamese::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1600 of file translator_vi.h.
    {
      QCString result="Danh sch tt c ";
      if (!extractAll) result+="( c m t) ";
      result+="cc module vi m t tm tt:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorVietnamese::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1642 of file translator_vi.h.
    {
      QCString result="Danh sch tt c ";
      if (!extractAll) result+="( c m t) ";
      result+="cc module thnh vin cng vi lin kt ti ";
      if (extractAll)
      {
        result+="Thng tin module cho tng thnh vin:";
      }
      else
      {
        result+="cc module thuc:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorVietnamese::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1638 of file translator_vi.h.
    { return "Thnh vin Module"; }
trMonth()
QCString TranslatorVietnamese::trMonth (int month, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1725 of file translator_vi.h.
    {
      static const char *months_short[] = { "Thg1", "Thg2", "Thg3", "Thg4", "Thg5", "Thg6", "Thg7", "Thg8", "Thg9", "Thg10", "Thg11", "Thg12" };
      static const char *months_full[]  = { "Thang Ging", "Thang Hai", "Thang Ba", "Thang T", "Thang Nm", "Thang Sau", "Thang Bay", "Thang Tam", "Thang Chin", "Thang Mi", "Thang Mi Mt", "Thang Mi Hai" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore()
QCString TranslatorVietnamese::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 144 of file translator_vi.h.
    { return "Tip..."; }
trNamespace()
QCString TranslatorVietnamese::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1220 of file translator_vi.h.
    {
      return createNoun(first_capital, singular, "namespace", "s");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorVietnamese::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 743 of file translator_vi.h.
    { return "Thng tin v Namespace"; }
trNamespaceIndex()
QCString TranslatorVietnamese::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 737 of file translator_vi.h.
    { return "Namespace Index"; }
trNamespaceList()
QCString TranslatorVietnamese::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 571 of file translator_vi.h.
    { return "Danh sch Namespace"; }
trNamespaceListDescription()
QCString TranslatorVietnamese::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 575 of file translator_vi.h.
    {
      QCString result="Danh sch tt c cc ";
      if (!extractAll) result+="( c bin tp) ";
      result+="namespaces vi m t tm tt:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorVietnamese::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 723 of file translator_vi.h.
    {
      QCString result="Danh sch tt c cc ";
      if (!extractAll) result+="( c bin son) ";
      result+="cc thnh vin namespace cng vi link ti ";
      if (extractAll)
        result+="Thng tin namespace cho tng thnh vin:";
      else
        result+=" namespaces m ph thuc bi:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorVietnamese::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 719 of file translator_vi.h.
    { return "Thnh vin Namespace"; }
trNamespaceReference()
QCString TranslatorVietnamese::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 634 of file translator_vi.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Tham chiu";
      return result;
    }
trNamespaces()
QCString TranslatorVietnamese::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 753 of file translator_vi.h.
    { return "Namespaces"; }
trNote()
QCString TranslatorVietnamese::trNote () inline override virtual
Implements Translator.
Definition at line 899 of file translator_vi.h.
    {
      return "Ghi ch";
    }
trOverloadText()
QCString TranslatorVietnamese::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1501 of file translator_vi.h.
    {
       return "Hm thnh vin dng overloaded, "
              "c ch ra cho vic tra cu d dng. N khc vi hm  trn"
              "ch  ch nhng tham s no n chp nhn.";
    }
trPackage()
QCString TranslatorVietnamese::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1114 of file translator_vi.h.
    {
      return "Gi "+name;
    }
trPackageAttribs()
QCString TranslatorVietnamese::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1375 of file translator_vi.h.
    {
      return "Cc thuc tnh Package";
    }
trPackageFunctions()
QCString TranslatorVietnamese::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1357 of file translator_vi.h.
    {
      return "Cc hm Package";
    }
trPackageListDescription()
QCString TranslatorVietnamese::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1119 of file translator_vi.h.
    {
      return "Danh sch cc gi cng vi m t tm tt (khi c th c):";
    }
trPackageMembers()
QCString TranslatorVietnamese::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1361 of file translator_vi.h.
    {
      return "Members Package";
    }
trPackages()
QCString TranslatorVietnamese::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1124 of file translator_vi.h.
    {
      return "Cc gi";
    }
trPackageTypes()
QCString TranslatorVietnamese::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1350 of file translator_vi.h.
    {
      return "Kiu gi";
    }
trPage()
QCString TranslatorVietnamese::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1238 of file translator_vi.h.
    {
      return createNoun(first_capital, singular, "trang", "");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorVietnamese::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 799 of file translator_vi.h.
    { return "tr."; }
trPageIndex()
QCString TranslatorVietnamese::trPageIndex () inline override virtual
Implements Translator.
Definition at line 890 of file translator_vi.h.
    {
      return "Ch mc trang";
    }
trParameters()
QCString TranslatorVietnamese::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 555 of file translator_vi.h.
    { return "Cc tham s"; }
trPostcondition()
QCString TranslatorVietnamese::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 859 of file translator_vi.h.
    {
      return "iu kin sau";
    }
trPrecondition()
QCString TranslatorVietnamese::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 854 of file translator_vi.h.
    {
      return "iu kin trc";
    }
trPrivateAttribs()
QCString TranslatorVietnamese::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 938 of file translator_vi.h.
    {
      return "Cc thuc tnh Private";
    }
trPrivateMembers()
QCString TranslatorVietnamese::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 655 of file translator_vi.h.
    { return "Cc hm thnh vin Private"; }
trPrivateSlots()
QCString TranslatorVietnamese::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 657 of file translator_vi.h.
    { return "Private Slots"; }
trPrivateTypes()
QCString TranslatorVietnamese::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 934 of file translator_vi.h.
    {
      return "Cc kiu Private";
    }
trProperties()
QCString TranslatorVietnamese::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1087 of file translator_vi.h.
    {
      return "Thuc tnh";
    }
trPropertyDocumentation()
QCString TranslatorVietnamese::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1092 of file translator_vi.h.
    {
      return "Thng tin thuc tnh (Property)";
    }
trProtectedAttribs()
QCString TranslatorVietnamese::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 926 of file translator_vi.h.
    {
      return "cc thuc tnh Protected";
    }
trProtectedMembers()
QCString TranslatorVietnamese::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 649 of file translator_vi.h.
    { return "Cc hm thnh vin Protected"; }
trProtectedSlots()
QCString TranslatorVietnamese::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 651 of file translator_vi.h.
    { return "Protected Slots"; }
trProtectedTypes()
QCString TranslatorVietnamese::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 922 of file translator_vi.h.
    {
      return "Cc kiu Protected";
    }
trPublicAttribs()
QCString TranslatorVietnamese::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 907 of file translator_vi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "cc trng  liu";
      }
      else
      {
        return "Cc thuc tnh Public";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorVietnamese::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 641 of file translator_vi.h.
    { return "Cc hm thnh vin Public"; }
trPublicSlots()
QCString TranslatorVietnamese::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 643 of file translator_vi.h.
    { return "Public Slots"; }
trPublicTypes()
QCString TranslatorVietnamese::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 903 of file translator_vi.h.
    {
      return "Public Types";
    }
trReferencedBy()
QCString TranslatorVietnamese::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 966 of file translator_vi.h.
    {
      return "Tham chiu bi";
    }
trReferenceManual()
QCString TranslatorVietnamese::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 433 of file translator_vi.h.
    { return "Thng tin tham chiu"; }
trReferences()
QCString TranslatorVietnamese::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1278 of file translator_vi.h.
    {
      return "Tham chiu";
    }
trReimplementedFromList()
QCString TranslatorVietnamese::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 705 of file translator_vi.h.
    {
      return "c thc thi li t "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorVietnamese::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 713 of file translator_vi.h.
    {
      return "c thc thi li trong "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorVietnamese::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 596 of file translator_vi.h.
    { return "Thng tin v Friends v cc hm lin quan"; }
trRelatedFunctions()
QCString TranslatorVietnamese::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 103 of file translator_vi.h.
    { return "Nhng hm lin quan"; }
trRelatedPages()
QCString TranslatorVietnamese::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 241 of file translator_vi.h.
    { return "Cc trang lin quan"; }
trRelatedPagesDescription()
QCString TranslatorVietnamese::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 355 of file translator_vi.h.
    { return "Danh sch tt c cc trang Thng tin c lin quan:"; }
trRelatedSubscript()
QCString TranslatorVietnamese::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 107 of file translator_vi.h.
    { return "(Ch  nhng hm ny khng phi l hm thnh vin.)"; }
trRemarks()
QCString TranslatorVietnamese::trRemarks () inline override virtual
Implements Translator.
Definition at line 970 of file translator_vi.h.
    {
      return "Ghi ch";
    }
trReturns()
QCString TranslatorVietnamese::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 547 of file translator_vi.h.
    { return "Gi tr tr v"; }
trReturnValues()
QCString TranslatorVietnamese::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 788 of file translator_vi.h.
    { return "Cc gi tr tr v"; }
trRTFansicp()
QCString TranslatorVietnamese::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1178 of file translator_vi.h.
    {
      return "1258";
    }
trRTFCharSet()
QCString TranslatorVietnamese::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1187 of file translator_vi.h.
    {
      return "163";
    }
trRTFGeneralIndex()
QCString TranslatorVietnamese::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1193 of file translator_vi.h.
    {
      return "Ch s";
    }
trRTFTableOfContents()
QCString TranslatorVietnamese::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1310 of file translator_vi.h.
    {
      return "Mc lc";
    }
trSearch()
QCString TranslatorVietnamese::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 249 of file translator_vi.h.
    { return "Tm kim"; }
trSearchMatches()
QCString TranslatorVietnamese::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1442 of file translator_vi.h.
    {
      return "Cc kt qu tha mn k:";
    }
trSearchResults()
QCString TranslatorVietnamese::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1423 of file translator_vi.h.
    {
      if (numDocuments==0)
      {
        return "Khng c ti liu no tha mn cc truy vn ca bn.";
      }
      else if (numDocuments==1)
      {
        return "Tm thy <b>1</b> ti liu tha m truy vn ca bn.";
      }
      else
      {
        return "Tm thy tt c <b>$num</b> ti liu tha m truy vn ca bn. "
               "Hin th nhng tha mn tt nht trc.";
      }
    }
trSearchResultsTitle()
QCString TranslatorVietnamese::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1411 of file translator_vi.h.
    {
      return "Kt qu tm kim";
    }
trSeeAlso()
QCString TranslatorVietnamese::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 551 of file translator_vi.h.
    { return "Xem thm"; }
trSignals()
QCString TranslatorVietnamese::trSignals () inline override virtual
Implements Translator.
Definition at line 645 of file translator_vi.h.
    { return "Signals"; }
trSince()
QCString TranslatorVietnamese::trSince () inline override virtual
Implements Translator.
Definition at line 983 of file translator_vi.h.
    {
      return "T";
    }
trSourceFile()
QCString TranslatorVietnamese::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1453 of file translator_vi.h.
    {
      return filename + " File ngun";
    }
trStaticPackageAttribs()
QCString TranslatorVietnamese::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1382 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Package";
    }
trStaticPackageFunctions()
QCString TranslatorVietnamese::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1368 of file translator_vi.h.
    {
      return "Cc hm Static Package";
    }
trStaticPrivateAttribs()
QCString TranslatorVietnamese::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 942 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Private";
    }
trStaticPrivateMembers()
QCString TranslatorVietnamese::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 659 of file translator_vi.h.
    { return "Cc hm thnh vin Static Private"; }
trStaticProtectedAttribs()
QCString TranslatorVietnamese::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 930 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Protected";
    }
trStaticProtectedMembers()
QCString TranslatorVietnamese::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 653 of file translator_vi.h.
    { return "Cc hm thnh vin Static Protected"; }
trStaticPublicAttribs()
QCString TranslatorVietnamese::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 918 of file translator_vi.h.
    {
      return "Cc thuc tnh Static Public";
    }
trStaticPublicMembers()
QCString TranslatorVietnamese::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 647 of file translator_vi.h.
    { return "Cc hm Static Public"; }
trSubprogram()
QCString TranslatorVietnamese::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1707 of file translator_vi.h.
    {
      return createNoun(first_capital, singular, "chng trnh con", "");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorVietnamese::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1586 of file translator_vi.h.
    { return "Thng tin v Function/Subroutine"; }
trSubprograms()
QCString TranslatorVietnamese::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1580 of file translator_vi.h.
    { return "Functions/Subroutines"; }
trTest()
QCString TranslatorVietnamese::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1072 of file translator_vi.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorVietnamese::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1077 of file translator_vi.h.
    {
      return "Danh sch Test";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorVietnamese::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 156 of file translator_vi.h.
    { return "Danh sch cc thnh vin y  cho"; }
trTodo()
QCString TranslatorVietnamese::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 952 of file translator_vi.h.
    {
      return "Mc tiu";
    }
trTodoList()
QCString TranslatorVietnamese::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 957 of file translator_vi.h.
    {
      return "Danh sch hng mc cn thc hin";
    }
trType()
QCString TranslatorVietnamese::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1699 of file translator_vi.h.
    {
      return createNoun(first_capital, false, "kiu", "");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorVietnamese::trTypeConstraints () inline override virtual
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1713 of file translator_vi.h.
    {
      return "Rng buc ca kiu (Type)";
    }
trTypedefDocumentation()
QCString TranslatorVietnamese::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 481 of file translator_vi.h.
    { return "Thng tin v Typedef"; }
trTypedefs()
QCString TranslatorVietnamese::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 445 of file translator_vi.h.
    { return "Typedefs"; }
trTypeDocumentation()
QCString TranslatorVietnamese::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1574 of file translator_vi.h.
    { return "Thng tin v kiu d liu"; }
trVariableDocumentation()
QCString TranslatorVietnamese::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 499 of file translator_vi.h.
    { return "Thng tin v cc bin"; }
trVariables()
QCString TranslatorVietnamese::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 463 of file translator_vi.h.
    { return "Cc bin"; }
trVersion()
QCString TranslatorVietnamese::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 539 of file translator_vi.h.
    { return "Phin bn"; }
trWarning()
QCString TranslatorVietnamese::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 535 of file translator_vi.h.
    { return "Lu "; }
trWriteList()
QCString TranslatorVietnamese::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 665 of file translator_vi.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=", v ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_vi.h