Doxygen: TranslatorBrazilian Class Reference
TranslatorBrazilian Class Reference
#include <src/translator_br.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description.
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool single) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
QCString trDesignUnitDocumentation () override
VHDL design unit documentation.
QCString trConcept (bool first_capital, bool singular) override
C++20 concept.
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
QCString trPackageList () override
QCString trFlowchart () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
QCString trCopyToClipboard () override
QCString trImportant () override
Public Member Functions inherited from Translator
virtual QCString updateNeededMessage ()
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Detailed Description
Definition at line 171 of file translator_br.h.
Member Function Documentation
getLanguageString()
QCString TranslatorBrazilian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 211 of file translator_br.h.
    {
      return "0x416 Portuguese(Brazil)";
    }
idLanguage()
QCString TranslatorBrazilian::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 183 of file translator_br.h.
    {
      return "brazilian";
    }
latexLanguageSupportCommand()
QCString TranslatorBrazilian::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 202 of file translator_br.h.
    {
      return "\\usepackage[brazil]{babel}";
    }
trAdditionalInheritedMembers()
QCString TranslatorBrazilian::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 2065 of file translator_br.h.
    { return "Outros membros herdados"; }
trAll()
QCString TranslatorBrazilian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1560 of file translator_br.h.
    {
      return "Todos";
    }
trAndMore()
QCString TranslatorBrazilian::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 2037 of file translator_br.h.
    { return "e "+number+" mais..."; }
trAttention()
QCString TranslatorBrazilian::trAttention () inline override virtual
Implements Translator.
Definition at line 1137 of file translator_br.h.
    {
      return "Ateno";
    }
trAuthor()
QCString TranslatorBrazilian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1433 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "autor", "es");
    }
References Translator::createNoun().
trBug()
QCString TranslatorBrazilian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1305 of file translator_br.h.
    {
      return "Bug";
    }
trBugList()
QCString TranslatorBrazilian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1310 of file translator_br.h.
    {
      return "Lista de Bugs";
    }
trCallerGraph()
QCString TranslatorBrazilian::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1683 of file translator_br.h.
    {
      return "Esse  o diagrama das funes que utilizam essa funo:";
    }
trCallGraph()
QCString TranslatorBrazilian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1565 of file translator_br.h.
    {
      return "Este  o diagrama das funes utilizadas por essa funo:";
    }
trCiteReferences()
QCString TranslatorBrazilian::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 2009 of file translator_br.h.
    { return "Referncias Bibliogrficas"; }
trClass()
QCString TranslatorBrazilian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1368 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "classe", "s");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trClassDiagram()
QCString TranslatorBrazilian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 653 of file translator_br.h.
    {
      return "Diagrama de hierarquia da classe "+clName+":";
    }
trClassDocumentation()
QCString TranslatorBrazilian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 534 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorBrazilian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1268 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de dados";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorBrazilian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 319 of file translator_br.h.
    { return "Hierarquia de Classes"; }
trClassHierarchyDescription()
QCString TranslatorBrazilian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 378 of file translator_br.h.
    { return "Esta lista de hierarquias est parcialmente ordenada (ordem alfabtica):"; }
trClassMethods()
QCString TranslatorBrazilian::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2103 of file translator_br.h.
    {
      return "Mtodos da classe";
    }
trCode()
QCString TranslatorBrazilian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 1037 of file translator_br.h.
    {
      return "cdigo";
    }
trCollaborationDiagram()
QCString TranslatorBrazilian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 992 of file translator_br.h.
    {
      return "Diagrama de colaborao para "+clName+":";
    }
trCompoundIndex()
QCString TranslatorBrazilian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 507 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndice das Estruturas de Dados";
      }
      else
      {
        return "ndice dos Componentes";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorBrazilian::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1735 of file translator_br.h.
    { return "ndice de Tipos de Dados"; }
trCompoundList()
QCString TranslatorBrazilian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 323 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de Dados";
      }
      else
      {
        return "Lista de Classes";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorBrazilian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 391 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Aqui esto as estruturas de dados, unies e suas respectivas descries:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Aqui esto as classes e suas respectivas descries:";
      }
      else
      {
        return "Aqui esto as classes, estruturas, unies e interfaces e suas respectivas descries:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorBrazilian::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1712 of file translator_br.h.
    { return "Aqui esto os tipos de dados com descries resumidas:"; }
trCompoundListFortran()
QCString TranslatorBrazilian::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1704 of file translator_br.h.
    { return "Lista de Tipos de Dados"; }
trCompoundMembers()
QCString TranslatorBrazilian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 340 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de Dados";
      }
      else
      {
        return "Membros de classe";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorBrazilian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 408 of file translator_br.h.
    {
      QCString result="Esta  a lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas as estruturas e campos de unies ";
        if (!extractAll)
        {
          result+="documentados";
        }
      }
      else
      {
        result+="todos os membros de classes ";
        if (!extractAll)
        {
          result+="documentados";
        }
      }
      result+=" com referncias para ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a documentao da estrutura/unio de cada campo:";
        }
        else
        {
          result+="a documentao da classe de cada membro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a estrutura/unio a que pertencem:";
        }
        else
        {
          result+="a classe a que pertencem:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorBrazilian::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1716 of file translator_br.h.
    {
      QCString result="Esta  a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos tipos de dados com links para ";
      if (extractAll)
      {
        result+="a documentao dos tipos de dados para cada membro:";
      }
      else
      {
        result+="os tipos de dados a que pertencem:";
      }
      return result;
    }
trCompoundMembersDescriptionTotal()
QCString TranslatorBrazilian::trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2620 of file translator_br.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool masculine = PortugueseTranslatorUtils::isClassMemberHighlightMasculine(hl);
      QCString result="Esta  a list de ";
      result+= (masculine?"todos os ":"todas as ");
      switch (hl)
      {
        case ClassMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="estruturas e unies";
          }
          else
          {
            result+="membros de classe";
          }
          break;
        case ClassMemberHighlight::Functions:
          result+="funes";
          break;
        case ClassMemberHighlight::Variables:
          result+="variveis";
          break;
        case ClassMemberHighlight::Typedefs:
          result+="definies de tipo";
          break;
        case ClassMemberHighlight::Enums:
          result+="enumeraes";
          break;
        case ClassMemberHighlight::EnumValues:
          result+="valores enumerados";
          break;
        case ClassMemberHighlight::Properties:
          result+="propriedades";
          break;
        case ClassMemberHighlight::Events:
          result+="eventos";
          break;
        case ClassMemberHighlight::Related:
          result+="smbolos relacionados";
          break;
        case ClassMemberHighlight::Total: // for completeness
          break;
      }
      if (!extractAll)
      {
        result+= masculine?" documentados":" documentadas";
      }
      result+=" com links para ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a documentao da estrutura/unio para cada campo:";
        }
        else
        {
          result+="a documentao da classe para cada membro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a estrutura/unio a que petencem:";
        }
        else
        {
          result+="a classe a que pertencem:";
        }
      }
      return result;
    }
References ClassMemberHighlight::All, Config_getBool, ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, PortugueseTranslatorUtils::isClassMemberHighlightMasculine(), ClassMemberHighlight::Properties, ClassMemberHighlight::Related, ClassMemberHighlight::Total, ClassMemberHighlight::Typedefs, and ClassMemberHighlight::Variables.
trCompoundMembersFortran()
QCString TranslatorBrazilian::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1708 of file translator_br.h.
    { return "Campos de Dados"; }
trCompoundReference()
QCString TranslatorBrazilian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 728 of file translator_br.h.
    {
      QCString result="Referncia";
      if (isTemplate) result+=" do Template";
      if (compType == ClassDef::Protocol)
      {
        result+=" do ";
      }
      else
      {
        result+=" da ";
      }
      switch(compType)
      {
        case ClassDef::Class:      result+="Classe "; break;
        case ClassDef::Struct:     result+="Estrutura "; break;
        case ClassDef::Union:      result+="Unio "; break;
        case ClassDef::Interface:  result+="Interface "; break;
        case ClassDef::Protocol:   result+="Protocolo "; break;
        case ClassDef::Category:   result+="Categoria "; break;
        case ClassDef::Exception:  result+="Exceo "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorBrazilian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1776 of file translator_br.h.
    {
      QCString result = "Referncia ";
      if (isTemplate) result+="da Template ";
      switch(compType)
      {
        case ClassDef::Class:      result+="do Modulo "; break;
        case ClassDef::Struct:     result+="do Tipo "; break;
        case ClassDef::Union:      result+="da Unio "; break;
        case ClassDef::Interface:  result+="da Interface "; break;
        case ClassDef::Protocol:   result+="do Protocolo "; break;
        case ClassDef::Category:   result+="da Categoria "; break;
        case ClassDef::Exception:  result+="da Exceo "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice()
QCString TranslatorBrazilian::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) inline override virtual
Implements Translator.
Definition at line 2403 of file translator_br.h.
    {
      QCString result="Referncia ";
      switch(compType)
      {
        case ClassDef::Class:      result+="da Classe "; break;
        case ClassDef::Struct:     result+="da Estrutura "; break;
        case ClassDef::Union:      result+="da Unio "; break;
        case ClassDef::Interface:  result+="da Interface "; break;
        case ClassDef::Protocol:   result+="do Protocolo "; break;
        case ClassDef::Category:   result+="da Categoria "; break;
        case ClassDef::Exception:  result+="da Exceo "; break;
        default: break;
      }
      if (isLocal) result+="Local ";
      result+= clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorBrazilian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 629 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de Dados";
      }
      else
      {
        return "Componentes";
      }
    }
References Config_getBool.
trCompoundType()
QCString TranslatorBrazilian::trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) inline override virtual
the compound type as used for the xrefitems
Implements Translator.
Definition at line 2541 of file translator_br.h.
    {
      QCString result;
      switch(compType)
      {
        case ClassDef::Class:
          if (lang == SrcLangExt::Fortran) trType(true,true);
          else result=trClass(true,true);
          break;
        case ClassDef::Struct:     result="Estrutura"; break;
        case ClassDef::Union:      result="Unio"; break;
        case ClassDef::Interface:  result="Interface"; break;
        case ClassDef::Protocol:   result="Protocolo"; break;
        case ClassDef::Category:   result="Categoria"; break;
        case ClassDef::Exception:  result="Exceo"; break;
        case ClassDef::Service:    result="Servio"; break;
        case ClassDef::Singleton:  result="Singleton"; break;
        default: break;
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, Fortran, ClassDef::Interface, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, ClassDef::Struct, trClass(), trType(), and ClassDef::Union.
trConcept()
QCString TranslatorBrazilian::trConcept (bool first_capital, bool singular) inline override virtual
C++20 concept.
Implements Translator.
Definition at line 2453 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "conceito", "s");
    }
References Translator::createNoun().
trConceptDefinition()
QCString TranslatorBrazilian::trConceptDefinition () inline override virtual
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2487 of file translator_br.h.
    {
        return "Definio de conceito";
    }
trConceptDocumentation()
QCString TranslatorBrazilian::trConceptDocumentation () inline override virtual
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2474 of file translator_br.h.
    { return "Documentao do Conceito"; }
trConceptIndex()
QCString TranslatorBrazilian::trConceptIndex () inline override virtual
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2470 of file translator_br.h.
    { return "ndice de Conceitos"; }
trConceptList()
QCString TranslatorBrazilian::trConceptList () inline override virtual
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2466 of file translator_br.h.
    { return "Lista de Conceitos"; }
trConceptListDescription()
QCString TranslatorBrazilian::trConceptListDescription (bool extractAll) inline override virtual
used as an introduction to the concept list
Implements Translator.
Definition at line 2478 of file translator_br.h.
    {
        QCString result="Esta  a lista de todos os conceitos ";
        if (!extractAll) result+="documentados ";
        result+="com suas respectivas descries:";
        return result;
    }
trConceptReference()
QCString TranslatorBrazilian::trConceptReference (const QCString & conceptName) inline override virtual
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2458 of file translator_br.h.
    {
        QCString result= "Referncia do Conceito ";
        result+=conceptName;
        return result;
    }
trConstantDocumentation()
QCString TranslatorBrazilian::trConstantDocumentation () inline override virtual
Implements Translator.
Definition at line 2311 of file translator_br.h.
    {
        return "Constantes";
    }
trConstantGroupReference()
QCString TranslatorBrazilian::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2140 of file translator_br.h.
    {
      QCString result = "Referncia do grupo de constantes ";
      result += namespaceName;
      return result;
    }
trConstantGroups()
QCString TranslatorBrazilian::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2136 of file translator_br.h.
    { return "Grupos de Constantes"; }
trConstants()
QCString TranslatorBrazilian::trConstants () inline override virtual
Implements Translator.
Definition at line 2307 of file translator_br.h.
    {
        return "Constantes";
    }
trConstructorDocumentation()
QCString TranslatorBrazilian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 1002 of file translator_br.h.
    {
      return "Construtores e Destrutores";
    }
trCopyright()
QCString TranslatorBrazilian::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 2013 of file translator_br.h.
    {
      // Note: I will left it as is because "Direitos autorais" may not fit
      // in the text.
      return "Copyright";
    }
trCopyToClipboard()
QCString TranslatorBrazilian::trCopyToClipboard () inline override virtual
Implements Translator.
Definition at line 2820 of file translator_br.h.
    {
      return "Copiado para a rea de transferncia";
    }
trCustomReference()
QCString TranslatorBrazilian::trCustomReference (const QCString & name) inline override virtual
Implements Translator.
Definition at line 2303 of file translator_br.h.
    { return "Referncia de " + QCString(name); }
trDataMemberDocumentation()
QCString TranslatorBrazilian::trDataMemberDocumentation () inline override virtual
Implements Translator.
Definition at line 2433 of file translator_br.h.
    {
        return "Dados Membros";
    }
trDataMembers()
QCString TranslatorBrazilian::trDataMembers () inline override virtual
Implements Translator.
Definition at line 2429 of file translator_br.h.
    {
        return "Dados Membros";
    }
trDataTypes()
QCString TranslatorBrazilian::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1759 of file translator_br.h.
    { return "Tipos de Dados"; }
trDate()
QCString TranslatorBrazilian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 667 of file translator_br.h.
    { return "Data"; }
trDateTime()
QCString TranslatorBrazilian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1962 of file translator_br.h.
    {
      static const char *days[]   = { "Segunda","Tera","Quarta","Quinta","Sexta","Sbado","Domingo" };
      static const char *months[] = { "Janeiro","Fevereiro","Maro","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s, %d de %s de %d",days[dayOfWeek-1],day,months[month-1],year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorBrazilian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1982 of file translator_br.h.
    {
      static const char *days_short[]   = { "seg", "ter", "qua", "qui", "sex", "sb", "dom" };
      static const char *days_full[]    = { "segunda-feira", "tera-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sbado", "domingo" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorBrazilian::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1998 of file translator_br.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period?1:0];
    }
trDeclaration()
QCString TranslatorBrazilian::trDeclaration () inline override virtual
Implements Translator.
Definition at line 2749 of file translator_br.h.
{ return "Declarao";}
trDefinedAtLineInSourceFile()
QCString TranslatorBrazilian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 969 of file translator_br.h.
    {
      return "Definio na linha @0 do arquivo @1.";
    }
trDefinedIn()
QCString TranslatorBrazilian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 307 of file translator_br.h.
    { return "definido(a) em"; }
trDefinedInSourceFile()
QCString TranslatorBrazilian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 973 of file translator_br.h.
    {
      return "Definio no arquivo @0.";
    }
trDefineDocumentation()
QCString TranslatorBrazilian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 599 of file translator_br.h.
    { return "Definies e macros"; }
trDefines()
QCString TranslatorBrazilian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 563 of file translator_br.h.
    { return "Definies e Macros"; }
trDefineValue()
QCString TranslatorBrazilian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1295 of file translator_br.h.
    {
      return "Valor:";
    }
trDefinition()
QCString TranslatorBrazilian::trDefinition () inline override virtual
Implements Translator.
Definition at line 2748 of file translator_br.h.
{ return "Definio";}
trDeprecated()
QCString TranslatorBrazilian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 982 of file translator_br.h.
    {
      return "Obsoleto(a)";
    }
trDeprecatedList()
QCString TranslatorBrazilian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1488 of file translator_br.h.
    {
      return "Lista de itens obsoletos";
    }
trDesignUnitDocumentation()
QCString TranslatorBrazilian::trDesignUnitDocumentation () inline override virtual
VHDL design unit documentation.
Implements Translator.
Definition at line 2443 of file translator_br.h.
    {
        return "Documentao da Unidade de Projeto";
    }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorBrazilian::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Implements Translator.
Definition at line 2194 of file translator_br.h.
    { return "Hierarquia da Unidade de Design"; }
trDesignUnitIndex()
QCString TranslatorBrazilian::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Implements Translator.
Definition at line 2209 of file translator_br.h.
    { return "ndice de Unidades de Design"; }
trDesignUnitList()
QCString TranslatorBrazilian::trDesignUnitList () inline override virtual
VHDL design unit list.
Implements Translator.
Definition at line 2197 of file translator_br.h.
    { return "Lista de Unidades de Design"; }
trDesignUnitListDescription()
QCString TranslatorBrazilian::trDesignUnitListDescription () inline override virtual
VHDL design unit list description.
Implements Translator.
Definition at line 2203 of file translator_br.h.
    {
        return "Esta  uma lista de todos os membros de unidades de design "
                        "com ligaes para as entidades s quais pertencem:";
    }
trDesignUnitMembers()
QCString TranslatorBrazilian::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Implements Translator.
Definition at line 2200 of file translator_br.h.
    { return "Membros da Unidade de Design"; }
trDesignUnits()
QCString TranslatorBrazilian::trDesignUnits () inline override virtual
VHDL design units.
Implements Translator.
Definition at line 2212 of file translator_br.h.
    { return "Unidades de Design"; }
trDetailedDescription()
QCString TranslatorBrazilian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 227 of file translator_br.h.
    { return "Descrio detalhada"; }
trDetailLevel()
QCString TranslatorBrazilian::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 2029 of file translator_br.h.
    { return "nvel de detalhes"; }
trDetails()
QCString TranslatorBrazilian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 231 of file translator_br.h.
    { return "Detalhes"; }
trDictionaries()
QCString TranslatorBrazilian::trDictionaries () inline override virtual
Implements Translator.
Definition at line 2323 of file translator_br.h.
    {
        return "Dicionrios";
    }
trDictionaryDocumentation()
QCString TranslatorBrazilian::trDictionaryDocumentation () inline override virtual
Implements Translator.
Definition at line 2327 of file translator_br.h.
    {
        return "Dicionrios";
    }
trDir()
QCString TranslatorBrazilian::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1659 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "diretrio", "s");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorBrazilian::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 2021 of file translator_br.h.
    { return QCString("Grafo de dependncias do diretrio ")+name+":"; }
trDirDocumentation()
QCString TranslatorBrazilian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1637 of file translator_br.h.
    { return "Documentao do Diretrio"; }
trDirectories()
QCString TranslatorBrazilian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1643 of file translator_br.h.
    { return "Diretrios"; }
trDirIndex()
QCString TranslatorBrazilian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1631 of file translator_br.h.
    { return "Hierarquia de Diretrios"; }
trDirReference()
QCString TranslatorBrazilian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1649 of file translator_br.h.
    {
        QCString result = "Referncia do diretrio ";
        result += dirName;
        return result;
    }
trDirRelation()
QCString TranslatorBrazilian::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1901 of file translator_br.h.
    {
      return "Relao " + QCString(name);
    }
trDocumentation()
QCString TranslatorBrazilian::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 489 of file translator_br.h.
    { return "Documentao" + (!projName.isEmpty()? " de " + projName : ""); }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorBrazilian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 575 of file translator_br.h.
    { return "Enumeraes"; }
trEnumerationTypeDocumentation()
QCString TranslatorBrazilian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 611 of file translator_br.h.
    { return "Enumeraes"; }
trEnumerationValueDocumentation()
QCString TranslatorBrazilian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1691 of file translator_br.h.
    { return "Documentao da enumerao"; }
trEnumerationValues()
QCString TranslatorBrazilian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 593 of file translator_br.h.
    { return "Enumeradores"; }
trEnumGeneratedFromFiles()
QCString TranslatorBrazilian::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 2041 of file translator_br.h.
    { QCString result = "A documentao para essa enumerao foi gerada a partir ";
      if (single) {
        result += "do seguinte arquivo:";
      } else {
        result += "dos seguintes arquivos:";
      }
      return result;
    }
trEnumName()
QCString TranslatorBrazilian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 299 of file translator_br.h.
    { return "Enumerao"; }
trEnumReference()
QCString TranslatorBrazilian::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 2052 of file translator_br.h.
    {
      QCString result = "Referncia da enumerao ";
      return result + name;
    }
trEnumValue()
QCString TranslatorBrazilian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 303 of file translator_br.h.
    { return "Valor enumerado"; }
trEventDocumentation()
QCString TranslatorBrazilian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1505 of file translator_br.h.
    {
      return "Eventos";
    }
trEvents()
QCString TranslatorBrazilian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1500 of file translator_br.h.
    {
      return "Eventos";
    }
trExamples()
QCString TranslatorBrazilian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 370 of file translator_br.h.
    { return "Exemplos"; }
trExamplesDescription()
QCString TranslatorBrazilian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 477 of file translator_br.h.
    { return "Lista de todos os exemplos:"; }
trExceptionDocumentation()
QCString TranslatorBrazilian::trExceptionDocumentation () inline override virtual
Implements Translator.
Definition at line 2399 of file translator_br.h.
    {
        return "Excees";
    }
trExceptionHierarchy()
QCString TranslatorBrazilian::trExceptionHierarchy () inline override virtual
Implements Translator.
Definition at line 2391 of file translator_br.h.
    {
        return "Hierarquia de Excees";
    }
trExceptionHierarchyDescription()
QCString TranslatorBrazilian::trExceptionHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2395 of file translator_br.h.
    {
        return "Esta  a lista parcialmente ordenadas de heranas:";
    }
trExceptionIndex()
QCString TranslatorBrazilian::trExceptionIndex () inline override virtual
Implements Translator.
Definition at line 2379 of file translator_br.h.
    {
        return "ndice the Excees";
    }
trExceptionList()
QCString TranslatorBrazilian::trExceptionList () inline override virtual
Implements Translator.
Definition at line 2383 of file translator_br.h.
    {
        return "Lista de Excees";
    }
trExceptionListDescription()
QCString TranslatorBrazilian::trExceptionListDescription () inline override virtual
Implements Translator.
Definition at line 2387 of file translator_br.h.
    {
        return "Estas so as excees com suas respectivas descries:";
    }
trExceptions()
QCString TranslatorBrazilian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 683 of file translator_br.h.
    { return "Excees"; }
trExportedModules()
QCString TranslatorBrazilian::trExportedModules () inline override virtual
Implements Translator.
Definition at line 2811 of file translator_br.h.
    {
      return "Mdulos Exportados";
    }
trExtendsClass()
QCString TranslatorBrazilian::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2095 of file translator_br.h.
    {
      return "estende a classe @0.";
    }
trFile()
QCString TranslatorBrazilian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1377 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "arquivo", "s");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorBrazilian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 553 of file translator_br.h.
    { return "Arquivos"; }
trFileIn()
QCString TranslatorBrazilian::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1938 of file translator_br.h.
    {
      return "Arquivo em "+name;
    }
trFileIndex()
QCString TranslatorBrazilian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 522 of file translator_br.h.
    { return "ndice dos Arquivos"; }
trFileList()
QCString TranslatorBrazilian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 336 of file translator_br.h.
    { return "Lista de Arquivos"; }
trFileListDescription()
QCString TranslatorBrazilian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 382 of file translator_br.h.
    {
      QCString result="Esta  a lista de todos os arquivos ";
      if (!extractAll) result+="documentados ";
      result+="e suas respectivas descries:";
      return result;
    }
trFileMembers()
QCString TranslatorBrazilian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 353 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globais";
      }
      else
      {
        return "Membros dos Arquivos";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorBrazilian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 455 of file translator_br.h.
    {
      QCString result="Esta  a lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas as funes, variveis, definies, enumeraes e definies de tipos ";
        if (!extractAll) result+="documentadas ";
      }
      else
      {
        result+="todos os membros dos arquivos ";
        if (!extractAll) result+="documentados ";
      }
      result+="com referncias para ";
      if (extractAll)
        result+="seus respectivos arquivos:";
      else
        result+="suas respectivas documentaes:";
      return result;
    }
References Config_getBool.
trFileMembersDescriptionTotal()
QCString TranslatorBrazilian::trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2563 of file translator_br.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool masculine = PortugueseTranslatorUtils::isFileMemberHighlightMasculine(hl);
      QCString result="Esta  a list de ";
      result+= (masculine?"todos os ":"todas as ");
      switch (hl)
      {
        case FileMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="funes, variveis, definies, enumeraes e definies de tipos";
          }
          else
          {
            result+="membros do arquivo";
          }
          break;
        case FileMemberHighlight::Functions:
          result+="funes";
          break;
        case FileMemberHighlight::Variables:
          result+="variveis";
          break;
        case FileMemberHighlight::Typedefs:
          result+="definies de tipos";
          break;
        case FileMemberHighlight::Sequences:
          result+="sequencias";
          break;
        case FileMemberHighlight::Dictionaries:
          result+="dicionrios";
          break;
        case FileMemberHighlight::Enums:
          result+="enumeraes";
          break;
        case FileMemberHighlight::EnumValues:
          result+="valores da enumerao";
          break;
        case FileMemberHighlight::Defines:
          result+="definies/macros";
          break;
        case FileMemberHighlight::Total: // for completeness
          break;
      }
      if (!extractAll)
      {
        result+= masculine? " documentados": " documentadas";
      }
      result+=" com links para ";
      if (extractAll)
        result+="os arquivos aos quais pertencem:";
      else
        result+="a documentao:";
      return result;
    }
References FileMemberHighlight::All, Config_getBool, FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, PortugueseTranslatorUtils::isFileMemberHighlightMasculine(), FileMemberHighlight::Sequences, FileMemberHighlight::Total, FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
trFileReference()
QCString TranslatorBrazilian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 758 of file translator_br.h.
    {
      QCString result = "Referncia do Arquivo ";
      result += fileName;
      return result;
    }
trFlowchart()
QCString TranslatorBrazilian::trFlowchart () inline override virtual
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2505 of file translator_br.h.
    {
        return "Fluxograma:";
    }
trFriends()
QCString TranslatorBrazilian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 710 of file translator_br.h.
    { return "Amigos"; }
trFunctionAndProc()
QCString TranslatorBrazilian::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Implements Translator.
Definition at line 2215 of file translator_br.h.
    { return "Funes/Procedimentos/Processos"; }
trFunctionDocumentation()
QCString TranslatorBrazilian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 617 of file translator_br.h.
    { return "Funes"; }
trFunctions()
QCString TranslatorBrazilian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 581 of file translator_br.h.
    { return "Funes"; }
trGeneratedAt()
QCString TranslatorBrazilian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 644 of file translator_br.h.
    {
      QCString result="Gerado em "+date;
      if (!projName.isEmpty()) result+=" para "+projName;
      result+=" por";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorBrazilian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 291 of file translator_br.h.
    { QCString result="Gerado automaticamente por Doxygen";
      if (!s.isEmpty()) result+=" para "+s;
      result+=" a partir do cdigo fonte.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorBrazilian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 687 of file translator_br.h.
    { return "Gerado por"; }
trGeneratedFromFiles()
QCString TranslatorBrazilian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 913 of file translator_br.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="A documentao para ";
      if (compType == ClassDef::Protocol)
      {
         result+= "esse ";
      }
      else
      {
         result+= "essa ";
      }
      switch(compType)
      {
        case ClassDef::Class:      result+=vhdlOpt?"Unidade de Design ":"classe "; break;
        case ClassDef::Struct:     result+="estrutura "; break;
        case ClassDef::Union:      result+="unio "; break;
        case ClassDef::Interface:  result+="interface "; break;
        case ClassDef::Protocol:   result+="protocolo "; break;
        case ClassDef::Category:   result+="categoria "; break;
        case ClassDef::Exception:  result+="exceo "; break;
        default: break;
      }
      result+=" foi gerada a partir ";
      if (single) result+="do seguinte arquivo:"; else result+="dos seguintes arquivos:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorBrazilian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1846 of file translator_br.h.
    {
      // single is true implies a single file
      QCString result="A documentao para ";
      switch(compType)
      {
        case ClassDef::Class:      result+="esse modulo "; break;
        case ClassDef::Struct:     result+="esse tipo "; break;
        case ClassDef::Union:      result+="essa unio "; break;
        case ClassDef::Interface:  result+="essa interface "; break;
        case ClassDef::Protocol:   result+="esso protocolo "; break;
        case ClassDef::Category:   result+="essa categoria "; break;
        case ClassDef::Exception:  result+="essa exceo "; break;
        default: break;
      }
      result+=" foi gerada a partir do";
      if (single)
        result+=" seguinte arquivo:";
      else
        result+="s seguintes arquivos:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorBrazilian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1422 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "globa", "ais", "l");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorBrazilian::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1913 of file translator_br.h.
    {
      return "Namespace global";
    }
trGotoDocumentation()
QCString TranslatorBrazilian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 1012 of file translator_br.h.
    {
      return "Ir para a documentao desse arquivo.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorBrazilian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 1045 of file translator_br.h.
    {
      return "Ir para o grfico de hierarquia de classes";
    }
trGotoSourceCode()
QCString TranslatorBrazilian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 1007 of file translator_br.h.
    {
      return "Ir para o cdigo-fonte desse arquivo.";
    }
trGotoTextualHierarchy()
QCString TranslatorBrazilian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 1049 of file translator_br.h.
    {
      return "Ir para a hierarquia de classes (texto)";
    }
trGraphicalHierarchy()
QCString TranslatorBrazilian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 1041 of file translator_br.h.
    {
      return "Grfico de Hierarquia de Classes";
    }
trGroup()
QCString TranslatorBrazilian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1395 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "grupo", "s");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorBrazilian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 501 of file translator_br.h.
    { return "ndice Hierrquico"; }
trImplementedFromList()
QCString TranslatorBrazilian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1456 of file translator_br.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorBrazilian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1464 of file translator_br.h.
    {
      return "Implementado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImportant()
QCString TranslatorBrazilian::trImportant () inline override virtual
Implements Translator.
Definition at line 2827 of file translator_br.h.
    {
      return "Importante";
    }
trInclByDepGraph()
QCString TranslatorBrazilian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 1141 of file translator_br.h.
    {
      return "Este grafo mostra quais arquivos esto direta ou indiretamente relacionados com esse arquivo:";
    }
trInclDepGraph()
QCString TranslatorBrazilian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 997 of file translator_br.h.
    {
      return "Grfico de dependncia de incluses para "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorBrazilian::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1947 of file translator_br.h.
    {
      return "Inclui arquivo em "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorBrazilian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 285 of file translator_br.h.
    { return ", incluindo os membros herdados."; }
trInheritedByList()
QCString TranslatorBrazilian::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 847 of file translator_br.h.
    {
      return "Superclasse de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorBrazilian::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 2059 of file translator_br.h.
    { return QCString(members)+" herdados de "+what; }
trInheritsList()
QCString TranslatorBrazilian::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 839 of file translator_br.h.
    {
      return "Subclasse de " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorBrazilian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 1032 of file translator_br.h.
    {
      return "Valor inicial:";
    }
trInstanceMethods()
QCString TranslatorBrazilian::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2111 of file translator_br.h.
    {
      return "Mtodos da instncia";
    }
trInterfaceDocumentation()
QCString TranslatorBrazilian::trInterfaceDocumentation () inline override virtual
Implements Translator.
Definition at line 2355 of file translator_br.h.
    {
        return "Interfaces";
    }
trInterfaceHierarchy()
QCString TranslatorBrazilian::trInterfaceHierarchy () inline override virtual
Implements Translator.
Definition at line 2347 of file translator_br.h.
    {
        return "Hierarquia de Interfaces";
    }
trInterfaceHierarchyDescription()
QCString TranslatorBrazilian::trInterfaceHierarchyDescription () inline override virtual
Implements Translator.
Definition at line 2351 of file translator_br.h.
    {
        return "Esta  a lista parcialmente ordenadas de heranas:";
    }
trInterfaceIndex()
QCString TranslatorBrazilian::trInterfaceIndex () inline override virtual
Implements Translator.
Definition at line 2335 of file translator_br.h.
    {
        return "ndice de Interfaces";
    }
trInterfaceList()
QCString TranslatorBrazilian::trInterfaceList () inline override virtual
Implements Translator.
Definition at line 2339 of file translator_br.h.
    {
        return "Lista de Interfaces";
    }
trInterfaceListDescription()
QCString TranslatorBrazilian::trInterfaceListDescription () inline override virtual
Implements Translator.
Definition at line 2343 of file translator_br.h.
    {
        return "Estas so as interfaces com suas respectivas descries:";
    }
trInterfaces()
QCString TranslatorBrazilian::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2128 of file translator_br.h.
    { return "Interfaces Exportadas"; }
trInvariant()
QCString TranslatorBrazilian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 1027 of file translator_br.h.
    {
      return "Invariante";
    }
trISOLang()
QCString TranslatorBrazilian::trISOLang () inline override virtual
Implements Translator.
Definition at line 207 of file translator_br.h.
    {
      return "pt-BR";
    }
trLegend()
QCString TranslatorBrazilian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1228 of file translator_br.h.
    {
      return "legenda";
    }
trLegendDocs()
QCString TranslatorBrazilian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1162 of file translator_br.h.
    {
      return
        "Esta pgina explica como interpretar os grafos gerados pelo doxygen.<p>\n"
        "Considere o seguinte exemplo:\n"
        "\\code\n"
        "/*! Classe oculta por causa da truncagem */\n"
        "class Invisible { };\n\n"
        "/*! Classe Truncated, relao de herana est oculta */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe no documentada com os comentrios do Doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe possui que possui uma relao de herana pblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Um template de classe */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe possui que possui uma relao de herana protegida  */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe possui que possui uma relao de herana privada  */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe utilizada pela classe Inherited */\n"
        "class Used { };\n\n"
        "/*! Super classe que herda outras classes */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Isto ir gerar o seguinte grfo:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "As caixas no grafo acima possuem os seguintes significados:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Uma caixa cinza denota a estrutura ou a classe que gerou"
        "este grafo.</li>\n"
        "<li>Uma caixa com a borda preta denota uma estrutura ou classe documentada.</li>\n"
        "<li>Uma caixa com a borda cinza denota uma estrutura ou classe no documentada.</li>\n"
        "<li>Uma caixa com a borda vermelha denota uma estrutura ou classe na"
        "qual nem todas as relaes so mostradas. Um grafo  truncado quando "
        "esse no cabe no espao especificado.</li>\n"
        "</ul>\n"
        "<p>\n"
        "As setas possuem os seguintes significados:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Uma seta azul escura denota a relao de herana pblica entre "
        "duas classes.</li>\n"
        "<li>Uma seta verde escura denota a relao de herana protegida entre "
        "duas classes.</li>\n"
        "<li>Uma seta vermelha escura denota a relao de herana privada entre "
        "duas classes.</li>\n"
        "<li>Uma seta pontilhada prpura denota a relao de uso e/ou agragao "
        "por outra classe/estrutura. A etiqueta da seta denota o nome do(s) campo(s) "
        "que representa(m) este apontamento.</li>\n"
        "<li>Uma seta pontilhada amarela denota a relao de instanciao de uma "
        "<em>template</em>. A etiqueta da seta denota os parmetros de instanciao "
        "desta <em>template</em>.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorBrazilian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 1155 of file translator_br.h.
    {
      return "Legenda do Grafo";
    }
trListOfAllMembers()
QCString TranslatorBrazilian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 273 of file translator_br.h.
    { return "Lista de todos os Membros"; }
trLoading()
QCString TranslatorBrazilian::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1907 of file translator_br.h.
    {
      return "Carregando...";
    }
trMainPage()
QCString TranslatorBrazilian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 953 of file translator_br.h.
    { return "Pgina Principal"; }
trMember()
QCString TranslatorBrazilian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1413 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "membro", "s");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorBrazilian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 256 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos";
      }
      else
      {
        return "Atributos";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorBrazilian::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 239 of file translator_br.h.
    { return "Documentao das enumeraes"; }
trMemberFunctionDocumentation()
QCString TranslatorBrazilian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 243 of file translator_br.h.
    {
        if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
        {
          return "Documentao das funes, procedimentos e processos";
        }
        else
        {
            return "Documentao das funes";
        }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran()
QCString TranslatorBrazilian::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1700 of file translator_br.h.
    { return "Documentao de Funo Membro/Subrotina"; }
trMemberList()
QCString TranslatorBrazilian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 277 of file translator_br.h.
    { return "Lista dos Membros"; }
trMemberTypedefDocumentation()
QCString TranslatorBrazilian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 235 of file translator_br.h.
    { return "Documentao das definies de tipos"; }
trMethodDocumentation()
QCString TranslatorBrazilian::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2118 of file translator_br.h.
    {
      return "Documentao do mtodo";
    }
trModule()
QCString TranslatorBrazilian::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1838 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "mdulo", "s");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorBrazilian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 528 of file translator_br.h.
    { return "Mdulos"; }
trModuleIndex()
QCString TranslatorBrazilian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 495 of file translator_br.h.
    { return "ndice dos mdulos"; }
trModuleMembersDescriptionTotal()
QCString TranslatorBrazilian::trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2765 of file translator_br.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool masculine = PortugueseTranslatorUtils::isModuleMemberHighlightMasculine(hl);
      QCString result="Esta  a list de ";
      result+= (masculine?"todos os ":"todas as ");
      QCString singularResult = "";
      QCString pluralResult = "";
      switch (hl)
      {
        case ModuleMemberHighlight::All:
          singularResult="membro";
          break;
        case ModuleMemberHighlight::Functions:
          singularResult="funo";
          pluralResult="funes";
          break;
        case ModuleMemberHighlight::Variables:
          singularResult="varivel";
          pluralResult="variveis";
          break;
        case ModuleMemberHighlight::Typedefs:
          singularResult="definio de tipo";
          pluralResult="definies de tipo";
          break;
        case ModuleMemberHighlight::Enums:
          singularResult="enumerao";
          pluralResult="enumeraes";
          break;
        case ModuleMemberHighlight::EnumValues:
          singularResult="valor enumerado";
          pluralResult="valores enumerados";
          break;
        case ModuleMemberHighlight::Total: // for completeness
          break;
      }
      result+=(pluralResult.isEmpty() ? singularResult+"s" : pluralResult);
      result+="do mdulo ";
      if (!extractAll) result+="documentado ";
      result+=" com links para ";
      if (extractAll)
        result+="a documentao de cada " + singularResult + ":";
      else
        result+="o mdulo a que pertencem:";
      return result;
    }
References ModuleMemberHighlight::All, Config_getBool, ModuleMemberHighlight::Enums, ModuleMemberHighlight::EnumValues, ModuleMemberHighlight::Functions, QCString::isEmpty(), PortugueseTranslatorUtils::isModuleMemberHighlightMasculine(), ModuleMemberHighlight::Total, ModuleMemberHighlight::Typedefs, and ModuleMemberHighlight::Variables.
trModuleReference()
QCString TranslatorBrazilian::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1800 of file translator_br.h.
    {
      QCString result = "Referncia do Mdulo ";
      result += namespaceName;
      return result;
    }
trModules()
QCString TranslatorBrazilian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 315 of file translator_br.h.
    { return "Mdulos"; }
trModulesDescription()
QCString TranslatorBrazilian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 485 of file translator_br.h.
    { return "Lista de todos os mdulos:"; }
trModulesIndex()
QCString TranslatorBrazilian::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1831 of file translator_br.h.
    { return "ndice dos Mdulos"; }
trModulesList()
QCString TranslatorBrazilian::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1763 of file translator_br.h.
    { return "Lista de Mdulos"; }
trModulesListDescription()
QCString TranslatorBrazilian::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1767 of file translator_br.h.
    {
      QCString result="Esta  a lista de todos os mdulos ";
      if (!extractAll) result+="documentados ";
      result+="com descries resumidas:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorBrazilian::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1812 of file translator_br.h.
    {
      QCString result="Esta  a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos mdulos com links para ";
      if (extractAll)
      {
        result+="a documentao dos mdulos para cada membro:";
      }
      else
      {
        result+="os mdulos a que pertencem:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorBrazilian::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1808 of file translator_br.h.
    { return "Membros do Mdulo"; }
trMonth()
QCString TranslatorBrazilian::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1990 of file translator_br.h.
    {
      static const char *months_short[] = { "jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez" };
      static const char *months_full[]  = { "janeiro", "fevereiro", "maro", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorBrazilian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 269 of file translator_br.h.
    { return "Mais..."; }
trNamespace()
QCString TranslatorBrazilian::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1386 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "namespace", "s");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorBrazilian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 893 of file translator_br.h.
    { return "Namespace"; }
trNamespaceIndex()
QCString TranslatorBrazilian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 887 of file translator_br.h.
    { return "Namespaces"; }
trNamespaceList()
QCString TranslatorBrazilian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 695 of file translator_br.h.
    { return "Lista de Namespaces"; }
trNamespaceListDescription()
QCString TranslatorBrazilian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 699 of file translator_br.h.
    {
      QCString result="Esta  a lista de todos os Namespaces ";
      if (!extractAll) result+="documentados ";
      result+="com suas respectivas descries:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorBrazilian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 873 of file translator_br.h.
    {
      QCString result="Essa  a lista com todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="do Namespace com referncias para ";
      if (extractAll)
        result+="a documentao do Namespace para cada membro:";
      else
        result+="os seus respectivos Namespaces:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorBrazilian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 869 of file translator_br.h.
    { return "Membros do namespace"; }
trNamespaceMembersDescriptionTotal()
QCString TranslatorBrazilian::trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) inline override virtual
Implements Translator.
Definition at line 2695 of file translator_br.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      bool masculine = PortugueseTranslatorUtils::isNamespaceMemberHighlightMasculine(hl);
      QCString result="Esta  a list de ";
      result+= (masculine?"todos os ":"todas as ");
      QCString singularResult = "";
      QCString pluralResult = "";
      switch (hl)
      {
        case NamespaceMemberHighlight::All:
          singularResult="membro";
          break;
        case NamespaceMemberHighlight::Functions:
          singularResult="funo";
          pluralResult="funes";
          break;
        case NamespaceMemberHighlight::Variables:
          singularResult="varivel";
          pluralResult="variveis";
          break;
        case NamespaceMemberHighlight::Typedefs:
          singularResult="definio de tipo";
          pluralResult="definies de tipo";
          break;
        case NamespaceMemberHighlight::Sequences:
          singularResult="sequencia";
          pluralResult="sequencias";
          break;
        case NamespaceMemberHighlight::Dictionaries:
          singularResult="dicionrio";
          break;
        case NamespaceMemberHighlight::Enums:
          singularResult="enumerao";
          pluralResult="enumeraes";
          break;
        case NamespaceMemberHighlight::EnumValues:
          singularResult="valor enumerado";
          pluralResult="valores enumerados";
          break;
        case NamespaceMemberHighlight::Total: // for completeness
          break;
      }
      result+=(pluralResult.isEmpty() ? singularResult+"s" : pluralResult);
      result+=" do namespace ";
      if (!extractAll) result+=" documentado";
      result+=" com links para ";
      if (extractAll)
        result+="a documentao de cada " + singularResult + ":";
      else
        result+="o namespace a que pertencem:";
      return result;
    }
References NamespaceMemberHighlight::All, Config_getBool, NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, QCString::isEmpty(), PortugueseTranslatorUtils::isNamespaceMemberHighlightMasculine(), NamespaceMemberHighlight::Sequences, NamespaceMemberHighlight::Total, NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
trNamespaceReference()
QCString TranslatorBrazilian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 766 of file translator_br.h.
    {
      QCString result ="Refncia do Namespace ";
      result += namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorBrazilian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 903 of file translator_br.h.
    { return "Namespaces"; }
trNoMatches()
QCString TranslatorBrazilian::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1925 of file translator_br.h.
    {
      return "Nenhuma entrada encontrado";
    }
trNote()
QCString TranslatorBrazilian::trNote () inline override virtual
Implements Translator.
Definition at line 1062 of file translator_br.h.
    {
      return "Observao";
    }
trOperationDocumentation()
QCString TranslatorBrazilian::trOperationDocumentation () inline override virtual
Implements Translator.
Definition at line 2425 of file translator_br.h.
    {
        return "Operaes";
    }
trOperations()
QCString TranslatorBrazilian::trOperations () inline override virtual
Implements Translator.
Definition at line 2421 of file translator_br.h.
    {
        return "Operaes";
    }
trOverloadText()
QCString TranslatorBrazilian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1671 of file translator_br.h.
    {
       return "Esse  um mtodo provido por convenincia. "
                "Ele difere do mtodo acima apenas na lista de "
                "argumentos que devem ser utilizados.";
    }
trPackage()
QCString TranslatorBrazilian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1280 of file translator_br.h.
    {
      return "Pacote "+name;
    }
trPackageAttribs()
QCString TranslatorBrazilian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1541 of file translator_br.h.
    {
      return "Atributos do Pacote";
    }
trPackageFunctions()
QCString TranslatorBrazilian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1523 of file translator_br.h.
    {
      return "Funes do Pacote";
    }
trPackageList()
QCString TranslatorBrazilian::trPackageList () inline override virtual
Implements Translator.
Definition at line 2495 of file translator_br.h.
    { return "Lista de pacotes"; }
trPackageListDescription()
QCString TranslatorBrazilian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1285 of file translator_br.h.
    {
      return "Esta  a lista com os pacotes e suas respectivas descries (quando disponveis):";
    }
trPackageMembers()
QCString TranslatorBrazilian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1527 of file translator_br.h.
    {
      return "Membros do Pacote";
    }
trPackages()
QCString TranslatorBrazilian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1290 of file translator_br.h.
    {
      return "Pacotes";
    }
trPackageTypes()
QCString TranslatorBrazilian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1516 of file translator_br.h.
    {
      return "Tipos do Pacote";
    }
trPage()
QCString TranslatorBrazilian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1404 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "pgina", "s");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorBrazilian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 959 of file translator_br.h.
    {
      // Decidi mudar de pgina para "p." para ficar mais compacto.
      return "p.";
    }
trPageIndex()
QCString TranslatorBrazilian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 1053 of file translator_br.h.
    {
      return "ndice da Pgina";
    }
trPanelSynchronisationTooltip()
QCString TranslatorBrazilian::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 2076 of file translator_br.h.
    {
      QCString opt = enable ? "ativar" : "desativar";
      return "clique para "+opt+" a sincronizao do painel";
    }
trParameters()
QCString TranslatorBrazilian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 679 of file translator_br.h.
    { return "Parmetros"; }
trPostcondition()
QCString TranslatorBrazilian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 1022 of file translator_br.h.
    {
      return "Ps-condio";
    }
trPrecondition()
QCString TranslatorBrazilian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 1017 of file translator_br.h.
    {
      return "Pr-condio";
    }
trPrivateAttribs()
QCString TranslatorBrazilian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 1101 of file translator_br.h.
    {
      return "Atributos Privados";
    }
trPrivateMembers()
QCString TranslatorBrazilian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 803 of file translator_br.h.
    { return "Membros privados"; }
trPrivateSlots()
QCString TranslatorBrazilian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 806 of file translator_br.h.
    { return "Slots privados"; }
trPrivateTypes()
QCString TranslatorBrazilian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 1097 of file translator_br.h.
    {
      return "Tipos Privados";
    }
trProperties()
QCString TranslatorBrazilian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1253 of file translator_br.h.
    {
      return "Propriedades";
    }
trPropertyDocumentation()
QCString TranslatorBrazilian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1258 of file translator_br.h.
    {
      return "Propriedades";
    }
trProtectedAttribs()
QCString TranslatorBrazilian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 1089 of file translator_br.h.
    {
      return "Atributos Protegidos";
    }
trProtectedMembers()
QCString TranslatorBrazilian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 794 of file translator_br.h.
    { return "Membros protegidos"; }
trProtectedSlots()
QCString TranslatorBrazilian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 797 of file translator_br.h.
    { return "Slots protegidos"; }
trProtectedTypes()
QCString TranslatorBrazilian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 1085 of file translator_br.h.
    {
      return "Tipos Protegidos";
    }
trProvidedByCategory()
QCString TranslatorBrazilian::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2086 of file translator_br.h.
    {
      return "Provido pela categoria @0.";
    }
trPublicAttribs()
QCString TranslatorBrazilian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 1070 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de Dados";
      }
      else
      {
        return "Atributos Pblicos";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorBrazilian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 773 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_JAVA))
      {
        return "Mtodos Pblicos";
      }
      else
      {
        return "Membros Pblicos";
      }
    }
References Config_getBool.
trPublicSlots()
QCString TranslatorBrazilian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 785 of file translator_br.h.
    { return "Slots Pblicos"; }
trPublicTypes()
QCString TranslatorBrazilian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 1066 of file translator_br.h.
    {
      return "Tipos Pblicos";
    }
trReferencedBy()
QCString TranslatorBrazilian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 1129 of file translator_br.h.
    {
      return "Referenciado(a) por";
    }
trReferenceManual()
QCString TranslatorBrazilian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 557 of file translator_br.h.
    { return "Guia de Referncia"; }
trReferences()
QCString TranslatorBrazilian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1444 of file translator_br.h.
    {
      return "Referencias";
    }
trReimplementedFromList()
QCString TranslatorBrazilian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 855 of file translator_br.h.
    {
      return "Reimplementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorBrazilian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 863 of file translator_br.h.
    {
      return "Reimplementado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorBrazilian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 720 of file translator_br.h.
    { return "Amigos e Funes Relacionadas"; }
trRelatedFunctions()
QCString TranslatorBrazilian::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 219 of file translator_br.h.
    { return "Funes relacionadas"; }
trRelatedPages()
QCString TranslatorBrazilian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 366 of file translator_br.h.
    { return "Pginas relacionadas"; }
trRelatedPagesDescription()
QCString TranslatorBrazilian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 481 of file translator_br.h.
    { return "Lista de toda a documentao relacionadas:"; }
trRelatedSubscript()
QCString TranslatorBrazilian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 223 of file translator_br.h.
    { return "(Note que estas no so funes membros.)"; }
trRelatedSymbolDocumentation()
QCString TranslatorBrazilian::trRelatedSymbolDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes.
Supersedes trRelatedFunctionDocumentation
Implements Translator.
Definition at line 2537 of file translator_br.h.
    { return "Documentao dos smbolos amigos e relacionados"; }
trRelatedSymbols()
QCString TranslatorBrazilian::trRelatedSymbols () inline override virtual
Please translate also updated body of the method trMemberFunctionDocumentation(), now better adapted for VHDL sources documentation.
used in the compound documentation before a list of related symbols.
Supersedes trRelatedFunctions
Implements Translator.
Definition at line 2522 of file translator_br.h.
    { return "Smbolos relacionados"; }
trRelatedSymbolsSubscript()
QCString TranslatorBrazilian::trRelatedSymbolsSubscript () inline override virtual
subscript for the related symbols
Supersedes trRelatedSubscript
Implements Translator.
Definition at line 2529 of file translator_br.h.
    { return "(Note que estes no so smbolos membros.)"; }
trRemarks()
QCString TranslatorBrazilian::trRemarks () inline override virtual
Implements Translator.
Definition at line 1133 of file translator_br.h.
    {
      return "Anotaes";
    }
trReturns()
QCString TranslatorBrazilian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 671 of file translator_br.h.
    { return "Retorna"; }
trReturnValues()
QCString TranslatorBrazilian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 948 of file translator_br.h.
    { return "Valores Retornados"; }
trRTFansicp()
QCString TranslatorBrazilian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1344 of file translator_br.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorBrazilian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1353 of file translator_br.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorBrazilian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1359 of file translator_br.h.
    {
      return "Sumrio";
    }
trRTFTableOfContents()
QCString TranslatorBrazilian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1476 of file translator_br.h.
    {
      return "Sumrio";
    }
trSearch()
QCString TranslatorBrazilian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 374 of file translator_br.h.
    { return "Busca"; }
trSearching()
QCString TranslatorBrazilian::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1919 of file translator_br.h.
    {
      return "Procurando...";
    }
trSearchMatches()
QCString TranslatorBrazilian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1608 of file translator_br.h.
    {
      return "Resultados:";
    }
trSearchResults()
QCString TranslatorBrazilian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1589 of file translator_br.h.
    {
      if (numDocuments==0)
      {
        return "Nenhum documento foi encontrado.";
      }
      else if (numDocuments==1)
      {
        return "Apenas <b>1</b> documento foi encontrado.";
      }
      else
      {
        return "<b>$num</b> documentos encontrados. "
               "Mostrando os melhores resultados primeiro.";
      }
    }
trSearchResultsTitle()
QCString TranslatorBrazilian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1577 of file translator_br.h.
    {
      return "Resultado da Busca";
    }
trSeeAlso()
QCString TranslatorBrazilian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 675 of file translator_br.h.
    { return "Veja tambm"; }
trSequenceDocumentation()
QCString TranslatorBrazilian::trSequenceDocumentation () inline override virtual
Implements Translator.
Definition at line 2319 of file translator_br.h.
    {
        return "Sequncias";
    }
trSequences()
QCString TranslatorBrazilian::trSequences () inline override virtual
Implements Translator.
Definition at line 2315 of file translator_br.h.
    {
        return "Sequncias";
    }
trServiceGeneratedFromFiles()
QCString TranslatorBrazilian::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 2163 of file translator_br.h.
    {
      // single is true implies a single file
      QCString result="A documentao para esse servio "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte arquivo:";
      } else {
        result+="dos seguintes arquivos:";
      }
      return result;
    }
trServiceReference()
QCString TranslatorBrazilian::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 2147 of file translator_br.h.
    {
      QCString result = "Referncia do servio ";
      result += sName;
      return result;
    }
trServices()
QCString TranslatorBrazilian::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2132 of file translator_br.h.
    { return "Servios Inclusos"; }
trSignals()
QCString TranslatorBrazilian::trSignals () inline override virtual
Implements Translator.
Definition at line 788 of file translator_br.h.
    { return "Sinais"; }
trSince()
QCString TranslatorBrazilian::trSince () inline override virtual
Implements Translator.
Definition at line 1145 of file translator_br.h.
    {
      return "Desde";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorBrazilian::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 2176 of file translator_br.h.
    {
      // single is true implies a single file
      QCString result="A documentao para esse Singleton "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte arquivo:";
      } else {
        result+="dos: seguintes arquivos:";
      }
      return result;
    }
trSingletonReference()
QCString TranslatorBrazilian::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 2154 of file translator_br.h.
    {
      // TODO: Emerson Ferreira proposes to add emphasis around the word
      // Singleton but I'm not sure if this will work for non HTML generators.
      QCString result = "Referncia do Singleton ";
      result += sName;
      return result;
    }
trSliceInterfaces()
QCString TranslatorBrazilian::trSliceInterfaces () inline override virtual
Implements Translator.
Definition at line 2331 of file translator_br.h.
    {
        return "Interfaces";
    }
trSourceFile()
QCString TranslatorBrazilian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1619 of file translator_br.h.
    {
      return  "Cdigo-Fonte de " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorBrazilian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1548 of file translator_br.h.
    {
      return "Atributos Estticos do Pacote";
    }
trStaticPackageFunctions()
QCString TranslatorBrazilian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1534 of file translator_br.h.
    {
      return "Funes Estticas do Pacote";
    }
trStaticPrivateAttribs()
QCString TranslatorBrazilian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 1105 of file translator_br.h.
    {
      return "Atributos Privados Estticos";
    }
trStaticPrivateMembers()
QCString TranslatorBrazilian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 809 of file translator_br.h.
    { return "Membros privados estticos"; }
trStaticProtectedAttribs()
QCString TranslatorBrazilian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 1093 of file translator_br.h.
    {
      return "Atributos Protegidos Estticos";
    }
trStaticProtectedMembers()
QCString TranslatorBrazilian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 800 of file translator_br.h.
    { return "Membros protegidos estticos"; }
trStaticPublicAttribs()
QCString TranslatorBrazilian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 1081 of file translator_br.h.
    {
      return "Atributos Pblicos Estticos";
    }
trStaticPublicMembers()
QCString TranslatorBrazilian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 791 of file translator_br.h.
    { return "Membros pblicos estticos"; }
trStructDocumentation()
QCString TranslatorBrazilian::trStructDocumentation () inline override virtual
Implements Translator.
Definition at line 2375 of file translator_br.h.
    {
        return "Estruturas";
    }
trStructIndex()
QCString TranslatorBrazilian::trStructIndex () inline override virtual
Implements Translator.
Definition at line 2363 of file translator_br.h.
    {
        return "ndice de Estruturas";
    }
trStructList()
QCString TranslatorBrazilian::trStructList () inline override virtual
Implements Translator.
Definition at line 2367 of file translator_br.h.
    {
        return "Lista de Estruturas";
    }
trStructListDescription()
QCString TranslatorBrazilian::trStructListDescription () inline override virtual
Implements Translator.
Definition at line 2371 of file translator_br.h.
    {
        return "Estas so as estruturas com suas respectivas descries:";
    }
trStructs()
QCString TranslatorBrazilian::trStructs () inline override virtual
Implements Translator.
Definition at line 2359 of file translator_br.h.
    {
        return "Estruturas";
    }
trSubprogram()
QCString TranslatorBrazilian::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1885 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "subrotina", "s");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorBrazilian::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1753 of file translator_br.h.
    { return "Documentao da Funo/Subrotina"; }
trSubprograms()
QCString TranslatorBrazilian::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1747 of file translator_br.h.
    { return "Funes/Subrotinas"; }
trTemplateParameters()
QCString TranslatorBrazilian::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 2033 of file translator_br.h.
    { return "Parmetros do template"; }
trTest()
QCString TranslatorBrazilian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1238 of file translator_br.h.
    {
      return "Teste";
    }
trTestList()
QCString TranslatorBrazilian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1243 of file translator_br.h.
    {
      return "Lista de Testes";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorBrazilian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 281 of file translator_br.h.
    { return "Esta  a lista de todos os membros de"; }
trTodo()
QCString TranslatorBrazilian::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 1115 of file translator_br.h.
    {
      return "Atividades futuras";
    }
trTodoList()
QCString TranslatorBrazilian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 1120 of file translator_br.h.
    {
      return "Lista de atividades futuras";
    }
trTopicDocumentation()
QCString TranslatorBrazilian::trTopicDocumentation () inline override virtual
Implements Translator.
Definition at line 2757 of file translator_br.h.
    { return "Tpico"; }
trTopicIndex()
QCString TranslatorBrazilian::trTopicIndex () inline override virtual
Implements Translator.
Definition at line 2761 of file translator_br.h.
    { return "ndice de Tpicos"; }
trTopicList()
QCString TranslatorBrazilian::trTopicList () inline override virtual
Implements Translator.
Definition at line 2759 of file translator_br.h.
    { return "Lista de Tpicos"; }
trTopicListDescription()
QCString TranslatorBrazilian::trTopicListDescription () inline override virtual
Implements Translator.
Definition at line 2763 of file translator_br.h.
    { return "Esta  uma lista de todos os tpicos e suas descries:"; }
trTopics()
QCString TranslatorBrazilian::trTopics () inline override virtual
Implements Translator.
Definition at line 2755 of file translator_br.h.
    { return "Tpicos"; }
trType()
QCString TranslatorBrazilian::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1876 of file translator_br.h.
    {
      return createNoun(first_capital, singular, "tipo", "s");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trTypeConstraints()
QCString TranslatorBrazilian::trTypeConstraints () inline override virtual
C# Type Contraint list
Implements Translator.
Definition at line 1891 of file translator_br.h.
    {
      return "Restries do Tipo";
    }
trTypedefDocumentation()
QCString TranslatorBrazilian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 605 of file translator_br.h.
    { return "Definies dos tipos"; }
trTypedefs()
QCString TranslatorBrazilian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 569 of file translator_br.h.
    { return "Definies de Tipos"; }
trTypeDocumentation()
QCString TranslatorBrazilian::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1741 of file translator_br.h.
    { return "Documentao dos Tipos de Dados"; }
trVariableDocumentation()
QCString TranslatorBrazilian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 623 of file translator_br.h.
    { return "Variveis"; }
trVariables()
QCString TranslatorBrazilian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 587 of file translator_br.h.
    { return "Variveis"; }
trVersion()
QCString TranslatorBrazilian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 663 of file translator_br.h.
    { return "Verso"; }
trVhdlType()
QCString TranslatorBrazilian::trVhdlType (VhdlSpecifier type, bool single) inline override virtual
VHDL type.
Implements Translator.
Definition at line 2218 of file translator_br.h.
    {
      switch(type)
      {
        case VhdlSpecifier::LIBRARY:
          if (single) return "Biblioteca";
          else        return "Bibliotecas";
        case VhdlSpecifier::PACKAGE:
          if (single) return "Pacote";
          else        return "Pacotes";
        case VhdlSpecifier::SIGNAL:
          if (single) return "Sinal";
          else        return "Sinais";
        case VhdlSpecifier::COMPONENT:
          if (single) return "Componente";
          else        return "Componentes";
        case VhdlSpecifier::CONSTANT:
          if (single) return "Constante";
          else        return "Constantes";
        case VhdlSpecifier::ENTITY:
          if (single) return "Entidade";
          else        return "Entidades";
        case VhdlSpecifier::TYPE:
          if (single) return "Tipo";
          else        return "Tipos";
        case VhdlSpecifier::SUBTYPE:
          if (single) return "Subtipo";
          else        return "Subtipos";
        case VhdlSpecifier::FUNCTION:
          if (single) return "Funo";
          else        return "Funes";
        case VhdlSpecifier::RECORD:
          if (single) return "Registro";
          else        return "Registros";
        case VhdlSpecifier::PROCEDURE:
          if (single) return "Procedimento";
          else        return "Procedimentos";
        case VhdlSpecifier::ARCHITECTURE:
          if (single) return "Arquitetura";
          else        return "Arquiteturas";
        case VhdlSpecifier::ATTRIBUTE:
          if (single) return "Atributo";
          else        return "Atributos";
        case VhdlSpecifier::PROCESS:
          if (single) return "Processo";
          else        return "Processos";
        case VhdlSpecifier::PORT:
          if (single) return "Porta";
          else        return "Portas";
        case VhdlSpecifier::USE:
          if (single) return "clusula de uso";
          else        return "clusulas de uso";
        case VhdlSpecifier::GENERIC:
          if (single) return "Generico";
          else        return "Genericos";
        case VhdlSpecifier::PACKAGE_BODY:
          return "Corpo do Pacote";
        case VhdlSpecifier::UNITS:
          return "Unidades";
        case VhdlSpecifier::SHAREDVARIABLE:
          if (single) return "Varivel Compartilhada";
          else        return "Variveis Compartilhadas";
        case VhdlSpecifier::VFILE:
          if (single) return "Arquivo";
          else        return "Arquivos";
        case VhdlSpecifier::GROUP:
          if (single) return "Grupo";
          else        return "Grupos";
        case VhdlSpecifier::INSTANTIATION:
            if (single) return "Instncia";
            else        return "Instncias";
        case VhdlSpecifier::ALIAS:
          if (single) return "Apelido";
          else        return "Apelidos";
        case VhdlSpecifier::CONFIG:
          if (single) return "Configurao";
          else        return "Configuraes";
        case VhdlSpecifier::MISCELLANEOUS:
          return "Outros"; // Is this correct for VHDL?
        case VhdlSpecifier::UCF_CONST:
          return "Restries";
        default:
          return "Classe";
      }
    }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorBrazilian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 659 of file translator_br.h.
    { return "Aviso"; }
trWriteList()
QCString TranslatorBrazilian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 815 of file translator_br.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" e ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_br.h