Doxygen: src/tagreader.cpp File Reference
tagreader.cpp File Reference
#include "tagreader.h"
#include <map>
#include <functional>
#include <utility>
#include <algorithm>
#include <variant>
#include <assert.h>
#include <stdio.h>
#include <stdarg.h>
#include "xml.h"
#include "entry.h"
#include "doxygen.h"
#include "util.h"
#include "message.h"
#include "defargs.h"
#include "arguments.h"
#include "filedef.h"
#include "filename.h"
#include "section.h"
#include "containers.h"
#include "debug.h"
#include "anchor.h"
#include "moduledef.h"
Classes
class anonymous_namespace{tagreader.cpp}::TagAnchorInfo
Information about an linkable anchor.
class anonymous_namespace{tagreader.cpp}::TagEnumValueInfo
Container for enum values that are scoped within an enum.
class anonymous_namespace{tagreader.cpp}::TagIncludeInfo
Container for include info that can be read from a tagfile.
class anonymous_namespace{tagreader.cpp}::TagMemberInfo
Container for member specific info that can be read from a tagfile.
struct anonymous_namespace{tagreader.cpp}::TagCompoundInfo
Base class for all compound types.
struct anonymous_namespace{tagreader.cpp}::TagClassInfo
Container for class specific info that can be read from a tagfile.
struct anonymous_namespace{tagreader.cpp}::TagConceptInfo
Container for concept specific info that can be read from a tagfile.
struct anonymous_namespace{tagreader.cpp}::TagModuleInfo
Container for module specific info that can be read from a tagfile.
struct anonymous_namespace{tagreader.cpp}::TagNamespaceInfo
Container for namespace specific info that can be read from a tagfile.
struct anonymous_namespace{tagreader.cpp}::TagPackageInfo
Container for package specific info that can be read from a tagfile.
struct anonymous_namespace{tagreader.cpp}::TagFileInfo
Container for file specific info that can be read from a tagfile.
struct anonymous_namespace{tagreader.cpp}::TagGroupInfo
Container for group specific info that can be read from a tagfile.
struct anonymous_namespace{tagreader.cpp}::TagPageInfo
Container for page specific info that can be read from a tagfile.
struct anonymous_namespace{tagreader.cpp}::TagDirInfo
Container for directory specific info that can be read from a tagfile.
class anonymous_namespace{tagreader.cpp}::TagCompoundVariant
Variant class that holds a unique pointer to one of the specific container types.
class anonymous_namespace{tagreader.cpp}::TagFileParser
Tag file parser.
struct anonymous_namespace{tagreader.cpp}::ElementCallbacks
struct anonymous_namespace{tagreader.cpp}::CompoundFactory
Namespaces
namespace anonymous_namespace{tagreader.cpp}
Typedefs
using anonymous_namespace{tagreader.cpp}::TagClassInfoPtr = std::unique_ptr<TagClassInfo>
using anonymous_namespace{tagreader.cpp}::TagConceptInfoPtr = std::unique_ptr<TagConceptInfo>
using anonymous_namespace{tagreader.cpp}::TagModuleInfoPtr = std::unique_ptr<TagModuleInfo>
using anonymous_namespace{tagreader.cpp}::TagNamespaceInfoPtr = std::unique_ptr<TagNamespaceInfo>
using anonymous_namespace{tagreader.cpp}::TagPackageInfoPtr = std::unique_ptr<TagPackageInfo>
using anonymous_namespace{tagreader.cpp}::TagFileInfoPtr = std::unique_ptr<TagFileInfo>
using anonymous_namespace{tagreader.cpp}::TagGroupInfoPtr = std::unique_ptr<TagGroupInfo>
using anonymous_namespace{tagreader.cpp}::TagPageInfoPtr = std::unique_ptr<TagPageInfo>
using anonymous_namespace{tagreader.cpp}::TagDirInfoPtr = std::unique_ptr<TagDirInfo>
Functions
ElementCallbacks::StartCallback anonymous_namespace{tagreader.cpp}::startCb (void(TagFileParser::*fn)(const XMLHandlers::Attributes &))
ElementCallbacks::EndCallback anonymous_namespace{tagreader.cpp}::endCb (void(TagFileParser::*fn)())
void parseTagFile (const std::shared_ptr< Entry > &root, const char *fullName)
Variables
static const std::map< std::string, ElementCallbacks > anonymous_namespace{tagreader.cpp}::g_elementHandlers
static const std::map< std::string, CompoundFactory > anonymous_namespace{tagreader.cpp}::g_compoundFactory
Function Documentation
parseTagFile()
void parseTagFile (const std::shared_ptr< Entry > & root, const char * fullName)
Definition at line 1823 of file tagreader.cpp.
{
  TagFileParser tagFileParser(fullName);
  QCString inputStr = fileToString(fullName);
  XMLHandlers handlers;
  // connect the generic events handlers of the XML parser to the specific handlers of the tagFileParser object
  handlers.startDocument = [&tagFileParser]()                                                              { tagFileParser.startDocument(); };
  handlers.startElement  = [&tagFileParser](const std::string &name,const XMLHandlers::Attributes &attrs)  { tagFileParser.startElement(QCString(name),attrs); };
  handlers.endElement    = [&tagFileParser](const std::string &name)                                       { tagFileParser.endElement(QCString(name)); };
  handlers.characters    = [&tagFileParser](const std::string &chars)                                      { tagFileParser.characters(QCString(chars)); };
  handlers.error         = [&tagFileParser](const std::string &fileName,int lineNr,const std::string &msg) { tagFileParser.error(QCString(fileName),lineNr,QCString(msg)); };
  XMLParser parser(handlers);
  tagFileParser.setDocumentLocator(&parser);
  parser.parse(fullName,inputStr.data(),Debug::isFlagSet(Debug::Lex_xml),
               [&]() { DebugLex::print(Debug::Lex_xml,"Entering","libxml/xml.l",fullName); },
               [&]() { DebugLex::print(Debug::Lex_xml,"Finished", "libxml/xml.l",fullName); }
              );
  tagFileParser.buildLists(root);
  tagFileParser.addIncludes();
  if (Debug::isFlagSet(Debug::Tag))
  {
    tagFileParser.dump();
  }
}
References XMLHandlers::characters, QCString::data(), XMLHandlers::endElement, XMLHandlers::error, fileToString(), Debug::isFlagSet(), Debug::Lex_xml, msg(), XMLParser::parse(), XMLHandlers::startDocument, XMLHandlers::startElement, Debug::Tag, and anonymous_namespace{tagreader.cpp}::TagFileParser::TagFileParser().
Referenced by readTagFile().