Doxygen: src/xmldocvisitor.cpp File Reference
xmldocvisitor.cpp File Reference
#include "xmldocvisitor.h"
#include "docparser.h"
#include "language.h"
#include "doxygen.h"
#include "outputgen.h"
#include "xmlgen.h"
#include "dot.h"
#include "message.h"
#include "util.h"
#include "parserintf.h"
#include "filename.h"
#include "config.h"
#include "htmlentity.h"
#include "emoji.h"
#include "filedef.h"
#include "fileinfo.h"
#include "codefragment.h"
Functions
static void startSimpleSect (TextStream &t, const DocSimpleSect &s)
static void endSimpleSect (TextStream &t, const DocSimpleSect &)
static void visitCaption (XmlDocVisitor &visitor, const DocNodeList &children)
static void visitPreStart (TextStream &t, const char *cmd, bool doCaption, XmlDocVisitor &visitor, const DocNodeList &children, const QCString &name, bool writeType, DocImage::Type type, const QCString &width, const QCString &height, const QCString engine=QCString(), const QCString &alt=QCString(), bool inlineImage=FALSE)
static void visitPostEnd (TextStream &t, const char *cmd)
Function Documentation
endSimpleSect()
static void endSimpleSect (TextStream & t, const DocSimpleSect &) static
Definition at line 80 of file xmldocvisitor.cpp.
{
  t << "</simplesect>\n";
}
Referenced by XmlDocVisitor::operator()(), and XmlDocVisitor::operator()().
startSimpleSect()
static void startSimpleSect (TextStream & t, const DocSimpleSect & s) static
Definition at line 34 of file xmldocvisitor.cpp.
{
  t << "<simplesect kind=\"";
  switch(s.type())
  {
    case DocSimpleSect::See:
      t << "see"; break;
    case DocSimpleSect::Return:
      t << "return"; break;
    case DocSimpleSect::Author:
      t << "author"; break;
    case DocSimpleSect::Authors:
      t << "authors"; break;
    case DocSimpleSect::Version:
      t << "version"; break;
    case DocSimpleSect::Since:
      t << "since"; break;
    case DocSimpleSect::Date:
      t << "date"; break;
    case DocSimpleSect::Note:
      t << "note"; break;
    case DocSimpleSect::Warning:
      t << "warning"; break;
    case DocSimpleSect::Pre:
      t << "pre"; break;
    case DocSimpleSect::Post:
      t << "post"; break;
    case DocSimpleSect::Copyright:
      t << "copyright"; break;
    case DocSimpleSect::Invar:
      t << "invariant"; break;
    case DocSimpleSect::Remark:
      t << "remark"; break;
    case DocSimpleSect::Attention:
      t << "attention"; break;
    case DocSimpleSect::Important:
      t << "important"; break;
    case DocSimpleSect::User:
      t << "par"; break;
    case DocSimpleSect::Rcs:
      t << "rcs"; break;
    case DocSimpleSect::Unknown:  break;
  }
  t << "\">";
}
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, DocSimpleSect::Important, DocSimpleSect::Invar, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, DocSimpleSect::See, DocSimpleSect::Since, DocSimpleSect::type(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, and DocSimpleSect::Warning.
Referenced by XmlDocVisitor::operator()(), and XmlDocVisitor::operator()().
visitCaption()
static void visitCaption (XmlDocVisitor & visitor, const DocNodeList & children) static
Definition at line 85 of file xmldocvisitor.cpp.
{
  for (const auto &n : children)
  {
    std::visit(visitor,n);
  }
}
Referenced by visitPreStart().
visitPostEnd()
static void visitPostEnd (TextStream & t, const char * cmd) static
Definition at line 145 of file xmldocvisitor.cpp.
{
  t << "</" << cmd << ">\n";
}
visitPreStart()
static void visitPreStart (TextStream & t, const char * cmd, bool doCaption, XmlDocVisitor & visitor, const DocNodeList & children, const QCString & name, bool writeType, DocImage::Type type, const QCString & width, const QCString & height, const QCString engine = QCString(), const QCString & alt = QCString(), bool inlineImage = FALSE) static
Definition at line 93 of file xmldocvisitor.cpp.
{
  t << "<" << cmd;
  if (writeType)
  {
    t << " type=\"";
    switch(type)
    {
      case DocImage::Html:    t << "html"; break;
      case DocImage::Latex:   t << "latex"; break;
      case DocImage::Rtf:     t << "rtf"; break;
      case DocImage::DocBook: t << "docbook"; break;
      case DocImage::Xml:     t << "xml"; break;
    }
    t << "\"";
  }
  if (!name.isEmpty())
  {
    t << " name=\"" << convertToXML(name, TRUE) << "\"";
  }
  if (!width.isEmpty())
  {
    t << " width=\"" << convertToXML(width) << "\"";
  }
  if (!height.isEmpty())
  {
    t << " height=\"" << convertToXML(height) << "\"";
  }
  if (!engine.isEmpty())
  {
    t << " engine=\"" << convertToXML(engine) << "\"";
  }
  if (!alt.isEmpty())
  {
    t << " alt=\"" << convertToXML(alt) << "\"";
  }
  if (inlineImage)
  {
    t << " inline=\"yes\"";
  }
  if (doCaption)
  {
    t << " caption=\"";
    visitCaption(visitor, children);
    t << "\"";
  }
  t << ">";
}
References convertToXML(), DocImage::DocBook, FALSE, DocImage::Html, QCString::isEmpty(), DocImage::Latex, DocImage::Rtf, TRUE, visitCaption(), and DocImage::Xml.