Doxygen: DocDotFile Class Reference
DocDotFile Class Reference
Node representing a dot file.
#include <src/docnode.h>
Public Member Functions
DocDotFile (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
bool parse ()
Public Member Functions inherited from DocDiagramFileBase
DocDiagramFileBase (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
QCString name () const
QCString file () const
QCString relPath () const
bool hasCaption () const
QCString width () const
QCString height () const
QCString context () const
QCString srcFile () const
int srcLine () const
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from DocDiagramFileBase
std::unique_ptr< Private > p
Detailed Description
Node representing a dot file.
Definition at line 691 of file docnode.h.
Constructor & Destructor Documentation
DocDotFile()
DocDotFile::DocDotFile (DocParser * parser, DocNodeVariant * parent, const QCString & name, const QCString & context, const QCString & srcFile, int srcLine)
Definition at line 1050 of file docnode.cpp.
                                                            :
  DocDiagramFileBase(parser,parent,name,context,srcFile,srcLine)
{
  p->relPath = parser->context.relPath;
}
References DocDiagramFileBase::context(), DocDiagramFileBase::DocDiagramFileBase(), DocDiagramFileBase::name(), DocDiagramFileBase::p, parent(), DocNode::parser(), DocDiagramFileBase::srcFile(), and DocDiagramFileBase::srcLine().
Member Function Documentation
parse()
bool DocDotFile::parse ()
Definition at line 1057 of file docnode.cpp.
{
  bool ok = false;
  parser()->defaultHandleTitleAndSize(CommandType::CMD_DOTFILE,thisVariant(),children(),p->width,p->height);
  bool ambig = false;
  FileDef *fd = findFileDef(Doxygen::dotFileNameLinkedMap,p->name,ambig);
  if (fd==nullptr && !p->name.endsWith(".dot")) // try with .dot extension as well
  {
    fd = findFileDef(Doxygen::dotFileNameLinkedMap,p->name+".dot",ambig);
  }
  if (fd)
  {
    p->file = fd->absFilePath();
    ok = true;
    if (ambig)
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"included dot file name '%s' is ambiguous.\n"
           "Possible candidates:\n%s",qPrint(p->name),
           qPrint(showFileDefMatches(Doxygen::dotFileNameLinkedMap,p->name))
          );
    }
  }
  else
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"included dot file '%s' is not found "
           "in any of the paths specified via DOTFILE_DIRS!",qPrint(p->name));
  }
  return ok;
}
References FileDef::absFilePath(), DocCompoundNode::children(), CMD_DOTFILE, DocDiagramFileBase::context(), DocParser::defaultHandleTitleAndSize(), Doxygen::dotFileNameLinkedMap, findFileDef(), DocDiagramFileBase::p, DocNode::parser(), qPrint(), showFileDefMatches(), DocNode::thisVariant(), and warn_doc_error.
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp