Doxygen: FortranOutlineParser Class Reference
FortranOutlineParser Class Reference
Fortran language parser using state-based lexical scanning.
#include <src/fortranscanner.h>
Classes
struct Private
Public Member Functions
FortranOutlineParser (FortranFormat format=FortranFormat::Unknown)
~FortranOutlineParser () override
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser) override
Parses a single input file with the goal to build an Entry tree.
bool needsPreprocessing (const QCString &extension) const override
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
void parsePrototype (const QCString &text) override
Callback function called by the comment block scanner.
Public Member Functions inherited from OutlineParserInterface
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Fortran language parser using state-based lexical scanning.
This is the Fortran language parser for doxygen.
Definition at line 27 of file fortranscanner.h.
Constructor & Destructor Documentation
FortranOutlineParser()
FortranOutlineParser::FortranOutlineParser (FortranFormat format = FortranFormat::Unknown)
Definition at line 3343 of file fortranscanner.l.
   : p(std::make_unique<Private>(format))
{
}
References p.
Referenced by FortranOutlineParserFixed::FortranOutlineParserFixed(), and FortranOutlineParserFree::FortranOutlineParserFree().
~FortranOutlineParser()
FortranOutlineParser::~FortranOutlineParser () override
Definition at line 3348 of file fortranscanner.l.
{
  fortranscannerYYlex_destroy(p->yyscanner);
}
References p.
Member Function Documentation
needsPreprocessing()
bool FortranOutlineParser::needsPreprocessing (const QCString & extension) const override virtual
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 3366 of file fortranscanner.l.
{
  return extension!=extension.lower(); // use preprocessor only for upper case extensions
}
References QCString::lower().
parseInput()
void FortranOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) override virtual
Parses a single input file with the goal to build an Entry tree.
Parameters
[in] fileName The full name of the file.
[in] fileBuf The contents of the file (zero terminated).
[in,out] root The root of the tree of Entry *nodes representing the information extracted from the file.
[in] clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
Definition at line 3353 of file fortranscanner.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->thisParser = this;
  DebugLex debugLex(Debug::Lex_fortranscanner, __FILE__, qPrint(fileName));
  ::parseMain(p->yyscanner,fileName,fileBuf,root,p->format);
}
References Debug::Lex_fortranscanner, p, parseMain(), and qPrint().
parsePrototype()
void FortranOutlineParser::parsePrototype (const QCString & text) override virtual
Callback function called by the comment block scanner.
It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Definition at line 3371 of file fortranscanner.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  pushBuffer(p->yyscanner,text);
  yyextra->parsingPrototype = TRUE;
  BEGIN(Prototype);
  fortranscannerYYlex(p->yyscanner);
  yyextra->parsingPrototype = FALSE;
  popBuffer(p->yyscanner);
}
References FALSE, p, popBuffer(), pushBuffer(), and TRUE.
Member Data Documentation
p
std::unique_ptr<Private> FortranOutlineParser::p private
Definition at line 42 of file fortranscanner.h.
Referenced by FortranOutlineParser(), parseInput(), parsePrototype(), and ~FortranOutlineParser().
The documentation for this class was generated from the following files:
src/fortranscanner.h
src/fortranscanner.l