Doxygen: ConfigString Class Reference
ConfigString Class Reference
Class representing a string type option.
#include <src/configimpl.h>
Public Types
enum WidgetType {
String , File , Dir , Image ,
FileAndDir
}
Public Types inherited from ConfigOption
enum OptionType {
O_Info , O_List , O_Enum , O_String ,
O_Int , O_Bool , O_Obsolete , O_Disabled
}
enum { MAX_OPTION_LENGTH = 23 }
Public Member Functions
ConfigString (const char *name, const char *doc)
void setWidgetType (WidgetType w)
WidgetType widgetType () const
void setDefaultValue (const char *v)
QCString * valueRef ()
void writeTemplate (TextStream &t, bool sl, bool) override
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode) override
void writeXMLDoxyfile (TextStream &t) override
void writeXSDDoxyfile (TextStream &t) override
void substEnvVars () override
void init () override
void emptyValueToDefault () override
bool isDefault () override
Public Member Functions inherited from ConfigOption
ConfigOption (OptionType t)
OptionType kind () const
QCString name () const
QCString docs () const
QCString dependsOn () const
void addDependency (const char *dep)
void setEncoding (const QCString &e)
void setUserComment (const QCString &u)
Private Attributes
QCString m_value
QCString m_defValue
WidgetType m_widgetType
Additional Inherited Members
Protected Member Functions inherited from ConfigOption
virtual void convertStrToVal (Config::CompareMode)
void writeBoolValue (TextStream &t, bool v, bool initSpace=true)
void writeIntValue (TextStream &t, int i, bool initSpace=true)
void writeStringValue (TextStream &t, const QCString &s, bool initSpace=true, bool wasQuoted=false)
void writeStringList (TextStream &t, const StringVector &l)
Protected Attributes inherited from ConfigOption
QCString m_spaces
QCString m_name
QCString m_doc
QCString m_dependency
QCString m_encoding
QCString m_userComment
OptionType m_kind
Detailed Description
Class representing a string type option.
Definition at line 186 of file configimpl.h.
Member Enumeration Documentation
WidgetType
enum ConfigString::WidgetType
Enumerator
String
File
Dir
Image
FileAndDir
Definition at line 189 of file configimpl.h.
{ String, File, Dir, Image, FileAndDir };
Constructor & Destructor Documentation
ConfigString()
ConfigString::ConfigString (const char * name, const char * doc) inline
Definition at line 190 of file configimpl.h.
      : ConfigOption(O_String)
    {
      m_name = name;
      m_doc = doc;
      m_widgetType = String;
    }
References ConfigOption::ConfigOption(), ConfigOption::m_doc, ConfigOption::m_name, m_widgetType, ConfigOption::name(), ConfigOption::O_String, and String.
Member Function Documentation
compareDoxyfile()
void ConfigString::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) override virtual
Implements ConfigOption.
Definition at line 512 of file configimpl.l.
{
  if (!isDefault()) writeTemplate(t,TRUE,TRUE);
}
References isDefault(), TRUE, and writeTemplate().
emptyValueToDefault()
void ConfigString::emptyValueToDefault () inline override virtual
Reimplemented from ConfigOption.
Definition at line 207 of file configimpl.h.
{ if (m_value.isEmpty()) m_value=m_defValue; };
References m_defValue, and m_value.
init()
void ConfigString::init () inline override virtual
Reimplemented from ConfigOption.
Definition at line 206 of file configimpl.h.
{ m_value = m_defValue; }
References m_defValue, and m_value.
Referenced by Config::parse().
isDefault()
bool ConfigString::isDefault () inline override virtual
Reimplemented from ConfigOption.
Definition at line 208 of file configimpl.h.
{ return m_value.stripWhiteSpace() == m_defValue.stripWhiteSpace(); }
References m_defValue, and m_value.
Referenced by compareDoxyfile(), and writeXMLDoxyfile().
setDefaultValue()
void ConfigString::setDefaultValue (const char * v) inline
Definition at line 199 of file configimpl.h.
{ m_defValue = v; }
References m_defValue.
setWidgetType()
void ConfigString::setWidgetType (WidgetType w) inline
Definition at line 197 of file configimpl.h.
{ m_widgetType = w; }
References m_widgetType.
substEnvVars()
void ConfigString::substEnvVars () override virtual
Implements ConfigOption.
Definition at line 1514 of file configimpl.l.
{
  substEnvVarsInString(m_value);
}
References m_value, and substEnvVarsInString().
valueRef()
QCString * ConfigString::valueRef () inline
Definition at line 200 of file configimpl.h.
{ return &m_value; }
References m_value.
Referenced by checkEncoding().
widgetType()
WidgetType ConfigString::widgetType () const inline
Definition at line 198 of file configimpl.h.
{ return m_widgetType; }
References m_widgetType.
writeTemplate()
void ConfigString::writeTemplate (TextStream & t, bool sl, bool) override virtual
Implements ConfigOption.
Definition at line 495 of file configimpl.l.
{
  if (!sl)
  {
    t << "\n";
    t << convertToComment(m_doc, m_userComment);
    t << "\n";
  }
  else if (!m_userComment.isEmpty())
  {
    t << convertToComment("", m_userComment);
  }
  t << m_name << m_spaces.left(MAX_OPTION_LENGTH-m_name.length()) << "=";
  writeStringValue(t,m_value);
  t << "\n";
}
References convertToComment(), ConfigOption::m_doc, ConfigOption::m_name, ConfigOption::m_spaces, ConfigOption::m_userComment, m_value, ConfigOption::MAX_OPTION_LENGTH, and ConfigOption::writeStringValue().
Referenced by compareDoxyfile().
writeXMLDoxyfile()
void ConfigString::writeXMLDoxyfile (TextStream & t) override virtual
Implements ConfigOption.
Definition at line 517 of file configimpl.l.
{
  t << "  <option  id='" << m_name << "'";
  t << " default='" << (isDefault() ? "yes" : "no") << "'";
  t << " type='string'";
  t << ">";
  t << "<value>";
  t << "<![CDATA[";
  writeStringValue(t,m_value,false);
  t << "]]>";
  t << "</value>";
  t << "</option>\n";
}
References isDefault(), ConfigOption::m_name, m_value, and ConfigOption::writeStringValue().
writeXSDDoxyfile()
void ConfigString::writeXSDDoxyfile (TextStream & t) override virtual
Implements ConfigOption.
Definition at line 531 of file configimpl.l.
{
  t << "      <xsd:enumeration value=\"" << m_name << "\"/>\n";
}
References ConfigOption::m_name.
Member Data Documentation
m_defValue
QCString ConfigString::m_defValue private
Definition at line 212 of file configimpl.h.
Referenced by emptyValueToDefault(), init(), isDefault(), and setDefaultValue().
m_value
QCString ConfigString::m_value private
Definition at line 211 of file configimpl.h.
Referenced by emptyValueToDefault(), init(), isDefault(), substEnvVars(), valueRef(), writeTemplate(), and writeXMLDoxyfile().
m_widgetType
WidgetType ConfigString::m_widgetType private
Definition at line 213 of file configimpl.h.
Referenced by ConfigString(), setWidgetType(), and widgetType().
The documentation for this class was generated from the following files:
src/configimpl.h
src/configimpl.l