Doxygen: src/filedef.cpp File Reference
filedef.cpp File Reference
#include <unordered_set>
#include "memberlist.h"
#include "classlist.h"
#include "filedef.h"
#include "doxygen.h"
#include "memberdef.h"
#include "classdef.h"
#include "namespacedef.h"
#include "util.h"
#include "language.h"
#include "outputlist.h"
#include "dot.h"
#include "dotincldepgraph.h"
#include "message.h"
#include "docparser.h"
#include "searchindex.h"
#include "htags.h"
#include "parserintf.h"
#include "portable.h"
#include "vhdldocgen.h"
#include "debug.h"
#include "layout.h"
#include "entry.h"
#include "groupdef.h"
#include "filename.h"
#include "membergroup.h"
#include "dirdef.h"
#include "config.h"
#include "clangparser.h"
#include "settings.h"
#include "definitionimpl.h"
#include "conceptdef.h"
#include "moduledef.h"
Classes
class FileDefImpl
Typedefs
using DefinitionLineMap = std::unordered_map<int,const Definition *>
using MemberDefLineMap = std::unordered_map<int,const MemberDef *>
using IncludeInfoMap = std::unordered_map<std::string, const IncludeInfo *>
Functions
QCString includeStatement (SrcLangExt lang, IncludeKind kind)
QCString includeOpen (SrcLangExt lang, IncludeKind kind)
QCString includeClose (SrcLangExt lang, IncludeKind kind)
QCString includeTagFileAttributes (SrcLangExt lang, IncludeKind kind)
std::unique_ptr< FileDef > createFileDef (const QCString &p, const QCString &n, const QCString &ref, const QCString &dn)
static void getAllIncludeFilesRecursively (StringUnorderedSet &filesVisited, const FileDef *fd, StringVector &incFiles)
bool compareFileDefs (const FileDef *fd1, const FileDef *fd2)
FileDef * toFileDef (Definition *d)
const FileDef * toFileDef (const Definition *d)
Typedef Documentation
DefinitionLineMap
using DefinitionLineMap = std::unordered_map<int,const Definition *>
Definition at line 116 of file filedef.cpp.
IncludeInfoMap
using IncludeInfoMap = std::unordered_map<std::string, const IncludeInfo *>
Definition at line 118 of file filedef.cpp.
MemberDefLineMap
using MemberDefLineMap = std::unordered_map<int,const MemberDef *>
Definition at line 117 of file filedef.cpp.
Function Documentation
compareFileDefs()
bool compareFileDefs (const FileDef * fd1, const FileDef * fd2)
Definition at line 1885 of file filedef.cpp.
{
  return qstricmp_sort(fd1->name(),fd2->name()) < 0;
}
References Definition::name(), and qstricmp_sort().
Referenced by DirDefImpl::sort(), and writeFileIndex().
createFileDef()
std::unique_ptr< FileDef > createFileDef (const QCString & p, const QCString & n, const QCString & ref, const QCString & dn)
Definition at line 265 of file filedef.cpp.
{
  return std::make_unique<FileDefImpl>(p,n,ref,dn);
}
Referenced by anonymous_namespace{tagreader.cpp}::TagFileParser::buildLists(), DocbookDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), XmlDocVisitor::operator()(), CCodeParser::parseCode(), FortranCodeParser::parseCode(), LexCodeParser::parseCode(), PythonCodeParser::parseCode(), SQLCodeParser::parseCode(), VHDLCodeParser::parseCode(), XMLCodeParser::parseCode(), CodeFragmentManager::parseCodeFragment(), readDir(), readFileOrDirectory(), and writeGraphInfo().
getAllIncludeFilesRecursively()
static void getAllIncludeFilesRecursively (StringUnorderedSet & filesVisited, const FileDef * fd, StringVector & incFiles) static
Definition at line 1795 of file filedef.cpp.
{
  for (const auto &ii : fd->includeFileList())
  {
    if (ii.fileDef && !ii.fileDef->isReference() &&
        filesVisited.find(ii.fileDef->absFilePath().str())==filesVisited.end())
    {
      //printf("FileDefImpl::addIncludeDependency(%s)\n",qPrint(ii->fileDef->absFilePath()));
      incFiles.push_back(ii.fileDef->absFilePath().str());
      filesVisited.insert(ii.fileDef->absFilePath().str());
      getAllIncludeFilesRecursively(filesVisited,ii.fileDef,incFiles);
    }
  }
}
References getAllIncludeFilesRecursively(), and FileDef::includeFileList().
Referenced by getAllIncludeFilesRecursively().
includeClose()
QCString includeClose (SrcLangExt lang, IncludeKind kind)
Definition at line 86 of file filedef.cpp.
{
  if (lang==SrcLangExt::Java || lang==SrcLangExt::IDL) return ";";
  switch (kind)
  {
    case IncludeKind::ImportLocal:       return "\";";
    case IncludeKind::ImportLocalObjC:   return "\"";
    case IncludeKind::IncludeLocal:      return "\"";
    case IncludeKind::ImportSystem:      return ">;";
    case IncludeKind::ImportSystemObjC:  return ">";
    case IncludeKind::IncludeSystem:     return ">";
    case IncludeKind::ImportModule:      return ";";
  }
  return "";
}
References IDL, ImportLocal, ImportLocalObjC, ImportModule, ImportSystem, ImportSystemObjC, IncludeLocal, IncludeSystem, and Java.
Referenced by ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), and FileDefImpl::writeIncludeFiles().
includeOpen()
QCString includeOpen (SrcLangExt lang, IncludeKind kind)
Definition at line 73 of file filedef.cpp.
{
  if (lang==SrcLangExt::Java || kind==IncludeKind::ImportModule) return "";
  if (kind & IncludeKind_LocalMask)
  {
    return "\"";
  }
  else
  {
    return "<";
  }
}
References ImportModule, IncludeKind_LocalMask, and Java.
Referenced by ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), and FileDefImpl::writeIncludeFiles().
includeStatement()
QCString includeStatement (SrcLangExt lang, IncludeKind kind)
Definition at line 56 of file filedef.cpp.
{
  bool isIDLorJava = lang==SrcLangExt::IDL || lang==SrcLangExt::Java;
  if (isIDLorJava || (kind & IncludeKind_ImportMask))
  {
    return "import ";
  }
  else if (kind & IncludeKind_ObjCMask)
  {
    return "#import ";
  }
  else
  {
    return "#include ";
  }
}
References IDL, IncludeKind_ImportMask, IncludeKind_ObjCMask, and Java.
Referenced by ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), and FileDefImpl::writeIncludeFiles().
includeTagFileAttributes()
QCString includeTagFileAttributes (SrcLangExt lang, IncludeKind kind)
Definition at line 102 of file filedef.cpp.
{
  QCString result;
  bool isIDLorJava = lang==SrcLangExt::IDL || lang==SrcLangExt::Java;
  result.sprintf("local=\"%s\" import=\"%s\" module=\"%s\" objc=\"%s\"",
           (kind & IncludeKind_LocalMask)  ? "yes" : "no",
           (isIDLorJava || (kind & IncludeKind_ImportMask)) ? "yes" : "no",
           (kind==IncludeKind::ImportModule) ? "yes" : "no",
           (kind & IncludeKind_ObjCMask) ? "yes" : "no");
  return result;
}
References IDL, ImportModule, IncludeKind_ImportMask, IncludeKind_LocalMask, IncludeKind_ObjCMask, Java, and QCString::sprintf().
Referenced by FileDefImpl::writeTagFile().
toFileDef() [1/2]
const FileDef * toFileDef (const Definition * d)
Definition at line 1905 of file filedef.cpp.
{
  if (d==nullptr) return nullptr;
  if (d && typeid(*d)==typeid(FileDefImpl))
  {
    return static_cast<const FileDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
toFileDef() [2/2]
FileDef * toFileDef (Definition * d)
Definition at line 1892 of file filedef.cpp.
{
  if (d==nullptr) return nullptr;
  if (d && typeid(*d)==typeid(FileDefImpl))
  {
    return static_cast<FileDef*>(d);
  }
  else
  {
    return nullptr;
  }
}
Referenced by DocSets::addIndexItem(), DocLink::DocLink(), DocRef::DocRef(), findModuleDef(), SymbolResolver::Private::followPath(), generateJSTree(), FTVHelp::Private::generateTree(), DocParser::handleLinkedWord(), NamespaceDefImpl::insertMember(), insertMemberAlias(), SymbolResolver::Private::isAccessibleFrom(), ClassDefImpl::moveTo(), MemberDefImpl::moveTo(), DefinitionImpl::navigationPathAsString(), node2URL(), SearchIndex::setCurrentDoc(), and SearchIndexExternal::setCurrentDoc().