Doxygen: OutlineParserInterface Class Reference
OutlineParserInterface Class Reference abstract
Abstract interface for outline parsers.
#include <src/parserintf.h>
Public Member Functions
virtual void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)=0
Parses a single input file with the goal to build an Entry tree.
virtual bool needsPreprocessing (const QCString &extension) const =0
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
virtual void parsePrototype (const QCString &text)=0
Callback function called by the comment block scanner.
Detailed Description
Abstract interface for outline parsers.
By implementing the methods of this interface one can add a new language parser to doxygen. The parser implementation can make use of the comment block parser to parse the contents of special comment blocks.
Definition at line 41 of file parserintf.h.
Member Function Documentation
needsPreprocessing()
virtual bool OutlineParserInterface::needsPreprocessing (const QCString & extension) const pure virtual
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implemented in COutlineParser, FortranOutlineParser, LexOutlineParser, MarkdownOutlineParser, NullOutlineParser, PythonOutlineParser, and VHDLOutlineParser.
References needsPreprocessing().
Referenced by needsPreprocessing(), and parseFile().
parseInput()
virtual void OutlineParserInterface::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) pure virtual
Parses a single input file with the goal to build an Entry tree.
Parameters
[in] fileName The full name of the file.
[in] fileBuf The contents of the file (zero terminated).
[in,out] root The root of the tree of Entry *nodes representing the information extracted from the file.
[in] clangParser The clang translation unit parser object or nullptr if disabled.
Implemented in COutlineParser, FortranOutlineParser, LexOutlineParser, MarkdownOutlineParser, NullOutlineParser, PythonOutlineParser, and VHDLOutlineParser.
References parseInput().
Referenced by parseFile(), and parseInput().
parsePrototype()
virtual void OutlineParserInterface::parsePrototype (const QCString & text) pure virtual
Callback function called by the comment block scanner.
It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implemented in COutlineParser, FortranOutlineParser, LexOutlineParser, MarkdownOutlineParser, NullOutlineParser, PythonOutlineParser, and VHDLOutlineParser.
References parsePrototype().
Referenced by parsePrototype().
The documentation for this class was generated from the following file:
src/parserintf.h