Doxygen: /home/runner/work/doxygen/doxygen/src/dir.cpp File Reference
dir.cpp File Reference
#include "filesystem.hpp"
#include "dir.h"
Classes
struct DirEntry::Private
struct DirIterator::Private
struct Dir::Private
Macros
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
Functions
bool operator== (const DirIterator &it1, const DirIterator &it2)
bool operator!= (const DirIterator &it1, const DirIterator &it2)
DirIterator begin (DirIterator it) noexcept
DirIterator end (const DirIterator &) noexcept
static void correctPath (std::string &s)
Macro Definition Documentation
NOMINMAX
#define NOMINMAX
Definition at line 16 of file dir.cpp.
WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
Definition at line 17 of file dir.cpp.
Function Documentation
begin()
DirIterator begin (DirIterator it) noexcept
Definition at line 124 of file dir.cpp.
{
  return it;
}
Referenced by FlowChart::buildCommentNodes(), buildDirectories(), MemberLists::get(), ExampleList::inSort(), parseInput(), portable_memmem(), and searchInputFiles().
correctPath()
static void correctPath (std::string & s) static
Definition at line 187 of file dir.cpp.
{
  std::replace( s.begin(), s.end(), '\\', '/' );
}
Referenced by Dir::absPath(), Dir::cleanDirPath(), Dir::currentDirPath(), and Dir::filePath().
end()
DirIterator end (const DirIterator &) noexcept
Definition at line 129 of file dir.cpp.
{
  return DirIterator();
}
Referenced by DocGroup::addDocs(), addMembersToMemberGroup(), addToIndices(), SymbolListContext::alloc(), SymbolGroupContext::alloc(), buildDefineList(), buildDirectories(), DocParser::checkArgumentName(), DocGroup::close(), convertCharEntitiesToUTF8(), endScope(), expandAliasRec(), externalRef(), DefinitionImpl::externalReference(), extractCanonicalType(), extractClassNameFromType(), extractDirection(), extractFromParens(), filterTitle(), findAndRemoveWord(), findClassRelation(), Markdown::findEndOfLine(), findTableColumns(), MemberLists::get(), getResolvedNamespace(), getTemplateArgumentsInName(), DocPara::handleDoxyConfig(), DocPara::handleIncludeOperator(), ExampleList::inSort(), Markdown::isAtxHeader(), Markdown::isBlockCommand(), MemberDefImpl::isBriefSectionVisible(), isFencedCodeBlock(), isLinkRef(), Markdown::isSpecialCommand(), isTableBlock(), linkifyText(), normalizeNonTemplateArgumentsInString(), DocGroup::open(), VhdlDocGen::parseFuncProto(), parseInput(), VhdlDocGen::prepareComment(), SymbolListContext::Private::Private(), Markdown::processBlocks(), Markdown::processCodeSpan(), processConcatOperators(), Markdown::processInline(), Markdown::processQuotations(), QCString::quoted(), readAliases(), removeAnonymousScopes(), TemplateNodeMarkers::render(), replaceColorMarkers(), replaceNamespaceAliases(), resolveModuleProcedures(), searchInputFiles(), split(), stripEmptyLines(), QCString::stripWhiteSpace(), substEnvVarsInString(), substituteTemplateArgumentsInString(), substituteTemplatesInString(), TemplateNodeRange::TemplateNodeRange(), Markdown::writeBlockQuote(), Markdown::writeCodeBlock(), writeMarkerList(), and Markdown::writeTableBlock().
operator!=()
bool operator!= (const DirIterator & it1, const DirIterator & it2)
Definition at line 119 of file dir.cpp.
{
  return it1.p->it!=it2.p->it;
}
operator==()
bool operator== (const DirIterator & it1, const DirIterator & it2)
Definition at line 114 of file dir.cpp.
{
  return it1.p->it == it2.p->it;
}