Doxygen: DefinitionAliasImpl Class Reference
DefinitionAliasImpl Class Reference
#include <definitionimpl.h>
Public Member Functions
DefinitionAliasImpl (Definition *def, const Definition *scope, const Definition *alias)
virtual ~DefinitionAliasImpl ()
void init ()
void deinit ()
const QCString & name () const
QCString qualifiedName () const
Private Member Functions
void updateQualifiedName () const
Private Attributes
Definition * m_def
const Definition * m_scope
QCString m_symbolName
QCString m_qualifiedName
Detailed Description
Definition at line 296 of file definitionimpl.h.
Constructor & Destructor Documentation
DefinitionAliasImpl()
DefinitionAliasImpl::DefinitionAliasImpl (Definition * def, const Definition * scope, const Definition * alias)
Definition at line 1897 of file definition.cpp.
      : m_def(def), m_scope(scope), m_symbolName(alias->_symbolName())
{
}
~DefinitionAliasImpl()
DefinitionAliasImpl::~DefinitionAliasImpl () virtual
Definition at line 1902 of file definition.cpp.
{
}
Member Function Documentation
deinit()
void DefinitionAliasImpl::deinit ()
Definition at line 1912 of file definition.cpp.
{
  removeFromMap(m_symbolName,m_def);
}
References m_def, m_symbolName, and removeFromMap().
Referenced by DefinitionAliasMixin< Base >::deinit().
init()
void DefinitionAliasImpl::init ()
Definition at line 1906 of file definition.cpp.
{
  //printf("%s::addToMap(%s)\n",qPrint(name()),qPrint(alias->name()));
  addToMap(m_symbolName,m_def);
}
References addToMap(), m_def, and m_symbolName.
Referenced by DefinitionAliasMixin< Base >::init().
name()
const QCString & DefinitionAliasImpl::name () const
Definition at line 1942 of file definition.cpp.
{
  updateQualifiedName();
  return m_qualifiedName;
}
References m_qualifiedName, and updateQualifiedName().
Referenced by DefinitionAliasMixin< Base >::name().
qualifiedName()
QCString DefinitionAliasImpl::qualifiedName () const
Definition at line 1936 of file definition.cpp.
{
  updateQualifiedName();
  return m_qualifiedName;
}
References m_qualifiedName, and updateQualifiedName().
Referenced by DefinitionAliasMixin< Base >::qualifiedName().
updateQualifiedName()
void DefinitionAliasImpl::updateQualifiedName () const private
Definition at line 1917 of file definition.cpp.
{
  std::lock_guard<std::recursive_mutex> lock(g_qualifiedNameMutex);
  if (m_qualifiedName.isEmpty())
  {
    //printf("start %s::qualifiedName() localName=%s\n",qPrint(name()),qPrint(m_impl->localName));
    if (m_scope==0)
    {
      m_qualifiedName = m_def->localName();
    }
    else
    {
      m_qualifiedName = m_scope->qualifiedName()+
        getLanguageSpecificSeparator(m_scope->getLanguage())+
        m_def->localName();
    }
  }
}
References g_qualifiedNameMutex, Definition::getLanguage(), getLanguageSpecificSeparator(), QCString::isEmpty(), Definition::localName(), m_def, m_qualifiedName, m_scope, and Definition::qualifiedName().
Referenced by name(), and qualifiedName().
Member Data Documentation
m_def
Definition* DefinitionAliasImpl::m_def private
Definition at line 307 of file definitionimpl.h.
Referenced by deinit(), init(), and updateQualifiedName().
m_qualifiedName
QCString DefinitionAliasImpl::m_qualifiedName mutable private
Definition at line 310 of file definitionimpl.h.
Referenced by name(), qualifiedName(), and updateQualifiedName().
m_scope
const Definition* DefinitionAliasImpl::m_scope private
Definition at line 308 of file definitionimpl.h.
Referenced by updateQualifiedName().
m_symbolName
QCString DefinitionAliasImpl::m_symbolName private
Definition at line 309 of file definitionimpl.h.
Referenced by deinit(), and init().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/definitionimpl.h
/home/runner/work/doxygen/doxygen/src/definition.cpp