Doxygen: PageTreeContext::Private Class Reference
PageTreeContext::Private Class Reference
Public Member Functions
Private (const PageLinkedMap &pages)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
TemplateVariant title () const
int createMaxDepth () const
int createPreferredDepth () const
Private Attributes
TemplateListIntfPtr m_pageTree
CachedItem< int, Private, &Private::createMaxDepth > m_maxDepth
CachedItem< int, Private, &Private::createPreferredDepth > m_preferredDepth
Static Private Attributes
static const PropertyMap< PageTreeContext::Private > s_inst
Detailed Description
Definition at line 6586 of file context.cpp.
Constructor & Destructor Documentation
Private()
PageTreeContext::Private::Private (const PageLinkedMap & pages) inline
Definition at line 6589 of file context.cpp.
    {
      m_pageTree = NestingContext::alloc(0,ContextTreeType::Page,0);
      auto ctx = std::dynamic_pointer_cast<NestingContext>(m_pageTree);
      ClassDefSet visitedClasses;
      // Add pages
      ctx->addPages(pages,TRUE,visitedClasses);
    }
References NestingContext::alloc(), m_pageTree, Page, and TRUE.
Member Function Documentation
createMaxDepth()
int PageTreeContext::Private::createMaxDepth () const inline private
Definition at line 6614 of file context.cpp.
    {
      return computeMaxDepth(m_pageTree);
    }
References computeMaxDepth(), and m_pageTree.
createPreferredDepth()
int PageTreeContext::Private::createPreferredDepth () const inline private
Definition at line 6618 of file context.cpp.
    {
      return computePreferredDepth(m_pageTree,m_maxDepth.get(this));
    }
References computePreferredDepth(), m_maxDepth, and m_pageTree.
fields()
StringVector PageTreeContext::Private::fields () const inline
Definition at line 6600 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fileName()
TemplateVariant PageTreeContext::Private::fileName () const inline private
Definition at line 6605 of file context.cpp.
{ return "pages"; }
get()
TemplateVariant PageTreeContext::Private::get (const QCString & n) const inline
Definition at line 6599 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), and s_inst.
highlight()
TemplateVariant PageTreeContext::Private::highlight () const inline private
Definition at line 6607 of file context.cpp.
{ return "pages"; }
maxDepth()
TemplateVariant PageTreeContext::Private::maxDepth () const inline private
Definition at line 6609 of file context.cpp.
{ return m_maxDepth.get(this); }
References m_maxDepth.
preferredDepth()
TemplateVariant PageTreeContext::Private::preferredDepth () const inline private
Definition at line 6610 of file context.cpp.
{ return m_preferredDepth.get(this); }
References m_preferredDepth.
relPath()
TemplateVariant PageTreeContext::Private::relPath () const inline private
Definition at line 6606 of file context.cpp.
{ return ""; }
subhighlight()
TemplateVariant PageTreeContext::Private::subhighlight () const inline private
Definition at line 6608 of file context.cpp.
{ return ""; }
title()
TemplateVariant PageTreeContext::Private::title () const inline private
Definition at line 6611 of file context.cpp.
{ return theTranslator->trRelatedPages(); }
References theTranslator, and Translator::trRelatedPages().
tree()
TemplateVariant PageTreeContext::Private::tree () const inline private
Definition at line 6604 of file context.cpp.
{ return TemplateVariant(m_pageTree); }
References m_pageTree.
Member Data Documentation
m_maxDepth
CachedItem<int, Private, &Private::createMaxDepth> PageTreeContext::Private::m_maxDepth private
Definition at line 6623 of file context.cpp.
Referenced by createPreferredDepth(), and maxDepth().
m_pageTree
TemplateListIntfPtr PageTreeContext::Private::m_pageTree private
Definition at line 6622 of file context.cpp.
Referenced by createMaxDepth(), createPreferredDepth(), Private(), and tree().
m_preferredDepth
CachedItem<int, Private, &Private::createPreferredDepth> PageTreeContext::Private::m_preferredDepth private
Definition at line 6624 of file context.cpp.
Referenced by preferredDepth().
s_inst
const PropertyMap< PageTreeContext::Private > PageTreeContext::Private::s_inst static private
Initial value:
{
  {  "tree",          &Private::tree },
  {  "fileName",      &Private::fileName },
  {  "relPath",       &Private::relPath },
  {  "highlight",     &Private::highlight },
  {  "subhighlight",  &Private::subhighlight },
  {  "title",         &Private::title },
  {  "preferredDepth",&Private::preferredDepth },
  {  "maxDepth",      &Private::maxDepth }
}
Definition at line 6625 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/context.cpp