Doxygen: TranslatorHungarian Class Reference
TranslatorHungarian Class Reference
#include <src/translator_hu.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString updateNeededMessage () override
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString updateNeededMessage () override
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Private Member Functions
const char * zed (char c)
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) override methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include "translator.h" or "translator_adapter.h" here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 55 of file translator_hu.h.
Member Function Documentation
getLanguageString()
QCString TranslatorHungarian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 107 of file translator_hu.h.
    {
      return "0x40E Hungarian";
    }
idLanguage()
QCString TranslatorHungarian::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 80 of file translator_hu.h.
    { return "hungarian"; }
latexLanguageSupportCommand()
QCString TranslatorHungarian::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 97 of file translator_hu.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[magyar]{babel}\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorHungarian::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1895 of file translator_hu.h.
    { return "Tovbbi rklt tagok"; }
trAll()
QCString TranslatorHungarian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1409 of file translator_hu.h.
    {
      return "sszes";
    }
trAndMore()
QCString TranslatorHungarian::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1873 of file translator_hu.h.
    { return "s "+number+" elemmel tbb..."; }
trAttention()
QCString TranslatorHungarian::trAttention () inline override virtual
Implements Translator.
Definition at line 988 of file translator_hu.h.
    {
      return "Figyelem";
    }
trAuthor()
QCString TranslatorHungarian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1282 of file translator_hu.h.
    {
      return createNoun(first_capital, singular, "szerz", "k");
    }
References Translator::createNoun().
trBug()
QCString TranslatorHungarian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1154 of file translator_hu.h.
    {
      return "Hiba";
    }
trBugList()
QCString TranslatorHungarian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1159 of file translator_hu.h.
    {
      return "Hiba lista";
    }
trCallerGraph()
QCString TranslatorHungarian::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1529 of file translator_hu.h.
    {
      return "A fggvny hv grfja:";
    }
trCallGraph()
QCString TranslatorHungarian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1414 of file translator_hu.h.
    {
      return "A fggvny hvsi grfja:";
    }
trCiteReferences()
QCString TranslatorHungarian::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1849 of file translator_hu.h.
    { return "Bibliogrfia"; }
trClass()
QCString TranslatorHungarian::trClass (bool first_capital, bool) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1217 of file translator_hu.h.
    {
      return createNoun(first_capital, true, "osztly", "");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorHungarian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 542 of file translator_hu.h.
    {
      return QCString("A")+zed(clName[0])+clName+" osztly szrmazsi diagramja:";
    }
References zed().
trClassDocumentation()
QCString TranslatorHungarian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 423 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek dokumentcija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Osztlyok dokumentcija";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorHungarian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1117 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek";
      }
      else
      {
        return "Osztlyok";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorHungarian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 206 of file translator_hu.h.
    { return "Osztlyhierarchia"; }
trClassHierarchyDescription()
QCString TranslatorHungarian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 265 of file translator_hu.h.
    { return "Majdnem (de nem teljesen) betrendbe szedett "
             "leszrmazsi lista:";
    }
trClassMethods()
QCString TranslatorHungarian::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1933 of file translator_hu.h.
    {
      return "Osztly metdusok";
    }
trCode()
QCString TranslatorHungarian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 888 of file translator_hu.h.
    {
      return "forrskd";
    }
trCollaborationDiagram()
QCString TranslatorHungarian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 843 of file translator_hu.h.
    {
      return QCString("A")+zed(clName[0])+clName+" osztly egyttmkdsi diagramja:";
    }
References zed().
trCompoundIndex()
QCString TranslatorHungarian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 396 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezet-mutat";
      }
      else
      {
        return "Osztlymutat";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorHungarian::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1583 of file translator_hu.h.
    { return "Adattpus index"; }
trCompoundList()
QCString TranslatorHungarian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 210 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek";
      }
      else
      {
        return "Osztlylista";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorHungarian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 280 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Az sszes adatszerkezet listja rvid lersokkal:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Az sszes osztly listja rvid lersokkal:";
      }
      else
      {
        return "Az sszes osztly, struktra, uni s interfsz "
               "listja rvid lersokkal:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorHungarian::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1557 of file translator_hu.h.
    { return "Rvid lerssal elltott adattpusok:"; }
trCompoundListFortran()
QCString TranslatorHungarian::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1549 of file translator_hu.h.
    { return "Adattpusok listja"; }
trCompoundMembers()
QCString TranslatorHungarian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 227 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatmezk";
      }
      else
      {
        return "Osztlytagok";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorHungarian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 299 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll)
      {
        result+="dokumentlt ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktra- s unimez";
      }
      else
      {
        result+="osztlytag";
      }
      result+=" listja, valamint hivatkozs ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a megfelel struktra/uni dokumentcira minden meznl:";
        }
        else
        {
          result+="a megfelel osztlydokumentcira minden tagnl:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a struktrkra/unikra, amikhez tartoznak:";
        }
        else
        {
          result+="az osztlyokra, amikhez tartoznak:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorHungarian::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1561 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll)
      {
        result+="dokumentlt ";
      }
      result+="adattpus tagvltoz";
      result+=" hivatkozsokkal elltva ";
      if (!extractAll)
      {
         result+="az egyes adattagok adatszerkezetnek dokumentcijra";
      }
      else
      {
         result+="azokhoz az adattpusokhoz, amelyekhez tartoznak:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorHungarian::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1553 of file translator_hu.h.
    { return "Adatmezk"; }
trCompoundReference()
QCString TranslatorHungarian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 617 of file translator_hu.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" osztly"; break;
        case ClassDef::Struct:     result+=" struktra"; break;
        case ClassDef::Union:      result+=" uni"; break;
        case ClassDef::Interface:  result+=" interfsz"; break;
        case ClassDef::Protocol:   result+=" protokoll"; break;
        case ClassDef::Category:   result+=" kategria"; break;
        case ClassDef::Exception:  result+=" kivtel"; break;
        default: break;
      }
      if (isTemplate) result+="sablon-";
      result+="referencia";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorHungarian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1623 of file translator_hu.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" modul"; break;
        case ClassDef::Struct:     result+=" tpus"; break;
        case ClassDef::Union:      result+=" uni"; break;
        case ClassDef::Interface:  result+=" interfsz"; break;
        case ClassDef::Protocol:   result+=" protokoll"; break;
        case ClassDef::Category:   result+=" kategria"; break;
        case ClassDef::Exception:  result+=" kivtel"; break;
        default: break;
      }
      if (isTemplate) result+=" sablon";
      result+=" hivatkozs";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorHungarian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 518 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatszerkezetek";
      }
      else
      {
        return "Osztlyok";
      }
    }
References Config_getBool.
trConstantGroupReference()
QCString TranslatorHungarian::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1970 of file translator_hu.h.
    {
      QCString result=namespaceName;
      result+=" konstans csoport referencia";
      return result;
    }
trConstantGroups()
QCString TranslatorHungarian::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 1966 of file translator_hu.h.
    { return "Konstans csoportok"; }
trConstructorDocumentation()
QCString TranslatorHungarian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 853 of file translator_hu.h.
    {
      return "Konstruktorok s destruktorok dokumentcija";
    }
trCopyright()
QCString TranslatorHungarian::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1853 of file translator_hu.h.
    { return "Szerzi jog"; }
trDataTypes()
QCString TranslatorHungarian::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1606 of file translator_hu.h.
    { return "Adattpusok"; }
trDate()
QCString TranslatorHungarian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 556 of file translator_hu.h.
    { return "Dtum"; }
trDateTime()
QCString TranslatorHungarian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1802 of file translator_hu.h.
    {
      static const char *days[]   = { "Htf","Kedd","Szerda","Cstrtk","Pntek","Szombat","Vasrnap" };
      static const char *months[] = { "Janur","Februr","Mrcius","prilis","Mjus","Jnius","Jlius","Augusztus","Szeptember","Oktber","November","December" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorHungarian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1822 of file translator_hu.h.
    {
      static const char *days_short[]   = { "H", "K", "Sze", "Cs", "P", "Szo", "V" };
      static const char *days_full[]    = { "htf", "kedd", "szerda", "cstrtk", "pntek", "szombat", "vasrnap" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorHungarian::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1838 of file translator_hu.h.
    {
      static const char *dayPeriod[] = { "de.", "du." };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorHungarian::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 820 of file translator_hu.h.
    {
      return "Definci a(z) @1 fjl @0. sorban.";
    }
trDefinedIn()
QCString TranslatorHungarian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 194 of file translator_hu.h.
    { return "definilja:"; }
trDefinedInSourceFile()
QCString TranslatorHungarian::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 824 of file translator_hu.h.
    {
      return "Definci a(z) @0 fjlban.";
    }
trDefineDocumentation()
QCString TranslatorHungarian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 488 of file translator_hu.h.
    { return "Makrdefincik dokumentcija"; }
trDefines()
QCString TranslatorHungarian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 452 of file translator_hu.h.
    { return "Makrdefincik"; }
trDefineValue()
QCString TranslatorHungarian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1144 of file translator_hu.h.
    {
      return "rtk:";
    }
trDeprecated()
QCString TranslatorHungarian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 833 of file translator_hu.h.
    {
      return "Ellenjavallt";
    }
trDeprecatedList()
QCString TranslatorHungarian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1337 of file translator_hu.h.
    {
      return "Ellenjavallt elemek listja";
    }
trDetailedDescription()
QCString TranslatorHungarian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 123 of file translator_hu.h.
    { return "Rszletes lers"; }
trDetailLevel()
QCString TranslatorHungarian::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1865 of file translator_hu.h.
    { return "rszletessgi szint"; }
trDetails()
QCString TranslatorHungarian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 127 of file translator_hu.h.
    { return "Rszletek"; }
trDir()
QCString TranslatorHungarian::trDir (bool first_capital, bool) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1504 of file translator_hu.h.
    {
      return createNoun(first_capital, true, "knyvtr", "");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorHungarian::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1857 of file translator_hu.h.
    { return QCString("Knyvtr fggsgi grf a(z) ")+name+"-knyvtrhoz:"; }
trDirDocumentation()
QCString TranslatorHungarian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1486 of file translator_hu.h.
    { return "Knyvtrak dokumentcija"; }
trDirectories()
QCString TranslatorHungarian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1492 of file translator_hu.h.
    { return "Knyvtrak"; }
trDirIndex()
QCString TranslatorHungarian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1480 of file translator_hu.h.
    { return "Knyvtrhierarchia"; }
trDirReference()
QCString TranslatorHungarian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1498 of file translator_hu.h.
    { QCString result=dirName; result+=" knyvtrreferencia"; return result; }
trDirRelation()
QCString TranslatorHungarian::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1741 of file translator_hu.h.
    {
      return QCString(name)+" kapcsolat";
    }
trDocumentation()
QCString TranslatorHungarian::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 378 of file translator_hu.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentci"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorHungarian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 464 of file translator_hu.h.
    { return "Enumercik"; }
trEnumerationTypeDocumentation()
QCString TranslatorHungarian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 500 of file translator_hu.h.
    { return "Enumercik dokumentcija"; }
trEnumerationValueDocumentation()
QCString TranslatorHungarian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1537 of file translator_hu.h.
    { return "Enumercis-rtk dokumentci"; }
trEnumerationValues()
QCString TranslatorHungarian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 482 of file translator_hu.h.
    { return "Enumerci-rtkek"; }
trEnumGeneratedFromFiles()
QCString TranslatorHungarian::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1877 of file translator_hu.h.
    { QCString result = "A dokumentci ehhez az enum-hoz a kvetkez fjl";
      if (!single) result+="ok";
      result+=" alapjn kszlt:";
      return result;
    }
trEnumName()
QCString TranslatorHungarian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 186 of file translator_hu.h.
    { return "enum"; }
trEnumReference()
QCString TranslatorHungarian::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1885 of file translator_hu.h.
    { return QCString(name)+" felsorol referencia"; }
trEnumValue()
QCString TranslatorHungarian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 190 of file translator_hu.h.
    { return "enum-rtk"; }
trEventDocumentation()
QCString TranslatorHungarian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1354 of file translator_hu.h.
    {
      return "Esemnyek dokumentcija";
    }
trEvents()
QCString TranslatorHungarian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1349 of file translator_hu.h.
    {
      return "Esemnyek";
    }
trExamples()
QCString TranslatorHungarian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 257 of file translator_hu.h.
    { return "Pldk"; }
trExamplesDescription()
QCString TranslatorHungarian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 363 of file translator_hu.h.
    { return "A pldk listja:"; }
trExceptions()
QCString TranslatorHungarian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 572 of file translator_hu.h.
    { return "Kivtelek"; }
trExtendsClass()
QCString TranslatorHungarian::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1925 of file translator_hu.h.
    {
      return "@0 kiterjesztett osztly.";
    }
trFile()
QCString TranslatorHungarian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1226 of file translator_hu.h.
    {
      return createNoun(first_capital, singular, "fjl", "ok");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorHungarian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 442 of file translator_hu.h.
    { return "Fjlok dokumentcija"; }
trFileIn()
QCString TranslatorHungarian::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1778 of file translator_hu.h.
    {
      return "Fjl a(z) "+name+" knyvtrban";
    }
trFileIndex()
QCString TranslatorHungarian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 411 of file translator_hu.h.
    { return "Fjlmutat"; }
trFileList()
QCString TranslatorHungarian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 223 of file translator_hu.h.
    { return "Fjllista"; }
trFileListDescription()
QCString TranslatorHungarian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 271 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="fjl listja rvid lersokkal:";
      return result;
    }
trFileMembers()
QCString TranslatorHungarian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 240 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globlis elemek";
      }
      else
      {
        return "Fjlelemek";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorHungarian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 341 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="fggvny, vltoz, makrdefinci, enumerci s tpusdefinci";
      }
      else
      {
        result+="fjlelem";
      }
      result+=" listja, valamint hivatkozs ";
      if (extractAll)
        result+="a fjlokra, amikhez tartoznak:";
      else
        result+="a dokumentcira:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorHungarian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 639 of file translator_hu.h.
    {
      QCString result=fileName;
      result+=" fjlreferencia";
      return result;
    }
trFriends()
QCString TranslatorHungarian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 599 of file translator_hu.h.
    { return "Bartok"; }
trFunctionDocumentation()
QCString TranslatorHungarian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 506 of file translator_hu.h.
    { return "Fggvnyek dokumentcija"; }
trFunctions()
QCString TranslatorHungarian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 470 of file translator_hu.h.
    { return "Fggvnyek"; }
trGeneratedAt()
QCString TranslatorHungarian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 533 of file translator_hu.h.
    {
      QCString result="";
      if (!projName.isEmpty()) result+="Projekt: "+projName;
      result+=" Kszlt: "+date+" Ksztette: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorHungarian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 178 of file translator_hu.h.
    { QCString result="Ezt a dokumentcit a Doxygen ksztette ";
      if (!s.isEmpty()) result+=QCString(" a") + zed(s[0])+s+" projekthez";
      result+=" a forrskdbl.";
      return result;
    }
References QCString::isEmpty(), and zed().
trGeneratedBy()
QCString TranslatorHungarian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 576 of file translator_hu.h.
    { return "Ksztette"; }
trGeneratedFromFiles()
QCString TranslatorHungarian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 776 of file translator_hu.h.
    { // single is true implies a single file
      QCString result="Ez a dokumentci ";
      switch(compType)
      {
        case ClassDef::Class:      result+="az osztlyrl"; break;
        case ClassDef::Struct:     result+="a struktrrl"; break;
        case ClassDef::Union:      result+="az unirl"; break;
        case ClassDef::Interface:  result+="az interfszrl"; break;
        case ClassDef::Protocol:   result+="a protokollrl"; break;
        case ClassDef::Category:   result+="a kategrirl"; break;
        case ClassDef::Exception:  result+="a kivtelrl"; break;
        default: break;
      }
      result+=" a kvetkez fjl";
      if (!single) result+="ok";
      result+=" alapjn kszlt:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorHungarian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1690 of file translator_hu.h.
    {
      // single is true implies a single file
      QCString result="Ez a dokumentci ";
      switch(compType)
      {
        case ClassDef::Class:      result+="a modulrl"; break;
        case ClassDef::Struct:     result+="a tpusrl"; break;
        case ClassDef::Union:      result+="az unirl"; break;
        case ClassDef::Interface:  result+="az interfszrl"; break;
        case ClassDef::Protocol:   result+="a protokollrl"; break;
        case ClassDef::Category:   result+="a kategrirl"; break;
        case ClassDef::Exception:  result+="a kivtelrl"; break;
        default: break;
      }
      result+=" a kvetkez fjl";
      if (!single) result+="ok";
      result+=" alapjn kszlt:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorHungarian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1271 of file translator_hu.h.
    {
      return createNoun(first_capital, singular, "globlis elem", "ek");
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorHungarian::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1753 of file translator_hu.h.
    {
      return "Globlis nvtr";
    }
trGotoDocumentation()
QCString TranslatorHungarian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 863 of file translator_hu.h.
    {
      return "Ugrs a fjl dokumentcijhoz.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorHungarian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 896 of file translator_hu.h.
    {
      return "Ugrs az osztlyhierarchia-brhoz";
    }
trGotoSourceCode()
QCString TranslatorHungarian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 858 of file translator_hu.h.
    {
      return "Ugrs a fjl forrskdjhoz.";
    }
trGotoTextualHierarchy()
QCString TranslatorHungarian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 900 of file translator_hu.h.
    {
      return "Ugrs az szveges osztlyhierarchihoz";
    }
trGraphicalHierarchy()
QCString TranslatorHungarian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 892 of file translator_hu.h.
    {
      return "Osztlyhierarchia-bra";
    }
trGroup()
QCString TranslatorHungarian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1244 of file translator_hu.h.
    {
      return createNoun(first_capital, singular, "modul", "ok");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorHungarian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 390 of file translator_hu.h.
    { return "Hierarchikus mutat"; }
trImplementedFromList()
QCString TranslatorHungarian::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1305 of file translator_hu.h.
    {
      return "Megvalstja a kvetkezket: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorHungarian::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1313 of file translator_hu.h.
    {
      return "Megvalstjk a kvetkezk: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph()
QCString TranslatorHungarian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 992 of file translator_hu.h.
    {
      return "Ez az bra azt mutatja, hogy mely fjlok gyazzk be "
             "kzvetve vagy kzvetlenl ezt a fjlt:";
    }
trInclDepGraph()
QCString TranslatorHungarian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 848 of file translator_hu.h.
    {
      return QCString("A")+zed(fName[0])+fName+" defincis fjl fggsi grfja:";
    }
References zed().
trIncludesFileIn()
QCString TranslatorHungarian::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1787 of file translator_hu.h.
    {
      return "Tartalmazott fjl a(z) "+name+" knyvtrban";
    }
trIncludingInheritedMembers()
QCString TranslatorHungarian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 172 of file translator_hu.h.
    { return " osztly tagjainak teljes listja, az rklt tagokkal egytt."; }
trInheritedByList()
QCString TranslatorHungarian::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 710 of file translator_hu.h.
    {
      return "Leszrmazottak: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorHungarian::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1889 of file translator_hu.h.
    { return QCString(members)+" a(z) "+what+" osztlybl szrmaznak"; }
trInheritsList()
QCString TranslatorHungarian::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 702 of file translator_hu.h.
    {
      return "sk: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorHungarian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 883 of file translator_hu.h.
    {
      return "Kezd rtk:";
    }
trInstanceMethods()
QCString TranslatorHungarian::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1941 of file translator_hu.h.
    {
      return "Pldny metdusok";
    }
trInterfaces()
QCString TranslatorHungarian::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1958 of file translator_hu.h.
    { return "Exportlt interfszek"; }
trInvariant()
QCString TranslatorHungarian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 878 of file translator_hu.h.
    {
      return "Invarins";
    }
trISOLang()
QCString TranslatorHungarian::trISOLang () inline override virtual
Implements Translator.
Definition at line 103 of file translator_hu.h.
    {
      return "hu";
    }
trLegend()
QCString TranslatorHungarian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1077 of file translator_hu.h.
    {
      return "Jelmagyarzat";
    }
trLegendDocs()
QCString TranslatorHungarian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1014 of file translator_hu.h.
    {
      return
        "Ez az oldal elmagyarzza hogyan kell rtelmezni a "
        "doxygen ltal ksztett brkat.<p>\n"
        "Vegyk a kvetkez pldt:\n"
        "\\code\n"
        "/*! Vgs miatt nem lthat osztly */\n"
        "class Invisible { };\n\n"
        "/*! Levgott osztly, szrmazsa rejtett */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Doxygen kommentekkel nem dokumentlt osztly */\n"
        "class Undocumented { };\n\n"
        "/*! Publikus szrmaztatsal levezetett osztly */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Egy sablonosztly */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Vdett szrmaztatsal levezetett osztly */\n"
        "class ProtectedBase { };\n\n"
        "/*! Privt szrmaztatsal levezetett osztly */\n"
        "class PrivateBase { };\n\n"
        "/*! Osztly, melyet a szrmaztatott osztly hasznl */\n"
        "class Used { };\n\n"
        "/*! Osztly, mely tbb msiknak leszrmazottja */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Az eredmny a kvetkez bra lesz:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "A fenti brn lev dobozok jelentse a kvetkez:\n"
        "<ul>\n"
        "<li>Kitlttt fekete doboz jelzi azt az osztlyt vagy struktrt,"
        "amelyrl az bra szl.</li>\n"
        "<li>Fekete keret jelzi a dokumentlt osztlyokat s struktrkat.</li>\n"
        "<li>Szrke keret jelzi a nem dokumentlt osztlyokat s struktrkat.</li>\n"
        "<li>Piros keret jelzi azokat az osztlyokat s struktrkat, amelyeknl vgs miatt nem lthat "
        "az sszes leszrmaztatsi kapcsolat. Egy bra vgsra kerl, ha nem fr bele "
        "a megadott tartomnyba.</li>\n"
        "</ul>\n"
        "<p>\n"
        "A nyilak jelentse a kvetkez:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Sttkk nyl jelzi a publikus szrmaztats "
        "kapcsolatt kt osztly kztt.</li>\n"
        "<li>Sttzld nyl jelzi a vdett szrmaztatst.</li>\n"
        "<li>Sttvrs nyl jelzi a privt szrmaztatst.</li>\n"
        "<li>Lila szaggatott nyl jelzi, ha az osztly egy msikat hasznl vagy tartalmaz. "
        "A nyl felirata jelzi a vltoz(k) nevt, amelyeken keresztl a msik osztly kapcsoldik.</li>\n"
        "<li>Srga szaggatott nyl jelzi a kapcsolatot a sablonpldny s a pldnyostott "
        "osztlysablon kztt. A nyl felirata jelzi a plny sablonparamtereit.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorHungarian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 1007 of file translator_hu.h.
    {
      return "Jelmagyarzat";
    }
trListOfAllMembers()
QCString TranslatorHungarian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 160 of file translator_hu.h.
    { return "A tagok teljes listja"; }
trLoading()
QCString TranslatorHungarian::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1747 of file translator_hu.h.
    {
      return "Betlts...";
    }
trMainPage()
QCString TranslatorHungarian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 807 of file translator_hu.h.
    { return "Foldal"; }
trMember()
QCString TranslatorHungarian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1262 of file translator_hu.h.
    {
      return createNoun(first_capital, singular, "tag", "ok");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorHungarian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 143 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatmezk dokumentcija";
      }
      else
      {
        return "Adattagok dokumentcija";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorHungarian::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 135 of file translator_hu.h.
    { return "Enumerci-tagok dokumentcija"; }
trMemberFunctionDocumentation()
QCString TranslatorHungarian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 139 of file translator_hu.h.
    { return "Tagfggvnyek dokumentcija"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorHungarian::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1545 of file translator_hu.h.
    { return "Tagfggvny/Alprogram dokumentci"; }
trMemberList()
QCString TranslatorHungarian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 164 of file translator_hu.h.
    { return "Taglista"; }
trMemberTypedefDocumentation()
QCString TranslatorHungarian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 131 of file translator_hu.h.
    { return "Tpusdefinci-tagok dokumentcija"; }
trMethodDocumentation()
QCString TranslatorHungarian::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1948 of file translator_hu.h.
    {
      return "Metdus dokumentci";
    }
trModule()
QCString TranslatorHungarian::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1682 of file translator_hu.h.
    {
      return createNoun(first_capital, singular, "modul", "s");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorHungarian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 417 of file translator_hu.h.
    { return "Modulok dokumentcija"; }
trModuleIndex()
QCString TranslatorHungarian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 384 of file translator_hu.h.
    { return "Modulmutat"; }
trModuleReference()
QCString TranslatorHungarian::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1644 of file translator_hu.h.
    {
      QCString result=namespaceName;
      result+=" modul hivatkozs";
      return result;
    }
trModules()
QCString TranslatorHungarian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 202 of file translator_hu.h.
    { return "Modulok"; }
trModulesDescription()
QCString TranslatorHungarian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 371 of file translator_hu.h.
    { return "A modulok listja:"; }
trModulesIndex()
QCString TranslatorHungarian::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1675 of file translator_hu.h.
    { return "Modulok indexe"; }
trModulesList()
QCString TranslatorHungarian::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1610 of file translator_hu.h.
    { return "Modulok listja"; }
trModulesListDescription()
QCString TranslatorHungarian::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1614 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="rvid lerssal elltott modul:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorHungarian::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1656 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="modul adattagja hivatkozsokkal elltva ";
      if (extractAll)
      {
        result+="az egyes adattagok moduljainak dokumentcijra:";
      }
      else
      {
        result+="azokhoz a modulokhoz, amelyekhez tartoznak:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorHungarian::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1652 of file translator_hu.h.
    { return "Modul adattagok"; }
trMonth()
QCString TranslatorHungarian::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1830 of file translator_hu.h.
    {
      static const char *months_short[] = { "jan.", "febr.", "mrc.", "pr.", "mj.", "jn.", "jl.", "aug.", "szept.", "okt.", "nov.", "dec." };
      static const char *months_full[]  = { "janur", "februr", "mrcius", "prilis", "mjus", "jnius", "jlius", "augusztus", "szeptember", "oktber", "november", "december" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorHungarian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 156 of file translator_hu.h.
    { return "Rszletek..."; }
trNamespace()
QCString TranslatorHungarian::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1235 of file translator_hu.h.
    {
      return createNoun(first_capital, singular, "nvt", "erek", "r");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorHungarian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 756 of file translator_hu.h.
    { return "Nvterek dokumentcija"; }
trNamespaceIndex()
QCString TranslatorHungarian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 750 of file translator_hu.h.
    { return "Nvtrmutat"; }
trNamespaceList()
QCString TranslatorHungarian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 584 of file translator_hu.h.
    { return "Nvtrlista"; }
trNamespaceListDescription()
QCString TranslatorHungarian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 588 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="nvtr listja rvid lersokkal:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorHungarian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 736 of file translator_hu.h.
    {
      QCString result="Az sszes ";
      if (!extractAll) result+="dokumentlt ";
      result+="nvtr tagjainak listja, valamint hivatkozs ";
      if (extractAll)
        result+=" a megfelel nvtr dokumentcira minden tagnl:";
      else
        result+=" a nvterekre, amelynek tagjai:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorHungarian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 732 of file translator_hu.h.
    { return "Nvtrtagok"; }
trNamespaceReference()
QCString TranslatorHungarian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 647 of file translator_hu.h.
    {
      QCString result=namespaceName;
      result+=" nvtr-referencia";
      return result;
    }
trNamespaces()
QCString TranslatorHungarian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 766 of file translator_hu.h.
    { return "Nvterek"; }
trNoMatches()
QCString TranslatorHungarian::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1765 of file translator_hu.h.
    {
      return "Nincs egyezs";
    }
trNote()
QCString TranslatorHungarian::trNote () inline override virtual
Implements Translator.
Definition at line 913 of file translator_hu.h.
    {
      return "Megjegyzs";
    }
trOverloadText()
QCString TranslatorHungarian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1516 of file translator_hu.h.
    {
       return "Ez egy tlterhelt tagfggvny, "
              "a knyelem rdekben. A fenti fggvnytl csak abban klnbzik, "
              "hogy milyen argumentumokat fogad el.";
    }
trPackage()
QCString TranslatorHungarian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1129 of file translator_hu.h.
    {
      return name+" csomag";
    }
trPackageAttribs()
QCString TranslatorHungarian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1390 of file translator_hu.h.
    {
      return "Csomag attribtumok";
    }
trPackageFunctions()
QCString TranslatorHungarian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1372 of file translator_hu.h.
    {
      return "Csomag fggvnyek";
    }
trPackageListDescription()
QCString TranslatorHungarian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1134 of file translator_hu.h.
    {
      return "A csomagok rvid lersai (ha lteznek):";
    }
trPackageMembers()
QCString TranslatorHungarian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1376 of file translator_hu.h.
    {
      return "Csomag tagok";
    }
trPackages()
QCString TranslatorHungarian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1139 of file translator_hu.h.
    {
      return "Csomagok";
    }
trPackageTypes()
QCString TranslatorHungarian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1365 of file translator_hu.h.
    {
      return "Csomag tpusok";
    }
trPage()
QCString TranslatorHungarian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1253 of file translator_hu.h.
    {
      return createNoun(first_capital, singular, "oldal", "ak");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorHungarian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 813 of file translator_hu.h.
    { return "o."; }
trPageIndex()
QCString TranslatorHungarian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 904 of file translator_hu.h.
    {
      return "Oldalmutat";
    }
trPanelSynchronisationTooltip()
QCString TranslatorHungarian::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1906 of file translator_hu.h.
    {
      QCString opt = enable ? "engedlyez" : "letilt";
      return "Kattintson a(z) "+opt+" panel synchronisation";
    }
trParameters()
QCString TranslatorHungarian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 568 of file translator_hu.h.
    { return "Paramterek"; }
trPostcondition()
QCString TranslatorHungarian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 873 of file translator_hu.h.
    {
      return "Utfelttel";
    }
trPrecondition()
QCString TranslatorHungarian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 868 of file translator_hu.h.
    {
      return "Elfelttel";
    }
trPrivateAttribs()
QCString TranslatorHungarian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 952 of file translator_hu.h.
    {
      return "Privt attribtumok";
    }
trPrivateMembers()
QCString TranslatorHungarian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 668 of file translator_hu.h.
    { return "Privt tagfggvnyek"; }
trPrivateSlots()
QCString TranslatorHungarian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 670 of file translator_hu.h.
    { return "Privt rsek"; }
trPrivateTypes()
QCString TranslatorHungarian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 948 of file translator_hu.h.
    {
      return "Privt tpusok";
    }
trProperties()
QCString TranslatorHungarian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1102 of file translator_hu.h.
    {
      return "Tulajdonsgok";
    }
trPropertyDocumentation()
QCString TranslatorHungarian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1107 of file translator_hu.h.
    {
      return "Tulajdonsgok dokumentcijka";
    }
trProtectedAttribs()
QCString TranslatorHungarian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 940 of file translator_hu.h.
    {
      return "Vdett attribtumok";
    }
trProtectedMembers()
QCString TranslatorHungarian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 662 of file translator_hu.h.
    { return "Vdett tagfggvnyek"; }
trProtectedSlots()
QCString TranslatorHungarian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 664 of file translator_hu.h.
    { return "Vdett rsek"; }
trProtectedTypes()
QCString TranslatorHungarian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 936 of file translator_hu.h.
    {
      return "Vdett tpusok";
    }
trProvidedByCategory()
QCString TranslatorHungarian::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1916 of file translator_hu.h.
    {
      return "@0 kategria szerint.";
    }
trPublicAttribs()
QCString TranslatorHungarian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 921 of file translator_hu.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Adatmezk";
      }
      else
      {
        return "Publikus attribtumok";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorHungarian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 654 of file translator_hu.h.
    { return "Publikus tagfggvnyek"; }
trPublicSlots()
QCString TranslatorHungarian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 656 of file translator_hu.h.
    { return "Publikus rsek"; }
trPublicTypes()
QCString TranslatorHungarian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 917 of file translator_hu.h.
    {
      return "Publikus tpusok";
    }
trReferencedBy()
QCString TranslatorHungarian::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 980 of file translator_hu.h.
    {
      return "Hivatkozsok:";
    }
trReferenceManual()
QCString TranslatorHungarian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 446 of file translator_hu.h.
    { return "Referencia kziknyv"; }
trReferences()
QCString TranslatorHungarian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1293 of file translator_hu.h.
    {
      return "Hivatkozsok";
    }
trReimplementedFromList()
QCString TranslatorHungarian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 718 of file translator_hu.h.
    {
      return "jraimplementlt sk: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorHungarian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 726 of file translator_hu.h.
    {
      return "jraimplementl leszrmazottak: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorHungarian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 609 of file translator_hu.h.
    { return "Bart s kapcsold fggvnyek dokumentcija"; }
trRelatedFunctions()
QCString TranslatorHungarian::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 115 of file translator_hu.h.
    { return "Kapcsold fggvnyek"; }
trRelatedPages()
QCString TranslatorHungarian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 253 of file translator_hu.h.
    { return "Kapcsold lapok"; }
trRelatedPagesDescription()
QCString TranslatorHungarian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 367 of file translator_hu.h.
    { return "A kapcsold dokumentcik listja:"; }
trRelatedSubscript()
QCString TranslatorHungarian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 119 of file translator_hu.h.
    { return "(Figyelem! Ezek a fggvnyek nem tagjai az osztlynak!)"; }
trRemarks()
QCString TranslatorHungarian::trRemarks () inline override virtual
Implements Translator.
Definition at line 984 of file translator_hu.h.
    {
      return "Megjegyzsek";
    }
trReturns()
QCString TranslatorHungarian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 560 of file translator_hu.h.
    { return "Visszatrsi rtk"; }
trReturnValues()
QCString TranslatorHungarian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 802 of file translator_hu.h.
    { return "Visszatrsi rtkek"; }
trRTFansicp()
QCString TranslatorHungarian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1193 of file translator_hu.h.
    {
      return "1250";
    }
trRTFCharSet()
QCString TranslatorHungarian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1202 of file translator_hu.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorHungarian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1208 of file translator_hu.h.
    {
      return "Trgymutat";
    }
trRTFTableOfContents()
QCString TranslatorHungarian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1325 of file translator_hu.h.
    {
      return "Tartalomjegyzk";
    }
trSearch()
QCString TranslatorHungarian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 261 of file translator_hu.h.
    { return "Keress"; }
trSearching()
QCString TranslatorHungarian::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1759 of file translator_hu.h.
    {
      return "Keress...";
    }
trSearchMatches()
QCString TranslatorHungarian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1457 of file translator_hu.h.
    {
      return "Tallatok:";
    }
trSearchResults()
QCString TranslatorHungarian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1438 of file translator_hu.h.
    {
      if (numDocuments==0)
      {
        return "Sajnos egy dokumentum sem felelt meg a keressi feltteleknek.";
      }
      else if (numDocuments==1)
      {
        return "<b>1</b> dokumentum felelt meg a keressi feltteleknek.";
      }
      else
      {
        return "<b>$num</b> dokumentum felelt meg a keressi feltteleknek."
               "Elsnek a legjobb tallatok vannak feltntetve.";
      }
    }
trSearchResultsTitle()
QCString TranslatorHungarian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1426 of file translator_hu.h.
    {
      return "A keress eredmnye";
    }
trSeeAlso()
QCString TranslatorHungarian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 564 of file translator_hu.h.
    { return "Lsd mg"; }
trServiceGeneratedFromFiles()
QCString TranslatorHungarian::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 1991 of file translator_hu.h.
    {
      // single is true implies a single file
      QCString result="A szolgltats dokumentcija "
                                "a kvetkez fjl";
      if (single) result+="bl"; else result+="okbl";
      result+="lett ltrehozva:";
      return result;
    }
trServiceReference()
QCString TranslatorHungarian::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 1977 of file translator_hu.h.
    {
      QCString result=sName;
      result+=" szolgltats referencia";
      return result;
    }
trServices()
QCString TranslatorHungarian::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1962 of file translator_hu.h.
    { return "Mellkelt szolgltatsok"; }
trSignals()
QCString TranslatorHungarian::trSignals () inline override virtual
Implements Translator.
Definition at line 658 of file translator_hu.h.
    { return "Szignlok"; }
trSince()
QCString TranslatorHungarian::trSince () inline override virtual
Implements Translator.
Definition at line 997 of file translator_hu.h.
    {
      return "Elszr bevezetve";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorHungarian::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 2001 of file translator_hu.h.
    {
      // single is true implies a single file
      QCString result="Az egyke pldny dokomentcija "
                                "a kvetkez fjl";
      if (single) result+="bl"; else result+="okbl";
      result+="lett ltrehozva:";
      return result;
    }
trSingletonReference()
QCString TranslatorHungarian::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 1984 of file translator_hu.h.
    {
      QCString result=sName;
      result+=" egyke pldny referencia";
      return result;
    }
trSourceFile()
QCString TranslatorHungarian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1468 of file translator_hu.h.
    {
      return filename + " Forrsfjl";
    }
trStaticPackageAttribs()
QCString TranslatorHungarian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1397 of file translator_hu.h.
    {
      return "Statikus csomag attribtumok";
    }
trStaticPackageFunctions()
QCString TranslatorHungarian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1383 of file translator_hu.h.
    {
      return "Statikus csomag fggvnyek";
    }
trStaticPrivateAttribs()
QCString TranslatorHungarian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 956 of file translator_hu.h.
    {
      return "Statikus privt attribtumok";
    }
trStaticPrivateMembers()
QCString TranslatorHungarian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 672 of file translator_hu.h.
    { return "Statikus privt tagfggvnyek"; }
trStaticProtectedAttribs()
QCString TranslatorHungarian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 944 of file translator_hu.h.
    {
      return "Statikus vdett attribtumok";
    }
trStaticProtectedMembers()
QCString TranslatorHungarian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 666 of file translator_hu.h.
    { return "Statikus vdett tagfggvnyek"; }
trStaticPublicAttribs()
QCString TranslatorHungarian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 932 of file translator_hu.h.
    {
      return "Statikus publikus attribtumok";
    }
trStaticPublicMembers()
QCString TranslatorHungarian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 660 of file translator_hu.h.
    { return "Statikus publikus tagfggvnyek"; }
trSubprogram()
QCString TranslatorHungarian::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1725 of file translator_hu.h.
    {
      return createNoun(first_capital, singular, "alprogram", "ok");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorHungarian::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1600 of file translator_hu.h.
    { return "Fggvny/Alprogram dokumentci"; }
trSubprograms()
QCString TranslatorHungarian::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1594 of file translator_hu.h.
    { return "Fggvnyek/Alprogramok"; }
trTemplateParameters()
QCString TranslatorHungarian::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1869 of file translator_hu.h.
    { return "Sablon paramterek"; }
trTest()
QCString TranslatorHungarian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1087 of file translator_hu.h.
    {
      return "Teszt";
    }
trTestList()
QCString TranslatorHungarian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1092 of file translator_hu.h.
    {
      return "Tesztlista";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorHungarian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 168 of file translator_hu.h.
    { return "A(z)"; }
trTodo()
QCString TranslatorHungarian::trTodo () inline override virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 966 of file translator_hu.h.
    {
      return "Tennival";
    }
trTodoList()
QCString TranslatorHungarian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 971 of file translator_hu.h.
    {
      return "Tennivalk listja";
    }
trType()
QCString TranslatorHungarian::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1716 of file translator_hu.h.
    {
      return createNoun(first_capital, singular, "tpus", "ok");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorHungarian::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1731 of file translator_hu.h.
    {
      return "Tpuskorltozsok";
    }
trTypedefDocumentation()
QCString TranslatorHungarian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 494 of file translator_hu.h.
    { return "Tpusdefincik dokumentcija"; }
trTypedefs()
QCString TranslatorHungarian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 458 of file translator_hu.h.
    { return "Tpusdefincik"; }
trTypeDocumentation()
QCString TranslatorHungarian::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1589 of file translator_hu.h.
    { return "Adattpus dokumentci"; }
trVariableDocumentation()
QCString TranslatorHungarian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 512 of file translator_hu.h.
    { return "Vltozk dokumentcija"; }
trVariables()
QCString TranslatorHungarian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 476 of file translator_hu.h.
    { return "Vltozk"; }
trVersion()
QCString TranslatorHungarian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 552 of file translator_hu.h.
    { return "Verzi"; }
trWarning()
QCString TranslatorHungarian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 548 of file translator_hu.h.
    { return "Figyelmeztets"; }
trWriteList()
QCString TranslatorHungarian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 678 of file translator_hu.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" s ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
zed()
const char * TranslatorHungarian::zed (char c) inline private
Definition at line 58 of file translator_hu.h.
    {
        switch (c & ~('a' ^ 'A')) {
            case 'B': case 'C': case 'D': case 'F': case 'G':
            case 'H': case 'J': case 'K': case 'L': case 'M':
            case 'N': case 'P': case 'Q': case 'R': case 'S':
            case 'T': case 'V': case 'W': case 'X': case 'Z':
                return "  ";
            default:
                return "z ";
        }
    }
Referenced by trClassDiagram(), trCollaborationDiagram(), trGeneratedAutomatically(), and trInclDepGraph().
The documentation for this class was generated from the following file:
src/translator_hu.h