Doxygen: ClassDefAliasImpl Class Reference
ClassDefAliasImpl Class Reference
Public Member Functions
ClassDefAliasImpl (const Definition *newScope, const ClassDef *cd)
~ClassDefAliasImpl () override
DefType definitionType () const override
const ClassDef * getCdAlias () const
std::unique_ptr< ClassDef > deepCopy (const QCString &name) const override
void moveTo (Definition *) override
CodeSymbolType codeSymbolType () const override
QCString getOutputFileBase () const override
QCString getInstanceOutputFileBase () const override
QCString getSourceFileBase () const override
QCString getReference () const override
bool isReference () const override
bool isLocal () const override
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES.
ClassLinkedRefMap getClasses () const override
returns the classes nested into this class
bool hasDocumentation () const override
bool hasDetailedDescription () const override
returns TRUE if this class has a non-empty detailed description
QCString collaborationGraphFileName () const override
returns the file name to use for the collaboration graph
QCString inheritanceGraphFileName () const override
returns the file name to use for the inheritance graph
QCString displayName (bool includeScope=TRUE) const override
CompoundType compoundType () const override
Returns the type of compound this is, i.e.
QCString compoundTypeString () const override
Returns the type of compound as a string.
const BaseClassList & baseClasses () const override
Returns the list of base classes from which this class directly inherits.
const BaseClassList & subClasses () const override
Returns the list of sub classes that directly derive from this class.
const MemberNameInfoLinkedMap & memberNameInfoLinkedMap () const override
Returns a dictionary of all members.
Protection protection () const override
Return the protection level (Public,Protected,Private) in which this compound was found.
bool isLinkableInProject () const override
bool isLinkable () const override
bool isVisibleInHierarchy () const override
the class is visible in a class diagram, or class hierarchy
bool visibleInParentsDeclList () const override
show this class in the declaration section of its parent?
const ArgumentList & templateArguments () const override
Returns the template arguments of this class.
FileDef * getFileDef () const override
Returns the namespace this compound is in, or 0 if it has a global scope.
ModuleDef * getModuleDef () const override
Returns the C++20 module in which this compound's definition can be found.
const MemberDef * getMemberByName (const QCString &s) const override
Returns the member with the given name.
int isBaseClass (const ClassDef *bcd, bool followInstances, const QCString &templSpec) const override
Returns TRUE iff bcd is a direct or indirect base class of this class.
bool isSubClass (ClassDef *bcd, int level=0) const override
Returns TRUE iff bcd is a direct or indirect sub class of this class.
bool isAccessibleMember (const MemberDef *md) const override
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
const TemplateInstanceList & getTemplateInstances () const override
Returns a sorted dictionary with all template instances found for this template class.
const ClassDef * templateMaster () const override
Returns the template master of which this class is an instance.
bool isTemplate () const override
Returns TRUE if this class is a template.
const IncludeInfo * includeInfo () const override
const UsesClassList & usedImplementationClasses () const override
const UsesClassList & usedByImplementationClasses () const override
const ConstraintClassList & templateTypeConstraints () const override
bool isTemplateArgument () const override
const Definition * findInnerCompound (const QCString &name) const override
ArgumentLists getTemplateParameterLists () const override
Returns the template parameter lists that form the template declaration of this class.
QCString qualifiedNameWithTemplateParameters (const ArgumentLists *actualParams=nullptr, uint32_t *actualParamIndex=nullptr) const override
bool isAbstract () const override
Returns TRUE if there is at least one pure virtual member in this class.
bool isObjectiveC () const override
Returns TRUE if this class is implemented in Objective-C.
bool isFortran () const override
Returns TRUE if this class is implemented in Fortran.
bool isCSharp () const override
Returns TRUE if this class is implemented in C#.
bool isFinal () const override
Returns TRUE if this class is marked as final.
bool isSealed () const override
Returns TRUE if this class is marked as sealed.
bool isPublished () const override
Returns TRUE if this class is marked as published.
bool isExtension () const override
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
bool isForwardDeclared () const override
Returns TRUE if this class represents a forward declaration of a template class.
bool isInterface () const override
Returns TRUE if this class represents an interface.
ClassDef * categoryOf () const override
Returns the class of which this is a category (Objective-C only)
QCString className () const override
Returns the name of the class including outer classes, but not including namespaces.
MemberList * getMemberList (MemberListType lt) const override
Returns the members in the list identified by lt.
const MemberLists & getMemberLists () const override
Returns the list containing the list of members sorted per type.
const MemberGroupList & getMemberGroups () const override
Returns the member groups defined for this class.
const TemplateNameMap & getTemplateBaseClassNames () const override
bool isUsedOnly () const override
QCString anchor () const override
bool isEmbeddedInOuterScope () const override
bool isSimple () const override
const ClassDef * tagLessReference () const override
const MemberDef * isSmartPointer () const override
bool isJavaEnum () const override
QCString title () const override
QCString generatedFromFiles () const override
const FileList & usedFiles () const override
const ArgumentList & typeConstraints () const override
const ExampleList & getExamples () const override
bool hasExamples () const override
QCString getMemberListFileName () const override
bool subGrouping () const override
bool isSliceLocal () const override
bool hasNonReferenceSuperClass () const override
QCString requiresClause () const override
StringVector getQualifiers () const override
bool containsOverload (const MemberDef *md) const override
int countMembersIncludingGrouped (MemberListType lt, const ClassDef *inheritedFrom, bool additional) const override
int countMemberDeclarations (MemberListType lt, const ClassDef *inheritedFrom, MemberListType lt2, bool invert, bool showAlways, ClassDefSet &visitedClasses) const override
void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const override
ClassDef * insertTemplateInstance (const QCString &fileName, int startLine, int startColumn, const QCString &templSpec, bool &freshInstance) const override
bool isImplicitTemplateInstance () const override
void writeDocumentation (OutputList &ol) const override
void writeDocumentationForInnerClasses (OutputList &ol) const override
void writeMemberPages (OutputList &ol) const override
void writeMemberList (OutputList &ol) const override
void writeDeclaration (OutputList &ol, const MemberDef *md, bool inGroup, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const override
void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const override
void writeSummaryLinks (OutputList &ol) const override
void writeInlineDocumentation (OutputList &ol) const override
void writeTagFile (TextStream &ol) const override
void writeMemberDeclarations (OutputList &ol, ClassDefSet &visitedClasses, MemberListType lt, const QCString &title, const QCString &subTitle=QCString(), bool showInline=FALSE, const ClassDef *inheritedFrom=nullptr, MemberListType lt2=MemberListType::Invalid(), bool invert=FALSE, bool showAlways=FALSE) const override
void addGroupedInheritedMembers (OutputList &ol, MemberListType lt, const ClassDef *inheritedFrom, const QCString &inheritId) const override
void updateBaseClasses (const BaseClassList &) override
Update the list of base classes to the one passed.
void updateSubClasses (const BaseClassList &) override
Update the list of sub classes to the one passed.
Public Member Functions inherited from DefinitionAliasMixin< ClassDef >
DefinitionAliasMixin (const Definition *scope, const Definition *alias)
~DefinitionAliasMixin () override=default
void init ()
void deinit ()
bool isAlias () const override
const QCString & name () const override
bool isAnonymous () const override
const QCString & localName () const override
QCString qualifiedName () const override
QCString symbolName () const override
QCString getSourceFileBase () const override
QCString getSourceAnchor () const override
QCString documentation () const override
int docLine () const override
QCString docFile () const override
QCString briefDescription (bool abbreviate=FALSE) const override
QCString briefDescriptionAsTooltip () const override
int briefLine () const override
QCString inbodyDocumentation () const override
QCString inbodyFile () const override
int inbodyLine () const override
QCString briefFile () const override
QCString getDefFileName () const override
QCString getDefFileExtension () const override
int getDefLine () const override
int getDefColumn () const override
bool hasDocumentation () const override
bool hasUserDocumentation () const override
bool isVisibleInProject () const override
bool isVisible () const override
bool isHidden () const override
bool isArtificial () const override
bool isExported () const override
QCString getReference () const override
bool isReference () const override
QCString externalReference (const QCString &relPath) const override
int getStartDefLine () const override
int getStartBodyLine () const override
int getEndBodyLine () const override
const FileDef * getBodyDef () const override
SrcLangExt getLanguage () const override
const GroupList & partOfGroups () const override
bool isLinkableViaGroup () const override
const RefItemVector & xrefListItems () const override
const Definition * findInnerCompound (const QCString &name) const override
Definition * getOuterScope () const override
const MemberVector & getReferencesMembers () const override
const MemberVector & getReferencedByMembers () const override
bool hasSections () const override
bool hasSources () const override
bool hasBriefDescription () const override
QCString id () const override
const SectionRefs & getSectionRefs () const override
QCString navigationPathAsString () const override
QCString pathFragment () const override
Public Member Functions inherited from ClassDef
Public Member Functions inherited from Definition
Additional Inherited Members
Public Types inherited from ClassDef
enum CompoundType {
Class , Struct , Union , Interface ,
Protocol , Category , Exception , Service ,
Singleton
}
The various compound types.
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Protected Member Functions inherited from DefinitionAliasMixin< ClassDef >
const Definition * getAlias () const
const Definition * getScope () const
Detailed Description
Definition at line 422 of file classdef.cpp.
Constructor & Destructor Documentation
ClassDefAliasImpl()
ClassDefAliasImpl::ClassDefAliasImpl (const Definition * newScope, const ClassDef * cd) inline
Definition at line 425 of file classdef.cpp.
      : DefinitionAliasMixin(newScope,cd) { init(); }
References DefinitionAliasMixin< ClassDef >::DefinitionAliasMixin(), and DefinitionAliasMixin< ClassDef >::init().
~ClassDefAliasImpl()
ClassDefAliasImpl::~ClassDefAliasImpl () inline override
Definition at line 427 of file classdef.cpp.
{ deinit(); }
References DefinitionAliasMixin< ClassDef >::deinit().
Member Function Documentation
addGroupedInheritedMembers()
void ClassDefAliasImpl::addGroupedInheritedMembers (OutputList & ol, MemberListType lt, const ClassDef * inheritedFrom, const QCString & inheritId) const inline override virtual
Implements ClassDef.
Definition at line 634 of file classdef.cpp.
    { getCdAlias()->addGroupedInheritedMembers(ol,lt,inheritedFrom,inheritId); }
References ClassDef::addGroupedInheritedMembers(), and getCdAlias().
anchor()
QCString ClassDefAliasImpl::anchor () const inline override virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 555 of file classdef.cpp.
    { return getCdAlias()->anchor(); }
References Definition::anchor(), and getCdAlias().
baseClasses()
const BaseClassList & ClassDefAliasImpl::baseClasses () const inline override virtual
Returns the list of base classes from which this class directly inherits.
Implements ClassDef.
Definition at line 468 of file classdef.cpp.
    { return getCdAlias()->baseClasses(); }
References ClassDef::baseClasses(), and getCdAlias().
categoryOf()
ClassDef * ClassDefAliasImpl::categoryOf () const inline override virtual
Returns the class of which this is a category (Objective-C only)
Implements ClassDef.
Definition at line 541 of file classdef.cpp.
    { return getCdAlias()->categoryOf(); }
References ClassDef::categoryOf(), and getCdAlias().
className()
QCString ClassDefAliasImpl::className () const inline override virtual
Returns the name of the class including outer classes, but not including namespaces.
Implements ClassDef.
Definition at line 543 of file classdef.cpp.
    { return getCdAlias()->className(); }
References ClassDef::className(), and getCdAlias().
codeSymbolType()
CodeSymbolType ClassDefAliasImpl::codeSymbolType () const inline override virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 438 of file classdef.cpp.
    { return getCdAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getCdAlias().
collaborationGraphFileName()
QCString ClassDefAliasImpl::collaborationGraphFileName () const inline override virtual
returns the file name to use for the collaboration graph
Implements ClassDef.
Definition at line 458 of file classdef.cpp.
    { return getCdAlias()->collaborationGraphFileName(); }
References ClassDef::collaborationGraphFileName(), and getCdAlias().
compoundType()
CompoundType ClassDefAliasImpl::compoundType () const inline override virtual
Returns the type of compound this is, i.e.
class/struct/union/..
Implements ClassDef.
Definition at line 464 of file classdef.cpp.
    { return getCdAlias()->compoundType(); }
References ClassDef::compoundType(), and getCdAlias().
compoundTypeString()
QCString ClassDefAliasImpl::compoundTypeString () const inline override virtual
Returns the type of compound as a string.
Implements ClassDef.
Definition at line 466 of file classdef.cpp.
    { return getCdAlias()->compoundTypeString(); }
References ClassDef::compoundTypeString(), and getCdAlias().
containsOverload()
bool ClassDefAliasImpl::containsOverload (const MemberDef * md) const inline override virtual
Implements ClassDef.
Definition at line 591 of file classdef.cpp.
    { return getCdAlias()->containsOverload(md); }
References ClassDef::containsOverload(), and getCdAlias().
countMemberDeclarations()
int ClassDefAliasImpl::countMemberDeclarations (MemberListType lt, const ClassDef * inheritedFrom, MemberListType lt2, bool invert, bool showAlways, ClassDefSet & visitedClasses) const inline override virtual
Implements ClassDef.
Definition at line 596 of file classdef.cpp.
    { return getCdAlias()->countMemberDeclarations(lt,inheritedFrom,lt2,invert,showAlways,visitedClasses); }
References ClassDef::countMemberDeclarations(), and getCdAlias().
countMembersIncludingGrouped()
int ClassDefAliasImpl::countMembersIncludingGrouped (MemberListType lt, const ClassDef * inheritedFrom, bool additional) const inline override virtual
Implements ClassDef.
Definition at line 594 of file classdef.cpp.
    { return getCdAlias()->countMembersIncludingGrouped(lt,inheritedFrom,additional); }
References ClassDef::countMembersIncludingGrouped(), and getCdAlias().
deepCopy()
std::unique_ptr< ClassDef > ClassDefAliasImpl::deepCopy (const QCString & name) const inline override virtual
Implements ClassDef.
Definition at line 433 of file classdef.cpp.
{
      return createClassDefAlias(getScope(),getCdAlias());
    }
References createClassDefAlias(), getCdAlias(), DefinitionAliasMixin< ClassDef >::getScope(), and Definition::name().
definitionType()
DefType ClassDefAliasImpl::definitionType () const inline override virtual
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Definition at line 430 of file classdef.cpp.
{ return TypeClass; }
References definitionType(), and Definition::TypeClass.
Referenced by definitionType().
displayName()
QCString ClassDefAliasImpl::displayName (bool includeScope = TRUE) const inline override virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 462 of file classdef.cpp.
    { return makeDisplayName(this,includeScope); }
References makeDisplayName().
findInnerCompound()
const Definition * ClassDefAliasImpl::findInnerCompound (const QCString & name) const inline override virtual
Implements Definition.
Definition at line 514 of file classdef.cpp.
    { return getCdAlias()->findInnerCompound(name); }
References Definition::findInnerCompound(), getCdAlias(), and Definition::name().
generatedFromFiles()
QCString ClassDefAliasImpl::generatedFromFiles () const inline override virtual
Implements ClassDef.
Definition at line 569 of file classdef.cpp.
    { return getCdAlias()->generatedFromFiles(); }
References ClassDef::generatedFromFiles(), and getCdAlias().
getCdAlias()
const ClassDef * ClassDefAliasImpl::getCdAlias () const inline
Definition at line 432 of file classdef.cpp.
{ return toClassDef(getAlias()); }
References DefinitionAliasMixin< ClassDef >::getAlias(), and toClassDef().
Referenced by addGroupedInheritedMembers(), anchor(), baseClasses(), categoryOf(), className(), codeSymbolType(), collaborationGraphFileName(), compoundType(), compoundTypeString(), containsOverload(), countMemberDeclarations(), countMembersIncludingGrouped(), deepCopy(), findInnerCompound(), generatedFromFiles(), getClasses(), getExamples(), getFileDef(), getInstanceOutputFileBase(), getMemberByName(), getMemberGroups(), getMemberList(), getMemberListFileName(), getMemberLists(), getModuleDef(), getOutputFileBase(), getQualifiers(), getReference(), getSourceFileBase(), getTemplateBaseClassNames(), getTemplateInstances(), getTemplateParameterLists(), hasDetailedDescription(), hasDocumentation(), hasExamples(), hasNonReferenceSuperClass(), includeInfo(), inheritanceGraphFileName(), insertTemplateInstance(), isAbstract(), isAccessibleMember(), isBaseClass(), isCSharp(), isEmbeddedInOuterScope(), isExtension(), isFinal(), isFortran(), isForwardDeclared(), isImplicitTemplateInstance(), isInterface(), isJavaEnum(), isLinkable(), isLinkableInProject(), isLocal(), isObjectiveC(), isPublished(), isReference(), isSealed(), isSimple(), isSliceLocal(), isSmartPointer(), isSubClass(), isTemplate(), isTemplateArgument(), isUsedOnly(), isVisibleInHierarchy(), memberNameInfoLinkedMap(), protection(), requiresClause(), subClasses(), subGrouping(), tagLessReference(), templateArguments(), templateMaster(), templateTypeConstraints(), title(), typeConstraints(), usedByImplementationClasses(), usedFiles(), usedImplementationClasses(), visibleInParentsDeclList(), writeDeclaration(), writeDeclarationLink(), writeDocumentation(), writeDocumentationForInnerClasses(), writeInlineDocumentation(), writeMemberDeclarations(), writeMemberList(), writeMemberPages(), writeQuickMemberLinks(), writeSummaryLinks(), and writeTagFile().
getClasses()
ClassLinkedRefMap ClassDefAliasImpl::getClasses () const inline override virtual
returns the classes nested into this class
Implements ClassDef.
Definition at line 452 of file classdef.cpp.
    { return getCdAlias()->getClasses(); }
References getCdAlias(), and ClassDef::getClasses().
getExamples()
const ExampleList & ClassDefAliasImpl::getExamples () const inline override virtual
Implements ClassDef.
Definition at line 575 of file classdef.cpp.
    { return getCdAlias()->getExamples(); }
References getCdAlias(), and ClassDef::getExamples().
getFileDef()
FileDef * ClassDefAliasImpl::getFileDef () const inline override virtual
Returns the namespace this compound is in, or 0 if it has a global scope.
Returns the file in which this compound's definition can be found. Should not return 0 (but it might be a good idea to check anyway).
Implements ClassDef.
Definition at line 486 of file classdef.cpp.
    { return getCdAlias()->getFileDef(); }
References getCdAlias(), and ClassDef::getFileDef().
getInstanceOutputFileBase()
QCString ClassDefAliasImpl::getInstanceOutputFileBase () const inline override virtual
Implements ClassDef.
Definition at line 442 of file classdef.cpp.
    { return getCdAlias()->getInstanceOutputFileBase(); }
References getCdAlias(), and ClassDef::getInstanceOutputFileBase().
getMemberByName()
const MemberDef * ClassDefAliasImpl::getMemberByName (const QCString &) const inline override virtual
Returns the member with the given name.
Implements ClassDef.
Definition at line 490 of file classdef.cpp.
    { return getCdAlias()->getMemberByName(s); }
References getCdAlias(), and ClassDef::getMemberByName().
getMemberGroups()
const MemberGroupList & ClassDefAliasImpl::getMemberGroups () const inline override virtual
Returns the member groups defined for this class.
Implements ClassDef.
Definition at line 549 of file classdef.cpp.
    { return getCdAlias()->getMemberGroups(); }
References getCdAlias(), and ClassDef::getMemberGroups().
getMemberList()
MemberList * ClassDefAliasImpl::getMemberList (MemberListType lt) const inline override virtual
Returns the members in the list identified by lt.
Implements ClassDef.
Definition at line 545 of file classdef.cpp.
    { return getCdAlias()->getMemberList(lt); }
References getCdAlias(), and ClassDef::getMemberList().
getMemberListFileName()
QCString ClassDefAliasImpl::getMemberListFileName () const inline override virtual
Implements ClassDef.
Definition at line 579 of file classdef.cpp.
    { return getCdAlias()->getMemberListFileName(); }
References getCdAlias(), and ClassDef::getMemberListFileName().
getMemberLists()
const MemberLists & ClassDefAliasImpl::getMemberLists () const inline override virtual
Returns the list containing the list of members sorted per type.
Implements ClassDef.
Definition at line 547 of file classdef.cpp.
    { return getCdAlias()->getMemberLists(); }
References getCdAlias(), and ClassDef::getMemberLists().
getModuleDef()
ModuleDef * ClassDefAliasImpl::getModuleDef () const inline override virtual
Returns the C++20 module in which this compound's definition can be found.
Implements ClassDef.
Definition at line 488 of file classdef.cpp.
    { return getCdAlias()->getModuleDef(); }
References getCdAlias(), and ClassDef::getModuleDef().
getOutputFileBase()
QCString ClassDefAliasImpl::getOutputFileBase () const inline override virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 440 of file classdef.cpp.
    { return getCdAlias()->getOutputFileBase(); }
References getCdAlias(), and Definition::getOutputFileBase().
getQualifiers()
StringVector ClassDefAliasImpl::getQualifiers () const inline override virtual
Implements ClassDef.
Definition at line 589 of file classdef.cpp.
    { return getCdAlias()->getQualifiers(); }
References getCdAlias(), and ClassDef::getQualifiers().
getReference()
QCString ClassDefAliasImpl::getReference () const inline override virtual
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Implements Definition.
Definition at line 446 of file classdef.cpp.
    { return getCdAlias()->getReference(); }
References getCdAlias(), and Definition::getReference().
getSourceFileBase()
QCString ClassDefAliasImpl::getSourceFileBase () const inline override virtual
Returns the name of the source listing of this definition.
Implements Definition.
Definition at line 444 of file classdef.cpp.
    { return getCdAlias()->getSourceFileBase(); }
References getCdAlias(), and Definition::getSourceFileBase().
getTemplateBaseClassNames()
const TemplateNameMap & ClassDefAliasImpl::getTemplateBaseClassNames () const inline override virtual
Implements ClassDef.
Definition at line 551 of file classdef.cpp.
    { return getCdAlias()->getTemplateBaseClassNames(); }
References getCdAlias(), and ClassDef::getTemplateBaseClassNames().
getTemplateInstances()
const TemplateInstanceList & ClassDefAliasImpl::getTemplateInstances () const inline override virtual
Returns a sorted dictionary with all template instances found for this template class.
Returns 0 if not a template or no instances.
Implements ClassDef.
Definition at line 498 of file classdef.cpp.
    { return getCdAlias()->getTemplateInstances(); }
References getCdAlias(), and ClassDef::getTemplateInstances().
getTemplateParameterLists()
ArgumentLists ClassDefAliasImpl::getTemplateParameterLists () const inline override virtual
Returns the template parameter lists that form the template declaration of this class.
Example: template<class T> class TC {} = 0; will return a list with one ArgumentList containing one argument with type="class" and name="T".
Implements ClassDef.
Definition at line 516 of file classdef.cpp.
    { return getCdAlias()->getTemplateParameterLists(); }
References getCdAlias(), and ClassDef::getTemplateParameterLists().
hasDetailedDescription()
bool ClassDefAliasImpl::hasDetailedDescription () const inline override virtual
returns TRUE if this class has a non-empty detailed description
Implements ClassDef.
Definition at line 456 of file classdef.cpp.
    { return getCdAlias()->hasDetailedDescription(); }
References getCdAlias(), and ClassDef::hasDetailedDescription().
hasDocumentation()
bool ClassDefAliasImpl::hasDocumentation () const inline override virtual
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Implements Definition.
Definition at line 454 of file classdef.cpp.
    { return getCdAlias()->hasDocumentation(); }
References getCdAlias(), and Definition::hasDocumentation().
hasExamples()
bool ClassDefAliasImpl::hasExamples () const inline override virtual
Implements ClassDef.
Definition at line 577 of file classdef.cpp.
    { return getCdAlias()->hasExamples(); }
References getCdAlias(), and ClassDef::hasExamples().
hasNonReferenceSuperClass()
bool ClassDefAliasImpl::hasNonReferenceSuperClass () const inline override virtual
Implements ClassDef.
Definition at line 585 of file classdef.cpp.
    { return getCdAlias()->hasNonReferenceSuperClass(); }
References getCdAlias(), and ClassDef::hasNonReferenceSuperClass().
includeInfo()
const IncludeInfo * ClassDefAliasImpl::includeInfo () const inline override virtual
Implements ClassDef.
Definition at line 504 of file classdef.cpp.
    { return getCdAlias()->includeInfo(); }
References getCdAlias(), and ClassDef::includeInfo().
inheritanceGraphFileName()
QCString ClassDefAliasImpl::inheritanceGraphFileName () const inline override virtual
returns the file name to use for the inheritance graph
Implements ClassDef.
Definition at line 460 of file classdef.cpp.
    { return getCdAlias()->inheritanceGraphFileName(); }
References getCdAlias(), and ClassDef::inheritanceGraphFileName().
insertTemplateInstance()
ClassDef * ClassDefAliasImpl::insertTemplateInstance (const QCString & fileName, int startLine, int startColumn, const QCString & templSpec, bool & freshInstance) const inline override virtual
Implements ClassDef.
Definition at line 603 of file classdef.cpp.
    { return getCdAlias()->insertTemplateInstance(fileName,startLine,startColumn,templSpec,freshInstance); }
References getCdAlias(), and ClassDef::insertTemplateInstance().
isAbstract()
bool ClassDefAliasImpl::isAbstract () const inline override virtual
Returns TRUE if there is at least one pure virtual member in this class.
Implements ClassDef.
Definition at line 521 of file classdef.cpp.
    { return getCdAlias()->isAbstract(); }
References getCdAlias(), and ClassDef::isAbstract().
isAccessibleMember()
bool ClassDefAliasImpl::isAccessibleMember (const MemberDef * md) const inline override virtual
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
Implements ClassDef.
Definition at line 496 of file classdef.cpp.
    { return getCdAlias()->isAccessibleMember(md); }
References getCdAlias(), and ClassDef::isAccessibleMember().
isBaseClass()
int ClassDefAliasImpl::isBaseClass (const ClassDef * bcd, bool followInstances, const QCString & templSpec) const inline override virtual
Returns TRUE iff bcd is a direct or indirect base class of this class.
This function will recursively traverse all branches of the inheritance tree.
Implements ClassDef.
Definition at line 492 of file classdef.cpp.
    { return getCdAlias()->isBaseClass(bcd,followInstances,templSpec); }
References getCdAlias(), and ClassDef::isBaseClass().
isCSharp()
bool ClassDefAliasImpl::isCSharp () const inline override virtual
Returns TRUE if this class is implemented in C#.
Implements ClassDef.
Definition at line 527 of file classdef.cpp.
    { return getCdAlias()->isCSharp(); }
References getCdAlias(), and ClassDef::isCSharp().
isEmbeddedInOuterScope()
bool ClassDefAliasImpl::isEmbeddedInOuterScope () const inline override virtual
Implements ClassDef.
Definition at line 557 of file classdef.cpp.
    { return getCdAlias()->isEmbeddedInOuterScope(); }
References getCdAlias(), and ClassDef::isEmbeddedInOuterScope().
isExtension()
bool ClassDefAliasImpl::isExtension () const inline override virtual
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
Implements ClassDef.
Definition at line 535 of file classdef.cpp.
    { return getCdAlias()->isExtension(); }
References getCdAlias(), and ClassDef::isExtension().
isFinal()
bool ClassDefAliasImpl::isFinal () const inline override virtual
Returns TRUE if this class is marked as final.
Implements ClassDef.
Definition at line 529 of file classdef.cpp.
    { return getCdAlias()->isFinal(); }
References getCdAlias(), and ClassDef::isFinal().
isFortran()
bool ClassDefAliasImpl::isFortran () const inline override virtual
Returns TRUE if this class is implemented in Fortran.
Implements ClassDef.
Definition at line 525 of file classdef.cpp.
    { return getCdAlias()->isFortran(); }
References getCdAlias(), and ClassDef::isFortran().
isForwardDeclared()
bool ClassDefAliasImpl::isForwardDeclared () const inline override virtual
Returns TRUE if this class represents a forward declaration of a template class.
Implements ClassDef.
Definition at line 537 of file classdef.cpp.
    { return getCdAlias()->isForwardDeclared(); }
References getCdAlias(), and ClassDef::isForwardDeclared().
isImplicitTemplateInstance()
bool ClassDefAliasImpl::isImplicitTemplateInstance () const inline override virtual
Implements ClassDef.
Definition at line 606 of file classdef.cpp.
    { return getCdAlias()->isImplicitTemplateInstance(); }
References getCdAlias(), and ClassDef::isImplicitTemplateInstance().
isInterface()
bool ClassDefAliasImpl::isInterface () const inline override virtual
Returns TRUE if this class represents an interface.
Implements ClassDef.
Definition at line 539 of file classdef.cpp.
    { return getCdAlias()->isInterface(); }
References getCdAlias(), and ClassDef::isInterface().
isJavaEnum()
bool ClassDefAliasImpl::isJavaEnum () const inline override virtual
Implements ClassDef.
Definition at line 565 of file classdef.cpp.
    { return getCdAlias()->isJavaEnum(); }
References getCdAlias(), and ClassDef::isJavaEnum().
isLinkable()
bool ClassDefAliasImpl::isLinkable () const inline override virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 478 of file classdef.cpp.
    { return getCdAlias()->isLinkable(); }
References getCdAlias(), and Definition::isLinkable().
isLinkableInProject()
bool ClassDefAliasImpl::isLinkableInProject () const inline override virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 476 of file classdef.cpp.
    { return getCdAlias()->isLinkableInProject(); }
References getCdAlias(), and Definition::isLinkableInProject().
isLocal()
bool ClassDefAliasImpl::isLocal () const inline override virtual
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES.
Implements ClassDef.
Definition at line 450 of file classdef.cpp.
    { return getCdAlias()->isLocal(); }
References getCdAlias(), and ClassDef::isLocal().
isObjectiveC()
bool ClassDefAliasImpl::isObjectiveC () const inline override virtual
Returns TRUE if this class is implemented in Objective-C.
Implements ClassDef.
Definition at line 523 of file classdef.cpp.
    { return getCdAlias()->isObjectiveC(); }
References getCdAlias(), and ClassDef::isObjectiveC().
isPublished()
bool ClassDefAliasImpl::isPublished () const inline override virtual
Returns TRUE if this class is marked as published.
Implements ClassDef.
Definition at line 533 of file classdef.cpp.
    { return getCdAlias()->isPublished(); }
References getCdAlias(), and ClassDef::isPublished().
isReference()
bool ClassDefAliasImpl::isReference () const inline override virtual
Returns TRUE if this definition is imported via a tag file.
Implements Definition.
Definition at line 448 of file classdef.cpp.
    { return getCdAlias()->isReference(); }
References getCdAlias(), and Definition::isReference().
isSealed()
bool ClassDefAliasImpl::isSealed () const inline override virtual
Returns TRUE if this class is marked as sealed.
Implements ClassDef.
Definition at line 531 of file classdef.cpp.
    { return getCdAlias()->isSealed(); }
References getCdAlias(), and ClassDef::isSealed().
isSimple()
bool ClassDefAliasImpl::isSimple () const inline override virtual
Implements ClassDef.
Definition at line 559 of file classdef.cpp.
    { return getCdAlias()->isSimple(); }
References getCdAlias(), and ClassDef::isSimple().
isSliceLocal()
bool ClassDefAliasImpl::isSliceLocal () const inline override virtual
Implements ClassDef.
Definition at line 583 of file classdef.cpp.
    { return getCdAlias()->isSliceLocal(); }
References getCdAlias(), and ClassDef::isSliceLocal().
isSmartPointer()
const MemberDef * ClassDefAliasImpl::isSmartPointer () const inline override virtual
Implements ClassDef.
Definition at line 563 of file classdef.cpp.
    { return getCdAlias()->isSmartPointer(); }
References getCdAlias(), and ClassDef::isSmartPointer().
isSubClass()
bool ClassDefAliasImpl::isSubClass (ClassDef * bcd, int level = 0) const inline override virtual
Returns TRUE iff bcd is a direct or indirect sub class of this class.
Implements ClassDef.
Definition at line 494 of file classdef.cpp.
    { return getCdAlias()->isSubClass(bcd,level); }
References getCdAlias(), and ClassDef::isSubClass().
isTemplate()
bool ClassDefAliasImpl::isTemplate () const inline override virtual
Returns TRUE if this class is a template.
Implements ClassDef.
Definition at line 502 of file classdef.cpp.
    { return getCdAlias()->isTemplate(); }
References getCdAlias(), and ClassDef::isTemplate().
isTemplateArgument()
bool ClassDefAliasImpl::isTemplateArgument () const inline override virtual
Implements ClassDef.
Definition at line 512 of file classdef.cpp.
    { return getCdAlias()->isTemplateArgument(); }
References getCdAlias(), and ClassDef::isTemplateArgument().
isUsedOnly()
bool ClassDefAliasImpl::isUsedOnly () const inline override virtual
Implements ClassDef.
Definition at line 553 of file classdef.cpp.
    { return getCdAlias()->isUsedOnly(); }
References getCdAlias(), and ClassDef::isUsedOnly().
isVisibleInHierarchy()
bool ClassDefAliasImpl::isVisibleInHierarchy () const inline override virtual
the class is visible in a class diagram, or class hierarchy
Implements ClassDef.
Definition at line 480 of file classdef.cpp.
    { return getCdAlias()->isVisibleInHierarchy(); }
References getCdAlias(), and ClassDef::isVisibleInHierarchy().
memberNameInfoLinkedMap()
const MemberNameInfoLinkedMap & ClassDefAliasImpl::memberNameInfoLinkedMap () const inline override virtual
Returns a dictionary of all members.
This includes any inherited members. Members are sorted alphabetically.
Implements ClassDef.
Definition at line 472 of file classdef.cpp.
    { return getCdAlias()->memberNameInfoLinkedMap(); }
References getCdAlias(), and ClassDef::memberNameInfoLinkedMap().
moveTo()
void ClassDefAliasImpl::moveTo (Definition *) inline override virtual
Implements ClassDef.
Definition at line 436 of file classdef.cpp.
{}
protection()
Protection ClassDefAliasImpl::protection () const inline override virtual
Return the protection level (Public,Protected,Private) in which this compound was found.
Implements ClassDef.
Definition at line 474 of file classdef.cpp.
    { return getCdAlias()->protection(); }
References getCdAlias(), and ClassDef::protection().
qualifiedNameWithTemplateParameters()
QCString ClassDefAliasImpl::qualifiedNameWithTemplateParameters (const ArgumentLists * actualParams = nullptr, uint32_t * actualParamIndex = nullptr) const inline override virtual
Implements ClassDef.
Definition at line 518 of file classdef.cpp.
    { return makeQualifiedNameWithTemplateParameters(this,actualParams,actualParamIndex); }
References makeQualifiedNameWithTemplateParameters().
requiresClause()
QCString ClassDefAliasImpl::requiresClause () const inline override virtual
Implements ClassDef.
Definition at line 587 of file classdef.cpp.
    { return getCdAlias()->requiresClause(); }
References getCdAlias(), and ClassDef::requiresClause().
subClasses()
const BaseClassList & ClassDefAliasImpl::subClasses () const inline override virtual
Returns the list of sub classes that directly derive from this class.
Implements ClassDef.
Definition at line 470 of file classdef.cpp.
    { return getCdAlias()->subClasses(); }
References getCdAlias(), and ClassDef::subClasses().
subGrouping()
bool ClassDefAliasImpl::subGrouping () const inline override virtual
Implements ClassDef.
Definition at line 581 of file classdef.cpp.
    { return getCdAlias()->subGrouping(); }
References getCdAlias(), and ClassDef::subGrouping().
tagLessReference()
const ClassDef * ClassDefAliasImpl::tagLessReference () const inline override virtual
Implements ClassDef.
Definition at line 561 of file classdef.cpp.
    { return getCdAlias()->tagLessReference(); }
References getCdAlias(), and ClassDef::tagLessReference().
templateArguments()
const ArgumentList & ClassDefAliasImpl::templateArguments () const inline override virtual
Returns the template arguments of this class.
Implements ClassDef.
Definition at line 484 of file classdef.cpp.
    { return getCdAlias()->templateArguments(); }
References getCdAlias(), and ClassDef::templateArguments().
templateMaster()
const ClassDef * ClassDefAliasImpl::templateMaster () const inline override virtual
Returns the template master of which this class is an instance.
Returns 0 if not applicable.
Implements ClassDef.
Definition at line 500 of file classdef.cpp.
    { return getCdAlias()->templateMaster(); }
References getCdAlias(), and ClassDef::templateMaster().
templateTypeConstraints()
const ConstraintClassList & ClassDefAliasImpl::templateTypeConstraints () const inline override virtual
Implements ClassDef.
Definition at line 510 of file classdef.cpp.
    { return getCdAlias()->templateTypeConstraints(); }
References getCdAlias(), and ClassDef::templateTypeConstraints().
title()
QCString ClassDefAliasImpl::title () const inline override virtual
Implements ClassDef.
Definition at line 567 of file classdef.cpp.
    { return getCdAlias()->title(); }
References getCdAlias(), and ClassDef::title().
Referenced by writeMemberDeclarations().
typeConstraints()
const ArgumentList & ClassDefAliasImpl::typeConstraints () const inline override virtual
Implements ClassDef.
Definition at line 573 of file classdef.cpp.
    { return getCdAlias()->typeConstraints(); }
References getCdAlias(), and ClassDef::typeConstraints().
updateBaseClasses()
void ClassDefAliasImpl::updateBaseClasses (const BaseClassList & bcd) inline override virtual
Update the list of base classes to the one passed.
Implements ClassDef.
Definition at line 638 of file classdef.cpp.
{}
updateSubClasses()
void ClassDefAliasImpl::updateSubClasses (const BaseClassList & bcd) inline override virtual
Update the list of sub classes to the one passed.
Implements ClassDef.
Definition at line 639 of file classdef.cpp.
{}
usedByImplementationClasses()
const UsesClassList & ClassDefAliasImpl::usedByImplementationClasses () const inline override virtual
Implements ClassDef.
Definition at line 508 of file classdef.cpp.
    { return getCdAlias()->usedByImplementationClasses(); }
References getCdAlias(), and ClassDef::usedByImplementationClasses().
usedFiles()
const FileList & ClassDefAliasImpl::usedFiles () const inline override virtual
Implements ClassDef.
Definition at line 571 of file classdef.cpp.
    { return getCdAlias()->usedFiles(); }
References getCdAlias(), and ClassDef::usedFiles().
usedImplementationClasses()
const UsesClassList & ClassDefAliasImpl::usedImplementationClasses () const inline override virtual
Implements ClassDef.
Definition at line 506 of file classdef.cpp.
    { return getCdAlias()->usedImplementationClasses(); }
References getCdAlias(), and ClassDef::usedImplementationClasses().
visibleInParentsDeclList()
bool ClassDefAliasImpl::visibleInParentsDeclList () const inline override virtual
show this class in the declaration section of its parent?
Implements ClassDef.
Definition at line 482 of file classdef.cpp.
    { return getCdAlias()->visibleInParentsDeclList(); }
References getCdAlias(), and ClassDef::visibleInParentsDeclList().
writeDeclaration()
void ClassDefAliasImpl::writeDeclaration (OutputList & ol, const MemberDef * md, bool inGroup, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const inline override virtual
Implements ClassDef.
Definition at line 617 of file classdef.cpp.
    { getCdAlias()->writeDeclaration(ol,md,inGroup,indentLevel,inheritedFrom,inheritId); }
References getCdAlias(), and ClassDef::writeDeclaration().
writeDeclarationLink()
void ClassDefAliasImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const inline override virtual
Implements ClassDef.
Definition at line 600 of file classdef.cpp.
    { getCdAlias()->writeDeclarationLink(ol,found,header,localNames); }
References found, getCdAlias(), and ClassDef::writeDeclarationLink().
writeDocumentation()
void ClassDefAliasImpl::writeDocumentation (OutputList & ol) const inline override virtual
Implements ClassDef.
Definition at line 609 of file classdef.cpp.
    { getCdAlias()->writeDocumentation(ol); }
References getCdAlias(), and ClassDef::writeDocumentation().
writeDocumentationForInnerClasses()
void ClassDefAliasImpl::writeDocumentationForInnerClasses (OutputList & ol) const inline override virtual
Implements ClassDef.
Definition at line 611 of file classdef.cpp.
    { getCdAlias()->writeDocumentationForInnerClasses(ol); }
References getCdAlias(), and ClassDef::writeDocumentationForInnerClasses().
writeInlineDocumentation()
void ClassDefAliasImpl::writeInlineDocumentation (OutputList & ol) const inline override virtual
Implements ClassDef.
Definition at line 624 of file classdef.cpp.
    { getCdAlias()->writeInlineDocumentation(ol); }
References getCdAlias(), and ClassDef::writeInlineDocumentation().
writeMemberDeclarations()
void ClassDefAliasImpl::writeMemberDeclarations (OutputList & ol, ClassDefSet & visitedClasses, MemberListType lt, const QCString & title, const QCString & subTitle = QCString(), bool showInline = FALSE, const ClassDef * inheritedFrom = nullptr, MemberListType lt2 = MemberListType::Invalid(), bool invert = FALSE, bool showAlways = FALSE) const inline override virtual
Implements ClassDef.
Definition at line 628 of file classdef.cpp.
    { getCdAlias()->writeMemberDeclarations(ol,visitedClasses,lt,title,subTitle,showInline,inheritedFrom,lt2,invert,showAlways); }
References getCdAlias(), title(), and ClassDef::writeMemberDeclarations().
writeMemberList()
void ClassDefAliasImpl::writeMemberList (OutputList & ol) const inline override virtual
Implements ClassDef.
Definition at line 615 of file classdef.cpp.
    { getCdAlias()->writeMemberList(ol); }
References getCdAlias(), and ClassDef::writeMemberList().
writeMemberPages()
void ClassDefAliasImpl::writeMemberPages (OutputList & ol) const inline override virtual
Implements ClassDef.
Definition at line 613 of file classdef.cpp.
    { getCdAlias()->writeMemberPages(ol); }
References getCdAlias(), and ClassDef::writeMemberPages().
writeQuickMemberLinks()
void ClassDefAliasImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * md) const inline override virtual
Implements ClassDef.
Definition at line 620 of file classdef.cpp.
    { getCdAlias()->writeQuickMemberLinks(ol,md); }
References getCdAlias(), and ClassDef::writeQuickMemberLinks().
writeSummaryLinks()
void ClassDefAliasImpl::writeSummaryLinks (OutputList & ol) const inline override virtual
Implements ClassDef.
Definition at line 622 of file classdef.cpp.
    { getCdAlias()->writeSummaryLinks(ol); }
References getCdAlias(), and ClassDef::writeSummaryLinks().
writeTagFile()
void ClassDefAliasImpl::writeTagFile (TextStream & ol) const inline override virtual
Implements ClassDef.
Definition at line 626 of file classdef.cpp.
    { getCdAlias()->writeTagFile(ol); }
References getCdAlias(), and ClassDef::writeTagFile().
The documentation for this class was generated from the following file:
src/classdef.cpp