Doxygen: /home/runner/work/doxygen/doxygen/src/docnode.cpp File Reference
docnode.cpp File Reference
#include "docnode.h"
#include "docparser_p.h"
#include "htmlentity.h"
#include "configimpl.h"
#include "configoptions.h"
#include "emoji.h"
#include "message.h"
#include "doxygen.h"
#include "cite.h"
#include "util.h"
#include "formula.h"
#include "markdown.h"
#include "pagedef.h"
#include "namespacedef.h"
#include "groupdef.h"
#include "cmdmapper.h"
#include "config.h"
#include "vhdldocgen.h"
#include "doctokenizer.h"
#include "plantuml.h"
#include "language.h"
#include "datetime.h"
#include "trace.h"
#include "anchor.h"
Classes
struct ActiveRowSpan
Helper class to compute the grid for an HTML style table.
Macros
#define AUTO_TRACE(...) (void)0
#define AUTO_TRACE_ADD(...) (void)0
#define AUTO_TRACE_EXIT(...) (void)0
#define INTERNAL_ASSERT(x) do {} while(0)
Typedefs
typedef std::vector< ActiveRowSpan > RowSpanList
List of ActiveRowSpan classes.
Functions
static void unescapeCRef (QCString &s)
static QCString stripKnownExtensions (const QCString &text)
static void setParent (DocNodeVariant *n, DocNodeVariant *newParent)
static void flattenParagraphs (DocNodeVariant *root, DocNodeList &children)
static bool findAttribute (const HtmlAttribList &tagHtmlAttribs, const char *attrName, QCString *result)
Variables
static const char * g_sectionLevelToName []
static const std::set< std::string > g_plantumlEngine
Macro Definition Documentation
AUTO_TRACE
#define AUTO_TRACE (...) (void)0
Definition at line 45 of file docnode.cpp.
AUTO_TRACE_ADD
#define AUTO_TRACE_ADD (...) (void)0
Definition at line 46 of file docnode.cpp.
AUTO_TRACE_EXIT
#define AUTO_TRACE_EXIT (...) (void)0
Definition at line 47 of file docnode.cpp.
INTERNAL_ASSERT
#define INTERNAL_ASSERT (x) do {} while(0)
Definition at line 50 of file docnode.cpp.
Typedef Documentation
RowSpanList
typedef std::vector<ActiveRowSpan> RowSpanList
List of ActiveRowSpan classes.
Definition at line 2068 of file docnode.cpp.
Function Documentation
findAttribute()
static bool findAttribute (const HtmlAttribList & tagHtmlAttribs, const char * attrName, QCString * result) static
Definition at line 4521 of file docnode.cpp.
{
  for (const auto &opt : tagHtmlAttribs)
  {
    if (opt.name==attrName)
    {
      *result = opt.value;
      return TRUE;
    }
  }
  return FALSE;
}
References FALSE, and TRUE.
Referenced by DocPara::handleHtmlStartTag().
flattenParagraphs()
static void flattenParagraphs (DocNodeVariant * root, DocNodeList & children) static
Definition at line 784 of file docnode.cpp.
{
  DocNodeList newChildren;
  for (auto &dn : children)
  {
    DocPara *para = std::get_if<DocPara>(&dn);
    if (para)
    {
      //// move the children of the paragraph to the end of the newChildren list
      newChildren.move_append(para->children());
    }
  }
  // replace the children list by the newChildren list
  children.clear();
  children.move_append(newChildren);
  // reparent the children
  for (auto &cn : children)
  {
    setParent(&cn,root);
  }
}
References DocCompoundNode::children(), GrowVector< T >::clear(), DocNodeList::move_append(), and setParent().
Referenced by DocRef::parse().
setParent()
static void setParent (DocNodeVariant * n, DocNodeVariant * newParent) static
Definition at line 116 of file docnode.cpp.
{
  std::visit([&](auto &&x)->decltype(auto) { return x.setParent(newParent); }, *n);
}
Referenced by flattenParagraphs().
stripKnownExtensions()
static QCString stripKnownExtensions (const QCString & text) static
Strips known html and tex extensions from text.
Definition at line 101 of file docnode.cpp.
{
  QCString result=text;
  if (result.endsWith(".tex"))
  {
    result=result.left(result.length()-4);
  }
  else if (result.right(Doxygen::htmlFileExtension.length())==
         QCString(Doxygen::htmlFileExtension))
  {
    result=result.left(result.length()-Doxygen::htmlFileExtension.length());
  }
  return result;
}
References QCString::endsWith(), Doxygen::htmlFileExtension, QCString::left(), QCString::length(), and QCString::right().
Referenced by DocLink::DocLink(), DocRef::DocRef(), and DocSecRefItem::parse().
unescapeCRef()
static void unescapeCRef (QCString & s) static
Definition at line 79 of file docnode.cpp.
{
  QCString result;
  const char *p = s.data();
  if (p)
  {
    char c;
    while ((c=*p++))
    {
      if (c=='{') c='<'; else if (c=='}') c='>';
      result+=c;
    }
  }
  result=substitute(result,"&lt;","<");
  result=substitute(result,"&gt;",">");
  s = result;
}
References QCString::data(), and substitute().
Referenced by DocPara::handleHtmlStartTag().
Variable Documentation
g_plantumlEngine
const std::set<std::string> g_plantumlEngine static
Initial value:
{
  "uml", "bpm", "wire", "dot", "ditaa",
  "salt", "math", "latex", "gantt", "mindmap",
  "wbs", "yaml", "creole", "json", "flow",
  "board", "git", "hcl", "regex", "ebnf"
}
Definition at line 68 of file docnode.cpp.
Referenced by DocPara::handleCommand().
g_sectionLevelToName
const char* g_sectionLevelToName[] static
Initial value:
=
{
  "page",
  "section",
  "subsection",
  "subsubsection",
  "paragraph",
  "subparagraph"
}
Definition at line 55 of file docnode.cpp.
Referenced by DocSection::parse().