Doxygen: DotCallGraph Class Reference
DotCallGraph Class Reference
Representation of an call graph.
#include <src/dotcallgraph.h>
Public Member Functions
DotCallGraph (const MemberDef *md, bool inverse)
~DotCallGraph () override
bool isTrivial () const
bool isTooBig () const
int numNodes () const
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
Public Member Functions inherited from DotGraph
DotGraph ()
virtual ~DotGraph ()=default
Static Public Member Functions
static bool isTrivial (const MemberDef *md, bool inverse)
Protected Member Functions
QCString getBaseName () const override
QCString getMapLabel () const override
void computeTheGraph () override
Protected Member Functions inherited from DotGraph
int getNextNodeNumber ()
returns the node number.
int getNextEdgeNumber ()
returns the edge number.
QCString writeGraph (TextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1)
virtual QCString absMapName () const
virtual QCString getImgAltText () const
QCString absBaseName () const
QCString absDotName () const
QCString imgName () const
QCString absImgName () const
QCString relImgName () const
Private Member Functions
void buildGraph (DotNode *n, const MemberDef *md, int distance)
void determineVisibleNodes (DotNodeDeque &queue, int &maxNodes)
void determineTruncatedNodes (DotNodeDeque &queue)
Private Attributes
DotNode * m_startNode
DotNodeMap m_usedNodes
bool m_inverse
QCString m_diskName
const Definition * m_scope
Additional Inherited Members
Static Protected Member Functions inherited from DotGraph
static void writeGraphHeader (TextStream &t, const QCString &title=QCString())
static void writeGraphFooter (TextStream &t)
static void computeGraph (DotNode *root, GraphType gt, GraphOutputFormat format, const QCString &rank, bool renderParents, bool backArrows, const QCString &title, QCString &graphStr)
Protected Attributes inherited from DotGraph
GraphOutputFormat m_graphFormat = GraphOutputFormat::BITMAP
EmbeddedOutputFormat m_textFormat = EmbeddedOutputFormat::Html
Dir m_dir
QCString m_fileName
QCString m_relPath
bool m_generateImageMap = false
int m_graphId = 0
QCString m_absPath
QCString m_baseName
QCString m_theGraph
bool m_regenerate = false
bool m_doNotAddImageToIndex = false
bool m_noDivTag = false
bool m_zoomable = true
bool m_urlOnly = false
Detailed Description
Representation of an call graph.
Definition at line 26 of file dotcallgraph.h.
Constructor & Destructor Documentation
DotCallGraph()
DotCallGraph::DotCallGraph (const MemberDef * md, bool inverse)
Definition at line 120 of file dotcallgraph.cpp.
{
  m_inverse = inverse;
  m_diskName = md->getOutputFileBase()+"_"+md->anchor();
  m_scope    = md->getOuterScope();
  QCString uniqueId = getUniqueId(md);
  QCString name;
  if (Config_getBool(HIDE_SCOPE_NAMES))
  {
    name = md->name();
  }
  else
  {
    name = md->qualifiedName();
  }
  QCString tooltip = md->briefDescriptionAsTooltip();
  m_startNode = new DotNode(this,
    linkToText(md->getLanguage(),name,FALSE),
    tooltip,
    uniqueId,
    TRUE     // root node
  );
  m_startNode->setDistance(0);
  m_usedNodes.emplace(uniqueId.str(),m_startNode);
  buildGraph(m_startNode,md,1);
  int maxNodes = Config_getInt(DOT_GRAPH_MAX_NODES);
  DotNodeDeque openNodeQueue;
  openNodeQueue.push_back(m_startNode);
  determineVisibleNodes(openNodeQueue,maxNodes);
  openNodeQueue.clear();
  openNodeQueue.push_back(m_startNode);
  determineTruncatedNodes(openNodeQueue);
}
References Definition::anchor(), Definition::briefDescriptionAsTooltip(), buildGraph(), Config_getBool, Config_getInt, determineTruncatedNodes(), determineVisibleNodes(), DotGraph::DotNode, FALSE, Definition::getLanguage(), Definition::getOuterScope(), Definition::getOutputFileBase(), getUniqueId(), linkToText(), m_diskName, m_inverse, m_scope, m_startNode, m_usedNodes, Definition::name(), Definition::qualifiedName(), QCString::str(), and TRUE.
~DotCallGraph()
DotCallGraph::~DotCallGraph () override
Definition at line 155 of file dotcallgraph.cpp.
{
  DotNode::deleteNodes(m_startNode);
}
References DotNode::deleteNodes(), and m_startNode.
Member Function Documentation
buildGraph()
void DotCallGraph::buildGraph (DotNode * n, const MemberDef * md, int distance) private
Definition at line 33 of file dotcallgraph.cpp.
{
  auto refs = m_inverse ? md->getReferencedByMembers() : md->getReferencesMembers();
  for (const auto &rmd : refs)
  {
    if (rmd->isCallable())
    {
      QCString uniqueId = getUniqueId(rmd);
      auto it = m_usedNodes.find(uniqueId.str());
      if (it!=m_usedNodes.end()) // file is already a node in the graph
      {
        DotNode *bn = it->second;
        n->addChild(bn,EdgeInfo::Blue,EdgeInfo::Solid);
        bn->addParent(n);
        bn->setDistance(distance);
      }
      else
      {
        QCString name;
        if (Config_getBool(HIDE_SCOPE_NAMES))
        {
          name  = rmd->getOuterScope()==m_scope ?
            rmd->name() : rmd->qualifiedName();
        }
        else
        {
          name = rmd->qualifiedName();
        }
        QCString tooltip = rmd->briefDescriptionAsTooltip();
        DotNode *bn = new DotNode(
            this,
            linkToText(rmd->getLanguage(),name,FALSE),
            tooltip,
            uniqueId,
            0 //distance
            );
        n->addChild(bn,EdgeInfo::Blue,EdgeInfo::Solid);
        bn->addParent(n);
        bn->setDistance(distance);
        m_usedNodes.emplace(uniqueId.str(),bn);
        buildGraph(bn,rmd,distance+1);
      }
    }
  }
}
References DotNode::addChild(), DotNode::addParent(), EdgeInfo::Blue, buildGraph(), Config_getBool, DotGraph::DotNode, FALSE, Definition::getReferencedByMembers(), Definition::getReferencesMembers(), getUniqueId(), linkToText(), m_inverse, m_scope, m_usedNodes, DotNode::setDistance(), EdgeInfo::Solid, and QCString::str().
Referenced by buildGraph(), and DotCallGraph().
computeTheGraph()
void DotCallGraph::computeTheGraph () override protected virtual
Implements DotGraph.
Definition at line 165 of file dotcallgraph.cpp.
{
  computeGraph(
    m_startNode,
    GraphType::CallGraph,
    m_graphFormat,
    m_inverse ? "RL" : "LR",
    FALSE,
    m_inverse,
    m_startNode->label(),
    m_theGraph);
}
References CallGraph, DotGraph::computeGraph(), FALSE, DotGraph::m_graphFormat, m_inverse, m_startNode, and DotGraph::m_theGraph.
determineTruncatedNodes()
void DotCallGraph::determineTruncatedNodes (DotNodeDeque & queue) private
Definition at line 99 of file dotcallgraph.cpp.
{
  while (!queue.empty())
  {
    DotNode *n = queue.front();
    queue.pop_front();
    if (n->isVisible() && n->isTruncated()==DotNode::Unknown)
    {
      bool truncated = FALSE;
      for (const auto &dn : n->children())
      {
        if (!dn->isVisible())
          truncated = TRUE;
        else
          queue.push_back(dn);
      }
      n->markAsTruncated(truncated);
    }
  }
}
References DotNode::children(), DotGraph::DotNode, FALSE, DotNode::isTruncated(), DotNode::isVisible(), DotNode::markAsTruncated(), TRUE, and DotNode::Unknown.
Referenced by DotCallGraph().
determineVisibleNodes()
void DotCallGraph::determineVisibleNodes (DotNodeDeque & queue, int & maxNodes) private
Definition at line 80 of file dotcallgraph.cpp.
{
  while (!queue.empty() && maxNodes>0)
  {
    DotNode *n = queue.front();
    queue.pop_front();
    if (!n->isVisible() && n->distance()<=Config_getInt(MAX_DOT_GRAPH_DEPTH)) // not yet processed
    {
      n->markAsVisible();
      maxNodes--;
      // add direct children
      for (const auto &dn : n->children())
      {
        queue.push_back(dn);
      }
    }
  }
}
References DotNode::children(), Config_getInt, DotNode::distance(), DotGraph::DotNode, DotNode::isVisible(), and DotNode::markAsVisible().
Referenced by DotCallGraph().
getBaseName()
QCString DotCallGraph::getBaseName () const override protected virtual
Implements DotGraph.
Definition at line 160 of file dotcallgraph.cpp.
{
  return m_diskName + (m_inverse ? "_icgraph" : "_cgraph");
}
References m_diskName, and m_inverse.
getMapLabel()
QCString DotCallGraph::getMapLabel () const override protected virtual
Implements DotGraph.
Definition at line 178 of file dotcallgraph.cpp.
{
  return m_baseName;
}
References DotGraph::m_baseName.
isTooBig()
bool DotCallGraph::isTooBig () const
Definition at line 202 of file dotcallgraph.cpp.
{
  return numNodes()>=Config_getInt(DOT_GRAPH_MAX_NODES);
}
References Config_getInt, and numNodes().
Referenced by MemberDefImpl::_writeCallerGraph(), and MemberDefImpl::_writeCallGraph().
isTrivial() [1/2]
bool DotCallGraph::isTrivial () const
Definition at line 197 of file dotcallgraph.cpp.
{
  return m_startNode->children().empty();
}
References m_startNode.
Referenced by MemberDefImpl::_hasVisibleCallerGraph(), MemberDefImpl::_hasVisibleCallGraph(), MemberDefImpl::_writeCallerGraph(), and MemberDefImpl::_writeCallGraph().
isTrivial() [2/2]
bool DotCallGraph::isTrivial (const MemberDef * md, bool inverse) static
Definition at line 212 of file dotcallgraph.cpp.
{
  auto refs = inverse ? md->getReferencedByMembers() : md->getReferencesMembers();
  for (const auto &rmd : refs)
  {
    if (rmd->isCallable())
    {
      return FALSE;
    }
  }
  return TRUE;
}
References FALSE, Definition::getReferencedByMembers(), Definition::getReferencesMembers(), and TRUE.
numNodes()
int DotCallGraph::numNodes () const
Definition at line 207 of file dotcallgraph.cpp.
{
  return static_cast<int>(m_startNode->children().size());
}
References m_startNode.
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), and isTooBig().
writeGraph()
QCString DotCallGraph::writeGraph (TextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1)
Definition at line 183 of file dotcallgraph.cpp.
{
  m_doNotAddImageToIndex = textFormat!=EmbeddedOutputFormat::Html;
  return DotGraph::writeGraph(out, graphFormat, textFormat, path, fileName, relPath, generateImageMap, graphId);
}
References Html, DotGraph::m_doNotAddImageToIndex, and DotGraph::writeGraph().
Referenced by DocbookGenerator::endCallGraph(), HtmlGenerator::endCallGraph(), LatexGenerator::endCallGraph(), and RTFGenerator::endCallGraph().
Member Data Documentation
m_diskName
QCString DotCallGraph::m_diskName private
Definition at line 54 of file dotcallgraph.h.
Referenced by DotCallGraph(), and getBaseName().
m_inverse
bool DotCallGraph::m_inverse private
Definition at line 53 of file dotcallgraph.h.
Referenced by buildGraph(), computeTheGraph(), DotCallGraph(), and getBaseName().
m_scope
const Definition* DotCallGraph::m_scope private
Definition at line 55 of file dotcallgraph.h.
Referenced by buildGraph(), and DotCallGraph().
m_startNode
DotNode* DotCallGraph::m_startNode private
Definition at line 51 of file dotcallgraph.h.
Referenced by computeTheGraph(), DotCallGraph(), isTrivial(), numNodes(), and ~DotCallGraph().
m_usedNodes
DotNodeMap DotCallGraph::m_usedNodes private
Definition at line 52 of file dotcallgraph.h.
Referenced by buildGraph(), and DotCallGraph().
The documentation for this class was generated from the following files:
src/dotcallgraph.h
src/dotcallgraph.cpp