Doxygen: DocHtmlDetails Class Reference
DocHtmlDetails Class Reference
Node Html details.
#include <src/docnode.h>
Public Member Functions
DocHtmlDetails (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
const HtmlAttribList & attribs () const
Token parse ()
void parseSummary (DocNodeVariant *, HtmlAttribList &attribs)
const DocNodeVariant * summary () const
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
HtmlAttribList m_attribs
std::unique_ptr< DocNodeVariant > m_summary
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node Html details.
Definition at line 835 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlDetails()
DocHtmlDetails::DocHtmlDetails (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) inline
Definition at line 838 of file docnode.h.
                                                                                           :
       DocCompoundNode(parser,parent), m_attribs(attribs) {}
References attribs(), DocCompoundNode::DocCompoundNode(), m_attribs, DocNode::parent(), and DocNode::parser().
Member Function Documentation
attribs()
const HtmlAttribList & DocHtmlDetails::attribs () const inline
Definition at line 840 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by DocHtmlDetails(), HtmlDocVisitor::operator()(), PrintDocVisitor::operator()(), and parseSummary().
parse()
Token DocHtmlDetails::parse ()
Definition at line 1404 of file docnode.cpp.
{
  AUTO_TRACE();
  Token retval(TokenRetval::TK_NONE);
  auto ns = AutoNodeStack(parser(),thisVariant());
  // parse one or more paragraphs
  bool isFirst=TRUE;
  DocPara *par=nullptr;
  do
  {
    children().append<DocPara>(parser(),thisVariant());
    par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse();
  }
  while (retval.is(TokenRetval::TK_NEWPARA));
  if (par) par->markLast();
  if (retval.is_any_of(TokenRetval::TK_NONE,TokenRetval::TK_EOF))
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment while inside <details> block");
  }
  if (!summary())
  {
    HtmlAttribList summaryAttribs;
    m_summary = createDocNode<DocHtmlSummary>(parser(),thisVariant(),summaryAttribs);
    DocHtmlSummary *summary = &std::get<DocHtmlSummary>(*m_summary);
    summary->children().append<DocWord>(parser(),thisVariant(),theTranslator->trDetails());
  }
  AUTO_TRACE_EXIT("retval={}",retval.to_string());
  return retval.is(TokenRetval::RetVal_EndHtmlDetails) ? Token::make_RetVal_OK() : retval;
}
References DocNodeList::append(), AUTO_TRACE, AUTO_TRACE_EXIT, DocCompoundNode::children(), createDocNode(), FALSE, DocNodeList::get_last(), Token::is(), Token::is_any_of(), m_summary, DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), DocNode::parser(), summary(), theTranslator, DocNode::thisVariant(), Token::to_string(), Translator::trDetails(), TRUE, and warn_doc_error.
parseSummary()
void DocHtmlDetails::parseSummary (DocNodeVariant * parent, HtmlAttribList & attribs)
Definition at line 1439 of file docnode.cpp.
{
  AUTO_TRACE();
  m_summary = createDocNode<DocHtmlSummary>(parser(),parent,attribs);
  DocHtmlSummary *summary = &std::get<DocHtmlSummary>(*m_summary);
  summary->parse();
}
References attribs(), AUTO_TRACE, createDocNode(), m_summary, DocNode::parent(), DocNode::parser(), and summary().
Referenced by DocPara::handleHtmlStartTag().
summary()
const DocNodeVariant * DocHtmlDetails::summary () const inline
Definition at line 843 of file docnode.h.
{ return m_summary.get(); }
References m_summary.
Referenced by DocPara::handleHtmlStartTag(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), parse(), and parseSummary().
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlDetails::m_attribs private
Definition at line 846 of file docnode.h.
Referenced by attribs(), and DocHtmlDetails().
m_summary
std::unique_ptr<DocNodeVariant> DocHtmlDetails::m_summary private
Definition at line 847 of file docnode.h.
Referenced by parse(), parseSummary(), and summary().
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp