Doxygen: /home/runner/work/doxygen/doxygen/src/message.h File Reference
message.h File Reference
#include <cstdarg>
#include "qcstring.h"
Macros
#define PRINTFLIKE(FORMAT, PARAM)
#define msg_no_newline_allowed(x) static_assert(!has_newline_at_end(x),"text: \"" x "\" should not have \\n at end");
#define msg_newline_required(x) static_assert(has_newline_at_end(x),"text: \"" x "\" should have \\n at end");
#define warn(file, line, fmt, ...)
#define warn_undoc(file, line, fmt, ...)
#define warn_incomplete_doc(file, line, fmt, ...)
#define warn_doc_error(file, line, fmt, ...)
#define warn_uncond(fmt, ...)
#define err(fmt, ...)
#define err_full(file, line, fmt, ...)
#define term(fmt, ...)
Functions
void msg (const char *fmt,...) PRINTFLIKE(1
void void warn_ (const QCString &file, int line, const char *fmt,...) PRINTFLIKE(3
void void void va_warn (const QCString &file, int line, const char *fmt, va_list args)
void warn_simple (const QCString &file, int line, const char *text)
void warn_undoc_ (const QCString &file, int line, const char *fmt,...) PRINTFLIKE(3
void void warn_incomplete_doc_ (const QCString &file, int line, const char *fmt,...) PRINTFLIKE(3
void void void warn_doc_error_ (const QCString &file, int line, const char *fmt,...) PRINTFLIKE(3
void void void void warn_uncond_ (const char *fmt,...) PRINTFLIKE(1
void void void void void err_ (const char *fmt,...) PRINTFLIKE(1
void void void void void void err_full_ (const QCString &file, int line, const char *fmt,...) PRINTFLIKE(3
void void void void void void void term_ (const char *fmt,...) PRINTFLIKE(1
void void void void void void void QCString warn_line (const QCString &file, int line)
void initWarningFormat ()
void warn_flush ()
void finishWarnExit ()
template<std::size_t N>
constexpr bool has_newline_at_end (const char(&str)[N])
Macro Definition Documentation
err
#define err (fmt, ...)
Value:
   do {     \
   msg_newline_required(fmt); \
   err_(fmt,##__VA_ARGS__);     \
   } while(0)
Definition at line 84 of file message.h.
err_full
#define err_full (file, line, fmt, ...)
Value:
   do { \
   msg_no_newline_allowed(fmt);          \
   err_full_(file,line,fmt,##__VA_ARGS__); \
   } while(0)
Definition at line 89 of file message.h.
msg_newline_required
#define msg_newline_required (x) static_assert(has_newline_at_end(x),"text: \"" x "\" should have \\n at end");
Definition at line 56 of file message.h.
msg_no_newline_allowed
#define msg_no_newline_allowed (x) static_assert(!has_newline_at_end(x),"text: \"" x "\" should not have \\n at end");
Definition at line 53 of file message.h.
PRINTFLIKE
#define PRINTFLIKE (FORMAT, PARAM)
Definition at line 25 of file message.h.
term
#define term (fmt, ...)
Value:
   do {    \
   msg_newline_required(fmt); \
   term_(fmt,##__VA_ARGS__);    \
   } while(0)
Definition at line 94 of file message.h.
warn
#define warn (file, line, fmt, ...)
Value:
   do { \
   msg_no_newline_allowed(fmt);      \
   warn_(file,line,fmt,##__VA_ARGS__); \
   } while(0)
Definition at line 59 of file message.h.
warn_doc_error
#define warn_doc_error (file, line, fmt, ...)
Value:
   do { \
   msg_no_newline_allowed(fmt);                \
   warn_doc_error_(file,line,fmt,##__VA_ARGS__); \
   } while(0)
Definition at line 74 of file message.h.
warn_incomplete_doc
#define warn_incomplete_doc (file, line, fmt, ...)
Value:
   do { \
   msg_no_newline_allowed(fmt);                     \
   warn_incomplete_doc_(file,line,fmt,##__VA_ARGS__); \
   } while(0)
Definition at line 69 of file message.h.
warn_uncond
#define warn_uncond (fmt, ...)
Value:
   do { \
   msg_newline_required(fmt);     \
   warn_uncond_(fmt,##__VA_ARGS__); \
   } while(0)
Definition at line 79 of file message.h.
warn_undoc
#define warn_undoc (file, line, fmt, ...)
Value:
   do { \
   msg_no_newline_allowed(fmt);            \
   warn_undoc_(file,line,fmt,##__VA_ARGS__); \
   } while(0)
Definition at line 64 of file message.h.
Function Documentation
err_()
void void void void void err_ (const char * fmt, ...)
err_full_()
void void void void void void err_full_ (const QCString & file, int line, const char * fmt, ...)
finishWarnExit()
void finishWarnExit ()
Definition at line 305 of file message.cpp.
{
  fflush(stdout);
  if (g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT && g_warnlogFile != "-")
  {
    Portable::fclose(g_warnFile);
    g_warnFile = nullptr;
  }
  if (g_warnStat && g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT && g_warnlogFile != "-")
  {
    std::ifstream warnFile = Portable::openInputStream(g_warnlogFile);
    if (!warnFile.is_open())
    {
      g_warnFile = stderr;
      err("Cannot open warnings file '%s' for reading\n",g_warnlogFile.data());
    }
    else
    {
      std::string line;
      while (getline(warnFile,line))
      {
        fprintf(stderr,"%s\n",line.c_str());
      }
      warnFile.close();
    }
  }
  if (g_warnlogTemp) Portable::unlink(g_warnlogFile);
  if (g_warnStat && (g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS ||
                     g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT))
  {
    Doxygen::terminating=true;
    exit(1);
  }
}
References QCString::data(), err, Portable::fclose(), g_warnBehavior, g_warnFile, g_warnlogFile, g_warnlogTemp, g_warnStat, Portable::openInputStream(), Doxygen::terminating, and Portable::unlink().
Referenced by generateOutput().
has_newline_at_end()
template<std::size_t N> constexpr bool has_newline_at_end (const char(&) str[N]) constexpr
Definition at line 48 of file message.h.
{
  return str[N-2]=='\n';
}
initWarningFormat()
void initWarningFormat ()
Definition at line 41 of file message.cpp.
{
  g_warnFormat = Config_getString(WARN_FORMAT);
  g_warnLineFormat = Config_getString(WARN_LINE_FORMAT);
  g_warnBehavior = Config_getEnum(WARN_AS_ERROR);
  g_warnlogFile = Config_getString(WARN_LOGFILE);
  if (g_warnlogFile.isEmpty() && g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT)
  {
    uint32_t pid = Portable::pid();
    g_warnlogFile.sprintf("doxygen_warnings_temp_%d.tmp",pid);
    g_warnlogTemp = true;
  }
  if (!g_warnlogFile.isEmpty())
  {
    if (g_warnlogFile == "-")
    {
      g_warnFile = stdout;
    }
    else
    {
      FileInfo fi(g_warnlogFile.str());
      Dir d(fi.dirPath().c_str());
      if (!d.exists() && !d.mkdir(fi.dirPath().c_str()))
      {
        // point it to something valid, because warn() relies on it
        g_warnFile = stderr;
        err("Cannot create directory for '%s', redirecting 'WARN_LOGFILE' output to 'stderr'\n",g_warnlogFile.data());
      }
      else if (!(g_warnFile = Portable::fopen(g_warnlogFile,"w")))
      {
        // point it to something valid, because warn() relies on it
        g_warnFile = stderr;
        err("Cannot open '%s' for writing, redirecting 'WARN_LOGFILE' output to 'stderr'\n",g_warnlogFile.data());
      }
    }
  }
  else
  {
    g_warnFile = stderr;
  }
  if (g_warnBehavior != WARN_AS_ERROR_t::NO)
  {
    g_warningStr = g_errorStr;
  }
  // make sure the g_warnFile is closed in case we call exit and it is still open
  std::atexit([](){
      if (g_warnFile && g_warnFile!=stderr && g_warnFile!=stdout)
      {
        Portable::fclose(g_warnFile);
        g_warnFile = nullptr;
      }
  });
}
References Config_getEnum, Config_getString, QCString::data(), FileInfo::dirPath(), err, Dir::exists(), Portable::fclose(), Portable::fopen(), g_errorStr, g_warnBehavior, g_warnFile, g_warnFormat, g_warningStr, g_warnLineFormat, g_warnlogFile, g_warnlogTemp, QCString::isEmpty(), Dir::mkdir(), Portable::pid(), QCString::sprintf(), and QCString::str().
Referenced by checkConfiguration().
msg()
void msg (const char * fmt, ...)
term_()
void void void void void void void term_ (const char * fmt, ...)
va_warn()
void void void va_warn (const QCString & file, int line, const char * fmt, va_list args)
Definition at line 218 of file message.cpp.
{
  do_warn(Config_getBool(WARNINGS), file, line, g_warningStr, fmt, args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by TemplateContextImpl::warn(), and TemplateParser::warn().
warn_()
void void warn_ (const QCString & file, int line, const char * fmt, ...)
warn_doc_error_()
void void void warn_doc_error_ (const QCString & file, int line, const char * fmt, ...)
warn_flush()
void warn_flush ()
Definition at line 298 of file message.cpp.
{
  fflush(g_warnFile);
}
References g_warnFile.
Referenced by Statistics::end().
warn_incomplete_doc_()
void void warn_incomplete_doc_ (const QCString & file, int line, const char * fmt, ...)
warn_line()
void void void void void void void QCString warn_line (const QCString & file, int line)
Definition at line 198 of file message.cpp.
{
  QCString fileSubst = file.isEmpty() ? "<unknown>" : file;
  QCString lineSubst; lineSubst.setNum(line);
  return  substitute(
            substitute(
              g_warnLineFormat,
              "$file",fileSubst
            ),
            "$line",lineSubst
          );
}
References g_warnLineFormat, QCString::isEmpty(), QCString::setNum(), and substitute().
Referenced by addMemberFunction(), checkPageRelations(), computePageRelations(), and findGlobalMember().
warn_simple()
void warn_simple (const QCString & file, int line, const char * text)
Definition at line 223 of file message.cpp.
{
  if (!Config_getBool(WARNINGS)) return; // warning type disabled
  format_warn(file,line,QCString(g_warningStr) + text);
}
References Config_getBool, format_warn(), and g_warningStr.
Referenced by addMemberFunction().
warn_uncond_()
void void void void warn_uncond_ (const char * fmt, ...)
warn_undoc_()
void warn_undoc_ (const QCString & file, int line, const char * fmt, ...)