Doxygen: TranslatorGerman Class Reference
TranslatorGerman Class Reference
#include <src/translator_de.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int numEntries) override
QCString trInheritedByList (int numEntries) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool, bool singular) override
QCString trFile (bool, bool singular) override
QCString trNamespace (bool, bool singular) override
QCString trGroup (bool, bool singular) override
QCString trPage (bool, bool singular) override
QCString trMember (bool, bool singular) override
QCString trGlobal (bool, bool singular) override
QCString trAuthor (bool, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int numEntries) override
QCString trImplementedInList (int numEntries) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool, bool singular) override
QCString trSubprogram (bool, bool singular) override
QCString trTypeConstraints () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Compiles a date string.
QCString trDayOfWeek (int dayOfWeek, bool, bool full) override
QCString trMonth (int month, bool, bool full) override
QCString trDayPeriod (bool period) override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
QCString trInterfaces () override
old style UNO IDL services: implemented interfaces
QCString trServices () override
old style UNO IDL services: inherited services
QCString trConstantGroups () override
UNO IDL constant groups.
QCString trConstantGroupReference (const QCString &namespaceName) override
UNO IDL constant groups.
QCString trServiceReference (const QCString &sName) override
UNO IDL service page title.
QCString trSingletonReference (const QCString &sName) override
UNO IDL singleton page title.
QCString trServiceGeneratedFromFiles (bool single) override
UNO IDL service page.
QCString trSingletonGeneratedFromFiles (bool single) override
UNO IDL singleton page.
QCString trDesignUnitHierarchy () override
VHDL design unit hierarchy.
QCString trDesignUnitList () override
VHDL design unit list.
QCString trDesignUnitMembers () override
VHDL design unit members.
QCString trDesignUnitListDescription () override
VHDL design unit list description.
QCString trDesignUnitIndex () override
VHDL design unit index.
QCString trDesignUnits () override
VHDL design units.
QCString trFunctionAndProc () override
VHDL functions/procedures/processes.
QCString trVhdlType (VhdlSpecifier type, bool single) override
VHDL type.
QCString trCustomReference (const QCString &name) override
QCString trDesignUnitDocumentation () override
VHDL design unit documentation.
QCString trConcept (bool first_capital, bool singular) override
C++20 concept.
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
QCString trPackageList () override
QCString trFlowchart () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
QCString trCopyToClipboard () override
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString updateNeededMessage () override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString updateNeededMessage () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
Public Member Functions inherited from TranslatorAdapter_1_11_0
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 149 of file translator_de.h.
Member Function Documentation
getLanguageString()
QCString TranslatorGerman::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 176 of file translator_de.h.
    {
      return "0x407 German";
    }
idLanguage()
QCString TranslatorGerman::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 161 of file translator_de.h.
    { return "german"; }
latexLanguageSupportCommand()
QCString TranslatorGerman::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method was designed for languages which do wish to use a babel package.
Implements Translator.
Definition at line 167 of file translator_de.h.
    {
      return "\\usepackage[ngerman]{babel}\n";
    }
trAdditionalInheritedMembers()
QCString TranslatorGerman::trAdditionalInheritedMembers () inline override virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 2011 of file translator_de.h.
    { return "Weitere Geerbte Elemente"; }
trAll()
QCString TranslatorGerman::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1521 of file translator_de.h.
    {
      return "Alle";
    }
trAndMore()
QCString TranslatorGerman::trAndMore (const QCString & number) inline override virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1986 of file translator_de.h.
    { return "und "+number+" mehr ..."; }
trAttention()
QCString TranslatorGerman::trAttention () inline override virtual
Implements Translator.
Definition at line 1097 of file translator_de.h.
    {
      return "Achtung";
    }
trAuthor()
QCString TranslatorGerman::trAuthor (bool , bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1389 of file translator_de.h.
    {
      return createNoun(true, singular, "Autor", "en");
    }
References Translator::createNoun().
trBug()
QCString TranslatorGerman::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1280 of file translator_de.h.
    {
      return "Fehler";
    }
trBugList()
QCString TranslatorGerman::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1286 of file translator_de.h.
    {
      return "Liste der bekannten Fehler";
    }
trCallerGraph()
QCString TranslatorGerman::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1640 of file translator_de.h.
    {
      return "Hier ist ein Graph der zeigt, wo diese Funktion aufgerufen wird:";
    }
trCallGraph()
QCString TranslatorGerman::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1526 of file translator_de.h.
    {
      return "Hier ist ein Graph, der zeigt, was diese Funktion aufruft:";
    }
trCiteReferences()
QCString TranslatorGerman::trCiteReferences () inline override virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1962 of file translator_de.h.
    { return "Literaturverzeichnis"; }
trClass()
QCString TranslatorGerman::trClass (bool , bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1323 of file translator_de.h.
    {
      return createNoun(true, singular, "Klasse", "n");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trClassDiagram()
QCString TranslatorGerman::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 614 of file translator_de.h.
    {
      return "Klassendiagramm fr "+clName+":";
    }
trClassDocumentation()
QCString TranslatorGerman::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 495 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstruktur-Dokumentation";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassen-Dokumentation";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses()
QCString TranslatorGerman::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1238 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstrukturen";
      }
      else
      {
        return "Klassen";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorGerman::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 275 of file translator_de.h.
    { return "Klassenhierarchie"; }
trClassHierarchyDescription()
QCString TranslatorGerman::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 334 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Hier folgt eine hierarchische Auflistung der "
               "Entwurfseinheiten:";
      }
      else
      {
        return "Die Liste der Ableitungen ist -mit Einschrnkungen- "
               "alphabetisch sortiert:";
      }
    }
References Config_getBool.
trClassMethods()
QCString TranslatorGerman::trClassMethods () inline override virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2049 of file translator_de.h.
    {
      return "Klassenmethoden";
    }
trCode()
QCString TranslatorGerman::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 980 of file translator_de.h.
    {
      return "code";
    }
trCollaborationDiagram()
QCString TranslatorGerman::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 926 of file translator_de.h.
    {
      return "Zusammengehrigkeiten von "+clName+":";
    }
trCompoundIndex()
QCString TranslatorGerman::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 472 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
    return "Datenstruktur-Verzeichnis";
      else
        return "Klassen-Verzeichnis";
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorGerman::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1695 of file translator_de.h.
    { return "Datentyp-Index"; }
trCompoundList()
QCString TranslatorGerman::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 279 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstrukturen";
      }
      else
      {
        return "Auflistung der Klassen";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorGerman::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 358 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Hier folgt die Aufzhlung aller Datenstrukturen "
               "mit einer Kurzbeschreibung:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Hier folgt die Aufzhlung aller Klassen mit einer Kurzbeschreibung:";
      }
      else
      {
        return "Hier folgt die Aufzhlung aller Klassen, Strukturen, "
               "Varianten und Schnittstellen mit einer Kurzbeschreibung:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorGerman::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1668 of file translator_de.h.
      { return "Hier folgen die Datentypen mit Kurzbeschreibungen:"; }
trCompoundListFortran()
QCString TranslatorGerman::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1660 of file translator_de.h.
    { return "Datentyp-Liste"; }
trCompoundMembers()
QCString TranslatorGerman::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 296 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstruktur-Elemente";
      }
      else
      {
        return "Klassen-Elemente";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorGerman::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 377 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll)
      {
        result+="dokumentierten ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="Strukturen und Varianten";
      }
      else
      {
        result+="Klassenelemente";
      }
      result+=" mit Verweisen auf ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die Dokumentation zu jedem Element:";
        }
        else
        {
          result+="die Klassendokumentation zu jedem Element:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die zugehrigen Elemente:";
        }
        else
        {
          result+="die zugehrigen Klassen:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorGerman::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1672 of file translator_de.h.
    {
      QCString result="Hier folgt eine Liste aller ";
      if (!extractAll)
      {
        result+="dokumentierten ";
      }
      result+="Datentypelemente";
      result+=" mit Links ";
      if (!extractAll)
      {
         result+="zur Datenstruktur-Dokumentation fr jedes Element";
      }
      else
      {
         result+="zu den Datentypen, zu denen sie gehren:";
      }
      return result;
    }
trCompoundMembersDescriptionTotal()
QCString TranslatorGerman::trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) inline override virtual
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2417 of file translator_de.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="Hier ist eine Liste aller ";
      if (!extractAll)
      {
        result+="dokumentierter ";
      }
      switch (hl)
      {
        case ClassMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="Struktur- und Einheits-Felder";
          }
          else
          {
            result+="Klassen-Funktionen";
          }
          break;
        case ClassMemberHighlight::Functions:
          result+="Funktionen";
          break;
        case ClassMemberHighlight::Variables:
          result+="Variablen";
          break;
        case ClassMemberHighlight::Typedefs:
          result+="Typen-Definitionen";
          break;
        case ClassMemberHighlight::Enums:
          result+="Aufzhlungen";
          break;
        case ClassMemberHighlight::EnumValues:
          result+="Aufzhlungs-Werte";
          break;
        case ClassMemberHighlight::Properties:
          result+="Eigenschaften";
          break;
        case ClassMemberHighlight::Events:
          result+="Ereignisse";
          break;
        case ClassMemberHighlight::Related:
          result+="zugehrige Symbole";
          break;
        case ClassMemberHighlight::Total: // for completeness
          break;
      }
      result+=" mit Verweisen auf ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die struct/union Dokumentation fr jedes Feld:";
        }
        else
        {
          result+="die Klassen-Dokumentation fr jede Funktion:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die Strukturen/Einheiten auf denen sie sich beziehen:";
        }
        else
        {
          result+="die Klassen auf denen sie sich beziehen:";
        }
      }
      return result;
    }
References ClassMemberHighlight::All, Config_getBool, ClassMemberHighlight::Enums, ClassMemberHighlight::EnumValues, ClassMemberHighlight::Events, ClassMemberHighlight::Functions, ClassMemberHighlight::Properties, ClassMemberHighlight::Related, ClassMemberHighlight::Total, ClassMemberHighlight::Typedefs, and ClassMemberHighlight::Variables.
trCompoundMembersFortran()
QCString TranslatorGerman::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1664 of file translator_de.h.
    { return "Datenfelder"; }
trCompoundReference()
QCString TranslatorGerman::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 689 of file translator_de.h.
    {
      QCString result=clName+" ";
      if (isTemplate) result+="Template-";
      switch(compType)
      {
        case ClassDef::Class:  result+="Klassen"; break;
        case ClassDef::Struct: result+="Struktur"; break;
        case ClassDef::Union:  result+="Varianten"; break;
        case ClassDef::Interface:  result+="Schnittstellen"; break;
        case ClassDef::Protocol:  result+="Protokoll"; break;
        case ClassDef::Category:  result+="Kategorie"; break;
        case ClassDef::Exception:  result+="Ausnahmen"; break;
        default: break;
      }
      result+="referenz";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorGerman::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1736 of file translator_de.h.
    {
      QCString result=clName;
      result += "-";
      switch(compType)
      {
        case ClassDef::Class:      result+="Modul"; break;
        case ClassDef::Struct:     result+="Typ"; break;
        case ClassDef::Union:      result+="Union"; break;
        case ClassDef::Interface:  result+="Interface"; break;
        case ClassDef::Protocol:   result+="Protokoll"; break;
        case ClassDef::Category:   result+="Kategorie"; break;
        case ClassDef::Exception:  result+="Ausnahmen"; break;
        default: break;
      }
      if (isTemplate) result+="-Template";
      result+="-Referenz";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorGerman::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 590 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstrukturen";
      }
      else
      {
        return "Klassen";
      }
    }
References Config_getBool.
trCompoundType()
QCString TranslatorGerman::trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) inline override virtual
the compound type as used for the xrefitems
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2343 of file translator_de.h.
    {
      QCString result;
      switch(compType)
      {
        case ClassDef::Class:
          if (lang == SrcLangExt::Fortran) trType(true,true);
          else result=trClass(true,true);
          break;
        case ClassDef::Struct:     result="Struct"; break;
        case ClassDef::Union:      result="Union"; break;
        case ClassDef::Interface:  result="Interface"; break;
        case ClassDef::Protocol:   result="Protocol"; break;
        case ClassDef::Category:   result="Category"; break;
        case ClassDef::Exception:  result="Exception"; break;
        case ClassDef::Service:    result="Service"; break;
        case ClassDef::Singleton:  result="Singleton"; break;
        default: break;
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, Fortran, ClassDef::Interface, ClassDef::Protocol, ClassDef::Service, ClassDef::Singleton, ClassDef::Struct, trClass(), trType(), and ClassDef::Union.
trConcept()
QCString TranslatorGerman::trConcept (bool first_capital, bool singular) inline override virtual
C++20 concept.
Reimplemented from TranslatorAdapter_1_9_2.
Definition at line 2256 of file translator_de.h.
    {
      return createNoun(first_capital, singular, "Konzept", "Konzepte");
    }
References Translator::createNoun().
trConceptDefinition()
QCString TranslatorGerman::trConceptDefinition () inline override virtual
used to introduce the definition of the C++20 concept
Reimplemented from TranslatorAdapter_1_9_2.
Definition at line 2290 of file translator_de.h.
    {
      return "Konzept-Definition";
    }
trConceptDocumentation()
QCString TranslatorGerman::trConceptDocumentation () inline override virtual
used as the title of chapter containing all information about concepts.
Reimplemented from TranslatorAdapter_1_9_2.
Definition at line 2277 of file translator_de.h.
    { return "Konzept Dokumentation"; }
trConceptIndex()
QCString TranslatorGerman::trConceptIndex () inline override virtual
used as the title of chapter containing the index listing all concepts.
Reimplemented from TranslatorAdapter_1_9_2.
Definition at line 2273 of file translator_de.h.
    { return "Konzept Index"; }
trConceptList()
QCString TranslatorGerman::trConceptList () inline override virtual
used as the title of page containing all the index of all concepts.
Reimplemented from TranslatorAdapter_1_9_2.
Definition at line 2269 of file translator_de.h.
    { return "Konzept Liste"; }
trConceptListDescription()
QCString TranslatorGerman::trConceptListDescription (bool extractAll) inline override virtual
used as an introduction to the concept list
Reimplemented from TranslatorAdapter_1_9_2.
Definition at line 2281 of file translator_de.h.
    {
      QCString result="Hier folgt eine Lister aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Konzepte mit Kurzbeschreibungen:";
      return result;
    }
trConceptReference()
QCString TranslatorGerman::trConceptReference (const QCString & conceptName) inline override virtual
used as the title of the HTML page of a C++20 concept page
Reimplemented from TranslatorAdapter_1_9_2.
Definition at line 2261 of file translator_de.h.
    {
      QCString result=conceptName;
      result+=" Konzept Referenz";
      return result;
    }
trConstantGroupReference()
QCString TranslatorGerman::trConstantGroupReference (const QCString & namespaceName) inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2086 of file translator_de.h.
    {
      QCString result=namespaceName;
      result+=" Konstantengruppen-Referenz";
      return result;
    }
trConstantGroups()
QCString TranslatorGerman::trConstantGroups () inline override virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2082 of file translator_de.h.
    { return "Konstante Gruppen"; }
trConstructorDocumentation()
QCString TranslatorGerman::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 938 of file translator_de.h.
    {
      return "Beschreibung der Konstruktoren und Destruktoren";
    }
trCopyright()
QCString TranslatorGerman::trCopyright () inline override virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1966 of file translator_de.h.
    { return "Copyright"; }
trCopyToClipboard()
QCString TranslatorGerman::trCopyToClipboard () inline override virtual
Reimplemented from TranslatorAdapter_1_10_0.
Definition at line 2623 of file translator_de.h.
    {
      return "In die Zwischenablage kopieren";
    }
trCustomReference()
QCString TranslatorGerman::trCustomReference (const QCString & name) inline override virtual
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2240 of file translator_de.h.
    { return QCString(name)+"-Referenz"; }
trDataTypes()
QCString TranslatorGerman::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1719 of file translator_de.h.
    { return "Datentypen"; }
trDate()
QCString TranslatorGerman::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 628 of file translator_de.h.
    { return "Datum"; }
trDateTime()
QCString TranslatorGerman::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) inline override virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1917 of file translator_de.h.
    {
      static const char *days[]   = { "Mon","Die","Mit","Don","Fre","Sam","Son" };
      static const char *months[] = { "Jan","Feb","Mr","Apr","Mai","Jun","Jul","Aug","Sep","Okt","Nov","Dez" };
      QCString sdate;
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Date)
      {
        sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      }
      if (includeTime == DateTimeType::DateTime) sdate += " ";
      if (includeTime == DateTimeType::DateTime || includeTime == DateTimeType::Time)
      {
        QCString stime;
        stime.sprintf("%.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References Date, DateTime, QCString::sprintf(), and Time.
trDayOfWeek()
QCString TranslatorGerman::trDayOfWeek (int dayOfWeek, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1937 of file translator_de.h.
    {
      static const char *days_short[]   = { "Mo", "Di", "Mi", "Do", "Fr", "Sa", "So" };
      static const char *days_full[]    = { "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod()
QCString TranslatorGerman::trDayPeriod (bool period) inline override virtual
Implements Translator.
Definition at line 1951 of file translator_de.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period?1:0];
    }
trDeclaration()
QCString TranslatorGerman::trDeclaration () inline override virtual
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2549 of file translator_de.h.
{ return "Deklaration";}
trDefinedAtLineInSourceFile()
QCString TranslatorGerman::trDefinedAtLineInSourceFile () inline override virtual
Implements Translator.
Definition at line 902 of file translator_de.h.
    {
      return "Definiert in Zeile @0 der Datei @1.";
    }
trDefinedIn()
QCString TranslatorGerman::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 263 of file translator_de.h.
    { return "Definiert in"; }
trDefinedInSourceFile()
QCString TranslatorGerman::trDefinedInSourceFile () inline override virtual
Implements Translator.
Definition at line 907 of file translator_de.h.
    {
      return "Definiert in Datei @0.";
    }
trDefineDocumentation()
QCString TranslatorGerman::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 560 of file translator_de.h.
    { return "Makro-Dokumentation"; }
trDefines()
QCString TranslatorGerman::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 524 of file translator_de.h.
    { return "Makrodefinitionen"; }
trDefineValue()
QCString TranslatorGerman::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1270 of file translator_de.h.
    {
      return "Wert:";
    }
trDefinition()
QCString TranslatorGerman::trDefinition () inline override virtual
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2548 of file translator_de.h.
{ return "Definition";}
trDeprecated()
QCString TranslatorGerman::trDeprecated () inline override virtual
Implements Translator.
Definition at line 916 of file translator_de.h.
    {
      return "Veraltet";
    }
trDeprecatedList()
QCString TranslatorGerman::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1444 of file translator_de.h.
    {
      return "Veraltete Elemente";
    }
trDesignUnitDocumentation()
QCString TranslatorGerman::trDesignUnitDocumentation () inline override virtual
VHDL design unit documentation.
Reimplemented from TranslatorAdapter_1_8_19.
Definition at line 2248 of file translator_de.h.
    { return "Entwurfseinheiten-Dokumentation"; }
Referenced by trClassDocumentation().
trDesignUnitHierarchy()
QCString TranslatorGerman::trDesignUnitHierarchy () inline override virtual
VHDL design unit hierarchy.
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2131 of file translator_de.h.
    { return "Entwurfseinheiten-Hierarchie"; }
trDesignUnitIndex()
QCString TranslatorGerman::trDesignUnitIndex () inline override virtual
VHDL design unit index.
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2146 of file translator_de.h.
    { return "Entwurfseinheiten-Verzeichnis"; }
trDesignUnitList()
QCString TranslatorGerman::trDesignUnitList () inline override virtual
VHDL design unit list.
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2134 of file translator_de.h.
    { return "Auflistung der Entwurfseinheiten"; }
trDesignUnitListDescription()
QCString TranslatorGerman::trDesignUnitListDescription () inline override virtual
VHDL design unit list description.
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2140 of file translator_de.h.
    {
        return "Hier folgt die Aufzhlung aller Entwurfseinheiten und deren "
               "Elemente mit einer Kurzbeschreibung:";
    }
trDesignUnitMembers()
QCString TranslatorGerman::trDesignUnitMembers () inline override virtual
VHDL design unit members.
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2137 of file translator_de.h.
    { return "Entwurfseinheiten-Elemente"; }
trDesignUnits()
QCString TranslatorGerman::trDesignUnits () inline override virtual
VHDL design units.
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2149 of file translator_de.h.
    { return "Entwurfseinheiten"; }
trDetailedDescription()
QCString TranslatorGerman::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 192 of file translator_de.h.
    { return "Ausfhrliche Beschreibung"; }
trDetailLevel()
QCString TranslatorGerman::trDetailLevel () inline override virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1978 of file translator_de.h.
    { return "Detailebene"; }
trDetails()
QCString TranslatorGerman::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 196 of file translator_de.h.
    { return "Details"; }
trDir()
QCString TranslatorGerman::trDir (bool , bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1616 of file translator_de.h.
    {
      return createNoun(true, singular, "Verzeichnis", "se");
    }
References Translator::createNoun().
trDirDepGraph()
QCString TranslatorGerman::trDirDepGraph (const QCString & name) inline override virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1970 of file translator_de.h.
    { return QCString("Diagramm der Verzeichnisabhngigkeiten fr ")+name+":"; }
trDirDocumentation()
QCString TranslatorGerman::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1598 of file translator_de.h.
    { return "Verzeichnisdokumentation"; }
trDirectories()
QCString TranslatorGerman::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1604 of file translator_de.h.
    { return "Verzeichnisse"; }
trDirIndex()
QCString TranslatorGerman::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1592 of file translator_de.h.
    { return "Verzeichnishierarchie"; }
trDirReference()
QCString TranslatorGerman::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1610 of file translator_de.h.
    { QCString result=dirName; result+="-Verzeichnisreferenz"; return result; }
trDirRelation()
QCString TranslatorGerman::trDirRelation (const QCString & name) inline override virtual
directory relation for name
Implements Translator.
Definition at line 1856 of file translator_de.h.
    {
      return "Bezug " + QCString(name);
    }
trDocumentation()
QCString TranslatorGerman::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 454 of file translator_de.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentation"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorGerman::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 536 of file translator_de.h.
    { return "Aufzhlungen"; }
trEnumerationTypeDocumentation()
QCString TranslatorGerman::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 572 of file translator_de.h.
    { return "Dokumentation der Aufzhlungstypen"; }
trEnumerationValueDocumentation()
QCString TranslatorGerman::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1648 of file translator_de.h.
    { return "Dokumentation der Aufzhlungswerte"; }
trEnumerationValues()
QCString TranslatorGerman::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 554 of file translator_de.h.
    { return "Aufzhlungswerte"; }
trEnumGeneratedFromFiles()
QCString TranslatorGerman::trEnumGeneratedFromFiles (bool single) inline override virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1990 of file translator_de.h.
    { QCString result = "Die Dokumentation fr diesen enum wurde aus ";
      if (single)
        result += "der folgenden Datei";
      else
        result += "den folgenden Dateien";
      result+=" generiert:";
      return result;
    }
trEnumName()
QCString TranslatorGerman::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 255 of file translator_de.h.
    { return "enum-Bezeichner"; }
trEnumReference()
QCString TranslatorGerman::trEnumReference (const QCString & name) inline override virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 2001 of file translator_de.h.
    { return QCString(name)+" Enum-Referenz"; }
trEnumValue()
QCString TranslatorGerman::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 259 of file translator_de.h.
    { return "enum-Wert"; }
trEventDocumentation()
QCString TranslatorGerman::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1462 of file translator_de.h.
    {
      return "Ereignisdokumentation";
    }
trEvents()
QCString TranslatorGerman::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1456 of file translator_de.h.
    {
      return "Ereignisse";
    }
trExamples()
QCString TranslatorGerman::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 326 of file translator_de.h.
    { return "Beispiele"; }
trExamplesDescription()
QCString TranslatorGerman::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 440 of file translator_de.h.
    { return "Hier folgt eine Liste mit allen Beispielen:"; }
trExceptions()
QCString TranslatorGerman::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 644 of file translator_de.h.
    { return "Ausnahmebehandlung"; }
trExportedModules()
QCString TranslatorGerman::trExportedModules () inline override virtual
Reimplemented from TranslatorAdapter_1_9_8.
Definition at line 2614 of file translator_de.h.
    {
      return "Exportierte Module";
    }
trExtendsClass()
QCString TranslatorGerman::trExtendsClass () inline override virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2041 of file translator_de.h.
    {
      return "Erweitert Klasse @0.";
    }
trFile()
QCString TranslatorGerman::trFile (bool , bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1332 of file translator_de.h.
    {
      return createNoun(true, singular, "Datei", "en");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorGerman::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 514 of file translator_de.h.
    { return "Datei-Dokumentation"; }
trFileIn()
QCString TranslatorGerman::trFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1893 of file translator_de.h.
    {
      return "Datei in "+name;
    }
trFileIndex()
QCString TranslatorGerman::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 483 of file translator_de.h.
    { return "Datei-Verzeichnis"; }
trFileList()
QCString TranslatorGerman::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 292 of file translator_de.h.
    { return "Auflistung der Dateien"; }
trFileListDescription()
QCString TranslatorGerman::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 349 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Dateien mit einer Kurzbeschreibung:";
      return result;
    }
trFileMembers()
QCString TranslatorGerman::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 309 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globale Elemente";
      }
      else
      {
        return "Datei-Elemente";
      }
    }
References Config_getBool.
trFileMembersDescription()
QCString TranslatorGerman::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 419 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll) result+="dokumentierten ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="Funktionen, Variablen, Makros, Aufzhlungen und Typdefinitionen";
      }
      else
      {
        result+="Dateielemente";
      }
      result+=" mit Verweisen auf ";
      if (extractAll)
        result+="die Dokumentation zu jedem Element:";
      else
        result+="die zugehrigen Dateien:";
      return result;
    }
References Config_getBool.
trFileMembersDescriptionTotal()
QCString TranslatorGerman::trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) inline override virtual
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2365 of file translator_de.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result="Hier ist eine Lister aller ";
      if (!extractAll) result+="documented ";
      switch (hl)
      {
        case FileMemberHighlight::All:
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          {
            result+="functions, variables, defines, enums, and typedefs";
          }
          else
          {
            result+="zugehriger Dateien";
          }
          break;
        case FileMemberHighlight::Functions:
          result+="Funktionen";
          break;
        case FileMemberHighlight::Variables:
          result+="Variablen";
          break;
        case FileMemberHighlight::Typedefs:
          result+="Typen-Definitionen";
          break;
        case FileMemberHighlight::Sequences:
          result+="Abfolgen";
          break;
        case FileMemberHighlight::Dictionaries:
          result+="Wrterbcher";
          break;
        case FileMemberHighlight::Enums:
          result+="Aufzhlungen";
          break;
        case FileMemberHighlight::EnumValues:
          result+="Aufzhlungs-Werte";
          break;
        case FileMemberHighlight::Defines:
          result+="Makros";
          break;
        case FileMemberHighlight::Total: // for completeness
          break;
      }
      result+=" mit verweisen auf ";
      if (extractAll)
        result+="bezugnehmenden Dateien:";
      else
        result+="die Dokumentation";
      return result;
    }
References FileMemberHighlight::All, Config_getBool, FileMemberHighlight::Defines, FileMemberHighlight::Dictionaries, FileMemberHighlight::Enums, FileMemberHighlight::EnumValues, FileMemberHighlight::Functions, FileMemberHighlight::Sequences, FileMemberHighlight::Total, FileMemberHighlight::Typedefs, and FileMemberHighlight::Variables.
trFileReference()
QCString TranslatorGerman::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 711 of file translator_de.h.
    {
      QCString result=fileName;
      result+="-Dateireferenz";
      return result;
    }
trFlowchart()
QCString TranslatorGerman::trFlowchart () inline override virtual
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Reimplemented from TranslatorAdapter_1_9_5.
Definition at line 2309 of file translator_de.h.
    { return "Fludiagram:"; }
trFriends()
QCString TranslatorGerman::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 671 of file translator_de.h.
    { return "Freundbeziehungen"; }
trFunctionAndProc()
QCString TranslatorGerman::trFunctionAndProc () inline override virtual
VHDL functions/procedures/processes.
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2152 of file translator_de.h.
    { return "Funktionen/Prozeduren/Prozesse"; }
trFunctionDocumentation()
QCString TranslatorGerman::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 578 of file translator_de.h.
    { return "Dokumentation der Funktionen"; }
trFunctions()
QCString TranslatorGerman::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 542 of file translator_de.h.
    { return "Funktionen"; }
trGeneratedAt()
QCString TranslatorGerman::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 605 of file translator_de.h.
    {
      QCString result="Erzeugt am "+date;
      if (!projName.isEmpty()) result+=" fr "+projName;
      result+=" von";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorGerman::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 247 of file translator_de.h.
    { QCString result="Automatisch erzeugt von Doxygen";
      if (!s.isEmpty()) result+=" fr "+s;
      result+=" aus dem Quellcode.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorGerman::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 648 of file translator_de.h.
    { return "Erzeugt von"; }
trGeneratedFromFiles()
QCString TranslatorGerman::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 858 of file translator_de.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="Die Dokumentation fr diese";
      switch(compType)
      {
        case ClassDef::Class:      result+=vhdlOpt?" Entwurfseinheiten":" Klasse"; break;
        case ClassDef::Struct:     result+=" Struktur"; break;
        case ClassDef::Union:      result+=" Variante"; break;
        case ClassDef::Interface:  result+=" Schnittstelle"; break;
        case ClassDef::Protocol:   result+="s Protokoll"; break;
        case ClassDef::Category:   result+=" Kategorie"; break;
        case ClassDef::Exception:  result+=" Ausnahme"; break;
        default: break;
      }
      result+=" wurde erzeugt aufgrund der Datei";
      if (single) result+=":"; else result+="en:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorGerman::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1804 of file translator_de.h.
    {
      // single is true implies a single file
      QCString result="Die Dokumentation fr ";
      switch(compType)
      {
        case ClassDef::Class:      result+="dieses Modul"; break;
        case ClassDef::Struct:     result+="diesen Typ"; break;
        case ClassDef::Union:      result+="diese Union"; break;
        case ClassDef::Interface:  result+="dieses Interface"; break;
        case ClassDef::Protocol:   result+="dieses Protokoll"; break;
        case ClassDef::Category:   result+="diese Kategorie"; break;
        case ClassDef::Exception:  result+="diese Ausnahme"; break;
        default: break;
      }
      if (single)
        result+=" wurde aus der folgenden Datei erzeugt:";
      else
        result+=" wurde aus den folgenden Dateien erzeugt:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorGerman::trGlobal (bool , bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1377 of file translator_de.h.
    {
      return createNoun(true, singular, "Global", ""); // FIXME
    }
References Translator::createNoun().
trGlobalNamespace()
QCString TranslatorGerman::trGlobalNamespace () inline override virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1868 of file translator_de.h.
    {
      return "Globaler Namensbereich";
    }
trGotoDocumentation()
QCString TranslatorGerman::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 950 of file translator_de.h.
    {
      return "gehe zur Dokumentation dieser Datei";
    }
trGotoGraphicalHierarchy()
QCString TranslatorGerman::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 990 of file translator_de.h.
    {
      return "gehe zur grafischen Darstellung der Klassenhierarchie";
    }
trGotoSourceCode()
QCString TranslatorGerman::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 944 of file translator_de.h.
    {
      return "gehe zum Quellcode dieser Datei";
    }
trGotoTextualHierarchy()
QCString TranslatorGerman::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 995 of file translator_de.h.
    {
      return "gehe zur textbasierten Darstellung der Klassenhierarchie";
    }
trGraphicalHierarchy()
QCString TranslatorGerman::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 985 of file translator_de.h.
    {
      return "Grafische Darstellung der Klassenhierarchie";
    }
trGroup()
QCString TranslatorGerman::trGroup (bool , bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1350 of file translator_de.h.
    {
      return createNoun(true, singular, "Gruppe", "n");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorGerman::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 466 of file translator_de.h.
    { return "Hierarchie-Verzeichnis"; }
trImplementedFromList()
QCString TranslatorGerman::trImplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1412 of file translator_de.h.
    {
      return "Implementiert " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedInList()
QCString TranslatorGerman::trImplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1420 of file translator_de.h.
    {
      return "Implementiert in " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImportant()
QCString TranslatorGerman::trImportant () inline override virtual
Reimplemented from TranslatorAdapter_1_11_0.
Definition at line 2630 of file translator_de.h.
    {
      return "Wichtig";
    }
trInclByDepGraph()
QCString TranslatorGerman::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 1102 of file translator_de.h.
    {
      return "Dieser Graph zeigt, welche Datei direkt oder "
             "indirekt diese Datei enthlt:";
    }
trInclDepGraph()
QCString TranslatorGerman::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 932 of file translator_de.h.
    {
      return "Include-Abhngigkeitsdiagramm fr "+fName+":";
    }
trIncludesFileIn()
QCString TranslatorGerman::trIncludesFileIn (const QCString & name) inline override virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1902 of file translator_de.h.
    {
      return "Include-Dateien in "+name;
    }
trIncludingInheritedMembers()
QCString TranslatorGerman::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 241 of file translator_de.h.
    { return " einschlielich aller geerbten Elemente."; }
trInheritedByList()
QCString TranslatorGerman::trInheritedByList (int numEntries) inline override virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 791 of file translator_de.h.
    {
      return "Basisklasse fr "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom()
QCString TranslatorGerman::trInheritedFrom (const QCString & members, const QCString & what) inline override virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 2005 of file translator_de.h.
    { return QCString(members)+" geerbt von "+what; }
trInheritsList()
QCString TranslatorGerman::trInheritsList (int numEntries) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 783 of file translator_de.h.
    {
      return "Abgeleitet von "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue()
QCString TranslatorGerman::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 974 of file translator_de.h.
    {
      return "Initialisierung:";
    }
trInstanceMethods()
QCString TranslatorGerman::trInstanceMethods () inline override virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2057 of file translator_de.h.
    {
      return "Instanzmethoden";
    }
trInterfaces()
QCString TranslatorGerman::trInterfaces () inline override virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2074 of file translator_de.h.
    { return "Exportierte Interfaces"; }
trInvariant()
QCString TranslatorGerman::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 968 of file translator_de.h.
    {
      return "Invariante";
    }
trISOLang()
QCString TranslatorGerman::trISOLang () inline override virtual
Implements Translator.
Definition at line 172 of file translator_de.h.
    {
      return "de";
    }
trLegend()
QCString TranslatorGerman::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1196 of file translator_de.h.
    {
      return "Legende";
    }
trLegendDocs()
QCString TranslatorGerman::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1126 of file translator_de.h.
    {
      return
        "Diese Seite erklrt die Interpretation der von doxygen "
        "erzeugten Graphen.<p>\n"
        "Beispiel:\n"
        "\\code\n"
        "/*! Wegen Verkrzung unsichtbare Klasse */\n"
        "class Invisible { };\n\n"
        "/*! Klasse verkrzt dargestellt, Vererbungsbeziehung ist versteckt */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Nicht mit doxygen-Kommentaren dokumentierte Klasse */\n"
        "class Undocumented { };\n\n"
        "/*! Mithilfe ffentlicher Vererbung vererbte Klasse */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Eine Template-Klasse */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Mithilfe geschtzter Vererbung vererbte Klasse */\n"
        "class ProtectedBase { };\n\n"
        "/*! Mithilfe privater Vererbung vererbte Klasse */\n"
        "class PrivateBase { };\n\n"
        "/*! Von der Klasse Inherited benutzte Klasse */\n"
        "class Used { };\n\n"
        "/*! Superklasse, die von mehreren anderen Klassen erbt */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dies liefert den folgenden Graphen:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Die Rechtecke in obigem Graphen bedeuten:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Ein grau geflltes Rechteck stellt die Struktur oder "
        "Klasse dar, fr die der Graph erzeugt wurde.</li>\n"
        "<li>Ein Rechteck mit schwarzem Rahmen kennzeichnet eine dokumentierte "
        "Struktur oder Klasse.</li>\n"
        "<li>Ein Rechteck mit grauem Rahmen kennzeichnet eine undokumentierte "
        "Struktur oder Klasse.</li>\n"
        "<li>Ein Rechteck mit rotem Rahmen kennzeichnet eine dokumentierte "
        "Struktur oder Klasse, fr die nicht alle Vererbungs-/"
        "Enthaltenseinsbeziehungen dargestellt werden. Ein Graph wird gekrzt, "
        "wenn er nicht in die angegebenen Schranken passt.</li>\n"
        "</ul>\n"
        "<p>\n"
        "Die Pfeile bedeuten:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Ein blauer Pfeil stellt eine ffentliche Vererbungsbeziehung "
        "zwischen zwei Klassen dar.</li>\n"
        "<li>Ein dunkelgrner Pfeil stellt geschtzte Vererbung dar.</li>\n"
        "<li>Ein dunkelroter Pfeil stellt private Vererbung dar.</li>\n"
        "<li>Ein gestrichelter violetter Pfeil bedeutet, dass eine Klasse in "
        "einer anderen enthalten ist oder von einer anderen benutzt wird. Am "
        "Pfeil stehen die Variable(n), mit deren Hilfe auf die Struktur oder "
        "Klasse an der Pfeilspitze zugegriffen werden kann.</li>\n"
        "<li>Ein gestrichelter gelber Pfeil kennzeichnet eine Verknpfung "
        "zwischen einer Template-Instanz und der Template-Klasse von welcher "
        "es abstammt. Neben dem Pfeil sind die Template-Parameter aufgefhrt.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorGerman::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 1118 of file translator_de.h.
    {
      return "Erklrung des Graphen";
    }
trListOfAllMembers()
QCString TranslatorGerman::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 229 of file translator_de.h.
    { return "Aufstellung aller Elemente"; }
trLoading()
QCString TranslatorGerman::trLoading () inline override virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1862 of file translator_de.h.
    {
      return "Lade ...";
    }
trMainPage()
QCString TranslatorGerman::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 889 of file translator_de.h.
    { return "Hauptseite"; }
trMember()
QCString TranslatorGerman::trMember (bool , bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1368 of file translator_de.h.
    {
      return createNoun(true, singular, "Element", "e");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorGerman::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 212 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentation der Felder";
      }
      else
      {
        return "Dokumentation der Datenelemente";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorGerman::trMemberEnumerationDocumentation () inline override virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 204 of file translator_de.h.
    { return "Dokumentation der Aufzhlungstypen"; }
trMemberFunctionDocumentation()
QCString TranslatorGerman::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 208 of file translator_de.h.
    { return "Dokumentation der Elementfunktionen"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorGerman::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1656 of file translator_de.h.
    { return "Elementfunktionen/Unterroutinen-Dokumentation"; }
trMemberList()
QCString TranslatorGerman::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 233 of file translator_de.h.
    { return "Elementverzeichnis"; }
trMemberTypedefDocumentation()
QCString TranslatorGerman::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 200 of file translator_de.h.
    { return "Dokumentation der benutzerdefinierten Datentypen"; }
trMethodDocumentation()
QCString TranslatorGerman::trMethodDocumentation () inline override virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2064 of file translator_de.h.
    {
      return "Methodendokumentation";
    }
trModule()
QCString TranslatorGerman::trModule (bool , bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1796 of file translator_de.h.
    {
      return createNoun(true, singular, "Modul", "e");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorGerman::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 489 of file translator_de.h.
    { return "Modul-Dokumentation"; }
trModuleIndex()
QCString TranslatorGerman::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 460 of file translator_de.h.
    { return "Modul-Verzeichnis"; }
trModuleMembersDescriptionTotal()
QCString TranslatorGerman::trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) inline override virtual
Reimplemented from TranslatorAdapter_1_9_8.
Definition at line 2565 of file translator_de.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result = "Zusammengefat ";
      QCString singularResult = result + "bezieht sich das Modul auf: ";
      QCString pluralResult   = result + "beziehen sich die Module auf: ";
      switch (hl)
      {
        case ModuleMemberHighlight::All:
          if (!extractAll)
              singularResult += "die verlinkte Modul-Beschreibung fr jedes Mitglied:"; else
              pluralResult   += "die verlinkten Modul-Beschreibungen aller Mitglieder:";
          break;
        case ModuleMemberHighlight::Functions:
          if (!extractAll)
              singularResult += "die verlinkte Modul-Beschreibung fr jede Funktion:"; else
              pluralResult   += "die verlinkten Modul-Beschreibungen aller Funktionen:";
          break;
        case ModuleMemberHighlight::Variables:
          if (!extractAll)
              singularResult += "die verlinkte Modul-Beschreibung fr jede Variable:"; else
              pluralResult   += "die verlinkten Modul-Beschreibungen fr alle Variablen:";
          break;
        case ModuleMemberHighlight::Typedefs:
          if (!extractAll)
              singularResult += "die verlinkte Modul-Beschreibung fr jede Typ-Definition:"; else
              pluralResult   += "die verlinkten Modul-Beschreibungen fr jeden Definitions-Typen:";
          break;
        case ModuleMemberHighlight::Enums:
          if (!extractAll)
              singularResult += "die verlinkte Modul-Beschreibung fr jede Aufzhlung:"; else
              pluralResult   += "die verlinkten Modul-Beschreibungen aller Aufzhlungen:";
          break;
        case ModuleMemberHighlight::EnumValues:
          if (!extractAll)
              singularResult += "die verlinkte Modul-Beschreibung fr jedem Aufzhlungswert:"; else
              pluralResult   += "die verlinkten Modul-Beschreibungen aller Aufzhlungswerte:";
          break;
        case ModuleMemberHighlight::Total: // for completeness
          break;
      }
      if (!extractAll)
        result = singularResult; else
        result = pluralResult;
      return result;
    }
References ModuleMemberHighlight::All, Config_getBool, ModuleMemberHighlight::Enums, ModuleMemberHighlight::EnumValues, ModuleMemberHighlight::Functions, ModuleMemberHighlight::Total, ModuleMemberHighlight::Typedefs, and ModuleMemberHighlight::Variables.
trModuleReference()
QCString TranslatorGerman::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1758 of file translator_de.h.
    {
      QCString result=namespaceName;
      result+="-Modul-Referenz";
      return result;
    }
trModules()
QCString TranslatorGerman::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 271 of file translator_de.h.
    { return "Module"; }
trModulesDescription()
QCString TranslatorGerman::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 448 of file translator_de.h.
    { return "Hier folgt die Aufzhlung aller Module:"; }
trModulesIndex()
QCString TranslatorGerman::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1789 of file translator_de.h.
    { return "Modul-Index"; }
trModulesList()
QCString TranslatorGerman::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1723 of file translator_de.h.
    { return "Modulliste"; }
trModulesListDescription()
QCString TranslatorGerman::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1727 of file translator_de.h.
    {
      QCString result="Hier folgt eine Liste aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Module mit ihren Kurzbeschreibungen:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorGerman::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1770 of file translator_de.h.
    {
      QCString result="Hier folgt eine Liste aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Modulelemente mit Links ";
      if (extractAll)
      {
        result+="zur Moduldokumentation fr jedes Element:";
      }
      else
      {
        result+="zu den Modulen, zu denen sie gehren:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorGerman::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1766 of file translator_de.h.
    { return "Modul-Elemente"; }
trMonth()
QCString TranslatorGerman::trMonth (int month, bool , bool full) inline override virtual
Implements Translator.
Definition at line 1944 of file translator_de.h.
    {
      static const char *months_short[] = { "Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez" };
      static const char *months_full[]  = { "Januar", "Februar", "Mrz", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore()
QCString TranslatorGerman::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 225 of file translator_de.h.
    { return "Mehr ..."; }
trNamespace()
QCString TranslatorGerman::trNamespace (bool , bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1341 of file translator_de.h.
    {
      return createNoun(true, singular, "Namensbereich", "e");
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorGerman::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 838 of file translator_de.h.
    { return "Dokumentation der Namensbereiche"; }
trNamespaceIndex()
QCString TranslatorGerman::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 832 of file translator_de.h.
    { return "Verzeichnis der Namensbereiche"; }
trNamespaceList()
QCString TranslatorGerman::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 656 of file translator_de.h.
    { return "Liste aller Namensbereiche"; }
trNamespaceListDescription()
QCString TranslatorGerman::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 660 of file translator_de.h.
    {
      QCString result="Liste aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Namensbereiche mit Kurzbeschreibung:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorGerman::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 817 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Namensbereichselemente mit Verweisen auf ";
      if (extractAll)
        result+="die Namensbereichsdokumentation fr jedes Element:";
      else
        result+="die zugehrigen Dateien:";
      return result;
    }
trNamespaceMembers()
QCString TranslatorGerman::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 813 of file translator_de.h.
    { return "Elemente eines Namensbereiches"; }
trNamespaceMembersDescriptionTotal()
QCString TranslatorGerman::trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) inline override virtual
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2490 of file translator_de.h.
    {
      bool extractAll = Config_getBool(EXTRACT_ALL);
      QCString result           = "Hier folgt eine Liste mit Verweisen auf die Namensraum-Dokumentation fr ";
      QCString result_singular1 = result + "jede dokumentierte";
      QCString result_singular2 = result + "jedes dokumentiertes";
      QCString result_singular3 = result + "jeder dokumentierten";
      QCString result_plural    = result + "alle dokumentierten";
      QCString singularResult = "";
      QCString pluralResult   = "";
      switch (hl)
      {
        case NamespaceMemberHighlight::All:
          singularResult = result_singular2 + "Mitglied";
          pluralResult   = result_plural    + "Mitglieder";
          break;
        case NamespaceMemberHighlight::Functions:
          singularResult = result_singular1 + "Funktion";
          pluralResult   = result_plural    + "Funktionen";
          break;
        case NamespaceMemberHighlight::Variables:
          singularResult = result_singular1 + "Variable";
          pluralResult   = result_plural    + "Variablen";
          break;
        case NamespaceMemberHighlight::Typedefs:
          singularResult = result_singular1 + "Typ-Definition";
          pluralResult   = result_plural    + "Typen-Defintionen";
          break;
        case NamespaceMemberHighlight::Sequences:
          singularResult = result_singular1 + "Abfolge";
          pluralResult   = result_plural    + "Abfolgen";
          break;
        case NamespaceMemberHighlight::Dictionaries:
          singularResult = result_singular2 + "Wrterbuch";
          pluralResult   = result_plural    + "Wrterbcher";
          break;
        case NamespaceMemberHighlight::Enums:
          singularResult = result_singular3 + "Aufzhlung";
          pluralResult   = result_plural    + "Aufzhlungen";
          break;
        case NamespaceMemberHighlight::EnumValues:
          singularResult = result_singular3 + "Aufzhlung";
          pluralResult   = result_plural    + "Aufzhlungen";
          break;
        case NamespaceMemberHighlight::Total: // for completeness
          break;
      }
      // TODO: plural form !!!
      if (!extractAll)
        result += singularResult + " mit Verweise auf die Namensraum-Dokumentation:"; else
        result += singularResult + " mit Verweise auf dem sich beziehenden Namensraum:";
      return result;
    }
References NamespaceMemberHighlight::All, Config_getBool, NamespaceMemberHighlight::Dictionaries, NamespaceMemberHighlight::Enums, NamespaceMemberHighlight::EnumValues, NamespaceMemberHighlight::Functions, NamespaceMemberHighlight::Sequences, NamespaceMemberHighlight::Total, NamespaceMemberHighlight::Typedefs, and NamespaceMemberHighlight::Variables.
trNamespaceReference()
QCString TranslatorGerman::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 719 of file translator_de.h.
    {
      QCString result=namespaceName;
      result+="-Namensbereichsreferenz";
      return result;
    }
trNamespaces()
QCString TranslatorGerman::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 848 of file translator_de.h.
    { return "Namensbereiche"; }
trNoMatches()
QCString TranslatorGerman::trNoMatches () inline override virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1880 of file translator_de.h.
    {
      return "Keine Treffer";
    }
trNote()
QCString TranslatorGerman::trNote () inline override virtual
Implements Translator.
Definition at line 1010 of file translator_de.h.
    {
      return "Zu beachten";
    }
trOverloadText()
QCString TranslatorGerman::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1628 of file translator_de.h.
    {
       return "Dies ist eine berladene Methode, die der Bequemlichkeit "
              "wegen bereitgestellt wird. Sie unterscheidet sich von der "
              "obigen Funktion nur in den Argumenten die sie untersttzt.";
    }
trPackage()
QCString TranslatorGerman::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1251 of file translator_de.h.
    {
      return "Paket "+name;
    }
trPackageAttribs()
QCString TranslatorGerman::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1501 of file translator_de.h.
    {
      return "Paketattribute";
    }
trPackageFunctions()
QCString TranslatorGerman::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1481 of file translator_de.h.
    {
      return "Paketfunktionen";
    }
trPackageList()
QCString TranslatorGerman::trPackageList () inline override virtual
Reimplemented from TranslatorAdapter_1_9_4.
Definition at line 2299 of file translator_de.h.
    { return "Paket-Liste"; }
trPackageListDescription()
QCString TranslatorGerman::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1258 of file translator_de.h.
    {
      return "Hier folgen die Pakete mit einer Kurzbeschreibung (wenn verfgbar):";
    }
trPackageMembers()
QCString TranslatorGerman::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1485 of file translator_de.h.
    {
      return "Paketelemente";
    }
trPackages()
QCString TranslatorGerman::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1264 of file translator_de.h.
    {
      return "Pakete";
    }
trPackageTypes()
QCString TranslatorGerman::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1473 of file translator_de.h.
    {
      return "Pakettypen";
    }
trPage()
QCString TranslatorGerman::trPage (bool , bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1359 of file translator_de.h.
    {
      return createNoun(true, singular, "Seite", "n");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorGerman::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 895 of file translator_de.h.
    { return "S."; }
trPageIndex()
QCString TranslatorGerman::trPageIndex () inline override virtual
Implements Translator.
Definition at line 1000 of file translator_de.h.
    {
      return "Seitenindex";
    }
trPanelSynchronisationTooltip()
QCString TranslatorGerman::trPanelSynchronisationTooltip (bool enable) inline override virtual
Used as a tooltip for the toggle button thatappears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 2022 of file translator_de.h.
    {
      QCString opt = enable ? "einzuschalten" : "auszuschalten";
      return "Klicken um Panelsynchronisation "+opt;
    }
trParameters()
QCString TranslatorGerman::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 640 of file translator_de.h.
    { return "Parameter"; }
trPostcondition()
QCString TranslatorGerman::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 962 of file translator_de.h.
    {
      return "Nachbedingung";
    }
trPrecondition()
QCString TranslatorGerman::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 956 of file translator_de.h.
    {
      return "Vorbedingung";
    }
trPrivateAttribs()
QCString TranslatorGerman::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 1057 of file translator_de.h.
    {
      return "Private Attribute";
    }
trPrivateMembers()
QCString TranslatorGerman::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 747 of file translator_de.h.
    { return "Private Methoden"; }
trPrivateSlots()
QCString TranslatorGerman::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 750 of file translator_de.h.
    { return "Private Slots"; }
trPrivateTypes()
QCString TranslatorGerman::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 1052 of file translator_de.h.
    {
      return "Private Typen";
    }
trProperties()
QCString TranslatorGerman::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1222 of file translator_de.h.
    {
      return "Propertys";
    }
trPropertyDocumentation()
QCString TranslatorGerman::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1228 of file translator_de.h.
    {
      return "Dokumentation der Propertys";
    }
trProtectedAttribs()
QCString TranslatorGerman::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 1042 of file translator_de.h.
    {
      return "Geschtzte Attribute";
    }
trProtectedMembers()
QCString TranslatorGerman::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 738 of file translator_de.h.
    { return "Geschtzte Methoden"; }
trProtectedSlots()
QCString TranslatorGerman::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 741 of file translator_de.h.
    { return "Geschtzte Slots"; }
trProtectedTypes()
QCString TranslatorGerman::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 1037 of file translator_de.h.
    {
      return "Geschtzte Typen";
    }
trProvidedByCategory()
QCString TranslatorGerman::trProvidedByCategory () inline override virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2032 of file translator_de.h.
    {
      return "Bestandteil der Kategorie @0.";
    }
trPublicAttribs()
QCString TranslatorGerman::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 1020 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenfelder";
      }
      else
      {
        return "ffentliche Attribute";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorGerman::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 726 of file translator_de.h.
    { return "ffentliche Methoden"; }
trPublicSlots()
QCString TranslatorGerman::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 729 of file translator_de.h.
    { return "ffentliche Slots"; }
trPublicTypes()
QCString TranslatorGerman::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 1015 of file translator_de.h.
    {
      return "ffentliche Typen";
    }
trReferencedBy()
QCString TranslatorGerman::trReferencedBy () inline override virtual
Implements Translator.
Definition at line 1087 of file translator_de.h.
    {
      return "Wird benutzt von";
    }
trReferenceManual()
QCString TranslatorGerman::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 518 of file translator_de.h.
    { return "Nachschlagewerk"; }
trReferences()
QCString TranslatorGerman::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1400 of file translator_de.h.
    {
      return "Benutzt";
    }
trReimplementedFromList()
QCString TranslatorGerman::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 799 of file translator_de.h.
    {
      return "Erneute Implementation von "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorGerman::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 807 of file translator_de.h.
    {
      return "Erneute Implementation in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorGerman::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 681 of file translator_de.h.
    { return "Freundbeziehungen und Funktionsdokumentation"; }
trRelatedFunctions()
QCString TranslatorGerman::trRelatedFunctions () inline override virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 184 of file translator_de.h.
    { return "Verwandte Funktionen"; }
trRelatedPages()
QCString TranslatorGerman::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 322 of file translator_de.h.
    { return "Zustzliche Informationen"; }
trRelatedPagesDescription()
QCString TranslatorGerman::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 444 of file translator_de.h.
    { return "Hier folgt eine Liste mit zusammengehrigen Themengebieten:"; }
trRelatedSubscript()
QCString TranslatorGerman::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 188 of file translator_de.h.
    { return "(Es handelt sich hierbei nicht um Elementfunktionen.)"; }
trRelatedSymbolDocumentation()
QCString TranslatorGerman::trRelatedSymbolDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes.
Supersedes trRelatedFunctionDocumentation
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2339 of file translator_de.h.
    { return "Freunde und bezugnehmende Symbol-Dokumentation"; }
trRelatedSymbols()
QCString TranslatorGerman::trRelatedSymbols () inline override virtual
Please translate also updated body of the method trMemberFunctionDocumentation(), now better adapted for VHDL sources documentation.
used in the compound documentation before a list of related symbols.
Supersedes trRelatedFunctions
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2324 of file translator_de.h.
    { return "Zugehrige Symbole"; }
trRelatedSymbolsSubscript()
QCString TranslatorGerman::trRelatedSymbolsSubscript () inline override virtual
subscript for the related symbols
Supersedes trRelatedSubscript
Reimplemented from TranslatorAdapter_1_9_6.
Definition at line 2331 of file translator_de.h.
    { return "(Hinweis: diese Symbole sind keine Funktionen.)"; }
trRemarks()
QCString TranslatorGerman::trRemarks () inline override virtual
Implements Translator.
Definition at line 1092 of file translator_de.h.
    {
      return "Bemerkungen";
    }
trReturns()
QCString TranslatorGerman::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 632 of file translator_de.h.
    { return "Rckgabe"; }
trReturnValues()
QCString TranslatorGerman::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 884 of file translator_de.h.
    { return "Rckgabewerte"; }
trRTFansicp()
QCString TranslatorGerman::trRTFansicp () inline override virtual
Used as ansicpg for RTF file. See translator_en.h for details.
Implements Translator.
Definition at line 1296 of file translator_de.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorGerman::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1304 of file translator_de.h.
    {
      return "0";
    }
trRTFGeneralIndex()
QCString TranslatorGerman::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1310 of file translator_de.h.
    {
      return "Index";
    }
trRTFTableOfContents()
QCString TranslatorGerman::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1432 of file translator_de.h.
    {
      return "Inhaltsverzeichnis";
    }
trSearch()
QCString TranslatorGerman::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 330 of file translator_de.h.
    { return "Suchen"; }
trSearching()
QCString TranslatorGerman::trSearching () inline override virtual
Message shown while searching
Implements Translator.
Definition at line 1874 of file translator_de.h.
    {
      return "Suche ...";
    }
trSearchMatches()
QCString TranslatorGerman::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1569 of file translator_de.h.
    {
      return "Treffer:";
    }
trSearchResults()
QCString TranslatorGerman::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1550 of file translator_de.h.
    {
      if (numDocuments==0)
      {
        return "Es wurden keine Dokumente zu Ihrer Suchanfrage gefunden.";
      }
      else if (numDocuments==1)
      {
        return "Es wurde <b>1</b> Dokument zu Ihrer Suchanfrage gefunden.";
      }
      else
      {
        return "Es wurden <b>$num</b> Dokumente zu Ihrer Suchanfrage "
           "gefunden. Die besten Treffer werden zuerst angezeigt.";
      }
    }
trSearchResultsTitle()
QCString TranslatorGerman::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1538 of file translator_de.h.
    {
      return "Suchergebnisse";
    }
trSeeAlso()
QCString TranslatorGerman::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 636 of file translator_de.h.
    { return "Siehe auch"; }
trServiceGeneratedFromFiles()
QCString TranslatorGerman::trServiceGeneratedFromFiles (bool single) inline override virtual
UNO IDL service page.
Implements Translator.
Definition at line 2110 of file translator_de.h.
    {
      QCString result="Die Dokumentation fr diesen Dienst "
                                "wurde generiert aus ";
      if (single) result+="folgender Datei: "; else result+="folgenden Dateien: ";
      return result;
    }
trServiceReference()
QCString TranslatorGerman::trServiceReference (const QCString & sName) inline override virtual
UNO IDL service page title.
Implements Translator.
Definition at line 2094 of file translator_de.h.
    {
      QCString result=sName;
      result+=" Dienstreferenz";
      return result;
    }
trServices()
QCString TranslatorGerman::trServices () inline override virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2078 of file translator_de.h.
    { return "Eingebundene Dienste"; }
trSignals()
QCString TranslatorGerman::trSignals () inline override virtual
Implements Translator.
Definition at line 732 of file translator_de.h.
    { return "Signale"; }
trSince()
QCString TranslatorGerman::trSince () inline override virtual
Implements Translator.
Definition at line 1108 of file translator_de.h.
    {
      return "Seit";
    }
trSingletonGeneratedFromFiles()
QCString TranslatorGerman::trSingletonGeneratedFromFiles (bool single) inline override virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 2119 of file translator_de.h.
    {
      QCString result="Die Dokumentation fr diesen Singleton wurde generiert aus ";
      if (single) result+="folgender Datei:"; else result+="folgenden Dateien:";
      return result;
    }
trSingletonReference()
QCString TranslatorGerman::trSingletonReference (const QCString & sName) inline override virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 2102 of file translator_de.h.
    {
      QCString result=sName;
      result+=" Singleton-Referenz";
      return result;
    }
trSourceFile()
QCString TranslatorGerman::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1580 of file translator_de.h.
    {
      return filename + " Quellcode";
    }
trStaticPackageAttribs()
QCString TranslatorGerman::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1509 of file translator_de.h.
    {
      return "Statische Paketattribute";
    }
trStaticPackageFunctions()
QCString TranslatorGerman::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1493 of file translator_de.h.
    {
      return "Statische Paketfunktionen";
    }
trStaticPrivateAttribs()
QCString TranslatorGerman::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 1062 of file translator_de.h.
    {
      return "Statische, private Attribute";
    }
trStaticPrivateMembers()
QCString TranslatorGerman::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 753 of file translator_de.h.
    { return "Private, statische Methoden"; }
trStaticProtectedAttribs()
QCString TranslatorGerman::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 1047 of file translator_de.h.
    {
      return "Statische, geschtzte Attribute";
    }
trStaticProtectedMembers()
QCString TranslatorGerman::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 744 of file translator_de.h.
    { return "Geschtzte, statische Methoden"; }
trStaticPublicAttribs()
QCString TranslatorGerman::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 1032 of file translator_de.h.
    {
      return "Statische ffentliche Attribute";
    }
trStaticPublicMembers()
QCString TranslatorGerman::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 735 of file translator_de.h.
    { return "ffentliche, statische Methoden"; }
trSubprogram()
QCString TranslatorGerman::trSubprogram (bool , bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1840 of file translator_de.h.
    {
      return createNoun(true, singular, "Unterprogramm", "e");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorGerman::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1713 of file translator_de.h.
    { return "Funktionen/Unterroutinen-Dokumentation"; }
trSubprograms()
QCString TranslatorGerman::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1707 of file translator_de.h.
    { return "Funktionen/Unterroutinen"; }
trTemplateParameters()
QCString TranslatorGerman::trTemplateParameters () inline override virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1982 of file translator_de.h.
    { return "Template-Parameter"; }
trTest()
QCString TranslatorGerman::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1206 of file translator_de.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorGerman::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1212 of file translator_de.h.
    {
      return "Test-Liste";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorGerman::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 237 of file translator_de.h.
    { return "Vollstndige Aufstellung aller Elemente fr"; }
trTodo()
QCString TranslatorGerman::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1072 of file translator_de.h.
    {
      return "Noch zu erledigen";
    }
trTodoList()
QCString TranslatorGerman::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 1078 of file translator_de.h.
    {
      return "Ausstehende Aufgaben";
    }
trTopicDocumentation()
QCString TranslatorGerman::trTopicDocumentation () inline override virtual
Reimplemented from TranslatorAdapter_1_9_8.
Definition at line 2557 of file translator_de.h.
    { return "Themen Dokumentation"; }
trTopicIndex()
QCString TranslatorGerman::trTopicIndex () inline override virtual
Reimplemented from TranslatorAdapter_1_9_8.
Definition at line 2561 of file translator_de.h.
    { return "Themen Index"; }
trTopicList()
QCString TranslatorGerman::trTopicList () inline override virtual
Reimplemented from TranslatorAdapter_1_9_8.
Definition at line 2559 of file translator_de.h.
    { return "Themen-Liste"; }
trTopicListDescription()
QCString TranslatorGerman::trTopicListDescription () inline override virtual
Reimplemented from TranslatorAdapter_1_9_8.
Definition at line 2563 of file translator_de.h.
    { return "Es folgt eine Liste der Themen mit einer Kurzbeschreibung"; }
trTopics()
QCString TranslatorGerman::trTopics () inline override virtual
Reimplemented from TranslatorAdapter_1_9_8.
Definition at line 2555 of file translator_de.h.
    { return "Themen"; }
trType()
QCString TranslatorGerman::trType (bool , bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1831 of file translator_de.h.
    {
      return createNoun(true, singular, "Typ", "en");
    }
References Translator::createNoun().
Referenced by trCompoundType().
trTypeConstraints()
QCString TranslatorGerman::trTypeConstraints () inline override virtual
C# Type Constraint list
Implements Translator.
Definition at line 1846 of file translator_de.h.
    {
      return "Type Constraints";
    }
trTypedefDocumentation()
QCString TranslatorGerman::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 566 of file translator_de.h.
    { return "Dokumentation der benutzerdefinierten Typen"; }
trTypedefs()
QCString TranslatorGerman::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 530 of file translator_de.h.
    { return "Typdefinitionen"; }
trTypeDocumentation()
QCString TranslatorGerman::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1701 of file translator_de.h.
    { return "Datentyp-Dokumentation"; }
trVariableDocumentation()
QCString TranslatorGerman::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 584 of file translator_de.h.
    { return "Variablen-Dokumentation"; }
trVariables()
QCString TranslatorGerman::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 548 of file translator_de.h.
    { return "Variablen"; }
trVersion()
QCString TranslatorGerman::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 624 of file translator_de.h.
    { return "Version"; }
trVhdlType()
QCString TranslatorGerman::trVhdlType (VhdlSpecifier type, bool single) inline override virtual
VHDL type.
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2155 of file translator_de.h.
    {
      switch(type)
      {
        case VhdlSpecifier::LIBRARY:
          if (single) return "Bibliothek";
          else        return "Bibliotheken";
        case VhdlSpecifier::PACKAGE:
          if (single) return "Paket";
          else        return "Pakete";
        case VhdlSpecifier::SIGNAL:
          if (single) return "Signal";
          else        return "Signale";
        case VhdlSpecifier::COMPONENT:
          if (single) return "Komponente";
          else        return "Komponenten";
        case VhdlSpecifier::CONSTANT:
          if (single) return "Konstante";
          else        return "Konstanten";
        case VhdlSpecifier::ENTITY:
          if (single) return "Entwurfseinheit";
          else        return "Entwurfseinheiten";
        case VhdlSpecifier::TYPE:
          if (single) return "Typ";
          else        return "Typen";
        case VhdlSpecifier::SUBTYPE:
          if (single) return "Subtyp";
          else        return "Subtypen";
        case VhdlSpecifier::FUNCTION:
          if (single) return "Funktion";
          else        return "Funktionen";
        case VhdlSpecifier::RECORD:
          if (single) return "Datenstruktur";
          else        return "Datenstrukturen";
        case VhdlSpecifier::PROCEDURE:
          if (single) return "Prozedur";
          else        return "Prozeduren";
        case VhdlSpecifier::ARCHITECTURE:
          if (single) return "Architektur";
          else        return "Architekturen";
        case VhdlSpecifier::ATTRIBUTE:
          if (single) return "Attribut";
          else        return "Attribute";
        case VhdlSpecifier::PROCESS:
          if (single) return "Prozess";
          else        return "Prozesse";
        case VhdlSpecifier::PORT:
          if (single) return "Schnittstelle";
          else        return "Schnittstellen";
        case VhdlSpecifier::USE:
          if (single) return "Use Klausel";
          else        return "Use Klauseln";
        case VhdlSpecifier::GENERIC:
          if (single) return "Parameter";
          else        return "Parameter";
        case VhdlSpecifier::PACKAGE_BODY:
          return "Paketkrper";
        case VhdlSpecifier::UNITS:
          return "Einheiten";
        case VhdlSpecifier::SHAREDVARIABLE:
          if (single) return "Geteilte Variable";
          else        return "Geteilte Variablen";
        case VhdlSpecifier::VFILE:
          if (single) return "Datei";
          else        return "Dateien";
        case VhdlSpecifier::GROUP:
          if (single) return "Gruppe";
          else        return "Gruppen";
        case VhdlSpecifier::INSTANTIATION:
          if (single) return "Instanziierung";
          else        return "Instanziierungen";
        case VhdlSpecifier::ALIAS:
          if (single) return "Alias";
          else        return "Aliase";
        case VhdlSpecifier::CONFIG:
          if (single) return "Konfiguration";
          else        return "Konfigurationen";
        case VhdlSpecifier::MISCELLANEOUS:
          return "Verschiedenes";
        case VhdlSpecifier::UCF_CONST:
          return "Constraints";
        default:
          return "Klasse";
      }
    }
References ALIAS, ARCHITECTURE, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, ENTITY, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PACKAGE, PACKAGE_BODY, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, TYPE, UCF_CONST, UNITS, USE, and VFILE.
trWarning()
QCString TranslatorGerman::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 620 of file translator_de.h.
    { return "Warnung"; }
trWriteList()
QCString TranslatorGerman::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 759 of file translator_de.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" und ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_de.h