Doxygen: ConceptDefAliasImpl Class Reference
ConceptDefAliasImpl Class Reference
Public Member Functions
ConceptDefAliasImpl (const Definition *newScope, const ConceptDef *cd)
~ConceptDefAliasImpl () override
const ConceptDef * getCdAlias () const
DefType definitionType () const override
CodeSymbolType codeSymbolType () const override
QCString getOutputFileBase () const override
QCString getReference () const override
bool isReference () const override
bool hasDetailedDescription () const override
QCString displayName (bool includeScope=true) const override
const IncludeInfo * includeInfo () const override
ArgumentList getTemplateParameterList () const override
QCString anchor () const override
bool isLinkableInProject () const override
bool isLinkable () const override
QCString initializer () const override
const NamespaceDef * getNamespaceDef () const override
const FileDef * getFileDef () const override
const ModuleDef * getModuleDef () const override
QCString title () const override
void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const override
int groupId () const override
Public Member Functions inherited from DefinitionAliasMixin< ConceptDef >
DefinitionAliasMixin (const Definition *scope, const Definition *alias)
~DefinitionAliasMixin () override=default
void init ()
void deinit ()
bool isAlias () const override
const QCString & name () const override
bool isAnonymous () const override
const QCString & localName () const override
QCString qualifiedName () const override
QCString symbolName () const override
QCString getSourceFileBase () const override
QCString getSourceAnchor () const override
QCString documentation () const override
int docLine () const override
QCString docFile () const override
QCString briefDescription (bool abbreviate=FALSE) const override
QCString briefDescriptionAsTooltip () const override
int briefLine () const override
QCString inbodyDocumentation () const override
QCString inbodyFile () const override
int inbodyLine () const override
QCString briefFile () const override
QCString getDefFileName () const override
QCString getDefFileExtension () const override
int getDefLine () const override
int getDefColumn () const override
bool hasDocumentation () const override
bool hasUserDocumentation () const override
bool isVisibleInProject () const override
bool isVisible () const override
bool isHidden () const override
bool isArtificial () const override
bool isExported () const override
QCString getReference () const override
bool isReference () const override
QCString externalReference (const QCString &relPath) const override
int getStartDefLine () const override
int getStartBodyLine () const override
int getEndBodyLine () const override
const FileDef * getBodyDef () const override
SrcLangExt getLanguage () const override
const GroupList & partOfGroups () const override
bool isLinkableViaGroup () const override
const RefItemVector & xrefListItems () const override
const Definition * findInnerCompound (const QCString &name) const override
Definition * getOuterScope () const override
const MemberVector & getReferencesMembers () const override
const MemberVector & getReferencedByMembers () const override
bool hasSections () const override
bool hasSources () const override
bool hasBriefDescription () const override
QCString id () const override
const SectionRefs & getSectionRefs () const override
QCString navigationPathAsString () const override
QCString pathFragment () const override
Public Member Functions inherited from ConceptDef
Public Member Functions inherited from Definition
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Protected Member Functions inherited from DefinitionAliasMixin< ConceptDef >
const Definition * getAlias () const
const Definition * getScope () const
Detailed Description
Definition at line 99 of file conceptdef.cpp.
Constructor & Destructor Documentation
ConceptDefAliasImpl()
ConceptDefAliasImpl::ConceptDefAliasImpl (const Definition * newScope, const ConceptDef * cd) inline
Definition at line 102 of file conceptdef.cpp.
      : DefinitionAliasMixin(newScope,cd) { init(); }
References DefinitionAliasMixin< ConceptDef >::DefinitionAliasMixin(), and DefinitionAliasMixin< ConceptDef >::init().
~ConceptDefAliasImpl()
ConceptDefAliasImpl::~ConceptDefAliasImpl () inline override
Definition at line 104 of file conceptdef.cpp.
{ deinit(); }
References DefinitionAliasMixin< ConceptDef >::deinit().
Member Function Documentation
anchor()
QCString ConceptDefAliasImpl::anchor () const inline override virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 126 of file conceptdef.cpp.
    { return getCdAlias()->anchor(); }
References Definition::anchor(), and getCdAlias().
codeSymbolType()
CodeSymbolType ConceptDefAliasImpl::codeSymbolType () const inline override virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 110 of file conceptdef.cpp.
    { return getCdAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getCdAlias().
definitionType()
DefType ConceptDefAliasImpl::definitionType () const inline override virtual
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Definition at line 109 of file conceptdef.cpp.
{ return TypeConcept; }
References Definition::TypeConcept.
displayName()
QCString ConceptDefAliasImpl::displayName (bool includeScope = true) const inline override virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 120 of file conceptdef.cpp.
    { return getCdAlias()->displayName(includeScope); }
References Definition::displayName(), and getCdAlias().
getCdAlias()
const ConceptDef * ConceptDefAliasImpl::getCdAlias () const inline
Definition at line 107 of file conceptdef.cpp.
{ return toConceptDef(getAlias()); }
References DefinitionAliasMixin< ConceptDef >::getAlias(), getCdAlias(), and toConceptDef().
Referenced by anchor(), codeSymbolType(), displayName(), getCdAlias(), getFileDef(), getModuleDef(), getNamespaceDef(), getOutputFileBase(), getReference(), getTemplateParameterList(), groupId(), hasDetailedDescription(), includeInfo(), initializer(), isLinkable(), isLinkableInProject(), isReference(), title(), and writeDeclarationLink().
getFileDef()
const FileDef * ConceptDefAliasImpl::getFileDef () const inline override virtual
Implements ConceptDef.
Definition at line 136 of file conceptdef.cpp.
    { return getCdAlias()->getFileDef(); }
References getCdAlias(), and ConceptDef::getFileDef().
getModuleDef()
const ModuleDef * ConceptDefAliasImpl::getModuleDef () const inline override virtual
Implements ConceptDef.
Definition at line 138 of file conceptdef.cpp.
    { return getCdAlias()->getModuleDef(); }
References getCdAlias(), and ConceptDef::getModuleDef().
getNamespaceDef()
const NamespaceDef * ConceptDefAliasImpl::getNamespaceDef () const inline override virtual
Implements ConceptDef.
Definition at line 134 of file conceptdef.cpp.
    { return getCdAlias()->getNamespaceDef(); }
References getCdAlias(), and ConceptDef::getNamespaceDef().
getOutputFileBase()
QCString ConceptDefAliasImpl::getOutputFileBase () const inline override virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 112 of file conceptdef.cpp.
    { return getCdAlias()->getOutputFileBase(); }
References getCdAlias(), and Definition::getOutputFileBase().
getReference()
QCString ConceptDefAliasImpl::getReference () const inline override virtual
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Implements Definition.
Definition at line 114 of file conceptdef.cpp.
    { return getCdAlias()->getReference(); }
References getCdAlias(), and Definition::getReference().
getTemplateParameterList()
ArgumentList ConceptDefAliasImpl::getTemplateParameterList () const inline override virtual
Implements ConceptDef.
Definition at line 124 of file conceptdef.cpp.
    { return getCdAlias()->getTemplateParameterList(); }
References getCdAlias(), and ConceptDef::getTemplateParameterList().
groupId()
int ConceptDefAliasImpl::groupId () const inline override virtual
Implements ConceptDef.
Definition at line 145 of file conceptdef.cpp.
    { return getCdAlias()->groupId(); }
References getCdAlias(), and ConceptDef::groupId().
hasDetailedDescription()
bool ConceptDefAliasImpl::hasDetailedDescription () const inline override virtual
Implements ConceptDef.
Definition at line 118 of file conceptdef.cpp.
    { return getCdAlias()->hasDetailedDescription(); }
References getCdAlias(), and ConceptDef::hasDetailedDescription().
includeInfo()
const IncludeInfo * ConceptDefAliasImpl::includeInfo () const inline override virtual
Implements ConceptDef.
Definition at line 122 of file conceptdef.cpp.
    { return getCdAlias()->includeInfo(); }
References getCdAlias(), and ConceptDef::includeInfo().
initializer()
QCString ConceptDefAliasImpl::initializer () const inline override virtual
Implements ConceptDef.
Definition at line 132 of file conceptdef.cpp.
    { return getCdAlias()->initializer(); }
References getCdAlias(), and ConceptDef::initializer().
isLinkable()
bool ConceptDefAliasImpl::isLinkable () const inline override virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 130 of file conceptdef.cpp.
    { return getCdAlias()->isLinkable(); }
References getCdAlias(), and Definition::isLinkable().
isLinkableInProject()
bool ConceptDefAliasImpl::isLinkableInProject () const inline override virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 128 of file conceptdef.cpp.
    { return getCdAlias()->isLinkableInProject(); }
References getCdAlias(), and Definition::isLinkableInProject().
isReference()
bool ConceptDefAliasImpl::isReference () const inline override virtual
Returns TRUE if this definition is imported via a tag file.
Implements Definition.
Definition at line 116 of file conceptdef.cpp.
    { return getCdAlias()->isReference(); }
References getCdAlias(), and Definition::isReference().
title()
QCString ConceptDefAliasImpl::title () const inline override virtual
Implements ConceptDef.
Definition at line 140 of file conceptdef.cpp.
    { return getCdAlias()->title(); }
References getCdAlias(), and ConceptDef::title().
writeDeclarationLink()
void ConceptDefAliasImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const inline override virtual
Implements ConceptDef.
Definition at line 142 of file conceptdef.cpp.
    { getCdAlias()->writeDeclarationLink(ol,found,header,localNames); }
References found, getCdAlias(), and ConceptDef::writeDeclarationLink().
The documentation for this class was generated from the following file:
src/conceptdef.cpp