Doxygen: Token Class Reference
Token Class Reference
#include <src/doctokenizer.h>
Public Member Functions
Token (TokenRetval tv)
TokenRetval value () const
TOKEN_SPECIFICATIONS RETVAL_SPECIFICATIONS const char * to_string () const
char command_to_char () const
template<typename... ARGS>
bool is_any_of (ARGS... args) const
bool is (TokenRetval rv) const
Static Public Member Functions
static Token char_to_command (char c)
Private Attributes
TokenRetval m_value
Friends
bool operator== (const Token &t1, const Token &t2)
bool operator!= (const Token &t1, const Token &t2)
Detailed Description
Definition at line 81 of file doctokenizer.h.
Constructor & Destructor Documentation
Token()
Token::Token (TokenRetval tv) inline explicit
Definition at line 84 of file doctokenizer.h.
: m_value(tv) {}
References m_value.
Referenced by char_to_command(), operator!=, and operator==.
Member Function Documentation
char_to_command()
static Token Token::char_to_command (char c) inline static
Definition at line 109 of file doctokenizer.h.
    {
      return c=='@' ? make_TK_COMMAND_AT() : make_TK_COMMAND_BS();
    }
References Token().
command_to_char()
char Token::command_to_char () const inline
Definition at line 104 of file doctokenizer.h.
    {
      return m_value==TokenRetval::TK_COMMAND_AT ? '@' : '\\';
    }
References m_value.
Referenced by DocParser::errorHandleDefaultToken(), DocHtmlDescTitle::parse(), DocLink::parse(), DocPara::parse(), and DocSecRefList::parse().
is()
bool Token::is (TokenRetval rv) const inline
Definition at line 120 of file doctokenizer.h.
    {
      return m_value==rv;
    }
References m_value.
Referenced by DocParser::defaultHandleTitleAndSize(), DocParser::defaultHandleToken(), DocParser::handleAnchor(), DocPara::handleCite(), DocPara::handleDoxyConfig(), DocPara::handleEmoji(), DocPara::handleFile(), DocPara::handleHtmlStartTag(), DocPara::handleIFile(), DocPara::handleILine(), DocParser::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocParser::handleInternalRef(), DocPara::handleLink(), DocPara::handleParamSection(), DocParser::handlePrefix(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleShowDate(), DocPara::handleSimpleSection(), DocParser::handleStyleArgument(), DocPara::handleXRefItem(), DocParser::internalValidatingParseDoc(), DocAutoList::parse(), DocAutoListItem::parse(), DocHtmlBlockQuote::parse(), DocHtmlCell::parse(), DocHtmlDescData::parse(), DocHtmlDescList::parse(), DocHtmlDescTitle::parse(), DocHtmlDetails::parse(), DocHtmlList::parse(), DocHtmlListItem::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocIndexEntry::parse(), DocInternal::parse(), DocPara::parse(), DocParamList::parse(), DocParamSect::parse(), DocParBlock::parse(), DocRoot::parse(), DocSecRefList::parse(), DocSection::parse(), DocSimpleList::parse(), DocHtmlCell::parseXml(), DocHtmlList::parseXml(), DocHtmlListItem::parseXml(), DocHtmlRow::parseXml(), DocHtmlTable::parseXml(), DocParamList::parseXml(), and DocSimpleSect::parseXml().
is_any_of()
template<typename... ARGS> bool Token::is_any_of (ARGS... args) const inline
Definition at line 115 of file doctokenizer.h.
    {
      return ((m_value == args) || ...);
    }
References m_value.
Referenced by DocParser::defaultHandleTitleAndSize(), DocParser::defaultHandleToken(), DocParser::handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleDoxyConfig(), DocPara::handleEmoji(), DocParser::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocParser::handleInternalRef(), DocParser::handlePrefix(), DocPara::handleSection(), DocPara::handleShowDate(), DocPara::handleStartCode(), DocParser::handleStyleArgument(), DocHRef::parse(), DocHtmlBlockQuote::parse(), DocHtmlCaption::parse(), DocHtmlCell::parse(), DocHtmlDescList::parse(), DocHtmlDescTitle::parse(), DocHtmlDetails::parse(), DocHtmlHeader::parse(), DocHtmlList::parse(), DocHtmlRow::parse(), DocHtmlSummary::parse(), DocHtmlTable::parse(), DocIndexEntry::parse(), DocInternal::parse(), DocInternalRef::parse(), DocLink::parse(), DocPara::parse(), DocParamList::parse(), DocRef::parse(), DocRoot::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocSection::parse(), DocText::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocHtmlList::parseXml(), DocHtmlListItem::parseXml(), DocHtmlRow::parseXml(), DocHtmlTable::parseXml(), DocParamList::parseXml(), and DocSimpleSect::parseXml().
to_string()
TOKEN_SPECIFICATIONS RETVAL_SPECIFICATIONS const char * Token::to_string () const inline
Definition at line 91 of file doctokenizer.h.
    {
      const char *result = "ERROR";
      switch (m_value)
      {
#define TKSPEC(x,y) case TokenRetval::x: result = #x; break;
        TOKEN_SPECIFICATIONS
        RETVAL_SPECIFICATIONS
#undef TKSPEC
      }
      return result;
    }
References m_value, RETVAL_SPECIFICATIONS, and TOKEN_SPECIFICATIONS.
Referenced by DocParser::defaultHandleToken(), DocParser::errorHandleDefaultToken(), DocParser::handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleDoxyConfig(), DocPara::handleEmoji(), DocPara::handleFile(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlStartTag(), DocPara::handleIFile(), DocParser::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocParser::handleInternalRef(), DocPara::handleLink(), DocPara::handleParamSection(), DocParser::handlePrefix(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleStartCode(), DocParser::handleStyleArgument(), DocAutoList::parse(), DocAutoListItem::parse(), DocHtmlBlockQuote::parse(), DocHtmlDescList::parse(), DocHtmlDescTitle::parse(), DocHtmlDetails::parse(), DocHtmlList::parse(), DocHtmlListItem::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocIndexEntry::parse(), DocInternal::parse(), DocLink::parse(), DocPara::parse(), DocParamList::parse(), DocParamSect::parse(), DocParBlock::parse(), DocSecRefList::parse(), DocSection::parse(), DocSimpleSect::parse(), DocText::parse(), DocHtmlList::parseXml(), DocHtmlListItem::parseXml(), DocHtmlRow::parseXml(), DocParamList::parseXml(), and DocSimpleSect::parseXml().
value()
TokenRetval Token::value () const inline
Definition at line 85 of file doctokenizer.h.
{ return m_value; }
References m_value.
Referenced by DocParser::defaultHandleToken(), DocParser::errorHandleDefaultToken(), DocParser::handleStyleArgument(), DocHRef::parse(), DocHtmlCaption::parse(), DocHtmlDescTitle::parse(), DocHtmlHeader::parse(), DocHtmlSummary::parse(), DocIndexEntry::parse(), DocLink::parse(), DocPara::parse(), DocRef::parse(), and DocText::parse().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const Token & t1, const Token & t2) friend
Definition at line 126 of file doctokenizer.h.
{ return !(operator==(t1,t2)); }
References operator==, and Token().
operator==
bool operator== (const Token & t1, const Token & t2) friend
Definition at line 125 of file doctokenizer.h.
{ return t1.m_value==t2.m_value; }
References m_value, and Token().
Referenced by operator!=.
Member Data Documentation
m_value
TokenRetval Token::m_value private
Definition at line 129 of file doctokenizer.h.
Referenced by command_to_char(), is(), is_any_of(), operator==, to_string(), Token(), and value().
The documentation for this class was generated from the following file:
src/doctokenizer.h