Doxygen: FilePair Class Reference
FilePair Class Reference
Class representing a pair of FileDef objects.
#include <src/dirdef.h>
Public Member Functions
FilePair (const FileDef *src, const FileDef *dst)
const FileDef * source () const
const FileDef * destination () const
Static Public Member Functions
static QCString key (const FileDef *srcFd, const FileDef *dstFd)
Private Attributes
const FileDef * m_src
const FileDef * m_dst
Detailed Description
Class representing a pair of FileDef objects.
Definition at line 41 of file dirdef.h.
Constructor & Destructor Documentation
FilePair()
FilePair::FilePair (const FileDef * src, const FileDef * dst) inline
Definition at line 44 of file dirdef.h.
: m_src(src), m_dst(dst) {}
References m_dst, and m_src.
Member Function Documentation
destination()
const FileDef * FilePair::destination () const inline
Definition at line 46 of file dirdef.h.
{ return m_dst; }
References m_dst.
key()
QCString FilePair::key (const FileDef * srcFd, const FileDef * dstFd) static
Definition at line 883 of file dirdef.cpp.
{
  return srcFd->getOutputFileBase()+";"+dstFd->getOutputFileBase();
}
References Definition::getOutputFileBase().
Referenced by UsedDir::addFileDep(), and DirDefImpl::addUsesDependency().
source()
const FileDef * FilePair::source () const inline
Definition at line 45 of file dirdef.h.
{ return m_src; }
References m_src.
Member Data Documentation
m_dst
const FileDef* FilePair::m_dst private
Definition at line 50 of file dirdef.h.
Referenced by destination(), and FilePair().
m_src
const FileDef* FilePair::m_src private
Definition at line 49 of file dirdef.h.
Referenced by FilePair(), and source().
The documentation for this class was generated from the following files:
src/dirdef.h
src/dirdef.cpp