Doxygen: src/searchindex.cpp File Reference
searchindex.cpp File Reference
#include <ctype.h>
#include <assert.h>
#include <mutex>
#include <map>
#include <unordered_map>
#include "searchindex.h"
#include "config.h"
#include "util.h"
#include "doxygen.h"
#include "language.h"
#include "pagedef.h"
#include "growbuf.h"
#include "message.h"
#include "groupdef.h"
#include "filedef.h"
#include "portable.h"
Functions
static int charsToIndex (const QCString &word)
static void writeInt (std::ostream &f, size_t index)
static void writeString (std::ostream &f, const QCString &s)
static QCString definitionToName (const Definition *ctx)
void initSearchIndexer ()
void finalizeSearchIndexer ()
Variables
const size_t numIndexEntries = 256*256
static std::mutex g_searchIndexMutex
Function Documentation
charsToIndex()
static int charsToIndex (const QCString & word) static
Definition at line 175 of file searchindex.cpp.
{
  if (word.length()<2) return -1;
  // Fast string hashing algorithm
  //register uint16_t h=0;
  //const char *k = word;
  //uint16_t mask=0xfc00;
  //while ( *k )
  //{
  //  h = (h&mask)^(h<<6)^(*k++);
  //}
  //return h;
  // Simple hashing that allows for substring searching
  uint32_t c1=static_cast<uint8_t>(word[0]);
  uint32_t c2=static_cast<uint8_t>(word[1]);
  return c1*256+c2;
}
References word.
Referenced by SearchIndex::addWordRec().
definitionToName()
static QCString definitionToName (const Definition * ctx) static
Definition at line 391 of file searchindex.cpp.
{
  if (ctx && ctx->definitionType()==Definition::TypeMember)
  {
    const MemberDef *md = toMemberDef(ctx);
    if (md->isFunction())
      return "function";
    else if (md->isSlot())
      return "slot";
    else if (md->isSignal())
      return "signal";
    else if (md->isVariable())
      return "variable";
    else if (md->isTypedef())
      return "typedef";
    else if (md->isEnumerate())
      return "enum";
    else if (md->isEnumValue())
      return "enumvalue";
    else if (md->isProperty())
      return "property";
    else if (md->isEvent())
      return "event";
    else if (md->isRelated() || md->isForeign())
      return "related";
    else if (md->isFriend())
      return "friend";
    else if (md->isDefine())
      return "define";
  }
  else if (ctx)
  {
    switch(ctx->definitionType())
    {
      case Definition::TypeClass:
        return (toClassDef(ctx))->compoundTypeString();
      case Definition::TypeFile:
        return "file";
      case Definition::TypeNamespace:
        return "namespace";
      case Definition::TypeConcept:
        return "concept";
      case Definition::TypeGroup:
        return "group";
      case Definition::TypePackage:
        return "package";
      case Definition::TypePage:
        return "page";
      case Definition::TypeDir:
        return "dir";
      case Definition::TypeModule:
        return "module";
      default:
        break;
    }
  }
  return "unknown";
}
References Definition::definitionType(), MemberDef::isDefine(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isEvent(), MemberDef::isForeign(), MemberDef::isFriend(), MemberDef::isFunction(), MemberDef::isProperty(), MemberDef::isRelated(), MemberDef::isSignal(), MemberDef::isSlot(), MemberDef::isTypedef(), MemberDef::isVariable(), toClassDef(), toMemberDef(), Definition::TypeClass, Definition::TypeConcept, Definition::TypeDir, Definition::TypeFile, Definition::TypeGroup, Definition::TypeMember, Definition::TypeModule, Definition::TypeNamespace, Definition::TypePackage, and Definition::TypePage.
Referenced by SearchIndexExternal::setCurrentDoc().
finalizeSearchIndexer()
void finalizeSearchIndexer ()
Cleanup the search indexer
Definition at line 551 of file searchindex.cpp.
{
  Doxygen::searchIndex.setKind(SearchIndexIntf::Disabled);
}
References SearchIndexIntf::Disabled, Doxygen::searchIndex, and SearchIndexIntf::setKind().
Referenced by generateOutput().
initSearchIndexer()
void initSearchIndexer ()
Initialize the search indexer
Definition at line 540 of file searchindex.cpp.
{
  bool searchEngine      = Config_getBool(SEARCHENGINE);
  bool serverBasedSearch = Config_getBool(SERVER_BASED_SEARCH);
  bool externalSearch    = Config_getBool(EXTERNAL_SEARCH);
  if (searchEngine && serverBasedSearch)
  {
    Doxygen::searchIndex.setKind(externalSearch ? SearchIndexIntf::External : SearchIndexIntf::Internal);
  }
}
References Config_getBool, SearchIndexIntf::External, SearchIndexIntf::Internal, Doxygen::searchIndex, and SearchIndexIntf::setKind().
Referenced by parseInput().
writeInt()
static void writeInt (std::ostream & f, size_t index) static
Definition at line 242 of file searchindex.cpp.
{
  f.put(static_cast<int>((index>>24)&0xff));
  f.put(static_cast<int>((index>>16)&0xff));
  f.put(static_cast<int>((index>>8)&0xff));
  f.put(static_cast<int>(index&0xff));
}
Referenced by SearchIndex::write().
writeString()
static void writeString (std::ostream & f, const QCString & s) static
Definition at line 250 of file searchindex.cpp.
{
  size_t l = s.length();
  for (size_t i=0;i<l;i++) f.put(s[i]);
  f.put(0);
}
References QCString::length().
Referenced by SearchIndex::write().
Variable Documentation
g_searchIndexMutex
std::mutex g_searchIndexMutex static
Definition at line 50 of file searchindex.cpp.
Referenced by SearchIndex::addWord(), SearchIndexExternal::addWord(), SearchIndex::setCurrentDoc(), and SearchIndexExternal::setCurrentDoc().
numIndexEntries
const size_t numIndexEntries = 256*256
Definition at line 48 of file searchindex.cpp.
Referenced by SearchIndex::SearchIndex(), and SearchIndex::write().