Doxygen: DocTitle Class Reference
DocTitle Class Reference
Node representing a simple section title.
#include <src/docnode.h>
Public Member Functions
DocTitle (DocParser *parser, DocNodeVariant *parent)
void parse ()
void parseFromString (DocNodeVariant *, const QCString &title)
bool hasTitle () const
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node representing a simple section title.
Definition at line 587 of file docnode.h.
Constructor & Destructor Documentation
DocTitle()
DocTitle::DocTitle (DocParser * parser, DocNodeVariant * parent) inline
Definition at line 590 of file docnode.h.
: DocCompoundNode(parser,parent) {}
References DocCompoundNode::DocCompoundNode(), DocNode::parent(), and DocNode::parser().
Member Function Documentation
hasTitle()
bool DocTitle::hasTitle () const inline
Definition at line 593 of file docnode.h.
{ return !children().empty(); }
References DocCompoundNode::children(), and GrowVector< T >::empty().
Referenced by DocbookDocVisitor::operator()().
parse()
void DocTitle::parse ()
Definition at line 2854 of file docnode.cpp.
{
  AUTO_TRACE();
  auto ns = AutoNodeStack(parser(),thisVariant());
  parser()->tokenizer.setStateTitle();
  Token tok = parser()->tokenizer.lex();
  while (!tok.is_any_of(TokenRetval::TK_NONE, TokenRetval::TK_EOF))
  {
    if (!parser()->defaultHandleToken(thisVariant(),tok,children()))
    {
      parser()->errorHandleDefaultToken(thisVariant(),tok,children(),"title section");
    }
    tok = parser()->tokenizer.lex();
  }
  parser()->tokenizer.setStatePara();
  parser()->handlePendingStyleCommands(thisVariant(),children());
}
References AUTO_TRACE, DocCompoundNode::children(), DocParser::errorHandleDefaultToken(), DocParser::handlePendingStyleCommands(), Token::is_any_of(), DocTokenizer::lex(), DocNode::parser(), DocTokenizer::setStatePara(), DocTokenizer::setStateTitle(), DocNode::thisVariant(), and DocParser::tokenizer.
parseFromString()
void DocTitle::parseFromString (DocNodeVariant * parent, const QCString & title)
Definition at line 2872 of file docnode.cpp.
{
  parser()->context.insideHtmlLink=TRUE;
  parser()->pushContext(); // this will create a new parser->context.token
  parser()->internalValidatingParseDoc(thisVariant(),children(),text);
  parser()->popContext(); // this will restore the old parser->context.token
  parser()->context.insideHtmlLink=FALSE;
  parser()->tokenizer.setStatePara();
  flattenParagraphs(thisVariant(),children());
}
References DocCompoundNode::children(), DocParser::context, FALSE, flattenParagraphs(), DocParserContext::insideHtmlLink, DocParser::internalValidatingParseDoc(), DocNode::parent(), DocNode::parser(), DocParser::popContext(), DocParser::pushContext(), DocTokenizer::setStatePara(), DocNode::thisVariant(), DocParser::tokenizer, and TRUE.
The documentation for this class was generated from the following files:
src/docnode.h
src/docnode.cpp