Doxygen: TemplateNodeFactory Class Reference
TemplateNodeFactory Class Reference
Factory class for creating tag AST nodes found in a template.
Classes
class AutoRegister
Helper class for registering a template AST node.
Public Types
typedef TemplateNodePtr(* CreateFunc) (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Public Member Functions
TemplateNodePtr create (const QCString &name, TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void registerTemplateNode (const QCString &name, CreateFunc func)
Static Public Member Functions
static TemplateNodeFactory & instance ()
Private Attributes
std::unordered_map< std::string, CreateFunc > m_registry
Detailed Description
Factory class for creating tag AST nodes found in a template.
Definition at line 4631 of file template.cpp.
Member Typedef Documentation
CreateFunc
typedef TemplateNodePtr(* TemplateNodeFactory::CreateFunc) (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Definition at line 4634 of file template.cpp.
Member Function Documentation
create()
TemplateNodePtr TemplateNodeFactory::create (const QCString & name, TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 4646 of file template.cpp.
    {
      auto it = m_registry.find(name.str());
      if (it==m_registry.end()) return 0;
      return it->second(parser,parent,line,data);
    }
References m_registry, parent(), and QCString::str().
Referenced by TemplateParser::parse().
instance()
static TemplateNodeFactory & TemplateNodeFactory::instance () inline static
Definition at line 4639 of file template.cpp.
    {
      static std::unique_ptr<TemplateNodeFactory> instance;
      if (instance==0) instance = std::make_unique<TemplateNodeFactory>();
      return *instance;
    }
References instance().
Referenced by TemplateNodeFactory::AutoRegister< T >::AutoRegister(), instance(), and TemplateParser::parse().
registerTemplateNode()
void TemplateNodeFactory::registerTemplateNode (const QCString & name, CreateFunc func) inline
Definition at line 4657 of file template.cpp.
    {
      m_registry.insert(std::make_pair(name.str(),func));
    }
References m_registry, and QCString::str().
Referenced by TemplateNodeFactory::AutoRegister< T >::AutoRegister().
Member Data Documentation
m_registry
std::unordered_map<std::string,CreateFunc> TemplateNodeFactory::m_registry private
Definition at line 4673 of file template.cpp.
Referenced by create(), and registerTemplateNode().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/template.cpp