Doxygen: TranslatorSerbian Class Reference
TranslatorSerbian Class Reference
#include <src/translator_sr.h>
Public Member Functions
QCString idLanguage () override
QCString latexLanguageSupportCommand () override
QCString trISOLang () override
QCString getLanguageString () override
language codes for Html help
QCString trRelatedFunctions () override
Čini se da je ovako manje loše nego "Povezane funkcije", što uopšte ne izgleda dobro jer ta kartica sadrži prijatelje i globalne funkcije.
QCString trRelatedSubscript () override
QCString trDetailedDescription () override
QCString trDetails () override
QCString trMemberTypedefDocumentation () override
QCString trMemberEnumerationDocumentation () override
Ovo je u skladu sa "unutrašnja klasa" što se može videti u knjizi.
QCString trMemberFunctionDocumentation () override
QCString trMemberDataDocumentation () override
QCString trMore () override
QCString trListOfAllMembers () override
QCString trMemberList () override
QCString trThisIsTheListOfAllMembers () override
QCString trIncludingInheritedMembers () override
QCString trGeneratedAutomatically (const QCString &s) override
QCString trEnumName () override
QCString trEnumValue () override
QCString trDefinedIn () override
QCString trModules () override
QCString trClassHierarchy () override
QCString trCompoundList () override
QCString trFileList () override
QCString trCompoundMembers () override
QCString trFileMembers () override
QCString trRelatedPages () override
QCString trExamples () override
QCString trSearch () override
QCString trClassHierarchyDescription () override
QCString trFileListDescription (bool extractAll) override
QCString trCompoundListDescription () override
QCString trCompoundMembersDescription (bool extractAll) override
QCString trFileMembersDescription (bool extractAll) override
QCString trExamplesDescription () override
QCString trRelatedPagesDescription () override
QCString trModulesDescription () override
QCString trDocumentation (const QCString &projName) override
QCString trModuleIndex () override
QCString trHierarchicalIndex () override
QCString trCompoundIndex () override
QCString trFileIndex () override
QCString trModuleDocumentation () override
QCString trClassDocumentation () override
QCString trFileDocumentation () override
QCString trReferenceManual () override
QCString trDefines () override
QCString trTypedefs () override
QCString trEnumerations () override
QCString trFunctions () override
QCString trVariables () override
QCString trEnumerationValues () override
QCString trDefineDocumentation () override
QCString trTypedefDocumentation () override
QCString trEnumerationTypeDocumentation () override
QCString trFunctionDocumentation () override
QCString trVariableDocumentation () override
QCString trCompounds () override
QCString trGeneratedAt (const QCString &date, const QCString &projName) override
QCString trClassDiagram (const QCString &clName) override
QCString trWarning () override
QCString trVersion () override
QCString trDate () override
QCString trReturns () override
QCString trSeeAlso () override
QCString trParameters () override
QCString trExceptions () override
QCString trGeneratedBy () override
QCString trNamespaceList () override
QCString trNamespaceListDescription (bool extractAll) override
QCString trFriends () override
QCString trRelatedFunctionDocumentation () override
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trFileReference (const QCString &fileName) override
QCString trNamespaceReference (const QCString &namespaceName) override
QCString trPublicMembers () override
QCString trPublicSlots () override
QCString trSignals () override
QCString trStaticPublicMembers () override
QCString trProtectedMembers () override
QCString trProtectedSlots () override
QCString trStaticProtectedMembers () override
QCString trPrivateMembers () override
QCString trPrivateSlots () override
QCString trStaticPrivateMembers () override
QCString trWriteList (int numEntries) override
QCString trInheritsList (int) override
QCString trInheritedByList (int) override
QCString trReimplementedFromList (int numEntries) override
QCString trReimplementedInList (int numEntries) override
QCString trNamespaceMembers () override
QCString trNamespaceMemberDescription (bool extractAll) override
QCString trNamespaceIndex () override
QCString trNamespaceDocumentation () override
QCString trNamespaces () override
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) override
QCString trReturnValues () override
QCString trMainPage () override
QCString trPageAbbreviation () override
QCString trDefinedAtLineInSourceFile () override
QCString trDefinedInSourceFile () override
QCString trDeprecated () override
QCString trCollaborationDiagram (const QCString &clName) override
QCString trInclDepGraph (const QCString &fName) override
QCString trConstructorDocumentation () override
QCString trGotoSourceCode () override
QCString trGotoDocumentation () override
QCString trPrecondition () override
QCString trPostcondition () override
QCString trInvariant () override
QCString trInitialValue () override
QCString trCode () override
QCString trGraphicalHierarchy () override
QCString trGotoGraphicalHierarchy () override
QCString trGotoTextualHierarchy () override
QCString trPageIndex () override
QCString trNote () override
QCString trPublicTypes () override
QCString trPublicAttribs () override
QCString trStaticPublicAttribs () override
QCString trProtectedTypes () override
QCString trProtectedAttribs () override
QCString trStaticProtectedAttribs () override
QCString trPrivateTypes () override
QCString trPrivateAttribs () override
QCString trStaticPrivateAttribs () override
QCString trTodo () override
QCString trTodoList () override
QCString trReferencedBy () override
QCString trRemarks () override
QCString trAttention () override
QCString trInclByDepGraph () override
QCString trSince () override
QCString trLegendTitle () override
QCString trLegendDocs () override
QCString trLegend () override
QCString trTest () override
QCString trTestList () override
QCString trProperties () override
QCString trPropertyDocumentation () override
QCString trClasses () override
QCString trPackage (const QCString &name) override
QCString trPackageListDescription () override
QCString trPackages () override
QCString trDefineValue () override
QCString trBug () override
QCString trBugList () override
QCString trRTFansicp () override
QCString trRTFCharSet () override
QCString trRTFGeneralIndex () override
QCString trClass (bool first_capital, bool singular) override
QCString trFile (bool first_capital, bool singular) override
QCString trNamespace (bool first_capital, bool singular) override
QCString trGroup (bool first_capital, bool singular) override
QCString trPage (bool first_capital, bool singular) override
QCString trMember (bool first_capital, bool singular) override
QCString trGlobal (bool first_capital, bool singular) override
QCString trAuthor (bool first_capital, bool singular) override
QCString trReferences () override
QCString trImplementedFromList (int) override
QCString trImplementedInList (int) override
QCString trRTFTableOfContents () override
QCString trDeprecatedList () override
QCString trEvents () override
QCString trEventDocumentation () override
QCString trPackageTypes () override
QCString trPackageFunctions () override
QCString trPackageMembers () override
QCString trStaticPackageFunctions () override
QCString trPackageAttribs () override
QCString trStaticPackageAttribs () override
QCString trAll () override
QCString trCallGraph () override
QCString trSearchResultsTitle () override
QCString trSearchResults (int numDocuments) override
QCString trSearchMatches () override
QCString trSourceFile (const QCString &filename) override
QCString trDirIndex () override
QCString trDirDocumentation () override
QCString trDirectories () override
QCString trDirReference (const QCString &dirName) override
QCString trDir (bool first_capital, bool singular) override
QCString trOverloadText () override
QCString trCallerGraph () override
QCString trEnumerationValueDocumentation () override
QCString trMemberFunctionDocumentationFortran () override
QCString trCompoundListFortran () override
QCString trCompoundMembersFortran () override
QCString trCompoundListDescriptionFortran () override
QCString trCompoundMembersDescriptionFortran (bool extractAll) override
QCString trCompoundIndexFortran () override
QCString trTypeDocumentation () override
QCString trSubprograms () override
QCString trSubprogramDocumentation () override
QCString trDataTypes () override
QCString trModulesList () override
QCString trModulesListDescription (bool extractAll) override
QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate) override
QCString trModuleReference (const QCString &namespaceName) override
QCString trModulesMembers () override
QCString trModulesMemberDescription (bool extractAll) override
QCString trModulesIndex () override
QCString trModule (bool first_capital, bool singular) override
QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) override
QCString trType (bool first_capital, bool singular) override
QCString trSubprogram (bool first_capital, bool singular) override
QCString trTypeConstraints () override
QCString trInterfaces () override
QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full) override
QCString trMonth (int month, bool first_capital, bool full) override
QCString trDayPeriod (bool period) override
Public Member Functions inherited from TranslatorAdapter_1_6_0
QCString updateNeededMessage () override
QCString trDirRelation (const QCString &name) override
QCString trLoading () override
QCString trGlobalNamespace () override
QCString trSearching () override
QCString trNoMatches () override
Public Member Functions inherited from TranslatorAdapter_1_7_5
QCString updateNeededMessage () override
QCString trCiteReferences () override
QCString trCopyright () override
QCString trDirDepGraph (const QCString &name) override
QCString trFileIn (const QCString &name) override
QCString trIncludesFileIn (const QCString &name) override
QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, DateTimeType includeTime) override
Public Member Functions inherited from TranslatorAdapter_1_8_0
QCString updateNeededMessage () override
QCString trDetailLevel () override
QCString trTemplateParameters () override
QCString trAndMore (const QCString &number) override
QCString trEnumGeneratedFromFiles (bool single) override
QCString trEnumReference (const QCString &name) override
QCString trInheritedFrom (const QCString &members, const QCString &what) override
QCString trAdditionalInheritedMembers () override
Public Member Functions inherited from TranslatorAdapter_1_8_2
QCString updateNeededMessage () override
QCString trPanelSynchronisationTooltip (bool enable) override
QCString trProvidedByCategory () override
QCString trExtendsClass () override
QCString trClassMethods () override
QCString trInstanceMethods () override
QCString trMethodDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_4
QCString updateNeededMessage () override
QCString trServices () override
QCString trConstantGroups () override
QCString trConstantGroupReference (const QCString &namespaceName) override
QCString trServiceReference (const QCString &sName) override
QCString trSingletonReference (const QCString &sName) override
QCString trServiceGeneratedFromFiles (bool single) override
QCString trSingletonGeneratedFromFiles (bool single) override
Public Member Functions inherited from TranslatorAdapter_1_8_15
QCString trDesignUnitHierarchy () override
QCString trDesignUnitList () override
QCString trDesignUnitMembers () override
QCString trDesignUnitListDescription () override
QCString trDesignUnitIndex () override
QCString trDesignUnits () override
QCString trFunctionAndProc () override
QCString trVhdlType (VhdlSpecifier type, bool single) override
QCString trCustomReference (const QCString &name) override
QCString trConstants () override
QCString trConstantDocumentation () override
QCString trSequences () override
QCString trSequenceDocumentation () override
QCString trDictionaries () override
QCString trDictionaryDocumentation () override
QCString trSliceInterfaces () override
QCString trInterfaceIndex () override
QCString trInterfaceList () override
QCString trInterfaceListDescription () override
QCString trInterfaceHierarchy () override
QCString trInterfaceHierarchyDescription () override
QCString trInterfaceDocumentation () override
QCString trStructs () override
QCString trStructIndex () override
QCString trStructList () override
QCString trStructListDescription () override
QCString trStructDocumentation () override
QCString trExceptionIndex () override
QCString trExceptionList () override
QCString trExceptionListDescription () override
QCString trExceptionHierarchy () override
QCString trExceptionHierarchyDescription () override
QCString trExceptionDocumentation () override
QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal) override
QCString trOperations () override
QCString trOperationDocumentation () override
QCString trDataMembers () override
QCString trDataMemberDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_8_19
QCString trDesignUnitDocumentation () override
Public Member Functions inherited from TranslatorAdapter_1_9_2
QCString updateNeededMessage () override
QCString trConcept (bool first_capital, bool singular) override
QCString trConceptReference (const QCString &conceptName) override
QCString trConceptList () override
QCString trConceptIndex () override
QCString trConceptDocumentation () override
QCString trConceptListDescription (bool extractAll) override
QCString trConceptDefinition () override
Public Member Functions inherited from TranslatorAdapter_1_9_4
QCString updateNeededMessage () override
QCString trPackageList () override
Public Member Functions inherited from TranslatorAdapter_1_9_5
QCString updateNeededMessage () override
QCString trFlowchart () override
Public Member Functions inherited from TranslatorAdapter_1_9_6
QCString updateNeededMessage () override
QCString trRelatedSymbols () override
QCString trRelatedSymbolsSubscript () override
QCString trRelatedSymbolDocumentation () override
QCString trCompoundType (ClassDef::CompoundType compType, SrcLangExt lang) override
QCString trFileMembersDescriptionTotal (FileMemberHighlight::Enum hl) override
QCString trCompoundMembersDescriptionTotal (ClassMemberHighlight::Enum hl) override
QCString trNamespaceMembersDescriptionTotal (NamespaceMemberHighlight::Enum hl) override
QCString trDefinition () override
QCString trDeclaration () override
Public Member Functions inherited from TranslatorAdapter_1_9_8
QCString updateNeededMessage () override
QCString trTopics () override
QCString trTopicDocumentation () override
QCString trTopicList () override
QCString trTopicIndex () override
QCString trTopicListDescription () override
QCString trModuleMembersDescriptionTotal (ModuleMemberHighlight::Enum hl) override
QCString trExportedModules () override
Public Member Functions inherited from TranslatorAdapter_1_10_0
QCString trCopyToClipboard () override
Public Member Functions inherited from TranslatorAdapter_1_11_0
QCString trImportant () override
Public Member Functions inherited from TranslatorAdapterBase
Public Member Functions inherited from Translator
virtual QCString latexFontenc ()
virtual QCString latexFont ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString latexCommandName ()
virtual bool needsPunctuation ()
add punctuation at the end of a brief description when needed and supported by the language
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Member Functions inherited from Translator
QCString p_latexCommandName (const QCString &latexCmd)
QCString createNoun (bool first_capital, bool singular, const QCString &base, const QCString &plurSuffix, const QCString &singSuffix="")
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 27 of file translator_sr.h.
Member Function Documentation
getLanguageString()
QCString TranslatorSerbian::getLanguageString () inline override virtual
language codes for Html help
 0x402 Bulgarian
 0x405 Czech
 0x406 Danish
 0x413 Dutch
 0xC09 English (Australia)
 0x809 English (Britain)
 0x1009 English (Canada)
 0x1809 English (Ireland)
 0x1409 English (New Zealand)
 0x1C09 English (South Africa)
 0x409 English (United States)
 0x40B Finnish
 0x40C French
 0x407 German
 0x408 Greece
 0x439 Hindi
 0x40E Hungarian
 0x410 Italian
 0x814 Norwegian
 0x415 Polish
 0x816 Portuguese(Portugal)
 0x416 Portuguese(Brazil)
 0x419 Russian
 0x80A Spanish(Mexico)
 0xC0A Spanish(Modern Sort)
 0x40A Spanish(Traditional Sort)
 0x41D Swedish
 0x41F Turkey
 0x411 Japanese
 0x412 Korean
 0x804 Chinese (PRC)
 0x404 Chinese (Taiwan)
New LCIDs:
 0x421 Indonesian
 0x41A Croatian
 0x418 Romanian
 0x424 Slovenian
 0x41B Slovak
 0x422 Ukrainian
 0x81A Serbian (Serbia, Latin)
 0x403 Catalan
 0x426 Latvian
 0x427 Lithuanian
 0x436 Afrikaans
 0x42A Vietnamese
 0x429 Persian (Iran)
 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h ,
       so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available).
0x48f Esperanto
So do a fallback to the default language
0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 65 of file translator_sr.h.
    {
      return "0x81A Serbian (Serbia, Latin)";
    }
idLanguage()
QCString TranslatorSerbian::idLanguage () inline override virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 39 of file translator_sr.h.
    { return "serbian"; }
latexLanguageSupportCommand()
QCString TranslatorSerbian::latexLanguageSupportCommand () inline override virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 56 of file translator_sr.h.
    {
      QCString result="\\usepackage[serbian]{babel}\n";
      return result;
    }
trAll()
QCString TranslatorSerbian::trAll () inline override virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1365 of file translator_sr.h.
    {
      return "Sve";
    }
trAttention()
QCString TranslatorSerbian::trAttention () inline override virtual
Implements Translator.
Definition at line 945 of file translator_sr.h.
    {
      return "Pažnja";
    }
trAuthor()
QCString TranslatorSerbian::trAuthor (bool first_capital, bool singular) inline override virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1238 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "autor", "i");
    }
References Translator::createNoun().
trBug()
QCString TranslatorSerbian::trBug () inline override virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1110 of file translator_sr.h.
    {
      return "Greška";
    }
trBugList()
QCString TranslatorSerbian::trBugList () inline override virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1115 of file translator_sr.h.
    {
      return "Spisak grešaka";
    }
trCallerGraph()
QCString TranslatorSerbian::trCallerGraph () inline override virtual
This is used to introduce a caller (or called-by) graph
Možda je bolje "Graf pozivalaca ove funkcije"
Implements Translator.
Definition at line 1483 of file translator_sr.h.
    { //! Možda je bolje "Graf pozivalaca ove funkcije"
      return "Graf funkcija koje pozivaju ovu funkciju:";
    }
trCallGraph()
QCString TranslatorSerbian::trCallGraph () inline override virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1370 of file translator_sr.h.
    {
      return "Graf poziva iz ove funkcije:";
    }
trClass()
QCString TranslatorSerbian::trClass (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1173 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "klas", "e", "a");
    }
References Translator::createNoun().
trClassDiagram()
QCString TranslatorSerbian::trClassDiagram (const QCString & clName) inline override virtual
this text is put before a class diagram
Implements Translator.
Definition at line 499 of file translator_sr.h.
    {
      return QCString("Dijagram nasleđivanja za klasu ") + clName + ":";
    }
trClassDocumentation()
QCString TranslatorSerbian::trClassDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 380 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacija stuktura/unija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentacija klasa";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses()
QCString TranslatorSerbian::trClasses () inline override virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1073 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strukture i unije";
      }
      else
      {
        return "Klase";
      }
    }
References Config_getBool.
trClassHierarchy()
QCString TranslatorSerbian::trClassHierarchy () inline override virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 167 of file translator_sr.h.
    { return "Hijerarhija klasa"; }
trClassHierarchyDescription()
QCString TranslatorSerbian::trClassHierarchyDescription () inline override virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 226 of file translator_sr.h.
    { return "Hijerahija klasa uređena približno po abecedi:"; }
trCode()
QCString TranslatorSerbian::trCode () inline override virtual
Text used the source code in the file index
Implements Translator.
Definition at line 845 of file translator_sr.h.
    {
      return "programski kod";
    }
trCollaborationDiagram()
QCString TranslatorSerbian::trCollaborationDiagram (const QCString & clName) inline override virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 800 of file translator_sr.h.
    {
      return "Klasni dijagram za "+clName+":";
    }
trCompoundIndex()
QCString TranslatorSerbian::trCompoundIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 353 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Spisak struktura/unija";
      }
      else
      {
        return "Spisak klasa";
      }
    }
References Config_getBool.
trCompoundIndexFortran()
QCString TranslatorSerbian::trCompoundIndexFortran () inline override virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1539 of file translator_sr.h.
    { return "Sadržaj složenog tipa podataka"; }
trCompoundList()
QCString TranslatorSerbian::trCompoundList () inline override virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 171 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Spisak struktura";
      }
      else
      {
        return "Spisak klasa";
      }
    }
References Config_getBool.
trCompoundListDescription()
QCString TranslatorSerbian::trCompoundListDescription () inline override virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 239 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Spisak struktura sa kratkim opisima:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Spisak klasa sa kratkim opisima:";
      }
      else
      {
        return "Spisak klasa, struktura, unija i interfejsa sa kratkim opisima:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran()
QCString TranslatorSerbian::trCompoundListDescriptionFortran () inline override virtual
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1512 of file translator_sr.h.
    { return "Spisak složenih tipova podataka sa kratkim opisima:"; }
trCompoundListFortran()
QCString TranslatorSerbian::trCompoundListFortran () inline override virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1504 of file translator_sr.h.
    { return "Složeni tipovi podataka"; }
trCompoundMembers()
QCString TranslatorSerbian::trCompoundMembers () inline override virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 188 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Sva polja struktura";
      }
      else
      {
        return "Svi članovi klasa";
      }
    }
References Config_getBool.
trCompoundMembersDescription()
QCString TranslatorSerbian::trCompoundMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 257 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll)
      {
        result+="dokumentovanih ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="članova struktura/unija";
      }
      else
      {
        result+="članova klasa";
      }
      result+=" sa vezama ka ";
      if (extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentaciji svakog polja strukture/unije:";
        }
        else
        {
          result+="dokumentaciji svakog člana klase:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="strukturama/unijama kojima pripadaju:";
        }
        else
        {
          result+="klasama kojima pripadaju:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran()
QCString TranslatorSerbian::trCompoundMembersDescriptionFortran (bool extractAll) inline override virtual
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1516 of file translator_sr.h.
    {
      QCString result=" Spisak svih ";
      if (!extractAll)
      {
        result+="dokumentovanih ";
      }
      result+="polja složenih tipova podataka";
      result+=" sa vezama ka ";
      if (!extractAll)
      {
         result+="dokumentaciji strukture podataka za svakog člana";
      }
      else
      {
         result+="složenim tipovima podataka kojima pripadaju:";
      }
      return result;
    }
trCompoundMembersFortran()
QCString TranslatorSerbian::trCompoundMembersFortran () inline override virtual
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1508 of file translator_sr.h.
    { return "Polja u složenim tipovima podataka"; }
trCompoundReference()
QCString TranslatorSerbian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 574 of file translator_sr.h.
    {
      QCString result( "Dokumentacija " );
      switch(compType)
      {
        case ClassDef::Class:      result+="klase "; break;
        case ClassDef::Struct:     result+="strukture "; break;
        case ClassDef::Union:      result+="unije "; break;
        case ClassDef::Interface:  result+="interfejsa "; break;
        case ClassDef::Protocol:   result+="protokola "; break;
        case ClassDef::Category:   result+="kategorije "; break;
        case ClassDef::Exception:  result+="izuzetka "; break;
        default: break;
      }
      if (isTemplate) result += "šablona ";
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
QCString TranslatorSerbian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) inline override virtual
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1580 of file translator_sr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class:      result+=" Modul"; break;
        case ClassDef::Struct:     result+=" Tip"; break;
        case ClassDef::Union:      result+=" Unija"; break;
        case ClassDef::Interface:  result+=" Interfejs"; break;
        case ClassDef::Protocol:   result+=" Protokol"; break;
        case ClassDef::Category:   result+=" Kategorija"; break;
        case ClassDef::Exception:  result+=" Izuzetak"; break;
        default: break;
      }
      result+=" - sažet pregled";
      if (isTemplate) result+=" šablona";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorSerbian::trCompounds () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 475 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strukture i unije";
      }
      else
      {
        return "Klase, strukture i unije";
      }
    }
References Config_getBool.
trConstructorDocumentation()
QCString TranslatorSerbian::trConstructorDocumentation () inline override virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 810 of file translator_sr.h.
    {
      return "Dokumentacija konstruktora i destruktora";
    }
trDataTypes()
QCString TranslatorSerbian::trDataTypes () inline override virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1563 of file translator_sr.h.
    { return "Složeni tipovi podataka"; }
trDate()
QCString TranslatorSerbian::trDate () inline override virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 513 of file translator_sr.h.
    { return "Datum"; }
trDayOfWeek()
QCString TranslatorSerbian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1695 of file translator_sr.h.
    {
      static const char *days_short[]   = { "pon", "uto", "sre", "čet", "pet", "sub", "ned" };
      static const char *days_full[]    = { "ponedeljak", "utorak", "sreda", "četvrtak", "petak", "subota", "nedelja" };
      QCString text  = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod()
QCString TranslatorSerbian::trDayPeriod (bool period) inline override virtual
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1711 of file translator_sr.h.
    {
      static const char *dayPeriod[] = { "pre podne", "po podne" };
      return dayPeriod[period?1:0];
    }
trDefinedAtLineInSourceFile()
QCString TranslatorSerbian::trDefinedAtLineInSourceFile () inline override virtual
Izbacujemo rod
Implements Translator.
Definition at line 777 of file translator_sr.h.
    { //! Izbacujemo rod
      return "Definicija je u redu @0 datoteke @1.";
    }
trDefinedIn()
QCString TranslatorSerbian::trDefinedIn () inline override virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 155 of file translator_sr.h.
    { return "definicija u"; }
trDefinedInSourceFile()
QCString TranslatorSerbian::trDefinedInSourceFile () inline override virtual
Izbacujemo rod
Implements Translator.
Definition at line 781 of file translator_sr.h.
    { //! Izbacujemo rod
      return "Definicija je u datoteci @0.";
    }
trDefineDocumentation()
QCString TranslatorSerbian::trDefineDocumentation () inline override virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 445 of file translator_sr.h.
    { return "Dokumentacija makro zamene"; }
trDefines()
QCString TranslatorSerbian::trDefines () inline override virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 409 of file translator_sr.h.
    { return "Makro zamene"; }
trDefineValue()
QCString TranslatorSerbian::trDefineValue () inline override virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1100 of file translator_sr.h.
    {
      return "Vrednost:";
    }
trDeprecated()
QCString TranslatorSerbian::trDeprecated () inline override virtual
Implements Translator.
Definition at line 790 of file translator_sr.h.
    {
      return "Zastarelo";
    }
trDeprecatedList()
QCString TranslatorSerbian::trDeprecatedList () inline override virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1293 of file translator_sr.h.
    {
      return "Spisak zastarelih stvari";
    }
trDetailedDescription()
QCString TranslatorSerbian::trDetailedDescription () inline override virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 83 of file translator_sr.h.
    { return "Opširniji opis"; }
trDetails()
QCString TranslatorSerbian::trDetails () inline override virtual
header that is used when the summary tag is missing inside the details tag
Implements Translator.
Definition at line 87 of file translator_sr.h.
    { return "Podrobnosće"; }
trDir()
QCString TranslatorSerbian::trDir (bool first_capital, bool singular) inline override virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1460 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "direktorijum", "i");
    }
References Translator::createNoun().
trDirDocumentation()
QCString TranslatorSerbian::trDirDocumentation () inline override virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1442 of file translator_sr.h.
    { return "Dokumentacija direktorijuma"; }
trDirectories()
QCString TranslatorSerbian::trDirectories () inline override virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1448 of file translator_sr.h.
    { return "Direktorijumi"; }
trDirIndex()
QCString TranslatorSerbian::trDirIndex () inline override virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1436 of file translator_sr.h.
    { return "Hijerarhija direktorijuma"; }
trDirReference()
QCString TranslatorSerbian::trDirReference (const QCString & dirName) inline override virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1454 of file translator_sr.h.
    { QCString result=dirName; result+="Opis direktorijuma"; return result; }
trDocumentation()
QCString TranslatorSerbian::trDocumentation (const QCString & projName) inline override virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 335 of file translator_sr.h.
    { return (!projName.isEmpty()?projName + " " : "") + "Dokumentacija"; }
References QCString::isEmpty().
trEnumerations()
QCString TranslatorSerbian::trEnumerations () inline override virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 421 of file translator_sr.h.
    { return "Nabrajanja"; }
trEnumerationTypeDocumentation()
QCString TranslatorSerbian::trEnumerationTypeDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 457 of file translator_sr.h.
    { return "Dokumentacija nabrajanja"; }
trEnumerationValueDocumentation()
QCString TranslatorSerbian::trEnumerationValueDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1491 of file translator_sr.h.
    { return "Dokumentacija enum vrednosti"; }
trEnumerationValues()
QCString TranslatorSerbian::trEnumerationValues () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 439 of file translator_sr.h.
    { return "Vrednosti nabrojanih konstanti"; }
trEnumName()
QCString TranslatorSerbian::trEnumName () inline override virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 147 of file translator_sr.h.
    { return "ime nabrajanja "; }
trEnumValue()
QCString TranslatorSerbian::trEnumValue () inline override virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 151 of file translator_sr.h.
    { return "vrednost nabrojane konstante"; }
trEventDocumentation()
QCString TranslatorSerbian::trEventDocumentation () inline override virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1310 of file translator_sr.h.
    {
      return "Dokumentacija događaja";
    }
trEvents()
QCString TranslatorSerbian::trEvents () inline override virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1305 of file translator_sr.h.
    {
      return "Događaji";
    }
trExamples()
QCString TranslatorSerbian::trExamples () inline override virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 218 of file translator_sr.h.
    { return "Primeri"; }
trExamplesDescription()
QCString TranslatorSerbian::trExamplesDescription () inline override virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 321 of file translator_sr.h.
    { return "Spisak svih primera:"; }
trExceptions()
QCString TranslatorSerbian::trExceptions () inline override virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 529 of file translator_sr.h.
    { return "Izuzeci"; }
trFile()
QCString TranslatorSerbian::trFile (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1182 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "datotek", "e", "a");
    }
References Translator::createNoun().
trFileDocumentation()
QCString TranslatorSerbian::trFileDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 399 of file translator_sr.h.
    { return "Dokumentacija datoteke"; }
trFileIndex()
QCString TranslatorSerbian::trFileIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 368 of file translator_sr.h.
    { return "Indeks datoteka"; }
trFileList()
QCString TranslatorSerbian::trFileList () inline override virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 184 of file translator_sr.h.
    { return "Spisak datoteka"; }
trFileListDescription()
QCString TranslatorSerbian::trFileListDescription (bool extractAll) inline override virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 230 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="datoteka, sa kratkim opisima:";
      return result;
    }
trFileMembers()
QCString TranslatorSerbian::trFileMembers () inline override virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 201 of file translator_sr.h.
    {
      //if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      //{
      // return "Članovi datoteke"; // TODO: translate me
      //}
      //else
      //{
      return "Članovi datoteke";
      //}
    }
trFileMembersDescription()
QCString TranslatorSerbian::trFileMembersDescription (bool extractAll) inline override virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 299 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcija, promenljivih, makro zamena, nabrajanja i definicija tipa";
      }
      else
      {
        result+="članova";
      }
      result+=" sa vezama ka ";
      if (extractAll)
        result+="datotekama u kojima se nalaze:";
      else
        result+="dokumentaciji:";
      return result;
    }
References Config_getBool.
trFileReference()
QCString TranslatorSerbian::trFileReference (const QCString & fileName) inline override virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 596 of file translator_sr.h.
    {
      QCString result = "Opis datoteke ";
      result += fileName;
      return result;
    }
trFriends()
QCString TranslatorSerbian::trFriends () inline override virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 556 of file translator_sr.h.
    { return "Prijatelji"; }
trFunctionDocumentation()
QCString TranslatorSerbian::trFunctionDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 463 of file translator_sr.h.
    { return "Dokumentacija funkcije"; }
trFunctions()
QCString TranslatorSerbian::trFunctions () inline override virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 427 of file translator_sr.h.
    { return "Funkcije"; }
trGeneratedAt()
QCString TranslatorSerbian::trGeneratedAt (const QCString & date, const QCString & projName) inline override virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 490 of file translator_sr.h.
    {
      QCString result="[" + date + "] Napravljeno automatski ";
      if (!projName.isEmpty()) result+=" za projekat " + projName;
          result+=" upotrebom ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically()
QCString TranslatorSerbian::trGeneratedAutomatically (const QCString & s) inline override virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 139 of file translator_sr.h.
    { QCString result="Napravljeno automatski korišćenjem alata Doxygen";
      if (!s.isEmpty()) result+=" za projekat " + s;
      result+=" od izvornog koda.";
      return result;
    }
References QCString::isEmpty().
trGeneratedBy()
QCString TranslatorSerbian::trGeneratedBy () inline override virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 533 of file translator_sr.h.
    { return "Napravio"; }
trGeneratedFromFiles()
QCString TranslatorSerbian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 733 of file translator_sr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ";
      switch(compType)
      {
        case ClassDef::Class:      result+="ove klase"; break;
        case ClassDef::Struct:     result+="ove strukture"; break;
        case ClassDef::Union:      result+="ove unije"; break;
        case ClassDef::Interface:  result+="ovog interfejsa"; break;
        case ClassDef::Protocol:   result+="ovog protokola"; break;
        case ClassDef::Category:   result+="ove kategorije"; break;
        case ClassDef::Exception:  result+="ovog izuzetka"; break;
        default: break;
      }
      result+=" je napravljena na osnovu ";
      if (single) result+="datoteke "; else result+="sledećih datoteka:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
QCString TranslatorSerbian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline override virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1646 of file translator_sr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija za ovaj ";
      switch(compType)
      {
        case ClassDef::Class:      result+="modul"; break;
        case ClassDef::Struct:     result+="tip"; break;
        case ClassDef::Union:      result+="uniju"; break;
        case ClassDef::Interface:  result+="interfejs"; break;
        case ClassDef::Protocol:   result+="protokol"; break;
        case ClassDef::Category:   result+="kategoriju"; break;
        case ClassDef::Exception:  result+="izuzetak"; break;
        default: break;
      }
      result+=" napravljena je automatski od sledeć";
      if (single) result+="e datoteke:"; else result+="ih datoteka:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
QCString TranslatorSerbian::trGlobal (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1227 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "globalni poda", "ci", "tak");
    }
References Translator::createNoun().
trGotoDocumentation()
QCString TranslatorSerbian::trGotoDocumentation () inline override virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 820 of file translator_sr.h.
    {
      return "Dokumentacija.";
    }
trGotoGraphicalHierarchy()
QCString TranslatorSerbian::trGotoGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 853 of file translator_sr.h.
    {
      return "Prikaz hijerarhije klasa u obliku grafa";
    }
trGotoSourceCode()
QCString TranslatorSerbian::trGotoSourceCode () inline override virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 815 of file translator_sr.h.
    {
      return "Izvorni kod.";
    }
trGotoTextualHierarchy()
QCString TranslatorSerbian::trGotoTextualHierarchy () inline override virtual
Implements Translator.
Definition at line 857 of file translator_sr.h.
    {
      return "Prikaz hijerarhije klasa u obliku nazubljenog teksta";
    }
trGraphicalHierarchy()
QCString TranslatorSerbian::trGraphicalHierarchy () inline override virtual
Implements Translator.
Definition at line 849 of file translator_sr.h.
    {
      return "Hijerarhija klasa u obliku grafa";
    }
trGroup()
QCString TranslatorSerbian::trGroup (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1200 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "grup", "e", "a");
    }
References Translator::createNoun().
trHierarchicalIndex()
QCString TranslatorSerbian::trHierarchicalIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 347 of file translator_sr.h.
    { return "Hijerarhijski sadržaj"; }
trImplementedFromList()
QCString TranslatorSerbian::trImplementedFromList (int) inline override virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
"Definiše" je previše kratko, ispada sa de definišu same apstraktne klase
Implements Translator.
Definition at line 1261 of file translator_sr.h.
    { //! "Definiše" je previše kratko, ispada sa de definišu same apstraktne klase
      return "Definiše apstraktnu funkciju deklarisanu u ";
    }
trImplementedInList()
QCString TranslatorSerbian::trImplementedInList (int) inline override virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Izbegavanje roda
Implements Translator.
Definition at line 1269 of file translator_sr.h.
    { //! Izbegavanje roda
      return "Definicija u ";
    }
trInclByDepGraph()
QCString TranslatorSerbian::trInclByDepGraph () inline override virtual
Implements Translator.
Definition at line 949 of file translator_sr.h.
    {
      return "Ovaj graf pokazuje koje datoteke direktno "
             "ili indirektno uključuju ovu datoteku: ";
    }
trInclDepGraph()
QCString TranslatorSerbian::trInclDepGraph (const QCString & fName) inline override virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 805 of file translator_sr.h.
    {
      return "Graf zavisnosti datoteka za "+fName+":";
    }
trIncludingInheritedMembers()
QCString TranslatorSerbian::trIncludingInheritedMembers () inline override virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 133 of file translator_sr.h.
    { return ", uključujući nasleđene članove."; }
trInheritedByList()
QCString TranslatorSerbian::trInheritedByList (int) inline override virtual
used in class documentation to produce a list of derived classes, if class diagrams are disabled.
Implements Translator.
Definition at line 667 of file translator_sr.h.
    {
      return "Spisak izvedenih klasa: ";
    }
trInheritsList()
QCString TranslatorSerbian::trInheritsList (int) inline override virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 659 of file translator_sr.h.
    {
      return "Spisak osnovnih klasa: ";
    }
trInitialValue()
QCString TranslatorSerbian::trInitialValue () inline override virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 840 of file translator_sr.h.
    {
      return "Početna vrednost:";
    }
trInterfaces()
QCString TranslatorSerbian::trInterfaces () inline override virtual
Used for Java interfaces in the summary section of Java packages
< Radna okruzenja. Ali to je dve reci.
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 1690 of file translator_sr.h.
    {
      return "Interfejsi";  //!< Radna okruzenja. Ali to je dve reci.
    }
trInvariant()
QCString TranslatorSerbian::trInvariant () inline override virtual
Text for the \invariant command
Implements Translator.
Definition at line 835 of file translator_sr.h.
    {
      return "Invarijanta";
    }
trISOLang()
QCString TranslatorSerbian::trISOLang () inline override virtual
Implements Translator.
Definition at line 61 of file translator_sr.h.
    {
      return "sr-Latn";
    }
trLegend()
QCString TranslatorSerbian::trLegend () inline override virtual
text for the link to the legend page
Implements Translator.
Definition at line 1033 of file translator_sr.h.
    {
      return "Objašnjenje korišćenih simbola";
    }
trLegendDocs()
QCString TranslatorSerbian::trLegendDocs () inline override virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 971 of file translator_sr.h.
    {
      return
        "Ova stranica objašnjava kako tumačiti grafikone koje je napravio "
        "doxygen.<p>\n"
        "Na primer:\n"
        "\\code\n"
        "/*! Klasa nevidljiva zbog trenutnih ograničenja */\n"
        "class Invisible { };\n\n"
        "/*! Klasa kojoj se ne vidi način izvođenja */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasa bez doxygen komentara */\n"
        "class Undocumented { };\n\n"
        "/*! Klasa izvedena iz osnovne klase javnim izvođenjem */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Šablonska klasa */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasa izvedena iz osnovne klase zaštićenim izvođenjem */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasa izvedena iz osnovne klase privatnim izvođenjem */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasa korišćena u nekoj/nekim od drugih klasa */\n"
        "class Used { };\n\n"
        "/*! Klasa izvedena iz više osnovnih klasa */\n"
        "class Inherited : public PublicBase,\n"
        "                  protected ProtectedBase,\n"
        "                  private PrivateBase,\n"
        "                  public Undocumented,\n"
        "                  public Templ<int>\n"
        "{\n"
        "  private:\n"
        "    Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Ako je \\c MAX_DOT_GRAPH_HEIGHT tag u konfiguracionoj datoteci "
        "postavljen na \\c 200 graf izvođenja će izgledati ovako:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "Graf će biti odsečen ako ne stane unutar zadatih granica.\n"
        "<p>\n"
        "Pravougaonici imaju sledeća značenja:\n"
        "<ul>\n"
         "<li>Puni sivi predstavlja strukturu ili klasu za koju je graf napravljen.\n"
         "<li>Sa crnom ivicom predstavlja dokumentovanu strukturu ili klasu.\n"
         "<li>Sa sivom ivicom predstavlja strukturu ili klasu bez doxygen komentara.\n"
         "<li>Sa crvenom ivicom predstavlja dokumentovanu strukturu ili klasu\n"
         "za koju nisu prikazani svi relevantni grafovi.\n"
         "</ul>"
        "Strelice imaju sledeća značenja:\n"
        "<ul>\n"
         "<li>Tamnoplava strelica označava javno izvođenje.\n"
         "<li>Tamnozelena strelica označava zaštićeno izvođenje.\n"
         "<li>Tamnocrvena strelica označava privatno izvođenje.\n"
         "<li>Ljubičasta isprekidana strelica označava da je klasa sadržana "
          "ili korišćena u drugoj klasi. Strelica je označena imenom atributa "
          "preko koga se pristupa klasi/strukturi na koju pokazuje.\n"
         "<li>Žuta isprekidana strelica označava vezu između primerka šablona i"
          " šablona klase od kojeg je primerak napravljen. "
          "Strelica je označena stvarnim argumentima šablona.\n"
        "</ul>\n"
        ;
    }
References getDotImageExtension().
trLegendTitle()
QCString TranslatorSerbian::trLegendTitle () inline override virtual
title of the graph legend page
Implements Translator.
Definition at line 964 of file translator_sr.h.
    {
      return "Objašnjenje korišćenih simbola";
    }
trListOfAllMembers()
QCString TranslatorSerbian::trListOfAllMembers () inline override virtual
put in the class documentation
Implements Translator.
Definition at line 121 of file translator_sr.h.
    { return "Spisak svih članova"; }
trMainPage()
QCString TranslatorSerbian::trMainPage () inline override virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 764 of file translator_sr.h.
    { return "Glavna strana"; }
trMember()
QCString TranslatorSerbian::trMember (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1218 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "član", "ovi");
    }
References Translator::createNoun().
trMemberDataDocumentation()
QCString TranslatorSerbian::trMemberDataDocumentation () inline override virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 104 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacija polja";
      }
      else
      {
        return "Dokumentacija atributa";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation()
QCString TranslatorSerbian::trMemberEnumerationDocumentation () inline override virtual
Ovo je u skladu sa "unutrašnja klasa" što se može videti u knjizi.
header that is put before the list of enumerations.
Implements Translator.
Definition at line 95 of file translator_sr.h.
    { return "Dokumentacija unutrašnjih nabrajanja"; }
trMemberFunctionDocumentation()
QCString TranslatorSerbian::trMemberFunctionDocumentation () inline override virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 100 of file translator_sr.h.
    { return "Dokumentacija funkcija članica"; }
trMemberFunctionDocumentationFortran()
QCString TranslatorSerbian::trMemberFunctionDocumentationFortran () inline override virtual
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1499 of file translator_sr.h.
    { return "Dokumentacija funkcija i procedura"; }
trMemberList()
QCString TranslatorSerbian::trMemberList () inline override virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 125 of file translator_sr.h.
    { return "Spisak članova"; }
trMemberTypedefDocumentation()
QCString TranslatorSerbian::trMemberTypedefDocumentation () inline override virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 91 of file translator_sr.h.
    { return "Dokumentacija unutrašnjih definicija tipa"; }
trModule()
QCString TranslatorSerbian::trModule (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1639 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "modul", "i");
    }
References Translator::createNoun().
trModuleDocumentation()
QCString TranslatorSerbian::trModuleDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 374 of file translator_sr.h.
    { return "Dokumentacija modula"; }
trModuleIndex()
QCString TranslatorSerbian::trModuleIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 341 of file translator_sr.h.
    { return "Indeks modula"; }
trModuleReference()
QCString TranslatorSerbian::trModuleReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1601 of file translator_sr.h.
    {
      QCString result=namespaceName;
      result+=" - sažet pregled modula";
      return result;
    }
trModules()
QCString TranslatorSerbian::trModules () inline override virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 163 of file translator_sr.h.
    { return "Moduli"; }
trModulesDescription()
QCString TranslatorSerbian::trModulesDescription () inline override virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 329 of file translator_sr.h.
    { return "Spisak svih modula:"; }
trModulesIndex()
QCString TranslatorSerbian::trModulesIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1632 of file translator_sr.h.
    { return "Spisak modula"; }
trModulesList()
QCString TranslatorSerbian::trModulesList () inline override virtual
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1567 of file translator_sr.h.
    { return "Spisak modula"; }
trModulesListDescription()
QCString TranslatorSerbian::trModulesListDescription (bool extractAll) inline override virtual
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1571 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="modula sa kratkim opisima:";
      return result;
    }
trModulesMemberDescription()
QCString TranslatorSerbian::trModulesMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1613 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="članova modula sa vezama ka ";
      if (extractAll)
      {
        result+="dokumentaciji za svakog člana modula:";
      }
      else
      {
        result+="modulima kojima pripadaju:";
      }
      return result;
    }
trModulesMembers()
QCString TranslatorSerbian::trModulesMembers () inline override virtual
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1609 of file translator_sr.h.
    { return "Članovi modula"; }
trMonth()
QCString TranslatorSerbian::trMonth (int month, bool first_capital, bool full) inline override virtual
Implements Translator.
Definition at line 1703 of file translator_sr.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "avg", "sep", "okt", "nov", "dec" };
      static const char *months_full[]  = { "januar", "februar", "mart", "april", "maj", "jun", "jul", "avgust", "septembar", "oktobar", "novembar", "decembar" };
      QCString text  = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore()
QCString TranslatorSerbian::trMore () inline override virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 117 of file translator_sr.h.
    { return "Još..."; }
trNamespace()
QCString TranslatorSerbian::trNamespace (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1191 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "prostor", "i") + " imena";
    }
References Translator::createNoun().
trNamespaceDocumentation()
QCString TranslatorSerbian::trNamespaceDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 713 of file translator_sr.h.
    { return "Dokumentacija prostora imena"; }
trNamespaceIndex()
QCString TranslatorSerbian::trNamespaceIndex () inline override virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 707 of file translator_sr.h.
    { return "Indeks prostora imena"; }
trNamespaceList()
QCString TranslatorSerbian::trNamespaceList () inline override virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 541 of file translator_sr.h.
    { return "Spisak prostora imena"; }
trNamespaceListDescription()
QCString TranslatorSerbian::trNamespaceListDescription (bool extractAll) inline override virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 545 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="prostora imena sa kratkim opisom:";
      return result;
    }
trNamespaceMemberDescription()
QCString TranslatorSerbian::trNamespaceMemberDescription (bool extractAll) inline override virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 693 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="članova prostora imena sa vezama prema ";
      if (extractAll)
        result+="dokumentaciji svakog člana prostora imena: ";
      else
        result+="prostorima imena kojima pripadaju: ";
      return result;
    }
trNamespaceMembers()
QCString TranslatorSerbian::trNamespaceMembers () inline override virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 689 of file translator_sr.h.
    { return "Članovi prostora imena"; }
trNamespaceReference()
QCString TranslatorSerbian::trNamespaceReference (const QCString & namespaceName) inline override virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 604 of file translator_sr.h.
    {
      QCString result="Opis prostora imena ";
      result += namespaceName;
      return result;
    }
trNamespaces()
QCString TranslatorSerbian::trNamespaces () inline override virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 723 of file translator_sr.h.
    { return "Prostori imena"; }
trNote()
QCString TranslatorSerbian::trNote () inline override virtual
Implements Translator.
Definition at line 870 of file translator_sr.h.
    {
      return "Beleška";
    }
trOverloadText()
QCString TranslatorSerbian::trOverloadText () inline override virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1472 of file translator_sr.h.
    {
       return "Ovo je funkcija prekopljenog imena, razlikuje se "
              "od gore navedene samo po argumentima koje prihvata.";
    }
trPackage()
QCString TranslatorSerbian::trPackage (const QCString & name) inline override virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1085 of file translator_sr.h.
    {
      return "Paket "+name;
    }
trPackageAttribs()
QCString TranslatorSerbian::trPackageAttribs () inline override virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1346 of file translator_sr.h.
    {
      return "Atributi u paketu"; // Clanovi u paketu
    }
trPackageFunctions()
QCString TranslatorSerbian::trPackageFunctions () inline override virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1328 of file translator_sr.h.
    {
      return "Funkcije u paketu";
    }
trPackageListDescription()
QCString TranslatorSerbian::trPackageListDescription () inline override virtual
The description of the package index page
Implements Translator.
Definition at line 1090 of file translator_sr.h.
    {
      return "Paketi s kratkim opisom (ukoliko postoji):";
    }
trPackageMembers()
QCString TranslatorSerbian::trPackageMembers () inline override virtual
Implements Translator.
Definition at line 1332 of file translator_sr.h.
    {
      return "Članovi u paketu";
    }
trPackages()
QCString TranslatorSerbian::trPackages () inline override virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1095 of file translator_sr.h.
    {
      return "Paketi";
    }
trPackageTypes()
QCString TranslatorSerbian::trPackageTypes () inline override virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1321 of file translator_sr.h.
    {
      return "Tipovi u paketu";
    }
trPage()
QCString TranslatorSerbian::trPage (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1209 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "stran", "e", "a");
    }
References Translator::createNoun().
trPageAbbreviation()
QCString TranslatorSerbian::trPageAbbreviation () inline override virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 770 of file translator_sr.h.
    { return "str."; }
trPageIndex()
QCString TranslatorSerbian::trPageIndex () inline override virtual
Implements Translator.
Definition at line 861 of file translator_sr.h.
    {
      return "Indeks stranice";
    }
trParameters()
QCString TranslatorSerbian::trParameters () inline override virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 525 of file translator_sr.h.
    { return "Parametri"; }
trPostcondition()
QCString TranslatorSerbian::trPostcondition () inline override virtual
Text for the \post command
Implements Translator.
Definition at line 830 of file translator_sr.h.
    {
      return "Stanje po izvršenju";
    }
trPrecondition()
QCString TranslatorSerbian::trPrecondition () inline override virtual
Text for the \pre command
Implements Translator.
Definition at line 825 of file translator_sr.h.
    {
      return "Preduslovi";
    }
trPrivateAttribs()
QCString TranslatorSerbian::trPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 909 of file translator_sr.h.
    {
      return "Privatni članovi";
    }
trPrivateMembers()
QCString TranslatorSerbian::trPrivateMembers () inline override virtual
Implements Translator.
Definition at line 625 of file translator_sr.h.
    { return "Privatni članovi"; }
trPrivateSlots()
QCString TranslatorSerbian::trPrivateSlots () inline override virtual
Implements Translator.
Definition at line 627 of file translator_sr.h.
    { return "Privatni slotovi"; }
trPrivateTypes()
QCString TranslatorSerbian::trPrivateTypes () inline override virtual
Implements Translator.
Definition at line 905 of file translator_sr.h.
    {
      return "Privatni tipovi";
    }
trProperties()
QCString TranslatorSerbian::trProperties () inline override virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1058 of file translator_sr.h.
    {
      return "Osobine";
    }
trPropertyDocumentation()
QCString TranslatorSerbian::trPropertyDocumentation () inline override virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1063 of file translator_sr.h.
    {
      return "Dokumentacija osobina";
    }
trProtectedAttribs()
QCString TranslatorSerbian::trProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 897 of file translator_sr.h.
    {
      return "Zaštićeni članovi";
    }
trProtectedMembers()
QCString TranslatorSerbian::trProtectedMembers () inline override virtual
Implements Translator.
Definition at line 619 of file translator_sr.h.
    { return "Zaštićeni članovi";  }
trProtectedSlots()
QCString TranslatorSerbian::trProtectedSlots () inline override virtual
Implements Translator.
Definition at line 621 of file translator_sr.h.
    { return "Zaštićeni slotovi"; }
trProtectedTypes()
QCString TranslatorSerbian::trProtectedTypes () inline override virtual
Implements Translator.
Definition at line 893 of file translator_sr.h.
    {
      return "Zaštićeni tipovi";
    }
trPublicAttribs()
QCString TranslatorSerbian::trPublicAttribs () inline override virtual
Implements Translator.
Definition at line 878 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Polja";
      }
      else
      {
        return "Javni članovi";
      }
    }
References Config_getBool.
trPublicMembers()
QCString TranslatorSerbian::trPublicMembers () inline override virtual
Implements Translator.
Definition at line 611 of file translator_sr.h.
    { return "Javni članovi"; }
trPublicSlots()
QCString TranslatorSerbian::trPublicSlots () inline override virtual
Implements Translator.
Definition at line 613 of file translator_sr.h.
    { return "Javni slotovi"; }
trPublicTypes()
QCString TranslatorSerbian::trPublicTypes () inline override virtual
Implements Translator.
Definition at line 874 of file translator_sr.h.
    {
      return "Javni tipovi";
    }
trReferencedBy()
QCString TranslatorSerbian::trReferencedBy () inline override virtual
Izbegavanje roda. Uskladjivanje sa trReferences
Implements Translator.
Definition at line 937 of file translator_sr.h.
    { //! Izbegavanje roda. Uskladjivanje sa trReferences
      return "Korisnici: ";
    }
trReferenceManual()
QCString TranslatorSerbian::trReferenceManual () inline override virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 403 of file translator_sr.h.
    { return "Priručnik"; }
trReferences()
QCString TranslatorSerbian::trReferences () inline override virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1249 of file translator_sr.h.
    {
      return "Koristi";
    }
trReimplementedFromList()
QCString TranslatorSerbian::trReimplementedFromList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 675 of file translator_sr.h.
    {
      return "Menja definiciju iz "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList()
QCString TranslatorSerbian::trReimplementedInList (int numEntries) inline override virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Ako već ne možemo jednu reč (redefinicija), da uskladimo sa prethodnim i izbacimo upotrebu roda
Implements Translator.
Definition at line 683 of file translator_sr.h.
    { //! Ako već ne možemo jednu reč (redefinicija), da uskladimo sa prethodnim i izbacimo upotrebu roda
      return "Definicija je izmenjena u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorSerbian::trRelatedFunctionDocumentation () inline override virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 566 of file translator_sr.h.
    { return "Dokumentacija prijatelja i relevantnih funkcija"; }
trRelatedFunctions()
QCString TranslatorSerbian::trRelatedFunctions () inline override virtual
Čini se da je ovako manje loše nego "Povezane funkcije", što uopšte ne izgleda dobro jer ta kartica sadrži prijatelje i globalne funkcije.
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 73 of file translator_sr.h.
    { return "Relevantne funkcije"; }
trRelatedPages()
QCString TranslatorSerbian::trRelatedPages () inline override virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 214 of file translator_sr.h.
    { return "Stranice koje imaju veze sa ovom stranicom"; }
trRelatedPagesDescription()
QCString TranslatorSerbian::trRelatedPagesDescription () inline override virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 325 of file translator_sr.h.
    { return "Spisak stranica koje imaju veze sa ovom stranicom:"; }
trRelatedSubscript()
QCString TranslatorSerbian::trRelatedSubscript () inline override virtual
subscript for the related functions.
Implements Translator.
Definition at line 79 of file translator_sr.h.
    { return "(To nisu funkcije članice.)"; }
trRemarks()
QCString TranslatorSerbian::trRemarks () inline override virtual
Implements Translator.
Definition at line 941 of file translator_sr.h.
    {
      return "Napomene";
    }
trReturns()
QCString TranslatorSerbian::trReturns () inline override virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 517 of file translator_sr.h.
    { return "Vrednost funkcije"; }
trReturnValues()
QCString TranslatorSerbian::trReturnValues () inline override virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 759 of file translator_sr.h.
    { return "Karakteristične vrednosti funkcije"; }
trRTFansicp()
QCString TranslatorSerbian::trRTFansicp () inline override virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
------------------------------------------------------
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1149 of file translator_sr.h.
    {
      return "1252";
    }
trRTFCharSet()
QCString TranslatorSerbian::trRTFCharSet () inline override virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1158 of file translator_sr.h.
    {
      return "238";
    }
trRTFGeneralIndex()
QCString TranslatorSerbian::trRTFGeneralIndex () inline override virtual
Used as header RTF general index
Implements Translator.
Definition at line 1164 of file translator_sr.h.
    {
      return "Sadržaj";
    }
trRTFTableOfContents()
QCString TranslatorSerbian::trRTFTableOfContents () inline override virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1281 of file translator_sr.h.
     {
      return "Sadržaj";
     }
trSearch()
QCString TranslatorSerbian::trSearch () inline override virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 222 of file translator_sr.h.
    { return "Traži"; }
trSearchMatches()
QCString TranslatorSerbian::trSearchMatches () inline override virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1413 of file translator_sr.h.
    {
      return "Pronađeno:";
    }
trSearchResults()
QCString TranslatorSerbian::trSearchResults (int numDocuments) inline override virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1394 of file translator_sr.h.
    {
      if (numDocuments==0)
      {
        return "Nema dokumenata koji odgovaraju Vašem upitu.";
      }
      else if (numDocuments==1)
      { return "Nađen je <b>1</b> dokument koji odgovara vašem upitu."; }
      else if (numDocuments<5)
      { return "Nađena su <b>$num</b> dokumenta koji odgovaraju vašem upitu."
               " Najbolji su prikazani prvi."; }
      else
      { return "Nađeno je <b>$num</b> dokumenata koji odgovaraju vašem upitu."
               " Najbolji su prikazani prvi.";
      }
    }
trSearchResultsTitle()
QCString TranslatorSerbian::trSearchResultsTitle () inline override virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1382 of file translator_sr.h.
    {
      return "Rezultati pretraživanja";
    }
trSeeAlso()
QCString TranslatorSerbian::trSeeAlso () inline override virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 521 of file translator_sr.h.
    { return "Takođe pogledati"; }
trSignals()
QCString TranslatorSerbian::trSignals () inline override virtual
Implements Translator.
Definition at line 615 of file translator_sr.h.
    { return "Signali"; }
trSince()
QCString TranslatorSerbian::trSince () inline override virtual
Implements Translator.
Definition at line 954 of file translator_sr.h.
    {
      return "Od";
    }
trSourceFile()
QCString TranslatorSerbian::trSourceFile (const QCString & filename) inline override virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1424 of file translator_sr.h.
    {
      return "Izvorni kod datoteke " + filename;
    }
trStaticPackageAttribs()
QCString TranslatorSerbian::trStaticPackageAttribs () inline override virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1353 of file translator_sr.h.
    {
      return "Statički atributi u paketu";  // Zajednicki clanovi u paketu
    }
trStaticPackageFunctions()
QCString TranslatorSerbian::trStaticPackageFunctions () inline override virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1339 of file translator_sr.h.
    {
      return "Statičke funkcije u paketu";  // Zajednicke funkcije u paketu
    }
trStaticPrivateAttribs()
QCString TranslatorSerbian::trStaticPrivateAttribs () inline override virtual
Implements Translator.
Definition at line 913 of file translator_sr.h.
    {
      return "Zajednički privatni članovi";
    }
trStaticPrivateMembers()
QCString TranslatorSerbian::trStaticPrivateMembers () inline override virtual
Implements Translator.
Definition at line 629 of file translator_sr.h.
    { return "Zajednički privatni članovi"; }
trStaticProtectedAttribs()
QCString TranslatorSerbian::trStaticProtectedAttribs () inline override virtual
Implements Translator.
Definition at line 901 of file translator_sr.h.
    {
      return "Zajednički zaštićeni članovi";
    }
trStaticProtectedMembers()
QCString TranslatorSerbian::trStaticProtectedMembers () inline override virtual
Implements Translator.
Definition at line 623 of file translator_sr.h.
    { return "Zajednički zaštićeni članovi"; }
trStaticPublicAttribs()
QCString TranslatorSerbian::trStaticPublicAttribs () inline override virtual
Implements Translator.
Definition at line 889 of file translator_sr.h.
    {
      return "Zajednički javni članovi";
    }
trStaticPublicMembers()
QCString TranslatorSerbian::trStaticPublicMembers () inline override virtual
Implements Translator.
Definition at line 617 of file translator_sr.h.
    { return "Zajednički javni članovi"; }
trSubprogram()
QCString TranslatorSerbian::trSubprogram (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1678 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "procedur", "e", "a");
    }
References Translator::createNoun().
trSubprogramDocumentation()
QCString TranslatorSerbian::trSubprogramDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1557 of file translator_sr.h.
    { return "Dokumentacija funkcija i procedura"; }
trSubprograms()
QCString TranslatorSerbian::trSubprograms () inline override virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1551 of file translator_sr.h.
    { return "Funkcije i procedure"; }
trTest()
QCString TranslatorSerbian::trTest () inline override virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1043 of file translator_sr.h.
    {
      return "Test";
    }
trTestList()
QCString TranslatorSerbian::trTestList () inline override virtual
Used as the header of the test list
Implements Translator.
Definition at line 1048 of file translator_sr.h.
    {
      return "Spisak testova";
    }
trThisIsTheListOfAllMembers()
QCString TranslatorSerbian::trThisIsTheListOfAllMembers () inline override virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 129 of file translator_sr.h.
    { return "Ovo je spisak svih članova"; }
trTodo()
QCString TranslatorSerbian::trTodo () inline override virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 923 of file translator_sr.h.
    {
      return "Uraditi";
    }
trTodoList()
QCString TranslatorSerbian::trTodoList () inline override virtual
Used as the header of the todo list
Implements Translator.
Definition at line 928 of file translator_sr.h.
    {
      return "Spisak stvari koje treba uraditi";
    }
trType()
QCString TranslatorSerbian::trType (bool first_capital, bool singular) inline override virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1670 of file translator_sr.h.
    {
      return createNoun(first_capital, singular, "tip", "ovi");
    }
References Translator::createNoun().
trTypeConstraints()
QCString TranslatorSerbian::trTypeConstraints () inline override virtual
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1684 of file translator_sr.h.
    {
      return "Ograničenja tipova";
    }
trTypedefDocumentation()
QCString TranslatorSerbian::trTypedefDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 451 of file translator_sr.h.
    { return "Dokumentacija definicije tipa"; }
trTypedefs()
QCString TranslatorSerbian::trTypedefs () inline override virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 415 of file translator_sr.h.
    { return "Definicije tipa"; }
trTypeDocumentation()
QCString TranslatorSerbian::trTypeDocumentation () inline override virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1545 of file translator_sr.h.
    { return "Dokumentacija tipova podataka"; }
trVariableDocumentation()
QCString TranslatorSerbian::trVariableDocumentation () inline override virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 469 of file translator_sr.h.
    { return "Dokumentacija promenljive"; }
trVariables()
QCString TranslatorSerbian::trVariables () inline override virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 433 of file translator_sr.h.
    { return "Promenljive"; }
trVersion()
QCString TranslatorSerbian::trVersion () inline override virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 509 of file translator_sr.h.
    { return "Verzija"; }
trWarning()
QCString TranslatorSerbian::trWarning () inline override virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 505 of file translator_sr.h.
    { return "Upozorenje"; }
trWriteList()
QCString TranslatorSerbian::trWriteList (int numEntries) inline override virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 635 of file translator_sr.h.
    {
      QCString result;
      // the inherits list contain `numEntries' classes
      for (int i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1)  // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else                // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_sr.h