Doxygen: DocDiaFile Class Reference
DocDiaFile Class Reference
Node representing a dia file.
#include <docnode.h>
Public Member Functions
DocDiaFile (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
bool parse ()
Public Member Functions inherited from DocDiagramFileBase
DocDiagramFileBase (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
QCString name () const
QCString file () const
QCString relPath () const
bool hasCaption () const
QCString width () const
QCString height () const
QCString context () const
QCString srcFile () const
int srcLine () const
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
DocNode (const DocNode &)=delete
DocNode & operator= (const DocNode &)=delete
DocNode (DocNode &&)=default
DocNode & operator= (DocNode &&)=default
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocNodeVariant * thisVariant ()
const DocNodeVariant * thisVariant () const
void setThisVariant (DocNodeVariant *thisVariant)
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from DocDiagramFileBase
std::unique_ptr< Private > p
Detailed Description
Node representing a dia file.
Definition at line 701 of file docnode.h.
Constructor & Destructor Documentation
DocDiaFile()
DocDiaFile::DocDiaFile (DocParser * parser, DocNodeVariant * parent, const QCString & name, const QCString & context, const QCString & srcFile, int srcLine)
Definition at line 1086 of file docnode.cpp.
                                                            :
  DocDiagramFileBase(parser,parent,name,context,srcFile,srcLine)
{
  p->relPath = parser->context.relPath;
}
References DocParser::context, DocDiagramFileBase::p, DocNode::parser(), DocDiagramFileBase::relPath(), and DocParserContext::relPath.
Member Function Documentation
parse()
bool DocDiaFile::parse ()
Definition at line 1093 of file docnode.cpp.
{
  bool ok = false;
  parser()->defaultHandleTitleAndSize(CMD_DIAFILE,thisVariant(),children(),p->width,p->height);
  bool ambig;
  FileDef *fd = findFileDef(Doxygen::diaFileNameLinkedMap,p->name,ambig);
  if (fd==0 && !p->name.endsWith(".dia")) // try with .dia extension as well
  {
    fd = findFileDef(Doxygen::diaFileNameLinkedMap,p->name+".dia",ambig);
  }
  if (fd)
  {
    p->file = fd->absFilePath();
    ok = true;
    if (ambig)
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"included dia file name %s is ambiguous.\n"
           "Possible candidates:\n%s",qPrint(p->name),
           qPrint(showFileDefMatches(Doxygen::diaFileNameLinkedMap,p->name))
          );
    }
  }
  else
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"included dia file %s is not found "
           "in any of the paths specified via DIAFILE_DIRS!",qPrint(p->name));
  }
  return ok;
}
References FileDef::absFilePath(), DocCompoundNode::children(), CMD_DIAFILE, DocDiagramFileBase::context(), DocParser::defaultHandleTitleAndSize(), Doxygen::diaFileNameLinkedMap, QCString::endsWith(), findFileDef(), FileDef::name(), DocDiagramFileBase::p, DocNode::parser(), qPrint(), showFileDefMatches(), DocNode::thisVariant(), and warn_doc_error.
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/docnode.h
/home/runner/work/doxygen/doxygen/src/docnode.cpp