Doxygen: ModuleDef Class Reference
ModuleDef Class Reference abstract
#include <src/moduledef.h>
Public Types
enum class Type { Interface , Implementation }
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeModule = 3 ,
TypeMember = 4 , TypeGroup = 5 , TypePackage = 6 , TypePage = 7 ,
TypeDir = 8 , TypeConcept = 9
}
Public Member Functions
virtual Type moduleType () const =0
virtual QCString partitionName () const =0
virtual void writeDocumentation (OutputList &ol)=0
virtual bool isPrimaryInterface () const =0
virtual MemberList * getMemberList (MemberListType lt) const =0
virtual const MemberLists & getMemberLists () const =0
virtual const MemberGroupList & getMemberGroups () const =0
virtual int countVisibleMembers () const =0
virtual const ClassLinkedRefMap & getClasses () const =0
virtual const ConceptLinkedRefMap & getConcepts () const =0
virtual FileDef * getFileDef () const =0
virtual const ImportInfoMap & getImports () const =0
virtual const ImportInfoMap & getExports () const =0
virtual const ModuleMap & partitions () const =0
virtual void writeTagFile (TextStream &tagFile) const =0
virtual FileList getUsedFiles () const =0
Public Member Functions inherited from DefinitionMutable
virtual void setName (const QCString &name)=0
virtual void setId (const QCString &name)=0
virtual void setDefFile (const QCString &df, int defLine, int defColumn)=0
virtual void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)=0
virtual void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)=0
virtual void setInbodyDocumentation (const QCString &d, const QCString &docFile, int docLine)=0
virtual void setReference (const QCString &r)=0
virtual void setBodySegment (int defLine, int bls, int ble)=0
virtual void setBodyDef (const FileDef *fd)=0
virtual void setRefItems (const RefItemVector &sli)=0
virtual void setOuterScope (Definition *d)=0
virtual void setHidden (bool b)=0
virtual void setArtificial (bool b)=0
virtual void setExported (bool b)=0
virtual void setLanguage (SrcLangExt lang)=0
virtual void setLocalName (const QCString &name)=0
virtual void makePartOfGroup (GroupDef *gd)=0
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)=0
virtual void addSourceReferencedBy (MemberDef *d, const QCString &sourceRefName)=0
virtual void addSourceReferences (MemberDef *d, const QCString &sourceRefName)=0
virtual void mergeRefItems (Definition *d)=0
virtual void addInnerCompound (Definition *d)=0
virtual void mergeReferences (const Definition *other)=0
virtual void mergeReferencedBy (const Definition *other)=0
virtual void computeTooltip ()=0
virtual void writeSourceDef (OutputList &ol) const =0
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const =0
virtual bool hasSourceRefs () const =0
virtual bool hasSourceReffedBy () const =0
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const =0
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const =0
virtual void writeNavigationPath (OutputList &ol) const =0
virtual void writeQuickMemberLinks (OutputList &, const MemberDef *) const =0
virtual void writeSummaryLinks (OutputList &) const =0
virtual void writeDocAnchorsToTagFile (TextStream &) const =0
virtual void writeToc (OutputList &ol, const LocalToc &lt) const =0
Public Member Functions inherited from Definition
virtual DefType definitionType () const =0
virtual CodeSymbolType codeSymbolType () const =0
virtual bool isAlias () const =0
virtual const QCString & name () const =0
virtual bool isAnonymous () const =0
virtual QCString displayName (bool includeScope=TRUE) const =0
virtual const QCString & localName () const =0
virtual QCString qualifiedName () const =0
virtual QCString symbolName () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString getSourceFileBase () const =0
virtual QCString getSourceAnchor () const =0
virtual QCString documentation () const =0
virtual int docLine () const =0
virtual QCString docFile () const =0
virtual QCString briefDescription (bool abbreviate=FALSE) const =0
virtual QCString briefDescriptionAsTooltip () const =0
virtual int briefLine () const =0
virtual QCString inbodyDocumentation () const =0
virtual QCString inbodyFile () const =0
virtual int inbodyLine () const =0
virtual QCString briefFile () const =0
virtual QCString getDefFileName () const =0
virtual QCString getDefFileExtension () const =0
virtual int getDefLine () const =0
virtual int getDefColumn () const =0
virtual bool hasDocumentation () const =0
virtual bool hasUserDocumentation () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isVisibleInProject () const =0
virtual bool isVisible () const =0
virtual bool isHidden () const =0
virtual bool isArtificial () const =0
virtual bool isExported () const =0
virtual QCString getReference () const =0
virtual bool isReference () const =0
virtual QCString externalReference (const QCString &relPath) const =0
virtual int getStartDefLine () const =0
virtual int getStartBodyLine () const =0
virtual int getEndBodyLine () const =0
virtual const FileDef * getBodyDef () const =0
virtual SrcLangExt getLanguage () const =0
Returns the programming language this definition was written in.
virtual const GroupList & partOfGroups () const =0
virtual bool isLinkableViaGroup () const =0
virtual const RefItemVector & xrefListItems () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual Definition * getOuterScope () const =0
virtual const MemberVector & getReferencesMembers () const =0
virtual const MemberVector & getReferencedByMembers () const =0
virtual bool hasSections () const =0
virtual bool hasSources () const =0
virtual bool hasBriefDescription () const =0
returns TRUE if this class has a brief description
virtual QCString id () const =0
virtual const SectionRefs & getSectionRefs () const =0
returns the section dictionary, only of importance for pagedef
virtual QCString navigationPathAsString () const =0
virtual QCString pathFragment () const =0
virtual void _setSymbolName (const QCString &name)=0
virtual QCString _symbolName () const =0
Detailed Description
Definition at line 63 of file moduledef.h.
Member Enumeration Documentation
Type
enum class ModuleDef::Type strong
Enumerator
Interface
Implementation
Definition at line 68 of file moduledef.h.
    {
      Interface,
      Implementation
    };
Member Function Documentation
countVisibleMembers()
virtual int ModuleDef::countVisibleMembers () const pure virtual
Implemented in ModuleDefImpl.
Referenced by writeModuleTreeNode().
getClasses()
virtual const ClassLinkedRefMap & ModuleDef::getClasses () const pure virtual
Implemented in ModuleDefImpl.
Referenced by PerlModGenerator::generatePerlModForModule(), generateSqlite3ForModule(), generateXMLForModule(), and writeModuleTreeNode().
getConcepts()
virtual const ConceptLinkedRefMap & ModuleDef::getConcepts () const pure virtual
Implemented in ModuleDefImpl.
Referenced by PerlModGenerator::generatePerlModForModule(), generateSqlite3ForModule(), generateXMLForModule(), and writeModuleTreeNode().
getExports()
virtual const ImportInfoMap & ModuleDef::getExports () const pure virtual
Implemented in ModuleDefImpl.
Referenced by generateXMLForModule().
getFileDef()
virtual FileDef * ModuleDef::getFileDef () const pure virtual
Implemented in ModuleDefImpl.
Referenced by ModuleManager::resolveImports(), and ModuleDefImpl::sortMemberLists().
getImports()
virtual const ImportInfoMap & ModuleDef::getImports () const pure virtual
Implemented in ModuleDefImpl.
Referenced by ModuleManager::resolvePartitionsRecursively().
getMemberGroups()
virtual const MemberGroupList & ModuleDef::getMemberGroups () const pure virtual
Implemented in ModuleDefImpl.
Referenced by PerlModGenerator::generatePerlModForModule(), generateSqlite3ForModule(), and generateXMLForModule().
getMemberList()
virtual MemberList * ModuleDef::getMemberList (MemberListType lt) const pure virtual
Implemented in ModuleDefImpl.
Referenced by PerlModGenerator::generatePerlModForModule(), and writeModuleMembers().
getMemberLists()
virtual const MemberLists & ModuleDef::getMemberLists () const pure virtual
Implemented in ModuleDefImpl.
Referenced by generateSqlite3ForModule(), and generateXMLForModule().
getUsedFiles()
virtual FileList ModuleDef::getUsedFiles () const pure virtual
Implemented in ModuleDefImpl.
Referenced by PerlModGenerator::generatePerlModForModule(), generateSqlite3ForModule(), and generateXMLForModule().
isPrimaryInterface()
virtual bool ModuleDef::isPrimaryInterface () const pure virtual
Implemented in ModuleDefImpl.
Referenced by Index::addModuleMemberNameToIndex(), and generateXMLForModule().
moduleType()
virtual Type ModuleDef::moduleType () const pure virtual
Implemented in ModuleDefImpl.
partitionName()
virtual QCString ModuleDef::partitionName () const pure virtual
Implemented in ModuleDefImpl.
partitions()
virtual const ModuleMap & ModuleDef::partitions () const pure virtual
Implemented in ModuleDefImpl.
writeDocumentation()
virtual void ModuleDef::writeDocumentation (OutputList & ol) pure virtual
Implemented in ModuleDefImpl.
writeTagFile()
virtual void ModuleDef::writeTagFile (TextStream & tagFile) const pure virtual
Implemented in ModuleDefImpl.
The documentation for this class was generated from the following file:
src/moduledef.h