Doxygen: DiagramRow Class Reference
DiagramRow Class Reference
Class representing a row in the built-in class diagram.
Public Types
using Ptr = std::unique_ptr< DiagramItem >
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using reverse_iterator = typename Vec::reverse_iterator
Public Member Functions
DiagramRow (TreeDiagram *d, uint32_t l)
void insertClass (DiagramItem *parent, const ClassDef *cd, bool doBases, Protection prot, Specifier virt, const QCString &ts)
uint32_t number ()
DiagramItem * item (int index)
uint32_t numItems () const
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
Private Attributes
TreeDiagram * m_diagram
uint32_t m_level
Vec m_items
Detailed Description
Class representing a row in the built-in class diagram.
Definition at line 77 of file diagram.cpp.
Member Typedef Documentation
iterator
using DiagramRow::iterator = typename Vec::iterator
Definition at line 82 of file diagram.cpp.
Ptr
using DiagramRow::Ptr = std::unique_ptr<DiagramItem>
Definition at line 80 of file diagram.cpp.
reverse_iterator
using DiagramRow::reverse_iterator = typename Vec::reverse_iterator
Definition at line 83 of file diagram.cpp.
Vec
using DiagramRow::Vec = std::vector<Ptr>
Definition at line 81 of file diagram.cpp.
Constructor & Destructor Documentation
DiagramRow()
DiagramRow::DiagramRow (TreeDiagram * d, uint32_t l) inline
Definition at line 84 of file diagram.cpp.
: m_diagram(d), m_level(l) {}
Member Function Documentation
begin()
iterator DiagramRow::begin () inline
Definition at line 91 of file diagram.cpp.
{ return m_items.begin();  }
References m_items.
Referenced by TreeDiagram::computeLayout().
end()
iterator DiagramRow::end () inline
Definition at line 92 of file diagram.cpp.
{ return m_items.end();    }
References m_items.
Referenced by TreeDiagram::computeLayout().
insertClass()
void DiagramRow::insertClass (DiagramItem * parent, const ClassDef * cd, bool doBases, Protection prot, Specifier virt, const QCString & ts)
Definition at line 358 of file diagram.cpp.
{
  auto di = std::make_unique<DiagramItem>(parent, m_diagram->row(m_level)->numItems(),
                                          cd,prot,virt,ts);
  DiagramItem *di_ptr = di.get();
  if (parent) parent->addChild(di_ptr);
  di->move(static_cast<int>(m_items.size()*gridWidth),static_cast<int>(m_level*gridHeight));
  m_items.push_back(std::move(di));
  int count=0;
  for (const auto &bcd : doBases ? cd->baseClasses() : cd->subClasses())
  {
    /* there are base/sub classes */
    ClassDef *ccd=bcd.classDef;
    if (ccd && ccd->isVisibleInHierarchy()) count++;
  }
  if (count>0 && (prot!=Protection::Private || !doBases))
  {
    DiagramRow *row=0;
    if (m_diagram->numRows()<=m_level+1) /* add new row */
    {
      row=m_diagram->addRow(m_level+1);
    }
    else /* get next row */
    {
      row=m_diagram->row(m_level+1);
    }
    for (const auto &bcd : doBases ? cd->baseClasses() : cd->subClasses())
    {
      ClassDef *ccd=bcd.classDef;
      if (ccd && ccd->isVisibleInHierarchy())
      {
        row->insertClass(di_ptr,ccd,doBases,bcd.prot,
            doBases ? bcd.virt            : Specifier::Normal,
            doBases ? bcd.templSpecifiers : QCString());
      }
    }
  }
}
References DiagramItem::addChild(), TreeDiagram::addRow(), ClassDef::baseClasses(), gridHeight, gridWidth, insertClass(), ClassDef::isVisibleInHierarchy(), m_diagram, m_items, m_level, Normal, numItems(), TreeDiagram::numRows(), parent(), Private, TreeDiagram::row(), and ClassDef::subClasses().
Referenced by insertClass(), and TreeDiagram::TreeDiagram().
item()
DiagramItem * DiagramRow::item (int index) inline
Definition at line 89 of file diagram.cpp.
{ return m_items.at(index).get(); }
References m_items.
Referenced by TreeDiagram::layoutTree().
number()
uint32_t DiagramRow::number () inline
Definition at line 87 of file diagram.cpp.
{ return m_level; }
References m_level.
numItems()
uint32_t DiagramRow::numItems () const inline
Definition at line 90 of file diagram.cpp.
{ return static_cast<uint32_t>(m_items.size()); }
References m_items.
Referenced by insertClass(), and TreeDiagram::layoutTree().
rbegin()
reverse_iterator DiagramRow::rbegin () inline
Definition at line 93 of file diagram.cpp.
{ return m_items.rbegin();  }
References m_items.
rend()
reverse_iterator DiagramRow::rend () inline
Definition at line 94 of file diagram.cpp.
{ return m_items.rend();    }
References m_items.
Member Data Documentation
m_diagram
TreeDiagram* DiagramRow::m_diagram private
Definition at line 96 of file diagram.cpp.
Referenced by insertClass().
m_items
Vec DiagramRow::m_items private
Definition at line 98 of file diagram.cpp.
Referenced by begin(), end(), insertClass(), item(), numItems(), rbegin(), and rend().
m_level
uint32_t DiagramRow::m_level private
Definition at line 97 of file diagram.cpp.
Referenced by insertClass(), and number().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/diagram.cpp