Doxygen: FileContext Class Reference
FileContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
Gets the value for a field name.
virtual StringVector fields () const
Return the list of fields.
FileContext (const FileDef *)
virtual ~FileContext ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()=default
Destroys the struct.
Static Public Member Functions
static TemplateStructIntfPtr alloc (const FileDef *fd)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 257 of file context.h.
Constructor & Destructor Documentation
FileContext()
FileContext::FileContext (const FileDef * fd)
Definition at line 3110 of file context.cpp.
                                          : p(std::make_unique<Private>(fd))
{
}
~FileContext()
FileContext::~FileContext () virtual
Definition at line 3114 of file context.cpp.
{
}
Member Function Documentation
alloc()
static TemplateStructIntfPtr FileContext::alloc (const FileDef * fd) inline static
Definition at line 260 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<FileContext>(fd)); }
Referenced by UsedFilesContext::Private::addFile(), FileListContext::Private::addFiles(), NestingNodeContext::Private::createFile(), IncludeInfoContext::Private::createFileContext(), MemberContext::Private::createFileDef(), DirContext::Private::createFiles(), and ModuleContext::Private::createFiles().
fields()
StringVector FileContext::fields () const virtual
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 3123 of file context.cpp.
{
  return p->fields();
}
References p.
get()
TemplateVariant FileContext::get (const QCString & name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 3118 of file context.cpp.
{
  return p->get(n);
}
References p.
Member Data Documentation
p
std::unique_ptr<Private> FileContext::p private
Definition at line 272 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/context.h
/home/runner/work/doxygen/doxygen/src/context.cpp