Doxygen: anonymous_namespace{tagreader.cpp}::TagFileParser Class Reference
anonymous_namespace{tagreader.cpp}::TagFileParser Class Reference
Tag file parser.
Public Types
enum State {
Invalid , InClass , InConcept , InFile ,
InNamespace , InGroup , InPage , InMember ,
InEnumValue , InPackage , InDir , InModule ,
InTempArgList
}
Public Member Functions
TagFileParser (const char *tagName)
void setDocumentLocator (const XMLLocator *locator)
void startDocument ()
void startElement (const QCString &name, const XMLHandlers::Attributes &attrib)
void endElement (const QCString &name)
void characters (const QCString &ch)
void error (const QCString &fileName, int lineNr, const QCString &msg)
void dump ()
void buildLists (const std::shared_ptr< Entry > &root)
void addIncludes ()
void startCompound (const XMLHandlers::Attributes &attrib)
void endCompound ()
void startMember (const XMLHandlers::Attributes &attrib)
void endMember ()
void startEnumValue (const XMLHandlers::Attributes &attrib)
void endEnumValue ()
void endDocAnchor ()
void endClass ()
void endConcept ()
void endModule ()
void endNamespace ()
void endFile ()
void endPage ()
void endSubpage ()
void endDir ()
void startStringValue (const XMLHandlers::Attributes &)
void startDocAnchor (const XMLHandlers::Attributes &attrib)
void endType ()
void endName ()
void startBase (const XMLHandlers::Attributes &attrib)
void endBase ()
void startIncludes (const XMLHandlers::Attributes &attrib)
void endIncludes ()
void endTemplateArg ()
void endFilename ()
void endPath ()
void endAnchor ()
void endClangId ()
void endAnchorFile ()
void endArglist ()
void endTitle ()
void endSubgroup ()
void startIgnoreElement (const XMLHandlers::Attributes &)
void endIgnoreElement ()
void buildMemberList (const std::shared_ptr< Entry > &ce, const std::vector< TagMemberInfo > &members)
void addDocAnchors (const std::shared_ptr< Entry > &e, const std::vector< TagAnchorInfo > &l)
Private Member Functions
void p_warn (const char *fmt)
void p_warn (const char *fmt, const char *s)
Private Attributes
std::vector< TagCompoundVariant > m_tagFileCompounds
TagCompoundVariant m_curCompound
TagMemberInfo m_curMember
TagEnumValueInfo m_curEnumValue
TagIncludeInfo m_curIncludes
QCString m_curString
QCString m_tagName
QCString m_fileName
QCString m_title
State m_state = Invalid
std::stack< State > m_stateStack
const XMLLocator * m_locator = nullptr
Detailed Description
Tag file parser.
Reads an XML-structured tagfile and builds up the structure in memory. The method buildLists() is used to transfer/translate the structures to the doxygen engine.
Definition at line 328 of file tagreader.cpp.
Member Enumeration Documentation
State
enum anonymous_namespace{tagreader.cpp}::TagFileParser::State
Enumerator
Invalid
InClass
InConcept
InFile
InNamespace
InGroup
InPage
InMember
InEnumValue
InPackage
InDir
InModule
InTempArgList
Definition at line 984 of file tagreader.cpp.
               { Invalid,
                 InClass,
                 InConcept,
                 InFile,
                 InNamespace,
                 InGroup,
                 InPage,
                 InMember,
                 InEnumValue,
                 InPackage,
                 InDir,
                 InModule,
                 InTempArgList
               };
Constructor & Destructor Documentation
TagFileParser()
anonymous_namespace{tagreader.cpp}::TagFileParser::TagFileParser (const char * tagName) inline explicit
Definition at line 331 of file tagreader.cpp.
: m_tagName(tagName) {}
References m_tagName.
Referenced by parseTagFile().
Member Function Documentation
addDocAnchors()
void anonymous_namespace{tagreader.cpp}::TagFileParser::addDocAnchors (const std::shared_ptr< Entry > & e, const std::vector< TagAnchorInfo > & l)
Definition at line 1357 of file tagreader.cpp.
{
  for (const auto &ta : l)
  {
    if (SectionManager::instance().find(QCString(ta.label))==nullptr)
    {
      //printf("New sectionInfo file=%s anchor=%s\n",
      //    qPrint(ta->fileName),qPrint(ta->label));
      SectionInfo *si=SectionManager::instance().add(
          ta.label,ta.fileName,-1,ta.title,
          SectionType::Anchor,0,m_tagName);
      e->anchors.push_back(si);
    }
    else
    {
      //printf("Replace sectionInfo file=%s anchor=%s\n",
      //    qPrint(ta->fileName),qPrint(ta->label));
      SectionManager::instance().replace(
          ta.label,ta.fileName,-1,ta.title,
          SectionType::Anchor,0,m_tagName);
    }
  }
}
References SectionManager::add(), SectionType::Anchor, SectionManager::instance(), m_tagName, and SectionManager::replace().
Referenced by buildLists(), and buildMemberList().
addIncludes()
void anonymous_namespace{tagreader.cpp}::TagFileParser::addIncludes ()
Definition at line 1764 of file tagreader.cpp.
{
  for (const auto &comp : m_tagFileCompounds)
  {
    const TagFileInfo *tfi = comp.getFileInfo();
    if (tfi)
    {
      //printf("tag file tagName=%s path=%s name=%s\n",qPrint(m_tagName),qPrint(tfi->path),qPrint(tfi->name));
      FileName *fn = Doxygen::inputNameLinkedMap->find(tfi->name);
      if (fn)
      {
        for (const auto &fd : *fn)
        {
          //printf("input file path=%s name=%s\n",qPrint(fd->getPath()),qPrint(fd->name()));
          if (fd->getPath()==QCString(m_tagName+":"+tfi->path))
          {
            //printf("found\n");
            for (const auto &ii : tfi->includes)
            {
              //printf("ii->name='%s'\n",qPrint(ii->name));
              FileName *ifn = Doxygen::inputNameLinkedMap->find(ii.name);
              ASSERT(ifn!=nullptr);
              if (ifn)
              {
                for (const auto &ifd : *ifn)
                {
                  //printf("ifd->getOutputFileBase()=%s ii->id=%s\n",
                  //        qPrint(ifd->getOutputFileBase()),qPrint(ii->id));
                  if (ifd->getOutputFileBase()==QCString(ii.id))
                  {
                    IncludeKind kind = IncludeKind::IncludeSystem;
                    if (ii.isModule)
                    {
                      kind = IncludeKind::ImportModule;
                    }
                    else if (ii.isImported)
                    {
                      kind = ii.isLocal ? IncludeKind::ImportLocal : IncludeKind::ImportSystem;
                    }
                    else if (ii.isLocal)
                    {
                      kind = IncludeKind::IncludeLocal;
                    }
                    fd->addIncludeDependency(ifd.get(),ii.text,kind);
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
References ASSERT, ImportLocal, ImportModule, ImportSystem, IncludeLocal, anonymous_namespace{tagreader.cpp}::TagFileInfo::includes, IncludeSystem, Doxygen::inputNameLinkedMap, m_tagFileCompounds, m_tagName, anonymous_namespace{tagreader.cpp}::TagCompoundInfo::name, and anonymous_namespace{tagreader.cpp}::TagFileInfo::path.
buildLists()
void anonymous_namespace{tagreader.cpp}::TagFileParser::buildLists (const std::shared_ptr< Entry > & root)
Injects the info gathered by the XML parser into the Entry tree. This tree contains the information extracted from the input in a "unrelated" form.
Definition at line 1500 of file tagreader.cpp.
{
  // build class list
  for (const auto &comp : m_tagFileCompounds)
  {
    const TagClassInfo *tci = comp.getClassInfo();
    if (tci)
    {
      std::shared_ptr<Entry> ce = std::make_shared<Entry>();
      ce->section = EntryType::makeClass();
      switch (tci->kind)
      {
        case TagClassInfo::Kind::Class:     break;
        case TagClassInfo::Kind::Struct:    ce->spec = TypeSpecifier().setStruct(true);    break;
        case TagClassInfo::Kind::Union:     ce->spec = TypeSpecifier().setUnion(true);     break;
        case TagClassInfo::Kind::Interface: ce->spec = TypeSpecifier().setInterface(true); break;
        case TagClassInfo::Kind::Enum:      ce->spec = TypeSpecifier().setEnum(true);      break;
        case TagClassInfo::Kind::Exception: ce->spec = TypeSpecifier().setException(true); break;
        case TagClassInfo::Kind::Protocol:  ce->spec = TypeSpecifier().setProtocol(true);  break;
        case TagClassInfo::Kind::Category:  ce->spec = TypeSpecifier().setCategory(true);  break;
        case TagClassInfo::Kind::Service:   ce->spec = TypeSpecifier().setService(true);   break;
        case TagClassInfo::Kind::Singleton: ce->spec = TypeSpecifier().setSingleton(true); break;
        case TagClassInfo::Kind::None:      // should never happen, means not properly initialized
                                      assert(tci->kind != TagClassInfo::Kind::None);
                                      break;
      }
      ce->name     = tci->name;
      if (tci->kind==TagClassInfo::Kind::Protocol)
      {
        ce->name+="-p";
      }
      addDocAnchors(ce,tci->docAnchors);
      ce->tagInfoData.tagName  = m_tagName;
      ce->tagInfoData.anchor   = tci->anchor;
      ce->tagInfoData.fileName = tci->filename;
      ce->startLine            = tci->lineNr;
      ce->fileName             = m_tagName;
      ce->hasTagInfo           = TRUE;
      ce->id                   = tci->clangId;
      ce->lang                 = tci->isObjC ? SrcLangExt::ObjC : SrcLangExt::Unknown;
      // transfer base class list
      ce->extends  = tci->bases;
      if (!tci->templateArguments.empty())
      {
        ArgumentList al;
        for (const auto &argName : tci->templateArguments)
        {
          Argument a;
          a.type = "class";
          a.name = argName.c_str();
          al.push_back(a);
        }
        ce->tArgLists.push_back(al);
      }
      buildMemberList(ce,tci->members);
      root->moveToSubEntryAndKeep(ce);
    }
  }
  // build file list
  for (const auto &comp : m_tagFileCompounds)
  {
    const TagFileInfo *tfi = comp.getFileInfo();
    if (tfi)
    {
      std::shared_ptr<Entry> fe = std::make_shared<Entry>();
      fe->section = guessSection(tfi->name);
      fe->name     = tfi->name;
      addDocAnchors(fe,tfi->docAnchors);
      fe->tagInfoData.tagName  = m_tagName;
      fe->tagInfoData.fileName = tfi->filename;
      fe->hasTagInfo = TRUE;
      QCString fullName = m_tagName+":"+tfi->path+stripPath(tfi->name);
      fe->fileName  = fullName;
      fe->startLine = tfi->lineNr;
      //printf("createFileDef() filename=%s\n",qPrint(tfi->filename));
      QCString tagid = m_tagName+":"+tfi->path;
      auto fd = createFileDef(tagid, tfi->name,m_tagName, tfi->filename);
      FileName *mn = Doxygen::inputNameLinkedMap->find(tfi->name);
      if (mn)
      {
        mn->push_back(std::move(fd));
      }
      else
      {
        mn = Doxygen::inputNameLinkedMap->add(tfi->name,fullName);
        mn->push_back(std::move(fd));
      }
      buildMemberList(fe,tfi->members);
      root->moveToSubEntryAndKeep(fe);
    }
  }
  // build concept list
  for (const auto &comp : m_tagFileCompounds)
  {
    const TagConceptInfo *tci = comp.getConceptInfo();
    if (tci)
    {
      std::shared_ptr<Entry> ce = std::make_shared<Entry>();
      ce->section = EntryType::makeConcept();
      ce->name     = tci->name;
      addDocAnchors(ce,tci->docAnchors);
      ce->tagInfoData.tagName  = m_tagName;
      ce->tagInfoData.fileName = tci->filename;
      ce->startLine   = tci->lineNr;
      ce->fileName    = m_tagName;
      ce->hasTagInfo  = TRUE;
      ce->id       = tci->clangId;
      root->moveToSubEntryAndKeep(ce);
    }
  }
  // build module list
  for (const auto &comp : m_tagFileCompounds)
  {
    const TagModuleInfo *tmi = comp.getModuleInfo();
    if (tmi)
    {
      auto &mm = ModuleManager::instance();
      mm.createModuleDef(tmi->filename,tmi->lineNr,1,true,tmi->name,QCString());
      mm.addTagInfo(tmi->filename,m_tagName,tmi->clangId);
      ModuleDef *mod = mm.getPrimaryInterface(tmi->name);
      if (mod && !tmi->docAnchors.empty())
      {
        std::vector<const SectionInfo *> anchorList;
        for (const auto &ta : tmi->docAnchors)
        {
          if (SectionManager::instance().find(QCString(ta.label))==nullptr)
          {
            //printf("New sectionInfo file=%s anchor=%s\n",
            //    qPrint(ta->fileName),qPrint(ta->label));
            SectionInfo *si=SectionManager::instance().add(
                ta.label,ta.fileName,-1,ta.title,
                SectionType::Anchor,0,m_tagName);
            anchorList.push_back(si);
          }
          else
          {
            p_warn("Duplicate anchor %s found",qPrint(ta.label));
          }
        }
        mod->addSectionsToDefinition(anchorList);
      }
    }
  }
  // build namespace list
  for (const auto &comp : m_tagFileCompounds)
  {
    const TagNamespaceInfo *tni = comp.getNamespaceInfo();
    if (tni)
    {
      std::shared_ptr<Entry> ne = std::make_shared<Entry>();
      ne->section = EntryType::makeNamespace();
      ne->name     = tni->name;
      addDocAnchors(ne,tni->docAnchors);
      ne->tagInfoData.tagName  = m_tagName;
      ne->tagInfoData.fileName = tni->filename;
      ne->startLine   = tni->lineNr;
      ne->fileName    = m_tagName;
      ne->hasTagInfo  = TRUE;
      ne->id       = tni->clangId;
      buildMemberList(ne,tni->members);
      root->moveToSubEntryAndKeep(ne);
    }
  }
  // build package list
  for (const auto &comp : m_tagFileCompounds)
  {
    const TagPackageInfo *tpgi = comp.getPackageInfo();
    if (tpgi)
    {
      std::shared_ptr<Entry> pe = std::make_shared<Entry>();
      pe->section = EntryType::makePackage();
      pe->name     = tpgi->name;
      addDocAnchors(pe,tpgi->docAnchors);
      pe->tagInfoData.tagName  = m_tagName;
      pe->tagInfoData.fileName = tpgi->filename;
      pe->startLine   = tpgi->lineNr;
      pe->fileName    = m_tagName;
      pe->hasTagInfo  = TRUE;
      buildMemberList(pe,tpgi->members);
      root->moveToSubEntryAndKeep(pe);
    }
  }
  // build group list
  for (const auto &comp : m_tagFileCompounds)
  {
    const TagGroupInfo *tgi = comp.getGroupInfo();
    if (tgi)
    {
      std::shared_ptr<Entry> ge = std::make_shared<Entry>();
      ge->section = EntryType::makeGroupDoc();
      ge->name     = tgi->name;
      ge->type     = tgi->title;
      addDocAnchors(ge,tgi->docAnchors);
      ge->tagInfoData.tagName  = m_tagName;
      ge->tagInfoData.fileName = tgi->filename;
      ge->startLine   = tgi->lineNr;
      ge->fileName    = m_tagName;
      ge->hasTagInfo  = TRUE;
      buildMemberList(ge,tgi->members);
      root->moveToSubEntryAndKeep(ge);
    }
  }
  for (const auto &comp : m_tagFileCompounds)
  {
    const TagGroupInfo *tgi = comp.getGroupInfo();
    if (tgi)
    {
      // set subgroup relations bug_774118
      for (const auto &sg : tgi->subgroupList)
      {
        const auto &children = root->children();
        auto i = std::find_if(children.begin(),children.end(),
            [&](const std::shared_ptr<Entry> &e) { return e->name == sg.c_str(); });
        if (i!=children.end())
        {
          (*i)->groups.emplace_back(tgi->name,Grouping::GROUPING_INGROUP);
        }
      }
    }
  }
  // build page list
  for (const auto &comp : m_tagFileCompounds)
  {
    const TagPageInfo *tpi = comp.getPageInfo();
    if (tpi)
    {
      std::shared_ptr<Entry> pe = std::make_shared<Entry>();
      bool isIndex = (stripExtensionGeneral(tpi->filename,getFileNameExtension(tpi->filename))=="index");
      pe->section  = isIndex ? EntryType::makeMainpageDoc() : EntryType::makePageDoc();
      pe->name     = tpi->name;
      pe->args     = tpi->title;
      for (const auto &subpage : tpi->subpages)
      {
        // we add subpage labels as a kind of "inheritance" relation to prevent
        // needing to add another list to the Entry class.
        pe->extends.emplace_back(stripExtension(QCString(subpage)),Protection::Public,Specifier::Normal);
      }
      addDocAnchors(pe,tpi->docAnchors);
      pe->tagInfoData.tagName  = m_tagName;
      pe->tagInfoData.fileName = stripExtension(tpi->filename);
      pe->startLine   = tpi->lineNr;
      pe->fileName    = m_tagName;
      pe->hasTagInfo  = TRUE;
      root->moveToSubEntryAndKeep(pe);
    }
  }
}
References SectionManager::add(), addDocAnchors(), DefinitionMutable::addSectionsToDefinition(), SectionType::Anchor, anonymous_namespace{tagreader.cpp}::TagClassInfo::anchor, anonymous_namespace{tagreader.cpp}::TagClassInfo::bases, buildMemberList(), anonymous_namespace{tagreader.cpp}::TagClassInfo::Category, anonymous_namespace{tagreader.cpp}::TagClassInfo::clangId, anonymous_namespace{tagreader.cpp}::TagConceptInfo::clangId, anonymous_namespace{tagreader.cpp}::TagModuleInfo::clangId, anonymous_namespace{tagreader.cpp}::TagNamespaceInfo::clangId, anonymous_namespace{tagreader.cpp}::TagClassInfo::Class, createFileDef(), anonymous_namespace{tagreader.cpp}::TagCompoundInfo::docAnchors, anonymous_namespace{tagreader.cpp}::TagClassInfo::Enum, anonymous_namespace{tagreader.cpp}::TagClassInfo::Exception, anonymous_namespace{tagreader.cpp}::TagCompoundInfo::filename, getFileNameExtension(), Grouping::GROUPING_INGROUP, guessSection(), Doxygen::inputNameLinkedMap, ModuleManager::instance(), SectionManager::instance(), anonymous_namespace{tagreader.cpp}::TagClassInfo::Interface, anonymous_namespace{tagreader.cpp}::TagClassInfo::isObjC, anonymous_namespace{tagreader.cpp}::TagClassInfo::kind, anonymous_namespace{tagreader.cpp}::TagCompoundInfo::lineNr, m_tagFileCompounds, m_tagName, anonymous_namespace{tagreader.cpp}::TagCompoundInfo::members, anonymous_namespace{tagreader.cpp}::TagCompoundInfo::name, Argument::name, anonymous_namespace{tagreader.cpp}::TagClassInfo::None, Normal, ObjC, p_warn(), anonymous_namespace{tagreader.cpp}::TagFileInfo::path, anonymous_namespace{tagreader.cpp}::TagClassInfo::Protocol, Public, ArgumentList::push_back(), qPrint(), anonymous_namespace{tagreader.cpp}::TagClassInfo::Service, anonymous_namespace{tagreader.cpp}::TagClassInfo::Singleton, stripExtension(), stripExtensionGeneral(), stripPath(), anonymous_namespace{tagreader.cpp}::TagClassInfo::Struct, anonymous_namespace{tagreader.cpp}::TagGroupInfo::subgroupList, anonymous_namespace{tagreader.cpp}::TagPageInfo::subpages, anonymous_namespace{tagreader.cpp}::TagClassInfo::templateArguments, anonymous_namespace{tagreader.cpp}::TagGroupInfo::title, anonymous_namespace{tagreader.cpp}::TagPageInfo::title, TRUE, Argument::type, anonymous_namespace{tagreader.cpp}::TagClassInfo::Union, and Unknown.
buildMemberList()
void anonymous_namespace{tagreader.cpp}::TagFileParser::buildMemberList (const std::shared_ptr< Entry > & ce, const std::vector< TagMemberInfo > & members)
Definition at line 1381 of file tagreader.cpp.
{
  for (const auto &tmi : members)
  {
    std::shared_ptr<Entry> me = std::make_shared<Entry>();
    me->type       = tmi.type;
    me->name       = tmi.name;
    me->args       = tmi.arglist;
    if (!me->args.isEmpty())
    {
      me->argList = *stringToArgumentList(SrcLangExt::Cpp,me->args);
    }
    if (tmi.enumValues.size()>0)
    {
      me->spec.setStrong(true);
      for (const auto &evi : tmi.enumValues)
      {
        std::shared_ptr<Entry> ev = std::make_shared<Entry>();
        ev->type       = "@";
        ev->name       = evi.name;
        ev->id         = evi.clangid;
        ev->section = EntryType::makeVariable();
        ev->tagInfoData.tagName    = m_tagName;
        ev->tagInfoData.anchor     = evi.anchor;
        ev->tagInfoData.fileName   = evi.file;
        ev->hasTagInfo    = TRUE;
        me->moveToSubEntryAndKeep(ev);
      }
    }
    me->protection = tmi.prot;
    me->virt       = tmi.virt;
    me->isStatic   = tmi.isStatic;
    me->fileName   = ce->fileName;
    me->id         = tmi.clangId;
    me->startLine  = tmi.lineNr;
    if (ce->section.isGroupDoc())
    {
      me->groups.emplace_back(ce->name,Grouping::GROUPING_INGROUP);
    }
    addDocAnchors(me,tmi.docAnchors);
    me->tagInfoData.tagName    = m_tagName;
    me->tagInfoData.anchor     = tmi.anchor;
    me->tagInfoData.fileName   = tmi.anchorFile;
    me->hasTagInfo    = TRUE;
    if (tmi.kind=="define")
    {
      me->type="#define";
      me->section = EntryType::makeDefine();
    }
    else if (tmi.kind=="enumvalue")
    {
      me->section = EntryType::makeVariable();
      me->mtype = MethodTypes::Method;
    }
    else if (tmi.kind=="property")
    {
      me->section = EntryType::makeVariable();
      me->mtype = MethodTypes::Property;
    }
    else if (tmi.kind=="event")
    {
      me->section = EntryType::makeVariable();
      me->mtype = MethodTypes::Event;
    }
    else if (tmi.kind=="variable")
    {
      me->section = EntryType::makeVariable();
      me->mtype = MethodTypes::Method;
    }
    else if (tmi.kind=="typedef")
    {
      me->section = EntryType::makeVariable();
      me->type.prepend("typedef ");
      me->mtype = MethodTypes::Method;
    }
    else if (tmi.kind=="enumeration")
    {
      me->section = EntryType::makeEnum();
      me->mtype = MethodTypes::Method;
    }
    else if (tmi.kind=="function")
    {
      me->section = EntryType::makeFunction();
      me->mtype = MethodTypes::Method;
    }
    else if (tmi.kind=="signal")
    {
      me->section = EntryType::makeFunction();
      me->mtype = MethodTypes::Signal;
    }
    else if (tmi.kind=="prototype")
    {
      me->section = EntryType::makeFunction();
      me->mtype = MethodTypes::Method;
    }
    else if (tmi.kind=="friend")
    {
      me->section = EntryType::makeFunction();
      me->type.prepend("friend ");
      me->mtype = MethodTypes::Method;
    }
    else if (tmi.kind=="dcop")
    {
      me->section = EntryType::makeFunction();
      me->mtype = MethodTypes::DCOP;
    }
    else if (tmi.kind=="slot")
    {
      me->section = EntryType::makeFunction();
      me->mtype = MethodTypes::Slot;
    }
    ce->moveToSubEntryAndKeep(me);
  }
}
References addDocAnchors(), Cpp, DCOP, Event, Grouping::GROUPING_INGROUP, m_tagName, Method, Property, Signal, Slot, stringToArgumentList(), and TRUE.
Referenced by buildLists().
characters()
void anonymous_namespace{tagreader.cpp}::TagFileParser::characters (const QCString & ch) inline
Definition at line 345 of file tagreader.cpp.
{ m_curString+=ch; }
References m_curString.
dump()
void anonymous_namespace{tagreader.cpp}::TagFileParser::dump ()
Dumps the internal structures. For debugging only!
Definition at line 1174 of file tagreader.cpp.
{
  Debug::print(Debug::Tag,0,"-------- Results --------\n");
  //============== CLASSES
  for (const auto &comp : m_tagFileCompounds)
  {
    if (comp.type()==TagCompoundVariant::Type::Class)
    {
      const TagClassInfo *cd = comp.getClassInfo();
      Debug::print(Debug::Tag,0,"class '%s'\n",qPrint(cd->name));
      Debug::print(Debug::Tag,0,"  filename '%s'\n",qPrint(cd->filename));
      for (const BaseInfo &bi : cd->bases)
      {
        Debug::print(Debug::Tag,0, "  base: %s \n", bi.name.isEmpty() ? "" : qPrint(bi.name) );
      }
      for (const auto &md : cd->members)
      {
        Debug::print(Debug::Tag,0,"  member:\n");
        Debug::print(Debug::Tag,0,"    kind: '%s'\n",qPrint(md.kind));
        Debug::print(Debug::Tag,0,"    name: '%s'\n",qPrint(md.name));
        Debug::print(Debug::Tag,0,"    anchor: '%s'\n",qPrint(md.anchor));
        Debug::print(Debug::Tag,0,"    arglist: '%s'\n",qPrint(md.arglist));
      }
    }
  }
  //============== CONCEPTS
  for (const auto &comp : m_tagFileCompounds)
  {
    if (comp.type()==TagCompoundVariant::Type::Concept)
    {
      const TagConceptInfo *cd = comp.getConceptInfo();
      Debug::print(Debug::Tag,0,"concept '%s'\n",qPrint(cd->name));
      Debug::print(Debug::Tag,0,"  filename '%s'\n",qPrint(cd->filename));
    }
  }
  //============== MODULES
  for (const auto &comp : m_tagFileCompounds)
  {
    if (comp.type()==TagCompoundVariant::Type::Module)
    {
      const TagModuleInfo *mi = comp.getModuleInfo();
      Debug::print(Debug::Tag,0,"module '%s'\n",qPrint(mi->name));
      Debug::print(Debug::Tag,0,"  filename '%s'\n",qPrint(mi->filename));
    }
  }
  //============== NAMESPACES
  for (const auto &comp : m_tagFileCompounds)
  {
    if (comp.type()==TagCompoundVariant::Type::Namespace)
    {
      const TagNamespaceInfo *nd = comp.getNamespaceInfo();
      Debug::print(Debug::Tag,0,"namespace '%s'\n",qPrint(nd->name));
      Debug::print(Debug::Tag,0,"  filename '%s'\n",qPrint(nd->filename));
      for (const auto &cls : nd->classList)
      {
        Debug::print(Debug::Tag,0, "  class: %s \n", cls.c_str() );
      }
      for (const auto &md : nd->members)
      {
        Debug::print(Debug::Tag,0,"  member:\n");
        Debug::print(Debug::Tag,0,"    kind: '%s'\n",qPrint(md.kind));
        Debug::print(Debug::Tag,0,"    name: '%s'\n",qPrint(md.name));
        Debug::print(Debug::Tag,0,"    anchor: '%s'\n",qPrint(md.anchor));
        Debug::print(Debug::Tag,0,"    arglist: '%s'\n",qPrint(md.arglist));
      }
    }
  }
  //============== FILES
  for (const auto &comp : m_tagFileCompounds)
  {
    if (comp.type()==TagCompoundVariant::Type::File)
    {
      const TagFileInfo *fd = comp.getFileInfo();
      Debug::print(Debug::Tag,0,"file '%s'\n",qPrint(fd->name));
      Debug::print(Debug::Tag,0,"  filename '%s'\n",qPrint(fd->filename));
      for (const auto &ns : fd->namespaceList)
      {
        Debug::print(Debug::Tag,0, "  namespace: %s \n", ns.c_str() );
      }
      for (const auto &cs : fd->classList)
      {
        Debug::print(Debug::Tag,0, "  class: %s \n", cs.c_str() );
      }
      for (const auto &md : fd->members)
      {
        Debug::print(Debug::Tag,0,"  member:\n");
        Debug::print(Debug::Tag,0,"    kind: '%s'\n",qPrint(md.kind));
        Debug::print(Debug::Tag,0,"    name: '%s'\n",qPrint(md.name));
        Debug::print(Debug::Tag,0,"    anchor: '%s'\n",qPrint(md.anchor));
        Debug::print(Debug::Tag,0,"    arglist: '%s'\n",qPrint(md.arglist));
      }
      for (const auto &ii : fd->includes)
      {
        Debug::print(Debug::Tag,0,"  includes id: %s name: %s\n",qPrint(ii.id),qPrint(ii.name));
      }
    }
  }
  //============== GROUPS
  for (const auto &comp : m_tagFileCompounds)
  {
    if (comp.type()==TagCompoundVariant::Type::Group)
    {
      const TagGroupInfo *gd = comp.getGroupInfo();
      Debug::print(Debug::Tag,0,"group '%s'\n",qPrint(gd->name));
      Debug::print(Debug::Tag,0,"  filename '%s'\n",qPrint(gd->filename));
      for (const auto &ns : gd->namespaceList)
      {
        Debug::print(Debug::Tag,0, "  namespace: %s \n", ns.c_str() );
      }
      for (const auto &cs : gd->classList)
      {
        Debug::print(Debug::Tag,0, "  class: %s \n", cs.c_str() );
      }
      for (const auto &fi : gd->fileList)
      {
        Debug::print(Debug::Tag,0, "  file: %s \n", fi.c_str() );
      }
      for (const auto &sg : gd->subgroupList)
      {
        Debug::print(Debug::Tag,0, "  subgroup: %s \n", sg.c_str() );
      }
      for (const auto &pg : gd->pageList)
      {
        Debug::print(Debug::Tag,0, "  page: %s \n", pg.c_str() );
      }
      for (const auto &md : gd->members)
      {
        Debug::print(Debug::Tag,0,"  member:\n");
        Debug::print(Debug::Tag,0,"    kind: '%s'\n",qPrint(md.kind));
        Debug::print(Debug::Tag,0,"    name: '%s'\n",qPrint(md.name));
        Debug::print(Debug::Tag,0,"    anchor: '%s'\n",qPrint(md.anchor));
        Debug::print(Debug::Tag,0,"    arglist: '%s'\n",qPrint(md.arglist));
      }
    }
  }
  //============== PAGES
  for (const auto &comp : m_tagFileCompounds)
  {
    if (comp.type()==TagCompoundVariant::Type::Page)
    {
      const TagPageInfo *pd = comp.getPageInfo();
      Debug::print(Debug::Tag,0,"page '%s'\n",qPrint(pd->name));
      Debug::print(Debug::Tag,0,"  title '%s'\n",qPrint(pd->title));
      Debug::print(Debug::Tag,0,"  filename '%s'\n",qPrint(pd->filename));
    }
  }
  //============== DIRS
  for (const auto &comp : m_tagFileCompounds)
  {
    if (comp.type()==TagCompoundVariant::Type::Dir)
    {
      const TagDirInfo *dd = comp.getDirInfo();
      {
        Debug::print(Debug::Tag,0,"dir '%s'\n",qPrint(dd->name));
        Debug::print(Debug::Tag,0,"  path '%s'\n",qPrint(dd->path));
        for (const auto &fi : dd->fileList)
        {
          Debug::print(Debug::Tag,0, "  file: %s \n", fi.c_str() );
        }
        for (const auto &sd : dd->subdirList)
        {
          Debug::print(Debug::Tag,0, "  subdir: %s \n", sd.c_str() );
        }
      }
    }
  }
  Debug::print(Debug::Tag,0,"-------------------------\n");
}
References anonymous_namespace{tagreader.cpp}::TagClassInfo::bases, anonymous_namespace{tagreader.cpp}::TagCompoundVariant::Class, anonymous_namespace{tagreader.cpp}::TagFileInfo::classList, anonymous_namespace{tagreader.cpp}::TagGroupInfo::classList, anonymous_namespace{tagreader.cpp}::TagNamespaceInfo::classList, anonymous_namespace{tagreader.cpp}::TagCompoundVariant::Concept, anonymous_namespace{tagreader.cpp}::TagCompoundVariant::Dir, anonymous_namespace{tagreader.cpp}::TagCompoundVariant::File, anonymous_namespace{tagreader.cpp}::TagDirInfo::fileList, anonymous_namespace{tagreader.cpp}::TagGroupInfo::fileList, anonymous_namespace{tagreader.cpp}::TagCompoundInfo::filename, anonymous_namespace{tagreader.cpp}::TagCompoundVariant::Group, anonymous_namespace{tagreader.cpp}::TagFileInfo::includes, QCString::isEmpty(), m_tagFileCompounds, anonymous_namespace{tagreader.cpp}::TagCompoundInfo::members, anonymous_namespace{tagreader.cpp}::TagCompoundVariant::Module, anonymous_namespace{tagreader.cpp}::TagCompoundInfo::name, BaseInfo::name, anonymous_namespace{tagreader.cpp}::TagCompoundVariant::Namespace, anonymous_namespace{tagreader.cpp}::TagFileInfo::namespaceList, anonymous_namespace{tagreader.cpp}::TagGroupInfo::namespaceList, anonymous_namespace{tagreader.cpp}::TagCompoundVariant::Page, anonymous_namespace{tagreader.cpp}::TagGroupInfo::pageList, anonymous_namespace{tagreader.cpp}::TagDirInfo::path, Debug::print(), qPrint(), anonymous_namespace{tagreader.cpp}::TagDirInfo::subdirList, anonymous_namespace{tagreader.cpp}::TagGroupInfo::subgroupList, Debug::Tag, and anonymous_namespace{tagreader.cpp}::TagPageInfo::title.
endAnchor()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endAnchor () inline
Definition at line 872 of file tagreader.cpp.
    {
      if (m_state==InMember)
      {
        m_curMember.anchor = m_curString;
      }
      else if (m_state==InClass)
      {
        TagClassInfo *info = m_curCompound.getClassInfo();
        if (info) info->anchor = m_curString;
      }
      else
      {
        p_warn("Unexpected tag 'anchor' found");
      }
    }
References anonymous_namespace{tagreader.cpp}::TagClassInfo::anchor, InClass, InMember, m_curCompound, m_curMember, m_curString, m_state, and p_warn().
endAnchorFile()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endAnchorFile () inline
Definition at line 913 of file tagreader.cpp.
    {
      if (m_state==InMember)
      {
        m_curMember.anchorFile = m_curString;
      }
      else
      {
        p_warn("Unexpected tag 'anchorfile' found");
      }
    }
References InMember, m_curMember, m_curString, m_state, and p_warn().
endArglist()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endArglist () inline
Definition at line 925 of file tagreader.cpp.
    {
      if (m_state==InMember)
      {
        m_curMember.arglist = m_curString;
      }
      else
      {
        p_warn("Unexpected tag 'arglist' found");
      }
    }
References InMember, m_curMember, m_curString, m_state, and p_warn().
endBase()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endBase () inline
Definition at line 774 of file tagreader.cpp.
    {
      TagClassInfo *info = m_curCompound.getClassInfo();
      if (m_state==InClass && info)
      {
        info->bases.back().name = m_curString;
      }
      else
      {
        p_warn("Unexpected tag 'base' found");
      }
    }
References anonymous_namespace{tagreader.cpp}::TagClassInfo::bases, InClass, m_curCompound, m_curString, m_state, and p_warn().
endClangId()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endClangId () inline
Definition at line 889 of file tagreader.cpp.
    {
      if (m_state==InMember)
      {
        m_curMember.clangId = m_curString;
      }
      else if (m_state==InClass)
      {
        TagClassInfo *info = m_curCompound.getClassInfo();
        if (info) info->clangId =  m_curString;
      }
      else if (m_state==InNamespace)
      {
        TagNamespaceInfo *info = m_curCompound.getNamespaceInfo();
        if (info) info->clangId = m_curString;
      }
      else
      {
        p_warn("Unexpected tag 'clangid' found");
      }
    }
References anonymous_namespace{tagreader.cpp}::TagClassInfo::clangId, anonymous_namespace{tagreader.cpp}::TagNamespaceInfo::clangId, InClass, InMember, InNamespace, m_curCompound, m_curMember, m_curString, m_state, and p_warn().
endClass()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endClass () inline
Definition at line 511 of file tagreader.cpp.
    {
      switch(m_state)
      {
        case InClass:
          {
            TagClassInfo *info = m_curCompound.getClassInfo();
            if (info) info->classList.push_back(m_curString.str());
          }
          break;
        case InFile:
          {
            TagFileInfo *info = m_curCompound.getFileInfo();
            if (info) info->classList.push_back(m_curString.str());
          }
          break;
        case InNamespace:
          {
            TagNamespaceInfo *info = m_curCompound.getNamespaceInfo();
            if (info) info->classList.push_back(m_curString.str());
          }
          break;
        case InGroup:
          {
            TagGroupInfo *info = m_curCompound.getGroupInfo();
            if (info) info->classList.push_back(m_curString.str());
          }
          break;
        case InPackage:
          {
            TagPackageInfo *info = m_curCompound.getPackageInfo();
            if (info) info->classList.push_back(m_curString.str());
          }
          break;
        default:
          p_warn("Unexpected tag 'class' found");
          break;
      }
    }
References anonymous_namespace{tagreader.cpp}::TagClassInfo::classList, anonymous_namespace{tagreader.cpp}::TagFileInfo::classList, anonymous_namespace{tagreader.cpp}::TagGroupInfo::classList, anonymous_namespace{tagreader.cpp}::TagNamespaceInfo::classList, anonymous_namespace{tagreader.cpp}::TagPackageInfo::classList, InClass, InFile, InGroup, InNamespace, InPackage, m_curCompound, m_curString, m_state, and p_warn().
endCompound()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endCompound () inline
Definition at line 356 of file tagreader.cpp.
    {
      switch (m_state)
      {
        case InClass:
        case InConcept:
        case InFile:
        case InNamespace:
        case InGroup:
        case InPage:
        case InDir:
        case InModule:
        case InPackage:
          m_tagFileCompounds.push_back(std::move(m_curCompound));
          break;
        default:
          p_warn("tag 'compound' was not expected!");
          break;
      }
    }
References InClass, InConcept, InDir, InFile, InGroup, InModule, InNamespace, InPackage, InPage, m_curCompound, m_state, m_tagFileCompounds, and p_warn().
endConcept()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endConcept () inline
Definition at line 551 of file tagreader.cpp.
    {
      switch(m_state)
      {
        case InNamespace:
          {
            TagNamespaceInfo *info = m_curCompound.getNamespaceInfo();
            if (info) info->conceptList.push_back(m_curString.str());
          }
          break;
        case InFile:
          {
            TagFileInfo *info = m_curCompound.getFileInfo();
            if (info) info->conceptList.push_back(m_curString.str());
          }
          break;
        case InGroup:
          {
            TagGroupInfo *info = m_curCompound.getGroupInfo();
            if (info) info->conceptList.push_back(m_curString.str());
          }
          break;
        default:
          p_warn("Unexpected tag 'concept' found");
          break;
      }
    }
References anonymous_namespace{tagreader.cpp}::TagFileInfo::conceptList, anonymous_namespace{tagreader.cpp}::TagGroupInfo::conceptList, anonymous_namespace{tagreader.cpp}::TagNamespaceInfo::conceptList, InFile, InGroup, InNamespace, m_curCompound, m_curString, m_state, and p_warn().
endDir()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endDir () inline
Definition at line 677 of file tagreader.cpp.
    {
      switch(m_state)
      {
        case InDir:
          {
            TagDirInfo *info = m_curCompound.getDirInfo();
            if (info) info->subdirList.push_back(m_curString.str());
          }
          break;
        default:
          p_warn("Unexpected tag 'dir' found");
          break;
      }
    }
References InDir, m_curCompound, m_curString, m_state, p_warn(), and anonymous_namespace{tagreader.cpp}::TagDirInfo::subdirList.
endDocAnchor()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endDocAnchor () inline
Definition at line 464 of file tagreader.cpp.
    {
      // Check whether or not the tag is automatically generate, in that case ignore the tag.
      switch(m_state)
      {
        case InClass:
        case InConcept:
        case InFile:
        case InNamespace:
        case InGroup:
        case InPage:
        case InMember:
        case InPackage:
        case InDir:
        case InModule:
          if (AnchorGenerator::looksGenerated(m_curString.str())) return;
          break;
        default:
          p_warn("Unexpected tag 'docanchor' found");
          return;
      }
      switch(m_state)
      {
        case InClass:
        case InConcept:
        case InFile:
        case InNamespace:
        case InGroup:
        case InPage:
        case InPackage:
        case InDir:
        case InModule:
          {
            TagCompoundInfo *info = m_curCompound.getCompoundInfo();
            if (info)
            {
              info->docAnchors.emplace_back(m_fileName,m_curString,m_title);
            }
          }
          break;
        case InMember:
          m_curMember.docAnchors.emplace_back(m_fileName,m_curString,m_title);
          break;
        default: break; // will not be reached
      }
    }
References anonymous_namespace{tagreader.cpp}::TagCompoundInfo::docAnchors, InClass, InConcept, InDir, InFile, InGroup, InMember, InModule, InNamespace, InPackage, InPage, AnchorGenerator::looksGenerated(), m_curCompound, m_curMember, m_curString, m_fileName, m_state, m_title, and p_warn().
endElement()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endElement (const QCString & name)
Definition at line 1132 of file tagreader.cpp.
{
  //printf("endElement '%s'\n",qPrint(name));
  auto it = g_elementHandlers.find(name.str());
  if (it!=std::end(g_elementHandlers))
  {
    it->second.endCb(*this);
  }
  else
  {
    p_warn("Unknown end tag '%s' found!",qPrint(name));
  }
}
References anonymous_namespace{tagreader.cpp}::g_elementHandlers, p_warn(), qPrint(), and QCString::str().
endEnumValue()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endEnumValue () inline
Definition at line 452 of file tagreader.cpp.
    {
      m_curEnumValue.name = QCString(m_curString).stripWhiteSpace().str();
      m_state = m_stateStack.top();
      m_stateStack.pop();
      if (m_state==InMember)
      {
        m_curMember.enumValues.push_back(m_curEnumValue);
        m_curEnumValue=TagEnumValueInfo();
      }
    }
References InMember, m_curEnumValue, m_curMember, m_curString, m_state, and m_stateStack.
endFile()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endFile () inline
Definition at line 623 of file tagreader.cpp.
    {
      switch(m_state)
      {
        case InGroup:
          {
            TagGroupInfo *info = m_curCompound.getGroupInfo();
            if (info) info->fileList.push_back(m_curString.str());
          }
          break;
        case InDir:
          {
            TagDirInfo *info = m_curCompound.getDirInfo();
            if (info) info->fileList.push_back(m_curString.str());
          }
          break;
        default:
          p_warn("Unexpected tag 'file' found");
          break;
      }
    }
References anonymous_namespace{tagreader.cpp}::TagDirInfo::fileList, anonymous_namespace{tagreader.cpp}::TagGroupInfo::fileList, InDir, InGroup, m_curCompound, m_curString, m_state, and p_warn().
endFilename()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endFilename () inline
Definition at line 826 of file tagreader.cpp.
    {
      switch (m_state)
      {
        case InClass:
        case InConcept:
        case InNamespace:
        case InFile:
        case InGroup:
        case InPage:
        case InPackage:
        case InDir:
        case InModule:
          {
            TagCompoundInfo *info = m_curCompound.getCompoundInfo();
            if (info) info->filename = m_curString;
          }
          break;
        default:
          p_warn("Unexpected tag 'filename' found");
          break;
      }
    }
References anonymous_namespace{tagreader.cpp}::TagCompoundInfo::filename, InClass, InConcept, InDir, InFile, InGroup, InModule, InNamespace, InPackage, InPage, m_curCompound, m_curString, m_state, and p_warn().
endIgnoreElement()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endIgnoreElement () inline
Definition at line 976 of file tagreader.cpp.
    {
    }
endIncludes()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endIncludes () inline
Definition at line 799 of file tagreader.cpp.
    {
      m_curIncludes.text = m_curString;
      TagFileInfo *info = m_curCompound.getFileInfo();
      if (m_state==InFile && info)
      {
        info->includes.push_back(m_curIncludes);
      }
      else
      {
        p_warn("Unexpected tag 'includes' found");
      }
    }
References anonymous_namespace{tagreader.cpp}::TagFileInfo::includes, InFile, m_curCompound, m_curIncludes, m_curString, m_state, and p_warn().
endMember()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endMember () inline
Definition at line 409 of file tagreader.cpp.
    {
      m_state = m_stateStack.top();
      m_stateStack.pop();
      switch(m_state)
      {
        case InClass:
        case InFile:
        case InNamespace:
        case InGroup:
        case InPackage:
          {
            TagCompoundInfo *info = m_curCompound.getCompoundInfo();
            if (info)
            {
              info->members.push_back(m_curMember);
            }
          }
          break;
        default:
          p_warn("Unexpected tag 'member' found");
          break;
      }
    }
References InClass, InFile, InGroup, InNamespace, InPackage, m_curCompound, m_curMember, m_state, m_stateStack, anonymous_namespace{tagreader.cpp}::TagCompoundInfo::members, and p_warn().
endModule()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endModule () inline
Definition at line 579 of file tagreader.cpp.
    {
      switch(m_state)
      {
        case InGroup:
          {
            TagGroupInfo *info = m_curCompound.getGroupInfo();
            if (info) info->moduleList.push_back(m_curString.str());
          }
          break;
        default:
          p_warn("Unexpected tag 'module' found");
          break;
      }
    }
References InGroup, m_curCompound, m_curString, m_state, anonymous_namespace{tagreader.cpp}::TagGroupInfo::moduleList, and p_warn().
endName()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endName () inline
Definition at line 717 of file tagreader.cpp.
    {
      switch (m_state)
      {
        case InClass:
        case InConcept:
        case InFile:
        case InNamespace:
        case InGroup:
        case InPage:
        case InDir:
        case InPackage:
        case InModule:
          {
            TagCompoundInfo *info = m_curCompound.getCompoundInfo();
            if (info) info->name = m_curString;
          }
          break;
        case InMember:
          m_curMember.name = m_curString;
          break;
        default:
          p_warn("Unexpected tag 'name' found");
          break;
      }
    }
References InClass, InConcept, InDir, InFile, InGroup, InMember, InModule, InNamespace, InPackage, InPage, m_curCompound, m_curMember, m_curString, m_state, anonymous_namespace{tagreader.cpp}::TagCompoundInfo::name, and p_warn().
endNamespace()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endNamespace () inline
Definition at line 595 of file tagreader.cpp.
    {
      switch(m_state)
      {
        case InNamespace:
          {
            TagNamespaceInfo *info = m_curCompound.getNamespaceInfo();
            if (info) info->namespaceList.push_back(m_curString.str());
          }
          break;
        case InFile:
          {
            TagFileInfo *info = m_curCompound.getFileInfo();
            if (info) info->namespaceList.push_back(m_curString.str());
          }
          break;
        case InGroup:
          {
            TagGroupInfo *info = m_curCompound.getGroupInfo();
            if (info) info->namespaceList.push_back(m_curString.str());
          }
          break;
        default:
          p_warn("Unexpected tag 'namespace' found");
          break;
      }
    }
References InFile, InGroup, InNamespace, m_curCompound, m_curString, m_state, anonymous_namespace{tagreader.cpp}::TagFileInfo::namespaceList, anonymous_namespace{tagreader.cpp}::TagGroupInfo::namespaceList, anonymous_namespace{tagreader.cpp}::TagNamespaceInfo::namespaceList, and p_warn().
endPage()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endPage () inline
Definition at line 645 of file tagreader.cpp.
    {
      switch(m_state)
      {
        case InGroup:
          {
            TagGroupInfo *info = m_curCompound.getGroupInfo();
            if (info) info->fileList.push_back(m_curString.str());
          }
          break;
        default:
          p_warn("Unexpected tag 'page' found");
          break;
      }
    }
References anonymous_namespace{tagreader.cpp}::TagGroupInfo::fileList, InGroup, m_curCompound, m_curString, m_state, and p_warn().
endPath()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endPath () inline
Definition at line 850 of file tagreader.cpp.
    {
      switch (m_state)
      {
        case InFile:
          {
            TagFileInfo *info = m_curCompound.getFileInfo();
            if (info) info->path = m_curString;
          }
          break;
        case InDir:
          {
            TagDirInfo *info = m_curCompound.getDirInfo();
            if (info) info->path = m_curString;
          }
          break;
        default:
          p_warn("Unexpected tag 'path' found");
          break;
      }
    }
References InDir, InFile, m_curCompound, m_curString, m_state, p_warn(), anonymous_namespace{tagreader.cpp}::TagDirInfo::path, and anonymous_namespace{tagreader.cpp}::TagFileInfo::path.
endSubgroup()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endSubgroup () inline
Definition at line 959 of file tagreader.cpp.
    {
      if (m_state==InGroup)
      {
        TagGroupInfo *info = m_curCompound.getGroupInfo();
        if (info) info->subgroupList.push_back(m_curString.str());
      }
      else
      {
        p_warn("Unexpected tag 'subgroup' found");
      }
    }
References InGroup, m_curCompound, m_curString, m_state, p_warn(), and anonymous_namespace{tagreader.cpp}::TagGroupInfo::subgroupList.
endSubpage()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endSubpage () inline
Definition at line 661 of file tagreader.cpp.
    {
      switch(m_state)
      {
        case InPage:
          {
            TagPageInfo *info = m_curCompound.getPageInfo();
            if (info) info->subpages.push_back(m_curString.str());
          }
          break;
        default:
          p_warn("Unexpected tag 'subpage' found");
          break;
      }
    }
References InPage, m_curCompound, m_curString, m_state, p_warn(), and anonymous_namespace{tagreader.cpp}::TagPageInfo::subpages.
endTemplateArg()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endTemplateArg () inline
Definition at line 813 of file tagreader.cpp.
    {
      TagClassInfo *info = m_curCompound.getClassInfo();
      if (m_state==InClass && info)
      {
        info->templateArguments.push_back(m_curString.str());
      }
      else
      {
        p_warn("Unexpected tag 'templarg' found");
      }
    }
References InClass, m_curCompound, m_curString, m_state, p_warn(), and anonymous_namespace{tagreader.cpp}::TagClassInfo::templateArguments.
endTitle()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endTitle () inline
Definition at line 937 of file tagreader.cpp.
    {
      switch (m_state)
      {
        case InGroup:
          {
            TagGroupInfo *info = m_curCompound.getGroupInfo();
            if (info) info->title = m_curString;
          }
          break;
        case InPage:
          {
            TagPageInfo *info = m_curCompound.getPageInfo();
            if (info) info->title = m_curString;
          }
          break;
        default:
          p_warn("Unexpected tag 'title' found");
          break;
      }
    }
References InGroup, InPage, m_curCompound, m_curString, m_state, p_warn(), anonymous_namespace{tagreader.cpp}::TagGroupInfo::title, and anonymous_namespace{tagreader.cpp}::TagPageInfo::title.
endType()
void anonymous_namespace{tagreader.cpp}::TagFileParser::endType () inline
Definition at line 705 of file tagreader.cpp.
    {
      if (m_state==InMember)
      {
        m_curMember.type = m_curString;
      }
      else
      {
        p_warn("Unexpected tag 'type' found");
      }
    }
References InMember, m_curMember, m_curString, m_state, and p_warn().
error()
void anonymous_namespace{tagreader.cpp}::TagFileParser::error (const QCString & fileName, int lineNr, const QCString & msg) inline
Definition at line 346 of file tagreader.cpp.
    {
      ::warn_(fileName,lineNr,"%s",qPrint(msg));
    }
References msg(), qPrint(), and warn_().
p_warn() [1/2]
void anonymous_namespace{tagreader.cpp}::TagFileParser::p_warn (const char * fmt) inline private
Definition at line 1000 of file tagreader.cpp.
    {
      QCString fileName = m_locator->fileName();
      ::warn_(fileName,m_locator->lineNr(),"%s", fmt);
    }
References m_locator, and warn_().
Referenced by buildLists(), endAnchor(), endAnchorFile(), endArglist(), endBase(), endClangId(), endClass(), endCompound(), endConcept(), endDir(), endDocAnchor(), endElement(), endFile(), endFilename(), endIncludes(), endMember(), endModule(), endName(), endNamespace(), endPage(), endPath(), endSubgroup(), endSubpage(), endTemplateArg(), endTitle(), endType(), startBase(), startCompound(), startElement(), and startEnumValue().
p_warn() [2/2]
void anonymous_namespace{tagreader.cpp}::TagFileParser::p_warn (const char * fmt, const char * s) inline private
Definition at line 1006 of file tagreader.cpp.
    {
      QCString fileName = m_locator->fileName();
      ::warn_(fileName,m_locator->lineNr(),fmt,s);
    }
References m_locator, and warn_().
setDocumentLocator()
void anonymous_namespace{tagreader.cpp}::TagFileParser::setDocumentLocator (const XMLLocator * locator) inline
Definition at line 333 of file tagreader.cpp.
    {
      m_locator = locator;
    }
References m_locator.
startBase()
void anonymous_namespace{tagreader.cpp}::TagFileParser::startBase (const XMLHandlers::Attributes & attrib) inline
Definition at line 744 of file tagreader.cpp.
    {
      m_curString="";
      TagClassInfo *info = m_curCompound.getClassInfo();
      if (m_state==InClass && info)
      {
        QCString protStr = XMLHandlers::value(attrib,"protection");
        QCString virtStr = XMLHandlers::value(attrib,"virtualness");
        Protection prot = Protection::Public;
        Specifier  virt = Specifier::Normal;
        if (protStr=="protected")
        {
          prot = Protection::Protected;
        }
        else if (protStr=="private")
        {
          prot = Protection::Private;
        }
        if (virtStr=="virtual")
        {
          virt = Specifier::Virtual;
        }
        info->bases.emplace_back(m_curString,prot,virt);
      }
      else
      {
        p_warn("Unexpected tag 'base' found");
      }
    }
References anonymous_namespace{tagreader.cpp}::TagClassInfo::bases, InClass, m_curCompound, m_curString, m_state, Normal, p_warn(), Private, Protected, Public, XMLHandlers::value(), and Virtual.
startCompound()
void anonymous_namespace{tagreader.cpp}::TagFileParser::startCompound (const XMLHandlers::Attributes & attrib)
Definition at line 1146 of file tagreader.cpp.
{
  m_curString = "";
  std::string kind   = XMLHandlers::value(attrib,"kind");
  std::string isObjC = XMLHandlers::value(attrib,"objc");
  auto it = g_compoundFactory.find(kind);
  if (it!=g_compoundFactory.end())
  {
    m_curCompound = it->second.make_instance();
    m_state       = it->second.state;
    TagCompoundInfo *info = m_curCompound.getCompoundInfo();
    if (info) info->lineNr = m_locator->lineNr();
  }
  else
  {
    p_warn("Unknown compound attribute '%s' found!",kind.c_str());
    m_state = Invalid;
  }
  TagClassInfo *classInfo = m_curCompound.getClassInfo();
  if (isObjC=="yes" && classInfo)
  {
    classInfo->isObjC = TRUE;
  }
}
References anonymous_namespace{tagreader.cpp}::g_compoundFactory, Invalid, anonymous_namespace{tagreader.cpp}::TagClassInfo::isObjC, anonymous_namespace{tagreader.cpp}::TagCompoundInfo::lineNr, m_curCompound, m_curString, m_locator, m_state, p_warn(), TRUE, and XMLHandlers::value().
startDocAnchor()
void anonymous_namespace{tagreader.cpp}::TagFileParser::startDocAnchor (const XMLHandlers::Attributes & attrib) inline
Definition at line 698 of file tagreader.cpp.
    {
      m_fileName  = XMLHandlers::value(attrib,"file");
      m_title     = XMLHandlers::value(attrib,"title");
      m_curString = "";
    }
References m_curString, m_fileName, m_title, and XMLHandlers::value().
startDocument()
void anonymous_namespace{tagreader.cpp}::TagFileParser::startDocument () inline
Definition at line 338 of file tagreader.cpp.
    {
      m_state = Invalid;
    }
References Invalid, and m_state.
startElement()
void anonymous_namespace{tagreader.cpp}::TagFileParser::startElement (const QCString & name, const XMLHandlers::Attributes & attrib)
Definition at line 1118 of file tagreader.cpp.
{
  //printf("startElement '%s'\n",qPrint(name));
  auto it = g_elementHandlers.find(name.str());
  if (it!=std::end(g_elementHandlers))
  {
    it->second.startCb(*this,attrib);
  }
  else
  {
    p_warn("Unknown start tag '%s' found!",qPrint(name));
  }
}
References anonymous_namespace{tagreader.cpp}::g_elementHandlers, p_warn(), qPrint(), and QCString::str().
startEnumValue()
void anonymous_namespace{tagreader.cpp}::TagFileParser::startEnumValue (const XMLHandlers::Attributes & attrib) inline
Definition at line 434 of file tagreader.cpp.
    {
      if (m_state==InMember)
      {
        m_curString = "";
        m_curEnumValue = TagEnumValueInfo();
        m_curEnumValue.file    = XMLHandlers::value(attrib,"file");
        m_curEnumValue.anchor  = XMLHandlers::value(attrib,"anchor");
        m_curEnumValue.clangid = XMLHandlers::value(attrib,"clangid");
        m_stateStack.push(m_state);
        m_state = InEnumValue;
      }
      else
      {
        p_warn("Found 'enumvalue' tag outside of member tag");
      }
    }
References InEnumValue, InMember, m_curEnumValue, m_curString, m_state, m_stateStack, p_warn(), and XMLHandlers::value().
startIgnoreElement()
void anonymous_namespace{tagreader.cpp}::TagFileParser::startIgnoreElement (const XMLHandlers::Attributes &) inline
Definition at line 972 of file tagreader.cpp.
    {
    }
startIncludes()
void anonymous_namespace{tagreader.cpp}::TagFileParser::startIncludes (const XMLHandlers::Attributes & attrib) inline
Definition at line 787 of file tagreader.cpp.
    {
      m_curIncludes = TagIncludeInfo();
      m_curIncludes.id         = XMLHandlers::value(attrib,"id");
      m_curIncludes.name       = XMLHandlers::value(attrib,"name");
      m_curIncludes.isLocal    = XMLHandlers::value(attrib,"local")=="yes";
      m_curIncludes.isImported = XMLHandlers::value(attrib,"imported")=="yes";
      m_curIncludes.isModule   = XMLHandlers::value(attrib,"module")=="yes";
      m_curIncludes.isObjC     = XMLHandlers::value(attrib,"objc")=="yes";
      m_curString="";
    }
References m_curIncludes, m_curString, and XMLHandlers::value().
startMember()
void anonymous_namespace{tagreader.cpp}::TagFileParser::startMember (const XMLHandlers::Attributes & attrib) inline
Definition at line 377 of file tagreader.cpp.
    {
      m_curMember = TagMemberInfo();
      m_curMember.kind   = XMLHandlers::value(attrib,"kind");
      QCString protStr   = XMLHandlers::value(attrib,"protection");
      QCString virtStr   = XMLHandlers::value(attrib,"virtualness");
      QCString staticStr = XMLHandlers::value(attrib,"static");
      m_curMember.lineNr = m_locator->lineNr();
      if (protStr=="protected")
      {
        m_curMember.prot = Protection::Protected;
      }
      else if (protStr=="private")
      {
        m_curMember.prot = Protection::Private;
      }
      if (virtStr=="virtual")
      {
        m_curMember.virt = Specifier::Virtual;
      }
      else if (virtStr=="pure")
      {
        m_curMember.virt = Specifier::Pure;
      }
      if (staticStr=="yes")
      {
        m_curMember.isStatic = TRUE;
      }
      m_stateStack.push(m_state);
      m_state = InMember;
    }
References InMember, m_curMember, m_locator, m_state, m_stateStack, Private, Protected, Pure, TRUE, XMLHandlers::value(), and Virtual.
startStringValue()
void anonymous_namespace{tagreader.cpp}::TagFileParser::startStringValue (const XMLHandlers::Attributes &) inline
Definition at line 693 of file tagreader.cpp.
    {
      m_curString = "";
    }
References m_curString.
Member Data Documentation
m_curCompound
TagCompoundVariant anonymous_namespace{tagreader.cpp}::TagFileParser::m_curCompound private
Definition at line 1016 of file tagreader.cpp.
Referenced by endAnchor(), endBase(), endClangId(), endClass(), endCompound(), endConcept(), endDir(), endDocAnchor(), endFile(), endFilename(), endIncludes(), endMember(), endModule(), endName(), endNamespace(), endPage(), endPath(), endSubgroup(), endSubpage(), endTemplateArg(), endTitle(), startBase(), and startCompound().
m_curEnumValue
TagEnumValueInfo anonymous_namespace{tagreader.cpp}::TagFileParser::m_curEnumValue private
Definition at line 1019 of file tagreader.cpp.
Referenced by endEnumValue(), and startEnumValue().
m_curIncludes
TagIncludeInfo anonymous_namespace{tagreader.cpp}::TagFileParser::m_curIncludes private
Definition at line 1020 of file tagreader.cpp.
Referenced by endIncludes(), and startIncludes().
m_curMember
TagMemberInfo anonymous_namespace{tagreader.cpp}::TagFileParser::m_curMember private
Definition at line 1018 of file tagreader.cpp.
Referenced by endAnchor(), endAnchorFile(), endArglist(), endClangId(), endDocAnchor(), endEnumValue(), endMember(), endName(), endType(), and startMember().
m_curString
QCString anonymous_namespace{tagreader.cpp}::TagFileParser::m_curString private
Definition at line 1022 of file tagreader.cpp.
Referenced by characters(), endAnchor(), endAnchorFile(), endArglist(), endBase(), endClangId(), endClass(), endConcept(), endDir(), endDocAnchor(), endEnumValue(), endFile(), endFilename(), endIncludes(), endModule(), endName(), endNamespace(), endPage(), endPath(), endSubgroup(), endSubpage(), endTemplateArg(), endTitle(), endType(), startBase(), startCompound(), startDocAnchor(), startEnumValue(), startIncludes(), and startStringValue().
m_fileName
QCString anonymous_namespace{tagreader.cpp}::TagFileParser::m_fileName private
Definition at line 1024 of file tagreader.cpp.
Referenced by endDocAnchor(), and startDocAnchor().
m_locator
const XMLLocator* anonymous_namespace{tagreader.cpp}::TagFileParser::m_locator = nullptr private
Definition at line 1028 of file tagreader.cpp.
Referenced by p_warn(), p_warn(), setDocumentLocator(), startCompound(), and startMember().
m_state
State anonymous_namespace{tagreader.cpp}::TagFileParser::m_state = Invalid private
Definition at line 1026 of file tagreader.cpp.
Referenced by endAnchor(), endAnchorFile(), endArglist(), endBase(), endClangId(), endClass(), endCompound(), endConcept(), endDir(), endDocAnchor(), endEnumValue(), endFile(), endFilename(), endIncludes(), endMember(), endModule(), endName(), endNamespace(), endPage(), endPath(), endSubgroup(), endSubpage(), endTemplateArg(), endTitle(), endType(), startBase(), startCompound(), startDocument(), startEnumValue(), and startMember().
m_stateStack
std::stack<State> anonymous_namespace{tagreader.cpp}::TagFileParser::m_stateStack private
Definition at line 1027 of file tagreader.cpp.
Referenced by endEnumValue(), endMember(), startEnumValue(), and startMember().
m_tagFileCompounds
std::vector< TagCompoundVariant > anonymous_namespace{tagreader.cpp}::TagFileParser::m_tagFileCompounds private
Definition at line 1015 of file tagreader.cpp.
Referenced by addIncludes(), buildLists(), dump(), and endCompound().
m_tagName
QCString anonymous_namespace{tagreader.cpp}::TagFileParser::m_tagName private
Definition at line 1023 of file tagreader.cpp.
Referenced by addDocAnchors(), addIncludes(), buildLists(), buildMemberList(), and TagFileParser().
m_title
QCString anonymous_namespace{tagreader.cpp}::TagFileParser::m_title private
Definition at line 1025 of file tagreader.cpp.
Referenced by endDocAnchor(), and startDocAnchor().
The documentation for this class was generated from the following file:
src/tagreader.cpp